### ISSUE TITLE
Better syntax for package imports

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#10018]
From the day that Kasper introduced &quot;package:&quot;, he has suggested we should add a better syntax for it, but it seems there is no actual bug for this. So here it is.

Looking at the world's external Dart code (i.e. all packages available on pub), I see:
- 25125 &quot;package:&quot; imports
- 19545 &quot;dart:&quot; imports
- 19478 other imports (presumably relative URLs)
- 64148 total imports

In other words, &quot;package:&quot; imports are the most common form of importing Dart code. The current syntax for importing, say, unittest's main library looks:

import &quot;package:unittest/unittest.dart&quot;;

This is painfully long for what is the most common way to reference a Dart library. &quot;package&quot; is long. &quot;unittest&quot; is mentioned twice. The &quot;.dart&quot; is unnecessary. The quotes aren't needed because package names and the libraries they contain are restricted to valid Dart identifiers.

Better syntax for package imports can be added in a backwards-compatible way after 1.0.

**Comment by jmesserly** [comment]
this would still be nice :)

**Comment by davidmorgan** [comment]
+1

**Comment by mit-mit** [comment]
Closing as a duplicate of https://github.com/dart-lang/language/issues/649
