### ISSUE TITLE
dart2js checked mode failures in drt after dart:typeddata

### ISSUE THREAD

**Issue by madsager** [dart-lang/sdk#10097]
FAILED: dart2js-drt-checked release_ia32 html/postmessage_structured_test/typed_arrays
FAILED: dart2js-drt-checked release_ia32 html/postmessage_structured_test/primitives

In both cases:

ERROR   Uncaught error: type 'Uint8Array' is not a subtype of type 'ByteBuffer'

**Comment by matanlurey** [comment]
Checked mode is gone.
