### ISSUE TITLE
html/dom_isolates_test failing on IE after typed data landed in dart2js

### ISSUE THREAD

**Issue by madsager** [dart-lang/sdk#10098]
FAILED: dart2js-ie9 release_ia32 html/dom_isolates_test
Expected: pass 
Actual: fail

stdout:

&nbsp;&nbsp;&lt;h1&gt; Running /E:/b/build/slave/dart2js-ie9-win7-all-6-6/build/dart/tests/html/dom_isolates_test.dart &lt;/h1&gt;
&nbsp;&nbsp;&lt;script type=&quot;text/javascript&quot; src=&quot;/root_dart/pkg/unittest/lib/test_controller.js&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script onerror=&quot;externalError(null)&quot; type=&quot;text/javascript&quot; src=&quot;/root_build/generated_tests/dart2js-ie9/tests_html_dom_isolates_test/test.js&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script type=&quot;text/javascript&quot; src=&quot;/root_dart/pkg/browser/lib/dart.js&quot;&gt;&lt;/script&gt;

&lt;pre&gt;Error: 

http://127.0.0.1:51296/root_build/generated_tests/dart2js-ie9/tests_html_dom_isolates_test/test.js:5946:
Object doesn't support property or method 'then$1'

&lt;/pre&gt;&lt;pre&gt;FAIL&lt;/pre&gt;&lt;pre&gt;FAIL&lt;/pre&gt;

To retest, run:  E:\b\build\slave\dart2js-ie9-win7-all-6-6\build\dart\tools\testing\bin\windows\dart.exe /E:/b/build/slave/dart2js-ie9-win7-all-6-6/build/dart/tools/testing/dart/http_server.dart -p 51296 -c 51297 --build-directory=E:\b\build\slave\dart2js-ie9-win7-all-6-6\build\dart\build\ReleaseIA32

Compilation command: build\ReleaseIA32\dart-sdk\bin\dart2js.bat &quot;--package-root=build/ReleaseIA32/packages/&quot; &quot;--out=E:/b/build/slave/dart2js-ie9-win7-all-6-6/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/tests_html_dom_isolates_test/test.js&quot; &quot;/E:/b/build/slave/dart2js-ie9-win7-all-6-6/build/dart/tests/html/dom_isolates_test.dart&quot;

Command line: python &quot;E:\b\build\slave\dart2js-ie9-win7-all-6-6\build\dart\tools\testing\run_selenium.py&quot; &quot;--browser=ie9&quot; &quot;--timeout=240&quot; &quot;--out=http://127.0.0.1:51296/root_build/generated_tests/dart2js-ie9/tests_html_dom_isolates_test/test.html?crossOriginPort=51297&quot;

**Comment by rakudrama** [comment]
dart2js does not support IE9
