### ISSUE TITLE
dart2js: non-optimized interceptors - lack of control flow constant folding

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#10103]
-------- TEST input
import 'dart:html';
main() {
&nbsp;&nbsp;var c = new CanvasElement(width: 800, height: 600);
&nbsp;&nbsp;if (c is !CanvasElement) return;
&nbsp;&nbsp;var ctx = c.context2D;
&nbsp;&nbsp;print(ctx);
}

-------- constructor
&nbsp;&nbsp;factory CanvasElement({int width, int height}) {
&nbsp;&nbsp;&nbsp;&nbsp;var e = document.$dom_createElement(&quot;canvas&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;if (width != null) e.width = width;
&nbsp;&nbsp;&nbsp;&nbsp;if (height != null) e.height = height;
&nbsp;&nbsp;&nbsp;&nbsp;return e;
&nbsp;&nbsp;}

-------- resulting code
$.CanvasElement_CanvasElement = function(height, width) {
&nbsp;&nbsp;var e = document.createElement(&quot;canvas&quot;);
&nbsp;&nbsp;$.set$width$x(e, width);
&nbsp;&nbsp;$.set$height$x(e, height);
&nbsp;&nbsp;return e;
};

The code has two one-shot interceptors.
I would expect a single interceptor to be used twice, i.e.:
&nbsp;&nbsp;t1 = $.getInterceptor$x(e);
&nbsp;&nbsp;t1.set$width(e, width);
&nbsp;&nbsp;t1.set$height(e, height);

Looking at the CFG, the first pass of constant folding replaces the conditions with 'true' since type analysis determines the arguments are never null.
The structure of the CFG is maintained, which probably inhibits GVN.
Even the very late dead code eliminator (after one-shots) doesn't get rid of the 'if (true)' control flow.

**Comment by karlklose** [comment]
Will be obsolete with the new backend.
