### ISSUE TITLE
Report warning when part references library which does not source it.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#10214]
I'm trying to fix https://code.google.com/p/dart/issues/detail?id=9320 and want to approach to it by providing Quick Fix. Would be nice if analyzer will provide warning and resolve identifier to LibraryElement.

Let me know if you think it should not work this way.
Alternatively I can do it using Quick Assist, but then there is discoverability issue.

App.dart

---

library app;
&lt;EOF&gt;

MyPart.dart

---

part of app;
&lt;EOF&gt;

**Comment by askeksa-google** [comment]
The analyzer now gives an error in this case.
