### ISSUE TITLE
HttpRequest not supported in non-DOM isolates in Dartium

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10223]
This program works fine in dart2js:

import 'dart:isolate';
import 'dart:html' show HttpRequest;

useHttpRequest() {
&nbsp;&nbsp;port.receive((String uri, SendPort replyTo) {
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpRequest.getString('test.dart').then((text) =&gt; replyTo.send(text));
&nbsp;&nbsp;&nbsp;&nbsp;} catch (e, trace) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replyTo.send('$e\n$trace');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;});
}

main() {
&nbsp;&nbsp;print('Starting isolate');
&nbsp;&nbsp;spawnFunction(useHttpRequest).call('test.dart').then((reply) =&gt; print('Reply: $reply'));
}

The console shows:

Starting isolate test.dart.js:4629
Reply: import 'dart:isolate';
import 'dart:html' show HttpRequest;

useHttpRequest() {
&nbsp;&nbsp;port.receive((String uri, SendPort replyTo) {
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// replyTo.send('Hello');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpRequest.getString('test.dart').then((text) =&gt; replyTo.send(text));
&nbsp;&nbsp;&nbsp;&nbsp;} catch (e, trace) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replyTo.send('$e\n$trace');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;});
}

main() {
&nbsp;&nbsp;print('Starting isolate');
&nbsp;&nbsp;spawnFunction(useHttpRequest).call('test.dart').then((reply) =&gt; print('Reply: $reply'));
}
&nbsp;test.dart.js:4629

Unfortunately, sadness descents on Dartium.  This is what is printed in the console:

Starting isolate undefined:1
Reply: DOM access is not enabled in this isolate
# ­0      HttpRequest._create (file:///Volumes/data/b/build/slave/dartium-mac-inc/build/src/out/Release/gen/webkit/bindings/dart/dart/html/HttpRequest.dart:60:3)
# ­1      HttpRequest.HttpRequest (file:///Volumes/data/b/build/slave/dartium-mac-inc/build/src/out/Release/gen/webkit/bindings/dart/dart/html/HttpRequest.dart:58:35)
# ­2      HttpRequest.request (file:///Volumes/data/b/build/slave/dartium-mac-inc/build/src/out/Release/gen/webkit/bindings/dart/dart/html/HttpRequest.dart:10:15)
# ­3      HttpRequest.getString (file:///Volumes/data/b/build/slave/dartium-mac-inc/build/src/out/Release/gen/webkit/bindings/dart/dart/html/HttpRequest.dart:5:19)
# ­4      useHttpRequest.&lt;anonymous closure&gt; (http://127.0.0.1:56653/web_editor/test.dart:6:28)
# ­5      _ReceivePortImpl._handleMessage (dart:isolate-patch:81:92)

&nbsp;undefined:1

**Comment by jtmcdole** [comment]
What is the status on this bug? Is anyone working on it?

**Comment by alan-knight** [comment]
Yes, in that we expect to turn isolates in Dartium into webworkers, but it's gated on some other Dartium work. Note that a workaround is that you can spawn a webworker running JS explicitly in Dartium, it's just awkward and not fun to debug.
