### ISSUE TITLE
dart2js -- need a way to debug without inlining

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#10292]
I'm trying to debug some test failures, it is difficult because the code is not in the right method. For example I see an exception in a method like &quot;_InstanceCursor.remove&quot; but the bug was actually in _instanceCount, but it got inlined along with other methods, so that wasn't at all apparent. That happens frequently over the course of a debug session.

I'm all for aggressive optimizations :), but at some point the output doesn't resemble the input enough to permit debugging. Maybe we need a -O flag so the developer can control optimization level? Then they can find their own balance between optimization/debuggability, similar to what folks do in C/C++.

**Comment by sigmundch** [comment]
it appears this bug is just stale. We currently have a `--disable-inlining` flag available for this purpose.
