### ISSUE TITLE
Cannot debug Dartium w/ SpeedTracer extension enabled

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#10298]
It appears to break debugging within Dartium- everything appears to work but breakpoints don't break. I thought it was a problem with the editor or Dartium for quite a while.

Extension is from:
https://chrome.google.com/webstore/detail/speed-tracer-by-google/ognampngfcbddbfemdapefohjiobgbdl

**Comment by sethladd** [comment]
Looks like not planned.
