### ISSUE TITLE
dart2dart is not obvious

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#10338]
We (the project, team) refer to a thing called &quot;dart2dart&quot;. However, there is no such command as &quot;dart2dart&quot;.

Suggestion:

add a script to the SDK called dart2dart that simply delegates to dart2js --output-type=dart

As our deployment story gets baked, it's becomes important to incorporate dart2js and dart2dart as deployment options.

**Comment by zoechi** [comment]
can be closed, no dart2dart anymore
