### ISSUE TITLE
Report specific ErrorCode when "var" is used instead of "dynamic"

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#10356]
https://code.google.com/p/dart/issues/detail?id=10355
So, Quick Fix could use this information and suggest fix.

For example for: Map&lt;String, var&gt;

**Comment by srawlins** [comment]
We seem to recover much much better today. This now gets reported as:

> error: The keyword 'var' cannot be used as a type name
> warning: The name 'var' is not a type and cannot be used as a parameterized type

Done?
