### ISSUE TITLE
dart2js source mirrors won't allow you to analyze "private" libraries.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10369]
dart2js source mirrors won't allow you to analyze &quot;private&quot; libraries.

I don't think this restriction makes sense here as you'll get a MirrorSystem that happily shows you these libraries (as it should).

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
