### ISSUE TITLE
Source library mirrors should provide access to compilation units of a library.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10370]
It is possible that it doesn't make sense to expose compilation units in dart:mirrors, but the source mirrors should provide this abstraction.

For example:

abstract class LibrarySourceMirror extends LibraryMirror {
&nbsp;&nbsp;final Map&lt;Uri, CompilationUnitMirror&gt; compilationUnits;
}

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
