### ISSUE TITLE
List.from is fixed length, but loop through list still checks for ioore

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#10489]
Consider this code:

List&lt;String&gt; fruits = new List.from(['apples', 'oranges']);

void main() {
&nbsp;&nbsp;for (int i = 0; i &lt; fruits.length; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;print(fruits[i]);
&nbsp;&nbsp;}
}

this compiles to the following JS code:

$.main = function() {
&nbsp;&nbsp;var i, t1;
&nbsp;&nbsp;for (i = 0; i &lt; $.get$fruits().length; ++i) {
&nbsp;&nbsp;&nbsp;&nbsp;t1 = $.get$fruits();
&nbsp;&nbsp;&nbsp;&nbsp;if (i &gt;= t1.length)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw $.ioore(i);
&nbsp;&nbsp;&nbsp;&nbsp;$.Primitives_printString($.toString$0(t1[i]));
&nbsp;&nbsp;}
};

I would expect that the constructor for List.from() returns a fixed length list. Thus, dart2js could inline the list length in a for loop and avoid the ioore check.

**Comment by karlklose** [comment]
Verified fix in 79a8654e5fb30dfce902636961d6a5ffb69e6f85
