### ISSUE TITLE
[mirrors] What are the arguments to invoke and setField (and their async versions)?

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10499]
As far as I can tell from tests of the VM mirrors, invoke and setField (and their async versions) do not take instance mirrors as arguments, but objects from the current isolate.

This poses the following question: if I were to write a debugger operating on another isolate, how would I evaluate an expression in that isolate. For example:

InstanceMirror remoteObject1 = ...;
InstanceMirror remoteObject2 = ...;
// Whoops, remoteObject2 does not have a reflectee:
remoteObject1.invokeAsync(const Symbol('=='), [remoteObject2.reflectee]);

**Comment by bkonyi** [comment]
@peter-ahe-google is this still a useful issue? Closing for now, but feel free to reopen.
