### ISSUE TITLE
Symbols representing private names from different libraries should not be equal

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10526]
According to Lasse:

// Have this code available:

class _ {
&nbsp;&nbsp;const _();
&nbsp;&nbsp;noSuchMethod(i) =&gt; i.memberName;
}
const $ = const _();

// Then do:

var symbol1 = $._foo;

// and in another library

var symbol2 = $._foo;

// somewhere

print(symbol1 == symbol2);  // true or false?

Currently the VM prints false and dart2js prints true.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
