### ISSUE TITLE
Provide a dart method that trigger a breakpoint

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#10536]
In javascript, you can drop in a

debugger;

statement to trigger a breakpoint when running the code with a debug tool (e.g. chrome dev tools).

It would be helpful to have a similar dart statement so that breakpoints can be triggered in the code and then used in whatever debugger the user prefers (e.g. dartium or dart editor).
In particular, when dealing with generated code it is challenging to set breakpoints at the moment.

**Comment by zoechi** [comment]
Can this be closed?

**Comment by mhausner** [comment]
Yes, this functionality has been added in the dart:developer library (https://api.dartlang.org/stable/1.20.1/dart-developer/dart-developer-library.html)
