### ISSUE TITLE
Crash in dart2js when calling patched top-level method from patch file.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10543]
In mirrors_patch.dart, I had to write:

patch ClassMirror reflectClass(Type key) =&gt; _reflectClass(key);

ClassMirror _reflectClass(Type key) { .. }

To avoid this crash:

$ ./sdk/bin/dart2js_developer tests/lib/mirrors/mirrors_test.dart 
pkg/unittest/lib/mock.dart:1345:31: Warning: Using &quot;MirrorSystem.getName&quot; may result in larger output.
&nbsp;&nbsp;&nbsp;&nbsp;var method = MirrorSystem.getName(invocation.memberName);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^
sdk/lib/_internal/compiler/implementation/lib/mirrors_patch.dart:59:19: null
&nbsp;&nbsp;ClassMirror get type =&gt; reflectClass(reflectee.runtimeType);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

\* the name and version of your operating system,

\* the Dart SDK build number (build number could not be determined), and

\* the entire message you see here (including the full stack trace
&nbsp;&nbsp;below as well as the source location above).

Internal error: Compiler crashed: null.
# ­0      invariant (.../sdk/lib/_internal/compiler/implementation/compiler.dart:1314:5)
# ­1      HStatic.HStatic (.../sdk/lib/_internal/compiler/implementation/ssa/nodes.dart:1985:21)
# ­2      SsaBuilder.visitStaticSend (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:3482:29)
# ­3      ResolvedVisitor.visitSend (.../sdk/lib/_internal/compiler/implementation/resolved_visitor.dart:47:31)
# ­4      SsaBuilder.visitSend (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:3208:20)
# ­5      Send.accept (.../sdk/lib/_internal/compiler/implementation/tree/nodes.dart:342:47)
# ­6      SsaBuilder.visit (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:1844:34)
# ­7      SsaBuilder.visitReturn (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:4012:12)
# ­8      Return.accept (.../sdk/lib/_internal/compiler/implementation/tree/nodes.dart:969:49)
# ­9      SsaBuilder.buildMethod (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:959:25)
# ­10     SsaBuilderTask.build.&lt;anonymous closure&gt; (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:45:36)
# ­11     CompilerTask.measure (.../sdk/lib/_internal/compiler/implementation/compiler.dart:1225:37)
# ­12     SsaBuilderTask.build (.../sdk/lib/_internal/compiler/implementation/ssa/builder.dart:32:19)
# ­13     JavaScriptBackend.codegen (.../sdk/lib/_internal/compiler/implementation/js_backend/backend.dart:1388:33)
# ­14     Compiler.codegen (.../sdk/lib/_internal/compiler/implementation/compiler.dart:991:20)
# ­15     CodegenWorkItem.run (.../sdk/lib/_internal/compiler/implementation/compiler.dart:74:21)
# ­16     Compiler.processQueue.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (.../sdk/lib/_internal/compiler/implementation/compiler.dart:887:54)
# ­17     Compiler.withCurrentElement (.../sdk/lib/_internal/compiler/implementation/compiler.dart:355:15)
# ­18     Compiler.withCurrentElement (.../sdk/lib/_internal/compiler/implementation/compiler.dart:363:7)
# ­19     Compiler.processQueue.&lt;anonymous closure&gt; (.../sdk/lib/_internal/compiler/implementation/compiler.dart:887:25)
# ­20     CodegenEnqueuer.forEach (.../sdk/lib/_internal/compiler/implementation/enqueue.dart:713:8)
# ­21     Compiler.processQueue (.../sdk/lib/_internal/compiler/implementation/compiler.dart:886:18)
# ­22     Compiler.runCompiler (.../sdk/lib/_internal/compiler/implementation/compiler.dart:856:17)
# ­23     Compiler.run (.../sdk/lib/_internal/compiler/implementation/compiler.dart:600:18)
# ­24     Compiler.run (.../sdk/lib/_internal/compiler/implementation/compiler.dart:616:7)
# ­25     Compiler.run (.../sdk/lib/_internal/compiler/implementation/apiimpl.dart:257:29)
# ­26     compile (.../sdk/lib/_internal/compiler/compiler.dart:96:15)
# ­27     compile (.../sdk/lib/_internal/compiler/implementation/dart2js.dart:330:14)
# ­28     compilerMain (.../sdk/lib/_internal/compiler/implementation/dart2js.dart:377:10)
# ­29     mainWithErrorHandler (.../sdk/lib/_internal/compiler/implementation/dart2js.dart:506:17)
# ­30     main (.../sdk/lib/_internal/compiler/implementation/dart2js.dart:522:23)

$

**Comment by bkonyi** [comment]
I'm assuming this is specifically a dart2js issue, so I'm closing it for now since we no longer support `dart:mirrors` on web.
