### ISSUE TITLE
Avoid crashing due to ErroneousElementX

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10541]
ErroneousElementX seems to cause random crashes in places where it shouldn't.  We should fix that by having it make up answers instead of crashing.

Mostly, ErroneousElementX is used to tell the backend to generate code that throws an exception.  To all other users, including dartdoc, it is unfortunately a common source of crashes.

I'm pretty sure that 9917 is about ErroneousElementX, and I discovered that if you're using deferred loading, the compiler will crash if a static method is unresolved.

IIRC, Johnni was the original author, so I think he should be deciding to accept this issue or not.

Tentatively marking this as high as I generally raise the priority of crashes.  Not that there's a particular crash here, but it does raise the risk of crashes as the compiler changes.

**Comment by karlklose** [comment]
The model we use now is that [Element]s can be malformed and backend ends have to check for that before asking any questions.
