### ISSUE TITLE
[mirrors] Small cleanups in the mirror API

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10542]
Please clean up the mirror API:

\* Use List, not List&lt;Object&gt;

\* Use Map&lt;String, dynamic&gt;, not Map&lt;String, Object&gt;

\* Please add a space after commas.

**Comment by srawlins** [comment]
Mirrors API no longer includes `List<Object>`, nor `Map<String, Object>`. Code has been formatted with dartfmt, adding appropriate whitespace.
