### ISSUE TITLE
Allow empty type parameters in type annotations and infer generics for initialized variable declarations (diamond operator)

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#10611]
A variable declaration with generics often includes visually redundant type information, for example:

```dart
Map<String, Symbol> _cache = new Map<String, Symbol>();
```

Removing the generics from either side does have effects though, especially in checked mode. We should support inferring generics for initialized variable declarations. This would allow type checks in checked-mode, but reduce visual redundancy:

```dart
Map<> _cache = new Map<String, Symbol>();
```

**Comment by matanlurey** [comment]
Dart2 has type inference that allows the use of `var` or `final` here instead of `Map<>`.
