### ISSUE TITLE
self-hosted compiler has specific performance problems

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10630]
It seems like the self-hosted compiler has some performance problems in specific parts of the compiler.  In particular, the scanner, parser, and resolver are much slower than dart2js command line.

Is this because the Dart VM is really good at optimizing these parts, or is it because dart2js generates slow code?  I don't know, but it might be worth investigating.

This is compiling the HTML fibonacci example from the command line:

Reading input files took 82msec
LibraryLoader took 53msec
Scanner took 150msec
Diet Parser took 83msec
Parser took 189msec
Patching Parser took 16msec
Resolver took 638msec
Closure Simplifier took 31msec
Type checker took 29msec
Type inference took 173msec
ConstantHandler took 0msec
Deferred Loading took 0msec
Enqueue took 140msec
SSA builder took 169msec
SSA optimizer took 194msec
SSA code generator took 169msec
CodeEmitter took 242msec
Total compile-time 2599msec; unaccounted 241msec

This is compiling the same example on try.dartlang.org:

Reading input files took 0msec
LibraryLoader took 37msec
Scanner took 425msec
Diet Parser took 46msec
Parser took 412msec
Patching Parser took 27msec
Resolver took 1063msec
Closure Simplifier took 26msec
Type checker took 16msec
Type inference took 177msec
ConstantHandler took 0msec
Deferred Loading took 0msec
Enqueue took 241msec
SSA builder took 102msec
SSA optimizer took 238msec
SSA code generator took 146msec
CodeEmitter took 170msec
Total compile-time 3520msec; unaccounted 394msec

**Comment by karlklose** [comment]
These numbers are really old. Please reopen if this is still a problem.
