### ISSUE TITLE
boolConversionCheck should throw an error with a description

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#10760]
Today you get: Instance of 'AssertionError' if boolConversionCheck fails in checked mode.

I think we can do better.

**Comment by rakudrama** [comment]
The spec prescribes the operation of boolean conversion:

```Dart
(bool v){
    assert(v != null);
    return identical(v, true);
}(o)
```

In checked mode the `bool` type annotation takes priority.
The error is only an assertion failure for the value `null`.

I think the most reasonable enhancement that sticks to the letter of the spec would be to add a message to the assert once assertions with messages are supported.

The VM hides any helper code.
Turing on various checks shows that it does not strictly follow the spec:
--enable-asserts does not enable any part of the check
--enable-type-checks enables both the type check and the assertion.
VM:
```
Unhandled exception:
type 'int' is not a subtype of type 'bool' of 'boolean expression'.
#0      main (file:///home/sra/play1/bug6i8k.dart:2:6)

Unhandled exception:
Failed assertion: boolean expression must not be null
#0      main (file:///home/sra/play1/bug6i8k.dart:2:6)
```

dart2js shows several frames of helper code. These could be marked to be elided.
```
out.js:1012: type 'JSInt' is not a subtype of type 'bool'
      throw H.wrapException(H.TypeErrorImplementation$(value, "bool"));
      ^
type 'JSInt' is not a subtype of type 'bool'
    at dart.wrapException (out.js:624:17)
    at dart.boolTypeCheck (out.js:1012:15)
    at dart.boolConversionCheck (out.js:989:9)
    at dart.main (out.js:1795:13)

out.js:1058: Assertion failed
        throw H.wrapException(new P.AssertionError());
        ^
Assertion failed
    at dart.wrapException (out.js:624:17)
    at dart.assertHelper (out.js:1058:17)
    at dart.boolConversionCheck (out.js:990:9)
    at dart.main (out.js:1795:13)
```
