### ISSUE TITLE
dart2js type warning following is check

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#10776]
Code following an 'is' check does not take into account the is check for the type.

The following generates warnings from dart2js and the old analyzer, but not the new one:

class Bar {
&nbsp;&nbsp;bool get isBar =&gt; true;
}

void check(Object f) {
&nbsp;&nbsp;// Warning here that isBar is not defined on Foo.
&nbsp;&nbsp;if (f is Bar &amp;&amp; f.isBar) {
&nbsp;&nbsp;&nbsp;&nbsp;// Warning here too.
&nbsp;&nbsp;&nbsp;&nbsp;var b = f.isBar;
&nbsp;&nbsp;}
}

**Comment by munificent** [comment]
Type promotion is in the language now (and has been for quite some time).
