### ISSUE TITLE
Warn about misspelled meta tags

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#10913]
If I write &quot;@Observable&quot; you should be signaling an warning saying that the &quot;O&quot; must be lower case, I lost more than 30 minuts trying to understand why by observable was not working ehehe...
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.5.9_r22879 (2013-05-18)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_21
# projects: 1
# open dart files: 1

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 457 / 169 MB
thread count: 28
index: 392390 relationships in 104463 elements in 306 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by srawlins** [comment]
There are warnings for this now:

```dart
class A {
  @depricated
  int x;
}
```

https://dartpad.dartlang.org/7bf5fa9b6d363d40c3a44e4baa11bf7a

> error: Annotation can be only constant variable or constant constructor invocation

The warning is a little oblique, but it tells you "I don't know what you tried to do on line 2."
