### ISSUE TITLE
Incomplete code completion from static collection

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#11062]
Consider this code:

class Foo {
&nbsp;&nbsp;static List strings = new List&lt;String&gt;();
}

void main() {
&nbsp;&nbsp;Foo.strings.first.[CODE COMPLETE]
}

expected:

options for a string

actual:

options from Object

Please see attached screenshot.

Hope this helps!

______
**Attachment:**
[Screen Shot 2013-06-03 at 9.42.08 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-11062/comment-0/Screen Shot 2013-06-03 at 9.42.08 PM.png) (72.57 KB)

**Comment by bwilkerson** [comment]
Closing as stale.
