### ISSUE TITLE
Analyzer fails to respect certain "is" checks

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#11080]
Consider the following code:

&nbsp;&nbsp;&nbsp;&nbsp;import &quot;dart:typed_data&quot;;

&nbsp;&nbsp;&nbsp;&nbsp;void doIt(List list) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (list is TypedData) print(list.buffer);
&nbsp;&nbsp;&nbsp;&nbsp;}

Running the analyzer on this produces the following error:

&nbsp;&nbsp;&nbsp;&nbsp;[warning] There is no such getter 'buffer' in 'List'

despite the fact that &quot;list&quot; must be an instance of TypedData in the &quot;if&quot; block, and TypedData defines a &quot;buffer&quot; getter.

**Comment by Hixie** [comment]
I don't understand this limitation. If you enter a code block that's gated by an `if (foo is Bar)`, then it makes no sense to me that the analyzer wouldn't assume that isn't that block, `foo` is a `Bar`, irrespective of any other types that it might think `foo` is as well.

**Comment by bwilkerson** [comment]
Consider the following code:

```
abstract class A {
  void mA();
}

abstract class B {
  void mB();
}

void f(A p) {
  if (p is B) {
    p.mA();
    p.mB();
  }
}
```

In the absence of intersection types you can choose one of two "wrong" semantics. Within the body of the `if`, either `p` has type `A` or `p` has type `B`. Either way you end up with a spurious error message.

The original authors chose one of the two options, but both are bad. I'm not sure which would result if fewer spurious error messages in practice. Feel free to re-open this case if you want the language team to consider changing this behavior.

**Comment by Hixie** [comment]
I think the analyzer should assume that in that block, `p` is both `A` _and_ `B`.

**Comment by Hixie** [comment]
(i don't have the access to reopen bugs in the dart sdk repo :-) )

**Comment by bwilkerson** [comment]
We tried adding union types behind the scenes awhile back and it turned out to be so confusing to users that we ended up backing all that out. I'm concerned that intersection types would be the same. In any case, this behavior is currently part of the specification, so I'm turning this into a language issue.

**Comment by lrhn** [comment]
Looks like a variant of an "improve type promotion" request (#25565)
