### ISSUE TITLE
Consider adding typecase

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#11130]
FTR, I'm putting this in to be considered in some future version.

People are asking for flow-dependent type rules. The poster child for these is

Object v = e;
if (v is T) {
&nbsp;&nbsp;v.operationDefinedOnlyOnT;
}

which warns that v does not support operationDefinedOnlyOnT. &quot;Obviously&quot; this is stupid and people ask why can't the system tell this won't be a problem. &quot;Obviously&quot; is in quotes, because if you put such rules in the language, they have to cover other cases.

Object v;
if ((v = e) is T) {
&nbsp;&nbsp;v.operationDefinedOnlyOnT;
}

does that change? Why? What is the exact rule. How about:

if (((v = e) is T) &amp;&amp; v.somePredicateOnlyDefinedForT) { 
&nbsp;&nbsp;&nbsp;&nbsp;v.operationDefinedOnlyOnT;
}

This clearly shows the danger of reasoning from specific use cases. There is a reason no one does this.

It might be better to have a dedicated construct (as other languages have had in the past) like typecase

typecase e of
&nbsp;&nbsp;&nbsp;T1 v1: {... here, v1 is known to be a T1 ...}
&nbsp;&nbsp;&nbsp;T2 v2: { .. and here v2 is a T2 ...}
&nbsp;&nbsp;&nbsp;default: ...

but maybe adding a special construct is not justified in a loosely typed setting.

**Comment by munificent** [comment]
I'm going to consider this a duplicate of #2949. I think any general purpose pattern matching construct would also handle type tests.

**Comment by groz** [comment]
> There is a reason no one does this.

Outdated by Kotlin.
