### ISSUE TITLE
Tear-off closures of deferred functions are assumed to be non-null

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#11137]
Type inference, tear-off closures of static/top-level functions, and deferred loading doesn't mix.

See readFoo in tests/compiler/dart2js_extra/deferred/deferred_function_test.dart.

**Comment by rakudrama** [comment]
I think this is an obsolete issue.

Static method tearoff getters are in the same deferred unit as the method.
There will be a deferred library guard before the access, so the access cannot return null.
