### ISSUE TITLE
VM: Incorrect error message if trying to use factory constructor as super constructor.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#11202]
Example code:
&nbsp;&nbsp;class wExtendedElementList extends List {
&nbsp;&nbsp;&nbsp;&nbsp;wExtendedElementList.from(List elements) : super.from(elements){}
&nbsp;&nbsp;}
This uses a factory constructor as the super-constructor in the initializer list. The error message given is:

&nbsp;&nbsp;Error: line 2 pos 48: super class constructor 'List.from' not found
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wExtendedElementList.from(List elements) : super.from(elements){}

This error message is misleading, going on incorrect, since List.from is a constructor. The error isn't that it doesn't exist, but that it is a factory constructor instead of a generative constructor.
(It's technically true that the compiler didn't find List.from, but that's because it was looking in the wrong place).

**Comment by zanderso** [comment]
This appears to be still happening.
