### ISSUE TITLE
Triage test failures on arm

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#11207]
After enabling isolate/lib/standalone/vm tests, there are more than 100 failures remaining. I'll mark all crashes/failures in the status file with this bug number.

My guess is that failures can have the following reasons:
- unimplemented code in the codegenerator
- code generator needs to use 'gnueabihf' calling convention
- secure socket / https / extension tests: since we compile statically they can't dynamically load libraries

Please don't close this bug until either all issues have been resolved, or other (more specific) bugs have been filed.

**Comment by zanderso** [comment]
There are no more markers in the isolate/lib/standalone/vm status files for arm.
