### ISSUE TITLE
Need a way to identify annotations

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11241]
For context, see: https://code.google.com/p/dart/issues/detail?id=11210

The spec defines annotations but there's nothing to say how to identify annotations programmatically. To do effective code completion for annotations we need something better than &quot;find all const's&quot;. The list of program elements that are allowed by the spec is inappropriate from a UX standpoint because nearly all of them would be wrong for use as annotations.

One possible solution (just to get things started): Define a &quot;known annotation&quot; in the SDK and establish the convention that all other annotations be annotated with that root annotation. At least then we'd be able to pick out those const's that are intended for use as an @­annotation.

Having a way to identify intended annotations will be useful for various tools. For example, a future lint tool could identify mis-used annotations. Today, as described in the referenced issue, it would help code completion.

**Comment by natebosch** [comment]
@bwilkerson - have we had continued complaints about completion for annotations?

Do we expect to take any action here?

**Comment by bwilkerson** [comment]
Nope.
