### ISSUE TITLE
Flaky test: drawImage_image_element

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#11416]
html/canvasrenderingcontext2d_test/drawImage_image_element failed on a (unrelated) commit on IE9.
See:
http://build.chromium.org/p/client.dart/builders/dart2js-ie9-win7-all-4-6/builds/2826/steps/dart2js%20tests%20failures/logs/stdio

Could be that the browsers don't guarantee that the pixels we get back with 'getImageData' are *exactly* the same as the ones written using 'drawImageToRect'?

I'll mark it as flaky.

**Comment by Markzipan** [comment]
Closing this since IE is no longer supported on our web targets, and this is a super old bug. Revive if necessary.
