### ISSUE TITLE
Can't get path to current script

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#1145]
When writing Dart scripts that read other files, it's helpful if you can identify that file with a path that's relative to the script itself. Right now, I don't think there's a way to get that in Dart. Instead, paths are always relative to where Dart was invoked from. This causes problems if you want to invoke the same script from different paths and have it still be able to reliably find files.

For example, I have a unit test (utils/tests/dartdoc/src/dartdoc_tests.dart) that wants to load a file in its same directory (dummy.dart). This unit test is run both through test.dart and frog's presubmit.py from different paths. Short of &quot;let me see if it's here? no, how about here?&quot; kind of hacks, I don't know of a clean way to support that.

**Comment by sethladd** [comment]
We have a Platform.script now.

Closing. Please reopen if that is not correct.

**Comment by nex3** [comment]
`Platform.script` isn't really enough here. It's not going to reliably point to the same thing in different contexts, and even if it did a Dart script really wants to be able to find paths relative to a *library* rather than relative to the entrypoint.

The best solution here is really a resource API like the one @lrhn is working on, though, so I'm fine with leaving this issue closed.

**Comment by sethladd** [comment]
The Resource API doesn't give you the path to your script, though.

It does allow you to load files/things with a package: URI and get the same resolution logic used when importing a Dart library via package:.  Maybe that was the intent of this issue? If so, great!

**Comment by nex3** [comment]
It can give you the real URL for a `package:` URL, which allows libraries to find their own locations. If I can look up the real location of the package that contains my script, then I can get the real location of my script, too.

**Comment by sethladd** [comment]
@lrhn or @nex3 can you post a link to the CL? Thanks!

**Comment by nex3** [comment]
As far as I know, the API is still in the design stage.

**Comment by ianloic** [comment]
I would also like this please.

**Comment by 0xff00ff** [comment]
+1 I want this feature. Is this can be done in some way?

**Comment by AkatQuas** [comment]
+1 Please. 
I need tho configure the project root dynamically.
From node, we have `__dirname__`, could we have something similar in Dart ?

**Comment by pacifio** [comment]
I am trying to load a natively compiled file and trying to run it using Process.run but when I use it as a library and get to another folder the path to the compiled file changes . I need the path of the original library here !

For example

This is mouse.dart:
```dart
import 'dart:io';

class _Mouse {
  void position() {
    if (Platform.isWindows) {
    } else {
      Directory.current = '../../bin/scripts/mouse/darwin/';
      Process.run('./mouse', ['position']).then((results) {
        print(results);
      });
    }
  }
}

final mouse = _Mouse();
```

The path to mouse file ( a compiled cli tool ) works if I execute this from mouse.dart but if I switch to example.dart:
```dart
import 'package:dart_autogui/dart_autogui.dart';

void main() {
  mouse.position();
}
```

This generates an error as follows :
```
Unhandled exception:
FileSystemException: Setting current working directory failed, path = '../../bin/scripts/mouse/darwin/' (OS Error: No such file or directory, errno = 2)
#0      _Directory.current= (dart:io/directory_impl.dart:79:7)
#1      Directory.current= (dart:io/directory.dart:196:18)
#2      _Mouse.position (package:demo/src/mouse/mouse.dart:7:17)
#3      main (file:///Users/adib/Desktop/open_source/demo/example/example.dart:4:9)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This should not happen . If I had something like ```__dirname``` like node . Please tell me how can I find the realtive path from the original library file / `mouse.dart`
