### ISSUE TITLE
Dart VM GC needs an API to indicate external memory pressure

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#11471]
When Dart objects are holding on to external memory, e.g. when typed data objects are allocated with external memory for backing store, there is no way for the GC to know that running a GC could free much more memory that what the VM heap holds.

V8 has the API AdjustAmountOfExternalAllocatedMemory (https://code.google.com/p/v8/source/browse/branches/bleeding_edge/include/v8.h#­3909) to indicate the amount of external memory kept alive by the V8 heap.

Dart could have an API like this or the number of external bytes could be aded to some other API where the finalization is registered, to avoid the need to two matching calls to increment and decrement the number of external bytes

**Comment by kodandersson** [comment]
I implemented this a long time ago; see "external_allocation_size" parameters in dart_api.h.
