### ISSUE TITLE
Request for exit analysis

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11485]
Can we have the following method be flagged.  It's signature says to return a string but it is not returning anything.

&nbsp;&nbsp;String format(value, [String parameters = null]) {
&nbsp;&nbsp;&nbsp;&nbsp;// Handle null case.
&nbsp;&nbsp;&nbsp;&nbsp;if (value == null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return '';
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;// Handle case where an object other than an array is passed.
&nbsp;&nbsp;&nbsp;&nbsp;if (!(value is Iterable)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return value.toString();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;// Handle empty list.
&nbsp;&nbsp;&nbsp;&nbsp;if (value.isEmpty) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return '';
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;\_formatValue(value, parameters);
&nbsp;&nbsp;}
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.5.20_r24160 (2013-06-18)
OS: Linux - amd64 (3.2.5-gg1236)
JVM: 1.7.0-google-v5
# projects: 2
# open dart files: 19
auto-run pub: false
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 786 / 505 MB
thread count: 33
index: 483112 relationships in 114610 keys in 831 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by srawlins** [comment]
Done.

https://dartpad.dartlang.org/b3c31f16edf01b1f67adc9e6096f91e5
