### ISSUE TITLE
Mocks tests are not statically negative

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#11517]
&nbsp;&nbsp;Please fix these tests to make them statically negative.
&nbsp;&nbsp;Otherwise, I'd like to know if it is fine to mark them as &quot;fail, OK&quot; in status files.

unittest/test/mock_regexp_negative_test: fail
unittest/test/mock_stepwise_negative_test: fail

**Comment by srawlins** [comment]
No more mock*_negative_test files.
