### ISSUE TITLE
VM should compile with -Wconversion

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#11526]
The -Wall flag does not include -Wconversion which warns when assignments truncate numbers (like int = int64, short = int, ...).
The VM should add this flag to its standard flags.
Currently there are several places in the VM where the warning would trigger. So these need to be fixed first.

**Comment by zanderso** [comment]
There are now 100s of these. This would be a fairly serious clean-up.

**Comment by mraleph** [comment]
I don't think we are planning to go through this cleanup any time soon.
