### ISSUE TITLE
InstanceMirror needs methods to check if field/method exists

### ISSUE THREAD

**Issue by pavelgj** [dart-lang/sdk#11557]
InstanceMirror is missing the following methods:

&nbsp;&nbsp;bool hasSetter(Symbol fieldName);
&nbsp;&nbsp;bool hasGetter(Symbol fieldName);
&nbsp;&nbsp;bool hasMethod(Symbol memberName, List positionalArguments, [Map&lt;Symbol, dynamic&gt; namedArguments]);

The alternative right now is to do try-catch for NoSuchMethodError, but it doesn't tell you if there's no such method on the instance or somewhere further down the stack, so it's not ideal.

**Comment by bkonyi** [comment]
This should be possible by checking if the `Symbol` is in either `ClassMirror.instanceMembers` or `ClassMirror.staticMembers`.
