### ISSUE TITLE
[dart2js] Zero-effect code not tree-shaken off

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#11559]
INPUT:

main() {
&nbsp;&nbsp;new Foo();  // Has no effect
}

class Foo {}

OUTPUT (reformatted):

main(){
&nbsp;&nbsp;new Foo();  // expected to be gone
}

class Foo{}  // expected to be gone

**Comment by yjbanov** [comment]
This issue was misclassified. Reopening and moving to dart2js.

**Comment by rakudrama** [comment]
I can't repro anything that looks like this.

The current generated JavaScript is
```js
    main() {
    }
```
with no sign of `Foo`.
