### ISSUE TITLE
[dart2js] Unused fields are not tree-shaken off, sensitive to type annotations

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#11558]
INPUT:

main() {
&nbsp;&nbsp;print(new Foo().hello);
}

class Bar {
&nbsp;&nbsp;String txt = &quot; World&quot;;
}

class Foo {
&nbsp;&nbsp;String _hello;
&nbsp;&nbsp;Bar _world;  // never initialized
&nbsp;&nbsp;String get hello {
&nbsp;&nbsp;&nbsp;&nbsp;if (_hello == null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_hello = &quot;Hello&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return _hello;
&nbsp;&nbsp;}
&nbsp;&nbsp;String get world {
&nbsp;&nbsp;&nbsp;&nbsp;if (_world == null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_world = new Bar();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return _world.txt;
&nbsp;&nbsp;}
}

OUTPUT (reformatted):

main(){
&nbsp;&nbsp;print(new Foo().hello);
}

class Bar{}  // Expected Bar to be gone.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// However, it will be gone if I change type of _world to &quot;var&quot;.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Nice to see txt tree-shaken off.

class Foo{
&nbsp;&nbsp;String _hello;  // Used, so it stays.
&nbsp;&nbsp;Bar _world;  // Not used, expected to be gone
&nbsp;&nbsp;String get hello{
&nbsp;&nbsp;&nbsp;&nbsp;if(_hello==null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_hello=&quot;Hello&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return _hello;
&nbsp;&nbsp;}
}

**Comment by yjbanov** [comment]
This issue was misclassified. Reopening and moving to dart2js.

**Comment by greglittlefield-wf** [comment]
I just ran into the issue, only I was seeing it where unused fields from the superclass overridden by getters/setters in a subclass are not tree-shaken, and are still present in the JS constructor initializer list. 

For example,
```dart
class A {
  int a;
}
class B extends A {
  int get a => ...;
  set a(int value) => ...;
}
```

For more context on my use-case, see the "Leaving behind fields" section here: https://github.com/dart-lang/build/issues/897#issuecomment-365807794

I was thinking https://github.com/dart-lang/sdk/issues/21450 may mitigate this issue, but it would be nice to solve the issue and eliminate these fields completely.

---

Looks like the above example still reproduces on Dart 1.24.3, with some tweaks to prevent the `Foo` class from being fully optimized out:
```dart
main() {
  var foo = new Foo();
  print('$foo ${foo.hello}');
}

class Bar {
  String txt = " World";
}

class Foo {
  String _hello;
  Bar _world; // never initialized
  String get hello {
    if (_hello == null) {
      _hello = "Hello";
    }
    return _hello;
  }
  String get world {
    if (_world == null) {
      _world = new Bar();
    }
    return _world.txt;
  }
}
```
dart2js output
```js
["", "reduced.dart",, T, {
  "^": "",
    main: function() {
    H.printString(H.Primitives_objectToHumanReadableString(new T.Foo(null, null)) + " hello");
  },
  Foo: {
    "^": "Object;_hello,_world"
   }
}, 1]
```
dart2js constructor retrieved by stepping into it at runtime
```js
function Foo(p__hello, p__world) {
this._hello = p__hello;
this._world = p__world;
}
Foo.builtin$cls="Foo";
$desc=$collectedClasses.Foo[1];
Foo.prototype = $desc;
```

**Comment by Markzipan** [comment]
These examples no longe reproduce in Dart2JS. Closing
