### ISSUE TITLE
Flag name shadowing

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11560]
I'd love to see some feedback from editor if I'm using a name that shadows a more global name. A hint or tip would be really helpful.

Thanks!
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.5.20_r24275 (2013-06-21)
OS: Mac OS X - x86_64 (10.8.4)
JVM: 1.6.0_45
# projects: 5
# open dart files: 9

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 988 / 988 / 273 MB
thread count: 40
index: 744164 relationships in 133605 keys in 703 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by srawlins** [comment]
Moved to https://github.com/dart-lang/linter/issues/597
