### ISSUE TITLE
language/constructor_negative_test

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#11586]
Missing &quot;new&quot; or &quot;const&quot; looks as function invocation, so is warning.
So, this test is not negative.

12.14.3 Unqualied Invocation

Otherwise, i is equivalent to this:id(a1; : : : ; an; xn+1 : an+1; : : : ; xn+k : an+k).

12.15.1 Ordinary Invocation

Let T be the static type of o. It is a static type warning if T does not have
an accessible (3.2) instance member named m. If T:m exists, it is a static type
warning if the type F of T:m may not be assigned to a function type.

**Comment by bkonyi** [comment]
This has already been fixed for Dart 1.0 and is perfectly valid for Dart 2.0 (optional new).
