### ISSUE TITLE
Function type alias (typedef) is not a constant

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#11592]
language/first_class_types_constants_test

---

12.1 Constants

&nbsp;* An identier expression that denotes a constant variable or a class.

---

---

15.3.1 Typedef

The eect of a type alias of the form typedef T id(T1 p1; : : : ; Tn pn;[Tn+1
pn+1; : : : ; Tn+k pn+k]) declared in a library L is is to introduce the name id into
the scope of L, bound to the function type (T1; : : : ; Tn;[Tn+1 pn+1; : : : ; Tn+k
pn+k]) ! T. The eect of a type alias of the form typedef T id(T1 p1; : : : ; Tn
pn;fTn+1 pn+1; : : : ; Tn+k pn+kg) declared in a library L is is to introduce the
name id into the scope of L, bound to the function type (T1; : : : ; Tn;fTn+1
pn+1; : : : ; Tn+k pn+kg) ! T.

---

As I can see, typedef (form for type alias) does not declare class.
So, it is not a constant.

**Comment by natebosch** [comment]
What is the expected action here?

**Comment by scheglov** [comment]
The spec has been updated since then to include type aliases into constants.
![image](https://user-images.githubusercontent.com/384794/45168022-374d3500-b1af-11e8-8385-c46f576f5661.png)

So, the test is OK now.
