### ISSUE TITLE
Use "external" and annotations for native extensions in the standalone VM, rather than "native"

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#11606]
The &quot;native&quot; keyword should be removed from native extension code, and replaced with
the &quot;external&quot; keyword and a @­Native() annotation.  For example:

int systemRand() native &quot;SystemRand&quot;;

should instead be written

@Native(&quot;SystemRand&quot;)
external int systemRand()

This makes all code, except the code in the VM's and the dart2js *_patch.dart files, obey the Dart language specification.

This seems like the best option, to keep &quot;native&quot; from spreading into external user code and libraries, since &quot;native&quot; is not part of the language specification and &quot;external&quot; is.

This is related to issues 
https://code.google.com/p/dart/issues/detail?id=5979
https://code.google.com/p/dart/issues/detail?id=9850
https://code.google.com/p/dart/issues/detail?id=9835
https://code.google.com/p/dart/issues/detail?id=10616 (The dart-ext: scheme)

**Comment by whesse** [comment]
This change to native extensions is still a TODO, and still should be done.  Until we have a different way of tracking desired enhancements, we should keep this in the bug tracker.

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
