### ISSUE TITLE
Flag unused booleans

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11625]
Would be nice if a statement like a == b;  (outside of a conditional expression) would be flagged as a warning by the editor.
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.5.20_r24275 (2013-06-21)
OS: Linux - i386 (3.2.5-gg1236)
JVM: 1.7.0-google-v5
# projects: 4
# open dart files: 9
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 967 / 373 / 91 MB
thread count: 42
index: 274485 relationships in 58089 keys in 311 sources

SDK installed: true
Dartium installed: true
analysis engine: new
______
**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-11625/comment-0/screenshot.png) (365.30 KB)

**Comment by pq** [comment]
Moved to the linter: https://github.com/dart-lang/linter/issues/226.
