### ISSUE TITLE
Standalone package tests failing to load unittest dependencies

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#11647]
The tests in tests/standalone/package construct their own packages directory, but still use the unittest package. Now that unittest has dependencies of its own, this is problematic.

Right now, it looks like the only test that's failing on the bots is the analyzer test for standalone/package/package_isolate_test. This seems to be because it's already marked as failing on the VM for some reason.

**Comment by matanlurey** [comment]
Unit test is not used
