### ISSUE TITLE
Bad operator== in dart2js_mirror.dart

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#11641]
dart/sdk/lib/_internal/compiler/implementation/mirrors/dart2js_mirror.dart:1256:17: Hint: The class &quot;Dart2JsDynamicMirror&quot; overrides &quot;operator==&quot;, but not &quot;get hashCode&quot;.
&nbsp;&nbsp;bool operator ==(Object other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
dart/sdk/lib/_internal/compiler/implementation/mirrors/dart2js_mirror.dart:1224:17: Hint: The class &quot;Dart2JsVoidMirror&quot; overrides &quot;operator==&quot;, but not &quot;get hashCode&quot;.
&nbsp;&nbsp;bool operator ==(Object other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
dart/sdk/lib/_internal/compiler/implementation/mirrors/dart2js_mirror.dart:1105:17: Hint: The class &quot;Dart2JsInterfaceTypeMirror&quot; overrides &quot;operator==&quot;, but not &quot;get hashCode&quot;.
&nbsp;&nbsp;bool operator ==(Object other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
dart/sdk/lib/_internal/compiler/implementation/mirrors/dart2js_mirror.dart:973:17: Hint: The class &quot;Dart2JsTypeVariableMirror&quot; overrides &quot;operator==&quot;, but not &quot;get hashCode&quot;.
&nbsp;&nbsp;bool operator ==(var other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
dart/sdk/lib/_internal/compiler/implementation/mirrors/dart2js_mirror.dart:850:17: Hint: The class &quot;Dart2JsClassMirror&quot; overrides &quot;operator==&quot;, but not &quot;get hashCode&quot;.
&nbsp;&nbsp;bool operator ==(Object other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^

**Comment by bkonyi** [comment]
Closing since `dart:mirrors` is no longer supported for web.
