### ISSUE TITLE
Dart2js source mirror DeclarationMirror.lookupInScope does not support constructors

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#11653]
Dart2js source mirror DeclarationMirror.lookupInScope does not support constructors

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
