### ISSUE TITLE
Errors and warnings in "analyze_tests"

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#11665]
There is quite a number of failing tests, most probably because they become stale after library changes.
Now, with work on https://codereview.chromium.org/18174010/ they become exposed.

---

**Attachment:**
[analyze_tests.txt](https://storage.googleapis.com/google-code-attachments/dart/issue-11665/comment-0/analyze_tests.txt) (83.76 KB)

**Comment by natebosch** [comment]
The linked issues are closed - I'll assume for now this is no longer a problem. Please reopen if there are still failing tests that make sense to track in this issue.
