### ISSUE TITLE
Support for synchronous network I/O in dart:io

### ISSUE THREAD

**Issue by DrMarcII** [dart-lang/sdk#11670]
I am trying to build infrastructure to support WebDriver-based testing, but these tests are very ugly due to the fact that the WebDriver bindings are asynchronous. In order to build synchronous bindings for WebDriver we need support in the dart:io for synchronous HTTP requests.

**Comment by bkonyi** [comment]
[Here](https://docs.google.com/document/d/1woImHEZEXec9-W99-sEEZjIGfkmryMwO5a249mbNWuo/edit#heading=h.fp4s19tmnphe) is the proposed API spec for SynchronousSocket and SynchronousDatagramSocket. If you have any feedback or suggestions, please feel free to make comments in the document!

**Comment by matanlurey** [comment]
@bkonyi If you want the document to be public (i.e. outside of Google), you'll need to open up permissions. Otherwise you might want to make that clear :)

**Comment by bkonyi** [comment]
The RawSynchronousSocket implementation has gone through review and has just been landed [here](https://github.com/dart-lang/sdk/commit/a1f87ebdb835efdc91db5f18f81603658f1f7e32). Assuming there's no major failures on the bots, I'll start work on the HTTP client today.

**Comment by postmasters** [comment]
**Raw** socket usually is used to denote the ability to craft your own packet (ethernet header, tcp header, tcp body, etc). Just saying.
