### ISSUE TITLE
Need a hint that dom elements cannot be extended

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11734]
Dart doesn't allow classes such as DivElment to be extended. The editor should flag this.

// Example which is not allowed by dart and should be flagged

class ActionButton extends DivElement {  // &lt;---- display error here !!!!
&nbsp;&nbsp;var a;

&nbsp;&nbsp;factory ActionButton(String string) {
&nbsp;&nbsp;text = string;
&nbsp;&nbsp;}
}

http://stackoverflow.com/questions/13002606/how-do-i-create-composite-components-in-dart

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.5.20_r24275 (2013-06-21)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_21
# projects: 3
# open dart files: 1
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 400 / 105 MB
thread count: 27
index: 321362 relationships in 74939 keys in 238 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by bwilkerson** [comment]
Closing as stale.
