### ISSUE TITLE
C Dart debugger APIs believe that class "dynamic" exists and then blow up when it is used

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#11807]
What steps will reproduce the problem?
1. enumerate the classes in a library and their parent classes using the dart reflection API
2. find that &quot;dynamic&quot; is a class
3. attempt to get fields on the class and blow up.

What is the expected output? What do you see instead?
I would expect that either &quot;dynamic&quot; never shows up as an actual class or that all regular class introspection methods work on class dynamic.

I have a workaround locally of special casing for class &quot;dynamic&quot; it isn't overly high priority to fix immediately.

**Comment by rmacnak-google** [comment]
Same cause as #12478
