### ISSUE TITLE
Proxy is not typed in a useful way

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11829]
Code completion not working in example chrome app.

For example,

// ...
bounds.left -= boundsChange ~/ 2;

appWindow.setBounds(bounds);
appWindow.set|

Popup does not list &quot;setBounds&quot;.
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.1.2_r24980 (2013-07-12)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_05
# projects: 1
# open dart files: 1
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 351 / 289 MB
thread count: 24
index: 150985 relationships in 34300 keys in 147 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by bwilkerson** [comment]
Closing as stale.
