### ISSUE TITLE
There is something fishy with IE9

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#11875]
Spotted this failure http://chromegw.corp.google.com/i/client.dart/builders/dart2js-ie9-win7-all-5-6/builds/3793:

FAILED: dart2js-ie9 release_ia32 corelib/set_iterator_test
Expected: pass 
Actual: fail
CommandOutput[dart2js]:
CommandOutput[ie9]:

stdout:

&nbsp;&nbsp;&lt;h1&gt; Running /E:/b/build/slave/dart2js-ie9-win7-all-5-6/build/dart/tests/corelib/set_iterator_test.dart &lt;/h1&gt;
&nbsp;&nbsp;&lt;script type=&quot;text/javascript&quot; src=&quot;/root_dart/pkg/unittest/lib/test_controller.js&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script onerror=&quot;externalError(null)&quot; type=&quot;text/javascript&quot; src=&quot;/root_build/generated_tests/dart2js-ie9/tests_corelib_set_iterator_test/test.js&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script type=&quot;text/javascript&quot; src=&quot;/root_dart/pkg/browser/lib/dart.js&quot;&gt;&lt;/script&gt;
&nbsp;&nbsp;&lt;script type=&quot;text/javascript&quot; src=&quot;/root_dart/pkg/browser/lib/interop.js&quot;&gt;&lt;/script&gt;

&lt;pre&gt;Expect.equals(expected: &amp;lt;0&amp;gt;, actual: &amp;lt;2500&amp;gt;) fails.&lt;/pre&gt;&lt;pre&gt;Error: Some tests failed.&lt;/pre&gt;&lt;pre&gt;FAIL&lt;/pre&gt;

To retest, run:  E:\b\build\slave\dart2js-ie9-win7-all-5-6\build\dart\tools\testing\bin\windows\dart.exe /E:/b/build/slave/dart2js-ie9-win7-all-5-6/build/dart/tools/testing/dart/http_server.dart -p 51271 -c 51272 --build-directory=E:\b\build\slave\dart2js-ie9-win7-all-5-6\build\dart\build\ReleaseIA32 --runtime=ie9

Command[0]: build\ReleaseIA32\dart-sdk\bin\dart2js.bat --package-root=build/ReleaseIA32/packages/ --out=E:/b/build/slave/dart2js-ie9-win7-all-5-6/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/tests_corelib_set_iterator_test/test.js /E:/b/build/slave/dart2js-ie9-win7-all-5-6/build/dart/tests/corelib/set_iterator_test.dart
Took 0:00:03.042000

Command[1]: python E:\b\build\slave\dart2js-ie9-win7-all-5-6\build\dart\tools\testing\run_selenium.py --browser=ie9 --timeout=60 --out=http://127.0.0.1:51271/root_build/generated_tests/dart2js-ie9/tests_corelib_set_iterator_test/test.html?crossOriginPort=51272
Took 0:00:00.281000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -t60 -rie9 -cdart2js --use-sdk corelib/set_iterator_test

**Comment by dgrove** [comment]
ie9 is no longer supported.
