### ISSUE TITLE
dart2js mirrors: metadata missing from some variables in a variable declaration

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#11908]
I think this is a dart2js issue but not 100% sure. Consider the following program:

---

import 'dart:mirrors';

main() {
&nbsp;&nbsp;for (var field in reflect(new FooBar()).type.variables.values) {
&nbsp;&nbsp;&nbsp;&nbsp;print('field ${field.simpleName} has metadata '
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'${field.metadata.map((m) =&gt; m.reflectee).join()}');
&nbsp;&nbsp;}
}

const hello = 'hello';

class FooBar {
&nbsp;&nbsp;@­hello var x, y, z;
}

---

On VM it prints:

field Symbol(&quot;y&quot;) has metadata hello
field Symbol(&quot;x&quot;) has metadata hello
field Symbol(&quot;z&quot;) has metadata hello

On dart2js+d8 it prints:

field Symbol(&quot;x&quot;) has metadata hello
field Symbol(&quot;y&quot;) has metadata 
field Symbol(&quot;z&quot;) has metadata 

Note that &quot;y&quot; and &quot;z&quot; are missing metadata.

Since you can only specify metadata on the declaredIdentifier in the variableDeclaration (http://www.dartlang.org/docs/spec/latest/dart-language-specification.html#h.55kzc4r0q21p) , it makes me think metadata should apply to all of the identifiers.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
