### ISSUE TITLE
Warn on return statements in finally blocks when the try block returns?

### ISSUE THREAD

**Issue by polux** [dart-lang/sdk#11924]
I propose we warn (or hint) on return blocks in finally blocks  when the try block returns. I had to run the following code to make sure of what it prints:

```dart
g() { print("c"); return 1; }

f() {
  try {
    print("a");
    return g();
  } finally {
    print("b");
    return 2;
  }
}

main() { print(f()); }
```

**Comment by srawlins** [comment]
This has been implemented as the [control_flow_in_finally](http://dart-lang.github.io/linter/lints/control_flow_in_finally.html) lint rule.
