### ISSUE TITLE
dart2js produces illegible error when library prefix used as expression

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#11931]
**What steps will reproduce the problem?**
1. Compile this:

import 'dart:collection' as col;

foo(a) {}

main() {
&nbsp;&nbsp;foo(col).x();
}

What is the expected output?

An error message that:
a. Points to the offending line &quot;foo(col).x();&quot;, not the import statement
b. Contains the correct error description, e.g. &quot;library prefix 'col' used as expression&quot;

What do you see instead?

This:

&quot;&quot;&quot;
a.dart:1:1: Internal error: unexpected element kind prefix
import 'dart:collection' as col;
^^^^^^
Error: Compilation failed.
&quot;&quot;&quot;

**What version of the product are you using? On what operating system?**

Dart-to-JavaScript compiler (dart2js) version: 0.6.6.0_r25119

**Please provide any additional information below.**

An alternative fix would be to make libraries true objects that could be passed as values :)

**Comment by sigmundch** [comment]
handled in the FE
