### ISSUE TITLE
Part directives are confusing

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#11975]
**[user feedback]**

Really mystery wich of these part / part of announcements dart accepts.

Must use &quot;&quot;   or  ' '  ?

Must use  .dart  ?

why:        part of  myprogram;       is marked as an error ??

For beginners this is..  little bit messy....

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.6.5_r25017 (2013-07-15)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_21
# projects: 4
# open dart files: 4

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 561 / 310 MB
thread count: 24
index: 471423 relationships in 107203 keys in 607 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by munificent** [comment]
I think this will be resolved by #20792.
