### ISSUE TITLE
Don't skip LibTest/core/List/sort_A01_t04 on jsshell

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#11992]
See CL https://codereview.chromium.org/16938012/.

It seems like it was the compiler that timed out, not jsshell.

Now the status file says:

LibTest/core/List/sort_A01_t04: Pass, Timeout # Must be a bug in jsshell, test sometimes times out.

However, the test is already marked slow, and there was a bug in our test runner so that marking a test slow didn't allow the compilation longer time to complete.

I believe that the special case for jsshell should be removed now.

**Comment by zoechi** [comment]
Is this supposed to be reopened?
