### ISSUE TITLE
distinguish static methods from top-level functions in dart2js mirrors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#12133]
In dart2js mirrors, we seem to be including static methods together with top-level methods in the library mirror (this doesn't match the VM behavior). Additionally, the MethodMirror of those methods indicates that the method is topLevel and that declaring owner is the library (rather than the containing class), so it is not possible to distinguish a static method from a top-level method.

To reproduce this problem, take a look at this example:

library foo;
import 'dart:mirrors';

class A {
&nbsp;&nbsp;static void one() {}
}
void two() { }

main() {
&nbsp;&nbsp;var lib = currentMirrorSystem().findLibrary(const Symbol('foo')).first;

&nbsp;&nbsp;print(&quot;top-level:&quot;);
&nbsp;&nbsp;lib.functions.forEach((k, v) {
&nbsp;&nbsp;&nbsp;&nbsp;print('${k}: ${v.simpleName} ${v.isTopLevel}, ${v.owner.simpleName}');
&nbsp;&nbsp;});

&nbsp;&nbsp;print(&quot;\nin class:&quot;);
&nbsp;&nbsp;lib.classes.values.forEach((c) {
&nbsp;&nbsp;&nbsp;&nbsp;c.methods.forEach((k, v) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('${c.simpleName}.${k}: ${v.simpleName} ${v.isTopLevel}, ${v.owner.simpleName}');
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;});
}

In the VM, this program produces this output:

&nbsp;&nbsp;top-level:
&nbsp;&nbsp;Symbol(&quot;main&quot;): Symbol(&quot;main&quot;) true, Symbol(&quot;foo&quot;)
&nbsp;&nbsp;Symbol(&quot;two&quot;): Symbol(&quot;two&quot;) true, Symbol(&quot;foo&quot;)

&nbsp;&nbsp;in class:
&nbsp;&nbsp;Symbol(&quot;A&quot;).Symbol(&quot;one&quot;): Symbol(&quot;one&quot;) false, Symbol(&quot;A&quot;)

With dart2js, this is the output:

&nbsp;&nbsp;top-level:
&nbsp;&nbsp;Symbol(&quot;one&quot;): Symbol(&quot;one&quot;) true, Symbol(&quot;foo&quot;)
&nbsp;&nbsp;Symbol(&quot;main&quot;): Symbol(&quot;main&quot;) true, Symbol(&quot;foo&quot;)
&nbsp;&nbsp;Symbol(&quot;two&quot;): Symbol(&quot;two&quot;) true, Symbol(&quot;foo&quot;)

&nbsp;&nbsp;in class:
&nbsp;&nbsp;Symbol(&quot;main_closure&quot;).Symbol(&quot;call&quot;): Symbol(&quot;call&quot;) false, Symbol(&quot;main_closure&quot;)
&nbsp;&nbsp;Symbol(&quot;main__closure&quot;).Symbol(&quot;call&quot;): Symbol(&quot;call&quot;) false, Symbol(&quot;main__closure&quot;)
&nbsp;&nbsp;Symbol(&quot;A&quot;).Symbol(&quot;one&quot;): Symbol(&quot;one&quot;) false, Symbol(&quot;A&quot;)
&nbsp;&nbsp;Symbol(&quot;main_closure0&quot;).Symbol(&quot;call&quot;): Symbol(&quot;call&quot;) false, Symbol(&quot;main_closure0&quot;)

Note that:
&nbsp;\- &quot;one&quot; is listed in lib.functions
&nbsp;\- such &quot;one&quot; method has [isTopLevel] is true and has &quot;foo&quot; as the owner.
&nbsp;\- some additional classes are shown (&quot;main_closure&quot;, etc)

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
