### ISSUE TITLE
In these tests 'a' has dynamic type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#12162]
...so, it statically it is assignable to anything.
So, no static warnings.

type_variable_bounds2_test/00: fail
type_variable_bounds2_test/01: fail
type_variable_bounds2_test/02: fail
type_variable_bounds2_test/03: fail
type_variable_bounds2_test/04: fail
type_variable_bounds2_test/06: fail

**Comment by bkonyi** [comment]
This test has been rewritten for Dart 2.
