### ISSUE TITLE
Ambiguous import is now static warning, never error

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#12191]
https://code.google.com/p/dart/issues/detail?id=12106

prefix3_negative_test: fail
library_ambiguous_test/00: fail
library_ambiguous_test/01: fail
library_ambiguous_test/02: fail
library_ambiguous_test/03: fail

**Comment by natebosch** [comment]
Are there still tests to update? Our tools are doing the correct thing AFAIK.

**Comment by scheglov** [comment]
Yes, now that all problems in the specification are errors, this issue does not matter.
