### ISSUE TITLE
makeConstantList a candidate for minification?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#12208]
I compiled an app with a lost of const [...] definitions.

I noticed a mountain of

$.Ni=I.makeConstantList([1,0,3,2])
$.vL=I.makeConstantList([1,100,80])
$.G0=I.makeConstantList([1,134,108])
$.fM=I.makeConstantList([1,26,13])
$.Gx=I.makeConstantList([1,26,16])
$.J3=I.makeConstantList([1,26,19])
$.c1=I.makeConstantList([1,26,9])
$.c5=I.makeConstantList([1,44,16])
$.c3=I.makeConstantList([1,44,22])
$.SH=I.makeConstantList([1,44,28])
$.z1=I.makeConstantList([1,44,34])
$.Bb=I.makeConstantList([1,70,44])
...

I.mcl([...]) would save a lot of bytes

**Comment by rakudrama** [comment]
The repetition of `I.makeConstantList` is nowadays avoided by copying the function to a local that gets minified to a single character.
