### ISSUE TITLE
Incorrect error messages for ===

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#12347]
Username: kasperl

If I use &equals;&equals;&equals; in my code, I get pretty bizarre warnings. For this (wrong) code:

&nbsp;&nbsp;if (hashCode == entry.hashCode &amp;&amp; entry.key &equals;&equals;&equals; key)

I get these 2 problems and one warning:

Expected an identifier
Illegal assignment to non-assignable expression
Undefined name ''

I would have expected to be told that there is no &equals;&equals;&equals; operator.

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.6.15_r25822 (2013-08-06)
OS: Mac OS X - x86_64 (10.8.4)
JVM: 1.6.0_51
# projects: 2
# open dart files: 3

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 996 / 148 / 61 MB
thread count: 19

index: 157401 relationships in 35920 keys in 152 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by pq** [comment]
This is greatly improved.  Regardless, future work should be tracked in fresh issues on the CFE.
