### ISSUE TITLE
Unhelpful errors for decr operator

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#12346]
Username: kasperl

I have some code and when I by accident change a '-' in the source code to '--', I get 6 problems and one warning.

int index = hashCode &amp; (buckets.length -- 1);

Expected an identifier
Expected to find ')'
Expected to find ';'
Expected to find ';'
Expected to find ';'
Unexpected token ')'
Undefined name ''

Somehow these warnings do not really help me spot the problem.

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.6.15_r25822 (2013-08-06)
OS: Mac OS X - x86_64 (10.8.4)
JVM: 1.6.0_51
# projects: 2
# open dart files: 3

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 996 / 148 / 66 MB
thread count: 17
index: 157401 relationships in 35920 keys in 152 sources

SDK installed: true
Dartium installed: true
analysis engine: new

**Comment by srawlins** [comment]
Interesting. Here's a better example:

```dart
void main() {
  int a = 7;
  int b = a -- 2;
  b = 5 & (a -- 2);
}
```

(https://dartpad.dartlang.org/e1e1b8a97f5958fa80ed007dd73bec93)

On line 3, there is a simple error: `Unexpected token '2'`. But on line 4, it doesn't recover as well:

> error: Expected to find ';'
> error: Expected to find ')'
> error: Unexpected token ')'

**Comment by srawlins** [comment]
And now it's even better: one error on line 3, two on line 4:

```none
$ cat 12346.dart 
void main() {
  int a = 7;
  int b = a -- 2;
  b = 5 & (a -- 2);
}
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ dartanalyzer --preview-dart-2 12346.dart 
Analyzing 12346.dart...
  error • Unexpected text '2' at 12346.dart:3:16 • unexpected_token
  error • Expected to find ')' at 12346.dart:4:17 • expected_token
  error • Unexpected text ')' at 12346.dart:4:18 • unexpected_token
  hint • The value of the local variable 'b' isn't used at 12346.dart:3:7 • unused_local_variable
3 errors and 1 hint found.
```
