### ISSUE TITLE
Make accessing "this" in initializers a runtime error, not a static error.

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#12352]
This would allow &quot;this&quot; references in closures declared in initializers that aren't invoked until after the instance is fully initialized. This would be very convenient for 

\* Default values for function-valued fields:

class A {
&nbsp;&nbsp;var x;
&nbsp;&nbsp;var reset = () { x = 0; };
}

\* Similarly, closures used in declarative configuration of objects, in the style that's popular with JS frameworks like Ember, Angular, etc.:

class MyApp extends App {
&nbsp;&nbsp;var section;
&nbsp;&nbsp;final router = new Router({
&nbsp;&nbsp;&nbsp;&nbsp;'home': route('/')..onEnter.listen((e) =&gt; section = 'home');
&nbsp;&nbsp;&nbsp;&nbsp;'one': route('/page_one')..onEnter.listen((e) =&gt; section = 'one');
&nbsp;&nbsp;});
}

Of course the closures could be executed before the object is initialized, but in many cases they just capture the 'this' reference and access it later. By not allow 'this' references in initializers at all we force some initialization to happen in the constructor body and thus limit the use of final in these cases.

**Comment by natebosch** [comment]
Resolving as a duplicate of #33857 because that issue has more active discussion.
