### ISSUE TITLE
It is compile-time error to invoke not existing function

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#12381]
language/issue11724_test
language/call_nonexistent_static_test/08

main() {
&nbsp;&nbsp;f()
}

&nbsp;&nbsp;f() is unqualified invocation 12.14.3.
&nbsp;&nbsp;&quot;An unqualified function invocation i has the form
id(a1; : : : ; an; xn+1 : an+1; : : : ; xn+k : an+k),
where id is an identier.&quot;

&nbsp;&nbsp;And because &quot;f&quot; is not defined, we use &quot;Otherwise, i is equivalent to this:id(a1; : : : ; an; xn+1 : an+1; : : : ; xn+k : an+k).&quot;

&nbsp;&nbsp;But in 12.10 it is specified that &quot;It is a compile-time error if this appears in a top-level function or variable
initializer, in a factory constructor, or in a static method or variable initializer,
or in the initializer of an instance variable.&quot;

**Comment by natebosch** [comment]
Can this be closed? Do the tests need to be updated or removed?
