### ISSUE TITLE
co19/LibTest/core/Stopwatch/start_A01_t03 flaky on windows

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#12383]
From https://code.google.com/p/co19/issues/detail?id=484

see http://chromegw.corp.google.com/i/client.dart/builders/vm-win32-trunk .

http://chromegw.corp.google.com/i/client.dart/builders/vm-win32-trunk/builds/190/steps/tests/logs/stdio

FAILED: none-vm release_ia32 co19/LibTest/core/Stopwatch/start_A01_t03
Expected: pass 
Actual: fail
CommandOutput[vm\]:

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#­0      Expect._fail (file:///E:/b/build/slave/vm-win32-trunk/build/dart/tests/co19/src/Utils/expect.dart:287:5)
#­1      Expect.isTrue (file:///E:/b/build/slave/vm-win32-trunk/build/dart/tests/co19/src/Utils/expect.dart:30:10)
#­2      main (file:///E:/b/build/slave/vm-win32-trunk/build/dart/tests/co19/src/LibTest/core/Stopwatch/start_A01_t03.dart:37:16)

Command[vm\]: build\ReleaseIA32\dart.exe --ignore-unrecognized-flags --package-root=build/ReleaseIA32/packages/ E:\b\build\slave\vm-win32-trunk\build\dart\tests\co19\src\LibTest\core\Stopwatch\start_A01_t03.dart
Took 0:00:00.094000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -t60 co19/LibTest/core/Stopwatch/start_A01_t03

**Comment by rmacnak-google** [comment]
c99df050b106830ab22606caca8cae2142f55ef7
