### ISSUE TITLE
Using undeclared (or hidden) variable is warning, not error

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#12397]
language/scope_negative_test

3.1 Scoping
If a declaration d named n is in the namespace induced by a scope S, then d
hides any declaration named n that is available in the lexically enclosing scope
of S.

12.30 Identier Reference
It is as static warning if an identier expression id occurs inside a top level or
static function (be it function, method, getter, or setter) or variable initializer
and there is no declaration d with name id in the lexical scope enclosing the
expression.

12.13 Property Extraction
12.14.3 Unqualied Invocation
Let T be the static type of o. It is a static type warning if T does not have
an accessible (3.2) instance member named m.

**Comment by natebosch** [comment]
I'm pretty sure this is intended to be an error now.

Can this be closed? Does the test need to be updated or removed?

**Comment by eernstg** [comment]
Closing:

I believe this issue reports a problem with `tests/language/scope_negative_test.dart`, which was merged into `tests/language/scope_variable_test.dart` in 6a02eca2d3ba05e63490ece8a6cfdb1380025939, which was later corrected in 1f2051f88a80c962068f5a4946b3dacdaa213c7b (Sep 2013) and copied (with no changes) into language_2 in 354a4ec42030f0b02230f8c0e2419a57cb230413 (Oct 2017).

That test looks OK (no need to remove anything), and there are no status entries.
