### ISSUE TITLE
Build and use tip-of-tree Chromium content shell on bots

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#12416]
Can we build Chromium content shell from tip-of-tree (or perhaps http://dev.chromium.org/developers/how-tos/get-the-code#TOC-LKGR) on a semi-regular basis and use that for our dart2js tests?

Ideally, using a new content shell would trigger a separate line in the waterfall, so we could see that new failures are due to the new content shell.

Today, we're seeing failures (e.g., &quot;int is not int&quot;) only when we do Dartium rolls.

**Comment by athomas** [comment]
We are no longer using content shell.
