### ISSUE TITLE
ClassMirror method for determining if one class descends from another

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#12439]
It would be very useful for ClassMirror to expose a method that takes another ClassMirror and returns whether or not the first ClassMirror descends from the second (that is, the latter ClassMirror appears anywhere in the transitive superclass and superinterface tree of the former).

**Comment by bkonyi** [comment]
I believe this is covered by [ClassMirror.isSubclassOf](https://api.dartlang.org/dev/2.0.0-dev.40.0/dart-mirrors/ClassMirror/isSubclassOf.html).
