### ISSUE TITLE
Need a better validation when there are native fields in a class (direct or from the super class chain)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#12455]
Currently the VM has a check to ensure that there is a native resolver in the library in which classes with native fields are defined. This is a
bit restrictive and we need a better validation scheme.

Maybe we don't predefine NativeFieldWrapper classes and instead have them
be defined by the embedder, the burden of validating then falls on the
embedder.

**Comment by mraleph** [comment]
Nothing is happening since 2013. Please reopen @a-siva if you consider working on this any time soon.
