### ISSUE TITLE
tests/lib/mirrors/mixin_test.dart is broken

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#12464]
The test doesn't work without @­MirrorsUsed.

The test assumes an anonymous mixin application is named 'M1(M2(Super))' but it should be 'Super with M2, M1'.

The test assumes constructors are members, but they are not.

The mixin is the owner of members, but not the constructor (which is explicitly copied down per the specification).

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
