### ISSUE TITLE
support private _main in Dart?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#12460]
This bug is more a channel for discussion. I ran recently into this situation and it made me ponder things a bit. 

I was wondering if there are any reasons why 'main' has to be public, or if it should actually be private (for example, suppose we call it '_main').

The rationale for this is that it would make it easy to write libraries that serve both as libraries and entrypoints, without having to hide their 'main' method.

For example:

&nbsp;a.dart:
&nbsp;&nbsp;library a;
&nbsp;&nbsp;x = 1;
&nbsp;&nbsp;_main() =&gt; print(x);

&nbsp;b.dart:
&nbsp;&nbsp;import 'a.dart';
&nbsp;&nbsp;y = x + 1;
&nbsp;&nbsp;_main() =&gt; print(y);

The idea is that these programs would have no conflicts in their imports and could be run as entrypoints (&quot;dart a.dart&quot; prints '1', &quot;dart b.dart&quot; prints '2').

This sounds like a minor improvement because you could write this with 'hide' directives today:
&nbsp;a.dart:
&nbsp;&nbsp;library a;
&nbsp;&nbsp;x = 1;
&nbsp;&nbsp;main() =&gt; print(x);

&nbsp;b.dart:
&nbsp;&nbsp;import 'a.dart' hide main;
&nbsp;&nbsp;y = x + 1;
&nbsp;&nbsp;main() =&gt; print(y);

But it brings up two questions:
&nbsp;\- what is more appropriate: a public or private method?
&nbsp;\- should we support this in the future?

**Comment by munificent** [comment]
Not a bad idea, but also probably not worth the effort. Given how ancient this request is, we seem to be able to live without it OK. :)
