### ISSUE TITLE
Provide cleaner way to detect file not found and directory not found errors

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#12461]
If you try to perform an IO operation on a non-existent entity, you'll get either a FileException or a DirectoryException whose OSError has an errorCode of 2 on Mac/Linux and 3 on Windows. This makes handling a file-not-found error at runtime awkward.

How about a custom NotFoundException type?

Also, what's the difference between DirectoryException and FileException? They seem to have the same state.

**Comment by Keithcat1** [comment]
I'm also a little interested in this. Languages like Python will raise a FileNotFound error and not just an IoError.
I guess this will have to be changed in Dart 3, unless it won't break compatibility?

**Comment by brianquinlan** [comment]
> If you try to perform an IO operation on a non-existent entity, you'll get either a FileException or a DirectoryException whose OSError has an errorCode of 2 on Mac/Linux and 3 on Windows...

I agree with the issue overall but do you have a repro where a non-existent file generates a `errorCode` or 3 on Windows?

I just tested with `File.openRead` and get `errorCode` 2.

**Comment by brianquinlan** [comment]
PR in progress here: https://dart-review.googlesource.com/c/sdk/+/267280

**Comment by brianquinlan** [comment]
Fixed in b75f8aaaf50eaac586cb168a0007eed37dedbae4
