### ISSUE TITLE
VM: importing dart:core with a prefix hides dynamic

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#12478]
import 'dart:core' as core;

main(){
&nbsp;&nbsp;// Should still be available because it is not a member of dart:core.
&nbsp;&nbsp;Expect.isTrue(dynamic is Type);
&nbsp;&nbsp;
&nbsp;&nbsp;Expect.throws(() =&gt; mycore.dynamic is Type,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(e) =&gt; e is NoSuchMethodError,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'dynamic is not a member of dart:core');
}

**Comment by zanderso** [comment]
@mhausner @rmacnak-google This appears to still happen, but is it still incorrect? Is this issue stale?

**Comment by rmacnak-google** [comment]
I believe this issue is still valid.

tests/language/dynamic_prefix_core_test.dart isn't marked as failing for kernel though, so it will probably end up fixed by the new front end.

**Comment by mhausner** [comment]
This is still valid, but will be obsolete with the new front-end. I don't see a reason to fix this for the current front-end.

As @rmacnak-google observes, this works in the new Front-end, so closing the issue.

**Comment by eernstg** [comment]
This is closed, but in case anyone ever takes a look here: Please note that `dynamic` _is_ exported by 'dart:core', and `tests/language{,_2}/import_core_prefix_test.dart` need to be updated as described in #32060.
