### ISSUE TITLE
Missing dependency to generator files when building the editor.

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#12483]
If a file in editor/tools/plugins/com.google.dart.tools.core/src/com/google/dart/tools/core/generator/chrome (e.g. build.dart) is changed building the editor again using:

$ tools/test.py -mrelease editor

Does not detect the change and nothing is build.

Touching a java file is needed to kick off a new build.

**Comment by athomas** [comment]
No more editor :)
