### ISSUE TITLE
Test makes the VM hit an ASSERT: tests/co19/src/LibTest/isolate/isolate_api/spawnFunction_A02_t01.dart

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#12506]
In debug mode, the test tests/co19/src/LibTest/isolate/isolate_api/spawnFunction_A02_t01.dart hits an ASSERT  (r26267):

~/dart $ gdb --args out/DebugIA32/dart tests/co19/src/LibTest/isolate/isolate_api/spawnFunction_A02_t01.dart
Reading symbols from /usr/local/google/home/kustermann/src/dart_all/dart/out/DebugIA32/dart...done.
(gdb) r
Starting program: /usr/local/google/home/kustermann/src/dart_all/dart/out/DebugIA32/dart tests/co19/src/LibTest/isolate/isolate_api/spawnFunction_A02_t01.dart
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/usr/grte/v3/lib64/libthread_db.so.1&quot;.
runtime/lib/isolate.cc:268: error: expected: ctx.num_variables() == 0

Program received signal SIGABRT, Aborted.
0xf7fdb430 in __kernel_vsyscall ()
(gdb) bt
# ­0  0xf7fdb430 in __kernel_vsyscall ()
# ­1  0xf7ce31df in raise () from /lib/i386-linux-gnu/libc.so.6
# ­2  0xf7ce6825 in abort () from /lib/i386-linux-gnu/libc.so.6
# ­3  0x080980a3 in dart::DynamicAssertionHelper::Fail (this=&lt;optimized out&gt;, format=&lt;optimized out&gt;) at runtime/platform/assert.cc:40
# ­4  0x0853d9bc in isolate (this=&lt;optimized out&gt;, arguments=&lt;optimized out&gt;, this=&lt;optimized out&gt;, isolate=

&nbsp;&nbsp;&nbsp;&nbsp;{dart::Isolate *(dart::StackZone *, dart::NativeArguments *, const dart::NativeArguments *, dart::BaseIsolate *, dart::Isolate *)} 0x853d031 &lt;dart::BootstrapNatives::DN_isolate_spawnFunction(_Dart_NativeArguments*)+353&gt;, isolate=
&nbsp;&nbsp;&nbsp;&nbsp;{dart::Isolate *(dart::StackZone *, dart::NativeArguments *, const dart::NativeArguments *, dart::BaseIsolate *, dart::Isolate *)} 0x853d031 &lt;dart::BootstrapNatives::DN_isolate_spawnFunction(_Dart_NativeArguments*)+353&gt;, this=&lt;optimized out&gt;)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/lib/isolate.cc:268
# ­5  dart::BootstrapNatives::DN_isolate_spawnFunction (args=&lt;optimized out&gt;) at runtime/lib/isolate.cc:226
# ­6  0xf5c32190 in ?? ()
# ­7  0xf3a41e9a in ?? ()
# ­8  0xf3a41dae in ?? ()
# ­9  0xf3a41b49 in ?? ()
# ­10 0xf3a31087 in ?? ()
# ­11 0x080e430e in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=..., context=...)

&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_entry.cc:68
# ­12 0x080e4001 in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=...)

&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_entry.cc:37
# ­13 0x080e3dc2 in dart::DartEntry::InvokeFunction (function=..., arguments=...) at runtime/vm/dart_entry.cc:27
# ­14 0x0806bd4f in Dart_Invoke (target=&lt;optimized out&gt;, name=&lt;optimized out&gt;, number_of_arguments=&lt;optimized out&gt;,

&nbsp;&nbsp;&nbsp;&nbsp;arguments=&lt;optimized out&gt;) at runtime/vm/dart_api_impl.cc:3114
# ­15 0x08052c5f in dart::bin::main (argc=20, argv=&lt;optimized out&gt;) at runtime/bin/main.cc:842
# ­16 0xf7cce4d3 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
# ­17 0x08051eb5 in _start ()

(gdb)

**Comment by zanderso** [comment]
This crash does not appear to reproduce.
