### ISSUE TITLE
Dart VM: A closure should be invokable via 'call'.

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#12550]
((p1) =&gt; &quot;$p1&quot;)(3)  -&gt; &quot;3&quot;
((p1) =&gt; &quot;$p1&quot;).call(3) -&gt; reports error

co19/Language/12_Expressions/14_Function_Invocation/4_Function_Expression_Invocation_A05_t01

**Comment by rmacnak-google** [comment]
Was fixed sometime in 2014.
