### ISSUE TITLE
Support understands() method/construct on objects

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#12606]
A mechanism for detecting if an object understands a given method/getter/setter is needed

**Comment by munificent** [comment]
Given all of the pain that `noSuchMethod()` has caused for our ahead-of-time static compilers, we're pretty disinclined to put more metaprogramming APIs right on Object itself. :)

Adding members to Object is also a big breaking change and prevents user-defined classes from using that name. We'd rather these kinds of APIs be separated out into a separate distinct meta layer—i.e. mirrors.

**Comment by rmacnak-google** [comment]
noSuchMethod() does not cause any pain for the VM's ahead-of-time compiler.

**Comment by munificent** [comment]
> noSuchMethod() does not cause any pain for the VM's ahead-of-time compiler.

If the VM was our only compiler, lots of things would be easier. :)
