### ISSUE TITLE
Invalid CSS property name: -webkit-touch-callout

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#12709]
**[user feedback]**

Generated sunflower application from Welcome page.

Ran &quot;sunflower.dart&quot; (run button), received the followng
output message:
&nbsp;&nbsp;&nbsp;&quot;Invalid CSS property name: -webkit-touch-callout&quot;

There was some quick display at the top of the new panel, but I could
not read it. It disappeared too quickly.
Application seemed to work correctly - did not expect Output error message.

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.6.19_r26297 (2013-08-17)
OS: Windows 7 - x86 (6.1)
JVM: 1.7.0_25
# projects: 3
# open dart files: 0
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 967 / 178 / 95 MB
thread count: 27
index: 159557 relationships in 36627 keys in 154 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
I don't think this exists any more.

```
sdk$ git grep webkit-touch
sdk$
```
