### ISSUE TITLE
A number of language/type_variable_bounds* tests fail on dart2js

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#12702]
The failures are only in checked mode.

Currently it is

&nbsp;&nbsp;type_variable_bounds_test/01
&nbsp;&nbsp;type_variable_bounds_test/02
&nbsp;&nbsp;type_variable_bounds_test/04
&nbsp;&nbsp;type_variable_bounds_test/05
&nbsp;&nbsp;type_variable_bounds2_test/00
&nbsp;&nbsp;type_variable_bounds2_test/03
&nbsp;&nbsp;type_variable_bounds2_test/05
&nbsp;&nbsp;type_variable_bounds3_test/00

And apparently

&nbsp;&nbsp;type_variable_bounds2_test/06

pass for the wrong reason

**Comment by sigmundch** [comment]
close - the status file reflect the contents of this bug.
