### ISSUE TITLE
Class is not emitted for reflection if it is not instantiated.

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#12799]
This fails:

@MirrorsUsed(targets: 'C.foo')
import 'dart:mirrors';

class C {
&nbsp;&nbsp;static var foo;
&nbsp;&nbsp;static var bar;
}

main() =&gt; reflectClass(C);

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
