### ISSUE TITLE
Annotate warnings if the analyzer can infer that they are false positives

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#12821]
This code:

&nbsp;&nbsp;&nbsp;&nbsp;Object a = &quot;a string&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;if (a is String) a.length;

currently generates a type warning even though there no type error can occur in this code at runtime. Determining that fact, however, requires some primitive flow-based type analysis, which is tricky to specify in some corner cases. I'd like to propose a solution:

1. The language specification does not try to handle this case. Instead, it mandates that a warning \*should\* be generated in the above code, but allows that such a warning may be decorated or annotated by an analyzer that does more sophisticated type analysis.

2. The analyzer can then do flow analysis using whatever algorithm it sees fit and mark warnings like the above as false positives.

This would:

1. Keep the spec simple and free from having to define any flow-sensitive analysis algorithm.
2. Keep all tools consistently generating the same set of warnings so users aren't confused.
3. Let users easily tell which warnings are false positives and ignore them.

**Comment by srawlins** [comment]
The original example no longer generates warnings; type is inferred after `is` checks. Close?

**Comment by bwilkerson** [comment]
Yeah. Strong mode will probably negate the value of this idea.
