### ISSUE TITLE
Test language/not_enough_positional_arguments_test.dart is failing on dart2js

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#12838]
The following parts of the multi-test is failing:

&nbsp;&nbsp;not_enough_positional_arguments_test/01
&nbsp;&nbsp;not_enough_positional_arguments_test/02
&nbsp;&nbsp;not_enough_positional_arguments_test/04
&nbsp;&nbsp;not_enough_positional_arguments_test/05

**Comment by sigmundch** [comment]
status tracking now done directly on .status files.
