### ISSUE TITLE
corelib/collection_length_test dart2js generated output takes a long time in checked mode on IE

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#12844]
This is regularly timing out, e.g., 
http://build.chromium.org/p/client.dart/builders/dart2js-ie9-win7-all-5-6/builds/4497/steps/dart2js%20tests%20--checked%20failures/logs/stdio

I will mark it in the status file

**Comment by matanlurey** [comment]
Checked mode is a goner
