### ISSUE TITLE
mirrors/return_type_test is flaky on Safari

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#12858]
lib/mirrors/return_type_test is flaky on Safari. It just timed out (whereas previous runs didn't show up in the slow-tests list).

http://build.chromium.org/p/client.dart/builders/dart2js-safari-mac10.7-3-3/builds/6227/steps/dart2js%20tests%20failures/logs/stdio

Marking as flaky.

**Comment by srawlins** [comment]
Mirrors support on the web/dart2js is removed. [Announcement](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/djfFMNCWmkE).
