### ISSUE TITLE
Alignment problem on ARM

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#12868]
co19/LibTest/typed_data/Float32List/Float32List.view_A01_t02: Crash
co19/LibTest/typed_data/Float32x4/toUint32x4_A01_t02: Fail
co19/LibTest/typed_data/Float64List/Float64List.view_A01_t02: Crash

**Comment by zanderso** [comment]
@fsc8000 Does https://github.com/dart-lang/sdk/commit/fb75e1e5e481334260b2fd467393a367fc74389a help with this?

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/issues/22151
