### ISSUE TITLE
Allow super calls from mixins

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#12905]
class M {
&nbsp;&nbsp;foo(){
&nbsp;&nbsp;&nbsp;&nbsp;super.foo();
&nbsp;&nbsp;}
}

class S {
&nbsp;&nbsp;foo() {
&nbsp;&nbsp;&nbsp;return 'S foo';
&nbsp;&nbsp;}
}

class MA extends S with M {}

main(){
&nbsp;&nbsp;print(new MA().foo());
}

Should print 'S foo'

**Comment by gbracha** [comment]
See

https://github.com/gbracha/lessRestrictedMixins

**Comment by sethladd** [comment]
DEP 34 is now being implemented. See https://github.com/dart-lang/sdk/issues/23770
