### ISSUE TITLE
It is a compile­time error if a name N is re­exported by a library L and N is introduced into the export namespace of L by more than one export.

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#12916]
co19/Language/14_Libraries_and_Scripts/2_Exports_A04_t02

**Comment by zanderso** [comment]
This report is missing a lot of information. I'm going to close it as "Invalid", but feel free to re-open with repro instructions, etc.

**Comment by peter-ahe-google** [comment]
The first comment identifies a failing co19 test.

**Comment by peter-ahe-google** [comment]
This test has since been renamed:

```
$ git grep 12916
tests/co19/co19-dartium.status:Language/Libraries_and_Scripts/Exports/reexport_t01: fail # Dart issue 12916
tests/co19/co19-dartium.status:Language/Libraries_and_Scripts/Exports/reexport_t02: fail # Dart issue 12916
tests/co19/co19-runtime.status:Language/Libraries_and_Scripts/Exports/reexport_t01: fail # Dart issue 12916
tests/co19/co19-runtime.status:Language/Libraries_and_Scripts/Exports/reexport_t02: fail # Dart issue 12916
```

**Comment by mhausner** [comment]
This error will likely be fixed with the new front end. I would not spend time fixing it in the current VM.

**Comment by peter-ahe-google** [comment]
Yes, I plan to fix this in Fasta. Feel free to move this bug to area-fasta and assign it to me.
