### ISSUE TITLE
Allow users to specify type arguments in ClassMirror.newInstance

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#12921]
Maybe?

Or maybe specify that the same arguments from the ClassMirror will be used if it is a mirror on an instantiated generic and all dynamic otherwise?

**Comment by pulyaevskiy** [comment]
Is this something that requires DEP or can be implemented and submitted in a PR?

**Comment by eernstg** [comment]
I believe this is subsumed by the feature requested in https://github.com/dart-lang/sdk/pull/26012.

**Comment by natebosch** [comment]
I think we can close this since it's covered by type arguments in `reflectType`
