### ISSUE TITLE
Find common way of handling checked mode tests for the Vm and dart2js

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#12927]
Some tests use the VMOptions comments like this

// VMOptions=--checked

or

// VMOptions=--enable_type_checks

It is used to make tests which test for static type warnings to pass in both checked and unchecked mode (basically always running then in checked mode on the VM).

For dart2js all these tests are added to the status file with status &quot;Fail, OK&quot;.

This should be handled in a common way, and possibly in a way where all these tests are not taking up space in the status files.

**Comment by matanlurey** [comment]
Checked mode is a goner
