### ISSUE TITLE
Switch to WheelEvent constructor rather than document.createEvent

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#12958]
After rolling Dartium forward in r26947, html/wheelevent_test started failing on dart2js.

**Comment by natebosch** [comment]
@alan-knight - did this end up getting fixed?

**Comment by alan-knight** [comment]
It looks like it to me. At least I see this for WheelEvent in html_dart2js.

```
return JS('WheelEvent', 'new WheelEvent(#, #)', type,
        convertDartToNative_Dictionary(options));
``
