### ISSUE TITLE
Please review new void used as type message

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#12969]
I have looked at these error messages:

foo.dart:1:1: expected identifier, but got 'void'
void x;
^^^^
foo.dart:1:5: Error: Type &quot;void&quot; is only allowed in a return type.
foo(void x) {}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^

It is changed to:

foo.dart:1:1: Error: Type 'void' can't be used here because it isn't a return type.
Try removing 'void' keyword or replace it with 'var', 'final', or a type.
void x;
^^^^
foo.dart:1:5: Error: Type 'void' can't be used here because it isn't a return type.
Try removing 'void' keyword or replace it with 'var', 'final', or a type.
foo(void x) {}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^

Let me know what you think.

**Comment by bkonyi** [comment]
I'm guessing this has been resolved and can be closed, right @peter-ahe-google?
