### ISSUE TITLE
Please review new error message about extraneous modifier

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#12970]
I plan to add the messages below to the compiler, please let me know what you think.

memory:main.dart:1:1: Error: Can't have modifier 'var' here.
Try removing 'var'.
var String foo; main(){}
^^^
memory:main.dart:1:5: Error: Can't have modifier 'set' here.
Try removing 'set'.
var set foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:5: Error: Can't have modifier 'final' here.
Try removing 'final'.
var final foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^
memory:main.dart:1:5: Error: Can't have modifier 'var' here.
Try removing 'var'.
var var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:5: Error: Can't have modifier 'const' here.
Try removing 'const'.
var const foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^
memory:main.dart:1:5: Error: Can't have modifier 'abstract' here.
Try removing 'abstract'.
var abstract foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^
memory:main.dart:1:5: Error: Can't have modifier 'static' here.
Try removing 'static'.
var static foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^
memory:main.dart:1:5: Error: Can't have modifier 'external' here.
Try removing 'external'.
var external foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^
memory:main.dart:1:1: Error: Can't have modifier 'get' here.
Try removing 'get'.
get var foo; main(){}
^^^
memory:main.dart:1:5: Error: Can't have modifier 'var' here.
Try removing 'var'.
get var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:1: Error: Can't have modifier 'set' here.
Try removing 'set'.
set var foo; main(){}
^^^
memory:main.dart:1:5: Error: Can't have modifier 'var' here.
Try removing 'var'.
set var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:7: Error: Can't have modifier 'var' here.
Try removing 'var'.
final var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:5: Error: Can't have modifier 'var' here.
Try removing 'var'.
var var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:7: Error: Can't have modifier 'var' here.
Try removing 'var'.
const var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:1: Error: Can't have modifier 'abstract' here.
Try removing 'abstract'.
abstract var foo; main(){}
^^^^^^^^
memory:main.dart:1:10: Error: Can't have modifier 'var' here.
Try removing 'var'.
abstract var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:1: Error: Can't have modifier 'static' here.
Try removing 'static'.
static var foo; main(){}
^^^^^^
memory:main.dart:1:8: Error: Can't have modifier 'var' here.
Try removing 'var'.
static var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^
memory:main.dart:1:1: Error: Can't have modifier 'external' here.
Try removing 'external'.
external var foo; main(){}
^^^^^^^^
memory:main.dart:1:10: Error: Can't have modifier 'var' here.
Try removing 'var'.
external var foo; main(){}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^

**Comment by askeksa-google** [comment]
Seem to be well established now.
