### ISSUE TITLE
Incorrect propagation of RangeErrors in dart2js

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#12989]
I'm currently preparing the next co19 roll to r569. Some co19 tests expect a RangeError to be thrown. But it seems like dart2js is converting RangeErrors coming from d8 to ArgumentErrors.

Here's an example tests/co19/src/LibTest/typed_data/ByteData/setInt8_A02_t01.dart:
main() {
&nbsp;&nbsp;var byteData = new ByteData(0);
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;byteData.setInt8(-1, 0);
&nbsp;&nbsp;&nbsp;&nbsp;Expect.fail(&quot;RangeError is expected&quot;);
&nbsp;&nbsp;} on RangeError catch(ok) {}
}

The generated code for main sees that the result of 'unwrapException' is not a RangeError so it will throw the \*raw exception\* (which is a V8 RangeError):

main: function() {
&nbsp;&nbsp;var byteData, byteData0, exception, t1, t2;
&nbsp;&nbsp;byteData0 = new DataView(new ArrayBuffer(0));
&nbsp;&nbsp;byteData0.$dartCachedLength = byteData0.length;
&nbsp;&nbsp;byteData = byteData0;
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;$.setInt8$2$x(byteData, -1, 0);
&nbsp;&nbsp;&nbsp;&nbsp;$.Expect__fail(&quot;Expect.fail('RangeError is expected')&quot;);
&nbsp;&nbsp;} catch (exception) {
&nbsp;&nbsp;&nbsp;&nbsp;t1 = $.unwrapException(exception);
&nbsp;&nbsp;&nbsp;&nbsp;t2 = $.getInterceptor(t1);
&nbsp;&nbsp;&nbsp;&nbsp;if (typeof t1 &equals;&equals;&equals; &quot;object&quot; &amp;&amp; t1 !== null &amp;&amp; !!t2.$isRangeError)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;    
&nbsp;&nbsp;&nbsp;&nbsp;else 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw exception;
&nbsp;&nbsp;}

}},

$ ./tools/test.py -mrelease -cdart2js -rd8 co19/LibTest/typed_data/ByteData/setInt8_A02_t01

FAILED: dart2js-d8 release_ia32 co19/LibTest/typed_data/ByteData/setInt8_A02_t01
Expected: pass 
Actual: fail
CommandOutput[dart2js\]:
CommandOutput[d8\]:

stdout:
out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1220: RangeError: Offset is outside the bounds of the DataView
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw exception;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
RangeError: Offset is outside the bounds of the DataView
&nbsp;&nbsp;&nbsp;&nbsp;at DataView.setInt8 (native)
&nbsp;&nbsp;&nbsp;&nbsp;at ByteData.setInt8$2 (out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1202:21)
&nbsp;&nbsp;&nbsp;&nbsp;at $.setInt8$2$x (out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1331:39)
&nbsp;&nbsp;&nbsp;&nbsp;at main (out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1212:7)
&nbsp;&nbsp;&nbsp;&nbsp;at out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1426:7
&nbsp;&nbsp;&nbsp;&nbsp;at init.currentScript (out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1396:5)
&nbsp;&nbsp;&nbsp;&nbsp;at out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1414:3
&nbsp;&nbsp;&nbsp;&nbsp;at out/ReleaseIA32/generated_tests/dart2js-d8/tests_co19_src_LibTest_typed_data_ByteData_setInt8_A02_t01/out.js:1622:3

**Comment by rakudrama** [comment]
It would be possible to translate JavaScript RangeErrors to Dart RangeErrors.
However, not all browsers throw JavaScript RangeErrors.  Firefox appears to throw plain Error objects.
