### ISSUE TITLE
Data race reports from ThreadSanitizer

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#13025]
Hi Dart engs,

I've tried ThreadSanitizer (a compiler instrumentation based data race
detector, clang.llvm.org/docs/ThreadSanitizer.html) on Dart tests and
got a number of race reports, particularly related to dart::Parser
(although there's a number of other races).
Can someone please help to verify whether these races are true positives or not?

The common sources of false positives are:
&nbsp;- custom thread implementations (looks like the mentioned code uses
pthreads, so this shouldn't be the case)
&nbsp;- custom synchronization primitives (TSan knows about pthread mutexes
and condvars and C++11 atomics, but other implementations of
atomics/locks/etc. may require annotations).

Unless these are used, the reported races are likely to be true.

In order to reproduce the reports you'll need to run the following commands:

export CC=/path/to/clang
export CXX=/path/to/clang++
export LD=/path/to/clang++
export CFLAGS=&quot;-fsanitize=thread -w -fPIE&quot;
export CXXLAGS=&quot;-fsanitize=thread -w -fPIE&quot;
export LDLAGS=&quot;-fsanitize=thread -pie&quot;
./tools/build.py --arch=x64

# The next line may hang your machine. If this happens, try running
tests one by one
./tools/test.py --arch=x64 --runtime=vm

Attached is a log from the invocation of test.py. There are 18
distinct race reports:

SUMMARY: ThreadSanitizer: data race
dart/runtime/bin/dbg_connection.cc:438
dart::bin::DebuggerConnectionHandler::AddNewDebuggerConnection(int)
SUMMARY: ThreadSanitizer: data race
dart/runtime/bin/process_linux.cc:156
dart::bin::ExitCodeHandler::WakeUpFd()
SUMMARY: ThreadSanitizer: data race dart/runtime/platform/assert.h:101
void dart::DynamicAssertionHelper::Equals&lt;long, long&gt;(long const&amp;,
long const&amp;)
SUMMARY: ThreadSanitizer: data race
dart/runtime/vm/message_handler_test.cc:72
dart::TestMessageHandler::port_buffer() const
SUMMARY: ThreadSanitizer: data race
dart/runtime/vm/message_handler_test.cc:74
dart::TestMessageHandler::message_count() const
SUMMARY: ThreadSanitizer: data race
dart/runtime/vm/message_handler_test.cc:75
dart::TestMessageHandler::start_called() const
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/parser.cc:348
dart::Parser::SetPosition(long)
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/parser.cc:371
dart::Parser::CurrentToken()
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/parser.cc:377
dart::Parser::LookaheadToken(int)
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/parser.cc:67 ~TraceParser
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/parser.h:273
dart::Parser::ConsumeToken()
SUMMARY: ThreadSanitizer: data race dart/runtime/vm/thread_pool.cc:200
dart::ThreadPool::ReleaseIdleWorker(dart::ThreadPool::Worker\*)
SUMMARY: ThreadSanitizer: data race
dart/runtime/vm/thread_pool_test.cc:159
dart::Dart_TestThreadPool_WorkerTimeout()
SUMMARY: ThreadSanitizer: data race
dart/third_party/net_nss/ssl/sslsock.c:270 ssl_FindSocket
SUMMARY: ThreadSanitizer: data race
dart/third_party/nss/nspr/pr/src/pthreads/ptsynch.c:149 PR_NewLock
SUMMARY: ThreadSanitizer: data race
dart/third_party/nss/nspr/pr/src/pthreads/ptsynch.c:165 PR_DestroyLock
SUMMARY: ThreadSanitizer: data race
dart/third_party/nss/nspr/pr/src/pthreads/ptsynch.c:186 PR_Lock
SUMMARY: ThreadSanitizer: data race
dart/third_party/nss/nspr/pr/src/pthreads/ptsynch.c:211 PR_Unlock
______
**Attachment:**
[log.gz](https://storage.googleapis.com/google-code-attachments/dart/issue-13025/comment-0/log.gz) (312.24 KB)

**Comment by mhausner** [comment]
This bug is stale. The race in compiler stat counters has been removed some time ago by introducing per-isolate counters.
