### ISSUE TITLE
Content Assist: generate overriding methods

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#13052]
I would be great if editor content assist offered to generate overriding methods.

class Foo extends Bar {
&nbsp;&nbsp;ru                 // &lt;&lt;&lt;&lt; cmd-space could offer to generate a run() method overriding the superclass method
}

class Bar {
&nbsp;&nbsp;run() {
&nbsp;&nbsp;}
}

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/41483

**Comment by scheglov** [comment]
This is awesome!

**Comment by danrubel** [comment]
👍

**Comment by sethladd** [comment]
Nice!
