### ISSUE TITLE
Improve formatting of VM stack traces

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#13095]
VM stack traces are currently very difficult to read. Here's an example stack frame:

&nbsp;&nbsp;&nbsp;&nbsp;#­0      main.&lt;anonymous closure&gt; (file:///home/nweiz/goog/dart/dart/test.dart:29:3)

Here are some issues with it:

\* The initial number provides no useful information to the reader.
* The phrase &quot;anonymous closure&quot; is very verbose.
* Using a file URI to identify the file is confusing for users who are used to thinking about their files in terms of paths.
* Using an absolute URI is unnecessarily verbose and ends up making it harder to tell what file an error occurred in.
* Attaching the line and column numbers to the URI makes it harder to copy and paste the URI in most Unix terminals.
* The URIs aren't vertically aligned, making them harder to read.

Here's an example of how the stack_trace package's pretty printer addresses these issues:

&nbsp;&nbsp;&nbsp;&nbsp;test.dart 29:3   main.&lt;fn&gt;
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 29:24  main

The URIs are made relative and printed as paths if they refer to files on disk. &quot;&lt;fn&gt;&quot; is used in place of &quot;&lt;anonymous closure&gt;&quot;. The function names are aligned to make them easier to read.

**Comment by nex3** [comment]
This is definitely not stale—the stack traces are in the same format as they were when this was opened.

@iposva-google Please verify that issues are irrelevant before closing them.

**Comment by iposva-google** [comment]
It is stale from my perspective. We give the full information to developers and if you are not happy with the format then there is a way to drop it. Dropping information a-priori makes it impossible for it to be reconstituted.

There is also no work planned. Reclosing.

**Comment by rmacnak-google** [comment]
The Dart standard requires StackTrace.toString() to report function activations exactly: no omitted frames (e.g., from inlining), no synthetic frames, no obfuscation, and precise source locations. The base stack traces should not be lossy.
