### ISSUE TITLE
Dart2js does not support a generic mixin application as mixin.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#13109]
FAILED: dart2js-d8 release_ia32 language/mixin_mixin2_test
Expected: pass 
Actual: fail
CommandOutput[dart2js]:
CommandOutput[d8]:

stdout:
/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:734: Expect.equals(expected: &lt;num&gt;, actual: &lt;dynamic&gt;) fails.
&nbsp;&nbsp;throw $.wrapException(new $.ExpectException(message));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
Error
&nbsp;&nbsp;&nbsp;&nbsp;at wrapException (/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:315:13)
&nbsp;&nbsp;&nbsp;&nbsp;at Expect__fail (/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:734:11)
&nbsp;&nbsp;&nbsp;&nbsp;at Expect_equals (/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:730:5)
&nbsp;&nbsp;&nbsp;&nbsp;at main (/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:745:5)
&nbsp;&nbsp;&nbsp;&nbsp;at /usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:868:7
&nbsp;&nbsp;&nbsp;&nbsp;at init.currentScript (/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:838:5)
&nbsp;&nbsp;&nbsp;&nbsp;at /usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:856:3
&nbsp;&nbsp;&nbsp;&nbsp;at /usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js:1073:3

Command[dart2js]: out/ReleaseIA32/dart-sdk/bin/dart2js --allow-mock-compilation --categories=all --package-root=out/ReleaseIA32/packages/ /usr/local/google/home/regis/dart2/dart/tests/language/mixin_mixin2_test.dart --out=/usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js
Took 0:00:01.451000

Command[d8]: /usr/local/google/home/regis/dart2/dart/third_party/d8/linux/d8 /usr/local/google/home/regis/dart2/dart/out/ReleaseIA32/generated_tests/dart2js-d8/tests_language_mixin_mixin2_test/out.js
Took 0:00:00.040000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py --use-sdk -mrelease -cdart2js -rd8 -t60 language/mixin_mixin2_test

&equals;&equals;&equals;
&equals;&equals;&equals; 1 test failed
&equals;&equals;&equals;

**Comment by rakudrama** [comment]
The issue with language/mixin_mixin2_test is that the intermediate types `Set` and `Map` are not in the program, causing RuntimeType.toString to crash because the type term has `null` classes.
