### ISSUE TITLE
Missed optimizations regarding strings

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#13114]
returnString(x) {
&nbsp;&nbsp;if (x == new DateTime.now().millisecondsSinceEpoch) return null;
&nbsp;&nbsp;return 'fisk';
}

main() {
&nbsp;&nbsp;String x = returnString(1);
&nbsp;&nbsp;String s = '';
&nbsp;&nbsp;s += 'y';
&nbsp;&nbsp;s = '$s$x${returnString(0)}$x';
&nbsp;&nbsp;print(s);
&nbsp;&nbsp;s = '$s${returnString(0)}$x';
&nbsp;&nbsp;print(s);
&nbsp;&nbsp;print(s);
}

Becomes:

main: function() {
&nbsp;&nbsp;var x, s;
&nbsp;&nbsp;x = $.returnString(1);
&nbsp;&nbsp;s = C.JSString_methods.$add(&quot;&quot;, &quot;y&quot;) + x + $.returnString(0) + x;

Notice that s += &quot;...&quot; isn't optimized as well as s = &quot;$s...&quot;

&nbsp;&nbsp;$.Primitives_printString(s);
&nbsp;&nbsp;s = s + $.returnString(0) + x;

Notice that this could be:   s += $.returnString(0) + x;

&nbsp;&nbsp;$.Primitives_printString(s);
&nbsp;&nbsp;$.Primitives_printString(s);
}

**Comment by rakudrama** [comment]
The SSA output is now:

```js
    main: function() {
      var x, s;
      x = K.returnString(1);
      s = "y" + H.S(x) + H.S(K.returnString(0)) + H.S(x);
      P.print(s);
      s = s + H.S(K.returnString(0)) + H.S(x);
      P.print(s);
      P.print(s);
    }
```

Although the SSA backend will convert  `s = s + "foo"` to  `s += "foo"`, this is not the same as

    s = s + a + b  -->  s += a + b

That requires reassociation of  `(s + a) + b` to `s + (a + b)`, which by itself is harmful since it requires introduction of parentheses.


The CPS output is

```js
    main: function() {
      var x = K.returnString(1), s = "y" + H.S(x) + H.S(K.returnString(0)) + H.S(x);
      P.print(s);
      P.print(s = s + H.S(K.returnString(0)) + H.S(x));
      P.print(s);
    }
```

Generating `+=` in any context is still TODO.

**Comment by rakudrama** [comment]
I'm closing this, since the occasional size benefit  from reassociation followed by "+=" is small.
(dart2js does do limited reassociation combined with constant-folding,)
