### ISSUE TITLE
Clarify NodeValidatorBuilder default rules

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#13207]
Regarding: http://api.dartlang.org/docs/bleeding_edge/dart_html/NodeValidatorBuilder.html

The default constructor says: &quot;Construct a default NodeValidator which only accepts whitelisted HTML5 elements and attributes.&quot;

But the class docs say: &quot;By default this will not accept anything&quot;

What is the default behavior?

Can, can you be more specific what &quot;whitelisted HTML5 elements and attributes&quot; are?

Thanks!

**Comment by srawlins** [comment]
The docs for the class no longer mention "whitelisted" and the [common constructor docs](https://api.dartlang.org/dev/2.0.0-dev.37.0/dart-html/NodeValidatorBuilder/NodeValidatorBuilder.common.html) are pretty extensive now.
