### ISSUE TITLE
Analyzer error message on a parse error is incomprehensible.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#13227]
For the code
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;while (1 &lt; 2 &lt; 3) {}
&nbsp;&nbsp;}
the analyzer generates the following warnings:

---

[error] Expected to find ')' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 15)
[error] Expected to find ';' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 15)
[error] Expected a type name (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[error] Expected to find '&gt;' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[error] Expected a list or map literal (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[error] Expected to find ';' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[error] Expected to find ';' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[error] Expected an identifier (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 18)
[error] Unexpected token ')' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 18)
[warning] The name '' is not a type and cannot be used as a parameterized type (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 17)
[warning] Undefined name '' (/usr/local/google/home/lrn/dart/full/dart/dev/d2jspars.dart, line 2, col 18)
9 errors and 2 warnings found.

---

It's very hard to figure out what the error is. If possible, make the error message more useful.

**Comment by bwilkerson** [comment]
This is handled better by Fasta.
