### ISSUE TITLE
Must dynamically construct a symbol to access a named constructor with mirrors

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#13248]
The [ClassMirror.constructors] map indexes named constructors with symbols like &quot;Foo&quot; and &quot;Foo.named&quot;. This means that if you statically know the name of the constructor you want but not the name of the class itself, you need to dynamically construct a symbol to reflect on that constructor (e.g. `new Symbol(&quot;${MirrorSystem.getName(mirror.simpleName)}.named&quot;)`).

Contrast this with [ClassMirror.newInstance], which refers to constructors using symbols that don't include the class name.

**Comment by natebosch** [comment]
Closing in favor of #16075 since `ClassMirrors.constructors` no longer exists and the linked issue covers `ClassMirrors.declarations`.
