### ISSUE TITLE
[next] Non-determinism in html code gen script

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#13286]
In html_dartium.dart, running go.sh sometimes reorders these overloads.  It should be deterministic.

@@ -26121,13 +26122,13 @­@ class Url extends NativeFieldWrapperClass1 {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if ((blob_OR_source_OR_stream is Blob || blob_OR_source_OR_stream == null)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return _createObjectURL_1(blob_OR_source_OR_stream);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
-    if ((blob_OR_source_OR_stream is MediaStream || blob_OR_source_OR_stream == null)) {
-    if ((blob_OR_source_OR_stream is MediaSource || blob_OR_source_OR_stream == null)) {
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return _createObjectURL_2(blob_OR_source_OR_stream);
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
-    if ((blob_OR_source_OR_stream is MediaSource || blob_OR_source_OR_stream == null)) {
-    if ((blob_OR_source_OR_stream is _WebKitMediaSource || blob_OR_source_OR_stream == null)) {
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return _createObjectURL_3(blob_OR_source_OR_stream);
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
-    if ((blob_OR_source_OR_stream is _WebKitMediaSource || blob_OR_source_OR_stream == null)) {
-    if ((blob_OR_source_OR_stream is MediaStream || blob_OR_source_OR_stream == null)) {
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return _createObjectURL_4(blob_OR_source_OR_stream);
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

**Comment by natebosch** [comment]
@vsmenon - I'm not familiar with these tools - do they still exist? Was this strictly related to dartium?

**Comment by vsmenon** [comment]
It's the tools that generate dart:html from IDL files.  This seems obsolete.  @terrylucas - please reopen if I'm mistaken.
