### ISSUE TITLE
dart2js: compiled html apps are not forward compatible: new browsers can break deployed apps

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#13285]
dart2js compiled apps are not safe to be deployed long term. Browsers can break Dart apps in ways that would *not* break an application written purely in JavaScript.

dart2js+html's dynamic dispatch works roughly like:
1. find the target object's JS type name (see getFunctionForTypeNameOf in native_helper.dart)
2. map JS type name to corresponding Dart type
3. apply Dart semantics for that method call

Some type names like &quot;Node&quot; and &quot;HTMLElement&quot; are specified and likely to be safe to use for the foreseeable future.

However, many other type names can and do get changed by browsers between major releases. For example, Firefox renamed the type that backs &quot;.attributes&quot; to MozNamedAttrMap, and this broke all use of HTML attributes.
(http://code.google.com/p/dart/issues/detail?id=11879). According to Pete this happened twice with IE11 as well. I think we have seen similar issues in Blink rolls.

How do we solve this for Dart 1.0? We must have a way to deploy apps that is not going to need recompilation whenever a browser vendor releases a new version...

Other scary facts about our current dispatch:
* it relies on User Agent sniffing
* both IE and Firefox have ad hoc rename tables (see typeNameInFirefox, typeNameInIE)
* everything falls back to Object.prototype.toString. From the perspective of HTML/DOM standards, the behavior here is unspecified. Typical JavaScript programs don't depend on it except for debugging.

**Comment by kasperpeulen** [comment]
How is the process on this issue going, it is marked as high, but it has no milestone.

This issue has never been a problem for me, but someone in this reddit posts, claims that he had to wait for a new firefox update to make his dart app work again in firefox after a dart update:
https://www.reddit.com/r/javascript/comments/3tvgrq/fiber_launched_this_week_as_googles_first_angular/

**Comment by jmesserly** [comment]
IDK how you're feeling about this @rakudrama but I'm inclined to close this as stale, I think we're in a good place now and browsers are a lot more sane these days generally. Feel free to reopen.
