### ISSUE TITLE
dart2js, analyzer, pub: API first - all features should be exposed via library (dart:compiler?) which is then wrapped by binary

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#13346]
In a lot of my workflows, I'm wrapping these dart executables with Process and then parsing the STDOUT.

Ideally, they would be exposed as &quot;API first&quot; (playing off &quot;Mobile first&quot;) - then wrapped with an associated binary.

Event having a &quot;run dart&quot; API would be amazing. Let me passing in flags, expose STDOUT/ERR as Streams, hooking into debugging and tracing infrastructure

Etc

**Comment by lrhn** [comment]
This should probably be a package, not a platform library. There is no need for the VM to include a complete dart-to-javascript compiler.

**Comment by kevmoo** [comment]
> This should probably be a package, not a platform library. There is no need for the VM to include a complete dart-to-javascript compiler.

Agreed!
