### ISSUE TITLE
dart:mirrors docs need one-line summaries

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13377]
The API docs for dart:mirrors need one-line summaries. The library is fine, but its functions and classes, as well as the classes' members, need one liners so they'll look good in the new dartdoc.

These docs are visible from links on api.dartlang.org/dart_mirrors.html.

Info on writing docs is at https://code.google.com/p/dart/wiki/WritingApiDocumentation.

**Comment by srawlins** [comment]
Oops. I fixed this in #24505
