### ISSUE TITLE
Asserts should allow full expressions

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#13401]
The grammar for the assert statement currently restricts the contained expression to be a &quot;conditionalExpression&quot; rather than a full &quot;expression&quot;. I don't think there's any value to this because you can get around it by parenthesizing any arbitrary expression. Please allow full expressions without requiring parentheses. (I believe both dart2js and the VM currently allow a full expression.)

**Comment by munificent** [comment]
Duplicate of #26865 (which is done).
