### ISSUE TITLE
dart2js: LibraryMirror.classes includes synthetic classes for closures

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#13439]
fails part of library_declarations_test

import 'dart:mirrors';

class C {}

main(){
&nbsp;&nbsp;[1, 2].forEach((x)=&gt;print(x));
&nbsp;&nbsp;print(reflectClass(C).owner.classes.values.toList());
}

prints:
1
2
[ClassMirror on 'C', ClassMirror on 'main_closure']

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
