### ISSUE TITLE
dart2js: ClassMirror.declarations is missing abstract methods

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#13440]
fails part of class_declarations_test

import 'dart:mirrors';

class C {
&nbsp;abstractMethod();
}

main(){
&nbsp;&nbsp;print(reflectClass(C).declarations.values.toList());
}

prints:
[MethodMirror on 'C']

**Comment by yunjia** [comment]
Is there any plan to fix this?

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
