### ISSUE TITLE
dart2js: compiler crashes when we can't find builtin libraries

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#13508]
**[user feedback]**

Trying to run dartdoc on the hello world example

Running dartdoc...
Analyzing libraries...
Error: Can't read 'file:///C:/Program%20Files/darteditor-win32-64/dart/dart-sdk/lib/_internal/lib/js_helper.dart' (Error reading '/C:/Program%20Files/darteditor-win32-64/dart/dart-sdk/lib/_internal/lib/js_helper.dart' (OS Error: The system cannot find the path specified.

, errno = 3)).
Error: Can't read 'file:///C:/Program%20Files/darteditor-win32-64/dart/dart-sdk/lib/_internal/lib/interceptors.dart' (Error reading '/C:/Program%20Files/darteditor-win32-64/dart/dart-sdk/lib/_internal/lib/interceptors.dart' (OS Error: The system cannot find the path specified.

, errno = 3)).
Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

\* the name and version of your operating system,

\* the Dart SDK build number (build number could not be determined), and

\* the entire message you see here (including the full stack trace
&nbsp;&nbsp;below as well as the source location above).

The compiler crashed.
#­0      Object.noSuchMethod (dart:core-patch/object_patch.dart:20:25)
#­1      Compiler.scanBuiltinLibraries.&lt;anonymous closure&gt; (file:///e:/b/build/slave/dart-editor-win-trunk/build/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:542:42)
#­2      \_Future._propagateToListeners.&lt;anonymous closure&gt; (dart:async/future_impl.dart:264:55)
#­3      \_ZoneBase._runInZone (dart:async/zone.dart:82:17)
#­4      \_ZoneBase._runUnguarded (dart:async/zone.dart:102:22)
#­5      \_ZoneBase.executeCallback (dart:async/zone.dart:58:23)
#­6      \_Future._propagateToListeners (dart:async/future_impl.dart:259:37)
#­7      \_Future._addListener.&lt;anonymous closure&gt; (dart:async/future_impl.dart:128:30)
#­8      \_asyncRunCallback (dart:async/event_loop.dart:9:15)
#­9      \_createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:8:13)
#­10     \_Timer._createTimerHandler._handleTimeout (timer_impl.dart:95:21)
#­11     \_Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:111:23)
#­12     \_ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)
#­13     Compiler.scanBuiltinLibraries.&lt;anonymous closure&gt; (file:///e:/b/build/slave/dart-editor-win-trunk/build/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:542:42)
#­14     \_Future._propagateToListeners.&lt;anonymous closure&gt; (dart:async/future_impl.dart:264:55)
#­19     \_ZoneBase._runInZone (dart:async/zone.dart:82:17)
#­20     \_ZoneBase._runUnguarded (dart:async/zone.dart:102:22)
#­21     \_ZoneBase.executeCallback (dart:async/zone.dart:58:23)
#­22     \_Future._propagateToListeners (dart:async/future_impl.dart:259:37)
#­23     \_Future._addListener.&lt;anonymous closure&gt; (dart:async/future_impl.dart:128:30)
#­24     \_asyncRunCallback (dart:async/event_loop.dart:9:15)
#­25     \_createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:8:13)
#­26     \_Timer._createTimerHandler._handleTimeout (timer_impl.dart:95:21)
#­27     \_Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:111:23)
#­28     \_ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)

Error: generation failed: The null object does not have a method 'find'.

NoSuchMethodError : method not found: 'find'
Receiver: null
Arguments: [Instance of 'StringWrapper']
StackTrace: #­0      Object.noSuchMethod (dart:core-patch/object_patch.dart:20:25)
#­1      Compiler.scanBuiltinLibraries.&lt;anonymous closure&gt; (file:///e:/b/build/slave/dart-editor-win-trunk/build/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:542:42)
#­2      \_Future._propagateToListeners.&lt;anonymous closure&gt; (dart:async/future_impl.dart:264:55)
#­3      \_ZoneBase._runInZone (dart:async/zone.dart:82:17)
#­4      \_ZoneBase._runUnguarded (dart:async/zone.dart:102:22)
#­5      \_ZoneBase.executeCallback (dart:async/zone.dart:58:23)
#­6      \_Future._propagateToListeners (dart:async/future_impl.dart:259:37)
#­7      \_Future._addListener.&lt;anonymous closure&gt; (dart:async/future_impl.dart:128:30)
#­8      \_asyncRunCallback (dart:async/event_loop.dart:9:15)
#­9      \_createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:8:13)
#­10     \_Timer._createTimerHandler._handleTimeout (timer_impl.dart:95:21)
#­11     \_Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:111:23)
#­12     \_ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)
#­13     Compiler.scanBuiltinLibraries.&lt;anonymous closure&gt; (file:///e:/b/build/slave/dart-editor-win-trunk/build/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:542:42)
#­14     \_Future._propagateToListeners.&lt;anonymous closure&gt; (dart:async/future_impl.dart:264:55)
#­19     \_ZoneBase._runInZone (dart:async/zone.dart:82:17)
#­20     \_ZoneBase._runUnguarded (dart:async/zone.dart:102:22)
#­21     \_ZoneBase.executeCallback (dart:async/zone.dart:58:23)
#­22     \_Future._propagateToListeners (dart:async/future_impl.dart:259:37)
#­23     \_Future._addListener.&lt;anonymous closure&gt; (dart:async/future_impl.dart:128:30)
#­24     \_asyncRunCallback (dart:async/event_loop.dart:9:15)
#­25     \_createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:8:13)
#­26     \_Timer._createTimerHandler._handleTimeout (timer_impl.dart:95:21)
#­27     \_Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:111:23)
#­28     \_ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.7.3_r27487 (2013-09-13)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_40
# projects: 2
# open dart files: 3
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 362 / 282 MB
thread count: 23
index: 196661 relationships in 41832 keys in 191 sources

SDK installed: true
Dartium installed: true

**Comment by sigmundch** [comment]
duplicating against #23599
