### ISSUE TITLE
Provide feedback to help reduce inconsistencies and surprises between VM and dart2js when working with numbers

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#13601]
Developers use Dartium and the VM for development due to the very fast iteration cycles. Developers then compile to JavaScript and deploy onto the open web. If there are inconsistencies in behavior between the two runtimes, developers are often debugging issues without expecting the issue is in the platform. This causes a perception issue, and creates mistrust.

Here are the known differences that we can warn users about, when they care about running on dart2js:

identical(1, 1.0)
&nbsp;&nbsp;true in dart2js
&nbsp;&nbsp;false in vm
(1 is double)
&nbsp;&nbsp;true in dart2js
&nbsp;&nbsp;false in vm
(1.0 is int)
&nbsp;&nbsp;true in dart2js
&nbsp;&nbsp;false in vm
overflow past 53 bits (this might be done?)
32 bit truncation for bitwise operations
1 == 1.0
&nbsp;&nbsp;true in dart2js
&nbsp;&nbsp;false in vm

Please add a hint for the cases where the analyzer can detect the above code will run with potentially different behavior in VM and dart2js.

(this is an extension of the work Jamie did)

**Comment by bwilkerson** [comment]
Closing as obsolete, given 64 bit ints.

**Comment by sigmundch** [comment]
Note that there will still be inconsistencies: ddc and dart2js will not implement int64 semantics for ints, they will continue to be mapped to JSNumber

**Comment by bwilkerson** [comment]
Is there useful information we could provide users in these cases?
