### ISSUE TITLE
Failure on lib/async/stream_controller_async_test

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#13608]
From http://build.chromium.org/p/client.dart/builders/vm-win32-release-be/builds/258/steps/tests/logs/stdio

&equals;&equals;&equals; Failure summary:

FAILED: none-vm release_ia32 lib/async/stream_controller_async_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
Uncaught Error: Expect.listEquals(list length, expected: &lt;9&gt;, actual: &lt;5&gt;) fails: Next element &lt;DataEvent: 4&gt;
Stack Trace:
# ­0      Expect._fail (package:expect/expect.dart:368:5)
# ­1      Expect.listEquals (package:expect/expect.dart:202:12)
# ­2      testSink.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///e:/b/build/slave/vm-win32-release-be/build/dart/tests/lib/async/stream_controller_async_test.dart:676:32)
# ­3      testSink.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.executeWhenPauseIsDone (file:///e:/b/build/slave/vm-win32-release-be/build/dart/tests/lib/async/stream_controller_async_test.dart:673:23)
# ­4      testSink.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.executeWhenPauseIsDone.&lt;anonymous closure&gt; (file:///e:/b/build/slave/vm-win32-release-be/build/dart/tests/lib/async/stream_controller_async_test.dart:670:48)
# ­5      Future.Future.delayed.&lt;anonymous closure&gt; (dart:async/future.dart:178)
# ­6      _Future._propagateToListeners.&lt;anonymous closure&gt; (dart:async/future_impl.dart:449)
# ­8      _rootRun (dart:async/zone.dart:510)
# ­9      _ZoneDelegate.run (dart:async/zone.dart:323)
# ­10     _CustomizedZone.run (dart:async/zone.dart:468)
# ­11     _Future._propagateToListeners (dart:async/future_impl.dart:441)
# ­12     _Future._complete (dart:async/future_impl.dart:298)
# ­13     _SyncCompleter.complete (dart:async/future_impl.dart:44)
# ­14     Future.Future.delayed.&lt;anonymous closure&gt; (dart:async/future.dart:180)
# ­15     _createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:11)
# ­16     _Timer._createTimerHandler._handleTimeout (timer_impl.dart:151)
# ­17     _Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:168)
# ­18     _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:113)

stderr:
Unhandled exception:
Expect.listEquals(list length, expected: &lt;9&gt;, actual: &lt;5&gt;) fails: Next element &lt;DataEvent: 4&gt;
# ­0      _rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:505)
# ­1      _asyncRunCallback (dart:async/event_loop.dart:18)
# ­2      _asyncRunCallback (dart:async/event_loop.dart:21)
# ­3      _createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:11)
# ­4      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:151)
# ­5      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:159)
# ­6      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:159)
# ­7      _Timer._createTimerHandler.&lt;anonymous closure&gt; (timer_impl.dart:168)
# ­8      _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:113)

Command[vm]: build\ReleaseIA32\dart.exe --ignore-unrecognized-flags --package-root=build/ReleaseIA32/packages/ e:\b\build\slave\vm-win32-release-be\build\dart\tests\lib\async\stream_controller_async_test.dart
Took 0:00:00.530000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -t60 lib/async/stream_controller_async_test

&equals;&equals;&equals;
&equals;&equals;&equals; 1 test failed
&equals;&equals;&equals;

**Comment by rmacnak-google** [comment]
Oops, wrong bug number in that commit.
