### ISSUE TITLE
dart_analyzer: The analyzer output should print file / line numbers in a parsable format

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#13623]
Currently the dart analyzer prints file names and line numbers as:

[warning] Undefined name '$rootScope' (/home/deboer/gits/angular-dart/test/dom/http_spec.dart, line 969, col 9)

Tools (e.g. WebStorm) understand file name / line numbers in the form:

/home/deboer/gits/angular-dart/test/dom/http_spec.dart:969

The analyzer should use that format to better integrate with other tools.

**Comment by srawlins** [comment]
Is this feasible? Is the analyzer going to change the output format, which would break existing tools that use `dartanalyzer` and read stdout?

**Comment by bwilkerson** [comment]
We (implicitly) make backward compatibility guarantees for machine format, but not for anything else. Hopefully nobody is depending on a non-machine format.

That said, I'm not sure how useful this is given that analysis server is now the way we integrate with other tools.

**Comment by srawlins** [comment]
Yeah I say we can this. analysis_server and --format=machine work.
