### ISSUE TITLE
VM reports runtime error instead of compile-time error for a reserved keyword used as identifier in string interpolation

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#13627]
Spec: &quot;A reserved word may not be used as an identifier; it is a compile-time error if a reserved word is used where an identifier is expected.&quot;

language/class_keyword_test/02 fails with a runtime error instead of compile-time error.

**Comment by zanderso** [comment]
This is a duplicate of https://github.com/dart-lang/sdk/issues/8823
