### ISSUE TITLE
Dart2js and dart2dart wrongly report compile-time error for non conflicting constructor and setter names 

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#13639]
Spec:

The name of a setter is  obtained by appending the  string `='  to the identifier given in its signature.
Hence, a setter name can never conflict with, override or be overridden by a getter or method.

bad_constructor_test/05 wrongly reports a compile-time error

**Comment by johnniwinther** [comment]
There is also a conflict between methods and setter in setter4_test

**Comment by lrhn** [comment]
I'm not aware of any changes in this regard for Dart 2.0, so are we sure it's correct for the analyzer to report a compile-time error?

**Comment by sigmundch** [comment]
this appears now to be working correctly - bad_constructor_test is not mentioned in any .status file at at this time.

**Comment by sigmundch** [comment]
(except for the Dart1 implementation of dart2js)
