### ISSUE TITLE
VM reports no static method when no such method is on an instance

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#13655]
Given the following code

class C&lt;T&gt; {
&nbsp;&nbsp;foo() =&gt; T();
}

main() {
&nbsp;&nbsp;print(new C&lt;int&gt;().foo());
}

We get the following  error message, that claims that no \*static\* method T was found, when in reality it is a missing instance method.

Unhandled exception:
No constructor 'C.foo' declared in class 'C'.

NoSuchMethodError : method not found: 'C.foo'
Receiver: Type: class 'C'
Arguments: [...]
#­0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:99:5)
#­1      main (file:///Users/gbracha/dart/dart/dart-sdk/C.dart:7:23)
gbracha-macpro:dart-sdk gbracha$ emacs C.dart
gbracha-macpro:dart-sdk gbracha$ ./bin/dart C.dart
Unhandled exception:
No static method 'T' declared in class 'C'.

NoSuchMethodError : method not found: 'T'
Receiver: Type: class 'C'
Arguments: [...]
#­0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:99:5)
#­1      C.foo (file:///Users/gbracha/dart/dart/dart-sdk/C.dart:3:12)
#­2      main (file:///Users/gbracha/dart/dart/dart-sdk/C.dart:7:25)

**Comment by srawlins** [comment]
This has been fixed. The VM now reports a missing instance method:

```
Unhandled exception:
Class 'C<int>' has no instance method 'T'.

NoSuchMethodError: method not found: 'T'
Receiver: Instance of 'C<int>'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      C.foo (file:///Users/srawlins/code/dart-repo2/sdk/13655.dart:2:12)
#3      main (file:///Users/srawlins/code/dart-repo2/sdk/13655.dart:6:22)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by lrhn** [comment]
And for the record, that's the spec-mandated behavior, even if it looks odd that *because* a `T` type variable is in scope, it turns `T()` into `this.T()` where the `T` no longer refers to the type variable.
