### ISSUE TITLE
Dart VM reports a runtime error instead of a compile-time error 

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#13685]
Dart VM reports a runtime error instead of a compile-time in checked mode for:

&nbsp;&nbsp;language/compile_time_constant_checked3_test/01: MissingCompileTimeError
&nbsp;&nbsp;language/compile_time_constant_checked3_test/02: MissingCompileTimeError
&nbsp;&nbsp;language/compile_time_constant_checked3_test/03: MissingCompileTimeError
&nbsp;&nbsp;language/compile_time_constant_checked3_test/04: MissingCompileTimeError
&nbsp;&nbsp;language/compile_time_constant_checked3_test/05: MissingCompileTimeError
&nbsp;&nbsp;language/compile_time_constant_checked3_test/06: MissingCompileTimeError

**Comment by mit-mit** [comment]
Closing as stale, please open a new issue if there is a current, important issue.
