### ISSUE TITLE
Confusing error location for mismatched string curlies

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#13736]
Given the following code with mismatch {}'s in the string:

void main() { 
&nbsp;&nbsp;var i = 0;
&nbsp;&nbsp;print('foo ${i');
}

dart2js gives the error:
squigly_error.dart:3:13: unmatched '{'
void main() {

I would expect it to report the error for the print statement, not for the main() method.

**Comment by sigmundch** [comment]
handled better in CFE
