### ISSUE TITLE
TypeParameter index mismatch

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#13751]
It seems like things go wrong if a type parameter has an index that does not match its position in the type arguments list.  There is a failure on the optimization-counter-threshold=5 builder.

Reproduce with:

out/DebugIA32/dart --optimization-counter-threshold=5 --enable_asserts --enable_type_checks --package-root=out/DebugIA32/packages/ tests/co19/src/LibTest/core/Runes/takeWhile_A01_t01.dart

It seems like things have already gone wrong in the parser.  Apply the attached patch to svn r28152.  (Via &quot;patch -p1 &lt; patch.diff&quot; in the dart directory).
______
**Attachment:**
[patch.diff](https://storage.googleapis.com/google-code-attachments/dart/issue-13751/comment-0/patch.diff) (2.22 KB)

**Comment by mhausner** [comment]
I suspect this bug is stale.
