### ISSUE TITLE
Improve the dart:async API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13759]
Here are the dart:async pages that are in the top 100 views on api.dartlang.org:

/dart_async/Timer.html
/dart_async/StreamSubscription.html
/dart_async/StreamTransformer.html
/dart_async/StreamSink.html

Strangely, the library page isn't in the top 100... But it's important, too.

**Comment by srawlins** [comment]
[Timer](https://api.dartlang.org/1.12.1/dart-async/Timer-class.html), [StreamSubscription](https://api.dartlang.org/1.12.1/dart-async/StreamSubscription-class.html), [StreamTransformer](https://api.dartlang.org/1.12.1/dart-async/StreamTransformer-class.html), and [StreamSink](https://api.dartlang.org/1.12.1/dart-async/StreamSink-class.html) all have great class-level and member-level docs now. Closing.
