### ISSUE TITLE
Improve the dart:collection API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13760]
Here are the dart:collection pages that are in the top 100 views on api.dartlang.org:

/dart_collection.html
/dart_collection/HashMap.html
/dart_collection/Maps.html
/dart_collection/LinkedList.html

**Comment by srawlins** [comment]
The good:

* [dart-collection](https://api.dartlang.org/1.12.1/dart-collection/dart-collection-library.html) only has a one-sentence description. Probably fine.
* [HashMap](https://api.dartlang.org/1.12.1/dart-collection/HashMap-class.html) has great docs.

The bad:

* [Maps](https://api.dartlang.org/1.12.1/dart-collection/Maps-class.html) doesn't have (any?) docs.
* [LinkedList](https://api.dartlang.org/1.12.1/dart-collection/LinkedList-class.html) doesn't have many docs.

**Comment by lrhn** [comment]
The `Maps` class really, really shouldn't exist. It's a left-over from before we had mixins. That said, it exists, so it should be documented (so we can recommend you use MapMixin instead!).

The LinkedList would also be a prime candidate for moving into a package if that ever becomes possible. It is significantly different from the remaining collections in core. 
Again, it should still be documented. And maybe copied to package collection, so we can recommend people use that version, in a bid to - eventually - deprecate it.

**Comment by sethladd** [comment]
@lrhn +1 for adding docs that say "you should be using this instead!" and perhaps even adding a `@Deprecated('2.0')` indicating that it's a candidate for removal in 2.0.

**Comment by srawlins** [comment]
The `Maps` class has been deleted. [LinkedList](https://api.dartlang.org/dev/dart-collection/LinkedList-class.html) has great docs on the class, and doc comments on all class members.
