### ISSUE TITLE
dart2js: combine assignments (shorter code)

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#13763]
**[user feedback]**

I have this repeating pattern in dart2js output:

W.ew7.$isa=true

W.Koa.$isrg=true

W.Koa.$isa=true

W.ipe.$isrg=true
...
some hundred lines...
Couldn't they be combined to:

W.ew7.$isa=W.Koa.$isrg=W.Koa.$isa=W.ipe.$isrg=true

That would save around 5kb in my situation.

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.7.5_r27776 (2013-09-23)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 1
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 447 / 70 MB
thread count: 28
index: 421861 relationships in 79695 keys in 678 sources

SDK installed: true
Dartium installed: true

**Comment by rakudrama** [comment]
Obsolete. We no longer generate this code, rather we use properties.
