### ISSUE TITLE
Improve the dart:core API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13767]
Here are the dart:core pages that are in the top 100 views on api.dartlang.org:

/dart_core.html
/dart_core/List.html
/dart_core/String.html
/dart_core/Map.html
/dart_core/DateTime.html
/dart_core/Iterable.html
/dart_core/int.html
/dart_core/Object.html
/dart_core/num.html
/dart_core/RegExp.html
/dart_core/Duration.html
/dart_core/double.html
/dart_core/Set.html
/dart_core/Uri.html
/dart_core/StringBuffer.html
/dart_core/Pattern.html
/dart_core/Type.html
/dart_core/Stopwatch.html
/dart_core/Iterator.html
/dart_core/Exception.html
/dart_core/Function.html
/dart_core/Symbol.html
/dart_core/bool.html
/dart_core/Comparable.html
/dart_core/Match.html
/dart_core/StringSink.html
/dart_core/Error.html

**Comment by natebosch** [comment]
I think most of these have decent docs - are there specific ones you think can be improved @kwalrath ?

**Comment by kwalrath** [comment]
Not off the top of my head, and I filed this so long ago that the analytics probably aren't valid any more. I'll close this, and we can reopen individual issues as we need them. If someone wants up-to-date analytics for any reason, I'm happy to provide them.
