### ISSUE TITLE
Improve the dart:html API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13768]
Lots of dart:html pages are in the top 100 views on api.dartlang.org, so any attention we can give these should be helpful:

/dart_html.html
/dart_html/Element.html
/dart_html/HttpRequest.html
/dart_html/Window.html
/dart_html/CanvasRenderingContext2D.html
/dart_html/CanvasElement.html
/dart_html/Event.html
/dart_html/WebSocket.html
/dart_html/InputElement.html
/dart_html/Node.html
/dart_html/MouseEvent.html
/dart_html/Document.html
/dart_html/HtmlElement.html
/dart_html/DivElement.html
/dart_html/KeyboardEvent.html
/dart_html/ElementStream.html
/dart_html/EventTarget.html
/dart_html/FileReader.html
/dart_html/Blob.html
/dart_html/ButtonElement.html
/dart_html/CustomEvent.html
/dart_html/ImageElement.html
/dart_html/Events.html
/dart_html/HtmlDocument.html

**Comment by natebosch** [comment]
Closing as stale.
