### ISSUE TITLE
Improve the dart:io API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#13770]
Lots of dart:io pages are in the top 100 views on api.dartlang.org, so any attention we can give these should be especially helpful:

/dart_io.html
/dart_io/File.html
/dart_io/HttpServer.html
/dart_io/HttpClient.html
/dart_io/HttpRequest.html
/dart_io/WebSocket.html
/dart_io/Directory.html
/dart_io/Process.html
/dart_io/Socket.html
/dart_io/IOSink.html
/dart_io/HttpResponse.html
/dart_io/Platform.html
/dart_io/HttpClientRequest.html

(PS: Why is there no Library-IO label?)

**Comment by srawlins** [comment]
* The [library](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/dart-io-library.html) is very fleshed out.
* [File](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/File-class.html) is complete.
* [HttpClient](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/HttpClient-class.html) is complete.
* [HttpServer](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/HttpServer-class.html) is complete.
* [HttpRequest](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/HttpRequest-class.html) is complete.
* [WebSocket](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/WebSocket-class.html) is complete.
* [Directory](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/Directory-class.html) is complete.
* [Process](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/Process-class.html) is complete.
* [Socket](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/Socket-class.html) is complete.
* [IOSink](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/IOSink-class.html) is complete.
* [HttpResponse](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/HttpResponse-class.html) is complete.
* [Platform](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/Platform-class.html) is complete.
* [HttpClientRequest](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/HttpClientRequest-class.html) is complete.
* [FileSystemEntity](https://api.dartlang.org/dev/2.0.0-dev.64.1/dart-io/FileSystemEntity-class.html) is complete.
