### ISSUE TITLE
lib/mirrors/delegate_test is failing in CSP mode

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#13864]
This test was added in revision 28270

Failure below, I will mark it in the status file

Unsupported operation: Can't use 'field' in reflection because it is not included in a @­MirrorsUsed annotation.
Error
&nbsp;&nbsp;&nbsp;&nbsp;at Object.wrapException (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:749:13)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.throwExpression (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:768:11)
&nbsp;&nbsp;&nbsp;&nbsp;at JSInvocationMirror._getCachedInvocation$1 (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:1567:11)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.JSInvocationMirror.static.JSInvocationMirror_invokeFromMirror (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:1581:23)
&nbsp;&nbsp;&nbsp;&nbsp;at JsInstanceMirror.delegate$1 (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:1806:14)
&nbsp;&nbsp;&nbsp;&nbsp;at Proxy.noSuchMethod$1 (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:3259:30)
&nbsp;&nbsp;&nbsp;&nbsp;at Proxy.Object.get$field (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:2778:17)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.main (http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:3205:29)
&nbsp;&nbsp;&nbsp;&nbsp;at http://127.0.0.1:36148/root_build/generated_tests/dart2js-drt-checked-csp/tests_lib_mirrors_delegate_test/test.precompiled.js:3512:35
&nbsp;&nbsp;&nbsp;&nbsp;at dartMainRunner (http://127.0.0.1:36148/root_dart/pkg/unittest/lib/test_controller.js:217:5)

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
