### ISSUE TITLE
Dart VM compiler optimizations: do not box integer at the end of each loop iteration.

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#13875]
In loop of 'runInts' variable 'sum' is boxed at the end of each loop iteration. Instead box it only outside the loop, similarly to doubles.

runInts(a, b) {
&nbsp;&nbsp;var sum = 0;
&nbsp;&nbsp;for (int i = 0; i &lt; 10000; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;sum = sum + a - b;
&nbsp;&nbsp;}
&nbsp;&nbsp;return sum;
}

main() {
&nbsp;&nbsp;for (int i = 0; i &lt; 100; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;runInts(1, 0x7FFFFFFF);
&nbsp;&nbsp;}
}

**Comment by fsc8000** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8adefa8e7969c2ade49699d40bf5b73fc57d517f
