### ISSUE TITLE
[next] keyCode values for KeyboardEvents created via KeyEvent in dartium are incorrect

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#13902]
Currently if you programmatically create a new KeyEvent, the underlying KeyboardEvent that gets created on Dartium has a keyCode and charCode of 0 istead of the desired value. We'll need to make the proper calls into v8/DOM to actually set the correct value.

**Comment by georgelesica-wf** [comment]
It would be really nice to finally get a solution to this issue, especially since the recommended method (at the top of https://api.dartlang.org/1.13.1/dart-html/KeyEvent-class.html) appears to be broken in 1.13 (see below). Is there another workaround being considered or is there some kind of ETA on this?

```
Uncaught Unhandled exception:
InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.
#0      Blink_JsNative_DomException.callMethod (dart:_blink:17262)
#1      BlinkEventTarget.dispatchEvent_Callback_1_ (dart:_blink:4422)
#2      EventTarget.dispatchEvent (dart:html:17300)
#3      _CustomKeyEventStreamImpl.add (dart:html:44939)
#4      _KeyboardEventHandler.processKeyDown (dart:html:46680)
#5      wrap_event_listener.<anonymous closure>.<anonymous closure> (dart:html:1215)
```

**Comment by terrylucas** [comment]
After we roll Dartium forward to build 45/46 we'll re-look at all open Dartium bugs.

**Comment by vsmenon** [comment]
Just hit this in pageloader, which used this API for testing.  

Should KeyEvent be deprecated in favor of KeyboardEvent?  That appears to be the new standard, but it's not quite there on all browsers though:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent

**Comment by kevmoo** [comment]
http://caniuse.com/#search=KeyboardEvent

Worth looking at the specific bits that are and aren't supported.

**Comment by alan-knight** [comment]
The important thing is probably KeyboardEvent.key, which would be an actual portable and standard way of identifying the key. If we're lucky, you'll even be able to set it when constructing the event. But it's only just gone into the bleeding edge of Safari. We may be able to hack around it by delegating that to keyIdentifier on Safari in the meantime.

**Comment by eukreign** [comment]
I'm trying to unit test some keyboard handling in my app. Is there any work around for this at all? I'm willing to re-architect my app just so I can generate keyboard events artificially. I see a bunch of unit tests in Dart SDK but they are failing... :-1: 

https://github.com/dart-lang/sdk/blob/master/tests/html/keyboard_event_test.dart

Is there something that does work?

**Comment by eukreign** [comment]
@georgelesica-wf Thanks for the tips. What I ended up doing is abstracting even further:

```dart
class Input extends HtmlElement {
    StreamController<KeyEvent> controller = new StreamController<KeyEvent>(sync: true);
    Stream<KeyEvent> get onKeyEvent => controller.stream;
    Input.created(): super.created() {
        onKeyDown.listen((KeyboardEvent e) {
            controller.add(new KeyEvent.wrap(e));
        });
    }
}
```

When I want to listen for KeyEvents I can do it like so (added bonus is that `handleKeyboard` will get a `KeyEvent` object):
```dart
input.onKeyEvent.listen(handleKeyboard);
```

When I want to test:
```dart
input.controller.add(new KeyEvent('keydown', charCode: key));
```

So far this has worked pretty well.
