### ISSUE TITLE
vm: Examples where test coverage is inadequate

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#13912]
Test coverage could add instrumentation just for coverage rather than relying only on counters that exist for optimization.

Coverage-only instrumentation could be zero / unhit at optimization time and become hit without needing to deoptimize, which would require optimized code to still have some coverage instrumentation (perhaps inexact).

There must be a gazillion papers on doing this efficiently.

Examples:

No coverage at all:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  static String \_eitherOf(String val1, String val2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (val1 != null) return val1;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (val2 != null) return val2;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    return '';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  }

No way to tell if the manual defaulting has test coverage:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  static void \_fillMapWithMappedIterable(Map map, Iterable iterable,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|                                         key(element), value(element)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (key == null) key = \_id;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (value == null) value = \_id;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
&nbsp;&nbsp;&nbsp;9144|    for (var element in iterable) {
&nbsp;&nbsp;&nbsp;4445|      map[key(element)] = value(element);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  }

Can't tell if this is used only with empty iterables:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  static bool any(Iterable iterable, bool f(o)) {
11247036|    for (final e in iterable) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      if (f(e)) return true;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    return false;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  }

All we can tell for sure here is that the method was called:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  static SourceString operatorNameToIdentifier(SourceString name) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (name == null) return null;
&nbsp;&nbsp;45329|    String value = name.stringValue;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    if (value == null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return name;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '==')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$eq');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '~')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$not');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '[]')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$index');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '[]=')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$indexSet');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '\*')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$mul');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '/')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$div');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '%')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$mod');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '~/')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$tdiv');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '+')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$add');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&lt;&lt;')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$shl');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&gt;&gt;')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$shr');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&gt;=')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$ge');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&gt;')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$gt');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&lt;=')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$le');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&lt;')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$lt');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '&amp;')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$and');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '^')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$xor');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '|')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$or');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, '-')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$sub');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else if (identical(value, 'unary-')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return const SourceString(r'operator$negate');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    } else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      return name;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  }

**Comment by zanderso** [comment]
This looks stale.
