### ISSUE TITLE
Probably no static warning required here

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#13916]
I don't see why static type warning should be reported here.
Bar declared default constructor.
And factory constructor can redirect to an constructor that is its subtype.
And Bar() is subtype of Foo, because it has same parameter types and their return types are assignable.

// From Dart Language Specification, 0.12 M1, &quot;7.6.2 Factories&quot;: It is
// a compile-time error if a redirecting factory constructor does not
// redirect to a non-redirecting factory constructor or to a
// generative constructor in a finite number of steps.

// TODO(ahe): The above specification will probably change to
// something like: &quot;It is a compile-time error if a redirecting
// factory constructor redirects to itself, either directly or
// indirectly via a sequence of redirections.&quot;

class Foo extends Bar {
&nbsp;&nbsp;factory Foo() = Bar; /// 01: static type warning, dynamic type error
}

class Bar {
}

main() {
&nbsp;&nbsp;new Foo();
}

**Comment by askeksa-google** [comment]
The test has a cycle now, so it is testing what it claims to test.
