### ISSUE TITLE
Modify dart:isolate tests to run on Dartium

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#13921]
We no longer support spawnFunction from the DOM isolate on Dartium.  Instead, spawnUri must be used to create a background isolate (which cannot access dart:html).  spawnFunction may be used from background isolates.

The following tests now fail on Dartium.  We should consider either:
(a) Modifying the tests to use spawnUri
(b) Running them automatically in a background isolate (in the test framework?)

browser/compute_this_script_browser_stream_test: Fail
browser/compute_this_script_browser_test: Fail
count_stream_test: Fail
count_test: Fail
cross_isolate_message_test: Fail
global_error_handler2_test: Fail
global_error_handler_stream2_test: Fail
global_error_handler_stream_test: Fail
global_error_handler_test: Fail
illegal_msg_stream_test: Fail
illegal_msg_test: Fail
isolate_complex_messages_stream_test: Fail
isolate_complex_messages_test: Fail
mandel_isolate_stream_test: Fail
mandel_isolate_test: Fail
message2_test: Fail
message_stream2_test: Fail
message_stream_test: Fail
message_test: Fail
mint_maker_test: Fail
nested_spawn2_test: Fail
nested_spawn_stream_test: Fail
nested_spawn_test: Fail
request_reply_test: Fail
spawn_function_custom_class_test: Fail
spawn_function_test: Fail
stacktrace_message_test: Fail
unresolved_ports_test: Fail

**Comment by bkonyi** [comment]
Dartium is dead (woohoo!). Closing.
