### ISSUE TITLE
isolate/browser/typed_data_message_test failure not properly report on dartium 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#13961]
For some reason, this test is failing but being reported as a pass.

FAILED: none-drt-checked release_ia32 isolate/browser/typed_data_message_test
Expected: Fail 
Actual: Pass
CommandOutput[content_shell]:

stdout:
CONSOLE MESSAGE: unittest-suite-wait-for-done
CONSOLE MESSAGE: line 205: Error: 

http://127.0.0.1:54264/root_build/generated_tests/none-drt-checked/tests_isolate_browser_typed_data_message_test/test.html?crossOriginPort=41786:0:
spawnFunction is not supported from a dom-enabled isolate. Please use spawnUri instead.

CONSOLE MESSAGE: line 205: FAIL
Content-Type: text/plain
PASS
All 0 tests passed

**Comment by bkonyi** [comment]
Dartium is dead. Closing.
