### ISSUE TITLE
Dartium renderer crashes makes tests timeout on dartium tests

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#14074]
Running the tests in debug mode reveals us hitting a few different assertions:
IRST STACK (hit 2 times running all tests on dartium)

stderr: ASSERTION FAILED: !m_urlSourceMap.contains(url)
../../third_party/WebKit/Source/bindings/dart/DartAsyncLoader.cpp(134) : void WebCore::DartAsyncLoader::process(const WTF::String&amp;, const WTF::String&amp;, intptr_t)

stderr: 1   0x7f4d4f9661dc

stderr: 2   0x7f4d4f966efa

stderr: 3   0x7f4d4efe3e76

stderr: 4   0x7f4d4efe4152

stderr: 5   0x7f4d4efe4219

stderr: 6   0x7f4d4effccc9
7   0x7f4d423d8071

stderr: 8   0x7f4d49c31672 content::ResourceDispatcher::OnRequestComplete(int, int, bool, std::string const&amp;, base::TimeTicks const&amp;)

stderr: 9   0x7f4d49c35306

stderr: 10  0x7f4d49c34224 bool ResourceMsg_RequestComplete::Dispatch&lt;content::ResourceDispatcher, content::ResourceDispatcher, void (content::ResourceDispatcher::*)(int, int, bool, std::string const&amp;, base::TimeTicks const&amp;)&gt;(IPC::Message const*, content::ResourceDispatcher*, content::ResourceDispatcher*, void (content::ResourceDispatcher::*)(int, int, bool, std::string const&amp;, base::TimeTicks const&amp;))

stderr: 11  0x7f4d49c324f0 content::ResourceDispatcher::DispatchMessage(IPC::Message const&amp;)

stderr: 12  0x7f4d49c306e3 content::ResourceDispatcher::OnMessageReceived(IPC::Message const&amp;)

stderr: 13  0x7f4d49bad3bf content::ChildThread::OnMessageReceived(IPC::Message const&amp;)

stderr: 14  0x7f4d52320c40 IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&amp;)
15  0x7f4d52324952

stderr: 16  0x7f4d52324422
17  0x7f4d52323cc9

stderr: 18  0x7f4d534c070d

stderr: 19  0x7f4d5351c404 base::MessageLoop::RunTask(base::PendingTask const&amp;)

stderr: 20  0x7f4d5351c528 base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&amp;)

stderr: 21  0x7f4d5351ca4d base::MessageLoop::DoWork()

stderr: 22  0x7f4d53523508

stderr: 23  0x7f4d5351bf95 base::MessageLoop::RunInternal()

stderr: 24  0x7f4d5351be4c base::MessageLoop::RunHandler()

stderr: 25  0x7f4d53559964 base::RunLoop::Run()

stderr: 26  0x7f4d5351b7d4 base::MessageLoop::Run()

stderr: 27  0x7f4d49ff885e

stderr: 28  0x7f4d496af859

stderr: 29  0x7f4d496afaa7

stderr: 30  0x7f4d496b0c1a

stderr: 31  0x7f4d496aeee7 content::ContentMain(int, char const**, content::ContentMainDelegate*)

SECOND STACK (hit 3 times running all tests on dartium)

stderr: ASSERTION FAILED: m_eventPath[i]-&gt;eventPath()
../../third_party/WebKit/Source/core/dom/Event.cpp(196) : WTF::PassRefPtr&lt;WebCore::NodeList&gt; WebCore::Event::path() const

stderr: 1   0x7f35a4adcae9

stderr: 2   0x7f35a5c06c5b

stderr: 3   0x7f35a489744a
4   0x7f358face30b

THIRD STACK (hit 1 time running all tests on dartium)
stderr: ASSERTION FAILED: WTF::isMainThread()
../../third_party/WebKit/Source/core/fetch/MemoryCache.cpp(60) : WebCore::MemoryCache* WebCore::memoryCache()

stderr: 1   0x7fafd91dbc06

stderr: 2   0x7fafd91cc335

stderr: 3   0x7fafd91cb3f6

stderr: 4   0x7fafd9b42ae2

stderr: 5   0x7fafd9b439da

stderr: 6   0x7fafd9b45e3a

stderr: 7   0x7fafd8ab4d14

stderr: 8   0x7fafd8ab4d89

stderr: 9   0x7fafd8ab59a4

stderr: 10  0x7fafd8ab576e
11  0x7fafc465725d

**Comment by whesse** [comment]
We are currently rerunning all dartium tests, if they fail, because of this bug.  I plan to remove this rerunning step (we are first removing it for Safari), and see if flakiness returns, and if it is the same root cause.

**Comment by athomas** [comment]
Stale Dartium issue (which will no longer be supported on 2.0).
