### ISSUE TITLE
What is a line in Dart source?

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14073]
The specification says: &quot;Multiline strings are delimited by either matching triples of single quotes or matching triples of double quotes. If the first line of a multiline string consists solely of whitespace characters then that line is ignored, including the new line at its end.&quot;

This brings up the question of what is a line, and the &quot;new line at its end&quot;?

The specification includes the following grammar productions:

NEWLINE: \n | \r ;

WHITESPACE: ('\t' | ' ' | NEWLINE)+;

I see at least two problems with this definition:
1. On Windows, a line is terminated by CRLF, that is, the Dart string '\r\n'. However, the definition of NEWLINE implies that we should only strip the first '\r' leaving the '\n'. The fix would be to change the NEWLINE production to:

NEWLINE: '\n' | '\r\n' ;
1. The production for WHITESPACE includes NEWLINE, this leads to confusion when interpreting the quote in the beginning of this bug report.

**Comment by lrhn** [comment]
The spec has been updated to say that lines end in line-terminator sequences which are CR+LF, CR or LF, and that a line terminator only supplies one LF character to a multi-line string.
