### ISSUE TITLE
Move MirrorsUsed out of dart:mirrors

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14106]
There seems to be general consensus that @­MirrorsUsed is hard to use and otherwise problematic (in particular, introduces unfamiliar syntax).

Unfortunately, we don't a good answer to all the problems, and we need to experiment more.

So one idea that has come up is to move MirrorsUsed out of dart:mirrors and into a package to highlight its experimental nature.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
