### ISSUE TITLE
Streams article needs update to remove EventTransformStream

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#14148]
Due to EventTransformStream's removal, dartlang.org tests are failing. Could you please update the article and the tests? If the changes are straightforward, you can make them directly in github (https://github.com/dart-lang/dartlang.org/tree/master/src/site/articles/creating-streams). If not, you can either get your own dartlang.org git repo and make a CL, or give me the new code/words in whatever way is easiest for you.

You can view the article here:
https://www.dartlang.org/articles/creating-streams/

-k-

**Comment by lrhn** [comment]
Is this still relevant?

**Comment by kwalrath** [comment]
I'm not sure. If the stream tutorial covers everything you need, we can retire this article. If it doesn't, we should talk about doc needs for streams.

cc @Sfshaza

**Comment by lrhn** [comment]
I believe Kathy has a newer and better async streams tutorial at https://www.dartlang.org/docs/tutorials/streams/
@kwalrath : I think we can retire (mark as obsolete) the old one.

**Comment by kwalrath** [comment]
The [tutorial](https://www.dartlang.org/docs/tutorials/streams/) is about _using_ streams, and the [article](https://www.dartlang.org/articles/creating-streams/) is about _creating_ streams. We removed the really obsolete sections that used EventTransformStream & StreamEventTransformer.

If you think that people don't need info on creating streams (or at least, not up-to-date info on that)—then we can mark the article as obsolete.

If you think it would help developers, we could add links to the source for libraries that have good examples of creating streams.

**Comment by lrhn** [comment]
On Tue, Dec 8, 2015 at 7:44 PM, Kathy Walrath <notifications@github.com>
wrote:

> The tutorial <https://www.dartlang.org/docs/tutorials/streams/> is about
> *using* streams, and the article
> <https://www.dartlang.org/articles/creating-streams/> is about *creating*
> streams. We removed the really obsolete sections that used
> EventTransformStream & StreamEventTransformer.
>
> If you think that people don't need info on creating streams (or at least,
> not up-to-date info on that)—then we can mark the article as obsolete.
>
Ack, true, there is a difference.

> If you think it would help developers, we could add links to the source
> for libraries that have good examples of creating streams.
>
Or I could rewrite the article to use async*. I should probably do that. :)

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by kwalrath** [comment]
Rewriting to use async* would be great!
