### ISSUE TITLE
Check iterators

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#14178]
Username: kasperl

When we have code like this:

&nbsp;&nbsp;&nbsp;MyClass m = ...;
&nbsp;&nbsp;&nbsp;for (var x in m) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;}

it would be useful to get a warning or a hint if m doesn't implement the 'iterator' getter. Not sure if this is covered by the spec, but it might be (in which case it should be a warning).
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.1.2_r28706 (2013-10-16)
OS: Linux - i386 (3.2.5-gg1336)
JVM: 1.7.0-google-v5
# projects: 1
# open dart files: 11
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1933 / 684 / 147 MB
thread count: 32
index: 408792 relationships in 86532 keys in 297 sources

SDK installed: true
Dartium installed: false

**Comment by srawlins** [comment]
This is done as of: cb7aa02.
