### ISSUE TITLE
improve VM error messages when 2 imports collide

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#14202]
Let's improve the error message when 2 imports include names that collide.  When I first run into this, I had no idea I had a name conflict and I kept thinking that my import was wrong, or the name I used had a typo... 

Here is a simple example with 3 files:

a.dart:
&nbsp;&nbsp;import 'b.dart';
&nbsp;&nbsp;import 'c.dart';
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;new Foo();
&nbsp;&nbsp;}

b.dart:
&nbsp;&nbsp;library b;
&nbsp;&nbsp;class Foo {}

c.dart:
&nbsp;&nbsp;library c;
&nbsp;&nbsp;class Foo {}

running: `dart a.dart` produces this error:

Unhandled exception:
'a.dart': Error: line 4 pos 7: type 'Foo' is not loaded
&nbsp;&nbsp;new Foo();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
malformed type used.
# ­0      main (a.dart:4:7)

**Comment by mraleph** [comment]
The error will be coming from CFE now. Closing this.
