### ISSUE TITLE
html/js_test/transferrables fails on IE10

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#14246]
html/js_test fails on IE10

**Comment by whesse** [comment]
Fixed in CL https://codereview.chromium.org/1380963003
Status updated in https://codereview.chromium.org/1379363002/

**Comment by whesse** [comment]
One of the subtests, transferrables, is still failing on IE10 and IE11.  Putting it in the status file.

**Comment by Markzipan** [comment]
Closing this since IE11 is no longer supported by our web targets.
