### ISSUE TITLE
Directory.watch reports incorrect events on OS X

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#14373]
On jmesserly's OS X 10.8.5 laptop, running the following code:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:io';

&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Directory(&quot;test&quot;).createSync();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File(&quot;test/foo&quot;).writeAsStringSync(&quot;foo&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Directory(&quot;test&quot;).watch().listen((e) =&gt; print(e));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File(&quot;test/foo&quot;).writeAsStringSync(&quot;foo&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;}

produces this output:

&nbsp;&nbsp;&nbsp;&nbsp;FileSystemCreateEvent('test/foo')
&nbsp;&nbsp;&nbsp;&nbsp;FileSystemModifyEvent('test/foo', contentChanged=true)
&nbsp;&nbsp;&nbsp;&nbsp;FileSystemDeleteEvent('test/foo')

This is clearly wildly incorrect. The creation of the file happened before the watcher began, and the file was never deleted at all.

**Comment by munificent** [comment]
I still see this issue on my Mac. If I run the above with a directory name that has never been created, I get:

```
FileSystemCreateEvent('test')
FileSystemCreateEvent('test/foo')
FileSystemModifyEvent('test/foo', contentChanged=true)
```

If I run:

```
rm -r test && dart watch.dart
```

Then I get:

```
FileSystemCreateEvent('test')
FileSystemDeleteEvent('test')
FileSystemCreateEvent('test/foo')
FileSystemModifyEvent('test/foo', contentChanged=true)
FileSystemDeleteEvent('test/foo')
```

**Comment by zichangg** [comment]
I'm not able to reproduce this issue on my Mac 10.15.6. I'll close the issue.

**Comment by scheglov** [comment]
I'm still seeing unexpected `create` event for this code (with `test` and its `test/foo` removed).
```dart
import 'dart:io';

main() {
  new Directory("test").createSync();
  new File("test/foo").writeAsStringSync("foo");
  new Directory("test").watch().listen((e) => print(e));
  new File("test/foo").writeAsStringSync("foo");
}
```
Output:
```
FileSystemCreateEvent('test/foo')
FileSystemModifyEvent('test/foo', contentChanged=true)
```

**Comment by aam** [comment]
It seems that underlying file system events api on mac os that we use for file/directory watching is coarse grained and can't be used to watch for fine-grained changes.
From https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/TechnologyOverview/TechnologyOverview.html#//apple_ref/doc/uid/TP40005289-CH3-SW1

```
In addition to collapsing notifications for changes to multiple files into a single, per-directory notification, the file system events daemon also coalesces multiple notifications on a given directory if they occur in a short period of time. You will always receive at least one notification after the last change is made.
...
It is not a mechanism for registering for fine-grained notification of filesystem changes
...
The file system events API is also not designed for finding out when a particular file changes. For such purposes, the kqueues mechanism is more appropriate.
...
The file system events API is designed for passively monitoring a large tree of files for changes.
```

So kqueues (https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/KernelQueues/KernelQueues.html) seems to be the technology that would give more precision, but will be more resource-intensive:
```
File system events are intended to provide notification of changes with directory-level granularity. For most purposes, this is sufficient. In some cases, however, you may need to receive notifications with finer granularity. For example, you might need to monitor only changes made to a single file. For that purpose, the kernel queue (kqueue) notification system is more appropriate.

If you are monitoring a large hierarchy of content, you should use file system events instead, however, because kernel queues are somewhat more complex than kernel events, and can be more resource intensive because of the additional user-kernel communication involved.
```

**Comment by devoncarew** [comment]
@aam - I see the following in the macos native watcher code:

```
      FSEventStreamStart(ref_);
      FSEventStreamFlushSync(ref_);
```

I'm curious what would happen if you ignored any native events from the flush call? If you emptied that native queue when a watcher is set up? Something like:

```
  bool ignoreInitialEvents = true;

...

  FSEventStreamStart(ref_);
  FSEventStreamFlushSync(ref_);
  ignoreInitialEvents = false;
```

Where `ignoreInitialEvents` is something that would be respected in the `Callback()` method.

**Comment by aam** [comment]
> I'm curious what would happen if you ignored any native events from the flush call?

I've experimented with this by adding print statements to before/after FlushSync call and inside of Callback itself, and what I saw is that "bogus" events(like create directory that happened before watcher was set up) still do come even after FlushSync was completed.

**Comment by devoncarew** [comment]
Ah, ok, it's not the complete flush that we would hope for.

**Comment by vsmenon** [comment]
@devoncarew @aam - is there anything further actionable here?  This is still marked P1.

**Comment by a-siva** [comment]
Based on the comments regarding how the API on macOS works  there are limitations here. 
Lowering the priority to P2 and will let @devoncarew confirm if there are alternatives that the analyzer could use in the Dart code.

**Comment by brianquinlan** [comment]
Can we just document the behavior on Mac OS X with a pointer to Apple's documentation?

**Comment by a-siva** [comment]
> Can we just document the behavior on Mac OS X with a pointer to Apple's documentation?

I am fine with that.

**Comment by brianquinlan** [comment]
I have a proposed documentation change here: https://dart-review.git.corp.google.com/c/sdk/+/268610

**Comment by brianquinlan** [comment]
Documented in f910f23469950deffbaca9568313c9f7e8420acb
