### ISSUE TITLE
Graphical glitch in solar3d sample.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#14387]
The solar3d sample on https://www.dartlang.org/samples/solar3d/ exposes a graphical glitch.
See http://i.imgur.com/vAw7sQL.png (as reported in issue #14386).

**Comment by srawlins** [comment]
I don't see this glitch on Mac OS X, Chrome 47. What platform was this observed on?

**Comment by floitschG** [comment]
Can still reproduce in Version 49.0.2618.8 dev (64-bit) on Linux.

**Comment by srawlins** [comment]
The solar3d sample has been archived.
