### ISSUE TITLE
Out of memory errors can cause a segmentation fault

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#14431]
I haven't found a way to consistently reproduce this, but I've occasionally seen segmentation faults that, when run in GDB, seem to be caused by out-of-memory exceptions.

**Comment by zanderso** [comment]
Was this on 32-bit? In general, we don't have a whole lot of control over what will go wrong when we're out of address space, but if you have a consistent repro feel free to re-open.

**Comment by nex3** [comment]
I haven't seen this in a long time, so I'm okay with marking it AssumedStale.
