### ISSUE TITLE
Crash in VM when running dart2js

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#14439]
python genastress.py 363
export DART_VM_OPTIONS=&quot;--old_gen_heap_size=16384&quot;
time out/ReleaseX64/dart-sdk/bin/dart2js stress.dart
Segmentation fault (core dumped)
real    7m23.529s
user    7m16.230s
sys 0m5.390s

I was unable to attach the code given the 10MB restriction.
//Lars

**Comment by rmacnak-google** [comment]
Cannot be reproduced without the test or test generator.
