### ISSUE TITLE
Add compression to dart:io WebSockets

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#14441]
There is a draft for compression frames: https://tools.ietf.org/id/draft-tyoshino-hybi-websocket-perframe-deflate-05.txt.

WebKit currently implements some draft of this, and advertises it as:

Sec-WebSocket-Extensions:x-webkit-deflate-frame

**Comment by butlermatt** [comment]
I took over this change from Kenneth. Current review:

https://codereview.chromium.org/1390353005/

**Comment by sgjesse** [comment]
Fix from @butlermatt and @kaendfinger landed in https://github.com/dart-lang/sdk/commit/95bb2159d9fb7f44d3bbc99932a57173e1b464aa.
