### ISSUE TITLE
main(args) could drag in lots of code

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#14455]
spawnUri is typed to receive a list of strings for &quot;args&quot;. But a [sendport] would not raise any type check warnings.

This means that, even in checked mode, main(args) could receive a SendPort and would therefore require isolate support (with all the code this implies).

We should discuss how we want to fix this. One way is to check on the spawner side (which is what we currently do in dart2js, but not in the VM).
Another option is to check on the spawnee side.

Note: even with one argument we still need rudimentary isolate support since the program could be launched in a web-worker.

Assigning to dart2js, but it really is a Library/Dart2js issue.

**Comment by matanlurey** [comment]
Dart2JS doesn't support this API anymore.
