### ISSUE TITLE
dart2js: canonicalize longish strings in JS output

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#14514]
We should be able to avoid generating extra copies of long strings in the JS output. For swarm we have a number of candidates:

96 x &quot;Lorem ipsum something or other...&quot;
27 x &quot;_EventStream&quot;
18 x &quot;__proto__&quot;
16 x &quot;&lt;non-identifier-key&gt;&quot;
15 x &quot;Future already completed&quot;
12 x &quot;sel&quot;
11 x &quot;IterableBase&quot;
10 x &quot;in-story&quot;
10 x &quot;Event&quot;
10 x &quot;No elements&quot;
8 x &quot;msg&quot;
8 x &quot;MappedIterable&quot;
7 x &quot;translate3d(&quot;
7 x &quot;command&quot;
7 x &quot;_BroadcastStreamController&quot;
6 x &quot;none&quot;
5 x &quot;px,&quot;
5 x &quot;func&quot;
5 x &quot;start&quot;
5 x &quot;null&quot;
4 x &quot;Cannot assign element of immutable List.&quot;
4 x &quot;ListIterable&quot;
4 x &quot;height&quot;
4 x &quot;width&quot;
4 x &quot;ref&quot;
4 x &quot;&quot;&gt;&quot;
4 x &quot;port&quot;
4 x &quot;Cannot resize immutable List.&quot;
4 x &quot;...&quot;
4 x &quot;false&quot;
4 x &quot;px,0px)&quot;
4 x &quot;true&quot;
4 x &quot;div&quot;
4 x &quot;Object&quot;
4 x &quot;replyTo&quot;
4 x &quot;HTMLElement&quot;
4 x &quot;display&quot;

**Comment by rakudrama** [comment]
Local duplicates of strings (and other values) are shared in the function: https://github.com/dart-lang/sdk/commit/f96362ccfda6abfadb52f5bf998a5a82e7b0e8b3
Repeated accesses to large strings are via a per-unit constant pool https://github.com/dart-lang/sdk/commit/d8b7ec5163f377f5da004ccf3e9b2c3b8668748a
