### ISSUE TITLE
Abstract classes cannot be created with a 'new' expression

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#14526]
language/

abstract_exact_selector_test: StaticWarning
abstract_runtime_error_test: StaticWarning

stderr:
WARNING|STATIC_WARNING|NEW_WITH_ABSTRACT_CLASS|/Users/scheglov/Source/Dart/dart/tests/language/abstract_exact_selector_test.dart|18|14|3|Abstract classes cannot be created with a 'new' expression

Command[dartanalyzer]: sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --show-package-warnings --package-root=xcodebuild/ReleaseIA32/packages/ --machine --no-hints /Users/scheglov/Source/Dart/dart/tests/language/abstract_exact_selector_test.dart
Took 0:00:02.659000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -cdartanalyzer -rnone -t240 language/abstract_exact_selector_test

**Comment by natebosch** [comment]
I don't get a failure running either `python tools/test.py -mrelease -cdart2analyzer -rnone -t240 language/abstract_exact_selector_test` or `python tools/test.py -mrelease -cdart2analyzer -rnone -t240 language_2/abstract_exact_selector_test`

Should we close this?
