### ISSUE TITLE
NON_CONSTANT_LIST_ELEMENT

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#14529]
language/bad_initializer1_negative_test

FAILED: dartanalyzer-none release_ia32 language/bad_initializer1_negative_test
Expected: Pass
Actual: CompileTimeError
CommandOutput[dartanalyzer]:

stderr:
ERROR|COMPILE_TIME_ERROR|NON_CONSTANT_LIST_ELEMENT|/Users/scheglov/Source/Dart/dart/tests/language/bad_initializer1_negative_test.dart|9|52|5|'const' lists must have all constant values
ERROR|COMPILE_TIME_ERROR|REFERENCE_TO_DECLARED_VARIABLE_IN_INITIALIZER|/Users/scheglov/Source/Dart/dart/tests/language/bad_initializer1_negative_test.dart|9|52|5|The name 'elems' cannot be referenced in the initializer of a variable with the same name

Command[dartanalyzer]: sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --show-package-warnings --package-root=xcodebuild/ReleaseIA32/packages/ --machine --no-hints /Users/scheglov/Source/Dart/dart/tests/language/bad_initializer1_negative_test.dart
Took 0:00:00.022000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -cdartanalyzer -rnone -t240 language/bad_initializer1_negative_test

**Comment by whesse** [comment]
This is a duplicate of #14880.  Negative tests that fail in the analyzer phase are reported as broken, when they should be failing there since they are negative.  Closing.  This issue number should be replaced by 14880 in the status file line.
