### ISSUE TITLE
PART_OF_NON_PART

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#14528]
application_negative_test

FAILED: dartanalyzer-none release_ia32 language/application_negative_test
Expected: Pass
Actual: CompileTimeError
CommandOutput[dartanalyzer]:

stderr:
ERROR|COMPILE_TIME_ERROR|PART_OF_NON_PART|/Users/scheglov/Source/Dart/dart/tests/language/application_negative_test.dart|6|6|19|The included part ''failing_main.dart'' must have a part-of directive
WARNING|STATIC_WARNING|UNDEFINED_IDENTIFIER|/Users/scheglov/Source/Dart/dart/tests/language/failing_main.dart|6|3|6|Undefined name 'Expect'

Command[dartanalyzer]: sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --show-package-warnings --package-root=xcodebuild/ReleaseIA32/packages/ --machine --no-hints /Users/scheglov/Source/Dart/dart/tests/language/application_negative_test.dart
Took 0:00:00.278000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -cdartanalyzer -rnone -t240 language/application_negative_test

**Comment by askeksa-google** [comment]
This seems to be a duplicate of https://github.com/dart-lang/sdk/issues/31210
