### ISSUE TITLE
Swarm has a lot of test suppressions

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#14523]
The following tests seem to have started failing after running these tests in an iframe instead of a new browser window.

dart2js-safari:

samples/swarm/test/swarm_test (http://build.chromium.org/p/client.dart/builders/dart2js-safari-mac10.7-3-3-be/builds/1218/steps/dart2js-safari%20tests%20failures/logs/stdio)

html/websql_test/functional (http://build.chromium.org/p/client.dart/builders/dart2js-safari-mac10.7-2-3-be/builds/1164/steps/dart2js-safari%20tests%20failures/logs/stdio)

dart2js-chrome:

samples/swarm/test/swarm_test (build.chromium.org/p/client.dart/builders/dart2js-chrome-mac10.7-be/builds/900/steps/dart2js-chrome%20tests%20failures/logs/stdio)

@blois/efortuna:
Do these tests have the requirement that they run in a new window?
Are the failures legitimate?

**Comment by rakudrama** [comment]
We don't run swarm tests anymore.
