### ISSUE TITLE
dart2js bug in classMirror.metadata: metadata should not be inherited

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#14559]
Dart2js and the Dartvm seem inconsistent in the implementation of ClassMirror.metadata. Looking at the api, it seems that the vm behavior matches what's documented.

Here is a test case that can be used to repro this:

&nbsp;&nbsp;import 'dart:mirrors';
&nbsp;&nbsp;const meta = &quot;annotation&quot;;

&nbsp;&nbsp;@­meta
&nbsp;&nbsp;class A {}

&nbsp;&nbsp;class B extends A {}

&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;print('A: ${reflectClass(A).metadata.length}');
&nbsp;&nbsp;&nbsp;&nbsp;print('B: ${reflectClass(B).metadata.length}');
&nbsp;&nbsp;}

The dartvm will print: 
&nbsp;&nbsp;A: 1
&nbsp;&nbsp;B: 0

dart2js will print:
&nbsp;&nbsp;A: 1
&nbsp;&nbsp;B: 1

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
