### ISSUE TITLE
List<String> not a subtype of List<String> in function type test

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14573]
typedef T Func&lt;T&gt;();

class Foo&lt;S&gt; {
&nbsp;&nbsp;m(x) =&gt; x is Func&lt;S&gt;;
}

class Bar&lt;T&gt; {
&nbsp;&nbsp;f() {
&nbsp;&nbsp;&nbsp;&nbsp;T local() {}
&nbsp;&nbsp;&nbsp;&nbsp;return local;
&nbsp;&nbsp;}
}

void main() {
&nbsp;&nbsp;var x = new Foo&lt;List&lt;String&gt;&gt;();
&nbsp;&nbsp;if (new DateTime.now().millisecondsSinceEpoch == 42) x = new Foo&lt;int&gt;();
&nbsp;&nbsp;print(x.m(new Bar&lt;String&gt;().f()));
&nbsp;&nbsp;print(x.m(new Bar&lt;List&lt;String&gt;&gt;().f()));
}

**Comment by srawlins** [comment]
This now just prints (using the VM):

```
false
true
```

**Comment by lrhn** [comment]
That's the correct result, and dart2js does the same, so I guess the problem has been fixed at some point.
