### ISSUE TITLE
What is analyze_library/lib/_internal/dartdoc/lib/src/json_serializer testing?

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14618]
If I run:

sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --show-package-warnings --package-root=xcodebuild/ReleaseIA32/packages/ --fatal-warnings --fatal-type-errors --show-sdk-warnings --machine --no-hints /Users/ahe/Dart/all/dart/sdk/lib/_internal/dartdoc/lib/src/json_serializer.dart

I get these errors, warnings, and hints:

ERROR|COMPILE_TIME_ERROR|REFERENCED_BEFORE_DECLARATION|/Users/ahe/Dart/all/dart/sdk/lib/collection/list.dart|331|28|6|Local variables cannot be referenced before they are declared
ERROR|STATIC_WARNING|NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_FIVE_PLUS|/Users/ahe/Dart/all/dart/sdk/lib/collection/hash_set.dart|88|7|7|Missing inherited members: 'IterableBase.map', 'IterableBase.isEmpty', 'IterableBase.join', 'IterableBase.lastWhere' and 36 more
ERROR|STATIC_WARNING|NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_FIVE_PLUS|/Users/ahe/Dart/all/dart/sdk/lib/collection/linked_hash_set.dart|25|7|13|Missing inherited members: 'IterableBase.every', 'IterableBase.isEmpty', 'IterableBase.join', 'IterableBase.toSet' and 36 more
ERROR|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/Users/ahe/Dart/all/dart/sdk/lib/convert/codec.dart|74|31|30|The return type '_InvertedCodec&lt;T, S&gt;' is not a 'Codec&lt;T, S&gt;', as defined by the method 'inverted'
INFO|HINT|UNUSED_IMPORT|/Users/ahe/Dart/all/dart/sdk/lib/_internal/dartdoc/lib/src/json_serializer.dart|12|8|12|Unused import
INFO|HINT|UNNECESSARY_CAST|/Users/ahe/Dart/all/dart/sdk/lib/async/future_impl.dart|521|40|22|Unnecessary cast
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/core/errors.dart|15|26|16|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|UNUSED_IMPORT|/Users/ahe/Dart/all/dart/sdk/lib/isolate/isolate.dart|18|8|17|Unused import
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|75|7|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|75|7|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|78|9|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|78|9|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|110|7|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|110|7|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|113|9|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|IS_DOUBLE|/Users/ahe/Dart/all/dart/sdk/lib/math/math.dart|113|9|11|When compiled to JS, this test might return true when the left hand side is an int
INFO|HINT|UNUSED_IMPORT|/Users/ahe/Dart/all/dart/sdk/lib/mirrors/mirrors.dart|51|8|12|Unused import
INFO|HINT|UNUSED_IMPORT|/Users/ahe/Dart/all/dart/sdk/lib/mirrors/mirrors.dart|52|8|14|Unused import

However, if I run the test:

python tools/test.py -mrelease -cdartanalyzer -rnone -t240 analyze_library/lib/_internal/dartdoc/lib/src/json_serializer

It doesn't fail.

**Comment by srawlins** [comment]
I'm closing this as stale.
