### ISSUE TITLE
Dartium tests should respect VMOptions from test files

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#14651]
Certain tests require the correct options to be passed to the VM to pass. Dartium needs to pass these on to Dart VM when running Dartium tests.

One example is language/issue13474_test.

**Comment by whesse** [comment]
Because we use a pool of open Dartium browsers to run all the dartium tests, we don't have a separate browser instance for each test.  Therefore we can't pass separate dart VM options to dartium for each test.  Since Dartium is heading for deprecation, I don't think this is worth fixing.
