### ISSUE TITLE
dart2js source mirrors should either provide access to exports or include exported elements

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#14669]
In the context of docgen, we are using dart2js source mirrors to extract the documentation information. However, the library mirrors we receive do not include exported members, and as far as I can see there is no way to retrieve them. We can look them up by name if we already know the name, but there is no way to get the list of names. So a program of the form

library stuff;
import 'src/otherStuff.dart';
export 'src/otherStuff.dart';
&lt;EOF&gt;
then has no documentation.

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
