### ISSUE TITLE
Document mirrorsused w/ advanced article

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#14661]
Post 1.0 we should have a 201/301 article on how to shrink your app's JavaScript size with MirrorsUsed. Probably part of a holistic effort to fully sweep through and document mirrors.

**Comment by srawlins** [comment]
Can this be closed?

Is that this? https://www.dartlang.org/articles/reflection-with-mirrors/

**Comment by sethladd** [comment]
Thanks for checking into this. We can close this issue.
