### ISSUE TITLE
VariableMirror.isConst does not exist

### ISSUE THREAD

**Issue by DrMarcII** [dart-lang/sdk#14671]
**What steps will reproduce the problem?**
1. In Dart VM (not checked in Dartium or dart2js)
2. Get a VariableMirror for an instance field on a class
3. Call isConst on it

**What is the expected output? What do you see instead?**
Expected: false (an instance field can't be const)
Actual: 
Caught Class '_LocalVariableMirrorImpl' has no instance getter 'isConst'.
&nbsp;&nbsp;
&nbsp;&nbsp;NoSuchMethodError : method not found: 'isConst'
&nbsp;&nbsp;Receiver: Instance of '_LocalVariableMirrorImpl@0x4863bc9'

**What version of the product are you using? On what operating system?**
Dart VM version: 0.8.7.0_r29341 (Mon Oct 28 02:00:50 2013) on &quot;linux_x64&quot;

**Please provide any additional information below.**

**Comment by srawlins** [comment]
Seems to work fine now:

issue-14671.dart:

```dart
import 'dart:mirrors';

void main() {
  ClassMirror cm = reflectClass(MyClass); // Reflects MyClass;
  for (var m in cm.declarations.values) {
    var name = MirrorSystem.getName(m.simpleName);
    if (m is VariableMirror) {
      print("VariableMirror for $name. isConst? ${m.isConst}");
    }
  }
}

class MyClass {
  int i;

  static const int j = 0;
}
```

```shell
$ dart issue-14671.dart
VariableMirror for i. isConst? false
VariableMirror for j. isConst? true

$ dart --version
Dart VM version: 1.12.1 (Tue Sep  8 04:10:39 2015) on "macos_x64"
```
