### ISSUE TITLE
Mixins part of superinterfaces.

### ISSUE THREAD

**Issue by szakarias** [dart-lang/sdk#14713]
In dart2js the example below prints &quot;[ClassMirror on 'Mixin']&quot; while on the vm it prints &quot;[]&quot;. In the specification, the next to last paragraph in Chapter 9's introduction seems to imply the former (that the mixin should be part of the superinterfaces of the class that mixes it in) but I couldn't find any specific mentioning of this.

class Mixin {}
class A {}
class B = A with Mixin;

main() {
&nbsp;&nbsp;print(reflectClass(B).superinterfaces);
}

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
