### ISSUE TITLE
Add getOrElse() to Map

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#14740]
As mentioned by Lasse in 6640, Map is missing the get analogue to putIfAbsent, getOrElse:

&nbsp;&nbsp;V getOrElse(K key, V fallback()) {
&nbsp;&nbsp;&nbsp;&nbsp;.. do internal lookup ..;
&nbsp;&nbsp;&nbsp;&nbsp;if (...not there...) return fallback();
&nbsp;&nbsp;&nbsp;&nbsp;return ... value of lookup ...;
&nbsp;&nbsp;}

**Comment by srawlins** [comment]
This is a duplicate of #2643.

**Comment by floitschG** [comment]
Thanks.
Closing as duplicate of #2643.
