### ISSUE TITLE
Out of memory in test.dart

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14761]
Check out r29345.

Patch in https://codereview.chromium.org/57773002 (this CL prints a lot of debug information to stdout).

Run:

./tools/test.py -mrelease -cdart2js -rd8 --time -pcolor --report --failure-summary --checked

This leads to this crash in test.dart:

Test configuration: dart2js_d8_release_ia32_checked
[00:47 |  --% | +  419 | -    0]Total: 10058 tests
&nbsp;* 107 tests will be skipped (7 skipped by design)
&nbsp;* 10 tests are expected to be flaky but not crash
&nbsp;* 8991 tests are expected to pass
&nbsp;* 28 tests are expected to fail that we won't fix
&nbsp;* 552 tests are expected to fail that we should fix
&nbsp;* 2 tests are expected to crash that we should fix
&nbsp;* 9 tests are allowed to timeout
&nbsp;* 0 tests are skipped on browsers due to compile-time error

[11:28 |  45% | + 4536 | -    0]Exhausted heap space, trying to allocate 268435472 bytes.
Uncaught Error: Out of Memory
Stack Trace:
# ­0      List._grow (dart:core-patch/growable_array.dart:166:24)
# ­1      List.add (dart:core-patch/growable_array.dart:129:12)
# ­2      addAll (dart:core-patch/growable_array.dart:136:10)
# ­3      _BufferingStreamSubscription._sendData.&lt;anonymous closure&gt; (dart:async/stream_impl.dart:184:55)
# ­4      _ZoneBase._runInZone (dart:async/zone.dart:82:17)
# ­10     _ZoneBase._runGuarded (dart:async/zone.dart:99:22)
# ­11     _ZoneBase.executePeriodicCallbackGuarded (dart:async/zone.dart:68:21)
# ­12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:184:41)
# ­13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:135:16)
# ­14     _StreamController&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:198:23)
# ­15     _StreamController._add (dart:async/stream_controller.dart:130:16)
# ­16     _StreamController.add (dart:async/stream_controller.dart:104:9)
# ­17     _onData (dart:io-patch/socket_patch.dart:827:42)
# ­18     _BufferingStreamSubscription._sendData.&lt;anonymous closure&gt; (dart:async/stream_impl.dart:184:55)
# ­19     _ZoneBase._runInZone (dart:async/zone.dart:82:17)
# ­20     _ZoneBase._runGuarded (dart:async/zone.dart:99:22)
# ­21     _ZoneBase.executePeriodicCallbackGuarded (dart:async/zone.dart:68:21)
# ­22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:184:41)
# ­23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:135:16)
# ­24     _StreamController&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:198:23)
# ­25     _StreamController._add (dart:async/stream_controller.dart:130:16)
# ­26     _StreamController.add (dart:async/stream_controller.dart:104:9)
# ­27     _RawSocket._RawSocket.&lt;anonymous closure&gt; (dart:io-patch/socket_patch.dart:544:52)
# ­28     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:344:39)
# ­29     _NativeSocket.connectToEventHandler.&lt;anonymous closure&gt; (dart:io-patch/socket_patch.dart:429:54)
# ­30     _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)

Unhandled exception:
Out of memory

**Comment by bkonyi** [comment]
Has this been resolved? Closing for now, assuming it isn't relevant anymore.
