### ISSUE TITLE
dart analyzer bat file does not work from within directories containing parenthesis

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#14795]
To reproduce, extract a build from our builders, rename it to, e.g., foobar(), and run the analyzer on some dart code

Fails with a strange exception

Trying the same simple fix we did for dart2js does not work, there are more escaping to be done.

**Comment by pq** [comment]
Bumping this one... @danrubel do you have any even vague memories of this issue?  Should we keep it open?

**Comment by danrubel** [comment]
No idea. Good question.

**Comment by bwilkerson** [comment]
I'm going to guess that we're not going to fix this (unless it's already been fixed).

**Comment by ricowind** [comment]
you can just test it by doing the suggested repro in the initial bug :-)
