### ISSUE TITLE
Report which import of dart:mirrors does not have MirrorsUsed

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#14839]
Output today:

packages/serialization/src/mirrors_helpers.dart:12:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';

If dart2js -v could tell me, in obvious terms, that a particular import of mirrors didn't specify MirrorsUsed, I can then better track down the culprit.

**Comment by sigmundch** [comment]
dart2js now reports where the imports to mirrors come from. It doesn't highlight which ones are missing the annotation, but it should narrow it down quickly for our users.
