### ISSUE TITLE
language/ref_before_declaration_test/none

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#14879]
There are actually for &quot;P&quot;, so analyzer reports warning which is not annotated.

FAILED: dartanalyzer-none release_ia32 language/ref_before_declaration_test/none
Expected: Pass
Actual: StaticWarning
CommandOutput[dartanalyzer]:

stderr:
WARNING|STATIC_TYPE_WARNING|UNDEFINED_METHOD|/Users/scheglov/Source/Dart/dart/xcodebuild/ReleaseIA32/generated_tests/language/ref_before_declaration_test_none.dart|43|7|1|The method 'P' is not defined for the class 'C'

Command[dartanalyzer]: sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --show-package-warnings --package-root=xcodebuild/ReleaseIA32/packages/ --machine --no-hints /Users/scheglov/Source/Dart/dart/xcodebuild/ReleaseIA32/generated_tests/language/ref_before_declaration_test_none.dart
Took 0:00:00.011000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -cdartanalyzer -rnone -t240 language/ref_before_declaration_test/none

**Comment by whesse** [comment]
Fixed in https://codereview.chromium.org/2901853002 @peter-ahe-google
