### ISSUE TITLE
dart2js source mirrors give wrong answer for isConstConstructor

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#14917]
e.g. if you get a mirror for the default constructor for Symbol it returns false to &quot;isConstConstructor&quot;

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
