### ISSUE TITLE
type_promotion_test 12, 13, 14

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#14933]
FuncDynToVoid &lt;&lt; FuncDynToDyn

dart2js/type_promotion_test/12: RuntimeError
dart2js/type_promotion_test/13: RuntimeError
dart2js/type_promotion_test/14: RuntimeError

**Comment by johnniwinther** [comment]
The fix would make << symmetric on ()->void and ()->dynamic

**Comment by sigmundch** [comment]
tracking in .status instead
