### ISSUE TITLE
dartj2s source mirrors should allow you to choose a different version of a library, in particular, the dartium version of html, which has better documentation

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#14939]
Right now, if I pass &quot;dart:html&quot; to dart2js.analyze, it choose the dart2js version of the library, and there isn't an obvious way at the level of that API to tell it to do something different. If I pass it a file path to the dartium version of the library it fails with the output 

../../../sdk/lib/html/dartium/html_dartium.dart:29:8: Error: Internal library 'dart:_collection-dev' is not accessible from 'file:///Users/alanknight/dart-git/dart/sdk/lib/html/dartium/html_dartium.dart'.
import 'dart:_collection-dev' hide Symbol, deprecated;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^
../../../sdk/lib/html/dartium/html_dartium.dart:36:8: Error: Library not found 'dart:nativewrappers'.
import 'dart:nativewrappers';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^
../../../sdk/lib/html/dartium/html_dartium.dart:19809:45: Unexpected token
&nbsp;&nbsp;static MutationObserver \_create(callback) native &quot;MutationObserver_constructorCallback&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^
Breaking on exception: compiler cancelled: Unexpected token

See https://code.google.com/p/dart/issues/detail?id=10991

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
