### ISSUE TITLE
Add hint for missing setters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#14959]
There should be a hint in the following code:

class Foo {
&nbsp;&nbsp;&nbsp;Bar get bar =&gt; null;
&nbsp;}

&nbsp;class Bar {}

&nbsp;main() {
&nbsp;&nbsp;&nbsp;var foo = new Foo();
&nbsp;&nbsp;&nbsp;foo.bar = new Bar(); // 'foo' does not have a setter named 'bar'
&nbsp;}

**Comment by srawlins** [comment]
There _is_ a warning on missing setters, if you declare `foo` with `Foo foo = ...` instead of `var foo`.

To get the warning with `var foo`, you must use `dartanalyzer --strong`. Close as fixed?
