### ISSUE TITLE
dart2js does no see hashCode having type int

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#14951]
When running dart2js on the following program

main() {
&nbsp;&nbsp;var o = new Object();
&nbsp;&nbsp;print((1 + o.hashCode) &amp; 0xFF);
}

I get the warning

test.dart:3:9: Warning: No operator '&amp;' in class 'num'.
&nbsp;&nbsp;print((1 + o.hashCode) &amp; 0xFF);

If o is types as Object the warning goes away. That is compiling the following two programs gives no warnings.

main() {
&nbsp;&nbsp;Object o = new Object();
&nbsp;&nbsp;print((1 + o.hashCode) &amp; 0xFF);
}

main() {
&nbsp;&nbsp;print((1 + new Object().hashCode) &amp; 0xFF);
}

**Comment by rakudrama** [comment]
Still happens. This is a problem with the type checker.

**Comment by srawlins** [comment]
dart2js now prints 71, no longer errors.
