### ISSUE TITLE
searchable_list sample test timeout in IE9

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#15047]
Marking as Pass/Timeout for now.

This is probably the same issue we are seeing with all polymer tests in IE9. 

See example log here:

http://chromegw.corp.google.com/i/client.dart/builders/dart2js-ie9-win7-all-4-6-be/builds/1174/steps/dart2js-ie9%20tests/logs/stdio

Relevant text:

FAILED: dart2js-ie9 release_ia32 samples/searchable_list/test/demo_app_test
Expected: Pass 
Actual: Timeout
CommandOutput[polymer_deploy]:

stdout:
polymer/deploy.dart: creating a deploy target for &quot;searchable_list&quot;
Done! All files written to &quot;E:/b/build/slave/dart2js-ie9-win7-all-4-6-be/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test&quot;

CommandOutput[dart2js]:

stdout:
build/ReleaseIA32/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test/test/demo_app_test.html_bootstrap.dart:1:1: Hint: 60 methods retained for use by dart:mirrors out of 2564 total methods (2%).
library app_bootstrap;

build/ReleaseIA32/packages/polymer/polymer.dart:50:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/observe/src/observable.dart:16:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/observe/src/path_observer.dart:10:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/polymer_expressions/eval.dart:12:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/polymer_expressions/src/mirrors.dart:11:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/polymer/deserialize.dart:8:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors' show TypeMirror;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
build/ReleaseIA32/packages/polymer/src/reflected_type.dart:11:1: Info: Import of 'dart:mirrors'.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^

CommandOutput[ie9]:

stdout:
Dom could not be fetched, since the test timed out.

stderr:
This test has not notified test.py that it started running. This could be a bug in test.py! Please contact ricow/kustermann

BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:

BrowserOutput.stderr:

To retest, run:  E:\b\build\slave\dart2js-ie9-win7-all-4-6-be\build\dart\tools\testing\bin\windows\dart.exe /E:/b/build/slave/dart2js-ie9-win7-all-4-6-be/build/dart/tools/testing/dart/http_server.dart -p 60520 -c 60521 --build-directory=E:\b\build\slave\dart2js-ie9-win7-all-4-6-be\build\dart\build\ReleaseIA32 --runtime=ie9

Command[polymer_deploy]: build\ReleaseIA32\dart.exe --package-root=build/ReleaseIA32/packages/ package:polymer/deploy.dart --test E:\b\build\slave\dart2js-ie9-win7-all-4-6-be\build\dart\samples\searchable_list\test\demo_app_test.html --out E:/b/build/slave/dart2js-ie9-win7-all-4-6-be/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test
Took 0:00:01.623000

Command[dart2js]: build\ReleaseIA32\dart-sdk\bin\dart2js.bat --package-root=build/ReleaseIA32/packages/ --out=E:/b/build/slave/dart2js-ie9-win7-all-4-6-be/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test/test/demo_app_test.html_bootstrap.dart.js E:/b/build/slave/dart2js-ie9-win7-all-4-6-be/build/dart/build/ReleaseIA32/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test/test/demo_app_test.html_bootstrap.dart
Took 0:00:22.900000

Command[ie9]: \E:\b\build\slave\dart2js-ie9-win7-all-4-6-be\build\dart\tools\testing\bin\windows\dart.exe tools/testing/dart/launch_browser.dart ie9 http://127.0.0.1:60520/root_build/generated_tests/dart2js-ie9/samples_searchable_list_test_demo_app_test/test/demo_app_test.html?crossOriginPort=60521
Took 0:01:00.001446

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -mrelease -cdart2js -rie9 --use-sdk --write-debug-log --use_browser_controller -t60 samples/searchable_list/test/demo_app_test

Done dart2js-ie9 release_ia32 samples/searchable_list/test/demo_app_test: fail

**Comment by srawlins** [comment]
There is no more searchable_list sample.
