### ISSUE TITLE
pkg/template_binding_test started failing on ie9 checked with revision 30299

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#15093]
I have compared dart2js output of r30299 and r30298 and both are the same.

log: http://build.chromium.org/p/client.dart/builders/dart2js-ie9-win7-all-5-6-be/builds/888/steps/dart2js-ie9%20tests%20--checked/logs/stdio

**Comment by srawlins** [comment]
There is no more template_binding_test.
