### ISSUE TITLE
dart2js errors have stack traces that don't remain identical over time.

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#15171]
Consider the following code:

&nbsp;&nbsp;&nbsp;&nbsp;var st1;
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'bad';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} catch (e, st) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;st1 = st;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rethrow;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;} catch (e, st2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(st1 == st2);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(identical(st1, st2));
&nbsp;&nbsp;&nbsp;&nbsp;}

On the VM, this prints &quot;true&quot; and &quot;true&quot;, but on dart2js it prints &quot;false&quot; and &quot;false&quot;. This makes it difficult to compare stack traces for equality and impossible to use them in expandos, which is blocking my work on issue #7040 on dart2js.

**Comment by sigmundch** [comment]
Forgot to close this - this was fixed in 1763aa3467d53c2129b440e126e01749ad51b677
