### ISSUE TITLE
Hint about non-useful concat being possible typo

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#15199]
I could wish for a hint when I'm concatenating adjacent strings together when it's at least possible I mean something else. e.g.

&nbsp;&nbsp;path.join(path.dirname(scriptDir), 'doc'  'sdk-introduction.md');

where the method I'm calling at least has the ability to take an additional parameter, and I'm concatenating two constant strings on the same line, which really doesn't gain me anything.

Alan Knight
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.0.0_r30187 (2013-11-12)
OS: Mac OS X - x86_64 (10.8.5)
JVM: 1.6.0_65
# projects: 3
# open dart files: 45

auto-run pub: false
localhost resolves to: 127.0.0.1
mem max/total/free: 1983 / 681 / 246 MB
thread count: 48
index: 702637 relationships in 142552 keys in 604 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
This has the strong possibility of yielding false positives. Should this be a linter instead? Similar to https://github.com/dart-lang/linter/issues/225.
