### ISSUE TITLE
Loading isolates from localhost doesn't work with a proxy

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#15215]
For details, see issue #15161. Here's a simple script that loads an isolate from localhost:

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpServer.bind('localhost', 0).then((server) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server.listen((request) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.response.write(&quot;fn() =&gt; print('in isolate');&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.response.close();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File('/tmp/test.dart').writeAsStringSync('''
&nbsp;&nbsp;&nbsp;&nbsp;import &quot;http://${server.address.host}:${server.port}/file.dart&quot;;

&nbsp;&nbsp;&nbsp;&nbsp;main() =&gt; fn();
&nbsp;&nbsp;&nbsp;&nbsp;''');

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Isolate.spawn(bufferedSpawn, '/tmp/test.dart');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;bufferedSpawn(uri) =&gt; Isolate.spawnUri(Uri.parse(uri), [], null);

**Comment by Bikeman868** [comment]
I notice that this thread is from 2014 and I am still having this issue in 2017. Was this issue never fixed? and is there a workaround?

**Comment by kevmoo** [comment]
@Bikeman868 – another option is to use `data:` URIs – then you don't even need to spin up a server.

**Comment by Bikeman868** [comment]
@kevmoo I have quite good knowledge of the Dart language but very little knowledge of how the Pub tool works or how to configure it. I just use `pub get` and `pub build` and that's it. I have no clue what `data:` URIs are and have never spun up a server.

**Comment by kevmoo** [comment]
Can I close this re https://github.com/dart-lang/pub/issues/1677#issuecomment-326651224 ?

**Comment by Bikeman868** [comment]
I closed it already (12 days ago)

**Comment by Bikeman868** [comment]
Oh, this is not the issue in your link. Yes, please close this issue.
