### ISSUE TITLE
dart2js should give functions meaningful names

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#15225]
dart2js produces anonymous functions, e.g:

SomeClass {
&nbsp;&nbsp;somefunction$0: function() { ... }
}

---

For debugging, dart2js should produce named functions, e.g.:

SomeClass {
&nbsp;&nbsp;somefunction$0: function SomeClass$somefunction$0() { ... }
}

this will improve the quality of debugging output.

**Comment by Khushipatil13** [comment]
One solution to improve the generated code of dart2js is to give functions more meaningful names. Currently, the names of the functions generated by dart2js are often not descriptive, making it difficult to understand what they do when debugging. By providing more descriptive names, it would be easier to identify the purpose of each function in the generated code and make debugging more efficient. This could be achieved by analyzing the source code of the Dart program and generating more descriptive names based on the function's behavior and purpose.

**Comment by sigmundch** [comment]
Marking this issue as obsolete.

* dart2js goal is to optimize for deployment. For debugging we use DDC
* DDC has debugger support to fully preserve symbol information
* dart2js encodes naming information on the side, which is used by deobfuscation tools today.
