### ISSUE TITLE
dart2js: used-type inference for hidden native classes during codegen

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#1525]
Instances of hidden native classes can reach the Dart program via four paths:

(1) returned from a native method or getter,
&nbsp;&nbsp;e.g. aha = document.getElementById();

(2) passed to functions which escape to the native world
&nbsp;&nbsp;e.g.  element.addEventListenter((e) =&gt; doIt());

(3) passed to methods on objects which escape to the native world.

(4) anything transitively reachable from the results of (2), (3) also escapes.

For dart:dom and dart:html we only need to consider (1) and (2), since all objects in class (3) have been typedef-ed as callback functions, and all callbacks return simple types.

This analysis will prevent the gratuitous generation of code like the following since in most programs, Float64Array will be determined to be unused:

// \*\*\*\*\*\*\*\*\*\* Code for \_Float64ArrayJs \*\*\*\*\*\*\*\*\*\*\*\*\*\*
var \_Float64ArrayJs = {};
$dynamic(&quot;get$length&quot;).Float64Array = function() {
&nbsp;&nbsp;return this.length;
}
$dynamic(&quot;$index&quot;).Float64Array = function(index) {
&nbsp;&nbsp;return this[index];
}

**Comment by sigmundch** [comment]
@rakudrama - seems like this is now been done for quite some time? I'm closing the issue assuming so, but please reopen if not.
