### ISSUE TITLE
@MirrorsUsed needs way to retain all instance methods with a certain name

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#15408]
Consider that you want to test if an object supports a given method but don't want to check for NoSuchMethodError.

In this case you cannot point to a specify instance method (if you could, you could just have used an &quot;is&quot; test).

In the current @­MirrorsUsed this could be:

@MirrorsUsed(instanceMethods: 'foo')
import 'dart:mirrors';

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
