### ISSUE TITLE
Analyzer does not handle aliases of @proxy

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#15467]
Analyzer does not handle aliases of @­proxy, like 

const alias = proxy;

@alias
class AliasProxy {}

Failing language tests:
language/proxy_test/05
language/proxy_test/06

**Comment by stereotype441** [comment]
I did some preliminary work on this ages ago.  The plan was to:

1. Don't report warnings that can be suppressed by `@proxy` in the resolver; instead, store enough information in the AST that the errors can be reported later by the ErrorVerifier.
2. Use constant evaluation to determine the values of annotations.
3. In the ErrorVerifier, make use of the constant evaluation results to determine whether a class is annotated with `@proxy`, and use that to decide whether to issue the warning or not.

I believe steps 1 and 2 have been completed.
