### ISSUE TITLE
minified JS is broken

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#15477]
I'm getting a random one-off error with minified output. App works without crashing when unminified.

Here's the output from the same code, broken and not

Broken minified dart2js output: https://github.com/dart-lang/widget.dart/commit/f5a2f1c39e7737b694466dee45e1e5ab5b028db8

Working dart2js output: https://github.com/dart-lang/widget.dart/commit/611973a80c88d934171c30f25f301c99d2472680
______
**Attachment:**
[Screen Shot 2013-12-05 at 2.31.26 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-15477/comment-0/Screen Shot 2013-12-05 at 2.31.26 PM.png) (407.13 KB)

**Comment by sigmundch** [comment]
@kevmoo - do you know if this is still an issue?

**Comment by kevmoo** [comment]
I think we can close it :smile:
