### ISSUE TITLE
dart2js erroneous warning

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#15494]
new Set.from(someList == null ? [] : 
&nbsp;&nbsp;&nbsp;&nbsp;someList);

outputs:

--- Dec 6, 2013 10:27:42 AM Running dart2js... ---
myexample.dart Warning: 'EfficientLength' is not assignable to 'Iterable&lt;dynamic&gt;'.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Set.from(someList.channelIds == null ? [] : 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/core/set.dart:54:11: Info: This is the method declaration.
&nbsp;&nbsp;factory Set.from(Iterable&lt;E&gt; other) = LinkedHashSet&lt;E&gt;.from;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^

This is not expected.

**Comment by srawlins** [comment]
Whatever this was has been fixed. Try in Dart Pad:

```dart
void main() {
  var someList = ['a', 'b'];
  var l2 = new Set.from(someList == null ? [] : someList);
  print(l2);

  someList = null;
  var l3 = new Set.from(someList == null ? [] : someList);
  print(l3);
}
```

It prints:

```
{a, b}
{}
```
