### ISSUE TITLE
Flaky co19/LibTest/async/Future/Future.delayed_A01_t02

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#15524]
The test co19/LibTest/async/Future/Future.delayed_A01_t02 looks like this (co19 rev 672):

&nbsp;20 check(delayms, value) {
&nbsp;21   Duration delay=durationMs(delayms);
&nbsp;22   Stopwatch sw=new Stopwatch();
&nbsp;23   sw.start();
&nbsp;24   asyncStart();
&nbsp;25   Future future = new Future.delayed(delay, (){
&nbsp;26     Duration elapsed=sw.elapsed;
&nbsp;27     Expect.isTrue(elapsed &gt;= delay, &quot;delay=$delay, elapsed=${elapsed}&quot;);
&nbsp;28     asyncEnd();
&nbsp;29   });
&nbsp;30 }
&nbsp;31 
&nbsp;32 main() {
&nbsp;33   check(0, 11);
&nbsp;34   check(300, 3);
&nbsp;35   check(50, 22);
&nbsp;36 }

(Note: the second argument to check is ignored)

It seems like this is a legitimate test, it calls Future.delayed() with a &quot;delay&quot; and asserts that the callback is only called after &quot;delay&quot; using a StopWatch.

This test is highly flaky on both the standalone VM and dartium (it surprised me that it's flaky on both, I would expect that standalone VM and dartium have different timer implementations).

Could someone from dartium and someone from dart:io investigate?
[Setting Area-IO, but this is dartium as well]

@floitsch: Maybe you can give some insight into the implementation of Future.delayed?

**Comment by lrhn** [comment]
We need a Dartium developer to check if this is still a problem.
