### ISSUE TITLE
Consider improving error message for top-level expressions

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#15534]
When a JavaScript programmer comes to Dart, one possible mistake that is easy to make is to forget to put all code in a main method.

See the discussion in https://groups.google.com/a/dartlang.org/d/msg/misc/gs6DzCA-mHk/-Gy3TCY5JNYJ.

The user had written something like this:

library altapp;

import 'package:logging/logging.dart';

Logger.root.level = Level.ALL;

But should have written:

library altapp;

import 'package:logging/logging.dart';

main() {
&nbsp;&nbsp;Logger.root.level = Level.ALL;
}

The error message was:

'file:///Users/ahe/Dart/all/dart/js.dart': error: line 5 pos 1: unexpected token 'Logger'
Logger.root.level = Level.ALL;
^

**Comment by mraleph** [comment]
This is obsolete because VM does not parse the code anymore.
