### ISSUE TITLE
Improve inlining of closure calls in Dart VM

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#15558]
When a local function calls another local function like in this example:

test(a, b) {
&nbsp;&nbsp;f(x, y) =&gt; x + y;
&nbsp;&nbsp;g(x, y) =&gt; f(x, y);
&nbsp;&nbsp;return g(a, b);
}

the optimizing compiler should be able to inline f into g. As of now, it can't do this yet.

**Comment by rmacnak-google** [comment]
I think this was fixed by 79a5307d5be58037f053912c1aec2067f0eb9975

**Comment by fsc8000** [comment]
Not in this case where one closure calls another closure: Inlining g into main works. Inlining f into g into main does not. Right now, it would require doing store-to-load forwarding on the callee graph of g to eliminate the load of f from the context.

**Comment by rmacnak-google** [comment]
@alexmarkov
