### ISSUE TITLE
DateTime creation in local time zone uses UTC instead if getting the local time zone offset causes an error

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#15560]
We've occasionally seen flaking on Dartium on the round-trip date parsing tests where a date is printed one way and parsed back and the result fails. It seems that what's happening is that the resulting date is off from the desired one by the amount of a UTC correction. It particularly seems to happen on low information formats, e.g. just the month name or month and year. but that may just be coincidence.

An example failure is
Date mismatch!
&nbsp;&nbsp;Expected 7
&nbsp;&nbsp;Got 6
&nbsp;&nbsp;Original date = 2012-07-27 13:58:59.012
&nbsp;&nbsp;Original ms = 1343422739012
&nbsp;&nbsp;Parsed back to 1970-06-30 17:00:00.000
&nbsp;&nbsp;Parsed ms = 15638400000
&nbsp;&nbsp;Original tz = -7:00:00.000000
&nbsp;&nbsp;Current tz name = 
&nbsp;&nbsp;Current tz = -7:00:00.000000
&nbsp;&nbsp;Current tz name = 
&nbsp;&nbsp;Start time = 2013-12-06 15:34:23.363
&nbsp;&nbsp;Current time 2013-12-06 15:34:23.387
....
FAIL: Test round-trip parsing of dates
Expected: '7' 
&nbsp;&nbsp;Actual: '6' 
&nbsp;&nbsp;&nbsp;Which: is different.
Expected: 7
&nbsp;&nbsp;Actual: 6
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^  
&nbsp;Differ at offset 0

package:unittest/src/simple_configuration.dart 141:7                                                                   SimpleConfiguration.onExpectFailure
...
package:unittest/src/expect.dart 75:29                                                                                 expect
../../../../root_dart/pkg/intl/test/date_time_format_test_core.dart 188:13                                             testRoundTripParsing
../../../../root_dart/pkg/intl/test/date_time_format_test_core.dart 261:29                                             runDateTests.&lt;fn&gt;

**Comment by alan-knight** [comment]
Not stale. Still happens.

**Comment by lrhn** [comment]
We are, however, still not fixing it.
