### ISSUE TITLE
Analyzer needs a better error...

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#15571]
Top of my library; nothing included except default dart:core.
&nbsp;&nbsp;&nbsp;&nbsp;class Node {
&nbsp;&nbsp;&nbsp;&nbsp;}

&quot;The name 'Node' is already defined&quot;
## 

What I expect: What's the other instance of Node.

**Comment by srawlins** [comment]
I think this can be closed. I can't recreate this error message.

**Comment by zoechi** [comment]
I get such an error often when I port code to Dart where the code has lots of syntax errors. After some of the errors are fixed (strings properly closed, curly braces properly closed, `===` changed to `==`, and various others) the error goes away eventually. I haven't found a simple repo yet.

**Comment by srawlins** [comment]
Closing as stale / no reproduction.
