### ISSUE TITLE
MirrorsUsed cannot merge symbols

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#15599]
Given a library which imports dart:mirrors with:

library a;
@MirrorsUsed(symbols: ['foo'])
import 'dart:mirrors';

Then another import which attempts to modify the first with:
@MirrorsUsed(symbols: const ['bar'], override: 'a')
import 'dart:mirrors';

The dart2js compiler fails with:

Internal error: Unsupported operation: Cannot add to a non-extendable array
# ­0      List.addAll (dart:core-patch/array.dart:230)
# ­1      MirrorUsageAnalyzer.merge (file:///mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/compiler/implementation/mirrors_used.dart:311)
# ­2      MirrorUsageAnalyzer.mergeUsages (file:///mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/compiler/implementation/mirrors_used.dart:289)

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
