### ISSUE TITLE
MirrorsUsed cannot narrow symbols

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#15600]
package:js uses dart:mirrors but only needs symbols. It would be great if by default it could only pull in symbols via:

@MirrorsUsed(symbols: '*')
import 'dart:mirrors';

The problem is that once this is done, then no one can narrow this down further (the symbols appear to be additive, and bug 15599 prevents merging).

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
