### ISSUE TITLE
breakpoint moves to strange lines

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#15634]
Breakpoints getting out of sync. I have a breakpoint set in comment.dart, on line 101, inside an if statement that I put there so I could have a breakpoint. It's shown in the text editor. When the program runs it does indeed print &quot;foo&quot;. When I look at the list of breakpoints, I see two active breakpoints in comment.dart, on the same line, 189. The file is 126 lines long.

Alan Knight
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.1.0.edge_031110 (2013-12-12)
OS: Mac OS X - x86_64 (10.9)
JVM: 1.6.0_65
# projects: 6
# open dart files: 56

auto-run pub: false
localhost resolves to: 127.0.0.1
mem max/total/free: 1983 / 636 / 329 MB
thread count: 54
index: 1204090 relationships in 213068 keys in 558 sources

SDK installed: true
Dartium installed: true

---

**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-15634/comment-0/screenshot.png) (338.08 KB)

**Comment by mhausner** [comment]
Breakpoint resolution has long been fixed.
