### ISSUE TITLE
String has no operator< etc

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#15693]
to reproduce:
'foo' &gt; 'bar' yields
&quot;Unhandled exception: Class 'String' has no instance method '&gt;'.&quot;
that sucks.  so we need 'foo'.compareTo('bar') &gt; 0, which looks horrible.

javascript and python let us compare strings with &lt;, &gt;, &lt;=, etc.
dart lets us compare numbers (1 &lt; 2).  why not strings?
Comparables should get &lt;, &gt;, &lt;=, etc defined for free.

here is one possible implementation: if a class implements Comparable
and a relational operator is not explicitly overridden, let it just
delegate to compareTo.  who would complain about such a feature?

Dart VM version: 1.0.2.1_r30821 (Tue Dec  3 12:51:29 2013) on &quot;linux_x64&quot;

**Comment by lrhn** [comment]
We don't expect to add `<` to `String`. The recommendation is to use `compareTo` or other specialized string comparison functions (like case-insensitive compare). 

(And I still think we should have character code literals).
