### ISSUE TITLE
VariableElement.computeType does not use the right scope.

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#15700]
VariableElement.computeType does not use the right scope since local declaration are not taken into accounter. For instance:

class Foo {}

void test(var o) {
&nbsp;&nbsp;String Foo;
&nbsp;&nbsp;void m(Foo foo) {}
}

Here the type of 'foo' will be the class 'Foo' and not the malformed type that is the reference of the local variable 'Foo'.

---

**Attachment:**
[compute_type.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-15700/comment-0/compute_type.dart) (159 Bytes)

**Comment by srawlins** [comment]
Obsolete as of CFE?

**Comment by johnniwinther** [comment]
Yes.
