### ISSUE TITLE
No-arg method hint request

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#15710]
I wish there was a hint that told me when I had a method with no arguments and I was just closurizing it and throwing the result away rather than calling it.

Alan Knight
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.1.0.edge_031147 (2013-12-13)
OS: Mac OS X - x86_64 (10.9)
JVM: 1.6.0_65
# projects: 6
# open dart files: 63

auto-run pub: false
localhost resolves to: 127.0.0.1
mem max/total/free: 1983 / 1049 / 407 MB
thread count: 70
index: 1203850 relationships in 218639 keys in -7715 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
I still think we should have a lint for this.

**Comment by zoechi** [comment]
Work in progress https://github.com/dart-lang/linter/pull/1014#issuecomment-395787139
I haven't found the new PR @davidmorgan mentioned.

**Comment by pq** [comment]
Closing here in favor of follow-up on the linter (and `unnecessary_statements`).

Thanks!
