### ISSUE TITLE
Add performance numbers for snapshot startup

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#15728]
We have benchmarks here: http://www.dartlang.org/performance

One of the benefits of the Dart VM is faster startup with snapshots. It would be nice to have some numbers to point to for demonstrating the real performance improvements.

It was suggested that we could compile dart2js with dart2js and load/run the resulting
output with V8 to get some comparable numbers with the minified Dart source code.

**Comment by mraleph** [comment]
This is stale.
