### ISSUE TITLE
serve/warns_on_assets_paths_test is failing on the Windows bot, but not locally

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#15741]
I just checked in a new test for pub. It passes everywhere, including on my local Windows machine. But it's failing on the bot with:

&nbsp;Results of running 'pub serve':
&nbsp;&nbsp;Process exited with exit code -1.
&nbsp;&nbsp;Standard output:
&nbsp;&nbsp;| MSG : Serving myapp on http://127.0.0.1:59461
&nbsp;&nbsp;| MSG : Build completed successfully
&nbsp;&nbsp;Standard error:
&nbsp;&nbsp;| FINE: Pub 0.1.2+3
&nbsp;&nbsp;| IO  : Spawning cmd /c ver
&nbsp;&nbsp;| IO  : Finished ver. Exit code 0.stdout:Microsoft Windows [Version 6.1.7601]Nothing output on stderr.
&nbsp;&nbsp;| IO  : Listing directory C:\Users\CHROME~2\AppData\Local\Temp\pub_3ddf4566-68f5-11e3-adfc-005056030208\myapp\web.
&nbsp;&nbsp;| IO  : Listing directory C:\Users\CHROME~2\AppData\Local\Temp\pub_3ddf4566-68f5-11e3-adfc-005056030208\myapp\web\foo.
&nbsp;&nbsp;| IO  : Listing directory C:\Users\CHROME~2\AppData\Local\Temp\pub_3ddf4566-68f5-11e3-adfc-005056030208\myapp\web\foo\assets.

I didn't think a negative exit code was even possible. As you can see, no exception is thrown. It looks like the process just dies.

http://chromegw.corp.google.com/i/client.dart/builders/pub-win-be/builds/2695/steps/pub%20tests/logs/stdio

Any idea what's going on here?

**Comment by srawlins** [comment]
Neither `pub serve` nor `pub build` are valid commands any more.

```none
$ pub serve
Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2

$ pub build
Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2

$ pub --version
Pub 2.0.0-dev.63.0
```
