### ISSUE TITLE
Hot-swap code, reduce full-reload situations

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#15860]
As projects grow, and more app-y experiences are built, performing a full reload to test a fix tends to slow down development. Hot-swapping code can significantly speed up development. For example, change a method's implementation and see the effects immediately.

**Comment by johnmccutchan** [comment]
The VM now supports hot reload. Closing.

**Comment by gnomesley** [comment]
Any plans for hot reload in Dartium?

**Comment by zoechi** [comment]
@gnomesley no, Dartium is going to die and be replaced by DDC
There is currently no hot reload for DDC and AFAIK no current plans to support it (that might change eventually when DDC becomes more mature)
