### ISSUE TITLE
audiobuffersourcenode_test broken in chrome 32 roll

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#15913]
This test has stopped working in the Chrome 32 roll:

FAILED: none-drt-checked release_ia32 html/audiobuffersourcenode_test/functional
Expected: Pass 
Actual: RuntimeError
CommandOutput[content_shell]:

stdout:
# READY

CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;debug&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;test_controller.js started&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;print&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;dart-calling-main&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.218
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;print&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;dart-main-done&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.261
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;message_received&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;dart-calling-main&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.375
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;message_received&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;unittest-suite-wait-for-done&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.376
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;message_received&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;dart-main-done&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.376
}
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;message_received&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;unittest-suite-done&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.377
}
Content-Type: text/plain
FAIL
2   ERROR   Expectation: functional createBuffer. Test failed: Caught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable. (Dartium)
file:///usr/local/google/home/vsm/svn/dartium/src/out/Release/gen/blink/bindings/dart/dart/web_audio/AudioBufferSourceNode.dart 134  AudioBufferSourceNode._stop_1
file:///usr/local/google/home/vsm/svn/dartium/src/out/Release/gen/blink/bindings/dart/dart/web_audio/AudioBufferSourceNode.dart 127  AudioBufferSourceNode.stop
../../../../root_dart/tests/html/audiobuffersourcenode_test.dart 23:18                                                               main.&lt;fn&gt;.&lt;fn&gt;
../../../../root_dart/pkg/unittest/lib/src/test_case.dart 109:30                                                                     _run.&lt;fn&gt;
dart:async/future_impl.dart 453                                                                                                      _Future._propagateToListeners.&lt;fn&gt;
dart:async/zone.dart 683                                                                                                             _rootRun
dart:async/zone.dart 832                                                                                                             _RootZone.run
dart:async/future_impl.dart 445                                                                                                      _Future._propagateToListeners
dart:async/future_impl.dart 303                                                                                                      _Future._complete
dart:async/future_impl.dart 354                                                                                                      _Future._asyncComplete.&lt;fn&gt;
dart:async/schedule_microtask.dart 18                                                                                                _asyncRunCallback
file:///usr/local/google/home/vsm/svn/dartium/src/dart/tools/dom/src/native_DOMImplementation.dart 604                               _handleMutation
Total 0 passed, 0 failed 1 errors

**Comment by matanlurey** [comment]
I'm guessing we no longer care about ContentShell.
