### ISSUE TITLE
dart:js on dart2js - Uncaught ReferenceError: DartObject is not defined

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#15931]
import 'dart:js';

main() {
&nbsp;&nbsp;print(new Object());
&nbsp;&nbsp;print(new JsObject(context['Date'], []));
&nbsp;&nbsp;print(new JsObject(context['Image'], []));
}

dart2js/Chrome:
Uncaught ReferenceError: DartObject is not defined

Dartium:
Instance of 'Object'
Mon Jan 06 2014 16:13:19 GMT-0800 (PST)
[object HTMLImageElement]

Dart r31525
Chrome 32.0.1700.68 beta

**Comment by joshualitt** [comment]
This bug no longer seems to reproduce at TOT.
