### ISSUE TITLE
There are two separate snapshots for dart2js in the SDK, wasting space

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#15967]
kustermann writes:
As far as I remember we have a separate dart2js snapshot. With this we have
actually two versions of dart2js:
- snapshots/utils_wrapper.dart.snapshot
- snapshots/dart2js.dart.snapshot

This just blows up the sdk size!

**Comment by munificent** [comment]
I don't see utils_wrapper.dart.snapshot any more, so assuming this is stale.
