### ISSUE TITLE
Unfriendly error message from List constructor

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#15986]
I'm seeing this exception:

Illegal argument(s): Length must be an integer in the range [0..268435455].
#­0      List.List (dart:core-patch/array_patch.dart:20)
#­1      MirrorUsageBuilder.convertConstantToUsageList (file:///Users/ahe/Dart/all/dart/sdk/lib/_internal/compiler/implementation/mirrors_used.dart:428)
#­2      MirrorUsageAnalyzerTask.validate (file:///Users/ahe/Dart/all/dart/sdk/lib/_internal/compiler/implementation/mirrors_used.dart:150)

I'm not told what the offending value is. Is it null? A string? A negative number?

**Comment by lrhn** [comment]
Better error messages have been added.
