### ISSUE TITLE
Need a cryptographic random number generator

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#15993]
**[user feedback]**

I need a cryptographic random number generator, but the crypto package doesn't contain one =/ I know about the one in dart:html, but I need one for my console application.

As you support SSL in dart:io, the code should already be there, but no way to use it from Dart.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.1.0.dev_05_00 (2013-12-20)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 0
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 772 / 547 MB
thread count: 34
index: 475313 relationships in 92853 keys in 7341 sources

SDK installed: true
Dartium installed: true

**Comment by whesse** [comment]
Duplicate of #1746.  Closing, and leaving that one open.
