### ISSUE TITLE
pkgbuild failing with --use-public-packages on packages with *-dev dependencies

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#16026]
I recently changed pkg/watcher to use features available in an unreleased version of pkg/scheduled_test (v0.9.3-dev). As such, I upgraded watcher's dependency on scheduled_test to &quot;&gt;=0.9.3-dev &lt;0.10.0&quot;. However, this caused pkgbuild with --use-public-packages to fail, since 0.9.3-dev wasn't (and will never be) released.

It's clearly unworkable for package authors to modify test status files every time they switch to or away from using dev versions in their dependencies. Perhaps the pkgbuild tests should sniff the pubspecs for *-dev dependencies and avoid running --use-public-packages if they exist?

**Comment by whesse** [comment]
Obsolete - the --use-repo-packages and --use-public-packages flags have been removed.
