### ISSUE TITLE
Link from API docs to broadcast streams article

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#16028]
Could you please add links from whatever async/io/stream* library/class doc comments are appropriate to https://www.dartlang.org/articles/broadcast-streams/?

**Comment by natebosch** [comment]
We currently link to https://www.dartlang.org/guides/libraries/library-tour#dartasync---asynchronous-programming from the `dart:async` documentation.

From there it's pretty easy to get to https://www.dartlang.org/tutorials/language/streams

Does that cover this? Can we link to https://www.dartlang.org/articles/broadcast-streams/ from https://www.dartlang.org/tutorials/language/streams ?

Do you still think it's worthwhile to link directly from some other place in the API docs?

**Comment by kwalrath** [comment]
I think we're good.
