### ISSUE TITLE
VM does not respect @MirrorsUsed, leads to differences in behavior

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#16048]
Users are finding that apps run fine in VM but not when compiled via dart2js, when @­MirrorsUsed is used. This annotation changes the behavior of the app, but is only respected by one of our runtimes.

In an effort to help catch errors as early as possible, can we have the VM look at @­MirrorsUsed (and whatever we come up with in the future).

**Comment by rmacnak-google** [comment]
MirrorsUsed does not have a specified behavior for the VM to implement.

Those looking for consistent reflection across the VM and dart2js should look at

https://github.com/dart-lang/reflectable
