### ISSUE TITLE
VM: Reflective access to simple name of constructor should be consistent in declarations and newInstance

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#16075]
The simple name of a constructor should be the identifier without the class or the constant symbol for the empty string if it is a default constructor. Currently this is not the case with unfortunate consequences.

One cannot lookup a constructor and use its simple name to run it, because the &quot;simple&quot; name is actually qualified by the class name.  This leads to the need to do string surgery to call the constructor.
The qualified name ends up being library.Class.Class.id which is very confusing.

Once the simple name behaves correctly, these problems should go away.

See issue #13248.

**Comment by mraleph** [comment]
@rmacnak-google Is this something we are going to fix? If not consider closing this issue as stale.
