### ISSUE TITLE
Improve getter/setter tracking.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#16168]
Intercepted members require different calling-conventions than non-intercepted members. If an interceptor has only a getter (but no setter), then we should use the non-intercepted convention for the setters.

Example (native_mirror_test):
&equals;&equals;&equals;
class A native &quot;A&quot; {
&nbsp;&nbsp;final foo;
}

class B {
&nbsp;&nbsp;String foo;
}

main() {
&nbsp;&nbsp;var b = new B();
&nbsp;&nbsp;reflect(b).setField(new Symbol(&quot;foo&quot;), &quot;bar&quot;);
&nbsp;&nbsp;Expect.equals(&quot;bar&quot;, b.foo);
}
&equals;&equals;&equals;

The setter of foo (in checked mode verifying that the argument is a String) should not need to use the intercepted calling-convention.

**Comment by matanlurey** [comment]
Dart2JS no longer supports mirrors
