### ISSUE TITLE
Produce an official OpenShift cartridge for Dart

### ISSUE THREAD

**Issue by schultzter** [dart-lang/sdk#16235]
OpenShift is a great PaaS and while we wait for Google's AppEngine to support Dart it would be really cool if you provided an official OpenShift cartridge rather than have us rely on under-resourced 3rd parties or everyone rolling their own.

I speak from personal experience since I'm now stuck maintaining an AUR package I no longer use but I don't want to abandon either and leave the community hanging.

**Comment by mit-mit** [comment]
Closing as NotPlanned, for current server options please see https://www.dartlang.org/server/
