### ISSUE TITLE
Number parsing should have consistent API

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#16319]
**[user feedback]**

Why to the arguments differ between double.parse and int.parse? Same functionality but one time with optional arguments and the second time with named arguments?
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_01_00 (2014-01-17)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 4

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1149 / 136 MB
thread count: 37
index: 598084 relationships in 109534 keys in 72587 sources

SDK installed: true
Dartium installed: true

**Comment by rakudrama** [comment]
During the libraries review in 2017 we had settled on always having two parse methods.

```dart
int v = int.parse(input);  // throws on non-integer input
int v = int.tryParse(input) ?? -1;  // tryParse returns null on bad input
```

If we make any change to improve consistency, we should make this change.

I reviewed about 2000 of uses of the current `int.parse`. This supports the parse+tryParse design:

Most uses were `int.parse(input)` - this would be the same.

Of the remaining uses, 30% defaulted to null, and almost all of the rest to simple values like `0` or `-1`.
```dart
  int.parse(input, onError: (_) => null)
  int.parse(input, onError: (_) => 0)
```
can be written in a more concisely:
```dart
     int.tryParse(input)
     int.tryParse(input) ?? 0
```
Often the `onError: (_) => null` version is used with a following test:

```dart
  var value = int.parse(input, onError: (_) => null);
  if (value == null) ...
```
```dart
  var value = int.tryParse(input);
  if (value == null) ...
```

The tryParse design has efficiency advantages.  Creating and passing a function as `onError:` is slower and results in bigger code on both VM and dart2js than the tryParse alternative of checking the returned value against `null`.

Another efficiency advantage is that by pushing the null-handling into the call side, the compiler can more easily discover nullability:
```dart
  var value = int.parse(input, (_) => 0);
  if (value > 0) ...

  var value = int.tryParse(input) ?? 0;
  if (value > 0) ...
```
In the first example it would require a new and difficult analysis (non-local, higher-order) to determine `value` is not `null`. In the second example, it is obvious from the `??` operator. Practically, only in the tryParse case can code be generated for `value > 0` without a null check.


The migration path is not too painful:
1. Add tryParse methods
2. Deprecate the `onError:` (named or positional) arguments
3. Remove the `onError:` parameters at some future date

**Comment by rakudrama** [comment]
@lrhn This issue is marked as Milestone 2.0. Does this mean we can implement steps 1. and 2. of the migration for Dart 2.0 ?

**Comment by dgrove** [comment]
@lrhn are any further changes happening here for 2.0, or can it be removed from 2.0?

**Comment by lrhn** [comment]
I believe the `parse`/`tryParse` library update is still pending.

**Comment by dgrove** [comment]
Any updates?

**Comment by leafpetersen** [comment]
The CL adding tryParse and deprecating onError is ready to land:

https://dart-review.googlesource.com/c/sdk/+/50723

That's all that can happen for this milestone.

**Comment by dgrove** [comment]
That seems reasonable. The actual removal could be done post-Dart 2.0

**Comment by dgrove** [comment]
Please ensure that these land by Thursday CET. Otherwise, we'll have to do
this after Dart 2.0 stable.

**Comment by dgrove** [comment]
This has landed in the SDK.
