### ISSUE TITLE
Control how an isolate resolves imports

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#16368]
In pub's build system, we use isolates to implement a plug-in API. Those transformer plug-ins import other libraries. Currently, the VM gives us no control over how those imports are handled. This is broken for us for two reasons:
1. The package root for those imports is wrong. It uses pub's own package root, which is obviously meaningless for some random application.
2. The libraries being imported may be themselves the result of a transformer. In this case, we need to be in control of the actual contents of the library being imported.

These are both necessary for the semantics of the build system. To work around the lack of control here, we internally start an HTTP server. Then we use the analyzer to parse every loaded Dart file and rewrite its import directives to hit our server. Every byte of loaded code then has to go over HTTP before it gets into the isolate. Since HTTP imports are resolved synchronously, we also have to put *that* onto another isolate.

As you can imagine, this adds significant complexity to pub, as well as adding several seconds of pointless startup time when running pub build.

**Comment by rmacnak-google** [comment]
Package maps.
