### ISSUE TITLE
Issue tracker has template that uses non-existing Area.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#16361]
The template &quot;Request to host package on Pub&quot; pre-fills the labels with &quot;Pub-HostRequest&quot;, which is not a standard/defined value.

Since the pub tool can upload directly to the pub servers, is this template necessary any more?
If so, perhaps add the label, and add Type-Task to the template.
Otherwise remove the template.

**Comment by mit-mit** [comment]
Closing as state, assuming this is for the former tracker.
