### ISSUE TITLE
Analyzer fails to give errors on compile time constants

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#16391]
Errors in compile-time constants that would have created runtime error if run in checked mode produce a compile time error. For instance:

const int foo = 'foo';

The analyzer does not produce these errors. Maybe it should, or at least give a hint that there is a problem in checked mode.

In the case above, the code the produces a static type warning, but not all such errors are accompanied by a static warning. For instance

class A {
&nbsp;&nbsp;final int field;

&nbsp;&nbsp;const A(this.field);
}

class B extends A {
&nbsp;&nbsp;const B(field) : super(field);
}

const b = const B('');

Here there is no static warning, but the &quot;const B('')&quot; will fail at compile time in checked mode.

**Comment by srawlins** [comment]
There is a new-ish analyzer check, const_eval_throws_exception, which is printed out for this case:

```
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ cat 16391.dart 
class A {
  final int field;

  const A(this.field);
}

class B extends A {
  const B(field) : super(field);
}

const b = const B('');
$ dartanalyzer 16391.dart 
Analyzing 16391.dart...
  info • Evaluation of this constant expression throws an exception at 16391.dart:11:11 • const_eval_throws_exception
```
