### ISSUE TITLE
dart2js: bad optimization of "x is Null"  -- what does TypeMask.isEmpty mean?

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#16407]
main() {
&nbsp;&nbsp;foo('null', null);
&nbsp;&nbsp;foo('&quot;x&quot;', 'x');
&nbsp;&nbsp;print('null is Null =&gt; ${null is Null}');
}

var foo = (s, v) {
&nbsp;&nbsp;print('$s is Null = ${v is Null}');
};

This program prints:
null is Null = false
&quot;x&quot; is Null = false
null is Null =&gt; true

The problem is that 'v is Null' is replaced with 'false'.

SsaInstructionSimplifier.visitIs:

&nbsp;&nbsp;&nbsp;&nbsp;} else if (!RuntimeTypes.hasTypeArguments(type)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TypeMask expressionMask = expression.instructionType;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TypeMask typeMask = (element == compiler.nullClass)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;? new TypeMask.subtype(element)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: new TypeMask.nonNullSubtype(element);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (expressionMask.union(typeMask, compiler) == typeMask) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return graph.addConstantBool(true, compiler);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if (expressionMask.intersection(typeMask, compiler).isEmpty) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return graph.addConstantBool(false, compiler);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}

expressionMask.intersection(typeMask, compiler) evaluates to a type that prints as '[null]'.
This type returns true for .isEmpty.

I would expect .isEmpty to return true only for the type representing a completely empty set of values, that does not include a null value.
However, '.isEmpty' seems to be orthogonal to '.isNullable'.
There are several places in the intersection, union and other algorithms that seem to assume that the type representing the singleton set of values {null} is also .isEmpty
So it is not trivial to strengthen .isEmpty to my expected meaning.

I think we should strength isEmpty to make  t1.intersection(t2).isEmpty a reliable test, instead of having to also check the result is non-nullable like this code from types_propagation.dart:

&nbsp;&nbsp;&nbsp;&nbsp;TypeMask outputType = checkedType.intersection(inputType, compiler);
&nbsp;&nbsp;&nbsp;&nbsp;if (outputType.isEmpty &amp;&amp; !outputType.isNullable) {

If we keep isEmpty orthogonal to isNullable, TypeMask.isEmpty really needs to be documented!

**Comment by sigmundch** [comment]
Note that the test above will stop failing when I land [a change][1] that calculates `isDisjoint` explicitly] (I modified the line in SSA with the problem illustrated by Stephen above). However, the issue still exists in the type mask abstraction: it would be nice if `isEmpty` really means empty, not empty-or-null

[1]: https://codereview.chromium.org/1604333002/

**Comment by rakudrama** [comment]
This is fixed.
