### ISSUE TITLE
Multitest should have special tagging for checked-mode compile-time error.

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#16411]
Multitest should have special tagging for checked-mode compile-time error. For instance in language/compile_time_constant_checked_test we have:

final int x = 'foo'; /// 01: static type warning, dynamic type error
const int y = 'foo'; /// 02: static type warning, compile-time error
int z = 'foo'; /// 03: static type warning, dynamic type error

In production mode, only warnings are expected and in checked mode errors are expected. 'dynamic type error' is implicitly checked mode only, but 'compile-time error' is for both checked and unchecked mode, thus requiring status files to be annotated with 'MissingCompileTimeError, OK'.

We should, similar to 'dynamic type error', have a 'static type error' (or some other better name) for indicating that a compile-time error is only expected in checked mode.

**Comment by matanlurey** [comment]
Checked mode is a goner
