### ISSUE TITLE
Missing warning for dead code- {.. if() { .. return; } else { .. return; } return; }

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#16420]
Username: kasperl

When compiling this piece of code from AngularDart, I'd expect to be told that the last 'return true' statement is dead code. The analyzer doesn't tell me that, but dart2js does.

----
main() {
&nbsp;&nbsp;unit.filterStacks = true;
&nbsp;&nbsp;unit.formatStacks = false;
&nbsp;&nbsp;unit.filterTests((test) {
&nbsp;&nbsp;&nbsp;&nbsp;if (jasmine.ddescribeActive) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String name = test.currentGroup;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return name.indexOf('DDESCRIBE: ') != -1;
&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return true;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return true;
&nbsp;&nbsp;});
}

----

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.edge_032153 (2014-01-30)
OS: Linux - i386 (3.2.5-gg1336)
JVM: 1.7.0-google-v5
# projects: 2
# open dart files: 25

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 967 / 567 / 285 MB
thread count: 49
index: 495471 relationships in 100059 keys in 6260 sources

**Comment by srawlins** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/d7833e1c1f418bf602d0b9faec7bc868daa55cde.
