### ISSUE TITLE
Quick fix to create field

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#16435]
Refactoring options should include creating field. E.g. &lt;code&gt;this.foo = &quot;bar&quot;&lt;/code&gt; shoud suggest creating field foo.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.1.0.dev_05_11 (2014-01-15)
OS: Linux - amd64 (3.2.5-gg1336)
JVM: 1.7.0-google-v5
# projects: 2
# open dart files: 7

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1328 / 633 MB
thread count: 33
index: 996648 relationships in 179091 keys in 24453 sources

SDK installed: true
Dartium installed: true

**Comment by bwilkerson** [comment]
This would be a quick fix, not a refactoring, so I updated the labels.

@srawlins I have to question marking this as technical debt. Can we remove that label?

**Comment by srawlins** [comment]
Absolutely, I got a little label-happy a few weeks ago.

**Comment by asashour** [comment]
I guess this is implemented in [create_field.dart](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/dart/create_field.dart)

**Comment by jcollins-g** [comment]
Manually tested:

```
class A {
  A(this.y);
  void f() {
   this.x = 1; 
  }
  void g() {
   z = 2;
  } 
}
```

Using Dart 2.18.0-171.0.dev on IntelliJ build Build #IC-221.5787.30, all of `x`, `y`, and `z` appear to have create field fixes available and working.  Perhaps this was fixed elsewhere?  Closing.
