### ISSUE TITLE
Interface inheritance and override rules are unclear

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#16443]
The paragraph the defines 'inherited(J, K)' for interfaces (§8.1.1) uses the unclear wording 'm is a member of A'  instead of for instance the well-defined 'A declares m'.

This makes is unclear how to handle the synthetic members introduced in case of multiple inherited members.

Consider this:

class A {
&nbsp;&nbsp;method(int a) =&gt; null;
}
class B {
&nbsp;&nbsp;method(num a) =&gt; null;
}
abstract class C implements A, B {
&nbsp;&nbsp;// C has a 'method' of type '(dynamic) -&gt; dynamic'.
}
class Class implements C {
&nbsp;&nbsp;method(double a) =&gt; null;
}

If the synthetic '(dynamic) -&gt; dynamic' method in C is 'a member of C' the checking of 'method' declared in 'Class' should be done against the synthetic member, thus causing no warning since '(double) -&gt; dynamic' is a subtype of '(dynamic) -&gt; dynamic'.

If the synthetic '(dynamic) -&gt; dynamic' method in C is not 'a member of C' the checking of 'method' declared in 'Class' should be done against the members declared in A and B, thus causing a warning for the override of the method declared in A since '(double) -&gt; dynamic' is a not subtype of '(int) -&gt; dynamic'.

I think the latter should be the case, since it would be consistent with the hierarchy in which 'Class' directly overrides methods in 'A' and 'B':

class A {
&nbsp;&nbsp;method(int a) =&gt; null;
}
class B {
&nbsp;&nbsp;method(num a) =&gt; null;
}
class Class implements A, B {
&nbsp;&nbsp;method(double a) =&gt; null; /// warning for the override of A.method.
}

**Comment by eernstg** [comment]
No Dart 2 milestone: This is now considered a subtask of #31228, which has a Dart 2 milestone.

**Comment by eernstg** [comment]
No Dart 2 milestone: This is now considered a subtask of #31228, which has a Dart 2 milestone.

**Comment by eernstg** [comment]
Said feature specification was completed, and then 614ae7f362ac2df8500c050862e76c4fc66b8822 integrated this topic into dartLangSpec.tex.
