### ISSUE TITLE
There is a number of analyzer errors against libraries/dart2js

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#16524]
There is a number of unassigned suppression for CompileTimeErrors on the analyzer in tests/analyzer/analyze_library.status for libraries/dart2js. Since these seem to overlap a lot I am filing them all under this bug, please divide the work between you.

I will mark these with this bug number, please go through them and fix up the status files or make bugs against the analyzer if there are bugs there.

Also cc some Seattle people since this may have some overlap with dart:html stuff. Tentatively assigning this to area library, but feel free to split this up or change it.

Marking the following with this bug:
lib/indexed_db/dart2js/indexed_db_dart2js: CompileTimeError
lib/indexed_db/dartium/indexed_db_dartium: CompileTimeError
lib/_internal/compiler/samples/compile_loop/compile_loop: CompileTimeError
lib/_internal/compiler/samples/darttags/darttags: CompileTimeError
lib/js/dart2js/js_dart2js: CompileTimeError
lib/js/dartium/js_dartium: CompileTimeError
lib/svg/dart2js/svg_dart2js: CompileTimeError
lib/svg/dartium/svg_dartium: CompileTimeError
lib/typed_data/dart2js/native_typed_data_dart2js: CompileTimeError
lib/typed_data/dart2js/typed_data_dart2js: CompileTimeError
lib/web_audio/dart2js/web_audio_dart2js: CompileTimeError
lib/web_audio/dartium/web_audio_dartium: CompileTimeError
lib/web_gl/dart2js/web_gl_dart2js: CompileTimeError
lib/web_gl/dartium/web_gl_dartium: CompileTimeError
lib/web_sql/dart2js/web_sql_dart2js: CompileTimeError
lib/web_sql/dartium/web_sql_dartium: CompileTimeError

**Comment by kevmoo** [comment]
Closing out as very stale!
