### ISSUE TITLE
js_helper declares a class that appears to be abstract, but then instantiates it

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#16566]
Error caught by the dart analyzer: 

ERROR|STATIC_WARNING|FUNCTION_WITHOUT_CALL|/Users/efortuna/dart-git2/dart/sdk/lib/_internal/lib/js_helper.dart|2127|7|14|Concrete classes that implement Function must implement the method call()
ERROR|STATIC_WARNING|FUNCTION_WITHOUT_CALL|/Users/efortuna/dart-git2/dart/sdk/lib/_internal/lib/js_helper.dart|2132|7|12|Concrete classes that implement Function must implement the method call()

Basically we have a class defined like so:
class TearOffClosure extends Closure {
}

that doesn't define call(). However, if you mark it as abstract, you find that there are other spots in the code where we are instantiating TearOffClosure objects (?). I'm not tremendously familiar with the JShelper code, so I'm hoping someone more familiar with that corner of the codebase can tell me what the best fix is.  (sra?)

filing for now under dart2js, even though the problem is the intersetion of dart2js, dart:html, and the analyzer.

**Comment by joshualitt** [comment]
Closing because this bug is not fixable currently.
