### ISSUE TITLE
dartanalyzer doesn't allow dart:html to implement key types for interceptors

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#16563]
Over the course of fixing compile time errors on the analyzer, there are a number of errors like this:

ERROR|COMPILE_TIME_ERROR|IMPLEMENTS_DISALLOWED_CLASS|/Users/efortuna/dart-git2/dart/sdk/lib/_internal/lib/interceptors.dart|292|45|4|Classes cannot implement 'bool'
ERROR|COMPILE_TIME_ERROR|IMPLEMENTS_DISALLOWED_CLASS|/Users/efortuna/dart-git2/dart/sdk/lib/_internal/lib/js_number.dart|321|41|3|Classes cannot implement 'int'
etc.

The use of interceptors is central to the implementation of dart:html, so I don't know how you'd like to proceed in this case -- give a special exception for dart:html in these cases? Modify Interceptor somehow? If we don't filter out these errors, there's no way dart:html can ever be compile-time-error free.

**Comment by munificent** [comment]
Two years later, I'm guessing this isn't a problem anymore...
