### ISSUE TITLE
Evaluate constant functions at compile time

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#16598]
[ed note: I'm just passing these along as I see them]

**[user feedback]**

Dart2Js generates code like this:

&nbsp;t2 = C.JSNumber_methods.toInt$0(Math.floor(7.111111111111111));

7.1... is a result of a devision of constants that Dart2Js calculated at build time, nice! But it could also call calculate Math.floor(7.1) at runtime, as it is also constant at build time.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_02_04 (2014-01-31)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 0

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 710 / 203 MB
thread count: 28
index: 559303 relationships in 108843 keys in 15485 sources

SDK installed: true
Dartium installed: true

**Comment by rakudrama** [comment]
I don't see many of these but I have recently seen:

          t1 = Math.pow(2, 52);

              t1._multiplierDigits = C.JSDouble_methods.round$0(Math.log(100) / 2.302585092994046);
