### ISSUE TITLE
Minification could benefit from compact initialization

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#16601]
**[user feedback]**

Dart2Js outputs a section of this form (if I understand is correct, it for type checks using the is keyword):

P.XkM.$isa=true
P.L8.$isL8=true
// 500 more lines...
P.L8.$isa=true

It about 7kb big atm, writing it as one expression would save some kb:

P.XkM.$isa=P.L8.$isL8=P.L8.$isL8=true
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_02_04 (2014-01-31)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 0

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 752 / 499 MB
thread count: 28
index: 723264 relationships in 140040 keys in 17517 sources

SDK installed: true
Dartium installed: true

**Comment by rakudrama** [comment]
Rewriting multiple assignments as one expression is something we could do.
This also occurs in the initializers for top level and static variables.

There is almost no benefit after gzip.
