### ISSUE TITLE
Unexpected function type

### ISSUE THREAD

**Issue by markhats** [dart-lang/sdk#16629]
I'm getting an &quot;Unexpected function type&quot; when running my app built to JS. The error from the console is given below and I have also attached two screenshots, one of the Call Stack and another of the variable values when at a breakpoint on the error.

Bug or something I'm doing wrong?

Uncaught Error: RuntimeError: Unexpected function type autograph.html_bootstrap.dart.js:43958
Stack Trace: 
Error
&nbsp;&nbsp;&nbsp;&nbsp;at dart.wrapException (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:3328:15)
&nbsp;&nbsp;&nbsp;&nbsp;at ReflectionInfo.computeFunctionRti$1 (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:4481:17)
&nbsp;&nbsp;&nbsp;&nbsp;at JsMethodMirror.get$metadata (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:25454:57)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._maybeInvoke (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:50058:40)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._loadLibrary (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:50037:9)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._loadLibraries (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:49948:11)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._initPolymerOptimized (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:49936:7)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.initPolymer (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:49930:7)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.main (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:5529:7)
&nbsp;&nbsp;&nbsp;&nbsp;at main0 (file:///C:/Users/Mark/Documents/GitHub/Autograph-Web-Version/Autograph/build%20(non-minified)/web/autograph.html_bootstrap.dart.js:5448:7)

---

**Attachments:**
[CallStack.PNG](https://storage.googleapis.com/google-code-attachments/dart/issue-16629/comment-0/CallStack.PNG) (62.33 KB)
[Variables.PNG](https://storage.googleapis.com/google-code-attachments/dart/issue-16629/comment-0/Variables.PNG) (58.91 KB)

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
