### ISSUE TITLE
jsshell testing doesn't work on Windows

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#16627]
jsshell testing doesn't work on Windows:

d:\dart-repo\dart&gt;python tools/test.py -mrelease -cdart2js -rjsshell --use-sdk --write-debug-log --write-test-outcome-log -t60 lib/mirrors/mirrors_reader_test
Test configuration: dart2js_jsshell_release_ia32
Process error:
&nbsp;&nbsp;Command: \d:\dart-repo\dart\tools\testing\bin\jsshell.bat d:/dart-repo/dart/build/ReleaseIA32/generated_compilations/dart2js-sdk/tests_lib_mirrors_mirrors_reader_test/out.js
&nbsp;&nbsp;Error: ProcessException: The system cannot find the file specified.

&nbsp;&nbsp;Command: \d:\dart-repo\dart\tools\testing\bin\jsshell.bat d:/dart-repo/dart/build/ReleaseIA32/generated_compilations/dart2js-sdk/tests_lib_mirrors_mirrors_reader_test/out.js

Note that

&nbsp;&nbsp;Command: \d:\dart-repo\dart\tools\testing\bin\jsshell.bat d:/dart-repo/dart/build/ReleaseIA32/generated_compilations/dart2js-sdk/tests_lib_mirrors_mirrors_reader_test/out.js

should have been

&nbsp;&nbsp;Command: d:\dart-repo\dart\tools\testing\bin\jsshell.bat d:/dart-repo/dart/build/ReleaseIA32/generated_compilations/dart2js-sdk/tests_lib_mirrors_mirrors_reader_test/out.js

That is without the prefixed '/'.

**Comment by athomas** [comment]
jsshell is no longer a supported configuration.
