### ISSUE TITLE
docgen does not provide a version flag

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#16718]
Generally, all our tools are able to output the version of the sdk which they belong to (and some, like dart2js, will also give this if the tool crashes)

We should add a --version flag to docgen to be compliant

**Comment by sethladd** [comment]
Thanks for the report. However, we don't plan to address this issue with dartdocgen. New dartdoc tool coming online: https://github.com/dart-lang/dartdoc

(the new dartdoc has a --version flag)
