### ISSUE TITLE
vm-observatory: (cpu) link goes to blank page - compile error?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#16750]
1.2.0-edge. r32524

See screen shot
______
**Attachment:**
[Screen Shot 2014-02-11 at 5.34.12 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-16750/comment-0/Screen Shot 2014-02-11 at 5.34.12 PM.png) (205.53 KB)

**Comment by rmacnak-google** [comment]
Stale.
