### ISSUE TITLE
Add a hint to identify unused variables

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#16812]
There should be a hint that would identify unused variables. The following are some examples:

import 'dart:html';
int myint1;//Not Used
int myint2=0;//Not Used
void main() {
&nbsp;&nbsp;&nbsp;&nbsp;int myint3=0;//Not Used
&nbsp;&nbsp;&nbsp;&nbsp;int myint4;//Not Used
&nbsp;&nbsp;&nbsp;&nbsp;String myStr;//Not Used
}

**Comment by srawlins** [comment]
This hint exists. Close?
