### ISSUE TITLE
CPA type inference infers dynamic for (expression == null) and (null == expression)

### ISSUE THREAD

**Issue by polux** [dart-lang/sdk#16825]
For expression of the form (expression == null) and (null == expression), the CPA type inference infers null instead of bool for =='s selector. 

Reason: SimpleTypeInferrerVisitor.visitDynamicSend never calls handleDynamicSend when one of the two arguments of == is the literal 'null'. Because of that, getSendReturnType is never called and I never call augmentInferredSelectorType.

Example where it leads to wrong output:

class A {
&nbsp;&nbsp;operator ==(x) =&gt; &quot;a&quot;;
}

main() {
&nbsp;&nbsp;new A() == 1;
&nbsp;&nbsp;1 == null;
}

Inferred selector type for default inference is Union of [[exact=JSString], [exact=JSBool]] 
Inferred selector type for CPA inference is [exact=JSString]
Intersection is [exact=JSString]

**Comment by rakudrama** [comment]
Obsolete; we removed CPA.
