### ISSUE TITLE
Odd error when comparing consts

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#16839]
const num INFO = 100;
const num WARN = 200;

const num FOO_LEVEL = const int.fromEnvironment('foo_level', defaultValue: WARN);

class Foo {
&nbsp;&nbsp;static const bool info = (FOO_LEVEL &lt;= INFO);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^
}

Leads to: An expression of type 'num' was expected

**Comment by mhausner** [comment]
This is no longer an issue.
