### ISSUE TITLE
Safari does not throw a NSM error on `null` when used through reflection

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#16831]
The following snippet from mirrors/null_test fails on Safari:

&nbsp;&nbsp;Expect.throws(() =&gt; nullMirror.invoke(#notDefined, []),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(e) =&gt; e is NoSuchMethodError,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'noSuchMethod');

Error message:
Exception: Expect.throws(noSuchMethod): Unexpected 'Error: 'null' is not an object (evaluating 'receiver[$name]')'

It probably throws, but not the right error.

**Comment by sigmundch** [comment]
this is now fixed in the latest safari.
