### ISSUE TITLE
dart2js: Allow new String.fromEnvironment('foo')

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#16846]
main() {
&nbsp;&nbsp;print(new String.fromEnvironment('hi'));
}

generates:

&nbsp;&nbsp;main: function() {
&nbsp;&nbsp;&nbsp;&nbsp;H.throwExpression(P.UnsupportedError$(&quot;String.fromEnvironment can only be used as a const constructor&quot;));
&nbsp;&nbsp;}

The VM does not have this restriction.

It is not always possible to contrive that String.fromEnvironment has a constant argument.
For example, https://code.google.com/p/dart/issues/detail?id=15593 would require the construction of the environment variable from the containing group.  This is not possible with 'const' since the parameters of a const constructor are not constants.

**Comment by srawlins** [comment]
@vsmenon can this be closed as of const-update-2018? String.fromEnvironment can only be const now, right?

**Comment by vsmenon** [comment]
Yes.
