### ISSUE TITLE
error in VariableMirror.type for a retained field whose type is a non-retained type argument

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#16925]
This seems like a bug in dart2js's implementation of mirrors.

Using VariableMirror.type seems to fail if I try to read the type of a field (which was retained using @­MirrorsUsed), whose type is a type-argument, and the type-argument was not retained. 

Consider the following example:

&nbsp;&nbsp;&nbsp;&nbsp;@­MirrorsUsed(metaTargets: const [_Retain])
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:mirrors';
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;class _Retain { const _Retain(); }
&nbsp;&nbsp;&nbsp;&nbsp;const retain = const _Retain();
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;class B {}

&nbsp;&nbsp;&nbsp;&nbsp;class A&lt;T&gt; {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@­retain T value = null;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var decl = reflectClass(new A().runtimeType).declarations[#value];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(decl.type);
&nbsp;&nbsp;&nbsp;&nbsp;}

This yields an exception if run with dart2js:

&nbsp;&nbsp;Caught Illegal argument(s): Type variable not present in list.

However:
&nbsp;\- if I retain T, for example by using `targets:const [A]`, I get the correct result &quot;TypeVariableMirror on 'T'&quot;
&nbsp;\- if I replace T for B, I get a reasonable result too (&quot;TypeMirror on 'dynamic'&quot;). Note that B is not retained by mirrors-used, but that it's not a type-arg.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
