### ISSUE TITLE
Consolidate the different versions of TEMP_FAILURE_RETRY_BLOCK_SIGNALS

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#16927]
We have both TEMP_FAILURE_RETRY_BLOCK_SIGNALS and TEMP_FAILURE_RETRY in our sources. In the presence of the profiler we should not ever use TEMP_FAILURE_RETRY as it has the potential of spinning without making any forward progress.

**Comment by johnmccutchan** [comment]
I believe this is fixed.
