### ISSUE TITLE
Provide a canonical way to find the Dart SDK root

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#16994]
In the development of pub transformers which resolve Dart source code, in order to resolve all of the code the Analyzer needs a path to the Dart SDK filter (in order to find the sources for dart: source code).

Unfortunately there does not seem to be a good way to find the SDK folder for the current Dart executable. I do have a user-configurable path, but this falls down when the code is used in unit-tests, transformers and other portable locations (location of SDK can differ across machines and test configurations).

Additional consideration- it might be good to look at something like .NET's reference assemblies which has a fixed root folder containing all versions installed, providing a structured environment for side-by-side installation of runtimes.

**Comment by sgjesse** [comment]
After a number of different changes we have decided the following:

*  `Platform.executable` will not change from its original behaviour
* A new getter `Platform.resolvedExecutable` is added. This returns the absolute path, without any symlinks, to the actual executable as resolved by the OS.

This landed on master, https://github.com/dart-lang/sdk/commit/c05c8c66069db91cc2fd48691dfc406c818d411d, and will go into 1.11, where is now in 1.11.0-dev.5.3, https://github.com/dart-lang/sdk/commit/c0e90cb984a423287c0cbcab5dea15c987332f07.

**Comment by sethladd** [comment]
Thanks for the update!
