### ISSUE TITLE
Missing feature detection for glibc calls

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#17002]
eventhandler_linux.cc uses sys/timerfd.h which wasn't added until glibc 2.8, and file_system_watcher_linux.cc uses inotify_init1, which wasn't added until glibc 2.9. Before using these features, features.h should be #included. Then you can check the preprocessor defines __GLIBC__ and __GLIBC_MINOR__. The code already in the _android.cc implementations should be safe.

This is needed when building for host during an Android build using the toolchain included in the AOSP tree (e.g. for snapshot generation), which uses glibc 2.7 headers.

**Comment by mraleph** [comment]
@zanderso is this something we are looking at? maybe we should close this issue.

**Comment by zanderso** [comment]
I think this is stale.
