### ISSUE TITLE
Tool to catch iterating a map, but not keys or values

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#17026]
Something I wish the analyzer warned about is when I mistakenly try to iterate over a map directly rather than iterate over its keys or values...

For example:
Map&lt;String, dynamic&gt; propTypeMap = {};
for(String prop in propTypeMap) {
...
}
compiles then crashes when run.  I make this mistake more than I care to admit... I guess because it looks natural it first glance.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_05_11 (2014-02-19)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_25
# projects: 14
# open dart files: 4
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1428 / 853 MB
thread count: 27
index: 1585157 relationships in 239183 keys in 3599 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
There is now a new warning for this:

> warning: The type 'Map<String, dynamic>' used in the 'for' loop must implement Iterable
