### ISSUE TITLE
Generate dartdoc comments based on method signature

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#17078]
Here at Dart Flight School in SF.  I would love to have the ability to automatically generate and update class and method comments like I can do in Eclipse.

/**
&nbsp;* This is method
&nbsp;*
&nbsp;* @­param theArg, the argument (duh!)
&nbsp;* @­return theArg
*/
public int funkyFunc(final int theArg) {
&nbsp;&nbsp;return theArg;
}

Ed Murphy
emurphy@conceptuamat.com
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_05_12 (2014-02-20)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_51
# projects: 4
# open dart files: 1

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 770 / 66 MB
thread count: 30
index: 531378 relationships in 110683 keys in 590 sources

SDK installed: true
Dartium installed: true

**Comment by natebosch** [comment]
The dartdoc tool will already include parameter and return type information in the generated output - we don't need to repeat them in the doc comment.
https://www.dartlang.org/guides/language/effective-dart/documentation#do-use-prose-to-explain-parameters-return-values-and-exceptions
