### ISSUE TITLE
Don't ship dartium with symbols on our release channels

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#17105]
The current version of dartium that we ship has a ton of symbols in them. We should utilize the gyp variables that enables us to get the symbols stripped (and dumped to a file) from the dartium target for all release builds that we ship on dev and stable. That way we still have the symbols available if we get a dump and without having ton of symbols shipped to users (I see a 70 meg reduction on the mac dartium size, 30 on linux if I just strip them using strip).

Questions:
Is there some (good) reason why we have not already done this?
Do we want to keep the symbols on the bleeding edge builders (I say we do, the stacks we get there are good indication when something goes wrong)

Vijay: I am tentatively assigning this to you, but feel free to pass this along or reasign back to me

**Comment by athomas** [comment]
Not shipping dartium anymore.
