### ISSUE TITLE
No-op code warning from analyzer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#17111]
Just messing around and hit a bug in my test app that was effectively:

&nbsp;&nbsp;foo + bar;

instead of: 

&nbsp;&nbsp;foo += bar;

Oops. 

C# would warn about this sort of dead code, should Dart? Just thinking about the recent Apple security issue with their &quot;goto fail&quot; bug.

**Comment by srawlins** [comment]
Dup of #11625?

**Comment by kevmoo** [comment]
Yup!
