### ISSUE TITLE
Use canonical fields for closure function and context

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#17160]
Context of the discussion:
https://codereview.chromium.org/178233003/diff/70001/runtime/vm/flow_graph_builder.cc#newcode2287

We should allocate the fields for the closure function and context once at VM or isolate startup. They should be part of the \_FunctionImpl class.

**Comment by rmacnak-google** [comment]
Stale. All closures are now instances of a single class, instead of the old class per signature per library.
