### ISSUE TITLE
Pub upgrade did not trigger analysis

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#17179]
Username: kasperl

I just ran 'pub upgrade' on a project which updated one of my dependencies. Then I started the project in Dartium, but unfortunately a constructor had changed so Dartium stopped with a NSM error. However, I didn't get any static warning in the editor before I chose 'Reanalyze sources'.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_05_15 (2014-02-24)
OS: Mac OS X - x86_64 (10.9.2)
JVM: 1.6.0_65

# projects: 1
# open dart files: 1
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1996 / 266 / 162 MB
thread count: 31
index: 235202 relationships in 50083 keys in 260 sources

SDK installed: true
Dartium installed: true

**Comment by bwilkerson** [comment]
Cannot reproduce; assumed stale.
