### ISSUE TITLE
Field::PrintToJSONStream tries to get class from abstract type (UNREACHABLE)

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#17254]
The vm service should be more careful when printing the type of a field.  We need to decide if returning a class for a field is appropriate in the first place.

\* thread #­2: tid = 0x2709a0, 0x92acb952 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGABRT
&nbsp;&nbsp;&nbsp;&nbsp;frame #­0: 0x92acb952 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill + 10:
-&gt; 0x92acb952:  jae    0x92acb962                ; \__pthread_kill + 26
&nbsp;&nbsp;&nbsp;0x92acb954:  calll  0x92acb959                ; \__pthread_kill + 17
&nbsp;&nbsp;&nbsp;0x92acb959:  popl   %edx
&nbsp;&nbsp;&nbsp;0x92acb95a:  movl   230807239(%edx), %edx
(lldb) bt
\* thread #­2: tid = 0x2709a0, 0x92acb952 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGABRT
&nbsp;&nbsp;&nbsp;&nbsp;frame #­0: 0x92acb952 libsystem_kernel.dylib`__pthread_kill + 10
&nbsp;&nbsp;&nbsp;&nbsp;frame #­1: 0x964c8167 libsystem_pthread.dylib`pthread_kill + 101
&nbsp;&nbsp;&nbsp;&nbsp;frame #­2: 0x92d3629c libsystem_c.dylib`abort + 155
&nbsp;&nbsp;&nbsp;&nbsp;frame #­3: 0x000551d5 dart`dart::DynamicAssertionHelper::Fail(this=&lt;unavailable&gt;, format=&lt;unavailable&gt;) + 917 at assert.cc:40
&nbsp;&nbsp;&nbsp;&nbsp;frame #­4: 0x0033ed73 dart`dart::AbstractType::type_class(this=0xb0182b98) const + 67 at object.cc:12168
&nbsp;&nbsp;&nbsp;&nbsp;frame #­5: 0x002fc631 dart`dart::Field::PrintToJSONStream(this=&lt;unavailable&gt;, stream=0xb01824d0, ref=&lt;unavailable&gt;) const + 1441 at object.cc:6391
&nbsp;&nbsp;&nbsp;&nbsp;frame #­6: 0x002bc40c dart`dart::JSONStream::PrintProperty(char const\*, dart::Object const&amp;, bool) [inlined] dart::JSONStream::PrintValue(this=0xb01824d0, o=&lt;unavailable&gt;) + 108 at json_stream.cc:226
&nbsp;&nbsp;&nbsp;&nbsp;frame #­7: 0x002bc3b9 dart`dart::JSONStream::PrintProperty(this=0xb01824d0, name=0x006680f3, o=&lt;unavailable&gt;, ref=&lt;unavailable&gt;) + 25 at json_stream.cc:306
&nbsp;&nbsp;&nbsp;&nbsp;frame #­8: 0x0033ec10 dart`dart::Instance::PrintToJSONStream(dart::JSONStream\*, bool) const [inlined] dart::JSONObject::AddProperty(this=0xb01824d0, ref=true, name=0x006680f3) const + 2112 at json_stream.h:143
&nbsp;&nbsp;&nbsp;&nbsp;frame #­9: 0x0033ebf2 dart`dart::Instance::PrintToJSONStream(this=0x00000100, stream=0xb01824d0, ref=true) const + 2082 at object.cc:12141
&nbsp;&nbsp;&nbsp;&nbsp;frame #­10: 0x00404cd5 dart`dart::HandleObjects(isolate=&lt;unavailable&gt;, js=&lt;unavailable&gt;) + 885 at service.cc:934
&nbsp;&nbsp;&nbsp;&nbsp;frame #­11: 0x004029ad dart`dart::Service::HandleIsolateMessage(isolate=&lt;unavailable&gt;, msg=&lt;unavailable&gt;) + 1613 at service.cc:583
&nbsp;&nbsp;&nbsp;&nbsp;frame #­12: 0x002b4a4b dart`dart::IsolateMessageHandler::HandleMessage(this=&lt;unavailable&gt;, message=0x07d57c40) + 1323 at isolate.cc:151
&nbsp;&nbsp;&nbsp;&nbsp;frame #­13: 0x002bee5b dart`dart::MessageHandler::HandleMessages(this=0x00d61e20, allow_normal_messages=&lt;unavailable&gt;, allow_multiple_normal_messages=&lt;unavailable&gt;) + 187 at message_handler.cc:153
&nbsp;&nbsp;&nbsp;&nbsp;frame #­14: 0x002bf014 dart`dart::MessageHandler::HandleOOBMessages(this=0x00d61e20) + 68 at message_handler.cc:187
&nbsp;&nbsp;&nbsp;&nbsp;frame #­15: 0x00160958 dart`dart::DRT_StackOverflow(dart::NativeArguments) [inlined] dart::NativeArguments::isolate(arguments=NativeArguments at 0xb0183a60, this=0x0095f548, this=0x0095f548, this=&lt;unavailable&gt;, isolate=0x01069200, isolate=0x01069200) const + 261 at code_generator.cc:1157
&nbsp;&nbsp;&nbsp;&nbsp;frame #­16: 0x00160853 dart`dart::DRT_StackOverflow(arguments=NativeArguments at 0xb0183b60) + 515 at code_generator.cc:1131
&nbsp;&nbsp;&nbsp;&nbsp;frame #­17: 0x00c4906c
&nbsp;&nbsp;&nbsp;&nbsp;frame #­18: 0x16d65817

**Comment by mraleph** [comment]
Seems stale.
