### ISSUE TITLE
[next] window.performance.getEntries() returns a List of null entries

### ISSUE THREAD

**Issue by alxhub** [dart-lang/sdk#17250]
**What steps will reproduce the problem?**

Call window.performance.getEntries()

**What is the expected output? What do you see instead?**

It should return a List&lt;PerformanceEntry&gt; with appropriate records.

Instead, it returns a List with the correct number of values, but they're all null.

**Comment by donny-dont** [comment]
@alan-knight I'm still seeing issues with this. This would be in 1.11.0-dev.5.2.

As a side question will the dart2js handle the case where its prefixed? Trying to run some stuff on a version of webkit where its webkitGetEntries.

**Comment by alan-knight** [comment]
I've been out for a couple of weeks, and still not back in the office, not sure if Terry's stuff has landed yet. @terrylucas 

Dart2js should in general handle the case of different prefixes. If it doesn't handle that specific case it should be just a matter of adding the variations to a list in the appropriate script.

**Comment by alan-knight** [comment]
Can you try a simple test to see if it works prefixed, and if it doesn't, make a separate bug for that?

**Comment by donny-dont** [comment]
@alan-knight should I write a test within the sdk and do a pull request?

**Comment by alan-knight** [comment]
That would be awesome. Assuming that the prefixed webkit version is in our test matrix.

**Comment by donny-dont** [comment]
It was failing in Chrome when compiled to JS.

**Comment by dustinlessard-wf** [comment]
This seems to also be an issue in Dart2.  The following code was tested in DartPad on Dart SDK 2.0.0

```dart
import 'dart:html';

void triggerLongTask(Duration duration) {
      final startTime = new DateTime.now();
      while (new DateTime.now().difference(startTime) < duration) {}
    }

void main() {
  triggerLongTask(new Duration(seconds:2));
  List<PerformanceEntry> entries = window.performance.getEntries();
  for(var entry in entries){
    if(entry == null){
      print('entry is null');
    }
    else{
      print(entry.entryType);
    }
  }
}

```
