### ISSUE TITLE
Create Encoder/Decoder for reflection data and let them share data structures between compiler and runtime.

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#17283]
Currently, the encoding and decoding are written in a different style and it is hard to tell if they actually implement the same thing or to extend the encoding with new information.

**Comment by mit-mit** [comment]
Deprecating 'Mirrors' label which had only this single usage

**Comment by floitschG** [comment]
To give an update: I did work in that direction but didn't get to refactor the mirrors completely. They are better now, but still not perfect.

**Comment by bkonyi** [comment]
Closing as `dart:mirrors` is no longer supported for web.
