### ISSUE TITLE
Report better error message when calling a closure with wrong (number of) arguments.

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#17280]
We should tell the user that this is about a closure call and that the argument number/names may be the source of the problem.
Currently we only say that 'call$n' cannot be found.

**Comment by srawlins** [comment]
Given this code:

```dart
void main() {
  var c1 = (a, b) => print('$a$b');

  c1(2);
}
```

dart2js shows the following error at runtime:

```
Error compiling to JavaScript:
main.dart:4:5:
Error: Too few positional arguments: 2 required, 1 given.

Error: Compilation failed.
```

Looks pretty good!
