### ISSUE TITLE
Cannot access Annotation from ElementAnnotation

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#17307]
We have a number of code gen scenarios where we need to access the parameters passed to the annotation, it's currently a pain to do this when dealing with elements (have to get the index of the annotation, go up to the element, get the node, then get the annotation by that index).

Would be great if the Annotation AST node was exposed from ElementAnnotation.

**Comment by sigurdm** [comment]
Are there any updates on this?

**Comment by bwilkerson** [comment]
I'm closing this as stale. Please re-open if this is still an issue.
