### ISSUE TITLE
Provide dart2js API to disable generating source maps

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#17403]
Dart2js internally has a flag used to control whether or not source maps or generated, but the public API does not expose this. In pub, I don't want to generate source maps in a release build since that build doesn't include the source .dart code that the source map would point to.

I have a workaround, so it's not at all blocking, but it would be nice to not do the work to generate the source map if pub isn't going to write it.

**Comment by sigmundch** [comment]
I believe the `--no-source-maps` flag is now exposed, but let me know if not.
