### ISSUE TITLE
Optimization suggestion 3

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#17435]
**[user feedback]**

Code generated by dart2js in debug mode. Looks like some lines are generated twice or even three times?

J.JSInt.$isint = true;
J.JSInt.$isnum = true;
J.JSInt.$isComparable = true;
J.JSInt.$asComparable = [J.JSNumber];
J.JSInt.$isComparable = true;
J.JSInt.$asComparable = [J.JSNumber];
J.JSInt.$isComparable = true;
J.JSInt.$asComparable = [J.JSNumber];
J.JSInt.$isObject = true;
...
J.JSDouble.$isdouble = true;
J.JSDouble.$isnum = true;
J.JSDouble.$isComparable = true;
J.JSDouble.$asComparable = [J.JSNumber];
J.JSDouble.$isComparable = true;
J.JSDouble.$asComparable = [J.JSNumber];
...
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.3.0.dev_03_02 (2014-03-10)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_45
# projects: 2
# open dart files: 0
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 730 / 565 MB
thread count: 29
index: 152110 relationships in 31414 keys in 138 sources

SDK installed: true
Dartium installed: true

**Comment by rakudrama** [comment]
Obsolete. We no longer generate this block.
