### ISSUE TITLE
Triage MIPS test failures

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#17440]
I have updated the test status files with the new MIPS failures (and some new passes) on the new build slaves.  There are failures in the co19, vm, and standalone suites.

The failures should be investigated, and individual bugs filed.

The skipping of co19 List tests is due to the fact that they allocate 300 MB of memory, and the buildslaves have 1 GB RAM and no swap space.

**Comment by rmacnak-google** [comment]
MIPS is no longer supported.
