### ISSUE TITLE
D8 detection doesn't work on Windows

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#17458]
D8 is detecting using the 'os' object and its 'system' property. The 'os' object is not defined in D8 on Windows.

**Comment by sigurdm** [comment]
The V8 team has suggested us to write a patch: https://code.google.com/p/v8/issues/detail?id=4096
(/cc @whesse)

**Comment by yangguo-chromium** [comment]
I'm planning to remove the 'os' object altogether. It's not used in V8 anywhere aside from one test, and is not maintained. Is this bug still up-to-date? Can you elaborate on what you mean with "d8 detection"? If you want to check whether the shell is d8, there are other ways. For example by checking and then calling the function 'version'.

**Comment by sigurdm** [comment]
We at least use os for setting up a fake self.location when running tests in d8.
https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/preambles/d8.js#L33

This is needed to load files located relative to the currently running script.

**Comment by johnniwinther** [comment]
The d8 detection is no longer need for deferred tests. `currentScript` is now set up in the d8 preamble.
