### ISSUE TITLE
The reported number of methods retained due to mirror usage is too high

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#17457]
We calculate this number as #functions we have code for - #number of functions when the codegen queue is empty for the first time.

This means we include all methods that we generate after the queue closes as being due to mirrors.

We should either mark distinct phases in the codegen queue or explicitly count the methods we include for mirror usage.

**Comment by bkonyi** [comment]
Since `dart:mirrors` is no longer supported on web, I'll assume this issue isn't relevant anymore.
