### ISSUE TITLE
Expose ability to generate cryptographically secure pseudo-random numbers

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#1746]
Either fix or document this.

**Comment by whesse** [comment]
There is no longer a dart:crypto library.  It has been moved to package:crypto.
A secure RNG should be provided by the embedder, so it should be made available in
dart:io for the standalone Dart executable, and in dart:html for the browser.
Dart:html already supports it in Crypto.getRandomValues, so this is now just a dart:io issue.

Labelling this issue as dart:io, and merging duplicate issues with it.
Duplicate issues, or blocked issues, are #15993 and #15064

**Comment by sethladd** [comment]
cc @crelier

**Comment by iposva-google** [comment]
Discussion I had with @sgjesse and @lrhn was that the VM team will take ownership of this one and expose it as "sec = new Random.secure();" or similar.
The general idea being that you start relying on the embedder (e.g. standalone VM, browser) to provide a secure random number source.

**Comment by sethladd** [comment]
Greatness. Thanks @crelier !

**Comment by sethladd** [comment]
Actually, @crelier would you might submitting a quick patch to CHANGELOG.md indicating this new API landed? Thanks!
