### ISSUE TITLE
Security: Make isolates resilient in the face of malformed messages

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#1747]
If an attacker is able to specify the raw stream of a serialized message (e.g. when a receive port is bound to a tcp port) and the message is read in Snapshot::SetupFromMemory, security problems can occur:
Missing check for length
Potentially missing checks for type (kind) of message (should be restricted to kMessage)

Once first security checks are implemented, the functionality should be fuzzed
If a malformed message is detected, the message potentially can be dropped

Reviewer also suggests this...

Snapshots should be redesigned so that code (type code) and data (type message) are treated differently

...but I'm not sure that this is an issue for us.

**Comment by mraleph** [comment]
It does not seem like we are planning anything in this area. @a-siva please reopen if you think we would work on this.
