### ISSUE TITLE
Security: Prevent DoS from hashmap collisions

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#1748]
DoS using hashmap collisions
dart/runtime/vm/object.cc
6156     hash_ += ch;
6157     hash_ += hash_ &lt;&lt; 10;
6158     hash_ ^= hash_ &gt;&gt; 6;
hash(attacker-supplied data) can be predicted
if hashmap is used on attacker-supplied keys, attacker can cause O(n^2) operations on the hashmap
background: http://www.youtube.com/watch?v=R2Cq3CLI6H8
solution: follow-up with Erik / apply same counter measures as V8

**Comment by gnprice** [comment]
This appears to be an umbrella issue for two issues that are now closed (/cc @lrhn who just closed #19399). Should this one also be closed?

**Comment by lrhn** [comment]
Yup.
