### ISSUE TITLE
Poor code quality of window.console.dir

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17508]
onSelect(Event e) {
&nbsp;&nbsp;window.console.dir(e);
}

Compiles to:

&nbsp;&nbsp;function(e) {
&nbsp;&nbsp;&nbsp;&nbsp;window;
&nbsp;&nbsp;&nbsp;&nbsp;$.get$Console__safeConsole().toString;
&nbsp;&nbsp;&nbsp;&nbsp;if (typeof console != &quot;undefined&quot;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.debug(e);
&nbsp;&nbsp;}

This is code is pretty awful compared to what I would have written myself:

&nbsp;&nbsp;function(e) {
&nbsp;&nbsp;&nbsp;&nbsp;!!self.console &amp;&amp; self.console.dir(e)
&nbsp;&nbsp;}

I'm also puzzled why console.debug is used. But perhaps console.debug and console.dir are the same. If so, dir is shorter.

**Comment by joshualitt** [comment]
Part of this issue has been fixed, but at this point it seems unlikely we'll have a chance to revisit. We can reopen this issue if it causes problems down the road.
