### ISSUE TITLE
IsolateSpawnException should expose more metadata

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#17501]
Currently, IsolateSpawnException only exposes a [toString] method (which is poorly formatted -- see issue #12689). This makes it very difficult to report isolate errors, such as those from &quot;pub serve&quot;, in a user-friendly manner.

For an error caused by a library failing to load, it would be useful to have, in order of descending usefulness:

\* The URI of the library that failed to load.
* The URIs of libraries that transitively imported that library.
* The line and position of each of those import statements.
* Information about the HTTP or filesystem error that caused the library load to fail.

**Comment by kevmoo** [comment]
Er, blocking https://github.com/dart-lang/pub/issues/896

**Comment by lrhn** [comment]
This is not information that we can generally have. If dart2js fails to spawn an isolate, it's either because the JS files didn't exist or it had an error. 

I think each platform should have a best-effort approach to reporting the errors, but it's not something we can generally add as fields of a the error.

**Comment by nex3** [comment]
I'm fine if there are fields that are `null` in dart2js. But the VM at least has access to a bunch of information that we need, and the only way we're currently able to get it is by parsing strings, which means we get broken every so often when `IsolateSpawnException.toString()` changes.

**Comment by floitschG** [comment]
Reassigning to VM.

This kind of information would need to come from the VM/embedder.

**Comment by matanlurey** [comment]
https://github.com/dart-lang/pub/issues/896 is closed, so I assume we can close this.
