### ISSUE TITLE
Allow "void" as a generic type parameter.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#17518]
The void type is only allowed as a function return type. It is equivalent to &quot;Null&quot; except for documentation purposes (and allowing &quot;return;&quot; statements in the body).
The documentation meaning is that the function does not return a meaningful value, and its result shouldn't be used.

For Future, we have the same documentation need. Some Futures carry no meaningful value, they are effectively the delayed results of evaluating a void function.
It would improve documentation if these futures could be typed as &quot;Future&lt;void&gt;&quot;. By duality, it would be equivalent to &quot;Future&lt;Null&gt;&quot;, but documenting a different intent.

It's likely to also be useful in other places. Perhaps we should allow &quot;void&quot; everywhere we currently allow &quot;dynamic&quot;.

**Comment by munificent** [comment]
Duplicate of #27504. (Yes, this one is much older, but that one is linked to by more things.)
