### ISSUE TITLE
Unclear if Math's sin/cos/etc functions take radians or degrees

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#17515]
e.g. https://api.dartlang.org/apidocs/channels/stable/#dart-math@id_sin

I might have missed it, but it's not clear to me if I'm supposed to pass in radians or degrees.

**Comment by arocnies** [comment]
This is still an issue. At least this one didn't keep me up late debugging like the HTTPRequest.timeout value did.

I like the idea of changing the variable name to reflect the unit. Maybe even providing optional named arguments for both units, e.x. "cos(rad: x); cos(deg: x)"? These changes, or simply adding the unit in the doc, would be a great improvement in code clarity.

**Comment by floitschG** [comment]
Had to revert the CL because of an issue with compiling the VM. (There was a fingerprint on the function which was taking the name of the argument into account).

We will try again tomorrow.
