### ISSUE TITLE
Security: Avoid bad range check pattern

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#1752]
The following are two examples of code that uses a bad range check pattern:

- DART_EXPORT Dart_Handle Dart_ListGetAsBytes(Dart_Handle list,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;intptr_t offset,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t\* native_array,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;intptr_t length) {
&nbsp;&nbsp;Isolate\* isolate = Isolate::Current();
&nbsp;&nbsp;DARTSCOPE(isolate);
&nbsp;&nbsp;const Object&amp; obj = Object::Handle(Api::UnwrapHandle(list));
&nbsp;&nbsp;if (obj.IsArray()) {
&nbsp;&nbsp;&nbsp;&nbsp;Array&amp; array_obj = Array::Handle();
&nbsp;&nbsp;&nbsp;&nbsp;array_obj ^= obj.raw();
&nbsp;&nbsp;&nbsp;&nbsp;if ((offset + length) &lt;= array_obj.Length()) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Object&amp; element = Object::Handle();

- byte_array.cc:
&nbsp;&nbsp;static void RangeCheck(const ByteArray&amp; array, const Smi&amp; index,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;intptr_t num_bytes) {
&nbsp;&nbsp;if ((index.Value() &lt; 0) || ((index.Value() + num_bytes) &gt; array.Length())) {

**Comment by iposva-google** [comment]
// Perform a range check, checking if
  //    offset + count <= length
  // without the risk of integer overflow.
  static inline bool RangeCheck(intptr_t offset,
                                intptr_t count,
                                intptr_t length) {
    return offset >= 0 &&
           count >= 0 &&
           length >= 0 &&
           count <= (length - offset);
  }
