### ISSUE TITLE
VM doesn't optimize division by constant (except powers of 2).

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#17547]
Example code:

``` dart
f(x) => x ~/ 10;
```

generates optimized code:

```
0xebadc472    d1f8                   sar eax, 1
0xebadc474    d1fb                   sar ebx, 1
0xebadc476    99                     cdq
0xebadc477    f7fb                   idiv ebx
0xebadc479    3d00000040             cmp eax, 0x40000000
0xebadc47e    0f845c000000           jz 0xebadc4e0
0xebadc484    03c0                   add eax,eax
```

Two smi untags (one should be enough) and an idiv instead of an imul.
I assume the cmp is for detecting division by zero, which is also not necessary.

Apart from unnecessary overhead, you can also convert division to a multiplication with much better efficiency.

Better code could be (edx still reserved):

```
mov ebx, 0x66666667
sar eax, 1
imul ebx      ;; result in edx:eax
sar edx, 2
lea eax, edx + edx
```

**Comment by lrhn** [comment]
Code is now:
```
0000000004177CC0    48c7c114000000         movq rcx,0x14
...
0000000004177CFC    48d1f8                 sarq rax,1
0000000004177CFF    48d1f9                 sarq rcx,1
0000000004177D02    4899                   cdqq
0000000004177D04    48f7f9                 idivq rcx
0000000004177D07    4d8b9f17000000         movq r11,[r15+0x17]
0000000004177D0E    493bc3                 cmpq rax,r11
0000000004177D11    0f841f000000           jz 0x4177d36
0000000004177D17    4803c0                 addq rax,rax
```
It's about the same as when originally filed. This is a division by a constant different from -1, it shouldn't need the compare. It also shouldn't need to smi-untag the constant. Or the operand for that matter, keep it multiplied by two and clear the tag bit afterwards. 
```
movq rcx, 0x0a
cddq
idivq rcx
andq rax, -2
```

And also, if the modulo isn't needed (I know you do div/mod combining), division by constants can be optimized.

**Comment by aam** [comment]
For negative numbers doesn't the proposed code in original report produces results that are off by 1?
-1 ~/ 10 results in -1, while expected is 0?

**Comment by rmacnak-google** [comment]
d1c9a2b06fe4c7bd2cd85036d6f3a6109d1ec6b9, 13ba681398dff9bc474fadafc2b3f1d77203487f
