### ISSUE TITLE
Null character printed in diagnostics for last line

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17556]
Create a file without a newline at the end:

echo -n main &gt; test.dart

Compile it with dart2js, piping the output into od -c

dart2js test.dart | od -c

This produces the following output:

0000000    t   e   s   t   .   d   a   r   t   :   1   :   1   :  \n   I
0000020    n   t   e   r   n   a   l       E   r   r   o   r   :       e
0000040    x   p   e   c   t   e   d       a       d   e   c   l   a   r
0000060    a   t   i   o   n   ,       b   u   t       g   o   t       '
0000100    m   a   i   n   '  \n   m   a   i   n  \0  \n   ^   ^   ^   ^
0000120   \n  
0000121

Notice there is a \0 in the output.

I believe the cause of this problem is caused by this change to dart2js' API:

&nbsp;* It is recommended to return a UTF-8 encoded list of bytes because the scanner
&nbsp;* is more efficient in this case. In either case, the data structure is
&nbsp;* expected to hold a zero element at the last position. If this is not the
&nbsp;* case, the entire data structure is copied before scanning.

I suspect that this can be fixed by modifying sdk/lib/_internal/compiler/implementation/source_file.dart.

**Comment by joshualitt** [comment]
I'm not sure if this is still an issue, but we haven't had further reports of problems. Closing.
