### ISSUE TITLE
No visible change to indicate that observatory is working.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#17565]
When clicking on different links in the observatory nothing happens.
The site continues working normally, until (several seconds later) suddenly the page that I clicked on appears.
This happens, for example, when asking for cpu and heap profiles.

**Comment by bkonyi** [comment]
Just took a look at this, and I don't seem to see any issues with pages not immediately loading. When navigating to the heap/cpu profiles it looks like there's loading bars now. Is this something that has been resolved since this issue was created @johnmccutchan?

**Comment by johnmccutchan** [comment]
@bkonyi Yes, this is a very old issue that should be closed.
