### ISSUE TITLE
Hard to click on observatory profiles

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#17563]
Version r33758

It's extremely hard to click on the heap profile (or any other non-cpu profile).

I click on the &quot;profile&quot; link on the root isolate.
This opens the cpu profile.
There I hover of the &quot;root isolate&quot; (&quot;Observatory &gt; root isolate &gt; cpu profile&quot; at the top).
This shows the heap profile as option. When I move the mouse down the pop-up disappears. After some trial-and-error I managed to click it, by either moving the mouse very fast, or by using an extension that allows me to click without moving the mouse.

Clicking the &quot;root isolate&quot; itself doesn't work and brings me back from where I started. (How would the hover work on mobile?)

Tested in Chrome (Dev, Aura) and Firefox.

**Comment by rmacnak-google** [comment]
Can't reproduce, assumed stale.
