### ISSUE TITLE
Memory usage in Observatory seems inconsistent

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#17581]
When looking at localhost:8181/#/isolates/ I see (for the root isolate): 2MB/117MB (map)

When I click on the link (leading to the allocation profile) I seem to have a much higher usage. In the &quot;Current column&quot;:
List: 201935616
CodeBufferMarker: 116115200
_LinkedHashMapEntry: 104358016
...

These 3 alone use up more than 400MB.

**Comment by rmacnak-google** [comment]
Stale.
