### ISSUE TITLE
dart2js doesn't recognize FileError

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17609]
LocalFileSystem doesn't work in incognito mode, and if you try to create a file system, a FileError is thrown.

dart2js doesn't recognize this and reports:

Uncaught Error: Instance of 'Interceptor'
Uncaught Instance of 'Interceptor'

Example program:

import 'dart:html';

main() {
&nbsp;&nbsp;window.requestFileSystem(1024*1024, persistent: true).then((fs) {
&nbsp;&nbsp;&nbsp;&nbsp;print(fs);
&nbsp;&nbsp;});
}

**Comment by joshualitt** [comment]
I'm not sure if this issues repros on TOT, but its been many years and we haven't had further reports of problems. I'm going to close this, but please reopen the issue if it is still causing problems.
