### ISSUE TITLE
Meta bug for new pkg/samples tests failing on IE10 - please triage

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#17607]
I will mark new ie10 only failures with this bug

**Comment by whesse** [comment]
Obsolete.  IE10 has been EOL for more than 1 year, and is no longer tested.

**Comment by ricowind** [comment]
"is no longer tested" :-)
https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-win8-ie10-be

If we remove that there are some other cleanup that we can do in status files:
git grep ie10 | grep status
pkg/pkg.status:[ $runtime == ie10 ]
tests/co19/co19-dart2js.status:LibTest/typed_data/Uint8ClampedList/Uint8ClampedList_A02_t01: Pass, fail # co19-roll r576: Passes on ie10. Please triage this failure
tests/co19/co19-dart2js.status:[ $compiler == dart2js && $runtime == ie10 ]
tests/corelib/corelib.status:[ $compiler == dart2js && $runtime == ie10 ]
tests/html/html.status:[$runtime == ie10 || $runtime == ie11]
tests/html/html.status:[$runtime == ie10 ]
tests/html/html.status:[ $runtime == ie10 ]

and in our test scripts 
git grep ie10 | grep "tools/testing"
tools/testing/dart/browser_controller.dart:    'ie10',
tools/testing/dart/browser_controller.dart:    'ie10'
tools/testing/dart/browser_controller.dart:    if ((browserName == 'ie10' || browserName == 'ie11') &&
tools/testing/dart/runtime_configuration.dart:      case 'ie10':
tools/testing/dart/status_reporter.dart:    'runtimes': ['chrome', 'ff', 'ie11', 'ie10'],
tools/testing/dart/test_configurations.dart:      // NOTE: We've experienced random timeouts of tests on ie9/ie10. The
tools/testing/dart/test_options.dart:         safari, ie9, ie10, ie11, firefox, opera, chromeOnAndroid,
tools/testing/dart/test_options.dart:    [ff | chrome | safari | ie9 | ie10 | ie11 | opera | chromeOnAndroid]:
tools/testing/dart/test_options.dart:            'ie10',
tools/testing/dart/test_options.dart:          'ie10',
tools/testing/dart/test_suite.dart:      'ie10',
tools/testing/dart/utils.dart:      'ie10': const {
tools/testing/run_selenium.py:  elif ((browser == 'ie9' or browser == 'ie10') and
