### ISSUE TITLE
Isolate.spawn not allowed in Dartium DOM isolate

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#17649]
The Isolate.spawn function throws when used in the main isolate.
It gives the error: 
&nbsp;&nbsp;IsolateSpawnException: 'spawnFunction is not supported from a dom-enabled isolate. Please use spawnUri instead.''

Dartium should allow using Isolate.spawn even in a DOM-enabled isolate. 
It is acceptable to have a DOM that throws on any access in the spawned isolate (e.g., &quot;Error: concurrent access to DOM not allowed&quot;).

This will allow libraries to do Isolate.spawn without knowing whether they are in a DOM-enabled isolate. If they don't know, they will likely not use the DOM anyway, but they will not fail when using basic Isolate functionality.

**Comment by normcf** [comment]
Sorry to append here so late, but I have a situation where I want to clone a piece of the DOM in the dom-enabled Isolate, do some long running work on it in a background Isolate (thread), then use the main dom-enabled Isolate to replace the fragment in the DOM.  So, essentially, I want to process HTML Elements, without accessing the DOM, in another thread.  Any thoughts on how to accomplish this would be useful.
