### ISSUE TITLE
Implementations allow void as type of getters.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#17650]
The specification allows &quot;void&quot; as the return type of top-level non-external getters only, not any other getter.
It is a syntax error to have &quot;void&quot; as a return type of non-top-level or non-external getters - the grammar does not allow it.

Implementations (VM, dart2js and analyzer) all allow void as a getter return type. Example code:

void get x =&gt; null;
//external void get y;
class C {
&nbsp;&nbsp;void get x =&gt; null;
&nbsp;&nbsp;static void get y =&gt; null;
}

main() {
&nbsp;C.y;
&nbsp;new C().x;
&nbsp;x;
// y;
}

This runs and analyzes without errors in the VM, dart2js and the analyzer. If removing the comments for the external getter, it still runs in the and analyzer, and parses in the VM and dart2js.

Should we change the specification?
Should void be allowed as a type in other places too?
Or is this a widespread implementation bug?
Should void be allowed for top-level non-external getters?

**Comment by munificent** [comment]
Looks like this is done.
