### ISSUE TITLE
After dart2js: Uncaught Error: NoSuchMethodError: Cannot call "get$functions"

### ISSUE THREAD

**Issue by danellis** [dart-lang/sdk#17656]
**What steps will reproduce the problem?**
1. https://github.com/danellis/minimaldartbug
2. pub build --mode=debug
3. pub serve
4. http://localhost:8080/index.html

**What is the expected output? What do you see instead?**
Resource interpreted as Script but transferred with MIME type application/dart: &quot;http://localhost:8080/index.html_bootstrap.dart&quot;. index.html:8
warning: file:///home/dan/projects/confabulous/bug/web/index.html.0.dart library not found index.html_bootstrap.dart.js:15697
Uncaught Error: NoSuchMethodError: Cannot call &quot;get$functions&quot; on &quot;#&lt;JsLibraryMirror&gt;&quot; (Object #&lt;JsLibraryMirror&gt; has no method 'get$functions') index.html_bootstrap.dart.js:15697
Stack Trace: 
TypeError: Object #&lt;JsLibraryMirror&gt; has no method 'get$functions'
&nbsp;&nbsp;&nbsp;&nbsp;at dart._loadLibrary (http://localhost:8080/index.html_bootstrap.dart.js:17848:19)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._loadLibraries (http://localhost:8080/index.html_bootstrap.dart.js:17765:11)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._initPolymerOptimized (http://localhost:8080/index.html_bootstrap.dart.js:17756:7)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.initPolymer (http://localhost:8080/index.html_bootstrap.dart.js:17750:7)
&nbsp;&nbsp;&nbsp;&nbsp;at main (http://localhost:8080/index.html_bootstrap.dart.js:4036:7)
&nbsp;&nbsp;&nbsp;&nbsp;at _IsolateContext.eval$1 (http://localhost:8080/index.html_bootstrap.dart.js:1297:23)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.startRootIsolate (http://localhost:8080/index.html_bootstrap.dart.js:1073:21)
&nbsp;&nbsp;&nbsp;&nbsp;at http://localhost:8080/index.html_bootstrap.dart.js:24119:7
&nbsp;&nbsp;&nbsp;&nbsp;at init.currentScript (http://localhost:8080/index.html_bootstrap.dart.js:24099:5)
&nbsp;&nbsp;&nbsp;&nbsp;at http://localhost:8080/index.html_bootstrap.dart.js:24113:3
&nbsp;index.html_bootstrap.dart.js:15697
Uncaught NoSuchMethodError: Cannot call &quot;get$functions&quot; on &quot;#&lt;JsLibraryMirror&gt;&quot; (Object #&lt;JsLibraryMirror&gt; has no method 'get$functions') index.html_bootstrap.dart.js:2297

**What version of the product are you using? On what operating system?**
Dart 1.2.0, Polymer.dart 0.9.5

**Please provide any additional information below.**
This is happening even on early builds of my app that were working okay before. Although I'm developing in IntelliJ, the minimaldartbug repo above is a fresh repo created without any IDE interference.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
