### ISSUE TITLE
export show/hide a non-existing member should be a warning

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#17672]
export 'foo.dart' hide not_here;
export 'bar.dart' show also_not_here;

These should be warnings

**Comment by srawlins** [comment]
CR out for review: https://codereview.chromium.org/1901923002/

**Comment by srawlins** [comment]
New analyzer hints UNDEFINED_SHOWN_NAME, and UNDEFINED_HIDDEN_NAME in 53bf36acdb4a6a12addf15eba06eacdab7552f22.
