### ISSUE TITLE
VM allows assignment in assert.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#17682]
Grammar of assert statements is:
> 'assert' '(' conditionalExpression ')' ';'

This does not allow assignment expressions directly as the expression.
The VM allows the syntax:
```dart
assert(x = true);
```

Analyzer now catches the syntax error.

**Comment by mhausner** [comment]
dart2js also allows assert(x = true). Both implementations are wrong. I suspect that there is code that may depend on this, maybe on purpose. For example, tests/standalone/io/file_constructor_test.dart. 

```
void main() {
  bool developerMode = false;
  assert(developerMode = true);
  ....
  if (developerMode) ....
```

**Comment by mhausner** [comment]
@floitschG, please determine whether the language spec should be updated, or the two implementations should be fixed.

**Comment by eernstg** [comment]
We discussed this issue in the language team and came up with the following analysis which concludes that we will switch to `assert(expression)`: https://gist.github.com/eernstg/50a327addd96035d5393a507c0ea2d9a.

This means that the vm and dart2js already implement the right semantics, but the analyzer should be adjusted. Created a new issue for the adjustment of the analyzer.
