### ISSUE TITLE
Give stable ids to all functions

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#17697]
The VM service currently fails to assign ids to some oddball functions which are not known by their owner class (see Function::PrintToJSONStream). Examples are signature functions of closures and stubs like 'megamorphic_miss'.

An interim solution is to treat these oddball functions as plain objects and use object id ring, but longer term we should probably try to assign stable ids to all functions.

**Comment by mraleph** [comment]
This seems stale. Nothing has happened for many years.
