### ISSUE TITLE
No List constructor takes Iterator<E>

### ISSUE THREAD

**Issue by paulevans-sonar** [dart-lang/sdk#17694]
You cannot create a List from an Iterator&lt;E&gt; - construction requires an Iterable&lt;E&gt; which wraps an iterator getter that returns an Iterator&lt;E&gt;
&nbsp;
It would be convenient if the programmer already has an iterator to use that rather than require the Iterator be wrapped in an Iteratable.  For example if a function only requires an Iterator&lt;E&gt; without caring about what collection it came from (map, set, random generator, whatever) and internally wanted to represent that as a list while processing it.

Though to be fair it looks like List.from(...) just goes over the collection at least once, perhaps going over and allocating a second list if fixed length is requested. Ideally this cost would be hinted at in the documentation.

// Copied from list.dart
&nbsp;&nbsp;/**
&nbsp;&nbsp;&nbsp;* Creates a list and initializes it using the contents of [other].
&nbsp;&nbsp;&nbsp;*
&nbsp;&nbsp;&nbsp;* The [Iterator] of [other] provides the order of the objects.
&nbsp;&nbsp;&nbsp;*
&nbsp;&nbsp;&nbsp;* This constructor returns a growable list if [growable] is true;
&nbsp;&nbsp;&nbsp;* otherwise, it returns a fixed-length list.
&nbsp;&nbsp;&nbsp;*/
&nbsp;&nbsp;factory List.from(Iterable other, { bool growable: true }) {
&nbsp;&nbsp;&nbsp;&nbsp;List&lt;E&gt; list = new List&lt;E&gt;();
&nbsp;&nbsp;&nbsp;&nbsp;for (E e in other) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list.add(e);
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;if (growable) return list;
&nbsp;&nbsp;&nbsp;&nbsp;return makeListFixedLength(list);
&nbsp;&nbsp;}

**Comment by matanlurey** [comment]
There is List.of now.
