### ISSUE TITLE
Finalize and implement spawn dom isolate API

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#17738]
I'm landing an experimental initial version in dart:html as spawnDomUri.  We need to finalize the API, include where it is (dart:isolate?).

**Comment by hermanbergwerf** [comment]
Any progress on this? I need this to use Dart in my web application.

**Comment by GeKorm** [comment]
@hermanbergwerf You can now import scripts compiled by dart2js. The downside is that it doesn't use the Isolate methods, so you need to implement those that you need manually. Other than that it's very similar. See [getScript()](https://pub.dartlang.org/packages/getscript) for an example of loading scripts.

**Comment by hermanbergwerf** [comment]
@GeKorm Awesome!

**Comment by jmesserly** [comment]
we're removing dart:isolate from dart4web (and spawnDomUri was not implemented by JS compilers)
