### ISSUE TITLE
Improve control over error reporting

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#17771]
Add a flag to only report errors for the libraries listed on the command-line. If a library has parts, then errors reported against those parts should also be reported, but errors reported against imported libraries should not be reported (unless the imported libraries are also listed on the command-line).

**Comment by pq** [comment]
@bwilkerson : is this stale?  Are we still interested in doing something like this?

**Comment by bwilkerson** [comment]
I think this is now the default behavior.
