### ISSUE TITLE
Statements following throw are unreachable

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#17776]
ldap: codefu

Code after a &quot;throw&quot; statment should probably be highlighted with yellow squigglies about unreachable code.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.3.0.dev_03_00 (2014-03-07)
OS: Linux - amd64 (3.2.5-gg1336)
JVM: 1.7.0-google-v5
# projects: 8
# open dart files: 17
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1001 / 656 MB
thread count: 38
index: 559615 relationships in 91961 keys in 737 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/d7833e1c1f418bf602d0b9faec7bc868daa55cde.
