### ISSUE TITLE
analyzer: missing type propagation of method calls on top-level final fields

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#17800]
I have code like:

void main(List arguments) {
&nbsp;&nbsp;var args = _argParser.parse(arguments);
&nbsp;&nbsp;// ... more code ...
}

final _argParser = new ArgParser()
&nbsp;&nbsp;&nbsp;&nbsp;// &lt;snip&gt;
&nbsp;&nbsp;&nbsp;&nbsp;..addFlag('help', help: 'prints this message');

When hovering over the bottom _argParser, it displays the propagated type as &quot;ArgParser&quot;. However, when hovering over the use in main, it doesn't show an inferred type, and the &quot;.parse&quot; doesn't let me &quot;go to declaration&quot; or show a method tooltip. It also means that &quot;var args&quot; doesn't get a propagated type either.

Dart Editor version 1.3.0.dev_06_01 (DEV)
Dart SDK version 1.3.0-dev.6.1

**Comment by leafpetersen** [comment]
I think this is fixed in strong mode.
