### ISSUE TITLE
Please remove DeferredLoadException

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17833]
Please remove DeferredLoadException from the Dart API. It serves no purpose and only clutters api.dartlang.org.

**Comment by goderbauer** [comment]
Instead of removing it, could it be used to fix issue #25224?

**Comment by srawlins** [comment]
This exception is thrown by dart2js, and users have code that catches it. Close?

**Comment by sigurdm** [comment]
I think we can.

**Comment by sigurdm** [comment]
Please reopen anyone who still this serves no purpose.
