### ISSUE TITLE
Better UX for expanding CPU profile

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#17847]
Give me a [+] button or similar. Clicking on the name vs the rest of the row is not super intuitive.
______
**Attachment:**
[Screen Shot 2014-03-26 at 4.48.51 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-17847/comment-0/Screen Shot 2014-03-26 at 4.48.51 PM.png) (26.17 KB)

**Comment by rmacnak-google** [comment]
The UI has had the standard arrow idiom for some time.
