### ISSUE TITLE
Display the selector in the stack trace line for noSuchMethod activations

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#17869]
If an activation of noSuchMethod appears in the middle of the stack it is often useful to know at a glance what method call it is handling. Given

```dart
class D {
  static doSomethingElse() {
    throw 'Blow up';
  }
}
class C {
  noSuchMethod(invocation) {
    D.doSomethingElse();
  }
}
main() {
  new C().doSomething();
}
```

it would be nice to see:

```
Unhandled exception:
Blow up
# ­0 D.doSomethingElse (uri:line:column)
# ­1 C.noSuchMethod(#doSomething) (uri:line:column)
# ­2 main (uri:line:column)
...
```

This is similar to how in Smalltalk '42 foo' will give you

```
SmallInteger(Object)&gt;&gt;doesNotUnderstand: #foo
UndefinedObject&gt;&gt;DoIt
```

**Comment by mraleph** [comment]
@rmacnak-google do you think you will work on this? If not consider closing as stale. If it did not happen in 4 years it is unlikely to happen any time soon.
