### ISSUE TITLE
Tear-off closures should not be accessible unless marked in MirrorsUsed

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#17939]
With CL https://codereview.chromium.org/217963002/ MirrorsUsed annotations are not respected for tear-off closures anymore. That is, they will be reflectable, even though they are not in the MirrorsUsed list.

I'm adding a mirrors_used_closure_test (in dart2js_extra).

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
