### ISSUE TITLE
Windows dart2js bots fill up C: drive - with IE auto crash recovery files.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#17961]
The dart2js-full-windows slaves are running out of space on the C: drive because crashes of IE leave a copy of the open tab information for IE's automatic crash recovery.

The directory C:\Users\chrome-bot\AppData\Local\Microsoft\Internet Explorer\Recovery\Active (or High\Active) contains tens of thousands of these files, some of which are &gt; 1 MB.

We discovered this on vm195-m3, because for some reason it has a 45 GB C drive, instead of the 60 GB C drive on the other slaves.

Automatic crash recovery can be disabled in the IE options, but it still writes these files to the directory.  The only way I found on the Internet to stop this is to use ACLs to make the directory unwritable:

icacls &quot;%UserProfile%\AppData\Local\Microsoft\Internet Explorer\Recovery&quot; /deny *S-1-1-0:(OI)(WD,AD) /t

http://social.technet.microsoft.com/Forums/ie/en-US/370124c3-3ae2-40b1-85d3-64f3d9a89df3/delete-internet-explorer-recovery-dat-files?forum=ieitprocurrentver

I'm currently deleting these files, which should give us about 3 months before it happens again.

**Comment by bkonyi** [comment]
Is this still an issue @whesse? Assuming it isn't for now, feel free to reopen.
