### ISSUE TITLE
Delete event occurs after create event

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17962]
On Mac, I'm observing behavior where new Directory(...).watch() sends events in a weird order.

Basically, I see this when I revert a file in git:

{&quot;modify&quot;:[&quot;.../cache.dart&quot;]}
{&quot;create&quot;:[&quot;.../cache.dart&quot;]}
{&quot;modify&quot;:[&quot;.../cache.dart&quot;]}
{&quot;delete&quot;:[&quot;.../cache.dart&quot;]}

I think what happens is that two events occur when a file is overwritten, create a new inode, and delete the old inode.

**Comment by brianquinlan** [comment]
This behavior is [now documented](https://github.com/dart-lang/sdk/blob/main/sdk/lib/io/file_system_entity.dart#L437).

It is hard to avoid this behavior on OS X without taking a large performance hit.
