### ISSUE TITLE
Annotation: @alwaysThrows

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#17999]
It's often nice to have a _fail() method or similar.

Often if it's used in a method with a return type, the analyzer will warn about a missing return type.

Solution:

@alwaysThrows (or similar) on a method definition

1) Analyzer confirms that all code paths through the method throw (as opposed to no-op or return)
2) Effectively replaces an inline throw in code, eliminating the &quot;does not end in a return statement&quot; hint

**Comment by srawlins** [comment]
This is filed under analyzer, but the implementation would also involve package:meta, right?

**Comment by bwilkerson** [comment]
Yes, but the authors are the same, so...

**Comment by srawlins** [comment]
Fair enough. Just understanding the implementation. I guess there's no "area-meta" label.

**Comment by srawlins** [comment]
Committed.
