### ISSUE TITLE
spawnDomUri gives warning in data-uris

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#18000]
Not sure if this can be fixed, but running code encoded in a base64 string will yield a warning if the mimetype is 'application/dart'.

For example:
&nbsp;&nbsp;&nbsp;&nbsp;&lt;script type=&quot;application/dart&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:html';
&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var code = 'main() =&gt; print(&quot;hi&quot;);';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var encoded = 'data:application/dart;base64,${window.btoa(code)}';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spawnDomUri(Uri.parse(encoded), [], '');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/script&gt;

Produces this warning:

Resource interpreted as Script but transferred with MIME type application/dart: &quot;data:application/dart;base64,bWFpbigpID0+IHByaW50KCJoaSIpOw==&quot;. 

Using 'data:text/javascript' gets rid of the warning, but it seems wrong.

**Comment by jmesserly** [comment]
we're removing dart:isolate from dart4web (and spawnDomUri was not implemented by JS compilers)
