### ISSUE TITLE
spawnDomUri fails when resolving import urls in base64 encoded uris

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#18001]
spawnDomUri API fails to resolve relative and &quot;package:&quot; uris in code encoded into a base64 URIs.

I'd assume these URIs should be resolved in terms of the window baseUri, but it doesn't seem that way. Here is a repro example:

bug.html:
&nbsp;&nbsp;&nbsp;&nbsp;&lt;script type=&quot;application/dart&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:html';
&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var baseUri = Uri.parse(window.location.href);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Spawning code in other files works:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spawnDomUri(baseUri.resolve('b.dart'), [], '');  // works
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spawnDomUri(baseUri.resolve('c.dart'), [], '');  // works

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Code that contains absolute URIs work too:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_spawn(baseUri.resolve(&quot;packages/a/a.dart&quot;), 1); // works
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// I'd expect these two examples to work in the same way:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_spawn(&quot;packages/a/a.dart&quot;, 2); // nothing happens?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_spawn(&quot;package:a/a.dart&quot;, 3);  // fails
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;_spawn(String importUrl, int i) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var code = 'import &quot;$importUrl&quot;;\nmain() =&gt; print(&quot;\$value [data-uri-$i]&quot;);';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// ignore the mime-type below, see issue #0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var encoded = 'data:text/javascript;base64,${window.btoa(code)}';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spawnDomUri(Uri.parse(encoded), [], '');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/script&gt;

packages/a/a.dart:
&nbsp;&nbsp;&nbsp;&nbsp;const value = &quot;hello world&quot;;

b.dart:
&nbsp;&nbsp;&nbsp;&nbsp;import 'packages/a/a.dart';
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;main() =&gt; print('$value [b]');

c.dart:
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:a/a.dart';
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;main() =&gt; print('$value [c]');

---

I see no output on the example labeled with #­2, but a failure as follows on example #­3:

'package:a/a.dart': error: line 1 pos 1: unexpected token '&lt;'
&lt;script type=&quot;application/dart&quot;&gt;
^: package:a/a.dart package:a/a.dart:1
Internal error: 'package:a/a.dart': error: line 1 pos 1: unexpected token '&lt;'
&lt;script type=&quot;application/dart&quot;&gt;
^ 

(FYI the error line seems to match the code of bug.html)

If I set DART_PACKAGE_ROOT then the example #­3 above works.

---

**Attachment:**
[spawnuri_bug.tgz](https://storage.googleapis.com/google-code-attachments/dart/issue-18001/comment-0/spawnuri_bug.tgz) (627 Bytes)

**Comment by jmesserly** [comment]
we're removing dart:isolate from dart4web (and spawnDomUri was not implemented by JS compilers)
