### ISSUE TITLE
VM has "ß".toUpperCase() be "ß" (German sharp s), not "SS".

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#18061]
The Unicode upper-case variant of &quot;ß&quot; (U+00DF) is &quot;SS&quot;, but the VM returns &quot;ß&quot; for &quot;ß&quot;.toUpperCase().

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/6706.
