### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#18071]
I just noticed this error message:

&nbsp;&nbsp;static const MessageKind POTENTIAL_MUTATION = const MessageKind(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Variable '#{variableName}' is not known to be of type &quot;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;'#{shownType}' because it is potentially mutated in the scope for &quot;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;promotion.&quot;);

From a user's perspective, this message doesn't really make sense (what is a &quot;promotion&quot;) and doesn't contain an example. Consider changing this message.

**Comment by natebosch** [comment]
I'm not able to track down this string with some grepping, assuming it was removed.

**Comment by peter-ahe-google** [comment]
Yes. I think this message was removed when Johnni removed the old front-end from dart2js.
