### ISSUE TITLE
Neither VM nor dart2js accepts null character in source code.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#18090]
The Dart specification allows all Unicode characters as string content (depending on the string type and delimiters). There is no exception made for the null character (ASCII NUL, U+0000).

However, neither implementation actually allow a program that contains a literal NUL inside a string literal. The Analyzer does allow it.

Example code (you have to replace the visual NUL with a real NUL):

main() {
&nbsp;print(&quot;␀&quot;);
}

Posting as single bug for both implementations in case it is really a spec change that is needed.

**Comment by rakudrama** [comment]
@johnniwinther does the CFE accept \u0000 in string literals and comments?

**Comment by lrhn** [comment]
Most likely it does not. If I create a file containing a zero byte inside a string literal, 
```dart
void main() => print("");
```
as `tests/language/zero_byte_test.dart`, and run it with the `fasta` target, it fails to see the bytes after the zero-byte.
The errors are all over the place:
```
tests/language/zero_byte_test.dart:1:22: Error: String starting with " must end with ".
void main() => print("");
                     ^
tests/language/zero_byte_test.dart:1:22: Error: The control character U+0000 can only be used in strings and comments.
void main() => print("");
                     ^
tests/language/zero_byte_test.dart:1:24: Error: String starting with " must end with ".
void main() => print("");
                       ^^^
tests/language/zero_byte_test.dart:1:21: Error: Can't find ')' to match '('.
void main() => print("");
                    ^
tests/language/zero_byte_test.dart:1:24: Error: Expected ';' after this.
void main() => print("");
                       ^^^
tests/language/zero_byte_test.dart:2:1: Error: Unexpected token ''.
```

So, the *parser* appears to not be able to handle zero-bytes in the source (even though its error message suggests that it should).

**Comment by johnniwinther** [comment]
I guess that if this is a parser issue, the analyzer should fail similarly on it.

**Comment by lrhn** [comment]
The analyzer does fail:
```
unexpected analysis errors in zero_byte_test.dart:
- Line 1, column 22: SYNTACTIC_ERROR.ILLEGAL_CHARACTER
  Illegal character '0'.

- Line 1, column 22: SYNTACTIC_ERROR.UNTERMINATED_STRING_LITERAL
  Unterminated string literal.

- Line 1, column 24: SYNTACTIC_ERROR.EXPECTED_TOKEN
  Expected to find ';'.

- Line 1, column 26: SYNTACTIC_ERROR.UNTERMINATED_STRING_LITERAL
  Unterminated string literal.

- Line 2, column 1: SYNTACTIC_ERROR.EXPECTED_TOKEN
  Expected to find ')'.
```
