### ISSUE TITLE
Code sample in HttpRequest constructor doc is wrong.

### ISSUE THREAD

**Issue by tfortes** [dart-lang/sdk#18110]
On the doc page for HttpRequest:
https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html.HttpRequest#id_HttpRequest-

The code sample for the ctor saying
'Request complete ${event.target.reponseText}'));

...should be  &gt;&gt; responseText &lt;&lt;

**Comment by srawlins** [comment]
This has been fixed. No more `reponseType`.
