### ISSUE TITLE
language/disassemble_test fails on drt due to test infrastructure

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#18122]
test.dart searches the output of context_shell for &quot;PASS&quot; or &quot;FAIL&quot;.  language/disassemble_test generates more than 100,000 characters (the disassembly of all generated code), so it is truncated in the middle.  This drops the part of the output that says PASS, so the test fails.

We should change this way of reporting success, or we should make the truncation code look for PASS or FAIL in the output it is dropping, and put it back in the output.

**Comment by sjindel-google** [comment]
This seems to be causing frequent flakiness on `vm-kernel-linux-x64-try`, e.g. https://ci.chromium.org/p/dart/builders/luci.dart.try/vm-kernel-linux-release-x64-try/287, which is becoming a serious issue for passing the CQ.

**Comment by whesse** [comment]
This is an issue about context_shell, which we have stopped using.  Is the problem that the same test is flaky on the vm? language/disassemble_test?

I would file a new issue, and close this one as obsolete.

**Comment by sjindel-google** [comment]
SGTM
