### ISSUE TITLE
Future.value doc could be more helpful

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#18157]
URL: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-async.Future#id_Future-value

the doc for Future.value says
&quot;A future whose value is available in the next event-loop iteration.&quot;

if the meaning of
&quot;available at time t&quot; is that
&quot;the 'then' and 'whenComplete' callbacks will be called at some moment &lt;= t&quot;,
then this is correct, but not as helpful as it could be, especially when writing a test.
e.g. i can't tell from these docs that
new Future(() =&gt; 1).then(foo) and
new Future.value(1).then(bar)
are completely different.  the former schedules foo on the event queue while the latter schedules bar on the microtask queue.  so if i want to test that some code can tolerate a value not being ready until the next event loop iteration, i can't use Future.value, i have to use the normal Future constructor.

e.g. demonstrating that Future.value schedules handling completion on the microtask queue:
&nbsp;&nbsp;print('start');
&nbsp;&nbsp;scheduleMicrotask(() {print('microtask 1');});
&nbsp;&nbsp;new Future.value(1).then((x) {print('value completed $x');});
&nbsp;&nbsp;scheduleMicrotask(() {print('microtask 2');});
&nbsp;&nbsp;new Future(() {
&nbsp;&nbsp;&nbsp;&nbsp;print('normal future running');
&nbsp;&nbsp;&nbsp;&nbsp;scheduleMicrotask(() {print('microtask 4');});
&nbsp;&nbsp;&nbsp;&nbsp;return 1;
&nbsp;&nbsp;}).then((x) {print('normal future completed $x');});
&nbsp;&nbsp;scheduleMicrotask(() {print('microtask 3');});
&nbsp;&nbsp;print('end');
prints
&nbsp;&nbsp;start
&nbsp;&nbsp;end
&nbsp;&nbsp;microtask 1
&nbsp;&nbsp;value completed 1
&nbsp;&nbsp;microtask 2
&nbsp;&nbsp;microtask 3
&nbsp;&nbsp;normal future running
&nbsp;&nbsp;normal future completed 1
&nbsp;&nbsp;microtask 4

it may be that the dart library guys don't want to promise when this thing completes - fear of commitment.
that seems less than ideal, but if it must be, can it be made clearer that it _doesn't_ promise that
the value first becomes available in the next event loop iteration since that seems like the natural way
to interpret the current docs?

**Comment by srawlins** [comment]
Now neither of the docs ([Future.value](https://api.dartlang.org/dev/2.0.0-dev.37.0/dart-async/Future/Future.value.html) and [Future.Future](https://api.dartlang.org/dev/2.0.0-dev.37.0/dart-async/Future/Future.html)) mention the event or microtask queues. I think the idea is that these are not specified or guaranteed, and should not be relied upon.
