### ISSUE TITLE
launch_browser.dart does not support --dartium flag

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#18155]
If you run ./tools/test.py with the --dartium flag, like so:

./tools/test.py --mode=release --compiler=none --runtime=dartium --tasks=1 --dartium=../../dartium-git/src/out/Debug/Chromium.app/Contents/MacOS/Chromium html/js_test

and it fails, it will print something like this:

To retest, run:  /Users/justinfagnani/Documents/Projects/dart2-repo/dart/tools/testing/bin/macos/dart /Users/justinfagnani/Documents/Projects/dart2-repo/dart/tools/testing/dart/http_server.dart -p 51496 -c 51497 --build-directory=/Users/justinfagnani/Documents/Projects/dart2-repo/dart/xcodebuild/ReleaseIA32 --runtime=dartium

Command[dartium]: /Users/justinfagnani/Documents/Projects/dart2-repo/dart/tools/testing/bin/macos/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:51496/root_build/generated_tests/none-dartium/tests_html_js_test/test.html?crossOriginPort=51497

Notice that the Command[dartium] does not include the path to the Dartium binary originally used, nor does launch_browser.dart seem to support a --dartium flag

**Comment by athomas** [comment]
Dartium will no longer be supported in 2.0.
