### ISSUE TITLE
classes used in implements/extends clauses are not always emitted.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#18175]
# Take the following example:

class A implements B&lt;C&gt; {}

class B&lt;E&gt;{}
class C{}

main() { print(new A() is B&lt;double&gt;); }
&equals;&equals;&equals;

It should print `false`, but prints `true` because the class C is not emitted and an `undefined` takes the place of `dynamic`.

**Comment by joshualitt** [comment]
This was fixed with the new rti.
