### ISSUE TITLE
Misleading error message when compiling dart

### ISSUE THREAD

**Issue by selkhateeb** [dart-lang/sdk#18218]
**What steps will reproduce the problem?**
1. Use python version 2.6 (or anything &lt; 2.7)
2. Compile

What is the expected output? 
Traceback (most recent call last):
&nbsp;&nbsp;File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
&nbsp;&nbsp;File &quot;compile_analyzer.py&quot;, line 98, in VerifyJavacGetPath
&nbsp;&nbsp;&nbsp;&nbsp;subprocess.check_output([javac_path, &quot;-version&quot;])
AttributeError: 'module' object has no attribute 'check_output'

What do you see instead?
&quot;You do not have JDK installed, can't build the analyzer&quot;

**What version of the product are you using? On what operating system?**
bleeding edge

**Comment by bkonyi** [comment]
The analyzer hasn't been implemented in Java for a long time. Closing.
