### ISSUE TITLE
Add tests for large-ish command-line analyzer classes

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#18227]
These classes need to have tests run by the bots.

com.google.dart.command.analyze.AnalyzerImpl
com.google.dart.command.analyze.AnalyzerMain
com.google.dart.command.analyze.AnalyzerOptions

**Comment by bwilkerson** [comment]
I believe this was referring to the Java implementation of analyzer, which is no more, so I'm closing this as stale.
