### ISSUE TITLE
API with sample code

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#1824]
[user feedback]

This is more API feedback. It would be greate to have an API with sample code like msdn.com for .NET developers. Right now documentation is vague and don't know exactly what to do with it.
////////////////////////////////////////////////////////////////////////////////////
Editor Version: 3934

**Comment by sethladd** [comment]
This would be very cool. It's not on the radar to put code samples into the majority of our API docs.

Help wanted, though!
