### ISSUE TITLE
Type propagation should infer both upper and lower bounds for type parameters of literal lists and maps

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#18269]
In some circumstances it makes sense for type propagation to infer the most specific possible type for the elements of a literal list or map.  For example, when offering completions for:

&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;var numbers = [1, 1, 2, 3, 5];
&nbsp;&nbsp;&nbsp;&nbsp;numbers[0].

it makes sense to infer that numbers has type List&lt;int&gt;, so that we can offer completions for int.

However, in others, it makes sense for type propagation to infer the least specific possible type.  For example, when generating hints for:

&nbsp;&nbsp;class A {}
&nbsp;&nbsp;class B extends A {}

&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;List&lt;A&gt; as = [];
&nbsp;&nbsp;&nbsp;&nbsp;[new B()].addAll(as);
&nbsp;&nbsp;}

we should infer that the type of [new B()] is List&lt;A&gt;, so that it is compatible with the call to addAll() (see issue #17934).

I suspect that we can address this issue by inferring both a lower bound and an upper bound for each type parameter, using a Hindley–Milner style type inference algorithm.  In the example above, upon encountering &quot;List &lt;A&gt; as = []&quot; we would infer a type of List&lt;T1&gt; where T1 &lt;= A.  Upon encountering &quot;[new B()]&quot;, we would [new B()]&quot;, we would infer a type of List&lt;T2&gt; where B &lt;= T2 &lt;= dynamic.  Then, when processing &quot;.addAll(as)&quot; we would unify types T1 and T2 and deduce that B &lt;= T2 = T1 &lt;= A.

**Comment by bwilkerson** [comment]
@stereotype441 Should we close this issue?

**Comment by srawlins** [comment]
I'll close this for now. Re-open if this is still a problem.
