### ISSUE TITLE
dart2js: currentMirrorSystem().findLibrary throws a NullError on empty libraries

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#18302]
e.g.
y.dart:
&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;==
library y;

// class B {}  //-- uncomment this line for the expected behaviour.

&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;==

t.dart:
&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;==
import 'dart:mirrors';
import './y.dart';

main() {
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(currentMirrorSystem().findLibrary(const Symbol('y')));
&nbsp;&nbsp;&nbsp;&nbsp;} catch (e) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;findLibrary threw: $e&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;}
}

&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;==

dart2js t.dart &amp;&amp; node out.js gives:
findLibrary threw: NullError: Cannot call &quot;get$single&quot; on null

when it should print:
LibraryMirror on 'y'

---

dart --version:
Dart VM version: 1.4.0-dev.2.2 (Tue Apr 15 11:17:30 2014) on &quot;linux_x64&quot;

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
