### ISSUE TITLE
Move BytesBuilder into dart:typed_data

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#18348]
There's nothing IO-specific about BytesBuilder; all it does is merge typed arrays together efficiently. This is something that's useful on the client as well as the server, so it seems like it would be very useful to move it into dart:typed_data.

**Comment by nex3** [comment]
This is adequately covered by the buffer classes in the `typed_data` package.

**Comment by lrhn** [comment]
It's actually a little different from the buffers, so I'm not opposed to making the class more available.

**Comment by leisim** [comment]
@nex3 @lrhn I think you should really consider this because this class is very useful but not available in the browser :/

**Comment by kevmoo** [comment]
Closing as duplicate of https://github.com/dart-lang/sdk/issues/29027 – even though this issue is older, #29027 has more recent info

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/084f9faf813bda21c9b5394d8afadab185b53bfb

**Comment by kevmoo** [comment]
Fix reverted in https://github.com/dart-lang/sdk/commit/51d3fae7d39d188b5c36651fa8cd80a8e25d779b

**Comment by kevmoo** [comment]
oops! still want to leave this closed and use #29027 as the main issue!
