### ISSUE TITLE
Provide better way to access constants through source mirrors.

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#18346]
Currently with a String constant, you can say Dart2JsStringConstantMirror.reflectee and get the original String object.

Why can't we do this with composite objects like Map and List? 

As it is, to get the original value, I need to check if the particular mirror is of type Dart2JsMapConstantMirror or Dart2JsListConstantMirror and then call the corresponding method, which seems pretty suboptimal, especially since those aren't public interfaces.

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
