### ISSUE TITLE
Constant-indexed expression of a const List or Map should be a compile-time const.

### ISSUE THREAD

**Issue by tlarsen4google** [dart-lang/sdk#18389]
If a Map or List is const, and a constant, present key or constant, in-bounds index is used, the resulting expression should also be a compile-time constant.

**What steps will reproduce the problem?**

const Map&lt;String, String&gt; A_CONST_MAP = const {
&nbsp;&nbsp;'foo': 'bar',
&nbsp;&nbsp;'baz': 'bif',
};

const List&lt;String&gt; A_CONST_LIST = const ['foo', 'bar'];

const String A_CONST_STRING = A_CONST_MAP['foo'];
const String ANOTHER_CONST_STRING = A_CONST_LIST[0];
const String YET_ANOTHER_CONST_STRING = A_CONST_MAP[A_CONST_LIST[0]];

What is the expected output?

No compiler error.

What do you see instead?

error: line XX pos YY: initializer is not a valid compile-time constant
const String A_CONST_STRING = A_CONST_MAP['foo'];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

error: line XX pos YY: initializer is not a valid compile-time constant
const String ANOTHER_CONST_STRING = A_CONST_LIST[0];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
etc.

**What version of the product are you using? On what operating system?**

Dart VM version: 1.1.0-dev.5.11 (Wed Jan 15 00:41:27 2014) on &quot;linux_x64&quot;

**Please provide any additional information below.**

Declaring these &quot;final&quot; quiets the &quot;initializer is not a valid compile-time constant&quot; error:

final String aFinalString = A_CONST_MAP['foo'];
final String anotherFinalString = A_CONST_LIST[0];

However, the resulting Strings are then not usable as default values for named parameters:

error: line XX pos YY: expression is not a valid compile-time constant
void Foo({String val: aFinalString}) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

**Comment by munificent** [comment]
Duplicate of #8885.
