### ISSUE TITLE
Hint for const

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#18413]
I'd like to report a bug in the Dart Editor.
If I define this class:

class DisplayObject extends EventDispatcher {
&nbsp;&nbsp;// Listing of mouse event names. Used in \_hasMouseEventListener.
&nbsp;&nbsp;static const List&lt;String&gt; MOUSE_EVENTS = ['click', 'dblclick', 'mousedown',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'mouseout', 'mouseover', 'pressmove', 'pressup', 'rollout', 'rollover'];
}

The Dart Editor doesn't indicates that the literal list (the right hand of the assingment) should also have the &quot;const&quot; modifier. So if I try to print the class variable with:

void main() {
print(DisplayObject.MOUSE_EVENTS);
}

I get the following error:

/home/fomoto/src/dart/dart-sdk/bin/dart --enable-checked-mode --debug:43184 easel_dart_test.dart
'file:///home/fomoto/dart/easel_dart_test/web/easel_dart_test.dart': error: line 4 pos 33: circular dependency while initializing static field 'MOUSE_EVENTS'
print(DisplayObject.MOUSE_EVENTS);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

Best regards,
Federico Omoto

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.3.0.release (2014-04-08)
OS: Linux - amd64 (3.13.10-200.fc20.x86_64)
JVM: 1.7.0_55
# projects: 3
# open dart files: 6
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 834 / 602 MB
thread count: 33
index: 282097 relationships in 34691 keys in 505 sources

SDK installed: true
Dartium installed: true

**Comment by srawlins** [comment]
There is now an error for this:

> error: 'const' variables must be constant value
