### ISSUE TITLE
Storing null redundantly into parent of newly allocated Context

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#18449]
After allocating a new context we store the parent field unconditionally. For a lot of context allocations we are storing null as the parent as we are not chaining. This field is already initialized to null in the allocation path. Here is an example:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; v4 &lt;\- AllocateContext:4(6) T{not-null, Context, Type: class 'dynamic'}
0x16f48221    bb30000000             mov ebx,0x30
0x16f48226    8b05b067d500           mov eax,[0xd567b0]
0x16f4822c    03d8                   add ebx,eax
0x16f4822e    3b1db467d500           cmp ebx,[0xd567b4]
0x16f48234    0f83bf110000           jnc 0x16f493f9
0x16f4823a    891db067d500           mov [0xd567b0],ebx
0x16f48240    83c001                 add eax,0x1
0x16f48243    ff05608e0b01           inc [0x10b8e60]
0x16f48249    8305648e0b0130         add [0x10b8e64],0x30
0x16f48250    c740ff00061600         mov [eax-0x1],0x160600
0x16f48257    c7400306000000         mov [eax+0x3],0x6
0x16f4825e    c74007d0c1e805         mov [eax+0x7],0x5e8c1d0
0x16f48265    c7400b00100a01         mov [eax+0xb],0x10a1000
0x16f4826c    c7400f21d0c400         mov [eax+0xf],0xc4d021
0x16f48273    8d5813                 lea ebx,[eax+0x13]
0x16f48276    b906000000             mov ecx,0x6
0x16f4827b    49                     dec ecx
0x16f4827c    c7048b21d0c400         mov [ebx+ecx*0x4],0xc4d021
0x16f48283    75f6                   jnz 0x16f4827b
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; ParallelMove eax &lt;\- eax
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; v6 &lt;\- CurrentContext:10() T{not-null, Context, Type: class 'dynamic'}
0x16f48285    89f1                   mov ecx,esi
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; ParallelMove S+0 &lt;\- ecx
0x16f48287    894df8                 mov [ebp-0x8],ecx
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; StoreInstanceField:16({16}, v4, v0) T{null, Null, Type: class 'Null'}
0x16f4828a    c7400f21d0c400         mov [eax+0xf],0xc4d021

Note that it appears that we are unconditionally setting the parent at 0x16f4828a after allocation even if the parent is null.

**Comment by mraleph** [comment]
This was solved by 47e44d5669b122ca1b5201c4196f2760e9eb6964 took just 5 years :)
