### ISSUE TITLE
Optimize Context allocation for small number of vars

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#18448]
Below is the code when allocating a context with a single variable:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; v23 &lt;\- AllocateContext:4(1) T{not-null, Context, Type: class 'dynamic'}
0x81a0ae8    bb18000000             mov ebx,0x18
0x81a0aed    8b05b067d500           mov eax,[0xd567b0]
0x81a0af3    03d8                   add ebx,eax
0x81a0af5    3b1db467d500           cmp ebx,[0xd567b4]
0x81a0afb    0f834d010000           jnc 0x81a0c4e
0x81a0b01    891db067d500           mov [0xd567b0],ebx
0x81a0b07    83c001                 add eax,0x1
0x81a0b0a    ff05608e0b01           inc [0x10b8e60]
0x81a0b10    8305648e0b0118         add [0x10b8e64],0x18
0x81a0b17    c740ff00031600         mov [eax-0x1],0x160300
0x81a0b1e    c7400301000000         mov [eax+0x3],0x1
0x81a0b25    c74007a0099709         mov [eax+0x7],0x99709a0
0x81a0b2c    c7400b00100a01         mov [eax+0xb],0x10a1000
0x81a0b33    c7400f21d0c400         mov [eax+0xf],0xc4d021
0x81a0b3a    8d5813                 lea ebx,[eax+0x13]
0x81a0b3d    b901000000             mov ecx,0x1
0x81a0b42    49                     dec ecx
0x81a0b43    c7048b21d0c400         mov [ebx+ecx*0x4],0xc4d021
0x81a0b4a    75f6                   jnz 0x81a0b42

We should consider unrolling at least a few of them to avoid the looping.

**Comment by rmacnak-google** [comment]
Context allocation is no longer done inline.
