### ISSUE TITLE
Redundant register move when spilling context

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#18450]
Note the redundant register allocation and register move in the code below.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; v6 &lt;\- CurrentContext:10() T{not-null, Context, Type: class 'dynamic'}
0x16f48285    89f1                   mov ecx,esi
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;; ParallelMove S+0 &lt;\- ecx
0x16f48287    894df8                 mov [ebp-0x8],ecx

**Comment by mraleph** [comment]
This was fixed when @fsc8000 refactored away context handling to use artificial `:current_context` variable.
