### ISSUE TITLE
dart command line: prefer documenting = as the argument separator in options

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#18465]
First, = is a much more standard separator. It is supported by the args package and used in a number of our tools.

Second, our documentation is inconsistent.

When running dart --help --verbose

break-at and snapshot document their arg as '='
debug and enable-vm-server document their optional arg as [:&lt;arg&gt;]

This should be changed to [=&lt;arg&gt;] to encourage consistency

--debug[:&lt;port number&gt;]
&nbsp;&nbsp;enables debugging and listens on specified port for debugger connections
&nbsp;&nbsp;(default port number is 5858)

--break-at=&lt;location&gt;
&nbsp;&nbsp;sets a breakpoint at specified location where &lt;location&gt; is one of :
&nbsp;&nbsp;url:&lt;line_num&gt; e.g. test.dart:10
&nbsp;&nbsp;[&lt;class_name&gt;.]&lt;function_name&gt; e.g. B.foo

--snapshot=&lt;file_name&gt;
&nbsp;&nbsp;loads Dart script and generates a snapshot in the specified file

--enable-vm-service[:&lt;port number&gt;]
&nbsp;&nbsp;enables the VM service and listens on specified port for connections
&nbsp;&nbsp;(default port number is 8181)

**Comment by rmacnak-google** [comment]
d7845c6a6f44b371f3e6aff652b55c9365cd0a67
