### ISSUE TITLE
dart command line: support --option[space]value in command line arguments

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#18464]
Most &quot;modern&quot; command line tools allow a space separator between an option an its value

&quot;command --option1 v1 --option2 v2&quot; style on their command line

With the dart vm:

~/&gt; dart --enable-vm-service 1234 test.dart
Unable to open file: /Users/kevmoo/1234

**Comment by mraleph** [comment]
Assuming this is stale.
