### ISSUE TITLE
Enable GVN on safe dynamic invocations

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#18519]
Currently, GVN is disabled on dynamic invocations even if the invoked target does not have side effects, as it might produce different values for each invocation (e.g. by allocating a new object).

gvn_dynamic_field_get_test is a dart2js test with an example.

**Comment by rakudrama** [comment]
I'm going to close this.
We could do better GVN on idempotent operations, but very few would be from dynamic calls.
