### ISSUE TITLE
No hint/warning for mistyped for..in loop variable

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#18534]
This code should generate either a hint or a warning (not sure which):

void f(List&lt;String&gt; strings) {
&nbsp;&nbsp;for (int i in strings) {
&nbsp;&nbsp;&nbsp;&nbsp;print(i);
&nbsp;&nbsp;}
}

I would have expected the analyzer to inform me that since the type of strings is List&lt;String&gt;, I can't iterate through it using &quot;int i&quot;.

**Comment by munificent** [comment]
This is done now, as of: cb7aa02116917259e72d53676e77f961698778fb
