### ISSUE TITLE
Analyzer should report a hint when a Future.then() callback fails to return the proper type.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#18531]
The following code illustrates a mistake I have made frequently, and would like the analyzer to issue a hint about:

import 'dart:async';

Future foo(int i) {
&nbsp;&nbsp;return new Future(() {});
}

Future&lt;int&gt; bar() {
&nbsp;&nbsp;return foo(1).then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;/* return */ foo(2).then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return 5;
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;});
}

I meant to create a method bar() that would perform foo(1) asynchronously, then perform foo(2) asynchronously, then complete the result with the number 5.  However, because I left out a &quot;return&quot; keyword, the closure passed to foo(1).then() returns null.  (Uncommenting the &quot;return&quot; keyword fixes the mistake).

It would be nice if the analyzer could infer that the closure passed to foo(1).then() was intended to return either an int or a Future&lt;int&gt;, and issue a warning to tell me that it's returning null instead.

**Comment by srawlins** [comment]
This has been fixed. The analyzer now reports errors for the above example:

```none
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ cat 18531.dart 
import 'dart:async';

Future foo(int i) {
  return new Future(() {});
}

Future<int> bar() {
  return foo(1).then(() {
    /* return */ foo(2).then(() {
      return 5;
    });
  });
}
$ dartanalyzer 18531.dart 
Analyzing 18531.dart...
  error • The argument type '() → Null' can't be assigned to the parameter type '(dynamic) → FutureOr<int>' at 18531.dart:8:22 • argument_type_not_assignable
  error • The argument type '() → int' can't be assigned to the parameter type '(dynamic) → FutureOr<dynamic>' at 18531.dart:9:30 • argument_type_not_assignable
2 errors found.
```
