### ISSUE TITLE
Support union arguments in new IDL

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#18564]
We're seeing syntax like the following in Blink IDL:

&nbsp;&nbsp;[ImplementedAs=namedGetter] getter (NodeList or Element) namedItem(DOMString name);

This requires C++ code that handles both types to be generated.

I'm modifying the template to throw for now when this case is encountered at runtime.

**Comment by terrylucas** [comment]
Closed unions are generated as dynamic until Dart supports either union or function overloading.
