### ISSUE TITLE
test.dart log files are hard to read

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#18634]
Here is an example of a message from test.dart:

CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;window_onerror&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;window.onerror called: \n\nhttp://127.0.0.1:58314/root_build/generated_compilations/dart2js/tests_try_cursor_position_test/test.js:11360:\nUncaught Expect.equals(expected: &lt;\n\n&gt;, actual: &lt;div&gt;) fails.\n\n&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 0.159
}

This generally makes stack traces impossible to read. You have to copy the output from test.dart into a file and replace all occurrences of '\n' with an actual newline character.

This is a regression that was introduced by the browser controller. Before then, the output would be readable.

**Comment by athomas** [comment]
Duplicate of #15499.
