### ISSUE TITLE
No incompatible type hint on: f(int x, String y) => x == y;

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#18655]
type == EventType.  aMinute == Duration.  I was prototypiung and realized this didn't show a type warning in the editor....

ldap: codefu
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.4.0.dev_02_02 (2014-04-15)
OS: Linux - amd64 (3.2.5-gg1336)
JVM: 1.7.0-google-v5
# projects: 6
# open dart files: 45
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1098 / 560 MB
thread count: 37
index: 1249177 relationships in 97036 keys in 1539 sources

SDK installed: true
Dartium installed: true
______
**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-18655/comment-0/screenshot.png) (404.53 KB)

**Comment by bwilkerson** [comment]
There is now feedback for the original case, so I'm closing this as stale.
