### ISSUE TITLE
show package warnings for imported libraries that belong to the same package

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#18661]
Dart2js currently hides warnings from other packages, which is great!

Unfortunately, dart2js is also hiding warnings from code that comes from the same package. I assume dart2js treats any file imported via a &quot;package:&quot; import as if it was in another package, but many packages use &quot;package:&quot; to import code from the same package. This in fact a very common practice, as it is used in a package's 'bin', 'web', and 'test' folders to reach into 'lib', and it is also used within the 'lib' folder to avoid &quot;../&quot; in relative paths (which are very hard to read and maintain).

Here is a simple example that would reproduce the problem:

foo/
&nbsp;&nbsp;|- b.dart:
&nbsp;&nbsp;|
&nbsp;&nbsp;|    import 'lib/a.dart';  
&nbsp;&nbsp;|    main() =&gt; print(x);
&nbsp;&nbsp;|  
&nbsp;&nbsp;|- c.dart:
&nbsp;&nbsp;|  
&nbsp;&nbsp;|    import 'package:foo/a.dart';
&nbsp;&nbsp;|    main() =&gt; print(x);
&nbsp;&nbsp;|  
&nbsp;&nbsp;|- lib/
&nbsp;&nbsp;|  |- a.dart:  
&nbsp;&nbsp;|  |
&nbsp;&nbsp;|  |   int x = '3';
&nbsp;&nbsp;|  
&nbsp;&nbsp;|- packages/
&nbsp;&nbsp;|  |- self -&gt; ../lib/

`dart2js b.dart` produces this warning:

packages/self/a.dart:2:7:
Warning: 'String' is not assignable to 'int'.
int x = '3';

(similarly doing `dart2js c.dart --show-package-warnings` will produce the warning above)

but `dart2js c.dart` produces:

Hint: 1 warning(s) suppressed in package:self.

**Comment by johnniwinther** [comment]
https://codereview.chromium.org/1513263002/ add support for a specifying the user packages like --show-package-warnings=foo,bar

**Comment by sigmundch** [comment]
would it be worth making the default list be be the current package, if there is one (instead of "all" or "none")?

Not sure if we can always determine what the current package is. While the .packages file doesn't specify it explicitly, it's common that the entry for the self package uses a relative path to the lib folder , so you'd have a line like:
```
self:lib/
```

@floitschG - are there any plans to expose explicitly to the different Dart implementations what the current package name is?

**Comment by joshualitt** [comment]
If this issue still repros, I believe it would be a CFE issue.
