### ISSUE TITLE
Mirrors: constructor parameters is a list of nulls for classes with mixins

### ISSUE THREAD

**Issue by pavelgj** [dart-lang/sdk#18675]
import 'dart:mirrors';
import 'package:unittest/unittest.dart';

class Foo {
&nbsp;&nbsp;Foo(String _);
}

abstract class Bar {
}

class MixedFooWithBar = Foo with Bar;

main() {
&nbsp;&nbsp;testClass(Type type) {
&nbsp;&nbsp;&nbsp;&nbsp;var classMirror = reflectClass(type);
&nbsp;&nbsp;&nbsp;&nbsp;MethodMirror ctor = classMirror.declarations[classMirror.simpleName];
&nbsp;&nbsp;&nbsp;&nbsp;expect(ctor.parameters.every((p) =&gt; p is ParameterMirror), isTrue);
&nbsp;&nbsp;}

&nbsp;&nbsp;test('returns parameter mirrors from constructor of class', () {
&nbsp;&nbsp;&nbsp;&nbsp;testClass(Foo); // PASSES
&nbsp;&nbsp;});

&nbsp;&nbsp;test('returns parameter mirrors from constructor of class with mixin', () {
&nbsp;&nbsp;&nbsp;&nbsp;testClass(MixedFooWithBar); // FAILS: ctor.parameters is [null](list of nulls) right now
&nbsp;&nbsp;});
}

**Comment by srawlins** [comment]
This is now fixed:

```dart
import 'dart:mirrors';

class Foo {
  Foo(String _);
}

abstract class Bar {}

class MixedFooWithBar = Foo with Bar;

main() {
  testClass(Type type) {
    var classMirror = reflectClass(type);
    MethodMirror ctor = classMirror.declarations[classMirror.simpleName];
    if (ctor.parameters.every((p) => p is ParameterMirror)) {
      print('yay $type');
    } else {
      print('boo $type');
    }
  }

    testClass(Foo); // PASSES

    testClass(MixedFooWithBar); // FAILS: ctor.parameters is [null](list of nulls) right now
}
```

```
$ dart --version
Dart VM version: 2.0.0-dev.65.0 (Tue Jun 26 14:17:21 2018 +0200) on "macos_x64"
$ dart 18675.dart 
yay Foo
yay MixedFooWithBar
```
