### ISSUE TITLE
Clarify constructor name restrictions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#18672]
The specification (section &quot;Constructors&quot;) says that it's a compile time error to have a constructor Foo.id if &quot;id&quot; is declared as a member in the class.
I think the specification needs to be e

Is a constructor a declared member of the class? It seems it isn't, since other parts of the specification says &quot;members or constructors&quot;.

If it is a member, what is its name? Is it &quot;Foo.id&quot; or &quot;id&quot;? What is the name of the default constructor: &quot;Foo&quot; or &quot;&quot;?

What prevents having two constructors named &quot;Foo.id&quot;? If constructors are not members, or the name of &quot;Foo.id&quot; isn't &quot;id&quot;, the text above does not prevent it.

Also, if the name of the constructor &quot;Foo&quot; is &quot;&quot;, then there is nothing preventing the constructor name &quot;Foo.Foo&quot;? Is this correct?
It seems the VM disallows &quot;Foo.Foo&quot;, but dart2js and the analyzer allows it.

**Comment by eernstg** [comment]
No milestone now: This will not block Dart 2.

The clarification will still need to be performed, hence the issue remains open.

**Comment by eernstg** [comment]
Closing: I believe this has been resolved, particularly in the section 'Class Member Conflicts' in dartLangSpect.tex.
