### ISSUE TITLE
indexed_db ObjectStore.count() compiled with dart2js not working on IE11 

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#18712]
**What steps will reproduce the problem?**
1. The following simple browser unit test

```
 test('count', () async {
    if (IdbFactory.supported) {
      String dbName = "com.tekartik.ie_count_bug.test";
      await window.indexedDB.deleteDatabase(dbName);
      _setupDb(VersionChangeEvent e) {
        Database db = (e.target as Request).result;
        db.createObjectStore("store", autoIncrement: true);
      }
      Database db = await window.indexedDB
          .open(dbName, version: 1, onUpgradeNeeded: _setupDb);

      Transaction transaction = db.transaction("store", "readwrite");
      var objectStore = transaction.objectStore("store");
      Map value = {'sample': 'value'};
      int key = await objectStore.add(value);
      print('added $key $value');
      int count = await objectStore.count(key);
      print('count_by_key: $count');
      expect(count, 1);

      // This crashes on ie
      count = await objectStore.count();
      print('count_all: $count');

      await transaction.completed;
      db.close();
    }
  });
```
1. works on Dartium and compiled to js in Chome/Firefox but fails on IE

What is the expected output?

&nbsp;&nbsp;1 PASS Expectation: idb count. 

&nbsp;What do you see instead?

&nbsp;&nbsp;1 ERROR Expectation: idb count. Test failed: Caught DataError 

**What version of the product are you using? On what operating system?**

&nbsp;&nbsp;Windows 8, IE 11, DartEditor 1.3.6

**Please provide any additional information below.**

While developping the following package
https://pub.dartlang.org/packages/idb_shim

I encoutered many issues with IE where some simple calls to index/cursor are simply failing without much report. Can you confirm the indexed_db unittest in the dart source code work on IE? and where can I see the result?

**Comment by alextekartik** [comment]
After more testing, it seems that both ObjectStore.count() and Index.count() fails only when no argument are given.
My thinking is that ie is not correctly interpreting a null key and rather expect an undefined key (but this is just a guess). This requires modifying the sdk, as indeed ObjectStore.\_count is called with a null key rather than without argument
The unit test (tested on IE11 and Edge12) is available here: https://github.com/alextekartik/idb_shim.dart/blob/master/test/bug/ie_count_bug_test_.dart#L27

**Comment by alextekartik** [comment]
One solution I guess would be to be able to have an 'undefined' argument for js calls. According to #24088, this is not possible. Any workaround?

**Comment by alan-knight** [comment]
The normal workaround we use for these sorts of things is calling the function without the argument at the JS level as well. e.g.

```
foo([x]) {
  if (x == null) {
   js_foo(); 
  } else {
    js_foo_with_one_arg(x); 
  }
```

Mostly that's important with constructors, but it does happen in other cases like this one.

**Comment by alan-knight** [comment]
And in this case, although the IDL clearly says optional for the argument, our generation script is reading it with optional = False.  Pointer to myself: AnalyzeOperation in generator.py

**Comment by alextekartik** [comment]
Indeed I modified locally my sdk (1.13-dev.7.10) with the following for IDBIndex (indexed_db_dart2js.dart)

```dart
  @DomName('IDBIndex.count')
  Future<int> count([key_OR_range]) {
   try {
      var request;
      if (key_OR_range == null) {
	    request = _count();
      } else {
	    request = _count(key_OR_range);
	  }
      return _completeRequest(request);
    } catch (e, stacktrace) {
      return new Future.error(e, stacktrace);
    }
  }
```

and

```dart
  @JSName('count')
  @DomName('IDBIndex.count')
  @DocsEditable()
  Request _count([Object key]) native;
```

and it works in IE! Since this file is autogenerated and I don't have the whole sdk build setup I cannot really provide a patch for that

**Comment by rakudrama** [comment]
We still support IE11 and it is not clear if the problem has been resolved in the IDL or generator

**Comment by Markzipan** [comment]
Closing this since IE11 is no longer supported by our web targets.
