### ISSUE TITLE
VM mixin has wrong type parameter in field initializers of mixin.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#18713]
Example code:

class T&lt;X&gt; {
&nbsp;&nbsp;final Type tType = X;
&nbsp;&nbsp;Type get getTType =&gt; X;
}

class S&lt;Y&gt; {
&nbsp;&nbsp;final Type sType = Y;
&nbsp;&nbsp;Type get getSType =&gt; Y;
}

class TS&lt;X, Y&gt; = T&lt;X&gt; with S&lt;Y&gt;;

main() {
&nbsp;&nbsp;var ts = new TS&lt;int, String&gt;();
&nbsp;&nbsp;print(ts.sType);     // int, should be String.
&nbsp;&nbsp;print(ts.tType);     // int
&nbsp;&nbsp;print(ts.getSType);  // String
&nbsp;&nbsp;print(ts.getTType);  // int
}

The type variable assigned to sType is incorrect.

**Comment by mhausner** [comment]
I have a fix for the VM. FWIW, dart2js prints

String
int
int
int

I will file a separate bug for that.

**Comment by mhausner** [comment]
This is fixed with https://codereview.chromium.org/2085003002/
Dart2js new issue is #26743.
