### ISSUE TITLE
mirros api can't find abstract declarations

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#18721]
As reported by gyuri:

In order for us to do a better job of helping you, please provide the following information when submitting a bug:

1) SVN revision where the error was reported.

Dart-to-JavaScript compiler (dart2js) version: 1.4.0-dev.2.2

2) Steps that we can use to reproduce the error along with sample code if necessary.

import 'dart:mirrors' as mirrors;

abstract class A {
&nbsp;int f;
&nbsp;int get g;
}

@proxy
class AImpl implements A {
&nbsp;@­override
&nbsp;noSuchMethod(Invocation mirror) {}
}

void main() {
&nbsp;mirrors.ClassMirror a = mirrors.reflect(new AImpl()).type;
&nbsp;mirrors.ClassMirror i = a.superinterfaces[0];
&nbsp;print('Instance members:');
&nbsp;print('Has #f: ${i.instanceMembers.containsKey(#f)}');
&nbsp;print('Has #g: ${i.instanceMembers.containsKey(#g)}');
&nbsp;print('Declarations:');
&nbsp;print('Has #f: ${i.declarations.containsKey(#f)}');
&nbsp;print('Has #g: ${i.declarations.containsKey(#g)}');
}

Output (dart):
Instance members:
Has #f: true
Has #g: false
Declarations:
Has #f: true
Has #g: true

Output (dart2js):
Instance members:
Has #f: true
Has #g: false
Declarations:
Has #f: true
Has #g: false

Notice the last line is different.

**Comment by alexeagle** [comment]
ping! I'm adding abstract methods in Angular and ran into this.

**Comment by sethladd** [comment]
cc @sigmundch

**Comment by sigmundch** [comment]
@gbracha @eernstg - what do we want to expose through the mirror systems

@alexeagle - is this for ng1 or ng2?


While it's important to have consistent semantics between dart2js and the vm, I have

**Comment by sigmundch** [comment]
sorry - hit enter accidentally, I updated the comment to:

> @gbracha @eernstg - what do we want to expose through the mirror systems: in particular it's important to have consistent semantics between dart2js and the vm, but I'm not sure whether abstract methods should be shown or not.

> @alexeagle - is this for ng1 or ng2? the reason I ask is that I understand that ng2 will run through transformers to get rid of all uses of mirrors, so you shouldn't be hitting this bug in that case.

**Comment by alexeagle** [comment]
It's for ng2 at dev time, not runtime. We have a test (https://github.com/angular/angular/blob/master/modules/angular2/test/public_api_spec.ts) which runs in both TS and Dart, and asserts that the symbols we re-export to the public API are exactly the given set. We need to introspect on the exposed classes to find their methods, hence the problem discovering which abstract methods are exposed to users.
For now, this only affected one method in one class so I've worked around it by leaving that class non-abstract (https://github.com/angular/angular/commit/b4fe590b2d4098781b55b5695c10b3ee425b969b#diff-4b1e7b465ca159498485e54d361864c0R8)

**Comment by eernstg** [comment]
The mirror APIs ('dart:mirrors' at first, of course, and then reflectable where no attempt has been made to revise this aspect) have the distinction between a behavioral and a structural point of view.

The `instanceMembers` method uses the behavioral point of view, which means that it includes members declared locally in the class whose mirror is being queried as well as inherited members, and abstract members are excluded. Both implementations agree on this.

The `declarations` method uses the structural point of view (in the end that means the actual declarations in a given piece of source code), which means that it includes both concrete and abstract members declared in the given class, but it does not traverse the inheritance chain to find any inherited members. In this case `dart` reports that both `f` and `g` exists, but `dart2js` omits `g`.

As far as I can see, that is a bug in the 'dart:mirrors' implementation used by `dart2js`.

Btw, package reflectable contains 'declarations_test.dart' where class `A` has an abstract `getter2` member (`class A { ..   int get getter2; .. }`) which is included in `declarations` and omitted from `instanceMembers`. Looks like exactly the same test, and it runs fine after transformation.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
