### ISSUE TITLE
Analyzer should recognize "assert(false)" as a form of return value.

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#18730]
Currently, the analyzer will print a hint complaining about the lack of a return value for code like the following (from the YAML package):

&nbsp;&nbsp;&nbsp;&nbsp;int inFlow(int ctx) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch (ctx) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case FLOW_OUT:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case FLOW_IN:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return FLOW_IN;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case BLOCK_KEY:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case FLOW_KEY:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return FLOW_KEY;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(false);
&nbsp;&nbsp;&nbsp;&nbsp;}

Like a &quot;throw&quot;, the &quot;assert(false)&quot; should tell the analyzer that the program will not get to the end of the function without a return value.

**Comment by srawlins** [comment]
Is this true? What if asserts aren't enabled? Is `throw assert(false)` better in these cases?

**Comment by matanlurey** [comment]
This definitely would go against the goal of `assert`, since you'd get `null` in production.

**Comment by srawlins** [comment]
But isn't that the point of `MISSING_RETURN` hints? Returns aren't actually required, as nulls are slipped in at runtime:

```
$ cat a.dart                                                                                                                                
void main() {                                                                                                                                                                                              
  var ret = f();
  print(ret);
}

int f() {}
$ dart a.dart                                                                                                                               
null
```

The MISSING_RETURN hint is telling you that you are missing a return, which is true when asserts aren't enabled in the example.

**Comment by srawlins** [comment]
(Oh I see, you mean that my suggestion, `throw assert(false)` is dumb... good point!)
