### ISSUE TITLE
Deferred loading part-files should be possible to load ahead of time.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#18745]
Given a program with n deferred libraries, it should be possible to start loading the program and the a given subset of those libraries simultaneously.

This requires the .part.js files to work stand-alone.

The current problem is that any deferred call checks if the deferred library is loaded. And it is the loadLibrary function that marks them as loaded. - This could be moved to the part-file itself.

There would be a fixed partial order to load the files in (or rather to run them).

**Comment by joshualitt** [comment]
We currently do support concatenating part files.
