### ISSUE TITLE
Problem with pulldown menu (in breadcrumb trail) when zoomed in.

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/sdk#18778]
I was zoomed in (on Chrome) looking for a specific string in the heap map.

This is an iterative process (I wish there were some way to go &quot;back&quot; in Observatory.)

When I land on the wrong instance, I use the root-&gt;heap map pulldown to bring the heap map up and to try again. While I am zoomed in, the menu is not working properly, as shown in the screenshot.
______
**Attachment:**
[Screen Shot 2014-05-12 at 1.29.36 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-18778/comment-0/Screen Shot 2014-05-12 at 1.29.36 PM.png) (269.39 KB)

**Comment by rmacnak-google** [comment]
Don't know when it was fixed, but this is working today.
