### ISSUE TITLE
"Inspected Target Crashed" in Instance inspector

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/sdk#18781]
Very often (not always, but quite often) when I click on an instance in Heap Map and then inspect it, the inspector will crash.

In particular, it seems to happen a lot when I try to click &quot;evaluate&quot; for the &quot;toString&quot; field on a List.

See attached screenshot.

---

**Attachment:**
[Screen Shot 2014-05-12 at 2.00.13 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-18781/comment-0/Screen Shot 2014-05-12 at 2.00.13 PM.png) (92.84 KB)

**Comment by kodandersson** [comment]
I believe the Observatory should be able to safely handle all objects nowadays.
@rmacnak-google Is that true?

**Comment by rmacnak-google** [comment]
Observatory should be able to safely handle objects reached through exploring libraries and the debugger. But Instances that contain non-Instances are still reachable through heap walking code like the heap map, heap snapshot, retaining path, etc. I think these will always be Arrays or GrowableObjectArrays. It may be enough to do a shallow scan for non-Instances and refuse to evaluate if any are found.

**Comment by mraleph** [comment]
@rmacnak-google Is this still an issue or was this resolved?

**Comment by natebosch** [comment]
Closing since this hasn't had an update in a while.

**Comment by natebosch** [comment]
Does this still need info? Are we gathering that info?
