### ISSUE TITLE
Code quality of unused stubs

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#18810]
This program:

import 'dart:html';

main() {
&nbsp;&nbsp;document.querySelector('#my-id')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..scrollIntoView() // Call twice to avoid inlining.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..scrollIntoView();
}

When compiled includes these stubs:

&nbsp;&nbsp;&nbsp;&nbsp;scrollIntoView$1: function(receiver, alignment) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var hasScrollIntoViewIfNeeded = !!receiver.scrollIntoViewIfNeeded;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (hasScrollIntoViewIfNeeded)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;receiver.scrollIntoViewIfNeeded();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;receiver.scrollIntoView();
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;scrollIntoView$0: function($receiver) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return this.scrollIntoView$1($receiver, null);
&nbsp;&nbsp;&nbsp;&nbsp;},

Since scrollIntoView$1 is never called directly, it should be possible to inline it in scrollIntoView$0.

I believe this is a general problem unrelated to dart:html.

**Comment by rakudrama** [comment]
We achieve the same effect by different means.
f the `$1` primary entry is unused from a call site (other than the stub, which does not exist yet), the argument (`alignment`) is inferred to be `null`, and is elided from the parameters.
The primary entry _becomes_ the `$0` entry, so no `$0` stub is needed to add the default value:

```js
    scrollIntoView$0(receiver) {
      var hasScrollIntoViewIfNeeded = !!receiver.scrollIntoViewIfNeeded;
      if (hasScrollIntoViewIfNeeded)
        receiver.scrollIntoViewIfNeeded();
      else
        receiver.scrollIntoView();
    }
```

A dynamic call or tear-off would mean that both entry points are needed, and the code would look like the original report.
Stubs are still generated too late for general inlining, but elided parameters help in some cases.
