### ISSUE TITLE
Hint about statements with no effect

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#18849]
ldap: codefu

Ideally, I'd like a warning about code where I might have forgotten to add &quot;return&quot; :)
Example:

if (test cases) {
&nbsp;&nbsp;null;
}
return something;

same with:
false;
true;

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.4.0.dev_06_04 (2014-05-12)
OS: Linux - amd64 (3.2.5-gg1336)
JVM: 1.7.0-google-v6
# projects: 6
# open dart files: 34

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 778 / 239 MB
thread count: 31
index: 620939 relationships in 110214 keys in 762 sources

SDK installed: true
Dartium installed: true

**Comment by bwilkerson** [comment]
I believe that the unnecessary_statements lint should satisfy this request.
