### ISSUE TITLE
Additional features needed in the snapshot code

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#18854]
- Need to support writing and reading of snapshots in a streaming manner so that we don't allocate a buffer upfront for holding teh snapshot.
- figure out what we need to do if an object with native fields is serialized (throw exception or serialize a null object).
- When writing out a partial snapshot we should restrict ourselves to only sending out objects whose type is in the core-lib
- While reading a full snapshot we need to assert that No GC happens even though allocations may happen
- we need a way of recompiling a regex when a regex is sent over in the snapshot

**Comment by mraleph** [comment]
@a-siva is any work on this planned short term? maybe we should close this issue.

**Comment by mraleph** [comment]
I am assuming that this is stale.

**Comment by mraleph** [comment]
There is still a comment in the code that references this issue.

**Comment by a-siva** [comment]
I have removed the comment in the code base as it pertained to use of that code in reading full snapshots. We do not use that code any more for reading full snapshots (this is done through the cluster snapshot code).

Closing this bug as obsolete now.
