### ISSUE TITLE
Hint when invoking getContext instead of context2D

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#18862]
It is more efficient to invoke the getter 'context2D' than it is to invoke the method 'getContext' with an argument of '2d'. We should have a hint to let people know.

See https://codereview.chromium.org/286273003/ for code that adds related knowledge to type propagation.

**Comment by srawlins** [comment]
WDYT Brian, is this still worth a diagnostic, or maybe leave for an analyzer plugin (er, future plugin)?

**Comment by bwilkerson** [comment]
There might still be browsers around for which this is true, and I'm not sure we want to make our users wait until we have plugins, so maybe we should leave this open for now. :-)

**Comment by parlough** [comment]
I think it's not worth it considering `package:web`, which at least as of right now uses just uses `getContext` anyway: https://github.com/dart-lang/web/blob/c786d745a99177dda073cb75d98a4fba95a68a86/lib/src/helpers/extensions.dart#L30-L31
