### ISSUE TITLE
Add hint for incorrect assignment based on propagated types.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#18864]
This code:

&nbsp;&nbsp;class A {}
&nbsp;&nbsp;class B {}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;Map&lt;String, A&gt; c = &lt;String, A&gt;{};
&nbsp;&nbsp;&nbsp;&nbsp;c['foo'] = new B();
&nbsp;&nbsp;}

produces the warning &quot;A value of type 'B' cannot be assigned to a variable of type 'A'&quot;, as expected.

This code should produce the equivalent hint, but it doesn't:

&nbsp;&nbsp;class A {}
&nbsp;&nbsp;class B {}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;var c = &lt;String, A&gt;{};
&nbsp;&nbsp;&nbsp;&nbsp;c['foo'] = new B();
&nbsp;&nbsp;}

**Comment by srawlins** [comment]
This works with Strong Mode. https://dartpad.dartlang.org/2df2687e6c8032763f26d8af5e53b213
