### ISSUE TITLE
Observatory needs an icon

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/sdk#18880]
Observatory needs its own icon. It needs both a 48x48 pixel icon and a much smaller icon that can be used in Dart Editor for the console. 

The attached image shows what we are using now inside of Dart Editor.

On the Tools index page, I am using the same icon that is used for Dart Editor, but it would be better to have an Observatory-specific icon.

**Comment by rmacnak-google** [comment]
Not planned.
