### ISSUE TITLE
dartanalyzer fails in batch mode in checkouts with a space in the path

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#18908]
On Windows and linux, if there is a space in the path of a dart checkout, running tools/test.py -cdartanalyzer -rnone  will show most tests failing, with the error

File not found: [absolute path of checkout, truncated at first space]

Other failures found (from the test infrastructure) when running in --nobatch mode are being fixed, but this issue is due to the batch mode of dartanalyzer (--client flag) reading the input file name from stdin, and parsing it by splitting it on spaces.  Even enclosing the file name in quotes, when the test runner puts it on stdin of the dartanalyzer (java) running in batch mode, does not succeed - it is still truncated at the space.  The analyzer needs to do a cleverer job of parsing the batch input, and then the test runner needs to be modified too.

This probably needs to be fixed in the Dart version of the analyzer too.  I believe floitch is working on a similar issue for dart2js.

**Comment by pq** [comment]
I believe this is no longer an issue?
