### ISSUE TITLE
Make type rules more flow sensitive.

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#18921]
[ed note: The analyzer actually has enough information to remove this warning, as indicated by the syntax highlighting of &quot;err.reasons&quot; -- 'reasons' is known to be a member. However, the spec says the editor MUST display the warning, so it does.]

ldap: codefu

Still seeing random places where the editor can't tell the type.  In the screen shot there's one path that checks if the error is not a CodeError and returns.  Later err is still listed as &quot;Object&quot; and thus there's yellow squiglies.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.4.0.dev_06_04 (2014-05-12)
OS: Linux - amd64 (3.2.5-gg1336)
JVM: 1.7.0-google-v6
# projects: 5
# open dart files: 41

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1039 / 770 MB
thread count: 51
index: 621951 relationships in 110530 keys in 758 sources

SDK installed: true
Dartium installed: true

---

**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-18921/comment-0/screenshot.png) (515.20 KB)

**Comment by munificent** [comment]
We are working on a proposal now that addresses this: https://github.com/dart-lang/sdk/pull/29624

**Comment by lrhn** [comment]
Done! 😁
