### ISSUE TITLE
unreachable code analysis does not support labeled statements

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#18936]
The type checker does not support labeled statements and thus might wrongly report code as unreachable. For example

L: {
&nbsp;&nbsp;if (true) break L;
&nbsp;&nbsp;return false;
}
return true;

will report 

Warning: Unreachable code.
&nbsp;&nbsp;return true;
&nbsp;&nbsp;^^^^^^^^^^^^

**Comment by srawlins** [comment]
This was fixed... at some point. https://dartpad.dartlang.org/77c9dfae2bcfdbc767f4ed501daaaa73
