### ISSUE TITLE
Warn on unused constructor, static, and top-level function parameters

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#18946]
It would be awesome if the analyzer helped warn about unused parameters in  constructors, like:

&nbsp;&nbsp;Foo.fromDetails(this._json, _jsonWatchEvent);

Which I was able to catch in someone's code review, but only after doing a double-take.

Optional: If people intended on swallowing / ignoring a variable, add @­ignored

**Comment by srawlins** [comment]
Definitely still good to have.

**Comment by srawlins** [comment]
This is implemented as a lint rule in the linter package: [avoid_unused_constructor_parameters](http://dart-lang.github.io/linter/lints/avoid_unused_constructor_parameters.html).
