### ISSUE TITLE
Dart cannot be built from Git repo

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#18991]
I'm hitting dead-locks generating the version files because it's not being run from an SVN repo. 

Basically tools/utils.py's GetSVNRevision() is hanging because 'git svn info' hangs.

Repro steps:
git clone https://chromium.googlesource.com/external/dart/bleeding_edge
cd bleeding_edge/dart
export GYP_GENERATORS=&quot;ninja&quot;
gyp --toplevel-dir=. --depth=. -Itools/gyp/all.gypi runtime/dart-runtime.gyp
ninja -C out/Debug libdart

I'm running into this when working on a custom embedder for Dart, trying to have a GYP dependency on Dart.

**Comment by mit-mit** [comment]
Stale, we are all git not, closing
