### ISSUE TITLE
VM prints "uncaught error" even when the error is caught

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#19034]
Consider tests/isolate/spawn_uri_missing_test.dart:

import 'dart:isolate';

import 'dart:async';

import 'package:async_helper/async_helper.dart';

const UNEXPECTED_MESSAGE = 'Created isolate from missing file.';

Future doTest() {
&nbsp;&nbsp;return Isolate.spawnUri(Uri.base.resolve('no_such_file'), [], null)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.then((Isolate isolate) {
&nbsp;&nbsp;&nbsp;&nbsp;throw UNEXPECTED_MESSAGE;
&nbsp;&nbsp;}).catchError((error) {
&nbsp;&nbsp;&nbsp;&nbsp;if (error == UNEXPECTED_MESSAGE) throw error;
&nbsp;&nbsp;&nbsp;&nbsp;print('An error was thrown as expected');
&nbsp;&nbsp;&nbsp;&nbsp;return null;
&nbsp;&nbsp;});
}

main() {
&nbsp;&nbsp;asyncTest(doTest);
}

When invoked on the standalone VM, this error message is printed:

Uncaught Error: FileSystemException: Cannot open file, path = '/Users/ahe/Dart/all/dart/no_such_file' (OS Error: No such file or directory, errno = 2)
Stack Trace: 
#­0      \_File.open.&lt;anonymous closure&gt; (dart:io/file_impl.dart:349)
#­1      \_rootRunUnary (dart:async/zone.dart:730)
#­2      \_RootZone.runUnary (dart:async/zone.dart:864)
#­3      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#­4      \_Future._propagateToListeners (dart:async/future_impl.dart:571)
#­5      \_Future._completeWithValue (dart:async/future_impl.dart:331)
#­6      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:393)
#­7      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#­8      \_asyncRunCallback (dart:async/schedule_microtask.dart:32)
#­9      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:128)

However, the error is caught using catchError, and nothing should be printed.

**Comment by lrhn** [comment]
I no longer see the error message, so assuming this has been fixed.
