### ISSUE TITLE
Dartium build occasionally fails with KeyError: 'Dart_Android_Base'

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#19054]
We've seen this occasionally on the bots and locally for the past month or so.  It's rare, and re-building appears to always work.

Here's the error:

Updating projects from gyp files...
Using overrides found in /Users/chrome-bot/.gyp/include.gypi
Traceback (most recent call last):
&nbsp;&nbsp;File &quot;src/build/gyp_chromium&quot;, line 296, in &lt;module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;gyp_rc = gyp.main(args)
&nbsp;&nbsp;File &quot;/Volumes/data/b/build/slave/dartium-mac-inc-be/build/src/tools/gyp/pylib/gyp/**init**.py&quot;, line 527, in main
&nbsp;&nbsp;&nbsp;&nbsp;return gyp_main(args)
&nbsp;&nbsp;File &quot;/Volumes/data/b/build/slave/dartium-mac-inc-be/build/src/tools/gyp/pylib/gyp/**init**.py&quot;, line 512, in gyp_main
&nbsp;&nbsp;&nbsp;&nbsp;generator.GenerateOutput(flat_list, targets, data, params)
&nbsp;&nbsp;File &quot;/Volumes/data/b/build/slave/dartium-mac-inc-be/build/src/tools/gyp/pylib/gyp/generator/ninja.py&quot;, line 2203, in GenerateOutput
&nbsp;&nbsp;&nbsp;&nbsp;pool.map(CallGenerateOutputForConfig, arglists)
&nbsp;&nbsp;File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py&quot;, line 250, in map
&nbsp;&nbsp;&nbsp;&nbsp;return self.map_async(func, iterable, chunksize).get()
&nbsp;&nbsp;File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py&quot;, line 554, in get
&nbsp;&nbsp;&nbsp;&nbsp;raise self._value
KeyError: 'Dart_Android_Base'
Hook '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/python src/build/gyp_chromium' took 51.98 secs

**Comment by athomas** [comment]
Closing. Dartium and GYP are no longer relevant.
