### ISSUE TITLE
VM does not allow metadata on local function declaration.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#19060]
Example code:

&nbsp;&nbsp;import &quot;dart:mirrors&quot;;
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;const X = 42;
&nbsp;&nbsp;&nbsp;&nbsp;@­X int foo() =&gt; 42;
&nbsp;&nbsp;&nbsp;&nbsp;print(reflect(foo).function.metadata);
&nbsp;&nbsp;}

This should parse correctly, and (if mirrors works) print the annotation.
Currently it doesn't even parse, but fails with:

'file:///.../mif4.dart': error: line 4 pos 3: unexpected token '@'
&nbsp;&nbsp;@­X int foo() =&gt; 42;
&nbsp;&nbsp;^

**Comment by rmacnak-google** [comment]
This won't be fixed in the VM front end.
