### ISSUE TITLE
Dart2js doesn't parse metadata on local function declarations.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#19061]
Example code:

&nbsp;&nbsp;import &quot;dart:mirrors&quot;;
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;const X = 42;
&nbsp;&nbsp;&nbsp;&nbsp;@­X int foo() =&gt; 42;
&nbsp;&nbsp;&nbsp;&nbsp;print(reflect(foo).function.metadata);
&nbsp;&nbsp;}

This should parse correctly, and (if mirrors works) print the annotation.
Currently it doesn't even parse, but fails with:

Error: Expected an expression, but got '@'.

**Comment by sigmundch** [comment]
dupe of #5842
