### ISSUE TITLE
"Reset" button in Observatory

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#19096]
Dart Observatory tab in dev tools in Dartium doesn't have a &quot;Reset&quot; button to reset the counters. This makes it hard to debug live applications, in which it takes multiple steps to get to the specific screen/widget/state to be profiled.

**Comment by turnidge** [comment]
Dart Observatory tab is not part of Dartium anymore.  Now you just connect to the service port when running dartium.  When you launch Dartium from the command line, it should advertise the vm service port.
