### ISSUE TITLE
StreamController.close returns a Future that never completes

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#19095]
Consider the following code:

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var controller = new StreamController();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;controller.close().then((_) =&gt; print(&quot;done closing&quot;));
&nbsp;&nbsp;&nbsp;&nbsp;}

This exits without printing anything. The [controller.close] Future is never completing.

With issues as straightforward as this and issue #18586 going undetected by the library authors, I'm worried that the test coverage for dart:async is woefully insufficient.

**Comment by natebosch** [comment]
Reopening since this the documentation is not updated and this is still confusing. The future will also never complete if the subscription was paused before the done even was delivered - this can easily happen in tests that use `StreamQueue`.

I think it's worth updating the documentation to make it clear that it's generally safe to ignore the returned Future, especially since usage of the `unawaited_future` lint is becoming more common.

**Comment by LewisHolliday** [comment]
I think the docs or the implementation is incorrect for broadcast stream controllers.

The docs say:
'The returned future is the same future provided by done. It is completed when the stream listeners is done sending events, This happens either **when the done event has been sent**, or when the subscriber on a single-subscription stream is canceled.'

**A broadcast stream controller will send the done event even if listeners are paused**, so some broadcast events may not have been received yet when the returned future completes.

```dart
import 'dart:async';

void main() async {
  final c = StreamController<int>.broadcast();
  final stream = c.stream;

  final sub = stream.listen(print);

  c.add(100);
 
  sub.pause();

  await c.close(); //nothing completes this
  print('closed'); 
}
```

**Comment by lrhn** [comment]
That is misleading. The done future is completed when the done event has been *processed*, not just sent.
A paused listener will not process the event.

I think it's slightly weird that a broadcast controller cares about its listeners being there or not, but there is a practical reason for it.

The reason for the "done future" existing at all, is that the stream controller/owner should not start cleaning up resources required by events until all events have been delivered. Even a broadcast stream can need that.
When the done future completes, it's guaranteed that there are no pending data (or error) events which have not been delivered, and which will be delivered later.

Stream listeners can pause their subscription until they have fully processed an event, that way they can tell the stream source that they're not done yet. When they receive the done event, they report that back, and both sides now know that all events have been fully processed.

So there is a reason. It's just not documented very well.
