### ISSUE TITLE
Adding an import makes my program faster

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#19157]
I have two identical programs, but one imports a large library:

==&gt; tests/compiler/dart2js/incremental/structured_fuzzer_async2.dart &lt;==
import 'dart:io';

import 'dart:async';

import '../memory_compiler.dart';

main(List&lt;String&gt; arguments) {
&nbsp;&nbsp;Stopwatch sw = new Stopwatch()..start();
&nbsp;&nbsp;Map&lt;String, String&gt; sources = &lt;String, String&gt;{};
&nbsp;&nbsp;Future&lt;String&gt; futures = new List&lt;Future&lt;String&gt;&gt;();
&nbsp;&nbsp;Uri testScheme = new Uri(scheme: 'org-dartlang-test');
&nbsp;&nbsp;Future.forEach(arguments, (String argument) {
&nbsp;&nbsp;&nbsp;&nbsp;Uri uri = testScheme.resolve(argument);
&nbsp;&nbsp;&nbsp;&nbsp;Future&lt;String&gt; future =
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File.fromUri(Uri.base.resolve(argument)).readAsString();
&nbsp;&nbsp;&nbsp;&nbsp;return future.then((String source) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sources['$uri'] = future;
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}).then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;sw.stop();
&nbsp;&nbsp;&nbsp;&nbsp;print(sw.elapsedMilliseconds);
&nbsp;&nbsp;});
}

==&gt; tests/compiler/dart2js/incremental/structured_fuzzer_async3.dart &lt;==
import 'dart:io';

import 'dart:async';

main(List&lt;String&gt; arguments) {
&nbsp;&nbsp;Stopwatch sw = new Stopwatch()..start();
&nbsp;&nbsp;Map&lt;String, String&gt; sources = &lt;String, String&gt;{};
&nbsp;&nbsp;Future&lt;String&gt; futures = new List&lt;Future&lt;String&gt;&gt;();
&nbsp;&nbsp;Uri testScheme = new Uri(scheme: 'org-dartlang-test');
&nbsp;&nbsp;Future.forEach(arguments, (String argument) {
&nbsp;&nbsp;&nbsp;&nbsp;Uri uri = testScheme.resolve(argument);
&nbsp;&nbsp;&nbsp;&nbsp;Future&lt;String&gt; future =
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File.fromUri(Uri.base.resolve(argument)).readAsString();
&nbsp;&nbsp;&nbsp;&nbsp;return future.then((String source) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sources['$uri'] = future;
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}).then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;sw.stop();
&nbsp;&nbsp;&nbsp;&nbsp;print(sw.elapsedMilliseconds);
&nbsp;&nbsp;});
}

I run the programs using (bash command line syntax):

for i in {1..10} ; do ./sdk/bin/dart -pp/ tests/compiler/dart2js/incremental/structured_fuzzer_async2.dart tests/compiler/dart2js_extra/\*.dart; done

Which prints:

102
103
102
100
104
99
98
100
99
107

for i in {1..10} ; do ./sdk/bin/dart -pp/ tests/compiler/dart2js/incremental/structured_fuzzer_async3.dart tests/compiler/dart2js_extra/\*.dart; done

Which prints:

121
118
117
120
120
116
117
118
118
116

This looks like removing the import makes the program 10% slower.

**Comment by mhausner** [comment]
I can't repro this. 

On the upside, this scheme may be useful for performance-related issues. Just add imports until the program runs fast enough :)
