### ISSUE TITLE
Embedding API giving incorrect function names?

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#19256]
When the snippet below is stopped at the throw, DevTools and the Editor will incorrectly name the top activation's function &quot;Foo.&lt;anonymous closure&gt;&quot;. The Observatory and the standalone stack trace correctly name it &quot;Foo.foo.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;&quot;.

class Foo extends Super {
&nbsp;&nbsp;foo() {
&nbsp;&nbsp;&nbsp;&nbsp;[1, 2, 3].forEach((ea){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1, 2, 3].forEach((ea){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (ea == 2)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw &quot;Two!&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}
}

**Comment by rmacnak-google** [comment]
@crelier IIRC, you mentioned one of the name printing methods stopped at one level?

**Comment by crelier** [comment]
I had missed the fact that the code was recursive. So I think that it does the correct thing, but in a convoluted way. I rewrote this function in my currently pending change.
