### ISSUE TITLE
Documentation of num.parse is technically incorrect.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#19284]
It claims the:
&nbsp;&nbsp;For any number n, this function satisfies identical(n, num.parse(n.toString())).

That isn't true for a NaN with a payload.

(It should also say that it returns the return value of the onError call).

**Comment by srawlins** [comment]
The documentation for [num.parse](https://api.dartlang.org/dev/2.0.0-dev.64.0/dart-core/num/parse.html) has been updated.
