### ISSUE TITLE
Dart VM fails to read dart files encoded as UTF-8-with-sig

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#19304]
**What steps will reproduce the problem?**
1. Create a .dart file saved as UTF8 with signature/BOM
2. Execute &quot;Dart (filename)&quot;

**What is the expected output? What do you see instead?**
- Expected: Script runs normally
- Actual: error: line 1 pos 1: unexpected character: '´╗┐' (U+FEFF)

**What version of the product are you using? On what operating system?**
- Dart VM version: 1.4.0 (Tue May 20 05:41:08 2014) on &quot;windows_ia32&quot;
- Windows 8.1 Professionalcls

---

**Attachment:**
[dart.png](https://storage.googleapis.com/google-code-attachments/dart/issue-19304/comment-0/dart.png) (26.18 KB)

**Comment by mraleph** [comment]
This seems stale.

**Comment by DanTup** [comment]
@mraleph Still happens in v2 dev48:

```
dantup-macbookpro:bin dantup$ dart --version
Dart VM version: 2.0.0-dev.48.0.flutter-fe606f890b (Mon Apr 16 21:21:13 2018 +0000) on "macos_x64"

dantup-macbookpro:bin dantup$ dart bom.dart
'file:///Users/dantup/Desktop/Dart%20Sample/bin/bom.dart': error: line 1 pos 1: unexpected character: '﻿' (U+FEFF)

﻿main() {
^
```

**Comment by mraleph** [comment]
@DanTup does it also fail if you run Dart VM with `--preview-dart-2`?

**Comment by DanTup** [comment]
Whoops, I forgot that wasn't default for the VM. Indeed, it's fine with that flag. Thanks!

**Comment by mraleph** [comment]
Thanks for checking. Marking this as fixed (it only took 4 years and a switch to a completely new parsing infrastructure :))
