### ISSUE TITLE
Analyzer should create a hint when the target of a cascade is a class

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#19316]
The following code:

class C {
&nbsp;&nbsp;m() {}
}
main() {
&nbsp;&nbsp;C..m();
}

will result in a run-time exception (no such method) being thrown. Analyzer should provide a hint to that effect. (This is based on issue #19313.)

**Comment by srawlins** [comment]
This now gives a warning:

> warning: The method 'm' is not defined for the class 'Type'.

https://dartpad.dartlang.org/673d7eb90de91f4e9f5cd8ea11a3eb3b
