### ISSUE TITLE
dart2js: reflective NSMEs don't match their non-reflective counterparts

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#19353]
mirrors/mirrors_nsm_test/dart2js: RuntimeError

==Base==
&nbsp;NoSuchMethodError : method not found: 'Symbol(&quot;get foo&quot;)'
Receiver: &quot;&quot;
Arguments: []

==Reflective==
&nbsp;NoSuchMethodError : method not found: 'Symbol(&quot;foo&quot;)'
Receiver: Instance of 'JsLibraryMirror'
Arguments: []

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
