### ISSUE TITLE
Allow main Dart isolate to be run as the main thread.

### ISSUE THREAD

**Issue by skabet** [dart-lang/sdk#19380]
Many UI libraries expect to be run in the main thread. It should either be the default behavior or available behind a flag.

**Comment by zanderso** [comment]
I don't believe there's anything to prevent a thread spawned from a native extension creating an isolate an isolate that takes care of it's own message handling. However we tend to create new embedders when different semantics like this are required. In any case, I don't think we're planning to add the requested feature to the standalone VM.
