### ISSUE TITLE
VM: Security: Prevent DoS from hashmap collisions 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#19399]
See https://code.google.com/p/dart/issues/detail?id=1748

This is for tracking the VM implementation of hashing algorithms

**Comment by kodandersson** [comment]
This very old feature request should have a priority assigned to it. How important is this relative to other DoS vectors, and how much performance are we willing to sacrifice?

**Comment by kevmoo** [comment]
I'd have to see a stack-rank of DOS vectors. :smile: 

How much performance: enough to mitigate the concern. Given ruby, JS, .NET etc have handled this, I'm assuming there are ways to do it without causing big regressions.

**Comment by drbo** [comment]
SipHash is a fast, cryptographically secure hash function.
