### ISSUE TITLE
Comments about observatory

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#19396]
**[user feedback]**

I played with the observatory in the last days. The observatory is a nice start but the performance is terrible. Some other problems I noticed:

I was testing it with pub, on startup pub is spawning soem isolates that are later stopped. I got an error message in observatory because isolates where missing (on the main page). Maybe you can handle that case better.

The resolution of the profiler (or the level of details) is not sufficent. It only shows methods that are using much samples, it would be nice if it could show the amount of sample per line! Visual Studio can do it for C++ and C#. I also miss this in the V8 profiler, so it would be a big plus compared to Javascript.
If I open the page of a function that is slow, the output could be more usefull. I only know the name , the Dart source code and the optimzisation status. Maybe sometimes it would be interesting to the assembler or another way to see that the generated code might be a bad choice.

For the allocation profiler: The performace is really bad, but I like it. It helped me to solve some problems. I like that you see the amount of objects that where allocated even if they where already collected. The Chrome Dev Tools can't do that! But now it would be nice to fix memory leaks as easy as with the Dev Tools. Another nice thing would be list for each type that shows where (in which line/function) the object was instanced and how often. Example:

new X() // 10% Of all allocations in line 1 method y() in file z

for (int i = 0; i &lt; 9; ++i) {
&nbsp;new X(); // 90%  Of all allocations in line 4 method y() in file z
}

The usebility of the drop down menu is not good. It is closing often while I try to use an option... I hate it!

IO stats would also be a cool addition, for both disk and network stuff. Now features that would be cool but more for the long run:
\* Export feature, I already had a situation where I would like to send a report that I captured to the Dart team to solve a problem
\* Capturing network traffic? Would be interesting for WebSockets. The Dev Tools don't handle Websocket debugging (reading the messages) that well. This would be interesting for both client and server.

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.5.0.dev_04_02 (2014-06-06)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_51
# projects: 5
# open dart files: 2
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 831 / 353 MB
thread count: 36
index: 1080102 relationships in 182277 keys in 1622 sources

SDK installed: true
Dartium installed: true

**Comment by turnidge** [comment]
Assigning John so he and comment and perhaps close this bug.  We have made many improvements to the profiler since this bug was filed, so it is unclear if all of the comments still apply.

**Comment by johnmccutchan** [comment]
@stevemessick Many of the issues you've raised have been addressed (to some extent):

- CPU Profiler now shows inlined functions. Per source line profiling is a good feature request, please file it separately.
- Allocation profiler is very fast now.
- Collecting information on where objects are allocated is in 1.12.
- IO stats are being worked on.
