### ISSUE TITLE
Request for an improved least upper bound on generic types

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#19425]
Feature request for an improved least upper bound on generic types:

The current definition of least upper bound for interface types is based on a hierarchical ordering of the supertypes of the types for which we try to find the most specific common type that is unique.

For instance for the least upper bound of `List<int>` and `List<dynamic>` we compute:

Supertypes for `List<int>` by depth:
```
0: Object
1: Iterable<int>, EfficientLength
2: List<int>
```

and supertypes for `List<dynamic>` by depth:
```
0: Object
1: Iterable<dynamic>, EfficientLength
2: List<dynamic>
```

The common supertypes are (by depth)
```
0: Object
1: EfficientLength
```

and `EfficientLength` is chosen because it's the most specific.

I propose a pragmatic solution that will improve the handling of generic types:

Instead of computing the least upper bound for interface directly on types but instead on declarations we will compute the superdeclarations by depth for both `List<dynamic>` and `List<int>` to be:
```
0: Object
1: Iterable, EfficientLength
2: List
```

We choose `List` as the most specific declaration. Since `List` is generic we want to find its type arguments. The naive approach is to apply algorithm recursively but (in strange cases) this can lead to infinite computations and/or recursive types so we don't go down that path. 

Instead, to get something of value, we use the more specific relation, `<<`, to find the type arguments of the most specific declaration: For each type variable, if one of the type arguments is less specific than all other we choose this, otherwise we choose dynamic. In the example, since `int << dynamic`, we then find `List<dynamic>` to be the least upper bound.

This solution will not aid in finding problems like `List list = b ? [] : 0;` but it will remove some of the annoying false positives encountered for generic types.

See also http://dartbug.com/19282 for background.

**Comment by munificent** [comment]
Merging with #27525.
