### ISSUE TITLE
Remove DART_PACKAGE_ROOT from Dartium

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#19433]
We no longer use this environment variable for development.

It's only used for a few LayoutTests in our blink branch.  We should modify those tests to not use package:unittest and remove the env var altogether.

**Comment by whesse** [comment]
Now that we don't have a package root anymore, all the tests are failing.  Unless we were to add a binding for DART_PACKAGE_SPEC or DART_PACKAGES, which took the .packages file, we can't solve this.  We want to remove unittest anyway - it is deprecated and unmaintained.

So step 1 is to mark those layout tests as failing, and step 2 is to remove unittest from them (and add no other packages).

**Comment by terrylucas** [comment]
Remove the Dartium LayoutTests using packages.

**Comment by whesse** [comment]
Should we also remove the use of the DART_PACKAGE_ROOT env vearible in dartium, before closing this issue?

**Comment by terrylucas** [comment]
Yep, no reason to use it.

**Comment by terrylucas** [comment]
Committed CL: https://codereview.chromium.org/2362793003/
