### ISSUE TITLE
Inconsistent API for external strings vs. typed arrays

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#19482]
External strings and external typed arrays are handled differently in the embedder API, the former take a peer and callback, while the latter do not:

Dart_Handle Dart_NewExternalLatin1String(
&nbsp;&nbsp;&nbsp;&nbsp;const uint8_t* latin1_array,
&nbsp;&nbsp;&nbsp;&nbsp;intptr_t length,
&nbsp;&nbsp;&nbsp;&nbsp;void* peer,
&nbsp;&nbsp;&nbsp;&nbsp;Dart_PeerFinalizer cback);

vs

Dart_Handle Dart_NewExternalTypedData(Dart_TypedData_Type type,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void* data,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;intptr_t length);

For the latter, the peer and callback can be specified when wrapping it in a new weak persistent handle.

This complicates the tracking of how much externally allocated memory is kept alive. We currently only track what the user tells us when creating the weak persistent handle, and also, this tracking is lost when sending external strings/typed arrays as messages between isolates.

**Comment by kodandersson** [comment]
Settling how to handle these as inter-isolate messages seems like the most important part.

**Comment by mraleph** [comment]
Seems stale - nothing has happened and nothing is planned to happen.
