### ISSUE TITLE
indexeddb_1_test timing out in Dartium

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#19512]
**If you know the Area-\* label, please set it \_and_ change status to Triaged.**

If you are reporting a problem in the Dart Editor, please open the Help -&gt;
**About Dart Editor dialog and add the Dart SDK version number to this**
**report.  If you prefer, you can use the 'Send Feedback' button in the Dart**
**Editor to file a report that will contain this information and additional**
**context helpful for debugging the problem.**

**Comment by kodandersson** [comment]
Closing as obsolete.
