### ISSUE TITLE
Dartanalyzer doesn't warn about "external" / Dart language specification is missing "external" keyword ?

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#19515]
The following dart file

$ cat test.dart
import 'dart:core' as external;

foo(external.String msg) =&gt; external.print(msg);

main() {
&nbsp;&nbsp;foo('Hello world.');
}

*Produces no warnings on the dartanalyzer*

$ dartanalyzer test.dart
Analyzing [test.dart]...
No issues found

*Produces an error on the dart VM*

$ dart test.dart  
'file:///usr/local/google/home/kustermann/discovery-tests/test.dart': error: line 3 pos 5: type name expected
foo(external.String msg) =&gt; external.print(msg);
&nbsp;&nbsp;&nbsp;&nbsp;^

*Produces an error and a warning in dart2js*

$ dart2js test.dart  
test.dart:3:13:
Error: Expected identifier, but got '.'.
foo(external.String msg) =&gt; external.print(msg);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
test.dart:6:6:
Warning: Arguments do not match the expected parameters of 'foo'.
&nbsp;&nbsp;foo('Hello world.');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^
Error: Compilation failed.

What should the behavior in this case be? The &quot;external&quot; word is not reserved in the language specification. The [Dart1.2Spec] defines the following list as reserved words that cannot be used as an identifier:

[assert, break, case, catch, class, const, continue, default, do, else, enum, extends, false, final, finally, for, if, in, is, new, null, rethrow, return, super, switch, this, throw, true, try, var, void, while, with]

I assume that the dartanalyzer needs to be changed and the &quot;external&quot; word needs to be included into the dart language specification. Opinions?

[Dart1.2Spec] https://www.dartlang.org/docs/spec/latest/dart-language-specification.html#h.huusvrzea3q

**Comment by natebosch** [comment]
This is now a static error in analyzer and CFE
