### ISSUE TITLE
VM internal JSON parser should support floating point numbers

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#19529]
The Service_Isolate test started to fail for no obvious reason. Turns out that we started sending a floating point number in the message and the VM internal parser (used by the tests) doesn't support floating point numbers. The VM internal JSON parser should support floating point numbers.

**Comment by mhausner** [comment]
I think this bug refers to the json implementation that has since been removed, so it is no longer relevant.

Please close if that's the case.
