### ISSUE TITLE
[Heap] Add an ability to see merged retaining paths

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#19585]
It is an extremely useful feature, as it allows you to see on what to concentrate, or see memory information for the part of the system you care about.

---

**Attachment:**
[Screen Shot 2014-06-20 at 10.48.11 AM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-19585/comment-0/Screen Shot 2014-06-20 at 10.48.11 AM.png) (641.25 KB)

**Comment by rmacnak-google** [comment]
I believe this is what Observatory calls "Dominator tree (merged siblings by class)"
