### ISSUE TITLE
Dart_MessageNotifyCallback should return Dart_Handle

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#19647]
Since it is up to the implementer of this API to marshall the message to the correct isolate, it seems like it should be possible for the implementer to return an error.

**Comment by zanderso** [comment]
The callback passed to Dart_SetMessageNotifyCallback takes an isolate, which is the isolate that has messages ready for processing on its queue. It's up to the implementation to decide what to do with errors encountered while handling the messages, e.g. shutdown the offending isolate and print an error to the console.
