### ISSUE TITLE
HttpRequest.getString seems to be failing in IE

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#19664]
See e.g. http://chromegw.corp.google.com/i/client.dart/builders/dart2js-ie10-win8-html-be/builds/7681/steps/dart2js-ie10%20tests/logs/stdio

I'm getting errors, as in https://code.google.com/p/dart/issues/detail?id=8983

the logs are showing it as an error inside HttpRequest.getString, so that seems like a more general issue.

**Comment by Markzipan** [comment]
Closing this since IE is no longer supported by our web targets.
