### ISSUE TITLE
show allocation stack trace

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#19677]
**[user feedback]**

Checking the allocation profile of my application in the Dart observatory, I noticed that I allocate many instances of \_OneByteString. I'm not sure where in my application I do characher iterator. It would be usefull to see the stack trace of the allocations of a class, so I can track down what part of my code might be improved.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.5.0.dev_04_20 (2014-06-23)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_51
# projects: 5
# open dart files: 0
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1065 / 280 MB
thread count: 30
index: 1105514 relationships in 185403 keys in 1654 sources

SDK installed: true
Dartium installed: true

**Comment by turnidge** [comment]
This was implemented by @johnmccutchan.
