### ISSUE TITLE
Use list-package-dirs rather than symlinks in the analyzer

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#19742]
Pub is planning on no longer producing package symlinks (issue #15103), but currently the analyzer relies on these symlinks to resolve &quot;package:&quot; imports. Ultimately it would be good for the analyzer to look up packages through barback, but until then it should use &quot;pub list-package-dirs&quot; to find the dependency paths so pub can safely cease producing symlinks.

**Comment by sethladd** [comment]
Is this still required?

Tracking down everything we need for https://github.com/dart-lang/sdk/issues/24112

**Comment by pq** [comment]
Nope.  Closing out.  Thanks!
