### ISSUE TITLE
several analysis_server_tests are slow

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#19756]
analysis_server/test/domain_analysis_test is slow out on jsshell.

analysis_server/test/analysis_notification_outline_test is slow on d8
analysis_server/test/domain_search_test is slow on d8

**Comment by bwilkerson** [comment]
I believe that the problem is in the test framework, not the tests. If you disagree, please start an e-mail conversation with me.

**Comment by whesse** [comment]
Status lines labeled with this issue are now labeled with #26813 .
The analyzer is compiled by dart2js and tested only on a special dedicated bot, since the analyzer is not intended to be used that way.  These function mainly as stress tests on dart2js and the analyzer.
