### ISSUE TITLE
Isolate communication must be specified: which objects can be sent to which isolates.

### ISSUE THREAD

**Issue by clayberg** [dart-lang/sdk#19762]
**[user feedback]**

This doesn't happen in dartium, only JS, when using isolates

onError:Message serialization: Illegal value Instance of 'JobExecutor' passed

______
**Attachment:**
[screenshot (7).png](https://storage.googleapis.com/google-code-attachments/dart/issue-19762/comment-0/screenshot (7).png) (89.51 KB)

**Comment by lrhn** [comment]
I believe we now have consensus and matching implementations.

You can send "JSON-like" structures (Map<String,>, List, num, String, bool, null) plus `Capability`/`SendPort` to `spawnUri` isolates and any object except function closures to `spawn` isolates.
