### ISSUE TITLE
[Coverage] No coverage for simple "if" statements

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#19912]
---

main() {
&nbsp;&nbsp;getLength('abc');
}

int getLength(String str) {
&nbsp;&nbsp;if (str == null) {
&nbsp;&nbsp;&nbsp;&nbsp;return 0;
&nbsp;&nbsp;}
&nbsp;&nbsp;return str.length;
}

---

&nbsp;&nbsp;Produces hit map:

hits=[3,0,3,1,10,1]

&nbsp;&nbsp;As a result, I miss the fact that there is no test coverage for a very important null check.
&nbsp;&nbsp;I'd say it makes coverage report 40% less useful than it could be :-)

**Comment by liamappelbe** [comment]
Branch coverage will take care of this. I'm working on it at the moment. Tracking bug: https://github.com/dart-lang/coverage/issues/141
