### ISSUE TITLE
Assignability warnings are unreadable

### ISSUE THREAD

**Issue by clayberg** [dart-lang/sdk#19920]
Assignability warnings are unreadable, because the include the full path where the type is defined.

Showing the path should only be necessary if the two types have the exact same name AND their libraries have the exact same name. If only the type names are the same, prefixing with the library names is good enough.

If the path should always be printed, it should not be in the first sentence of the error message.

**Comment by srawlins** [comment]
Can we have an example of this?

**Comment by bwilkerson** [comment]
I believe that the error messages are better than when the issue was opened, so I'm going to close it. Please open a new issue if there is a specific case that should be looked at.
