### ISSUE TITLE
Add all dart binaries to bin dir in Debian package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#19926]
At the moment, it seems only `dart` is symlinked. We should include dart2js, pub, etc

**Comment by Scorpiion** [comment]
I just run into this as well, have always been using the manual install before. 

Maybe as a temporary workaround the package could print out a recommendation to add /usr/lib/dart/bin to the PATH during/after the installation? Or add the info on the [download page](https://www.dartlang.org/downloads/linux.html#install-with-apt-get) that you have to setup your path for pub to work.

**Comment by sethladd** [comment]
And another user brought this up in our Slack channel. Maybe we can take another look at this?

cc @whesse @mit-mit

**Comment by franklinyu** [comment]
Not familiar with Debian package system; does it allow packages to put things in `/etc/profile.d`?

**Comment by monsterddq** [comment]
You can see answer at here: https://stackoverflow.com/questions/28466798/how-to-install-pub-command-line-usage-for-dart-on-ubuntu-web-server

**Comment by Rodsevich** [comment]
Maybe having created some scripts in /usr/bin that inside them call the snapshots would do the trick?
like a 'pub' shell script that contains:
`/usr/bin/dart /usr/lib/dart/bin/snapshots/pub.dart.snapshot "$@"`

**Comment by maks** [comment]
What makes this confusing for a new user is that `dart` is symlinked into `/usr/bin` but others like `pub` is not and on the [SDK install webpage step 3](https://dart.dev/tutorials/server/get-started#3-get-more-command-line-developer-tools) recommends installing stagehand using pub without mentioning that its not added to the path while dart via its symlink is. Step 2 does say:
>As you install, note the path to the SDK. You’ll need it in the next step.
yet the next step makes no mention of it :-(

**Comment by parlough** [comment]
@mit-mit Is this good to close now that all tools intended to be user accessible are under the `dart` CLI tool?

There is the exception of `dartaotruntime`, but it's less commonly used and it's [documented](https://dart.dev/tools/dartaotruntime) as requiring the PATH addition.

**Comment by mit-mit** [comment]
Yeah, I think we're good now.

Wrt. `dartaotruntime` that is intentionally left stand-alone; the use case is for environments where the smallest possible runtime is desirable.
