### ISSUE TITLE
API Documentation: Example for HtmlDocument.registerElement is wrong

### ISSUE THREAD

**Issue by yutak** [dart-lang/sdk#19976]
https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html.HtmlDocument#id_registerElement

In the example, FooElement derives from HtmlElement and defines a regular
method called &quot;created&quot;, but this does not work, because:

\* Unnamed HtmlElement constructor can't be accessed from derived classes
&nbsp;&nbsp;(constructor necessary but super() doesn't work), and
* &quot;created&quot; is defined as a named constructor in HtmlElement.

I guess derived classes should define &quot;.created&quot; named constructor as well,
and the example should follow that pattern.

**Comment by srawlins** [comment]
Still true at HEAD. https://api.dartlang.org/dev/dart-html/HtmlDocument/registerElement.html

**Comment by kevmoo** [comment]
We're going to deprecate registerElement
