### ISSUE TITLE
make sure that top-level css is not inlined twice

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#19995]
Make sure that top-level css is not inlined twice. this is probably not a problem for link-rel elements inside &lt;template&gt; tags, but for &lt;link-rels&gt; that occur on the top of several imported files we are probably duplicating things.

**Comment by floitschG** [comment]
@sigmundch could you please triage this issue.

**Comment by sigmundch** [comment]
moved to https://github.com/dart-lang/polymer-dart/issues/516
