### ISSUE TITLE
Compiling a moderately sized program times out

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20031]
Programs (or tests) which include dart2js or the analyzer have a tendency to time out on the build bots when compiled by dart2js.

We should either:

\* make dart2js faster.

\* increase the default time out.

For example, compiling tests/try/poi/serialize_test.dart takes 30 seconds if you're lucky. If you're unlucky, it takes twice as long on the build bot (and times out). On the other hand, the test completes in less than a second on the VM.

**Comment by srawlins** [comment]
This test no longer exists, and a lot of work went into speed of the dart2js in 2018. @vsmenon, close this bug? Open a new bug with current information if speed of a specific action becomes an issue?

**Comment by vsmenon** [comment]
Yeah, let's close this.
