### ISSUE TITLE
Generate hint for missing @override

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#20098]
Generate hint for missing @­override
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.6.0.dev_03_00 (2014-07-10)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_51
# projects: 1
# open dart files: 4

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 512 / 224 MB
thread count: 44
index: [1764346 locations, 2227 sources, 126692 elements]

SDK installed: true
Dartium installed: true

**Comment by bwilkerson** [comment]
The lint rule `annotate_overrides` should be sufficient. Please re-open the issue if it is not.
