### ISSUE TITLE
dart2js: incorrect substitution for type parameter used by mixin

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#20113]
The last statement should print 'false' but it prints 'true'.

---

main() {
&nbsp;&nbsp;var a = 'Hello';
&nbsp;&nbsp;var c = a.codeUnits;
&nbsp;&nbsp;print(c);
&nbsp;&nbsp;print(c.runtimeType);
&nbsp;&nbsp;print(c is Iterable&lt;int&gt;);
&nbsp;&nbsp;print(c is Iterable&lt;String&gt;);

&nbsp;&nbsp;var s = c.skip(1);
&nbsp;&nbsp;print(s);
&nbsp;&nbsp;print(s.runtimeType);
&nbsp;&nbsp;print(s is Iterable&lt;int&gt;);
&nbsp;&nbsp;print(s is Iterable&lt;String&gt;);
}

---

It appears that there is something messed up the the type lookup substitution function.

ListMixin.skip does a lookup of H.getRuntimeTypeArgument(this, &quot;ListMixin&quot;, 0)

&nbsp;&nbsp;ListMixin: {
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;skip$1: function(_, count) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return H.SubListIterable$(this, count, null, H.getRuntimeTypeArgument(this, &quot;ListMixin&quot;, 0));
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;}

But there is no $asListMixin.  There is a mysterious $asObject_ListMixin, so it appears that the name of the mixin application is being used instead of the mixed-in class.

&nbsp;&nbsp;_CodeUnits: {
&nbsp;&nbsp;&nbsp;&nbsp;&quot;^&quot;: &quot;UnmodifiableListBase;_string&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;$asUnmodifiableListBase: function() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return [P.$int];
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;$asListBase: function() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return [P.$int];
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;$asObject_ListMixin: function() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return [P.$int];
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;$asIterable: function() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return [P.$int];
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}

**Comment by rakudrama** [comment]
@karlklose, this still repros.  Any ideas?

**Comment by johnniwinther** [comment]
The RTI system needs a (complete) rewrite. There are many errors in the internal model and the system only works now most of the time due to workarounds.

**Comment by karlklose** [comment]
I tried to find a small reproduction, but the system worked correctly with small examples, which may indicate that this problem is not a general one but related to special treatment of native classes.

**Comment by sigmundch** [comment]
@rakudrama fixed this when adding `getRuntimeTypeArgumentIntercepted`
