### ISSUE TITLE
Document error-handling in transformers

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#20171]
We've received feedback that it's difficult to know how to handle errors in pubspecs. It would be good if this were explained in the documentation.

There are two main ways of doing error-handling:

\* If there's an error in the transformer configuration, the constructor should detect it and throw an error. This error will be be printed in a nice format and associated with the configuration in question.

\* If an error occurs while processing an input, the transformer can either throw it as a normal exception or report it using `transform.logger.error`. Either of these will mark the transform as failing for that input. The latter is useful for reporting multiple errors for the same transform, or when associating an error with a specific location in an input.

**Comment by Aetet** [comment]
Hello. Do you have any examples about error handling in transformers? How to completely interrupt build process when any error occur?

**Comment by sethladd** [comment]
Should this be moved to barback?

**Comment by nex3** [comment]
@Aetet There's no way to *completely* interrupt the build process, but `pub build` will emit a failing exit code if any transformer fails.

@sethladd No, the high-level barback documentation is part of the main dartlang.org docs.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/www.dartlang.org#1472

**Comment by Aetet** [comment]
It's not completely true. Because if we have failing transformer which parse `.md` files and dart file with `main() {}` last transformer will be dart2js, which swallow exit code. If there's no dart file everythin' will be fine, and build will be interrupted with correct exit code.

**Comment by nex3** [comment]
I'm sorry, I can't really follow what you're saying. If you have a concrete reproduction where you're seeing a 0 exit code when errors happen, feel free to post it here.

**Comment by Aetet** [comment]
Here's an example:
https://github.com/Aetet/transformer-issue

**Comment by nex3** [comment]
@Aetet I can reproduce that. Can you file an issue against [pub](https://github.com/dart-lang/pub/issues/new)?
