### ISSUE TITLE
Local names should completely shadow library prefixes.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#20185]
Based on my understanding of how bug 18027 was resolved, I believe that this code:

&nbsp;&nbsp;import 'dart:async' as async;
&nbsp;&nbsp;class Foo {
&nbsp;&nbsp;&nbsp;&nbsp;var async;
&nbsp;&nbsp;&nbsp;&nbsp;bar({async.Completer foobar}) {}
&nbsp;&nbsp;}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;var foo = new Foo();
&nbsp;&nbsp;&nbsp;&nbsp;foo.bar();
&nbsp;&nbsp;}

should produce a warning in analyzer (probably something like &quot;Undefined class 'async.Completer'&quot;) because the class member &quot;async&quot; shadows the global meaning of &quot;async&quot; as a prefix for 'dart:async'.

Currently analyzer doesn't consider local names to shadow library prefixes when doing type lookup, so it considers &quot;async.Completer&quot; to refer to the Completer type in 'dart:async', and produces no warning.

**Comment by natebosch** [comment]
Interestingly it does have an unused import, but then does not produce a warning on the usage of the type.

CFE gives `Error: 'async.Completer' can't be used as a type because 'async' doesn't refer to an import prefix.`

**Comment by keertip** [comment]
Closing as stale.
