### ISSUE TITLE
dart2js should give better error message when encountering dart:io (or other server libraries)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#20195]
import 'dart:io';
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;stdout.writeln(&quot;Hello, world!&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;stdout.flush();
&nbsp;&nbsp;}

But it produces this error message:

&nbsp;&nbsp;Error: Library not found 'dart:io'.
&nbsp;&nbsp;import 'dart:io';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^
&nbsp;&nbsp;Error: Compilation failed.

The workaround can be --categories=Server, but this is not intuitive.

Suggestions:

A) just make it work without specifying the categories :)
B) When printing out the error, suggest to the user to use --categories=Server

Thanks!

**Comment by askeksa-google** [comment]
Dart2js now accepts `dart:io`, so this issue is no longer relevant.
