### ISSUE TITLE
Spec needs to allow "#void" for consistency with "const Symbol('void')"

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#20191]
In issue #19972, we decided that in spite of the fact that &quot;void&quot; is not a valid identifier, we should allow:

```dart
const Symbol('void')
```

and

```dart
new Symbol('void')
```

because the mirrors API has come to rely on the use of the `void` symbol to represent the name of the return type of a function returning void.

For consistency, I believe we should also change the spec to allow void as a symbol literal, i.e.:

```dart
#void
```

I propose to modify the grammar rule:

```
symbolLiteral:
  ‘#’ (operator | (identifier (‘.’ identifier)*))
  ;
```

To instead read:

```
symbolLiteral:
  ‘#’ (void | operator | (identifier (‘.’ identifier)*))
  ;
```

(Note that the vm, dart2js, and the analyzer all currently forbid `void` as a symbol literal).

**Comment by eernstg** [comment]
No milestone now: This will not block Dart 2.

We may still perform said adjustment.

**Comment by eernstg** [comment]
`#void` is supported today.
