### ISSUE TITLE
Dart2dart doesn't support 'dart:io'

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#20193]
In theory dart2dart should be able to handle programs that use 'dart:io', like this one:

&nbsp;&nbsp;import 'dart:io';
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;stdout.writeln(&quot;Hello, world!&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;stdout.flush();
&nbsp;&nbsp;}

But it produces this error message:

&nbsp;&nbsp;Error: Library not found 'dart:io'.
&nbsp;&nbsp;import 'dart:io';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^
&nbsp;&nbsp;Error: Compilation failed.

**Comment by aabluedragon** [comment]
Sorry for reviving an old thread, but where is dart2dart? I can't find it within the sdk directory.

**Comment by ricowind** [comment]
dart2dart has been removed, see:
https://groups.google.com/a/dartlang.org/forum/#!search/dart2dart$20%22last$20release$20that$20ships%22/announce/9RjS-euIyGg/BeB71uhrdv0J

**Comment by aabluedragon** [comment]
And `dart2js --output-type=dart` has been deprecated, do we have a replacement?

**Comment by zoechi** [comment]
`dart2js  - - output-type=dart` **is** dart2dart. There is no replacement.

**Comment by zoechi** [comment]
What do you need dart2dart for? You can take a look at https://pub.dartlang.org/packages/pubs if you want a self-contained deployable.

**Comment by aabluedragon** [comment]
For obfuscating dart server code (while making it a self-contained deployable), for running staging / production REST APIs on customer servers.

**Comment by zoechi** [comment]
I guess the closest you can get regarding obfuscation are snapshots https://www.dartlang.org/articles/snapshots/.

**Comment by aabluedragon** [comment]
I thought so, but then I saw [this, (see comment by Ladislav Thon)] (https://groups.google.com/a/dartlang.org/forum/#!topic/misc/FeSueoDBoYY).
That led me to conclude that running something like dart2dart before creating a snapshot would've been optimal, because if what he says is true (is it?), then all of my function names, variables and whatever keep their original name even in the snapshot.

**Comment by zoechi** [comment]
I haven't investigates snapshots, but if they contain the source code we're out of luck.

**Comment by zoechi** [comment]
Could be https://codereview.chromium.org/1290933002/
