### ISSUE TITLE
Links to dart:io, dart:core and dart:html on api.dartlang.org fronpage text not working

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#20254]
How to reproduce the problem:
Go to api.dartlang.org
Click on one of the dart:io, dart:core or dart:html links in the frontpage text near the top of the page (_not_ the links on the left)

What do you expect:
I am taken to the dart:io page

What do you see:
I am not taken anywhere (well, I am taken to the frontpage again)

**Comment by srawlins** [comment]
These work now.
