### ISSUE TITLE
Empty analysis root leads to confusing error message

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#20263]
When starting a dart process from a script (e.g. a bash wrapper), a user might reasonably write code like this:

&nbsp;&nbsp;dart --package-root=$PACKAGE_ROOT $DART_FILE

This works fine if $PACKAGE_ROOT is defined.  However if it is undefined, bash will &quot;helpfully&quot; replace $PACKAGE_ROOT with the empty string, resulting in

&nbsp;&nbsp;dart --package-root= $DART_FILE

This causes the VM to output the misleading error message:

&nbsp;&nbsp;Unrecognized flags: package-root

This is a really unfortunate user trap, because it misleads the user into thinking that they have used the wrong command-line flag to specify the package root, when in fact the real problem is that the package root is empty.  I stumbled into this trap yesterday and was very confused, and I just watched another developer stumble into it and experience the same confusion.

It would be nice if the VM could output an error message like this instead:

&nbsp;&nbsp;Error: empty package root

**Comment by mhausner** [comment]
CL https://codereview.chromium.org/2084553003/ fixes this.
