### ISSUE TITLE
SDK README: references to packages and util?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#20262]
Riffing off the change: https://code.google.com/p/dart/source/detail?r=38695

I just downloaded the latest be release.

There is no packages directory.
There is a util directory, but it's empty.

Room for more tweaks in the README file? Should that util directory be in the zip file?

**Comment by natebosch** [comment]
@kevmoo - which README?

Is this issue stale?

**Comment by kevmoo** [comment]
Yup. Stale. Looks like the changes are done.
