### ISSUE TITLE
vmservice tests fail to import observatory package on Windows

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#20298]
The following seems to be caused by Windows not handling the dart/pkg/observatory symlink:

FAILED: none-vm-checked release_x64 standalone/vmservice/allocations_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm\]:

stdout:
Uncaught Error: FileSystemException: Cannot open file, path = 'E:\b\build\slave\vm-win64-release-be\build\dart\build\ReleaseX64\packages\observatory\service_io.dart' (OS Error: The system cannot find the path specified.

, errno = 3)
Stack Trace: 
#­0      \_File.open.&lt;anonymous closure&gt; (dart:io/file_impl.dart:349)
#­1      \_RootZone.runUnary (dart:async/zone.dart:1088)
#­2      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#­3      \_Future._propagateToListeners (dart:async/future_impl.dart:571)
#­4      \_Future._completeWithValue (dart:async/future_impl.dart:331)
#­5      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:393)
#­6      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#­7      \_asyncRunCallback (dart:async/schedule_microtask.dart:32)
#­8      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:126)

**Comment by turnidge** [comment]
Obsolete bug.
