### ISSUE TITLE
Hint when type of element in list literal does not match variable type in assignment statement

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#20297]
There is no warning here ...

&nbsp;&nbsp;&nbsp;List&lt;String&gt; list = [ new SomeClass() ];

... but when I refactor it, the warning appears ...

&nbsp;&nbsp;&nbsp;List&lt;String&gt; list = [];
&nbsp;&nbsp;&nbsp;list.add(new SomeClass());  // &lt;&lt;&lt; warning argument type 'SomeClass' not assignable to 'String'

It would be helpful if there was at least a hint in the former case so that I catch problem code earlier.

**Comment by srawlins** [comment]
This hint exists in Strong mode. https://dartpad.dartlang.org/63e755de5d8d5afe4fb8b5b1d65c4dc3
