### ISSUE TITLE
dart2js: compiler crash on closure over type variable

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#20359]
--------
main() {
&nbsp;&nbsp;var a = new X&lt;String&gt;();
&nbsp;&nbsp;var q = a.make();
&nbsp;&nbsp;print('q is List&lt;String&gt;  ${q is List&lt;String&gt;}');
&nbsp;&nbsp;print('q is List&lt;int&gt;     ${q is List&lt;int&gt;}');
}

class X&lt;T&gt; {
&nbsp;&nbsp;get make =&gt; () =&gt; &lt;T&gt;[];
}

--------
$ sdk/bin/dart2js_developer ~/play1/bug6i2m3.dart
/home/sra/play1/bug6i2m3.dart:9:7:
Internal Error: Cannot find value Instance of 'ThisLocal'.
&nbsp;&nbsp;get make =&gt; () =&gt; &lt;T&gt;[];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

\* the name and version of your operating system,

\* the Dart SDK build number (build number could not be determined), and

\* the entire message you see here (including the full stack trace
&nbsp;&nbsp;below as well as the source location above).

The compiler crashed: Internal Error: Cannot find value Instance of 'ThisLocal'.
#­0      Compiler.internalError (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:999:5)
#­1      LocalsHandler.readLocal (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:372:41)
#­2      LocalsHandler.readThis (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:409:33)
#­3      SsaBuilder.readTypeVariable (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:3877:49)
#­4      SsaBuilder.addTypeVariableReference (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:3937:32)
#­5      SsaBuilder.analyzeTypeArgument (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:3973:38)
#­6      SsaBuilder.setRtiIfNeeded (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:4983:40)
#­7      SsaBuilder.visitLiteralList (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:5005:35)
#­8      LiteralList.accept (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/tree/nodes.dart:941:54)
#­9      SsaBuilder.visit (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:2343:34)
#­10     SsaBuilder.visitReturn (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:4935:12)
#­11     Return.accept (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/tree/nodes.dart:1028:49)
#­12     SsaBuilder.buildMethod (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:1456:25)
#­13     SsaBuilderTask.build.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:44:38)
#­14     Compiler.withCurrentElement (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:800:15)
#­15     SsaBuilderTask.build.&lt;anonymous closure&gt; (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:32:41)
#­16     CompilerTask.measure (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1966:37)
#­17     SsaBuilderTask.build (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/ssa/builder.dart:30:19)
#­18     JavaScriptBackend.codegen (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/js_backend/backend.dart:1085:33)
#­19     Compiler.codegen (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1628:20)
#­20     CodegenWorkItem.run (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:181:21)
#­21     Compiler.processQueue.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1523:54)
#­22     Compiler.withCurrentElement (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:800:15)
#­23     Compiler.processQueue.&lt;anonymous closure&gt; (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1523:25)
#­24     QueueFilter.processWorkItem (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/enqueue.dart:872:6)
#­25     Enqueuer.forEach (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/enqueue.dart:608:31)
#­26     Compiler.processQueue (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1522:18)
#­27     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1458:17)
#­28     Compiler.runCompiler.&lt;anonymous closure&gt; (file:///usr/local/google/home/sra/dart-all/dart/sdk/lib/_internal/compiler/implementation/compiler.dart:1306:31)
#­29     \_RootZone.runUnary (dart:async/zone.dart:1082)
#­30     \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#­31     \_Future._propagateToListeners (dart:async/future_impl.dart:571)
#­32     \_Future._completeWithValue (dart:async/future_impl.dart:331)
#­33     \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:393)
#­34     \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:32)
#­35     \_asyncRunCallback (dart:async/schedule_microtask.dart:39)
#­36     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:126)

sra@sra-z620:~/dart-all/dart (master)$

**Comment by sigmundch** [comment]
this issue seems now fixed (tested on 1.13.0-dev.2.0)
