### ISSUE TITLE
Using show/hide with an identifier not exported by the library should give a warning.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#20363]
If you do any of:  
&nbsp;&nbsp;import &quot;foo.dart&quot; show notThere;
&nbsp;&nbsp;import &quot;foo.dart&quot; hide notThere;
&nbsp;&nbsp;export &quot;foo.dart&quot; show notThere;
&nbsp;&nbsp;export &quot;foo.dart&quot; hide notThere;
where &quot;notThere&quot; is not in the exported identifiers of the library &quot;foo.dart&quot;, there is no warning, or even a hint.

It might be reasonable to give such a warning.
If we don't want to change the spec on this, the analyzer/editor could give a hint.
I'm filing this under the analyzer for now, but we could upgrade it to Area-Language if it should be a warning.

**Comment by BlackHC** [comment]
Would it be possible to add support for this to the analyzer soon please? We (AWV) are reluctant to use show/hide at all as long as there is no support whatsoever for determining when show/hide identifiers are stale.

The feature would become usable for us, once we get at least a hint about when these statements need to be updated.

Regarding the spec: "Note that no errors or warnings are given if one hides or shows a name that is
not in a namespace. This prevents situations where removing a name from a
library would cause breakage of a client library."

I can see why you don't like an error here, but the distinction of warning vs hint for this is not very clear. I see no reason why this cannot be a static warning.

Especially given that you can export undefined symbols, too, this can lead to hard to spot issues.

**Comment by srawlins** [comment]
CR out for review: https://codereview.chromium.org/1901923002/

**Comment by BlackHC** [comment]
Awesome, thanks for looking into this!

**Comment by srawlins** [comment]
New analyzer hints UNDEFINED_SHOWN_NAME, and UNDEFINED_HIDDEN_NAME in 53bf36acdb4a6a12addf15eba06eacdab7552f22.
