### ISSUE TITLE
Move Dart's DEPS into the Dart repo

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#20370]
Currently having the DEPS outside of the repo adds unnecessary overhead to changes since it needs to be done from a separate enlistment.

Also, I'm not sure if this can be done at the same time (or if it is even logical), but could the dart folder within bleeding edge be removed as well?

The issue is that it prevents git-based dependencies from having the same folder structure as svn-based dependencies. For example, a DEPS for Dart is normally along the lines of:
deps = {
&nbsp;&nbsp;'src/dart':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'https://dart.googlecode.com/svn/branches/bleeding_edge/dart@38520'
}

The closest git dependency would be:
deps = {
&nbsp;&nbsp;'src/dart':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'https://chromium.googlesource.com/external/dart/bleeding_edge.git@ae863...'

But the resulting Dart code is nested one folder deeper in the tree (under src/dart/dart rather than src/dart).

Having the git dependency is desirable here as it allows easy migration of patches between enlistments (and is a step towards a single source control system).

**Comment by whesse** [comment]
This is all done, as part of the move to a git repo.
