### ISSUE TITLE
Infinite future chain exhaust memory

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20383]
This program will eventually lead to an OOM error:

import 'dart:async';

producer() {
&nbsp;&nbsp;return new Future(() =&gt; null);
}

main() {
&nbsp;&nbsp;repeat(null);
}

repeat(_) =&gt; producer().then(repeat);

We have discussed a possible strategy that could prevent that.

**Comment by lrhn** [comment]
With revision ed0bc4315832315c766, the program now runs without leaking on the VM.
