### ISSUE TITLE
Tutorial sample Its_all_about_you not working

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#20390]
Dart Editor version 1.6.0.dev_07_00 (DEV)
Dart SDK version 1.6.0-dev.7.0

The its_all_about_you sample is not working.

Repro:
Download latest dart-tutorials-samples-master.zip, unpack.
Start Dart Editor with a clean workspace and open its_all_about_you from the samples
Click the Run button

Expected:
The browser displays a page that looks like the example from the dartlang.org tutiroals web page

Observed:
The browser displays an empty page. The editor has a message:
Uncaught ReferenceError: Platform is not defined (http://localhost:8080/packages/polymer/src/js/polymer/polymer.js:12)

**Comment by srawlins** [comment]
This sample has been re-written, and does  not use Polymer any longer.
