### ISSUE TITLE
Add a strict type checking mode

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#20443]
There have been a number of requests recently (many on the mailing lists) to have a strict type checking mode that acts as if Dart had a sound type system. I'm creating this issue to give people a single place to record their interest, and as a blocking issue for more specific requests related to how such a mode should operate.

**Comment by pankleks** [comment]
Well I'm new in Dart and I just discovered that - I agree with run-time approach, but IMO lack of such warnings at compilation time - well at least for me it's kind of show stopper.

I see it's P2 - medium - but it looks like 2 years after not much has moved. Any updates on that?

**Comment by a14n** [comment]
See https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md .

There are several ways to activate it :
- with `dartanalyzer --strong`
- with a `.analysis_options` file (at the root of your project) containing :

  ```yaml
  analyzer:
    strong-mode: true
```

- in [DartPad](https://dartpad.dartlang.org/) with the checkbox in the right lower corner.

**Comment by bwilkerson** [comment]
Yes, strong mode is the answer to these requests, so I'm closing this issue.

**Comment by pankleks** [comment]
Thanks - much much better!:)

Question - apart from all good hints I get one which I don't understand.

```dart
class A<T extends Node> {
  T element;
  A(this.element);
}

class B<T extends HtmlElement> extends A<T> {
  B(HtmlElement element) : super(element);
}
```
At B constructor I got warning:
WARNING: Unsound implicit cast from HtmlElement to T

IMO above construction is right.


Side question - I'm trying to learn Dart using material on the web - however more detailed knowledge I look for I'm finding more and more out of date articles (including official ones) - what is the most up to date reference?

**Comment by bwilkerson** [comment]
At the point of `B`'s constructor all we know is that `element` is some kind of `HtmlElement`. But the super constructor is expecting it to be a `T` (which could be any subclass of `HtmlElement`. There's no guarantee that the actual argument is of the right subclass. What you really want is

```
B(T element) : super(element);
```

@Sfshaza Can you address the question about documentation?
