### ISSUE TITLE
Snapshot startup is too slow

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#20470]
In my tests on pub, it takes on the order of 100ms for the main() to begin executing when running from a snapshot. This is a very long time for just startup, especially since it's a snapshot and as such there's no additional parsing that needs to occur. As we're trying to get the runtime of &quot;pub run&quot; down, this will become more and more of an issue.

**Comment by zanderso** [comment]
It looks like the pub snapshot has grown to ~4.8MB which likely increases loading time.

**Comment by rmacnak-google** [comment]
Stale.  App-jit and app-aot snapshots are recommended where startup time is a concern.

https://github.com/dart-lang/sdk/wiki/Snapshots

**Comment by nex3** [comment]
@rmacnak-google Do app-aot snapshots have competitive runtime performance with code snapshots, or do they lose out because they don't get JITed? If we have to choose between slow startup and slow runtime, our problem isn't really solved.

**Comment by zoechi** [comment]
According to https://github.com/dart-lang/sdk/wiki/Snapshots snapshots get a training run with `--snapshot-kind=app-jit`

**Comment by nex3** [comment]
That's true for app-jit snapshots, but I'm not sure how you'd construct an effective training run for an application like pub that has many different commands that all execute different code paths. And a training run just isn't possible in general for some of our snapshot use-cases, such as generating snapshots of user executables for use by `pub run`.

**Comment by zanderso** [comment]
Even very simple training runs manage to pick up a lot of start up code, which allows for fast startup when running from the app-jit snapshot.

When running from an app-jit snapshot, JIT compilation and optimization are still possible, which means we still get good peak performance.

**Comment by nex3** [comment]
But what about situations (like `pub run`) where the executables are total black boxes, and we don't know *any* way to safely invoke them to do a training run?

**Comment by zanderso** [comment]
I think I might not be completely understanding your concern. However, you may be underestimating the amount of code that we have to compile and run just to get to `main()` and do e.g. command line argument parsing and printing some strings. Getting all of that code compiled in the app-jit snapshot has proved to be very beneficial.

Either way, it's certainly possible to come up with application-appropriate training runs by modifying e.g.:  https://github.com/dart-lang/sdk/blob/master/utils/pub/BUILD.gn#L7 but you have to keep in mind that there is a trade-off with size. As you add more code to the snapshot, there will be diminishing returns to startup performance.
