### ISSUE TITLE
Argument type mismatch hint is incomplete

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#20497]
Given the following code:

class F {
&nbsp;&nbsp;void call(int x, String y) {
&nbsp;&nbsp;}
}

main() {
&nbsp;&nbsp;var function = null as F;
&nbsp;&nbsp;function('', [2]);
&nbsp;&nbsp;function.call('', [2]);
}

Analyzer will hint (HintCode.ARGUMENT_TYPE_NOT_ASSIGNABLE) on the line with &quot;.call(&quot; that the argument types do not correspond to the parameter types, but will not hint on the line above. It should hint on both lines.

**Comment by parlough** [comment]
This has been fixed somewhere along the line:

<img width="380" alt="Screen Shot 2019-05-16 at 17 09 09" src="https://user-images.githubusercontent.com/18372958/57890532-8d25b280-77fd-11e9-89c9-78ff596fe8c0.png">
<img width="235" alt="Screen Shot 2019-05-16 at 17 09 54" src="https://user-images.githubusercontent.com/18372958/57890535-8eef7600-77fd-11e9-8f83-d265a58d8bd9.png">

**Comment by srawlins** [comment]
Hooray!
