### ISSUE TITLE
Print from isolate

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#20492]
**[user feedback]**

can we at least get a debug_print which works from isolates?

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.5.8.release (2014-07-29)
OS: Windows 8.1 - amd64 (6.3)
JVM: 1.8.0_11
# projects: 1
# open dart files: 6

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 369 / 189 MB
thread count: 29
index: [469357 locations, 296 sources, 29452 names]

SDK installed: true
Dartium installed: true

**Comment by floitschG** [comment]
Printing in isolates should work now.
