### ISSUE TITLE
tests_html_datalistelement_test is crashing in debug mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#20540]
/workspace/asiva/dartium-tot/src/out/Debug/content_shell --no-timeout --dump-render-tree 'http://127.0.0.1:33073/root_build/generated_tests/none-drt/tests_html_datalistelement_test/test.html?crossOriginPort=53524'

fails in debug mode.

ASSERTION FAILED: !NoEventDispatchAssertion::isEventDispatchForbidden()
../../third_party/WebKit/Source/core/dom/Node.cpp(2223) : void WebCore::Node::dispatchSubtreeModifiedEvent()
1   0x1dee74a
2   0x1db5cad
3   0x1db24ef
4   0x1dbc151
5   0x1dadc67
6   0x215587b
7   0x20ed746
8   0x2025660
9   0x20260a6
10  0x1eacbd8
11  0x1e47031
12  0x1e4548f
13  0x1dbc96d
14  0x1daf505
15  0x1d46ab3
16  0x1d46983
17  0x1d48c80
18  0x1d464ca
19  0x1de7e95
20  0x321e7ef
21  0x5cf8d56
22  0x7fb71ad0d3f7
Received signal 11 SEGV_MAPERR 0000fbadbeef
# ­0 0x0000007d0a4d base::debug::StackTrace::StackTrace()
# ­1 0x0000007d0379 base::debug::(anonymous namespace)::StackDumpSignalHandler()
# ­2 0x7fb716d23cb0 &lt;unknown&gt;
# ­3 0x000001dee754 WebCore::Node::dispatchSubtreeModifiedEvent()
# ­4 0x000001db5cad WebCore::Element::didAddAttribute()
# ­5 0x000001db24ef WebCore::Element::appendAttributeInternal()
# ­6 0x000001dbc151 WebCore::Element::setAttributeInternal()
# ­7 0x000001dadc67 WebCore::Element::setAttribute()
# ­8 0x00000215587b WebCore::TextControlInnerContainer::create()
# ­9 0x0000020ed746 WebCore::TextFieldInputType::listAttributeTargetChanged()
# ­10 0x000002025660 WebCore::HTMLInputElement::listAttributeTargetChanged()
# ­11 0x0000020260a6 WebCore::ListAttributeTargetObserver::idTargetChanged()
# ­12 0x000001eacbd8 WebCore::IdTargetObserverRegistry::notifyObserversInternal()
# ­13 0x000001e47031 WebCore::IdTargetObserverRegistry::notifyObservers()
# ­14 0x000001e4548f WebCore::TreeScope::addElementById()
# ­15 0x000001dbc96d WebCore::Element::updateId()
# ­16 0x000001daf505 WebCore::Element::insertedInto()
# ­17 0x000001d46ab3 WebCore::ContainerNode::notifyNodeInsertedInternal()
# ­18 0x000001d46983 WebCore::ContainerNode::notifyNodeInserted()
# ­19 0x000001d48c80 WebCore::ContainerNode::updateTreeAfterInsertion()
# ­20 0x000001d464ca WebCore::ContainerNode::appendChild()
# ­21 0x000001de7e95 WebCore::Node::appendChild()
# ­22 0x00000321e7ef WebCore::DartNodeInternal::appendChildCallback()
# ­23 0x000005cf8d56 dart::NativeEntry::NativeCallWrapper()
# ­24 0x7fb71ad0d3f7 &lt;unknown&gt;

&nbsp;&nbsp;r8: 00007fb71aeb1980  r9: 00007fb71aeed0d0 r10: 0000000000000001 r11: 0000000000000000
&nbsp;r12: 0000000002006c02 r13: 00007fb70de19c51 r14: 000023650687f020 r15: 00007fb70de19c51
&nbsp;&nbsp;di: 0000000000000000  si: 00000000efcdab90  bp: 00007fff7e8bcfd0  bx: 000023650671f4e0
&nbsp;&nbsp;dx: 00007fb715ea7aa0  ax: 00000000fbadbeef  cx: ffffffffffffffff  sp: 00007fff7e8bcf40
&nbsp;&nbsp;ip: 0000000001dee754 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000006
&nbsp;trp: 000000000000000e msk: 0000000000000000 cr2: 00000000fbadbeef
# CRASHED - renderer (pid 28775)

Content-Type: text/plain
# CRASHED - renderer (pid 28775)

**Comment by terrylucas** [comment]
Works just like dart2js (JS now with JSInterop).  Doesn't use Dart's C++ wrapper function.
