### ISSUE TITLE
Server should report errors rather than crashing when the SDK is invalid

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#20562]
The analysis server should verify that the path passed in on the command-line is valid. If not, it should report a fatal error and shutdown. This behavior should be documented in the spec.

However, it should be tolerant of having a directory separator at the end of the passed in path.

See https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/7NL4L4blLZg for additional information.

**Comment by srawlins** [comment]
`dart analyze` is tolerant of trailing slashes, and reports errors when a path is invalid. I'll close this as fixed.

```none
$ dart analyze pkg/dartdev
Analyzing dartdev...                   15.7s
No issues found!
$ dart analyze pkg/dartdev/
Analyzing dartdev...                   3.5s
No issues found!
$ dart analyze pkg/dartde
Directory or file doesn't exist: pkg/dartde

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```
