### ISSUE TITLE
Incorrect hint from analyzer

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20579]
[hint] The argument type 'CapturedVariable' cannot be assigned to the parameter type 'Element' (.../dart/sdk/lib/_internal/compiler/implementation/inferrer/simple_types_inferrer.dart, line 469, col 36)

The above hint isn't correct. The code is untyped, and there exist types that implement both Element and CapturedVariable.

**Comment by pq** [comment]
Assumed stale.
