### ISSUE TITLE
pkg/analysis_server/test/integration/analysis/update_content_test times out on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#20575]
The test pkg/analysis_server/test/integration/analysis/update_content_test is timing out on Windows on the buildbots.  Skipping for now.

**Comment by bwilkerson** [comment]
I believe that the problem is in the test framework, not the tests. If you disagree, please start an e-mail conversation with me.

**Comment by ricowind** [comment]
I don't know if this is a problem in the test framework or not, but for completeness could you elaborate on _what_ you think the problem is?

**Comment by whesse** [comment]
I believe that the test.py scripts had a timeout of 1 minute, and many analysis server tests are long-running.  We increased the timeout to 3 or 5 minutes, for this particular test suite, so the problem should be resolved.  The flaw was not in the framework, but in our assumptions about how people would be using it.  We assumed lots of small tests, in separate files. Some users want to put all tests in one large file.
