### ISSUE TITLE
Consider rewording hint about "the scope for promotion"

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20600]
I noticed this hint message:

p/try/poi/diff.dart:115:7:
Hint: Variable 'before' is not known to be of type 'VariableElementX' because it is potentially mutated in the scope for promotion.
&nbsp;&nbsp;if (before is modelx.VariableElementX) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p/try/poi/diff.dart:116:5:
Info: Variable 'before' is potentially mutated here.
&nbsp;&nbsp;&nbsp;&nbsp;before = before.variables;
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^

I don't believe that it is clear from the context what &quot;the scope for promotion&quot; refers to.

Also, I'd argue that there's nothing &quot;potential&quot; about this. So I'd remove that qualifier as well.

**Comment by srawlins** [comment]
I don't think dart2js generates error messages like this any more. I cannot grep anything ...
