### ISSUE TITLE
Analyzer should hint on list assignment that is guaranteed to fail in checked mode

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#20610]
The following code produces no errors, warnings, or hints in analyzer:

&nbsp;&nbsp;class A {}
&nbsp;&nbsp;class B extends A {}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;List&lt;B&gt; listOfB = &lt;A&gt;[];
&nbsp;&nbsp;&nbsp;&nbsp;print(listOfB);
&nbsp;&nbsp;}

However, executing it in the VM (in checked mode) produces this error:

&nbsp;&nbsp;type 'List&lt;A&gt;' is not a subtype of type 'List&lt;B&gt;' of 'listOfB'.

It seems like analyzer should produce a hint for this.

**Comment by srawlins** [comment]
This exists in Strong Mode: https://dartpad.dartlang.org/704e735a6a77dc82fc0277c0679c36b6

> error: Type check failed: <A> [] (List<A>) is not of type List<B>
