### ISSUE TITLE
in the dartium repl, can't use private vars from other libraries

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#20622]
at a breakpoint in library A, i want to be able to use private vars from library B.
i can see them, taunting me inside the console output.  e.g.
i type foo and hit enter at the repl and it shows me the foo object and i can inspect
its various parts by clicking on the triangle flippies.
one of foo's fields is _bar, which happens to be a List.
ok, what's in that List?  well, i can see it toString'ed, but i want to probe deeper,
e.g. i might want to test &quot;foo._bar[0] is Baz&quot;.
i can try to click around, but i can't see anything _inside_ the List.
maybe the data is hidden beyond some c++ barrier - who knows?
but even if not, i shouldn't have to navigate through the implementation details of List.
i just want to do stuff like foo._bar[0], which currently is forbidden.

&lt;rant&gt;
this seems silly.  if these things are so private, why show them to me in the first place?
and i'm at the debugger.  i don't need to be nannied.
give me the power, i accept the consequences.
this seems to serve no purpose but slow down my debugging.
&lt;/rant&gt;

btw, this is similar to bug 13811, but i think different in that that bug i don't think was
asking for an escalation of privilege inside the debugger.

chrome 36.0.1985.97 (Developer Build 280598)

**Comment by yjbanov** [comment]
+1

**Comment by tbosch** [comment]
+1

**Comment by zoechi** [comment]
+1
