### ISSUE TITLE
event.detail is incorrect and inconsistent between dart2js and dartium

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#20648]
If the event contains a JSON object containing a proxy to a Dart object, the result:
&nbsp;\- is null in dartium, but not null in JS.
&nbsp;\- in JS it returns an map containing the JsObject for the proxy, rather than the unwrapped object.

Here is a simple example that can repro this problem:

&lt;body&gt;
&nbsp;&nbsp;&lt;script&gt;
&nbsp;&nbsp;function fire(item)  {
&nbsp;&nbsp;&nbsp;&nbsp;var event = new CustomEvent('my-event', {detail: {item: item}});
&nbsp;&nbsp;&nbsp;&nbsp;document.body.dispatchEvent(event);
&nbsp;&nbsp;}
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script type=&quot;application/dart&quot; src=&quot;index.dart&quot;&gt;&lt;/script&gt;
&nbsp;&nbsp;&lt;script src=&quot;packages/browser/dart.js&quot;&gt;&lt;/script&gt;

index.dart:

&nbsp;&nbsp;import 'dart:html';
&nbsp;&nbsp;import 'dart:js';
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;document.body.on['my-event'].listen((e) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (e.detail != null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var d = e.detail[&quot;item&quot;];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('0: ${d}, type: ${d.runtimeType}');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('0: null');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var d = new JsObject.fromBrowserObject(e)['detail']['item'];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('1: $d, type: ${d.runtimeType}');
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;context['fire'].apply([new _Foo()]);
&nbsp;&nbsp;}
&nbsp;&nbsp;class _Foo { int id = 3; }

In dartium, this prints '0: null', in dart2js it prints '0: [object Object], type: JSObject ', where the object happens to be the JsObject proxy for _Foo

The second line prints the same result in both: `1: Instance of '_Foo', type: \_Foo`. I expect there result to always be like this line. 

This is related to bug 19315, but I'd like to make sure we track separately the inconsistency between the two implementations today.

**Comment by matanlurey** [comment]
Dartium is no longer supported.
