### ISSUE TITLE
Can't copy allocation profile

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20653]
In the VM observatory, the allocation profile cannot be copied because class names are in the shadow DOM.

So if you attempt to copy the information, you only get a list of numbers, without class names.

**Comment by rmacnak-google** [comment]
@B3rn475 Fixed by recent changes to the allocation profile?

**Comment by B3rn475** [comment]
You can now download the current allocation profile with the "download" button in the menu
