### ISSUE TITLE
IE11 versions on Windows 7 and Windows 8 behave differently

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#20659]
These tests started working on IE11 Windows 8 but not on Windows 7:
&nbsp;&nbsp;html/worker_test/functional
&nbsp;&nbsp;html/transferables_test
This test started failing  on IE11 Windows 8 but not on Windows 7:
&nbsp;&nbsp;html/node_validator_test

**Comment by rakudrama** [comment]
I'm not sure this issue is 'stale'.
We still support IE11
Microsoft still supports Windows 7.1 (extended support until 2020) and Windows 8 (until 2023).

**Comment by whesse** [comment]
We are shutting down testing on windows 8, and replacing it with Windows 10 testing.  Windows 8 use is small and declining.  It is much more important to get Windows 10 IE and edge browser testing running.
