### ISSUE TITLE
Need better control of Observatory output

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#20664]
**[user feedback]**

Username: kasperl

When running command line apps from within the editor, I find it somewhat annoying that the Observatory always prints a line to the console. It feels distracting that it interferes with the output of my app -- and that I have no reasonable way of making it stop (apart from disabling the observatory functionality).

Maybe the editor could surface this information differently? Maybe the VM could write the information somewhere else -- or only do it on demand when the VM process is sent a specific signal?
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.6.0.dev_09_06 (2014-08-21)
OS: Mac OS X - x86_64 (10.9.2)
JVM: 1.6.0_65
# projects: 3
# open dart files: 3
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1996 / 254 / 77 MB
thread count: 44
index: [574904 locations, 300 sources, 36024 elements]

SDK installed: true
Dartium installed: true
______
**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-20664/comment-0/screenshot.png) (151.70 KB)

**Comment by turnidge** [comment]
This output looks like it is gone now, when running a command line app with the --observe or --enable-vm-service flag.  Closing.
