### ISSUE TITLE
pkg/math remove null checks or provide helpful messages to ArgumentError

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#20778]
In general we don't explicitly check for null in library methods.

If we do check args, though, the 'message' param to ArgumentError should be helpful. A null 'message' won't help the user of the function

**Comment by floitschG** [comment]
@Kevmoo please triage this issue.
There is no Pkg-Math label, and the pkg directory does not seem to contain a 'math' directory.
I don't know where the sources for the math package are located.

**Comment by kevmoo** [comment]
Not sure what's going on here...
