### ISSUE TITLE
compute closure classes eagerly after resolution

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#20791]
We currently compute closure classes to represent closures lazily. However, as the type inferrer looks at each closure, we end up computing all closure classes anyway. It would be cleaner to have a clear point, e.g. directly after resolution, where these are computed. This would for instance allow the computation of reflectable members to include closure classes directly, rather than adding them later in an ad-hoc fashion.

**Comment by sigmundch** [comment]
I believe we've done so since we migrated to the CFE.
