### ISSUE TITLE
Build: add SHA-256 checksum for Editor downloads

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#20847]
Adding SHA-256 sums for the downloads was mostly done for Issue #20355, but there are not SHA-256 sums for the Editor downloads: http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/editor/

These should be added.

**Comment by srawlins** [comment]
Editor is dead. Thus, this issue is dead?

**Comment by sethladd** [comment]
yup!
