### ISSUE TITLE
A way of examining the pending futures/task queue in Observatory

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#20857]
I find myself with the situation that my short-lived server testing program runs correctly, but after I think everything ought to be shut down it waits roughly 5 seconds before terminating. It's difficult to do a lot of observing in five seconds, but it appears that the program is completely idle and presumably there's a timeout or a timed future that's pending.

I wish Observatory could tell me something about the futures that are pending, and possibly about the state of the event queue (but that's probably not very useful except when the VM is paused).

**Comment by johnmccutchan** [comment]
You can now find all open Isolate message ports (these keep isolates alive) in Observatory.

You can also see the pending message queue in Observatory's debugger.
