### ISSUE TITLE
Add custom resolver argument to standalone VM

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#20866]
I couldn't find a tracking bug for this. If there is one, feel free to merge this.

In our meeting last week, the VM team agreed to add an optional argument to the VM to enable custom URL resolving. Natalie has a document that proposes precise details on how that could work, but we're open to discussing that.

Our agreement was that this would land in 1.7, so setting that here.

**Comment by rmacnak-google** [comment]
We've gone with package maps instead.
