### ISSUE TITLE
Incorrect ARGUMENT_TYPE_NOT_ASSIGNABLE from analyzer 

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20883]
&nbsp;&nbsp;String positionString;
&nbsp;&nbsp;int position = int.parse(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;positionString, onError: (_) =&gt; print('Please enter an integer.'));

Gives:

ARGUMENT_TYPE_NOT_ASSIGNABLE
The argument type '(dynamic) → void' cannot be assigned to the parameter type '(String) → int'

That's not correct, as I haven't written void anywhere.

**Comment by munificent** [comment]
Closing this. We're OK with using type inference to determine the return type of a lambda based on its body. Users expect it, and it's important for making generic methods useful.

**Comment by peter-ahe-google** [comment]
When you use phrases like "users expect it", please cite the user studies you've performed to back up such claims.

**Comment by munificent** [comment]
You're assuming formal user studies are the only mechanism for acquiring any information on what users expect. That's a false assumption.

**Comment by peter-ahe-google** [comment]
I simply assumed that you weren't making assumptions about what users "expect". Based on that, I could only assume you had some data to back up your claims.

However, since you don't have data to back up your claims, and it would be counter-productive for me to claim the opposite was a fact (also without backing up my claims), could you please refrain from insinuating that you *know* what users expect?

Try to use phrases like, "I think that users expect". This way we can clearly tell the difference between when a decision is made on facts or when its made based on assumptions that aren't backed by facts.

Also, if you think something is a bad idea or a waste of time, please say so. If you're making a judgement call, please say so.

**Comment by munificent** [comment]
> Based on that, I could only assume you had some data to back up your claims.

I *do* have data to back that claim up:

* I have been interacting with Dart users for years and have seen piles of email from them expecting type inference to kick in. This is both on the public mailing list, internal users, private communication, etc.

* Strong mode does this inference, and we have watched users go through migration and see that it does not cause problems. We also get a lot of positive feedback from them about the inference. The fact that users *choose* to adopt strong mode at all carries signal that more inference is what they want.

* Other languages that have static type systems and lambdas do this same inference. Users coming from these languages will carry that expectation, and the designers of those languages presumably have some expertise at what they're doing.

Earlier, you asked about *user studies*. No, I have not conducted user studies on this particular feature. As you know, doing so wouldn't be cost effective. That does *not* mean I don't have any information whatsoever about its usability.

> could you please refrain from insinuating that you know what users expect?

I am not insinuating. I am *claiming*, yes, overall, roughly, this is the aggregate expectation of most of the user that we are targeting. I hope that most charitable readers understand that if I say, "People like vanilla ice cream" I don't literally mean *every person* likes it, but that I do mean "I feel that it's a safe bet that most do."

> Try to use phrases like, "I think that users expect". 

Yes, I will do that. Sorry. I've been grinding through a lot of issues, so some of my comments were a little terse.

> Also, if you think something is a bad idea or a waste of time, please say so. If you're making a judgement call, please say so.

I'm not sure what you mean by "bad idea or waste of time". Ideas are good or bad based on the context where they're applied and whether or not something is a waste of time depends a lot on how much time you have. I don't think this feature is *a priori* a bad idea or waste of time. I just don't think it's a good fit for Dart and the kinds of users we're focused on.

That is a judgement call, I guess. I'll try to be more explicit about that. Though, note that in this issue, my "judgement" is really "what all of our tools are already doing and people seem to be fine with." The only "call" I'm making here is that small corner of our static analysis rules, which people have been using for at least two years without much apparent complaint doesn't warrant a change.

**Comment by peter-ahe-google** [comment]
> Yes, I will do that. Sorry. I've been grinding through a lot of issues, so some of my comments were a little terse.
...
> That is a judgement call, I guess. I'll try to be more explicit about that. 

Much appreciated. Thank you.
