### ISSUE TITLE
Messages that include union types are pretty much impossible to read

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#20906]
Username: kasperl

The error / hint messages that include union types are pretty much impossible to read and understand.

The argument type '{BadInterfaceType,BadTypedefType,TypedefType,MalformedType,InterfaceType}' cannot be assigned to the parameter type 'GenericType'

It's not clear that this is really  a union type.
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.7.0.dev_02_00 (2014-09-10)
OS: Linux - amd64 (3.13.0-35-generic)
JVM: 1.7.0-google-v6
# projects: 1
# open dart files: 3
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 887 / 304 MB
thread count: 29
index: [737502 locations, 265 sources, 80240 elements]
______
**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-20906/comment-0/screenshot.png) (366.55 KB)

**Comment by bwilkerson** [comment]
Union types were removed a long time ago. I don't believe that this issue is relevant any more.
