### ISSUE TITLE
Analyzer does not infer type for overridden method parameters for completion purposes

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#20919]
class A {
&nbsp;&nbsp;int f(int x);
}

class B implements A {

&nbsp;&nbsp;@­override
&nbsp;&nbsp;f(x) {
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;}
}

The analyzer does not conclude that x in B.f() is an int.

**Comment by bwilkerson** [comment]
The semantics of Null Safety are the same as those requested, so this will soon be implemented by default.
