### ISSUE TITLE
Breakpoint stops at wrong line in newly spawned isolate

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#20987]
Breaking out new bug report from issue #20974:

If I set a breakpoint at the first line of an isolate, and then resume, VM stops again at the next line.

------------
import 'dart:isolate';

main() {
&nbsp;&nbsp;ReceivePort receivePort = new ReceivePort();
&nbsp;&nbsp;Isolate.spawn(runInIsolate, 42);
}

runInIsolate(int value) {
&nbsp;&nbsp;print('runInIsolate: A');
&nbsp;&nbsp;print('runInIsolate: B');
&nbsp;&nbsp;print('runInIsolate: C');
}

------------

&nbsp;&nbsp;See the protocol below.
&nbsp;&nbsp;Why did it stop at the line 10?
&nbsp;&nbsp;I set breakpoint only for the line 9.

(debug-isolates)$ dart ./ddbg.dart
&gt; connect
Isolate 194857467 has been created.
Main isolate is 194857467
Current isolate is now 194857467
4         ReceivePort receivePort = new ReceivePort();
&gt; sbp file:///Users/scheglov/dart/test2/bin/test2.dart 9
Set BP 1
&gt; r
Isolate 337403071 has been created.
Current isolate is now 337403071
9         print('runInIsolate: A');
&gt; sbp file:///Users/scheglov/dart/test2/bin/test2.dart 9
Set BP 1
&gt; r
Breakpoint 1 resolved in isolate 337403071 at file: test2.dart lib: 13 token: 40.
10        print('runInIsolate: B');

**Comment by rmacnak-google** [comment]
tools/ddgb.dart removed with legacy debugging protocol in 6249c2bcf3cb4a2241dd27caf087f07ea05147b3
