### ISSUE TITLE
Diagnose unused "show" expressions in imports.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21030]
It's really nice that the analyzer diagnoses unused imports. I use import/show a lot, and it would be extra nice if the analyzer could tell me when I have listed too much in the show clauses.

For example, a hint on &quot;Stream&quot; in this example would be nice:

import 'dart:async' show
&nbsp;&nbsp;&nbsp;&nbsp;Future,
&nbsp;&nbsp;&nbsp;&nbsp;Stream; // This isn't used.

main() {
&nbsp;&nbsp;new Future.value().then((_) =&gt; null);
}

**Comment by srawlins** [comment]
CL out for review! https://codereview.chromium.org/1863103002/

**Comment by srawlins** [comment]
Implemented in c1963b3995765dc8c4a5a90a3d01dac079552bf0.
