### ISSUE TITLE
Type == comparisons different when executing from snapshots

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#21079]
The following code behaves differently when executing from a snapshot vs from a Dart script- the '==' comparison is false for the first statement from a snapshot.

import 'dart:mirrors';
import 'dart:isolate';

void main() {
&nbsp;&nbsp;// True from .dart, false when executing from snapshot
&nbsp;&nbsp;print(reflectClass(MyException).superclass.reflectedType == IsolateSpawnException);

&nbsp;&nbsp;// True in both cases
&nbsp;&nbsp;print(reflectClass(IsolateSpawnException).reflectedType == IsolateSpawnException);
}

class MyException extends IsolateSpawnException {}

Repro:
dart --snapshot=foo.snapshot foo.dart
dart foo.snapshot

**Comment by a-siva** [comment]
https://codereview.chromium.org/1255003004/ was submitted to fix this
