### ISSUE TITLE
Dart2JS spurious compile time error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21072]
Dart2JS emits a compile-time error which is not in the spec, hence preventing a test of the corresponding run-time error which is required:

co19/src/Language/03_Overview/1_Scoping_A02_t05.dart

The compile-time error is 'Error: Cannot instantiate type variable 'C'', which is not supported by the spec.  

ECMA-408, p87, 15.31 says about an 'identifier expression e of the form id' with declaration d that 'If d is a type parameter T, then the value of e is [..] If, however, e occurs inside a static member, a compile-time error occurs.'; in the test, that 'C' is an identifier, but the grammatical derivation of this identifier does not involve 'expression', so it is reasonable to say that it is not an expression, and I found no other part of the spec that supports this compile-time error.

On the contrary, 13 has '..a type parameter is considered to be a malformed type when referenced by a static member', and 15.12.1 has 'If T is malformed or if T is a type variable a dynamic error occurs [when evaluating new T..]'.

So the test is correct, dart2js should not emit that compile-time error, and then we can run the test to see whether the run-time error is raised.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1323573002/
