### ISSUE TITLE
Stepping from an initially paused isolate goes immediately to the end of the program

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#21083]
If I start a command-line program with --pause-isolates-on-start, connect to Observatory, and then do any kind of step operation, it goes immediately to the end of the program. It would be better if it stepped to the first line of main()

**Comment by turnidge** [comment]
I've updated the protocol to support StepInto while paused at isolate start.

I've also updated the Observatory to inform users of their options when the program is paused at isolate start.

Fixed in 319214f58be75298f47a8b508ad9023c51fc4117.

**Comment by turnidge** [comment]
Had to revert.  Reopening for now.

**Comment by turnidge** [comment]
Once again: 256b044857a44977ba1b4ca58d3d96ab39765bdf
