### ISSUE TITLE
Malbounded type used in subtype test, but no dynamic error occurs

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21088]
Dart2JS does not throw a dynamic error even though a malbounded type is used in a subtype test (contrary to 18.2 in the spec):

Language/15_Types/2_Dynamic_Type_System_A01_t02.

**Comment by natebosch** [comment]
I think these are static errors now. Should the tests be removed?

**Comment by eernstg** [comment]
A malbounded type is indeed a compile-time error now, everywhere it occurs.

The set of co19 test files seems to have been reorganized a lot, so there are no files with names/paths like the ones mentioned above.

However, they may correspond to `co19/src/Language/Types/Dynamic_Type_System/malbounded_type_error_t01.dart` and `co19/src/Language/Types/Parameterized_Types/malbounded_t07.dart`. The `co19_2` versions of these tests do specify a compile-time error, and the `co19` versions are testing Dart 1 (and there aren't many configurations running them any more, anyway), so there is no need to remove any tests (except that, presumably, all of `co19` will soon go away in one step).

But I'll close this issue because there is no need to ask for Dart 1 fixes of any tool (including dart2js), and the compile-time errors in the `co19_2` tests would be working or covered by status files, anyway.

**Comment by eernstg** [comment]
Closing: This is concerned with a Dart 1 bug, and they won't be fixed at this point.
