### ISSUE TITLE
Dart2JS raises a compile-time error on duplicate final initialization, should be warning

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21093]
Dart2JS raises the compile-time error &quot;Field 'v' is initialized more than once&quot; with the following co19 test:

Language/05_Variables/05_Variables_A05_t01.

According to the spec (Sect.8, in ECMA-408 it's at the top of p13) this should be a static warning, and I could not see any support for the compile-time error.

**Comment by whesse** [comment]
These tests no longer fail with this error.  Is this error fixed?

**Comment by johnniwinther** [comment]
Is is unclear how the case

    class C {
      final v;
      C() : v = 1, v = 2;
    }

should be handled.

**Comment by whesse** [comment]
This error is still there - the tests expect this to be a static warning or a runtime error, not a compile time error.  When the spec is changed, the tests should be changed.

**Comment by sigmundch** [comment]
now handled by the CFE.
