### ISSUE TITLE
Dart2JS spurious compile-time error for 'new C' where C is not a class

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21092]
Dart2JS raises the compile-time error &quot;'C' is not a type&quot; with the following co19 test:

Language/03_Overview/1_Scoping_A02_t28.

It may be intended that 'new C..' should be a compile-time error when C is not a class (it's an int here), but 15.12.1 in the spec does not support this conclusion, and I haven't found support for it elsewhere in the spec (not much is said about the case 'new T..' where T is not a type).

So Dart2JS (and other relevant tools) could be changed to stop raising this compile-time error, or the spec could be changed to say that 'new T..' where T is a non-type is a compile-time error, presumably in 15.12 or 15.12.1.

**Comment by whesse** [comment]
These tests no longer fail.  Removed the suppressions from the status file.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org//1323573002
