### ISSUE TITLE
Dart_Initialize can only be called once per process

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#21106]
It seems that it should be possible to call this again after Dart_Cleanup has been called.
&nbsp;

**Comment by mraleph** [comment]
Shutting down and restarting Dart VM is needed to minimize memory usage of applications that embed flutter - but don't always have an active FlutterView. See flutter/flutter#16995.

**Comment by a-siva** [comment]
Looks like we have a number of issues that are blocked on this, can we get started on implementing this ability of shutting down the VM and restarting it again from the same embedding process.

**Comment by bkonyi** [comment]
Must have missed this notification in my inbox. I'll start looking into this today.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/75786 should address this

**Comment by bkonyi** [comment]
[Relanded the fix for this](https://dart-review.googlesource.com/c/sdk/+/76561). There's a follow up CL to do some additional cleanup, but `Dart_Initialize` can now be called after a `Dart_Cleanup`.

**Comment by chinmaygarde** [comment]
Flutter engine has been patched to shut down the VM cleanly and start it back up as needed. https://github.com/flutter/engine/pull/6387
