### ISSUE TITLE
Pause on exceptions/uncaught exceptions for Observatory

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#21121]
Observatory is missing the ability to pause on exceptions, both caught and uncaught. Right now if there's an exception Observatory pauses, but only because the isolate is exiting. The stack is already gone, so all you have is the traceback.

It should also have the same options as the debugger to pause on exceptions that are caught. A motivating case for this is debugging tests. If there's a test failure there will be an exception, but it will be caught by the test framework, so you need to be able to pause when it is thrown in order to debug.

Even better, be able to have some level of control over when it pauses for uncaught exceptions, to deal with programs which throw and catch lots of exceptions, where I'm interested in one in particular. Which I suppose if you generalize it, turns into conditional breakpoints.

**Comment by rmacnak-google** [comment]
392a83221ffd8405f671c9669a64bd950d6faf5e
