### ISSUE TITLE
ConstructorElement.effectiveTarget should resolve target across patch boundaries

### ISSUE THREAD

**Issue by herhut-ggl** [dart-lang/sdk#21132]
Currently, ConstructorElement.effectiveTarget follows a forwarding constructor chain until it hits the first non-forwarding constructor (the effective target of a constructor invocation). However, if such constructor is patched, the chain might continue in the patch class. In such cases, effectiveTarget should follow the chain to the patch class.

See testEffectiveTarget in dart2js/patch_test.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1382313002
