### ISSUE TITLE
Incorrect rejection of 'super !='

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21137]
The following co19 test stops with the compile-time error 'Error: '!=' cannot be called on super':

Language/12_Expressions/22_Equality_A01_t01.

According to 15.22, 'super != e' is equivalent to '!(super == e)', and the latter must be accepted during compilation and evaluated as described.

Note that the same issue arose for Area=VM (issue #1242), and it has been fixed there.  There may be other cases mentioned in issue #1242 which are useful to consider at the same time.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org//1152903003
