### ISSUE TITLE
NPE in Analyzer (P-D)

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#21162]
Unhandled exception:
AnalysisException: &lt;rethrow&gt;
Caused by The null object does not have a getter 'element'.

NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#­0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6821:7)
#­1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6784:21)
#­2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2469:86)
#­3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3101:41)
#­4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3132:36)
#­5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1226:81)
#­6      main (.../fuzz_driver.dart:40:60)
#­7      \_startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#­8      \_startMainIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:192)
#­9      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

Caused by The null object does not have a getter 'element'.

NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#­0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#­1      ConstantVisitor._validWithUnknownValue (package:analyzer/src/generated/constant.dart:1241:14)
#­2      ConstantValueComputer._evaluateConstructorCall (package:analyzer/src/generated/constant.dart:674:52)
#­3      ConstantValueComputer._computeValueFor (package:analyzer/src/generated/constant.dart:563:61)
#­4      ConstantValueComputer.computeValues (package:analyzer/src/generated/constant.dart:445:25)
#­5      LibraryResolver._performConstantEvaluation (package:analyzer/src/generated/resolver.dart:16560:29)
#­6      LibraryResolver.resolveLibrary (package:analyzer/src/generated/resolver.dart:16103:33)
#­7      ResolveDartLibraryTask.internalPerform (package:analyzer/src/generated/engine.dart:14432:29)
#­8      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6817:22)
#­9      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6784:21)
#­10     AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2469:86)
#­11     AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3101:41)
#­12     AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3132:36)
#­13     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1226:81)
#­14     main (.../fuzz_driver.dart:40:60)
#­15     \_startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#­16     \_startMainIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:192)
#­17     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
TEST: .../out-2013-12-31/compiler_unsupported-0.6.6/lib/implementation/js_backend/js_backend.dart

#­0      AnalysisContextImpl.recordResolveDartLibraryTaskResults (package:analyzer/src/generated/engine.dart:2257:7)
#­1      AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask (package:analyzer/src/generated/engine.dart:5361:133)
#­2      ResolveDartLibraryTask.accept (package:analyzer/src/generated/engine.dart:14412:77)
#­3      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6789:18)
#­4      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2469:86)
#­5      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3101:41)
#­6      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3132:36)
#­7      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1226:81)
#­8      main (.../fuzz_driver.dart:40:60)
#­9      \_startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#­10     \_startMainIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:192)
#­11     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

**Comment by bwilkerson** [comment]
The code that created the exception has been replaced, making this issue obsolete.
