### ISSUE TITLE
Dart2JS parsing miscategorizes tokens around const loop variable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21167]
Dart2JS fails with the compile-time error 'Error: Unexpected token 'x'' at 'for(const int x..' in the following co19 test:

Language/13_Statements/06_For_A01_t11.

Currently, the code should probably be accepted rather than ending in a compile-time error. Issue #5675 may result in a spec change such that it should be a compile-time error. In any case, the parser currently does not treat the given tokens as &lt;modifier&gt; &lt;type&gt; &lt;identifer&gt;, which means that dart2js should be modified both if the code should be accepted and if it should be rejected.

Presumably, the spec will be adjusted, and this ticket can be updated to &quot;make const loop vars a compile-time error&quot;.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1503063002/
