### ISSUE TITLE
Map as type/isMap for Instance service object

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#21185]
The Instance class has a variety of test methods and a user type which is distinct from the vm type. It would be good to have the ability to distinguish Map as well, to be able to do specific presentation for a Map, without needing to special case on the possible implementation classes. It looks like this is similar to what's done for List right now.

**Comment by rmacnak-google** [comment]
eca0d72abe0b7b35f4772dcbedabd61d9a86ac05
