### ISSUE TITLE
Missing UnsupportedOperation on (const {}).clear()

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21199]
Dart2JS generated code fails at 'Expect.throws(..)' in the following co19 test:

Language/12_Expressions/17_Getter_Invocation_A07_t02.

The method namedArguments should return a 'const {}' in this situation, and such a map should not be modified.  ECMA-408 p57 says 'Attempting to mutate a constant map literal will result in a dynamic error' which presumably means that attempts to modify an object obtained by evaluating a constant map literal expression must throw such an error.  If this had occurred, the 'Expect.throws(..)' would have succeeded.

**Comment by rakudrama** [comment]
Fixed https://github.com/dart-lang/sdk/commit/9425621eacb98695525b554f50cf46a8e7f3b45a
