### ISSUE TITLE
Dartium: Implement Isolate methods and spawn parameters for spawnDomUri

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21194]
Implement Isolate methods
- pause
- resume
- addErrorListener
- removeErrorLitener
- addOnExitListener
- removeOnExitListener
- setErrorsFatal
- kill
- ping
  and the Isolate.spawn/spawnUri &quot;paused&quot; parameter.

This probably depends on the VM implementing the features, and then respond to the same out-of-band messages.

**Comment by goderbauer** [comment]
Is there any update on this issue? Is "setErrorsFatal" available in Dartium yet?

**Comment by a-siva** [comment]
changing owner to terry

**Comment by terrylucas** [comment]
Will not fix.
