### ISSUE TITLE
Spurious compile time errors on 'new ..'

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21202]
Dart2JS fails the following co19 test with 'Error: 'variable' is not a type' (and 'Error: 'function' is not a type', commenting out the reason for the first error):

Language/07_Classes/6_Constructors/2_Factories_A08_t02.

In this test, 'new C()' should fail because C is unresolved (trusting the comment in the test), and an unresolved type is malformed (ECMA-408, 18.1, p113), and 'new &lt;malformed&gt;()' is a run-time error (ECMA-408, 15,12,1, p61).

The statement on p113 requires a little bit of interpretation, though: 'A type T is malformed iff: .. T has the form id or the form prefix.id, and in the enclosing lexical scope, the name id (respectively prefix.id) does not denote a type'.  The point as that we consider 'does not denote a type' to include &quot;is unresolved&quot;.

For the remaining checks the case is clear without any extra interpretation, i.e., we should get a static type warning and a run-time error in all four cases.  The run-time error should be a NoSuchMethodError in the last check, which could have been checked, but isn't.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1323573002/
