### ISSUE TITLE
Dart2JS raises spurious compile-time error for "near name clash" of method and setter

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21201]
The following co19 test fails with the compile-time error 'Error: Duplicate definition of 'foo'':

Language/07_Classes/1_Instance_Methods_A07_t01.

ECMA-408 10.1 p22 mandates a static warning, but no support for a compile-time error seems to exist.

**Comment by floitschG** [comment]
Test is now called Language/Classes/Instance_Methods/same_name_setter_t01.

Should be fixed with unified frontend.

**Comment by askeksa-google** [comment]
This is indeed fixed with the unified frontend.
