### ISSUE TITLE
Compact support for deferred loading

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21242]
I found this code in the dart2js output:

&nbsp;&nbsp;if (typeof($dart_deferred_initializers) &equals;&equals;&equals; &quot;undefined&quot;) $dart_deferred_initializers = Object.create(null);

I have two observations:
1. I'm not using deferred loading, so don't think this is needed.
2. The code could be more compact:

&nbsp;&nbsp;$dart_deferred_initializers = $dart_deferred_initializers || Object.create(null);

**Comment by joshualitt** [comment]
I believe the suggested optimization was implemented. I think we also avoid outputting the deferred load hooks unless they are used.
