### ISSUE TITLE
"Find uses" finds zero matches from generated_protocol.dart after long period of activity

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21254]
Several times over the last few days, I've noticed that after using editor (with the analysis server) for a few hours, &quot;Find uses&quot; stops working from within the file pkg/analysis_server/lib/src/generated_protocol.dart--any searches I attempt using this file as a starting point result in zero matches.  &quot;Reanalyze Sources&quot; does not fix the problem, but restarting editor does.

I haven't found a repro yet.

**Comment by devoncarew** [comment]
assumed stale?
