### ISSUE TITLE
Synchronization primitives for ARMv5 assembler

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#21263]
For atomically updating object headers in generated code, ARMv5 needs the now-deprecated 'swp' instruction, which is not yet implemented in the assembler.

For now, we'll just assert that we're running on a single core when the target is ARMv5.

**Comment by zanderso** [comment]
The assert remains in place and concurrent worker threads are disabled on ARMv5. In addition, we have no customers using multiprocessor ARMv5 hardware.
