### ISSUE TITLE
Typo in the Dart docs for the open() and send()

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#21284]
**[user feedback]**

I found a typo in the Dart docs for the open() and send() methods of the HttpRequest class:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html.HttpRequest#id_send

The sentence reads:

&quot;Use of this open method is intended only for more complext...&quot;

I have heard &quot;complext&quot; could be the superlative form of &quot;complex&quot;, but I think &quot;complex&quot; was intended here.

////////////////////////////////////////////////////////////////////////////////////
Editor: 1.6.0.release (2014-08-26)
OS: Linux - amd64 (3.13.0-32-generic)
JVM: 1.8.0_20
# projects: 2
# open dart files: 8

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 575 / 433 MB
thread count: 31
index: [628271 locations, 582 sources, 48116 elements]

SDK installed: true
Dartium installed: true

**Comment by bkonyi** [comment]
Looks like this is fixed. Closed.
