### ISSUE TITLE
analyzer/test/generated/resolver_test runs too long

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#21300]
0:01:56.736000 - vm - none-vm-checked debug_ia32/pkg/analyzer/test/generated/resolver_test

This test seems to be too big and it therefore is too close to the 2min cutoff. Any slight variation on the test machine will make it fail and thus it is flaking repeatedly:
http://chromegw.corp.google.com/i/client.dart/builders/pub-linux-debug-be/builds/4096/steps/pub%20and%20pkg%20tests%20failures/logs/stdio
http://chromegw.corp.google.com/i/client.dart/builders/pub-linux-debug-be/builds/4094/steps/pub%20and%20pkg%20tests%20failures/logs/stdio
http://chromegw.corp.google.com/i/client.dart/builders/pub-linux-debug-be/builds/4093/steps/pub%20and%20pkg%20tests%20failures/logs/stdio

**Comment by bwilkerson** [comment]
I believe that the problem is in the test framework, not the tests. If you disagree, please start an e-mail conversation with me.
