### ISSUE TITLE
Provide a stable "guessable" url for downloading old SDK/Dartium versions

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#21348]
For the dart-sdk Chocolatey package, I have to use this page to get the &quot;stable&quot; URLs for a package (to allow switching versions):

https://www.dartlang.org/tools/download_archive/

This makes it tricky for me to script without yanking data from that page. It would be much better if you could provide stable URLs built from that data, even if they just redirect to those ones.

Eg.:

https://www.dartlang.org/tools/download_archive/1.7.2/sdk/dartsdk-windows-ia32-release.zip

could redirect to

https://storage.googleapis.com/dart-archive/channels/stable/release/41096/sdk/dartsdk-windows-ia32-release.zip

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/www.dartlang.org#1451
