### ISSUE TITLE
Make TypeError, CastError, AssertionError abstract classes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21368]
The VM prevented creation and extension of these classes by accidentally removing the default constructor. Now that this is fixed, we probably still want to make the classes abstract, so a user will at least have to extend them with useful information.

**Comment by dgrove** [comment]
Is this still intended for 2.0?

**Comment by lrhn** [comment]
Yes

**Comment by dgrove** [comment]
Any updates, @lrhn?

**Comment by dgrove** [comment]
AFAIK, this work is no longer intended to be done (and definitely isn't part of the Dart2Stable milestone).

**Comment by lrhn** [comment]
Correct. We decided that it's not important enough to worry about.
