### ISSUE TITLE
Growth policy misinformed by concurrent sweep

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#21364]
Old-space growth policy is informed by available capacity. However, with concurrent sweeping, pages are freed and capacity adjusted after/while a GC is evaluated (see PageSpaceController::EvaluateGarbageCollection), which may lead to unintended and unpredictable decisions.

At a more basic level, the tweak &quot;allow growth by at least half the pages freed by GC&quot; is inherently incompatible with having a concurrent sweeper.

**Comment by kodandersson** [comment]
There should always be a reasonable "best estimate" of usage/capacity, which can be adjusted incrementally (and thread-safely) during concurrent sweeping (and soon, marking). This way, it should always be possible to evaluate the growth policy.

**Comment by mraleph** [comment]
When you have some time please review this @ErikCorryGoogle and close it if no action is planned.
