### ISSUE TITLE
Triage skipped co19 tests

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21366]
The following co19 tests depend on the content window frame, and need to be triaged:

LayoutTests/fast/borders/border-radius-child_t01: RuntimeError -&gt; Pass

LayoutTests/fast/css-generated-content/hit-test-generated-content_t01: RuntimeError -&gt; Pass

LayoutTests/fast/css/collapsed-whitespace-reattach-in-style-recalc_t01: RuntimeError -&gt; Pass

LayoutTests/fast/events/document-elementFromPoint_t01: RuntimeError -&gt; Pass

LayoutTests/fast/sub-pixel/float-containing-block-with-margin_t01: RuntimeError -&gt; Pass

LayoutTests/fast/sub-pixel/table-rows-have-stable-height_t01: RuntimeError -&gt; Pass

LayoutTests/fast/table/col-width-span-expand_t01: RuntimeError -&gt; Pass

LayoutTests/fast/text-autosizing/vertical-writing-mode_t01: RuntimeError -&gt; Pass

LayoutTests/fast/text/international/rtl-text-wrapping_t01: RuntimeError -&gt; Pass

LayoutTests/fast/writing-mode/positionForPoint_t01: RuntimeError -&gt; Pass

LayoutTests/fast/css/computed-offset-with-zoom_t01: Pass -&gt; RuntimeError
LayoutTests/fast/sub-pixel/inline-block-with-padding_t01: Pass -&gt; RuntimeError
LayoutTests/fast/sub-pixel/size-of-span-with-different-positions_t01: Pass -&gt; RuntimeError
LayoutTests/fast/text/international/complex-text-rectangle_t01: Pass -&gt; RuntimeError
LayoutTests/fast/text/line-breaks-after-hyphen-before-number_t01: Pass -&gt; RuntimeError

See also issue https://code.google.com/p/co19/issues/detail?id=732

**Comment by athomas** [comment]
LayoutTests have been deleted.
