### ISSUE TITLE
Search in Future<T> API web page cannot find text in folded sections

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21391]
Maybe this is just a feature enhancement request, but the situation described below created so much confusion that I tend to think it's a bug. ;-)

Looking at https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-async.Future, I suddenly noticed that the overview box to the right couldn't be used to find individual subsections (in particular, I could click 'whenComplete' and it wouldn't scroll the page anywhere relevant, and a native browser 'search on page' operation couldn't find the word 'whenComplete' any other place than in the overview box.

After a while I discovered that this situation arose because I (somehow, not noticing the effect) had clicked on a section header, 'Methods', such that this section got folded away.  It was only later, when I explained the situation to a nearby co-worker, that I noticed the little &quot;this is folded&quot; triangle and guessed that this might be the cause of the problem.

Is there a way to make search &quot;work&quot; on these hidden pieces of text, possibly such that the relevant sections are unfolded when something is searched and found in there?

Otherwise it might be good to simply disable the folding feature:  It is hardly going to be needed very badly by anyone, but it is very confusing when your overview box says that there is a 'whenComplete' subsection somewhere, and you just can't find it.

**Comment by sethladd** [comment]
The new dartdoc does not have folded sections, so searching within a page should "just work"
