### ISSUE TITLE
Support Unix Sockets in dart:io

### ISSUE THREAD

**Issue by schultzter** [dart-lang/sdk#21403]
**What steps will clearly show the issue / need for enhancement?**
1. a lot of Unix based systems use Unix sockets for interprocess communication
2. with dart:io only TCP based communication is possible
3. support for Unix sockets would greatly increase the integration potential of dart server-side apps

**What is the current output?**
None, not supported

**What would you like to see instead?**
Success, connected!

**What version of the product are you using? On what operating system?**
1.7.2 on Arch Linux

**Please provide any additional information below.**

**Comment by zoechi** [comment]
Any progress on this? I think to remember that I saw a commit or code review where this was mentioned not too long ago, but I might mix up something. I'd like to use this to connect to docker services. It's possible to configure Docker to accept http connections but that results in severe security issues.

**Comment by sgjesse** [comment]
We have been experimenting with adding support for UNIX domain sockets, and is currently using a patched Dart VM for some experimentation. However I don't expect this to be added after all, as we will try to move the experimental use we have back to TCP sockets.

For reference the experimental patch is here: https://codereview.chromium.org/1293533002/.

**Comment by zoechi** [comment]
@sgjesse Thanks a lot for this quick response!
Doesn't seem to add a lot of complexity.
What are the reasons for this changes being dropped?

**Comment by sgjesse** [comment]
The change is not complete - it is missing changes to the File class where
we currently also don't handle domain sockets (the patch have a hack to
allow one to delete this type of files).

Another concern is to add platform specific APIs dart:io. If this should be
abstracted to also have a Windows counterpart we would have to find a
matching IPC concept on Windows, which would increase the complexity quite
a bit.

On Fri, Dec 11, 2015 at 12:44 PM, Günter Zöchbauer <notifications@github.com

**Comment by zoechi** [comment]
I understand that reasoning, but it's sad to limit Darts usage on Unix systems this way because Windows doesn't provide anything similar :(

**Comment by Pajn** [comment]
Is there any development in this area?

There are many cross-platform languages that support Unix Sockets on platforms that have support for it and does not provide an alternative on Windows. The alternative already exist in the form of TCP and UDP, it's just a much worse alternative for certain use-cases.

Redis with Unix sockets can support around 50% more throughput than with TCP sockets, it's sad to have to think of that and have that as a thing to consider when choosing a server platform.

**Comment by hermanbergwerf** [comment]
I want to attempt to write a very simple X11 client in Dart. Is Unix sockets really off the table? That would be quite sad in my opinion.

**Comment by zoechi** [comment]
> Another concern is to add platform specific APIs dart:io. If this should be
abstracted to also have a Windows counterpart we would have to find a
matching IPC concept on Windows, which would increase the complexity quite
a bit.

This missing feature prevents several use cases which don't apply to Windows, because they are not used much on Windows but are a significant limitation on Unix systems.

**Comment by hermanbergwerf** [comment]
Perhaps there can be a `dart:unix` library for unix specific APIs?

**Comment by Hixie** [comment]
FWIW, this is the workaround I used (to send the string `status\n` to the Unix domain socket named `/tmp/control.socket`):
```dart
await Process.run('/bin/sh', <String>['-c', 'echo status | nc -U /tmp/control.socket']);
```

**Comment by knopp** [comment]
Why not use named pipes as counterpart on Windows? While not being completely same thing, for example libuv has single pipe stream abstraction that works for both domain socket and named pipes.

**Comment by recoilme** [comment]
Is there any development in this area?

**Comment by vanesyan** [comment]
Other programming languages supports Unix sockets, despite the fact that support limited only to Unix systems. For example, Rust marks API as xsupported only on Unix". https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html

Node.js also supports Unix sockets as well as Go.

Maybe the functionality can be exposed in specific module like `dart:unix` or `dart:uds`

**Comment by knopp** [comment]
NodeJS uses named pipes on windows (through libuv). We have a project using libuv on IPC (domain sockets on unix, named pipes on windows) and it works very well. I don't quite see why this couldn't be done for dart.

**Comment by bpilot** [comment]
Please fix this, this is the most annoying issue I have with Dart. I want to use Dart for IPC without management of clumsy ports.

**Comment by rahul-dutt-sharma** [comment]
Just dropped my plan to use Flutter for my dream project

**Comment by flddr** [comment]
We need that generally in future. For me not highest priority, but one of them, to _Dart_ the world :+1:

**Comment by radzish** [comment]
I believe that without this it is not possible to write serverless Cloud Run service connecting to Google CloudSQL directly: https://cloud.google.com/sql/docs/mysql/connect-run, as last one requires connecting to DB through Unix Domain Sockets

**Comment by edwjusti** [comment]
Windows supports AF_UNIX now. The dart runtime could simply throw an exception if support is not available. https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by vanesyan** [comment]
Seems that the work to integrate this was actually begun, see https://dart-review.googlesource.com/c/sdk/+/125932

**Comment by robert-ancell** [comment]
Sending credentials using SCM_CREDENTIALS is a required feature for some Unix Domain Socket servers. I hope this can be integrated into the Dart API in some way.

**Comment by DrSensor** [comment]
What about IOS/Mac?
Similiar on how nodejs/libuv switch to named pipes when running on Windows, does this feature need to switch to Mach port to avoid [sandboxing restrictions](https://iphonedevwiki.net/index.php/Unix_sockets#Bypassing_sandbox_with_inet_sockets)?

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/issues/44714 is blocked on this.

**Comment by a-siva** [comment]
work on this is progressing here https://dart-review.googlesource.com/c/sdk/+/125932

**Comment by knopp** [comment]
@a-siva, any reason why named pipes can't be used on windows, just like in libuv/nodejs?

**Comment by a-siva** [comment]
We will explore support on Windows after first getting this CL (Support on Linux, Macos and Android) to land.

**Comment by ZichangG** [comment]
The change has been landed. I open https://github.com/dart-lang/sdk/issues/41161 for supporting on Windows.

**Comment by banalg** [comment]
Good news, but I didn't succeed creating a socket SOCK_SEQPACKET, requested for some services like [uv4l.](https://www.linux-projects.org/documentation/uv4l-server/https://www.linux-projects.org/documentation/uv4l-server/)
Searching in the commit it seems we can only use SOCK_DGRAM and SOCK_STREAM.

Is it planned to accept others socket types ? http://man7.org/linux/man-pages/man2/socket.2.html
