### ISSUE TITLE
Refactor to async / await

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#21413]
Feature request for analyzer.

Help refactor old-school Future code to new hotness async await.

e.g.

main() {
&nbsp;&nbsp;doIt().then((x) =&gt; print(x));
}

Future doIt() =&gt; new Future.value(42);

into:

main() async {
&nbsp;&nbsp;print(await doIt());
}

doIt() async =&gt; 42;

**Comment by natebosch** [comment]
When I search `pkg/analyzer` I find 5928 "await" and only 957 "then". I think this refactoring was either done, or has been slowly transitioning. This issue probably isn't useful anymore.
