### ISSUE TITLE
Safari now supports indexedDB

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#21430]
Safari 6.2 and 7.1 now support indexedDB, so this should be added to the documentation for the dart:indexed_db library.  The indexeddb/supported test has been updated in the status file to indicate that it passes on Safari 6.2, macos 10.8.

**Comment by srawlins** [comment]
There is a link to [CanIUse](http://caniuse.com/#feat=indexeddb) in [the docs](https://api.dartlang.org/1.12.1/dart-indexed_db/dart-indexed_db-library.html), probably good enough?
