### ISSUE TITLE
Code completion not displayed typing between characters not separated by space

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#21456]
[from comment #­2 in https://code.google.com/p/dart/issues/detail?id=21380]

Code completition list is also not displayed when the cursor is typing between characters not separated by space. For example when typing the dot after 'object' doesn't display the list of object members, or sometimes it displays a PARTIAL and WRONG list of members: 

object.method()
object^

You need to insert a space on the right of the cursor before to display correctly the completition list of members when you are typing, like this:

object. method()
object^

The same is true for both the member list displayed when typing a dot after the 'object' name, and for the completition list manually called with Ctrl-Space. It shouls be also noted that the option to call autocompletition from the right mouse button contextual menu is missing.

**Comment by jwren** [comment]
This does not seem to be an issue with the latest implementations of the code completion service.
