### ISSUE TITLE
We need to display only one URL for each page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#21475]
When we looked at recent analytics for api.dartlang.org, we noticed the same pages coming up multiple times. For example, the dart:html library docs have at least 2 URLs in the top 50:

\* https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html
\* https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html

Both URLs should continue to work, but only one should be displayed in the browser. I'd prefer the dart:html nomenclature.

It'd be great if we could shorten the visible URLs at the same time. for example:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html
-&gt;
https://api.dartlang.org/dart:html

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html.Element
-&gt;
https://api.dartlang.org/dart:html.Element

https://api.dartlang.org/apidocs/channels/dev/dartdoc-viewer/dart:html
-&gt;
https://api.dartlang.org/dev/dart:html

**Comment by sethladd** [comment]
Addressed in the new dartdoc
