### ISSUE TITLE
API doc bug: no info on scrollOptions, bad link to webplatform.org

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#21482]
From https://groups.google.com/a/dartlang.org/forum/#!original/web/yzVjhH1g2mY/zzIuM6Fy4jYJ:

I'm looking at the window scroll methods at https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart-dom-html.Window#id_scroll and I can't figure out what &quot;scrollOptions&quot; is. There doesn't appear to be any documentation anywhere on this parameter. Also, the webplatform.org links are broken and need to be updated :(

**Comment by srawlins** [comment]
Link still 404s. https://api.dartlang.org/dev/dart-html/Window/scroll.html

**Comment by srawlins** [comment]
Happy Halloween, 2014!
