### ISSUE TITLE
4 xhr tests failing on Dartium after updating test runner vm

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#21525]
After updating the checked-in dart runtime, used to run test.dart, 4 xhr tests are failing on dartium:

co19/LayoutTests/fast/events/event-on-xhr-document_t01
co19/LayoutTests/fast/xmlhttprequest/xmlhttprequest-responsetype-document_t01
co19/LayoutTests/fast/xmlhttprequest/xmlhttprequest-responseXML-xml-document-responsetype_t01
co19/LayoutTests/fast/xpath/4XPath/Borrowed/od_20000608_t01

This is due to the fact that HttpServer in dart:io now sends different default headers, and the server in the testing scripts needs to be adjusted to that (most of these adjustments are already made).

**Comment by athomas** [comment]
Dartium is going away.
