### ISSUE TITLE
Analyzer should hint when type parameters shadow a name in the enclosing scope

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21529]
Consider the following class declaration:

class C&lt;String&gt; {
}

Within the body of C the name String will be shadowed. It would be nice to provide the user with a hint to point out the problem because that's unlikely to be what they intended to do.

**Comment by srawlins** [comment]
Since the language broadly allows shadowing, this will probably be implemented as a lint, and has been moved to https://github.com/dart-lang/linter/issues/665.
