### ISSUE TITLE
VM allows non-top-level function main functions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21535]
The specification (LaTeX version) states about running a script that:

&nbsp;&nbsp;&nbsp;It is a run time error if $S$ does not declare or import a top-level function `main`

The VM allows running scripts with non-top-level function mains, fx:

&nbsp;&nbsp;var main = function() { print(&quot;Hello world!&quot;); };
&nbsp;&nbsp;get main =&gt; function() { print(&quot;Hello world!&quot;); };
&nbsp;&nbsp;var main = new CallableObject();
&nbsp;&nbsp;var main = new ObjectWithNoSuchMethod();

In all these cases it should cause a runtime error.

**Comment by munificent** [comment]
Duplicate of #23887. (This one's older, but I already de-duped some other bug to that one, so I'm declaring it to be the winner.)
