### ISSUE TITLE
It's unspecified which scope instance variable initializers are evaluated in.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21581]
The spec says:

---

For each instance variable `f` of `i`, if the variable declaration of `f` has an initializer expression `e_f` , then `e_f` is evaluated to an object `o_f` and `f` is bound to `o_f` . Otherwise `f` is bound to `null`.
Observe that `this` is not in scope in `e_f`. Hence, the initialization cannot depend on other properties of the object being instantiated.

---

The minimal assumption would be that the expression is evaluated in the static scope of the class - that is: it is in the scope of the class, but it's an error to access non-static properties. 

That doesn't address access to type variables.
Type variables are generally considered non-static (they are not accessible from static methods), and they are explicitly mentioned as being in scope for initializer lists.

All implementations (VM, dart2js, analyzer) assumes that type variables are in scope for instance field initializers, with the value they will have for the object being created.

**Comment by eernstg** [comment]
We have the following:
```
The enclosing scope of an instance member declaration is the instance scope
of the class in which it is declared.
```
and noting that an initializing expression is part of the declaration of the instance variable that it initializes, I believe that we may conclude that it is in the instance scope of the enclosing class.

It is explicitly stated that it is a compile-time error for `this` to be referred (explicitly or implicitly) in a variable initializer:
```
It is a compile-time error if \THIS{} appears, implicitly or explicitly, ...
in the initializer of an instance variable.
```
I believe that `this` has no scope (it is not a member of any namespace), but even though it may _occur_ everywhere, all "inappropriate" locations are defined to be a compile-time error.

With that, I believe we can close this issue. Please re-open if needed.
