### ISSUE TITLE
Analyzer documentation does not explain package_root and pub.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#21595]
The command-line dartanalyzer needs to be run with the current directory set to the main directory of a package, to analyze the package.  This is not explained anywhere in the documentation printed by the tool, or at dartdocs.org.

The command-line help says that the --package-root option is deprecated, and pub should work automatically, but the dartdocs.org info just uses the --package-root option.

There is no example given of using analyzer to analyze a program in a package.  The way that worked for me is:

cd tools/apps/update_homebrew
[build dir]/dart-sdk/bin/dartanalyzer bin/update_homebrew.dart

**Comment by pq** [comment]
Closing for staleness.
