### ISSUE TITLE
Layout hit-test fails on MacOS

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#21605]
The tests
co19/LayoutTests/fast/writing-mode/vertical-inline-block-hittest_t01: Pass, RuntimeError #
co19/LayoutTests/fast/writing-mode/flipped-blocks-hit-test-overflow_t01: Pass, RuntimeError #

fail flakily on MacOS on Dartium.

**Comment by alan-knight** [comment]
Also happens on Windows.
