### ISSUE TITLE
The compiler crashed: FormatException: Unfinished UTF-8 octet sequence

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21627]
Compile the attached file (which contains a bad UTF-8 sequence).

The compiler crashes. Twice it seems.

Uncaught exception in diagnostic handler: FormatException: Bad UTF-8 encoding 0xa
# ­0      _Utf8Decoder.convert (dart:convert/utf.dart:455)
# ­1      Utf8Decoder.convert (dart:convert/utf.dart:322)
# ­2      Utf8Codec.decode (dart:convert/utf.dart:66)
# ­3      Utf8BytesSourceFile.slowText (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file.dart:173:35)
# ­4      CachingUtf8BytesSourceFile.slowText (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file.dart:202:34)
# ­5      SourceFile.lineStarts (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file.dart:45:54)
# ­6      SourceFile.getLine (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file.dart:79:24)
# ­7      SourceFile.getLocationMessage (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file.dart:127:23)
# ­8      FormattingDiagnosticHandler.diagnosticHandler (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file_provider.dart:203:38)
# ­9      FormattingDiagnosticHandler.call (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/source_file_provider.dart:217:29)
# ­10     Compiler.callUserHandler.&lt;anonymous closure&gt; (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/apiimpl.dart:341:16)
# ­11     CompilerTask.measure (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/compiler.dart:2067:37)
# ­12     Compiler.callUserHandler (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/apiimpl.dart:340:30)
# ­13     Compiler.reportDiagnostic (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/apiimpl.dart:327:22)
# ­14     Compiler.unhandledExceptionOnElement (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/compiler.dart:1068:21)
# ­15     Compiler.withCurrentElement (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/compiler.dart:856:36)
# ­16     _LibraryLoaderTask.createLibrarySync (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/library_loader.dart:580:39)
# ­17     _LibraryLoaderTask.createLibrary.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/library_loader.dart:564:30)
# ­18     _RootZone.runUnary (dart:async/zone.dart:1155)
# ­19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
# ­20     _Future._propagateToListeners (dart:async/future_impl.dart:567)
# ­21     _Future._completeWithValue (dart:async/future_impl.dart:358)
# ­22     _Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:412)
# ­23     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
# ­24     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
# ­25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
# ­26     _startIsolate (dart:isolate-patch/isolate_patch.dart:244)
# ­27     _startMainIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:192)
# ­28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

The compiler crashed: FormatException: Unfinished UTF-8 octet sequence
# ­0      _Utf8Decoder.flush (dart:convert/utf.dart:411)
# ­1      _Utf8Decoder.close (dart:convert/utf.dart:399)
# ­2      Utf8Decoder.convert (dart:convert/utf.dart:323)
# ­3      Utf8Codec.decode (dart:convert/utf.dart:66)
# ­4      Utf8BytesScanner.handleUnicode (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/utf8_bytes_scanner.dart:175:27)
# ­5      AbstractScanner.tokenizeSingleLineComment (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner.dart:728:38)
# ­6      AbstractScanner.tokenizeSlashOrComment (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner.dart:710:39)
# ­7      AbstractScanner.bigSwitch (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner.dart:358:36)
# ­8      AbstractScanner.tokenize (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner.dart:198:25)
# ­9      ScannerTask.scanElements (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner_task.dart:32:61)
# ­10     ScannerTask.scan.&lt;anonymous closure&gt; (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner_task.dart:25:19)
# ­11     CompilerTask.measure (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/compiler.dart:2067:37)
# ­12     ScannerTask.scan (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner_task.dart:24:12)
# ­13     ScannerTask.scanLibrary (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/scanner/scanner_task.dart:20:9)
# ­14     _LibraryLoaderTask.createLibrarySync.&lt;anonymous closure&gt; (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/library_loader.dart:586:35)
# ­15     Compiler.withCurrentElement (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/compiler.dart:839:15)
# ­16     _LibraryLoaderTask.createLibrarySync (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/library_loader.dart:580:39)
# ­17     _LibraryLoaderTask.createLibrary.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Users/ahe/Dart/all/dart/pkg/compiler/lib/src/library_loader.dart:564:30)
# ­18     _RootZone.runUnary (dart:async/zone.dart:1155)
# ­19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
# ­20     _Future._propagateToListeners (dart:async/future_impl.dart:567)
# ­21     _Future._completeWithValue (dart:async/future_impl.dart:358)
# ­22     _Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:412)
# ­23     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
# ­24     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
# ­25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
# ­26     _startIsolate (dart:isolate-patch/isolate_patch.dart:244)
# ­27     _startMainIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:192)
# ­28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

---

**Attachment:**
[bad.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-21627/comment-0/bad.dart) (15 Bytes)

**Comment by joshualitt** [comment]
Unfortunately, I cannot load the attached repro anymore. Closing, please reopen if this is still an issue.
