### ISSUE TITLE
Heap::IterateObjects includes garbage

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#21620]
With concurrent sweeping, Heap::IterateObjects will visit garbage that has not yet been swept, which is not clear from its description.

We should rename/document/hide this method better, and add an interface to iterate over only live objects.

This has caused failures in the test vm/cc/PrintJSON.

**Comment by a-siva** [comment]
@a-siva

**Comment by kodandersson** [comment]
The proposed fix is to default to waiting for the concurrent sweeper in the Heap::VisitObjects/VisitObjectPointers methods, but with the ability for things like GC/Verify to avoid the wait.

Also, we should add a NoGCSafePointScope to guard against visitors that might trigger a GC.

Furthermore, it seems like ObjectGraph already has a potential bug w.r.t. this issue in its Unmarker::UnmarkAll method.

**Comment by kodandersson** [comment]
I will first add the NoSafepointScope and fix ObjectGraph, then I'll revamp our current task counter to something more flexible that can also work with concurrent marking, something like having both NoSweepingScope and NoMarkingScope utilities, which wait, block, and can nest.
