### ISSUE TITLE
Dartanalyzer/DartVM disagree with dart2js about scoping rules

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#21633]
In dart2js it is possible to use an identifier declared in an outer scope, even though it is defined in the current scope if the usage happens before the declaration.

$ cat test.dart
var a = 10;
main() {
&nbsp;&nbsp;print(a);
&nbsp;&nbsp;var a = 42;
&nbsp;&nbsp;print(a);
}

$ dartanalyzer test.dart
Analyzing [test.dart]...
[error] Local variables cannot be referenced before they are declared (/.../test.dart, line 3, col 9)
1 error found.

$ dart test.dart        
'file://.../test.dart': error: line 4 pos 7: identifier 'a' previously used in line 3
&nbsp;&nbsp;var a = 42;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
$ dart2js --out=/tmp/x.js test.dart
$ d8 /tmp/x.js
10
42

**Comment by kmillikin** [comment]
This is a duplicate of #13205.
