### ISSUE TITLE
Sending HashMap through SendPort can make the result unusable.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21675]
Objects are cloned when sent through a SendPort, so they effectively change identity and identity-hashCode.

If you have a HashMap with keys that don't override Object.hashCode, the HashMap will not work when received.

Example:
&nbsp;&nbsp;import &quot;dart:isolate&quot;;
&nbsp;&nbsp;enum Foo { BAR, BAZ }  // Likely candidate for map keys
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;var map = { Foo.BAR: 42 };
&nbsp;&nbsp;&nbsp;&nbsp;var p;
&nbsp;&nbsp;&nbsp;&nbsp;p = new RawReceivePort((map) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var key = map.keys.first;  // The correct key!
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(map.values.first);   // 42
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(map[key]);           // null
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p.close();
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;p.sendPort.send(map);
&nbsp;&nbsp;}

The underlying problem is that the HashMap depends on the hash values of its elements, so when those change, the map need to be rebuilt. Even better would be to not send the hash structure or cached hash codes along at all, and rebuild the map from just the keys and values.

**Comment by floitschG** [comment]
Code that relies on hashcodes has to assume that sending it to a different isolate can break its assumptions.
We don't have any plans to fix this.
