### ISSUE TITLE
isolate/remote_unittest_helper.dart not working with spawnUri

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#21676]
The remote_unittest_helper script tries to find the current URI by going through the reflection:

&nbsp;&nbsp;ClosureMirror closure = reflect(main);
&nbsp;&nbsp;LibraryMirror library = closure.function.owner;
...
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;Isolate.spawnUri(library.uri, null, receivePort.sendPort);
...

This doesn't work anymore:
1. apparently `library` is `null` (not sure why), and
2. even if it wasn't, we don't provide the URL anymore if the script is minified.

**Comment by lrhn** [comment]
Is this a problem with the mirror library or the `remote_unittest_helper.dart` script?
I don't see how it's a problem in the isolate library?

**Comment by floitschG** [comment]
I believe it was a bug in the implementation of dart2js.

Tbh I'm not 100% sure what the problem was... (a year old).
Closing, since I can't reproduce.
