### ISSUE TITLE
provide better error message for broken imports

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#21693]
The current error message for a broken import is cryptic and hard to figure out where the error comes from:
&nbsp;- the error shows as an exception, when I see it, I start scanning the stack trace trying to find something related to my program, but turns out all fo the stack frames are from the system.
&nbsp;- the message doesn't say where the broken import comes from either. If you have the error somewhere deep in your code, you have to grep all your files to find out where that came from.

It would be great to improve this. Here is an example:

&nbsp;&nbsp;a.dart:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;import 'b.dart';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main() {}

Suppose I have not created b.dart. Running `dart a.dart` today produces this error:

Unhandled exception:
Uncaught Error: FileSystemException: Cannot open file, path = '/usr/local/path/to/current/working/directory/b.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#­0      \_File.open.&lt;anonymous closure&gt; (dart:io/file_impl.dart:349)
#­1      \_RootZone.runUnary (dart:async/zone.dart:1155)
#­2      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#­3      \_Future._propagateToListeners (dart:async/future_impl.dart:567)
#­4      \_Future._completeWithValue (dart:async/future_impl.dart:358)
#­5      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:412)
#­6      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­7      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­8      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#­9      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

#­0      \_rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
#­1      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­2      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­3      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#­4      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

It would be great to produce something like this instead:

&nbsp;&nbsp;file:///usr/local/path/to/current/working/directory/a.dart: error: line 1 pos 9:
&nbsp;&nbsp;imported file not found. The import URL was resolved to
&nbsp;&nbsp;file:///usr/local/path/to/current/working/directory/b.dart, but it was not
&nbsp;&nbsp;found in your file-system:

&nbsp;&nbsp;&nbsp;&nbsp;import 'b.dart';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^

**Comment by sigmundch** [comment]
Any updates on this?

**Comment by zanderso** [comment]
@sigmundch's example now gives:
```
Unhandled exception:
Could not import "file:///C:/Workspace/dart/b.dart" from "file:///C:/Workspace/dart/a.dart": FileSystemException: Cannot open file, errno = 2
```
which is better.
