### ISSUE TITLE
Test output elided

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21691]
I found this in the middle of a stack trace:

CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;print&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;[verbose info] Inferring types...&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 18.748

*****************************************************************************

Data removed due to excessive length

*****************************************************************************

ntal/library_updater.dart:506:26)\n#­2      LibraryUpdater.computeUpdateJs (package:dart2js_incremental/library_updater.dart:540:49)\n#­3      IncrementalCompiler.compileUpdates.&lt;anonymous closure&gt; (package:dart2js_incremental/dart2js_incremental.dart:132:48)\n#­4      _RootZone.runUnary (dart:async/zone.dart:1155)\n#­5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)\n#­6      _Future._propagateToListeners (dart:async/future_impl.dart:567)\n#­7      _Future._completeWithValue (dart:async/future_impl.dart:358)\n#­8      Future.wait.&lt;anonymous closure&gt; (dart:async/future.dart:282)\n#­9      _RootZone.runUnary (dart:async/zone.dart:1155)\n#­10     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)\n#­11     _Future._propagateToListeners (dart:async/future_impl.dart:567)\n#­12     _Future._completeWithValue (dart:async/future_impl.dart:358)\n#­13     _Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:412)\n#­14     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)\n#­15     _asyncRunCallback (dart:async/schedule_microtask.dart:48)\n#­16     _handleMutation (dart:html:41799)\n\n\n&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 31.437
}
Content-Type: text/plain
Running /Users/ahe/Dart/all/dart/tests/try/web/incremental_compilation_update_test.dart

That makes the stack trace unreadable.

**Comment by athomas** [comment]
This was raised at some point.
