### ISSUE TITLE
homebrew: add optional support for installing content shell

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#21717]
See https://github.com/kevmoo/homebrew-kevmoo/blob/master/dart-editor.rb

Suggestion: make the sym link use the name content_shell so we have the same name as on linux

**Comment by whesse** [comment]
The --with-dartium and --with-content-shell options have been added to the homebrew dart formula.
Content shell on android is no longer built or distributed.  Closing the issue.
