### ISSUE TITLE
dart:mirrors API docs: Broken links to "reflect"

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#21714]
I took a look at https://code.google.com/p/dart/source/browse/branches/bleeding_edge/dart/sdk/lib/mirrors/mirrors.dart, and found that the first bad link, at least, has the form [reflect\](\*r\*), which is obviously a problem. Perhaps use something like `calling [reflect] with the argument \*r\*`.

From https://github.com/dart-lang/www.dartlang.org/issues/1160:

1. Go to: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:mirrors.InstanceMirror
2. Click first hyperlinked &quot;reflect&quot;.
3. Error 404

This seems to happen for most/all references to &quot;reflect&quot; on that page.

**Comment by srawlins** [comment]
This is fixed. The link works: https://api.dartlang.org/1.12.1/dart-mirrors/ObjectMirror-class.html
