### ISSUE TITLE
Confusing warning message when trying to set a final variable in a derived class

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21739]
This file has two warnings, as indicated below:

&nbsp;&nbsp;class C {
&nbsp;&nbsp;&nbsp;&nbsp;final int i = null;
&nbsp;&nbsp;&nbsp;&nbsp;f() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i = 1; // WARNING: 'i' cannot be used as a setter, it is final
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
&nbsp;&nbsp;class D extends C {
&nbsp;&nbsp;&nbsp;&nbsp;g() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i = 1; // WARNING: Undefined name 'i'
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}

The first warning makes sense.  The second is confusing.  It would be nice if the warning in both cases could be &quot;'i' cannot be used as a setter, it is final&quot;.

**Comment by srawlins** [comment]
Both warnings now have the correct text:

```none
  error • 'i' can't be used as a setter because it's final. • 21739.dart:4:7 • assignment_to_final
  error • 'i' can't be used as a setter because it's final. • 21739.dart:9:7 • assignment_to_final
```
