### ISSUE TITLE
No hint when a function literal returns an incorrect type.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21748]
The following code produces a runtime error:

&nbsp;&nbsp;class C {}
&nbsp;&nbsp;class D {}
&nbsp;&nbsp;f(C arg()) {
&nbsp;&nbsp;&nbsp;&nbsp;C c = arg();
&nbsp;&nbsp;&nbsp;&nbsp;print(c);
&nbsp;&nbsp;}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;f(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return new D();
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}

Because the function literal passed to f() returns an instance of D, but f() expects it to return an instance of C.

But there are no warnings or hints.  (Note: according to the spec, there should be no warning, any function literal of the form &quot;() { ... }&quot; is defined to have static type &quot;() -&gt; dynamic&quot;, regardless of what it returns.)

It would be nice if the analyzer could produce a hint in this situation.  Ideally, it would infer from the function literal's usage that its intended return type is C, and then check any return statements inside the function literal to verify that they match that intent.

**Comment by srawlins** [comment]
The analyzer now produces static errors for the example code:

```none
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ cat 21748.dart 
class C {}
  class D {}
  f(C arg()) {
    C c = arg();
    print(c);
  }
  main() {
    f(() {
      return new D();
    });
  }
$ dartanalyzer 21748.dart 
Analyzing 21748.dart...
  error • The return type 'D' isn't a 'C', as defined by anonymous closure at 21748.dart:9:14 • return_of_invalid_type_from_closure
1 error found.
```
