### ISSUE TITLE
Analyzer doesn't handle absolute file paths properly on Windows

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21772]
From the build log for e.g. pub-win-be:

@@@BUILD_STEP pub and pkg  tests failures@@@

FAILED: none-vm-checked release_ia32 pkg/analyzer/test/generated/all_the_rest_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
...
FAIL: FileUriResolverTest | test_resolve_file
&nbsp;&nbsp;Expected: 'E:\does\not\exist.dart'
&nbsp;&nbsp;&nbsp;&nbsp;Actual: 'E:\b\build\slave\pub-win-be\build\dart\does\not\exist.dart'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Which: is different.
&nbsp;&nbsp;Expected: E:\does\not\e ...
&nbsp;&nbsp;&nbsp;&nbsp;Actual: E:\b\build\sl ...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;&nbsp;&nbsp;Differ at offset 3
&nbsp;&nbsp;
&nbsp;&nbsp;package:unittest/src/simple_configuration.dart 119:7        SimpleConfiguration.onExpectFailure
&nbsp;&nbsp;package:unittest/src/simple_configuration.dart 15:28        _ExpectFailureHandler.fail
&nbsp;&nbsp;package:matcher/src/expect.dart 121:9                       DefaultFailureHandler.failMatch
&nbsp;&nbsp;package:matcher/src/expect.dart 95:29                       expect
&nbsp;&nbsp;pkg\analyzer\test\generated\all_the_rest_test.dart 9880:11  FileUriResolverTest.test_resolve_file
&nbsp;&nbsp;dart:mirrors-patch/mirrors_impl.dart 539                    _LocalInstanceMirror.invoke
&nbsp;&nbsp;pkg\analyzer\test\reflective_tests.dart 77:36               _runTest.&lt;fn&gt;
&nbsp;&nbsp;dart:async/zone.dart 902                                    _rootRunUnary
&nbsp;&nbsp;dart:async/zone.dart 804                                    _CustomZone.runUnary
&nbsp;&nbsp;dart:async/future_impl.dart 484                             _Future._propagateToListeners.handleValueCallback
&nbsp;&nbsp;dart:async/future_impl.dart 567                             _Future._propagateToListeners
&nbsp;&nbsp;dart:async/future_impl.dart 358                             _Future._completeWithValue
&nbsp;&nbsp;dart:async/future_impl.dart 412                             _Future._asyncComplete.&lt;fn&gt;
&nbsp;&nbsp;dart:async/zone.dart 895                                    _rootRun
&nbsp;&nbsp;dart:async/zone.dart 796                                    _CustomZone.run
&nbsp;&nbsp;dart:async/zone.dart 704                                    _CustomZone.runGuarded
&nbsp;&nbsp;dart:async/zone.dart 729                                    _CustomZone.bindCallback.&lt;fn&gt;
&nbsp;&nbsp;dart:async/schedule_microtask.dart 41                       _asyncRunCallbackLoop
&nbsp;&nbsp;dart:async/schedule_microtask.dart 48                       _asyncRunCallback
&nbsp;&nbsp;dart:isolate-patch/isolate_patch.dart 84                    _runPendingImmediateCallback
&nbsp;&nbsp;dart:isolate-patch/isolate_patch.dart 131                   _RawReceivePortImpl._handleMessage
...
FAIL: SourceFactoryTest | test_resolveUri_nonAbsolute_absolute
&nbsp;&nbsp;Expected: 'E:\does\not\matter.dart'
&nbsp;&nbsp;&nbsp;&nbsp;Actual: 'E:\b\build\slave\pub-win-be\build\dart\does\not\matter.dart'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Which: is different.
&nbsp;&nbsp;Expected: E:\does\not\m ...
&nbsp;&nbsp;&nbsp;&nbsp;Actual: E:\b\build\sl ...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;&nbsp;&nbsp;Differ at offset 3
&nbsp;&nbsp;
&nbsp;&nbsp;package:unittest/src/simple_configuration.dart 119:7         SimpleConfiguration.onExpectFailure
&nbsp;&nbsp;package:unittest/src/simple_configuration.dart 15:28         _ExpectFailureHandler.fail
&nbsp;&nbsp;package:matcher/src/expect.dart 121:9                        DefaultFailureHandler.failMatch
&nbsp;&nbsp;package:matcher/src/expect.dart 95:29                        expect
&nbsp;&nbsp;pkg\analyzer\test\generated\all_the_rest_test.dart 10619:11  SourceFactoryTest.test_resolveUri_nonAbsolute_absolute
&nbsp;&nbsp;dart:mirrors-patch/mirrors_impl.dart 539                     _LocalInstanceMirror.invoke
&nbsp;&nbsp;pkg\analyzer\test\reflective_tests.dart 77:36                _runTest.&lt;fn&gt;
&nbsp;&nbsp;dart:async/zone.dart 902                                     _rootRunUnary
&nbsp;&nbsp;dart:async/zone.dart 804                                     _CustomZone.runUnary
&nbsp;&nbsp;dart:async/future_impl.dart 484                              _Future._propagateToListeners.handleValueCallback
&nbsp;&nbsp;dart:async/future_impl.dart 567                              _Future._propagateToListeners
&nbsp;&nbsp;dart:async/future_impl.dart 358                              _Future._completeWithValue
&nbsp;&nbsp;dart:async/future_impl.dart 412                              _Future._asyncComplete.&lt;fn&gt;
&nbsp;&nbsp;dart:async/zone.dart 895                                     _rootRun
&nbsp;&nbsp;dart:async/zone.dart 796                                     _CustomZone.run
&nbsp;&nbsp;dart:async/zone.dart 704                                     _CustomZone.runGuarded
&nbsp;&nbsp;dart:async/zone.dart 729                                     _CustomZone.bindCallback.&lt;fn&gt;
&nbsp;&nbsp;dart:async/schedule_microtask.dart 41                        _asyncRunCallbackLoop
&nbsp;&nbsp;dart:async/schedule_microtask.dart 48                        _asyncRunCallback
&nbsp;&nbsp;dart:isolate-patch/isolate_patch.dart 84                     _runPendingImmediateCallback
&nbsp;&nbsp;dart:isolate-patch/isolate_patch.dart 131                    _RawReceivePortImpl._handleMessage
...

**Comment by scheglov** [comment]
I see only one test failing on my Windows machine.
And this [CL](https://dart-review.googlesource.com/#/c/sdk/+/7943) "fixes" it.

But it is possible that some tests fail when you run not on `C:\`, so we might still have a problem even with this CL landed. I will try to land and see what happens.

**Comment by srawlins** [comment]
I suspect this is fixed. We've been doing better on Windows recently. Many users run Windows and it would be surprising if this was still an issue...
