### ISSUE TITLE
Add bool checkedMode optional, named arg to spawn/spawnUri isolate functions

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#21791]
We'd like &quot;pub run&quot; to run its Dart files in an isolate rather than as a subprocess, both to avoid extra Dart VM startup time and to provide it with an accurate view of the stdio it's talking to via [stdioType]. We'd also like to run executables in checked mode when pub itself is not, and to allow users to provide various other VM flags for e.g. debugging. To support all of this, we need some sort of VM-specific means of spawning an isolate with different flags than the parent isolate.

**Comment by kevmoo** [comment]
@lrhn is this resolved as of https://github.com/dart-lang/sdk/commit/5a843ebbf31c16abf92e9afbd8bf78db5deb9b26 ?

**Comment by lrhn** [comment]
I believe @iposva-google has some fix that needs to go in too (because otherwise it might just crash and burn if it manages to compile some code before the checked-mode is set).

**Comment by nex3** [comment]
![lets_party-145404](https://cloud.githubusercontent.com/assets/188/8047775/52f1e4b6-0dfe-11e5-96cf-07117acd3a35.gif)
