### ISSUE TITLE
It should be possible to navigate from an unresolved constructor call to the class

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21800]
Using editor with analysis server, create a file with the following code:

&nbsp;&nbsp;class Foo {
&nbsp;&nbsp;&nbsp;&nbsp;Foo.bar();
&nbsp;&nbsp;&nbsp;&nbsp;Foo.baz();
&nbsp;&nbsp;}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;new Foo();
&nbsp;&nbsp;}

Place the cursor on the word &quot;Foo&quot; in the line &quot;new Foo();&quot;, and press F3 (&quot;open declaration&quot;).

Expected result: the cursor should be moved to the declaration of the class Foo.

Observed result: the cursor doesn't move at all.

This bug is particularly frustrating in conjunction with issue #21799.  As a result of these two issues, the workflow for constructing a class is very difficult if the class only has named constructors and I can't remember their names: I type &quot;new Foo.&quot;, then see that I have no useful completions; then I try to use F3 to navigate to the class so I can see which constructor I want to call, but that doesn't work; so I have to navigate manually to the class declaration (e.g. using the omnibox) to figure out which named constructor I want.  By the time I've done all this I've lost a great deal of my train of thought.

**Comment by srawlins** [comment]
This is working in VS Code today.
