### ISSUE TITLE
Type propagation is either incomplete or not being reported correctly

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21813]
Paste the following into any file that is being analyzed:

test(s) {
&nbsp;&nbsp;var x;
&nbsp;&nbsp;if (s == 1) x = 'a';
&nbsp;&nbsp;else if (s == 2) x = 'b';
&nbsp;&nbsp;else x = 'c';
&nbsp;&nbsp;return x;
}

At every point, 'x' has a propagated type of 'dynamic'. It ought to have a propagated type of 'String' at every point except the declaration.

**Comment by srawlins** [comment]
This is resolved.
