### ISSUE TITLE
include webcomponents.lite.js

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#21831]
I didn't see this in our current pkg source code. But it is provided by:
https://github.com/webcomponents/webcomponentsjs

(side note: we don't seem to have a proper pkg- label for webcomponents. So I just used CustomElements)

**Comment by jmesserly** [comment]
maybe @jakemac53 can take a look? I presume this is needed for Polymer.dart 1.0

**Comment by jakemac53** [comment]
yes, I was aware of this but hadn't filed an issue yet, thanks!

**Comment by jmesserly** [comment]
moved: https://github.com/dart-lang/web-components/issues/22
