### ISSUE TITLE
Throw in expression of "await expression" is converted to Future with error.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21858]
Specification says about &quot;await e&quot;: 
&quot;First, the expression e is evaluated. Next:
If e raises an exception x, then an instance f of class Future is allocated
and later completed with x.&quot;

This is a surprising difference between &quot;await e;&quot; and &quot;var x = e; await x;&quot;, which doesn't seem to have any rationale (any argument for creating the error future should also apply to the variable-version).

Also, the documentation for &quot;throw expression&quot; only talks about propagating the exception to an enclosing try/catch handler, not to an enclosing await operator, so the description of await doesn't match what &quot;throw&quot; does.

I suggest not special casing the expression of an await any more than any previous expression in the same &quot;async basic block&quot;.

(This quote above also doesn't say what happens with the stack trace).

**Comment by zoechi** [comment]
I just run into an issue that looks like what is discussed here but I'm not sure

```
_testTaskImpl() async {
  try {
    await _dindStartForTest();
  } catch (e, s) {
    print(e);
    print(s);
    rethrow;
  } finally {
    await _dindCleanupAfterTest();
  }
}
```
The print statements print

```
type 'List' is not a subtype of type 'Stream' of 'stream'.
#0      StreamIterator.StreamIterator (dart:async/stream.dart:1676)
#1      _dindStartForTest.<_dindStartForTest_async_body> (file:///home/zoechi/dart/bwu_docker/tool/grind.dart)
#2      _rootRunUnary (dart:async/zone.dart:911)
#3      _CustomZone.runUnary (dart:async/zone.dart:811)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#6      _Future._complete (dart:async/future_impl.dart:358)
#7      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#8      _rootRun (dart:async/zone.dart:900)
#9      _CustomZone.run (dart:async/zone.dart:803)
#10     _CustomZone.runGuarded (dart:async/zone.dart:709)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#12     _rootRun (dart:async/zone.dart:904)
#13     _CustomZone.run (dart:async/zone.dart:803)
#14     _CustomZone.runGuarded (dart:async/zone.dart:709)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
Without the print statements the application exists only with 

```
type 'List' is not a subtype of type 'Stream' of 'stream'.
#0      StreamIterator.StreamIterator (dart:async/stream.dart:1676)
#1      _dindStartForTest.<_dindStartForTest_async_body> (file:///home/zoechi/dart/bwu_docker/tool/grind.dart)
```
which is not very helpful.

Should I create a separate issue for this?

**Comment by zoechi** [comment]
Doesn't look like it's related. I don't get a better stack trace even when I don't use try/catch/rethrow. Sorry for the noise.
