### ISSUE TITLE
Analysis engine missing error case

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21899]
Enter the following in any Dart file:

class C {
&nbsp;&nbsp;int v;
&nbsp;&nbsp;const C(this.v);
}

This should produce an error, but doesn't:

It is a compile-time error if a constant constructor is declared by a class that
has a non-final instance variable

**Comment by srawlins** [comment]
Analyzer now reports:

> Can't define a const constructor for a class with non-final fields.
