### ISSUE TITLE
Analyzer type equality is wrong on nested typedefs.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#21912]
The attached file has two assignments statements each assigning a rhs to a lhs of an incompatible type.  The two lhs variables have types which are equal up to expansion of typedefs, but the analyzer only warns on one of the assignments.  Based on some printf debugging, I believe that there may be a bug in the element type equality in the presence of nested typedef instantations.

leafp@leafp-linux:~$ ./dart/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 1.8.3

leafp@leafp-linux:~$ ./dart/dart-sdk/bin/dartanalyzer tmp/dart_test/bin/main.dart 
Analyzing [tmp/dart_test/bin/main.dart]...
[warning] A value of type 'Function2 (/usr/local/google/home/leafp/tmp/dart_test/bin/main.dart)' cannot be assigned to a variable of type 'Function2 (/usr/local/google/home/leafp/tmp/dart_test/bin/main.dart)' (/usr/local/google/home/leafp/tmp/dart_test/bin/main.dart, line 19, col 12)
[hint] The value of the local variable 'left' is not used (/usr/local/google/home/leafp/tmp/dart_test/bin/main.dart, line 16, col 63)
1 warning found.

______
**Attachment:**
[main.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-21912/comment-0/main.dart) (481 Bytes)

**Comment by stereotype441** [comment]
Looks like I forgot to close the bug when I fixed it on June 1.  I've just confirmed that it indeed still fixed.
