### ISSUE TITLE
Automatically add imports when pasting code

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21932]
When code is copied from one library to another it can contain references to names that are not yet visible in the target library. The imports for those names should automatically be inserted when the code is pasted.

I have made this an analyzer issue because the analysis server needs to be enhanced to support this before the editor can be updated.

**Comment by srawlins** [comment]
Is this different from #21139? Seems like a dup.

**Comment by bwilkerson** [comment]
I think #21139 is about having a way to ask all necessary imports to be added after editing a file for a while. This is about not requiring an extra step in one special case.

**Comment by bwilkerson** [comment]
This is being addressed by the import aware copy and paste APIs.
