### ISSUE TITLE
scheduled_test windows bot is failing strangely

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#21936]
See http://chromegw.corp.google.com/i/client.dart.packages/builders/packages-windows-scheduled_test/builds/2/steps/annotated_steps/logs/stdio. The test infrastructure seems to be having trouble deleting &quot;.flaky.log&quot;.

**Comment by srawlins** [comment]
scheduled_test is dead. https://pub.dartlang.org/packages/scheduled_test
