### ISSUE TITLE
Allow main() to be any kind of member, not just a function declaration

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#21951]
The spec is changing to allow the main function of  a script to be defined via a getter (implictly defined by a field, or explcitly as a getter). See section 18.4 in the latest draft (1.9) in the repo. TC52 has been given a heads up why this was necessary; it will have to go into the 3rd edition at the next spec revision, but AFIK no one objects and it will likely be approved in the next meeting on January 14th.

See also https://codereview.chromium.org/815963002/ for tests.

**Comment by lrhn** [comment]
The current plan is to only allow `main` functions.
