### ISSUE TITLE
Missing fix for undefined named parameter

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21965]
Enter the following text:

class C {
&nbsp;&nbsp;f() {
&nbsp;&nbsp;&nbsp;&nbsp;g(1, 2, also: 3);
&nbsp;&nbsp;}

&nbsp;&nbsp;g(int first, int second) {}
}

Place the cursor inside the word &quot;also&quot; and press Command-1 to get a list of quick fixes. It would be nice if the list included an option to define a named parameter in the method 'g'.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/54360
