### ISSUE TITLE
Docs for LibraryElement.isInSdk are wrong

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#21974]
Instead of &quot;Return `true` if this library is the dart:core library&quot;

should mention &quot;dart:\*&quot; or similar

**Comment by srawlins** [comment]
Aparently fixed. https://github.com/dart-lang/sdk/blob/ac48484a07ef3a8ad0109f4dfccfea2ce33267e0/pkg/analyzer/lib/dart/element/element.dart#L1430..L1433
