### ISSUE TITLE
Remove the StreamTransformer class.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21996]
The StreamTransformer class is an interface class with a single method.
That's unnecessary overhead, and it can be replaced by a function type
instead.

**Comment by thosakwe** [comment]
Is this interface still going to be removed?

**Comment by dgrove** [comment]
Are any further changes planned here for 2.0 @lrhn ?

**Comment by lrhn** [comment]
No, we decided not to make this change. Too breaking, not enough benefit.
