### ISSUE TITLE
Add a way to get a callback called before the current isolate shuts down.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#21999]
Sometimes its useful to set up cleanup that is called no matter how an isolate terminates, to ensure that resources are freed. For native extensions, this is even more important, since they are not freed automatically.

I suggest adding a way to add one or more callbacks for when an isolate would otherwise shut down.

Example:
&nbsp;&nbsp;Isolate.addOnBeforeExitHandler(callback);  // callback: ()-&gt;void
(with a corresponding remove function)

When an isolate is about to shut down (no open ReceivePort or pending events), and any on-before-exit callbacks have been added, all registered callbacks are removed and called, in some unspecified order. This can not be interrupted (they will all be called eventually).

This may trigger more async operations, keeping the isolate alive until cleanup is done. It might even keep the isolate alive indefinitely (but that's really discouraged!). More callbacks can be added during cleanup.

The next time there are nothing keeping the isolate alive, this repeats until there are also no registered callbacks, at which point the isolate properly exits. 
For well-written code, there should never be more than one clean-up phase, but we won't prevent it.

The Isolate.kill operation should be defined as clearing the event queues and closing all receive ports, so that cleanup will be called.
Calling kill again might interrupt cleanup, but at least the synchronous cleanup will be done (it cannot interrupt the calling of the registered cleanup functions, even if using &quot;kill immediate&quot;, which we should probably remove since it won't work).

**Comment by floitschG** [comment]
Related: https://github.com/dart-lang/sdk/issues/12170

**Comment by natebosch** [comment]
addOnExitListener now exists so I think this is complete.
https://api.dartlang.org/stable/2.0.0/dart-isolate/Isolate/addOnExitListener.html
