### ISSUE TITLE
Dart Analyzer fails to produce a warning for constant abstract instance initialization

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22010]
The Dart analyzer fails to produce a error with the following co19 test:

Language/12_Expressions/12_Instance_Creation/2_Const_A11_t01.

ECMA-208 p63 says 'It is a compile-time error if evaluation of a constant object results in an uncaught exception being thrown'. Hence, this test should raise a compile time error:

&nbsp;&nbsp;\- if we were to evaluate 'new A()' at runtime, an 'AbstractClassInstantiationError' must be thrown (p62)

&nbsp;&nbsp;\- evaluation of 'const A()' produces the value of 'new A()' (p63, noting that canonicalization can be ignored: it does not occur the first time we create an A, as here)

&nbsp;&nbsp;\- so the use of 'const A()' must be a compile time error, because nothing catches said 'AbstractClassInstantiationError'.

That compile-time error is currently missing.

See also issues
https://code.google.com/p/dart/issues/detail?id=21134
and
https://code.google.com/p/co19/issues/detail?id=714
and
https://code.google.com/p/dart/issues/detail?id=22007

**Comment by sgrekhov** [comment]
Now the test, mentioned above, renamed to Language/Expressions/Instance_Creation/Const/abstract_class_t01

**Comment by srawlins** [comment]
Yay analyzer now produces an error:

> Abstract classes can't be instantiated.
