### ISSUE TITLE
Subtyping definition in the spec doesn't match intended (and implemented) behavior

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#22033]
The spec definition of subtyping for generic instantiation with function types doesn't seem to capture the intended (and implemented) behavior.  Per conversation with Gilad, I believe this is a spec bug and not an implementation bug.

Consider the following function types:

typedef num Top(num x);
typedef int Bot(int x);

By the spec's definition of function subtyping, Bot &lt;: Top and Top &lt;: Bot.

By the spec's definition of function specificity, Bot &lt;&lt; Top, but Top &lt;/&lt; Bot

Question: is List&lt;Top&gt; &lt;: List&lt;Bot&gt; ?

My understanding was that this should be true, and running code through the VM agrees (in the program below all of the print statements are executed), but I can't come up with a reading of the spec which justifies this. 

Per the spec, List&lt;Top&gt; &lt;: List&lt;Bot&gt; iff [_|_ / dynamic] List&lt;Top&gt; &lt;&lt; List&lt;Bot&gt;

The only specificity rule that obviously applies is the rule for generic applications, which says that 

List&lt;Top&gt; &lt;&lt; List&lt;Bot&gt; if Top &lt;&lt; Bot

But I believe per above that Top &lt;/&lt; Bot, so this doesn't seem to follow.

// Example program, all print statements are executed by the vm.
void testF() {
&nbsp;&nbsp;&nbsp;var t = &lt;Top&gt;[];
&nbsp;&nbsp;&nbsp;var b = &lt;Bot&gt;[];
&nbsp;&nbsp;if (t is List&lt;Top&gt;) print(&quot;t is List&lt;Top&gt;&quot;);
&nbsp;&nbsp;if (t is List&lt;Bot&gt;) print (&quot;t is List&lt;Bot&gt;&quot;);
&nbsp;&nbsp;if (b is List&lt;Top&gt;) print(&quot;b is List&lt;Top&gt;&quot;);
&nbsp;&nbsp;if (b is List&lt;Bot&gt;) print (&quot;b is List&lt;Bot&gt;&quot;);
}

**Comment by eernstg** [comment]
I agree with the analysis and the conclusion that we cannot show `List<Top> <: List<Bot>`, but how did you conclude that this couldn't be the intention, and that the vm behavior is the solution?

**Comment by leafpetersen** [comment]
I could be wrong about intent.   But Dart 1.0 generics are fairly universally described as being covariant, and the very standard meaning of covariant is that `S <: T => F<S> <: F<T>`.  So it is either inaccurate to describe Dart 1.0 generics as covariant, or the spec language does not match the intention.

**Comment by eernstg** [comment]
I believe that we can close this issue as being irrelevant for Dart 2 (where function type subtyping is much less complex). @leafpetersen, please reopen if it is still relevant.
