### ISSUE TITLE
Meta-bug for Analysis Server plugin capability

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#22031]
This bug is for tracking plugin support for the analysis server.

**Comment by pq** [comment]
Behind the scenes, the dynamic bootloader is blocked until we get `Isolate.spawnUri` support for package resolution configuration of spawned isolates (https://github.com/dart-lang/sdk/issues/23951).

**Comment by bwilkerson** [comment]
We have static plugability, and I believe that's sufficient for now, so I'm closing this issue.
