### ISSUE TITLE
Missing error for duplicated initializing formal

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#22057]
Given the following code:

---

class C {
&nbsp;&nbsp;String f;
&nbsp;&nbsp;C(this.f, {this.f: ''});
}

---

There should be an error generated because the field 'f' is initialized more than once in the constructor. The VM currently has this behavior and the specification will be updated to clarify that this is the expected behavior.

**Comment by eernstg** [comment]
The feature described in #26655 (access to initializing formals) implies that initializing formals will be added to the formal parameter scope for resolution in the initializer list, and that feature has been scheduled for inclusion in the language. The name conflict described in this issue will be in line with the spec after the spec has been updated. So it should be possible to resolve this issue as part of the same process where #26655 is implemented.

**Comment by eernstg** [comment]
I believe this issue is now obsolete (the example does create a name clash which is a compile-time error, and the analyzer does detect it).

Closing. Please reopen if you think there is still an issue.
