### ISSUE TITLE
Compiler error with setter and final field

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#22065]
Compile this file:

==&gt; foo.dart &lt;==
class I {
&nbsp;&nbsp;var field;
}

class C implements I {
&nbsp;&nbsp;final field;

&nbsp;&nbsp;C(this.field);

&nbsp;&nbsp;void set field(_) {
&nbsp;&nbsp;&nbsp;&nbsp;throw &quot;unsupported&quot;;
&nbsp;&nbsp;}

&nbsp;&nbsp;m() {
&nbsp;&nbsp;&nbsp;&nbsp;print(field);
&nbsp;&nbsp;}
}

main() {
&nbsp;&nbsp;new C(1).m();
}

The compiler prints:

foo.dart:10:12:
Error: Duplicate definition of 'field'.
Try to rename or remove this definition.
&nbsp;&nbsp;void set field(_) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^
foo.dart:6:9:
Info: Existing definition of 'field'.
&nbsp;&nbsp;final field;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^
foo.dart:8:5:
Error: 'field' is not a field.
&nbsp;&nbsp;C(this.field);
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^
foo.dart:15:11:
Error: Duplicate definition of 'field'.
Try to rename or remove this definition.
&nbsp;&nbsp;&nbsp;&nbsp;print(field);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^
Error: Compilation failed.

I'm not sure the first error is correct. Also, the duplicated element leads to a bunch of confusing messages. The extra messages are probably my fault after removing Compiler.reportFatalError.

**Comment by srawlins** [comment]
dart2js now successfully compiles this code, and it prints 1 when executed.
