### ISSUE TITLE
Update Isolate API docs when features are implemented in all runtimes

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22067]
The following methods are being implemented across the VM and dart2js and Dartium:

addErrorListener
addOnExistListener
kill
pause
ping
removeErrorListener
removeOnExitListener
resume
setErrorsFatal
a `paused` parameter for spawnUri and spawn

When dart2js, VM, and Dartium support all of these, we'll need to update the respective API docs.

**Comment by kevmoo** [comment]
Isolate is going away on the web. Closing.
