### ISSUE TITLE
incorrect AST when space is missing between generic type and field name

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#22078]
I found this strange bug in the dart analyzer. Consider this code:

&nbsp;&nbsp;&nbsp;&nbsp;class A&lt;T&gt; {}
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;class Test {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&lt;int&gt; _x;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&lt;int&gt;_y;
&nbsp;&nbsp;&nbsp;&nbsp;}

This is valid Dart, the space after the `&gt;` is optional. When I run this through the analyzer and resolve the tree I can retrieve getters out of the element model of `Test`. They correctly indicate that these getters are synthetic, but when I try to retrieve their defining variable and original AST node, I get a different result. 

Below is a sample program to reproduce the issue. If you run this code on the file above you'll get the following output:

&nbsp;&nbsp;&nbsp;&nbsp;_x: true null A&lt;int&gt; _x _x
&nbsp;&nbsp;&nbsp;&nbsp;_y: true null A&lt;int&gt; _y null

This code assumes that the test file above is in the same directory and it's called &quot;space.dart&quot;
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:convert' as convert;
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:io';
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:analyzer/src/generated/engine.dart';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:analyzer/src/generated/java_io.dart';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:analyzer/src/generated/sdk_io.dart';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:analyzer/src/generated/source.dart';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:analyzer/src/generated/source_io.dart';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:path/path.dart' as path;
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var context = AnalysisEngine.instance.createAnalysisContext();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context.sourceFactory = new SourceFactory([
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new DartUriResolver(new DirectoryBasedDartSdk(new JavaFile(dartSdkDirectory))),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new FileUriResolver(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var filepath = new Uri.file(path.absolute('space.dart'));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var source = context.sourceFactory.forUri2(filepath);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var lib = context.computeLibraryElement(source);
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var gX = lib.getType('Test').getGetter('_x');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var gY = lib.getType('Test').getGetter('_y');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('_x: ${gX.isSynthetic} ${gX.node} ${gX.variable} ${gX.variable.node}');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('_y: ${gY.isSynthetic} ${gY.node} ${gY.variable} ${gY.variable.node}');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;final String dartSdkDirectory = () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool isSdkDir(String dirname) =&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new File(path.join(dirname, 'lib', '_internal', 'libraries.dart'))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.existsSync();
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String executable = Platform.executable;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (path.split(executable).length == 1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// TODO(sigmund,blois): make this cross-platform.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// HACK: A single part, hope it's on the path.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;executable = Process.runSync('which', ['dart'],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdoutEncoding: convert.UTF8).stdout.trim();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// In case Dart is symlinked (e.g. homebrew on Mac) follow symbolic links.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var link = new Link(executable);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (link.existsSync()) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;executable = link.resolveSymbolicLinksSync();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var sdkDir = path.dirname(path.dirname(executable));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (isSdkDir(sdkDir)) return sdkDir;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var parts = path.split(dartDir);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// If the dart executable is within the sdk dir then get the root.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (parts.contains('dart-sdk')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var dartSdkDir = path.joinAll(parts.take(parts.indexOf('dart-sdk') + 1));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (isSdkDir(dartSdkDir)) return dartSdkDir;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return null;
&nbsp;&nbsp;&nbsp;&nbsp;}();

**Comment by srawlins** [comment]
This is stale, as there is a new parser. Please re-open if you see this behavior with Fasta.
