### ISSUE TITLE
Request to refactor JavaFile name

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22075]
The name JavaFile is pretty confusing, coming from an analyzer written in Dart. It infects the code of people who use analyzer (e.g. dartdoc).

Can we come up with a new name? :)

**Comment by pq** [comment]
@bwilkerson I see that `JavaFile` still lingers but I don't clients need to know about it anymore... Is that right?

**Comment by bwilkerson** [comment]
It is not part of the public API, and, as far as I know, no clients are currently referencing it. I'm closing this under the assumption that it is no longer an issue.
