### ISSUE TITLE
Provide a means to wait until a file lock can be acquired

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#22081]
The existing file locking functions only provide the means to check whether a lock is available at a given point in time. Applications frequently want to acquire a lock immediately upon it becoming available, and I believe the OS APIs provide the means to do so. Please expose this in the API.

**Comment by zanderso** [comment]
https://github.com/dart-lang/sdk/commit/678cb048ed0eaa96729be7c955c7fadd32cf7024 adds a blocking option to `lock` and `lockSync`. Adding a timeout would entail a deeper refactoring, so let's skip it for now. Closing this issue as the originally requested feature has been added.
