### ISSUE TITLE
Memory leaks when building a script snapshot

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#22121]
When running gen_snapshot for building a script snapshot, asan detects memory leaks.

e.g.:

out/Release_asan/gen_snapshot --error_on_bad_type --error_on_bad_override --snapshot=snapshot_gen.bin snapshot.dart
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdout: ''
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stderr: '
&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;==
==6989==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 841245 byte(s) in 82 object(s) allocated from:
&nbsp;&nbsp;&nbsp;&nbsp;#­0 0x48b789 in \__interceptor_malloc (gen_snapshot+0x48b789)
&nbsp;&nbsp;&nbsp;&nbsp;#­1 0x4cad2a in dart::bin::DartUtils::ReadFile(unsigned char const\*\*, long\*, void\*) dart/runtime/bin/dartutils.cc:197:53
&nbsp;&nbsp;&nbsp;&nbsp;#­2 0xe70cd2 in dart::GetLibrarySource(dart::Library const&amp;, dart::String const&amp;, bool) dart/runtime/vm/bootstrap.cc:130:3

During a build of the standalone embedder we generate full snapshots, so probably these code paths aren't being exercised by the buildbot.

**Comment by kodandersson** [comment]
Does this still happen after the clean VM shutdown CL?

**Comment by kodandersson** [comment]
Superseded by https://github.com/dart-lang/sdk/issues/24467
