### ISSUE TITLE
Watcher exception

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#22139]
Just saw this in my log with Analysis Server turned on...

NoSuchMethodError: method not found: 'path'
Receiver: null
Arguments: []
# ­0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
# ­1      _FileSystemWatcher._listenOnSocket.&lt;anonymous closure&gt;.getPath (dart:io-patch/file_patch.dart:164)
# ­2      _FileSystemWatcher._listenOnSocket.&lt;anonymous closure&gt; (dart:io-patch/file_patch.dart:197)
# ­3      _rootRunUnary (dart:async/zone.dart:906)
# ­4      _CustomZone.runUnary (dart:async/zone.dart:804)
# ­5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
# ­6      _StreamController.add (dart:async/stream_controller.dart:412)
# ­7      _RawSocket._RawSocket.&lt;anonymous closure&gt; (dart:io-patch/socket_patch.dart:1300)
# ­8      _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:695)
# ­9      _asyncRunCallback (dart:async/schedule_microtask.dart:48)

**Comment by brianquinlan** [comment]
Can not reproduce.
