### ISSUE TITLE
dart2js crashes when generic parameters fail to close properly

### ISSUE THREAD

**Issue by skoga** [dart-lang/sdk#22135]
**What steps will reproduce the problem?**

Here is the code snippet that causes the problem:

@Injectable()
class SampleDataService {

&nbsp;&nbsp;...

&nbsp;&nbsp;Future&lt;List&lt;Map&lt;String, dynamic&gt;&gt; getAll() {
&nbsp;&nbsp;&nbsp;&nbsp;return new Future.value(_sampleData);
&nbsp;&nbsp;}

&nbsp;&nbsp;...
}

**What is the expected output? What do you see instead?**

I'd expect dart2js to not crash.

It crashes with:

method not found: 'next'
Receiver: null
Arguments: []
dart:core

in:

pkg/compiler/lib/src/scanner/parser.dart 937
...

Note that I'm not including the full stack trace atm since it includes internal google paths. Let me know if this is kosher or not, and I'll add it to the bug report.

**What version of the product are you using?**

1.9.0 dev 4

**On what operating system?**

linux

**What browser (if applicable)?**

n/a

**Please provide any additional information below.**

**Comment by sigmundch** [comment]
handled by the CFE
