### ISSUE TITLE
Analyzer has no public interface for querying the values of constants

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22140]
The values of constants are accessible after resolution via the &quot;evaluationResult&quot; getters of the classes ConstFieldElementImpl, ConstLocalVariableElementImpl, ConstTopLevelVariableElementImpl, DefaultFieldFormalParameterElementImpl, DefaultParameterElementImpl, and ElementAnnotationImpl.  But these getters are not exposed through any interface that is intended to be used by clients.

We should add &quot;evaluationResult&quot; to the appropriate public interfaces, and then mark the two &quot;ConstantEvaluator&quot; classes (in ast.dart and constant.dart) as deprecated, and we should update the comments above those classes to point to the public interfaces that the client should use to query constant values.

**Comment by bwilkerson** [comment]
A public interface has been added.
