### ISSUE TITLE
Make Events fully fakable so file transfers can be tested

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#22156]
As it stands, the major problem here is that fake events (e.g., MouseEvents) being dispatched to elements in tests cannot be fully populated with fake Files, FileLists, and DataTransfers. Using mocks fails because dispatching these events involves native code that expects real objects.

Is it possible to make it so that fully fakeable (or mockable) events can be dispatched to elements for testing?

**Comment by alan-knight** [comment]
I think the answer is no, it's not possible. Unless we have an approach, closing.
