### ISSUE TITLE
VM: ByteData access hits unaligned write on ARM

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#22151]
I attached a regression test:

$ out/ReleaseSIMARM/dart offset.dart 
Simulator hit unaligned write at 0xf68916e5, pc=0xf640fd00

0xf640fd00    e5801008               str r1, [r0, #+8]
sim&gt;

---

**Attachment:**
[offset.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-22151/comment-0/offset.dart) (242 Bytes)

**Comment by rmacnak-google** [comment]
26245de7a560de03faf382ec5b94fdff2b96e8c1
d5580f3b00f1631b6e735e9b757be09a9eb72896
72e1775fd1805778f7f2ca4f7242dcfb0afdc8a2
dddd96cfd2984f4c157b8c3632ad2b5dcb25b9fc
