### ISSUE TITLE
Memory leak on ie10 when running test scripts

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22203]
When running test.py on ie10, with the dart2js compiler, somehow the browser enters a state where it is allocating between 1 and 3 MB of memory per second, and it continues doing this until it is using 7 GB of memory, then crashes on an 8 GB machine.  This weird allocation continues even if the driving page and all test pages are closed, and only a new tab remains.

Also, the allocation does not start until about 30 seconds after the driver page starts running tests.  If the driver page is closed during that period, then the browser never enters this continually allocating mode.

This is happening on ie10 on Windows 8.  On a sharded test runner running ie10 on Windows 7, the allocation happens, exactly as before, but there seem to be successful garbage collections, and the total memory usage stays between 100 and 200 MB.

IE 11 on Windows 7 seems fine, and IE 11 on Windows 8 uses almost no memory at all.

**Comment by matanlurey** [comment]
This is a browser from years ago.
