### ISSUE TITLE
Analysis server failed to detect some filesystem changes during git rebase

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22218]
Yesterday, using Dart Editor with analysis server, I performed a &quot;git rebase&quot; which caused the following operations to occur:
1. pkg/analyzer/lib/src/generated/resolver.dart was changed on disk from a state where the TypeProviderImpl constructor required 2 argument to a state where it required 1 argument.  Other files were updated as well, including the file pkg/analyzer/test/generated/resolver_test.dart, which contains a call to the TypeProviderImpl constructor.
2. Immediately afterward (&lt;1 second later), pkg/analyzer/lib/src/generated/resolver.dart was changed back to a state where the TypeProviderImpl constructor required 2 arguments (although not the original state of the file).  Again, other files were also updated, including pkg/analyzer/test/generated/resolver_test.dart.

Both operations should have left the code base should have been in a state without errors and warnings.  However, after the second operation, I saw this warning in the editor's &quot;problems&quot; view, at the site of resolver_test.dart's call to the TypeProviderImpl constructor: &quot;1 positional arguments expected, but 2 found&quot;.  Based on the state of the files in the file system this warning should not have been shown.

I clicked on the warning to navigate to the code--this took me to the site of the call to the TypeProviderImpl constructor.  Then I used the &quot;F3&quot; button to attempt to navigate to the TypeProviderImpl constructor.  This took me to a nonsensical location in the resolver.dart file (character offset 477920, which is midway through an unrelated identifier).  Note that character offset 477920 is the correct location of the TypeProviderImpl constructor after operation 1 above.

Looking at the state of the analysis server through its http debugging interface, it appears that all analysis of the resolver.dart file came from the revision after operation 1, and fails to account for the changes introduced by operation 2.

I suspect there is a short window of time after a file change during which the analysis server is insensitive to further changes to the same file.  So what could have happened is this:
- Operation 1 occurred.
- The analysis server was informed of the files changed by operation 1 (including resolver.dart), and became insensitive to further changes in resolver.dart for a short period of time.
- The analysis server read the file resolver.dart from the file system, reading its state after operation 1.
- Operation 2 occurred.
- The analysis server once again became sensitive to changes to resolver.dart, but by this time it had missed the changes due to operation 2.

To further debug this problem I will need to add instrumentation to the code to track the filesystem operations performed by the analysis server, and the messages from the file watcher package to the analysis server.  Then I will need to wait for the problem to occur again and analyze the logs.

**Comment by devoncarew** [comment]
assumed stale
