### ISSUE TITLE
html canvas test fails on ie10 on Windows 8

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22216]
12 tests are failing because the color values are not the expected ones.  They seem to be mainly off by 1.  The following tests are failing on ie10 on the Windows 8 buildbot, with failures like:

Exception: Expect.equals(expected: &lt;rgba(255, 0, 0, 0.8)&gt;, actual: &lt;rgba(255, 0, 0, 0.9607843137254902)&gt;) fails.

value: Exception: deepEquals([0, 128, 0, 255], [1, 128, 0, 255], ) fails
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[cause: Expect.equals(expected: &lt;0&gt;, actual: &lt;1&gt;) fails.]

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;value: Exception: deepEquals([0, 128, 0, 255], [1, 129, 0, 255], , 'test 5') fails
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[cause: Expect.equals(expected: &lt;0&gt;, actual: &lt;1&gt;) fails.]

The tests that are failing are:
co19/LayoutTests/fast/canvas/set-colors_t01
co19/LayoutTests/fast/canvas/drawImage-with-negative-source-destination_t01
co19/LayoutTests/fast/canvas/canvas-scale-shadowBlur_t01
co19/LayoutTests/fast/canvas/canvas-getImageData-negative-source_t01
co19/LayoutTests/fast/canvas/canvas-save-restore-with-path_t01
co19/LayoutTests/fast/canvas/canvas-set-properties-with-non-invertible-ctm_t01
co19/LayoutTests/fast/canvas/canvas-modify-emptyPath_t01
co19/LayoutTests/fast/canvas/canvas-to-canvas_t01
co19/LayoutTests/fast/canvas/canvas-pattern-behaviour_t01
co19/LayoutTests/fast/canvas/canvas-save-restore_t01

**Comment by matanlurey** [comment]
This is a browser from years ago.
