### ISSUE TITLE
html_storage_quota_test is crashing in debug mode (both chrome 38 and chrome 39)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#22225]
/usr/local/google/home/asiva/workspace/dartium-tot/src/out/Debug/content_shell --no-timeout --dump-render-tree 'http://127.0.0.1:43356/root_build/generated_tests/none-drt/multitest_html_storage_quota_test_missingenumcheck/test.html?crossOriginPort=54068'

CONSOLE MESSAGE: dart-calling-main
Observatory listening on http://127.0.0.1:54380
CONSOLE MESSAGE: dart-main-done
CONSOLE MESSAGE: line 78: {
&nbsp;&nbsp;&quot;type&quot;: &quot;message_received&quot;,
&nbsp;&nbsp;&quot;value&quot;: &quot;unittest-suite-wait-for-done&quot;,
&nbsp;&nbsp;&quot;timestamp&quot;: 3.029
}
SHOULD NEVER BE REACHED
../../third_party/WebKit/Source/modules/quota/StorageQuota.cpp(67) : blink::WebStorageQuotaType blink::(anonymous namespace)::stringToStorageQuotaType(const WTF::String &amp;)
1   0x3e30983
2   0x3e307fa
3   0x40cd8d4
4   0x6bb889b
5   0x7fa70c546296
Received signal 11 SEGV_MAPERR 0000fbadbeef
#­0 0x0000008369fe base::debug::StackTrace::StackTrace()
#­1 0x000000836530 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#­2 0x7fa7179d8340 &lt;unknown&gt;
#­3 0x000003e30992 blink::(anonymous namespace)::stringToStorageQuotaType()
#­4 0x000003e307fa blink::StorageQuota::queryInfo()
#­5 0x0000040cd8d4 blink::DartStorageQuotaInternal::queryInfoCallback()
#­6 0x000006bb889b dart::NativeEntry::NativeCallWrapper()
#­7 0x7fa70c546296 &lt;unknown&gt;
&nbsp;&nbsp;r8: 00007fa71c9dea00  r9: 0000000000000001 r10: 00007fa715691be0 r11: 0000000000000000
&nbsp;r12: 00003537fdfa4020 r13: 00007fa70b50b5b1 r14: 00007fa70d411b69 r15: 00007fa70b50b5b1
&nbsp;&nbsp;di: 0000000000000000  si: 00000000efcdab90  bp: 00007fff32006ca0  bx: 00000000040cd820
&nbsp;&nbsp;dx: 0000000000000000  ax: f7b830e233c14500  cx: 00000000fbadbeef  sp: 00007fff32006c80
&nbsp;&nbsp;ip: 0000000003e30992 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000006
&nbsp;trp: 000000000000000e msk: 0000000000000000 cr2: 00000000fbadbeef
#CRASHED - renderer (pid 22023)
Content-Type: text/plain
#CRASHED - renderer (pid 22023)

**Comment by alan-knight** [comment]
StorageQuota is an API that's not enabled. We should just remove the tests and not generate the classes.
