### ISSUE TITLE
Test pkg/docgen/test/inherited_comments_test fails after r43350

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#22233]
The test hardcodes part of the Iterable dartdoc.
The Iterable documentation was updated in r43350, and no longer matches the test.
Please don't hard-code system library structure or documentation into tests unless those tests are intended to prevent changes to the structure or documentation. Use libraries designed for the test instead, that keeps the test from failing even if there is no bug.

**Comment by sethladd** [comment]
Thanks for the report. However, we don't plan to address this issue with dartdocgen. New dartdoc tool coming online: https://github.com/dart-lang/dartdoc
