### ISSUE TITLE
Step Into for await goes into AsyncCompleter, not into the user's method

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22277]
Consider this code:

a() async {
&nbsp;&nbsp;return await b();
}

b() async {
&nbsp;&nbsp;return await c();
}

c() async {
&nbsp;&nbsp;return 42;
}

sync() {
&nbsp;&nbsp;return 1;
}

main() async {
&nbsp;&nbsp;print(sync());
&nbsp;&nbsp;print(await a());
}

Set breakpoint inside of a().

Run in Dart Editor.

Breakpoint stops in a(). Yay!

Hit &quot;Step Into&quot;.

Expected: user is taken to inside of b().

Actual: user is taken to AsyncCompleter's complete.

Tested with Dart Editor version 1.9.0.dev_05_01 (DEV)

**Comment by rmacnak-google** [comment]
Observatory's debugger added a related command for asynchronous-step-over in 1.12. I'll look into asynchronous-step-into.

**Comment by jrote1** [comment]
Any news on this issue?

**Comment by rmacnak-google** [comment]
Implemented some time ago.
