### ISSUE TITLE
Dart core APIs not properly type checking / crashing

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#22309]
These should throw - probably an ArgumentError - note the incorrect types passed in.

From ianh: 

What's the right behaviour for an SDK function when passed the wrong type? Throw a type mismatch error? I tried some of the SDK functions but they handle bad input really poorly... for example:

void main() { print(new Duration({seconds: 'test'})) } // never terminates
void main() { print(new Symbol(new Object())) } // crashes with a stack with 5 calls deeper than main(), in the print call

**Comment by floitschG** [comment]
This is not a problem with strong mode.
