### ISSUE TITLE
Code Completion suggest prefixed classes as one step

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#22310]
With the following code:

&nbsp;&nbsp;import 'dart:async' as async;
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;new Fut
&nbsp;&nbsp;}

Position the cursor after &quot;new Fut&quot; and request completions.
It would be nice if &quot;async.Future&quot; was suggested as a completion.

**Comment by bwilkerson** [comment]
This now works if you select the `Future` from `dart:async`. If you select the `Future` from `dart:core` it doesn't insert the prefix, but then it doesn't need to. It's a bit unfortunate that we're suggesting `Future` (and `Stream`) twice, but they're effectively exported from both libraries, so it's really part of the bigger question of how to reduce duplication.
