### ISSUE TITLE
Request: a unifying interface for elements that have parameters

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22317]
Hi,

When working with the analyzer API, I find there are at least two different interfaces that expose the 'parameters' getter ==&gt; ExecutableElement and FunctionTypeAliasElement.

I have code that needs to take an element and get its parameters. It would be really awesome if there was a unifying interface (strawman: HasParameters, name doesn't matter) that marks an Element that has the parameters getter.

That way, I can avoid checking if the object instance is an ExecutableElement or FunctionTypeAliasElement. Also, I like to write type annotations, and currently there's no way to do a single annotation or a single `as` cast. :(

Thanks for listening!

**Comment by bwilkerson** [comment]
We now have a superclass named FunctionTypedElement.
