### ISSUE TITLE
Analyzer and dart2js disagree on whether to warn on malbounded type alias instantiation

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#22343]
This code:

class A {}

typedef T Function0&lt;T extends A&gt;();

main() {
&nbsp;&nbsp;Function0&lt;int&gt; f = () =&gt; 3;
&nbsp;&nbsp;f();
}

passes the dart analyzer with no warnings, but gets the following warning from dart2js:

Warning: 'int' is not a subtype of bound 'A' for type variable 'T' of type 'Function0&lt;T&gt;'.
Try to change or remove the type argument.
&nbsp;&nbsp;Function0&lt;int&gt; f = () =&gt; 3;
&nbsp;&nbsp;^^^^^^^^

The VM throws a checked mode error when the code is run indicating the type argument to Function0 is invalid.

**Comment by srawlins** [comment]
Analyzer now reports:

```none
Analyzing 22343.dart...
  error • 'int' doesn't extend 'A'. • 22343.dart:6:13 • type_argument_not_matching_bounds
  lint • Prefer generic function type aliases. • 22343.dart:3:11 • prefer_generic_function_type_aliases
1 error and 1 lint found.
```
