### ISSUE TITLE
async* yield should suspend.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#22351]
As I read the spec chapter 17.16.1, async* functions do not suspend control when yielding unless their stream (should be stream-subscription) has been paused.

I think this is wrong - a program like this:

foo() async* {
&nbsp;&nbsp;var i = 0;
&nbsp;&nbsp;while (true) {
&nbsp;&nbsp;&nbsp;&nbsp;yield i++;
&nbsp;&nbsp;}
}

main() async {
&nbsp;&nbsp;print(await foo().take(10).toList());
}

Diverges because control is never yielded.

**Comment by lrhn** [comment]
The current specification of `yield` now says that `yield` waits until the event has been "delivered".
In practice, that means until the stream listener's event handler has been called and the subscription is not paused.
It's possible (and likely) that the call to deliver the event immediately (except perhaps the very first event, if that happens immediately in response to the listen call). The handler can then immediately pause the subscription, and if not, execution can continue without pausing.

Implementations *may* delay as much as they want, though.

**Comment by natebosch** [comment]
The given example works as expected on the VM and dart2js - I'm going to assume we can close this but please reopen if the spec still needs to be updated.

See also https://github.com/dart-lang/sdk/issues/34775 which might supersede this issue in terms of the handler immediate pausing or cancelling the subscription.
