### ISSUE TITLE
Dartium content shell is flaky crashing

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#22350]
Examples:
http://build.chromium.org/p/client.dart/builders/dartium-win-full-be/builds/2860/steps/drt_core_checked_tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/dartium-lucid32-full-be/builds/5458/steps/drt_core_checked_tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/dartium-mac-full-be/builds/4628/steps/drt_core_checked_tests/logs/stdio

**Comment by a-siva** [comment]
changing owner to terry
