### ISSUE TITLE
Prioritize completion suggestions for "is X" using type information

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#22357]
If we complete:

foo(Statement statement) {
&nbsp;&nbsp;if (statement is ReS^) {
&nbsp;&nbsp;}
}

There are are items: RefactoringStatus and ReturnStatement.

Then ReturnStatement proposal should be before RefactoringStatus, because ReturnStatement is subclass of Statement and RefactoringStatus not - so ReturnStatement is a reasonable type to check, and RefactoringStatus isn't.

**Comment by jwren** [comment]
https://codereview.chromium.org/1871073003/

**Comment by jwren** [comment]
Landed, should be fixed in Dart SDK 1.16 when it is rolled.

**Comment by jwren** [comment]
https://codereview.chromium.org/1876603002/
