### ISSUE TITLE
Consider exposing features of the JS Intl namespace

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#22373]
The Intl namespace, which includes DateFormat, NumberFormat and Collation is now standard. It is still missing, as of Feb 2015 from IE10 and all versions of Safari, so we can't rely on it yet, but it will presumably get there. The Intl package provides some of these features, and might reasonably provide a way to call them via JS Interop, but it does not yet have Collation and the specific capabilities on numbers and dates differ. It might be worth having these exposed in dart:html. It would be good to have a creative answer for the name collision. Since Intl is a namespace in JS, maybe we can just not include it.

See also https://github.com/dart-lang/i18n/issues/353

**Comment by mosuem** [comment]
Done with `package:intl4x`.
