### ISSUE TITLE
Hit assert in VM with syntax error in dart:core code

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#22394]
I was making changes to uri.dart (in corelib), and was using out/DebugIA32/dart_no_snapshot for running with the changes. For some errors in Dart source in uri.dart an assert was hit.

Not sure if this is a real bug as running out/DebugIA32/dart_no_snapshot might not be &quot;supported&quot;.

gdb out/DebugIA32/dart_no_snapshot
GNU gdb (GDB) 7.8-gg10
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;
and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-grtev4-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.

&lt;http://go/gdb-home  FAQ: http://go/gdb-faq  Email: gdb-team  IRC: gdb&gt;
Find the GDB manual and other documentation resources online at:
&lt;http://www.gnu.org/software/gdb/documentation/&gt;.
For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;.
Reading symbols from out/DebugIA32/dart_no_snapshot...done.
Unable to determine compiler version.
Skipping loading of libstdc++ pretty-printers for now.
(gdb) run --ignore-unrecognized-flags --package-root=out/DebugIA32/packages/ /usr/local/prj/dart/git/dart/tests/corelib/uri_query_test.dartStarting program: /usr/local/prj/dart/git/dart/out/DebugIA32/dart_no_snapshot --ignore-unrecognized-flags --package-root=out/DebugIA32/packages/ /usr/local/prj/dart/git/dart/tests/corelib/uri_query_test.dart
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/usr/grte/v4/lib64/libthread_db.so.1&quot;.
WARNING: Giving up trying to load libstdc++ pretty-printers.
Please contact gdb-team@ and provide the program you are debugging.
[New Thread 0xf7c82b40 (LWP 23207)]
[New Thread 0xf73c3b40 (LWP 23208)]
[New Thread 0xf72c2b40 (LWP 23209)]
runtime/bin/dbg_message.cc:1416: error: expected: msg_queue != NULL

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xf72c2b40 (LWP 23209)]
0xf7fdb430 in \__kernel_vsyscall ()
(gdb) bt
#­0  0xf7fdb430 in \__kernel_vsyscall ()
#­1  0xf7cb4607 in raise () from /lib/i386-linux-gnu/libc.so.6
#­2  0xf7cb7a33 in abort () from /lib/i386-linux-gnu/libc.so.6
#­3  0x08285fe5 in dart::DynamicAssertionHelper::Fail (this=0xf72c1334, 
&nbsp;&nbsp;&nbsp;&nbsp;format=0x89a69fa &quot;expected: %s&quot;) at runtime/platform/assert.cc:41
#­4  0x08279083 in dart::bin::DbgMsgQueueList::IsolateEventHandler (
&nbsp;&nbsp;&nbsp;&nbsp;isolate_id=405837560, kind=kShutdown) at runtime/bin/dbg_message.cc:1416
#­5  0x0826602c in dart::DebuggerEventHandler (event=0xf72c141c)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/debugger_api_impl.cc:163
#­6  0x082c9a1a in dart::Debugger::InvokeEventHandler (event=0xf72c141c)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/debugger.cc:237
#­7  0x082c9b80 in dart::Debugger::SignalIsolateEvent (this=0xf71170f8, 
&nbsp;&nbsp;&nbsp;&nbsp;type=dart::DebuggerEvent::kIsolateShutdown) at runtime/vm/debugger.cc:256
#­8  0x082cc3bb in dart::Debugger::Shutdown (this=0xf71170f8)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/debugger.cc:1073
#­9  0x083e353a in dart::Isolate::Shutdown (this=0xf71004a8)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/isolate.cc:1125
#­10 0x082c0900 in dart::Dart::ShutdownIsolate () at runtime/vm/dart.cc:293
#­11 0x08239c62 in dart::Dart_CreateIsolate (script_uri=0x8a2d70d &quot;vm-service&quot;, 
&nbsp;&nbsp;&nbsp;&nbsp;main=0x0, snapshot=0x0, callback_data=0xf7100468, error=0xf72c2294)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_api_impl.cc:1304
#­12 0x082306ec in dart::bin::CreateIsolateAndSetupHelper (
&nbsp;&nbsp;&nbsp;&nbsp;script_uri=0x8a2d70d &quot;vm-service&quot;, main=0x0, package_root=0x88030ba &quot;.&quot;, 
&nbsp;&nbsp;&nbsp;&nbsp;error=0xf72c2294, exit_code=0xf72c2248) at runtime/bin/main.cc:589
#­13 0x08230baa in dart::bin::CreateIsolateAndSetup (
&nbsp;&nbsp;&nbsp;&nbsp;script_uri=0x8a2d70d &quot;vm-service&quot;, main=0x0, package_root=0x88030ba &quot;.&quot;, 
&nbsp;&nbsp;&nbsp;&nbsp;data=0x0, error=0xf72c2294) at runtime/bin/main.cc:691
#­14 0x084fcd2e in dart::RunServiceTask::Run (this=0x8c739a8)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/service.cc:737
#­15 0x0851d101 in dart::ThreadPool::Worker::Loop (this=0x8c739b8)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/thread_pool.cc:277
#­16 0x0851d2d0 in dart::ThreadPool::Worker::Main (args=147274168)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/thread_pool.cc:318
#­17 0x084803bb in dart::ThreadStart (data_ptr=0x8c73a18)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/os_thread_linux.cc:87
#­18 0xf7f96f70 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#­19 0xf7d7250e in clone () from /lib/i386-linux-gnu/libc.so.6

**Comment by mhausner** [comment]
I presume this is fixed.
