### ISSUE TITLE
Optimize the use of "pub list"

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22398]
Currently, when the analysis server first begins analyzing a context (e.g. because it was just started up, or because the user selected &quot;reanalyze sources&quot;), it runs &quot;pub list-package-dirs&quot; before doing any analysis.  In certain situations this can consume a substantial fraction of the total analysis time.  Here are three ways we might improve the situation:
1. Cache the result of running &quot;pub list&quot; on disk between runs of the analysis server; if the modification time on all of the dependencies is the same, we should just use the cached result.
2. Even in the circumstance where the modification time on some dependencies has changed (and hence &quot;pub list&quot; must be re-run), go ahead and begin analyzing using the cached result while waiting for &quot;pub list&quot; to complete.  This may allow the user to get some useful work done while waiting.
3. Once the &quot;pub list&quot; result is obtained, rather than completely invalidating the entire context, simply recompute the package URI lookup in all source files; then only invalidate data for sources that refer to a URI whose lookup has changed (and transitively invalidate all the sources which depend on those sources).  This should reduce the amount of reanalysis that needs to be done after &quot;pub list&quot; completes.

**Comment by bwilkerson** [comment]
We no longer use `pub list`, so this is obsolete.
