### ISSUE TITLE
Cannot use const ctor on a Class with a generic field - error in checked mode

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#22431]
class Foo {
&nbsp;&nbsp;final List&lt;int&gt; values;

&nbsp;&nbsp;const Foo(this.values);
}

const \_foo = const Foo(const &lt;int&gt;[1,2,3]);

This fails in checked mode because &quot;const &lt;int&gt;[1,2,3]&quot; has a rarified type of &quot;List&lt;Object&gt;&quot;, not &quot;List&lt;int&gt;&quot;

**Comment by mhausner** [comment]
The code does not fail on the VM, including checked mode.
