### ISSUE TITLE
Invalid reference to [List<int>]

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#22456]
Not sure if the issue is in docgen or in the dart-doc viewer.

Document references to parameterized types show incorrectly. For example, this  doc:

https://github.com/dart-lang/html5lib/blob/eaca2abbf149ab4d280ae94cb6e67480db421c0e/lib/parser.dart#L48

which says:

/// Parse the [input] html5 document fragment into a tree. The [input] can be
/// a [String], [List&lt;int&gt;] of bytes or an [HtmlTokenizer].

Comes up as:

Parse the input html5 document into a tree. The input can be a String, dart:core&lt;dart:core&gt; of bytes or an html5lib/tokenizer.HtmlTokenizer.

(see http://www.dartdocs.org/documentation/html5lib/0.12.0/index.html#html5lib/parser)

I would expect the dart:core&lt;dart:core&gt; to actually say List&lt;int&gt;

**Comment by sethladd** [comment]
Thanks for the report. However, we don't plan to address this issue with dartdocgen. New dartdoc tool coming online: https://github.com/dart-lang/dartdoc
