### ISSUE TITLE
When type is expected, prefixed completion should propose types

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#22467]
import 'package:path/path.dart' as ppp;

class A {
&nbsp;&nbsp;ppp.^
}

Expected: Context type proposal.
Actual: other non-type top-level declarations.

______
**Attachment:**
[Screen Shot 2015-02-17 at 5.25.23 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-22467/comment-0/Screen Shot 2015-02-17 at 5.25.23 PM.png) (142.62 KB)

**Comment by danrubel** [comment]
I believe that this is now fixed in HEAD. Please reopen if you find the problem still exists.
