### ISSUE TITLE
Dart APIs: Incorrect signature for closure arguments

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#22479]
Example:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:collection.ListBase#id_forEach

void forEach(Function void action(E element))

This is not correct Dart. It should be:

void forEach(void action(E element))

**Comment by lrhn** [comment]
There are plenty of these. 
If found `Iterable.fold`:
```
fold(initialValue, Function combine(previousValue, E element))
```
That's not just confusing, it's wrong - the return type is dynamic, not Function.

**Comment by sethladd** [comment]
The new dartdoc shows this:

![screen shot 2015-08-31 at 9 14 12 am](https://cloud.githubusercontent.com/assets/5479/9583519/ac3399d0-4fc0-11e5-92a5-fb87fcdc9bea.png)
