### ISSUE TITLE
Create linter for status files

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#22485]
Remove references to files and directories that no longer exist
Ensure all failures have associated issues
Etc

**Comment by bkonyi** [comment]
@whesse, do our status file tools cover these cases? Should we keep this open if we plan on deprecating status files anyway?

**Comment by whesse** [comment]
We have a presubmit on status files about normalizing them, but no additional work should be done on them except implementing the plan to remove them.

**Comment by munificent** [comment]
I did add a bunch of validation to status files after this bug was filed, but @whesse is right that we don't intend to do any more.
