### ISSUE TITLE
Adding a private class to DEFAULT_CORE_LIBRARY makes utils/source_mirrors_test fail

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#22508]
I get this failure:

.../sdk/lib/_internal/compiler/js_lib/preambles/d8.js:263: Uncaught Error: Invalid argument(s): &quot;_Proxy&quot; is a private identifier
Stack Trace:
Error
&nbsp;&nbsp;&nbsp;&nbsp;at dart.wrapException (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:2990:15)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.Symbol0.static.Symbol_validatePublicSymbol (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:11047:19)
&nbsp;&nbsp;&nbsp;&nbsp;at Dart2JsClassDeclarationMirror.dart.Dart2JsDeclarationMirror.get$simpleName (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:37660:30)
&nbsp;&nbsp;&nbsp;&nbsp;at ContainerMixin__ensureDeclarations_closure.dart.ContainerMixin__ensureDeclarations_closure.call$1 (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:37889:89)
&nbsp;&nbsp;&nbsp;&nbsp;at LinkEntry.dart.LinkEntry.forEach$1.H.computeSignature.func [as forEach$1] (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:123438:12)
&nbsp;&nbsp;&nbsp;&nbsp;at LibraryElementX.dart.LibraryElementX.forEachLocalMember$1 (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:50172:27)
&nbsp;&nbsp;&nbsp;&nbsp;at Dart2JsLibraryMirror.dart.Dart2JsLibraryMirror._forEachElement$1 (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:37484:98)
&nbsp;&nbsp;&nbsp;&nbsp;at Dart2JsLibraryMirror.dart.ContainerMixin._ensureDeclarations$0 (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:37870:14)
&nbsp;&nbsp;&nbsp;&nbsp;at Dart2JsLibraryMirror.dart.ContainerMixin.get$declarations (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:37878:12)
&nbsp;&nbsp;&nbsp;&nbsp;at main__closure.dart.main__closure.call$2 (.../xcodebuild/ReleaseIA32/generated_compilations/dart2js-checked/tests_utils_source_mirrors_test/out.js:87290:30)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw e;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

**Comment by sigmundch** [comment]
Now that dartdoc was moved away from the source-mirrors library and is using the analyzer parser directly, we will deprecate the source-mirrors library. So we are not planning to add this feature anymore.
 @sigmundch
