### ISSUE TITLE
Support search for nullable and polymorphic fields

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#22513]
In observatory, you can see what types the VM has seen in a given field and whether that field ever has a value of null. But you can't see it until you navigate to it. In large code bases there will be lots of types with lots of fields. It would be really nice if there were a search operation that would find all fields that can be null and a search operation that can find all fields whose value is polymorphic. This would make it easier to optimize a code base.

**Comment by turnidge** [comment]
The vm service is now documented here: 

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md

Closing this.
