### ISSUE TITLE
dart2js: recognize harmless noSuchMethod implementations

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#22558]
An implementation of noSuchMethod that uses a (chain of) super calls to hit Object.noSuchMethod is operationally indistinguishable from not implementing noSuchMethod, but is useful as a means to suppress warnings about incompletely implemented interfaces.

We should ensure dart2js code quality is not affected by these 'suppression' implementations.

If all implementations of noSuchMethod forward to Object.noSuchMethod we can omit the forwarding hooks on Object (~1% of a large program).
If all implementations of noSuchMethod always throw an exception we can improve type inference (~1.5% of a large program).

After resolution but before type inference:

&nbsp;&nbsp;Categorize noSuchMethod implementations into

&nbsp;&nbsp;[A\]: those that look like

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;noSuchMethod(Invocation invocation) =&gt; super.soSuchMethod(invocation);

&nbsp;&nbsp;where the super.noSuchMethod hits Object.noSuchMethod, Interceptor.noSuchMethod or another member of [A].

&nbsp;&nbsp;[B\]: those that syntactically directly throw an exception
&nbsp;&nbsp;[C\]: Everything else

&nbsp;&nbsp;During type inference members of sets [A] and [B] should be ignored in determining a return type (or strengthening an argument, Issue #17084).

After type inference:

&nbsp;&nbsp;Partition [C] into [C1] those that never return (empty returned type) and [C2] those that return.
&nbsp;&nbsp;Ensure (and test) the forwarding hooks are generated only if union([B], [C]) is non-empty.

At end of compilation:

&nbsp;&nbsp;Generate a diagnostic if there are implementations in [B] or [C\]:

&nbsp;&nbsp;If all definitions are in set [B], list the locations and say that the generated code will be smaller if they are rewritten to the recognized form.

&nbsp;&nbsp;If all definitions are in [B] or [C1], list the locations and say that the generated code will be smaller and permit more optimizations if they are rewritten to the recognized form.

&nbsp;&nbsp;Otherwise

&nbsp;&nbsp;(1) List locations of [C2], with a message saying these 'useful' implementations of noSuchMethod, if removed, will allow the generated code to be smaller and permit more optimizations.
&nbsp;&nbsp;(2) List locations of [B] and [C1], with a message saying rewriting them in the recognized form is also neccessary to get teh better code.

**Comment by hterkelsen** [comment]
This was implemented in c90a6adc6525f1d97a7f1047102e7980437b620d
