### ISSUE TITLE
using 'default' as an identifier results in a long series of utterly confusing messages

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#22553]
The following program gets six error messages in dartanalyzer:

&nbsp;&nbsp;&nbsp;const default = const Object();
&nbsp;&nbsp;&nbsp;void main() { }

They are:

&nbsp;&nbsp;&nbsp;[error] Expected to find ';' (test.dart, line 1, col 7)
&nbsp;&nbsp;&nbsp;[error] Expected an identifier (test.dart, line 1, col 7)
&nbsp;&nbsp;&nbsp;[error] Unexpected token 'default' (test.dart, line 1, col 7)
&nbsp;&nbsp;&nbsp;[error] Expected a method, getter, setter or operator
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;declaration (test.dart, line 1, col 7)
&nbsp;&nbsp;&nbsp;[error] The const variable 'default' must be initialized
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(test.dart, line 1, col 7)
&nbsp;&nbsp;&nbsp;[error] A function body must be provided (test.dart, line 1,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;col 31)

It also gives one error when compiling:

&nbsp;&nbsp;&nbsp;'test.dart': error: line 1 pos 1: unexpected token 'const'

None of these errors are useful. The useful error message here would be &quot;default is a reserved word, and cannot be used as an identifier&quot; or some such.

**Comment by natebosch** [comment]
Down to 1 error message - "error • Expected an identifier at /tmp/try.dart:1:7 • missing_identifier"

Leaving the issue open since it could still be improved by changing to "`default` is not a valid identifier"
