### ISSUE TITLE
VM error message for missing `async` could suggest fix

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#22567]
given:

foo() async =&gt; 42;
main() {
&nbsp;&nbsp;print(await foo());
}

error message is:

'test.dart': error: line 6 pos 15: ')' expected
&nbsp;&nbsp;print(await foo());
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

it seems like `await` is not supported. I can imagine this is for backwards compat, `await` still needs to work as a variable. However it would be super nice to have it suggest the fix, which is add `async` to `main`.

**Comment by sethladd** [comment]
dart2js now prints a helpful message:

```
~/tmp $ dart2js bug.dart
bug.dart:4:13:
Error: Expected ';' after this.
  var foo = await awesome();
            ^^^^^
bug.dart:4:13:
Warning: Cannot resolve 'await'.
Did you mean to add the 'async' marker to 'main'?
  var foo = await awesome();
            ^^^^^
Hint: When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/compiler/js_lib/preambles.
Error: Compilation failed.
```

**Comment by bwilkerson** [comment]
@mit-mit Why did you change the area to 'Analyzer'? I don't see any description of a problem with analyzer in here, so I'm puzzled.

**Comment by zoechi** [comment]
Quick-fixes are provided by the analyzer, aren't they?
The use of `await` could provide a quick-fix for adding `async` if it isn't there already.

**Comment by sethladd** [comment]
This was originally intended to ask that the VM print a more contextual error message.

I don't know if Analyzer currently prints a helpful feedback message, but if not, that should also be helpful :)

**Comment by mit-mit** [comment]
I guess I misunderstood what this bug was tracking. Should we keep it to track the VM issue, and then file a new one for the analyzer? I mean, it should be able to suggest a better fix than [`Undefined name 'await'`, right](https://dartpad.dartlang.org/557c783c629581b0e5c0)

**Comment by floitschG** [comment]
From what I can see, dart2js is the only one giving a good error message.
Both the analyzer as well as the VM complain about the syntax or the undefined name.
For reference here is the VM output:
```
$ dart /tmp/tt.dart
'file:///tmp/tt.dart': error: line 2 pos 15: ')' expected
  print(await 5);
              ^
```

**Comment by bwilkerson** [comment]
Yes, I think it's appropriate to keep this issue for the VM and create a new one for the analyzer.

**Comment by mit-mit** [comment]
Moved back to VM, and opened #24264 for Analyzer

**Comment by mhausner** [comment]
It is not the VM's job to analyze errors. That's why I commented above that the Analyzer should issue suggestions, not the VM. Change Florian's example above to print(await -5) and you have a syntactically correct expression that is most likely still wrong.

Even better than burdening the Analyzer or compiler: fix the language.

**Comment by iposva-google** [comment]
As Matthias points out the contextual error message for Dart in this case is the fact that there is no getter await.
