### ISSUE TITLE
Find Uses should be more restricted

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#22613]
Find Uses should only find uses of the selected element. For example, if I select an explicit setter and ask for uses, I don't want to see uses of the corresponding getter (and vice versa).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212829

**Comment by bwilkerson** [comment]
Thanks for looking at fixing this. Since the time when this issue was created the language has been steadily evolving from a model in which getters and setters were relatively independent declarations to a model in which a getter and setter tend to be thought of as a single "property". As a result, I'm not sure this is really a bug; it might be now be a feature.

Unless you feel otherwise, I think I'll close this issue and let you "abandon" your CL.

**Comment by asashour** [comment]
I see, then please close this. The CL is abandoned.
