### ISSUE TITLE
Overridden accessors should not be displayed

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#22631]
Try to complete:

---

abstract class A {
&nbsp;&nbsp;int get test;
&nbsp;&nbsp;void set test(int p);
}

class B extends A {
&nbsp;&nbsp;int test;

&nbsp;&nbsp;m() {
&nbsp;&nbsp;&nbsp;&nbsp;test^
&nbsp;&nbsp;}
}

---

Expected: only &quot;test&quot; from B.

Actual: B.test, get A.test, set A.test.
&nbsp;&nbsp;The last two elements are not accessible without &quot;super.&quot; prefix, so should not be displayed.

**Comment by bwilkerson** [comment]
I believe this now works as expected.
