### ISSUE TITLE
Analyzer not recognizing when import is added

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#22638]
To reproduce the problem:
1. Clone https://github.com/dart-lang/code_transformers
2. Change the analyzer dependency to depend on analyzer 0.24.0
3. Run the resolver_test https://github.com/dart-lang/code_transformers/blob/master/test/resolver_test.dart

The test fails because analyzer does not detect that the import to 'b/missing.dart' is now resolvable. If you make a trivial change to 'web/main.dart' such as adding a comment, the test passes. It seems like it is deciding not to analyze 'web/main.dart' since it's contents didn't change, but the analysis of 'web/main.dart' should change since it's import is now resolvable.

**Comment by srawlins** [comment]
We've since redesigned analysis broadly with AnalysisContexts, and have not seen recent reports of this.
