### ISSUE TITLE
Unused import hint often invalid if import contains annotations.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#22660]
As an example, the `initialize` package provides a way of supplying annotations which perform some static initialization (think @­CustomTag from polymer, which is now an Initializer). You need to import these files but may or may not actually use any of the classes from them directly. If you don't use them, then you will get an unused import hint even though you really are using it.

I don't know what the right solution is here, but I think we need to figure out something because in the new version of polymer especially this is going to be an extremely prevalent issue.

Some initial ideas:
1. Make the analyzer be aware of annotations which implement Initializer. If any exist in a file then it will never be marked as an unused import.
   
   My main concern here is it seems wrong to have the analyzer know about this package. There are other frameworks doing similar things which will run into the same issue but don't use the `initialize` package so they won't benefit.
2. Allow dartdoc comments on import directives and force the user to mention a class from the import in the comment:
   
   ``` dart
   /// For [MyElement] registration.
   import 'my_element.dart';
   ```
   
   Forces a fair bit of burden on the user, but its also more clear why the import exists.
3. Allow some other method to hide the hint.
   
   Same downsides as #­2, its going to force some extra burden on the user.
4. If a file contains any annotations, don't mark it as an unused import.
   
   This is probably to broad of a solution.

**Comment by zoechi** [comment]
The doc-comment workaround works fine for me.
The remaining issue is that some Dart files contain only the `@HtmlImport('some_file.html');` annotation (and the import for the `HtmlImport`) annotation but doesn't export anything.

There is no way to silence the unused import warnings using Dartdoc comments.

It would be great if unused import warnings could be suppressed for libraries that don't export anything.

**Comment by jakemac53** [comment]
Just going to close this as the workarounds are.... workable

**Comment by expelledboy** [comment]
What is the "workable" work around?
