### ISSUE TITLE
Api search suggestions not putting exact match first.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#22697]
On api.dartlang.org I write &quot;exit&quot; in the search box. The suggested completions are:
&nbsp;&nbsp;exitCode  property in Process  library dart:io
&nbsp;&nbsp;exitCode  getter in ProcessResult  library dart:io
&nbsp;&nbsp;exitCode  getter  library dart:io
&nbsp;&nbsp;exitCode=  setter  library dart:io
&nbsp;&nbsp;exitEvent  property in TextTrackCue  library dart:html
&nbsp;&nbsp;exitFullscreen  method in Document  library dart:html
&nbsp;&nbsp;exitFullscreen  method in HtmlDocument  library dart:html
&nbsp;&nbsp;exitFullscreen  method in VideoElement  library dart:html
&nbsp;&nbsp;exitPointerLock  method in Document  library dart:html
&nbsp;&nbsp;exit  method  library dart:io

That is, the exact match is actually the last suggestion. Pressing return sends me to exitCode (it doesn't actually do a search on &quot;exit&quot; as I would have expected).

I recommend putting exact matches before partial matches where possible.

**Comment by sethladd** [comment]
The new dartdoc tries to prefer exact matches. If it's not behaving the way you'd like, please file an issue at https://github.com/dart-lang/dartdoc/issues  Thanks!
