### ISSUE TITLE
Test of await, language/await_future_test, times out on Chrome 41 on macos.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22695]
FAILED: dart2js-chrome release_ia32 language/await_future_test
Expected: Pass 
Actual: Timeout
CommandOutput[dart2js\]:

There are no delays or timers in the test, so it almost certainly is hanging when it times out.  This seems quite bad, and it is in the new await code in dart2js, so marking as high priority.

It failed (timed out) in 3 runs out of 10 on the buildbot.

**Comment by sigurdm** [comment]
I looked through the last 100 logs of the mac-chrome bot (with a script). And it seems to not time out anymore. Is it a newer Chrome on the bot?

**Comment by whesse** [comment]
Yes, the debug log (which can be clicked on in the buildbot) says it is on
version 43.  We can probably re-enable the tests.

https://chromegw.corp.google.com/i/client.dart/builders/dart2js-chrome-mac10.9-be/builds/942/steps/annotated_steps/logs/debuglog

On Thu, Jun 4, 2015 at 3:16 PM, Sigurd Meldgaard <notifications@github.com>
wrote:

> I looked through the last 100 logs of the mac-chrome bot (with a script).
> And it seems to not time out anymore. Is it a newer Chrome on the bot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/22695#issuecomment-108894425>.
>



-- 
William Hesse

**Comment by whesse** [comment]
Yes, the debug log (which can be clicked on in the buildbot) says it is on version 43.  We can probably re-enable the tests.

http://build.chromium.org/p/client.dart/builders/dart2js-chrome-mac10.9-be/builds/942/steps/annotated_steps/logs/debuglog

**Comment by sigurdm** [comment]
Great! - I will reenable the tests.

**Comment by sigurdm** [comment]
Nope - my script was looking in the wrong places. The tests are still failing.

**Comment by whesse** [comment]
We are having lots of timeouts on many tests on Chrome on macos.  Here is a list of the most recent.  So it is not all async/await support.  And these are not tests that are taking a long time normally, when they do pass.

html/custom/attribute_changed_callback_test/fully_supported
html/custom/created_callback_test
html/custom/entered_left_view_test/disconnected_subtree
html/indexeddb_3_test
html/indexeddb_3_test
html/indexeddb_4_test
language/asyncstar_yield_test
lib/async/catch_errors18_test
lib/async/stream_event_transformed_test
lib/async/stream_event_transformed_test

This one does take 20s normally, but fails with 1 minute.
lib/convert/streamed_conversion_json_encode1_test

**Comment by whesse** [comment]
Tracked in meta-issue https://github.com/dart-lang/sdk/issues/23980

**Comment by whesse** [comment]
I am removing the two remaining timeout status lines for this issue (language/async_await_test and language/await_future_test), as the scattered timeouts are being tracked in #23980, and there is no evidence these timeouts have a different cause than the other, unsuppressed ones.  Closing this issue, leaving #23980 open.
