### ISSUE TITLE
Failure in lib/async/timer_isActive_test on Chrome 41 on macos

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22696]
The test lib/async/timer_isActive_test is failing with a runtime error, 3 times out of 10 on the chrome macos buildbot, since Chrome was updated to version 41.

The error is in the &quot;timer cancel test&quot; subtest:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: print
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;value: FAIL: timer cancel test
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Should not be reached.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 2634:15   dart.wrapException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 12409:17  SimpleConfiguration.dart.SimpleConfiguration.onExpectFailure$1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 12374:20  _ExpectFailureHandler.dart._ExpectFailureHandler.fail$1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 11929:22  main__closure0.dart.main__closure0.call$0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 5109:16   dart._rootRun
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 6803:39   _CustomZone.dart._CustomZone.run$1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 6716:19   _CustomZone.dart._CustomZone.runGuarded$1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 6898:26   _CustomZone_bindCallback_closure.dart._CustomZone_bindCallback_closure.call$0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 5112:14   dart._rootRun
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://127.0.0.1:57228/root_build/generated_compilations/dart2js-sdk/tests_lib_async_timer_isActive_test/test.js 6803:39   _CustomZone.dart._CustomZone.run$1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;timestamp: 9.027

**Comment by matanlurey** [comment]
This is a browser from years ago.
