### ISSUE TITLE
Don't warn about dynamically injected script tags if the library is already loaded

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#22712]
When injecting an html import which contains a dartium script into the dom at runtime, dartium currently throws a warning since that script will not be loaded. If the library pointed to by that script is already loaded though, then it should not throw this warning.

This is going to be a relatively common case in newer polymer apps, and without it we are forced to either ignore the warning or do an annoying dance that requires adding an extra html import for every element (one that contains the dart file, and one that does not).

**Comment by tmst** [comment]
Moving the following script tag from <head> into <body> stopped these errors from appearing in my Dartium console:
<script type="application/dart" src="index.dart"></script>

Don't ask me how I found out (hint: T&E). That's all I know. :-(
