### ISSUE TITLE
Add a way to capture stack chains in the analysis server

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#22744]
Stack chains are very useful for debugging asynchronous errors, providing contextual information on par with synchronous stack traces. Since the analysis server is fundamentally asynchronous, it would be nice if it analysis server had a flag to collect stack chains to ease the debugging asynchronous crashes. This would make things like issue #22653 easier to track.

Stack chains can be captured in a zone scope using Chain.capture from the stack_trace package; within that scope, Chain.forTrace can be used to retrieve the stack chain for a vanilla stack trace. I'd be happy to advise on setting this up.

**Comment by devoncarew** [comment]
I think we can close this, now that the VM supports chaining async calls natively.
