### ISSUE TITLE
Support partial parse/scan

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#22745]
Several times now I've run into cases where I want to parse one or another sort of &quot;head matter&quot; of a Dart file. This parsing has also ended up on important performance paths, so limiting the amount of work that needs to be done is important. For example, in pub we do some analysis for pub serve/build/run that requires us to know a file's imports and exports; in unittest we want to check each test file for annotations on the library tag.

Right now there are a few methods available on Parser to parse particular productions that can be used to avoid parsing the entire file. However, the way the APIs are structured means the whole thing still needs to be scanned, which can be expensive in and of itself when dealing with medium-to-large files. It would be really nice to be able to, say, have an API that would parse top-level productions on-demand without scanning any farther than necessary.

**Comment by matanlurey** [comment]
My assumption is the analyzer team does not plan on this anytime soon.
