### ISSUE TITLE
Warning on importing two anonymous libraries seems noisy/unecessary

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22836]
Dart doesn't have a way to silence individual warning types. Perhaps if we had that ability, we wouldn't need this request. So maybe I should be filing a &quot;allow someone to opt-out of certain warnings.&quot; :)  In the meantime...

It is possible to import two anonymous/unnamed libraries into the same app. However, a developer will see a warning when this happens. Because the program starts, compiles, and runs just fine, the warning feels too oppressive/noisy.

This warning feels more like a hint or a lint rule, less like a &quot;your program might break if you don't take care of this&quot;.

**Comment by munificent** [comment]
We removed this warning some time ago.
