### ISSUE TITLE
Unhelpful response if the SDK path isn't correct when the Analysis Server is launched

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#22882]
If an incorrect path for the SDK is passed to the Analysis Server on startup, the error that you receive is similar to the one at the end of this report.

It should sanity check the arguments passed and provide a more useful failure report.

NoSuchMethodError: method not found: 'getAbsolutePath'
Receiver: null
Arguments: []&quot;,&quot;stackTrace&quot;:&quot;#­0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
# ­1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
# ­2      _runPubListDefault (package:analyzer/source/pub_package_map_provider.dart:159:64)
# ­3      PubPackageMapProvider.computePackageMap (package:analyzer/source/pub_package_map_provider.dart:66:27)
# ­4      ContextManager._computePackageUriResolver.&lt;anonymous closure&gt; (package:analysis_server/src/context_manager.dart:371:63)
# ­5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150:15)
# ­6      ContextManager._computePackageUriResolver (package:analysis_server/src/context_manager.dart:370:55)
# ­7      ContextManager._createContext (package:analysis_server/src/context_manager.dart:396:64)
# ­8      ContextManager._createContextWithSources (package:analysis_server/src/context_manager.dart:453:39)
# ­9      ContextManager._createContexts (package:analysis_server/src/context_manager.dart:442:30)
# ­10     ContextManager.setRoots (package:analysis_server/src/context_manager.dart:242:24)
# ­11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:842:39)
# ­12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:149:28)
# ­13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:119:32)
# ­14     handleRequest.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (package:analysis_server/src/analysis_server.dart:597:58)

**Comment by skybrian** [comment]
I just reproduced this bug by sending an analysis.setAnalysisRoots RPC with an empty directory.

It looks like setRoots() ignores nonexistent directories but doesn't ignore directories that exist but don't have a pubspec.yaml or any packages. Not sure what's supposed to happen in that case, but it probably shouldn't be a stack trace.

**Comment by skybrian** [comment]
Never mind about the empty directory. As Luke says, this stack trace happens when Analysis Server can't find the SDK. 

It seems like DirectoryBasedDartSDK could do a better job of finding the default SDK. It looks for an environment variable named "com.google.dart.sdk", but if that's not found, it could try this:

  new Directory(Platform.resolvedExecutable).parent.parent

Workaround: pass in the --sdk flag on startup.

**Comment by srawlins** [comment]
Closing as stale. Please re-open if you see this again.
