### ISSUE TITLE
Analysis Server change in analysis.errors notification API 

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#22901]
This is a record of a discussion we have had to eventually delete the getErrors API from the Analysis Server

API: http://htmlpreview.github.io/?https://github.com/dart-lang/bleeding_edge/blob/master/dart/pkg/analysis_server/doc/api.html

Change: the last notification for a file should have a &quot;last=true&quot; boolean param.

**Comment by pq** [comment]
Not sure we need to keep this open... @jwren feel free to re-open if you think we should!
