### ISSUE TITLE
Async functions should run their initial part synchronously.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#22909]
The current specification delays running the initial part of an &quot;async&quot; function until a later microtask.
However, that makes async functions unusable when implementing functions that require action to be taken immediately.

One such example is the &quot;first&quot; getter on the Stream class. It should start listening to the stream immediately, and then complete its returned future with the first event it receives.

Implementing it using an async function seems like it could be:
&nbsp;&nbsp;
&nbsp;&nbsp;Future&lt;T&gt; get first async {
&nbsp;&nbsp;&nbsp;&nbsp;await for (T element in this) return element;
&nbsp;&nbsp;&nbsp;&nbsp;throw &quot;no such element&quot;;
&nbsp;&nbsp;}

However, that function doesn't listen on the stream immediately, and if the stream is a broadcast stream, the delay may cause it to miss events sent after the call to `first`.
This problem prevents implementing most Stream functions using async code.

I recommend letting the initial part of an async function be run immediately when it's called instead of being delayed.

**Comment by brianegan** [comment]
Haha, a bit of an oldie, but I'd love to see this fixed up! I couldn't figure out why this works with `async*` functions:

```dart
new StreamController().stream.asBroadcastStream();
```

But this does not:

```dart
new StreamController.broadcast().stream;
```

**Comment by zoechi** [comment]
@brianegan I thought this change is already active in recent Dart 2 versions.

**Comment by brianegan** [comment]
@zoechi Thanks! I'll do some testing with my lib + Dart2!

**Comment by zoechi** [comment]
Might need `--preview-dart-2` but I'm pretty sure I saw that work was done here.

**Comment by lrhn** [comment]
This has been specified and implemented. In Dart 2, this will be the behavior.

**Comment by brianegan** [comment]
For those interested -- this only applies to `async` functions, but not to `async*` functions, which is a detail I missed. This issue tracks `async*` functions: https://github.com/dart-lang/sdk/issues/33818
