### ISSUE TITLE
The behaviour of Function.apply should be specified

### ISSUE THREAD

**Issue by herhut-ggl** [dart-lang/sdk#22927]
While fixing a bug in the implementation of Function.apply I noticed that its behaviour is not actually specified. This is an issue as the spec itself refers to Function.apply to specify how super invocation works in the presence of getters.

If this gets specified, we should promote the regression test for issue #22917 to a language test.

**Comment by munificent** [comment]
> In this case, I think the specification is safe.

Speculatively closing since I think Lasse is saying there's no change we need to do. :)
