### ISSUE TITLE
Confusing error message from dart2js on 'e || throw x'.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#22926]
Code like:
&nbsp;&nbsp;(41 == 42) || throw &quot;x&quot;;
gives an error saying:

Error: Expected an expression, but got 'throw'.
&nbsp;&nbsp;41 == 42 || throw &quot;not&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^

That makes it sound like &quot;throw&quot; is not an expression, where the problem is that it's not a LogicalAndExpression.

**Comment by askeksa-google** [comment]
Same issue as https://github.com/dart-lang/sdk/issues/24891 with a different operator.
