### ISSUE TITLE
conflating versions in package bots

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#22934]
It seems that this problem is still happening.

If you publish 2 different packages with the same version, the bots show an invalid row confusing the results of one package with another.

See attached picture for an example. Consider the args package windows column:

- the row for commit # aae8f70cac50 is build #­169
- the row for html5lib 0.12.1 says build #­159

If you look at the build for #­159, turns out it was an older build from publishing `intl` with the same version number (0.12.1)

[link to build #­169\]: 
http://chromegw.corp.google.com/i/client.dart.packages/builders/packages-windows-args/builds/169

[link to build #­159\]: http://chromegw.corp.google.com/i/client.dart.packages/builders/packages-windows-args/builds/159
______
**Attachment:**
[versions_error.png](https://storage.googleapis.com/google-code-attachments/dart/issue-22934/comment-0/versions_error.png) (118.46 KB)

**Comment by ricowind** [comment]
still happening?

**Comment by sigmundch** [comment]
I think not anymore (since you added the full package + version name in the revision "number"). We can always reopen if we notice it again.
