### ISSUE TITLE
NoSuchMethodError stack trace doesn't tell me where the problem is

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22942]
Hi,

Consider this code:

import &quot;dart:async&quot;;

foo() async {
&nbsp;&nbsp;var x = 5;
&nbsp;&nbsp;var b = await (await x++ +await x++);
&nbsp;&nbsp;print(&quot;foo: $b&quot;);
}

arr() =&gt; new Future.value([0,1,2,3,4,5]);

bar(a) async {
&nbsp;&nbsp;var r = (await aaa())[await 3]++;
&nbsp;&nbsp;print(&quot;bar: $r&quot;);
}

main() {
&nbsp;&nbsp;//futureArray();
&nbsp;&nbsp;//foo();
&nbsp;&nbsp;bar([0,2,1,3,4,5]);
}

When you compile it with dart2js, you get an accurate warning (`aaa is unknown` or similar)

When you try to run it the compiled output, you will get this exception:

Uncaught Uncaught Error: NoSuchMethodError : method not found: 'Symbol(&quot;aaa&quot;)'
Receiver: &quot;&quot;
Arguments: []
Stack Trace:
NoSuchMethodError : method not found: 'Symbol(&quot;aaa&quot;)'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;&nbsp;&nbsp;at dart.wrapException (&lt;anonymous&gt;:1806:15)
&nbsp;&nbsp;&nbsp;&nbsp;at dart.throwNoSuchMethod (&lt;anonymous&gt;:2201:13)
&nbsp;&nbsp;&nbsp;&nbsp;at body (&lt;anonymous&gt;:5076:36)
&nbsp;&nbsp;&nbsp;&nbsp;at _wrapJsFunctionForAsync_closure.protected_1 (&lt;anonymous&gt;:2237:11)
&nbsp;&nbsp;&nbsp;&nbsp;at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$1 (&lt;anonymous&gt;:2783:12)
&nbsp;&nbsp;&nbsp;&nbsp;at _RootZone.dart._RootZone.runUnary$2 (&lt;anonymous&gt;:3989:18)
&nbsp;&nbsp;&nbsp;&nbsp;at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (&lt;anonymous&gt;:3736:57)
&nbsp;&nbsp;&nbsp;&nbsp;at dart._Future.static._Future__propagateToListeners (&lt;anonymous&gt;:3645:131)
&nbsp;&nbsp;&nbsp;&nbsp;at _Future.dart._Future._completeWithValue$1 (&lt;anonymous&gt;:3535:9)
&nbsp;&nbsp;&nbsp;&nbsp;at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (&lt;anonymous&gt;:3722:19)
API documentation

Expected: a line number that gets me to the line where `aaa` was encountered.

Here's the line 5076: t3.$indexSet(t1, t2, J.$add$ns(t3.$index(t1, t2), 1));

On the VM, here's the exception that I get:

sethladd@sethladd-macbookair ~/tmp/testdart2js $ dart test.dart
Unhandled exception:
Uncaught Error: No top-level method 'aaa' declared.

NoSuchMethodError: method not found: 'aaa'
Receiver: top-level
Arguments: [...]
Stack Trace:
# ­0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:176)
# ­1      bar.&lt;bar_async_body&gt; (file:///Users/sethladd/tmp/testdart2js/test.dart:12:18)
# ­2      Future.Future.microtask.&lt;anonymous closure&gt; (dart:async/future.dart:144)
# ­3      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
# ­4      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
# ­5      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
# ­6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
# ­0      _rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
# ­1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
# ­2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
# ­3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
# ­4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

Note that #­1 points me to line 12, which has the call to `aaa`

I've included the output of dart2js, if that helps.

Thanks for taking a look.

---

**Attachment:**
[out.js](https://storage.googleapis.com/google-code-attachments/dart/issue-22942/comment-0/out.js) (187.32 KB)

**Comment by matanlurey** [comment]
In Dart2 this is no longer a warning.
