### ISSUE TITLE
Confusing warning message when operator[]= not defined and using compound assignment

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22941]
The following code:

```
class C {
  operator[](index) => null;
}
f(C c) {
  c[1] += 2;
}
```

Produces the warning message: &quot;The operator '[]' is not defined for the class 'C'&quot;

But this isn't true.  The operator '[]' *is* defined for the class 'C'.  The warning should read: &quot;The operator '[]=' is not defined for the class 'C'&quot;.

Note that if &quot;+=&quot; is replaced with &quot;=&quot;, then the correct warning message appears.

**Comment by srawlins** [comment]
The warning is as you wish now:

```
  error • The operator '[]=' isn't defined for the type 'C'. • 22941.dart:5:4 • undefined_operator
```
