### ISSUE TITLE
Deprecated annotation ignored on fields

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22963]
Using editor with analysis server, create a file with the following contents, and observe the hints that are generated:

class C {
&nbsp;&nbsp;@­deprecated
&nbsp;&nbsp;int foo;

&nbsp;&nbsp;@­deprecated
&nbsp;&nbsp;int get bar =&gt; 1;
}

f(C c) =&gt; c.foo;
g(C c) =&gt; c.bar;

Expected behavior: both &quot;c.foo&quot; and &quot;c.bar&quot; should generate a hint, since they both refer to a deprecated member of class C.

Observed behavior: only &quot;c.bar&quot; generates a hint.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1797583003/
