### ISSUE TITLE
Update dartiverse sample to use requires.1.9 tag

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#22968]
This sample using async/await features

Too late for 1.9 gold, but we should do a merge-to-stable for the 1.9 dot release

**Comment by kevmoo** [comment]
How are we managing our samples in a post-Editor world?

**Comment by kevmoo** [comment]
We don't care about updating these tags for the Editor any more.

**Comment by sigmundch** [comment]
so no other tools downloads samples using the scheme we had in the editor? Does that mean we can stop adding these labels in the samples themselves too?
