### ISSUE TITLE
Small old gen heap size will cause SEGFAULT in the VM

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#22978]
Here's a reproduction:

$ out/ReleaseX64/dart --version                                                                  
Dart VM version: 1.10.0-edge.44668 (Tue Mar 24 17:12:17 2015) on &quot;linux_x64&quot;

$ cat hello.dart
main() =&gt; print('hello');

$ out/ReleaseX64/dart --old_gen_heap_size=1 hello.dart 
(gdb) run
...
(gdb) bt
#­0  dart::LongJumpScope::Jump (this=0x0, value=value@entry=1, error=...) at runtime/vm/longjump.cc:58
#­1  0x00000000007be8ea in dart::SnapshotReader::AllocateUninitialized (this=&lt;optimized out&gt;, class_id=62, size=262512)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/snapshot.cc:915
#­2  0x00000000007be93d in dart::SnapshotReader::NewArray (this=this@entry=0x7fffffffbcd0, len=len@entry=32811)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/snapshot.cc:602
#­3  0x0000000000838fbb in dart::Array::ReadFrom (reader=reader@entry=0x7fffffffbcd0, object_id=7399, tags=tags@entry=0, 
&nbsp;&nbsp;&nbsp;&nbsp;kind=dart::Snapshot::kFull) at runtime/vm/raw_object_snapshot.cc:2122
#­4  0x00000000007c109b in dart::SnapshotReader::ReadInlinedObject (this=0x7fffffffbcd0, object_id=&lt;optimized out&gt;)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/snapshot.cc:1071
#­5  0x00000000007c1e48 in dart::SnapshotReader::ReadFullSnapshot (this=this@entry=0x7fffffffbcd0) at runtime/vm/snapshot.cc:505
#­6  0x00000000005c425f in dart::Dart::InitializeIsolate (
&nbsp;&nbsp;&nbsp;&nbsp;snapshot_buffer=snapshot_buffer@entry=0xb12480 &lt;dart::bin::snapshot_buffer_&gt; &quot;8\r\021&quot;, data=data@entry=0x1256e40)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart.cc:242
#­7  0x0000000000562189 in dart::Dart_CreateIsolate (script_uri=&lt;optimized out&gt;, main=&lt;optimized out&gt;, 
&nbsp;&nbsp;&nbsp;&nbsp;snapshot=0xb12480 &lt;dart::bin::snapshot_buffer_&gt; &quot;8\r\021&quot;, callback_data=0x1256e40, error=0x7fffffffd010)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_api_impl.cc:1296
#­8  0x0000000000552b8e in dart::bin::CreateIsolateAndSetupHelper (script_uri=script_uri@entry=0x7fffffffd678 &quot;hello.dart&quot;, 
&nbsp;&nbsp;&nbsp;&nbsp;main=main@entry=0xe72a2a &quot;main&quot;, package_root=0x0, error=error@entry=0x7fffffffd010, exit_code=exit_code@entry=0x7fffffffd000)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/bin/main.cc:589
#­9  0x000000000054cbb6 in dart::bin::main (argc=3, argv=0x7fffffffd198) at runtime/bin/main.cc:986
#­10 0x000000000054d119 in main (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at runtime/bin/main.cc:1119

**Comment by rmacnak-google** [comment]
Nowadays we get a proper out of memory message.

```
$ ./out/ReleaseX64/dart --old_gen_heap_size=1 ~/hello.dart 
runtime/vm/clustered_snapshot.cc: 31: error: Out of memory
```
