### ISSUE TITLE
Produce warnings for deprecated parameters

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#22975]
It can occasionally be useful to deprecate optional or named parameters. It would be nice if the analyzer detected uses of parameters with a @­deprecated annotation and produced appropriate hints.

**Comment by srawlins** [comment]
@zoechi seems to be right for named parameters. Optional positional parameters do not get the warning:

https://dartpad.dartlang.org/f02d11a384a55689a8c0ed4eebdadcfa has just 1 warning:

> info: 'c' is deprecated

**Comment by srawlins** [comment]
Oops. Fixed back in May.
