### ISSUE TITLE
Use the source_span package in the analyzer library

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#22977]
The source_span package is becoming the Dart standard for reporting source locations. It would be cool if the analyzer package could use it as well for easier integration with the rest of the ecosystem.

I'd be happy to help out with integration.

**Comment by natebosch** [comment]
I see imports to source_span from analyzer. Is this done?

**Comment by bwilkerson** [comment]
No. As far as I can tell from a quick glance it's only being used in places were we're interfacing with another package that uses it.

I suspect that any attempt to switch analyzer to use it would require a breaking change to analyzer's API, and I don't want to have any more changes than necessary at this point.

**Comment by natebosch** [comment]
SGTM. Let's closed this as not planned.
