### ISSUE TITLE
Analyzer gets in an infinite loop when a file has parts on the order of 64

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23017]
Source issue: https://github.com/kevmoo/source_gen.dart/issues/46

AnalysisContextImpl.DEFAULT_CACHE_SIZE = 64;

I'm working on a repo.

So far: I get stuck in an infinite loop in the `while` in_cacheDartResolutionData 

State goes FLUSHED and stays FLUSHED.

**Comment by bwilkerson** [comment]
This should be fixed by the new task model. Please let me know if it isn't.
