### ISSUE TITLE
Update native extensions article

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#23024]
Can we mention the need to define DART_SHARED_LIB in the Linux and Mac build instructions as well?

https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/

**Comment by sethladd** [comment]
Here's the source for the article: https://github.com/dart-lang/www.dartlang.org/blob/master/src/site/articles/native-extensions-for-standalone-dart-vm/index.markdown

If possible, open the file in the GitHub editor and send us a pull request.

Thanks!

**Comment by sethladd** [comment]
Thanks to Ryan https://github.com/dart-lang/www.dartlang.org/pull/1380
