### ISSUE TITLE
Completion for imports has regressed

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23073]
Imports used to offer completions.

e.g. import 'dart:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^

After the move to Analysis Server (or possibly before) this has broken.

It doesn't work for package: either.

It doesn't work for part '.../' (I don't know if this used to work or not)

**Comment by bwilkerson** [comment]
If it's still broken on Windows we should open a separate issue for it, but I'm going to close this because the basic support was added.
