### ISSUE TITLE
better error message when loading a part file

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23082]
Today if you try running the vm on a part file, rather than a library file:

&nbsp;&nbsp;&nbsp;&nbsp;part of a;
&nbsp;&nbsp;&nbsp;&nbsp;main () {}

You get an error like:
&nbsp;&nbsp;'file:///path/to/file.dart': error: line 1 pos 6: url expected
&nbsp;&nbsp;part of a;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

It would make it more intuitive for our users if we can detect that this is a part-of construct and tell them that the vm expected a library instead.

See for example issue #20314 for details of the context where this came up: users tried to load a part file in Dartium and didn't understand why that didn't work. (I believe the error comes from the vm, that's why I assigned it to this area though)

**Comment by mhausner** [comment]
An improved error message has been implemented in CL 0a3bf27663697cc3e27d37edfe71d19d0598b879
