### ISSUE TITLE
If parser throws an exception, command-line analyzer reports no errors.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23096]
In the event that a bug in the parser causes an exception to be thrown, the command-line analyzer needs to give some indication that a problem has occurred.  Either it should terminate with a nonzero exit code, or it should report a synthetic error for the file indicating that parsing failed.

Currently, if the parser throws an exception, the exception is swallowed by the exception handler in AnalysisTask.perform(), and then analysis proceeds; as a result, it appears to the user as though the file has no errors.

I suspect a similar situation may exist for other analysis tasks.

**Comment by pq** [comment]
Closing for staleness.
