### ISSUE TITLE
Dart2js incorrect assignability warning

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23132]
(As reported by leafp in issue #22976, which is the corresponding Analyzer bug)

Consider the following code:

class A&lt;T&gt; {}
class B&lt;T&gt; implements A&lt;T&gt; {}
class C&lt;S, T&gt; implements B&lt;S&gt;, A&lt;T&gt; {}

main() {
&nbsp;&nbsp;A&lt;int&gt; a0 = new C&lt;int, String&gt;();
&nbsp;&nbsp;A&lt;int&gt; a1 = new C&lt;String, int&gt;();
}

My reading of the subtyping rules in the spec is that both :
&nbsp;&nbsp;&nbsp;C&lt;int, String&gt; &lt;&lt; A&lt;int&gt; 
and 
&nbsp;&nbsp;&nbsp;C&lt;String, int&gt; &lt;&lt; A&lt;int&gt;

There may be other restrictions in play that I'm not seeing, but based on this, it seems like both assignments are valid.

The dart analyzer currently gives an assignability warning on the second assignment.

Dart2js also gives a warning on the second assignment, but also indicates that this code pattern is not supported.

The VM does not throw a checked mode error on either assignment. 

leafp-macbookpro:~ leafp$ dartanalyzer --version
dartanalyzer version 1.9.0-dev.10.13
leafp-macbookpro:~ leafp$ dartanalyzer tmp/inherits2.dart 
Analyzing [tmp/inherits2.dart]...
[warning] A value of type 'C&lt;String, int&gt;' cannot be assigned to a variable of type 'A&lt;int&gt;' (/Users/leafp/tmp/inherits2.dart, line 7, col 15)
[hint] The value of the local variable 'a0' is not used (/Users/leafp/tmp/inherits2.dart, line 6, col 10)
[hint] The value of the local variable 'a1' is not used (/Users/leafp/tmp/inherits2.dart, line 7, col 10)
1 warning found.
leafp-macbookpro:~ leafp$ dart2js --version
Dart-to-JavaScript compiler (dart2js) version: 1.9.0-dev.10.13
leafp-macbookpro:~ leafp$ dart2js tmp/inherits2.dart 
tmp/inherits2.dart:3:1:
Error: Dart2js does not currently support inheritance of the same class with different type arguments: Both A&lt;T&gt; and A&lt;S&gt; are supertypes of C&lt;S, T&gt;.
class C&lt;S, T&gt; implements B&lt;S&gt;, A&lt;T&gt; {}
^^^^^
tmp/inherits2.dart:6:13:
Warning: 'C&lt;int, String&gt;' is not assignable to 'A&lt;int&gt;'.
&nbsp;&nbsp;A&lt;int&gt; a0 = new C&lt;int, String&gt;();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
Error: Compilation failed.
leafp-macbookpro:~ leafp$ dart --version
Dart VM version: 1.9.0-dev.10.13 (Mon Mar 23 05:02:38 2015) on &quot;macos_x64&quot;
leafp-macbookpro:~ leafp$ dart -c tmp/inherits2.dart
leafp-macbookpro:~

**Comment by johnniwinther** [comment]
The error is not in the assignment but in the multiple inheritance in the hierarchy (C implements A as both A<S> and A<T>) which dart2js does not support.

**Comment by sigmundch** [comment]
this will be handled by the CFE, I believe it wont be allowed like dart2js did.
