### ISSUE TITLE
Elements that get the same prototype as a superclass do not get the right class in dart2js

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#23144]
On IE the foreignobject tag gets a prototype of SVGElement, and we don't recognize it. Tried putting in a check in native_helper.dart in getTagIE like

&nbsp;&nbsp;&nbsp;&nbsp;if (tag == &quot;SVGElement&quot;) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (o.tagName == &quot;foreignObject&quot;) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return &quot;!SVGForeignObjectElement&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return &quot;!SVGElement&quot;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

That should set the class record on the individual object instead of on the shared prototype, but that doesn't work because the initNativeDispatchContinue has already set it on the prototype before we ever get there. So probably it needs an exception.

**Comment by vsmenon** [comment]
Closing as obsolete.
