### ISSUE TITLE
analyzer omits compile-time error for implicit 'this' in instance variable initializer

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23157]
This is the same as issue #21210, but for dartanalyzer instead of dart2js. The affected tests are:

Language/12_Expressions/14_Function_Invocation/3_Unqualified_Invocation_A01_t17
Language/12_Expressions/14_Function_Invocation/3_Unqualified_Invocation_A01_t18

(note that issue #21210 refers to the first edition of the spec, the same section can be found in the second edition of ecma-408 in chapter 16.14.3).

**Comment by srawlins** [comment]
This is stale; the referenced tests have moved or been deleted. If this is still an issue, I imagine a newer issue has been opened. But I suspect it is not an issue any longer.
