### ISSUE TITLE
Groups in tests with spaces in their name always pass, no matter what

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#23156]
See also https://github.com/dart-lang/test/issues/61 , but I suspect the problem is at least partially in test.py

So I can write a program like the attached foo_test, put it in dart/tests/html/foo_test.dart and run it with 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tools/test.py -m release -c dart2js -r chrome -j 1 html/foo_test

and get one pass and one fail. This is causing real false passes in our repo, e.g. a number of the groups in node_validator_test had spaces in the names, so we weren't actually properly testing HTML sanitization. It would be good if this either worked or was an error. I will try and track down any other tests in HTML that have this property.

______
**Attachment:**
[foo_test.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-23156/comment-0/foo_test.dart) (426 Bytes)

**Comment by ricowind** [comment]
did this get rolled in?

**Comment by kevmoo** [comment]
Yup! https://github.com/dart-lang/test/commit/e11f42991f24288fa3e37bab61c2742859c057cc
