### ISSUE TITLE
Analyzer should report a compile-time error for "factory const".

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23168]
The following program is accepted by analyzer with no errors or warnings, but is rejected as a parse error by the VM and dart2js:

class C {
&nbsp;&nbsp;factory const C() = C.named;
&nbsp;&nbsp;const C.named();
}
main() {
&nbsp;&nbsp;print(new C());
}

Based on my reading of the spec, the analyzer behavior is wrong.  The spec's grammar production for redirectingFactoryConstructorSignature is:

redirectingFactoryConstructorSignature:
&nbsp;&nbsp;&nbsp;&nbsp;const? factory identifier ('.' identifier)? formalParameterList '=' type ('.' identifier)?

Therefore &quot;const factory&quot; should be permitted, but &quot;factory const&quot; should be an error.

**Comment by natebosch** [comment]
I now get an error for this: "The modifier 'const' should be before the modifier 'factory'. [const_after_factory]"
