### ISSUE TITLE
No line number in stack trace and seems incomplete

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23162]
In the stack trace below, there's no line number for item #­0. Also, I believe that I should be seeing &quot;handleData&quot; at the top of the stack.

Exiting due to uncaught error.
Command not implemented yet: DriverCommand.Signal
#­0      readCommands.&lt;readCommands_async_body&gt; (package:fletchc/src/driver.dart)
#­1      \_asyncCatchHelper.&lt;anonymous closure&gt; (dart:core-patch/core_patch.dart:15)
#­2      \_rootRunBinary (dart:async/zone.dart:914)
#­3      \_CustomZone.runBinary (dart:async/zone.dart:812)
#­4      \_Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#­5      \_Future._propagateToListeners (dart:async/future_impl.dart:580)
#­6      \_Future._completeError (dart:async/future_impl.dart:376)
#­7      \_StreamIteratorImpl._onError (dart:async/stream_impl.dart:1063)
#­8      \_RootZone.runBinaryGuarded (dart:async/zone.dart:1104)
#­9      \_BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#­10     \_BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:371)
#­11     \_DelayedError.perform (dart:async/stream_impl.dart:606)
#­12     \_StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#­13     \_PendingEvents.schedule.&lt;anonymous closure&gt; (dart:async/stream_impl.dart:671)
#­14     \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­15     \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­16     \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­17     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

The error is thrown here:

&nbsp;&nbsp;void handleData(Uint8List data) {
&nbsp;&nbsp;&nbsp;&nbsp;// TODO(ahe): makeView(data, ...) to ensure monomorphism?
&nbsp;&nbsp;&nbsp;&nbsp;builder.add(data);
&nbsp;&nbsp;&nbsp;&nbsp;if (builder.length &lt; headerSize) return;
&nbsp;&nbsp;&nbsp;&nbsp;Uint8List list = builder.takeBytes();
&nbsp;&nbsp;&nbsp;&nbsp;ByteData view = new ByteData.view(list.buffer, list.offsetInBytes);
&nbsp;&nbsp;&nbsp;&nbsp;int length = view.getUint32(0, commandEndianness);
&nbsp;&nbsp;&nbsp;&nbsp;if (list.length - headerSize &lt; length) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;builder.add(list);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;int commandCode = view.getUint8(4);

&nbsp;&nbsp;&nbsp;&nbsp;DriverCommand command = DriverCommand.values[commandCode];
&nbsp;&nbsp;&nbsp;&nbsp;view = new ByteData.view(list.buffer, list.offsetInBytes + headerSize);
&nbsp;&nbsp;&nbsp;&nbsp;switch (command) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case DriverCommand.Arguments:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;controller.add(new Command(command, decodeArgumentsCommand(view)));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case DriverCommand.Stdin:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int length = view.getUint32(0, commandEndianness);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;controller.add(new Command(command, makeView(view, 4, length)));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;controller.addError(&quot;Command not implemented yet: $command&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}

But readCommands look like this:

Future&lt;Null&gt; readCommands(
&nbsp;&nbsp;&nbsp;&nbsp;StreamIterator&lt;Command&gt; commandIterator,
&nbsp;&nbsp;&nbsp;&nbsp;IOSink stdin) async {
&nbsp;&nbsp;while (await commandIterator.moveNext()) {
&nbsp;&nbsp;&nbsp;&nbsp;Command command = commandIterator.current;
&nbsp;&nbsp;&nbsp;&nbsp;if (command.code == DriverCommand.Stdin) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (command.data.length == 0) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await stdin.close();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdin.add(command.data);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Zone.ROOT.print(&quot;Unexpected command from client: $command&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
}

The complete source file is here: https://github.com/dart-lang/fletch/blob/f2d614a6248ae05b0d2ed366a1bb08180693873d/pkg/fletchc/lib/src/driver.dart

We're using Dart VM version 1.10.0-edge.44800 with this CL patched in: https://codereview.chromium.org/1061283003.

**Comment by mhausner** [comment]
I can't repro this.
