### ISSUE TITLE
service/debugging_test failing on windows debug

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#23179]
http://build.chromium.org/p/client.dart/builders/vm-win32-debug-be/builds/5859

This also seems to be hanging afterwards, see the taskkill step (i.e., the dart process from the testing is not terminating and we kill it - you can see the command line starting the service in the taskkill stdio output

I did not suppress this since the bot would remain red due to the task still being alive afterwards

**Comment by turnidge** [comment]
Old bug, closing.
