### ISSUE TITLE
Analysis Server doesn't notify clients when no analysis needs to be performed.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23177]
Usually the sequence follows:

SEND: {&quot;id&quot;:&quot;14900&quot;,&quot;method&quot;:&quot;analysis.updateContent&quot; ...
RECV: {&quot;id&quot;:&quot;14900&quot;,&quot;result&quot;:{}}
RECV: {&quot;event&quot;:&quot;server.status&quot;,&quot;params&quot;:{&quot;analysis&quot;:{&quot;isAnalyzing&quot;:false}}}

However, sometimes the server.status is never sent (example to follow by email).

**Comment by srawlins** [comment]
Unclear if this is still a problem for the legacy protocol. But even if it is, this is a `P4` issue.

**Comment by bwilkerson** [comment]
Given that there have been no other reported problems with the protocol, I'm going to close this.
