### ISSUE TITLE
Invalid method tree in Observatory profiler

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#23172]
1. Download Editor from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/editor/
&nbsp;&nbsp;&nbsp;I used http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/editor/darteditor-macos-ia32.zip

2. Extract it somewhere into dart folder.

3. Create dart/.options file with a single line (end it with \n)

------
com.google.dart.tools.core/experimental/analysisServer/profile=true

------

4. Edit DartEditor.ini to include following lines before the &quot;-vmargs&quot; line (change path to .options file):

--------
-debug
/Users/scheglov/tmp/dart/.options

--------

5. Start Editor.

6. Open package &quot;pkg/analyzer&quot; from the Dart repository.

7. Wait for analysis to finish.

8. Open Observatory at http://127.0.0.1:8181/ and open profiler.

9. Expand indexOperation / Dart / \_OneByteString.== items.

10. Note that profiler show that \_OneByteString.== is invoked by ElementCodec.encode2(), but actually it does not.

---------
&nbsp;&nbsp;/\*\*
&nbsp;&nbsp;&nbsp;\* Returns the second component of the [element] id.
&nbsp;&nbsp;&nbsp;\* In the most cases it is the [element]'s name offset.
&nbsp;&nbsp;&nbsp;\*/
&nbsp;&nbsp;int encode2(Element element) {
&nbsp;&nbsp;&nbsp;&nbsp;if (element is NameElement) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String name = element.name;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return \_stringCodec.encode(name);
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;if (element is ConstructorElement) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return element.enclosingElement.nameOffset;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return element.nameOffset;
&nbsp;&nbsp;}

---------
______
**Attachment:**
[Screen Shot 2015-04-10 at 12.51.23 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-23172/comment-0/Screen Shot 2015-04-10 at 12.51.23 PM.png) (200.67 KB)

**Comment by johnmccutchan** [comment]
Assumed stale.
