### ISSUE TITLE
Dart2js does not substitute type parameters when checking type of const with instance var initialized at declaration site.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23182]
The following code is runs without errors in the VM in both checked and unchecked mode:

class A {
&nbsp;&nbsp;const A();
}
class Test&lt;T extends A&gt; {
&nbsp;&nbsp;final T x = const A();
&nbsp;&nbsp;const Test();
}
main() {
&nbsp;&nbsp;print(const Test&lt;A&gt;());
}

However, when dart2js is given this input and told to compile in checked mode, it produces the error:

../../../tmp/test.dart:5:3:
Error: 'A' is not assignable to 'T'.
&nbsp;&nbsp;final T x = const A();
&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^
../../../tmp/test.dart:5:3:
Error: 'A' is not assignable to 'T'.
&nbsp;&nbsp;final T x = const A();
&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

I believe the VM behavior is correct: the assignment of &quot;const A()&quot; to the instance variable x should happen in the context of evaluating the constant &quot;const Test&lt;A&gt;()&quot;, thus type variable substitution should have changed the T into A, causing the type check to succeed.  Judging from dart2js's error message, it appears that it is not doing the type variable substitution properly.

The problem can be worked around by changing the main function to &quot;print(new Test&lt;A&gt;());&quot;, dart2js produces code that runs without exceptions.  It can also be worked around by moving the initialization of x from the declaration of the field to the declaration of the constructor (i.e. &quot;const Test() : x = const A();&quot;).  This suggests that the type check is only done incorrectly during constant evaluation, when the instance variable is initialized at the declaration site.

**Comment by stereotype441** [comment]
@hterkelsen Do we need to update `tests/language/language_dart2js.status`?  It still shows failures due to this bug.

**Comment by hterkelsen** [comment]
Yes, I missed those when I submitted the change. I updated the status file in 4eb2f6694b5f450b17022eb7f3bce36daca9b5fe
