### ISSUE TITLE
When incremental resolution fails, analysis server sends server.status(isAnalyzing:false) prior to analysis being finished.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23199]
While tracking down issue #23176, I noticed that sometimes the analysis server sends a server.status message with isAnalyzing=false prior to finishing analysis.  For example:

4.80561: SEND: {&quot;id&quot;:&quot;5&quot;,&quot;method&quot;:&quot;analysis.updateContent&quot;,&quot;params&quot;:{&quot;files&quot;:{&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;:...}}}
4.957881: RECV: {&quot;event&quot;:&quot;server.status&quot;,&quot;params&quot;:{&quot;analysis&quot;:{&quot;isAnalyzing&quot;:true}}}
4.959091: RECV: {&quot;event&quot;:&quot;server.status&quot;,&quot;params&quot;:{&quot;analysis&quot;:{&quot;isAnalyzing&quot;:false}}}
4.983654: RECV: {&quot;id&quot;:&quot;5&quot;,&quot;result&quot;:{}}
4.98573: RECV: {&quot;event&quot;:&quot;server.status&quot;,&quot;params&quot;:{&quot;analysis&quot;:{&quot;isAnalyzing&quot;:true}}}
4.987025: RECV: {&quot;event&quot;:&quot;analysis.errors&quot;,&quot;params&quot;:{&quot;file&quot;:&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;,&quot;errors&quot;:[]}}
4.988488: RECV: {&quot;event&quot;:&quot;analysis.errors&quot;,&quot;params&quot;:{&quot;file&quot;:&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;,&quot;errors&quot;:[...]}}
5.001836: RECV: {&quot;event&quot;:&quot;analysis.errors&quot;,&quot;params&quot;:{&quot;file&quot;:&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;,&quot;errors&quot;:[...]}}
5.007117: RECV: {&quot;event&quot;:&quot;analysis.errors&quot;,&quot;params&quot;:{&quot;file&quot;:&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;,&quot;errors&quot;:[...]}}
5.008658: RECV: {&quot;event&quot;:&quot;analysis.errors&quot;,&quot;params&quot;:{&quot;file&quot;:&quot;/var/folders/55/83dl8yk507bbspsg0b1vd5b0007dgy/T/analysisServerugfHGZ/test.dart&quot;,&quot;errors&quot;:[...]}}
5.010725: RECV: {&quot;event&quot;:&quot;server.status&quot;,&quot;params&quot;:{&quot;analysis&quot;:{&quot;isAnalyzing&quot;:false}}}

Note that in response to command 5 (which makes a large change to file &quot;.../test.dart&quot;, introducing errors), the server sends two server.status messages, indicating that analysis has started and stopped.  But it doesn't send any error notifications.  Later, after acknowledging command 5, the server sends an additional server.status message indicating that analysis has begun, followed by the expected error notifications, followed by a server.status message indicating that analysis has stopped again.

I suspect what is happening is that the server sends server.status(isAnalyzing:true) when incremental analysis starts.  Then, when it discovers that the change is too complex to be handled by incremental resolution, it sends server.status(isAnalyzing:false) to indicate that incremental resolution has stopped.  Only later does it notice that there is now non-incremental work to do, so it sends server.status(isAnalyzing:true) again.

This makes it really difficult to write integration tests that wait for analysis to complete before taking their next action, because when the test driver receives a server.status message with isAnalyzing=false, there's no way for it to know whether there is still more analysis to do.

**Comment by scheglov** [comment]
This was fixed.
