### ISSUE TITLE
Support PhantomJS on the package bots

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23195]
The test runner is going to start supporting PhantomJS, and it would be nice to run its tests of that functionality on the bots. Doing so requires that PhantomJS be installed there.

**Comment by ricowind** [comment]
Do we still need this (just wondering)

**Comment by nex3** [comment]
Yeah, the `test` bots have tests that exercise it.

**Comment by whesse** [comment]
Ping

**Comment by kevmoo** [comment]
Ping? We've still like this on the bots, please. 😄

**Comment by whesse** [comment]
It was a ping to me, that this issue is current.

**Comment by matanlurey** [comment]
Phantom is deprecated. I don't see this being useful anymore.
