### ISSUE TITLE
Dartium uncaught error: Dart_GetNativeIntegerArgument: expects argument at 1 to be of type Integer.

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23202]
Simply cd into examples/, run pub serve and open http://localhost:8080/src/material/checkbox/ in Dartium.

______
**Attachment:**
[repro.tar.gz](https://storage.googleapis.com/google-code-attachments/dart/issue-23202/comment-0/repro.tar.gz) (367.31 KB)

**Comment by alan-knight** [comment]
No longer occurs in current version. I do get a disabled noSuchMethod, but I suspect that's from changes in the base, and it's a very different type of error.
