### ISSUE TITLE
Investigate service/debugging_test failures on Windows

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#23201]
FAILED: none-vm debug_ia32 service/debugging_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm\]:

stdout:
\*\* Launching build\DebugIA32\dart.exe --compile-all --error_on_bad_type --error_on_bad_override --checked --ignore-unrecognized-flags --package-root=build/DebugIA32/packages/ --enable-vm-service:0 e:\b\build\slave\vm-win32-debug-be\build\dart\runtime\observatory\tests\service\debugging_test.dart --testee-mode
Observatory listening on http://127.0.0.1:51219
\*\* Signaled to run test queries on 51219

100000000
200000000
300000000
400000000
500000000
600000000
700000000
800000000
900000000
1000000000
Running debugging_test.dart [0/8]
Running debugging_test.dart [1/8]
Running debugging_test.dart [2/8]
Breakpoint reached
Running debugging_test.dart [3/8]
Running debugging_test.dart [4/8]
Breakpoint reached
Running debugging_test.dart [5/8]
Unexpected exception in service tests: Expected: 'testFunction'
&nbsp;&nbsp;Actual: '+'
&nbsp;&nbsp;&nbsp;Which: is different.
Expected: testFuncti ...
&nbsp;&nbsp;Actual: +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;Differ at offset 0
&nbsp;#­0      DefaultFailureHandler.fail (package:matcher/src/expect.dart:117:5)
#­1      DefaultFailureHandler.failMatch (package:matcher/src/expect.dart:121:5)
#­2      expect (package:matcher/src/expect.dart:95:20)
#­3      tests.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///e:/b/build/slave/vm-win32-debug-be/build/dart/runtime/observatory/tests/service/debugging_test.dart:115:7)
#­4      \_rootRunUnary (dart:async/zone.dart:902)
#­5      \_CustomZone.runUnary (dart:async/zone.dart:804)
#­6      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#­7      \_Future._propagateToListeners (dart:async/future_impl.dart:577)
#­8      \_Future._completeWithValue (dart:async/future_impl.dart:368)
#­9      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:422)
#­10     \_rootRun (dart:async/zone.dart:895)
#­11     \_CustomZone.run (dart:async/zone.dart:796)
#­12     \_CustomZone.runGuarded (dart:async/zone.dart:704)
#­13     \_CustomZone.bindCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:729)
#­14     \_microtaskLoop (dart:async/schedule_microtask.dart:43)
#­15     \_microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#­16     \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­17     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

stderr:
Unhandled exception:
Uncaught Error: Expected: 'testFunction'
&nbsp;&nbsp;Actual: '+'
&nbsp;&nbsp;&nbsp;Which: is different.
Expected: testFuncti ...
&nbsp;&nbsp;Actual: +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;Differ at offset 0

Stack Trace:
#­0      DefaultFailureHandler.fail (package:matcher/src/expect.dart:117:5)
#­1      DefaultFailureHandler.failMatch (package:matcher/src/expect.dart:121:5)
#­2      expect (package:matcher/src/expect.dart:95:20)
#­3      tests.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///e:/b/build/slave/vm-win32-debug-be/build/dart/runtime/observatory/tests/service/debugging_test.dart:115:7)
#­4      \_rootRunUnary (dart:async/zone.dart:902)
#­5      \_CustomZone.runUnary (dart:async/zone.dart:804)
#­6      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#­7      \_Future._propagateToListeners (dart:async/future_impl.dart:577)
#­8      \_Future._completeWithValue (dart:async/future_impl.dart:368)
#­9      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:422)
#­10     \_rootRun (dart:async/zone.dart:895)
#­11     \_CustomZone.run (dart:async/zone.dart:796)
#­12     \_CustomZone.runGuarded (dart:async/zone.dart:704)
#­13     \_CustomZone.bindCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:729)
#­14     \_microtaskLoop (dart:async/schedule_microtask.dart:43)
#­15     \_microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#­16     \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­17     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#­0      \_rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
#­1      \_microtaskLoop (dart:async/schedule_microtask.dart:43)
#­2      \_microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#­3      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­4      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm\]: set DART_CONFIGURATION=DebugIA32 &amp; build\DebugIA32\dart.exe --compile-all --error_on_bad_type --error_on_bad_override --checked --ignore-unrecognized-flags --package-root=build/DebugIA32/packages/ e:\b\build\slave\vm-win32-debug-be\build\dart\runtime\observatory\tests\service\debugging_test.dart
Took 0:00:22.153000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 service/debugging_test

**Comment by turnidge** [comment]
The debugging_test is no longer quite so brittle.  Test re-enabled on windows in 0230492433a0de2c1385380822de73e514ca52ab.
