### ISSUE TITLE
Local functions differ from local variables wrt assignment

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#23218]
See https://code.google.com/p/dart/issues/detail?id=23193

**Comment by eernstg** [comment]
This issue relies on assumptions which are no longer true (for Dart 2): It is now a compile-time error to assign to a local function, and the dynamic semantics of such code is hence irrelevant (so we don't care whether we would have executed `noSuchMethod` or thrown a `NoSuchMethodError`), and hence there is no need to adjust the language specification to say any of the two. Closing.
