### ISSUE TITLE
SEGV in VM if the line  isolate->heap()->WriteProtect(true); is commented out

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23217]
If line isolate-&gt;heap()-&gt;WriteProtect(true); is commented out as
// isolate-&gt;heap()-&gt;WriteProtect(true)
in Object::FinalizeVMIsolate(Isolate\* isolate) it leads to a SEGV
One would expect that the call to write protect the VM heap memory should not have any side effects.

(gdb) where
#­0  0xf71e90e0 in ?? ()
#­1  0xf6ec0082 in ?? ()
#­2  0xf6ec16f5 in ?? ()
#­3  0xf6ec2768 in ?? ()
#­4  0xf6ec2079 in ?? ()
#­5  0x080cb57f in dart::DartEntry::InvokeFunction (function=..., 
&nbsp;&nbsp;&nbsp;&nbsp;arguments=..., arguments_descriptor=...) at runtime/vm/dart_entry.cc:120
#­6  0x080cd1f1 in dart::DartEntry::InvokeFunction (function=..., 
&nbsp;&nbsp;&nbsp;&nbsp;arguments=...) at runtime/vm/dart_entry.cc:27
#­7  0x080cefd4 in dart::DartLibraryCalls::InstanceCreate (lib=..., 
&nbsp;&nbsp;&nbsp;&nbsp;class_name=..., constructor_name=..., arguments=...)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_entry.cc:374
#­8  0x082ce2f0 in dart::ObjectStore::PreallocateObjects (this=0x867a918)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/object_store.cc:136
#­9  0x080bfc50 in dart::Dart::InitializeIsolate (
&nbsp;&nbsp;&nbsp;&nbsp;snapshot_buffer=snapshot_buffer@entry=0x0, data=data@entry=0x0)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart.cc:264
#­10 0x08064b2e in dart::Dart_CreateIsolate (script_uri=0x0, main=0x0, 
&nbsp;&nbsp;&nbsp;&nbsp;snapshot=0x0, callback_data=0x0, error=0xffffd048)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/dart_api_impl.cc:1298
#­11 0x0804b4f2 in dart::bin::main (argc=argc@entry=5, 
&nbsp;&nbsp;&nbsp;&nbsp;argv=argv@entry=0xffffd144) at runtime/bin/gen_snapshot.cc:553
#­12 0x0804b87b in main (argc=5, argv=0xffffd144)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/bin/gen_snapshot.cc:628

**Comment by kodandersson** [comment]
f500a1bdd8e57750059005e2ee5260364a811427
