### ISSUE TITLE
Warnings on missing async are very unhelpful

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23234]
Consider the following code:

main() {
&nbsp;&nbsp;var x = await foo();
}

foo() async {
&nbsp;&nbsp;print (&quot;Hi&quot;);
}

The return from Analyzer is:
info:  The value of the local variable 'x' is not used
error: Expected to find ';'
warning: Undefined name 'await'

The return from Dart2JS is:

error: line 2 pos 17: semicolon expected
Warning: Cannot resolve 'await'.
&nbsp;&nbsp;var x = await foo();

The return from the VM is: 
error: line 2 pos 17: semicolon expected

&equals;&equals;&equals;=

None of these help the user fix the problem, which is that the main method is missing an async.

I suggest that we add a specific case here that reports something like

&quot;await may only be used in a method marked async. consider replacing 'main() {' with 'main() async {'&quot;

@Gilad - do you agree? Is there a wording change we need of 'marked async'?

**Comment by sigmundch** [comment]
seems like this and  #22625 are the same, so I'll close this issue as a duplicate.

**Comment by sethladd** [comment]
Love the dart2js message, when it encounters await without an async. Very cool.

https://codereview.chromium.org/1094903002/diff/80001/pkg/compiler/lib/src/warnings.dart

**Comment by lukechurch** [comment]
+1

**Comment by trinarytree** [comment]
I just got burned by this yet again.  It makes you waste your time looking everywhere for a mismatched parenthesis or a missing semicolon or something like that.  Is there any ETA on a fix?
