### ISSUE TITLE
VM service test failing with --optimization-counter-threshold=5 in debug mode

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#23232]
Revision: 45201

python tools/test.py --vm-options --optimization-counter-threshold=5 -t120 service/debugging_test

stdout:

Observatory listening on http://127.0.0.1:46715
\*\* Signaled to run test queries on 46715

100000000
200000000
300000000
400000000
500000000
600000000
700000000
800000000
900000000
1000000000
Running debugging_test.dart [0/8]
Running debugging_test.dart [1/8]
Running debugging_test.dart [2/8]
Breakpoint reached
Running debugging_test.dart [3/8]
Running debugging_test.dart [4/8]
Breakpoint reached
Running debugging_test.dart [5/8]
Unexpected exception in service tests: Expected: 'testFunction'
&nbsp;&nbsp;Actual: '+'
&nbsp;&nbsp;&nbsp;Which: is different.
Expected: testFuncti ...
&nbsp;&nbsp;Actual: +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;Differ at offset 0

**Comment by turnidge** [comment]
The test is no longer quite so brittle.  I am able to make this pass now.  Closing.
