### ISSUE TITLE
ASSERTION FAILED: !m_exception in blink::DartExceptionState::~DartExceptionState()

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23245]
&nbsp;&nbsp;[24189:24189:0416/180910:INFO:CONSOLE(78)] &quot;{
&nbsp;&nbsp;&nbsp;&nbsp;&quot;type&quot;: &quot;debug&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;value&quot;: &quot;test_controller.js started&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;timestamp&quot;: 0
&nbsp;&nbsp;}&quot;, source: http://127.0.0.1:49736/root_dart/tools/testing/dart/test_controller.js (78)
&nbsp;&nbsp;[24189:24189:0416/180910:INFO:CONSOLE(78)] &quot;{
&nbsp;&nbsp;&nbsp;&nbsp;&quot;type&quot;: &quot;debug&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;value&quot;: &quot;Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;timestamp&quot;: 0.052
&nbsp;&nbsp;}&quot;, source: http://127.0.0.1:49736/root_dart/tools/testing/dart/test_controller.js (78)
&nbsp;&nbsp;[24189:24189:0416/180912:INFO:CONSOLE(0)] &quot;Observatory listening at http://:0/&quot;, source: http://127.0.0.1:49736/root_build/generated_tests/none-dartium/tests_co19_src_WebPlatformTest_html_semantics_embedded-content_media-elements_interfaces_HTMLElement_HTMLMediaElement_addTextTrack_t01/test.html?crossOriginPort=53143 (0)
&nbsp;&nbsp;[24189:24189:0416/180912:INFO:CONSOLE(78)] &quot;{
&nbsp;&nbsp;&nbsp;&nbsp;&quot;type&quot;: &quot;print&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;value&quot;: &quot;dart-calling-main&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&quot;timestamp&quot;: 2.008
&nbsp;&nbsp;}&quot;, source: http://127.0.0.1:49736/root_dart/tools/testing/dart/test_controller.js (78)
&nbsp;&nbsp;ASSERTION FAILED: !m_exception
&nbsp;&nbsp;../../third_party/WebKit/Source/bindings/core/dart/DartExceptionState.h(46) : blink::DartExceptionState::~DartExceptionState()
&nbsp;&nbsp;1   0x7f5bfde4176b
&nbsp;&nbsp;2   0x7f5bfe8d5078
&nbsp;&nbsp;3   0x7f5bff57845e
&nbsp;&nbsp;4   0x7f5be4ed6296
&nbsp;&nbsp;Received signal 11 SEGV_MAPERR 0000fbadbeef
&nbsp;&nbsp;#­0 0x7f5c0644a02e base::debug::StackTrace::StackTrace()
&nbsp;&nbsp;#­1 0x7f5c06449b63 base::debug::(anonymous namespace)::StackDumpSignalHandler()
&nbsp;&nbsp;#­2 0x7f5bf73cccb0 &lt;unknown&gt;
&nbsp;&nbsp;#­3 0x7f5bfde41777 blink::DartExceptionState::~DartExceptionState()
&nbsp;&nbsp;#­4 0x7f5bfe8d5078 blink::DartHTMLMediaElementInternal::addTextTrackCallback()
&nbsp;&nbsp;#­5 0x7f5bff57845e dart::NativeEntry::NativeCallWrapper()
&nbsp;&nbsp;#­6 0x7f5be4ed6296 &lt;unknown&gt;

To retest, run:  /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/dart/http_server.dart -p 49736 -c 53143 --build-directory=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug --runtime=dartium --package-root=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug/packages

Command[dartium]: /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:49736/root_build/generated_tests/none-dartium/tests_co19_src_WebPlatformTest_html_semantics_embedded-content_media-elements_interfaces_HTMLElement_HTMLMediaElement_addTextTrack_t01/test.html?crossOriginPort=53143
Took 0:02:00.583020

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -rdartium -t120 co19/WebPlatformTest/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLMediaElement/addTextTrack_t01

FAILED: none-dartium debug_ia32 co19/LayoutTests/fast/canvas/canvas-lineDash-input-sequence_t01

The generated bindings code needs to pass in the DartExceptionState to the native methods and then call es.hadException() to check for exceptions

e.g:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int argCount /* FIXME(vsm): Remove this. */ ALLOW_UNUSED = Dart_GetNativeArgumentCount(args);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DartExceptionState es;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Blob* blob = DartBlob::toNative(args, 1, exception);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (exception)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;goto fail;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (UNLIKELY(argCount &lt;= 2)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;receiver-&gt;readAsText(blob, es);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (exception)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;goto fail;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

Should be:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int argCount /* FIXME(vsm): Remove this. */ ALLOW_UNUSED = Dart_GetNativeArgumentCount(args);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DartExceptionState es;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Blob* blob = DartBlob::toNative(args, 1, exception);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (exception)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;goto fail;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (UNLIKELY(argCount &lt;= 2)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;receiver-&gt;readAsText(blob, es);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (es.hadException()) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exception = es.toDart(args, true);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;goto fail;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

**Comment by terrylucas** [comment]
Not an issue using JSInterop instead of C++ stubs.
