### ISSUE TITLE
ASSERTION FAILED: !EventDispatchForbiddenScope::isEventDispatchForbidden()

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23247]
ASSERTION FAILED: !EventDispatchForbiddenScope::isEventDispatchForbidden()
&nbsp;&nbsp;../../third_party/WebKit/Source/core/dom/Node.cpp(2125) : void blink::Node::dispatchSubtreeModifiedEvent()
&nbsp;&nbsp;1   0x7fa1a8e1d366
&nbsp;&nbsp;2   0x7fa1a8dd78d0
&nbsp;&nbsp;3   0x7fa1a8dd784b
&nbsp;&nbsp;4   0x7fa1a8dde29f
&nbsp;&nbsp;5   0x7fa1a8dcfe2f
&nbsp;&nbsp;6   0x7fa1a96bd65e
&nbsp;&nbsp;7   0x7fa1a961bdb2
&nbsp;&nbsp;8   0x7fa1a94fe230
&nbsp;&nbsp;9   0x7fa1a9501e94
&nbsp;&nbsp;10  0x7fa1a8df5699
&nbsp;&nbsp;11  0x7fa1a8e7f8af
&nbsp;&nbsp;12  0x7fa1a8e7d37c
&nbsp;&nbsp;13  0x7fa1a8ddeeba
&nbsp;&nbsp;14  0x7fa1a8dd4413
&nbsp;&nbsp;15  0x7fa1a8d50a25
&nbsp;&nbsp;16  0x7fa1a8d4ec43
&nbsp;&nbsp;17  0x7fa1a8d4e6e2
&nbsp;&nbsp;18  0x7fa1a8d4e0a1
&nbsp;&nbsp;19  0x7fa1a8e15feb
&nbsp;&nbsp;20  0x7fa1a87a5e1b
&nbsp;&nbsp;21  0x7fa1a931e45e
&nbsp;&nbsp;22  0x7fa18ee8e296
&nbsp;&nbsp;Received signal 11 SEGV_MAPERR 0000fbadbeef
&nbsp;&nbsp;#­0 0x7fa1b01f002e base::debug::StackTrace::StackTrace()
&nbsp;&nbsp;#­1 0x7fa1b01efb63 base::debug::(anonymous namespace)::StackDumpSignalHandler()
&nbsp;&nbsp;#­2 0x7fa1a1172cb0 &lt;unknown&gt;
&nbsp;&nbsp;#­3 0x7fa1a8e1d372 blink::Node::dispatchSubtreeModifiedEvent()
&nbsp;&nbsp;#­4 0x7fa1a8dd78d0 blink::Element::didAddAttribute()
&nbsp;&nbsp;#­5 0x7fa1a8dd784b blink::Element::appendAttributeInternal()
&nbsp;&nbsp;#­6 0x7fa1a8dde29f blink::Element::setAttributeInternal()
&nbsp;&nbsp;#­7 0x7fa1a8dcfe2f blink::Element::setAttribute()
&nbsp;&nbsp;#­8 0x7fa1a96bd65e blink::TextControlInnerContainer::create()
&nbsp;&nbsp;#­9 0x7fa1a961bdb2 blink::TextFieldInputType::listAttributeTargetChanged()
&nbsp;&nbsp;#­10 0x7fa1a94fe230 blink::HTMLInputElement::listAttributeTargetChanged()
&nbsp;&nbsp;#­11 0x7fa1a9501e94 blink::ListAttributeTargetObserver::idTargetChanged()
&nbsp;&nbsp;#­12 0x7fa1a8df5699 blink::IdTargetObserverRegistry::notifyObserversInternal()
&nbsp;&nbsp;#­13 0x7fa1a8e7f8af blink::IdTargetObserverRegistry::notifyObservers()
&nbsp;&nbsp;#­14 0x7fa1a8e7d37c blink::TreeScope::addElementById()
&nbsp;&nbsp;#­15 0x7fa1a8ddeeba blink::Element::updateId()
&nbsp;&nbsp;#­16 0x7fa1a8dd4413 blink::Element::insertedInto()
&nbsp;&nbsp;#­17 0x7fa1a8d50a25 blink::ContainerNode::notifyNodeInsertedInternal()
&nbsp;&nbsp;#­18 0x7fa1a8d4ec43 blink::ContainerNode::notifyNodeInserted()
&nbsp;&nbsp;#­19 0x7fa1a8d4e6e2 blink::ContainerNode::updateTreeAfterInsertion()
&nbsp;&nbsp;#­20 0x7fa1a8d4e0a1 blink::ContainerNode::appendChild()
&nbsp;&nbsp;#­21 0x7fa1a8e15feb blink::Node::appendChild()
&nbsp;&nbsp;#­22 0x7fa1a87a5e1b blink::DartNodeInternal::appendChildCallback()
&nbsp;&nbsp;#­23 0x7fa1a931e45e dart::NativeEntry::NativeCallWrapper()

To retest, run:  /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/dart/http_server.dart -p 49736 -c 53143 --build-directory=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug --runtime=dartium --package-root=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug/packages

Command[dartium\]: /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:49736/root_build/generated_tests/none-dartium/tests_co19_src_LayoutTests_fast_forms_datalist_input-list_t01/test.html?crossOriginPort=53143
Took 0:02:00.362608

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -rdartium -t120 co19/LayoutTests/fast/forms/datalist/input-list_t01

FAILED: none-dartium debug_ia32 co19/LayoutTests/fast/forms/datalist/slider-appearance-with-ticks-crash_t01

**Comment by alan-knight** [comment]
Passes in 1.15
