### ISSUE TITLE
canvas.getContext('2d').setLineDash does not throw an exception when a non list value is passed in as an argument

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23246]
ASSERTION FAILED: Dart_IsList(object)

&nbsp;&nbsp;../../third_party/WebKit/Source/bindings/core/dart/DartUtilities.h(177) : static void blink::DartUtilities::toVector(Convertor, Dart_Handle, Vector&lt;T&gt; &amp;, Dart_Handle &amp;) [T = float, Convertor = blink::DartUtilities::TypeConvertor&lt;float&gt;]
&nbsp;&nbsp;1   0x7fed2043501e
&nbsp;&nbsp;2   0x7fed20434fc8
&nbsp;&nbsp;3   0x7fed204228a0
&nbsp;&nbsp;4   0x7fed20fb445e
&nbsp;&nbsp;5   0x7fed06952296
&nbsp;&nbsp;Received signal 11 SEGV_MAPERR 0000fbadbeef
&nbsp;&nbsp;#­0 0x7fed27e8602e base::debug::StackTrace::StackTrace()
&nbsp;&nbsp;#­1 0x7fed27e85b63 base::debug::(anonymous namespace)::StackDumpSignalHandler()
&nbsp;&nbsp;#­2 0x7fed18e08cb0 &lt;unknown&gt;
&nbsp;&nbsp;#­3 0x7fed2043502a blink::DartUtilities::toVector&lt;&gt;()
&nbsp;&nbsp;#­4 0x7fed20434fc8 blink::DartUtilities::toNativeVector&lt;&gt;()
&nbsp;&nbsp;#­5 0x7fed204228a0 blink::DartCanvasRenderingContext2DInternal::setLineDashCallback()
&nbsp;&nbsp;#­6 0x7fed20fb445e dart::NativeEntry::NativeCallWrapper()
&nbsp;&nbsp;#­7 0x7fed06952296 &lt;unknown&gt;
To retest, run:  /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/dart/http_server.dart -p 49736 -c 53143 --build-directory=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug --runtime=dartium --package-root=/mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/out/Debug/packages

Command[dartium\]: /mnt/data/b/build/slave/dartium-lucid64-debug-be/build/src/dart/tools/testing/bin/linux/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:49736/root_build/generated_tests/none-dartium/tests_co19_src_LayoutTests_fast_canvas_canvas-lineDash-input-sequence_t01/test.html?crossOriginPort=53143
Took 0:02:00.568957

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py -rdartium -t120 co19/LayoutTests/fast/canvas/canvas-lineDash-input-sequence_t01

FAILED: none-dartium debug_ia32 co19/LayoutTests/fast/forms/datalist/input-list_t01

**Comment by alan-knight** [comment]
Works in 1.15.
