### ISSUE TITLE
Creating a file to fix an erroneous import leads to errors not getting generated.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23240]
Using Dart Editor with analysis server.

1. Create a file &quot;file1.dart&quot; and populate it with the text &quot;import 'file2.dart';&quot;.  This results in the error message &quot;Target of URI does not exist: 'file2.dart'&quot;, as expected.  Save &quot;file1.dart&quot;.
2. Create a file &quot;file2.dart&quot;.  This fixes the error message, as expected.
3. Insert this text into file &quot;file2.dart&quot;: &quot;class C { final int i; }&quot;

Expected result: a warning message should appear, with the text &quot;The final variable 'i' must be initialized&quot;.

Observed result: no warning.

Digging through the analysis server's instrumentation log and its debugging interface, the file &quot;file2.dart&quot; is in a strange state: the analysis server regards it as an implicitly analyzed file (it should be considered explicitly analyzed), and it has a cached exception for it indicating that the file couldn't be read (in spite of the fact that it \*did\* successfully read it after I created it).  This cached exception stops the analyzer from generating errors and hints for the file.  (Though for some strange reason, it doesn't stop it from trying to resolve the file).

**Comment by bwilkerson** [comment]
This appears to have been fixed.
