### ISSUE TITLE
Incorrect array allocation overflow check for arm/arm64/mips

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23254]
Running test: ArrayLengthMaxElements
runtime/vm/scavenger.cc:223: error: expected: new_addr != 0
[New Thread 0xf7167b40 (LWP 16124)]
[New Thread 0xf72e9b40 (LWP 16123)]

Program received signal SIGABRT, Aborted.
0xf7fdb430 in \__kernel_vsyscall ()
(gdb) bt
#­0  0xf7fdb430 in \__kernel_vsyscall ()
#­1  0xf7cb8607 in raise () from /lib/i386-linux-gnu/libc.so.6
#­2  0xf7cbba33 in abort () from /lib/i386-linux-gnu/libc.so.6
#­3  0x082e1a75 in dart::DynamicAssertionHelper::Fail (this=this@entry=0xffffb0f4, format=format@entry=0x895b884 &quot;expected: %s&quot;)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/platform/assert.cc:41
#­4  0x0861e1bd in ScavengePointer (p=0xffffc148, this=0xffffb344) at runtime/vm/scavenger.cc:223
#­5  dart::ScavengerVisitor::VisitPointers (this=0xffffb344, first=0xffffc148, last=0xffffc148) at runtime/vm/scavenger.cc:96
#­6  0x0843bf8e in VisitPointer (p=0xffffc148, this=0xffffb344) at runtime/vm/visitor.h:37
#­7  dart::Handles&lt;2, 64, 4&gt;::HandlesBlock::VisitObjectPointers (this=this@entry=0xffffc144, visitor=visitor@entry=0xffffb344) at runtime/vm/handles_impl.h:341
#­8  0x0843bcbe in VisitScopedHandles (visitor=0xffffb344, this=0xffffc140) at runtime/vm/handles_impl.h:40
#­9  VisitObjectPointers (visitor=0xffffb344, this=0xffffc140) at runtime/vm/handles_impl.h:29
#­10 dart::VMHandles::VisitObjectPointers (this=this@entry=0xffffc140, visitor=visitor@entry=0xffffb344) at runtime/vm/handles.cc:42
#­11 0x0867b89a in dart::Zone::VisitObjectPointers (this=0xffffb3a8, visitor=visitor@entry=0xffffb344) at runtime/vm/zone.cc:197
#­12 0x084bca76 in dart::Isolate::VisitObjectPointers (this=this@entry=0xacfb9a0, visitor=visitor@entry=0xffffb344, 
&nbsp;&nbsp;&nbsp;&nbsp;visit_prologue_weak_handles=visit_prologue_weak_handles@entry=false, validate_frames=validate_frames@entry=false) at runtime/vm/isolate.cc:1485
#­13 0x0861918f in dart::Scavenger::IterateRoots (this=this@entry=0xad11030, isolate=isolate@entry=0xacfb9a0, visitor=visitor@entry=0xffffb344, 
&nbsp;&nbsp;&nbsp;&nbsp;visit_prologue_weak_persistent_handles=visit_prologue_weak_persistent_handles@entry=false) at runtime/vm/scavenger.cc:565
#­14 0x0861b7e2 in dart::Scavenger::Scavenge (this=0xad11030, invoke_api_callbacks=invoke_api_callbacks@entry=true) at runtime/vm/scavenger.cc:828
#­15 0x0843ecc1 in dart::Heap::CollectGarbage (this=this@entry=0xad0d378, space=space@entry=dart::Heap::kNew, 
&nbsp;&nbsp;&nbsp;&nbsp;api_callbacks=api_callbacks@entry=dart::Heap::kInvokeApiCallbacks, reason=reason@entry=dart::Heap::kNewSpace) at runtime/vm/heap.cc:275
#­16 0x0843ef32 in dart::Heap::CollectGarbage (this=0xad0d378, space=dart::Heap::kNew) at runtime/vm/heap.cc:317
#­17 0x0843f8e8 in dart::Heap::AllocateNew (this=this@entry=0xad0d378, size=size@entry=16) at runtime/vm/heap.cc:82
#­18 0x08569c8f in dart::Heap::Allocate (this=0xad0d378, size=16, space=dart::Heap::kNew) at runtime/vm/heap.h:81
#­19 0x08512350 in dart::Object::Allocate (cls_id=cls_id@entry=4, size=size@entry=16, space=space@entry=dart::Heap::kNew) at runtime/vm/object.cc:1669
#­20 0x0851739a in dart::TypeArguments::New (len=len@entry=1, space=space@entry=dart::Heap::kNew) at runtime/vm/object.cc:4771
#­21 0x085175c3 in dart::TypeArguments::InstantiateFrom (this=this@entry=0xffffc214, instantiator_type_arguments=..., 
&nbsp;&nbsp;&nbsp;&nbsp;bound_error=bound_error@entry=0xffffc18c, trail=0x0) at runtime/vm/object.cc:4687
#­22 0x0852d7ea in dart::Type::InstantiateFrom (this=0xffffc14c, instantiator_type_arguments=..., bound_error=0xffffc18c, trail=0x0)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/object.cc:14757
#­23 0x0853af22 in dart::Instance::IsInstanceOf (this=this@entry=0xffffc144, other=..., other_instantiator=..., bound_error=bound_error@entry=0xffffc18c)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/object.cc:13730
#­24 0x08342f5a in DRT_HelperTypeCheck (isolate=&lt;optimized out&gt;, thread=&lt;optimized out&gt;, zone=&lt;optimized out&gt;, arguments=...)
&nbsp;&nbsp;&nbsp;&nbsp;at runtime/vm/code_generator.cc:507
#­25 dart::DRT_TypeCheck (arguments=...) at runtime/vm/code_generator.cc:489
#­26 0x0863d9af in dart::Simulator::SupervisorCall (this=this@entry=0xad0d1b0, instr=instr@entry=0xad1d734) at runtime/vm/simulator_arm.cc:1535
#­27 0x0863df54 in dart::Simulator::DecodeType7 (this=0xad0d1b0, instr=0xad1d734) at runtime/vm/simulator_arm.cc:2605
#­28 0x08640055 in dart::Simulator::InstructionDecode (this=this@entry=0xad0d1b0, instr=0xad1d734) at runtime/vm/simulator_arm.cc:3633
#­29 0x0864028a in dart::Simulator::Execute (this=this@entry=0xad0d1b0) at runtime/vm/simulator_arm.cc:3663
#­30 0x086405de in dart::Simulator::Call (this=0xad0d1b0, entry=entry@entry=-153342272, parameter0=parameter0@entry=-153340048, 
&nbsp;&nbsp;&nbsp;&nbsp;parameter1=parameter1@entry=-12052, parameter2=parameter2@entry=-12108, parameter3=parameter3@entry=0, fp_return=fp_return@entry=false, 
&nbsp;&nbsp;&nbsp;&nbsp;fp_args=fp_args@entry=false) at runtime/vm/simulator_arm.cc:3787
#­31 0x083799f4 in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=...) at runtime/vm/dart_entry.cc:115
#­32 0x0837b5f1 in dart::DartEntry::InvokeFunction (function=..., arguments=...) at runtime/vm/dart_entry.cc:27
#­33 0x082ae62f in dart::Dart_Invoke (target=0xad1c7ac, name=0xad1c7b0, number_of_arguments=0, arguments=0x0) at runtime/vm/dart_api_impl.cc:4107
#­34 0x081f45b5 in Dart_TestHelperArrayLengthMaxElements () at runtime/vm/object_test.cc:1991

---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---print  
#­35 dart::Dart_TestArrayLengthMaxElements () at runtime/vm/object_test.cc:1982
#­36 0x08066b71 in dart::TestCase::Run (this=0xace1728 &lt;dart::kRegisterArrayLengthMaxElements&gt;) at runtime/bin/run_vm_tests.cc:30
#­37 0x08066be0 in dart::TestCaseBase::RunTest (this=this@entry=0xace1728 &lt;dart::kRegisterArrayLengthMaxElements&gt;) at runtime/bin/run_vm_tests.cc:37
#­38 0x08281740 in dart::TestCaseBase::RunAll () at runtime/vm/unit_test.cc:47
#­39 0x080528d8 in Main (argv=0xffffd434, argc=5) at runtime/bin/run_vm_tests.cc:109
#­40 main (argc=5, argv=0xffffd434) at runtime/bin/run_vm_tests.cc:124

**Comment by kevmoo** [comment]
@kodandersson please update milestones here

**Comment by kodandersson** [comment]
Fixed in r45354.
