### ISSUE TITLE
Analyzer and dart2js don't handle call method return types correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#23252]
The following program produces no errors or warnings from both dart2js and the analyzer (version 1.10.0-dev.1.5):

class B {
&nbsp;&nbsp;int call(int x) =&gt; x;
}

void main() {
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;B f = new B();
&nbsp;&nbsp;&nbsp;&nbsp;f(3).helloThisIsntThere();
&nbsp;&nbsp;&nbsp;&nbsp;double x = f(3);
&nbsp;&nbsp;}
}

This suggests to me that the expression f(3) is being treated as having static type &quot;dynamic&quot; instead of &quot;int&quot;.

My reading of the spec (section 16.14.4) is that the return type of f(3) should be &quot;int&quot; here.  There is admittedly a bit of ambiguity in the wording of the second to last sentence of the section which leaves open the possible interpretation that the static type should be &quot;dynamic&quot;, but this seems very contrary to the spirit and letter of the rest of the section.  

Gilad, can you confirm whether or not this reading is correct?

**Comment by jmesserly** [comment]
Oh funny, I just ran into this :). https://dartpad.dartlang.org/84c7116f3d409223b4cf 
I have a CL that should fix, as a result of treating these a bit more uniformly. The reason it doesn't work here is that "f" is a VariableElement and that sends _computeStaticReturnType down a path that doesn't check for an InterfaceType with a "call" method.
