### ISSUE TITLE
Cannot debug dart app with exported main: Error setting breakpoint at 'main': Dart_OneTimeBreakAtEntry: could not find function 'main'

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23256]
Hit this with both Dart Editor and IntelliJ

Dart VM version: 1.9.3

**Comment by zoechi** [comment]
+1 
Just run into this as well.
Dart VM version: 1.11.0-edge.131803 (Thu Jun  4 05:58:53 2015) on "linux_x64"

**Comment by mhausner** [comment]
Given that there were no complaints in 1.5 years, I presume this is stale.
