### ISSUE TITLE
Please update documentation on native extensions

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#23289]
https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/

Native Extensions for the Standalone Dart VM
Written by William Hesse 
May 2012

This is a very helpful document, but needs to be updated.

**Comment by sethladd** [comment]
Here is the source for the article: https://github.com/dart-lang/www.dartlang.org/blob/master/src/site/articles/native-extensions-for-standalone-dart-vm/index.markdown

We'll gladly take pull requests.

If the article is misleading or gives guidance that is no longer applicable, we should take it down until it's updated.

How relevant or correct is the article?

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/sdk/issues/23024

**Comment by MikeMitterer** [comment]
@sgmitrovic I started yesterday with a cmake base sample - maybe it helps: https://github.com/MikeMitterer/cmake-dart-extension-master but be aware - it's in a very early stage!!!!

@sethladd Do you know it there are plans to to support native extension for "pub global"? It would be even cooler if there would be a support for automatic compilation! cmake based... any plans?

**Comment by sethladd** [comment]
> Do you know it there are plans to to support native extension for "pub global"?

That would be so great, but no one is working on it now. I don't know if the pub team would take those patches, but it doesn't hurt to ask!

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
