### ISSUE TITLE
coverage_test aborts when encountering null code

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#23290]
FAILED: none-vm-checked debug_ia32 service/coverage_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm\]:

stdout:
\*\* Launching out/DebugIA32/dart --compile-all --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --enable_asserts --enable_type_checks --package-root=out/DebugIA32/packages/ --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/dart/runtime/observatory/tests/service/coverage_test.dart --testee-mode
Observatory listening on http://127.0.0.1:60008
\*\* Signaled to run test queries on 60008

otherFunction &lt;
10000
positive
10000
positive
10000
positive
10000
positive
10000
positive
10000
positive
10000
positive
Running coverage_test.dart [1/2]
10000
positive
10000
positive
10000
positive
Setting breakpoint.
Breakpoint reached
Running coverage_test.dart [2/2]
runtime/vm/object.h:4225: error: expected: raw() != null()
\*\* Killing script

stderr:
Unhandled exception:
Uncaught Error: Testee exited with -6
Stack Trace:
#­0      \_TestLauncher.launch.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/dart/runtime/observatory/tests/service/test_helper.dart:73:11)
#­1      \_RootZone.runUnary (dart:async/zone.dart:1157)
#­2      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#­3      \_Future._propagateToListeners (dart:async/future_impl.dart:577)
#­4      \_Future._completeWithValue (dart:async/future_impl.dart:368)
#­5      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:422)
#­6      \_microtaskLoop (dart:async/schedule_microtask.dart:43)
#­7      \_microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#­8      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­9      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#­0      \_rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
#­1      \_microtaskLoop (dart:async/schedule_microtask.dart:43)
#­2      \_microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#­3      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­4      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm\]: DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --compile-all --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --enable_asserts --enable_type_checks --package-root=out/DebugIA32/packages/ /mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/dart/runtime/observatory/tests/service/coverage_test.dart
Took 0:00:34.832000

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 service/coverage_test

**Comment by turnidge** [comment]
coverage_test is no longer so brittle.  test re-enabled in 0230492433a0de2c1385380822de73e514ca52ab.
