### ISSUE TITLE
Analyzer doesn't constant evaluate initializers at field declaration site

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23292]
(Mostly filing this bug so that I can refer to it in status files.  I'm working on a fix)

Given a class definition like this:

class C {
&nbsp;&nbsp;final x = 1;
&nbsp;&nbsp;final y;
&nbsp;&nbsp;const C() : y = 2;
}
const test = const C();

When evaluating the constant &quot;test&quot;, the analyzer currently does constant evaluation correctly for the field C.y, but ignores the initializer &quot;= 1&quot; for the field C.x.  Most of the time this is benign, however it causes analyzer to miss checked-mode errors.  For example, in the following code:

class C&lt;T&gt; {
&nbsp;&nbsp;final T x = y;
&nbsp;&nbsp;const C();
}
const y = 1;
const test = const C&lt;String&gt;();

There should be a checked-mode compile time error when attempting to evaluate the const &quot;const C&lt;String&gt;()&quot;, since supplying String for the type argument T is incompatible with the actual type of the constant C.x.

**Comment by bwilkerson** [comment]
The error is now being generated, so I believe this was fixed.
