### ISSUE TITLE
 Process.runSync cuts off stdout after null byte on Windows

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23295]
On Windows, if a process run via Process.runSync emits a null byte on stdout, all output following that null byte is omitted from the ProcessResult object. For example:

&nbsp;&nbsp;&nbsp;&nbsp;// inner.dart
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:io';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;before\x00after&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;// outer.dart
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:io';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var result = Process.runSync(Platform.executable, [&quot;inner.dart&quot;]);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(result.stdout);
&nbsp;&nbsp;&nbsp;&nbsp;}

When outer.dart is run on Windows, it incorrectly prints &quot;before&quot;.

**Comment by sgjesse** [comment]
Proposed change https://codereview.chromium.org/1194883002

**Comment by sgjesse** [comment]
Fixed in 0415d9271d50ffd61e5243c391a02678f271bce1.
