### ISSUE TITLE
The AnalysisError type in the Analysis Server spec needs to be updated

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#23291]
The AnalysisError type in the Analysis Server spec needs to be updated

http://htmlpreview.github.io/?https://github.com/dart-lang/bleeding_edge/blob/master/dart/pkg/analysis_server/doc/api.html#type_AnalysisError

Missing information:
- Severity information within the Warning (or other buckets) severity
- Flag or bit indicating type of issues (across severity) such as
  &nbsp;&nbsp;\- &quot;deprecated&quot;
  &nbsp;&nbsp;\- &quot;unused&quot;

**Comment by bwilkerson** [comment]
I'm guessing that this is no longer interesting. Please re-open it if I'm wrong.
