### ISSUE TITLE
Incorrect handling of invalid field initializer

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#23298]
In tests/co19/src/Language/12_Expressions/10_This_A03_t04.dart there is:

class C {
&nbsp;&nbsp;var x = this;
}

main() {
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;print(new C().x);
&nbsp;&nbsp;} catch(e) {}
}

The occurrence of this in class C should be an error.  The CPS translation tries to build a generative constructor for class C and eventually hits a path where the value of the field C.x is null and hits an assertion about the class c:

assert(Elements.isNativeOrExtendsNative(c));

but this assertion fails.

**Comment by rakudrama** [comment]
Obsolete
