### ISSUE TITLE
Need area Pkg-Reflectable or similar.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#23300]
In order to be able to receive reports about issues in the package Reflectable, it would be useful to have an entry in the 'New issue' menu (for instance, Area-Analyzer ... Pkg-PolymerExpressions [here, add: Pkg-Reflectable] Pkg-ScheduledTest ...).

I'm not sure which area to use for this issue, because none of the areas seem to be concerned with this issue tracker itself.

**Comment by mit-mit** [comment]
Added.
