### ISSUE TITLE
dart2js should recognize unmodifiable lists.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23309]
I've added an unmodifiable list constructor.
It creates lists that are unmodifiable - equivalent to const lists, except that the elements don't need to be const.
Dart2js should recognize these as being fixed length lists.

The results of creating such an arrau is currently only typed as being JSArray. 
I dared not use JSFixedArray because I'm not sure that wouldn't make dart2js think it's modifiable and skip checking for modifiability before storing to it (i.e., JSFixedArray looks like a specific type with a different behavior).

What is the type of a const list?

**Comment by rakudrama** [comment]
Done.
