### ISSUE TITLE
ARMv5TE and ARMv6 use long sequences for loading immediates

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#23306]
Unlike ARMv7, ARMv5TE and ARMv6 lack the movw and movt instructions. Large immediates must therefore be loaded one byte at a time in a four-byte sequence. Using the object pool for large immediate loads would reduce code size and could potentially also improve performance on low-end devices.

**Comment by crelier** [comment]
I came back to this issue and I got it working without passing an extra argument controlling constant pool usage.
Lots of asserts should make it reliable. I'll send a cl for review soon.
