### ISSUE TITLE
split is not a function error in Dart2JS compile of SVG toggle class 

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23358]
Please see https://dartpad.dartlang.org/32cb7c6597aafef14601

Toggling the class property is resulting in Uncaught TypeError: J.get$className$x(...).split is not a function

This doesn't occur in a Dartium run, and doesn't occur with toggling background on a Div only on SVG.

I'm not sure if this is an issue with Dart2JS or with the libraries, please reassign as appropriate.

Tested against SDK 1.9.3.

**Comment by rakudrama** [comment]
The dartpad snippet is working correctly so I'm assuming my fix is still good.
