### ISSUE TITLE
CPU profile is empty when running VM from Process spawned by VM

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23359]
Consider this code:

import 'dart:io';
import 'dart:async';

main() async {
&nbsp;&nbsp;Process.run('dart',
&nbsp;&nbsp;&nbsp;&nbsp;['--pause-isolates-on-exit', '--enable-vm-service=7334',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'--profile', 'loop.dart']);
&nbsp;&nbsp;await new Future.delayed(const Duration(seconds: 1));
&nbsp;&nbsp;Process.run('open', ['http://localhost:7334']);
}

When I run the above code, and open observatory, I do not see CPU profile data.

When I run via the command-line:

dart --pause-isolates-on-exit --enable-vm-service=7334 --profile loop.dart

and open the observatory, I see the profile data.

I've attached the two scripts to this issue.

I am using Dart 1.10 on my Mac.

---

**Attachments:**
[main.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-23359/comment-0/main.dart) (279 Bytes)
[loop.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-23359/comment-0/loop.dart) (108 Bytes)

**Comment by johnmccutchan** [comment]
Note, on Linux this now works. Mac still fails.

**Comment by bkonyi** [comment]
This should be resolved by https://dart-review.googlesource.com/c/sdk/+/127451/4 for all POSIX platforms.
