### ISSUE TITLE
Analyzer fails to give error for implicitly disallowed enum names

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23353]
According to section 13 (&quot;Enums&quot;) of the Dart language spec:

&quot;&quot;&quot;The declaration of an enum of the form metadata enum E { id0, . . . idn−1}; has the same effect as a class declaration

metadata class E {
&nbsp;&nbsp;final int index;
&nbsp;&nbsp;const E(this.index);
&nbsp;&nbsp;static const E id0 = const E(0);
&nbsp;&nbsp;. . .
&nbsp;&nbsp;static const E idn−1 = const E(n - 1);
&nbsp;&nbsp;static const List&lt;E&gt; values = const &lt;E&gt;[id0 . . . idn−1];
&nbsp;&nbsp;String toString() =&gt; { 0: ‘E.id0’, . . ., n-1: ‘E.idn−1’}[index];
}&quot;&quot;&quot;

Therefore, if an enumerated value is called &quot;values&quot;, &quot;toString&quot;, &quot;noSuchMethod&quot;, &quot;hashCode&quot;, or &quot;runtimeType&quot;, or matches the enum name, this should result in a compile-time error.

Analyzer doesn't report a compile-time error in any of these circumstances.

The VM and Dart2js report the expected errors.

**Comment by srawlins** [comment]
This is still an issue for analyzer. It will complain about the `values` value, but not the others given.

**Comment by srawlins** [comment]
@scheglov fixed the "matches the enum name" part in https://github.com/dart-lang/sdk/commit/3d19be30b5c6783c6d5b6520a0aac750f33b3819.
