### ISSUE TITLE
VM: Implementing the package spec proposal

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23369]
Tracking issue for implementing the package spec proposal.

Main issue: https://github.com/dart-lang/dart_enhancement_proposals/issues/5

Proposal: https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md

**Comment by nex3** [comment]
Milestone 1.11 is in merge mode now. How is this progressing?

**Comment by nex3** [comment]
Just to make sure: there will also be a `--package-spec` flag that allows the user to pass in a user-specified package location, right? This is important for pub.

**Comment by sethladd** [comment]
The DEP specified `--package-spec` so I would expect that it will be supported. Thanks for raising this.

Curious, how/why would pub use it?

**Comment by nex3** [comment]
The same way pub uses the `--package-root` flag now: to [compile snapshots from transformed code](https://github.com/dart-lang/pub/blob/master/lib/src/dart.dart#L192), [to executables in dependencies or globally-activated packages](https://github.com/dart-lang/pub/blob/master/lib/src/executable.dart#L118), and [to run pub itself for testing](https://github.com/dart-lang/pub/blob/master/test/test_pub.dart#L526).

**Comment by sethladd** [comment]
PR just landed https://github.com/dart-lang/sdk/commit/b07a9ddbcac8425a4468014a694a81f403e1798d

**Comment by iposva-google** [comment]
Fixed with https://codereview.chromium.org//1232593003
and https://codereview.chromium.org//1269643002

**Comment by sethladd** [comment]
Thanks @iposva-google , very cool!

**Comment by nex3** [comment]
Three questions:

* Does this support support passing a packages file into `Isolate.spawnUri`? If not, should we open a new sub-issue of #23372 for that?

* b07a9ddbcac8425a4468014a694a81f403e1798d mentions that it doesn't yet support `.packages` files for HTTP imports. Is that in yet? If not, should we wait to close this issue until it is?

* Where do the tests for this feature live?

**Comment by sethladd** [comment]
> Does this support support passing a packages file into Isolate.spawnUri? If not, should we open a new sub-issue of #23372 for that?

I just checked the bleeding_edge docs for Isolate.spawnUri, and it looks like there isn't a named parameter for packages file. Thanks for the catch. I can open a new sub-issue for that. (cc @lrhn )
