### ISSUE TITLE
dart2js: Implementing the package spec proposal

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23371]
Tracking issue for implementing the package spec proposal.

Main issue: https://github.com/dart-lang/dart_enhancement_proposals/issues/5

Proposal: https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md

**Comment by hterkelsen** [comment]
Fixed with 63681d5b59a26d00233ee582e8f9b9fa63c0bd80
