### ISSUE TITLE
Analyzer: implementing package spec proposal (.packages)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23373]
Tracking issue for implementing the package spec proposal.

Main issue: https://github.com/dart-lang/dart_enhancement_proposals/issues/5

Proposal: https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md

**Comment by sethladd** [comment]
So, the dartanalyzer works if you pass `--packages path/to/.packages`.

Next up: automatically find .packages

cc @pq

**Comment by sethladd** [comment]
Just tested a dartanalyzer from 1.12-dev.5.2

Auto-discovery worked!
I also renamed pubspec.lock and pubspec.yaml and auto-discovery still worked!
Passing in --packages to dartanalyzer worked!

What remains for this task?

cc @stereotype441 @bwilkerson

**Comment by sethladd** [comment]
Result from discussion:

* @stereotype441 will work to land a patch that makes sdk_ext + .packages work
* @sethladd and @devoncarew will turn on appveyor for analyzer_cli

cc @danrubel

**Comment by sethladd** [comment]
Howdy!

@stereotype441 and @pq how do we look here? Are you comfortable with the auto-discovery logic here?

**Comment by pq** [comment]
:+1: I think we're good to go for this cut.

As discussed we have some integration tests to back-fill but that's a larger issue.
