### ISSUE TITLE
No hint issued when an attempt is made to call an uncallable type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23384]
(Originally reported by Danny Tuppeny at https://groups.google.com/a/dartlang.org/forum/#!topic/misc/Xzieh_tQR94 and https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/kohgt1hgB_s)

The following code generates a warning (as expected) since String doesn't have a call method:

void main() {
&nbsp;&nbsp;String name = &quot;Danny&quot;;
&nbsp;&nbsp;print(name());
}

If the static type of the variable is changed to &quot;dynamic&quot;, i.e.:

void main() {
&nbsp;&nbsp;var name = &quot;Danny&quot;;
&nbsp;&nbsp;print(name());
}

then the analyzer should issue an equivalent hint, since the propagated type logic is still able to infer that the type of name is String.  But no hint is issued.

**Comment by srawlins** [comment]
For the given example, analyzer now issues a warning:

> 'name' isn't a function.
