### ISSUE TITLE
Analyzer incorrectly resolves super calls to interfaces.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23380]
The following code produces warnings in Dart2js but no warnings in analyzer:

abstract class Interface {
&nbsp;&nbsp;f();
&nbsp;&nbsp;get x;
&nbsp;&nbsp;void set y(value);
}

class Implementation implements Interface {
&nbsp;&nbsp;f() {
&nbsp;&nbsp;&nbsp;&nbsp;super.f(); // Warning expected
&nbsp;&nbsp;}
&nbsp;&nbsp;get x =&gt; super.x; // Warning expected
&nbsp;&nbsp;void set y(value) {
&nbsp;&nbsp;&nbsp;&nbsp;super.y = value; // Warning expected
&nbsp;&nbsp;}
}

main() {
&nbsp;&nbsp;new Implementation().f();
&nbsp;&nbsp;new Implementation().x;
&nbsp;&nbsp;new Implementation().y = 1;
}

I believe the dart2js behavior is correct--there should be warnings because the superclass of &quot;Implementation&quot; is &quot;Object&quot;, and &quot;Object&quot; doesn't have members &quot;f&quot;, &quot;x&quot;, or &quot;y&quot;.  It appears that the analyzer is incorrectly resolving the super calls to the interface class.

**Comment by natebosch** [comment]
I now get warnings like "The setter 'y' is always abstract in the supertype [abstract_super_member_reference]"
