### ISSUE TITLE
"for" in an async context differs from Future.forEach

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23394]
Currently if &quot;for&quot; is used with an async call, it produces many nested recursive calls from the perspective of Zones. This is especially problematic when using Chain tracking from the stack_trace package, since it can cause out-of-memory errors if the iteration goes on too long.

For example:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:async';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:stack_trace/stack_trace.dart';

&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chain.capture(() async {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (var i in [0, 1, 2, 3, 4, 5, 6]) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await new Future.value();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'oh no!';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, onError: (error, chain) =&gt; print(chain.terse));
&nbsp;&nbsp;&nbsp;&nbsp;}

which produces the output

&nbsp;&nbsp;&nbsp;&nbsp;test.dart 9:5  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async      \_Completer.completeError
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 10:4  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate    \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 7:7  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async                                Future.Future.microtask
&nbsp;&nbsp;&nbsp;&nbsp;test.dart                                 main.&lt;fn&gt;
&nbsp;&nbsp;&nbsp;&nbsp;package:stack_trace/src/chain.dart 78:12  Chain.capture
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 5:9                             main
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate                              \_RawReceivePortImpl._handleMessage

Compare this to an implementation that uses Future.forEach, which avoids creating recursive scopes:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:async';
&nbsp;&nbsp;&nbsp;&nbsp;import 'package:stack_trace/stack_trace.dart';

&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chain.capture(() async {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await Future.forEach([0, 1, 2, 3, 4, 5, 6], (i) async {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await new Future.value();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'oh no!';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, onError: (error, chain) =&gt; print(chain.terse));
&nbsp;&nbsp;&nbsp;&nbsp;}

which produces the output:

&nbsp;&nbsp;&nbsp;&nbsp;test.dart 9:5  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async      \_Completer.completeError
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 10:4  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate    \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async     \_Future.then
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 6:5  main.&lt;fn&gt;.&lt;async&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate   \_RawReceivePortImpl._handleMessage
&nbsp;&nbsp;&nbsp;&nbsp;&equals;&equals;&equals;== asynchronous gap &equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;dart:async                                Future.Future.microtask
&nbsp;&nbsp;&nbsp;&nbsp;test.dart                                 main.&lt;fn&gt;
&nbsp;&nbsp;&nbsp;&nbsp;package:stack_trace/src/chain.dart 78:12  Chain.capture
&nbsp;&nbsp;&nbsp;&nbsp;test.dart 5:9                             main
&nbsp;&nbsp;&nbsp;&nbsp;dart:isolate                              \_RawReceivePortImpl._handleMessage

**Comment by kevmoo** [comment]
Re-opening. This is assigned to language. If we agree the VM is doing the "right thing" per spec, we should discuss changing the spec. The current behavior is untenable.

**Comment by mhausner** [comment]
Twitchy fingers. Although I do think this needs to remain closed.

**Comment by lrhn** [comment]
The specification isn't specific about how you continue after an await. You wait for the future to complete, then the await-expression evaluates to the result (or throws on an error). That can be implemented in any number of ways.

For the sake of the user, the code after the await and the code before the await should at least appear to be running in the same scope. The way it's currently implemented, all the code after the await runs in the scope of the future's `then` handler, not in the scope of the call of `then` (like the non-await code above does). It is implemented as if it was written:

I think we should try to reduce the artificial scope nesting, not just for the stack-trace package.

**Comment by kmillikin** [comment]
The spec does have this (in the try/finally section):

> The active stack trace is an object whose toString() method produces a string
> that is a record of exactly those function activations within the current isolate
> that had not completed execution at the point where the current exception
> (16.9) was thrown.

> This implies that no synthetic function activations may be added to the trace,
> nor may any source level activations be omitted. This means, for example, that
> any inlining of functions done as an optimization must not be visible in the trace.
> Similarly, any synthetic routines used by the implementation must not appear in the
> trace.

which has always made it seem to me that the intent is for the code after the await to appear as if it ran in the same scope as the code before.

**Comment by lrhn** [comment]
I agree that the section on stack traces show a good intent, but not clear what it means for async calls.

Has an async function "completed execution" when it returns the `Future` (before executing any of its body) or when it completes the body? If the latter, you can have an async function that completes *after* the function that called, which gives interesting stack traces. 

When we await a future, the following code will be triggered by the future's completion, and will likely be run with an initial stack trace containing the microtask queue and a future result propagation function. Those are not synthetic. The "body" trampoline function of an async function is probably synthetic - it doesn't occur in the source - so we should hide it in stack traces if possible.

Also, the problem isn't so much with the single stack trace as with each new await-callback getting its callback registered anew, causing long chains of async stacks in the stacktrace package.

**Comment by floitschG** [comment]
Unless I have to revert the commit, this should be fixed with 4dae43d63727.

**Comment by kevmoo** [comment]
Reverted in cb4f9fc

**Comment by floitschG** [comment]
Fixed in debf1d6f7c2f97831cda1f6fa18093f76ed0545c if it sticks.
