### ISSUE TITLE
Incorrect error location for uninitialized static consts

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23403]
Enter the following code in the editor:

class C {
&nbsp;&nbsp;C();
&nbsp;&nbsp;static const int i;
}

Expected result: the error message &quot;The const variable 'i' must be initialized&quot; should appear at the site of the declaration of &quot;i&quot;.

Observed result: the correct error message occurs, but it appears at the site of the declaration of the constructor, which makes no sense.

If the constructor is commented out, the error message jumps to the expected location.

I suspect that what's happening is that we're re-using the logic for determining where to report uninitialized final fields (they should be reported at the constructor site(s) if there are explicit constructors, and at the field site if there are no explicit constructors).  But this logic doesn't make sense for static consts.

Note that if &quot;i&quot; is changed to &quot;final&quot; rather than &quot;static const&quot;, then the error changes to a warning (&quot;The final variable 'i' must be initialized&quot;), and the behavior would make sense, since final variables are typically initialized I suspect that we are erroneously re-using the logic

**Comment by srawlins** [comment]
The analyzer now only reports the correct error.
