### ISSUE TITLE
VM fails to use deferred redirecting factories after libary is loaded.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#23408]
main.dart:
&nbsp;import 'lib.dart' deferred as lib;

&nbsp;class C {
&nbsp;&nbsp;&nbsp;C();
&nbsp;&nbsp;&nbsp;factory C.c() = lib.C;
&nbsp;}

&nbsp;void main() {
&nbsp;&nbsp;&nbsp;lib.loadLibrary().then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(new C.c());
&nbsp;&nbsp;&nbsp;});
&nbsp;}

lib.dart:
&nbsp;import &quot;main.dart&quot; as main;

&nbsp;class C extends main.C {
&nbsp;&nbsp;&nbsp;C();
&nbsp;}

In my understanding this program should run without error (because lib is loaded when the constructor is invoked). On the VM it fails with:

dart main.dart
Unhandled exception:
Uncaught Error: 'file:///usr/local/google/home/sigurdm/test/main.dart': malformed type: line 5 pos 19: deferred type 'lib.C' is not yet loaded
&nbsp;&nbsp;factory C.c() = lib.C;

**Comment by mhausner** [comment]
https://codereview.chromium.org/1219023002/

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
ce917c5160dbefc71091f0b172c0a589e6cb2763 (presubmit successful).
