### ISSUE TITLE
Allow dart2js to compile programs where deferred imports are not available.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23414]
When the VM runs a program with a missing deferred import, the program doesn't fail until the import is loaded using loadLibrary.

If trying the same thing in dart2js, compilation fails immediately.

I would prefer if dart2js compiles such a program anyway, to a resulting JS code that fails unconditionally when the library is loaded. 
There should probably be a warning, but maybe also some way to avoid it when you know what you are doing.

This would allow a generic library to try to import, fx, &quot;dart:io&quot;, and only use it if it is actually there.
Currently a library can't use &quot;dart:io&quot; at all if it wants to be compiled using dart2js, even if it has a fallback for when the library isn't available.

**Comment by matanlurey** [comment]
I imagine that @sigmundch and team don't consider this important anymore.
