### ISSUE TITLE
Vm `await for` stops if stream was canceled.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#23445]
The following program should continue indefinitely, but only print 4 lines

&equals;&equals;&equals;
import 'dart:async';

process(period) async* {
&nbsp;&nbsp;var counter = 0;
&nbsp;&nbsp;await for (var tick in new Stream.periodic(period)) {
&nbsp;&nbsp;&nbsp;&nbsp;counter++;
&nbsp;&nbsp;&nbsp;&nbsp;print('counter = ${counter}');
&nbsp;&nbsp;}
}

void main() {
&nbsp;&nbsp;final s = process(const Duration(seconds: 1)).listen((val) { });
&nbsp;&nbsp;
&nbsp;&nbsp;new Timer(const Duration(seconds: 5), () {
&nbsp;&nbsp;&nbsp;&nbsp;s.cancel();
&nbsp;&nbsp;});
}

See discussion in Issue #23435.

**Comment by natebosch** [comment]
In the latest Dart this is printing ticks indefinitely.
