### ISSUE TITLE
Exception thrown when file is missing. Can we change to just message?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23440]
Please see the attached repro.

May we suggest that we &quot;tone down&quot; the exception here, as it's not an error in the analyzer, but instead is an error with a missing file. It's more of a &quot;user error&quot;. Instead, we'd like to see a simple message like &quot;Could not resolve package:missing&quot;

Here is the code:

import &quot;package:missing/stuff.dart&quot;;

main() {
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Hi!&quot;);
}

Here is the wrapper script:

dartanalyzer ./main.dart --no-hints --url-mapping=dart:mojo.io,/media/jimbe/mojossd/modular/src/third_party/mojo/src/mojo/public/dart/io.dart --package-root=. --fatal-warnings

Here's the (scary) error:

sethladd@sethladd-macbookair ~/Downloads/canonical-error $ ./fail.sh 
Analyzing [./main.dart]...
Canonical failed: ./missing
JavaIOException: IOException FileSystemException: Cannot resolve symbolic links, path = './missing' (OS Error: No such file or directory, errno = 2)
#­0      JavaFile.getCanonicalPath (package:analyzer/src/generated/java_io.dart:48)
#­1      JavaFile.getCanonicalFile (package:analyzer/src/generated/java_io.dart:43)
#­2      PackageUriResolver.getCanonicalFile (package:analyzer/src/generated/source_io.dart:390)
#­3      PackageUriResolver.resolveAbsolute (package:analyzer/src/generated/source_io.dart:444)
#­4      SourceFactory._internalResolveUri (package:analyzer/src/generated/source.dart:755)
#­5      SourceFactory.resolveUri (package:analyzer/src/generated/source.dart:706)
#­6      ParseDartTask.resolveDirective (package:analyzer/src/generated/engine.dart:9427)
#­7      ParseDartTask.internalPerform.&lt;anonymous closure&gt; (package:analyzer/src/generated/engine.dart:9370)
#­8      \_PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150)
#­9      ParseDartTask.internalPerform (package:analyzer/src/generated/engine.dart:9355)
#­10     AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6378)
#­11     AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6351)
#­12     AnalysisContextImpl._cacheDartParseData (package:analyzer/src/generated/engine.dart:2748)
#­13     AnalysisContextImpl._getDartParseData (package:analyzer/src/generated/engine.dart:3341)
#­14     AnalysisContextImpl.computeKindOf (package:analyzer/src/generated/engine.dart:1663)
#­15     AnalyzerImpl._analyzeSync (package:analyzer/src/analyzer_impl.dart:323)
#­16     AnalyzerImpl.analyzeSync (package:analyzer/src/analyzer_impl.dart:153)
#­17     \_runAnalyzer (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:83)
#­18     \_analyzeAll (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:56)
#­19     main (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:31)
#­20     \_startIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:253)
#­21     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)

Expected: a more user-friendly error, informing the user that package:missing could not be found

Actual: a big scary stack track :)
______
**Attachment:**
[canonical-error.tar](https://storage.googleapis.com/google-code-attachments/dart/issue-23440/comment-0/canonical-error.tar) (10 KB)

**Comment by pq** [comment]
The error is a bit better now.
```
[~/src] $ dartanalyzer main.dart
Analyzing [src/bin/main.dart]...
[error] Target of URI does not exist: 'package:missing/stuff.dart' (/Users/me/src/bin/main.dart, line 2, col 8)
```
Good enough @sethladd?

**Comment by sethladd** [comment]
Yeah! Thanks @pq :)

**Comment by pq** [comment]
Awesome.  That's how the error looks today. :)

Closing out!
