### ISSUE TITLE
Analyzer: implementing null-aware operators

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23456]
Tracking issue for null-aware operators.

Proposal: https://github.com/gbracha/nullAwareOperators/blob/master/proposal.md

**Comment by sethladd** [comment]
What work remains here? Looks like dart2js and VM have completed their work on this.

**Comment by stereotype441** [comment]
The only issue that remains is #23464, which I've been delaying waiting for an email discussion with Gilad to conclude.  I will ping him.

Issue #23464 is just an issue with the presentation of the warning message; the analyzer is generating static warnings in all the correct circumstances.  So I think we can consider the analyzer implementation of null-aware operators to be feature complete.  I will close this bug and leave #23464 open.
