### ISSUE TITLE
Sanitization throws on embed elements in Firefox

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#23466]
An embed element in Firefox is not an object, the typeof says Function. As a result we don't get an interceptor for it and it doesn't have methods. We probably need to drop down into JS to see if it's a reasonable element or not. We may be able to just outright reject &lt;embed&gt;.  See, e.g. co19/LayoutTests/fast/loader/loadInProgress_t01

**Comment by vsmenon** [comment]
Closing as obsolete as I don't think anyone's hit this in years.
