### ISSUE TITLE
dart2js: Spurious printed warning during formatting of NoSuchMethodException

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#23465]
The following program prints spurious lines about reflective use.
If it is necessary to have this warning, it should be suppressed for the purpose of generating NoSuchMethodError strings.

-------- unminified:
Warning: 'mumble' is used reflectively but not in MirrorsUsed. This will break minified code.
NoSuchMethodError: method not found: 'mumble'
Receiver: Instance of 'CCC'
Arguments: [1]

-------- minified:
Warning: 'To' is used reflectively but not in MirrorsUsed. This will break minified code.
NoSuchMethodError: method not found: 'To'
Receiver: Instance of 'U'
Arguments: [1]

-------- code:
class N {
&nbsp;&nbsp;noSuchMethod(i) =&gt; 42;
}
class CCC {
}
main() {
&nbsp;&nbsp;var a = (new DateTime.now().millisecondsSinceEpoch &gt; 2) ? new CCC() : new N();
&nbsp;&nbsp;var e;
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;e = a.mumble(1);
&nbsp;&nbsp;} catch (ex) {
&nbsp;&nbsp;&nbsp;&nbsp;e = ex;
&nbsp;&nbsp;}
&nbsp;&nbsp;print(e);
}

**Comment by matanlurey** [comment]
This is no longer an issue in Dart2.
