### ISSUE TITLE
Compiler crash on damaged code

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23470]
test.dart:

void main() 
{
&nbsp;&nbsp;&nbsp;double a'a$a.0
}

&equals;&equals;&equals; Response to compilation &equals;&equals;&equals;

test.dart:3:4:
Error: Expected ';' after this.
&nbsp;&nbsp;&nbsp;double a'a$a.0
&nbsp;&nbsp;&nbsp;^^^^^^
test.dart:1:6:
Internal Error: The compiler crashed when compiling this element.
void main() 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

\* the name and version of your operating system,

\* the Dart SDK build number (1.10.0), and

\* the entire message you see here (including the full stack trace
&nbsp;&nbsp;below as well as the source location above).

The compiler crashed: Class 'Send' has no instance getter 'token'.

NoSuchMethodError: method not found: 'token'
Receiver: Instance of 'Send'
Arguments: []
# ­0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
# ­1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
# ­2      ElementListener.endLiteralString (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/listener.dart:1406)
# ­3      Parser.parseSingleLiteralString (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:2215)
# ­4      Parser.parseLiteralString (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:2155)
# ­5      Parser.parsePrimary (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1930)
# ­6      Parser.parseUnaryExpression (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1895)
# ­7      Parser.parsePrecedenceExpression (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1775)
# ­8      Parser.parseExpression (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1751)
# ­9      Parser.parseExpressionStatement (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1743)
# ­10     Parser.parseStatement (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1597)
# ­11     Parser.parseFunctionBody (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1509)
# ­12     Parser.parseFunction (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/parser.dart:1407)
# ­13     FunctionElementX&amp;PartialElement&amp;PartialFunctionMixin.parseNode.parseFunction (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/listener.dart:2323)
# ­14     parse (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/listener.dart:2519)
# ­15     FunctionElementX&amp;PartialElement&amp;PartialFunctionMixin.parseNode (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/scanner/listener.dart:2326)
# ­16     ResolverTask.resolveSignature.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/resolution/members.dart:1304)
# ­17     CompilerTask.measure (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:2137)
# ­18     ResolverTask.resolveSignature.&lt;anonymous closure&gt; (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/resolution/members.dart:1304)
# ­19     Compiler.withCurrentElement (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:874)
# ­20     ResolverTask.resolveSignature (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/resolution/members.dart:1302)
# ­21     BaseFunctionElementX.computeSignature.&lt;anonymous closure&gt; (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/elements/modelx.dart:1817)
# ­22     Compiler.withCurrentElement (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:874)
# ­23     BaseFunctionElementX.computeSignature (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/elements/modelx.dart:1816)
# ­24     Compiler.computeMain (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:1507)
# ­25     Compiler.compileLoadedLibraries (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:1539)
# ­26     Compiler.runCompiler.&lt;anonymous closure&gt; (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/compiler/lib/src/compiler.dart:1465)
# ­27     _RootZone.runUnary (dart:async/zone.dart:1155)
# ­28     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
# ­29     _Future._propagateToListeners (dart:async/future_impl.dart:577)
# ­30     _Future._completeWithValue (dart:async/future_impl.dart:368)
# ­31     _Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:422)
# ­32     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
# ­33     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
# ­34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
# ­35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by sigmundch** [comment]
handled now by the CFE

**Comment by askeksa-google** [comment]
No longer crashes.
