### ISSUE TITLE
RTCPeerConnection-AddRemoveStream_t01 fails, probably due to obsolete prefixing

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#23475]
At least the log gives a warning of 
tests/co19/src/LayoutTests/fast/mediastream/RTCPeerConnection-AddRemoveStream_t01.dart:64:14:
Warning: Cannot resolve 'webkitRTCPeerConnection'.
&nbsp;&nbsp;&nbsp;&nbsp;pc = new webkitRTCPeerConnection(null, null);

**Comment by athomas** [comment]
LayoutTests have been deleted.
