### ISSUE TITLE
Support thread destructors on Windows

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23474]
Unlike pthread_key_create, TLSAlloc doesn't support a destructor, so use tricks from:
https://src.chromium.org/svn/trunk/src/base/threading/thread_local_storage_win.cc

**Comment by kodandersson** [comment]
This can be seen as yet another aspect of not leaking at shutdown:
https://github.com/dart-lang/sdk/issues/24467

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1391013006

**Comment by johnmccutchan** [comment]
NOTE: The list of thread destructors run on Windows is statically expressed in OnThreadExit - os_thread_win.cc.

**Comment by johnmccutchan** [comment]
Cleanup bug #24591
