### ISSUE TITLE
Poor parser error recovery after incomplete switch statement

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23473]
The following code:

```
class C {
  f(x) {
    switch (x)
    print(x); // EXPECTED ERROR
  }
  void g() {}
}
main() {
  new C().g();
} // UNEXPECTED ERROR
```

produces a compile error (as expected) on the line marked &quot;EXPECTED ERROR&quot;, because the switch statement is not followed by a &quot;{&quot;.

However, there is also an unexpected error on the line marked &quot;UNEXPECTED ERROR&quot;: &quot;Expected to find '}'&quot;.

It appears that the parser is inserting a synthetic opening brace after the &quot;switch (x)&quot;, and that is causing the rest of the file to be parsed at the wrong nesting level.

The user-visible manifestation of this bug is that when the user attempts to add a switch statement to the middle of a file, they see a potentially large number of spurious errors which appear just after typing &quot;switch&quot; and don't disappear until the brace pair &quot;{}&quot; is inserted.

A less user-visible effect (but a scarier one IMHO, because it may hide some nasty corner cases) is that after the incomplete switch statement, the scanner and the parser disagree about the level of indentation.  This could break some parser invariants (for example by causing the parser to see tokens associated with string interpolations in places where it doesn't believe it's inside a string).

Screenshot attached to illustrate the magnitude of follow-on errors caused by this bug.  The file in question was error and warning free before I inserted the text &quot;switch (field.type)&quot;.

---

**Attachment:**
[Screen Shot 2015-05-15 at 6.44.05 AM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-23473/comment-0/Screen Shot 2015-05-15 at 6.44.05 AM.png) (211.33 KB)

**Comment by srawlins** [comment]
The example now generates exactly one error:

```dart
$ dart 23473.dart 
23473.dart:3:14: Error: A switch statement must have a body, even if it is empty.
Try adding an empty body.
    switch (x)
             ^
```
