### ISSUE TITLE
VM: Forwarding constructor called using super() evaluates arguments twice.

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#23488]
var string = '';

append(x) {
&nbsp;&nbsp;string += x;
&nbsp;&nbsp;return x;
}

class A {
&nbsp;&nbsp;var x = append('x');
&nbsp;&nbsp;var y;
&nbsp;&nbsp;var z;

&nbsp;&nbsp;A() : this.foo(append('y'));

&nbsp;&nbsp;A.foo(this.y) : z = append('z');
}

class B extends A {
&nbsp;&nbsp;var w;

&nbsp;&nbsp;B() : super(), w = append('w');
}

main() {
&nbsp;&nbsp;new B();
&nbsp;&nbsp;print(string);
}

EXPECTED:

yxzw

ACTUAL:

yxzwy

**Comment by lrhn** [comment]
The VM now prints `wyxz`. 
The initial `w` is consistent with always doing the super-call last in an initializer list, which I believe is a deliberate choice (even if it doesn't follow the spec).

Still, the `x` instance members should be initialized before the initializer lists, so the correct answer is `xyzw`, and with super-call-last semantics the answer should still be `wxyz`.

**Comment by mhausner** [comment]
Implementing the oder ```xyzw``` or ```wxyz``` would require that there are two versions of the A.foo() constructor: one that initializes x (when called directly), another one that does not (when it is invoked from another constructor).

**Comment by asgerf** [comment]
I think `yxz` is the correct ordering. The spec says the *only* action of a redirecting constructor is to invoke another generative constructor, and last I checked, both vm and dart2js implement it this way.

I'm closing the issue since the bug it originally addressed has clearly been fixed.

**Comment by lrhn** [comment]
The correct ordering is `xyz` as I read the specification. 

Fields are initialized when the object is created by the `new` expression, *before* calling the constructor. They are not initialized as part of calling the constructor, so  it doesn't matter that it's a forwarding constructor.

From the spec:

> Evaluation of e proceeds as follows:
> First, the argument list `(a1, . . . , an, xn+1 : an+1, . . . , xn+k : an+k)` is evaluated.
...
> Otherwise, if q is a generative constructor (10.6.1), then:
> A fresh instance (10.6.1), *i*, of class *R* is allocated. For each instance variable *f* of *i*, if the variable declaration of *f* has an initializer expression *ef* , then *ef* is evaluated, with the type parameters (if any) of *R* bound to the actual type arguments *V1, . . . , Vl*, to an object of and *f* is bound to of . Otherwise *f* is bound to null.
...
> Next, *q* is executed with this bound to i, the type parameters (if any) of *R* bound to the actual type arguments *V1, . . . , Vl* and the formal parameter bindings that resulted from the evaluation of the argument list. The result of the evaluation of *e* is *i*.

(where *e* is the `new C.x<V1..Vl>(a1... xn+k, an+k)` expression and *q* is the constructor it refers to).

Here the *fields of i* are initialized before the constructor is called. It doesn't say it's only the fields declared by the top-mosty type in the class, it should also include inherited fields.
That is: Field initialization is not part of the constructor call, it's handled before the constructor invocation. Inherited superclass fields are initialized before the *first* constructor is called.

 (Now, this might be a mistake, and it *is* slightly suspicious that it says that the field initializers are all evaluated in the constructor's scope, which might not be correct for inherited fields, but the inherited fields are not initialized anywhere else!)

So, the VM (and dart2js too) is not implementing the specification.

If we want the specification to change, we should open a bug for that, but until that happens, this is a bug in the implementation of the language.

**Comment by lrhn** [comment]
But that is also another bug than this one, so I'll file that separately.
