### ISSUE TITLE
Analyzer error message on incompatible functions is very confusing

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#23492]
Running the analyzer (version 1.11.0-dev.0.0) on the attached file produces the following very confusing error message:

leafp@leafp-linux:~/src/dev_compiler$ dartanalyzer ~/tmp/function-warning.dart
Analyzing [/usr/local/google/home/leafp/tmp/function-warning.dart]...
[warning] A value of type 'Function2 (/usr/local/google/home/leafp/tmp/function-warning.dart)' cannot be assigned to a variable of type 'Function2 (/usr/local/google/home/leafp/tmp/function-warning.dart)' (/usr/local/google/home/leafp/tmp/function-warning.dart, line 12, col 27)
[hint] The value of the local variable 'a2b' is not used (/usr/local/google/home/leafp/tmp/function-warning.dart, line 12, col 21)
1 warning found.

Neither typedef instantiation gets printed out with its arguments, so the error message basically says &quot;Function2 cannot be assigned to Function2&quot;, which is fairly confusing.  I would expect an error message that looked something like &quot;Function2&lt;int, double&gt; cannot be assigned to a variable of type Function2&lt;A, B&gt;&quot;.

---

**Attachment:**
[function-warning.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-23492/comment-0/function-warning.dart) (312 Bytes)

**Comment by srawlins** [comment]
The attached file no longer exists. I'm going to mark this as stale, as I believe this has been reported elsewhere, and is either fixed, or tracked on a separate bug.
