### ISSUE TITLE
Errors in async blocks are propagated too slowly

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23497]
If an error is thrown in an async block, it propagates to the zone's error handler much more slowly than one thrown in a non-async context. For example:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:async';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;runZoned(() async {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleMicrotask(() =&gt; throw 'in microtask');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'in async function';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, onError: (error, stackTrace) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;caught $error&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;}

this prints:

&nbsp;&nbsp;&nbsp;&nbsp;in microtask
&nbsp;&nbsp;&nbsp;&nbsp;in async function

which is not expected, since &quot;in async function&quot; is thrown before &quot;in microtask&quot;. Compare to the version without async:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:async';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;runZoned(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleMicrotask(() =&gt; throw 'in microtask');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'in async function';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, onError: (error, stackTrace) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;caught $error&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;}

and the version that runs the entire body in a microtask:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:async';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;runZoned(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleMicrotask(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleMicrotask(() =&gt; throw 'in microtask');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw 'in async function';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, onError: (error, stackTrace) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;caught $error&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;}

both of which print

&nbsp;&nbsp;&nbsp;&nbsp;in async function
&nbsp;&nbsp;&nbsp;&nbsp;in microtask

as expected.

This is very important for testing (among other things), where errors have to be handled specially and users have strong expectations for their consistent ordering.

**Comment by floitschG** [comment]
Fixed in f2d08149fdeb5e67db1b3b4e4284cbac5a83169c.

**Comment by kevmoo** [comment]
Thanks, @floitschG !!!
