### ISSUE TITLE
Code completion confused by completing field name before constructor declaration

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23501]
Start with the following file:

class C {
&nbsp;&nbsp;final Stri

&nbsp;&nbsp;C();
}

Place the cursor at the end of the line &quot;final Stri&quot; and request completions.

Expected result: the only completions shown should begin with &quot;Stri&quot;, e.g. &quot;String&quot; or &quot;StringBuffer&quot;.  If &quot;String&quot; is chosen, the line should complete to &quot;final String&quot;.

Observed result: a vast array of irrelevant completions are shown, such as &quot;const&quot;, &quot;dynamic&quot;, &quot;AbstractClassInstantiationError&quot;, etc.  If &quot;String&quot; is chosen, the line completes to &quot;final StriString&quot;.

Commenting out the line &quot;C();&quot; works around the problem.

**Comment by danrubel** [comment]
Fixed. Please reopen if you find a failing case.
