### ISSUE TITLE
co19 canvas-strokePath-alpha-shadow_t01 fails on ie11

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23508]
The test
co19/LayoutTests/fast/canvas/canvas-strokePath-alpha-shadow_t01
fails with a windows driver error (I think), maybe due to the video driver taking too long and being interrupted by windows. It is consistent with this that the failure happens after 4.95 seconds.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: sync_exception
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;value: Exception: Error: Could not complete the operation due to error 887a0005.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Stack: Error: Could not complete the operation due to error 887a0005.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at main_test.call$7 (http://127.0.0.1:58412/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_canvas-strokePath-alpha-shadow_t01/test.js:1904:9)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at main (http://127.0.0.1:58412/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_canvas-strokePath-alpha-shadow_t01/test.js:1857:7)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at dartMainRunner (http://127.0.0.1:58412/root_dart/tools/testing/dart/test_controller.js:311:5)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at Anonymous function (http://127.0.0.1:58412/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_canvas-strokePath-alpha-shadow_t01/test.js:4131:7)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at onLoad (http://127.0.0.1:58412/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_canvas-strokePath-alpha-shadow_t01/test.js:4124:7)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;timestamp: 4.954

**Comment by athomas** [comment]
LayoutTests have been deleted.
