### ISSUE TITLE
Highly confusing error message when you forget the "new" on a call to a constructor

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#23503]
Uncaught Error: Class '_Type' has no instance method 'call'.

A better error would be:

Uncaught Error: Class '_Type' has no instance method 'call'. Did you forget to use 'new' when calling a constructor?

**Comment by mhausner** [comment]
If you "forget" the new operator you end up with, say, the expression

var x = List()

The right hand side is a type literal followed by the call operator. That is a perfectly legal Dart expression. However, class literals (of type _Type) do not implement the call operator, thus the error message at runtime when the call is resolved.

I think the more helpful error message proposed here belongs to the Analyzer or another tool. The VM should not be in the business of second-guessing completely legal Dart code.

I do like the idea of making Dart a more robust language with more compile-time errors.

**Comment by Hixie** [comment]
The proposed change doesn't affect the VM. The proposed change is to add a `_Type.noSuchMethod` implementation.

**Comment by Hixie** [comment]
(or to make the `Object.noSuchMethod` implementation check for this case)

**Comment by mraleph** [comment]
In Dart 2 there is optional new anyway.
