### ISSUE TITLE
CSS Webkit locale property reported in quotes on Chrome 43

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23506]
A number of co19 tests are failing because the String value of
&nbsp;getComputedStyle(element).getPropertyValue('-webkit-locale')
has changed from (for example) &quot;zh&quot; to &quot;'zh'&quot; in Chrome 43.  There are single quotes added surrounding the language name.
This also happens to other CSS properties, the 'content' property in computed-style-properties_t01.

This may be a change in what javascript is reporting, in which case an issue should be filed with Chrome.

Failing tests:
co19/LayoutTests/fast/css/content-language-case-insensitivity_t01
co19/LayoutTests/fast/css/content-language-dynamically-removed_t01
co19/LayoutTests/fast/css/content-language-dynamically-added_t01
co19/LayoutTests/fast/css/content-language-no-content_t01
co19/LayoutTests/fast/css/content-language-multiple_t01
co19/LayoutTests/fast/css/content-language-mapped-to-webkit-locale_t01
co19/LayoutTests/fast/css/getComputedStyle/computed-style-properties_t01
co19/LayoutTests/fast/css/nested-at-rules_t01

**Comment by srawlins** [comment]
As @alan-knight says, this is not a bug in chrome, and co19 was changed soon after, in https://github.com/dart-lang/co19/commit/e8fda3bb008a28092e450c3c809a547ce97a711e, to handle it.
