### ISSUE TITLE
Dart2js allows super call to private constructor in another library

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23529]
The following code produces a compile-time error in analyzer and the VM, but is allowed by Dart2js:

test1.dart:
class Base {
&nbsp;&nbsp;Base._privateConstructor() {
&nbsp;&nbsp;&nbsp;&nbsp;print('private constructor called');
&nbsp;&nbsp;}
}

test2.dart:
import 'test1.dart';
class Derived extends Base {
&nbsp;&nbsp;Derived() : super._privateConstructor();
}
main() {
&nbsp;&nbsp;new Derived();
}

When test2.dart is compiled using Dart2js and the result is run, the output &quot;private constructor called&quot; is printed.  This should not be possible, since the constructor is private to test1.dart, and there are no references to it in test1.dart.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org//1360153005
