### ISSUE TITLE
Save and reuse result of constant constructors invoked during parsing

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23533]
When optimizing a function containing a const constructor call, the parser will re-evaluate the constructor, even though the unoptimized compilation already added it to the canonicalized constants.

To avoid the cost of re-evaluation and reduce the number of places where optimization runs Dart code (important for upcoming concurrent compilation), we should save information about these constants and reuse them. This could for instance be done with a map keyed by script and token position.

**Comment by mhausner** [comment]
I am looking at this. There are a few places where we could re-use a previously computed compile-time constant. However, I think we run into problems if the AST for the function we compile looks different depending on whether the constant value has been computed before or not.

**Comment by mhausner** [comment]
Scratch that. The const constructor call is not part of the AST. D'uh.

**Comment by mhausner** [comment]
A cache for const objects, lists and maps has been introduced with this CL:
https://codereview.chromium.org//1308073005

Committed patchset #2 (id:20001) manually as
62e9d056681308fef71540300643db1a63639bc4 (presubmit successful).
