### ISSUE TITLE
Problem with for-in in async finally block

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23537]
In the example below, the finally block throws an unexpected error.

$ dart --version
Dart VM version: 1.10.0-edge.44800 (Tue Apr  7 14:10:27 2015) on &quot;macos_ia32&quot;
$ cat await.dart
import 'dart:async';

import 'package:expect/expect.dart';

main() async {
&nbsp;&nbsp;var commands = await new Future.value(null);

&nbsp;&nbsp;var session = await new Future.value(null);

&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;for (String expected in ['']) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expect.isTrue(await new Future.value(true));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expect.stringEquals(expected, '');
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;for (var program in ['']) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var update = await new Future.value(['']);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (update != null) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return null;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (var command in update) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(command);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await new Future.value(null);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (String expected in ['x']) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expect.isTrue(await new Future.value(true));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String actual = 'y';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expect.stringEquals(expected, actual);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Got expected output: $actual&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (program.code is String) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await new Future.value(null);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;} finally {
&nbsp;&nbsp;&nbsp;&nbsp;for (var command in ['a', 'b', 'c', 'd']) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(command);
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;await new Future.value(null);
&nbsp;&nbsp;&nbsp;&nbsp;Expect.equals(0, await new Future.value(0));
&nbsp;&nbsp;}
&nbsp;&nbsp;String stderr = await new Future.value(&quot;&quot;);
&nbsp;&nbsp;if (stderr != &quot;&quot;) {
&nbsp;&nbsp;&nbsp;&nbsp;throw &quot;Unexpected stderr from fletch VM:\n$stderr&quot;;
&nbsp;&nbsp;}
}
$ dart -ppackage await.dart 
Unhandled exception:
Uncaught Error: Class 'int' has no instance getter 'current'.

NoSuchMethodError: method not found: 'current'
Receiver: 10912128
Arguments: []
Stack Trace:
#­0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#­1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#­2      main.&lt;main_async_body&gt; (file:///Users/ahe/Dart/all/fletch/await.dart:41:47)
#­3      \_RootZone.runUnary (dart:async/zone.dart:1155)
#­4      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#­5      \_Future._propagateToListeners (dart:async/future_impl.dart:577)
#­6      \_Future._completeWithValue (dart:async/future_impl.dart:368)
#­7      \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:422)
#­8      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­9      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­10     \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­11     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#­0      \_rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
#­1      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­2      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­3      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­4      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
$

**Comment by crelier** [comment]
Fixed by https://codereview.chromium.org/1154823003/
