### ISSUE TITLE
Windows x64 VM crashing

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#23535]
The Windows x64 VM is crashing on the buildbot.

See http://build.chromium.org/p/client.dart/builders/vm-win64-release-be/builds/6463/steps/tests/logs/stdio

This have been happening for some time. The Windows x64 bot was &quot;down&quot; as it was out of disk space. When it started building again the crashes showed up.

**Comment by sgmitrovic** [comment]
I think that issues was resolved a while ago.
