### ISSUE TITLE
tree-shaking issue in cps-ir backend

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23548]
Some tests for the ??= operator are failing because of this. See if_null_assignment_static_test/01 for example.

Here is a reduced example to reproduce the problem:
&nbsp;&nbsp;&nbsp;&nbsp;class A { get a =&gt; print('a'); }
&nbsp;&nbsp;&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var x = null;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//new A().a;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(x ??= new A()).a;
&nbsp;&nbsp;&nbsp;&nbsp;}

With the commented as it is, this works with the SSA IR, but not with the CPS IR. If we remove the commented line, it works in both.

**Comment by rakudrama** [comment]
Obsolete
