### ISSUE TITLE
Create an abstract class to share between Maps and record objects

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#23541]
Unlike JavaScript [1], Dart clearly distinguishes between maps and other kinds of objects, for good reasons. However, sometimes we have Dart objects that are sort of like maps because they support accessing fields by name, without actually being maps.

In particular, my internal customers have a UI framework that displays records based on either protocol buffers or JSON maps, and we'd like to avoid creating extra wrapper objects.

I could change GeneratedMessage to implement Map, but this would be confusing:

(1) Protocol buffers are clearly not maps because you can't store arbitrary (key, value) pairs in them.

(2) Proto 3 adds support for actual maps, which would add to the confusion; we don't want both records and maps to implement Map and then have to distinguish &quot;real maps&quot; from &quot;map-like records&quot;.

(3) The Map interface is fairly big. For example, it supports &quot;length&quot; and &quot;values&quot; properties, and some .proto files already have fields with these names. This would cause confusion over what you mean when you access the .values field, for a feature we don't need for a record object.

Therefore, I propose extracting a common interface that can be implemented by both maps and record objects. How about:

abstract class Indexable&lt;V&gt; {
&nbsp;&nbsp;operator V [\](Object key)
}

This would need to be part of the dart:collection library because Map should implement it.

Then a Dart library could declare parameters that have type Indexable when it needs to access fields by name, but it doesn't require the full Map API.

(For this use case, we only care about string keys and dynamic values, much like JSON and JavaScript. But since Map has K and V type parameters already, it seems that Indexable should have a V parameter.)

[1] Before ES6, anyway.

**Comment by lrhn** [comment]
We still have no plan to add an `Indexable` interface, so this will be a no.
