### ISSUE TITLE
Running VM with --coverage_dir that doesn't exist fails with unexpected error

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23550]
Running the Dart VM with --coverage_dir, with a directory that doesn't exist, errors with an unexpected FileSystemException from trying to open a .dart file from my packages.

I do, however, get a correct error from --coverage_dir not existing. That part was expected (because the directory I specified didn't exist)

However, the failure about not being able to open a file that does exist was unexpected.

~/Code/dartdoc[run-tests-once] $ dart --coverage_dir=tmp test/all.dart 
Failed to write coverage file: tmp/dart-cov-74825-1039393057.json
Unhandled exception:
Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/sethladd/Code/dartdoc/test/packages/unittest/unittest.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#­0      \_asyncLoadErrorCallback (dart:_builtin:268)
#­1      \_asyncLoadError (dart:_builtin:287)
#­2      \_loadDataAsyncLoadPort.&lt;anonymous closure&gt; (dart:_builtin:304)
#­3      \_RootZone.runUnary (dart:async/zone.dart:1155)
#­4      \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#­5      \_Future._propagateToListeners (dart:async/future_impl.dart:577)
#­6      \_Future._complete (dart:async/future_impl.dart:358)
#­7      \_cancelAndValue (dart:async/stream_pipe.dart:62)
#­8      Stream.first.&lt;anonymous closure&gt; (dart:async/stream.dart:911)
#­9      \_RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#­10     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#­11     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#­12     \_StreamController&amp;&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#­13     \_StreamController._add (dart:async/stream_controller.dart:570)
#­14     \_StreamController.add (dart:async/stream_controller.dart:516)
#­15     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)

#­0      \_rootHandleUncaughtError.&lt;anonymous closure&gt; (dart:async/zone.dart:886)
#­1      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­2      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­3      \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­4      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
~/Code/dartdoc[run-tests-once] $ pub get
Resolving dependencies... 
Got dependencies!
~/Code/dartdoc[run-tests-once] $ dart test/all.dart 
unittest-suite-wait-for-done
^C
~/Code/dartdoc[run-tests-once] $ 
~/Code/dartdoc[run-tests-once] $ ls -l test/packages/
total 368
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 analyzer -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/analyzer-0.25.0+1/lib
lrwxr-xr-x  1 sethladd  5000  70 May 29 20:16 ansicolor -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/ansicolor-0.0.9/lib
lrwxr-xr-x  1 sethladd  5000  66 May 29 20:16 args -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/args-0.13.1/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 barback -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+4/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 cli_util -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/cli_util-0.0.1+2/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 collection -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/collection-1.1.1/lib
lrwxr-xr-x  1 sethladd  5000  69 May 29 20:16 contrast -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/contrast-0.1.1/lib
lrwxr-xr-x  1 sethladd  5000  67 May 29 20:16 crypto -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/crypto-0.9.0/lib
lrwxr-xr-x  1 sethladd  5000  70 May 29 20:16 csslib -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/csslib-0.12.0+1/lib
lrwxr-xr-x  1 sethladd  5000   6 May 29 20:16 dartdoc -&gt; ../lib
lrwxr-xr-x  1 sethladd  5000  68 May 29 20:16 den_api -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/den_api-0.1.0/lib
lrwxr-xr-x  1 sethladd  5000  67 May 29 20:16 github -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/github-2.2.2/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 glob -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/glob-1.0.4/lib
lrwxr-xr-x  1 sethladd  5000  70 May 29 20:16 grinder -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/grinder-0.7.1+3/lib
lrwxr-xr-x  1 sethladd  5000  68 May 29 20:16 html -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/html-0.12.1+1/lib
lrwxr-xr-x  1 sethladd  5000  66 May 29 20:16 http -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/http-0.11.2/lib
lrwxr-xr-x  1 sethladd  5000  74 May 29 20:16 http_parser -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/http_parser-0.0.2+6/lib
lrwxr-xr-x  1 sethladd  5000  74 May 29 20:16 http_server -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/http_server-0.9.5+1/lib
lrwxr-xr-x  1 sethladd  5000  66 May 29 20:16 intl -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4/lib
lrwxr-xr-x  1 sethladd  5000  68 May 29 20:16 librato -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/librato-0.0.3/lib
lrwxr-xr-x  1 sethladd  5000  69 May 29 20:16 logging -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/logging-0.11.1/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 markdown -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/markdown-0.7.1+2/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 matcher -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.0+1/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 mime -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/mime-0.9.3/lib
lrwxr-xr-x  1 sethladd  5000  80 May 29 20:16 mockable_filesystem -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/mockable_filesystem-0.0.3/lib
lrwxr-xr-x  1 sethladd  5000  75 May 29 20:16 mustache4dart -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/mustache4dart-1.0.10/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 path -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/path-1.3.5/lib
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 petitparser -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 pool -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/pool-1.0.2/lib
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 pub_cache -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/pub_cache-0.0.1+2/lib
lrwxr-xr-x  1 sethladd  5000  77 May 29 20:16 pub_package_data -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/pub_package_data-0.0.1/lib
lrwxr-xr-x  1 sethladd  5000  71 May 29 20:16 pub_semver -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/pub_semver-1.2.1/lib
lrwxr-xr-x  1 sethladd  5000  70 May 29 20:16 quiver -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/quiver-0.21.3+1/lib
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 source_span -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/source_span-1.1.2/lib
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 stack_trace -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.3.2/lib
lrwxr-xr-x  1 sethladd  5000  77 May 29 20:16 string_scanner -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/string_scanner-0.1.3+1/lib
lrwxr-xr-x  1 sethladd  5000  75 May 29 20:16 supports_color -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/supports_color-0.1.1/lib
lrwxr-xr-x  1 sethladd  5000  72 May 29 20:16 unittest -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/unittest-0.11.6+1/lib
lrwxr-xr-x  1 sethladd  5000  73 May 29 20:16 unscripted -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/unscripted-0.6.1+1/lib
lrwxr-xr-x  1 sethladd  5000  66 May 29 20:16 utf -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+2/lib
lrwxr-xr-x  1 sethladd  5000  68 May 29 20:16 watcher -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.5/lib
lrwxr-xr-x  1 sethladd  5000  89 May 29 20:16 webkit_inspection_protocol -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/webkit_inspection_protocol-0.0.1+1/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 when -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/when-0.2.0/lib
lrwxr-xr-x  1 sethladd  5000  66 May 29 20:16 which -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/which-0.1.3/lib
lrwxr-xr-x  1 sethladd  5000  64 May 29 20:16 xml -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/xml-2.3.2/lib
lrwxr-xr-x  1 sethladd  5000  65 May 29 20:16 yaml -&gt; /Users/sethladd/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.2/lib

**Comment by zanderso** [comment]
The --coverage_dir flag has been removed
