### ISSUE TITLE
double.operator-() is unstable

### ISSUE THREAD

**Issue by skabet** [dart-lang/sdk#23563]
The following:

&nbsp;&nbsp;print(identical(double.NAN, -double.NAN));

will print true at first, but false when optimized.

Note that the initial behavior is unexpected, as the compare is bitwise but the sign-bit is not changed.

**Comment by sgmitrovic** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/c0824e77255522a5f3e981b0ea88f7ccee60259a
