### ISSUE TITLE
use package-spec file in repo/gyp/bots

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23565]
once we have the package-specs implemented in all of our tools, it would be great to use it in our repo and bots and remove the use of symlinks (woo hoo!)

I'm creating this bug to track, but this is blocked on first seeing the features implemented (tracked in issue #23372)

**Comment by whesse** [comment]
I have created an initial CL to do this, which currently just creates the .packages file besides the packages directory, and uses it in the tests.  I will do more testing of this, and then commit.  Removing the packages directory will be a separate cl.

https://codereview.chromium.org/1746743002

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by whesse** [comment]
Done, with https://codereview.chromium.org/2346163005
