### ISSUE TITLE
Inconsistent parent/child relationships for PrefixElement

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23567]
Given code like this:
&nbsp;&nbsp;import 'foo.dart' as a;
&nbsp;&nbsp;import 'bar.dart' as a;

analyzer currently generates an element model with 1 LibraryElement, 2 ImportElements and 1 PrefixElement.  The Element.visitChildren method considers the ImportElements to be children of the LibraryElement, and considers the PrefixElement to be a child of both ImportElements.

This is in contrast to the behavior of Element.enclosingElement (effectively this encodes a &quot;parent&quot; relationship).  It considers the parent of the ImportElements to be the LibraryElement (which is consistent with the behavior of visitChildren), and considers the parent of the PrefixElement to *also* be a child of the LibraryElement (which is *inconsistent* with the behavior of visitChildren).

This has forced us to write clumsy workaround code in our indexing logic, since the single PrefixElement shared by both imports is insufficient to distinguish uses of the &quot;a&quot; prefix that refer to &quot;foo.dart&quot; from ones that refer to &quot;bar.dart&quot;.  It's also creating confusion for some clients of analyzer.

After discussion today, we decided that a more sensible model would be for the code above to produce 2 PrefixElements, one associated with each ImportElement, and that the enclosingElement of a PrefixElement should be its corresponding import.  Technically this would be a breaking change (since it's conceivable that some client code might rely on the enclosing element of a PrefixElement, or might expect overlapping prefixes to use identical elements).  However we think the effect on clients should be small.

**Comment by bwilkerson** [comment]
This is now obsolete given the element model rewrite happening to support augmentations, so I'm going to close it.
