### ISSUE TITLE
analysis_server: RemoveContentOverlay on "unknown" file causes analysis on it

### ISSUE THREAD

**Issue by radicaled** [dart-lang/sdk#23579]
Sending a message like this to the analysis server:

```
{"method":"analysis.updateContent","params":{"files":{"/home/arron/Projects/test_project/pubspec.yaml":{"type":"remove"}}},"id":"dart-tools-4"}
```

will cause the analysis server to begin parsing that file as if it were a valid Dart source file, even if the file at that path **has not** been added via `AddContentOverlay`. According to the documentation, doing this should be a NOOP.

**Comment by srawlins** [comment]
Possibly still a valid bug; bumping to P4 as this action seems like it should not happen much (ever?).

**Comment by keertip** [comment]
Will not fix, closing.
