### ISSUE TITLE
Incorrect setting of checked parameter in spawnURI

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#23578]
Test: isolate/checked_test.dart
crashes in x64:
 python tools/test.py -ax64 --write-debug-log --write-test-outcome-log --copy-coredumps --vm-options --optimization-counter-threshold=5 --exclude-suite pkg -t60 isolate/checked_test

The VM requires deterministic generation of unoptimized code in order to preserve deopt-ids. Therefore the checked mode must be turned on before any dart code in that isolate has been run. What happens is that RawReceivePortImpl._set_handler is compiled and run before checked mode is set and a sunsequent optimizing pass recompiles RawReceivePortImpl._set_handler  in checked mode. Wrong ICData gets assigned to instructions, causing a crash on x64 at least.

**Comment by sgmitrovic** [comment]
CC @iposva-google

**Comment by iposva-google** [comment]
Looking at this I realized that the whole setting of per isolate flags needs a complete revamp. Also we need to change the currently bolted-on strict compilation setting that can be set from the C API.

**Comment by iposva-google** [comment]
Fixed with https://codereview.chromium.org//1162033005

**Comment by sethladd** [comment]
Thanks!
