### ISSUE TITLE
Can't access properties of JsObject that wraps a javascript custom element prototype

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#23574]
See https://gist.github.com/jakemac53/dc4d38ba20e9783f1581 for an example which works in dartium but not in dart2js. The error message is the following:

&nbsp;&nbsp;&nbsp;&nbsp;Uncaught TypeError: J.getInterceptor$asx(...).$index is not a function

This makes it so you can't modify or access properties on the prototype of a javascript custom element, which limits pretty heavily what you can do.

**Comment by ricowind** [comment]
For completeness, this bug was updated while we moved over the issues:
Here is the only missing comment:
Comment #4 on issue 23574 by jakemac@google.com: Can't access properties of JsObject that wraps a javascript custom element prototype
https://code.google.com/p/dart/issues/detail?id=23574

Ah, thanks for the workaround, that has unblocked me for now at least :)

**Comment by kevmoo** [comment]
@sigmundch @jakemac53 Please remove the 1.11 milestone (or throw a fit to get this fixed).

Do not flag as 1.12 unless it is critical.

**Comment by jakemac53** [comment]
we have the workaround, so not critical

**Comment by ErikGrimes** [comment]
I'm not sure if this is a related or different issue, but the exception I'm getting is the same. 

I have a Dart function that is passed to a JavaScript function for a callback.  The JavaScript function passes a JavaScript object to the Dart function.  Attempting to access a property on the JavaScript object via "[]" results in "Uncaught TypeError: J.getInterceptor$asx(...).$index is not a function".  Accessing the property on a new object created via "new JsObject.fromBrowserObject" on the original object eliminates the exception, but returns undefined for the property value in dart2js.  Dartium returns the property value as expected.
