### ISSUE TITLE
Crashes for pkgbuild/samples/third_party/todomvc_performance

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23575]
Observed on build bot:
https://chromegw.corp.google.com/i/client.dart/builders/pub-mac-be/builds/13391/steps/pkgbuild_public_pkgs%20tests%20failures/logs/stdio
where the failure is in Dart code, but the failure seems impossible w.r.t. Dart semantics.

...and with a local debug build, it instead fails an assertion:

stderr:
runtime/vm/unicode.cc:224: error: expected: IsLatin1SequenceStart(utf8_array[i])

Command[dir_copy\]: Copying '/usr/local/google/home/koda/sendMaps/sdk/samples/third_party/todomvc_performance' to '/usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance'.
Took 0:00:00.062273

Command[modify_pubspec\]: Adding necessary dependency overrides to '/usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance/pubspec.yaml' (destination = /usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance/pubspec.yaml).
Took 0:00:00.003896

Command[pub_get\]: PUB_CACHE=/usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance/pub-cache /usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/dart-sdk/bin/pub get (working directory: /usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance)
Took 0:00:12.235000

Command[pub_build\]: PUB_CACHE=/usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance/pub-cache /usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/dart-sdk/bin/pub build (working directory: /usr/local/google/home/koda/sendMaps/sdk/out/DebugIA32/generated_pub_package_builds/public_packages/samples_third_party_todomvc_performance)
Did not run

Short reproduction command (experimental):
&nbsp;&nbsp;&nbsp;&nbsp;python tools/test.py --use-sdk --write-test-outcome-log -t120 --copy-coredumps --use-public-packages pkgbuild/samples/third_party/todomvc_performance

**Comment by fsc8000** [comment]
I fixed this in https://github.com/dart-lang/sdk/commit/63209c93d3572926c42e748395ebc9f31dbce273.
