### ISSUE TITLE
SDK Extensions for the Analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23583]
This is a request for "SDK Extensions" for the analyzer.

# Objective: make it easy to develop for new Dart platforms, like dart:sky, with our tools.

## Scenario/Demo:

* Starts up Atom, with the Dart plugin installed.
* Creates a new empty directory.
* Adds a pubspec.yaml file
* Declares a dependency on the sky package.
* Saves the file, and runs `pub get`
* Creates a lib/main.dart file, opens it up in Atom.
* writes "import 'dart:sky';"
* No errors!

## Proposed solution:

The Sky package includes the definition of dart:sky inside a new `sdk` directory in the package.

```
README.md
CHANGELOG.md
bin/
  ...
lib/
  ...
sdk/
  sky.dart
```

The Sky package includes new metadata that declares the location of the definition of dart:sky, using the `_sdk` key in the pubspec.yaml file.

```
name: sky
version: 0.0.5
dependencies:
  crypto: 0.3.4
_sdk:
  sky: sdk/sky.dart
```

A tool, such as the pub client, finds the `_sdk` metadata in any dependencies for the project. It then constructs a `.dart_sdk_extensions` file in the root of your project.

```
# This is a .extensions file
# It has comments, and key=value pairs.
sky=full/path/to/sky/package/sdk_ext/sky.dart
```

The analyzer looks for a `.dart_sdk_extensions` file (see below), parses it, and registers the additions mappings.

## Finding the .extensions file

If dartanalyzer is run on an individual file, then it will look for a .extensions file in the working directory. If dartanalyzer is run on a directory, then it will use the same algorithm used by analysis server when given an analysis root. Specifically, it will first run the algorithm used to compute a package-map map. That algorithm produces a map from directories to package maps. It will then look in each of the directories in the map for a .extensions file, and if one is found then any files in that directory (that are not also in a subdirectory used as a key in the map) will be analyzed in a context that includes the dart: URI's mapped in the .extensions file.

Alternatively, the dartanalyzer command-line tool can be passed a path to the extensions file. If a command-line arg is used to specify the .extensions file, the dartanalyzer will use that one. (Example: dartanalyzer --extensions=path/to/extensions/file analyze_me.dart)

Once dartanalyzer understands how to find .extensions, and how to use the --extensions argument, it can deprecate the --url-mappings command-line argument.

In no case will either dartanalyzer or the analysis server look up (or down) the directory structure to find a .extensions file that is not in either the working directory or one of the directories used as a key in the package-map map. (Note that this is different from the algorithm used to compute the package-map map, which will search up the directory structure from the initial directory.)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by sgjesse** [comment]
The specification above uses both `_sky_ext` in the text, and `_sdk` in the example `pubspec.yaml` file. Shouldn't it be just `sdk`?

Lasse mentioned that maybe `.extensions` is too generic, and should maybe be `.sdk_extensions`.

**Comment by sethladd** [comment]
Thanks for the review. I've updated the proposal above.

Using `.dart_sdk_extensions` seems like the most obvious file name.

**Comment by mezoni** [comment]
Does this means that any person can wrote an SDK extension and propose to use it?

**Comment by sethladd** [comment]
Anyone can build a new embedding of the Dart VM, and in that embedding introduce new libraries that only exist in that embedding.

**Comment by mezoni** [comment]
What means a `new embedding of the Dart VM`?
What is the difference between a common package and the new embedding of the Dart VM?
Only in the presence of the file `.extensions` in standard package?
Any additional features (benefits) will be provided or just a single feature as the possibility to use an import directive with `dart:` schema?

**Comment by sethladd** [comment]
Sky is an embedding of the VM. Dartium is an embedding of the VM. Even the stand-alone Dart VM is an embedding.

All embeddings should provide the core Dart, but embeddings are free to offer additional dart: libraries.

**Comment by mezoni** [comment]
If the stand-alone Dart VM is an embedding of the VM then what means a VM?
Where I can read about that `abstract` VM which is not a stand-alone VM but an `alma mater` VM?

- Alma mater VM
-- Stand-alone Dart VM embedded of Alma mater VM (or it not embedded of alma mater VM?)
-- Sky embedded of Alma mater VM (or it embedded of stand-alone VM?)
-- Dartium is an embedding of the VM (or it embedded of stand-alone VM?)

**Comment by mezoni** [comment]
Or does this means that Sky is an embedding of the VM but NOT an embedding of the stand-alone VM because Sky is another Dart distribution and Sky does not requires the stand-alone VM installed becasue Sky already is an embedding of the VM (which is NOT stand-alone Dart VM because stand-alone Dart VM are another (NOT a Sky) embedding)?

**Comment by sethladd** [comment]
I think the right way to think about it: Sky is an embedding of the core Dart VM technology.

**Comment by sethladd** [comment]
Thanks @johnmccutchan

**Comment by sethladd** [comment]
For the record, this landed. Docs to follow.
