### ISSUE TITLE
feature request: projection-based sorting API

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#23597]
This is meant to stimulate discussion on a possible improvement to the sorting API.
Comparators are often tedious to write and hard to read:

``` dart
people.sort((p1, p2) => Comparable.compare(p1.name, p2.name));
```

Notice how `Comparable.compare` is distracting and `name` is repeated.

Projections are often better (nb. this API is hypothetical and doesn't exist in Dart today,
but python has it):

``` dart
people.sortBy((p) => p.name);
```

These 2 APIs, comparators and projections, are equally powerful in the sense that you can reduce each to the other without significant loss of efficiency, but usually when both are available and there is an appropriate projection, it's simpler to use the projection API.

It seems like you need comparators primarily when there is no existing canonical implementation of a `Comparable` with the desired order, e.g. if you need to lexicographically order a list of pairs and you don't have a

``` dart
class OrderablePair<A extends Comparable, B extends Comparable> {
  final A a;
  final B b;

  OrderablePair(this.a, this.b);

  @override
  int compareTo(OrderablePair<A, B> other) {
    var aResult = Comparable.compare(this.a, other.a);
    if (aResult != 0) return aResult;
    return Comparable.compare(this.b, other.b);
  }
}
/// Convenient, but you lose type safety.
orderablePair(x, y) => new OrderablePair(x, y);
```

readily available, then one way or another, you must define a comparator.
But if you do have a `Comparable` available that implements the desired order, or can compose one from existing constructs, then projections can be a lot more convenient.  Examples:

``` dart
class Reversed<T> implements Comparable<T> {
  final T _delegate;

  Reversed(this._delegate);

  @override
  int compareTo(T other) => Comparable.compare(other, _delegate);
}
/// Convenient, but you lose type safety.
reversed(t) => new Reversed(t);

people.sortBy((p) => reversed(p.name));
people.sortBy((p) => p.socialSecurityNumber);
people.sortBy((p) => orderablePair(p.name, reversed(p.numChildren)));
```

(Nb. In order to create only O(n) little wrapper objects instead of Omega(n lg n),
`sortBy` should probably cache the projections until it finishes.)

Can Dart get a `sortBy` or some other projection-based sorting API?
Yeah, one could implement it oneself, but it's more of a pain than it sounds and core libraries should include batteries.  Dart has no generic methods, so you can't do this

``` dart
<E, T extends Comparable> void sortBy(List<E> list, Comparable<T> projection(E e)) {...}
```

You could try extending `List`, but `List` only has factory methods, so it's effectively a "final" class.  You could try using quiver's `DelegatingList`, but that's annoying and distracting.
For now, the best solution seems to be to just create a utility method and throw away type safety:

``` dart
void sortBy(List list, Comparable projection(e)) {...}
```

Ideas?

**Comment by sethladd** [comment]
cc @lrhn

**Comment by lrhn** [comment]
We won't be changing the `List` interface at this point.
What we can do is add helper functions for creating comparators, like:

```dart
Comparator.by(project(T x), [int compare(a, b) = Comparator.compare]) => 
    (T a, T b) => compare(project(a), project(b))
```

These would likely go into `package:collection` along with the equality functionality.

**Comment by seaneagan** [comment]
The [contrast package](https://github.com/seaneagan/contrast) has a `by` function for this:

`points.sort(by((point) => point.magnitude)`

as well as many other APIs related to comparison of values.

**Comment by matanlurey** [comment]
I think its reasonable to say adding a method to `package:collection` is the only likely outcome.
