### ISSUE TITLE
Need something like Dart_CreateLibrarySnapshot API call that will create a snapshot of the specified library

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23598]
We need a new API call that will create a snapshot of the specified library, something like Dart_CreateLibrarySnapshot.

The current API Dart_CreateScriptSnapshot creates a snapshot of the root_library (the script that was loaded in using Dart_LoadScript).

**Comment by a-siva** [comment]
cc: @abarth

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/commit/c67f93099fa3ac3e6a80e08517c16fe0df842806

**Comment by abarth** [comment]
Thanks!!
