### ISSUE TITLE
Fresh repo, fresh gclient sync, doesn't install markupsafe on a mac

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23593]
On a Mac

Brand new repo  (gclient sync)

cd tools/dom/scripts

./go.sh

Error: `ImportError: No module named markupsafe`

**Comment by sethladd** [comment]
cc @vsmenon

**Comment by sethladd** [comment]
workaround was to run:

`sudo easy_install markupsafe`

**Comment by floitschG** [comment]
@sethladd please triage this issue.

**Comment by srawlins** [comment]
+1 markupsafe requirement comes from Jinja2:

    File "/Users/srawlins/code/dart-repo2/sdk/third_party/jinja2/utils.py", line 520, in <module>
        from markupsafe import Markup, escape, soft_unicode

**Comment by srawlins** [comment]
What about adding a check to dartdomgenerator.py? Either that, or markupsafe needs to be pulled into third_party.

```diff
diff --git i/tools/dom/scripts/dartdomgenerator.py w/tools/dom/scripts/dartdomgenerator.py
index 5a35903..63976ce 100755
--- i/tools/dom/scripts/dartdomgenerator.py
+++ w/tools/dom/scripts/dartdomgenerator.py
@@ -5,6 +5,11 @@

 """This is the entry point to create Dart APIs from the IDL database."""

+try:
+  import markupsafe
+except ImportError:
+  raise ImportError('Could not find the markupsafe python package; try `easy_install markupsafe`')
+
 import css_code_generator
 import os
 import sys
```

**Comment by terrylucas** [comment]
For Mac you'll need to install markupsafe manually as mentioned above e.g.,

sudo easy_install markupsafe
