### ISSUE TITLE
Dartium Crashes on HTML5 Date Input

### ISSUE THREAD

**Issue by rightisleft** [dart-lang/sdk#23602]
Dartium will crash when using any html5 date input selector.

This is not related to dart code, only the Dartium browser. 

Here's a repro video: https://vid.me/ZgeL

Dartium Version: Version 39.0.2171.0
Operating System : OS X 10.10

Please let me know if i can provide additional details

This is blocking

**Comment by zoechi** [comment]
#23416

**Comment by alan-knight** [comment]
Yes, duplicate of #23416 per previous comment.
