### ISSUE TITLE
Scopes are created multiple times with the new task model

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#23608]
We have several tasks visiting ASTs using ScopedVisitor - BuildFunctionTypeAliasesTask, ResolveUnitTypeNamesTask, ResolveReferencesTask, etc. Visit the same AST multiple times, so we create new Scope instances for the same logical scopes multiple times. Creating scopes costs something.

Would be good to measure the cost and decide if we want to optimize this.

**Comment by bwilkerson** [comment]
Agreed, but so far I'm not seeing scope creation show up as a major cost in the performance measurements I've been doing. I'm going to close this until we know that it's an issue we need to address.

**Comment by scheglov** [comment]
Actually I see scopes creation in Observatory.
I'm not sure whether these percents should be added, but even 6% of 80% of 60% is still something :-)

![image](https://cloud.githubusercontent.com/assets/384794/10250552/54f37e5e-68e0-11e5-8700-3f719330d2f0.png)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1370993009
![image](https://cloud.githubusercontent.com/assets/384794/10251315/b89eab3c-68e4-11e5-91f4-8bf625ac9092.png)

**Comment by scheglov** [comment]
It is faster now.
