### ISSUE TITLE
Create new Resolver to play nice with package maps from package config files.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#23615]
As per our conversation, we need a new kind of resolver to work with the Package Resolution Configuration File [DEP](https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md). It will be used in [`Driver._chooseUriResolutionPolicy`](https://github.com/dart-lang/analyzer_cli/blob/master/lib/src/driver.dart) and be provided a `Map<String, Uri>` from the parsed config file. 

cc: @stereotype441

**Comment by mit-mit** [comment]
@pq, is this still needed for 1.12?

**Comment by pq** [comment]
This is done. Sorry for the lag in closing out!
