### ISSUE TITLE
Please merge the latest pub to dev

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23610]
Please cherry-pick dfd7844d2c9c0dd163e2e1299d064b7c23f83ea8. It brings in the latest pub, which gets rid of a deprecation warning that we don't want in 1.11.

**Comment by sethladd** [comment]
cc @ricowind @kasperl @whesse

**Comment by ricowind** [comment]
Fixed in 1b39e02dc275f97f6d1c75ee53041bf4cf6a620f

**Comment by sethladd** [comment]
Thanks Rico!
