### ISSUE TITLE
SDK extension support from pub

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23619]
See the actual proposal here: https://github.com/dart-lang/sdk/issues/23583

The SDK extensions proposal includes support for using pubspec.yaml to advertise that a package contains an SDK extension.

We'd like to ask that the pub client create the `.dart_sdk_extensions` file from all pubspec.yaml files for an application.

Thank you!

**Comment by mezoni** [comment]
Does this means that any person can wrote an SDK extension and propose to use it?

**Comment by sethladd** [comment]
No longer needed.
