### ISSUE TITLE
Dart2js problems when import prefix not followed by '.'

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23611]
If the user declares an import prefix like so:

    import '...' as prefix;

and then attempts to use `prefix` like a first-class object (i.e. not following it with '.'), the spec usually calls for a compile-time error.  There are two exceptions: `prefix()` should be treated as equivalent to `this.prefix()`, and `prefix = ...` should be treated as equivalent to `this.prefix = ...`.

Dart2js currently fails to produce the expected compile-time error for the following patterns:

    prefix?.identifier();
    prefix?.identifier;
    prefix?.identifier = ...;
    prefix?.identifier += ...;
    prefix?.identifier ??= ...;
    f(prefix);
    var x = prefix;
    var x = prefix[...];

The following patterns cause Dart2js to crash:

    prefix ??= ...;
    prefix[...] ??= ...;
    prefix = ...;
    prefix += ...;
    prefix[...] = ...;

The following pattern causes Dart2js to generate an improper warning at compile time, and throw a NoSuchMethodError at runtime:

    class B {
      void prefix() {}
    }
    class C extends B {
      void f() {
        prefix();  // Should be equivalent to "this.prefix();"
      }
    }

**Comment by gbracha** [comment]
We will adjust the spec to follow lexical scope consistently for the other two cases.

**Comment by stereotype441** [comment]
Note that the spec has now been updated to follow lexical scope consistently, and commit 9c90a66d0d9f2dd6f3e7cd831f2a3e15ddeb8603 adjusted the tests accordingly.  So the two exceptions I noted in my initial bug report no longer apply.
