### ISSUE TITLE
VM fails to give compile-time error when prefix not followed by '.'

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23612]
Section 16.32 (Identifier Reference) of the spec contains the following text:

Evaluation of an identifier expression e of the form id proceeds as follows:
Let d be the innermost declaration in the enclosing lexical scope whose name is id or id=.  If no such declaration exists in the lexical scope, let d be the declaration of the inherited member named id if it exists.
- If d is a prefix p, a compile-time error occurs unless the token immediately following d is '.'.

The VM does not correctly produce this compile-time error.  I will follow up with a CL containing tests that reproduce the problem.

Note, however, that there are two exceptions in which no compile-time error should be produced: if the prefix appears on the left side of a normal (non-compound) assignment, or to the left of an opening paren, then it is treated as though it were followed by `this.`.  In other words:

    import '...' as p;
    class Base {
      var p;
    }
    class Derived extends Base {
      f() {
        p = () {}; // Treated as: this.p = () {}
        p(); // Treated as: this.p();
      }
    }
    main() {
      new Derived().f();
    }

The VM handles these two exceptions correctly.

**Comment by iposva-google** [comment]
@gbracha

**Comment by gbracha** [comment]
we will adjust the spec to follow lexical scope consistently, eliminating the two exceptions mentioned above.

**Comment by stereotype441** [comment]
Note that the spec has now been updated to follow lexical scope consistently, and commit 9c90a66d0d9f2dd6f3e7cd831f2a3e15ddeb8603 adjusted the tests accordingly.  So the two exceptions I noted in my initial bug report no longer apply.

**Comment by mhausner** [comment]
Should this be closed then or is there still an issue?

**Comment by stereotype441** [comment]
It looks like this was fixed by 84be183a329c971541ba882a2244921c16c8f990.
