### ISSUE TITLE
Dart2js generates unexpected compile-time error for redundant initializer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23618]
If a final field is initialized both at the site of its declaration and at the site of the constructor declaration, that should be a runtime error, not a compile-time error.  It is only a compile-time error if the constructor is a const constructor _and_ it is invoked using "const".

Dart2js treats it as a compile-time error regardless of const-ness.

I will follow up with a CL introducing a failing test.

**Comment by askeksa-google** [comment]
In Dart 2, this situation is a compile-time error.
