### ISSUE TITLE
Please cherry pick dart2js packagespec implementation

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#23616]
Please cherry pick 63681d5b59a26d00233ee582e8f9b9fa63c0bd80 and fee40ca9e494cf6e854d81de3a53e37f70247241

This adds support for [this DEP](https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md) to dart2js.

**Comment by sethladd** [comment]
:bowtie:

**Comment by sethladd** [comment]
cc @kasperl @ricowind @whesse

**Comment by whesse** [comment]
Merged into 1.11.0-dev.5.2, which is now built, but not yet promoted.

**Comment by ricowind** [comment]
promoted
