### ISSUE TITLE
Const constructor can redirect to non-const constructor

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#23622]
```
class A {
  A();
  const A.redirecting() : this();
}

main() {
  print(const A.redirecting());
}
```

This program should fail, but prints:
`Instance of 'A'`

**Comment by mhausner** [comment]
I just stumped Gilad with this. There is no discussion of this in the spec. The spec should state that the redirection target must be const, just as the super initializer of a constant constructor must be a constant constructor.

**Comment by eernstg** [comment]
No milestone now: This clarification needs to be performed, but it will not block Dart 2.

**Comment by eernstg** [comment]
The language specification does specify that the redirectee must be const as well, as of 715d59779ef3c1333d482301783b2ad91a91cf46.

Given that the specification issue has been resolved I would close this issue. But I just checked that the [given example](https://github.com/dart-lang/sdk/issues/23622#issue-87328137) is still processed by the analyzer as well as the vm, and dart2js crashes, I'll relabel this issue instead.

**Comment by jensjoha** [comment]
We now get this error:
```
t.dart:3:27: Error: A constant constructor can't call a non-constant constructor.
  const A.redirecting() : this();
                          ^
```

but technically still produce this class:
```
class A extends core::Object {
  constructor •() → self::A
    : super core::Object::•()
    ;
  const constructor redirecting() → self::A
    : this self::A::•()
    ;
}
```
so some error recovery might be needed (e.g. remove the const from the redirecting constructor, or make its initializer invalid-initializer or whatnot).
