### ISSUE TITLE
Dart2js dart:mirrors does not include abstract members in declarations

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#23627]
import "dart:mirrors";
     
    abstract class A {
      int foo();
    }
    main() {
      print(reflectType(A).declarations);
    }
Prints `{Symbol("A"): MethodMirror on 'A'}` in dart2js and `{Symbol("foo"): MethodMirror on 'foo', Symbol("A"): MethodMirror on 'A'}` on the VM.
Not sure what is right, but it should be consistent at least.

**Comment by karlklose** [comment]
Duplicate of #18721.
