### ISSUE TITLE
Potential deadlock in FullSnapshotWriter::WriteVmIsolateSnapshot

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23626]
If the scripts array allocation in FullSnapshotWriter::WriteVmIsolateSnapshot triggers a GC, it would cause a deadlock with the task count increment in ForwardList's constructor.

A possible fix would be to add an Initialize method to ForwardList, to be called before any actual modification of header bits, or alternatively to compute the scripts array before creating the writer.

@a-siva

**Comment by kodandersson** [comment]
Unfortunately, the fix is not that simple, since Symbols::SetupSymbolTable at the end of WriteVmIsolateSnapshot also allocates.

**Comment by a-siva** [comment]
Daniel, I will take this bug, I am about to modify the snapshot writer to not change the header bits and instead use a side data structure to track objects that are already visited. Once this is done we don't need to have the snapshot writer doesn't need the check to prevent GC tasks

**Comment by a-siva** [comment]
https://chromiumcodereview.appspot.com/1399663002/ fixes this issue.
