### ISSUE TITLE
dart2js with csp mode: null reference error in IE 10-11

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/sdk#23623]
We are experiencing an issue running a project in IE10 and IE11 using compiled JS from dart2js with CSP mode enabled. I have created a reduced test-case that exhibits the issue with no external dependencies:

_pubspec.yaml_
```yaml
name: dart_ie_csp
transformers:
- $dart2js:
     csp: true
```

_web/index.dart_
```dart
import 'dart:html';

main() {
  querySelector('#content').innerHtml = 'Hello IE!';
}
```

_web/index.html_
```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<div id="content"></div>
<script src="index.dart.js"></script>

</body>
</html>
```

The resulting error (in IE11):
![sc](https://www.dropbox.com/s/hw6jlujgcc0bicr/Screenshot%202015-06-11%2015.27.45.png?dl=1)

In the image above, `constructor.name` is null, which causes `cls` to be null, etc.
![sc2](https://www.dropbox.com/s/ubflcmoi62yffv2/Screenshot%202015-06-11%2015.32.34.png?dl=1)

Simply switching CSP mode to `false` in the `pubspec.yaml` fixes the issue. However, we do require CSP-compliant JS in our production applications so this has become a roadblock.

**Comment by floitschG** [comment]
Just filed a cherry-pick request: https://github.com/dart-lang/sdk/issues/23660
