### ISSUE TITLE
Please merge revision 19bb19d7162cfae8e9fc1981fc12d8c75a2f83b0 into dev channel

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#23638]
@ricowind @whesse @kasperl
Fixes a heap corruption bug in the VM.

Revisions to be merged:
19bb19d7162cfae8e9fc1981fc12d8c75a2f83b0

This merged cleanly.

**Comment by whesse** [comment]
Cherry-picked to 1.11.0-dev.5.3, c0e90cb
