### ISSUE TITLE
Add support for Windows 10

### ISSUE THREAD

**Issue by Scorpiion** [dart-lang/sdk#23633]
Windows 10 is coming July 29, 2015. I guess Dart support on day 1 is not a requirement, but the sooner the better right?

I don't know the details of how much work is required, maybe there is no changes just a repacking/renaming of the existing Windows download? Personally I'm on Linux most of the time, but if anyone have downloaded the tech preview of Windows 10 and has the time to give some feedback here what works and/or not I'm sure that would be appreciated.

Source for release date:
http://www.microsoft.com/en-us/windows/features

Motivation for this issue was the [gplus post](https://plus.google.com/+DavyMitchell/posts/jb6jVSNYUpf) of @daftspaniel

**Comment by mit-mit** [comment]
I'll get this verified.

**Comment by mit-mit** [comment]
I did some basic testing of both the SDK and editors (Atom+WebStorm) and found no issues.
