### ISSUE TITLE
Enhancing Math Functions Max/Min

### ISSUE THREAD

**Issue by odesho** [dart-lang/sdk#23637]
I would like to submit codes to improve max and min function to find the max/min value in an array list. Is it possible to submit or is it completely unnecessary?

**Comment by seaneagan** [comment]
You can just use them in combination with `Iterable.reduce`:

https://dartpad.dartlang.org/f57669fe47b4514523ac

**Comment by odesho** [comment]
Damn... Didn't know such function existed. Thank You!

**Comment by sethladd** [comment]
Thanks @odesho for the question and to @seaneagan for the answer :)
