### ISSUE TITLE
Please merge 8 revisions into dev channel

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#23639]
@ricowind @whesse @kasperl @dgrove 
Revert the breaking changes to Platform.executable and adds Platform.resolvedExecutable with the enhanced behaviour.

Please cherry-pick the following changes:

d5a34bd6d2bf3c05023214e1cf387943929b56d4
bbdc57ebf6a5f0a2646c88ce3c42ff866ab97599
bd25e641f2819f6d353f712f3831eec767f37be6
5cc8fca131c00d5b673665af6dfc7f4906b1186d
ed72caa3cd17f3762a1f018b048714612ccf8de3
82535a6e911c0e2059f1af9797da0c9bcdbdb324
c05c8c66069db91cc2fd48691dfc406c818d411d
f9e8852edb1476b1b0c93b9beda99634eb248f4b

This merged cleanly

**Comment by sgjesse** [comment]
Please cherry-pick

9a01a22e96db9f407b729007f524e6e1e422ae51

as well. Making it 9 commits.

This last one reverts 4 of the 8 above.

**Comment by whesse** [comment]
Adding 3c85970 to the list of commits.  This is a status file update for 9a01a22.

**Comment by sgjesse** [comment]
Please also cherry-pick

3c85970637720824b8685660b9fe43a66ac90935

as well. Making it 10 commit.

This last one updates the status file.

**Comment by whesse** [comment]
10 commits cherry-picked to 1.11.0-dev.5.3, c0e90cb.
