### ISSUE TITLE
Dart-tips refers to feature no longer in the language, should contain disclaimer.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23636]
The page: https://www.dartlang.org/dart-tips/dart-tips-ep-6.html refers to the "?x" operator (whether argument `x` was passed). It might need to be updated with a warning that the feature is no longer in the language.

See: http://stackoverflow.com/questions/30830592/checking-if-optional-parameter-is-provided-in-dart/30838348#30838348

**Comment by srawlins** [comment]
Warning now exists at the top of the page. https://www.dartlang.org/dart-tips/dart-tips-ep-6.html
