### ISSUE TITLE
dart2js semantic visitor: handling erroneous super cases

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23631]
Consider this example:
```dart
class A {
  final foo = 3;
}

class B extends A {
  bar() => super.foo = 2;
}

main() {
  new B().bar();
}
```

This is currently invoking the semantic visitor method `visitUnresolvedSet` instead of `visitFinalSuperFieldSet`.

@johnniwinther was this intentional?

**Comment by johnniwinther** [comment]
The old resolution structure conflated the two; just storeing an ErroneousElement. The new resolution structure (in progress) will distinguish the two.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1274073003/
