### ISSUE TITLE
Refused to load the script for Content Security Policy

### ISSUE THREAD

**Issue by Maluma1** [dart-lang/sdk#23632]
This code:

    ScriptElement script = new Element.tag("script");
    script.src = "https://test.net/test/0.4.2/test.js";
    document.body.children.add(script);

generates this error:

> Refused to load the script 'https://test.net/test/0.4.2/test.js' because it violates the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I tried these ways to use an external script but do not work:

> http://stackoverflow.com/questions/30809498/refuse-to-load-js-in-dart

**Comment by floitschG** [comment]
If you compile with dart2js you need to use the --csp mode of dart2js.
Otherwise it's a Chrome-extension issue.
I can see you got some answers on stack-overflow. -> closing here.
