### ISSUE TITLE
DartVM crashes on nested awaits in catch blocks (Bus error 10 / exit code 138)

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#23634]
Just running the following code makes the Dart VM to crash:
```dart
import 'dart:async';
main() async {
  try {
    return await new Future.error('1');
  } catch (e1) {
    try {
      return await new Future.error('2');
    } catch (e2) {
      return await new Future.error('3');
    }
  }
}
```
Outputs:
```
> dart crash.dart ; echo $?
Bus error: 10
138
```

Note that the (equivalent?) code runs / propagates errors fine:
```dart
import 'dart:async';
main_() {
  return new Future.error('1').catchError(
  	(e1) => new Future.error('2').catchError(
  	  (e2) => new Future.error('3')
  	)
  );
}
```

**Comment by deftomat** [comment]
Which version did you use?

I try your code in **1.10.0_r45396** and its fine.

**Comment by ochafik** [comment]
This is with `1.10.1` on `macosx`.

Note that `1.11.0-dev.3.0` on `linux_x64` just segfaults.

**Comment by deftomat** [comment]
Yes, I try your code with ```1.10.1``` on ```macos_x64``` and I get the same error.

However, on ```Windows 8.1 x64``` its fine (also ```1.10.1```).

**Comment by sgmitrovic** [comment]
We had a couple of async fixes recently. No crashes on Mac any more:

1.11.0-edge.cde4fa201b7a1ec21d3197e2d809937d235004fb
