### ISSUE TITLE
Server's analysis.getNavigation request is not implemented

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#23640]
The specification defines the analysis.getNavigation request, but the current implementation of server does not implement it. This is needed in order to scale to large files.

**Comment by scheglov** [comment]
Started
https://codereview.chromium.org/1232683003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/d7c2f4550b64a460acc9785eba14a16a66a44707
