### ISSUE TITLE
Spec is too lenient in allowing map literals in expression statements.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23642]
Section 17.2 (Expression Statements) says:

> An _expression statement_ consists of an expression other than a non-constant map literal (16.8) that has no explicit type arguments.
> _The restriction on maps is designed to resolve an ambiguity in the grammar, when a statement begins with `{`._

This is insufficient to resolve the ambiguity, since it permits a construct like `{}[0];` to be parsed either as a single expression statement, or as the block statement `{}` followed by the expression statement `[0];`.  It also permits things like `{1:2}[3];` and `{}..toString()`, which are considered syntax errors by the analyzer, VM, and dart2js.

The way the analyzer, VM, and dart2js seem to be interpreting this spec text is that an expression statement may not _start with_ a non-constant map literal that has no explicit type arguments.  I think the spec text should be changed to reflect this interpretation.

**Comment by eernstg** [comment]
No milestone now: This will be taken into account as part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).

**Comment by srawlins** [comment]
I think this was fixed. The text now prohibits an expression statement from starting with a `{`, rather than starting with a "non-constant map literal."

```latex
\LMHash{}%
The expression of an expression statement is not allowed
to begin with a \lit{\{}.
\commentary{
This means that if some source text could otherwise be parsed as an expression
followed by a \lit{;}, then this grammar production does not apply
when the expression starts with a \lit{\{}.
}
\rationale{
The restriction resolves an ambiguity while parsing where a
\lit{\{} can start either a block (\ref{blocks}) or
a map literal (\ref{maps}).
By disallowing the latter from starting an expression statement,
the parser does not need to look further ahead
before deciding that it is parsing a block statement.
}
```
