### ISSUE TITLE
Intl: US time format not correct

### ISSUE THREAD

**Issue by jorgjanke** [dart-lang/sdk#23648]
According to the documentation, 
new DateFormat("Hm", "en_US") -> 12:08 PM
new DateFormat.yMd().add_Hm() -> 7/10/1996 12:08 PM
(which is expected behavior).

Unfortunately, instead of the pattern "h:mm s" or "K:mm s" the result is "HH:mm" (i.e. 24h)

test("us locale", () async {
String localeName = "en_US";
await initializeDateFormatting(localeName, null);

DateFormat ymd = new DateFormat.yMd(localeName);
expect(ymd.pattern, equals("M/d/y"), reason: "${ymd.format(new DateTime.now())}");
DateFormat hm = new DateFormat.Hm(localeName);
expect(hm.pattern, equals("h:mm a"), reason: "${hm.format(new DateTime.now())}");
DateFormat ymd_hm = new DateFormat.yMd(localeName).add_Hm();
expect(ymd_hm.pattern, equals("M/d/y h:mm a"), reason: "${ymd_hm.format(new DateTime.now())}");
});
00:00 +0 -1: us locale

Expected: 'h:mm a'
Actual: 'HH:mm'
Which: is different.
Expected: h:mm a
Actual: HH:mm
^
Differ at offset 0
00:10

Note that using new DateFormat.jm(); is not the solution as that would hardcode the 12h format.
My assumption is that the command is supposed to look up the correct format from the locale data. There, for the US, it is correctly "h:mm a".

(initially directly logged in tntl, but seems that bugs should be logged here)

**Comment by kevmoo** [comment]
No. These should be logged in the intl package.

https://github.com/dart-lang/intl/issues/70
