### ISSUE TITLE
Intl: Multiple Translations

### ISSUE THREAD

**Issue by jorgjanke** [dart-lang/sdk#23649]
If in your application you import a package, which is translated 
and in your application create a translation, you get:

Duplicated library name 'messages_all'.
library messages_all;

when using the generate_from_arb functionality.
This applies also to the library in the translated files, e.g. messages_es

The cause is that in generate_localized.dart, the library name(s) are hardcoded.

generate_from_arb.dart allows to specify a file prefix, e.g.
--generated-file-prefix=base-

I suggest to use the file prefix also for the library names.

(originally filed directly: https://github.com/dart-lang/intl/issues/9)

**Comment by kevmoo** [comment]
Having the issue on the intl package is the right place to start.
