### ISSUE TITLE
An exception without stack trace.

### ISSUE THREAD

**Issue by Tigerfyj** [dart-lang/sdk#23656]
I got an exception at the last line of _microtaskLoop() in schedule_microtask.dart. The message and stack track of the exception are null.

My code likes like:
```
final _results = <Future>[];
void callback1(P1 a, P2 b) {
  Future f = a.prcess(b);
  _results.add(f);
}

Future callback2() {
  return Future.wait(_results);
}
```

The callback2() didn't throw any exception. But the exception happens when the next microtask tried to run after callback2() finished.

The exception is gone after add eagerError=true. There isn't any exception after the change.
```
return Future.wait(_results, eagerError : true);
```

**Comment by floitschG** [comment]
On which platform did this happen? VM or dart2js (or both)?
Do you have a repro?

**Comment by Tigerfyj** [comment]
Both VM and dart2js. I don't have a repro.

**Comment by jakemac53** [comment]
Just hit roughly the same bug. Here is an example repro https://dartpad.dartlang.org/fa6b0fd4310cfa3b731a3c6733a020c6. If you pass an iterable to Future.wait which throws synchronously when its called (lazily), then you get two exceptions, one which is the actual error and one which has a null error/stack trace which you can't handle via try/catch.

**Comment by jakemac53** [comment]
cc @floitschG this seems like a bug in `Future.wait`

**Comment by floitschG** [comment]
I found the bug in the provided example. I hope it's also representative for the original report.
Will submit a fix soon.
