### ISSUE TITLE
Pub: support some form of authorization when downloading packages

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/sdk#23652]
Our organization has setup a fork of the [pub repository](https://github.com/dart-lang/pub-dartlang-dart) for our private/non-OSS packages. 

The current authorization flow for publishing packages to it works, however after perusing though the code, it looks like nothing similar exists for downloading packages with a `pub get`.

It would be great if pub could support authorization on a per-server basis.

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/pub#1327
