### ISSUE TITLE
Analyzer leaks memory if performAnalysisTask not called

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23651]
See: https://github.com/dart-lang/dart-services/commit/609151fb3823fbc5e5daa7725de739ad701957b2

Before this change (calling performAnalysisTask until it returns that there is no more work to do) was introduced, the analyzer slowly leaked memory, degrading performance.

With this change the memory usage is stable over 250k calls to compute errors and warnings.

**Comment by devoncarew** [comment]
assumed stale
