### ISSUE TITLE
Provide visibility into what's keeping the VM alive

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23655]
A frequent problem with complex asynchronous code is making sure the VM terminates once the user's code has finished running. This is usually caused by some unreleased resource, unclosed connection, or uncanceled timer, but it's very hard to track down what exactly is the cause.

@johnmccutchan mentioned that this could be done by surfacing the list of open ports, along with the handlers associated with those ports.

**Comment by zoechi** [comment]
The debugger in the observatory got a view the for event queue added recently which might help.

**Comment by nex3** [comment]
The event queue isn't relevant unless there's code actively running, which isn't the situation I'm running into. My problem is that all the code has stopped running, but the VM still hasn't terminated—I want to be able to start up the Observatory and see why.

**Comment by johnmccutchan** [comment]
@nex3 This CL will give a per isolate list of open ports- https://codereview.chromium.org/1189543003/

**Comment by nex3** [comment]
This looks great, thanks!
