### ISSUE TITLE
Improve logging package

### ISSUE THREAD

**Issue by jimbeveridge** [dart-lang/sdk#23653]
I've been using logging to debug Mojo packages and there are some refinements that would be very helpful. These features (except 5) are all part of Google's standard C++ logging module, [glog](https://github.com/google/glog).

1. Need a way to disambiguate log entries from a multi-isolate app. Getting the name of the current app is a challenge in Mojo, so the logging library can't do this automatically. Maybe make the app name an optional static member of the logging class?
2. Add support for accepting a filter of one or more RegEx expression that enumerate logging levels on a per-name basis, similar to glog.
3. It should be possible to globally set the log level across all isolates. Although this should be easy using environment variables, Mojo does not support dart:io, so that's problematic for Mojo apps. Maybe Mojo apps need to have a single source file that specifies the RegEx filter that all related Dart Mojo apps can include and pass to the logging package.
4. Logs going to the console should be color coded (yellow for warn, red for severe.)
5. Nice to have - log to an HTML window, including color support. The reason this is useful is that the HTML window can clear for each new run, making it much easier to see where new runs begin.

**Comment by sethladd** [comment]
I think we should move this issue over to https://github.com/dart-lang/logging/issues

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/logging#22

**Comment by kevmoo** [comment]
@sethladd https://github-issue-mover.appspot.com/ is your friend!
