### ISSUE TITLE
Dart2js loses type parameter on `new Future<int>.sync(()=>42)`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23650]
Example code (https://dartpad.dartlang.org/945cf4705aba3041dab9):
```dart
import "dart:async";
main() {
  var f = new Future<int>.sync(()=>42);
  print(f is Future<String>);  // true
  print(f.runtimeType);  // _Future, not _Future<int>
}
```

The VM behaves correctly, and it appears dart2js and the VM are running the same code, so it looks like a bug in dart2js.

**Comment by karlklose** [comment]
Type variables in factories using try-catch are not working correctly. It looks like we allocate a box but forget to initialize it.
