### ISSUE TITLE
Pub doesn't create packages/ symlink in tools/

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#23657]
The [tools](https://www.dartlang.org/tools/pub/package-layout.html#internal-tools-and-scripts) directory of a package should include a symlink to `packages/` (it's an [entrypoint directory](https://www.dartlang.org/tools/pub/glossary.html#entrypoint-directory)).

> ### Entrypoint directory
>
> A directory inside your package that is allowed to contain Dart entrypoints. Pub will ensure all of these directories get a “packages” directory, which is needed for “package:” imports to work.
>
> Pub has a whitelist of these directories: benchmark, bin, example, test, tool, and web. Any subdirectories of those (except bin) may also contain entrypoints.

My package lacks this symlink in `tools/` and whatever I call (`pub get`, `pub upgrade`, ...), nothing changes that.

This is either a documentation issue (is there a way to force pub to check symlinks and create if necessary? is `tools/` deprecated?) or a bug.

Pub version: 1.10.1
OS: Mac OS X 10.10.3 (14D136)

**Comment by a14n** [comment]
`tool/` instead of `tools/` should work.

**Comment by filiph** [comment]
Gah! Yes. Yes, it does. Sorry.
