### ISSUE TITLE
Throw statement lost message and stack trace

### ISSUE THREAD

**Issue by alhaad** [dart-lang/sdk#23654]
/cc @johnmccutchan 

I am facing a scenario where..

Analogous code in our repository:
Future abc() async {
  // throw "error works";
  var a = await _futureReturned();
  throw "error doesn't work"; // This throw looses error message and stack trace.
}

Have not been able to isolate this to a simpler example.

**Comment by johnmccutchan** [comment]
@mhausner @iposva-google

**Comment by jimbeveridge** [comment]
This bug appears to have been caused by trying to rethrow the exception with "throw e" instead of using "rethrow". This bug can be closed.

**Comment by mhausner** [comment]
Thanks for the update
