### ISSUE TITLE
dart2js: bug in world invariant?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23664]
The [dart docs](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/world.dart#L49) for `world.subtypeOf` and `world.subclassOf` indicate that the result would include the given class as part of the results if it is live.

In a simple program like:
```dart
class A {}
main() => new A();
```

If I query the world for subtypes-of A (or subclasses of A) I get an empty set. 

Seems like a bug in `populate`, but I wanted to first confirm. @johnniwinther - do you agree?

**Comment by johnniwinther** [comment]
I sound like a bug.
