### ISSUE TITLE
html_dartium.dart file is too big

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23665]
The html_dartium.dart file is super big:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dartium/html_dartium.dart

There are a number of problems with this:

* my computer crashes often if I try to edit it in webstorm, I think other people will have this as well
* I can't easily make a change in github. For example, if I see a one line typo in the doc, wouldn't it be cool, if people could just edit it on github, and create a PR really quick ? 
* I can reference to a certain line, for example, I just wanted to make an issue, that line number 12581 generates an infinite loop if the innerHtml of an custom element is changed in the created callback. I think it is very convenient if the user can directly navigate to such a specific line in the dart:html library.

**Comment by alan-knight** [comment]
I agree it's much too big, and painful to work with, but I don't see us doing anything about in the near future. The file is generated, so a pull request or editing that file wouldn't work anyway. And breaking it up would require significant changes to the generation code. Referencing line numbers would be handy, but you can reference by class/method/function name and it's not too bad. And if WebStorm, or your computer, can't handle a 50K line file in 2015, that's their fault ;-)

**Comment by kasperpeulen** [comment]
> The file is generated, so a pull request or editing that file wouldn't work anyway.

But what about if you want to contribute to dart:html docs?

**Comment by kasperpeulen** [comment]
> And if WebStorm, or your computer, can't handle a 50K line file in 2015, that's their fault ;-)

I don't think we can blame Webstorm anymore. I'm trying it now, and it seems like Dart Analysis is going crazy. Even if I just try to edit some doc.

**Comment by alan-knight** [comment]
I'm OK with blaming the analyzer :-)

Right now I don't know how contributing to dart:html docs would work. Or rather, I doubt there's a way that would work. There's a mechanism there, at least I think that's what the DocsEditable annotation is for. But I don't think it's been verified to work in quite a while, and would need some work. The mechanism to pull out MDN comments was abandoned. This would be simpler, but still not trivial to make sure it's reliably not throwing away the comments when the file is regenerated.
