### ISSUE TITLE
dartdocgen can't cope with dart:sky

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#23668]
I tried to use dartdocgen to generate documentation for the `sky` package, but the tool ran into a number of errors:

```
Error: Library not found 'dart:sky'.
Error: Not a compile-time constant.
  900: const Color(0xFF263238),
       ^^^^^^^^^^^^^^^^^^^^^^^
```

Eventually, the tool failed completely with the following message:

```
Error: Failed to create mirror system.
```

Presumably the problem is that dartdocgen doesn't know about the `dart:sky` library and is therefore unable to process packages that use it.

@sethladd @alan-knight

**Comment by abarth** [comment]
The way dartanalyzer solves this problem is with a --url-mapping command line flag.

**Comment by alan-knight** [comment]
dartdocgen, which uses the dart2js compile-time mirrors, is deprecated in favour of the not quite ready yet dartdoc, which uses analyzer and thus should be able to use the --url-mapping flag. @keertip

**Comment by sethladd** [comment]
Thanks for the report, @abarth. Known issue, and won't be fixed in dartdocgen.

I'll open a bug to support adding `--url-mapping` to the new dartdoc.

https://github.com/dart-lang/dartdoc/issues/599

**Comment by sethladd** [comment]
Closing as "won't fix"

**Comment by abarth** [comment]
Thanks!

**Comment by keertip** [comment]
dartdoc does use the analyzer, but currently there is no support to specify command line arguments for the analyzer.

**Comment by abarth** [comment]
If dartdoc can cope with dart:sky, I'll happily be a dogfooder of dartdoc.  :)
