### ISSUE TITLE
Least upper bound computation is not tested for F-bounded polymorphic types

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23663]
Prior to 13c3c10f22bc1e4432dc52e66838b3339d9a588b, analyzer's least upper bound computation only worked on interface types; for all other types, it computed a least upper bound of "dynamic".

As of 13c3c10f22bc1e4432dc52e66838b3339d9a588b, I believe least upper bound computation is correct except for two cases:
- Type parameters incorporating f-bounded polymorphism (untested)
- Least upper bound of two function types currently always yields "Function".

**Comment by munificent** [comment]
Since #23381 covers the function type case, I'm going to retarget this bug to just be about the remaining case and adjust the title accordingly. Let me know if that's not OK. :)

**Comment by keertip** [comment]
Will not fix, closing issue.
