### ISSUE TITLE
error: "The class does not have a default generative constructor error"

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23661]
I get the error: 

> The class 'PolymerElement' does not have a default generative constructor.

I really don't see what I'm doing wrong, I think that at least the error should be improved. Because I have no clue what is meant with the error.

It seems that if I remove the mixin, the error disappears. 

``` dart
import "dart:html";

class WebElement {
  final HtmlElement element;

  WebElement(String tag, [String typeExtension]) :
    element = new Element.tag(tag, typeExtension);

  WebElement.tag(String tag): this(tag);

  WebElement.from(this.element);

}

class PolymerElement extends WebElement {
  PolymerElement(String tag, [String typeExtension]) : super(tag, typeExtension);

  PolymerElement.from(HtmlElement element) : super.from(element);
}

class PaperItem extends PolymerElement with Behaviour {
  PaperItem() : super("paper-item");
}

abstract class Behaviour {

}
```

see also: https://dartpad.dartlang.org/a4e915e97c91ae746936

**Comment by kasperpeulen** [comment]
the quick fix, changes the code in this way:
```
class PaperItem extends PolymerElement with Behaviour {
  PaperItem() : super("paper-item"), super('');
}
```

which doesn't seem to solve the problem.

**Comment by kasperpeulen** [comment]
I see that the bug in dartium is actually very helpfull:
> cannot generate an implicit mixin application constructor forwarding to a super class constructor with optional parameters; add a constructor without optional parameters to class 'WebElement&PolymerBase' that redirects to the constructor with optional parameters and invoke it via super from a constructor of the class extending the mixin application
class PolymerElement extends WebElement with PolymerBase, HtmlElementMixin {

can we get the same error in the analyser ? 

Do I understand correctly, that this is the workaround:
```dart
import "dart:html";


class WebElement {
  final HtmlElement element;
  
  WebElement(String tag, [String typeExtension]) :
    element = new Element.tag(tag, typeExtension);
  
  WebElement.from(this.element);
  
  void appendToBody() {
    element.text = "hello";
    document.body.append(element);
  }
}

class PolymerElement extends WebElement {
  PolymerElement(String tag, [String typeExtension]) : 
      super(tag, typeExtension);
  
  PolymerElement.tag(String tag) : super(tag, null);
 
  PolymerElement.extension(String tag, String typeExtension) :
      super(tag, typeExtension);
  
  PolymerElement.from(HtmlElement element) : super.from(element);
}

class PaperItem extends PolymerElement with Behaviour {
  PaperItem() : super.tag("paper-item");
}

abstract class Behaviour {
  
}

main() {
  new PaperItem()..appendToBody();
  new PolymerElement("paper-item")..appendToBody();
}
```

https://dartpad.dartlang.org/c8ea6bcbc5b4ea6e1b1e

**Comment by bwilkerson** [comment]
Yes, we definitely need to improve the error message.

We also need to fix the quick fix. It shouldn't suggest inserting a super initializer when there's already a super initializer.
