### ISSUE TITLE
setting innerhtml in created callback generates infinite loop

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23666]
see this dartpad, to reproduce my problem:
https://dartpad.dartlang.org/0a21ce69ee45c3772d03

I think this is what happens. When you set the innerhtml of an custom element, then in line 12581 of html_dartium.dart the element is created again:

``` dart
      contextElement = _parseDocument.createElement(tagName);
      _parseDocument.body.append(contextElement);
```

So because it is created again, the created callback is called of that element, and in that callback the innerhtml is set, and then the cycle repeats indefinitely...

**Comment by alan-knight** [comment]
So this is directly below a comment that says " Workaround for Chrome bug 229142", which says it was fixed in Feb 2014. So it seems like we should just be able to change that.

**Comment by kasperpeulen** [comment]
@alan-knight 

I think the workaround was adding this code:
https://github.com/dart-lang/sdk/commit/647d73af0fa81d266414dd1f47edc3be69065306

But the problematic part is I think slightly below. So I set the innerhtml of some element, and this element is added to _parseDocument in this line:

https://github.com/dart-lang/sdk/blob/647d73af0fa81d266414dd1f47edc3be69065306/tools/dom/templates/html/impl/impl_Element.darttemplate#L1249

**Comment by alan-knight** [comment]
Ah, right. So this is actually a bit tricky. When you call innerHtml it wants to sanitize the text. It does that by creating a document fragment. But the document fragments wants a context element to put things in, and it can't use the original one or it would be directly modifying the DOM, bypassing the sanitization. So it creates a new one with the same tag... It's not obvious how to avoid this in general. I talked to the Polymer guys, and it might be a reasonable long-term solution that for custom elements we create the context as the first superclass that's a normal element.

For shorter term workarounds there's the obvious "don't do that" in the constructor, wait until later.

Another possibility. Presumably when you're setting this HTML in the constructor it's known and trusted HTML, and you don't really want it sanitized. I just committed something this morning that adds a known null sanitizer, and if you use it it bypasses the fragment creation completely. So you could write it as

     setInnerHtml("This doesn't cause an infinite loop", treeSanitizer: NodeTreeSanitizer.trusted)

See https://codereview.chromium.org/1154423009/ 

But this won't be in 1.11, so it'll take a while to be generally available.

**Comment by kasperpeulen** [comment]
@alan-knight thanks, this  NodeTreeSanitizer.trusted is something I would like to use in many cases. I tried it with 1.12 dev, but I couldn't get it to work:
https://gist.github.com/kasperpeulen/efc88f08c1ac97af047e

**Comment by alan-knight** [comment]
That works for me in bleeding edge. Which 1.12 dev are you using? And if it
fails, how does it fail. Does NodeTreeSanitizer.trusted exist in that
version?

**Comment by kasperpeulen** [comment]
@alan-knight I use 1.12.0-dev.3.1. It says NodeTreeSanitizer.trusted doesn't exist, however, Webstorm doesn't give an error, and I can see that it exist if I go to the decleration of NodeTreeSanitizer.trusted in Webstorm.

If I run it using webstorm, I get this error (or if I do pub serve):
```
Exception: No static getter 'trusted' declared in class 'NodeTreeSanitizer'.

NoSuchMethodError: method not found: 'trusted'
Receiver: Type: class 'NodeTreeSanitizer'
Arguments: [...]
```

If I do pub version I get:
`Pub 1.12.0-dev.3.1`

I'm confused ...

**Comment by alan-knight** [comment]
I can't think what else it is except something confused with versions. I installed 1.12.0-dev.3.1 using Homebrew on a Mac, ran the appropriate version of pub serve against it and it works, ran pub build and it has it in the compiled code. With WebStorm I find sometimes I have to check my project settings for which version I'm using, then quit and restart to force it to stop any running server bits. But I can't see how a pub serve reporting that version wouldn't find it. At least not without odd environment variables or command-line flags or something telling it to look in the wrong place.

**Comment by kasperpeulen** [comment]
I don't understand it as well... I also use homebrew, just installed the new version, but still nothing.

it works if I add the code to my project, like this:
https://dartpad.dartlang.org/d1261fd870faad2e6972
so I guess it must be something strange going on in my specific case

It is really strange ... the analyser and webstorm are clearly indicitating that the code you added is there...  well, I guess this is only something I can fix myself, probably just need to reinstall/reset some things, thanks for all your help.

**Comment by matanlurey** [comment]
Dartium is gone.
