### ISSUE TITLE
adding test coverage for CSP-mode in IE

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23662]
CSP is mainly used for chrome extensions, so we mainly test it there. It would be good to add coverage in our bots testing CSP on IE as well.

As @floitschG pointed out in https://codereview.chromium.org/1189983004/, it might be enough to just do a subset of the tests. Possibly the language suite?

@ricowind @whesse - would you be able to help us set this up? If not, maybe you could point me in the right direction (I'm not sure where the annotated_steps.py script lives now).

**Comment by athomas** [comment]
I assume this is obsolete.
