### ISSUE TITLE
Webstorm integration: Code completion for keywords not working at program locations occuring immediately before a variable identifier.

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#23679]
**What steps will reproduce the problem?**
1) Open webstorm and start a new Dart - Console Application project
2) Change the main function to the following: (The empty lines are there for clarity)

main(List<String> arguments) {

  int variable = 42;

  42;

  variable;

}
3) Place the cursor at the empty line above 'int variable = 42;'
4) Type a prefix of some keyword (e.g. nul, con, bre)
5) Repeat step 3 and 4, but place the cursor above 
'42;' and 'variable;'

**What is the expected output? What do you see instead?**
Expected:
Code completion should suggest the completion of the chosen keyword at every empty location inside inside the function

Actual:
Code completion does not work at the program locations before 'int variable = 42;' and 'variable;'.
![screenshot - 19-06-2015 14_02_17](https://cloud.githubusercontent.com/assets/12271154/8253052/05b4e374-168c-11e5-8333-3a26b422e711.png)

**What version of the product are you using?**
Webstorm: 10.0.4
Dart-SDK: dart-1.11.0-dev.5.4

**On what operating system?**
Windows 7 SP1(64bit)

**Please provide any additional information below.**
The issue can be reproduced with other types of variables (tested with: local, library, instance).
The issue has been reproduced on mac, using a previous version of webstorm, and using a previous version of the SDK.

**Comment by ricowind** [comment]
@jwren @danrubel

**Comment by jwren** [comment]
Closing code completion support has been recently replaced in IntelliJ by the Dart Analysis Server integration work which was released today in EAP (http://blog.jetbrains.com/webstorm/2015/07/webstorm-11-early-access-program/).
