### ISSUE TITLE
jsinterop: Need examples

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#23678]
* how to handle APIs that take literals as arguments
* example of using the d3 library

**Comment by kevmoo** [comment]
@kwalrath FYI: the next dev build (likely 1.13-dev.7, likely tomorrow) will have what we need here.

**Comment by kevmoo** [comment]
FYI: I've created examples here https://github.com/dart-lang/sdk/tree/master/pkg/js/example

Would LOVE docs updated on the site for this.

**Comment by mit-mit** [comment]
@kwalrath, is this now tracking adding docs on dartlang.org? If so, perhaps we can move the issue to the tracker there? Or is this tracking code samples that would be in the actual SDK?

**Comment by kwalrath** [comment]
https://github.com/dart-lang/www.dartlang.org/issues/1510 is (essentially) tracking js doc changes, so I think we can close this bug unless we expect more samples.

**Comment by mit-mit** [comment]
@kevmoo, are you aware of any last minute samples additions, or can we close this?

**Comment by kevmoo** [comment]
Closing.
