### ISSUE TITLE
customEvent.detail in dart is sometimes null, where the the js version contains information

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23680]
The custom (gesture) events that are fired by polymer.js 1.0 are not properly decoded to dart objects.
https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures

More specifically, the dart object looses all the information in the `detail` field:

<img src="https://cloud.githubusercontent.com/assets/1035299/8255959/e9ce3f44-16a3-11e5-9f78-6f0de2fc6bf1.png" width="50%">

<img src="https://cloud.githubusercontent.com/assets/1035299/8256007/47fa305a-16a4-11e5-83d0-065a645b7be8.png" width="50%">

In `html_dartium.dart` (line 7638-7641) I read:

``` dart
// Only try setting the detail if it's one of these types to avoid
// first-chance exceptions. Can expand this list in the future as needed.
if (detail is List || detail is Map || detail is String || detail is num) {
```

So maybe the time has come to expand this ? I would hope that I can properly work with customevents that polymer js is firing.

**Comment by kasperpeulen** [comment]
@kevmoo I would think this is Area-HTML.

**Comment by kevmoo** [comment]
@kaendfinger `Area-NONE` is flagged by our tools to ensure we can triage quickly. It should be removed when an area is assigned.

**Comment by jakemac53** [comment]
@kasperpeulen fwiw in the newer version Polymer is wrapping CustomEvent objects to get around this issue.

**Comment by sigmundch** [comment]
FYI - I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/19315, see also https://github.com/dart-lang/sdk/issues/20648.
