### ISSUE TITLE
Please merge these VM revisions into 1.11

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#23681]
@ricowind @whesse @kasperl @crelier 
> If this is a request to merge to stable please change the MergeToDev label to MergeToStable
In the new setup it is not apparent to me whether 1.11 is on stable or dev so I set both labels.

This includes an implementation of "int modInverse(int modulus)" similar to "int modPow(int exponent, int modulus)". This fixes issue 23502.

CLs and corresponding hashes:
https://codereview.chromium.org/1174513004/
https://codereview.chromium.org/1177873002/
https://codereview.chromium.org/1177063002/
https://codereview.chromium.org/1188843004/

f6f338ce67eb8801b350417baacf6d3681b26002
90315a1694a40ba738a5197295b0c1a7b9d03c5f
9edc6e5a6d31ec926be7743c06f500f125a04b54
16bb52b88ded9da50508d72bf86825b243ad8258

Prevent a potential conflict between observatory data collection and concurrent sweeping. This can cause mark bits being changed prematurely while the concurrent sweeper is running. Fixes issue 21620.

CLs and corresponding hashes:
https://codereview.chromium.org//1181943002
https://codereview.chromium.org//1179973005

1009d587de88ec04a66cd60409aba3a281e21f64
3ce2b95070a26d7aa5173673095d49e0494c4151

**Comment by ricowind** [comment]
Fixed in ec79b1622479c2b21d176aa9fa1e05b30eb4c676
