### ISSUE TITLE
Whether there is at least some correlation between the number of stars on Github and Dart popularity?

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#23687]
Most popular projects tend to recruit a very large number of stars on Github (especially at first).
Dart was moved at Github not so long ago but for some reason Dart has a very small number of stars.

Does this means that it is practically no one uses or does not see any prospects or there are other reasons for the lack of interest?

Or maybe exists a recommendation do not to vote for the Dart main repository to not to raise hype ahead of time?

P.S.
This issue is very important for me because Microsoft Typescript project also are not so popular but it has **5631** stars on Github.

5631 vs 224 is very big difference.

**What happened with Dart popularity?**

Or this is a temporary set of circumstances, and I can ask that question later when everything will fall into place?

**Comment by kasperpeulen** [comment]
I think a large amount of github stars come if a project is in a hype. Dart hasn't been hyped since it is on github. A couple of time ago, there was some hype about the dart's sky sdk for android, and in that 
period it got allmost 2000 stars: https://github.com/domokit/sky_sdk. 

But, no, dart is not very popular, you've been around along enough in the dart community to know it has never been really popular. Typescript is also not used very much, but gets a bit more attention lately. 

As you can clearly see, from the github repos, dart-sdk has much more daily commits and much more contributors than Typescript has. And then we don't even count repos like dart-style, polymer-dart, angular, dartdoc, fletch, sky, dev_compiler, dart-services etc. 

Typescript tries to solve an easier problem, and does a great job in solving this problem, but is clearly not as ambitious as dart is.

**Comment by mezoni** [comment]
@kasperpeulen
Thank you for clarification but I still does not understand: "Why are so small amount of stars?"
[Dart on Google+](https://plus.google.com/+dartlang) has  26260 members.
[Dart community on Google+](https://plus.google.com/communities/114566943291919232850) has  6841 members.

But Dart itself are a software and amount of the people who have interest in Dart as an open source software has only 227 persons?

40 persons from them are developers.
227-40=only 187 person with a some interest to an ambitious project with a lot of commits?

>> And then we don't even count repos like dart-style, polymer-dart, angular, dartdoc, fletch, sky, dev_compiler, dart-services etc.

They are not a Dart SDK. Why you tell about them I cannot understand.

Even if the Google does not want to develop them on the different Github accounts but want to place then on the same account on Github then this does not means that you should mention about them as about the argument that they are also part of Dart SDK.

Or you want to say that the Entity Framework are also the part of Microsoft .NET Framework only because it are developed by the Microsoft and it intended to use only with Microsoft .NET Framework?
I don't agree with such kind of conclusions.

I don't think that dart-style, polymer-dart, angular, dartdoc, fletch, sky, dev_compiler, dart-services etc arfe part pf Dart SDK (which are only the subject of this issue).

P.S.

For me it is not very reassuring figure (the absence of any case of interest from other developers with Github accounts) in the sense that no one takes Dart SDK seriously and hardly anyone will do a serious contribution into that project.

**Comment by kasperpeulen** [comment]
All the repos are listed are part of the dart eco system, and all the commits and contributors in all of those repos show how much google is investing in dart. That was the only point I was trying to make.

> For me it is not very reassuring figure (the absence of any case of interest from other developers with Github accounts) in the sense that no one takes Dart SDK seriously and hardly anyone will do a serious contribution into that project.

Okay, so you have answered your own question, great!  :+1:  Dart is not popular enough to your taste, that is fine. Maybe typescript fits your better, who knows, try it out. Can we mark this issue as resolved ?

**Comment by mezoni** [comment]
>> Okay, so you have answered your own question, great!  :+1: Dart is not popular enough to your taste, that is fine. Maybe typescript fits your better, who knows, try it out. Can we mark this issue as resolved ?

No, and no again. Because I ask not about (as you say) `dart eco system` but I ask about open source project called `Dart SDK` which are in this repository (and was moved here no so long ago).
All other projects are not related to Dart SDK so I cannot take all of them as an answer to question.

Dart SDK was moved on Github but where the crowd of willing to help develop Dart SDK that they will use for yourself in the future?

>> Okay, so you have answered your own question, great!
Unfortunately I don't answered my own question.
Rather on the contrary, your statements of such kind brought me even more confusing.

Dart is not popular enough not by my taste (this is only your conclusion). Dart is not popular enough by the Github statistics.
And this was a reason to create this issue.

Dart SDK rule the roast (was moved to Github) and at the same time Github statistics displays the results that not who does not have interest.
In the opposit, I have an interest.
But I am afraid that I will spend wasting their time on that what by the statistics is not popular.

Statistics are not a my taste (as you love to argue when exists lack of good results).

Statistics is a stubborn thing. And your arguments was, unfortunately, not based on statistical data but they are mostly was an arguments that `if it not in your taste then you can don't use it but use something other`.

**Comment by sgjesse** [comment]
I don't think this discussion is relevant in the issue tracker.

**Comment by mezoni** [comment]
>> I don't think this discussion is relevant in the issue tracker.

OK. This is not a right place for such question.
I am sorry.
Do you recommend that better to ask such question in the mass media?
