### ISSUE TITLE
On the page "Contributing" I read that "The source code of Dart follows the: Dart style guide". Should be filled the issue on each found deviations from this rule in Dart SDK?

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#23690]
According to the [Contributing](https://github.com/dart-lang/sdk/wiki/Contributing):

Coding style
The source code of Dart follows the:
Google C++ style guide
Dart style guide

Does this means that each line of source code in Dart SDK that does not follow these rules is an oversight of Dart Team?

If not, then what means the statement **The source code of Dart follows Dart style guide**
And what will means if the source code of Dart does not follows Dart style guide?

Or this is normal and these rules can be not followed only by Team members?

**Comment by sgjesse** [comment]
The code in the Dart SDK have developed over a number of years, and style guides have changed over time. In general new code should follow the style guides. We don't go update all files to follow the current style guide, and when editing a file which for some reason follows a different style it is sometimes better to keep that style to not pollute the diff.
