### ISSUE TITLE
CPS: crash in compilation of constructor super initializers---no selector

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#23691]
tools/test.py -mrelease --host-checked --cps-ir -cdart2js -rd8 pkg/js_ast/test/printer_callback_test

This test crashes because it hits a superclass constructor call in an initializer list and the superclass constructor has a null selector.

@asgerf @karlklose

**Comment by asgerf** [comment]
https://codereview.chromium.org/1200823002/
