### ISSUE TITLE
Please merge revision for gcd and compiler fix into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#23696]
@ricowind @whesse @kasperl @crelier @sgmitrovic 
This implements gcd for the int class and fixes an optimizer problem when dealing with big integers.

Changes:
https://codereview.chromium.org//1199513003/
https://codereview.chromium.org/1198993003/
https://codereview.chromium.org/1199593004/
https://codereview.chromium.org/1197263002/

Hashes:
a192ef4acb95fad1aad1887f59eed071eb5e8201
d9da805f07feb8b613832a5820c875f5b8703141
d0d5185550d5b41af75ec6e514c484da4abbf2b5
e91b99b66d7cce90ec0784e01128834d861b9d82

**Comment by ricowind** [comment]
These changes don't merge cleanly

**Comment by sgmitrovic** [comment]
A clean merge of changes listed above:
https://codereview.chromium.org/1204443004/

(Unfortunately not tested because of issues with pkg_tested/pub)

**Comment by ricowind** [comment]
See also my earlier mail on the subject, but you can set managed to False
in you .gclient file, after which gclient sync will work

I build this myself, and it builds, tests pass in release mode

Landing now

Cheers,
Rico

**Comment by ricowind** [comment]
merged
