### ISSUE TITLE
VM optimizing compiler : crash in range analysis

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#23693]
python tools/test.py -t120 corelib/big_integer_arith_vm_test

/sources/git-two/sdk/runtime/vm/flow_graph_range_analysis.cc:627: error: expected: min.ConstantValue() <= new_min.ConstantValue()

**Comment by sgmitrovic** [comment]
Simple testcase:
--optimization-counter-threshold=10
main() {
  for (int i = 0; i < 10; i++) {
    foo();
  }
}

foo() {
  var x = 12345678901234567890;
  var m = 10000000000000000001;
  return x.modInverse(m);
}

**Comment by sgmitrovic** [comment]
To reproduce run with --guess_other_cid  (default is false). It is unclear if 'guess_other_cid' optimization is to blame, but range analysis should be more robust.

**Comment by fsc8000** [comment]
I'll take a look.

**Comment by fsc8000** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/5daa5646ef8e09739778720aa27a89a26bd70aeb
