### ISSUE TITLE
CPS: crash in compilation of superclass initializers---mixin application class

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#23692]
tools/test.py -mrelease --cps-ir -cdart2js -rd8 -t60 dart2js_extra/21666_test

This test fails (and it looks like a few others) when walking up the chain of super calls in an initializer list.  It hits a mixin application class as a superclass, whose constructor does not have an AST.  This causes the code to try to call that class's default constructor, but there is no default constructor.

@asgerf @karlklose

**Comment by asgerf** [comment]
This was fixed a while ago, forgot to close it at the time.
