### ISSUE TITLE
Dart docs extends link is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#23695]
Navigate here: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Set

and click on IterableBase under "Extends".  It points to a non-existent IterableBase in dart:core - should be dart:collection

**Comment by sethladd** [comment]
I think this is fixed in the latest dartdoc 

Cc @keertip

**Comment by sethladd** [comment]
This is fixed in the latest dartdoc. Please reopen if not. Thanks for the report!
