### ISSUE TITLE
No docs in code completion

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#23694]
The CompletionSuggestion should have a value for the docSummary and docComplete fields when the source code has documentation, but they don't. For example, asking for code completion at the end of the next-to-last line in this sample code will return null (missing) fields:

    /// This is a dummy method.
    ///
    /// But I'm no dummy!
    noDoc() {
    }

    main() {
      noDo
    }

**Comment by devoncarew** [comment]
I ran into this as well; it would be great to be able to preview dartdoc info when completing methods.

**Comment by scheglov** [comment]
I remember that:

1. In Dart Editor we decided to use `analysis.getHover` to get documentation.

2. Couple months ago we discussed this again and... I don't remember the resolution, but I remember that @lukechurch was concerned about amount of data.

I'm also concerned about amount of work we would need to perform to extract documentation for each CompletionSuggestion.

Also, could one of the clients remind me what is, or what do they expect to see in `docSummary`?
What's the difference between it and method signature, which can be composed using `element`?
@danrubel , do you remember?

**Comment by devoncarew** [comment]
`docSummary` would I assume be the first markdown paragraph from the dartdoc documentation. The Atom client will likely never use the `docComplete` field. Perhaps that field could be deprecated.

> I'm also concerned about amount of work we would need to perform to extract documentation for each CompletionSuggestion.

Can we implement it, and measure the actual cost? If we do see a significant cost to populating the field, this could be something that clients opt into.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1380223003/

**Comment by scheglov** [comment]
I'm coping this performance difference from the CL.

```
For the first time when we complete top-level elements, such as "Str^" it takes
about 500-600 ms vs. 300 ms without documentation.
For the second and subsequent completions difference is not so high, but still
exists.

For prefixed completions difference is pretty high - 15 ms vs. 3 ms for
stringLiteral.^ completion.
I.e. documentation makes it 5 times more expensive.

I'm not sure that we want to take such performance hit.```

**Comment by scheglov** [comment]
It is still slow to compute and not put into JSON.
So, I'm trying to optimize its computation.
https://codereview.chromium.org/1376473007

**Comment by scheglov** [comment]
Done.
Performance is still not perfect though.

https://github.com/dart-lang/sdk/issues/23694

**Comment by scheglov** [comment]
Err...
https://github.com/dart-lang/sdk/commit/1af7b154af904cf0627708818eb15e9fb5066f8a

**Comment by scheglov** [comment]
It's very slow during switching tabs.
Rolling back...

**Comment by devoncarew** [comment]
Switching to @pq; Phil, let's meet about this - this is the last big item left.

**Comment by pq** [comment]
A bit of profiling has confirmed that caching doc comment contents with elements shouldn't add too much overhead. (Needless to say, this too will benefit from summaries.)

For example, this shows the number of elements, docs and char counts for a flutter app and the flutter lib.  Adds up to ~500k.

![screen shot 2015-12-17 at 2 06 25 pm](https://cloud.githubusercontent.com/assets/67586/11883385/6baf30fc-a4c7-11e5-9d44-95d6e1d4ee6b.png)

**Comment by pq** [comment]
https://codereview.chromium.org/1534043002/

:metal:

**Comment by pq** [comment]
Landed in https://github.com/dart-lang/sdk/commit/1f8eddcc2113ed5a0474520455582066a3ce6aaf.
