### ISSUE TITLE
CPS: Closures look up closed-over constants in the (compile-time) environment, but they're not there

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#23709]
We have lots of Invalid argument(s) failures in the CPS backend.  I only investigated one, but it seems like when it is trying to build arguments to pass to a closure class constructor it is looking up constants from the outer scope in the environment and they're not there.

@asgerf @karlklose @rakudrama @sigmundch

**Comment by rakudrama** [comment]
Obsolete
