### ISSUE TITLE
CPS: Bug in assignment propagation of loop variables

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#23701]
Assignment propagation assumes the tree is in SSA form, but this is not entirely true, because phi assignments have already been linearized. It will occasionally propagate a loop variable past one of its phi assignments.

E.g.

InvokeContinuation k (x1,y1)

Might linearize to:

x2 = x1
y2 = y1
break L

If this definition of y1 is in scope, it will erroneously propagate it into its use above:

y1 = x2 + 1

Yielding this:

x2 = x1
y2 = x2 + 1 (reads wrong value of x2)

(x2 can only be in scope here when the invocation was recursive)

Can be reproduced in dart2js_extra/for_test with this CL patched in https://codereview.chromium.org/1197673003/

@kmillikin

**Comment by asgerf** [comment]
Btw I am working on a solution.

**Comment by rakudrama** [comment]
Obsolete
