### ISSUE TITLE
Running Google Web App in background

### ISSUE THREAD

**Issue by kjha1991** [dart-lang/sdk#23713]
I need to create chromebook app. I have few queries:
- Can app start automatically once device boots and also run in background?
- Does Kiosk apps run in background or only in full-screen?
- If above feature is not possible through app then can we use chrome extensions or google admin console to start application and run it in background?
- If app is running in background, can it perform any task?

**Comment by floitschG** [comment]
These questions don't seem to be related to Dart.
If I were you I would ask on stack-overflow.
