### ISSUE TITLE
Segmentation fault with async functions

### ISSUE THREAD

**Issue by rfqu** [dart-lang/sdk#23710]
following code causes segfault:

f (int value) async {
  try {
    throw value;
  } catch (e) {
    return e+1;
  }
}

test() async {
  const int value=12345;
  Future<int> res= f(value);
  yield res.then((e)=>Expect.equals(value+1, e),
    onError: (e)=>Expect.fail(e)
  );
}

main() {
  test().then((_) => print("done"));
}

>  29357 Segmentation fault      (core dumped) $out/ReleaseX64/dart -c --package-root=$out/ReleaseX64/packages/ $@
Dart VM version: 1.10.1 (Mon May 11 22:46:14 2015) on "linux_x64"

**Comment by sgmitrovic** [comment]
Debug mode asser failure:
/sources/git-two/sdk/runtime/vm/parser.cc:9605: error: expected: innermost_function().IsGenerator() || innermost_function().IsSyncGenClosure() || innermost_function().IsAsyncGenerator() || innermost_function().IsAsyncGenClosure()

**Comment by mhausner** [comment]
The yield statement in the given example is illegal, since the enclosing function is not a generator. The VM fails to report a compile-time error. Nice catch.

**Comment by mhausner** [comment]
https://codereview.chromium.org/1204103002/

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
e5f339b8619d8f930979a2446e162853829f754c
