### ISSUE TITLE
dart2js: Add option to always generate noSuchMethod stubs

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#23714]
A JavaScript type error does not contain the receiver or the arguments.
If we are lucky we get a message like "TypeError: b.$2 is not a function".
This makes it difficult to understand the error, especially if the call stack is general interpreter-like code that calls Function.apply.  With non-interactive debugging via error messages and stack traces captured in the deployed client, there is no opportunity to inspect values on the call stack.

At a minimum we need the receiver type to understand the error. We can get this from the noSuchMethod stubs. If there are no noSuchMethod stubs we could generate degenerate noSuchMethod stubs that don't encode the named optional arguments, but that would add complexity.

I think we can streamline the generation of noSuchMethod stubs to make it more uniform and defer almost everything except creating a JavaScript closure to the first use. If we use a data table for the named optional arguments, the degenerate form is an empty table rather than emitting different code.

**Comment by matanlurey** [comment]
I think this is stale with Dart2, right @rakudrama?
