### ISSUE TITLE
delete sdk/utils/apidoc

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23711]
Seems this is no longer used since we switched over to docgen + docviewer. And in the future I don't believe there is any plans to use it. 

@sethladd just to double check with you, is it OK to delete this?

**Comment by sethladd** [comment]
Might want to check with @keertip on this one. It's been a while since I've been in the SDK. :)

**Comment by devoncarew** [comment]
@sigmundch, it looks like this has been done?

**Comment by sigmundch** [comment]
yep, seems that way.
