### ISSUE TITLE
Sending SIGQUIT to a Dart process causes it to crash

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23718]
I've only been able to reproduce this with the test runner running on pub. To reproduce, check out [the `sigquit-repro` branch of `pub`](/dart-lang/pub/tree/sigquit-repro), run `pub get`, then run `dart bin/pub.dart run test`. Once it starts printing output, use `ps` to find its PID and then run `kill -QUIT $pid`. You should see an error like this:

```
vm-service: Error: Unhandled exception:
UnimplementedError: Service script loading not supported.
#0      VMService._notSupported (dart:vmservice:118:5)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

I've tested this on [`1.10.1`](/dart-lang/sdk/commit/980d7cdd5e39e7aed82060fde225d1079c9eed35), 0535e37619995083321e22a3eda575920d36218c, and 69938db31a082d93b941e3526cdd0a29625842e5, all on Ubuntu.

**Comment by johnmccutchan** [comment]
Presumed stale.

**Comment by nex3** [comment]
I can no longer reproduce this as of 3b0104732b308a6464060ee8acbb9c7b22f9b8ce.
