### ISSUE TITLE
Order isolates by time of creation

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23717]
Currently there seems to be no strong notion of ordering in the listing of isolates in observatory. This makes it hard to navigate, especially in applications that spawn and kill isolates frequently like the test runner. Imposing a consistent age-based ordering on the list would make it a lot easier to track, and would have the additional benefit of always keeping the main isolate at the top.

**Comment by turnidge** [comment]
I agree.

**Comment by turnidge** [comment]
Done in 227010d9dc84c2e5bf042ca1c0367f36eacbfa6b.  The isolate list used in the vm service is now sorted by age, oldest to youngest.  This will improve the main isolate view as well as any other part of the system that lists isolates.  Thanks for reporting this issue.
