### ISSUE TITLE
dart2js: Static methods not tree-shaken 

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#23720]
The .js for this file contains `"Hello"`

```dart
main() {
  if (false) {
    (use)(foo);
  }
  (use)(bar);
}

foo() => "Hello";
bar() => "Bye";

use(x) {
  print(x());
}
```

The problem is that the function is marked as used before optimization rather than after optimization.
It should be possible to move the marking-as-used later.

**Comment by rakudrama** [comment]
Fix in testing https://chromiumcodereview.appspot.com/1211223002/

**Comment by sigmundch** [comment]
@rakudrama fixed this in https://github.com/dart-lang/sdk/commit/7d6051f21e84ec4bf2312b854a0e2c990ea88361
