### ISSUE TITLE
pub install/upgrade not creating link for Git repo on Linux

### ISSUE THREAD

**Issue by halverneus** [dart-lang/sdk#23727]
The repository clones as expected and exists in .pub-cache/git/, but the link is never created within the project itself. Project is on same partition as .pub-cache.

Pubspec for project as follows:

name: project
description: project 2.0
dependencies:
  got:
    git:
      url: https://stash.metro.ad.company.com/scm/got/got.git
      ref: release/initial
  browser: any
  intl: any

Pubspec for library as follows:

name: got
version: 0.0.1
description: Graphical objects toolkit.
dependencies:
  browser: any

pub install --trace --verbosity=all       
FINE: Pub 1.10.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - got any from git ({ref: release/initial, url: https://stash.metro.ad.company.com/scm/got/got.git}) (locked to 0.0.1)
    | - intl any from hosted (intl) (locked to 0.12.4)
    | - browser any from hosted (browser) (locked to 0.10.0+2)
SLVR: | got 0.0.1 from git is locked
SLVR: * select got 0.0.1 from git
SLVR: | browser 0.10.0+2 from hosted is locked
SLVR: | * select browser 0.10.0+2 from hosted
SLVR: | | intl 0.12.4 from hosted is locked
SLVR: | | * select intl 0.12.4 from hosted
IO  : Spawning "git --version" in /home/xxx/Remote/Development/go/src/team-gui/dart/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 1.9.1
    | Nothing output on stderr.
FINE: Determined git command null.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
SLVR: | | | analyzer 0.25.0+1 from hosted is locked
SLVR: | | | * select analyzer 0.25.0+1 from hosted
SLVR: | | | | args 0.13.2 from hosted is locked
SLVR: | | | | * select args 0.13.2 from hosted
SLVR: | | | | | path 1.3.5 from hosted is locked
SLVR: | | | | | * select path 1.3.5 from hosted
SLVR: | | | | | | petitparser 1.4.3 from hosted is locked
SLVR: | | | | | | * select petitparser 1.4.3 from hosted
SLVR: | | | | | | | watcher 0.9.6 from hosted is locked
SLVR: | | | | | | | * select watcher 0.9.6 from hosted
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
SLVR: BacktrackingSolver took 0:00:00.186847 seconds.
    | - Requested 0 version lists
    | - Looked up 0 cached version lists
    | - Requested 8 pubspecs
    | - Looked up 1 cached pubspecs
    | 
FINE: Resolving dependencies finished (0.198s).
IO  : Deleting directory /home/xxx/Remote/Development/go/src/team-gui/dart/packages.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
FINE: Creating link for package 'browser'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/browser pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib
FINE: Creating link for package 'intl'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/intl pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4/lib
FINE: Creating link for package 'analyzer'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/analyzer pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/analyzer-0.25.0+1/lib
FINE: Creating link for package 'args'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/args pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib
FINE: Creating link for package 'path'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/path pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/path-1.3.5/lib
FINE: Creating link for package 'petitparser'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/petitparser pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib
FINE: Creating link for package 'watcher'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/watcher pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.6/lib
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git checkout 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/got-46f356bf32a657ca66e78998b744510f1ff23bbb
IO  : Finished git. Exit code 0.
    | Nothing output on stdout.
    | stderr:
    | | HEAD is now at 46f356b... Removed currently unused dependency in pubspec.yaml.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Writing 837 characters to text file /home/xxx/Remote/Development/go/src/team-gui/dart/pubspec.lock.
FINE: Contents:
    | # Generated by pub
    | # See http://pub.dartlang.org/doc/glossary.html#lockfile
    | packages:
    |   analyzer:
    |     description: analyzer
    |     source: hosted
    |     version: "0.25.0+1"
    |   args:
    |     description: args
    |     source: hosted
    |     version: "0.13.2"
    |   got:
    |     description:
    |       ref: "release/initial"
    |       resolved-ref: "46f356bf32a657ca66e78998b744510f1ff23bbb"
    |       url: "https://stash.metro.ad.company.com/scm/got/got.git"
    |     source: git
    |     version: "0.0.1"
    |   browser:
    |     description: browser
    |     source: hosted
    |     version: "0.10.0+2"
    |   intl:
    |     description: intl
    |     source: hosted
    |     version: "0.12.4"
    |   path:
    |     description: path
    |     source: hosted
    |     version: "1.3.5"
    |   petitparser:
    |     description: petitparser
    |     source: hosted
    |     version: "1.4.3"
    |   watcher:
    |     description: watcher
    |     source: hosted
    |     version: "0.9.6"
FINE: Creating selflink for package 'TEAM'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/TEAM pointing to ../lib
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/packages pointing to ../packages
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/img/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/img/packages pointing to ../../packages
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/css/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/css/packages pointing to ../../packages
MSG : Got dependencies!
FINE: Loading package graph...
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
FINE: Loading package graph finished (0.010s).

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/pub#1325
