### ISSUE TITLE
Switch/Case : Can't give one processing for several values (the "not implemented" value, without break, is processed in "Default")

### ISSUE THREAD

**Issue by LSMetag** [dart-lang/sdk#23725]
Hi !

I just saw a minor bug in Dart 1.11. If, in a "switch" condition, I try to assign the same statement for several values, the not implemented value will be processed in the "Default" part, rather than processed by the following part.

An example

     switch(key)
                {
                  case "image":break;
                  case "email":break;
                  case "submit":
                  case "cancel": popup.appendHtml("<span>...</span>");break;
                  default : popup.appendHtml("<p>...</p>");break;
                }

The "submit" case generates a "<p" tag instead of a "span" tag.

Thank you for all your hard work. I love Dart !!!!

**Comment by floitschG** [comment]
I can't reproduce.
Does this happen for dart2js or the VM?
Do you have a repro?
Are you sure the input is not misspelled? (maybe print the `key` in the switch statement)

**Comment by LSMetag** [comment]
I linked all my code's project, in #23752, that I just submitted (for another problem).

You'll be able to test this in the end of the file WebApps/Lib/zoneruban.dart (OpenPopup method), linked to the "Inscription" Button on the top right of the screen. You'll see, in the inscription Popup, that the "Valider" button is a <p> whereas the "Annuler" button is a <span>

**Comment by floitschG** [comment]
I just tried with 32 and 64 bit versions of Dartium 1.11 (https://www.dartlang.org/downloads/archive/), and can't reproduce...
Version 39.0.2171.0 (64-bit), or
Version 39.0.2171.0

When I inspect the page they are correctly spans.

I'm running on Linux, but I doubt that the OS makes a difference.

**Comment by LSMetag** [comment]
I retested, inspecting with Firebug 2 instead of Firebug 3 alpha... You are right, there is no error.

You can close this ticket. I am very sorry !!!
