### ISSUE TITLE
AggregateTransformer and Transformer do not run together

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/sdk#23723]
My project have both AggregateTransformer and regular Transformer. The transformers works fine if I only use one of them. When I use both, an exception throw. Here is the trace: 

Loading source assets... 
Loading adl_client and adl_lib transformers... 
Building adl_client... ENV_TYPE: null
Generating blockDefinitions.dart ...
Building adl_client... (1.1s) Transfer index.html dart script tag...
ENV_TYPE: null
Building adl_client...
[Info from Dart2JS]:
Compiling adl_client|web/adl_app_controller.dart...
[Dart2JS on adl_client|web/adl_app_controller.dart]:
3 warning(s) suppressed in package:adl_lib.
[Warning from Dart2JS]:
web/adl_app_controller.dart:
336 methods retained for use by dart:mirrors out of 3981 total methods (8%).
[Info from Dart2JS on adl_client|web/adl_app_controller.dart]:
package:adl_lib/adl_lib.dart: Import of 'dart:mirrors'.
[Info from Dart2JS on adl_client|web/adl_app_controller.dart]:
package:dart_ext/function_ext_mirror_invoke.dart: Import of 'dart:mirrors'.
[Info from Dart2JS]:
Took 0:00:22.341625 to compile adl_client|web/adl_app_controller.dart.
Built 929 files to "build".
kzhao@MacBook-Pro:client (feature/DEB-22788) $ pub --trace build
Loading source assets... 
The null object does not have a getter 'isEmpty'.

NoSuchMethodError: method not found: 'isEmpty'
Receiver: null
Arguments: []
dart:core                                               Object.noSuchMethod
package:pub/src/barback/load_all_transformers.dart 141  _stageTransformers.stageNumberFor
dart:core                                               Iterable.reduce
package:pub/src/utils.dart 439                          maxAll
package:pub/src/barback/load_all_transformers.dart 142  _stageTransformers.stageNumberFor
package:pub/src/barback/load_all_transformers.dart 147  _stageTransformers
package:pub/src/barback/load_all_transformers.dart 64   loadAllTransformers.<async>
dart:isolate                                            _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                              _Completer.completeError
package:pub/src/barback/load_all_transformers.dart 127  loadAllTransformers.<async>
dart:isolate                                            _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:pub/src/barback/load_all_transformers.dart  loadAllTransformers
package:pub/src/barback/asset_environment.dart 514  AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>.<async>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
package:pub/src/barback/asset_environment.dart      AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>
package:pub/src/log.dart 378                        progress
package:pub/src/barback/asset_environment.dart 513  AssetEnvironment._load.<fn>.<async>.<fn>.<async>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                          Future.Future.sync
package:pub/src/barback/asset_environment.dart 673  AssetEnvironment._withStreamErrors
package:pub/src/barback/asset_environment.dart 512  AssetEnvironment._load.<fn>.<async>
dart:async                                          _SyncCompleter.complete
package:pub/src/barback/asset_environment.dart 674  AssetEnvironment._withStreamErrors.<fn>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                          _Future.then
package:pub/src/barback/asset_environment.dart 490  AssetEnvironment._load.<fn>.<async>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                          _Future.then
package:pub/src/barback/asset_environment.dart 479  AssetEnvironment._load.<fn>.<async>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:pub/src/barback/asset_environment.dart      AssetEnvironment._load.<fn>
package:pub/src/log.dart 378                        progress
package:pub/src/barback/asset_environment.dart 461  AssetEnvironment._load
package:pub/src/barback/asset_environment.dart 85   AssetEnvironment.create.<fn>.<async>
dart:isolate                                        _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                         _Future.then
package:pub/src/barback/asset_environment.dart 77  AssetEnvironment.create.<fn>.<async>
dart:isolate                                       _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                                         Future.Future.microtask
package:pub/src/barback/asset_environment.dart     AssetEnvironment.create.<fn>
package:pub/src/log.dart 378                       progress
package:pub/src/barback/asset_environment.dart 76  AssetEnvironment.create
package:pub/src/command/build.dart 64              BuildCommand.onRunTransformerCommand.<async>
dart:isolate                                       _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async                               Future.Future.microtask
package:pub/src/command/build.dart       BuildCommand.onRunTransformerCommand
package:pub/src/command/barback.dart 58  BarbackCommand.run
package:args/command_runner.dart 178     CommandRunner.runCommand.<fn>
dart:async                               Future.Future.sync
package:args/command_runner.dart 131     CommandRunner.runCommand
package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>.<fn>
dart:async                               Future.Future.sync
package:pub/src/utils.dart 103           captureErrors.<fn>
package:stack_trace/src/chain.dart 78    Chain.capture
package:pub/src/utils.dart 117           captureErrors
package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>
dart:isolate                             _RawReceivePortImpl._handleMessage
---- Log transcript ----
FINE: Pub 1.11.0
IO  : Deleting directory build.
FINE: Loading asset environment...
FINE: Loading package graph...
FINE: Loading package graph finished (0.3s).
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
FINE: Providing sources for smartcanvas|lib.
FINE: Providing sources for toolkit|lib.
FINE: Providing sources for adl_lib|lib.
FINE: Providing sources for jsproxy|lib.
FINE: Providing sources for adl_client|lib.
FINE: Loading source assets finished (0.8s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
    | adl_client/js_build_transformer: -
    | adl_client: adl_client/js_build_transformer, adl_lib and test/pub_serve
    | adl_lib: -
FINE: Loading transformers finished (0.0s).
FINE: Initializing barback finished (0.9s).
FINE: Loading asset environment finished (1.3s).
ERR : The null object does not have a getter 'isEmpty'.
    | 
    | NoSuchMethodError: method not found: 'isEmpty'
    | Receiver: null
    | Arguments: []
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                               Object.noSuchMethod
    | package:pub/src/barback/load_all_transformers.dart 141  _stageTransformers.stageNumberFor
    | dart:core                                               Iterable.reduce
    | package:pub/src/utils.dart 439                          maxAll
    | package:pub/src/barback/load_all_transformers.dart 142  _stageTransformers.stageNumberFor
    | package:pub/src/barback/load_all_transformers.dart 147  _stageTransformers
    | package:pub/src/barback/load_all_transformers.dart 64   loadAllTransformers.<async>
    | dart:isolate                                            _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                              _Completer.completeError
    | package:pub/src/barback/load_all_transformers.dart 127  loadAllTransformers.<async>
    | dart:isolate                                            _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                          Future.Future.microtask
    | package:pub/src/barback/load_all_transformers.dart  loadAllTransformers
    | package:pub/src/barback/asset_environment.dart 514  AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>.<async>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | package:pub/src/barback/asset_environment.dart      AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>
    | package:pub/src/log.dart 378                        progress
    | package:pub/src/barback/asset_environment.dart 513  AssetEnvironment._load.<fn>.<async>.<fn>.<async>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                          Future.Future.sync
    | package:pub/src/barback/asset_environment.dart 673  AssetEnvironment._withStreamErrors
    | package:pub/src/barback/asset_environment.dart 512  AssetEnvironment._load.<fn>.<async>
    | dart:async                                          _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 674  AssetEnvironment._withStreamErrors.<fn>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                          _Future.then
    | package:pub/src/barback/asset_environment.dart 490  AssetEnvironment._load.<fn>.<async>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                          _Future.then
    | package:pub/src/barback/asset_environment.dart 479  AssetEnvironment._load.<fn>.<async>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                          Future.Future.microtask
    | package:pub/src/barback/asset_environment.dart      AssetEnvironment._load.<fn>
    | package:pub/src/log.dart 378                        progress
    | package:pub/src/barback/asset_environment.dart 461  AssetEnvironment._load
    | package:pub/src/barback/asset_environment.dart 85   AssetEnvironment.create.<fn>.<async>
    | dart:isolate                                        _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                         _Future.then
    | package:pub/src/barback/asset_environment.dart 77  AssetEnvironment.create.<fn>.<async>
    | dart:isolate                                       _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.Future.microtask
    | package:pub/src/barback/asset_environment.dart     AssetEnvironment.create.<fn>
    | package:pub/src/log.dart 378                       progress
    | package:pub/src/barback/asset_environment.dart 76  AssetEnvironment.create
    | package:pub/src/command/build.dart 64              BuildCommand.onRunTransformerCommand.<async>
    | dart:isolate                                       _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/command/build.dart       BuildCommand.onRunTransformerCommand
    | package:pub/src/command/barback.dart 58  BarbackCommand.run
    | package:args/command_runner.dart 178     CommandRunner.runCommand.<fn>
    | dart:async                               Future.Future.sync
    | package:args/command_runner.dart 131     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                               Future.Future.sync
    | package:pub/src/utils.dart 103           captureErrors.<fn>
    | package:stack_trace/src/chain.dart 78    Chain.capture
    | package:pub/src/utils.dart 117           captureErrors
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>
    | dart:isolate                             _RawReceivePortImpl._handleMessage
---- End log transcript ----

**Comment by floitschG** [comment]
This issue was moved to dart-lang/barback#62
