### ISSUE TITLE
dart2js: minified one-shot interceptors have too long names after Name change

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#23731]
Size regression in minified code due to: https://codereview.chromium.org//1198293002

```javascript
// Old:
gv:function(a){return J.wS(this.Q.b)}},

// New:
gA:function(a){return J.gA$asx(this.Q.b)}},
```

Notice that `J.wS` becomes `J.gA$asx`
This is the one-shot interceptor function for `get length`.
This makes minified swarm 0.5% larger and another app nearly 1% larger.

Although the unminified name can be represented as a composite (here based on being a specialization of a getter of some name), the minified names need to be unique global identifiers that are available to frequency based name allocation.

**Comment by herhut-ggl** [comment]
See https://codereview.chromium.org/1212613009/ for a fix.

**Comment by rakudrama** [comment]
Would it be reasonable to split out the one-shot interceptors fix to fix
the regression?

**Comment by herhut-ggl** [comment]
See https://codereview.chromium.org/1220793006/.

**Comment by herhut-ggl** [comment]
Fixes in https://github.com/dart-lang/sdk/commit/964afc05237b9e86ff08043ac726ce421d4773d4.
