### ISSUE TITLE
Invalid StreamSubscription from async generator function

### ISSUE THREAD

**Issue by rfqu** [dart-lang/sdk#23740]
A StreamSubscription obtained from async generator function cannot be cancelled.

Following code fails with error:
Unhandled exception:
The null object does not have a method 'close'.

import "dart:async";

f (int value) async* {
  for (int k=0; k<value; k++) { 
     yield k;
  }
}

main() {
  StreamSubscription ss = f(5).listen(null);
  ss.cancel(); // this line causes the error
}

**Comment by floitschG** [comment]
I couldn't reproduce.
Does this happen on the VM or in dart2js?
Which version are you using?

**Comment by rfqu** [comment]
Dart VM version: 1.10.1 (Mon May 11 22:46:14 2015) on "linux_x64"

**Comment by rfqu** [comment]
test passes on dart 1.11.
The issue can be closed.

**Comment by lrhn** [comment]
Excellent.
