### ISSUE TITLE
--observe not included in output of -h or -h -v from VM

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23743]
It's hard to figure out how to start the observatory from the CLI. If you type `dart -h`, you get 4 options printed out, none of them observatory or services related. If you type in `dart -h -v` you get ~a hundred options. They're hard to dig through for a specific option, and none of them say observatory - instead it's --enable-vm-service.

**Comment by devoncarew** [comment]
@johnmccutchan @turnidge

**Comment by MikeMitterer** [comment]
Just posted some instructions how to open Dartium in observatory mode on Mac: https://plus.google.com/+MikeMitterer/posts/9AhzjVGA99a

**Comment by sethladd** [comment]
Good catch :)

**Comment by turnidge** [comment]
Fixed by @rmacnak-google in ba88435b7d3a50d55b8282178c66dc660c45e21a.
