### ISSUE TITLE
No static warning if class declares static method and has setter with the same name

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23749]
Dart specification (v3.0, June 2015) reads (10.7 Static methods):

"It is a static warning if a class C declares a static method named n and has a setter named n ="

In fact no warning produced. The code is the following.

``` dart
class C {
  static set s1(var value) => {};
  static s1() {
    return 1;
  }

  set s2(var value) => {};
  static s2() {
    return 2;
  }
}

main() {
  var x = C.s1();
}
```

Dart analyzer shows "No issues found" for this code. dartanalyzer version 1.11.0-edge.45833

**Comment by floitschG** [comment]
Relevant tests:
Language/Classes/Static_Methods/same_name_method_and_setter_t01
Language/Classes/Getters/static_getter_t02
Language/Classes/Setters/static_setter_t06

Also see: https://github.com/dart-lang/sdk/issues/12342, https://github.com/dart-lang/sdk/issues/14427, https://github.com/dart-lang/sdk/issues/21201, and https://github.com/dart-lang/sdk/issues/24534

/ccing @peter-ahe-google and @stereotype441 from frontend-team.

**Comment by askeksa-google** [comment]
Check apparently still missing in analyzer. It is pending in CFE, tracked by https://github.com/dart-lang/sdk/issues/33237

**Comment by srawlins** [comment]
Analyzer now reports the correct errors:

```none
Analyzing 23749.dart...
  error • The name 's1' is already defined. • 23749.dart:3:10 • duplicate_definition
  error • Class 'C' can't define static member 's2' and have instance member 'C.s2' with the same name. • 23749.dart:8:10 • conflicting_static_and_instance
```
