### ISSUE TITLE
pkgbuild tests fail on new compiler package

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23750]
The tests that test packages against the set of packages served by public pub, and against the set of packages in the repo, fail on the new compiler package.  They say that certain required packages are missing.  Also, a test complains that compiler and analyzer_cli have incompatible pubspecs.

These test failures are suppressed in /pkg/pkgbuild.status.

pkgbuild_repo_pkgs pkgbuild/pkg/compiler
Expected: Pass 
Actual: PubGetError
Could not find package js_runtime at ".../generated_pub_package_builds/sdk/lib/_internal/js_runtime".
Depended on by:
- compiler 

pkgbuild_repo_pkgs pkgbuild/third_party/pkg/package_config
Expected: Pass 
Actual: PubGetError
stderr:
Incompatible version constraints on package_config:
- analyzer_cli 1.1.0 depends on version ^0.1.1
- compiler 0.0.0 depends on version ^0.0.4

pkgbuild_public_pkgs pkgbuild/pkg/compiler
Expected: Pass 
Actual: PubGetError
Could not find package js_ast at "/Volumes/data/b/build/slave/pkg-mac-be/build/sdk/xcodebuild/ReleaseIA32/generated_pub_package_builds/public_packages/js_ast".
Depended on by:
- compiler 

CC: @ricowind @sigmundch

**Comment by whesse** [comment]
Another test is just failing on russian windows, due to the changed path:

pkgbuild/samples/third_party/dromaeo
Expected: Pass Slow 
Actual: Fail

Could not find asset compiler_unsupported|lib/sdk/_internal/compiler/js_lib/shared/async_await_error_codes.dart_.

**Comment by sigmundch** [comment]
Thanks Bill - somehow I didn't see the failures for these bots. I'll take a look.

**Comment by sigmundch** [comment]
I'm still a bit confused with the russian failure, since that test passes on all other platforms. I created [this CL](https://codereview.chromium.org/1217353002/) to fix all other issues, and filed a [separate bug](23760) to keep tracking the russian bug.
