### ISSUE TITLE
source_gen broken by 1.12-dev release

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23755]
See https://github.com/dart-lang/source_gen/issues/53

Suddenly getting a null resolution error?

Repo:

```
git clone https://github.com/dart-lang/source_gen.git
cd source_gen
pub install
pub run test
```

**Comment by kevmoo** [comment]
Related to the library move-around?

**Comment by kevmoo** [comment]
Critical bug in Angular https://github.com/angular/angular/issues/2798

**Comment by sigmundch** [comment]
I got a change in the works. Will update here shortly

**Comment by sigmundch** [comment]
https://codereview.chromium.org/1216313002/

**Comment by sigmundch** [comment]
should be fixed by: https://github.com/dart-lang/sdk/commit/4ec3db6947cdbb554c395d4b98196293bf7de3bc
