### ISSUE TITLE
Dart2JS : WebComponents performance issues (very serious)

### ISSUE THREAD

**Issue by LSMetag** [dart-lang/sdk#23752]
Hi,

From a long time, running my web project (based on Polymer Dart) as Javascript caused the Polymer components to load extremely slowly (1 second with Dart, 5 to 10 seconds in JS).

Using firebug, I got this message : 

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create webcomponents.js:6007:6"

Did you think about this ? I indeed plan to further optimize that, but If Dart2JS itself is a cause, It can be a real problem.

Here is the project repository : https://github.com/LSMetag/CVWebkit/, that can be a good testing.

The polymer components are in WebApp/Web/ZoneRuban.html and WebApp/Lib/zoneRuban.dart.
The "zoneruban" macro-component tag is invoked in WebApp/Web/CVWebkit.html.

config.yaml is the source file that is read to create layout and use components.

It would be a great help too if you could advise me about performance improving, if I am too at fault.

Thanks in advance !

**Comment by floitschG** [comment]
/cc @sigmundch 
According to my tests, setting up an inheritance chain using "__proto__" is the fastest, and V8 doesn't seem to mind.
Since IE doesn't support changing the prototype we already have a fallback in place. We could use that one, when detecting FF.
In this case the __proto__ change seems to come from webcomponents.js which isn't a dart2js produced file (afaik). So maybe this is a polymer issue and not dart2js related.

**Comment by LSMetag** [comment]
It's related to polymer, it's certain, because the performance issue is only on polymer components. And indeed, I tested on Firefox. I just tested in Chrome and I don't have this issue.

I thought It used VM but in fact no. The problem is linked to polymer, after being converted to JS, and using a browser other than Chrome.

**Comment by sigmundch** [comment]
@jakemac53

Jake has been working on a newer port of polymer.js, which should address many performance issues. I am not sure if part of that includes fixes to webcomponents.js to avoid this performance problem, but I know that the new architecture tries to avoid using some web-component features (for example, shadow-dom) if they seem to be too much of a performance bottleneck.

Jake can tell you a bit more, but my understanding is that load times are much better now.

**Comment by jakemac53** [comment]
You can try out https://github.com/dart-lang/sample-todomvc-polymer/tree/polymer-0.17 to see the new version. In non-chrome browsers especially it is much faster because of the lack of shadow dom and a few other things.

**Comment by sigmundch** [comment]
This issue was moved to dart-lang/web-components#30
