### ISSUE TITLE
A few problems in StreamIterator documentation/specification

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23753]
I've noticed a few problems in the StreamIterator documentation:

1. "An [Iterable] like interface for the values of a [Stream]." Clearly, StreamIterator is similar to Iterator, not Iterable.

2. The documentation of "current" implies that calling current is undefined before calling moveNext and after moveNext has returned false. This doesn't match its implementation, and the expectation you get by comparing it to Iterator.current which clearly documents that current will return null in those conditions.

@lrhn could you provide a quick reply as to whether "current" is truly undefined before calling moveNext and after it has returned false?

**Comment by lrhn** [comment]
I think it's safe to say that the value of `current` is `null` until `moveNext` is first called, and it's `null` after `moveNext` has returned false.
The undefined case is the time between calling `moveNext` and the returned future completing. At that time the value may be either the new value or null, and it's not clear when the change takes place.
The current value is set to null when moveNext is called, so it should never be the old value.

**Comment by lrhn** [comment]
I have updated comments on the `StreamIterable` class
