### ISSUE TITLE
test_watchFile_delete fails only on Windows

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#23762]
FAILED: none-vm-checked release_ia32 pkg/analyzer/test/file_system/physical_resource_provider_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
PASS: PhysicalResourceProviderTest | test_getStateLocation_uniqueness
FAIL: PhysicalResourceProviderTest | test_watchFile_delete
  Expected: ChangeType:&lt;remove>
    Actual: ChangeType:&lt;modify>

  package:unittest/src/simple_configuration.dart 128:34                     SimpleConfiguration.onExpectFailure
  package:unittest/src/simple_configuration.dart 24:13                      _ExpectFailureHandler.fail
  package:unittest/src/matcher/expect.dart 121:5                            DefaultFailureHandler.failMatch
  package:unittest/src/matcher/expect.dart 95:20                            expect
  pkg\analyzer\test\file_system\physical_resource_provider_test.dart 299:9  PhysicalResourceProviderTest.test_watchFile_delete.<fn>.<fn>
  dart:async/future.dart 228                                                Future.Future.delayed.<fn>
  dart:async/zone.dart 900                                                  _rootRun
  dart:async/zone.dart 803                                                  _CustomZone.run
  dart:async/zone.dart 709                                                  _CustomZone.runGuarded
  dart:async/zone.dart 734                                                  _CustomZone.bindCallback.<fn>
  dart:async/zone.dart 904                                                  _rootRun
  dart:async/zone.dart 803                                                  _CustomZone.run
  dart:async/zone.dart 709                                                  _CustomZone.runGuarded
  dart:async/zone.dart 734                                                  _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 16                                      Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 385                                    _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                                    _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148                                 _RawReceivePortImpl._handleMessage

**Comment by danrubel** [comment]
@nex3 We appear to be receiving a watcher modify event rather than a delete event on Windows, but it works correctly on Linux and Mac. Any suggestions?

**Comment by nex3** [comment]
Do you know what specific action on the filesystem triggers this?

**Comment by danrubel** [comment]
Yes. Its a test on the bots that is failing. 

http://build.chromium.org/p/client.dart/builders/pkg-win-be/builds/290/steps/annotated_steps/logs/stdio
and search for "FAILED: none-vm-checked release_ia32 pkg/analyzer/test/file_system/physical_resource_provider_test"

The test deletes creates, waits, then deletes a file. 
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/test/file_system/physical_resource_provider_test.dart#L299

**Comment by nex3** [comment]
Can you reproduce this outside the context of the bots? We certainly have [a test in the watcher package](https://github.com/dart-lang/watcher/blob/master/test/directory_watcher/shared.dart#L39-L44) for this behavior, so there's got to be something else going on that triggers the wrong event.

**Comment by danrubel** [comment]
Good question. I don't have a Windows box properly set up to test this but can do so next week. Are the watcher tests running on the bots?

**Comment by nex3** [comment]
Yeah, you can see them [here](http://build.chromium.org/p/client.dart.packages/console).

**Comment by danrubel** [comment]
Thanks! That's what I needed. I'll dig in and figure out what's different between the two tests of tests and why the analyzer test is failing.

**Comment by danrubel** [comment]
Patched the test to pass on Windows pending investigation.
https://codereview.chromium.org/1219863004/
A similar test on Windows in the underlying watcher package passes.

**Comment by DanTup** [comment]
FWIW I was just running these tests on my machine and it output this:

```
PhysicalResourceProviderTest:test_watchFile_delete received an event with type = remove
```

Not sure if this means it's been fixed, or whether it might affect different Windows versions differently (I'm running Windows 10 Pro).

**Comment by srawlins** [comment]
Closing as stale.

**Comment by DanTup** [comment]
I just noticed the output I mentioned above again which let me here. Except, in my output above it says `type = remove` which would've passed the test. However today I saw `modify`:

```
00:20 +3074: analyzer file system PhysicalResourceProviderWatchTest test_watchFile_delete

PhysicalResourceProviderWatchTest:test_watchFile_delete received an event with type = modify
```

So I believe this test would still be flaky on Windows if it wasn't for skipping the `expect()` on Windows:

https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/test/file_system/physical_resource_provider_watch_test.dart#L36-L47
