### ISSUE TITLE
VM allows omitting semicolon after local function declarations with => body.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23761]
Example code:
```dart
main() {
  foo(x) => (y) => x + y
  bar(x) => (y) { return x + y; }
  baz(x, y) => x + y
  print(foo(7)(4) + bar(3)(8) + baz(9, 11));
}
```
All three function declarations should have had a semicolon as the last token of the body, but the VM accepts this code without complaining.

**Comment by mhausner** [comment]
Committed patchset #3 (id:40001) manually as
782f7b268bda32e907714492ac50b706493027d3 (presubmit successful).
