### ISSUE TITLE
We should consider intrinsifying Object_instanceOf for calls from unoptimized code

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#23765]
The function Object_instanceOf is called a lot from unoptimized code due to patterns like '(a is double)' being used. It would be nice if we could intrinsify this so that we don't make native calls.
The profile of a sky app (mine-digger) shows about 13% of ticks in this native function.
@sgmitrovic

**Comment by sgmitrovic** [comment]
Added specialized instanceOf methods for some common types: String, Smi, int, num, double. This causes significant reduction of time spent in instanceOf and significant reduction of startup time. Adding intrinsics for each of those natives did not demonstrate any performance improvement, therefore I would refrain from adding intrinsics unless they need is demonstrated through profiling.
