### ISSUE TITLE
Implement generalized tear-offs in the analyzer

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#23777]
See #23774.

**Comment by sethladd** [comment]
Hi! Looks like Flutter is going to start using this feature. Looking forward to seeing this in the Analyzer!

**Comment by whesse** [comment]
Many co19 analyzer tests are marked as failing due to this bug, and are suppressed in the status file tests/co19/co19-analyzer2.status.

**Comment by munificent** [comment]
Since they were never finished and didn't seem to work out that well, we're removing generalized tear-offs: https://github.com/dart-lang/sdk/issues/27518
