### ISSUE TITLE
Implement generalized tear-offs

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#23774]
It's in the spec.
- [x] VM (#23775)
- [ ] VM: tear-offs of super methods (https://github.com/dart-lang/sdk/issues/24835)
- [ ] dart2js (#23776)
- [ ] analyzer (#23777)

**Comment by ochafik** [comment]
Is there any update on generalized tear-offs for the web? If not, should they be removed from the specs?

**Comment by munificent** [comment]
Yes, we're going to remove them: https://github.com/dart-lang/sdk/issues/27518
