### ISSUE TITLE
Implement super() calls in mixins in analyzer behind a flag

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#23772]
This is the analyzer-specific issue for #23770. That issue has the details.

**Comment by sethladd** [comment]
Hi @bwilkerson and @stereotype441 is there any work here for the analyzer?

**Comment by stereotype441** [comment]
@sethladd yes, there is work for analyzer, but hopefully a small amount.  Currently, analyzer reports a compile-time error if:
- a class that refers to super is used as a mixin, or
- a class that is not derived from Object is used as a mixin.

A flag needs to be created, and these error cases need to be removed when the flag is set.

**Comment by sethladd** [comment]
Thanks for the update! We have an anxious customer looking forward to this feature. :)

**Comment by stereotype441** [comment]
Support has now landed in the command-line analyzer and analysis server.

**Comment by sethladd** [comment]
Is this work behind a flag?

**Comment by bwilkerson** [comment]
It is behind the --supermixin flag in the command-line analyzer. It is available in the analysis server, behind a client-configurable option, but I don't know whether any clients have made it possible for users to enable the option.

**Comment by sethladd** [comment]
cc @devoncarew for how to turn this on via Atom.

Also, can't wait for a .analysis_options to turn stuff like this on without a GUI. :)

What will it take to remove the flag? What signal are we waiting for?

**Comment by devoncarew** [comment]
+1 to using the `.analysis_options` file. Once people start using this feature in a project, every developer on the project will need to turn it on. If they use the analysis server flag, it'll get turned on for other projects as well, whether that's desired or not. It's really something that should be under SCM with the rest of the source.

**Comment by sethladd** [comment]
Also, that way we only need to implement the configurability once... otherwise, we're asking three IDEs (or more?) to build GUIs for these kinds of flags (and, thus, coordinate releases of plugins with SDKs).

**Comment by bwilkerson** [comment]
> ... how to turn this on via Atom ...

Use the `analysis.updateOptions` request to set the `enableSuperMixins ` option to `true`.

> What will it take to remove the flag? What signal are we waiting for?

See https://github.com/dart-lang/sdk/issues/23770 for context.

**Comment by sethladd** [comment]
> See #23770 for context.

Right, thanks. Are you waiting for the spec to be formally blessed by TC52 before removing the flag? (IIR that's "standard operating procedure")

**Comment by bwilkerson** [comment]
Yes. And waiting for the rest of the tools (ddc and dart2js) to support it. We don't really want to enable a feature like this in some places but not in others.
