### ISSUE TITLE
Dynamic variables that are initialized with a function literal uses the wrong type for code-completion

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#23785]
**What steps will reproduce the problem?**
1) Open Webstorm and create a Dart-Console Application
2) In main.dart add a dynamic variable declaration that initializes to a function literal

```
main(List<String> arguments) {
    var f = () = > 42;
}
```

3) After the variable declaration statement type `f.` and wait for the code-completion suggestions to appear

**What is the expected output? What do you see instead?**
**Expected:**
Code-completion should show suggestions based on the type Function

**Actual:**
Code-completion shows suggestions based on the type int;

**What version of the product are you using?**
Webstorm 10.0.4
Dart SDK: 1.12.0-dev.1.1

**Comment by whesse** [comment]
@danrubel @scheglov Let me know what the correct labels and routing for this should be.

**Comment by bwilkerson** [comment]
It is possible that the problem is caused by the syntax error in the example (the use of "= >" rather than "=>").

**Comment by alexander-doroshko** [comment]
WebStorm now switched to code completion powered by the Analysis server. For this sample (if I fix => syntax) there's no completion at all:
![image](https://cloud.githubusercontent.com/assets/4499789/9119010/1a11aeb2-3c7d-11e5-826a-672a51b5296f.png)
Even if I add explicit type annotation:
![image](https://cloud.githubusercontent.com/assets/4499789/9119030/37eb2a80-3c7d-11e5-9c80-177ff65a2c62.png)
But I get some if I remove variable initialization:
![image](https://cloud.githubusercontent.com/assets/4499789/9119054/5409e15c-3c7d-11e5-9fce-8158ae53c027.png)

cc @danrubel

**Comment by bwilkerson** [comment]
In the original example, `f` has a propagated type of `() -> int`, so the type analysis is correct. I'm guessing the code completion engine isn't mapping a FunctionType to the InterfaceType for `Function`.

**Comment by bwilkerson** [comment]
We now suggest both `call` and the methods inherited from `Object`, which I believe are the correct things to suggest.
