### ISSUE TITLE
matchMedia.onChange.listen crashes on FF (38.0.5) and Safari 7.1.6 but works in Chrome

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#23784]
This

``` dart
_screenSizeMediaQuery = dom.window.matchMedia("(max-width: 850px)");
_screenSizeMediaQuery.onChange.listen((_) {
   // Works fine in Chrom but not in FF and Safari
));
```

Dartium works too (clear)

but this

``` dart
// add Listener works????
_screenSizeMediaQuery.addListener( (_) => _screenSizeHandler());
```

works in all three browsers.
I don't know if it's a bug or just poor documentation - but it took me quite a while to figure this out.

BTW: Figuring this out was a nightmare. FF does not support source maps and safari showed quite silly places where it thought the problem occured. Is was more or less a try / recompile / error thing.

**Comment by sethladd** [comment]
caniuse says matchMedia should work in all supported browsers: http://caniuse.com/#feat=matchmedia

**Comment by MikeMitterer** [comment]
True, but as said above - I had this problem and it didn't work.

**Comment by adaojunior** [comment]
I

**Comment by adaojunior** [comment]
+1

it broke my angular app on Safari 9.0.2
```
TypeError: receiver.addEventListener is not a function. (In 'receiver.addEventListener(type, H.convertDartClosureToJS(listener, 1), false)', 'receiver.addEventListener' is undefined)
eval$1isolate_helper.dart:468
startRootIsolateisolate_helper.dart:118
(anonymous function)iterable.dart:275
(anonymous function)iterable.dart:275
(anonymous function)iterable.dart:275
(anonymous function)iterable.dart:275
(anonymous function)iterable.dart:275
```
As @MikeMitterer  said it breaks when I use `onChange.listen`.

**Comment by matanlurey** [comment]
These are very old browsers.
