### ISSUE TITLE
repository name

### ISSUE THREAD

**Issue by layzerar** [dart-lang/sdk#23782]
I suggest renaming this repository from `sdk` to `dart-sdk` or `dart` and adding a `Getting The Source` button in the `GET STARTED` menu at the dart's [homepage](https://www.dartlang.org/).

You see, you cann't find this repository by just type `dart` in github's search engine(https://github.com/search?utf8=%E2%9C%93&q=dart).

**Comment by sethladd** [comment]
Thanks for the suggestion. We have a lot of tools that look for this repository by name. It's unlikely that we'll change it now, unfortunately.
