### ISSUE TITLE
LinkedListEntry hasNext

### ISSUE THREAD

**Issue by Bluenuance** [dart-lang/sdk#23787]
LinkedListEntry should have a convenience getter "hasNext"
so code like
while(item != null) {..}.
can become
while(item.hasNext) {...}

**Comment by lrhn** [comment]
I can see that it would make things easier.
However, the `LinkedListEntrt` class is made to be extended, so adding an extra `hasNext` getter to it may break existing code that already has a method of that name. That doesn't even seem improbable.
I don't think we'll risk that.
