### ISSUE TITLE
Dart Analyzer doesn't understand generic types with the call method

### ISSUE THREAD

**Issue by MichaelFenwick** [dart-lang/sdk#23789]
When attempting to use a generic type for typehinting on the `call` method (either as an argument type or as a return type) the Dart Analyzer uses the generic's name as though it were a literal class name.

See the StackOverflow question at http://stackoverflow.com/questions/31243054/using-darts-call-method-with-generics/31246217 for example code to reproduce the issue.

**Comment by srawlins** [comment]
The analyzer now correctly understands the types in the StackOverflow question.
