### ISSUE TITLE
Support Class?.member in the VM

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23794]
As of b11670f89924c1961be8f93d00848c7fa9887f99, `Class?.member` is interpreted the same as `Class.member`. Currently, the VM treats it as `(Class)?.member`, which throws a `NoSuchMethodError` when accessing static methods.

**Comment by mhausner** [comment]
This is fixed

Committed patchset #1 (id:1) manually as
223e5a6bb5877dd4c3c46cf1f097172c879e8424 (presubmit successful).

**Comment by mit-mit** [comment]
This is commit 223e5a6bb5877dd4c3c46cf1f097172c879e8424, confirmed that this was already merged to the dev channel:

```
mit-macbookpro:sdk mit$ git log a5c19bdb713bd3bd18bb47fe13fc2d9f220078e9

commit a5c19bdb713bd3bd18bb47fe13fc2d9f220078e9
Merge: bfc0565 28611c9
Author: William Hesse <whesse@google.com>
Date:   Tue Aug 11 11:21:05 2015 +0200

    Version 1.12.0-dev.5.2
    
...
    Cherry-pick 223e5a6bb5877dd4c3c46cf1f097172c879e8424 to dev
...
```
