### ISSUE TITLE
Broken error message from the VM when importing wrong uri.

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#23796]
Running the following program:
  import 'packages:e.dart';
  main() {}

Results in:
Unhandled exception:
The null object does not have a getter '_uri'.

NoSuchMethodError: method not found: '_uri'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _handleLoaderReply (dart:_builtin:290)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

The above is impossible to read, please fix the NPE in _handleLoaderReply

**Comment by lrhn** [comment]
Duplicated by issue #23803
