### ISSUE TITLE
Server uses CPU when idle

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#23790]
I'm working on my laptop doing some recreational programming using Dart and Webstorm on my Mac laptop. The laptop is getting a bit hot so I looked into the cause. The Activity Monitor seems to be blaming the Dart Analyzer:

Dart Analyzer is consistently using about 5% CPU when idle. "Idle wakeups" is around 800 which is a lot higher than every other process except the kernel.

On the Energy tab, Webstorm's "average energy impact" is about 20% and if I drill down it's blaming the Dart subprocess for most of it.

Perhaps either the analysis server is doing something when it's supposed to be idle, or WebStorm is polling it? Not sure who to blame. Although, it seems like WebStorm wakeups would be more than 1 if it were polling.

Whatever it is, it seems to be persistent; shutting down WebStorm and starting it back up again results in the same CPU usage.

This is using:
WebStorm 10.0.4
dartanalyzer version 1.11.0.
## 

When I spin up Dart Plugins for Eclipse, I see analysis server idle at around 2%.
It appears this is not unique to IntelliJ.

**Comment by sethladd** [comment]
I have noticed this, too. I simply kill Atom (and the analyzer) if I'm not using it, because it drains battery. This is when it's idle, which is the concerning part.

**Comment by devoncarew** [comment]
My battery usage has been better since I first noticed this. I suspect possibly the move to the new task model helped? As well as atom buffering file overlay changes for very brief times before sending them into the analysis server (w/ the net result of the analysis server doing a lot less work). Removing the flutter label.

**Comment by devoncarew** [comment]
I believe this is no longer the case.
