### ISSUE TITLE
Cast shouldn't be necessary inside if that checks type of a property.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#23798]
[Example](https://dartpad.dartlang.org/df97fcea3b11331872c2)

**Comment by bwilkerson** [comment]
This is working as specified. Unfortunately, type promotion, as defined by the specification, doesn't handle this case:

    if (a.value is B) {
      print(a.value.message);
    }

It only allows the type of *variables* to be promoted. That means that it will handle a slightly modified case:

    var value = a.value;
    if (value is B) {
      print(value.message);
    }

but not the one you care about.

**Comment by jakemac53** [comment]
Is there a technical limitation to this, or is it just the spec which is the limiting factor?

**Comment by bwilkerson** [comment]
Yes. It's the specification, but the specification is limited because it's hard to specify when it's safe to know that the value of a field of an object won't have changed between the type test and the reference to it later in code.

**Comment by jakemac53** [comment]
Ah ok good point, I can see how that would be difficult :)

**Comment by sethladd** [comment]
Imagine if `a.value` is a getter that randomly returns different types :)
