### ISSUE TITLE
Remove flag for null-aware operators in the Analyzer

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23793]
See #23454; null-aware operators are currently implemented, but only behind a flag. Now that they're in the spec, they should be usable by default.

**Comment by sigurdm** [comment]
Proposed patch here: https://codereview.chromium.org/1225273002/

**Comment by sigurdm** [comment]
Landed

**Comment by stereotype441** [comment]
@sigurdm, it looks like you have the wrong bug.  This bug is for null-aware operators in *analyzer*.  Your CL enabled them in dart2js.

**Comment by sethladd** [comment]
The dart2js issue is here: https://github.com/dart-lang/sdk/issues/23791 :)

**Comment by sigurdm** [comment]
Sorry - thanks for fixing it up!

**Comment by sethladd** [comment]
The analyzer now has null-aware operators on by default.

**Comment by stereotype441** [comment]
FYI, I am leaving this bug open because there is some clean-up work in analyzer that is still yet to be done.  But Seth is correct; from a user's point of view the feature is now turned on.

**Comment by sethladd** [comment]
@stereotype441 should we open a new issue to track the cleanup? Technically, this is just about removing the flag.

**Comment by stereotype441** [comment]
@sethladd Ok, submitted #23899 to track the remaining clean-up work.
