### ISSUE TITLE
Allow isolates to be spawned with separate environment constants

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23799]
When spawning an isolate, it would be useful to control what environment constants are available within that isolate. This would be nice for things like `pub run` or the `test` package runner, where the user may specify environment constants on the command line. It can also be looked at as a security feature; if an isolate is used to run untrusted code, the caller may not want the isolate to have access to its environment constants, which may contain secret information.

**Comment by seaneagan** [comment]
Another use case related to pub run here:

**Comment by bkonyi** [comment]
I think this is handled by [Isolate.spawnUri](https://api.dartlang.org/dev/2.0.0-dev.40.0/dart-isolate/Isolate/spawnUri.html)'s `environment` parameter. Closing for now, but please reopen if this isn't resolved.
