### ISSUE TITLE
Ensure all embedder threads initialize their Thread before using VM

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#23807]
Embedder threads that call VM functionality without (or before) entering any isolate will currently not have their Thread structure initialized, thus Thread::Current() is NULL. For now, this is manageable, but it leads to some awkward special casing in our code, and potentially more serious design problems in the future.

We should either:
(a) add an initilization API call that each embedder thread must call before any other VM functionality (possibly excepting the main one that initializes the entire Dart VM), or
(b) always do check+lazy init in Thread::Current

If we opt for (a), we should do it sooner rather than later (since the number of embedders will hopefully only increase). For (b), we need to evaluate the performance impact.

@a-siva

**Comment by rmacnak-google** [comment]
I believe this was addressed by 9e19d236ca83136d49cf54f38a8b551927be70bf
