### ISSUE TITLE
Dart2js elminates code with side-effect.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23806]
The code 
```dart
main() {
  print("Creating list");
  var s = new List(0x100000001);
  print(s.length.toRadixString(16));
  //print(s[0]);
  print("Done");
}
```
Runs without problem and prints the length "100000001".

If the commented out line is reenabled, then the program throws in the `new List` call because the list length is invalid (JS array lengths must be UInt32 values).

The program should throw in both cases (or in neither). 
It seems the check for whether a "new List(n)" call can throw only considers negative values, not too large values, so the list creation is eliminated event if it would have thrown.

**Comment by rakudrama** [comment]
Fixed https://codereview.chromium.org/1431513012/
