### ISSUE TITLE
Install Chrome on all package bots

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23808]
Currently Chrome is only available on the Linux package bots, but it would be good to have it available everywhere.

**Comment by whesse** [comment]
Done - Chrome and Firefox are on the Windows bot, and Chrome is at /Applications/Google Chrome.app on the Mac OS X bots.  The executable is at 
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
