### ISSUE TITLE
Bus error on Raspberry Pi when using mongodb

### ISSUE THREAD

**Issue by laeuter** [dart-lang/sdk#23810]
**What steps will reproduce the problem?**
1. run dart file on command line using mongodb

----------------------------mongotest.dart-----------------------------
import 'package:mongo_dart/mongo_dart.dart';
import 'package:logging/logging.dart';

void main() {
  dbConnection();
}

void dbConnection() {
  Logger.root.level=Level.ALL;
  Logger.root.onRecord.listen((LogRecord rec) {
    print('${rec.level.name}: ${rec.time}: ${rec.message}');
  });
  var db = new Db('mongodb://127.0.0.1/test');
  print("Here");
  db.open().then((success) {
    print("Here B");
    if (success) {
      var _bios = db.collection("std");
      Cursor cur = _bios.find();
      cur.each((Map bio) {
        print(bio);
      });
    }
  });
}

----------------------------pubspec.yaml-----------------------------
name: MongoTest
description: A sample command-line application
dependencies:
  mongo_dart: any

**What is the expected output? What do you see instead?**
Here
Here B
(and data in the db)

But I got

Here
[  724.430982] Unhandled fault: alignment exception (0x001) at 0x75dc6bc5
Bus-Zugriffsfehler

**What version of the product are you using?**
Dart VM version: 1.12.0-edge.9f00e0591816edd4cca0cf349e87b7b4f82cd2e6 (Sun Jun 28 16:19:06 2015) on "linux_arm"

**On what operating system?**
Debian raspbian wheezy on Raspberry Pi 2, but I got the same error late last year when still using Raspberry Pi Model B;

**What browser (if applicable)?**
N/A command line app

**Please provide any additional information below.**
I had hoped that this were resolved by https://github.com/dart-lang/sdk/issues/22384, but apparently it wasn't

cat /proc/cpu/alignment before
User:       0
System:     0 (  (null))
Skipped:    0
Half:       0
Word:       0
DWord:      0
Multi:      0
User faults:    2 (fixup)

cat /proc/cpu/alignment after
User:       3
System:     0 (  (null))
Skipped:    1
Half:       0
Word:       0
DWord:      1
Multi:      1
User faults:    2 (fixup)

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/issues/22151
