### ISSUE TITLE
Dart editor shows that wrong getter inherited

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23813]
Steps to reproduce. 

In Dart Editor create a file with the following code:
```dart
abstract class SI1 {
  int get m1;
}
abstract class SI2 {
  bool get m1;
}
abstract class SI3 {
  Object get m1;
}
abstract class I implements SI1, SI2, SI3 {
}
main() {
  I i = null;
}
```
Now in function main() type the following code: i.
Window with the available methods of interface I appears. It shows that I has getter m1 -> bool
According Dart spec (v 3.0, June 2015) 11.1.1 Inheritance and Overriding "However, if the above rules would cause multiple members m 1 , . . . , m k with
the same name n to be inherited (because identically named members existed
in several superinterfaces) then at most one member is inherited.
...
Otherwise, if the static types T 1 , . . . , T k of the members m 1 , . . . , m k are not
identical, then there must be a member m x such that T x <: T i , 1 ≤ x ≤ k for
all i ∈ 1..k, or a static type warning occurs. The member that is inherited is
m x , if it exists;"

In the example above member that should be inherited is Object get m1;

Tested on Dart Editor version 1.8.5.release (STABLE)
Dart SDK version 1.8.5

**Comment by bwilkerson** [comment]
I believe that this has been fixed. Please re-open the issue if you're still seeing the same behavior.
