### ISSUE TITLE
Windows Installer for SDK + Chromium

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#23818]
Usually I'm using Mac or Linux. Today I installed Dart (SDK) the first timer under Windows and was surprised how uncomfortable the installation was. Download a ZIP???? no. This is not the "Windows way" of installing something. I don't want to unpack, copy the SDK folder somewhere, set the PATH manually... Finally I used chocolatey.org and it worked nicely. But this is also not the Windows-Way. 

Please provide a common installer.

**Comment by sethladd** [comment]
Thanks for the feedback. We should link to Chocolatey in our downloads page. See https://github.com/dart-lang/www.dartlang.org/issues/1343

**Comment by MikeMitterer** [comment]
Thanks - but I think Chocolatey is an option and it's nice but what the average user needs is a Windows-Installer. I was really surprised that I couldn't find one. I think under Windows it's not common to use a package-management - at least for the base installation. If you look at node.js (https://nodejs.org/download/) than you know what I mean. If you want to try out node.js for the first time -  download the installer, confirm everything and you are done.

**Comment by GeKorm** [comment]
I made an installer for 64-bit stable and dev versions. It downloads installs the latest SDK as well as Dartium. It adds /bin to the Path and /dart-sdk to the DART_SDK environment variables.

I can maintain an offline installer as well as 32-bit versions. Tell me what you think.

[Releases here](https://github.com/GeKorm/dart-windows/releases/latest). [Website](http://www.gekorm.com/dart-windows/)

**Comment by MikeMitterer** [comment]
:+1: Cool men!

**Comment by sethladd** [comment]
@GeKorm can you open a request over at https://github.com/dart-lang/www.dartlang.org/issues to mention the installer? thanks!
