### ISSUE TITLE
Dart Editor shows inherited getter but should not

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23817]
Steps to reproduce. In Dart Editor create file with the following code
```dart
abstract class SI1 {
  int get m => 1;
}

abstract class SI2 {
  int get m => 2;
}

abstract class SI3 {
  int m();
}

abstract class I implements SI1, SI2, SI3 {
}

main() {
  I i = null;
}
```
Now in function main() type i.

Actual Result. Tip window with all members of interface I occurs. It shows that I has getter m -> int

Expected result. According Dart Specification (Edition 3.0, June 2015) 11.1.1Inheritance and Overriding 

"However, if the above rules would cause multiple members m 1 , . . . , m k with
the same name n to be inherited (because identically named members existed
in several superinterfaces) then at most one member is inherited.
If some but not all of the m i , 1 ≤ i ≤ k are getters none of the m i are
inherited, and a static warning is issued."

Example above is the case when not all of the inherited interface members are getters so none of them should be inherited and Dart Editor tip window should not show any getter or method named m as a member of interface I

Tested in Dart Editor version 1.8.5.release (STABLE)
Dart SDK version 1.8.5

**Comment by jwren** [comment]
Closing issue.

The warning is issued as it should be.  The spec says nothing about what should or should not be listed in a code completion.  Code completion aims to suggest text that when added will leave the dart source in state in which no additional errors/warnings/hints are added.  In this case however, it is not warning free code-- in fact it does not appear that the invocation site of i.m() is a warning.

It is not unreasonable that the user might want to complete to the method name, and then go back and clean up the warning.

![image](https://cloud.githubusercontent.com/assets/1533520/14801899/f9ab6e0c-0b01-11e6-9c0a-0c2883a4024a.png)
