### ISSUE TITLE
VM observatory: dart2js warnings at compile-time

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#23812]
When building the sdk I get the following two warnings from dart2js when building the observatory. The first one has been around for some time. The second one seems new. We should fix those.

Building observatory... (5.1s) 
[Warning from polymer (PolymerBootstrapTransformer) on observatory|web/index.html]:
We have detected a cycle in your import graph when running initializers on ActionLinkElement. This means the super class ObservatoryElement has a dependency on this library (possibly transitive).
[Info from Dart2JS]:
Compiling observatory|web/index.html.polymer.bootstrap.dart...
[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/observatory/src/elements/service_view.dart:100:9:
dead code
        break;
        ^^^^^^
[Info from Dart2JS]:

**Comment by fsc8000** [comment]
Here is the full warning from dart2js:

[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/observatory/src/elements/service_view.dart:100:9:
dead code
        break;
        ^^^^^^

**Comment by karlklose** [comment]
This should have been fixed in a26a536d865193911b2efe6eb25f72dbb67f3754.

On Thu, Jul 9, 2015 at 11:11 AM, Florian Schneider <notifications@github.com

**Comment by karlklose** [comment]
Oh sorry, this is a new one. Never mind.
