### ISSUE TITLE
Add dartanalyzer warning for missing `@override` annotation on overridden methods

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/sdk#23815]
For projects that don't use the `@override` annotation (or use it inconsistently) and want to switch to using the same, it would be great if `dartanalyzer` provided a warning for all methods that were overridden but without the annotation.

**Comment by lrhn** [comment]
Maybe the analyzer could assume that a package that uses @override in one place wants to use it correctly everywhere, and a package that never uses it doesn't want to, and won't get any warnings about missing @override annotations. 

That means you need to read the entire package to see that override isn't used - so an alternative is to do it per-library instead.

**Comment by johnmccutchan** [comment]
Even better would be if a project could configure this (and other features) on or off for the analysis server / dartanalyze with settings in pubspec.yaml or another configuration file that is a peer to pubspec.yaml

**Comment by seaneagan** [comment]
Maybe this is something for [the linter](https://github.com/dart-lang/linter) which does have on/off configuration for lints?  Although I think the linter was in the process of being integrated into the analyzer last I checked.

**Comment by sethladd** [comment]
We have project-local configurations now. We could give projects the option to toggle this warning on.

**Comment by sethladd** [comment]
cc @pq this is a candidate for analyzer plugins

**Comment by bwilkerson** [comment]
Given that @override is defined in the core library, it seems to me that this functionality ought to be part of the base product.

**Comment by pq** [comment]
This has been implemented as a lint (https://github.com/dart-lang/linter/issues/167).  Docs [here](http://dart-lang.github.io/linter/lints/annotate_overrides.html).

Enable it in analysis options like so:

```
linter:
  rules:
    -  annotate_overrides
```
