### ISSUE TITLE
False suggestion in code completion in IJ integration

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23826]
IJ + DAS, 2015-07-10 build

There completions wouldn't result in code that compiled.

![completion](https://cloud.githubusercontent.com/assets/2978182/8625017/e4769dd4-2733-11e5-9ecf-9dab0f923f42.png)

I suspect that there's a need to add some priority level filtration.

**Comment by lukechurch** [comment]
cc @jwren

**Comment by lukechurch** [comment]
@bwilkerson On further usage, this is actually a release-blocker on the feature. I'm escalating the priority.

**Comment by lukechurch** [comment]
This appears to be suggesting _all_ instances methods that are in scope, independently of whether it is a completion on that instance or not.

**Comment by danrubel** [comment]
Per discussion, this really breaks down into multiple issues:
1) [sort Dart completions by relevancy](https://youtrack.jetbrains.com/issue/WEB-17242)
2) auto import
3) [Don't suggest using classes from "test" in the package implementation](https://github.com/dart-lang/sdk/issues/22358)
4) ... ?

**Comment by jwren** [comment]
The original issue (screenshot) behavior is now fixed.  At this point all I can see this bug doing is tracking the auto import (https://github.com/dart-lang/sdk/issues/21931) and https://github.com/dart-lang/sdk/issues/22358.

Since the issues are tracked elsewhere, closing this issue.
