### ISSUE TITLE
IJ + DAS, no icons in completion dialog

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23829]
IJ usually displays nice icons next to the completions - this helps with visual search of the completion list. They are missing form the completions model that uses DAS.

![completion](https://cloud.githubusercontent.com/assets/2978182/8633563/26beebf0-27c6-11e5-9ee2-40f9ee4b7103.png)

**Comment by bwilkerson** [comment]
I believe that this is a client issue. Please move this issue to the IntelliJ issue tracker.

**Comment by danrubel** [comment]
The underlying information for deciding which icon to display is provided by Analysis Server and used by Dart Plugins for Eclipse to choose the appropriate icon when displaying suggestions.

![image](https://cloud.githubusercontent.com/assets/2891888/8656900/62b3d582-2968-11e5-98c7-72e38061e2e5.png)
