### ISSUE TITLE
Please merge revision 374f9e3941f94b9750cce8e103470c6db4ae0c84 into dev channel

### ISSUE THREAD

**Issue by herhut-ggl** [dart-lang/sdk#23820]
@ricowind @whesse @kasperl
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

This fixed a regression in the new frequency based namer that leads to wrong dispatch on one shot interceptors.

374f9e3941f94b9750cce8e103470c6db4ae0c84

This is a two line change.

**Comment by herhut-ggl** [comment]
Turns out the above CL contains a bug itself. Please also merge 

22ce26bffaa198c1ee0439d9f54b28c7bc3efa64

**Comment by whesse** [comment]
These were in the full push to trunk on July 14, 2015.
