### ISSUE TITLE
VM: Implementing Resource class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23824]
Tracking issue for the VM's implementation of Resource class.

See meta issue https://github.com/dart-lang/sdk/issues/23823

**Comment by sethladd** [comment]
Blocking roll-out of dartdoc in SDK, hence High pri.

**Comment by sethladd** [comment]
Landed in https://github.com/dart-lang/sdk/commit/f63db4960cf66bc0f19ea1eceb4549efead30dfc

Thanks!

**Comment by nex3** [comment]
I'm also curious where the Resource tests live.
