### ISSUE TITLE
Snapshot compatibility

### ISSUE THREAD

**Issue by gmalakov** [dart-lang/sdk#23834]
I have a problem. When I want to deploy an app to a server. I create snapshot. Before version 1.11 I was able to create snapshot on my windows machine and upload it to a linux server without a problem.  Now when I create snapshot with 1.11.1 on windows x32 and upload to a linux x64 with the exactly same version of dart 1.11.1 i get the message "Segmentation fault".
 Dart snapshot compatibility is a great problem because otherwise I have to upload the whole source tree to the server leaving my code unprotected like it's in php and etc.  I hope solution for this will come out soon.
I'm now able to do dart2js --output-type=dart --categories=Server app.dart --out=out.dart
But script says it's deprecated and will not be available on the next version and it leaves also unprotected code.

**Comment by fsc8000** [comment]
Seems like a bug in the VM's snapshot code. It should work across OS platforms.

Do you have a sample file to reproduce the segmentation fault?

**Comment by gmalakov** [comment]
I think that's the one.
It runs on Windows but doesn't run in Linux x64. However if I rebuild on
server. Everything is fine.

2015-07-13 14:45 GMT+03:00 Florian Schneider <notifications@github.com>:

**Comment by gmalakov** [comment]
And is there a opportunity these snapshots to become executable across versions etc if it's built on 1.10 to run on 1.12 across time. That should be very nice indeed.

**Comment by fsc8000** [comment]
Unfortunately, there is no cross-version compatibility of snapshots. Snapshots are only guaranteed to work with the exact same version of the SDK. However, a segfault should not occur. Instead an error message should appear. I don't know of any plans to support this.

Do you have a script that you can share which exhibits your problem (where versions match, but OS platforms are different), so that we can reproduce it locally?

**Comment by gmalakov** [comment]
Yes, the snapshot I sent you is built on 1.11.1 Win x32. It should work on
win32 but shouldn't on Linux x64.

2015-07-13 15:42 GMT+03:00 Florian Schneider <notifications@github.com>:

**Comment by fsc8000** [comment]
Where can I find your snapshot? I does not seem to attached to the issue.

**Comment by gmalakov** [comment]
I sent it with the email. I cannot attach the snapshot there !

**Comment by fsc8000** [comment]
Hm ok. It seems that github does not attach file to issues when replying via email. Can you upload it somewhere else and post ? Or paste sample Dart script here?

**Comment by zoechi** [comment]
It might work to attach it if you change the `.zip` extension to `.jpg`.
You can store the on some cloud drive and post a link here.

**Comment by sethladd** [comment]
Dropbox is also a good way to easily host binaries with public URLs.

**Comment by gmalakov** [comment]
I'll try jpeg variant.
![srv](https://cloud.githubusercontent.com/assets/13311536/8692119/a936973a-2ad3-11e5-84c2-a4e49c1c30f3.jpg)

**Comment by fsc8000** [comment]
Have you tried using the Windows 64-bit version? Snapshots are not compatible between 32- and 64-bit versions of the SDK.

**Comment by gmalakov** [comment]
No but I'm now using Linux x64. that helps

2015-07-15 15:42 GMT+03:00 Florian Schneider <notifications@github.com>:

**Comment by fsc8000** [comment]
Ok,  the issue has nothing to do with Windows. I see the same issue when trying to run a Linux 32-bit snapshot on a 64-bit VM.

The VM should provide a proper error message instead of segfaulting.

**Comment by fsc8000** [comment]
Also tested on bleeding edge and failing:

$ out/ReleaseX64/dart --snapshot=snap.out ~/s/examples/hello.dart 
$ out/ReleaseX64/dart snap.out 
Hello
$ out/ReleaseIA32/dart snap.out 
Segmentation fault (core dumped)

**Comment by gmalakov** [comment]
Thanks for support. I understand now :)

2015-07-15 17:57 GMT+03:00 Florian Schneider <notifications@github.com>:

**Comment by a-siva** [comment]
This is not a VM version compatibility issue, a script snapshot generated on x64 should work on ia32 and vice versa.

When the symbol table was moved into the VM isolate a dependency of the script snapshot on the VM version was introduced, this was fixed in  https://github.com/dart-lang/sdk/issues/23647 but there were some remnants where we were still accounting for the number of VM isolate object ids in the script snapshot and message snapshot writer.
A cl https://codereview.chromium.org/1234803008/ is out for review that should fix this problem.

**Comment by fsc8000** [comment]
Thanks Siva for fixing this! These fixes should also be merged into 1.11.

**Comment by gmalakov** [comment]
That's a pretty fast reaction. Thanks for your replies guys :)

2015-07-16 11:21 GMT+03:00 Florian Schneider <notifications@github.com>:

**Comment by a-siva** [comment]
This cl has been merged into 1.12 so closing issue.
