### ISSUE TITLE
IJ + DAS no types in the completion dialog

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23830]
There is no extra information adornments in the completion dialog, e.g. the type signature of the methods. The scope where it came from etc.

**Comment by bwilkerson** [comment]
We need to determine whether (a) server is not providing the appropriate information or (b) whether the client is not displaying the information.

**Comment by danrubel** [comment]
This is provided by Analysis Server and displayed in Dart Plugins for Eclipse.

![image](https://cloud.githubusercontent.com/assets/2891888/8656763/8dcb6178-2967-11e5-9a9c-1f7972c5f3bc.png)

**Comment by alexander-doroshko** [comment]
That was a problem at IntelliJ IDEA side that is fixed now.
