### ISSUE TITLE
IJ + DAS no function arguments in completion dialog

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23831]
E.g. num.toStringAsFixed takes a single integer as an argument.

However the display in IJ doesn't list any arugments.

**Comment by bwilkerson** [comment]
We need to determine whether (a) server is not providing this information or (b) whether the client is not displaying it.

**Comment by danrubel** [comment]
This information is provided by Analysis Server and shows up in Dart Plugins for Eclipse.

![image](https://cloud.githubusercontent.com/assets/2891888/8656699/391b492c-2967-11e5-9522-279c8a07c8d8.png)

**Comment by bwilkerson** [comment]
I believe that this can be closed now. Assigned to you to double check.

**Comment by scheglov** [comment]
Yes, this feature is implemented in DPI.
