### ISSUE TITLE
XPathNSResolver interface tests broken in analyzer

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23839]
The co19 tests that try to implement the XPathNSResolver interface now fail, because the interface contains new blink js_object methods after revision 4947e570d47bb72a057a2069e83b4e80f48468a3.
https://github.com/dart-lang/sdk/commit/4947e570d47bb72a057a2069e83b4e80f48468a3.

Either the tests are wrong (and createXPathNSResolver should be used), or these methods should not be on the interface.

The problem may be in sdk/lib/html/dartium/html_dartium.dart?

Marking the co19 tests as fail in tests/co19/co19-analyzer2.status.

Here is an example failure message:
FAILED: dart2analyzer-none-checked release_ia32 co19/LayoutTests/fast/xpath/attr-namespace_t02
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_TWO|/mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/xpath/attr-namespace_t02.dart|14|7|17|Missing concrete implementation of setter 'XPathNSResolver.blink_jsObject' and getter 'XPathNSResolver.blink_jsObject'

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --enable_asserts --enable_type_checks --show-package-warnings --enable-async --package-root=out/ReleaseIA32/packages/ --machine --no-hints /mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/xpath/attr-namespace_t02.dart
Took 0:00:00.014000

**Comment by whesse** [comment]
Besides the 8 tests that implement the XPathNSResolver interface, there is another failing test that tries to implement the Rect interface.  Apparently , svg::Rect used to only implement x, y, width, and height, but now it also has  blink_jsObject:

FAILED: dart2analyzer-none-checked release_ia32 co19/LayoutTests/fast/svg/getbbox_t01
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_TWO|/mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/svg/getbbox_t01.dart|63|7|6|Missing concrete implementation of setter 'Rect.blink_jsObject' and getter 'Rect.blink_jsObject'


Command[dart2analyzer]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --enable_asserts --enable_type_checks --show-package-warnings --enable-async --package-root=out/ReleaseIA32/packages/ --machine --no-hints /mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/svg/getbbox_t01.dart
Took 0:00:00.010000

**Comment by terrylucas** [comment]
XPathNSResolver failures resolved a while ago.  These tests are now passing.  There is another bug mentioned in here which getbbox_t01 this tests fails on all non-chrome tests (FF, safari, IE).  Created new issue to track this issue https://github.com/dart-lang/sdk/issues/30014
