### ISSUE TITLE
Dartium checked tests failing WhereIterable<Node> not subtype of Iterable<Element>

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23849]
5 tests are failing on all platforms of Dartium, in checked mode, with the error:
Test failed: Caught type 'WhereIterable&lt;Node&gt;' is not a subtype of type 'Iterable&lt;Element&gt;' 

Tests are:
html/element_test/attributes
html/node_validator_important_if_you_suppress_make_the_bug_critical_test/svg
html/svgelement_test/additionalConstructors
html/svgelement_test/elementget
html/svgelement_test/innerHtml

Suppressing them in tests/html/html.status.
@terrylucas

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1236793006/
