### ISSUE TITLE
dart2js --analyze-only and trivial noSuchMethod

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23843]
If I have a trivial noSuchMethod that calls super.noSuchMethod, dart2js --analyze-only will report these hints:

```
tests/fletch_tests/message_tests.dart:232:3:
Hint: The method 'noSuchMethod' is never called.
Consider deleting it.
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
  ^^^^^^^^^^^^
tests/fletch_tests/message_tests.dart:210:3:
Hint: The method 'noSuchMethod' is never called.
Consider deleting it.
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
  ^^^^^^^^^^^^
```

If I change the methods to:

```
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation) as dynamic;
```

The hint goes away.

**Comment by hterkelsen** [comment]
This hint does an ad-hoc match of the syntax of noSuchMethod implementations. I'll extend the check to catch this case, but in general we can't show a hint for all possible "inactive" noSuchMethod implementations.
