### ISSUE TITLE
Make dart:html works in standalone DartVM

### ISSUE THREAD

**Issue by Thiltal** [dart-lang/sdk#23847]
I can import [html](https://github.com/dart-lang/html) library working with HTML on server. The problem is in sharing the code between server and client. The Document class from pub library is another class than the Document class from dart:html. There is no way how to write a library, working both, on server and on client making real manipulation with browse's DOM.

DartVM should run a barebone dartium, without pixel rendering and events, simulating some part of browser's behavior.

**Comment by sethladd** [comment]
We're working on a configurable import scheme, which should allow someone to write a library that works across multiple Dart times.

cc @kevmoo @munificent who might be able to link to the right page?

**Comment by munificent** [comment]
See: https://github.com/munificent/dep-external-libraries/blob/master/Proposal.md

Though that is different from what's being requested here. Even with configuration-specific code, you still can't take a library that uses "dart:html" and run it on the standalone VM. You would instead have to make some platform-independent wrapper around "dart:html" and then convince everyone to use that, *then* you could run those libraries on the standalone VM.

**Comment by sethladd** [comment]
@munificent good point, thanks for the clarification.

**Comment by Thiltal** [comment]
It could be enough for our work. Thanks
