### ISSUE TITLE
Stream#take() Drops Generic Type Variable

### ISSUE THREAD

**Issue by jriggins** [dart-lang/sdk#23859]
I'm new to the process but I created a [CL](https://codereview.chromium.org/1238143003/) with tests and proposed fix to exhibit the issue.

Basically the `Stream` returned from `Stream#take()` will pass any type check with explicit type parameters because it is a generic `Stream` and not a `Stream<T>`.

**Comment by floitschG** [comment]
With the unified frontend and Dart 2.0, this will be fixed.
The API of `Stream.take` already states that the returned stream is a `Stream<T>`.
