### ISSUE TITLE
convert/line_splitter_test fails in Chrome/Firefox on Windows

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#23856]
Seems likely to be some kind of line delimiter error.

See, e.g. https://uberchromegw.corp.google.com/i/client.dart/builders/full-win7-ie11-2-4-be/builds/4689

**Comment by alan-knight** [comment]
Suppressed in https://codereview.chromium.org/1236793011/

**Comment by mit-mit** [comment]
@lrhn , @floitschG , any updates on this one?

**Comment by lrhn** [comment]
The bug is either in the test, dart2js, the VM or the language specification, depending on your point of view.
I can fix the test.

**Comment by mit-mit** [comment]
Great, thanks

**Comment by lrhn** [comment]
Fixed (committed by pquitslund)
