### ISSUE TITLE
dart2js: deferred fragments should not steal a type if it's used in type arguments of the main fragment

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23853]
Consider this example:

**repro.dart:**
```dart
import 'c.dart';
import 'b.dart' deferred as b;

class TypeLiteral<T> {
  Type get type => T;
}

class A {}

main() {
  print(new TypeLiteral<C<A>>().type);
  b.loadLibrary().then((_) => b.createC());
}
```

**b.dart**:
```dart
import 'c.dart';

createC() => new C();
```

**c.dart**:
```dart
class C<T> {}
```

The type `C` is used directly in the deferred library `b`, but also indirectly by the main library when printing the type arguments of the TypeLiteral.

The current output produced by dart2js includes `C` in b's fragment, rather than the main fragment. As a result, the main fragment fails with an error of the form:
```
TypeError: Cannot read property 'builtin$cls' of undefined
    at dart.runtimeTypeToString (out.js:2396:22)
    at dart.main (out.js:5331:32)
    at _IsolateContext.dart._IsolateContext.eval$1 (out.js:1131:25)
    at dart.startRootIsolate (out.js:814:23)
```

**Comment by sigmundch** [comment]
@sigurdm @floitschG

**Comment by floitschG** [comment]
Adding to the analysis: it requires a generic class (`class C<T>`) to crash, but even without it the result is wrong. That is, a `List<C>` (or `TypeLiteral<C>` in the example) doesn't crash, but silently replaces the `C` with `dynamic`. Dart2js uses `undefined` as `dynamic` and when it sets the generic type it accesses a non-existing property, thus replacing `C` with `undefined`/`dynamic`.
