### ISSUE TITLE
Please merge revision 735e5a3eb4a5028eac3399679b3dcd51360d97c6 into stable channel

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23850]
@ricowind @whesse @kasperl

This fixes a crash in the WebSocket code caused by closing a socket after its stream subscription has been canceled

Please merge 735e5a3eb4a5028eac3399679b3dcd51360d97c6.

This merged cleanly.

**Comment by whesse** [comment]
This was merged in version 1.11.2, released in 1.11.3.
