### ISSUE TITLE
take full advantage of github features in our bug tracker

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23860]
It would be great to:
- use colors!
- allow/add sub-team labels (subcategorize issues)
- use a clean naming convention that looks nice in the github UI (no caps, no dashes)
- do a happy dance every time a bug is fixed

I like the current approach taken by the angular team: https://github.com/angular/angular/issues.

@dgrove @sethladd @kevmoo

**Comment by sethladd** [comment]
Need to find Michael Thomsen's GitHub ID :)
