### ISSUE TITLE
Move github/kevmoo/shelf_static.dart to github/dart-lang

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23866]
If this package is needed, it should be on dart-lang, and it should be mirrored to chromium.googlesource.com.  We are not supposed to have any direct github fetches from non dart-lang repos, and all repos are supposed to be mirrored to googlesource.

Is this still needed?  If so, can we add the dart-lang repo?

@kevmoo @whesse @rico

**Comment by kevmoo** [comment]
Where is this being used?

**Comment by kevmoo** [comment]
Answered my own question: https://github.com/search?utf8=%E2%9C%93&q=shelf_static+user%3Adart-lang+extension%3Ayaml&type=Code&ref=advsearch&l=

pkg/test and the dev_compiler

**Comment by whesse** [comment]
Yes, so please coordinate with them about what should be done.  Thanks!

On Mon, Jul 20, 2015 at 6:41 PM, Kevin Moore <notifications@github.com>
wrote:

> Answered my own question:
> https://github.com/search?utf8=%E2%9C%93&q=shelf_static+user%3Adart-lang+extension%3Ayaml&type=Code&ref=advsearch&l=
>
> pkg/test and the dev_compiler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23866#issuecomment-122944248>.
>



-- 
William Hesse

**Comment by kevmoo** [comment]
See https://codereview.chromium.org/1241153003/
