### ISSUE TITLE
`analysis.updateOptions` throws exceptions if optional fields aren't passed in

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23863]
`analysis.updateOptions` throws exceptions if optional fields aren't passed in. For instance, if I want to just set `enableNullAwareOperators`, I get an exception back:

```
Uncaught Uncaught Error: [RequestError code: INVALID_PARAMETER,message: Invalid parameter 'params.options.enableAsync'. Expected to be bool.]
```

This means that I have to pass in all the currently known options when I want to just set one. And it means that I'll have trouble communicating with an analysis server that understands more parameters then I currently send in.

**Comment by bwilkerson** [comment]
I cannot reproduce the behavior you're describing. Sending a request with a single option defined ("{options: {enableNullAwareOperators: true}}") works for me without producing an error.

Is there a stack trace to go with the error message?
Can you capture the JSON encoding of the request that's being sent?

If not, I have a CL out (https://codereview.chromium.org/1246573002/) that should get us a little more information. Please re-run the code after this CL has landed.

**Comment by devoncarew** [comment]
If it helps, I'm running with the analysis server from Dart VM version: 1.12.0-dev.1.0.

**Comment by devoncarew** [comment]
And, I now suspect that I'm passing in `null` for the unspecified values. Let me confirm.

**Comment by devoncarew** [comment]
Yup, we were providing values for the fields we were interested in, and passing in `null` for all other fields. I switched to just passing in values for fields being used and things are working smoothly :)
