### ISSUE TITLE
`CompletionSuggestion.parameterType` field is not populated

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23861]
It doesn't look like the field `CompletionSuggestion.parameterType` is ever populated for named parameter completions. See also https://github.com/dart-atom/dartlang/issues/74.

**Comment by sethladd** [comment]
Should this be labeled Analyzer-Completion ?

**Comment by devoncarew** [comment]
@danrubel, is this one of the things that requires a rewrite for the new task model, or could it be completed w/o a re-write?

**Comment by jwren** [comment]
Will be fixed soon: https://codereview.chromium.org/1864243002/

**Comment by jwren** [comment]
Change just landed.  Feature should be in 1.16

**Comment by devoncarew** [comment]
:tada:
