### ISSUE TITLE
The analyzer seems to have issues with very big constants

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#23870]
I have a constant with lots of const symbols (2000+), and the analyzer fails with: "Evaluation of this constant expression causes exception".

**Comment by stereotype441** [comment]
@floitschG any chance you can point me to some code that demonstrates the problem?  It might make it faster to debug.

**Comment by floitschG** [comment]
https://chromiumcodereview.appspot.com/1238303002/

**Comment by stereotype441** [comment]
Looking at the line numbers where the failures are reported, the constant expressions that analyzer claims lead to exceptions are:

    const Symbol('do')
    const Symbol('if')
    const Symbol('in')
    const Symbol('is')

All of which are keywords.  The documentation for the Symbol constructor (sdk/lib/core/symbol.dart) says (in part):

    * The name must be a valid public Dart member name,
    * public constructor name, or library name, optionally qualified.
    *
    * A qualified name is a valid name preceded by a public identifier name
    * and a '`.`', e.g., `foo.bar.baz=` is a qualified version of `baz=`.
    * That means that the content of the [name] String must be either
    *
    * * a valid public Dart identifier
    *   (that is, an identifier not starting with "`_`"),
    * * such an identifier followed by "=" (a setter name),
    * * the name of a declarable operator
    *   (one of "`+`", "`-`", "`*`", "`/`", "`%`", "`~/`", "`&`", "`|`",
    *   "`^`", "`~`", "`<<`", "`>>`", "`<`", "`<=`", "`>`", "`>=`", "`==`",
    *   "`[]`", "`[]=`", or "`unary-`"),
    * * any of the above preceeded by any number of qualifiers,
    *   where a qualifier is a non-private identifier followed by '`.`',
    * * or the empty string (the default name of a library with no library
    *   name declaration).

Keywords like `do`, `if`, `in`, and `is` are not valid public Dart identifiers.  Here's the relevant spec text, from section 20.1.1 (Reserved Words):

> A reserved word may not be used as an identifier; it is a compile-time error if a reserved word is used where an identifier is expected.
> **assert, break, case, catch, class, const, continue, default, do, else, enum, extends, false, final, finally, for, if, in, is, new, null, rethrow, return, super, switch, this, throw, true, try, var, void, while, with**.

**So I believe that analyzer is correct to report an error in this situation.**

Unfortunately, neither dart2js nor the VM properly report the required compile-time errors in this situation (see #11669, #13596, and #19972).  These bugs don't seem to be getting much attention (one of them is two years old!), so I propose that we modify the test to avoid the problematic symbols.  I'll submit a CL to that effect.

**Comment by floitschG** [comment]
Thanks for the fix. It would be nice if the analyzer reported why it failed, though.
