### ISSUE TITLE
Dart analyzer: nor compile-error nor static warning for wrong mixin application

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23878]
Steps to reproduce/
1. Create Dart file with the following code:

``` dart
class S {
  bool get g => false;
}

class M {
  int get g => 1;
}

class C = S with M;

class S2 {
  bool get m => false;
}

class M2 {
  int m() => 1;
}

class C2 = S2 with M2;

main() {
}
```
1. Run it in dart analyzer

Actual result: no warning, no compile-time error

Expected result: According Dart specification (Edition 3, June 2015) 12.1 Mixin Application

> "Let K be a class declaration with the same constructors, superclass and in-
> terfaces as C, and the instance members declared by M (respectively M 1 , . . . , M k ).
> It is a static warning if the declaration of K would cause a static warning. It is
> a compile-time error if the declaration of K would cause a compile-time error.
> If, for example, M declares an instance member im whose type is at odds with
> the type of a member of the same name in S, this will result in a static warning
> just as if we had defined K by means of an ordinary class declaration extending S,
> with a body that included im."

So the should be a static warning and compile-time error respectively because M declares getter with the same name as S but its type odds with the getter declared in S and getter and method with the same names

Tested in dartanalyzer version 1.11.0-edge.45833

**Comment by srawlins** [comment]
Analyzer now reports correct issues about inconsistent inheritance:

```none
Analyzing 23878.dart...
  error • Superinterfaces don't have a valid override for 'g': S.g (bool Function()), M.g (int Function()). • 23878.dart:9:7 • inconsistent_inheritance
  error • 'M.g' ('int Function()') isn't a valid override of 'S.g' ('bool Function()'). • 23878.dart:9:18 • invalid_override
  error • 'm' is inherited as a getter (from 'S2') and also a method (from 'M2'). • 23878.dart:19:7 • inconsistent_inheritance_getter_and_method
  error • Superinterfaces don't have a valid override for 'm': S2.m (bool Function()), M2.m (int Function()). • 23878.dart:19:7 • inconsistent_inheritance
```
