### ISSUE TITLE
Implement DateFormat time zone formatting

### ISSUE THREAD

**Issue by ajsergeev** [dart-lang/sdk#23879]
v,z patterns don't work because:

  String formatTimeZoneId(DateTime date) {
    // TODO(alanknight): implement time zone support
    throw new UnimplementedError();
  }

  String formatTimeZone(DateTime date) {
    throw new UnimplementedError();
  }

  String formatTimeZoneRFC(DateTime date) {
    throw new UnimplementedError();
  }

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/intl#74
