### ISSUE TITLE
add a `has quick fix` metadata flag on analysis errors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23874]
It would be nice to be able to display when an error has an associated quick fix. This way the user will know when to select it and hit `ctrl-1`.

See also https://github.com/dart-atom/dartlang/issues/89.

**Comment by bwilkerson** [comment]
@scheglov 

My guess is that it wouldn't be performant to compute the quick fixes for errors at the point at which we're reporting them, especially in cases where parser recovery has failed and we have lots of extraneous errors. Konstantin, correct me if I'm wrong.

We could potentially approximate a value, basically a "this error *usually* has a quick fix" flag, but that would probably be worse than no data when we get it wrong.

**Comment by devoncarew** [comment]
Are there errors where we always know that there are quick fixes? I agree that false positives wouldn't be good.

**Comment by scheglov** [comment]
No, practically all of the fixes generators do some checks to decide
whether it is possible to produce a fix.

On Mon, Jul 20, 2015 at 1:13 PM, Devon Carew <notifications@github.com>
wrote:

> Are there errors where we always know that there are quick fixes? I agree
> that false positives wouldn't be good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23874#issuecomment-123016001>.
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.

**Comment by bwilkerson** [comment]
Which means, yes, there are some, but there are very few.

Also, false negatives might be equally bad because users would have a hard time discovering that there are sometimes fixes where none are indicated.

Did we have this indicator in Editor prior to moving to the analysis server? If so, how did we do it?

**Comment by scheglov** [comment]
Yes, we did have this indicator.
  And we checked only ErrorCode, without checking whether the fix can be
actually produced.
  So, there were false positives.

On Mon, Jul 20, 2015 at 1:30 PM, Brian Wilkerson <notifications@github.com>
wrote:

> Which means, yes, there are some, but there are very few.
>
> Also, false negatives might be equally bad because users would have a hard
> time discovering that there are sometimes fixes where none are indicated.
>
> Did we have this indicator in Editor prior to moving to the analysis
> server? If so, how did we do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23874#issuecomment-123024833>.
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.

**Comment by devoncarew** [comment]
Do you have a sense for the performance indication of checking whether any quick fixes actually apply to a specific issue, after first filtering them for types of errors that might have quick fixes? So, checking first on ErrorCode, and then on the specific error?

**Comment by scheglov** [comment]
The existing edit.getFixes request already does something like this - it
checks for ErrorCode and then attempts to create a fix.
  So, in theory we could ask fixes for each error.

  But no, I don't know how fast or slow it might be.

On Mon, Jul 20, 2015 at 1:56 PM, Devon Carew <notifications@github.com>
wrote:

> Do you have a sense for the performance indication of checking whether any
> quick fixes actually apply to a specific issue, after first filtering them
> for types of errors that might have quick fixes? So, checking first on
> ErrorCode, and then on the specific error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23874#issuecomment-123034912>.
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.

**Comment by lukechurch** [comment]
+1

**Comment by scheglov** [comment]
We cannot compute all the fixes at the time when we send errors - it is just too expensive.
If clients don't want to have the flag `usuallyHasQuickFix`, then it is `WontFix`.

**Comment by devoncarew** [comment]
From talking to @jwren and reviewing the dartpad source, both clients (IntelliJ and dartpad) get this data on demand as errors are reported to them. They do this by making an analysis server call per error that is reported. So that's `n` IPC calls, which is much more expensive than if done in process in the analysis server itself.

If `usuallyHasQuickFix` will have a low rate of false positives, then it would be a good stand-in for `hasQuickFix`.

Otherwise I would want a way for a client to opt in to the extra cost of an accurate `hasQuickFix` flag on errors. The number of errors in a project is generally low, and giving users a clear and easy way to resolve them is important.

**Comment by bwilkerson** [comment]
> So that's n IPC calls ...

(where 'n' is the number of errors in a file).

> The number of errors in a project is generally low ...

Then the number of errors in a file must be low as well. I'm not convinced that you can't make those 'n' calls for now while we work on higher priority issues.

I'd like to see an experiment that proves that the time is too great before we prioritize this above other work.

**Comment by scheglov** [comment]
Actually we have a trick we used for Quick Assists integration in IDEA.

We just cannot request all the possible Quick Assists in a file.
So, instead we always add 10 of them, but request and enable in `isAvailable`.
This way we could avoid creating fixes for the errors the user never selects or even sees.

**Comment by devoncarew** [comment]
> (where 'n' is the number of errors in a file).

`n` is the number of errors reported by the analysis server for the all the created contexts. We pass all the errors to the linter, and need the quick fix availability info at the time that the issues are created,

**Comment by bwilkerson** [comment]
> We pass all the errors to the linter, and need the quick fix availability info at the time that the issues are created,

I'm not sure what the "linter" is, but if this means what I think it means (that you cannot wait to determine which, if any, fixes are available for an error until the user requests to see them) then the framework is broken. It just won't scale.

**Comment by alexander-doroshko** [comment]
In IntelliJ we ask server for quick fixes only for the error that is under caret (and cache received quick fixes until file contents change). If there are any then we show a bulb - user get understanding that fixes are available and he can click the bulb or press Alt+Enter. For errors that never were under caret we do not care if quick fixes exist or not.

**Comment by devoncarew** [comment]
To clarify this request, we'd like to display a badge in the problems view

<img width="608" alt="screen shot 2015-09-30 at 3 56 41 pm" src="https://cloud.githubusercontent.com/assets/1269969/10209008/7089c006-678c-11e5-8943-c510449cfb9a.png">

indicating when an issue has a quick fix. This will make the quick-fix feature discoverable; currently it has very poor discovery. The problems view displays all the errors for the current project. The issues themselves are managed by the `linter` package in Atom; we create the linter items when they are reported to us by the analysis server. The only on-demand part of this is when we create a menu with the quick fixes available at a particular source location, when the user hits `ctrl-1` there.

The current plan is for @pq to investigate the performance impact so we can know what the cost will be to clients.

**Comment by scheglov** [comment]
I agree with @bwilkerson - it's not scalable.

Even if there are no quick fixes that are slow now, preparing and sending all of them at the time when we send errors notification will limit us in what we can do in quick fixes. If it's an interactive operation, user can wait 100-200 ms. If it's something what should be done for every error, and we have just 5 such error, user definitely does not want to wait 500-1000 ms to get errors refresh. And we, as AS developers cannot afford pausing the whole AS for 500-1000 ms.

**Comment by clayberg** [comment]
Devon can correct me if I'm wrong, but the analysis server only needs to return a boolean indicating the existence of any quick fix for each error, not the full list of all quick fixes for every error. Obviously, that will take some amount of extra work, but that should be up to the client to decide if it wants to take the hit. Give Devon the ability to opt in to that extra bit of analysis and get the results back he needs. It does not need to affect any other client that does not need that level of detail for its problems view. Otherwise, you are essentially saying that you can't handle an important client need like this, and I don't think that is very helpful. I think we need to think more about how to provide the client with the minimal amount of data it needs in a reasonable amount of time. Or come up with an alternative solution for Devon that will work with the Atom architecture.

**Comment by pq** [comment]
Is there a distinction to be made between fixes (fast) and assists (maybe slow)?

Besides that, I like Eric's suggestion of an opt-in `FIXES_HINT` parameter of the `getErrors` request.  I'm guessing that we could very quickly flag problems that currently have associated fixes.  In tough cases we could maybe settle for a heuristic and live with a few false positives.  Incidentally: do we have any existing tough cases or are we more concerned with future-proofing?

**Comment by scheglov** [comment]
Future-proofing.

Does Atom use `getErrors`? I though it uses `analysis.errors` subscription.

Well, if we allow some false positives, then this feature is easier and can be done with some shortcuts.

BTW, we need these flags only for priority files, right?
The user cannot see other errors.
So, it could be an additional subscription.

**Comment by clayberg** [comment]
I was assuming this was for fixes only (to show a badge in the problems view) and could either apply to the priority files (just open editors) or all files in the project if all the errors are being displayed (Devon?). I assume quick assists apply to the open, visible files and would show a badge in the source view. That would be a separate issue.

**Comment by bwilkerson** [comment]
>  ... the analysis server only needs to return a boolean indicating the existence of any quick fix for each error ...

Maybe. We'd prefer to show the availability of a quick fix, but the existence of a quick fix might be a reasonable substitute. (The distinction I'm drawing is this: some quick fixes are only available in certain contexts, but always exist as a potential.)

> Obviously, that will take some amount of extra work, but that should be up to the client to decide if it wants to take the hit.

It also impacts the performance of the rest of server. It's our job to evaluate the reasonableness of such requests. We're not saying 'no', we're evaluating alternatives.

> I was assuming this was for fixes only ...

Yes, this is for fixes only, not for assists.

> BTW, we need these flags only for priority files, right?

No, we need this flag for all errors, not just those in priority files. They show up in the problems view and that's where they want the badge.

We had a meeting yesterday and have a path forward. Phil is going to try an experiment to see how many false positives there would need to be and what the cost is. We'll make a decision about this feature after we have more data.

**Comment by clayberg** [comment]
Having a small percentage of false positives would be much more preferable than nothing in this case. If it is an opt in piece of information, would it affect the performance for clients that did not opt in? I also assume that the fewer errors there are reported in the project, the less of a performance hit we would take. I think showing the existence of a quick fix would be fine. If there are cases where it actually doesn't apply, we can tell the user that at the time (assuming there are no other quick fixes that are available). What we need here is something that is good 99% of the time rather than bad 100% of the time as it is now.

**Comment by pq** [comment]
Based on a conversation with @scheglov this afternoon, here's a quick cut:

https://codereview.chromium.org/1385523002/

**Comment by clayberg** [comment]
That looks like it should be very quick. If it does what Devon needs, ship it!

**Comment by pq** [comment]
Landed in 8697392367be57f9f595abca0cd106c2f3e56f3e.

Issue to track false negatives: https://github.com/dart-lang/sdk/issues/24496.

**Comment by sethladd** [comment]
Thanks!
