### ISSUE TITLE
Implement errorsAreFatal, onExit and onError parameters to the spawn functions

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#23876]
dart2js needs to implement the newly added optional parameters for the spawn functions which have been added as part of https://codereview.chromium.org/1240743003/.

**Comment by karlklose** [comment]
The tests for this feature on dart2js (error_exit_at_spawn_test, error_at_spawn_test, exit_at_spawn_test) timeout on browsers. Skipping them for now (see https://codereview.chromium.org/1240243003).
