### ISSUE TITLE
Directory.watch on OS X can report events that happened while it wasn't watching

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23877]
If a subscription to `Directory.watch` is created, canceled, and re-created it can receive events that occurred while it wasn't listening. [This is causing flakiness on the `watcher` package bots](http://build.chromium.org/p/client.dart.packages/builders/packages-mac-watcher/builds/384/steps/annotated_steps/logs/stdio). An easy reproduction is to run the following code:

``` dart
import 'dart:async';
import 'dart:io';

Future printNextEvent(String path) {
  var completer = new Completer();
  var sub;
  sub = new Directory("test").watch().listen((event) {
    print(event);
    sub.cancel();
    completer.complete();
  });

  return completer.future;
}

main() async {
  new Directory("test").createSync();

  var future = printNextEvent("test");
  await new File("test/one.txt").writeAsString("");
  await future;

  await new File("test/two.txt").writeAsString("");

  printNextEvent("test");
  await new File("test/three.txt").writeAsString("");
}
```

Notice that it prints events for `one.txt` and `two.txt`, rather than for `one.txt` and `three.txt` as you'd expect (and as it does on Linux).

See also #14373.

**Comment by brianquinlan** [comment]
This behavior is [now documented](https://github.com/dart-lang/sdk/blob/main/sdk/lib/io/file_system_entity.dart#L437).

It is hard to avoid this behavior on OS X without taking a large performance hit.
