### ISSUE TITLE
Toplevel variable valid entry point for script?

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#23887]
Is this script supposed to run and print 'hest'?

```dart
var main = () => print('hest');
```

The VM says yes, dart2js complains that main is not a function (warning + compile-time error).

The spec seems to be a bit undecided:

> "A script is a library whose exported namespace (18.2) includes **a top-level
> member named main**. It is a static warning if the static type of main is not
> assignable to a function type or is a function type with more than two required
> parameters.
>
> A script S may be executed as follows:
> First, S is compiled as a library as specified above. Then, **the top-level
> function main** that is in the exported namespace of S is invoked."

**Comment by zoechi** [comment]
It should work - see #21535

**Comment by lrhn** [comment]
It should no longer work. In Dart 2 we require that main is a function declaration.
