### ISSUE TITLE
Webstorm: Issue with settings breakpoints while debugging in unchecked mode.

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#23889]
**Summary:**
When Dartium is running in unchecked mode there is an issue with setting breakpoints while debugging an application 

Normally, when setting a breakpoint at an assert statement the breakpoint will occur at the program location following that statement (that is, when running in unchecked mode). However, if a breakpoint is already present at that location, the breakpoint will instead be disabled.
Furthermore, any attempt to reenable the breakpoint fails as long as the breakpoint at the assertion statement is present (at least until the application is restarted). 

While this particular issue is probably less relevant, I experienced a similar issue where it became impossible to change any breakpoints at all while the application was running . When this occured (it happened twice), I had to restart webstorm entirely to fix the issue. The exact steps to reproduce that issue could however not be found.

**What steps will reproduce the problem?**
1) In webstorm, create a new Dart 'Uber Simple Web Application'
2) Change the content of main.dart to the following:
```
import 'dart:html';

void main() {
  querySelector('#output').text = 'Your Dart app is running.';
  querySelector('#output').onClick.listen(foo);
}

foo(event) {
  assert(false);

  var bar = 42;
}
```
3) Navigate to Settings/Languages & Frameworks/Dart and make sure that 'Start Dartium in checked mode' is disabled.
4) Add a breakpoint at the line containing  `var bar = 42;`
5) Run the application with debugging enabled
6) In Dartium click the 'Your Dart app is running' text and observe that the breakpoint triggers.
7) Add a breakpoint at the line containing ```assert(false);``` and resume the application
8) In Dartium click the 'Your Dart app is running' text again
**What is the expected output? What do you see instead?**
*Expected:*
The program halts at the location corresponding to ```var bar = 42;```

*Actual:*
The program continues as normal.

**What version of the product are you using?**
Webstorm 10.0.4
Dart SDK: 1.12.0-dev.4.0

**Comment by sethladd** [comment]
Hi, can you please file this WebStorm issue over in the WebStorm/JetBrains issue tracker? https://youtrack.jetbrains.com/

I'm going to close this issue, but we appreciate the report and please do file it with JetBrains. Thanks!

**Comment by zoechi** [comment]
Could be an SDK issue. Trying to reproduce in Observatory debugger might show where the bug lies.
