### ISSUE TITLE
Dart semantics depends on newline encoding

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#23888]
The specification of multiline string is underspecified wrt. the semantics of a newlines.

This introduces the risk that the Dart semantics depends on newline encodings and thus changes upon checkout if the revision system normalizes newline encodings, as is now the case for our own dart-lang/sdk repository.

The VM normalizes occurrences of '\n', '\r', and '\r\n' to a '\n' within a multiline string—which is the preferred behavior since it removes the semantic instability.
The analyzer and dart2js takes '\n', '\r' and '\r\n' verbatim thus making them semantics vulnerable to newline encodings. See the tests in tests/language/multiline_newline_test.dart.

This bug is spec-wise related to dartbug.com/14073 

@kasperl

**Comment by lrhn** [comment]
This hit another test (lib/convert/line_splitter_test.dart) which used multi-line strings as test data, and which failed with Windows line endings.

**Comment by johnniwinther** [comment]
Issue #23020 also relates to this.

**Comment by munificent** [comment]
Marking this as a duplicate of #23562, which is older.
