### ISSUE TITLE
Cannot execute `getField` twice on operator name.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#23880]
Consider the following three programs:

```dart
// Program 1: Demonstrate issue with repeated `getField` doing a tear-off on
// an operator, based on an `int` instance.

import 'dart:mirrors';

main() {
  Symbol memberNameSymbol = new Symbol("+");
  InstanceMirror instanceMirror1 = reflect(1);
  ClosureMirror closureMirror1 = instanceMirror1.getField(memberNameSymbol);
  InstanceMirror instanceMirror2 = reflect(2);
  ClosureMirror closureMirror2 = instanceMirror2.getField(memberNameSymbol);
}

// Program 2: Demonstrate issue with repeated `getField` doing a tear-off on
// an operator, based on an instance of a user-defined class.

import 'dart:mirrors';

class C {
  operator +(int i) => 42;
}

main() {
  Symbol memberNameSymbol = new Symbol("+");
  InstanceMirror instanceMirror1 = reflect(new C());
  ClosureMirror closureMirror1 = instanceMirror1.getField(memberNameSymbol);
  InstanceMirror instanceMirror2 = reflect(new C());
  ClosureMirror closureMirror2 = instanceMirror2.getField(memberNameSymbol);
}

// Program 3: Demonstrate that there is no issue with repeated `getField` doing
// a tear-off on a non-operator.

import 'dart:mirrors';

class C {
  int f(int i) => 42;
}

main() {
  Symbol memberNameSymbol = new Symbol("f");
  InstanceMirror instanceMirror1 = reflect(new C());
  ClosureMirror closureMirror1 = instanceMirror1.getField(memberNameSymbol);
  InstanceMirror instanceMirror2 = reflect(new C());
  ClosureMirror closureMirror2 = instanceMirror2.getField(memberNameSymbol);
}
```

On the vm, the third program runs with no output (and no errors). When executed by the vm, program 1 and 2 print the following error message:

```
'evaluate:source': error: line 1 pos 16: identifier expected
() => (x) => x.+;
               ^
```

The error only occurs when the `getField` operation is executed twice (comment out the line containing the last invocation of `getField` and the programs run without problems), and only when the symbol is the name of an operator (see program 3).

Maybe there is some kind of state involved that is produced by the first invocation of `getField` and which is somehow corrupting the second invocation of `getField`?  Note that it makes no difference whether we perform this test on the same instance mirror twice, or we create a new one (it still fails if the declaration of `instanceMirror2` and its initialization is deleted, and `instanceMirror2` is changed to `instanceMirror1` in the last line). But the fact that the error occurs with two different instance mirrors illustrates that it isn't state inside a single instance mirror that creates the problem.

**Comment by rmacnak-google** [comment]
Right, there are two implementations of getField in the VM, a slow path and a fast path. The fast path only kicks in if a given symbol is accessed repeatedly, and it doesn't handle closurizing operators.

**Comment by rmacnak-google** [comment]
bc90a5e1f043e3c47b725721a6d0670cf7e91ec4
