### ISSUE TITLE
Isolate.spawn[Uri] - document errorsAreFatal, onExit, onError in Changelog

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23884]
....and remove the "not implemented" note to the doc comments.

**Comment by mit-mit** [comment]
@lrhn , @kevmoo, what is the status of this bug?

**Comment by lrhn** [comment]
All done, except that the dart2js implementation seems to not work - the program dies before the onDone message comes back.

**Comment by lrhn** [comment]
And now it works too.
