### ISSUE TITLE
Update analyzer_cli and analysis_server for null-aware operator support.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23899]
Null-aware operators are now enabled by default in analyzer (see #23793).  Since most users get their version of analyzer via the sdk, and the sdk builds from bleeding edge, this means that the feature is enabled in the users' hands.  However, we still need to the following clean-up tasks:

- Update analyzer_cli to depend on a version of analyzer that has null-aware operators turned on by default.
- Deprecate analyzer_cli's command-line option for null-aware operators.
- Update analysis_server to depend on a version of analyzer that has null-aware operators turned on by default.
- Deprecate analysis_server's wire API option for null-aware operators.

**Comment by sethladd** [comment]
Nice, thanks!
