### ISSUE TITLE
Many tests timing out flakily on macos chrome 44

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23891]
These tests all timed out once on chrome 44, but none have been seen to time out twice.  Not suppressing them yet, since none have repeated.

```
  1 html/custom/attribute_changed_callback_test/fully_supported  Pass   Timeout
  1 html/custom/created_callback_test  Fail   Timeout
  1 html/custom/entered_left_view_test/disconnected_subtree  Pass   Timeout
  1 html/custom/js_custom_test  Pass   Timeout
  1 html/cssstyledeclaration_test  Pass   Timeout
  1 html/node_validator_important_if_you_suppress_make_the_bug_critical_test/DOM_sanitization  Pass   Timeout
  1 html/xhr_test/xhr  Pass   Timeout
  1 language/async_star_test/02  RuntimeError   Timeout
  1 language/async_star_test/none  Pass   Timeout
  1 lib/async/run_zoned7_test  Pass   Timeout
  1 lib/async/stream_periodic2_test  Pass   Timeout
  1 lib/async/timer_cancel_test  Pass   Timeout
```

**Comment by alan-knight** [comment]
Many of these seem to have something to do with async callbacks, although not all of them. stream_periodic2_test seems the smallest. But I don't see anything obvious, and I can't get any of them to fail. Maybe stream_periodic2 ought to be returning a future from the test function, but if that's required then it's not clear why it wouldn't have been erratically timing out all along.

**Comment by whesse** [comment]
There is a change in tools/testing/dart/test_configurations.dart to reduce the number of browser processes to processors/2 in this case, but it doesn't seem to help.

**Comment by matanlurey** [comment]
This is a browser from years ago.
