### ISSUE TITLE
Runtime dynamic object/real proxy

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#23896]
It is very useful that we can override noSuchMethod and create effective proxies. It would be even more useful if it were possible to create proxies that implement every interface (actual dynamics) when it comes to type checks.

```
// Implements every interface in regard to type-checks
class Forwarder implements dynamic {
  final _delegate;

  Forwarder(this._delegate);

  noSuchMethod(invocation) => ...;
}
```

```
Forwarder forwarder = new Forwarder('hello');
String a = forwarder;
assert(a.runtimeType == Forwarder);
assert(a is String);
```

Forwarder is effectively dynamic. Currently, this only works for generic parameters in type checks.
(`print(new List<dynamic>() is List<String>); // prints true`).

An alternative would be to provide a way to mixin classes at runtime, but that would seem much more difficult to implement in the VM/dart2js.

Currently, one has to manually create proxies that implement the right interfaces to avoid runtime errors, which does not scale well for writing generic interceptors/loggers/etc.

**Comment by seaneagan** [comment]
Isn't that what [@proxy](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core#id_proxy) is for?

**Comment by BlackHC** [comment]
That does not work. Also even if it were to work as described in the comments, it would only silence static warnings. However, the issue here are runtime errors.

**Comment by a14n** [comment]
duplicate of #5641 ?
