### ISSUE TITLE
language/deferred_type_dependency_test fails analyzer

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23894]
The new multitest deferred_type_dependency_test fails the analyzer because of a circular dependency test file (imports) lib (imports) test file.  The original test file is changed because it is a multitest, but the import statement in the lib still imports the original test file.

I'm not sure this can be fixed while keeping it a multitest.
Suppressing it in language

The discussion below is not about the actual analysis failure.
Also, the /// none annotation cannot be used to do what is done here.  /// none, if it worked, would be just like any other key.  It doesn't work because of the implementation (though in this case it does - the failure mode if is a new annotation key appears after the first use of none).  I'll change this in the testing scripts, to catch this error.  It would work as an annotation:  /// none: runtimeFailure.  This is what you really want, rather than trying to patch up the none case to work.

Really, we shouldn't have a default none.  Adding a key /// none on an empty line, would enable a none case, if we didn't have it as a special case.

**Comment by askeksa-google** [comment]
Works in the analyzer now.
