### ISSUE TITLE
compiler crashed when compiling class declaration

### ISSUE THREAD

**Issue by kharland** [dart-lang/sdk#23893]
**OS**: ubuntu 14.04 'Trusty' (Linux Kernel: 3.13.0-55-generic)

**output of `dart --version`**: Dart VM version: 1.12.0-dev.3.1+google3-v1.12.0.dev.3.1 (google3) on "linux_x64"

**Error message**:
[Error from Dart2JS on experimental.users.kjharland.kjh_ang|web/main.dart]:
packages/experimental.users.kjharland.kjh_ang/components/search_component.dart:11:1:
The compiler crashed when compiling this element.
class SearchComponent {
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on experimental.users.kjharland.kjh_ang|web/main.dart threw error: Class 'ErrorNode' has no instance getter 'expression'.

NoSuchMethodError: method not found: 'expression'
Receiver: Instance of 'ErrorNode'
Arguments: []
dart:core                                                               Object.noSuchMethod
package:compiler/src/scanner/listener.dart 2572                         PartialMetadataAnnotation.parseNode
package:compiler/src/resolution/resolution_common.dart 923              ResolverTask.resolveMetadataAnnotation.<fn>.<fn>
package:compiler/src/compiler.dart 2200                                 CompilerTask.measure
package:compiler/src/resolution/resolution_common.dart 919              ResolverTask.resolveMetadataAnnotation.<fn>
package:compiler/src/compiler.dart 920                                  Compiler.withCurrentElement
package:compiler/src/resolution/resolution_common.dart 919              ResolverTask.resolveMetadataAnnotation
package:compiler/src/elements/modelx.dart 2829                          MetadataAnnotationX.ensureResolved
package:compiler/src/resolution/resolution_common.dart 541              ResolverTask._postProcessClassElement
package:compiler/src/resolution/resolution_common.dart 459              ResolverTask._resolveTypeDeclaration.<fn>.<fn>
package:compiler/src/compiler.dart 2200                                 CompilerTask.measure
package:compiler/src/resolution/resolution_common.dart 448              ResolverTask._resolveTypeDeclaration.<fn>
package:compiler/src/compiler.dart 920                                  Compiler.withCurrentElement
package:compiler/src/resolution/resolution_common.dart 447              ResolverTask._resolveTypeDeclaration
package:compiler/src/resolution/resolution_common.dart 484              ResolverTask.resolveClass
package:compiler/src/elements/modelx.dart 2349                          BaseClassElementX.ensureResolved
package:compiler/src/resolution/members.dart 1915                       ResolverVisitor.handleClassSend
package:compiler/src/resolution/members.dart 2429                       ResolverVisitor.handleResolvedSend
package:compiler/src/resolution/members.dart 2478                       ResolverVisitor.handleUnqualifiedSend
package:compiler/src/resolution/members.dart 2491                       ResolverVisitor.visitSend
package:compiler/src/tree/nodes.dart 381                                Send.accept
package:compiler/src/resolution/resolution_common.dart 982              CommonResolverVisitor.visit
package:compiler/src/resolution/members.dart 804                        ResolverVisitor.resolveArguments
package:compiler/src/resolution/members.dart 2021                       ResolverVisitor.handleDynamicAccessSemantics
package:compiler/src/resolution/members.dart 1514                       ResolverVisitor.handleThisPropertyAccess
package:compiler/src/resolution/members.dart 2471                       ResolverVisitor.handleUnqualifiedSend
package:compiler/src/resolution/members.dart 2491                       ResolverVisitor.visitSend
package:compiler/src/tree/nodes.dart 381                                Send.accept
package:compiler/src/resolution/resolution_common.dart 982              CommonResolverVisitor.visit
package:compiler/src/resolution/members.dart 488                        ResolverVisitor.visitExpressionStatement
package:compiler/src/tree/nodes.dart 1155                               ExpressionStatement.accept
package:compiler/src/resolution/resolution_common.dart 982              CommonResolverVisitor.visit
package:compiler/src/resolution/members.dart 2764                       ResolverVisitor.visitNodeList
package:compiler/src/tree/nodes.dart 565                                NodeList.accept
package:compiler/src/resolution/resolution_common.dart 982              CommonResolverVisitor.visit
package:compiler/src/resolution/members.dart 451                        ResolverVisitor.visitIn
package:compiler/src/resolution/members.dart 471                        ResolverVisitor.visitBlock
package:compiler/src/tree/nodes.dart 612                                Block.accept
package:compiler/src/resolution/resolution_common.dart 982              CommonResolverVisitor.visit
package:compiler/src/resolution/resolution_common.dart 176              ResolverTask.resolveMethodElementImplementation.<fn>
package:compiler/src/compiler.dart 920                                  Compiler.withCurrentElement
package:compiler/src/resolution/resolution_common.dart 137              ResolverTask.resolveMethodElementImplementation
package:compiler/src/resolution/resolution_common.dart 246              ResolverTask.resolveMethodElement.<fn>
package:compiler/src/compiler.dart 920                                  Compiler.withCurrentElement
package:compiler/src/resolution/resolution_common.dart 210              ResolverTask.resolveMethodElement
package:compiler/src/resolution/resolution_common.dart 36               ResolverTask.resolve.<fn>
package:compiler/src/compiler.dart 2200                                 CompilerTask.measure
package:compiler/src/resolution/resolution_common.dart 15               ResolverTask.resolve
package:compiler/src/compiler.dart 1805                                 Compiler.analyzeElement
package:compiler/src/compiler.dart 1831                                 Compiler.analyze
package:compiler/src/compiler.dart 45                                   ResolutionWorkItem.run
package:compiler/src/compiler.dart 1739                                 Compiler.processQueue.<fn>.<fn>
package:compiler/src/compiler.dart 920                                  Compiler.withCurrentElement
package:compiler/src/compiler.dart 1738                                 Compiler.processQueue.<fn>
package:compiler/src/enqueue.dart 953                                   QueueFilter.processWorkItem
package:compiler/src/enqueue.dart 639                                   Enqueuer.forEach
package:compiler/src/compiler.dart 1737                                 Compiler.processQueue
package:compiler/src/compiler.dart 1607                                 Compiler.compileLoadedLibraries
package:compiler/src/compiler.dart 1516                                 Compiler.runCompiler.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:compiler/src/compiler.dart 1515                                 Compiler.runCompiler
package:compiler/src/compiler.dart 1235                                 Compiler.run.<fn>
dart:async                                                              Future.Future.sync
package:compiler/src/compiler.dart 1235                                 Compiler.run
package:compiler/src/apiimpl.dart 403                                   Compiler.run.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:compiler/src/apiimpl.dart 400                                   Compiler.run
package:compiler/compiler_new.dart 176                                  compile
package:compiler/compiler.dart 133                                      compile
package:pub/src/dart.dart 108                                           compile.<async>
===== asynchronous gap ===========================
dart:async                                                              Future.Future.microtask
package:pub/src/dart.dart                                               compile
package:pub/src/barback/dart2js_transformer.dart 134                    Dart2JSTransformer._doCompilation
package:pub/src/barback/dart2js_transformer.dart 82                     Dart2JSTransformer.apply.<fn>.<fn>
dart:async                                                              Future.Future.sync
package:pool/pool.dart 91                                               Pool.withResource.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:pool/pool.dart 90                                               Pool.withResource
package:pub/src/barback/dart2js_transformer.dart 79                     Dart2JSTransformer.apply.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:pub/src/barback/dart2js_transformer.dart 75                     Dart2JSTransformer.apply
package:barback/src/transformer/wrapping_aggregate_transformer.dart 53  WrappingAggregateTransformer.apply.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:barback/src/transformer/wrapping_aggregate_transformer.dart 53  WrappingAggregateTransformer.apply
package:barback/src/graph/transform_node.dart 624                       TransformNode._runApply.<fn>
dart:async                                                              Future.Future.sync
package:barback/src/utils.dart 244                                      syncFuture
package:barback/src/graph/transform_node.dart 620                       TransformNode._runApply
package:barback/src/graph/transform_node.dart 517                       TransformNode._apply
package:barback/src/graph/transform_node.dart 277                       TransformNode.force
package:barback/src/graph/transformer_classifier.dart 142               TransformerClassifier.forceAllTransforms
package:barback/src/graph/phase.dart 287                                Phase.forceAllTransforms
package:barback/src/graph/asset_cascade.dart 209                        AssetCascade.forceAllTransforms
package:barback/src/graph/package_graph.dart 156                        PackageGraph.getAllAssets.<fn>
dart:async                                                              Future.Future.sync
package:barback/src/utils.dart 244                                      syncFuture
package:barback/src/graph/package_graph.dart 280                        PackageGraph._inErrorZone.<fn>
dart:async                                                              runZoned
package:barback/src/graph/package_graph.dart 279                        PackageGraph._inErrorZone
package:barback/src/graph/package_graph.dart 156                        PackageGraph.getAllAssets
package:barback/src/barback.dart 106                                    Barback.getAllAssets
package:pub/src/command/build.dart 97                                   BuildCommand.onRunTransformerCommand.<async>.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:pub/src/command/build.dart 95                                   BuildCommand.onRunTransformerCommand.<async>.<fn>.<fn>
package:pub/src/log.dart 378                                            progress
package:pub/src/command/build.dart 89                                   BuildCommand.onRunTransformerCommand.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                              _Future.then
package:pub/src/command/build.dart 67                                   BuildCommand.onRunTransformerCommand.<async>
===== asynchronous gap ===========================
dart:async                                                              Future.Future.microtask
package:pub/src/command/build.dart                                      BuildCommand.onRunTransformerCommand
package:pub/src/command/barback.dart 58                                 BarbackCommand.run
package:args/command_runner.dart 178                                    CommandRunner.runCommand.<fn>
dart:async                                                              Future.Future.sync
package:args/command_runner.dart 131                                    CommandRunner.runCommand
package:pub/src/command_runner.dart 126                                 PubCommandRunner.runCommand.<async>.<fn>
dart:async                                                              Future.Future.sync
package:pub/src/utils.dart 103                                          captureErrors.<fn>
package:stack_trace                                                     Chain.capture
package:pub/src/utils.dart 117                                          captureErrors
package:pub/src/command_runner.dart 126                                 PubCommandRunner.runCommand.<async>
Build failed.
ERROR: /google/src/cloud/kjharland/kjharland-gt/google3/experimental/users/kjharland/kjh_ang/BUILD:11:1: Executing pub build //experimental/users/kjharland/kjh_ang:kjh_ang failed (Exit 1) [forge_remote_host=iccmh6].
Target //experimental/users/kjharland/kjh_ang:kjh_ang failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.530s, Forge stats: 0/1 actions cached, 9.7s CPU used, 0.0s queue time, 0.0 MB ObjFS output, 0.0 MB local output, Critical Path: 12.85s, Forge (99.88% of the time): [queue: 0.15%, setup: 10.60%, process: 78.08%]
INFO: Build results are being uploaded in the background, and will eventually be available at http://sponge/9a9e84fb-6326-415b-be5a-feca3e3f225a

**Comment by sigmundch** [comment]
@kharland do you have available for us a snippet of code that produces the crash?

**Comment by sigmundch** [comment]
It looks like an issue with a malformed annotation. I was able to reproduce the failure with this simple example:
```dart
@Deprecated('a',)
class B {}
main() => new B();
```

which produces this error (I replaced the standard boilerplate with `...`):
```
foo.dart:1:17:
Error: Expected an expression, but got ')'.
@Deprecated('a',)
                ^
foo.dart:2:1:
Internal Error: The compiler crashed when compiling this element.
class B {}
^^^^^
The compiler is broken.

...
...

The compiler crashed: Class 'ErrorNode' has no instance getter 'expression'.

NoSuchMethodError: method not found: 'expression'
Receiver: Instance of 'ErrorNode'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      PartialMetadataAnnotation.parseNode (file:///mnt/data/b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/scanner/listener.dart:2572)
#3      ResolverTask.resolveMetadataAnnotation.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:923)

```

The good news is that we already report another error that helps people recover from the issue. The bad news is that we still crash.

**Comment by sigmundch** [comment]
fix out for review https://codereview.chromium.org/1257513002/

**Comment by kharland** [comment]
Apologies for the delay. Great work, thanks for handling this so quickly.
