### ISSUE TITLE
Code completion on inferred type with async is missing

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#23890]
From https://youtrack.jetbrains.com/issue/WEB-17108

    import 'package:gcloud/pubsub.dart' as ps;
    
    main() async {
      ps.Topic topic = await ps.pubsubService.createTopic("test");
    }

The explicit typing of topic is currently necessary to get completions, but it shouldn't be. The type of the createTopic method is explicit so type inferencing should support completions with the more Darty style of coding: 

    main() async {
      var topic = await ps.pubsubService.createTopic("test");
      topic.
    }

**Comment by alexander-doroshko** [comment]
@danrubel This issue is about WebStorm internal completion logic. When we switch to Analysis Server powered completion the issue will become obsolete. As far as I see Analysis Server already works fine with this case.

**Comment by alexander-doroshko** [comment]
Looks like the issue can be closed. As I can see Analysis Server already works well with this case.

**Comment by danrubel** [comment]
Thanks for the update. Closing.
