### ISSUE TITLE
Expose the Observatory debugger for external use

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23901]
Observatory's text-based debugger interface is pretty nice, and it would be especially nice if it were accessible by external clients. For example, the test runner might have a flag that opens the debugger right in the user's terminal so they don't have to open a web browser to do simple debugging. Of course this could be implemented manually, but that runs the risk of having odd differences with Observatory's own interface.

I could imagine two ways this might work. Either the VM service exposes some sort of `startDebugger`/`sendDebuggerLine`/debugger output event API, or an external package is created that uses the VM service and a pluggable input/output model, which is then used by Observatory. The latter is probably a little cleaner, although it would presumably require that all VM services used by the package be made stable, which might be too high a cost for now.

Note that for me personally, this is lower priority than #23900 or #23897.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by nex3** [comment]
@iposva-google Why did you remove the VM label? Observatory issues go under, `Area-VM`, correct?

/cc @kevmoo, the label tzar

**Comment by iposva-google** [comment]
I was not done cleaning up the labels.

**Comment by nex3** [comment]
I didn't realize there was an `Area-Observatory` label. I've moved all the existing `VM-Observatory` issues over to it, and deleted the `VM-Observatory` label to prevent further confusion.
