### ISSUE TITLE
Add a "pause on error" command to the VM service

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23900]
When debugging, it's very useful for a user to be able to pause the program when an error occurs. Of course there's already top-level error handling that can be done, but specifically being able to pause _at the site where the error is thrown_ is most useful for inspecting local state and setting relevant breakpoints for a future run.

This is supported via Observatory, so I assume it's available privately in the VM service. Making it public would be great, and would help improve the debugging UI for the test runner.

**Comment by sethladd** [comment]
This would be great for Sky development, too.

**Comment by turnidge** [comment]
We have implemented the ability to break when any exception is thrown.  This is currently implemented in the hidden method _setExceptionPauseInfo.

I agree that this service method should be made public.
