### ISSUE TITLE
Context manager bypasses resourceProvider when using package roots.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#23909]
The code in ContextManagerImpl._computePackageUriResolver which handles package roots uses the JavaFile class to read the contents of the package root, rather than the resourceProvider.  Since the resourceProvider is used during unit tests to replace the true filesystem with a mock filesystem, this means that the normal code for handling package roots is not exercised by unit tests, and a separate bogus code path (which otherwise is dead code) is used instead.

I will shortly be submitting a CL which disables the tests and eliminates the bogus code path so that I don't have to maintain it while I'm refactoring the ContextManager.  But the proper solution is to add the necessary functionality to ResourceProvider so that this code path doesn't have to use JavaFile, and then re-enable the tests.

**Comment by stereotype441** [comment]
Minor correction: the codepath isn't entirely bogus--it could also trigger in the event of a race condition where the package root existed at the time it was specified, but then disappeared before the contents of the folder could be read.

**Comment by stereotype441** [comment]
This bug was accidentally auto-closed because the commit message for cdfa46faa594c1d382675419716fb3fdbffa3f63 says it "partially fixes" the bug.  Re-opening since the bug is not yet completely fixed.

**Comment by johnmccutchan** [comment]
Related: https://codereview.chromium.org/1295463003/

**Comment by srawlins** [comment]
I no longer see any references to packageUri in this file, nor JavaFIle. I'm assuming this was fixed long ago. Please re-open if it is still an issue.
