### ISSUE TITLE
Irrelevant retaining paths can obscure the real reason ports aren't closed

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23902]
The port inspection feature of Observatory is often very useful for tracking down why an application hasn't yet closed, but under certain (relatively common) circumstances it can surface misleading and unhelpful information. In general, I've found that the best way for figuring out why a port is still live is to look at its retaining path. However, sometimes this retaining path includes code that used the port at one point but later stopped, as opposed to code that is currently causing it to stay alive.

For example, see the following code:

```dart
import 'dart:async';

void shortTimer() {
  Timer.run(() => print("short timer fired"));
}

void longTimer() {
  new Timer(new Duration(hours: 1), () => print("long timer fired"));
}

void main() {
  shortTimer();
  longTimer();
}
```

If I run this with `--enable-vm-service` and look at the ports in Observatory, I see a single port labeled `_Timer._handleMessage._handleMessage`. When I select this port and look at its retaining path, I see a long list containing references to `shortTimer` but no references to `longTimer`. This is clearly incorrect; `shortTimer` has already fired, so only `longTimer` should be keeping the port alive.

It's worth noting that if I reverse the order in which `shortTimer()` and `longTimer()` are called, `longTimer` shows up in the retaining path instead.

**Comment by rmacnak-google** [comment]
A few issues here:

A port is not open because its Dart proxy is reachable. A port's Dart proxy can be garbage collected without the port being closed.

Retaining paths are based only on the connectivity of the object graph, and the one you get is arbitrary. A programmer can guide a backwards search with domain knowledge using the 'inbound references' tool to get more meaningful reasons an object is reachable.

That said, an object can never be alive only because of call site caches so I have excluded them during the search for a retaining path.

**Comment by nex3** [comment]
> A few issues here:
>
> A port is not open because its Dart proxy is reachable. A port's Dart proxy can be garbage collected without the port being closed.
> 
> Retaining paths are based only on the connectivity of the object graph, and the one you get is arbitrary. A programmer can guide a backwards search with domain knowledge using the 'inbound references' tool to get more meaningful reasons an object is reachable.

In that case, can it display *all* the retaining paths? Also, where's the inbound references tool?

> That said, an object can never be alive only because of call site caches so I have excluded them during the search for a retaining path.

What's the CL that does this?

**Comment by bkonyi** [comment]
Just to update the current state of open port debugging, it's now possible to determine where ports were allocated and the core libraries provide debugging labels. This information is currently only surfaced in the VM Tools -> Isolates pane in DevTools, visible with "VM Developer Mode" enabled.

![image](https://user-images.githubusercontent.com/24210656/107296092-94571000-6a25-11eb-99e3-ef14991bf077.png)
