### ISSUE TITLE
Error reporting in missing switch case is excessive

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#23904]
This switch is missing a case.

This much error highlighting makes the code difficulty to read. Consider reporting it on the 'switch (..)' text only.

![image](https://cloud.githubusercontent.com/assets/2978182/8844207/3b7f0974-310a-11e5-8693-c802bde5f58c.png)

IntelliJ IDEA (Minerva) IU-142.3050.1
Build #IU-142.3050, built on July 7, 2015
JRE: 1.8.0_40-internal-b82 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1252123004/
