### ISSUE TITLE
 VM reports native extension is missing regardless of reason why dlopen fails

### ISSUE THREAD

**Issue by hcstern** [dart-lang/sdk#23908]
In runtime/bin/extensions.cc, the function LoadExtension calls LoadExtensionLibrary. On Linux, LoadExtensionLibrary in runtime/bin/extensions_linux.cc just returns the result of the dlopen call. If the dlopen call fails (and returns NULL) or if dlerror doesn't return NULL (for a reason that may not be it not being found) we still get an ApiError message that just says "cannot find extension library".

It would be nice if on Linux the LoadExtensionLibrary function added the output of dlerror() to the ApiError message.

**Comment by a-siva** [comment]
https://chromiumcodereview.appspot.com/1403683007/ fixes this.

**Comment by boustrophedon** [comment]
:)
