### ISSUE TITLE
How to manage multi-thread in native extension

### ISSUE THREAD

**Issue by Kleak** [dart-lang/sdk#23913]
Hello every body,
I try to create a native extension that allow me to create VFS (Virtual File System) and i have some problem.
Actually i use dokan because I have a windows.
When dokan call his dokan operations I don't know on which thread i am and the vm was not happy.
But I have found Dart_EnterIsolate(your_isolate) but now I have an other error which is : 
vm\dart_api_impl.cc:1382: error: Multiple mutators within one isolate is not supported 

If you can take a look at my extension and give me some tips on how to do this kind of things.
The code is here : https://github.com/Rollercops/Dart-Dokany

Thanks a lot

**Comment by matanlurey** [comment]
I think its fair to say this won't be addressed. Sorry about that.
