### ISSUE TITLE
Dartium path shown on "brew upgrade dart" is incorrect

### ISSUE THREAD

**Issue by sanfordredlich** [dart-lang/sdk#23918]
Hi, it shows: "/usr/local/opt/dart/Chromium.app" when it should be "/usr/local/opt/dartium" because that's how the symlinks are actually set up. See output below:

| ~ @ Sanfords-MBP (sanford) 
| => brew upgrade dart
==> Upgrading 1 outdated package, with result:
dart-lang/dart/dart 1.11.1
==> Upgrading dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.1/sdk/dartsdk-macos-x64-release.zip
######################################################################## 100.0%
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app
==> Summary
🍺  /usr/local/Cellar/dart/1.11.1: 224 files, 31M, built in 2.4 minutes

------------------------------

| /usr/local/opt/dart @ Sanfords-MBP (sanford) 
| => cd ..
total 44
lrwxr-xr-x  1 sanford  admin    23B Nov  8  2014 autoconf -> ../Cellar/autoconf/2.69
lrwxr-xr-x  1 sanford  admin    21B Jul 29 08:48 dart -> ../Cellar/dart/1.11.1
lrwxr-xr-x  1 sanford  admin    24B Jun  4 08:50 dartium -> ../Cellar/dartium/1.10.1
lrwxr-xr-x  1 sanford  admin    24B Jan 15  2015 exercism -> ../Cellar/exercism/1.9.0
lrwxr-xr-x  1 sanford  admin    19B May 30 07:10 hub -> ../Cellar/hub/2.2.1
lrwxr-xr-x  1 sanford  admin    22B Nov  4  2014 mysql -> ../Cellar/mysql/5.6.21
lrwxr-xr-x  1 sanford  admin    24B Nov  4  2014 openssl -> ../Cellar/openssl/1.0.1j
lrwxr-xr-x  1 sanford  admin    25B Nov  8  2014 pkg-config -> ../Cellar/pkg-config/0.28
lrwxr-xr-x  1 sanford  admin    21B Nov  8  2014 rbenv -> ../Cellar/rbenv/0.4.0
lrwxr-xr-x  1 sanford  admin    29B Nov  8  2014 ruby-build -> ../Cellar/ruby-build/20141028
lrwxr-xr-x  1 sanford  admin    19B Nov  7  2014 wget -> ../Cellar/wget/1.16
________________________________________________________________________________
| /usr/local/opt @ Sanfords-MBP (sanford) 
| => pwd
/usr/local/opt

**Comment by sethladd** [comment]
This issue was moved to dart-lang/www.dartlang.org#1421

**Comment by sethladd** [comment]
This issue was moved to dart-lang/homebrew-dart#35
