### ISSUE TITLE
Bus error: 10 - no explanation

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23914]
1. git clone https://github.com/kevmoo/vote.dart
1. cd vote.dart/
1. git checkout repo_bug_fun
1. pub install
1. dart test/vote/irv_test.dart

Fails with `Bus error: 10` in latest dev build and latest bleeding edge.

**Comment by sgmitrovic** [comment]
thread #2: tid = 0x13096, 0x00044e07 dart`dart::AtomicOperations::CompareAndSwapWord(ptr=0x0108c308, old_value=4063746, new_value=4129282) + 39 at atomic_macos.h:28, stop reason = EXC_BAD_ACCESS (code=2, address=0x108c308)
    frame #0: 0x00044e07 dart`dart::AtomicOperations::CompareAndSwapWord(ptr=0x0108c308, old_value=4063746, new_value=4129282) + 39 at atomic_macos.h:28
   25  	inline uword AtomicOperations::CompareAndSwapWord(uword* ptr,
   26  	                                                  uword old_value,
   27  	                                                  uword new_value) {
-> 28  	  return __sync_val_compare_and_swap(ptr, old_value, new_value);
   29  	}
   30  	#endif  // !defined(USING_SIMULATOR)
   31  	

* thread #2: tid = 0x13096, 0x00044e07 dart`dart::AtomicOperations::CompareAndSwapWord(ptr=0x0108c308, old_value=4063746, new_value=4129282) + 39 at atomic_macos.h:28, stop reason = EXC_BAD_ACCESS (code=2, address=0x108c308)
  * frame #0: 0x00044e07 dart`dart::AtomicOperations::CompareAndSwapWord(ptr=0x0108c308, old_value=4063746, new_value=4129282) + 39 at atomic_macos.h:28
    frame #1: 0x00522a91 dart`dart::Object::CompareAndSwapTags(this=0xb0101a9c, old_tags=4063746, new_tags=4129282) const + 65 at object.h:249
    frame #2: 0x003d886a dart`dart::Array::MakeImmutable(this=0xb0101a9c) const + 106 at object.cc:19743
    frame #3: 0x000c0697 dart`dart::DN_HelperInternal_makeFixedListUnmodifiable(isolate=0x0189c400, thread=0x01400000, zone=0xb0101680, arguments=0xb0101cc4) + 231 at growable_array.cc:101
    frame #4: 0x000c0477 dart`dart::BootstrapNatives::DN_Internal_makeFixedListUnmodifiable(args=0xb0101cc4) + 743 at growable_array.cc:99
    frame #5: 0x01200360
    frame #6: 0x075ad3ac

**Comment by kevmoo** [comment]
Confirmed in 3ba3667926fe2c3590e0c8da2ccb066191530648 Thanks!
