### ISSUE TITLE
location offsets are incorrect for some returned references

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23919]
The analysis server seems to return incorrect column offsets for some location. When I issue a find references call for `DivElement`, I get ~17 results, including many in dart:html. Most of these references highlight correctly in the code. A few don't (and they both are references in dartdoc).

<img width="281" alt="screen shot 2015-07-29 at 10 38 28 pm" src="https://cloud.githubusercontent.com/assets/1269969/8976548/6898b6c4-3643-11e5-8142-2c533bc87d89.png">

<img width="300" alt="screen shot 2015-07-29 at 10 38 47 pm" src="https://cloud.githubusercontent.com/assets/1269969/8976549/6898f62a-3643-11e5-80f9-0f45f3797fcc.png">

The returned info from the call is:

```
{"file":"/Users/devoncarew/homebrew/opt/dart/libexec/lib/html/dartium/html_dartium.dart","offset":298153,"length":10,"startLine":8465,"startColumn":10}
```

The offset and lines are correct. The column is off-by one.

We are seeing more serious problems with the offsets for errors and warnings being incorrect. Not sure if that is related to this problem.

**Comment by sethladd** [comment]
FWIW this happens a lot, enough for us to notice repeatedly. Thanks for taking a look!

**Comment by bwilkerson** [comment]
I added a test, and we appear to have the right offsets in the normal case. I'm guessing that this is an issue with incremental resolution, possibly forgetting to update the offsets to references within comments.

**Comment by scheglov** [comment]
The problem is not in navigation, but in search.
And actually it is most probably in the scanner, because we use LineInfo to convert offsets into line/column. I can reproduce it.

Will fix.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1271553002

**Comment by scheglov** [comment]
Fixed.

https://github.com/dart-lang/sdk/commit/8eb0de07f30bf7596521606856f8b3aabc8555cc

**Comment by devoncarew** [comment]
Awesome! I'll test to see if this also solves the larger offset issue (https://github.com/dart-atom/dartlang/issues/116).

**Comment by sethladd** [comment]
Yay! Thanks @scheglov !
