### ISSUE TITLE
VM: Snaphot created on ia32 does not work on x64

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#23910]
Repro using the Richards benchmark:

$ out/DebugX64/dart --version
Dart VM version: 1.12.0-edge.a27ce8c7cf6f33e991f3fc3993211fa0da379e42 (Fri Jul 24 14:11:30 2015) on "linux_x64"

$ out/ReleaseIA32/dart --snapshot=snap.out ~/s/b/Richards/dart/Richards.dart 
$ out/ReleaseIA32/dart snap.out
Richards(RunTime): 877.0745287154756 us.
$ out/ReleaseX64/dart snap.out
Segmentation fault (core dumped)
$ out/DebugX64/dart snap.out
runtime/vm/snapshot.cc:469: error: expected: index == backward_references_->length()
Aborted (core dumped)

**Comment by fsc8000** [comment]
Ping. Could you reproduce this?

It seems still an issue at Dart VM version: 1.12.0-edge.470111791c1a0c792e54e33f461d0a2ed19ffa6c (Tue Jul 28 10:28:46 2015) on "linux_x64"

**Comment by iposva-google** [comment]
Still reproduces. Siva is looking at this...

**Comment by a-siva** [comment]
https://codereview.chromium.org/1264683002/ should fix this.
