### ISSUE TITLE
Could we show a hint when a function that returns nothing is used where we expect a function to return something?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23912]
Consider this case:

```
typedef String Foo();

wantsAFoo(Foo foo) {
  var result = foo();
  print('Result is $result');
}

main() {
  var thing = () { /* noop */ }; // expect a hint or warning here, it doesn't return anything
  wantsAFoo(thing);
}
```

It would be really nice to show the user at least a hint because `thing`'s function doesn't return anything, but we're passing thing to `wantsAFoo`, which takes a `Foo`, and `Foo` returns a String.

**Comment by bwilkerson** [comment]
I understand the desire, but just to play devils advocate...

The closure, because it doesn't have a return statement, returns `null`, which is a valid value for a String.

**Comment by sethladd** [comment]
> The closure, because it doesn't have a return statement, returns null, which is a valid value for a String.

That's true, which is why I'd want a hint and not a warning. The developer probably didn't mean to implicitly return null here. Omitting a return for a function that's been marked to return something is probably programmer error.

**Comment by kasperpeulen** [comment]
I would really like this as well.

I think the hint should be similar as with this code:

```dart
String helloWorld() {
  String result = 'hello world!!!!';
  result.replaceAll('!','');
}
```

see: https://dartpad.dartlang.org/949b7d9b85b18509dd21
-- 
Kasper

**Comment by Mixolyde** [comment]
Does the analyzer already give a hint or warning if you expect a return from a function with the void return type? For example:

    void voidFoo() { /* does nothing */ }

    wantsAVoidFoo() {
      var result = voidFoo();
      print('Result is $result');
    }

**Comment by zoechi** [comment]
I guess this would mostly be solved by NN/NNBD

**Comment by srawlins** [comment]
We have solutions now in null safe code, for functions which return non-nullable types and nullable types.
