### ISSUE TITLE
Include the Dart VM version in Dartium's version string

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23926]
Right now, it's very hard for a user to tell what version of Dart their Dartium version runs. Several times when reproducing bugs, I've asked users for this and they just supply the Chrome version, because that's what `--version` prints. We should add the Dart VM version string to Dartium's `--version` output.

The sooner we do this, the faster it will be before most versions of Dartium in the wild support it, so it would be nice to prioritize it highly.

/cc @sethladd

**Comment by sethladd** [comment]
Surprised this isn't in the User Agent now, or in some sort of 

Perhaps @terrylucas or @alan-knight have an idea of where to put this info, or if it's available.

@nex3 sounds like you're asking for this info to be somehow discoverable by the developer (even if it's a manual process?)... that is, did you need this info from JavaScript?

**Comment by nex3** [comment]
I'm mostly concerned with users being able to accurately report the Dart version their Dartium is running. I haven't checked whether it's in the user agent, although if it's not, it seems like it should be.

**Comment by ricowind** [comment]
Note that the dart version is available from chrome://version

**Comment by alan-knight** [comment]
It's not even in chrome://version any more

**Comment by alan-knight** [comment]
From #24622 it should also include the date, not just the hash

**Comment by terrylucas** [comment]
[CL](https://codereview.chromium.org/1904503002/) will display Dart version in chrome://version and in if the switch --version is specified.

**Comment by terrylucas** [comment]
committed c2d1ddba7a86ce11a8dcb77a4ac101872d6110bd (Chromium) and DEPS change commit b500f3c0089e133aae45857cbc08a65aeedd40f3 (Dart)
