### ISSUE TITLE
Quick Fix: organize imports and add show

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23921]
I'd love to be able to right-click and issue a Quick Fix (or whatever we want to call it :) to "organize imports and add all the show's"

Clean code is best code.

Thanks!

**Comment by sethladd** [comment]
cc @jmesserly

**Comment by scheglov** [comment]
These features are already available as two separate features.

1. Sort unit/class members.
![image](https://cloud.githubusercontent.com/assets/384794/8988726/c67e1c08-369c-11e5-8a3e-9b471106dd4d.png)

2. Add explicit 'show' combinator.
![image](https://cloud.githubusercontent.com/assets/384794/8988742/dc6757b4-369c-11e5-810c-7a1c29d34c9e.png)
  I'm in the faction that believes that "show" combinators should be added only as needed.
  So, I'm not sure that we want to convert all imports to use "show".

**Comment by alexander-doroshko** [comment]
How about organizing imports with dart_style tool? After dart_style I want my code to look perfect. It means no unused imports and imports/exports ordered according to style guide. In IntelliJ world 'Reformat Code' by default includes 'Optimize imports' in Java and in other supported languages, and optimizing imports include removing unused and sorting remaining.

**Comment by alexander-doroshko** [comment]
Though probably it's be better to provide a separate service at Analysis Server side for organizing imports/exports. IDEs will be able to decide themselves when to run both reformat and optimize imports and when only one of these actions.

**Comment by bwilkerson** [comment]
I agree, separate services seems better to me too. A conscious choice was made for dart_style (dartformat) to not make any changes to the user's code other than white-space changes, and I still think it was a good choice.

**Comment by scheglov** [comment]
Well, we already have edit.sortMembers, which will sort:
1. Unit directives - imports and exports.
2. Unit declarations - classes, variables, etc.
3. Class members - fields, constructors, members, etc.

The only problem is that it does all these together.
I.e. you cannot do only one, like sort imports, or even just sort directives.
It's all of nothing.

Is it important to have a separate feature for sorting imports/exports?
Will it align better with IDEA if we ran it right after edit.format and apply only the final result?

**Comment by alexander-doroshko** [comment]
Does edit.sortMembers remove unused imports?
Anyway I think Optimize Imports should be a separate action as well, not only as a part of sortMembers. IDE may decide to combine it with dart_style, just run both on one keystroke.
In Java I optimize imports (as a part of code reformat action) hundreds time a day, but I never use sortMembers (called Rearrange Code in IntelliJ). I'd like to have similar experience with Dart.
We may think about adding a check box at IDE side whether to optimize imports together with dart_style or not, but that's a separate topic.

**Comment by scheglov** [comment]
No, edit.sortMembers does not remove imports or anything else.
It just sorts them.

So, yes, it seems that it would be nice to have a separate edit.organizeImports request.
This feature would be somewhat more expensive than edit.sortMembers, because to know whether some imports are unused, we need to fully resolve and compute errors for the unit/library.

**Comment by jmesserly** [comment]
Dumb question:
> Sort unit/class members.
> Add explicit 'show' combinator.

In IntelliJ, do these show up as https://www.jetbrains.com/idea/help/intention-actions.html? I could've sworn I got one of them (maybe "organize imports") to pop up at some point ... but now I can't get them to trigger in 11 EAP w/ analysis_server integration.

**Comment by scheglov** [comment]
I'm pretty sure that IDEA does not get these actions from Analysis Server yet.
So, maybe it was Dart Editor?

**Comment by jmesserly** [comment]
ah, I was thinking of the "add import" quick fix, which does work.

**Comment by sethladd** [comment]
@devoncarew this would be nice for Atom :)

@scheglov does the 'add show combinator' work for all imports, or just the import that you've selected?

**Comment by scheglov** [comment]
@sethladd Just for one import under selection.

**Comment by scheglov** [comment]
"Optimize Imports" action for Dart in IDEA is on the way.
https://github.com/JetBrains/intellij-plugins/pull/236

**Comment by scheglov** [comment]
Landed.

**Comment by jmesserly** [comment]
\o/ Awesome!

**Comment by sethladd** [comment]
+1 !

**Comment by kasperpeulen** [comment]
yeah :D

![](http://i.imgur.com/FrIrSX8.gif)
![](http://i.imgur.com/QBOkwzw.gif)
