### ISSUE TITLE
Consider renaming server options file.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#23927]
ATM server options live in a file called `.dart_analysis_server.yaml` in your homedir but this is tentative.  @sethladd and @johnmccutchan I think were proposing a unification on `.analysis_options.yaml`.  If we do that we'll want to put this in a `.dart`-y sub directory since otherwise it won't be obvious that it's dart-related.

**Comment by johnmccutchan** [comment]
The per-context options file name is '.analysis_options'. I suggest the global one use the same name.

**Comment by pq** [comment]
> The per-context options file name is '.analysis_options'. I suggest the global one use the same name.
:+1: 

In that case maybe we can scope it in a sub-dir.  How about something as simple as:

    .dart/.analysis_options

?

**Comment by johnmccutchan** [comment]
sgtm

**Comment by bwilkerson** [comment]
How much overlap do we expect them to have in terms of the sets of options that can be specified? Unless the options are close to the same I think it would be confusing to use the same name. But if they're almost completely the same (modulo a few that can only appear in the global file) then it makes sense to use the same name.

Are we thinking of the "global" one as being a place for personal preferences (as opposed to global options that don't apply to individual contexts)?

If the same option is specified in both, which wins?

**Comment by bwilkerson** [comment]
I believe that this has been resolved.
