### ISSUE TITLE
Analysis Server: implement support for .packages

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23925]
Tracking bug. Parent/meta issue is https://github.com/dart-lang/sdk/issues/23372

**Comment by pq** [comment]
As of https://github.com/dart-lang/sdk/commit/818229cbae1004f560428f843f7ebe531cf10558 support can be enabled via an option specified in a `.dart_analysis_server.yaml` file in your homedir. Specifically:

    ContextManagerImpl.ENABLE_PACKAGESPEC_SUPPORT: true

**Comment by sethladd** [comment]
@stereotype441 what do you think, can we close this? How do you feel about this support?

**Comment by stereotype441** [comment]
We are as complete as we're going to get for 1.12.  All the major use cases we're aware of are addressed.

Some rewrite for 1.13 is planned that should tighten up the feature even more, and reduce our risk of unknown bugs, but I don't see any reason to hold up 1.12 waiting for that.

**Comment by sethladd** [comment]
Thanks for the update!
