### ISSUE TITLE
Poor documentation for native extensions

### ISSUE THREAD

**Issue by austincummings** [dart-lang/sdk#23922]
The [documentation page for native extensions](https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/) is severely lacking in detail. 

There is no mention of why library handler error's happen. There is also no mention of how to tie a C++ object to a Dart object. The example code is out of date with what's in the repo. There is basically no self troubleshooting when it comes to native extensions. 

These are extremely important if you want people to develop for the language. Right now Dart is lacking in database libraries and those are only possible with native extensions.

**Comment by kevmoo** [comment]
We might want to transfer this to the dartlang.org repo issue tracker...

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/www.dartlang.org#1423
