### ISSUE TITLE
Provide a way to get an Isolate's ID in user code

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23924]
When writing code that's debugging isolates it has access to—as is common, for example, in the test runner—it's currently very hard to associate an `Isolate` object with the ID necessary to refer to it using the VM service. Just providing a string ID property would make this way easier, although having something like `isolateId(Isolate isolate)` in `dart:developer` would work as well.

**Comment by kevmoo** [comment]
@a-siva @johnmccutchan We think this would save a LOT of time implementing the debugging story in pkg/test – and also make it more reliable.

Possible to look into for this milestone?

**Comment by lrhn** [comment]
In general, isolates are identified by their control ports and there isn't necessarily a numeric ID.
If the ID asked for here is for the VM service, it shouldn't be in the `dart:isolate` library, but I think it would fit in the `dart:developer` library.

**Comment by nex3** [comment]
It could still be useful to have a cross-platform way of identifying an isolate that's not intimately tied to instance equality, but that's not too important to me. `dart:developer` would be fine.

**Comment by kevmoo** [comment]
CL in process - https://codereview.chromium.org/2542003002/

**Comment by nex3** [comment]
Thanks! :tada:
