### ISSUE TITLE
Incorrect code completion results from text `super`

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23929]
Consider this similar case:

```
class Thing {
  String get superDuper;
}
```

Create an instance of thing, and type `thing.super` and then try to code complete.

Expected: see the `superDuper` option.

Actual: nothing.

See screenshots:

![screen shot 2015-07-30 at 7 51 14 pm](https://cloud.githubusercontent.com/assets/5479/8999839/8a1de736-36f4-11e5-8618-c70d29b23e92.png)

![screen shot 2015-07-30 at 7 51 09 pm](https://cloud.githubusercontent.com/assets/5479/8999841/8e38c96c-36f4-11e5-8bee-d37cbcbd47fc.png)

Hope that helps!

**Comment by sethladd** [comment]
cc @devoncarew but I suspect this is an AS issue, but maybe an Atom issue.

**Comment by devoncarew** [comment]
If you turn the logging up to `finer`, you can see the data that the AS sends atom. Fair warning, it can be pretty verbose.

**Comment by sethladd** [comment]
cc @lukechurch do you see this in WebStorm?

**Comment by danrubel** [comment]
Duplicate of #23882
