### ISSUE TITLE
Make it easier to detect memory leaks

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#23933]
I know there is observatory and I played with it for quite a while and it shows a lot of cool informations but I am not sure if I have memory leaks or not????

E.G. allocation profile - old generation, new generation??? If an object disappears from new generation but accumulates in old generation after GC is this a memory leak or not? 
Say I have 15 XY-objects in old generation how can I find out who references them?

It would also be cool to have a manual how to avoid! memory leaks. 
Say an object A has a periodic timer X this timer is started in As CTOR. When A is dereferenced what's with the timer X. 
Or another example - what happens with all the registered event listeners? Do I have to cancel these event listeners / streams or does Dart this job for me?

**Comment by sethladd** [comment]
Thanks for the feedback, @MikeMitterer !

fyi to @Sfshaza on a potential topic to document

**Comment by turnidge** [comment]
@johnmccutchan or @rmacnak-google do you want to comment on this?

**Comment by johnmccutchan** [comment]
> Say I have 15 XY-objects in old generation how can I find out who references them?

Yes, you can navigate to an instance of XY, and look at the retaining path.

**Comment by rmacnak-google** [comment]
Observatory offers many ways to explore the object graph, including following incoming reference, finding retaining paths ("pointer chasing"), dominator tree analysis, ownership group analysis, and finding live instances of any class.
