### ISSUE TITLE
need to update the observatory bug report link

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23936]
The 'file a bug report' link in the observatory points to an old url: `https://code.google.com/p/dart/issues/entry?template=Observatory`.

<img width="113" alt="screen shot 2015-07-31 at 11 38 27 am" src="https://cloud.githubusercontent.com/assets/1269969/9014681/c7c77e4c-3778-11e5-897e-091b423392cc.png">

**Comment by sethladd** [comment]
Also, good catch :)

**Comment by johnmccutchan** [comment]
@sethladd Do we have a new template or link to use?

**Comment by sethladd** [comment]
Doesn't look like it.

I did find a way to set the title or body. e.g.:

`https://github.com/dart-lang/sdk/issues/new?title=Observatory:&body=Observatory%20Feedback`

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1254413011/

**Comment by sethladd** [comment]
Thanks!
