### ISSUE TITLE
Observatory debugger can render offscreen

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23934]
![screen shot 2015-07-31 at 10 03 49 am](https://cloud.githubusercontent.com/assets/5479/9012658/8440f110-376b-11e5-83a4-9134f25b9c8b.png)

Working on a laptop.

Thanks for taking a look!

**Comment by turnidge** [comment]
I've got a fix which clips this at the edge.  The browser is fighting my attempts to show a scroll bar.

![screen shot 2015-08-24 at 2 09 44 pm](https://cloud.githubusercontent.com/assets/4804200/9452572/dc29e8b2-4a69-11e5-8e90-e822e1485359.png)

**Comment by turnidge** [comment]
Two fixes:

d6060d2dddcea1d28fd6bde67afc25b089e352f0
1587f88c2da2fc722ddc36f77830f6d360410108

These fix the rendering and also makes the variables consume much less horizontal space.
