### ISSUE TITLE
A way to keep Observatory's object inspect in view as I 'n' through a function?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23938]
![dart_vm_observatory](https://cloud.githubusercontent.com/assets/5479/9016307/efe7c704-3784-11e5-8250-21d1c8fb2647.png)

The function that I'm debugging is 25 lines long. As I type 'n' to move through the function, the object inspector on the right scrolls out of view.

It would be nice to keep the object inspector in view as I debug.

Thanks!

**Comment by turnidge** [comment]
Fixed in commit 3bf009d8d351c07853e606bde775875aa692ca01.
