### ISSUE TITLE
Sort Analyzer autocomplete suggestions by applicable types

### ISSUE THREAD

**Issue by alechenninger** [dart-lang/sdk#23937]
The first results should be types which are most relevant to the current assignment.

For example, if I'm passing an argument which annotated with type `Foo` to a function, and I type `new ` and ask for suggestions from the analyzer, I should first see suggestions for constructors of types which will implement `Foo`.

Originally filed as https://github.com/dart-atom/dartlang/issues/143

**Comment by jwren** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/26254 which is now fixed.
