### ISSUE TITLE
Switch statement execute failure

### ISSUE THREAD

**Issue by taozuhong** [dart-lang/sdk#23943]
EVN: dart web app execute in Dartium(39.0.2171.0 )
Dart: 1.11
OS: Windows 8.1 (64bit)

the first window.alert statement can execute and alert message: EventAction.Insert, the others can't be executed(haven't alert message)

``` dart
void SaveDialogData() {
  TimeEvent event = null;
  window.alert(gEventAction.toString());
  switch (gEventAction)
  {
    case EventAction.Insert:
      event = new TimeEvent();
      event.priority  = 3;
      event.status = 0;
      gEventArray.add(event);
      break;

    case EventAction.Update:
      event = gEventArray[gEventIndex];
      break;

    default:
      event = null;
      break;
  }

  window.alert();
  window.alert((null != event).toString());
  if (null != event) {
    event.subject = querySelector("#eventSubject").text;
    event.content = querySelector("#eventContent").text;
    event.stakeHolder = querySelector("#eventHolders").text;
    event.timing = DateTime.parse(querySelector("#eventSubject").text);

    window.alert(event.toJson());
  }
}
```

the complete sample as follow:LightWebApp.7z.Png ,just rename and upzip it
![lightwebapp 7z](https://cloud.githubusercontent.com/assets/13451009/9152830/78b42220-3e6b-11e5-826d-62fcecc2b114.Png)

**Comment by kasperl** [comment]
Hi @taozuhong! Have you tried setting a break point at the alert that seems to work for you and single step forward from there? Do you hit the EventAction.Insert case?

**Comment by alan-knight** [comment]
Do you have a complete example. This depends a lot on exactly what e.g. EventAction.Insert is, and it's not in the code.

**Comment by taozuhong** [comment]
I have upload the complete sample. in the sample, EventAction.Insert is not hit in execute flow.
