### ISSUE TITLE
analyser doesn't infer type in await for

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23945]
I would expect that the analyser could infer the type here:

![image](https://cloud.githubusercontent.com/assets/1035299/9028857/efa7e5d6-3986-11e5-9c75-0608a21da386.png)

**Comment by kasperpeulen** [comment]
checking some other examples, but it seems true generally, I don't get any completions here for example:
![image](https://cloud.githubusercontent.com/assets/1035299/9029170/b0987650-398e-11e5-8636-adc19f788563.png)

**Comment by sethladd** [comment]
cc @danrubel who is working on completion.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1268733004/
