### ISSUE TITLE
Observatory's debugger can't scroll source code if wider than 80 characters

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23959]
If source code is greater than 80 characters wide, I'm unable to scroll to see the remaining characters.

![screen shot 2015-08-03 at 10 22 15 pm](https://cloud.githubusercontent.com/assets/5479/9053748/39069e5a-3a2e-11e5-966b-687507b16697.png)

**Comment by sethladd** [comment]
cc @turnidge

**Comment by turnidge** [comment]
Well, I reopened this because my scroll bar disappeared.  But it turns out that this is because I had attached a bluetooth trackpad to my mac and OSX disguises scrollbars when there is a track pad.
