### ISSUE TITLE
When code completing a type annotation, can we order types to the top?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23954]
Consider this case:

![screen shot 2015-08-03 at 12 29 49 pm](https://cloud.githubusercontent.com/assets/5479/9045855/7bdc5592-39db-11e5-81d4-fc617b1eaf6b.png)

Expected: a list of options that are types, with `ArgParser` as the top option (because I'm instantiating an ArgParser right there)

Actual: a list containing, in order, `args, arguments, ArgParser, ArgResults, ...`

**Comment by sethladd** [comment]
cc @danrubel let me know if I can provide a repro case. Thanks!

**Comment by srawlins** [comment]
I think this is complete. Playing around in this position, I only get type suggsetions.
