### ISSUE TITLE
Crash in vm/cc/ManyTasksWithZones

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#23958]
From http://build.chromium.org/p/client.dart/builders/vm-linux-debug-ia32-be/builds/4692/steps/tests/logs/stdio

=== Failure summary:

FAILED: none-vm debug_ia32 vm/cc/ManyTasksWithZones
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

stdout:
Running test: ManyTasksWithZones

stderr:
runtime/vm/isolate.h:164: error: expected: mutator_thread_ == __null || IsIsolateOf(mutator_thread_)

Command[run_vm_unittest]: DART_CONFIGURATION=DebugIA32 out/DebugIA32/run_vm_tests --ignore-unrecognized-flags ManyTasksWithZones
Took 0:00:00.250000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 vm/cc/ManyTasksWithZones

**Comment by kodandersson** [comment]
This is a race in the DEBUG-mode assertion.

Current hypothesis from core dump analysis:
When the mutator thread is exiting an isolate, there are two NULL writes: into Isolate::mutator_thread_ and Thread::isolate_. If another (helper) thread is entering the same isolate at the same time, it might observe those two NULL writes in the wrong order, causing the DEBUG_ASSERT to fail.

One fix is to ensure memory ordering, e.g., with a mutex.

**Comment by kodandersson** [comment]
Fixed by 7d82391e8949513ced7be0ee6cd56b9f4a38fcd8
