### ISSUE TITLE
Clicking to set a breakpoint removes focus from debug input

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23956]
In `Dart VM version: 1.12.0-dev.3.1`

Clicking to set a breakpoint in the source code (the little B) removes the focus from the input text field.

I was trying to set a breakpoint and then hit c to continue.

Thanks for taking a look!

**Comment by sethladd** [comment]
cc @turnidge

**Comment by turnidge** [comment]
Fixed in f73b8aa019adcc1a443ceb0f61953853130fa528

**Comment by sethladd** [comment]
Thanks!
