### ISSUE TITLE
Request: requesting a .packages file from http: import of an entry point

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23952]
If a Dart runtime fetches an entry point from an `http:` URI, according to DEP https://github.com/dart-lang/dart_enhancement_proposals/issues/5 (detailed here: https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md) , the Dart runtime should:

> Look for a .packages file next to the program entry point (which can then not be given using a package: URI). For example running an application like:
> `dart http://example.com/smarty/main.dart`
> will cause the dart stand-alone VM to check for the existence of http://example.com/smarty/.packages, and if that URI returns a file, use the content for resolving package URIs in the application.

**Comment by iposva-google** [comment]
Fixed with https://codereview.chromium.org//1268313002
