### ISSUE TITLE
The `log` function in `dart:developer` should be more user friendly.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#23950]
The `log` function in `dart:developer` assumes optional named arguments are supplied.

The sequence number and timestamp are converted to 64-bit integers without checking if they are `null`.
Both can have reasonable defaults (one plus previous sequence number and current time, respectively), and the function should supply these if they are not provided.

The timestamp should probably be a DateTime, not an integer.

The level should have a default.

Both name and message are expected to be passed. That may be reasonable, but since it's only checked in C++ code, the error message is just the generic "Invalid arguments(s)" response usually reserved for invalid native calls, which we try to avoid showing by testing the parameters in Dart before calling the native function.
If the parameters are not optional, it might be better to not make them named.

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1266053003
