### ISSUE TITLE
analyzer: quick fixes don't always suggest import

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23966]
Quick fixes don't seem to always suggest importing a library, see this gif:

![](http://i.imgur.com/yy0Aw2q.gif)

If I press ctrl+space two times, I do get the suggestion, and after it is already imported once, I also do get a quick fix suggestions. If I then restart the analyzer the quick fix disappears again.

**Comment by sethladd** [comment]
I wonder if this is a WebStorm issue?  (because of the ctrl-space two times)

cc @jwren

**Comment by alexander-doroshko** [comment]
Completion is shown on the screenshot just to illustrate that appropriate import statement that makes code green exists. I guess the issue is that DAS doesn't suggest Quick Fix to add corresponding import.

**Comment by kasperpeulen** [comment]
Yeah, indeed so bascily I can do an auto import with pressing ctrl+space two times.

But I can not get an auto import with alt+enter (quick fix).

Except if I already imported the library once, and then removed it. Then I *can* auto import the library with alt+enter (quick fix)

**Comment by kasperpeulen** [comment]
@alexander-doroshko 

It seems like with this commit the auto completions also uses DAS ?
https://github.com/JetBrains/intellij-plugins/commit/bd3f0ba23d39521258a5b5387e091966d63f67e7

Because now if I do ctrl+space two times I don't get the auto import any more:
![](http://i.imgur.com/LXnqb6Z.gif)

**Comment by alexander-doroshko** [comment]
Yes, auto-import feature is lost for a while. Ping https://github.com/dart-lang/sdk/issues/21931

**Comment by scheglov** [comment]
Yes, until the library is imported once, somewhere in the project, DAS does not analyze it.
So, DAS has no idea what is in the library.
So, it cannot create a quick fix.

Analyzing all the libraries from all the imported packages might be too expensive.

**Comment by kasperpeulen** [comment]
For me, this feels like a regression, because as far as I can remember, it used to work in webstorm. @scheglov
