### ISSUE TITLE
Code completion doesn't respect import prefix presence

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#23969]
![image](https://cloud.githubusercontent.com/assets/4499789/9068214/c8e15a94-3aea-11e5-8e71-cd6ca821ef33.png)

Selecting any variant from completion leads to red code because all classes from `dart:core` must be used via `core` import prefix. I suggest that variants in completion list appear like `core.String`, `core.StringBuffer`, etc.

**Comment by danrubel** [comment]
Yes, we definitely need to address this issue.

@alexander-doroshko In the situation above, would we want to have a suggestion "core.String" or just "String" and if selected then "core.String" would be inserted?

@devoncarew @lukechurch Any thoughts on what would be best for users?

**Comment by alexander-doroshko** [comment]
I think, `core.String`. There might be other String classes accessible via other import prefixes. In this case seeing both `core.String` and `other.String` in the completion list looks logical.

**Comment by devoncarew** [comment]
If they prefix `dart:core`, should they need to type in `core.` before they start seeing completions from the core library?

**Comment by alexander-doroshko** [comment]
As a user I like when IDE saves my keystrokes. So I'd like to have prefixed symbols in completion even if I didn't type prefix yet.

**Comment by kasperpeulen** [comment]
not sure if it is worth something, but I agree with @alexander-doroshko I would like that as well.

**Comment by zoechi** [comment]
If it shows the prefix in the completion list it would be great. Otherwise it would not be possible to distinguish two elements with the same name but different prefixes.

**Comment by bwilkerson** [comment]
I agree; I'd also like to have the prefix in the list. But this means that clients will need to not filter out suggestions where there is a prefix that doesn't match the identifier that is before the cursor.

**Comment by alexander-doroshko** [comment]
Correct. Not sure about other IDEs, but it is easily controlled in IntelliJ/WebStorm. If you typed `Str` you'll get `core.String` in completion.

**Comment by bwilkerson** [comment]
@danrubel Is this fixed, or should we remove the "FixIt" label?

**Comment by alexander-doroshko** [comment]
@bwilkerson @danrubel Not fixed yet as of 1.14.0-dev.7.1

**Comment by alexander-doroshko** [comment]
@danrubel Seems to be fixed as of Dart SDK 1.15-dev.4.0.
In SDK 1.14 it also works fine for all import prefixes except the prefix for 'dart:core', but in 1.15-dev.4.0 it handles 'dart:core' correctly as well.

**Comment by danrubel** [comment]
Thanks for confirming!
