### ISSUE TITLE
Warnings for missing methods from superclass could include more info

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23965]
_From @sethladd on July 29, 2015 22:58_

![screen shot 2015-07-29 at 3 56 50 pm](https://cloud.githubusercontent.com/assets/5479/8971971/7e0808c2-360a-11e5-8bb6-3b20e1bd9d63.png)

Notice how it says "missing concrete implementation of setter 'List.length'". It would be nice if it showed the signature for `length`.

Better yet, it would be great if there was a quick fix that just added in those method. :)

_Copied from original issue: dart-atom/dartlang#131_

**Comment by sethladd** [comment]
_From @devoncarew on July 30, 2015 17:20_

@lukechurch

@sethladd - thanks for the report. I believe the resolution for this would be in the analysis engine.

**Comment by sethladd** [comment]
Ah, that message comes straight from the analysis server? OK, I'll move the issue.

**Comment by bwilkerson** [comment]
Yes, this comes from the analysis server. There is a quick fix for the warning that does what you want, but it appears that Atom is not able to display quick fixes if there is more than one (and in this case there is). Sorry to ping-pong, but I think this is a UI issue.

**Comment by sethladd** [comment]
Thanks, good to know there is a quick fix!
