### ISSUE TITLE
Typo in StreamSubscription

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23961]
From https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream.dart#L1308:

     * A subscritption on events from a [Stream].

@lrhn

**Comment by sethladd** [comment]
Good catch! :)

**Comment by floitschG** [comment]
Lasse fixed it with 0a35f7be3bc2d6dd598374c8abed6bff768c72cc
