### ISSUE TITLE
analyzer: convert arrow function to normal function

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23963]
I would wish that some refactoring like this existed:
**convert arrow function to normal function** (and vice versa)

basicly, it should refactor:
```dart
bool get dartIsAwesome => true;
```

to:
```dart
bool get dartIsAwesome {
  return true;
}
```

**Comment by alan-knight** [comment]
It used to exist in the editor and was one of my most commonly used refactorings.

**Comment by bwilkerson** [comment]
@kasperpeulen Which editor/IDE are you using? This functionality is available in server as a quick assist, but the way you access quick assists differs from one editor to another.

**Comment by kasperpeulen** [comment]
Ah, I use webstorm, for some reason I never noticed. I was looking here:

![image](https://cloud.githubusercontent.com/assets/1035299/9069238/5c08e2c2-3ae8-11e5-818a-d1e0ff7f67f0.png)

But I can just press alt+enter, that is awesome!
![](http://i.imgur.com/5dQHurw.gif)

I have one suggestion, it doesn't give me a quick assist in this case:
![image](https://cloud.githubusercontent.com/assets/1035299/9069266/9078074a-3ae8-11e5-958e-e38bff359165.png)

I would think it may be nice, to also do the quick assist suggestion in this case.

Also, for the other way around, if the return type is void, maybe not do a return statement ? So basicly, converting:
```dart
document.onClick.listen((e) => print('hello world'));
```

to 

```dart
document.onClick.listen((e) {
  print('hello world');<caret>
});
```

and put the caret in that position ?

**Comment by scheglov** [comment]
1. Support for Quick Assists from DAS is very new, it was landed into the IDEA plugin yesterday. So, this may be the reason why you haven't see it before :-)

2. Agree, we can improve it for void expressions.

3. I don't know yet how and what to support for caret, but I will check in the future.

**Comment by scheglov** [comment]
2. Improving for void expressions and exit position (not used yet in DPI).
  Started. https://codereview.chromium.org/1267333003

**Comment by scheglov** [comment]
Improved support for void expressions landed in DAS.
https://github.com/dart-lang/sdk/commit/d11b644cc5d9e80920a0d48f101075ec46e122b9

**Comment by kasperpeulen** [comment]
awesome, thanks

**Comment by scheglov** [comment]
DAS already produces "exit position" for converting expression function bodies to block function bodies.
So, it's an IDEA plugin issue.

**Comment by alexander-doroshko** [comment]
What is IDEA plugin issue? Since DAS-powered quick assists are already integrated IntelliJ IDEA / WebStrom have this intention action in Alt+Enter popup.

**Comment by scheglov** [comment]
We don't apply the "selection" result in the IDEA plugin:
```json
{
  "id": "397",
  "result": {
    "assists": [
      {
        "message": "Convert into block body",
        "edits": [
          {
            "file": "/Users/scheglov/dart/test/bin/test.dart",
            "fileStamp": 1444060804540,
            "edits": [
              {
                "offset": 6,
                "length": 12,
                "replacement": "{\n  print(0);\n}"
              }
            ]
          }
        ],
        "linkedEditGroups": [],
        "selection": {
          "file": "/Users/scheglov/dart/test/bin/test.dart",
          "offset": 19
        }
      }
    ]
  }
}```
