### ISSUE TITLE
Debugger test failure uncovered by vmservice change

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#23977]
Starting the server for the VM Service unconditionally as in this patch:

https://codereview.chromium.org/1268143003

Causes a debugger test to fail. Mysteriously, the test _also_ fails when --enable_vm_service is provided on the command line, which is normally what would have caused _autoStart to be true.

zra@zach:~/dart/sdk$ out/DebugIA32/dart  -p out/DebugIA32/packages tests/standalone/debugger/nosuchmethod_debugger_test.dart args: --debug:0 /usr/local/google/home/zra/dart/sdk/tests/standalone/debugger/nosuchmethod_debugger_test.dart --debuggee
Debug target process started, pid 32707.
TARG: Debugger listening on port 36145
Debug target found listening at port '36145'
Debuggee isolate id 730182220 created.
TARG: Observatory listening on http://127.0.0.1:46828
Matched frames: [main]
Matched frames: [main]
Set breakpoint at line 19 in file:///usr/local/google/home/zra/dart/sdk/tests/standalone/debugger/nosuchmethod_debugger_test.dart
Command: resume
TARG: Hello from debuggee
Isolate 730182220: breakpoint 2 resolved at location {url: file:///usr/local/google/home/zra/dart/sdk/tests/standalone/debugger/nosuchmethod_debugger_test.dart, libraryId: 14, tokenOffset: 80}
Matched frames: [main]
Matched locals (i)
Command: stepInto
Command: stepInto
Sending kill signal to process 32707...
Connection closed by debug target
process 32707 terminated with exit code -15.

===== Errors detected: =====
Error: call frame 0: expected function name 'A.noSuchMethod' but found '_InvocationMirror@915557746._allocateInvocationMirror@915557746'
Error while matching response to debugger command
...

**Comment by zanderso** [comment]
@johnmccutchan @turnidge

**Comment by johnmccutchan** [comment]
The legacy debug protocol has been removed.

**Comment by iposva-google** [comment]
@johnmccutchan, @zanderso  Is this still a problem? If not, please close.
