### ISSUE TITLE
for completions includes parenthesis but if/while/switch etc don't include parenthesis

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23978]
I would think this should be kind of consistent maybe ?

![image](https://cloud.githubusercontent.com/assets/1035299/9075691/11034fe4-3b18-11e5-8678-0517324e07e4.png)

![image](https://cloud.githubusercontent.com/assets/1035299/9075704/38e0d2e8-3b18-11e5-91a7-c89414941ebd.png)

![image](https://cloud.githubusercontent.com/assets/1035299/9075709/40ad76de-3b18-11e5-8f09-882fa3584425.png)

Also, if I complete the `for` suggestion, the caret ends up here:
![image](https://cloud.githubusercontent.com/assets/1035299/9075721/71f672a4-3b18-11e5-95a3-6e6da61791b3.png)

I would think caret should be one to the left, not sure if this is a webstorm issue ?

**Comment by alexander-doroshko** [comment]
caret placement is WebStorm issue

**Comment by kasperpeulen** [comment]
@alexander-doroshko ah, okay, shouldn't it be better if the analyzer also gives information about where the caret should be after the completion.

I see that both atom, dartpad, and webstorm doesn't do the right caret position after completing this `for` statement. Also for things like completing:

```dart
import '' show ;<caret>
```

the caret ends up in this place in all 3 editors. It seems ideal to me that the analyzer can give information about where the caret should be after completing.

**Comment by alexander-doroshko** [comment]
Analyzer gives this info but IDEs do not handle it correctly.

**Comment by danrubel** [comment]
After discussion, we decided that client templates are more expressive and thus are removing the () from the for keyword suggestion along with the import suggestion variations. Instead, if the client wants something more than just the keyword inserted, they can detect a specific keyword suggestion and dynamically replace that with a template. For example, if the analysis server suggests the 'import' keyword, then the client could dynamically replace that suggestion with multiple import templates such as
```dart
import '';
import '' as ;
import '' show ;
```
