### ISSUE TITLE
Observatory debugger: typing 'up' moves down a frame

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23973]
Just a bit of disconnect... 'up' and 'down' as commands in the text input field don't map to what's happening in the UI. In the UI, I move down and up. :)

**Comment by sethladd** [comment]
cc @turnidge

**Comment by iposva-google** [comment]
This behaves exactly as it should be and how it is expected by developers. The top of the stack is at the top visually.

Quoting from https://sourceware.org/gdb/current/onlinedocs/gdb/Selection.html#Selection
up n
Move n frames up the stack; n defaults to 1. For positive numbers n, this advances toward the outermost frame, to higher frame numbers, to frames that have existed longer.

down n
Move n frames down the stack; n defaults to 1. For positive numbers n, this advances toward the innermost frame, to lower frame numbers, to frames that were created more recently. You may abbreviate down as do.

**Comment by turnidge** [comment]
I have added a way to toggle this in Observatory debugger.

To get the gdb-like meaning of up and down type:

```
set up-is-down true
```

This setting is stored in the browser's local storage and should persist between runs.

By default, up and down will now correspond to up and down in the UI.

Changed in 5b6136fdfb0addf98abc52fff1c605a84bfd465c.
