### ISSUE TITLE
analysis server spec html generator: add index for easier navigation of html file

### ISSUE THREAD

**Issue by guillermooo** [dart-lang/sdk#23971]
This was discussed a while ago in the analyzer mailing list. I can have a go at implementing an index that links to the requests, types etc from the bottom of the file. The api has grown quite a bit and hunting down the item you're interested in looking up is no fun. Hopefully, an index would make it simpler to browse the different types, requests, etc.

Very rough WIP below.

![index](https://cloud.githubusercontent.com/assets/684948/9071568/3784b9c2-3af6-11e5-924b-cc7f174f838a.png)

Suggestions welcome! I'm planning to use tables to compact the sections, very much like the Python docs do for basically the same thing; see: https://docs.python.org/3/library/functions.html

**Comment by bwilkerson** [comment]
That looks good to me! We should also add a link to the index from the "table of contents" near the top of the document.

**Comment by guillermooo** [comment]
I'll do that. I'm also thinking about adding an `<index>` element to the input to formalize its place in the doc.

**Comment by guillermooo** [comment]
[ ] add link to index  to table of contents
[ ] add `<index>` element to raw input file

**Comment by bwilkerson** [comment]
That sounds reasonable, too.

**Comment by guillermooo** [comment]
First attempt, using floats instead of tables. I'm not a CSS expert, but this layout seems to work fine for the desktop as well as for mobile (if that matters).

![desktop](https://cloud.githubusercontent.com/assets/684948/9079124/fe9de47a-3b46-11e5-89d0-29870bc73ccf.png)

![mobile](https://cloud.githubusercontent.com/assets/684948/9079125/fe9fee00-3b46-11e5-9467-10a4a14382c6.png)

**Comment by bwilkerson** [comment]
Nice!
