### ISSUE TITLE
library name when creating a new dart file doesn't respect the dart style guide

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23972]
say i have this file in `lib/bar.dart`: 

```dart
library bar;  
import 'dir/foo.dart'; 
```

If the import `dir/foo.dart` doesn't exist. I can use alt+enter in webstorm to create the file, and it gives the file the library name: `foo` which I think is very nice, but the style guide says to give `lib/dir/foo.dart` the library name `[packagename].dir.foo`, see: 
https://www.dartlang.org/articles/style-guide/

**Comment by kasperpeulen** [comment]
Hm.. it gives the file 'command_runner.dart' the library name 'command.runner'. I don't understand the reasoning behind that.

**Comment by scheglov** [comment]
Started.
https://codereview.chromium.org/1253103007

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/fbb7aedee54770c1c8a040aa9415cbd33a021785

**Comment by kasperpeulen** [comment]
wow that is fast, thanks :dancers:
