### ISSUE TITLE
Function as listener argument is not suggested by code completion

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#23984]
![image](https://cloud.githubusercontent.com/assets/4499789/9089448/d703cd1a-3b9d-11e5-894b-a1be5a8f5f80.png)

It seems to depend on function return type: `void` vs `dynamic`. In this sample both `clickHandler` and `otherClickHandler` work, but completion suggests only `otherClickHandler`.

Code to copy/paste:

```
import 'dart:html';

main() {
  var element = querySelector("foo");
  element.onClick.listen(cli);
}

void clickHandler() {}

otherClickHandler() {}
```

**Comment by srawlins** [comment]
[Stream<T>.listen](https://api.dartlang.org/dev/2.0.0-dev.37.0/dart-async/Stream/listen.html)'s first parameter is a `void Function(T)`, but your `clickHandler` is a `void Function()`. It should not suggest `clickHandler`.

**Comment by alexander-doroshko** [comment]
@srawlins I guess either both `clickHandler()` and `otherClickHandler()` should be in the completion list or none. 
BTW nothing changes if I add a parameter to both functions (and in this case, both variants should definitely be suggested):
```
import 'dart:html';

main() {
  var element = querySelector("foo");
  element.onClick.listen(cli<caret>);
}

void clickHandler(MouseEvent a) {}

otherClickHandler(MouseEvent a) {}
```

I do not have permissions to reopen the issue.

**Comment by srawlins** [comment]
Sorry about that. You're right. `void clickHandler(MouseEvent a) {}` and `otherClickHandler(MouseEvent a) {}` should be suggested.

**Comment by bwilkerson** [comment]
The situation is almost worse at this point. In the following code, placing the cursor after `(cli` and requesting completions the returned list includes `otherClickHandler` but not `clickHandler`.

```
class C<T> {
  void m(void Function(T) f) {}
}

void f(C<String> c) {
  c.m(cli);
}

void clickHandler(String s) {}
otherClickHandler(String s) {}
```
