### ISSUE TITLE
No top-level setter declared when using ??

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#23988]
to reproduce:
dartium version: 39.0.2171.0 (Developer Build) custom
dart version: 1.12.0-dev.4.0
in the dartium debugger, evaluate `2 ?? 1`.  it will correctly print 2.
now evaluate `var x = 2 ?? 1`.  it will incorrectly set x to 1.
the same problem happens when executing loaded code.  it's not just a debugger problem.

**Comment by trinarytree** [comment]
this is interesting.  if i reload the debugger and make sure no variable x is in scope,
when i execute `var x = 2 ?? 1`, it says
```
Unhandled exception:
No top-level setter '$consoleVariables=' declared.

NoSuchMethodError: method not found: '$consoleVariables='
Receiver: top-level
Arguments: [...]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      Eval.<anonymous closure> (evaluate:source:2:23)
```

then if i execute `var x = 3` and then `var x = 2 ?? 1`, it will print 3!
so i think once dartium sees the ??, it refuses to do the assignment and simply returns the current value of x.

**Comment by trinarytree** [comment]
even weirder:
```
var x = 3
x = (2 ?? 1)       // returns 3, doesn't do the assignment
x = (2 ?? 1) + 0   // returns 2, does the assignment
```

**Comment by jacob314** [comment]
To be clear. This is a dart vm issue not a devools issue.

Example repro:

void main() {
  var x;
  var y;
  // This call is fine
  x = (() => (2 ?? 3))();
  print("x = $x");

  // This throws "No top-level setter 'y=' declared
  y = 2 ?? 3;
  print("y = $y");
}

**Comment by mhausner** [comment]
Looking at this.

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
fc55f38aaf053a62d1959b09644ecff49fc35d43 (presubmit successful).

https://codereview.chromium.org/1273033007/
