### ISSUE TITLE
code completion in function arguments could be improved

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23992]
This code completion is powered by DAS. So I guess this is not a webstorm issue:

![image](https://cloud.githubusercontent.com/assets/1035299/9100081/0d0c4eb2-3bd7-11e5-9609-6ff2f7267fe1.png)

I get lots of noise, but not the only valid thing I could place here, which is arg1,arg2 or arg3. If I would type `a`, I do get the named parameters:

![image](https://cloud.githubusercontent.com/assets/1035299/9100130/673c440a-3bd7-11e5-9293-6ae41af6ae76.png)

But also completions, that doesn't make sense. I think the only valid thing I could write here is, arg1, arg2 or arg3.

**Comment by kasperpeulen** [comment]
I was looking how this could be implemented. Essentially, if there are named parameters in the completion list, I think you can safely conclude that all other parameters are junk.

I'm not totally sure if and how this would be possible, but I think, something like this should work:
```
if completions.any(c.kind == Completion.NAMED_PARAMETER) :
  completions.removeWhere(c.kind != Completion.NAMED_PARAMETER)
```

**Comment by kasperpeulen** [comment]
It seems like something like this indeed works:
https://github.com/dart-lang/sdk/commit/2e33b737cb7447646a75e30e54d9c3479e360a66

![image](https://cloud.githubusercontent.com/assets/1035299/11580378/315d534c-9a37-11e5-9ea2-f4573f207695.png)

I think this is also the fastest way to do it.

**Comment by kasperpeulen** [comment]
https://codereview.chromium.org/1497133002

**Comment by danrubel** [comment]
This may be the right patch, but I'd rather update the contributors to not suggest those suppressed suggestions in the first place. Let me think about this over the next several days and get back to you.

**Comment by danrubel** [comment]
Code completion is designed to operate on code that is being written (obviously), and as such needs to be flexible in what it suggests. If completing arguments in a method invocation and it's appropriate to show named param, then we do so and we prioritize those suggestions above all others because most likely that is what is desired. But should we suppress the other suggestions? What if the user is adding a new required param to a method invocation and will later update the method declaration parameters? Obviously this is not a common case which is why we always list the named param first, but should we never show the others? I don't know whether we should or should not. Something to ponder.

**Comment by kasperpeulen** [comment]
> This may be the right patch, but I'd rather update the contributors to not suggest those suppressed suggestions in the first place

I've been trying to implement it like that first. But, I ended up with a lot of code, to find out what the parameters of the function/method/constructor/annotation are, and then I needed to check if the place of the caret is not the place of a positional argument.

Basically copying what happens in ArgListContributor, but then in other contributors, to make sure completions are not added. It seemed smarter to me, to do this logic only in one place.

> I don't know whether we should or should not. 

Personally, I like it, if I'm doing something that is not supposed to work, that I then get no completions. For example, maybe I'm expecting Duration to have one required parameter (int milliseconds).

```
int timeOut = 3000;
new Duration(ti^)
```

I'm just typing, and I get this:

![image](https://cloud.githubusercontent.com/assets/1035299/11595027/a6b8ceca-9aad-11e5-917f-75948161d686.png)

I would rather have no completion, that immediately tells me I'm doing something wrong. That is how most (all?) dart completions work, and I like that, if I then go back, I see that the only allowed completions here are named arguments.

**Comment by danrubel** [comment]
When the method declaration is in a library that you cannot edit (e.g. not in the workspace) and only named parameter suggestions make sense, then I agree that we should not show other suggestions. I also agree that adding lots of code/overhead to other contributors doesn't make sense either. I'll continue to ponder this over the next several days.

**Comment by kasperpeulen** [comment]
> When the method declaration is in a library that you cannot edit (e.g. not in the workspace) and only named parameter suggestions make sense, then I agree that we should not show other suggestions. 

Okay, makes sense

**Comment by danrubel** [comment]
There seem to be two issues here:
[ ] [remove argument list suggestions](#25197) ... because neither IntelliJ nor Atom use them
[ ] [don't show other suggestions when showing named argument suggestions](#25198)
