### ISSUE TITLE
 Failed to download resource "dart"

### ISSUE THREAD

**Issue by lanzf** [dart-lang/sdk#23993]
Ｉ used
"brew install dart --with-content-shell --with-dartium" command line for get Dark SDK,but  got the message :
curl: (7) Failed to connect to storage.googleapis.com port 443: Operation timed out
Error: Failed to download resource "dart"
Download failed: https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.3/sdk/dartsdk-macos-x64-release.zip

And I go to https://www.dartlang.org/downloads/archive/  there is no macos version ,How to get Dark SDK?

**Comment by whesse** [comment]
The SDK for Mac OS X is there, at the URL listed above, and is also at https://www.dartlang.org/downloads/archive/ .  I am able to download it from both places.  The dropdown menu at www.dartlang.org/downloads/archive must have Mac chosen.

This may have been a one-time failure, connecting to Google cloud storage.
Please reopen this if you continue to have this problem.

**Comment by avstudios** [comment]
I have same problem. The only difference is error url.
```Download failed: https://gsdview.appspot.com/dart-editor-archive-integration/11397/dartsdk-macos-64.zip```

**Comment by whesse** [comment]
avstudios: I don't know where you are getting this URL from.  There is no bucket called dart-editor-archive-integration.  What are you trying to do, and what page are you doing it from?  Are you using homebrew, with the tap "brew tap dart-lang/dart"?  Are you downloading from the dartlang.org web page?

**Comment by avstudios** [comment]
@whesse I'm using homebrew with ```brew tap dart-lang/dart```. Using instructions from ```https://www.dartlang.org/downloads/mac.html#homebrew```. I've upgraded homebrew to latest version. 
I don't know why the url is different to ```https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.3/sdk/dartsdk-macos-x64-release.zip```.

**Comment by whesse** [comment]
It sounds like an out-of-date formula.  I would uninstall dart, brew untap dart-lang/dart, tap it, brew update, and then try installing again.

If this doesn't work, you could look inside the caches for homebrew to see where that url is coming from, using grep, for instance.

**Comment by avstudios** [comment]
There was an issue with Homebrew. I had to run ```cd /usr/local/Library && git stash && git clean -d -f```` to set the right url. All works fine now. Thanks Will.
