### ISSUE TITLE
VM deadlocks when passed the "--packages" flag

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23991]
When the VM is passed the `--packages` flag pointing to a valid package spec, it deadlocks without ever starting the application. For example, if you have:

```dart
// app.dart
void main() => print("hello!");
```

```
// .packages
myapp:lib/
```

And you run `dart --packages=.packages app.dart`, it will never print anything and never exit.

**Comment by sethladd** [comment]
Confirmed in SDK version 1.12.0-dev.5.0 

Thanks for the report.

**Comment by iposva-google** [comment]
Fixed with https://codereview.chromium.org/1278623002
