### ISSUE TITLE
Async* yield semantics incorrect on VM

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23994]
The new test language/async_star_regression_fisk_test.dart fails on the VM, because the second call to yield in the generator function fisk, in the third call to function fugl, throws to the finally clause, because the stream is cancelled, before the expression in the yield statement (an await expression) evaluates to an object, which is not the order specified in the specification of the yield statement.

Test marked in status file language/language.status.

**Comment by floitschG** [comment]
This was a bug in the stream class, not the VM.
see https://codereview.chromium.org/1284223005

The different behavior of the VM and dart2js is explained by an additional scheduleMicrotask that dart2js does when executing finallys. (I believe the spec allows that additional call).
