### ISSUE TITLE
await for does not send pause/resume to its stream, when there is an await in the body, on the VM.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23996]
Regression test: language/async_star_await_pauses_test.

Any await statement inside an await for is supposed to pause the stream associated with the await for.

**Comment by lrhn** [comment]
The reason it doesn't happen now is that await-for is implemented using `StreamIterator` which has a  one-element cache. The original source will only be paused if another event arrives before the loop continues, which a simple test like this won't hit.

For the record, I think the spec is overly specific about when streams must be paused.

**Comment by iposva-google** [comment]
CC: @mhausner

As Lasse points out the VM's implementation is following the spirit of the spec, if not the exact details. There are no current plans to address this issue.

Should we have an updated test which verifies that an await-for implementation does not consume "unbounded" values from a stream, to ensure that we continue following the spirit of the spec?

**Comment by mhausner** [comment]
dart2js uses the same StreamIterator with a one element cache. Thus, I'd expect the VM and dart2js to having matching behavior at least. (bug 23995 confirms my expectation.)

I like Ivan's idea to have a test that ensures the stream is paused, ensuring that there no unbounded generation of stream elements.

**Comment by whesse** [comment]
The test is currently skipped, because it times out, on the vm and on browsers.

We could stop the test from timing out, by putting  a watchdog timer in it, and having it exit, but since
we intend to keep this "broken" behavior, the test will never pass.  I think we should delete this test, and write a new one which will test the current behavior of the StreamIterator, as Ivan suggested.

Deleting the current language/async_star_await_pauses_test.  Someone should write a new one.

**Comment by whesse** [comment]
I changed my mind, and fixed the test instead.  I will close the issue when the new test is committed:

https://codereview.chromium.org/1869583003/

**Comment by zanderso** [comment]
It looks like this can be closed.
