### ISSUE TITLE
code completion should suggest named parameters for constructors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24004]
See also https://github.com/dart-atom/dartlang/issues/186. Code completion for names parameters _is_ working for functions but not constructors.

I couldn't find another bug tracking this issue.

@danrubel

**Comment by devoncarew** [comment]
@danrubel, I'm still seeing this. I'm using the latest dev SDK build, which should have your change.

You can confirm by creating a new sky project and trying to code complete in any of the constructors (`Scaffold`, `Toolbar`, ...):

```dart
import 'package:sky/widgets.dart';

void main() => runApp(new HelloWorldApp());

class HelloWorldApp extends App {
  Widget build() {
    return new Scaffold(
        toolbar: new ToolBar(center: new Text("Sky Demo")),
        body: new Material(child: new Center(child: new Text("Hello world!"))),
        floatingActionButton: new FloatingActionButton(
            child: new Icon(type: 'content/add', size: 24)));
  }
}
```

**Comment by bwilkerson** [comment]
I believe this is now working as expected.
