### ISSUE TITLE
FormElement in dart:html missing `elements` property

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#24008]
http://www.w3schools.com/jsref/coll_form_elements.asp

**Comment by alan-knight** [comment]
It's explicitly suppressed. I don't know what the reason is.

**Comment by jakemac53** [comment]
I wonder if originally it was though that this was equivalent to `children`?

**Comment by zoechi** [comment]
Just stumbled upon this as well.
It's part of the HTML5 spec 
http://www.w3.org/TR/html5/forms.html#dom-form-elements 
would be nice to have.
