### ISSUE TITLE
Observatory "Connect to a Dart VM" page contains a hard coded port

### ISSUE THREAD

**Issue by Fox32** [dart-lang/sdk#24014]
On the right of the page the documetation says:

```
Request a crash dump with:
'curl localhost:8181/_getCrashDump > dump.json'
```

The comment doesn't help as port 8181 is a hardcoded port and not the port the observatory is served from. Replacing the port with the right one works.

**Comment by johnmccutchan** [comment]
The text was meant to be an illustrative example and not be copy and pasteable. But your point is a good one, we can easily make this the real port.

**Comment by johnmccutchan** [comment]
@B3rn475 Please attempt to fix this.
