### ISSUE TITLE
Provide a way of getting a map supporting lookup from packageName to Uri

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24022]
By analogy with `Platform.packageRoot`. This is useful for ensuring that spawned tools like the analyzer or the VM run in the same package context as the current process.

/cc @davidmorgan

**Comment by sethladd** [comment]
For completeness, what would the getter return?

**Comment by nex3** [comment]
Personally, I'd prefer it return the URI of the package spec file if one was used for the current isolate (or maybe for the VM as a whole?). That doesn't exactly match the behavior of `Platform.packageRoot`, though, which returns *exactly* the value of the `--package-root` flag provided to the VM, if any. In general that tends to be less than optimally helpful, though, since there may be a package root/spec in effect even if it's not explicitly passed.

**Comment by mit-mit** [comment]
Punting to 1.13 based on prioritization in #23372

**Comment by sethladd** [comment]
cc @iposva-google who I think is looking into this.

**Comment by mit-mit** [comment]
Landed: https://codereview.chromium.org/1334353002/

**Comment by sethladd** [comment]
:+1:

**Comment by nex3** [comment]
This has been rolled back, so I'm re-opening.

Also, the new name for this property is `Isolate.packageConfig`.

**Comment by mit-mit** [comment]
I believe this has landed

**Comment by nex3** [comment]
This hasn't landed yet; the new APIs don't include a map, just a function to do the lookup, which isn't what we asked for. @mit-mit can you reopen?

**Comment by iposva-google** [comment]
"Personally, I'd prefer it return the URI of the package spec file if one was used for the current isolate" is exactly what you asked for and getting with Isolate.packageConfig. Keeping closed.

**Comment by nex3** [comment]
I'm sorry, you're right. I'll file a separate issue for the map.
