### ISSUE TITLE
Problem with "pub get" of "sky"

### ISSUE THREAD

**Issue by RossBabcock3** [dart-lang/sdk#24027]
IO  : Spawning "C:\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz"
in C:\Users\Ross\AppData\Local\Temp\pub_a5d5d995-3e25-11e5-826d-303a64246ad9
IO  : Finished C:\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe. Exit code 0.
    | stdout:
    | |
    | | 7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    | |
    | | Processing archive: data.tar.gz
    | |
    | | Extracting  data.tar
    | |
    | | Everything is Ok
    | |
    | | Size:       98856960
    | | Compressed: 30545368
    | Nothing output on stderr.
IO  : Spawning "C:\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe x C:\Users\Ross
\AppData\Local\Temp\pub_a5d5d995-3e25-11e5-826d-303a64246ad9\data.tar" in C:\Use
rs\Ross\AppData\Roaming\Pub\Cache\_temp\dira5d5d994-3e25-11e5-826d-303a64246ad9
ERR : Timed out after 30.0s while downloading https://pub.dartlang.org/packages/
material_design_icons/versions/0.0.2.tar.gz.
    | This is likely a transient error. Please try again later.
FINE: Exception type: TimeoutException
ERR : package:pub/src/io.dart 831  timeout.<fn>
    | dart:isolate                 _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                              Timer.Timer
    | package:pub/src/io.dart 820             timeout
    | package:pub/src/source/hosted.dart 194  HostedSource._download.<fn>.<fn>
    | dart:isolate                            _RawReceivePortImpl._handleMessage

    | ===== asynchronous gap ===========================
    | dart:async                              _Future.then
    | package:pub/src/source/hosted.dart 193  HostedSource._download.<fn>
    | dart:async                              Future.Future.sync
    | package:pub/src/source/hosted.dart 184  HostedSource._download
    | package:pub/src/source/hosted.dart 93   HostedSource.downloadToSystemCache
.<fn>
    | dart:isolate                            _RawReceivePortImpl._handleMessage

    | ===== asynchronous gap ===========================
    | dart:async                             _Future.then
    | package:pub/src/source/hosted.dart 86  HostedSource.downloadToSystemCache
    | package:pub/src/source/cached.dart 51  CachedSource.get
    | package:pub/src/entrypoint.dart 365    Entrypoint._get.<fn>
    | dart:async                             Future.Future.sync
    | package:pub/src/entrypoint.dart 357    Entrypoint._get
    | dart:async                             Future.wait
    | package:pub/src/entrypoint.dart 133    Entrypoint.acquireDependencies.<asy
nc>
    | dart:isolate                           _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                           _Future.then
    | package:pub/src/entrypoint.dart 115  Entrypoint.acquireDependencies.<async
>
    | dart:isolate                         _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/entrypoint.dart          Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 30      GetCommand.run
    | package:args/command_runner.dart 178     CommandRunner.runCommand.<fn>
    | dart:async                               Future.Future.sync
    | package:args/command_runner.dart 131     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<asyn
c>.<fn>
    | dart:async                               Future.Future.sync
    | package:pub/src/utils.dart 103           captureErrors.<fn>
    | package:stack_trace/src/chain.dart 78    Chain.capture
    | package:pub/src/utils.dart 117           captureErrors
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<asyn
c>
    | dart:isolate                             _RawReceivePortImpl._handleMessag
e
---- End log transcript ----

**Comment by RossBabcock3** [comment]
Everything goes fine until "material_design_icons" try to download. At that point I get a timeout.

**Comment by sethladd** [comment]
Thanks for the report. What version of pub are you using? The timeout was removed in 1.12 (dev channels).

**Comment by sethladd** [comment]
This issue was moved to dart-lang/pub#1310
