### ISSUE TITLE
starting observatory for web app in command line fails on OSX

### ISSUE THREAD

**Issue by tomaszkubacki** [dart-lang/sdk#24029]
Observatory seems starting twice. Observatory web app is not working properly and says:

"Disconnected from VM: Connection saw corrupt JSON message: FormatException: SyntaxError: Unexpected number 
[Connect to a VM]"

Same procedure (with different paths) works (though it's also starting twice) on Linux/64 (not tested on windows)

### steps to reproduce

1. generated new app with: stagehand web-simple
2. pub get
3. pub serve 
4. started observatory with:

 /usr/local/opt/dart/Chromium.app/Contents/MacOS/Chromium --DART_FLAGS="--steal_breakpoints --pause-isolates-on-start" http://localhost:8080

### expected result 
observatory start and print its URI - able to browse observatory web app

### actual results

[19274:1291:0809/183329:ERROR:renderer_main.cc(207)] Running without renderer sandbox
[19275:1291:0809/183329:ERROR:renderer_main.cc(207)] Running without renderer sandbox
Observatory listening on http://127.0.0.1:56065
Observatory listening on http://127.0.0.1:56068
[19279:1291:0809/183334:ERROR:renderer_main.cc(207)] Running without renderer sandbox
Observatory listening on http://127.0.0.1:56072
[19280:1291:0809/183336:ERROR:renderer_main.cc(207)] Running without renderer sandbox
Observatory listening on http://127.0.0.1:56078

Browsing observatory web app page states:
"Disconnected from VM: Connection saw corrupt JSON message: FormatException: SyntaxError: Unexpected number 
[Connect to a VM]"

Discussion started here:

Posted question here: https://groups.google.com/a/dartlang.org/forum/?hl=en&fromgroups#!topic/observatory-discuss/suJkqlCTKoM

**Comment by tomaszkubacki** [comment]
Added screenshot  
![obervatory_crash_osx](https://cloud.githubusercontent.com/assets/348532/9166386/a80ba3d0-3f52-11e5-9411-e6cd76e2a6f1.png)

**Comment by turnidge** [comment]
From John:

Hi,

An Observatory is hosted for each Dart VM instance. When starting up, Dartium opens multiple tabs, resulting in multiple VM instances. 

A simpler way to use Observatory with Dartium is:

1) Launch Dartium without any command line flags.
2) Navigate a tab to your Dart app.
3) Open up DevTools and you'll see the URL for the Observatory for this tab.

HTH,
John
