### ISSUE TITLE
debugger evaluation always null

### ISSUE THREAD

**Issue by maiermic** [dart-lang/sdk#24028]
I use [source_gen](https://pub.dartlang.org/packages/source_gen) package to generate code. If I run a _build.dart_ file (like [this](https://github.com/dart-lang/source_gen/blob/master/build.dart) one in the [source_gen repository](https://github.com/dart-lang/source_gen)) in debug mode and pause in `generateForAnnotatedElement` method of a `GeneratorForAnnotation` class (for example [JsonLiteralGenerator](http://www.dartdocs.org/documentation/source_gen/0.4.2/index.html#source_gen/source_gen-example-json_literal_generator.JsonLiteralGenerator) in [json_literal_generator.dart](https://github.com/dart-lang/source_gen/blob/master/lib/generators/json_literal_generator.dart)), I always get `null` as a result, if I evaluate an expression (for example `3 + 4`) in Intellij (Dart Plugin) or Observatory (debugger). If I pause in another context (for example in the function `_isConstType` in [json_literal_generator.dart](https://github.com/dart-lang/source_gen/blob/master/lib/generators/json_literal_generator.dart)), evaluation works as expected (`3 + 4` evaluates to `7`).

I use Dart-SDK 1.12.0-dev.5.1 on Windows 8.1.

**Comment by johnmccutchan** [comment]
@turnidge

**Comment by rmacnak-google** [comment]
Assumed stale.
