### ISSUE TITLE
Expose RegExp.isCaseSensitive and RegExp.isMultiLine via the VM Service Protocol

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24039]
Currently, the VM Service Protocol's `Instance` type can represent a `RegExp`, and it exposes the `RegExp`'s pattern. However, it doesn't expose its case-sensitivity or multi-line flags, which means the user doesn't have a complete picture of the actual semantics of the expression. Doing so would be more consistent.

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by nex3** [comment]
It looks like this was fixed by 3851c8c0eda48907649193d475737e87192eeee5. @rmacnak-google, don't forget to add a CHANGELOG entry!
