### ISSUE TITLE
Please merge revisions <see content> into dev channel

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24031]
@ricowind @whesse @kasperl

The requested CLs add flags to dart2js, so that users can use the startup-emitter.

Revisions:
3cbedb02e418ccbad3b865ba5bd2ee558de1c7ef
7e9fcbf5d6942ef14a287984ee72207469f34943
49daca25d0fe85ee47c88a959f0007b18e60d4f7
6377f1858726949354437381f596d82316c361dd

This merged cleanly

**Comment by whesse** [comment]
Merged in 1.12.0-dev.5.2
