### ISSUE TITLE
Issue with number of Samples in CPU profile in Observatory (Linux)

### ISSUE THREAD

**Issue by rajmaniar** [dart-lang/sdk#24033]
I'm using Observatory in Dart 1.11.3 (Linux VM) with the observatory port forwarded over SSH. 
The CPU profile in either view always shows a low number of samples: about ~200 samples (spanning 0s). On the osx VM this shows about 2 seconds of samples (so ~2000 samples).

The linux VM is started with these flags:
* ignore_unrecognized_flags  =  true //--Observe:9999
* pause_isolates_on_exit  =  true
* write_protect_code  =  false

**Comment by johnmccutchan** [comment]
Do you have a test program you're running?

**Comment by rajmaniar** [comment]
I’m running our app server which a long running process and we’re sending a fair amount of traffic to it.

I’m not sure if that answers your question… :-)

**Comment by johnmccutchan** [comment]
Please try Dart 1.13 and reopen with a reproduction case.
