### ISSUE TITLE
Support data: URIs.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24030]
Dart should have support for `data:` URIs, including full support for both base64 and percent-encoded data.

They should work with the Resource class, and there should be some way to parse them and get the content type and flags.

**Comment by sethladd** [comment]
You can use data: URIs to load an isolate via spawnUri, and I think it also works with `Resource`.

But there isn't a formal "data URI" class, which would make it easier to construct and parse them.

**Comment by rmacnak-google** [comment]
The VM supports only percent-encoded data uris because there is already support in the core libraries for percent encoding but not for base64.

**Comment by lrhn** [comment]
The `Uri` class now has extra support for data: URIs, including base64 encoding.
