### ISSUE TITLE
Observatory used with a command line app 

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#24041]
I have made some attempts to use the Observatory to explore the execution of a simple command line application, but the UI fails to start (so I cannot do anything with it at all).

Reference:
    This is basically a replay of the scenario described in the first few paragraphs of this page:
    https://www.dartlang.org/tools/observatory/get-started.html

Steps to reproduce:
    1. Create a tiny app, e.g., a file 'hello.dart' containing `main() { print("Hello, world!"); }`
    2. On a Linux command line, run `dart --observe --pause-isolates-on-start hello.dart`.
    3. On the same host, load 'http://localhost:8181/' in a browser (I'm using chrome 44.0.2403.130)

Expected behavior:
    I'd expect the browser to render a page containing information along with user interface elements like menus and buttons, similar to the screen dumps shown in the section 'Observatory UI' at the above-mentioned URL.

Observed behavior:
    The browser tab shows a short JSON text (no rendering, just the raw text): {"jsonrpc":"2.0", "error":{"code":-32601,"message":"Method not found","data":{"request":{"method":"","params":{}}}},"id":""}

Obviously, the JSON output looks like a failed method invocation (in the Observatory?), but it is not obvious to me why the things I'm doing would request something impossible, and it is also likely that the outcome in such a case could be more self-explanatory for the casual user.

PS: I realize that this looks like a wrong invocation scenario---lots of people are using the Observatory, and here we cannot even get it started with the simplest possible app---but I have made a number of requests for explanations and improvements, and so far nobody has pointed out anything obviously crazy with the steps I've taken to get the Observatory started. So what is going on here?!

**Comment by ricowind** [comment]
works fine for me

**Comment by ricowind** [comment]
I tried this on tot and on latest dev release

**Comment by eernstg** [comment]
Interesting! Here's my `dart --version`:
Dart VM version: 1.12.0-dev.5.0+google3-v1.12.0.dev.5.0 (google3) on "linux_x64"
I retried the experiment with a recently recompiled vm, and then it all works as expected:
Dart VM version: 1.12.0-edge.f9ea40f971ddad72b3e237de38bc7e523e415d14 (Tue Aug 11 10:25:00 2015) on "linux_ia32".

So the issue can be marked as resolved, unless it affects a lot of (potential) google3 users?

**Comment by turnidge** [comment]
Thanks for reporting the problem.  Going to close this unless I hear that it is still affecting people.
