### ISSUE TITLE
Please merge VM changes into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24040]
@ricowind @whesse @kasperl
- Avoids creating unmodifiable lists in List.from.
- Fixes and cleanups for tear-offs.
- Fixes for .packages handling.
- Fixes several usability issues in the Observatory.

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
1426ac4f77eb1669775baee49cee7ea5a79b7987 - Reuse constructor closures.
f73b8aa019adcc1a443ceb0f61953853130fa528 - Observatory: Debugger input focus.
e974b952a73dffa72ed1ea87f5f8cd85f8790782 - Fix List.from
223e5a6bb5877dd4c3c46cf1f097172c879e8424 - Fix C?.m
ee9c0cbb2c86935bab2a31c241ebbbe01466e9e0 - Fix --packages without package use
b6c979f20b01239e92e7acc3ad34b879d4d95b83 - ObjectMirror.delegate
227010d9dc84c2e5bf042ca1c0367f36eacbfa6b - Observatory: ordered isolate list
521dee763c95a374031e06572d3f56ceb8e8d91f - Fix canonicalization of type arguments (fixes pub crash)
38b9945cfd7cb2cc587df013d4d31ae028d99f6b - Observatory: library dependency
b34267d0d79d43bc343a26901f67a00a176f4bb8 - Keep privates private through mirrors
49a61ba3f53a135cd7ce6085fb0afc642c50d123 - Observatory: dismiss evaluation results
8cee9ac89d92f702950c27e2982177ea1da5560b - Modifiable double boxes when initializing with constant.
97a4ae8f9496b6740cff67b1664258b51c0a7f68 - Observatory: hot keys in the debugger
756763f3ca17737a464d8482303cebf068c7599d - Allow build on iOS
2b2d4cf1bf355648e218542e9c7d4641999fb5bc - Observatory: configurable allocation profile
447e497ac985d7f13dfb1ad2d98a5b1c2e8fc709 - Observatory: faster object graph
fc981a21c5b141aaf2526073988d7545ec851c16 - Always inline operators
5b6136fdfb0addf98abc52fff1c605a84bfd465c - Observatory: better set command in debugger
a5c0dbfffe58ab3a568b4928da3e6a3b79315262 - Observatory: Fix continue command
55b7315d8387268e43cac325106dd62b241b2c7f - Hide constructor closure functions
e61f1dc8ce48789166121364bcbc961f45dc38be - canonicalize objects in snapshot
256b044857a44977ba1b4ca58d3d96ab39765bdf - Observatory: allow stepping at paused start

Sample CL is https://codereview.chromium.org/1268353004
This merged cleanly

**Comment by whesse** [comment]
Merged in 1.12.0-dev.5.2
