### ISSUE TITLE
String.split should not trust Pattern argument

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#24043]
The following causes a crash:

class EvilMatch implements Match {
  int get start => 100000000;
  int get end =>   3;  
}       
      
class EvilIterator implements Iterator<EvilMatch> {
  bool moveNext() => true;
  EvilMatch get current => new EvilMatch();
}
  
class EvilIterable extends Iterable {
  Iterator<EvilMatch> get iterator => new EvilIterator();
}       
      
class EvilPattern {
  Iterable<EvilMatch> allMatches(String s) => new EvilIterable();
} 

void main() {
  print("foo".split(new EvilPattern())[0].length);
}

**Comment by sgmitrovic** [comment]
Fixed in 56c91201c32b
