### ISSUE TITLE
Termination delay with synchronous HttpClient() request

### ISSUE THREAD

**Issue by raphway** [dart-lang/sdk#24045]
The following code makes an HTTP request to `https://example.com` and waits for the request to be complete before continuing execution. However, at the end of execution, it keeps running for a few more seconds without doing anything (apparently) before it finally terminates. Adding `exit(0);` to the end of the `main()` function solves the issue, though.

#### Code: ####

    import 'dart:async';
    import 'dart:convert' show UTF8;
    import 'dart:io';
    
    Future main() async {
      await makeRequest();
      print('end of main');
      // exit(0); here solves the problem.
    }
    
    Future makeRequest() async {
      var request = await new HttpClient().postUrl(Uri.parse('https://example.com'));
      var response = await request.close();
      var contents = await response.transform(UTF8.decoder).join();
      print(contents);
    }

#### Expected output: ####

    // HTTP response...
    end of main

*(The app terminates immediately after printing the last line.)*

#### Actual output: ###

    // HTTP response...
    end of main
    // (Execution continues for a few seconds before terminating...)

*(The app keeps running for a few seconds after printing the last line before it finally terminates.)*

**Comment by sgjesse** [comment]
This is caused by the HttpClient instance having a connection pool which can keep the Dart VM alive. There are two ways of avoiding this:

1. Close the HttpClient explicitly
2. Use non-persistent connections

```
import 'dart:async';
import 'dart:convert' show UTF8;
import 'dart:io';

Future main() async {
  await makeRequest();
  print('end of main');
}

Future makeRequest() async {
  var client = new HttpClient();
  var request = await client.postUrl(Uri.parse('https://example.com'));
  var response = await request.close();
  var contents = await response.transform(UTF8.decoder).join();
  print(contents);
  client.close();  // Close the client.
}
```

```
import 'dart:async';
import 'dart:convert' show UTF8;
import 'dart:io';

Future main() async {
  await makeRequest();
  print('end of main');
}

Future makeRequest() async {
  var request = await new HttpClient().postUrl(Uri.parse('https://example.com'));
  request.persistentConnection = false;  // Use non-persistent connection.
  var response = await request.close();
  var contents = await response.transform(UTF8.decoder).join();
  print(contents);
}
```

**Comment by raphway** [comment]
Thanks @sgjesse, it solved the issue. And after you mentioned the closing of connections, I went to check the documentation for `HttpClient` and there is even a section under the title 'Closing the HttpClient' that explains this behaviour. My bad for not reading it...
