### ISSUE TITLE
Pub should be able to read `--no-package-symlinks` from an environment variable 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24046]
I usually use `pub get`\`pub upgrade` from command line and find the argument quite cumbersome to use.  I'd prefer setting `export pub_options=--no-package-symlinks` and be sure it is applied everywhere.

**Comment by sethladd** [comment]
:) I just emailed about that exact question.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/pub#1311
