### ISSUE TITLE
Error repeated on stder although isolate has error listener installed

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#24052]
Consider the program below. When run with -DareErrorsFatal=true, this message is printed on stderr:

```
in ShutdownIsolate: 'file:///.../isolate.dart': error: line 42 pos 7: type name expected
  new new();
      ^

```

As I have installed an error handler on the isolate, I expect no message is printed.

These messages are confusing when running tests that are expected to fail, as these additional error messages may lead people to investigate the wrong problem.

The work around I have found so far is to not set errors to fatal. Unfortunately, this means that a broken program may continue and potentially cause real harm as invariants may be broken.

```
import 'dart:isolate';

const bool areErrorsFatal = const bool.fromEnvironment("areErrorsFatal");

main() async {
  Isolate isolate;
  ReceivePort exitPort = new ReceivePort();
  ReceivePort errorPort = new ReceivePort();

  exitPort.listen((_) {
    print("Isolate exited");
    exitPort.close();
    errorPort.close();
  });

  errorPort.listen((List message) {
    var error = message[0];
    var stackTrace = message[1];
    print("Error in isolate: $error");
    if (stackTrace != null) {
      print(stackTrace);
    }
    if (!areErrorsFatal) {
      print("Killing isolate");
      isolate.kill();
    }
  });

  isolate = await Isolate.spawn(entryPoint, null, paused: true);

  isolate.setErrorsFatal(areErrorsFatal);
  isolate.addOnExitListener(exitPort.sendPort);
  isolate.addErrorListener(errorPort.sendPort);
  ReceivePort ping = new ReceivePort();
  isolate.ping(ping.sendPort);
  await ping.first;

  isolate.resume(isolate.pauseCapability);
}

entryPoint(_) {
  new new();
}
```

**Comment by peter-ahe-google** [comment]
@lrhn @sgjesse

**Comment by lrhn** [comment]
I agree that printing an uncaught error should be the last fallback if nothing in the program handles the error, and an error listener on an isolate should be considered handling it.

**Comment by lrhn** [comment]
Should be fixed now.
