### ISSUE TITLE
SDK 1.12 breaks Dartium running Dart extensions

### ISSUE THREAD

**Issue by travissanderson-wf** [dart-lang/sdk#24056]
My version of Dartium might be behind, but when I clear out all my symlink packages directories I can no longer run my extension in Dart.  Switching back to 1.11 / running without clear symlinks works.

**Comment by sethladd** [comment]
Thanks for the report.

How did you clear out all the symlinks? Do you mean, using the `--no-package-symlinks` ?

Also, what do you mean "my extension" ?

**Comment by travissanderson-wf** [comment]
Yep, using `--no-package-symlinks`.  I have a Chrome extension written in Dart that I load "unpacked" locally from the `my_extension/web/` directory.
