### ISSUE TITLE
pub get timeout

### ISSUE THREAD

**Issue by tonygentilcore** [dart-lang/sdk#24050]
The `sky_engine` package is fairly large. I frequently hit this error when trying to get it (and have heard other developers report the same):
```
$ pub get
Resolving dependencies... (2.2s) 
Downloading sky_engine 0.0.8...
Timed out after 30.0s while downloading https://pub.dartlang.org/packages/sky_engine/versions/0.0.8.tar.gz.
This is likely a transient error. Please try again later.
package:pub/src/io.dart 859  timeout.<fn>
This is an unexpected error. Please run

    pub --trace get

and include the results in a bug report on http://dartbug.com/new.

$ pub version
Pub 1.12.0-dev.3.1
```

While that runs, I can see in my ActivityMonitor that the `dart` process is receiving data from the network. But the 30s timeout doesn't appear to be long enough to get the whole thing. Would it be possible to do something like not timeout if data is still coming in, provide a longer default timeout, or make the timeout configurable?

/cc @alhaad @abarth

**Comment by sethladd** [comment]
Can you update to the latest SDK? That timeout should have been removed. I unfortunately don't remember the exact date we removed the timeout, but the latest dev channel should work for you.

**Comment by tonygentilcore** [comment]
ps. my full `pub --trace get` log doesn't appear safe for a public bug. If any googlers want it, send me an email.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/pub#1312
