### ISSUE TITLE
Download a Dart SDK instead of a checked-in Dart binary, for testing and observatory build

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24053]
To simplify the observatory build process, and make it more stable, we should use a checked-in SDK (stored in cloud storage, using depot_tools/download_from_cloud_storage in DEPS) to build observatory.  This would replace the checked-in binaries used by the test scripts, in tools/testing/bin with an SDK in tools/sdks.

Currenly blocked on support for downloading and unzipping .tar.gz files being relanded in depot_tools.
We would also want to build SDKs for MIPS and ARM.

@johnmccutchan @iposva-google @ricowind @whesse

**Comment by ricowind** [comment]
depot tools support for tar.gz landed last week

**Comment by whesse** [comment]
A CL for this is at https://codereview.chromium.org/1322753005

**Comment by whesse** [comment]
The SDK is now downloaded by the bots, and observatory build should start using it.  I will open a different issue, to move the test.py scripts to start using the SDK instead of testing/bin, and to remove testing/bin.
