### ISSUE TITLE
dart2js: CPS backend crashes because it doesn't always close over type variables

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#24064]
@asgerf do you want to take this one?

Standalone test case:

```dart
class A<T> {
  A() {
    [].forEach((T x) {});
  }
}

main() {
  new A();
  print(true.runtimeType);
}
```

The use of runtimeType means that the closure class for `(T x) {}` thinks it should have a field for T, but there is no T in scope in the constructor A().

**Comment by asgerf** [comment]
https://codereview.chromium.org/1286113003/
