### ISSUE TITLE
Style guide: how are labels formatted and indented?

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#24066]
I guess people don't use labels much, because the style guide doesn't seem to mention them.  I think it should give some guidance on the naming.  Is it `littleCamelCase:` or `BigCamelCase:` or `SHOUTING_CASE:`?

We might also suggest an indentation style, perhaps one of:

```dart
label: for (...
```

```dart
label:
for (...
```

```dart
label:
  for (...
```

**Comment by munificent** [comment]
I don't think I've ever seen labels used in real Dart code. You can probably infer how to style them from the rules for `switch` cases, since those are basically the same.

**Comment by kevmoo** [comment]
Where are we calling home for these types of bugs? `dart_style`? The web site?

**Comment by kmillikin** [comment]
OK, I suggest that they be formatted with lowerCamelCase.  The reason is that their scoping rules are similar to variables.

I prefer the second indentation I suggested above (label on a line by itself, aligned with the beginning of the labeled statement) because the first looks jagged when long descriptive label names are used and the third shows a false level of nesting.

I guess leaving the style guide silent on labels allows me to format them the way I want anyway.  And as @munificent points out there's little danger I'll have to read anyone else's labels....  Reopen if you actually want to change it.

**Comment by munificent** [comment]
> Where are we calling home for these types of bugs? dart_style? The web site?

Style guide bugs go [here](https://github.com/dart-lang/www.dartlang.org/issues?q=is%3Aopen+is%3Aissue+label%3AStyleGuide).

> OK, I suggest that they be formatted with lowerCamelCase. The reason is that their scoping rules are similar to variables.

Yup. The style guide says, unless some other style guide rule overrides it, that all identifiers are lowerCamelCase.

> I guess leaving the style guide silent on labels allows me to format them the way I want anyway.

Works for me.
