### ISSUE TITLE
Invalid annotation @Returns on Node.childNodes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#24076]
The following program gives the error `Internal error: 'dart:html': malformed type: line 24469: type 'Returns' is not loaded @ Returns("NodeList")`:

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="application/dart">
      import 'dart:html';
      import 'dart:mirrors';

      main() {
        ClassMirror clazz = reflectType(Node);
        clazz.declarations[#childNodes].metadata;
      }
    </script>
  </head>
</html>
```

This only appears if you actually try and access the metadata, since its not actually created until that time.

**Comment by jakemac53** [comment]
I think @Creates might also be invalid as I don't get a jump to definition option in intellij

**Comment by alan-knight** [comment]
Those are defined in dart:_js_helper, which is imported in the dart2js version of dart:html, but not in the Dartium version. They could probably be moved to dart:html_common.

**Comment by alan-knight** [comment]
Fixed in https://codereview.chromium.org//1290263002

As it stands, this wouldn't be in 1.12. Is it important to try and get this cherry-picked?

**Comment by jakemac53** [comment]
Doesn't need to get cherry-picked, am working around it currently.
