### ISSUE TITLE
Analyzer: When multiple imports provide the same symbol, one import should be marked as "unused"

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#24073]
e.g. In Angular, the `package:angular/angular.dart` file exports `package:di/di.dart`.

In the following file, the `Module` symbol is coming from di.dart, but also exported through angular.

```
import package:angular/angular.dart
import package:di/di.dart

class MyModule extends Module { ... }
```

Currently, the analyzer does not give any hints about unused imports. 

However, I would expect angular.dart to be flagged as "unused". angular.dart is not used since `Module` is also available through di.dart.

**Comment by srawlins** [comment]
Even a subset of this, examining just shown names would be useful. I found some code with:

```dart
import 'package:a/a.dart';
import 'package:a/src/foo.dart' show foo;
```

because at one point, `a.dart` did not export `foo`. But now it does, so the second import is unnecessary. Not sure if one is easier to implement or faster to run than the other...

**Comment by srawlins** [comment]
I'll close this in favor of the issue I've been referencing when landing changes. https://github.com/dart-lang/sdk/issues/44569
