### ISSUE TITLE
DebugSIMARM64 (no bot) failing vm/cc/Int8ListLengthMaxElements and vm/cc/LargeMap

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24079]
Simulator hit unaligned read

**Comment by fsc8000** [comment]
@zanderso: Is this a duplicate of #23953 or #22151?

**Comment by zanderso** [comment]
This appears to be a different bug. At least with Int8ListLengthMaxElements, an argument descriptor array is missing a heap object tag, and applying a field offset results in an unaligned read. So, nothing to do with typed data. I'll investigate more.

**Comment by fsc8000** [comment]
@whesse, @zanderso  Maybe we should run debug-arm64 tests on the buildbot to catch things like this early. What was the reason for not running this configuration?
