### ISSUE TITLE
Please merge Observatory revisions into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24075]
@ricowind @whesse @kasperl

cc @johnmccutchan @rmacnak-google 

Observatory UI cleanups for 1.12.

Revisions:
fbe47ffa538a99c388d455abe023ad975344fbb3 - Test cleanups (prevents conflicts)
d0f216eb30f764470cca62413938f7cc4192c8ed - Prevent warning message in Dartium.
5979d9341eeaf37c1b7e5bf26598c4e0266df921 - Demangle library names.
62dbce855558492323b8f0344ddff59f07f4ff11 - Update library annotations.
919f79e0449a49f35c1d466a28b3e19e779a8586 - Fix links to script and line.
10de20f2307cfc96cba12a47343bae4ddfb61418 - Remove load graph from isolate.
82b4f03dec5cbe98aa3510d88dd11e07b8164acb - Avoid exception when refreshing profile from isolate page.
f9944c1c4c31f528a64cdce2c0ca2b28df5954db - Sync isolate drop down menu with summary page.
8e91f1a7c3d6a41ea17c4527059de944ac86b2b5 - Fix heap map display.
7af879a084aa5d9c90666e634e7dfbc60dfc92cb - Fix time span in profiler.
2ecf40450c43ef91f9e73d324267c7d9dd8a9a4b - Only show link for Dart functions.
cacacfa64549b4b275f3877ac12e86f98b049f3c - Hide empty CPU profile on class page.
3dd39ef37cb8529af55201f8bc72e613ba6acaf2 - Fix CPU profile table.
71d7d7a4de18e2ff63d6f8e78fc307f5f7001ba8 - Fix CPU profile table for native functions.

This merged cleanly

**Comment by whesse** [comment]
Merged to 1.12.0-dev.5.4
