### ISSUE TITLE
Please merge VM crash fix into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24089]
@ricowind @whesse @kasperl

cc @johnmccutchan 
This fixes a crasher when requesting an allocation profiles for VM internal objects such as Context.

Revisions
ec675a3b0d2e3267631c58cfae3568af28aa693c
22a1159f4b080a206e21e106a6aa5395cab9b65e

This merged cleanly

**Comment by whesse** [comment]
Merged to 1.12.0-dev.5.4
