### ISSUE TITLE
MIPS build is broken

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#24081]
It looks like it might be caused by the inline assembly:
# define COPY_FP_REGISTER(fp) asm volatile ("move %0, %%r30" : "=r" (fp) );

from:

https://github.com/dart-lang/sdk/commit/a1798f7e456dc921e14329faa7ecccca939ef644

@johnmccutchan

**Comment by zanderso** [comment]
@iposva-google @ricowind can we have the buildbot send email when the MIPS build fails?

**Comment by ricowind** [comment]
@whesse worked on getting mips cross compilation up and running at some point, don't know the status on that (our mips boards are on the fyi waterfall atm)

**Comment by whesse** [comment]
Yes, we can get the buildbot to send email to a list of addresses, and also to the relevant committers, when a build fails.  The mips bots are currently compiling on the mips boards themselves in a Debian chroot - we want to move this to cross compilation, using the same compilers and OS that the fiber team uses.

**Comment by zanderso** [comment]
The build is fixed and tests are passing. @whesse would it be possible to email me + committers when the build breaks, and committers when tests fail? I'll leave this issue open and assign to you to track. Thanks!

**Comment by whesse** [comment]
The mips bots take such a long time to run, that any mails to committers would be mails to 20 or 30 people.  There have also been some flaky test failures.  I would suggest just adding zanderso to the list of failure notificatees instead.  We have not really had trouble with new tests or changes failing only on mips - all the mips specific errors have been vm changes.  I think tracking down the cause of a real, persistent failure is more productive than notifying everyone on every failure.

**Comment by zanderso** [comment]
sgtm if I can be notified only when the build fails, and not for every test failure.

**Comment by rmacnak-google** [comment]
MIPS is no longer supported.
