### ISSUE TITLE
Pub hangs and is unkillable on windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24086]
The pub get command that is run for each package, is slow, and timing out.  All of these pub get commands are remaining alive, and slow down the system, making all future ones time out too.  We get about 50 unkillable pub processes running.

**Comment by whesse** [comment]
The same is also happening on the regular windows bot for pub and package tests.

**Comment by whesse** [comment]
This is now the master bug for tracking work on this issue.

The unkillable hung pub process shows up as doing 200 MB/s of "other" I/O, which is not read or write, but something like stat.

These flakily hanging pub processes are a big problem on the buildbot, and we have now switched to automatically rebooting all windows slaves that run pub, after each build.

@nex3 @munificent @ricowind @sgjesse

**Comment by nex3** [comment]
I can't think of any stats `pub get` would do—nor indeed any I/O operations other than HTTP GETs, file reads and writes, and invoking Git if there's a git dependency to be downloaded.

**Comment by whesse** [comment]
tools/task_kill.py has now been modified not to report failure on Windows when killing Dart.  This change should be reverted when this issue is fixed.  https://codereview.chromium.org/1582773002

**Comment by whesse** [comment]
This should have disappeared when we stopped using the package roots and symbolic links, but it looks like we got a hanging, unkillable pub process after that point too (but very rarely).  I couldn't log in to see the process details, but I restarted, and next time it happens, I may be able to log in and debug it.

**Comment by natebosch** [comment]
Have we had any further issues with this?

**Comment by athomas** [comment]
I have not seen this ever, so I'm tentatively closing this.
