### ISSUE TITLE
Could pub tool support system proxy setting?

### ISSUE THREAD

**Issue by taozuhong** [dart-lang/sdk#24080]
I have set the proxy for my machine, but dart can't read it, could pub tool support system proxy setting?

![image](https://cloud.githubusercontent.com/assets/13451009/9265809/f7a6b8ec-426a-11e5-87fd-bb9e1f6399ce.png)

''when run the pub tool (set proxy by manual),it will return the result as follow pictures:''
![image](https://cloud.githubusercontent.com/assets/13451009/9265836/60f9bc54-426b-11e5-93ee-9f8ed0abadba.png)

![image](https://cloud.githubusercontent.com/assets/13451009/9265841/71addce2-426b-11e5-9b26-a3ca2833d849.png)

**Comment by zoechi** [comment]
Current support is by using environment variables:  
- https://www.dartlang.org/tools/editor/troubleshoot.html#pub-get-firewall
- http://stackoverflow.com/questions/24021315/network-connection-proxies-in-dart-editor

**Comment by taozuhong** [comment]
I know and have used the environment variables HTTP_PROXY/HTTPS_PROXY,but system setting are more flexable, so I hope pub command tool can support it .

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/pub#1317

**Comment by nex3** [comment]
Pub doesn't explicitly deal with any network configuration at all. This is an issue for `dart:io`.

**Comment by sgjesse** [comment]
For more information see https://github.com/dart-lang/sdk/issues/5454 which have a long discussion on proxy configuration, here is a copy of one of the comments on supporting automatic proxy configuration:

We cannot support automatic configuration script (.pac) directly in Dart. A .pac is a JavaScript script intended for running in a browser. When a .pac script is used the .pac function FindProxyForURL is called and the returned string is then interpreted by the browser, e.g.:

function FindProxyForURL(url, host)
{
  return "PROXY proxy.example.com:8080; DIRECT";
}

The string returned by HttpClient.findProxy callback uses the same format as .pac scripts.

There are several standalone .pac evaluators out there, one is https://code.google.com/p/pacparser/. If you use that with the following Python script you should get the string to be used in line 7.

import pacparser
pacparser.init()
pacparser.parse_pac_file('wpad.dat')
print pacparser.find_proxy('http://pub.dartlang.org', 'pub.dartlang.org')
pacparser.cleanup()
