### ISSUE TITLE
How to use * (not multiply) operator overload?

### ISSUE THREAD

**Issue by acterhd** [dart-lang/sdk#24098]
Hello. How to I can for pseudo pointers make setter and getter operator like this?

```
var some = *ptr; //getter
*ptr = another; //setter
```

**Comment by mezoni** [comment]
One possible way is to change file name extension from `.dart` to `.c`
After that they (dereference operators) should work.

**Comment by acterhd** [comment]
I want this operator overload.

**Comment by lrhn** [comment]
There are two overloadable unary prefix opearators: `-` and `~`. If you can use those instead, 

Is the syntax really that important, or do you just want a simple way to get a wrapper around a variable?

**Comment by floitschG** [comment]
In some cases getters and setters might also work. (Especially in a static context).

There are no plans on adding unary *,+ or / operators. Closing.
