### ISSUE TITLE
Request: testing package_config on the packagebots

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24092]
cc @pq 

We'd like to ask that the package_config repo be set up to be tested on our packagebots.

https://github.com/dart-lang/package_config

Thanks!

**Comment by sethladd** [comment]
cc @whesse is this something you can help with? Thanks!

cc @hterkelsen for FYI

**Comment by whesse** [comment]
This is one of my goals for this week, to get it running.  A run that uses .packages, and no /package directory.

**Comment by pq** [comment]
Clarifying question: do you want this to run in the packagebot waterfall, in `pkg_tested`, or both?

**Comment by mit-mit** [comment]
@sethladd, are there any concrete test cases you have in mind?

**Comment by whesse** [comment]
Ok, my comment about "goals for this week" was not about this issue.  That comment was about making all bots on the package waterfall run using the .package file and no packages/ directory.

On this issue, I will add the package_config package to the package waterfall.  I think this particular package would also benefit from being added to the package testing bots on the main waterfall.  We added code to support the fact that all users will need to manually delete third_party/pkg/package_config, when we move it to third_party/pkg_tested/package_config, so now we are ready to do this move.

**Comment by mit-mit** [comment]
Isn't that #24093? We actually don't think that is required in 1.12. We have to make sure that the .package generation works in 1.12, but we are not guranteering that the whole tool chain works without a packaged dir until 1.13. see #24112

**Comment by whesse** [comment]
OK, continuing discussion about testing of .package on #24093.  On this issue, we will add package_config to both the package waterfall and to package testing bots on the main waterfall.

**Comment by sethladd** [comment]
Thanks @whesse !
