### ISSUE TITLE
Merge the latest pub to dev

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24094]
The commit 7c06881680ee07274f4fb2dffafeb019bf882e0f needs to be be merged into stable. It contains two major pub features slated for 1.12: support for the `Resource` API in `pub run` and `pub global run`, and removal of implicit `pub get` calls.
[edit whesse]
also merge
57bf18c3f808df096fc4a3720228e321a0dd7c13
and
65834295d999484aa68a6bffefce2e235e03fb56
[end edit]

**Comment by whesse** [comment]
I think we want to merge this to dev - dev is the channel that 1.12 is on, and where 1.12 stable will come from.  Stable is the channel with 1.11 on, that we are only merging major bug fixes to.

If you want to also merge to stable 1.11, after we merge this to dev 1.12, please file another mergeToStable bug.  Changing this to MergeToDev.

**Comment by mit-mit** [comment]
Yes, this should go via Dev not via Stable.

**Comment by sethladd** [comment]
Thanks @nex3 !

**Comment by whesse** [comment]
Also the two commits
57bf18c3f808df096fc4a3720228e321a0dd7c13
and
65834295d999484aa68a6bffefce2e235e03fb56
should be merged with this.  They fix a test which was broken by the pub update.

**Comment by whesse** [comment]
Merged to 1.12.0-dev.5.5.
