### ISSUE TITLE
Analyzer: Error when passing a function to Typed Class

### ISSUE THREAD

**Issue by luisvt** [dart-lang/sdk#24101]
When creating next class:

sample: https://dartpad.dartlang.org/845dbcc2820fa88422cf

```dart
class Person {
  String name;
  int age;
}

class From<T> {
  
  From(bool fun(T t)) {
    print(fun);
    
    //print((reflect(fun) as ClosureMirror).function.source);
  }
}

void main() {
  Person p1 = new Person()..name = 'my name';
  
  print(p1?.name ?? "hello");
  
  //closure code is not correctly analized.
  new From<Person>((p) => p.name == 'luis' && p.age > 21);
}
```

It should shows me the attributes of p highlighted and also let me auto-complete those attributes.

If I use a method and call it with single point it works correctly:

https://dartpad.dartlang.org/c54cbcbc1a7abc0f029d

```dart
import 'dart:mirrors';

class Person {
  String name;
  int age;
}

class From<T> {
  
  where(bool fun(T t)) {
    print(fun);
    
    //print((reflect(fun) as ClosureMirror).function.source);
  }
}

void main() {
  Person p1 = new Person()..name = 'my name';
  
  print(p1?.name ?? "hello");
  
  new From<Person>().where((p) => p.name == 'luis' && p.age > 21);
}
```

However, if I use double period when calling `where` it stop working

```dart
// No highlighted code and no auto-complete
new From<Person>()..where((p) => p.name == 'luis' && p.age > 21);
```

**Comment by zoechi** [comment]
There line that should demonstrate the problem doesn't have the "double period". Can you please "correct" the code so it correctly demonstrates the problem?

**Comment by luisvt** [comment]
code corrected.

**Comment by danrubel** [comment]
I believe this has been fixed. Please reopen if you see this problem re-occur.
