### ISSUE TITLE
VM: Flaky service test service/async_next_test on Win64

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24105]
@johnmccutchan @rmacnak-google 

Have you seen this one failing before?

=== Failure summary:

FAILED: none-vm release_x64 service/async_next_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
*\* Launching build\ReleaseX64\dart.exe --error_on_bad_type --error_on_bad_override --verbose_debug --ignore-unrecognized-flags --package-root=build/ReleaseX64/packages/ --enable-vm-service:0 E:\b\build\slave\vm-win64-release-be\build\sdk\runtime\observatory\tests\service\async_next_test.dart --testee-mode
Observatory listening on http://127.0.0.1:60051
*\* Signaled to run test queries on 60051

> > > single step break at file:///E:/b/build/slave/vm-win64-release-be/build/sdk/runtime/observatory/tests/service/async_next_test.dart:14 (func <doAsync_async_body> token 44)
> > > Running async_next_test.dart [1/9]
> > > Breakpoint reached
> > > Running async_next_test.dart [2/9]
> > > Checking we are at line 14
> > > Running async_next_test.dart [3/9]
> > > Resolved BP for function 'file:///E:/b/build/slave/vm-win64-release-be/build/sdk/runtime/observatory/tests/service/async_next_test.dart_::_doAsync_<doAsync_async_body>' at line 12
> > > hit user breakpoint at file:///E:/b/build/slave/vm-win64-release-be/build/sdk/runtime/observatory/tests/service/async_next_test.dart:12 (token 26) (address 0x3bef6ef)
> > > Running async_next_test.dart [4/9]
> > > single step break at file:///E:/b/build/slave/vm-win64-release-be/build/sdk/runtime/observatory/tests/service/async_next_test.dart:15 (func <doAsync_async_body> token 51)
> > > Event: ServiceEvent(owner='isolates/172217569', kind='PauseBreakpoint')
> > > Breakpoint reached
> > > Running async_next_test.dart [5/9]
> > > Checking we are at line 15
> > > Running async_next_test.dart [6/9]
> > > *\* Killing script
> > > Unexpected exception in service tests: Exception: No async continuation available null

stderr:
Unhandled exception:
Uncaught Error: Exception: No async continuation available
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: set DART_CONFIGURATION=ReleaseX64 & build\ReleaseX64\dart.exe --error_on_bad_type --error_on_bad_override --verbose_debug --ignore-unrecognized-flags --package-root=build/ReleaseX64/packages/ E:\b\build\slave\vm-win64-release-be\build\sdk\runtime\observatory\tests\service\async_next_test.dart
Took 0:00:01.717000

Short reproduction command (experimental):
    python tools/test.py -mrelease -ax64 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t60 service/async_next_test
# 
# === 1 test failed

**Comment by johnmccutchan** [comment]
FYI- @turnidge 

The service tests started flaking last week. Will investigate this week.

Thanks,
John
