### ISSUE TITLE
Web animations not working in dart, only js

### ISSUE THREAD

**Issue by luna-duclos** [dart-lang/sdk#24104]
When using the web-animations-js polyfill and compiling dart code to javascript, all animation code works as expected in all browsers (tested on chrome, firefox, Opera, dartium)

However, when not using dart2js but instead running dart code directly in dartium, an exception occurs:

```
Exception: Unsupported operation: [info: e:\b\build\slave\dartium-win-full-dev\build\src\third_party\webkit\source\bindings\core\dart\custom\dartelementcustom.cpp:100]
border.dart:92 CoilBorderElement.attached
package:template_binding/src/template_iterator.dart:389 _TemplateIterator@905045800._insertInstanceAt@905045800
package:template_binding/src/template_iterator.dart:480 _TemplateIterator@905045800._handleSplices@905045800
package:template_binding/src/template_iterator.dart:358 _TemplateIterator@905045800._valueChanged@905045800
package:template_binding/src/template_iterator.dart:331 _TemplateIterator@905045800._updateValue@905045800
package:template_binding/src/template_iterator.dart:326 _TemplateIterator@905045800._updateIteratedValue@905045800
package:polymer_expressions/polymer_expressions.dart:302 _Binding@528331630._convertAndCheck@528331630
package:observe/src/dirty_check.dart:120 <anonymous closure>
package:observe/src/dirty_check.dart:111 <anonymous closure>
package:observe/src/dirty_check.dart:111 <anonymous closure>
```

I suspect the same fix that was applied in dart2js needs to be applied somewhere else as well, as this DOES work in Dartium when using dart2js, just not when running in pure dart.

**Comment by PSG-Luna** [comment]
The dart2js part of this seems to have been fixed in #18202

**Comment by alan-knight** [comment]
I don't think it's the same fix. The Dartium error is that a function animateCallback has not bee implemented.

Do you have a simple example that fails?

**Comment by PSG-Luna** [comment]
Only a complex application at the moment, I'll give a stab at a simple example tomorrow
