### ISSUE TITLE
Pub build requires a .package file, even if /packages exists

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24103]
Even if all the required packages are present, in a /packages directory, pub build fails, saying a .packages file is required.  This means that previous versions of pub are not compatible with the new version.

@nex3

**Comment by mit-mit** [comment]
@sethladd, @nex3, is this by-design? Users should be able to just run `pub get` first, right?

**Comment by sethladd** [comment]
> Users should be able to just run pub get first, right?

Right. I feel this is reasonable, as `pub get` shouldn't change the versions you are depending on.

This might make for a good item in the CHANGELOG and/or NOTES for this release.

**Comment by munificent** [comment]
Yup, @nex3 documented the change in the commit that brings pub into the SDK: https://github.com/dart-lang/sdk/commit/7c06881680ee07274f4fb2dffafeb019bf882e0f.

**Comment by sethladd** [comment]
On :fire: !! :)
