### ISSUE TITLE
New pub version breaks tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24102]
The new version of pub breaks existing tests, because it requires a .pubspec.lock file and a .packages file to run pub build.

The test dart2js/source_map_pub_build_validity_test copies the sunflower sample to a new directory and runs pub build on it.

The new version of pub fails with an error, saying pub get must be run first.

Also, if pub get has been run, from a prior version of pub, pub build fails and says a .packages file must be present.

buildbot failure:
http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-2-5-be/builds/11761/steps/dart2js_unit-vm%20tests%20--checked%20failures/logs/stdio

@nex3

**Comment by whesse** [comment]
In this case, there is a package required by the pubspec.yaml, the browser package.  But if no package is required, and there is only an SDK constraint in the pubspec, the same error is reported.

It should not be required to run pub get on a package that has no dependencies, I think.  Filing separate issue for this.

**Comment by whesse** [comment]
OK, I see from the changelog that this is working as intended.  The test needs to be fixed, then, to accommodate this breaking change.

**Comment by sethladd** [comment]
@whesse thanks for noticing!

It sounds like this is an issue with a dart2js test... should we move the Area ? I might have read it wrong, though.

**Comment by whesse** [comment]
This will be fixed with https://codereview.chromium.org/1295653005/
This should be merged in with the merge that updates pub.
