### ISSUE TITLE
Confusing error message if JS was also compiled manually, after pub build

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24108]
If I have an index.html that refers to main.dart, and at some point for debugging purposes I just ran dart2js manually and named the output main.dart.js, then if I later try to run pub build, I get the error

Build error:
Transforms {Dart2JS on BasicWeb|web/main.dart} all emitted asset BasicWeb|web/main.dart.js.

which is not very clear.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/pub#1315
