### ISSUE TITLE
dartanalyzer can't resolve package: URIs unless it's in the dir of the project

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24116]
Consider this case:
- create a dummy project (via `stagehand package-simple`)
- pub get
- cd to your home directory
- run `dartanalyzer path/to/dummy/project/bin/main.dart`

Expected: analysis to work

Actual:

```
~ $ dartanalyzer ~/tmp/testpkg/bin/main.dart 
Analyzing [/Users/sethladd/tmp/testpkg/bin/main.dart]...
[error] Target of URI does not exist: 'package:testpkg/testpkg.dart' (/Users/sethladd/tmp/testpkg/bin/main.dart, line 4, col 8)
[warning] Undefined name 'testpkg' (/Users/sethladd/tmp/testpkg/bin/main.dart, line 4, col 42)
[warning] Undefined name 'testpkg' (/Users/sethladd/tmp/testpkg/bin/main.dart, line 8, col 25)
1 error and 2 warnings found.
```

If I cd into my dummy project, I can analyze:

```
~ $ cd tmp/testpkg/
~/tmp/testpkg $ dartanalyzer bin/main.dart 
Analyzing [bin/main.dart]...
No issues found
```

FWIW the VM runs the code from an arbitrary directory

```
~ $ dart ~/tmp/testpkg/bin/main.dart 
Hello world: 42!
```

**Comment by sethladd** [comment]
cc @pq

**Comment by pq** [comment]
After chatting with @stereotype441 at length yesterday, I'm pretty convinced that getting this right depends on solving the larger issue of proper context creation for enumerated files (https://github.com/dart-lang/analyzer_cli/issues/53) which is gated by the much discussed `ContextManager` rework (https://github.com/dart-lang/sdk/issues/24133).

**Comment by hir3npatel** [comment]
How would one work around this with the sublime text 3 dart plugin? Even if I launch sublime from the directory of the project, I get the "target of uri does not exist" error. Doing an analysis via cli command in the project dir works fine.

**Comment by hir3npatel** [comment]
Oops, turns out I did a pub get as root, but am using sublime as a user, so the files in .pub-cache had permissions preventing the normal user from accessing package files. A chown of those files to the user has fixed the errors for sublime. Sorry for the noise.

**Comment by srawlins** [comment]
This is either solved, or just not a context we plan to support.
