### ISSUE TITLE
Dart API should use an embedder-provided memory allocator

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#24110]
The VM should only pass ownership of memory to the embedder when that memory was allocated with a function provided by the embedder. That is, we can't return a pointer from an API call to memory the embedder might not know how to deallocate.

**Comment by kodandersson** [comment]
I'm all for supporting an embedder-provided allocator, but why couldn't this issue also be solved by providing a Dart_Delete call that frees the allocation we performed (without relying on the VM being initialized)?
