### ISSUE TITLE
Test is failing in package_config

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24113]
This is a tracking bug for 
https://github.com/dart-lang/package_config/issues/29

A test in this package is failing, and is now turning the main Dart waterfall red.  This needs to be fixed immediately.  This cannot be fixed by a status update because the package uses package:test.

@pq @sethladd @lrhn

**Comment by pq** [comment]
@lrhn has a CL to address this here: 

https://codereview.chromium.org/1303483002/

@whesse: let me know if you want me to land it.

**Comment by whesse** [comment]
Yes, please land it.  Thanks.

On Tue, Aug 18, 2015 at 5:36 PM, Phil Quitslund <notifications@github.com>
wrote:

> @lrhn <https://github.com/lrhn> has a CL to address this here:
>
> https://codereview.chromium.org/1303483002/
>
> @whesse <https://github.com/whesse>: let me know if you want me to land
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24113#issuecomment-132252545>.
>



-- 
William Hesse

**Comment by pq** [comment]
PR here: https://github.com/dart-lang/package_config/pull/31.  PTAL!

**Comment by whesse** [comment]
This was not actually a milestone 1.12 bug, because an earlier version of package_config is in 1.12.
I will discuss whether any later fixes to package_config need to go into Dart 1.12, and file a merge bug if needed.
