### ISSUE TITLE
Possible VM Memory Leak

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#24129]
We have found a possible memory leak in the Dart VM. I have created a ZIP file with the stuff needed to reproduce this issue.

ZIP file: http://files.directcode.io/dart-leak-broker.zip

Steps:
1. Download and extract the ZIP file.
2. Run `dart --observe broker.dart`
3. Run `dart responder.dart`
4. Run `dart requester.dart`

You will need to run these commands in 3 terminal sessions at the same time.

If you look at the Observatory on broker.dart, you will see the memory use is large. However, when looking at the memory usage of the process on the Operating System side, it's much higher.
In one of our tests, our heap was 32mb. However, the process was actually using 700mb of memory.

Source: https://github.com/IOT-DSA/sdk-dslink-dart

**Comment by johnmccutchan** [comment]
Probably unrelated but I fixed a leak in ThreadRegistry yesterday (a Monitor was leaked for every isolate). Fix is here: https://github.com/dart-lang/sdk/blob/master/runtime/vm/thread_registry.cc#L30

**Comment by sethladd** [comment]
@kaendfinger can you add the OS and the Dart VM version you were using? Thanks!

**Comment by kaendfinger** [comment]
@sethladd Sure

OS: Linux x64 (Ubuntu 14.04 Server on Amazon EC2)
Dart VM: v1.11.3

I also reproduced it on a v1.13.0 Git Build at commit e2f6739b4472b3f25e0d85f74772915834a699b5.

**Comment by sethladd** [comment]
Thanks @kaendfinger . Any chance you can try 1.12-dev ?

**Comment by kaendfinger** [comment]
@sethladd Sure, I should be able to try it in a few hours. I'll report the result ASAP.

**Comment by kaendfinger** [comment]
@sethladd I don't believe I am seeing the leak in the 1.12-dev. I'm getting a very stable memory use from the system stats. While I was investigating, I wanted to know what the relationship between what Observatory reports for memory usage and what the system reports for memory usage is. Should I expect these numbers to be close together?

**Comment by zanderso** [comment]
I was able to reproduce using 1.12.0-dev.5.5. I will continue investigating.

**Comment by zanderso** [comment]
@kaendfinger could you explain a little about what this program is doing? Is it just an http server responding to requests from the responder and requester, or is there also something else going on that could give us a hint? Thanks!

**Comment by kaendfinger** [comment]
@zanderso After running it for a bit longer, it started producing the leak again.

Broker is an HTTP server that allows WebSocket connections and allows each WebSocket client to communicate with each other using our protocol.
Responder is a WebSocket client that communicates using our protocol and provides data.
Requester is a WebSocket client that communicates using our protocol and subscribes to a data stream from the Responder. With some additional caching and other details like that. It measures how many data updates it receives in 1 second. All of the protocol is in JSON.

**Comment by zanderso** [comment]
@kodandersson Please investigate the proper deallocation of the InterruptableThreadState objects.

**Comment by johnmccutchan** [comment]
Related to this- an isolate's ThreadRegistry remembers every thread that an isolate ever runs on. This list is never pruned, so even after a thread exits- the ThreadRegistry is holding onto a ThreadRegistry::Entry for each thread that entered the isolate. We could get into a bad state where an isolate is run on more and more threads and memory usage will grow by a (small) amount for each thread.

**Comment by iposva-google** [comment]
@kaendfinger:
> While I was investigating, I wanted to know what the relationship between what Observatory reports for memory usage and what the system reports for memory usage is. Should I expect these numbers to be close together?

The Observatory reports the Dart heap capacity in use, separately for the new and old generations. There are C++ based allocations in the VM within your process which are not being exposed in the Observatory, but are included in the system reports. The difference between the two numbers comes from VM internal data structures, networking buffers, thread stacks, ...

**Comment by kaendfinger** [comment]
@iposva-google Thanks for the explanation.

**Comment by mit-mit** [comment]
Tagging for 1.12 consideration

**Comment by kodandersson** [comment]
This fixes leaks related to StoreBuffer:
https://codereview.chromium.org/1309603003/

**Comment by whesse** [comment]
I believe that this issue is fixed, and the fixes were merged into 1.12.0-dev.5.9. Please verify and close this issue.

**Comment by kaendfinger** [comment]
@whesse Ok I will check them out ASAP.

**Comment by dglogik** [comment]
The memory leak is verified as fixed. Thank you very much. There is another issue with same test perhaps unrelated; however we're seeing very high CPU usage and observatory is showing 0% CPU utilization.

**Comment by kaendfinger** [comment]
@johnmccutchan I believe this would be in your area. To elaborate on the CPU Usage at 0% thing, we are actually getting a Pi Chart that says 100% Idle, even though it's doing constant work.

**Comment by johnmccutchan** [comment]
What program can I use to reproduce this?

**Comment by kaendfinger** [comment]
@johnmccutchan This is profiling broker.dart
If you would like, here is the live thing: http://benchmark.iot-dsa.org:8181/#/vm

**Comment by johnmccutchan** [comment]
@kaendfinger I need a local reproducible so I can diagnose the problem

**Comment by whesse** [comment]
Can we start a different bug for the CPU usage issue - this 1.12 milestone issue about the VM memory leak should be closed.  Post a link to the new issue to this bug, when it is created.

**Comment by johnmccutchan** [comment]
@kaendfinger The CPU profile issue is likely a known bug with programs that mostly process events quickly. We schedule a profile tick and the isolate finishes processing messages before it is sampled. A local reproduction would be helpful to use while I figure out the correct heurestic for this type of program.

**Comment by kaendfinger** [comment]
@johnmccutchan I will open a new issue for this in just a little bit.
