### ISSUE TITLE
Add void return type for log in dart:developer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24128]
Good to understand if the return value is something interesting.

**Comment by lrhn** [comment]
I think I would prefer `void` as return type. The only value that could make sense to return is the sequence number, but I'm not convinced it's worth it.

What is it returning now? (It's not documented to return anything).

**Comment by johnmccutchan** [comment]
It returns nothing.

**Comment by sethladd** [comment]
Addressed with https://codereview.chromium.org/1295803004/

**Comment by johnmccutchan** [comment]
Thanks Seth!
