### ISSUE TITLE
dartanalyzer crashes when .packages is invalid UTF8

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#24127]
stdout:
```
Unable to read package config data from /usr/local/google/home/het/code/dart/sdk/tests/standalone/package/scenarios/invalid/invalid_utf8.packages: FormatException: Not a valid package name (at character 1)
þ
^
```

**Comment by pq** [comment]
Unlike the `dart2js` corollary (#24120), this doesn't dump a stack trace and the message seems reasonable enough.  @hterkelsen: What's the desired result?

**Comment by pq** [comment]
Back to @hterkelsen: what's the desired result?

**Comment by hterkelsen** [comment]
Since the analyzer is expected to terminate with a nonzero exit code on these then I think it's OK to mark them as 'Crash' in the status file.
