### ISSUE TITLE
dartanalyzer crashes when given a nonexistent file in --packages

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#24123]
stdout:
```
Unable to read package config data from /usr/local/google/home/het/code/dart/sdk/tests/standalone/package/scenarios/invalid/non_existent.packages: FileSystemException: Cannot open file, path = '/usr/local/google/home/het/code/dart/sdk/tests/standalone/package/scenarios/invalid/non_existent.packages' (OS Error: No such file or directory, errno = 2)
```

**Comment by bwilkerson** [comment]
I assume that the issue is the quality of the feedback rather than the behavior of not analyzing the files when one of the inputs is invalid.

**Comment by hterkelsen** [comment]
Yes. The issue is that this is causing dartanalyzer to crash rather than
just reporting an error. The same goes for the other bugs related to
packages.

**Comment by pq** [comment]
I think we need to get clearer on what constitutes a "crash".  I *think* what you mean is that the sdk test runner is reporting a crash.  If that's the case, maybe we need to rethink how we test error conditions in our test scenarios?   IMO this scenario *should* produce and error message (and code).  Is that a test we can express with the runner?

**Comment by hterkelsen** [comment]
Would dartanalyzer "crash" if given a --package-root option that pointed to
a nonexistent directory?

**Comment by pq** [comment]
As it happens, yes.  Worse actually since it gives us a stack trace!

```
[~] $ dartanalyzer --package-root not/here foo.dart
Analyzing [foo.dart]...
Unhandled exception:
FileSystemException: Directory listing failed, path = 'not/here/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._list (dart:io-patch/directory_patch.dart:17)
#1      _Directory.listSync (dart:io/directory_impl.dart:229)
#2      _PackageRootPackageMapBuilder.buildPackageMap (package:analyzer_cli/src/driver.dart:566)
#3      Driver._chooseUriResolutionPolicy (package:analyzer_cli/src/driver.dart:274)
#4      Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:358)
#5      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:113)
#6      Driver.start (package:analyzer_cli/src/driver.dart:102)
#7      main (file:///Users/pquitslund/src/git/clones/dart/sdk/third_party/pkg/analyzer_cli/bin/analyzer.dart:11)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by pq** [comment]
IMO that should be fixed to look more like what we're doing for `.packages`.

Issue to track a fix: https://github.com/dart-lang/analyzer_cli/issues/55

**Comment by pq** [comment]
> Would dartanalyzer "crash" if given a --package-root option that pointed to
a nonexistent directory?

As of https://github.com/dart-lang/analyzer_cli/commit/4a2470fed4913f5a2f7051ae8b6c30c426dde682, this now reports something more like:

    Package root directory (does/not/exist) does not exist.

With an error code of `3`.

**Comment by pq** [comment]
Bumping back to @hterkelsen for more info.  What's the desired behavior?

**Comment by hterkelsen** [comment]
It's OK for the dartanalyzer to 'Crash' on these tests. Closing since this is WAI
