### ISSUE TITLE
Poor message when .packages contains same package name twice

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#24124]
stdout:

```
Unable to read package config data from /usr/local/google/home/het/code/dart/sdk/tests/standalone/package/scenarios/invalid/same_package_twice.packages: FormatException: Same package name occured twice. (at offset 56)
```

**Comment by pq** [comment]
What's the desired result?  I thought we were just bailing if package config files were malformed.

Also, I'm not sure we can characterize this as a 'crash' (but that's obviously a nit).

What does `dart2js` do?

**Comment by bwilkerson** [comment]
> I'm not sure we can characterize this as a 'crash' ...

I agree. This looks like a reasonable error message to me.

**Comment by sethladd** [comment]
Perhaps we can reword the output?

Instead of leading with 'Unable to read package config data from' , let's lead with the actual problem.

How's this?

`.packages format exception: package name '_____' detected twice in /usr/local/google/home/het/code/dart/sdk/tests/standalone/package/scenarios/invalid/same_package_twice.packages`

**Comment by pq** [comment]
@sethladd :+1: for better error messaging.

If we want to go that way, we should move this over to `package_config` since that's where the error we're reporting originates.

**Comment by hterkelsen** [comment]
When I run these scenarios in the SDK test runner, the test runner says they have "Crash"ed. I'm not sure how the test runner distinguishes between compile time errors and crashes.

**Comment by pq** [comment]
> When I run these scenarios in the SDK test runner, the test runner says they have "Crash"ed. I'm not sure how the test runner distinguishes between compile time errors and crashes.

Interesting.  I'm guessing that we produce an error code and that the runner is picking up on that?  In any event, I would expect that we actually *want* that behavior and want our tests to be checking for it.  That is, I would expect that if I run the analyzer with malformed `.packages` info it should produce a useful error message and code.   Is that something we can express in a test scenario?

**Comment by hterkelsen** [comment]
Looking through the .status files in tests/ I don't see any other tests marked 'Crash' for the dartanalyzer besides these.

**Comment by pq** [comment]
> Looking through the .status files in tests/ I don't see any other tests marked 'Crash' for the dartanalyzer besides these.

Cool.  I'm guessing that's because the other tests aren't verifying error conditions?

Sorry if I'm being thick but is there a way to write a test scenario that asserts that the analyzer (or dart2js or the vm), exits with an error code?

**Comment by pq** [comment]
@sethladd : should we move this over to `package_config` for improved messaging there?

**Comment by pq** [comment]
Bumping to @sethladd for follow-up.

**Comment by bwilkerson** [comment]
ping

**Comment by sethladd** [comment]
> should we move this over to package_config for improved messaging there?

I guess that's up to yall on where the best place to put the message is. I assume if you move it over to package_config, then multiple consumers will get a consistent message and experience. That seems like a win to me!

**Comment by devoncarew** [comment]
closing as assumed stale
