### ISSUE TITLE
Please merge dart2js --packages fixes to dev

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#24139]
Please merge the following revisions to dev, they fix dart2js handling of .packages files:
44f890b3c8a5963f348f771c1bd4ff656e7a466e
43e6b8b8dba3138aa2dbe0eaa45bda7fd1e5927d
98e67aa065809ded6e27cb27d3a46b06b77e90c2

**Comment by whesse** [comment]
Merged in 1.12.0-dev.5.6
