### ISSUE TITLE
update bootstraping VM used to build observatory

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24136]
We should update the vm used to build observatory in build.py. I inadvertly broke the build because I started using null-aware operators in dart2js, which are not yet in the VM that is used in the bootstrap process.

@whesse @johnmccutchan

**Comment by rmacnak-google** [comment]
It's fairly old:

~/dart2/sdk/tools/testing/bin/linux$ dart --version
Dart VM version: 1.9.0-dev.10.13 (Mon Mar 23 06:45:57 2015) on "linux_ia32"

**Comment by sigmundch** [comment]
I for now reverted the use of ?? here: https://codereview.chromium.org/1293533006

**Comment by whesse** [comment]
We are planning to update the SDK used to build really soon now.  Just waiting for a cl to land, enabled us to use a complete, downloaded SDK for this.

**Comment by whesse** [comment]
CL https://codereview.chromium.org/1322753005/ , which fixes issue #24053 , downloads the new 1.12.0 stable release SDK for all platforms.  We then need to switch the observatory build over to this.

**Comment by sigmundch** [comment]
Awesome - does this mean that observatory will be built with the pub/dart2js from that downloaded SDK as well? or just using the repo versions of pub/dart2js with the downloaded VM?

If we have a choice, I'd prefer the former: that would make it easier to ensure we are using a consistent set of sdk tools when we build observatory.

**Comment by whesse** [comment]
Yes, that is the point of uploading the whole SDK.  We will also use this
to run the test scripts.

**Comment by whesse** [comment]
The uploaded SDK is now available to the bots.  The observatory team should now switch the build to use it.

**Comment by whesse** [comment]
The observatory now uses the downloaded SDK, which is the stable version 1.12.0, to build observatory.  If that doesn't work, it falls back to using the bootstrap binary to build observatory.
