### ISSUE TITLE
dart2js: ??= not correctly propagated through type inference

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24134]
```dart
void main() {
  Map map;
  map ??= {};
  print(map.length);
  print(map.length == 0);
}
```

This prints:

```dart
0
false
```

I'm not joking. Take a look at this dartpad demo:
https://dartpad.dartlang.org/e1bc7d449cacb06bfce5

**Comment by hterkelsen** [comment]
This does the expected thing if the line `map ??= {}` is changed to `map = {}`. @sigmundch implemented null-aware operators in dart2js

**Comment by dynaxis** [comment]
On VM, the results are sane.

**Comment by sigmundch** [comment]
thanks for filing, I'll take a look, I'm guessing the bug might be in how the inferrer traces the size of the map with `??=`. The bug doesn't come up if you do `map = map ?? {}`, for instance.

**Comment by sigmundch** [comment]
Sent out fix for review here: https://codereview.chromium.org/1305663002/
