### ISSUE TITLE
Merge new dartdoc binary to 1.12

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24130]
@devoncarew, we need to merge the new dartdoc binary (dart-lang/dartdoc#620) into the 1.12 dev branch, right? If so, can you please add the MergeToDev label to this bug once ready as per the [cherry-pick process](https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-dev-channel)?

**Comment by devoncarew** [comment]
I believe @keertip is working on this.

**Comment by mit-mit** [comment]
Closing this, 24131 is tracking the merge
