### ISSUE TITLE
chain null-aware operator

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#24135]
With dart2js

```dart
void main() {
  Map map;
  
  (((map ??= {})['key1'] ??= {})['key2'] ??= {})['key3'] = 'value';
  print(map);
}
```

Instead of print `{key1: {key2: {key3: value}}}` we get `Uncaught TypeError: Cannot read property 'constructor' of undefined`

https://dartpad.dartlang.org/fb1600f504c236d36241

**Comment by tristancaron** [comment]
Probably related to #24134

**Comment by sigmundch** [comment]
Sent out fix for review here: https://codereview.chromium.org/1305663002/
