### ISSUE TITLE
VM service: Class.error documentation is incorrect

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24146]
In the [VM service documentation](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#class), the `Class.error` field is documented to have type `@Instance`. However, in practice this field returns a value of type `@Error`. `@Error` is probably correct, since it includes extra metadata like the error kind and stack trace.

**Comment by turnidge** [comment]
Yep.  Will fix.

**Comment by turnidge** [comment]
Fixed in bfd59ed7993dc8718b2beb501b429a69fc4c1973.
