### ISSUE TITLE
Dynamically-spawned isolates have a malformed rootLib field in the service protocol

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24140]
When an isolate is newly-spawned and reported via an `IsolateStart` event, loading the isolate will result in an invalid value for the `rootLib` field. Instead of a `@Library`, it will be an `@Instance` with `_vmType` set to `Library` but otherwise looking like a null instance:

```json
"rootLib": {
  "type": "@Instance",
  "_vmType": "Library",
  "kind": "Null",
  "fixedId": true,
  "id": "objects/null",
  "valueAsString": "null"
}
```

Nor does the entrypoint library appear in the `libraries` list.

This seems to happen regardless of whether `Isolate.spawn` or `Isolate.spawnUri` is used.

**Comment by johnmccutchan** [comment]
IsolateStart is sent very early on and what you are seeing is consistent. We probably need another event that signals the isolate is 'runnable'.

**Comment by nex3** [comment]
As a user of the protocol, I'd prefer to have `IsolateStart` be sent later so I can always rely on my isolate references being in a usable state. If that's not possible, then `rootLib` could be marked as `[optional]`.

**Comment by johnmccutchan** [comment]
1) We should mark rootLib and entry optional and we shouldn't be including rootLib for a null instance.
2) We should send out an even when an isolate is fully ready.

**Comment by nex3** [comment]
:+1:

**Comment by nex3** [comment]
It would be nice to also have an `@Isolate.isRunnable` field. Otherwise, moving from an `@Isolate` that may or may not be runnable to a runnable `Isolate` takes an extra `getObject` to see whether you need to listen to the `Isolate` stream at all.

**Comment by nex3** [comment]
I would be nice to also have an `@Isolate.isRunnable` field, so that code that gets an arbitrary `@Isolate` and wants a guaranteed-runnable `Isolate` can avoid listening to a stream when unnecessary.
