### ISSUE TITLE
Dynamically-spawned isolates should include their entrypoint in the service protocol

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24141]
When an isolate is newly-spawned and reported via an `IsolateStart` event, loading the isolate won't return a value for the `entry` field. The documentation does say that this field is optional, but it seems like it should be included for these isolates, since it's well-defined.

See also #24140

**Comment by johnmccutchan** [comment]
IsolateStart is sent very early on and what you are seeing is consistent. We probably need another event that signals the isolate is 'runnable'.

**Comment by johnmccutchan** [comment]
Duplicate of #24140
