### ISSUE TITLE
getIsolate returns malformed error responses in the service protocol

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24142]
When passing an expired Isolate ID to `getIsolate`, it returned the following response:

```json
{
  "type": "Error",
  "message": "Cannot find isolate id: 1051045948",
  "request": {
    "method": "getIsolate",
    "params": {
      "isolateId": "isolates/1051045948"
    }
  }
}
```

This isn't a valid `Error` object according to the VM service documentation, nor is `getIsolate` documented to return an `Error`. If it fails, I'd expect it to return a RPC-level error, or a `Sentinel` as per `getObject`.

**Comment by johnmccutchan** [comment]
@nex3 You are correct, we should return an RPC-level error. This is just a bug.

**Comment by turnidge** [comment]
This now returns an RPC-level error.  0706f6de29bc29bbeebad192d65d2ce3fe42051f.
