### ISSUE TITLE
VM service: unclear how to invoke removeBreakpoint

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24147]
The VM service documentation includes [a `removeBreakpoint()` function](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#removebreakpoint) that takes an isolate ID and a (string) breakpoint ID. However, [the `Breakpoint` class itself](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#breakpoint) doesn't include an ID field. The closest thing is the breakpoint number, but that's an integer, not a string.

**Comment by turnidge** [comment]
Yep.  Breakpoint extends Object.  Error in service.md.

**Comment by turnidge** [comment]
Fixed in bfd59ed7993dc8718b2beb501b429a69fc4c1973.

**Comment by nex3** [comment]
Just to clarify: despite `Breakpoint` extending `Object`, `@Breakpoint` is intended to be undefined and unused?

**Comment by turnidge** [comment]
Yeah, this is intentional but I'll admit that it is weird.  I could put it
in the spec, but nothing currently ever returns it...
