### ISSUE TITLE
Please merge multiple revisions into dev channel

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24151]
@ricowind @whesse @kasperl

Fully implement new parameters on `Isolate.spawn`/`Isolate.spawnUri` on dart2js and remove the "not implemented yet" warning.
Document parameters in CHANGELOG.md.

Revisions:
4b80cfd69eaf98
5fa70c4220fb70
6c7093dd1900e5
f8f06d784ad1c9
2d38e15b822432

The first four merge cleanly, the fifth does not. A cleaned-up merge against 1.12.0-dev.5.5 is available at:
https://codereview.chromium.org/1298793004

**Comment by whesse** [comment]
The CL is based on master, not dev, and I think it is maybe better to have an individual fixed merge for the commit with problems.  This is pretty hard for you to prepare, so is it easy for you to tell me how to resolve the conflicts, and I will do it in the cherry-pick process?

**Comment by lrhn** [comment]
The merge that fails is on CHANGELOG.md. It only needs to include the part about dart:isolate, not the two following changes.
(Those other changes probably still need to go into 1.12-dev too since they are documenting 1.12 changes and are not on the branch yet, but I don't know if that has already been asked for).

**Comment by whesse** [comment]
Merged in 1.12.0-dev.5.6
