### ISSUE TITLE
Could dart support offline build and publish app to android?

### ISSUE THREAD

**Issue by taozuhong** [dart-lang/sdk#24152]
I'm dart developer in china, due to the GFW( china great firewall), I can't using pub tool to get or upgrade package , so I hope dart sdk could support build and publish app in offline mode.

Could dartt support offline build and publish app to android?

**Comment by nex3** [comment]
Pub does have an `--offline` flag that you can pass to `pub get` or `pub upgrade` that will tell it to only fetch packages from your local cache. If you can fill that cache manually, it's certainly possible to avoid making requests to `pub.dartlang.org`. I don't think this is something we want to support more explicitly, though.
