### ISSUE TITLE
Mark Resource class 'Experimental' in 1.12

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24150]
Per release meeting discussion: During the implementation of the Resource class we have learned a number of things that will likely cause us to redesign the Resource class API post 1.12. However, we still think shipping the class in 1.12 is valuable to get more feedback from customers. Thus, we agreed to mark Resource as Experimental, in the dartdoc comments, with a note that says "This API is under development, it may be changed or removed in future releases."

**Comment by mit-mit** [comment]
Closed with https://github.com/dart-lang/sdk/commit/1d537028f7cbe026fb682804fb13c72aa3261ae5

**Comment by devoncarew** [comment]
Is there an issue to track the api discussion?

**Comment by sethladd** [comment]
You probably want to check out https://github.com/dart-lang/sdk/issues/24022
