### ISSUE TITLE
Unnamed libraries should not cause warnings

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24156]
Commit a0e4f281609de0e4c66676c299f630d570e9e276 modified the spec so that it is no longer a warning to import multiple unnamed libraries.  It is still a warning to import multiple named libraries with the same name.

We need to modify the analyzer to implement this change, and update (or write) the corresponding shared tests.

**Comment by sethladd** [comment]
yay!!!!!!!!!

**Comment by sethladd** [comment]
@pq is this in the command-line analyzer or Analysis Server for 1.13-dev ?

**Comment by stereotype441** [comment]
@sethladd Yes to both.

**Comment by sethladd** [comment]
woohoo! :)

**Comment by sethladd** [comment]
Just to confirm, is this behind a flag?

**Comment by stereotype441** [comment]
@sethladd No, the behavior has been unconditionally changed.

**Comment by sethladd** [comment]
Cool, thanks for the confirmation!
