### ISSUE TITLE
pkg/compiler failing analysis on a test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24158]
The new version of dartdoc has a test that causes an analysis failure on 1.12-dev, https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer_experimental-linux-release-dev/builds/97

This needs to be fixed, and the fix merged to 1.12-dev.  This will be trickier because the error is not there on bleeding edge, so there may already be a fix somewhere on bleeding-edge (master), that just needs to be found and merged to dev.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by keertip** [comment]
@whesse , is it the pkg/docgen test failures that I should be looking at?

**Comment by keertip** [comment]
@whesse  it looks like the warnings are in the pkg/compiler code, and nothing to do with docgen ?

Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|UNDEFINED_IDENTIFIER|/mnt/data/b/build/slave/analyzer_experimental-linux-release-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart|392|21|21|Undefined name 'NO_LOCATION_SPANNABLE'
WARNING|STATIC_WARNING|UNDEFINED_IDENTIFIER|/mnt/data/b/build/slave/analyzer_experimental-linux-release-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart|392|44|11|Undefined name 'MessageKind'

**Comment by whesse** [comment]
Ok, the analysis is failing on a file changed in a different merged CL, coming from @hterkelsen

**Comment by hterkelsen** [comment]
This will be fixed when #24159 is merged

**Comment by whesse** [comment]
This is fixed in 1.12.0-dev.5.10
