### ISSUE TITLE
VM: command line debugger tools/ddbg.dart broken?

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24165]
@mhausner : It seems that ddbg tries to open the current working directory and failing.

:/media/SSD/dartgit2/sdk$ out/ReleaseIA32/dart tools/ddbg.dart hello.dart 
> run
Started process 7812 'out/ReleaseIA32/dart --debug:5858  hello.dart '
Isolate 892178730 has been created.
Isolate 892178730 has terminated.
Unhandled exception:
Load Error for "file:///media/SSD/dartgit2/sdk/": Error loading file:///media/SSD/dartgit2/sdk/:
  FileSystemException: Cannot open file, path = '/media/SSD/dartgit2/sdk/' (OS Error: Is a directory, errno = 21)
#0      _asyncLoadErrorCallback (dart:_builtin:149)
#1      _asyncLoadError (dart:_builtin:541)
#2      _handleLoaderReply (dart:_builtin:364)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Process exited with code 255.

**Comment by mhausner** [comment]
I just synced and built now. I can't repro this. Maybe the missing package-root is a problem in your case?

$DART_ROOT/xcodebuild/DebugIA32/dart  $DART_ROOT/tools/ddbg.dart --package-root=$DART_ROOT/xcodebuild/DebugIA32/packages/ tests/language/hello_dart_test.dart 
> run
Started process 13868 '/src/d1/sdk/xcodebuild/DebugIA32/dart --debug:5858 --package-root=/src/d1/sdk/xcodebuild/DebugIA32/packages/ tests/language/hello_dart_test.dart '
Isolate 899005093 has been created.
Main isolate is 899005093
Current isolate is now 899005093
15      main() {
> bt
#0  main at file: hello_dart_test.dart lib: 14 token: 29
#1  <anonymous closure> at file: isolate_patch.dart lib: 1 token: 1366
  port = (obj, id 0) object of type _RawReceivePortImpl
  isSpawnUri = true
  entryPoint = (closure main() => dynamic file: hello_dart_test.dart lib: 14 token: 29)
  args = (list, id 3, len 1) [""]
  message = (obj, id 4) null
  _ = (obj, id 4) null
#2  _RawReceivePortImpl@709387912._handleMessage@709387912 at file: isolate_patch.dart lib: 1 token: 771
  handler = (closure _startIsolate.<anonymous closure>(dynamic) => dynamic file: isolate_patch.dart lib: 1 token: 1296)
  message = (obj, id 4) null
> r
Hello, Darter!
Main isolate 899005093 has terminated.
All isolates have terminated.
Process exited normally.
>

**Comment by mhausner** [comment]
FWIW, if I leave out the package-root, I get the same error you do:

```
$ $DART_ROOT/xcodebuild/DebugIA32/dart  $DART_ROOT/tools/ddbg.dart  tests/language/hello_dart_test.dart 
> run
Started process 13971 '/src/d1/sdk/xcodebuild/DebugIA32/dart --debug:5858  tests/language/hello_dart_test.dart '
Isolate 477326014 has been created.
Isolate 477326014 has terminated.
Unhandled exception:
Load Error for "file:///src/d1/sdk/": Error loading file:///src/d1/sdk/:
  FileSystemException: Cannot open file, path = '/src/d1/sdk/' (OS Error: Is a directory, errno = 21)
#0      _asyncLoadErrorCallback (dart:_builtin:149)
#1      _asyncLoadError (dart:_builtin:541)
#2      _handleLoaderReply (dart:_builtin:364)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Process exited with code 255.
> 
```

**Comment by fsc8000** [comment]
Possibly - I did not know that the package-root is mandatory. Maybe the error message should mention it?

**Comment by rmacnak-google** [comment]
Removed with the legacy debug protocol in 6249c2bcf3cb4a2241dd27caf087f07ea05147b3
