### ISSUE TITLE
--break-at interprets a file as a function

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24161]
From the `dart --help -v` output:

```
--break-at=<location>
  sets a breakpoint at specified location where <location> is one of :
  url:<line_num> e.g. test.dart:10
  [<class_name>.]<function_name> e.g. B.foo
```

However, when I run `dart --break-at=test.dart:2 test.dart` on the following file:

```dart
main() {
  print("one");
  print("two");
}
```

it prints this error and exits immediately:

```
Error setting breakpoint at 'test.dart:2': Dart_OneTimeBreakAtEntry: could not find function 'test.dart:2'
```

This happens regardless of whether the path is relative or absolute. I'm using `1.13.0-edge.9e18a7519d429f87c70bb3b8871c6cc666ee3fa6`.

**Comment by johnmccutchan** [comment]
@nex3 Note that this flag may only work with the the deprecated debugger. 

In the meantime: 

1) import 'dart:developer';
2) Add a debugger() statement where you want the breakpoint to hit
3) Connect to Observatory and start debugging.

**Comment by iposva-google** [comment]
The help text is outdated.The feature of breaking at file:line has not been supported for 2+ years.

Thanks for finding this issue.

**Comment by iposva-google** [comment]
@mhausner Can you please update the verbose usage text? Thanks!

**Comment by nex3** [comment]
@iposva-google Does that mean there's no way to set a breakpoint in the body of a function from the command line?

**Comment by mhausner** [comment]
I'll fix the outdated help text. Breaking at an arbitrary location can be done via the steps outlined but @johnmccutchan above.

**Comment by nex3** [comment]
Setting a line-based breakpoint is possible via Observatory and the VM service protocol—why not support it on the command line?

**Comment by iposva-google** [comment]
Because breakpoints should be set via the VM service connection, which acts as the debugger agent. The command line flag was originally introduced for the legacy debugger protocol, which does not allow for breaking on isolate start. The command line flag will be removed when the legacy debugger protocol is removed.

**Comment by nex3** [comment]
Why does the VM service connection have to be the only debugger agent? It's a lot lower-overhead for a user to pass a single flag than to pass `--pause-isolates-on-start` (which is buried in the VM development flags list), connect to the observatory, navigate to the debugger, and set the breakpoint there.

**Comment by rmacnak-google** [comment]
Flag removed with the legacy debug protocol in 6249c2bcf3cb4a2241dd27caf087f07ea05147b3
