### ISSUE TITLE
No warning when element HTML file is missing import

### ISSUE THREAD

**Issue by theqwertman** [dart-lang/sdk#24167]
For example, 

    <polymer-element name="address-entry">
      <template>
        <style>
          :host {
            display: block;
          }
        </style>
    <paper-dialog><h2>Something</h2></paper-dialog>

should report an error since there is no import link whatsoever, but the build succeeds without complaint, and the developer must investigate to find out why their element is not appearing.

**Comment by sigmundch** [comment]
This issue was moved to dart-lang/polymer-dart#560
