### ISSUE TITLE
Debugger moves breakpoint to line 0

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#24164]
I'm using the debugger (from the Dart Editor, don't ask why).  I've set a breakpoint in a function that looks like:

```dart
  void visitInvokeMethod(InvokeMethod node) {
    if (constifyExpression(node)) return;
    if (specializeOperatorCall(node)) return;
    if (specializeFieldAccess(node)) return;
    if (specializeIndexableAccess(node)) return;
    if (specializeArrayAccess(node)) return;
    if (specializeClosureCall(node)) return;
    if (node.selector.name.contains('getDispatchProperty')) {
      print('found it');
    }

    AbstractValue receiver = getValue(node.receiver.definition);
    node.receiverIsNotNull = receiver.isDefinitelyNotNull;
  }
```

The breakpoint is at the line 1580: `print('found it');`.  The output window in the editor reports:

```
Observatory listening on http://127.0.0.1:60711
Dart file (src/tree/tree_benchmark.dart) compiled to JavaScript: out.js
[breakpoint in type_propagation.dart moved from line 1580 to 0]
```

(The second line of text is printed by the application I'm debugging).  I could not create a reduced test case and my debugging scenario is kind of complicated to reproduce.

**Comment by sethladd** [comment]
Thanks for the report. We don't even have a label for Dart Editor anymore. :/ Can you please try Observatory or WebStorm ?
