### ISSUE TITLE
no 'localName' completion for top-level html element of html package

### ISSUE THREAD

**Issue by guillermooo** [dart-lang/sdk#24178]
More details here:

https://github.com/guillermooo/dart-sublime-bundle/issues/563

**Comment by bwilkerson** [comment]
Given your example:

    import "package:html/parser.dart";

    main() {
      var p1 = parse("<p>hello</p>");
      var t1 = p1.nodes.first;
      print(t1.^);
    }

Note that `parse` returns a `Document`, `Document.nodes` returns a `NodeList`, and `NodeList.first` returns a `Node`. Given that `localName` is not defined on `Node`, not including it in the list seems reasonable to me. Am I missing something?

**Comment by guillermooo** [comment]
```dart
import "package:html/parser.dart";

main() {
  var p1 = parse("<p>hello</p>");
  var t1 = p1.nodes.first;
  print(t1.localName);
}
```
That returns "html" for me. That's what puzzled me, but I have not dug into the code.

**Comment by bwilkerson** [comment]
To be clear, I was referring to the static types of the methods and getters, not the run-time types of the values returned by them.

**Comment by guillermooo** [comment]
I think I was expecting the Dart VM to return an error in checked mode here and enforce this:

```
...
(t1 as dom.Element).localName
...
```

But it turns out the VM never enforces anything, it's just the DAS that is able to flag more issues as you get more explicit with var decls, etc. I keep forgetting this.

So everything works as I expect with this:

```dart
...
// var t1 = parsed.nodes.first;
dom.Node t1 = parsed.nodes.first;

t1.localName // DAS flags this now but the VM runs it happily anyway
```

**Comment by guillermooo** [comment]
After your explanations, this is a no-bug, so closing this out.
