### ISSUE TITLE
Please merge CL 1305353003 into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24177]
@ricowind @whesse @kasperl @mit-mit 
This fixes several small and large memory leaks in 1.12.

Due to the amount of conflicts when applying the cherry-picks, the resolved changes in https://codereview.chromium.org/1305353003/ should be applied to the dev branch.

cc:
@kodandersson @johnmccutchan @zanderso

**Comment by whesse** [comment]
Merged in 1.12.0-dev.5.9
