### ISSUE TITLE
Code completion not showing obvious match

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24175]
Hi,

I recorded odd behavior with code completion in Atom, but I suspect this is the analysis server?

https://www.youtube.com/watch?v=j5kGQhNtwDI&feature=youtu.be

In this case, my object has a method called oneLineDoc. I'm try to complete it, by typing o then n etc

There's really nothing else that would match `o` other than oneLineDoc however you'll see a second 1 that no options appear. If I type `n` I do see an option. If I type `e` the option disappears.

**Comment by sethladd** [comment]
cc @devoncarew for Atom

**Comment by devoncarew** [comment]
`on` is a keyword; perhaps that's throwing off the analysis engine?

**Comment by jwren** [comment]
Could not reproduce with the code below.  If it is still occurring, reopen with either a code snippet or a code location in a library where the issue does still occur.

```
class A {
  int oneLineDoc;
}

m(dynamic d) {}

f(A a) {

  m(a.oneLine^)
}
```
