### ISSUE TITLE
Add a quickfix to extract class definitions from unit tests

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/sdk#24179]
User Story
1. I write a group of unit tests for a class that doesn't exist yet.
2. Quick fix on test group suggests 'Extract class definition'.
3. New skeleton implementation of class added to a new file or existing file.

This would aid productivity and encourage test first development.

**Comment by keertip** [comment]
Great idea, but we will not get to this. Closing issue as will not implement.
