### ISSUE TITLE
Observatory javascript issue in calculating inbound references

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#24181]
@johnmccutchan 

See attached screenshot
![screenshot from 2015-08-24 15 07 44](https://cloud.githubusercontent.com/assets/5475521/9440768/ed1bf680-4a71-11e5-9ab4-87b3c33694ee.png)

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
85ef528eaa3360f55644194eea5d6711159e79f8
