### ISSUE TITLE
registerElement on Safari

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#24187]
```dart
document.registerElement('my-header', MyHeader, extendsTag: 'header');
```
When compiled to JS and executed on Safari, I get `TypeError: undefined is not a function (evaluating '$document.registerElement(tag, options)')`

OS X 10.10.4
Safari 8.0.7
Dart 1.11.3

**Comment by alan-knight** [comment]
That would have to be filed as a bug against Safari. They don't support registerElement yet. See, e.g. https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement
