### ISSUE TITLE
Analysis server goes into infinite analysis loop when resolution throws exception

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24198]
When the analysis engine is used in asynchronous fashion (by repeated execution of performAnalysisTask()), and an exception occurs during analysis of a file, the file should be placed in an "exception" state so that performAnalysisTask() will move on to analyzing other files.  The analysis server relies on this behavior to ensure that if an exception occurs, analysis will eventually terminate and the user can still make use of analysis server features in unrelated files.

However, in the repro for issue #24191, this doesn't seem to be working, at least not in the case where the exception is thrown during resolution.  Instead, the analysis server goes into an infinite loop, analyzing the same file repeatedly many times per second.  Code completion and navigation requests in the bad file are extremely slow to respond.

**Comment by mit-mit** [comment]
Is anyone looking into this?

**Comment by bwilkerson** [comment]
Not directly, but we are doing some related work (implementing the new task model) that might also fix this issue.

**Comment by mit-mit** [comment]
Unassigning milestone until we actually have someone working on this.

**Comment by bwilkerson** [comment]
Now that the new task model is in, we need to check whether this is still an issue.

**Comment by scheglov** [comment]
No, we don't get into infinite analysis loop.
We mark entries with exceptions and stop analysis.
