### ISSUE TITLE
Dart SDK wrongly changes path to libraries when moving file

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24195]
Steps to reproduce

1. Create file lib.dart with the following content:
```dart
library some_lib;
```
2. Create file file.dart with the following content
```dart
import "lib.dart";
main() {
}
```
3. Create folder 'folder'
4. In dart SDK drag and drop both file.dart and lib.dart to the newly created folder (both files at the same time)

Actual result: in file file.dart path to the library changed to ../lib.dart
```dart
import "../lib.dart";
main() {
}

Expected: import should contain correct path to the library

Tested on Dart Editor version 1.8.5.release (STABLE), Dart SDK version 1.8.5 on Ubuntu 14.04 LTS

**Comment by whesse** [comment]
The Dart Editor has been phased out, and is replaced with plugins for different free and commercial IDEs. The Dart Editor no longer ships, so it is unlikely that there will be bug fixes for it.
