### ISSUE TITLE
fold with combine that returns future

### ISSUE THREAD

**Issue by maiermic** [dart-lang/sdk#24199]
Why does this test fail?

``` dart
test('fold returns Future of Future', () {
  new Stream.empty()
      .fold(new Future.value(42), (p, c) => p)
      .then((e) => expect(e is Future, isTrue));
});
```

Is this a bug or a feature? If it is a feature, please mention this behaviour in the doc comments of fold.

**Comment by lrhn** [comment]
Feature. You generally cannot create a Future of a Future. 

That means that when `fold`, which is an async function itself, tries to complete its returned future with your future, it completes the returned future with the *result* of your future instead.

I'm not sure if this is written out explicitly anywhere. it should probably be mentioned on the Future class.

**Comment by floitschG** [comment]
Created a bug for the documention: https://github.com/dart-lang/sdk/issues/30415
