### ISSUE TITLE
the parameters field in the Element type doesn't handle optional params correctly

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24194]
The parameters field in the Element type doesn't handle optional params correctly. The `parameters` text I get back from completions doesn't concatenate optional parameters correctly - it starts and stops a new optional section with each parameter. For context, this is for `CompletionSuggestion.element.parameters`.

```
runZoned: (() → dynamic body, {Map<dynamic, dynamic> zoneValues}, {ZoneSpecification zoneSpecification}, {Function onError})
```

<img width="482" alt="screen shot 2015-08-24 at 7 14 20 pm" src="https://cloud.githubusercontent.com/assets/1269969/9457181/d01131ae-4a94-11e5-89ae-481f38e0c5ec.png">

<img width="735" alt="screen shot 2015-08-24 at 7 14 45 pm" src="https://cloud.githubusercontent.com/assets/1269969/9457180/d0100a04-4a94-11e5-89e8-becc57d55f66.png">

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1313113002/
