### ISSUE TITLE
Await for expression using type ReceivePort causes exception in Resolver

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24191]
Pasting the following code into an empty Dart file:

    import 'dart:isolate';

    f(ReceivePort p) async {
      await for (var v in p) {}
    }

causes an exception to occur.  Here's the relevant part of the stacktrace:

    RangeError (index):: Invalid value:: Only valid value is 0:: 0
    #0      List.[] (dart::core-patch/array.dart::134)
    #1      ResolverVisitor._getStreamElementType (package::analyzer/src/generated/resolver.dart::11268)
    #2      ResolverVisitor.visitForEachStatementInScope (package::analyzer/src/generated/resolver.dart::10824)

It appears that the problem is that _getStreamElementType() assumes that if the type of the stream expression exposes a listen() function, then its zeroth type parameter indicating the type of the thing being iterated over.  But that is not the case for ReceivePort, which has no type parameters.

It is also possible to imagine classes which have type parameters, but for which the zeroth type parameter is not the type of the thing being iterated over, e.g.:

    class MyCustomStream<T> implements Stream<List<T>> { ... }

Probably what should happen instead is that _getStreamElementType() should examine the type of the listen() function in order to determine the type of the thing being iterated over (this is similar to what _getIteratorElementType() does).

However we might want to consider doing a band-aid fix sooner, since this exception causes the analysis server to go into an infinite analysis loop.

(I will file a separate issue about the fact that an exception in resolution can cause an infinite analysis loop in the analysis server; the analysis server really should be more robust than that.)

**Comment by jmesserly** [comment]
should be fixed now
