### ISSUE TITLE
dart:mirrors includes static members when doing mixin-application

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#24204]
```
import "dart:mirrors";

class M {
static staticFoo(x) => x + 1;
}

class A {}

class B extends A with M {}

main() {
  print(reflectType(B).superclass.declarations);
  print(reflectType(B).superclass.invoke(#staticFoo, [1]));
}
```

prints (on the vm):

```
{Symbol("staticFoo"): MethodMirror on 'staticFoo', Symbol(".A with .M"): MethodMirror on '.A with .M'}
Unhandled exception:
No static method 'staticFoo' declared in class 'A&M'.

NoSuchMethodError: method not found: 'staticFoo'
Receiver: Type: class 'A&M'
Arguments: [1]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      _LocalClassMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:927)
#2      _LocalObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:363)
#3      main (file:///usr/local/google/home/sigurdm/test/main.dart:13:35)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

So the method seems to be there (in declarations) but cannot be invoked. Dart2js has similar behavior.
The spec seems to say that static methods are not mixed in.

**Comment by sigurdm** [comment]
I have made a cl https://codereview.chromium.org/1315103003/ that fixes a few formatting issues of this and undoes the changes to run_tests. We prefer having modularized changes.

I will apply this, and then apply the diff to the cl when it has LGTM.

**Comment by sigurdm** [comment]
And sorry for the delay

**Comment by rmacnak-google** [comment]
I believe this is a bug in the spec: that mixin applications should get copies of static members and the following should print false.

class S1 {}
class S2 {}
class M {
  static var field = new Object();
  staticField() => field;  // Not M.field.
}
class MA1 extends S1 with M {}
class MA2 extends S2 with M {}

main() {
  print(new MA1().staticField() == new MA2().staticField());
}

@gbracha
