### ISSUE TITLE
auto-complete should be ordering results in a more useful order

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24201]
From https://github.com/dart-atom/dartlang/issues/239:

I have a class definition with 5+ fields and I am trying to instantiate it:

```dart
var a = new MyClass()..[ctrl+space]
```
However the first suggested completions are: 
```
false, new, null, true
```
It does not seem like I would ever need to auto-complete those. 

Then appear all the properties (own and inherited) in an alphabetical order.
I think it would be more useful to provide the fields and properties at the top as very few programmers forget the keywords of a language.

**Comment by sethladd** [comment]
Just saw this:

![screen shot 2015-08-26 at 1 52 21 pm](https://cloud.githubusercontent.com/assets/5479/9505879/bc04b332-4bf9-11e5-9c0e-6fcefc75c280.png)

The example here is: `object..forEach`. Maybe the AS can order the code completion results to prefer getters that would return something that forEach can be called on?

**Comment by jwren** [comment]
![image](https://cloud.githubusercontent.com/assets/1533520/14692249/ca4c9fe6-070a-11e6-8bd6-a3862576a4ce.png)
