### ISSUE TITLE
Strange inference with a ternary operator and Lists

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24202]
On the following code:

```dart
void fn(Iterable iter) {}

void main() {
  bool condition = true;
  Iterable<String> iter = [];
  fn(condition ? [] : iter.toList());
}
```

The analyzer reports the following warning:

```
[warning] The argument type 'EfficientLength' cannot be assigned to the parameter type 'Iterable'
```

This seems wrong. The first branch of the ternary operator is a `List`, which is assignable to `Iterable`.

Note that if `<String>` is removed from the type annotation for `iter`, or if `<String>` is added to the list literal, the warning goes away.

I'm using 1.13.0-edge.9e18a7519d429f87c70bb3b8871c6cc666ee3fa6.

**Comment by lrhn** [comment]
This looks like an instance of issue 19425.

**Comment by bwilkerson** [comment]
Yes, sadly, unless we get a different definition of least upper bounds we're stuck. The current specification of LUB says that LUB(List<String>, List<dynamic>) is EfficientLength. The answer that everyone expects is List<dynamic>, so it surprises lots of people fairly frequently.

To work around this, you either have to write "<String>[]" for the literal, or stop using the conditional operator (the only place where LUB is used in the spec.).
