### ISSUE TITLE
DateTime.parse() does not strictly include RFC 3339: limited millisecond length

### ISSUE THREAD

**Issue by ericklaus-wf** [dart-lang/sdk#24205]
RFC 3339 defines the "time-secfrac" component of a timestamp to be `"." 1*DIGIT`, which permits second fractions of unlimited length. `DateTime.parse()` only accepts a second fraction component of up to length 6.

The length limitation on "millis_opt" should be removed, or the documentation should be updated to note that DateTime.parse() does not strictly support RFC 3339.

**Comment by stevenroose** [comment]
I have this problem as well. Dart fails to parse dates generated by Go, f.e.: `2018-01-29T18:39:51.396781283+01:00`.

**Comment by stevenroose** [comment]
Is there a reason why Dart calls the standard "ISO8601" while Go refers to "RFC3339".

Could the two teams in Google maybe agree on a standard to follow? :)

**Comment by curtiscovington** [comment]
I'm having this issue too. It is really annoying having to chop off some digits of the string I get from Go's time.Time in order for DateTime to parse it correctly.

**Comment by stevenroose** [comment]
I think I solved it by in Go, making a `newTime := time.Unix(oldTime.Unix())`, which truncate to seconds.

**Comment by curtiscovington** [comment]
@stevenroose I solved it in dart by just taking a substring. But I think the Dart SDK should address this specifically. A default server timestamp from Go should have no issues parsing through Dart. Even if we lose precision. Perhaps the parse could optionally chop off the extra digits?

**Comment by stevenroose** [comment]
@curtiscovington I had a substring thing first, but it broke when using different time zones etc. Yeah Dart should surely solve this.

**Comment by lrhn** [comment]
See also #1878.
We should extend the formats recognized by `DateTime.parse`.
Accepting more formats does come with a cost, since all the necessary code will be included when you use the function, even if you only use a single simple format.

**Comment by vargavince91** [comment]
I have the same issue with creating Dart `DateTime` object coming from a Go backend (for example: `const invalid = "2019-05-31T10:35:45.347333481Z";`).

As you see this format is using nanoseconds (`10^-9`) and the [Dart `DateTime.parse`](https://github.com/dart-lang/sdk/blob/db8dca4fbf815883a595d00c7296c97c785885b1/sdk/lib/core/date_time.dart#L277) code only allows up to microseconds (`10^-6`).

The quick fix I used: drop the sub-microsecond digits (from between 7th to 9th)

```dart
String removeNano(String s) {
  // You could add a stricter verification, but for my usecase this is just enough:
  if (s.length == 30) return s.substring(0, 26) + s[29];
   // Decide what to do when invalid format is passed in: return null, return original string, or throw?
  throw Exception('Unexpected format.');
}
// Example usage
void main() {
  const invalidNano = "2019-05-31T10:35:45.347333481Z";
  //// This would fail:
  // DateTime.parse(invalidNano);
  final date = DateTime.parse(removeNano(invalidNano));
  print(date);
}
```

What would be the implications of allowing nanosecond values? As I see the `parse` method could ignore extra digits relatively easily, so I assume there are other reasons you decided not to update the `parse` method.  Would you merge a pull request adding the nano support? Which solution would you merge (ignore sub-microsecond values, round sub-microsecond values to the microsecond, complete nanoseconds support)?

**Comment by kinex** [comment]
Same problem with date strings created in C#: For example:
```c# 
DateTimeOffset.Now.ToString("O")
```
outputs: "2019-08-09T06:55:01.8968264+00:00"

**Comment by mtcliatt** [comment]
Can we get a response to vargavince91's comment please?

**Comment by Albert221** [comment]
I created a pub package to address this exact problem for `built_value`: https://pub.dev/packages/rfc_3339_date_time_serializer

**Comment by lewinpauli** [comment]
I did it the following way:

```
import 'package:intl/intl.dart'; //needed for DateFormat

String formatToGolangCompatibleRFC3339NanoUtc(DateTime date) {
    
      return DateFormat("yyyy-MM-ddTHH:mm:ss.SSSSSSSSS+00:00").format(DateTime.parse(date.toString()).toUtc());
}
```
Usage:

`print(formatToGolangCompatibleRFC3339NanoUtc(DateTime.now()));`

Output:

`2023-05-02T14:13:19.275000000+00:00`

Note:

if you dont want to use utc you can use "date.timeZoneOffset" and replace the hardcoded +00:00
