### ISSUE TITLE
Removing legacy debug protocol from VM

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24209]
The [Dart VM Service Protocol](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) is now spec'ed and battle tested.

The legacy debug protocol is now deprecated. We intend to remove this support in 1.13. We encourage tool vendors to use the new Service Protocol for debugging a Dart VM.

**Comment by sethladd** [comment]
cc @johnmccutchan @turnidge

**Comment by mit-mit** [comment]
@sethladd , should we move this bug to 1.14? This wont happen until then, right?

**Comment by mit-mit** [comment]
@iposva-google moving to you now that we are in 1.14.

**Comment by rmacnak-google** [comment]
6249c2bcf3cb4a2241dd27caf087f07ea05147b3

**Comment by zoechi** [comment]
Is WebStorm using the new protocol already or will WebStorm debugging break with bleeding_edge in a few days @alexander-doroshko?

**Comment by alexander-doroshko** [comment]
WebStorm already uses new VM Service protocol for debugging in case of SDK 1.14+

**Comment by zoechi** [comment]
@alexander-doroshko Great! Thanks for the confirmation.

**Comment by EasonPai** [comment]
dear @alexander-doroshko,
how can I know my version of WebStorm is already uses new VM Service protocol for debugging?
I have an issue probably related to this. 

When I tried to work on my Mac (El Captain) & WebStorm 10.0.4 , and I got the problem below.
If this is an issues related to the new protocol, what should i do now?

> Unable to connect debugger to the Dart VM: Connection refused 
>  
> /Users/eason/Documents/dev/dart/sdk/dart-sdk/dart-sdk_v1.14.2/bin/dart --ignore-unrecognized-flags --checked --package-root=/Users/eason/Documents/dev/dart/project/project-dartsphere/dartsphere/packages --debug:52304 --break-at-isolate-spawn --enable-vm-service:52305 --trace_service_pause_events /Users/eason/Documents/dev/dart/project/project-dartsphere/dartsphere/bin/main.dart
> Observatory listening on http://127.0.0.1:52305
> Process finished with exit code 137

**Comment by alexander-doroshko** [comment]
@EasonPai New VM Service Protocol is used for debugging if 2 conditions are met:
-WebStorm 11+ or IntelliJ IDEA 15+
-Dart SDK 1.14+

To make sure that VM Service Protocol is used for debugging see Dart VM command line: there should be no **--debug:XXXX** flag. In your case it is there and it confirms that you need to update your IDE.

**Comment by EasonPai** [comment]
Thanks for the info, 
But it is frustrating that we can't use the version that we already bought to do the development.
Hope there will be some plugin or patch to help on this.

**Comment by alexander-doroshko** [comment]
@EasonPai [WebStorm 10](http://blog.jetbrains.com/webstorm/2015/03/webstorm-10-released/) was released on March 31, 2015. [Dart SDK 1.14](http://news.dartlang.org/2016/01/dart-1.html) was released **10 months later**, on 29 of January, 2016. At that moment WebStorm 11 was already out and was already able to debug via new protocol. You shouldn't expect old IDE to support new technologies.
