### ISSUE TITLE
Observatory data shouldn't be linked into the binary

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#24200]
The observatory data takes up a significant amount of space in the binary.  Instead of storing the data in the binary itself, we should store it in a separate file and read that file when we need the data.

Ideally, the embedder would be able to supply the path where the file is located because on Android its going to be in some wacky place.

**Comment by iposva-google** [comment]
Adam, how is it going to help if the data is separate from the binary?
As you mention the data is not touched in the binary when the Observatory is not used, so it is not being paged in unless it is needed, correct? The reason we do not have an external file is so we do have to go find it, regardless where you installed and are running from. Instead the Observatory resources are always available in the Dart binaries.

**Comment by iposva-google** [comment]
John just gave me background info... For deployment scenarios we should be able to remove the resources entirely. At the same time we should disable profiling, allocation stats, and all other related bookkeeping.

**Comment by abarth** [comment]
@iposva-google Yeah, we'd like to use the same binary for end-developers and in production.

**Comment by rmacnak-google** [comment]
2844eb86cac7358ccc6e638c3de41e293824098d
