### ISSUE TITLE
Implement assert() messages behind a flag in analyzer

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#24217]
This is the analyzer-specific issue for #24213. That issue has the details.

**Comment by stereotype441** [comment]
https://codereview.chromium.org/1309543011/ adds support to the analysis engine.  Once that has been reviewed and landed, we will need to make a separate (trivial) changes to analyzer_cli and analysis_server to add the flag.

**Comment by sethladd** [comment]
Thanks!

Should I open a new issue to track the other plumbing?

**Comment by munificent** [comment]
And you added tests. :metal:

**Comment by sethladd** [comment]
The DEP met today, and decided that the type annotation on the optional param should be String. Does the CL reflect that?

**Comment by stereotype441** [comment]
IIRC, the CL does reflect that.  However I can't verify right now since codereview.chromium.org appears to be down due to certificate errors.  I will check back tomorrow to confirm.

**Comment by sethladd** [comment]
Thanks Paul.

**Comment by stereotype441** [comment]
I just double-checked, and yes, the CL is consistent with the proposed spec change.  It requires the optional assertion message param to be assignable to String, or a warning is issued.

**Comment by sethladd** [comment]
Thanks @stereotype441 for checking!

**Comment by bwilkerson** [comment]
Messages in asserts is now enabled by default in analyzer (https://codereview.chromium.org/2557513008/).
