### ISSUE TITLE
analysis server is analyzing dart code in the `.pub/` directory

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24212]
Initially filed here: https://github.com/dart-atom/dartlang/issues/252.

It looks like the analysis server is analyzing code in the `.pub/` directory. When you run `pub get` on a project that imports the `intl` package, dart code is created in the `.pub/deps/debug/intl/`. This code has some analysis issues, and these are reported by the AS. Confusion ensues.

**Comment by sethladd** [comment]
Wow, good catch!

**Comment by devoncarew** [comment]
From experimentation, this happens when the code in the .pub dir changes but not on first scan.

**Comment by devoncarew** [comment]
FYI, we're seeing this one quite a bit.

**Comment by lukechurch** [comment]
@danrubel @bwilkerson: I've just run into this and it resulted in a good bit of head scratching. Could we look at what it would take to get it resolved? Any thoughts?

**Comment by bwilkerson** [comment]
My first guess would be to look at the file watching code. It looks like it's not ignoring files in directories whose name starts with a period.

**Comment by sethladd** [comment]
This is a really important issue that affects our customers, so optimistically adding to 1.13. Thanks for taking a look!

**Comment by stereotype441** [comment]
I've confirmed the bug.  Working on a fix.

**Comment by stereotype441** [comment]
Fix out for review: https://codereview.chromium.org/1372173004/

**Comment by sethladd** [comment]
Thanks!
