### ISSUE TITLE
Roll dartium to Chromium 44

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#24218]

**Comment by whesse** [comment]
Shouldn't this be labeled milestone 1.13?  @mit-mit was not aware of this work, and its impact on the release?

**Comment by mit-mit** [comment]
Also, what is the schedule for this work? We are just a week from cherry pick season.

**Comment by mit-mit** [comment]
Per leads meeting discussion, this is not in 1.13. Marking for 1.14.

**Comment by mit-mit** [comment]
Moving to 1.15 per leads discussion. The work is almost complete, and should land in a 1.15 dev channel release soon, however we want a bit more "bake time" before we put it in a stable release.

**Comment by mit-mit** [comment]
Can we close this? I believe this is in bleeding edge now, right? CC @whesse

**Comment by whesse** [comment]
Yes.  There is some further work, about the SDK and IDL generation, but a separate bug should be filed for that, and it won't be milestone 1.15.  I'll leave it to Terry to close this.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by mit-mit** [comment]
Closing this bug as the roll shipped in 1.15. @terrylucas @kevmoo can you open a new issue(s) tracking what remains in 1.16?

**Comment by terrylucas** [comment]
These are the Active Dartium 1.16 bugs
<https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aarea-dartium+milestone%3A1.16>
.

**Comment by mit-mit** [comment]
Excellent, thanks Terry!
