### ISSUE TITLE
Support a way to silence analyzer feedback per line/function/method/etc

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#24210]
Often in tests to test error paths, I'm writing something that I know is not analyzer clean on one line, or for a whole function. It would be great if the analyzer has a mechanism to silence the feedback from the analyzer for a line or function/method/class.

**Comment by johnmccutchan** [comment]
@sethladd

**Comment by sethladd** [comment]
We ran into this on dartdoc, too. We have purposefully broken code. We know there are warnings in there, but we won't want to be told about them.

**Comment by johnmccutchan** [comment]
@abarth FYI

**Comment by bwilkerson** [comment]
There is a mechanism (`// ignore:` comments) to suppress on a single line. Given how old this request is, I'm guessing that the current solution is sufficient. Please re-open if that's not the case.

**Comment by zoechi** [comment]
or `// ignore_for_file: ...`
