### ISSUE TITLE
Add field isFieldInitializer to dart:mirrors:ParameterMirror

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/sdk#24219]
For whatever reason,  is_field_initializer is not passed back along with other  parameter info from runtime/vm/parser.cc (Parser::ParseFunctionParameters) -> runtime/lib/mirrors.cc

Is there any reason it shouldn't be exposed in dart?

**Comment by seaneagan** [comment]
dupe of #16094 ?

**Comment by llamadonica** [comment]
Yep, my mistake. Didn't know what I was looking for until I started diving into the code.

**Comment by dgrove** [comment]
Duplicate of #16094 .
