### ISSUE TITLE
VM build is not incremental

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#24220]
How to reproduce the problem:
tools/build.py -mrelease runtime
tools/build.py -mrelease runtime

What is the expected output:
On first invocation: build output
On second invocation: nothing to do

What is the actual output:
First invocation: build output
Second invocation: 
```
make -j 32 BUILDTYPE=ReleaseIA32 runtime
  ACTION runtime_dart_runtime_gyp_build_observatory_host_deploy_observatory out/ReleaseIA32/observatory/deployed/web/index.html
  TOUCH runtime_dart_runtime_gyp_generate_snapshot_bin_host_generate_snapshot_bin.intermediate
  ACTION Generating /usr/local/google/home/ricow/src/hub_dart/sdk/out/ReleaseIA32/obj/gen/vm_isolate_snapshot_gen.bin /usr/local/google/home/ricow/src/hub_dart/sdk/out/ReleaseIA32/obj/gen/isolate_snapshot_gen.bin files. runtime_dart_runtime_gyp_generate_snapshot_bin_host_generate_snapshot_bin.intermediate
  ACTION Generating /usr/local/google/home/ricow/src/hub_dart/sdk/out/ReleaseIA32/obj/gen/snapshot_gen.cc file. out/ReleaseIA32/obj/gen/snapshot_gen.cc
  CXX(target) out/ReleaseIA32/obj.target/dart/gen/snapshot_gen.o
  CXX(target) out/ReleaseIA32/obj.target/run_vm_tests/gen/snapshot_gen.o
  LINK(target) out/ReleaseIA32/dart
  LINK(target) out/ReleaseIA32/run_vm_tests
  TOUCH out/ReleaseIA32/obj.target/runtime.stamp
rm runtime_dart_runtime_gyp_generate_snapshot_bin_host_generate_snapshot_bin.intermediate
```

**Comment by ricowind** [comment]
@iposva-google @johnmccutchan 
Ivan: because of the snapshot generation
John: Because of the observatory deploy (John, I see that you do a copy, you may need to explicitly touch the output file, the copy will not change the timestamp which is used to determine if we rerun)

**Comment by johnmccutchan** [comment]
I investigated the snapshot generation and there is a bug in how gyp generates Makefiles when a build rule has two outputs that will always trigger a rebuild.

**Comment by johnmccutchan** [comment]
Fix for both issues- https://codereview.chromium.org/1304953004/
