### ISSUE TITLE
runtime/vm/os_thread_linux.cc:221: error: pthread error: 16 (Device or resource busy)

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24222]
Appears to be flaky - possibly related to recent changes? @kodandersson @johnmccutchan 

FAILED: none-vm debug_x64 co19/LibTest/isolate/ReceivePort/skip_A01_t01
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
unittest-suite-success

stderr:
runtime/vm/os_thread_linux.cc:221: error: pthread error: 16 (Device or resource busy)

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/skip_A01_t01.dart
Took 0:00:03.665000

Short reproduction command (experimental):
    python tools/test.py -ax64 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 co19/LibTest/isolate/ReceivePort/skip_A01_t01

=== Failure summary:

FAILED: none-vm debug_ia32 service/pause_on_start_and_exit_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching out/DebugIA32/dart --trace-service --pause-isolates-on-start --pause-isolates-on-exit --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugIA32/packages/ --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/sdk/runtime/observatory/tests/service/pause_on_start_and_exit_test.dart --testee-mode
vm-service: Booting dart:vmservice library.
vm-service: Registering running isolates.
vm-service: Isolate pause_on_start_and_exit_test.dart$main-743971132 743971132 registered.
** Signaled to run test queries on 57502
Observatory listening on http://127.0.0.1:57502
vm-service: Dropping event of type PauseStart (pause_on_start_and_exit_test.dart$main-743971132)
vm-service: starting stream 'Isolate'
vm-service: starting stream 'Debug'
vm-service: starting stream '_Graph'
Isolate vm-service processing service request getVM
Isolate vm-service processed service request getVM in 84 us.
Running pause_on_start_and_exit_test.dart [1/1]
Getting stream...
Subscribing...
Subscribed.  Pause event is ServiceEvent(owner='isolates/743971132', kind='PauseStart')
Subscription cancelled.
Done waiting for pause event.
Isolate pause_on_start_and_exit_test.dart$main-743971132 processing service request getIsolate
Isolate pause_on_start_and_exit_test.dart$main-743971132 processed service request getIsolate in 1116 us.
Isolate pause_on_start_and_exit_test.dart$main-743971132 processing service request getIsolate
Isolate pause_on_start_and_exit_test.dart$main-743971132 processed service request getIsolate in 1131 us.
VM-VERBOSE: pause_on_start_and_exit_test.dart$main reloaded. pause event= ServiceEvent(owner='isolates/743971132', kind='PauseStart')
Resuming...
VM-VERBOSE: pause_on_start_and_exit_test.dart$main _onEvent ServiceEvent(owner='isolates/743971132', kind='Resume')
VM-VERBOSE: pause_on_start_and_exit_test.dart$main pause event ServiceEvent(owner='isolates/743971132', kind='Resume')
Isolate pause_on_start_and_exit_test.dart$main-743971132 processing service request resume
vm-service: Pushing event of type Resume to stream Debug (pause_on_start_and_exit_test.dart$main-743971132)
Isolate pause_on_start_and_exit_test.dart$main-743971132 processed service request resume in 60 us.
Hello
vm-service: Pushing event of type PauseExit to stream Debug (pause_on_start_and_exit_test.dart$main-743971132)
VM-VERBOSE: pause_on_start_and_exit_test.dart$main _onEvent ServiceEvent(owner='isolates/743971132', kind='PauseExit')
VM-VERBOSE: pause_on_start_and_exit_test.dart$main pause event ServiceEvent(owner='isolates/743971132', kind='PauseExit')
Received PauseExit
runtime/vm/thread.cc:157: error: expected: !isolate->HasMutatorThread()
** Killing script

stderr:
Unhandled exception:
Uncaught Error: Testee exited with -6
Stack Trace:
#0      _TestLauncher.launch.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:79:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1165)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#4      _Future._completeWithValue (dart:async/future_impl.dart:376)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugIA32/packages/ /mnt/data/b/build/slave/vm-linux-debug-ia32-be/build/sdk/runtime/observatory/tests/service/pause_on_start_and_exit_test.dart
Took 0:00:06.041000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 service/pause_on_start_and_exit_test

**Comment by iposva-google** [comment]
This particular bug is for the first failure in this report. I'll open a second one for the service test failure.

**Comment by iposva-google** [comment]
Second part of the report is split off into https://github.com/dart-lang/sdk/issues/24224

**Comment by kodandersson** [comment]
No core dump available and not observed recently, closing as obsolete.

**Comment by zoechi** [comment]
I get this in Docker (based on `google/dart`)
An application as simple as one that creates an UUID and prints it
