### ISSUE TITLE
dart2js bug or missed optimization in CPS type propagation

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#24228]
Ideally, we should be able to assert that when we transform a branch to a known target that the analysis has concluded that the other target is unreachable, by adding the asserts below to TransformingVisitor.visitBranch in cps_ir/type_propagation.dart.

``` dart
    if (boolifiedValue == AbstractBool.True) {
      assert(!analyzer.reachableContinuations.contains(falseCont));
      replaceSubtree(falseCont.body, new Unreachable());
      InvokeContinuation invoke = new InvokeContinuation(trueCont, []);
      replaceSubtree(node, invoke);
      push(invoke);
      return;
    }
    if (boolifiedValue == AbstractBool.False) {
      assert(!analyzer.reachableContinuations.contains(trueCont));
      replaceSubtree(trueCont.body, new Unreachable());
      InvokeContinuation invoke = new InvokeContinuation(falseCont, []);
      replaceSubtree(node, invoke);
      push(invoke);
      return;
    }
```

Unfortunately these asserts fail (try tests/co19/src/Language/14_Libraries_and_Scripts/13_Libraries_and_Scripts_A05_t02.dart for one example).

This is either just a bug in the analysis or a potential missed optimization.  Because the analysis thinks the unreachable branch is reachable, analysis results from that code are polluting the rest of the analysis.

**Comment by rakudrama** [comment]
Obsolete
