### ISSUE TITLE
VM: Failing (flaky) service test service/smart_next_test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24221]
Is this a known issue @johnmccutchan @rmacnak-google ?

=== Failure summary:

FAILED: none-vm debug_x64 service/smart_next_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching out/DebugX64/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/smart_next_test.dart --testee-mode
Observatory listening on http://127.0.0.1:42330
** Signaled to run test queries on 42330

Running smart_next_test.dart [1/27]
Breakpoint reached
Running smart_next_test.dart [2/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(57))
Running smart_next_test.dart [3/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Running smart_next_test.dart [4/27]
Breakpoint reached
Running smart_next_test.dart [5/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(55))
Running smart_next_test.dart [6/27]
next-async
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
Running smart_next_test.dart [7/27]
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Event: ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [8/27]
Checking we are at line 17
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(62))
Running smart_next_test.dart [9/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Running smart_next_test.dart [10/27]
Breakpoint reached
Running smart_next_test.dart [11/27]
Checking we are at line 18
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(67))
Running smart_next_test.dart [12/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Running smart_next_test.dart [13/27]
Breakpoint reached
Running smart_next_test.dart [14/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(74))
Running smart_next_test.dart [15/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Running smart_next_test.dart [16/27]
Breakpoint reached
Running smart_next_test.dart [17/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(72))
Running smart_next_test.dart [18/27]
next-async
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
Running smart_next_test.dart [19/27]
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Event: ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [20/27]
Checking we are at line 20
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(81))
Running smart_next_test.dart [21/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
Running smart_next_test.dart [22/27]
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Event: ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Breakpoint reached
Running smart_next_test.dart [23/27]
Checking we are at line 20
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(79))
Running smart_next_test.dart [24/27]
next-sync
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='Resume')
Running smart_next_test.dart [25/27]
VM-VERBOSE: smart_next_test.dart$main pause event ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Event: ServiceEvent(owner='isolates/721152444', kind='PauseBreakpoint')
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [26/27]
Checking we are at line 21
We are at Frame(_RootZone.runUnary zone.dart:token(8932))
** Killing script
Unexpected exception in service tests: Expected: <21>
  Actual: <1165>
 #0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      stoppedAtLine.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:223:5)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#5      _rootRunUnary (dart:async/zone.dart:910)
#6      _CustomZone.runUnary (dart:async/zone.dart:810)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#9      _Future._completeWithValue (dart:async/future_impl.dart:376)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#11     _rootRun (dart:async/zone.dart:903)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

stderr:
Unhandled exception:
Uncaught Error: Expected: <21>
  Actual: <1165>

Stack Trace:
#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      stoppedAtLine.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:223:5)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#5      _rootRunUnary (dart:async/zone.dart:910)
#6      _CustomZone.runUnary (dart:async/zone.dart:810)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#9      _Future._completeWithValue (dart:async/future_impl.dart:376)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#11     _rootRun (dart:async/zone.dart:903)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/smart_next_test.dart
Took 0:00:10.449000

Short reproduction command (experimental):
    python tools/test.py -ax64 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 service/smart_next_test

**Comment by johnmccutchan** [comment]
@fsc8000 Known issue. Thanks for filing.

**Comment by rmacnak-google** [comment]
Dup of #24176
