### ISSUE TITLE
dart:html.Document is missing createTextNode()

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#24235]
The appears to be no way to create a Text node for any document other than the global document.

**Comment by kulshekhar** [comment]
Here's a temporary solution for anyone who needs it:

```dart
import 'dart:html' as html;

html.Node createTextNode(String text) {
  return html.document.createDocumentFragment()
    ..appendText(text)
    ..firstChild;
}
```

**Comment by justinfagnani** [comment]
Why is this closed? There's still no createTextNode() method on document as there should be: https://developer.mozilla.org/en-US/docs/Web/API/Document/createTextNode

**Comment by matanlurey** [comment]
It is closed as stale since its been 3 years without a response.

It's unlikely this will be prioritized, and keeping the issue open indefinitely holds no value.

**Comment by kevmoo** [comment]
@justinfagnani – are you blocked by this on any of your current projects?

While I'm sympathetic to wanting to keep open all valid bugs, I tend to agree it's better to keep focus on bugs that are actually causing user pain NOW – or we have no way to prioritize our work.
