### ISSUE TITLE
Flaky assertion failure in service/pause_on_start_then_step_test

### ISSUE THREAD

**Issue by kodandersson** [dart-lang/sdk#24230]
I observed this only once locally, while preparing to commit db8e0e6423cfe842465e8397e6489fcd26deb4f2

FAILED: none-vm-checked debug_ia32 service/pause_on_start_then_step_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching out/DebugIA32/dart --trace-service --pause-isolates-on-start --pause-isolates-on-exit --error_on_bad_type --error_on_bad_override --marker_tasks=0 --ignore-unrecognized-flags --enable_asserts --enable_type_checks --package-root=out/DebugIA32/packages/ --enable-vm-service:0 /usr/local/google/home/koda/parmark4/sdk/runtime/observatory/tests/service/pause_on_start_then_step_test.dart --testee-mode
vm-service: Booting dart:vmservice library.
vm-service: Registering running isolates.
vm-service: Isolate pause_on_start_then_step_test.dart$main-970774403 970774403 registered.
** Signaled to run test queries on 34888
Observatory listening on http://127.0.0.1:34888
vm-service: Dropping event of type PauseStart (pause_on_start_then_step_test.dart$main-970774403)
vm-service: starting stream 'Isolate'
vm-service: starting stream 'Debug'
vm-service: starting stream '_Graph'
Isolate vm-service processing service request getVM
Isolate vm-service processed service request getVM in 55 us.
Running pause_on_start_then_step_test.dart [1/1]
Getting stream...
Subscribing...
Subscribed.  Pause event is ServiceEvent(owner='isolates/970774403', kind='PauseStart', time=2015-08-28 09:28:54.423)
Subscription cancelled.
Done waiting for pause event.
Isolate pause_on_start_then_step_test.dart$main-970774403 processing service request getIsolate
Isolate pause_on_start_then_step_test.dart$main-970774403 processed service request getIsolate in 1071 us.
Isolate pause_on_start_then_step_test.dart$main-970774403 processing service request getIsolate
Isolate pause_on_start_then_step_test.dart$main-970774403 processed service request getIsolate in 1101 us.
Stepping...
Waiting for PauseBreakpoint
** Killing script
Unexpected exception in service tests: 'package:observatory/src/service/object.dart': Failed assertion: line 1370 pos 16: '(pauseEvent == null) ||
               !event.timestamp.isBefore(pauseEvent.timestamp)' is not true. #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      Isolate._onEvent (package:observatory/src/service/object.dart:1370:16)
#2      VM._dispatchEventToIsolate (package:observatory/src/service/object.dart:695:15)
#3      _rootRunUnary (dart:async/zone.dart:910)
#4      _CustomZone.runUnary (dart:async/zone.dart:810)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#7      _DelayedData.perform (dart:async/stream_impl.dart:595)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#10     _rootRun (dart:async/zone.dart:899)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:903)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

stderr:
Unhandled exception:
Uncaught Error: 'package:observatory/src/service/object.dart': Failed assertion: line 1370 pos 16: '(pauseEvent == null) ||
               !event.timestamp.isBefore(pauseEvent.timestamp)' is not true.
Stack Trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      Isolate._onEvent (package:observatory/src/service/object.dart:1370:16)
#2      VM._dispatchEventToIsolate (package:observatory/src/service/object.dart:695:15)
#3      _rootRunUnary (dart:async/zone.dart:910)
#4      _CustomZone.runUnary (dart:async/zone.dart:810)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#7      _DelayedData.perform (dart:async/stream_impl.dart:595)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#10     _rootRun (dart:async/zone.dart:899)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:903)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --error_on_bad_type --error_on_bad_override --marker_tasks=0 --ignore-unrecognized-flags --enable_asserts --enable_type_checks --package-root=out/DebugIA32/packages/ /usr/local/google/home/koda/parmark4/sdk/runtime/observatory/tests/service/pause_on_start_then_step_test.dart
Took 0:00:07.266000

Short reproduction command (experimental):
    python tools/test.py --vm-options --marker_tasks=0 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 service/pause_on_start_then_step_test

[00:19 |  54% | +  818 | -    1]

**Comment by turnidge** [comment]
I fixed this.
