### ISSUE TITLE
After upgrading to 1.12.0-dev.5.10 "Dart Analysis" blinks / scans forever 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24238]
Check out my GIF (Statusbar in IJ) - It takes about 15 to 30 mins to analyze my project (I guess with all the samples...)
While it runs IJ becomes almost unusable, it slows down the whole program...

![dartanalysis](https://cloud.githubusercontent.com/assets/116654/9582400/6ef3fd7c-5005-11e5-8606-519c24870f8d.gif)

**Comment by alexander-doroshko** [comment]
You are right, blinking 'Dart Analysis' status in the IDE means exactly that the server scans all numerous pubspec.yaml-based projects and subprojects.

**Comment by MikeMitterer** [comment]
I switched back to IntelliJ IDEA (Cassiopeia) IU-141.2552.1
Build #IU-141.2552, built on August 27, 2015
JRE: 1.6.0_65-b14-462-11M4609 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple Inc.

Changed Dart to 1.12 and became even worse. I cleaned the cache and restarted IJ. It's scanning now since 2 hours!!!!!! on a i7 3.5 Ghz with 16 G of Ram...

**Comment by zoechi** [comment]
This might be a WebStorm issue. AFAIR WebStorm processes all files in all packages directories and symlinks and only afterwards checks for duplicates and excludes all the packages symlinks. If the directories were excluded first this scanning would probably be finished in a few seconds.
I might be totally wrong here, but I run into a similar situation with nested projects a few months ago. I don't know a good workaround. I didn't have too many sub-projects. AFAIR I canceled the WebStorm task and added the packages symlinks manually to the directory exclusion list.

**Comment by MikeMitterer** [comment]
Thanks! I just restarted the scan. Is the whole thing back to beta or what? Drives me crazy. Took me yesterday the whole afternoon and today the whole morning...

**Comment by MikeMitterer** [comment]
Adding exclude dirs by hand, moving "example" to "samples" because Analyzer has problems to recognize subprojects - really??? A fix encoded "--no-package-symlinks" in EAP 15 with no way back except switching to IJ 14 - Dart is really cool and I like it but these things make Dart look somehow immature @clayberg

**Comment by zoechi** [comment]
I guess this will also resolve itself when the packages symlinks are gone. Almost there :dancers:

**Comment by sethladd** [comment]
> EAP 15 with no way back except switching to IJ 14

I hope we can fix EAP 15 to not run with --no-package-symlinks. Tracking here: https://youtrack.jetbrains.com/issue/WEB-18006

**Comment by MikeMitterer** [comment]
Thanks!

**Comment by alexander-doroshko** [comment]
If I read this issue description correctly it is about bad Analysis Server performance when working with huge Dart project with numerous nested pubspecs. I'm afraid I do not understand how it related to the `–no-package-symlinks` flag.

**Comment by MikeMitterer** [comment]
Don't know - this is just where the whole problem started. In EAP 15 I upgraded to 1.12, made a pub update via IDE (no-package-symlink) and the result was the blinking "Dart Analysis". The project worked before I upgraded + pub updated.

**Comment by alexander-doroshko** [comment]
"Dart Analysis" progress is introduced in EAP 15. Before it Dart Analysis Server server did the same, but IDE didn't indicate anyhow its busy status. You simply had no clue that server is busy and that some server-based operations may not work or be slow until the server warms up. Indeed server is slow to warm up with huge projects and this is not related to the IDE.

Long indexing is a separate problem. If you do `pub get` not from the IDE and then open the project for the first time IDE scans each symlink individually. So if you have 1000 symlinks to the same file (that's what `pub get` does) IDE will scan it 1000 times. After scanning IDE will exclude all duplicates of `packages` folders and they will never be scanned again. Recommended way is to open project before calling `pub get` (while numerous `packages` not exist yet) and then run `pub get` from the IDE (pubspec context menu or right from the editor). In this case IDE excluded `packages` copies are excluded BEFORE scanning starts, so scanning doesn't happen.

I hope that some day symlinks will finally go away and all symlinks related problems will disappear.
