### ISSUE TITLE
.packages file approach breaks tooling 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24237]
When I first read the announcement for the new "packages approach" I thought there will be at least one packages folder for every project (in project root) But today I experienced that you removed the packages folder as a whole - not good. This breaks all possibilities to refer to "packages" 

Getting rid of all the symlinks is great but the current approach is to strict!

For example in my MDL/Dart lib I refer to assets from my mdl-packages: https://goo.gl/Qzlgtk 
` <link rel="stylesheet" href="packages/mdl/assets/styles/material.min.css">` Serving index.html fails with every webserver except pub serve. 

With the new approach every tool that is not aware of the Dart .packages file breaks. SASS, every local Webserver aso. The only way to work around it is to use transformers - really???? is this the future?  

This SCSS file for example: https://goo.gl/rAVYE5 - breaks. The solution would be to use an absolute path to Darts cache or to work with a relative path back to mdl-root...

**Comment by MikeMitterer** [comment]
Maybe it helps if pub could generate e.g. a resource folder where it links to package resources
I mean something like this:
![screenshot-1840](https://cloud.githubusercontent.com/assets/116654/9578370/868f1cd0-4fe9-11e5-977a-94a6faf0ff56.png)

This would solve at least the SASS problem. 

Other webserver than pub server still have the "transformer" problem. My "SiteGen" app watches some template files/folders, updates the web-folder and finally serves these files - without calling all the necessary transformers SiteGen breaks (at least the server-part)
https://goo.gl/v40K7F

**Comment by zoechi** [comment]
Currently this is a WebStorm/IntelliJ issue because WebStorm runs `pub get`/`pub upgrade` with the `--no-package-symlinks` option. If you run `pub get` from command line you get your `packages` folder back.

**Comment by alexander-doroshko** [comment]
I guess since Dart SDK 1.13 `no-package-symlinks` will be the only available mode and there will be no flags to enable old 'packages' symlinks generation. So I wouldn't say there are any issues at IDE side.

**Comment by zoechi** [comment]
This is why I added "Currently".
This seems this has changed again though. If I run `pub upgrade` (`Dart VM version: 1.13.0-edge.656bd5af8206dc46ce697aa94e9cd387d1d53382 (Fri Aug 28 14:33:40 2015) on "linux_x64"`) without any options the packages folder and symlinks are created. But I also think that a week or so ago there was no way to create the `packages` folder with 1.13. 
`pub help upgrade` doesn't list the `--[no-]package-symlinks` option but the option is recognized anyway.
Seems to need some clarification about the strategy from the Dart team but workarounds are available.

**Comment by sethladd** [comment]
Thanks for the feedback!

`--no-package-symlinks` is only for the very brave. Things will probably break if you use that flag today. We are working towards a world where that is the default, but we're not there.

`--no-package-symlinks` is not a visible user option, because we don't want users to accidentally start using it (if you are using it, you should really know what you are doing :)

> But today I experienced that you removed the packages folder as a whole - not good. This breaks all possibilities to refer to "packages"

This is why we don't advertise `--no-package-symlinks` except for tool vendors testing their tools.

> WebStorm/IntelliJ issue because WebStorm runs pub get/pub upgrade with the --no-package-symlinks option.

It shouldn't do that. We'll need to file a bug. For Dart 1.12, the default is to NOT use that flag.

Since this seems like a WebStorm issue, I'll close it here and open an issue for JetBrains.

**Comment by sethladd** [comment]
https://youtrack.jetbrains.com/issue/WEB-18006

**Comment by alexander-doroshko** [comment]
@sethladd This flag is used in WebStorm/IntelliJ IDEA Early Access releases only, I was sure that's fine to start using new features in EAPs, isn't it?

**Comment by sethladd** [comment]
@alexander-doroshko unfortunately, our other tools aren't ready to deal with no packages/ dir, so even the EAP shouldn't default to that flag on.

**Comment by alexander-doroshko** [comment]
Mike is saying that `serving index.html fails with every webserver except pub serve` and that SASS and SCSS fail.
Yes, I can disable .packages support in WebStorm and enable it back in few weeks when SDK 1.13 will be better, but how will this help to answer Mike's question?

**Comment by sethladd** [comment]
> but how will this help to answer Mike's question?

We'll need to figure that out.

**Comment by MikeMitterer** [comment]
@sethladd  + @alexander-doroshko I think we need at least one packages folder per project - ONE not all the symlinks but one in the root of the project. Otherwise its impossible for tools like SASS or a webserver (local for testing) to interact with Dart.

**Comment by sethladd** [comment]
cc @floitschG as I think he's looking at the issue
