### ISSUE TITLE
VM Service: Context is documented but not used

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24249]
The `Context` type and its corresponding `@Context` and `ContextElement` are documented, but not used anywhere in the public service protocol. In addition, it's not documented to inherit from `Object`, making it kind of confusing what the relationship between `@Context` and `Context` is.

**Comment by turnidge** [comment]
The closureContext field for Instance had the wrong type.  Also, yes, Context should extend Object.  Fixing.
