### ISSUE TITLE
VM Service: getObject doesn't work with removed breakpoints

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24247]
If a `Breakpoint` is added and later removed, the `getObject` function fails in an unexpected way (error code -32602, "invalid parasms") when passed its ID. I would expect instead a `Sentinel` indicating that the breakpoint is no longer valid, as per the `getObject` documentation.

**Comment by turnidge** [comment]
I'm going to make it return the Collected sentinel and clarify the documentation.
