### ISSUE TITLE
Regression of #22982: Isolate cannot send Map as message in certain conditions (AKA "object is a regular Dart Instance")

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#24243]
The Priority-High bug https://github.com/dart-lang/sdk/issues/22982 is back. 

I noticed the regression in one of my projects, tried running the isolate_message_bug test (provided in the original bug), and it fails in the same way as it did in 1.9.1.

**Comment by sethladd** [comment]
On the VM, and/or Dartium?

**Comment by filiph** [comment]
Both.

isolate_message_bug I only tested in Dartium. But I noticed the bug (assuming it's the same one) on the VM.

**Comment by filiph** [comment]
tried isolate_message_bug on the VM now – crashes

**Comment by sethladd** [comment]
Thanks for the head's up! Is it the repro case from the original https://github.com/dart-lang/sdk/issues/22982 issue?  (the .zip from the top of #22982)

cc @kodandersson

**Comment by filiph** [comment]
Yes

**Comment by filiph** [comment]
Oh, I should say that while before I could fix this by sending `new Map.from(map)` (instead of just `map`, see https://github.com/dart-lang/sdk/issues/22982#issuecomment-108462503), this doesn't resolve the issue now.

If it helps, I recursively walked through the Map before sending it and looked at each element's runtimeType.

    _InternalLinkedHashMap
    _InternalLinkedHashMap<String, Map<String, Object>>
    _InternalLinkedHashMap<String, Object>
    _InternalLinkedHashMap<String, String>
    bool
    int
    List
    Null
    String

Is it possible that _InternalLinkedHashMap somehow looks like a non-primitive type?

For reference, this is the result of the same recursive walk when run in Chrome (compiled to JS) — where this works:

    bool
    int
    JSArray
    JsLinkedHashMap
    JsLinkedHashMap<String, Map<String, Object>>
    JsLinkedHashMap<String, Object>
    JsLinkedHashMap<String, String>
    Null
    String

**Comment by kodandersson** [comment]
@filiph When you say "tried isolate_message_bug on the VM", what code did you run exactly? The application uses dart:html, so it can't run on the standalone VM.

**Comment by filiph** [comment]
@kodandersson I made a minimal edit to the code so that it doesn't use dart:html. So I meant Dart VM proper (command line).

Can't attach files to github issues, so here:
https://drive.google.com/file/d/0BzP0HrbVsp3KbWowLWR2YmxfY1E/view?usp=sharing

**Comment by sethladd** [comment]
Thanks @filiph !

**Comment by kodandersson** [comment]
The error is triggered by any map that has (recursively) a Map type as a type argument. The snapshot writer fails to serialize the class object for Map. I'm not sure whether anything has changed recently w.r.t. this.

**Comment by kodandersson** [comment]
It's actually not specific to Map. The same issue arises for a message constructed by "new List<List<int>>()". It only seems to happen for spawnUri, though.

**Comment by kodandersson** [comment]
@a-siva Did something change recently w.r.t. serialization of type arguments?

**Comment by a-siva** [comment]
https://codereview.chromium.org/1343213002/ was submitted to fix this issue.
