### ISSUE TITLE
No code completion when typing an annotation without a class below it

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24240]
From https://github.com/dart-atom/dartlang/issues/100

**Comment by jwren** [comment]
@danrubel Question: what kinds of completions are missing that Seth is looking for?  Not recorded in the dart-atom/dartlang#100 link, and it is not obvious after playing with this sample code:

```
class Blah {
  final int _a, _b, _c;
  const Blah(this._a, this._b, this._c);
}

int one() => 1;
int two() => 2;
int three() => 3;

@Blah(1,1,1)
class A {}

@Blah // <--- can complete "Blah here"
```

**Comment by danrubel** [comment]
I consider this fixed. Please reopen if you find a case where this does not work.
