### ISSUE TITLE
VM Service: startTime fields are a doubles, should be integers

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24245]
The `startTime` fields of `VM` and `Isolate` are documented as being `int`s but are being emitted with trailing `.0`s that cause them to be parsed as doubles instead, which can break code that was expecting ints.

This seems to have been introduced at some point after `1.12.0`.

**Comment by turnidge** [comment]
John, should we update the documentation here?  We always return startTime as a double so that it works when observatory is compiled with dart2js, right?

**Comment by nex3** [comment]
Other timestamp fields are returned as ints, FWIW.

**Comment by johnmccutchan** [comment]
All timestamps transmitted over the service protocol must be sent as the double value of milliseconds since the epoch. It's possible we have some documentation and/or code bugs around handling of timestamps.

**Comment by nex3** [comment]
Now that pids are represented as ints, how will this work with dart2js?

**Comment by johnmccutchan** [comment]
@nex3 I'm not sure I understand the question. Dart has both integers and doubles and the service protocol now encodes data as the natural type (e.g. integer for pids and timestamps).

**Comment by nex3** [comment]
My understanding was that JS couldn't represent the full gamut of 64-bit integers in its native number type, so numbers that could be 64-bit on some platform (such as PIDs) were sent as strings.

**Comment by johnmccutchan** [comment]
@nex3 Got it. In practice pids don't exceed 16-bits. JavaScript can represent 53-bit integers losslessly. Think about the last time you had to kill a process with a pid as big as 9.0071993e+15.

For reference:

On Linux, if you configure away from the default, the limit is 2^22
On Mac the limit is "99999"
On Windows the limit is 2^32
