### ISSUE TITLE
dartdoc.bat has a wrong variable expansion and fails to run dartdoc

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/sdk#24252]
https://github.com/dart-lang/sdk/blob/1.12.0/sdk/bin/dartdoc.bat#L17

In the referenced line, `$BIN_DIR` should have been `%BIN_DIR%`. Due to this issue, `dartdoc.bat` won't run `dartdoc` properly.

**Comment by sethladd** [comment]
Sorry about that. Thanks for filing!

@keertip @whesse is there a way our Windows bots can run this and other .bat files during a build, to test they are correct?

cc @mit-mit

**Comment by sethladd** [comment]
Related: https://github.com/dart-lang/sdk/issues/24263

**Comment by keertip** [comment]
Thanks for the report!

**Comment by keertip** [comment]
fixed in https://codereview.chromium.org/1318603006/

**Comment by sethladd** [comment]
Can we roll this out in a 1.12.1 release?

**Comment by keertip** [comment]
Was just filing the issue! #24265

**Comment by sethladd** [comment]
> Was just filing the issue!

You :guitar:
