### ISSUE TITLE
Code completion feature request: suggest variable/parameter names based on its type

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24254]
When you write Java code in IntelliJ IDEA and want to declare variable or parameter IDE suggests var name based on var type:
![image](https://cloud.githubusercontent.com/assets/4499789/9601550/0436110e-50ab-11e5-80b0-66d8fc812d25.png)
Would be great to have the same functionality for Dart.

(originally filed to WebStorm issue tracker: [WEB-14343](https://youtrack.jetbrains.com/issue/WEB-14343))

**Comment by jwren** [comment]
https://codereview.chromium.org/1916893002/

**Comment by jwren** [comment]
https://codereview.chromium.org/1916213002/
