### ISSUE TITLE
pub upgrade generates wrong symlink in sample if sample has it's own pubspec.yaml

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24251]
I think there is still a problem in Analyzer - it has problems with standalone samples. You can see here what I mean with "standalone": https://goo.gl/qeb42u Each sample lives in it's own universe with it's own pubspec.yaml. The only connection to it's parent lib is through something like this: https://goo.gl/R2VqcZ

I borrowed this idea from the Angular guys and it's much more flexible than the default way. (default way = share base pubspec with sample pubspec)

Today I switched back to IntelliJ IDEA (Cassiopeia) IU-141.2552.1
Build #IU-141.2552, built on August 27, 2015
JRE: 1.6.0_65-b14-462-11M4609 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple Inc.
(back from IJ 15 EAP)

and made a pub upgrade for my MDL/Dart lib and it generated a package for every sample back to it's parent - this is wrong if the sample has it's own pubspec.yaml!

I think this problem is somehow related to #24238

![screenshot-1841](https://cloud.githubusercontent.com/assets/116654/9597668/636a6a0c-5084-11e5-8342-75c77b5b3e2d.png)

**Comment by zoechi** [comment]
Sub-projects are just not supported by pub. This is known behavior and they don't intend to change it.  
A workaround is to not name the folder `example` (nor like any other of the known pub top-level directories). `example_` works well for me.
I guess this will become a non-issue anyway when the `packages` folder and symlinks are gone.

**Comment by zoechi** [comment]
See for example #23296

**Comment by MikeMitterer** [comment]
Thanks @zoechi - I'll try your approach. I'm happy if it works but I find the solution still annoying.  The rule should be not so complicated to implement. If a project has it's own pubspec treat it as extra project. 

I'm not sure if it's possible to get rid of the packages folder at all. I think we need one but only ONE packages folder per project. Otherwise it becomes impossible for other tools like e.g. SASS to work with dart libs. Or take a simple webserver - it fails with the current (1.12) .packages approach. This approach needs transformers - if you can't use a transformer you will fail.

**Comment by zoechi** [comment]
@MikeMitterer tell me about it ;-). My current approach (`example_` directory) works well enough though and I'm satisfied, but yes, it's not perfect. 
Again I'm pretty sure this issue will be solved when the packages symlinks are gone, even when a `packages` directory per project remains (which I hope won't be necessary).

**Comment by MikeMitterer** [comment]
;-) I cross my fingers an hope the best! In the meantime I moved my example to samples and started a new indexing session...
