### ISSUE TITLE
Smarter quick fix to add import statement for 3rd party package

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24257]
Notice that there are 2 different quick fixes to add different imports that would make `PathException` class available in the current file:
![image](https://cloud.githubusercontent.com/assets/4499789/9602952/80eb509c-50b5-11e5-93e2-b00861426c13.png)
Suggestion to import `package:path/path.dart` looks good, but not sure about suggestion to import `package:path/src/path_exception.dart`.
[Pub Package Layout Conventions](https://www.dartlang.org/tools/pub/package-layout.html) say that `you should never import from another package’s lib/src directory. Those files are not part of the package’s public API`. I think that if both 'public' and 'not public' import can resolve the problem Quick Fix should suggest only public one.

Related case is for class like `ParsedPath`. It is not a part of public API according to Layout Conventions and can only be made accessible by importing `package:path/src/parsed_path.dart`.
![image](https://cloud.githubusercontent.com/assets/4499789/9603045/72ee720c-50b6-11e5-8269-a812cdaacd60.png)
The question here is whether Quick Fix should suggest not-public URI to import or suggest nothing at all.

**Comment by bwilkerson** [comment]
One other question comes to mind. Should we be assuming that the user intends to follow the pub conventions? If so, we should make such suggestions when within the same package, but not when we're within a different package.

**Comment by scheglov** [comment]
Well, I don't know.
I like the idea of importing only API libraries.
But there are two problems.

1. We still want to suggesting importing non-API in the same package.

2. Some packages don't have enough public API, for example `analyzer` - almost everything is in `src/generated`. I'm not sure if this is just an unfortunate exception or something what happens pretty often. Maybe we still want to suggest them, but with lower priority.

  OTOH, if the *same* element is exported from both API and non-API libraries, we don't want to suggest non-API ones.

**Comment by bwilkerson** [comment]
> OTOH, if the same element is exported from both API and non-API libraries, we don't want to suggest non-API ones.

Except, sigh, for analyzer. There are some "public" libraries (in quotes because I don't think we really want them to be public) that re-export names from "private" libraries (in quotes because they ought to be part of the public API), and I never want to import from the public libraries, even from another package. But again, that's probably because analyzer is a mess (um, I mean "unfortunate exception" :-).

But we do want to be careful about making it hard for users to work around poorly structured third party packages.

**Comment by srawlins** [comment]
"Adding imports" features have changed a lot in a few years, meaning we've mostly improved it, supported lint configuration, and supported conventions. I think we generally suggest the right import. Closing.
