### ISSUE TITLE
Code completion with generic type and extends

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24255]
Sample code:

```
class Foo {
  String name;
}

class Bar<T extends Foo> {
    getName(T foo) {
      return foo.n<caret>;
    }
}
```

Problem: `name` is not suggested by the code completion at `<caret>` position. `T` is known to extend `Foo`, so properties of `Foo` are expected to be suggested.

(originally filed to WebStorm issue tracker: [WEB-13973](https://youtrack.jetbrains.com/issue/WEB-13973))

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/190723
