### ISSUE TITLE
Create a cross-mips compiler, instead of compiling inside a debian chroot on mips hardware

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24253]
Our mips testers are slow, because they both build and test, and they also don't use the toolchain our customers use.

Switch the setup to cross-compile on linux, using their toolchain, and then test that sdk on our mips hardware.

**Comment by zanderso** [comment]
I was wondering if it might be possible to increase the priority of this a little? At some point our customers will want to use a newer version of the VM. It would be nice to be able to tell them with confidence that it is safe to upgrade. @sgjesse @iposva-google

**Comment by whesse** [comment]
We can boost it a little, but it will still be months before it happens, I think.  The existing mips builders should start running tests again soon, as I have been fixing the problems with them today.  So the only differences will be between their compilation toolkit and the debian gcc make, which hopefully shouldn't be many.

**Comment by athomas** [comment]
No more mips.
