### ISSUE TITLE
Deferred import fails in Polymer app when run on Google App Engine local server

### ISSUE THREAD

**Issue by rillomas** [dart-lang/sdk#24269]
I'm getting the following error in Dartium when I run a small Polymer app in Google App Engine local server (goapp) with Go + Dart.

	 Exception: Uncaught Error: The null object does not have a getter 'uri'.

	NoSuchMethodError: method not found: 'uri'
	Receiver: null
	Arguments: []
	Stack Trace:
	#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
	#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
	#2      InitializationCrawler._readLibraryDeclarations (package:initialize/src/mirror_loader.dart:103:36)
	#3      InitializationCrawler._readLibraryDeclarations (package:initialize/src/mirror_loader.dart:104:7)
	#4      InitializationCrawler.run (package:initialize/src/mirror_loader.dart:53:5)
	#5      loadInitializers (package:initialize/src/mirror_loader.dart:16:74)
	#6      run (package:initialize/initialize.dart:27:24)
	#7      run.<run_async_body> (package:web_components/src/mirror_initializer.dart:26:11)
	#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
	#9      dirtyCheckZoneSpec.wrapCallback.<anonymous closure> (package:observe/src/dirty_check.dart:111:15)
	#10     dirtyCheckZoneSpec.wrapCallback.<anonymous closure> (package:observe/src/dirty_check.dart:111:15)
	#11     _rootRun (dart:async/zone.dart:904)
	#12     _CustomZone.run (dart:async/zone.dart:803)
	#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
	#14     _microtaskLoop (dart:async/schedule_microtask.dart:43)
	#15     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
	#16     _ScheduleImmediateHelper._handleMutation (dart:html:42567)

I've tracked down the error which seems to be related with deffered loading, because when I disable deferred import, the code works without any errors.

I'm using the following environment
 - Windows 10 Pro x64
 - appengine SDK 1.9.25 for windows/amd64
 - Dart 1.12.0
 - Dartium 1.12.0
 - Polymer 0.16.3+3

The whole project's code can be found at https://github.com/rillomas/intl_test/tree/dc02cdcabeaa3382e252eddbad9bce1e64c549c5 .

I wasn't quite sure where to post this issue (Dartium? Polymer.dart? App Engine?), so sorry if this repo is inappropriate.

**Comment by zoechi** [comment]
Deferred loading is not yet supported in Polymer.
See dart-lang/polymer-dart#79

**Comment by rillomas** [comment]
The deferring code was originally generated by intl.dart. (example https://github.com/rillomas/intl_test/blob/44fb1dc06fb78cae900a3d5650b416f84f7bc178/web/lib/messages/messages_all.dart)
Does that mean I can't use intl.dart with Polymer.dart?
Plus, the deferred code use to work on previous versions of intl.dart + Polymer.dart.

**Comment by zoechi** [comment]
I guess "not supported deferred in polymer" is only for loading elements but should work for plain Dart source. Sorry for the confusion.

**Comment by jakemac53** [comment]
I wasn't able to repro this in `pub serve` or a local server. Seems like it must be a weird interaction with the Google App Engine local server? If you provide more info about how I could repro this using that server then I can debug further.

**Comment by rillomas** [comment]
I tried to reproduce the error on a different machine (Windows 7 x64), and it's not reproducing...
Might have been some sort of environment related problem? Hmm weird. I had the same problem on this Win7 machine two days ago.
I'll check a bit more and close this issue if it was a false alarm. Sorry for the confusion guys.

**Comment by rillomas** [comment]
The error seems to have been related to an incomplete pub get. The problem reproduced on a different project, and after I deleted all `packages` and `.packages` files/directories and ran `pub get` again, it worked.

**Comment by madsager** [comment]
I'll close this issue for now. If you manage to reproduce problem with having to kill 'pub get' and getting into an inconsistent state, could you file a separate bug report on the dart-lang/pub repo? Thanks for the report!
