### ISSUE TITLE
Layout test failure in inspector/evaluate-in-console

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24268]
A recent change to the VM makes the webkit layout test dart/inspector/evaluate-in-console fail.
For some reason, the class of the receiver in a thrown exception has changed from 'Test' to '`K2'.
Also, there is an "Observatory listening" message that is unexpected.

It looks like it is the change https://codereview.chromium.org//1322043002 that has caused this error.

The status file for these tests is at http://src.chromium.org/blink/branches/dart/2171_3/dartium/LayoutTests/TestExpectations

A new status line would have to be added at the top of the file, this would have to be committed (I think that this SVN repository is still writable - the main chromium branches became read-only a year ago), and the new revision needs to be set as "dartium_webkit_revision" in tools/deps/dartium.deps/DEPS.

The text diff between the expected and actual results is:
--- /mnt/data/b/build/slave/dartium-lucid64-inc-be/build/src/webkit/Release/layout-test-results/dart/inspector/evaluate-in-console-expected.txt
+++ /mnt/data/b/build/slave/dartium-lucid64-inc-be/build/src/webkit/Release/layout-test-results/dart/inspector/evaluate-in-console-actual.txt
@@ -1,3 +1,5 @@
+Observatory listening on http://127.0.0.1:42624
+CONSOLE INFO: Observatory listening at http://127.0.0.1:48570/
 CONSOLE MESSAGE: Hello Instance of 'Window'
 CONSOLE MESSAGE: foo
 
@@ -12,10 +14,10 @@
 test.foo = 3 = 3
 test.foo = 3
 test.somePropertyThatDoesntExist = Uncaught Unhandled exception:
-Class 'Test' has no instance getter 'somePropertyThatDoesntExist'.
+Class '` K2' has no instance getter 'somePropertyThatDoesntExist'.
 
 NoSuchMethodError: method not found: 'somePropertyThatDoesntExist'
-Receiver: Instance of 'Test'
+Receiver: Instance of '` K2'
 Arguments: []
 #0      Object._noSuchMethod (DART_CORE_LIBRARY_SOURCE_LOCATION)
 #1      Object.noSuchMethod (DART_CORE_LIBRARY_SOURCE_LOCATION)
@@ -23,10 +25,10 @@
 #3      handleMessage (FILE_SOURCE_LOCATION/evaluate-in-console.dart:13:5)
 test.toString() = "<Test instance with instanceField = new value>"
 test.toString(1) = Uncaught Unhandled exception:
-Class 'Test' has no instance method 'toString' with matching arguments.
+Class '` K2' has no instance method 'toString' with matching arguments.
 
 NoSuchMethodError: incorrect number of arguments passed to method named 'toString'
-Receiver: Instance of 'Test'
+Receiver: Instance of '` K2'
 Tried calling: toString(1)
 Found: toString()
 #0      Object._noSuchMethod (DART_CORE_LIBRARY_SOURCE_LOCATION)

**Comment by whesse** [comment]
@sgmitrovic

**Comment by sgmitrovic** [comment]
Fixed in df29a93b0dfd
