### ISSUE TITLE
dart2js: isolates in minified mode

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24266]
Users have reported that messages sent between isolates appear to break if both isolates are compiled in minified mode.

We are still working on getting a repro to clarify the issue. We believe the message only contains the serializable types, but I'm not certain at this time that we are validating this in the isolate library (It may be that we are not complaining if Dart objects are sent on the message).

**Comment by sigmundch** [comment]
update: it appears their issue was that they were using `--trust-type-annotations --trust-primitives`. We should test and make sure isolates don't break when using those flags.

**Comment by sethladd** [comment]
Thanks for digging in!!
