### ISSUE TITLE
Submit DEP 034 to TC52

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24262]
DEP 34 has been approved. Please put under consideration in TC52.

https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Accepted/0034%20-%20Less%20Restricted%20Mixins/proposal.md

**Comment by a14n** [comment]
conflict : _DEP 034_ in title vs. _DEP 28_ in description.

**Comment by mit-mit** [comment]
My bad, this is indeed for 34. Updated.

**Comment by mit-mit** [comment]
Not required to ship 1.13, removing release value.

**Comment by anders-sandholm** [comment]
As of the 4th edition of Ecma 408 (Dec'15) this now part of the standard.
http://www.ecma-international.org/publications/standards/Ecma-408.htm
