### ISSUE TITLE
Analyzer warning not very helpful when missing async on a method

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24264]
The following code

```
foo() async => 42;
main() {
  print(await foo());
}
```

is missing the async keyword on the main method. However, the Analyzer warning is not very helpful, it just says [`Undefined name 'await'`](https://dartpad.dartlang.org/557c783c629581b0e5c0)

It would be great if we could be more specific and point the user towards the easy resolution to this.

**Comment by srawlins** [comment]
Should this be wrapped into #24375?

**Comment by bwilkerson** [comment]
The error message has been improved and a quick fix added, so I'm going to close this.
