### ISSUE TITLE
Please merge revision fe5550e934591380f7bb7c926f6f8dc7dc16f199 into stable channel

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#24265]
@ricowind @whesse @mit-mit @kasperl

fixes issue #24252 , dartdoc.bat from the sdk/bin does not work.

EXAMLE: fe5550e934591380f7bb7c926f6f8dc7dc16f199

**Comment by whesse** [comment]
Merged in version 1.12.1.
