### ISSUE TITLE
it would be nice to be able to show a file's library name as part of the outline view

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24279]
The `outline` event includes the file path and the initial, root `Outline` element. It would be nice to also be able to show the library name for the current file (if it has one).

@bwilkerson @scheglov

**Comment by bwilkerson** [comment]
This doesn't sound very interesting to me. I can't think why anyone would want to see the library name. By convention it's effectively the relative path to the file, so it doesn't add any information. (And I expect that many libraries will stop having a name now that it's no longer a warning to import multiple unnamed libraries.)

Are you getting user requests for this feature? If so, do you know what the motivation it?

**Comment by devoncarew** [comment]
It's nice for the outline view to have a title, and nicer still if we can use the symbolic name for the resource. For pubspec files, this would be the package name. For dart files, this would be the library name (if it has one). I agree that some teams don't use the library name feature, but those teams are still in the minority.

Instead of this guy:

<img width="265" alt="screen shot 2015-09-02 at 5 00 39 pm" src="https://cloud.githubusercontent.com/assets/1269969/9647632/3e6b3be4-5194-11e5-9455-6ceed69cf472.png">

I'd like to be able to show:

<img width="103" alt="screen shot 2015-09-02 at 5 00 51 pm" src="https://cloud.githubusercontent.com/assets/1269969/9647634/46673096-5194-11e5-926a-ccf5558bac18.png">

**Comment by bwilkerson** [comment]
And presumably fall back to the file name if there is no library name?

**Comment by devoncarew** [comment]
I like having it empty if the user didn't supply any. That might be interesting info to the client. If it's always populated with something, the client won't know if the user did or didn't use a library directive.

**Comment by scheglov** [comment]
@devoncarew What do you want to have if it is a part of a library? Nothing?
Should we have separate `libraryName` and `partOfLibraryName` fields?

**Comment by devoncarew** [comment]
Separate would make sense, although I'm less concerned with a high fidelity experience for parts. Can parts be parted into multiple libraries? Nothing would be ok; `partOfLibraryName` would also work.

**Comment by bwilkerson** [comment]
> Can parts be parted into multiple libraries?

Unfortunately, yes.

**Comment by clayberg** [comment]
So, what is the consensus here? It sounds like an easy thing to provide.

**Comment by scheglov** [comment]
OK, I will take it back and implement.

**Comment by scheglov** [comment]
DAS spec change.
https://codereview.chromium.org/1375163003/

**Comment by scheglov** [comment]
DAS implementation of the new spec.
https://codereview.chromium.org/1380103005

**Comment by scheglov** [comment]
Done.

**Comment by devoncarew** [comment]
Thanks! This made it into the latest dev sdk:

<img width="242" alt="screen shot 2015-10-08 at 11 28 49 am" src="https://cloud.githubusercontent.com/assets/1269969/10375921/f37c9a5a-6daf-11e5-932b-3c7e1075a3a2.png">

<img width="240" alt="screen shot 2015-10-08 at 11 29 40 am" src="https://cloud.githubusercontent.com/assets/1269969/10375922/f37d333e-6daf-11e5-928b-9f8b63e67482.png">

**Comment by scheglov** [comment]
Nice!
