### ISSUE TITLE
outline view first item always has its offset set to zero

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24277]
When getting a tree of outline items for a dart file, the first item in the file always has its offset set to 0. We sync the outline view UI to the file selection using this info. This means that whenever the user is in the first ~20 ish lines of a file, we indicate to them that they are in the first item. It often actually starts 10-20 lines below the first line.

**Comment by devoncarew** [comment]
@scheglov, from our discussion in the office

**Comment by scheglov** [comment]
https://codereview.chromium.org/1325143003
