### ISSUE TITLE
NonExistingSource exception during sendAnalysisNotificationNavigation

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24272]
From IntelliJ logs...

Dart analysis server, SDK version 1.11.1, server version 1.7.0, error: UnsupportedOperationException: /home/<username>/<....>/server.dart does not exist. null
#0 NonExistingSource.encoding (package:analyzer/src/generated/source.dart:344)
#1 CompilationUnitElementImpl.identifier (package:analyzer/src/generated/element.dart:1410)
#2 ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/generated/element.dart:3138)
#3 ElementImpl.location (package:analyzer/src/generated/element.dart:2768)

#4 DartUnitNavigationComputer._addRegion (package:analysis_server/src/computer/computer_navigation.dart:52)
#5 DartUnitNavigationComputer._addRegionForNode (package:analysis_server/src/computer/computer_navigation.dart:75)
#6 _DartUnitNavigationComputerVisitor.visitSimpleIdentifier (package:analysis_server/src/computer/computer_navigation.dart:218)
#7 SimpleIdentifier.accept (package:analyzer/src/generated/ast.dart:16160)
#8 AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:2937)
#9 ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4235)
#10 RecursiveAstVisitor.visitClassDeclaration (package:analyzer/src/generated/ast.dart:14574)
#11 ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4171)
#12 _DartUnitNavigationComputerVisitor.visitCompilationUnit (package:analysis_server/src/computer/computer_navigation.dart:127)
#13 CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4779)
#14 DartUnitNavigationComputer.compute (package:analysis_server/src/computer/computer_navigation.dart:32)
#15 sendAnalysisNotificationNavigation.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:137)
#16 _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:188)

#17 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:152)
#18 _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:186)
#19 sendAnalysisNotificationNavigation (package:analysis_server/src/operation/operation_analysis.dart:135)
#20 _DartNavigationOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:346)
#21 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:731)

**Comment by zoechi** [comment]
Looks a bit like https://youtrack.jetbrains.com/issue/WEB-18020#comment=27-1106083

**Comment by alexander-doroshko** [comment]
No, I don't think they are related.
Stack trace pasted here is an unexpected error reported by the server.
Error reported by Mike is sort of 'expected', it is reported by a different mechanism and IDE won't rethrow them any more.

**Comment by scheglov** [comment]
I cannot imagine how it could be possible to have a ClassDeclaration in a NonExistingSource.
