### ISSUE TITLE
Return empty list of suggestions if content changes after completion was requested

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24271]
Dart analysis server, SDK version 1.12.0-dev.5.1, server version 1.9.0, FATAL error: RangeError: Value not in range: 1582
#0 _StringBase.substring (dart:core-patch/string_patch.dart:365)
#1 DartCompletionRequest.filterText (package:analysis_server/src/services/completion/dart_completion_manager.dart:334)
#2 _ImportedSuggestionBuilder._addTopLevelSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:247)
#3 _ImportedSuggestionBuilder._addSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:235)
#4 _ImportedSuggestionBuilder.computeFull.addSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:110)

**Comment by danrubel** [comment]
It appears that the content was updated between the time we received the completion request and the time that resolution was complete. I'll add guard code that returns an empty set of suggestions when this situation occurs.

**Comment by scheglov** [comment]
Is this the same issue or a new one?

```
Dart analysis server, SDK version 1.14.0-dev.1.0, server version 1.12.0, error: Failed to handle completion domain request: {clientRequestTime: 1448432999366, params: {file: /Users/apple/Workspace/finchos/ui2/src/index.dart, offset: 1}, method: completion.getSuggestions, id: 9}
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:368)
#1      DartCompletionRequest.filterText (package:analysis_server/src/services/completion/dart_completion_manager.dart:398)
#2      _ImportedSuggestionBuilder._addTopLevelSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:254)
#3      _ImportedSuggestionBuilder._addSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:242)
#4      _ImportedSuggestionBuilder.computeFull.addSuggestions (package:analysis_server/src/services/completion/imported_reference_contributor.dart:117)
#5      _rootRunUnary (dart:async/zone.dart:914)
#6      _CustomZone.runUnary (dart:async/zone.dart:810)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#9      _Future._completeWithValue (dart:async/future_impl.dart:376)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#11     _rootRun (dart:async/zone.dart:907)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by danrubel** [comment]
Looks like the same issue to me.

**Comment by bwilkerson** [comment]
@danrubel Any ideas on how to track this down and fix it?

**Comment by lukechurch** [comment]
This is happening a lot. LMK if more data can help.

**Comment by danrubel** [comment]
I'll dig and see what I can find and fix.

**Comment by bwilkerson** [comment]
Thanks! Or if you don't have time right now feel free to add pointers to this issue and leave it for someone else. I know this isn't necessarily your highest priority (though your help *is* greatly appreciated).
