### ISSUE TITLE
Request to analyze only certain packages from the command line

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24273]
Hi,

Would it be possible to add a command-line argument for the analyzer, to let us say, effectively, "please analyze packages, but ONLY these packages"

Right now, we can use --package-warnings, but that pulls in too many errors/warnings from packages we know are violating the analyzer.

Ideally, something like: --package-warnings=foo,bar would be very helpful!

**Comment by bwilkerson** [comment]
That sounds possible, but could you move this issue over to the analyzer_cli repository? (Someday I need to figure out how to do that myself.)

**Comment by sethladd** [comment]
search for "github issue mover" and you'll land on https://github-issue-mover.appspot.com/

Meanwhile, I'll do it for this one.

Thanks for the review.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/analyzer_cli#58
