### ISSUE TITLE
Request to add an option to enable assert + message support in analysis server

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24276]
Following on the work from https://github.com/dart-lang/sdk/issues/24217

We'd love a way for a user to opt-in to support for assert + message in Analysis server.

Thanks!

**Comment by bwilkerson** [comment]
One possible approach for this would be to add the flag via the .analysis_options file.

**Comment by sethladd** [comment]
I'm a fan.

**Comment by stereotype441** [comment]
Note: `FixProcessor._inferUndefinedExpressionType` will need to be modified so that fixes like "create local variable" will infer the correct type for the assertion expression.

**Comment by bwilkerson** [comment]
Messages in asserts is now enabled by default in analyzer (https://codereview.chromium.org/2557513008/).

**Comment by sethladd** [comment]
Thanks for the update!
