### ISSUE TITLE
Pub: provide better conflict feedback

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/sdk#24282]
I just had to troubleshoot a version incompatibility issue posted to my package [here](https://github.com/dart-bridge/bridge/issues/5).

When trying to depend on both the most recent versions of `bridge` and `di`, this message is provided ny pub:

```
Package dotenv has no versions that match >=0.1.3+1 <0.2.0 derived from:
- bridge 1.0.0-alpha4 depends on version ^0.1.3+1
```

When really, this is not the issue at all. Turns out (after some awkward troubleshooting) that the problem is that `bridge` depends on `dotenv` which depends on *`args`*, and `di` depends on an old version `analyzer` where it depended on an incompatible version of *`args`*:

```
bridge 1.0.0-alpha4
  - dotenv 0.1.3+3
    = args 0.13.2

di 3.3.4
  - analyzer 0.24.6  # di has constraint <0.25.0
    = args 0.12.2+6 # analyzer has constraint <0.13.0
```

Shouldn't the `pub get` report something like this?:

```
Incompatible dependencies:
bridge 1.0.0-alpha4 -> dotenv 0.1.3+3 -> args 0.13.2
di 3.3.4 -> analyzer 0.24.6 (0.26.1+3 available) -> args 0.12.2+6 (0.13.2 available)
```

**Comment by madsager** [comment]
This issue was moved to dart-lang/pub#1330
