### ISSUE TITLE
Bit shift right has surprising behavior for Mints

### ISSUE THREAD

**Issue by madsager** [dart-lang/sdk#24283]
Shifting an integer value right by a large number of bits should yield either 0 or -1 depending on the sign of what is shifted. However, that doesn't happen for Mints. Instead it looks like it goes to the raw machine version of right shift which will perform a shift with the shift value modulo 64 (because it only uses the lower bits).

Example program:

```dart
main() {
  // Smi
  var i = 1 << 30;
  var j = -i;
  print(i >> 37);
  print(j >> 37);
  // Mint
  i = 1 << 50;
  j = -i;
  print(i >> 67);
  print(j >> 67);
  // Bigint
  i = i << 120;
  j = -i;
  print(i >> 199);
  print(j >> 199);
}
```

Should print:
0
-1
0
-1
0
-1

Instead it prints:
0
-1
140737488355328
-140737488355328
0
-1

**Comment by iposva-google** [comment]
cc @sgmitrovic @mhausner
