### ISSUE TITLE
Use git instead of subversion for all dependencies

### ISSUE THREAD

**Issue by mulander** [dart-lang/sdk#24287]
gclient informs upon checkout that subversion is deprecated

```
$ gclient config https://github.com/dartlang/sdk.git                                                                                                                             
$ gclient sync
Oh hai! You are using subversion. Chrome infra is eager to get rid of
svn support so please switch to git.
Tracking bug: http://crbug.com/475320
If you are a project owner, you may request git migration assistance at: 
  https://code.google.com/p/chromium/issues/entry?template=Infra-Git
Syncing projects: 100% (86/86), done.
```

**Comment by sethladd** [comment]
cc @whesse

**Comment by whesse** [comment]
There are a small number of dependencies in our DEPS that still fetch from SVN.  We will be getting rid of those in the next few months, to stop this message.  We already fetch all the important repositories from git.

**Comment by whesse** [comment]
We have removed all of the dependencies on SVN repositories from our checkout of Dart.  Dartium still has a dependency on SVN repos containing our modified copies of Chromium and Blink, but this will go away after we roll Dartium to version 45.
