### ISSUE TITLE
Launch new JS interop on Dart2Js and Dartium

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#24284]
CL with initial dart2js support is for review here.
https://codereview.chromium.org/1318043005/

**Comment by mit-mit** [comment]
Hi @jacob314, is this on track for completion over the next week or so?

**Comment by jacob314** [comment]
On track but landing hot.

**Comment by kevmoo** [comment]
:metal: as of 6dd851e2a45bddbbe685c5a424c9f33542fae034
