### ISSUE TITLE
No compile time error for metadata without required arguments

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24281]
According to Dart Programming Language Speciﬁcation version 1.9, chapter 15 'Metadata':
>It is a compile time error if the expression is not one of the following:
>• A reference to a compile-time constant variable.
>• A call to a constant constructor.

However, if a call to a constant constructor does not include arguments, no compile error is produced.
test1.dart
```dart
class A {
    const A(int x);
}

@A
class B{}

main() {
}
```
>dart.exe --version
>Dart VM version: 1.12.0 (Mon Aug 31 03:21:50 2015) on "windows_x64"
>dart.exe  --checked  test1.dart
> *no output*

**Comment by lrhn** [comment]
The VM takes advantage of "compile-time" not being any fixed time. It doesn't compile the entire program before it starts running, but may compile a a function immediately before it's called. 
An annotation need not be compiled until you try to access it, which you never do, so compile time never comes for `@A`.

Try actually accessing the annotation:
```
import "dart:mirrors";
class A { const A(int x); }
@A class B{}

main() {
  print("1");
  var b = new B();
  print("2");
  var m = reflect(b);
  print("3");
  var c = m.type;
  print("4");
  var a = c.metadata;  // Fails here.
  print("5");
  var a0 = a[0];
  print("6");
  print(a0);
  print("7");
}
```

The output is:
```
'anno.dart': error: line 3 pos 2: expression must be a compile-time constant
@A class B{}
 ^
```

**Comment by mhausner** [comment]
There is no bug here. As Lasse explains, the annotation isn't compiled until it is actually used. As his example proves, the error is reported when class B is instantiated.
