### ISSUE TITLE
Observatory logging doesn't wrap long lines in the UI, instead truncates them.

### ISSUE THREAD

**Issue by FaisalAbid** [dart-lang/sdk#24299]
When viewing the output of long lines i.e log(map) or log(jsonString), Observatory cuts off the text rather than wrap the line to a new line.

See screenshot.

<img width="1395" alt="screenshot 2015-09-05 03 24 56" src="https://cloud.githubusercontent.com/assets/253700/9698304/f9717850-537d-11e5-9921-dfaffc1c7a79.png">

You can see the line is being cut off. You are not able to scroll to the right.

However whats interesting is that if I were to change the zoom level on Chrome to say 80%, you'll actually see that the line is being truncated. 

<img width="1358" alt="screenshot 2015-09-05 03 25 17" src="https://cloud.githubusercontent.com/assets/253700/9698310/304f1742-537e-11e5-8361-6bd5161143a6.png">

Kind of annoying being I end up going to the terminal to view the logs.

**Comment by turnidge** [comment]
Two options here.  (1) make it wrap or (2) show a scroll bar.

**Comment by deftomat** [comment]
@turnidge Provided commit adds horizontal scroll bar. However, the issue is that a logged message will be truncated to 128 chars. No matter how wide window is.
