### ISSUE TITLE
no argument name completion for annotations

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24296]
with functions I get nice completions for the name of the arguments:

![image](https://cloud.githubusercontent.com/assets/1035299/9692614/92218722-534a-11e5-84e4-991c2e3e56f9.png)

but with annotations, I don't get those completions:
![image](https://cloud.githubusercontent.com/assets/1035299/9692647/b99ffdd8-534a-11e5-8f63-cb40ffb510c9.png)

**Comment by a14n** [comment]
dup of #24259

**Comment by kasperpeulen** [comment]
thanks @danrubel !!!
