### ISSUE TITLE
Error message for list index out of bounds is confusing

### ISSUE THREAD

**Issue by apwilson** [dart-lang/sdk#24295]
I received this error message:

`RangeError (index): Invalid value: Only valid value is 0: 0`
`#0      List.[] (dart:core-patch/growable_array.dart:136)`

The error message implies that the only valid value is 0 and that I used 0 - no problem right?

I think when I encountered this error my list size was 0 and the index I used was 0.

**Comment by iposva-google** [comment]
This message is from RangeError and it looks like it gets confused about the bounds being passed in. Assigning to Lasse as he most recently was changing how the VM is reporting out of range errors.

**Comment by lrhn** [comment]
I found a few off-by-one bugs in the error messages originating in C++ code.
I'm fixing this, and improving the error message for a RangeError with an empty range/IndexError on an empty indexable - and fixing a bunch of other places to give similar errors where they now differ significantly by platform (typed data, I'm looking at you!).
