### ISSUE TITLE
dart2js type inferrer does not see closures occurring only as parameter default values as being called.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24297]
See tests/compiler/dart2js/simple_inferrer_const_closure_default_test.dart

defaultFn3.x, defaultFn4.x, defaultFn5.x and defaultFn6.x are inferred as [empty] instead of a small integer.
Ideally these functions would be traced from the default value to get a precise type.  This must be happening for the direct call.

foo5.fn and foo6.fn are inferred as [empty] instead of a function.
It appears that foo5 and foo6 are not considered to be called at all.

**Comment by sigmundch** [comment]
I believe Stephan fixed this via 75b48722bc041e41f9a703531e5ce6913a1667c0
