### ISSUE TITLE
Duration and nanoseconds

### ISSUE THREAD

**Issue by Scorpiion** [dart-lang/sdk#24306]
Hi, the recent discussion about Dart 2.0 made me think about Dart's Duration class.

For example @floitschG's comment here on the mailing list: 
https://groups.google.com/a/dartlang.org/forum/#!msg/misc/q1zYHt5bPQo/wXjVUDC_LQAJ

The fact that other languages such as [Go Duration](http://golang.org/pkg/time/#Duration) and [Java Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) is based around nanoseconds, and Dart's is based around microseconds, is that one of those "tainted design decisions"?

I just wanted to mention it in case the current direction of Dart would benefit from a change like this. I think it could be a non-breaking feature since it only would add nanoseconds. I don't know how the support in browsers are, but maybe if possible nanoseconds could just be microseconds \* 1000 in the browser. The reason I hit this is because during serialization of Duration's i Go it defaults to a nanoseconds value, so for now I convert Dart's Duration to and from nanoseconds with multiplication and division of the microsecond value.

**Comment by Scorpiion** [comment]
If nanoseconds is simply out of the question, then feel free to close this issue after explaining so.

**Comment by lrhn** [comment]
Nothing prevents us from adding an `asNanoseconds` getter or `nanoseconds` constructor argument.
We should probably do that, just because it's convenient (no need for picos yet, I guess).
The only problem is that the internal value will then likely have to be nanoseconds to avoid loosing information, which affects performance (the number of seconds needed for the internal value to exceed the smi ranges is reduced by a factor of 3).

**Comment by Scorpiion** [comment]
I agree, the fact remain that it seems others use nanoseconds as their internal representation, so maybe the range is big enough (if they don't use a bigger datatype internally than Dart can or do use, I don't know the specifics).

**Comment by Scorpiion** [comment]
Just as a reference/example, this is how I serialize a Duration today:

```dart
class DurationSample {
  Duration Ttl;

  DurationSample(this.Ttl);

  DurationSample.fromJson(Map json) {
    // Decode from ns since that is Go's default behavior
    if(json['Ttl'] is int) {
      Ttl = new Duration(microseconds: ((json['Ttl'] / 1000) as double).floor());
    }
  }

  Map toJson() {
    return {
      "Ttl": Ttl.inMicroseconds * 1000 // Encode as ns since that is Go's default behavior
    };
  }
}
```
