### ISSUE TITLE
Dartanalyzer false alarm: the value of local variable not used

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#24303]
Test Code:

```
void main() {
  int count = 0;
  for (int i = 0; i < 10; ++i) 
    f(() {++count;});
}
void f(task()) {
}
```

Dartanalyzer said: The value of the local variable 'count' is not used (/Users/tomyeh/test/dart/dart.dart, line 2, col 7)

It is incorrect.

Tested version: Dart 1.12.0

**Comment by lrhn** [comment]
It might be a bug (I really have no idea), but in this case, it's actually pretty precise: You don't actually *use* the value for anything. 
If you remove the count variable and all expressions using it, your program will behave exactly the same.

The last assignment to the count is unused. The previous assignment is only used in the last assignment, etc., so transitively you never use the variable. An good optimizing compiler should remove your entire program :)

**Comment by bwilkerson** [comment]
This is working as intended. The assumption is that you won't write code to declare, initialize and compute a value unless you intended to use that value for something, and hence that you'd want to be told when you forgot to use it. To that end, the hint looks for variables that are declared but not used for anything other than updating themselves.

As was pointed out, in this case the value of `count` really is unused.
