### ISSUE TITLE
ContextManager needs to watch for appearance of non-existent analysis roots

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24305]
From the analysis server API documentation, in the [analysis.setAnalysisRoots](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_analysis.setAnalysisRoots) section:

> Note that this request determines the set of requested analysis roots. The actual set of analysis roots at any given time is the intersection of this set with the set of files and directories actually present on the filesystem. When the filesystem changes, the actual set of analysis roots is automatically updated, but the set of requested analysis roots is unchanged. This means that if the client sets an analysis root before the root becomes visible to server in the filesystem, there is no error; once the server sees the root in the filesystem it will start analyzing it. Similarly, server will stop analyzing files that are removed from the file system but they will remain in the set of requested roots.

Currently, if an analysis root does not exist in the file system at the time that setAnalysisRoots is invoked, the analysis server will not watch for its appearance.  This means that, for instance, if the user's editor supports a single operation that creates a folder and sets it as an analysis root, race conditions in the file system may prevent that folder from being analyzed.

This should be fixed as part of the re-work of the ContextManager (#24133).

**Comment by keertip** [comment]
Likely not valid anymore as there has been rewrites/refactors in this area. Closing as stale.
