### ISSUE TITLE
Consider using pkg/async CancelableOperation in pkg/analyzer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24316]
@nex3 Just added this to pkg/async – might be a nice way to dry things up...

**Comment by jmesserly** [comment]
assumed stale

**Comment by kevmoo** [comment]
Optimistically reopening. It'd be good if we stop duplicating this type of logic when we have existing solutions - https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/cancelable_future.dart

**Comment by jmesserly** [comment]
yeah, IDK if we're going to refactor this if we didn't in the last 3 yrs tho? like if you want to send analyzer folks a patch they may very well accept it otherwise I don't see it changing?

**Comment by jmesserly** [comment]
(like, there are tons of actual user visible bugs, seems all of those would be higher priority)

**Comment by bwilkerson** [comment]
Yes, they'd be much higher priority.

And this code might well go away with the move to CFE (I haven't looked at where it's being used).

**Comment by kevmoo** [comment]
ack
