### ISSUE TITLE
XsltProcessor deprecated ?

### ISSUE THREAD

**Issue by damien-git** [dart-lang/sdk#24317]
XsltProcessor seems to be deprecated. How is it possible to do an XSL transform in Dart ? If it is not possible, this is an issue...

**Comment by alan-knight** [comment]
It's deprecated in Blink. See https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/zIg2KC7PyH0%5B1-25%5D

I would assume it's possible to have a package providing XSLT.

**Comment by damien-git** [comment]
wow, the web keeps regressing every day. I doubt there will ever be a complete implementation in Javascript, and that is even less likely in Dart.
The Blink thread points to most XSLT usage being server-side, and I believe that, but Dart lets us move code from the server to the client because it is easier to create large applications in Dart than in Javascript. And even in Javascript there are more and more large applications manipulating XML documents. It looks like this decision is mostly based on implementation issues in Blink.

...but thanks for the fast comment.
