### ISSUE TITLE
How to use parameterized type as annotation?

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24312]
The Dart Programming Language Speciﬁcation version 1.9 defines the following syntax for metadata:

> Dart supports metadata which is used to attach user deﬁned annotations
> to program structures.
> metadata:
> (‘@’ qualiﬁed (‘.’ identiﬁer)? (arguments)?)*
> ;

The defined syntax do not allow to use parameterized type as annotation.
The following code produce compile time error:

``` dart
class A<T> {
  const A(T x);
}

main() {
  var a = new A<String>('aaa'); // OK
  @A<String>('bbb') var x; // error: unexpected token '@'
}
```

Please, clarify whether it is possible to use parameterized type as annotation.
If it is not allowed, please, add some note to the specification about this.

**Comment by lrhn** [comment]
It's not currently possible to create the annotation value at the annotation point if it needs type parameters, but you can create it using a separate const variable:
```
const _astring = const A<String>('bbb');
@_astring var x;
```
Admittedly not as pretty. 
Marking this as a request for allowing type parameters in annotation constructor calls.

**Comment by lrhn** [comment]
Now actually works.
