### ISSUE TITLE
VM service: Document what Message.messageObjectId is

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24310]
The VM service docs include a public `Message.messageObjectId` field, but they don't mention what is safe to do with it. I'd guess that it could be passed to `getObject`, but I'd feel wary doing so unless that's actually documented.

**Comment by johnmccutchan** [comment]
messageObjectId is an id that can be safely passed to getObject. The returned object is the message payload.

**Comment by nex3** [comment]
What classes of objects can it return? Will it always be an `Instance`, or can it be other things as well?

**Comment by johnmccutchan** [comment]
It can return anything that can be transmitted as a Dart message to a Dart SendPort/ReceivePort. In other words, `Instance`.

**Comment by turnidge** [comment]
We need to add "messages" support to LookupHeapObject -- then message ids will be useful for any api, not just getObject.  We should also update the service.md docs.

**Comment by johnmccutchan** [comment]
Documentation has been updated and the behaviour of message objects is now unified with other heap objects.

https://codereview.chromium.org/1339713002/
