### ISSUE TITLE
Make code coverage api public in VM Service

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#24318]
The code coverage api is currently private.  We should make it public.

Before we do this, we should switch to a token-based output rather than a line-based output.  We should also clean up the json in general.

**Comment by eernstg** [comment]
Yes, please! ;-) We'd like to use coverage in a programmatic manner for the package reflectable.

**Comment by iposva-google** [comment]
Clarification: By public this means through the VM service protocol, not as a Dart API.

**Comment by turnidge** [comment]
45ec466ce5619f4dab962a8adf0eee7d60faf06d
