### ISSUE TITLE
Remove --coverage-dir option from the VM.

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#24319]
We should remove the --coverage-dir option from the VM once the code coverage tool switches to using the vm service protocol for this.

@cbracken

**Comment by iposva-google** [comment]
cc @cbracken 

Moving to 1.14 as we are not yet ready to switch.

**Comment by mit-mit** [comment]
@turnidge @cbracken is this happening in 1.14?

**Comment by kevmoo** [comment]
@turnidge @cbracken Ping?

**Comment by iposva-google** [comment]
Moving to 1.15 because the replacement API is not yet entirely ready.

**Comment by iposva-google** [comment]
@cbracken Please work with Todd to make sure the new API implements the features you need.

**Comment by cbracken** [comment]
Will do!

**Comment by alexander-doroshko** [comment]
@turnidge We are working on coverage support in IntelliJ IDEA / WebStorm. Is `pub global run coverage:collect_coverage` the only recommended way to collect coverage or we can use `--coverage-dir` VM option or anything else?

cc @scheglov, @jingbian

**Comment by zoechi** [comment]
I guess https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#sourcereportcoverage

**Comment by cbracken** [comment]
@iposva-google I'm nearing the point where I'll have time to spend time porting package:coverage over to the new coverage API. In all likelihood, next week.

@alexander-doroshko If you've got an existing implementation of the service protocol (I'd imagine you must for debugging etc.) and don't need LCOV output, package:coverage doesn't give you much benefit over rolling your own against the API that @zoechi points out. package:coverage simply provides tooling that runs against that same API -- for the moment, the previous version of it.

What would be nice would be VM service package that wraps up the entire protocol + API. package:coverage would then simply add the merging/formatting tooling.

**Comment by jingbian** [comment]
Hi Chris,

So if we simply want the coverage data dumped into a json file with a
predefined file name. What are your suggestions?

Previously, we ran another process with coverage:collect_coverage to do so.
Is there a better alternative? (like only a flag for "dart" binary instead
of an extra process)
Also --coverage_dir is OK, but seems deprecated and doesn't have an option
to specify the file name.


On Fri, Feb 19, 2016 at 6:05 AM, Chris Bracken <notifications@github.com>
wrote:

> @iposva-google <https://github.com/iposva-google> I'm nearing the point
> where I'll have time to spend time porting package:coverage over to the new
> coverage API. In all likelihood, next week.
>
> @alexander-doroshko <https://github.com/alexander-doroshko> If you've got
> an existing implementation of the service protocol (I'd imagine you must
> for debugging etc.) and don't need LCOV output, package:coverage doesn't
> give you much benefit over rolling your own against the API that @zoechi
> <https://github.com/zoechi> points out. package:coverage simply provides
> tooling that runs against that same API -- for the moment, the previous
> version of it.
>
> What would be nice would be VM service package that wraps up the entire
> protocol + API. package:coverage would then simply add the
> merging/formatting tooling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24319#issuecomment-185942730>.
>



-- 
Thanks and regards,
Jing Bian

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by cbracken** [comment]
> So if we simply want the coverage data dumped into a json file with a predefined file name. What are your suggestions? Previously, we ran another process with coverage:collect_coverage to do so.
Is there a better alternative?

`collect_coverage` is the way to do it.

**Comment by iposva-google** [comment]
Fixed with c434931517ae2a05f96b26c0fe6ff581d322ed02
