### ISSUE TITLE
List.last should have a setter, too

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#24320]
Iterable.last is read-only: makes sense.
List.last is read-only, too :( does not make sense as Iterable vs List is unmodifiable vs modifiable interface-wise.

Please add a setter. It's sad to have to use weird workarounds to set the last element in a List.

**Comment by lrhn** [comment]
Adding something to the List interface at this point will mean that all existing list implementations are now incomplete. List is an interface that is often implemented by libraries, so there is a high bar for allowing changes.
That said, I completely agree that it should be there (and first= too).
See: https://codereview.chromium.org/315173005/

**Comment by matanlurey** [comment]
This happened! Thanks @lrhn!
