### ISSUE TITLE
VM service: Isolates don't include their entrypoints

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24329]
The documentation for `Isolate.entry` says that it's guaranteed to be included for a runnable isolate, but when I load an `Isolate` for a process that's been running actively for a while I see the following JSON:

```json
{
    "type": "Isolate",
    "fixedId": true,
    "id": "isolates/237290978",
    "name": "test.dart$main",
    "number": "237290978",
    "startTime": 1441935949438,
    "livePorts": 0,
    "pauseOnExit": true,
    "pauseEvent": {...},
    "rootLib": {...},
    "libraries": [...],
    "breakpoints": []
}
```

There's no `entry` field, even though all the other fields that indicate a runnable isolate are.

**Comment by nex3** [comment]
I tested this against e07d9e89183b400a1b3230e56b971da68a8e0bd7.

**Comment by turnidge** [comment]
Ugh.  Due to the way that Dart VM embedding works, I don't necessarily know the entrypoint when the isolate is made runnable.  In particular, the entrypoint is not available for the *main* isolate.

I'm leaning towards making entry private (_entry) and removing it from the spec.

**Comment by nex3** [comment]
For the main isolate, isn't it always going to the the root library's `main()` function?

**Comment by turnidge** [comment]
Depends on the embedder.  Usually, yes.

The name of the entrypoint for the first isolate is passed in to
Dart_CreateIsolate, so it is available and we could try to resolve it.  The
problem is that if an embedder decided to, say, start the main isolate
somewhere else, like MyClass.myMain, then we might not handle it very well.

Processing this.
