### ISSUE TITLE
Using loadLibrary with deferred imports pollutes the global namespace 

### ISSUE THREAD

**Issue by grumpy** [dart-lang/sdk#24328]
Similar to https://github.com/dart-lang/sdk/issues/2265, but only applies to deferred libraries after loadLibrary is called.

This causes problems with jQuery, because it overwrites $ in the global namespace.

**Comment by danschultz** [comment]
When is this fix expected to go out in a stable release?

**Comment by sethladd** [comment]
What's the impact of this bug?

**Comment by Aetet** [comment]
In what stable release this fix will appear? Because our dart intl package break jQuery libs.

**Comment by sigurdm** [comment]
@sethladd knows more than me about the release schedule.

**Comment by sethladd** [comment]
If 1.13-dev has this fix, then it will be in the 1.13-final. Can you try 1.13 dev channel?
