### ISSUE TITLE
Android arm64 build is broken on boringssl

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#24321]
```
$ ./tools/build.py -m release -a arm64 --os=android runtime
...
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S: Assembler messages:
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:28: Error: unknown pseudo-op: `.syntax'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:29: Error: unknown cpu `cortex-a8'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:30: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:40: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:43: Error: unknown pseudo-op: `.fpu'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:44: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:45: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:46: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:47: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:48: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:49: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:50: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:51: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:52: Error: unknown pseudo-op: `.eabi_attribute'
third_party/boringssl/src/crypto/chacha/chacha_vec_arm.S:53: Error: unknown pseudo-op: `.thumb'
chacha_vec.c:59: Error: unknown pseudo-op: `.thumb'
chacha_vec.c:60: Error: unknown pseudo-op: `.thumb_func'
chacha_vec.c:63: Error: junk at end of line, first unrecognized character is `@'
chacha_vec.c:64: Error: junk at end of line, first unrecognized character is `@'
chacha_vec.c:65: Error: unknown mnemonic `push' -- `push {r4,r5,r6,r7,r8,r9,r10,fp,lr}'
chacha_vec.c:66: Error: operand 1 should be an integer register -- `mov r8,r3'
```
Etc.

**Comment by zanderso** [comment]
I have tried updating our android_tools, but the same error is produced by the newest version.

**Comment by sgjesse** [comment]
This is most likely caused by the BoringSSL ARM32 assembly code being used on ARM64 as well.

If BoringSSL does not have ARM64 assembly implementation we should use the generic C implementation.

**Comment by whesse** [comment]
I have filed an issue with BoringSSL to ask if that is the case.  It seems likely, but they actually specifically enable this file for __aarch64__ in the guards.  But this might have been an oversight.  There are also errors in the c file, though, so it is not just a matter of changing this guard.

Here is the BoringSSL issue (which is public) that I filed.  I'll try and get the exact compiler lines to them as well. https://code.google.com/p/chromium/issues/detail?id=530543

**Comment by whesse** [comment]
@zanderso : Could you try removing the  "|| defined(__aarch64__)" from the guard in line 26 of chacha_vec_arm.S, and see if the compilation works?  I think this might be sufficient to make it work.

The file chacha_vec_arm.S is not included in Chromium builds on __aarch64__, because Chromium specifies different lists of files to include for each architecture, and doesn't include it for arm64.  We include all files for all architectures, and rely on guards in the files to disable them for architectures they don't apply to.  This may just be a mistake in the guard.

**Comment by zanderso** [comment]
The build succeeds after removing that.

**Comment by whesse** [comment]
Great - I have submitted the change upstream.  I can also commit the change
to the Dart repo, since it is a local copy of the file that is the problem.


On Mon, Oct 5, 2015 at 5:17 PM, Zachary Anderson <notifications@github.com>
wrote:

> The build succeeds after removing that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24321#issuecomment-145566005>.
>



-- 
William Hesse

**Comment by rmacnak-google** [comment]
It looks like this change was landed upstream, but we're still on an old version of boringssl. In fact, it looks like we have never update boringssl since it landed. How often do we expect to update it?

**Comment by whesse** [comment]
Our update schedule will be limited by Chrome's update schedule, since the
gyp build of BoringSSL that we use is coming from them.  But they have
updated recently, to a Dec 18 2015 version of BoringSSL, so we can update
to that one.

I expect we will update it somewhere between twice a year and monthly.  We
don't have a formal plan or schedule for doing it - perhaps we should
establish one.

On Tue, Jan 5, 2016 at 12:49 AM, Ryan Macnak <notifications@github.com>
wrote:

> It looks like this change was landed upstream, but we're still on an old
> version of boringssl. In fact, it looks like we have never update boringssl
> since it landed. How often do we expect to update it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24321#issuecomment-168847419>.
>



-- 
William Hesse

**Comment by iposva-google** [comment]
While you are figuring out the ongoing schedule I suggest that you roll to the latest from Chrome now. This will likely solve at least some of the issues we are seeing with the switch to boringssl. Thanks!

**Comment by whesse** [comment]
I have a CL that rolls to the lastest BoringSSL from Chrome, which is Dec
18.  It compiles and runs (with patches), without error on linux x64 and
ia32.
I will do more testing, but the patches need to be upstreamed, and I will
roll to tip-of-tree, to make it compile without patches.

I think we could do a patch in Dart, by copying the file to our local
assembly directories in third_party/boring.ssl, removing the original from
the sources in boringssl.gypi,
modifying the copy, and adding it to boringssl.gypi, but it seems better to
upstream it.

The Dart CL is https://codereview.chromium.org/1653973006/

The patch is https://boringssl-review.googlesource.com/#/c/7030/


On Mon, Jan 25, 2016 at 8:20 PM, Ivan Posva <notifications@github.com>
wrote:

> While you are figuring out the ongoing schedule I suggest that you roll to
> the latest from Chrome now. This will likely solve at least some of the
> issues we are seeing with the switch to boringssl. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24321#issuecomment-174627339>.
>



-- 
William Hesse

**Comment by whesse** [comment]
The fix is still in the pending BoringSSL roll, which is delayed on C11 support.  The issue tracking this is
#26367 .  We need to update from the compilers in ubuntu precise to those in ubuntu trusty, but this also rolls our glibc requirements.

**Comment by zanderso** [comment]
We rolled BoringSSL, so I think we can close this one.
