### ISSUE TITLE
VM service: document Breakpoint

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24327]
The `Breakpoint` type in the VM service is currently has no documentation. It would be helpful to have full documentation like other types, and in particular to document what it means for a breakpoint to be "resolved". When does it become resolved? What a user can safely assume about a resolved breakpoint? Will its location always be a `SourceLocation` once it's resolved?

**Comment by turnidge** [comment]
I guess "resolved" is kinda redundant -- we could just rely on the distinction between SourceLocation and UnresolvedSourceLocation.
