### ISSUE TITLE
Typo in bigint.dart

### ISSUE THREAD

**Issue by madsager** [dart-lang/sdk#24324]
The following snippet refers to d_cmp_ab which is not defined anywhere. d_cmp_b is defined above but unused, so that is probably what this was meant to be?

```dart
        if (d_neg == b_neg) {
          var d_cmp_b =
              _compareDigits(d_digits, abcd_used, b_digits, abcd_used);
          if (d_cmp_b > 0) {
            _absSub(d_digits, abcd_used, b_digits, abcd_used, d_digits);
          } else {
            _absSub(b_digits, abcd_used, d_digits, abcd_used, d_digits);
            d_neg = !d_neg && (d_cmp_ab != 0);
          }
        }
```

**Comment by crelier** [comment]
Yep, looks like a typo to me.
If this can wait a few days, I'll into it next week and understand why this remained hidden until now. I'm too busy batch interviewing in Shanghai right now.

**Comment by madsager** [comment]
No hurry from my side, better just take our time and get the fix tested as well.

For context: I'm playing with using your code as the bigint implementation for Fletch which is where I noticed this in passing. :-)

**Comment by crelier** [comment]
The code path with the typo is only used for modInverse (not for gcd), and only when the modulus is even, which never really happens in practice. It is quite painful to find a pair of input numbers that will trigger this path. But the fix is obvious.

Thanks for finding it.
