### ISSUE TITLE
No compile-time error while getter access and method extraction

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24332]
Specification "16.18.1Getter Access and Method Extraction"

"Evaluation of a property extraction i of the form e.m proceeds as follows:
...
It is a compile-time error if m is a member of class Object and e is either a
prefix object (18.1) or a constant type literal."

Consider the code:

```dart
import 'some_lib.dart' as lib;

main() {
  var x = lib.toString;
  var y = String.toString;
}
```
No compile error. Dart analyzer produces warnings only, Dart produces NoSuchMethodError
Dart VM version: 1.12.0-dev.5.10 (Tue Aug 25 04:09:15 2015) on "linux_x64"

**Comment by bwilkerson** [comment]
There are now warnings for both lines. I'm guessing that this was fixed, but if you're still seeing the problem please re-open this issue.
