### ISSUE TITLE
Add quick fix to add import with prefix

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24338]
There is a quick fix to add an import for an unknown type name, but when the type name is qualified the only fix suggestion is to define the class (which is not a valid fix and shouldn't be suggested). For example, enter the following code into a Dart file:

class C {
  prefix.String s;
}

and place the cursor inside the identifier 'String'. It would be nice if one of the suggested fixes was to add an import (of dart:core, in this case) with the given prefix.

**Comment by srawlins** [comment]
I like this idea.

**Comment by FMorschel** [comment]
Related to:

- https://github.com/dart-lang/sdk/issues/55863
- https://github.com/dart-lang/sdk/issues/41515
