### ISSUE TITLE
try/poi tests fail after compiler_helper switched to memory compiler

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24334]
Some tests running try on dartium fail after the change in https://codereview.chromium.org//1322973007

This switches some component with one that uses dart:io to find package_root from Platform.  Since this doesn't exist on the browser, it fails.

I'm not sure what the right solution is for this - I have heard that the try tests are being removed/changed, and that the mock compiler that memory compiler is replacing is being removed, so reverting the CL may not be the right answer.

The 5 failing tests are suppressed in tests/try/try.status.

@johnniwinther @sigurdm @peter-ahe-google

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1336843003/
