### ISSUE TITLE
No longer required to warn if methods are missing if superclass implements noSuchMethod

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24337]
A little birdie told me (cough @gbracha cough) that the latest draft of the spec has wording around noSuchMethod, superclasses, and warnings.

If I understand correctly, the following will no longer be required:

```
//Mock class
class MockCat extends Mock implements Cat{
  //this tells Dart analyzer you meant not to implement all methods,
  //and not to hint/warn that methods are missing 
  noSuchMethod(i) => super.noSuchMethod(i);
}
```

That is, the noSuchMethod in MockCat will no longer be required to silence analyzer warnings.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1414003003/

**Comment by kevmoo** [comment]
@bwilkerson Can we close https://github.com/dart-lang/sdk/issues/16132 too?

**Comment by bwilkerson** [comment]
I didn't do anything related to `@proxy`, so probably not.
