### ISSUE TITLE
No definition for term 'field'

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24333]
The Dart Programming Language Speciﬁcation version 1.9 reads:

> Metadata can appear before a library, part header, class, typedef, type pa-
> rameter, constructor, factory, function, **ﬁeld**, parameter, or variable declaration
> and before an import, export or part directive.

Unfortunately, term 'field' is not defined in the specification. Quick search on specification texts shows only reference or usage of this term. 

One may assume that field is related to a class. But there is a good definition for class members:

> A class has constructors, instance members and static members. The in-
> stance members of a class are its instance methods, getters, setters and instance
> variables. The static members of a class are its static methods, getters, setters
> and static variables. The members of a class are its static and instance members.

Probably, field is a synonym for instance variables?

Please, define term 'field' in the specification.

**Comment by eernstg** [comment]
Aleksei, thanks for noting this! I've created https://codereview.chromium.org/2613293002 to resolve the issue.
