### ISSUE TITLE
No completions after "yield" or "yield*"

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24346]
Starting from the following file state:

    import 'dart:async';
    class C {
      Stream foo() => null;
      Stream bar() async* {
        yield f;
        yield* f;
      }
    }

Place the cursor after each of the identifiers "f" and request code completions.

Expected result: "foo()" should be suggested as a completion.
Observed result: no completions are available.

**Comment by Lootwig** [comment]
In IntelliJ, this is not working with

IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019

and 

Dart plugin 192.6603.23

Especially "yield [Constructor initials]" only offers to complete the desired constructor when the "new" keyword is included.
