### ISSUE TITLE
Instantiate a Generic Parameter

### ISSUE THREAD

**Issue by jrote1** [dart-lang/sdk#24343]
For example

    class GenericClass<T>
    {
         T getInstance()
         {
               //This does not work
               return new T();
         }
    }

You should be able to instantiate a generic, maybe extra syntax should be added to generics for example. 

    class GenericClass<T with new()>

This would mean the generic type should have an empty constructor.

**Comment by floitschG** [comment]
Duplicate of issue 3633.
