### ISSUE TITLE
VM service: pause() doesn't do anything when no code is running

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24349]
When an isolate is alive but no code is running (e.g. when there's an open receive port), the `pause` RPC doesn't have any effect. This makes it hard to write code that works correctly in different contexts; for example, code that pauses an isolate and waits for a pause event to fire can deadlock.

Ideally, calling `pause` in this state would fire a `PauseInterrupted` event and set the Isolate's `pauseEvent`. But if that's not possible, it should at least throw an error indicating that the pause couldn't be completed.

**Comment by iposva-google** [comment]
CC @turnidge

**Comment by turnidge** [comment]
I have a fix for this, but I am waiting on Zach's kill-all-isolates change to land first, as there is a lot of code overlap.
