### ISSUE TITLE
LocalVariableElementImpl.computeNode doesn't handle for-each statements or catch clauses.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24347]
The method `LocalVariableElementImpl.computeNode` assumes that the variable is declared in a `VariableDeclaration`.  However, this isn't always the case.  Local variables can also be declared in a `ForEachStatement` or a `CatchClause`.  Attempting to call `computeNode` on such a variable causes null to be returned.

Fixing this bug will require modifying the return type of `LocalVariableElement.computeNode` from `VariableDeclaration` to `AstNode`.

**Comment by srawlins** [comment]
There is no longer a method, `LocalVariableElementImpl.computeNode`. I'll close this as stale. Please re-open if the bug still exists in some form.
