### ISSUE TITLE
Dart2js deferred loading compiles top-level maps in the deferred library into the main file

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24356]
See https://github.com/alan-knight/deferred_load

Do a

      pub build --mode=debug

and in the generated you can see that inlines the whole "stuff" map in the main .js file. If you have multiple large maps like this, as happens with Intl messages, you get far too much code in the main file.

**Comment by rakudrama** [comment]
A work-around is to compute the value for the top level variable via a function that is not inlined.

```dart
final stuff = {...};
```

-->

```dart
final stuff = _stuff(_stuff);  // Two references inhibits inlining.
_stuff(_ignored) => {...};
```

**Comment by hterkelsen** [comment]
dart2js avoids inlining across deferred boundaries:
https://github.com/dart-lang/sdk/blob/bb2c3a9350eec6cedb88b8f879d3626edadcfeb3/pkg/compiler/lib/src/ssa/builder.dart#L1444

However, if the code to be inlined is a single node (such as a single expression), it will inline it anyways. As a workaround you can change it into a getter:

```dart
get stuff => {
      "good": printThings("good"),
      "ok": printThings("ok"),
      "weird": printThings("weird")
    };
```

**Comment by hterkelsen** [comment]
Lazy initializers, which are used for all top-level non-const and static fields, are always placed in the main part. I see some TODOs about not forcing all lazy fields to be in the main output unit -https://github.com/dart-lang/sdk/blob/1414d9b27e6e5b775bccbd90d914b030ee41fec0/pkg/compiler/lib/src/js_emitter/model.dart#L119 for example - and I don't see any reason why all of the lazy initializers need to be in one place, so I will implement putting the lazy fields in their own libraries.
