### ISSUE TITLE
VM service: stdout doesn't produce WriteEvents

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24351]
Currently only `print()` produces `WriteEvent`s on the `Stdout` stream; `dart:io`'s `stdout.add()` and derived methods don't. `stderr` produces `WriteEvent`s on `Stderr` as expected.

**Comment by turnidge** [comment]
Can you verify that you are calling flush() on Stdout?

**Comment by turnidge** [comment]
To provide more background, print is a special case in the code.  Stdout and Stderr are handled by, more-or-less, the same code path and I have seen them both working for me in the past.  That's why I'm thinking that buffering may be implicated.

**Comment by nex3** [comment]
I was mostly testing with `stdout.writeln()`, which I believe always flushes. Even if I explicitly add a `stdout.flush()` it doesn't seem to work.

**Comment by turnidge** [comment]
Huh.  Have you looked at
runtime/observatory/tests/service/capture_stdio_test.dart?  It currently
passes, capturing stdout.write().  I have rewritten it to try
stdout.writeln and that works too.  So something else is going on.

Could this be related to your other bug involving the Debug stream?

Could you run your program with the --trace-service flag and attach the
output here?

**Comment by turnidge** [comment]
Emailing messed up the last sentence of my previous message:

Could you run your Dart VM with the --trace-service flag and attach the output from running your test?

**Comment by nex3** [comment]
Investigating further, it looks like this is actually triggered by the *process's* (not the VM service's) stdout stream being paused.

**Comment by turnidge** [comment]
Ok, so are you ok with me closing this bug?

**Comment by nex3** [comment]
I think it's still a problem that the process's stdout stream affects the VM service's, especially since it *only* affects the `stdout` sink and not `print()`.

**Comment by turnidge** [comment]
Well, that problem comes in because the embedder (standalone vm) chose to
implement print() through a completely different code path than the rest of
stdout.  On dartium, for example, print() goes to the javascript console.

I should probably not post print events to Stdout at all... to be
completely correct I might need to post them to a third stream... ugh.

Will ponder this.

**Comment by turnidge** [comment]
Looking at the specs for print, it specifies that it prints it to the "console", which seems to me to leave it up  to the embedder, especially since not all dart impls will have a notion of stdout.

**Comment by nex3** [comment]
The stream is literally named `Stdout`, and you're telling me that data written to stdout isn't supposed to be emitted from it?

Look, I don't care whether you categorize this as a bug or a feature, but it's clearly necessary behavior. Please don't close it out based on nitty semantic arguments.
