### ISSUE TITLE
Crashes on debug Windows on dev channel

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24359]
There are failures of assertions, in debug mode, on the buildbots.  The failing assertions are:

FAILED: none-vm debug_ia32 standalone/full_coverage_test
Expected: Pass Actual: Crash
stderr:
vm\os_thread_win.cc:121: error: expected: GetLastError() == ERROR_INVALID_PARAMETER

and

FAILED: none-vm-checked debug_ia32 vm/cc/RunLoop_ExceptionChild
Expected: Pass Actual: Crash
stderr:
vm\message_handler.cc:331: error: expected: oob_queue_->IsEmpty()

The failing runs can be seen at:
http://build.chromium.org/p/client.dart/builders/vm-win32-debug-dev/builds/314
and
http://build.chromium.org/p/client.dart/builders/vm-win64-debug-dev/builds/85/steps/checked_tests/logs/stdio

**Comment by whesse** [comment]
These crashes are not seen on bleeding-edge, which I have checked is identical to the new dev version, at commit 8d96919609c6f1916fafbcbbc7a0639131606fc4.  I have triggered new builds of each of the dev channel builders that failed.

**Comment by iposva-google** [comment]
CC @turnidge

**Comment by iposva-google** [comment]
I will also split the first assertion about Windows GetLastError into a separate bug report.

**Comment by iposva-google** [comment]
The GetLastError was fixed before I could even split the bug into two parts: https://codereview.chromium.org/1345273002/

**Comment by iposva-google** [comment]
Zach, any progress on this?

**Comment by zanderso** [comment]
I removed the ASSERT for the first crash (https://github.com/dart-lang/sdk/commit/1390b664cbc1674fb828dc772431fa7957c4f5e9), and turned off the shutdown code for the second (https://github.com/dart-lang/sdk/commit/a580bafc5de1ff9a66d642fa92f5eb85fb2f1a31). As discussed, the message handler needs a bit of work before we can re-enable the shutdown code.
