### ISSUE TITLE
Tear-off: expression is not evaluated to object

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24357]
According Dart spec "16.18.3 General Closurization"

"Evaluation of a property extraction i of the form e#m proceeds as follows:
First, the expression e is evaluated to an object o. Then:..."

But in fact expression is not evaluated to object o. Run the following program

``` dart
class A {
  int get g => 1;
}

class C {
  A get m => new A();
}

main() { 
  C c = new C();
  var x = c.m#g;
}
```

Result: error: semicolon expected
  var x = c.m#g;

 var x = (c.m)#g works well.

Tested on Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:28:05 2015) on "linux_x64"

**Comment by lrhn** [comment]
The behavior is what the current grammar specifies:
```
postfixExpression:
  assignableExpression postfixOperator |
  primary (selector* | ( ‘#’ ( (identifier ‘=’?) | operator)))
  ;
```
This means that you can't put a "#foo" after a selector like `.m` - you can do either, but not both. It does work when you wrap it in parentheses because a parenthesized expression is a `primary`.

**Comment by sgrekhov** [comment]
Isn't it a contradiction with 

Evaluation of a property extraction i of the form e#m proceeds as follows:
First, the expression e is evaluated to an object o.?

According this statement getter invocation should be evaluated to the object which is  value of the getter

**Comment by kmillikin** [comment]
It's not a contradiction, it just doesn't stand on its own.  You have to read that section along with the grammar as @lrhn did above.

Consider the analogous: Evaluation of an multiplication expression of the form e0 * e1 proceeds as follows: first the expression e0 is evaluated, then the expression e1 is evaluated, then the result is multiplied.

Now, would you expect `x * y + z` to first evaluate `x`, then evaluate `y + z`, then multiply the results?  That's not what actually happens, because if the precedence rules encoded in the grammar.

**Comment by iposva-google** [comment]
Over to Gilad to validate that the VM's approach is correct here.

**Comment by sgrekhov** [comment]
What about this?
```dart
class A {
  int m() => 1;
}

A getA() {
  return new A();
}

main() {
  var f = getA()#m;
}
```
Result: 
error: line 24 pos 17: semicolon expected
  var f = getA()#m;
                ^

**Comment by lrhn** [comment]
`getA()#m` is still not valid syntax. The grammar allows *either* a tear-off operation *or* a "selector" chain (call or member access, basically) after a primary expression. Here you do `getA()` which is not a  primary expression (`getA` is a primary expression, `getA()` has the call selector after it so you can't also have a tear-off). Again you need to write `(getA())#m` if that is what you want to do.

**Comment by sgrekhov** [comment]
Ok, thank you for clarification. But I think  this grammar is, at least, not obvious at this point and the above is not what Dart user, not deeply familiar with the specification and sophisticated syntax like 'primary (selector* | ( ‘#’ ( (identifier ‘=’?) | operator)))', expects.

getA().m works, getA()#m not. Why? Why this limited (limited comparing with '.') syntax is needed at all?

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.
