### ISSUE TITLE
Provide a way to inspect all of a zone's values

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#24358]
This is mainly for debugging. It would be nice to be able to access the underlying HashMap to be able to print it to the console or similar.

**Comment by lrhn** [comment]
Like `Expando`, it is a deliberate choice not to make the keys available to everybody. That allows you to have "private" zone variables by using a key that you don't share with anybody else.
Giving programmatic access to the keys would break this abstraction.

A *real* debugger should be able to see the underlying hash *maps*. There is one for each zone object, and values are only propagated to child zones when they ask for them by key, so there is no single hash map containing all of a zones variables. So, even if we wanted it, it isn't as trivial as returning a map.

What you can do is to run your program in a debugging zone which overrides the fork operation. Then you can record the maps as the new zones are created and keep the information on the side.

**Comment by BlackHC** [comment]
Thanks!
