### ISSUE TITLE
The position of the keys on maps are random?

### ISSUE THREAD

**Issue by gil0mendes** [dart-lang/sdk#24362]
Hey I have a question... 

If I create the follow map {'A': 'a', 'B': 'b', 'C': 'c'} and inspecting the keys the output is ['A', 'C', 'B'] but I expected them to be ['A', 'B', 'C']!!! This is strange!

This is the correct behaviour or is it a bug?

**Comment by sethladd** [comment]
Map keys aren't guaranteed to be ordered.

You might want to look at https://api.dartlang.org/1.12.1/dart-collection/LinkedHashMap-class.html

**Comment by gil0mendes** [comment]
Yes... This should help... With the HashMap work fine, but is more difficult to do some unit tests ;)

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/14930950/what-are-the-differences-between-the-different-map-implementations-in-dart/14930951#14930951

**Comment by lrhn** [comment]
The map *literal* is expected to be a linked hash map with keys inserted in syntactic order. I believe the specification requires this. So, they should be iterated as `'A', 'B', 'C'`.
When I run:
```
main() {
 print({'A':0,'B':0,'C':0}.keys);
}
```
I get `(A, B, C)` on both the VM and dart2js. 

How do you run your program, and can you show more of the code giving this result?
