### ISSUE TITLE
MIPS build is broken

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#24360]
/b/build/slave/vm-mips-release-be/build/sdk/tools/sdks/linux/dart-sdk/bin/pub: line 37: /b/build/slave/vm-mips-release-be/build/sdk/tools/sdks/linux/dart-sdk/bin/dart: cannot execute binary file
/b/build/slave/vm-mips-release-be/build/sdk/tools/sdks/linux/dart-sdk/bin/pub: line 37: /b/build/slave/vm-mips-release-be/build/sdk/tools/sdks/linux/dart-sdk/bin/dart: Success
make: **\* [runtime/observatory/pubspec.lock] Error 126
make: **\* Waiting for unfinished jobs....

It seems to have been broken for quite some time. Is anyone being notified of these breakages?

**Comment by zanderso** [comment]
@whesse

**Comment by johnmccutchan** [comment]
I believe @whesse is looking at fixing this build breakage.

**Comment by whesse** [comment]
Yes, it should have been fixed by my recent changes to observatory tool.  There may be other issues that show up, but that was definitely the reason it was broken.

**Comment by whesse** [comment]
The observatory build is now working, but the linker is being killed by the OS for using too much memory when linking dart.  I'll first try using -j1 instead of -j2 when building, and see if the process memory limit can be increased.

**Comment by whesse** [comment]
Added a change to the buildbot to build on the mips slaves with -j1.  They do die when trying to link two versions of dart at once.  This should fix them.

Long-term fix is to cross-compile for MIPS, and only run the tests on the devices.

**Comment by whesse** [comment]
The change to the buildbot is not working - will work more on it tomorrow.  The DART_NUMBER_OF_CORES environment variable isn't making it all the way to the build.py command.

**Comment by rmacnak-google** [comment]
MIPS is no longer supported.
