### ISSUE TITLE
Removing dartdocgen from SDK

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24368]
We can remove dartdocgen from the SDK. We should probably do this fairly soon to catch any impact.

* starting from 1.12 we've printed out a deprecation warning
* starting in 1.12, we're shipping dartdoc tool

**Comment by sethladd** [comment]
cc @keertip to confirm
cc @mit-mit for label triaging (not sure how to triage this)
cc @whesse for impact on SDK generation scripts

**Comment by keertip** [comment]
I will put out a cl to remove it from the SDK.

**Comment by keertip** [comment]
Done with https://codereview.chromium.org/1356943002/ and https://codereview.chromium.org/1353213002/
