### ISSUE TITLE
Tear-off syntax doesn't find setter

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24367]
Run the following code:
```dart
class C {
  void set m(int val) {}
}

main() {
  var o = new C();
  var i = o#m;
}
```
Result: 
Unhandled exception:
Class 'C' has no instance getter 'm'.
NoSuchMethodError: method not found: 'm'
Receiver: Instance of 'C'

According "16.18.3 General Closurization" value of i should be "closurization of setter f on object o"

Tested on Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:28:05 2015) on "linux_x64"

**Comment by lrhn** [comment]
This is correct behavior. To extract the setter you need to write `o#m=`.
The name of the setter is `m=`, and the name of the getter is `m`. That allows you to distinguish the two.
