### ISSUE TITLE
when the analysis server can't bind to its diagnostics port, it throws an exception

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24363]
When starting the analysis server up with the option `--port=xyz`, if it can't bind to the port, I _beleive_ it throws an exception. I see an error message in the stdout stream, and the AS is left in an odd state.

The AS should guard against the exception, even if it does print an error message to the stdout stream.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1349263002/
