### ISSUE TITLE
Dart spec grammar includes unused rule

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#24373]
The dart spec includes this rule in the grammar:

```
getOrSet: get | set;
```

The `getOrSet` rule is not referred to anywhere in the spec.

**Comment by sethladd** [comment]
cc @gbracha

**Comment by eernstg** [comment]
Fixed in https://github.com/dart-lang/language/commit/e163637d1537ccc9ccde1d25ca87b82286aa634d.
