### ISSUE TITLE
No completion depending on position in source 

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#24377]
Tested with _Analysis Server v1.9.0, SDK 1.12.0_ on Atom and on dartpad.

With the following code `a` doesn't have a propagated type and you don't have completion with `int` members.

```dart
final b = a.
final a = 1;
```

If you switch the declarations `a` has the `int` propagated type and useful completions.

```dart
final a = 1;
final b = a.
```

**Comment by bwilkerson** [comment]
That's very strange. I thought we had disabled type propagation of static variables because of this ordering problem.

**Comment by a14n** [comment]
humm, disable type propagation is quite extreme. Usually you declare variable in the good order so this issue will not arise frequently. Having to add type annotation on every static variable is really worse that living with this little issue. So forget this issue and keep type propagation on static members ;)

**Comment by jwren** [comment]
Issue no longer exists, even without types annotated, and in "wrong" order.

Analysis Server 1.16

![image](https://cloud.githubusercontent.com/assets/1533520/14861140/d2a714e0-0c60-11e6-9b22-71b711c1e577.png)
