### ISSUE TITLE
Dart VM big integer numerics 5x slower than Python 3 + XMPZ

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#24378]
[Python 3 + XMPZ beats Dart VM 5x](http://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=dart&lang2=python3).

Benchmark code:
- [Python 3](http://benchmarksgame.alioth.debian.org/u64q/program.php?test=pidigits&lang=python3&id=5)
- [Dart](http://benchmarksgame.alioth.debian.org/u64q/program.php?test=pidigits&lang=dart&id=1)

**Comment by johnmccutchan** [comment]
What are MP numerics?

**Comment by yjbanov** [comment]
"multiple precision", a.k.a. "arbitrary precision".

**Comment by yjbanov** [comment]
Feel free to update the description to something more recognizable.

**Comment by munificent** [comment]
Closing because Dart no longer has big integers as its default integer representation.

**Comment by mraleph** [comment]
We still have `BigInt` class though - so it would be good to check where are we standing.

**Comment by srawlins** [comment]
@yjbanov your link in the description is dead. Do you know if it has moved?

**Comment by mraleph** [comment]
I think it has moved here: https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/pidigits.html

Though now Dart program is actually failing, instead of just being slow:

https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-dart-1.html

**Comment by yjbanov** [comment]
Closing due to lack of clarity about the problem.
