### ISSUE TITLE
Finish moving pkg/fixnum to it's own GitHub project

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24379]
We never deleted the content out of the sdk – and there have been deployments from the SDK since the migration started.

**Comment by mit-mit** [comment]
@cbracken, did you look into this? We have just one week left in 1.13 before cherry picking starts, so would really like to see this happen soon.

**Comment by mit-mit** [comment]
@kevmoo, can you dig a bit and figure out what the status is, pls?

**Comment by mit-mit** [comment]
Did we already announce that this is being moved?

**Comment by kevmoo** [comment]
@mit-mit there is no user facing work here. Just finishing the move to github – currently it's both in sdk/pkg and its own repo – need to merge in some fixes, etc.

**Comment by mit-mit** [comment]
Hi, did we get this completed?

**Comment by mit-mit** [comment]
Removing 1.13 flag as this does not change the actual SDK itself. The work is still important and should happen soon, though.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/9c5e6fa304d1b6ec9fecab5b60f86a6ef1713684
