### ISSUE TITLE
Add isLetter(), isDigit() etc to Dart core library

### ISSUE THREAD

**Issue by mishadynin** [dart-lang/sdk#24374]
Testing character categories is functionality that is reasonably expected to be part of the core API.
Currently, these functions can be found in

https://github.com/dart-lang/sdk/blob/da0363172adaa266ef2d44cf87e09b61a185e79d/pkg/analysis_server/lib/src/services/correction/strings.dart#L142
and
https://pub.dartlang.org/packages/unicode_helper

**Comment by lrhn** [comment]
This should be part of more general unicode support, which we don't currently have.

It's not clear to me that it should be in the platform libraries, but having a `dart:unicode` library may make sense.
