### ISSUE TITLE
Node validator test fails on firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24384]
There is a failure on dart2js firefox of the critical test html/node_validator_important_if_you_suppress_make_the_bug_critical_test/DOM_sanitization 

LInk to the failure: https://uberchromegw.corp.google.com/i/client.dart/builders/full-linux-3-4-be/builds/2642/steps/dart2js-ff%20tests%20--dart2js-batch%20failures/logs/stdio

Actual failure:
...
                         <a href="#testFilter=DOM_sanitization sanitizes embed">
                                  DOM_sanitization sanitizes embed
                                </a>.
                              </p>
                              <pre>Test failed: Caught NoSuchMethodError: method not found: 'get$_safeTagName' (J.getInterceptor$x(...).get$_safeTagName is not a function)</pre>
                            </td>
                          </tr><tr><td></td><td colspan="2"><pre>http://127.0.0.1:40642/root_build/generated_compilations/dart2js-sdk/tests_html_node_validator_important_if_you_suppress_make_the_bug_critical_test/test.js 17251:12  J.get$_safeTagName$x
                    http://127.0.0.1:40642/root_build/generated_compilations/dart2js-sdk/tests_html_node_validator_important_if_you_suppress_make_the_bug_critical_test/test.js 12859:75  dart&lt;._ValidatingTreeSanitizer._sanitizeUntrustedElement$2
                    http://127.0.0.1:40642/root_build/generated_compilations/dart2js-sdk/tests_html_node_validator_important_if_you_suppress_make_the_bug_critical_test/test.js 12914:13  dart&lt;._ValidatingTreeSanitizer_sanitizeTree_walk.call$2

**Comment by alan-knight** [comment]
Fixed in https://codereview.chromium.org/1365093003
