### ISSUE TITLE
Make ARM builds automatically and public available  

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#24383]
There is Dart builds for ARM available on the dart-misc mailing list but only for the 1.12.0 version:

https://groups.google.com/a/dartlang.org/d/msg/misc/Ee-IKvFNGMw/bHTkY19gLgAJ

The ARM build is missing again with the new 1.12.1 version so it seems like the ARM version is not automatically built with new Dart releases. Please make this builds automatically.

Also, it would be nice if the ARM version is added to the Dart download page:

https://www.dartlang.org/downloads/archive/

**Comment by whesse** [comment]
The arm SDKs are now uploaded for the most recent stable and dev builds, and will be added to all new future builds.  I haven't yet written a script to automate it.  The request to put them on the dartlang.org downloads page is filed, at https://github.com/dart-lang/www.dartlang.org/issues/1463

**Comment by sebe** [comment]
Cool, I only need the 32bit arm for my raspberry pi 2, is there need for a separate 64bit arm sdk?
Is there a need for mips as well? I noticed that it was included in http://gsdview.appspot.com/dart-archive/channels/stable/release/1.12.0/sdk/

**Comment by whesse** [comment]
I only have done the 32-bit arm one.  I'm not sure the 64-bit one is stable, and what hardware it runs on, and if we have an automatic build of it.

**Comment by sebe** [comment]
Thanks, cool, I did a google and it seems ARM 64 cpu can run unmodified ARMv7 32-bit binaries anyway.
Also other than mobile devices, the main place I see a lot of arm chips are in chromebooks I think they are currently 32bit, there maybe a 64bit arm chromebook/chromeos device soon using the Nvidia Tegra X1, which is 64bit.
