### ISSUE TITLE
html/node_validator test failing on IE 11

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24387]
The test html/node_validator_important_if_you_suppress_make_the_bug_critical_test/dom_clobbering
is failing on IE 11.  Example failure report:

                              <p>Expectation: 
                                <a href="#testFilter=dom_clobbering tagName makes containing form invalid">
                                  dom_clobbering tagName makes containing form invalid
                                </a>.
                              </p>
                              <pre>Expected: 'FORM'
                      Actual: InputElement:&lt;input&gt;
                       Which: InputElement:&lt;input&gt;is not a string
                    </pre>
                            </td>
                          </tr><tr><td></td><td colspan="2"><pre>http://127.0.0.1:49751/root_build/generated_compilations/dart2js-sdk/tests_html_node_validator_important_if_you_suppress_make_the_bug_critical_test/test.js 17042:11  SimpleConfiguration.onExpectFailure$1
                    http://127.0.0.1:49751/root_build/generated_compilations/dart2js-sdk/tests_html_node_validator_important_if_you_suppress_make_the_bug_critical_test/test.js 16995:9   _ExpectFailureHandler.fail$1

**Comment by alan-knight** [comment]
Fixed in https://codereview.chromium.org/1365093003/
