### ISSUE TITLE
_methodNameFromUri gets bad Uri

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24388]
#0      _Utf8Decoder.convert (dart:convert/utf.dart:554)
#1      Utf8Decoder.convert (dart:convert/utf.dart:346)
#2      Utf8Codec.decode (dart:convert/utf.dart:66)
#3      Uri._uriDecode (dart:core/uri.dart:2346)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#5      ListIterable.toList (dart:_internal/iterable.dart:219)
#6      Uri.pathSegments (dart:core/uri.dart:1016)
#7      Message._methodNameFromUri (message.dart:48:13)
#8      Message.Message.fromUri (message.dart:55:31)
#9      Server._requestHandler (server.dart:150:23)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1103)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#14     _StreamController._add (dart:async/stream_controller.dart:616)

**Comment by iposva-google** [comment]
And the rest of the trace is here...

#15     _StreamController.add (dart:async/stream_controller.dart:562)
#16     _HttpServer._handleRequest (dart:io/http_impl.dart:2364)
#17     _HttpConnection._HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2117)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1103)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#21     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#22     _StreamController._add (dart:async/stream_controller.dart:616)
#23     _StreamController.add (dart:async/stream_controller.dart:562)
#24     _HttpParser._headersEnd (dart:io/http_parser.dart:387)
#25     _HttpParser._doParse (dart:io/http_parser.dart:709)
#26     _HttpParser._parse (dart:io/http_parser.dart:330)
#27     _HttpParser._onData (dart:io/http_parser.dart:819)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1103)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#31     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#32     _StreamController._add (dart:async/stream_controller.dart:616)
#33     _StreamController.add (dart:async/stream_controller.dart:562)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:1703)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1103)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#38     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#39     _StreamController._add (dart:async/stream_controller.dart:616)
#40     _StreamController.add (dart:async/stream_controller.dart:562)
#41     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1257)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#44     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

**Comment by iposva-google** [comment]
vm-service: Error: Unhandled exception:
Uncaught Error: FormatException: Bad UTF-8 encoding 0x80
Stack Trace:

**Comment by johnmccutchan** [comment]
Based on frame #9, this is a direct HTTP GET request. So, this isn't a WebSocket RPC from Observatory, it is likely a request from the browser (or curl, ...).

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1357023004/
