### ISSUE TITLE
html/svgelement_test/[inner,outer]html failing on Firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24386]
The tests are failing on Firefox on Windows:
html/svgelement_test/innerHtml
html/svgelement_test/outerHtml

They don't fail on linux.  The failing version on windows is FF 40, the passing version on linux is FF 34.

The tests are suppressed in the status file tests/html/html.status.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1345413004/

Will commit tomorrow morning.
