### ISSUE TITLE
using core.Resource in a Dart transformer leads to Build error

### ISSUE THREAD

**Issue by simon-void** [dart-lang/sdk#24382]
using the core.Resource class in a Barback transformer leads to a build error in the project referencing that transformer. In case of my [transformer project](https://github.com/simon-void/simple_resource_loading_transformer/blob/master/lib/transformer.dart) this error looks like this:
_Build error: Transform InsertCopyright on {your project} threw error: Load Error for "package:simple_resource_loading_transformer/copyright.txt": SocketException: OS Error: Connection refused_
a little bit more explanation in this [stackoverflow ticket](http://stackoverflow.com/questions/32660355/using-core-resource-in-a-dart-transformer-leads-to-build-error)

**Comment by sethladd** [comment]
This issue was moved to dart-lang/barback#65
