### ISSUE TITLE
dart2js test utils/source_mirrors_test timing out frequently

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24385]
This test timed out 3 times within 7 builds - this is getting very tedious.

Is this a known issue, or could it be a recent change, @whesse @kmillikin @asgerf ? I'm trying to get rid of as many timeouts in tests as possible, as they are slowing down everybody.

I'm trying to figure out if anything on the VM side may be causing it, but my own measurements on my machine show no slow-down at my change (bac82e259223), on the contrary: dart2js compilation was 41s after vs. 43s before.

More than 40s compilation time in ia32 release mode on a Z620 seems like a lot. Is it possible to reduce the size of the test?

http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-1-5-be/builds/12440/steps/dart2js-d8%20tests%20--minified%20--dart2js-batch%20failures/logs/stdio

http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-1-5-be/builds/12437/steps/dart2js-d8%20tests%20--minified%20--dart2js-batch%20failures/logs/stdio

http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-1-5-be/builds/12433/steps/dart2js-d8%20tests%20--minified%20--dart2js-batch%20failures/logs/stdio

**Comment by asgerf** [comment]
As far as I can tell the compiler has to compile itself and then run the actual test using d8. The bootstrapping is taking time, not really the test itself.

Bootstrapping tests will get slower as dart2js grows bigger (which it seems to be doing). It *could* be a specific thing we're doing that's causing a slowdown, like the massive use of mixins in the semantic visitor, but the incremental difference suggests it's just the size going up.

I guess we should mark bootstrapping tests as slow or stop running them?

Or start deleting lots of code in dart2js.

**Comment by sigmundch** [comment]
Sounds good to mark them as slow for now. Going forward I think Asger suggestion to delete some code in dart2js is quite feasible. In this specific case, I think source_mirrors could be one of the features that we'll get rid of (I believe it was only used for dartdocgen, which was just replaced by the new dartdoc tool).

**Comment by fsc8000** [comment]
Ping?

**Comment by asgerf** [comment]
Sorry, completely forgot to follow up on this.

https://codereview.chromium.org/1361133004/
