### ISSUE TITLE
dart2js: should produce deterministic output

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24391]
A couple tests seem to be failing in this FYI bot:

http://build.chromium.org/p/client.dart.fyi/builders/dart2js-dump-info-be/builds/7460/steps/Compare%20outputs/logs/stdio

```
(view as text)
@@@BUILD_STEP Compare outputs@@@
Running: diff -rq -x *\.json /tmp/tmpDnL7l8/normal /tmp/tmpDnL7l8/dump
Files /tmp/tmpDnL7l8/normal/dart2js-sdk/tests_html_custom_constructor_calls_created_synchronously_test/out.js and /tmp/tmpDnL7l8/dump/dart2js-sdk/tests_html_custom_constructor_calls_created_synchronously_test/out.js differ
Files /tmp/tmpDnL7l8/normal/dart2js-sdk/tests_html_custom_js_custom_test/out.js and /tmp/tmpDnL7l8/dump/dart2js-sdk/tests_html_custom_js_custom_test/out.js differ
@@@STEP_FAILURE@@@
ProcessDart2js_dump_info


--------------------------------------------------------------------------------
started: Mon Sep 21 13:16:46 2015
ended: Mon Sep 21 13:16:46 2015
duration: 0 secs
status: FAILURE
status reason: 
```

**Comment by sigmundch** [comment]
After we fix this, we can move the FYI bot back to the main waterfall and ensure it stays green.

**Comment by hterkelsen** [comment]
It's not just dump info vs non-dump info, two successive runs of dart2js will produce different output:
```
$ dart2js --out=out1.js --package-root=out/ReleaseIA32/packages tests/html/custom/constructor_calls_created_synchronously_test.dart
$ dart2js --out=out12.js --package-root=out/ReleaseIA32/packages tests/html/custom/constructor_calls_created_synchronously_test.dart
$ diff -q out1.js out2.js
Files out1.js and out2.js differ
```

**Comment by sigmundch** [comment]
Good point Harry. I also the idea you mentioned offline: we might want check whether 2 subsequent runs of dart2js with the same input and flags have the same output.

@iposva-google - does the VM has a mechanism to make sources of non-determinism more likely to show up while testing (for example, a way to force hash-codes to be generated at random with a different seed)?

**Comment by rakudrama** [comment]
Fix available: https://codereview.chromium.org/1358363002/

**Comment by sigmundch** [comment]
Thanks @rakudrama  for the fix in https://github.com/dart-lang/sdk/commit/8852bf9e14683b15607f9df42d69bd58acf873bc
