### ISSUE TITLE
assert_with_message_test fails on dart2js csp on content shell

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24397]
The test dart2js_extra/assert_with_message_test fails on the drt csp buildbot.
The failure is suppressed in status file tests/compiler/dart2js_extra/dart2js_extra.status

The error message is:
FAILED: dart2js-drt-checked release_ia32 dart2js_extra/assert_with_message_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:
CommandOutput[content_shell]:

stdout:
#READY
CONSOLE MESSAGE: line 78: {
  "type": "debug",
  "value": "test_controller.js started",
  "timestamp": 0
}
CONSOLE MESSAGE: line 78: {
  "type": "print",
  "value": "dart-calling-main",
  "timestamp": 0.071
}
CONSOLE MESSAGE: line 78: {
  "type": "sync_exception",
  "value": "Exception: Expect.isTrue(false, 'name: <<NullError: method not found: 'constructor' on null>> (F) is TypeError') fails.\nStack: Expect.isTrue(false, 'name: <<NullError: method not found: 'constructor' on null>> (F) is TypeError') fails.\n    at dart.d (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:682:3)\n    at dart.aB (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1510:24)\n    at dart.aC (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1509:3)\n    at ak.dart.ak.$2 (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1295:3)\n    at dart.c5 (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1242:3)\n    at dart.bw (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1266:3)\n    at dartMainRunner (http://127.0.0.1:41255/root_dart/tools/testing/dart/test_controller.js:311:5)\n    at http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1638:55\n    at init.currentScript (http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1634:55)\n    at http://127.0.0.1:41255/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1637:84",
  "timestamp": 0.121
}
Content-Type: text/plain
Running /mnt/data/b/build/slave/dart2js-drt-linux-csp-be/build/sdk/tests/compiler/dart2js_extra/assert_with_message_test.dart

FAIL
#EOF
#EOF

**Comment by whesse** [comment]
Only fails in checked mode

**Comment by rakudrama** [comment]
I have fixed the bug. Thanks for tracking this issue.
