### ISSUE TITLE
await expressions not properly skipped by "??="

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24392]
In the following program:

    import 'dart:async';
    Future<int> f() async {
      print('f() called');
      return 2;
    }
    main() async {
      int x = 1;
      x ??= await f();
      print(x);
    }

I would expect evaluation of the expression `await f()` to be skipped, due to the fact that `x` has a non-null value at the time the statement `x ??= await f();` is reached.  Therefore, the program should simply print:

    1

However, when I run it under the VM, it prints:

    f() called
    1

It appears that the await expression is being executed anyway, and then its result is discarded.

Dart2js does not show this problem.

**Comment by lrhn** [comment]
I hit this too. Quite annoying and hard to debug.

**Comment by micahbeeman-wf** [comment]
Also encountered this.

**Comment by fsc8000** [comment]
Fixed with 598018bd212a072e025866865ba4e5a1bd6841c7
