### ISSUE TITLE
Chrome states that SDK is not commonly downloaded and may be dangerous

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24395]
When downloading the SDK zip for MacOS from the download archive, Chrome puts up warning saying the download may be dangerous.
![screen shot 2015-09-22 at 09 42 45](https://cloud.githubusercontent.com/assets/13644170/10013073/5337b30c-610e-11e5-9151-3418126b70b2.png)

**Comment by mit-mit** [comment]
Learn More link goes here:
https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1

**Comment by mit-mit** [comment]
Does not repro with same Chrome version on Linux.

**Comment by mit-mit** [comment]
Repros on Windows also.

**Comment by mit-mit** [comment]
Opened Chrome bug:
https://code.google.com/p/chromium/issues/detail?id=534735&thanks=534735&ts=1442908966

**Comment by jmesserly** [comment]
looks like the Chrome bug was WontFixed, anything we can still do?

**Comment by mit-mit** [comment]
Yes, they followed up with me in email, and I am looking into some options.

**Comment by mit-mit** [comment]
This has been resolved with some help form the safe browsing team. If any sees this again, please let me know.
