### ISSUE TITLE
Calls to dart:web_gl RenderingContext fail after dart2js compilation

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#24390]
Hi guys,

Was told I should file a bug report so here it is brace yourselves!

Been porting the Quake 3 engine to dart and love the language!

I'm halfway through the port and going well with that - I have a BSP tree rendered and working in pure dart and the scene renders perfectly in the dartium browser I'm so happy!  .. There is just one problem.. After I do a dart2js compile of the web application, most main WebGL API calls fail. I'm talking about calls like gl.bufferData, all the WebGLObject creation functions like gl.createTexture(), createShader(). I've built a workaround which makes use of JS interop (dart:js) to proxy the RenderingContext and pipe API calls to javascript code that executes them - this seems to work but is a dirty hack. I suspect dart might be wrapping the WebGL Objects that are created by the API. 
I'm getting messages i.e. after a texImage2D() call like the 9th parameter is not a valid ArrayBufferView. 
I've managed to track down and inspect the buffer data object in javascript and found that it is indeed and instance of an ArrayBuffer.

The only work around is if I create functions like these in javascript and call them from dart. 
Basically reinstantiating and filling my webgl objects just before I use them by my API call (even if they were already the correct WebGL type from dart) is the only way I can get an API call through. The gl context I pass through to the javascript function is not a dart RenderingContext but the underlying WebGLRenderingContext for my canvas.

var jsinterop = 
{
        texImage2D_09: function(gl, target, level, internalformat, width, height, border, format, type, dt, pixels)
        {  
            if(pixels == null)
            {
                return gl.texImage2D(target, level, internalformat, width, height, border, format, type, null);
            }
            else
            {
                return 
                gl.texImage2D(target, level, internalformat, width, height, border, format, type, 
                        dt == 'Uint8ClampedArray'  ? new Uint8ClampedArray(pixels) 
                    : ( dt == 'Uint8Array'  ? new Uint8Array(pixels) 
                    : ( dt == 'Uint32Array' ? new Uint32Array(pixels) 
                    : ( dt == 'Uint16Array' ? new Uint16Array(pixels) 
                    : ( dt == 'Int8Array'  ? new Int8Array(pixels) 
                    : ( dt == 'Int16Array'  ? new Int16Array(pixels) 
                    : ( dt == 'Int32Array'  ? new Int32Array(pixels) 
                    : ( dt == 'Float32Array'  ? new Float32Array(pixels) 
                    : ( dt == 'Float64Array'  ? new Float64Array(pixels) : pixels))))))))
                );
            }
        }
};

I'm running Dart Editor version 1.10.0.release (STABLE)
Dart SDK version 1.10.0, Dartium browser Version 39.0.2171.0 custom.
- Note that Dart Editor says there's an update available but i cant run it in the IDE I think I need to run a command - I'm running Linux Mint 17.2 this could be an issue but I'm sure I've got an up to date dart:web_gl library.

If you guys would like more code or info I am able to provide what is required.

Regards,
Gerallt
geralltf at gmail.com
http://alpha.ivsoftware.org

**Comment by RealityDaemon** [comment]
A little dart code of some of the hacks I put in place to get me by.. 
part of tech3;

Symbol symGetError = new Symbol('getError');
Symbol symGetActiveAttrib = new Symbol('getActiveAttrib');
Symbol symTexImage2D = new Symbol('texImage2D');
Symbol symCreateTexture  = new Symbol('createTexture');
Symbol symBindTexture  = new Symbol('bindTexture');
Symbol symCreateShader  = new Symbol('createShader');
Symbol symShaderSource  = new Symbol('shaderSource');
Symbol symCompileShader = new Symbol('compileShader');
Symbol symGetShaderParameter = new Symbol('getShaderParameter');
Symbol symGetShaderInfoLog = new Symbol('getShaderInfoLog');
Symbol symDeleteShader = new Symbol('deleteShader');
Symbol symCreateProgram = new Symbol('createProgram');
Symbol symAttachShader = new Symbol('attachShader');
Symbol symLinkProgram = new Symbol('linkProgram');
Symbol symGetProgramParameter = new Symbol('getProgramParameter');
Symbol symDeleteProgram = new Symbol('deleteProgram');
Symbol symGetAttribLocation = new Symbol('getAttribLocation');
Symbol symGetActiveUniform = new Symbol('getActiveUniform');
Symbol symGetUniformLocation = new Symbol('getUniformLocation');

Symbol sym__interop_texImage2D_09 = new Symbol('texImage2D_09');
Symbol sym__interop_texImage2D_06 = new Symbol('texImage2D_06');

dynamic processWebGLPipe(Symbol method_symbol, List parameterlist, String method_name, rendering_context renderer)
{
  var gl = renderer.gl;
  var result = null;
  var p = parameterlist;
  

  ///////////////////////// TEXTURING /////////////////////////
  if(method_symbol == symTexImage2D)
  {
    if(parameterlist.length == 6)
    {
      result = pipe_texImage2D_06(p[0], p[1], p[2], p[3], p[4], p[5]);
    }
    else if (parameterlist.length == 9)
    {
      result = pipe_texImage2D_09(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8]);
    }
  }
  else if (method_symbol == symCreateTexture)
  {
    result = wrapFromJSObject(WebGLInterop.api_call(symCreateTexture, [ gl ]));
  }
  else if (method_symbol == symBindTexture)
  {
    result = WebGLInterop.api_call(symBindTexture, [ gl, p[0], p[1] ]);
  }
  ///////////////////////// SHADERS /////////////////////////
  else if (method_symbol == symCreateProgram)
  {
    result = wrapFromJSObject(WebGLInterop.api_call(symCreateProgram, [ gl ]));
  }
  else if (method_symbol == symGetProgramParameter)
  {
    result = WebGLInterop.api_call(symGetProgramParameter, [ gl, p[0], p[1] ]);
  }
  else if (method_symbol == symAttachShader)
  {
    WebGLInterop.api_call(symAttachShader, [ gl, p[0], p[1] ]);
  }
  else if(method_symbol == symLinkProgram)
  {
    WebGLInterop.api_call(symLinkProgram, [ gl, p[0] ]);
  }
  else if (method_symbol == symCreateShader)
  {
    result = wrapFromJSObject(WebGLInterop.api_call(symCreateShader, [ gl, p[0] ]));
  }
  else if (method_symbol == symShaderSource)
  {
    WebGLInterop.api_call(symShaderSource, [ gl, p[0], p[1] ]);
  }
  else if (method_symbol == symCompileShader)
  {
    WebGLInterop.api_call(symCompileShader, [ gl, p[0] ]);
  }
  else if(method_symbol == symGetShaderParameter)
  {
    result = WebGLInterop.api_call(symGetShaderParameter, [ gl, p[0], p[1] ]);
  }
  else if(method_symbol == symGetShaderInfoLog)
  {
    result = WebGLInterop.api_call(symGetShaderInfoLog, [ gl, p[0] ]);
  }
  else if(method_symbol == symDeleteShader)
  {
    WebGLInterop.api_call(symDeleteShader, [ gl, p[0] ]);
  }
  else if(method_symbol == symDeleteProgram)
  {
    WebGLInterop.api_call(symDeleteProgram, [ gl, p[0] ]);
  }
  else if(method_symbol == symGetActiveAttrib)
  {
    result = wrapFromJSObject(WebGLInterop.api_call(symGetActiveAttrib, [ gl, p[0], p[1] ]));
  }
  else if(method_symbol == symGetAttribLocation)
  {
    result = WebGLInterop.api_call(symGetAttribLocation, [ gl, p[0], p[1] ]);
  }
  else if(method_symbol == symGetActiveUniform)
  {
    result = wrapFromJSObject(WebGLInterop.api_call(symGetActiveUniform, [ gl, p[0], p[1] ]));
  }
  else if(method_symbol == symGetUniformLocation)
  {
    result = WebGLInterop.api_call(symGetUniformLocation, [ gl, p[0], p[1] ]);
  }
  /////////////////////// MISC //////////////////////////////
  else
  {
    try
    {
      result = WebGLInterop.gl_call(gl, method_name, parameterlist);
    }
    catch(ex) 
    {
      /* just ignore. Any issues javascript side are not our problem
       * We can however inspect the error state later on */
    }
  }
  
  return result;
}
// https://www.khronos.org/registry/webgl/specs/1.0/
dynamic pipe_texImage2D_09(int target, int level, int internalformat, 
                   int width, int height, int border, 
                   int format, int type, [dynamic pixels])
{
  // pixels must be ArrayBufferView but is nullable
  dynamic result;
  List params = null;;
  
  if(pixels==null)
  {
    params = [  gl, target,  level, internalformat, width, 
                height, border, format, type, ' '  ];
  }
  else
  {
    JsArray arr = new JsArray.from(pixels);
    String dt = getTypedDataArrayType(pixels);
    
    
    
    params = [  gl, target,  level, internalformat,
                 width, height, border, 
                format,   type, dt, arr  ];
  }
  
  result = WebGLInterop.api_call(sym__interop_texImage2D_09, params);
  
  return result;
}

  static dynamic api_call(Symbol api_symb, List args)
  {
    String funct = symbol_name(api_symb);
    
    JsObject interop = context['jsinterop'];
    dynamic result = interop.callMethod(funct, args);
    return result;
  }

**Comment by RealityDaemon** [comment]
dynamic wrapFromJSObject(JsObject j)
{
  
  if(j != null)
  {
    String type = j.toString();

    if(type=="[object WebGLTexture]")
    {
      GLTexture tex = new GLTexture();
      tex.underlying = j;
      return tex;
    }
    if(type=="[object WebGLShader]")
    {
      GLShader s = new GLShader();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLBuffer]")
    {
      GLBuffer s = new GLBuffer();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLActiveInfo]")
    {
      GLActiveInfo s = new GLActiveInfo();
      s.underlying = j;
      s.name = j['name'];
      s.size = j['size'];
      s.type = j['type'];
      return s;
    }
    if(type=="[object WebGLProgram]")
    {
      GLProgram s = new GLProgram();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLUniformLocation]")
    {
      GLUniformLocation s = new GLUniformLocation();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLFramebuffer]")
    {
      GLFramebuffer s = new GLFramebuffer();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLRenderbuffer]")
    {
      GLRenderbuffer s = new GLRenderbuffer();
      s.underlying = j;
      return s;
    }
    if(type=="[object WebGLShaderPrecisionFormat]")
    {
      GLShaderPrecisionFormat s = new GLShaderPrecisionFormat();
      s.underlying = j;
      s.precision = j['precision'];
      s.rangeMax = j['rangeMax'];
      s.rangeMin = j['rangeMin'];      
      return s;
    }
  }
  return j;
}

**Comment by sigmundch** [comment]
I wonder whether the dart:web_gl is up to date for chrome 39 (the version at which Dartium is today), but not for Chrome 45 (current stable chrome)

/cc @alan-knight @terrylucas is dart:web_gl generated from the Chrome 39 IDLs? Could that be the issue here? (has there been breaking changes since Chrome 39?)

**Comment by RealityDaemon** [comment]
For my testing I'm using Chrome Version 44.0.2403.157  and Firefox version 40.0.3.
I would have thought that it wouldn't matter much what browser I'm using or what IDL dart:web_gl is based on atm, just as long as it implements WebGL version 1.0 or 2.0.
Come to think of it I've used dart:web_gl before but never tried JS compilation. Could it maybe be not what API dart complies with but how it uses it?

**Comment by RealityDaemon** [comment]
JavaScript is a bit of a minefield that and how JavaScript uses WebGL. 
I really dislike it how in JavaScript I have to reinstantiate my TypeData objects right before a GL call like this: 

gl.texImage2D(target, level, internalformat, width, height, border, format, type, new Uint8Array(pixels) );

for the call to go through properly without gl.GetError() returning an error.

If I declare my TypeData object like this:

var pixels =  new Uint8Array (data);

.. maybe do something else here 

gl.texImage2D(target, level, internalformat, width, height, border, format, type, pixels ); // then perform my GL api call here

the API call fails unless I use the API like above

**Comment by RealityDaemon** [comment]
Of course if I'm in pure dart declaring my TypeData objects and using them later without having to do what is inefficient - reinstantiate and fill the objects right before a call - works if I'm running pure dart code on the Dart VM but not when compiled. This is great this is how the API should be used in dart - but in JavaScript I believe it works a little differently. I think something needs to happen to marry the two in this case
