### ISSUE TITLE
co19/LayoutTests/fast/forms/change-form-element-document-crash_t01 failing on firefox 40/windows

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24409]
Might be due to the firefox update, or might be related to Dartium JsInterop changes.

**Comment by sigmundch** [comment]
@alan-knight  - I noticed the status file marks this test as failing, but this is making the dart2js-linux bots red. See for example: https://build.chromium.org/p/client.dart/builders/full-linux-2-4-be/builds/3228/steps/dart2js-ff%20tests%20--dart2js-batch/logs/stdio

Is this a windows only failure?

**Comment by sigmundch** [comment]
it appears that it is also passing in windows here https://build.chromium.org/p/client.dart/builders/full-win7-ie11-2-4-be/builds/6337/steps/dart2js-ff%20tests%20--dart2js-batch/logs/stdio

**Comment by alan-knight** [comment]
Unsuppressed in https://codereview.chromium.org/1496383002
