### ISSUE TITLE
Analysis Server doesn't provide semantic highlighting for Dart code in HTML

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24401]
Although client subscribes to "HIGHLIGHTS" for both Dart and HTML files it receives notifications (`com.google.dart.server.AnalysisServerListenerAdapter#computedHighlights`) for Dart files only.

**Comment by bwilkerson** [comment]
I'm guessing that this is now a non-issue. Please re-open if that's not true.
