### ISSUE TITLE
No API search in safari iPhone portrait mode

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#24418]
Search is missing from api.dartlang.org on Safari on iPhone in portrait mode. Work around: use landscape mode. 

![image](https://cloud.githubusercontent.com/assets/5689005/10055154/f6422632-6234-11e5-844e-e849502c5ef1.png)
![image](https://cloud.githubusercontent.com/assets/5689005/10055153/f641efaa-6234-11e5-9b05-eaa9dd1b643a.png)

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#924
