### ISSUE TITLE
Precision of SIMD FP operations

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24416]
What is the expected precision for SIMD arithmetic?

Some architectures don't support denormalized FP numbers in their vector instruction set.

From the ARM documentation: "NEON always uses flush-to-zero mode."

We have SIMD tests that have denormalized numbers as results. (e.g. co19/LibTest/typed_data/Float32x4/operator_multiplication_A01_t01)

On ARM those operations will return 0 if they are computed using the NEON instructions which areused in optimized code and intrinsics.

Either we accept FTZ mode for Float32x4 operations, or we can't use the accelerated instruction set on some architectures.

I'm inclined to allow FTZ mode for Float32x4 and Float64x2 since they are used for high-performance computations and we want to use NEON instructions. What do you think @johnmccutchan ?

**Comment by johnmccutchan** [comment]
Precision of denormal arithmetic for SIMD has always been left undefined. This remains true in the now finalized SIMD.js specification. If we have tests that depend on the support (or lack of support) for denormal arithmetic, we should ensure that the status files reflect which architectures the test will pass on.

**Comment by fsc8000** [comment]
Ok, I updated the test status for now (see my latest CL), but I guess co19 should be updated to reflect that.

**Comment by iposva-google** [comment]
@johnmccutchan can you please file a co19 bug and reference it here?

**Comment by johnmccutchan** [comment]
https://github.com/dart-lang/co19/issues/5

**Comment by fsc8000** [comment]
We did not roll co19 since Oct 2015 @whesse ?

**Comment by whesse** [comment]
Maybe today.
