### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24419]
On both

  https://www.dartlang.org/tools/observatory/cpu-profile.html#defining-user-tags

and

  https://www.dartlang.org/tools/observatory/tags.html

There are links to https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart-developer, which is broken.

**Comment by kwalrath** [comment]
cc @Sfshaza. Should we move these to https://github.com/dart-lang/www.dartlang.org/issues?

**Comment by boasjls** [comment]
Adding to this. There are numerous broken links found in the dart-samples section: (https://www.dartlang.org/samples/)
Specifically the links to the source and readme files on github are broken for the following samples:

*polymer.dart*
	 - Searchable List
	 - Polymer and internationalization
	 - A task management tool

*Using Javascript from Dart*
	 -- all

*Working with the I/O library*
	 -- all

*Animation and graphics*
	 - 2D solar system animation

*Touch events*
	 -- all

**Comment by kwalrath** [comment]
Yikes. Thanks for the report, @boasjls.

**Comment by srawlins** [comment]
I mentioned a few of these at dart-lang/www.dartlang.org#1479. I don't think they're all fixed though.

**Comment by kwalrath** [comment]
All the sample issues should be fixed. I've filed https://github.com/dart-lang/www.dartlang.org/issues/1489 to track the others.
