### ISSUE TITLE
Annotate hints with whether they are JS only

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#24415]
I'm currently working on a VM only project. It will not be compiled to Javascript.

I'm still given a large number of info items which read:
"When compiled to JS, this test might return true when LHS is an int ........."

As I'm not compiling to JS, this is just noise. Could we add a marker to the metadata associated with the info saying that this info only applies when compiled to JS so I can ask the tooling not to display them?

cc @devoncarew - this is primarily affecting me within Atom primarily due to the increased visual intensity of info messages.

**Comment by bwilkerson** [comment]
The client can do even better. Analysis server has a request to set analysis options, and one of the options is `generateDart2jsHints`. The client can set this to false. Unfortunately, these options are only supported at a global level, not on a per analysis root basis.

**Comment by devoncarew** [comment]
What SDK version are you using? These hints should have been changed from opt-out to opt-in. This was done for the analyzer CLI. I can't say whether the same change was made for the analysis server.

**Comment by lukechurch** [comment]
Dart VM version: 1.12.0-dev.1.0 (Tue Jun 30 03:40:06 2015) on "macos_x64"

**Comment by bwilkerson** [comment]
As far as I can see from the code, the default value for this flag should be 'false' everywhere. These hints should only be getting returned if the client is explicitly enabling them.

**Comment by devoncarew** [comment]
That version of 1.12 dev doesn't have that behaviour.
