### ISSUE TITLE
Null-coalescing operator with Map literal in initializer causes dart2js error

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#24410]
The following program works fine in the VM, but fails to compile via dart2js.

``` dart
class A {
  final map;
  A() : this.map = null ?? {};
}

main() {
  new A();
}
```

The error:

```
Error: Expected a declaration, but got ';'.
  A() : this.myField = null ?? {};
                                 ^
Error: Compilation failed.
```

This seems to only happen with the map literal, and only in the initializer. 

Also worth noting that wrapping the literal in parentheses avoids the issue:

``` dart
  A() : this.map = null ?? ({});
```

---

Dartpad demonstrating the issue: https://dartpad.dartlang.org/378810888e5f811dc032

**Comment by matanlurey** [comment]
Fixed in Dart2.
