### ISSUE TITLE
Dartium fails to run applications which uses WebGL

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#24424]
**Summary:**
Dartium (1.13.0-dev.4.0) fails to run applications that uses WebGL. A 'black screen' is rendered inside the canvas element.

**What steps will reproduce the problem?**
1) Clone the repository: https://github.com/dart-lang/sample-pop_pop_win
2) Run pub get followed by pub serve
3) Open Dartium and navigate to the url where the application is hosted

**What is the expected output? What do you see instead?**
*Expected:*
The application loads and runs without any issues

*Actual:*
After the application is loaded only a black screen is rendered

**What version of the product are you using?**
Dartium (release) - 1.13.0-dev.4.0
Dart-SDK - 1.13.0-dev.4.0

**On what operating system?**
Windows 7 SP1(64bit)

**Please provide any additional information below.**
The issue have not been seen in any recent Dartium builds, and can specifically not be reproduced using the previous build (1.13.0-dev.3.1).
The issue has also been reproduced on MacOS.

**Comment by alan-knight** [comment]
As with 22428, this works fine for me in bleeding edge and I don't see any dev.4.0 build.
