### ISSUE TITLE
Dartium fails to run applications which uses polymer.dart

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#24428]
**Summary:**
Applications which uses polymer.dart no longer work using the Dartium 1.13.0-dev.4.0 build.

**What steps will reproduce the problem?**
1) Clone https://github.com/dart-lang/dart-tutorials-samples
2) Navigate to the `polymer_list` sub-directory
3) Run `pub get` followed by `pub serve`
4) In dartium navigate to the url where the application is hosted

**What is the expected output? What do you see instead?**
_Expected:_
The sample-application loads and runs without issues

_Actual:_
The sample-application yields the following console output:

```Uncaught Unhandled exception:
type 'JsObjectImpl' is not a subtype of type 'HtmlElement' of 'element'.
#0      PolymerDeclaration.PolymerDeclaration (package:polymer/src/declaration.dart:117:27)
#1      _hookJsPolymer.registerDart.<anonymous closure> (package:polymer/src/loader.dart:102:15)
#2      _RootZone.run (dart:async/zone.dart:1160)
#3      _hookJsPolymer.registerDart (package:polymer/src/loader.dart:101:19)```

**What version of the product are you using?**
Dartium (release) 1.13.0-dev.4.0
DartSDK 1.13.0-dev.4.0

**On what operating system?**
Windows 7 SP1(64bit)

**Please provide any additional information below.**
The issue can not be reproduced using a previous version of Dartium (specifically tested with 1.13.0-dev.3.1)

All of the (polymer.dart) samples tested yields console output similar to the above.

**Comment by alan-knight** [comment]
This seems to work for me in bleeding edge. As far as I can see dev.4.0 isn't there yet. Where are you getting it from?

**Comment by boasjls** [comment]
It was downloaded from:
http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.13.0-dev.4.0/
