### ISSUE TITLE
Generating a precompiled snapshot should not require using dart_no_snapshot

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24427]
dart_no_snapshot does not work for cross-compiled builds: it has absolute source paths built-in from compile-time.

We should make --gen-precompiled-snapshot work with the normal dart binary @rmacnak-google.

For now I disabled precompilation_test for targets that use cross-compiled builds.

**Comment by iposva-google** [comment]
Actually we should use gen_snapshot to generate the full snapshot and precompilation output.

**Comment by fsc8000** [comment]
+1 for using gen_snapshot. But the issue remains:

gen_snapshot has absolute source paths compiled into it. Should we maybe just add a command-line option to gen_snapshot to specify the base-path for the library sources?

**Comment by rmacnak-google** [comment]
We've been created precompiled snapshots from dart_bootstrap and gen_snapshot for some time now.
