### ISSUE TITLE
Compile-error when static and instance members declared

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24437]
If to declare static method with the same name as in superclass error occurs
```dart
class A {
 int m() => 1;
 int s() => 2;
}
class C extends A {
 int m();
 static int s() => 0;
}
main() {
 C c = new C();
}
```
dartanalyzer gives [error] The name 's' is already defined in 'A'
dart produces 
static method 's' of class 'C' conflicts with instance member 's' of super class 'A'
 static int s() => 0;
 ^
(Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:28:05 2015) on "linux_x64")

But where in the specification it is said about compile error here? The only that I was able to find (in chapters "10.9.1 Inheritance and Overriding" and "10.1 Instance Methods")

"It is a static warning if a class C declares an instance method named n and an accessible
static member named n is declared in a superclass of C." and "It is a warning if you have an static member named m in your class or any superclass (even though it is not inherited) and an instance member of the same name"

But both of this about having static method in superclass and instance method in the class. In the example above we have instance method in the superclass and static method in the class. Please point to the place in the specification where it is said that there should be an error in this case

**Comment by bwilkerson** [comment]
Gilad can correct me if I'm wrong, but section 10 states:

It is a compile-time error if a class has an instance member and a static member with the same name.

I believe that the meaning of "has" is "declares or inherits".
