### ISSUE TITLE
Nested lists in Dartium can't be passed in postMessage

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24432]
Dart lists have their own prototype, and if you pass them you get an error that the object can't be cloned. Even if we copy them into ordinary lists, then we lose identity so cyclic structures don't work. See tests/html/postmessage_structured_test/primitives.
@jacob314

**Comment by alan-knight** [comment]
This looks like it might be fixed via https://codereview.chromium.org/1383903002

The test starts passing, though it isn't obvious to me why it helps.

**Comment by jacob314** [comment]
Is this fixed?

**Comment by alan-knight** [comment]
Yes, it seems to be.
