### ISSUE TITLE
Warnings during build

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24435]
The following warnings how up during a build.
It seems whatever is being built must be seriously broken.

```
  ACTION Creating compiler_isolate.dart.js out/ReleaseIA32/obj/gen/compiler_isolate.dart.js
src/leap.dart:19:5:
Hint: Library 'file:///usr/local/google/home/sra/Dart/sdk/site/try/src/compilation.dart' doesn't export a 'compilerIsolate' declaration.
Try removing 'compilerIsolate' from the 'show' clause.
    compilerIsolate,
    ^^^^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:77:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ClassBuilder' declaration.
Try removing 'ClassBuilder' from the 'show' clause.
    ClassBuilder,
    ^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:78:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ClassEmitter' declaration.
Try removing 'ClassEmitter' from the 'show' clause.
    ClassEmitter,
    ^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:80:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ContainerBuilder' declaration.
Try removing 'ContainerBuilder' from the 'show' clause.
    ContainerBuilder,
    ^^^^^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:81:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'MemberInfo' declaration.
Try removing 'MemberInfo' from the 'show' clause.
    MemberInfo,
    ^^^^^^^^^^
```

**Comment by johnniwinther** [comment]
I've added a hint for show or hide combinator that doesn't match anything. These does not indicate that anything is broken, but that the imports/exports contain some noise (similar to the check for unused import performed by the analyzer)

**Comment by nex3** [comment]
I strongly dislike this hint. It adds a lot of bogus noise for valid declarations in packages. Packages are often written to be compatible with a wide array of possible dependencies, and sometimes it's necessary to hide a name that's only exported in some versions of those dependencies.

For example, the `test` package imports the `matcher` package. Old versions of `matcher` declared a function named `throwsA()`, but in more recent versions that function was moved to `test`. `test` wants as wide a constraint as possible on `matcher`, so it includes the old versions and writes:

```dart
import "matcher" hide throwsA;

Matcher throwsA(matcher) {
  /* ... */
}
```

This is a perfectly valid and useful `hide` declaration. But if a user who doesn't need the old version of `matcher` gets a new version without a `throwsA` function, they get bogus warnings that they have no way to fix.

**Comment by kevmoo** [comment]
I agree w/ @nex3 – also, we should avoid adding hints to dart2js that are specific to dart2js.

Let's keep this kind of logic centralized in the analyzer

**Comment by johnniwinther** [comment]
@nex3: Your case makes an argument for an optimization of the hint (for instance not giving it an package imports). 

The hint did find noise in the sdk (and compiler): See https://codereview.chromium.org/1346133002/. So the analyzer should probably do something with combinators.

**Comment by johnniwinther** [comment]
@nex3: Your only applies to hide combinators. Maybe that is what we should change wrt. to the hint.

**Comment by bwilkerson** [comment]
As I recall it, the original reason for not specifying a warning for including a name in either a show or hide clause that isn't defined in the imported library was exactly the one the @nex3 gave: we don't want changes in code that is outside a library to be able to create warnings in that library unless it's very clear that there is a real problem (especially, but not exclusively, in cases where the user doesn't own the imported library). And note that if the name is referenced in the importing library then there will be an error or warning at the location of the reference, so a hint at the point of the import would be redundant.

I could imagine adding a hint (to analyzer) that tells the user when a name in a show clause is not referenced anywhere in the library, but I don't think we should have a hint when a name in either a show or hide clause isn't defined in the imported library.

**Comment by johnniwinther** [comment]
The title is wrong; it's a hint, not a warning.

Currently, the analyzer gives a hint when an import is not used. This is noisy in the face of debug helper libraries (we have one such in dart2js). Furthermore, an often occuring problem (in dart2js at least) is that a name is not in scope despite an import explicitly showing it, which after some confused search through our many files is revealed as a case where a hint like this could have helped (even better if the message included which other library (or libraries) declared the name).

**Comment by bwilkerson** [comment]
> Currently, the analyzer gives a hint when an import is not used. This is noisy in the face of debug helper libraries (we have one such in dart2js).

That sounds like an argument in favor of fixing the unused import hint, not an argument in favor of adding more hints with false positives. :-) Let's start an e-mail thread or open an issue to track the problem you're seeing.

> Furthermore, an often occuring problem (in dart2js at least) is that a name is not in scope despite an import explicitly showing it ...

I presume you get a warning at the reference site. Perhaps the error message needs to be adjusted to read something more like this:

The name <name> is not defined. It is explicitly included in a show clause for the library <uri>, but that library does not define that name.

That probably would have made it easier to solve the problem without introducing a hint that has false positives.

**Comment by johnniwinther** [comment]
I acknowledge that we have false positives in face of hide and packages. This can and will be fixed. The hint for show is still valid and indicates a (latent) bug.

**Comment by nex3** [comment]
Marking this as 1.13 since we shouldn't ship a busted warning to stable.

How is the fix for this coming along?

**Comment by johnniwinther** [comment]
https://codereview.chromium.org/1382143005 has put a limit on the hints on hide.

**Comment by nex3** [comment]
@johnniwinther should this issue be closed, then?

**Comment by johnniwinther** [comment]
Yes.

**Comment by kevmoo** [comment]
Reopening per https://github.com/angular/angular/issues/5255

dart2js should not have warnings that don't exist in Analyzer – unless they are specific to dart2js

**Comment by yjbanov** [comment]
I think we do want to warn about missing and unused symbols listed in `show`. It doesn't have the version problem that `hide` has.

**Comment by sigmundch** [comment]
/cc @floitschG 

Note that these are currently presented as "hints" in dart2js, and not warnings.  @kevmoo - are you suggesting that analyzer has to always have a superset of the hints that dart2js will ever show to the user? While I agree we should have warnings in analyzer & dart2js consistent, I don't believe we need to do so for hints. I think hints are a good way to experiment with new messages that we may want to surface and then we can have those experiments graduate if they prove to be useful. In this case, I think they are.

Looking at angular/angular#5255 it appears like pub-build is "raising" the level from hint to a warning though, so I think that should be fixed (just filed https://github.com/dart-lang/pub/issues/1360)

**Comment by floitschG** [comment]
This hint is reasonable and leads to cleaner code. As such, I think we should provide it.
It seems like the real question (raised in angular/angular#5255 and by Kevin earlier in this thread) is, if dart2js should provide hints that the analyzer doesn't.
For the current issue, we could simply wait until the analyzer provides a similar hint, but there are cases where the analyzer doesn't have the same information.
1. the compiler works in a more constrained environment (where environment flags have been finalized, and where the compilation-target is known).
2. the compiler could use the type-inference to give hints.

**Comment by kevmoo** [comment]
@bwilkerson Seems a reasonable hint, at the least

**Comment by jmesserly** [comment]
assuming this is stale with the common front end. If not we can open a new bug for CFE.
