### ISSUE TITLE
exception from analysis server when parsing .analysis_options file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24431]
When I have an empty `.analysis_options` file, the analysis server throws an exception when parsing it:

```
[RequestError code: SERVER_ERROR, message: Exception: Bad options file format (expected map, got Null)
```

An empty yaml file is valid; the analysis server should just treat it as not having any relevant info.

cc @pq @johnmccutchan

**Comment by devoncarew** [comment]
`Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:13:39 2015) on "macos_x64"`

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1369573003
