### ISSUE TITLE
Tear-off syntax and named constructor

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24436]
There is the following text in the specification (16.18.3 General Closurization) :

"Evaluation of a property extraction i of the form e#m proceeds as follows
...
The static type of i is:
...
• The static type of function T.m, if T is Type, e is a constant type literal
and the class corresponding to e declares an accessible static member or
constructor named m."

Why "constructor named m" is mentioned here? Tear-off syntax doesn't support named constructor extraction. The following code fails
```dart
class C {
  C.m() {
  }
}

main() {
  var i = C#m;
}
```

**Comment by iposva-google** [comment]
@sgrekhov : The below version seems to do what you want. It appears that the language specification was not clear?
```
main() {
  var i = new C#m;
  print(i);
  var o = i();
  print(o.runtimeType);
}
```

**Comment by sgrekhov** [comment]
Now its clear, thank you.

**Comment by StokeMasterJack** [comment]
I think this syntax may be deprecated. It doesn't seem to work for me.

**Comment by mraleph** [comment]
@StokeMasterJack yes, the generalized tear off syntax was deprecated and removed from the Dart language.
