### ISSUE TITLE
Future<<bottom>> is not obvious in error messages.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#24445]
PTAL: https://dartpad.dartlang.org/8abfbf860a09aa2bc8d2

```
Map<String, String> demo() async {
  return null;
}
```

gives

```
The return type Future<<bottom>> is not .....
```

I understand why the argument is being made that null has the type '< bottom >' - but I'm not sure that all of our users have read Pierce. How awful would it be to conflate the value and the type of the value in this specific case?

```
The return type Future<<null>> is not .......
```

Further is there a reason why we're overloading the syntax used for type parameterisation < T > to also describe what I presume are 'special' types? If there isn't a strong reason for it, then using another form here would seem advisable.

cc @gbracha in case this is case is too upsetting to even contemplate further.

**Comment by lrhn** [comment]
`Future<<null>>` should probably be `Future<Null>`. The bottom case could be written as `Future<dynamic>`, which captures the fact that we don't actually know a type.

**Comment by gbracha** [comment]
So Future<Bottom> makes perfect sense, but yes, I agree most Dart programmers are not comfortable with TAPL and should not have to be.  Future<dynamic> would do nicely. Future<Null> unfortunately is not useful for anything, since the type of null is Bottom rather than Null.

**Comment by natebosch** [comment]
I think this has gotten much better. Current error is "Functions marked 'async' must have a return type assignable to 'Future'."
