### ISSUE TITLE
Update errors for 'part' file that is not a part any more

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24441]
Create 2 files:

```
library foo;
part 'foo_part.dart';
```

```
part of foo;
Incorrect a;
```

Analysis Server reports a warning ''Undefined class Incorrect". So far so good.

Now comment out `part 'foo_part.dart';`. Since this moment server doesn't know anything about errors/warnings in `foo_part.dart` file.

But server doesn't report an empty errors list for `foo_part.dart` (`com.google.dart.server.AnalysisServerListenerAdapter#computedErrors`) and doesn't notify client that this file is not analyzed any more (`com.google.dart.server.AnalysisServerListenerAdapter#flushedResults`). So client continues to show outdated ''Undefined class Incorrect" warning in its Problems View.
As I understand the docs, `flushedResults` should be invoked.

**Comment by bwilkerson** [comment]
The file `foo_part.dart` is still being analyzed, so a `flushedResults` notification would be wrong, but the errors should definitely be updated.

**Comment by alexander-doroshko** [comment]
Ok, empty list in `com.google.dart.server.AnalysisServerListenerAdapter#computedErrors` is fine.

Related: as you say that the file is still being analyzed, shouldn't client expect the following notifications from server (probably with empty lists):
`com.google.dart.server.AnalysisServerListenerAdapter#computedHighlights`
`com.google.dart.server.AnalysisServerListenerAdapter#computedNavigation`
`com.google.dart.server.AnalysisServerListenerAdapter#computedOverrides`
?
(and I guess the rest of `computedXXX` as well).

The problem is that IDE caches the latest received data and doesn't get a clue that this data became outdated. Solution that works for clients is either to send a single `flushedResults` or updated results for ALL `computedXXX`.

**Comment by srawlins** [comment]
Closing as stale; please re-open if this seems to be an active bug.
