### ISSUE TITLE
Analysis Server doesn't suggest to rename library if invoked from 'part of foo' reference

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24440]
Create 2 files:
```
library foo;
part 'foo_part.dart';
```
```
part of foo;
```
Analysis Server is able to rename library if refactoring is invoked for declaration (`library foo`). I also expect the same result if I invoke rename for reference ```part of foo```.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1364853007

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/6c029f9cb13c221a7ec0617d002e3149db2374df
