### ISSUE TITLE
LayoutTest multi-wrapper-test-actual.txt doesn't see expected exception

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24444]
Most of the failure is just minor format differences, but the names of the element classes are printed as their tags, and most importantly there's an exception expected that isn't being shown, we're just printing a null.

**Comment by whesse** [comment]
There are still differences between the expected and actual - mainly formatting differences.  Diff attached:

[multi-wrapper-test-diff.txt](https://github.com/dart-lang/sdk/files/356895/multi-wrapper-test-diff.txt)
