### ISSUE TITLE
Incorrect rename of 'library foo  .  bar;'

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24442]
Applying refactoring provided by the Analysis Server for library name that has spaces around dot leads to invalid result:
```library foo  .  bar  . baz;```
entering new name  "renamed":
```library renamed  . baz;```

**Comment by zoechi** [comment]
Is this a valid library name?

**Comment by alexander-doroshko** [comment]
Yes, the same as `foo.bar.baz`. Spec allows spaces and comments anywhere between tokens.
Not a standard use case of course, so not a high priority issue.

**Comment by scheglov** [comment]
Preparatory CL: https://codereview.chromium.org/1364583006

**Comment by scheglov** [comment]
Fix for the bug.
https://codereview.chromium.org/1370793003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/4f8649f1b32f8b2f8a60b03f9b5d70cde38c7a3a
