### ISSUE TITLE
refactoring "extract method" creates parameter for named arguments with const values 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24457]
```dart
  _writeFile(io.File elementHtmlFile, bool recursive, String tagName) {
    if (!elementHtmlFile.existsSync()) {
      elementHtmlFile.createSync(recursive: true);
      elementHtmlFile.writeAsStringSync(_elementHtmlContent(tagName, '', ''));
    }
  }
```
`bool recursive` is redundant.

**Comment by scheglov** [comment]
Works for me in Dart Editor.
![image](https://cloud.githubusercontent.com/assets/384794/10137382/0e7ff0c2-65ae-11e5-925d-a4697a6589bb.png)

Are you using IDEA?
IIRC its refactoring implementation has this bug.

**Comment by zoechi** [comment]
Shouldn't WebStorm 11 EAP already use the analyzer for this?

**Comment by alexander-doroshko** [comment]
In current WebStorm 11 EAP server driven 'extract method' is disabled. Will be enabled in the next EAP later this week.
