### ISSUE TITLE
Allow a user to configure which hints are "fatal"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24452]
Some customers treat some hints as fatal. Their build tools and continuous integration systems want to "fail" if certain hints pop up.

This is a request to allow us to use something like the .analysis_options file to declare, for a project, which hints are fatal.

This would be a big productivity win for us, and allow us to not have to force our users to run analyzer through our custom scripts.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew @hixie

**Comment by Hixie** [comment]
Are there warnings that nobody would ever want fatal?

**Comment by sethladd** [comment]
@Hixie definitely. some hints are contextual, and many hints are FYI (like, unused import)... not everyone wants to make that one fatal.

BTW I want to start a band called "Fatal Hints".

**Comment by Hixie** [comment]
You misunderstand my question. My question wasn't "are there hints that somebody doesn't want fatal". My question was "are there hints that nobody would ever want fatal". As in, are there hints like "by the way, nice code"? Or is it all things that are probably issues one way or the other, even if some people for some reason don't care about them?

**Comment by pq** [comment]
Following up on @Hixie's point (if I'm not misinterpreting), I'm curious if something like a single `treatHintsAsErrors` config might not be sufficient.  Are there specific hints that should NOT fail a build?  And more on that note, @sethladd I'm curious if there are still errors or warnings that you also want to special case?  If so, maybe we should consider something like:

  * `treatHintsAsErrors` to escalate hints, with
  * general-purpose mechanism for ignoring/excluding specific errors

It occurs to me that there's at least conceptually some overlap with what the dev compiler does to escalate warnings...  Paging @jmesserly to chime in on that! :)

**Comment by sethladd** [comment]
We need both:

* --fatal-hints (like we have --fatal-warnings)
* mechanism to fatalize specific hints/warnings

**Comment by jmesserly** [comment]
+1 Seth's comment

@Hixie wrote:
> My question was "are there hints that nobody would ever want fatal".

fwiw, here's the hint list: [pkg/analyzer/lib/src/generated/error.dart#L2830](https://github.com/dart-lang/sdk/blob/9ac032d5459203406c0367391b099a9d354c8ffd/pkg/analyzer/lib/src/generated/error.dart#L2830).

I think the answer is no. For each hint, someone would want it to be fatal.

**Comment by pq** [comment]
@sethladd : do you still have errors/warnings you'd want to *de*-escalate?

**Comment by pq** [comment]
@jmesserly does the dev compiler just escalate all warnings to errors?

FWIW my preference would be a means to escalate all to fail a build and then provide a mechanism for specifically calling out warnings to ignore.  I could imagine we'd want to do this potentially at both the project and at the source levels of granularity.

**Comment by jmesserly** [comment]
> does the dev compiler just escalate all warnings to errors?

Currently, yes.

Most warnings are pretty serious, IMO. They usually mean "there's something wrong here, but your code can still compile so you can run other stuff, but if you reach this line it will fail"

**Comment by pq** [comment]
That's my sense too.  The exceptions I expect will be few and far between and possibly worked around with the existing mechanism for excluding files.  (Codegen warnings: I'm looking at you!)

Seth can you provide any more motivation for why you'd want: 

>  * mechanism to fatalize specific hints/warnings

Thanks!

**Comment by jmesserly** [comment]
> Codegen warnings: I'm looking at you!

yeah, definitely some hints that are worth ignoring especially in codegen, e.g. unused imports, maybe unused fields/variables too.

**Comment by alan-knight** [comment]
That seems like it could be a problem in some cases. For example, in the
Intl code for printing numbers there's always a warning about a line that
will produce different results in the VM and when compiled to JS. That code
is there precisely so we can tell if we're in JS or in the VM, because what
you need to do to print large numbers correctly is different between the
two.

I'm not sure if "escalating to errors" means that you would cause the
entire program to fail to compile, or just that running that line would be
an error. But in this case either one would be a problem.

That particular problem could be avoided if we provided a way of checking
that didn't produce a warning, but as far as I know we don't have one now.

**Comment by bwilkerson** [comment]
> My question wasn't "are there hints that somebody doesn't want fatal". My question was "are there hints that nobody would ever want fatal". As in, are there hints like "by the way, nice code"? Or is it all things that are probably issues one way or the other, even if some people for some reason don't care about them?

I hope not. We have a policy that hints should be real problems and should have zero false-positives. (And I personally consider dead code to be a problem.)

I have no problem with a mechanism to cause dartanalyzer to fail when there are hints. I'd rather see a single `--fatal-hints` flag (or corresponding line in the analysis options file) than a mechanism for choosing which hints to fail for.

I do have concerns with a mechanism to ignore some errors, warnings or hints. Obviously, the best answer here is for all of the errors, warnings and hints that we produce to be meaningful. If that's not the case, then we need to first ask why they aren't meaningful and see whether we can make them meaningful for everyone. If there really are exceptions for some people that we cannot adequately capture, then perhaps we do need a general mechanism; but I want proof that it's needed before we create it.

**Comment by zoechi** [comment]
@alan-knight I guess you'll have to wait for configurable imports.

**Comment by sethladd** [comment]
>  I'd rather see a single --fatal-hints flag (or corresponding line in the analysis options file) than a mechanism for choosing which hints to fail for

Why? One person's informative hint (dead code) is another's fatal error. We should allow projects and teams to pick their level of fatality. Dart is a _scalable_ language... fatality levels are relative to project size and life cycle, and can change over time as the project grows.

**Comment by Hixie** [comment]
For the case @alan-knight describes you really need an inline pragma to disable the warning for that block of code. You wouldn't want to disable the warning everywhere. (Unless you didn't care about compiling to JS for whatever reason, e.g. you're targetting some other embedder).

**Comment by sethladd** [comment]
+1 for an `@IgnoreWarnings` or similar. I can think of tests where I purposefully had incorrect code. Unfortunately, that made my project have a big "you have X errors/warnings" sign on it. :(

**Comment by pq** [comment]
> +1 for an `@IgnoreWarnings` or similar. I can think of tests where I purposefully had incorrect code. Unfortunately, that made my project have a big "you have X errors/warnings" sign on it. :(

I tend to use the exclude file hammer for this.
```
analyzer:
  exclude:
    - test/data/no_packages_file/sdk_ext_user.dart
    - test/data/super_mixin_example.dart
```
For test source this seems to work.  Not appropriate though in @alan-knight's use-case.  Note that we have an existing issue for a general `@SuppressWarnings` construct (https://github.com/dart-lang/sdk/issues/12490).  I'd love to see some progress there.

@sethladd : how close to happy would you be with a `--fatal-hints` flag and motion on https://github.com/dart-lang/sdk/issues/12490 to allow you to suppress unwanted feedback?

**Comment by sethladd** [comment]
> how close to happy would you be with a --fatal-hints flag and motion on #12490 to allow you to suppress unwanted feedback?

I do think we should add a --fatal-hints flag.

How do you propose we can suppress unwanted feedback?

(+1 to the general idea, curious what you had in mind)

There are two things we'd like to allow our users to do:

* For a project, disable feedback of a certain class ("hide all warnings") and or a certain type ("hide the hint that I didn't sing the canadian national anthem backwards first" -- a lesser-known hint)

* At the specific location of the feedback, use an annotation to suppress/ignore a certain type of feedback

The "use the exclude hammer for a whole test file" is too big of a hammer most times.

Thanks!

**Comment by pq** [comment]
> How do you propose we can suppress unwanted feedback?

I was thinking something along the lines of an annotation or source-code comment convention.

>  * For a project, disable feedback of a certain class ("hide all warnings") and or a certain type ("hide the hint that I didn't sing the canadian national anthem backwards first" -- a lesser-known hint)

Oh. But I like that one!

But seriously, it sounds like you want something at the project options level.  Something like:

```
analyzer:
  errors:
    exclude:
      - CanadianAnthemFTW
```

Besides settling on syntax we'd also need to get clear on how we're matching errors.  At one end of the spectrum is committing to an immutable numbering or naming scheme (like what microsoft [does](https://msdn.microsoft.com/en-us/library/xb57z28f.aspx)).  At the other is something fuzzier like a regexp on warning text contents.

Maybe we can split this into two issues?  What about taking the general error suppression conversation over to https://github.com/dart-lang/sdk/issues/12490 and leave this to track the `--fatal-hints` ask?  Alternatively, maybe make this a meta topic and break out another for `--fatal-hints`?

**Comment by sethladd** [comment]
>  it sounds like you want something at the project options level

Yup! For an entire project, I'd like to silence specific types of feedback.

**Comment by bwilkerson** [comment]
> I was thinking something along the lines of an annotation or source-code comment convention.

Note that we're *very* limited in terms of where annotations are allowed.

> At the other is something fuzzier like a regexp on warning text contents.

We really don't want to do that! We need well defined constants representing each error, warning and hint.

**Comment by pq** [comment]
> > I was thinking something along the lines of an annotation or source-code comment convention.

>Note that we're very limited in terms of where annotations are allowed.

Agreed.  An advantage of a comment convention is that it gets around this.  It also opens the door to annotating non-source files (e.g., CSS, HTML).  For example, in the style of [pylint](http://docs.pylint.org/faq.html), source might look like this:
```
// analyzer: ignore=unused_local
var foo = 13;
```
(Not that I'm endorsing this format.)  In this case `unused_local` gets elevated to API. Needless to say we'll want to be thoughtful in cooking up a scheme for unique error codes if we go down this road.

**Comment by pq** [comment]
Support for `--fatal-hints` in flight: https://codereview.chromium.org/1382023002/

**Comment by alan-knight** [comment]
Singing the Canadian national anthem *backwards* should always be a fatal error. Thee for guard on stand we. Canada, oh!

**Comment by sethladd** [comment]
:maple_leaf: ftw!

**Comment by pq** [comment]
The `--fatal-hints` flag landed a bit ago (https://github.com/dart-lang/analyzer_cli/commit/d3b33ce85e524868105f55b3a76154cc391e9408).  Curious how far this gets us.  Any feedback?

**Comment by Hixie** [comment]
We hit a minor Android issue when rolling Dart the other day, so I think we haven't yet imported this change. I've turned it on for skyanalyzer with --ignore-unrecognized-flags though, so when we do roll it'll take effect. If I don't comment here again, it's because it's working great. :-)

**Comment by pq** [comment]
> If I don't comment here again, it's because it's working great. :-)

Good deal.  My sense from @sethladd's comments above is that this will only get us part of the way there (without source-level annotations/metadata).  I look forward to seeing just how far!

**Comment by Hixie** [comment]
Well we cheat a little (we wrap the analyzer with https://github.com/flutter/engine/blob/master/sky/tools/skyanalyzer to exclude some messages we, for various reasons, can't fix), but certainly per-line message exclusion would be better.

**Comment by pq** [comment]
Before too long I hope we can get you out of the business of cheating.  :-)

In short order, we should be able to do a little cleaning up.  For example, we're *close* to having the linter reliably configurable via `.analysis_options`.  In the next few weeks you should be able to specify your lints in a file at the top-level of your project like this:

```
linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - library_names
    - super_goes_last
    # ...
```

Then you can get rid of:
```
  # Disable the lint checks that will be caught by code review
  re.compile(r'^\[lint\] Avoid defining a one-member abstract class when a simple function will do'),
  re.compile(r'^\[lint\] Prefer using lowerCamelCase for constant names.'),
  re.compile(r'^\[lint\] Name non-constant identifiers using lowerCamelCase.'),
```
by specifying just the lints that interest you.  A bonus is that the command-line analyzer and server both respect this configuration so you won't have any disconnect between what you see in the output of `skyanalyzer` and in an IDE.  Incidentally, @devoncarew : are you doing any error filtering on the client side?

**Comment by Hixie** [comment]
Not sure if this is the right bug for this, but FWIW:

For the "Prefer using lowerCamelCase for constant names" message, we actually do want the message, we just need to exclude it for a few constants where we've used the underlying platform's names unmodified (in our case, Android constants, but you can imagine this happening with Unix constants like EINVAL or whatever).

For "Name non-constant identifiers using lowerCamelCase", the only reason we have that excluded is that it prevents the name "__" (double underscore). We use "_", "__", "___", etc, to represent arguments that we're intentionally ignoring in callbacks. Those are the only cases where we want to allow the type to be omitted, and are the only cases where we want the identifiers to not be lowerCamelCase.

**Comment by devoncarew** [comment]
We had been filtering in Atom. We removed those when the last round of changes (library names, JS code gen warnings) went stable.

I'd definitely prefer this to be driven by a file that's committed to the repo. It'll make it much more reliable across clients / CLI tools.

**Comment by pq** [comment]
Probably best to file issues over on the [linter](https://github.com/dart-lang/linter) itself.  The first one seems to suggest a configurable lint.  For example:
```
rules:
  - lower_camel_case_constants:
    except: # or something
      - EINVAL
      - MESSAGE_STATE_CHANGE
      # ...
```
The second seems like a bug.  My sense is that your convention is a reasonable one and allowing `_` and `__` vars is a good thing.

**Comment by rakudrama** [comment]
If `_` and `___` are allowed, perhaps so should  `_unused_`_mumbleName_.
Further, for all of the above, check that they are, in fact, unused.

**Comment by skybrian** [comment]
One reason you might want to make only some warnings fatal is that you have a large codebase and can't fix them all at once, so you make them fatal one at a time as they're fixed, for a "ratchet" effect. 
Another strategy is to make the warnings errors in one directory at a time as you clean things up. Both techniques are sometimes useful when maintaining Google's code base.

Another issue I ran into: some generated .dart files have unused imports, and it's difficult for the code generator to figure out which ones are used. On the other hand, it's easy for the code generator to emit some sort of annotation saying to ignore unused imports for this file.

I plan to do this in Google-specific post-processing until some kind of consensus is reached.

**Comment by skybrian** [comment]
One reason you might want to make only some warnings fatal is that you have a large codebase and can't fix them all at once, so you make them fatal one at a time as they're fixed, for a "ratchet" effect. 
Another strategy is to make the warnings errors in one directory at a time as you clean things up.

Another issue I ran into: some generated .dart files have unused imports, and it's difficult for the code generator to figure out which ones are used. On the other hand, it's easy for the code generator to emit some sort of annotation saying to ignore unused imports for this file.

**Comment by pq** [comment]
@sethladd : the current syntax for suppressing warnings was intentionally left open to supporting this.  That is:
```
errors:
  unused_local_variable: ignore
```
could be extended to support an `error` directive to escalate to an error, like so:
```
errors:
  unused_local_variable: error
```
Look reasonable?

**Comment by sethladd** [comment]
If `unused_local_variable` is in the errors section, wouldn't that imply that it's an error? That is, do we need the value of `error` ? Would it be sufficient to simply list a hint's name under errors to make it an "error" ?

**Comment by bwilkerson** [comment]
Isn't terminology wonderful!

The word "error" is used for anything specified by the language spec as being a "compile-time error". But the word "error" is also used for anything that is a compile-time error, static warning, static type warning, hint, lint, etc. In the options file the "errors" section uses the word in the more general sense.

If you have a better suggestion for either term, let me know.

**Comment by skybrian** [comment]
I have been using "problem" for all kinds of analyzer messages, regardless of level. (Borrowed from Eclipse.)

**Comment by pq** [comment]
> If unused_local_variable is in the errors section, wouldn't that imply that it's an error? That is, do we need the value of error ? Would it be sufficient to simply list a hint's name under errors to make it an "error" ?

Good point.  Changing this is not impossible but would invalidate existing options files.  (Alternatively, we could "deprecate" `errors` in favor of a new term (`problem`))?  Let's break this into two issues.

Modulo the name, does the proposal work for you @sethladd ?  In other words,

```
shmerrors:
  unused_local_variable: error
 ```

would escalate `unused_local_variable`s to an error notification.

If you really dislike `errors`, let's open another issue to track renaming.

**Comment by zoechi** [comment]
I'm wondering what `shm` in `shmerrors` could mean ...

**Comment by bwilkerson** [comment]
The word "error" is being used here in the general sense of a problem in user code, not in the more specific sense of a particular severity level. In the absence of a better general term, I think we should leave it as is and not break existing users. Isn't English fun? :-)

> I'm wondering what shm in shmerrors could mean ...

Nothing. It's just a made up replacement for "errors" because there really isn't a better English word for "a problem in user code".

**Comment by pq** [comment]
As of 8887cd69f0f8cb8de36f1ac0986a98c484fdf869, error severities can be configured via `.analysis_options` in the CLI and server.  For example:

```
analyzer:
  errors:
    unused_local_variable: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
```

ignores `unused_local_variable`s, treats `invalid_assignment`s as warnings, `missing_return`s as errors, and `dead_code` as infos.

**Comment by timehdl** [comment]
There's no good solution that I'm using right now：
 // ignore: non_constant_identifier_names

**Comment by bwilkerson** [comment]
@timehdl Sorry, but I didn't understand your comment. Perhaps you could elaborate.
