### ISSUE TITLE
TARGET_OS_IOS macro collides with macro in Xcode 7.0

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#24453]
When building on a Mac with Xcode 7.0, TARGET_OS_IOS is defined by the SDK to be 0.  This definition collides with the use of the symbol in `runtime/platform/globals.h`, which assumes that simply defining this symbol means we're building for iOS.  The end result is that `Platform::Environment` incorrectly returns `nullptr`, breaking the Flutter unit testing harness.

The patch in the gist below fixes the issue, but you'll probably want to fix it a different way, which is why I'm not sending the patch as a pull request:

https://gist.github.com/abarth/8942a1d5b3028003f235

/cc @iposva-google @sethladd

**Comment by whesse** [comment]
Submitted cl https://codereview.chromium.org/1388973002/

**Comment by whesse** [comment]
Fixed.  This will be in the next dev channel release 1.13.0-dev.7.0, and in the stable release of 1.13.
