### ISSUE TITLE
[analyzer] DartTypes not the same for class.typeParameters and method.returnType

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#24454]
With the following code the analyzer (0.26.1+6 and Dart-1.12.0) the `DartType` returned by `classElement.typeParameters[0]` and `m1Method.returnType` are not equals.

```dart
abstract class A<T> {
  T m1();
}
```

Here's the test I made:

```dart
print(templateElement.typeParameters[0]); // returns T
print(templateElement.methods.first.returnType); // returns T
print(templateElement.typeParameters[0] ==
    templateElement.methods.first.returnType); // returns false
```

Shouldn't they be equals ? If this behaviour is as design how can I know that `T` is `T`?

**Comment by bwilkerson** [comment]
The first expression (`templateElement.typeParameters[0]`) returns an instance of TypeParameterElement. The second (`templateElement.methods.first.returnType`) returns an instance of DartType. Those will never be the same.

To get the type that is defined by a type parameter, use the getter `type`. The following should return `true`:

    print(templateElement.typeParameters[0].type ==
        templateElement.methods.first.returnType);

**Comment by a14n** [comment]
Thanks for the explanation. `.type` works.
