### ISSUE TITLE
dart2js: Unsafe propagation across method lookup

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#24458]
In JS the method lookup is evaluated before the arguments to a method call, which can prevent propagation. For example:

``` dart
y = foo();
x.bar(y); // not safe to propagate foo() if x can be null, because 'x.bar' throws
```

In the CPS/Tree backend, this is currently handled by the flag `InvokeMethod.receiverIsNotNull`, which tells assignment propagation if it is safe to propagate non-constant expressions into the arguments.

This broke when type refinement was introduced:

``` dart
y = x.foo(); // x cannot be null after call
x.bar(y); // x is not null. Propagating y seems safe.

=> x.bar(x.foo()); // Oops. Throws for 'x.bar' instead of 'x.foo'
```

Because assignment propagation reorders expressions, the information based on type refinement may become invalid.

The SSA backend seems to fall into the same trap, probably for similar reasons, but I'm not sure.

A potential solution in the CPS backend is to explicitly check for this in assignment propagation, but that pass is already too complicated, and it's sort of hack to check for "something that may have promoted the type of x".

A alternative is to initially use Dart-style method lookup, i.e. where the method lookup evaluates after the arguments. That means propagation is always safe. Then there is a pass after assignment propagation that switches to JS-style method lookup, and the pass has to "unpropagate" arguments to preserve evaluation order. The semantics of the tree IR thus depends on where in the pipeline we are, like with the unsugaring pass in CPS.

@kmillikin @rakudrama

**Comment by rakudrama** [comment]
Obsolete
