### ISSUE TITLE
Quick fix "create method" incorrectly copies type prefixes

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24459]
With the following initial state:

test1.dart:

    import 'test2.dart' as test2;
    class C {
      test2.D d;
      f(test2.E e) {
        d.g(e); // Warning: method "g" not defined
      }
    }

test2.dart:

    class D {}
    class E {}

Attempting to use the quick fix "create method 'g'" causes the following code to be inserted into the declaration of class D:

    void g(test2.E e) {
    }

This is incorrect, since test2.dart has no prefix called `test2`.  The correct code to insert would be:

    void g(E e) {
    }

**Comment by scheglov** [comment]
https://codereview.chromium.org/1375043004
