### ISSUE TITLE
.packages: Move resource lookup & loading to a package and deprecate Resource class

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24463]
#19430 will introduce support for getting the package root. Based on that we should move the implementation of what is in the Resource class into a package, and discontinue the Resource class.

**Comment by sethladd** [comment]
Related: https://github.com/dart-lang/sdk/issues/24499

**Comment by sethladd** [comment]
resource package placeholder created, @lrhn is an uploader: https://pub.dartlang.org/packages/resource

**Comment by mit-mit** [comment]
CR: https://codereview.chromium.org/1374953002/

**Comment by mit-mit** [comment]
And the CR for the package: https://codereview.chromium.org/1387163002/

**Comment by kevmoo** [comment]
Resource class is deprecated in 1.13 – keeping this open for 1.14 to track work on the package

**Comment by mit-mit** [comment]
@kevmoo, we should land this now, right?

**Comment by lrhn** [comment]
As soon as the necessary functionality is landed in the VM, yes.

**Comment by mit-mit** [comment]
This was landed in https://github.com/dart-lang/resource/commit/527b11d472abbdc4ee3d08749f5685e2265f3465; closing.
