### ISSUE TITLE
Dart libraries are initialized before the first dart <script> tag is encountered in an entrypoint

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/sdk#24462]
On Dartium, the Dart libraries appear to be initialized before the first dart script tag is processed in the html entrypoint. For example, if the first script tag in my html entrypoint replaces XMLHttpRequest, this is not reflected by HttpRequest in the Dart runtime. This is different than how browsers appear to normally work with scripts in html, where they are processed in the order they are encountered. This causes problems using JavaScript libraries that rely on being able to replace objects in the browser (e.g. sinonjs, pretenderjs).

**Comment by sigmundch** [comment]
Dartium's definition of the DOM APIs is separate from the JS definitions today (they go directly to the native APIs within chrome). I understand that @terrylucas and @alan-knight are changing this to start using js-interop instead. I'm not sure though if your use case would be addressed at that point.

**Comment by alan-knight** [comment]
That change is live on bleeding-edge right now, so you can see if it works or not.

**Comment by jacob314** [comment]
Version of Dartium on bleeding-edge should work for your use case if Dart2Js works for your use case.

**Comment by ErikGrimes** [comment]
I created tests for BrowserClient and HttpRequest and ran them in Chrome. Both failed. 

```
00:15 +5 -1: basic tests should work with BrowserClient                                            
  type 'UnknownJavaScriptObject' is not a subtype of type 'HttpRequest'
  dart:_internal                            _LinkedHashSet.add
  package:http/browser_client.dart 50:7     BrowserClient.send.<fn>
  ===== asynchronous gap ===========================
  dart:async                                _Future.then
  package:http/browser_client.dart 48:12    BrowserClient.send
  ===== asynchronous gap ===========================
  dart:_internal                            asyncHelper
  package:http/src/base_client.dart 158:18  BaseClient._sendUnstreamed
  package:http/src/base_client.dart 158:18  BaseClient._sendUnstreamed
  ===== asynchronous gap ===========================
  dart:_internal                            asyncHelper
  package:http/src/base_client.dart 34:33   main.<fn>.<fn>
  package:stack_trace                       StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  
00:15 +5 -2: basic tests should work with HttpRequest                                              
  NoSuchMethodError: method not found: 'addEventListener$3' (J.getInterceptor$x(...).addEventListener$3 is not a function)
  package:http_parser/src/utils.dart 23:1        J.x
  dart:html                                      HttpRequest.getString
  package:brproxy/brproxy.dart 11:34             $call
  package:stack_trace                            StackZoneSpecification.registerUnaryCallback.<fn>
  ===== asynchronous gap ===========================
  dart:_internal                                 asyncHelper
  package:matcher/src/core_matchers.dart 109:48  $call
  ===== asynchronous gap ===========================
  dart:_internal                                 asyncHelper
  package:matcher/src/core_matchers.dart 109:48  main.<fn>.<fn>
  package:stack_trace                            StackZoneSpecification.registerUnaryCallback.<fn>.<fn>

```

It looks like dart2js is picking up my version of XMLHttpRequest, but failing for different reasons in each case?
