### ISSUE TITLE
dart2js: package_resource_test hits assertion

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24461]
@hterkelsen can you take a look?

```
Internal Error: makeConstructedConstant can only be called with the effective target: origin function(Resource#)
  const resource = const Resource(uriText);
                   ^^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.
...
The compiler crashed: Assertion failure: makeConstructedConstant can only be called with the effective target: origin function(Resource#)
```

Repro:
tools/test.py -mrelease -cdart2js -rd8 --host-checked corelib/package_resource_test

**Comment by hterkelsen** [comment]
The issue seems to be that the origin constructor for Resource is not seen as a redirecting factory constructor, even though it has a patch implementation. I think this can be fixed by adding support for origin constructors when we resolve forwarding constructors.

**Comment by sigmundch** [comment]
I'd hold off on fixing this though, since I assume this is likely going to change when this CL lands: https://codereview.chromium.org/1374953002/

**Comment by hterkelsen** [comment]
The failing test will go away, but the bug will occur again with any patch class with a forwarding patch constructor implementation.

**Comment by sigmundch** [comment]
ah, I see, then yes, we probably want to fix that :)
