### ISSUE TITLE
arm image doesn't work on quad core armv7 system

### ISSUE THREAD

**Issue by kgersen** [dart-lang/sdk#24466]
when trying to run the arm image available at: http://gsdview.appspot.com/dart-archive/channels/stable/release/1.12.1/sdk/
I get a:
"Illegal instruction"
error

The relevant gdb output:
```
Reading symbols from dart-sdk/bin/dart...(no debugging symbols found)...done.
[New LWP 15797]
[New LWP 15794]
[New LWP 15795]
[New LWP 15796]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `dart-sdk/bin/dart testdart.dart'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0xb5d87644 in ?? ()
```
the 'testdart.dart' program is a simple hello word:
```
void main() {
  print("Hello, World!");
}
```
The machine is a quadcore armv7 running Debian (jessi)
uname -a:
```Linux <hostname> 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l GNU/Linux```

/proc/cpuinfo:
```
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1332.01
Features        : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

processor       : 1
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1332.01
Features        : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

processor       : 2
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1332.01
Features        : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

processor       : 3
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1332.01
Features        : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

Hardware        : Marvell Armada 370/XP (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by zanderso** [comment]
The disassemble command: http://visualgdb.com/gdbreference/commands/disassemble

So the address you have above was 0xb5d87644, so you'd do:
$ disassemble 0xb5d87604,+128

And gdb will spit out the 16 instructions on either side of the illegal instruction.

A stack trace at the faulting instruction could be useful as well, you can get that with:
$ bt

A bit surprised we're hitting an illegal instruction, this looks like a pretty standard ARMv7-A chip:

http://www.marvell.com/embedded-processors/armada-xp/assets/ARMADA-XP-Functional-SpecDatasheet.pdf

**Comment by kgersen** [comment]
here the dis:
```
Dump of assembler code from 0xb5d87604 to 0xb5d87684:
   0xb5d87604:  strtlt  r8, [r10], -r1, lsr #32
   0xb5d87608:  strtlt  r8, [r10], -r1, lsr #32
   0xb5d8760c:  strtlt  r8, [r10], -r1, lsr #32
   0xb5d87610:  andseq  r5, r0, r0, lsl #20
   0xb5d87614:  ldrblt  r0, [pc, #3097] ; 0xb5d88235
   0xb5d87618:  ldrblt  r0, [pc, #2929] ; 0xb5d88191
   0xb5d8761c:                  ; <UNDEFINED> instruction: 0x000002bc
   0xb5d87620:  ldr     r0, [sp]
   0xb5d87624:  ldr     r1, [sp, #4]
   0xb5d87628:  orr     r12, r0, r1
   0xb5d8762c:  tst     r12, #1
   0xb5d87630:  bne     0xb5d87654
   0xb5d87634:  cmp     r0, #0
   0xb5d87638:  beq     0xb5d87654
   0xb5d8763c:  asr     r0, r0, #1
   0xb5d87640:  asr     r1, r1, #1
=> 0xb5d87644:                  ; <UNDEFINED> instruction: 0xe7100011
   0xb5d87648:  cmp     r0, #1073741824 ; 0x40000000
   0xb5d8764c:  lslne   r0, r0, #1
   0xb5d87650:  bxne    lr
   0xb5d87654:  mov     r7, r10
   0xb5d87658:  ldr     r10, [pc, #-72] ; 0xb5d87618
   0xb5d8765c:  ldr     r6, [r10, #11]
   0xb5d87660:  mov     r10, r7
   0xb5d87664:  ldr     r7, [r6, #47]   ; 0x2f
   0xb5d87668:  add     r7, r7, #1
   0xb5d8766c:  str     r7, [r6, #47]   ; 0x2f
   0xb5d87670:  movw    r12, #23000     ; 0x59d8
   0xb5d87674:  cmp     r7, r12
   0xb5d87678:  movwge  r12, #33792     ; 0x8400
   0xb5d8767c:  movtge  r12, #46630     ; 0xb626
   0xb5d87680:  bxge    r12
```

**Comment by kgersen** [comment]
and the bt:
```
(gdb) bt
#0  0xb5d87644 in ?? ()
#1  0xb6269ba8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by rmacnak-google** [comment]
Works on Raspberry Pi 2, which lists

Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 

I wonder if we use something from vfpv4.

Can you try running with --use-vfp=false?

**Comment by zanderso** [comment]
Thanks for posting the disassembly. It's the sdiv instruction, which is weird because /proc/cpuinfo is showing integer division support. Might need to add a special case to feature detection. I'll investigate further tomorrow.

**Comment by kgersen** [comment]
I can arrange an access for you to the server if you want. it's empty and unused atm so there is no privacy/security concerns. I can pm you the ip & ssh priv key if you want. just tell me.

**Comment by zanderso** [comment]
Sounds good. In the meantime, to make sure we've really found the problem, could you try passing --no-use-integer-division on the dart command line?

**Comment by zanderso** [comment]
Doing a bit of Googling about this chip, I haven't been able to find any evidence that it misreports the presence of integer division, but Linux does occasionally twiddle these bits before reporting them, so it could be something that is kernel version dependent. The docs say this chip is ARMv7A compliant, and integer division is optional there. If --no-use-integer-division fixes the issue, I'll add a special case for this chip so that the flag isn't needed.

**Comment by kgersen** [comment]
It works with "--no-use-integer-division"! good find!

do you still need access to the server or is this case closed ?

**Comment by zanderso** [comment]
Just landed a special case for this chip in our feature detection at top-of-tree. Closing this issue, but please feel free to re-open if you're unable to verify the fix. Thanks for the bug report!
