### ISSUE TITLE
Missing compile-time errors for closure ripoff operator #

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24472]
New co19 tests for the property extraction and closurization operator # reveal some missing errors:

Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t01: MissingCompileTimeError
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t02: MissingCompileTimeError
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t03: MissingCompileTimeError
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t04: MissingCompileTimeError
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t05: MissingCompileTimeError
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t06: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t01: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t02: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t03: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t04: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t05: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t06: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t07: MissingCompileTimeError
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/class_object_member_t08: MissingCompileTimeError
Language/Expressions/Property_Extraction/Named_Constructor_Extraction/not_class_t01: CompileTimeError

**Comment by iposva-google** [comment]
These tests are also not found in the current repo?

**Comment by whesse** [comment]
Should I just note in the issues I file that the tests are in tip-of-tree
co19, or should I not make issues for them until we roll?  The problem is
then that the status files will not have issue numbers for the tests they
mark as failing.

On Mon, Oct 5, 2015 at 3:02 PM, Ivan Posva <notifications@github.com> wrote:

> These tests are also not found in the current repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24472#issuecomment-145520914>.
>



-- 
William Hesse

**Comment by iposva-google** [comment]
Cc'ing @gbracha to ensure tests are correct.

**Comment by mhausner** [comment]
I'm fine with filing now. I'll wait for your check-in and then take a look at the bugs. You can assign all language-related bugs directly to me.

**Comment by mhausner** [comment]
These tests fail because the VM does not implement the numerous special cases that the Spec lists. For example, the Spec makes it a compile-time error if the extracted name is also a member of type Object, or if the extracted name is a type.

Some of the restrictions are a bit iffy the way they are formulated at present. For example, the expression L.hashCode would have to be a compile-time error even if a library exports a top-level field hashCode and is imported via prefix L.

**Comment by a-siva** [comment]
The following tests now work correctly on the VM as general closurization of the form x#y is a compile error now.

Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t01
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t02
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t03
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t04
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t05
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t06

**Comment by mhausner** [comment]
The # operator has been removed from the language, so this is obsolete.
