### ISSUE TITLE
Request for analysis server to return/send the PID of its process

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24477]
In order to help display resource consumption information to the user, and in order for clients to make informed decisions around the health of the AS, we would like to request a new API (or augmentation of existing API) to return the PID from the analysis server's process.

See also https://github.com/dart-lang/sdk/issues/24020

Thanks for the review!

**Comment by bwilkerson** [comment]
We can easily extend the server.connected notification to include the process id.

**Comment by pq** [comment]
@devoncarew : do we still need this?

**Comment by devoncarew** [comment]
If we get https://github.com/dart-lang/sdk/issues/24480, then this one isn't needed :)

**Comment by pq** [comment]
Closing this in favor of pushing on https://github.com/dart-lang/sdk/issues/24480.
