### ISSUE TITLE
Hints emitted in Dart build phase from dart2js_incremental

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24470]
It looks like there are some warning/hints in this file that should be fixed:

../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:77:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ClassBuilder' declaration.
Try removing 'ClassBuilder' from the 'show' clause.
    ClassBuilder,
    ^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:78:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ClassEmitter' declaration.
Try removing 'ClassEmitter' from the 'show' clause.
    ClassEmitter,
    ^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:80:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'ContainerBuilder' declaration.
Try removing 'ContainerBuilder' from the 'show' clause.
    ContainerBuilder,
    ^^^^^^^^^^^^^^^^
../../out/ReleaseIA32/packages/dart2js_incremental/library_updater.dart:81:5:
Hint: Library 'package:compiler/src/js_emitter/js_emitter.dart' doesn't export a 'MemberInfo' declaration.
Try removing 'MemberInfo' from the 'show' clause.
    MemberInfo,
    ^^^^^^^^^^

**Comment by kevmoo** [comment]
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/24435
