### ISSUE TITLE
VM is missing compile-time errors for const constructors with various non-const elements

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24471]
There are new co19 tests for the updated language spec, testing that various malformed constant constructors throw compile-time errors.  The VM fails these.
The tests are introduced in https://github.com/dart-lang/co19/commit/9ccc64ef50e8d721e802924998fd1402d1c6793f
but they are renamed later to:

Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t01: MissingCompileTimeError
Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t02: MissingCompileTimeError
Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t03: MissingCompileTimeError
Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_superclass_t01: MissingCompileTimeError
Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_superclass_t02: MissingCompileTimeError

**Comment by iposva-google** [comment]
I cannot find the tests you are mentioning in the current repo, nor are there failure lines associated with this bug number.

**Comment by whesse** [comment]
Oh, sorry.  They are in the TOT co19 repo, and I am working on a CL to roll
co19 and update the status files.
It is a large CL, and cannot be committed in parts, so I am making the
issues as I add them to the status files in the CL.
You can see the tests in github dart-lang/co19, and I will upload the
(incomplete) CL rolling co19 as

https://codereview.chromium.org/1390533003/


Part of this CL is a renaming of many of the co19 tests, with renaming of
tests in the status files performed by Unipro.



On Mon, Oct 5, 2015 at 2:59 PM, Ivan Posva <notifications@github.com> wrote:

> I cannot find the tests you are mentioning in the current repo, nor are
> there failure lines associated with this bug number.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24471#issuecomment-145519958>.
>



-- 
William Hesse

**Comment by iposva-google** [comment]
Looks like a lot of renaming work needed. Sorry to see that happening while at the same time it is nice to drop the arbitrary numbers.

CC'ing @gbracha to make sure the tests are correct.

**Comment by mhausner** [comment]
All the tests listed above are buggy. They do not actually reference the class that contains the compile-time error.

E.g:

```
class A {
}

class C {
  final x = new A();
  const C();
}

main() {
}
```

If I add a ```const C();``` in main, the expected compile-time error is generated.

I will file the co19 bugs.

**Comment by mhausner** [comment]
Filed https://github.com/dart-lang/co19/issues/18
