### ISSUE TITLE
Request to remove flag for mixin+super in analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24478]
Given an update to our flag policy, we can remove the flag for mixin+super.

Thank you for taking a look!

**Comment by sethladd** [comment]
There are concerns this will confuse users who are building web apps. Thus, we will keep the flag in analyzer in 1.13. Meanwhile, we have an idea for what to do for 1.14. Stay tuned.

**Comment by sethladd** [comment]
We agreed to remove this flag for 1.14.

**Comment by bwilkerson** [comment]
So, to be clear, all of our targets (Web, Flutter, etc.) will support this flag?

**Comment by sethladd** [comment]
Not in the 1.14 timeframe, but the leads just decided it's OK to remove this flag for 1.14 and not wait for every implementation.

(sorry, the use of 'we' was pretty vague)

**Comment by zoechi** [comment]
Does this mean this is not yet implemented in dart2js?

**Comment by sethladd** [comment]
> Does this mean this is not yet implemented in dart2js?

Correct. It's not implemented in dart2js. It's turned on by default in the VM.

**Comment by mit-mit** [comment]
@bwilkerson what is the status of this?

**Comment by bwilkerson** [comment]
No work has been scheduled for it. I assumed that if there's no push to get it into all platforms that there isn't a great demand for it. I'm guessing, from your query, that I might have been wrong. Is there a great desire to enable it by default in the analyzer? If so, do we need a flag to disable it for users using dart2js?

**Comment by bwilkerson** [comment]
According to an e-mail conversation with Dan and Kasper, the flag should not be removed until it can be implemented everywhere.

**Comment by zoechi** [comment]
I got the impression this is important for Polymer @jakemac53

**Comment by jakemac53** [comment]
@zoechi Polymer does not directly use this feature currently. We implemented the behaviors using static methods which the framework would invoke instead in order to get unblocked.

**Comment by stereotype441** [comment]
Reopening the issue since we haven't yet removed the flag, and we do plan to do so.  Just not until it is implemented in dart2js (#23773).

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bwilkerson** [comment]
I'm closing this. The flag is still there and I expect it will remain until the new mixin support is available, by which time analyzer will be on the new front end.
