### ISSUE TITLE
Function parameters are treated differently when using await

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#24488]
Function parameters are treated differently when function was called with `await` instead of using `.then`.
For example, this code
```dart
import 'dart:async';
main() async {
  Future foo(int a1, int a2) {
    print("from foo: $a1 $a2");
    return new Future.value();
  }

  int a = 0;
  await foo(a++, a++);
  print("after await foo: $a");

  a = 0;
  foo(a++, a++).then((_) {
    print("after foo.then: $a");
  });
}
```
outputs
```
from foo: 0 0
after await foo: 1
from foo: 0 1
after foo.then: 2
```
This behavior appears only when running on DartVM (tested 1.12.1 and 1.13.0-dev.5.0). Dart2JS works fine.

**Comment by iposva-google** [comment]
CC @crelier

**Comment by mhausner** [comment]
Committed patchset #1 (id:1) manually as
c5ed2f55b7f1c8450ec9ca52dbd53f35d2f11ce2 (presubmit successful).
