### ISSUE TITLE
Annotation and const constructor

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24487]
```
class ExampleAnnotation extends Object { // class declaration
  final String itemA;
  final String itemB;
  final String itemC;
  const ExampleAnnotation(this.itemA, this.itemB, this.itemC); // constructor declaration
}

@ExampleAnnotation()   // (1)
class TargetClass {
  TargetClass(){
    new ExampleAnnotation(); // (2)
  }
}
```

Both (1) and (2) should be resolved to constructor declaration, but currently (1) is resolved to class declaration.

(Originally reported as https://youtrack.jetbrains.com/issue/WEB-16737)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1378713004

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/62fd9ac7878c9f48d0aefdfed8ed7b850375672c
