### ISSUE TITLE
need a way to have visibility into the amount of resources that the AS is consuming

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24480]
This is re-filed version of #24020 - some comments from that in-line:

Related to dart-atom/dartlang#189. We have situations where the AS process consumes large amounts of RAM, and/or persistent high CPU usage. We'd like a way to be aware of this on the client end. It may be difficult to get precise resource usage (RAM / CPU), but hopefully there are some suitable proxies. Number of contexts, size of each context, ... This could be exposed as a specific API that clients call, or perhaps as a periodic notification.

--

It would still be nice for clients to be able to opt in to a periodic heartbeat from the analysis server. The payload could be metrics that are easy for the AS to calculate and that would act as good proxies for the resource consumption of the AS. I would see this API as generally useful to clients. It would mean that the monitoring code could be written in one place instead of each client writing its own monitoring code.

--

From @lukechurch:

Let me try and help out here.

People develop a 'spider sense' for 'this is a well behaving tool', 'this isn't'. In the physical world we use all sorts of signals to build this 'feeling'. E.g. the vibration in a car steering wheel as you're driving it. 

Digital things are on a whole polished glass boxes, which lack a lot of these signals. So people need other ones. When the system gets __really__ reliable people can start to use its behaviour as a signal. E.g. we saw people using code completion stopping working as a signal that they'd got something wrong with their code.

On the whole our tooling isn't there yet. So when people get strange behaviour they don't know whether it's their code being broken or the system misbehaving. They will often assume the former and waste a lot of time. Anything we can do to add signals that people can start using to build a 'this is normal, this isn't' feeling will help a lot in the user knowing when to keep pushing on or when to repair.

So e.g. RAM usage. If the user builds an instinct that 'my project usually takes AS about 1Gb to run', the system starts behaving funny and they notice it's using 4Gb - then they might correctly short cut to the realisation that it was AS. And click the ''Something is dodgy, send a perf report and restart' button.

My instinct for what 3 useful metrics would be are:

- RAM usage of AS
- Average + Variance of latency Request/Response from Server over the past 30s
- CPU load fraction in AS process

I think putting these three numbers somewhere continuously on the UI at low intensity might well help build the 'spider sense'.

**Comment by pq** [comment]
@devoncarew how close would we get if we added a `Status` request that supplied the kinds of stats that we render on the HTML status page?  Given that you could tease out some proxies to surface.

**Comment by pq** [comment]
First cut plumbed through as of https://github.com/dart-lang/sdk/commit/82e83bb34d913c1ba171d174e66e60b95bea492a.

Preliminary diagnostics payload looks like:
```
{
  contexts:  [
    {
      name: /project, 
      explicitFileCount: 8,
      implicitFileCount: 0,
      workItemQueueLength: 0, 
      cacheEntryExceptions: []
    }
  ]
}
```
More details in the [review](https://codereview.chromium.org/1416093007/diff/40001/pkg/analysis_server/tool/spec/spec_input.html).

Note that this experimental API is in `spec_input.html` but anything flagged `experimental` will not have docs generated. :+1:

**Comment by devoncarew** [comment]
Closing this as much of the work has landed, and we have two open, more specific, issues for the remaining work.

**Comment by devoncarew** [comment]
Thanks!
