### ISSUE TITLE
Dartium bleeding edge exception

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24494]
>Observatory listening at http://127.0.0.1:60914/
constructor != null && jsTypeName.length > 0
 #0      debug_or_assert (dart:html:1256)
#1      wrap_jso (dart:html:1182)
#2      MutationObserver._create (dart:html:27264)
#3      MutationObserver.MutationObserver._ (dart:html:27227)
#4      MutationObserver.MutationObserver (dart:html:27326)
#5      _ScheduleImmediateHelper._ScheduleImmediateHelper.<anonymous closure> (dart:html:48747)
#6      _RootZone.run (dart:async/zone.dart:1160)
#7      _ScheduleImmediateHelper._ScheduleImmediateHelper (dart:html:48744)
#8      _scheduleImmediateHelper (dart:html:48770)
#9      _scheduleImmediateHelper (dart:html:48769)
#10     _scheduleImmediateClosure.<anonymous closure> (dart:html:48773)
#11     _AsyncRun._scheduleImmediate (dart:async-patch/schedule_microtask_patch.dart:10)
#12     _scheduleAsyncCallback (dart:async/schedule_microtask.dart:73)
#13     _rootScheduleMicrotask (dart:async/zone.dart:957)
#14     scheduleMicrotask (dart:async/schedule_microtask.dart:138)
#15     Future.Future.microtask (dart:async/future.dart:142)
#16     main (http://localhost:63342/polymer1/auto_binding_element/web/index_reflectable_original_main.dart)
#17     main (http://localhost:63342/polymer1/auto_binding_element/web/index.dart:26:10)
#18     main (http://localhost:63342/polymer1/auto_binding_element/web/index.bootstrap.dart:5:11)
#19     main (http://localhost:63342/polymer1/auto_binding_element/web/index.bootstrap.initialize.dart:30:10)

> index_reflectable_original_main.dart:1 Exception: The null object does not have a method 'observe'.
>
NoSuchMethodError: method not found: 'observe'
Receiver: null
Arguments: [Instance of 'DivElement', attributes: true]
main index_reflectable_original_main.dart:1 
main index.dart:29 
main index.bootstrap.dart:5 
main index.bootstrap.initialize.dart:36 main

I had this issue with this Polymer 1.0.0-rc.2 example https://github.com/bwu-dart-playground/polymer1/tree/master/auto_binding_element
When I switched back to `Dart VM version: 1.13.0-edge.33b037125fbf5e8319a99fd5e5700441c921efde (Mon Sep 14 18:13:24 2015) on "linux_x64"` the example was working fine.

Are interested in such bug reports at this time?

**Comment by alan-knight** [comment]
We are interested, but can you try it again. There was a check-in this morning that fixes a number of polymer issues.

**Comment by alan-knight** [comment]
Although maybe not right away, unless you're compiling it yourself. I don't think the bleeding edge version has even built yet for all platforms.

**Comment by zoechi** [comment]
Grat, I'll try it again,  but I don't know yet when I'll have time, could be that's not before friday.

**Comment by zoechi** [comment]
I still get the same exception with Dartium from 
http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/dartium/
1.13.0-edge.8e523195e66f97727bd299ff2477c61f337f3184
Linux x64

**Comment by zoechi** [comment]
Update - my current exception looks a bit different:

> chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
2015-10-14 10:41:01.928chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
2015-10-14 10:41:05.680index.html:1 Observatory listening at http://127.0.0.1:38508/
2015-10-14 10:41:07.210index_reflectable_original_main.dart:1 Exception: type 'JsObjectImpl' is not a subtype of type 'MutationObserver' of 'function result'.index_reflectable_original_main.dart:1 mainindex.dart:172 mainindex.bootstrap.dart:5 mainindex.bootstrap.initialize.dart:782 main

Dart VM version: 
Dartium: 1.13.0-edge.bb3060aa5940dbdaf4c21da63a7f66b65f7f5b2f
Dart: 1.13.0-edge.06c3e1ae72d8ef35b150291dfbada839a4247111 (Tue Oct 13 16:09:38 2015) on "linux_x64" 
(from the `latest` folder)

**Comment by mit-mit** [comment]
Current thinking is that we need a new Chrome roll of Dartium to resolve this. That roll is scheduled for 1.14 -- see https://github.com/dart-lang/sdk/issues/24218 -- so moving this to 1.14 also.

**Comment by zoechi** [comment]
This seems fixed after the last update (Dartium 1.13.0-edge.f3f358e5f38829f3284d7f922f2393d0803115dd)

**Comment by dgrove** [comment]
great!

**Comment by zoechi** [comment]
Since the bleeding edge update id did yesterday, it got it back:

 >Observatory listening at http://127.0.0.1:45021/
Exception: type 'JsObjectImpl' is not a subtype of type 'MutationObserver' of 'function result'.
  main	

Dartium:

> 1.13.0-edge.0a341e97905086356163314798ebf5874673b519

**Comment by alan-knight** [comment]
I don't think that's the same as your original symptom. Do you have any more details about the circumstances?

**Comment by zoechi** [comment]
Right, it's not like the original, but the same or similar to the one mentioned in the comment https://github.com/dart-lang/sdk/issues/24494#issuecomment-147977358

The circumstances when I get the exception are the same though.

I get this exception in every Polymer 1.0.0-rc application.
Here is a very simple example https://github.com/bwu-dart-playground/polymer1/tree/master/click_this

**Comment by zoechi** [comment]
I get the exception while the entry page (index.html) is loaded, after some delay, but before I do any user action. It looks like Polymer initialization is failing.

**Comment by zoechi** [comment]
If I revert to an older Dartium version 
> 1.13.0-edge.f3f358e5f38829f3284d7f922f2393d0803115dd  

it works fine.

**Comment by alan-knight** [comment]
The click_this example is working for me in that exact version, as well as in the tip of bleeding edge. I tried both building it myself on Linux and downloading the Mac version, and both were fine.

**Comment by zoechi** [comment]
I updated again to bleeding edge latest

Dartium 

> 1.13.0-edge.2529e684f0f5080958941a3baf6414a27a7869a7

VM:

> Dart VM version: 1.13.0-edge.0172094a500e0043fadc50df3042ad345f4ec904 (Thu Oct 29 02:00:29 2015) on "linux_x64"  

The click_this example fails

> Exception: type 'JsObjectImpl' is not a subtype of type 'MutationObserver' of 'function result'.
index_reflectable_original_main.dart:1 
mainindex.dart:28 
mainindex.bootstrap.dart:5 
mainindex.bootstrap.initialize.dart:33 
main

After reverting Dartium to 

> Dart	1.13.0-edge.f3f358e5f38829f3284d7f922f2393d0803115dd

the example works again.

I have no idea what additional information I could provide to make this reproducible.

**Comment by alan-knight** [comment]
Can you try putting a breakpoint on MutationObserver._create  (line 27341 in html_dartium.dart in the current BE) and see what's happening in the wrap_jso call at the end. Presumably that's where you're getting a JsObjectImpl and not the corresponding Dart object.

I'm suspicious there's something strange in your setup, because having all polymer initializations fail is something that we'd probably hear about pretty quickly.

**Comment by zoechi** [comment]
Dartium 

> 1.13.0-edge.d1e01e205a615257ba9391cb531ad8b053af1fed

without `wrap_jso(...)`
![image](https://cloud.githubusercontent.com/assets/405837/10841256/fd0f604a-7ee7-11e5-9b7e-2173099d10d6.png)
with `wrap_jso(...)`
![image](https://cloud.githubusercontent.com/assets/405837/10841267/229de354-7ee8-11e5-9f2d-0190fa2135b2.png)

Dartium

> 1.13.0-edge.f3f358e5f38829f3284d7f922f2393d0803115dd

Shows different code and this one works 

![image](https://cloud.githubusercontent.com/assets/405837/10841363/ee27f582-7ee8-11e5-8714-55d278ba6f59.png)

**Comment by alan-knight** [comment]
OK, so the reason it's not getting wrapped is that the thing you're getting back is not [object MutationObserver], but looks like something wrapping a MutationObserver. The field _creationZone does not, as far as I can tell, exist anywhere in the Dart SDK or in Dartium. A quick google search shows something like that in Angular2. Is it possible you've got something from 
Angular2 or elsewhere that's monkey-patching MutationObserver?

**Comment by zoechi** [comment]
Nothing from Angular, just Polymer. Maybe @jakemac53 has any idea?

**Comment by alan-knight** [comment]
I'm pretty sure it's the Polymer DevTools extension. That explicitly has code that monkey-patches system constructors to add that _creationZone field and replaces them with an unnamed function. Dartium relies on the constructor name when wrapping.

**Comment by zoechi** [comment]
You are right. 
I wasn't aware I had an extension installed, I forgot they are kept, even when Dartium is re-installed and never used it.
Anything that should be done about it? Create a bug report for the Polymer DevTools extension?
Otherwise you can close the issue.
Thanks a lot for figuring that out.

**Comment by alan-knight** [comment]
Great. Filed https://github.com/dart-lang/sdk/issues/24776 and https://github.com/angular/zone.js/issues/197
