### ISSUE TITLE
Many of Analyzer's ast docs are not formatted.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#24498]
In general, according to the [Guidelines for Doc Comments](https://www.dartlang.org/articles/doc-comment-guidelines/):

* The first paragraph should be a "one-sentence" description.
* Method descriptions should begin with a "third-person verb," such as "Returns true for..."

**Comment by srawlins** [comment]
First CL to fix this (through lines 620) here: https://codereview.chromium.org/1388793002

**Comment by srawlins** [comment]
Second CL to fix this (lines 660 to 3000) here: https://codereview.chromium.org/1377613003

**Comment by bwilkerson** [comment]
While I appreciate all the work you did, I would prefer to leave the comments the way they are. I know that they don't strictly conform to the published style guide, but conformance is a non-goal for us. In some cases it is explicitly an anti-goal. For example, our team explicitly decided to use block-style documentation comments. As for the wording, the comments throughout the package are (mostly) internally consistent and I think they are reasonably readable as they are.
