### ISSUE TITLE
Deprecate the Resource class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24499]
We believe that a package will be published that can contain the Resource class. Therefore, we can deprecate the Resource class in the SDK.

Requires the new package to be published, so we can link to it from the deprecation notice.

**Comment by sethladd** [comment]
https://chromiumcodereview.appspot.com/1385933002/ is the template, still needs the link.

**Comment by mit-mit** [comment]
Per discussion with @floitschG, we believe we should remove the resource class in 1.13. It was marked experimental in 1.12, and the actual work for a customer to migrate to the new package is very, very minimal.

**Comment by sethladd** [comment]
I have deprecated the class, marked for removal in 1.14. See https://codereview.chromium.org/1385933002

**Comment by kasperpeulen** [comment]
I don't understand how I should use the Resource class now. The dart package is deprecated and the pub package is pending.

**Comment by mit-mit** [comment]
We should have some more details on this (incl. new APIs) in the next few weeks. Stay tuned!

CC @kevmoo
