### ISSUE TITLE
Contributing wiki page links to non-existent "WritingApiDocumentation"

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#24497]
https://github.com/dart-lang/sdk/wiki/Contributing links to https://github.com/dart-lang/sdk/wiki/WritingApiDocumentation.md which doesn't exist.

**Comment by butlermatt** [comment]
In addition to the previous content that was on the WritingApiDocumentation, please consider also adding a style guide which would include sentence tense, structure and words to avoid or use. I know there are a number of preferences in style for documentation but I'm horrible at remembering them :)

**Comment by srawlins** [comment]
You mean like the [Dart Doc Comments](https://www.dartlang.org/articles/doc-comment-guidelines/)?

**Comment by butlermatt** [comment]
@srawlins Yes similar, but I'm thinking more expanded version of the "content" section of that article. Things such as preference for active voice (vs passive), etc. Particularly as they apply more stringently with the core API docs

**Comment by kwalrath** [comment]
https://en.wikiversity.org/wiki/Technical_writing_style has some good general tips for technical writing. We could point to that.

**Comment by kwalrath** [comment]
Oops, should have closed this.
