### ISSUE TITLE
Explore `hasFix` false negatives.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#24496]
Follow-up to https://github.com/dart-lang/sdk/issues/23874.

A few context-sensitive fixes were skipped in `hasFix` calculation in the interest of speed.  That speed should be better understood and benchmarked in case we can do better.

**Comment by bwilkerson** [comment]
(I'm assuming that by "false negative" you mean reporting that an error doesn't have a fix when it really does.)

My biggest concern here is that if the flag isn't accurate, and a client uses the flag to indicate to the user when a fix is available, then users might never discover the existence of the fix.

**Comment by pq** [comment]
:+1:  Adding @devoncarew for his 2 cents.

**Comment by devoncarew** [comment]
It's hard to know the impact w/o knowing how frequently this occurs. If it doesn't happen very often, it won't have much impact.

**Comment by pq** [comment]
Closing for staleness.
