### ISSUE TITLE
dart2js with csp mode: null reference error in IE 10

### ISSUE THREAD

**Issue by dustyholmes-wf** [dart-lang/sdk#24491]
We are experiencing an issue running a project in IE10 using compiled JS from dart2js with CSP mode enabled. I have created a reduced test-case that exhibits the issue with no external dependencies:

pubspec.yaml

``` yaml
name: dart_ie_csp
transformers:
- $dart2js:
     csp: true
```

web/test.dart

``` dart
import 'dart:async';
import 'dart:html';

StreamController _sc;

main() {
  _sc = new StreamController();
  querySelector('#content').innerHtml = 'Hello IE!';
}
```

web/index.html

``` html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<div id="content"></div>
<script src="test.dart.js"></script>

</body>
</html>
```

The resulting error (in IE10):
![image](https://cloud.githubusercontent.com/assets/1479507/10257576/de221a0e-691d-11e5-87cf-2316e2cae778.png)

In the image above prototype is null resulting in the error. Curiously, this is not null.

The key element here seems to be saving the new StreamController into a variable. Without saving to _sc there is no exception. I haven't been able to reproduce this with any other classes, at this point.

Simply switching CSP mode to false in the pubspec.yaml fixes the issue. However, we do require CSP-compliant JS in our production applications so this has become a roadblock.

**Comment by matanlurey** [comment]
IE10 is quite old now, and not supported AFAICT.
