### ISSUE TITLE
VM Service: Make Event.exception an @Error

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24492]
Currently, the `Event.exception` field for `PauseException` events is an `@Instance`. It would be more useful (and more consistent) for it to be an `@Error` instead—that gives the user access to the stack trace as well.

**Comment by turnidge** [comment]
Will do.

**Comment by turnidge** [comment]
Actually, after looking at this for a bit, I'm wondering if it would be sufficient to just query the vm for it's stack trace using the protocol?  We have some optimizations in the vm where we don't actually allocate the UnhandledException (Error) object in some cases.

**Comment by turnidge** [comment]
I have decided that the protocol already provides a mechanism to get the current stack trace when we are paused via the getStack() rpc, so I am closing this as will-not-fix.
