### ISSUE TITLE
Many of mirror's docs are not formatted.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#24505]
In general, according to the [Guidelines for Doc Comments](https://www.dartlang.org/articles/doc-comment-guidelines/):

* The first paragraph should be a "one-sentence" description.

Also need commas where necessary, and need to format lists and paragraphs as Markdown lists and paragraphs.

**Comment by srawlins** [comment]
First CL to fix this: https://codereview.chromium.org/1383403002/

**Comment by srawlins** [comment]
Second CL to fix this: https://codereview.chromium.org/1390813002/

**Comment by srawlins** [comment]
Aaand done.

**Comment by sethladd** [comment]
Cool, thanks Sam!
