### ISSUE TITLE
With new task model enabled, type propagation not done for final fields initialized at declaration site.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24504]
With code like the following:

    class Y {
      final x='hi';
      mth() {
        x;
      }
    }

With the new task model disabled, the propagated type of `x` is inferred to be `String`.  With the new task model enabled, the propagated type of `x` does not appear to be computed, so the type of `x` is inferred to be `Object`.

Note: due to #24503, type propagation of final fields sometimes appears to be broken even with the new task model disabled, since incremental resolution fails to preserve the propagated type.

**Comment by stereotype441** [comment]
Note: this causes the test "pkg/analysis_server/test/completion_test" to fail.  The test case that fails is "test035-1", which looks nearly the same as the code above, except that `x;` is replaced by `x.length`, and completion is requested between `.` and `length`:

    class Y {
      final x='hi';
      mth() {
        x.length;
      }
    }

The failure is that `length` is expected to show up in the list of completions, and it is not.

**Comment by bwilkerson** [comment]
I see 'length' in the list of completions, so I believe that this was fixed. If you're still seeing a problem, please re-open this issue.
