### ISSUE TITLE
Spec doesn't specify what happens to ??= with async expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24508]
The spec says 

> `v ??= e` is equivalent to the evaluation of the expression `((x) => x == null ? v = e : x)(v)` ...

This translation is not correct if `e` contains an `await` expression. 
In that case, the translation might want to not use a function expression, and be something like:
   ((x = v) == null ? v = e : x)
where `x` still fresh and declared somewhere.
This retains the synchronous execution in the non-null case that the expression suggests (if `v` is not null, the expression, including the await, is not executed).

**Comment by lrhn** [comment]
(This is a general problem with many of the rewrites in the spec - if they use anonymous functions to introduce a variable, they may also change the async/sync context of the expressions moved into the synthetic function).

**Comment by eernstg** [comment]
No milestone now: This does not block Dart 2.

Note that this issue is a subset of https://github.com/dart-lang/sdk/issues/25858.

**Comment by lrhn** [comment]
This has been fixed. It no longer uses a function literal to "desugar" the behavior.
