### ISSUE TITLE
With new task model enabled, command line analyzer no longer shows errors in non-".dart" files.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24502]
With the old task model, we determined how to report errors for a given file by reading its SourceEntry from the analysis cache, and then using the type of SourceEntry (DartEntry or HtmlEntry) to determine the type of errors to look for.  As a result, if a ".dart" file imports a file with some unrecognized suffix (e.g. ".lib"), that file will be analyzed as a dart file, and errors will be reported for it.

With the new task model, we determine how to report errors for a given file by passing it to each WorkManager; the WorkManagers use the file suffix to determine what type of errors to look for.  As a result, if a ".dart" file imports a file with some unrecognized suffix, errors won't be reported for that file at all.

At a minimum, I believe we should make one of the following changes:
- Redesign the way error reporting works, so that all files reached through `import` statements have errors reported as though they are Dart source files, 
- Add a hint, warning, or error so that if the user imports a file whose suffix is not `.dart`, they will be alerted to the fact that they won't see analysis results for that file.

(The first alternative seems superior in terms of user experience, but it may be _much_ more difficult, so we may with to consider the second alternative as a temporary fix).

**Comment by stereotype441** [comment]
Note: this causes the shared test "language/top_level_non_prefixed_library_test" to stop issuing warnings when the new task model is enabled, contrary to the expectation set in the file `tests/language/language_analyzer2.status`.

**Comment by natebosch** [comment]
It looks to me like the `dartanalyzer` cli is reporting these errors now.
