### ISSUE TITLE
Failure on DOM custom elements tests in Dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24516]
The tests
html/custom/document_register_type_extensions_test/construction
html/custom/document_register_type_extensions_test/parsing
and
co19/LayoutTests/fast/dom/custom/document-register-type-extensions_t01
are failing after commit
https://codereview.chromium.org/1382383003

These are marked in the status files tests/html/html.status and tests/co19/co19-dartium.status.

**Comment by alan-knight** [comment]
All three of these are passing now.
