### ISSUE TITLE
quick fix for "Condition must have a static type of bool"

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24518]
Say I would write this code:

```dart
DivElement div = ...;

if (div) {
   ...
}
```

I get the warning: "Condition must have a static type of bool".

Would be nice to have a quick fix that change the code into `div != null`. As this may be a mistake that devs from other languages would make. (Empirically confirmed at slack.)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1393953002

**Comment by scheglov** [comment]
Done.
https://github.com/dart-lang/sdk/commit/63d8b70fce4947332e11597e4f985249d2d667bb
