### ISSUE TITLE
Provide a synchronous way to access Isolate.packageMap and Isolate.packageRoot

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24513]
Currently, these getters are asynchronous. This makes them much more painful to use them in scripting code and library code, both of which are likely to want to be able to resolve `package:` URIs reliably.

To fix this, we should either make the getters synchronous by default or add `Isolate.packageMapSync` and `Isolate.packageRootSync` getters in addition. The former option provides a cleaner API at the cost of unavoidably briefly blocking the caller in cases where the information isn't synchronously available already—that is, where the isolate doesn't have `package:` imports.

**Comment by iposva-google** [comment]
cc @lrhn 

Not planned and impossible to implement.

**Comment by lrhn** [comment]
I'm all for this, if anyone can find a way to actually implement it. Not too hackish, preferably.

**Comment by nex3** [comment]
> Not planned and impossible to implement.

"Impossible" is an overstatement. Here are three different ways you could implement this:

* Pass the parsed package spec into the isolate before code starts running, so that `Isolate.packageMap` can always be accessed synchronously. This does mean that the package spec must be parsed even if the main isolate doesn't use `package:` imports, but that's a (presumably small) one-time cost.

* Make `Isolate.packageMapSync` reload the package spec if it's not synchronously available in the current isolate. This may cause redundant parsing of the spec, but it avoids eagerly doing work for isolates that don't use `package:` imports.

* Make `Isolate.packageMapSync` synchronously get the package map from whatever internal isolate is in charge of that. It sounds like you're saying that this sort of synchronous isolate communication is impossible, but #12617 indicates otherwise—if you call `Isolate.spawnUri` on code that contains `package:` imports, the VM must synchronously load the package map in order to synchronously resolve `package:` URIs.
