### ISSUE TITLE
Completion test broken by "Disable type overrides for properties."

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24511]
It appears that the [disable type overrides for properties](https://github.com/dart-lang/sdk/commit/ef434d6a9b258f9267267cf3a91ec5a47b26f526) CL breaks [test035-1](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/completion_test.dart#L2853).

FAIL: test035-1
  Expected 'length' but found none:
    [toString, hashCode]
  package:unittest/src/simple_configuration.dart 128:34  SimpleConfiguration.onExpectFailure
  package:unittest/src/simple_configuration.dart 24:13   _ExpectFailureHandler.fail
  package:unittest/src/matcher/expect.dart 103:18        fail
  test/completion_test_support.dart 49:7                 CompletionTestCase.assertHasCompletion
  test/completion_test_support.dart 91:9                 CompletionTestCase.runTest.<fn>

Does analysis need to be fixed or is the test itself bad?
Given...

class Y {final x='hi';mth() {x.^length;}}

... should x have a the propagated type of "String" ?
Based upon the test result, it appears that it was "String" but is now "Object".

**Comment by danrubel** [comment]
(TBR) fix test for now... https://codereview.chromium.org/1384823005

**Comment by scheglov** [comment]
The test itself is bad.
We don't perform type inferencing for fields with the old task model.
It should not have had type String before, it it does not now.

**Comment by danrubel** [comment]
Should the test itself be deleted or will the new task model perform type inferencing for fields?

**Comment by scheglov** [comment]
The new task model will perform type inferencing for fields.

On Tue, Oct 6, 2015 at 12:28 PM, Dan Rubel <notifications@github.com> wrote:

> Should the test itself be deleted or will the new task model perform type
> inferencing for fields?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24511#issuecomment-145972505>.
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.

**Comment by danrubel** [comment]
Then we leave the test in place and adjust the expectations when the new task model is enabled. Thanks!
