### ISSUE TITLE
dart analyzer does not return comments for library in sdk

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#24514]
Noticed that the docs generated on bleeding edge do not have library doc comments. https://github.com/dart-lang/dartdoc/issues/943. analyzer is not returning the comment for the libraries,
element.computeDocumentationComment is returning null.

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/4e6195fdf5f5bb6f4c6d1c303d4e0c4f6da3113d

**Comment by keertip** [comment]
Thank for the quick fix!
