### ISSUE TITLE
dart2js cps_ir: Remove code that adds interceptor to TypeTest from unsugar.dart

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24523]
Ideally we would add the interceptor only when needed for TypeTestViaFlag.

```
letPrim p1 = TypeTest x in
 ...
```

--->

```
letPrim p2 = Interceptor x in
  letPrim p1 = TypeTestViaFlag p2
    ...
```

This is currently awkward since the rewriting in type_propagation can only replace a Primitive with another Primitive.  Once we remove this problem, do the following:
- remove interceptor field from TypeTest
- remove initialization of interceptor from unsugar

**Comment by asgerf** [comment]
Returning a primitive from a visit method is intended to simply the very common case of 1-to-1 replacements, but it should be ok to insert additional primitives above the current one.

Here is how it looks in the null type test:
```dart
Primitive visitTypeTest(TypeTest node) {
  [...]
    Primitive nullConst = makeConstantPrimitive(new NullConstantValue());
    insertLetPrim(node.parent, nullConst);
    return new ApplyBuiltinOperator(
        BuiltinOperator.LooseNeq,
        <Primitive>[prim, nullConst],
        node.sourceInformation);
  [...]
}
```

**Comment by rakudrama** [comment]
@asgerf It works for a constant because it is not worth revisiting a constant.
We definitely want to revisit __Interceptor__ since it may be optimized away.

Similarly if we break __a & b__ into __NumToUint32(NumAnd(a, b))__ we will want to revisit NumAnd to compute its type to see if NumToUint32 is needed.
In this case, we probably already have the best type, so just updating the derived information might be OK.

**Comment by asgerf** [comment]
Good point.

Perhaps we should allow a CpsFragment to be returned from the visit method.

**Comment by rakudrama** [comment]
Obsolete
