### ISSUE TITLE
.packages: Pub: Unhide --no-package-symlinks flag

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24526]
Open for discussion: do we want/need a release with this flag visible?

Linked bug: https://github.com/dart-lang/pub/issues/1340

**Comment by mit-mit** [comment]
@kevmoo, did we get this unhidden? If not, can we get that done ASAP?

**Comment by kevmoo** [comment]
Closing this out – master bug is in pub: https://github.com/dart-lang/pub/issues/1340
