### ISSUE TITLE
Standardize dart2js and dartium semantics for cross frame access

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#24520]
Currently dartium allows cross frame access but dart2js does not. 
Dart2js can be made to allow cross frame access without a performance hit.
Dart Dev Compiler is likely the sticking point due to symbol based expandos for Dart methods.

**Comment by mit-mit** [comment]
Moving to 1.15 now that we are in cherry pick season for 1.14

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by jacob314** [comment]
Dartium now blocks cross frame access again.
Dart Dev Compiler does not yet support proper cross-frame access checks but there is a separate bug under dev compiler tracking that.
