### ISSUE TITLE
=> function example in "A Tour of the Dart Language" should not be void

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#24525]
In https://www.dartlang.org/docs/dart-up-and-running/ch02.html#functions, it says
> For functions that contain just one expression, you can use a shorthand syntax:
```dart
void printNumber(num number) =>
    print('The number is $number.');
```
> The `=> expr;` syntax is a shorthand for `{ return expr;}`. 

It seems a little bit like bad practice to suggest using `=>` with void functions, since the doc explicitly calls out that `=>` is  "shorthand for `{ return expr;}`"

**Expected result:**
`=>` should be used as an example with a function that has a return value, not a void function.
For example, something like:
```dart
String makeExcited(String message) => '$message!!';
```

**Comment by sethladd** [comment]
Actually, moved here: https://github.com/dart-lang/www.dartlang.org/issues/1484 :)

**Comment by keertip** [comment]
Thanks!
