### ISSUE TITLE
Major regression in 1.13.0-dev.6.0: no notifications for SDK files

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24538]
Analysis Server doesn't send notifications for files from the Dart SDK any more: `computedHighlights`, `computedNavigation`, `computedImplemented`, `computedOverrides`

**Comment by scheglov** [comment]
Started
https://codereview.chromium.org/1399873002

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/ebdfa991d4bef84fda38252ad915609c0b9ca977
