### ISSUE TITLE
No static warning if class has implicitly declared static getter and an explicitly declared instance  setter with the same name

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24534]
Specification (3rd Edition, June 2015) states (10.2 Getters):

It is a static warning if a class declares a static getter named v and also
has a non-static setter named v =. ... These warnings must be issued regardless of
whether the getters or setters are declared explicitly or implicitly.

Look at the following program:

``` dart
class C {
  static int v;
  set v(int v1) { /// static type warning
  }
}

main() {
  C.v;
}
```

There are instance setter and implicitly defined static getter. But dartanalyzer produces 
[error] The name 'v' is already defined

No static warning reported

**Comment by askeksa-google** [comment]
This is now an error, and the analyzer produces an error. Closing.
