### ISSUE TITLE
WebGL issue on iOS9

### ISSUE THREAD

**Issue by markhats** [dart-lang/sdk#24547]
I'm getting an issue with a three.dart (WebGL) app when running on iOS9 (Safari). It seems fine on everything else including iOS8.

The error in console is:
````
[Error] Uncaught Error: Error: receiver.getParameter is not a function. (In 'receiver.getParameter(pname)', 'receiver.getParameter' is undefined)
Stack Trace:
getParameter$1@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:68983:37
getParameter$1$x@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:108426:55
WebGLRenderer$10$alpha$antialias$canvas$context$depth$logarithmicDepthBuffer$precision$premultipliedAlpha$preserveDrawingBuffer$stencil@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:102218:45
....
````
Also:
````
Error] Uncaught Error: Error: receiver.getExtension is not a function. (In 'receiver.getExtension($name)', 'receiver.getExtension' is undefined)
Stack Trace:
getExtension$1@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:68980:37
getExtension$1$x@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:108423:55
$get$1@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:98514:43
WebGLRenderer$10$alpha$antialias$canvas$context$depth$logarithmicDepthBuffer$precision$premultipliedAlpha$preserveDrawingBuffer$stencil@http://www.autograph-maths.com/webversion-debug/autograph.html_bootstrap.dart.js:102227:31
....
````
A bit of debugging shows that ```receiver``` which is a ```WebGLRenderingContext``` doesn't have either ```getParameter``` or ```getExtension``` defined. Not sure where the problem lies since it only seems to occur in iOS9.

**Comment by alan-knight** [comment]
I think both of those should be there, according to https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14

There's some mention of a Safari bug with reference WebGLRenderingContext constants, but that doesn't seem like the same thing. If those are actually missing from the underlying JS object I'm not sure what we can do. Can you tell if they're just prefixed, or otherwise available?

**Comment by markhats** [comment]
After spending most of yesterday trying to debug this issue, I finally found it was related to the inclusion of ```webcomponents.js```. This seems to contain wrappers for the canvas element and the webgl context which are causing issues on iOS9. 

```
  (function(scope) {
    "use strict";
    var HTMLElement = scope.wrappers.HTMLElement;
    var mixin = scope.mixin;
    var registerWrapper = scope.registerWrapper;
    var unsafeUnwrap = scope.unsafeUnwrap;
    var wrap = scope.wrap;
    var OriginalHTMLCanvasElement = window.HTMLCanvasElement;
    function HTMLCanvasElement(node) {
      HTMLElement.call(this, node);
    }
    HTMLCanvasElement.prototype = Object.create(HTMLElement.prototype);
    mixin(HTMLCanvasElement.prototype, {
      getContext: function() {
        var context = unsafeUnwrap(this).getContext.apply(unsafeUnwrap(this), arguments);
        return context && wrap(context);
      }
    });
    registerWrapper(OriginalHTMLCanvasElement, HTMLCanvasElement, document.createElement("canvas"));
    scope.wrappers.HTMLCanvasElement = HTMLCanvasElement;
  })(window.ShadowDOMPolyfill);
```
For now, I have commented out this code and it seems to solve the issue for me. I don't really know what the purpose of the wrapper is and what consequences it is going to have commenting out the code. At the moment it seems fine.

I have also filed a bug report at: https://github.com/webcomponents/webcomponentsjs/issues/414

**Comment by alan-knight** [comment]
OK. There doesn't seem to be anything we should be doing at the Dart library level for that, so closing this. Feel free to re-open if you do see something.
