### ISSUE TITLE
Strong mode confusing message with async

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24540]
The following code gives the following message:

```
[error] Type check failed: fetch(request) (Future<UrlResponse>) is not of type UrlResponse (.../fetch.dart, line 56, col 10)
```

```dart
Future<UrlResponse> fetch(UrlRequest request) async {
  try {
    UrlLoaderProxy loader = new UrlLoaderProxy.unbound();
    _networkService.ptr.createUrlLoader(loader);
    UrlResponse response = (await loader.ptr.start(request)).response;
    loader.close();
    return response;
  } catch (e) {
    print("NetworkService unavailable $e");
    return new UrlResponse()..statusCode = 500;
  }
}

Future<UrlResponse> fetchUrl(String relativeUrl) async {
  String url = Uri.base.resolve(relativeUrl).toString();
  UrlRequest request = new UrlRequest()
    ..url = url
    ..autoFollowRedirects = true;
  return fetch(request); // error here
}
```

If I remove Future<> around the fetchUrl return type, or if I add "await" before the fetch() call in that method, the error goes away.

**Comment by sethladd** [comment]
cc @vsmenon @leafpetersen

**Comment by leafpetersen** [comment]
I'm a bit surprised that removing the `Future<>` works to silence the error - that might be a bug?  But we were discussing our restriction on returning Futures directly from `async` code earlier today and I think the consensus was that this should go away.  We'll likely fix this shortly.

**Comment by Hixie** [comment]
I was surprised also.

**Comment by Hixie** [comment]
Is the code buggy? What's the correct fix?

**Comment by sethladd** [comment]
The correct code would be:

```
Future<UrlResponse> fetchUrl(String relativeUrl) async {
  String url = Uri.base.resolve(relativeUrl).toString();
  UrlRequest request = new UrlRequest()
    ..url = url
    ..autoFollowRedirects = true;
  return await fetch(request); // error here
}
```

I also added http://stackoverflow.com/questions/33055477/what-happens-when-i-return-a-future-from-a-function-marked-as-async-in-dart/33055555

**Comment by Hixie** [comment]
I'm not convinced your stackoverflow answer is right... I'm sure I've read documentation to the effect that the "async" code unwraps Future<>s. Mostly I'm just confused about that now...

**Comment by zoechi** [comment]
`await` unwraps

**Comment by Hixie** [comment]
Does `async` not unwrap? i.e. is `Future<int> foo() async { ... }` the same or different than `int foo() async { ... }` ?

**Comment by zoechi** [comment]
No, as @sethladd wrote, if you add `async` to a funtion the return type is always `Future<something>`. `await` does the unwrapping.

**Comment by sethladd** [comment]
> I'm not convinced your stackoverflow answer is right

I tested it on dartpad.dartlang.org : https://dartpad.dartlang.org/92c5a74874fd92a5aec2

**Comment by Hixie** [comment]
> `int foo() async { ... }` is invalid

Interesting. I could have sworn I had code that used async with a non-Future return type and had the Future implied around it. Weird. Oh well.

**Comment by sethladd** [comment]
> I could have sworn I had code that used async with a non-Future return type and had the Future implied around it.

You probably did, because that works fine. :)

`Future<int> neat() async => 42` is completely legit. Here, 42 is the value that completes the Future that was returned.

`neat() async => 42` is also completely legit. The return type annotation is dynamic, which is more than happy to allow `Future<int>`

`int neat() async => 42` is broken in checked mode, because the type of the object returned by the implementation of the function is `Future<int>`

**Comment by lrhn** [comment]
> I tested it on dartpad.dartlang.org : https://dartpad.dartlang.org/92c5a74874fd92a5aec2

That test is misleading because `thing` is actually `Future<dynamic>`. All `async` functions return Future<dynamic> objects, independently of how they are typed.
I've elaborated by e-mail.

**Comment by sethladd** [comment]
Thanks @lrhn ! I need to get smarter++ for this area of the language. More info here: http://stackoverflow.com/questions/33055477/what-happens-when-i-return-a-future-from-a-function-marked-as-async-in-dart

**Comment by vsmenon** [comment]
In the context of the original example, what's the cleanest change?  Allowing this pattern?  Telling the programmer to drop the `async` on the declaration of `fetchUrl`?

**Comment by sethladd** [comment]
If you have zero awaits in your function, and it's marked as async, and all you do is return a Future, we could suggest the developer removes the async marker.
