### ISSUE TITLE
Isolate.spawnUri: rename packages arg to packageMap

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24545]
As a named arg, it should align with its corresponding property.

Let's do it now while we still can!

**Comment by lrhn** [comment]
Good point. It made sense as an argument because it matched the command line parameter, but it's better to match the property.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/57f4827c7684e0afc466cd035a9bb3ecaa6d2fd7 – this will be cherry-picked into 1.13
