### ISSUE TITLE
completion for import can be done smarter

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24555]
Every so many minutes I need to add an import, I think it may be nice if the code completion for the import keyword is a little smarter.

What about this:
![image](https://cloud.githubusercontent.com/assets/1035299/10418201/79db3df8-7054-11e5-9915-e922d9911991.png)

autocomplete to:
``import '<caret>'`
![image](https://cloud.githubusercontent.com/assets/1035299/10418205/920c33fa-7054-11e5-8e67-4fc2fc920415.png)

this saves 4 keystrokes:
  1. pressing space
  2. pressing `'`, 
  3. pressing arrow right
  4. pressing `;`

I think this would be convenient, especially as now the webstorm auto import quick fixs don't work anymore in all cases.

**Comment by alexander-doroshko** [comment]
Hint: you can configure corresponding live template in WebStorm that will insert template and run code completion at caret between quotes. For example if you set 'i' as an abbreviation you'll only need to type `i<Tab>` and the next keystrokes are to select uri from already shown completion list. Adding more custom templates for creating classes/methods, etc. can gain your productivity even more.

**Comment by jwren** [comment]
https://codereview.chromium.org/1860213002/
