### ISSUE TITLE
Observatory build broken when bootstrapping

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24556]
Removing dart:profiler from the SDK breaks the observatory build when bootstrapping, since the pinned set of downloaded libraries for the observatory build includes an older version of analyzer requiring dart:profiler.

This can be seen on the debian package builder, which uses the bootstrap executable to build the observatory: https://uberchromegw.corp.google.com/i/client.dart/builders/linux-distribution-support-debian_wheezy-be

I think we just need to update the zipped up set of libraries that the observatory build downloads.
This needs to be fixed in order to do the next dev channel release, in a couple of days.

@johnmccutchan

**Comment by whesse** [comment]
Also, we can get rid of the error from the charted package at the same time (if a newer version of charted fixes it):
packages/charted/core/utils/rect.dart:22:16:
The class 'Rect' overrides 'operator==', but not 'get hashCode'.
  bool operator==(other) =>
               ^^
[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/charted/core/utils/rect.dart:58:16:
The class 'AbsoluteRect' overrides 'operator==', but not 'get hashCode'.
  bool operator==(other) =>

**Comment by johnmccutchan** [comment]
@whesse No charted package and I've already filed a bug with the team.

I'm preparing new Observatory packages.

**Comment by johnmccutchan** [comment]
@whesse I've updated the packages but the mirrors don't seem to be updating?

**Comment by johnmccutchan** [comment]
See this commit https://github.com/dart-lang/observatory_pub_packages/commit/5c199c5954146747f75ed127871207718dc87786

**Comment by johnmccutchan** [comment]
This is the CL to pull the lever: https://codereview.chromium.org/1400023002

**Comment by whesse** [comment]
The mirror has updated, at https://chromium.googlesource.com/external/github.com/dart-lang/observatory_pub_packages

**Comment by mit-mit** [comment]
Issues resolved, closing
