### ISSUE TITLE
DOM Issue TBD: broken Angular2 build

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24553]
See https://github.com/angular/angular/issues/4467

@yjbanov Can you provide details here? It seems that 1.13.0-dev.6.0 hasn't resolved things yet, either

CC @tbosch

**Comment by yjbanov** [comment]
The tests seem to fail due to DOM issues. Can't tell exactly yet what the issue is, but all failing tests attempt to access DOM in some way.

**Comment by kevmoo** [comment]
Trying a bleeding edge build to see if the issue has been fixed

https://travis-ci.org/angular/angular/jobs/85171580

CC @terrylucas @alan-knight

**Comment by kevmoo** [comment]
Trying again - https://travis-ci.org/angular/angular/jobs/85185760

**Comment by kevmoo** [comment]
...and again: https://travis-ci.org/angular/angular/builds/85188496

**Comment by kevmoo** [comment]
...and again https://travis-ci.org/angular/angular/builds/85189153

**Comment by kevmoo** [comment]
Seems like we're gold – see https://travis-ci.org/angular/angular/builds/85189153

We'll have a get a couple of patches into Angular, though

**Comment by hterkelsen** [comment]
The patches for dart:profiler are already out:
https://github.com/angular/di.dart/pull/225
https://github.com/angular/angular.dart/pull/1742

**Comment by kevmoo** [comment]
I have a pull request out that turns dev channel back on https://github.com/angular/angular/pull/4745

Blocked by the patches above (from @hterkelsen )

**Comment by kevmoo** [comment]
Both above patches have landed. Trying another build https://travis-ci.org/angular/angular/builds/85439407

**Comment by kevmoo** [comment]
Fixed! https://github.com/angular/angular/issues/4467
