### ISSUE TITLE
latest analyzer is analyzing html files in the build/ directory

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24552]
<img width="722" alt="screen shot 2015-10-10 at 5 13 28 pm" src="https://cloud.githubusercontent.com/assets/1269969/10413918/5758cd1e-6f72-11e5-80cd-413a6fe3e5c0.png">

I'm seeing hundreds of errors in an existing project (dartpad) that were not there w/ the previous version of the analysis server. I'm using `1.13.0-dev.6.0`. These files are:

- html files from the implementation of polymer - not files I would want analyzed
- they don't have things like `head`, `body`, or `html` sections, by design
- they are in the `build/` dir, which itself shouldn't be analyzed

These errors are drowning out all the other errors and warnings on my project.

**Comment by zoechi** [comment]
I reported a similar issue (not about `build` directory though) https://youtrack.jetbrains.com/issue/WEB-18506 which should be fixed by  https://codereview.chromium.org/1395033003

**Comment by devoncarew** [comment]
Cool - that's related, but I think a separate issue.

**Comment by scheglov** [comment]
Is it really different? Why?
We don't report "Expected DOCTYPE" at all now.

**Comment by devoncarew** [comment]
That was one category of errors among the 500 different errors reported (I max out at reporting 500 errors per project). Happy to discuss this more tomorrow, but:

- we shouldn't analyze files in `build/`
- these files run properly in the browser - if there really were issues, they shouldn't be at an error level - that would imply some sort of runtime error
- these _are_ valid polymer files. Given all the variants of html and templating languages out there, I question whether we want to be strict about interpreting (and reporting) html issues. These issues will be false positives for the user (valid for their use case)

**Comment by sethladd** [comment]
Noticed this too when looking at a customer's screen.

**Comment by zoechi** [comment]
@devoncarew according to your screenshot the files seem to be in `lib` not in `build`.

The errors about to missing `<!DOCTYPE ...>` are gone now, but I still get hundreds of errors because of not recognized HTML comment tags

![image](https://cloud.githubusercontent.com/assets/405837/10601612/13429cce-7713-11e5-8a2b-9817fcb29301.png)

and dozens of errors on the same position

![image](https://cloud.githubusercontent.com/assets/405837/10601635/305e64dc-7713-11e5-9453-0753e869302f.png)

**Comment by devoncarew** [comment]
@zoechi, I also see errors in `lib/` :)

**Comment by pq** [comment]
@scheglov: where are we on these points?

- [ ] we shouldn't analyze files in `build/`
- [ ] these files run properly in the browser - if there really were issues, they shouldn't be at an error level - that would imply some sort of runtime error
- [ ] these are valid polymer files. Given all the variants of html and templating languages out there, I question whether we want to be strict about interpreting (and reporting) html issues. These issues will be false positives for the user (valid for their use case)

**Comment by scheglov** [comment]
These errors are produced by the https://github.com/dart-lang/html package.
So, you should open issues against it instead.

If `paper-icon-button.html` looks like (this)[https://github.com/Polymer/paper-icon-button/blob/master/paper-icon-button.html], then it violates the [HTML5 spec](http://www.w3.org/TR/html5/syntax.html#comments), and even GitHub highlight it as an error.

![image](https://cloud.githubusercontent.com/assets/384794/10613354/abbd3928-7709-11e5-880f-c9f46eb18eda.png)

**Comment by scheglov** [comment]
@pq 

1. `build/` folder is not special in general case, so it is analyzed. If this is not desired, then `.analysis_options` should be used.

2. I guess we need a way to disable reporting HTML parsing errors completely. Again, in `.analysis_options`. I would appreciate some explanation how I could implement this :-)

3. Some errors are actual errors even in Polymer. So, in the future it would be nice to make disabling errors more fine grain. But it is very hard to discover. There are about 100 errors reported by the `html` package. There is not way user can find them out. Hm... Or we could include IDs of these errors into the error and provide Quick Fixes to update `.analysis_options` file!

**Comment by bwilkerson** [comment]
Perhaps for 1.13 we should just stop reporting the HTML parsing errors until we can work out some of the details of how to disable certain errors. At the moment, it sounds like the noise is harming the UX more than the valid errors are helping it.

**Comment by pq** [comment]
> Or we could include IDs of these errors into the error and provide Quick Fixes to update .analysis_options file!

Are there "stable" identifiers?

**Comment by scheglov** [comment]
Kind of :-)
https://github.com/dart-lang/html/blob/master/lib/src/constants.dart

**Comment by bwilkerson** [comment]
> Are there "stable" identifiers?

No, not yet. We're working on getting them. I **really** don't want to use internal constants as identifiers.

**Comment by scheglov** [comment]
I've opened an issue to track controlling HTML parsing errors.
https://github.com/dart-lang/sdk/issues/24643

**Comment by scheglov** [comment]
@bwilkerson OK https://codereview.chromium.org/1418663002

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/29f3baf6465fe2d35b5d6ab49e6df0dff300fbd5
