### ISSUE TITLE
Code completion doesn't recommend sync or async*

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#24554]
In the first example 'async*' isn't being recommended

![image](https://cloud.githubusercontent.com/assets/2978182/10417046/5790db82-7026-11e5-8368-f0853e46c82f.png)

In the second 'sync' is not being recommended

![image](https://cloud.githubusercontent.com/assets/2978182/10417048/5edb039a-7026-11e5-9f0c-a7ca3c5dc074.png)

**Comment by danrubel** [comment]
Fixed https://codereview.chromium.org/1509193003/
