### ISSUE TITLE
Dartium: Objects in IFrames get wrapped, even if accessed through JSInterop

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24568]
e.g. LibTest/html/IFrameElement/IFrameElement.created_A01_t01

**Comment by terrylucas** [comment]
class MyIFrameElement extends IFrameElement {
  factory MyIFrameElement() {
    return new Element.tag('my-iframe');
  }

  MyIFrameElement.created() : super.created();

  void testit() {
    print("In testit 222");
  }
}



iframe_test() {
  var ife;
  var tag = 'my-iframe';
  document.registerElement(tag, MyIFrameElement, extendsTag: 'iframe');

  ife = document.createElement('iframe', 'my-iframe');
  document.body.append(ife);

  ife.testit();
  print(ife);
}

**Comment by terrylucas** [comment]
See co19 issue https://github.com/dart-lang/co19/issues/117 the test needs to change.
