### ISSUE TITLE
analyzer no longer removes the whitespace before the /// in comments

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#24561]
`computeDocumentationComment` no longer removes the whitespace before the `///` in comments. 

```
  /// Start a synchronous operation labeled [name]. Optionally takes
  /// a [Map] of [arguments]. This operation must be finished before
  /// returning to the event queue.
```

returns 
"/// Start a synchronous operation labeled [name]. Optionally takes\n  /// a [Map] of [arguments]. This operation must be finished before\n  /// returning to the event queue."

Note the whitespace after \n. This was not the case in the previous version.

**Comment by scheglov** [comment]
Please attach the file you see the problem it.

**Comment by srawlins** [comment]
Dup of dart-lang/dartdoc#947.

**Comment by sethladd** [comment]
@srawlins not quite a dupe. This is the root cause for https://github.com/dart-lang/dartdoc/issues/947

**Comment by keertip** [comment]
@scheglov  https://github.com/dart-lang/sdk/blob/master/sdk/lib/developer/timeline.dart

**Comment by scheglov** [comment]
Ah... Now I understand.
This is AsDesigned.
This method returns `comment for this element as it appears in the original source`.
This means with all the beginning / ending delimiters, spaces, etc.
It's up to the client to strip all this stuff for the specific use.

**Comment by keertip** [comment]
@scheglov , this behavior has changed from previous versions of the analyzer.  It used to trim the whitespace before the `///`

**Comment by scheglov** [comment]
True, it used too.
But it wasn't promised.
