### ISSUE TITLE
Specific form of typedef causes runtime error

### ISSUE THREAD

**Issue by krisgiesing** [dart-lang/sdk#24567]
Self-contained test (requires only dart:sky) here:

https://gist.github.com/krisgiesing/ce88a972d2d1acbae14a

**Comment by Hixie** [comment]
cc @sethladd

**Comment by sethladd** [comment]
Hi @krisgiesing what version of the VM are you using?

**Comment by krisgiesing** [comment]
I'm running the Flutter unit tests here. What's the best way to check?

**Comment by abarth** [comment]
```
abarth@abarth3:/src/flutter/engine/src$ grep dart_version DEPS 
abarth@abarth3:/src/flutter/engine/src$ grep dart_revision DEPS 
  'dart_revision': '80dec9493fa8caa2d26c230a23ae7e8eb7cb3bb6',
    Var('chromium_git') + '/external/github.com/dart-lang/sdk.git' + '@' + Var('dart_revision'),
```

**Comment by krisgiesing** [comment]
After logging this issue I had to do a few rounds of merges to catch up to HEAD.  However, my best guess is this:

grep dart_revision DEPS
  'dart_revision': 'c9334ed61f11df2d9aecc6311a5981eba0e55c01',
    Var('chromium_git') + '/external/github.com/dart-lang/sdk.git' + '@' + Var('dart_revision'),

**Comment by zoechi** [comment]
Shouldn't  
`typedef void FooBar(Event event);` be  
`typedef void FooBar(sky. Event event);`

**Comment by Hixie** [comment]
The FooBar typedef isn't used in the test. It's mere presence (pointing at the locally defined Event, not sky.Event) causes the failure.

**Comment by krisgiesing** [comment]
Exactly as Ian says.

**Comment by rmacnak-google** [comment]
The signature class of _handleEvent's implicit closure is probably incorrect canonicalized to FooBar.

**Comment by crelier** [comment]
I have a small reproducible case:

import "package:expect/expect.dart";
import 'dart:math' as math;

class Random { }
typedef F(Random r);

main() {
  f(Random r) { }
  g(math.Random r) { }
  Expect.isTrue(f is F);
  Expect.isFalse(g is F);  // fails here
}

**Comment by crelier** [comment]
Fixed in https://codereview.chromium.org/1584223006/

**Comment by krisgiesing** [comment]
Thanks!
