### ISSUE TITLE
MapMixin should use containsKey in putIfAbsent

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#24560]
Currently putIfAbsent inlines the implementation of containsKey and so defines it twice.

This means that if class uses MapMixin and implements containsKey for either efficiency or behavior it *must* also implement putIfAbsent. putIfAbsent should instead call containsKey.

**Comment by lrhn** [comment]
Generally, we try to avoid having methods depend on other public (overridable) methods. That's not generally true here - rather, the idea was to define all the implemented methods in terms of the few unimplemented ones.
In this case, I think it's reasonable to use `containsKey` in `putIfAbsent`

Still, if the contains method is important, then maybe the `keys` iterable's `contains` method should also be implemented efficiently.

**Comment by lrhn** [comment]
Done
