### ISSUE TITLE
dynamic invoke hint when nothing should be dynamic

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24564]
```class A { } void main() { A a; a ??= new A(); }```
gets:
```[hint] a ??= new A() requires dynamic invoke```
...everything's typed, it doesn't seem like there'd be anything dynamic about it.

This is with --strong-hints, dartanalyzer version 1.13.0-dev.6.0.

**Comment by jmesserly** [comment]
We don't have strong hints anymore but there's still a bug here:
```dart
class A {}
class B extends A {}
// this is not an error in --strong but should be
void main() { B a; a ??= new A(); print(a); }
// this error will be correctly reported
void main2() { B a; a = new A(); print(a); }
```

this may be related to https://github.com/dart-lang/sdk/issues/25387

**Comment by jmesserly** [comment]
pri-high because it's bad if we can't correctly type check null aware ops

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1575173005
