### ISSUE TITLE
"inferred type" feedback from strong mode isn't actionable for VM users

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24563]
We're using Strong Mode for a VM-only project, and the following feedback isn't clear if this is something actionable or something we need to take care of.

`[hint] (symbol) => config.stocks[symbol] has inferred type (String) → dynamic`

From this line: https://github.com/flutter/engine/blob/master/examples/stocks/lib/stock_home.dart#L174

Either:

* This means there is a bug, which we should fix in our code. However, it doesn't sound like a bug I need to address.
* This means something to DDC users, but not VM users. If so, can we disable this feedback if you are not compiling with DDC?
* This is just an FYI, with no implications on the running app. If so, is there any classification for this kind of feedback? We're trying to be hint-free.

**Comment by sethladd** [comment]
cc @hixie @vsmenon @leafpetersen

**Comment by vsmenon** [comment]
I think this is the third, even for DDC users, we should suppress this.

**Comment by Hixie** [comment]
This isn't even actionable for DCC users, as far as I can tell. At least, I've no idea what it means for me.

**Comment by sethladd** [comment]
Thanks @vsmenon . Does it make sense to reclassify instead of suppress? Like --enable-inference-feedback ? Would anyone want to know a return type was inferred?

**Comment by jmesserly** [comment]
We've removed all of these. FWIW `--strong-hints` was supposed to be a hidden flag :). Sorry about that.

**Comment by jmesserly** [comment]
specifically it was fixed in this commit: https://github.com/dart-lang/sdk/commit/f092c247fd7317339608483dd9613bae89cd4b20

**Comment by Hixie** [comment]
No flags will be hidden if they're visible in the source. :-)

**Comment by zoechi** [comment]
Seems to be back.
I get this now for every closure. 30% of my code now has a wiggled underline when I enable strong-mode.

**Comment by jmesserly** [comment]
Doh! @leafpetersen any ideas how this one might be back? Did we change the error/warning levels?

@zoechi if you can give us a repro that would be really helpful!

**Comment by jmesserly** [comment]
High priority based on "30% of code has wiggled underline". That does not sound pleasant :)

**Comment by zoechi** [comment]
https://github.com/bwu-dart/bwu_polymer_routing `polymer1` branch 
change `strong-mode: false` to `strong-mode: true` in `.analysis_options` and `example_/.analysis_options`

**Comment by leafpetersen** [comment]
Moving the inference code into the resolver moved the inference hints from behind the programmatic flag.  I'll have a fix shortly.
