### ISSUE TITLE
Tear-off property extraction does not work for unary minus

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24572]
Unary minus property extraction does not work. Example:
```dart
class C {
  int value;
  int operator - () {
    return -value;
  }

  int operator - (var v) {
    return v - 2;
  }
}

main() {
  C o = new C();
  var f1 = o#unary-;
  var f2 = o#-;
}
```
Actual result of running this code (Dart VM version: 1.13.0-dev.6.0 (Wed Oct  7 08:09:59 2015) on "linux_x64")
```dart
error: line 34 pos 19: unexpected token ';'
  var f = o#unary-;
                  ^
```
Without line 'var f1 = o#unary-;' code works. According specification (3-rd edition, June 2015) "10.1.1 Operators"

"The name of the unary operator - is unary-."

So, if class contains unary minus operator, then o#unary- should extract this operator

**Comment by lrhn** [comment]
While `unary-` is the name of the operator, it's not a syntactically valid production of the `operator` production in the grammar.
The grammar in question is:
```
postfixExpression: ... |
    primary (selector* | ( ‘#’ ( (identifier ‘=’?) | operator)))
```
That is, what can come after a `#` is either an identifier (optionally followed by `=`) or an operator. The operator production includes "-" but not "unary-".
So, `o#unary-` is parsed as `(o#unary)-` and expects something after the minus operator.

You currently can't extract the unary minus operator.
