### ISSUE TITLE
No static warning if class has implicitly declared static setter and an instance  method or getter with the same name

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24573]
According Dart specification (3-rd Edition, June 2015) "10.3 Setters"

"It is a static warning if a class declares a static setter named v = and also has a non-static member named v....These warnings must be issued regardless of whether the getters or setters
are declared explicitly or implicitly"

Run the following code in dartanalyzer

``` dart
class C {
  static int v;
  int v() { return 3; }
}

main() {
  C.v = 2;
}
```

Actual result: 

``` dart
[error] 'v' cannot be used to name a method, there is already a getter with the same name
```

No static warning produced
Expected: both error and warning should be issued

**Comment by lrhn** [comment]
In practice, it would be confusing to have two different warnings and errors for the same variable name conflict. Showing only the most critical one (the errors that prevents compilation) seems like the correct choice.

Is this allowed by the specification?

**Comment by sgrekhov** [comment]
There are no warning only if static setter is declared implicitly. If static setter, in the example above, is declared explicitly dartanalazer produces both error and warning. According the specification there should be no difference if "... the getters or setters are declared explicitly or implicitly"

**Comment by lrhn** [comment]
Agree on that.

**Comment by srawlins** [comment]
The analyzer now produces:

> line 2 • Class 'C' can't define static member 'v' and have instance member 'C.v' with the same name.
Try renaming the member to a name that doesn't conflict.
