### ISSUE TITLE
Invalidate/recompute context when strong mode is (un)set.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#24574]
Specifically, if an `.analysis_options` file is modified from
```
analyzer:
  strong-mode: false
```
to
```
analyzer:
  strong-mode: true
```
analysis results for that context should be re-computed.

**Comment by pq** [comment]
Moreover, if an options file is added or removed, the *right thing* should happen.

**Comment by pq** [comment]
https://codereview.chromium.org/1399893004/

**Comment by pq** [comment]
Implemented w/ cae05d6bd43d8f2cf616b6d93317c28a99778190.

**Comment by zoechi** [comment]
Where does it look for the `.analysis_options` file. In the project directory or user home directory?

**Comment by pq** [comment]
Project directory.
