### ISSUE TITLE
map_literal_oom_test fails on content shell in checked mode

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24571]
The test standalone/map_literal_oom_test fails on content shell (drt) in checked mode.  It passes on dartium, only failing on drt.  Marking this as low priority, since other out-of-memory tests are just skipped on dartium and drt, and the problem is probably just in what the test expects.  The error is

 FAILED: none-drt-checked release_x64 standalone/map_literal_oom_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[content_shell]:

stdout:
# READY

Observatory listening on http://127.0.0.1:40817
CONSOLE MESSAGE: line 78: {
  "type": "debug",
  "value": "test_controller.js started",
  "timestamp": 0
}
CONSOLE MESSAGE: line 78: {
  "type": "window_onerror",
  "value": "window.onerror called: \n\nhttp://127.0.0.1:58502/root_build/generated_tests/none-drt-checked/tests_standalone_map_literal_oom_test/test.dart:0:\nException: Out of Memory\n\n",
  "timestamp": 0.369
}
CONSOLE ERROR: Exception: Out of Memory
CONSOLE INFO: Observatory listening at http://127.0.0.1:40817/
CONSOLE MESSAGE: line 78: {
  "type": "window_onerror",
  "value": "window.onerror called: \n\nhttp://127.0.0.1:58502/root_build/generated_tests/none-drt-checked/tests_standalone_map_literal_oom_test/test.dart:0:\nInternal error: Dart_Invoke expects library argument 'target' to be loaded.\n\n",
  "timestamp": 0.372
}
CONSOLE ERROR: Internal error: Dart_Invoke expects library argument 'target' to be loaded.
Content-Type: text/plain
Running /mnt/data/b/build/slave/dartium-lucid64-full-be/build/src/dart/tests/standalone/map_literal_oom_test.dart

FAIL
FAIL
# EOF
# EOF

stderr:
[795:795:1012/220941:11609714889:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[868:868:1012/220941:11609980938:ERROR:renderer_main.cc(207)] Running without renderer sandbox
Exhausted heap space, trying to allocate 262512 bytes.
# EOF

**Comment by whesse** [comment]
This test has started passing again on all platforms except x64, where it is still failing.  Status is updated in tests/standalone/standalone.status.

The list of commits that seems to include the change that fixed it on most platforms is:

Change #42752

Changed by	hausner@google.com
Changed at	Thu 29 Oct 2015 16:36:31
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	7c924f0a25b83ce9c3bf96e5dbbee314ca2f0eff
Comments

Token stream iterator improvement
Eliminate the double indirection in accessing the token object array. It has no measurable effect, unfortunately :)

BUG=
R=asiva@google.com

Review URL: https://codereview.chromium.org/1427863002 .
Changed files

runtime/vm/object.cc
runtime/vm/object.h
Change #42753

Changed by	kevmoo@google.com
Changed at	Thu 29 Oct 2015 16:36:58
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	bf713555bffaece660b0df2ee5fed44603fa5c9a
Comments

Remove dart:isolate changes from 1.13 changelog, documented spawnUri environment argument
Closes https://github.com/dart-lang/sdk/issues/24757
helps https://github.com/dart-lang/sdk/issues/24474

R=sethladd@google.com

Review URL: https://codereview.chromium.org/1423323003 .
Changed files

CHANGELOG.md
Change #42754

Changed by	terry@google.com
Changed at	Thu 29 Oct 2015 17:05:59
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	e84f9941e1cf210646aef72e01eefaa993a7b798
Comments

Fixed Native custom element
BUG=24754
R=alanknight@google.com

Review URL: https://codereview.chromium.org/1422323006 .
Changed files

sdk/lib/html/dartium/html_dartium.dart
sdk/lib/html/html_common/conversions_dartium.dart
Change #42755

Changed by	scheglov@google.com
Changed at	Thu 29 Oct 2015 17:46:00
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	03eed1c3c944d3122a257a95d4e2dcc391f8668e
Comments

Fix for duplicate priority sources.
R=brianwilkerson@google.com
BUG=

Review URL: https://codereview.chromium.org/1408163008 .
Changed files

pkg/analysis_server/lib/src/analysis_server.dart
pkg/analysis_server/test/analysis/set_priority_files_test.dart
Change #42756

Changed by	jacobr@google.com
Changed at	Thu 29 Oct 2015 19:17:08
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	688b69fb65f2c6c51a68df56551de484fd5d2eea
Comments

Support isExternal method on MethodMirror in the Dart VM. Not really intended for public consumption. switch to using isExternal and using anonymous.
BUG=
R=alanknight@google.com, asiva@google.com

Review URL: https://codereview.chromium.org/1421133003 .
Changed files

runtime/lib/mirrors.cc
runtime/lib/mirrors.h
runtime/lib/mirrors_impl.dart
sdk/lib/js/dartium/js_dartium.dart
Change #42757

Changed by	jacobr@google.com
Changed at	Thu 29 Oct 2015 19:18:19
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	e0d2263bb3b77e20b319a539cfefe3e8a76a2d5c
Comments

Add @anonymous annotation and restrict object literal constructors to only anonymous classes. This frees up defining factory constructors that do not correspond to object literals on JS interop classes.
BUG=
R=sra@google.com

Review URL: https://codereview.chromium.org/1409033005 .
Changed files

pkg/compiler/lib/src/diagnostics/messages.dart
pkg/compiler/lib/src/js_backend/backend_helpers.dart
pkg/compiler/lib/src/js_backend/js_interop_analysis.dart
pkg/compiler/lib/src/ssa/builder.dart
pkg/js/lib/js.dart
pkg/js/pubspec.yaml
tests/html/js_typed_interop_test.dart

**Comment by whesse** [comment]
@alan-knight 
Now the test has started failing again on the ia32 platforms around Dec 1.  Updating the status.

I suggest it is probably the commit to dartium in https://codereview.chromium.org/1490763005

The full blamelist for the run where it started again is:
Change #43218

Changed by	asgerf@google.com
Changed at	Tue 01 Dec 2015 08:20:16
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	ab37dac248ecdb49a28ec6bb057c11e046d8be29
Comments

dart2js cps: Add more constraint rules to bounds-check elimination.
The sign of a +/- operation is computed, which can help in cases where
the result could not be proven to be within 53-bit range.

Also added rules for ~/, %, >>, &, and unary negation operators.

BUG=
R=sra@google.com

Review URL: https://codereview.chromium.org/1479193002 .
Changed files

pkg/compiler/lib/src/cps_ir/bounds_checker.dart
pkg/compiler/lib/src/cps_ir/octagon.dart
pkg/compiler/lib/src/cps_ir/type_propagation.dart
Change #43219

Changed by	hausner@google.com
Changed at	Tue 01 Dec 2015 09:21:17
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	ad0f14e0ce54efb62a297b259156face55708100
Comments

Eliminate all but one top-level class per library.
Each script has an associated top-level class in which the top-level functions and fields are stored, and the reference to the script. All other fields in the TL class are unused. There are 380 TL classes in corelib alone; eliminating them saves space.

This CL eliminates all TL classes but one per library. All TL functions and fields in the library are stored in that TL class. Because scripts are not stored directly in functions and fields, but are a
...skip...
Before:
Size of vm isolate snapshot = 930813
New space (0k of 0k) Old space (1184k of 1624k)
VM Isolate: Number of symbols : 14909
Size of isolate snapshot = 261873
New space (0k of 2048k) Old space (987k of 1024k)

After:
Size of vm isolate snapshot = 931101
New space (0k of 0k) Old space (713k of 1156k)
VM Isolate: Number of symbols : 14907
Size of isolate snapshot = 256956
New space (0k of 1024k) Old space (514k of 768k)

R=iposva@google.com

Review URL: https://codereview.chromium.org/1410383020 .
Changed files

runtime/lib/mirrors.cc
runtime/vm/object.cc
runtime/vm/object.h
runtime/vm/parser.cc
runtime/vm/parser.h
runtime/vm/raw_object.h
runtime/vm/raw_object_snapshot.cc
Change #43220

Changed by	fschneider@google.com
Changed at	Tue 01 Dec 2015 09:26:33
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	a05ad6111a7fe8e98ee8b713b285458da36b1e55
Comments

VM: In CompileAll, don't iterate collected closures for every class
Instead iterate all collected closures at the end. This avoids unnessarily
visiting of the collected closures array and calling Function::Owner.

BUG=
R=hausner@google.com

Review URL: https://codereview.chromium.org/1491503003 .
Changed files

runtime/vm/compiler.cc
runtime/vm/flow_graph_optimizer.h
runtime/vm/object.cc
Change #43221

Changed by	alanknight@google.com
Changed at	Tue 01 Dec 2015 10:48:19
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	160355de4296d7e775ff721d8f568fec634ae953
Comments

Add the right type conversions for various postMessage methods
BUG=

Review URL: https://codereview.chromium.org/1490763005 .
Changed files

sdk/lib/html/dart2js/html_dart2js.dart
sdk/lib/html/dartium/html_dartium.dart
tools/dom/scripts/generator.py
Change #43222

Changed by	zra@google.com
Changed at	Tue 01 Dec 2015 10:52:19
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	618d4ee9b741e42f1de61293a4cd7f5e68a84da7
Comments

Thread and Timeline fixes for Mojo.
Creates an OSThread in OSThread::Current() if a thread doesn't
already have one.

Also removes the setup of an unneeded StackZone from a Timeline API
function.

BUG=

Review URL: https://codereview.chromium.org/1483113002 .
Changed files

runtime/vm/dart_api_impl.cc
runtime/vm/dart_api_impl_test.cc
runtime/vm/os_thread.cc
runtime/vm/os_thread.h
Change #43223

Changed by	alanknight@google.com
Changed at	Tue 01 Dec 2015 11:10:23
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	bfd0efa95514351162d03131cc91f89ef8171ff3
Comments

Suppress more flaky co19 tests due to spawn semantics changes
BUG=

Review URL: https://codereview.chromium.org/1490863002 .
Changed files

tests/co19/co19-dartium.status

**Comment by alan-knight** [comment]
Currently either passes, crashes, or runtime errors on bots. Skipping in https://codereview.chromium.org/1797013002

**Comment by terrylucas** [comment]
Test is gone.
