### ISSUE TITLE
Implement configuration specific imports in the analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24579]
This is the analyzer specific issue for #24581. That issue has the details.

**Comment by danrubel** [comment]
DEP committee notes on [configuration specific imports](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Meetings/2015-10-14%20DEP%20Committee%20Meeting.md#config-specific-code)

**Comment by floitschG** [comment]
Available now through the options file.
See e17f2b98cf7fb4f9679ed0a2e65c288b9344e8f6
