### ISSUE TITLE
documentation for parameters

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24588]
Atom seems to be able to give documentation for parameters:

![image](https://cloud.githubusercontent.com/assets/1035299/10485477/b27ffd0a-728a-11e5-99db-335050de5493.png)

But there doesn't seem to be a way to documentate parameters. Would it may be an idea to put the documentation of the associated field there?

**Comment by sethladd** [comment]
cc @devoncarew Is this an issue with Atom, or Atom's use of Analysis Server?

**Comment by kasperpeulen** [comment]
Oh actually, it *is* possible to provide documentation for parameters, my bad.

![image](https://cloud.githubusercontent.com/assets/1035299/10491722/5ad54e34-72a8-11e5-8397-28a69f73a5bf.png)

It basicly searches for the documentation of the constructor/function/method, which seems reasonable. Closing this.

**Comment by devoncarew** [comment]
I think in this case that the parameter is not doc'd, but the field is. That use in the ctor is a shorthand for an assignment from the param to the field.

**Comment by devoncarew** [comment]
But yeah, what @kasperpeulen said, this is confusing UX w/ the difference between a doc'd field and param.

**Comment by kasperpeulen** [comment]
![image](https://cloud.githubusercontent.com/assets/1035299/23326722/21bc4138-fb01-11e6-9812-6de6a2f80352.png)

it actually works now like I suggested :) 👍
