### ISSUE TITLE
Set predefined environment variables for existing libraries in the VM

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24587]
See issue #24581.

Not clear, if we want to expose these behind the flag, or not.

**Comment by lrhn** [comment]
It's not clear what happens if the user adds `-Ddart.library.io=false` on the command line.
Should it override the default, not override the default or cause an error?

**Comment by floitschG** [comment]
Explicitly provided flags should override the automatically provided ones.

**Comment by floitschG** [comment]
Fixed with 55630a5e901edcafbaf4fa4971d6e4508358093d
