### ISSUE TITLE
js_dart_to_string_test fails on Dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24584]
The test
html/js_dart_to_string_test is failing with a RuntimeError on Dartium and drt (content shell).

The failure is:
FAIL
1	FAIL	
Expectation: toString custom dart .

Expected: '#fooBar#'
  Actual: '[object DartObject]'
   Which: is different.
Expected: #fooBar#
  Actual: [object Da ...
          ^
 Differ at offset 0
package:unittest/src/simple_configuration.dart 128:34                         SimpleConfiguration.onExpectFailure
package:unittest/src/simple_configuration.dart 24:13                          _ExpectFailureHandler.fail
package:unittest/src/matcher/expect.dart 121:5                                DefaultFailureHandler.failMatch
package:unittest/src/matcher/expect.dart 95:20                                expect
http://127.0.0.1:34265/root_dart/tests/html/js_dart_to_string_test.dart 42:7  main.<fn>.<fn>
package:unittest/src/internal_test_case.dart 120:37                           InternalTestCase.run.<fn>
dart:async/zone.dart 914                                                      _rootRunUnary

**Comment by whesse** [comment]
I guess this was fixed?  There was no message with the closing, or CL reference, but I see it has been removed from the status file.

**Comment by terrylucas** [comment]
The change was in third_party/WebKit I suspect that's why it wasn't
mentioned.
