### ISSUE TITLE
Dartium tests failing with JSObjectImpl where window or document expected.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24585]
The test
co19/LibTest/html/Window/document_A01_t01 
is failing with
 Exception: type 'JsObjectImpl' is not a subtype of type 'Document' of 'function result'.
in checked mode, and 
 Exception: NoSuchMethodError: method not found: 'window'
                    Receiver: Instance of 'JsObjectImpl'
in unchecked mode.

The test
co19/WebPlatformTest/html/browsers/browsing-the-web/read-text/load-text-plain_t01
is failing in checked mode with
 Uncaught Unhandled exception:
                    type 'JsObjectImpl' is not a subtype of type 'Document' of 'function result'.

The test
co19/LibTest/html/Window/requestFileSystem_A02_t01
is timing out in checked mode.

**Comment by alan-knight** [comment]
The second one passes now. The other two are both the same symptom. The result of window.open is a window from another frame, so we don't attempt to wrap it and just return the JsObject.  +jacob314

**Comment by terrylucas** [comment]
Fails on all platforms dart2js and dartium.
