### ISSUE TITLE
'pub serve' fails when pubspec.lock has changed

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#24589]
When the pubspec.lock file changes, 'pub serve' fails:

```
The pubspec.lock file has changed since the .packages file was generated, please run "pub get" aga
in.
```

This requires users to run `pub get` and then `pub serve` again.  A workaround is to alias `pub get && pub serve` to `pub serve`

Is this intentional?

**Comment by zoechi** [comment]
This is intentional to not run `pub serve` on outdated dependencies. There was a change recently that this message is only shown when actually dependencies (or version constraints)  were changed but not for transformer config or similar unrelated changes.

**Comment by johnpryan** [comment]
I agree running `pub serve` on outdated dependencies is bad, but is there a reason pub wouldn't attempt to update the dependencies automatically anymore?

**Comment by zoechi** [comment]
I haven't seen doing it in the past. 
This issue should be moved to the pub repository.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1343
