### ISSUE TITLE
Uri.removeFragment() corrupts URIs

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24593]
If I run `Uri.parse("foo:bar#baz").removeFragment().toString()`, I get `"foo://:0bar?"`, where I'd just expect `"foo:bar"`. This is particularly problematic for working with `data:` URIs, which aren't at all structured like typical hierarchical URIs and whose [fragments must be ignored](https://simonsapin.github.io/data-urls/).

**Comment by lrhn** [comment]
Fixed.
