### ISSUE TITLE
VM: Enum.values has wrong type argument, should be const

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24594]
enum E { A }

main() {
  print(identical(const <E>[E.A], E.values));  // Should print true.
}

Causes tree-shaking to produce an incorrect result for

print(E.values.join());

when there are no others references to members of E. Namely,

Instance of 'E' (Object.toString) instead of E.A (E.toString)

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
647ada25ed6f6ec745fd5e5885cbeb53c3741b1c (presubmit successful).
