### ISSUE TITLE
no static warning if redirecting factory constructor doesn't have type parameters

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#24592]
Not sure if this is a spec issue, an analyzer issue, or working as intended. But the Dart Analyzer finds no problems with this code:

``` dart
abstract class Equality<E> {
  const factory Equality() = DefaultEquality; // No warning here
  // ...
}
// ... even though we have no type parameters here:
class DefaultEquality implements Equality {
  // ...
}
```

from: https://github.com/dart-lang/collection/blob/5ab8354b59adae6c2ec1ee232274674f1850aa64/lib/equality.dart#L18

The spec does say:

> It is a static type warning if any of the type arguments to `k'` are not subtypes
> of the bounds of the corresponding formal type parameters of `type`.

It sort of implies that `type` should have formal type parameters, but it doesn't explicitly state that.

a couple of previous related issues: https://github.com/dart-lang/sdk/issues/7278, https://github.com/dart-lang/sdk/issues/13345

**Comment by bwilkerson** [comment]
Is there an implication that the number of type parameters must be equal?

**Comment by lrhn** [comment]
Type parameters of redirecting factory constructors are not forwarded automatically. You have to write them (which also means that you are allowed to write different ones than the ones on the superclass).
