### ISSUE TITLE
standalone/io/process_sync_test timing out frequently on Win debug-ia32

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24596]
It takes >2min on Windows debug mode. Could we reduce the size/number of iterations in this test to avoid these timeouts and reduce buildbot cycle time, @sgjesse ?

**Comment by fsc8000** [comment]
https://codereview.chromium.org/1402123004/ reduces running time of this test on my machine from 12s to 9s.

**Comment by whesse** [comment]
The running time of this test, when it passes, is quite stable, at around 16 seconds.  I think the failures are due to the test hanging, not due to it being slow.  So speeding up the test will not necessarily solve the problem.

**Comment by fsc8000** [comment]
I think you're right - these timeouts are likely due to a crash, and the test hanging afterwards. There are more examples of this - e.g. tests expected to crash are frequently timing out on Windows.

**Comment by fsc8000** [comment]
@zanderso Just stumbled over this: You recently fixed Windows-related hanging issues. Could these tests be related?

**Comment by zanderso** [comment]
If you just hit a hang on bleeding edge, then it is probably unrelated. The bug I fixed could have caused hangs in a wide variety of situations, so if you don't have the fix, then it could be related.

**Comment by fsc8000** [comment]
Maybe we should remove them from the status file to test if they still time out.

**Comment by a-siva** [comment]
Checked the current test results page and this test appears to be green on all configurations. Closing this issue.
