### ISSUE TITLE
analysis_getNavigation() handles offset and length arguments incorrectly

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24599]
According to `analysis_getNavigation()` [docs](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html): 
`If a navigation region overlaps (but extends either before or after) given region of the file it will be included in the result.`

I observe 3 kinds of problems with SDK 1.13.0-dev.7.0:
1. Regions that do not intersect with requested region are returned.
2. Region equal to the requested is not returned.
3. Region that intersects is not returned.

Below are proving screenshots. Red-underlined are offset and length passed to `analysis_getNavigation()`. You can see that results do not match requested region. All screenshots correspond to a file with content
```
import 'src/bar.dart';

import "package:foo/lib.dart";

main() {
  inBar;
  inLib;
}
```
![image](https://cloud.githubusercontent.com/assets/4499789/10518958/4b6636ba-736c-11e5-821e-402ce546525b.png)
![image](https://cloud.githubusercontent.com/assets/4499789/10519019/82c829f6-736c-11e5-8135-4117001e03ba.png)
![image](https://cloud.githubusercontent.com/assets/4499789/10519394/29173b84-736e-11e5-9298-ea804a76897e.png)

**Comment by scheglov** [comment]
Started.
https://codereview.chromium.org/1405033002

It is OK for getNavigation() to return more information than requested.
But it is not OK to not provide enough information.

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/a30bcd7b97c5d4704b27c99ba9cf8d85b527bb83

**Comment by scheglov** [comment]
Merge request for 1.13
https://github.com/dart-lang/sdk/issues/24600
