### ISSUE TITLE
Analysis_server_test fails locally, but not on buildbot

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24597]
Running the test analysis_server/test/analysis_server_test locally consistently fails, but the test is not failing on the buildbot.  The error I get is

ERROR: AnalysisServerTest | test_no_duplicate_notifications
  Test failed: Caught The null object does not have a getter 'extensions'.
  
  NoSuchMethodError: method not found: 'extensions'
  Receiver: null
  Arguments: []
  dart:core-patch/object_patch.dart 42                       Object._noSuchMethod
  dart:core-patch/object_patch.dart 45                       Object.noSuchMethod
  package:analyzer/src/plugin/options_plugin.dart 26:38      OptionsPlugin.optionsProcessors
  package:analysis_server/src/context_manager.dart 497:43    ContextManagerImpl.processOptionsForContext
  package:analysis_server/src/context_manager.dart 881:5     ContextManagerImpl._createContext
  package:analysis_server/src/context_manager.dart 912:16    ContextManagerImpl._createContexts
  package:analysis_server/src/context_manager.dart 629:9     ContextManagerImpl.setRoots
  package:analysis_server/src/analysis_server.dart 951:22    AnalysisServer.setAnalysisRoots
  pkg/analysis_server/test/analysis_server_test.dart 329:12  AnalysisServerTest.test_no_duplicate_notifications.<async>
  dart:async/future.dart 144                                 Future.Future.microtask.<fn>

**Comment by stereotype441** [comment]
Actually it was failing on the buildbots too.  See for example http://build.chromium.org/p/client.dart/builders/pkg-linux-be/builds/1263/steps/pkg%20tests%20failures/logs/stdio

Fixed by 395b82c041466763e9b738000586e91f389edc99
