### ISSUE TITLE
jsinterop: js_typed_interop_test/closure fails in checked mode with dart2js

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24608]
This fails on all browsers, and is not run on non-browsers.  Error is

FAIL
8	ERROR	
Expectation: closure call from js .

Test failed: Caught type 'JavaScriptFunction' is not a subtype of type 'Function'
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 3078:17   dart.wrapException
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 3548:15   dart.propertyTypeError
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 3559:9    dart.interceptedTypeCheck
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 16429:18  dart.allowInterop
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 17530:33  main__closure3.dart.main__closure3.call$0
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 19506:35  InternalTestCase.dart.InternalTestCase._testFunction$0
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 19545:25  InternalTestCase_run_closure0.dart.InternalTestCase_run_closure0.call$1
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 6409:18   dart._rootRunUnary
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 8113:137  _CustomZone.dart._CustomZone.runUnary$2
http://127.0.0.1:51234/root_build/generated_compilations/dart2js-checked/tests_html_js_typed_interop_test/test.js 7044:80   _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0

**Comment by whesse** [comment]
Failure is suppressed in html/html.status

**Comment by sigmundch** [comment]
Jacob - I assume you'll be more familiar with this. Could you take a look?

**Comment by jacob314** [comment]
Out for review. 
https://codereview.chromium.org/1416803002/

**Comment by jacob314** [comment]
Fixed.  Once the build is green, I'll send out a cherry-pick request for 1.3

**Comment by mit-mit** [comment]
Closing as Bill merged #24656
