### ISSUE TITLE
"not a subtype" exceptions should include qualified type names

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#24606]
We are currently looking at an exception:

```
EXCEPTION: type 'GtItemListExampleComponentApi' is not a subtype of type 'GtItemListExampleComponentApi' of 'context'.
```

where the two types have the same name, but they are defined in two different libraries. But omitting the library names in the error, we do not know which libraries these types are coming from or which type should be the subtype of the other.

**Comment by mraleph** [comment]
This was fixed.

**Comment by jbdeboer** [comment]
Thank you. As always, it is an honour to see your work.

**Comment by mraleph** [comment]
@jbdeboer it was fixed probably several years ago, we are just going through an issue cleanup :)
