### ISSUE TITLE
Task model has consistency and performance issues

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24601]
The test for this is here: https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/test/src/task/dart_test.dart#L1915

**Comment by bwilkerson** [comment]
These at least partially solve the problem:

https://codereview.chromium.org/1403003002/
https://codereview.chromium.org/1409813002/

Further testing needed.

**Comment by mit-mit** [comment]
Any news? Shall we get these cherry picked?

**Comment by bwilkerson** [comment]
They have been cherry picked. Waiting for feedback to know whether they have solved the problem or whether there is more work to be done.

**Comment by mit-mit** [comment]
@scheglov, did we conclude if this is fixed?

**Comment by bwilkerson** [comment]
No, we haven't really concluded anything. I believe that the specific problem that prompted this issue to be opened has been fixed, but this issue has sort of become a more general "task model is not ready to ship" marker issue. I'll update the title to reflect that.

**Comment by bwilkerson** [comment]
I believe that this is now fixed. We are no longer seeing the problems we were having before.
