### ISSUE TITLE
some tests fail with type-inference disabled

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24604]
These language tests fail if we disable type-inference:

```
language/assert_assignable_type_test
language/method_override4_test
language/classes_static_method_clash_test
language/cyclic_default_values_test
language/many_named_arguments_test
```

**Comment by askeksa-google** [comment]
Since type inference is an integral part of a Dart 2 implementation, this doesn't seem relevant any more.

**Comment by sigmundch** [comment]
Thanks @askeksa-google  - I should clarify however that if you see bugs in dart2js mentioning 'type-inferenece' then it likely means something else: in dart2js we have a whole program type propagation analysis that we named type-inference long before Dart2 and user-type inference was added to the language.

I'm ok closing this bug though, just for different reasons :). We plan to add a bot to test things with many dart2js passes disabled, and we'll track status using the .status files, not individual issues.

**Comment by askeksa-google** [comment]
Thanks for the clarification.
