### ISSUE TITLE
Closurizations of the constructor (named or anonymous) are not equal

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24607]
According to specification (3-rd edition, June 2015) "16.18.8 Named Constructor Closurization"
"Except that iff identical(T1 , T2 ) then new T1#m == new T2 #m."

But in fact:

``` dart
class C {
  C.m() {
  }
}

main() {
  print(identical(C, C)); // prints true
  print(new C#m == new C#m); // prints false
}
```

The same issue exists for anonymous constructors too.

``` dart
class C {
  C() {
  }
}

main() {
  print(new C# == new C#); // prints false
}
```

Tested on Dart VM version: 1.13.0-dev.6.0 (Wed Oct  7 08:09:59 2015) on "linux_x64"

**Comment by sgrekhov** [comment]
The same issue exists for anonymous constructors too.
```dart
class C {
  C() {
  }
}

main() {
  print(new C# == new C#); // prints false
}
```

**Comment by fsc8000** [comment]
Do you have a corresponding co19 test?

**Comment by sgrekhov** [comment]
I've added them recently. Please see

https://github.com/dart-lang/co19/blob/master/Language/Expressions/Property_Extraction/Named_Constructor_Closurization/identical_t01.dart
https://github.com/dart-lang/co19/blob/master/Language/Expressions/Property_Extraction/Anonymous_Constructor_Closurization/identical_t01.dart

**Comment by mhausner** [comment]
This is a known limitation of the current implementation.

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.

**Comment by mhausner** [comment]
Bugs that fix themselves are my favorite ones.

**Comment by munificent** [comment]
Mine too! :D
