### ISSUE TITLE
Analysis Server runs 'pub list-package-dirs' too many times (malformed pubspecs)

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24614]
(SDK 1.13-dev.7.0)
- Checkout project https://github.com/MikeMitterer/dart-material-design-lite. It contains 62 pubspec.yaml files of which 54 are valid and 8 are invalid (they are templates with placeholders).
- Open this project in the IDE. Analysis Server reports that it runs 'pub list-package-dirs' 62 times which is fine. Server warm up takes just 47 seconds (I guess no 3rd party packages analysis because no pub get done).
- Now run 'pub get' for all valid pubspecs (recommended to do it from the IDE)
- Close and reopen IDE

At this moment server says that  'pub list-package-dirs' was already started **more than 2000 times** and it already took 15 minutes. I'm killing the process as I can't wait more.

Note that if I delete malformed pubspecs from the project and restart the IDE it helps a bit. Analysis Server runs pub list 150 times in this case (still more than 54 - amount of pubspecs left) and server warms up in 4 minutes.

**Comment by sethladd** [comment]
Do we have a Milestone for this?

cc @kevmoo

**Comment by scheglov** [comment]
https://codereview.chromium.org/1415713002

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/efc1d4b224821d4cbc64796c0348a6f019fa0649

**Comment by scheglov** [comment]
Merge request.
https://github.com/dart-lang/sdk/issues/24628
