### ISSUE TITLE
Validation and error-reporting for `.analysis_options` files

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#24618]
As the analyzer worklflow involves `.analysis_options` more and more (for excluding files from analysis, specifying and configuring plugins, etc.) we should provide them with error feedback on properties files.  As things stand, errors/warnings are either ignored entirely (in the case of options that are not processed by any processors) or logged (in the case of malformatted YAML).  Since no one knows where logs go, the second is effectively no better than the first.  To start, propagating minimal errors to the client for display in the editor/IDE would be a huge boon.  Down the road we can consider a richer experience (fixes and completions).

**Comment by pq** [comment]
Some progress.  All the plumbing is in place and some reporting is live.

Top-level options are currently validated:

![screen shot 2015-10-28 at 3 33 49 pm](https://cloud.githubusercontent.com/assets/67586/10805214/4eb56d82-7d89-11e5-8aea-4f9264ef977c.png)

And with https://codereview.chromium.org/1411053003/ error code validation is on the way:

![screen shot 2015-10-28 at 3 32 20 pm](https://cloud.githubusercontent.com/assets/67586/10805196/31ae40f6-7d89-11e5-83fe-0ce07f0408dc.png)

**Comment by sethladd** [comment]
This is very cool.

Since you have all these rules, or are building them out now, is our README updated and is this file's format documented?

**Comment by zoechi** [comment]
It's `.analysis_options` not `.analysis_preferences`?
I guess it's worth changing the title to not start confusion.

**Comment by sethladd** [comment]
Thanks :)

**Comment by pq** [comment]
@sethladd : no doc updates yet.  My thinking was to let this settle a bit and then do a bulk update (with an explanation of `language` configuration as well).  Maybe this is something we can get @Sfshaza  to help with?

**Comment by sethladd** [comment]
> My thinking was to let this settle a bit and then do a bulk update

Makes sense.

**Comment by pq** [comment]
First cut is done.  We can open fresh tracking bugs for things like completions and fixes as needed.
