### ISSUE TITLE
Analysis Server re-analyzes the same code multiple times if referenced from different packages

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24611]
I suspect that Analysis Server is analyzing the same files several times and keeps the same data in memory several times. I made the following experiment (SDK 1.13.0-dev.7.0):
**1.** Created a simple project with pubspec

```
name: project1

dependencies:
  angular2: any
```

and a single Dart file:

```
import "package:angular2/angular2.dart";
```

I ran `pub get` and opened the project in the IDE.
According to status reported by the Analysis Server initial analysis took 7.5s (pub list-package-dirs time not included). Analysis Server process consumes 240Mb RAM.

**2.** I closed the IDE and made 10 copies of this package in neighbor folders (and ran pub get for each). Thus I got a project that contains 10 equal `pubspec.yaml` files, 10 simple dart files, and each of these 10 project references the same bunch of 3rd party dependencies (angular2 package).

Initial analysis now took 25 seconds. Analysis Server process now consumes 720Mb RAM.

I may be wrong but general considerations make me think that analysis time and memory consumption should grow linearly (or less) as code base grows. In this case code base in experiments 1 and 2 is almost equal (I assume SDK and 3rd party packages included in code base), but analysis time and memory consumption differs 3x times.

This issue is to make sure that Analysis Server is not analyzing the same files several times and doesn't store the same data in memory several times.

**Comment by bwilkerson** [comment]
Analysis server absolutely re-analyzes code multiple times if it's referenced from multiple packages. This is, unfortunately, a long-standing known issue.

**Comment by devoncarew** [comment]
I believe this was addressed with the analysis driver re-write.
