### ISSUE TITLE
pub run test -p dartium looks for the `dartium` binary; the binary is actually named `chrome`

### ISSUE THREAD

**Issue by jirkadanek** [dart-lang/sdk#24616]
I'm running dart test using the `test` package..

    pub run test -p dartium

When I execute the command above, I get the following error.

    Failed to run Dartium: No such file or directory
        Command: dartium --user-data-dir=/tmp/dart_test_pLppGJ http://localhost:59531/nI6HuPYC2TYNlxlFC2UiMNf4eBs9I0iJ/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A59531%2FnI6HuPYC2TYNlxlFC2UiMNf4eBs9I0iJ%2F0 --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate.
    dart:isolate  _RawReceivePortImpl._handleMessage

I have both dartium and dart.sdk downloaded and in PATH.
The version is 1.13.0-dev.7.0 (Wed Oct 14 06:04:50 2015) on "linux_x64"

The same issue was discussed four months ago at https://stackoverflow.com/questions/30675583/failed-to-load-dartium-when-running-test
The solution described there, `ln -s chrome dartium` in the directory where I unpacked Dartium works for me.

I would expect pub run test to work without me having to create any symlinks.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/test#353
