### ISSUE TITLE
Analysis Serve is running 'pub list-package-dirs' for excluded packages

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24612]
I have a project with the following folder structure:
```
root
  - project1
  - project2
  - ...
  - project10
```
Each projectX has pubspec.yaml file, pub get is done, so .packages files are also there. But all projectX where X >= 2 are excluded.
IDE passes the following roots to the Analysis Server:
- Included root: `root`
- Excluded roots: `root/project2, root/project3, ..., root/project10`

But according to the status reported by the Analysis Server (SDK 1.13-dev.7.0) it runs 'pub list-package-dirs' for all 10 pubspec.yaml files.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1411393003

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/5e9ea82aa44b75b1084c6e8f45ae5a5e952ad368
