### ISSUE TITLE
Analysis Server doesn't release memory after project close

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24613]
- Open some large project in the IDE.
- Wait for Analysis Server to warm up, see how much memory is consumes using any Process Explorer.
- Close project. IDE sends empty root list to the Analysis Server via `analysis_setAnalysisRoots`.
After that I waited for several minutes, but Analysis Process still consumes several gigabytes of memory. (Windows 8.1, SDK 1.13-dev.7.0)

**Comment by scheglov** [comment]
I open the project with analyzer and analysis_server modules.
After analysis is done DAS "used" Old Generation is "595.4MB of 604.6MB".
I close project and "used" Old Generation is "82.6MB of 420.6MB".
When I repeat opening and closing the project I get similar number.

So, I guess DAS does release the memory, but VM still keeps some of it allocated.


@johnmccutchan @iposva-google Does VM release memory to OS when the application stops using so much memory?

**Comment by iposva-google** [comment]
In your example the VM released about 200MB back to the OS, but keeps some memory around expecting you to grow again. Which is what your get when you reopen a project again.

**Comment by scheglov** [comment]
@iposva-google  Yes, I see that it releases *some* memory. I'd like to understand it better - what is an approximate algorithm here? Does VM release memory up to some fixed size, like 400MB or up to some percentage of the max heap size, or...?

**Comment by scheglov** [comment]
I think we have found the/a reason why memory is not released after closing a big project.
This is especially true for projects with many legacy `packages/` folders.
https://codereview.chromium.org/1447603004

**Comment by scheglov** [comment]
I believe the issue was fixed.

**Comment by alexander-doroshko** [comment]
I played a bit with today's 1.14.0-edge.674a2f6d90ea063b13a33a74d7bb010f062ae8fe:
- Open big project. Memory consumed by the Analysis Server grows up to 3.45Gb
- Close project. Wait 10 minutes. Memory stays at 3.45Gb
- Open the same project again. Consumed memory drops to 1.1Gb and then grows to 3.65Gb
- Close project and wait. Memory stays at 3.65Gb
- Open the same project again. Memory drops to 1.5Gb and grows to 3.8Gb
- Close this big project and open toy size 1-file project. Memory stays at 3.8Gb.

**Comment by scheglov** [comment]
I would love to have / know this project for testing.

When I open the whole SDK repo, wait for analysis and close the project memory usage drops tenfold. But the allocated heap size does not. I opened a [new issue](https://github.com/dart-lang/sdk/issues/25178) against the VM.


![image](https://cloud.githubusercontent.com/assets/384794/11667212/407e6c96-9da5-11e5-9635-d331bd512db2.png)

**Comment by alexander-doroshko** [comment]
I checked memory using Sysinternals' Process Explorer. It shows allocated memory. I think if I looked at it using Observatory I would also see that 90% of allocated memory not used.
The project I played with consists of several [Mike's repositories](https://github.com/MikeMitterer), `pub get` done for all pubspecs: 
![image](https://cloud.githubusercontent.com/assets/4499789/11668857/6e8a5e8c-9e0a-11e5-9625-8b88b7bea75c.png)
.

**Comment by sircco** [comment]
Sent: {"id":"49","method":"analysis.getErrors","params":{"file":"\/home\/dart\/x\/lib\/c_wizard.dart"}}
this consumes around 100MB per file, 

also if you do this (notice same file name)
Sent: {"id":"50","method":"analysis.getErrors","params":{"file":"\/home\/dart\/x\/lib\/c_wizard.dart"}}
it will consume another 100-250MB

file is declaring a lib, creating object, nothing fancy
