### ISSUE TITLE
Specification: no definition for 'anonymous constructor'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24621]
Dart Language Specification (3-rd Edition, June 2015) contains "16.18.5 Anonymous Constructor Extraction" and "16.18.9 Anonymous Constructor Closurization" but no definition of what 'anonymous constructor' is. Specification should provide definition of 'anonymous constructor' to avoid ambiguity. For example:

``` dart
class A {
}
class C {
C() {}
}
```

Which of these classes has anonymous constructor? It's unclear from the current specification

**Comment by eernstg** [comment]
Said sections were removed when generalized tear-offs were taken out of the language and no such phrases are used at this point. Closing.
