### ISSUE TITLE
jsinterop: Rename "Js" class to "JS"

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#24624]
The current `Js` class name doesn't follow the style guide which states that two-letter acronyms should be left capitalized like `JS`.

**Comment by sigmundch** [comment]
@jacob314 submitted a fix in https://github.com/dart-lang/sdk/commit/be1fcb944176bed2bf1294c78cd39844df67dda6

@kevmoo do we need a cherry-pick request to make sure this makes it to the sable branch? We should wait for the bots to be happy before merging though.

**Comment by jacob314** [comment]
Once the bots are green we'll need to cherry pick this to the stable branch.

**Comment by mit-mit** [comment]
Closing as Bill merged #24641
