### ISSUE TITLE
Documenting the .analysis_options file

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24625]
Should we document the .analysis_options file ? Where would that document live?

cc @Sfshaza @kevmoo @pq

**Comment by sethladd** [comment]
Happy to help write something here, if you can recommend a place to put it. Since it appears to be a feature of the analyzer, shared by both the CLI and the server, one idea is to put it into the README of the analyzer package.

**Comment by pq** [comment]
:+1:  I think the `README` is a good place to start.

**Comment by bwilkerson** [comment]
While the documentation pages currently point people at the README for the command-line analyzer, that doesn't seem like a very intuitive place to find documentation for an editor/IDE. It would be nice if there could be a common place that made sense for all of these tools.

**Comment by sethladd** [comment]
Thanks @bwilkerson . We'll work to make this discoverable.

**Comment by sethladd** [comment]
for the docs:

Some example .analysis_options files

https://github.com/dart-lang/analyzer_cli/blob/master/.analysis_options
https://github.com/dart-lang/linter/blob/master/.analysis_options
https://github.com/dart-lang/dev_compiler/blob/master/.analysis_options

Strong-mode is set like this:

```
analyzer:
  strong-mode: true
```

Lint rules like so:

```
linter:
  rules:
    -camel_case_types
    # ….
```

**Comment by sethladd** [comment]
CL is out: https://codereview.chromium.org/1414133002/

**Comment by zoechi** [comment]
Seems `.analysis_options` file is loaded now in `Dart VM version: 1.13.0-edge.cc0a9c3e7eb32588c219f7f16a1a806e88a397d3 (Mon Oct 19 15:23:49 2015) on "linux_x64"`
I get strong mode warnings :smiley: in WebStorm Dart Analysis view.

Is there already a way to disable hints like "Unused import"? 

In Polymer projects I get flooded by "Unused import" because it uses lots of HTML-only imports and no way to silence them.

```dart
@HtmlImport('some_file.html') 
library some_library

import `package:polymer_elements:some_lib_with_other_html_import.dart`;

// no actual code
```

**Comment by zoechi** [comment]
Is there a way to ignore all html files in all subdirectories to work around dart-lang/sdk#24552

**Comment by bwilkerson** [comment]
> Is there already a way to disable hints like "Unused import"?

No, not yet.

> Is there a way to ignore all html files in all subdirectories ...

The 'exclude' option can take a glob pattern.

**Comment by jacehensley-wf** [comment]
It would also be nice to know what version of linter is being used, or let it be configurable.

**Comment by srawlins** [comment]
@Sfshaza can this be closed? Link?

**Comment by lrhn** [comment]
I wouldn't want this closed before there is documentation of *all* the options and how to write them.
Examples only work if the thing you want to do is in the example. I have so far been unable to write an analysis options file that enables any experimental feature. It's just not in the examples, and there is no documented reasoning that can be used to infer it.

**Comment by bwilkerson** [comment]
> I have so far been unable to write an analysis options file that enables any experimental feature.

I'm not surprised; it's not terribly intuitive.

There is, of course, the interesting issue here that experimental features tend to be fairly short lived. If we document them (and I'm not arguing that we shouldn't) we need to have a process in place to ensure that the docs get updated when they are added or removed (either because they're abandoned or because they are enabled by default).

Just to capture the information somewhere, you can enable experimental features by adding a "language" key under the top-level "analyzer" key, whose value is a map. The keys of the map are features and the values are bool's. The keys that are currently supported are "enableAssertInitializer", "enableInitializingFormalAccess", and "enableSuperMixins". So, for example, to allow super in mixins, you would add the following:
```
analyzer:
  language:
    enableSuperMixins: true
```
There are several features missing from this list that ought to be supported, but nobody seems to have noticed. Let me know if the feature you want isn't listed here and I'll be happy to add it.

**Comment by lrhn** [comment]
T

On Wed, Nov 23, 2016 at 5:53 PM, Brian Wilkerson <notifications@github.com>
wrote:

> I have so far been unable to write an analysis options file that enables
> any experimental feature.
>
> I'm not surprised; it's not terribly intuitive.
>
> There is, of course, the interesting issue here that experimental features
> tend to be fairly short lived. If we document them (and I'm not arguing
> that we shouldn't) we need to have a process in place to ensure that the
> docs get updated when they are added or removed (either because they're
> abandoned or because they are enabled by default).
>
I can see why documenting experimental features individually is a sisyphean
task, so if there is a structured way to go from the flag used by other
tools to an option entry, it would at least make it deducible. (Or just
also accept a command line flag like everybody else.)

Just to capture the information somewhere, you can enable experimental
> features by adding a "language" key under the top-level "analyzer" key,
> whose value is a map. The keys of the map are features and the values are
> bool's. The keys that are currently supported are
> "enableAssertInitializer", "enableInitializingFormalAccess", and
> "enableSuperMixins". So, for example, to allow super in mixins, you would
> add the following:
>
> analyzer:
>   language:
>     enableSuperMixins: true
>
> The experimental feature I'm looking for has flag --assert-message, so I
guess it'll be analyzer>language>enableAssertMessage: true.
I'll check it again when I get to the office, but I don't think it's
working.

> There are several features missing from this list that ought to be
> supported, but nobody seems to have noticed. Let me know if the feature you
> want isn't listed here and I'll be happy to add it.
>
The language tests sometimes have a flag, set in a comment like:

// SharedOptions=--assert-message

It would be great if this works for the analyzer as well, but I don't think
it does.

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by bwilkerson** [comment]
> The experimental feature I'm looking for has flag --assert-message, so I guess it'd be analyzer>language>enableAssertMessage: true. I'll check it again when I get to the office, but I don't think it's working.

Correct. As I mentioned, there are only three keys currently working: "enableAssertInitializer", "enableInitializingFormalAccess", and "enableSuperMixins". Unfortunately, the one you're looking for isn't currently supported.

> It would be better if this worked for the analyzer as well, but I don't think it does.

We do sometimes add flags to the command-line analyzer for such features, though looking at the code this particular flag does not appear to be supported.

**Comment by thosakwe** [comment]
+1 for being able to silence "Unused import"!!!

**Comment by zoechi** [comment]
@thosakwe have you tried

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_imports: ignore
```
https://www.dartlang.org/guides/language/analysis-options

**Comment by kevmoo** [comment]
This is fixed, right?

https://www.dartlang.org/guides/language/analysis-options
