### ISSUE TITLE
Rename the Dartium binary to `dartium`

### ISSUE THREAD

**Issue by jirkadanek** [dart-lang/sdk#24631]
The Dartium binary has been called by various names.
- Currently (1.13-dev) it is named `chrome`.
- The documentation at https://www.dartlang.org/tools/dartium/ refers to it as `Chromium`.

I encountered issues https://github.com/dart-lang/sdk/issues/24616, https://github.com/dart-lang/test/issues/353 and https://github.com/dart-lang/test/issues/63 that stem from the fact it is not possible to identify a Dartium binary by its name only. (When called `chrome` It may conflict with the Chrome browser, dtto for Chromium).

I suggest that the binary be renamed to `dartium` (or `dartium.exe` or `dartium.app`, depending on the platform) to resolve the ambiguity. This would allow users to have both Chrome and Dartium in PATH and know which is being executed.

**Comment by kasperpeulen** [comment]
The binary is for me called `dartium` actually. I'm using 1.13-dev.

**Comment by jirkadanek** [comment]
Not for me:

    [jirka@arch Downloads]$ ls
    [jirka@arch Downloads]$ wget "https://storage.googleapis.com/dart-archive/channels/dev/release/1.13.0-dev.7.0/dartium/dartium-linux-x64-release.zip"
    --2015-10-20 00:20:29--  https://storage.googleapis.com/dart-archive/channels/dev/release/1.13.0-dev.7.0/dartium/dartium-linux-x64-release.zip
    Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.211.48, 2a00:1450:4016:805::2010
    Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.211.48|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 77370942 (74M) [application/zip]
    Saving to: ‘dartium-linux-x64-release.zip’

...

    [jirka@arch Downloads]$ unzip dartium-linux-x64-release.zip 
    Archive:  dartium-linux-x64-release.zip
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/pnacl/
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/pnacl/pnacl_public_x86_64_libcrt_platform_a  

...

    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/pnacl/pnacl_public_x86_64_crtbegin_o  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/xdg-settings  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/libpdf.so  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/chrome_100_percent.pak  
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/lib/
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/chrome-wrapper                 <========= HERE =====
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/chrome.1  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/nacl_helper_bootstrap  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/nacl_irt_x86_64.nexe  
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/cs.pak  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/vi.pak  

...

    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/es-419.pak  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/nb.pak  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/es.pak  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/locales/fa.pak  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/chrome                         <========= HERE =====
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/nacl_helper  
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/
    creating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/inspector/
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/inspector/source_frame.js  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/inspector/devtools_extension_api.js  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/inspector/heap_snapshot_worker.js  
    inflating: dartium-lucid64-full-dev-1.13.0-dev.7.0.0/resources/inspector/devices.js

...

    [jirka@arch Downloads]$ find -name dartium
    [jirka@arch Downloads]$ find -name chrome
    ./dartium-lucid64-full-dev-1.13.0-dev.7.0.0/chrome
    [jirka@arch Downloads]$

**Comment by zoechi** [comment]
@kasperpeulen maybe homebrew added a symlink for you?
```bash
myname@myhost ~
 (master) $ dart --version
Dart VM version: 1.13.0-edge.cc0a9c3e7eb32588c219f7f16a1a806e88a397d3 (Mon Oct 19 15:23:49 2015) on "linux_x64"
myname@myhost ~
 (master) $ which dartium
/usr/bin/dartium
myname@myhost ~
 (master) $ ls -la /usr/bin/dartium
lrwxrwxrwx 1 root root 35 Mai 24 19:55 /usr/bin/dartium -> /usr/local/apps/dart/dartium/chrome
```

**Comment by whesse** [comment]
This sounds like a good idea.

@ricowind @sgjesse @iposva-google
