### ISSUE TITLE
HttpRequest.open() uses the "async" keyword

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#24637]
[HttpRequest.open()](https://api.dartlang.org/1.12.1/dart-html/HttpRequest/open.html) can't be used in an async function:

```
[error] The keywords 'async', 'await', and 'yield' may not be used as identifiers in an asynchronous or generator function.
```

It would be nice if this were called something else, but it might cause confusion, since javascript documentation on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open%28%29) calls the parameter "async."

**Comment by lrhn** [comment]
@gbracha 
This is problematic! I'm fine with not allowing you to introduce or use a variable named "async", but it's highly disruptive to not be able to pass a named parameter named "async" to an unrelated function.
We may want to consider fixing the specification to allow this use.
The identifier "async" doesn't have any special meaning inside an async function anyway, so it's only restricted to avoid confusion, which suggests that there won't be any conflict with loosening that restriction.

**Comment by lrhn** [comment]
The specification now states that `async` is not a keyword, not even in an `async` function.

**Comment by natebosch** [comment]
For future visitors, the first version of the SDK where the analyzer doesn't complain about this is `2.4.0`
