### ISSUE TITLE
Exception in completion

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24630]
I was typing this and attempt to complete.
Approximately.

  SearchDomainHandler(AnalysisServer server) : server = server, searchEngine = server.sea^ {
    searchEngine = server.searchEngine;
  }

Dart analysis server, SDK version 1.13.0-edge.e0636b183c4ab2a87b2d93198105c1413e3ea4d8, server version 1.12.0, FATAL error: The null object does not have a getter 'library'.

NoSuchMethodError: method not found: 'library'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      InterfaceTypeSuggestionBuilder.suggestionsFor (package:analysis_server/src/services/completion/suggestion_builder.dart:439:54)
#3      _PrefixedIdentifierSuggestionBuilder.computeFull (package:analysis_server/src/services/completion/prefixed_element_contributor.dart:364:44)
#4      PrefixedElementContributor.computeFull (package:analysis_server/src/services/completion/prefixed_element_contributor.dart:47:22)
#5      DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:222:15)
#6      CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165:17)
#7      DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:221:23)
#8      List.forEach (dart:core-patch/growable_array.dart:233)
#9      DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:217:14)
#10     CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165:17)
#11     DartCompletionManager.computeFull.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:211:19)
#12     _rootRunUnary (dart:async/zone.dart:914)
#13     _CustomZone.runUnary (dart:async/zone.dart:810)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#16     _Future._completeWithValue (dart:async/future_impl.dart:376)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#18     _rootRun (dart:async/zone.dart:907)
#19     _CustomZone.run (dart:async/zone.dart:802)
#20     _CustomZone.runGuarded (dart:async/zone.dart:708)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#23     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:192)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)

**Comment by danrubel** [comment]
I cannot reproduce this. I'm lowering the priority for now until we get a consistent bead on this problem.

**Comment by danrubel** [comment]
Sorry for the delay. I was trying to find a way to repro this exception, but could not. This should keep it from occurring... https://codereview.chromium.org/1418093003/
