### ISSUE TITLE
Dart Analyzer: warn about extra "awaits"

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#24634]
Should the analyzer warn about awaits on non-future data types? Example:
- `var a = await 5;`
- `var b = await foo.allwaysReturnsString():`

**Comment by zoechi** [comment]
I think this is a dup of #24533

**Comment by floitschG** [comment]
Not sure this is a dupe. I assume the hint should be inside an async function.

awaiting on a non-future is legal. It might still be interesting to provide a hint.

**Comment by srawlins** [comment]
Awaiting on a non-Future _is_ legal, because a function declared to return a Future might _not_ return a Future at runtime, and that shouldn't blow up await.

However, there is no reason to ever `await 5` or `await returnsAString()` where `returnsAString()` is declared to return a String, right?

**Comment by goderbauer** [comment]
I don't think it is a dupe. I do understand that it's perfectly legal to have an await in these situations. However, I also think that the analyzer should provide you with a hint if the await is unnecessary.

**Comment by srawlins** [comment]
Would this be accepted as a HINT in the analyzer?

**Comment by bwilkerson** [comment]
How many false positives would a rule like this tend to produce? IMO, if there are enough (any?) then it should be a lint rather than a hint.

**Comment by srawlins** [comment]
This has been implemented as a linter rule. [await_only_futures](http://dart-lang.github.io/linter/lints/await_only_futures.html).
