### ISSUE TITLE
Migrate completion to new plugin API

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24647]

**Comment by danrubel** [comment]
First [cut](https://codereview.chromium.org/1407273004/) ... to be revised.
[Small step](https://codereview.chromium.org/1414193003/) towards completion on new task model with new plugin API.

**Comment by bwilkerson** [comment]
@danrubel How is the going? Have we finished the migration?

**Comment by danrubel** [comment]
It is complete except for [suggesting identifiers that are not yet imported](https://github.com/dart-lang/sdk/issues/25820).
