### ISSUE TITLE
Hint when noSuchMethod only invokes a noSuchMethod inherited from somewhere other than Object

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24648]
Given code like:

    class B extends A {
      noSuchMethod(x) => super.noSuchMethod(x);
    }

Produce a hint that the method can be removed as long as the noSuchMethod on the right-hand side is not referring to the one inherited from Object.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1506903005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/1b0a5c313f94620289db6a1b3328d3b3399fc57d
