### ISSUE TITLE
service protocol not including the type field for BoundVariables

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24654]
In the fragment below:

```json
        "vars": [
          {
            "name": "args",
            "value": {
              "type": "@Instance",
              "_vmType": "Array",
              "class": {
                "type": "@Class",
                "fixedId": true,
                "id": "classes\/62",
                "name": "_List",
                "_vmName": "_List@915557746"
              },
              "kind": "List",
              "id": "objects\/0",
              "length": 0
            },
            "_tokenPos": 12,
            "_endTokenPos": 169
          },
          {
            "name": "abc",
            "value": {
              "type": "@Instance",
              "_vmType": "String",
              "class": {
                "type": "@Class",
                "fixedId": true,
                "id": "classes\/65",
                "name": "_OneByteString",
                "_vmName": "_OneByteString@915557746"
              },
              "kind": "String",
              "id": "objects\/1",
              "valueAsString": "abd_def"
            },
            "_tokenPos": 20,
            "_endTokenPos": 169
          },

```

There's no `type` field for the instances of `BoundVariable`. This is for the bound variables off the `vars` field of `Frame`.

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by johnmccutchan** [comment]
Similarly- BoundedField isn't emitted.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1420633003/

**Comment by turnidge** [comment]
BoundVariable and BoundField do not extend Response.  There is no requirement for them to have a "type" field.

**Comment by devoncarew** [comment]
Cool. It should be noted that the tree of objects returned from the service protocol can be parsed w/o knowing the context (i.e, you don't have to know that the `Frame.vars` field is a list of `BoundVariable`), except for these two cases (BoundVariable and BoundField). It might be useful for them to define a `type` field even if they don't extend Response, just for completeness.

I can easily switch back to parsing w/o the `type` info however. If you decide to change it back please ping this bug, so I can update.

**Comment by johnmccutchan** [comment]
We've included the types for awhile now. I think this issue can be closed.
