### ISSUE TITLE
100% CPU spike in analyzer

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24655]
Vague tracking bug for Analysis Server 100% CPU spike.

**Comment by kevmoo** [comment]
Update: @danrubel is investigating

**Comment by bwilkerson** [comment]
Any update on this issue? Are we still seeing the problem? Do we have any idea what's causing it?

**Comment by bwilkerson** [comment]
Also, is this still on track for 1.13? (It's currently blocking https://github.com/dart-lang/sdk/issues/24690 from being closed.)

**Comment by danrubel** [comment]
This is really a duplicate/meta of other bugs such as https://github.com/dart-lang/sdk/issues/24601. I believe this issue has been addressed. Closing.
