### ISSUE TITLE
Redirecting factory constructor to itself produces compile-time error 

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#24665]
According to specification (3-rd edition, June 2015) "10.6.2 Factories":
"It is a run-time error if a redirecting factory constructor redirects to itself,
either directly or indirectly via a sequence of redirections."
However the test

``` dart
class F {
  factory F() = F;
}
main() {
  new F();
}
```

reports compile-time error.

``` dart
dart test.dart 
'file:test.dart': error: line 2 pos 3: factory 'F.' illegally redirects to itself
  factory F() = F;
  ^
```

Tested on Dart VM version: 1.13.0-dev.6.0 (Wed Oct 7 08:09:59 2015) on "linux_x64".

**Comment by askeksa-google** [comment]
The spec is incorrect here. See https://github.com/dart-lang/sdk/issues/33649
