### ISSUE TITLE
Pub: Does not support a "version:" attribute

### ISSUE THREAD

**Issue by Gen8** [dart-lang/sdk#24662]
Content of the pub file:
name: section
version: 2015.10.20
dependencies:
  test:
    version: ">=0.0.0"

The problem is the "version:" attribute.
Correct is: text: ">=0.0.0"

I send a bug report because it was suggested by pub:
This is an unexpected error. Please run

    pub --trace upgrade --no-package-symlinks

and include the results in a bug report on http://dartbug.com/new.

The output of pub --trace upgrade --no-package-symlinks where I have replaced the path of my local file with XXX.

Resolving dependencies...
Bad state: No element
dart:core                                            List.single
package:pub/src/pubspec.dart 468                     Pubspec._parseDependencies.<fn>
dart:collection                                      _HashMap.forEach
package:collection/wrappers.dart 336                 DelegatingMap.forEach
package:pub/src/pubspec.dart 434                     Pubspec._parseDependencies
package:pub/src/pubspec.dart 98                      Pubspec.dependencies
package:pub/src/package.dart 53                      Package.dependencies
package:pub/src/solver/backtracking_solver.dart 613  BacktrackingSolver._logParameters
package:pub/src/solver/backtracking_solver.dart 143  BacktrackingSolver.solve.<async>
===== asynchronous gap ===========================
dart:async                                           _Completer.completeError
package:pub/src/solver/backtracking_solver.dart 188  BacktrackingSolver.solve.<async>
===== asynchronous gap ===========================
dart:async                                           Future.Future.microtask
package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
package:pub/src/log.dart 393                         progress
package:pub/src/solver/version_solver.dart 38        resolveVersions
package:pub/src/entrypoint.dart 152                  Entrypoint.acquireDependencies.<async>
===== asynchronous gap ===========================
dart:async                                           Future.Future.microtask
package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
package:pub/src/command/upgrade.dart 34              UpgradeCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                           Future.Future.microtask
package:pub/src/command/upgrade.dart                 UpgradeCommand.run
package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
dart:async                                           Future.Future.sync
package:args/command_runner.dart 131                 CommandRunner.runCommand
package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
dart:async                                           Future.Future.sync
package:pub/src/utils.dart 103                       captureErrors.<fn>
package:stack_trace                                  Chain.capture
package:pub/src/utils.dart 117                       captureErrors
package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>
---- Log transcript ----
FINE: Pub 1.13.0-dev.7.1
IO  : Spawning "cmd /c ver" in XXX
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.10240]
    | Nothing output on stderr.
MSG : Resolving dependencies...
FINE: Resolving dependencies finished (0.0s).
ERR : Bad state: No element
FINE: Exception type: StateError
ERR : dart:core                                            List.single
    | package:pub/src/pubspec.dart 468                     Pubspec._parseDependencies.<fn>
    | dart:collection                                      _HashMap.forEach
    | package:collection/wrappers.dart 336                 DelegatingMap.forEach
    | package:pub/src/pubspec.dart 434                     Pubspec._parseDependencies
    | package:pub/src/pubspec.dart 98                      Pubspec.dependencies
    | package:pub/src/package.dart 53                      Package.dependencies
    | package:pub/src/solver/backtracking_solver.dart 613  BacktrackingSolver._logParameters
    | package:pub/src/solver/backtracking_solver.dart 143  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _Completer.completeError
    | package:pub/src/solver/backtracking_solver.dart 188  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
    | package:pub/src/log.dart 393                         progress
    | package:pub/src/solver/version_solver.dart 38        resolveVersions
    | package:pub/src/entrypoint.dart 152                  Entrypoint.acquireDependencies.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
    | package:pub/src/command/upgrade.dart 34              UpgradeCommand.run.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/command/upgrade.dart                 UpgradeCommand.run
    | package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
    | dart:async                                           Future.Future.sync
    | package:args/command_runner.dart 131                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/utils.dart 103                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 117                       captureErrors
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>
---- End log transcript ----

**Comment by zoechi** [comment]
`2015.10.20` isn't a valid pub version
https://www.dartlang.org/tools/pub/versioning.html

**Comment by madsager** [comment]
This issue was moved to dart-lang/pub#1348
