### ISSUE TITLE
Pub: Expected a key while parsing a block mapping. path:

### ISSUE THREAD

**Issue by Gen8** [dart-lang/sdk#24663]
My pubspec.yaml contains this:
name: Name1
version: 2015.10.20
dependencies:
  test: ">=0.0.0"
  Name2: ">=0.0.0"
    path: ../Name2-2015-10-21

And I get this error:
Error on line 6, column 5 of pubspec.yaml: Expected a key while parsing a block mapping.
    path: ../tenum-2015-09-28
    ^

I get no error if I remove the version constraint for the Name2 package:
name: Name1
version: 2015.10.20
dependencies:
  test: ">=0.0.0"
  Name2:
    path: ../Name2-2015-10-21

**Comment by zoechi** [comment]
Can you please enclose the yaml content in triple-backticks (``` ` ```). Formatting matters for yaml.
You can't have a path **and** a version constraint.

**Comment by madsager** [comment]
This issue was moved to dart-lang/pub#1347

**Comment by sovoereign** [comment]
please find a solution here [Flutter Pub: Expected a key while parsing a block mapping. path:
](url)

**Comment by zoechi** [comment]
@sovoereign that link doesn't point anywhere useful

**Comment by patelkrunal78** [comment]
Spaces are significant in YAML

assets is indented too far

You Can Find Your Solution at [Here](https://icetutor.com/question/flutter-pub-expected-a-key-while-parsing-a-block-mapping-path-2)
