### ISSUE TITLE
Specification: wrong definition of super closurization equality

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24661]
Dart Language Specification (3-rd Edition / June 2015) reads (16.18.10 Super Closurization):
"Except that iff two closurizations were created by code declared in the same class with identical bindings of this then super1#m == super2#m, super1.m == super2.m, super1#m == super2.m and super1.m == super2#m."
First, it is unclear what "...with identical bindings..." means. Specification should be more clear on that.
Second, consider the following program:

``` dart
class A {
  int m() => 1;
}

class B extends A {
  getClosurization() {
    return super.m;
  }
}

class C extends B {
  void test() {
    print(super.m == super.getClosurization()); // prints true
  }
}

main() {
  C o = new C();
  o.test();
}
```

The current Dart implementation (Dart VM version: 1.13.0-dev.6.0 (Wed Oct  7 08:09:59 2015) on "linux_x64") prints true. And it is what I expect. But in this example closurizations were not created by code declared in the same class and therefore, according the spec, should not be equal.

Either specification either implementation is wrong. I think spec should be changed.

**Comment by lrhn** [comment]
The "identical bindings of `this`" means that the `this` value in the methods are identical - i.e., it's methods in the same class *and* on the same instance.

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.
