### ISSUE TITLE
Add 1.12.2 section to CHANGLOG mentioning one change there

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24675]
RE e6d9210 commit

I'd love details here so we can post to announce@

CC @mit-mit

**Comment by davenotik** [comment]
It was in fact added since: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#core-library-changes-2 as mentioned over at https://groups.google.com/a/dartlang.org/d/msg/misc/Cy1Wwckgg0M/jy7hdn7HAQAJ.

**Comment by kevmoo** [comment]
Thanks for the heads up, @davenotik 

Seems fixed in 9fc82d04aab3b569098fe7c6fab756afa1203e2b
