### ISSUE TITLE
NoSuchMethodError: method not found: 'getState'

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24689]
@bwilkerson has a possible fix.
I will work on a fix for the cache.

1:33:37 PM Throwable: Dart analysis server, SDK version 1.13.0-edge.6c85fe785a85b1a907ce05f440dd08b2fd0fd994, server version 1.12.0, FATAL error: The null object does not have a method 'getState'.

NoSuchMethodError: method not found: 'getState'
Receiver: null
Arguments: [Instance of 'ResultDescriptorImpl']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      AnalysisContextImpl.computeResolvedCompilationUnitAsync. (package:analyzer/src/context/context.dart:657)
#3      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2026)
#4      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1520)
#5      AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1101)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:149)
#7      AnalysisContextImpl.performAnalysis... (show balloon)

**Comment by scheglov** [comment]
[Keep cache entries for explicitly added sources.](https://codereview.chromium.org/1420613003)

**Comment by scheglov** [comment]
This may fix this problem.
https://codereview.chromium.org/1420613003/

We need to observe to test this hypothesis.

**Comment by bwilkerson** [comment]
We are no longer seeing this exception being produced, so I'm going to close this issue.
