### ISSUE TITLE
dart2js code broken in IE if HttpRequest.timeout is used

### ISSUE THREAD

**Issue by rinick** [dart-lang/sdk#24688]
```dart
import 'dart:html';
main(){
  HttpRequest xhr = new HttpRequest();
  xhr.timeout = 0;  // this line breaks dart2js
  window.alert('it runs');
}
```
compile this with dart2js, IE throw error during dart closure initialization
works fine in chrome, firefox, and Microsoft Edge browser

**Comment by sethladd** [comment]
Thanks for the report! Curious, what version of Dart are you using?

**Comment by sigmundch** [comment]
Also, can you indicate what version of IE you were using?

**Comment by rinick** [comment]
I tested it with 1.12.1 and 1.13.0
with IE 11,   IE 10 emulation mode in IE 11

**Comment by ajsergeev** [comment]
The same thing is with SDK 1.11.1 for me

**Comment by alan-knight** [comment]
Note from https://msdn.microsoft.com/en-us/library/cc304105(v=vs.85).aspx

"The timeout property may be set only in the time interval between a call to the open method and the first call to the send method."

Is that the issue you're seeing?

**Comment by rinick** [comment]
yes, I think that's the issue, thanks for the help!

also I find some other properties have same problem, like XMLHTTPRequest.responseType.
which is not even documented in msdn 
https://msdn.microsoft.com/en-us/library/hh872882(v=vs.85).aspx

It would be nice if dart2js can do the trick for IE and delay the setting, or maybe mention this issue in dart's doc.
