### ISSUE TITLE
Configure analyzer to enable/disable certain lints

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24680]
It looks like it's almost possible, but not completely, to configure which lints are applied per project, via the .analysis_options file

Let's make it possible and awesome!

**Comment by pq** [comment]
> Let's make it possible and awesome!

![screen shot 2015-11-06 at 3 42 36 pm](https://cloud.githubusercontent.com/assets/67586/11011461/0be1325a-849d-11e5-898a-b63b7e13d2f6.png)

Done.

Bonus points for validation of known lint rules.

![screen shot 2015-11-06 at 3 43 40 pm](https://cloud.githubusercontent.com/assets/67586/11011478/2c8e7620-849d-11e5-91a3-39a721d1e764.png)

:+1:
