### ISSUE TITLE
Roll back packageConfig/File/Spec updates in 1.13

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24691]
* [x] Remove `Isolate.packageMap` getter
* [x] Remove `Isolate.packageRoot` getter
* [x] Remove `Isolate.spawnUri({packageMap})` named argument

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by iposva-google** [comment]
Review pending in https://codereview.chromium.org/1409343007/

**Comment by kevmoo** [comment]
Landed in 1fa2ef874d61eb3ea994d26009cb2d02a86e5bf3

Thanks, @iposva-google - would you open a merge request for 1.13?

**Comment by iposva-google** [comment]
Removed additional obsolete test with d164c23394d2afd34c7cd4d2dc96940789db7c77

**Comment by iposva-google** [comment]
Merge request filed as issue 24701.
