### ISSUE TITLE
Request for removing empty package.

### ISSUE THREAD

**Issue by VZout** [dart-lang/sdk#24697]
Hello I was having problems with the "test" package created by the dart eclipse plugin but pub get could not download it. So i tried publishing to see if my package works without the /test directory.

https://pub.dartlang.org/packages/weDGE

Could you please remove it for me?

**Comment by sethladd** [comment]
cc @whesse who might be able to help?

**Comment by whesse** [comment]
We don't have a simple system in place for removing packages.  If you still want to publish a package with this name, could you simply publish a new version, 0.0.2, of this package, with the correct files?

**Comment by kevmoo** [comment]
@VZout if it's just a mistaken upload, with no value, I think @mkustermann has the keys to fix this.

**Comment by whesse** [comment]
I have removed the package.  I was just asking if it really needed to be removed.
