### ISSUE TITLE
Add builtin-roots option to SecurityContext constructor

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24693]
We should expose a way to construct new SecurityContext objects that contain the built-in CA roots that SecurityContext.defaultContext contains.  If people want to modify this context, they should be able to create a new one which can be modified independently of the global one.  Adding client certificates is an example of a modification people would want to do to this context.

**Comment by jakobr-google** [comment]
This is even more important now, given that supported protocols for ALPN are also registered on the SecurityContext.

I need this for gRPC, where I have to declare support for h2 in ALPN, and at the same time trust the built-in roots. The only way to do that currently is through `SecurityContext.defaultContext`, but that causes all other unrelated connections to also negotiate h2, breaking other libraries.

Exposing `trustBuiltinRoots()` (or with a better name) on `SecurityContext` instances should fix this. I'm hoping it's possible to port the fix to stable as well.

**Comment by zanderso** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/20580/ Adds an optional named boolean parameter `withTrustedRoots` to the SecurityContext constructor.
