### ISSUE TITLE
Please merge 2 CLs into dev channel

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#24703]
@whesse @mit-mit @kasperl

Area-Dartium

Please merge these two CLs into dev channel.

Fixes failure with nested custom elements and data binding; order of creation was not consistent between C++ code in Dartium 1.12 and Dartium JS interop.  Also, noticed a breakage with code movement from a checkin a few days ago (returning null instead of HtmlDocument).

1: Fixed improper construction of custom elements https://github.com/dart-lang/sdk/commit/d796048fccea932b074a508505ccea1ab283f354 

2: Failure from a few days ago (returning null) on an exception masked error https://github.com/dart-lang/sdk/commit/e4a156785bdaa8ffda4c907559c3a8e35f6b6cdc

https://codereview.chromium.org/1409853006

Merged clean.

**Comment by whesse** [comment]
Also include this commit, which updates a passing test in the status file:
54aee614a29c62c7b2fad43e07954a987754d37a

**Comment by whesse** [comment]
Merged in version 1.13.0-dev.7.3
The real -dev.7.3, not -dev.7.2.
