### ISSUE TITLE
ThreadIterator_AddFindRemove test is flaky

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24700]
See, for example (links will go stale):
http://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/10678/steps/tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/10671/steps/checked_tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/vm-arm64-sim-release-be/builds/8169/steps/tests/logs/stdio

**Comment by fsc8000** [comment]
Duplicate of #24692 .
