### ISSUE TITLE
error on changing to device mode, Already have a Dart type associated

### ISSUE THREAD

**Issue by cbobach** [dart-lang/sdk#24702]
# spa_error
Reconstruct polymer-dart spa errors in device mode

Using dart version: 1.13.0-dev.7.2, chromium version: 45.0.2454.101 Ubuntu 15.10, and dartium version: Chromium 39.0.2171.99 custom 

dependencies:
  web_components: '>=0.11.3 <0.13.0'
  route_hierarchical: any
  reflectable: ^0.3.1
  polymer: ^1.0.0-rc.2
  polymer_interop: ^1.0.0-rc.1
  polymer_elements:
    git:
      url: https://github.com/dart-lang/polymer_elements.git
      ref: update

ERROR:
interop_support.js:72 Already have a Dart type associated with iron-media-query
interop_support.js:72 Already have a Dart type associated with iron-selector
interop_support.js:72 Already have a Dart type associated with paper-drawer-panel
interop_support.js:72 Already have a Dart type associated with paper-item
interop_support.js:72 Already have a Dart type associated with paper-menu
interop_support.js:72 Already have a Dart type associated with iron-meta
interop_support.js:72 Already have a Dart type associated with iron-meta-query
interop_support.js:72 Already have a Dart type associated with iron-icon
interop_support.js:72 Already have a Dart type associated with iron-iconset-svg
interop_support.js:72 Already have a Dart type associated with opaque-animation
interop_support.js:72 Already have a Dart type associated with neon-animatable
interop_support.js:72 Already have a Dart type associated with neon-animated-pages
interop_support.js:72 Already have a Dart type associated with slide-left-animation
interop_support.js:72 Already have a Dart type associated with slide-from-right-animation
interop_support.js:72 Already have a Dart type associated with array-selector
interop_support.js:72 Already have a Dart type associated with dom-bind
interop_support.js:72 Already have a Dart type associated with dom-if
interop_support.js:72 Already have a Dart type associated with dom-repeat
js_helper.dart:1697 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'main-app'. A type with that name is already registered.

I have made a repo that reproduces the error https://github.com/cbobach/spa_error. I have found an old error that looks similarly with polymer  0.16 https://github.com/dart-lang/polymer-dart/issues/58.

**Comment by madsager** [comment]
This issue was moved to dart-lang/polymer_elements#102
