### ISSUE TITLE
Please merge revisions into dev channel

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#24701]
@ricowind @whesse @kasperl
This does "Roll back packageConfig/File/Spec updates in 1.13"
As described in issue 24691.

Revisions:
1fa2ef874d61eb3ea994d26009cb2d02a86e5bf3
d164c23394d2afd34c7cd4d2dc96940789db7c77

**Comment by iposva-google** [comment]
CC @lrhn @mit-mit @sethladd

**Comment by whesse** [comment]
Merged in version 1.13.0-dev.7.3
The real -dev.7.3, not -dev.7.2.
