### ISSUE TITLE
Please merge revision #5bd191ee12674f0fb60cc887be4c97bdd6a9ca79 into dev channel

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24715]
@whesse @mit-mit @kasperl 
Please merge 5bd191ee12674f0fb60cc887be4c97bdd6a9ca79 to fix [Exception from analyser when adding r before an import string](https://github.com/dart-lang/sdk/issues/24709)

This merged cleanly

**Comment by whesse** [comment]
This is subsumed by merge request #24742 which includes it.
