### ISSUE TITLE
Analyzer strong mode error on valid use of factory constructor

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#24711]
We generally make it an error to try to downcast an instance creation expression, since such a downcast will always fail.  This is not true for factory constructors however - we need to allow this case.  This example currently returns an error, should be allowed.

```dart
class Animal {
  Animal();
  factory Animal.cat() {return new Cat();}
}

class Cat extends Animal {
  Cat();
}

void main() {
  Cat c = new Animal.cat();
}
```

cc @vsmenon @devoncarew

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1578863004/
