### ISSUE TITLE
Unactionable "has inferred type" hint with typedefs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24710]
```dart
typedef String Test(String arg);

String test1(String arg) => '1';
String test2(String arg) => '2';

void main() {
  Test test = test1;
  test = test == test1 ? test2 : test1;"                                                                                                                                                                      
}
```

```
Analyzing [test.dart]...
[hint] test == test1 ? test2 : test1 has inferred type (String) → String (test.dart, line 8, col 10)
1 hint found.
```

I don't know what the analyzer wants me to do here. Give it a pat on the head? (Apologies if this is one of the strong mode hints that was recently removed. We haven't yet revved the SDK.)

I think my ideal resolution here would be to replace this hint with a warning that fires whenever you have an implied type (e.g. when you haven't specialised a list literal, or when you call the Map constructor without specialising it, or when you use `var` or don't explicitly type a property or argument).

**Comment by bwilkerson** [comment]
This hasn't been removed, but should be reviewed.

**Comment by vsmenon** [comment]
Yeah, this was a strong-hint.  We've removed that.

In future, we'll have a warning when we *can't* determine a non-dynamic type.

**Comment by Hixie** [comment]
Cool. I filed https://github.com/dart-lang/sdk/issues/24712 on the warning I'd like to see.

What SDK version should I be using to see these warnings be gone?

**Comment by vsmenon** [comment]
Looks like it hasn't pushed out yet.  But, regardless, remove --strong-hints get rid of this hint.  That flag will disappear.

**Comment by jmesserly** [comment]
I believe this has been fixed. (strong hints are not turned on as part of strong-mode.)
