### ISSUE TITLE
Missing and extra quick fixes for undefined type

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24714]
Given the following files:

a.dart
    library a;
    class One {}

b.dart
    library b;
    class One {}
    class Two {}

c.dart
    library c;
    import 'b.dart' show Two;
    main () {
      new Two();
      new One();
    }

Place the cursor over the name "One" in c.dart and ask for quick fixes.

I expected to see a suggestion to import a.dart, but it isn't there.
I didn't expect to see a suggestion to change the name to "int", but it is there.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1413973007

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/cbea0dedf98c449178455eb17089d7a1b6a16985
