### ISSUE TITLE
Js interop and pass arguments as functions

### ISSUE THREAD

**Issue by Aetet** [dart-lang/sdk#24720]
Hello.
I play around with js-interop. But there's no example for passing function as argument.
Example:
```js
Redux.createStore((state, action) => {
 // some code
}, 0);
```
At dart I do this:
```dart
@Js("Redux.createStore")
external Store createStore(Function reducer, State state);

@Js()
class Store {

}

@Js()
class State {
  external factory State({num a});
}
```

But when I invoke `createStore` function with:
```dart
  more(state, action) {
    print('state: $state');
    print('action: $action');
  }
  var a = createStore(more, new State(a: 1));
  print(a);
```
 `reducer` It does not have type of function and exception raises. How to handle this situation?

**Comment by jirkadanek** [comment]
The README for package:js says

>Passing functions to JavaScript.
If you are passing a Dart function to a JavaScript API, you must wrap it using `allowInterop` or `allowInteropCaptureThis`.

There are some examples contained in tests, see https://github.com/dart-lang/sdk/blob/master/tests/html/js_typed_interop_test.dart for one.

I guess what you need to do is call

    var a = createStore(allowInterop(more), new State(a: 1));

**Comment by Aetet** [comment]
Thanks
