### ISSUE TITLE
pub.dartlang.org shows a different latest version of a package in the search result than in the package version history. This also applies for the modification date.

### ISSUE THREAD

**Issue by christophhermann** [dart-lang/sdk#24729]
When searching at https://pub.dartlang.org/ for polymer then version 0.16.3+3 is reported:
![image](https://cloud.githubusercontent.com/assets/3696338/10738822/7ccbc7e6-7c19-11e5-84aa-ca04b0c7e824.png)

But when I am looking directly at the version history the current version is 1.0.0-rc.3:
![image](https://cloud.githubusercontent.com/assets/3696338/10738868/b1b7baf0-7c19-11e5-8e2b-a18ec66190bd.png)

Sadly, pub also thinks that 0.16.3+3 is the latest version. Therefore I am not able to run `pub get` on a polymer project built by stagehand. The dependencies of such a project are:

> dependencies:
>   browser: ^0.10.0
>   polymer_elements: ^1.0.0-rc.1
>   polymer: ^1.0.0-rc.2
>   reflectable: ^0.3.1
>   web_components: ^0.12.0

My platform is Mac.
Pub version is 1.12.2
Dart version is 
> Dart VM version: 1.12.2 (Wed Oct 21 06:56:12 2015) on "macos_x64"

The output from `pub get --verbose` is:

> pub get --verbose
> FINE: Pub 1.12.2
> MSG : Resolving dependencies...
> SLVR: Solving dependencies:
>     | - web_components ^0.12.0 from hosted (web_components)
>     | - polymer ^1.0.0-rc.2 from hosted (polymer)
>     | - browser ^0.10.0 from hosted (browser)
>     | - reflectable ^0.3.1 from hosted (reflectable)
>     | - polymer_elements ^1.0.0-rc.1 from hosted (polymer_elements)
> IO  : Get versions from https://pub.dartlang.org/api/packages/web_components.
> FINE: HTTP GET https://pub.dartlang.org/api/packages/web_components
>     | Accept: application/vnd.pub.v2+json
>     | user-agent: Dart pub 1.12.2
> FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/web_components
>     | took 0:00:08.685511
>     | alt-svc: quic=":443"; p="1"; ma=604800
>     | cache-control: private
>     | transfer-encoding: chunked
>     | date: Mon, 26 Oct 2015 18:47:51 GMT
>     | content-encoding: gzip
>     | content-type: application/json
>     | x-frame-options: SAMEORIGIN
>     | via: iwfh132:14812
>     | x-xss-protection: 1; mode=block
>     | x-content-type-options: nosniff
>     | server: Google Frontend
> IO  : Get versions from https://pub.dartlang.org/api/packages/polymer.
> FINE: HTTP GET https://pub.dartlang.org/api/packages/polymer
>     | Accept: application/vnd.pub.v2+json
>     | user-agent: Dart pub 1.12.2
> FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/polymer
>     | took 0:00:00.169713
>     | alt-svc: quic=":443"; p="1"; ma=604800
>     | cache-control: private
>     | transfer-encoding: chunked
>     | date: Mon, 26 Oct 2015 18:47:52 GMT
>     | content-encoding: gzip
>     | content-type: application/json
>     | x-frame-options: SAMEORIGIN
>     | via: iwgu69:26104
>     | x-xss-protection: 1; mode=block
>     | x-content-type-options: nosniff
>     | server: Google Frontend
> IO  : Get versions from https://pub.dartlang.org/api/packages/browser.
> FINE: HTTP GET https://pub.dartlang.org/api/packages/browser
>     | Accept: application/vnd.pub.v2+json
>     | user-agent: Dart pub 1.12.2
> FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/browser
>     | took 0:00:00.182468
>     | alt-svc: quic=":443"; p="1"; ma=604800
>     | cache-control: private
>     | transfer-encoding: chunked
>     | date: Mon, 26 Oct 2015 18:47:52 GMT
>     | content-encoding: gzip
>     | content-type: application/json
>     | x-frame-options: SAMEORIGIN
>     | via: iwgu69:26104
>     | x-xss-protection: 1; mode=block
>     | x-content-type-options: nosniff
>     | server: Google Frontend
> IO  : Get versions from https://pub.dartlang.org/api/packages/reflectable.
> FINE: HTTP GET https://pub.dartlang.org/api/packages/reflectable
>     | Accept: application/vnd.pub.v2+json
>     | user-agent: Dart pub 1.12.2
> FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/reflectable
>     | took 0:00:00.164278
>     | alt-svc: quic=":443"; p="1"; ma=604800
>     | cache-control: private
>     | transfer-encoding: chunked
>     | date: Mon, 26 Oct 2015 18:47:52 GMT
>     | content-encoding: gzip
>     | content-type: application/json
>     | x-frame-options: SAMEORIGIN
>     | via: iwgu69:26104
>     | x-xss-protection: 1; mode=block
>     | x-content-type-options: nosniff
>     | server: Google Frontend
> IO  : Get versions from https://pub.dartlang.org/api/packages/polymer_elements.
> FINE: HTTP GET https://pub.dartlang.org/api/packages/polymer_elements
>     | Accept: application/vnd.pub.v2+json
>     | user-agent: Dart pub 1.12.2
> FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/polymer_elements
>     | took 0:00:00.164855
>     | alt-svc: quic=":443"; p="1"; ma=604800
>     | cache-control: private
>     | transfer-encoding: chunked
>     | date: Mon, 26 Oct 2015 18:47:52 GMT
>     | content-encoding: gzip
>     | content-type: application/json
>     | x-frame-options: SAMEORIGIN
>     | via: iwgu69:26104
>     | x-xss-protection: 1; mode=block
>     | x-content-type-options: nosniff
>     | server: Google Frontend
> SLVR: * start at root
> SLVR: | version 0.16.3+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.3+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.3+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.1+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.1+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.1+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.1+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+7 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+6 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.16.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.5+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.5+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.5+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.5+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.3+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.3+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1+5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.15.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.2+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.14.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.13.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.13.0+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.13.0+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.13.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.13.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.2+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.1+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.0+7 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.0+6 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.0+5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.12.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0+5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.1+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.1+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.5+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.5+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.3+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.3+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.3+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.2+4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.2+3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.2+2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.2+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.1+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.9.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.2+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.0+1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.5.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | constraint doesn't match selected version 0.0.1 of test:
>     | |   polymer 1.0.0-rc.3 from hosted -> test ^0.12.3 from hosted (test)
> SLVR: | constraint doesn't match selected version 0.0.1 of test:
>     | |   polymer 1.0.0-rc.2 from hosted -> test ^0.12.3 from hosted (test)
> SLVR: | version 0.12.0-dev of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.1-dev of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.8 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.7 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.6 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.3 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.11.0-dev of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.13 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.12 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.11 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.10 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.9 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.8 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.7 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.6 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.5 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.4 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.3.dev of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.2 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.1 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: | version 0.10.0-pre.0 of polymer doesn't match >=1.0.0-rc.2 <2.0.0:
>     | |   test 0.0.1 (root) -> polymer ^1.0.0-rc.2 from hosted (polymer)
> SLVR: BacktrackingSolver took 0:00:09.589496 seconds.
>     | - Requested 5 version lists
>     | - Looked up 1 cached version lists
>     | - Requested 0 pubspecs
>     | - Looked up 5 cached pubspecs
>     | 
> FINE: Resolving dependencies finished (9.650s).
> ERR : Package polymer has no versions that match >=1.0.0-rc.2 <2.0.0 derived from:
>     | - test depends on version ^1.0.0-rc.2
> FINE: Exception type: NoVersionException
> FINE: package:pub/src/entrypoint.dart 154      Entrypoint.acquireDependencies.<async>
>     | ===== asynchronous gap ===========================
>     | dart:async                               _Completer.completeError
>     | package:pub/src/entrypoint.dart 199      Entrypoint.acquireDependencies.<async>
>     | ===== asynchronous gap ===========================
>     | dart:async                               _Future.then
>     | package:pub/src/entrypoint.dart 152      Entrypoint.acquireDependencies.<async>
>     | ===== asynchronous gap ===========================
>     | dart:async                               Future.Future.microtask
>     | package:pub/src/entrypoint.dart          Entrypoint.acquireDependencies
>     | package:pub/src/command/get.dart 30      GetCommand.run
>     | package:args/command_runner.dart 178     CommandRunner.runCommand.<fn>
>     | dart:async                               Future.Future.sync
>     | package:args/command_runner.dart 131     CommandRunner.runCommand
>     | package:pub/src/command_runner.dart 130  PubCommandRunner.runCommand.<async>.<fn>
>     | dart:async                               Future.Future.sync
>     | package:pub/src/utils.dart 103           captureErrors.<fn>
>     | package:stack_trace                      Chain.capture
>     | package:pub/src/utils.dart 117           captureErrors
>     | package:pub/src/command_runner.dart 130  PubCommandRunner.runCommand.<async>

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#45
