### ISSUE TITLE
dart2js cps: Type of lists change after creation

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#24727]
The SDK is implemented using the assumption that the type of a JSArray can change after creation (but before the array escapes into user code).

This CPS IR currently enforces that the runtime type of an object must be set in the same atomic instruction as the allocation. The ReadTypeVariable and TypeTest instructions are thus location-independent. But this makes it hard to support arrays with reified type arguments.

We could discard the assumption and add a SetRuntimeType instruction. ReadTypeVariable would then be harder to get rid of (about as hard as load elimination / scalar replacement). In theory it could block scalar replacement if we fail to remove it (although I haven't seen any case where that happens).

Another approach is to make ReadTypeVariable and TypeTest location-independent EXCEPT when the type being manipulated might depend on the type variable on a JSArray object. That's kind of a hack.

Lastly, we could special-case every call that might lead to JSArray.typed and translate the whole thing into one instruction. But there are quite a few calls that indirectly lead to JSArray.typed calls.

**Comment by rakudrama** [comment]
Obsolete
