### ISSUE TITLE
Extends clause for class Object is permitted

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#24724]
According to specification (3-rd edition, June 2015) "10.9 Superclasses":
"It is a compile-time error to specify an extends clause for class Object."
However test below is compiled and executed successfully.
```dart
class A { int b = 1; }
class Object extends A {}
main() {
  A a = new Object();
  Object o = new Object();
  print(a.b);
  print(o.b);
}

dart test
1
1
```
Tested on Dart VM version: 1.13.0-dev.7.3 (Fri Oct 23 04:39:45 2015) on "linux_x64"

**Comment by lrhn** [comment]
The specification states that references to specific names always refer to the member of that name in the `dart:core` library, so in this case it is only saying that it's an error if `Object` in `dart:core` specifies a superclass (which, luckily, it doesn't).

> References to otherwise unspecified names of program entities (such as
classes or functions) are interpreted as the names of members of the Dart core
library.
