### ISSUE TITLE
Spec, grammar: function expression should not require semicolon

### ISSUE THREAD

**Issue by burakemir** [dart-lang/sdk#24728]
Dart Language Specification (3-rd Edition / June 2015) reads (16.10 Function Expressions)

functionExpression:
  formalParameterList functionBody
;

however

functionBody:
  async? ‘=>’ expression ‘;’
| ...etc
;

This looks unintended, not only since the paragraphs below mention the form "=> e" without semicolon, but because it would seem clumsy for function expressions to require a terminating semicolon. E.g. when passing a function as an argument, we'd write x.foo((e) => true) and in fact there is a lot of code out there that has this form.

It is not a simply typo however, since we do have two situations where requiring a semicolon makes sense: 
"functionSignature functionBody" as referenced from topLevelDefinition and
"methodSignature functionBody" from classMemberDefinition.

So maybe changing those to a new nonterminal terminatedFunctionBody would be enough to fix it.

**Comment by eernstg** [comment]
No milestone now: This correction is part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).

**Comment by srawlins** [comment]
This was fixed at some point:

```latex
\begin{grammar}                                                                                                                                        
<functionExpression> ::= <formalParameterPart> <functionBody>                                                                                          
\end{grammar}
```

**Comment by eernstg** [comment]
`<functionBody>` actually still ends in a [semicolon](https://github.com/dart-lang/language/blob/437683f3758b540e8baf7cbae2478e1f81a3a401/specification/dartLangSpec.tex#L1176), but [this PR](https://github.com/dart-lang/language/pull/628) will fix it.

**Comment by eernstg** [comment]
Landed [said PR](https://github.com/dart-lang/language/pull/628).
