### ISSUE TITLE
Polymer throws in bleeding edge Dartium

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24725]
Dartium:
> 1.13.0-edge.289bd0a056abb17587a692fd9b1f5f02190139e5

Dart:
> Dart VM version: 1.13.0-edge.289a22182e629e7e4f9085e3807ca0256dad5769 (Mon Oct 26 01:46:33 2015) on "linux_x64"

With a simple Polymer 1.0.0-rc.2 project.

> Serving content_editable web on http://localhost:43401
Build error:
Transform WebComponents on content_editable|web/index.html threw error: Class 'LibrarySpecificUnit' has no instance getter 'isInSystemLibrary'.
>
NoSuchMethodError: method not found: 'isInSystemLibrary'
Receiver: Instance of 'LibrarySpecificUnit'
Arguments: []
dart:core-patch/object_patch.dart 42                          Object._noSuchMethod
dart:core-patch/object_patch.dart 45                          Object.noSuchMethod
package:analyzer/src/generated/engine.dart 11313:42           SdkCachePartition.contains
package:analyzer/src/generated/engine.dart 133:26             AnalysisCache.get
package:analyzer/src/context/cache.dart 984:46                CachePartition._getDataFor
package:analyzer/src/context/cache.dart 615:36                CacheEntry._setDependedOnResults.<fn>
dart:core-patch/growable_array.dart 233                       List.forEach
package:analyzer/src/context/cache.dart 614:32                CacheEntry._setDependedOnResults
package:analyzer/src/context/cache.dart 490:5                 CacheEntry.setValue
package:analyzer/src/task/driver.dart 281:17                  AnalysisDriver.performWorkItem.<fn>
package:analyzer/src/generated/utilities_general.dart 170:15  _PerformanceTagImpl.makeCurrentWhile
package:analyzer/src/task/driver.dart 272:34                  AnalysisDriver.performWorkItem
package:analyzer/src/task/driver.dart 110:18                  AnalysisDriver.computeResult
package:analyzer/src/context/context.dart 662:14              AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 628:12              AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25       ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                              MappedListIterable.elementAt
dart:_internal/iterable.dart 219                              ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10       ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1149                                     _RootZone.runUnary
dart:async/future_impl.dart 502                               _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 585                               _Future._propagateToListeners
dart:async/future_impl.dart 376                               _Future._completeWithValue
dart:async/future_impl.dart 430                               _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                         _microtaskLoop
dart:async/schedule_microtask.dart 52                         _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 151                     _RawReceivePortImpl._handleMessage
>
dart:core                                                     Object.noSuchMethod
package:analyzer/src/generated/engine.dart 11313:42           SdkCachePartition.contains
package:analyzer/src/generated/engine.dart 133:26             AnalysisCache.get
package:analyzer/src/context/cache.dart 984:46                CachePartition._getDataFor
package:analyzer/src/context/cache.dart 615:36                CacheEntry._setDependedOnResults.<fn>
dart:core                                                     List.forEach
package:analyzer/src/context/cache.dart 614:32                CacheEntry._setDependedOnResults
package:analyzer/src/context/cache.dart 490:5                 CacheEntry.setValue
package:analyzer/src/task/driver.dart 281:17                  AnalysisDriver.performWorkItem.<fn>
package:analyzer/src/generated/utilities_general.dart 170:15  _PerformanceTagImpl.makeCurrentWhile
package:analyzer/src/task/driver.dart 272:34                  AnalysisDriver.performWorkItem
package:analyzer/src/task/driver.dart 110:18                  AnalysisDriver.computeResult
package:analyzer/src/context/context.dart 662:14              AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 628:12              AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25       ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                                ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10       ResolverImpl._performResolve.<fn>
[web] GET index.html => Could not find asset content_editable|web/index.html.
Build completed with 1 errors.

**Comment by zoechi** [comment]
It's actually not caused by Dartium but by the Analyzer. 
Limiting to `0.26.1+14` fixes the issue.

**Comment by bwilkerson** [comment]
If limiting the version of analyzer solves the problem, then it sounds like an issue for the owners of the pubspec containing that dependency. Which package contains the dependency?

**Comment by zoechi** [comment]
dart-lang/web-components#35
