### ISSUE TITLE
Move the command-line analyzer into the main repository

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24731]
I believe that there are four steps in this process:

- [x] 1. Copy the code from the old repository to the new repository.
- [x] 2. Fix the build system to build from the new location rather than the old.
- [x] 3. Move the issues from the old repository to the new repository.
- [x] 4. Update dartlang docs to point to new `README` location.
- [x] 5. ~~Remove the old repository.~~   Make the old repo read-only. (Follow-up: #25192.)

We should wait to start this until 1.13 has shipped. When a step is finished, please mark it and assign this issue to the person responsible for the next step (or me if you don't know who that is).

**Comment by pq** [comment]
@whesse, I thinking about this one:

> [2] Fix the build system to build from the new location rather than the old.

Minimally, I expect we need to remove `analyzer_cli` from `DEPS` and update `dartanalyzer` in `bin`...  Anything not obvious to consider?  Will `gclient sync` complain when it leaves `third_party`?  Anything we can do to make things go smoothest?

Thanks in advance!

**Comment by whesse** [comment]
I don't see any problems with that.  When people first update after it is removed, gclient sync will tell them to remove the directory manually.  They may well miss that, and leave it there.  After that, it may keep putting links to it in the out/[modeArch]/packages directory, until it is removed manually.  But that should not be a problem.

**Comment by pq** [comment]
Regarding 

>  3. Move the issues from the old repository to the new repository.

@nex3 : I know you have a clever script to do bulk issue moves...  Is that handy?

**Comment by nex3** [comment]
My script is very hacky, and right now those hacks are strongly oriented towards moving issues from the SDK repo to a different repo rather than the reverse. Since there are relatively few issues, it would probably be easier to use the non-bulk mover or just do it manually.

**Comment by pq** [comment]
Good deal.  Thanks!

**Comment by pq** [comment]
cc @Sfshaza for the dartlang doc update.  (Thanks in advance! :))

**Comment by pq** [comment]
cc @kevmoo as a heads-up that as soon as the docs pointers are up to date, I'll want to nuke the old repo and I may need an assist.

**Comment by kevmoo** [comment]
@pq happy to help

**Comment by whesse** [comment]
We need to be able to build old revisions of the SDK, so we cannot remove a
repo that is referred to by previous versions of the DEPS file.  Do not
nuke the repo.  You could commit deletions of all files, and a changed
README, but I think just changing the README and prohibiting commits (by a
precommit hook?) is better.

On Mon, Dec 7, 2015 at 6:21 PM, Kevin Moore <notifications@github.com>
wrote:

> @pq <https://github.com/pq> happy to help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24731#issuecomment-162598329>.
>



-- 
William Hesse

**Comment by Sfshaza** [comment]
The redirects have been updated. Try: https://www.dartlang.org/tools/analyzer/

**Comment by pq** [comment]
Yay!  Thanks @Sfshaza!

**Comment by pq** [comment]
Sounds good @whesse. @kevmoo : do you know the github-foo to do to prohibit commits?

**Comment by pq** [comment]
I've gone as far as I know how to go on the read-only bit.  Here are the current settings.

<img width="503" alt="screen shot 2015-12-09 at 9 11 33 am" src="https://cloud.githubusercontent.com/assets/67586/11692581/0420e7be-9e55-11e5-9f1d-132e99c1d83f.png">

I've opened up a follow-up bug for @kevmoo for any loose ends.

**Comment by pq** [comment]
:metal:
