### ISSUE TITLE
Class 'LibrarySpecificUnit' has no instance getter 'isInSystemLibrary'

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/sdk#24735]
Analyzer "0.26.1+16" seems to be ... broken.
It destroyed my Polymer project after "pub upgrade". Adding "analyzer: 0.26.1+14" to my pubspec.yaml works.

pub serve output
----------------------------

Build error:
Transform WebComponents on fnx_router|web/index.html threw error: Class 'LibrarySpecificUnit' has no instance getter 'isInSystemLibrary'.

NoSuchMethodError: method not found: 'isInSystemLibrary'
Receiver: Instance of 'LibrarySpecificUnit'
Arguments: []
dart:core-patch/object_patch.dart 42                       Object._noSuchMethod
dart:core-patch/object_patch.dart 45                       Object.noSuchMethod
package:analyzer/src/generated/engine.dart 11313           SdkCachePartition.contains
package:analyzer/src/generated/engine.dart 133             AnalysisCache.get
package:analyzer/src/context/cache.dart 984                CachePartition._getDataFor
package:analyzer/src/context/cache.dart 615                CacheEntry._setDependedOnResults.<fn>
dart:core-patch/growable_array.dart 234                    List.forEach
package:analyzer/src/context/cache.dart 614                CacheEntry._setDependedOnResults
package:analyzer/src/context/cache.dart 490                CacheEntry.setValue
package:analyzer/src/task/driver.dart 281                  AnalysisDriver.performWorkItem.<fn>
package:analyzer/src/generated/utilities_general.dart 170  _PerformanceTagImpl.makeCurrentWhile
package:analyzer/src/task/driver.dart 272                  AnalysisDriver.performWorkItem
package:analyzer/src/task/driver.dart 110                  AnalysisDriver.computeResult
package:analyzer/src/context/context.dart 662              AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 628              AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157       ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                           MappedListIterable.elementAt
dart:_internal/iterable.dart 219                           ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158       ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1166                                  _RootZone.runUnary
dart:async/future_impl.dart 494                            _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 577                            _Future._propagateToListeners
dart:async/future_impl.dart 368                            _Future._completeWithValue
dart:async/future_impl.dart 422                            _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                      _microtaskLoop
dart:async/schedule_microtask.dart 52                      _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage

**Comment by zoechi** [comment]
dup of dart-lang/web-components#35

**Comment by jakemac53** [comment]
I can confirm this is breaking all current polymer projects

**Comment by bwilkerson** [comment]
Can the polymer project add a limit on the analyzer version as a short term patch?

I've looked at this enough to know what's happening, but haven't yet figured out how it's happening, so I don't know how long it will take to get it fixed.

**Comment by jakemac53** [comment]
yes, I can add that in the short term

**Comment by jakemac53** [comment]
Actually, I am not sure how pub would deal with this. Since the current version of polymer accepts any version of the analyzer, if I publish a new version that does not it will have to choose either the newest analyzer or newest polymer... @munificent might be able to shed some light on what pub would do in this case.

**Comment by munificent** [comment]
@nex3 

If that version of analyzer is totally broken, we should either publish a fix for it or possibly tombstone it (i.e. the nuclear option: remove that version from pub.dartlang.org forever).

**Comment by bwilkerson** [comment]
I'm guessing that we have packages (I'd guess analyzer_cli) that depend on something in this version. Fixing the version is clearly the right option, I just don't know how quickly we can get to it and was investigating alternatives to remove our user's pain.

**Comment by nex3** [comment]
Why do we have packages depending on something that's specific to a patch version?

**Comment by bwilkerson** [comment]
My first guess is that we (the analyzer team) messed up and that some change was made that wasn't appropriate for a patch version. But I haven't had time to verify that yet.

**Comment by jakemac53** [comment]
fwiw I did add a constraint on `<0.26.1+15` to Polymer temporarily fix the issue that users see, but hopefully this can get resolved sooner rather than later so that we aren't blocking people from updating their versions of the analyzer (or updating packages which depend on a newer version).

**Comment by eernstg** [comment]
A similar version constraint has been used in package reflectable since https://github.com/dart-lang/code_transformers/issues/29, for what might very well be the same reason (the symptom is that the reflectable transformer never terminates, and it is stuck in `Resolvers.get`).

**Comment by eernstg** [comment]
We have just published a new version 0.3.4 of https://github.com/dart-lang/reflectable which contains the upper bound `analyzer: '>=0.26.0 <=0.26.1+14'`; I just confirmed that we cannot lift that constraint, because there are still several issues (including https://github.com/dart-lang/code_transformers/issues/29, as mentioned above).

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bwilkerson** [comment]
@eernstg @jakemac53 Can we close out this issue, now that we've gotten past the version issue?

**Comment by jakemac53** [comment]
Yes I don't believe this is an issue any longer
