### ISSUE TITLE
Please allow analyzer to look inside of a package for all core libraries for an embedder

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24732]
In order to help developers code against a set of core libraries offered by an embedder, we'd like to include all embedder's core libraries inside of a package. The analyzer can use these core libraries when analyzing developers' code.

For example, the flutter package should include all core libraries offered by the Flutter embedder running inside of the APK.

**Comment by bwilkerson** [comment]
I'd like to understand the semantics of the proposal that spawned this issue better before we start implementing it.

**Comment by sethladd** [comment]
Definitely. We are reviewing offline.

**Comment by pq** [comment]
Bouncing to you @sethladd.  Are we good to close this out?

**Comment by sethladd** [comment]
Probably, but we haven't turned it on for Flutter yet. Would like to keep it open until we see it work.

**Comment by bwilkerson** [comment]
Personally, I'd prefer to close this issue and have you open more specific issues if you run into specific problems with the implementation.

**Comment by sethladd** [comment]
That makes sense, but let's wait for John (eng on this feature) to let us know.

**Comment by johnmccutchan** [comment]
I think we can close this
