### ISSUE TITLE
autocompletion failure

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#24730]
This is with the preview build from @keertip based on 1.13.0-dev.7.1 . I'm expecting the autocomplete below to include things like length and clear()

![autocompletion-oct-26](https://cloud.githubusercontent.com/assets/2108507/10739948/b51dfa7a-7bdc-11e5-9f5b-347b219e2cb0.png)

**Comment by bwilkerson** [comment]
Have you enable strong mode?

If not, then this is expected behavior, or at least a known issue (#23001). Analyzer does not infer types of top-level variables or fields, but strong mode should infer a type for the field and that type should be used by completion.

**Comment by dgrove** [comment]
This is without strong mode, so it must be a dup. The fact that @kevmoo and I both expected this to be inferred is a good indicator that the current behavior isn't very intuitive.

**Comment by dgrove** [comment]
Duplicate of #23001.
