### ISSUE TITLE
Please merge two revisions into dev channel

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24744]
@whesse @mit-mit @kasperl @kevmoo @terrylucas @jacob314 

<Describe the problem this merge is fixing - include issue numbers if applicable>
Deprecate new internal Dartium/JsInterop APIs that are public.
Add documentation for allowInterop and allowInteropCaptureThis

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
8831fb876ea5989f48a3e95858cf83093b374e96  - Deprecate new internal Dartium/JsInterop APIs that are public
1ea666f401bf384de8f4a27793e0e680f9fbc3ca   - Add documentation for allowInterop and allowInteropCaptureThis

See 
https://codereview.chromium.org/1428593002
https://codereview.chromium.org/1411173005

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
This merged cleanly. There are no Dart "code" changes, only adding @Deprecated annotations. And the generating Python scripts are changed to include those annotations.

We expect to move/make private some of these post 1.13, but this is lower risk close to release.

**Comment by whesse** [comment]
Merged to dev in version 1.13.0-dev.7.4
