### ISSUE TITLE
Please merge many revisions into dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24742]
These are ordered oldest first

888c4c526f5a942d3168bc58573f364efa82fa97
5ec298794bf70d1855d74321d63c635007d92578
cae05d6bd43d8f2cf616b6d93317c28a99778190
3188a749946e62f335914691b5a7198662b3648a
9989687a2599c566d376967753992ef5e5481927
0cd0c886a102f7a17f23ff372c51bc65beb86ced
395b82c041466763e9b738000586e91f389edc99
e3970349ba95c242e563df0d0fe0b285bc234d7e
91e5facc0f1738bae94a9f4b3f7958d47de7ac92 # straight-forward cherry-pick error in changelog/pubspec
40b38e988bf46f9c17ef35ba326e0d92e30f843d
18a29ba8a86ff7bfd2f712d44285acd2cfaa48e2
ce6614f2dc418385919fed4d74a07be74b1fe40b
381d3ac5497f3d127bffcf3cdb5a6189652f7df7
3825cf0cd45f367de7f4cde35acd124b0a256725
adb8ebd0e67d10fadb4e2cc9ba55c1347e80cfa4
67576340b0d9a3670707851648584258f1ead7a4
204ee60bd0019cbca821677457ac91c7547e282b
873d46cbbb9ab13f47a0e51cad1da35b7cc03066
b49a389fbf0fff063d4de38f44c2406c29dd8667
c0d68a5437e9a35aed549e2c4021bcd5b4abef0d
af4fbdd9528a6411ea1f1c29f3beccdc0ae093b7
3b198ed6ae1af640759da49f115fce3739e82712
2d3fe73b363b3757db494a3458bd08c0f63f5f80
3a6234692593dc08c42d9c596b285b3b90022e98
8eb408914d1410a79af066e43c959fd6e6b51b05
27eb09033f880d9832380d37751b193f50a53127
948b21a8cff96a1a8cec414121983c8923eb2c21
c5f4af4df6c252f55fb2c08897e5d795c4ee92a7
6da5bb4ee44bafae746f0bdd118030c1b96e79fb
140a4f5891a4e7fbd716e6e3100dd68ed03c5e97
365ea71f7801e38f36115b9955b78f61ee90c018
e0636b183c4ab2a87b2d93198105c1413e3ea4d8
78c7cde13207a5c8df688c637d60c7cf563545ab
186bbfc92928a5324aa4f60488277730bdcd3731
568484d1062fc11afdd3b37d94350e0356a27c10 # trivaial merge fix - take "analyzer_cli_rev @ c7a2274"
4249335a0e8672ebd1593df9e85c45b798c54705
ea947094aea148d26bcb76527087f17f99866239
d5830fb6a3bc37de8ce230fcd3e6ffd6798a8435
5e9ea82aa44b75b1084c6e8f45ae5a5e952ad368
5f71b2e7cd3137fe4e8b7b58bb04b8c1f32129bf
f145f89ccb4b807641914a0631e9c77995a29b20
f8092a10124e0b0a9bbfb7b4da38b5aea58ac727
2a88bdac4adcc50a40d8f0724827b4bbfe949695
5b48108e07ab669ba6aaab31f45852a0f5f4ca91
c7907e780079a475b087f6bc614fd0967d3ea4a7
fc1f07fe2ee04640917751607ceaea6b031d9a1d
cc8f64b824ac0bd7607ffd330f0b4c287ee25e0f
527c163becbfe34b8c545f60cb67efb6ff30ab3e
de54dcbb0a442ade22d9d0a59b649a7653e7ec2b
bf0ba96027339f70dce4f1c4d34cb16651b5222d
ba6078197ba8093706873569d123cd94aa897308
6c85fe785a85b1a907ce05f440dd08b2fd0fd994
417161413f62fc73444327facd42311963b0f37a
ff40c262cf934d6e5068c1e2ca8d547956c94877
63865b5d1bda3861f4fd65edec38d99e44dd6ce4
f18a0209fb118d13a05cda315c91cefb04c0282a
7995c8ef1e8b3f9a5b18b42f553b77ab64ae7f6d
fb8cc0aa39e911cb0119a434ba6ea9e6e9ad76af
afa746230fc22a8274bd7fa496aa63e0c7ddbc03
9efcce02c314efd82dcc57a2a6a5a9592cec88d1
6726ac5ccd06239977c7a2aa06a4d3e3e34dd9ba
0881b53a3bf73e1b7671ea337f05d2dcf9aba80b
f45c8bc91785195f6c440f2045bbafda173b763a
b1215d77183e4e8306151177ca6ecbc550666f94
fe4644e35bdc9343066c00d3399b2f82ab380528
763af3d14e77157438797fdeed6eecb1d827b352
f09778528afedc456112fdf1b032431f0d5f6e93
af8c1938dcc80e7192207b9b143f70e197075498
a4a3053afd866841e360211318c5888869a28f3f
07acac8b8e87d66e5e89fb7a94596428c98ca212
d12abed5d72ae6676eda757fb0475c48d55b7a8b
5bd191ee12674f0fb60cc887be4c97bdd6a9ca79
33e6b737e8ecff2f4d913a0624e51b90d6692b84
041e61a0f63467612635a3cead6e999f7ca7b485
c133bf9467a2b469c24bf77e6187d727b4ef2595
df580cf0ea94121eee70daa303e73520cae0677e
4653d9bb76e8be1aeaf6db6f0fcdb9c8cd9d5d47
c43f292dd9f4bbb708756d0e1b56bdfac2f6ecdc
396ed51cf04cfdfd3f33e6803a32e6a9cbfeefcf
2d8d0e1ed79c4ddd38b6ea7ea07373dc88fcfe57
289bd0a056abb17587a692fd9b1f5f02190139e5
bb431bbec438320105da4c1876f260aa4fea161e
6e7c45403700f8ccd1a99d71f08cd7fdafd41c93
68dc36a3e73c5303828c0cec9b469e2038bf7a14
15c9636924bf128057a305187c920d9b3cb102ef
ffccd9af762ac566051acb7fa45f446e0ae06af5
b32e2ce0db74f052e2aa1e548e78e7f3d2532737
cbea0dedf98c449178455eb17089d7a1b6a16985
52fb3b3babd3595539ca4872475948c462e9a6d1
808f32d61d1188451a54feac6173054814dbbd22
e2f905e11d731a2d3b808cd0a824b447cef227e7 
cee3f13ae0a945acba9ef4250ca6be0456b28033

**Comment by whesse** [comment]
Merged to dev in version 1.13.0-dev.7.4
