### ISSUE TITLE
VM should be able to produce heap dumps and Observatory should be able to analyze them

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#24749]
Currently there is no way to solve memory usage problems on users machines.
Asking users to stop doing everything and using their machine for many hours is not an option.

@scheglov @iposva-google @rmacnak-google @bwilkerson @dgrove @clayberg

**Comment by iposva-google** [comment]
cc @dgrove

**Comment by rmacnak-google** [comment]
6e987b6eb556673d5b346c5152ca2c42441e28d6
