### ISSUE TITLE
Can't code complete a named parameter's name

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24758]
![screen shot 2015-10-29 at 1 25 16 pm](https://cloud.githubusercontent.com/assets/5479/10831086/a3df3222-7e40-11e5-8d3f-d8f15316055f.png)

Using Dart VM version: 1.13.0-dev.7.4 (Tue Oct 27 14:56:01 2015) on "macos_x64"

Should this work?

Expected: show me that `size` is an option here
Actual: no options

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Seth, do you see this consistently? There was a fix for this early in the 1.13 dev releases - it would definitely be in that version of the sdk.

**Comment by sethladd** [comment]
I don't know about "consistently", but it doesn't work for me. I'm on the very latest dev channel.

**Comment by devoncarew** [comment]
@danrubel

**Comment by danrubel** [comment]
This works (completing after the 'm')
```
new Duration(m)
```
but this does not (again, completing after the 'm')
```
new Duration(m: 34)
```

**Comment by sethladd** [comment]
Thanks for confirming!

**Comment by sethladd** [comment]
Very cool, thanks!!
