### ISSUE TITLE
analyzer does not return library level documentation

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#24756]
Something changed between 0.26.1+14 and 15 that the analyzer no longer returns doc comments for library elements. This breaks dartdoc.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1427513003/

**Comment by kevmoo** [comment]
Closed with https://github.com/dart-lang/sdk/commit/677d4b5bbc97c2aee1b03de8398ffedf977cd703

@keertip Do we need another +x release of the analyzer so dartdoc can pick up this fix?

**Comment by keertip** [comment]
@kevmoo we don't need another release of dartdoc, no code changes there. Checked with the latest (just) published analyzer code, dartdoc works fine!

**Comment by kevmoo** [comment]
@keertip right, but we DO need to publish a new analyzer version, right?

**Comment by bwilkerson** [comment]
We have already published a new version of analyzer with this fix.

**Comment by keertip** [comment]
@kevmoo, did not quite read the comment! As Brian mentioned, all done!
