### ISSUE TITLE
Code completing the value of a named argument doesn't show expected option: enum values

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24759]
Here's the code in question:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Column([
      new Center(child: new Text("first")),
      new Center(child: new Text("second")),
      new Center(child: new Text("third"))
    ], justifyContent: );
  }
}

```

Put your cusor after `justifyContent:` and try to code complete.

Expected: Show me `FlexJustifyContent`. That's what justifyContent is annotated for.

Actual: a bunch of options, none of which make sense in this context.

![screen shot 2015-10-29 at 2 53 36 pm](https://cloud.githubusercontent.com/assets/5479/10833129/09089344-7e4d-11e5-8b5f-54aecbf5e35e.png)

Hope that helps. Thanks!

**Comment by sethladd** [comment]
cc @devoncarew @danrubel

**Comment by sethladd** [comment]
FWIW, if I start typing the correct type name (Flex...) I get all options that start with Flex, instead of the one option that really only works here.

![screen shot 2015-10-29 at 2 57 50 pm](https://cloud.githubusercontent.com/assets/5479/10833227/9db42cd8-7e4d-11e5-9cd0-bf106098bf19.png)

**Comment by jwren** [comment]
Work in progress.  PR to be uploaded soon.

**Comment by jwren** [comment]
https://codereview.chromium.org/1881733002/- gets us closer to having only the correct kind of thing suggested in some named argument list.

There is no such justifyContext any more.  @sethladd what kind of annotation do you want respected?  Is it Flutter specific?  I don't think we have any such support in code completion yet.

**Comment by jwren** [comment]
@devoncarew Can you assist here?  What kind of annotation was this before the API went away?  Was it an enum, something else?  Can you give me an example/sample that works with APIs today?

**Comment by devoncarew** [comment]
@jwren, jup, looks like this code has changed. The new named parameter will be something like `crossAxisAlignment:`, and the valid values are `CrossAxisAlignment` enums (CrossAxisAlignment.start, end, center, stretch, baseline).

**Comment by devoncarew** [comment]
So, the problem is mostly likely that named params that are enums don't suggest the enum values.

**Comment by sethladd** [comment]
Sorry, I missed your ping.

> That's what justifyContent is annotated for.

> what kind of annotation do you want respected? 

The type annotations on the parameters. In the example above, `justifyContent` has a type annotation for `FlexJustifyContent`. So, when trying to code complete a value for `justifyContent`, consider sorting/prioritizing `FlexJustifyContent`

> Is it Flutter specific

Nope. Just a comment/suggestion around using Dart's type annotations.

**Comment by sethladd** [comment]
Looks like https://codereview.chromium.org/1989393002 was committed. Can we close this issue?

**Comment by sethladd** [comment]
Thanks!
