### ISSUE TITLE
new js interop: example works in dartium, but not compiled in chrome

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24752]
You can find the gist here, to reproduce:
https://gist.github.com/kasperpeulen/c31df5d8ab77e6aaf86e

I call this in main:
```dart
MathJax.Hub.Queue(() => MathJax.Hub.Typeset());
```

Using the following interop:
```dart
@JS('MathJax') external MathJaxClass get MathJax;

@JS('MathJax')
class MathJaxClass {
  external HubClass get Hub;
}

@JS('MathJax.Hub')
class HubClass {
  external Queue([p1,p2,p3,p4,p5,p6,p7,p8,p9,p10]);

  external Typeset();
}
```

I don't get any errors in chrome, so I have no idea what is going wrong. I just know that it works in dartium (and equivalent javascript code also works).

**Comment by jacob314** [comment]
For dart2js you must call allowInterop on any closures passed to JavaScript.
Change

MathJax.Hub.Queue(() => MathJax.Hub.Typeset());

to

MathJax.Hub.Queue(allowInterop(() => MathJax.Hub.Typeset()));

and your example works.
For 1.1.14 we will likely make Dartium throw an exception if you attempt to
pass a closure without calling allowInterop.

**Comment by kasperpeulen** [comment]
@jacob314 ah cool, thanks. Would it be somehow possible to do this `allowInterop()` on the library side? Instead of the library consumer side?

I was also wondering, I can not get this to work:

```
MathJax.Hub.Queue(allowInterop(MathJax.Hub.Typeset));
```

Is that expected?

**Comment by jacob314** [comment]
You must call it on the library consumer side. Cases such as passing arrays
between Dart and JS are intractable if it is not called on the consumer
side.

We could make it a little less painful by providing an
@allowInterop annotation that could even be used on a per library basis to
ensure that all closures created in a particular library are compatible
with JavaScript.
The other option would be to have a dart2js flag that slows down general
dart2js closure generation by making all closures implicitly call
allowInterop.

I don't understand the MathJax.Hub.TypeSet example.  Based on the method
signatures, MathJax.Hub.TypeSet is a JavaScript function so there is no
need to call allowInterop. However, I would guess that perhaps you are
getting tripped up by wanting the JavaScript function to have "this" bound
to MathJax.Hub.

**Comment by kasperpeulen** [comment]
> You must call it on the library consumer side. Cases such as passing arrays
between Dart and JS are intractable if it is not called on the consumer
side.

Sorry, I meant with library side, not the js package library, but my mathjax wrapper library. So basically, I want the user of my library not to worry about passing `allowInterop`. I could write something like:

```dart
MathJaxHubQueue(Function callback) {
  MathJax.Hub.Queue(allowInterop(callback));
}
```

But I would rather write something like:

```dart
@JS('MathJax.Hub')
class HubClass {

  Queue(Function callback) {
  _Queue(allowInterop(callback));
  }

  @JS('Queue)
  external _Queue(Function callback);

  external Typeset();
}
```

or maybe something like?

```dart
@JS('MathJax.Hub')
class HubClass {
  @allowInterop
  external Queue(Function callback);

  external Typeset();
}
```

**Comment by jacob314** [comment]
Please do not try to hide the need to call allowInterop from your users.
Your users will still need to know about it if at some point your API
starts passing Arrays containing Functions to JavaScript, etc.
Calling the allowInterop function on the user side is just the minimum
viable support for making Dart functions compatible with JavaScript. We
will provide better user level ways to specify that closures can be used
from JavaScript in the future (e.g. annotations users write when they
define closures, etc).
