### ISSUE TITLE
Analyzer doesn't show a warning for `(...)` on non-type annotation 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24751]
```dart
@PolymerRegister('app-element')
class AppElement extends PolymerElement {
  AppElement.created() : super.created();

  @property(observer: 'selectedxChanged')
  bool selected;
```
while `property` is defined as 

```dart
class Property extends PolymerReflectable {
  /// Fire *-change events to support two way binding.
  final bool notify;

  /// Name of a method to call when the property changes.
  final String observer;

  /// Whether or not this property should be reflected back to the attribute.
  final bool reflectToAttribute;

  /// Provided for computed properties.
  final String computed;

  const Property(
      {this.notify: false,
      this.observer,
      this.reflectToAttribute: false,
      this.computed});
}

const property = const Property();
```

The lower-case `@property` refers to `const property` which is a `const Property()` 

My mistake was that when I want to pass arguments I need to use the upper-case annotation
`@Property(...)` instead of `@property(...)`, but the analyzer should show a warning because `@property(...)` is invalid.

see also http://stackoverflow.com/questions/33365273/internal-error-http-localhost63342-epimss-polymer-app-web-index-dart-malf

**Comment by scheglov** [comment]
https://codereview.chromium.org/1436433002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/574cef9ee702581cab3b8e915fd7927ec947fe27
