### ISSUE TITLE
Add @anonymous annotation to specify @JS classes that don't have an actual prototype

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#24764]
These classes are the only classes allowed to have factory constructors that desugar to creating object literals. This will enable marking regular JS interop constructors as factory constructors.

**Comment by a14n** [comment]
`@anonymous` looks good to me (I used the same name in [js_wrapping](https://github.com/a14n/dart-js-wrapping#anonymous-objects))

**Comment by jacob314** [comment]
That isn't a coincidence. :)

**Comment by jacob314** [comment]
Patch landed to breeding_edge.
