### ISSUE TITLE
Dart objects not recognized as Dart objects in IE10

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#24762]
Causing apps to not start.

In `getInterceptor` the check `receiver instanceof P.Object` evaluates to `false` in IE10 where in Chrome and in IE11 it evaluates to `true`. This issue causes apps to never even start as it happens very early at runtime.

/cc @johnniwinther @hterkelsen @akunkel23

**Comment by akunkel23** [comment]
Ping, any update on this? We would prefer not to have to drop IE10 support (sending users to a "browser not supported" page) but as it is our pages are completely broken in IE10.

**Comment by akunkel23** [comment]
I may have spoken too soon, it seems like in our latest build things are working again - has anything changed recently?

**Comment by sigmundch** [comment]
Hey @akunkel23 - cool to hear your app is working again. I however don't believe there was any change in dart2js regarding this. It could be that this is not triggered on the latest angular or latest version of your app.

If you happen to reproduce the problem, please let me know what version of the dart2js/framework caused this so we can take a closer look.

Thanks!

**Comment by yjbanov** [comment]
@akunkel23 is it possible that you switched from the experimental JS emitter to the normal one?

**Comment by akunkel23** [comment]
Not that I'm aware of, where would that be configured?

**Comment by sigmundch** [comment]
basically if you have the `--fast-emitter` dart2js flag turn on, you'd be using the experimental emitter

**Comment by akunkel23** [comment]
Ah, no I don't think we've ever used it.

**Comment by yjbanov** [comment]
Has `--fast-emitter` been renamed to `--fast-startup`? If so, you might be using it.

**Comment by akunkel23** [comment]
Oh, yeah, we are using that but we never stopped, it's still enabled.

**Comment by sigmundch** [comment]
Thanks Yegor - my bad, it was `--fast-startup` all along.

**Comment by hterkelsen** [comment]
Let's close this unless we can get a repro
