### ISSUE TITLE
analyzer gets confused by "dynamic" used as an identifier

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#24765]
In 1.13.0-dev.7.4 a new warning appeared in some tricky code:
[warning] Negation argument must have a static type of 'bool'

The situation: a factory constructor has a bool keyword parameter named "dynamic" and calls another constructor with "!dynamic".

It's easy to work around, but this should work since "dynamic" is a built-in identifier rather than a keyword.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1416723011

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/2d41202422d1f6386d6edbeb6881ec3e23113c27
