### ISSUE TITLE
Unhandled exception in asynchronous for-in loop

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24766]
Intention of the code below is to catch the exception, that arise inside stream, 
while  event is generated.
However the exception is not caught by try ... catch clause.
Instead it is reported as unhandled. 

```
import 'dart:async';

computation(int computationCount){
  if (computationCount<5){
    return computationCount;
  }
  throw new Exception();
}

test() async {
  var processedValues = [];
  var period = new Duration(microseconds:1);
  try {
    await for (var i in new Stream.periodic(period, computation)) {
      processedValues.add(i);
    }
  } catch (e){
    print("Caught $e");
  }
  print(processedValues);
}

main() {
  test();
}
```
Output:
>Unhandled exception:
>Exception
>#0      computation (file:///D:/test.dart:7:3)
>#1      Stream.Stream.periodic.sendEvent (dart:async/stream.dart:152)
>#2      Stream.Stream.periodic.startPeriodicTimer.<anonymous closure> (dart:async/stream.dart:159)
>#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
>#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
>#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Dart VM version: 1.12.2 (Wed Oct 21 07:10:52 2015) on "windows_x64"

**Comment by lrhn** [comment]
This is a consequence of the way Stream.periodic is written. if the computation throws, the error is not added to the stream, so it just becomes an uncaught error in the internal timer callback.
I will fix.

**Comment by lrhn** [comment]
Fixed
