### ISSUE TITLE
No compile-error if mixin declares factory constructor

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24767]
According specification (3-rd Edition, June 2015) "12 Mixins":

"It is a compile-time error if a declared or derived mixin explicitly declares a
constructor."

In fact there are no compile error if mixin declares factory constructor:

``` dart
class A {
}

class M {
  factory M() {}
}

class C extends A with M {
}

main() {
  new C();
}
```

This code produces no error. Tested on Dart VM version: 1.13.0-dev.7.2 (Wed Oct 21 02:26:18 2015) on "windows_x64"

**Comment by mhausner** [comment]
Observation: dart2js compiles the program given above without any error message as well. In fact, if the 'factory' keyword is deleted, making M() a generative constructor, dart2js issues this error:

```
Error: Class used as mixin cannot have non-factory constructor.
     M() {}
```

The error message sounds as if factory constructors are allowed.

**Comment by mhausner** [comment]
Gilad, can you please clarify whether factory constructors are allowed in mixins? If they are, what are the semantics?

Thank you.

**Comment by gbracha** [comment]
The spec is very clear.  Constructors are not allowed. That said, we could certainly consider a change, as a factory constructor would pose no real challenges.  If it is indeed the case that all implementations support it, changing the spec might be a fine option.

**Comment by lrhn** [comment]
VM runs program without problem, analyzer does not warn, so I think a spec change would be fine.

**Comment by mhausner** [comment]
Please no Spec change. I will update the VM to follow the spec.

**Comment by mhausner** [comment]
The VM is Spec compliant with 851b4a995c72b484e1b4d13dabbc7e6dcfe7cc24

The error message is now more helpful, too. It points to the mixin application and the offending constructor.

```
dart ~/tmp/s.dart 
'file:///.../s.dart': error: line 5 pos 3: factory 'M' is illegal in mixin class M
  factory M() { print("hi"); }
  ^
'file:///..../s.dart': error: line 8 pos 24: mixin class 'M' must not have constructors
class C extends A with M {
                       ^

```

Dart2js and the analyzer need to fix their implementation. Bugs 25588 (analyzer) and 25587 (dart2js) are filed.

**Comment by jacob314** [comment]
Unfortunately this is a breaking change and we try to avoid shipping breaking changes unless we have discussed them.
This change is impacting existing users who added harmless factory constructors to their mixin classes.

**Comment by jacob314** [comment]
//cc @kevmoo

**Comment by iposva-google** [comment]
What you are saying in a sense is that fixing a bug is a breaking change. Sorry.

**Comment by kevmoo** [comment]
> What you are saying in a sense is that fixing a bug is a breaking change.

Absolutely. Folks are depending on the behavior we ship. We promise not to break them unless it's unavoidable.

In this case it's completely avoidable – so we will avoid it.

**Comment by lrhn** [comment]
So, if we don't want to change the behavior, we will need to change the specification.

I don't think that is a problem, as long as the factory constructor is not part of the mixin of the declaring class - we don't want to introduce constructors in a mixin application (yet).

**Comment by iposva-google** [comment]
You are basing this discussion on a single comment from Gilad, which "we could consider" a change to the spec. Since this has morphed into a discussion whether to change the spec or not I am removing the area-vm label. In any case it should be up to Gilad to determine what is right in the spec, regardless whether or not existing code relies on the broken implementation or not.

**Comment by mhausner** [comment]
Which user was impacted by this change?

**Comment by gbracha** [comment]
A factory constructor is really just a static method that can be called via new. It isn't part of the mixin and doesn't impact the design of any object construction mechanism we would consider to relax the ban on real constructors in mixins.  I expect to make a small tweak to the spec so that it does not ban factory constructors shortly. Specifically, section 12 will be revised to state:

It is a compile-time error if a declared or derived mixin explicitly declares a constructor _which is not a factory constructor_ . 

(the new text is italicized)

**Comment by iposva-google** [comment]
@gbracha Do you want to clarify for other kinds of constructors as well? Thanks.

**Comment by eernstg** [comment]
The change indicated in [this comment](https://github.com/dart-lang/sdk/issues/24767#issuecomment-185454872) was performed in 65421fb2bf6. Closing.
