### ISSUE TITLE
Dart VM crash when stressing inlining

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#24761]
./xcodebuild/DebugX64/dart --noopt --max_inlined_per_depth=5000 --inlining_callee_call_sites_threshold=50 --inlining_callee_size_threshold=6000 --inlining_depth_threshold=60 --inlining_size_threshold=6000 --inlining-hotness=0 --inlining-size_threshold=6000  benchmarks/DeltaBlue/dart/DeltaBlue.dart

/sources/git-debeli/sdk/runtime/vm/intermediate_language.cc:408: error: expected: StaticField().StaticValue() != Object::sentinel().raw()

**Comment by fsc8000** [comment]
Not reproducible anymore. Likely fixed in the mean time.
