### ISSUE TITLE
Resolve monkey-patched JS constructors better in Dartium

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24776]
zones.js replaces MutationObserver with an unnamed constructor. wrap_jso uses the name to look up the wrapper, so it fails in that case. We should handle that case more robustly. I think we have some logic for that already, it just needs to be extended to non-custom elements. We should also probably take a look at how dart2js looks up interceptors and make sure we're compatible with that. Justin mentioned that Stephen had at one point talked about pulling that logic out.
@rakudrama @justinfagnani

**Comment by sigmundch** [comment]
Some of it was made available to support the web components polyfill in the past (which wrapped almost every single JS object). Maybe that is what you need here too?

Take a look at: https://github.com/dart-lang/web-components/blob/8cf45405f966d57fdade70a2e0138a20d87962f6/lib/dart_support.js

in particular how we define a transformer in `window.dartNativeDispatchHooksTransformer`.

**Comment by sigmundch** [comment]
Do you have something else in mind or is the `dartNativeDispatchHooksTransformer` sufficent? If so, maybe we can close this issue?

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by terrylucas** [comment]
Alan does the problem still exist and if so would Siggi's solution work?

**Comment by alan-knight** [comment]
According to https://github.com/angular/zone.js/issues/197 the motivating example has been rewritten. It might need the Polymer DevTools extension to be updated to that version, but the problem should go away. I think the kind of fix that Siggi mentioned would work, but if we don't have any actual problems with it it may not be that important.
