### ISSUE TITLE
Allow `class Proxy<T> implements T`

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#24775]
This would reduce the amount of boilerplate needed for any kind of proxy implementation to 0.
We are using proxies a lot during testing eg mocks, and it would be useful if we could avoid to have transformers there or additional boilerplate:
Right now, we create specific `Proxy$T` classes that `implement $T, Proxy<$T>` which is cumbersome.

Thanks,
 Andreas

**Comment by matanlurey** [comment]
Proxies have changed quite a bit for Dart 2.
