### ISSUE TITLE
Please merge 2 CL into dev channel (one in Dart git and one in WebKit branch)

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#24771]
@whesse @mit-mit @kasperl

Area-Dartium

#1.  Please cherry-pick  e84f9941e1cf210646aef72e01eefaa993a7b798
Fixes Native custom element
BUG=24754

This didn't merge cleanly see CL https://codereview.chromium.org/1426613003

#2.  In addition, to the above cherry-pick the following change to WebKit (blink) must be cherry-picked:

commit 38a14a0c53347aa227dc2197d84e08f733c4cdff
Author: jacobr@google.com <jacobr@google.com@bbb929c8-8fbe-4397-9dbb-9b2b20218538>
Date:   Thu Oct 29 18:31:18 2015 +0000

    Fix crash in devtools when the prototype of a polymer element is incorrectly considered a dart:html object instead of a JsObject.
    
    Review URL: https://codereview.chromium.org/1419953005 .
    
    git-svn-id: svn://svn.chromium.org/blink/branches/dart/dartium@202692 bbb929c8-8fbe-4397-9dbb-9b2b20218538

There is no merge issue with the above WebKit cherry-pick.

#3.  After the above cherry-picks the DEPS file located in tools/deps/dartium.deps/DEPS (in the Dart origin/dev GIT repository) will need to change the dartium_webkit_revision to the revision # created for the 1.13 dev branch of WebKit after the cherry-pick of 38a14a0c53347aa227dc2197d84e08f733c4cdff e,g,

"dartium_webkit_revision": "#####",

**Comment by kevmoo** [comment]
Closed with 4db460ec48bfd82c370d99d9d816b2b45181c943
