### ISSUE TITLE
Observatory: exception on heap map page

### ISSUE THREAD

**Issue by mhausner** [dart-lang/sdk#24774]
This command:
dart --observe --pause_isolates_on_exit  ./pkg/compiler/lib/src/dart2js.dart  tests/language/hello_dart_test.dart

Then go to debugger | heap map

Unexpected exception:

NullError: method not found: 'ga3' on null

Stacktrace:

TypeError: Cannot read property 'ga3' of undefined at J.fl (http://localhost:8181/index.html.polymer.bootstrap.dart.js:36478:31) at jD.dart.jD.ue (http://localhost:8181/index.html.polymer.bootstrap.dart.js:23305:5) at jD.dart.jD.LX (http://localhost:8181/index.html.polymer.bootstrap.dart.js:23336:8) at eval (eval at <anonymous> (http://localhost:8181/index.html.polymer.bootstrap.dart.js:1773:8), <anonymous>:2:34) at dart.yT (http://localhost:8181/index.html.polymer.bootstrap.dart.js:11968:9) at VO.dart.VO.f6 (http://localhost:8181/index.html.polymer.bootstrap.dart.js:13338:12) at VO.dart.VO.ko (http://localhost:8181/index.html.polymer.bootstrap.dart.js:13289:12) at VT.dart.VT.$1 (http://localhost:8181/index.html.polymer.bootstrap.dart.js:13393:31) at a1x.dart.a1x.$0 (http://localhost:8181/index.html.polymer.bootstrap.dart.js:2191:29) at oU.dart.oU.jC (http://localhost:8181/index.html.polymer.bootstrap.dart.js:1051:9)

[Connect to a different VM]

**Comment by rmacnak-google** [comment]
Assumed stale.
