### ISSUE TITLE
dart2js:  world.fieldNeverChanges(field) does not detect super-setters

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24781]
tests/co19/Language/12_Expressions/15_Method_Invocation/4_Super_Invocation_A03_t04.dart
This test has a field that is assigned only via `super.func = ...`:
The query `compiler.world.fieldNeverChanges(field);` incorrectly returns `true` for this field.
This causes an incorrect optimization for https://github.com/dart-lang/sdk/commit/cc0525c0c4828bd476d70c3aa1261d3c3fbc70b5.

Unfortunately, there are many _effectively final_ fields that could be declared as final but are not.
Avoiding the _effectively final_ heuristic means the optimization misses many nice cases.

**Comment by rakudrama** [comment]
@johnniwinther Johnni - do you know where and how super.func=... should be registered as an assignment to func?

**Comment by johnniwinther** [comment]
I've never seen the subsystem but I'll take a look. Sounds like something the frontent should compute.

**Comment by johnniwinther** [comment]
FYI the test has been renamed to tests/co19/src/Language/Expressions/Method_Invocation/Super_Invocation/method_lookup_failed_t04.dart
