### ISSUE TITLE
Stack traces in precompiled code missing inlined frames

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24783]

**Comment by iposva-google** [comment]
As discussed we should have a way of specifying "with symbols" during a build, which then adds all of the necessary information to the snapshot.

cc @rmacnak-google

**Comment by fsc8000** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
AOT has inline frames and line numbers in stack traces as of cfe5e5f075431641642a8e3be2fbd4414eaca1fd
