### ISSUE TITLE
Test isolate/spawn_uri_multi_test/01 times out on x64 dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24795]
The test
isolate/spawn_uri_multi_test/01
is timing out flakily on the x64 dartium bot.
When the test doesn't time out, it takes less than 3 seconds.  When it times out, it takes over 1 minute.

Updated in status file.

The error is:
FAILED: none-dartium-checked release_x64 isolate/spawn_uri_multi_test/01
Expected: Pass 
Actual: Timeout
CommandOutput[dartium]:

stdout:
message:
  Dom could not be fetched, since the test timed out.

**Comment by terrylucas** [comment]
Seems to work in Dart 1.24.2 Stable (Dartium 50) will re-enable.
