### ISSUE TITLE
dart2js handles imports from https urls with default trusted roots only.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24797]
The dart2js code that reads libraries from http and https URLs uses an HttpClient that is created without an explicity SecurityContext.  The default context used in this case uses a default set of trusted root CAs, so only https URLs that are served by servers with a valid certificate backed by a well-known CA will be accepted.

To allow custom trusted root certificates, an option would need to be added to dart2js, to add these trusted roots, and they would be passed to the HttpClient.  I don't think there is any demand for this at this point, so the existing behaviour should be documented as working as intended.

The test for this, at tests/compiler/dart2js/http_test.dart, tries to use a custom set of test certificates, and therefore can't work.  It is also not updated to BoringSSL.  This test should be removed, since it cannot be made to pass.  The fact that it is not failing now, probably means that the test is not run.

**Comment by sigmundch** [comment]
dart2js no longer supports https imports
