### ISSUE TITLE
analysis_server/.../analysis_options_test fails on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24796]
The test pkg/analysis_server/test/integration/analysis/analysis_options_test
is failing with a runtime error on Windows. pkg/pkg.status is updated.

The error report is:
FAILED: none-vm-checked debug_ia32 pkg/analysis_server/test/integration/analysis/analysis_options_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
FAIL: OptionsIntegrationTest | test_option_warning
  Expected: List
    Actual: <null>

  package:unittest/src/simple_configuration.dart 128:34                          SimpleConfiguration.onExpectFailure
  package:unittest/src/simple_configuration.dart 24:13                           _ExpectFailureHandler.fail
  package:unittest/src/matcher/expect.dart 121:5                                 DefaultFailureHandler.failMatch
  package:unittest/src/matcher/expect.dart 95:20                                 expect
  pkg\analysis_server\test\integration\analysis\analysis_options_test.dart 35:5  OptionsIntegrationTest.test_option_warning.<async>
  dart:async-patch/async_patch.dart 27                                           _asyncThenWrapperHelper.<fn>
  dart:async/zone.dart 914                                                       _rootRunUnary
  dart:async/zone.dart 810                                                       _CustomZone.runUnary
  dart:async/future_impl.dart 502                                                _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 585                                                _Future._propagateToListeners
  dart:async/future_impl.dart 376                                                _Future._completeWithValue
  dart:async/future_impl.dart 430                                                _Future._asyncComplete.<fn>
  dart:async/zone.dart 907                                                       _rootRun
  dart:async/zone.dart 802                                                       _CustomZone.run
  dart:async/zone.dart 708                                                       _CustomZone.runGuarded
  dart:async/zone.dart 733                                                       _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 43                                          _microtaskLoop
  dart:async/schedule_microtask.dart 52                                          _microtaskLoopEntry
  dart:isolate-patch/isolate_patch.dart 96                                       _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 151                                      _RawReceivePortImpl._handleMessage

0 PASSED, 1 FAILED, 0 ERRORS

```
stderr:
Unhandled exception:
Exception: Some tests failed.
#0      SimpleConfiguration.onDone (package:unittest/src/simple_configuration.dart:197:9)
#1      _completeTests (package:unittest/unittest.dart:368:10)
#2      _runTest (package:unittest/unittest.dart:308:5)
#3      _nextTestCase (package:unittest/unittest.dart:256:3)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by whesse** [comment]
The test now passes. @DanTup @bwilkerson 
Removing the line from the status file.

**Comment by DanTup** [comment]
@whesse Thanks! I had created a CL to do this - out of curiosity, how did you notice it passing now if it was skipping?
