### ISSUE TITLE
Consider renaming `.analysis_options` to `.analysis_options.yaml`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24794]
I find it quite cumbersome when I edit `.analysis_options`, that I don't get any IDE support.
For example I often want to use <kbd>ctrl</kbd>+<kbd>/</kbd> to comment/uncomment some lines and of course always helpful is syntax highlighting.

This wouldn't be much of an issue if this file wasn't subject to manual editing, but I assume this is the way this file will be usually maintained.

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by pq** [comment]
What IDE do you use?  `Atom` has special support for options files now. :)  You should also be able to make this association in the IDE?

From my perspective I don't think we want to add this extension since it may limit us down the road.  (What if we want to extend or constrain YAML?  What if the built-in YAML editor does things that interfere with our best practices?)  

On another note, I've got a bunch of special support rolling out that should make these files feel more first-class.  In short order you'll see validation and errors and before long quick fixes and code completion. :+1:

**Comment by johnmccutchan** [comment]
My preference is that this file is merged with pubspec.yaml

**Comment by bwilkerson** [comment]
We discussed that, and decided that we should support the case where code that isn't a package is being developed.

**Comment by zoechi** [comment]
I use WebStorm. I guess there is a way to teach it about this file, but this shouldn't be necessary for anyone using something different than Atom.  
I mostly wanted to be sure this was an conscious decision. 

Should this be moved to WebStorm (and Sublime Plugin, ...) for out-of-the-box support of this file?

**Comment by pq** [comment]
> Should this be moved to WebStorm (and Sublime Plugin, ...) for out-of-the-box support of this file?

Sure.   On a related note, WS should treat these as priority files so that you get analysis as you type.

Related: https://github.com/dart-atom/dartlang/issues/437

**Comment by sethladd** [comment]
I appreciate the suggestion, but I don't think we're going to do this. +1 for having better editor support, for sure.

cc @kevmoo to confirm plans, but we might want to close this one out.

**Comment by pq** [comment]
@kevmoo : care to weigh in?

**Comment by alexander-doroshko** [comment]
Just FYI: WebStorm and all other JetBrains IDEs now treat `.analysis_options` files as YAML without any user configuration.

**Comment by kevmoo** [comment]
Glad to hear it, @alexander-doroshko 

File extensions are nice – seems like an easy thing to add support for. Support both with and without extension – only document w/ .yaml as the extension.

**Comment by alexander-doroshko** [comment]
I'd vote for not allowing to do the same thing in 2 ways if not necessary.

**Comment by johnmccutchan** [comment]
@alexander-doroshko +1

**Comment by bwilkerson** [comment]
@alexander-doroshko +100 We have too much of that already.

Either we make a breaking change (possibly in stages) or we leave it alone.

**Comment by pq** [comment]
:+1: 

And in that spirit, closing out.  Feel free to re-open if you want to continued the discussion!
