### ISSUE TITLE
Re-add dart:profiler

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24803]
The removal of `dart:profiler` in 1.13 has caused a lot of pain and strife for Dart users, and 1.13 isn't even released yet. The `analyzer` package, which is transitively used by almost every Dart package at least for testing, used `dart:profiler` up until its `0.26.1+8` release in October. This means that most packages for which `pub upgrade` hasn't been run recently will crash as soon as their tests are run.

The core SDK should generally avoid making breaking changes, since without incrementing its major version there's no way for packages to be future-proof against such changes. This is a case where the change is particularly painful because of how it affects `analyzer`, one of the most widely-used packages. It's also relatively easy to just avoid the breakage by retaining `dart:profiler` as a deprecated library that exports `dart:developer`.

cc @kevmoo @sethladd

**Comment by sethladd** [comment]
I can say that we did see more breaks that we anticipated. Unfortunately, we make breaking changes to the SDK (removing dart:profiler wasn't the only time), but we don't also rev the SDK version to reflect that we had a breaking change. Ideally, we should have bumped SDK version to 2.0 with this change.

If we were to roll back the removal of dart:profiler, would we hold everyone to a high standard of "we don't break users until we bump version number" ?

Perhaps the SDK team could consider a more liberal policy of bumping the SDK version when we introduce a breaking change.

Another idea: the SDK team could pick specific git tags to pull from, for each component of the SDK. Pulling from HEAD for everything means that it's harder to move quickly and keep the individual component parts light and shedding legacy.

Right now, we're trying to have it both ways: introduce breaking changes, but not bump versions.

**Comment by nex3** [comment]
I'd love to see the SDK start revving its major version semantically, but I think assessing breaking changes in terms of the pain they're likely to cause versus the difficulty of making them non-breaking is an acceptable short-term solution. This change is easy to avoid and causes a lot of pain, but some other breaking changes—like updating the VM service protocol—are harder to avoid and less likely to cause pain.

**Comment by mit-mit** [comment]
Florian fixed this: https://github.com/dart-lang/sdk/commit/be025b841211c5589f162e206160e656c81a8f83
