### ISSUE TITLE
Ability to express version constraints on packages that you do not depend upon

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#24800]
It would be useful if you could express a version constraint on a package that you don't directly depend upon.

**Comment by sethladd** [comment]
Detailing a scenario here might help.

Regardless, we should move this to the pub issue tracker.

**Comment by johnmccutchan** [comment]
This version constraint would interact with any of your transitive dependencies or if your package itself is being consumed by another package.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/pub#1356
