### ISSUE TITLE
The second argument to Dart_Initialize is incorrectly documented

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/sdk#24804]
**Summary:**
The second argument to `Dart_Initialize` is the instructions snapshot. The documentation states that this must be *"A buffer containing a snapshot of precompiled instructions, or NULL if no snapshot is provided."*. However, it is expected that the caller pass the symbol address instead. This is unlike the similarly documented argument `vm_isolate_snapshot`.

**Proposed Resolution:**
The documentation updated to reflect expected use and the the argument changed to read something like `const uint8_t** instructions_snapshot`

*or*

The implementation should do the extra dereference to match documentation. Callers would need to modify their code. But at this point, that should only be `flutter/engine`.

**Comment by rmacnak-google** [comment]
There's no extra deference of instructions_snapshot versus vm_isolate_snapshot happening in the VM. I think the difference is the instruction snapshot assembly creates an inline buffer, but you created a pointer to a buffer for the vm isolate snapshot in C.

==instructions.S==
.globl kInstructionSnapshot
kInstructionSnapshot:
   .long 0xAABBCCDD

==vmisolate.c==
char vmisolatesnapshot[] = { 0xAA, 0xBB, 0xCC, 0xDD };
char* vmisolatesnapshotp = vmisolatesnapshot;


#include <dlfcn.h>
#include <stdio.h>

void main() {
  void *lib = dlopen("libfoo.so", RTLD_NOW);
  printf("lib %p\n", lib);

  int* instructions = (int*)dlsym(lib, "kInstructionSnapshot");
  printf("instructions %p\n", instructions); 
  printf("*instructions %x\n", *instructions);

  int* vmisolate = (int*)dlsym(lib, "vmisolatesnapshot");
  printf("vmisolate %p\n", vmisolate);
  printf("*vmisolate %x\n", *vmisolate);

  int** vmisolatep = (int**)dlsym(lib, "vmisolatesnapshotp");
  printf("vmisolatep %p\n", vmisolatep);
  printf("*vmisolatep %p\n", *vmisolatep);
  printf("**vmisolatep %x\n", **vmisolatep);
}

lib 0x1776030
instructions 0x7f74c08946c5  << Dart_Initialize wants this
*instructions aabbccdd
vmisolate 0x7f74c0a95030  << Dart_Initialize wants this
*vmisolate ddccbbaa
vmisolatep 0x7f74c0a95038
*vmisolatep 0x7f74c0a95030  << Dart_Initialize wants this
**vmisolatep ddccbbaa
