### ISSUE TITLE
[JS interop] "window." doesn't work in Dartium

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#24817]
I am using the new JS Interop. I tried to access the `foo` property of the `window` object with the following code:

```dart
@JS("window.foo")
external List<Function> get foo;
```

When I `pub serve` my dart application and access it in dartium, I am getting the following error:
```
Class 'Window' has no instance method '[]'.
NoSuchMethodError: method not found: '[]'
Receiver: Instance of 'Window'
Arguments: ["foo"]
```

When I remove the `window.` from the annotation, everything works as expected. However, I would still expect it to work with the `window.` as well since that is where this property lives.

**Comment by jacob314** [comment]
Note. 
@JS("foo") works fine. The issue is automatically converting dom types in dart:html is messing up the dartium implementation for this case.

**Comment by mit-mit** [comment]
@jacob314 any news on this?

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by jacob314** [comment]
Fixed a while ago. Regression test checked in here:
https://github.com/dart-lang/sdk/commit/bcf224b3e68924a1d5a76659063256cb8e6f32d0
