### ISSUE TITLE
JsObject wrapper not present when compiled with dart2js

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#24816]
I'm seeing inconsistent behavior between Dartium and dart2js compiled code when using the latest js package.

Simplified example

```html
<script>
a = {
  data: "{}"
}
</script>
<script src="index.dart" type="application/dart"></script>
<script src="packages/browser/dart.js"></script>
```

```dart
import 'dart:js' as js;
import 'package:js/js.dart';

class A {
}

@JS()
external A get a;

void main() {
  print(a);
  print(a is js.JsObject);
}
```

Dartium produces
```shell
[object Object]
true
```

Chrome produces
```shell
Uncaught TypeError: J.getInterceptor(...).toString$0 is not a function
```

Another example which has function calls is at https://gist.github.com/donny-dont/0cebc2521abfb7f74b56

**Comment by a14n** [comment]
Actually there are 2 issues showed by this code:


1. there's an error in chrome after the dart2js compilation for `print(a)` altougth dartium outputs `[object Object]`
1. the result of `a is js.JsObject` is `true` in dartium but `false` in chrome after the dart2js compilation


```dart
void main() {
  // print(a); <- fails with dart2js with "Uncaught TypeError: J.getInterceptor(...).toString$0 is not a function"
  print(a is js.JsObject);
}
```

**Comment by jacob314** [comment]
js.JsObject, js.JsFunction, and js.JsArray
are not compatible with the new typed JS interop. 
Please do not attempt to use those classes in conjunction with the typed JavaScript interop as the results are unspecified.
Generally in Dartium, the two happen to be compatible but in Dart2Js they aren't at all compatible. For 1.14 it would not surprise me if js.JsObject stops being compatible with typed JavaScript interop under Dartium to reduce the confusion.

**Comment by donny-dont** [comment]
So what should the types be? Also how are you supposed to access them?

**Comment by donny-dont** [comment]
Oh got it now. It needs an anonymous JS object

```
@JS()
@anonymous()
class A {
  external String get data;
}
```
