### ISSUE TITLE
Directory.watch reports incorrect paths on Linux when symlinks are involved

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24815]
When a symlink and its target are both being watched using `Directory.watch`, it reports incorrect paths. In particular, both streams report one of the paths (it's not clear which one is selected or why). For example:

``` dart
import 'dart:async';
import 'dart:io';

import 'package:watcher/watcher.dart';

main() async {
  if (new Directory("dir").existsSync()) {
    new Directory("dir").deleteSync(recursive: true);
  }

  if (new Link("link").existsSync()) new Link("link").deleteSync();

  new Directory("dir").createSync();
  new Link("link").createSync("dir");

  new Directory("link").watch().listen((event) => print("link: $event"));
  new Directory("dir").watch().listen((event) => print("dir: $event"));

  await new Future.delayed(new Duration(seconds: 1));

  new File("dir/file.txt").writeAsStringSync("");
}
```

This creates a directory and a link to that directory, watches both, and adds a file to the directory. On my machine, it prints:

```
link: FileSystemCreateEvent('link/file.txt')
dir: FileSystemCreateEvent('link/file.txt')
link: FileSystemModifyEvent('link/file.txt', contentChanged=true)
dir: FileSystemModifyEvent('link/file.txt', contentChanged=true)
```

Note that all the paths begin with `link/`, even though some of them are coming from the watch on `dir`.

Talking to @johnmccutchan, our house expert on inotify, it sounds like the wrapper—`Directory.watch()`—is expected to track the paths that correspond to given watches. A single inotify watch ID may correspond to multiple paths on disk, because inotify watches inodes, not paths. The watcher should remember _all_ paths that are watched for a given inode and ensure that each of them gets events with paths resolved correctly.

**Comment by nex3** [comment]
This also occurs for `File.watch()`.

**Comment by johnmccutchan** [comment]
I just looked at the usage of inotify in file_system_watcher_linux.cc is pretty bugged.

Using inotify to monitor paths is complex with many edge cases. 

An implementation I wrote in 2005 for reference: https://github.com/GNOME/glib/tree/master/gio/inotify
