### ISSUE TITLE
Please merge revision 7ea2b300f12ad115d5eb70200055f24e173c7c50 and c34b23ccfe35b9e623d1f9367ae590e8a6798302 into dev channel

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#24811]
@whesse @mit-mit @kasperl

Change log updates.

https://github.com/dart-lang/sdk/commit/7ea2b300f12ad115d5eb70200055f24e173c7c50 
https://github.com/dart-lang/sdk/commit/c34b23ccfe35b9e623d1f9367ae590e8a6798302

**Comment by whesse** [comment]
This was merged in 1.13.0-dev.7.8
