### ISSUE TITLE
layout test for inspector failing after restoring dart:profiler library

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24824]
One of the webkit layout tests for the inspector in dartium is failing after we restored the dart:profiler library.  The commit restoring the library is https://github.com/dart-lang/sdk/commit/be025b841211c5589f162e206160e656c81a8f83

The failing test is
Starting 1 worker ...
[1/1] dart/inspector/scope-variables.html failed unexpectedly (text diff)

and the command to run the tests (which will need to be modified when not run on the build slave) is
python /Volumes/data/b/build/slave/dartium-mac-full-be/build/src/webkit/tools/layout_tests/run_webkit_tests.py  --no-show-results --time-out-ms 30000 --builder-name BuildBot --additional-env-var DART_FLAGS=--enable_type_checks --warning_as_error --additional-env-var DART_PACKAGE_ROOT=file:///Volumes/data/b/build/slave/dartium-mac-full-be/build/src/out/Release/packages dart

**Comment by whesse** [comment]
Boosting the priority to high - either suppress it in the status file, or fix it.

**Comment by terrylucas** [comment]
Reverting the CL caused profiler to appear again in the stack trace.
Changed the expected output for scope-variables I've committed the change
to WebKit  see CL https://codereview.chromium.org/1421553011/

**Comment by whesse** [comment]
Thanks!  Also push this to our Webkit branch for stable 1.13 - see comments on CL.
