### ISSUE TITLE
Support checked mode type tests on JSInterop functions in dart2js

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#24822]
1.14 as instructions for 1.13 are to not use dart2js checked mode with JS interop.

**Comment by kevmoo** [comment]
@jacob314 are we tracking this for 1.14?

**Comment by jacob314** [comment]
This should move to 1.15 or perhaps later. I really don't think there is much value in dart2js checked mode. checked mode is mainly a development time feature useful in dartium and dev compiler.
