### ISSUE TITLE
New test js_function_getter_trust_types failing on dev channel.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24828]
The test html/js_function_getter_trust_types_test is failing on the dev channel.  The test was introduced in commit https://github.com/dart-lang/sdk/commit/d0f456a910675bab3b47b80fddf1fda5ee9b7fa8.

**Comment by sigmundch** [comment]
@whesse - It seems that the test is now enabled on the dev channel. Is this bug still applicable or can we close it?

**Comment by whesse** [comment]
Dev channel is now 1.14, so the issue is stale.  A full push of bleeding-edge to dev has happened since this was filed.
