### ISSUE TITLE
If a class Foo has a constructor named bar, warn when calling Foo.bar()

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24836]
The following code:

```dart
   Foo foo = Foo.bar()
```
...leads to analyzer errors to the effect that there's no such static method as Foo.bar(). When there's a constructor with that name, we should add a hint to the effect that maybe you forgot the "new".

**Comment by sethladd** [comment]
Love the idea. Anything we can do to nudge our users in the right direction is a win. I love the idea of not just saying "you're wrong" but then also saying "maybe you wanted..."

cc @pq

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1407903011/

**Comment by sethladd** [comment]
Nice! Thanks for the helpful message :)
