### ISSUE TITLE
Inconsistent behavior of NaN negation on mips vs simmips

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24830]
From MIPS builder:

FAILED: none-vm release_mips corelib/nan_infinity_test/01
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.isFalse(true) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.isFalse (package:expect/expect.dart:120:5)
#2      main (file:///b/build/slave/vm-mips-release-be/build/sdk/out/ReleaseMIPS/generated_tests/corelib/nan_infinity_test_01.dart:57:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Command[vm]: DART_CONFIGURATION=ReleaseMIPS out/ReleaseMIPS/dart --ignore-unrecognized-flags --package-root=out/ReleaseMIPS/packages/ /b/build/slave/vm-mips-release-be/build/sdk/out/ReleaseMIPS/generated_tests/corelib/nan_infinity_test_01.dart
Took 0:00:01.864000

Short reproduction command (experimental):
    python tools/test.py -mrelease -amips --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t240 corelib/nan_infinity_test/01

FAILED: none-vm release_mips corelib/nan_infinity_test/none
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.isFalse(true) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.isFalse (package:expect/expect.dart:120:5)
#2      main (file:///b/build/slave/vm-mips-release-be/build/sdk/out/ReleaseMIPS/generated_tests/corelib/nan_infinity_test_none.dart:57:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Command[vm]: DART_CONFIGURATION=ReleaseMIPS out/ReleaseMIPS/dart --ignore-unrecognized-flags --package-root=out/ReleaseMIPS/packages/ /b/build/slave/vm-mips-release-be/build/sdk/out/ReleaseMIPS/generated_tests/corelib/nan_infinity_test_none.dart
Took 0:00:02.061000

Short reproduction command (experimental):
    python tools/test.py -mrelease -amips --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t240 corelib/nan_infinity_test/none

FAILED: none-vm release_mips language/nan_identical_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.isFalse(true) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.isFalse (package:expect/expect.dart:120:5)
#2      main (file:///b/build/slave/vm-mips-release-be/build/sdk/tests/language/nan_identical_test.dart:25:12)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Command[vm]: DART_CONFIGURATION=ReleaseMIPS out/ReleaseMIPS/dart --optimization-counter-threshold=4 --ignore-unrecognized-flags --package-root=out/ReleaseMIPS/packages/ /b/build/slave/vm-mips-release-be/build/sdk/tests/language/nan_identical_test.dart
Took 0:00:05.057000

Short reproduction command (experimental):
    python tools/test.py -mrelease -amips --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t240 language/nan_identical_test

**Comment by fsc8000** [comment]
@zanderso Not sure, if it is specified how -nan should look like, but we should just be consistent between optimized/unoptimized code and simulator vs hardware.

**Comment by lrhn** [comment]
Seems related to #23563

**Comment by rmacnak-google** [comment]
MIPS is no longer supported.
