### ISSUE TITLE
html/mediasource_test supported and failing on Firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24838]
The new version 42 of Firefox supports mediasource, and so the test
html/mediasource_test/supported is passing, and the test
html/mediasource_test/functional is failing with a runtime error.

This is currently happening on Windows, since the linux bots are on version 41.
The error is

`</tr>      <tr>
                            <td>3</td>
                            <td class="unittest-fail">
                              FAIL
                            </td>
                            <td>
                              <p>Expectation: 
                                <a href="#testFilter=functional media types">
                                  functional media types
                                </a>.
                              </p>
                              <pre>Expected: &lt;true&gt;
                      Actual: &lt;false&gt;
                    </pre>
`
Also, according to the status file, 
"# Firefox Feature support statuses-"
"# All changes should be accompanied by platform support annotation changes."

There is no info about where these annotations are, that should be changed.

**Comment by alan-knight** [comment]
Presumably the annotations refers to the @SupportedBrowser class annotations, e.g. https://api.dartlang.org/1.12.2/dart-html/MediaSource-class.html
