### ISSUE TITLE
Dartanalyzer: wrong warning about interface inheritance

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24844]
Dartanalyzer produces warning on the following code:
```dart
abstract class SI1 {
  int m1(int v1);
  int m2(int v1);
}

abstract class SI2 {
  bool m1(int v1);
  bool m2(int v1);
}

abstract class SI3 {
  Object m1(num v1);
  void m2(num v1);
}

abstract class I implements SI1, SI2, SI3 {
}

main() {
}
```
[warning] 'm2' is inherited by at least two interfaces inconsistently, from (int) -> int, (int) -> bool
And there are no warning about m1. But according "19.5 Function Types" of the Dart specification (3-rd edition, June 2015) void is a subtype of any type

"A function type (T1, . . . Tk, [Tk+1 . . . , Tn+m]) ! T is a subtype of the function
type (S1, . . . , Sk+j , [Sk+j+1 . . . , Sn]) ! S, if all of the following conditions
are met:
1. Either
• S is void, Or
• T () S.
2. 8i 2 1..n, Ti () Si."

So, there should be no warning (as well as for m1)

**Comment by bwilkerson** [comment]
I believe that you have the order of the methods backwards. The effect of this rule is that a method with a return type of `void` can be overridden by a method with a non-`void` return type, but a method with a return type of `void` cannot override a method with a non-`void` return type. Consider the following example:

    class A {
      int m1() => 0;
      void m2() {}
    }

    class B extends A {
      void m1() {} // not valid
      int m2() => 0; // valid
    }
