### ISSUE TITLE
constructor tear-offs should be considered const

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#24845]
A class's constructor is basically a static method and static methods are considered const,
yet the compiler doesn't consider a constructor tear-off to be a const.  Example:

``` dart
class A {
  static A constructor() => new A();
}

void main() {
  const f = A.constructor;  // Compiler is ok with this.
  const g = new A#;  // Compiler hypocritically complains that new A# is not a const,
         // even though it's basically the same as A.constructor.
}
```

This is annoying because I would like to use such tear-offs in Angular2 bindings:

``` dart
class SingletonBinding extends Binding {
  final Function constructor;
  const SingletonBinding(this.constructor, ...) : super(...);
}
// In the DI configuration...
const myBindings = const [
  // Doesn't work just because Dart is silly and doesn't
  // recognize new MyService# as a const.
  const SingletonBinding(new MyService#, ...),
];
```

I don't see how such a tear-off can capture variables from the surrounding context the way
arbitrary closures can, so can they just be considered const?

**Comment by lrhn** [comment]
They definitely *can* be considered const. The simple rewrite is to create a static function calling the constructor:
   static _Foo(x, y) => new Foo(x, y);
and using `_Foo` instead of `new Foo#`. That's basically what the `#` notation should mean anyway, so it would make sense if it was itself const.

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.
