### ISSUE TITLE
Please merge revision #TBD into dev channel

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24842]
@whesse @mit-mit @kasperl @dgrove 
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
Works around a Dartium crash from isolates being shutdown without being properly started.
Fixes a test expectation that was broken by the re-inclusion of dart:profiler.

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
Note: These are Webkit revisions
svn://svn.chromium.org/blink/branches/dart/dartium@202696 - https://codereview.chromium.org/1428333002
svn://svn.chromium.org/blink/branches/dart/dartium@202696 - https://codereview.chromium.org/1421553011

And then the corresponding update to tools/deps/dartium.deps/DEPS

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
I'm quite sure this will merge cleanly :-)

**Comment by whesse** [comment]
Merged in 1.13.0-dev.7.10
