### ISSUE TITLE
Isolate.spawn should not reload scripts for every new isolate.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#24849]
We are using one dart process which spawns up to 32 isolates, each of which is running effectively the dart2js/fletchc compiler. We have observed that the main isolate is basically **blocked for up to 16 seconds** thereby not being able to process any events inside the event loop.

Debugging this revealed that `Isolate.spawn()` - even though it is documented to return a `Future` does a native call which can take **0.5 seconds**. So spawning 32 isolates will do 32 native calls to `Isolate_spawnFunction` which takes then **16 seconds** for us: 

``` dart
// Effectively this:
var futures = [];
for (int i = 0; i < 32; i++) {
  futures.add(Isolate.spawn(compilerEntrypoint));
}
await Future.wait(futures);
```

After more debugging it turns out that
- `Isolate.spawn` is blocking and not spawning in the background
  => This is a serious issue. In an event based system, one simply cannot do long blocking calls. The loading of an isolate should happen in the background, allowing the main thread to continue to run. 
- `Isolate.spawn` is loading dart source code for each isolate
  => This is redundant work (loading/tokenizing/parsing/compiling over and over again) and it would be nice to eliminate this unnecessary work.

Almost all of these **500 ms** is spend [running a new event loop which loads sources](https://github.com/dart-lang/sdk/blob/master/runtime/bin/main.cc#L813).

@iposva-google 

@peter-ahe-google @madsager

**Comment by a-siva** [comment]
@turnidge

**Comment by turnidge** [comment]
I have an old cl that addresses this by moving more of isolate spawning to a separate thread.  It had to be rolled back because of bad interactions with dartium.  I will revive the change -- Dartium is a lot different now.

**Comment by turnidge** [comment]
I have committed change 71b3d5aba894daeaf04165f10f0fd302251d6b4a which makes spawning occur in the background.

I am leaving this bug open to track the other half of the bug report: specifically that we reload dart source in every new isolate.  I am also updating the bug title to fit that.

@a-siva

**Comment by mkustermann** [comment]
This is awesome and will help us a lot: Thank you :)

**Comment by peter-ahe-google** [comment]
As far as I can tell after running some experiments, this fixes our problems.

**Comment by nex3** [comment]
Unless I'm mistaken, I think this is a duplicate of #6610.

@turnidge Does 71b3d5aba894daeaf04165f10f0fd302251d6b4a also make #12617?

**Comment by a-siva** [comment]
Yes the second half is a duplicate of https://github.com/dart-lang/sdk/issues/6610.

Add a test here to spawn an isolate using a URI that is served by the spawning isolate and ensure there is no deadlock.

**Comment by mkustermann** [comment]
The VM spawns isolate in the background does not re-read the source code anymore afaik. Marking this issue a stale.
