### ISSUE TITLE
[js interop] Passing Dart lists between multiple dart apps doesn't work

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#24843]
I have two dart apps on the same page and use the new JS interop to pass a Dart list between them. This doesn't work and the second app processing the dart list sees the following exception:

```type 'JsObjectImpl' is not a subtype of type 'List<StabilizeFunction>' of 'function result'.```

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by jacob314** [comment]
This now works but the issue wasn't closed.
