### ISSUE TITLE
Please, clarify the specification for asynchronous for-in loop

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24859]
In the issue #24854 it was discovered that Dart Programming Language Speciﬁcation version 1.9 should be updated in chapter 17.6.3 Asynchronous For-in. The statement 

> Let u be the stream associated with the immediately enclosing asynchronous
> for loop or generator function (9), if any. If another event e u of u occurs before
> execution of s is complete, handling of e u must wait until s is complete.
- should not mention generator function, because there are actually no restrictions on the events of a generator function. (See https://github.com/dart-lang/sdk/issues/24854#issuecomment-155008017 )
- add explicit restriction, that body of any asynchronous loop is not reentrant, and all events are handled sequentially one by one. (see https://github.com/dart-lang/sdk/issues/24854#issuecomment-155000730 and https://github.com/dart-lang/sdk/issues/24854#issuecomment-155008017 ).

**Comment by anders-sandholm** [comment]
@gbracha
