### ISSUE TITLE
Null-aware method invocation results in: unexpected token "."

### ISSUE THREAD

**Issue by davenotik** [dart-lang/sdk#24853]
Dart SDK 1.12.2
Running in Dartium

```
...
  Map encode() {
    return {
      "user": user,
      "type": type,
      "createdDate": createdDate.toString(),
      "updatedDate": updatedDate.toString(),
      "url": url,
      "siteUrl": siteUrl,
      "lastCrawledDate": lastCrawledDate?.toString()
    };
  }
...
```

Error:

```
Uncaught 'package:woven/src/shared/model/feed.dart': error: line 24 pos 42: unexpected token '.'
      "lastCrawledDate": lastCrawledDate?.toString()
```

**Comment by zoechi** [comment]
Works fine here https://dartpad.dartlang.org/0bd773c3c2176cb5fa91

**Comment by davenotik** [comment]
@zoechi indeed, seems to work for me in DartPad too with a simple test.

https://dartpad.dartlang.org/d496f173c18651fa4888

But Dartium throws an error. Have you tried there?

**Comment by Bluenuance** [comment]
same issue here (also Dart 1.12.2 - using WebStorm 11)

obj?.sendMessage(message);
running using Dartium: 
error: line 53 pos 21: unexpected token '.'
  obj?.sendMessage(message);

**Comment by alan-knight** [comment]
Seems fine in 1.15.
