### ISSUE TITLE
quick fix create method doesn't create named params

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24865]
When quick fixing the following code (method used but not declared):
```
      tryToAutoConfigure(complainOnFailure: false);
```

it creates the following method declaration:

```
  void tryToAutoConfigure(bool arg0) {
  }
```

Where, it should create something like:
```
  void tryToAutoConfigure({bool complainOnFailure}) {
  }
```

@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1475743003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/6859412facdf673013820715723305313fba5c53
