### ISSUE TITLE
Cannot reference undefined label 'xyz'

### ISSUE THREAD

**Issue by jkleiser** [dart-lang/sdk#24867]
dartanalyzer gives the error message "Cannot reference undefined label" depending on what comes just after the label in question. The following sample code is quite meaningless, but if I remove the print line just after "whynot:", then the error message goes away.
```
void strange() {
whynot:
  print("Why does this line cause _Cannot reference undefined label 'whynot'_?");
  for (int i = 0; ;) {
    break whynot;
    print("$i");
  }
}

void main() { print("whynot?"); }
```

I'm using Dart VM version: 1.12.2 (Wed Oct 21 06:56:12 2015) on "macos_x64".

**Comment by bwilkerson** [comment]
The only purpose for labels is to be used in a `break` or `continue` statement. The `break` and `continue` statements can only transfer control to a `do`, `for`, `while` or `switch` statement. Therefore, labels on any other statement can never be referenced. The error message clearly needs to be improved, but the error is real.

Change your main to invoke `strange()` and try running the code. The VM will report:

    'file:.../test.dart': error: line 20 pos 5: label 'whynot' not found
        break whynot;
        ^
