### ISSUE TITLE
Analyzer: No type check for functions taken from hashmap

### ISSUE THREAD

**Issue by Gen8** [dart-lang/sdk#24869]
I am using strong mode.
I do not have write permission to attach a file. Therefore I copy the test code hereunder:

import "dart:collection";

class C {

	F f;
}

typedef String F(C c);

void main () {

	Map<String, F> functions = new HashMap();
	functions.putIfAbsent("hello", () => (C c) => "a");

	for(var key in functions.keys){
			functions[key]();
	}

}

**Comment by leafpetersen** [comment]
I think this is the same bug as https://github.com/dart-lang/sdk/issues/25349 .  The analyzer doesn't currently do any argument checking for function expression applications.

**Comment by leafpetersen** [comment]
This is fixed in bleeding edge ( @jmesserly  fixed).
