### ISSUE TITLE
Chrome can no longer connect to dart:io WebSocket servers

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#24864]
WebSocket connection to 'ws://localhost:8181/ws' failed: Error during WebSocket handshake: Error in permessage-deflate: client_max_window_bits must have value

This is breaking Observatory.

@sgjesse

**Comment by sethladd** [comment]
cc @kaendfinger

**Comment by johnmccutchan** [comment]
Observatory doesn't work for me in Chrome 47.

**Comment by johnmccutchan** [comment]
I was able to work around the issue by landing the following patch:

https://codereview.chromium.org/1430333002/

**Comment by kaendfinger** [comment]
We will look into this ASAP. Looks like a simple issue to fix, just as a note.

**Comment by sgjesse** [comment]
It would be great if we can have real browser tests of this.

A short term solution could be to add tests where the exact headers that Chrome, IE, Firefox and Safari are sending is used.

**Comment by butlermatt** [comment]
As @kaendfinger mentioned, this is an easy fix. It appears to be an implementation detail with Chrome. The spec doesn't specify that if chrome sends `client_max_window_bits` without specifying a value, that the server must specify a value, but that's the behaviour Chrome is expecting. An easy solution is when no `client_max_window_bits` is specified, we'll send back the default value for it. I'll have a CL for this shortly.

**Comment by johnmccutchan** [comment]
How do we know that IE, Firefox, etc do not have issues?

**Comment by butlermatt** [comment]
Patch in: https://codereview.chromium.org/1437623002/

The dart sdk test suit is passing and I've manually tried testing this patch in Firefox, Chrome, Safari and IE (Edge). Safari was unable to be verified due to issues with Polymer. However both Chrome and Firefox enable compression and IE does not request compression so it works without compression enabled.

**Comment by sgjesse** [comment]
The fix landed in bcd7466b562e1ac873e9a7309ca95eb9b84f723e, @johnmccutchan could you try to turn on WebSocket compression for the observatory again?

**Comment by johnmccutchan** [comment]
@sgjesse The VM service protocol is mission critical. We will not be turning on WebSocket compression for it until we are certain that the compression code is compatible with all existing web socket clients / browsers.
