### ISSUE TITLE
type 'NodeList' is not a subtype of type 'List<Element>' of 'directChildren' when debugging in IntelliJ

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24868]
This line: https://goo.gl/UjFEkY produces the above error message but only while debugging this module in IntelliJ 15
![screenshot-1922](https://cloud.githubusercontent.com/assets/116654/11064366/25d7a202-87bd-11e5-9a60-e77ae9a82912.png)

It works in all other cases - Chromium/Dartium VM + dar2js Version

**Comment by alan-knight** [comment]
Are you running it in checked mode in any of the other cases? That message seems correct, in that NodeList is not a List<Element>, it implements List<Node>. And the return type of childNodes is List<Node>, so assigning it to List<Element> is not valid.

**Comment by iposva-google** [comment]
As @MikeMitterer said this properly works on Dartium/VM unless used by IntelliJ 15. Not sure what IntelliJ's debugger is doing in this case. Eric?

**Comment by mit-mit** [comment]
@clayberg can you comment on Ivan's question above?

**Comment by bwilkerson** [comment]
The error is occurring at run-time, not during analysis.

**Comment by jwren** [comment]
Which version of Dartium/ IntelliJ are you using?  Will go look at the flags that we are passing in (not sure of even a flag that exists that enables such behavior.)

- Jaime

**Comment by MikeMitterer** [comment]
Im using 
IntelliJ IDEA (Minerva) IU-143.870.1
Build #IU-143.870, built on November 18, 2015
JRE: 1.8.0_40-release-b92 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

and Chromium Version 39.0.2171.0
Since dart 1.13 this is also a problem in Dart2JS - its ok that this is an error but dartanalyzer should warn me about this and not just crash in test or in dart2js.

**Comment by bwilkerson** [comment]
@kasperl Not sure why you added the "area-analyzer" label to this issue. It appears to me to be an interaction between IntelliJ and Dartium, having nothing to do with the analyzer. I think we should either move it out of the 'sdk' issue tracker or create a new "area-IntelliJ" label for such issues.

**Comment by terrylucas** [comment]
Please re-test with Dart 1.24.2 Stable (Dartium 50).
