### ISSUE TITLE
myvar ?? ( throw new ArgumentError("Test")) produces "Internal error: ... unexpected token '?'

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24879]
Dartanalyzer does not complain but DartVM crashes.

This works:
```dart
myvar != null ? "" : (throw new ArgumentError("Test"));
```

**Comment by lrhn** [comment]
Does not reproduce for me as  a stand-alone example:
```
main() {
  var x;
  x ?? (throw new ArgumentError("NOooooooooooo....!"));
}
```

Which version of the Dart VM are you using? (You can run "dart --version" to see the version).
I'm on version: 1.13.0-edge.9cfba28da17a951c7f2da5d810ff8be7f8004b80 (which is somewhere around tip of tree).

**Comment by MikeMitterer** [comment]
dart --version
Dart VM version: 1.13.0-dev.7.10 (Fri Nov  6 01:48:28 2015) on "macos_x64"

And it crashes in Chromium
```dart
null ?? (throw new ArgumentError("Test Exception"));
```
brings
```
 Internal error: 'package:mobiad_rest_ui_mdl/components/Connections.dart': error: line 154 pos 15: unexpected token '?'
        null ?? (throw new ArgumentError("Test Exception"));
              ^
```

**Comment by MikeMitterer** [comment]
Ohhh - forgot: I'm using Chromium Version 39.0.2171.99

**Comment by MikeMitterer** [comment]
Uhhhh - that did the trick! For whatever reason OSX started an old version of Chromium for me!!!! I wasn't aware that this old version was on my machine. It was only the case when the system started the browser for me - manually, I got the right one. Sorry for the confusion!
