### ISSUE TITLE
autofocus is missing from standard html5 attributes

### ISSUE THREAD

**Issue by sorenbronsted** [dart-lang/sdk#24870]
I keep getting 'Removing disallowed attribute <INPUT autofocus="">' when using setInnerHtml with default nodevalidator and when I look for autofocus in _Html5NodeValidator._standardAttributes it is missing.

**Comment by alan-knight** [comment]
Should be easy enough.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1588773002

**Comment by mit-mit** [comment]
@alan-knight , looks like the CL landed; can we close this issue? Also, do we need to cherry pick this into 1.14?

**Comment by alan-knight** [comment]
Yes, was going to close it once I put in the cherry-pick.

**Comment by alan-knight** [comment]
Cherry-pick to 1.14 is https://github.com/dart-lang/sdk/issues/25505
