### ISSUE TITLE
execution.mapUri doesn't on Windows for dart:* uris 

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#24873]
From Alex: Breakpoints in SDK files do not work for me because execution_mapUri(1, "C:\dart\dart-1.14-fake\lib\core\print.dart", null) returns file:///C:/dart/dart-1.14-fake/lib/core/print.dart instead of dart:core/print.dart. Server bug?

Source:https://github.com/JetBrains/intellij-plugins/pull/298#issuecomment-155445301

**Comment by scheglov** [comment]
https://codereview.chromium.org/1457643002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/4ed3afeb5edac86fd2afc2cb3a23d6f83533b253
