### ISSUE TITLE
VM allows tear-offs from prefix objects.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24877]
@gbracha 

The VM allows the following program:

```
import "samefile.dart" as prefix;
main() {
   print(prefix#main);
}
```

The specification requires this program to be a compile-time error due to section 16.33 "Identifier Reference" stating: 

> if d is a prefix p, a compile-time error occurs unless the token immediately following d is ’.’.

On the other hand, the functionality is useful since its the only way to tear-off a top-level getter or setter.

Gilad: What is the intention here?

**Comment by gbracha** [comment]
That sentence predates the # operation and was overlooked when the change was made. Section 16.8.3 explicitly discusses the use of prefixes and #.  I'll fix it.

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.
