### ISSUE TITLE
Null aware access operators don't support maps.

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#24872]
If I try to access a map value of a possibly null class, it will blow up.
Sample code:
```dart
void main() {
  // "if null" operator
  print(null ?? 'New in Dart 1.12');
  
  // null-aware method invocation
  var isNull = null;
  print(isNull?.foo()); // Works
  print(isNull?.foo['test']); // Blows up
}
```
Dartpad:
https://dartpad.dartlang.org/0593a864be7d75cd2da1

Dart2JS produces this obscure error:
`Uncaught TypeError: C.JSNull_methods.$index is not a function`

In the VM it's much more clear what is happening:
`The null object does not have a method '[]'`

This occurs with Dart 1.12.2 and bleeding_edge

**Comment by sethladd** [comment]
What happens on the VM?

**Comment by butlermatt** [comment]
`The null object does not have a method '[]'`

**Comment by sethladd** [comment]
ah, thanks!

**Comment by srawlins** [comment]
I don't see the bug.

Looking at your statement, `isNull?.foo['test']` first evaluates `isNull?.foo` ([null-aware access](http://news.dartlang.org/2015/08/dart-112-released-with-null-aware.html)), which evaluates to null. Then it evaluates `null['test']`, but `The null object does not have a method '[]'`.

I think maybe you are expecting [null-aware map lookup](https://groups.google.com/a/dartlang.org/forum/#!searchin/misc/null/misc/JFtKXzUlgKA/VrX_H_sbAQAJ)?, like `isNull?.foo?['test']`, which is not a thing.

**Comment by butlermatt** [comment]
I suppose I am expecting the null-aware map lookup, but without the extra null check. I guess that comes down to not anticipating [] as an operator. 
Thanks for the reference to that discussion, I hadn't noticed it previously.

**Comment by jaysephjw** [comment]
Null aware map lookup would be a great feature to have built in, e.g. when destructuring json into objects.

The linked thread mentions adding `get` and `add` methods to map, since null aware access exists, allowing `name = json.get('attributes')?.get('name')`. 

I plan to work around by adding `get` and `add` on Map via extension method.

**Comment by eernstg** [comment]
Just FYI, the following program works fine when the not yet released non-null-by-default feature (aka NNBD) is turned on:

```dart
main() {
  Map? map = null;
  map?.[3] = "Unused";
  print(map?.[3]);
}
```

So 'closed-as-intended' was true in 2015, but things have been moving since then and the null-aware index operators will be available along with NNBD.

**Comment by tarobins** [comment]
It seems the syntax for the null aware map accessor landed on 

```
void main() {
  Map? map = null;
  map?[3] = "Unused";
  print(map?[3]);
}
```

(i.e. no `.` after the ?)  Just noting cause I found the above example when searching for the syntax.
