### ISSUE TITLE
RenderObject.layout seems to be taking more time than expected

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#24875]
In Flutter's layout_bench.dart, the profiler says we're spending a lot of time in RenderObject.layout, which is surprising because that's function's job is to just to check whether we can skip layout and (if not) call performLayout, which is the function that many subclasses override to do the actual layout work:

https://github.com/flutter/flutter/blob/master/packages/unit/benchmark/stocks/layout_bench.dart

The instructions for running the benchmark are in the README.md:

https://github.com/flutter/flutter/blob/master/packages/unit/benchmark/README.md

To make the benchmark easier to profile, you might want to set the `_kRunForever` flag to true.

/cc @iposva-google

**Comment by abarth** [comment]
Looking at the disassembly, there seems to be a lot of code for copying parameters into the function and a lot of mov instructions for calling performLayout (which doesn't take any arguments), at least on Intel.

**Comment by fsc8000** [comment]
I just landed https://github.com/dart-lang/sdk/commit/2783afd6072bd3937f0d3f1d99032f35a09de4be which - together with changing the layout() code to use a closure call for performLayout() - should improve layout_bench by around 7% (measured on Linux).

**Comment by abarth** [comment]
Thanks!

**Comment by fsc8000** [comment]
We implemented a number of optimizations to improve performance of the layout. Closing this as I see usually less than 5% time spent in the layout method when running layout_bench AOT compiled.

**Comment by abarth** [comment]
Awesome.  Thanks!
