### ISSUE TITLE
exporting to JS might need some name mangling

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24886]
_From @jmesserly on October 21, 2015 23:40_

I recall some issues when the Dart class has static methods that are banned in strict mode like "arguments" "caller" and "callee". Pretty obscure but might need name mangling to expose in JS.

_Copied from original issue: dart-lang/js-interop-experimental#198_

**Comment by kevmoo** [comment]
_From @jmesserly on October 21, 2015 23:40_

(filed as a tracking issue after a chat with @jacob314)

**Comment by kevmoo** [comment]
_From @jacob314 on October 21, 2015 23:50_

We're planning on using JS$ to mangle illegal JS names in dart. Perhaps we should use Dart$ to mangle Dart names

**Comment by jacob314** [comment]
Using Dart$ seems consistent with using JS$. Might be nice if we could think of a short prefix that could be used both ways but I can't think of one.

**Comment by matanlurey** [comment]
I think we've decided exporting to JS is not on the immediate roadmap.
