### ISSUE TITLE
RTE when using dart2js

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24887]
_From @frankpepermans on October 23, 2015 10:7_

Example:
Run all_tests.html from https://github.com/frankpepermans/rxdart/tree/master/test in both the Dart VM and as compiled to JS

- Dart VM: all tests pass
- Js: 3 'fail with invalid arguments' or 'method not found'

Using SDK 1.13.0-dev.7.2
Js: 0.6.0-beta-5

_Copied from original issue: dart-lang/js-interop-experimental#199_

**Comment by kevmoo** [comment]
@frankpepermans how are you running these? Are you using `pub serve test`?

**Comment by frankpepermans** [comment]
Hi @kevmoo 

Yes, using pub serve (with the 1.13 release)

**Comment by jacob314** [comment]
Closing as rxdart does not use JS interop and the bug description is vague.
