### ISSUE TITLE
Run dart2js_unit-vm tests only once

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#24883]
The tests 'dart2js_unit-vm tests' should only be run once. Currently the same tests are run under the 'dart2js', 'dart2js-checked' and 'dart2js' (cps) columns.

**Comment by whesse** [comment]
Yes, very good point.  I'll do this.

**Comment by whesse** [comment]
This is now done - the tests run only on the linux jsshell builders (and are sharded on them)

The recipe lines that do this start with:
    # Special hard-coded steps with compiler=none, run on selected runtimes
    if runtime == 'jsshell' and system == 'linux' and sharded:
      IsFirstTestStep = False
      api.python('dart2js unit tests',
