### ISSUE TITLE
dev-channel Dartium returns int where it previously returned double

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24882]
```dart
HtmlElement elem = ...;
var bcr = elem.getBoundingClientRect();
int top = (bcr.top as double).toInt()
```
This code now throws 
> Unhandled exception: type 'int' is not a subtype of type 'double'.

Is this intentional?

It would make my code shorter because I don't need to convert but it breaks my bwu_datagrid package.
It seems I need to change the code to check what type I get and then convert or skip it to make it work in 1.12. and 1.13.x-dev

**Comment by lrhn** [comment]
There is the option of doing `(bcr.top as num).toInt()`.

The `getBoundingClientRect` function returns a `Rectangle<dynamic>`. The `Rectangle` class is declared as `Rectangle<T extends num>`, so the result should be a `num`.

**Comment by zoechi** [comment]
Ah, didn't check close enough. So the type is `num` but the instance is now `int` but was `double` before.

**Comment by zoechi** [comment]
@lrhn thanks for your workaround, mine was needlessy verbose :-/.

**Comment by alan-knight** [comment]
The type was actually double before, but we changed it as part of updating Dartium to use JS-interop. JS doesn't distinguish between the two, and the JS-interop conversions will return an int if the JS number happens to be an int and a double otherwise.

**Comment by zoechi** [comment]
Ok, so what's left is to add this to the changelog to reduce surprises?

**Comment by alan-knight** [comment]
Good point.
https://codereview.chromium.org/1432143004/
