### ISSUE TITLE
corelib: Add growable parameter to List.filled constructor

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24884]
Just today I need to create a list with N copies of something and then add more elements.

I'd like to say  `new List.filled(N, something, growable: true)`.

Most of the List constructors have a growable: parameter, List.filled should too.

**Comment by lrhn** [comment]
Alternative:  `new List.generate(N, (_)=>something);` or `[]..length = N..fillRange(0, N, something)`.

The reason we decided that `List.filled` should not create growable lists was to avoid confusion. 
Users could assume that increasing the list's length would fill the new slots with the "fill" value as well, which it won't.

**Comment by lrhn** [comment]
Done.
