### ISSUE TITLE
Misleading warning for `?? throw`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24892]
The code `x ?? throw 0` gives the following errors:

```
ERROR|SYNTACTIC_ERROR|...file.dart|3|8|Expected to find ';'
ERROR|SYNTACTIC_ERROR|...file.dart|3|8|Expected an identifier
```

This is misleading since the real solution to the errors is to add parentheses around the `throw 0` expression. 
Listing what you expect to find is great, but it should be complete then, and '(' is also possible here.

**Comment by askeksa-google** [comment]
Will become a duplicate of https://github.com/dart-lang/sdk/issues/24891 when the analyzer integrates with the CFE.

**Comment by srawlins** [comment]
And so it is done. Duplicate of #24891.
