### ISSUE TITLE
await for loop unexpectedly terminates the program 

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24895]
Asynchronous for-in loop unexpectedly terminates the program.
The following code demonstrates the problem:
```
import 'dart:async';

Future test() async {
  StreamController<String> sc = new StreamController<String>();
  sc.add('a');
  sc.add('b');
  await for (String s in sc.stream){
    print("in loop: $s");
  }
  print("after loop");
  return "passed";
}

main() {
  print("test start");
  test().then((v) => print("test result: $v"))
    .then((v) => print("test finish"));
}
```
Expected output:
>test start
>in loop: a
>in loop: b
>after loop
>test result: passed
>test finish

Actual output:
>test start
>in loop: a
>in loop: b

Dart VM version: 1.12.2 (Wed Oct 21 07:10:52 2015) on "windows_x64"

**Comment by lrhn** [comment]
This is a known problem (see #23797) - your program has a deadlock. You are await-for'ing a stream that never terminates (there is no `sc.close()` call), so the loop waits forever for the next event to arrive.

Or rather, being slightly smarter than you would expect, the VM detects that there are no open ports, no scheduled timers and no waiting microtasks, and decides that the program is done, so it can shut down.

An async program is executed as a sequence of top-level events/microtasks triggered by previous work or outside influences. In this case the events are 

* main()
* event "a"
* event "b"

... and that's it. After that, there are no further events, and no without that, no way to introduce new events, so the VM closes down just as it would after a successfully run program. It doesn't distinguish between different reasons for running out of events.

**Comment by mhausner** [comment]
Closing since it's a duplicate.
