### ISSUE TITLE
Enhance the ExecutionDomain

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24893]
We'll need to discuss enhancements to the analysis server's ExecutionDomain. Right now it's essentially hardcoded to know about dart cli apps and dart web apps. We'll need to make this mechanism more flexible to cover application types that the analysis server may not be aware of.

For example, a project may have several dart libraries with `main()` methods. Some of these libraries may be regular dart CLI apps, and some may be flutter entry-points. Atom will need to launch these two libraries differently. The only way we'll be able to decide this is by looking at the transitive closure of the imported libraries for each entry-point.

This is similar to what's done for web apps (looking for `dart:html`). We'd recognize a flutter entry-point by the transitive import of `package:flutter`. We'll want a general purpose solution that lets clients self-serve when they need to support new launch types.

**Comment by floitschG** [comment]
Also note that configuration specific imports will make the transitive search become less reliable.

**Comment by devoncarew** [comment]
From discussion, we may be able to self-serve on this one, if we run a regex over the file with `main()`. We'd have to be ok with a ~low false negative rate.

**Comment by pq** [comment]
> From discussion, we may be able to self-serve on this one, if we run a regex over the file with main(). We'd have to be ok with a ~low false negative rate.

Is this sufficient or do we want an analysis query for the the transitive closure of imports?

**Comment by pq** [comment]
New `AnalysisDomain` request for the transitive closure of reachable sources in flight:

https://codereview.chromium.org/1491013002/

This should solve the specific problem for flutter (e.g., "is this a `flutter` entry-point?") but generalizes to other cases (like web apps, tests, and beyond).

**Comment by pq** [comment]
`AnalysisDomain.getReachableSrouces` request landed in 43f027fc05f25a40049dee0a71418570f6f20d10.

**Comment by devoncarew** [comment]
:metal:
