### ISSUE TITLE
Delete nuxeo_automation from pub

### ISSUE THREAD

**Issue by nelsonsilva** [dart-lang/sdk#24894]
I'd like to request deletion of nuxeo_automation from pub. A renamed and newer nuxeo_client package has already been published.

**Comment by zoechi** [comment]
This is published since 8/2013!
A better approach would be to publish another version of `nuxeo_automation`, with an updated README.md, pointing to `nuxeo_client` and a hint `nuxeo_automation` is deprecated, instead of removing the package.

**Comment by nelsonsilva** [comment]
:+1:  will do
