### ISSUE TITLE
analysis server stuck in a loop

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24902]
_From @jmesserly on November 5, 2015 21:19_

What seems to be happening: analysis_server kicks off, finishes, then immediately goes from IDLE back to analyzing, even though I'm not typing or changing anything.

Here's the "finer" console log from a few seconds of it looping. 120MB(!)
https://drive.google.com/a/google.com/file/d/0B1F3uma0zu_xSGU5bkdOS01RdnM/view
$ dart --version
Dart VM version: 1.13.0-dev.7.6 (Fri Oct 30 15:14:38 2015) on "macos_x64"

atom version: 1.10
dart plugin version: 0.4.13

_Copied from original issue: dart-atom/dartlang#493_

**Comment by devoncarew** [comment]
Thanks for the bug report! I'll have to create a new github label for bug reports greater than 100MB :)

The log contains responses from the AS to commands we're sending in. It doesn't contain the text for those commands however. I'll go over our logging code to make sure we're logging when we should. I suspect that those commands will be very interesting, either overlay changes, priority source changes, ...

The AS should not be causing re-analysis, but they'll probably want to know which commands are causing the re-analysis.

**Comment by devoncarew** [comment]
Hmm, we are logging commands to the server correctly, so I don't know why they're not showing up in your log.

**Comment by devoncarew** [comment]
We now trim very long messages from the AS when logging. The next version of the plugin should only create a log file ~200-300kb. Should be a lot easier for users and devs to dig through.

**Comment by bwilkerson** [comment]
Do we have any additional information about this?

@jmesserly Are you still seeing this behavior? If so, can you get updated log files?

**Comment by jmesserly** [comment]
Ah, I've been using IntelliJ lately. Let me update everything in Atom and give it another try.

**Comment by jmesserly** [comment]
(BTW, I never saw this problem in IntelliJ, only in Atom. Made me suspect a plugin issue vs Analysis Server issue.)

**Comment by bwilkerson** [comment]
Either that, or a bug in server when used the way Atom is using it.

**Comment by devoncarew** [comment]
The release of atom from last week now batches up file deltas. It send them to the server after a 400ms quiet period, or if any other analysis server call is about to be made. This should reduce the number of file deltas we send to the server by 3x-10x.

**Comment by jmesserly** [comment]
looks fixed to me :+1:

**Comment by jmesserly** [comment]
DOH, spoke too soon. It's back. It happened after a while. Let me see if I can find a way to reproduce it.

**Comment by jmesserly** [comment]
FWIW, it definitely seems a lot harder to reproduce than before. Before I could make it happen pretty consistently by editing class/member/top-level-field declarations in files like the old generated/element.dart file. Now I'm not sure what triggered it. I switched to "finer" logging though, so I can grab a log in case I manage to reproduce it.

**Comment by bwilkerson** [comment]
I'm guessing that this is no longer an issue.
