### ISSUE TITLE
Please merge two revisions into dev channel

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24903]
@whesse @mit-mit @kasperl

The first revision causes the analysis server to stop analyzing files inside a top-level 'doc' folder. Server analyzes HTML files to find embedded Dart scripts, but shouldn't analyze documentation files. This causes problems most commonly with packages that have generated dartdoc.

02fe5bcd5af7b25e0ff2fd73c751865b323baf85

The second revision causes more error information to be sent from the analysis server to clients where it will be logged. The expectation is that this will give us more information to help diagnose problems.

5b61845221b0d40f31edf5cfc2155e2253b2aa72

**Comment by dgrove** [comment]
Merged to dev 426edff01629bb92ac8e88f27ae25404c35f769b
