### ISSUE TITLE
Remove analysis server's use of the watcher package

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24916]
There are two problems with analysis server using the watcher package.

The first is that the watcher package processes the OS notifications in order to try to classify them as "add", "change" or "remove" events, but analysis server doesn't actually care about this classification and would actually be more reliable if we just got the raw OS notifications.

The second is that the watcher package is using large amounts of memory (modeling the file system) in order to be able to do this classification, and large amounts of processing time in order to maintain this model and perform the classification. Analysis server would be more efficient if we just got the raw OS notifications.

**Comment by dgrove** [comment]
I think you probably do want some abstraction. Otherwise, I'm not sure how you'll enable users to deal with their own network-mounted files.

**Comment by bwilkerson** [comment]
Agreed. Watcher just isn't the right abstraction as it stands today.

One possibility is to add support to the watcher package to access the low level events in such a way that we don't incur the overhead that watcher currently adds.

**Comment by mit-mit** [comment]
@bwilkerson, is anyone working on this?

**Comment by scheglov** [comment]
@nex3 @munificent 
Guys, what's the status of the `watcher` package?
Do you see ways to make it more reliable, use less memory and be faster?
What is the ETA - 1.14, 1.15, etc?

If this cannot be done, we will have to resort to lower level APIs.

**Comment by munificent** [comment]
> Do you see ways to make it more reliable, use less memory and be faster?

Definitely use less memory and be faster. I have a couple of patches out for that and some ideas (that we talked about a few days ago) to improve on that. Reliable... well, watching is generally pretty flaky.

> What is the ETA - 1.14, 1.15, etc?

Pretty soon. 1.14 is a good aim.

**Comment by scheglov** [comment]
You know what we mean under *reliable* :-)
False positives are OK, false negatives - not OK.

Glad to hear that it is moving forward!

**Comment by bwilkerson** [comment]
> Reliable... well, watching is generally pretty flaky.

To be clear, what we're asking for is only that it is as reliable as the underlying OS's support. There should never be a case when the OS informs the watcher package of a change and that change is not passed on to the server.

**Comment by bwilkerson** [comment]
@scheglov Where are we on this?

**Comment by scheglov** [comment]
If `Pub` does not generate `packages` folders, then `watcher` performance is acceptable.
I'm not aware about any specific examples when `watcher` misses notifications.

**Comment by mit-mit** [comment]
Clearing P1 flag as it's not clear this is that urgent (and nothing indicates it is being treated as such)

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bwilkerson** [comment]
At this point I think we're going to leave server depending on watcher at least until we have finished moving of or `packages` directories.
