### ISSUE TITLE
summary_test.dart is slow to compile; resulting executable appears to do nothing.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24914]
The test `pkg/analyzer/test/src/summary/summary_test` has been timing out on the Dart2js buildbot recently (see http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-1-5-be/builds/13173/steps/dart2js-d8%20tests%20--minified%20--dart2js-batch/logs/stdio).  @whesse has updated the status file to mark the test as slow (ebf8830dd2e9e2188288321e7afa5e23ce768bdb), which should fix the buildbot.  But I'm concerned that there may be a deeper issue.

When I run the test locally, dart2js compilation takes 30 seconds.  Then, if I attempt to run the resulting executable using d8, it quickly exits without generating any output at all.  If I introduce a deliberate failure into summary_test.dart, the behavior is unchanged.  By contrast, if I run the test using the VM, it outputs a chatty sequence of messages from the unittest package, and it correctly detects deliberately introduced failures.

This makes me suspect that I'm running into a dart2js compilation bug.

(Note that summary_test.dart is under active development; if this is a heisenbug and winds up disappearing, try reproducing at commit 6f734612022facc26b67e67761c154563e4f7916).

**Comment by whesse** [comment]
Are we certain that the analyzer test runs under d8?  If it depends on any dart:io stuff, to read files, for example, they are unsupported on dart2js, so the program would exit.

If it is supposed to run, and do all the tests, under dart2js, then I would do printf debugging in the test, to see which parts, if any, are actually running when you run the dart2js output.  I could imagine that we don't actually intend it to actually work correctly in dart2js, and are just using it to check the dart2js compiler for crashes.

**Comment by stereotype441** [comment]
I believe the test should run under d8, but I could be wrong.  What is the expected behavior if the program depends on any dart:io stuff?  (I thought dart2js was supposed to print out an error message during compilation in this case). What I'm seeing is that the program is exiting immediately with an exit code of 0 and no error/warning message.  If that's the intended behavior, it's a really poor user experience (especially in the case of unit tests, where an exit code of 0 will get mistaken for success).

I tried adding a `print('foo');` statement at the top of main, and there was no effect.  Then I tried deleting all other code in the file (with the exception of the library declaration and the import statements), and there was still no effect.  Then I tried commenting out import statements, and I found that if I commented out the following import statements, then the program printed out "foo":

    import 'package:analyzer/src/generated/element.dart';
    import 'package:analyzer/src/generated/java_engine_io.dart';
    import 'package:analyzer/src/generated/source.dart';
    import 'package:analyzer/src/summary/summarize_elements.dart'
        as summarize_elements;
    import '../../generated/resolver_test.dart';

If I re-introduced any of these 5 import statements, then the program went back to doing nothing.

It's my understanding that unused imports shouldn't affect program behavior, so I'm still inclined to suspect this is a dart2js bug.

**Comment by whesse** [comment]
Sure.  I would file the reduced case as a bug with dart2js.  See if you can
reduce it even further.  And you can comment on the original test it comes
from.

On Fri, Nov 13, 2015 at 8:29 PM, Paul Berry <notifications@github.com>
wrote:

> I believe the test should run under d8, but I could be wrong. What is the
> expected behavior if the program depends on any dart:io stuff? (I thought
> dart2js was supposed to print out an error message during compilation in
> this case). What I'm seeing is that the program is exiting immediately with
> an exit code of 0 and no error/warning message. If that's the intended
> behavior, it's a really poor user experience (especially in the case of
> unit tests, where an exit code of 0 will get mistaken for success).
>
> I tried adding a print('foo'); statement at the top of main, and there
> was no effect. Then I tried deleting all other code in the file (with the
> exception of the library declaration and the import statements), and there
> was still no effect. Then I tried commenting out import statements, and I
> found that if I commented out the following import statements, then the
> program printed out "foo":
>
> import 'package:analyzer/src/generated/element.dart';
> import 'package:analyzer/src/generated/java_engine_io.dart';
> import 'package:analyzer/src/generated/source.dart';
> import 'package:analyzer/src/summary/summarize_elements.dart'
>     as summarize_elements;
> import '../../generated/resolver_test.dart';
>
> If I re-introduced any of these 5 import statements, then the program went
> back to doing nothing.
>
> It's my understanding that unused imports shouldn't affect program
> behavior, so I'm still inclined to suspect this is a dart2js bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24914#issuecomment-156535250>.
>



-- 
William Hesse

**Comment by stereotype441** [comment]
@sigmundch it looks like @pq may have run into this as well--see http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-cps-be/builds/519/steps/dart2js-d8%20tests%20--dart2js-batch%20--cps-ir/logs/stdio, which shows a compilation timeout in `pkg/analyzer_cli/test/super_mixin_test`

**Comment by pq** [comment]
> looks like @pq may have run into this as well

That's right.  Here's a proposed status file update to address:

https://codereview.chromium.org/1464833002/

**Comment by stereotype441** [comment]
It looks like some other tests are beginning to see similar problems.  See for example http://build.chromium.org/p/client.dart/builders/dart2js-linux-jsshell-release-4-4-be/builds/12295/steps/dart2js-jsshell%20tests%20--dart2js-batch%20failures/logs/stdio

(Note that the "failed" test did not actually run; it timed out during dart2js's attempt to compile it)

**Comment by stereotype441** [comment]
And here's another example: http://build.chromium.org/p/client.dart/builders/full-win7-ie10-2-4-be/builds/7209/steps/dart2js_extra-chrome%20tests%20--dart2js-batch%20failures/logs/stdio

**Comment by whesse** [comment]
The analyzer unit tests, which are part of the analyzer source code, are only run in the vm now.  The buildbot runs them on the builders called "dart2js-jsshell", but they run on the vm, not jsshell, there.
Closing this issue.
