### ISSUE TITLE
Dart linux installation instructions should have instructions for pub

### ISSUE THREAD

**Issue by kulakowski** [dart-lang/sdk#24915]
https://www.dartlang.org/downloads/linux.html does not mention that pub (and dartfmt etc.) are placed in the location described in https://www.dartlang.org/tools/sdk/. Linking to the latter's instructions would be clarifying.

I came across this following the directions on http://flutter.io/getting-started/ which point to the linux installation instructions.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/www.dartlang.org#1525
