### ISSUE TITLE
main() is not called when Google Chrome inspector is opened.

### ISSUE THREAD

**Issue by dikmax** [dart-lang/sdk#24917]
In compiled version `main()` is not called, but only when inspector is opened. I don't have minimal set to reproduce, but you can see behavior on my site <https://dikmax.name/>, navbar on top is colored using dart. Source [here](https://github.com/dikmax/dikmax.name/tree/master/dart).

I actually don't know even how to debug this issue, without inspector. Any suggestions?

I use:
MacOS 10.11
Google Chrome 46

**Comment by zoechi** [comment]
Do you have the `packages/browser/dart.js` script tag after your Dart script tag in your entry page? 
I guess it's some timing issue.

**Comment by zoechi** [comment]
Sorry, missed your source link. 
There is no index.html. How do you link the Dart script into your page? How do you build to JS? 

You shouldn't import with relative paths that go outside top-level directories like
`import '../lib/app.dart';`
use instead 
`import 'package:dikmax. name/app.dart';`

**Comment by zoechi** [comment]
It's also discouraged to use `any` as dependency constraint. This can easily lead to surprising versions being fetched by pub.  For example when pub can't find a matching set of recent versions and an old version hasn't specified an upper bound for a dependency (which was often the case especially in early versions of old packages)

**Comment by dikmax** [comment]
I'm using static site builder written in Haskell, source is /src/Site.hs. 
Js built using following command

```bash
dart2js --out=_temp/script.dart.js --minify dart/web/main.dart
```
`packages/browser/dart.js` is not included, because it's only replaces `<script type="application/dart">` with `<script type="text/javascript">` and I include compiled js directly.

I've tried to remove all code to check if it because of dart-code I've written. I left only one `print()` but no help. If inspector is opened then nothing is appeared in console. If on page load inspector is closed, then after you open inspector you'll see console output.

**Comment by dikmax** [comment]
I think I'll close this issue. I've noticed icon which says that Google Chrome has blocked js. It appears only with inspector opened. Don't know reason, but this is definitely not dart-sdk issue.
