### ISSUE TITLE
dartdocs should specify the default value of documented fields

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24929]
```dart
/// The color to use when painting RenderError boxes in checked mode.
ui.Color debugErrorBoxColor = const ui.Color(0xFFFF0000);
```

...turns into:
> `Color debugErrorBoxColor`
> _read / write_
> The color to use when painting RenderError boxes in checked mode.

It would be nice if it also said something like:

> Defaults value: `const Color(0xffff0000)`

...or some such.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/dartdoc#1030
