### ISSUE TITLE
Avoid reset in flutter apps

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24926]
When debugging flutter apps, one uses the "flutter start" command which pushes a new snapshot onto the device (and forwards the observatory port).
Unfortunately it also destroys the current VM...
That means that every change in the source requires to start the debugging session from scratch. It would be really helpful if the breakpoints, open source-code locations, ... were still accessible after a flutter-restart.

Assigning to observatory (since the debugger's equivalent in editors usually deals with this transparently), but it could probably also be solved (at least partially) by modifying how flutter apps are run.

**Comment by iposva-google** [comment]
@floitschG Is there a particular reason the Flutter application needs to be started from a snapshot during development? @turnidge has added a way to restart an application from within the Observatory, but as far as I remember that needed a tiny change in the embedder code. I would like to see this functionality in the Flutter setup as well.

**Comment by johnmccutchan** [comment]
In the past the Flutter embedder had support for restarting apps automatically by shaking the device. Does this not exist anymore?

**Comment by sethladd** [comment]
We're moving away from that. We'd like to get the edit/refresh cycle (from editor to device) down to 1 second on an Android phone.

**Comment by floitschG** [comment]
The shaking approach would lose the breakpoints, and I'm not sure if the open files would still be valid, but it would be a good start.

Integrating Flutter-debugging into Atom, is apparently another goal which would solve this for me.

**Comment by eseidelGoogle** [comment]
@jason-simmons just implemented the ability to have the same flutter engine process load a new .flx file.  Does the Dart VM have support for reloading just one dart file and not a whole app?

The Flutter Debugger also works in Atom now (at least on Android) thanks to @devoncarew

**Comment by rmacnak-google** [comment]
Bug predates hot-reload.
