### ISSUE TITLE
Disable some throw-locations

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24922]
When running in a testing-harness, it is very common that all exceptions are caught. If one wants to break at exceptions, it is therefore necessary to set the flag to "All".
However, it is equally likely that one runs with the stacktrace package which uses `try {throw 0; } catch(e, st) { <use st>}` to capture stacktraces.
If there are lots of asynchronous calls it gets impossible to break at the actual exception point I'm interested in.
It would be great if I could ignore a throwing place. "Ignore exceptions at XYZ", or simply "ignore exceptions here" (immediately when an exception triggered a break).

**Comment by lrhn** [comment]
What if we had a way to get a stack trace that didn't count as a throw?
E.g., a `StackTrace.current` getter which returns a stack trace at the current location (maybe even dropping itself from the stack first, just to be nice). If the VM doesn't consider that to be a throw, then it doesn't interfere with actual throws. It'll probably be faster too.

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by floitschG** [comment]
I think both would be nice options. Lasse's suggestion would deprioritize this feature request.

**Comment by lrhn** [comment]
Have `StackTrace.current`.
