### ISSUE TITLE
dart2js: constant names not stable for type parameters, large strings

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24920]
Both of these constants in dart:html are mapped to the same name, `C.EventStreamProvider_load`:

``` Dart
  static const EventStreamProvider<Event> loadEvent = const EventStreamProvider<Event>('load');
  static const EventStreamProvider<ProgressEvent> loadEvent = const EventStreamProvider<ProgressEvent>('load');
```

This leads to minified names

```
C.a0=new W.M("load")
C.a1=new W.M("load")
```

in one compilation and 

```
C.a1=new W.M("load")
C.a0=new W.M("load")
```

in another. (From `sdk/bin/dart2js samples-dev/swarm/swarm.dart --minify --out=m2.js`)
The names a0 and a1 have been assigned in a way that seems to be stable (the references are unchanged). This means that the constants are emitted in a different order.

Since the constants are sorted by the (unminified) name `C.EventStreamProvider_load`, the order is not deterministic.
Repeated compiles flip the order of the constants, leading to differences in the output of compiling the same program twice with no changes.

There is no type parameter attached to the runtime constant object because it is unused, but the runtime type parameters could be included in the name.

Large strings have a different problem. We use a hash function to reduce the large string to an identifier. This can have collisions. There is a collision on JS_CONST constants containing strings in the js_runtime!

We can't embed the whole constant in the name. I think we need to develop a compareTo function for constants that always distinguishes non-identical constants. This can be used in place of the pretty-name / hash-name scheme, or as a fall-back for when the current scheme produces identical names.
(sorting by the hash-name first helps gzip.)

The above is one cause of https://github.com/dart-lang/sdk/issues/24721

**Comment by rakudrama** [comment]
CL investigating the __compareTo__ approach: https://codereview.chromium.org/1491413008/ .

**Comment by srawlins** [comment]
@rakudrama tagged this as "closed-obsolete", and I think the issue has been fixed, as we have deterministic builds internally.
