### ISSUE TITLE
segfault when setting breakpoint

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24934]
When I run my Dart server application with this WebStorm launch configuration
- Dart File: `/home/myuser/dart/bwu_dev_server/bin/devserver.dart`
- checked mode [x]
- Program arguments: `-d../dart-lang/polymer_elements_demos`
- Working directory: `/home/myuser/dart/bwu_dev_server`

then load this file 
https://github.com/bwu-dart/polymer_elements_demos/blob/23a153aa8966d97de2d4849ecf5f97568a08c652/web/index.html
using Dartium, 

then after Dartium displays the page set a breakpoint at  
https://github.com/bwu-dart/bwu_dev_server/blob/85dc580a0be33b9d742544464e455e8c4668ac7b/lib/src/file_cache.dart#L12-L12

the application exits 
> Process finished with exit code 139

**Comment by zoechi** [comment]
`dart --version`
> Dart VM version: 1.13.0-edge.73b6080a6b26ad24380477c4a584edd6cb2e2ab5 (Fri Nov 13 14:15:20 2015) on "linux_x64"

I also just saw that WebStorm shows a different Dart version in 

Settings > Languages & Frameworks > Dart > Version 

> 1.13.0-edge.508b70bdabe4a2ca37435eea5686eebe8e77d2b4

The 2nd seems to be from the `version` file in the `dart-sdk` directory. 

Why do they differ? (from bleeding_edge latest)

**Comment by alan-knight** [comment]
I don't think this is a Dartium issue. It's a segfault in the server code after a breakpoint is set in Dartium, i.e. it sounds like a problem with the debugging protocol.

**Comment by iposva-google** [comment]
@zoechi What is not really clear from your description is the following: Which process crashes? The dart server VM or Dartium? If it is the server code, then the question is whether you need Dartium to be driving the loading or whether any artificial load on the server causes the crash as well, making reproduction much simpler. Lastly, is it possible to get the same crash if setting the breakpoint from within the Observatory instead of WebStorm, which would make the setup even more minimal. Thanks!

**Comment by zoechi** [comment]
Sorry, for not being more clear. Never seen a segfault in Dartium, I thought it only "Aw, Snap!" s.

It's the server process that segfaults the moment I set the breakpoint and it doesn't crash when I set the breakpoint in Observator only in WebStorm. 
Should I move this over to the WebStorm issue tracker? @alexander-doroshko 
The VM shouldn't crash anyway.

**Comment by iposva-google** [comment]
Thanks for the clarification. We just need a good way to reproduce this issue. As you say a segfault is not a good outcome.

**Comment by zoechi** [comment]
You can't reproduce? For me it segfaults every time I set a breakpoint in this file, (not only the line I posted above).

**Comment by zoechi** [comment]
Can't reproduce
