### ISSUE TITLE
change the `experimental.getDiagnostics` call from the experimental domain to a `diagnostics` domain

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24931]
The `diagnostics` domain can still be marked as experimental, but we'll need it to settle in it's final location in order to start calling it from the client. So, `diagnostics.getDiagnostics`. The diagnostics domain may or may not get logging capability.

**Comment by pq** [comment]
https://codereview.chromium.org/1453433002/

**Comment by devoncarew** [comment]
Thanks!

**Comment by pq** [comment]
Done w/ https://github.com/dart-lang/sdk/commit/6d9cb5e48a8a55d0988c43ed52b0e20260c5c922.
