### ISSUE TITLE
Investigate the performance of the `getDiagnostics` call

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24932]
Some initial experiments indicate that the `getDiagnostics` call takes on the order of 200ms. A `getVersion` call takes ~10ms. We should be sure that getting diagnostics doesn't do a lot of work, or cause a lot of work to be done. We just want to measure :)

**Comment by devoncarew** [comment]
FYI, we will be polling this API about once a second when the user is viewing analysis server performance data. We'll want to have confidence that measuring the thing doesn't substantially change  its performance.

**Comment by devoncarew** [comment]
To follow up, I see this when opening the flutter repo. I has about 20 contexts, and the analysis server has about 10k explicitly and implicitly analyzed files.

**Comment by bwilkerson** [comment]
@devoncarew Is this still an issue we need to track?

**Comment by devoncarew** [comment]
No, I think this is stale.
