### ISSUE TITLE
Empty else clause should raise at least a warning

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/sdk#24936]
Running on 1.12.2, I noticed that 'else;' DOESN'T flag a warning or error. 

I can't think an empty else clause has any valid use cases. More likely to be created by accident and this could lead to hard to find bugs.

Csharp reports a warning in this case. Dart 1.X should report at least a warning, maybe an error in Dart 2.0 onwards.

Example follows.
```javascript
  main(List<String> args) {
    int x=1,y=0;
    if (x>y)
      print("1");
    else;
      print("2");
  }
```

The output is
C:\Users\daftspaniel\WebstormProjects\untitled1\bin\main.dart
Observatory listening on http://127.0.0.1:51706
1
2

Process finished with exit code 0

**Comment by pq** [comment]
Thanks for the report!

Lint implementation in flight here: https://codereview.chromium.org/1447263002/

**Comment by pq** [comment]
Implemented w/ https://github.com/dart-lang/linter/commit/8ff723b19b6c6948ca8bf686919355794334ae0c.  I'll push out a new linter build (and integrate it with the dev analyzer) in the next week.

**Comment by daftspaniel** [comment]
Thanks @pq - impressed with the quick response! :+1:
