### ISSUE TITLE
Replace jinja2 with package:mustache in dart:html generation?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#24937]
Looks like [we're using Python scripts](https://github.com/dart-lang/sdk/tree/master/tools/dom) to generate dart:html from .darttemplate files, and JSON data files. We're using a combination of Jinja2 and simpler Python string interpolation as our templating tooling to generate .dart files from the .darttemplate and .json files. So, two questions:
1. **Is it important that all this tooling remain Python, or can it be converted to Dart?** (I assume it was written before/during Dart stabilization, so Python was chosen for this tooling.)
2. **Would this tooling be in a better place if it used the [mustache package](https://pub.dartlang.org/packages/mustache) for templating?** i.e. more maintainable?

And some comments:
- It's good to eat our own dogfood; using Dart to generate Dart.
- I've used the mustache package before; it's very stable and 100% in line with the mustache specification.
- The mustache templating language is drastically simpler than the Jinja2 templating language, but combined with the Dart code that generates the context that a template is parsed in, Mustache should be essentially equivalent.

**Comment by whesse** [comment]
I would classify this as an dart:html and documentation issue, since the infrastructure team has never been involved in these tools, as far as I know.  So I'm adding the area:documentation label and removing area:infra.

**Comment by terrylucas** [comment]
The reason jinja2 is used is because the python scripts we use come from Chrome and these scripts use jinja2.  Every roll of Dartium, from a Chromium to build, updates these set of common Chrome python files.

**Comment by srawlins** [comment]
Ah interesting. That is a very good reason to keep using Jinja2! I'll close.
