### ISSUE TITLE
additional measurements to the `getDiagnostics` call

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24933]
We should additionally measure things like:

- the depth of the task queue
- how long it takes to process commands, as a weighted moving average

I think these, and the current context size metric, would give us enough meaningful metrics for the users.

**Comment by bwilkerson** [comment]
> the depth of the task queue

What do you mean by that?

**Comment by pq** [comment]
> how long it takes to process commands, as a weighted moving average

Do you mean client-initiated commands like get me hovers, completions, outline info, etc?

**Comment by devoncarew** [comment]
Let's talk in person. I'm interested in a measure of latency that will increase when the analysis server is heavily loaded or becoming unresponsive.

**Comment by pq** [comment]
> the depth of the task queue

Landed in https://github.com/dart-lang/sdk/commit/c0466f28f51bc4e00f4646504e3736b3d9580eb2.

**Comment by pq** [comment]
https://github.com/dart-lang/sdk/commit/c0466f28f51bc4e00f4646504e3736b3d9580eb2 adds a rolling average of work-queue length.

**Comment by bwilkerson** [comment]
> ... a rolling average of work-queue length.

Is this information available on the status page? If not, could it be added there?

**Comment by pq** [comment]
It's not but I'm not sure it would be so useful as the status page is currently implemented.  Net-net this feature depends on regular client requests to keep rescheduling the sampling.   Unless we manually refresh the status page the sampling will timeout and we'll see really lumpy data...

**Comment by pq** [comment]
Closing out as these are done as of https://github.com/dart-lang/sdk/commit/c0466f28f51bc4e00f4646504e3736b3d9580eb2:
> * the depth of the task queue
* how long it takes to process commands, as a weighted moving average

@devoncarew : feel free to re-open if you have more ideas!

**Comment by devoncarew** [comment]
Yeah, with that 2nd item

> how long it takes to process commands, as a weighted moving average

I was trying to capture a sense to latency in the engine - how loaded it is. I don't think we have that yet, but am happy to file a new issue.
