### ISSUE TITLE
Analysis server fatal error (SDK 1.13.0-dev.7.10)

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24939]
Reported by WebStorm user.

    OS: Windows 10
    Dart analysis server, SDK version 1.13.0-dev.7.10, server version 1.12.0, FATAL error: The null object does not have a getter 'source'.

    NoSuchMethodError: method not found: 'source'
    Receiver: null
    Arguments: []
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
    #2      SdkCachePartition.isResponsibleFor (package:analyzer/src/context/cache.dart:1233)
    #3      AnalysisCache.get (package:analyzer/src/context/cache.dart:107)
    #4      AnalysisContextImpl.getCacheEntry (package:analyzer/src/context/context.dart:745)
    #5      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:684)
    #6      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:816)
    #7      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395)
    #8      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:782)
    #9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
    #10     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:774)
    #11     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:245)
    #12     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
    #13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
    #14     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
    #15     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
    #16     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
    #17     Future.Future.<anonymous closure> (dart:async/future.dart:118)
    #18     _rootRun (dart:async/zone.dart:903)
    #19     _CustomZone.run (dart:async/zone.dart:802)
    #20     _CustomZone.runGuarded (dart:async/zone.dart:708)
    #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
    #22     _rootRun (dart:async/zone.dart:907)
    #23     _CustomZone.run (dart:async/zone.dart:802)
    #24     _CustomZone.runGuarded (dart:async/zone.dart:708)
    #25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
    #26     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
    #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
    #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
    #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

**Comment by scheglov** [comment]
Adding debug output.
https://codereview.chromium.org/1444353004
