### ISSUE TITLE
Add "reachable memory size" to Observatory.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24945]
In contrast with "retained", "reachable" means that all the reachable objects are included, even if they are reachable from the root through other objects.

**Comment by rmacnak-google** [comment]
75cd019a9cecf30ef428b114cc2e654b2b6ded02

**Comment by scheglov** [comment]
I've tried this feature and it gives me results I don't expect.

1. Total heap.
![image](https://cloud.githubusercontent.com/assets/384794/11349094/2f696900-91df-11e5-9d8b-d9dad6faf033.png)

2. CompilationUnit.
![image](https://cloud.githubusercontent.com/assets/384794/11349112/494447b4-91df-11e5-910e-3cf2625c0542.png)

3. CompilationUnitElement.
![image](https://cloud.githubusercontent.com/assets/384794/11349125/612fd8b6-91df-11e5-9225-7e724b16934f.png)

I don't quite understand how the reachable size of `CompilationUnitElement` instances can be `614MB`. It's way too much. Ad it the retained size of `CompilationUnit instances` is `113MB`, this mean AFAIK that no objects of other classes references these `113MB`. So, the reachable size of `CompilationUnitElement` instances can be at max `614MB - 113MB`.

**Comment by rmacnak-google** [comment]
The only bound on the reachable size of an object is the heap size. In a data structure with extensive back references and cross references, the reachable size of any part of it is likely to be the size of the whole thing.

shallow size <= retained size <= reachable size <= total heap size

"Ad it the retained size of CompilationUnit instances is 113MB, this mean AFAIK that no objects of other classes references these 113MB"

Not quite. The objects that make up that 113 MB may be (and probably are) referenced by objects that are not instances of CompilationUnit. All we can say is that that subgraph is only reachable from the GC roots (globals, stack, API handles) through instances of CompilationUnit.
