### ISSUE TITLE
CanvasElement.context2D.canvas returns undefined

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/sdk#24948]
1. Create a canvas element in html
2. Grab the element in Dart
3. Print CanvasElement.context2D.canvas, it will display as undefined.

**Comment by alan-knight** [comment]
Is this dart2js or Dartium? Which version?

**Comment by ErikGrimes** [comment]
Woops.  Sorry about that.

Dartium 39.0.2171.0
Dart SDK 1.12.1 on mac osx 10.9.5

**Comment by kevmoo** [comment]
```dart
import 'dart:html';

void main() {
  var canvas = querySelector('#foo') as CanvasElement;
  print(canvas.context2D.canvas);
  print(canvas.context2D.canvas.runtimeType);
}
```

Confirmed the right behavior in dart2js

```
canvas
CanvasElement
```

Dartium is no longer supported
