### ISSUE TITLE
Enable analyzer to auto-discover a configuration file in a package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24943]
Tracking issue, related to https://github.com/dart-lang/sdk/issues/24733

This issue reflects the need to ship analyzer configurations in a package. Presumably, we'll use the _embedder.yaml file, to configure errors/hints/warnings/lints.

**Comment by pq** [comment]
https://codereview.chromium.org/1445363002/

**Comment by pq** [comment]
Implemented w/ 3a1a3ee0948f0bfe6b3d36c49b5e8eb0dfb1b8b.

**Comment by sethladd** [comment]
Great! Does this mean that Flutter can now use this file, and get rid of their analyzer wrapper script? (or, at least try to get rid of it?)

**Comment by pq** [comment]
We don't have enough lints implemented to do away with their script completely but we're edging along and can likely simplify it...  We should certainly experiment.

**Comment by sethladd** [comment]
Just confirming that if we create this file in our package, and put anything in it, then it will be read and will configure the analyzer. We'll give it a go and report back. Thanks!

**Comment by pq** [comment]
> Just confirming that if we create this file in our package, and put anything in it, then it will be read and will configure the analyzer. We'll give it a go and report back. Thanks!

Absolutely.  If that doesn't *just work*, it's a bug!
