### ISSUE TITLE
Dart VM types/imports not canonicalized when main is in lib/

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#24942]
When starting an application with `main` in the `lib/` directory, Dart VM treats local imports differently from `package:` imports.

Example:

```dart
// file: lib/a.dart
import 'b.dart' as i1;
import 'package:imports/b.dart' as i2;

main() {
  print('>>> ${(i1.Foo).hashCode}');
  print('>>> ${(i2.Foo).hashCode}');  // not same as previous line
  print('>>> ${new i1.Foo() is i2.Foo}');  // false
  i2.Foo foo = new i1.Foo();  // throws in checked mode
}

// file: lib/b.dart
library b;

class Foo {}
```

Example output:

```
$ dart -c lib/a.dart
>>> 77156731
>>> 718081013
>>> false
Unhandled exception:
type 'b.Foo' is not a subtype of type 'b.Foo' of 'foo'.
#0      main (file:///Users/yjbanov/code/tmp/imports/lib/a.dart:8:20)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

Example expected output (what you get when `main` is in `bin` for example):

```
$ dart -c bin/main.dart
>>> 211364468
>>> 211364468
>>> true
```

This affects Flutter apps, which always launch from `lib/`.

**Comment by iposva-google** [comment]
This is expected and defined behaviour. Also, I do not see how the example program can even run in the second case as I am not sure how the import of 'b.dart' even resolves.

The correct way to start you program out of a package library location is to launch it with the following command line:
dart --package-root=<your appropriate package root> package:imports/a.dart

**Comment by yjbanov** [comment]
This worked:

`dart -c --package-root=./packages package:imports/a.dart`

So it seems flutter specifies incorrect main file.
