### ISSUE TITLE
Please merge 2 revisions

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24950]
@whesse @mit-mit @kasperl
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
https://github.com/dart-lang/sdk/issues/24939

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
0e712ea00c4b13fd09d7f9e3d1fef1d3bf0299ec - to make it mergeable and a bit faster
97088a2e90afdd40ef98cd18cc265a5a05caf8b7 - the CL with debug information and preventing fatal DAS error

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
These 2 changes should be merged in this order, then it merges cleanly.

**Comment by mit-mit** [comment]
Closing this as wont-fix per discussion with @clayberg that this is not a blocker for 1.13.

**Comment by mit-mit** [comment]
@whesse FYI
