### ISSUE TITLE
StreamController.onCancel is called before end of the await for loop

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24956]
The specification for class StreamController ( https://api.dartlang.org/1.12.1/dart-async/StreamController/StreamController.html ) reads:

> The onListen callback is called when the stream receives its listener and 
> onCancel when the listener ends its subscription.

The following code demonstrates, that onCancel is called in the middle of the asynchronous loop.

```
import 'dart:async';

Future test() async {
  StreamController<String> sc = new StreamController<String>();
  sc.add('a');
  sc.add('b');
  sc.onCancel = () { print("loop 0: subscription cancelled");};
  sc.close();
  await for (String s in sc.stream){
    print("loop 0: $s");
    await for (String s in new Stream.fromIterable(['a','b'])){
      print("loop 1: $s");
    }
  }
  print("after loop 0");
}

main() {
  print("test start");
  test().then((v) => print("test result: $v"))
    .then((v) => print("test finish"));
}
```

Output:

> test start
> loop 0: a
> loop 1: a
> loop 1: b
> loop 0: subscription cancelled
> loop 0: b
> loop 1: a
> loop 1: b
> after loop 0
> test result: null
> test finish

Expected output:

> test start
> loop 0: a
> loop 1: a
> loop 1: b
> loop 0: b
> loop 1: a
> loop 1: b
> loop 0: subscription cancelled
> after loop 0
> test result: null
> test finish

Dart VM version: 1.12.2 (Wed Oct 21 07:10:52 2015) on "windows_x64"

**Comment by lrhn** [comment]
Quick guess: The onCancel is also called when the stream has sent its done event. The way the loop is implemented uses a one-event buffer (to avoid repeatedly pausing and resuming). That means that the done event is *sent* in the middle of a loop body execution, but delayed by the loop until the body completes. 

The source stream basically cancels itself, independently of the loop.

It's technically wrong - the specification requires the loop to pause the stream subscription at any async operation in the loop body - which may be a waste of time if the next event doesn't show up until after the body is done anyway. So, for performance it allows the next event to arrive, and only pauses then if the body is still not done, giving this problem.

**Comment by fsc8000** [comment]
Not reproducible anymore for me (probably got fixed at some point). Reopen, if this should still be an issue.

Tried with 1.22:
```
>out\ReleaseX64\dart.exe --version
Dart VM version: 1.22.0-edge.d71c70d56dee50c12c91d03627192e6ef93b8c7a (Wed Jan 25 11:24:59 2017) on "windows_x64"
```

```
out\ReleaseX64\dart.exe r24956.dart
test start
loop 0: a
loop 1: a
loop 1: b
loop 0: b
loop 1: a
loop 1: b
loop 0: subscription cancelled
after loop 0
test result: null
test finish
```
