### ISSUE TITLE
Dart startup is slow

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24953]
Running `time dart pub.dart.snapshot` says that displaying "pub"'s help information takes 228ms of wall-clock time.

Running `time dart` says that displaying "dart"'s help information takes only 2ms of wall-clock time, which seems much more in line with what one would expect.

**Comment by zanderso** [comment]
Related: https://github.com/dart-lang/sdk/issues/20470

**Comment by mraleph** [comment]
Does not seem to be actionable. Closing it as stale.
