### ISSUE TITLE
new Element.html("<div></div>") throws an error on firefox

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#24969]
tested using dart sdk 1.12 and 1.13

It throws the following error on firefox (tested on windows 10 with firefox 29.0 - while it works fine on Chrome and IE)

```
Removing element due to corrupted attributes on <div>
```

It works when using a dummy sanitizer though.

**Comment by alan-knight** [comment]
This is not reproducing for me, but I have Firefox 42, and I wouldn't even know how to get 29. If it doesn't reproduce on a more current version, then I'd think that's a browser bug.

**Comment by alextekartik** [comment]
yes indeed. i should turn on my windows box more often. indeed working fine on Firefox 42. Sorry for the bad report
