### ISSUE TITLE
Exception in pub build

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24960]
@MikeMitterer
@munificent 
@nex3 

Mike, I noticed that there was an exception on `pub build`  execution before `pub get`.
Natalie would like to get more information about this problem.

**Comment by scheglov** [comment]
How to move issues?

**Comment by nex3** [comment]
I think there's a tool for it, but it's probably easier to just close this and open a new one.

**Comment by scheglov** [comment]
I'm fine with having it the SDK repo.

**Comment by nex3** [comment]
That's not really the question. Pub issues should be filed against pub, not against the SDK.

**Comment by scheglov** [comment]
Oh, sorry.
It looked as a question to me.

https://github.com/dart-lang/pub/issues/1362

**Comment by kevmoo** [comment]
Moved to https://github.com/dart-lang/pub/issues/1362
