### ISSUE TITLE
implement codegen of the new jsinterop in cpsir

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24978]

**Comment by zoechi** [comment]
May I ask what "nssa" means? I saw it a few times recently but have no clue what it is about.

**Comment by sigmundch** [comment]
We have been doing some work to replace our ssa backend with the a cps-ir (continuation-passing-style IR), but we plan to do some refactoring changes that will remove the continuations from CPS-ir, which makes it more like a nested-ssa, or "nssa" for short :)

**Comment by zoechi** [comment]
Never mind :D 
Thanks anyway!

**Comment by sigmundch** [comment]
I'll be sending https://codereview.chromium.org/1688433006 out shortly. The following two tests are still failing:

`js_typed_interop_side_cast_exp_test`: It's not clear whether we want to continue supporting these semantics of allowing a side-cast. I haven't investigated what makes this behave different than SSA, but it's quite possible this seems to be breaking some assumptions in type-propagation.
 
`js_typed_interop_test/static_method_tearoff_1`: this seems broken due to an unrelated issue with tree-shaking. It might be related to #25720.

The CL also adds `js_typed_interop_test/static_method_tearoff_2`: to illustrate issue #25759.

**Comment by sigmundch** [comment]
landed support in https://github.com/dart-lang/sdk/commit/a0c438a972bb4e8bc47881cbb948c3ed74aab00e. Closing since pending issues are tracked in the two bugs mentioned above.
