### ISSUE TITLE
[package:glob] "/**/*.dart" should match any absolute Dart file path on any OS

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24971]
@nex3 @munificent @bwilkerson 

Asking users to think about differences between Posix and Windows styles is too much.
Especially when path separators are already `/` for any OS.

I don't also quite understand the requirement for the leading `/` to match absolute paths.
It seems confusing.

**Comment by nex3** [comment]
Please file this against [the `glob` repo](http://github.com/dart-lang/glob).

**Comment by scheglov** [comment]
Done.
https://github.com/dart-lang/glob/issues/2
