### ISSUE TITLE
AnalysisServer.setPriorityFiles() should remember the given set

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24979]
The specification states that the path may become an actual priority file later.

> Note that this request determines the set of requested priority files. The actual set of priority files is the intersection of the requested set of priority files with the set of files currently subject to analysis. (See analysis.setSubscriptions for a description of files that are subject to analysis.)
> 
> If a requested priority file is a directory it is ignored, but remains in the set of requested priority files so that if it later becomes a file it can be included in the set of actual priority files.

**Comment by bwilkerson** [comment]
I believe that this is now being done. Please re-open if that's not the case.
