### ISSUE TITLE
Analyzer does not work properly when using exclude in .analysis_options

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24983]
Opening this on behalf of @mikemitterer who mentioned this issue in #24812, so that we can track this issue separately.

**Comment by mit-mit** [comment]
Adding in content @mikemitterer wrote in original thread:

A few days ago I've moved all the MDL/Dart samples to https://goo.gl/UM9hsN
As you can see in the SS DA ist not able to resolve an Object defined in it's own lib LoginDialog
And again - it's DA-Server. The cmdline-version works.

[Update]
I forgot to mention that I have a .analysis_options file for this module. I wasn't sure if this is already implemented or if this was just a proposal - so I tried it out

analyzer:
  exclude:
    - 'samples/**'

![](https://cloud.githubusercontent.com/assets/116654/11234951/352ef6e0-8dcd-11e5-8ef7-7b6d238e412d.png)

**Comment by scheglov** [comment]
If `samples/**` is ignored, none of its files should  not be analyzed at all.
You have this error because the file is analyzed in a wrong analysis context.

https://github.com/dart-lang/sdk/commit/a689bf41805c251b5bae646e0eb82f832d1e309f
This will prevent analysis of excluded files.
