### ISSUE TITLE
dart:profiler error after SDK 1.13.0 update

### ISSUE THREAD

**Issue by sambbaron** [dart-lang/sdk#24986]
I saw another issue related to dart:profile, but I am not sure if this is related because I am getting a different error.  After updating the SDK to 1.13.0, I am receiving the following error:

[Error from _Serial on orchard|web/orchard.dart]:
Unable to resolve asset ID for "dart:profiler"

**Comment by kevmoo** [comment]
@sambbaron try "pub upgrade".

If that doesn't fix things, you may have a version constraint issue with an old version of analyzer. Let me know...

**Comment by sambbaron** [comment]
@kevmoo That fixed it!  Thank you!
