### ISSUE TITLE
Precompilation: crash in WidenSmiToInt32 on simarm

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24987]
FAILED: none-vm debug_simarm co19/Language/Expressions/Logical_Boolean_Expressions/syntax_t01
Expected: Pass
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/bit_vector.h:88: error: expected: i >= 0 && i < length()

0  0xf7fdb440 in __kernel_vsyscall ()
#1  0xf7cbf607 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7cc2a33 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x081dd4b5 in dart::DynamicAssertionHelper::Fail (this=this@entry=0xffffb934, 
    format=format@entry=0x8787728 "expected: %s") at runtime/platform/assert.cc:41
#4  0x08225066 in dart::BitVector::Contains (this=0x9026610, i=-1) at runtime/vm/bit_vector.h:88
#5  0x082c92ba in dart::FlowGraphOptimizer::WidenSmiToInt32 (this=this@entry=0xffffbb60)
    at runtime/vm/flow_graph_optimizer.cc:4889
#6  0x0821118f in dart::CompileParsedFunctionHelper (pipeline=pipeline@entry=0x8f1c508, 
    parsed_function=parsed_function@entry=0xffffc028, optimized=optimized@entry=true, 
    osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:613
#7  0x082140e9 in dart::CompileFunctionHelper (pipeline=pipeline@entry=0x8f1c508, function=..., 
    optimized=<optimized out>, osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:1167
#8  0x08215d78 in dart::Compiler::CompileFunction (thread=0x8e93580, function=...)
    at runtime/vm/compiler.cc:1259
#9  0x0846bee0 in dart::Precompiler::ProcessFunction (this=this@entry=0xffffc814, function=...)
    at runtime/vm/precompiler.cc:358
#10 0x0846c90e in dart::Precompiler::Iterate (this=this@entry=0xffffc814)
    at runtime/vm/precompiler.cc:335
#11 0x0846dffe in dart::Precompiler::DoCompileAll (this=this@entry=0xffffc814, 
    embedder_entry_points=embedder_entry_points@entry=0xffffc9f0) at runtime/vm/precompiler.cc:102
#12 0x0846e29e in dart::Precompiler::CompileAll (
    embedder_entry_points=embedder_entry_points@entry=0xffffc9f0, 
    reset_fields=reset_fields@entry=false) at runtime/vm/precompiler.cc:39
#13 0x081b1bfd in dart::Dart_Precompile (entry_points=0xffffc9f0, reset_fields=false)
    at runtime/vm/dart_api_impl.cc:6040
#14 0x081867b9 in dart::bin::RunMainIsolate (
    script_name=script_name@entry=0xffffcf84 "/usr/local/google/home/rmacnak/dart1/sdk/tests/co19/src/Language/Expressions/Logical_Boolean_Expressions/syntax_t01.dart", 
    dart_options=dart_options@entry=0xffffcbc4) at runtime/bin/main.cc:1273
#15 0x0817d57a in dart::bin::main (argc=argc@entry=7, argv=argv@entry=0xffffccb4)
    at runtime/bin/main.cc:1484
#16 0x0817d74b in main (argc=7, argv=0xffffccb4) at runtime/bin/main.cc:1524

**Comment by fsc8000** [comment]
Fixed in 166b3d
