### ISSUE TITLE
define "inspectee" on the service protocol Event response type

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24998]
The Event class (subclass of Response) defines several optional fields for all the values that different events might have. The `Debug` stream event `Inspect` has the field 'inspectee', but this is not defined on the service protocol doc.

It'd be nice to have this as part of the public API, as this is the event that the `dart:developer` `inspect()` method fires.

**Comment by devoncarew** [comment]
```json
"inspectee":{  
        "type":"@Instance",
        "class":{  
          "type":"@Class",
          "fixedId":true,
          "id":"classes\/1360",
          "name":"Dog"
        },
        "kind":"PlainInstance",
        "id":"objects\/24"
      }
```

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
c0a0c92a5e9533b42a13f76ef9708e82cccfb84d
