### ISSUE TITLE
dartanalyzer doesn't warn about dead code

### ISSUE THREAD

**Issue by mishadynin** [dart-lang/sdk#24997]
I had the following typo/bug in my code, and dartanalyzer didn't warn me about it:

```
void main() {
  var foo;
  // Do stuff...
  foo == null;  // Meant to assign instead!
}
```

I was expecting some sort of warning.
(FWIW, javac reports "error: not a statement" for equivalent code.)

**Comment by bwilkerson** [comment]
A hint would be good.

> FWIW, javac reports ...

True. The Java Language Specification limits the kind of expression that can stand alone as a statement. Dart doesn't.

**Comment by srawlins** [comment]
Dup of #11625.
