### ISSUE TITLE
Please, clarify specification for break

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25005]
The Dart Programming Language Speciﬁcation version 1.9, chapter 17.14 Break reads:

> Let sb be a break statement.
> ...
> If sE is an asynchronous for loop (17.6.3), its associated stream subscription
> is canceled. Furthermore, let ak be the set of asynchronous for loops and **yield-
> each** statements (17.16.2) **enclosing** sb that are enclosed in sE , 1 ≤ k ≤ m,
> where a k is enclosed in a k+1 . The stream subscriptions associated with aj are
> canceled, 1 ≤ j ≤ m, innermost ﬁrst, so that aj is canceled before a j+1 .

The yield-each statement syntax is (according to chapter 17.16.2 Yield-Each):

> yieldEachStatement:
>  yield\* expression ‘;’
> ;

It is not clear, how yield-each statement can enclose break statement. 
If this is possible, please, provide some examples.
If it is not possible, please, update the specification.

**Comment by lrhn** [comment]
Agree, yield*-statements can't enclose a break statement.

**Comment by alsemenov** [comment]
The same issue is in chapter 17.15 Continue:
>If sE is an asynchronous for loop (17.6.3), let ak be the set of asynchronous
>for loops and **yield-each statements (17.16.2) enclosing** sc that are enclosed
>in sE , 1 ≤ k ≤ m, where ak is enclosed in ak+1 .

**Comment by alsemenov** [comment]
I am sorry, I have closed the issue by mistake
