### ISSUE TITLE
2 projects in WebStorm with different versions of a dependency, the first found is used

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25007]
- project p1
  - depencencies: 
    - polymer_interop: 1.0.0-rc.4
- project p2
  - depencencies: 
    - p1: path ..
    - polymer_interop: 1.0.0-rc.5

`pubspec.yaml` of p2 is in `p1/example_/pubspec.yaml`

code navigation (<kbd>Ctrl</kbd>+click) on `import 'package:polymer_interop/polymer_interop.dart';` in a file from `p2` jumps to `polymer_interop: 1.0.0-rc.4`

`new PolymerCollection(columnCheckboxes)` (introduced in version `1.0.0-rc.5`) shows an error and the above import is shown as unused.

**Comment by alexander-doroshko** [comment]
Is `pub get` done for both packages? Do two `.packages` files contain correct (different) paths to `polymer_interop`?

**Comment by zoechi** [comment]
run `pub upgrade --no-package-symlinks` in both projects. It seems analyzer always uses the first one listed in `External Libraries/Dart Packages` (or WebStorm only sends the first one - don't know about details)

**Comment by alexander-doroshko** [comment]
It's analyzer that decides where to jump. Do two `.packages` files contain different paths to `polymer_interop`?

**Comment by zoechi** [comment]
Yup, each contains the path to a different version in `.pub-cache`

**Comment by zoechi** [comment]
Quite old and haven't seen this happen since a long time - going to close.
