### ISSUE TITLE
dartdoc has excpetions when generating docs on bleeding edge

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#25016]
Generation failed: type 'ModelFunction' is not a subtype of type 'Typedef' in type cast.
dart:core                                                     Object._as
package:dartdoc/src/model.dart 410:67                         ModelElement.linkedParams.renderParam
dart:core                                                     Iterable.join
package:dartdoc/src/model.dart 446:46                         ModelElement.linkedParams.renderParams
package:dartdoc/src/model.dart 458:33                         ModelElement.linkedParams
package:dartdoc/src/model.dart 470:40                         ModelElement.linkedParamsNoMetadata
dart:mirrors                                                  _LocalInstanceMirror.getField

**Comment by keertip** [comment]
Looks like the build failure could be this commit 

https://codereview.chromium.org/1447373002

**Comment by IgorMinar** [comment]
angular/angular is affected: https://travis-ci.org/angular/angular/jobs/92375705#L904

**Comment by bwilkerson** [comment]
@jmesserly

**Comment by jmesserly** [comment]
I'm a little confused, isn't dartdoc at https://pub.dartlang.org/packages/dartdoc, https://github.com/dart-lang/dartdoc? or is this a different dartdoc?

Happy to help make dartdoc to work with latest package:analyzer, but not sure where the code for it lives.

The change, for what it's worth: function types in parameters previously pretended to be typedefs (even though there was no corresponding typedef). Now they work more like normal function types (i.e. they are backed by FunctionElement).

**Comment by keertip** [comment]
@jmesserly Yes, dartdoc is at https://github.com/dart-lang/dartdoc. It also ships in the sdk, which is why it gets built with the latest analyzer source.

Thanks for the offer, worked with @bwilkerson  to fix the issue.

**Comment by jmesserly** [comment]
awesome, let me know if I can help!

**Comment by keertip** [comment]
Fixed and updated dartdoc in sdk https://codereview.chromium.org/1468263002/
