### ISSUE TITLE
dartanalyzer --machine flag doesn't escape characters as intended

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25017]
The escapePipe function [1] doesn't actually do anything, because it compares a code unit (int) to a string. As a result, pipe characters and backslashes aren't actually escaped. Example output:

WARNING|STATIC_TYPE_WARNING|NON_BOOL_OPERAND|somefile.dart|867|9|33|The operands of the '||' operator must be assignable to 'bool'

I expected it to be "the '\\|\\|' operator".

Parsing issues are likely to be rare since filenames generally don't contain a '|' character and messages rarely have them.

Maybe the best approach would be to start over with a --json flag, to avoid parsing and printing issues.

[1] https://github.com/dart-lang/sdk/blob/9ae1265ff534c9a189d7ac4cbcbc7b6ca282debc/pkg/analyzer_cli/lib/src/error_formatter.dart#L178

**Comment by bwilkerson** [comment]
We should find out (a) how many customers are depending on this format and (b) whether this bug is causing them problems. Given that the message is always last, it's fairly benign.

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/sdk/commit/1ec13d1548c70d508d2149cd7ecbb9fde9c164e2
