### ISSUE TITLE
Dartium very slow

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25014]
When I run this example of a Grid/Datasheet component https://github.com/bwu-dart/bwu_datagrid/blob/1656186567358b77fbe4567ed33277eae9e83273/example_/web/checkbox_row_select.html
it takes quite a while until the data area is rendered.
The column titles provide a context menu to show/hide columns. When I click a checkbox it takes 10-15 secs until the view is built and Dartium responds to clicks.
When I load the same example with Chrome there is no noticable delay at all.

Both loaded from `pub serve` (using WebStorm)

> Dart VM version: 1.14.0-edge.64e71a0b2e74cbb8a2a840b18fa100007ec1c43f (Fri Nov 20 02:13:48 2015) on "linux_x64"

Dartium

> Dart	1.13.0-edge.517a44348143fc0af59d6f3e49fc7b9a06e5a8f4

I just started again working again on this project (didn't do anything since about 6 weeks), therefore I can't tell what version exactly introduced this slowness.

**Comment by alan-knight** [comment]
With the switch to using JS Interop, things that are doing many calls back and forth could easily slow down compared to calling through C++. We've seen remarkably few performance issue with it so far, but you might have found one. Thanks for the repro.

**Comment by zoechi** [comment]
I can't reproduce today (after update to newest bleeding edge).
I add another comment when I run into it again.
Feel free to close.

**Comment by alan-knight** [comment]
Sounds good to me.
