### ISSUE TITLE
indexed_db multi-store transaction failure

### ISSUE THREAD

**Issue by jptrainor** [dart-lang/sdk#25013]
dart sdk + dartium version: 1.13
os: OSX 10.10.5
 
Indexed_db multi-store transactions stopped working in either Dart 1.12 or 1.13.  I get the following error returned by Dartium when the a transaction is started on multiple object stores:

Test failed: Caught NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

The "One of the specified object stores was not found." is coming back from Dartium when an indexed_dbi.Database.transaction(..) call is performed with multiple object stores. 

I have attached a test that demonstrates the error. This test has worked in all prior version of Dartium that I have tested. Note that this test was created, originally, in order to expose this same issue on other browsers, e.g. Safari where multi-store transactions are not supported. As such, this test has existed and has run without issue on Dartium for quite a while.  Untar the attached file as follows (on OSX):

base64 --decode < testidbmultistorebug.tar.gz.base64.txt | tar tvzf -

(I encoded it as txt to overcome github attachement limitation.)
[testidbmultistorebug.tar.gz.base64.txt](https://github.com/dart-lang/sdk/files/40495/testidbmultistorebug.tar.gz.base64.txt)

Possibly related issue:  compound index keys are also failing as of 1.13. I suspect it is a similar issue arising due to whatever 1.13 changes are causing this problem.

**Comment by alextekartik** [comment]
I just found out this bug after filling a similar (well actually the same plus some sample code right in the bug description) issue #25019. The funny thing is that I also noticed this bug for a test that should only fail in safari...It does indeed breaks many app I have

**Comment by alan-knight** [comment]
Yes, it's missing the appropriate type conversion for a list there. You can work around it by manually inserting the conversion. You call convertDartToNative_SerializedScriptValue, e.g. in the test case

```
  idb.Transaction t = db.transaction(convertDartToNative_SerializedScriptValue([idbMultiStoreTestStoreNameA, idbMultiStoreTestStoreNameB]), 'readwrite');
```

**Comment by alan-knight** [comment]
Fixed in https://codereview.chromium.org/1473443003

**Comment by alextekartik** [comment]
Great! Are there any sanity unittest on this that would validate that this won't break in the future?
