### ISSUE TITLE
Exception: created constructor initializer must call super.created()

### ISSUE THREAD

**Issue by markhats** [dart-lang/sdk#25028]
Just upgraded to 1.13 and now get this exception when some of my custom elements are registered.

Traced it to the following lines in the _hasCreatedConstructor method in html_dartium.dart.
```
var createdSource = methodMirror.source;
superCreatedCalled = createdSource.contains("super.created(");
```
This seems to search for the exact string "super.created(" in the element's constructor which then fails if there is any whitespace before the bracket character. Removing the whitespace seems to fix the problem.

**Comment by kevmoo** [comment]
@markhats is this with Polymer? Which version?

Do you hit this when running in Dartium? dart2js? Both?

**Comment by alan-knight** [comment]
So we can just fix this by running dart_style over the code before running it? :-)

**Comment by kevmoo** [comment]
@alan-knight Or the analyzer :smile:

**Comment by markhats** [comment]
@kevmoo Yes, this is with Polymer v0.15.5+4. It only occurs when running in Dartium. dart2js seems fine.

**Comment by kevmoo** [comment]
@alan-knight This should be easy to fix, no?

We should get a merge-to-stable request to fix this

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1537563006/

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1537563006/

**Comment by kevmoo** [comment]
Closed in https://github.com/dart-lang/sdk/commit/168e9ee882b67e0a61a005ff0c7c9f4b8ca9b81e
