### ISSUE TITLE
VM doesn't treat strings as canonicalized in const expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#25024]
Example:
    const i = identical("ab", "a" + "b");
    print(i);  // false

This should print "true" - both "ab" and "a"+"b" are compile-time constant expressions, and so is calling identical on them. The result of a compile-time constant identical call on two compile-time constant strings should be true if the strings are equal.

It seems to be a problem with String.+. Other ways to dynamically build the string do not have the same problem:
   const j = identical("ab", "${"a"}${"b"}");
   print(j);  // true

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
11a101a325e62aef5f568c8536ede77a6dc2bf94
