### ISSUE TITLE
1.14.0-dev.1.0: spawnUri is not yet supported on background isolates

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25025]
Failure log from Angular 2 build: https://travis-ci.org/angular/angular/jobs/92763702

The only place we use `spawnUri`: https://github.com/angular/angular/blob/646b9200a2ea6373318fd88a83d721d46a571115/modules/angular2/src/web_workers/ui/application.dart#L30

**Comment by iposva-google** [comment]
@turnidge is looking at creating some Dartium special handling.
