### ISSUE TITLE
Dart analysis server, SDK version 1.14.0-dev.1.0, server version 1.12.0, error: Exception from fix contributor: DefaultFixContributor

### ISSUE THREAD

**Issue by TylerThompson** [dart-lang/sdk#25021]
I created a report and sent it through intellij to Jet Brains as well. 
Using intellij IDEA 143.870.1 with dart 1.14.0-dev the Dart Analysis plugin throws the following error. 

Dart analysis server, SDK version 1.14.0-dev.1.0, server version 1.12.0, error: Exception from fix contributor: DefaultFixContributor
           RangeError: Index: 4, Size: 2
           #0      NodeList.[] (package:analyzer/src/generated/ast.dart:12758)
           #1      FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:372)
           #2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:212)
           #3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:52)
           #4      DartFixContributor.computeFixes (package:analysis_server/plugin/edit/fix/fix_dart.dart:37)
           #5      computeFixes (package:analysis_server/src/services/correction/fix.dart:27)
           #6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:164)
           #7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:195)
           #8      AnalysisServer.handleRequest.<anonymous closure...

**Comment by scheglov** [comment]
https://codereview.chromium.org/1468913004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/1e05c35650c3935a6245ef406e18ffa5630f71d0
