### ISSUE TITLE
No completion in 'part'-file after import prefix

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25023]
Major bug report from WebStorm users.
```
library test;
import 'dart:html' as html;
part 'main_part.dart';
```
```
part of test;

html.<caret>
```
![image](https://cloud.githubusercontent.com/assets/4499789/11335665/33c1e094-91ef-11e5-9388-9bacc770aa94.png)

**Comment by zoechi** [comment]
Looks related to #24910 (not about autocompletion but code navigation with prefixes)
