### ISSUE TITLE
Stuck at Resolvers.get

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#25032]
This issue was reported as https://github.com/dart-lang/code_transformers/issues/29 on Nov 3rd, but there is hardly any doubt that it is an analyzer issue.

In some cases the `get` method on an instance of `Resolvers` from 'resolvers.dart' gets stuck, in the sense that the next statement after `await` never gets executed:

``` dart
  Resolvers resolvers = ..;
  Resolver resolver = await resolvers.get(myTransform);
  // not reached
```

The problem is easy to reproduce:

```
  git clone 'https://github.com/dart-lang/reflectable'
  cd reflectable/tool
  git co 64be223a843f31b799b1170de4fe786e0468c32a
  ./bottest
```

This will end in a state where the `pub build --mode=debug test` process is stuck. The actual location where it is stuck is at line 2741 in 'lib/src/transformer_implementation.dart'. Note that the stuck state may hereafter be reproduced much faster by running `pub build --mode=debug test` directly in the 'test_reflectable' subdirectory (`cd ../test_reflectable` in the above setting).

The problem disappears when we use a dependency setting such that the version of the analyzer is 0.26.1+14 rather than anything more recent (just tested with 0.26.3).

Another issue that arises at the same version boundary is that `VariableElementImpl.evaluationResult` returns the expected value in older versions of the analyzer, and null in newer versions starting with 0.26.1+15, and there are probably other issues as well, so we have been forced to insert a non-trivial upper bound in the 'pubspec.yaml's of reflectable, such that we get a version '<=0.26.1+14'.

Because of this, it is necessary to use an older version of reflectable (64be223a843f31b799b1170de4fe786e0468c32a will do, as mentioned) in order to see this issue, because newer versions of reflectable will avoid the post-0.26.1+14 versions of analyzer.

**Comment by eernstg** [comment]
I think we are discussing issues related to this issue in other locations (e.g., https://github.com/dart-lang/code_transformers/issues/31). Maybe we could take it here?

**Comment by bwilkerson** [comment]
@eernstg Has this issue been resolved at this point? If so, please close it.

**Comment by natebosch** [comment]
code_transformers has been deprecated. 

I think there were potential deadlocks when there were import cycles across packages in pub build - not sure if that is what was happening here. In any case this should be fixed by the replacement build system package:build and package:build_runner
