### ISSUE TITLE
Js interop and local vars

### ISSUE THREAD

**Issue by Aetet** [dart-lang/sdk#25033]
Currently js interop works fine with global vars, but what about local vars through closure? If it will support it, then it will has clear exports and require. Because in all module systems that's just 

``` js
function(require, exports, module){
// Here will be transpiled dart code
}
```

If in js interop we can access to local vars like: `require, exports, module` then we can make all require and exports clear to user like:

``` dart
@JS('require')
external Request get requireCommon()

@JS()
class Request {
// definition for node request module
}

@JS('module.exports')
external void set exportsCommon(Exports exports)

@JS()
class Exports {
   external get String a;
}

Request request = requireCommon('request');
new Exports(a: 'Hello')
```

Or we can add new annotation for require:

``` dart
@JSRequire('request')
class Request {}
```

There's some problem with new annotation is what will be cwd ? Current directory with dart file or with compiled dart file.

So we can use js modules like request in dart and exporting code from dart without syntax change.

**Comment by kevmoo** [comment]
@Aetet would you share the API you're trying to work with?

**Comment by Aetet** [comment]
I build my code with webpack, which can understand CommonJS module.
In my js code I can do something like this:
```js
import from '../dart/build/web/main.dart.js'
```
That's good. But I want export some vars from dart code. For example variable `a = 'Hello',
So in js code it will look like this:
```js
import {a} from  '../dart/build/web/main.dart.js'
```

So webpack wrap compiled code of main.dart.js like this:
```js
(function(modules) {
// Operation over modules
})([
// a lot of js modules
// And here will be compiled dart module
function(module, exports, __webpack_require__) {
eval("(function(){compiled dart code})()");
])
```
So if dart code can operate with `module, exports, __webpack_require__` like it operates with global vars in js-interop layer, we can use all benefits from modern module systems like es6 without any pain. So the question is how achieve access to `module, exports, __webpack_require__` from dart code without making them global?

**Comment by kevmoo** [comment]
@Aetet I think I understand. Our focus w/ this first set of work is to enable consumption of JS APIs from within a Dart app.

We want to be able to enable the creation of JS libraries from Dart, but that work will happen later.

I think your request is along those lines...

**Comment by Aetet** [comment]
Is any update on this?

**Comment by kevmoo** [comment]
@jacob314 😃

**Comment by jmesserly** [comment]
merging into https://github.com/dart-lang/sdk/issues/25059
