### ISSUE TITLE
Analysis Server: computedErrors() contains errors for incorrect file

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25034]
Consider this code:
`main.dart`:
```
library test;
part 'main_part.dart';
class A {}
```
`main_part.dart`:
```
class A {}
```
Note that the only error here is that `main_part.dart` file doesn't contain `part of` directive.

The problem is that `AnalysisError` array (or list) passed both to `GetErrorsConsumer#computedErrors` and `AnalysisServerListener#computedErrors` contains errors from different files (and incorrect error is repeated 3 times):
![image](https://cloud.githubusercontent.com/assets/4499789/11373301/9ecbbede-92e2-11e5-9b1a-d8db45a187aa.png)

IDE has the right to assume that all errors in a single `computedErrors()` invocation are for a single file (that was in sent `analysis_getErrors()` request, or given as a 1st argument in `AnalysisServerListener#computedErrors`), but this assumption leads to strange highlighting and glitches with global problems view.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1477553002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/cfb7d61a9cb6dd58d93f3d8e17a4831455a8d971
