### ISSUE TITLE
Analysis Server hangs

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25048]
`Dart VM version: 1.14.0-edge.e3457758ed7e2b24263bcbd9831cd764ce9fd110 (Tue Nov 24 16:05:37 2015) on "windows_x64"`
At some point all DAS driven features stopped working and progress "Dart Analysis..." shown in the IDE became infinite. Attaching latest kilobytes of logs (I had ` --instrumentation-log-file` enabled). I have 1.5Gb more logs from that session if needed. The latest line in logs contains error, after that no lines were appended to the log.
```
"The null object does not have a method 'dispose'.\n\nNoSuchMethodError:: method not found:: 'dispose'\nReceiver:: null\nArguments:: []"
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::45)
#2      ServerContextManagerCallbacks.removeContext (package::analysis_server/src/analysis_server.dart::1507)
#3      ContextManagerImpl._destroyContext (package::analysis_server/src/context_manager.dart::1000)
#4      List.forEach (dart::core-patch/growable_array.dart::233)
#5      ContextManagerImpl.refresh (package::analysis_server/src/context_manager.dart::580)
#6      AnalysisServer.reanalyze (package::analysis_server/src/analysis_server.dart::846)
#7      AnalysisDomainHandler.reanalyze (package::analysis_server/src/domain_analysis.dart::219)
...
```
[das_hang.txt](https://github.com/dart-lang/sdk/files/44921/das_hang.txt)

**Comment by scheglov** [comment]
Yes, could you please archive the log and send it to me.

**Comment by alexander-doroshko** [comment]
Uploaded to Google drive and shared with you. Also there are screenshots of the Analysis Server Status pages taken before server stopped responding but after hanging.

**Comment by scheglov** [comment]
I can (almost) reproduce it.
It takes me two `Reanalyze Dart Source` requests to case the exception.
It seems that the problem happens when you have two analysis roots and one contains another.
That and the fact that we track contexts in `ContextManagerImpl` and `AnalysisServer.folderMap`.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1487903002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/5b2ad27b06940ee1005630d431f7b89db5241b38
