### ISSUE TITLE
dart2js: Poor type-inference for null-aware operators "??" and "??="

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#25043]
In the following program
  __get fred__ is inferred as non-null `[subclass=JSPositiveInt]` but
  __get fran__ is nullable `[null|subclass=JSPositiveInt]`

__get fred__ is as close as you can get to the spec definition of `??=` without using a closure.

The argument __x__ of __dump__ is also nullable, showing the problem is with `??` too.

Obviously we would like to infer a non-nullable type whenever possible on a operator that is usually used to ensure a value is not null.

```dart
main() {
  dump(_fred ?? 99);
  print(fred);
  print(fred);
  print(fran);
  print(fran);
  dump(_fred ?? 99);
}

int tick = 0;
var _fred;
get fred {
  var x = _fred;
  return x == null ? _fred = ++tick : x;
}

var _fran;
get fran => _fran ??= ++tick;

dump(x) {
  print(x);
}

```

**Comment by rakudrama** [comment]
https://codereview.chromium.org/1469353008/

**Comment by zoechi** [comment]
Can you assume that the result is non-null when a null-aware operator is used? What when the alternative expression also resolves to null?

**Comment by lrhn** [comment]
If the alternative can be null, then the entire expression can be null. In the example code above, the alternative can't be null, and the compiler recognizes this in the `fred` case, but not in the `fran` case.

I guess it can be expressed as `isNullable(e1 ?? e2) == isNullable(e1) && isNullable(e2)`, where it seems the current implementation uses `isNullable(e1) || isNullable(e2)` instead.

**Comment by zoechi** [comment]
Thanks for the explanation :)

**Comment by rakudrama** [comment]
CL has been committed.
