### ISSUE TITLE
Compilation of vm fails on debian

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25052]
We build a debian package for release on linux, and it fails with a new compiler warning in
the vm compilation.  This happened in the commit of https://codereview.chromium.org/1439483003
I can get details of the compiler and version with the warning, and add them to the bug.
We can't release a new dev version until this is fixed.

runtime/vm/parser.cc: In static member function ‘static dart::RawObject* dart::Parser::ParseMetadata(const dart::Class&, intptr_t)’:
runtime/vm/parser.cc:1011:11: error: variable ‘thread’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
cc1plus: all warnings being treated as errors

**Comment by zanderso** [comment]
https://codereview.chromium.org/1484653002/

**Comment by zanderso** [comment]
@whesse if the Debian build is good now, could you go ahead and close this? Thanks!
