### ISSUE TITLE
Bug with Timers and the System Clock

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25055]
If I set a timer like this:

```dart
import "dart:async";

main() async {
  var i = 1;
  new Timer.periodic(const Duration(seconds: 1), (_) {
    print("[${new DateTime.now().millisecondsSinceEpoch}] Hello #${i}");
    i++;
  });
}
```

and then spring my system clock forward say 2 or 3 hours, the timer will execute approximately the amount of times it would have executed if I kept it running from the time right before I set the clock to the time I set the clock to.

If I set my clock backwards, the timer will seem to stop.

Setting Clock Forwards: http://cl.ly/3I0a1W15040i
Setting Clock Backwards: http://cl.ly/1Y251F0W2P2P

This is a pretty critical issue, as system time changes can happen for many reasons, one of which includes Out of Box experiences, where the system time can change as a result of a user setting their timezone on a device.

Reproduced with Dart v1.12.2 on ARM

**Comment by lrhn** [comment]
I can see the problem. Dart timers are based on scheduled timeouts - a one second timer sets up a scheduled callback at (now + 1 second). If the system clock then goes back by one hour, that timer isn't due for another one hour and one second.

For periodic timers, the VM timers are isochonous - it schedules a callback every second, independently of whether the timer can run or not. If you have a long-running process that blocks the event loop for two seconds, you will have two expired timers waiting afterwards. So, if you increase the system clock by one hour, the periodic timer will assume that it has been blocked for 3600 seconds and try to catch up.
It's intended behavior that makes sense if you get a little delayed, but for a one hour change, it's not really reasonable.

One "solution" to the latter problem is to drop isochronous timers and just do like JavaScript (which dart2js already does): Only schedule the next event after running the previous one.
That means that if your one-second periodic timer is delayed for two seconds, then it only gets one event afterwards, and the next event will be one second after the end of the callback. Timing will slip over time. 
We should consider doing something like this - but it will be changing the behavior of existing code.

As for the former problem - VM timers being affected by system clock changes - I think it's a problem that the embedder needs to handle somehow, if possible. If you ask for a `new Timer(const Duration(seconds: 2))`, then it should happen two seconds later - there is nothing in the call that suggests that it's affected the actual time of day.

**Comment by ricowind** [comment]
I don't think changing the timezone will have an effect (or daylight savings time for that matter, originally in the bug). The actual underlying clock of the os does not change because of that. Leap seconds will have an effect, but google as well as others will use different solutions to decrease the impact of this, see  
https://googleblog.blogspot.dk/2011/09/time-technology-and-leaping-seconds.html .

In production I would assume all servers/devices to use an ntp server

**Comment by kaendfinger** [comment]
@ricowind We have devices which may run completely offline. The thing that interests me is that the JVM doesn't seem to get tripped up by this. We have Java code that sometimes runs parallel to our Dart code. We have low-power devices running the code, and when the timer tries to catch-up, it causes CPU to go to 100% due to all the events that are being triggered.

**Comment by dglogik** [comment]
That's is precisely the problem for our use-case. We have an init.d service that's starting our Dart process on a raspberry pi. During boot the raspberry pi initially has a default time and then it gets an update from the ntp server and the clock changes. This causes everything to go haywire. Can you recommend a workaround for this use-case as the clock itself is something that is outside of our control.

Dennis Khvostionov

**Comment by iposva-google** [comment]
We are planning to switch the time source for Timer events to be the monotonic time source on the OS. This should resolve these issue with using the system clock for scheduling timer events.

**Comment by kaendfinger** [comment]
@iposva-google Awesome, thanks.

**Comment by rmacnak-google** [comment]
9387fead15f6158abc502702d0091c355d69dec3
fc551b6f330c3d8e0d240dd80a8afeed1bb6d9cb
1a333dcdd2d9a57588926eda89bfa0f1092c9165
2bfdde5c36c9393f38a453a49684e4ba0f5e8b8f

**Comment by kaendfinger** [comment]
Thanks

**Comment by rmacnak-google** [comment]
Windows: 22683803edd6873c6b5c321897d485ecd97f56c2
