### ISSUE TITLE
The ?? operator should be allowed in compile-time constant expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#25054]
Currently `x ?? y` is not a compile-time constant/potentially constant expression, but `x != null ? x : y` is (when `x` and `y` are potentially constant). Since the former is a shorthand for the latter, it should also be compile-time constant.

**Comment by lrhn** [comment]
CL: https://codereview.chromium.org/1493693002/

**Comment by munificent** [comment]
I'm guessing this is done now.
