### ISSUE TITLE
generated dartdocs can't be cleanly unzipped on a Mac

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25056]
To reproduce, download the 1.13.0 API docs from: https://www.dartlang.org/downloads/archive/

Unzip from the command line using "unzip".

The zip file contains files that differ only in case. On a Mac filesystem, this means you can't cleanly unzip the archive. It will complain about having to overwrite files:

replace gen-dartdocs/dart-web_gl/RenderingContext/VIEWPORT.html?
replace gen-dartdocs/dart-html/Window/defaultstatus.html? [y]es, [n]o, [A]ll, [N]one, [r]ename:
replace gen-dartdocs/dart-io/HttpHeaders/EXPIRES.html? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
replace gen-dartdocs/dart-io/HttpHeaders/DATE.html? [y]es, [n]o, [A]ll, [N]one, [r]ename
replace gen-dartdocs/dart-io/HttpHeaders/host.html? [y]es, [n]o, [A]ll, [N]one, [r]ename:

**Comment by sebe** [comment]
Just passing, interesting issue, I had no idea that Mac file system default was case insensitive.

Using date as example i dart-io/HttpHeaders, when I go to the website I can see both html files with chrome.
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/DATE.html
Dart SDK dart:io HttpHeaders DATE CONSTANT DATE
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/date.html
Dart SDK dart:io HttpHeaders date PROPERTY date

A solution would be to put all the constants in a CONSTANT/constant directory
 dart-io/HttpHeaders/constants/DATE.html

**Comment by kevmoo** [comment]
@sebe It's not quite that simple. Dart allows any members to vary only by case. The fact that consts vs variables in this case is the issue doesn't generalize, sadly.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/dartdoc#1045
