### ISSUE TITLE
A static field cannot override another static field

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25057]
Given the following code:

    class A {
      static int F = 0;
    }
    class B extends A {
      static int F = 1;
    }

analysis server is reporting that A.F is overridden by B.F. But static fields do not override other static fields, so this is wrong.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1488443002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/1933891bad7ca8e8c6bb90816c42e9ea633733b7
