### ISSUE TITLE
pub terminates with SIGILL on Raspberry Pi 2

### ISSUE THREAD

**Issue by austincummings** [dart-lang/sdk#25062]
I'm running the Dart build for linux ARM 1.13.0 downloadable from [here](https://storage.googleapis.com/dart-archive/channels/stable/release/1.13.0/sdk/dartsdk-linux-arm-release.zip). I tried to run `pub global activate dhttpd` on my raspberry pi 2 and after a while pub exited with SIGILL and core dumped. I have the core file if that's needed.

**Comment by zanderso** [comment]
@rmacnak-google

**Comment by kaendfinger** [comment]
I can reproduce this too.

**Comment by fsc8000** [comment]
It looks similar very to #24855 . I think the fix for that was not merged to the stable channel yet. Correct, @rmacnak-google ?

**Comment by zanderso** [comment]
@rmacnak-google and I investigated. The fix has not been merged to the stable channel, yet. @rmacnak-google will work on getting it in.

@austincummings @kaendfinger in the meantime it would be helpful to verify that this does not repro on a recent dev release. https://storage.googleapis.com/dart-archive/channels/dev/release/1.14.0-dev.1.0/sdk/dartsdk-linux-arm-release.zip Thanks!

**Comment by austincummings** [comment]
@zanderso yeah it's all working on the dev release.

**Comment by kaendfinger** [comment]
Same here @zanderso, working great with dev channel build.

**Comment by iposva-google** [comment]
Ryan, can you please investigate whether we want to file a merge request to stable for this. Thanks!

**Comment by rmacnak-google** [comment]
#25066
