### ISSUE TITLE
analysis server is very chatty

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25060]
When starting up, with a few medium sized projects loaded, we receive ~4000 messages from the server until the initial analysis is complete. Most of them are of the form:

```
{"event":"analysis.errors","params":{"file":"/Users/devoncarew/projects/atom/dartlang/test/utils_test.dart","errors":[]}}
```

The client already knows there aren't errors for the reported files, so this notification could be omitted. If we don't report 0 errors for files where the client already knows or assumes 0 errors, we could cut the initial communication from ~4000 messages to ~40.

**Comment by bwilkerson** [comment]
Not all clients assume that files have zero errors. Dart Editor, for example, used to cache the errors between sessions and depended on getting an update if the file had changed.

That said, we could reduce the traffic by not sending a zero-length notification if the previous notification contained zero errors.

**Comment by devoncarew** [comment]
we're not going to take any action here
