### ISSUE TITLE
Please merge revisions 3fa0cae & b837d63 into stable channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25068]
@whesse @mit-mit @kasperl

This is to fix a crash in dart2js related to js-interop (issue #24974)

This requires 2 cherry-picks:
* https://github.com/dart-lang/sdk/commit/3fa0cae192dce46aef1c9040e8782702aa1e2d9c (most of the change)
* https://github.com/dart-lang/sdk/commit/b837d63d47aed38ceae39b78ba4d04048475d0e5 (a follow up fix)

Note this doesn't merge cleanly. I created [CL 1485823004][1] with all the necessary changes. In particular,
* the first merge has a conflict, to resolve I had to delete the conflicting lines (conflict was a modify-vs-delete)
* Some APIs changed since the stable channel was cut, I changed the code where the API was different. These API changes are the diff between patchset 1 and patchset 2 of the attached CL.

[1]: https://codereview.chromium.org/1485823004/

**Comment by sigmundch** [comment]
It seems we need this merged to the dev channel as well. I haven't tested if it merges cleanly yet, if it doesn't, most likely the fixes are the same than those needed in the stable channel.

**Comment by whesse** [comment]
We are still doing full pushes to dev channel, so it won't need a merge.

**Comment by sigmundch** [comment]
ah ok - FWIW, there was no conflict for dev channel: I was able to cherry-pick both changes without a problem.

**Comment by whesse** [comment]
Merged in 1.13.1
