### ISSUE TITLE
Analyzer: null pointer exception in search.findElementReferences

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25063]
Atom 1.2.0 dartlang 0.4.15 Dart SDK 1.3.0

While attempting to find references to a named constructor, a red dialog box appeared showing an Analyzer stack trace. Unfortunately this dialog doesn't support copy and paste (see https://github.com/dart-atom/dartlang/issues/587#issuecomment-160522557), so here's an excerpt:

```
method: search.findElementReferences, id: 177
The null object does not have a getter 'constructors'
IndexableElementKind.forElement indexable_element.dart:166
IndexableElement.kind
ElementCode.encodeHash code.dart:126
SplitIndexStore.getRelationships split_store.dart:880
...
ElementReferencesComputer._findSingleElementReferences
```

(Reanalyzing sources fixed it.)

**Comment by bwilkerson** [comment]
@devoncarew Any chance we could make it easier for users to send us the stack traces being reported through this dialog?

**Comment by devoncarew** [comment]
Yup, it's possible to add a button to the dialog and post the stacktrace to a github url. Can you file an issue on https://github.com/dart-atom/dartlang to track this?

**Comment by scheglov** [comment]
@skybrian Do you remember what were you searching? And in which codebase?

**Comment by skybrian** [comment]
I was working on a side project on the plane. It happened in the middle of a big refactoring, so not easy to reproduce at this point.

**Comment by scheglov** [comment]
Cannot reproduce.
