### ISSUE TITLE
make the `diagnostic.getDiagnostics()` call stable

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25061]
Once the API settles down, we'll need to mark the API as stable. That'll make it safe for clients to call.

**Comment by devoncarew** [comment]
blocked on https://github.com/dart-lang/sdk/issues/24932

**Comment by devoncarew** [comment]
Here's what we're showing now:

<img width="304" alt="screen shot 2015-12-03 at 9 29 34 am" src="https://cloud.githubusercontent.com/assets/1269969/11568379/8afab968-99a0-11e5-8870-294aca5b419c.png">

This does a good job of showing the analysis server resources. It polls the diagnostic call once a second while the status view is open.

I don't see any more breaking changes to this API; any additional work would be additional, backwards compatible functionality. Once #24932 is resolved, we should look at declaring the API stable.

**Comment by bwilkerson** [comment]
How useful is this information to users? Have you gotten any feedback (like "What's all this extra noise? It makes me want to close the status view." or "This is really interesting, but I don't know what to do with it." or "This is really helpful; now I know when to force the server to reboot!")?

**Comment by devoncarew** [comment]
It hasn't rolled out to users yet, not in this work. I don't really expect to get much feedback from users about it.

I find it useful to know how 'large' a project is, from the pov of the analysis server. When I open the futter project, the number of contexts goes to 20, and the number of analyzed files to 10k+.

**Comment by bwilkerson** [comment]
> I don't really expect to get much feedback from users about it.

I'm confused then. I thought the purpose of the diagnostic information was to inform users when there was a problem they needed to respond to. Maybe the purpose has shifted... Let's talk offline sometime.

**Comment by devoncarew** [comment]
I don't think we'll get feedback about this particular feature, even if it adds value for users. It's not the type of thing they'll send feedback about.

**Comment by pq** [comment]
@devoncarew : to confirm, you're good with this API as it stands?  That is, from your perspective we can bump it to `STABLE`?

**Comment by bwilkerson** [comment]
I have a concern with making the API stable at this point. Let's talk offline.

**Comment by devoncarew** [comment]
@pq: yes, this is good for what I need.

**Comment by bwilkerson** [comment]
Thanks for the conversation. Concerns allayed.

**Comment by pq** [comment]
https://codereview.chromium.org/1509033003/

**Comment by devoncarew** [comment]
:metal:
