### ISSUE TITLE
Precompilation fails to reset fields not reached during tree shaking

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25075]
E.g., RawReceivePort _packagesPort in dart:_builtin during standalone/package/package_test, which leads to a crash attempting to snapshot the receive port.

**Comment by rmacnak-google** [comment]
Related: 4d9a399f53f3414f9551541bc3798bb54c677536

**Comment by mraleph** [comment]
The issue seems stale.
