### ISSUE TITLE
Assert failure in VM after commit of https://codereview.chromium.org/1410383020/

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25077]
On the debug buildbots, an assert is failing in the test vm/cc/PrintJSON

FAILED: none-vm debug_ia32 vm/cc/PrintJSON
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

stdout:
Running test: PrintJSON

stderr:
/Volumes/data/b/build/slave/vm-mac-debug-ia32-be/build/sdk/runtime/vm/object.cc:7578: error: expected: cls.LookupField(field_name) == this->raw()

void Field::PrintJSONImpl(JSONStream* stream, bool ref) const {
  7526   JSONObject jsobj(stream);	  7575   JSONObject jsobj(stream);
  7527   Class& cls = Class::Handle(owner());	  7576   Class& cls = Class::Handle(owner());
  7528   String& field_name = String::Handle(name());	  7577   String& field_name = String::Handle(name());
  7529   ASSERT(cls.LookupField(field_name) == this->raw());	  7578   ASSERT(cls.LookupField(field_name) == this->raw());
  7530   field_name = String::EncodeIRI(field_name);	  7579   field_name = String::EncodeIRI(field_name);
  7531   AddCommonObjectProperties(&jsobj, "Field", ref);	  7580   AddCommonObjectProperties(&jsobj, "Field", ref);
  7532   jsobj.AddFixedServiceId("classes/%" Pd "/fields/%s",	  7581   jsobj.AddFixedServiceId("classes/%" Pd "/fields/%

**Comment by mhausner** [comment]
I am looking at this. Thank you for the heads-up!

I will remove the ASSERT to turn the bot green and then look into the
matter further.


Matthias

**Comment by johnmccutchan** [comment]
ping

**Comment by mhausner** [comment]
The problem was that the test collected all Field objects it finds on the heap and prints them. Some fields happen to be metadata fields which are no longer stored in the top-level class. Thus, the lookup in the ASSERT fails. The assertion has become to aggressive, so removing was the right thing to do.
