### ISSUE TITLE
Unable to pass List to Worker.postMessage in dartium v1.13

### ISSUE THREAD

**Issue by rwl** [dart-lang/sdk#25074]
In `dartium-lucid64-full-stable-1.13.0.0` you can no longer pass a `List` to `Worker.postMessage`. I get this error:
```
Exception: DataCloneError: Failed to execute 'postMessage' on 'Worker': An object could not be cloned.
```
It works with dart2js.
In dartium if you pass the list to `new JsObject.jsify` it works, but in Firefox the worker then 

seems to receive `{_jsObject: [foo, bar], $builtinTypeInfo: [null]}`

**Comment by rwl** [comment]
I have created a simple project to illustrate this issue:

https://github.com/rwl/dart_sdk_issue_25074

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1490763005

**Comment by alan-knight** [comment]
Thanks. Should be fixed in bleeding edge as soon as that change gets built.
