### ISSUE TITLE
Null deref message is misleading

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25079]
I tried to null-deref a variable called `_from`, in the expression `_from.settings.mostValuableKeys`. The error message is:

```
 The null object does not have a getter 'settings'.

 NoSuchMethodError: method not found: 'settings'
 Receiver: null
 Arguments: []
 Stack trace:
 #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
 #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
 #2      HeroController._getMostValuableKeys (packages/flutter/src/widgets/hero_controller.dart:91)
 #3      HeroController._updateQuest (packages/flutter/src/widgets/hero_controller.dart:99)
 #4      Scheduler.invokeCallback (packages/flutter/src/animation/scheduler.dart:90)
 #5      Scheduler.beginFrame (packages/flutter/src/animation/scheduler.dart:81)
 #6      _beginFrame (engine/src/out/android_Debug/gen/sky/bindings/Customhooks.dart:45)
```

This is a highly misleading message. It brings all the focus of the attention to the identifier `settings` (note how `_from` isn't even mentioned), and it repeats five times that the problem is that something (a getter once, a method four times) doesn't exist. The word "null" is only mentioned twice, once to refer to a "null object", and once to refer to a "receiver".

At no point does this just say "`_from` was null" or "attempted to dereference a null value" or anything like that.

I would like to recommend that `noSuchObject` on `Null` be more helpful, e.g. throwing a "NullDereferenceError" error or some such, rather than a "NoSuchMethodError" error. (For back-compat, maybe "NullDereferenceError" could inherit from "NoSuchMethodError", just with a more useful error message.)

Ideally, it would even say what variable was null, though I understand that that is significantly more complicated.

**Comment by lrhn** [comment]
Arguably can be seen as `area-library` since all the spec says about Null is 
> Invoking a method on null yields a NoSuchMethodError unless the method is explicitly implemented by class Null

We can add a `NullError` as a subclass of `NoSuchMethodError`, throw it in `Null.noSuchMethod` and still satisfy the spec.

**Comment by floitschG** [comment]
However, it wouldn't give a nice error message, on what was the receiver. Ideally, the VM (unfortunately dart2js has a harder time doing that), should report on a foo.bar, that "foo" is null. That is, it helps to have both the receiver as well as the selector.

**Comment by Hixie** [comment]
Another option is for the VM to expose the "last successfully dereferenced variable name" in a secret API that Null can get to.

**Comment by lrhn** [comment]
I don't think adding an overhead on all variable dereferencing is worth it. An improvement should be a cost only when it's actually used. Also, not all nulls come from variables. you can have:
   foo().bar();
if foo() returns null, then the expression that is unecxpectedly null is "foo()", not a variable.
So, if anything, it should be Null.noSuchMethod that looks back on the stack and figures out which expression evaluated to a call on null.

**Comment by Hixie** [comment]
It now says:

```
NoSuchMethodError: The getter 'settings' was called on null.
Receiver: null
Tried calling: settings
 Stack trace:
 #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
 #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
 #2      HeroController._getMostValuableKeys (packages/flutter/src/widgets/hero_controller.dart:91)
 #3      HeroController._updateQuest (packages/flutter/src/widgets/hero_controller.dart:99)
 #4      Scheduler.invokeCallback (packages/flutter/src/animation/scheduler.dart:90)
 #5      Scheduler.beginFrame (packages/flutter/src/animation/scheduler.dart:81)
 #6      _beginFrame (engine/src/out/android_Debug/gen/sky/bindings/Customhooks.dart:45)
```

...which is an improvement, but it still doesn't mention that `_from` was null, which is really what matters.

**Comment by greglittlefield-wf** [comment]
Agreed, this error can be quite misleading; I see it trip up our developers quite frequently.

**Comment by mraleph** [comment]
This issue seems stale. No work has happened in this area for 2 years. Closing this - please reopen if it still matters to you.
