### ISSUE TITLE
Analyser ignores return type of emulated function `call()`

### ISSUE THREAD

**Issue by aabluedragon** [dart-lang/sdk#25078]
Using version 1.14.0-dev.1.0 and the Webstorm IDE:

In this case, the analyser will not emit a warning (and no auto-complete options show up in WebStorm):

```
class EmuFunc {
  int call()=>1;
}
main() {
  EmuFunc e = new EmuFunc();
  String a = e(); // Not complaining about `int` != `string`
}
```

The analyser will warn only if not under the `main()` scope.

```
class EmuFunc {
  int call()=>1;
}
EmuFunc e = new EmuFunc();
String a = e(); // Will show warning as expected
```

**Comment by greglittlefield-wf** [comment]
Looks like the analyzer doesn't check the arguments, either:
```dart
typedef Test(bool arg1, int arg2);

 main() {
   Test test;
   
   test('not bool', 'not int'); // type warning as expected
   test(); // required argument warning as expected
   
   test.call('not bool', 'not int'); // no warnings
   test.call(); // no warnings
}
```

**Comment by greglittlefield-wf** [comment]
Actually, mine was a typedef and it still didn't work...

**Comment by srawlins** [comment]
Analyzer now correctly reports on the call to `e()` in the orignal example:

> A value of type 'int' can't be assigned to a variable of type 'String'.

And on the 4x calls in @greglittlefield-wf 's example:

> The argument type 'String' can't be assigned to the parameter type 'bool'.
> The argument type 'String' can't be assigned to the parameter type 'int'.

> 2 positional argument(s) expected, but 0 found.

> The argument type 'String' can't be assigned to the parameter type 'bool'.
> The argument type 'String' can't be assigned to the parameter type 'int'.

> 2 positional argument(s) expected, but 0 found.
