### ISSUE TITLE
canvas.measureText.width returns int sometimes

### ISSUE THREAD

**Issue by andrey-zakharov** [dart-lang/sdk#25080]
According to MDN: TextMetrics.width is double.
Its true for dart almost all the time. But attached test fails.
width gives 13 as integer for canvas font "13px Roboto" and text "00":
```
import 'package:test/test.dart';
import 'dart:html';

main() {
  test("TextMetrics.width", () {
    var canvas = document.createElement('canvas');
    var context = canvas.getContext('2d');
    context.font = '13px Roboto';
    expect( context.measureText("test").width.runtimeType, double );
    expect( context.measureText("00").width.runtimeType, double );
  });
}
```

[textmetrics_test.dart.txt](https://github.com/dart-lang/sdk/files/49080/textmetrics_test.dart.txt)

**Comment by andrey-zakharov** [comment]
It gives me
```
pub run test -pdartium  test/textmetrics_test.dart 
00:03 +0 -1: TextMetrics.width                                                                     
  Expected: ?:<double>
    Actual: ?:<int>
  
  package:test                expect
  textmetrics_test.dart 10:5  main.<fn>
  
00:03 +0 -1: Some tests failed.                
```

**Comment by zoechi** [comment]
JavaScript has only double only Dart distinguishes between int and double. 
I think this is a dup of #https://github.com/dart-lang/sdk/issues/24882

**Comment by kevmoo** [comment]
The type of `width` is num – one shouldn't assume it's either double or int, per @zoechi 

https://api.dartlang.org/1.13.0/dart-html/TextMetrics-class.html
