### ISSUE TITLE
Pub yaml file should allow tabs

### ISSUE THREAD

**Issue by blakemcbride** [dart-lang/sdk#25084]
When I use pub with a yaml containing tabs, I get:

    Error on line 2, column 1 of pubspec.yaml: Tab characters are not allowed as indentation.
	    dquery: any
    ^

Why not?  Seems rather arbitrary.  Tabs are convenient to line things up.  Can't you treat tabs as just some space characters?

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/19975954/a-yaml-file-cannot-contain-tabs-as-indentation

**Comment by kevmoo** [comment]
Yup http://www.yaml.org/faq.html
