### ISSUE TITLE
Analyzer doesn't hint if assert lambda return value isn't a boolean expression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25085]
This code should have an analyzer warning but does not:

``` dart
void main() { assert(() { return 0; }); }
```

```
$ dartanalyzer test.dart
Analyzing [test.dart]...
No issues found
$ dart --checked test.dart
Unhandled exception:
type 'int' is not a subtype of type 'bool' of 'boolean expression'.
#0      main (test.dart:2:22)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
$
```

**Comment by lrhn** [comment]
It can only be a hint. It's not a language warning because the actual return type of the function is `dynamic` which is assignable to `bool`.
If you had used `assert(() => 0)` the return type would be `int`, and you would get a warning.

**Comment by Hixie** [comment]
alternatively, we could change the spec...

**Comment by bwilkerson** [comment]
The spec has been changed for Dart 2.0 such that closures are no longer supported, so this would appear to be a non-issue. Please re-open if I'm wrong.
