### ISSUE TITLE
SDK missing dart2js

### ISSUE THREAD

**Issue by blakemcbride** [dart-lang/sdk#25082]
The docs say the SDK includes dart2js.  It doesn't.  I installed dart2js after a search for the correct (tools?) download.  Now I am home.  I've spend 20 minutes looking for the download.  Please either include dart2js in the standard sdk, or make it easy to find.  Find someone who doesn't know anything about dart and see how hard dart2js is to find.  Follow where they look and place a link at each place!  Please!

**Comment by srawlins** [comment]
Please tell us how you installed the SDK.

Also what is this "tools?" download that _did_ include dart2js?

**Comment by blakemcbride** [comment]
I am on Linux.  I used the apt-get setup.  I just found dart2js in /usr/lib/dart/bin
There is nothing in https://www.dartlang.org/downloads/linux.html
telling me to set the path.  It shouldn't be in there anyway.  You should install it to 
/usr/bin

**Comment by blakemcbride** [comment]
Earlier I found some zip that had dart2js.  I unzipped it into /usr directory (probably eliminating one dirsctory in the archive).  That worked.  Knowing what I know now, I think I may have just unpacked a zip file and manually put it in the right place.  I think it should either be put in the right place (/usr/bin) or the docs should be clear about setting the path.

**Comment by blakemcbride** [comment]
/usr/lib/dart needs to be moved to /usr or /usr/local
since it already has sub-directories of bin, include, lib...

**Comment by blakemcbride** [comment]
You have a link from /usr/bin/dart to /usr/lib/dart/bin/dart
Why not setup similar links for dart2js and friends?

**Comment by blakemcbride** [comment]
Setting up a link doesn't work either because then you get:
Unhandled exception:
Load Error for "file:///usr/bin/snapshots/dart2js.dart.snapshot": Error loading file:///usr/bin/snapshots/dart2js.dart.snapshot:
  FileSystemException: Cannot open file, path = '/usr/bin/snapshots/dart2js.dart.snapshot' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:147)
#1      _asyncLoadError (dart:_builtin:559)
#2      _handleLoaderReply (dart:_builtin:362)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

**Comment by blakemcbride** [comment]
The following lines fixes the problem:

cd /usr/lib/dart
cp -rp * /usr/local

**Comment by blakemcbride** [comment]
But, of course, apt-get update won't work...

**Comment by whesse** [comment]
There was a discussion about this on dart misc mailing list, I think. I
will find the duplicate issues for this and link them, and reference the
discussion on the list.  We should see if we should reconsider our decision
to only link to dart executable, and make the requirement to add the dart
directory to the path more explicit.

**Comment by blakemcbride** [comment]
Thanks.  Just want to help reduce resistance.  Sure this is all very simple once you know what you are doing.  But it needs to be easy upfront or you loose new people.

**Comment by blakemcbride** [comment]
I think the bottom line is this, do whatever you want.  Just make it easy to figure out how to get a basic setup to work.  If people need to setup links or copy files or setup an environment variable, tell us.  Then, in every place we might look, point us to the answer.

**Comment by diaafayed72** [comment]
I installed flutter in window 10 but dart2js missed

**Comment by mraleph** [comment]
> I installed flutter in window 10 but dart2js missed

It's now `dart compile js`, there is no standalone `dart2js` binary. 

Also don't comment on random issues from the past.
