### ISSUE TITLE
"using namespace"

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25088]
Library prefixes are a nice feature in Dart but sometimes it clutters the source.
C++ uses namespaces - this would be a cool feature for Dart.

Sample: (assume mypackages defines Type which is also defined in dart:core)

``` dart
import "package:mypackage/mypackage.dart" as mp;
...
using namespace mp;
Typ.<whatever...> ... Uses mp.Type
```

**Comment by zoechi** [comment]
I usually use `import '...' show Xxx;`. This way I don't have to use prefixes, only when there are name collisions and then namespaces wouldn't help neither.

**Comment by lrhn** [comment]
If the request is to make a library *locally* accessible, e.g., only inside a function or a particular piece of code, then it makes sense.
```foo() { with(mp) { .... Type.something() ... Type.other() .. } } ```
(this will still only work with library prefixes, not objects).

**Comment by munificent** [comment]
I'm not sure what the request is here. You can import a library without a prefix.

Is this about scoping an import to within a block?

**Comment by natebosch** [comment]
Closing since it's not clear what the request is and it has been without update for a long time. If this is still something we'd should consider supporting please add a comment clarifying the request.
