### ISSUE TITLE
many completions can be followed with a space

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25090]
Some of the jetbrains editors I use, follow completions with a space if that is possible. It is may be as small thing, but I really like that.

For example, most keywords  can be automatically followed by a space. Also, when declaring a variable, classes can be followed by a space.

**Comment by alexander-doroshko** [comment]
Whether it should be done at Analysis Server side or at IDE side is a subject to discuss.
Also: when you are typing in the middle of something, auto-adding a space may result in duplicated space if required space was already there.
I just wanted to emphasize that the feature is not that trivial. Indeed in some other languages supported by the JetBrains' IDEs space auto-inserting on code completion is sometimes performed (as well as semicolon auto-insert, etc.), but AFAIK corresponding logic is rather complicated. I do not know all details yet unfortunately.

**Comment by kasperpeulen** [comment]
@alexander-doroshko Oh I see now. I thought it would be trivial for cases like `import, void, var, if, while, for, switch`, but yes, if you change some type of a function to `void` then it may have two spaces. That would be a bit strange yes.

**Comment by jwren** [comment]
To be consistent, and avoid situations where two spaces are inserted (above), or where users expect no space, so they add space out of habit, I am closing this issue.
