### ISSUE TITLE
Win64 flaky test failure vm/cc/TimelineAnalysis_ThreadBlockCount

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25091]
@johnmccutchan 

http://build.chromium.org/p/client.dart/builders/vm-win64-release-be/builds/9124/steps/checked_tests/logs/stdio

=== Failure summary:

FAILED: none-vm-checked release_x64 vm/cc/TimelineAnalysis_ThreadBlockCount
Expected: Pass 
Actual: Fail
CommandOutput[run_vm_unittest]:

stdout:
Running test: TimelineAnalysis_ThreadBlockCount
Done: TimelineAnalysis_ThreadBlockCount

stderr:
vm\timeline_test.cc:383: error: expected: <00000000006F8620> but was: <00000000006FAC40>
vm\timeline_test.cc:384: error: expected: <00000000006FAC40> but was: <00000000006F8620>
vm\timeline_test.cc:406: error: expected: LabelMatch(it.Next(), "B1")
vm\timeline_test.cc:408: error: expected: LabelMatch(it.Next(), "B2")
vm\timeline_test.cc:410: error: expected: LabelMatch(it.Next(), "B3")
vm\timeline_test.cc:412: error: expected: LabelMatch(it.Next(), "A1")

Command[run_vm_unittest]: set DART_CONFIGURATION=ReleaseX64 & build\ReleaseX64\run_vm_tests --ignore-unrecognized-flags TimelineAnalysis_ThreadBlockCount
Took 0:00:00.033000

Short reproduction command (experimental):
    python tools/test.py -mrelease --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t60 vm/cc/TimelineAnalysis_ThreadBlockCount

===
=== 1 test failed
===

**Comment by johnmccutchan** [comment]
I believe this was fixed by waiting for 32 milliseconds instead of 1 millisecond. On Windows a sleep of 1 millisecond may be a no-op.
