### ISSUE TITLE
Really confusing parser and analyzer output when you do "Map<X, Y>{...}"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25096]
The following code, at first glance, doesn't seem wrong. Of course, it is, because Map literals are of the form `<...>{}`, not `Map<...>{}`. But, imagine being in the mindset where you think the code is right.

```dart
void test(Map map) { }

void main() {
  test(Map<String, String>{ '': '' });
}
```

In that mindset, the analyzer's output here is extremely confusing:

```
Analyzing [test.dart]...
[warning] 1 positional arguments expected, but 2 found (test.dart, line 5, col 7)
[warning] The operator '<' is not defined for the class 'Type' (test.dart, line 5, col 11)
[warning] The operator '>' is not defined for the class 'Type' (test.dart, line 5, col 26)
3 errors found.
```

The runtime output is not much better:
```
Unhandled exception:
Class '_Type' has no instance method '<'.

NoSuchMethodError: method not found: '<'
Receiver: Type: class 'Map'
Arguments: [Type: class 'String']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      main (test.dart:5:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

The analyzer and the compiler both for some reason think the `<` is an operator, rather than being either the delimiter for the type parameter of the `Map` type, or the delimiter for the type parameter of the map literal.

I would have expected an analyzer warning along the lines of "Unexpected `{` after type `Map<String, String>`". (Maybe, for bonus points, followed by "If you meant to start a Map literal, do not include the word `Map` before the type parameters".)

**Comment by lrhn** [comment]
We do have the problem that the grammar is valid. It is equivalent to `test((Map < String), (String > { '': '' }));`. Only long after parsing can we see that the operands are type objects, so you probably didn't mean to parse it that way.

On the other hand, we will need to be able to parse it as a type parameter if we want to have generic functions, so we might as well start now. That means that we need to parse the same code in two different ways, and pick the right one based on the value of some of the sub-expression - either parse them both at start, or go back and reparse later. 
It shouldn't be impossible (generic functions depends on it).

**Comment by Hixie** [comment]
Oh, interesting, I hadn't noticed it could be parsed that way. Good point.

```dart
void test(Map map) { }

void main() {
  test(
    Map < String,
    String > { '': '' }
  );
}
```

I guess the analyzer could detect this, but yeah, if it's valid code, the compiler probably couldn't...

**Comment by bwilkerson** [comment]
Yes. The goal would not be to eliminate warnings, just change the multiple existing unhelpful warnings into a single "Map literals are not allowed to specify the type 'Map'" warning (with a quick fix to remove the name 'Map').

**Comment by srawlins** [comment]
Dup of #4348, where we agree to fix both Map and List.
