### ISSUE TITLE
 The null object does not have a method 'accept'.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25092]
https://github.com/bwu-dart/bwu_polymer_routing `polymer1` branch
is a repo. 
I run `pub run grinder` (with strong-mode disabled, not tried with strong-mode enabled)

> myuser@mypc ~/dart/bwu_polymer_routing
 (polymer1) $ pub run grinder
Wrong script snapshot version, expected '3acc9c3982c3d8bb80ce2ca34a4be0fa' found '0cf29d77ab95cd4861fbb07ce569ae91'
grinder running [analyze] [check-format] [lint] [test] [check]
>
[analyze]
  dartanalyzer lib/di.dart lib/static_keys.dart lib/bind_view.dart lib/module.dart lib/bind_route.dart test/some_test.dart
     tool/grind.dart
  Analyzing [lib/di.dart, lib/static_keys.dart, lib/bind_view.dart, lib/module.dart, lib/bind_route.dart, test/some_test.d
    art, tool/grind.dart]...
  Unhandled exception:
  AnalysisException: Cannot compute DART_ERRORS for /home/myuser/dart/bwu_polymer_routing/lib/di.dart
  Caused by Unexpected exception while performing GenerateLintsTask for source /home/myuser/dart/bwu_polymer_routing/lib/d
    i.dart
  #0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
  #1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
  #2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
  #3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
  #4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:675)
  #5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
  #6      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
  #7      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
  #8      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
  #9      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
  #10     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
  #11     Driver.start (package:analyzer_cli/src/driver.dart:107)
  #12     main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
  #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
  #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  >
  Caused by The null object does not have a method 'accept'.
  >
  NoSuchMethodError: method not found: 'accept'
  Receiver: null
  Arguments: [Instance of '_VisitoHelper']
  #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
  #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
  #2      Visitor.visitMethodDeclaration (package:linter/src/rules/type_annotate_public_apis.dart:101)
  #3      DelegatingAstVisitor.visitMethodDeclaration.<anonymous closure> (package:analyzer/src/generated/visitors.dart:47
    5)
  #4      Iterable.forEach (dart:core/iterable.dart:218)
  #5      DelegatingAstVisitor.visitMethodDeclaration (package:analyzer/src/generated/visitors.dart:475)
  #6      MethodDeclaration.accept (package:analyzer/src/generated/ast.dart:12173)
  #7      NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
  #8      ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4419)
  #9      DelegatingAstVisitor.visitClassDeclaration (package:analyzer/src/generated/visitors.dart:116)
  #10     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349)
  #11     NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
  #12     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
  #13     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/src/generated/visitors.dart:144)
  #14     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
  #15     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:2822)
  #16     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
  #17     AnalysisTask.perform (package:analyzer/task/model.dart:210)
  #18     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
  #19     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
  #20     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:675)
  #21     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
  #22     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
  #23     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
  #24     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
  #25     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
  #26     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
  #27     Driver.start (package:analyzer_cli/src/driver.dart:107)
  #28     main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
  #29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
  #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  >
  >
  #0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
  #1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
  #2      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
  #3      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
  #4      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
  #5      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
  #6      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
  #7      Driver.start (package:analyzer_cli/src/driver.dart:107)
  #8      main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
  #9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
  #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
dartanalyzer failed with:
exit code: 255
>
stdout:
>
Analyzing [lib/di.dart, lib/static_keys.dart, lib/bind_view.dart, lib/module.dart, lib/bind_route.dart, test/some_test.dart, tool/grind.dart]...
>
>
stderr:
>
Unhandled exception:
AnalysisException: Cannot compute DART_ERRORS for /home/myuser/dart/bwu_polymer_routing/lib/di.dart
Caused by Unexpected exception while performing GenerateLintsTask for source /home/myuser/dart/bwu_polymer_routing/lib/di.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:675)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
#6      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
#7      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
#8      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
#9      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
#10     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
#11     Driver.start (package:analyzer_cli/src/driver.dart:107)
#12     main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
Caused by The null object does not have a method 'accept'.
>
NoSuchMethodError: method not found: 'accept'
Receiver: null
Arguments: [Instance of '_VisitoHelper']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Visitor.visitMethodDeclaration (package:linter/src/rules/type_annotate_public_apis.dart:101)
#3      DelegatingAstVisitor.visitMethodDeclaration.<anonymous closure> (package:analyzer/src/generated/visitors.dart:475)
#4      Iterable.forEach (dart:core/iterable.dart:218)
#5      DelegatingAstVisitor.visitMethodDeclaration (package:analyzer/src/generated/visitors.dart:475)
#6      MethodDeclaration.accept (package:analyzer/src/generated/ast.dart:12173)
#7      NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
#8      ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4419)
#9      DelegatingAstVisitor.visitClassDeclaration (package:analyzer/src/generated/visitors.dart:116)
#10     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349)
#11     NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
#12     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
#13     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/src/generated/visitors.dart:144)
#14     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#15     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:2822)
#16     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#17     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#18     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#19     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
#20     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:675)
#21     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
#22     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
#23     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
#24     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
#25     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
#26     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
#27     Driver.start (package:analyzer_cli/src/driver.dart:107)
#28     main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
>
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:608)
#2      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:125)
#3      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:161)
#4      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:119)
#5      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:516)
#6      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:168)
#7      Driver.start (package:analyzer_cli/src/driver.dart:107)
#8      main (file:///mnt/data/b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
#0      run (package:grinder/src/run.dart:46:5)
#1      Analyzer.analyze (package:grinder/grinder_sdk.dart:349:5)
#2      main.<anon> (file:///home/myuser/dart/bwu_polymer_routing/tool/grind.dart:13:35)
#3      analyze (package:bwu_grinder_tasks/bwu_grinder_tasks.dart:22:25)
#4      _LocalLibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1286)
#5      _LocalObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:364)
#6      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#7      _rootRun (dart:async/zone.dart:907)
#8      _CustomZone.run (dart:async/zone.dart:802)
#9      runZoned (dart:async/zone.dart:1245)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:115:12)
#11     GrinderTask.execute (package:grinder/grinder.dart:189:27)
#12     Grinder._executeTask (package:grinder/grinder.dart:404:23)
#13     Grinder.start.<anon> (package:grinder/grinder.dart:379:16)
#14     Future.forEach.<anon>.<anon> (dart:async/future.dart:336)
#15     Future.Future.sync (dart:async/future.dart:168)
#16     Future.forEach.<anon> (dart:async/future.dart:336)
#17     Future.Future.sync (dart:async/future.dart:168)
#18     Future.doWhile.<anon> (dart:async/future.dart:361)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#20     _RootZone.bindUnaryCallback.<anon> (dart:async/zone.dart:1116)
#21     Future.doWhile (dart:async/future.dart:367)
#22     Future.forEach (dart:async/future.dart:334)
#23     Grinder.start (package:grinder/grinder.dart:378:21)
#24     cli (package:grinder/src/cli.dart:67:39)
#25     Function._apply (dart:core-patch/function_patch.dart:7)
#26     Function.apply (dart:core-patch/function_patch.dart:28)
#27     FunctionScript._getTopCommandResult (package:unscripted/src/script_impl.dart:156:67)
#28     DeclarationScript._handleResults (package:unscripted/src/script_impl.dart:107:21)
#29     ScriptImpl.execute.<anon>.<anon> (package:unscripted/src/script_impl.dart:49:11)

.

> Dart VM version: 1.14.0-edge.d0ea4371c9bab943b31b41299e1627e48a22e1f3 (Tue Dec  1 17:47:48 2015) on "linux_x64"

.

> Wrong script snapshot version 

seems unrelated. When I run again I get the same exception.

**Comment by zoechi** [comment]
just saw, looks like dart-lang/linter#151

**Comment by pq** [comment]
> just saw, looks like dart-lang/linter#151

Yep.  Thanks @zoechi! :+1:

**Comment by pq** [comment]
Fixed in https://github.com/dart-lang/linter/commit/978780db714597558c754c53b9bf7b4bedbef4d1, published as version `0.1.9` to [pub](https://pub.dartlang.org/packages/linter), landed in the SDK as of 94f73224c044e4f95774308e75b529b8a71013e7.
