### ISSUE TITLE
Precompilation: hotness is a bad inlining heuristic without counter feedback

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25097]
@sgmitrovic @fsc8000 

Consider 

removeme1(x) {
  return x;
}
removeme2() {
  return true;
}

main() {
  print(removeme1("Hello"));
  print(removeme2());
}

Under noopt, neither removeme is inlined because they don't meet the hotness heuristic.

Static Calls (4)
  => Function 'removeme1': static. (deopt count 0)
     Bailout: cold 0.000000
  => Function 'print': static. (deopt count 0)
     Bailout: cold 0.000000
  => Function 'removeme2': static. (deopt count 0)
     Bailout: cold 0.000000
  => Function 'print': static. (deopt count 0)
     Bailout: cold 0.000000

But they should be inlined because they are tiny leaf functions.

**Comment by fsc8000** [comment]
Agreed. I have experimented a liitle with setting the hot/cold threshold to 0, and instead using a smaller size budget when precompiling. We need to keep code size somewhat under control - larger methods often slow down especially on ARM.

**Comment by rmacnak-google** [comment]
899046e4fc88aeb57db68c660e46026c4931bc30
