### ISSUE TITLE
When type annotation doesn't match assignment, offer quick fix to change annotation

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25095]
Considering this case: `String x = 1;` which is clearly a warning.

Asking for quick fixes, I see these options:

![screen shot 2015-12-02 at 3 20 09 pm](https://cloud.githubusercontent.com/assets/5479/11547404/56b5b3d0-9908-11e5-96ea-a4b84480c010.png)

I'd love to see a "Change String to int type annotation" as a fix.

Also, the second Quick Fix (split variable) doesn't actually fix the problem. After I apply that "fix", the warning persists.

Thanks!

**Comment by scheglov** [comment]
None of the two displayed items is a Quick Fix, they're both Quick Assists.
It is just happened accidentally that the first one also fixes the issue.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1492053004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/5f49df16445a8affe539ee9e614eafad1d82e7c1

**Comment by sethladd** [comment]
> None of the two displayed items is a Quick Fix, they're both Quick Assists.

Sorry, I don't know the difference between the two. I saw these options when I hit Control-1 on the warning. What's the difference between an assist and a fix?  (cc @devoncarew )

Also, thanks for the "quick" fix! :)

**Comment by bwilkerson** [comment]
A quick *fix* is a code change that is suggested because of an error. For example, you type `new Foo()` when there is no class named 'Foo' and server will suggest that you create a class named 'Foo'.

A quick *assist* is a code change that is suggested because it might be useful. For example, you use a block style documentation comment `/** ... */` and server will suggest converting it to a line style comment `/// ...`.

**Comment by devoncarew** [comment]
In atom, we show both types when the user hits `ctrl-1`. We sort quick fixes first; there's a slight difference in their presentation.

**Comment by scheglov** [comment]
The same in IDEA - fixes first, then assists.

![image](https://cloud.githubusercontent.com/assets/384794/11567913/5bad8b74-999e-11e5-9b98-16ebd5e45a2c.png)
