### ISSUE TITLE
Type variable warning on static generic method

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25094]
The following code produces a bogus warning that type parameters are not allowed on static members:

```dart
class C {
  static /*=T*/ f/*<T>*/() => null;
}
```

`[warning] Static members cannot reference type parameters (/Users/leafp/tmp/scratch.dart, line 2, col 13)`

dartanalyzer version 1.14.0-edge.daf5f6d258a99428cc4dc9ff17645a33e4e4bebd

**Comment by jmesserly** [comment]
ah, yup. That is likely happening from error verifier. We'll need to refine the check:
```dart
class C<E> {
  static /*=T*/ f/*<T>*/(E e) => null;
}
```
usage of "E" should be an error but not "T"

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1508183002/
