### ISSUE TITLE
required parameters end up in completion list (with high relevance)

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25107]
This first completions seems strange to me:

![image](https://cloud.githubusercontent.com/assets/1035299/11575765/19adf95a-9a13-11e5-8a2a-543195d0efcd.png)

I thought it was a bug, but it doesn't seems like that when I look at the code:
https://github.com/dart-lang/sdk/blob/c2b70c90545f2804718053579ea773311890a0cb/pkg/analysis_server/lib/src/services/completion/arglist_contributor.dart#L210

When I press enter, to complete, I get this:
![image](https://cloud.githubusercontent.com/assets/1035299/11575777/2c810b8a-9a13-11e5-9ca3-6fc4f3fcd175.png)

What is the ratio behind this? I would think only named parameters should end up in the completion list?

**Comment by danrubel** [comment]
Fix as part of #25197
