### ISSUE TITLE
Analyzer, please help me more when telling me the overridden signature doesn't match

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25108]
```
[warning] Must have at least 1 parameters to match the overridden method from 'ModalRoute' (main.dart, line 104, col 10)
```

What parameter? Ideally, I'd want the analyzer to tell me the signature of the method I'm trying to override, so I can copy-and-paste it without having to open the other file. Alternatively, it could give me a link to the file where it's defined, as in:

```
[warning] Must have at least 1 parameters to match the overridden method from 'ModalRoute' (main.dart, line 104, col 10)
[hint] 'ModalRoute.buildPage()' is defined here (routes.dart, line 96, col 1)
```

Or both. :-)

**Comment by bwilkerson** [comment]
It would also be nice to have a quick fix that would add the parameter.

Is there information we could pass to clients so that they could allow easy navigation to the referenced method?

**Comment by scheglov** [comment]
@Hixie What IDE do you use?
It is already possible to navigate to the overridden method, even if the overriding method does not have parameters in line with it.

![image](https://cloud.githubusercontent.com/assets/384794/11598089/b4482eb6-9a74-11e5-8d32-14c6078e9fce.png)

**Comment by Hixie** [comment]
I use Emacs, configured to parse analyzer logs so it can jump to any file/line/col in the logs.

**Comment by scheglov** [comment]
I think adding full method signatures will make error messages too long.

It should be easy to navigate to the overridden method knowing its name and defining class even in non-IDE editors.

**Comment by Hixie** [comment]
I don't see how it could be easy without dart-specific tooling nor why it would be better to have to go look it up rather than just having the analyzer give you the answer.

**Comment by scheglov** [comment]
Almost all Dart developers use IDEA, and reporting too long error messages is useless for them.
Moreover, it will force them to change the message column width in the Dart Analysis view.

You could for example comment the method out and use Quick Fix to create it with the correct signature. See `edit.getFixes` in the [Analysis Server protocol](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/spec/spec_input.html).

**Comment by sethladd** [comment]
> Almost all Dart developers use IDEA

This may be true for Googlers, but we're seeing growth of Atom for Dart development. Not everyone uses IDEA :)

**Comment by scheglov** [comment]
Does Atom support `analysis.overrides` notification to jump to overridden methods?

**Comment by Hixie** [comment]
I don't think that question matters. What about people using Nano? Or Notepad? Or Vim in an ssh session to one machine with the analyzer being run in a Travis buildbot?

**Comment by sethladd** [comment]
> Does Atom support analysis.overrides notification to jump to overridden methods?

cc @devoncarew

**Comment by scheglov** [comment]
https://codereview.chromium.org/1509693002

**Comment by bwilkerson** [comment]
> I think adding full method signatures will make error messages too long.

Another alternative to consider: Add this information to the "correction" message. (Yes, I know that the correction message isn't being displayed in very many places, but that's a different issue.) Something like:

    [warning] Must have at least 1 parameters to match the overridden method from 'ModalRoute' (main.dart, line 104, col 10)
    [suggestion] Make the parameters match those defined for Route.buildPage (routes.dart, line 96, col 1).

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/dad4baa7827e2557ba4eb7df2a83d369b3f8bdf4

**Comment by sethladd** [comment]
Cool, thanks!
