### ISSUE TITLE
Analyzer is so slow

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25109]
I know the Flutter repo is a lot of code, but it's taking 30 seconds to analyze the whole repo, and that's sad making. :-(

```
ianh@ianh:~/dev/flutter$ time flutter analyze --flutter-repo
No analyzer warnings!

real    0m26.235s
user    0m27.168s
sys     0m1.021s
ianh@ianh:~/dev/flutter$ 
```

(`flutter analyze` runs analyzer on a single dart file that imports, directly or indirectly, every dart file in the flutter repository.)

**Comment by pq** [comment]
Looking into this through the lens of directory-aware analysis (#25129), allowing us to better target analysis (e.g., no more `--package-warnings`).

**Comment by Hixie** [comment]
Same machine today is now a minute and a half:

```
$ time flutter analyze --flutter-repo
Analyzing 180 entry points...
No analyzer warnings! (ran in 95.5s)

real    1m35.765s
user    1m41.639s
sys     0m1.574s
$ 
```

To be fair, there's more code, and we do more analysis now. But this is definitely harming our edit/refresh cycle.

**Comment by devoncarew** [comment]
Phil did a lot of work here in Q1/Q1; I'm going to close this as the time is much better:

```
Analyzing 835 files...
No analyzer warnings! (ran in 23.2s; 56 public members lack documentation)
```

**Comment by Hixie** [comment]
I agree that it is much better, but it is still very slow.

**Comment by Hixie** [comment]
For example. In the 80s, I could compile a ten line Pascal program in milliseconds.  Today, on a raspberry pi, a ten line dart program takes many seconds to analyze.
