### ISSUE TITLE
Please merge commit dff13bef8de104d33b04820136da2d80f3c835d7 to dev and stable.

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25105]
Commit dff13bef8de104d33b04820136da2d80f3c835d7

It is purely removing code - so should merge cleanly.

It fixes a crash bug in the VM that is present for quite a long time (at least since Jan'15).

**Comment by mit-mit** [comment]
Removing merge-to-dev as we have been doing weekly merges for dev.

**Comment by whesse** [comment]
Merged in 1.13.1
