### ISSUE TITLE
JS Interop doesn't catch when a Event has a detail field.

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#25119]
With the following commit https://github.com/Polymer/polymer/commit/da71dfeb54f9a8e2fe92c8113d853bf0723d457a Polymer isn't firing CustomEvents anymore. Instead it appends a .detail to an Event object. This breaks the an attempt at rolling the 1.2.3 version of Polymer.js.

I'm guessing as pub serving some changes to conversions_dartium.dart but it feels like something along the lines of

```
    var jsTypeName = js.JsNative.getProperty(constructor, 'name');
    if (jsTypeName is! String || jsTypeName.length == 0) {
      // Not an html type.
      js.setDartHtmlWrapperFor(jsObject, jsObject);
      return jsObject;
    } else if ((jsTypeName == 'Event') && (js.JsNative.hasProperty(jsObject, 'detail'))) {
      jsTypeName = 'CustomEvent';
    }
```

in `wrap_jso_no_SerializedScriptvalue` would do the trick.

@jakemac53

**Comment by donny-dont** [comment]
Somewhat related https://github.com/dart-lang/sdk/issues/23680

**Comment by donny-dont** [comment]
This change also seemed to break IE https://github.com/Polymer/polymer/issues/3014

**Comment by donny-dont** [comment]
```
jsObject = [object Event]
 [[JavaScript View]] = Event
  bubbles = false
  cancelBubble = false
  cancelable = false
  clipboardData = undefined
  currentTarget = bindings-element
  defaultPrevented = false
  detail = Object
  eventPhase = 2
  path = NodeList[1]
  returnValue = true
  srcElement = bindings-element
  target = bindings-element
  timeStamp = 1449272183744
  type = "my-object-changed"
  __proto__ = Event
 [[class]] = JsObjectImpl
```

That's the value passed into `wrap_jso_no_SerializedScriptvalue` when calling notifyPath in the following polymer_interop test https://github.com/dart-lang/polymer_interop/blob/1.0.0-rc.5/test/polymer_base_test.dart#L323

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.

(I believe you'll need to use `package:js`, not `dart:js`, going forward)
