### ISSUE TITLE
Classes that implement abstract mixins have double values when debugging.

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25116]
from https://youtrack.jetbrains.com/issue/WEB-17066

<img src="https://cloud.githubusercontent.com/assets/1035299/11597060/67376e4e-9ab9-11e5-82a6-1b9b473a7daf.png" width="50%">
I think the picture is quite well describing the problem. Also see this gist to reproduce the problem:

https://gist.github.com/anonymous/626e085a78e3a933fe6b

I would expect that the debugger would only 1 time show the `one` property.

**Comment by bwilkerson** [comment]
The object actually has two fields with the same name, so it seems appropriate to me that the debugger would let me see that. It would be nice if there were some UI to tell me the classes in which identically named fields are declared, but that's a separate issue.

**Comment by kasperpeulen** [comment]
@bwilkerson Not sure I understand the details of this. But if I `new Foo().one` I get the value `1`. And if I ask for `new Foo().two`, I get the value `2`. So it seems to me that in this object, the `one` variable in the `Mixin` class is overriden by the `one` variable in the `Foo` class. That is how I often use abstract mixins.

I don't see why I would ever want to know  the value `one = null` value that is effectively overriden.

**Comment by kasperpeulen** [comment]
If I write this code slightly different, I don't get two `one` fields in the debugger:
![image](https://cloud.githubusercontent.com/assets/1035299/11599305/6041fc00-9ac6-11e5-8634-478444ed82ae.png)

**Comment by bwilkerson** [comment]
> If I write this code slightly different, I don't get two one fields in the debugger

Right. Because `Foo` no longer mixes in `Mixin` it no longer get the extra field.

> Not sure I understand the details of this.

Even though only one of the fields is accessible, there are still two fields allocated in the object. (Which means it's using more memory than it needs to.) I'd just prefer to have the debugger tell me what the actual structure of the object looks like rather than which fields are accessible.

**Comment by kasperpeulen** [comment]
> Right. Because Foo no longer mixes in Mixin it no longer get the extra field.

Oh oops. I see now. 

> Even though only one of the fields is accessible, there are still two fields allocated in the object. (Which means it's using more memory than it needs to.) I'd just prefer to have the debugger tell me what the actual structure of the object looks like rather than which fields are accessible.

Okay, I guess that is a good point. I thought this worked differently. I see this is actually some lack of knowledge of me from the language. It works the same with extending an object I see now, it is not really something about mixins.

![image](https://cloud.githubusercontent.com/assets/1035299/11600573/d7ddbe46-9acd-11e5-9f33-900ad40ed2b7.png)

In the editor it says, I'm overriding the variable `myInt` in the abstract class. So I thought this meant, that the variable in the abstract class would get the value `2`. But in reality, it seems that it is more "hiding" the variable in the abstract class. This feels a bit weird to me. Why would you need really "override" the value? Now you have two variables, and only one is used?

**Comment by kasperpeulen** [comment]
Okay, I close this, I guess I need to read more about the dart language ;)
