### ISSUE TITLE
Redirecting constructor with body reported as external constructor

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#25113]
The analyzer reports a misleading warning when a redirecting constructor has a body.

For the code below, it reports: "External constructor may not have a body"

It should have been something like: "Constructor with redirection may not have a function body"

```dart
class Foo {
  final x;
  Foo(this.x);
  Foo.bar(x) : this(x) {
    print('Hello');
  }
}
```

**Comment by lrhn** [comment]
Technical term is "redirecting generative constructor", but I'm not sure that will mean much to users.
We have redirecting factory constructors too, and they also don't have bodies, so just "Redirecting constructor must not have a body".

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1709013004/
