### ISSUE TITLE
pkg/analysis_server/test/analysis_server_test appears flaky

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25112]
I just noticed that this test appears flaky, but I'm not certain.
For example, this unrelated change: https://github.com/dart-lang/sdk/commit/346e0da5dbcba6688f224e11528ba71d3a107f73, produced this buildbot failure:

https://build.chromium.org/p/client.dart/builders/pkg-linux-debug-be/builds/2846/steps/pkg%20tests/logs/stdio

**Comment by bwilkerson** [comment]
@danrubel Is this the test that you recently fixed, or is this a different problem?

**Comment by danrubel** [comment]
I increased the threshold, which *appears* to have solved this issue.
https://codereview.chromium.org/1508523002/diff/1/pkg/analysis_server/test/analysis_server_test.dart
