### ISSUE TITLE
Update `optionsProcessed` API to pass "raw" maps.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25126]
Currently the expectation is that we pass options of type `Map<String,YamlNode>` which is not compatible with the type of map we get when merging embedded options with user-defined ones.

This blocks: #25115.

**Comment by bwilkerson** [comment]
Is there any way to get better type information? Should we pre-process the YamlNodes into something that *is* compatible?

**Comment by pq** [comment]
> Is there any way to get better type information? Should we pre-process the YamlNodes into something that is compatible?

I've puzzled about this but I'm not sure.  The rub is that yaml (and the options format) is so open-ended.  For example, a valid value might be a string, bool, list or map.  In the end, I don't see any way to sensibly process options without a bunch of `is` checks.  I'm not sure there's that much value in passing in anything other than `Map<String,dynamic>`.  Needless to say, thoughts appreciated!

**Comment by bwilkerson** [comment]
Aside from a general like for type annotations :-) I'm a bit concerned that processors will end up needing to be written like this:

    if (value is YamlNode) {
      // logic for parsing raw yaml nodes
    } else if (value is Map) {
      // nearly identical logic for parsing a map
    }

because it has to handle both raw inputs and merged inputs. I hate the idea of having to duplicate large amounts of logic. Maybe a wrapper around one form or the other that makes them look the same?

**Comment by pq** [comment]
:)

I feel you.  I believe that `YamlMap`s can be treated *nearly* as simple maps for the purposes of processing.  IOW: I think we can get away with only a few checks.  I'll explore this though and follow-up.

**Comment by pq** [comment]
Analyzer API: ee310b6aff6e0844f3ffafd1b240fae38612b77c.
Linter update: https://github.com/dart-lang/linter/commit/97a27c37e549510966c1f5256f84586152ba6371.
Linter and error filter config fixes in flight: https://codereview.chromium.org/1503353002/
