### ISSUE TITLE
try/poi/serialize test is broken

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25125]
@fsc8000 @peter-ahe-google 

The --no-opt change broke serialization in try/poi.  The test is in tests/try/poi/serialize_test.dart, and the status is in tests/try/try.status.

The failure can be reproduced with tools/test.py -mrelease -rvm -cnone try/poi/serialize

The expected string has line breaks, and the produced one doesn't, or vice versa.
The commits where the test started failing on the buildbot are:
Change #43285

Changed by	fschneider@google.com
Changed at	Fri 04 Dec 2015 04:08:14
Repository	https://chromium.googlesource.com/external/github.com/dart-lang/sdk.git
Project	sdk-master
Branch	master
Revision	2b7ff6dfaba9723ee1fa467554b8c2fd4b42ae29
Comments

Fix test by removing the --noopt flag from the test file.
Not all platforms (ia32) support --noopt, and test.py --noopt will run the test
with this option anyway.

TBR=rmacnak@google.com

BUG=

Review URL: https://codereview.chromium.org/1497213002 .
Changed files

tests/language/vm/precompiled_static_initializer_test.dart

**Comment by fsc8000** [comment]
I don't see how my change affected that test. Are you sure that you bisected correctly?

**Comment by fsc8000** [comment]
bisected to fc868df0045d67de8fe5feb81264e839dd5a9b05 @sigurdm

**Comment by sigurdm** [comment]
Proposed fix: https://codereview.chromium.org/1498963004/
