### ISSUE TITLE
Completion should order based on surrounding context

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25124]
Create a file with the following code:

    class Ca {}
    class Cb {}
    class Cc {}
    class Cd {}
    class Ce {}
    class Cf {}

    void main() {
      Cf c = new C
    }

and request completions after the last 'C'. It would be nice for the suggestion for `Cf` to be at the top of the list, given that (a) that's the known type of the left-hand side of the assignment, (b) that type is a concrete type, and (c) none of the types that currently show up above it are assignable to `Cf`.

**Comment by jwren** [comment]
Duplicate of #26254 which is now fixed.
