### ISSUE TITLE
Remove (crufty)`analyzer_cli` pub package.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25128]
_From @zoechi on November 19, 2015 8:10_

> $ pub global activate analyzer_cli
> Package analyzer_cli is currently active at version 1.1.2.
> Resolving dependencies... (7.4s) 
> - analyzer 0.26.2+1
> - analyzer_cli 1.1.2
> - args 0.13.2
> - async 1.4.0
> - charcode 1.1.0
> - cli_util 0.0.1+2
> - collection 1.1.3
> - convert 1.0.1
> - crypto 0.9.1
> - csslib 0.12.2
> - dev_compiler 0.1.11
> - glob 1.0.5
> - html 0.12.2
> - http_parser 1.1.0
> - js 0.6.0
> - linter 0.1.7
> - logging 0.11.2
> - mime 0.9.3
> - package_config 0.1.3
> - path 1.3.7
> - plugin 0.1.0
> - pub_semver 1.2.3
> - shelf 0.6.4+2
> - shelf_static 0.2.3+1
> - source_maps 0.10.1
> - source_span 1.2.1
> - stack_trace 1.5.0
> - string_scanner 0.1.4
> - typed_data 1.1.1
> - utf 0.9.0+2
> - watcher 0.9.7
> - when 0.2.0
> - which 0.1.3
> - yaml 2.1.7
>   Precompiling executables... 
>   Loading source assets... 
>   Failed to precompile analyzer_cli:analyzer:
>   Unhandled exception:
>   Load Error for "package:dev_compiler/strong_mode.dart": Failure getting http://localhost:46341/packages/dev_compiler/strong_mode.dart:
>   404 Not Found
>   #0      _asyncLoadErrorCallback (dart:_builtin:147)
>   #1      _asyncLoadError (dart:_builtin:559)
>   #2      _handleLoaderReply (dart:_builtin:362)
>   #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
> 
> Dart VM version: 1.14.0-edge.a689bf41805c251b5bae646e0eb82f832d1e309f (Wed Nov 18 17:36:06 2015) on "linux_x64"

_Copied from original issue: dart-lang/analyzer_cli#80_

**Comment by taisph** [comment]
Still fails with `Pub 1.18.1` leaving `pub global` in a broken state:

```
 pub global deactivate analyzer_cli
Cannot open file, path = '/home/user/.pub-cache/global_packages/analyzer_cli/pubspec.lock' (OS Error: No such file or directory, errno = 2)
 pub global list
Cannot open file, path = '/home/user/.pub-cache/global_packages/analyzer_cli/pubspec.lock' (OS Error: No such file or directory, errno = 2)
```

Updated original error output:
```
 pub global activate analyzer_cli
Resolving dependencies... (6.3s)
+ analyzer 0.26.2+1 (0.27.4 available)
+ analyzer_cli 1.1.2
+ args 0.13.5
+ async 1.11.1
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.9.0
+ convert 2.0.1
+ crypto 0.9.1 (2.0.1 available)
+ csslib 0.13.2
+ dev_compiler 0.1.13 (0.1.24 available)
+ glob 1.1.3
+ html 0.12.2+2 (0.13.0 available)
+ http_parser 3.0.2
+ js 0.6.0
+ linter 0.1.9 (0.1.23 available)
+ logging 0.11.3+1
+ mime 0.9.3
+ package_config 0.1.5 (1.0.0 available)
+ path 1.3.9
+ plugin 0.1.0 (0.2.0 available)
+ pub_semver 1.3.0
+ shelf 0.6.5+2
+ shelf_static 0.2.4
+ source_maps 0.10.1+1
+ source_span 1.2.3
+ stack_trace 1.6.6
+ stream_channel 1.5.0
+ string_scanner 1.0.0
+ typed_data 1.1.3
+ utf 0.9.0+3
+ watcher 0.9.7+3
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.10
Downloading analyzer_cli 1.1.2...
Downloading plugin 0.1.0...
Downloading cli_util 0.0.1+2...
Downloading which 0.1.3...
Downloading when 0.2.0...
Downloading package_config 0.1.5...
Downloading dev_compiler 0.1.13...
Downloading html 0.12.2+2...
Downloading pub_semver 1.3.0...
Downloading shelf_static 0.2.4...
Downloading http_parser 3.0.2...
Downloading linter 0.1.9...
Downloading js 0.6.0...
Downloading shelf 0.6.5+2...
Downloading stream_channel 1.5.0...
Downloading mime 0.9.3...
Downloading crypto 0.9.1...
Downloading source_maps 0.10.1+1...
Downloading stack_trace 1.6.6...
Downloading analyzer 0.26.2+1...
Precompiling executables...
Loading source assets...
Failed to precompile analyzer_cli:analyzer:
Unhandled exception:
Could not import "package:dev_compiler/strong_mode.dart" from "package:analyzer_cli/src/driver.dart": Failure getting http://localhost:45095/packages/dev_compiler/strong_mode.dart:
  404 Not Found
null
```

**Comment by pq** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
I suspect that at least one of the listed packages has an invalid dependency constraint. The file `strong_mode.dart` was moved from the dev_compiler package to the analyzer package at some point. I suspect that pub has selected a version of dev_compiler after the file was removed and a version of some package that depended on it being there that wasn't updated to reflect that fact. But I have no idea which package has the wrong constraint.

Given that neither analyzer, analyzer_cli or analysis_server (no longer, if ever) depends on dev_compiler, I don't think this is a problem for the analyzer team. I do think that `pub` should not break if it encounters a problem, so it's at least an issue for that team.

**Comment by pq** [comment]
It's also worth pointing out that the `analyzer_cli` package isn't really designed to be run via pub.  I'm guessing that the published version is ***very*** old...

**Comment by kevmoo** [comment]
@pq is there any good reason to have it published? Might be worth removing – or at least warning people to stay away

**Comment by pq** [comment]
Great question.  I think we should remove it altogether ideally.  It's really not designed for popular consumption.  Looking at the package I notice that @vsmenon uploaded it (way back).  I'm guessing it's not longer being used (since it's so wildly out of date).  But worth checking with him.

**Comment by vsmenon** [comment]
Yeah, I don't think we need it any more.  I think this is from before it was in the SDK proper?

**Comment by pq** [comment]
That sounds right.

**Comment by pq** [comment]
@kevmoo : I'm not sure about the process for removal...  can you help with that?

**Comment by kevmoo** [comment]
Needs https://github.com/dart-lang/pub-dartlang-dart/issues/289

**Comment by kevmoo** [comment]
needs dart-lang/pub-dartlang-dart#289

**Comment by pq** [comment]
@jakobr-google, @mit-mit: can you do this?  Or should I open a new issue somewhere?

**Comment by kevmoo** [comment]
You can mark it "discontinued" on the package site – file an issue https://github.com/dart-lang/pub-dartlang-dart/issues/new

We should delete the code out of the SDK, too!

**Comment by pq** [comment]
Thanks @kevmoo!

Closing in favor of: https://github.com/dart-lang/pub-dartlang-dart/issues/1399.

> We should delete the code out of the SDK, too!

We still use that; it's just the package that doesn't make sense.
