### ISSUE TITLE
Upgrade to Dart 1.13 --> Exception when using dart:web_sql

### ISSUE THREAD

**Issue by bwnyasse** [dart-lang/sdk#25121]
Just upgraded to Dartium 1.13.0 and now get this exception :

<pre>
 Uncaught Unhandled exception:
The null object does not have a method 'call'.

NoSuchMethodError: method not found: 'call'
Receiver: null
Arguments: [Instance of 'SqlTransaction', Instance of 'SqlResultSet']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SqlTransaction.executeSql.<anonymous closure> (dart:web_sql:412)
</pre>

'I remain on Dartium 1.12.2 release to avoid this error'

**Comment by hterkelsen** [comment]
Can you please provide some code that reproduces this issue?

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
