### ISSUE TITLE
Observatory doesn't work (Windows 8.1, SDK 1.14)

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25127]
I start app with `--pause_isolates_on_start --enable-vm-service:57411` VM options and open Observatory page in Chrome (while app is alive of course). The page is just empty. Tired both with 1.14-dev.1.0 and with today's 1.14-edge builds. 

Works fine on Mac. Didn't try on Linux. With SDK 1.13 it works fine on Windows as well.

**Comment by fsc8000** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
5805cba963e4b0c8ff1d5a11f245b23b7aa110f8

**Comment by alexander-doroshko** [comment]
Works fine with today's nightly SDK, thanks for the quick fix!
