### ISSUE TITLE
analyze all Dart files in a directory or a package

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25129]
_From @zoechi on November 13, 2015 9:44_

I find it rather useless to analyze one dart file at a time. 
I want to analyze an entire pub package or at least a list of directories.

``` bash
dartanalyzer lib bin web tool example
```

Ideally it would just analyze all files that match `include`/`exclude` globs in `.analysis_options` by

``` bash
dartanalyzer
```

_Copied from original issue: dart-lang/analyzer_cli#79_

**Comment by pq** [comment]
This would be very useful to flutter.  As an interim solution they're synthesizing a `main()` that collects analysis targets but that hits snags with `package` imports (see https://github.com/flutter/flutter/issues/1680 and https://github.com/dart-lang/sdk/issues/25722).

**Comment by devoncarew** [comment]
Removing the high label; more of the analysis (for Flutter) will go through the analysis server.

**Comment by sethladd** [comment]
I just ran into a case where I wanted to do this.

**Comment by pq** [comment]
This should actually work.

For example:

    dartanalyzer lib

or:

    dartanalyzer .

should do the right thing.

Optimistically closing.
