### ISSUE TITLE
Surface TODOs separately from other warnings

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25132]
_From @Andersmholmgren on November 7, 2015 23:43_

Currently (in Intellij at least) the TODOs are marked as warnings indistinct from other warnings. It would be nice to see 

```
3 TODOs
4 typos
1 warning
```

I am assuming that the analyzer is not surfacing this information. If it is then I will refile in the dart plugin for intellij

_Copied from original issue: dart-lang/analyzer_cli#77_

**Comment by pq** [comment]
_From @bwilkerson on November 8, 2015 4:22_

The analysis server sends back a different error kind for TODO's, so IntelliJ should be able to display them differently.

**Comment by alexander-doroshko** [comment]
TODOs highlighted as warnings in IntelliJ IDEA is a bug at IDE side that is already fixed.
