### ISSUE TITLE
Document lint rule set configuration.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25137]
_From @pq on October 13, 2015 15:33_

Lint rules can be enabled via `.analysis_options` and the syntax needs to be documented.

```
linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - library_names
    - super_goes_last
```

_Copied from original issue: dart-lang/analyzer_cli#70_

**Comment by pq** [comment]
_From @zoechi on October 13, 2015 19:22_

And the list of lint rule names. Looks like #69 is about this, right?

**Comment by bwilkerson** [comment]
@pq Is this still needed?

**Comment by zoechi** [comment]
https://www.dartlang.org/guides/language/analysis-options should do it
The linter packages readme also contains this link
