### ISSUE TITLE
Analyzer doesn't warn when you export a non-existent symbol

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25154]
This has no warnings or anything:
```dart
export 'dart:core' show	HaHaYouAreFunny;
void main() { }
```

Having at least a hint here would greatly help when we do refactorings and renamings.

**Comment by bwilkerson** [comment]
Duplicate of #21030

**Comment by Hixie** [comment]
I don't think #21030 is the same bug as this. That bug is about not warning when the imported symbols aren't used. This bug is about exported symbols being non-existent.

**Comment by bwilkerson** [comment]
Ok, that makes sense.

**Comment by srawlins** [comment]
CR out for review: https://codereview.chromium.org/1901923002/

**Comment by srawlins** [comment]
New analyzer hints UNDEFINED_SHOWN_NAME in 53bf36acdb4a6a12addf15eba06eacdab7552f22.
