### ISSUE TITLE
Support colorized output.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25151]
_From @pq on April 22, 2015 20:34_

Moved from http://dartbug.com/23166: 

The mojo project runs the `dartanalyzer` as part of its build step. I've gotten very used to Clang's user-friendly errors with a colorization that makes it easy to parse at a glance (see screenshot).

The dart analyzer errors on the other hand get lost in the build spew and require more hunting.

In addition to colorization, some other clang-inspired ideas that'd be helpful:
1. Change the format to lead with the file name, ie.
   
   ../../examples/png_viewer/png_viewer.cc:73:16: error: unknown type name 'string'; did you mean 'String'?
2. Add hints and pointers to the column number, ie.
   
   static const string kMaxZoomPercentage = 400;
                ^~~~~~
                String

_Copied from original issue: dart-lang/analyzer_cli#14_

**Comment by pq** [comment]
![clangcolors](https://cloud.githubusercontent.com/assets/67586/7284702/56a67cc2-e8f4-11e4-84e2-6a82e1bd16e1.png)

**Comment by devoncarew** [comment]
The colorization aspect of this is done.
