### ISSUE TITLE
Only exceptions from dartanalyzer with latest bleeding_edge 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25159]
> 22:32:07 Throwable: Dart analysis server, SDK version 1.14.0-edge.032c829246c071a96f218bbc02b17f4db5729a27, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for /home/myuser/dart/bwu_docker/lib/src/shared/json_util.dart in /home/myuser/dart/bwu_docker/lib/src/shared/json_util.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:685)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#2      DartAssistContributor.computeAssists. (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask. (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback. (dart:async/zone.dart:733)
#8      _rootRun (dart:as... (show balloon)
22:32:09 Throwable: Dart analysis server, SDK version 1.14.0-edge.032c829246c071a96f218bbc02b17f4db5729a27, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for /home/myuser/dart/bwu_docker/lib/src/shared/data_structures.dart in /home/myuser/dart/bwu_docker/lib/src/shared/data_structures.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:685)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#2      DartAssistContributor.computeAssists. (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask. (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback. (dart:async/zone.dart:733)
#8      _root... (show balloon)
22:32:11 Throwable: Dart analysis server, SDK version 1.14.0-edge.032c829246c071a96f218bbc02b17f4db5729a27, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for /home/myuser/dart/bwu_docker/lib/src/v1x15_and_up/tasks.dart in /home/myuser/dart/bwu_docker/lib/src/v1x15_and_up/tasks.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:685)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#2      DartAssistContributor.computeAssists. (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask. (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback. (dart:async/zone.dart:733)
#8      _rootRun (dar... (show balloon)
22:32:14 Throwable: Dart analysis server, SDK version 1.14.0-edge.032c829246c071a96f218bbc02b17f4db5729a27, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for /home/myuser/dart/bwu_docker/lib/src/v1x15_and_up/data_structures.dart in /home/myuser/dart/bwu_docker/lib/src/v1x15_and_up/data_structures.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:685)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#2      DartAssistContributor.computeAssists. (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask. (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback. (dart:async/zone.dart:733)
#... (show balloon)
22:33:00 Throwable: Dart analysis server, SDK version 1.14.0-edge.032c829246c071a96f218bbc02b17f4db5729a27, server version 1.12.0, error: Task failed: ResolveUnitTask for source /home/myuser/.pub-cache/hosted/pub.dartlang.org/collection-1.2.0/lib/priority_queue.dart
Unexpected exception while performing ResolveUnitTask for source /home/myuser/.pub-cache/hosted/pub.dartlang.org/collection-1.2.0/lib/priority_queue.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#4      AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1122)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#6      AnalysisContextImpl.performAnalysisTask (package:analyze... (show balloon)

- 

> Dart VM version: 1.14.0-edge.052b12c014b535ba52f4f75ed83c80fcc045c270 (Mon Dec  7 10:10:00 2015) on "linux_x64"

with strong-mode enabled

In 2 of 3 tested projects no code navigation, no errors/warnings in WebStorm Dart Analysis view (for example https://github.com/bwu-dart/bwu_docker)

With strong-mode disabled everything seems to work fine so far.

**Comment by zoechi** [comment]
With

> Dart VM version: 1.14.0-edge.6327b26652bf7d523e6e8044f56f96a233a8bb84 (Tue Dec  8 02:53:14 2015) on "linux_x64"

Code navigation is working again, but I still get an exception and I assume there should be some strong-mode warnings/hints but only violations of a linter rule are shown in the WebStrom "Dart Analysis" view but nothing else.

> Dart analysis server, SDK version 1.14.0-edge.5c9a5541872109ef13f120d7f35051eea0aab3a5, server version 1.12.0, error: Task failed: ResolveUnitTask for source /home/zoechi/dart/bwu_docker/lib/src/shared/data_structures.dart
Unexpected exception while performing ResolveUnitTask for source /home/zoechi/dart/bwu_docker/lib/src/shared/data_structures.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1122)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1120)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
Caused by The null object does not have a getter 'length'.
>
NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:652)
#3      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12370)
#4      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:11818)
#5      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12370)
#6      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#7      ReturnStatement.visitChildren (package:analyzer/src/generated/ast.dart:16037)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11837)
#9      UnifyingAstVisitor.visitReturnStatement (package:analyzer/src/generated/ast.dart:20003)
#10     ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:11891)
#11     ReturnStatement.accept (package:analyzer/src/generated/ast.dart:16033)
#12     NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
#13     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11837)
#15     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19775)
#16     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12783)
#17     Block.accept (package:analyzer/src/generated/ast.dart:3594)
#18     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#19     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11837)
#21     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:19778)
#22     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:12795)
#23     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:11137)
#24     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673)
#25     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#26     MethodDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:12182)
#27     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11837)
#28     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/src/generated/ast.dart:19950)
#29     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:13169)
#30     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:11803)
#31     MethodDeclaration.accept (package:analyzer/src/generated/ast.dart:12173)
#32     NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
#33     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:12864)
#34     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:12841)
#35     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:11179)
#36     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349)
#37     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:11267)
#38     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#39     ResolveUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4637)
#40     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#41     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#42     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#43     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#44     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1122)
#45     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#46     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1120)
#47     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#48     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#49     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#50     _rootRun (dart:async/zone.dart:903)
#51     _CustomZone.run (dart:async/zone.dart:802)
#52     _CustomZone.runGuarded (dart:async/zone.dart:708)
#53     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#54     _rootRun (dart:async/zone.dart:907)
#55     _CustomZone.run (dart:async/zone.dart:802)
#56     _CustomZone.runGuarded (dart:async/zone.dart:708)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#58     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#59     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:202)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)

**Comment by bwilkerson** [comment]
This appears to be fixed. When I load the project and analyze it in strong mode, there are no exceptions being thrown.
