### ISSUE TITLE
Merge the breaking changes from analyzer into bleeding edge

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25169]
We need to merge the breaking changes from analyzer into bleeding edge.

**Comment by stereotype441** [comment]
@clayberg

**Comment by stereotype441** [comment]
The merge has landed: https://github.com/dart-lang/sdk/commit/c0d68205b9e11809c4da7ced695dce941b2ae1d0.  Leaving this bug open while we wait to see the effect on the buildbots.

**Comment by stereotype441** [comment]
Analyzer buildbot failures being tracked here: https://github.com/dart-lang/sdk/issues/25173

**Comment by stereotype441** [comment]
All the bot failures caused by the merge have now been fixed.
