### ISSUE TITLE
missing downwards inference case: list literal in map literal

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25174]
Here's a simplified repro:

```dart
class Resource {}
class Folder extends Resource {}

Resource getResource(String str) => null;

main() {
  var map = <String, List<Folder>>{
    'pkgA': [getResource('/pkgA/lib/')],
    'pkgB': [getResource('/pkgB/lib/')]
  };
}
```

gives:
```
$ ./xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --strong test.dart
Analyzing [test.dart]...
[error] Type check failed: [getResource('/pkgA/lib/')] (List<dynamic>) is not of type List<Folder> because [getResource('/pkgA/lib/')] cannot be typed as List<Folder> (test.dart, line 8, col 13)
[error] Type check failed: [getResource('/pkgB/lib/')] (List<dynamic>) is not of type List<Folder> because [getResource('/pkgB/lib/')] cannot be typed as List<Folder> (test.dart, line 9, col 13)
[hint] The value of the local variable 'map' is not used (test.dart, line 7, col 7)
2 errors and 1 hint found.
```
(edit: removed typo in simplified example)

**Comment by leafpetersen** [comment]
Ah, right.  It's not the list literal specifically, it's that I'm not propagating types from explicitly typed literals downwards (only inferred type literals).  If you move the type annotation from the literal to the variable type, I think it will work.  List literals are probably the same.

**Comment by jmesserly** [comment]
Ah, nice. BTW the actual example was a constructor call to PackageMapUriResolver, with constructor signature:
```dart
PackageMapUriResolver(this.resourceProvider, this.packageMap) {
```
and packageMap field:
```dart
final Map<String, List<Folder>> packageMap;
```

... maybe the explicit type is stopping the downward inference? I wonder if I got rid of the type from the map literal, maybe it would "just work".

**Comment by leafpetersen** [comment]
Yes, the explicit type is stopping the downward inference.  There are tests for the untyped "list literal inside of a map literal" case, but I missed this one.  If you look at the visit method for these literals, the propagation downwards only happens if the type arguments are empty.  The code just needs to be moved around a bit to still do the downwards propagation (but not the inference) in the case that we have an explicit type.

**Comment by jmesserly** [comment]
ah nice, thanks for the pointers. Maybe I will take a shot at fixing. If I understand correctly it looks like an easy one :)

**Comment by jmesserly** [comment]
yup that worked! Fixed lists & maps. Fairly sure it already works for InstanceCreationExpression but I'll double check.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1507883003/
