### ISSUE TITLE
improve function type error messages by showing what's incompatible

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25170]
Function type error messages from strong-mode can be hard to understand. It took me a while to decipher this:
```
Invalid override. The type of FunctionTypeImpl.substitute2 ((List<DartType>, List<DartType>, [List<FunctionTypeAliasElement>]) → DartType) is not a subtype of FunctionType.substitute2 ((List<DartType>, List<DartType>) → FunctionType).lib/src/generated/element.dart, line 5713
```
I think the issue is the horizontal scrolling ... the thing that's wrong is pushed way off the right side, in both Atom and IntelliJ it's very hard to see the return type is different.

@vsmenon had an idea: we can instead say something about the return type:

```
Return type DartType is not a subtype of FunctionType, in the override FunctionTypeImpl.substitute2 (overridden from FunctionType.substitute2).
```

I'd be good to check other tools (for Dart but also other languages) to get some ideas on what works best here.

Of course, they won't always be that easy, but a few special cases can probably handle a lot of the common errors.

**Comment by bwilkerson** [comment]
Specializing the error message would be fantastic. We'll still need the general case for times when there are so many problems that a specialized message doesn't make sense, but hopefully that will be rare.

**Comment by jmesserly** [comment]
FWIW, this is now implemented in ErrorVerifier, so if we merge CodeChecker's checks into ErrorVerifier we'll get the better error messages.

**Comment by jmesserly** [comment]
I'm going to dupe this in https://github.com/dart-lang/sdk/issues/25350, since merging the two systems will fix the error
