### ISSUE TITLE
implement generic functions/methods in other AST nodes besides MethodInvocation

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25175]
Right now generic function calls are only supported for the MethodInvocation AST node, which applies to method calls like `o.m<t>(...)` and function calls like `f<t>(...)`

We need to support these:
- [x] tear offs, e.g. `o.m`
- [ ] instantiated tear offs, e.g.  `o.m<t>` 
- [ ] instantiation of the function type, e.g. `var y = f<int>;`
- [x] function expression invocation, e.g. `(f)(1, 2)` or `(f)<int>(1, 2)`
- [x] generic function expression, e.g. `<T>(T x) => x`

**Comment by jmesserly** [comment]
btw feel free to edit the first message, not sure if I've captured all of the missing features

**Comment by leafpetersen** [comment]
Tear offs seem to be working.  I think the partial instantiation is lower priority, particularly given that I think the work involved will be larger.  I'll work on getting function expression invocation working.

**Comment by jmesserly** [comment]
@leafpetersen if you don't mind I'll take this, I think it will be pretty easy to fix to FunctionExpressionInvocation after the cleanup in https://codereview.chromium.org/1568643002/

**Comment by jmesserly** [comment]
This might belong in a different bug, but I just noticed we don't handle this case correctly:
```dart
int lambdaCall = (/*<T>*/(/*=T*/ e) => e)/*<int>*/(3);
```

**Comment by leafpetersen** [comment]
Sure, all yours.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1561233003/ :)

**Comment by jmesserly** [comment]
Hmmm, actually it looks like we don't support that lambda form?
https://github.com/leafpetersen/dep-generic-methods/blob/master/proposal.md#functions

In which case it's a bug in the error handling, as we should disallow type parameters there.

**Comment by leafpetersen** [comment]
Tearoffs were fixed in https://codereview.chromium.org/1568643002

**Comment by jmesserly** [comment]
Fix for lambdas: https://codereview.chromium.org/1579303002/

Funny to chase down the bug, only to see a TODO(jmesserly) describing the problem :)

**Comment by jmesserly** [comment]
dropping priority, as the only cases left are the instantiated tear-offs & functions.

**Comment by jmesserly** [comment]
There's an interesting instantiated tear off example at https://github.com/dart-lang/dev_compiler/issues/426. It uses a generic function as a default argument. For that example, we'd also have to allow function instantiations to be treated as constant expressions.

**Comment by jmesserly** [comment]
CL is out for downward inference on instantiations. So even if we don't have syntax support yet, at least they will work in an inferred context.

**Comment by jmesserly** [comment]
split out the remaining issues into a new bug: https://github.com/dart-lang/sdk/issues/25824, as they're lower priority than what this bug originally covered
