### ISSUE TITLE
VM does not return memory to OS

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25178]
- Start IntelliJ
- Import the whole SDK repo as a project
- Open Observatory, notice that VM uses `2.5 GB` of heap
- Close the SDK project.
- Switch back to Observatory, open Heap Allocation, to GC
- The memory usage dropped to `238 MB`, the allocated heap is still `2.4 GB`.
  
  Why?

![image](https://cloud.githubusercontent.com/assets/384794/11667287/a253090e-9da5-11e5-85de-a9d72fe46632.png)

**Comment by scheglov** [comment]
@alexander-doroshko

**Comment by kaendfinger** [comment]
Is this related to #24938?

**Comment by scheglov** [comment]
Yes, it seems so.

**Comment by rmacnak-google** [comment]
The VM returns memory to the OS when every object on a page if no longer reachable. If the fraction of old space that is used is low, it is likely fragmentation.

https://github.com/dart-lang/sdk/issues/30978
