### ISSUE TITLE
document.onFullscreenChange doesn't fire

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#25177]
`document.onFullscreenChange` doesn't fire events. Instead of:

`document.onFullscreenChange.listen(_onFullScreenChange);`

 You need to do:

`document.addEventListener('fullscreenchange', _onFullScreenChange);`

**Comment by mnordine** [comment]
I don't know if this is relevant, but I noticed references to `onfullscreenchange` in `sdk/sdk/lib/_blink/dartium/_blink_dartium.dart`. While I believe it should be `fullscreenchange`.

**Comment by mnordine** [comment]
> That seems consistent with all the other event properties there.

Yes, but I found
> For each doc in eventDocs, in order, fire an event named fullscreenchange on doc.

from https://fullscreen.spec.whatwg.org/

**Comment by mnordine** [comment]
>  Is this only in Dartium, or also in dart2js?

I'm having a hard time getting full screen api working after using dart2js (https://github.com/dart-lang/sdk/issues/4136), so I've only tried it in Dartium.

When I try to do `element.requestFullscreen()`, using Chrome after dart2js, I get the following error:

`js_helper.dart:1699 Uncaught NoSuchMethodError: method not found: 'requestFullscreen' (this.a.requestFullscreen is not a function)`

Know any work around to test in dart2js?

**Comment by alan-knight** [comment]
My thought, without investigating too closely, is that if all the events look like that in the spec, and they all look different in _blink_dartium.dart, then you'd expect no events at all to work if that's the problem.

Well, in Chrome it's webkitRequestFullscreen. Normally dart2js tries things with vendor prefixes, but there might be a problem there. As a workaround, you could do something like (typed without validating)
   var e = new JsObject.fromBrowserObject(document.body);
   e.callMethod("webkitRequestFullScreen", []);
for Chrome - the method name may be different in other browsers.

**Comment by mnordine** [comment]
Thanks, you hack worked, and `document.onFullscreenChange.listen(_onFullScreenChange);` works fine in Chrome with it.

So I guess once https://github.com/dart-lang/sdk/issues/4136 is fixed, Full Screen API will work as expected, and I won't need the above hack?

**Comment by alan-knight** [comment]
Yes, once we fix it for dart2js you shouldn't need the hack. Although I think it doesn't need to be a polyfill at this point. Not sure if updating Dartium will just fix it or if there's more work to do. We'll find out soon :-)

**Comment by mnordine** [comment]
Oddly, I just checked in Dartium, and now `document.onFullscreenChange.listen(_onFullScreenChange);` works with your above hack as well.

**Comment by kevmoo** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.

**Comment by mnordine** [comment]
I think this is still an issue. In `html_dart2js.dart`, here is the relevant code:

```dart
  /**
   * Static factory designed to expose `fullscreenchange` events to event
   * handlers that are not necessarily instances of [Element].
   *
   * See [EventStreamProvider] for usage information.
   */
  @SupportedBrowser(SupportedBrowser.CHROME)
  @SupportedBrowser(SupportedBrowser.SAFARI)
  static const EventStreamProvider<Event> fullscreenChangeEvent =
      const EventStreamProvider<Event>('webkitfullscreenchange');
```

Also see https://github.com/dart-lang/sdk/issues/25324#issuecomment-679272927
