### ISSUE TITLE
Request to make Observatory traces loadable by about:tracing

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25180]
I'd love to be able to download/save a tracing export from Observatory, send that to someone else, and have them open it in (presumably) about:tracing.

That doesn't appear to work today, but maybe it's an easy thing to add?

Thanks!

**Comment by rmacnak-google** [comment]
The "doesn't work today" situation was trying to load the raw RPC response from _getVMTimeline into about:tracing. An export option would extract the traceEvents.

**Comment by johnmccutchan** [comment]
@sethladd Saved timelines can be loaded into Observatory and about:tracing.
