### ISSUE TITLE
Break-points trigger at unexpected locations

### ISSUE THREAD

**Issue by krkboasit** [dart-lang/sdk#25186]
## Summary:
Breakpoints placed at a function invocation does not trigger at the expected program location. 
Instead of breaking before the arguments are evaluated the breakpoint triggers after the function arguments have been evaluated.
This is inconvenient as one would expect to be able to step into the function used as an argument for a function invocation.

## What steps will reproduce the problem?
1. Create a new simple-command-line project.
2. Replace the contents of main.dart with the following:
```
String foo() {
  return 'Hello world';
}

main(List<String> args) {
  print(foo());
}
```
3. Place a break-point at the line containing print().
4. Run the application in debug-mode.
5. Try to step into the foo() method.

## What is the expected output? What do you see instead?
__Expected:__
The debug process steps into the foo() method.

__Actual:__
The debug process skips the foo() method and steps into the print() method.

## What version of the product are you using?
WebStorm 11.0.1
Dart-SDK 14.0-dev.3.0

On what operating system?
Windows 7 SP1(64bit)

**Comment by alexander-doroshko** [comment]
Works as expected for me. See screenshots: after stopping on a breakpoint I press `F7` and get to `foo()`.
![image](https://cloud.githubusercontent.com/assets/4499789/11682759/f5d659d2-9e77-11e5-9d16-2fd400376ec3.png)
![image](https://cloud.githubusercontent.com/assets/4499789/11682770/06eacafa-9e78-11e5-8ae6-d2746158eb62.png)

**Comment by boasjls** [comment]
We've reproduced this issue with 1.14-dev.1.0 as well.
It does not occur with the 1.13 stable build.

**Comment by alexander-doroshko** [comment]
In case of SDK 1.13 WebStorm uses old legacy debugger protocol; in case of SDK 1.14+ it uses VM Service protocol. But for me in both cases it works as on my screenshots (I'm on Windows 8.1, 64-bit SDK).

**Comment by rmacnak-google** [comment]
@turnidge 

Where in the line are you placing the breakpoint? The VM supports precise line:column breakpoints, so you will get different behavior if the breakpoint is set on the print call or the foo call. The UI in the screenshots doesn't seem to be surfacing column positions.

**Comment by alexander-doroshko** [comment]
Column is optional in [addBreakpointWithScriptUri](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#addbreakpointwithscripturi) RPC and WebStorm doesn't pass any. I believe it means zero, I expect to stop as early as possible on this line.

**Comment by boasjls** [comment]
After updating WebStorm to 11.0.2 I can no longer reproduce this.

**Comment by iposva-google** [comment]
Thanks for the update. Closing...
