### ISSUE TITLE
generic method override error on return types

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25183]
Seen with latest Dart SDK containing today's fixes:
```
The return type 'V (/Users/jmesserly/src/dart/sdk/pkg/analyzer/lib/src/context/context.dart)' is not assignable to 'V (/Users/jmesserly/src/dart/sdk/pkg/analyzer/lib/src/generated/engine.dart)' as required by the method it is overriding from 'AnalysisContext'lib/src/context/context.dart, line 930
```

Given that the error message looks different from https://github.com/dart-lang/sdk/issues/25170, I think this one is coming from ErrorVerifier. It looks like it does not understand the return type of generic methods when it checks overrides. (not sure if parameters are working).

I'm seeing this on most (all?) generic methods overrides

**Comment by leafpetersen** [comment]
Yeah, I think tackling the error verifier is a pretty high priority now.  The functionality is getting into decent shape, but we're going to get lots of spurious warnings, and (less critically but still important) we'll be missing some useful warnings.

**Comment by jmesserly** [comment]
Agreed. Should we file another one to track warnings that we should add? In the meantime I'll take a shot at this one.

**Comment by jmesserly** [comment]
Hmmm. It's in the same method so I might just go ahead and add some of the new errors/warnings (number of type parameters, bounds) based on: https://github.com/leafpetersen/dep-generic-methods/blob/master/proposal.md#function-subtyping

Trying to figure out what seems worth keeping there. I think a lot of this is subsumed by CodeChecker in strong mode (which does the subtype check), although it looks like we still need some parts of _checkForAllInvalidOverrideErrorCodes like the INVALID_OVERRIDE_DIFFERENT_DEFAULT_VALUES_* check.

**Comment by leafpetersen** [comment]
Sounds good to me.  Tracking bug for the missing warnings filed here:

https://github.com/dart-lang/sdk/issues/25200

Feel free to add any that I forgot.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1514683002/
