### ISSUE TITLE
spurious info-level message that a private class isn't used

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25184]
Example:

class Foo {
  _Bar x;
}

class _Bar {
}

This message appears:
The class '_Bar' is not used

However, it is used as a field type.

**Comment by skybrian** [comment]
If we're agreed that it's a real bug, I'd like to try to fix it.

**Comment by bwilkerson** [comment]
It is, and that would be great! Thanks!

**Comment by liuming0** [comment]
Something might be related. 

INFO: The value of '_a' is not used.

class Foo {
  String _a;
  
  Foo() {
    _init();
  }
  
  void _init() {
    _a = 'bar';
  }
}

**Comment by skybrian** [comment]
I think it's correct to report a problem in this case because the '_a'
variable is written but never read. But perhaps the message could be
clarified.

- Brian

**Comment by skybrian** [comment]
https://codereview.chromium.org/1512833007/
