### ISSUE TITLE
[breaking] Cross-origin window access is impossible window.parent == null 

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#25187]
## What steps will reproduce the problem?

Access a 'window.parent' from an embedded iframe with different origin than the embedding page.
## What is the expected output? What do you see instead?

**Expected:** A `window` object on which I can call `postMessage`
**What I see:** `null`
## What version of the product are you using?

Dart 1.13 + Matching Dartium version (ref 76d50a3)
## On what operating system?

Linux Mint
## What browser (if applicable)?

Dartium
## Please provide any additional information below.

Compiling the code to JS returns `_DOMWindowCrossFrame` for `window.parent` as it should. Vanilla JS also returns an instance of `Window` and Dartium+Dart returns `null`. Considering our application uses a _lot_ of `postMessage` we have to downgrade to v 1.12 until this issue is resolved and our tests can pass once again.

**Comment by alan-knight** [comment]
Do you have a reproduction for this? Looking at our tests, I seem to be getting a window back. It's not wrapped as a _DOMWindowCrossFrame, which is a known issue, you just get a full window back. But that's not null, and seems like it shouldn't be an issue.

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
