### ISSUE TITLE
Fix the type parameter API's in ParameterizedType and FunctionType

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25193]
The API's for accessing type parameters have changed because we needed to split "bound" and "not bound" type parameters. We need to update the API's to make it easier for clients (like dartdoc).

**Comment by jmesserly** [comment]
"typeFormals" was one idea @leafpetersen and I had, "formals" and "actuals" is common terminology for this sort of thing.

Other ideas: we could pull typeParameters/typeArguments out into a "type substitution" or "type environment" object, as those two really describe the surrounding context of type variables.

Another related issue: InterfaceTypes should use consistent substitute/instantiate terminology as FunctionType does.

**Comment by leafpetersen** [comment]
A somewhat related issue that I think we need to address is the gymnastics associated with instantiating generic methods and then re-constituting the un-instantiated types.  Currently, in a method invocation `o.f<int>(3)`, where `f` has type `<T> T -> T`, we associate the type `int -> int` with the method name in the MethodInvocation.  This is a little hinky, as can be seen in the need for the `originalFunction` and `instantiatedTypeArguments` functionality.  It's kind of brittle relying on a function type to remember that it came from an instantiation of something else.  And I really don't know what to do here for variables with generic function type.  There's a partial workaround in place for function typed formals, but I'll be surprised if it generalizes. 

It might be time to take a step back now that we have some experience with this and do some API design work to figure out where we want to get to with all of this.

**Comment by bwilkerson** [comment]
> It might be time to take a step back now that we have some experience with this and do some API design work to figure out where we want to get to with all of this.

I agree. Let's talk off-line.

**Comment by jmesserly** [comment]
> This is a little hinky, as can be seen in the need for the originalFunction and instantiatedTypeArguments

Oh one thought on this -- yeah, it's definitely a hack. But we shouldn't need it if we implement type inference in one pass, right? At the moment we do downwards and upwards in separate stages, which is why upwards has to be able to "undo" some of the work.

**Comment by leafpetersen** [comment]
@jmesserly  I'm sure we can work around things, but just on first principles, I'm uncomfortable with it.  It feels bad from an AST design standpoint.  It's odd that in `e(x)` and `e<int>x` `e` in both cases will end up with `int -> int` as the type, and that you will have to look at the type arguments to figure out whether or not `e` originally had a generic function type, and that if you want to figure out what the original function type was you'll basically have to re-do the resolution (it's easy if `e` is a static reference to a function, but in general it can be an arbitrary expression).  Currently we only need to do this for type inference, but we will need to do it for error verification as well (e.g. to check that type arguments are appropriate) and in general it doesn't seem like an unreasonable thing to do.

**Comment by jmesserly** [comment]
just landed a fix in https://github.com/dart-lang/sdk/commit/924f2f97b75bc9774fe49813806e574d1ddbccb1

**Comment by jmesserly** [comment]
Well, fixed all of the things mentioned here (typeFormals, originalFunction, instantiatedTypeArguments)

There is still an issue of using consistent terminology with InterfaceType. I've opened https://github.com/dart-lang/sdk/issues/25378 to track that.
