### ISSUE TITLE
Type inference should show errors on assignment

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#25194]
Original bug (closed in favor of filing here):
https://github.com/dart-lang/dart-pad/issues/710

Original gist:
https://dartpad.dartlang.org/9a312cd3be014079f5ea

Non-inferred gist:
https://dartpad.dartlang.org/35244023f934c9cf9f4e

I like to argue for and use "var" locally with the belief that the tools will 'just work', this is one of those differing cases I feel is a bug.

**Comment by leafpetersen** [comment]
Just as an FYI - strong mode does this kind of inference (as well as others) and will provide errors and warnings based on it.  Of course, it comes with various other restrictions that may or may not fit your needs.

**Comment by jtmcdole** [comment]
Is there a flag to enable strong mode on dart-pad?

**Comment by leafpetersen** [comment]
Not sure.  @devoncarew is this possible?  If not, is it something that would be reasonable to support?

**Comment by devoncarew** [comment]
Yup, possible in a turing complete sense, but it's not as simple as flipping a flag. It would be hard in that we'd need to service the requests from a different backend, or have two types of backends we dispatch to.

It might make sense in the context of experimenting with generated the JS code with DDC. Not something we'd do in the short term, but maybe a good Q1 task.

**Comment by munificent** [comment]
I think this is stale now. DartPad has a "Strong Mode" check box.
