### ISSUE TITLE
Make deprecated `analyzer_cli` repo "read-only".

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25192]
We've moved the living source to the SDK repo but need to keep the old one around since it's referenced in (past) DEPS.

At this point, the main move is done so I'm closing out the meta-bug (#24731) and leaving this to track any lingering clean-up to make this repo any more read-only/decommissioned.

@kevmoo : punting to you for thoughts.

**Comment by pq** [comment]
This may in fact be enough:

<img width="503" alt="screen shot 2015-12-09 at 9 11 33 am" src="https://cloud.githubusercontent.com/assets/67586/11692550/e4c3c8a0-9e54-11e5-9968-0a9638e8453f.png">

**Comment by kevmoo** [comment]
Yup. Perfect.
