### ISSUE TITLE
Incorrect suggestions for code complete before a : as a named param

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25205]
Consider this case:

![screen shot 2015-12-09 at 2 59 02 pm](https://cloud.githubusercontent.com/assets/5479/11701623/768dcc88-9e85-11e5-8520-e8102a39262a.png)

Trying to see what named param I can use here (between the `(` and the `:`), but I see keywords and classes.

(FWIW, I do see "named args" as well, and they are at the top, which is nice.

**Comment by jwren** [comment]
2 things:

1) parameter names are now at the top in this case, so I am closing this issue.

2) Code completion is intended to work from the right to the left, filling in this kind of case, while is legit (we ought to suggest only the names that are of the type on the RHS of the ':'), it is low priority: we want to prioritize the situation where you have the new MaterialApp(^) situation.


![image](https://cloud.githubusercontent.com/assets/1533520/14802613/28fa6ea6-0b07-11e6-80bf-4ae5641c538c.png)
