### ISSUE TITLE
improve error messages for poorly formed service protocol extension messages

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25202]
When sending a command to a service protocol extension (`'foo'`), if you don't include an `isolateId` param, you get the response back `'-32601 method not found'`. This is a bit misleading. The `foo` extension has been registered by the app under debug, it's just the isolateId param which is missing. I assume w/o this info observatory can't route it to the right isolate.

**Comment by devoncarew** [comment]
@turnidge

**Comment by turnidge** [comment]
Out of curiosity, which method did you use to discover this problem, if you recall?

**Comment by turnidge** [comment]
If we wanted to fix this, I guess we would need to keep a global list of all known service extensions for all isolates and then go through that list in the case of a missing isolate parameter.  Not sure if we want to do this.  Reassigning to John since he works on extensions.
