### ISSUE TITLE
service protocol extension message params all converted into strings

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25208]
When a debugger client calls a service protocol extension:

`fooBar` with params `{'foo': 123, 'bar': true, 'baz': 'abc'}`

it arrives at the handler with all the params converted into their string equivalents:

`fooBarHandler` receives `{'foo': '123', 'bar': 'true', 'baz': 'abc'}`

So, ints, bools, and non-string params are all converted into strings.

@turnidge @johnmccutchan @rmacnak-google

**Comment by johnmccutchan** [comment]
Internal to the VM the service protocol parameters (names and values) are encoded as strings. I will document this limitation of service protocol parameters.

**Comment by devoncarew** [comment]
OK. Sounds like the params we're getting will always be a `Map<String, String>`. You might want to update the signature for the ServiceExtensionHandler typedef (https://api.dartlang.org/1.13.0/dart-developer/ServiceExtensionHandler.html) so there's no confusion.
