### ISSUE TITLE
Add warning for cascade on type

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25218]
This runs to completion ...
```
    main() { int.parse('27'); }
```
... but this throws an exception at runtime ...
```
    main() { int..parse('27'); }
```
Yet there is no error/warning from the analyzer.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1519583002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/0f95992770377ae24662b48bfe3580076795c1d4
