### ISSUE TITLE
Analyzer buildbot failing due to divergent implementations of typed_data package

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25221]
Commit https://github.com/dart-lang/sdk/commit/5cfc7ab028f1af79e135ee9becb422473f1d2411 updated the DEPS file to bring a new version of the `convert` package into the SDK.  This in turn caused the analyzer buildbot to detect a pair of warnings:

    WARNING|STATIC_WARNING|EXTRA_POSITIONAL_ARGUMENTS|/usr/local/google/home/paulberry/dart-new/sdk/third_party/pkg/convert/lib/src/percent/decoder.dart|202|20|26|1 positional arguments expected, but 3 found
    WARNING|STATIC_WARNING|EXTRA_POSITIONAL_ARGUMENTS|/usr/local/google/home/paulberry/dart-new/sdk/third_party/pkg/convert/lib/src/percent/decoder.dart|225|20|28|1 positional arguments expected, but 3 found

Since these warnings claim that too many arguments are being passed to the `Uint8Buffer.addAll()` method, I dug into the implementation of `Uint8Buffer` (which is provided by the `typed_data` package).  To my surprise, I found two divergent implementations:
- One implementation in https://github.com/dart-lang/typed_data
- One implementation in https://github.com/dart-lang/sdk/tree/master/pkg/typed_data

(This was surprising because our normal practice when a package is developed outside the SDK is to bring it into the SDK via DEPS, rather than have a duplicate implementation which is what seems to have been done here).

It appears that the former implementation of `typed_data` is the one we have been publishing to pub.  So when `convert` is used in a conventional fashion (e.g. by downloading the source code and running `pub get`), the former implementation of `typed_data` is what gets used; this implementation contains a definition of `Uint8Buffer.addAll()` that accepts three arguments, so there is no problem.  But when `convert` is used inside the SDK, it uses the package root built by the build process to locate `typed_data`, and that package root points to the latter implementation, whose definition of `Uint8Buffer.addAll()` only accepts one argument.

So this is not just a bogus warning; any use of the convert package within an executable built into the SDK (e.g. the analyzer or pub) could conceivably fail due to this argument mismatch.

As a short term fix I'm going to change the DEPS file to point back to the previous version of `convert`.  (The only difference is the passing of extra arguments to `Uint8Buffer.addAll()` so this should be safe for now).  This is a band-aid, however; I'm hoping someone with a deeper understanding of `typed_data` can lend some insight as to whether it is necessary to have two separate implementations of it (I'm hoping it's not), and if so, how to keep them synchronized effectively.

**Comment by stereotype441** [comment]
@lrhn

**Comment by nex3** [comment]
The proper solution here is to bring in the latest version of `typed_data` via DEPS. I have no idea why there's a non-DEPS implementation in the SDK, though; maybe @whesse can shed some light on that?

**Comment by lrhn** [comment]
I think the version in `sdk/pkg` should just be deleted. That's where it was originally developed, before being moved to github. The version in the repository hasn't been touched in 2015, and the github repository has been extending that version.

**Comment by whesse** [comment]
OK, I'll do it, and put the current stable tag in third_party/pkg.

On Fri, Dec 11, 2015 at 10:37 AM, Lasse R.H. Nielsen <
notifications@github.com> wrote:

> I think the version in sdk/pkg should just be deleted. That's where it
> was originally developed, before being moved to github. The version in the
> repository hasn't been touched in 2015, and the github repository has been
> extending that version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25221#issuecomment-163887262>.
>



-- 
William Hesse

**Comment by whesse** [comment]
This is done, and the version of typed_data in third_party/pkg is 1.1.2.  The current stable version is 1.1.3.  Someone should try rolling it, but that is a separate issue.
