### ISSUE TITLE
cannot catch loadLibrary exceptions in stand-alone VM

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#25224]
I am trying to deffered load a library and I want to catch any exception that happens during the loading. For that, I wrapped the `loadLibrary()` call in a try catch block:

``` dart
  test('loadLibrary catching', () async {
    try {
      print("Going to load library.");
      await defferedImport.loadLibrary();
      print("Library loaded.");
    } catch(e, s) {
      print("unable to load library");
    }
  });
```

When I now introduce a syntax error in the `defferedImport` source, the test execution _terminates_ at the `loadLibrary()` call. The catch clause is never executed.

Is that intentional? Why can I not catch exceptions thrown by `loadLibrary()`? It also seems that this behavior is not in line with the specification: I think, the spec [1] on page 130 basically says that if a call to `loadLibrary()` fails (e.g. due to a compilation problem) nothing happens and you get the chance to call `loadLibrary()` again. 

[1] http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf

**Comment by mraleph** [comment]
The issue seems stale. Please reopen if it still matters to you.
