### ISSUE TITLE
High CPU Usage with heavy use of WebSockets and JSON

### ISSUE THREAD

**Issue by kendfinger** [dart-lang/sdk#25229]
We have created a benchmark that simulates large amounts of load with a server and client communicating via WebSockets and large JSON messages.
See [this Gist](https://gist.github.com/kaendfinger/afbd2bbf3db0c923b9ad) for the benchmark code.

You can run the test by running the following commands:

``` bash
# Spawn a Server in one Terminal
$ dart benchmark.dart --server
# Spawn a Client in another Terminal
$ dart benchmark.dart --client
```

We see extremely large amounts of CPU Usage (100% for both the server and client).

**Dart Version**: v1.13.0
**Platforms**: Windows, Mac

**Comment by floitschG** [comment]
@lrhn: could you have a first look?
If it's not the json conversion, please update the labels.

**Comment by lrhn** [comment]
It may be JSON, it may be UTF-8 encoding or GrowableList.addAll. I don't see anything that stands out as being the single source of the CPU usage.

The 1%+ CPU users for the client is:
```
Executing	In stack Method 
11.34%	11.35%	_Utf8Encoder._fillBuffer
8.15%	43.03%	_GrowableList.addAll
6.59%	29.03%	_GrowableList._grow
5.78%	5.81%	Lists.copy
3.98%	4.03%	_StringBase._createOneByteString
3.82%	3.82%	_Utf8Decoder.convert.scanOneByteCharacters
3.62%	3.63%	_TypedListIterator.moveNext
3.47%	3.47%	[Stub] AllocateArray
2.01%	2.01%	ListIterator.current
1.13%	3.91%	_Uint8Array._Uint8Array
```
For the server it's:
```
Executing	In stack	Method 
5.93%	5.95%	_Utf8Encoder._fillBuffer
3.54%	3.54%	[Stub] AllocateArray
3.48%	12.05%	_GrowableList._grow
3.47%	20.68%	_GrowableList.addAll
3.10%	7.70%	_JsonStringifier.writeStringContent
3.07%	3.07%	_Uint8ArrayView.[]
2.88%	2.90%	Lists.copy
2.61%	2.62%	_StringBase._createOneByteString
2.45%	2.45%	_Utf8Decoder.convert.scanOneByteCharacters
2.42%	12.46%	StringBuffer._addPart
2.25%	8.63%	_ChunkedJsonParser.parseString
2.01%	5.08%	_TypedListIterator.moveNext
1.87%	22.27%	_ChunkedJsonParser.parse
1.69%	1.69%	_JsonStringParser.getChar
1.65%	3.03%	_OneByteString._substringUncheckedNative
1.30%	14.67%	StringBuffer.write
1.29%	4.37%	_StringBase.substring
1.27%	23.69%	_JsonStringifier.writeMap
1.13%	1.13%	_OneByteString.hashCode
1.11%	1.56%	_GrowableList.add
```

The `addAll` calls come from `_WebSocketPerMessageDeflate.processIncomingMessage`. It seems to be using a growable list internally to collect bytes. It should at least be using a byte buffer, and it could be reusing it.

**Comment by rinick** [comment]
here is an updated benchmark, this time the main benchmark load is moved to client app so I can compare it with js
https://gist.github.com/rinick/ff1e2cf681ae4ab53f2c

use `dart benchmark` to start a server
use `dart benchmark --client` to start a dart client
open http://localhost:9540 in chrome to start a web client

please only use one client at a time, so benchmark result won't be affected by the load of server.

I can get about 26~30 frames/second in dart client, and 40~41 frames/second in js.
