### ISSUE TITLE
infer constructor type arguments from values

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25220]
Would it be possible that strong mode infers the type of `otherMap` below to be `Map<String, String>`

```dart
  var map = new Map<String, String>();   
  var otherMap = new Map.from(map);
```

Now `otherMap` has type `Map<dynamic, dynamic>`.

**Comment by jmesserly** [comment]
@kasperpeulen definitely! We can use upwards inference for constructors like we do for generic methods. Was chatting with @leafpetersen earlier this week about this.

**Comment by kasperpeulen** [comment]
awesome :+1:

**Comment by jmesserly** [comment]
BTW, a related issue is that we don't (AFAIK) do downwards inference on generic methods. Current state of the world:
* constructor type parameters are only inferred from downwards inference
* generic function type parameters are only inferred from upwards inference

**Comment by jmesserly** [comment]
Also map/list literals: https://github.com/dart-lang/dev_compiler/issues/108
and block bodied lambda return: https://github.com/dart-lang/sdk/issues/25487

**Comment by jmesserly** [comment]
note, we should fix LUB first: https://github.com/dart-lang/sdk/issues/25802, or we're going to get strange results in some cases

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1717803003/ fixes literals. Still need constructors.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2115173002/ fixes constructors

**Comment by kasperpeulen** [comment]
@jmesserly Not sure if I understand correctly, but it doesn't seem to work as I expected:
![image](https://cloud.githubusercontent.com/assets/1035299/23326664/64dd5b56-fb00-11e6-873a-d9f477319937.png)

**Comment by jmesserly** [comment]
@kasperpeulen the [Map.from](https://api.dartlang.org/stable/1.22.1/dart-core/Map/Map.from.html) constructor (like List.from) is designed to be able to cast from one type to another, so it won't infer. 
The signature is `new Map.from(Map other)`
if the signature was `new Map.from(Map<K, V> other)` then it would work, but you would not be able to use Map.from in a cast like this:
```dart
var m = <dynamic, dynamic>{1: 2}
var m2 = new Map<int, int>.from(m); // allowed, casts easy key/value
```

that's an API design choice for the SDK. Inference however is supported for constructors. For example [List.filled](https://api.dartlang.org/stable/1.22.1/dart-core/List/List.filled.html) can infer from the value type.
