### ISSUE TITLE
Logical typo in chapters 'Break' and 'Continue'

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25234]
The Dart Programming Language Speciﬁcation version 1.9, chapter 17.15 Continue reads:

> Let sc be a continue statement. If sc is of the form continue L;, then let sE
> be the the innermost labeled do (17.8), for (17.6) or while (17.7) statement or
> case clause with label L enclosing sc . If s c is of the form continue; then let sE
> be the the innermost do (17.8), for (17.6) or while (17.7) statement enclosing sc .
> ...
> **If sE is an asynchronous for loop** (17.6.3), let ak be the set of asynchronous
> for loops and yield-each statements (17.16.2) enclosing sc that are enclosed
> in sE , 1 ≤ k ≤ m, where a k is enclosed in ak+1 . The stream subscriptions
> associated with aj are canceled, 1 ≤ j ≤ m, innermost ﬁrst, so that aj is
> canceled before aj+1 .

I believe the highlighted part of the texts should be changed to 
'If sE is an asynchronous for loop or there are asynchronous loops enclosed in sE, that enclose sc'

The same problem is observed in chapter 17.14 Break

**Comment by lrhn** [comment]
It's almost correct, but actually we need to be aware of enclosing `finally` blocks as well - they may interrupt the escape and in that case the async for loops outside of the finally must not be cancelled, only those inside.

Basically, it's not as simple as this text pretends it is.
