### ISSUE TITLE
Analyzer gets out of sync with actual files (atom)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#25237]
Since I switched over to primarily using atom I have noticed that it is pretty common for the analysis to get out of sync with actual files, which results in spurious warnings which are not correct. 

Unfortunately this is extremely difficult to reproduce in any sort of consistent manner, but it does happen to me a couple times each day....

**Comment by sethladd** [comment]
cc @devoncarew I wonder if there's any diagnostics we could have you send us?

**Comment by bwilkerson** [comment]
Can you please enable the local instrumentation log and send us a copy immediately after you notice this problem?

**Comment by jakemac53** [comment]
@bwilkerson sure, what are the steps to doing that?

**Comment by bwilkerson** [comment]
I believe that @devoncarew added support for that, but I don't remember where the control is where you can enter the path to the file to which the data will be written.

**Comment by devoncarew** [comment]
@bwilkerson, to my knowledge instrumentation is either on or off by default; and to be clear, I don't believe that Jake is running in a google3 context.

**Comment by bwilkerson** [comment]
@devoncarew Right. I believe we talked at one point about adding support for users to provide additional arguments to be passed to the analysis server. That can be used to specify a file to which instrumentation data will be written, by adding something like "--instrumentation-log-file=/User/me/server-log-file.txt". But I don't know where these arguments are specified.

**Comment by devoncarew** [comment]
Yup. @jakemac53, if you open your config.cson file (Atom > Open your Config) and add a `analysisServerOptions` line under the `dartlang:` section, all that text will be passed to the analysis server as command-line options. It will require a restart of atom to take effect.

**Comment by jakemac53** [comment]
Ok great that looks like its working, will follow up here once it happens again.

**Comment by bwilkerson** [comment]
Is this problem still occurring, or should we close this issue?

**Comment by jakemac53** [comment]
we can probably close it, I haven't been able to repro since filing the issue :/

**Comment by jakemac53** [comment]
Actually, I just got a repro today but of course I had turned off the analyzer logs :(. However, I noticed that it happened when renaming files, not sure if that helps or not. I am actually still getting analyzer warnings in the console for files which no longer exist (they were moved into a subfolder).

**Comment by devoncarew** [comment]
> However, I noticed that it happened when renaming files

That helps a lot, and is probably an issue on the atom side. I'll open an issue for that -
