### ISSUE TITLE
Refactoring repeatedly eventually produces bogus error message

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25238]
Start with a file containing the following:

    class Foo {
      /** Helper to get the floor of a number. Note that we expect it to be positive. */
      _floor(number) => number is num ? number.floor() : number ~/ 1;

      _round(number) {
        if (number is num) {
          return number.round();
        } else if (number.remainder(1) == 0) {
          // Not a normal number, but int-like, e.g. Int64
          return number;
        } else {
          // TODO(alanknight): Do this more efficiently. If IntX  had floor and round we could avoid this.
          var basic = _floor(number);
          var fraction = (number - basic).toDouble().round();
          return fraction == 0 ? number : number + fraction;
        }
      }
    }

Repeatedly renaming the two method parameters (sometimes to the same name, sometimes to different names) will eventually report that the refactoring cannot be performed because of a "duplicate parameter name".

**Comment by scheglov** [comment]
https://codereview.chromium.org/1522583005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/56f0adf9bf527b9b8d69ec296a4387e4ea53264f
