### ISSUE TITLE
Statement 'continue L;' cancels stream subscriptions in wrong order

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25247]
The Dart Programming Language Speciﬁcation version 1.9, chapter 17.15 Continue reads:
>Let sc be a continue statement. If sc is of the form continue L;, then let sE
>be the the innermost labeled do (17.8), for (17.6) or while (17.7) statement or
>case clause with label L enclosing sc . If s c is of the form continue; then let sE
>be the the innermost do (17.8), for (17.6) or while (17.7) statement enclosing sc .
> ...
> If sE is an asynchronous for loop (17.6.3), let ak be the set of asynchronous
>for loops and yield-each statements (17.16.2) enclosing sc that are enclosed
>in sE , 1 ≤ k ≤ m, where a k is enclosed in ak+1 . The stream subscriptions
>associated with aj are canceled, 1 ≤ j ≤ m, innermost ﬁrst, so that aj is
>canceled before aj+1 .

The following code demonstrates that stream subscriptions are canceled in wrong order:
```
import 'dart:async';

Stream makeStream(Iterable iterable, int id) {
  Stream makeStreamInternal(Iterable iterable) async* {
    for (var element in iterable) {
      yield element;
    }
  }

  Stream s = makeStreamInternal(iterable);
  print("created stream $id");
  return s.asBroadcastStream(onCancel: (_) {
    print("cancel stream $id");
  });
}

Future test1() async {
  int i = 0;

  L:
  await for (String s in makeStream(['a', 'b'], i++)) {
    print("loop0: $s");
    await for (String s in makeStream(['a', 'b'], i++)) {
      print("loop1: $s");
      await for (String s in makeStream(['a', 'b'], i++)) {
        print("loop2: $s");
        continue L;
      }
    }
  }
}

main() {
  test1().then((_) => print("test1 completed"));
}
```
Test produces output:
>created stream 0
>loop0: a
>**created stream 1**
>loop1: a
>**created stream 2**
>loop2: a
>**cancel stream 1**
>**cancel stream 2**
>cancel stream 0
>loop0: b
>**created stream 3**
>loop1: a
>**created stream 4**
>loop2: a
>**cancel stream 3**
>**cancel stream 4**
>test1 completed

Expected output is:
>created stream 0
>loop0: a
>**created stream 1**
>loop1: a
>**created stream 2**
>loop2: a
>**cancel stream 2**
>**cancel stream 1**
>cancel stream 0
>loop0: b
>**created stream 3**
>loop1: a
>**created stream 4**
>loop2: a
>**cancel stream 4**
>**cancel stream 3**
>test1 completed

Dart VM version: 1.13.0 (Wed Nov 18 12:24:20 2015) on "windows_x64"

**Comment by lrhn** [comment]
I think what you are seeing here is an artifact of asynchronous reporting of the cancelling.
 void onData(d) { _sub.onData(d); }
 void onError(d) { _sub.onError(d); }
 void onDone(d) { _sub.onDone(d); }

If you actually check the time when the streams are cancelled, e.g., using:

```
import 'dart:async';

class WrapStream extends Stream {
  int _id;
  Stream _stream;
  WrapStream(this._id, this._stream);
  listen(onData, {onError,onDone,cancelOnError}) {
    print("listen $_id");
    return new _WrapSub(_stream.listen(onData, onError:onError, onDone:onDone,
                        cancelOnError: cancelOnError), _id);
  }
}

class _WrapSub implements StreamSubscription {
 int _id;
 StreamSubscription _sub;
 _WrapSub(this._sub, this._id);
 void onData(d) { _sub.onData(d); }
 void onError(d) { _sub.onError(d); }
 void onDone(d) { _sub.onDone(d); }
 void pause([Future f]) { _sub.pause(f); }
 void resume() { _sub.resume(); }
 bool get isPaused => _sub.isPaused;
 Future cancel() {
   print("cancel $_id");
   var f = _sub.cancel();
   if (f is Future) {
     f = f.whenComplete(() { print("cancelled! $_id"); });
   }
   return f;
 }
 Future asFuture([val]) => _sub.asFuture(val);
}

Stream makeStream(Iterable iterable, int id) {
  Stream makeStreamInternal(Iterable iterable) async* {
    for (var element in iterable) {
      yield element;
    }
  }

  Stream s = makeStreamInternal(iterable);
  print("created stream $id");
  return new WrapStream(id, s);
}

Future test1() async {
  int i = 0;

  L:
  await for (String s in makeStream(['a', 'b'], i++)) {
    print("loop0: $s");
    await for (String s in makeStream(['a', 'b'], i++)) {
      print("loop1: $s");
      await for (String s in makeStream(['a', 'b'], i++)) {
        print("loop2: $s");
        continue L;
      }
    }
  }
}

main() {
  test1().then((_) => print("test1 completed"));
}
```
then the output is

> created stream 0
> listen 0
> loop0: a
> **created stream 1**
> listen 1
> loop1: a
> **created stream 2**
> listen 2
> loop2: a
> **cancel 2**
> **cancel 1**
> loop0: b
> **created stream 3**
> listen 3
> **cancelled! 2**
> loop1: a
> **created stream 4**
> listen 4
> loop2: a
> **cancel 4**
> **cancel 3**
> test1 completed
> **cancelled! 4**

That is, the cancel operations are called in the correct order. 
The wrapper ensures that you print exactly when the StreamSubscription's cancel method is called, not when it is reported to the callback.
I'm not entirely sure why there is a delay in calling the callback, I'll see if I can figure that out, but the VM isn't doing anything wrong here.


(However, what you can see is that stream 2 and 4 have a cancel method which returns a `Future`.
That future should really also be waited for by the loop - canceling an await-for stream should await the result of calling `cancel` because cancelling *is* an async operation and there is no way for the user to wait for it - but sadly the specification currently doesn't require this).
