### ISSUE TITLE
Server reports that setters override getters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25244]
Create a file with the following contents:

    abstract class A {
      int get x;
    }

    class B extends A {
      int _x;
      int get x => _x;
      set x(int i) => _x = i;
    }

Open the file in IntelliJ and the setter will be marked as overriding an inherited member. Clicking on the icon will navigate to the getter in class A. But given that setters do not override getters, this seems wrong and is confusing, making it hard to see when I'm missing an override annotation.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1519413002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/38a4193b5fb9bd6f2de73c099cc09a113d301664
