### ISSUE TITLE
optionally increase cutoff for string truncation?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25242]
It looks like the service protocol truncates strings at 128 chars. There are times when you want to show the user more than that. Specifically, in atom when the user has selected an object, we call `toString()` on that object and display the result. We're happy with thousands of chars coming back in this case, and would prefer that to having to page through the string somehow.

One possibility would be to (optionally?) globally increase the cutoff for string truncation. Another would be to increase the cutoff for results from the `evaluate()` / `evaluateInFrame()` methods, either all the time, or as an optional parameter.

related to https://github.com/dart-lang/sdk/issues/25157

**Comment by rmacnak-google** [comment]
You can get a full String response from a String reference using getObject.

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#ids-and-names

**Comment by devoncarew** [comment]
Cool, thanks for the info. I'll plan on calling that.
