### ISSUE TITLE
js-interop:anonymous annotation with missing external factory constructor

### ISSUE THREAD

**Issue by cjkao** [dart-lang/sdk#25241]
**Describe the issue you're seeing**
anonymous annotation without external factory constructor would lead dart2js crash
```
NoSuchMethodError: method not found: 'orderedForEachParameter'
Receiver: null
Arguments: [Closure: (ParameterElement) => dynamic]
dart:core                                                                 Object.noSuchMethod
```

**Does it happen in Dartium or when compiled to JavaScript?**
dart2js
* Dart SDK version: 1.13.0
* pkg/js version: 0.6.0

Failing code:
```dart
// or a link to a GitHub repo or gist.github.com
@JS()
@anonymous
class PolarOptions {
  bool scaleShowLabelBackdrop; 
}
void main() {
 new PolarOptions();
}
```

**Comment by sigmundch** [comment]
Thanks for reporting - thankfully we already have a fix for this (see #24974). The fix is already available in the Dart dev channel (1.14). There is a pending request to merge the fix into the stable channel too (you can subscribe for updates at #25068).
