### ISSUE TITLE
generic functions with dynamic arguments

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25243]
I was trying to type annotate the following function:

<img src="https://cloud.githubusercontent.com/assets/1035299/11763320/235eac98-a106-11e5-8395-d29302d0ec67.png" width="75%">

I'm not totally sure what the best way is to cast it so that strong mode is happy, and the user gets an error, if they use an not allowed argument. In the end, I tried this:

```dart
Iterable/*<T>*/ makeFlat/*<T>*/(Iterable<dynamic> iterable) sync* {
  if (iterable.every((e) => e is! Iterable)) {
    if (iterable is Iterable/*<T>*/) {
      yield* iterable;
    } else {
      throw _makeFlatArgError;
    }
  } else {
    for (dynamic element in iterable) {
      if (element is Iterable) {
        yield* makeFlat/*<T>*/(element);
      } else {
        yield new Cast<T>(element).casted;
      }
    }
  }
}

class Cast<T> {
  final T casted;
  Cast(dynamic element) : casted = element as T;
}

final _makeFlatArgError = new ArgumentError("The argument of makeFlat must be"
    "an Iterable where the elements are either of type T or Iterable<T>");
```

Now, strong mode is happy. But it feels a very hacky, and I guess it is not really what I should do. Any suggestions how to tackle this?

**Comment by zoechi** [comment]
I think this should look like
`yield element as dynamic /*=T*/`
`yield new Cast<T>(element).casted;`

**Comment by kasperpeulen** [comment]
@zoechi right thanks!
