### ISSUE TITLE
Function literals in annotations crash Dartium

### ISSUE THREAD

**Issue by mgreenland** [dart-lang/sdk#25240]
The following code:

```dart
class SomeAnnotation {
  const SomeAnnotation(someValue);
}

@SomeAnnotation(() => 3)
main() {}
```

causes Dartium to crash to the "Aw, Snap!" screen.

Other non-const values still print out the "expression is not a valid compile-time constant" error; it's just function literals that cause this, as far as I can tell.

I was able to reproduce this on Linux with Dart version 1.13.0-dev.7.12 and on Windows with Dart version 1.14.0-dev.4.0

**Comment by rmacnak-google** [comment]
```
import 'dart:mirrors';

class SomeAnnotation {
  const SomeAnnotation(someValue);
}

@SomeAnnotation(() => 3)
main() {
  print(reflect(main).function.metadata);
}
```

crashes the standalone VM.

**Comment by rmacnak-google** [comment]
c740fea5450707e077c8088157df724acabc673a
