### ISSUE TITLE
Bad var name suggestion and validation when extracting variable

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25253]
Try to extract `foo()`. Analysis Server suggests `foo` as a name for the extracted variable, but this name will cause red code. Also Analysis server won't prevent me from giving `bar` name to the variable, but such name will introduce red code as well.
![image](https://cloud.githubusercontent.com/assets/4499789/11789714/04d0d9e6-a2a9-11e5-9284-30946fc6726b.png)
![image](https://cloud.githubusercontent.com/assets/4499789/11789741/202247de-a2a9-11e5-840f-ce0712a3644b.png)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1528013004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/70cd905c4dbe845f10f3f149190eb273aa56d8bf
