### ISSUE TITLE
Hide implementation members in dart:js

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25259]
![screen shot 2015-12-14 at 2 28 24 pm](https://cloud.githubusercontent.com/assets/17034/11796153/a07e754a-a26f-11e5-9922-e7026d641173.png)

From https://api.dartlang.org/135309/dart-js/dart-js-library.html - SDK at fd0f649327dab7831f8f11a536bbbc6c9c00ede3

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by joshualitt** [comment]
This appears to have been fixed.
