### ISSUE TITLE
Extracting variable from void function call

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25252]
Analysis Server suggests to extract local variable initialized with a void functino call. Is tehre any sense in it?
![image](https://cloud.githubusercontent.com/assets/4499789/11789611/6d88a82a-a2a8-11e5-8bf5-8a014012d3c1.png)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1528023002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f71ae984a993c07bc95eb4d544755c562336adcd
