### ISSUE TITLE
Dart List literals should infer type from asignee

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#25254]
`bug.dart`:
```
void main() {
  List<int> foo = [""];
  print(foo is List<int>);
  print(foo is List<double>);
}
```
```
%dart bug.dart
true
true
```
```
%dartanalyzer bug.dart 
Analyzing [bug.dart]...
No issues found
```
```
%dartanalyzer bug.dart --strong
Analyzing [bug.dart]...
[error] Type check failed: [""] (List<dynamic>) is not of type List<int> because "" cannot be typed as int (/src/flutter/bug.dart, line 3, col 19)
1 error found.
```
Strong mode is correct here, this is an error.  The analyzer should surface this error, by default.  But really the bug is in the language, that the language should create [] as type `<int>` because the LHS is typed as such.  I shouldn't need to type `<int>` twice in order to get the typing.  If I really want dynamic, I should need to type `List<int> = <dynamic>[];`

@sethladd suggested @gbracha might have context here.  @hixie

**Comment by floitschG** [comment]
One of the fundamental properties of Dart is that removing type annotations (not generic types) doesn't change the semantics of programs.
Thus `int x = ...` and `var x = ...` have the same semantics. Similarly `List<int> x = ...` and `var x = ...` have the same runtime semantics.
This is the same reason that `double x = 0`; doesn't work, and is another reason that `int x` can't be initialized to `0`.

This property is fundamental to Dart, so closing as WAI.
