### ISSUE TITLE
Version constraint on analyzer 0.26.1+14 too flexible?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#25250]
The analyzer version 0.26.1+14 is not the newest at this point, and unittest is being replaced, but it may still be useful to know about this problem that I've encountered. So here we go:

Consider a package that specifies dependencies including the following ones:

``` yaml
dependencies:
  analyzer: '>=0.26.0 <=0.26.1+14'
  unittest: '^0.12.0'
```

This is accepted by `pub get` and `pub upgrade`, so the constraints do have a solution (in the concrete examples I have, the resulting pubspec.lock has analyzer version 0.26.1+14 and unittest version 0.12.3). However, this combination of versions makes vm execution fail with a "malformed type: ..'DelegatingSink'.." message, and it makes compilation/analysis warn about the undefined class name.

Actually, the message from `dartanalyzer` (hence presumably from the analyzer) is rather confusing:

```
  The name 'DelegatingSink' is defined in the libraries 'delegating_sink.dart' and
      'sink.dart (via async.dart)' 
      (/usr/local/google/home/eernst/.pub-cache/hosted/pub.dartlang.org/test-0.12.3+9/lib/src/runner/engine.dart, line 95, col 36)
```

which doesn't obviously parse into "the name 'DelegatingSink' is undefined".

In any case, it seems that some of the constraints involved should have been more restrictive, or some package version should have bumped the major version number (using X+1 in X._._ or 0.X._) because it contains a breaking change (enough to break 'engine.dart' at least).

**Comment by bwilkerson** [comment]
I'm not sure how much of this is actionable, but we can certainly improve the error message.

**Comment by eernstg** [comment]
I understand that it wouldn't be easy to fiddle with the version constraints in the middle of a series of versions with increments at the "+" level. Focusing on the error message makes sense (and the issue might be relevant up to the most recent version).

**Comment by pq** [comment]
@scheglov I feel like the error here actually got better.  Or maybe it's just happening less...  Or is that wishful thinking?

**Comment by scheglov** [comment]
I don't actually publish anything these days.
But I don't hear much cries of despair too.

**Comment by pq** [comment]
I'll take a gamble then and close as stale (or at least de-prioritized).
