### ISSUE TITLE
expose the list of registered service extensions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25257]
From discussion here: https://github.com/flutter/flutter/pull/911#discussion_r47564318

It would be nice to have a service protocol command to retrieve the list of service extensions registered for each isolate. This would allow clients to know about available services without having to speculatively call them. Something like `supportsCommand(String id)`, or `List<String> getRegisteredExtensions()`.

@johnmccutchan

**Comment by devoncarew** [comment]
@Hixie

**Comment by devoncarew** [comment]
And, probably as part of this, it'd be nice to get events when an extension is registered. So, a client can ask for all the service extensions when it first learns of an isolate, and then get notified of any new service extensions. It can always have an up-to-date view of the service extensions and avoid any race conditions in when the app actually registered the extension.

I'll follow up in email just to clarify the use cases.

**Comment by johnmccutchan** [comment]
To summarize:

1) Add a service protocol RPC:

getExtensionList(IsolateId isolate)

2) Add an event stream for extension registration events.

**Comment by devoncarew** [comment]
Yup, that would be it. Happy to follow up to observatory-discuss if you think more details on the use case would help.

**Comment by johnmccutchan** [comment]
I think I've got enough to run with.

**Comment by iposva-google** [comment]
Instead of email, which we might or might not receive, why not explain some of your use cases here? Thanks!

**Comment by johnmccutchan** [comment]
This was fixed in https://codereview.chromium.org/1527793004/
