### ISSUE TITLE
Analysis Server hangs when asking for refactoring

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25251]
Reproducible with both SDKs 1.13 and 1.14-dev.4.0. Using Windows 8.1, didn't try on Mac/Linux
Simple single-file project:
```
void main() {
  print("foo");
}
```
Place caret inside `"foo"` string, no selection, try to introduce variable. Server gets stuck. No errors in instrumentation-log-file. The last line in log is pasted below, after that server doesn't accept any requests and doesn't send any responses.

```
Req:{"id"::"10","method"::"edit.getRefactoring","params"::{"kind"::"EXTRACT_LOCAL_VARIABLE","file"::"C::\\dart_projects\\untitled1\\bin\\main.dart","offset"::24,"length"::0,"validateOnly"::true,"options"::{"name"::"name","extractAll"::true}},"clientRequestTime"::1450115425016}
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1522193002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/b44ed3e91e208f4066417b7d37bfc7905cc1edf4
