### ISSUE TITLE
Constant assignments should infer constant constructors

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#25261]
For example, take this "goldfish" constant Item constructor:
```
static const Item goldfish =
	const Item(Colors.orange, "goldfish", "goldfishes", const [
		const FishableItemTrait(0.8),
		const CrushableItemTrait(const [const CrushChance(Items.gold, 0.7)])
	]);
```
In order to actually make this object constant, I had to opt to using const everywhere, instead of letting Dart infer the need for const. This would not become ambiguous in any way as the item itself, the goldfish, is declared constant.

**Comment by zoechi** [comment]
This is a known issue https://github.com/lrhn/dep-const/blob/master/proposal.md

**Comment by lrhn** [comment]
The original issue is #4046.
As you might guess, I completely agree that it should be fixed.
