### ISSUE TITLE
Dart is missing &&= and ||= operators

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25264]
It's really useful to be able to write code like:

``` dart
    result.canTap ||= onCanTap != null;
    result.canDoubleTap ||= onDoubleTap != null;
    result.canLongPress ||= onLongPress != null;
```

...but currently we can't because `||=` and `&&=` don't work in Dart. `|=` and `&=` work, but `|` and `&` aren't implemented by `bool` so that doesn't help here.

**Comment by lrhn** [comment]
I agree that it would be nice.

I think `||=` and `&&=` would have slightly different semantics than other `op=` assignments. Those effectively do `lhs = lhs op expr`. In the case of `||=` and `&&=` you probably don't even want to do the assignment if it is already true/false, so the translation should be something like:
```dart
lhs &&= expr   ==>   let v = lhs in (v ? lhs = expr : v)
lhs ||= expr   ==>   let v = lhs in (!v ? lhs = expr : v)
```

For non-short-circuit boolean operators, see #1080
Adding `&` and `|` to bool, like in Java and C++, was voted down at the time (the change is minscule, it's two one-line functions in the core library, but the spec might want to make them compile-time constants as well).

**Comment by floitschG** [comment]
Fwiw we already opened that can of worms with `??=`. Since that one already exists we should just all `||=` and `&&=`.

**Comment by munificent** [comment]
Tracked by: #26996. I know this one's older, but that one has more details.
