### ISSUE TITLE
Observatory downloaded packages have invalid paths in .package files

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25262]
The collection of packages that is downloaded for the observatory build, in third_party/observatory_pub_packages, has .packages files in the individual package directories.
These files have absolute paths to the pub caches on various contributor's machines, which are meaningless on other people's machines.

I think perhaps these .packages files shouldn't even be there?
@johnmccutchan

**Comment by johnmccutchan** [comment]
We probably shouldn't have .packages file checked in there.

**Comment by johnmccutchan** [comment]
@turnidge FYI

**Comment by johnmccutchan** [comment]
@sigmundch I actually wonder if this bug is in the html package on pub.

**Comment by johnmccutchan** [comment]
cat html/.packages 
# Generated by pub on 2015-08-28 13:15:28.852.
args:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib/
csslib:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/csslib-0.12.1/lib/
logging:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/logging-0.11.1+1/lib/
path:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/path-1.3.6/lib/
source_span:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/source_span-1.1.4/lib/
stack_trace:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.4.1/lib/
unittest:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/unittest-0.11.6+1/lib/
utf:file:///usr/local/google/home/sigmund/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+2/lib/
html:lib/

**Comment by sigmundch** [comment]
quite possible that the html package doesn't have `.packages` in the git ignore.

@munificent @nex3 - should we automatically exclude `.packages` files when calling `pub lish`?

**Comment by sigmundch** [comment]
https://codereview.chromium.org/1528213003/

**Comment by nex3** [comment]
We do automatically exclude them—*if* you don't have a `.gitignore`. If you do, we follow that instead, because we trust you to have a better idea than we do of what you want to ignore.

**Comment by sigmundch** [comment]
I see, makes sense.
