### ISSUE TITLE
Code completing in a constructor for a non-existent class shows me plenty of options

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25266]
Is this the right behavior? I'm trying to explore the code, and so I typed `new Button()` and tried to see what I can put into Button's constructor. I saw a lot of options, none of them looked right.

Turns out, there's no class called Button! :)

Expected: no options for completion, maybe even with an error that says "no completions for unknown class".

![screen shot 2015-12-15 at 1 53 24 pm](https://cloud.githubusercontent.com/assets/5479/11825457/ee64362c-a333-11e5-91ee-d0a2ab872707.png)

And for the record, I did notice the orange underline under Button, but I figured/assumed that was telling me "there's no constructor with zero parameters" which is why I was looking for what I could use as arguments.

**Comment by bwilkerson** [comment]
I don't think we want to not suggest valid options in invalid code. While the lack of a concrete constructor means that we have little or no information to use for ranking, it's not impossible that the user intends to use quick fixes to create a class and constructor that match the invocation site after typing in the invocation site.
