### ISSUE TITLE
expose annotations to help dart2js optimizations

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25272]
I'd like to create a package that exposes some annotations understood by dart2js. 
Some of the use cases for this are:
- frameworks could indicate hot-paths that can benefit from inlining. For example, see https://github.com/dart-lang/sdk/issues/25270 request to inline looseIdentical in ng2 apps.
- we identified something curious and are deciding whether it is worth writing an analysis for it. Before doing so, we could include annotations in the source code to test out a transformation idea. For example, we could use `@notnull` to help the compiler understand nullability on certain cases that the current inferrer failed to do so.
- we can provide one-day a more fine-grain control on trusting types (e.g. trust the types of this package, but not of some other third-party package).

For now, I suggest we make public the same annotations we have today on `package:expect` for our own unit tests. As part of doing that we can then see what would be the proper way to add more.

**Comment by rakudrama** [comment]
We have `@dart2js.noInline` and `@dart2js.tryInline`:
```
///     import 'package:meta/dart2js.dart' as dart2js;
///
///     @dart2js.noInline
///     String text() => 'A String of unusual size';
```

We will put more annotations in the same package as they become available.
