### ISSUE TITLE
Windows SDK build broken: compiler is out of heap space

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25276]
I guess MSVC can't handle array initializers that large. Is it possible to split this into multiple files? @johnmccutchan @zanderso 

http://build.chromium.org/p/client.dart/builders/vm-win32-debug-be/builds/7672/steps/build/logs/stdio

>..\build\DebugIA32\obj\global_intermediate\observatory_assets.cc(433174): fatal error C1060: compiler is out of heap space

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1534523002/

**Comment by fsc8000** [comment]
Agree. Compressing is even better.
