### ISSUE TITLE
Compile ng2 change checks down to !==

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25270]
Due to a difference in the way Dart VM and JS perform `String` comparison (see https://github.com/dart-lang/sdk/issues/22496) Angular checks for object identity using the following function:

``` dart
bool looseIdentical(a, b) =>
    a is String && b is String ? a == b : identical(a, b);
```

This way both Dartium and Chrome behave the same. However, in JS you already get this behavior for free using the `===` operator. The code above results in the following:

``` dart
    looseIdentical: [function(a, b) {
      return typeof a === "string" && typeof b === "string" ? J.$eq$(a, b) : a == null ? b == null : a === b;
    }

    // myriads of calls like this one are generated from people's templates:
    if (!Q.looseIdentical(l_foo0, this.foo0)) {
      this.dispatcher.notifyOnBinding$2(...);
      this.foo0 = l_foo0;
    }
```

We are paying the cost of two function calls and a type check before we get to `===`. I'd rather see the whole thing inlined and reduced to:

``` dart
    if (l_foo0 !== this.foo0) {
      this.dispatcher.notifyOnBinding$2(...);
      this.foo0 = l_foo0;
    }
```
## Attempt to trick dart2js

Trick by @sigmundch:

``` dart
const _IS_DART_VM = !identical(1.0, 1);
bool looseIdentical(a, b) => _IS_DART_VM
    ? a is String && b is String ? a == b : identical(a, b)
    : identical(a, b);
```

Results in the following:

``` dart
    looseIdentical: function(a, b) {
      var t1 = a == null ? b == null : a === b;
      return t1;
    }
```

Slightly better, but still costing a function call and a conditional expression before we get to `===`.

How can we get it down to just `!==`? These comparisons are done by change detectors which are on the performance hot path.

**Comment by yjbanov** [comment]
Idea: would it be possible to tweak Dart VM to match JS `===` semantics in Dartium (and _only_ in Dartium)? After all, all debugging that's happening in Dartium ends up compiled to JS anyway.

**Comment by matanlurey** [comment]
No more Dartium!
