### ISSUE TITLE
Stream#map docs don't cover all cases

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#25273]
Right now it says
"Creates a new stream that converts each element of this stream to a new value using the convert function.

The returned stream is a broadcast stream if this stream is. If a broadcast stream is listened to more than once, each subscription will individually execute map for each event."

But this doesn't say what happens when it's a non-broadcast stream nor what happens when it's listened to 0 or 1 times.  in particular, it's not obvious that in all cases,

(*) if there are N listeners, then `convert` gets called N times for each event on the stream.

E.g. if there are 0 listeners, then `convert` is never called, no matter how many events there are on the stream.  If you are looking for a side effect, `map` might make you unhappy.  Could you update the docs to make (*) clear?

**Comment by lrhn** [comment]
Thanks for the report. Docs have been updated to be more explicit about what happens.
