### ISSUE TITLE
Windows package bots' taskkill seems flaky

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25279]
See the status pages for [`glob`](http://build.chromium.org/p/client.dart.packages/builders/packages-windows-glob), [`http_multi_server`](http://build.chromium.org/p/client.dart.packages/builders/packages-windows-http_multi_server), and [`http_throttle`](http://build.chromium.org/p/client.dart.packages/builders/packages-windows-http_throttle) for example. More often than not the Windows builds are being reported as failing in the taskkill step, which makes it difficult to see when actual test failures occur.

**Comment by whesse** [comment]
This seems to be the same issue as on the windows pub bots, where a run of pub turns into an unkillikable process.  I'm still trying to pin down the cause.

**Comment by whesse** [comment]
This issue is tracked at #24086
