### ISSUE TITLE
analysis server from SDK 1.13 reports 1.12 as its version

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25283]
$ dart --version
Dart VM version: 1.13.0 (Wed Nov 18 12:15:29 2015) on "macos_x64"

$ dartanalyzer --version
dartanalyzer version 1.13.0

$ dart ~/software/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
{"event":"server.connected","params":{"version":"1.12.0"}}
^C

**Comment by bwilkerson** [comment]
Correct. The version reported by the server is the version of the wire protocol, not the version of the SDK in which it is embedded.
