### ISSUE TITLE
ConstantEvaluationTarget_Annotation consumes too much memory, shouldn't exist

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25285]
The analyzer class `ConstantEvaluationTarget_Annotation` contains a reference to `Annotation`, which is an AST node.  This is bad because AST nodes contain parent pointers; therefore the presence of any `ConstantEvaluationTarget_Annotation` referring to a given compilation unit will keep that entire compilation unit's AST in memory.  This is likely the cause of a significant amount of unnecessary memory usage in analyzer.

In discussing what to do about this with @scheglov and @bwilkerson, we realized that `ConstantEvaluationTarget_Annotation` shouldn't exist at all.  Instead what we should do is have `ElementAnnotation` implement `ConstantEvaluationTarget`, so that the `ElementAnnotation` itself can be used as the target.  Additionally, we need for `ElementAnnotation` to store a clone of the AST for the annotation (so that at the time of constant evaluation, we can evaluate the constant).  This clone will be detached from the rest of the AST for the compilation unit, so it won't consume unnecessary memory.

**Comment by kevmoo** [comment]
@stereotype441 Is this worthy of a cherry-pick for 1.14? If not, we should change the milestone

**Comment by stereotype441** [comment]
I believe this is a prerequisite for proper functioning of annotations in summaries, so I'm starting work on it now.
