### ISSUE TITLE
Version-aware analyzer

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#25284]
One thing I would love to see is the analyzer being aware of the project as a whole and the language constraints. In particular what I'm thinking is the analyzer being able to detect the SDK constraint (eg: `sdk: ">=1.9.0"`) from the pubspec. Then provide warnings (probably informational?) based on that, such as if I had the 1.9 sdk constraint but tried to use null-aware operators (`??=`, etc). It would be nice if it triggered a warning saying the language usage doesn't match the sdk version.

**Comment by srawlins** [comment]
This is now implemented; the analyzer will recognize new syntax and will report if the version constraints do not match. :)
