### ISSUE TITLE
New package bots

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25288]
The following packages don't have package bots yet:

- [x] [`convert`](/dart-lang/convert)
- [x] [`pub_semver`](/dart-lang/pub_semver)
- [x] [`shelf_static`](/dart-lang/shelf_static)
- [x] [`shelf_proxy`](/dart-lang/shelf_proxy)
- [x] [`source_map_stack_trace`](/dart-lang/source_map_stack_trace)
- [x] [`vm_service_client`](/dart-lang/vm_service_client)
- [x] [`boolean_selector`](/dart-lang/boolean_selector)

Thanks!

**Comment by nex3** [comment]
I've added another package to the list. @whesse can we move forward on this?

**Comment by whesse** [comment]
Yes, this is easy to do - it just fell off my radar.  I can do it tomorrow
or next week.  But the number of packages is getting quite big - I will
want to split it onto multiple slaves soon, or even multiple waterfalls.

On Thu, Feb 18, 2016 at 11:01 PM, Natalie Weizenbaum <
notifications@github.com> wrote:

> I've added another package to the list. @whesse
> <https://github.com/whesse> can we move forward on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25288#issuecomment-185941774>.
>



-- 
William Hesse

**Comment by whesse** [comment]
boolean_selector is not published to pub, by the way.

**Comment by whesse** [comment]
CL for this uploaded: https://codereview.chromium.org/1715693002

**Comment by nex3** [comment]
https://pub.dartlang.org/packages/boolean_selector ?

Note that the search index can take a while to catch up to the actual
uploaded packages. The only reliable way to tell if a package exists is to
plug in its URL directly.
