### ISSUE TITLE
analyzer doesn't warn about deprecated fields

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25295]
To reproduce, paste into DartPad:

class Foo {
  @deprecated
  String someField;
  
  @deprecated
  someMethod() {}
}

main() {
  Foo f = new Foo();
  print(f.someField);
  f.someMethod();
}

I expected two deprecation warnings (for someField and someMethod) but only got one, for someMethod.

**Comment by bwilkerson** [comment]
Duplicate of #22963
