### ISSUE TITLE
Could I code complete from a library that I've imported, even if it's not in my "show" list?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25298]
Hi,

I have this:

```
import 'package:flutter/material.dart'
    show
        Align,
        BuildContext,
        FractionalOffset,
        Positioned,
        Stack,
        State,
        StatefulComponent,
        Text,
        Widget,
        runApp;
```

and I was trying to add a Container. It wouldn't code complete, presumably because it wasn't in my show list. 

Once I added it to my show list, I could complete it.

Would like to offer completes for names that come from libraries I've imported, even if they aren't in my show list. The completion should then also add it to my show list, if I have one.

There is a Quick Fix that adds a new name to the show list, but that's only after I manually type the name.

Thanks!

**Comment by alexander-doroshko** [comment]
related to https://github.com/dart-lang/sdk/issues/21931

**Comment by bwilkerson** [comment]
We now suggest items from imported libraries that are not yet shown.
