### ISSUE TITLE
No static warning in checked mode if two libraries with the same name imported

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25291]
Dart Language spec 4th Edition, Dec 2015. 18.1 Imports

"It is a static warning to import two different libraries with the same name
unless their name is the empty string."

But if two libraries with the same name imported dart produces no errors in checked mode. Example
```dart
import "lib1.dart";
import "lib2.dart";

main() {
 x == y;
}
```
lib1.dart:
```dart
library library_name;
var x = 1;
```
lib2.dart:
```dart
library library_name;
var y = 1;
```
Dartanalizer produces warning on this code (as expected) but dart in checked mode produces no error or warning.

Tested on Dart VM version: 1.14.0-edge.e47ac24c795cd3aebe3248c622dca5864a965c3e (Thu Dec 17 20:15:08 2015) on "windows_x64"

**Comment by lrhn** [comment]
This is a *warning*. Warnings are created by static analysis, not at runtime. The VM doesn't do static analysis, it only implemented the runtime semantics of Dart, so it doesn't give warnings at all, only errors.

Warnings are independent of checked mode - checked mode is a runtime property and it just enables assertions (including type assertions).
