### ISSUE TITLE
Typo in specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25290]
Dart Language specification, 4th Edition / December 2015, 16.18 Property Extraction

"Evaluation of a conditional property extraction expression e of the form e1?.id
is equivalent to the evaluation of the expression ((x) => x == null?null :
x.id)(e1). unless e1 is a type literal, in which case it is equivalent to **e1.m**"

I believe that there should be "...in which case it is equivalent to **e1.id**"

**Comment by natebosch** [comment]
I think in the current spec this is at https://github.com/dart-lang/sdk/blob/0789ab8b0ed0e6a90ea02d317195be705581f652/docs/language/dartLangSpec.tex#L7430-L7458 and no longer has this bug.
