### ISSUE TITLE
Package XXX has no versions that match YYY derived from 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25301]
I have two packages, both both rely on `reflectable: ^0.5.0` 
pub get gives me the error message:
```
Package reflectable has no versions that match >=0.5.0 <0.6.0 derived from:
- beanvalidator 0.1.0 depends on version ^0.5.0
- validate_sample depends on version ^0.5.0
``` 
reflectable has currently 0.5.0 

![screenshot-1955](https://cloud.githubusercontent.com/assets/116654/11931299/9bdb635a-a7eb-11e5-8b09-3150286a2646.png)

**Comment by MikeMitterer** [comment]
PS: Here is what I get from `pub -v update &> pub.update.txt`
[pub.update.txt](https://github.com/dart-lang/sdk/files/68483/pub.update.txt)

**Comment by zoechi** [comment]
Does validate_simple or di depend on analyzer < 0.27.0?
reflectable 0.5.0 depends on 0.27.1

**Comment by MikeMitterer** [comment]
It's probably di - as you assume it depends on analyzer < 0.27.0
But even it is di - what does this error message mean???? It's absolut crap!
I also tried to overwrite the analyzer dependencies via dependency_override - no chance.

**Comment by zoechi** [comment]
This message is misleading and a known issue and it just means that `pub` couldn't find a compatible set of dependencies. There are probably more conflicts.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/pub#1375
