### ISSUE TITLE
Unmatched token is parsed as modifier

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#25308]
Running the following code:
    class C {
      C(v) {
          throw '');
      }
    }
gives the error message
   Can't have modifier ''SymbolToken({)' isn't closed.' here.

The compiler should not complain about modifiers here - instead it should report the error associated with the unmatched token.

The error message is reported from 
Parser.expectVarFinalOrConst (sdk/pkg/compiler/lib/src/parser/parser.dart:922:16)

**Comment by johnniwinther** [comment]
Thank you! I've been looking for a small repo of this kind of error!
