### ISSUE TITLE
dart2js: sourcemaps/source_mapping_operators_test fails

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#25304]
**sourcemaps/source_mapping_operators_test** fails after https://github.com/dart-lang/sdk/commit/d2c403704c5cd13779a00eee22894158a50fdc59

I think the generated code changed because the CL allows a better type to be inferred for **.length** in `args.length > 0`.

I don't know how to fix the expected output. Perhaps there should be a README with instructions that work when copy&paste-ed.

```
Missing code points for function(main) in 'tests/compiler/dart2js/sourcemaps/operators_test_file.dart' in config 'ssa':
  CodePoint[kind=Call (PropertyAccess),js=t2.$gt(),dart=null,location=null]
  CodePoint[kind=Return,js=return t2.$gt(),dart=null,location=null]
Using the new source information system.
Inlining disabled
```

**Comment by sigmundch** [comment]
the test is marked as passing now, I believe this bug is stale.
