### ISSUE TITLE
Provide quick fix for removing final variable

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25316]
![image](https://cloud.githubusercontent.com/assets/1035299/12007324/aec04978-abff-11e5-82bf-149d227ee5fb.png)

I think it would be nice to have a quick fix here that removes the final keyword.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1545323002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/e1c6faceb571535847557a759af4e2e1e31d218a

**Comment by kasperpeulen** [comment]
awesome thanks
