### ISSUE TITLE
Analysis server crashes with stacktrace in split_store

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25314]
This morning I'm seeing repeated analysis server crashes with a stacktrace that looks like this:

    RangeError (index): Invalid value: Not in range 0..36063, inclusive: -1
    #0      List.[] (dart:core-patch/growable_array.dart:135)
    #1      StringCodec.decode (package:analysis_server/src/services/index/store/codec.dart:166)
    #2      ElementCodec.decode (package:analysis_server/src/services/index/store/codec.dart:85)
    #3      LocationData.getLocation (package:analysis_server/src/services/index/store/split_store.dart:624)
    #4      IndexNode.getRelationships (package:analysis_server/src/services/index/store/split_store.dart:475)
    #5      SplitIndexStore.getRelationships.<anonymous closure> (package:analysis_server/src/services/index/store/split_store.dart:899)
    #6      _rootRunUnary (dart:async/zone.dart:914)
    #7      _CustomZone.runUnary (dart:async/zone.dart:810)
    #8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
    #9      _Future._propagateToListeners (dart:async/future_impl.dart:585)
    #10     _Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:568)
    #11     _rootRunUnary (dart:async/zone.dart:914)
    #12     _CustomZone.runUnary (dart:async/zone.dart:810)
    #13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
    #14     _Future._propagateToListeners (dart:async/future_impl.dart:585)
    #15     _Future._completeWithValue (dart:async/future_impl.dart:376)
    #16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
    #17     _rootRun (dart:async/zone.dart:907)
    #18     _CustomZone.run (dart:async/zone.dart:802)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:708)
    #20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
    #21     _microtaskLoop (dart:async/schedule_microtask.dart:43)
    #22     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
    #23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
    #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

It looks like somehow a `LocationData` object is being created with an `elementId1` of -1, which I'm guessing should never happen.

I have some guesses as to what I did that provoked this error.  I'll do some additional digging and update the bug if I come to any firm conclusions.

**Comment by stereotype441** [comment]
It looks like it may be a problem updating the index after incremental analysis.  I have a file containing a class with a static final member whose initializer is the result of invoking a function literal:

    static final Map<String, UnlinkedPublicNamespace> corePublicNamespace = () {
      var analysisContext = AnalysisContextFactory.contextWithCore();
      Map<String, UnlinkedPublicNamespace> uriToNamespace =
      <String, UnlinkedPublicNamespace>{};
      summarize_elements.LibrarySerializationResult serializedCore =
      summarize_elements.serializeLibrary(
          new BuilderContext(),
          analysisContext.typeProvider.objectType.element.library,
          typeProvider);
      for (int i = 0; i < serializedCore.unlinkedUnits.length; i++) {
        uriToNamespace[serializedCore.unitUris[i]] = new UnlinkedUnit.fromBuffer(
            serializedCore.unlinkedUnits[i].toBuffer()).publicNamespace;
      }
    }();

(Note: the code above is not expected to make much sense--I was in the middle of writing it at the time this bug occurred).

If I make a small change to the body of the function literal (e.g. commenting out the line `var analysisContext = AnalysisContextFactory.contextWithCore();`) the server log says that incremental analysis has succeeded, but then a fraction of a second later it crashes with a fatal exception, and the server log indicates that the command causing the fatal exception was the command with the incremental change.

**Comment by stereotype441** [comment]
This appears to be a minimal test case.  Create a file containing the text:

    class C extends D {
      static final f = () {
        var x = 0;
      }();
    }

    class D {}

Then place the cursor to the left of the `0` and type `1`.  Analysis server crashes.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1546223003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/8302308b715234d8d01520a5917c0fc839a47de9
