### ISSUE TITLE
Specification: not clear explanation of mixin application warning

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25312]
Dart Language specification, 4th Edition, Dec 2015, "12.1 Mixin Application"

"Let MA be a mixin derived from a class M with direct superclass Sstatic.
Let A be an application of MA. It is a static warning if the superclass of A
is not a subtype of Sstatic."

The first sentence from the above is not clear enough. Sstatic is superclass of M or MA (in 4th edition mixins are allowed to have superclasses other than Object)? What exactly is described above?
```dart
class Sstatic {
}
class M {
}
class MA = Sstatic with M;
class SuperA {
}
class A = SuperA with MA;
```
Or may be
```dart
class Sstatic {
}
class M extends Sstatic {
}
class SuperA {
}
class A = SuperA with M;
```
Please clarify and change the spec to be more clear here.

**Comment by sgrekhov** [comment]
Please clarify, what exactly is ment in specification under
"Let MA be a mixin derived from a class M with direct superclass Sstatic.
Let A be an application of MA. It is a static warning if the superclass of A
is not a subtype of Sstatic."
Could you show an example?

**Comment by lrhn** [comment]
The mixin `MA` is derived from the class `M`, and `M` has direct superclass S<sub>static</sub>.
That means that there is a class:
```dart
class M extends S_static { 
  contentsOfMA(); 
}
```
The mixin, MA, derived from this class contains the members declared by `M` (e.g.,` contentsOfMA()`).

The mixin application of `MA` with superclass `X` can, for example, be written as
```dart
class A = X with MA;
```
It is an error if `X` is not a subtype of S<sub>static</sub>.

You can also write:
```dart
class Z extends X with MA { something(); }
```
Here the superclass of `Z` is the mixin application `X with MA` and *that* mixin application must satisfy that `X` is a subtype of S<sub>static</sub>.

The description is exactIterable<int> normalizeCase(Iterable<int> codePoints);

**Comment by lrhn** [comment]
I have added an explanatory comment to the spec.
