### ISSUE TITLE
Inconsistent behavior with String

### ISSUE THREAD

**Issue by krkboasit** [dart-lang/sdk#25311]
## Summary:

When starting to type 'string' with a lowercase 's', the intellisense does not contain the type 'String', however it does contain 'toString()'.

## What steps will reproduce the problem?

1. Create a new project in Webstorm.
2. Type the letters str all in lowercase.

## What is the expected output? What do you see instead?

__Expected:__
The option 'String' will show up in the intellisense.

__Actual:__
The option 'toString()' shows up, but 'String' does not.

## What version of the product are you using?

Dartium dartium-win-full-dev-1.14.0-dev.5.0.0

WebStorm 11.0.2
Dart V1.14-dev.5.0

On what operating system?
Windows 7 SP1(32bit)
MacOS(64bit)

## Please provide any additional information below.

Typing 'Str' with an uppercase 'S' does make 'String' appear in the intellisense.

This seems to be an issue when the identifier starts with a lowercase letter.

**Comment by alexander-doroshko** [comment]
@krkboasit This a configurable feature of WebStorm. See Settings (Preferences) | Editor | General | Code Completion | Case sensitive completion. Default is 'First letter'. Just set it to 'None' if you want.
![image](https://cloud.githubusercontent.com/assets/4499789/11975856/1e07e716-a983-11e5-819e-6a8523c1a1ba.png)
