### ISSUE TITLE
Extracting variable extracts stuff that can't be extracted

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25313]
See the following gif:

![](https://youtrack.jetbrains.com/_persistent/refactor_webstorm.gif?file=74-280232&v=0&c=true&rw=242&rh=170&u=1450961863443)

So there are two issues:

* Sometimes things get extracted that can't be extracted (not much sense to extract just `A`, not possible to extract `a`)
* Things that can be extracted are not always listed in the options (I wanted to extract `new A(a: 1)`)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1547113002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/78ae012d2da31c0d10e918402081e1562fbe5967

**Comment by kasperpeulen** [comment]
Thanks @scheglov!
