### ISSUE TITLE
dart:objc

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#25326]
On iOS, Flutter runs the DartVM in a process that also contains lots of Objective-C code. It would be useful to be able to communicate between the DartVM and the Objective-C code.

One approach is to introduce a built-in `dart:objc` library that exposed the Objective-C ABI to Dart (e.g., `objc_sendMessage` and friends).  We could build this library on top of the DartVM C API, but I imagine it would be more efficient to build the library inside the VM.

Most developers wouldn't use `dart:objc` directly.  Instead, they'd use auto-generate Dart code that reflected the Objective-C APIs that they wanted to access.  For that reason, `dart:objc` should be optimized for performance over programmability.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/pull/2217 is the sketch.

**Comment by natebosch** [comment]
Since flutter experimented with this and decided not to land it I don't think we need to continue considering it for the Dart SDK.
