### ISSUE TITLE
no analyzer hint with unused private field

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25323]
Consider the following:

![image](https://cloud.githubusercontent.com/assets/1035299/12060385/98248914-af6e-11e5-9f98-a205b9b2327c.png)

I really like that the analyzer shows me the field is not used (anymore).

However, if I write it like this:

![image](https://cloud.githubusercontent.com/assets/1035299/12060387/b65f94aa-af6e-11e5-8efc-4e0db5c85190.png)

The analyser thinks the variable is used, while it is only initialised.

**Comment by srawlins** [comment]
I think this has been fixed:

```
$ cat 25323.dart
```

```dart
class A {
  var _a;
  var _b = 1;

  A() : _a = 2;

  void f() {
    _b = 2;
  }
}
```

```
$ xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer 25323.dart
Analyzing [25323.dart]...
[hint] The value of the field '_a' is not used (/Users/srawlins/code/dart-repo3/sdk/25323.dart, line 2, col 7)
[hint] The value of the field '_b' is not used (/Users/srawlins/code/dart-repo3/sdk/25323.dart, line 3, col 7)
2 hints found.

```

**Comment by kasperpeulen** [comment]
fixed

**Comment by kevmoo** [comment]
Reopening for top-level fields

**Comment by devoncarew** [comment]
Note sure that a feature request can hit a P1, but agree that it would be great to have.

/cc @bwilkerson @scheglov @MichaelRFairhurst

**Comment by kevmoo** [comment]
Sorry. This is such a useful way to know about unused imports, etc. Also
feels like a big oversight

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/13929

**Comment by kevmoo** [comment]
FIxed in https://github.com/dart-lang/sdk/commit/462542b734f40e7e3eb863c63be98569dbafc090
