### ISSUE TITLE
js interop works, but analyzer doesn't like it

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25321]
So I basically trying to write a interop for the `ga` function of google analytics.
The problem is that it is not only a function, but also exposes properties (`l` and `q`). 

The following code, actually runs, and sends pageview events to google analytics. The only way to make the analyzer happy is add a `call` method. However, if I do that, dart2js breaks.

So basically, this codes works fine, but I just want to silence the analyzer.

```
import 'package:js/js.dart';

@JS('ga')
external Ga get ga;

@JS('ga')
class Ga {
  external int get l;

  external set l(int l);

  external List get q;

  external set q(List q);
}

class Analytics {
  Analytics(String trackingNumber) {
    ga.l = new DateTime.now().millisecondsSinceEpoch;
    ga('create', trackingNumber, 'auto');
  }

  send(String event) {
    ga('send', event);
  }
}
```

![](https://slack-files.com/files-tmb/T04JD132G-F0HFAB048-a912d8f44f/pasted_image_at_2015_12_29_06_23_pm_360.png)

**Comment by jacob314** [comment]
I have a CL in progress that will fix this. Adding a call method to A js interop class isn't supposed to break dart2js. You will also want to make class Ga implement Function as is the convention for classes with a call method.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by jacob314** [comment]
Fixed by
https://github.com/dart-lang/sdk/commit/bbb0c3f7275295c79e639808f5777aedc6374f5a
