### ISSUE TITLE
Please merge revision 5363e5c into stable channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25334]
@whesse @mit-mit @kasperl

This commit fixes a customer facing issue where they can't extract a stack trace from an asynchornous error, and therefore they have a hard time debugging issues discovered in production. This is forcing them to use 1.12 and wait until 1.14 hits the stable channel (issue #25235 has more details).

Revisions to be merged:
5363e5c

The code changes and tests merged cleanly, only the status file lib.status had a conflict and need to be fixed after cherry-picking this commit.

**Comment by whesse** [comment]
Merged into Version 1.13.2
