### ISSUE TITLE
VM Crash in UnboxIntegerInstr::Canonicalize

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#25335]
xcodebuild/DebugX64/dart --optimization-counter-threshold=10 --package-root=xcodebuild/DebugX64/packages/ /sources/git-one/sdk/tests/standalone/bytedata_test.dart

./vm/intermediate_language.h:7788: error: expected: (from == kUnboxedMint) || (from == kUnboxedUint32) || (from == kUnboxedInt32)

from is kTagged
to is kUnboxedMint

**Comment by mraleph** [comment]
Fixed with c0e374d455009c8512a061e06884bb862819c3d0
