### ISSUE TITLE
Reconcile Future/Promise

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#25336]
For JS interop, it would be ideal if we could adapt Dart Futures to implement the Promise interface.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
and adapt JS Promises to act as Dart Futures.

This will also ease DOM interop as Promise becomes more common.

Ideally, Dart Future actually is a JS Promise, simply exposing different user-facing APIs (similar to Dart builtin List type and JS Array). But we could also try adapters, similar to Dart Iterable objects exposing a [Symbol.iterator]() method to JS, and Dart for-each consuming JS Iterables.

There is an existing Dart Dev compiler issue for this.
https://github.com/dart-lang/dev_compiler/issues/245

**Comment by sigmundch** [comment]
seems closely related to #24679 - is it a duplicate?

**Comment by jacob314** [comment]
Yeah the author of 24679 had the same idea. :)
