### ISSUE TITLE
non-dangling part file test failing on Windows bot (but passing on Mac and Linux)

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25332]
From http://build.chromium.org/p/client.dart/builders/pkg-win-debug-be/builds/2170/steps/annotated_steps/logs/stdio

FAILED: none-vm-checked debug_ia32 pkg/analyzer_cli/test/driver_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
PASS: Driver | options | custom processor
PASS: Driver | exit codes | fatal hints
PASS: Driver | exit codes | not fatal hints
PASS: Driver | exit codes | fatal errors
PASS: Driver | exit codes | not fatal warnings
PASS: Driver | exit codes | fatal warnings
PASS: Driver | exit codes | missing options file
PASS: Driver | exit codes | missing dart file
PASS: Driver | exit codes | part file
FAIL: Driver | exit codes | non-dangling part file
  Expected: <0>
    Actual: <3>

  package:unittest/src/simple_configuration.dart 128:34  SimpleConfiguration.onExpectFailure
  package:unittest/src/simple_configuration.dart 24:13   _ExpectFailureHandler.fail
  package:unittest/src/matcher/expect.dart 121:5         DefaultFailureHandler.failMatch
  package:unittest/src/matcher/expect.dart 95:20         expect
  pkg\analyzer_cli\test\driver_test.dart 120:9           main.<fn>.<fn>.<fn>
  package:unittest/src/internal_test_case.dart 120:37    InternalTestCase.run.<fn>
  dart:async/zone.dart 914                               _rootRunUnary
  dart:async/zone.dart 810                               _CustomZone.runUnary
  dart:async/future_impl.dart 551                        _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 637                        _Future._propagateToListeners
  dart:async/future_impl.dart 424                        _Future._completeWithValue
  dart:async/future_impl.dart 479                        _Future._asyncComplete.<fn>
  dart:async/zone.dart 907                               _rootRun
  dart:async/zone.dart 802                               _CustomZone.run
  dart:async/zone.dart 708                               _CustomZone.runGuarded
  dart:async/zone.dart 733                               _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                  _microtaskLoop
  dart:async/schedule_microtask.dart 50                  _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 394                 _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                 _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148              _RawReceivePortImpl._handleMessage
PASS: Driver | exit codes | extra part file
PASS: Driver | linter | lints in options | gets analysis options

**Comment by keertip** [comment]
closing as stale.
