### ISSUE TITLE
Outdated samples are broken

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25338]
There are two samples in the repo that have been broken since [pub dropped support for older barback versions](https://github.com/dart-lang/pub/commit/a1dd3484795b2bc221aaa8d007f3162251b3c08e). [`samples/third_party/dromaeo`](https://github.com/dart-lang/sdk/blob/master/samples/third_party/dromaeo/pubspec.yaml) depends directly on `barback` `^0.13.0` (outdated since April 2014), whereas [`samples/third_party/todomvc_performance`](https://github.com/dart-lang/sdk/blob/master/samples/third_party/todomvc_performance/pubspec.yaml) depends on `polymer` `^0.10.0` (outdated since June 2014).

**Comment by srawlins** [comment]
I think this belongs over here: https://github.com/dart-lang/www.dartlang.org/

**Comment by nex3** [comment]
The biggest problem with this is that these samples are breaking the test infrastructure for the SDK.

**Comment by kevmoo** [comment]
@nex3 We got these removed, right?

**Comment by nex3** [comment]
Yep!
