### ISSUE TITLE
Anonymous mixin application mirrors have no type arguments.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#25344]
I think a 'dart:mirrors' `ClassMirror` representing an anonymous mixin application should have type arguments in some cases, but it doesn't.

Consider the following code:

``` dart
import 'dart:mirrors';

class A<X> {}
class M<Y> {}
class C<X, Y> extends A<X> with M<Y> {}

class MM<X, Y> = A<X> with M<Y>;
class D<X, Y> extends MM<X, Y> {}

main() {
  print("Using class A<X> {}, class M<Y> {}, X == int, Y == String.");
  ClassMirror cMirror =
      reflectType(new C<int, String>().runtimeType).superclass;
  print("A<X> with M<Y> has ${cMirror.typeArguments.length} type arguments");
  ClassMirror dMirror =
      reflectType(new D<int, String>().runtimeType).superclass;
  print("A named version of A<X> with M<Y> has "
      "${dMirror.typeArguments.length} type arguments: "
      "${dMirror.typeArguments[0].reflectedType} and "
      "${dMirror.typeArguments[1].reflectedType}.");
}
```

When executed by the vm it prints the following:

```
Using class A<X> {}, class M<Y> {}, X == int, Y == String.
A<X> with M<Y> has 0 type arguments
A named version of A<X> with M<Y> has 2 type arguments: int and String.
```

This shows that the anonymous class which arises because `M<Y>` is mixin-applied to `A<X>` is considered to have zero type arguments by 'dart:mirrors' in the vm. Still, when we apply `C` to a list of type arguments as in `C<int, String>` then it must have that mixin application as its immediate superclass. Let us call it `A<int> with M<String>` even though that syntax is not supported in Dart as a denotation of the anonymous mixin application (for instance, you cannot use that as a type annotation). This means that the superclass `A<X> with M<Y>` must be generic.

In particular, two distinct instantiations of `C` (say, `C<int, String>` and `C<String, bool>`) must have distinct superclasses (such that they can disagree on the value of `X` and the value of `Y`, and they can support the correct semantics of `_ is X` expressions, etc.), and this is only possible if the superclass takes two type arguments, corresponding to the free occurrences of `X` and `Y`.

The problem is that the type arguments for this superclass are implicit, they can only be determined by a traversal of the mixin application expression itself, finding the set of free type variables (here: `X` and `Y`), and listing them, along with some relevant bounds, in a synthetic type parameter list.

There is no general nesting, so we know for sure that these free variables will be taken from the list of type variables declared for the enclosing class (here: `C`), and it is easy to see that the bounds should be exactly the same as the bounds given at the declaration site for those type variables (here: none, but in general they can be copied as text because there cannot be any scopes between the type argument list of `C` and the applications of those type parameters in its `extends` clause). The bounds cannot be tighter, because the type variables could have any of the values allowed by the bounds in the type parameter list for `C`, and they need not be more loose because static checking (whether or not it causes warnings) cannot have assumed more.

In summary, we can choose to let the type parameter list for the anonymous mixin application `A<X> with M<Y>` be a sublist of the type parameter list of the enclosing class `C` (containing all the type variables that are in use, which is all of them here).

This essentially means that we should consider `A<X> with M<Y>` to mean exactly the same thing as `MM<X, Y>` in the code snippet above.

Given that we can do this, and it creates obvious problems to attempt to claim that the anonymous mixin application does not have type parameters, I think the correct thing to do would be to follow that scheme.

(We could of course reorder the type parameters, e.g., sorting them alphabetically, but I don't see any choice which is more natural than copying the required sublist of the type parameter declarations of the enclosing class).

**Comment by lrhn** [comment]
@gbracha 
I think the reasoning is correct. For `class C<A, B> extends D<A> with E<B> { something; }`, the (singlular) superclass of C<A,B> is the mixin application `D<A> with E<B>`. We can't reasonably let each generic instantiation of C have a separate superclass.
The superclass mixin application has free type variables. If it is to be treated as a class, those type variables need to be bound, effectively requiring the mixin application class itself to have type parameters.

The specification doesn't treat type variables in its description of mixin application.
The simplest solution would be to pass all type parameters of C to the superclass (that way we won't have to consider which ones are actually used). Effectively, the superclass of C above becomes the class that could be written `class DwithE<A, B> = D<A> with E<B>;` (like all other mixin applications can be reduced to anonymous mixin application definitions using `class .. = ... with ...`).

**Comment by gbracha** [comment]
I disagree completely.  The class C has as its super class a non-generic class that is the result of applying the mixin of M<Y> to the class A<X>. So yes, each instantiation of C has a potentially distinct superclass.

**Comment by lrhn** [comment]
That's another perspective than the one I favor. 
In that case, there is no "class C" (semantically at least, there is a "class declaration" syntactically). Instead the declaration introduces a class-factory C that takes two type arguments (say `T1` and `T2`) to create a *class* `C<T1,T2>`. That class, `C<T1, T2>`, has a single superclass which is `D<T1> with E<T2>`. In that view, each (equivalence class of) `Type` object corresponds to a separate class (or dynamic), and `List<int>` and `List<bool>` are different *classes*.

More generally, ""generic" classes" are not actually classes, they are functions that map type parameters to classes. Classes are instantiations of generic class templates/functions defined by class declarations (trivially in the case of having zero type parameters).

Is this a correct interpretation?

**Comment by eernstg** [comment]
I've always been in favor of the same terminology (a "non-generic class" is a class, a "generic class" is a function from type arguments to classes, and a "type" is a class (which may be the result of applying such a function to some type arguments)). But that's a separate war. ;-)

I think the important thing to note here is that the phrase "the result of applying the mixin of `M<Y>` to the class `A<X>`" contains the free variables `X` and `Y`. In order to answer the question "What is the superclass of `C<S, T>`?" for any given `S` and `T`, we need to put `S` and `T` into the phrase with the free variables. That kind of operation is usually achieved using a function, which is exactly what a generic class is.

So the point of view where `A<X> with M<Y>` is considered to denote a generic class explains what is going on with the type arguments, whereas the claim that "the result of applying the mixin of `M<Y>` to the class `A<X>`" is a non-generic class leaves them unexplained.

**Comment by munificent** [comment]
Is there any language work to do for this, or is it just a mirror library thing? I'm going to speculatively assume the latter and remove area:language.

**Comment by eernstg** [comment]
Right, the change to dart:mirrors would be such that with the following program we would get the printout shown below:
``` dart
import 'dart:mirrors';

class A<X> {}
class M<Y> {}
class C<X, Y> extends A<X> with M<Y> {}

main() {
  ClassMirror cMirror =
      reflectType(new C<int, String>().runtimeType).superclass;
  print("A<X> with M<Y> has "
      "${cMirror.typeArguments.length} type arguments: "
      "${cMirror.typeArguments[0].reflectedType} and "
      "${cMirror.typeArguments[1].reflectedType}.");
}
```
Here is the desired printout:
```
A<X> with M<Y> has 2 type arguments: int and String.
```

**Comment by lrhn** [comment]
Is the spec actually saying this? 
That is, is it saying that `A<X> with M<Y>` is a generic type with two type parameters?

**Comment by eernstg** [comment]
Almost. ;-)

We have the following in `\subsection{Superclasses}`:

```
The superclass of a class $C$ that has a with clause \code{\WITH{} $M_1, \ldots, M_k$}
and an extends clause \code{\EXTENDS{} S}
is the application of mixin (\ref{mixins}) $M_k* \cdots * M_1$  to S
```
In `\subsection{Mixin Application}` we find this:
```
A  mixin application of the form \code{$S$ \WITH{} $M$;} defines a class $C$ with 
superclass $S$.
...
A  mixin application of the form  \code{$S$ \WITH{} $M_1, \ldots, M_k$;}
defines a class $C$ whose superclass is the application of
the mixin composition (\ref{mixinComposition}) $M_{k-1} * \ldots * M_1$ to $S$.
```
This means that we have the notion of a **composite mixin** which is the "product" of a list of mixins (most specific first), and such a composite mixin can be applied to a class. For instance, with `class C extends S with M1, M2 {}`, the superclass of `C` is `apply(S, M2 * M1)`. The rules from `\subsection{Mixin Application}` allow us to find all superclasses: The superclasses of `C` are `apply(S, M2 * M1)`, `apply(S, M1)`, and `S`, followed by the superclasses of `S`, if any.

In `\subsection{Mixin Composition}`, we can see that **mixin composition** is defined in terms of the effect of applying a composite mixin to a class (note that we consider `M2 * M1` where the spec considers `M1<..> * M2<..>`, so we have `M2` where the spec has `M1<...>` and `M1` where the spec has `M2<...>`):
```dart
// apply(S, M2 * M1) is equivalent to Id1, where:
class Id1 = Id2 with M2;
class Id2 = S with M1;
```
A more concise way to say the same thing is the following rewrite rule: `apply(S, M2 * M1) == apply(apply(S, M1), M2)`.

In `\subsection{Mixin Composition}` it is also stated that `Mixin composition is associative`, which fits in nicely with that equivalence (considered as a rewrite rule):
```
apply(S, (M1 * M2) * M3) ==
apply(apply(S, M3), M1 * M2) ==
apply(apply(apply(S, M3), M2), M1) ==
apply(apply(S, M2 * M3), M1) ==
apply(S, M1 * (M2 * M3))
```
In other words, we might as well use the notation `S with M1, M2` rather than `apply(S, M2 * M1)` to denote the application of `S` to the composite mixin `M2 * M1`, and we would then have the rewrite rule `S with M1, M2 == (S with M1) with M2`, which is just `S with M1 with M2` due to the associativity.

Now consider generic classes. A direct translation of the above example could give us something like the following: Assuming the declaration `class D<X> extends U<X> with N1<X>, N2<X> {}`, the superclasses of `D<X>` are `U<X> with N1<X>, N2<X>`, `U<X> with N1<X>`, and `U<X>`, followed by the superclasses of `U<X>`.

We cannot ignore the type arguments. In particular, we can see that there is no way to recover sufficient information about the flow of type variables if we consider a declaration like this one: `class E<X, Y> = U<Y, X> with N1<X>, N2<Y>`.

Hence, we need to understand expressions like `U<X> with N1<X>, N2<X>` as denotations of classes (or `apply(U<X>, N2<X> * N1<X>)` if you prefer that notation).

Given that `X` is a free variable in this expression, my claim is that this is a meaningless expression, unless we allow for passing an actual value of `X` to that expression, which would typically mean that it is a (type) argument. Something that accepts actual type arguments and thereby yields a class is (everywhere else) a generic class, so I argue that it is reasonable to consider a mixin application like `U<X> with N1<X>, N2<X>` (or `apply(U<X>, N2<X> * N1<X>)`) to be a generic class. The type argument list of that generic class must contain all free type variables in the expression (here: just `X`). These type arguments are always defined in a formal type parameter list of an enclosing class declaration (`class C<../*here!*/..> ..`) or named mixin application (`class C<../*here!*/> = ..`), so we will get both the names and the bounds by copying that type argument list.

This means that we understand anonymous mixin applications as follows:
```dart
class C extends S with M1, M2 {}
class D<X> extends U<X> with N1<X>, N2<X> {}

// .. desugars to this:

class _C$super = S with M1, M2;
class C extends _C$super {}

class _D$super<X> = U<X> with N1<X>, N2<X>;
class D<X> extends _D$super<X> {}
```
Here you can easily see that `_D$super` is a generic class, and you can see how its type parameter is used in the mixin application in its body.

The general rule in `\subsection{Mixin Composition}` clearly indicates that the application of a composite mixin to a class yields a generic class:
```dart
// General rule as specified in \subsection{Mixin Composition}:
// apply(S<V_1 ... V_k_S>, M1<T_1 ... T_k_M_1> * M2<U_1 ... U_k_M_2>)
// is equivalent to this declaration:
abstract class Id1<T_1 ... T_k_M_1, U_1 ... U_k_M_2, V_1 ... V_k_S> =
    Id2<U_1 ... U_k_M_2, V_1 ... V_k_S> with M1<T_1 ... T_k_M_1>;
// .. where `Id2` is given by this declaration:
abstract class Id2<U_1 ... U_k_M_2, V_1 ... V_k_S> =
    S<V_1 ... V_k_S> with M2<U_1 ... U_k_M_2>;
```
However, this rule won't work as stated. For example, this rule allows for the following:
```dart
// `List<List<int>> with M1, M2`:
abstract class Id1a<List<int>> = Id2a<List<int>> with M1;
abstract class Id2a<List<int>> = List<List<int>> with M2;
```
This is syntactically wrong, of course, which illustrates that we need to fix this rule. We need to take it seriously that mixin applications take specific type arguments (that may be _used_ in `T_i`, `U_i`, and `V_i`), and those type arguments are provided from the enclosing declaration's formal type parameter list, which is also the place where we can find some meaningful bounds.

**Comment by eernstg** [comment]
Note that #28104 has been closed because the language specification already specifies a mixin application as being a generic class when the applied mixin or the superclass is generic.
