### ISSUE TITLE
Add dartanalyzer --no-info

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25341]
It's cool that the analyzer reports TODOs as "info" notifications, but these can cause a lot of clutter, especially on the command line. It would be really nice to have a flag that could disable them, just like we have `--no-hints`.

**Comment by srawlins** [comment]
`--no-hints` currently does disable TODO infos. Are you saying there should be a `--no-info` flag that would allow hints, but disable infos like TODO?

**Comment by bwilkerson** [comment]
In another issue it was proposed that info messages be disabled by default with a flag to get them if you want to. This seems like a better solution to me.

**Comment by devoncarew** [comment]
We no longer show todos in the analyzer cli output.

**Comment by zoechi** [comment]
and also no way to opt in?
