### ISSUE TITLE
Analyzer doesn't check function expression invocation arguments

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25349]
For the following program, the analyzer gives a warning on the first invocation of `f`, but not on the second invocation of `(f)`.

dartanalyzer version 1.14.0-edge.dff4089ff21650d984f85e2a44f959e630406cf3

```dart
int f (int x) => x;
void main() {
  f("hello");
  (f)("hello");
}
```
cc @jmesserly @stereotype441 @bwilkerson

**Comment by jmesserly** [comment]
I think this happens because ElementResolver.visitFunctionExpressionInvocation only resolves when the Expression is a FunctionExpression. Could be fixed by getting the expression's staticType, and if it's a FunctionType, call _resolveArgumentsToParameters with the type's parameters.

**Comment by leafpetersen** [comment]
This is fixed in bleeding edge.
