### ISSUE TITLE
Missing ARM64 binaries in tools/testing/bin/linux and tools/sdks/linux

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25352]
tools/sdks/linux is used to build Observatory and currently the build tries to use the ia32 binary on arm64. Having it use the arm32 binary works but is kludgy (The toolchain on arm64 doesn't support arm32 the way that x64 supports ia32. In particular, ld and gdb don't work with arm32 binaries).

tools/testing/bin/linux is used for ./tools/test.py and currently tries to use a missing dart-arm64. Trying to use the (rather old) ARM32 binary results in crashes on ARM64.

**Comment by whesse** [comment]
An arm64 binary has been added to tools/sdks/linux, and the name-lookup function now returns it on arm64 machines.  Please check that this works on your hardware.  An upcoming changelist will switch test.py to use these executables, and removes tools/testing/bin/linux.
