### ISSUE TITLE
trying to extend a class with factory construction doesn't give analyzer warning

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25358]
I was trying to do the following:

```
import 'package:logging/logging.dart';

main(List<String> arguments) {
  final AppLogger log = new AppLogger(Level.ALL, 'my-app');
  log.fine('hello world!');
}

class AppLogger extends Logger {
  factory AppLogger(Level logLevel, String appName) {
    Logger.root.level = logLevel;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name} ${rec.message}');
    });
    return new Logger(appName);
  }
}
```

I get the following error message:

```

Unhandled exception:
type 'Logger' is not a subtype of type 'AppLogger' of 'function result'.
#0      AppLogger.AppLogger (file:///Users/kasper/Code/DartProjects/untitled9/bin/main.dart:19:16)
#1      main (file:///Users/kasper/Code/DartProjects/untitled9/bin/main.dart:9:29)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Process finished with exit code 255
```

After searching a bit, I believe this doesn't work because `Logger` is a factory constructor. Is this correct? I think it would be good to give an analyzer warning for this.

**Comment by lrhn** [comment]
The problem is that `AppLogger` is a *subtype* of `Logger`, not the other way around. 
The factory constructor of `AppLogger` must return an object which is an `AppLogger` (the factory constructor is like a static function with a return type of `AppLogger`).
What you do return is a `Logger` instance which is not an `AppLogger`, hence the checked mode error.

This should cause a static warning (static type of expression of return statement doesn't match function return type).

**Comment by kasperpeulen** [comment]
@lrhn but sometimes I am able to do this same thing:

```
main() {
  print (new A().value);
}

class A extends B {
  factory A() => new B('hello world');
}

class B {
  final String value;
  B(this.value);
}
```

Isn't that the same thing? A is a subtype of B, but I can return B.

**Comment by kasperpeulen** [comment]
oh hm.. it doesn't work in the vm, but it does work in dartpad

**Comment by kasperpeulen** [comment]
or more general, it works only compiled to javascript, it also doesn't work in dartium

**Comment by lrhn** [comment]
It works in production mode, not in checked mode.
The only thing preventing you from returning anything from a factory constructor is the (implicit) return type which is the same as the class it is a factory on. In production mode you can return any object, just as from a normal static function.
(That also means that you can always return null from a factory constructor.)

Both dart2js and the VM implements the runtime semantics correctly in both production and checked mode, the analyzer is missing a warning.

**Comment by kasperpeulen** [comment]
@lrhn but dartpad runs in checked mode I believe, see:

https://github.com/dart-lang/dart-services/pull/189

but also if I do `pub serve mode=debug` or `pub build mode=debug` it still works

**Comment by lrhn** [comment]
Indeed. Dartpad is not running in checked mode. It's running the analyzer first to print warnings, but you don't get a runtime error from code like `int x = "foo";`.

**Comment by kasperpeulen** [comment]
I see now thanks!

Just one last thing if you don't mind. Is it true that `pub serve --mode=debug` does by design not run in checked mode, and that you need to force checked mode in `pubspec.yaml`. We were wondering this on slack.

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.
