### ISSUE TITLE
analyzer error while typing in a package name

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25367]
Atom popped up a dialog with this stack trace while I was typing an (incorrect) package URL:

Error from the analysis server: Could not resolve URI (package:s) relative to source (/Users/skybrian/dart/work/exerciser/bin/type.dart) Invalid argument (packageUri): Package URIs must start with the package name followed by a '/': Instance of 'Uri'

#0      checkValidPackageUri (package:package_config/src/util.dart:72)
#1      PackagesBase.resolve (package:package_config/src/packages_impl.dart:37)
#2      SourceFactory._internalResolveUri (package:analyzer/src/generated/source.dart:824)
#3      SourceFactory.resolveUri (package:analyzer/src/generated/source.dart:741)
#4      ParseDartTask.resolveDirective (package:analyzer/src/task/dart.dart:3366)
#5      ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:3269)
#6      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#7      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#8      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#9      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#10     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#12     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#13     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#14     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)

It seems like this should be reported as an error in the code, without a stack trace.

$ dart --version
Dart VM version: 1.13.0 (Wed Nov 18 12:15:29 2015) on "macos_x64"

**Comment by bwilkerson** [comment]
Yes, that should produce an error, not an exception.

**Comment by skybrian** [comment]
This bug seems to be Mac-specific. (I wasn't able to reproduce it on Linux.)

**Comment by skybrian** [comment]
It only happens when a .packages file exists.
