### ISSUE TITLE
Dartium doesn't stop at a breakpoint unless the Chrome dev inspector is open

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25369]
If you set a breakpoint in a script running in Dartium or content_shell, the debugger won't actually pause at that breakpoint unless the Chrome dev inspector itself is open. This is true even if Observatory itself is open, so setting a breakpoint in Observatory and then continuing will run right through the breakpoint.

This is a particularly problem for users using content_shell with the test runner. The runner displays both the Observatory URL and the remote debugger URL, so users who only care about code and not HTML elements would naturally choose to just use Observatory on its own. It also makes testing debugging-related functionality very difficult, since we have to somehow open the dev inspector to make any breakpoints work.

**Comment by zoechi** [comment]
Interesting, in WebStorm (and DartEditor) the connection to the debugger is (was) disconnected as soon as the devtools are opened.

**Comment by terrylucas** [comment]
You could using the debugger statement to stop (that should work).

Please re-try with Dart 1.24.2 Stable (Dartium 50).
