### ISSUE TITLE
No analyser warning on incompatible assignment of a ternary condition result.

### ISSUE THREAD

**Issue by aabluedragon** [dart-lang/sdk#25366]
Dart VM version: 1.14.0-dev.6.0

Dart analyser does not raise an error about type incompatibility in the following case:
```java
int rand = new Random().nextInt(3);
int test = rand>0? "123" : 123;
```

**Comment by bwilkerson** [comment]
While a warning would be nice, this is actually working according to the specification. The static type of a conditional expression is the least upper bound of the static types of the "then" and "else" expressions. The least upper bound of String and int is Object. Object is assignable to int, hence there is no warning.

This is a result of Dart having adopted an unsound type system. Strong mode uses a less unsound type system that should disallow that assignment, so I believe that you can get the warning you want by enabling strong mode.

**Comment by leafpetersen** [comment]
Unfortunately, strong mode won't catch this right now, since we also allow implicit downcasts.  We could (and should) do better though.  Filed an issue here:

https://github.com/dart-lang/sdk/issues/25368
