### ISSUE TITLE
Assertion failure during inlining with --noopt

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25364]
runtime/vm/intermediate_language.cc:821: error: expected: other->env() != NULL

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --noopt --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /usr/local/google/home/rmacnak/dart1/sdk/tests/language/do_while_test.dart
Took 0:00:01.178000

Short reproduction command (experimental):
    python tools/test.py --noopt --exclude-suite pkg -t120 language/do_while_test

@fsc8000 @mraleph

**Comment by mraleph** [comment]
Fixed by 2306f29cc42590143a6b29048186f8a7e4a11e37
