### ISSUE TITLE
No warning when returning incorrect type

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25363]
Consider this code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: "Flutter Demo",
      routes: {'/': (RouteArguments args) => new FlutterDemo()}));
}

class FlutterDemoComponent extends StatefulComponent {
  @override
  State createState() => new FlutterDemo();
}

class FlutterDemo extends State {
  String message = "Hello, world!";

  Widget build(BuildContext context) {
    return new Scaffold(
        toolBar: new ToolBar(center: new Text("Flutter Demo")),
        body: new Material(child: new Center(child: new Text(message))),
        floatingActionButton: new FloatingActionButton(
            child: new Icon(icon: 'content/add'), onPressed: () {
          setState(() {
            message = "tapped!";
          });
        }));
  }
}
```

Expected: warning that FlutterDemo doesn't implement Widget, on line with `routes: {...`

Actual: no warning:

![screen shot 2016-01-06 at 1 08 52 pm](https://cloud.githubusercontent.com/assets/5479/12154828/a819a252-b476-11e5-8dc0-308be671e2d4.png)

Background:

```dart
class MaterialApp extends StatefulComponent {
  MaterialApp({
    Key key,
    this.title,
    this.theme,
    this.routes: const <String, RouteBuilder>{},
    this.onGenerateRoute,
    this.onLocaleChanged
  }) : super(key: key) {
    assert(routes != null);
    assert(routes.containsKey(Navigator.defaultRouteName) || onGenerateRoute != null);
  }

  final String title;
  final ThemeData theme;
  final Map<String, RouteBuilder> routes;

  ...
```

and 

```dart
typedef Widget RouteBuilder(RouteArguments args);
```

Thanks for taking a look!

**Comment by sethladd** [comment]
Workaround: add generics to my map.

`routes: <String, RouteBuilder>{'/': (RouteArguments args) => new FlutterDemo()}));`

which is kind of a mouthful, but it does then trigger the warning. Maybe analyzer could do some inferencing here? Or, maybe I want strong mode?

**Comment by bwilkerson** [comment]
Not sure I'd classify this as a defect; technically it's working the way the language is specified to work.

I don't think strong-mode does this kind of inference, either, but you could try enabling it to see.

**Comment by leafpetersen** [comment]
Strong mode should infer the type of the map literal there and warn you.  If it doesn't it's a bug, unless I'm missing something.  Strong mode rejects this example, which I think captures the essence of your program:

```dart
typedef int F(String x);

class A {
  A({this.routes : const {}});
  final Map<String, F> routes;
}

void main() {
  new A(routes: {"f" : (String x) => x});
}
```

**Comment by kevmoo** [comment]
Closing now – we think it works. @sethladd to verify with strong-mode
