### ISSUE TITLE
Assertion failure in constant propagator with --noopt

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25362]
runtime/vm/constant_propagator.cc:757: error: expected: ((rep == kUnboxedFloat32x4) && (value_cid == kFloat32x4Cid)) ||\
 ((rep == kUnboxedInt32x4) && (value_cid == kInt32x4Cid)) || ((rep == kUnboxedDouble) && (value_cid == kDoubleCid)) || \
((rep == kUnboxedMint) && (value_cid == kMintCid))

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --noopt --ignore-unrecognized-flags --package-root=out/Debug\
X64/packages/ /usr/local/google/home/rmacnak/dart-noopt/sdk/tests/co19/src/LibTest/typed_data/Float32List/fillRange_A01\
_t01.dart
Took 0:00:02.447000

Short reproduction command (experimental):
    python tools/test.py --noopt --exclude-suite pkg -t120 co19/LibTest/typed_data/Float32List/fillRange_A01_t01

@fsc8000 @mraleph

**Comment by mraleph** [comment]
Fixed by 122722f50b413f410fc05ed6822b8cb4ed42123b
