### ISSUE TITLE
Assembler::CheckCodePointer messes with the stack frame layout and breaks the profiler in debug builds

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25361]

**Comment by johnmccutchan** [comment]
@fsc8000

**Comment by fsc8000** [comment]
Which instances of CheckCodePointer do you mean?

**Comment by johnmccutchan** [comment]
X64, ARM, ARM64, and MIPS all push something onto the stack before the frame is setup. This subtly breaks the profiler.
