### ISSUE TITLE
VM service: Pause RPC doesn't seem to pause the isolate

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25379]
When I send a `pause` RPC to an observatory instance, I get back a success response. But if I then use `getIsolate` to retrieve the isolate's metadata, it reports its `pauseEvent` as `EventKind.Resume`.

This seems to be new as of 1.14.

**Comment by turnidge** [comment]
The success result means that the request to pause has been received.  If you want to be notified when the isolate is actually paused, you will need to listen for the PauseEvent on the Debug stream.

From service.md:

The _pause_ RPC is used to interrupt a running isolate. The RPC enqueues the interrupt request and potentially returns before the isolate is paused.

When the isolate is paused an event will be sent on the _Debug_ stream.
