### ISSUE TITLE
Analyzer cannot find property references until restarted

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#25371]
Using WebStorm 11.0.3 with Dart SDK 1.13.1 I'm seeing an issue where finding usages of a class property (a simple type annotated string getter) suddenly stops working and just reports 'no usages'. If I restart the analysis server using the 'dart analysis' console it works again.

Apologies for such a crapy bug report but I have not idea how to provide better info. The issue is sporadic. The indicator for an ongoing analysis ('analyzing dart sources') is not active when this happens.

**Comment by bwilkerson** [comment]
I'm assuming this is obsolete.
