### ISSUE TITLE
Per-Isolate Resource Allocation

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25370]
(Note: This is something that if I recall, has been discussed before, specifically by @kasperl)

In the production server code I designed, I use a custom built system to create pools of isolates of any arbitrary size that can listen for HTTP requests, process data tasks like decompressing files and encoding JSON, execute processes in a managed and safe way, and communicate with other parts of the server architecture. One thing that I have noticed while building this architecture is that I have some isolates that I want to limit how big their heap is. I want to be able to tell an isolate that it has an `X` MB heap to work with.

I already know of one potential issue: this is simply impossible (unless something happened to Web Workers recently that I didn't know about) to compile to JavaScript.

**Comment by floitschG** [comment]
@a-siva : I reassigned this issue to the VM. The API would be available through the isolate library (probably) but the work really is in the VM.

**Comment by mraleph** [comment]
Closing as stale. Please reopen if it still matters.
