### ISSUE TITLE
Make updating CHANGELOG for incremental releases part of workflow

### ISSUE THREAD

**Issue by davenotik** [dart-lang/sdk#25374]
WebStorm notifies me of a new SDK release, e.g. 1.13.2. I find the CHANGELOG for the SDK, but nothing there about 1.13.x. It's nice to know what's included before I update. It's happened before that the CHANGELOG wasn't updated, and so perhaps worth considering making it a part of the development workflow? Release new version -> update CHANGELOG, etc.

**Comment by mit-mit** [comment]
Thanks for the suggestion @davenotik, we have updated the changelog.md file with comments for 1.13.1 and 1.13.2, and have update our release process documentation to do this going forward before we push a new stable patch release.
