### ISSUE TITLE
reconcile typeParameters/typeFormals APIs in InterfaceType/FunctionType

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25378]
We believe the model in FunctionTypeImpl is in a decent place, now, but it's not consistent with InterfaceType. Probably the following changes would work:
- introduce typeFormals on InterfaceType
- rename substitute4 to instantiate, with similar semantics as FunctionType.instantiate
- uninstantiated typeParameters go into typeFormals
- typeParameters/typeArguments will be set for an instantiated InterfaceType

Probably a fairly straightforward change. ~~It is breaking, however, so we'll have to figure out how to coordinate it.~~ (edit: we can keep the old API as deprecated, so it's not breaking)

**Comment by leafpetersen** [comment]
Would this need to be breaking now, given that all of the relevant interfaces are marked as "do not extend, implement, or mix-in"?

**Comment by jmesserly** [comment]
@leafpetersen -- yeah, I was a bit confused in my intro... I was thinking in terms of renames, but we could leave the old name `@deprecated`. I'll edit that.

**Comment by jmesserly** [comment]
Ah, I remember now. The potential breaking part would be:
>  typeParameters/typeArguments will be set for an instantiated InterfaceType

In other words, do we still set typeParams/typeArgs for an uninstantiated type? For function types, we no longer do. I think that may have broken dartdoc (though I might be confusing that with an unrelated change to how function typed params were pretending to be typedefs).

But it'd be fine to get 90% of the way there, and get to the clean API, and do the typeArgs/typeParams break later.

**Comment by leafpetersen** [comment]
First (easy) part of this is done.  Added instantiate on ParameterizedType and deprecated substitute4.

https://codereview.chromium.org/1758913002

**Comment by jmesserly** [comment]
Probably not planning any big fixes here. Hopefully CFE can replace some of this.
