### ISSUE TITLE
extend js class with js class with the new interop

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#25375]
I think the code speaks itself:

``` dart
@JS('Parse')
library parse.user;

import 'package:js/js.dart';

import 'package:app/services/parse/object.dart';
import 'package:app/services/parse/promise.dart';

@JS()
class User extends ParseObject {
  @JS('signUp')
  external Promise _signUp(Map<String, Object> attrs, Map<String, Object> options);
  Promise signUp(Map<String, Object> attrs, Map<String, Object> options) {
    options.forEach((String key, Object value) {
      if (value is Function) {
        options[key] = allowInterop(value);
      }
    });

    return _signUp(attrs, options);
  }
}
```

``` dart
@JS('Parse')
library parse.object;

import 'package:js/js.dart';

@JS('Object')
class ParseObject {
  external bool set(String key, Object value, [Map options = null]);
}
```

``` dart
final parseUser.User user = new parseUser.User();
user.set('key', 'value');
```

Error message in chromium

```
ORIGINAL EXCEPTION: Class 'User' has no instance method 'set'.

NoSuchMethodError: method not found: 'set'
Receiver: Instance of 'User'
Arguments: [...]VM2044:1 (anonymous function)
```

Is it me ?

**Comment by a14n** [comment]
`@JS` is only use for the instantiation of the object. So the `set` method must be on the js instance of your user js variable (created by `new parseUser.User()` in dart - so `new Parse.User()` in js).

btw, if nothing has changed your code will not work:

- you cannot put `@JS` on class member ( see #24779 )  :-(
- you can only have `external` members on `@JS` annotated classes :-(

**Comment by tristancaron** [comment]
I made a wrap for the Parse JavaScript SDK (parse.com).  `Parse.User` extends `Parse.Object` in JS. So I was thinking that I could do the same in Dart.

And about your second point, it sounds weird, because, I've already did that on other cases, and it worked, as far I remember.

**Comment by jacob314** [comment]
a14n is correct.
We need to improve the error messages to make it clearer.
Unfortunately only external members are allowed on @JS annotated classes to keep the performance and code size where it needs to be.

**Comment by tristancaron** [comment]
I get it. And an annotated library must only have externals members also?

**Comment by a14n** [comment]
no, you can mix `@JS` annotated elements with other.

**Comment by matanlurey** [comment]
I think its safe to say since #26844 is closed we can also close this.
