### ISSUE TITLE
server doesn't report error if non-normalized file path is sent in setAnalysisRoots request

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25376]
In Atom, errors show up, but the outline view displays "outline not available". According to the instrumentation logs, the Atom plugin is subscribing to outline events but nothing is ever returned, nor is any error returned.

I also noticed that code completion doesn't work. (Control-space doesn't do anything.)

If I copy the project to a local drive, outline events show up as normal.

This is using:
Dart VM version: 1.13.0 (Wed Nov 18 12:27:07 2015) on "linux_x64"
Atom 1.3.2 on Ubuntu
dartlang 0.5.1

I expect that filesystem notifications don't work here (it's a FUSE-based filesystem using an unmodified Dart SDK), and perhaps sending outline events isn't feasible, but it seems like the analysis server should report some sort of error with a hint that switching filesystems may fix the problem.

**Comment by bwilkerson** [comment]
So, just to be clear, the following are all happening:
 - Atom is sending an analysis.setAnalysisRoots request that includes a directory containing the file,
 - Atom is sending an analysis.setSubscriptions request that requests an OUTLINE for the file,
 - server is sending an analysis.errors notification for the file, but
 - server is *not* sending an analysis.outline notification for the file.

Has the file been modified (has an analysis.updateContent request been sent for the file)?

It seems unlikely that it has to do with file system notifications (by which I assume you mean the notifications used by the watcher package). We only depend on those to detect changes after analysis has been done. If server was able to report errors then we could obviously read the content of the file and analyze it (at least partially). And that means that we should have been able to produce an outline.

Were there any server.error notifications sent to Atom?

**Comment by skybrian** [comment]
Yes that's correct; I see the OUTLINE subscription and the analysis.errors events but no analysis.outline events.

The only error I see is:
1452196475182:Res:{"error"::{"code"::"UNANALYZED_PRIORITY_FILES","message"::"Unanalyzed files cannot be a priority:: '[redacted filename]"},"id"::"7"}

There is an analysis.updateContent call that overlays the file before the errors are sent.

**Comment by bwilkerson** [comment]
Please double check: is the directory in the analysis.setAnalysisRoots request a directory that contains the file for which no outline information is being produced? If so, is the file being excluded in a .analysis_options file?

If the file ought to be getting analyzed, then the error response to the analysis.setSubscriptions request is the original problem. If the file is not in an analysis root or is excluded, then the server is performing according to the specification.

**Comment by skybrian** [comment]
This looks like a symlink issue. On the command line, I followed a symlink to get to the project directory and then opened atom using "atom .". The call to analysis.setAnalysisRoots has an absolute path that goes through the symlink.

So, it seems like a call to Directory.resolveSymbolicLinks on each directory in the setAnalysisRoots call would fix this. I'm not sure if this is the IDE's responsibility or analysis server's. If the analysis server requires symlinks to be resolved, we should probably document it and return an error if the path is not a canonical absolute path? Alternately it could just fix the directory.

**Comment by skybrian** [comment]
Verified this behavior on a Mac using just a symlink, so it's clear it has nothing to do with FUSE. Sorry about that!

To reproduce for a project named work/someproject:

ln -s work2 work
cd work2/someproject
atom .

**Comment by bwilkerson** [comment]
The server specification states that a FilePath is "The absolute, normalized path of a file.", so it is the client's responsibility to resolve symbolic links before sending the paths to server. Could you move this to the Atom issue tracker?

**Comment by skybrian** [comment]
Looks like the Atom plugin already has a bug for this:
https://github.com/dart-atom/dartlang/issues/344

And apparently that was in response to a bug I filed last September and then forgot about over the holidays. (Now I remember that I was skipping the symlink and opening the project in the canonical directory, as a workaround.)

I think there is still a bug on the analysis server side, since it doesn't report any error in response to a setAnalysisRoots request with invalid arguments.

**Comment by srawlins** [comment]
As we haven't sen activity on this in 7 years, I'm closing this as stale; if someone encounters this, feel free to ping, re-open, or open a new issue. I imagine symlink-related issues have been reported in separate issues.
