### ISSUE TITLE
Request for more info when import fails

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25384]
Hi,

Debugging an issue, and it might have been easier to debug if we printed out what file is trying to import a file that doesn't exist.

Consider this case:

```
import 'exists.dart';

main() { }
```

and then in exists.dart:

```
import 'doesnotexist.dart';
```

Running this, I get this error:

```
~/tmp $ dart broken.dart 
Unhandled exception:
Load Error for "file:///Users/sethladd/tmp/doesnotexist.dart": Error loading file:///Users/sethladd/tmp/doesnotexist.dart:
  FileSystemException: Cannot open file, path = '/Users/sethladd/tmp/doesnotexist.dart' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:147)
#1      _asyncLoadError (dart:_builtin:559)
#2      _handleLoaderReply (dart:_builtin:362)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

What do we think about telling the developer which file (and bonus, which line) is trying to do the import? Maybe an error message like (just a strawman, but notice how it tells the developer what file is trying to do the import):

"Import error, could not import file:///Users/sethladd/tmp/doesnotexist.dart from file://...../exists.dart"

Thanks for taking a look!

**Comment by zoechi** [comment]
dup of #21693?

**Comment by turnidge** [comment]
Ok, this seems like it would make the problem quite frustrating to debug.  I have a change in hand that will change the error message to something like this:

```
$ dart ~/dart-scratch/bad_import.dart
Unhandled exception:
Could not import "file:///Users/turnidge/dart-scratch/doesnotexist.dart" from "file:///Users/turnidge/dart-scratch/bad_import.dart": FileSystemException: Cannot open file, path = '/Users/turnidge/dart-scratch/doesnotexist.dart' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:162)
#1      _asyncLoadError (dart:_builtin:577)
#2      _handleLoaderReply (dart:_builtin:394)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Notice that this still has two problems:

1 - It would be nice to not print this as an exception at all.  Why bother with all of the clutter?
2 - It would be nice to print the line:col of the import.

**Comment by turnidge** [comment]
Well I've submitted 250773cb651beec1a61e126a6c0756aace9c19ca.

Not a perfect fix, but an improvement.

**Comment by zanderso** [comment]
It looks like the original request is satisfied, so I'll go ahead and close this. @turnidge if you still want to work on this more feel free to reopen.
