### ISSUE TITLE
What is the order of instance field declaration initializers

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#25381]
This is from Dart Programming Language Specification, 3rd Edition / June 2015:

> A fresh instance (10.6.1), i, of class R is allocated. For each instance variable f of i, if the variable declaration of f has an initializer expression ef , then ef is evaluated, with the type parameters (if any) of R bound to the actual type arguments V1,...,Vl, to an object of and f is bound to of. Otherwise f is bound to null.

What is the order of evaluation of "ef"?

I assume the order is superclasses first, order they appear in source code.

**Comment by zoechi** [comment]
There seems to be something missing at the end or is this similar to Fermat's last theorem where the solution is omitted ;-)

**Comment by peter-ahe-google** [comment]
Thank you, Günter. I've updated the original message.

**Comment by eernstg** [comment]
It continues like this: 'Observe that `this` is not in scope in ef . Hence, the initialization cannot depend
on other properties of the object being instantiated'. So maybe it doesn't matter? However, the reasoning in 10.6.1 about the order of evaluation of initializers during constructor execution would apply: 'We could observe the order by side effecting external routines called. So we need to specify the order.'

I also couldn't find any specifics on the ordering of field initializer expression evaluation, so maybe a phrase about that should be added. The one you mention seems to be consistent with other ordering constraints that I could find in the spec, except that textual ordering is mentioned frequently and ordering-by-inheritance seems to be specific to this case (the only other non-textual principle I could spot is "innermost-first" for stream subscription canceling).
