### ISSUE TITLE
CLI support for `_embedder.yaml`.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25380]
As noted in #25011, it looks like `_embedder.yaml` never made it into the analyzer CLI.  This issue tracks making it so.

**Comment by mit-mit** [comment]
@pq was this completed? If not, do we it in 1.14 and thus need to cherry pick it?

**Comment by pq** [comment]
@mit-mit : not yet.  Turns out we had some plumbing to do elsewhere so this will have to be cherry-picked.

FWIW, one preliminary bit is in flight here: https://codereview.chromium.org/1584663006/.

cc: @danrubel

**Comment by bwilkerson** [comment]
> ... so this will have to be cherry-picked.

Is there a reason why this needs to go into 1.14, or can it be part of 1.15?

**Comment by pq** [comment]
Flutter wants this bad. 

cc @sethladd

**Comment by bwilkerson** [comment]
Are we confident that we can get it in by 1.14 (with less than a week) and tested well enough to be sure that it's stable? 1.14 is shipping in 3 working days (counting today). That seems really tight to me.

**Comment by mit-mit** [comment]
Can Flutter use dev channel builds?

**Comment by sethladd** [comment]
Flutter encourages its developers to use stable channel. Don't try to rush this in just for us, but we do look forward to it landing for 1.15.

**Comment by mit-mit** [comment]
Moving to 1.15

**Comment by pq** [comment]
Should be good as of 3d3c9c5af46ffed91786672872006cba8581f533.
