### ISSUE TITLE
vm crashes (exit code 138) with complex generics when using parts

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/sdk#25389]
Similar to https://github.com/dart-lang/sdk/issues/25122 but only seems to take effect when code uses `part of` syntax

The following works

```
main() {}

abstract class ComponentState<S extends ComponentState> {}

abstract class AbstractListEditorState<D,
    S extends AbstractListEditorState<D, S>> extends ComponentState<S> {}

class IssueListEditorState
    extends AbstractListEditorState<String, IssueListEditorState>
    implements ComponentState<IssueListEditorState> {}

abstract class AbstractListEditor<D, S extends AbstractListEditorState<D, S>> {}
```

If you take this code and break it up as follows

```
library arghh;

part 'generics_new_parts_part.dart';

main() {}

abstract class AbstractListEditor<D, S extends AbstractListEditorState<D, S>> {}
```

and

```
part of arghh;

abstract class ComponentState<S extends ComponentState> {}

abstract class AbstractListEditorState<D,
    S extends AbstractListEditorState<D, S>> extends ComponentState<S> {}

class IssueListEditorState
    extends AbstractListEditorState<String, IssueListEditorState>
    implements ComponentState<IssueListEditorState> {}
```

it now crashes with the exit code 138

This seems to be have been introduced in 1.14.0-dev.5.0 and is still broken in dev.6.0.
I don't have any trouble in dev.4.0.

**Comment by fsc8000** [comment]
Could it be related to the fix of #25122 ?

**Comment by Andersmholmgren** [comment]
I assume that was not directed at me?

Either way it is hard to tell for me as this code would have failed due to #25122 anyway. i.e. I can't test it with an older vm as it would fail anyway

**Comment by crelier** [comment]
There is a cl out for review fixing this issue.
https://codereview.chromium.org/1580643004/

**Comment by crelier** [comment]
Fixed

**Comment by Andersmholmgren** [comment]
Cool. Thanks
