### ISSUE TITLE
Downwards inference doesn't push types into the `??` operator

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25387]
In the following example, we should infer the type of the list literal by pushing the context type down into the branches of the `??` operator.  

This causes some unnecessary strong mode warnings in the markdown package.

cc @devoncarew 

```dart
void main () {
  List<String> y = null ?? [];
}
```

**Comment by jmesserly** [comment]
possibly related to https://github.com/dart-lang/sdk/issues/24564 ... it doesn't look like we can type check `??=` at all

**Comment by jmesserly** [comment]
@leafpetersen -- I may go ahead and grab this unless you already started it :)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1575173005
