### ISSUE TITLE
Element.documentationComment doesn't work for enum values

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25385]
Given a source file like this:

    enum E {
      /**
       * Documentation comment
       */
      val;
    }

Calling `documentationComment` on the element for `val` produces `null`.

Discovered while trying to implement `documentationComment` support in summaries.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1689303002

**Comment by srawlins** [comment]
@scheglov this was fixed?

**Comment by scheglov** [comment]
I think so.
Closing it now.
