### ISSUE TITLE
add the ability to open the analysis server diagnostics port via an api call

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25395]
Related to https://github.com/dart-atom/dartlang/issues/682. It would be nice to be able to open the analysis server diagnostics port via an api call. This would allow the analysis server to choose an available port to bind to, and return the actual port that was used. Using a CLI flag to enable the port means that users need to re-start the analyzer to enable the port, losing context of their issue.

**Comment by devoncarew** [comment]
I'm think about implementing something like this. My sketch of the API would be something like:

```
      <request method="getServerPort">
        <p>
          Return the port of the diagnostic web server. If the server is not running
          this call will start the server.
        </p>
        <result>
          <field name="port">
            <ref>int</ref>
            <p>The diagnostic server port.</p>
          </field>
        </result>
      </request>
```

or as Dart:

```dart
int diagnostic.getServerPort();
```

This would:
- return the existing port if the server was running
- start the server if not; return the port bound to
- continue to respect the `--port` flag as a CLI arg (but likely move some bits of the implementation out of the `src/server/driver.dart` library.

@bwilkerson, @scheglov, thoughts? This would make it easier to view diagnostics for a running instance w/o having to adjust IntelliJ registry flags and restart the server.

**Comment by scheglov** [comment]
SGTM

**Comment by bwilkerson** [comment]
Given that only the client can send requests to the server, this would require a UI affordance in each client in order to open the port. I think we need the "add command-line flags" affordance for other reasons, so it isn't clear to me that this helps the UX.

**Comment by devoncarew** [comment]
> this would require a UI affordance in each client in order to open the port

Yup! I'm specifically thinking of something like a menu item on the gear icon of the Dart Analysis view:

<img width="122" alt="screen shot 2017-02-17 at 3 09 38 pm" src="https://cloud.githubusercontent.com/assets/1269969/23086683/5b0367b6-f523-11e6-9b0f-d82a779e6f7c.png">

or something similar - easy to get to but hidden behind one level of interaction.

**Comment by devoncarew** [comment]
(initial version out for review: https://codereview.chromium.org/2703033002/)
