### ISSUE TITLE
IntelliJ 'rename' refactor becomes easily confused

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25398]
I'm not sure if this is an IntelliJ or Analyzer bug.

IntelliJ version: IntelliJ IDEA 15.02, Build #IC-143.1184
Dart SDK version: 1.14.0-edge.f2270ed0d82dc032238477b516e91d90ae187cae

I tried the rename refactoring to make a private name public, had second thoughts after writing a bit of code, and tried to rename back.  IntelliJ refuses to rename, reports an error that the renamed field will be invisible in a library that doesn't actually use it.  I can't figure out a way to perform the rename.

I think the following steps will reproduce it.

1. Create a pair of Dart files defining a pair of different libraries.
2. Add a library private field to one of them.
3. Rename the field to a public name.
4. Now use the field in the other library.  Save.
5. Remove the use of the field in the second library.  Save.
6. Rename the field back to a private name.  Error: "Renamed field will be invisible in other_library_name'.

**Comment by kmillikin** [comment]
Ooops, this is invalid.  There was one lingering reference to the identifier in the second library that I did not catch --- the analyzer's behavior is OK.

**Comment by alexander-doroshko** [comment]
@kmillikin Just FYI: 'Save' action doesn't change anything in Dart development workflow in JetBrains IDEs. In fact Save is almost useless in IntelliJ at all. Code is saved automatically when needed (on frame deactivation, before running a Dart script, on project close, etc.). Code insight features do not care whether the files are saved or not.
