### ISSUE TITLE
Make Stream.firstWhere match Iterable.firstWhere in using the element type.

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25397]
I don't understand this line:
https://github.com/dart-lang/sdk/blob/ba675bddf2e60acfca1c12956c689c54de41547d/sdk/lib/async/stream.dart#L1065

Why is the return type `Future<dynamic>`. I would think it should return `Future<T>`?

**Comment by zoechi** [comment]
You can return any object as default value if no element fits the where check. Therefore you can't limit the return type.

**Comment by kasperpeulen** [comment]
Hm... But then I feel like the defaultValue should also be of type `T`. Why would you want to have another type?

This is also how it works for `Iterable`:
https://api.dartlang.org/135497/dart-core/Iterable/firstWhere.html

**Comment by zoechi** [comment]
`...firstWhere((KeyboardEvent e) => e.keycode == 65, default: 'not found')`
You can't create a `new KeyboardEvent()` for example, nor can you for any class with private constructors. How would you cope with this? `null` isn't allowed as well AFAIR.

**Comment by zoechi** [comment]
Yup, that's interested that `Iterable` uses `<E>`

**Comment by kasperpeulen** [comment]
@zoechi So say you would have this:

```
import 'dart:html';

TextAreaElement textarea = querySelector('textarea');
main() async {
  var firstDown =
      await textarea.onKeyUp.firstWhere((e) => e.keyCode == KeyCode.DOWN, default: 'not found');
  print(firstDown);
}
```

I think this would be just a future that never "completes". If nobody ever presses the down key. So I think the default will never be triggered. 

I think for streams that are finite so to say, it often is possible to provide a default value of that type:

```
main() async {
  int a  = await stream().firstWhere((i) => i == 2, defaultValue: () => 0);
  print(a);
}

Stream<int> stream() async* {
  for (int i = 0; i < 10; i++) {
    yield new Random().nextInt(10);
  }
}
```

And you can always do `null` that makes more sense to me then `'not found'`.

**Comment by zoechi** [comment]
I didn't investigate too closely but AFAIR `null` indicates an error in `Iterable.firstWhere(...)`. Seems `Stream` and `Iterable` differ here.
I leave it to @lrhn to explain ;-)

**Comment by floitschG** [comment]
Change happened in https://codereview.chromium.org/14246008/
For some reason I "[h]ad to change firstWhere and lastWhere, too."
In retrospect that was a mistake. I'm guessing that some tests started failing and the change made complete sense at that time...
Unfortunately I'm afraid that this would be a breaking change (with little benefit), and I'm inclined to leave it this way.

**Comment by lrhn** [comment]
Looks like we also missed changing the signature of `firstWhere`/`lastWhere` in sdk/lib/core/iterable.dart, even if it was changed in the implementations of `Iterable`. Those were changed back to match the interface again in https://codereview.chromium.org//794953002
So, `Iterable` got lucky and was changed back, `Stream` didn't.

**Comment by lrhn** [comment]
I agree that the difference between `Iterable` and `Stream` is annoying, but changing it now is a breaking change.

**Comment by zoechi** [comment]
You also don't plan to fix such issues in Dart 2.0?

**Comment by kasperpeulen** [comment]
> So, Iterable got lucky and was changed back, Stream didn't.

I would argue, better late than never.

> I agree that the difference between Iterable and Stream is annoying, but changing it now is a breaking change.

It is only breaking in checked mode right? I think this one of the most innocent breaking changes. Could it be considered for 2.0? :) @lrhn

**Comment by lrhn** [comment]
Yes, marking as 2.0.

**Comment by floitschG** [comment]
Yes. We are considering this change for Dart 2.0.

**Comment by kasperpeulen** [comment]
Any chance this will land in 2.0? @floitschG

**Comment by vsmenon** [comment]
@lrhn @leafpetersen - was this fixed with the recent lib changes?

**Comment by leafpetersen** [comment]
This is fixed.
