### ISSUE TITLE
generic method comments don't work for list/map literals

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25407]
`/*<T>*/[]` does not work, but `new List/*<T>*/()` does.

The workaround is easy: either the `new List` form or use downwards inference.

**Comment by leafpetersen** [comment]
Presumably `<dynamic /*=T*/>[]` is another workaround?

**Comment by jmesserly** [comment]
> Presumably <dynamic /*=T*/>[] is another workaround?

Yes.

Fix is here: https://codereview.chromium.org/1589663002
Just to make @munificent happy :tada: :wink:

**Comment by jmesserly** [comment]
Spoke too soon, that breaks something in test_genericMethod_functionExpressionInvocation_explicit. Boooooo :)

**Comment by munificent** [comment]
:balloon: :metal:
