### ISSUE TITLE
Effective Dart: AVOID generic public top-level member names

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25403]
Unless a library is designed to be imported with a prefix (e.g. `dart:math`, `package:path`) we should discourage the use of generic top-level member names.

For example, a top-level function `register` would not be descriptive enough, risks to shadow another symbol with the same name, or cause a conflict. However, it might be ok if your library is meant to be used with a prefix, e.g. `plugins.register(myPlugin)` is fine.

Can this guideline be added to Effective Dart?

**Comment by munificent** [comment]
Great idea, thanks!

**Comment by munificent** [comment]
Migrated to: https://github.com/dart-lang/www.dartlang.org/issues/1543
