### ISSUE TITLE
ListMixin map/extend generic method comments

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25408]
Right now they don't match the generic method comment signatures on Iterable, so this is an error:
````dart
class _FbList<E> extends Object with ListMixin<E> implements List<E>
```

Marked high-pri because this is easy to hit.

CC @leafpetersen, as this is related to SDK working with strong mode.

(this is sort of area-sdk, but only affects Analyzer strong mode. Not sure best way to label it.)

**Comment by leafpetersen** [comment]
I fixed a bunch of these in the DDC copy of the sdk here:  https://codereview.chromium.org/1554683002/

Lots of those SDK changes should get rolled into the main SDK.

**Comment by jmesserly** [comment]
I think @vsmenon is looking at this one.
