### ISSUE TITLE
Dartium 45 roll PageScriptDebugServer removed need to replace

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#25400]
Need a way to access PageScriptDebugServer::shared().isPaused() (PageScriptDebugServer was eliminated see CL https://codereview.chromium.org/999763002)

Also noticed, comment V8 used to have a PageScriptDebugServer which we mirrored.
Now they have a MainThreadDebugger instead...

See isAnyScriptPaused() in DartScriptDebugServer.cpp, function needs to call PageScriptDebugServer::shared().isPaused() to be able to do what use to be done:

     return isPaused() || PageScriptDebugServer::shared().isPaused();

**Comment by jacob314** [comment]
It was still there... Just renamed to V8ScriptDebugServer
