### ISSUE TITLE
Inline refactor isn't always correct and the output can be cleaned up

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25404]
When it works it's awesome, but I've noticed that the inline refactor for a method doesn't always work.  In `pkg/compiler/lib/src/cps_ir/cps_ir_builder.dart` in the SDK, search for method buildInvokeStatic, choose Refactor -> Inline... -> Inline all references and remove the method.

There is one call site that looked like:

```dart
  ir.Primitive exception = thenBuilder.buildInvokeStatic(
      error,
      new Selector.fromElement(error),
      <ir.Primitive>[],
      sourceInformation);
```

and now looks like:

```dart
  assert(!error.isLocal);
  assert(!error.isInstanceMember);
  assert(thenBuilder.isOpen);
  ir.Primitive exception = addPrimitive(
new ir.InvokeStatic(error, new Selector.fromElement(error), <ir.Primitive>[], sourceInformation));
```

Specifically the receiver `thenBuilder` has been lost from the call to `addPrimitive` in the inlined body.  (Note that it was not lost from the call to `isOpen` in the assert).

2. It might be nice to automatically format the output in case there are a lot of call sites.  In this case, there is a too-long line, and offside indentation of a continued line.

3. There is an unwanted blank line left at the site of the original method.  This is the whitespace that followed the method.  It seems nicer to eliminate all the blank lines up to the next member (but there's only one definition site so it's not terrible to have to clean it up by hand).

**Comment by scheglov** [comment]
0. [This CL](https://codereview.chromium.org/1629533003) should fix the problem with implicit `this` references.

1. Formatting is out of scope of refactorings. You will need to format source independently.

2. I will look how to remove empty lines during inlining.

**Comment by scheglov** [comment]
[CL](https://codereview.chromium.org/1628623002) for removing leading empty lines before delete-inlined methods.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/fe7a48d6c7a24a099505a2f216b02b293235d709
