### ISSUE TITLE
Type-checking of JS class interferes with subsequent type-checks 

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#25419]
A type-check of a JS class declared using the new `package:js` interop interferes with subsequent type-checks in the dart2js-compiled code.

This issue is reproducible on reproducible on Dart `1.13.1` as well as on and Dart `1.14.0-dev.6.0`.

### Test case 
(semi-roundabout to prevent tree-shaking/optimization that prevents this error from occurring)
```dart
import 'dart:math';

import 'package:js/js.dart';

@JS()
@anonymous
class AnonymousJsObject {}

getUnoptimizableString() {
  bool dynamicValueThatWillAlwaysBeTrue = new Random().nextInt(1) < 2;
  print('Should be true: ${dynamicValueThatWillAlwaysBeTrue}');
  return dynamicValueThatWillAlwaysBeTrue ? 'String' : new Object();
}

void main() {
  print('Using AnonymousJsObject so it doesn\'t get tree-shaken... ${new AnonymousJsObject().runtimeType}');

  var string = getUnoptimizableString();

  // Correctly prints 'false' in Dartium and dart2js.
  print('print(string is! String && string is AnonymousJsObject); ${string is! String && string is AnonymousJsObject}');

  // Correctly prints 'false' in Dartium.
  // Incorrectly prints 'true' in dart2js.
  print('print(string is AnonymousJsObject && string is! String); ${string is AnonymousJsObject && string is! String}');
}
```
 The dart2js output seems to strip off the String type-check if and only if it follows the `is AnonymousJsObject` check:
```js
      P.print("print(string is! String && string is AnonymousJsObject); " + (typeof string !== "string" && !!J.getInterceptor(string).$isAnonymousJsObject));
      P.print("print(string is AnonymousJsObject && string is! String); " + (!!J.getInterceptor(string).$isAnonymousJsObject && true));
```

**Comment by jacob314** [comment]
We shouldn't allow any type checks for anonymous js types. Type checking one of those types should really be a compile error.

**Comment by greglittlefield-wf** [comment]
I agree that telling between those JS types probably shouldn't be allowed. The results are unintuitive, given other `is`-operator behavior.

There should still be a way to detect whether something is an anonymous JS type, though.

The real desired behavior I'm going for is being able to differentiate JS types from non-JS types and apply handling accordingly.

**Comment by greglittlefield-wf** [comment]
For example, what I have now:
```dart
@JS()
@anonymous
class ReactElementStore {
  external bool get validated;
  external set validated(bool value);
}

@JS()
@anonymous
class ReactElement {
  external ReactElementStore get _store;
  external dynamic get type;

  external String get key;
  external dynamic get ref;
  external InteropProps get props;
}

...
void validateChildren(List children) {
  children.forEach((dynamic child) {
    // Keep `child is ReactElement` check at the end to work around dart2js bug: https://github.com/dart-lang/sdk/issues/25419
    if (child != null && child is! String && child is! bool && child is! num && child is ReactElement) {
      // "Primitive" types and ReactElements should be the only thing that get in here....
      // ReactElement type-checking returns false positives, so we need to `is!` all of them.
      child._store?.validated = true;
    }
  });
}
```
(I realize that still probably isn't doing what I expected due to the nature of the JS type type-check.)


What I really want to do:
```dart
void validateChildren(List children) {
  children.forEach((dynamic child) {
    if (isInstanceOfJsType(child)) {
      (child as ReactElement)._store?.validated = true;
    }
  });
}
```

Perhaps this should be a separate issue?

**Comment by jacob314** [comment]
Correct. Please file a separate bug to support an isInstanceOfJsType(child,
JsType) method.
For that case your JS type will need to not have the @anonymous annotation.
That annotation indicates there is no explicit JS prototype associated with
the class so it would be impossible to use JS instanceof.

**Comment by greglittlefield-wf** [comment]
What about the case for `@anonymous` JS types? Would it be possible to tell them apart from native Dart objects? That's what I'm really looking for.

**Comment by jacob314** [comment]
Suppose you have a JavaScript Array that has a couple properties added to
it so that it is compatible with the signature of your @anonymous JS type.
This is a reasonable use of @anonymous for libraries such as d3. However,
this array also needs to be treated as a regular Dart List. Do you want to
distinguish this object from "native" Dart objects? Similarly, DOM objects
in the future will be able to be considered both native Dart objects and JS
interop objects.

**Comment by greglittlefield-wf** [comment]
Okay, that makes sense. The more we talk through this, the more I understand what the real problem is; thanks for your patience.

So my approach to being able to distinguish "native" Dart vs anonymous JS objects just fundamentally isn't a good idea.

It looks like the ___real___ issue I was having when I applied that initial workaround is that type-checking the `@anonymous` type I've declared worked fine in the VM for any type, but doesn't work in dart2js for JS primitives (numbers, strings, booleans).

---

Take, for example, the difference in the output of the following code in the VM and in dart2js:

```dart
import 'dart:math';

import 'package:js/js.dart';

@JS()
@anonymous
class AnonymousJsObject {
  external get foo;

  external factory AnonymousJsObject();
}

getUnoptimizableValue(value) {
  bool dynamicValueThatWillAlwaysBeTrue = new Random().nextInt(1) < 2;
  print('Should be true: ${dynamicValueThatWillAlwaysBeTrue}');
  return dynamicValueThatWillAlwaysBeTrue ? value : new Object();
}

void anonymousTest(description, dynamic originalValue) {
  var value = getUnoptimizableValue(originalValue);

  try {
    if (value is AnonymousJsObject) {
      print('$description: `AnonymousJsObject.foo` value: ${value.foo}');
    } else {
      print('$description: Not an AnonymousJsObject');
    }
  } catch (e) {
    print('$description: Error reading `AnonymousJsObject.foo`: $e');
  }
}

void main() {
  print('Using AnonymousJsObject so it doesn\'t get tree-shaken... ${new AnonymousJsObject().runtimeType}');

  anonymousTest('AnonymousJsObject', new AnonymousJsObject());
  anonymousTest('Dart Object', new Object());
  anonymousTest('String', 'a string');
  anonymousTest('int', 2);
  anonymousTest('bool', true);
}
```

##### Output on Dart VM
```
AnonymousJsObject: `AnonymousJsObject.foo` value: null
Dart Object: Not an AnonymousJsObject
String: Not an AnonymousJsObject
int: Not an AnonymousJsObject
bool: Not an AnonymousJsObject
```

##### Output on dart2js
```
AnonymousJsObject: `AnonymousJsObject.foo` value: null
Dart Object: Not an AnonymousJsObject
String: Error reading `AnonymousJsObject.foo`: NoSuchMethodError: method not found: 'get$foo' (J.getInterceptor$x(...).get$foo is not a function)
int: Error reading `AnonymousJsObject.foo`: NoSuchMethodError: method not found: 'get$foo' (J.getInterceptor$x(...).get$foo is not a function)
bool: Error reading `AnonymousJsObject.foo`: NoSuchMethodError: method not found: 'get$foo' (J.getInterceptor$x(...).get$foo is not a function)
```

**Comment by jacob314** [comment]
Happy to talk through any of these edge cases with you. I've found the
discussion helpful as well.
Some notes: the Dart Dev Compiler will be able to provide 100% consistent
JS interop behavior with dart2js but dartium never will because
fundamentally Dartium has two separate VMs while dart2js and Dart Dev
Compiler only have a single VM storing all objects. An example of another
challenging to handle with full fidelity edge cases are undefined vs null.
Generally the design for JS interop is to make the design decisions that
will lead to the best world with Dart2JS and Dart Dev Compiler at the cost
that some edge cases in Dartium may be inconsistent with Dart2Js when it
comes to JS Interop.

**Comment by jacob314** [comment]
Johnni I believe you were looking into making Dart2JS reach the correct conclusions on type checks on JSInterop objects.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/2307883002/
