### ISSUE TITLE
Request: Quick Fix for "add missing @override"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25416]
Flutter would like to add @override to our code. We'd love tool support. Ideally, something like "automatic addition of @override when overriding a method" as a quick fix or quick add.

Thanks!

**Comment by sethladd** [comment]
Prompted by https://github.com/flutter/flutter/pull/1207

**Comment by pq** [comment]
Landed in https://github.com/dart-lang/sdk/commit/549a7a4d00c73a918439cdcb3601001e1955a581.  Will take a bit to percolate to stable but in the meantime, a teaser:

![screen shot 2016-02-26 at 2 39 53 pm](https://cloud.githubusercontent.com/assets/67586/13367368/eea894c4-dc96-11e5-8e4e-18a0f497b5c3.png)
:question: 

![screen shot 2016-02-26 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/67586/13367367/eea518d0-dc96-11e5-9bee-cebf0366ff17.png)
:eyes: 

![screen shot 2016-02-26 at 2 40 12 pm](https://cloud.githubusercontent.com/assets/67586/13367366/eea47b8c-dc96-11e5-802f-f1e2ea620675.png)

:dancers:
