### ISSUE TITLE
dartanalyzer and @override docs don't match when overriding fields

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#25415]
The [docs](https://api.dartlang.org/1.12.1/dart-core/override.html) say

"The annotation `@override` marks an instance member as overriding a
superclass member with the same name.

The annotation applies to instance methods, getters and setters, and to
**instance fields**, where it means that **the implicit getter and setter of the
field is marked as overriding**, but the field itself is not."

let's see...

``` dart
// foo.dart
class A {
  @override
  int x;   // <-- dartanalyzer should warn, but it doesn't.

  @override
  int get y => 1;  //  <-- dartanalyzer correctly warns for this.
}
```

So apparently, despite what the docs say, the `@override` on `x` is not equivalent `@override` on the implicit getter and setter.  I'm guessing that this is a bug in dartanalyzer and not a doc bug.

Also, just curious, what does the phrase "but the field itself is not" mean?  How is the contract different due to the presence of this phrase?

**Comment by lrhn** [comment]
If you have a field named `x` in a class, and adds a field named `x` in a subclass, you now have two independent fields which can have different values. One does not override the other (in the sense that it replaces the other), the two fields happily coexist on the same object.
The subclass getter and setter will override the superclass ones, and you can only access the subclass ones - unless you are internally using `super.x` somewhere to overrule the virtual dispatch.

I distinguish the actual field (part of object state) from the implicit getter/setter (part of the interface), even if both are introduced by the same field declaration.

**Comment by trinarytree** [comment]
Thanks.  That answers my last question.

What about the previous part?  The getter and setter of `x` in `A` falsely claim to override the getter and setter of `x` in `Object` (which has no `x` getter and setter).  The **bolded** parts of the docs, together with the observed behavior on `y`, seem to imply that dartanalyzer should output a warning for the `x` declaration.

**Comment by lrhn** [comment]
For the first part I agree that it's an analyzer bug. I've marked this issue as area-analyzer type-defect, so it's up to the analyzer developers now :)

**Comment by srawlins** [comment]
It looks like this was fixed at some point, perhaps with the introduction of the "OVERRIDE_ON_NON_OVERRIDING_FIELD". Not sure when. But with Dart 2.0.0-dev.6.0, I get the following hints:

```
Analyzing 25415.dart...
  hint • Field doesn't override an inherited getter or setter at 25415.dart:3:7 • override_on_non_overriding_field
  hint • Getter doesn't override an inherited getter at 25415.dart:6:11 • override_on_non_overriding_getter
2 hints found.
```
