### ISSUE TITLE
Request: optional Hint when code is missing @override

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25417]
Hi,

We'd love a way to opt-in for a Hint that says "you're missing an @override here: ..."

Then, we can add it to our _embedder.yaml and enforce that the flutter SDK has all the @overrides in all the right places.

Thanks!

**Comment by sethladd** [comment]
Prompted by https://github.com/flutter/flutter/pull/1207

**Comment by kevmoo** [comment]
Dupe of https://github.com/dart-lang/sdk/issues/23815
