### ISSUE TITLE
Assertion in Class::set_super_type

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#25426]
From https://build.chromium.org/p/client.dart/builders/vm-win32-debug-be/builds/7873/steps/checked_tests/logs/stdio :

FAILED: none-vm-checked debug_ia32 co19/Language/Mixins/Mixin_Application/wrong_type_t02
Expected: Crash 
Actual: Timeout
CommandOutput[vm]:

stderr:
vm\object.cc:2497: error: expected: value.IsNull() || (value.IsType() && !value.IsDynamicType()) || value.IsMixinAppType()

Command[vm]: set DART_CONFIGURATION=DebugIA32 & build\DebugIA32\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --package-root=build/DebugIA32/packages/ E:\b\build\slave\vm-win32-debug-be\build\sdk\tests\co19\src\Language\Mixins\Mixin_Application\wrong_type_t02.dart
Took 0:02:00.064000

Short reproduction command (experimental):
    python tools/test.py -aia32 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 co19/Language/Mixins/Mixin_Application/wrong_type_t02

**Comment by crelier** [comment]
Fixed in  https://codereview.chromium.org/1588723002
