### ISSUE TITLE
VM: Crash in shutdown on ARM64

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25424]
./dart hello.dart
Hello, world!
*** Error in `./dart': munmap_chunk(): invalid pointer: 0x0000000000cecb00 ***
Aborted

./dart --shutdown=false hello.dart 
Hello, world!

gdb --args ./dart hello.dart
...
Program received signal SIGABRT, Aborted.
0x0000007fb7c949b8 in raise () from /lib/aarch64-linux-gnu/libc.so.6
(gdb) bt
#0  0x0000007fb7c949b8 in raise () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000007fb7c95cc0 in abort () from /lib/aarch64-linux-gnu/libc.so.6
#2  0x0000007fb7cd0654 in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#3  0x0000007ffffff378 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by rmacnak-google** [comment]
@zanderso

**Comment by zanderso** [comment]
Does this happen reliably? Is there any change of getting a stack trace from a Debug build with symbols?

**Comment by rmacnak-google** [comment]
2ebe6f459ee8fcb6c2f9a814fc348df4719166f3
