### ISSUE TITLE
dart2js cps: Generate do-while for end-tested loops

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#25420]
It is not common, but there are some loops that would be more compact if expressed as do-while:

``` js
          while (true) {
            _contents += H.S(iterator._collection$_current);
            if (!iterator.moveNext$0())
              break;
          }
-->
          do {
            _contents += H.S(iterator._collection$_current);
          } while (iterator.moveNext$0());
```

**Comment by lrhn** [comment]
If the loop contains a `continue`, there is a difference between the two loops. The former will skip the next test and restart the body and the latter will only skip to the test.
(The compiler should be able to recognize that so it shouldn't be a problem, just worth noting that the two loops are not completely equivalent in all cases).

**Comment by rakudrama** [comment]
Obsolete
