### ISSUE TITLE
VM: Assertion failure in CSE

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25422]
runtime/vm/intermediate_language.cc:348: error: expected: other_op != NULL

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --noopt --optimization-counter-threshold=10 --no-use-osr --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /usr/local/google/home/rmacnak/dart1/sdk/tests/language/vm/if_conversion_vm_test.dart
Took 0:00:01.440000

Short reproduction command (experimental):
    python tools/test.py --noopt -t120 language/vm/if_conversion_vm_test

@mraleph

**Comment by iposva-google** [comment]
@mraleph @fsc8000

**Comment by mraleph** [comment]
Fixed by a3e42b6f7b114e6600e0687872536a6be4caebf6
