### ISSUE TITLE
pub upgrade, pub build fails with transformers on latest 1.14 dev build (tracking bug)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25423]
Tracking bug for https://github.com/dart-lang/pub/issues/1379

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/pub#1379

**Comment by mit-mit** [comment]
Looks like dart-lang/pub#1379 was closed, can we close this also?

**Comment by kevmoo** [comment]
Covered by these separate 1.14 issues

Isolate.spawn is broken in snapshots when run near a foreign .packages file dart-lang/sdk#25428
 Open
Isolate.spawn is broken in snapshots when the original .packages file is missing dart-lang/sdk#25429
 Open
Isolate.spawn is broken in snapshots when the original Dart file is missing dart-lang/sdk#25430
