### ISSUE TITLE
cpsir: bottom-up inlining

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25431]
- Reduced inlining on must-throw paths.
- Reduced inlining of methods containing try - performance hazard
- Reduced inlining into methods containing try - performance hazard
- Reduced inlining of lazy static initializers - single-run code
- Split inlining: (1) leave functions “delimited”, later (2) integrate the function

(feel free to split this in individual bugs if you prefer)

**Comment by rakudrama** [comment]
Obsolete
