### ISSUE TITLE
Tests for Map assume LinkedHashMap

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/sdk#25463]
The tests for the Map interface are not consistent with the contract of the interface.

F.e. here: https://github.com/dart-lang/sdk/blob/master/tests/corelib/map_values_test.dart#L20

`Maps.values` makes no promise about the order in which the values appear in the `Iterable`. Also, the return value of `Map.values` is allowed to be a `List`.

There are several more of this kind of issues with the tests for Map.

**Comment by kevmoo** [comment]
But...the map literal in Dart (which aligns with the implementation returned by `new Map` does guarantee ordering – so things like JSON literals round-trip without changes.
