### ISSUE TITLE
Issue with program tracing when removing a breakpoint during debugging.

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#25465]
**Summary:**
Removing a breakpoint during debugging makes the 'step-over' command not stop at the corresponding program location.

**What steps will reproduce the problem?**
1) Open webstorm and create a new command-line-application
2) Replace the contents of main.dart with the following:
```
main(List<String> args) {
  var foo;
  foo = 42;
  print(foo);
}
```
3) Place at breakpoint at line 2 and 3 ('var foo;' and 'foo = 42;')
4) Execute the 'debug' command
5) When the program stops at line 2 remove the breakpoint at line 3
6) Execute the 'step-over' command
*Expected:*
The program pauses at line 3

*Actual:*
The program pauses at line 4

**What version of the product are you using?**
Dart-SDK 1.14-dev.7.0
WebStorm 11.0.3

**Please provide any additional information below.**
The issue has been reproduced on both Mac and Windows.

**Comment by mit-mit** [comment]
This also fails with WebStorm 11.0.3 and Dart 1.13.

**Comment by mit-mit** [comment]
Same with WebStorm 12 EAP and Dart 1.14.dev.7.0

**Comment by mit-mit** [comment]
@clayberg is this likely a WebStorm issue or Dart issue?

**Comment by alexander-doroshko** [comment]
Trying this debugging scenario in Observatory will help to detect whether this is IDE or Dart debugger issue.

**Comment by alexander-doroshko** [comment]
So, I'm getting the same in Observatory, without IDE at all. Though it doesn't seem to be a major issue to me.
![image](https://cloud.githubusercontent.com/assets/4499789/12322630/5d4a1d1e-bac6-11e5-9070-c5350e755cc1.png)

**Comment by mit-mit** [comment]
Yes, good point. Looks like this is on the Dart side.

**Comment by mit-mit** [comment]
Given this is not a regression in 1.14 I think we can take our time and do a solid fix for 1.15

**Comment by johnmccutchan** [comment]
@turnidge @mhausner

**Comment by iposva-google** [comment]
Todd, please work with Matthias to figure out whether this problem is in the protocol or the internal setting of breakpoints. Thanks!

**Comment by turnidge** [comment]
I investigated this a bit and I wanted to record what I found so I don't lose state.  In debugger.cc, there is code that skips a single stepping breakpoint if there is already a breakpoint active at that program point:

```
  // Don't pause for a single step if there is a breakpoint set                  
  // at this location.                                                           
  if (HasActiveBreakpoint(frame->pc())) {
    return Error::null();
  }
```

For some reason, even after deleting the user's breakpoint, there is still an active code breakpoint at that part of the program.

**Comment by turnidge** [comment]
There was a change a while back which broke the removal of breakpoints.  This caused old breakpoints to leave... ghosts... in the code which caused single-stepping to skip them.  I have a change pending which restores the removal of breakpoints.  This uncovered another problem: if you remove a breakpoint while you are at it and then single step, you would stutter-step there, hitting the breakpoint twice, once for the breakpoint and once for the stepping.

I have written a test case to cover both of these failures.

**Comment by turnidge** [comment]
Actually, it's more complicated than this... I've found more failures... still working on it.
