### ISSUE TITLE
Please merge WebSocket patches into dev channel

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#25464]
@whesse @mit-mit @kasperl
This resolved the issues with websocket compression revealed by the Authbahn test suite. All Autobahn tests related to Websocket compression now pass for both server and client.

Revision to be merged:
a72ddf3a9d4eaa023e966cb39b52c4d78bb2186c
82aeb1997ed6f9d84c117fb3f1636b5966ec2f62
9240052ebb59111bdcb58ed06b4a878347b8932f

This merges cleanly.

**Comment by whesse** [comment]
Merged in 1.14.0-dev.7.1
