### ISSUE TITLE
Observatory rewrites "foo is! Bar" as "foo is !Bar" (different semantics)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25476]
When you look at code in Observatory, "foo is! Bar" becomes "foo is !Bar". This causes confusion since those expressions mean wildly different things.

**Comment by iposva-google** [comment]
Where do you observe a difference between "foo is !Bar" and "foo is! Bar"? As far as I can tell they are equivalent.: https://dartpad.dartlang.org/f34eb832322238145a1c

**Comment by lrhn** [comment]
They are equivalent, and also equivalent to `foo is ! Bar`. It's just whitespace. 

The `is!` "operator" is actually the `is` token followed by the `!` token, and it is in a syntax production which allows whitespace between tokens.

The `foo is! Bar` style has won the popularity contest now and been enshrined in the style guide, but in the earlier times, both were being used by different people, each preferring their own style.

(That said, the observatory may want to change the output to what the readers expect, to avoid confusion).

**Comment by iposva-google** [comment]
Re: "what the readers expect" really depends on the reader. Some do think of the production as "a isnot Bar" while others prefer "a is notBar". I see both of them being used interchangeably.

**Comment by Hixie** [comment]
Wow. Interesting. That is... surprising.

So `!` has a different meaning if used where an expression is expect vs after `is`.
Where an expression is expected, it actually acts as a `bool`-specific operator. You can't override it.
`is` introduces a new context where only `!` or a type identifier work. You can't put an expression there.
Thanks for explaining this!

**Comment by turnidge** [comment]
Just to document, I switched the code gen to prefer "is!" over "is !".

I also changed "pos ++" to "pos++"
