### ISSUE TITLE
Buildbot "pkg-win-be" cannot build SDK reliably

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25474]
17 of the last 20 builds made by this buildbot have failed at the "build sdk" step.  The remaining 3 builds have terminated with an exception.

This is preventing me from debugging #25470.

**Comment by whesse** [comment]
This is fixed with the master restart.  And there is also a pkg-win bot on
FYI, running Windows 10, which is going smoothly.  The hanging unkillikable
Dart process was locking Dart.exe.  we now reboot to kill it.

**Comment by stereotype441** [comment]
I don't believe the master restart fixed this.  Looking at https://build.chromium.org/p/client.dart/builders/pkg-win-be, there have been 12 build attempts since the bug was closed, and they have all failed at the "build sdk" step.

(Note, however, that this bug no longer blocks #25470, thanks to @whesse's observation that #25470 also reproduces on one of the "try" bots.)

**Comment by whesse** [comment]
Yes, I've noticed.  I just forced a restart on the bots, and am waiting to see if they will auto-reboot now after each run.  We also have the same problem (the hanging unkillable dart) on the Windows 10 bot now, though it only affects the pub-win builder.
