### ISSUE TITLE
May need access from DartScriptState in InspectorConsoleAgent

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#25473]
Dartium 45 roll issue.

Inside InspectorConsoleAgent::sendConsoleMessageToFrontend function we have no way of getting to the DartScriptState since DartScriptState is no longer derived from ScriptState I've currently commented out the code that access isDartScriptState()

    // TODO(terry): Needed to disable because we need to get a DartScriptState
    //              since DartScriptState isn't derived from ScriptState see
    //              issue 
/*
    if (scriptState && scriptState->isDartScriptState()) {
        DartScopes scopes(v8Handle);
        DartInspectorConsoleMessage::addToFrontend(frontend(), m_injectedScriptManager, generatePreview, consoleMessage, jsonObj);
        return;
    }
*/

**Comment by jacob314** [comment]
This is directly related to
https://github.com/dart-lang/sdk/issues/25006
This code is dead code unless that issue is fixed in a way that sends Dart console messages to a separate script.

**Comment by terrylucas** [comment]
Closed this issue for now until #25006 is fixed.
