### ISSUE TITLE
run cps ir browser tests in the bots

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25479]
@whesse - we would like to run dart2js with --use-cps-ir in the bots, what would be the best way to proceed? Do we reuse the existing dart2js bots for this, or add more machines to keep the turnaround times more reasonable?

**Comment by whesse** [comment]
I would add more bots, to keep them separate.  I thought we were already
running this.

**Comment by hterkelsen** [comment]
We are running CPS on the dart2js unit tests, but I don't think we are running them on the html tests. If we were running CPS on the html tests, then that bot would be red since CPS fails many of the html tests.

**Comment by sigmundch** [comment]
@whesse - how is this coming along?

To clarify further from what Harry said - we currently have one bot running dart2js in CPSIR + d8, but no bot running on actual browsers. The cpsir+d8 config covers some tests in the html and co19 suites, but none of the browser tests (which are large part of those suites).

We need to add coverage for chrome, ff, ie11, ie10 & safari. 

Is there something we can do to help? or something we can do short term before we get all the new bots set up?

**Comment by whesse** [comment]
Adding new bots isn't that hard - I can do it, but it will slow down
whatever slaves I pick to also do these ones.  Maybe I can use our cloud
slaves, that don't have IPv6.

On Tue, Feb 9, 2016 at 11:41 PM, sigmundch <notifications@github.com> wrote:

> @whesse <https://github.com/whesse> - how is this coming along?
>
> To clarify further from what Harry said - we currently have one bot
> running dart2js in CPSIR + d8, but no bot running on actual browsers. The
> cpsir+d8 config covers some tests in the html and co19 suites, but none of
> the browser tests (which are large part of those suites).
>
> We need to add coverage for chrome, ff, ie11, ie10 & safari.
>
> Is there something we can do to help? or something we can do short term
> before we get all the new bots set up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25479#issuecomment-182112402>.
>



-- 
William Hesse

**Comment by sigmundch** [comment]
cool, alternatively, any chance we can get more slaves from infra?

If not, I wonder if it's worth splitting the suites to reduce the load on the slaves. For example, I expect the bulk of the co19/language suites are unlikely to have browser-specific behavior, so we could run those only in a subset of the runtimes.

**Comment by sigmundch** [comment]
regardless - I'd be ok starting with either of the three options and improving things a bit a a time. Are any of the cloud slaves windows/mac?

**Comment by whesse** [comment]
No, they are linux, but we have a couple extra windows/mac ones, I think.

**Comment by sigmundch** [comment]
:+1: thanks Bill!

**Comment by whesse** [comment]
We will not add testing of cps-ir on browsers, while development of it is paused.
