### ISSUE TITLE
pub serve stopped working

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/sdk#25481]
I update dart to latest in dev channel. It worked in the morning, but now it is stopped working.

Load Error for "file:///b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart": Error loading file:///b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart:
  FileSystemException: Cannot open file, path = '/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:155)
#1      _asyncLoadError (dart:_builtin:566)
#2      _handleLoaderReply (dart:_builtin:383)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by kevmoo** [comment]
Already covered by a set of issues

Isolate.spawn is broken in snapshots when run near a foreign .packages file dart-lang/sdk#25428
Open
Isolate.spawn is broken in snapshots when the original .packages file is missing dart-lang/sdk#25429
Open
Isolate.spawn is broken in snapshots when the original Dart file is missing dart-lang/sdk#25430
