### ISSUE TITLE
Raw generic method type parameters leaking into propagated type in strong mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25483]
In the code below produces the following hint:

```
[hint] The argument type 'List<T>' cannot be assigned to the parameter type 'Iterable<String>' (/Users/leafp/tmp/scratch.dart, line 5, col 19)
```

Note that the the raw generic method type parameter `T` is leaking into the error message.

I suspect that this is related to the special case code in the analyzer for treating `map` and other functions as generic for the purposes of the propagated type.

```dart
void main() {
  var value;
  var items = value.map((x) => from(x)).toList();
  List<String> l = items;
}
```

Assigning to @jmesserly, since we've discussed turning off type propagation in strong mode either temporarily or permanently.  Feel free to bounce it back though.

**Comment by jmesserly** [comment]
I believe that I *just* landed a fix for this, the fix for #25340, but I'll double check.

**Comment by jmesserly** [comment]
The bug, BTW, was that when getting the propagatedType's return type, it used the uninstantiated type instead of propagatedInvokeType. That's how it ends up with `List<T>` even though it's computed the type of map as `(dynamic -> dynamic) -> List<dynamic>`

**Comment by jmesserly** [comment]
output:
```
Analyzing [test.dart]...
[warning] The function 'from' is not defined (test.dart, line 3, col 32)
[warning] items (dynamic) will need runtime check to cast to type List<String> (test.dart, line 4, col 20)
[hint] The value of the local variable 'l' is not used (test.dart, line 4, col 16)
2 warnings and 1 hint found.
```
looks reasonable to me

**Comment by leafpetersen** [comment]
How's that for bug turnaround time!  Negative time from filing to resolving... :)
