### ISSUE TITLE
dart2js and VM don't agree about factory as a static method

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25489]
Consider the code:

```dart
class Test {
  static factory() {
    return 50;
  }
}

main() {
  print(Test.factory());
}
```

Run this code on the Dart VM:

```
$ dart test.dart
'file:///home/ubuntu/test.dart': error: line 2 pos 17: factory method cannot be explicitly marked static
  static factory() {
                ^
```

Run this code in NodeJS with dart2js:

```
$ dart2js -o test.js test.dart
$ node test.js
50
```

**Comment by lrhn** [comment]
In Dart, `factory` is a "built-in identifier". Those are not allowed in all places:
> . It is a compile-time error if a built-in identifier is used as the declared name of a prefix, class, type parameter or type alias. It is a compile-time error to use a built-in identifier other than dynamic as a type annotation or type parameter.

Here `factory` is the name of a (static) method, which is not prohibited by the specification. It works in dart2js and is accepted by the analyzer, so this is a VM parser bug.

**Comment by mhausner** [comment]
Change the method factory() into a dynamic method and dart2js fails as well:

```
class Test {
  factory() {
    return 50;
  }
}

main() {
  print(new Test().factory());
}


[d2 sdk]$ dart ./pkg/compiler/lib/src/dart2js.dart  ~/tmp/s.dart
/Users/hausner/tmp/s.dart:3:10:
Error: Expected identifier, but got '('.
  factory() {
         ^
/Users/hausner/tmp/s.dart:9:9:
Warning: No method named 'factory' in class 'Test'.
  print(new Test().factory());
        ^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

Another example of how the language is unnecessarily baroque.

**Comment by mhausner** [comment]
Saved the universe with 4ca841772589c193138a18ad807adc66e43cae21
