### ISSUE TITLE
Plans to add Recursive Directory Watching to Linux?

### ISSUE THREAD

**Issue by Andruj** [dart-lang/sdk#25485]
The implementation supports watching both files and directories. Recursive watching is not supported. Note: When watching files directly, delete events might not happen as expected. 
-Docs for https://api.dartlang.org/1.12.0/dart-io/Directory/watch.html

Any plans to allow for recursive glob watching like Node?

**Comment by kevmoo** [comment]
@Andruj have you looked at https://github.com/dart-lang/watcher ?

**Comment by Andruj** [comment]
Yeah I saw that, but I was wondering if there were plans for expanding the sdk watch method....

**Comment by srawlins** [comment]
There are not such plans. The watcher package is used by various tools to accomplish this.
