### ISSUE TITLE
VM allows to invoke Object method on prefix object and constant type literal

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25496]
According to Dart Language specification (4th edition, Dec 2015) "16.17.1 Ordinary Invocation":

"It is a compile-time error to invoke any of the methods of class Object on a prefix object or on a constant type literal that is immediately followed by the token ‘.’."

However, dart (Dart VM version: 1.14.0-dev.6.0 (Wed Jan  6 02:11:09 2016) on "linux_x64") doesn't report compile-time errors when compiles tests:

``` dart
    test1
import '../lib.dart' as lb;

main() {
    lb.toString();
}
```

``` dart
    test2
class A {}

main() {
    A.toString();
}
```

dartanalizer reports warnings:
for test1: [warning] The function 'toString' is not defined 
for test2: [warning] The method 'toString' is not defined for the class 'A'

**Comment by mraleph** [comment]
Closing as stale. VM parser is deprecated.
