### ISSUE TITLE
Strange behavior with generics and type checks

### ISSUE THREAD

**Issue by aghassemi** [dart-lang/sdk#25508]
The following code
```
  List<int> b = [];
  print(b is List<String>);
```

returns `true` for `b is List<String>` but `b` is actually a `List<int>` and should not pass this check.

**Comment by Zowal** [comment]
Try
```
List<int> b = new List<int>();
print(b is List<String>);
```

**Comment by aghassemi** [comment]
oh I see. Thanks! Both `List<int> b = new List<int>();` and `List<int> b = <int>[];` work correctly. Sorry for the false alarm.

Cheers,
Ali
