### ISSUE TITLE
provide a better help message when the Observatory UI is not available

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25502]
If the Observatory UI is not available for some reason, connecting to the port results in an unhelpful error:

{"jsonrpc":"2.0", "error":{"code":-32601,"message":"Method not found","data":{"request":{"method":"vm","params":{}}}},"id":""}

Instead we should provide a message explaining what happened and the workaround. Perhaps something like:

The Observatory API is running, but the Observatory UI not available on this port. (Workaround: connect remotely using another instance of Observatory, such as from Dartium.)

**Comment by johnmccutchan** [comment]
Which embedder ships without the Observatory UI?

**Comment by johnmccutchan** [comment]
@cbracken

**Comment by rmacnak-google** [comment]
d0529c86380
