### ISSUE TITLE
useless deprecated warning?

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25503]
This warning notifies the user that the constructor for a deprecated class is deprecated.
That seems like noise to me.

![screenshot from 2016-01-15 14 38 13](https://cloud.githubusercontent.com/assets/2891888/12363244/b975e1e8-bb95-11e5-9403-5794c3ddb9a0.png)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1598773004/
