### ISSUE TITLE
Blue underline of unused function moves if you subsequently modify parts of the function.

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25504]
_From @apwilson on January 15, 2016 18:35_

```dart
int unusedFunction() => 10 + 10;
    ~~~~~~~~~~~~~~       // underline
```
change to this:

```dart
int unusedFunction() => 1000 + 1000;
        ~~~~~~~~~~~~~~       // underline
```

Underline moves the same number of characters added to the function.

_Copied from original issue: dart-atom/dartlang#702_

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1584653007

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/6b56451788612c49b34f0e85f316a4b037c51f7c
