### ISSUE TITLE
"Invalid constructor name" error doesn't appear after incremental analysis

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25513]
To reproduce in Atom, paste this code into a file:

```
class Card {
  Card.foo();
}
```

Then on the second line, delete the "C" from "Card.foo".

The following message should appear, but doesn't:
test.dart:2: Invalid constructor name

If you reanalyze sources then the error will appear.

(Found via a stress test.)

**Comment by scheglov** [comment]
Works for me.
I think this was fixed by https://github.com/dart-lang/sdk/commit/23e9fbcf3041d2b0a089f128b2841750c3020786
