### ISSUE TITLE
incremental analysis doesn't warn about uninitialized final field

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25515]
To reproduce in Atom, paste this into a file:

```
class Problem {
  final String severity;
  final Map location;
  final String message;

  Problem(Map json)
      : severity = json["severity"],
        location = json["location"],
        message = json["message"];
}
```

Delete line 8 which initializes the 'location' field.

No error shows up. If you reanalyze sources, you will see the error:

The final variable 'location' must be initialized - test.dart, line 6

This might have the same root cause as #25514.
(Found via a stress test.)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1606103003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/203e16919aad10a0958f1e5589e412126d339587
