### ISSUE TITLE
.analysis_options shouldn't be a hidden file

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25510]
The analysis options file is similar to pubspec.yaml in that developers should be able to see it and edit it. It's not like .packages which is normally machine-generated. Therefore I argue that it shouldn't be a hidden file - we should make it visible for all to see.

(It should probably also have the .yaml extension so the editors will do the right thing.)

**Comment by zoechi** [comment]
See also #23927

**Comment by natebosch** [comment]
`analysis_options.yaml` is an option now. Is that enough to resolve this issue or do we want to wait until `.analysis_options` is fully removed?

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/28385 which has longer discussion.
