### ISSUE TITLE
incremental analysis gets confused after editing expression within string interpolation

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25519]
To reproduce, paste this into Atom:

```
import "dart:io";

class DartCommand {
  final String script;
  DartCommand(this.script);

  start(List<String> args, {StringSink logSink}) {
    var exe = Platform.executable;
    if (logSink != null) {
      logSink.writeln("Process starting: $exe ${args.join(' ')}");
    }
    return Process.start(exe, args);
  }
}
```

Then delete the parenthesis just after "join" on line 10.

A bunch of errors show up, but a warning is missing. Reanalyzing sources will make it appear:
The final variable 'script' must be initialized - test.dart line 12

Now, add the parenthesis back again. All errors and warnings should be fixed, but there are three still there:
'start' cannot be used to name a constructor and a method in this class - test.dart, line 15
Invalid constructor name - test.dart, line 15
The final variable 'script' must be initialized - test.dart, line 15

Reanalyzing sources will make the problems disappear.

(Found with a stress test.)

**Comment by scheglov** [comment]
Works for me.
I think it was fixed by https://github.com/dart-lang/sdk/commit/23e9fbcf3041d2b0a089f128b2841750c3020786
