### ISSUE TITLE
incremental analysis doesn't show warnings after deleting a quotation mark

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25514]
To reproduce in Atom, paste this into a file:

```
class Problem {
  final Map location;
  final String message;

  Problem(Map json)
      : location = json["location"],
        message = json["message"];
}
```

Delete the last quotation mark surrounding "location"

Since the file does not parse, it will show several errors, starting with "Unterminated string literal".

However, if you now reanalyze sources, it will show an additional error:
Undefined name 'json' - test.dart, line 6

So, incremental analysis and full analysis don't agree.
The original example was with a larger file where many more warnings show up after a full analysis.
(Found via stress test.)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1605263002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/23e9fbcf3041d2b0a089f128b2841750c3020786
