### ISSUE TITLE
"Type check failed: [value of positional argument] ([type]) is not of type [type of first parameter]"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25527]
Analyzing this:
```dart
class Test { Test({ int a, String b }); }
void main() {
  new Test(true);
}
```
leads to:
```
[error] Type check failed: true (bool) is not of type int (/home/ianh/dev/scratch/test.dart, line 3, col 12)
[warning] 0 positional arguments expected, but 1 found (/home/ianh/dev/scratch/test.dart, line 3, col 11)
```

The first message here (from strong mode) is mighty confusing. I think it should just be dropped entirely.

**Comment by jmesserly** [comment]
I think I fixed this in a very recent CL. Let me double check. We had some crazy logic that, if parameters didn't match up, would check types against whatever happened to be the parameter declared in the same lexical position, regardless of whether it was named or not.

As you point out -- it's totally unnecessary. The message about "0 positional arguments expected, but 1 found" already captures the problem.

**Comment by jmesserly** [comment]
yay, it was fixed :)
```
Analyzing [/Users/jmesserly/scratch/test.dart]...
[warning] 0 positional arguments expected, but 1 found (/Users/jmesserly/scratch/test.dart, line 3, col 11)
1 warning found.
```
Fix was at https://github.com/dart-lang/sdk/commit/f114dc1073d2f8705ad819d83267c8b6fe95588b#diff-5007ab83ce347c31b221267e7fa8de8fR132

**Comment by Hixie** [comment]
sweet, thanks!
