### ISSUE TITLE
incremental analysis puts warnings in the wrong location after editing super call

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25521]
To reproduce, paste into Atom:

```
abstract class Coercion {
  Coercion(fromType, toType);
}

class CoercionError extends Coercion {
  CoercionError() : super(null, null);
}

abstract class CoercionInfo {
  static const String _propertyName = 'dev_compiler.src.info.CoercionInfo';
}
```
There should be a warning:
The value of the field '_propertyName' is not used - test.dart, line 10

Then delete the open parenthesis after "super" on 6.

The location of the warning shifts two characters to the left:

```
  static const String _propertyName = 'dev_compiler.src.info.CoercionInfo';
                    ^^^^^^^^^^^^^
```

Then reanalyze sources, and undo the edit. Now the location of the warning is two characters too far to the right.

Reanalyze sources to fix it again.

(Found with a stress test.)

**Comment by scheglov** [comment]
Works for me.
I think it is fixed by https://github.com/dart-lang/sdk/commit/203e16919aad10a0958f1e5589e412126d339587
