### ISSUE TITLE
investigate use of DartType.isMoreSpecificThan in analyzer w/ strong mode

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25535]
We may want to move this operation onto TypeSystem, so we can have a strong mode version.

CC @leafpetersen @vsmenon

**Comment by jmesserly** [comment]
We're a bit concerned it might be leading to incorrect semantics in some cases. e.g. Future's flatten operation is one that came up recently, as well as type promotion rules (we already avoid isMoreSpecificThan for it -- see TypeSystem.canPromoteTo).

**Comment by bwilkerson** [comment]
If the strong mode definition is different, what is "more specific than" in strong mode?

If it's just that we're using isMoreSpecificThan in some places where that's not appropriate in strong mode, then we should identify the new type operation and change the appropriate clients to use the new operation.

**Comment by jmesserly** [comment]
In strong mode it's just subtype... so if we put it on type system:
```dart
class StrongTypeSystemImpl {
  // ...
  DartType isMoreSpecificThan(DartType t1, DartType t2) => isSubtypeOf(t1, t2);
}
```

Strong mode's subtype is different from the spec's more specific than. For example, function types. The spec would say int -> int is more specific than Object -> Object. Strong mode would say Object -> int is a subtype of int -> Object. (Intuition: a function that accepts any object can be passed an integer, but the reverse isn't true.)
```dart
typedef Object IntToObj(int x);
objToInt(Object x) => 42;
main() {
  IntToObj f = objToInt;
  int x = f(100);
  print(x);
}
```

**Comment by bwilkerson** [comment]
So, yes, strong mode changes the definition of isMoreSpecificThan and it ought to be on TypeSystem.

**Comment by leafpetersen** [comment]
@jmesserly do you have a brief summary of the places that more specific than is used?

**Comment by jmesserly** [comment]
> do you have a brief summary of the places that more specific than is used?
Not really -- `cd pkg/analyzer/lib; git grep isMoreSpecificThan | wc -l` shows 42 uses. Part of the bug was to triage them.

At least one is in the definition of flatten(T). I think I fixed that one, though.

**Comment by jmesserly** [comment]
I suspect this is obsolete; we moved a lot of stuff to TypeSystem.
