### ISSUE TITLE
Provide streamlined Foreign Function Interface like Java's JNA

### ISSUE THREAD

**Issue by jirkadanek** [dart-lang/sdk#25532]
JNA (https://github.com/java-native-access/jna) allows calling into dynamically loaded native libraries from Java without writing any glue code in C. What's more, it can do the calls efficiently.

Another example of streamlined FFI interface is http://luajit.org/ext_ffi.html

The approach to calling native code described in https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/#anatomy-of-a-native-extension is very different and much less straightforward.

The point of this feature request is that I would like to see a JNAlike FFI in Dart. This issue is a followup of #21983

**Comment by asb** [comment]
Dartino/Fletch had a neat FFI library: [implementation](https://github.com/dartino/sdk/tree/master/lib/ffi), [tests](https://github.com/dartino/sdk/tree/master/tests/ffi). Bringing this to the standard Dart VM would be fantastic. Are the core devs receptive to FFI support in this style?

**Comment by asb** [comment]
Dartino/Fletch had a neat FFI library: [implementation](https://github.com/dartino/sdk/tree/master/lib/ffi), [tests](https://github.com/dartino/sdk/tree/master/tests/ffi). Bringing this to the standard Dart VM would be fantastic. Are the core devs receptive to FFI support in this style?

**Comment by asb** [comment]
Dartino/Fletch had a neat FFI library: [implementation](https://github.com/dartino/sdk/tree/master/lib/ffi), [tests](https://github.com/dartino/sdk/tree/master/tests/ffi). Bringing this to the standard Dart VM would be fantastic. Are the core devs receptive to FFI support in this style?

**Comment by asb** [comment]
Dartino/Fletch had a neat FFI library: [implementation](https://github.com/dartino/sdk/tree/master/lib/ffi), [tests](https://github.com/dartino/sdk/tree/master/tests/ffi). Bringing this to the standard Dart VM would be fantastic. Are the core devs receptive to FFI support in this style?

**Comment by asb** [comment]
Dartino/Fletch had a neat FFI library: [implementation](https://github.com/dartino/sdk/tree/master/lib/ffi), [tests](https://github.com/dartino/sdk/tree/master/tests/ffi). Bringing this to the standard Dart VM would be fantastic. Are the core devs receptive to FFI support in this style?

**Comment by floitschG** [comment]
This would be a multi-area effort (touching on the VM, precompilation, frontend, ...), so CCing /cc  @mraleph @kmillikin

**Comment by mraleph** [comment]
Closing as stale. No work is currently happening on this issue and no work is scheduled.
