### ISSUE TITLE
Analyzer report static warning for @proxy superclass

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25540]
According to Dart Language specification (4th edition, Dec 2015) "16.17.3 Super Invocation":

"Let Sstatic be the superclass of the immediately enclosing class. It is a static type warning if Sstatic 
does not have an accessible instance member named m unless Sstatic or a superinterface of Sstatic 
is annotated with an annotation denoting a constant identical to the constant @proxy deﬁned in 
dart:core."

However dartanalyzer (version 1.14.0-dev.7.1) reports static warning:

``` dart
> dartanalyzer test.dart
Analyzing [test.dart]...
[warning] The method 'nonExistingMethod' is not defined in a superclass of 'S' 
(test.dart, line 6, col 11)
1 warning found.
```

``` dart
@proxy
class S {}

class A extends S {
  test() {
    super.nonExistingMethod(); ///ststic type warning
  }
}
```

**Comment by lrhn** [comment]
In case the example looks like it *should* fail, this can be meaningful code now that class `A` can be used as a mixin on a class implementing `S`.
