### ISSUE TITLE
bogus error for final field used as constant

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25547]
```
final times1 = [];

class Foo {
  final times2 = [];

  foo1([int x = times1]) {}
  foo2([int x = times2]) {}
}
```

I see three errors:
'const' variables must be constant value - test.dart, line 4
Default values of an optional parameter must be constant - test.dart,line 6
Default values of an optional parameter must be constant - test.dart, line 7

We shouldn't show the error on line 4 because times2 is not const. Based on the code, it appears that we calculate a constant value for final fields, but not for a final top-level variables, and this triggers the error.

(Simplified from #25526)

**Comment by parlough** [comment]
Seems to be fixed already with https://github.com/dart-lang/sdk/commit/ccf3870ffcec6f6418dd7471f924be86674f22ce
