### ISSUE TITLE
service/developer_extension_test might be flaky

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25545]
Here is an example failure:

https://build.chromium.org/p/client.dart/builders/vm-mac-release-ia32-be/builds/11630/steps/tests/logs/stdio

I was not able to reproduce this locally. This showed up after a change I made to dart2js, which I believe is unrelated to this.

@johnmccutchan @turnidge

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1751523003/ should give us a clue.
