### ISSUE TITLE
Missing "getPrivateSymbol" mentioned in ECMA-408

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#25549]
Section 16.6 Symbols:
```
A symbol literal # id evaluates to the object that would be returned by
the call mirror.getPrivateSymbol(’id’) where mirror is an instance of the class
LibraryMirror defined in the library dart:mirrors, reflecting the current library
```
getPrivateSymbol doesn't exists for LIbraryMirror.

I'm mostly trying to make testing of private members easier. If only symbolLiteral would access a library private symbols. It is currently defined as:

‘#’ (operator | (identifier (‘.’ identifier)*))

Would have been nice to do something in test code as #otherlib._privateSymbol

**Comment by lrhn** [comment]
The mirror library doesn't seem to implement getPrivateSymbol, so I guess  mention of it it should be removed from the spec.

**Comment by lrhn** [comment]
The actual way to create private symbols in the mirror system is: `MirrorSystem.getSymbol("_privateSymbol", libraryMirror)`.

Example:

    var core = reflectClass(Invocation).owner;
    var s = MirrorSystem.getSymbol("_id", core);
    print(s);
    print(s == #_id);
