### ISSUE TITLE
No documentation comment in hover for overriding methods

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25542]
Enter the following in a Dart file:

    class A {
      /** Return the name of this object's class. */
      String get className => 'A';
    }

    class B extends A {
      @override
      String get className => 'B';
    }

    f(B b) {
      b.className;
    }

Hover over the getter in `A` and see that the comment is included in the hover text.

Hover over the getter in `B`. There is no doc comment displayed. Hover over the getter in `f`. Again, there is no doc comment. The getter in `B` should inherit the comment from `A` and it should be displayed in both places.

**Comment by skybrian** [comment]
Perhaps with an (inherited comment) indicator at the end, to avoid confusion?

**Comment by bwilkerson** [comment]
Sure. Although in the spirit of more is better, perhaps something like "Copied from A" to indicate which class contains the inherited method.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1632033002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/e7e52ae2c05bed6567bfaf3c8b9c8918a466c6d7
