### ISSUE TITLE
Analyzer crashes compiling deeply nested code

### ISSUE THREAD

**Issue by mhausner** [dart-lang/sdk#25558]
The analyzer crashes when compiling deeply nested expressions or statements.

Tests: language/deep_nesting1_test, language/deep_nesting2_test

**Comment by bwilkerson** [comment]
Where are these tests located? I just resynced but they're not where I expected to find them (tests/language). If they're not checked in yet, could you attach it here or send it to me via e-mail? Thanks.

**Comment by mhausner** [comment]
The are checked in now. I had to rename them to deep_nesting1_negative_test
and deep_nesting2_negative_test, btw.

**Comment by scheglov** [comment]
CL to avoid crashing, and reporting a parse error instead.
https://codereview.chromium.org/2823993002
