### ISSUE TITLE
Isolate spawnUri Unable to spawn isolate (1.14.0-dev.7.2)

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#25556]
There appears to be some change in 1.14.0-dev.7.2 that is causing us not to be able to locate code from the library with the specified URI.

The code for the Isolate to run is sitting in the same directory as the code which spawns the Isolate.

This is within the test, directory.... Was previously elsewhere but scale it right back and can still produce the problem

Spawn code 

``` dart
Uri exec = new Uri.file('isolate_executor.dart');
List args = [1,2,3]
String msg = ' Whatever'
Isolate result = await Isolate.spawnUri(exec, args, msg)
```

```bash
dart:isolate                                     Isolate.spawnUri
package:durable/src/services/isolate.dart 16:24  acquireIsolate.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:durable/src/services/isolate.dart        acquireIsolate
test/unit/isolate_test.dart 33:32                main.<fn>.<fn>.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
test/unit/isolate_test.dart                      main.<fn>.<fn>

IsolateSpawnException: Unable to spawn isolate: 'data:application/dart;charset=utf-8,import%20%22package:test/src/backend/metadata.dart%22;%0Aimport%20%22package:test/src/runner/vm/isolate_listener.dart%22;%0A%0Aimport%20%22file:///Users/rayk/Projects/durable/test/unit/isolate_executor.dart': error: line 4 pos 76: unterminated string literal
import "file:///Users/rayk/Projects/durable/test/unit/isolate_executor.dart
                                                                           ^
``` 
The isolate_executor.dart just has a main, with nothing else.

```dart
/// This Isolate execute is used for test only purposes. It provides a script
/// to call from within the test environment.

main(List args, int messages) {}
```

I initially thought the problem was with the paths in the URI, I had the spawning code in separate directory as code for the Isolate to execute. Which was previously working fine.  I kept scaling back the problem until I reach the point above.. The spawning code in the test directory and sitting right next to the code for the isolate.

Not sure if this relates to #24058... But need some help. Thanks.

**Comment by lrhn** [comment]
You are using `new Uri.file(...)` with a relative path. That means that the resulting URI is also relative - it's just "isolate_executor.dart", with no "file:" or path in front (the only difference between `new Uri.file` and `Uri.parse` in this case is that the former accepts backslashes as path separators on Windows).

So, you are trying to do `Isolate.spawnUri(relativeUri,...)`. That first resolves the relative URI relative to the URI of the isolate entry-point. I believe that is what has always happened (we considered resolving it relative to Uri.base, but realized that that would change the existing behavior).

However, that doesn't explain the actual data: URI we are seeing here (which is indeed missing a closing quote and everything after that). 

Is your isolate entry-point a data: URI?
That would explain that everything after the last '/' in the URI is replaced by "isolate_executor.dart".
A data: URI is a non-hierarchical URI, so resolving relative to that won't work very well (the result is slightly amusing, but mostly painful).

If this worked before, it must have previously resolved the exec URI against a different base URI.
@nex3 Natalie, is this data:-URI as entry point a new thing in tests? (Is it even test doing it?)
@iposva-google If not, Ivan, can you see what it would previously have done that worked?

**Comment by nex3** [comment]
> Natalie, is this data:-URI as entry point a new thing in tests? (Is it even test doing it?)

Test is doing it, but it's not particularly new. It was added in dart-lang/test@a635337bce85dd49ed74a24eeb6dc9c8ed7652ed, which was released in version 0.12.4+1 in August.

**Comment by rayk** [comment]
Guys for added clarity just knock up this experiment:

```bash
~/Projects/isodance > ls -R             
CHANGELOG.md README.md    lib          pubspec.lock test
LICENSE      example      packages     pubspec.yaml

./example:
isodance_example.dart packages

./lib:
findStub.dart findfile.dart isodance.dart src

./lib/src:
core.dart          findFile.dart      iso_executor.dart  isodance_base.dart

./packages:
.......

./test:
findFile.dart           isodance_test.dart      simp_iso_test.dart
findStub.dart           packages                test_executor_stub.dart

```

**Comment by rayk** [comment]
Quick experiment to explore the issue further, (Hope this will give more signal than noise)

#### The Directory Layout 

```bash
CHANGELOG.md README.md    lib          pubspec.lock test
LICENSE      example      packages     pubspec.yaml

./example:
findfile.dart packages

./lib:
findStub.dart findfile.dart isodance.dart src

./lib/src:
core.dart          findFile.dart      iso_executor.dart  isodance_base.dart

./packages:
..... "as expected"

./test:
findFile.dart           isodance_test.dart      simp_iso_test.dart
findStub.dart           packages                test_executor_stub.dart
```

#### Dumb code to show the relative path

```dart
import 'dart:io';
import 'package:path/path.dart';

main() {
    Context pwd = new Context();

    print('-------------------------------------------------------------');
    print('Platforms Natural Base: ${Uri.base}');
    print('Present Working Dir: ${pwd.current.toString()}');
    print('-------------------------------------------------------------');
    
    Uri pathA = new Uri.file('lib/src/iso_executor.dart');

    File fileSysObject = new File.fromUri(pathA);
    
    print('P a t h  A:');
    print('************');
    
    print("isAbsolute?: [${pathA.isAbsolute}]");
    print("toString:\t\t [${pathA.toString()}]");
    print('authority: [${pathA.authority}]');
    print('hasAbsolutePath: [${pathA.hasAbsolutePath}]');
    print('host: [${pathA.host}]');
    print('path: [${pathA.path}]');
    print('pathSegments: [${pathA.pathSegments}]');
    print('scheme: [${pathA.scheme}]');
    print('---------------------------------------------------------');
    print('Existens: [${fileSysObject.existsSync()}]');
    
}
```

**Comment by lrhn** [comment]
The "unterminated string literal" comes because the test framework changes the entry point to be a data URI. You can't be relative to a data URI, and spawnUri resolves a relative URI relative to the entry point (we should probably throw if resolving against a data: URI instead of doing something meaningless).  

My only question is why it worked before 1.14 - it should also have been resolving relative to the entry point there, and the test package has been using a data: entry point for a while (according to Natalie above).

Ivan?

**Comment by mit-mit** [comment]
Closing this as per last comment from @lrhn is sounds like we have the correct behavoir. Sorry if I missed something in this long thread.
