### ISSUE TITLE
VM doesn't introduce function type on class from abstract call member.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#25550]
Example:

    typedef int Adder(int a, int b);
    class Mock {
      noSuchMethod(i) => ...l
    }
    class MockAdder extends Mock {
      int call(int a, int b);
    }
    main() {
      Adder adder = new MockAdder();  // Checked-mode failure in VM.
    }

The code runs in dart2js and has no warnings from the analyzer.
The type `MockAdder` should be a subtype of `Function` and the function type (int,int)->int, but in the VM, it isn't.

Adding a call member is the only way to add a function type to a class (you can't `implement Adder`).

The workaround is to add a concrete function: `int call(int a, int b) => super(a, b);` instead, but that shouldn't be necessary.

**Comment by iposva-google** [comment]
@gbracha Here is a question for you: Does it really count as implementing a Function if the call method is abstract?

**Comment by lrhn** [comment]
*Implementing* a function is defined in terms of the interface of the class, not the implementation. Whether a method is abstract or not does not change how it affects the class' interface.

If you define an abstract type with a call method, a variable of that type must be treatable as a function:
```dart
typedef int Func(int _);
class C { int call(int x) => x * 2; }  // Implements Function and int->int.
abstract class C2 implements C {}  // Implements C, so also implement Function and int->int
class C3 extends C2 { noSuchMethod(i) => 42; }  // Extends C2, so implements Function and int->int.
C foo () => new C3();
main() {
   C c = foo();
   Func f = c;  // Must not fail in checked mode.
}
```

See also:
> It is a static warning if a concrete class implements Function and does not have a concrete method named call unless that class has an implementation of noSuchMethod() distinct from the one declared in class Object.

That at least suggests that you can be a function without a concrete call method.
