### ISSUE TITLE
Hint if a final field "overrides" non-final field

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#25567]
If a final field "overrides" a non-final field, the setter for the superfield becomes a black hole eating all values assigned to the field, never to be seen again.

For extra style points, the hint could be omitted if the setter is also explicitly overridden and/or the super field is accessed using super, because that indicates the user knows what he is doing. Without those indicators, I would argue it is certainly a bug, and we could save the user from one of those "wtf moments" that Dart wasn't supposed to have.

Of course, using fields to "override" other fields is kind of a grotesque coding style in general, so it might be better to just always hint about this.

**Comment by alexeieleusis** [comment]
Sent a CL for review https://codereview.chromium.org/1870423002

**Comment by pq** [comment]
@alexeieleusis's lint landed a while ago so closing out.

Docs here:

http://dart-lang.github.io/linter/lints/overridden_fields.html

👍
