### ISSUE TITLE
Analyzer doesn't always normalize

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#25563]
I have the following error/warning:

WARNING: The argument type 'Message (/usr/local/google/home/floitsch/code/mojo-pkg/lib/src/message.dart)' cannot be assigned to the parameter type 'Message (/mnt/ssd/floitsch/code/mojo-pkg/lib/src/message.dart)' ([mojo] lib/src/proxy.dart:221)

The reason for this message is, that `/usr/local/google/home/floitsch/code` is a symlink to `/mnt/ssd/floitsch/code`.

It seems like on some code-paths, the analyzer normalizes symbolic links, whereas on others it doesn't.

My project doesn't have any absolute paths, so the choice of using the /usr/local or /mnt/ssd is not something that is imposed by the packages-symlink (or similar).

**Comment by floitschG** [comment]
I just started working on the analyzer, and (ironically) just ran into this again.

It seems like the analyzer itself is not affected, but only the IDE.

Reproduce (also see the attached .tar file):
1. Create a directory somewhere.
2. Create two packages inside it.
3. Make the two packages depend on each other. (See below for how this should be done).
4. create a symlink to the directory that contains the two packages.
5. open the packages inside intellij from within those two directories.

How to create the dependency:

In the first pkg:
``` dart
import 'package:pkg2/lib2.dart';

class A {}
A a;
bar() { a = foo(); }
```

In the second package:
``` dart
import "package:pkg1/lib1.dart";

A foo() { return new A(); }
```

This dependency yields the following IDE warning:
> WARNING: A value of type 'A (/tmp/sym/pkg1/lib/lib1.dart)' can't be assigned to a variable of type 'A (/tmp/sym/symlink/pkg1/lib/lib1.dart)'. ([pkg1] lib/lib1.dart:8)

You should be able to use the attached .tar file.

[sym.tar.gz](https://github.com/dart-lang/sdk/files/717016/sym.tar.gz)

**Comment by srawlins** [comment]
Closing as stale.
