### ISSUE TITLE
Dartium layout tests fail with new "Observatory is listening ..." message

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25571]
All of the dartium bots are failing the Webkit dart layout tests, because two tests are not getting the expected test output from the browser.  They are getting additional text at the beginning, saying the observatory is listening on a specific port:

--- /mnt/data/b/build/slave/dartium-lucid64-full-be/build/src/webkit/Release/layout-test-results/dart/inspector/debugger-expected.txt
+++ /mnt/data/b/build/slave/dartium-lucid64-full-be/build/src/webkit/Release/layout-test-results/dart/inspector/debugger-actual.txt
@@ -1,3 +1,5 @@
+Observatory listening on http://127.0.0.1:42300
+CONSOLE INFO: Observatory listening at http://127.0.0.1:37531/
 
 Running: testSetBreakpoint
 Set timer for test function.

I don't see how we can update the test expectations to include these messages, because the messages are different each time, and use different ports.  For example, another linux bot has the extra lines:
+Observatory listening on http://127.0.0.1:45697
+Observatory listening on http://127.0.0.1:42704
+CONSOLE INFO: Observatory listening at http://127.0.0.1:45697/
 

Is there a way to stop Dartum from printing these observatory messages, or of making the tests expect them?
@alan-knight @terrylucas @johnmccutchan @rmacnak-google

**Comment by johnmccutchan** [comment]
Someone must have reverted my change to remove these messages from the test log.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/888663005/

**Comment by jacob314** [comment]
I'm taking a look at why it is broken.

**Comment by jacob314** [comment]
https://codereview.chromium.org/1638583003/
Should fix it. Waiting for the bots.
Wish the webkit diffs weren't so misleading. if yourtestname-actual.txt
included the results of running the text normalization passes in
single_test_runner.py
it would be a lot clearer what the actual diff was.

**Comment by jacob314** [comment]
Confirmed. It was just a case of confusing error messages. Really wish the diff actually reflected why the test failed. The diff for Observatory doesn't cause the test to fail and there was a "diff" even though the text was the same due to asymmetric running of post-process steps on only the actual file and not the expectation file.

**Comment by whesse** [comment]
Thanks.  Now we know for the future, that we need to look deeper.

On Wed, Jan 27, 2016 at 7:55 PM, Jacob Richman <notifications@github.com>
wrote:

> Confirmed. It was just a case of confusing error messages. Really wish the
> diff actually reflected why the test failed. The diff for Observatory
> doesn't cause the test to fail and there was a "diff" even though the text
> was the same due to asymmetric running of post-process steps on only the
> actual file and not the expectation file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25571#issuecomment-175791833>.
>



-- 
William Hesse
