### ISSUE TITLE
MISSING_ENUM_CONSTANT_IN_SWITCH should be a warning

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25576]
Given a switch over an enum, where the switch does not handle all cases. This is currently an error in Analyzer. I believe it should be a warning, per the spec, as well as the documentation comment.

```dart

  /**
   * Enum proposal: It is a static warning if all of the following conditions
   * hold:
   * * The switch statement does not have a 'default' clause.
   * * The static type of <i>e</i> is an enumerated typed with elements
   *   <i>id<sub>1</sub></i>, &hellip;, <i>id<sub>n</sub></i>.
   * * The sets {<i>e<sub>1</sub></i>, &hellip;, <i>e<sub>k</sub></i>} and
   *   {<i>id<sub>1</sub></i>, &hellip;, <i>id<sub>n</sub></i>} are not the
   *   same.
   *
   * Parameters:
   * 0: the name of the constant that is missing
   */
  static const CompileTimeErrorCode MISSING_ENUM_CONSTANT_IN_SWITCH =
      const CompileTimeErrorCode(
          'MISSING_ENUM_CONSTANT_IN_SWITCH',
          "Missing case clause for '{0}'",
          "Add a case clause for the missing constant or add a default clause.");
```

Note the mismatch between the comment (warning) and the error level. I checked and 3rd ed Dart spec says it should be a warning:
> It is a static warning if all of the following conditions hold:
> • The switch statement does not have a default clause.
> • The static type of e is an enumerated typed with elements id1, . . . , idn.
> • The sets {e1, . . . , ek} and {id1, . . . , idn} are not the same.
> In other words, a warning will be issued if a switch statement over an enum is
not exhaustive.

Should be a simple fix: change CompileTimeErrorCode to StaticWarningCode.

**Comment by munificent** [comment]
Hey, @bwilkerson and @stereotype441, is it OK if I work on this?

**Comment by bwilkerson** [comment]
Of course!
