### ISSUE TITLE
Dartium 45 will probably crashed if paused.

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#25589]
The following function in DartUtilitites.cpp should be written to use DartHandleProxy instead of why I wrote.  JacobR will rewrite.

ScriptValue DartUtilities::dartToScriptValue(Dart_Handle object)
{
    // TODO(terry): Added bug per JacobR - he thinks it would be better to use
    //              DartHandleProxy probably pressing pause crashes Dartium 45.
    //              See issue: 
    Dart_Handle exception = 0;
    ScriptState* v8ScriptState = currentDartScriptState()->v8ScriptState();
    v8::Handle<v8::Value> value = V8Converter::toV8(object, exception);
    if (exception)
        return ScriptValue(v8ScriptState, v8::Undefined(v8ScriptState->isolate()));
    ASSERT(!value.IsEmpty());

    return ScriptValue(v8ScriptState, value);
}

**Comment by mit-mit** [comment]
Tagging P1 per note that this can cause crashes.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by terrylucas** [comment]
This was fixed by Jacob
