### ISSUE TITLE
using `catch` as the name of a constructor argument

### ISSUE THREAD

**Issue by hackst8r** [dart-lang/sdk#25584]
import 'package:test/test.dart' ;

/**
# PROBLEM

Exposed by using `catch` as the name of a constructor argument

```
$ dart --version
Dart VM version: 1.13.2 (Tue Jan  5 06:40:05 2016) on "linux_ia32"
```

# SYMPTOM

when attempting to run this test , the test runner get's caught in an infinite loop and must be interrupted with ^C^C .

sample output from test runner :
```
00:00 +0: loading test/test_aaaa_test.dart
00:00 +0: test/test_aaaa_test.dart: use catch as a function argument name
00:01 +0: test/test_aaaa_test.dart: use catch as a function argument name
00:02 +0: test/test_aaaa_test.dart: use catch as a function argument name
…etc in an endless loop…
^C^C
shell returned 254
```

# EXPECTATION

- is it really the case that all reserved words like `catch` are forbidden from usage as function argument names ?
- even if it is , dart should flag this error instead of the current confusing and hard to track down behavior

# AUTHOR

hackst8r
**/
```
void main ()
{
	test ("use catch as a constructor argument name", () => new TEST ()) ;
}

class TEST
{
	TEST ()
	{
		new FOO ('hello') ;
	}
}

class FOO
{
	String msg ;

	FOO (String catch)
	{
		msg = catch ;
	}
}
```

**Comment by lrhn** [comment]
@nex3 
Similar to #25585. Suggests that any syntax error can cause the test runner to hang.

**Comment by whesse** [comment]
Created issue https://github.com/dart-lang/test/issues/389 in the repository for the test package.  Please continue discussion on this bug there.
