### ISSUE TITLE
Exception when trying to set breakpoint in library run by test package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25586]
I ran VM with `dart --observe --pause-isolates-on-start test/model_test.dart`

Then, I opened observatory. I tried to set a breakpoint in one of my model classes in lib/ and then I saw this:

![screen shot 2016-01-26 at 10 36 24 am](https://cloud.githubusercontent.com/assets/5479/12590643/dc3e990a-c418-11e5-8015-d8f71179f0e2.png)

Running:

```
~/Code/dartdoc[exported-libs] $ dart --version
Dart VM version: 1.13.1 (Thu Dec 17 06:29:16 2015) on "macos_x64"
```

To repro, clone this https://github.com/dart-lang/dartdoc, run `pub get`, and then run `dart --observe --pause-isolates-on-start test/model_test.dart`

Thanks for taking a look!

**Comment by johnmccutchan** [comment]
Just tested and confirmed this works as expected on

Dart VM version: 1.14.0-dev.4.0 (Fri Dec 11 01:51:05 2015) on "linux_x64"

**Comment by sethladd** [comment]
Works for me with 1.14-dev. Thanks for checking!
