### ISSUE TITLE
using `this.msg` as the name when defining a property of a class

### ISSUE THREAD

**Issue by hackst8r** [dart-lang/sdk#25585]
import 'package:test/test.dart' ;

/**

# PROBLEM

Exposed by using `this.msg` as the name when defining a property of a class .

```
$ dart --version
Dart VM version: 1.13.2 (Tue Jan  5 06:40:05 2016) on "linux_ia32"
```

# SYMPTOM

when attempting to run this test , the test runner get's caught in an infinite loop and must be interrupted with ^C^C .

sample output from test runner :
```
00:06 +0: test/test_aaaa_test.dart: use this.msg as the name when defining a property of a class   ^C
Waiting for current test(s) to finish.
Press Control-C again to terminate immediately.
^C
shell returned 254
```

# EXPECTATION

- dart should emit a syntax error instead of the current confusing and hard to track down behaviour

# AUTHOR

- hackst8r

**/
```
void main ()
{
	test ("use this.msg as the name when defining a property of a class", () => new TEST ()) ;
}

class TEST
{
	TEST ()
	{
		new FOO ('hello') ;
	}
}

class FOO
{
	String this.msg ; // - oops ! s/b : `String msg`

	FOO (String this.msg)
	{
	}
}
```

**Comment by lrhn** [comment]
The syntax causes a syntax error in my Dart VM (1.14.0), as well as in dart2js and the Dart analyzer.

Is this only caused by the test runner hanging?

**Comment by whesse** [comment]
This is not what area-test is for.  This bug should be filed in the test package repo.  I have created issue https://github.com/dart-lang/test/issues/389, and have moved this issue there.  All further discussion should be on that issue.
