### ISSUE TITLE
analysis cache corruption detected via call to diagnostic.getDiagnostics

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25593]
I modified my stress tester to periodically get diagnostics. This resulted in an exception (after running for a while) in DiagnosticDomainHandler.computeDiagnostics. I can consistently reproduce it using the example/playdrag.dart file:

class PlayDrag {
  final List<num> times = new List<num>();

  PlayDrag.start() {}

  void update(num pos) {
    for (int i = times.length - 2; i >= 0; i--) {}
  }
}

The exception is:

NoSuchMethodError: method not found: 'exception'
Receiver: null
Arguments: [], stackTrace: #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DiagnosticDomainHandler.extractData (package:analysis_server/src/domain_diagnostic.dart:74)

From debugging, it looks like the problem that extractData encounters cache corruption by iterating over all the entries in the cache. Internally, SingleMapIterator looks up each key in a map. The bug happens when it gets back a null CacheEntry. The hashCode is changing after the entry was added to the cache, so the entry can no longer be found.

The CacheEntry triggering the exception has a DefaultParameterElementImpl as its key and its value prints as "int itimes.length - 2". So, the mutation being tested is probably adding the "r" in "for" to convert a function definition into a for loop.

I believe (but haven't yet proven) that it's due to an update in the incremental resolver.

The PoorMansIncrementalResolver.resolve() function updates the cache before changing element offsets:

incrementalResolver._updateCache();
incrementalResolver._updateElementNameOffsets();

The problem is that changing element offsets changes their hash codes. It seems likely that this changes the key of an element that's already in the cache.

More generally, I think we need to verify that we never mutate an Element so that its hashCode changes after putting it into the cache. Perhaps Element mutations should trigger an exception in that case.

**Comment by skybrian** [comment]
@scheglov

**Comment by skybrian** [comment]
Some questions about how locations work in the element model:

Most elements (other than MultiplyDefinedElement), have a location property that returns a non-null ElementLocation. You can then call AnalyzerContext.getElement(location) to get the original Element back. Also, ElementLocation has an encoding that can be used to reconstruct a location, so it could even be sent across the network. (However, this encoding doesn't seem to be used in the analysis server API?)

How long do these ElementLocations need to be valid? Is there a need for getElement() to work for anonymous functions and local variables? Within a Dart program, there's no way to refer to these things from outside a method body, so it would be nice if they didn't need to have a globally unique name.

**Comment by skybrian** [comment]
Suppose we stop using an Element as a key to look things up in the cache? Instead we could introduce an immutable ElementKey which is an AnalysisTarget.

By default, operator== of ElementImpl uses ElementKind and ElementLocation to decide that two elements are equal, so they belong in ElementKey. Where operator== is currently overridden, we would want to provide a different key.

This way, an element's key may change (causing a leak) but it's not possible to corrupt a cache key.

**Comment by skybrian** [comment]
I also tried changing Element's operator== and hashCode to use identity equality as @scheglov suggested. To get tests to pass that use _SameResolutionValidator, I needed to change operator== in InterfaceTypeImpl to do the equality check the old way, using the element location.

**Comment by bwilkerson** [comment]
> ElementLocation has an encoding ... However, this encoding doesn't seem to be used in the analysis server API?

Correct. The client does not (currently) need to refer to an element, hence there was no need to pass this information across the API.

> How long do these ElementLocations need to be valid?

For as long as the element exists. An ElementLocation is for an element as a file path is for a file.

> Is there a need for getElement() to work for anonymous functions and local variables? Within a Dart program, there's no way to refer to these things from outside a method body, so it would be nice if they didn't need to have a globally unique name.

I don't know. The answer used to be yes, because we used locations as keys in the index, but I think that has changed. I'm not sure whether there's any other use of locations associated with elements inside a function body. I do know that locations are being used for summaries, but I don't believe that summaries encode elements inside function bodies.

> Suppose we stop using an Element as a key to look things up in the cache? Instead we could introduce an immutable ElementKey which is an AnalysisTarget.

If the performance penalty of doing so wasn't significant (just to be clear, I don't know whether it would be or not), then that would probably be ok. But it seems to me that if we were able to do so then we could just define Element.== to use the state in the ElementKey without adding the indirection.

> This way, an element's key may change (causing a leak) but it's not possible to corrupt a cache key.

A memory leak would be equally bad. We need to look for a solution that doesn't have that characteristic.

**Comment by skybrian** [comment]
Fixed by 54ee3eefd1a0e3ce12ba6d5fd03a4213dabccdb2

I will start a new issue to discuss alternatives to file offset based locations.
