### ISSUE TITLE
Dart VM using much more memory than Observatory reports

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25592]
Hello! I have been doing thorough investigations into possible memory leaks in our own codebase for DSA. However, I am noticing that the memory usages displayed in Observatory are massively off from what I am seeing in System Monitoring tools. On the reproduction below, I'm getting hundreds of megabytes more in real memory usage than what I see in Observatory.

I have created a special repository for storing reproductions of these kinds of things. Sorry for not including all the info here, if that is desired rather than externally linking it, please let me know.

[Reproduction Information](https://github.com/IOT-DSA/reproductions/blob/master/cases/01-26-16_DartIncreasedMemory.md)

**Comment by Pacane** [comment]
Nice work

**Comment by alexander-doroshko** [comment]
May be related to #25178 and #24613

**Comment by iposva-google** [comment]
Not related to #25178 or #24613 as in this report the observatory is not showing where the memory is being consumed unlike in these other issues.

**Comment by iposva-google** [comment]
cc @johnmccutchan @zanderso

**Comment by kaendfinger** [comment]
Has it been reproduced yet? If it is reproduced by others, it could be a potential blocker for 1.14.

**Comment by johnmccutchan** [comment]
@kaendfinger I have been running your reproduction on Linux with 1.14-dev.7.2 for two hours and I haven't seen anything yet.

Virtual Memory: 705.9 MB
Resident Memory: 175.7 MB
Writable Memory: 169.8 MB

**Comment by kaendfinger** [comment]
@johnmccutchan It looks like this might have been the result of accidentally using the wrong Observatory for another test I was doing, which resulted in the memory usage being higher.

I'm going to close this issue, the memory leak investigation for DSA has lead us to find a leak in our own code. Thanks for the help :)
