### ISSUE TITLE
CLI version of the analyzer backed by the server

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25590]
Right now I run `dartanalyzer` under `watch` which is suboptimal. I only get updates every ~25 seconds, and if I made the change right at the start of those ~25 seconds, it can be up to a ~50 seconds before I see the error. I'd love to be able to run a command line version of the analyzer driven by the analyzer server such that it could give right up-to-the-second updates.

The most Unixy option is probably to have the server run in the background, and then a command line interface that just dumps the current status, which I would then run under `watch`.

**Comment by sethladd** [comment]
One workaround for now: keep Atom open, only for the live analyzer view.

**Comment by devoncarew** [comment]
We have this now, in `flutter analyze --watch`.
