### ISSUE TITLE
Request to use all packages in package_config.json when offering to Quick Fix add import

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25599]
(this is the analyzer-specific issue request from https://github.com/dart-atom/dartlang/issues/730)

If a library is from a package in pubspec.lock or .packages (that is, the package is part of my project), it would be productive and helpful if the library is available for Quick Fix - Add Import.

Steps:
- Add flutter to your pubspec.yaml
- Run pub get
- Open lib/main.dart
- Delete any existing imports
- Put your cursor on Widget, which should have a warning ("unknown name")
- Trigger Quick Fix (Control-1 in Atom)

Expected:

Two options for the Quick Fix:
- Create class Widgets
- Offer "auto-import package:flutter/widgets.dart"

Actual:
- Create class Widgets

Rationale: the library (widgets.dart) is part of flutter package, which I have installed.

**Comment by scheglov** [comment]
This was implemented, we look at all dependencies in `pubspec.yaml`, normal and `dev` (outside `lib`), and suggest code completion or quick fixes with API libraries from these dependencies.
