### ISSUE TITLE
Duplicated setters cause an invalid element model to be create

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25601]
Add the following code to a Dart file:

class C {
  set zzz(x) {}
  set zzz(y) {}
}

The synthetic field created for the first setter ends up being associated with the second setter as well. Not sure what the right solution is, but my first guess is that we should create a second synthetic field.

**Comment by bwilkerson** [comment]
See
DeclarationResolverTest.fail_visitMethodDeclaration_setter_duplicate
ElementBuilderTest.fail_visitMethodDeclaration_setter_duplicate

**Comment by bwilkerson** [comment]
Actually, the best solution is to stop creating synthetic fields, but that's a much bigger task.

**Comment by srawlins** [comment]
At this point, we at least have a compile time error. Maybe it does not matter if the element model is a little bit flawed in such a case.
