### ISSUE TITLE
Analyzer should not search superclass (or interfaces) of mixins during resolution

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25605]
The following code should generate a static warning:

    class A { a() => null; }
    class B {}
    class C {}
    class M = A with B;
    class T = C with M;
    main() {
      new T().a();
    }

The reason a warning is needed is because the declaration `class T = C with M` creates a class whose superclass is `C` and which declares everything that `M` declares.  `M`, in turn, declares everything that `B` declares.  `M` does not declare `a`, it merely inherits it.  Therefore, since `a` is not declared by any superclass or interface of `T`, attempting to access a member `a` of `T` should be a warning.

Similarly, this code should generate a static warning:

    class A {}
    class B { b() => null; }
    class C {}
    class M extends A with B {}
    class T = C with M;
    main() {
      new T().b();
    }

Again, `T` declares everything that `M` declares.  But `M` does not declare `B`, it merely inherits it from its superclass (which is `A with B`).  Therefore, attempting to access a member `a` of `T` should be a warning.

Finally, this code should generate two static warnings, but it only generates the first one:

    class A { a() => null; }
    class B {}
    abstract class M implements A {}
    class T = B with M; // Warning: Missing concrete implementation of 'A.a'
    main() {
      new T().a(); // Warning: The method 'a' is not defined for the class 'T'
    }

The second warning is required because `T` declares everything that `M` declares, and `M` does not declare `a`.  Therefore, neither `T` nor any of its superclasses or interfaces declare `a`.

The first two cases are only possible with the presence of the `--supermixin` flag.

I will add tests demonstrating this bug shortly.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1951363003/
