### ISSUE TITLE
Analyzer warns on using Function in assert

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#25613]
This:

``` dart
foo(Function f) {
  assert(f);
}
```

Produces:

```
[warning] Assertions must be on either a 'bool' or '() -> bool'
```

Not that anyone on Earth even uses the function argument to assert, but this is technically incorrect (the best kind of incorrect), since `Function` can be assigned to `() -> bool`. It's getting tripped up in `_checkForNonBoolExpression()` because `Function` is an interface type.

**Comment by bwilkerson** [comment]
This is now the correct behavior.
