### ISSUE TITLE
mixin_supertype_subclass3_test causes assertion failure in debug build of vm

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25617]
See https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-recipe-be/builds/11/steps/test%20vm/logs/stdio.

I will update the status file shortly.

**Comment by crelier** [comment]
Adding the relevant portion of the log before it disappears:

=== Failure summary:


FAILED: none-vm debug_x64 language/mixin_supertype_subclass3_test/02
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/class_finalizer.cc:1967: error: expected: aliased_mixin_type.IsFinalized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --supermixin --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-recipe-be/build/sdk/out/DebugX64/generated_tests/language/mixin_supertype_subclass3_test_02.dart
Took 0:00:00.841000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 language/mixin_supertype_subclass3_test/02


FAILED: none-vm debug_x64 language/mixin_supertype_subclass3_test/01
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/class_finalizer.cc:1967: error: expected: aliased_mixin_type.IsFinalized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --supermixin --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-recipe-be/build/sdk/out/DebugX64/generated_tests/language/mixin_supertype_subclass3_test_01.dart
Took 0:00:00.891000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 language/mixin_supertype_subclass3_test/01


FAILED: none-vm debug_x64 language/mixin_supertype_subclass3_test/03
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/class_finalizer.cc:1967: error: expected: aliased_mixin_type.IsFinalized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --supermixin --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-recipe-be/build/sdk/out/DebugX64/generated_tests/language/mixin_supertype_subclass3_test_03.dart
Took 0:00:00.768000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 language/mixin_supertype_subclass3_test/03


FAILED: none-vm debug_x64 language/mixin_supertype_subclass3_test/04
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/class_finalizer.cc:1967: error: expected: aliased_mixin_type.IsFinalized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --supermixin --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-recipe-be/build/sdk/out/DebugX64/generated_tests/language/mixin_supertype_subclass3_test_04.dart
Took 0:00:00.832000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 language/mixin_supertype_subclass3_test/04


FAILED: none-vm debug_x64 language/mixin_supertype_subclass3_test/05
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/class_finalizer.cc:1967: error: expected: aliased_mixin_type.IsFinalized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --supermixin --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-recipe-be/build/sdk/out/DebugX64/generated_tests/language/mixin_supertype_subclass3_test_05.dart
Took 0:00:00.724000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 language/mixin_supertype_subclass3_test/05



===
=== 5 tests failed
===
