### ISSUE TITLE
Analyzer doesn't emit proper warning for supertype of mixin

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25614]
In the text added to section 12 ("mixins") of the spec for DEP 34 (2c7234bd610bd5a99dd501da4ee59e78a33f1839), the following text appears:

> Let `M_A` be a mixin derived from a class `M` with direct superclass `S_static`.
> 
> Let `A` be an application of `M_A`. It is a static warning if the superclass of `A` is not a subtype of `S_static`.

In other words, given code:

```
class M extends S_static {}
class A = B with M;
```

If `B` is not a subtype of `S_static`, a warning should be issued.

Analyzer does not issue any such warning.

I will add a test demonstrating this bug shortly.

**Comment by askeksa-google** [comment]
Only relevant with the supermixins feature, but in that case, the check is still missing.

**Comment by MichaelRFairhurst** [comment]
failing 11 tests

**Comment by srawlins** [comment]
An error is reported now, and the spec has changed.
