### ISSUE TITLE
Extract method refactor doesn't handle references to local functions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25616]
Starting with the following file:

    class C {
      int f(int a) {
        int callback(int x) => x + a;
        int b = a + 1;
        int c = callback(b);
        int d = c + 1;
        return d;
      }
    }

Select the line `int c = callback(b);` and perform an "extract method" refactor.

Observed result:

    class C {
      int f(int a) {
        int callback(int x) => x + a;
        int b = a + 1;
        int c = extractedMethod(b);
        int d = c + 1;
        return d;
      }
    
      int extractedMethod(int b) {
        int c = callback(b);
        return c;
      }
    }

Which contains an undefined reference to `callback` in `extractedMethod`.

Expected result:

    class C {
      int f(int a) {
        int callback(int x) => x + a;
        int b = a + 1;
        int c = extractedMethod(callback, b);
        int d = c + 1;
        return d;
      }
    }

    int extractedMethod(int callback(int x), int b) {
      int c = callback(b);
    }

**Comment by scheglov** [comment]
https://codereview.chromium.org/1655353002/

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/b0c06a5827f3b9773cfa1c6acd97226f6d5e256f
