### ISSUE TITLE
Generic tearoff not working

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#25619]
We're not getting the right type on math.max below:

```dart
import 'dart:math' as math;
main() {
  takeFn(math.max/*<int>*/);
}
void takeFn(int fn(int a, int b)) {}
```

We're getting the following errors:

```
[error] Type check failed: math.max (<T extends num>(T, T) → T) is not of type (int, int) → int (/Users/vsm/git/dev_compiler/foo.dart, line 7, col 10)
[warning] The argument type '(T, T) → T' cannot be assigned to the parameter type '(int, int) → int' (/Users/vsm/git/dev_compiler/foo.dart, line 7, col 10)
1 error and 1 warning found.
```

**Comment by vsmenon** [comment]
@jmesserly Are we missing logic on tearoffs?

**Comment by jmesserly** [comment]
yeah this is basically the unimplemented case in https://github.com/dart-lang/sdk/issues/25175 ... we chatted about it, might be worth adding the downward inference here even though we don't support explicit instantiation yet.

The workaround would be: `(x, y) => max(x, y)` then inference should figure it out.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1644403005
