### ISSUE TITLE
Please merge https://codereview.chromium.org/1645423002/

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25618]

**Comment by johnmccutchan** [comment]
@iposva-google @whesse

**Comment by iposva-google** [comment]
This fixes issue #25602.

**Comment by whesse** [comment]
Shall we do a patch release with just this fix, or wait to see if we get more fixes coming in?

**Comment by mit-mit** [comment]
Let's patch stable now. CL is https://github.com/dart-lang/sdk/commit/ce650790a1446f205a49714b717b844eed6196fd

**Comment by whesse** [comment]
This CL is merged into version 1.14.1.

**Comment by johnmccutchan** [comment]
How about:

* Fixed VM crash when a debugger attempts to set a break point during
script loading.
