### ISSUE TITLE
No quick fix for `await for`

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25622]
I saw there is quick fix for `await`, it would may be nice to also have one for `await for`:

```
void main() {
  await for () {
    
  }
}
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1650853002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/3f7a21bc0eabde466b4fd2a514e59a30417b0825

**Comment by kasperpeulen** [comment]
thanks!
