### ISSUE TITLE
when quick fixing await also change the return type of the function

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25623]
When quick fixing this await to add the async modifier:

```
void main() {
  await 1;
}
```

It would be nice if the return type could change to `Future`

**Comment by scheglov** [comment]
https://codereview.chromium.org/1652963003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/86106d7a6d1ea479b6ec139d7c54e84f6630eede

**Comment by kasperpeulen** [comment]
Thanks :+1:
