### ISSUE TITLE
spurious typedef issue 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#25620]
The following test produces an error:

import "dart:async";
typedef Future<T> SyncedExecutionFn<T>(Future<T> fn());
main() {}

dart ~/tmp/y.dart 
'file:///y.dart': error: line 3 pos 1: typedef 'SyncedExecutionFn' illegally refers to itself
typedef Future<T> SyncedExecutionFn<T>(Future<T> fn());
^

**Comment by iposva-google** [comment]
Now with pointy brackets:
```
import "dart:async";

typedef Future<T> SyncedExecutionFn<T>(Future<T> fn());

main() {}
```

Thank you GitBug!
