### ISSUE TITLE
Error or crash when importing getter and setter from different libraries

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25626]
Attempting to import a getter named `x` and setter named `x=` from different libraries produces inconsistent results in dart2js.  If the imports are done directly, neither the getter nor the setter are imported; attempting to use either results in a runtime error such as `method not found: 'x'`. If the imports are done via an export, dart2js crashes with the message `The compiler is broken.`.

Even in the cases where dart2js doesn't crash, the behavior is incorrect.  There's nothing in the spec requiring a getter and its corresponding setter to be imported from the same library; the two entities have different names so they should not conflict with each other.

The VM and the analyzer also mishandle this situation, but not in the same way.

I will submit shared tests shortly demonstrating the bug.

**Comment by sigmundch** [comment]
removed the dart2js area - for dart2js this is now handled by the CFE. Leaving it open as it was also labeled area-analyzer.

**Comment by srawlins** [comment]
This probably has the same root cause as https://github.com/dart-lang/sdk/issues/23286

**Comment by srawlins** [comment]
The analyzer issue for this is https://github.com/dart-lang/sdk/issues/25624.
