### ISSUE TITLE
Code completing a function in a show list inserts function sig, not function name

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25629]
Consider this case:

![screen shot 2016-01-31 at 4 16 10 pm](https://cloud.githubusercontent.com/assets/5479/12706276/0812b2b6-c836-11e5-8513-a2b616df50bc.png)

This is what is inserted, if you use the UI to choose `helperFunction`

![screen shot 2016-01-31 at 4 16 03 pm](https://cloud.githubusercontent.com/assets/5479/12706280/13c1d272-c836-11e5-93a8-7eb738d5ff5c.png)

Expected: just insert the name `helperFunction` because we're in a `show` list here.

Note that code completion does insert the name for a class, typedef, and top-level variable into the `show` list.

Thanks for taking a look!

**Comment by sethladd** [comment]
cc @devoncarew because Atom

**Comment by danrubel** [comment]
The suggestion is an identifier not an invocation. My guess (unsubstantiated) is that Atom is not differentiating between an "invocation" suggestion and an "identifier" suggestion.

**Comment by devoncarew** [comment]
I think this is a dup of https://github.com/dart-atom/dartlang/issues/195.

**Comment by bwilkerson** [comment]
Seth, please re-open this issue if it isn't a duplicate.
