### ISSUE TITLE
Problems view reported undefined name, but name was not underlined

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25632]
Before reanalyze sources (notice how the incorrect name wasn't underscored, yet the problems view reports (correctly) the incorrect name)

![screen shot 2016-01-31 at 7 38 31 pm](https://cloud.githubusercontent.com/assets/5479/12708244/643d28ac-c852-11e5-97b0-ed015a68563e.png)

After reanalyze sources (notice how the incorrect name is no underscored)

![screen shot 2016-01-31 at 7 38 51 pm](https://cloud.githubusercontent.com/assets/5479/12708247/68ec0f6c-c852-11e5-96a8-94f099e1d831.png)

**Comment by sethladd** [comment]
cc @devoncarew because Atom but this is probably (??) an analyzer issue

Can I include any analyzer logs for you? If so, how do I grab them from Atom?

**Comment by bwilkerson** [comment]
@devoncarew Is Atom using the same data to populate the problems view and highlight text in the editor? If so, then this sounds like an Atom issue. If not, then perhaps server is reporting inconsistent results.

**Comment by devoncarew** [comment]
@sethladd, I don't believe there's a way to get the analyzer logs.

This could be an issue with the linter package; though the fact that reanalyze sources fixes it seems to indicate a problem with incremental analysis. Perhaps the source location is incorrect w/ incremental analysis, and the reanalyze sources fixes the location.

**Comment by bwilkerson** [comment]
> This could be an issue with the linter package; though the fact that reanalyze sources fixes it seems to indicate a problem with incremental analysis ...

I don't understand. The error was reported before reanalyze with the right line number and was reported after reanalyze with the same line number. If server is providing the same data, but the display is different, that would be on the Atom side, wouldn't it?

I have no idea whether the infos that disappeared after a reanalyze are valid or not, so I can't comment on them.

> Perhaps the source location is incorrect w/ incremental analysis, and the reanalyze sources fixes the location.

The source location appears to be the same (based on the line number in the error message).

**Comment by devoncarew** [comment]
The analysis server reports both char position, and line+column position. There have been cases in the past where these have gotten out of sync, generally as a result of issues in incremental analysis. I think this could be another case of the same.

**Comment by bwilkerson** [comment]
@scheglov Can you think of any reason why the line number / column number data would be out of sync with the offset?

**Comment by scheglov** [comment]
@bwilkerson Don't know. We perform complete scan during incremental resolution and replace the `LINE_INFO` analysis result. We might need to use instrumentation logs to track this problem down.

**Comment by bwilkerson** [comment]
@devoncarew Can you capture instrumentation logs the next time you see this occur?

**Comment by devoncarew** [comment]
@bwilkerson, I didn't report the issue :)

**Comment by bwilkerson** [comment]
Sorry, I meant the next time you see the offset be inconsistent with the line and column numbers.

**Comment by bwilkerson** [comment]
I'm not sure how to proceed on this issue without more information, such as the server communication logs or a reproduction case. Please re-open this issue if you can reproduce it.
