### ISSUE TITLE
Test freezes on Dartium 1.15.0-dev.0.0

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/sdk#25636]
Just create any barebone Dart lib with some tests. And run those tests as follows:
`$ pub run test -p dartium `
With Dartium 1.15.0-dev.0.0, it just freezes while it terminates as expected on Chrome and Firefox via dart2js.

Checked with 1.14.0 release, and it works fine.
I'm on Windows 10.

**Comment by zoechi** [comment]
Eagerly awaiting for the new Dartium to land in 1.15.0-dev :no_mouth:

**Comment by alan-knight** [comment]
I'm not sure if it's the same, but there's something broken on bleeding edge Dartium causing it to snap very frequently, and it may be related.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1653143002/  fixed my snapping problem and the bot failures, so with luck it also fixes this issue. We may need a cherry-pick to dev.

**Comment by dynaxis** [comment]
![untitled](https://cloud.githubusercontent.com/assets/570120/12781991/68bfe1ce-cabb-11e5-8b7b-b1cee3656baf.png)
Unfortunately dev.1.0 still has a problem. This time the test starts to run. But freezes as in dev.0.0.
I think spotted the commit @alan-knight mentioned above in dev.1.0 release, so it seems it didn't resolve this issue.

FYI, the above test I ran is from the skeleton of library generated by the latest WebStorm 12 EAP. So it should be easy to check if this problem is fixed or not.

```
library untitled1.test;

import 'package:untitled1/untitled1.dart';
import 'package:test/test.dart';

void main() {
  group('A group of tests', () {
    Awesome awesome;

    setUp(() {
      awesome = new Awesome();
    });

    test('First Test', () {
      expect(awesome.isAwesome, isTrue);
    });
  });
}
```
On VM, the same test passes w/o any problem as expected.

**Comment by alan-knight** [comment]
This was fine for me on bleeding edge a couple of days ago. There should be a new dev version now, so it may be fixed there.

**Comment by dynaxis** [comment]
In `1.15.0-dev.2.0`, the problem is still intact.
```
D:\msys64\home\dynaxis\work\untitled>pub run test -p dartium
00:00 +0: test\untitled_test.dart: A group of tests First Test
```

**Comment by alan-knight** [comment]
I think I'm seeing a different symptom now on both bleeding edge and dev.2, where I get a JS-interop related stack trace. Will look at that.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1683403005/

**Comment by kegluneq** [comment]
I was seeing similar symptoms that have cleared up in `1.15.0-dev.3.0`

**Comment by dynaxis** [comment]
I also tried it and found the problem is finally gone in `1.15.0.-dev.3.0`.

**Comment by alan-knight** [comment]
Great.
