### ISSUE TITLE
Refactor or Quick Fix: split long string to multiple lines

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25631]
Would _love_ the editor/analyzer's help to split a long string to multiple lines.

Consider:

![screen shot 2016-01-31 at 7 33 09 pm](https://cloud.githubusercontent.com/assets/5479/12708181/9bb1e026-c851-11e5-97a6-312372f4aa8c.png)

Imagine if I could Refactor or Quick Fix and split to multiple lines, at 80 chars, with adjacent strings.

I'd end up with:

![screen shot 2016-01-31 at 7 35 11 pm](https://cloud.githubusercontent.com/assets/5479/12708190/c800e758-c851-11e5-9f22-2f27ed1e14ee.png)

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew because Atom

**Comment by keertip** [comment]
Good idea, but very unlikely that we will get to it.
