### ISSUE TITLE
Please, clarify the yield* specification, regarding error handling.

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25634]
Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, chapter 17.16.2 Yield-Each reads:

> Execution of a statement s of the form yield\* e; proceeds as follows:
> First, the expression e is evaluated to an object o.
> If the immediately enclosing function m is marked sync\* (9), then:
> 1. It is a dynamic error if the class of o does not implement Iterable. Otherwise
> 2. The method iterator is invoked upon o returning an object i.
> 3. The moveNext method of i is invoked on it with no arguments. If moveNext
> returns false execution of s is complete. Otherwise
> 4. The getter current is invoked on i. If the invocation raises an exception ex,
> execution of s throws ex. Otherwise, the result x of the getter invocation
> is added to the iterable associated with m. Execution of the function m
> immediately enclosing s is suspended until the nullary method moveNext()
> is invoked upon the iterator used to initiate the current invocation of m,
> at which point execution of s continues at 3.
> 5. The current call to moveNext() returns true.

There is a number of places, where the outer code may throw an exception:
1. evaluation of expression e
2. invocation of method iterator
3. invocation of method moveNext
4. invocation of getter current
However, only the last case is described. Please, clarify all cases.

> If m is marked async\* (9), then:
> • It is a dynamic error if the class of o does not implement Stream. Otherwise
> • For each element x of o:
> – If the stream u associated with m has been paused, then execution
> of m is suspended until u is resumed or canceled.
> – If the stream u associated with m has been canceled, then let c be
> the ﬁnally clause (17.11) of the innermost enclosing try-ﬁnally state-
> ment, if any. If c is deﬁned, let h be the handler induced by c. If h is
> deﬁned, control is transferred to h. If h is undeﬁned, the immediately
> enclosing function terminates.
> – Otherwise, x is added to the stream associated with m in the order
> it appears in o. The function m may suspend.
> • If the stream o is done, execution of s is complete.

Please, clarify the case, when stream o finishes with error. 
Is this error propagated to stream u?

**Comment by alsemenov** [comment]
Please, also clarify whether the dynamic error, which occurs if the class of o does not implement Stream, is added to the stream u.

**Comment by alsemenov** [comment]
Please, also take in account a discussion in issue #25662

**Comment by lrhn** [comment]
When the function invocation ends with a thrown exception, one of two things happen:
* if the stream subscription has been cancelled, the error is used to complete the future returned by the `cancel` call.
* If the stream subscription has not been cancelled, the error is output on the stream as an error event, followed by a done event.

A "dynamic error" means an error object thrown at runtime, so it will terminate the function invocation - unless the error is caught by a try/catch or superseded by a try/finally.

From the spec:

> When *f* terminates:
> • If the current return value is defined then, if *s* has been canceled then its cancellation future is completed with *null* (16.2).
> • If the current exception *x* is defined:
>    – *x* is added to *s*.
>    – If *s* has been canceled then its cancellation future is completed with *x* as an error.
> • *s* is closed.

(It looks like *x* is added to *s* in all cases, but when the subscription has been cancelled, that's a no-op, and so is closing *s*).
