### ISSUE TITLE
Analyzer should lint about getter returning a function reference in a void context

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25638]
e.g. if I do:

``` dart
   void main() {
     print;
   }
```

...that should warrant at least a lint.

**Comment by srawlins** [comment]
Dup of #18849?

**Comment by bwilkerson** [comment]
I think #18849 is more general.

**Comment by srawlins** [comment]
Alright how about dup of https://github.com/dart-lang/sdk/issues/15710?

**Comment by srawlins** [comment]
dup of #15710
