### ISSUE TITLE
Specification of super expression assignment should be more clear

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25633]
Dart Language specification, 4th Edition (December 2015), "16.19 Assignment"

> Evaluation of an assignment of the form super.v = e proceeds as follows:
> Let g be the method currently executing, and let C be the class in which
> g was looked up. Let Sdynamic be the superclass of C. The expression e is
> evaluated to an object o. Then, the setter v = is looked up (16.15.2) in Sdynamic
> with respect to the current library. The body of v = is executed with its formal
> parameter bound to o and **this** bound to **this**.

"This bound to this" looks like a typo. It's better to clarify this statement. Something like "...this bound to this of class C"

**Comment by eernstg** [comment]
Closing: Resolved in the current specification (using `and \THIS{} bound to the current value of \THIS{}` like other, similar locations).
