### ISSUE TITLE
Analyzer exception

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25644]
While working on this project

https://github.com/bwu-dart-playground/dart_playground/blob/e961b050394d05cfd0a9fc4e4a4856c38c08fd80/angular2/template_syntax/lib/app_element.dart

and this folder

playground/dart_playground/blob/e961b050394d05cfd0a9fc4e4a4856c38c08fd80/angular2

opened in WebStorm

> Dart analysis server, SDK version 1.15.0-edge.d76fe1eacd91b354da1c8c9595f0fdc4bd5b2519, server version 1.14.0, error: Task failed: ComputeInferableStaticVariableDependenciesTask for element dynamic role in source /home/zoechi/dart/playground/angular2/template_syntax/lib/app_element.dart
> Failed to find the declaration of the variable role in /home/zoechi/dart/playground/angular2/template_syntax/lib/app_element.dart
> # 0      InferStaticVariableTask.getDeclaration (package:analyzer/src/task/dart.dart:3069)
> # 1      ComputeInferableStaticVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:1979)
> # 2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:318)
> # 3      AnalysisTask.perform (package:analyzer/task/model.dart:218)
> # 4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
> # 5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
> # 6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:657)
> # 7      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1224)
> # 8      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:666)
> # 9      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:40)
> # 10     AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:661)
> # 11     EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:157)
> # 12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
> # 13     _rootRun (dart:async/zone.dart:891)
> # 14     _CustomZone.run (dart:async/zone.dart:790)
> # 15     _CustomZone.runGuarded (dart:async/zone.dart:696)
> # 16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
> # 17     _rootRun (dart:async/zone.dart:895)
> # 18     _CustomZone.run (dart:async/zone.dart:790)
> # 19     _CustomZone.runGuarded (dart:async/zone.dart:696)
> # 20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
> # 21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
> # 22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> # 23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
> # 24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
> 
> java.lang.Throwable
>     at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
>     at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
>     at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
>     at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
>     at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
>     at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
>     at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
>     at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)

> Dart VM version: 1.15.0-edge.d76fe1eacd91b354da1c8c9595f0fdc4bd5b2519 (Mon Feb  1 19:54:21 2016) on "linux_x64"

**Comment by zoechi** [comment]
WebStorm 12 EAP

**Comment by bwilkerson** [comment]
I'm guessing that the content of the file has changed since this was posted because there is no definition of the variable `role`. If it didn't previously exist then I'd have to guess that analyzer has stale data (the list of variables whose type should be inferred).

**Comment by zoechi** [comment]
The link points to a specific commit, therefore it's probably as you said - stale data.
