### ISSUE TITLE
Update BoringSSL in Dart to more recent version

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25647]
The version of BoringSSL in Dart is from June 25, 2015, and it should be updated to the version currently used by Chromium (Dec 18 2015) or later.

@iposva-google @zanderso @rmacnak-google @sgjesse

**Comment by whesse** [comment]
The Dart CL is https://codereview.chromium.org/1653973006/

The patch is https://boringssl-review.googlesource.com/#/c/7030/

We still  need more testing, and to decide whether to use the upstreamed patch, or make a local patch that works.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request
