### ISSUE TITLE
Fixup "create method" sometimes assigns duplicate parameter names

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25650]
Starting with the code:

    class C {
      int x;
    }

    class D {
      foo(C c1, C c2) {
        bar(c1.x, c2.x);
      }
    }

Place the cursor on the identifier `bar` and select the "create method" fixup.

The code which is inserted has an error:

    void bar(int x, int x) { // Error: the name 'x' is already defined
    }

Expected behavior: the generated names should be adjusted so they are unique, e.g. by adding trailing digits, e.g.:

    void bar(int x1, int x2) {
    }

**Comment by scheglov** [comment]
https://codereview.chromium.org/1664423002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/960b9c34093b9f989074985360e7dbffe06b6318
