### ISSUE TITLE
error is in the wrong location for an undefined constant after edits above it

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25657]
To reproduce, copy this into a file in Atom:

```
// a comment

getName(PanelId id) {
  const panelNames = const <PanelId, String>{
    PanelId.note: "Notes",
    PanelId.tokens: "Tokens",
    PanelId.syntaxTree: "Syntax Trees",
    PanelId.javascript: "JavaScript",
    PanelId.output: "Output",
  };
  return panelNames[id];
}
```

Since PanelId is undefined, the following error appears underneath "PanelId" on lines 5 through 9:

'const' variables must be constant value

Now, add blank lines between the comment and the getName() function. For each line you add, the location of the error moves to the left by one character.

(Editing the comment has no effect. However, edits to whitespace within getName() do have an effect.)

Found via a stress test.

**Comment by bwilkerson** [comment]
@scheglov Is the incremental resolver used in this case?

**Comment by scheglov** [comment]
@bwilkerson Yes. I can reproduce the problem.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1667023002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/098d67330bdafb29f30f85e4c5fc906c75bdef24
