### ISSUE TITLE
`this` value differs between dart2js and Dartium when calling a JS function.

### ISSUE THREAD

**Issue by kseo** [dart-lang/sdk#25658]
I create a function `JsTest` and added `showThis` function to it. It simply prints `this` value to the console.

```js
(function (mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
      module.exports = mod();
  else if (typeof define == "function" && define.amd) // AMD
      return define([], mod);
  else // Plain browser env
      this.JsTest = mod();
})(function () {
  "use strict";

  function JsTest() {
  }

  JsTest.showThis = function (name, value) {
    console.log(this);
  };

  return JsTest;
});
```

On the Dart side, I declared `showThis` function with @JS annotation.

```dart
@JS('JsTest.showThis')
external void showThis();

void main() {
  showThis();
}
```

dart2js prints `function JsTest() {}` as I expected, but surprisingly Dartium prints `Window`.

**Comment by jacob314** [comment]
The dart2js behavior is correct.

**Comment by jacob314** [comment]
Verified that this was fixed a while ago. Regression test checked in here:
https://github.com/dart-lang/sdk/commit/bcf224b3e68924a1d5a76659063256cb8e6f32d0
