### ISSUE TITLE
Fix URL in the message 'Observatory listening on http://0.0.0.0:5858'

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25661]
I start Dart VM with the VM option `--enable-vm-service:5858/0.0.0.0` to make Observatory accessible from other computers in the local network. VM prints URL that is not valid:
```
Observatory listening on http://0.0.0.0:5858
```

I suggest to print 
```
Observatory listening on http://localhost:5858
```

**Comment by iposva-google** [comment]
"localhost" is definitely not the right thing to print here if the purpose is to connect from remote machines.

We could print the hostname. But even that can be slightly misleading as potentially a machine could be known under different names or IP addresses on different networks. However this is a rather rare case and usually has to do with only allowing access from a management network.

**Comment by johnmccutchan** [comment]
I think 0.0.0.0 is probably the best address to print here. 0.0.0.0 means all addresses on this machine. Which will at the very least include 127.0.0.1 and very likely at least one more address (your internet ip).

Regardless, pasting the link "http://0.0.0.0:5858/" into Chrome does the right thing and navigates me to Observatory.
