### ISSUE TITLE
No operators in outline

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25669]
Enter the following in a Dart file in IntelliJ:

    class C {
      int get getter => 0;
      C operator +(C other) => null;
      bool operator ==(C other) => false;
      int method() => 0;
    }

Note that 'getter' and 'method' both appear in the outline, but the operators do not. I think that they ought to. I don't know whether this is a server of IntelliJ issue, but I expect it's a server issue.

**Comment by scheglov** [comment]
IDEA does not use DAS outline.
It parses Dart code locally and uses ASTs for many features including outline.

The problem with parsing operators was fixed about 2 months ago.
![image](https://cloud.githubusercontent.com/assets/384794/12799253/b4b4b192-ca82-11e5-92e9-9898c905cf83.png)

**Comment by alexander-doroshko** [comment]
@bwilkerson Yep, operators in Structure View are shown in [WebStorm 12 EAP](https://confluence.jetbrains.com/display/WI/WebStorm+EAP) and [IntelliJ IDEA 16 EAP](https://confluence.jetbrains.com/display/IDEADEV/IDEA+16+EAP)
