### ISSUE TITLE
Remove Document.getCssCanvasContext and .supportsCssCanvasContext

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25664]
Chrome has dropped these, and it was the only browser supporting these.
The tests of them have already been removed.

**Comment by whesse** [comment]
If these dom functions are still in the dart:html library, they need to be removed.  That is what this bug is tracking.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by kevmoo** [comment]
@terrylucas @alan-knight Any thoughts on these?

**Comment by terrylucas** [comment]
```
This is in Chrome 45 (at least in the IDLs) so its in dart:html and in Dartium 1.16.

[CallWith=ScriptState, DeprecateAs=DocumentGetCSSCanvasContext] any getCSSCanvasContext(DOMString contextId, DOMString name, long width, long height);
```
For dart2js supportsCssCanvasContext will return false if the browser doesn't support it.  I'm assuming this is was removed in a Chrome version > 45?

**Comment by mit-mit** [comment]
Clearing milestone as no one seems to be working on this...

**Comment by kevmoo** [comment]
@terrylucas – removed 2+ years ago from Chrome - https://chromium.googlesource.com/chromium/src.git/+/24e58b0d8fab28fa20e69f191d833fe97aaff75d

**Comment by kevmoo** [comment]
Still in bleeding edge - https://api.dartlang.org/be/154776/dart-html/HtmlDocument/getCssCanvasContext.html

**Comment by terrylucas** [comment]
Fixed https://dart-review.googlesource.com/c/sdk/+/48381
