### ISSUE TITLE
Unexpected behavior when renaming member on a class which inherits from a different package

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#25666]
**Summary:**
Rename/refactor has some unexpected, and potentially unwanted, behavior when working 
with identifiers from a different package.

Specifically, in webstorm, if I have a class Foo that declares a member foo and 
inherits from class Bar, where Bar is declared in a different package and declares a member bar,
then I can rename foo to bar such that the renamed foo now shadows the bar identifier from Bar.

This is not otherwise allowed if I declare the class Bar in same package as Foo, and could
potentially change the program semantics.

**What steps will reproduce the problem?**
1) Create a package project 'awesome' in Webstorm. By default this project
exports the following class
```
class Awesome {
  bool get isAwesome => true;
}
```
2) Create a new simple command line project which imports the 'awesome' package.
Change the contents of main.dart to the following:
```
import 'package:awesome/awesome.dart';

class MoreAwesome extends Awesome {
  bool get isNotAwesome => false;
}

main(List<String> args) {
  print(new MoreAwesome().isAwesome);
  print(new MoreAwesome().isNotAwesome);
}
```
3) Use the rename function on the isNotAwesome identifier and rename it to isAwesome
What is the expected output? What do you see instead?
*Expected:*
An error should be displayed - Renamed field will shadow getter 'isAwesome'.

*Actual:*
'isNotAwesome' is renamed to 'isAwesome' and running the program will now yield
the output
```
    false
    false
```
where it would previously yield
```
    true
    false
```

**What version of the product are you using?**
Dart SDK-1.15-dev.1.0

This appears to be a change that was introduced in Dart-1.14,
and it has been verified that is does not occur in Dart-1.13.

**Comment by scheglov** [comment]
I started working on this problem a while ago, but I don't remember whether I was able to reproduce it or not. But I cannot reproduce it now, so probably it was fixed.

Adding a new test for this case.
https://codereview.chromium.org/2204263002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/30b24019073260d47824e3027b4a045f35087528
