### ISSUE TITLE
html/svgelement_test/PathElement fails on Chrome

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25665]
Started with the update to Chrome 48 on all platforms.
Currently suppressed in status file tests/html/html.status

Error is:
 <p>Expectation: 
                                <a href="#testFilter=PathElement pathSegList">
                                  PathElement pathSegList
                                </a>.
                              </p>
                              <pre>Test failed: Caught NullError: method not found: 'get$iterator' on null</pre>
                            </td>
                          </tr><tr><td></td><td colspan="2"><pre>http://127.0.0.1:60863/root_build/generated_compilations/dart2js-sdk/tests_html_svgelement_test/test.js 1739:166  main__closure.dart.main__closure.call$0
                    http://127.0.0.1:60863/root_build/generated_compilations/dart2js-sdk/tests_html_svgelement_test/test.js 17928:35  InternalTestCase.dart.InternalTestCase._testFunction$0

**Comment by alan-knight** [comment]
Test was obsolete, API removed. Fixed in https://codereview.chromium.org/2902973004/ 
(by deleting that particular test)
