### ISSUE TITLE
Strong mode inconsistencies with analysis server

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#25667]
Using strong mode in an IDE with analysis server can lead to unexpected results.  It appears to be mixing and matching strong analysis contexts with non-strong ones.

@bwilkerson is working on a proper fix.

**Comment by vsmenon** [comment]
Marking as critical as this breaking folks using strong mode in an IDE.  If a real fix will take a while, we may need a workaround.

**Comment by vsmenon** [comment]
Investigating a workaround.  @bwilkerson is working a real fix, but it'll probably be a week or so.

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://codereview.chromium.org/1686613002/.
