### ISSUE TITLE
Creating a instance of JS annotated class differs between dart2js and Dartium

### ISSUE THREAD

**Issue by kseo** [dart-lang/sdk#25660]
I created a JavaScript function which shows the passed `obj` on the console.

```js
function show(obj) {
  console.log(obj);
}
```

On Dart side, I decalred `JsObject` class with `@JS` and `anonymous` annotation to make it JavaScript object.

```dart
@JS()
@anonymous
class JsObject {}
```

dart2js creates an  instance of `JsObject` as a plain JavaScript object, while Dartium creates a opaque instance with its prototype chain pointing to `DartObject`.

```dart
void main() {
  final jsObj = new JsObject();
  show(jsObj);
}
```

If a class is not annotated with `@JS`, both dart2js and Dartium correctly create a Dart object.

```dart
class DartObject {}

void main() {
  final dartObj = new DartObject();
  show(dartObj);
}
```

**Comment by jacob314** [comment]
Making console log consistent in dart2js and dartium is a non-goal. Dartium goes to great lengths to try to make Dart objects debug-able but dart2js doesn't as deployed performance is more important.
