### ISSUE TITLE
Wrong implementation of noSuchMethod() can be called

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25671]
Dart Language Specification 4-th Edition (December, 2015), "16.19 Assignment"
> Evaluation of an assignment of the form super.v = e proceeds as follows:
> ...
> Then the method noSuchMethod() is looked up in Sdynamic and invoked
with argument im. However, if the implementation found cannot be invoked
with a single positional argument, the implementation of noSuchMethod() in
class Object is invoked...

But if there is an implementation of noSuchMethod() that cannot be invoked with a single positional argument it is invoked anyway. Example:
```dart
class A {
  noSuchMethod() { /// static type warning
    throw new Exception("Wrong noSuchMethod() should not be called");
  }
}
class C extends A {
  test() {
    super.v = 1; /// static type warning
  }
}
main() {
  C c = new C();
  c.test();
}
```
In this example noSuchMethod() is called and Exception is thrown. When it is not super.v = e assignment then everything works as expected. For example:
```dart
class C {
  noSuchMethod() {  /// static type warning
    throw new Exception("Wrong noSuchMethod() should not be called");
  }
}
main() {
  C c = new C();
  try {
    c.v = 1;
  } on NoSuchMethodError catch(e) {
    print("Expected");
  }
}
```
This code works well ("Expected" printed)
Tested on Dart VM version: 1.15.0-dev.0.0 (Thu Jan 28 11:10:53 2016) on "windows_x64"

**Comment by lrhn** [comment]
Dart 2 makes it a compile-time error to have a `noSuchMethod` that cannot be called with a single argument of type `Invocation`, so that failure mode is gone.

Also, a super-invocation that is not targeting a non-abstract implementation is also a compile-time error, so that too is moot.
