### ISSUE TITLE
Dart should error when attempting to `show` a symbol not defined in a package.

### ISSUE THREAD

**Issue by DavidSouther** [dart-lang/sdk#25672]

**Comment by zoechi** [comment]
dup of #21030

**Comment by DavidSouther** [comment]
No, #21030 is for including symbols that are present, but unused. There should be an error when a symbol is shown, but does not exist in the imported source.

**Comment by bwilkerson** [comment]
The current semantics are described in the specification (section 18.1) by

> Note that no errors or warnings are given if one hides or shows a name that is not in a namespace. This prevents situations where removing a name from a library would cause breakage of a client library.

We could add a hint for this case, but it's not clear how useful it would be. The number of times when a name is shown when that name does not exist, and that do not cause other warnings when the name is used in code, seems fairly small. Are you running into this case often, and if so, how?

**Comment by DavidSouther** [comment]
I expect locality of errors. If a library has removed a symbol, the error is more useful when near the import than when buried in the middle of unrelated code.

**Comment by srawlins** [comment]
CR out for review: https://codereview.chromium.org/1901923002/

**Comment by srawlins** [comment]
New analyzer hints UNDEFINED_SHOWN_NAME in 53bf36acdb4a6a12addf15eba06eacdab7552f22.
