### ISSUE TITLE
Create N missing overrides fix sometimes creates Dart code that doesn't compile

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#25686]
Start with the code below with an empty body of the class B.  Perform the fix associated with the  error on B (missing overrides), then run the action to "Create 3 missing overrides", the code below is what comes out, "var" is missing on "d", which does not compile.

```
abstract class A {
  static var a, b, c;
  var d;
  int i;

  one();

}

class B implements A {
  
  d;

  int i;

  @override
  one() {
    // TODO: implement one
  }
}
```

**Comment by jwren** [comment]
1.14.0-dev.7.2

**Comment by jwren** [comment]
1.14.0-dev.7.2

**Comment by scheglov** [comment]
https://codereview.chromium.org/1668273002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/fb520065b8966793aff7c93dffc5135e822d7ae6
