### ISSUE TITLE
Provide a way to enable a source-location suppression of an error/warning

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25685]
@bwilkerson to provide details...

**Comment by pq** [comment]
Related to or dup of: https://github.com/dart-lang/sdk/issues/12490

**Comment by bwilkerson** [comment]
Yes, it's related, but there's been no movement on that issue for years, so we're going to implement something analyzer specific.

Given that annotations cannot be placed everywhere we want, we're probably looking at a special comment "syntax", maybe something like "//#suppress MISSING_OVERRIDE". Details of the format TBD.

**Comment by alexander-doroshko** [comment]
FYI, how it works in IntellJ IDEA for Java.
Assume we have a warning about potential NullPointerException:
![image](https://cloud.githubusercontent.com/assets/4499789/12845374/57b63a2a-cc16-11e5-97d8-2063237735e8.png)

There are some quick fixes available:
![image](https://cloud.githubusercontent.com/assets/4499789/12845408/915bb52a-cc16-11e5-84ef-3d8bb8e23bea.png)

If we do not want to change code but only want to get rid of warning highlighting in the IDE there are 2 ways to suppress the warning: annotation and comment. IDE suggests both in a quick fix submenu:
![image](https://cloud.githubusercontent.com/assets/4499789/12845478/347db42e-cc17-11e5-8bc0-97d34e38464c.png)

So we can suppress the warning for statement with annotation:
![image](https://cloud.githubusercontent.com/assets/4499789/12845508/5ede6862-cc17-11e5-9787-c74bff3a1be8.png)

.. or with comment:
![image](https://cloud.githubusercontent.com/assets/4499789/12845522/78fdc850-cc17-11e5-9b7f-439cbd3484b6.png)

In some context where annotation is not allowed by Java syntax, suppression with comment is the only possible way.
Note that it is possible to suppress warning at different level: for statement, for the whole method or for the whole class. Suppression for the whole method or class is possible with annotation only, not with a comment.

**Comment by bwilkerson** [comment]
Good to know, thanks!

My inclination would be to start with a comment form because of the fairly severe limitations on the use of annotations in Dart. (For example, you can't place an annotation on a statement unless the statement is declaring a local variable or local function.)

**Comment by alexander-doroshko** [comment]
> For example, you can't place an annotation on a statement unless the statement is declaring a local variable or local function.

The same in Java. Usually we suppress warnings for individual statement with comment (and usually it is the only possible way for statement), but for the whole method or class - annotation is the only way.

**Comment by pq** [comment]
Thanks for all the comments!

After some conversations with @Hixie, I think we really need the fine granularity of line-level suppressions.  Annotations may be handy for suppression at the larger block level.  If we go that route, we should discuss adding the appropriate annotation to `meta` (see: https://github.com/dart-lang/sdk/issues/25741).

To start, I'm running with Brian's proposed format (`//# ...`) but am open to other ideas.  Let the bike-shedding begin! :wink:

**Comment by alexander-doroshko** [comment]
Does anybody know any existing format of suppressing warning with comments?
The only one I know is IntelliJ IDEA's one:
```
//noinspection WARNING_CODE
```
If there are several warnings in one statement they can be suppressed with comma-separated list:
```
//noinspection WARNING_CODE_1,WARNING_CODE_2
```
Spaces count is not strictly defined, any text at the end is allowed. The following is treated the same as above:
```
//    noinspection    WARNING_CODE_1    ,    WARNING_CODE_2    just because
```

**Comment by Hixie** [comment]
The syntax we use in flutter is:
`// analyzer says "..."`
...where `...` is a substring of whatever the analyzer message is.

I like this because it's aesthetically pleasing and self-documenting (you see the message right there). Things like "//noinspection" are ugly.

**Comment by alexander-doroshko** [comment]
> // analyzer says "..."

Wording may change without changing the warning meaning. I wouldn't like to force all users to revisit all suppressions in code on each SDK update.

**Comment by Hixie** [comment]
That's certainly an issue with that approach.

**Comment by bwilkerson** [comment]
The wording almost certainly will change. There is an active (but background) task to improve error messages, to share those messages across multiple tools, and to provide unique error codes both for purposes like this and to make it easier to search for documentation about those messages (https://github.com/dart-lang/sdk/blob/master/pkg/dart_messages).

One unfortunate consequence of this effort is a move from more readable message id's like `CONST_CONSTRUCTOR_WITH_BODY` to `LGJGHW`, which will make readable annotations less readable:

// analyzer says LGJGHW

**Comment by Hixie** [comment]
We could have:
```dart
// analyzer says "..." (LGJGHW)
```
...where we ignore errors on lines that have the form "// analyzer says .+ (...)" where "..." matches the code.

**Comment by zoechi** [comment]
I'd like to have some indication that it is not just a comment like the `#` mentioned above

```dart
// # LGJGHW Arbitrary ignored text
```
mouseover to reveal the full message would be great :smile: 

Is it fine to have one suppression per line?

Should inline comments `/* # LGJGHW Arbitrary ignored text */` also be supported? 

What about ranges?

```dart
// # start LGJGHW Arbitrary ignored text
lots of code
// # end LGJGHW Arbitrary ignored text
```

**Comment by zoechi** [comment]
A pre-commit hook (or similar) could lookup the long error message and insert it after the error code to always keep it up-to-date

**Comment by sethladd** [comment]
Design doc from @pq https://docs.google.com/document/d/1YJCkxnklLR2aKzQUrp6cWmqk7yUhfJwtaXIGcjZIk-Y/edit

**Comment by pq** [comment]
Bike-shedding doc [here](https://docs.google.com/document/d/1YJCkxnklLR2aKzQUrp6cWmqk7yUhfJwtaXIGcjZIk-Y/edit?usp=sharing).

Currently implemention supports single suppressions like so:
```
// ignore: invalid_assigment
int x = ‘’;   
```
and multiples like this:
```
// ignore: invalid_assignment, const_initialized_with_non_constant_value
const x = y; 
```

**Comment by pq** [comment]
Landed in https://github.com/dart-lang/sdk/commit/51188b660192dad2bfed14d53a275639ba9ed8af.

**Comment by pq** [comment]
And voila.

![screen shot 2016-02-26 at 10 32 08 am](https://cloud.githubusercontent.com/assets/67586/13361565/50f69db0-dc74-11e5-80e8-25b8d6ecd6a0.png)

... drumroll ...

![screen shot 2016-02-26 at 10 32 14 am](https://cloud.githubusercontent.com/assets/67586/13361567/601844e2-dc74-11e5-9b51-70ae44fd5ab1.png)

Look ma, no warning!

**Comment by devoncarew** [comment]
\o/

**Comment by zoechi** [comment]
\o/ 
Who creates the follow-up issue for quick fixes? So you guys don't run out of work ;-)

**Comment by pq** [comment]
> Who creates the follow-up issue for quick fixes? So you guys don't run out of work ;-)

I think you just volunteered! :)

Feel free to assign it to me.  I'd love to see that happen.

**Comment by zoechi** [comment]
Is there some hint when there is nothing to suppress?

**Comment by pq** [comment]
Request tracked here: https://github.com/dart-lang/sdk/issues/25917

**Comment by csga5000** [comment]
Is there someplace that documents all the valid ignore keys?

I can't figure out for the life of me how to ignore an unused function

EX:
```
void _deleteDatabase() async {
}
```

**Comment by csga5000** [comment]
Oh, I see that if I use flutter analyze it shows the key. (I don't think vscode does anywhere, I'm going to open an issue there)

**Comment by bwilkerson** [comment]
IntelliJ provides a quick-fix to add the comment for you. VS Code might, but I don't have it running on my machine so I can't check.

**Comment by csga5000** [comment]
I don't think it does, the "show fixes" menu doesn't include any sort of "suppress warning" option.

Tracking here: https://github.com/Dart-Code/Dart-Code/issues/890

**Comment by DanTup** [comment]
@bwilkerson Is IntelliJ doing this itself? I was just about to comment on the other issue asking if it makes sense in the server or should I try to do it in the editor?

**Comment by zoechi** [comment]
There are several errors/warnings where no suppression quick-fixes are offered. That's quite cumbersome because the error message also doesn't include the code.

https://stackoverflow.com/a/35969635/217408 contains links to Dart source with the codes

**Comment by DanTup** [comment]
In Dart Code we have an option (`dart.showLintNames`) that prefixes the names onto lints/hints (presumably you can't ignore warnings/errors?), but not sure if IntelliJ has the same.

**Comment by zoechi** [comment]
I'm not aware of such an option in IntelliJ, but it would be quite helpful.

**Comment by bwilkerson** [comment]
> Is IntelliJ doing this itself?

I'm not sure, but I'm not seeing anywhere where server is doing this, so it might be.

@scheglov @jwren 

If so, is there a reason why this isn't being done in server? It certainly seems like it ought to be done there.

**Comment by DanTup** [comment]
That was my thinking too. It's be great functionality for all clients to get for free :)

Ofc, if it is added, we need to ensure IntelliJ wouldn't show its own at the same time.

**Comment by pq** [comment]
I know I implemented this in server a while back but maybe never landed it.  I think it was politics.  Anyway, I'm 100% in favor of adding it (back) in.

**Comment by jwren** [comment]
My understanding: politics prevented us from having error and warning suppression in the server.  Users wanted it so Alex put in the functionality into the Dart Plugin.

**Comment by bwilkerson** [comment]
We ought to be past that point, so we should be able to move the functionality into server.

**Comment by DanTup** [comment]
Should we re-open this then? :)
