### ISSUE TITLE
pub build should not modify pubspec.lock

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25688]
This broke both Flutter and Mojo when they upgraded to Dart 1.14 and is a regression from 1.13.

$ ls -l pubspec.lock
-rw-r----- 1 johnmccutchan eng 9.6K Feb  4 12:54 pubspec.lock
$ pub build
...
$ls -l pubspec.lock
-rw-r----- 1 johnmccutchan eng 9.6K Feb  4 12:57 pubspec.lock

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub#1388
