### ISSUE TITLE
dart2js_extra/deferred_custom_loader_test fails in csp mode on browsers

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25683]
The test dart2js_extra/deferred_custom_loader_test, located at tests/compiler/dart2js_extra/deferred_custom_loader_test.dart, is failing
when run on linux content_shell in CSP mode, proabably for obvious reasons.

If this is expected, then the status should be changed to SkipByDesign, as it is for the deferred_fail_and_retry_test.

I'm doing that now, marking it SkipByDesign, with this issue number cited.
So if this is as expected, and not going to change, just close the issue and leave the status
unchanged.

Here is the error:
FAILED: dart2js-drt-checked release_ia32 dart2js_extra/deferred_custom_loader_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:
CONSOLE ERROR: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

CONSOLE MESSAGE: line 78: {
  "type": "window_onerror",
  "value": "window.onerror called: \n\nhttp://127.0.0.1:52467/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_deferred_custom_loader_test/test.js:5045:\nUncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src 'self'\".\n\n\n",
  "timestamp": 0.087

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rdrt -aia32 --use-sdk --write-debug-log --write-test-outcome-log --clear_browser_cache --minified --dart2js-batch --csp --checked -t480 dart2js_extra/deferred_custom_loader_test

**Comment by sigmundch** [comment]
thanks bill, skip by design sgtm.
