### ISSUE TITLE
Add ability define dart:* libraries via _embedders.yaml

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25687]
* [x] Add embedded libs to sky engine build (https://github.com/flutter/flutter/issues/1712)
* [x] Specify flutter libs in `_embedder.yaml` (https://github.com/flutter/flutter/issues/523)

**Comment by devoncarew** [comment]
Clarified with @pq, this is for embedders to essentially be able to define their flavor of SDK.

@pq, can you remove the text in the first comment and replace with sub-issue check boxes?

**Comment by pq** [comment]
> @pq, can you remove the text in the first comment and replace with sub-issue check boxes?

First cut done.

@abarth : let me know if we have or need an issue to track publishing sky engine.

**Comment by pq** [comment]
I think w/ @johnmccutchan's work we can call this done?

**Comment by johnmccutchan** [comment]
yep
