### ISSUE TITLE
dartanalyzer reports the same error multiple times when given multiple entry points

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25697]
To reproduce, create three files:

entry1.dart

```
import "target.dart";

main() {
  print(x);
}
```

entry2.dart

```
import "target.dart";

main() {
  print(x);
}
```

target.dart

```
var x = 3;

asdf
```

Then run dartanalyzer on both entry files:

```
$ dartanalyzer entry1.dart entry2.dart 
```

It will analyze them sequentially and print the same error twice. If given a lot of files (for example using a glob) then you get lots of duplicates.

**Comment by skybrian** [comment]
This is also true when using --machine.

**Comment by nex3** [comment]
Can we increase the priority on this? It's very frustrating when dealing with large packages, especially when they have a couple intended hints (for example, many packages refer to their own deprecated members). Passing `dartanalyzer lib/` should be the recommended way of analyzing all the libraries in a package, but it can drown the user in duplicate errors which makes it very painful in practice.

**Comment by devoncarew** [comment]
This is still on track for 1.23; it's about a day of work. I can get to it; @danrubel has also said that an upcoming refactoring he's considering may also cover this issue.

**Comment by dgrove** [comment]
@devoncarew any update on this?

**Comment by devoncarew** [comment]
Still planned. I see that the milestone for 1.23 is targeted to March 29th; is that accurate?

**Comment by dgrove** [comment]
Thanks! That's the correct day.

**Comment by devoncarew** [comment]
Annnnnd, bumping to the next milestone.

**Comment by devoncarew** [comment]
https://codereview.chromium.org/2793813002/

**Comment by devoncarew** [comment]
fixed in master
