### ISSUE TITLE
dartium becomes unresponsive when no DevTools is open and there is a break point set

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/sdk#25699]
Symptom:
No response, wait or force quit message from dartium.

Cause:
A break point and a few things.

How to reproduce:
1)Set a breakpoint in dartium Developer Tools by right clicking a line number.
AND
2)Close Developer tools and keep it closed
AND
3)Restarted dartium and visit the same page containing a break point.

Version: 1.14.0

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
