### ISSUE TITLE
Annotation referring to named constructor with prefix has incorrect element

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25706]
Given an annotation like `@prefix.className.constructorName(...)`, resolution sets `Annotation.element` to point to the ClassElement for `className`.  This is incorrect; it should point to the ConstructorElement for `constructorName`.

**Comment by stereotype441** [comment]
A similar problem occurs for annotations like `@prefix.className.staticVariable`.

**Comment by scheglov** [comment]
I can reproduce the problem with `@prefix.className.staticVariable`.
But `@prefix.className.constructorName()` works for me.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2376463002
I've added tests for these two cases and other cases.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/85d3aff2595f4b9419d3693736c928fdf1ab5a73
