### ISSUE TITLE
fix codegen of subexpressions under `new #` templates

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25708]
We seem to be generating incorrect code for JS templates of the form `new #()`. These are used in the the [JsObject constructor][1] from `dart:js`. The CPS IR incorrectly generates code like this:

```js
return P._wrapToDart(new P._convertToJS(J.$index$asx($.$get$context(), "foo"))());
```

Instead of code like:
```js
var foo = P._convertToJS(J.$index$asx($.$get$context(), "foo"));
return P._wrapToDart(new foo());
```
or even:
```js
return P._wrapToDart(new (P._convertToJS(J.$index$asx($.$get$context(), "foo")))());
```

This is the reason behind these failing tests:
```
js_test/JsObject_methods
js_test/new_JsObject
```

Here is a simplified repro:
**repro.dart:**
```dart
import 'dart:js';
main() => new JsObject(context['foo']);
```

**repro_extra.js:**
function foo() {}

Then running this will throw an error like those seen in the tests above
third_party/d8/linux/d8 sdk/lib/_internal/js_runtime/lib/preambles/d8.js repro_extra.js out.js

[1]: https://github.com/dart-lang/sdk/blob/010e0e6b71364c80ae02549fa3a23c1946e8b0ba/sdk/lib/js/dart2js/js_dart2js.dart#L151

**Comment by asgerf** [comment]
Nice catch.

Seems like the js_ast printer uses the wrong precedence when descending into the callee of a 'new'. Should be an easy fix.
