### ISSUE TITLE
Archive symbol information for binaries in dart-sdk in addition to stripped binaries

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#25701]
Our dartsdk builders only archive stripped binaries. Sometimes it would be really helpful to get the symbol information when debugging issues.

A common way, on linux at least, is to extract the symbol information from the executable into another file. Gdb can be told to load symbols from a different file. [This](http://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target) shows how one can do that under linux. Not sure about MacOS.

@whesse

cc @ricowind

**Comment by whesse** [comment]
Great idea.  Let's do it.  File an issue on infra.

On Fri, Feb 5, 2016 at 12:14 PM, Martin Kustermann <notifications@github.com
> wrote:

> Our dartsdk builders only archive stripped binaries. Sometimes it would be
> really helpful to get the symbol information when debugging issues.
>
> A common way, on linux at least, is to extract the symbol information from
> the executable into another file. Gdb can be told to load symbols from a
> different file. This
> <http://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target>
> shows how one can do that under linux. Not sure about MacOS.
>
> @whesse <https://github.com/whesse>
>
> cc @ricowind <https://github.com/ricowind>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25701>.
>



-- 
William Hesse
