### ISSUE TITLE
Archive arm dartsdks on every revision

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#25702]
Currently the dartsdk builders do not seem to archive arm sdk zip files.

The dartsdk bundles can be found e.g. here for a bleeding edge revision and it is **missing** an arm version:

``` bash
$ gsutil ls gs://dart-archive/channels/be/raw/136190/sdk/
...
```

Same is true for all builders, also for stable (see `gs://dart-archive/channels/stable/raw/1.14.1/sdk`). There is also no support for that in the [GCSNamer](https://github.com/dart-lang/sdk/blob/master/tools/bots/bot_utils.py#L186).

But they suddenly appear in the promoted `release` folder. Comparing the timestamps on them (e.g. `gsutil ls -lh gs://dart-archive/channels/stable/release/1.14.1/sdk`) it looks like they are uploaded from the side from somewhere else. From where?

@whesse Can't we have dartsdks for arm be archived as everything else on each revision?

Some context: Dartino is using DartVM binaries from specific revisions (sometimes from bleeding edge) and we have to get the binary for linux/linux-arm/mac/windows. So for now we need to log into the buildbot to get them, since they don't seem to be automatically archived.

cc @ricowind

**Comment by whesse** [comment]
Yes, this is clear, we need to create the SDK on the builders rather than creating one afterwards by a hack.

**Comment by athomas** [comment]
Fixed.
