### ISSUE TITLE
Specification: setters of class Object are mentioned

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25700]
Dart Language Specification, 4-th Edition (December 2015), "16.19 Assignment"

> It is a compile-time error to invoke any of the setters of class Object on a
> prefix object (18.1) or on a constant type literal that is immediately followed
> by the token ‘.’.

Class Object, defined in dart:core, does not have any setters, so the statement above has no sense

**Comment by eernstg** [comment]
Closing, dartLangSpec.tex does not refer to setters of class Object at this point.
