### ISSUE TITLE
Please merge revision 600940f18ff8c1d555896fbe9038139457491a59 into stable channel

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25705]
@ricowind @whesse @kasperl

This fixes dart-lang/pub#1386.

The revision is 600940f18ff8c1d555896fbe9038139457491a59.

This merged cleanly.

**Comment by whesse** [comment]
Note this fixes a bug that was introduced in 1.14, and has been hit by external users.  So I think we definitely need to make a release.

**Comment by kevmoo** [comment]
:metal:

**Comment by mit-mit** [comment]
LGTM

**Comment by whesse** [comment]
Merged in 1.14.2
