### ISSUE TITLE
Please merge revision ca7ee2b6cd6f589d488eb761c1857428df027f7e into stable channel

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#25718]
@whesse @mit-mit @kasperl
This fixes fix EOF detection when reading an entire file from some special files. Issue: https://github.com/dart-lang/sdk/issues/25596

Please merge: ca7ee2b6cd6f589d488eb761c1857428df027f7e

This merged cleanly.

**Comment by mit-mit** [comment]
LGTM

**Comment by whesse** [comment]
Merged in 1.14.2
