### ISSUE TITLE
Please merge 1e6c5f196befa21b26b3bd40877167691ee9c346 into stable channel

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25721]
Hi,

Please merge 1e6c5f196befa21b26b3bd40877167691ee9c346 into the stable channel.

Thanks,
John

**Comment by johnmccutchan** [comment]
@whesse @mit-mit

**Comment by johnmccutchan** [comment]
This is required for Atom's debugger to work robustly.

**Comment by whesse** [comment]
This CL did not merge cleanly into stable.  I have created https://codereview.chromium.org/1681903002/ as a proposed merge.  Please review it, before we commit the new stable 1.14.2.

**Comment by whesse** [comment]
Because there is no version of the service protocol that includes these changes but not other unrelated ones, we are not merging this to stable.  The users hitting this are OK using 1.15.0-dev instead.
