### ISSUE TITLE
Please merge 834b3f02b6ab740a213fd808e6c6f3269bed80e5 into stable and dev

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#25729]
This fixes an ancient bug in the code generation on x64 that can cause weird errors due to incorrect codegen for `identical(...)`.

834b3f02b6ab740a213fd808e6c6f3269bed80e5

/cc @whesse

**Comment by whesse** [comment]
We are not in cherry-pick season on dev.

**Comment by whesse** [comment]
Merged in 1.14.2
