### ISSUE TITLE
Documentation: typo in DateTime.toIso8601String() specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25728]
Please see https://api.dartlang.org/1.14.1/dart-core/DateTime/toIso8601String.html

> mmm are microseconds in the range 000 to 999, and
> uuu are microseconds in the range 001 to 999. If microsecond equals 0, then this part is omitted.

mmm are **milliseconds**, not microseconds

**Comment by floitschG** [comment]
Thanks.
Updated the documentation in 381c12df4ade7cfe67aedd391a1896072a6fc799
