### ISSUE TITLE
Build-in deferred identifier is permitted as type parameter and type alias.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25732]
According to Dart Language specification (4th edition, Dec 2015) "16.33 Identifier Reference":

"It  is  a  compile-time  error  if  a  built-in  identifier  is used as the declared name of a prefix, class, type parameter or type alias."

However, dart compiles successfully tests below, while analyzer reports error.

``` dart
class A<deferred> {
  bool check(x) => x is deferred;
}
main() {
  new A().check(null);
}
```

``` dart
typedef int deferred();
main() {
  try {
    null is deferred;
  } catch (anything) {
  }
}
```

**Comment by floitschG** [comment]
@gbracha: Both implementations (VM and dart2js) accept the code.
We can either fix them, or change the spec and the analyzer and be more lenient. (There shouldn't be harm in recognizing `deferred` specially if it is used in the `import` line.

**Comment by askeksa-google** [comment]
Works in Fasta. This is tested in several tests in `co19/Language/Expressions/Identifier_Reference/`.
