### ISSUE TITLE
Build-in identifiers are permitted as prefix.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25733]
According to Dart Language specification (4th edition, Dec 2015) "16.33 Identifier Reference":

"It is a compile-time error if a built-in identifier is used as the declared name of a prefix, class, type parameter or type alias."

However, dart compiles successfully test below.

``` dart
library lib;
var x = 1;
```

``` dart
import "lib.dart" as abstract;
main() {
  abstract.x;
}
```

The same is true for other build-in identifiers: as, deferred, dynamic, export, external, factory, get, implements, import, library, operator, part, set, static, typedef.

**Comment by floitschG** [comment]
Dart2js and analyzer don't complain either.
I'm not sure, if there are corner-cases where a prefix with a built-in identifier would hurt.
