### ISSUE TITLE
Dart language spec permits to use dynamic as a type parameter.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25734]
According to Dart Language specification (4th edition, Dec 2015) "16.33 Identifier Reference":

"It is a compile-time error to use a built-in identifier other than dynamic as a type annotation or type parameter."

It is not clear how to use dynamic as a type parameter. May be instead of ' type parameter' should be
'type of parameter'? Please clarify.

**Comment by zoechi** [comment]
Generic type parameter I guess `List<dynamic>`

**Comment by munificent** [comment]
@zoechi is correct. :)
