### ISSUE TITLE
Analyzer crashes when trying to use mixin application constructor in const fashion

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25738]
The following code crashes analyzer:

    class B {
      const B();
    }

    class C = B with M;

    class M {}

    const x = const C();

    main() {
      print(x);
    }

The spec seems to imply that the implicitly defined constructor for `C` is non-const, so this code should generate a compile-time error.  Both dart2js and the VM behave consistently with this interpretation.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1711673003/
