### ISSUE TITLE
Can't use mixins with classes that have named arguments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25742]
In Flutter we use named arguments heavily. The fact that we can't use mixins when the superclass has named arguments is a major problem that keeps getting in our way.

It's not clear why named arguments would be a problem. Just forward the constructor "super" call past the mixin.

**Comment by lrhn** [comment]
I assume it's the superclass constructors that can't have named parameters?

It seems like an oversight that only constructors with no optional parameters (positional or named) are forwarded. I can't see a practical problem preventing it.

**Comment by Hixie** [comment]
```dart
class A { A({ bool hello }); }
class B { }
class C extends A with B { }
```
=> `This mixin application is invalid because all of the constructors in the base class 'A' have optional parameters.`

**Comment by floitschG** [comment]
Duplicate of
https://github.com/dart-lang/sdk/issues/19226
https://github.com/dart-lang/sdk/issues/17610

and ultimately
https://github.com/dart-lang/sdk/issues/15101

Also dart2js supports it (contrary to the spec, but showing that implementation wise it's feasible), but the VM doesn't.

**Comment by Hixie** [comment]
See https://github.com/dart-lang/sdk/issues/31543 for the current status of this bug.
