### ISSUE TITLE
Microtasks are no longer dispatched after a runtime syntax error

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25745]
If a syntax error is encountered at runtime, it's _not_ detected synchronously while `main()` is on the stack, and the isolate recovers using `Isolate.setErrorsFatal(false)`, microtasks in that isolate will cease to be dispatched. For example:

``` dart
import 'dart:async';
import 'dart:isolate';

void badFn() {continue;}

void main() {
  var errorPort = new ReceivePort();
  Isolate.current.setErrorsFatal(false);
  Isolate.current.addErrorListener(errorPort.sendPort);
  errorPort.listen((message) {
    print("caught error");
    Timer.run(() => print("after timer"));
    scheduleMicrotask(() => print("after microtask"));
  });

  scheduleMicrotask(() => badFn());
}
```

This prints "caught error" and "after timer", but not "after microtask".

**Comment by nex3** [comment]
See also #23684, which proposes to make runtime syntax errors thrown like other exceptions.

**Comment by natebosch** [comment]
Given that the Dart 2 VM no longer attempts to execute code with a parse error I don't think this issue is relevant anymore.
