### ISSUE TITLE
Please, clarify the yield* specification, regarding stream cancellation

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25749]
Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, chapter 17.16.2 Yield-Each reads:

> If m is marked async\* (9), then:
> • It is a dynamic error if the class of o does not implement Stream. Otherwise
> • For each element x of o:
> – If the stream u associated with m has been paused, then execution
> of m is suspended until u is resumed or canceled.
> – If the stream u associated with m has been canceled, then let c be
> the ﬁnally clause (17.11) of the innermost enclosing try-ﬁnally state-
> ment, if any. If c is deﬁned, let h be the handler induced by c. If h is
> deﬁned, control is transferred to h. If h is undeﬁned, the immediately
> enclosing function terminates.
> – Otherwise, x is added to the stream associated with m in the order
> it appears in o. The function m may suspend.
> • If the stream o is done, execution of s is complete.
1. The text implicitly assume a subscription to stream o. Please, make it explicit.
2. Please, clarify what happens with the subscription to stream o, if stream u is cancelled?
   Is it cancelled too? Will the stream o be cleaned up as part of stream u clean up?
3. According to API specification https://api.dartlang.org/1.14.1/dart-async/Stream-class.html stream can not be cancelled, but stream subscription can be cancelled. Please, correct this typo.

**Comment by lrhn** [comment]
You can't cancel a stream, only a stream subscription  (ditto for pause and resume), but it is common to conflate the two when talking about a subscription on a single-subscription stream.
 
I agree that the specification could be more explicit about the subscription.
