### ISSUE TITLE
ServiceExtensionResponse doesn't document the semantics of the returned string

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25758]
[`new ServiceExtensionResponse.result()`](https://api.dartlang.org/1.14.2/dart-developer/ServiceExtensionResponse/ServiceExtensionResponse.result.html) takes a string, but doesn't document document the semantics or requirements for that string. This is particularly relevant because it seems like this string is directly interpolated into the JSON-RPC response, which means that it must be valid JSON and that clients must expect a decoded version of the data included in the string.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1685703005/
