### ISSUE TITLE
Specification: wrong definition of mixin

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25764]
Dart Language specification, 4th Edition (December 2015). Chapter 12 Mixins

> A mixin describes the difference between a class and its superclass.

The difference between a class and its superclass are members defined in the class. According to http://www.bracha.org/mixins-paper.pdf "Mixin is a set of modifications (overrides and/or extensions) to be applied to a superclass parameter"

**Comment by lrhn** [comment]
How is the definition wrong?

**Comment by sgrekhov** [comment]
Ok, I'll try to clarify.
```dart
class S {
  var s;
}
class M {
  var m;
}
class C extends S with M {
  var c;
}
```
This is the same as 
```dart
class A = S with M;
class C extends A {
  var c;
}
```
The difference between class C and its superclass (class A) is instance variable c, defined in C. Mixin (class M) describes the difference between S and A, but  "A mixin describes the difference between a class and its superclass." defines that M describes a difference between C and S

**Comment by lrhn** [comment]
In this case, `M` defines a mixin (it *is* a class which extends `Object`, it extends object with the mixin `{ var m; }`), and so is `{ var c; }` (the mixin defined by the class `C`).

The superclass of `C` is `A`. The difference between `C` and `A` is the "mixin" `{ var c; }`.
The superclass of `A` is `S`. The difference between `A` and `S` is the mixin defined by `M`.

That means that in every case, the difference between a class and its superclass is a mixin.

The `M` in `S with M` refers to the mixin define by `M`. The superclass of `S with M` is `S` and the mixin of `M` defines the difference.
The superclass of `C` is `S with M` (whether named `A` or not) - so `S` is not the superclass of `C`, and there is no single mixin which describes the difference between `C` and `S`. There are two mixins (that of `M` and that of `C`) that together describe that difference, with `S with M` as the intermediate class.

(That `{ var c; }` is a mixin can be seen from a declaration like `class D = A with C;` which extends the class `A` with the mixin `{ var c; }` to get a class that has the same fields as `C`).

**Comment by sgrekhov** [comment]
Oh... Thank you for clarification. But from the specification I had a different understanding of what mixin is. So I was under impression that mixin is a class which follows `with` clause.  

> That means that in every case, the difference between a class and its superclass is a mixin.

But what about
```dart
class M {
  var m;
  M(val) {
    m = val;
  }
}
```
Specification reads
> It is a compile-time error if a declared or derived mixin explicitly declares
> a constructor.
What is mixin in this case? The difference between `Object` and `M` cannot be a mixin because class M defines a constructor.

Specification written in a way that makes me think that mixin is a class that describes a set of "adjustment" that should be applied to superclass and produces new (named or not) class that became a new superclass

**Comment by lrhn** [comment]
We say that a class can be "used as a mixin" when it doesn't have a constructor. As such `S with M` is using the class `M` as a mixin. However, what that means is that the members *declared* by `M` are added to the class `S with M` (which has superclass `S` and which also adds forwarding constructors for each generative constructor in `S`). 
The members of `M` that are only inherited are not included in the mixin application.
You can see this as extracting the "mixin of M" from `M` (the delta between `M` and its superclass) and applying it to the superclass. That's my words, I don't think the specification says that.

It used to be that the superclass of a mixin class had to be `Object`. Even then, the members of `Object` were not included in the mixin application. It was always only the declared members of the class used as a mixin.

If a class defines a constructor, then it can't be used as a mixin. In my words, the class does not have a mixin that you can extract and apply to something else - or it has one, but you can't apply it. The end effect is the same - it's a compile time error if you try.

**Comment by sgrekhov** [comment]
@lrhn thank you! Now it's much clearer for me. What I'm going to do is to close this issue and create the new one. Than specification should clearly define the following:

- mixin definition
- clear definition of derived mixin and clear definitionof declared mixin (btw what is declared mixin?)
- clearly state that if class, that mixed in by `with `clause, only members declared in the class are added to the class declaration, not the inherited ones (or at least add non-normative section to the spec with an example)

Do you agree with it?

And I have one more (hope the last one:))  question regarding mixins. Specification reads

> Let MA be a mixin derived from a class M with direct superclass Sstatic.
> Let A be an application of MA. It is a static warning if the superclass of A
> is not a subtype of Sstatic.

I'm I understand this right that this describes the following case:
```dart
class Sstatic {
}
class M extends Sstatic {
}
class SuperA {
}
class A = SuperA with M;  /// static type warning because SuperA is not a subtype of Sstatic

main() {
  new A();
}
```
If this is so it looks as a strange limitation

**Comment by lrhn** [comment]
To be exact: The specification needs to clearly specify how a mixin application defines a new class from a super-class and a mixin-class. That includes saying that only the members declared in the mixin-class (not those inherited from the super-class of the mixin-class) are added to the new class, along with forwarding constructors for each generative constructor of the super-class. 

I agree that the sentence "*C* declares the same instance members as *M*" would be more clear if it emphasizes that only the declared members, not the inherited members, of *M* are declared by *C*.

Speaking about "mixin" as a separate concept might just be confusing, but if it is used, it should be clearly defined.

A for the question, it is exactly the case that it covers. The limitation is necessary because the mixin class may contain code that does "super.foo()", and to ensure that this isn't completely wrong, the super-class that the mixin class is applied to should also have the same members.

**Comment by sgrekhov** [comment]
@lrhn Thank you!
