### ISSUE TITLE
Dartanalyzer doesn't warn about mixin's superclass member

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25763]
This is offshot of #25762 
Class derived from the mixin application should have only those members that explicitly declared in it, not in its superclass. Otherwise analyzer should warn about that. But in fact it doesn't. Example:

``` dart
class S {
  int get g1 => 1;
}
class M1 {
  int get g2 => 2;
}
class M2 extends M1 {
  int get g3 => 3;
}
class C extends S with M2 {
}

main() {
  C c = new C();
  c.g2; // g2 is not mixed into C, so there should be a warning about not existing getter g2
}
```

Tested on Dart VM version: 1.15.0-dev.2.0 (Wed Feb 10 02:55:12 2016) on "windows_x64"

**Comment by kasperl** [comment]
I wonder if the real issue is that the analyzer should complain that `C` only partially implements the `M2` interface because it's missing the `g2` getter.

**Comment by askeksa-google** [comment]
Since (with the super mixin feature) a base class must be a subtype of the superclass of the mixin, this issue is now meaningless.
