### ISSUE TITLE
Does WebGL work at all under Dartium?

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#25767]
The bots don't run WebGL, so all the tests are suppressed. If I try to run locally, but under remote desktop, I get a WebGL initialization error. We need to verify if WebGL is actually able to run at all under Dartium.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by terrylucas** [comment]
WebGL does work now in Dartium 45 the webgl test run locally on Linux and Mac.  Only Mac bots can test WebGL.

Should investigate why Windows webgl doesn't work locally.  Downgraded since all by Windows work.

**Comment by mit-mit** [comment]
Clearing milestone as this does not appear to being worked on...

**Comment by alan-knight** [comment]
It does work.
