### ISSUE TITLE
With generic methods enabled, analyzer fails to parse local generic function returning void

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25769]
The following code generates parse errors, even if generic method support is enabled:

```dart
    void f() {
      void g<T>() {
      }
    }
```

**Comment by jmesserly** [comment]
Do you know if this is related to enableGenericMethods, or enableGenericMethodComments?

Strong mode only turns on the latter.

**Comment by stereotype441** [comment]
@jmesserly I was doing my testing with enableGenericMethods.

**Comment by jmesserly** [comment]
Ah, probably not a strong mode issue then? I haven't done anything with `enableGenericMethods` flag in the parser. At some point we'll want to enable the real syntax in both modes, though.

Maybe we need an analyzer-generic-methods label? That way we could start tracking generic method issues+normal mode. I think a lot of the work is done there, but there's probably a few issues still.

That said I'm happy to help with all of those issues when we're ready. :)

**Comment by stereotype441** [comment]
Ah, good point.  Not a strong mode issue.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1693963002/

**Comment by Andersmholmgren** [comment]
I'm a little confused why the impact of this is. Can I set a VM flag that allows me to use generic methods without the comment form and other than syntax everything else will behave the same as for the comment form?

**Comment by stereotype441** [comment]
@Andersmholmgren No.  As far as I know there's no support for generic method syntax in the VM yet.  This bug refers to the implementation of generic methods in the analyzer, which is a bit ahead of the VM right now, but still a work in progress.

**Comment by Andersmholmgren** [comment]
Ah gotcha. Thanks
