### ISSUE TITLE
Growable List + clear() memory leak

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25778]
Growable Lists are backed by fixed-length buffers in the Dart VM.

Growable lists do not shrink the buffer when `clear()` is called.
This means that if I allocate 1 million lists, each with 2000 elements,
and call `clear()`, memory is not freed, as the buffer does not shrink.

```dart
List<List<int>> lists;

main() {
  print("Creating 1 million lists.");

  lists = new List<List<int>>();
  for (var listCount = 1; listCount <= 1000000; listCount++) {
    lists.add(new List<int>.generate(2000, (i) => null));
  }

  print("Clearing lists.");
  for (var list in lists) {
    list.clear();
  }

  print("Lists cleared. ");
}
```

This problem is not seen when you set `length` on the list to zero, as this seems to resize the buffer. It is at least my expected behavior that calling `clear()` would resize the buffer to zero.

**Comment by steelstyle** [comment]
I don't think this should be the case, language like c++ can have the same behavior (not changing capacity but number of element in the list).
Maybe a method "trimToSize" like in java can do the work work.

**Comment by kaendfinger** [comment]
Thanks :+1:
