### ISSUE TITLE
js-interop: '.call is not a function' when using callback

### ISSUE THREAD

**Issue by PaulAnnekov** [dart-lang/sdk#25777]
I want to implement a callback for `click` event using leaflet's `on` method (http://leafletjs.com/reference.html#events-on). But when I trigger an event (click on polygon) I see an error in console: `Uncaught TypeError: listeners[i].action.call is not a function`. And I need to get event object too, to make some checks.

Happens only in Chrome. Works ok in Dartium but maybe handles `event` argument (see web_app.dart in gist) wrong.

* Dart SDK version: 1.15.0-dev.2.0 (Wed Feb 10 11:10:22 2016) on "linux_x64"
* pkg/js version: 0.6.0

Failing code:
https://gist.github.com/PaulAnnekov/e165ede2a2561dcd6167

**Comment by jacob314** [comment]
instead of passing onReady directly, you need to call 
allowInterop(onReady)
which will convert the Dart function to a JavaScript compatible function.
