### ISSUE TITLE
Analyzer reports warning instead of error for build-in identifiers used as type parameter.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25772]
According to Dart Language specification (4th edition, Dec 2015) "16.33 Identifier Reference":

"It is a compile-time error to use a built-in identifier other than dynamic as a type annotation or type parameter."

However, analyzer reports warning for test below, while dart reports error.

``` dart
class A<T> {}
main() {
  new A<abstract>();
}
```

The analyzer reports warning for other build-in identifiers, except dynamic. 
Note, dart doesn't report error for build-in identifier deferred.

**Comment by askeksa-google** [comment]
Analyzer gives correct error message now.
