### ISSUE TITLE
Dartium doesn't call Dart_IsolateMakeRunnable making it impossible to set breakpoints through the Observatory

### ISSUE THREAD

**Issue by jayudey-wf** [dart-lang/sdk#25775]
The observatory is no longer allowing me to set break points.  Prior to getting to the screen that allows me to set break points I receive an error indicating that the isolate is not runnable.

dart sdk verison >= 1.14.1 http://recordit.co/SnnsyI84et
dart sdk version < 1.14.1 http://recordit.co/T5A5LXjEDi

I am still unable to set break points in the current dev channel, 1.15.0-dev.2.0.

In the screenshots included above I used the random_color example found within this repo, https://github.com/Workiva/w_flux. The examples can be run by using `pub run dart_dev examples`

**Comment by johnmccutchan** [comment]
@jayudey-wf What embedder are you running?

**Comment by johnmccutchan** [comment]
@jayudey-wf The embedder you are using is not calling Dart_IsolateMakeRunnable after loading the sources.

**Comment by jayudey-wf** [comment]
below is how i'm embedding the dart into the html file if that's what you are asking

https://github.com/Workiva/w_flux/blob/master/example/random_color/index.html#L27

**Comment by johnmccutchan** [comment]
@jayudey-wf Are you running in Dartium?

**Comment by jayudey-wf** [comment]
yes

**Comment by johnmccutchan** [comment]
@jacob314 @alan-knight FYI

**Comment by johnmccutchan** [comment]
@jayudey-wf Thanks. I'm working on a fix for Dartium now.

**Comment by jayudey-wf** [comment]
ok, awesome. let me know if there is any additional information that you might need and thanks again!

**Comment by alan-knight** [comment]
Didn't we already fix this in https://codereview.chromium.org/1678963002/ ?

Or is there another code path?

**Comment by johnmccutchan** [comment]
@alan-knight Oh, looks like you guys have already fixed it. Is this in the latest -dev release?

**Comment by alan-knight** [comment]
It ought to be. But if the problem was in 1.14 we may need to cherry-pick it.

**Comment by johnmccutchan** [comment]
@jayudey-wf Please confirm this is still an issue with the latest Dartium dev release.

**Comment by jayudey-wf** [comment]
It's not an issue in the 1.15.0-dev.3.0 sdk, so this issue can be closed. I had checked in 1.15.0-dev.2.0 to ensure it was still an issue there and it was. I didn't realize that a new dev version had been tagged.

Thanks!
