### ISSUE TITLE
type inference for 'var' variables doesn't distinguish between getters and setters

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25783]
To reproduce, copy into DartPad:

```
class Foo {
  get bar => 1;
}

void main() {
  var foo = new Foo();
  print(foo.bar);
  foo.bar = 2; // no hint
}
```

There is no hint when setting `bar` because a getter exists.

**Comment by bwilkerson** [comment]
Minor correction. There is no *hint* when setting bar. Not sure whether it's because there is a getter (and the hint is wrong) or because we have not implemented that hint yet.

**Comment by skybrian** [comment]
If you remove the getter then it does display a hint. So, it is using the presence of a getter to decide whether to display the hint.

**Comment by srawlins** [comment]
Also if you change `var foo = ...` to `Foo foo = ...`, you now get the hint "No setter named 'bar' in class 'Foo'". https://dartpad.dartlang.org/8383fcd70fd55320a8a3

**Comment by pylaligand** [comment]
Note: same applies if you do `final bar = 1` in the Foo class and/or you do `final foo = new Foo()` in main.

**Comment by srawlins** [comment]
The analyzer now correctly reports an error for the example:

> No setter named 'bar' in class 'Foo'.
