### ISSUE TITLE
A more powerful weakmap/expando for fully simulating  dynamic property or method

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/sdk#25781]
On giving expando a try, I found it very basic and limited.
To overcome the limitations, I came up with:

- keys method for expando

<strong>Edited</strong>  to remove my bubbling and to add the below (as an example of an application of the key fetch-able weakmap I wrote using expando ):
<cod><pre>
var m = new AdvancedWeakmap(); //m can be any object
var d = new Dynamism();
d.on(m).add_method('bye',(name,age){
    print("dynamically added bye \n ${name}, "
        'Your age is ${age}, you are not '
        'allowed to drink legally');
  });
//get the list of all added methods as strings
print(d.on(m).methods());
//calling the added method
d.on(m).bye('doggy',5);
//prints
//[hi, bye]
//dynamically added bye 
// doggy, Your age is 5, you are not allowed to drink legally

</code></pre>

Maybe a feature like the below (key fetch-able weakmap)can be added to dart? 
<code><pre>
import 'dart:core';
import 'dart:developer';
main(List<String> args) {
//sample code for demonstrating an application of weakmap

  var m = new AdvancedWeakmap();
  var t = new DateTime.now();
  //associating key and value on the context of t
  // both key and value should be garbage collected when t is garbage collected
  m.add(
      t,
      new AWMapKey('print time now'),
      () =>print(t));

 //fetching all the keys than can be used to fetch values in the context of t
  for (var k in m.keys(t)) {
    print(k.toString()); // 'print time now' will be printed
    m.value(t, k)(); //value fetched is the function ()=>print(t)
  }
  //now destroying all keys, values by destroying the context t
  t = null;

  //creating a partial copy of the AdvancedWeakmap m
  print('==copying partially(only '
      'key two and its associates copied)==');
 //adding new key value pairs to now empty m
  t = new DateTime.now();
  m.add(t, new AWMapKey('key one'), () {
    print('key one used to fetch this:'+t.toString());
  });
  m.add(t, new AWMapKey('key two'), () {
    print('key two used to fetch this'+t.toString());
  });
 // copying only 'key two' to the new AdvancedWeakmap
  var m2 = new AdvancedWeakmap();
  for (var k in m.keys(t)){
    if(k.toString().contains('key two')){
      m2.add(t,k,m.value(t,k));
    }
  }
  //using the copied key value pair
  for(var k in m2.keys(t)) {
    print(k.toString());
    m2.value(t,k)();
  }

  //dynamic property sim ugly but safe
  print('=====dynamic property sim====');
  var d = new Dynamism();
  d.add_method(m,'hi',(){print('dynamically added hi');});
  d.invoke((){m.hi();},m);

  // improved, but the return value of on call
  // now contains a strong reference to the key.
  // var strongReferenceTo_m = d.on(m);
  // potentially dangerous.
  d.on(m).add_method('bye',(name,age){
    print("dynamically added bye \n ${name}, "
        'Your age is ${age}, you are not '
        'allowed to drink legally');
  });
  //get all added methods
  print(d.on(m).methods());
  d.on(m).bye('doggy',5);
}
class Dynamism {
  AdvancedWeakmap _am = new AdvancedWeakmap();
  add_method(
      var targetObject,
      String methodName,
      var newMethod){
      _am.add(
          targetObject,
          new AWMapKey(methodName),
          newMethod);
  }
  void invoke(var wrapper, var wrapped,[List args=null]) {
    ///if you want to invoke a function on
    ///object a, then use
    ///invoke((){a.yourFunction}, a)
    try {
      wrapper();
    } on NoSuchMethodError catch (e) {
      var l = e.toString().split('\n');
      var funcName = l[0]
          .split('has no instance method ')
          .last;
      //find the function in map
      funcName = funcName.substring(1, funcName.length - 2);
      var key;
      for(var k in _am.keys(wrapped)){
        if(k.toString() == funcName)
          key = k;
      }
      if(key == null) {
        rethrow;
        return;
      }
      var function_to_call = _am.value(wrapped,key);
      function_to_call();
    } catch (e) {
      rethrow;
    }
  }
  on(var object){
//    AdvancedWeakmap pc = _am.partial_copy(object);
    return new DynamicWrapper(object,_am);
  }
}
class DynamicWrapper{
  ///MUST BE USED ONLY AS A TEMPORAL OBJECT.
  ///
  ///Currently this object is dangerous
  ///internally holds a strong reference
  ///to the weakmap key,_key_object,
  var _key_object;
  bool _destroyed = false;
  AdvancedWeakmap _awm;
  DynamicWrapper(
      this._key_object,
      this._awm
      ){ }
  add_method(
      String methodName,
      var newMethod){
    _awm.add(
        _key_object,
        new AWMapKey(methodName),
        newMethod);
    _destroy();
  }
  List<String> methods(){
    List keys = [];
    for(var k in _awm.keys(_key_object))
      keys.add(k.toString());
    return keys;
  }
  _destroy(){
    _key_object = null;
    _awm = null;
    _destroyed = true;
  }
  noSuchMethod(Invocation invocation) {
    if(_destroyed){
      throw 'DynamicWrapper reused error: '
          'Dynamism_instance.on(object) must be '
          'used as a temporal object';
    }
    Symbol methodSymbol = invocation.memberName;
    List args = invocation.positionalArguments;
    Function f;
    for(AWMapKey k in _awm.keys(_key_object)){
      Symbol s = new Symbol(k.toString());
      if(s == methodSymbol){
        f = _awm.value(_key_object,k);
        break;
      }
    }
    if(f == null) super.noSuchMethod(invocation);
    switch(args.length){
      case 0:
        var r = f();
        _destroy();
        return r;
      case 1:
        return _call1(f,args);
      case 2:
        return _call2(f,args);
      case 3:
        return _call3(f,args);
      case 4:
        return _call4(f,args);
      case 5:
        return _call5(f,args);
    }
  }
  _call1(Function f,List l){
    var one=l[0];
    var r = f(one);
    _destroy();
    return r;
  }
  _call2(Function f,List l){
    var one=l[0],two=l[1];
    var r = f(one,two);
    _destroy();
    return r;
  }
  _call3(Function f, List l){
    var one=l[0], two=l[1],
        three =l[2];
    var r = f(one,two,three);
    _destroy();
    return r;
  }
  _call4(Function f,List l){
    var one=l[0], two=l[1],
        three =l[2],four =l[3];
    var r = f(one,two,three,four);
    _destroy();
    return r;
  }
  _call5(Function f,List l){
    var one=l[0], two=l[1], three =l[2]
    ,four =l[3],five = l[4];
    var r = f(one,two,three,four,five);
    _destroy();
    return r;
  }
}
class AWMapKey{
  ///Expando cannot take a string as a key
  ///so for the time being wrapping string it
  /// make it a valid key
  String _key;
  AWMapKey(this._key){ }
  String toString()=>_key;
}

class AdvancedWeakmap{
  Expando _keys = new Expando();
  Expando _values = new Expando();
  add(var context,var key, var value){
    ///keys and values could only be accessed
    ///with the defined context.
    /// keys and values should be garbage collected
    ///soon after context is garbage collected.
    _keys[context] ??= [];
    _keys[context].add(key);
    _values[context] ??= [];
    var v = new Expando();
    v[key] = value;
    _values[context].add(v);
  }
  keys(context){
  ///return keys that can be used with the given context
  ///to fetch values saves on the context.
  ///The returned keys will not be garbage collected when
  ///context is garbage collected.
    return _keys[context];
  }
  value(context, key){
  ///return the value saved on the given context
  ///with the given key
    List l =  _values[context];
    for(var expando in l){
      if(expando[key] != null)
        return expando[key];
    }
  }
  partial_copy(var context){
    ///copy values and keys associated
    ///with the context to another
    ///AdvancedWeakmap.
    ///Deleting the original should not
    ///affect the copy
    var newMap = new AdvancedWeakmap();
    for (var k in keys(context))
      newMap.add(context,k,value(context,k));
    return newMap;
  }
}
</code></pre>

I originally started asking the question that led to expanding expando here:http://stackoverflow.com/questions/35366346/how-to-share-expado-or-weakmap-properties-or-other-options-if-available-cleanl/35403391#35403391

**Comment by lrhn** [comment]
Could you explain *exactly* which behavior you expect. It's hard to say if a complex piece of code is correct if the code is all you have, and it isn't documented.

**Comment by TastyCatFood** [comment]
Sorry about posting in a wrong place and yes I now recognize that I did not explain enough.

My concern: can I rely on expando property/value to be garbage collected when the key for the value has been garbage collected?
<code><pre>
var expando = new Expando();
var key = new DateTime.now(); //key
expando[key] = (_)=>print('hi');
key = null; // key deleted
//will (_)=>print('hi') be garbage collected too?
//Or the expando property survives till expando is garbage collected
</pre></code>
Or a value tied with an expando object stay in memory forever?

My second intention for posting here was to ask if a expando variant like AdvancedWeakmap I wrote could be added to dart as it makes the below easier.
The code I posted runs alright, I was just not certain about how garbage collection goes for sure:
<pre><code>
print('=====dynamic property sim====');
var m = new AdvancedWeakmap();
var d = new Dynamism();
//adding a new method hi on m in the context of d
d.add_method(m,'hi',(){print('dynamically added hi');});
//calling the added method hi in the context of d
d.invoke((){m.hi();},m);  </pre></code>
Evil code that I agree, but somehow being able to do this feels right.

**Comment by lrhn** [comment]
You should be able to rely on the value being GC'ed when the key is no longer reachable.

**Comment by TastyCatFood** [comment]
Thank you.
Sorry about my initial unreadable post. I got obsessed over this to the point of sickness and was living in a delusion of being a genius forgetting both human language and manners. 

AdvancedWeakMap(bad name, but I don't know the name for this kind of structure) hopefully will alleviate the lack of weakref in dart a little.

**Comment by floitschG** [comment]
As Lasse states: this should be in a package and not part of dart:core.

Fwiw I wrote a small (hopefully) simpler (but untested) version of the map:

``` dart
class AdvancedWeakMap{
  final _expando = new Expando();

  add(var context,var key, var value) {
    var map = _expando[context];
    if (map == null) {
      map = {};
      _expando[context] = map;
    }
    map[key] = value;
  }

  keys(context){
    return _expando[context]?.keys?.toList();
  }

  value(context, key){
    var map = _expando[context];
    if (map == null) return null;
    return map[key];
  }

  partial_copy(var context){
    var newMap = new AdvancedWeakmap();
    var map = _expando[context];
    if (map != null) {
      newMap._expando[context] = new Map.from(map);
    }
    return newMap;
  }
}
```

**Comment by TastyCatFood** [comment]
Thanks floitschG
I wonder why using a map never occurred to me, now you got rid of half the troubles for me.

Finally  major bugs are gone, though it's worse in terms performance than before.
I will try to get it published in few days:  
https://github.com/TastyCatFood/superexpando
