### ISSUE TITLE
eventhandler macos assertion failure

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25789]
FAILED: none-vm debug_x64 service/logging_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
*\* Launching xcodebuild/DebugX64/dart --trace-service --trace-service-verbose --ignore-unrecognized-flags --package-root=xcodebuild/DebugX64/packages/ --enable-vm-service:0 /Volumes/data/b/build/slave/vm-mac-debug-x64-be/build/sdk/runtime/observatory/tests/service/logging_test.dart --testee-mode
vm-service: Booting dart:vmservice library.
vm-service: Registering running isolates.
vm-service: Isolate logging_test.dart$main-963572997 963572997 registered.
Observatory listening on http://127.0.0.1:50850
*\* Signaled to run test queries on 50850

Hit debugger!vm-service: starting stream 'VM'
vm-service: starting stream 'Isolate'
vm-service: starting stream 'Debug'
vm-service: starting stream '_Graph'
[+1580ms] Isolate vm-service processing service request getVM
[+1581ms] Isolate vm-service processed service request getVM (86us)
[+1632ms] Isolate logging_test.dart$main-963572997 processing service request getIsolate
[+1634ms] Isolate logging_test.dart$main-963572997 processed service request getIsolate (2138us)
Running logging_test.dart [1/4]
[+1961ms] Isolate logging_test.dart$main-963572997 processing service request getIsolate
[+1962ms] Isolate logging_test.dart$main-963572997 processed service request getIsolate (932us)
Paused with PauseBreakpoint
Running logging_test.dart [2/4]
vm-service: starting stream '_Logging'
[+2064ms] Isolate logging_test.dart$main-963572997 processing service request resume
[+2064ms] Isolate logging_test.dart$main-963572997 processed service request resume (33us)
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='Resume') to stream Debug
Running logging_test.dart [3/4]
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='_Logging') to stream _Logging
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='PauseBreakpoint') to stream Debug
vm-service: stopping stream '_Logging'
[+2150ms] Isolate logging_test.dart$main-963572997 processing service request getIsolate
[+2151ms] Isolate logging_test.dart$main-963572997 processed service request getIsolate (921us)
Paused with PauseBreakpoint
Running logging_test.dart [4/4]
vm-service: starting stream '_Logging'
[+2252ms] Isolate logging_test.dart$main-963572997 processing service request resume
[+2252ms] Isolate logging_test.dart$main-963572997 processed service request resume (42us)
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='Resume') to stream Debug
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='_Logging') to stream _Logging
*\* Killing script
vm-service: stopping stream '_Logging'
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='ServiceExtensionAdded') to stream Isolate
vm-service: Pushing ServiceEvent(isolate='logging_test.dart$main-963572997', kind='ServiceExtensionAdded') to stream Isolate

stderr:
/Volumes/data/b/build/slave/vm-mac-debug-x64-be/build/sdk/runtime/bin/eventhandler_macos.cc:60: error: expected: !di->tracked_by_kqueue()

**Comment by fsc8000** [comment]
This seems to affect different tests. Here is another example:

FAILED: none-vm-checked debug_x64 service/vm_restart_test

https://build.chromium.org/p/client.dart/builders/vm-mac-debug-x64-be/builds/8217/steps/checked%20vm%20tests/logs/stdio

**Comment by mraleph** [comment]
This is a duplicated of #24417
