### ISSUE TITLE
Please merge a6e4f35e0bcfb0206e63b834cb03b9a0c31996d7 to stable

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25780]
It fixes a crash bug in the Dart VM (issue #25771)

**Comment by mit-mit** [comment]
@asgerf is the change that triggered this (#25771) for the upcoming 1.15 release, or for stable? Just trying to understand if this can go out with 1.15 rather than patching stable. I don't beleve there have been any external reports of this.

**Comment by asgerf** [comment]
The change to dart2js which observed the bug landed in 64fa2ef5.

**Comment by mit-mit** [comment]
I understand. But are the any plans to merge that to stable? If not, seems like both that change and https://github.com/dart-lang/sdk/commit/a6e4f35e0bcfb0206e63b834cb03b9a0c31996d7 can go out together in 1.15.

**Comment by asgerf** [comment]
There are no plans to merge the dart2js change (64fa2ef) to stable.

**Comment by fsc8000** [comment]
The VM bug is more general, and is present since circa October. It affects potentially all Dart code. It is unrelated to the dart2js change, and will merge easily.

**Comment by mit-mit** [comment]
Let's include if we do another stable patch, but otherwise with until
either that happens or an external customer reports it.

On Thu, Feb 18, 2016 at 2:57 PM, Florian Schneider <notifications@github.com

**Comment by mit-mit** [comment]
1.15 will ship to stable in just a week, so at this point I am going to close this merge request as 1.15 will have the change.
