### ISSUE TITLE
Crash when running Pop, Pop, Win w/ 1.16.0-dev.1.0 in Dartium & Dart2js

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25797]
![screen shot 2016-02-17 at 9 19 25 am](https://cloud.githubusercontent.com/assets/17034/13118126/9f81bb82-d557-11e5-9325-d99ede79c54c.png)

CC @terrylucas @jacob314 @alan-knight

**Comment by kevmoo** [comment]
Here's the fun thing. This relates to getting `context2d` from Canvas.

If I `print` it early in the call stack, it works fine.

If I don't, it crashes.

**Comment by kevmoo** [comment]
@jacob314 see repro here https://github.com/dart-lang/sample-pop_pop_win/compare/sdk_i25797

**Comment by boasjls** [comment]
I tested several of the canvas2d samples and they all appear to work. However none of the WebGL samples do work.
I think the somewhat odd behavior here can be explained by StageXL having both a Canvas2D and a WebGL engine. 
When the getter is called for context2d, as in your repro example, the Canvas2D engine is then used. Otherwise it defaults to WebGL which then doesn't work.

**Comment by terrylucas** [comment]
Your build of Dartium is using sdk/libs generated from roll 39 although the
guts is roll 45.  Probably, and IDL change that needs to exposed w/ re-gen
of the dart libraries for html/svg/web_audio/etc.

pop-pop-win is working with my build of Dartium.  I have a Dartium which
has all the generated _blink and sdk/lib files not yet on bleeding edge.
Hope to have this last part of the roll ready today/tomorrow.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bp74** [comment]
I did a quick test with 1.15.0-dev.5.0.0 and it seems that WebGL is working fine now.

**Comment by jacob314** [comment]
This was fixed.

**Comment by kevmoo** [comment]
It's back. Same repro. Same work-around.

1.16.0-dev.1.0

**Comment by alan-knight** [comment]
This is because we regenerated WebGL in 1.16 from new IDL and methods (marked experimental and unstable) have changed, and they're used in StageXL. I sent a pull request which fixes those particular issues to StageXL. @bp74

**Comment by kevmoo** [comment]
My request: can we add back `bufferDataTyped` marked as `@deprecated`?

If we are going to break things, we should at least give folks time to migrate – for the easy ones at least.

**Comment by alan-knight** [comment]
So what is the point of having something marked unstable and experimental if we have to preserve backward compatibility when it changes? We're going to end up carrying around a lot of manually maintained baggage from old DOM APIs.

**Comment by bp74** [comment]
I agree that removing methods that are marked as unstable or experimental is okay.  The problem is that the dart analyzer never showed this information. I never saw a warning that those methods are unstable, experimental or deprecated.

**Comment by bp74** [comment]
After checking api.dartlang.org I get what you mean. The whole WebGL api is marked as experimental. Which is a little bit frightening considering that we are talking an API that is standardized for many years.

**Comment by kevmoo** [comment]
Looks like we're walking back from this - see https://github.com/dart-lang/sdk/issues/26047

**Comment by alan-knight** [comment]
Duplicate of #26047
