### ISSUE TITLE
JSON.decode doesn't play nice with postMessage in dart2js

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25792]
It seems that, even when using Dart2JS, `JSON.decode` returns a `_JsonMap` type. When this type is included in another collection type, and that type is passed to `Window.postMessage` (or presumably any other API that uses the structured clone algorithm), it's passed through as an opaque object rather than a map. This seems like a pretty serious issue, since it's easy for JSON-parsed maps to find their way into places that don't know where they originally came from, and there's no good way to check if it's a `_JsonMap` at runtime.

I tested this against 3011aff0473041eacf508df404813c3c2dc140c2.

**Comment by lrhn** [comment]
That seems like a problem with `Window.postMessage`. We have many different `Map` implementations in the platform libraries, and there is no reason one should work better than another.

**Comment by nex3** [comment]
It turns out this was just #25636. False alarm.

**Comment by jacob314** [comment]
Assigning to Alan as he was recently working on a postMessage bug in Dartium
