### ISSUE TITLE
Revert 851b4a9 - Compile-time error if mixin class has a factory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25791]
See 851b4a995c72b484e1b4d13dabbc7e6dcfe7cc24

The ship has sailed on this implementation. We have known breaks here.

As @gbracha said (https://github.com/dart-lang/sdk/issues/24767#issuecomment-174783687) we are fine to change the spec here...

CC @mhausner

**Comment by jacob314** [comment]
Sent out cl to revert. https://codereview.chromium.org/1699233002/

**Comment by kevmoo** [comment]
Commit https://github.com/dart-lang/sdk/commit/6a0b3210265c5fbb74ed0d1b4b6c67910454e853
