### ISSUE TITLE
No audio when running Pop, Pop, Win w/ 1.15-dev.3.0 in Dartium

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25798]
If I do the work-around in https://github.com/dart-lang/sdk/issues/25797, the game runs, but I don't get any audio

**Comment by mit-mit** [comment]
@kevmoo did anyone look into this?

**Comment by kevmoo** [comment]
I believe @jacob314 looked at this – and resolved it?

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bp74** [comment]
I did a quick test with 1.15.0-dev.5.0.0 and it seems that WebAudioApi and AudioElement are working fine now.

**Comment by alan-knight** [comment]
Yes, this was fixed.
