### ISSUE TITLE
UnknownJavascriptObject interceptor: method not found

### ISSUE THREAD

**Issue by denis-aes** [dart-lang/sdk#25796]
I'm calling JS method from object. Accessibility of this method depends on it's name.

When name is "find" - method is unaccessible, because it is missing in interceptors prototype.
When name is "findWithDartFix" - everything is ok.

In every case - interceptor is the same - UnknownJavascriptObject. Code validity depends only on calling method name.

I've found that class 
dart-sdk/pkg/compiler/lib/src/ssa/interceptor_simplifier.dart

Makes optimization and mixes together methods to proxy calls from different JS objects.
 * 4) Single use interceptors at dynamic invoke sites are replaced with 'one
 * shot interceptors' which are synthesized static helper functions that fetch
 * the interceptor and then call the method.  This saves code size and makes the
 * receiver of an intercepted call a candidate for being generated at use site.

Workaround: change method name. 

This is very important and annoying issue for developing with js.dart. It is breaking the code and hardly to find the reason. 

And workaround makes me to change code inside external 3rd party JS library. Very unhandy.
Please, take a look.

For extra details - see screenshots.

Buggy screenshot [Buggy screenshot](https://drive.google.com/file/d/0B2IBVU0_lfrTYWRuVTNkUnhQQ2c/view?usp=sharing)

Fixed screenshot [Fixed screenshot](https://drive.google.com/file/d/0B2IBVU0_lfrTVWxubmg5bkJjQjA/view?usp=sharing)

**Comment by denis-aes** [comment]
May be duplicate with https://github.com/dart-lang/sdk/issues/25785, but not sure. In my case another interceptor is used and seems that interceptor selection is correct.

**Comment by jacob314** [comment]
This isn't 25785. There was a separate issue that caused some method on JavaScriptObject to be lost if their names collided with other method names active in the program.
