### ISSUE TITLE
Strong mode should infer parameter types from default value expressions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25794]
Currently, strong mode does not infer the type of the parameter `x` in the code below:

```
void f({x: false}) {
  ...
}
```

It seems like it would be reasonable to do so, since it would be similar to the way it infers the type of variables from their initializer expressions.

**Comment by jmesserly** [comment]
Nice, yeah, we probably just forgot about this AST node.

**Comment by jmesserly** [comment]
Doh, I just hit this while implementing/testing https://github.com/dart-lang/sdk/issues/25573 (no-implicit-dynamic). I may roll in a fix or look at it concurrently.

**Comment by jmesserly** [comment]
update, fixed it in resolver & element summaries, still haven't got it working in AST-based summaries yet.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2092333002/ -- but I might be way off on that approach :)

**Comment by jmesserly** [comment]
Revert CL up, because this regressed cyclic_default_values https://codereview.chromium.org/2109353004/

It seems like this inference will need to be implemented as part of the top-level field inference, if we want to handle top-level/static functions correctly.

**Comment by jmesserly** [comment]
I'm guessing we do not plan to change the language inference here at this point. closing
