### ISSUE TITLE
Request for better embedding story.

### ISSUE THREAD

**Issue by mfrancis107** [dart-lang/sdk#25806]
I've been working on embedding dart into a VR application I'm working on for several weeks and am still trying to reverse engineer main.cc to understand what exactly is going on just to load and run a basic script.

There either needs to be a cleaner API that requires much less boilerplate, or there needs to be better documentation.

The portion of the API that is similar to Native Extension seems straight forward and sufficiently documented. But the whole initialization process seems verbose just for basic setup.

**Comment by johnmccutchan** [comment]
@mfrancis107 What are you stuck on?
