### ISSUE TITLE
can't forward reference functions declared within other functions

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#25805]
Example:
This is fine:
```dart
void f() {
  g();
}
  
void g() {}

void main() {
  f();
}
```
but apparently this is not:
```dart
void main() {
  void f() {
    g();
  }
  
  void g() {}

  f();
}
```

```
error: line 6 pos 8: identifier 'g' previously used in line 3
  void g() {}
       ^
```
First, the error message could stand to be a bit more friendly - this doesn't mention forward referencing.
But more importantly, is there some technical reason to forbid this?  The meaning of g can't depend on the execution of some previous statement, right?

Ways this can be annoying:
- inside a unittest that has this structure:
```dart
group('Foo', () {
  void f() {
    g(); // Ugghh.. now I am punished with having to order f and g
         // carefully just because they are declared inside the group.
  }

  void g() {}

  test('should bar', () {
    f();
  });
});
```
- when f and g call each other mutually recursively.

**Comment by lrhn** [comment]
The function `g` can depend on a previous line:
```dart
main() {
   void f(){ g(); }
   f();
   var x = 42;
   void g() { print(x); }
}
```
The call to `f` precedes the initialization of the variable used  by `g`, so it can't be allowed to run.

That does mean that you can't declare mutually recursive functions (that easily) inside a function body. It works at the top-level because there is no evaluation order, but inside function bodies, there is an evaluation order, and we try to respect it - no using a name before it's declared.

**Comment by anders-sandholm** [comment]
Closing - let me know if I'm being too trigger happy - it sounds like the current behavior is needed although I understand that there are contexts where this is annoying.

**Comment by trinarytree** [comment]
Sorry, I should have responded.  lrhn's explanation was great.  So it seems like it's forbidden just to prevent the surprise of variables being used before being properly initialized.

**Comment by floitschG** [comment]
Fwiw there is an easy work-around if you need mutually recursive functions:

```
main() {
  var f, g;
  f = () { g(); };
  g = () { f(); };
}
```
