### ISSUE TITLE
fix strong mode LUB

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25802]
I believe strong mode's LUB is not sound for function types (parameter types are computed via LUB).

Also we don't handle generic function types correctly:
```dart
    // The type we infer for `v` is currently `(Object) -> int`, which is wrong.
    final v = f() ? /*<T>*/(T t) => 0 : /*<T>*/(T t) => 1;
    bool f() => true;
```

**Comment by jmesserly** [comment]
I'm going to split out the "improve generic types" into its own bug. The soundness issue is more urgent, our upwards inference uses LUB and that will lead to incorrect conclusions.

**Comment by jmesserly** [comment]
BTW, I added a note about handling generic function types correctly. Given two types like `<U>(U) ->int` and `<V>(V) -> int` it should construct a fresh variable F, instantiate both functions, and then run function LUB as normal (GLB on params and LUB on return type). Result would be something like: `<F>(F) -> int` in this example.

**Comment by leafpetersen** [comment]
There's an implied GLB on the bounds on the type parameters as well.  We also need to define exactly what we mean by GLB for interface types.  I suspect that the right starting (and possibly finishing point) is to take the lesser of the two types if they compare, and otherwise take bottom (with the appropriate pointwise extension for generics).

**Comment by jmesserly** [comment]
> I suspect that the right starting (and possibly finishing point) is to take the lesser of the two types if they compare, and otherwise take bottom (with the appropriate pointwise extension for generics).

yeah, that's the GLB currently used for upwards inference (https://github.com/dart-lang/sdk/blob/09a7387740c172ccf2a4e81bac0617b49fd4fe8f/pkg/analyzer/lib/src/generated/type_system.dart#L776) -- should've factored it out properly. Doh :)

**Comment by leafpetersen** [comment]
Yes, modulo generics.  We should probably eventually compute (e.g.):
```
  GLB(List<int>, List<String>) = List<bottom>
  GLB(List<num>, Iterable<int>) = List<int> 
```
instead of `bottom` for each of those.  Basically the dual of the LUB algorithm that we also need to implement...

**Comment by munificent** [comment]
Made some more progress on this here: https://codereview.chromium.org/1807213005/

Still need to do generics, but LUB for function types should be correct now.

**Comment by jmesserly** [comment]
Generics are covered by https://github.com/dart-lang/sdk/issues/25821 so I think we can close this. Yay :)

**Comment by munificent** [comment]
Ah, cool. Didn't realize there was a separate bug for that. :)
