### ISSUE TITLE
Generic method syntax does not support generic closures

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25819]
Using generic comment syntax I can write code like this:

```
print(/*<U, V>*/() => 0);
```

However, if I drop the comments and enable generic method syntax:

```
print(<U, V>() => 0);
```

I get a syntax error.

**Comment by eernstg** [comment]
Closing: At this point I believe all tools support generic method syntax (or full generic methods), including generic function literals. @stereotype441, please reopen with further info if something is still missing.
