### ISSUE TITLE
Could you please delete a package I uploaded by mistake?

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/sdk#25810]
Sorry about bothering you like this.
Please delete this one: https://pub.dartlang.org/packages/mitstletoe

There are no users as it's only a day old and there has been no visitors and even if there were, they would have my github address.
I have uploaded a package with the correct name already.
  
I'm aware that other people are not as careless as I am, but maybe uploaders should be allowed to delete their packages for the first 24 hours or so? 
It's only a matter of time before someone uploads an inappropriate materials or  private files.

**Comment by alan-knight** [comment]
Bob, does this fall to you? Or who would look after that now?

**Comment by zoechi** [comment]
This might be interesting http://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package

**Comment by munificent** [comment]
Not me anymore. :) @mkustermann and @sgjesse manage the server now.

**Comment by whesse** [comment]
I will remove the package.

**Comment by whesse** [comment]
Removed.

**Comment by TastyCatFood** [comment]
Thank you so much and sorry for troubling you for this.
