### ISSUE TITLE
Expected element is treated as JsObjectImpl in Dartium

### ISSUE THREAD

**Issue by lkovaleva** [dart-lang/sdk#25823]
I have a `<paper-input>` and I need to get its inner `<input>` element, which is accessible like so:
https://elements.polymer-project.org/elements/paper-input#property-inputElement

Here's the resulting code snippet:

``` dart
Element paperInputElement; // This is bound to <paper-input> via Angular.
Element getInput() {
  if (paperInputElement.tagName != 'PAPER-INPUT') {
    return null;
  }

  var paperInput = new JsObject.fromBrowserObject(paperInputElement);
  var input = paperInput['inputElement'];
  if (input is Element) {
    return input; // This is the expected return, but it only works in Chrome.
  }
  return wrap_jso(input); // Dartium requires this wrapper since it sees JsObjectImpl.
}
```

Note that without the wrap_jso call, Dartium returns the error:
`type 'JsObjectImpl' is not a subtype of type 'Element'`

Ideally I shouldn't need the extra if-else and should simply be able to return `paperInput['inputElement']` as an Element in both Chrome and Dartium.

**Comment by jmesserly** [comment]
CC @jacob314 @terrylucas

**Comment by alan-knight** [comment]
Which versions? There have been a lot of changes around the wrapping code.

**Comment by lkovaleva** [comment]
I have...
Dart SDK: version 1.14.0-dev.7.2
Dartium: Version 39.0.2171.0 (64-bit)
