### ISSUE TITLE
Regression in SDK 1.14+: no quick fix to import matching package

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25827]
(Originally filed in [WebStorm's issue tracker](https://youtrack.jetbrains.com/issue/WEB-20437))

I have `path` package in `pubspec.yaml` and `pub get` done.
SDK 1.13:
![image](https://cloud.githubusercontent.com/assets/4499789/13195469/d8b7eb38-d7c3-11e5-8e5c-bfe433dcea75.png)

SDK 1.14 and 1.15-dev-3.0:
![image](https://cloud.githubusercontent.com/assets/4499789/13195458/a0a52d28-d7c3-11e5-9961-4453ee606257.png)

**Problem:** no quick fix offering to add matching import statement.

**Another problem** (SDK 1.13, first screenshot): quick fix to import `package:path/src/path_exception.dart` seems to be redundant, according to [Pub Package Layout Conventions](https://www.dartlang.org/tools/pub/package-layout.html) (see Implementation files) these files should be treated as package-private. **Already filed as #24257.**

**Questionable:** is there a sense in `Remove type annotation` quick assist for such incomplete code?

**Comment by alexander-doroshko** [comment]
People [keep pinging](https://twitter.com/passsy/status/704587908372684800) us. @scheglov is this your area?

**Comment by Aetet** [comment]
:+1:

**Comment by alexander-doroshko** [comment]
Seems to work again with Dart SDK 1.16.0-dev.1.0

**Comment by scheglov** [comment]
Yes, it works now if the library is used at all in the same module. Still does not work if the containing package was added to `pubspec.yaml`, downloaded using `Pub` but is not used anywhere yet. Although I think it has never worked in these conditions, so it's not a bug.

**Comment by srawlins** [comment]
Closed as fixed as per [comment](https://github.com/dart-lang/sdk/issues/25827#issuecomment-200039009)
