### ISSUE TITLE
Analyzer fails to recognize const variable as const.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#25834]
Example:

``` dart
void test1() {
  print("OK");
}

const Function f1 = test1;

const Map<String, Function> c = const {
  'foo': test1,
  'bar': f1,
};

main() {
  c['bar']();
}
```

(tested on dartpad.dartlang.org).

The analyzer gives an error because the use of `f1` is not recognized as a constant expression.

**Comment by srawlins** [comment]
This appears to be fixed, at least in Dart 2.0.0-dev.6.0. Both with and without `--strong`, there are no analyzer errors in this code.
