### ISSUE TITLE
Analyzer CLI silently ignores command line flags in preference to .analysis_options

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25837]
If the dartanalyzer is run from a directory which contains a .analysis_options file in which the strong-mode option is not set, passing the `--strong` flag on the command line has no effect (it is silently ignored).

The command line analyzer should either prefer the command line flags over the .analysis_options, or issue a warning if it overrides the flag set on the command line.

```
leafp-macbookpro:dev_compiler leafp$ ~/dart/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 1.15.0-dev.3.0leafp-macbookpro:dev_compiler leafp$ 
leafp-macbookpro:dev_compiler leafp$ cat .analysis_options 
analyzer:
  exclude:
    - doc/api/**
    - node_modules/**
    - tool/input_sdk/**
    - tool/generated_sdk/**
    - test/codegen/**
    - test/samples/**
    - test/transformer/hello_app/**
leafp-macbookpro:dev_compiler leafp$ ~/dart/dart-sdk/bin/dartanalyzer --strong ~/tmp/generic.dart 
Analyzing [/Users/leafp/tmp/generic.dart]...
[hint] The value of the local variable 'l' is not used (/Users/leafp/tmp/generic.dart, line 3, col 13)
1 hint found.
leafp-macbookpro:dev_compiler leafp$ cd ..
leafp-macbookpro:ddc leafp$ cat .analysis_options 
cat: .analysis_options: No such file or directory
leafp-macbookpro:ddc leafp$ ~/dart/dart-sdk/bin/dartanalyzer --strong ~/tmp/generic.dart 
Analyzing [/Users/leafp/tmp/generic.dart]...
[warning] Unsound implicit cast from List<dynamic> to List<int> (/Users/leafp/tmp/generic.dart, line 3, col 17)
[hint] The value of the local variable 'l' is not used (/Users/leafp/tmp/generic.dart, line 3, col 13)
1 warning and 1 hint found.
```

**Comment by skybrian** [comment]
Another possibility would be to fail if they're incompatible. That is, if you want to use strong mode use --strong, then it would fail and tell you to fix the analyzer_options file to match.

It would ensure consistency, but maybe too annoying.

**Comment by leafpetersen** [comment]
My personal sense is that explicitly passing an option should take precedence, but I'm happy enough with anything that doesn't just silently ignore the command line option.

**Comment by srawlins** [comment]
Luckily analyzer CLI is going awaaaaay.
