### ISSUE TITLE
Libraries with same file name but different paths aren't distinguished

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#25836]
If a library lacks a library tag—which I anticipate will be almost all of them over time—observatory shows it using its short file name. That's rad.

However, if you have two libraries with the same short name but in different directories, they appear the same in the isolate's libraries list. In that case, it would be good to distinguish them using their URL path or something.

**Comment by bwilkerson** [comment]
In fact, always using the URI (or at least making it available, such as by hover text) might help in debugging situations where the same library was imported using two different URI's.
