### ISSUE TITLE
investigate which calls to typeOfElementWithSelector are necessary

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25838]
CPSIR calls this API of type-infererrer more than SSA does. The API shows up as a possible slow operation in the profiles (if the type mask is very general, it will enumerate many elements that match the given selector, and then compute a union of the return types of each element).

**Comment by sigmundch** [comment]
One location that appears in the profile is https://github.com/dart-lang/sdk/blob/e67b4c916179aae334ab7458a857d39ac8867379/pkg/compiler/lib/src/cps_ir/type_propagation.dart#L2737, where we don't care about the return type if it's non-constant.

A specialized query might be more appropriate there. The query just needs to answer whether the return value is a constant, empty, or nullable.

**Comment by zoechi** [comment]
Interesting word in the title - the first one :D

**Comment by sigmundch** [comment]
haha - thanks :)

**Comment by sigmundch** [comment]
actually I retract from my earlier comment - the name "constant-propagation-lattice" let me to think that we didn't care about non-constants, but we actually do.
