### ISSUE TITLE
The obvious reading of return/break/continue inside finally is not the intended one

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25847]
The specification for return says:

> First the expression e is evaluated, producing an object o. Next:
> • The current return value is set to o and the current exception (16.9) and active stack trace (17.11) become undefined.
> • Let c be the finally clause of the innermost enclosing try-finally statement (17.11), if any. If c is defined, let h be the handler induced by c. If h is defined, control is transferred to h.
> • Otherwise execution of the current method terminates.

When return occurs inside the finally clause of a try-finally statement S, then the innermost enclosing try-finally statement is S itself which would seem to reenter the finally clause.  There is a similar problem with break and continue.  E.g., for break:

> Furthermore, let s1, . . . , sn be those try statements that are both enclosed in sE [the target]
> and that enclose sb [the break], and that have a finally clause.

This only works if the code in the finally clause is not enclosed in the try-finally statement (for return) and not enclosed in the try statement (for break and continue), which contradicts the obvious reading.

Note that code in the catch clauses must be enclosed in the try-finally (for return) and enclosed in the try statement (for break and continue) otherwise the finally code would be skipped.

**Comment by lrhn** [comment]
The "correct" reading would be that "enclosing `try`/`catch`/`finally`" really only means enclosed in the *body* of the `try`. It should be reworded.

**Comment by kmillikin** [comment]
It must also include code enclosed in any of the catch parts, otherwise return, break, and continue inside a catch part of try/catch/finally would skip the finally part.

**Comment by lrhn** [comment]
OK, I surrender, it just can't be read in a way that works.
