### ISSUE TITLE
analyzer should set SDK options consistently?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25844]
@lukechurch is hitting this in try.dartlang.org

We fixed all of the clients (analyzer_cli, analysis_server, dev_compiler) to set SDK options to match normal options. But that's kind of a workaround, I think? Because Analyzer will crash (during resolution) if they are not set consistently.

Here is some context:

https://codereview.chromium.org/1664213002/
bugs that were fixed: https://github.com/dart-lang/sdk/issues/25681 -- has stack trace, https://github.com/dart-lang/sdk/issues/25667

fix for analysis_server was CL: https://codereview.chromium.org/1686613002/
here's how we set it in DDC: https://github.com/dart-lang/dev_compiler/blob/56cbbf67d400d03ac6aab6aa8359229f7a33fdd3/lib/src/analysis_context.dart#L74
fix for analyzer_cli was a bit older.

**Comment by jmesserly** [comment]
CC @bwilkerson for thoughts. I'm wondering if the Analyzer API should guard against inconsistent setting somehow. At least we could throw an error telling folks about the potential problem?

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen as well

**Comment by jmesserly** [comment]
The workaround for now is to grab sourceFactory.dartSdk.context.analysisOptions and set it that way

**Comment by bwilkerson** [comment]
> Luke is hitting this in try.dartlang.org

How? Is there a way to set the options in dartpad?

> I'm wondering if the Analyzer API should guard against inconsistent setting somehow.

That sounds reasonable. We could require that (the important subset of) the SDK's options match the outer context's settings at the point at which the source factory is set. We'd also have to guard against setting a context's options after a source factory has been set (because the context cannot select its own SDK). I'm not sure whether it would break any existing clients, though.

**Comment by lukechurch** [comment]
> Luke is hitting this in try.dartlang.org
> How? Is there a way to set the options in dartpad?

@bwilkerson I've sent you an email with the details, I wanted to be sure that it was actually this issue I was hitting.

**Comment by vsmenon** [comment]
This should be fixed as of @bwilkerson 's change from a couple weeks ago.
