### ISSUE TITLE
Options support to default in to all lints.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25843]
Lints are currently opt-in.  A rationale for this is that lints by design potentially produce false positives and, moreover, the full set of defined lints contains a number of rules that contradict each other.  Confronting users with a flood of contradicting advice would, needless to say, be a bad thing.  However, the downside is that when new lints are added they are not easily discovered.  A possible remedy would be to add a new property to lint rule configuration in `.analysis_options` that enables users to enable all lints and selectively identify those they want to exclude.

Design discussion [here](https://docs.google.com/document/d/1bD4KXt5Hn7VNp1hknhExQHJ9u79-5J8Orwl7f9Rdx_k/edit?ts=56cca1d1).

**Comment by zoechi** [comment]
I don't have access to the doc yet (requested access).  

I'd like predefined groups of lint rules like (without too much reasoning about what groups actually make sense and how they should be named), for example:

- Dart style guide
- Flutter style guide
- Code health
- Common pitfalls
- ...

then in `.analysis_options` 
- enable specific groups 
- disable specific rules 

New rules could get added to the group they fit in automatically (could be a breaking change though when CI builds depend on lint rules not producing warnings).

If this isn't the desired behavior   
- enable each single rule explicitly

A rule can be a member of more than one group.
A command should list all available linter rules.

**Comment by pq** [comment]
Access granted! 

What you describe is exactly where this could ultimately lead: targeted builtin rulesets.  Ideally we should also provide a means for them to be created and hosted externally (e.g., flutter rules would be maintained by flutter, etc.)

**Comment by bwilkerson** [comment]
In general, we do not want lints to be opt-out because we want it to be possible to define contradictory lint rules and allow users to decide which rules to apply. Providing rule sets would solve most of the problems but allow lints to remain opt-in.

**Comment by DanTup** [comment]
> we want it to be possible to define contradictory lint rules and allow users to decide which rules to apply

That sounds totally valid!

> Providing rule sets would solve most of the problems but allow lints to remain opt-in.

Is there a specific case for this that we can subscribe to for updates?

Thanks!

**Comment by bwilkerson** [comment]
This is probably the closest: https://github.com/dart-lang/linter/issues/288. There's been a lot of discussion, but no agreement on exactly how these groups should work.
