### ISSUE TITLE
Spec is unclear about invoking methods on null

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25849]
The spec has:

> Invoking a method on null yields a NoSuchMethodError unless the method is explicitly implemented by class Null.

This should be a property of the null object, not the syntactic null literal (we don't intend any difference).  It's also a property of getters and setters as well as methods.  So while it's all true, it suggests a distinction in the special case that I don't think we intend.

The spec doesn't seem to define "explicitly implemented".  One possible reading is "not inherited", but I don't think that's the intent here.  The language in 10.4 Abstract Instance Members is "concrete method (respectively, concrete getter or concrete setter)" for one that has an implementation.  And the language in 10.1 is "instance methods" for the methods declared in a class and those that are inherited.  So perhaps "concrete instance methods" here?

I really wonder, though, why the normal rules for method, getter, and setter lookup don't just work here.  My quick reading suggests that they actually do work and we could get rid of what looks like a special case for null.

**Comment by lrhn** [comment]
I think this could be reduced to "The `Null` class declares no members and only has the members inherited from the `Object` class.". Maybe we also need to say that it has no constructors.

**Comment by kmillikin** [comment]
@lrhn That seems like a library implementation detail to me.  What about an implementation that wants to use an overridden "toString" method in class Null?

**Comment by lrhn** [comment]
Ack, that's true (we do that). So more like:

> The `Null` class does not declare any instance members that are not also declared by the `Object` class, but may override some inherited members.

Alternatively we should just not write anything since it is, as you say, a library matter. The spec does enforce some things on the libraries, but here it doesn't really need to. It could be explanatory/non-normative text saying that `null` won't do anything useful.

**Comment by kmillikin** [comment]
This has almost been fixed.  The spec still says that the Null class does not declare any methods except those also declared by Object.

A pedantic reading is that this does allow Null to have arbitrary getters, setters, and instance variables.

**Comment by eernstg** [comment]
No milestone now: This clarification may still need some work in order to be completed, but this will not block Dart 2.

**Comment by eernstg** [comment]
Closing: The special casing of the null literal is gone and the members of `\code{Null}` have been specified explicitly, as of commit 843bb96813f9a171c7257fcd5e282ff1d323c53d.
