### ISSUE TITLE
Analyzer package not avaliable from pub.dartlang.org

### ISSUE THREAD

**Issue by vgordievskiy** [dart-lang/sdk#25842]
url https://pub.dartlang.org/api/packages/analyzer return 500 Internal Server Error code

**Comment by zoechi** [comment]
I tried a few others and always got the same response. There were already issues on Sunday and at some time since then. I guess this should be reported in https://github.com/dart-lang/pub-dartlang-dart though.

**Comment by zoechi** [comment]
dart-lang/pub-dartlang-dart#48

**Comment by vgordievskiy** [comment]
now this works.
