### ISSUE TITLE
Hint when @protected members are used outside instances of subclasses.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25841]
See `@protected`annotation definition here: https://codereview.chromium.org/1719353002/.

**Comment by pq** [comment]
Support for methods landed in https://github.com/dart-lang/sdk/commit/84f32fe5a653824b127ceed729d5831191ff06a6.
Support for members, in general, landed in https://github.com/dart-lang/sdk/commit/212a058f13f6135cf2ce89d1d3ea58e09731c763.

**Comment by Hixie** [comment]
qv https://github.com/dart-lang/sdk/issues/3193, https://github.com/dart-lang/sdk/issues/6119

**Comment by pq** [comment]
`meta` package [published](https://pub.dartlang.org/packages/meta).  Closing out.

**Comment by donny-dont** [comment]
@pq is the analyzer package going to get a push as well with this? I didn't see the protected checks in 0.27.3-alpha.0

**Comment by bwilkerson** [comment]
Eventually, yes. We're in the process of implementing several annotations and it might make sense to wait for more of them to be implemented rather than flooding the world with lots of extra versions.

Do you need it for something?

**Comment by donny-dont** [comment]
@bwilkerson I can certainly wait. Been waiting a long time for `@protected` so whats a little longer. Great work all around :+1:

**Comment by bwilkerson** [comment]
I guess the question really is, do you need a version of the analyzer package published to pub, or are you just waiting for a new build of the SDK with this support in it? (The two are not necessarily kept in sync.)

**Comment by donny-dont** [comment]
I have a library that will load a library through the analyzer then gather the metadata and then let you run queries against the data. I have support for deprecated and override and I was going to add support for instantiating `@protected` whenever that lands.

**Comment by bwilkerson** [comment]
It isn't clear that you need a new version of the analyzer package. Analyzer doesn't need to understand an annotation to capture it (though it does have some utility methods for the annotations it knows about). And the annotation itself is defined in the 'meta' package (https://pub.dartlang.org/packages/meta), so you can start adding it to code today. You probably have enough to do what you want, although the utility methods would be helpful.

**Comment by donny-dont** [comment]
It was the utility methods ala `isDeprecated` that would be nice. No rush on my end.
