### ISSUE TITLE
Specification defines features in terms of function-literal applications which isn't always a valid rewrite in async contexts.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#25858]
Example, `o?.m(a1, . . . , an, xn+1 : an+1, . . . , xn+k : an+k)` is defined as equivalent to `((x) => x == null?null : x.m(a1, . . . , an, xn+1 : an+1, . . . , xn+k : an+k))(o)`.

This moves the expressions `a1` .. `an+k` into a new non-async function. If the original expression is in an async function and any of these expressions contain an `await`, the resulting rewrite is incorrect.

The specification needs another way to introduce new expression-level bindings without resorting to function literals, perhaps `let x = e1 in e2` which wouldn't change the scope.

**Comment by kmillikin** [comment]
Dart itself needs `let x = e1 in e2`, not just the spec :)

**Comment by lrhn** [comment]
I completely agree, but that's #25275 :)

**Comment by eernstg** [comment]
No milestone now: This is independent of Dart 2. Note that several changes to the language specification have already eliminated such function literals and applications thereof. The issue still pertains to any remaining ones.

**Comment by eernstg** [comment]
Note that #24508 is a special case of this issue, so it should be handled together with this one.

**Comment by lrhn** [comment]
I believe this has been fixed. I'll close this now, and if we find that there are still cases left, we can reopen.
