### ISSUE TITLE
The equivalence for string interpolation does not hold

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25853]
The spec has:

> An interpolated string ‘s1${e}s2’ is equivalent to the concatenation of the strings ‘s1’, e.toString() and ‘s2’. Likewise an interpolated string “s1${e}s2” is equivalent to the concatenation of the strings “s1”, e.toString() and “s2”.

This equivalence does not seem to hold in all cases.
- If e is a library prefix, then the interpolation is a compile-time error and the other is a call to the library's exported toString function.
- If e is the name of a class, then the interpolation calls toString() on the Type object reifying the class and the other is a call to a static toString member.

Both of these could probably be repaired by writing `(e).toString()` for the equivalence or else `((x) => x.toString())(e)`
- If e evaluates to an object with an overridden toString() method that does not return a string, then e.toString() is not a string so 'the concatenation of the strings' doesn't seem right.

This could be repaired by saying something like the string concatenation of the objects 's1', ...

**Comment by kmillikin** [comment]
Another problem with this section is that the order of evaluation of the subexpressions of a string interpolation is unspecified.

I read "‘s1${e}s2’ is equivalent to the concatenation of the strings ‘s1’, e.toString() and ‘s2’" as saying that all three of 's1', e.toString(), and 's2' have been evaluated (since it says they are strings, and they are not strings until they are evaluated).  That doesn't seem to require them to be evaluated in the order that they are listed, though.

**Comment by kmillikin** [comment]
@lrhn

**Comment by lrhn** [comment]
This has been fixed in the spec. 
The evaluation order is now explicitly left-to-right, and prefixes are evaluated as-is, not with a syntatically appended `.toString()`.
