### ISSUE TITLE
Redundant, unclear, and missing cases in the definition of function termination

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25850]
Section 16.14 Function Invocation (3rd edition) defines function termination:

> Execution of f terminates when the first of the following occurs:
> • An exception is thrown and not caught within the current function activation.
> • A return statement (17.12) immediately nested in the body of f is executed and not intercepted in a finally (17.11) clause.
> • The last statement of the body completes execution.

The last statement of the body is always a return statement because one is implicitly appended to the body to make this true.

It seems like the third case of the definition implies the second one, and thus the third case is redundant.

**Comment by kmillikin** [comment]
I'm not going to file yet another issue but the first clause above is not completely clear, either.

By the obvious reading, if f calls g and g calls h and h throws an exception that is caught by g, then f terminates because the first of those things that happened was that an exception was thrown and not caught within the current function activation.

We want to make it not caught within the activation of f.  We're really defining termination of an activation, not a function.

**Comment by kmillikin** [comment]
The list is missing two cases of function termination.  From the spec for yield*:

> If the enclosing function m is marked async* and the stream u associated with m has been canceled, then let c be the finally clause (17.11) of the innermost enclosing try-finally statement, if any. If c is defined, let h be the handler induced by c. If h is defined, control is transferred to h. If h is undefined, the immediately enclosing function terminates.

And from the specification for yield*:

> If the stream u associated with m has been canceled, then let c be the finally clause (17.11) of the innermost enclosing try-finally statement, if any. If c is defined, let h be the handler induced by c. If h is defined, control is transferred to h. If h is undefined, the immediately enclosing function terminates.

Both of these constructs can terminate the immediately enclosing function.

**Comment by lrhn** [comment]
An option is to just say that a `yield` after subscription cancellation will act equivalently to `return;`, which it does, instead of specifying the same behavior again.

**Comment by kmillikin** [comment]
@lrhn That is definitely better.  It nicely avoids the bug #25921 where the problem is that yield and yield* execute a return without setting the current return value.
