### ISSUE TITLE
The specification of current return value/current exception should be streamlined

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25859]
They're hard to reason about because they're basically a mutable variable per activation (current return value) and a mutable global variable (current exception + active stack trace).

The spec should adopt either one, but not both, of:
1. They are only set when "in the immediate process of" returning or throwing and they are always both undefined when executing Dart source code.
2. We don't care about their values at places where they can't possibly be observed.  (They are observed at function termination and by on-catch matching.)

If 1, then the current exception should be made undefined before executing on-catch statements.  It isn't currently, but that might be a bug.  Then when returning it should be unnecessary to make the current exception undefined.  It will already be undefined, so we could just "assert" it.  And when throwing or rethrowing it should be unnecessary to make the current return value undefined.

If 2, then it is not necessary to save and restore return values and exceptions for catch or finally blocks.  It is then mandatory to make the current exception undefined when returning (just before it might be observed) and the current return value undefined when throwing or rethrowing.  We still have the property that they are not simultaneously defined.

I think either of these would make reasoning about them a bit simpler because they wouldn't be mutated unnecessarily.  I prefer 2, because then they are nicely available to the spec (for rethrow, for example) and it more closely matches what an implementation might do.  It also has the advantage of not specifying mutation that is unobservable.  That seems like a nice property of a specification.

Another complication is that the specification for exception handling includes impossible control flows (I think).  While that's not really wrong, it is misleading and makes reasoning about exception handling complicated.
- In the case that a try handler catches an exception and there is no matching on-catch clause, then the finally clause will be executed.

> If no on-catch clause is found, the finally clause is executed. Then, execution resumes at the end of the try statement.

There is no "then".  The finally clause is executed with a current exception defined because we are in a try handler.  In that case, the finally clause rethrows (or else control does not fall off the end of the finally statement).  Control flow from unhandled exception to the end of the try is confusing and we should instead do the equivalent of assert(false).
- A finally handler is only entered by a thrown exception inside the catch part of by a return inside the try or catch parts.

> Then the finally clause is executed. Let m be the immediately enclosing function. If r is defined then the current return value is set to r and then....
> Otherwise, execution resumes at the end of the try statement.

In the case of a thrown exception, the finally clause rethrows (or else control does not fall off the end of the finally statement).  In the case of a return, then r is defined.  There is no "otherwise".  The apparent control flow from a finally entered by throwing or returning to the end of the try statement is confusing.

**Comment by kmillikin** [comment]
>> Then the finally clause is executed. Let m be the immediately enclosing function. If r is defined then the current return value is set to r and then....
>> Otherwise, execution resumes at the end of the try statement.

> In the case of a thrown exception, the finally clause rethrows (or else control does not fall off the end of the finally statement). In the case of a return, then r is defined. There is no "otherwise". The apparent control flow from a finally entered by throwing or returning to the end of the try statement is confusing.

I forgot about yield and yield* inside async* functions.  They will enter the finally handler without setting either of the current return value or current exception.  In that case, control flow from the handler to the end of the try statement is not actually dead but I think that's a bug.  Filed #25921.

**Comment by lrhn** [comment]
Working of a rewrite that addresses this issue: https://codereview.chromium.org/2399343002/
It's work in progress.
