### ISSUE TITLE
Analyzer shows wrong hint if if finds something like name?.firstname = "ddd"

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25852]
This

``` dart
class _Name {
    String firstname;
    String lastname;
    _Name(this.firstname, this.lastname);
}

main() async {
    group('Language', () {
        setUp(() { });

        test('> Assignment', () {
            final _Name name = null;

            name?.firstname = "Mike";
            expect(name,isNull);

        }); // end of 'Assignment' test
    });
    // End of 'Language' group
}
```

brings `[hint] The class '_Name' is not used` - in my opinion this is wrong

**Comment by srawlins** [comment]
But... there is no `_Name`... you made it null.

https://dartpad.dartlang.org/d28a7b4c806ea717d37db04a3bba15d1

**Comment by MikeMitterer** [comment]
null doesn't mean it's not used - it's value is just null.
I modified your dartpad a bit - uses "if" now to check a - the same result. As said - to me the warning is wrong.

**Comment by bwilkerson** [comment]
I agree with Mike. The class is clearly being used as a type annotation and the hint should not be produced.

**Comment by srawlins** [comment]
Analyzer no longer reports `[hint] The class '_Name' is not used`.
