### ISSUE TITLE
The create_sdk target rebuilds the summary files always, even if nothing has changed

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25851]
Building the create_sdk target always runs certain commands, even if no files have changed since the last build.  This should be fixed if possible, listing the inputs of these steps correctly, so they only run if the inputs have changed.

  TOUCH utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  ACTION utils_compiler_compiler_gyp_dart2js_target_generate_snapshots utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  TOUCH utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
  ACTION utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
Generating spec mode summary.
    Done in 19997 ms.
Generating strong mode summary.
    Done in 19042 ms.
  ACTION Creating SDK. out/ReleaseX64/dart-sdk/README
rm utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate

**Comment by scheglov** [comment]
Is this true?
I cannot reproduce this.

```
scheglov@scheglov-macbookpro3:~/Source/Dart/sdk.git/sdk (master)$ ./tools/build.py --mode release --arch ia32 create_sdk
Please set JAVA_HOME to /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home
xcodebuild -project dart.xcodeproj -target create_sdk -configuration ReleaseIA32 SYMROOT=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild
Build settings from command line:
    SYMROOT = /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild

** BUILD SUCCEEDED **```

As you can see, no summaries or any other steps.

OTOH inputs are probably incorrect, but in the opposite way - they don't list files which I think hey should include - all libraries and analyzer.

**Comment by whesse** [comment]
OK, maybe it is something on the bots.

On Mon, Feb 29, 2016 at 7:23 PM, Konstantin Scheglov <
notifications@github.com> wrote:

> Is this true?
> I cannot reproduce this.
>
> scheglov@scheglov-macbookpro3:~/Source/Dart/sdk.git/sdk (master)$ ./tools/build.py --mode release --arch ia32 create_sdk
> Please set JAVA_HOME to /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home
> xcodebuild -project dart.xcodeproj -target create_sdk -configuration ReleaseIA32 SYMROOT=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild
> Build settings from command line:
>     SYMROOT = /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild
>
> ** BUILD SUCCEEDED **```
>
> As you can see, no summaries or any other steps.
>
> OTOH inputs are probably incorrect, but in the opposite way - they don't list files which I think hey should include - all libraries and analyzer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/25851#issuecomment-190320833>.
>



-- 
William Hesse

**Comment by scheglov** [comment]
This [CL](https://codereview.chromium.org/1749813003) widens the input set to include the whole `sdk/lib` folder because we generate summaries for these files.

**Comment by whesse** [comment]
I have just seen this reproducing on a bot.  I'll try it locally.:

  TOUCH out/ReleaseIA32/obj.target/utils/dartdoc/dartdoc.stamp
Generating spec mode summary and index.
  TOUCH out/ReleaseIA32/obj.target/utils/analysis_server/analysis_server.stamp
  TOUCH out/ReleaseIA32/obj.target/utils/compiler/dart2js.stamp
  TOUCH out/ReleaseIA32/obj.target/utils/pub/pub.stamp
	Done in 24005 ms.
Generating strong mode summary and index.
	Done in 21633 ms.
  TOUCH out/ReleaseIA32/obj.target/utils/dartanalyzer/dartanalyzer.stamp
  ACTION Creating SDK. out/ReleaseIA32/dart-sdk/README
  TOUCH out/ReleaseIA32/obj.target/create_sdk_internal.stamp
  TOUCH out/ReleaseIA32/obj.target/create_sdk.stamp
rm utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate


golem@builder2-1a:/tmp/buildFolder4OovOj/sdk$ ./tools/build.py --mode=release --arch=ia32 create_sdk
make -j 8 BUILDTYPE=ReleaseIA32 create_sdk
  TOUCH utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  ACTION utils_compiler_compiler_gyp_dart2js_target_generate_snapshots utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  TOUCH utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
  ACTION utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
Generating spec mode summary and index.
	Done in 24995 ms.
Generating strong mode summary and index.
	Done in 22241 ms.
  ACTION Creating SDK. out/ReleaseIA32/dart-sdk/README
rm utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate


golem@builder2-1a:/tmp/buildFolder4OovOj/sdk$ ./tools/build.py --mode=release --arch=ia32 create_sdk
make -j 8 BUILDTYPE=ReleaseIA32 create_sdk
  TOUCH utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  ACTION utils_compiler_compiler_gyp_dart2js_target_generate_snapshots utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
  TOUCH utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
  ACTION utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
Generating spec mode summary and index.
	Done in 24485 ms.
Generating strong mode summary and index.
	Done in 21105 ms.
  ACTION Creating SDK. out/ReleaseIA32/dart-sdk/README
rm utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
golem@builder2-1a:/tmp/buildFolder4OovOj/sdk$

**Comment by stereotype441** [comment]
I am able to reproduce this on Linux but not Mac.  I am currently suspecting a bug in the "gyp" tool's "make" backend.  The reason the failure doesn't occur on Mac is that Mac builds use XCode, not "make".

Here is a snippet from the makefile that gyp generates:

    $(obj)/gen/spec.sum: obj := $(abs_obj)
    $(obj)/gen/spec.sum: builddir := $(abs_builddir)
    $(obj)/gen/spec.sum: TOOLSET := $(TOOLSET)
    $(obj)/gen/spec.sum $(obj)/gen/strong.sum: utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
        @:
    .INTERMEDIATE: utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate
    utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries.intermediate: $(builddir)/dart ... FORCE_DO_CMD
        $(call do_cmd,touch)
        $(call do_cmd,utils_dartanalyzer_dartanalyzer_gyp_dartanalyzer_target_generate_summaries)

For reasons I don't entirely understand, the presence of `FORCE_DO_CMD` as a dependency of the intermediate file causes the actions to run on every build.  I'm guessing there's a strange interaction between the "phony" rule for `FORCE_DO_CMD` and the "intermediate" rule for `target_generate_summaries.intermediate` (both "phony" and "intermediate" rules have strange behaviors in Make).

If I change the build action so that it only generates a single output file, the problem goes away.

I will look into whether it's possible to break down our summary-related build steps so that each one of them outputs a single file.

**Comment by scheglov** [comment]
Possible solution.
Ideally would be great to fix the build tools.
https://codereview.chromium.org/1775973003

**Comment by rmacnak-google** [comment]
The SDK builders now verify a second build invocation does nothing.
