### ISSUE TITLE
strong mode ignores incorrect return type of async function

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25854]
Consider:
```dart
import 'dart:async';
abstract class SubFuture<T> implements Future<T> {}
SubFuture<int> foo() async {
  return 42;
}
main() async {
  print(await foo());
}
```
This program will:
* work in VM production mode
* fail in VM checked mode (type `_Future` is not a subtype of type `SubFuture<int>`)
* work in Analyzer normal mode
* work in Analyzer strong mode

In strong mode, we should be able to see that this can't work. A user-defined Future subtype is not possible.

At least one thing is going wrong here: when we match the declared return type during inference, we use flatten(T). Flatten is a bit too powerful as it will search the type hierarchy looking for Future. All we should really do is match Future directly (and Iterable for `sync*`, Stream for `async*`).

`sync*` and `async*` have a similar problem but it may be hidden currently by how matchTypes is used. matchTypes is a big hammer though, and doing more work than is needed. Discovered while investigating https://codereview.chromium.org/1724543002/.

**Comment by jmesserly** [comment]
Note, we could let this pass in Analyzer strong mode, but use a runtime check in DDC. But that doesn't seem right. The problem is easy to detect statically.

Also the same bug happens with something like `SubFuture<int> foo() async {}` so changing return/yield won't be enough to fix.

**Comment by leafpetersen** [comment]
This seems like something we should reject statically.  If I'm understanding this correctly, there's no situation in which you will actually get a SubFuture out, so why allow the API to pretend that it will return one?

**Comment by jmesserly** [comment]
Yup, exactly. "async" function bodies will return the same type as `new Future` constructors: some implementation controlled private subtype of Future. In practice, I think it's always [dart:async `_Future<T>`](https://github.com/dart-lang/sdk/blob/6a75757e47af1202dabc21f4201a786a27a9f280/sdk/lib/async/future_impl.dart#L120).

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1910033002/
