### ISSUE TITLE
Command line Analyzer bug- new line in message when using --format=machine

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#25864]
Using: --format=machine 

And this code from /analysis_server/lib/plugin/protocol/generated_protocol.dart:

```
-   STATIC_TYPE_WARNING
-   STATIC_WARNING
-   SYNTACTIC_ERROR
-   TODO
- }
  *
- Clients may not extend, implement or mix-in this class.
  */
```

The following is output, note that the issue is that there is a newline before the ' \* }':
```
INFO|TODO|TODO|/third_party/dart_lang/trunk/pkg/analysis_server/lib/plugin/protocol/generated_protocol.dart|8162|6|9|TODO
- }
```
And since ' \* }' isn't in the 'INFO|TODO|TODO|/file/path/...' format, it cannot be parsed as promised by  --format=machine

2 issues should be fixed: TODO regex should be fixed not to pick up the above TODO as a TODO, Messages (at least for TODOs), should be scrubbed for new lines.

**Comment by bwilkerson** [comment]
If this is actually breaking something feel free to bump the priority.

**Comment by devoncarew** [comment]
Closing; we no longer show TODOs for the cli analyzer.
