### ISSUE TITLE
Summary files not available to sdk/bin/dartanalyzer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25861]
During development, we frequently run the analyzer using `sdk/bin/dartanalyzer`, which is a bash script that runs the analyzer from source, pointing it to the source files for the sdk (which are located in `sdk/`).  For example, this is how `test.sh` runs the analyzer.  This is convenient because it lets us run the latest analyzer without having to rebuild it from source.

However, if we want to use summaries, this is a problem, because the analyzer looks for summaries inside directory `lib/_internal/` of the sdk.  Since `sdk/bin/dartanalyzer` configures it to use `sdk/` as its sdk, this means it looks in `sdk/lib/_internal/`.  But this directory doesn't contain any summaries, since summaries are a build artifact.  Summaries only show up in output directories like `out/ReleaseIA32/dart-sdk/lib/_internal/`.

Once summary support is enabled by default, we will want to ensure that summaries are available to `sdk/bin/dartanalyzer`, so that the testing performed by the buildbots will exercise summary deserialization code.

**Comment by kevmoo** [comment]
@stereotype441 – still an issue?

**Comment by stereotype441** [comment]
This was fixed sometime in the last two years.
