### ISSUE TITLE
MouseEvent.dataTransfer.files is empty on drop event

### ISSUE THREAD

**Issue by vgordievskiy** [dart-lang/sdk#25863]
https://www.dartlang.org/samples/dndfiles at current moment not works on drop event.

Section 1: Using Form Input, Drag and Drop, and Reading Files
https://github.com/dart-lang/dart-samples/blob/master/html5/web/file/dndfiles/dndfiles.dart

**Comment by kwalrath** [comment]
@Sfshaza could you look into this?

**Comment by vgordievskiy** [comment]
any updates for this?

**Comment by srawlins** [comment]
Hi @kwalrath do we still run the Samples site?

**Comment by srawlins** [comment]
Samples has since been archived, including drag-and-drop.
