### ISSUE TITLE
Process.runSync is not robust w.r.t. capturing standard output streams

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25862]
When `Process.runSync` fails to capture a standard output stream, it throws:

```
Caught expected error while stopping application: FileSystemException: Error retreiving socket type, path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._socketType (dart:io-patch/stdio_patch.dart:35)
#1      _RawSocket._RawSocket._readPipe (dart:io-patch/socket_patch.dart:1248)
#2      _Socket._Socket._readPipe (dart:io-patch/socket_patch.dart:1515)
#3      _ProcessImpl._ProcessImpl (dart:io-patch/process_patch.dart:263)
#4      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:596)
#5      Process.runSync (dart:io-patch/process_patch.dart:64)
#6      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:98)
#7      runSync (package:flutter_tools/src/base/process.dart:74)
#8      AndroidDevice.stopApp.<stopApp_async_body> (package:flutter_tools/src/android/android_device.dart:304)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
```

This currently affects Flutter trying to launch `adb` to work with Android devices.

(also the word "retreiving" is misspelled)

**Comment by johnmccutchan** [comment]
@sgjesse

**Comment by johnmccutchan** [comment]
Other info: This is happening on MacOS setting up the stdout stream for the spawned process.

**Comment by johnmccutchan** [comment]
fstat on stdout returns an error and sets errno=9

**Comment by johnmccutchan** [comment]
One final bit of information: The Dart script launches the same command line once at start and once before exit, the first launch succeeds the second launch fails with the error seen above.

I've put up a work around [CL](https://codereview.chromium.org/1736123002/) but I'm not sure if this is the correct sync.

**Comment by sgjesse** [comment]
I have look into the code, and as far as I can see the problem is that the `_RawSocket._readPipe` constructor is broken. In this case we are calling it with fd being null, and in that case it still tries to do fstat - in that case `_getStdioHandle` (which is `Socket_GetStdioHandle` in `socket.cc`) is not called, and the native field is not set to anything - not sure what value it has then.

@johnmccutchan I think this is the right patch, but maybe you can verify where you cna reproduce the issue.

```
diff --git a/runtime/bin/socket_patch.dart b/runtime/bin/socket_patch.dart
index 09904b4..1ec51b7 100644
--- a/runtime/bin/socket_patch.dart
+++ b/runtime/bin/socket_patch.dart
@@ -1243,9 +1243,11 @@ class _RawSocket extends Stream<RawSocketEvent>
     native.isClosedWrite = true;
     if (fd != null) _getStdioHandle(native, fd);
     var result = new _RawSocket(native);
-    result._isMacOSTerminalInput =
-        Platform.isMacOS &&
-        _StdIOUtils._socketType(result._socket) == _STDIO_HANDLE_TYPE_TERMINAL;
+    if (fd != null) {
+      var socketType = _StdIOUtils._socketType(result._socket);
+      result._isMacOSTerminalInput =
+          Platform.isMacOS && socketType == _STDIO_HANDLE_TYPE_TERMINAL;
+    }
     return result;
   }
```

**Comment by yjbanov** [comment]
Just checked that this works. I cannot confirm if the streams are functioning correctly as I'm not using them, but I am able to launch a process using `Process.runSync` and it runs and completes with status `0`.

**Comment by johnmccutchan** [comment]
@sgjesse Confirmed your fix works. Want me to land it or will you?

**Comment by sgjesse** [comment]
@johnmccutchan thanks for testing.

Landed TBR from a new CL, and filed a merge request #25908.
