### ISSUE TITLE
The versioning of the spec on the web page and on the spec's cover don't agree

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25866]
I don't know how to triage this issue.  I keep getting confused about versioning of the spec.

https://www.dartlang.org/docs/spec/ claims to link to the 3rd edition of the spec.  But when I click on the link I get a cover page that says 4th edition.  This is confusing.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/www.dartlang.org#1554
