### ISSUE TITLE
Dartium affected by SSL bug on Ubuntu

### ISSUE THREAD

**Issue by Klikini** [dart-lang/sdk#25865]
The following Ubuntu bug has been fixed through a Chromium update, but **Dartium has been not updated with the fix yet**, making it impossible to use Dartium for the Dart app I need to test (the login system makes HTTPS requests to our authentication server, and the bug breaks all HTTPS requests!) 

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1547762

The problem, which applies to all `https://` URLs:
![image](https://cloud.githubusercontent.com/assets/1693960/13339561/57fae3d0-dbef-11e5-90a1-860369737f7a.png)

I should probably also point out that SSL works fine on the same system under Chrome, Firefox, Opera, cURL, etc.

**Comment by alan-knight** [comment]
In the short term, the workaround in the bug of --ssl-version-max=tls1 seems to work as a workaround.

**Comment by Klikini** [comment]
@alan-knight This works, thank you!

**Comment by ThomasLocke** [comment]
I can confirm that this bug/problem is also present when using the newly released Slackware 14.2 (64 bit).

The workaround proposed by @alan-knight solves the problem.

**Comment by terrylucas** [comment]
Thomas this problem should no longer exist with Dartium 1.17 or newer (based on Chromium 45).

**Comment by terrylucas** [comment]
We've also removed a bad patch from Chromium 45 dealing the ssl3 in Dartium build 1.18 dev 4.

**Comment by ThomasLocke** [comment]
@terrylucas I am using Dartium 1.17 (the latest from dartlang.org), and the problem is still very much alive and well on my box. The only way for me to access Google HTTPS URLs is with the @alan-knight workaround.

**Comment by terrylucas** [comment]
Thomas could you try [https://storage.googleapis.com/dart-archive/channels/dev/release/1.18.0-dev.4.2/dartium/dartium-linux-x64-release.zip](Dartium 1.18.0-dev.4.2) unzip this file and launch dartium in the extracted directory

**Comment by ThomasLocke** [comment]
Epic win @terrylucas!

I've no idea why 1.18.0 works, since it seems to be the same as 1.17.1 (45.0.2454.104)?

**Comment by terrylucas** [comment]
Its not quite the same see [https://codereview.chromium.org/2148453002](https://codereview.chromium.org/2148453002) removed the ChaCha20+Poly1305 cipher code which collided with other NSS/SSL work.
