### ISSUE TITLE
[JS Interop] Allow @JS namespace annotation without library directive

### ISSUE THREAD

**Issue by har79** [dart-lang/sdk#25872]
Library directives are now, in most cases, optional and not very useful. However, they are required for the  @JS namespace annotation. It would be nice if this were not the case.

This is similar to an issue with @web_components.HtmlImport: https://github.com/dart-lang/web-components/issues/40. The solution suggested in that issue of looking for the annotation on all top-level directives and declarations wouldn't work since @JS means something different when applied to a declaration, however it seems possible to just look for the annotation on the first directive in the file, as with @test.TestOn.

**Comment by jacob314** [comment]
Won't fix. Requiring the @JS annotations at the library level is needed for Dartium dartup performance.
