### ISSUE TITLE
Set<E>.contains takes Object not E

### ISSUE THREAD

**Issue by ianloic** [dart-lang/sdk#25878]
I just had a bug (thankfully caught during code review) because I was passing the wrong value to Set.contains. The incorrect value was of a different type than the Set holds, but dartanalyzer didn't complain. Then I looked at the docs and found that Set.contains takes an Object rather than the element type E. Most other methods on Set<E> take E.

**Comment by lrhn** [comment]
This is deliberate.
You are generally able to treat a `Set<Subclass>` as a `Set<Superclass>` as long as you are only reading from it (you can't add a `Superclass` instance, but all elements you extract from the set can be assigned to a `Superclass` variable).

For this to work, you need to be able to ask if `set.contains(superClassInstance)` for any super-class of the element type. We can't describe that in the Dart type system, so we have to allow any object to be passed.

If you check the Java `Set` class, its `contains` method has the same typing - it accepts object.

**Comment by lrhn** [comment]
As a follow-up, asking for a super-class instance isn't even enough.
If you treat a `Set<int>` as a `Set<num>`, you also need to be able to pass a double to `contains`.
If you go even further and treat it as a `Set<Object>`, any object need to be accepted. You are not actually casting anything, it's just that `Set<int>` is assignable to `Set<Object>`, and as long as you only read, it should work as a `Set<Object>`, so `contains` must be able to accept any object.
