### ISSUE TITLE
I wish I could control what the analyzer analyzed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25873]
Right now, to analyze all the flutter code, we create one big main.dart file that imports all our entry points, and tell it to analyze everything, including packages. We have to include packages because our code is spread across many packages, and we want it all checked.

This is great, except that some of the packages come from pub, and we can't fix those (or at least, we don't want errors in those libraries to make our build go red).

Right now we filter out the messages from anything that points to the dart cache, but this means that our builds take 30-60 seconds when they could take much less because they don't have to be analyzing anything outside our repo.

It would be great if we could say that all code that came in via a path should be analyzed, but anything that came in via pub should not.

**Comment by pq** [comment]
This relates to the long-standing ask for directory/package-scoped analysis (https://github.com/dart-lang/sdk/issues/25129).

**Comment by bwilkerson** [comment]
Closing as a duplicate.
