### ISSUE TITLE
instantiate interface types to bounds in Strong Mode?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25877]
For example, `Rectangle<T extends num>`. In this case, `Rectangle<dynamic>` will be rejected.

I think we may have a soundness issue around this. (I don't know that we're validating bounds in either generic function or interface types.)

FWIW, we already instantiate generic function types to their bounds by default.

**Comment by jmesserly** [comment]
(Marked high priority as I believe this is a soundness issue)

**Comment by vsmenon** [comment]
@leafpetersen

Do we need this in strong mode or just DDC runtime?

**Comment by jmesserly** [comment]
IMO we should validate bounds statically. Indeed this is on the list for generic methods: https://github.com/dart-lang/sdk/issues/25200. 
```dart
class B {}
class D extends B {}

class C<T extends B> {
  T get t => null;
}

main() {
  // ERROR
  //var x = new C<D>().t;
  //x = 42;

  // no error ... (y is dynamic)
  var y = new C().t;
  y = 42;
}
```

Otherwise we can't rely on `T extends B` in codegen and have to treat everything as a dsend. Kind of defeats the point of a type bound.

**Comment by jmesserly** [comment]
Also we're in an inconsistent state right now, because generic methods do instantiate to bounds (statically).

**Comment by leafpetersen** [comment]
Odd - we seem to check the bounds when they're there explicitly, but not for implicit instantiations.  There must be a difference code path in the analyzer.  We should either reject the instantiation or else instantiate to bounds.  I'd advocate for the latter.
