### ISSUE TITLE
dart:math max and min type annotation does not match 'double'

### ISSUE THREAD

**Issue by manuelF** [dart-lang/sdk#25879]
```dart
import 'dart:math';
List<double> songs = <double>[1.0, 2.0, 3.0, 4.0];
double get score => songs.reduce(max);
```

Running `dartanalyzer --strong file.dart`
`[error] Type check failed: max (<T extends num>(T, T) → T) is not of type (double, double) → double `
`[warning] The argument type '(T, T) → T' cannot be assigned to the parameter type '(double, double) → double' `

However, double extends num[1], so the type annotation should match.

[1]https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/double.dart#L25

**Comment by vsmenon** [comment]
@manuelF I believe this was fixed recently.  I see no error or warning in version `1.15.0-dev.3.0`.  Are you on stable channel?

**Comment by manuelF** [comment]
That can be the issue, I am running an older release apparently.
```bash
$> dartanalyzer --version
dartanalyzer version 1.14.0-dev.7.2
```

Thanks!
