### ISSUE TITLE
Class 'CompilationUnitElementImpl' has no instance getter 'type'.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25882]
> Dart analysis server, SDK version 1.15.0-edge.e4b800845b42381da08a1eac9f906d7ebb12a2a7, server version 1.14.0, error: Task failed: GenerateHintsTask for source /home/zoechi/dart/bwu_ng_quick_nav/lib/bwu_ng_quick_nav.dart
Unexpected exception while performing GenerateHintsTask for source /home/zoechi/dart/bwu_ng_quick_nav/lib/bwu_ng_quick_nav.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:249)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1125)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1123)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:837)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:891)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#14     _rootRun (dart:async/zone.dart:895)
#15     _CustomZone.run (dart:async/zone.dart:790)
#16     _CustomZone.runGuarded (dart:async/zone.dart:696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
Caused by Class 'CompilationUnitElementImpl' has no instance getter 'type'.
>
NoSuchMethodError: method not found: 'type'
Receiver: Instance of 'CompilationUnitElementImpl'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      BestPracticesVerifier._checkForInvalidProtectedPropertyAccess (package:analyzer/src/generated/resolver.dart:669)
#3      BestPracticesVerifier.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:241)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8707)
#5      AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:936)
#6      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7070)
#7      RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:940)
#8      BestPracticesVerifier.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:210)
#9      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7066)
#10     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:936)
#11     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5502)
#12     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:838)
#13     BestPracticesVerifier.visitIfStatement (package:analyzer/src/generated/resolver.dart:164)
#14     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5498)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7429)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1253)
#17     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:586)
#18     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1249)
#19     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:936)
#20     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1200)
#21     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:592)
#22     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1196)
#23     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:936)
#24     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6955)
#25     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:934)
#26     BestPracticesVerifier.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:203)
#27     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6946)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7429)
#29     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1857)
#30     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:622)
#31     BestPracticesVerifier.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:125)
#32     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1797)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7429)
#34     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2376)
#35     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:646)
#36     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2369)
#37     GenerateHintsTask.internalPerform (package:analyzer/src/task/dart.dart:2692)
#38     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#39     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#40     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#41     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:249)
#42     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1125)
#43     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#44     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1123)
#45     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#46     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:837)
#47     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#48     _rootRun (dart:async/zone.dart:891)
#49     _CustomZone.run (dart:async/zone.dart:790)
#50     _CustomZone.runGuarded (dart:async/zone.dart:696)
#51     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#52     _rootRun (dart:async/zone.dart:895)
#53     _CustomZone.run (dart:async/zone.dart:790)
#54     _CustomZone.runGuarded (dart:async/zone.dart:696)
#55     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#56     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#57     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#58     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)

> Dart VM version: 1.15.0-edge.a8d71a461d82a54a5d9a2a7feac4faa74981aafc (Fri Feb 26 15:24:12 2016) on "linux_x64"

**.analysis_options**
```yaml
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - public_member_api_docs
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - package_names

```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1749753002/
