### ISSUE TITLE
dart:svg supports SVG APIs like pathSegList, but chrome doesn't anymore

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/sdk#25887]
About a year ago, I built [this chart](http://alexanderjohr.blogspot.de/2014/05/dart-redmine-spent-time-visualizer-now.html) using dart:svg. I now had to rewrite it, because it stopped working in Chrome. One reason was, that I used the SVG API to draw the paths. For example:

I used the pathSegList to add points to the path:

```
    PathElement capSvgPath = new PathElement();
    PathSegList pathSegList = capSvgPath.pathSegList;
    pathSegList.appendItem(capSvgPath.createSvgPathSegMovetoAbs(0, 0));
```

And that already causes the problem, because pathSegList does exist in Dartium, but dosn't exist in Chrome anymore. It seams, that it was removed from Chrome, as it was removed from the SVG standard.

I rewrote the hole thing using d3 and the package:js library for js interop. Now I set the `d` attribute of the path directly and it works again:

```
    PathElement capSvgPath = new PathElement();

    LineFunction lineFunction = line()
      ..x(allowInterop(([LinePoint point, num index]) => point.x))
      ..y(allowInterop(([LinePoint point, num index]) => point.y))
      ..interpolate("linear-closed");

    var lineData = lineFunction.apply(lineFunction, [capCoordiantes]);
    capSvgPath.setAttribute("d", lineData);
```

But the fact that it ran in Dartium and not in Chrome confused me. I spent hours to find out, that it has nothing to do with my code, but with Chrome. And finding bugs in Chrome after dart2js compiled it, is so much more painful then debugging in Dartium. In fact, I love debugging in Dartium :).

When Chrome doesn't support it anymore, shouldn't it also be removed from Dartium?

**Comment by zoechi** [comment]
What Dart version are you using?  
Dartium included in stable (don't know about latest dev releases) is based on Chromium 39, which might still contain it. Bleeding edge Dart already contains Dartium based on Chromium 45. Would be interesting if you can reproduce there.

**Comment by AlexanderJohr** [comment]
I'm using 1.14.2 of the Dart SDK and Dartium. Should I always consider downloading the sdk from the dev channel for valid issues?

**Comment by alan-knight** [comment]
If things are fixed in dev channel, then that's a way of getting the fix before it's released. In this case, it isn't fixed there yet.

**Comment by Tomucha** [comment]
This is still an issue, I've just run into it ... SDK shouldn't offer pathSegList as a part of SVG API.
Dart VM version: 1.20.1 (Wed Oct 12 15:00:54 2016) on "macos_x64"

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
