### ISSUE TITLE
NodeList.accept considered harmful

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25889]
In the analyzer's API (analyzer/lib/dart/ast/ast.dart) AST nodes have an accept method that takes an AstVisitor and returns a result.  NodeList which does not implement AstNode also has an accept method that takes a Visitor but this method just returns null.  There's no easy way to change that behavior on a per-visitor basis.

I just spent some time tracking down an issue where I was inadvertently calling accept on a NodeList and expecting a non-null result.

I think it would be better to have either one of the following:
1. Don't call this method accept, call it acceptForEach or something like that.  Only classes that implement AstNode get to have an honest-to-goodness accept method that takes an AstVisitor.  Calling accept on a NodeList will not work.
2. Make NodeList implement AstNode and add a visitNodeList method the the AstVisitor interface so it can be implemented on a per-visitor basis.  Calling accept on a NodeList will do the "right thing" according to the visitor.

**Comment by bwilkerson** [comment]
Interesting ideas. I also considered a couple of other alternatives when first designing the AST structure:

* Always return a list of the values returned for each of the elements of the list.

* Allow a "combinator" to be passed in that would be used to compute the result (allowing for logical and's and or's, etc.).

Those have some unfortunate performance issues.

The work around, in the mean time, is to visit the elements of the node list manually where necessary.

**Comment by kmillikin** [comment]
A possibility now would be to give `accept` in class `NodeList` a return type of `void`.  Feel free to close this feature request, though, if it's not valuable.

**Comment by parlough** [comment]
> A possibility now would be to give `accept` in class `NodeList` a return type of `void`. Feel free to close this feature request, though, if it's not valuable.

Since a `void` return type was added in https://github.com/dart-lang/sdk/commit/6bf946bbfc6b15649732a74ddf63444f8a2e15e0, I'm going to close this as fixed now that there is a proper signal there is no result. If anyone would like to see further changes to the `NodeList` API, please open a new issue or reopen this one :)
