### ISSUE TITLE
Code coverage tool and test do not support .package files

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25888]
The tools tools/full-coverage.dart, which processes the json output of the vm's --coverage-dir option into other formats, and the test for this tool, do not support the use of a --packages option instead of --package-root.

The test will be failing as soon as we start running tests using a .packages file instead of the current [build_dir]/packages directory full of links.

The tool and test will need to be fixed.  It is unclear why the test is failing - there are no package references in the test files, and the json output is the same, whether the tests are run with .packages or a package root.

**Comment by iposva-google** [comment]
All of the --coverage-dir tests will be removed as soon as @cbracken moves to use the new VM service based APIs.

See #24319.

**Comment by cbracken** [comment]
package:coverage supports running without `--coverage-dir` for VM tests today. Any tests that rely on it should move to run using the `--observe:xxxx` option on one VM and use `collect_coverage` to collect.

**Comment by iposva-google** [comment]
The full-coverage.dart tool has been removed as part of the removal of the old-style coverage functionality.

Fixed with c434931517ae2a05f96b26c0fe6ff581d322ed02
