### ISSUE TITLE
Using DateTime with js interop either works in Dartium, or dart2js, but not both

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/sdk#25886]
I tried to use the Dart DateTime type with package:js 0.6.0. I discuss the problems I had in much more detail in my [blogpost](http://alexanderjohr.blogspot.de/2016/03/my-findings-about-dart-datetime-object.html).

When writing a js interface with DateTime properties, this works in Dartium:

```
@JS()
@anonymous
class RangeSliderDateRange {
  external get wheelMode;
  external DateTime get min;
  external DateTime get max;
  external factory RangeSliderDateRange({DateTime min, DateTime max});
}
```

But it doesn't work in Chrome after compiling it with dart2js. The DateTime objects confuses the js libaries I use.

I then tried to create my own minimalistic Date interface:

```
@JS()
class Date {
  external num getTime();
  external factory Date([int year, int month, int day]);
}
```

Converting the DateTime to Date and back to DateTime then works in dart2js. But converting it back doesn't work in Dartium anymore. For some reason Dartium thinks, that the Date object is a DateTime object.

When the user selects a date range, a callback is fired. Here are the js interfaces for the callback data:

```
@JS()
@anonymous
class ValueChangeEventData {
  external ValueChangeEventDataValues get values;
}

@JS()
@anonymous
class ValueChangeEventDataValues {
  external Date get min;
  external Date get max;
}
```

When I now convert the Date into DateTime, it works in dart2js. Not in Dartium anymore, because Dartium thinks that the dates already are DateTime and thus don't have the `getTime()` method.

```
  void dateSliderValuesChanging(e, ValueChangeEventData data) {
    DateTime minDate =
    new DateTime.fromMillisecondsSinceEpoch(data.values.min.getTime());
    DateTime maxDate =
    new DateTime.fromMillisecondsSinceEpoch(data.values.max.getTime());

    visualizeDataInSpiderChart(
        parsedExampleData, minDate, maxDate, spiderChart);
  }
```

When I now do this nasty thing and just treat the Date objects like DateTime objects, the analyzer and the dart2js compiler are complaining about type inference. Of course it doesn't work in Chrome anymore, because in Chrome these objects are in fact Date, and have to be converted. But Dartium is happy again, because it somehow converted the Date objects already back to DateTime.

```
  void dateSliderValuesChanging(e, ValueChangeEventData data) {
    DateTime minDate = data.values.min;
    DateTime maxDate = data.values.max;

    visualizeDataInSpiderChart(
        parsedExampleData, minDate, maxDate, spiderChart);
  }
```

What might do the trick, is to find out, if I am using Dartium or dart2js. I think it should just work using DateTime objects for all js interop, but I don't know, if that is possible.

**Comment by jacob314** [comment]
A Dart DateTime object should automatically become a JavaScript Date object when passed through all forms of JavaScript interop and vice versa. JavaScript Date objects should be in local not utc form by default.

**Comment by zijam** [comment]
I also have the same problem with Dart DateTime() object and JavaScript Date() object.
After running dart2js I don't have access to ```toLocae()``` method from DateTime object in JavaScript.

**Comment by johnpryan** [comment]
> A Dart DateTime object should automatically become a JavaScript Date object when passed through all forms of JavaScript interop and vice versa. JavaScript Date objects should be in local not utc form by default.

Does "should" in this case mean "does" or "once this is fixed"?

**Comment by jhochman** [comment]
My workaround:

I added this to pubspec.yaml:

`transformers:
  - $dart2js:
      environment: {'PROD': 'true'}
`

And these classes:

`class DateFactory {
  static dynamic create (int year, int month, int day) {
    if (const String.fromEnvironment('PROD') == null) {
      return new DateTime(year,month,day);
    } else {
      return new DateJS(year,month,day);
    }
  }
}

@JS('Date')
class DateJS {
  external factory DateJS([int year, int month, int day]);
}
`

And replace:

`new DateTime(1998, 7, 5)`

With:

`DateFactory.create(1998, 7, 5)`

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
