### ISSUE TITLE
parseCompilationUnit generates an exception on Windows if not supplied a name.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25885]
This is causing failures in `pkg/analyzer/test/parse_compilation_unit_test` when run on `pkg-win-be`.  See for instance https://build.chromium.org/p/client.dart/builders/pkg-win-be/builds/1883/steps/pkg%20tests/logs/stdio, excerpted below:

    ERROR: parses a valid compilation unit successfully
      Test failed: Caught Invalid argument(s): Illegal character in path
      dart:core/uri.dart 855                                    Uri._checkWindowsPathReservedCharacters
      dart:core/uri.dart 956                                    Uri._makeWindowsFileUrl
      dart:core/uri.dart 738                                    Uri.Uri.file
      package:analyzer/src/string_source.dart 30:45             StringSource.StringSource
      package:analyzer/analyzer.dart 39:20                      parseCompilationUnit
      pkg\analyzer\test\parse_compilation_unit_test.dart 15:16  main.<fn>
      package:unittest/src/internal_test_case.dart 120:37       InternalTestCase.run.<fn>
      dart:async/zone.dart 902                                  _rootRunUnary
      dart:async/zone.dart 798                                  _CustomZone.runUnary
      dart:async/future_impl.dart 551                           _Future._propagateToListeners.handleValueCallback
      dart:async/future_impl.dart 637                           _Future._propagateToListeners
      dart:async/future_impl.dart 424                           _Future._completeWithValue
      dart:async/future_impl.dart 479                           _Future._asyncComplete.<fn>
      dart:async/zone.dart 895                                  _rootRun
      dart:async/zone.dart 790                                  _CustomZone.run
      dart:async/zone.dart 696                                  _CustomZone.runGuarded
      dart:async/zone.dart 721                                  _CustomZone.bindCallback.<fn>
      dart:async/schedule_microtask.dart 41                     _microtaskLoop
      dart:async/schedule_microtask.dart 50                     _startMicrotaskLoop
      dart:isolate-patch/isolate_patch.dart 96                  _runPendingImmediateCallback
      dart:isolate-patch/isolate_patch.dart 149                 _RawReceivePortImpl._handleMessage

Looking at the code, it appears to be due to c8a3ede9022846af88df4bc88068936d357af709, which introduced a call to `new Uri.file(fullName)` to the `StringSource` constructor.  If no name is passed to `parseCompilationUnit`, it defaults to a name of `<unknown source>`, which can't be converted to a URI on Windows because it contains characters that are not legal in a path.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1750773002/
