### ISSUE TITLE
Analyzer should warn about using the wrong types in non-typed methods on generics.

### ISSUE THREAD

**Issue by ianloic** [dart-lang/sdk#25881]
For example, Set<T>.contains() takes an Object because of limitations in the Dart type system (see: #25878). I recently wrote a bug where I passed the wrong thing to a contains method. The analyzer should be able to easily see that what I passed was neither of the correct type nor one of its superclasses and warn if it is not.

**Comment by jmesserly** [comment]
as noted here: https://github.com/dart-lang/sdk/issues/25878#issuecomment-189751518 we can't restrict Set.contains like this.

Perhaps in the future if we come up with a general solution for co/cotravariance.
