### ISSUE TITLE
Runtime, run-time, and run time are used inconsistently

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25883]
In the spec these terms are used very inconsistently, even when used formally as defined in the spec (e.g., run-time error vs. run time error vs. runtime error).  Similarly for compile-time and compile time.

My suggestion would be to use 'run-time' and 'compile-time' consistently as an adjective (e.g., run-time type, run-time value, run-time error, compile-time constant, compile-time error).  Use 'run time' and 'compile time' consistently for describing different times (e.g., at run time, at compile time).

There are then a few occurrences of 'runtime' as a noun that describes the Dart run-time system.  (Thankfully, there are no occurrences of 'compiletime'.)  Avoid this because it's jargon and not really a noun anyway and use 'run-time system' instead.

**Comment by mezoni** [comment]
>> My suggestion would be to use 'run-time' and 'compile-time'...

https://en.wikipedia.org/wiki/Run_time_(program_lifecycle_phase)

In computer science, `run time`, runtime or execution time is the time during which a program is running (executing), in contrast to other program lifecycle phases such as `compile time`, `link time` and `load time`.

I've never heard anything about 'run-time' and 'compile-time' (with a hyphen).

**Comment by kmillikin** [comment]
@mezoni, you stopped reading that Wikipedia page just a bit too soon!

> In computer science, run time, runtime or execution time is the time during which a program is running (executing), in contrast to other program lifecycle phases such as compile time, link time and load time.

> A run-time error....

**Comment by mezoni** [comment]
>>@mezoni, you stopped reading that Wikipedia page just a bit too soon!

Really!!

**Comment by mezoni** [comment]
@kmillikin I think it can only mean one thing - it's synonymous.

Look at the same page on Wikidepia.

Application errors (exceptions)
Exception handling is one language feature designed to handle `runtime errors`, providing a ...

I think that there is no differences how to use them.

**Comment by kmillikin** [comment]
The noun 'runtime' is jargon which comes from taking the adjective in the phrase 'run-time system' and turning it into a noun.  It's ugly to read in my opinion and easily avoided anyway.  Still, using it as a noun for the run-time system isn't really incorrect.

The adjective form of 'run time' (the program lifecycle phase in your linked Wikipedia page) is 'run-time'.  This parallels 'compile-time' which is the adjective form of 'compile time'.  The spec absolutely should not use the adjective 'runtime' to describe this lifecycle phase for the same reason it should not use 'compiletime'.  It's nonsense.

The adjective 'run-time' describes things that pertain to run time.  The adjective 'runtime' describes things that pertain to the runtime (in other words, the run-time system).  There is a difference between them.  For example, a run-time error is one that happens at run time.  A runtime error is an error in the run-time system.  A run-time error mandated by the spec represents the proper functioning of the runtime and is therefore not a runtime error.  Likewise, a run-time type described by the spec is the type of a Dart object at run time.  A runtime type is a type that is used in the implementation of the run-time system and it might not even be a Dart type at all.

The spec has no reason to mention the runtime.  I don't think it even has to mandate that there be a run-time system.

Anyway: the issue here is that the spec should at least be self-consistent with respect to the use of run time, run-time, and runtime.  Hopefully that use is parallel to the use of compile time, compile-time, and compiletime.
