### ISSUE TITLE
Failures with -cprecompiler -rprecompiled_runtime

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25892]
Language/Expressions/Constants/identifier_denotes_a_constant_t05: Crash
Language/Expressions/Constants/static_method_t01: Crash
isolate/function_send_test: RuntimeError
isolate/message3_test/fun: RuntimeError

**Comment by kevmoo** [comment]
Closed by https://github.com/dart-lang/sdk/commit/a78ed1c47adde35e946d0149d609c37eacb80988 ?

**Comment by rmacnak-google** [comment]
No, only the two crashes fixed by a78ed1c47adde35e946d0149d609c37eacb80988.

**Comment by rmacnak-google** [comment]
Isolate messaging tests in e880063e884278b1d6d62725571d98de3db3ae6a
