### ISSUE TITLE
Precompilation: Replace use of Dart::IsRunningPrecompiledCode with DART_PRECOMPILED_RUNTIME

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25894]
And then disable running precompiled code from the 'dart' binary.

First need to have Flutter's Runner using DART_PRECOMPILED_RUNTIME.

@fsc8000

**Comment by cskau-g** [comment]
Can I ask, what was the motivation behind making the 'dart' executable not run precompiled code?
