### ISSUE TITLE
Missing compiler error in closurization expression

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#25896]
In the General Closurization section, the spec states:
"It is a compile-time error if e is a prefix object (18.1) and m refers to a type
or a member of class Object."

See co19 tests for missing compiler errors:
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t01
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t02
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t03
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t04
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t05
Language/Expressions/Property_Extraction/General_Closurization/class_object_member_t06

**Comment by mhausner** [comment]
As discussed offline, this is a dup of dartbug.com/24472
