### ISSUE TITLE
VM isolate may report being resumed prior to entering "paused on start"

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25902]
A VM isolate's "pauseEvent" field is temporarily set to "Resume" prior to going "PauseStart" as reported by the Observatory's "getIsolate" API call. This situation makes it ambiguous for some tools, such as `flutter drive`, to tell if they should wait for the isolate to enter "PauseStart" and then resume it, or whether the isolate is resumed for good and there's nothing to wait for.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1756393002/

**Comment by alexander-doroshko** [comment]
Dupe of #24550
