### ISSUE TITLE
Please, clarify specification for async* function invokation

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25909]
Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, chapter 16.14 Function Invocation reads:

> If f is marked async\* (9), then a fresh instance s implementing the built-in
> class Stream is associated with the invocation and immediately returned. When
> s is listened to, execution of the body of f will begin. When f terminates:
> • **If the current return value is deﬁned then, if s has been canceled then its
> cancellation future is completed with null** (16.2).
> • If the current exception x is deﬁned:
> – x is added to s.
> – If s has been canceled then its cancellation future is completed with
> x as an error.
> • s is closed.

It is not clear, what happens if current return value is not defined, but the stream subscription has been cancelled. What value is used to complete the cancellation future?

However the description for StreamSubscription.cancel() ( https://api.dartlang.org/1.14.2/dart-async/StreamSubscription/cancel.html ) states that cancellation future always completes with null value:

> Cancels this subscription. It will no longer receive events.
> 
> May return a future which completes when the stream is done cleaning up. This can be used if the stream needs to release some resources that are needed for a following operation, for example a file being read, that should be deleted afterwards. In that case, the file may not be able to be deleted successfully until the returned future has completed.
> 
> **The future will be completed with a null value**. If the cleanup throws, which it really shouldn't, the returned future will be completed with that error.
> 
> Returns null if there is no need to wait.

So I believe, the text `If the current return value is deﬁned then` can be omitted.

**Comment by kmillikin** [comment]
No, the future should complete normally with null or else complete with an error, as mentioned in the API docs:

> The future will be completed with a null value. If the cleanup throws, which it really shouldn't, the returned future will be completed with that error.

It's not obvious from 16.14 Function Invocation, but a provable property of the spec (assuming no bugs in the spec!) is that when a function activation terminates, then _exactly_ one of the current return value or current exception is defined.  So, if f has terminated and the current return value is undefined, then it must be the case the the current exception is defined (the second bullet point) and the cancellation future is completed with the current exception as an error.

I think this section is pretty clear when I read it.  @alsemenov What would you suggest as a clarification?

**Comment by alsemenov** [comment]
I think I need to clarify myself.
The sentence `If the current return value is deﬁned then, if s has been canceled then its
cancellation future is completed with null (16.2)` produce a lot of confusion to me.

First, it refers to `current return value` of asynchronous generator function. The reader have to find out what does it means. After reading chapter `17.12 Return` it becomes clear that `current return value` is basically set by `return <expression>` statement. **But this statement is prohibited for asynchronous generator functions**. The reader have to go deeper. After studying all corner cases it turns out that `current return value` is set to null. Still I am not sure in this. For example, function can be terminated in yield statement as result of stream cancellation. Does it set the `current return value` in this case?

Second, the sentence does not actually need the `current return value`. Regardless of the value, the cancellation future is completed with null. As @kmillikin clarified in his comment, `current return value` is necessary only to distinguish two cases: 
>when a function activation terminates, then exactly one of the current return value or current 
>exception is defined. 
However I am not sure where to find this place in the specification, it's not obvious from `16.14 Function Invocation`. I would prefer simpler way to distinguish these cases.

Third, after @kmillikin comment I understand the intention of the specification, but it takes a lot of efforts. I would suggest to simplify the `16.14 Function Invocation` and make it more clear and obvious.
For example:
>  • If the current exception is not defined and s has been canceled, then its
> cancellation future is completed with null, 
> • If the current exception x is deﬁned:
> ...

This example is much more easier to understand (no reference to redundant `current return value`) and from logical point of view all cases are mentioned (either current exception is defined or not).

**Comment by kmillikin** [comment]
@alsemenov, you are right about yield and yield*.  I was forgetting about them because they are missing from the list of the ways that functions can terminate at the end of 16.14.  (I've added them to #25850.)

Due to yield and yield*, the property is that when a function terminates, _at most_ one of the current return value or current exception is defined.  It can be the case that they are both undefined.  That is why the section you quoted has to be written as it is in the spec --- if they are both undefined then presumably the cancellation future has already been completed and so it should not be completed with null (which would be caused by your suggested revision).

**Comment by kmillikin** [comment]
In #25850 @lrhn suggests changing `yield` and `yield*` to execute a return inside `async*` functions when the stream has been canceled.  Note that this change would establish the property that I thought we had in the first place --- that exactly one of current return value or current exception was defined when a function terminates.

**Comment by kmillikin** [comment]
This has all been cleaned up in the specification.
