### ISSUE TITLE
Generated mips code for DoubleToInt should use TRUNC instruction instead of CVT.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#25900]
The CVT instruction uses the current rounding mode. We should use TRUNC instead.
See failing co19 test LibTest/core/double/toInt_A01_t01

**Comment by iposva-google** [comment]
Is this also exposed on simmips or only on HW?

**Comment by crelier** [comment]
Only hardware.

**Comment by crelier** [comment]
Fixed in  https://codereview.chromium.org/1765623002 .
