### ISSUE TITLE
'Undefined class' error changes depending on unused imported class

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25906]
To reproduce, in Atom create this file:

```
import "appbar.dart";

class AppView {
  expand() => const Tag.div();
}
```

It results in the following errors:

Target of URI does not exist: 'appbar.dart' - appview.dart, line 1
Undefined class 'Tag.div' - appview.dart, line 4

Now, create appbar.dart with intentionally bad syntax. (I do this by moving it from a temp directory.)

```
Frame ge editorButton => new Tag();
```

There are several more errors, but notice in particular that the error for 'Tag.div' goes away, and this info message appears:

Unused import - appview.dart, line 1

Reanalyze sources, and the unused import message goes away. (It seems to me that it's still unused.)

Move appbar.dart back to the temp directory, and close the tab in Atom.

The error message is now:
Undefined class 'Tag' - appview.dart, line 4

This is different from before when the undefined class was 'Tag.div'.

Found via a stress test. In itself, I don't think this is a serious error for users, but it might be a symptom of a caching issue.

**Comment by skybrian** [comment]
The specific error message seems to change based on whether the TypeName is resolved to an element or not. I put a log statement in TypeResolverVisitor.visitTypeName, and it varies:

visitTypeName: element=Tag() typeNameSimple=Tag
visitTypeName: element=null typeNameSimple=Tag
visitTypeName: element=null typeNameSimple=div

**Comment by skybrian** [comment]
It looks like this has something to do with some code that rewrites the AST in the resolver. Here's the comment that explains it:

```
            // Rewrite the constructor name. The parser, when it sees a
            // constructor named "a.b", cannot tell whether "a" is a prefix and
            // "b" is a class name, or whether "a" is a class name and "b" is a
            // constructor name. It arbitrarily chooses the former, but in this
            // case was wrong.
```

I verified that the constructor name is getting rewritten:
Tag.div in nameScope: null
rewrote constructor name to Tag.div
visitTypeName isConst: element=Tag() typeNameSimple=Tag

It seems that when we re-run the resolver using the same AST, on the second time around, the constructor name has already been rewritten, so the error is reported differently. To make this consistent after type resolution was invalidated, we would need to undo this rewrite on the AST and check if it should be done again in the new situation.

**Comment by bwilkerson** [comment]
Or we need to not re-write the AST at all, or we need to ensure that we produce the same error message no matter which way it was parsed.

**Comment by skybrian** [comment]
I'm thinking a good approach would be to rewrite the AST at the end of the parse task. That way, if it's invalidated, the whole thing gets done again.

Once we've built an AST, we can create a list of prefixes (without resolving them - just looking at imports) and I think this would be enough to rewrite the named constructors.

Perhaps it could be done single-pass, but that might be tricky since this is context-sensitive.

**Comment by keertip** [comment]
closing as stale as the parser has been rewritten and is in the unified front end.
