### ISSUE TITLE
Adding `strong-mode: true` to .analysis_options while running causes weirdness with generic methods

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25904]
Reproduction steps:
1. Use `someIterable.map` in a way that requires type information _and_ where the generic type can be inferred.
2. Add `strong-mode: true` to `.analysis_options` in a running IntelliJ instance

Expected: no errors. Either the new option isn't honored (until restart) or strong mode goes clean

Actual: get a warning about `Iterable<dynamic>` is not `Iterable<SomeType>`

Thoughts from @leafpetersen – the SDK libs are not refreshed with the generic info (without a restart)

Dart version: Dart VM version: 1.15.0-dev.4.0

**Comment by leafpetersen** [comment]
Edited your comment so the `<...>` show up.  The error is what I would expect to see if the definition of Iterable.map is not being parsed in strong mode (i.e. the generic annotation is not being picked up), but then the application of Iterable.map is being checked in strong mode.  Hence my hypothesis that the SDK context isn't getting rebuilt appropriately.

**Comment by bwilkerson** [comment]
I'm assuming this has been fixed by now.
