### ISSUE TITLE
Sporadic exception in DeclarationResolver._resolveMetadata

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25913]
When analyzing large codebases, the command line analyzer occasionally crashes with the following stacktrace:

    Unhandled exception:
    AnalysisException: Cannot compute LIBRARY_ELEMENT for ...
    Caused by Unexpected exception while performing BuildCompilationUnitElementTask for source ...
    #0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
    #1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
    #2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
    #3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
    #4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:664)
    #5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
    #6      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
    #7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #8      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
    #9      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
    #10     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
    #11     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
    #12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
    #13     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
    #14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #15     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
    #16     Driver.start (package:analyzer_cli/src/driver.dart:129)
    #17     main (file:///.../pkg/analyzer_cli/bin/analyzer.dart:22)
    #18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
    #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
    
    Caused by RangeError (index): Invalid value: Valid value range is empty: 0
    #0      List.[] (dart:core-patch/array.dart:134)
    #1      DeclarationResolver._resolveMetadata (package:analyzer/src/generated/resolver.dart:2857)
    #2      DeclarationResolver.visitLibraryDirective (package:analyzer/src/generated/resolver.dart:2471)
    #3      LibraryDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6561)
    #4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7582)
    #5      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2420)
    #6      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
    #7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2414)
    #8      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2177)
    #9      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:895)
    #10     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
    #11     AnalysisTask.perform (package:analyzer/task/model.dart:229)
    #12     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
    #13     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
    #14     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:664)
    #15     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
    #16     AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
    #17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #18     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
    #19     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
    #20     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
    #21     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
    #22     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
    #23     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
    #24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #25     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
    #26     Driver.start (package:analyzer_cli/src/driver.dart:129)
    #27     main (file:///.../pkg/analyzer_cli/bin/analyzer.dart:22)
    #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
    #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
    
    
    #0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:668)
    #1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
    #2      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
    #3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #4      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
    #5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
    #6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
    #7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
    #8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
    #9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
    #10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
    #11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
    #12     Driver.start (package:analyzer_cli/src/driver.dart:129)
    #13     main (file:///.../pkg/analyzer_cli/bin/analyzer.dart:22)
    #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
    #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

(Note: some private customer data has been replaced by `...`).

**Comment by stereotype441** [comment]
We believe the problem was introduced by https://github.com/dart-lang/sdk/commit/2cdec8fd1051d8207bc4135fd04928a2e6a27a98.  The rough scenario is:

- The analyzer begins analyzing a compilation unit, and runs `ElementBuilder` to create all the element annotations for that compilation unit.  The annotations for directives are not stored in the element model yet, because this is done by a later task.  But they are stored in the AST.
- Before the annotations can be stored in the element model, the AST is thrown away due to memory pressure.  Now the references to the element annotations are lost.
- After the AST is recreated, `DeclarationResolver` tries to hook it up to the existing element model.  But since the pointers to the element annotations hadn't been stored yet, `DeclarationResolver` runs off the end of an array trying to find them.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1768713002/
