### ISSUE TITLE
Add an `@ignore` annotation to support error suppression.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25919]
In line with source level suppressions via comments (https://github.com/dart-lang/sdk/issues/25685) and as proposed in the [doc](https://docs.google.com/document/d/1YJCkxnklLR2aKzQUrp6cWmqk7yUhfJwtaXIGcjZIk-Y/edit), let's consider adding an `@ignore` annotation.

This would be handy, for example, when want to suppress specific errors at the library level (e.g., examples as discussed in https://github.com/dart-lang/sdk/issues/25912).

**Comment by pq** [comment]
cc @bwilkerson

**Comment by srawlins** [comment]
Note that `// ignore_for_file: ` has been added in the last few months, for the library-level use case.

**Comment by pq** [comment]
Closing as `ignore_for_file` gets us there.
