### ISSUE TITLE
lib/mirrors/metadata_allowed_values_test failing in dart2js host-checked mode

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25911]
The four tests
lib/mirrors/metadata_allowed_values_test/28
lib/mirrors/metadata_allowed_values_test/29
lib/mirrors/metadata_allowed_values_test/30
lib/mirrors/metadata_allowed_values_test/31
are failing in --host-checked mode on the buildbots, on linux.
The failing command line is:

tools/test.py '--mode=release' '--arch=ia32' '--compiler=dart2js' --dart2js-batch '--runtime=d8'
 '--progress=buildbot' -v --clear_browser_cache --report --time --failure-summary --write-debug-log
 --write-test-outcome-log --copy-coredumps --host-checked '--shards=5' '--shard=1'

The failure reproduces also on MacOS, with -mrelease -aia32 -cdart2js -rd8 --host-checked --dart2js-batch lib/mirrors/metadata_allowed_values_test/28

The error output (a crash in dart2js) is

xcodebuild/ReleaseIA32/generated_tests/lib/metadata_allowed_values_test_28.dart:153:1:
Internal Error: The compiler crashed when compiling this element.
class LL {
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:
- the name and version of your operating system,
- the Dart SDK build number (build number could not be determined), and
- the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'PartialClassElement' is not a subtype of type 'ExecutableElement' of 'enclosing'.
#0      LocalFunctionElementX.LocalFunctionElementX (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/elements/modelx.dart:2189:43)
#1      ResolverVisitor.visitFunctionExpression (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:609:42)
#2      FunctionExpression.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:827:38)
#3      CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#4      ResolverVisitor.resolveArguments (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:740:33)
#5      ResolverVisitor.visitNewExpression.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3919:35)
#6      ResolverVisitor.inConstantContext (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:273:24)
#7      ResolverVisitor.visitNewExpression (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3919:11)
#8      NewExpression.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:560:38)
#9      ResolverTask.resolveMetadataAnnotation.<anonymous closure>.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:1066:12)
#10     CompilerTask.measure (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:55:37)
#11     ResolverTask.resolveMetadataAnnotation.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:1049:68)
#12     _CompilerDiagnosticReporter.withCurrentElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1755:15)
#13     ResolverTask.resolveMetadataAnnotation (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:1049:14)
#14     _CompilerResolution.resolveMetadataAnnotation (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:2100:23)
#15     MetadataAnnotationX.ensureResolved (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/elements/modelx.dart:3152:18)
#16     ResolverTask._postProcessClassElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:658:16)
#17     ResolverTask._resolveTypeDeclaration.<anonymous closure>.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:575:15)
#18     CompilerTask.measure (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:55:37)
#19     ResolverTask._resolveTypeDeclaration.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:563:14)
#20     _CompilerDiagnosticReporter.withCurrentElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1755:15)
#21     ResolverTask._resolveTypeDeclaration (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:562:21)
#22     ResolverTask.resolveClass (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:600:12)
#23     _CompilerResolution.resolveClass (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:2090:23)
#24     BaseClassElementX.ensureResolved (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/elements/modelx.dart:2648:18)
#25     ResolverVisitor.handleClassSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:2178:9)
#26     ResolverVisitor.handleResolvedSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:2973:14)
#27     ResolverVisitor.handleUnqualifiedSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3066:14)
#28     ResolverVisitor.visitSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3104:14)
#29     Send.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:412:38)
#30     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#31     ResolverVisitor.resolveArguments (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:740:33)
#32     ResolverVisitor.handleStaticOrTopLevelAccess (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:2732:11)
#33     ResolverVisitor.handleResolvedSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:2984:14)
#34     ResolverVisitor.handleUnqualifiedSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3066:14)
#35     ResolverVisitor.visitSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3104:14)
#36     Send.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:412:38)
#37     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#38     ResolverVisitor.visitExpressionPrefix (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:1140:31)
#39     ResolverVisitor.handleQualifiedSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:2423:31)
#40     ResolverVisitor.visitSend (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3101:14)
#41     Send.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:412:38)
#42     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#43     ResolverVisitor.visitExpressionStatement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:564:5)
#44     ExpressionStatement.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:1229:38)
#45     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#46     ResolverVisitor.visitNodeList (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:3654:7)
#47     NodeList.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:599:38)
#48     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#49     ResolverVisitor.visitIn (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:527:31)
#50     ResolverVisitor.visitBlock (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/members.dart:547:5)
#51     Block.accept (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/tree/nodes.dart:646:38)
#52     CommonResolverVisitor.visit (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:41:54)
#53     ResolverTask.resolveMethodElementImplementation.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:269:17)
#54     _CompilerDiagnosticReporter.withCurrentElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1755:15)
#55     ResolverTask.resolveMethodElementImplementation (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:226:21)
#56     ResolverTask.resolveMethodElement.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:342:16)
#57     _CompilerDiagnosticReporter.withCurrentElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1755:15)
#58     ResolverTask.resolveMethodElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:305:21)
#59     ResolverTask.resolve.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:112:32)
#60     CompilerTask.measure (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:55:37)
#61     ResolverTask.resolve (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/resolution/resolution.dart:92:12)
#62     _CompilerResolution.computeWorldImpact.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:2128:29)
#63     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:254)
#64     _CompilerResolution.computeWorldImpact (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:2123:30)
#65     Compiler.analyzeElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1208:23)
#66     Compiler.analyze (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1230:31)
#67     ResolutionWorkItem.run (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/common/resolution.dart:53:35)
#68     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1121:46)
#69     _CompilerDiagnosticReporter.withCurrentElement (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1755:15)
#70     Compiler.emptyQueue.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1120:14)
#71     QueueFilter.processWorkItem (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/enqueue.dart:1014:6)
#72     Enqueuer.forEach (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/enqueue.dart:704:16)
#73     Compiler.emptyQueue (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1119:11)
#74     Compiler.processQueue (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1147:5)
#75     Compiler.compileLoadedLibraries (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:1015:5)
#76     Compiler.runInternal.<anonymous closure> (file:///Users/whesse/sdk/sdk/pkg/compiler/lib/src/compiler.dart:886:7)
#77     _RootZone.runUnary (dart:async/zone.dart:1137)
#78     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#79     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#80     _Future._completeWithValue (dart:async/future_impl.dart:424)
#81     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#82     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#83     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#84     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[dart2js]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --package-root=xcodebuild/ReleaseIA32/packages/ /Users/whesse/sdk/sdk/xcodebuild/ReleaseIA32/generated_tests/lib/metadata_allowed_values_test_28.dart --out=/Users/whesse/sdk/sdk/xcodebuild/ReleaseIA32/generated_compilations/dart2js/multitest_lib_metadata_allowed_values_test_28/out.js
Took 0:00:01.381225

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -cdart2js --dart2js-batch -rd8 --host-checked -t960 lib/mirrors/metadata_allowed_values_test/28

**Comment by whesse** [comment]
Also failing in --host-checked mode:
corelib/package_resource_test
lib/mirrors/circular_factory_redirection_test/02

And only in --host-checked but not --checked mode:
lib/mirrors/mirrors_used_typedef_declaration_test/none
lib/mirrors/mirrors_used_typedef_declaration_test/01
lib/mirrors/typedef_library_test

**Comment by whesse** [comment]
Also failing in --host-checked mode:
corelib/collection_removes_test
html/js_typed_interop_default_arg_test/[none,default_value,explicit_argument]

**Comment by bkonyi** [comment]
Closing as `dart:mirrors` is no longer supported on web.
