### ISSUE TITLE
for-in loop warning should be treated as implicit cast?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25916]
```dart
      if (segments is Map) {
        for (String segment in segments.keys) {
          // ...
        }
      }
```
We issue a warning on `segments.keys`:
```
WARNING: Unsound implicit cast from Iterable<dynamic> to Iterable<String> ([stagexl] lib/src/resources/sound_sprite.dart:22)
```
I guess we pushed the type down. But conceptually, this is more like an implicit cast from `dynamic` to `String`, which we wouldn't issue a warning for:

```dart
        var iterator = segments.keys.iterator;
        while (iterator.moveNext()) {
          // no warnings!
          String segment = iterator.current;
        }
```

it seems a bit odd to treat the desugared pattern differently from the for-in loop

**Comment by jmesserly** [comment]
CC @leafpetersen @munificent for thoughts

**Comment by jmesserly** [comment]
(also CC @kevmoo who was looking at StageXL)

**Comment by leafpetersen** [comment]
I believe that @munificent is working on fixing this right now.

**Comment by munificent** [comment]
Not exactly. The for-in checking I did manifests the same warning. But I will. :)
