### ISSUE TITLE
Closures can sometimes see shadowed variables

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25910]
@mhausner Related to the code in #21633, if we have

``` dart
main() {
  var a = 10;
  {
    print(a);  // Compile-time error.
    var a = 42;
    print(a);
  }
}
```

Then the Dart VM rightly signals a compile-time error at the first reference to the inner `a` before the end of its initializer expression.  However, this analysis does not seem to look inside closures:

``` dart
main() {
  var a = 10;
  {
    print((()=>a)());  // Prints 10!
    var a = 42;
    print(a);
  }
}
```

(Analyzer gets this right.  Dart2js gets it wrong.)

**Comment by iposva-google** [comment]
Assigning to @gbracha first to clarify language spec.

**Comment by lrhn** [comment]
The specification is fairly straight-forward on this. The scope of a local variable declaration is the block it's contained in. It is a compile-time error to have a reference to the variable that is not *syntactically* later than the declaration of that variable. That means any occurrence of the variable before the declaration or inside the declaration's initializer expression is a compile-time error. 

Kevin is right, this is a bug.

**Comment by kmillikin** [comment]
Both the VM and dart2js have the incorrect behavior.  The new Common Front End does not have the bug, so I would say that it's not a high priority to change the existing implementations.

**Comment by kmillikin** [comment]
Both the VM and dart2js use the CFE and no longer have the bug.
