### ISSUE TITLE
Quick fix for source-location suppression

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25915]
Now that #25685 has landed it would be great if hints and warnings would provide quick fixes to suppress them.

**Comment by zoechi** [comment]
@pq seems I have no permission to assign or add tags.

**Comment by pq** [comment]
Thank you!

**Comment by pq** [comment]
Landed in https://github.com/dart-lang/sdk/commit/1f0a0b5a5c464db06761aa7ec0f8f0ac5081dc33.

![screen shot 2016-03-04 at 12 28 02 pm](https://cloud.githubusercontent.com/assets/67586/13539338/98991efa-e204-11e5-8b00-9e049ff6bb22.png)
=>

![screen shot 2016-03-04 at 12 28 07 pm](https://cloud.githubusercontent.com/assets/67586/13539339/989b9522-e204-11e5-8689-da2374c1f2b8.png)

Aside: it looks like IntelliJ doesn't use the fix `relevance` value in sorting which I don't love...

@jwren can you confirm?

**Comment by jwren** [comment]
Looking at the [Analysis Server API Specification](http://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html), the only reference to `relevance` is for code completions.  I don't see a `relevance`, or even an indication that the list that is passed back is in a particular order.

@bwilkerson

**Comment by bwilkerson** [comment]
I guess I would have expected that server sorted them before returning them, but maybe that's not the case. @scheglov

**Comment by scheglov** [comment]
Server **does** sort them by `relevance`.

![image](https://cloud.githubusercontent.com/assets/384794/13542482/f123c454-e217-11e5-82d5-31ae5de98e40.png)

But IDEA resorts them by name.

![image](https://cloud.githubusercontent.com/assets/384794/13542497/0451a49c-e218-11e5-96cc-e1f4a20fcc24.png)

**Comment by jwren** [comment]
@alexander-doroshko I tracked the list of fixes from the analysis server down into com.intellij.codeInsight.daemon.impl.HightlightInfo, where we are preserving the lust order.  My guess is that the UI itself is sorting them alphabetically?

**Comment by alexander-doroshko** [comment]
@scheglov @jwren I've disabled sorting of quick fixes at IntelliJ IDEA side, order from server is preserved now.

**Comment by alexander-doroshko** [comment]
For the record: Analysis Server-driven Quick Fixes for warnings suppression have been reverted, details in #25926.

**Comment by scheglov** [comment]
@alexander-doroshko Nice! Thank you! :-)
