### ISSUE TITLE
Confusing definition for references to uninitialized local variables

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25922]
I'm trying to understand the semantics of local variables, and this clause in the spec is confusing (the non-normative rationale is in italics):

> A local variable may only be referenced at a source code location that is after its initializer, if any, is complete, or a compile-time error occurs. The error may be reported either at the point where the premature reference occurs, or at the variable declaration.
> 
> _We allow the error to be reported at the declaration to allow implementations to avoid an extra processing phase._

Coupled with the definition of compile-time errors:

> Compile-time errors are errors that preclude execution. A compile-time error must be reported by a Dart compiler before the erroneous code is executed.

This reads as if an implementation is free to decide whether (1) a reference to a variable before its initialization is erroneous code and a compile-time error must be reported before it is executed, or (2) the declaration of a variable that has been referenced before its initialization is erroneous code and a compile-time error must be reported before it is executed.

The second one of those doesn't make sense to me:

``` dart
undefined() {
  throw a;  // This should not be executed.
  var a;
}
```

**Comment by lrhn** [comment]
I agree that it looks confusing.
I'm assuming it's trying to cover a case like:
```
bar() {
  foo(x) => x + y;
  var y = 42;
  return foo;
}
```
In this case, the erroneous usage is in the `foo` function, but the VM (or a similar implementation with interleaved compilation and execution) may not compile the `foo` function before it's called. So, the VM may report a compile time error when compiling the `var y` declaration or when compiling the `y` usage in the `foo` function - which may be at very different times.

If the error reporting must happen when the declaration is compiled, the VM would need an extra processing phase to (at least) parse the `foo` function, even if it isn't compiling it at this point.

On the other hand, an implementation is free to report the compilation error before executing the declaration as well.
So it really is (1) or (2) - implementations may pick either.

**Comment by kmillikin** [comment]
I wondered if something like that was the motivation, but it still doesn't make sense to me.  The rationale muddies things when it talks about about avoiding extra phases because there is so much more that is unsaid than said.

It doesn't really make any difference to an implementation that compiles `foo` when compiling `bar`, because the two compile times coincide.

For an implementation that compiles `foo` when it is applied (after compilation of `bar`), I agree that it seems complicated to try to report the error at the application of `foo` and you would choose to report it when compiling the block in `bar`.

I think it's fine for the spec to say unambiguously that it is the block in `bar` containing the use of `y` before its initializer that is the compile-time error.  There should also be no difference between the text here and in 17.4 Local Function Declaration.

**Comment by lrhn** [comment]
I agree. The error is at the early occurrence of the variable (removing that will fix the problem, removing the declaration won't), and you may report compile-time errors at any time you are compiling code that contains the error, as long as it's before executing it. There is no need to be explicit about when that is.
If you had multiple nested function declarations containing the error, you could detect the problem at any intermediate function body as well (maybe due to inlining of the error code).

I would avoid saying that you can report errors at *any* time before executing it because there is a push to make compile-time errors catchable at runtime, and you would want the error to occur at a point where the erroneous code is involved, so that the error is repeatable if the same function is called again - even if code is really being compiled in a background thread, and the error was detected concurrently with unrelated execution.

**Comment by kmillikin** [comment]
This is still an issue.  I suggest just getting rid of:

> The error may be reported either at the point where the premature reference occurs, or at the variable declaration.

> _We allow the error to be reported at the declaration to allow implementations to avoid an extra processing phase._

**Comment by lrhn** [comment]
Agree. The first statement is sufficient and correct.

**Comment by eernstg** [comment]
No milestone now: The clarification should be carried out as described, but this does not block Dart 2.

**Comment by eernstg** [comment]
Closing: [This](https://github.com/dart-lang/sdk/issues/25922#issuecomment-346029463) was part of the update in commit 5af984438298212fd821a091c013602b419340e5.
