### ISSUE TITLE
Make it normative that true and false are the only boolean values

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25923]
The spec has:

> The reserved words true and false denote objects that represent the boolean values true and false respectively. They are the boolean literals.
> 
> Both true and false implement the built-in class bool. It is a compile-time error for a class to attempt to extend, mix in or implement bool.
> It follows that the two boolean literals are the only two instances of bool.

The last sentence is non-normative commentary.

It doesn't follow that there are no other instances of bool.  For instance, it isn't specified that there is no bool constructor and that `new bool()` does not return a value distinct from true or false (`identical` on booleans is almost unspecified, it just has to agree with `operator==` which is unspecified).

It also isn't specified that an `external` function cannot return a boolean value distinct from true and false.

Rather than trying to close all possible loopholes, it might be more clear to say normatively that there are no other boolean values than true and false since that seems to be the intent.

**Comment by eernstg** [comment]
No milestone now: This correction should be carried out, but it does not block Dart 2.

**Comment by eernstg** [comment]
Closing: As of today we have this in section 'Booleans':

```
Both {\em true} and {\em false} are instances of the built-in class \code{bool},
and there are no other objects that implement \code{bool}.
```
