### ISSUE TITLE
websql_test/functional broken with Chrome 45 IDL

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#25927]
I have one fix, but working on a better one. Suppressing in the meantime.

**Comment by whesse** [comment]
Currently working on ie and ff, broken on chrome varieties and safari.

**Comment by alan-knight** [comment]
Fixed in https://codereview.chromium.org/1779023002/

**Comment by alan-knight** [comment]
And removed the suppression in https://codereview.chromium.org/1777013003
