### ISSUE TITLE
Dart's analysis warns about `final` uninitialized in abstract class

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#25920]
https://dartpad.dartlang.org/099eb648084b7a117366

An abstract class is supposed to be a class that can’t be instantiated. The message from Dart Analysis say that variable MUST be initialized in the abstract. I think it's not an error to leave that variable uninitialized.

**Comment by zoechi** [comment]
Not sure if it is a bug. A workaround is to use getter and setter instead https://dartpad.dartlang.org/0783bcc6ab37eafe1d90

**Comment by eernstg** [comment]
It is not even a workaround: Fields can neither be evaluated nor mutated directly, it is always done via a getter or setter (which might be generated implicitly). This makes the lone getter a natural way to express an abstract immutable field.

**Comment by tristancaron** [comment]
That seems fair. I'll use getter for the future. Thanks both of you.

**Comment by lrhn** [comment]
Abstract classes *may* leave some members abstract, but final fields will introduce an actual field and a non-abstract implicit getter. Final fields must be initialized in the class where they are defined, whether the class is abstract or not. No other class can initialize the field.

The example code actually has a class with two fields, each with its own getter, and the subclass getter shadows the superclass getter. It is an error to not initialize the superclass field.

**Comment by tristancaron** [comment]
@lrhn Thank you for your explanation.
