### ISSUE TITLE
Analyzer warning when assigning CanvasRenderingContext using conditional operator

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#25934]
This code

```dart
var isWebGl = true;
CanvasElement canvas = querySelector('#canvas');
CanvasRenderingContext ctx = isWebGl ? canvas.getContext3d() : canvas.context2D;
```
produces the following warning:

> WARNING: A value of type 'DartHtmlDomObject' cannot be assigned to a variable of type 'CanvasRenderingContext' ([untitled] web\main.dart:10)

I'd expect no warning at all as the WebGL `RenderingContext` and the `CanvasRenderingContext2D` both implement `CanvasRenderingContext`.

I'm using Dart VM version: 1.15.0-dev.5.0 (Wed Mar 02 04:39:03 2016) on "windows_x64".

**Comment by bwilkerson** [comment]
I agree with you. Unfortunately the language specification doesn't. According to section 16.20, given a conditional expression `c` of the form `e1 ? e2 : e3`

> The static type of `c` is the least upper bound (19.8.2) of the static type of `e2` and the static type of `e3`.

Which makes sense. Unfortunately the definition of least upper bound is not what you'd expect, and that leads to the problems. In particular, the least upper bound of `RenderingContext` and `CanvasRenderingContext2D` ends up being `DartHtmlDomObject`.

So as unpleasant as this is, it is working as expected.

You can probably work around the issue by casting either `e2` or `e3` to `CanvasRenderingContext` (though I can't try it at the moment).
