### ISSUE TITLE
Strong mode doesn't infer lambda return types

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#25939]
See https://github.com/dart-lang/build/pull/79/files#diff-9245a1f98f0acef47adcf0165b3ad021R62 for an example where I had to extract the lambda out to a method in order to get rid of the strong mode error.

**Comment by vsmenon** [comment]
This may be a specific issue with `async` methods.

**Comment by jmesserly** [comment]
I believe this was fixed in https://github.com/dart-lang/sdk/commit/1f8aa2bdb03c338c67058e5bae65a781b5bdd922. Do you know what version you were running?

**Comment by jakemac53** [comment]
I am on version `1.15.0-dev.3.0` of the sdk

**Comment by jakemac53** [comment]
Confirmed, I updated to `1.15.0-dev.5.0` and no more warning, thanks!

**Comment by jmesserly** [comment]
Awesome!
