### ISSUE TITLE
new failures in safari

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#25941]
These started failing since the new roll:

```
LayoutTests/fast/encoding/css-charset-dom_t01
LayoutTests/fast/innerHTML/innerHTML-svg-write_t01
```

I'm about to submit a CL marking them as failing.

**Comment by alan-knight** [comment]
the css-charset-dom is because CSSCharsetRule disappeared from the IDL. Working on that.

**Comment by alan-knight** [comment]
CssCharsetRule exists only in WebKit. But if we leave it out entirely then when we enumerate a list of CssRule, we can encounter an unknown JavaScript object in Safari. So I put back the IDL for it in Dart supplemental.

**Comment by athomas** [comment]
LayoutTests have been deleted.
