### ISSUE TITLE
poor error message when you give out of range values to double.toStringAsFixed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25948]
Doing "toStringAsFixed(200)" on a double value fires an exception whose message is just "RangeError: 200". It should say what the valid range is. (Also, it should probably explain why it can only do 20 decimal places. That seems arbitrarily small given that it's quite possible to have numbers with more decimals.)

**Comment by lrhn** [comment]
Now says: `Uncaught Error: RangeError (fractionDigits): Invalid value: Not in inclusive range 0..20: 200`.
