### ISSUE TITLE
Dart VM: bad code generated with --no-use-field-guards

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#25957]
Crashes and incorrect code observed

python tools/test.py -aia32 --exclude-suite pkg --vm-options "--optimization-counter-threshold=10  --no-use_field_guards" -t120 corelib/num_sign_test
python tools/test.py -aia32 --exclude-suite pkg --vm-options "--optimization-counter-threshold=10  --no-use_field_guards" -t120 corelib/double_parse_test/02
python tools/test.py -aia32 --exclude-suite pkg --vm-options "--optimization-counter-threshold=10  --no-use_field_guards" -t120 service/implicit_getter_setter_test
python tools/test.py -aia32 --exclude-suite pkg --vm-options "--optimization-counter-threshold=10  --no-use_field_guards" -t120 language/cha_deopt2_test

**Comment by fsc8000** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/15f23eedc9d9383a62aac36e31ff93a1ebb36b91
