### ISSUE TITLE
dart2js supporting an option to generate JS not depending on browser (for easy sharing code with swift and others)

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#25959]
We're trying to share the same Dart library in Swift environment by compiling it into JS code. Unfortunately, the generated JS code assumes window, document and other browser related stuffs. We manage to escape them, though tedious.

It will be great if dart2js provides an option for generating browser-less code.

**Comment by sigmundch** [comment]
Have you tried using the [preamble code](https://github.com/dart-lang/sdk/tree/master/sdk/lib/_internal/js_runtime/lib/preambles)?

Dart2js uses some browser features to implement some of it's core libraries like dart-async, and to implement some features like deferred loading. Some features require more than others, but it might be possible to provide JS implementations of what you need (assuming you are not using dart:html directly, of course). The folder above has preamble files to do this for running directly on d8 (command-line version of v8) and jsshell (firefox's engine), but you might be able to adapt them to fit the needs of your specific environment.

**Comment by tomyeh** [comment]
Thanks for the information.

What we share are just some plain but sophisticated library, such as a customised markdown converter. No dart:html, of course. We don't use dart:async in this library so far, but it could be a plus we can. Like I mentioned, we managed to get it work on swift. Not difficult but tedious and vulnerable to future d2j.

Anyway, I think it is a good feature to support. It is helpful for people who'd like share code among different platforms.

**Comment by joshualitt** [comment]
Closing because we have dart2js_server mode, which I think fulfills some of the requirements for this bug.
