### ISSUE TITLE
Add a callback method in Dart_Initialize that will be called when a thread pool thread dies

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#25950]
/**
 * A thread death callback function.
 *
 * This callback, provided by the embedder, is called before a thread in the vm
 * thread pool exits.
 *
 * This function could be used to dispose of native resources that
 * are associated and attached to the thread, in order to avoid leaks.
 */
typedef void (*Dart_ThreadExitCallback)();

Change Dart_Initialize as follows:
DART_EXPORT char* Dart_Initialize(
    const uint8_t* vm_isolate_snapshot,
    const uint8_t* instructions_snapshot,
    const uint8_t* data_snapshot,
    Dart_IsolateCreateCallback create,
    Dart_IsolateInterruptCallback interrupt,
    Dart_IsolateUnhandledExceptionCallback unhandled_exception,
    Dart_IsolateShutdownCallback shutdown,
    Dart_FileOpenCallback file_open,
    Dart_FileReadCallback file_read,
    Dart_FileWriteCallback file_write,
    Dart_FileCloseCallback file_close,
    Dart_ThreadExitCallback thread_exit,
    Dart_EntropySource entropy_source,
    Dart_GetVMServiceAssetsArchive get_service_assets);

**Comment by zanderso** [comment]
Maybe instead (or in addition) a callback to request a thread from the embedder whose lifetime the embedder manages? If no callback is provided we fall back onto our //runtime/vm/thread_pool.cc. Something like:

`int (Dart_ThreadCallback)(int (*)(void*), void*)`

The embedder could make a one-off thread to run the function, or run on its own thread pool, and wrap the thread in whatever initialization and cleanup code it needs.

**Comment by a-siva** [comment]
Landed https://codereview.chromium.org/1807293002/ which does the basic thread death callback.

Zach is there a use case for creation of a thread whose lifetime is managed by the embedder?

**Comment by iposva-google** [comment]
We can open a different feature request if we decided that the embedder needs to supply threads to the pool. Closing.
