### ISSUE TITLE
add error codes into the analysis server protocol

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25958]
Right now error messages have severity, type, location, and message, but not their code. We need a way to know the specific code of a message so that we can show users an option to suppress them at source locations (or add them to the `.analysis_options` file).

My understanding is that the codes themselves are likely going to change, but (old or new codes) we'll still need a slot for them in the protocol.

```
  final String severity;
  final String type;
  final Location location;
  final String message;
  @optional final String correction;
  @optional final bool hasFix;
```

**Comment by pq** [comment]
https://codereview.chromium.org/1774913006/

**Comment by pq** [comment]
Implemented in https://github.com/dart-lang/sdk/commit/e7e205f00b24faf9ee5cdf0baf21b8a0a04f8c3a.
