### ISSUE TITLE
dart samples invalid link

### ISSUE THREAD

**Issue by sircco** [dart-lang/sdk#25963]
in official docs it is specified:

For even more examples, see Dart HTML5 Samples on Github.

but on 
https://github.com/dart-lang/dart-samples/blob/master/deferred_loading_samples/lazyloader/README.md
link to deferred loading is invalid
probably it should point to
https://www.dartlang.org/docs/dart-up-and-running/ch02.html#deferred-loading

**Comment by natebosch** [comment]
Filed https://github.com/dart-lang/dart-samples/issues/114
