### ISSUE TITLE
Invalid URLs in Dart API documentation

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25960]
It is possible to download the generated API documentation bundle from official Dart site https://www.dartlang.org/downloads/archive/
The bundle contains a lot of HTML files with the following code:

``` html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26406144-9', 'auto');
  ga('send', 'pageview');

</script>

<script async src="//survey.g.doubleclick.net/async_survey?site=4vq7qmqpfn4zjduve64c4h6lqa">
</script>
```

If the documents are opened from local drive, the URL of document is like `file:///D:/dev/dart/gen-dartdocs/dart-async/Stream/isEmpty.html`. The references  `//www.google-analytics.com/analytics.js` and `//www.google-analytics.com/analytics.js` are transformed into  `file://www.google-analytics.com/analytics.js` and `file://www.google-analytics.com/analytics.js`. These URLs are invalid and cause enormous delays when documents are opened in Chrome.

**Comment by alsemenov** [comment]
Chrome developer tools also report error

> script.js:194 XMLHttpRequest cannot load file:///D:/dev/dart/gen-dartdocs/index.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by floitschG** [comment]
This looks like a Dartdoc issue. Should we migrate it to its bug tracker?

Ccing @lukechurch . Maybe he knows more about the tracking links.
