### ISSUE TITLE
Exception computing quick fix

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25962]
I don't know what the code looked like when this error occurred, but it was almost certainly invalid code that caused the exception. I think it was while I was editing one line, and the likely intermediate states are:

    _checkPackageMap(root, isNull);
    _checkPackageMap(_packageMaproot, isNull);
    _checkPackageMap(_packageMap()root, isNull);
    _checkPackageMap(_packageMap(root, isNull);
    _checkPackageMap(_packageMap(root), isNull);
    expect(_packageMap(root), isNull);

Dart analysis server, SDK version 1.15.0-edge.d8786ac278f98e771e230970ee860f35ea7a6ff1, server version 1.14.0, error: Exception from fix contributor: DefaultFixContributor
RangeError: Index: 1, Size: 1
#0      NodeListImpl.[] (package:analyzer/src/dart/ast/ast.dart:7565)
#1      FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:432)
#2      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:245)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:891)
#5      _CustomZone.run (dart:async/zone.dart:790)
#6      _CustomZone.runGuarded (dart:async/zone.dart:696)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#8      _rootRun (dart:async/zone.dart:895)
#9      _CustomZone.run (dart:async/zone.dart:790)
#10     _CustomZone.runGuarded (dart:async/zone.dart:696)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1776353003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/21ed1750cef0cfed837d24637a15cae35d28953d
