### ISSUE TITLE
JsFunction no longer implements Function

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#25976]
After upgrading to SDK 1.15.0 I noticed that JsFunction no longer implements Function, this was done by this [commit](https://github.com/dart-lang/sdk/commit/cf7ae2e0cb2c9af91c86ee603a71d114e72905db). Because of that change you can no longer call a JsFunction. 

What is the suggested way to call a JsFunction going forward?

**Comment by jacob314** [comment]
You should use https://pub.dartlang.org/packages/js
I believe dart2js never supported JsFunction that implements Function.
What code did you have that relied on JsFunction implementing function?

**Comment by jacehensley-wf** [comment]
Ahh I see, yeah we are planning to move to package:js fairly soon. Thanks for the quick response!
