### ISSUE TITLE
Unable to code complete a named param in a constructor that already has params

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25975]
Flutter uses named params all over the place, and so we'd love some help to make this better.

Here's the example code:

```
class Foo {
  String name;
  int number;
  Foo({this.name, this.number});
}

main() {
  var f = new Foo(
    
    number: 1);
}
```

Looks like the analyzer server isn't sending code completion options when you try to code complete from within a constructor that already has some named params declared.

Take this example behavior:

![screen shot 2016-03-10 at 3 09 21 pm](https://cloud.githubusercontent.com/assets/5479/13687800/7a64856e-e6d2-11e5-8fcd-49b69071040c.png)

In the above, I would expect to see `name: String` as an option at the top.

If I try to code complete inside an empty constructor, I do get named param options:

![screen shot 2016-03-10 at 3 08 54 pm](https://cloud.githubusercontent.com/assets/5479/13687795/724567cc-e6d2-11e5-8980-a4d19fc6406a.png)

Notice this behavior is consistent in dartpad and webstorm, so I'm guessing (?) this is an Analyzer Server thing, and not just an Atom thing.

![screen shot 2016-03-10 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/5479/13687810/91a31ba0-e6d2-11e5-8ad5-87f3976a8a33.png)

![screen shot 2016-03-10 at 2 59 07 pm](https://cloud.githubusercontent.com/assets/5479/13687820/9bdf50ca-e6d2-11e5-87b1-1ecb8150edf4.png)

We'd love to give our users the ability to code complete a named parameter.

Also, can we show the type of the named param? In all cases (atom, webstorm, dartpad) the type is not shown.

Thanks for taking a look!

**Comment by bwilkerson** [comment]
@danrubel

**Comment by jwren** [comment]
I am close to having a pull request to fix this, I hope to have it fixed and committed within a few days.

**Comment by sethladd** [comment]
Thanks!

I might also add, not only would I expect to see `name: String` as the first option, I also would _not_ expect to see `bool` or `const` in the list. The only thing I can put in there is `name: something`.

**Comment by jwren** [comment]
https://codereview.chromium.org/1806113002/

**Comment by jwren** [comment]
Fix has been landed, https://codereview.chromium.org/1806113002/
