### ISSUE TITLE
Fatal lints

### ISSUE THREAD

**Issue by tonygentilcore** [dart-lang/sdk#25977]
I'd like to be able to make lints fatal (non-zero exit code) without writing a wrapper to scrape the output. A `--fatal-lints` would do the trick as well as something in `.analysis_options`.

**Comment by zoechi** [comment]
Seems this is already implemented (not tried myself yet) #24452

**Comment by tonygentilcore** [comment]
AFAICT, that lets you have fatal warnings and hints, but not lints. Flutter still wraps the analyzer in a script that checks for lint outputs because the exit code is 0 when there are only lints. I'm testing with
```
dartanalyzer version 1.15.0-dev.4.0
```

/cc @sethladd

**Comment by pylaligand** [comment]
If nobody is fundamentally opposed to it, I'll take a stab at adding the option.

**Comment by bwilkerson** [comment]
Contributions are always welcome!

If "fatal" just means a non-zero error code from the command-line analyzer, then it makes more sense to me for it to be a command-line analyzer flag.

**Comment by pylaligand** [comment]
PR is out for review.
