### ISSUE TITLE
dartanalyzer fails on startup for dangling symlink in package directory

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25984]
Maybe we should skip the symlink and continue, and report bad imports if the package is ever used?

Unhandled exception:
FileSystemException: Cannot resolve symbolic links, path = '[redacted]' (OS Error: No such file or directory, errno = 2)
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:679)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:346)
#2      _PackageRootPackageMapBuilder.buildPackageMap (package:analyzer_cli/src/driver.dart:651)
#3      Driver._chooseUriResolutionPolicy (package:analyzer_cli/src/driver.dart:326)
#4      Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:406)
#5      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:139)
#6      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#8      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#9      Driver.start (package:analyzer_cli/src/driver.dart:112)
#10     main ([redacted]/analyzer_cli/bin/analyzer.dart:14)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
