### ISSUE TITLE
Unhelpful message "A value of type '(int) → Future<int>' cannot be assigned to a variable of type 'VMServiceConnectFunction'"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25988]
When the analyzer doesn't like how you're assigning a function reference, it gives a message of the form:

```
[warning] A value of type '(int) → Future<int>' cannot be assigned to a variable of type 'VMServiceConnectFunction'
```

...which would be far more helpful if it actually told me what 'VMServiceConnectFunction' _was_.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1795233002/

Given code like this:

    typedef int Binary(int x, int y);

    void main() {
      Binary f = (int a) => a;
    }

The error message now reads:

    A value of type '(int) → int' cannot be assigned to a variable of type 'Binary(int, int) → int'

**Comment by Hixie** [comment]
fantastic! thanks!

**Comment by sethladd** [comment]
Apparently this isn't fixed in all cases? See issue 6183 above.

**Comment by srawlins** [comment]
Closing in favor of newer bugs which may have been filed.
