### ISSUE TITLE
Static checking of for in statements. These will now produce static warnings:

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#25980]
```dart
// Not Iterable.
for (var i in 1234) { ... }
```

Dart language specification:
17.6.2 For-in for-in
A for statement of the form for (f inalConstV arOrT ype? id in e) s is
equivalent to the following code:

```dart
var n0 = e.iterator;
while (n0.moveNext()) {
  finalConstVarOrType? id = n0.current;
 s
}
```

This means that for `for-in` statement does not requires an `Iterable` (in any way).
All that is necessary is that the object instance has the getter `iterator` with type of `Iterator` (by the lang spec).
More precisely, only the getter `iterator` is required with the following criteria (by lang spec):
- Method `bool moveNext()`
- Getter `T current`

Currently analyzer does not follows the language specification.
I get a lot of errors even if my classes follow language specification and implements the getter `iterator` with the type of `Iterator`.

Eg.
Type check failed: this (_ReadOnlyCollection<TKey, TValue>) is not of type Iterable<dynamic>

```dart
    for (var kvp in this) {
      map[kvp.key] = kvp.value;
    }
```

This is unpleasant (does not follow language spec) for a serious project such as Google Dart.

Is there any reasonable explanations of such behavior of analyzer (does not meet ECMA-408)?

**Comment by mezoni** [comment]
P.S.

Bad

```dart
// Not Iterable.
for (var i in 1234) { ... }
```

Good

```
// Not implements iterator.
for (var i in 1234) { ... }
```

**Comment by mezoni** [comment]
[Using foreach with Collections](https://msdn.microsoft.com/en-us/library/aa288257(v=vs.71).aspx)

To iterate through a collection, the collection must meet specific requirements. For example, in the following foreach statement:

The collection type:
 - Must include an instance method named GetEnumerator that returns a type, for example, Enumerator (explained below).

The type Enumerator (a class or struct) must contain:
- A property named Current that returns ItemType or a type that can be converted to it. The property accessor returns the current element of the collection.
- A bool method, named MoveNext, that increments the item counter and returns true if there are more items in the collection.

The same specification I found in Dart language specification (ECMA-408, 17.6.2) but the authors of the code analyzer probably do not know anything about this rule in ECMA-408.

**Comment by munificent** [comment]
We intend the change the spec to follow analyzer's behavior. The originally specified behavior was never implemented.

**Comment by mezoni** [comment]
>> We intend the change the spec to follow analyzer's behavior. The originally specified behavior was never implemented.

Thank you for the answer.
Now I know that the your analyzer does not follows the official language specification.
But I wonder why? Only because you wrote `we intend the change the spec`?
Is this enough to violate with the official language specification?

>> The originally specified behavior was never implemented.

Never implemented is not same as the current situation (violation with the official language specification).

**Comment by lrhn** [comment]
What Bob is saying is that this is a know error in the analyzer, and we plan to fix it by changing the specification to match.

In practice, non-`Iterable` objects are only very rarely used in a `for-in` iteration, so when the analyzer detects it happening, it's more likely to be an error than a deliberate choice to have a non-`Iterable ` class (with or without an `iterable` getter). Making it a warning will, on average, help people.

**Comment by kmillikin** [comment]
Why is it likely an error to use `for-in` over an object that provides a suitable `.iterator` but doesn't implement the (pretty big) `Iterator` interface?  What could go wrong?

**Comment by mezoni** [comment]
I strarted refactoring my old package (queries)[https://pub.dartlang.org/packages/queries] to the new package `enumerable` (without the plans to implement queriables).

Currently Dart (when it implements coroutines) is more attractive but with the changes of the requirements to be an `Iterable` instead of to be at least able to iterate (eg. have an `Iterable iterator` which is enough for iterations because `Iterable` in Dart is very complex and not used directly in iterations).

With intended changes will not be possible use in `for-in` statements other instances of types able to iterations (with iterators).

It is very good that I found out about the planned changes early enough and it's bad because it limits the development of third-party implementations of the missing functionality.

I had planned to do a mix of IEnumerable with IObservable in Dart and it's very good that I found out about your new plans.
Thanks for the clarification, it will save me from wasting their time.

**Comment by mezoni** [comment]
@kmillikin  
>> Why is it likely an error to use for-in over an object that provides a suitable .iterator but doesn't implement the (pretty big) Iterable interface? What could go wrong?

It was a rhetorical question, or you are looking to get a plausible answer from your colleagues?

P.S.
Well-known fact - `Iterable` is not necessary to the iterations, just enough of `Iterator` (and, of course, the instance which provides the right access to the reenterant iterator's instance which does not necessarily have to be an `Iterable`).

**Comment by munificent** [comment]
>  Iterable in Dart is very complex and not used directly in iterations

Any class that implements `.iterator` can extend IterableBase or mix in IterableMixin and get all of the other required Iterable methods for free. Those two classes implement those methods in terms of the one required `.iterator` getter, which is the one thing for-in requires too.

**Comment by lrhn** [comment]
@kmillikin 
> Why is it likely an error to use `for-in` over an object that provides a suitable `.iterator` but doesn't implement the (pretty big) `Iterable` interface?  What could go wrong?

Looking only at statistics, it's more likely that you forgot to extend or mix-in `Iterable` than that you intended to make a non-`Iterable` class that has an `iterator` getter that returns something compatible with `Iterator`. There are many `Iterable` classes, and very, very few non-`Iterable` classes compatible with `for-in`.

It's not uncontroversial to change this to give a static warning, but I personally think it's the right choice. Users should not have to worry about being for-in'able and being `Iterable` as two different concepts.

**Comment by kmillikin** [comment]
@lrhn I don't know about the likelihood, but if I made a non-Iterable class with an iterator getter that returns something compatible with Iterator, and then used for-in over it, I didn't do it by accident.

I still don't think it's even likely a bug and the warning doesn't help avoid any bugs as far as I can see.  It would be a bug to trying to call takeWhile or whatever on something that doesn't implement it and that's what we should warn about.

There are workarounds, of course: 

1. Ignore or suppress the warning.
2. Fix the warning by implementing Iterable even when you don't want to (which isn't entirely 'free').
3. Fix the warning by using while, not for-in.

I guess I'd choose 3, but it feels like jumping through a hoop.

**Comment by munificent** [comment]
It's definitely the case that you can write valid code that would do what you want if for-in was structurally typed instead of nominally typed. I think that's true of structural typing in general.

The interesting question for me is how that choice fits into the rest of the language, and how Dart fits into the larger language ecosystem. In general, Dart is nominally typed. You cannot assign A to B even if A's method set is a superset of B's. `yield*` considers it a *dynamic* error if the object does not implement `Iterable` or `Stream`.

Having a couple of corners that are structurally typed feels to me like it adds complexity—both in terms of implementing the static checking and in the user's mental model of the language—for little net benefit. 

Looking at a broader scope, if you compare Dart to other high level client-side languages like TypeScript, I think one of its key differentiators is that it is nominally typed. I think it makes more sense for Dart to focus on that than to try to blend a few random ad-hoc bits of structural typing into the spec.
