### ISSUE TITLE
analyzer should have a mode where it includes the error name in parentheses after the message

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25981]
e.g.:

```
[lint] Specify type annotations. (popup_menu.dart, line 341, col 3, always_specify_types)
```

This should not be the default mode (too verbose), but it would be useful to be able to enable this mode.

**Comment by bwilkerson** [comment]
This is currently provided with machine formatted output (`--machine`). Is that sufficient, or do you need a more human readable form?

**Comment by Hixie** [comment]
`--machine` hides the message, so it doesn't really work for this use case, which is to figure out what the code is for a particular message. :-)

**Comment by zoechi** [comment]
I think the code should always be included. In what situation would it be too verbose?

**Comment by srawlins** [comment]
I suspect this has changed in the intervening years. The error name is printed by default:

```none
$ cat 21739.dart 
class C {
  final int i = null;
  f() {
    i = 1;
  }
}
$ dartanalyzer 21739.dart 
Analyzing 21739.dart...
  error • 'i' can't be used as a setter because it's final. • 21739.dart:4:5 • assignment_to_final
1 error found.
```
