### ISSUE TITLE
Future.value and Future.sync are bug-prone because they're not typed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25989]
Future.value's argument should be of type T; Future.sync's argument should be a generic typedef with a type argument T that returns T and has no arguments.

**Comment by lrhn** [comment]
That would be great if it worked, but both `Future.sync` and `Future.value` also accept `Future<T>` as value, so the actual type is the union of `T` and `Future<T>`.

**Comment by Hixie** [comment]
I think that's a mistake (just use `await` to handle it) but if we can't fix that then can we have Union types? The situation right now is that we have bugs that the analyzer isn't catching.

**Comment by bwilkerson** [comment]
It wouldn't be that hard to add a hint to the analyzer to catch these issues. It would be better, of course, if we didn't have to special case because the type system wasn't able to express everything, but this wouldn't be the first place we've done so.

@pq Want to add these to your list?

**Comment by bwilkerson** [comment]
I'm guessing that this is no longer relevant. Please re-open if I'm wrong.
