### ISSUE TITLE
Dart install via apt-get on Ubuntu machine not working

### ISSUE THREAD

**Issue by sjelin** [dart-lang/sdk#25987]
I followed the instructions at https://www.dartlang.org/downloads/linux.html#install-with-apt-get but it didn't work.  Here's my console output:

```
sjelin@sjelin-linux:~/angular$ sudo apt-get update
[sudo] password for sjelin: 
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com InRelease
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com InRelease
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons InRelease
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com/main i386 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com/main i386 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main i386 Packages

sjelin@sjelin-linux:~/angular$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

sjelin@sjelin-linux:~/angular$ sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1745  100  1745    0     0  18042      0 --:--:-- --:--:-- --:--:-- 18177
OK

sjelin@sjelin-linux:~/angular$ sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0    504      0 --:--:-- --:--:-- --:--:--   505

sjelin@sjelin-linux:~/angular$ sudo apt-get update
Ign https://storage.googleapis.com stable InRelease
Ign https://storage.googleapis.com unstable InRelease
Ign https://storage.googleapis.com stable Release.gpg
Ign https://storage.googleapis.com unstable Release.gpg
Ign https://storage.googleapis.com stable Release
Ign https://storage.googleapis.com unstable Release
Err https://storage.googleapis.com stable/main amd64 Packages
  Could not resolve proxy: apt-squid.corp.google.com
Err https://storage.googleapis.com unstable/main amd64 Packages
  Could not resolve proxy: apt-squid.corp.google.com
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com InRelease
Get:1 https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com InRelease
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons InRelease
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@sjelin-linux.sea.corp.google.com/main i386 Packages
Get:2 https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com/main amd64 Packages
Get:3 https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@sjelin-linux.sea.corp.google.com/main i386 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main i386 Packages
Fetched 43.1 kB in 3s (12.5 kB/s)
W: Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/main/binary-amd64/Packages  Could not resolve proxy: apt-squid.corp.google.com

W: Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/unstable/main/binary-amd64/Packages  Could not resolve proxy: apt-squid.corp.google.com

E: Some index files failed to download. They have been ignored, or old ones used instead.

sjelin@sjelin-linux:~/angular$ sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    97  100    97    0     0    505      0 --:--:-- --:--:-- --:--:--   507
sjelin@sjelin-linux:~/angular$ sudo apt-get install dart
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dart

sjelin@sjelin-linux:~/angular$ dart
No command 'dart' found, did you mean:
 Command 'dact' from package 'dact' (universe)
 Command 'darts' from package 'darts' (universe)
 Command 'zart' from package 'gmic-zart' (universe)
 Command 'dat' from package 'liballegro4-dev' (universe)
 Command 'dar' from package 'dar' (universe)
 Command 'tart' from package 'tart' (universe)
 Command 'dirt' from package 'dput-ng' (universe)
dart: command not found
```

I was able to do a manual install though so that's good.

cc @leafpetersen

**Comment by juniorsatanas** [comment]
Unable to locate package dart

**Comment by whesse** [comment]
The failure to fetch from 
https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/main/binary-amd64/Packages
was the problem.

There is a message about "Could not resolve proxy: apt-squid.corp.google.com"
If you are trying to install Dart this way on a internal Google workstation, it won't work because this external repository cannot be added to your apt-get universe for security reasons.  Please install Dart
in the special way designed for internal Google users.
If you are not an internal Google user, please try again, and reopen the issue if it still fails.

**Comment by kamhawy4** [comment]
sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
 sudo apt-get update
 sudo apt-get install dart

**Comment by kamhawy4** [comment]
https://dart.dev/get-dart

**Comment by ngdangtu-vn** [comment]
OS: Ubuntu 20.10 for Raspberry Pi

I followed the (https://dart.dev/get-dart) link even before I came here and I still got this error. Before that, I've tried on Raspberry Pi OS and it works very well. It only failed on Ubuntu 20.10.

Mine doesn't have any message like `Could not resolve proxy: apt-squid.corp.google.com` during the whole installation.

It only has this when I started `sudo apt install dart`:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dart
```

Also, I had checked that `dart` is exist:

```
dart-doc/groovy 6.9.2-3ubuntu1 all
dart/stable 2.10.4-1 amd64
darts/groovy 0.32-20 arm64
```

Does anyone have any idea?

**Comment by ciaranduffin** [comment]
@ngdangtu-vn I am having the same issue, did you ever find a fix?

**Comment by ngdangtu-vn** [comment]
> @ngdangtu-vn I am having the same issue, did you ever find a fix?

Yes, I found a tiny link on the same page that send me to this : https://dart.dev/tools/sdk/archive

From there I download the SDK for my OS (in my case is Raspberry OS, and later is Ubuntu 20.10) which is Linux ARMv8. After download, I unzip and set PATH. That's all.

**Comment by ChristopherDelgado** [comment]
> OS: Ubuntu 20.10 for Raspberry Pi
> 
> I followed the (https://dart.dev/get-dart) link even before I came here and I still got this error. Before that, I've tried on Raspberry Pi OS and it works very well. It only failed on Ubuntu 20.10.
> 
> Mine doesn't have any message like `Could not resolve proxy: apt-squid.corp.google.com` during the whole installation.
> 
> It only has this when I started `sudo apt install dart`:
> 
> ```
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package dart
> ```
> 
> Also, I had checked that `dart` is exist:
> 
> ```
> dart-doc/groovy 6.9.2-3ubuntu1 all
> dart/stable 2.10.4-1 amd64
> darts/groovy 0.32-20 arm64
> ```
> 
> Does anyone have any idea?

In case anyone has this problem again and was following the instructions at https://dart.dev/get-dart just make sure that you run sudo apt-get update one more time before attempting to install dart, the repository listings need to be refreshed.

**Comment by sourcecaster** [comment]
The same issue on a fresh ARM EC2 ubuntu 20.04 instance. Followed instruction exactly. Did run apt update.
root@ip-172-34-41-181:/tmp# sudo apt install dart
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dart
```

**Comment by apolat2000** [comment]
Why is this issue closed? I ran `sudo apt-get update` beforehand but i still get `E: Unable to locate package dart` when i run `sudo apt-get install dart`.

Any updates on this?

**Comment by 6a6kaBKedax** [comment]
Same problem. Run the bash commands one by one from this guide https://dart.dev/get-dart#linux and nothing work. 

E: Unable to locate package dart

DISTRIB_RELEASE=22.04
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**Comment by rafaneo** [comment]
If you copy the commands from [this](https://dart.dev/get-dart) link one by one it doesn't find the dart package but if you copy and paste them all at once it works just fine.
