### ISSUE TITLE
Building on fedora

### ISSUE THREAD

**Issue by waghanza** [dart-lang/sdk#25990]
Hi,

According to the [wiki](https://github.com/dart-lang/sdk/wiki/Building-Dart-on-CentOS,-Red-Hat,-Fedora-and-Amazon-Linux-AMI) bulding `Dart` is available for fedora
but when I try to build it (inside a docker), I have this message

~~~bash
ERROR: Only Ubuntu 12.04 (precise) through 14.04 (trusty) are currently supported
~~~
my `Dockerfile` is 
~~~dockerfile
FROM fedora:23
RUN dnf -y update
RUN dnf -y install @development-tools gcc-c++ wget redhat-lsb

RUN wget http://src.chromium.org/svn/trunk/src/build/install-build-deps.sh
RUN chmod +x install-build-deps.sh
RUN ./install-build-deps.sh --no-chromeos-fonts
~~~
Has anyone already built `Dart` on fedora ?

**Comment by rmacnak-google** [comment]
I believe that message comes from the Chromium install-build-deps scripts. If you aren't building Dartium, you can probably skip that step.

**Comment by waghanza** [comment]
you mean I could build `Dart` without `Chromium` ?

according to the doc https://github.com/dart-lang/sdk/wiki/Building-Dart-on-CentOS,-Red-Hat,-Fedora-and-Amazon-Linux-AMI I need depot_tools, no ?

**Comment by rmacnak-google** [comment]
Depot tools, yes. But not the dependencies installed by http://src.chromium.org/svn/trunk/src/build/install-build-deps.sh.
