### ISSUE TITLE
Short-circuit type inference is inverted with for and continue

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25998]
In the following code:

``` dart
void main() {
  for (var element in <int>[]) {
    if (element is! String) continue;
    print(element.isEmpty);
  }
}
```

emits a hint about `isEmpty` not being defined on `int`. This hint is bogus, since the `isEmpty` call can only be reached if the element is a string.

What's weirder, though, is what happens when we invert the conditional:

``` dart
void main() {
  for (var element in <int>[]) {
    if (element is String) continue;
    print(element.isEmpty);
  }
}
```

This _doesn't_ print a hint. It seems like the analyzer has an inverted notion of `continue`'s effect on control flow.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
