### ISSUE TITLE
parseDirectives causes bad Uri to be created

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#25996]
I was migrating to use the `build` project and ran into an issue with the analyzer within `parseDirectives`

```
CompilationUnit parseDirectives(String contents,
    {String name, bool suppressErrors: false}) {
  if (name == null) name = '<unknown source>';
  var source = new StringSource(contents, name);
  var errorCollector = new _ErrorCollector();
  var reader = new CharSequenceReader(contents);
  var scanner = new Scanner(source, reader, errorCollector);
  var token = scanner.tokenize();
  var parser = new Parser(source, errorCollector);
  var unit = parser.parseDirectives(token);
  unit.lineInfo = new LineInfo(scanner.lineStarts);

  if (errorCollector.hasErrors && !suppressErrors) throw errorCollector.group;

  return unit;
}
```

Since `name` is null the name becomes `<unknown source>`. This then goes into the StringSource constructor.

```
  StringSource(this._contents, String fullName)
      : this.fullName = fullName,
        uri = fullName == null ? null : new Uri.file(fullName),
        modificationStamp = new DateTime.now().millisecondsSinceEpoch;
```

If fullName is null then everything works as expected. However since its `<unknown source>` then the Uri constructor will throw.

Commenting out the if statement that sets the value seems to work.

@jakemac53

**Comment by bwilkerson** [comment]
Ah, I missed an occurrence. Yes, commenting out the line is the right fix.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1806843003/

**Comment by donny-dont** [comment]
:+1: guessing this will be in 0.27.3-alpha.3?

**Comment by bwilkerson** [comment]
Yes. The next version will probably be published by the end of the week.

**Comment by donny-dont** [comment]
Awesome thanks for the fix @bwilkerson. Keep up the good work
