### ISSUE TITLE
registerElement exceptions swallowed

### ISSUE THREAD

**Issue by eukreign** [dart-lang/sdk#25997]
It is impossible to unit test custom elements that register with `registerElement()` and happen to fail inside the `attached()` callback method. I filed a similar [bug in the test package repo](https://github.com/dart-lang/test/issues/406#issuecomment-196555759) but was asked to refile it here.

To reproduce:

1) create a foo project with this `pubspec.yaml`:

``` yaml
name: foobar
dependencies:
    test: any 
```

2) add `test/foo_test.dart`:

``` dart
import 'dart:html';
import 'package:test/test.dart';

class FooElement extends HtmlElement {
  FooElement.created() : super.created();
  attached() {
    print('Creating foo!');
    call_non_existent_method();
    print('Done creating foo!');
  }
}

void main() {
  test('x-foo', () {
    document.registerElement('x-foo', FooElement);
  }); 
}
```

3) add `test/foo_test.html`:

``` html
<x-foo></x-foo>
<link rel="x-dart-test" href="foo_test.dart">
<script src="packages/test/dart.js"></script>
```

4) running the test swallows the exception:

``` shell
$ pub run test:test -p content-shell
00:00 +0: loading test/foo_test.dart
00:01 +0: loading test/foo_test.dart
00:02 +0: loading test/foo_test.dart
00:03 +0: loading test/foo_test.dart
00:03 +0: test/foo_test.dart: x-foo
00:03 +0: test/foo_test.dart: x-foo

Creating foo!
00:03 +1: test/foo_test.dart: x-foo
00:03 +1: All tests passed!                                                                        
```

Notice that only `Creating foo!` printed to the console above and no exception was reported.

**Comment by eukreign** [comment]
Any ideas or solutions? Would be really nice if exceptions in `attached()` would show up somewhere.

**Comment by elmcrest** [comment]
annoying! :)

**Comment by eukreign** [comment]
Is this going to be a WONTFIX and then with DDC it will no longer be a problem? Would be nice if someone from Dart team would provide some feedback on this.

Since exceptions are swallowed I suspect a lot of people who encounter this problem just think they are doing something wrong with their elements and not knowing what (since no errors are printed anywhere) they just give up on custom elements altogether, which is rather unfortunate.

The situation with `created()` is even worse where even `print()` statements are swallowed :-(

**Comment by matanlurey** [comment]
Dartium and ContentShell are no longer supported.
