### ISSUE TITLE
Precompilation: Instructions don't need an object header

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25992]
Instructions are currently snapshotted to look like pre-marked objects so they can be traversed. We could remove these headers, not traverse their pages, and have Code object reference them only by their entry points instead of as object pointers.

**Comment by iposva-google** [comment]
CC @mraleph @fsc8000

**Comment by fsc8000** [comment]
Same for other objects in .rodata (PC descriptors, stack maps, string literals)?

**Comment by rmacnak-google** [comment]
String literals will still show up as the targets of object pointers and receivers of instance calls, so they need an object header. PC descriptors and stack maps would be candidates though.

**Comment by rmacnak-google** [comment]
b2f3e8efe1f32bacad99ddbedbc434a6102d8be2
