### ISSUE TITLE
Analyzer doesn't report static warning for assert statement.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#26002]
According to Dart Language specification (4th edition, Dec 2015) "16.33 Identifier Reference":

"It is a static type warning if the type of e may not be assigned to either bool or () → bool."

However, dartanalyzer does not report warning for test below.

``` dart
bool foo(x) {
  return false;
}

main() {
  try {
    assert (foo); /// static type warning
  } catch (e) {
  }
}
```

Tested with Dart VM version: 1.16.0-dev.0.0 (Wed Mar  9 15:14:15 2016) on "linux_x64".

**Comment by zoechi** [comment]
Seems related #25613

**Comment by srawlins** [comment]
`assert` now only accepts a bool, not a function. This bug is obsolete.
