### ISSUE TITLE
Comparable Enums

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#26000]
Pretty simple language request: make enums comparable.

``` dart
enum Count {one, two three}
print(Count.one.index < Count.three.index); // true
print(Count.one < Count.three);
                ^ The operator '<' is not defined for the class 'Count'

```

**Comment by lrhn** [comment]
While that makes sense for some enumerations, it makes no sense for others - `Color.red < Color.blue`?

I'd rather have a way to extend enums with user specified functionality, then you could add a `<` operator yourself:
```dart
enum Number {
  one, two, three;
  bool operator<(Number other) => id < other.id;
}
```

That is: I don't think this particular extension of enums is worth a language change, but giving users the option to extend enums as needed would pay for itself.

**Comment by jtmcdole** [comment]
Except that blue < red does make sense from a [wavelength perspective](https://en.wikipedia.org/wiki/Frequency#/media/File:EM_spectrum.svg) ;)  Agreed - user extending enums would be great.

**Comment by lrhn** [comment]
While I'm still all for increasing the power of enum declarations, this particular request by itself is not going to happen.
