### ISSUE TITLE
Observatory: cpu profile unusable with long method names

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26006]
Dart2js has a class created with many mixins that the VM names:

Visitor&IrBuilderMixin&SemanticSendResolvedMixin&ErrorBulkMixin&BaseImplementationOfStaticsMixin&BaseImplementationOfLocalsMixin&BaseImplementationOfDynamicsMixin&BaseImplementationOfConstantsMixin&BaseImplementationOfNewMixin&BaseImplementationOfCompoundsMixin&BaseImplementationOfSetIfNullsMixin&BaseImplementationOfIndexCompoundsMixin

It has a constructor called:

Visitor&IrBuilderMixin&SemanticSendResolvedMixin&ErrorBulkMixin&BaseImplementationOfStaticsMixin&BaseImplementationOfLocalsMixin&BaseImplementationOfDynamicsMixin&BaseImplementationOfConstantsMixin&BaseImplementationOfNewMixin&BaseImplementationOfCompoundsMixin&BaseImplementationOfSetIfNullsMixin&BaseImplementationOfIndexCompoundsMixin.Visitor&IrBuilderMixin&SemanticSendResolvedMixin&ErrorBulkMixin&BaseImplementationOfStaticsMixin&BaseImplementationOfLocalsMixin&BaseImplementationOfDynamicsMixin&BaseImplementationOfConstantsMixin&BaseImplementationOfNewMixin&BaseImplementationOfCompoundsMixin&BaseImplementationOfSetIfNullsMixin&BaseImplementationOfIndexCompoundsMixin

When this name is displayed in the cpu profile, the profile becomes too wide to be usable.

It might be an idea to move the columns after the name to before the tree (i.e. from far right to far left).

**Comment by turnidge** [comment]
@rakudrama, could you add a screen shot?  I just want to see how bad this looks.

**Comment by johnmccutchan** [comment]
The UI for the profiler has been changed so that it is usable with long method names.
