### ISSUE TITLE
VM crash when accessing cpu profile

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26013]
1. Checkout revision 149ad3a2e9a9d21e8f2ec14faf72aff9c5ccc83b of the sdk repository.
2. Build the SDK. My build script looks like this:

    ./tools/build.py --mode release --arch ia32 packages
    ./tools/build.py --mode release --arch ia32 create_sdk

then copies the built SDK to `/Users/brianwilkerson/Dev/dart/dart-sdk`.

3. Copy the attached file to `sdk/pkg/analyzer/test/performance/time_resolve_unit_type_names_task.dart` (requires a rename) and edit the explicit paths in it to match your machine.
4. Run the following command

    /Users/brianwilkerson/Dev/dart/dart-sdk/bin/dart --ignore-unrecognized-flags --pause_isolates_on_exit --observe=8181 --checked --enable-vm-service:63597 --trace_service_pause_events /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/test/performance/time_resolve_unit_type_names_task.dart

5. While the command is running, using the printed URL to open observatory. After the program has finished running (about 3 minutes), click on "cpu profile (table)". The output I see is shown below.

    Observatory listening on http://127.0.0.1:63597
    Analyzing 8920 files
    Completed 1 analyses
      total time   = 180585ms
      compute time = 72604ms
      task time    = 18600ms
    Isolate time_resolve_unit_type_names_task.dart$main-658343601 paused before exiting. Use the Observatory to release it.
    dart(71583,0xb1753000) malloc: *** mach_vm_map(size=8388608) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

    Process finished with exit code 134

[time_resolve_unit_type_names_task.txt](https://github.com/dart-lang/sdk/files/176213/time_resolve_unit_type_names_task.txt)

**Comment by johnmccutchan** [comment]
Thanks for the report. I'm trying to reproduce this now. Just some notes about your command line:

$ Users/brianwilkerson/Dev/dart/dart-sdk/bin/dart --ignore-unrecognized-flags --pause_isolates_on_exit --observe=8181 --checked --enable-vm-service:63597 --trace_service_pause_events 

--observe implies --pause_isolates_on_exit
--observe=8181 is equivalent of --enable-vm-service:8181

The command like could be written as:

--observe=63597

**Comment by johnmccutchan** [comment]
When I try and run it I get the following:

Analyzing 4270 files
Unhandled exception:
AnalysisException: Cannot compute RESOLVED_UNIT3 for /usr/local/google/home/johnmccutchan/workspace/dart/sdk/pkg/analyzer/test/instrumentation/test_all.dart in /usr/local/google/home/johnmccutchan/workspace/dart/sdk/pkg/analyzer/test/instrumentation/test_all.dart
Caused by Could not resolve "dart:core": SDK incorrectly configured

**Comment by johnmccutchan** [comment]
I was able to go and look at the CPU profile even with that exception but could not reproduce.

**Comment by iposva-google** [comment]
The error being printed is indicative of the process being entirely out of address space. We need to make sure we are reproducing this on a 32-bit build and I guess with all of the analyzer data loaded into memory.

**Comment by johnmccutchan** [comment]
@iposva-google Good point.
