### ISSUE TITLE
A value of type 'void' cannot be assigned to a variable of type 'Null'

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#26025]
I'm extending a generic class:

```dart
class B<T> {
  T execute();
}

class A extends B<Null> {
 void execute();
}
```

`void` and `Null` should be interchangeable here to be able to write nice Dart code.

```dart
Null execute() {
  ...
  return null;
}
```

looks weird and adds unnecessary boilerplate. A return value of type `Null` can always only be `null`.

**Comment by floitschG** [comment]
We are going to allow `void` as generic argument.
At the same time `void` won't guarantee a `null` value anymore.

As a consequence I'm closing this issue.
