### ISSUE TITLE
Regression: TODOs treated as errors by dartanalyzer as of 1.16.0-dev.1.0

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#26026]
Given:
```dart
// TODO(ochafik): hello.
main() {}
```

Then `dartanalyzer --strong ~/analyzer.dart` yields:
```
Analyzing [/Users/ochafik/analyzer.dart]...
[error] TODO(ochafik): hello. (/Users/ochafik/analyzer.dart, line 1, col 4)
1 error found.
```

```
dartanalyzer --version
dartanalyzer version 1.16.0-dev.1.0
````

Works fine in 1.16.0-dev.0.0 (emitted as `hint` instead of `error`)

**Comment by jwren** [comment]
To clarify, does this regression only happen with strong-mode enabled?

**Comment by kevmoo** [comment]
@jwren I have strong mode enabled – yes

**Comment by kevmoo** [comment]
@jwren ...and disabling strong mode eliminates the squiggles.

**Comment by leafpetersen** [comment]
@munificent Is this related to your error message changes?

**Comment by munificent** [comment]
Gah, it must be. I'll take a look.

**Comment by munificent** [comment]
Sorry about that. Accidentally made strong mode REALLY STRONG mode. :metal: :angry: :metal:

**Comment by ochafik** [comment]
AUTHORITARIAN mode FTW! (todo -> thou shalt do it now... would solve so many issues!)

Thanks for the quick fix!

**Comment by lexaknyazev** [comment]
With 1.16.0-dev.2.0 `Unsound implicit cast (strong_mode_down_cast_composite)` reports as an `error`. Was `warning` with 1.15.0.

**Comment by leafpetersen** [comment]
@munificent

**Comment by munificent** [comment]
I'll take a look.

**Comment by kevmoo** [comment]
@munificent different bug, no? The TODO issue has not regressed, right?

**Comment by munificent** [comment]
If it is an issue, it's probably still caused by the same severity promotion code.

**Comment by munificent** [comment]
https://codereview.chromium.org/1833553002/
