### ISSUE TITLE
Cascaded catchError doesn't prevent calling of runZoned onError handler

### ISSUE THREAD

**Issue by snrnats** [dart-lang/sdk#26022]
Assume we have a **Future** that throw an error inside **runZoned**. If we use cascade notation (“double dot”) to call **then()** and **catchError()** then both catchError handler and runZoned error handler will get the error. For sure there is no reason to use cascade notation to handle Future errors. However I found it in a project I am working on. Thus it can lead  to unexpected behaviour.

Here is an example:
https://dartpad.dartlang.org/cecfa8b63ef024c59f30

**Comment by lrhn** [comment]
That sounds exactly right - if you use cascade notation then you split the async result into two paths, and only one of them handles the error - the other path (the `then` branch) will have an unhandled error which the zone captures for you.

Basically: Never use cascade notation with futures. Always use async/await when you can, it doesn't allow you to shoot yourself in the foot as easily as using raw futures.
