### ISSUE TITLE
Weird error around necessary and/or unnecessary cast

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26027]
This code tells me I have an unnecessary cast `as Map<String, String>`

```dart
void main() {
  List<String> o;
  var x = o.fold({}, (x, y) {
    x[y] = 'thing';
    return x;
  }) as Map<String, String>;
  _printInt(x);
}

void _printInt(Map<String, String> things) => print(things);
```

Removing the cast gives me

> ERROR: Unsound implicit cast from dynamic to Map<String, String> ([build] lib/build.dart:28)

on the call to `_printInt`

Dart VM version: 1.16.0-dev.1.0

**Comment by kevmoo** [comment]
Per https://github.com/dart-lang/sdk/issues/25490#issuecomment-195607283

**Comment by jmesserly** [comment]
Funny. I think inference gets enough info to figure it out from the "as" .... hmm, we probably shouldn't infer from an explicit cast? Or if we do, we shouldn't then turn around and tell you your cast was redundant :)

**Comment by jmesserly** [comment]
(btw, feel free to bump to "high" @leafpetersen @kevmoo if you think it makes sense. "medium" was my guess.)

**Comment by munificent** [comment]
I'm gonna take a crack at this.

**Comment by munificent** [comment]
Here's a slightly simpler repro:

```dart
void main() {
  var list = [] as List<String>;
  takeList(list);
}

void takeList(List<String> things) => null;
```

> we probably shouldn't infer from an explicit cast?

I think that's right. The fact that you are doing an explicit cast implies to me that the expression on the LHS may *not* be that type, so it seems weird to presume it is.

**Comment by bwilkerson** [comment]
I agree.

**Comment by jmesserly** [comment]
> I think that's right. The fact that you are doing an explicit cast implies to me that the expression on the LHS may not be that type, so it seems weird to presume it is.

yeah in this case though, it was possible to make it that type via inference. Inference fixed your code for you :)

Stylistically it certainly seems preferable to write `<String>[]` in this case. Any time inference can figure it out, you could've written that type explicitly. So perhaps we should suggest an auto-correct.

But I'm not a huge fan of just complaining to the user (or worse, letting the cast fail at runtime, which is harder to debug), when we could've easily figured out the types for them.

**Comment by jmesserly** [comment]
Chatted with Bob, we want to see if https://github.com/dart-lang/sdk/issues/25573 (no-implicit-dynamic) helps address the case I was concerned about above.
