### ISSUE TITLE
For `Optimize Imports` follow the style guide for the current project

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26020]
https://www.dartlang.org/effective-dart/style/#prefer-placing-third-party-package-imports-before-other-imports

Imports for my app should be last.

**Comment by greglittlefield-wf** [comment]
I'd love to see this implemented; would you accept a patch?

**Comment by Stargator** [comment]
@greglittlefield-wf I think that would help speed up the process.

**Comment by srawlins** [comment]
I suspect directives_ordering lints about this. https://dart.dev/guides/language/effective-dart/style#do-place-package-imports-before-relative-imports

But that doesn't speak to Optimize Imports.

**Comment by kevmoo** [comment]
It seems this effective dart rule has been dropped. I agree. Closing.
