### ISSUE TITLE
Add new repository mirrors

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26028]
We need repository mirrors for:
- [`boolean_selector`](/dart-lang/boolean_selector)
- [`stream_channel`](/dart-lang/stream_channel)
- [`typed_data`](/dart-lang/typed_data)
- [`web_socket_channel`](/dart-lang/web_socket_channel)

**Comment by athomas** [comment]
I don't know when this was done, but I can see all of them have mirrors on dart.googlesource.com.
