### ISSUE TITLE
Angular2 custom pipe class fails after dart2js

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#26038]
I have a custom Pipe class where I do a cast on the incoming args,

In the HTML file I did the following: foo |bar:baz where baz is the argument.

Now baz is actually a typedef => bool TypeDefName(someValue)

If I cast the incoming argument as following => arg[0] as TypeDefName, then I get an RTE in JS,
but it works fine in DartVM.

When I just cast as Function, it works in JS => arg[0] as Function

**Comment by sigmundch** [comment]
@frankpepermans - would you be able to provide a sample small program that reproduces the issue? A small piece of code that works without using angular would be best.

I've tried several cases that match what you describe, but I have not been able to reproduce it yet. For example, this program produces the same output in the vm and dart2js:

```dart
typedef bool Foo(x);

main() {
  test(f1);
  test(f2);
  test(f3);
  test(f4);
}

bool f1(y) => false;
bool f2() => false;
bool f3([y]) => false;
bool f4(z, [y]) => false;

int i = 1;
test(f) {
  try {
    f as Foo;
    print('$i: ok');
  } catch(e) {
    print('$i: fail');
  }
  i++;
}
```

**Comment by frankpepermans** [comment]
I've just tried without Angular 2 and it does work.

Might it be that the Angular 2 transformer is causing this?
What I saw as RTE was in the lines of 'could not find 'ListItem on null' whereas the original code in Dart is as following:

`typedef bool IsSelectedHandler(ListItem listItem);

@Pipe(name: 'selectedItems')
@Injectable()
class SelectedItemsPipe<T extends Comparable> implements PipeTransform {

  const SelectedItemsPipe();

  List<ListItem<T>> transform(List<ListItem<T>> dataProvider, [List<dynamic> args = null]) {
    final IsSelectedHandlerhandler = args.first as IsSelectedHandler;
    final bool moveSelectionOnTop = args.last as bool;

    if (!moveSelectionOnTop) return const [];

    return dataProvider.where((ListItem<T> listItem) => listItem != null && handler(listItem)).toList(growable: false);
  }
}`

**Comment by frankpepermans** [comment]
Swapping to Function made dart2js work again:

```
typedef bool IsSelectedHandler(ListItem listItem);

@Pipe(name: "selectedItems")
@Injectable()
class SelectedItemsPipe<T extends Comparable> implements PipeTransform {

  const SelectedItemsPipe();

  List<ListItem<T>> transform(List<ListItem<T>> dataProvider, [List<dynamic> args = null]) {
    final Function handler = args.first as Function;
    final bool moveSelectionOnTop = args.last as bool;

    if (!moveSelectionOnTop) return const [];

    return dataProvider.where((ListItem<T> listItem) => listItem != null && handler(listItem)).toList(growable: false);
  }
}
```

**Comment by sigmundch** [comment]
I wonder if angular wraps the function in some way before passing it down and does it in a way that makes the type inconsistent.

What does the definition of your argument look like?

If you print `args.first` and `args.first.runtimeType` what do you see?

**Comment by frankpepermans** [comment]
Added tracers =>

```
typedef bool IsSelectedHandler(ListItem listItem);

@Pipe(name: 'selectedItems')
@Injectable()
class SelectedItemsPipe<T extends Comparable> implements PipeTransform {

  const SelectedItemsPipe();

  List<ListItem<T>> transform(List<ListItem<T>> dataProvider, [List<dynamic> args = null]) {
    print('-- START --');
    print(args.first);
    print(args.first.runtimeType);
    print(IsSelectedHandler);
    print('-- END --');
    final Function handler = args.first as Function;
    final bool moveSelectionOnTop = args.last as bool;

    if (!moveSelectionOnTop) return const [];

    return dataProvider.where((ListItem<T> listItem) => listItem != null && handler(listItem)).toList(growable: false);
  }
}
```

This is what I get, first DartVM:

-- START --
Closure: (ListItem<T>) => bool from Function 'isSelected':.
(ListItem) => bool
IsSelectedHandler
-- END --

Now in Chrome

-- START --
Closure 'isSelected$1' of Instance of 'ListRenderer'
undefined
 IsSelectedHandler0
-- END --

**Comment by sigmundch** [comment]
I'm wondering what `ListRenderer`, `ListRenderer.isSelected` and your angular template look like.

Unfortunately I still haven't been able to repro. If your code is open source, please share with us a pointer to it so we can run it locally. If not, consider maybe creating a small angular app with a single template that shows this problem.

Thanks!
