### ISSUE TITLE
Quick Fix contains incorrect offsets in LinkedEditGroups

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26039]
_Originally reported in [WebStorm's issue tracker](https://youtrack.jetbrains.com/issue/WEB-20841)._
Consider this code:

```
import 'dart:html';

class Foo {
  foo() {
    Element e;
    bar = e.onClick.listen(listener);
  }

  void listener(MouseEvent event) {
  }
}
```

Analysis server reports an error `Undefined name 'bar'` and suggests a quick fix `Create field 'bar'`. Corresponding `SourceChange` has one `SourceFileEdit` with two `SourceEdits`:
- one `SourceEdit` inserts field declaration `StreamSubscription<MouseEvent> bar;`
- another one adds required import directive `import 'dart:async';`

Also this `SourceChange` contains two `LinkedEditGroups`:
- one suggests to stop at field type `StreamSubscription<MouseEvent>`
- another one stops at field name `bar`

**The problem** is that offsets in these `LinkedEditGroups` are calculated against file text that we get after applying only the first `SourceEdit`. And when IDE starts live template (`LinkedEditGroups`) after applying both - all ranges are shifted by `import 'dart:async';` text length and we get:
![image](https://cloud.githubusercontent.com/assets/4499789/13884248/3e1fd320-ed3e-11e5-8910-ba3c5f1185df.png)

**Comment by bwilkerson** [comment]
I believe that this has been fixed.
