### ISSUE TITLE
circular dependency for function _FutureListener.then

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26030]
Unexpected exception in service tests: ServerRpcException(Error in extension `ext..delay`: 'dart:async/future_impl.dart': error: line 82: circular dependency for function _FutureListener.then
Pending Functions:
0: _FutureListener.then

  _FutureListener.then(this.result,
                      ^
) #0      tests.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/developer_extension_test.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:914)
#3      _CustomZone.runBinary (dart:async/zone.dart:806)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:579)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:641)
#6      _Future._completeError (dart:async/future_impl.dart:432)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:488)
#8      _rootRun (dart:async/zone.dart:895)
#9      _CustomZone.run (dart:async/zone.dart:790)
#10     _CustomZone.runGuarded (dart:async/zone.dart:696)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by johnmccutchan** [comment]
@turnidge @mhausner

**Comment by johnmccutchan** [comment]
From Matthias:

I see that _FutureListener.then() uses the constant STATE_THEN_ONERROR which is initialized with an expression that is computed at compile-time, possibly when then() is compiled if it hasn't been referenced before. If the error is happening frequently, you could patch your tree and replace the initializer for  STATE_THEN_ONERROR like this:

static const int STATE_THEN_ONERROR = 3;

That should avoid the synthetic initializer function for the constant. The then() function can then be compiled without recursively compiling something else.

**Comment by johnmccutchan** [comment]
I'm attempting this here https://codereview.chromium.org/1811103002/

**Comment by iposva-google** [comment]
@mhausner What I would like to understand is why it is an issue if the compilation of _FutureListener.then() causes a recursive compilation of a compile-time constant.

**Comment by johnmccutchan** [comment]
@mhausner The work around did not work.

https://build.chromium.org/p/client.dart/builders/vm-mac-release-x64-be/builds/12370/steps/checked%20vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment]
I haven't seen this since adding many NoOOBScopes
