### ISSUE TITLE
Regression in c75a817 breaks pkg/test tests

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26031]
I did the bisect dance to find the commit - looks like its this c75a817

Repo

1. Get pkg/test: https://github.com/dart-lang/test
2. `pub get`
3. `pub run test -x browser test/runner/configuration/`

CC @zanderso @nex3

**Comment by kevmoo** [comment]
Output from test.

Seems that a weird path is generated? ...

```
00:03 +31 -76: test/runner/configuration/top_level_test.dart: command line args take precedence
  The schedule had 2 errors:
  ScheduleError:
  | ProcessException: No such file or directory
  |   Command: /Users/kevmoo/source/github/test.dart/p --packages=file:///Users/kevmoo/source/github/test.dart/.packages /Users/kevmoo/source/github/test.dart/bin/test.dart --package-root=/Users/kevmoo/source/github/test.dart/packages --concurrency=1 --timeout=none test.dart

  Stack chain:
  | dart:io                                                    Process.start
  | package:scheduled_test/scheduled_process.dart 158:24       ScheduledProcess._scheduleStartProcess.<fn>.<fn>
```

**Comment by kevmoo** [comment]
More fun:

It seems that `Platform.resolvedExecutable` is returning garbage. The same tests fail each time, but each run the value changes.

Some samples 

```
value, value.codeUnits
², [57377, 178, 1]
!à², [33, 224, 178]
à, [8, 224]
```

**Comment by zanderso** [comment]
A scoped allocated string is being cached in a global. I'll have a fix shortly.

**Comment by zanderso** [comment]
https://codereview.chromium.org/1813943004/

This should fix the problem, but I was unable to follow your repro instructions. 'pub get' fails after I clone the test package. Could you please either fix the instructions or post a small reproduction. Thanks!

**Comment by kevmoo** [comment]
edit the pubspec.yaml to have a version of `0.12.12`

Sorry – it's a difficult repo. I think it involves isolates?

**Comment by kevmoo** [comment]
Confirmed in ca924d09d14e54133c1d52c8da1aece6240cd5e6 with original repro – Thanks!
