### ISSUE TITLE
WebGL: RenderingContext.texImage2D issues in dev-channel

### ISSUE THREAD

**Issue by bp74** [dart-lang/sdk#26047]
Hi,

The dev-channel removed some methods from WebGL and i try to migrate my code to the new methods. Unfortunately there are some issues with this. See also ...

https://github.com/dart-lang/sdk/issues/25797#issuecomment-198554221
https://github.com/bp74/StageXL/pull/232

#### dart2js implementation 

texImage2D: 
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dart2js/web_gl_dart2js.dart#L2795

As the comment says, this method should only be used for compatibility reasons and it is recommended to use texImage2DTyped and texImage2DUntyped. The dart2js code also looks much nicer compared to the texImage2D method (see above).

texImage2DUntyped:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dart2js/web_gl_dart2js.dart#L3118

texImage2DTyped:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dart2js/web_gl_dart2js.dart#L3125

Using the texImage2DTyped and texImage2DUntyped method in my code works perfectly fine when compiled to JavaScript. The compiled code also looks beautiful without any overhead. But those methods fail to run in Dartium! 

#### Dartium implementation 

texImage2D: 
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dartium/web_gl_dartium.dart#L3362

texImage2DUntyped:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dartium/web_gl_dartium.dart#L3672
This method tries to call texImage2DImage, texImage2DImageData, texImage2DCanvas, texImage2DVideo which do not exist, right? Dartium does not crash but the textures are just black and you can't upload images. This is probably the main issue here!

texImage2DTyped:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dartium/web_gl_dartium.dart#L3692
This method tries to call texImage2D

#### Summary

I would prefer to call texImage2DTyped and texImage2DUntyped. The first one is used to create WebGL textures for a given size, the second one is used to uploade image, canvas or video elements.

**Comment by bp74** [comment]
Btw. both method names (texImage2DTyped and texImage2DUntyped) are very strange. Why is the first one typed and the second one untyped? Each method is used for a particular use case but my understanding is that it has nothing to do with typed or untyped. I get the point that the last parameter of texImage2DUntyped is untyped (image, canvas, video or imagedata) but it feels strange anyhow :)

**Comment by lexaknyazev** [comment]
The same ocurred with `bufferDataTyped`.

**Comment by bp74** [comment]
The situation with `bufferDataTyped` is a little bit different, at least in my use case. The method was removed but the `bufferData` method does the same thing and works fine for me. Maybe there are situation where `bufferData` has issues too. Anyway `bufferDataTyped` probably deserves to be deprecated at least for the next release (as @kevmoo said here: https://github.com/dart-lang/sdk/issues/25797#issuecomment-198554221)

**Comment by lexaknyazev** [comment]
My point is that in both (`texImage2D` & `bufferData`) cases there were strongly typed functions with explicit recommendation to use them instead of 'generic' js-compatible. What have changed so they're deprecated now? Anyway they were just aliases.

**Comment by kevmoo** [comment]
@terrylucas @jacob314 @alan-knight I'd like to *at least* keep this around, marked as deprecated for a few releases, if possible.

**Comment by alan-knight** [comment]
The comments are obsolete. Previously Dartium was calling directly into Chrome C++ and it made a difference if you were passing a typed array or not. Using "typed/untyped" to mean "TypedArray/SomethingElse" is rather confusing. But now we're calling JS, so it makes no difference.

The implementations of the image methods is hard-coded in a template, and needs fixing.

**Comment by lexaknyazev** [comment]
@alan-knight Will type-safe aliases be deprecated or just refactored for the next release?
`border_OR_canvas_OR_image_OR_pixels_OR_video` from `texImage2D` or `data_OR_size` from `bufferData` doesn't feel like Dart, imho.

**Comment by alan-knight** [comment]
It's not that they're type-safe, there was just a special version for typed arrays. data_OR_size and the like have been there all along. We're trying to be less in the business of rewriting DOM APIs to feel more like Dart, needing to keep up as they change, and making users' code less efficient.

It seems like these four are the main problem, so it seems manageable to just maintain them as (deprecated) forwarders and we're not going to have to do it for hundreds of changed methods.

**Comment by lexaknyazev** [comment]
Thanks. Now that change looks reasonable in the long-term perspective. 
Maybe #4938 will help to make such DOM APIs a bit less dynamic without manual rewriting.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1831033002/

**Comment by bp74** [comment]
I think there is still an issue with texImage2D (the method that should be used instead of the typed and untyped methods). The Dartium implementation is different than the dart2js implementation.

Dartium (Line 2774)

    if (pixels != null && type != null && format != null ...

dart2js (Line 3363)

    if ((pixels is TypedData || pixels == null) && (type is int) && (format is int) && 

The dart2js version looks correct because it allows the pixels parameter to be null. The Dartium version does not allow the pixels to be null, which is a valid value because you can call texImage2D with pixels=null if you just want to create a texture with a given width and height. This code should work:

    _renderingContext.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null);

**Comment by kevmoo** [comment]
@alan-knight thoughts on the comment from @bp74 ?

**Comment by bp74** [comment]
I think i mixed up the Dartium and dart2js code. 
The code is the other way around, but the issue is still the same.

**Comment by alan-knight** [comment]
Thanks, I'll take a look.

**Comment by kevmoo** [comment]
@alan-knight checked in ab55f22 which tried to help this – I think – but we're still crashing

The call from StageXL to bufferDataTyped (now deprecated) crashes with `RenderingContext` has no getter `targetTexture` on Pop, Pop, Win

**Comment by alan-knight** [comment]
Well that's embarassing. https://codereview.chromium.org/1846803002/

**Comment by alan-knight** [comment]
Landed

**Comment by bp74** [comment]
The change did fix some of the more obvious bugs, but not all. Please compare this two lines of code:

https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dart2js/web_gl_dart2js.dart#L2774
https://github.com/dart-lang/sdk/blob/master/sdk/lib/web_gl/dartium/web_gl_dartium.dart#L3071

In Dartium it is allowed to set the parameter `pixels` to null (which is a valid call to this method) but in dart2js you will get an exception. The call to `texImage2D` would look like this:

    _renderingContext.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null);

This is a use case where `border_OR_canvas_OR_image_OR_pixels_OR_video` isn't an ImageData, ImageElement, CanvasElement or VideoElement.

Btw. the same applies to `texsubimage2D`. Please reopen this issue.

**Comment by kevmoo** [comment]
Thanks, @bp74

**Comment by alan-knight** [comment]
It's tricky, because that code is generated based on the IDL. We could hard-coded it, but I hate to do that. I tracked down where it was diverging in the generation between Dartium and dart2js versions. @bp74  Can you patch in the following CL and see if it seems to be doing the right thing for you?

https://codereview.chromium.org/1885943002

**Comment by bp74** [comment]
I will try to do those tests asap!

**Comment by bp74** [comment]
I did some tests and the patch works great. It fixes all my errors.

**Comment by alan-knight** [comment]
OK, I've landed it and will see about getting it cherry-picked on Monday.
