### ISSUE TITLE
Analyzer:   Too many calls to NamespaceBuilder._createExportMapping

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26044]
Profiling analyzer on a large app reveals NamespaceBuilder._createExportMapping accounts for 35% of runtime.
Adding print statements reveals this is due to 5M calls.
This seems like too many for ~3k libraries.

**Comment by scheglov** [comment]
Just curious, do you run analyzer in strong mode?

**Comment by bwilkerson** [comment]
I discovered the cause earlier this morning: although we cache the export namespace of each library for efficiency, we fail to use the cached namespace when visiting AST structures (when computing a LibraryScope).

**Comment by scheglov** [comment]
https://codereview.chromium.org/1821543002

@pq FYI this makes Flutter analysis 20% faster.

**Comment by pq** [comment]
Woah!  Great catch!

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/97759f471cdb68ce1bb41360c429bc175b099d0b
