### ISSUE TITLE
Document what's changed in dart:html/webgl/etc with 1.16

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26045]
There are a lot of changes due to changed IDL. We should produce at least some sort of listing for people. @kevmoo @jacob314 @terrylucas

**Comment by mit-mit** [comment]
1.16 is about to ship, please get this quickly!

**Comment by kevmoo** [comment]
Closed as dupe of https://github.com/dart-lang/sdk/issues/25970
