### ISSUE TITLE
vm: LinkedHashMap creation is slow

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26046]
I was experimenting with switching dartanalyzer to use LinkedHashMap in place of HashMap.  The new compact implementation should save space. The switch over did save a little bit of space, but the performance was degraded enough to abandon the idea. A lot of time was spent in `_InternalLinkedHashMap._InternalLinkedHashMap` (nearly 10% if I recall).

Also, profiling dart2js shows `_InternalLinkedHashMap._InternalLinkedHashMap` takes about 3% of overall time, even though many small maps are implemented via the list-backed mode of utils/maplet.dart

The following program shows the impact of the slow allocation.
Maps are twice as slow as HashMaps, where Sets are not very different from HashSets.

The new compact LinkedHashSets would be very nice if the allocation performance could be improved. I'm not sure why there is no Dart implementation of the constructor. If it is necessary that hash maps need to be generated in C code, perhaps an instrinsifier can be written.

```
for m in HashMap Map HashSet Set ; do sdk/bin/dart hashmap2.dart $m ; done
HashMap 2.634
Map 5.944
HashSet 2.355
Set 2.565
```
---
hashmap2.dart
```
import 'dart:collection';

var a, b, c;

class M {
  from(other);
  fromIterables(keys, values);
}

class M1 extends M {
  from(Map other) => new Map.from(other);
  fromIterables(keys, values) => new Map.fromIterables(keys, values);
}

class M2 extends M {
  from(Map other) => new HashMap.from(other);
  fromIterables(keys, values) => new HashMap.fromIterables(keys, values);
}

class M3 extends M {
  from(Map other) => new LinkedHashMap.from(other);
  fromIterables(keys, values) => new LinkedHashMap.fromIterables(keys, values);
}
  

class S1 extends M {
  from(other) => new Set.from(other);
  fromIterables(keys, values) => new Set.from(keys);
}

class S2 extends M {
  from(other) => new HashSet.from(other);
  fromIterables(keys, values) => new HashSet.from(keys);
}
  

work(M m) {
  for (int i = 0; i < 10000000; i++) {
    c = m.from(a);
    c.addAll(b);
  }
}

main(List<String> argv) {
  var methods = {
    'Map': new M1(),
    'HashMap': new M2(),
    'LinkedHashMap': new M3(),
    'Set': new S1(),
    'HashSet': new S2()
  };

  var m = methods[argv.single];
  a = m.fromIterables(['abc', 'bcd', 'cde'], ['bcd', 'cde', 'def']);
  b = m.fromIterables(['xxx', 'yyy', 'zzz'], ['bcd', 'cde', 'def']);

  var sw = new Stopwatch()..start();
  work(m);
  print('${argv.single} ${sw.elapsedMilliseconds / 1000}');
}
```

**Comment by fsc8000** [comment]
These are the number with my CL:
```
HashMap 2.512
Map 3.631
HashSet 2.348
Set 1.991
```

The remaining difference is not due to allocation, but rather the  different implementations of ```forEach```.

**Comment by fsc8000** [comment]
The 3% speedup on dart2js compile times seems in line with your observation of time spent in ```_InternalLinkedHashMap._InternalLinkedHashMap```
