### ISSUE TITLE
Dartium snaps when used with WebStorm livereload plugin

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26048]
As soon as I change the HTML in WebStorm Dartium snaps.
This is a simple WebStorm project without any Dart code and not even a `pubspec.yaml`
Just a directory `example1` with `index.html` and `index.css`

**Comment by zoechi** [comment]
> Chromium	45.0.2454.104 (Developer Build) (64-bit)
Revision	b16942297fc65fd478c6f46afd1c3aaecde77009
OS	Linux 
Blink	537.36 (@abaaf1d0b6b6483140b5dca34e80fc259833ddf7)

**Comment by alan-knight** [comment]
Do you mean the LiveEdit plugin? That says it's only supported in Chrome, and I suspect that it requires a more recent version of Chrome than Dartium is currently at.

**Comment by zoechi** [comment]
Right "LiveEdit". I haven't seen that information about the Chrome version. If it is not supposed to work then the issue can be closed. I just thought it should not snap.

**Comment by alexander-doroshko** [comment]
Request to support LiveEdit in Dartium was closed without a fix (#6035), it is not supported and not planned.

**Comment by zoechi** [comment]
Just to clarify: Actually this was not a request to support LiveEdit. I just tried it and it with Dartium and it made Dartium snap. That is what I think shouldn't happen. 
If you don't plan to do anything about it just ignore my comment. 
I guess Dartium will be updated to a newer Chrome version eventually anyway.

**Comment by alexander-doroshko** [comment]
Ok, let Dart team decide what to do with Dartium crash.

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
