### ISSUE TITLE
Observatory: Allow UI to change cpu profile tag order without re-fetching data

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26043]

**Comment by johnmccutchan** [comment]
@B3rn475 I believe this is part of your cpu-profile CL right?

**Comment by johnmccutchan** [comment]
@B3rn475 In your CL description you can write:

```Fixes https://github.com/dart-lang/sdk/issues/26043```

And this bug will automatically be closed when you commit

**Comment by B3rn475** [comment]
Updated CL description
