### ISSUE TITLE
Analyzer: high fraction of time in 	PackageUriResolver.resolveAbsolute

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26055]
When running analyzer on a large app with 3330 packages, I see that 
13% of the time is spent in `PackageUriResolver.resolveAbsolute`.
Half of that time is in `JavaFile.getAbsolutePath` which seems to be inefficient at string level, but I can't help wondering if the real problem is that `PackageUriResolver.resolveAbsolute` is called too many times.

I believe @munificent noticed the same.

**Comment by rakudrama** [comment]
https://codereview.chromium.org/1817423002 avoids some of the computations.
There are still many more calls than expected, but this helps.

**Comment by devoncarew** [comment]
We've profiled several times since this issue was filed, so I assume we now longer see these hot spots.
