### ISSUE TITLE
Analyzer error message leaves off method name

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26056]
I'm seeing lots of error messages like the following when I run in strong mode:

```
[error] The return type 'String' is not a 'int', as defined by the method ''. (/Users/leafp/tmp/error.dart, line 6, col 28)
1 error found.
```

Note that there is no name printed for the method.  I'm not sure if this is a strong mode only issue or not.  See below for reproduction case (strong mode only):

``` dart
class A {
  void test (int f()) {}
}

void main() {
  new A().test(() { return "hello"; });
}
```

**Comment by eernstg** [comment]
In the case where the relevant expression for a static type warning is a lambda it makes sense that no name can be printed, but some of them are so short that it would be reasonable to print the whole lambda (and for longer ones there could be an ellipsis, e.g., `(T x) { print("Hello, world); ... })`. I don't know about you, but I'll only look up 'line 6, col 28' if there's no other strategy at hand. ;-)

**Comment by zoechi** [comment]
Line, col is fine for me when the IDE provides a link from the error message to the source location. 
Enough context in the error message is important as well. People post code snippets into chat apps or StackOverflow and there is no way of telling what line in no 6 is.

**Comment by leafpetersen** [comment]
I found the text `by the method ''` to be very confusing.  Saying something like `in anonymous closure` would make it clear what's happening.  This probably arises because in spec mode there is no way to get an invalid return type for an anonymous closure, but strong mode inference makes it possible.

**Comment by bwilkerson** [comment]
Yes, we should add a code for closures.
