### ISSUE TITLE
"A Tour Of The Dart Language" refers to "%" as "the multiplicative operator"

### ISSUE THREAD

**Issue by cmza** [dart-lang/sdk#26052]
At least twice, I read "the multiplicative operator %"...surely that should be "the modulo operator"?

**Comment by eernstg** [comment]
There are several multiplicative operators (Section 16.28 in the spec v1.11 lists them: `*`, `/`, `%`, `~/`). What this says is essentially "the operator % (which is by the way one of the multiplicative operators)..", and the main purpose would be to indicate how it fits into the grammar, e.g., with respect to precedence. So it's not so much of a contradiction as it sounds at first. ;-)

**Comment by cmza** [comment]
Ah..  If I read it as [one of] the multiplicative operator[s], that does
indeed make sense.  Thanks for the learning moment! :-)

**Comment by eernstg** [comment]
Thanks for being proactive!
