### ISSUE TITLE
An integer literal with exponent (e.g. 1e8) is a double

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#26053]
Consider this code:

```
void main() {
  var count = 1e8;
  doSomething(count);
}

void doSomething(int count) {
  print(count);
}
```
https://dartpad.dartlang.org/59e0e9cd1828c2a2b167

This shows the following hint (and throws in checked mode):

> The argument type 'double' cannot be assigned to the parameter type 'int'

According to [specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) (at least how I read it), `count` should be an integer in this instance. Snip from page 53 (emphasis mine):

> If a numeric literal begins with the prefix ‘0x’ or ‘0X’, it denotes the hexadecimal integer represented by the part of the literal following ‘0x’ (respectively ‘0X’). Otherwise, **if the numeric literal does not include a decimal point it denotes a decimal integer.** Otherwise, the numeric literal denotes a 64 bit double precision floating point number as specified by the IEEE 754 standard.

**Comment by mezoni** [comment]
Page 52

16.3 Numbers
A numeric literal is either a decimal or hexadecimal integer of arbitrary
size, or a decimal double.

Decimal integer number cannot contain character `e` as in you case (1e8).
But decimal double number can contain `e` for denoting exponent.

**Comment by filiph** [comment]
> Decimal integer number cannot contain character e as in you case (1e8).

Why? Hexadecimals have to start with `0x` so there's no way to confuse `1e8` for hexadecimals.

> > A numeric literal is either a decimal or hexadecimal integer of arbitrary size, or a decimal double.

IMHO, this doesn't say anything about the issue (it doesn't prohibit integers from being written with exponents).

I don't feel strongly about this, and I understand the issue with `1e-4` (automatically a double). It's just that I want to use a big integer constant and the only other way to write it is `100000000`, which isn't very readable (is it 1 million? 10 million? 100 million? 1 billion?).

**Comment by mezoni** [comment]
>> Why? Hexadecimals have to start with 0x so there's no way to confuse 1e8 for hexadecimals

This is not the same. In your example number does not start with `0x`.
Why need to wrote this argument here if in your example (issue) was used `1e8` but not  `0x1e8`?

**Comment by lrhn** [comment]
Dart follows most other languages in that exponential notation numerals represents double values.
It's just simpler. You also avoid having to argue whether 1.2e5 is an int (it's an integer double value, not an int).
What some other languages have is a way to express integers in exponential notation, for example `1p8` (1 * 10**8) or `0x1p8` (1 * 16 ** 8). We should consider that for Dart as well.
Another alternative is to allow delimiters in number literals, like in Java: `100_000_000` is more readable than `100000000`.

**Comment by filiph** [comment]
Thanks for clarification. I didn't think about `1.2e5`. Fixing the spec makes sense.

I agree that delimiters in number literals would be a much better solution to my particular problem. I think I saw a bug for that somewhere, I'll subscribe to it.
