### ISSUE TITLE
Importing nonexistant files in dart doesn't correspond to spec.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#26061]
According to Dart Language specification (4th edition, Dec 2015) "18.1 Imports":

"It is a compile-time error if the specified URI of an immediate import does not refer to a library declaration. The interpretation of URIs is described in section 18.5 below.
It is a static warning if the specified URI of a deferred import does not refer to a library declaration."

However, dart compiles test below, and unhandled exception occurs in runtime. Note, dartanalyzer
reports an error.

``` dart
import "nonexistant_file.dart";
main() {
  var someVar = 0;
}
```

Second test is successfully compiled with dart, while dartanalyzer reports error instead of warning.

``` dart
import "nonexistant_file.dart" deferred as p;
main() {
  var someVar = 0;
}
```

Tested with Dart VM version: 1.16.0-dev.1.0 (Wed Mar 16 09:25:56 2016) on "linux_x64".

**Comment by zoechi** [comment]
Dart compiles at runtime (VM, not dart2js), just before it executes the code the first time, therefore I guess an unhandled exception is the appropriate response.
I'm sure we'll get a more accurate explanation of one of the Dart team members.

**Comment by bkonyi** [comment]
This appears to have been fixed (the second example now causes a compile-time error).
