### ISSUE TITLE
add case insensitive to search.findTopLevelDeclarations

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26064]
For the search domain, it would be nice if the `findTopLevelDeclarations` call had an optional case insensitive argument. The current (required) param is just `String pattern`.

**Comment by lrhn** [comment]
A more general solution would be to pass a `Pattern` or a match function, but that's hard to do in a remote call. Allowing a RegExp is another possibility.

**Comment by devoncarew** [comment]
It takes a regex currently; I'd like to pass through a flag to the `caseSensitive` param of the regex constructor.

**Comment by devoncarew** [comment]
not planned
