### ISSUE TITLE
analyzer does not detect invalid usage of ??= operator when a getter is not present

### ISSUE THREAD

**Issue by johnryan-wf** [dart-lang/sdk#26068]
If a class has a setter, but no getter, dartanalyzer does not print a warning when the `??=` is used:

``` dart
class Foo {
  set bar(int x){}
}

main() { 
  var f = new Foo();
  f.bar ??= 100; // should display a warning
}
```

dartpad link: [dartpad.dartlang.org/?source=7cd388ba-5eeb-4612-8593-e454afd8029b](https://dartpad.dartlang.org/?source=7cd388ba-5eeb-4612-8593-e454afd8029b)

**Comment by srawlins** [comment]
This has been fixed:

```none
Analyzing 26068.dart...
  error • The getter 'bar' isn't defined for the type 'Foo'. • 26068.dart:7:5 • undefined_getter
```
