### ISSUE TITLE
Strong mode generic methods not being recognized in analysis server

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26062]
The program below produces no analyzer errors with 1.16.0-dev.1.0 in both server and command line mode.

In 1.16.0-edge.a48732a03daae87455ce6a70d589b7fd3d06e730 I still see no errors in command line mode, but in server mode (via intellij) I see warnings and errors suggesting that the text of the program is being analyzed in strong mode, but against a non-strong mode SDK.

```dart
Map<String, int> _icons;

List<String> get iconNames {
  final String iconSetPrefix = "hello";
  return _icons.keys.map/*<String>*/((String id) => '$iconSetPrefix$id').toList();
}
```

cc @bwilkerson @zoechi

**Comment by skybrian** [comment]
An example I just ran into:

```
List makeTuple(int x) => [x, x.toString()];

main() {
  List<int> items = [1, 2, 3];
  Iterable<List> mapped = items.map(makeTuple);
  List<List> tuples = mapped.toList();
  print(tuples);
}
```

The error I see is:
`Unsound implicit cast from Iterable<dynamic> to Iterable<List<dynamic>> - map_test.dart, line 5`

**Comment by leafpetersen** [comment]
I'm trying to bisect this in the background while I work on other things, hopefully will be able to point to a commit soon.

**Comment by skybrian** [comment]
I worked around it by writing a for loop.

**Comment by leafpetersen** [comment]
@scheglov has diagnosed the issue.

**Comment by leafpetersen** [comment]
@devoncarew this may affect Atom as well.

**Comment by scheglov** [comment]
Using Dart SDK summary, which was causing the problem, was disabled.
https://github.com/dart-lang/sdk/commit/08989ce327510eaf63a2609509f3e7052563f07b

We're working on making a change to make using SDK summary compatible with the strong mode.

**Comment by scheglov** [comment]
I think choosing correct spec/strong SDK summary was fixed.
https://github.com/dart-lang/sdk/commit/c675ba270f144e5055d70bd41612f67decfb7540
