### ISSUE TITLE
checked mode error on fully typed code that static analysis is ok with

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26067]
The following code:

```dart
void main() {
  List<int> a = <int>[1, 3, 3];
  List<int> b = a.map/*<int>*/((int x) => x * 10);
  print('$b');
}
```

...has no static analysis errors, and runs fine in release mode.

In checked mode, however, it throws:
```
Unhandled exception:
type 'MappedListIterable' is not a subtype of type 'List<int>' of 'b'.
#0      main (test.dart:3:19)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

I don't understand why it doesn't have a static analysis error.

**Comment by bwilkerson** [comment]
I would expect an analysis error if strong mode is enabled, but not if it isn't. How are you running analysis?

The checked mode error appears to be because `MappedListIterable` and `List` are not related to each other. But static analysis has no way to know that the run-time type of `map` isn't `Iterable`.

**Comment by leafpetersen** [comment]
We still allow implicit downcasts in strong mode.  So we won't warn here.  We have discussed adding a flag to disallow implicit downcasts.  This would likely introduce a large number of warnings to most existing code bases though, and so we haven't prioritized it.

**Comment by Hixie** [comment]
What's the relationship between `MappedListIterable` and `List<int>`?

**Comment by bwilkerson** [comment]
`MappedListIterable` extends `ListIterable`, which extends `Iterable`. `List` implements `Iterable`. So nothing direct.

**Comment by Hixie** [comment]
Oh, I see, the problem is that map() is declared to return an Iterable, not a MappedIterable. I understand your earlier comment now.

**Comment by Hixie** [comment]
Yeah I don't know how we could catch this short of tracking the types through control-flow analysis.

**Comment by bwilkerson** [comment]
Feel free to re-open this if you think we should try to fix it.

**Comment by Hixie** [comment]
If we're ok with map() never being able to return an actual List, and always returning something like MappedListIterable, one solution might be to have a subclass of Iterable like MappedIterableBase or something, that all the MappedListIterable, MappedIterable, etc, classes that map() can return extend. Then, declare map() as returning one of these MappedIterableBase classes instead of any Iterable. Should be backwards compatible, but would catch anyone doing this mistake.

This is basically the one place where Dart's type narrowing semantics catch me out, but I do it so often it's quite annoying. :-)
