### ISSUE TITLE
Observatory: <unknown dart function> 8% of profile

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26066]
I'm running dartanalyzer on an app with ~3000 libraries.
<unknown dart function> is 8% of the samples under "Dart"

16.22% [Stub] MegamorphicLookup
8.08% <unknown Dart function>
3.31% [Stub] Subtype1TestCache
2.77%[Stub] OneArgCheckInlineCache

More than 1% of <unknown Dart function> makes it hard to be confident in the profile.

**Comment by johnmccutchan** [comment]
<unknown dart function> is GC'd code.
