### ISSUE TITLE
Lint for "await" with something that isn't a Future

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26065]
e.g.:
```dart
main() async {
  print(await 23);
}
```

**Comment by eseidelGoogle** [comment]
@pq may know of an error we could turn on.

**Comment by bwilkerson** [comment]
According to the specification:

> Evaluation of an await expression a of the form _**await** e_ proceeds as follows:
>
> First, the expression _e_ is evaluated. Next:
>
> If _e_ raises an exception _x_, then an instance _f_ of class Future is allocated and later completed with _x_. **Otherwise, if _e_ evaluates to an object _o_ that is not an instance of _Future_, then let _f_ be the result of calling _Future.value()_ with _o_ as its argument**; otherwise let _f_ be the result of evaluating _e_.
>
> ...
>
> **It is not a static warning if the type of e is not a subtype of Future.** Tools may choose to give a hint in such cases.

Sounds like you'd like a lint rule.

**Comment by Hixie** [comment]
Yeah I don't really mind what the runtime behavior is. I just want to catch cases where we have extraneous "await"s that don't do anything useful.

**Comment by alexeieleusis** [comment]
Sent https://codereview.chromium.org/1886173004

**Comment by pq** [comment]
@Hixie : thanks to @alexeieleusis, we've got a new `await_only_future` lint to try when we pull the next dev build. 👍

**Comment by Hixie** [comment]
Nice!

**Comment by zoechi** [comment]
The analyzer tells me

> WARNING: 'await_only_future' is not a recognized lint rule ([bwu_datagrid] .analysis_options:15)

Dart VM version: 1.17.0-edge.79e4792dd609ef2bb1f66588a912e420bc058709 (Fri May 27 15:42:45 2016) on "linux_x64"

**Comment by alexeieleusis** [comment]
The name was changed to await_only_futures https://github.com/dart-lang/linter/commit/ecfaed3ea52ea2b5a7d9e0a7db94cf1f92208280 https://github.com/dart-lang/linter/blob/master/lib/src/rules/await_only_futures.dart

**Comment by zoechi** [comment]
@alexeieleusis oh, thanks! I checked with http://dart-lang.github.io/linter/lints/ but missed that additional `s`

**Comment by pq** [comment]
Sorry for the confusion @zoechi !  That name change was unfortunate but I think ultimately is more consistent with the other lints.

**Comment by zoechi** [comment]
@pq Nothing to worry. I got an ultra-fast response anyway :)
