### ISSUE TITLE
the search.findTopLevelDeclarations call doesn't return results for package code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26063]
The search domain's `findTopLevelDeclarations` call returns results for user code but not for code that lives in referenced packages. Concretely for Atom, this means that you can find a type declaration like `HelloWorldFlutter`, but not like Flutter's `StatefulWidget` class.

@scheglov

**Comment by devoncarew** [comment]
(This is for implementing a find type dialog)

**Comment by scheglov** [comment]
https://codereview.chromium.org/1829463002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/5e4218b7545aa8a0c0e8326771c27363d21fc8b0

**Comment by devoncarew** [comment]
Thanks!
