### ISSUE TITLE
Analyzer: 7% of time in NamespaceBuilder.createImportNamespaceForDirective

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26069]
On a large app that has 3000 libraries that import mostly with a prefix, 7% of the time is spent in NamespaceBuilder.createImportNamespaceForDirective, most in NamespaceBuilder._applyPrefix.

```
      definedNames.forEach((String name, Element element) {
        newNames["$prefix.$name"] = element;
      });
```

@bwilkerson 
It seems like there is an opportunity here to represent the Namespace as a more structured map where the prefix string maps to an interior map of the names, so the iteration over the names is deferred.
The same library imported in N places could be represented as a N Prefix nodes rather than N copies of the scope.
I see that SyntheticIdentifiers are used to lookup the 'prefix.name'-style names. This would be a two-stage lookup.

@leafpetersen
**--strong** makes things worse, NamespaceBuilder.createImportNamespaceForDirective accounting for **13%** of run time. Almost twice as many LibraryScope objects are created. It seems that library scopes should reused across tasks or be cached.  

without **--strong**,  ResolutionContextBuilder.contextFor (which eventually calls this code) is called by:

	100%   PropagateVariableTypeTask.internalPerform

with **--strong**,  ResolutionContextBuilder.contextFor is called by:

	66.76% InferStaticVariableTypeTask.internalPerform
	32.24% PropagateVariableTypeTask.internalPerform

The 2/3 - 1/3 split indicates that InferStaticVariableTypeTask might be doing the work _twice_.

**Comment by leafpetersen** [comment]
Both of these tasks visit all of the individual top level variable declarations and static fields one at a time, and each time they presumably build up a name scope.  Presumably all of the name contexts for a given library should be the same for all of the top level variables, but maybe not for the class statics?  We do inference at a library cycle granularity though, so we would at least have to have the name scopes for all of the libraries in the cycle.

I'm not sure why InferStaticVariableTypeTask does it twice as often - worth looking into.

**Comment by bwilkerson** [comment]
Were these measurements taken before or after https://codereview.chromium.org/1821543002/?

> It seems like there is an opportunity here to represent the Namespace as a more structured map where the prefix string maps to an interior map of the names, so the iteration over the names is deferred.

I like the general idea; it's always good to not do unnecessary work. I seem to remember, though, that there was previously a bug because we were not correctly concatenating the names and treating them like a single identifier in lookup. I don't remember the details, but there ought to be a unit test for that case.

**Comment by scheglov** [comment]
Should we also cache import namespaces as we cache export namespaces now?
https://github.com/dart-lang/sdk/commit/97759f471cdb68ce1bb41360c429bc175b099d0b

**Comment by bwilkerson** [comment]
I tried that (happy to share the code), but didn't see any difference in overall time. Not sure why.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1916223004/
