### ISSUE TITLE
Broken type inference - (list ?? anotherList) should be inferred as iterable

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#26079]
`(list ?? anotherList)` is inferred as EfficientLength which is not iterable so the following snippet results in an analyzer warning:

```dart
for(var _ in (list ?? anotherList));
```

as does

```dart
var newList = list ?? anotherList;
for(var _ in newList);
```

but the analyzer can be appeased by

```dart
List newList = list ?? anotherList;
for(var _ in newList);
```

Ideally all 3 of these cases should work with no warnings.

**Comment by bwilkerson** [comment]
Yep. That's the result of the way least-upper-bound is defined in the specification. Strong mode has a slightly different definition that tends to do what you want.

**Comment by natebosch** [comment]
For the record: this behavior exists running in strong mode as well.

**Comment by jmesserly** [comment]
Yup, we want to fix this in strong mode! Thanks for the report.
Merging this into https://github.com/dart-lang/sdk/issues/25821
