### ISSUE TITLE
Timer inside an Isolate halts when the tab becomes inactive in Dartium

### ISSUE THREAD

**Issue by rillomas** [dart-lang/sdk#26070]
I was trying to do [this method](http://stackoverflow.com/a/12522580/2432759) in a Polymer web app using isolates to send a heartbeat even while the tab is inactive, but this seemed to be not working in Dartium. I translated the code to JavaScript using `pub build` and that was working OK in Chrome.

I made a small app to reproduce this problem.

https://github.com/rillomas/isolate_sample
# Steps to reproduce
1. Get code from https://github.com/rillomas/isolate_sample
2. Run `pub get`
3. Run `pub serve`
4. Access `localhost:8080` with Dartium
5. Open developer console and confirm the ticking log like `[INFO] : tick at 2016-03-23 11:22:55.251241`
6. Create a new tab in Dartium and switch to that tab (Keep the two tabs attached in a single window)
7. The ticking log will not appear anymore

It will work as intended if you translate the code to JavaScript by the following steps:
1. Get code from https://github.com/rillomas/isolate_sample
2. Run `pub get`
3. Run `pub build`
4. move to `build` directory and start a  web server there. I used `python -m SimpleHTTPServer`.
5. Access `localhost:8000/web/index.html` with Chrome
6. Open developer console and confirm the ticking log like `[INFO] : tick at 2016-03-23 11:22:55.251241`
7. Create a new tab in Chrome and switch to that tab (Keep the two tabs attached in a single window)
8. The ticking log will keep appearing
# Environment

OS: Windows 7 x64
Dart SDK/Dartium: 1.15.0
Chrome (used for testing `pub build`): 49.0.2623.87 m (64-bit)

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
