### ISSUE TITLE
noSuchMethod not needed anymore for Mock classes

### ISSUE THREAD

**Issue by enyo** [dart-lang/sdk#26074]
Previously there was an analyzer warning when writing Mock classes like this (with `mockito` or `mock`):

```dart
class MockRequestContext extends Mock implements RequestContext {}
```

It would warn about unimplemented member variables and methods. So it was necessary to add a `noSuchMethod` function.

In recent versions of dart, this is not necessary anymore.

Is this a bug or a feature?

**Comment by lrhn** [comment]
I believe it's a bug-fix.
The specification requires a warning if a class doesn't implement its interface, unless the class overrides the `noSuchMethod` inherited from `Object`.

The analyzer was previously giving warnings unless the class itself declared a `noSuchMethod`, whether or not it inherited one from a superclass (other than `Object). That was incorrect.

(I don't know if the spec changed on this at some point.)

**Comment by enyo** [comment]
Ah Ok @lrhn , so if any of my superclasses (except `Object`) implements `noSuchMethod` then there is no warning? Makes sense. I'm closing this then.
