### ISSUE TITLE
Strong mode does not accept contravariant override when argument is dynamic

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#26077]
I'm seeing this strong-mode error in `charted`:
```
[error] Invalid override. The type of TimeScale.scale ((dynamic) → num) is not a subtype of LinearScale.scale ((num) → num). (/usr/local/google/home/het/Code/charted/lib/core/scales/time_scale.dart, line 70, col 3)
```

Here are the relevant lines:
* https://github.com/google/charted/blob/master/lib/core/scales/time_scale.dart#L70
* https://github.com/google/charted/blob/master/lib/core/scales/linear_scale.dart#L129

**Comment by leafpetersen** [comment]
Can you work around it for now by using Object in the subclass instead of dynamic?

**Comment by hterkelsen** [comment]
Yes, that resolved the error.

**Comment by bwilkerson** [comment]
@leafpetersen Are we intending to address this at some point, or should we close it?

**Comment by leafpetersen** [comment]
Opened a more general bug to track this here:

https://github.com/dart-lang/sdk/issues/26151

**Comment by leafpetersen** [comment]
This is fixed now.
