### ISSUE TITLE
Dartium / Chromium crashes if inspecting + hovering over img src

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#26089]
Inspecting `<img id="dynimage" src="assets/images/dog.png" width="300">` crashes the whole thing.

Check out this video.
[dartium-crash-image.mp4.zip](https://github.com/dart-lang/sdk/files/189368/dartium-crash-image.mp4.zip)

SS after crash
![screenshot-1987](https://cloud.githubusercontent.com/assets/116654/14042730/fd2de8b8-f27c-11e5-8579-430495b24526.png)

Dartium: Version 45.0.2454.0
IntelliJ IDEA (Minerva) IU-145.596.7
Build #IU-145.596, built on March 24, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac: 10.9.5

**Comment by MikeMitterer** [comment]
OK - Today I got a "Unexpected exception"...
![screenshot-1993](https://cloud.githubusercontent.com/assets/116654/14141605/73a77426-f680-11e5-9fbc-698e86d6fe50.png)

**Comment by alan-knight** [comment]
That would be an observatory issue and should probably be filed as a separate bug.

**Comment by MikeMitterer** [comment]
However - it's very annoying. I have to kill and restart Dartium every 5th or 6th reload.

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable (Dartium 50).
