### ISSUE TITLE
autocomplete for import path ends up with .dart.dart

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26083]
It's pretty common to change an import:
```dart
import 'path/to/foo_some_long_name.dart';
```

if I double click foo and start typing, I will get a new autocompletion (awesome!) however once I select it I end up with invalid code:
```dart
import 'path/to/bar.dart.dart'; // OOPS
```

Autocomplete should understand it needs to replace the full path string to the end, not stop at just what I have selected.

Minor issue, but over time it adds up since it happens every single time you edit an import using autocompletion.

(this is in IntelliJ/WebStorm, FWIW)

**Comment by alexander-doroshko** [comment]
@jmesserly, @zoechi Inserting completion variant is handled by the IDE.

Speaking of IntelliJ IDEA / WebStorm - there are 2 ways of choosing completion item from the list: `Enter` and `Tab`:
- `Enter` inserts completion variant 'as is', without deleting 'tail' text (to the right from the caret)
- `Tab` replaces tail text with completion item (provided that caret is inside of a word)

(Strictly speaking some other special keys like Space or Comma also do insert completion variant and insert Space or Comma after it correspondingly. You may think that it works like `Enter`, not like `Tab`.)

I think this issue can be closed.

**Comment by jmesserly** [comment]
Good to know there is one key that will trigger the right behavior, although I'm not sure how it is a good state that most keys cause the wrong behavior, or how folks are supposed to discover it. I appreciate your reply though, I'll know now to use "tab" and not any other ways of triggering completion.

**Comment by jmesserly** [comment]
I guess if there's nothing we can do from the Dart side, it makes sense to close.

**Comment by danrubel** [comment]
On the Dart side, code completion has always returned the replacement length which includes the entire URI up to but not including the closing quote. I just added tests to assert this... https://codereview.chromium.org/1843513003/

**Comment by bwilkerson** [comment]
@jwren Do you want to add an IntelliJ issue for this?
