### ISSUE TITLE
Type propagation/inference not symmetric for ?:

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26086]
This program generates an error on line 2, but not line 1:

``` dart
class A {}
class B extends A {
  b() {}
}

main() {
  A a = new B();
  a is B ? a.b() : null; // 1
  a is! B ? null : a.b(); // 2
}
```

I would expect them to both be valid.

**Comment by lrhn** [comment]
You say "error", but it should only be a warning on line 2, and it's required by the specification.

The type promotion is only defined for positive tests by the current specification. That means that the static type of `a` is `A` in all of line 2.

**Comment by munificent** [comment]
> You say "error", but it should only be a warning on line 2, and it's required by the specification.

In strong mode, where I noticed this, type warnings are promoted to errors. But, yes, this is reported as a warning when strong mode is not enabled.

> The type promotion is only defined for positive tests by the current specification.

Should I reassign to area-language?

**Comment by lrhn** [comment]
By all means request a better type promotion specification. I can't find an open feature request for it, but there might be one already that I couldn't find.

Or request that the analyzer can be allowed to not show warnings that it knows are spurious.

**Comment by leafpetersen** [comment]
@munificent This is covered by the proposal that you and @bwilkerson are working, correct?

**Comment by munificent** [comment]
Yes. Duplicate of #29624.
