### ISSUE TITLE
order of quick fixes for unresolved class name

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26082]
I'm writing a file like:
```dart
import 'package:analyzer/analyzer.dart' show CompilationUnit, parseDirectives;
...
someMethod() {
  AnalysisErrorListener a;
}
```
When I select quick fix for "AnalysisErrorListener", I am offered three options in this order:
* Create class 'AnalysisErrorListener'
* Import library 'package:analyzer/src/generated/error.dart'
* Update library 'analyzer.dart' import

Ideally they would be in the opposite order. Updating an import if using "show" is a very common operation. Adding an import is next best. Creating a class, when it already exists in an import, is my last choice. I appreciate that the option is offered, but imports should take priority, especially if I'm already using that package.

(Actually the particular case was even more obvious -- I was passing an AnalysisErrorListener.NULL_LISTENER to a parameter of type AnalysisErrorListener ...)

(p.s. apologies if I triaged wrong, not sure what area quick fixes are under)

**Comment by zoechi** [comment]
Similar to #26050

**Comment by alexander-doroshko** [comment]
@jmesserly I guess you are using IntelliJ IDEA or WebStorm, right? Actually it was a bug in these IDEs. Order of quick fixes provided by the Analysis Server is exactly as you expect, but IDEs used to sort them alphabetically. This is fixed now and you'll get the fix in few days with the new IDE update.

**Comment by jmesserly** [comment]
Oh nice!!! Yes this was IntelliJ/WebStorm. I will close it then and look forward to the fix. Cheers!

**Comment by jmesserly** [comment]
oh yeah, @zoechi this is a dupe of your issue. I should've searched first :)
