### ISSUE TITLE
Observatory: evaluation fails on some _Lists

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26088]
When on the inspect page for instance of _List, you can enter e.g. 'length' or some other expression.

When viewing the 'buckets' member of a MegamorphicCache, evaluation fails:

```
length  evaluate: invalid 'targetId' parameter: id 'objects/2225' does not correspond to a library, class, or instance
```

This instance should be viewable like any other instance.

**Comment by rmacnak-google** [comment]
This is intended, though the error message is misleading. The array in a megamorphic cache contains function objects (not to be confused with closures), which don't have Dart classes. Allowing eval on such an array would mean these objects could end up as the receiver of an instance call or target of an is or as check. The error should say something like "Cannot evaluate a VM-internal object."

**Comment by rakudrama** [comment]
This answer makes https://github.com/dart-lang/sdk/issues/26004 a much higher priority for me.

**Comment by rmacnak-google** [comment]
00eff0ff6ac9ce4af468c7e77e9572cf9266d57d
