### ISSUE TITLE
Tests with breakpoint set being skipped when using --pause-after-load 

### ISSUE THREAD

**Issue by TimIrwin26** [dart-lang/sdk#26080]
Transferred over from https://github.com/dart-lang/test/issues/409

When attempting to debug unit tests running on either content-shell or Dartium, any group where I set a breakpoint in one of the tests using browser developer tools ends up skipped.

In the second test run, I set a breakpoint in one of the tests during the "pause-after-load" using Chrome developer tools. The tests run fine if "--pause-after-load" is used with no browser breakpoints.

- OSX 10.11.3
- Dart 1.15.0
- test 1.12.12
- Current version of Chrome (or Dartium shipped in Homebrew package w/ Dart 1.15.0)
- Also reproduces on Ubuntu with a similar setup.

````
pro:~/sandbox/unit_test$ pub run test -p content-shell test/some_test.dart 
00:04 +0: A should fail                                                                            
abc
00:04 +0 -1: A should fail                                                                         
  Expected: <false>
    Actual: <true>
  
  package:test         expect
  some_test.dart 11:7  main.<fn>.<fn>
  
00:04 +0 -1: B should pass                                                                         
abc
00:04 +1 -1: C all called                                                                          
[should fail, should pass]
00:04 +2 -1: Some tests failed.          
                                                          
pro:~/sandbox/unit_test$ pub run test -p content-shell test/some_test.dart --pause-after-load
00:04 +0: loading test/some_test.dart                                                              

Observatory URL: http://127.0.0.1:51847
Remote debugger URL: http://localhost:51837/devtools/inspector.html?ws=localhost:51837/devtools/page/7341D459-82CC-47A9-9C3C-6A77CA1CF37D
The test runner is paused. Open the remote debugger or the Observatory and set breakpoints. Once
you're finished, return to this terminal and press Enter.

00:04 +0: All tests skipped.      
````
[pubspec.yaml.txt](https://github.com/dart-lang/test/files/186252/pubspec.yaml.txt)
[some_test.dart.txt](https://github.com/dart-lang/test/files/186228/some_test.dart.txt)

**Comment by terrylucas** [comment]
Please test with 1.17.1 Stable or 1.18 Dev channel.  There was a recent fix where BPs were not handled (cross frame).
