### ISSUE TITLE
Analyzer least upper bound computation fails to terminate on some inputs

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26094]
The code below causes a loop in the analyzer code (currently in strong mode and spec mode).

The language spec definition doesn't seem to provide much help here.  It seems like there's a pretty clear reading of the spec that gives `LUB(S, T) = LUB(Returns<S>, Returns<T>) = () -> LUB(S, T)`.

``` dart
typedef T Returns<T>();
class Bar <S extends  Returns<S>, T extends Returns<T>> {
  int foo(bool b) {
    S s;
    T t;
    return b ? s : t;
  }
}
```

**Comment by leafpetersen** [comment]
@munificent I don't think this is due to your changes, but FYI.

**Comment by leafpetersen** [comment]
I'm working on a fix for the strong mode code path.

**Comment by munificent** [comment]
Oof, nasty. The spec does point out that F-bounded quantification may lead to infinite types and that that case has to be handled... which we apparently don't.

**Comment by leafpetersen** [comment]
Strong mode side fixed here:

https://codereview.chromium.org/1843453002/

**Comment by leafpetersen** [comment]
Closing this, since it's fixed on the Dart 2 side.
