### ISSUE TITLE
.map declared with 0 type parameters

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#26105]
Since updating to 1.16 dev channel I have been getting errors from the analyzer around generic methods that were not present previously.

```
    writeArgumentsToBuffer(
        mixins.map/*<String>*/((type) => generateType(type)),
        buffer
    );
```

This results in the following errors listed within WebStorm.

```
ERROR: Unsound implicit cast from Iterable<dynamic> to Iterable<String> ([dogma_codegen] lib\src\codegen\class_metadata.dart:51)
ERROR: The type '((TypeMetadata) → dynamic) → Iterable<dynamic>' is declared with 0 type parameters, but 1 type arguments were given ([dogma_codegen] lib\src\codegen\class_metadata.dart:51)
```

In this case mixins is a List<TypeMetadata>. Previously there was no error given here and everything seemed to be working as advertised.

**Comment by zoechi** [comment]
dup of #26062
