### ISSUE TITLE
/b/build/slave/dart-sdk-mac-dev/build/sdk/runtime/vm/object.cc:15083: error: unreachable code

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/sdk#26101]
I'm seeing this on a bunch of my tests. 

I haven't had a chance to try to create a repro. Any advice on what I should be looking for that might trigger this is appreciated.

**Comment by iposva-google** [comment]
What version of the VM are you running?

**Comment by crelier** [comment]
I suspect that the type is null, but without repro, it is hard for me to tell what is causing this.

Interestingly, @sgmitrovic asked me yesterday if types were set to null temporarily in the class finalizer. So maybe he is seeing null types too?

**Comment by sgmitrovic** [comment]
On Tue, Mar 29, 2016 at 9:29 AM, Régis Crelier <notifications@github.com>
wrote:

> I suspect that the type is null, but without repro, it is hard for me to
> tell what is causing this.
>
> Interestingly, @sgmitrovic <https://github.com/sgmitrovic> asked me
> yesterday if types were set to null temporarily in the class finalizer. So
> maybe he is seeing null types too?
>
My problem was caused by looking up reexports, I was seeing empty arrays.
The error seems like a null-type issue, indeed. I have not seen a similar
issue in a long time.

**Comment by crelier** [comment]
Thanks Srdjan.
Anders, a repro is needed here.

**Comment by Andersmholmgren** [comment]
I'll have to try to get a repro. It's on the same code base where I hit the
other 3 generics bugs that I filed previously so my money is that it
relates to that in some way.
It seems pretty clear that my code has travelled on paths in the VM that
aren't very well travelled

**Comment by sgmitrovic** [comment]
Repro would be the best, but a stack trace from, e.g. core file may also be helpful.

**Comment by crelier** [comment]
Srdjan, having fixed several generic issues reported by Anders in the past, I can tell you that stack traces won't do (some will simply reflect infinite recursion, for example). As Anders puts it, his code has traveled unexplored paths in the VM :-) 
But we are very grateful to Anders for venturing into and reporting from dangerously unexplored territories. This only makes the VM better.

**Comment by Andersmholmgren** [comment]
Haha that's alright Régis I accept cash in any currency ;-)
