### ISSUE TITLE
Ubuntu no longer includes fonts ttf-kochi-mincho or ttf-kochi-gothic

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26119]
_From @vpigrad on March 29, 2016 3:36_

This blocks running tests that need content_shell.  They recommend "fonts-vlgothic" or "fonts-ipafont-gothic" which are more up to date.  I don't think the kochi fonts have been updated in over a decade:

https://launchpad.net/ubuntu/xenial/+package/ttf-kochi-gothic

_Copied from original issue: dart-lang/test#415_

**Comment by nex3** [comment]
_From @zoechi on March 29, 2016 8:29_

As a workaround I created symlinks to arbitrary other fonts to make it work but that shouldn't be necessary.

(Debian - some of these fonts might be available as package for Ubuntu but aren't for Debian)

```bash
apt-get install msttcorefonts fonts-indic fonts-tlwg-garuda-otf
mkdir /usr/share/fonts/truetype/kochi
cd /usr/share/fonts/truetype/kochi
ln -s ../dejavu/DejaVuSans-Bold.ttf kochi-gothic.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf kochi-mincho.ttf
mkdir /usr/share/fonts/truetype/ttf-indic-fonts-core/
cd /usr/share/fonts/truetype/ttf-indic-fonts-core/
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_hi.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_ta.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf MuktiNarrow.ttf
mkdir /usr/share/fonts/truetype/ttf-punjabi-fonts/
cd /usr/share/fonts/truetype/ttf-punjabi-fonts/
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_pa.ttf

ln -s dejavu/ ttf-dejavu
cd /usr/share/fonts/truetype
ln -s dejavu/ ttf-dejavu
```

**Comment by nex3** [comment]
I've moved this issue here because it's about content shell itself being broken, not about test in particular.

**Comment by vpigrad** [comment]
Thank you zoechi.  Your fix worked on Ubuntu 14, but didn't on 16.  On 16, it fails with the error:

 [10411:10411:0100/000000:21269733035:ERROR:zygote_linux.cc(612)] write: Broken pipe

The lack of output as to why it quit makes troubleshooting the failure impossible.

**Comment by vpigrad** [comment]
Ignore my last post.  I only thought it wasn't working since the error message is misleading.  You have to pass it a URL in the command line or, it fails with the above misleading error.

content_shell --dump-render-tree http://google.com/

Works.

**Comment by vpigrad** [comment]
After a Ubuntu update to 16.04 yesterday, the above workaround no longer works.  I ran strace, and you can see that content_shell does a stat on the Microsoft fonts, but doesn't open them.  It's a blocking issue again.

**Comment by zoechi** [comment]
content_shell was built to run Chrome layout tests not to use it for unit testing. It is convenient because it doesn't open a window, besides that its a misuse of the tool.  
An alternative could be `pub run test` to run a custom executable and support passing additional command line options to the browser like

```bash
xvfb-run --server-args='-screen 0, 1024x768x16' dartium -start-maximized http://localhost:63342/bwu_quick_nav/example/example1.html
```

**Comment by vpigrad** [comment]
A workaround for Ubuntu 16.04 is to downgrade ​libfontconfig1 and ​fontconfig-config to 2.11.1-0ubuntu8.
