### ISSUE TITLE
Unused Dart_ entrypoints stripped

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#26113]
With the current linker settings the dart binary fails to include all of the exported Dart_ entrypoints, which makes dart extensions fail to link dynamically at runtime.

**Comment by pylaligand** [comment]
https://gist.github.com/pylaligand/8bf90093f42b532ef862

This results in:
```
dyld: lazy symbol binding failed: Symbol not found: _Dart_IsDouble
  Referenced from: /path/to/my_library.dylib
  Expected in: flat namespace
```

**Comment by rmacnak-google** [comment]
92d492f9e27fb2c2491dae7514fb2d517558df3b

**Comment by pylaligand** [comment]
Thanks for fixing! When should we expect the fix to hit the stable channel?

**Comment by rmacnak-google** [comment]
The next stable is planned for Apr 22 (go/dart-release-schedule).
