### ISSUE TITLE
Warnings in web_gl_dart2js.dart

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#26111]
https://codereview.chromium.org/1831033002 introduced the following warnings in web_gl_dart2js.dart:

sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3063:5:
Warning: The method 'bufferSubData2D' is not defined for the class 'RenderingContext'.
    bufferSubData2D(targetTexture, levelOfDetail, xOffset, yOffset,
        format, type, data);

sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3063:21:
Warning: The getter 'targetTexture' is not defined for the class 'RenderingContext'.
    bufferSubData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                    ^^^^^^^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3063:36:
Warning: The getter 'levelOfDetail' is not defined for the class 'RenderingContext'.
    bufferSubData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                   ^^^^^^^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3063:51:
Warning: The getter 'xOffset' is not defined for the class 'RenderingContext'.
    bufferSubData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                                  ^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3063:60:
Warning: The getter 'yOffset' is not defined for the class 'RenderingContext'.
    bufferSubData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                                           ^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3064:9:
Warning: The getter 'format' is not defined for the class 'RenderingContext'.
        format, type, data);
        ^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3064:17:
Warning: The getter 'type' is not defined for the class 'RenderingContext'.
        format, type, data);
                ^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3054:5:
Warning: The method 'bufferData2D' is not defined for the class 'RenderingContext'.
    bufferData2D(targetTexture, levelOfDetail, xOffset, yOffset,
        format, type, data);

sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3054:18:
Warning: The getter 'targetTexture' is not defined for the class 'RenderingContext'.
    bufferData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                 ^^^^^^^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3054:33:
Warning: The getter 'levelOfDetail' is not defined for the class 'RenderingContext'.
    bufferData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                ^^^^^^^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3054:48:
Warning: The getter 'xOffset' is not defined for the class 'RenderingContext'.
    bufferData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                               ^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3054:57:
Warning: The getter 'yOffset' is not defined for the class 'RenderingContext'.
    bufferData2D(targetTexture, levelOfDetail, xOffset, yOffset,
                                                        ^^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3055:9:
Warning: The getter 'format' is not defined for the class 'RenderingContext'.
        format, type, data);
        ^^^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3055:17:
Warning: The getter 'type' is not defined for the class 'RenderingContext'.
        format, type, data);
                ^^^^
sdk/lib/web_gl/dart2js/web_gl_dart2js.dart:3009:16:
Warning: The getter 'targetText' is not defined for the class 'RenderingContext'.
    texImage2D(targetText, levelOfDetail, internalFormat, format, type, data);
               ^^^^^^^^^^

**Comment by johnniwinther** [comment]
The warnings are temporarily whitelisted in https://codereview.chromium.org/1838153002

**Comment by alan-knight** [comment]
Fixed, and whitelisting removed, in https://codereview.chromium.org/1846803002/
