### ISSUE TITLE
Dart List doesn't report the correct value for getOwnpropertyDescriptor in dartium 45

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#26128]
Repro:
      var list = ["a", "b"];
      var descriptor = Object.getOwnPropertyDescriptor(list, 0);
      // TODO(jacobr): re-enable th
      //expect(descriptor.enumerable, isTrue);
      // expect(descriptor.configurable, isTrue);

This is relatively harmless

**Comment by terrylucas** [comment]
Using:

var object = context['Object'];
var descriptor = object.callMethod("getOwnPropertyDescriptor", [list, 0]);

descriptor.configurable is True
descriptor.enumerable is False.

descriptor = object.callMethod('getOwnPropertyDescriptor', [descriptor["value"], 0])
descriptor.enumerable is True
descriptor.configurable is False

I don't think we're going to do anything more in Dartium but what should be done in dart:html/dart2js should Object be exposed with static methods e.g., getOwnPropertyDescriptor?
