### ISSUE TITLE
Analyzer FunctionTypeImpl equality doesn't treat named parameters as unordered

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26126]
The implementation of equality in FunctionTypeImpl compares named parameters in the order in which
they were added to the map.  This means that function types which are semantically equal can compare unequal (because their named parameters ended up in a different order).  It may be that we want two different notions of equality: syntactic equality and semantic equality.  I'm not sure that this is an active bug, but it seems like a latent bug to me.  I ran into this trying to use type equality in tests.

**Comment by bwilkerson** [comment]
I'm not sure what the use case is for syntactic equality. I suspect that semantic equality is the only one we really care about.

**Comment by leafpetersen** [comment]
I didn't have any concrete uses in mind for syntactic equality, but it's not inconceivable that there would be.  One consideration is that if you make == be semantic equality then the hash function has to respect that.  I guess you could just store the names in a canonical order and then it doesn't get any more expensive to compute.

I can imagine that some tools might want to distinguish between a typedef and its expansion (which should probably be semantically equal)?

**Comment by jmesserly** [comment]
> I can imagine that some tools might want to distinguish between a typedef and its expansion (which should probably be semantically equal)?

yeah, in DDC's runtime type system, we split typedefs from other function types. That gave us a nice way to avoid bugs where we confuse one thing accidentally. I think some of the complexity in FunctionTypeImpl is that 4 different things are combined there (non-generic/generic function types, and typedefs with or without type parameters of their own). In Dart1 only two things were combined (typedefs with type params, non-generic function types) so it was more tractable.

**Comment by jmesserly** [comment]
I should add, for the purposes of subtyping, DDC gets the corresponding function type for a typedef (unwrapping it, in a sense). But by tracking typedefs separately, we can print the typedef differently, which is very helpful for debugging.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124382
