### ISSUE TITLE
Sideways casts should be disallowed

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26120]
For backwards compatibility while we transitioned old code to strong mode and added generic method support we've allowed sideways casts in strong mode when the cast would have been an up or down cast in regular Dart.  This should be discontinued at some point soon.  See TODO(vsm) in DownCast.create in info.dart.

**Comment by jmesserly** [comment]
@leafpetersen does the no-implicit-casts flag subsume this issue?

**Comment by leafpetersen** [comment]
I don't think so.  Even with implicit casts, at some point we want to start disallowing these.  If no-implicit casts becomes the standard, then this becomes moot of course.

**Comment by jmesserly** [comment]
I wonder if we're at the point where I could just fix that? it looks easy to do in type_system but I wasn't sure if we were waiting for some reason

**Comment by jmesserly** [comment]
fyi working on this

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2231273002/
