### ISSUE TITLE
many strong mode errors are not correctly classified in Analyzer

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26122]
I'm going through StaticWarningCode. Almost all of these should be errors in strong mode. There are a handful of exceptions that are bona fide warnings.

I'll send out a CL shortly working around this in DDC, but naturally, that is just a short term fix.

**Comment by bwilkerson** [comment]
Perhaps the StaticWarningCode constructor should take an optional parameter indicating that it is a strong-mode error, which DDC (and other tools) could then use to promote warnings when running in strong mode. Just a thought.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1840203002/diff/20001/lib/src/report.dart for my attempt to workaround it on DDC side.

**Comment by bwilkerson** [comment]
Yep. Hence my suggestion to mark them in the error codes.

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen @munificent if any of you have a chance to take a look at this?

IMO it would be good to fix sooner rather than later, since lots of folks are in the process of getting packages strong mode clean.

**Comment by jmesserly** [comment]
BTW one option: we could probably just treat all StaticWarningCodes as errors.

The only categories that DDC allows are: uninitiated final, non-exhaustive enum, mismatched getter/setter types, and various incorrect use of "void" and/or return types.

That would leave our "down cast composite" as the only remaining warning.

**Comment by leafpetersen** [comment]
This:

const StaticWarningCode ARGUMENT_TYPE_NOT_ASSIGNABLE_STATIC_WARNING = const StaticWarningCode(

is one of the most noticeable misclassified ones - since this is not a StaticTypeWarning, it doesn't get caught by our current heuristic to upgrade severity.

**Comment by jmesserly** [comment]
@leafpetersen -- I thought @munificent 's ErrorProcessor was already upgrading these to errors

**Comment by jmesserly** [comment]
Specifically https://codereview.chromium.org/1840203002/diff/20001/lib/src/report.dart around line 180 should hit https://github.com/dart-lang/sdk/blob/0c1e85ebadaa0680d4ff30acc1f3ac823c53756e/pkg/analyzer/lib/source/error_processor.dart#L126. Maybe the error type isn't ErrorType.STATIC_TYPE_WARNING even though it's a StaticWarningCode?

**Comment by leafpetersen** [comment]
Didn't I just say that... ?  :)

Yes, I don't know why, but that warning is not a STATIC_TYPE_WARNING, it's a STATIC_WARNING, and so it doesn't get upgraded.

**Comment by jmesserly** [comment]
doh, yeah I misunderstood that :). But yeah, at least we're upgrading it on the DDC side now. Analyzer would be better though, for sure!

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1861363002/ adds the hooks necessary to fix this issue. To finish, someone who knows which warning codes should *not* be errors should change the default value of the optional parameter in StaticWarningCode's constructor and add an argument of `false` where appropriate.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2108823002/ -- fixes this. From that CL I also link to the DDC side.
