### ISSUE TITLE
Strong mode differs based on how it's enabled

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26129]
I have the following file called `test.dart`:

```dart
import 'dart:async';

abstract class Result<T> {
  static Future/*<T>*/ release/*<T>*/(Future<Result/*<T>*/> future) =>
      future.then/*<Future<T>>*/((result) => result.asFuture);

  Future<T> get asFuture;
}
```

If I run `dartanalyzer test.dart` with no `.analysis_options` file, or if I run `dartanalyzer --strong test.dart` with or without an `.analysis_options` file, it prints no errors. However, if I create the following `.analysis_options` file:

```yaml
analyzer:
  strong-mode: true
```

and I run `dartanalyzer test.dart` (**without** `--strong`), it prints the following error:

```
[error] The return type 'Future<Future<T>>' is not a 'Future<T>', as defined by the method 'release'.
```

**Comment by jmesserly** [comment]
Crazy! Probably picking up different SDKs?

(aside: not sure if it was intended, but in that example the generic method "T" shadows the class "T" ... we should probably be issuing an error for that, but might not be implemented)

**Comment by nex3** [comment]
That is intended; I'd expect it not to be a problem, since it's a static method.

**Comment by jmesserly** [comment]
> That is intended; I'd expect it not to be a problem, since it's a static method.

Ah, right. Yeah, should be fine in that case. (There used to be an analyzer warning disallowing any type parameters in static methods, I *think* I fixed it to only disallow the class's type parameters...)

**Comment by lrhn** [comment]
I don't think it should be a problem to shadow a type variable in a non-static method either. Shadowing is allowed for all other names.

**Comment by leafpetersen** [comment]
@bwilkerson @pq Any chance either of you could spare a few cycles to try to track this down?  It's small but insidious.  It looks like something with the way that analyzer options are getting propagated from command line vs .analysis_options.  Maybe not getting copied in somewhere when set from the .analysis_options file?

**Comment by pq** [comment]
@leafpetersen : I can repro this and have a breakpoint set in the debugger but don't quite know what to make of what I'm seeing...  Maybe we can take a look tomorrow?

**Comment by pq** [comment]
Running this again today  I'm seeing different results in the CLI.

```
[error] The type '((Result<T>) → dynamic, {onError: Function}) → Future<dynamic>' is declared with 0 type parameters, but 1 type arguments were given (/src/sandbox/console-full/lib/test.dart, line 5, col 14)
[warning] Unsound implicit cast from Future<dynamic> to Future<T> (/src/sandbox/console-full/lib/test.dart, line 5, col 7)
1 error and 1 warning found.
```

The basic issue is that we're not properly propagating `.analysis_options` configurations to the SDK context.  I'll work on fixing that.  In the meantime, if there's anything interesting about the new errors, chime in!

**Comment by leafpetersen** [comment]
@pq That new error is what you get when you analyze strong mode code against a non-strong mode SDK.  Basically the declaration (I think Future.then here?) has been analyzed ignoring generic methods, and now in your application at the call site a generic parameter is being passed.

**Comment by nex3** [comment]
![Yayyyy](https://cloud.githubusercontent.com/assets/188/15161838/84bc953a-16b4-11e6-93a8-3a005df53bc7.gif)
