### ISSUE TITLE
Update pkg/analyzer to pkg/crypto >=0.9.2 <2.0.0 – fix deprecations

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26138]
A few deprecations – blocks folks who depend on analyzer from getting strong-mode clean

**Comment by nex3** [comment]
Please actually use `>=0.9.2 <1.0.0`, as [the changelog](https://github.com/dart-lang/crypto/blob/master/CHANGELOG.md#100) requests.

**Comment by kevmoo** [comment]
> Please actually use >=0.9.2 <2.0.0, as the changelog requests.

Yup – we should just stop using the deprecated APIs – will change title

**Comment by kevmoo** [comment]
@bwilkerson I'd like to bump the priority on this – lots of folks are using analyzer package and they can't get the latest crypto.

Or they version solver is giving them the latest version of crypto and an older version of analyzer – `pkg/test` this is what happens.

**Comment by kevmoo** [comment]
I'll take a look at this quick...

**Comment by kevmoo** [comment]
Started here https://codereview.chromium.org/1890973003/

**Comment by kevmoo** [comment]
Closed in https://github.com/dart-lang/sdk/commit/5b5312a67c1c5f6c40564a9f9278e2011099cd89
