### ISSUE TITLE
Analyzer incorrectly says that an exported import is unused.

### ISSUE THREAD

**Issue by ianloic** [dart-lang/sdk#26135]
When running `dartanalyzer c.dart` on the follow code I get the error
```
Analyzing [c.dart]...
[hint] Unused import (/Users/ianloic/tmp/dart-analyzer-bug/b.dart, line 1, col 8)
1 hint found.
```
even though the import is clearly used. I was able to work around this by moving a declaration into the wrong file and / or adding extra imports that break the API I'm going for. It would be good for the analyzer to understand what's going on here.

a.dart:
```
int foo = 42;
```

b.dart:
```
import "a.dart";
export "a.dart";
```
c.dart:
```
import "b.dart";
void main() {
  print("the answer is $foo");
}
```

**Comment by bwilkerson** [comment]
I'm not sure _I_ understand what's going on here :-)

Is that the complete content of `b.dart`? If so, it looks to me like the import is not necessary. (You don't have to import a library in order to export it.)

**Comment by ianloic** [comment]
Oh. I assumed you had to import to export. Never mind me...
