### ISSUE TITLE
Inference failure for Iterable.expand()

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26139]
In the following code:

```dart
List<String> strings() {
  var stuff = [].expand((i) {
    return <String>[];
  });

  return stuff.toList();
}
```

the final line produces a warning:

```
[warning] Unsound implicit cast from List<dynamic> to List<String>
```

It seems that inference should be able do determine that the type parameter for
expand is String in this case.

**Comment by leafpetersen** [comment]
I think this is an instance of https://github.com/dart-lang/sdk/issues/25490, but one that we can maybe address more easily.  The lambda body is checked using the pre-inference context type (`Iterable<dynamic>`), which is possibly then overriding the inferred return type of the function ('List<String'), and therefore disabling the generic method inference.

**Comment by jmesserly** [comment]
Original example still reproduces, but this works:
```dart
List<String> strings() {
  var stuff = [].expand((i) => <String>[]);
  return stuff.toList();
}
```
I thought we were supposed to treat "return" the same as `=>` ... I think your theory is right Leaf: when we are going down we (tentatively) assume T is dynamic, when we are going up, well, we never infer return context if one was present already. But we shouldn't do that. Instead we should let the return context be tightened, which would fix this.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2225413002
