### ISSUE TITLE
No dynamic type error in async function with 'return e;' statement

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26133]
The Dart Programming Language Speciﬁcation version 1.11 chapter 17.12 Return reads:

> Executing a return statement return e; proceeds as follows:
> First the expression e is evaluated, producing an object o. Next:
> ...
>Let T be the static type of e and let f be the immediately enclosing function.
> ...
> Let S be the runtime type of o. In checked mode:
> • If the body of f is marked async (9) it is a dynamic type error if o is
> not null (16.2) and Future&lt;S&gt; is not a subtype of the actual return type
> (19.8.1) of f.

The following tests demonstrates, that dynamic type error does not occur in checked mode.
```dart
import 'dart:async';

isCheckedMode() {
  try {
    var i = 1;
    String s = i;
    return false;
  } on TypeError {
    return true;
  }
}

var x = 'a';

Future<int> foo() async {
  return x;
}

main() {
  foo().then(
      (_) {
        if (isCheckedMode()){
          print('Test failure: TypeError is expected in checked mode');
        } else {
          print('Test passed');
        }
      },
      onError: (e) {
        if (!isCheckedMode()){
          print('Test failure: TypeError is not expected without checked mode');
        } else if(!(e is TypeError)){
          print('Test failure: TypeError is expected instead of $e');
        } else {
          print('Test passed');
        }
      }
  );
}
```

Test output:
> dart --checked test.dart
> Test failure: TypeError is expected in checked mode
> dart test.dart
> Test passed
 
Expected output:
> dart --checked test.dart
> Test passed
> dart test.dart
> Test passed

Dart VM version: 1.15.0 (Wed Mar 09 10:07:59 2016) on "windows_x64"

**Comment by iposva-google** [comment]
CC @crelier @gbracha

**Comment by whesse** [comment]
There is still a crashing test that is marked with this issue, Language/Statements/Continue/async_loops_t10: Crash # Issue 26133
And on ASAN bots, it is a failure rather than a crash, because ASAN captures the crash, so there is a status line for ASAN as well

**Comment by crelier** [comment]
I am not sure why the co19 test failure references this issue. As far as I can tell, it is unrelated. I filed a new issue #26577 and closed this one again.
