### ISSUE TITLE
analysis server doesn't recognize enableConditionalDirectives

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26136]
In the `.analysis_options` file, the command line analyzer recognizes `enableConditionalDirectives: true` and can parse files that use conditional directives. However the analysis server doesn't respect this flag.

To repo, clone https://github.com/dart-lang/usage and open with an analysis server based product. `Dart VM version: 1.16.0-dev.2.0`

Related to https://github.com/dart-lang/sdk/issues/24581.

**Comment by pq** [comment]
Conditional directives are enabled by default as of https://github.com/dart-lang/sdk/commit/bcd8ef3dea0caffa6a715191cc937fe48076dc81...  This should be ok now?

**Comment by devoncarew** [comment]
Looks good now!
