### ISSUE TITLE
vm/cc/SafepointTestDart crash (flaky)

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26131]
https://build.chromium.org/p/client.dart/builders/vm-linux-debug-ia32-be/builds/6383/steps/checked%20vm%20tests/logs/stdio

=== Failure summary:

FAILED: none-vm-checked debug_ia32 vm/cc/SafepointTestDart
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

stdout:
Running test: SafepointTestDart

stderr:
runtime/vm/stack_frame.cc:31: error: expected: code != Object::null()

Command[run_vm_unittest]: DART_CONFIGURATION=DebugIA32 out/DebugIA32/run_vm_tests --ignore-unrecognized-flags SafepointTestDart
Took 0:00:03.533291

Short reproduction command (experimental):
    python tools/test.py -aia32 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 vm/cc/SafepointTestDart

**Comment by fsc8000** [comment]
@a-siva  Is this a known issue?

**Comment by iposva-google** [comment]
@rmacnak-google is aware about the flaky failure after his seemingly unrelated change. Decided to leave the change in today so that we can figure out flakiness frequency.

**Comment by rmacnak-google** [comment]
ba608694b7aa481b8e62f6aeb22ee388646b4f0b
