### ISSUE TITLE
Support messages like IMPORT_EXPERIMENTAL_MIRRORS for analyzeUri

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#26132]
Messages like IMPORT_EXPERIMENTAL_MIRRORS are currently not supported for analyzeUri since the library dependency graph is not available for consecutive runs. We should now be able to support it throught ExportElement's

**Comment by bkonyi** [comment]
Closing as `dart:mirrors` are no longer supported for web.
