### ISSUE TITLE
VM: VerifyPointers does not work with background compilation

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#26149]
see runtime/vm/custom_isolate_test.cc

Pointer verification must reach a safepoint, otherwise the other thread may be still constructing objects while verifier is verifying.

**Comment by iposva-google** [comment]
We should disallow the combination of pointer verification and background compilation.

**Comment by fsc8000** [comment]
I think this is fixed now @rmacnak-google . We have a safepoint-scope around the heap verification in VerifyOnTransition() now.
