### ISSUE TITLE
File member sorting mishandles doccomments above an import

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26140]
Start with the following code in IntelliJ:

    /**
     * Comment
     */
    import 'package:foo/foo.dart';
    import 'package:bar/bar.dart';

    main() {}

Now use `Sort members in Dart file`.  The result is:

    import 'package:bar/bar.dart';
    /**
     * Comment
     */
    import 'package:foo/foo.dart';

    main() {}

Which seems fairly reasonable.

Now use `Sort members in Dart file` again.  The result is:

    import 'package:bar/bar.dart';
    /**
     * Comment
     */
    import 'package:foo/foo.dart';
    /**
     * Comment
     */

    main() {}

Which is definitely wrong.

Now use `Sort members in Dart file` again.

This results in IntelliJ logging `IllegalArgumentException: endOffset < startOffset: 81 < 101; documentLength: 112`

Digging through the code, I see two bugs:  First of all, import sorting sometimes duplicates doc comments.  That causes the "definitely wrong" case above.

Secondly, the `findCommonOverlap` function matches the overlapping text backwards, e.g.:

    findCommonOverlap('123456xyz', 'xyzabcd') == 0
    findCommonOverlap('123456xyz', 'zyxabcd') == 3

This causes it to sometimes send invalid indices to IntelliJ.  That causes the IllegalArgumentException.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/582c0389403472d5b773316c3f89b646f33c777f

**Comment by scheglov** [comment]
Reopening for `findCommonOverlap` fixing.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1849843002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/559bc17535f5d85243540466a63d8a0cb36fdc6a
