### ISSUE TITLE
VM: VerifyPointers does not work OSR (debug mode)

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#26150]
xcodebuild/DebugX64/run_vm_tests --optimization-counter-threshold=10 CustomIsolates

/sources/git-two/sdk/runtime/vm/object.cc:13608: error: expected: !is_optimized()

OSR compilation is invokeked via StackOverflow runtime function. Just before exiting the runtime function, it modifies the return address to point to the prolog of the OSR method. That prolog does not have a stack map associated with it, as we do not expect the exit of a runtime function to be a safepoint.

**Comment by iposva-google** [comment]
We should ensure that the transition back from OSR does not attempt verification in this particular call.

**Comment by rmacnak-google** [comment]
Fixed in bb85b32d515c0035a38e1145b5dd8e0acd83d71c
