### ISSUE TITLE
Having to define analysis_options in every package is cumbersome.

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#26154]
My repository hosts 15+ Dart packages and defines one .analysis_options file at the root. It looks like that options file is ignored by Atom which shows me all sorts of lint warnings when the file only specifies a handful (and a manual run of dartanalyzer only shows those).

/cc @devoncarew

**Comment by devoncarew** [comment]
also cc @pq

**Comment by bwilkerson** [comment]
I believe the expectation is for each package to have its own options file, but it sounds like the options file is in the directory containing all of the packages. Is that true?

If so, does it work correctly (for one of the packages) if you copy the file to the root of the package?

**Comment by pylaligand** [comment]
Yes.

No.

**Comment by pq** [comment]
> > If so, does it work correctly (for one of the packages) if you copy the file to the root of the package?

> No.

I'd like to try and reproduce this.  Is your repo public?

**Comment by pylaligand** [comment]
It is not, but I can create one that reproduces the issue if that's helpful.

**Comment by pq** [comment]
That would be great.  Thanks!

**Comment by pylaligand** [comment]
So I tried to put together a smaller repo exhibiting the issue, but while the options file does not get picked up if it is placed at the root _of the project_, it does work when copied to the root _of the package_.

I then went back to my repo, tried to restart analysis, restart Atom, but it still shows lints I'm not enabling either at the root of the project or the root of the package. As an example, I never set `always_declare_return_types` anywhere and yet I'm seeing plenty of "Declare method return types" infos in Atom.

Not sure where to go from here. Since we both work for Google, I guess I can add you to my repo.

**Comment by pq** [comment]
> So I tried to put together a smaller repo exhibiting the issue, but while the options file does not get picked up if it is placed at the root of the project, it does work when copied to the root of the package.

Right.  Another source for confusion.  Options correspond to _packages_.  We often talk as if projects and packages were synonymous when often they're not.

> Not sure where to go from here. Since we both work for Google, I guess I can add you to my repo.

Awesome.  Happy to look.

**Comment by pq** [comment]
> I then went back to my repo, tried to restart analysis, restart Atom, but it still shows lints I'm not enabling either at the root of the project or the root of the package. As an example, I never set always_declare_return_types anywhere and yet I'm seeing plenty of "Declare method return types" infos in Atom.

On looking over the sources, I think I see (the other) source of confusion.  What you're seeing are analysis options that are inherited from flutter, which identifies a number of [analyses](https://github.com/flutter/engine/blob/master/sky/packages/sky_engine/lib/_embedder.yaml) that get turned on for all clients.

cc @sethladd @Hixie

To summarize, I see two issues:

1. Having options defined in 15 packages is cumbersome.
2. Inheriting embedded options can be confusing.

**Comment by pylaligand** [comment]
I filed https://github.com/flutter/atom-flutter/issues/62 for the Flutter part. Wanna keep this one open for issue 1?

**Comment by pq** [comment]
Great.  Yep.  I re-named it to reflect the new thrust.  Thanks!

**Comment by pq** [comment]
Kicked off a doc to explore a proposal [here](https://docs.google.com/document/d/1rRlZut75Twl8hJ6529xjGRc12miHFPpQ8gr_oP6J3dc/edit?usp=sharing).  Thoughts welcome!

**Comment by pylaligand** [comment]
I don't think so.
