### ISSUE TITLE
Analyzer should catch dangling [Foo] references in dartdocs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26158]

**Comment by scheglov** [comment]
There is some work in progress, which was not actually finished.
https://codereview.chromium.org/1530993002

**Comment by pq** [comment]
Given the possible (undesired) impact, maybe this should be a lint?

**Comment by pq** [comment]
cc @bwilkerson : what do you think about migrating this to a lint?

**Comment by pq** [comment]
@scheglov : how do you feel about us moving this over to a lint?

**Comment by bwilkerson** [comment]
Sorry, I missed the earlier ping.

I think that, hint or lint, we need to clean up the false positives as much as possible first.

I don't remember: are we currently treating square brackets within code as references and trying to resolve them? I don't think we want to do that, whether for this rule or for anything else (like navigation or refactoring). So I think we should take care of that problem independent of what happens to this rule.

**Comment by scheglov** [comment]
@bwilkerson We [remove code blocks](https://github.com/dart-lang/sdk/commit/c19e958822a2941a4a5c90219a61a00d60c92a35) while resolving comments.

**Comment by Hixie** [comment]
If it's a lint, it would actually _help_ with removing false positives, since we could turn it on only when we're specifically looking at this.

**Comment by pq** [comment]
Closing in favor of the lint request, in progress and tracked yonder: https://github.com/dart-lang/linter/issues/240.
