### ISSUE TITLE
Document addition of SecurityContext.alpnSupported in changelog

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26157]
Please, @zanderso ?

**Comment by iposva-google** [comment]
I feel like we are overburdening the Changelog.md file with unnecessary noise. **Maybe** the addition to the SecurityContext API is useful as per this request. But bug fixes such as correct handling of weekday at start of epoch? Why is 0f5c249f22b7dc7dd1f6d052b36e386b7534a8b9 (<-totally random bug fix) not included?

Please explain...

**Comment by kevmoo** [comment]
@iposva-google Agreed. Documenting bug fixes is out of scope – unless they are HUGE.

**Comment by iposva-google** [comment]
Thanks for the clarification.
