### ISSUE TITLE
Downwards inference does not infer types for optional parameters from required parameters

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26155]
In the code below, downwards inference successfully fills in the type for `y` but not for `x`.  Both should work.

```dart
void takesF(void f(int x)) {
  takesF(([x]) {});
  takesF((y) {});
}
```

**Comment by jmesserly** [comment]
very strange. I wonder what's going on there, or if it's related to the other bug (not removing fuzzy arrows). In general we try and treat all kinds of parameters uniformly whenever we can (typically using `.parameters` on FunctionTypeImpl which lets us iterate over all of them).

**Comment by jmesserly** [comment]
I can still reproduce this:
```dart
// with --strong --no-implicit-casts --no-implicit-dynamic
void takesF(void f(int x)) {
  // [error] Missing parameter type for 'x'. Either add an explicit type like 'dynamic', [...]
  // [error] A value of type 'dynamic' cannot be assigned to a variable of type 'bool' 
  takesF(([x]) { bool z = x.isEven; });
  takesF((y) { bool z = y.isEven; });
}
```
going to take a look

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2230513002/
