### ISSUE TITLE
Observatory: cannot print protected fields of superclass (even when in method of that class)

### ISSUE THREAD

**Issue by schwa423** [dart-lang/sdk#26161]
I have two classes MemGraph and GraphBase, where the former extends the latter (they aren't in the same library). GraphBase has a field "_observers".  

If I step the debugger into a MemGraph instance, then I get an error when I type "print _observers".  This occurs even if I step the debugger into a GraphBase method that uses _observers (in other words, "_observers" appears in the stack frame I'm looking at, but I can't print it).

Here is a stack trace, where GraphBase._notifyInternal() uses "_observers".

$ print _observers
Unhandled exception:
Class 'MemGraph' has no instance getter '_observers'.

NoSuchMethodError: method not found: '_observers'
Receiver: Instance of 'MemGraph'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      MemGraph.Eval (evaluate:source:1:16)
#3      GraphBase._notifyInternal (package:modular/graph/graph_base.dart:77:50)
#4      GraphBase.notifyGraphChanged (package:modular/graph/graph_base.dart:54:5)
#5      MemGraph.privateAddNode (package:modular/graph/mem_graph.dart:58:5)

**Comment by rmacnak-google** [comment]
87e8bc2c96d2a90ae701d10fa986fcb63a1f102e
