### ISSUE TITLE
Observatory: cannot see superclass fields

### ISSUE THREAD

**Issue by schwa423** [dart-lang/sdk#26160]
I have two classes MemGraph and GraphBase, where the former extends the latter.    If I am debugging in Observatory, I might come upon the following situation.

$ print myMemGraph
=  MemGraph {  ⊞  } 

If I click on the '+' sign to expand it, I can see the MemGraph fields, but not the GraphBase fields.

**Comment by zoechi** [comment]
As you mentioned in #26161, you have private fields in `GraphBase`. If `GraphBase` is in a different library than `MemGraph`, the private fields of `GraphBase` are not accessible from `MemGraph`. 
Identifiers starting with `_` are library-private, not protected. If you want protected fields you get "some" support by the analyzer if you make the field public (without `_`) and add the `@protcteded` annotation from the https://pub.dartlang.org/packages/meta package. I don't know if they are also supported in spec-mode or only in strong-mode.

**Comment by rmacnak-google** [comment]
They are all there, just not in the expected order (superclass first).

**Comment by schwa423** [comment]
As Ryan said, the fields were there, but in an unexpected order... as a result I misread the GUI.

Regarding access to private fields, I respectfully disagree with @zoechi.  Observatory is a debugger, so I should be able to see whatever fields I want to, regardless of the runtime type of the object being inspected.

**Comment by rmacnak-google** [comment]
441f7d852405547309173e401fe41391218c4ec0
