### ISSUE TITLE
Invalid warning in strong mode

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26174]
Create a Dart file containing the following:

    abstract class A {
      bool operator ==(Object object);
    }

    class B implements A {}

With strong mode enabled, there is a warning generated that I think ought not to be generated:

    WARNING: Missing concrete implementation of 'Source.==' ([analysis_server] test/stress/generator/packages.dart:723)

The method in question is implemented in Object, and hence is not missing. There is no warning in spec mode.

**Comment by bwilkerson** [comment]
@leafpetersen It's possible that this isn't a real bug. What's going on here is that the declaration in `A` has a parameter type of `Object` and the method in `Object` has a parameter type of `dynamic`:

    bool operator ==(other)

So the method in `A` is not a subtype of the method in `Object` in strong mode.

Is that the behavior we want? (Is there anything that can validly be passed to a `dynamic` parameter that can't be passed to an `Object` parameter?)

**Comment by leafpetersen** [comment]
No, this doesn't seem right. We should essentially treat dynamic and Object as equivalent for these purposes.  Our subtyping code usually uses an "isTop" function which treats them both the same.  Do you know if the error is coming from the strong mode checker override checker (in checker.dart) or from the error verifier?  If the latter, I think the error verifier does its checking in a somewhat different way, so it may not be handling this correctly.  There may also be an interaction with some oddness that we have in place where we treat dynamic as bottom in function parameter positions, though here that should make this go through.

Independent of that issue, the error message is not ideal:  https://github.com/dart-lang/sdk/issues/25232 .

**Comment by bwilkerson** [comment]
It's coming from the ErrorVerifier (line 4518):

    if (_typeSystem.isSubtypeOf(foundConcreteFT, requiredMemberFT)) {

foundConcreteFT = (dynamic) -> bool
requiredMemberFT = (Object) -> bool

And I agree that the error message isn't good.

**Comment by leafpetersen** [comment]
Ok.  Assuming that the subtype check there is in the correct order, which I presume it is (foundConcreteFT is presumably the type of the actual implementation provided, which  must be a subtype of the type promised by the interface), then what's going on is that we are treating foundConcreteFT as (bottom) => bool because of our special treatment of dynamic parameters.

I'm actually in the middle of a CL which is trying to make some of this more rational, so maybe I should take this over.

**Comment by bwilkerson** [comment]
Yes, "found" is the implementation in `Object`, "required" is the abstract method in `A`.

It's all yours.
