### ISSUE TITLE
Patching classes after finalized causes ~80 language test failures

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#26178]
The elimination of the snapshot code (patching methods after class is finalized) change [CL](https://codereview.chromium.org/1850653003/) in the VM seems to be causing these failures.  I've changed our DEPS to not use Jacob's [CL](https://codereview.chromium.org/1850653003/) which I guess is exercising that portion of the VM.

Here's a [log](https://uberchromegw.corp.google.com/i/client.dart/builders/dartium-mac-inc-be/builds/11685/steps/dartium_core_unchecked_tests/logs/stdio) of the ~80 failures on a bot, happens on all bots and all platforms.

We can't leave this DEPS for too long it prevents us from changing WebKit until this is fixed.

Can one of you can check to see which side of the fence is causing the failures?

**Comment by jacob314** [comment]
Running with a debug build I am seeing the following assert hit.
../../dart/runtime/vm/parser.cc:7672: error: expected: current_class().is_finalized()

multitest_language_interface_cycle_test_01

**Comment by jacob314** [comment]
Issue was we were attempting to run code even when it had a compile error.  Fix will be out shortly.
