### ISSUE TITLE
Mirrors broken for function typedef

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#26187]
Test co19/Language/Metadata/before_param_t09 now fails in Dartium in the last couple of days.  I'm wondering if it has to do with the [CL](https://chromiumcodereview.appspot.com/1834673003/) Do not compilig a class when the class mirror tries to access the metadata.  Here's the test:

```
import 'dart:mirrors';

class A {
  const A();
}

typedef void f(@A() int, String);

main() {
  ParameterMirror paramMirror = (mirrors.reflectType(f) as mirrors.TypedefMirror).parameters[0];
  // paramMirror.type should be int but its now dynamic.

  // Below fails metaData is an empty list.
  print('.A' == mirrors.MirrorSystem.getName(paramMirror.metadata[0].type.qualifiedName));
}
```

**Comment by a-siva** [comment]
The code you have above does not match up with the code that is there in the repo for co19/Language/Metadata/before_param_t09.dart

import 'dart:mirrors';
import '../../Utils/expect.dart';

class A {
  const A();
}

typedef void f(@A() int, String);

main() {
  ParameterMirror paramMirror =
    (reflectType(f) as TypedefMirror).referent.parameters[0];
  Expect.equals('.A',
    MirrorSystem.getName(paramMirror.metadata[0].type.qualifiedName));
}

**Comment by terrylucas** [comment]
In copying I was sticking in a better markup for issue and somehow lost something. but the code I tested is just like yours above.  The failure is still the same

paramMirror.type is dynamic not int 
and
paramMirror.metadata is an empty list.

**Comment by terrylucas** [comment]
Did you try running the code?  It fails in Dartium

**Comment by a-siva** [comment]
This program reproduces the problem on standalone VM:

import 'dart:mirrors';
class A {
  const A();
}
typedef void f(@A() int, String);
main() {
  var libraries = currentMirrorSystem().libarries;
  ParameterMirror paramMirror =
    (reflectType(f) as TypedefMirror).referent.parameters[0];
  print('.A' == MirrorSystem.getName(paramMirror.metadata[0].type.qualifiedName));
}

Comment out the line 
  var libraries = currentMirrorSystem().libarries;

and the test will work.

Adding @crelier
