### ISSUE TITLE
"// ignore:" incantation should be required at the end of the line, not before it 

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26181]
(Reported by @Hixie.)

Otherwise it interferes with dartdocs. For example:

```dart
/// An object that can hit-test pointers.
abstract class HitTestable { // ignore: one_member_abstracts
  void hitTest(HitTestResult result, Point position);
}
```

(Moved from: https://github.com/dart-lang/linter/issues/203.)

**Comment by Hixie** [comment]
it also is generally unintuitive to me that the warning is on the  "wrong" line. ☺

**Comment by pq** [comment]
Implemented with 6b2060598491e106f941bafe20a53467f26958ea.

For example:

![screen shot 2016-04-22 at 11 11 00 am](https://cloud.githubusercontent.com/assets/67586/14750697/f59bdea2-087a-11e6-967a-6f5568008cb1.png)

...

![screen shot 2016-04-22 at 11 11 10 am](https://cloud.githubusercontent.com/assets/67586/14750719/15e6e2ce-087b-11e6-8a7e-47164d465b1f.png)

🎉

**Comment by zoechi** [comment]
Does this mean `// ignore: ...` can now be in the line before or in the same line at the end or only the later?

**Comment by bwilkerson** [comment]
It can be in either location: at the end of the line containing the error, or by itself on the line immediately preceding the line containing the error. (Where "containing the error" means the line that contains the first character of the error region in cases where the error continues across multiple lines.)

**Comment by zoechi** [comment]
@bwilkerson great, thanks for the info.
