### ISSUE TITLE
(Need a technical support) How do I determine that the class implements the operator unary minus?

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#26189]
I need a technical support from developers.
How do I determine that the class implements the operator unary minus (through reflection)?

**Comment by eernstg** [comment]
The tricky part would be the name "unary-" (and adding error checking etc. ;-):

```dart
bool hasUnaryMinus(Type clazz) {
  return reflectClass(clazz).declarations.values.any(
      (DeclarationMirror d) => d.simpleName == const Symbol("unary-"));
}
```

PS: Since it's a question rather than an issue, it would be better to ask on a mailing list.

**Comment by mezoni** [comment]
Thank you.
