### ISSUE TITLE
Strong mode should recognize new A/*<T>*/.named()

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26183]
In the following example, the `<T>` is ignored.

```dart
var completer = new Completer/*<T>*/.sync();
```
The analyzer should handle the comment syntax as for literals.

(Workaround is currently to write `new Completer<dynamic/*=T*/>.sync()`.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1870733002/
