### ISSUE TITLE
add url safe Base64

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/sdk#26186]
As mentioned in https://github.com/dart-lang/crypto/issues/32, removal of the 'url-safe' base64 functionality from the `crypto` package has left users of that package without a 'url-safe' implementation.

This is critical for things like implementations of the `jwt` standard.

**Comment by lrhn** [comment]
It's functionality that fits into package:convert.
However, it's probably simple to add a Base64Encoder.urlSafe constructor and a modified translation table to dart:convert, and it allows you to reuse the remaining code.
