### ISSUE TITLE
Dart analyzer 1.15.0: problem with UnmodifiableListView

### ISSUE THREAD

**Issue by afandria** [dart-lang/sdk#26184]
I had code that used to be analyzed fine but now has a warning with dartanalyzer 1.15.0.

```
$ dartanalyzer --version
dartanalyzer version 1.15.0
```

My code is like this:

```dart
import 'dart:collection';

class Card {
  final String deck;
  final String identifier;

  Card(this.deck, this.identifier);
  Card.fromString(String cardData)
      : deck = cardData.split(" ")[0],
        identifier = cardData.split(" ")[1];

  bool operator ==(Object other) {
    if (other is! Card) return false;
    Card o = other as Card;
    return deck == o.deck && identifier == o.identifier;
  }

  int get hashCode => 37 * (deck.hashCode + 41 * identifier.hashCode);

  static final List<Card> all = new UnmodifiableListView<Card>(<Card>[
    new Card("classic", "c1"),
    new Card("classic", "c2"),
    new Card("classic", "c3"),
    new Card("classic", "c4"),
    new Card("classic", "c5"),
    new Card("classic", "c6"),
    new Card("classic", "c7"),
    new Card("classic", "c8"),
    new Card("classic", "c9"),
    new Card("classic", "c10"),
    new Card("classic", "cj"),
    new Card("classic", "cq"),
    new Card("classic", "ck"),
    new Card("classic", "d1"),
    new Card("classic", "d2"),
    new Card("classic", "d3"),
    new Card("classic", "d4"),
    new Card("classic", "d5"),
    new Card("classic", "d6"),
    new Card("classic", "d7"),
    new Card("classic", "d8"),
    new Card("classic", "d9"),
    new Card("classic", "d10"),
    new Card("classic", "dj"),
    new Card("classic", "dq"),
    new Card("classic", "dk"),
    new Card("classic", "h1"),
    new Card("classic", "h2"),
    new Card("classic", "h3"),
    new Card("classic", "h4"),
    new Card("classic", "h5"),
    new Card("classic", "h6"),
    new Card("classic", "h7"),
    new Card("classic", "h8"),
    new Card("classic", "h9"),
    new Card("classic", "h10"),
    new Card("classic", "hj"),
    new Card("classic", "hq"),
    new Card("classic", "hk"),
    new Card("classic", "s1"),
    new Card("classic", "s2"),
    new Card("classic", "s3"),
    new Card("classic", "s4"),
    new Card("classic", "s5"),
    new Card("classic", "s6"),
    new Card("classic", "s7"),
    new Card("classic", "s8"),
    new Card("classic", "s9"),
    new Card("classic", "s10"),
    new Card("classic", "sj"),
    new Card("classic", "sq"),
    new Card("classic", "sk"),
  ]);

  toString() => "${deck} ${identifier}";

  get string => toString();
}
```

The warning is:
`A value of type 'UnmodifiableListView<Card>' cannot be assigned to a variable of type 'List<Card>'`

This may be a regression related to #10090

However, this code has no warnings when plopped into DartPad and only sometimes shows the warning in Atom with the Dart and Flutter plugins.

**Comment by bwilkerson** [comment]
Do you have strong mode enabled?

**Comment by afandria** [comment]
I'm not running dartanalyzer with any special flags, and I don't recall configuring it to use strong mode. How can I find out?

**Comment by bwilkerson** [comment]
If you're not passing in a command-line flag ("--strong", IIRC), then it would have to be in your .analysis_options file and would look like

    analyzer:
      strong-mode: true

**Comment by afandria** [comment]
Yeah, I'm not using the flag, nor does my project have `.analysis_options`.

**Comment by afandria** [comment]
Actually, it looks like there are some `.analysis_options` on my filesystem, but the dartanalyzer I'm using doesn't have `strong-mode: true`. I see this:

```
linter:
  rules:
    - annotate_overrides
    - empty_constructor_bodies
    - unnecessary_brace_in_string_interp
```

**Comment by afandria** [comment]
Could it be that `.analysis_options` is based on the actual imported package?

My collections packages at collections-1.5.0 have an analyzer in them with

```
analyzer:
  strong-mode: true
```

inside `$HOME/.pub-cache/hosted/pub.dartlang.org/collection-1.5.0/.analysis_options`

**Comment by bwilkerson** [comment]
I went back and re-read the original post, and found I'd glossed over:

> However, this code has no warnings when plopped into DartPad and only sometimes shows the warning in Atom with the Dart and Flutter plugins.

Options from imported packages are not used, but the options from Flutter are magic and are inherited, and do enable strong mode. I believe that DartPad is *not* using strong mode, so I'm fairly sure this is a strong mode issue. Thanks!

**Comment by pq** [comment]
cc @sethladd as an FYI on confusion arising from options inherited from `_embedder.yaml`.

**Comment by leafpetersen** [comment]
I can't reproduce this with the example code above by running the command line dart analyzer in neither strong mode nor spec mode.  Tested with 1.15.0 and 1.16.0-dev.4.0.  Closing this as stale, but if this still reproduces please re-open with more details (i.e. platform, exactly what sdk version you're using, any .analysis_options,  etc).
