### ISSUE TITLE
type 'UnixDomainAddress' is not loaded

### ISSUE THREAD

**Issue by StefanaCerovina** [dart-lang/sdk#26196]
Unhandled exception:
'package:fletchc/src/hub/hub_main.dart': malformed type: line 229 pos 40: type 'UnixDomainAddress' is not loaded
  server = await ServerSocket.bind(new UnixDomainAddress(socketFile.path), 0);
                                       ^

#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:56)
#1      main.<main_async_body> (package:fletchc/src/hub/hub_main.dart:229:40)
#2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#3      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#5      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
./fletch: Failed to start fletch server (Connection refused).
Use DART_VM environment variable to override location of Dart VM.

I have tried to build dartino on arm board, and use manually cross compiled dart on x64 machine. 

How can I build dart executable for arm platform, and use it for dartino project?

**Comment by mit-mit** [comment]
Hi @StefanaCerovina, regarding building Dartino, please see the instructions here:
https://github.com/dartino/sdk/wiki/Building

Also, please log Dartino issues in the Dartino issue tracker:
https://github.com/dartino/sdk/issues
