### ISSUE TITLE
More flow-based type refinements for strong-mode?

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#26195]
Within an `if (value is SomeClass)` block, `value` is inferred to be of type `SomeClass`. But negative `is!` test doesn't seem to get the same inference:

``` dart
class Foo<T> {
  void take(T s) {}

  void error(Object item) {
    if (item is! T) return;
    take(item); // Unsound implicit cast from Object to T
    // note: same result when using an "else" block.
  }
  void ok(Object item) {
    if (item is T) take(item);
  }
}
```

(tested with `dartanalyzer --strong` version 1.16.0-dev.2.0)

**Comment by jmesserly** [comment]
moving to language

**Comment by srawlins** [comment]
This has been replaced by https://github.com/dart-lang/language/issues/80 in the new language repo.
