### ISSUE TITLE
When precompiling gen_snapshot should have the option to output an object file instead of assembly file

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26199]
We'd like this behavior for Android where we don't necessarily have an assembler on the end-developers machine.

We'd just like the mmap the snapshot and execute it in this configuration.

@abarth @fsc8000

**Comment by abarth** [comment]
We've worked around this for now on Android, but end-developers won't be able to use AOT on Android until this bug is fixed because end-developers on Android don't have a toolchain that can compile assembly files.

/cc @iposva-google

**Comment by abarth** [comment]
See https://github.com/flutter/engine/pull/2614 for the workaround.

**Comment by rmacnak-google** [comment]
f262fad6396d7525b931010f0fd12487f19477d5
