### ISSUE TITLE
dart2js javascript functions defined by package:js functions not added to JavaScriptObject

### ISSUE THREAD

**Issue by jakuub** [dart-lang/sdk#26206]
# The problem: 
The methods not used directly in main were not added to `JavaScriptObject` and therefor caused the error when called from async function. The call of it is there, but it is not defined in `JavaScriptObject`.

# Scenario 
We run simplified version of flux. So on app initialization, there is components binded to DOM, initilaized stores(classes listening to dispatcher and manipulating with state) and one dispatcher (basicaly one stream and streamcontroller). 
When someone click on Login button, 

1. component will recognize this (we use [tiles](https://github.com/cleandart/tiles)), 
2. pass event to dispatcher (stream controller), 
3. this is filtered by `Login` store, 
4. which call function on our Auth0 helper class, 
5. which call javascript Auth0.login function. 

After there this is the "simplified stack" in compiled javascript
1. This call calls `J.login$2$x`, 
2. which calles `J.getInterceptor$x(receiver).login$2(receiver, a0, a1)`
3. `J.getInterceptor$x(receiver) `return `J.getNativeInterceptor(receiver)`
4. which return `C.UnknownJavaScriptObject_methods`
5. they are equal to `J.UnknownJavaScriptObject.prototype`
6. which don't contain `login$2`

When we added try-catch block to main with calling of all theese js functions, they were added to `JavaScriptObject`, so i expect, there is some problem with tree-shaking, which remove them.

**Comment by jacob314** [comment]
The bug causing this has been fixed in tip of trunk.

**Comment by jakuub** [comment]
And can I ask, in which version of sdk it will be? Thank you very much :smile:
