### ISSUE TITLE
Support for ipv6 in observatory

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#26205]
Currently Observatory connects to 127.0.0.1 and fails to start up in a ipv6 only environment.

**Comment by johnmccutchan** [comment]
@keertip I won't have time to look at this soon. I suggest adding support yourself. The code is here: [runtime/bin/vmservice/server.dart#L170](https://github.com/dart-lang/sdk/blob/master/runtime/bin/vmservice/server.dart#L170).

**Comment by rmacnak-google** [comment]
Continued as #27841
