### ISSUE TITLE
VM Service: spawned isolate has a pauseEvent type of None despite --pause-isolates-on-start

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26204]
When an isolate is spawned via `Isolate.spawn()`, the VM service reports its pause status as "None" even if `--pause-isolates-on-start` was passed. [Here's an inspector view](http://www.jsonmate.com/permalink/570567d6180f6b4d110f5066) of the Isolate JSON in which the pause event is "None".

This seems to have started some time between 1.15 and 9f43293.

The easiest way to reproduce this is probably to run `pub run test  test/client_test.dart -n 'onIsolateStart emits an event when an isolate starts'` in [`vm_service_client`](/dart-lang/vm_service_client).

See also dart-lang/vm_service_client#5

**Comment by nex3** [comment]
Thinking about this further, this is actually the right behavior; we probably just need to wait until the isolate is runnable for it to be paused.

**Comment by johnmccutchan** [comment]
@nex3 Yes, None is reported before the isolate could be paused (while sources are being loaded, etc).
