### ISSUE TITLE
Issue with refactor-rename on functions defined in a different file 

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#26207]
**Summary:**
Refactor-renaming a function identifier imported from another file does not work as expected. 
The function identifier in the definition gets renamed, but the references does not. Furthermore
the import declaration is changed to something non-sensical.

**What steps will reproduce the problem?**
1) In WebStorm, create a simple-commandline applikation
2) Create a file foo.dart with the following content
```
bar() {
    return 42;
}
```
3) Replace the contents of main.dart with the following:
```
import 'foo.dart';

main() {
    bar();
}
```
4) Refactor-rename the `bar` identifier to `baz` in main.dart
*Expected:*
    The `bar` identifier in main.dart and foo.dart is changed to `baz`.

*Actual:*
	Only the `bar` identifier in foo.dart is changed. Furthermore the import
	declaration in main.dart is changed to `import baz;`

**What version of the product are you using?**
Dart-sdk and dartium 1.16-dev.4.0

**Please provide any additional information below.**
This appears to have been introduced with 1.16-dev.0.0.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1896023005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/daed53916a5c21731cf909cb8a808e3f69b81b68
