### ISSUE TITLE
JSON Array not converted into Dart List in Dartium

### ISSUE THREAD

**Issue by mofirouz** [dart-lang/sdk#26209]
Scenario: I receive JSON data from a server through a `HttpRequest`. This JSON data is a top-level array similar to below:
```json
[
  {
    "key": "value"
  },
  {
    "key": "value"
  }
]
```

Under Dartium (and IntelliJ), the data I get back in my Dart code is of class `‌JSArrayImpl` and each of the  objects inside the array are of type `JSObjectImpl`. If I try this in Chrome, I get a `LinkedHashMap` back (which is the expected type).

To temporarily fix this, I've had to wrap the data I send from the server so the JSON is an object and not an array. 

Dartium Version: 45.0.2454.0 (64-bit)
Dart SDK: Dart VM version: 1.15.0 (Wed Mar  9 09:55:45 2016) on "macos_x64"
Angular2: Angular2 Beta 13.
Mac OS X 10.11

**Comment by alan-knight** [comment]
JsArrayImpl implements list, so that should be fine. New JS Interop by default wraps things as opaque JS  objects, but if we know we're expecting JSON back we should convert to a Map. May just need to insert a serializedScriptValue or other conversion on that.

**Comment by jacob314** [comment]
This is an issue of us missing a call to
convertNativeToDart_SerializedScriptValue in the latest version of
dart:html in Dartium.
While JSArrayImpl implements list, the elements will be opaque typed JS
interop objects instead of the Map objects you are looking for.

**Comment by jacob314** [comment]
This should be  fixed in Dartium dev 1.16.04 assuming you are referring to
accessing the response field of the HttpRequest.
If you are still seeing an issue with 1.16.04, file a bug with a repro and
I will investigate further.
https://www.dartlang.org/downloads/archive/
