### ISSUE TITLE
Editing doc comments does not cause a reanalyze

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#26216]
When editing a doc comment I have to manually trigger a reanalyze in order for the changes to show up when view the doc comment. 

I have seen this issue with the Atom plugin as well as WebStorm.

SDK: 1.15.0
Analysis server: 1.14.0
Atom Plugin: 0.6.9

**Comment by leafpetersen** [comment]
@scheglov was looking at something that might be related?

**Comment by scheglov** [comment]
https://codereview.chromium.org/1878243002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/a0375e55c1dd0cbb87e595da846984b6536a30fb
