### ISSUE TITLE
Suppress TODO info outputs in command line analyzer

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26215]
The analysis server generates [info] reports for TODO lines in source code.  IDEs can choose to surface these or not as they like.  The command line analyzer currently outputs these with the normal error/warning/hint stream unless --no-hints are specified, but most users suppress or filter these.  The command line analyzer should suppress these by default.

**Comment by zoechi** [comment]
I also find it confusing that 

> [info] TODO(zoechi) check how this j...

can be suppressed with 

    dartanalyzer --no-hints ...

Shouldn't it be 

> [hint] TODO(zoechi) check how this j...

or

    dartanalyzer --no-info ...

**Comment by pq** [comment]
Fixed w/ 082edc9fa325c5a13e05f7a03f967cbb03d6fecc.
