### ISSUE TITLE
Null aware operator throwing error

### ISSUE THREAD

**Issue by xaguzman** [dart-lang/sdk#26227]
Dart 1.15.0
I am using intellij idea plugin (latest)
tried on atom, same result

```dart
class WebGLRenderbuffer extends Renderbuffer{
  GLNative.Renderbuffer nativeRenderbuffer;
}

var a = new WebGLRenderbuffer();
a?.nativeRenderbuffer;
```

I keep getting an `'?' unexpected` error

**Comment by zoechi** [comment]
https://dartpad.dartlang.org/adcae1ef1806ed6769e1821039b8fd53

    a?.nativeRenderbuffer;

works when moved inside a function. Only const/variable, class, and function declarations are allowed at library-level.

**Comment by xaguzman** [comment]
I am calling it inside some getters.... I havent been able to post an update on this, I will try tonight.

(just posting to show Im still having an issue with this so it won't be closed!)

**Comment by mit-mit** [comment]
Tentatively closing this as we need more info, @xaguzman please add detail and reopen if you are still seeing an issue

**Comment by xaguzman** [comment]
so ... i was actually able to compile the code...I was using itellijidea 14, which seems to not be using the latest version plugin...

Switched to intellijidea 16 and everything is working fine now!

Sorry for the confusion!
