### ISSUE TITLE
VM: MegamorphicLookup #6: mixin pattern

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26222]
This issue is split out from https://github.com/dart-lang/sdk/issues/26017

In dart2js,  ElementX.isField is defined by a mixin 

```
class ElementCommon {
   bool get isField => kind == ElementKind.FIELD;
}
```

get:kind is defined in various places, leading to a MegamorphicLookup from the mixin code.
If get:isField was cloned to the classes defining get:kind, then get:kind could be inlined.
get:kind is usually a field (on ElementX) or a returns a constant.

**Comment by fsc8000** [comment]
Duplicate of #26858
