### ISSUE TITLE
Conditional member access with index operator

### ISSUE THREAD

**Issue by tewalds** [dart-lang/sdk#26229]
I'd like to be able to use the conditional member access operator along with the index operator.

```dart
void main() {
  var m = rand() ? {'asdf': 3} : null;
  print(m?.containsKey('asdf'));  // works
  print(m?.['asdf']);  // compile error
  print(m ? m['asdf'] : null);  // closest approximation of what it should do.
}
```

An alternative would be just to create a `get` method such that m?.get('asdf') would work.

This would be particularly useful in parsing large json trees.

**Comment by leafpetersen** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/28389 .
