### ISSUE TITLE
VM: String.== inlining and code issues

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26234]
_OneByteString.== is often inlined, sometimes leading to slower code.

E.g. in dart2js, *SourceLocation.== calls *Uri.==
*Uri.== inlines calls to _OneByteString.==, inlining one step, leaving a call to _StringBase.==

```
class _OneByteString extends _StringBase implements String {
  ...
  bool operator ==(Object other) {
    return super == other;
  }
```

_StringBase.== has worse code that _OneByteString.== because (1) there is no intrinsifier (2) _StringBase.== is polymorphic in both receiver and argument (_OneByteString/_TwoByteString), so each iteration of the code unit comparison loop has a dispatch on each string type.

---

In Dartium, the code in the _StringBase.== loop is much worse.  Each call to  other.codeUnitAt(i) has a 4-way dispatch to four calls to _StringBase.codeUnitAt. I'm not sure why these are not lowered to indexed load instructions.  The _StringBase.codeUnitAt intrinsifier does a second dispatch to indexed load instructions, but has no path for externalized strings, leading to entering the runtime.

```
0x7f727edaf04b			push [rbp+0x10]	
0x7f727edaf04e			push [rbp-0x18]	
0x7f727edaf051			movq rax,[rsp+0x8]	
0x7f727edaf056			movq r10,[r15+0x17]	_ImmutableList (3) {  ⊞  }
0x7f727edaf05d			test al,0x1	
0x7f727edaf05f			jz 0x7f727edaf237	
0x7f727edaf065			movl rdi,[rax+0x3]	
0x7f727edaf068			cmpl rdi,0x45	
0x7f727edaf06b			jnz 0x7f727edaf087	
0x7f727edaf071			movq r12,[r15+0x1f]	_StringBase.codeUnitAt
0x7f727edaf078			movq r11,[r12+0x7]	
0x7f727edaf07d			call r11	
0x7f727edaf080			pop rcx	
0x7f727edaf081			pop rcx	
0x7f727edaf082			jmp 0x7f727edaf0df	
0x7f727edaf087			cmpl rdi,0x43	
0x7f727edaf08a			jnz 0x7f727edaf0a6	
0x7f727edaf090			movq r12,[r15+0x1f]	_StringBase.codeUnitAt
0x7f727edaf097			movq r11,[r12+0x7]	
0x7f727edaf09c			call r11	
0x7f727edaf09f			pop rcx	
0x7f727edaf0a0			pop rcx	
0x7f727edaf0a1			jmp 0x7f727edaf0df	
0x7f727edaf0a6			cmpl rdi,0x44	
0x7f727edaf0a9			jnz 0x7f727edaf0c5	
0x7f727edaf0af			movq r12,[r15+0x1f]	_StringBase.codeUnitAt
0x7f727edaf0b6			movq r11,[r12+0x7]	
0x7f727edaf0bb			call r11	
0x7f727edaf0be			pop rcx	
0x7f727edaf0bf			pop rcx	
0x7f727edaf0c0			jmp 0x7f727edaf0df	
0x7f727edaf0c5			cmpl rdi,0x46	
0x7f727edaf0c8			jnz 0x7f727edaf237	
0x7f727edaf0ce			movq r12,[r15+0x1f]	_StringBase.codeUnitAt
0x7f727edaf0d5			movq r11,[r12+0x7]	
0x7f727edaf0da			call r11	
0x7f727edaf0dd			pop rcx	
0x7f727edaf0de			pop rcx	
0x7f727edaf0df			movq rcx,[rbp-0x28]	
```

**Comment by rakudrama** [comment]
Adding the 2016Q1 CY label.
I extended the intrinsifier for _StringBase.codeUnitAt to handle external strings (https://chromiumcodereview.appspot.com/1868323002/).
I ran a table sorting workload on Dartium.
The change eliminates the 11% of time spent in Native String_codeUnitAt and total ticks by 13%.

Open to discussion, but what I think should be done:

- [ ] Extend intrinsifiers for _StringBase.codeUnitAt to cover all kinds of string (all architectures).

- [ ] Fully intrinsify String.==

- [ ] Understand why the crazy 4-way dispatch above happens and fix it (either generate indexed loads or just call _StringBase.codeUnitAt once. I have found this pattern inlined up the call chain into ~20 callers)

- [ ] Revisit the  __super == other__ definitions on subclasses. Most strings can be found not-equal on the basis of length without knowing the kind of string. Perhaps the == operation can be factored into a type and length test that gets inlined and an intrinsified body test that is not inlined.

**Comment by rakudrama** [comment]
This is the CL I used to get the 11% speedup: https://chromiumcodereview.appspot.com/1868323002/
While this is probably worthwhile on its own, it does seem like a symptom of a problem with ==.

**Comment by fsc8000** [comment]
There seems to be an underlying issue with inlining. I'll take a look.

Independent of that, I think the intrinsic code would be good to have.

**Comment by fsc8000** [comment]
Re intrinsics: I uploaded https://codereview.chromium.org/1961393002/ which handles all string types for codeUnitAt.

@rakudrama How can I test if I also get the reported 11% speedup?

**Comment by fsc8000** [comment]
Closing this as the original biggest performance bottleneck (runtime call) has been fixed.
