### ISSUE TITLE
Dartium crashes when trying to load element properties in 'Developer Tools'

### ISSUE THREAD

**Issue by Hypuk** [dart-lang/sdk#26238]
Dartium crashes with 'Inspected target disconnected' error when trying to view properties of any element in 'Developer Tools' window.

Steps to reproduce:
1. Go to any https://www.google.co.uk
2. Right click on any element -> Inspect element
3. Select 'Properties' tab

The following error is shown in dartium:
![dartium_bug](https://cloud.githubusercontent.com/assets/1088379/14424576/d399f950-ffd9-11e5-8204-24b004ce16c6.png)

The following error is shown in console:

```
[1397:1397:0411/113737:ERROR:renderer_main.cc(200)] Running without renderer sandbox
V8 error: Cannot create a handle without a HandleScope (v8::HandleScope::CreateHandle()).  Current memory usage: 31 MB
```

**Comment by terrylucas** [comment]
Please retry with Dart 1.24.2 Stable (Dartium 50)
