### ISSUE TITLE
Deferred Loading in a Part throws "Cannot find reflection information on <myClass>" error

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#26239]
If I try to load a deferred source inside a Part I get an "Cannot find reflection information on <myClass>" error.

in the main source:

```
...
import 'package:<myPackage>/<myClass>.dart' deferred as def_class;
...
part 'parts/partClass.dart';
.....
//await def_class.loadLibrary();  // If I remove the comment it works;
await <PartClass>.init();

```

in the part source:

```

part of main;

class PartClass {

  static init() async {

    await def_class.loadLibrary(); 
    def_class.<MyClass>.doAction();
   }
}
```

Am I doing something wrong?

**Comment by kevmoo** [comment]
@giorgiofran is this within a server/console app or a web app?

**Comment by giorgiofran** [comment]
In a Web App.

**Comment by kevmoo** [comment]
@giorgiofran Are you seeing this error when running it in Dartium, Chrome, or both?

**Comment by giorgiofran** [comment]
In Dartium. 
I have not yet tested in Chrome.

**Comment by alan-knight** [comment]
That error is coming from Angular. It's not clear to me that it has anything to do with Dartium. I'd say try it with dart2js. And possibly file something with Angular to see if they have more information.
