### ISSUE TITLE
Class member access on instantiation

### ISSUE THREAD

**Issue by mfrancis107** [dart-lang/sdk#26236]
It would be nice to be able to immediately call a method after instantiation.

As of right now you have to call methods on the variable like the below example.
```dart
var b1 = new Box();
b1..scale(x: 2)
    ..move(y: **4);
```

It'd be nice to be able to do this.
```dart
var b1 = new Box()
        ..scale(x: 2)
        ..move(y: 4);
```

**Comment by zoechi** [comment]
Works fine https://dartpad.dartlang.org/9c49c6d8d439fc9029b092b1614532a2

What error did you get?

**Comment by mfrancis107** [comment]
Closing this issue. Can't replicate. Must have been a symptom of working too late.
