### ISSUE TITLE
New quick assist: conversion between getters and final fields

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26249]
Would be great to have a quick assist to convert getter to final field and vice versa.

*Originally filed by @Andersmholmgren in [WebStorm's issue tracker](https://youtrack.jetbrains.com/issue/WEB-20438)*

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2144763002

**Comment by scheglov** [comment]
Getters to final fields is landed.
https://github.com/dart-lang/sdk/commit/f1fa32e3563c29a8abccb77bf79b3b4320dae204

**Comment by scheglov** [comment]
https://codereview.chromium.org/2140193003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/79f7150d9709ce85d8b07771af9a05343fe065cd
