### ISSUE TITLE
Error using pub behind corporate proxy

### ISSUE THREAD

**Issue by Tom18** [dart-lang/sdk#26245]
Following recommendation on windows shell after running "pub get" (see attachment):

Resolving dependencies...
Proxy failed to establish tunnel (407 Proxy Authentication Required)
package:pub/src/source/hosted.dart 249  HostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 75   HostedSource.doGetVersions.<async>
dart:async                              _Completer.completeError
package:http/src/base_client.dart 175   BaseClient._sendUnstreamed.<async>
dart:async                              _Completer.completeError
package:pub/src/http.dart 108           _PubHttpClient.send.<async>

**This is an unexpected error. Please run

```
pub --trace get
```

and include the results in a bug report on http://dartbug.com/new**

.

[unexptected_error.txt](https://github.com/dart-lang/sdk/files/214677/unexptected_error.txt)

**Comment by zoechi** [comment]
See dart-lang/pub#1359

**Comment by Tom18** [comment]
I had read your thread to this topic before I started my thread. According to your suggested solution I had set the system environment variables. Nevertheless, I received the error message on the console as mentioned above. 
My env variables look like the following pattern, since the proxy server expects credentials:
http_proxy=<username>:<pwd>@<host>:<port>/
https_proxy=<username>:<pwd>@<host>:<port>/
