### ISSUE TITLE
analyzer does not warn on unused imports when only use is from exported dart:core

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#26242]
Take the following:

```
import 'package:angular2/angular2.dart';

String heyo;
```

The analyzer does not warn on UNUSED_IMPORTS, because angular2.dart exports a file somewhere that exports `dart:core`. Boo.
### Solutions

When examining an element in a library to see what importDirective it came from, and thus deciding that said importDirective is used:
#### 1. Don't count an element that was exported by a library, but belongs to another library in another package.

I acknowledge that some packages top-level Dart file exports other package files (take package:test/test.dart, which [exports package:matcher/matcher.dart](https://github.com/dart-lang/test/blob/master/lib/test.dart#L18)). To be honest I'm kind of not into it. I think it is a smell to export files from another package...

If that is too harsh:
#### 2. Don't count a `dart:*` element that was exported by a library.

I think this is super duper reasonable. If _this_ is even to strict:
#### 3. Don't count a `dart:core` element that was exported by a library.

What do you think?

**Comment by bwilkerson** [comment]
> 1. Don't count an element that was exported by a library, but belongs to another library in another package.

Unless that was the only reason the name was visible? If someone imports library foo.dart, which exports a name defined in bar.dart, but doesn't import bar.dart then we can't report that foo.dart isn't being used, because it is. Removing it would break the code.

> 2. Don't count a dart:* element that was exported by a library.
> 3. Don't count a dart:core element that was exported by a library.

If someone imports foo.dart, which exports `dart:core`, and has a prefix on the import, and references core classes using the prefix, then removing the import would break the code.

> What do you think?

I think it's a difficult question and I'm not sure it happens often enough to be worth a lot of effort, but I might be wrong.

Our general approach (IIRC) is to assume that the name is being imported by the first import that contributes the name. Of course, that's hard for `dart:core` when it's implicit because I don't know where to insert it. I suspect that it's assumed to be the last import. Perhaps it would work better if it were assumed to be the first import (when it's implicit).

**Comment by srawlins** [comment]
> If someone imports foo.dart, which exports dart:core, and has a prefix on the import, and references core classes using the prefix, then removing the import would break the code.

Oh, I definitely understand that it might break the code to remove the import. I think that the correct imports should be added explicitly. You would only get an UNUSED_IMPORT warning if the _only_ thing you got out of that import was `dart:core as prefix`. I think we should definitely warn on that.

Even here: if you `import package:test/test.dart`, but you only use `matcher`, then you shouldn't be importing `test.dart`; you should be importing `matcher/dart`.

I take your point, however, that currently, you can remove any UNUSED_IMPORT imports, and your code will work great. This change would break from that. Maybe this is more like an INNEFFICIENT_IMPORT, or UNNECESSARILY_COMPLICATED_IMPORT. :tongue: Especially because of the implementation detail that if I want a different message, then I need a different HintCode.

I hate the idea of code growing stale, importing big ole' projects, unkowingly only because they export _other_ projects.

I wonder if we can also be looser with HintCodes, in how/why we implement them.

**Comment by srawlins** [comment]
ie. I'd love the following message:

> "package:angular2/angular2.dart" is imported, but only "package:else/else.dart" is used here. Use "import 'package:else/else.dart';" instead. [WEIRD_IMPORT]

**Comment by bwilkerson** [comment]
I like the idea of making this a different check (and I'd probably suggest a lint, because it's more a stylistic preference than a bug). That would also allow us to add a very targeted quick fix.

> I wonder if we can also be looser with HintCodes, in how/why we implement them.

Looser how?

**Comment by srawlins** [comment]
CR out for review: https://codereview.chromium.org/1885753003

I think this is an important warning to include. I found hundreds of instances of violations of this warning. Essentially: you think you've cleaned up a codebase of it's unused imports, only to find that you missed unused `package:angular2/angular2.dart` and `package:collection/collection.dart` imports, because their importers declared a String or a Map somewhere. This new warning takes care of that.

> Looser how?

Just thinking out loud. nevermind.

**Comment by srawlins** [comment]
Angular's been fixed. Can close this.
