### ISSUE TITLE
Generators may be really slower than in JS

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#26241]
Here is an implementation of the sieve of Eratosthenes﻿ :

```dart
/// generate an Iterable of natural number starting from [n]
Iterable<int> from(int n) sync* {
  yield n;
  yield* from(n + 1);
}

/// filter the [source] to skip the multiple of first element (that is a prime number)
Iterable<int> sieve(Iterable<int> source) sync* {
  final prime = source.first;
  yield prime;
  yield* sieve(source.skip(1).where((e) => e % prime != 0));
}

Iterable<int> get primes => sieve(from(2));

main() {
  for (int n = 10; n <= 200; n += 5){
    final sw = new Stopwatch()..start();
    primes.take(n).toList();
    print('$n => ${sw.elapsedMilliseconds}');
  }
}
```

With the DartVM 1.15.0 the follow last output lines are displayed :

```
190 => 4073
195 => 4508
200 => 5050
```

In other words, **the DartVM 1.15.0 takes 5050ms to get the 200 first prime numbers**.

I translated the above code in the following JS code :

```js
function* from(n) {
  yield n;
  yield* from(n + 1);
}

function* filter(it, predicate) {
  while (true) {
    let value = it.next().value;
    if (predicate(value)) yield value;
  }
}

function* sieve(it) {
  let prime = it.next().value;
  yield prime;
  yield* sieve(filter(it, function(e) { return e % prime !== 0; }));
}

function* primes() {
  yield* sieve(from(2));
}


for (var n = 10; n <= 200; n += 5) {
  var start = performance.now();
  var pIt = primes();
  var r = [];
  for (var i = 0; i < n; i++) {
    r.push(pIt.next().value);
  }
  var end = performance.now();
  console.log(n + " => " + (end - start));
}
```

In Chrome 49.0.2623.110 (64-bit) **the js version takes less than 200ms to get the 200 first prime numbers**.

On Dart Pad, the dart version compiled to js takes more than 8000ms to get the 200 first prime numbers.

**Comment by rakudrama** [comment]
There is a subtle difference between the Dart and JS versions.

In JavaScript, generators (function*) produce values that are iterators. In Dart, sync* methods return Iterables, i.e. generators. The dart methods skip, where, etc are generator combinators.
This means it is (too) easy to construct compound iterables that re-evaluate expressions.

```
Iterable<int> sieve(Iterable<int> source) sync* {
  final prime = source.first;
  yield prime;
  yield* sieve(source.skip(1).where((e) => e % prime != 0));
}
```

Each recursive call to sieve constructs a bigger and bigger Iterable/generator that is re-evaluated from scratch for __source.first__.
What is missing is an operation that returns the first item and the remainder of the same partially evaluated iterable. We can fake this by wrapping the iterator.

The nearest I can write in Dart to the JS code you wrote is:

```
/// filter the [source] to skip the multiple of first element (that is a prime number)
Iterable<int> sieve(Iterable<int> source) sync* {
  Iterator it = source.iterator;
  it.moveNext();
  final prime = it.current; //  was 'source.first';
  yield prime;
  yield* sieve(new OneShot(it).where((e) => e % prime != 0)); 
}

class OneShot<T> extends IterableBase<T> {
  Iteravar _iterator;
  OneShot(this._iterator);

  Iterator<T> get iterator {
    var result = _iterator;
    _iterator = null;
    if (result == null) throw "Re-use of one-shot Iterable";
    return result;
  }
}
```

With this change performance is approximately the same as JavaScript

**Comment by rakudrama** [comment]
I am closing this issue because there is not much difference to JS performance once the programs do the same thing.

---
This CL will speed things up in dart2js and dartpad: https://chromiumcodereview.appspot.com/1873413002/

---
As I mentioned above, for your kind of iterable-as-stream programming, you must avoid re-evaluating the iterable. A nice way to do this is to memoize the iterable:

```
Iterable<int> sieve(Iterable<int> source) sync* {
  source = new MemoizedIterable<int>(source);  // Do this because 'source' is used more than once.
  final prime = source.first;
  yield prime;
  yield* sieve(source.skip(1).where((e) => e % prime != 0));
}
```

Now it takes 15ms.

```
import 'dart:collection';


class MemoizedIterable<T> extends IterableBase<T> {
  Iterator<T> _iterator;  // null if [_first] and [_rest] valid.
  T _first;
  MemoizedIterable<T> _rest;  // null when empty.

  MemoizedIterable._(this._iterator);

  factory MemoizedIterable(Iterable<T> iterable) {
    if (iterable is MemoizedIterable) {
      return iterable;
    }
    return new MemoizedIterable<T>._(iterable.iterator);
  }

  Iterator<T> get iterator => new MemoizedIterableIterator<T>(this);

  bool _moveNext() {
    if (_iterator == null) {
      return _rest != null;
    }
    if (_iterator.moveNext()) {
      _first = _iterator.current;
      _rest = new MemoizedIterable<T>._(_iterator);
      _iterator = null;
      return true;
    }
    return false;
  }
}


class MemoizedIterableIterator<T> implements Iterator<T> {

  MemoizedIterable<T> _iterable;
  T _current;

  MemoizedIterableIterator(this._iterable);

  T get current => _current;

  bool moveNext() {
    if (_iterable == null) return false;
    bool result = _iterable._moveNext();
    _current = _iterable._first;
    _iterable = _iterable._rest;
    return result;
  }
}
```

**Comment by a14n** [comment]
Thank you for your help and your explanations. It also explains the issue #24032 I filed a while back.

I expected that the behaviour of `sync*` was a sort of memoized iterable but my assumptions seemed to be wrong.

Thinking about this current behaviour I don't really understand why it is done like that (re-evaluate on every call instead of memoizing) and I can't find a use-case where this behaviour would be what I want. Moreover, I see more and more code using `sync*` and `yield` to generate `Iterable` and it could be a big performance killer IIUC.

**Comment by lrhn** [comment]
A memoized iterable is only ever iterated once - after that you iterate the recording instead of the original. That makes it computationally cheap to re-iterate the same values, but it is memory-expensive to remember them. It's a trade-off that you can then make, which you couldn't if all iterables were memoizing.

If the iterable is a view of another iterable, say `var males = people.where((p) => p.isMale);`, then you want the current members of `people`, not the ones that were there when you iterated it the first time (and memoizing a mutable collection will almost certainly give a concurrent modification error at some point).

The design was to make the wrappings on iterables lazy because that's what works best for wrapped collections. That also means that the wrapping is executed every time you iterate.
