### ISSUE TITLE
Analyzer should show an error if operator== is defined but not "hashCode"

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#26259]
It's mandatory that, if you overwrite operator==, you also overwrite "hashCode"

**Plus:** Please add something like hash2/hash3... to one of the core libs. It's annoying to add quiver just for this.

**Comment by zoechi** [comment]
See also #dart-lang/linter#84

**Comment by zoechi** [comment]
Actually this part should already be implemented 

dart-lang/linter#168

if you add this to `.analysis_options`
```yaml
linter:
  rules:
    - hash_and_equals
```

**Comment by alexeieleusis** [comment]
friendly ping, as @zoechi points, this should be closed since this lint exists

**Comment by MikeMitterer** [comment]
:+1: Tanks
