### ISSUE TITLE
Clarify treatment of `endGroup` in dart2js parser

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26252]
The dart2js parser uses several constructs on the form `someToken.endGroup.foo` for some selector `foo` where it may or may not be guaranteed that `someToken.endGroup` is non-null. If it is guaranteed that `someToken.endGroup` is non-null (in particular when `someToken` is known to be an `OPEN_PAREN_TOKEN`) then some null checks can be removed, and if it may be null then some extra checks seem to be needed.

**Comment by peter-ahe-google** [comment]
The scanner ensures that `endGroup` is always non-null, even if there's an error.

**Comment by peter-ahe-google** [comment]
Well, unless you're looking at:

    a < 2
