### ISSUE TITLE
Dart analyzer stalls when editing inside html script tag 

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#26257]
**Summary:**
There is an issue with the dart-analyzer becoming unresponsive when editing dart-code in an html-document using WebStorm.
After the analyzer has run a few times it will take an increasing amount of time to analyze even simple functions, untill eventually it will stop responding and the 'Dart analysis' progress-spinner continues (seemingly) forever.

**What steps will reproduce the problem?**
1) Open Webstorm and create an Uber Simple Web Application
2) Open index.html and add the following to the body

```
<script type="application/dart">
main() {
  var foo = 42;
}
</script>
```

4) Open the Dart-Analysis window-pane to observe any issues that the analyzer is reporting
5) Repeatedly make a few changes to the program (e.g. remove the line `var foo = 42;`) and type it again), while verifying that the 'Dart-analysis' continues to report on issues it finds within program

_Expected:_
The 'Dart-analysis' window continues to update whenever the program is changed, i.e. it displays error-messages and then removes them when the issue is resolved.

_Actual:_
The dart-analyzer takes an increasingly long time to analyze the program, until it becomes completely unresponsive.

**What version of the product are you using?**
Webstorm: 2016.1.1
Dart-SDK: 1.16.0-dev.5.0

**Additional info**
This issue also occurs with dart-1.15-stable

**Comment by alexander-doroshko** [comment]
I can confirm the bug. In case of Dart in HTML editing Analysis Server sends
```
1460626511817:Noti:{"event"::"server.status","params"::{"analysis"::{"isAnalyzing"::true}}}
```
and never sends `{"isAnalyzing"::false}` afterwards, that's why IDE shows that analysis is in progress.
Also server stops sending any information to the IDE after some time.

**Comment by bwilkerson** [comment]
I assume that this is obsolete because we no longer analyze Dart code in HTML files.
