### ISSUE TITLE
Please merge revision 4bed72be27baace2473553dc282a847679191dfe into dev channel

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26269]
@whesse @mit-mit @kasperl

This fixes a bug wherein `pub serve` would serve stale content.

Please merge 4bed72be27baace2473553dc282a847679191dfe

https://codereview.chromium.org/1890913004 merges this cleanly. All pub tests pass.

**Comment by whesse** [comment]
The deletion of protobuf_tag in the supplied CL seems like a mistake.  Both tip-of-tree master and dev have the line, and the CL that is being merged doesn't delete it.  Applying the CL without the change to protobuf_tag.

**Comment by whesse** [comment]
Merged in 1.16.0-dev.5.1
