### ISSUE TITLE
Counter intuitive behavior of extends clause in Strong Mode

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#26276]
```dart
typedef EventListener<E extends Event>(E event);

EventListener foo;
```
I would expect foo to have function type 
```dart
(Event e) => dynamic
```
but it actually has type
```dart
(dynamic e) => dynamic 
```
which is consistent with existing dart but inconvenient for strong mode.
This blocks extending the existing EventListener typedef to support generics.

**Comment by jmesserly** [comment]
yeah that's a bug. I think we have it filed somewhere that we don't always instantiate things to bounds correctly.

**Comment by jmesserly** [comment]
Ah, it was fixed already for interface types: https://github.com/dart-lang/sdk/issues/25877

**Comment by scheglov** [comment]
If this was already fixed, then I think we should close it.

**Comment by jmesserly** [comment]
yeah, I wasn't sure if @jacob314 was seeing a different bug that happens with typedefs (FunctionTypeAliasElement & FunctionType), or wasn't on a new-enough SDK to see the fix (that was originally for ClassElement & InterfaceType).
