### ISSUE TITLE
observatory: ia32 disassembly references unclickable

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26277]
Sometimes the only way to navigate to optimized methods is to find them in the disassembly of a caller (or in a megamorphic cache referenced in the instructions of a caller).

On x64, the call sequence contains the object (optimized function or cache), allowing navigation.
On ia32, the disassembly contains text describing the object.

**Comment by iposva-google** [comment]
> Sometimes the only way to navigate to optimized methods...
@rakudrama Why does the Library->Class->Method->OptimizedCode sequence not work for you to get at the code for an optimized method?

**Comment by rakudrama** [comment]
@iposva-google I don't know why, but it is not a reliable way to get to the optimized code.
What you suggest usually works, but I have definitely picked a function of the cpu profile, found it to be unoptimized, visited the parent from the cpu profile and found a call to the optimized (*) version.

Is it possible that code is deoptimized via one path (so I see the unoptimized version) but the pointers to the optimized code are still present in some ICData, megamorphic cache, PP slot? It would make sense to use the more specialized versions until it hit a deoptimization exit.

I have not thought to check if this happens only with deoptimized code.

**Comment by johnmccutchan** [comment]
@rmacnak-google This isn't supported for ia32 is it?

**Comment by rmacnak-google** [comment]
The strings are an old feature of the disassembler that predates Observatory. The links are a new feature that was only implemented for the ObjectPool architectures. On IA32 we already track the pc offsets of object references for use by the GC, so adding the links should be straightforward.

**Comment by rakudrama** [comment]
The strings can be useful for understanding printed disassembly.
Perhaps the disassemblers could be refactored to have one piece of code
that captures the referenced or embedded object, with an option to print it
or save it for the Observatory disassembly.

**Comment by johnmccutchan** [comment]
unassigning myself because I have no plans to improve IA32 disassembly.
