### ISSUE TITLE
Dart query-selector does not recognize custom attributes if appended dynamically

### ISSUE THREAD

**Issue by drmovi** [dart-lang/sdk#26272]
```
document.querySelector('body').appendHtml('<div lc="any-value" ></div>');
expect(document.querySelector('[lc="any-value"]'), isNotNull);
```

this test fails because querySelector does not recognize custom attributes. any idea 
note that i use the dartium to test this append functionality not the vm alone

**Comment by zoechi** [comment]
You need to provide a `validator` or `treeSanitizer` to get custom attributes added.

[**DartPad example**](https://dartpad.dartlang.org/1a0eedd613004e81b99c60c9c7a93d79)

import 'dart:html';

class NullTreeSanitizer implements NodeTreeSanitizer {
  void sanitizeTree(Node node) {}
}

```dart
main() {
  document.querySelector('body').appendHtml('<div lc="any-value" >xxx</div>', treeSanitizer: new NullTreeSanitizer());
  if(document.querySelector('[lc="any-value"]') == null) {
    throw 'failed';
  }
  print('found');
}
```

I assumed there was such a `NullTreeSanitizer` added to the SDK recently but wasn't able to find it. Maybe someone else can point us to it or my memory might be flawed.

**Comment by drmovi** [comment]
thanks it works fine

**Comment by alan-knight** [comment]
The one added to the SDK was ```NodeTreeSanitizer.trusted```

And it does much better than writing your own because the SDK recognizes it and bypasses the sanitization altogether. So you'd better be sure that the html is trusted.
