### ISSUE TITLE
Annoying case where type is not inferred even though there is a single assignment calling a constructor

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#26278]
```dart
   var  controller; // Changing this to " StreamController<Geoposition> controller" results fixes the warning that controller.stream has type dynamic.
    controller = new StreamController<Geoposition>(sync: true,
      onListen: () {
        assert(watchId == null);
        watchId = _watchPosition(
            (position) {
              controller.add(_ensurePosition(position));
            },
            (error) {
              controller.addError(error);
            },
            options);
      },
      onCancel: () {
        assert(watchId != null);
        _clearWatch(watchId);
      });

    return controller.stream;
```

**Comment by bwilkerson** [comment]
@vsmenon What do you think: are we likely to address this? So far we are only inferring types for untyped variables based on the initializer. If we decide to go further, how much further? For example:

    var pi;
    if (supportsFloats) {
      pi = 3.14;
    } else {
      pi = 3;
    }

**Comment by vsmenon** [comment]
It's not on our short term list.

There has been some discussion on a unification-based type inference.  That's a pretty big change though.

@leafpetersen is there a better tracking bug for this?

**Comment by leafpetersen** [comment]
Short term I don't see this being addressed.  I'm inclined to just to close this out.  We are very aware of the limitations of the existing inference, and decided exactly what form of inference to support is very much on the radar for the language team.  I don't see much value in a tracking bug.  If anyone disagrees, feel free to file a general language bug for tracking type inference work and reference this.
