### ISSUE TITLE
dartlang and pub give http error 403  in iran 

### ISSUE THREAD

**Issue by iraj-jelo** [dart-lang/sdk#26274]
dartlang and  `pub get` give `http error 403` in iran. we have to use proxy for watching `dartlang.org` website or uising  `pub get` in comand line.  this error comes from google hosts and Boycotted and sanctioned by google against iranian ip

```
Resolving dependencies... (1.4s) 
HTTP error 403: Forbidden
package:pub/src/source/hosted.dart 249  HostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 75   HostedSource.doGetVersions.<async>
dart:async                              _Completer.completeError
package:http/src/base_client.dart 175   BaseClient._sendUnstreamed.<async>
dart:async                              _Completer.completeError
package:pub/src/http.dart 108           _PubHttpClient.send.<async>
This is an unexpected error. Please run

    pub --trace get

and include the results in a bug report on http://dartbug.com/new.
```

**Comment by kevmoo** [comment]
I'm not sure what we can do if the domain is blocked by an ISP – or country.

@iraj-jelo do you have a specific request or suggestion?

**Comment by iraj-jelo** [comment]
@kevmoo the domain is blocked by google hosting for all iranian (ip)s, i would like to write persian posts in my blog for persian countris like iran, afghanestan, tajikestan, ... , but i am afraid iranian ppl (80 melion ppl) will have problem from google side :) i suggest you to change 'pub' server with a server or host which doesn't have any limitation for nobody in the earth

**Comment by iraj-jelo** [comment]
notice:  `dartlang.org` isn't blocked by an iranian ISP or iranian government. we are blocked from google side for some services which hosted on some google servers.

**Comment by kevmoo** [comment]
@iraj-jelo I'm sorry. It seems that App Engine – which our pub site runs on – is blocked in Iran.

See https://support.google.com/a/answer/2891389?hl=en
And https://code.google.com/p/googleappengine/issues/detail?id=4537

Sadly, we're limited to what App Engine can do.
