### ISSUE TITLE
Punycode not supported in dart sdk

### ISSUE THREAD

**Issue by tomas234** [dart-lang/sdk#26284]
Conversation to and from punycode is not part of the sdk. This means http server can not access urns with international characters.

**Comment by kevmoo** [comment]
@tomas234 Sounds like you'd like support in the URI class, specifically?

**Comment by zoechi** [comment]
Just for reference https://github.com/vadimtsushko/punycode
It's not published on pub

> 
vadimtsushko [13:49] 
@tomas259 I think you are right, it should be easier to use it as a dart package. Take a look at https://github.com/vadimtsushko/punycode

**Comment by tomas234** [comment]
For me the problem is solved with @vadimtsushko code.
