### ISSUE TITLE
Dartium useing querySelector('#any').remove() throw The null object does not have a method 'remove'.

### ISSUE THREAD

**Issue by drmovi** [dart-lang/sdk#26281]
first i append a div with id="any" using the following

`document.querySelector('body').appendHtml('<div id="any"></div>');`

 then use the following to remove it

`querySelector('#any').remove();`

result of my test is
The null object does not have a method 'remove'.
I'm using webstorm and dart test package with dartium , what's wrong ?

**Comment by zoechi** [comment]
Looks like the same issue you created 2 days ago #26272

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
For support questions please use other channels like the ones listed in https://www.dartlang.org/support/

**Comment by drmovi** [comment]
thx i'll close it
