### ISSUE TITLE
Implement super property extraction  and super closurization

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26287]
Please implement  super property extraction  and super closurization (like super#m), described in "16.18.2 Super Getter Access and Method Closurization" and "16.18.10 Super Closurization" of Dart Language specification, 4th Edition / December 2015

Please, update co19 .status files when complete

**Comment by kevmoo** [comment]
@floitschG What's our story here?

**Comment by floitschG** [comment]
Given that it's easy to just write `super.m` (for functions) and `() => super.m` (for getters), I don't think there is lot of pressure to implement it anytime soon.

It is in the spec, though, so in theory the implementations (VM / dart2js) should implement it.

I don't think it's just `super#m`, though, but all `o#m`.

**Comment by munificent** [comment]
Generalized tear-offs are being removed (#27518) so I don't think we have to worry about this.
