### ISSUE TITLE
Analyzer doesn't detect deprecated variables

### ISSUE THREAD

**Issue by aaronstgeorge-wf** [dart-lang/sdk#26297]
I would assume this should create an analysis warning.
```dart
@Deprecated('')
List<String> stringList;

void main() {
  print(stringList);
}
```

**Comment by scheglov** [comment]
Works for me.
![image](https://cloud.githubusercontent.com/assets/384794/18319904/8e6d80e0-74dc-11e6-969f-99f946a5d3f7.png)

**Comment by aaronstgeorge-wf** [comment]
Seems to work in 1.19.0 🎆
