### ISSUE TITLE
Analyzer doesn't detect duplicate named parameter in constructor

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#26296]
For example, in DartPad, no diagnostics appear for this case:

```
class Foo {
  final bool bar;
  Foo({this.bar, bar});
}
```

**Comment by bwilkerson** [comment]
Is it suppose to? According to the specification:

> Using an initializing formal this.id in a formal parameter list does not introduce a formal parameter name into the scope of the constructor.

I think this is working as expected.

**Comment by skybrian** [comment]
Here's a more complete example:

```
class Foo {
  final bool bar;
  final bool baz;
  Foo({this.bar, bar}) : baz = bar;
  toString() => "Foo($bar, $baz)";
}

main() {
  print(new Foo(bar: true));
}
```

It works in Dartpad (the parameter gets assigned to both fields), but the Dart VM doesn't allow it:

$ dart ~/tmp/test.dart 
'file:///Users/skybrian/tmp/test.dart': error: line 4 pos 18: duplicate formal parameter 'bar'
  Foo({this.bar, bar}) : baz = bar;

If it's not an analyzer bug, perhaps it's a VM bug?

**Comment by bwilkerson** [comment]
We need clarification on the specification.

**Comment by eernstg** [comment]
The feature described in https://github.com/dart-lang/sdk/issues/26655 (access to initializing formals) implies that initializing formals will be added to the formal parameter scope for resolution in the initializer list, and that feature has been scheduled for inclusion in the language. The conflict described in this issue will be in line with the spec after the spec has been updated. So it should be possible to resolve this issue as part of the same process where #26655 is implemented.

**Comment by eernstg** [comment]
I believe this issue is now obsolete (the original example _does_ create a name clash which is a compile-time error, and the analyzer does detect it, just like the VM always did, even before the spec said so ;-).

Closing. Please reopen if you think there is still an issue.

**Comment by skybrian** [comment]
Verified that analysis server detects it. There is still no error in Dartpad, though. I guess Dartpad is so out of date that we can't rely on it anymore.
