### ISSUE TITLE
Should warn when assigning to catch clause's error or trace parameters

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26298]
Take a look at:

``` dart
main() {
  try {
    throw "!";
  } catch (error, trace) {
    error = null; // <--
    trace = null; // <--
  }
}
```

According to the spec (§17.11), the parameters to catch are final. Given that, the two marked lines should have static warnings.

**Comment by srawlins** [comment]
This is recently enforced by the analyzer; those parameters are now considered final.
