### ISSUE TITLE
adding a line break in a string template adds unnecessary quotes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26303]
Adding a line break before

```dart
        throw 'Number of passed arguments (${
            query.argumentValues == null ? 0 : query.argumentValues.length}) doesn\'t match the number of used named arguments (${query.namedArguments.length}).';
//                                                                        ^
```
results in 

```dart
        throw 'Number of passed arguments (${
            query.argumentValues == null ? 0 : query.argumentValues.length'
        '}) doesn\'t match the number of used named arguments (${query.namedArguments.length}).';
```

with two redundant `'` before and after the added line break.

**Comment by alexander-doroshko** [comment]
@zoechi What made you think this is a bug in SDK? ;)
SDK doesn't include any editor where you could type Enter.

**Comment by zoechi** [comment]
@alexander-doroshko Hard to tell where the work of the analyzer ends and the IDE begins for me. Do you think this is an IDE bug?

**Comment by alexander-doroshko** [comment]
Yes, typing is handled by the IDE.
Server used for code highlighting, errors and quick fixes, code completion, go to declaration, find usages, intention actions, line markers and refactorings. But some part of each feature is anyway implemented at IDE level and in some cases it is difficult for users to guess who is responsible for the bug.
