### ISSUE TITLE
ResolveInstanceFieldsInUnitTask resolves too much

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26306]
The task in the title re-resolves the entire unit instead of just the instance fields.  Comment from the code:

```dart
      // TODO(leafp): This code only needs to re-resolve the right hand sides of
      // instance fields.  We could do incremental resolution on each field
      // only using the incremental resolver.  However, this caused a massive
      // performance degredation on the large_class_declaration_test.dart test.
      // I would hypothesize that incremental resolution of field is linear in
      // the size of the enclosing class, and hence incrementally resolving each
      // field was quadratic.  We may wish to revisit this if we can resolve
      // this performance issue.
```

We need to stop re-resolving everything.

**Comment by bwilkerson** [comment]
I suspect that the comment might be wrong and that we are now doing more during this task than at the time the comment was written.

I wrote some code so that the task only resolves the initializers of instance fields, and 15 tests started failing. In all cases the reason was that some level of type inference was no longer being done in code that is outside of an instance field's initializer. Here's an example of a failing test's output:

    FAIL: analysis engine | src tests | task tests | task tests | ternary operator
      Checker errors do not match expected errors:
  
      Expected errors that were not reported:
      @1361 info:INFERRED_TYPE_CLOSURE
      line 28, column 63 of /main.dart: 
                      ? isValidKey : (/*info:INFERRED_TYPE_CLOSURE*/(_) => true);
                                                                    ^^^^^^^^^^^^^^
      @1467 info:INFERRED_TYPE_CLOSURE
      line 31, column 55 of /main.dart: 
                       ? v : (/*info:INFERRED_TYPE_CLOSURE*/(_) => true);
                                                            ^^^^^^^^^^^^^^

      package:unittest/src/simple_configuration.dart 128:34  SimpleConfiguration.onExpectFailure
      package:unittest/src/simple_configuration.dart 24:13   _ExpectFailureHandler.fail
      package:unittest/src/matcher/expect.dart 103:18        fail
      test/src/task/strong/strong_test_helper.dart 318:3     _reportFailure
      test/src/task/strong/strong_test_helper.dart 218:5     _expectErrors
      test/src/task/strong/strong_test_helper.dart 102:7     check
      test/src/task/strong/strong_test_helper.dart 114:10    checkFile
      test/src/task/strong/checker_test.dart 18:5            main.<fn>

**Comment by bwilkerson** [comment]
@leafpetersen Thoughts?

**Comment by leafpetersen** [comment]
Clearly something different is happening, but I don't think anything important should be.  The two likely possibilities are that this is a bug, or that this is something relatively inconsequential having to do with how we're reporting inference.

The specific case you show above really shouldn't rely on re-resolution of instance fields.  Note that all of the variables involved are explicitly typed.  So the only thing that is happening is downwards inference.  I believe that the PartialResolverVisitor should be skipping this code anyway, which makes it particularly surprising that something changes.  I don't think the inference is really necessary here: it should just be changing the parameter type from dynamic to Object, which is basically the same in this situation.  So my guess is either that the inference is really still happening but for some reason we're not recording it (or dropping the recorded inference event on the floor?), or for some reason the different code path is causing us to choose not to infer it.

Are there more examples where we're clearly not inferring something that matters?  That is, where we now get errors?

I would print out (or look at in the debugger) the type of that closure (or one in a smaller repro) at the various stages and see what and where it used to be inferred to, and where and how it gets resolved now.

**Comment by bwilkerson** [comment]
> The specific case you show above really shouldn't rely on re-resolution of instance fields.

Just to be clear, it doesn't depend on re-resolution of instance fields. As far as I can tell it depends on the additional work that PartialResolverVisitor is doing that this issue claims should not be necessary. It is currently re-resolving a lot more than instance field initializers, and tests fail when I remove the "extra" work.

> Are there more examples where we're clearly not inferring something that matters? That is, where we now get errors?

Yes, there were something like 12 - 15 test failures (I don't have the numbers in front of me). I can send them to you off-thread if you want.

The ideas you suggested are interesting; I'll look into it more next week.

**Comment by leafpetersen** [comment]
> Just to be clear, it doesn't depend on re-resolution of instance fields. As far as I can tell it depends on the additional work that PartialResolverVisitor is doing that this issue claims should not be necessary. It is 

Yeah, sorry, being vague.  The point is just that as far as I can tell, the snippet of code that is generating (now not-generating) those INFERRED_TYPE_LITERAL messages
  - is not resolved by the PartialResolverVisitor
  - doesn't reference anything whose type can be changed (inferred) by the PartialResolverVisitor

Clearly something is changing, it's just weird..

> Yes, there were something like 12 - 15 test failures (I don't have the numbers in front of me). I can send them to you off-thread if you want.

Might be useful.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1917893003/

This reduces the time for this task to a little less than half the previous time.

**Comment by leafpetersen** [comment]
Awesome, thanks!
