### ISSUE TITLE
Supporting for...in style loops and ranges in patterns

### ISSUE THREAD

**Issue by krupalshah** [dart-lang/sdk#26307]
Hi, 
Are there any plans about adding range style loops and pattern matching.

for(var i=0;i<10;i++) should be replaced by for (var i in 1...10)

Another examples would be switch cases. 
I think writing case 1...10: and case 1,2,5: etc. is very useful. These are the small features can make language very much productive. As 1.0 has been released so far, can we ask for these features now?

Worth to link this [FAQ].(https://www.dartlang.org/support/faq.html#q-can-dart-add-tuples-pattern-matching-non-nullable-types-partial-evaluation-optional-semicolons-)

**Comment by zoechi** [comment]
See also https://github.com/drager/dep-pattern-matching/blob/master/proposal.md and https://groups.google.com/a/dartlang.org/forum/#!msg/misc/MJXLjFxZu0A/p7e-NaDHAgAJ

**Comment by lrhn** [comment]
Adding number
