### ISSUE TITLE
improving error messages in strong mode

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26318]
Some ideas for improving error messages in Strong Mode.
- [ ] function type error messages could link to an explanation of function subtyping. Especially covariant parameters as that is a very common issue
- [ ] similar message for other "DownCastComposite"
- [ ] we've also seen some confusion about why something is sometimes an error (we know for sure it will fail) vs a warning (it will probably fail).
- [ ] it would be nice to give errors an error codes. (for example C# compiler uses codes like `CS0106` which makes it easy to search for, find posts about it, etc.)
- [x] existing hints sometimes are confusing, in particular unnecessary cast (https://github.com/dart-lang/sdk/issues/26308)

@leafpetersen and @sigmundch and I were chatting about this. Feel free to edit this issue adding additional items. Thanks!

**Comment by bwilkerson** [comment]
FYI: @floitschG has already started work on giving codes to errors.

**Comment by jmesserly** [comment]
yay!

**Comment by floitschG** [comment]
Yes. I started to add IDs to errors and warnings. Recently other tasks were of higher priority, but I intend to get back to it.

**Comment by jmesserly** [comment]
going to assume this issue is stale. We've been improving errors though based on feedback, indeed there's some Q3 OKRs (for DDC) to further improve error messages.
