### ISSUE TITLE
Crash when shutting down (PushBlock called in background compiler)

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#26316]
```
python tools/test.py --exclude-suite pkg --vm-options --optimization-counter-threshold=7 --checked -t120 co19/LibTest/collection/HashSet/HashSet_class_A01_t01
```

/sources/git-one/sdk/runtime/vm/store_buffer.cc:107: error: expected: thread->isolate()->mutator_thread() == thread
- thread #5: tid = 0x0004, 0x00007fff887f9f06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  - frame #0: 0x00007fff887f9f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff8a2224ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff904c76e7 libsystem_c.dylib`abort + 129
    frame #3: 0x000000010a53aa29 dart`dart::OS::Abort() + 9 at os_macos.cc:386
    frame #4: 0x000000010a1c39d7 dart`dart::DynamicAssertionHelper::Fail(this=<unavailable>, format="expected: %s") + 791 at assert.cc:42
    frame #5: 0x000000010a654fab dart`dart::StoreBuffer::PushBlock(this=0x00007ff346800290, block=<unavailable>, policy=<unavailable>) + 251 at store_buffer.cc:107
    frame #6: 0x000000010a66f7e3 dart`dart::Thread::ExitIsolateAsHelper(bool) [inlined] dart::Thread::StoreBufferRelease(this=<unavailable>, policy=kCheckThreshold) + 323 at thread.cc:515
    frame #7: 0x000000010a66f7c8 dart`dart::Thread::ExitIsolateAsHelper(bypass_safepoint=false) + 296 at thread.cc:299
    frame #8: 0x000000010a325d9f dart`dart::BackgroundCompiler::Run(this=0x00007ff346f00050) + 879 at compiler.cc:1794
    frame #9: 0x000000010a67317b dart`dart::ThreadPool::Worker::Loop(this=0x00007ff346f00190) + 139 at thread_pool.cc:388
    frame #10: 0x000000010a672fab dart`dart::ThreadPool::Worker::Main(args=140682843914640) + 443 at thread_pool.cc:446
    frame #11: 0x000000010a53ba06 dart`dart::ThreadStart(data_ptr=<unavailable>) + 70 at os_thread_macos.cc:97

**Comment by sgmitrovic** [comment]
Can be reproduced with:

 python tools/test.py  --vm-options="--optimization-counter-threshold=5 --background-compilation-stop-alot"  language

**Comment by fsc8000** [comment]
I can take a look at this.
