### ISSUE TITLE
Typo in description of Iterable.first

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26319]
The description of method Iterable.first ( https://api.dartlang.org/stable/1.15.0/dart-core/Iterable/first.html ) reads:

> E first
> Returns the first element.
> 
> Throws a StateError if this is empty. Otherwise `returs` the first element in the iteration order, equivalent to `(iterator..moveNext())..current`.

Should be `returns` and `(iterator..moveNext()).current`

**Comment by mezoni** [comment]
[Update iterable documentation to be more precise.](https://github.com/dart-lang/sdk/commit/c7a9b314ac9d69b01335ad8b28e16b90df13674a#diff-3295c9c494e70249c0421a0d1b772e09R375)

**Comment by mezoni** [comment]
>> Should be returns and (iterator..moveNext()).current

This is also incorrect.
Should be `returns` and `this.elementAt(0)`.

This code is not equivalent

```dart
(iterator..moveNext()).current
```

I think that author even did not tested it on equivalence to `(iterator..moveNext()).current`.
It never throw the `StateError` on the empty collection, it will return the value `null` which is not a equivalent .

**Comment by lrhn** [comment]
That's handled by the previous sentence: If the iterable is empty, it throws a `StateError`. Otherwise it is non-empty, so `moveNext` returns true, and in that case it's equivalent to `(iterator..moveNext()).current`.

That said, `this.elementAt(0)` is simpler and just as precise.

**Comment by mezoni** [comment]
>> That's handled by the previous sentence:

More precise it should be:

Returns the `first` element (on the non-indexable collection of the elements may create an additional `Iterator` in order to get this element).
If the iterable is empty, it throws a StateError.

**Comment by floitschG** [comment]
Thanks.
