### ISSUE TITLE
Update 1.16 changelog on dev channel re pub cacheing

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26315]
Please make a CL or a message about how to update the 1.16 changelog before we create the 1.16 stable release, since pub resource cacheing is turned off, I think. @kevmoo @mit-mit

**Comment by kevmoo** [comment]
The bug fix does invalidate what's in the changelog. We are still caching, just more correctly now. 😄 

...I think we can close this...

**Comment by munificent** [comment]
What Kevin said. Caching is still turned on. It's just not broken. :)
