### ISSUE TITLE
Please merge polymer fixes into dev channel

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#26327]
@whesse @mit-mit @kasperl 
Merge https://github.com/dart-lang/sdk/issues/26228 to 1.16 stable

* Describe the problem this merge is fixing - include issue numbers if applicable
This fixes a issue that broke Dart with Polymer.

* What revision(s) needs to be merged - please annotate revisions with reason if more than one
https://codereview.chromium.org/1908423004/
https://codereview.chromium.org/1914643002

* Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here
Did not try...

**Comment by eernstg** [comment]
Hej Michael,

der er en forbindelse til Reflectable omkring de CLs du nævner
(1908423004, 1914643002), og der er muligvis behov for at checke at de
løser problemet i forhold til Reflectable. Det gælder dog ikke hvis der er
nogen (Jacob McDonald?) som allerede har tjekket at de angivne CLs har løst
problemet for Polymer (fordi Polymer bruger Reflectable, og netop denne
anvendelse er den testcase jeg kender omkring problemet). Kender du til
status i den henseende?


On Mon, Apr 25, 2016 at 1:28 PM, Michael Thomsen <notifications@github.com>
wrote:

> @whesse <https://github.com/whesse> @mit-mit <https://github.com/mit-mit>
> @kasperl <https://github.com/kasperl>
> Merge #26228 <https://github.com/dart-lang/sdk/issues/26228> to 1.16
> stable
>
>
> This fixes a issue that broke Dart with Polymer.
>
>
> https://codereview.chromium.org/1908423004/
> https://codereview.chromium.org/1914643002
>
>
> Did not try...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26327>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mit-mit** [comment]
Hi Erik, no I am not aware of the details of how this might use reflectable -- there are more details in https://github.com/dart-lang/sdk/issues/26228, does that answer it for you?

**Comment by eernstg** [comment]
Rechecking the comments on #26228, I can see that it says 'Two CLs have been committed to fix the Polymer problems with Dartium 1.16' which seems to imply that it does fix the issue with Polymer. Trusting that, there should not be a need to run extra checks about this using Reflectable outside Polymer.

**Comment by whesse** [comment]
There are two commits to chromium.googlesource.com/dart/dartium/blink before c1840828, and one after, that have not been merged to dev.  We need to either make a new patch branch of dartium/blink, or merge these commits (and the corresponding commits to dart-lang/sdk), as well.  These changes seem to be problem-free, so I will attempt to merge all of them to dev.  The commits to dart-lang/sdk, which also include the DEPS updates pointing to dartium/blink, are:

e8fd9f5c1f9f3e5df1265cf762ceac5170c40621
8f7b8a9d87d63ff164cdeee1be64104b648d8056
cf59fdfabd77924e542954d6cb0ecd6d88272f99

The first commit has no comments on the review, saying any follow-up CLs were needed, and I don't see any later commits to the same files.

The second commit to blink was (implicitly) merged by 8f7b, which is the main one being merged here.  So it is apparently unproblematic.  And the third commit here, cf59, just merges test expectation changes.

**Comment by terrylucas** [comment]
William those cherry picks are right (if you want green Dartium bot runs
you'll need this commit 111a794
<https://github.com/dart-lang/sdk/commit/111a794141cd313460e4fe2593cfea9862fe1c0f>
it expects failure on a bad test (matches dart2js now).  I'll fix the test
in 1.17.

Thanks William.

**Comment by mit-mit** [comment]
@whesse, this was merged into 1.16.0-dev.5.5, right?

**Comment by whesse** [comment]
Merged into 1.16.0-dev.5.5.
