### ISSUE TITLE
Typo in HashMap.identity() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26326]
Please see https://api.dartlang.org/stable/1.15.0/dart-collection/HashMap/HashMap.identity.html

> 
> Creates an unordered identity-based map.
> 
> Effectively a shorthand for:
> 
>```
 new HashMap(equals: identical,
>             hashCode: identityHashCodeOf)
```
There are no `identityHashCodeOf `function in Dart. There should be `identityHashCode`

**Comment by floitschG** [comment]
Fixed in 111a794141cd313460e4fe2593cfea9862fe1c0f.
Thanks!

**Comment by sgrekhov** [comment]
Please fix the same issue for HashSet (https://api.dartlang.org/stable/1.15.0/dart-collection/HashSet/HashSet.identity.html), LinkedHashMap (https://api.dartlang.org/stable/1.15.0/dart-collection/LinkedHashMap/LinkedHashMap.identity.html) and LinkedHashSet (https://api.dartlang.org/stable/1.15.0/dart-collection/LinkedHashSet/LinkedHashSet.identity.html)

**Comment by floitschG** [comment]
Done in 516c09cb1f9821c3414daf6a6856feab7319a762. Thanks again.
