### ISSUE TITLE
dart2js main() function is executed before document is ready, resulting in null document.body

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#26325]
In my program, the `main()` function is executed as advertised - after the document is ready. However, after I compile to js with dart2js, it executes before. I'm 100% certain that's the case, because by simply moving the `<script>` tag out of the `<head>` section of the page and putting it just before the closing `</body>` tag, the program started working.

Here's a screencast demonstrating the problem: https://www.youtube.com/watch?v=SAV6DxJQ8Ho

**Comment by zoechi** [comment]
AFAIK that's the suggested place for the Dart script tag anyway. Or alternatively add the `defer` (or `async`) to the script tag.

**Comment by snitko** [comment]
Adding a `defer` attribute to `<script>` worked, thank you
