### ISSUE TITLE
Movement property of MouseEvent returns invalid data

### ISSUE THREAD

**Issue by dhenneke** [dart-lang/sdk#26324]
The `movement` property of the `MouseEvent` doesn't contain the correct data. The Point just contains `null` values for x and y.

Example that demonstrates the problem (hover over the blue canvas and check the console): https://dartpad.dartlang.org/377c31479e2ac939c8fd398fb0cfe218

I've tested this in Chrome 51.0.2704.22 beta-m (64-bit), Firefox 45.02 and IE 11.0.9600.18283 with the same results.

**Comment by alan-knight** [comment]
It was using the old webkit prefix. https://codereview.chromium.org/1921823002/

**Comment by alan-knight** [comment]
Also incorrectly said it was supported on Safari but not on Firefox, which is backwards.
