### ISSUE TITLE
js-interop: NoSuchMethodError when compiled to JavaScript

### ISSUE THREAD

**Issue by rillomas** [dart-lang/sdk#26321]
**Describe the issue you're seeing**
I get the following error when I access a web page built by `pub build`

`NoSuchMethodError: method not found: 'open$0' (J.getInterceptor$x(...).open$0 is not a function)`

**Does it happen in Dartium or when compiled to JavaScript?**
This is happening after the code is compiled to JavaScript.
I checked in Dartium and Chrome and both had the same error.

* Dart SDK version: `Dart VM version: 1.15.0 (Wed Mar 09 10:07:59 2016) on "windows_x64"`
* pkg/js version: `0.6.0`

Failing code:
https://github.com/rillomas/js_interop_issue

1. `pub get`
2. `pub build`
3. `cd build/web`
4. `python -m SimpleHTTPServer`
5. access localhost:8000 with a browser and open the console to see error

if you comment out the following line in `index.dart`, the code will work properly.

`_heartbeater = new Timer.periodic(HEARTBEAT_INTERVAL, _pulseHeartbeat);`

**Comment by DisDis** [comment]
Please disable 'minify'.

```
- $dart2js:
    checked: false
    minify: false
    sourceMaps: true
```

maybe duplicate: https://github.com/dart-lang/sdk/issues/25785

**Comment by rillomas** [comment]
I got the following error after disabling minify
`NoSuchMethodError: method not found: 'open$0' (J.getInterceptor$x(...).open$0 is not a function)`

**Comment by DisDis** [comment]
Yes it is the same [issue](https://github.com/dart-lang/sdk/issues/25785).

**Comment by mit-mit** [comment]
Closing as dupe.
