### ISSUE TITLE
Spec should not allow `return expr` in void function, even if expr is statically typed as void.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26323]
The Dart specification currently disallows `return expr` (and by extension `=> expr` bodies) for void functions _unless_ the `expr` has type void (basically, it's a call of a void function).

That seems safe - the function call should always return null - but actually it is not.
The problem is that while the _static_ type of the expression is `void`, the actual type may not be, because a method returning `void` may be overwritten in a subclass to return non-`void`.

This caused a problem in a case with code like: `void close() => _sink.close();` where `_sink` had type `Sink` (which has a `void close()` method) but the actual object was a subclass of `Sink` that had a `Future close()` method. The future was returned and (in checked mode) caught by the void type annotation.

Alternatively, a void type annotation should not cause an error if a non-null value is returned. That would be conceptually consistent - the value is expected to be ignored, so it can be anything. It's using the value that gets you a warning.

**Comment by mezoni** [comment]
I think that need only to add a warrning when method overrides a return type `void`.
And, of course, tear off the hands of those who write code like this (overrides a return type `void`).

```dart
void main() {
  void closeFoo(_Foo f) => f.close();

  _Foo foo1 = new Foo1();
  closeFoo(foo1);
  _Foo foo2 = new Foo2();
  closeFoo(foo2);
}

class Foo1 extends _Foo {
  void close() {
    //
  }
}

class Foo2 extends _Foo {
  // I am a stupid. I am does not follow the API. Ha-ha!
  // I will create a potential problem for you.
  int close() {
    return 0;
  }
}

class _Foo {
  void close() {
    //
  }
}
```

**Comment by floitschG** [comment]
I prefer to just allow it.

**Comment by eernstg** [comment]
The feature specification [generalized-void.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md) contains the exception that it is allowed for `return e;` to have an expression `e` with static type `void`, if the innermost enclosing function has return type `void`. So in that sense we have made the requested decision and specified it at the feature spec level, and only he language specification itself still needs to be updated, which will happen when that feature spec is integrated into the language specification.

**Comment by eernstg** [comment]
Added milestone for reaching the level where the feature specification is stable (but not yet integrated into the language specification). [This CL](https://dart-review.googlesource.com/c/sdk/+/35680) makes it an error to `return e` in a void function when the static type of `e` is different from `void` (which is similar to the request made in this issue, and the situations where they differ have been discussed separately).

**Comment by eernstg** [comment]
As mentioned in [this comment](https://github.com/dart-lang/sdk/issues/26323#issuecomment-360640142), we have the exception in [generalized-void.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md) that a void function can have `return e;` where the static type of `e` is `void`. The motivation for having it was backward compatibility. It's been there for a long time, and the document was accepted with that rule in it.

Given that feature specs will be integrated into the language spec, and the relevant feature spec does not need to be updated to match the decision we made, I think we can close this issue.

@lrhn, are you OK with this issue being closed?

**Comment by lrhn** [comment]
I accept it. It's not my personal preference :)

**Comment by eernstg** [comment]
Understood, and yet closing. ;-)
