### ISSUE TITLE
NetworkInterface.list not implemented on Android

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#26329]
> This API is not implemented in Dart for Android. See Socket::ListInterfaces in dart/runtime/bin/socket_android.cc.
> 
> Socket::ListInterfaces is also not setting the OSError. CObject::NewOSError then consumes the null OSError, resulting in a segfault.

See https://github.com/flutter/flutter/issues/205

**Comment by johnmccutchan** [comment]
@zanderso FYI

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by zanderso** [comment]
https://codereview.chromium.org/1916223003/

ifaddrs.h still does not exist in the NDK, so to support this API, we'll have to implement as suggested in the comment in socket_android.h. In the meantime, I've fixed the crash, and added NetworkInterface.listSupported.

**Comment by sethladd** [comment]
It looks like we landed @zanderso 's patch. Can we close this issue?

**Comment by sortie** [comment]
Reopening since it appears ifaddrs.h is available as of Android API level 24 (August 2016). If we can take advantage of that API level, then we can implement this feature.

**Comment by dnfield** [comment]
It would be ideal if we could do this in a way that supports <API24 as well.  WebRTC has an implementation that does this, for example.

**Comment by sortie** [comment]
Can you link to that implementation? I guess that would require making a raw system call.

**Comment by dnfield** [comment]
https://chromium.googlesource.com/external/webrtc/stable/talk/+/master/base/ifaddrs-android.cc

**Comment by dnfield** [comment]
My preference would be to see something like 

```
#ifdef API_24 // or whatever the right name is?
// Use NDK implementation
#else
// Use system calls
#endif // API_24
```

Flutter, for example, currently supports down to API 16.  I'd like to use this call in Flutter, but wouldn't be able to if it requires API 24 (which for Dart VM and the Engine, is a compile time flag).

**Comment by dnfield** [comment]
The #if should probably be more like this:

```cpp
#if __ANDROID_API__ >= 24
  // use NDK
#else
  // use system calls, e.g. the way that WebRTC does it
#endif // __ANDROID_API__
```
