### ISSUE TITLE
Include type information with generic promises from Chrome IDL

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26336]
For instance

https://chromium.googlesource.com/experimental/chromium/blink/+/master/Source/modules/background_sync/PeriodicSyncRegistration.idl

Defines `Promise<boolean>`

But in the code output, we just see `Future` with no type - https://api.dartlang.org/stable/1.16.0/dart-html/PeriodicSyncRegistration/unregister.html

**Comment by terrylucas** [comment]
Yep looks like Chrome started adding Promise<type> to the IDL we'll need to parse it in our Python IDL parser.  BTW, the background_sync/*.idl have been deleted in a subsequent release.  I wonder if we should look at hiding APIs that are sooo experimental.

**Comment by mit-mit** [comment]
@kevmoo @terrylucas is anyone looking at this? It's marked S1 but has seen no updated for 24 days...

**Comment by mit-mit** [comment]
Clearing milestone as there is no indication this is being worked on. @kevmoo FYI

**Comment by kevmoo** [comment]
Is this still an issue with the dart:html API?

From mobile. Sorry for brevity and/or spelling.

**Comment by terrylucas** [comment]
It is a dart:html in general issue.  I don't think we have any intention to
fix this in dartium_html.dart.  We could just reassign to area dart:html
(part of your earlier email on cleaning up dart:html).
