### ISSUE TITLE
Missing return in missing overrides quick fix when class body is on one line

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26335]
Create a dart file with the following content:

```
abstract class A {
  void m();
}
class B extends A {}
```

Select `B`, then select the quick fix "Create 1 missing overrides". There should be an extra carriage return after the opening brace.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2256463002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/010578b88aa9cdd43bc4b43dcb55ee56a3394f90
