### ISSUE TITLE
Document the precise behavior of --observe

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26339]
Currently none of our documentation details the precise behavior of the `--observe` flag in terms of other flags it implies (see [this comment](https://github.com/dart-lang/sdk/issues/26203#issuecomment-213610842) for those flags). The command-line documentation doesn't mention that it implies `--warn-on-pause-with-no-debugger`, and [the online documentation](https://www.dartlang.org/tools/dart-vm/) also doesn't mention that it implies `--pause-isolates-on-unhandled-exceptions`.

**Comment by turnidge** [comment]
Closed by #bd3cdf4009eef2226ecb2cd03c263b522a5d1d6a.
