### ISSUE TITLE
Transmit Blob to Isolate

### ISSUE THREAD

**Issue by Fox32** [dart-lang/sdk#26337]
Dart doesn't seem to allow to send blobs to another worker isolate. If fails with an exception that the type is unsupported. [The structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) states that it should be possible to transmit blobs. I couldn't try it, but I think `ImageBitmap` should also be transferable. 

Some background of what I try to achive: I have a WebGL application that needs to decode and upload many images. I store them as blobs on the client and currently load them into an `ImageElement` and later upload them into a texture. To make the process more async I would like to try the new [createImageBitmap ](https://developers.google.com/web/updates/2016/03/createimagebitmap-in-chrome-50) API in a background isolate. So I want to send a `Blob` to the isolate and later receive an `ImageBitmap` from the isolate.

I'm currently using 1.16.0-dev.5.5 on Windows 64bit

**Comment by floitschG** [comment]
Sorry for the noise. I initially thought that something else in the html library was still missing.

@rakudrama: what do you think is the best approach?
I think it would be relatively easy to add support (see sdk/lib/_internal/js_runtime/lib/isolate_serialization.dart), but we don't want to drag in the html-library whenever someone is using isolates. Do you think there is an easy way to detect these elements with a simple "JS" test?

**Comment by lrhn** [comment]
Isolates no longer work on the web.
