### ISSUE TITLE
NPE from pub get

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26338]
_From @devoncarew on April 25, 2016 16:49_

When running `pub get` on our bot, we saw a stack trace thrown from pub:

```
The null object does not have a getter '_doneFuture'.

NoSuchMethodError: method not found: '_doneFuture'
Receiver: null
Arguments: []
dart:async                                   _StreamController.close
package:pub/src/utils.dart 583               tee.<fn>
dart:async                                   _StreamController.close
package:pub/src/utils.dart 530               validateStream.<fn>
dart:async                                   _EventSinkWrapper.close
package:barback/src/utils/file_pool.dart 40  FilePool.openRead.<fn>.<fn>
```

More details here: https://build.chromium.org/p/client.flutter/builders/Linux/builds/786/steps/steps/logs/stdio.

This was intermittent - forcing a build on the bot didn't show the issue a 2nd time.

_Copied from original issue: dart-lang/pub#1412_

**Comment by nex3** [comment]
As far as I can tell, no pub code has ever included the code `_doneFuture`. It looks like something in `dart:async`. Since [the call on line 583](https://github.com/dart-lang/pub/blob/c1405b945c6d818c8cfe78334e8d4b11fd913103/lib/src/utils.dart#L583) isn't passing in any arguments, I can only assume that this isn't something we can fix in pub, so I'm going to redirect this to the SDK repo.

**Comment by lrhn** [comment]
I've looked at all references to `_doneFuture` in the SDK libraries, and they are all implicit `this._doneFuture` references. There is no code at all that reads `_doneFuture` of a reference that can be `null`, so this doesn't look like an SDK issue. 

Maybe it's a VM issue where `this` can somehow become `null`? 
Tentatively assigning to VM.

**Comment by zanderso** [comment]
This is a bit difficult to look into without some better reproduction instructions. The builder link also 404s for me. @devoncarew
