### ISSUE TITLE
Issue with refactor-rename on filename

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#26331]
**Summary:**
It is possible to temporarily halt the analysis-server in webstorm by using the refactor-rename function on a filename. This can be done by first renaming an identifier which was defined in the corresponding file-unit. After then renaming the filename, the analysis-server stops responding for a short while (code-completion temporarily stops working), and attempting to use the rename function again makes the server throw an error.

**Steps to reproduce:**
1) In Webstorm, create a dart project of type 'Console Application - a larger command-line application sample'.
2) The contents of main.dart should be similar to the following

```
import 'package:untitled90/untitled90.dart' as untitled90;

main(List<String> arguments) {
  print('Hello world: ${untitled90.calculate()}!');
}
```

3) Refactor-rename the `calculate` method identifier to `foo`
4) Refactor-rename the 'untitledXX.dart' dart filename to `bar.dart`
5) Refactor-rename the `arguments` parameter identifier to `baz`
_Expected:_
The `arguments` identifier can be renamed without issue
_Actual:_
The following error is shown:
![webstorm-error](https://cloud.githubusercontent.com/assets/12271154/14811808/359e3e7e-0b9a-11e6-9026-e2c6450ff614.png)

**SDK and Webstorm version**
Dart-SDK 1.16.0-dev.5.5
Webstorm 2016.11

**Other info**
When the server start responding again after a while, this issue can not be reproduced until a new project is started.

This may be related to
https://github.com/dart-lang/sdk/issues/26207

**Comment by srawlins** [comment]
We haven't seen this exception in a while.
