### ISSUE TITLE
Add a constructor for MessageChannel

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26349]
The [`MessageChannel`](https://api.dartlang.org/stable/1.16.0/dart-html/MessageChannel-class.html) class doesn't have a constructor, despite [the JS class](https://www.w3.org/TR/webmessaging/#message-channels) having one. This makes it pretty much impossible to use.

**Comment by alan-knight** [comment]
It looks like the reason it doesn't have a constructor is that the IDL is marked as CustomConstructor, even though there doesn't seem to be anything special about it. And we don't provide a custom constructor implementation. So I think providing one would fix that.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/2864053002

**Comment by kevmoo** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel/MessageChannel

**Comment by terrylucas** [comment]
Fixed https://dart-review.googlesource.com/c/sdk/+/48381
