### ISSUE TITLE
Default values must be constant: false positive

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#26345]
```dart
import 'dart:web_gl';

function({int colorMode : RenderingContext.RGBA}) {}
```

With Dart 1.16, the analyzer report an error `ERROR: Default values of an optional parameter must be constant`

The variable is defined as a `static const` int `web_gl_dartium.dart`

There is the same thing for some constants in dart:html but not all.
It worked in Dart 1.15.

**Comment by bwilkerson** [comment]
I cannot reproduce the behavior you're seeing on bleeding edge, using either the command-line analyzer or the analysis server. It's possible that the bug has been fixed.

**Comment by xavierhainaux** [comment]
Ok, good if this is already fixed in the next version. I only had a couple of those issues so I worked around by removing the default values in my code.

I close the issue.

**Comment by xavierhainaux** [comment]
Ok, I checked again and the issue totally disappeared. 
The only thing I see is a cache problem when I upgraded from 1.15 to 1.16
