### ISSUE TITLE
Document the correct way for tools to interact with the VM service

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26340]
According to [this comment](https://github.com/dart-lang/sdk/issues/26203#issuecomment-213610842), "`--observe` is not a flag that should be used by tools or tests". This should be mentioned in the documentation for `--observe`, with a link to documentation of the correct way for tools and tests to invoke the VM service.

**Comment by turnidge** [comment]
I have updated the help message to explicitly call out the fact that the --observe flag is an alias for other flags:

```
--observe[=<port>[/<bind-address>]]
  The observe flag is a convenience flag used to run a program with a
  set of options which are often useful for debugging under Observatory.
  These default options are:
      --enable-vm-service[=<port>[/<bind-address>]]
      --pause-isolates-on-exit
      --pause-isolates-on-unhandled-exceptions
      --warn-on-pause-with-no-debugger
  Please see these options (--help --verbose) for further documentation.
```

As for calling out explicitly that it should not be used in tools and tests, I have decided that that is not necessary, so long as the user of the flag is made aware of the fact that it is a convenience alias.

**Comment by nex3** [comment]
Just calling it a convenience alias is insufficient if you want to be able to modify the set of flags it implies. If it can have breaking behavioral changes at any time, you need to very clearly describe in which cases it's not safe to use.

**Comment by turnidge** [comment]
I have changed the message to reserve the right to modify the set of flags.  Thanks!

```
--observe[=<port>[/<bind-address>]]
  The observe flag is a convenience flag used to run a program with a
  set of options which are often useful for debugging under Observatory.
  These options are currently:
      --enable-vm-service[=<port>[/<bind-address>]]
      --pause-isolates-on-exit
      --pause-isolates-on-unhandled-exceptions
      --warn-on-pause-with-no-debugger
  This set is subject to change.
  Please see these options (--help --verbose) for further documentation.
```

**Comment by turnidge** [comment]
a02995c3c3d655d90378fc9eae35c18d1becf28a
