### ISSUE TITLE
Analysis server cannot find some usages

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#26355]
- Clone the project here: https://github.com/xavierhainaux/analysis_server_bug . The project has 2000 empty classes that are necessary to trigger the bug.
- Open the project in webstorm and enable Dart support.
- Kill and Restart the analysis server process (in webstorm “Restart analysis server”). The bug is present only on the first analysis.
- Wait a few seconds for the whole analysis to complete.
- In the file “lib/declaration.dart”, right click on the variable “oneVariable” and execute “Find usages”.
- Webstorm reports incorrectly “No usages found”
- Edit any dart file in the project (just add a white space for instance).
- Repeat the “Find usages”
- Webstorm now reports correctly 1 usage

Why do I care about this weird bug?
We have a pre-commit script which starts an analysis_server on our project and check that some tagged properties are actually used in the project.
Since the upgrade to Dart 1.16, the script failed to detect some usages of the properties. The usages in the same file that the declaration are not found.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1946353004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ada9cf43db62a35f63ef75286f3f14aebe222310
