### ISSUE TITLE
MessagePort: call start when onMessage is activated, hide start

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26351]
When a message is posted to one port of a `MessageChannel`, it never seems to be delivered to the other port. The following test reproduces this:

``` dart
import 'dart:html';

import 'package:js/js.dart';
import 'package:test/test.dart';

@JS("eval")
external _eval(String js);

void main() {
  test("a message can be passed through a channel", () async {
    var channel = _eval("new MessageChannel()") as MessageChannel;
    channel.port1.postMessage("hello");
    print(await channel.port2.onMessage.first);
  });
}
```

Note that the eval trick is there to work around #26349. This test never completes in Dartium, Chrome, or Firefox. The corresponding raw JS works as expected:

``` js
var channel = new MessageChannel();
channel.port1.postMessage("hello");
channel.port2.onmessage = function(message) { console.log(message); }
```

**Comment by alan-knight** [comment]
That doesn't like the "as" for me, and gives a cast failure. But fixing the constructor would be the right thing anyway.

**Comment by alan-knight** [comment]
So I can give it a constructor, but as described here, it never gets delivered. This is consistent in DDC as well.

The difference seems to be that while setting onmessage on the port does work in JS, using addEventListener with type "message" does not, and the latter is what our event streams do. I don't know why this doesn't seem to work for me - it appears from examples that it ought to.
```
var channel = new MessageChannel();
channel.port1.postMessage("hello");
channel.port2.addEventListener("message", function(message) { console.log(message); });
```

**Comment by kevmoo** [comment]
@nex3 @matanlurey – could be related to https://github.com/dart-lang/sdk/issues/32438 ?

**Comment by kevmoo** [comment]
@terrylucas is going to look at this...

**Comment by kevmoo** [comment]
Per the spec: https://html.spec.whatwg.org/multipage/web-messaging.html#examples-5

```
The key difference is that when using addEventListener(), the start() method must also be invoked. When using onmessage, the call to start() is implied.

The start() method, whether called explicitly or implicitly (by setting onmessage), starts the flow of messages: messages posted on message ports are initially paused, so that they don't get dropped on the floor before the script has had a chance to set up its handlers.
```

Since we use `addEventListener` under the covers w/ `onMessage`, a call to `start` is required.

This example works with `2.0.0-dev.43.0`:

```dart
import 'dart:html';

import 'package:test/test.dart';

void main() {
  test('a message can be passed through a channel', () async {
    var channel = new MessageChannel();
    channel.port1.postMessage('hello');

    channel.port2.start();
    print((await channel.port2.onMessage.first).data);
  });
}
```

@nex3 – I'm okay with this behavior – since I'd like to avoid adding "magic" to call start, etc.

Thoughts?

@terrylucas – FYI

**Comment by nex3** [comment]
Dart streams generally do whatever setup is necessary to start data flowing once a listener is added. I'd expect this to behave accordingly, without requiring me to explicitly start listening—especially since the code that eventually listens to the stream may be far removed from the code that creates the channel.

**Comment by kevmoo** [comment]
@nex3 – so do we auto-start and stop exposing the `start` method?

SGTM – just want to sanity check, though...

**Comment by nex3** [comment]
I think that makes sense, yeah.

**Comment by kevmoo** [comment]
@terrylucas – make sense?
