### ISSUE TITLE
Add support for shared analysis configurations.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26359]
A tracking issue for analysis configuration sharing as described in the [Sharing Analysis Options Rethink](https://docs.google.com/document/d/1rRlZut75Twl8hJ6529xjGRc12miHFPpQ8gr_oP6J3dc/edit?ts=57069571) doc.
- [x] server support (https://github.com/dart-lang/sdk/commit/870aa5e4f48be9574cd2fbc1dd191f1c91317835)
- [ ] cli support

**Comment by pq** [comment]
First cut out for review:  https://codereview.chromium.org/1923973004/

![screen shot 2016-04-28 at 10 10 24 am](https://cloud.githubusercontent.com/assets/67586/14894657/7c90d978-0d29-11e6-855a-6a47ffd31af9.png)

**Comment by bwilkerson** [comment]
@pq I'm guessing that this can be closed now. Please re-open if that's not the case.
