### ISSUE TITLE
new Iterable.generate() is not equivalent to const [0, ..., n - 1].map(generator)

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26358]
According to Iterable.generate(int count, [E generator(int index)]) documentation (see https://api.dartlang.org/stable/1.16.0/dart-core/Iterable/Iterable.generate.html)

> As an Iterable, new Iterable.generate(n, generator)) is equivalent to const [0, ..., n - 1].map(generator).

It isn't so. Look at the following program

```dart
int generator1(int index) {
  print("generator1(" + index.toString() + ")");
  return index;
}
int generator2(int index) {
  print("generator2(" + index.toString() + ")");
  return index;
}

main() {
  const arr = const [0, 1, 2, 3, 4, 5];
  Iterable i1 = arr.map(generator1);
  Iterable i2 = new Iterable.generate(arr.length, generator2);

  i1.elementAt(2);
  i1.elementAt(2);

  i2.elementAt(2);
  i2.elementAt(2);
}

```
Output is:
```
generator1(2)
generator1(2)
generator2(0)
generator2(1)
generator2(2)
generator2(0)
generator2(1)
generator2(2)

```
i1.elementAt(2) calls generator function only once
i2.elementAt(2) calls generator function 3 times.

That mean that new Iterable.generate(n, generator)) is **NOT** equivalent to const [0, ..., n - 1].map(generator).

Either documentation either implementation should be changed

**Comment by floitschG** [comment]
Good point.
We need to decide what we want to do here, but I think making it equivalent to the list would be the more efficient version.
@lrhn what do you think?

**Comment by lrhn** [comment]
I agree that it's just a missing optimization. We know the length and the value for the index at each position (it's the index), so we should just fix `elementAt` (and `first` and `last` if necessary) to get the value without iterating. It should be an efficient-length iterable if it isn't already.
I'd even say that `skip` and `take` should be efficient (not iterate past the skipped part).

**Comment by lrhn** [comment]
Fixed.
