### ISSUE TITLE
Coverage collection not working anymore under SDK version 1.16.0

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#26352]
# Steps to reproduce
- Get the latest stable SDK
- Write some testable code
- `pub global activate coverage`
- `dart --checked --observe=8000 testfile.dart`
- `pub global run coverage:collect_coverage --port=8000 --out coverage.json --wait-paused --resume-isolates`
- Watch it fail (in my case at least)

# Error
`JSON-RPC error -32601 (method not found): Method not found`
For: https://github.com/dart-lang/coverage/blob/0efd184aa00e6029b3606eac2d1ebb2af4fdaf3b/lib/src/vm_service_client.dart#L199

It looks like the Observatory RPC interface does not support `_getCoverage` anymore. A bit of research revealed this might indeed be the case: https://github.com/dart-lang/sdk/commit/c434931517ae2a05f96b26c0fe6ff581d322ed02#diff-243e54ec47a7b6d9b6088b2200bbf298L4022

**Edit:** this commit is also included in the `1.16.0` release, see: https://github.com/dart-lang/sdk/commits/1.16.0?page=4. Also, the `dart_coveralls` plugin exits with a 255 code and `Unrecognized flags: coverage_dir`

**Comment by kevmoo** [comment]
Tracked in the coverage package - https://github.com/dart-lang/coverage/issues/107
