### ISSUE TITLE
dart:async regression from strong-mode fixes

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26363]
https://github.com/dart-lang/sdk/commit/0253879a6039ec61220ff66dd1223dce815210a6 makes AsyncStressTest benchmarks up to 10x slower and adds 12k to swarm.

If it can't be fixed quickly, I suggest reverting and re-applying when the problems are fixed.

@dgrove @kevmoo @leafpetersen

**Comment by leafpetersen** [comment]
With some more changes to this patch https://codereview.chromium.org/1914373003/ most of the async stress tests are about the same.  There's still about a 2x regression on a couple of stream tests.  Blue is the baseline (before the first async patch), green is with both of my patch sets.

![image](https://cloud.githubusercontent.com/assets/8484504/14905369/b7d55244-0d64-11e6-95b1-76dbdc518fc3.png)

**Comment by leafpetersen** [comment]
I have some additional fixes that bring us back to parity: see the purple bars below.  (These benchmarks are ridiculously noisy, so take the bars with a grain of salt).

![image 1](https://cloud.githubusercontent.com/assets/8484504/14931014/103260b8-0e1d-11e6-889b-c10d4a2382f1.png)

**Comment by leafpetersen** [comment]
I believe that this should be fixed by bd323f27cdc128b79ed27a7d6af65d20ff2f94be .  @sra can you verify that there are no remaining significant regressions?  cc @cbracken

**Comment by rakudrama** [comment]
It looks great.
Thanks so much!
