### ISSUE TITLE
Require C11 support when compiling Dart, needed by BoringSSL

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#26367]
The version of clang we pull is from 2013. We can't roll BoringSSL until we update it.

**Comment by zanderso** [comment]
A local Linux/clang build that includes the updated BoringSSL works for me:

https://codereview.chromium.org/1930203003

So this might not actually be the problem, but we should update clang to whatever chromium is using anyway.

However, as another clue the Linux/clang build instructions say to set a bunch of environment variables:

https://github.com/dart-lang/sdk/wiki/Building

notably `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH`. The buildbot does not appear to be setting these. Are these not actually needed?

**Comment by whesse** [comment]
OK, I didn't update clang today, but you still think that should be done to fix this, right?  Should we add the environment variables as well?  Can you see any difference they make to your local build?
I can log in to the linux bots, and see where that header file is, and if it is missing from the  system include directories, and why.

If it is in our third_party clang checkout, and not the system files, then of course the problem is the environment variables.

**Comment by whesse** [comment]
I have created a CL that changes the recipe for the vm builders, adding the clang environment variables.  Other builders, and maybe users, have the problem that the library stdalign.h is a C11 feature, and gcc 4.6, the last version shipped with ubuntu precise, does not support it.  We will need to upgrade our requirements on all platforms, to make sure we support C11.  So this issue will be changed to "Support/Require C11 support for compiling Dart", and we will track our decisions and progress here.

**Comment by whesse** [comment]
@sgjesse @iposva @ricowind

**Comment by zanderso** [comment]
@whesse Are the bots updated? Would it make sense to try to land the BoringSSL update again? Thanks!

**Comment by whesse** [comment]
I had discussions about updating the bots, but there was no bug filed.  I have now requested all Dart buildbot slaves to be updated to trusty, and this should happen quite quickly.  I'll follow up when this is complete.

**Comment by zanderso** [comment]
@whesse friendly ping.

**Comment by whesse** [comment]
I am looking at this issue, and trying to work out the solution.  I will update the bug with progress reports.  We did update all bots to trusty, and then reverted the builders to precise so that the SDK would run on linux releases, like precise, without glibc 2.16.

**Comment by zanderso** [comment]
I think this one is done, so I will close it.
