### ISSUE TITLE
gen_snapshot should accept package map files

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/sdk#26362]
gen_snapshot currently requires a packages directory.  Flutter is migrating from packages directories to .packages map files, and we'd like support for map files in gen_snapshot

**Comment by sethladd** [comment]
Just ran into this myself (trying the same workflow, --release with Mac) :)

**Comment by iposva-google** [comment]
We are moving away from gen_snapshot and adding the missing functionality into dart_bootstrap.

dart_bootstrap has all the handling for package maps and features other advanced loading capabilities (e.g. loading from http:). dart_bootstrap also allows for creation of app snapshots. The things we are moving over from gen_snapshot is the URI mapping and manifest file handling.

**Comment by eseidelGoogle** [comment]
We're starting to recommend users to `flutter build apk --release` which causes them to hit this.

We could work around it in the flutter tool, but it would be best if we didn't have to.  Let me know if we should.

**Comment by sethladd** [comment]
Looks like the CL landed (woot!). Should we close this, or is there more to do here?

**Comment by jason-simmons** [comment]
I believe there's still some work remaining on the Dart side.  After that, we'll need to change flutter_tools to invoke gen_snapshot with the --packages flag.

**Comment by a-siva** [comment]
Landed https://github.com/dart-lang/sdk/commit/11682cd4c7e4d5a3b6be863bc9e84d207fe922df https://github.com/dart-lang/sdk/commit/aca3d3eedffa7c1bef890f62fe8f1af15d4d4805 and https://github.com/dart-lang/sdk/commit/d41d5dc414bec844d755d017000780c4eec0725d to fix the dart side issues.
