### ISSUE TITLE
unresolved type arguments to dynamic generic function invocation

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26368]
Given an example like:
```dart
void _test(Int2Int2Int f) {
  int y = f(123, 456);
  Expect.equals(y, 123);
  // `f` doesn't take type args.
  Expect.throws(() => (f as dynamic)/*<int>*/(123, 456)); 
}
```

... the `<int>` TypeArgumentList appears to be unresolved: the TypeName.type is null.

Probably resolution is just skipping that subtree?

Not a big deal, this only came up in a test case I was trying to write. Not sure if MethodInvocation has the same problem, I'll try it out and report back.

**Comment by jmesserly** [comment]
Methods appear to have the same problem:
```dart
class C {
  /*=T*/ m/*<T extends num>*/(/*=T*/ x, /*=T*/ y) => min(x, y);
  int m2(int x, int y) => min(x, y);
}
main() {
  Expect.equals(123, (new C() as dynamic).m/*<int>*/(123, 456));
  Expect.throws(() => (new C() as dynamic).m2/*<int>*/(123, 456));
}
```
I don't understand why methods don't work, though. In resolver.dart, I can see that visitFunctionExpressionInvocation is skipping the type args. But visitMethodInvocation it is not skipped, as far as I can see. Maybe it comes through as a FunctionExpressionInvocation?

Another strange issue:
``dart
  dynamic c = new C()l
  Expect.equals(123, c.m/*<int>*/(123, 456));
  Expect.throws(() => c.m2/*<int>*/(123, 456));
```
Now I get `[error] The type '(int, int) → int' is declared with 0 type parameters, but 1 type arguments were given` from the m2 line. Uh, that's great *but* ... why did it infer an explicit `dynamic` local var?

**Comment by jmesserly** [comment]
CC @leafpetersen @bwilkerson as FYI. My sense is this is not immediately high priority but I wanted y'all to be aware in case you hit this.

**Comment by scheglov** [comment]
Works for me.
See the attached screenshots, note that `TypeNameImpl` with name `int` has `type` and `element` set.

![image](https://cloud.githubusercontent.com/assets/384794/15156053/23c6ad02-169a-11e6-8e90-8f798323de06.png)


![image](https://cloud.githubusercontent.com/assets/384794/15156078/398e0fea-169a-11e6-9b3a-9c0175ee73b0.png)

**Comment by jmesserly** [comment]
okay I can take another look. Possibly has been fixed or is somehow an artifact of how we build DDC's tests (for speed, they all use the same AnalysisContext, which might stress things more than usual)

**Comment by jmesserly** [comment]
I can still reproduce this in DDC. The full test file is:
https://github.com/dart-lang/dev_compiler/blob/ef2f54c5d20c01fe29b2d7377ab2886a360e0c0a/test/codegen/language/generic_tearoff_test.dart#L20

To reproduce this line has to be removed:
https://github.com/dart-lang/dev_compiler/blob/ef2f54c5d20c01fe29b2d7377ab2886a360e0c0a/lib/src/compiler/code_generator.dart#L523
```dart
if (node.type == null) return js.call('dart.dynamic');
```
then this command line will do it from a DDC checkout (after `pub get`)
```
$ ./bin/dartdevc.dart compile -o out.js --url-mapping=package:expect/expect.dart,test/codegen/expect.dart test/codegen/language/generic_tearoff_test.dart 
```

results in
```
  The null object does not have a getter 'isVoid'.
  
  NoSuchMethodError: method not found: 'isVoid'
  Receiver: null
  Arguments: []
  dart:core                                                      Object.noSuchMethod
  package:dev_compiler/src/compiler/code_generator.dart 2244:14  CodeGenerator._emitType
  package:dev_compiler/src/compiler/code_generator.dart 525:12   CodeGenerator.visitTypeName
  dart:_internal                                                 ListIterable.toList
  package:dev_compiler/src/compiler/code_generator.dart 2566:52  CodeGenerator._emitFunctionTypeArguments
  package:dev_compiler/src/compiler/code_generator.dart 2548:12  CodeGenerator._emitInvokeTypeArguments
  package:dev_compiler/src/compiler/code_generator.dart 2528:22  CodeGenerator._emitFunctionCall
  package:dev_compiler/src/compiler/code_generator.dart 2650:7   CodeGenerator.visitFunctionExpressionInvocation
  package:analyzer/src/dart/ast/ast.dart 5288:15                 FunctionExpressionInvocationImpl.accept
  package:dev_compiler/src/compiler/code_generator.dart 4143:23  CodeGenerator._visit
  package:dev_compiler/src/compiler/code_generator.dart 2394:29  CodeGenerator.visitExpressionFunctionBody
  package:analyzer/src/dart/ast/ast.dart 3964:15                 ExpressionFunctionBodyImpl.accept
  <snip>
```

I'm not sure if it's something we're setting up in the AnalysisContext? We are turning on summaries including for the SDK.

**Comment by jmesserly** [comment]
Oh ... you know what. I totally forgot, these bugs almost always due to ResolutionCopier not copying over the data. We clone the AST before we generate code in DDC:
https://github.com/dart-lang/dev_compiler/blob/ef2f54c5d20c01fe29b2d7377ab2886a360e0c0a/lib/src/compiler/reify_coercions.dart#L120

I've fixed a handful of bugs where elements and types are not copied over (you can see some of our workarounds below in _TreeCloner, some of those can probably be removed now)

**Comment by jmesserly** [comment]
Ah, yeah, ResolutionCopier is not copying over TypeName.type, I fixed the problem with this change:
```dart
  @override
  TypeName visitTypeName(TypeName node) {
    var clone = super.visitTypeName(node);
    clone.type = node.type;
    return clone;
  }
```

I think we didn't hit this before because usually we have an element for the generic method we're calling, or in the case of a constructor `new List<int>.from(...)` we have the constructor element as well as the full type. But for generic methods `f.m<int>(...)` we only have the TypeArgumentList and its `List<TypeName>` nodes available.

**Comment by scheglov** [comment]
Is this the problem?
AFAIK `ResolutionCopier` does copy `TypeName.type`.

```
  @override
  bool visitTypeName(TypeName node) {
    TypeName toNode = this._toNode as TypeName;
    if (_and(_isEqualNodes(node.name, toNode.name),
        _isEqualNodes(node.typeArguments, toNode.typeArguments))) {
      toNode.type = node.type;
      return true;
    }
    return false;
  }
```

  But it does not process `MethodInvocation.typeArguments`.

```
  @override
  bool visitMethodInvocation(MethodInvocation node) {
    MethodInvocation toNode = this._toNode as MethodInvocation;
    if (_and(
        _isEqualNodes(node.target, toNode.target),
        _isEqualTokens(node.operator, toNode.operator),
        _isEqualNodes(node.typeArguments, toNode.typeArguments), <<< This!
        _isEqualNodes(node.methodName, toNode.methodName),
        _isEqualNodes(node.argumentList, toNode.argumentList))) {
      toNode.propagatedInvokeType = node.propagatedInvokeType;
      toNode.propagatedType = node.propagatedType;
      toNode.staticInvokeType = node.staticInvokeType;
      toNode.staticType = node.staticType;
      return true;
    }
    return false;
  }
```

**Comment by jmesserly** [comment]
Oh! yeah that could be it

**Comment by scheglov** [comment]
https://codereview.chromium.org/1970053002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/fad1ca3460c57d88c912a2d77c95f9dc700a41bd

**Comment by jmesserly** [comment]
awesome, thank you!
