### ISSUE TITLE
Js-interop: analyzer errors when declare @JS() functions with callbacks 

### ISSUE THREAD

**Issue by denis-aes** [dart-lang/sdk#26371]
I'm using node.js API from compiled Dart app. With package:js bindings for this api's:

```
    @JS('http')
    library http;
    import "package:js/js.dart";

    external Server createServer(
[ void requestListener(IncomingMessage request, ServerResponse response)])
```

And calling this from main.dart:

```
import "package:js/js.dart";
import "node_partly.dart" as http;

main() async {
  http.Server server = http.createServer(allowInterop(handler));
  server.listen(9876);
}

void handler(http.IncomingMessage request, http.ServerResponse response){
  response.write("Hello, from dart server! \n");
  response.write("You asked for ${request.url}");
  response.end();
}
```
Everything works fine.

But. Analyzer fails with error

> WARNING: The argument type 'JSFunction' cannot be assigned to the parameter type '(IncomingMessage, ServerResponse) → void'. ( example/main.dart:5)
> The problem is that allowInterop produces "JSFunction" - deprecated class for internal use.

And from point of view of annotations - there should be normal "Function" class.

This is annoying if to pay attention to this. And if I will not pay attention to analyzer errors - I may leave real error in my code.

How can I fix it?

P.S. Using latest dart 1.16

**Comment by a14n** [comment]
I just tested your sample and I don't see any analyzer issue (with Dart 1.16.0).

**Comment by denis-aes** [comment]
@a14n I have 'strong-mode: true' in analyzer options. Maybe this is the reason?

**Comment by a14n** [comment]
I can also see it in strong mode.

**Comment by jacob314** [comment]
Fixed. The problem was the allowInterop method was not taking advantage of the new generic method syntax. Now the type of the Function you pass to allowInterop is preserved.
