### ISSUE TITLE
Not agree with that the variable is not used when it used in assignment expression

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#26370]
Example 1 (OK)
No warning because varibale is used.

``` dart
var x = 0;
x = x + 1;
```

Example 2 (BAD)
Warning about that the varibale is not used.

``` dart
var x = 0;
x += 1;
```

But variable also used because before to add a value (1) to variable `x` this variable `x` is used to get it value (as for me, this has no sence which form of assignment I use if I know that variable would be used for read in the expression, explicitly or implicitly).

But if variable `x` is used to get their value then why I should get message about that the variable`x` not used?

**Comment by mezoni** [comment]
For me this looks very strange when I do same work but I get a some strange warnings on similar work.

Example:

```dart
class Parent {
  Parent() {
    var child1 = child("[");
    var child2 = child("]");
    var child3 = child("("); // <============ The value of local variable `child` is not used
    var child4 = child(")");

    child1 = child1 + child2;
    child3 += child4; // <============ Is this form of assignment is very bad?
  }

  Map<String, Child> children = <String, Child>{};

  Child child(String name) {
    var child = children[name];
    if (child != null) {
      return child;
    }

    child = new Child(name, this);
    children[name] = child;
    return child;
  }
}

class Child {
  Parent parent;

  String name;

  Child(this.name, this.parent);

  Child operator +(Child other) {
    return new Child(name + other.name, parent);
  }
}
```

**Comment by srawlins** [comment]
Sorry for the delayed response. `x` _is_ used to get the value for `+`, but is otherwise unused. This is considered unused.
