### ISSUE TITLE
VM treats same-name initializing formal and parameter as compile-time error.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26378]
The code:
```dart
class C { 
  final x;
  final y; 
  C(this.x, x) : y = x;
}
```
causes the VM to say:
```
'.../xx.dart': error: line 7 pos 20: duplicate formal parameter 'x'
  C(this.x, String x) : y = x;
```
This should not happen. The only place in the specification that can cause such an error is section 6.1 (Scoping):

> It is a compile-time error if there is more than one entity with the same name declared in the same scope.

However, an initializing formal does not introduce the name into the parameter scope, so there is no scope with the name `x` occurring twice - section 10.6.1:

> Using an initializing formal `this.id` in a formal parameter list does not introduce a formal parameter name into the scope of the constructor. 

Neither dart2js nor the Dart analyzer report an error for the program.

**Comment by floitschG** [comment]
Given that we would like to revisit the scoping, I think that this should not be treated as high priority.

**Comment by lrhn** [comment]
Agree. If anything, it's a good thing that this has never worked. That reduces the risk of breaking existing code if we make `this.x` introduce `x` into the parameter scope.

**Comment by mezoni** [comment]
Even if the positional parameters means a parameters which perfectly can be used without the name (only by the position) but I think that allowing the same identifiers is a bad idea.

Here is example:

```dart
// Here allowed?
 C(this.x, x);

// Here not allowed!
 C({this.x, x});
```

**Comment by floitschG** [comment]
@mezoni Agreed.
The spec currently allows it, but we are probably going to change name-scoping in constructors with `this.x`.

**Comment by iposva-google** [comment]
@lrhn @floitschG Given the discussion it is unclear to me whether this should even be a priority for fixing.

**Comment by floitschG** [comment]
@iposva-google: agreed.
Closing as wont-fix. We really want to improve the situation for `this.x` in the constructors, and then this issue won't matter anymore.
