### ISSUE TITLE
multi-line comments parsed incorrectlly

### ISSUE THREAD

**Issue by rinick** [dart-lang/sdk#26382]
```
/*http://a.com/*/
```

this comment breaks dart code, while it works fine in js and in c

**Comment by bwilkerson** [comment]
This is working as expected. According to section 20.1.2 of the Dart Language Specification:

> A multi-line comment begins with the token /* and ends with the token */. Everything between /* and */ must be ignored by the Dart compiler unless the comment is a documentation comment. Comments may nest.

Any multi-line comment can nest, so the "/*" near the end of that line is taken to be the start of a nested multi-line comment.

**Comment by mezoni** [comment]
/*http://a.com/*/

/* -> start 1
http://a.com -> content
/* -> start 2
/ -> content

So, token (comment) is not terminated if it are at the `end of file` or it are malformed if it are not at the end of file.
