### ISSUE TITLE
String.split docs don't agree with actual behavior.

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#26388]
The docs [here](https://api.dartlang.org/stable/1.16.0/dart-core/String/split.html) say
"If this string is empty, the result is an empty list if pattern matches the empty string, and it is [""] if the pattern doesn't match."
```dart
var string = '';
string.split('');                       // []
string.split("a");                      // ['']
```
but when I run this test, I don't get the claimed output, I get `[]` both times.

I notice that the documented behavior matches JavaScript, so it's like these docs are for the wrong language.  Please fix.

(Also, unrelated, the docs should consistently use single quotes.  Notice the "a".)

**Comment by lrhn** [comment]
The behavior *should* match JavaScript - it means that the translation to JavaScript is simple and efficient.
So, this is a bug.

Splitting a string on a pattern that doesn't match anywhere in the string should return the original string.
We have a requirement that after a split, an initial or trailing empty string is not included, and it seems that code fails to distinguish the case where the initial empty string is not the result of a split.

**Comment by rakudrama** [comment]
Surprising result considering these cases are tested:
https://github.com/dart-lang/sdk/blob/master/tests/corelib/string_split_test.dart#L46

**Comment by rakudrama** [comment]
Note **print**ing strings does not include the quote.
So `['a']` prints as `[a]` and `['']` will prints as `[]`.
@trinarytree, can you print the length?

**Comment by floitschG** [comment]
I just tried with dartpad, and there the length is 1.
I have to admit that it is confusing, that the string is not visible.

**Comment by trinarytree** [comment]
My apologies.  @rakudrama , you are right - I was fooled by List#toString not printing the quotes.

```dart
// This fooled me.
print(''.split(''));
print(''.split('a'));

// This shows the truth more clearly.
print(''.split('').map((s) => '"$s"').toList());
print(''.split('a').map((s) => '"$s"').toList());
```
... and now I can see that the production code for our project has a bug we need to fix.  :-)
