### ISSUE TITLE
Hitting assert in IsSubtypeOf code

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26387]
I'm hitting an assert, when I apply a CL that adds more types to the collections.

```
runtime/vm/object.cc:5110: error: expected: (index >= 0) && (index < Length())
Aborted (core dumped)
```

The function is:
```
RawAbstractType* const* TypeArguments::TypeAddr(intptr_t index) const {
  // TODO(iposva): Determine if we should throw an exception here.
  ASSERT((index >= 0) && (index < Length()));
  return &raw_ptr()->types()[index];
}
```

The CL is here: https://codereview.chromium.org/1937103002/

Once patched in, run:
`out/DebugX64/dart --compile_all --error-on-bad-override tests/language/hello_dart_test.dart`

/cc @crelier

**Comment by crelier** [comment]
We have a bug in the cloning of generic function types from the mixin class to the mixin application class. Working on it.
