### ISSUE TITLE
Observatory timeline events only include walltime, not cpu time

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26396]
Chromium trace events record both walltime and cpu time, so you can tell from the trace when the processor in question was just descheduled.

I'm not exactly sure how they do that, but I don't see the same in traces with observatory.  At least for things like Dart_GetField.  (See https://github.com/dart-lang/sdk/issues/26395).

@abarth or @johnmccutchan or @chinmaygarde might know.

**Comment by eseidelGoogle** [comment]
For example, here is a screenshot of a trace inside chrome:tracing which includes "selftime":
<img width="396" alt="screen shot 2016-05-03 at 7 52 36 pm" src="https://cloud.githubusercontent.com/assets/11857803/15004180/ab224e14-1168-11e6-9296-2a8192af9941.png">

**Comment by johnmccutchan** [comment]
If someone could point me to what Chrome is using to determine 'cpu time' on Linux/Android/Mac/Windows I can wire this up quickly.

**Comment by eseidelGoogle** [comment]
I suspect that is captured by thread_duration in the TraceEvent code.  @jamesr might know.

https://github.com/domokit/base/blob/master/trace_event/trace_event_impl.cc#L825
Which is updated via UpdateDuration:
https://github.com/domokit/base/blob/master/trace_event/trace_event_impl.cc#L682

Which is set during creation it looks like?
https://github.com/domokit/base/blob/2cf4e98a417f9694c5c39c49b12a3fa07335c4db/trace_event/trace_event_impl.cc#L1193

Presumably this timing based on "thread ticks" instead of walltime as per the ThreadTicks class in base?
Here is the Mac implementation for example:
https://code.google.com/p/chromium/codesearch#chromium/src/base/time/time_mac.cc&q=ThreadTicks&sq=package:chromium&type=cs&l=73

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1960483002/

**Comment by eseidelGoogle** [comment]
Thank you very very much!
