### ISSUE TITLE
Treat method tearoffs as definite functions in strong mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26393]
The code below produces this warning:

```
[warning] Unsound implicit cast from (dynamic) → void to (int) → void (/Users/leafp/tmp/tearoff.dart, line 4, col 10)
```

The warning is because `foo` is being treated as "fuzzy".  We can (and should) treat a direct method tear off as a definite function and emit no warning here.

```dart
class A {
  void foo(dynamic x) {}
  void test(void f(int x)) {
    test(foo);
  }
}
```

**Comment by leafpetersen** [comment]
cc @ochafik

**Comment by jmesserly** [comment]
Huh. I could've sworn we had fixed this at one point.

FWIW, I think we do the right thing at runtime in DDC :)

**Comment by jmesserly** [comment]
ohhh.... I think I came across the source of this bug in https://codereview.chromium.org/2211053002/diff/1/pkg/analyzer/lib/src/task/strong/checker.dart

... would be pretty easy to fix, I can just delete the "instanceMethods" special case.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2212233003

**Comment by jmesserly** [comment]
That fix was wrong, but from the discussion I think I have the right fix now. Will upload shortly.
