### ISSUE TITLE
Observatory tracing UI is very confusing

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26394]
1. When you open it, its not clear what button you need to push.
2. Not clear how you change categories.
3. After you start tracing, no indication that it's tracing.
4. Clicking stop tracing hangs the target device while it downloads the trace (expected) but provides no progress indicator (even indeterminant) in observatory.

@johnmccutchan

**Comment by johnmccutchan** [comment]
Agreed, the UI is rough.
