### ISSUE TITLE
Dart_GetField timeline events should include field name

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26395]
https://github.com/dart-lang/sdk/blob/f55c9c54a8821d9a421a64810e770beb491f754d/runtime/vm/dart_api_impl.cc#L4243
Is the line which creates this timeline event.

But I'm not sure of a way to make TimelineDurationScope include args, like for example how Chromium trace macros do:
https://github.com/domokit/base/blob/master/trace_event/trace_event.h#L47

@johnmccutchan likely knows.

**Comment by eseidelGoogle** [comment]
In my case I'm seeing a few long Dart_GetField events.  I'm tracing dart running on a super underpowered (single core, hyperthreaded) device and so I'm sure these long Dart_GetField events are just when my dart thread is descheduled.  But without cpu time from https://github.com/dart-lang/sdk/issues/26396 it's hard to know for sure.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1951003002/
