### ISSUE TITLE
Flutter traces include information from before trace started?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26401]
```
cd flutter/examples/material_gallery
flutter run
```
1. open observatory
2. click 'timeline'
3. click 'start recording'
4. click 'stop recording'
5. click 'refresh'

Notice how the trace includes a bunch of events from before you clicked 'start recording'.  All the interesting bits of your trace (including the dart code and flutter engine, etc.) are at the far right of the timeline.   This is particularly true if you've left the app running for a while.

@johnmccutchan @chinmaygarde 

![screenshot from 2016-05-04 10 40 05](https://cloud.githubusercontent.com/assets/11857803/15023265/a0bd672a-11e4-11e6-9041-a3e75c4010fb.png)

**Comment by eseidelGoogle** [comment]
It can also end up with traces after you stopped tracing?  Presumably they're still in the ringbuffer and we're dumping the whole ring buffer and not just the range we actually traced?

**Comment by johnmccutchan** [comment]
Observatory's timeline view is a hybrid view of the timeline and the cpu profiler. The CPU profiler is always running, so the blue bars you see before and after the trace are actually CPU samples-- this can be observed by selecting some of them and looking at the inspector panel at the bottom.

**Comment by eseidelGoogle** [comment]
This seems confusing.  I explicitly started/stopped and then am confused that I see stuff outside of when I started/stopped.
