### ISSUE TITLE
Dart hangs randomly on Windows

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#26400]
We have had really serious issues with Dart (1.15.0 and 1.16.0) on Windows.
On Windows 10, we are not having issues, and our HTTP Server is running for a whole week so far.
On Windows 7 and Windows Server 2012 R2 Datacenter, the Dart VM hangs with no errors every day. It is running as a Windows Service in this case. No errors are ever reported.

I filed this separately from #25582, as that seems to be more development-tools related.

**Comment by mezoni** [comment]
The same problem. Atom.io plugin called `dartlang` almost always stops to analyze the code.
As far as I know it (plugin) uses Dart analysis server (which is the problem).
I don't think that the problem in the analysis server but problem is in that the server stops working after some time (it is impossible to describe in detail because it is not subject to the understanding).

**Comment by mezoni** [comment]
What about the thing if the Dart developers should compile Dart VM with source symbols, run some tools and when it "hangs" then attach .NET debugger and seeing it where it loops?

P.S.
I like debuggers!
My favorites was these very cool tools:
- Turbo Debugger
- SoftIce
- WinIce

Interactive disassembler IDA Pro also was my coolest and useful tool!
...but this was a long time ago.

Как говорится "отладчик вам в руки" и проблема будет решена в мгновенье ока.

**Comment by kaendfinger** [comment]
@mezoni That's probably the easiest way to figure it out.

**Comment by zengyun261** [comment]
+1
I don't know how to solve the problem. 

OS: Windows Server 2012, Windows 10
Dart version: 1.14,1.15,1.16...

**Comment by zengyun261** [comment]
![1](https://cloud.githubusercontent.com/assets/4257565/15274756/1cf89ce0-1aed-11e6-8ffc-5ba6cf57595c.jpg)
![2](https://cloud.githubusercontent.com/assets/4257565/15274758/22949a6e-1aed-11e6-94ad-1f56c202f4eb.jpg)
![3](https://cloud.githubusercontent.com/assets/4257565/15274759/27d79e40-1aed-11e6-9644-ca4490e7e9bf.jpg)
![4](https://cloud.githubusercontent.com/assets/4257565/15274760/2a52c6d6-1aed-11e6-9dfe-307c328b1465.jpg)

**Comment by kaendfinger** [comment]
@zengyun261 Is that a debugging session with a stacktrace when Dart froze?

**Comment by zengyun261** [comment]
runtime/vm/os_thread_win.cc:   void OSThread::Join(ThreadJoinId id) 

Because the thread handle was closed,after the thread exits, the thread ID may be used by other processes, OpenThread returns the thread ID from other processes, WaitForSingleObject can not be returned. 
By Google Translate :(

**Comment by zanderso** [comment]
@zengyun261 Many thanks for tracking this down. There are actually two problems here. First, the thread handle recycling problem, and second: a worker thread shouldn't add itself to the idle list until *after* reaping exited threads. I will take a look at these.

@kaendfinger If you could still verify that you aren't hitting a different problem, that would be helpful. Thanks!

**Comment by kaendfinger** [comment]
@zanderso Will do.

**Comment by zanderso** [comment]
Update: The above change should fix @zengyun261's hang. @zengyun261 if you're able to verify the fix that would be very helpful! @kaendfinger we think it's likely that you were hitting the same problem, so it might be worthwhile seeing if it's gone after the change. This change will be in the next dev release, you can also grab a recent bleeding edge release e.g. from here: https://gsdview.appspot.com/dart-archive/channels/be/raw/138232/sdk/dartsdk-windows-x64-release.zip

**Comment by kaendfinger** [comment]
@zanderso Sounds good, we will do some testing and verify the issue is no longer present.

**Comment by julemand101** [comment]
Seems to have fixed the problem I had with random hangs on my Windows 8 machine. My WebSocket server has now run in over 24 hours (before the fix, my server hangs after a few hours). I will let the server run over the weekend and see if it still runs on Monday.

**Comment by kaendfinger** [comment]
@zanderso Things are looking better for us as well.

**Comment by zanderso** [comment]
Great! I filed an issue to get the fix merged into the stable channel.

**Comment by mit-mit** [comment]
The next stable release is roughly a week from now -- can the fix in stable wait until then?

**Comment by mit-mit** [comment]
Closing this as per above the fix is in. It will be available in 1.17 stable scheduled for next week.

**Comment by zanderso** [comment]
Reopening to wait for customers to try the 1.16 patch release when it is available.

**Comment by mit-mit** [comment]
@zanderso per my comment two days ago we are not expecting to do a 1.16 stable patch release, buy rather release this in the first 1.17  stable build scheduled for next week. Does that not work?

**Comment by zanderso** [comment]
@mit-mit no one responded to your question in the affirmative, so I assumed we were still doing a patch release. I don't believe this change was cherry-picked into the dev branch, so I don't believe it will show up in 1.17 stable unless we patch it into 1.16 stable. @whesse please confirm that you are still working on a 1.16 patch release?

**Comment by zanderso** [comment]
1.16.1 stable has been released with this fix. @kaendfinger if you could give it a shot that'd be great. Thanks!

**Comment by zanderso** [comment]
@mit-mit Thanks for your concern about this issue. I will close it myself after @kaendfinger verifies that the 1.16.1 release does not exhibit the problem.

**Comment by zanderso** [comment]
@kaendfinger reported offline that there have been no hangs since switching to 1.16.1, so I will close.
