### ISSUE TITLE
DARTIUM CRASH WITH SDK V1.16.0

### ISSUE THREAD

**Issue by brunoleguernic** [dart-lang/sdk#26408]
HI,
I have an APP client/server in developpement, all seems good in SK V1.15.0.
When I switch to V1.16.0, impossible running the app under new DARTIUM.

Here the switching steps:

v1.15 PUB SERVE
F:\dart-sdk\bin\pub.bat serve web --port=49369
Loading source assets...
Loading polymer transformers...
Serving amm7 web on http://localhost:49369
Build completed successfully
[web] GET index.html => amm7|web/index.html
[web] GET Served 37 assets.
[web] GET main_page.css => amm7|web/main_page.css
[web] GET Served 606 assets.
[web] GET Served 5 assets.
[web] GET Served 39 assets.
[web] GET packages/amm7/ico/connected.svg => amm7|lib/ico/connected.svg
[web] GET images/touch/chrome-touch-icon-192x192.png => amm7|web/images/touch/chrome-touch-icon-192x192.png

PUBSPEC:
name: 'amm7'
version: 0.7.0
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  mime: any
  google_maps: any
  mailer: any
  options_file: any
  sqljocky: any
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.16
  web_components: ^0.12.0

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
ALL IS OK
SWITCH TO V1.16.0
PUB REPAIR CACHE
Working dir: F:\amm7
F:\dart-sdk\bin\pub.bat cache repair
Downloading analyzer 0.22.4...
Downloading analyzer 0.24.6...
Downloading analyzer 0.25.0+1...
Downloading analyzer 0.25.2+1...
Downloading analyzer 0.26.4...
Downloading analyzer 0.27.1...
Downloading analyzer 0.27.2...
Downloading args 0.12.2+6...
Downloading args 0.13.2...
Downloading args 0.13.4...
Downloading async 1.3.0...
Downloading async 1.9.0...
Downloading async 1.10.0...
Downloading barback 0.15.2+4...
Downloading barback 0.15.2+6...
Downloading barback 0.15.2+7...
Downloading bignum 0.0.7...
Downloading boolean_selector 1.0.1...
Downloading browser 0.10.0+2...
Downloading bwu_datagrid 0.0.20...
Downloading bwu_datagrid 0.0.22...
Downloading bwu_datagrid 0.0.24...
Downloading bwu_utils 0.0.2...
Downloading bwu_utils_browser 0.0.3...
Downloading bwu_utils_browser 0.0.3+1...
Downloading charcode 1.1.0...
Downloading cli_util 0.0.1+1...
Downloading cli_util 0.0.1+2...
Downloading code_transformers 0.2.5...
Downloading code_transformers 0.2.7...
Downloading code_transformers 0.2.9...
Downloading code_transformers 0.2.9+3...
Downloading code_transformers 0.2.11...
Downloading code_transformers 0.4.0...
Downloading code_transformers 0.4.2+1...
Downloading collection 1.1.0...
Downloading collection 1.1.1...
Downloading collection 1.5.1...
Downloading collection 1.6.0...
Downloading convert 1.0.1...
Downloading convert 1.1.0...
Downloading convert 1.1.1...
Downloading core_elements 0.6.0+5...
Downloading core_elements 0.6.1+2...
Downloading core_elements 0.7.1+2...
Downloading core_elements 0.7.1+6...
Downloading crypto 0.9.0...
Downloading crypto 0.9.2+1...
Downloading crypto 1.0.0...
Downloading cryptoutils 0.2.0+2...
Downloading csslib 0.11.0+4...
Downloading csslib 0.12.1...
Downloading csslib 0.12.2...
Downloading csslib 0.13.1...
Downloading custom_element_apigen 0.1.3...
Downloading custom_element_apigen 0.1.7+1...
Downloading dart_style 0.1.8+2...
Downloading dart_style 0.2.1...
Downloading dart_style 0.2.4...
Downloading fixnum 0.9.1+2...
Downloading glob 1.0.5...
Downloading glob 1.1.2...
Downloading google_maps 2.0.7...
Downloading google_maps 3.0.2...
Downloading google_maps 3.1.0...
Downloading html 0.12.1+2...
Downloading html 0.12.2+1...
Downloading html 0.12.2+2...
Downloading html5lib 0.12.0...
Downloading http 0.11.3...
Downloading http 0.11.3+3...
Downloading http_multi_server 1.3.2...
Downloading http_multi_server 2.0.1...
Downloading http_parser 0.0.2+8...
Downloading http_parser 2.2.1...
Downloading initialize 0.2.0...
Downloading initialize 0.6.1...
Downloading initialize 0.6.1+2...
Downloading initialize 0.6.2+2...
Downloading intl 0.12.0+3...
Downloading intl 0.12.4+1...
Downloading intl 0.12.7...
Downloading intl 0.12.7+1...
Downloading js_wrapping 0.1.2...
Downloading js_wrapping 0.2.0+1...
Downloading logging 0.9.3...
Downloading logging 0.11.1...
Downloading logging 0.11.2...
Downloading logging 0.11.3...
Downloading mailer 0.8.12...
Downloading mailer 1.0.0...
Downloading matcher 0.12.0+1...
Downloading matcher 0.12.0+2...
Downloading mime 0.9.3...
Downloading observe 0.13.0...
Downloading observe 0.13.1+1...
Downloading observe 0.13.1+3...
Downloading observe 0.13.3+1...
Downloading options_file 0.10.0...
Downloading options_file 0.11.0...
Downloading package_config 0.1.3...
Downloading paper_elements 0.6.1...
Downloading paper_elements 0.6.2+3...
Downloading paper_elements 0.7.1+1...
Downloading paper_elements 0.7.1+2...
Downloading path 1.3.3...
Downloading path 1.3.6...
Downloading path 1.3.9...
Downloading petitparser 1.3.7...
Downloading petitparser 1.4.3...
Downloading petitparser 1.5.1...
Downloading petitparser 1.5.3...
Downloading plugin 0.1.0...
Downloading polymer 0.15.5+4...
Downloading polymer 0.16.3+3...
Downloading polymer 0.16.4+2...
Downloading polymer 1.0.0-rc.3...
Downloading polymer 1.0.0-rc.16...
Downloading polymer_elements 1.0.0-rc.8...
Downloading polymer_expressions 0.13.1...
Downloading polymer_interop 0.1.1...
Downloading polymer_interop 0.1.2+1...
Downloading polymer_interop 1.0.0-rc.7...
Downloading polymer_interop 1.0.0-rc.9...
Downloading pool 1.0.1...
Downloading pool 1.1.0...
Downloading pool 1.2.2...
Downloading pool 1.2.3...
Downloading pool 1.2.4...
Downloading pub_semver 1.2.1...
Downloading pub_semver 1.2.4...
Downloading quiver 0.18.2...
Downloading quiver 0.21.4...
Downloading quiver_log 1.0.3...
Downloading reflectable 0.3.3...
Downloading reflectable 0.5.2...
Downloading route_hierarchical 0.6.2...
Downloading shelf 0.6.2...
Downloading shelf 0.6.5...
Downloading shelf_static 0.2.3...
Downloading shelf_static 0.2.3+3...
Downloading shelf_web_socket 0.0.1+2...
Downloading shelf_web_socket 0.2.0...
Downloading smoke 0.2.1+1...
Downloading smoke 0.3.4...
Downloading smoke 0.3.5...
Downloading smoke 0.3.6+2...
Downloading source_gen 0.3.0+2...
Downloading source_gen 0.4.8...
Downloading source_map_stack_trace 1.0.4...
Downloading source_maps 0.10.0+1...
Downloading source_maps 0.10.1...
Downloading source_maps 0.10.1+1...
Downloading source_span 1.0.3...
Downloading source_span 1.1.2...
Downloading source_span 1.2.2...
Downloading sqljocky 0.6.2...
Downloading sqljocky 0.14.1...
Downloading stack_trace 0.9.3+2...
Downloading stack_trace 1.3.4...
Downloading stack_trace 1.4.1...
Downloading stack_trace 1.6.4...
Downloading stack_trace 1.6.5...
Downloading stagehand 0.2.2...
Downloading stagehand 1.0.4...
Downloading stream_channel 1.3.1...
Downloading string_scanner 0.1.3...
Downloading string_scanner 0.1.3+1...
Downloading string_scanner 0.1.4+1...
Downloading template_binding 0.14.0+1...
Downloading template_binding 0.14.0+2...
Downloading template_binding 0.14.0+4...
Downloading test 0.12.4+3...
Downloading test 0.12.13...
Downloading typed_data 1.1.2...
Downloading unittest 0.9.3...
Downloading unittest 0.11.6+3...
Downloading unittest 0.11.6+4...
Downloading unittest 0.12.4...
Downloading usage 1.0.0+1...
Downloading usage 1.2.0...
Downloading utf 0.9.0+2...
Downloading utf 0.9.0+3...
Downloading watcher 0.9.5...
Downloading watcher 0.9.7...
Downloading watcher 0.9.7+1...
Failed to repair watcher 0.9.7+1. Error:
HTTP error 404: Not Found
Downloading watcher 0.9.7+2...
Downloading web_components 0.10.1...
Downloading web_components 0.11.4+2...
Downloading web_components 0.12.0+4...
Downloading web_components 0.12.3...
Downloading web_socket_channel 1.0.2...
Downloading when 0.2.0...
Downloading which 0.1.3...
Downloading yaml 2.1.2...
Downloading yaml 2.1.3...
Downloading yaml 2.1.8...
Downloading zengen 0.3.2...
Reinstalled 197 packages.
Failed to reinstall 1 package:
- watcher 0.9.7+1
Reactivating stagehand 1.0.4...
Precompiling executables...
Loading source assets...
Precompiled stagehand:stagehand.
Installed executable stagehand.
Reactivated 1 package.
Process finished with exit code 69

PUB UPGRADE DEPENCIES
Working dir: F:\amm7
F:\dart-sdk\bin\pub.bat upgrade
Resolving dependencies...
  analyzer 0.27.1 (0.27.3 available)
  args 0.13.4
  async 1.10.0
  barback 0.15.2+7
  browser 0.10.0+2
  charcode 1.1.0
  cli_util 0.0.1+2
  code_transformers 0.4.0 (0.4.2+2 available)
  collection 1.6.0
> convert 1.1.1 (was 1.1.0)
  crypto 0.9.2+1 (1.1.1 available)
  csslib 0.13.1
  dart_style 0.2.4
  glob 1.1.2
  google_maps 2.0.7 (3.1.0 available)
  html 0.12.2+2
  initialize 0.6.2+2
  intl 0.12.7+1
  js_wrapping 0.1.2 (0.2.0+1 available)
  logging 0.11.3
  mailer 1.0.0
  mime 0.9.3
  options_file 0.11.0
  package_config 0.1.3
  path 1.3.9
  petitparser 1.5.3
  plugin 0.1.0
  polymer 1.0.0-rc.16
  polymer_elements 1.0.0-rc.8
  polymer_interop 1.0.0-rc.9
  pool 1.2.4
  reflectable 0.5.2 (0.5.4 available)
  source_maps 0.10.1+1
  source_span 1.2.2
  sqljocky 0.14.1
  stack_trace 1.6.5
  string_scanner 0.1.4+1
  typed_data 1.1.2
  unittest 0.11.6+4 (0.12.4+1 available)
  utf 0.9.0+3
  watcher 0.9.7+2
  web_components 0.12.3
  when 0.2.0
  which 0.1.3
> yaml 2.1.9 (was 2.1.8)
Downloading yaml 2.1.9...
Changed 2 dependencies!
Precompiling dependencies...
Loading source assets...
Loading initialize/build/loader_replacer, initialize, polymer_interop/src/build/minify_transformer, reflectable/src/transform_import, web_components/build/mirrors_remover and web_components transformers...
Precompiled dart_style, initialize, intl, polymer, polymer_elements, polymer_interop, reflectable and web_components.
Precompiling executables...
Loading source assets...
Precompiled polymer:new_element.
Process finished with exit code 0

RUNNING MY SERVER OK
F:\dart-sdk\bin\dart.exe --ignore-unrecognized-flags --checked --enable-vm-service:49751 --trace_service_pause_events F:\amm7\bin\amm_server.dart
Observatory listening on http://127.0.0.1:49751
listening for connections on 50443
listening for connections on 50080

RUNNING MY CLIENT NOK IN DARTIUM DEBUG
F:\dart-sdk\bin\pub.bat serve web --port=49782
Loading source assets...
Loading polymer transformers...
Serving amm7 web on http://localhost:49782
Build completed successfully
[web] GET index.html => amm7|web/index.html
[web] GET Served 37 assets.
[web] GET main_page.css => (cached) amm7|web/main_page.css
[web] GET Served 591 assets.
[web] GET images/touch/chrome-touch-icon-192x192.png => amm7|web/images/touch/chrome-touch-icon-192x192.png
[web] GET Served 2 cached assets.
[web] GET Served 3 cached assets.
[web] GET packages/polymer_elements/src/web-animations-js/web-animations-next-lite.min.js.map => polymer_elements|lib/src/web-animations-js/web-animations-next-lite.min.js.map

AFTER A VERY LONG TIME
I HAVE A MESSAGE IN DARTIUM CONSOLE:
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
index.bootstrap.initialize_reflectable_original_main.dart:1 An error occurred loading file: http://localhost:63342/amm7/web/index.bootstrap.initialize_reflectable_original_main.dart

DART2JS IS GOOD
DARTIUM VERSION : 45.0.2454.104
SDK: 1.16.0
WEBSTORM: 2016.1.1
WINDOWS 7

So i come back to V1.15.0....
Regards.
Bruno LE GUERNIC.

**Comment by alexander-doroshko** [comment]
The problem is at [WebStorm side](https://youtrack.jetbrains.com/issue/WEB-21355). It is already fixed and you'll get WebStorm 2016.1.2 release with the fix later this week.
