### ISSUE TITLE
JSON.decode() should create maps with reified key types

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26407]
Currently, when the `JSON` converter decodes a map, that map has no reified generic types. The nature of JSON requires that all objects have string keys, so it should be safe to always create `Map<String, dynamic>`. This makes it possible for users to write code like `JSON.decode(string) as Map<String, dynamic>` and have that work with a strong-mode-enabled runtime.

**Comment by floitschG** [comment]
Somehow forgot to commit this CL...
https://codereview.chromium.org/1980663002

I think I will wait until after 1.50 now. (It is a breaking change, after all).
