### ISSUE TITLE
Less restricted mixins are still not implemented in Dart analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26409]
According #23770 and #23772 less restricted mixins should be implemented in dart analyzer since 1.13. But dart analyzer version 1.16.0-dev.5.4 still reports an error if mixin class extends class other than Object. Example:
```dart
class Sstatic {
}

class M extends Sstatic {
}

class SuperA extends Sstatic {
}

class A = SuperA with M; 

main() {
  new A();
}
```
Dart analyzer reports on this:
`[error] The class 'M' cannot be used as a mixin because it extends a class other than Object`

The following co19 tests fail in dartanalyzer because of this issue:

  co19/Language/Mixins/Mixin_Application/static_warning_t01: CompileTimeError
  co19/Language/Mixins/Mixin_Application/static_warning_t02: CompileTimeError
  co19/Language/Mixins/Mixin_Application/superinterfaces_t06: CompileTimeError
  co19/Language/Mixins/Mixin_Application/superinterfaces_t07: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t11: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t12: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t13: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t14: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t20: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t21: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t22: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t23: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t24: CompileTimeError
  co19/Language/Mixins/Mixin_Application/syntax_t25: CompileTimeError

**Comment by bwilkerson** [comment]
This is still not implemented in dart2js, and we won't enable it by default until it's implemented everywhere. As noted in #23772, you can enable this feature with a command-line flag of `--supermixin`. I'm going to close this issue, but feel free to open a new issue in 'area-language' to request forward motion on this feature.
