### ISSUE TITLE
Static const object is not recognized as a compile-time const.

### ISSUE THREAD

**Issue by renning22** [dart-lang/sdk#26418]
I.e. following code doesn't build with error: "Case expressions must be constant"

```
class Foo {
  static const foo = const Foo._(1);
  
  final int value;
  const Foo._(this.value);
}

main() {
  switch (1) {
    case Foo.foo.value:
      print('1');
  }
}

```

**Comment by mezoni** [comment]
`Foo.foo.value` is not a const it just a final variable.

```dart
final int value;
```

**Comment by iposva-google** [comment]
Here is an example how to use constants in switch statements:
class Foo {
  static const foo = const Foo._(1);
  static const bar = const Foo._(2);

  final int value;
  const Foo._(this.value);
}

main() {
  var values = [const Foo._(2), new Foo._(1), const Foo._(1)];
  for (var val in values) {
    switch (val) {
      case Foo.foo:
        print('1');
        break;
      case Foo.bar:
        print('2');
        break;
      default:
        print('default: ${val.value}');
        break;
    }
  }
  print('done');
}
