### ISSUE TITLE
infer local function return types

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26414]
If I define a named function within a method body, that function's return type should be inferred. This matches the general style of relying on inference rather than explicit typing when possible in method bodies.

**Comment by jmesserly** [comment]
Hah, yeah, we had a bug about this at one point over in DDC (https://github.com/dart-lang/dev_compiler/issues/35).

Inference algorithms get a lot more interesting once local functions are involved :). The C# style inference we were planning (for #25490) is not powerful enough to handle them in general, IIRC. Scala might have something that handles it. There was another interesting paper which I can't find the link to at the moment, that extended colored local inference to handle functions.

That said -- if you only want *return types* and you don't need to have parameter types be inferred, then that should make it a lot easier. We should be albe to infer the same way we infer lambda expressions.

**Comment by nex3** [comment]
Yeah, I'm referring to return types here. Inferring parameters would be cool, but I don't expect it to be possible given the way inference works in the rest of the language.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2209293002
