### ISSUE TITLE
Dartium: Versions later than 1.12.2.0 up to 1.17.0-dev.2.0 - breakpoints gets ignored and other erratic bhv

### ISSUE THREAD

**Issue by rh-galaxy** [dart-lang/sdk#26410]
To reproduce (in win7):

1. svn checkout URL of repository
 - https://svn.code.sf.net/p/galaxyv2/code/
 - Enter 'other/web_play'

2. Get dart IDE up and running

 - If you don't have JRE or JDK installed you can find it here
  http://www.oracle.com/technetwork/java/javase/downloads/index.html

 - From http://www.eclipse.org/downloads/ download "Eclipse IDE for Java Developers"
 - Install by extracting it to any folder where you have write access

 - Download Dartium browser 1.12.2.0
  https://www.dartlang.org/downloads/archive/
  (_versions later than 1.12.2.0 up to 1.17.0-dev.2.0 did not work when
   this was written - breakpoints gets ignored and other erratic bhv_)
 - Unpack folder to the 'eclipse' folder and rename it to 'chromium'
 
 - Start the eclipse program
 - Select any empty folder as your workspace when asked
 
 - Install dart plugin
  This also downloads dart-sdk and places it in eclipse/dart-sdk
   Help -> Install New Software -> Add...
  name     - dart_plugin
  location - http://www.dartlang.org/eclipse/update/channels/stable/
  click Next until the plugin has been installed, then Finish
  
 - Setup Dart
  Window -> Preferences -> Dart -> SDK 
  click Upgrade SDK, OK
 
3. Make a clean copy of this folder (free from '.svn' folders)

 - Run project_clean_copy.bat
  This will create 'web_play_work'.

4. Import project into eclipse workspace

 - In eclipse:
  File -> Import -> General -> Existing project into workspace -> Next
  Browse, Select 'web_play_work' created in step 3 -> Finish
 - Restart eclipse

5. Set a breakpoint

 - C_Collision.dart row 65

6. Build and run (as dart in chromium)

 - Right click on project, Debug as... '3 Dartium launch'
 - make the ship run into the wall - breakpoint hit, the ship explodes on resume

Close all eclipse and replace Dartium with version 1.13+
Repeat 6
 - breakpoint not hit, the ship does never explode (collision not working)

**Comment by rh-galaxy** [comment]
Both versions of the browser show 39.0.2171.0 as the version (chrome://chrome/ address)

**Comment by terrylucas** [comment]
Please try with Dartium 1.17.1 Stable or 1.18 Dev channel there was a fix for BP not being honored checked in

**Comment by rh-galaxy** [comment]
Dartium 1.17.1 is the same...

**Comment by rh-galaxy** [comment]
This should not be closed!

But I have found that it is not an issue of ignored BP, but rather an error in the code path taken where all versions after 1.12.2.0 is not working as expected. The way to reproduce the error is still valid.

**Comment by keertip** [comment]
@rh-galaxy , the Eclipse plugin has not been upgraded to use the latest version of the debugging protocol, which is why it does not work. You can use Intellij or the dev console for debugging in Dartium.
