### ISSUE TITLE
enum E{ @deprecated one, two } main() {} throws exceptions

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#26413]
Add this test to local_reference_contributor_test.dart:

test_enum_deprecated2() async {
    addTestSource('enum E { @deprecated one, two } main() {^}');
    await computeSuggestions();
  }

to yield:

Observatory listening on http://127.0.0.1:49766
unittest-suite-wait-for-done
Task failed: BuildCompilationUnitElementTask for source /completionTest.dart
Unexpected exception while performing BuildCompilationUnitElementTask for source /completionTest.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251:9)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1161:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1159:50)
#7      DartCompletionContributorTest.performAnalysis (file:///usr/local/google/home/jwren/src/github/dart_workspace/sdk/pkg/analysis_server/test/services/completion/dart/completion_contributor_util.dart:546:13)
#8      DartCompletionContributorTest.performAnalysis.<anonymous closure> (file:///usr/local/google/home/jwren/src/github/dart_workspace/sdk/pkg/analysis_server/test/services/completion/dart/completion_contributor_util.dart:552:30)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by 'package:analyzer/src/dart/constant/utilities.dart': Failed assertion: line 176 pos 14: 'node.parent is PartOfDirective' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      ConstantFinder.visitAnnotation (package:analyzer/src/dart/constant/utilities.dart:176:14)
#2      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:310:15)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7663:20)
#4      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:160:17)
#5      EnumConstantDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3731:24)
#6      RecursiveAstVisitor.visitEnumConstantDeclaration (package:analyzer/dart/ast/visitor.dart:1533:10)
#7      EnumConstantDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3727:15)
....

**Comment by srawlins** [comment]
@bwilkerson, if this is on me, I'll fix it.

**Comment by bwilkerson** [comment]
I don't think it is. This isn't specific to the deprecated annotation, any annotation will trigger the bug.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1958433002/
