### ISSUE TITLE
DOMSettableTokenList not visible in Chrome, causes error sending list.value

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26422]
In IDL there's DomTokenList with sub-interface DOMSettableTokenList which has a value attribute which can be set. If we do something like in co19/LayoutTests/fast/dom/icon-size-property_t01 we get back a DOMSettableTokenList, but in Chrome the constructor name is DOMTokenList and the subclass doesn't exist. As a result sending value to it fails.

In Dartium we get the subclass back, and similarly in Safari.

This would probably be better if our toString() on DOMTokenList used the result of stringify rather than printing a generic string.

**Comment by athomas** [comment]
LayoutTests have been deleted.
