### ISSUE TITLE
Bleeding edge VM is 50% slower

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#26423]
All at once our Analysis Server tests started to take 45+ seconds instead of usual under 30 seconds.

@bwilkerson 
@stereotype441 

I've attempted to go back in history to check whether this is a change in tests or Analysis Server, but see the same performance problems. So, I guess this is the VM build I'm using causes the problem.

![image](https://cloud.githubusercontent.com/assets/384794/15086732/986a9b88-1397-11e6-8562-5c399067ef97.png)

![image](https://cloud.githubusercontent.com/assets/384794/15086743/ad2aad10-1397-11e6-9cd0-b28d6c5038bf.png)

![image](https://cloud.githubusercontent.com/assets/384794/15086746/b8a5e632-1397-11e6-90f4-d602d1adf2bf.png)

**Comment by iposva-google** [comment]
@scheglov It would be helpful if you could post the following. Thanks!
- What kind of test are you running? And what is the exact dart invocation line, so that we can reproduce?
- Do you have a CL or a range of CL/versions where this started happening?

Other more specific questions:
- Are you running any of your tests with --compile_all argument?

**Comment by scheglov** [comment]
1. I run the following script:
```
time /Users/scheglov/Applications/dart-1.17.dev2/bin/dart \
    --package-root=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseIA32/packages \
    /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/test_all.dart
```

2. With `1.17.0-dev.2.0 (ref 7f08cfc)` (32 bit) it takes `37 seconds` to run. After rebuilding `packages` it is down to `27 seconds`.

3. With `Dart VM version: 1.17.0-edge.02651a9949b514d78a94caa9a836b8887c2bbf58 (Sat May  7 12:53:11 2016) on "macos_ia32"` it takes `59.7 seconds` to run. After rebuilding `packages` it is down to `43.7 seconds`. But still `16 seconds slower`!

**Comment by pq** [comment]
FWIW we're noticing a possibly correlated dip in our flutter benchmarks as of `dev-3.0`. Any updates would be awesome!

**Comment by fsc8000** [comment]
It seems a recent change to timeline recording may be the issue. I see 9s spent in sys-time - mostly due from the method OS::GetCurrentThreadCPUMicros() used for timeline recording.

real	0m28.712s
user	0m30.103s
sys	0m0.963s

vs.

real	0m39.474s
user	0m35.926s
sys	0m10.163s

@johnmccutchan Is recording the thread's CPU time more expensive on Mac OS? Maybe it should be only switched on on-demand from the observatory?

@scheglov Is this an issue on Linux as well?

Try the following patch to confirm that this is the case:

```
diff --git a/runtime/vm/os_macos.cc b/runtime/vm/os_macos.cc
index 6d2d02a..652e08c 100644
--- a/runtime/vm/os_macos.cc
+++ b/runtime/vm/os_macos.cc
@@ -140,6 +140,7 @@ int64_t OS::GetCurrentMonotonicMicros() {
 
 
 int64_t OS::GetCurrentThreadCPUMicros() {
+  return 0;
   mach_msg_type_number_t count = THREAD_BASIC_INFO_COUNT;
   thread_basic_info_data_t info_data;
   thread_basic_info_t info = &info_data;
```

**Comment by scheglov** [comment]
On Linux `1.17.0-edge.1d2954ee2823a9f1bc999d7be7d4a0ee959e2c52 (Wed May 11 10:39:06 2016) on "linux_x64"` runs tests as fast as `1.16.0 (Tue Apr 26 07:14:44 2016) on "linux_x64"`.

**Comment by johnmccutchan** [comment]
Please confirm https://codereview.chromium.org/1975713003/ fixes the performance regression.

**Comment by johnmccutchan** [comment]
@fsc8000 The issue is that we were calling for the time even when the timeline wasn't recording.

**Comment by pq** [comment]
So awesome.  Thanks John!

**Comment by scheglov** [comment]
Thank you.
Analysis server tests are fast again.
