### ISSUE TITLE
Type promotion is confusing on type parameters

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#26439]
The following is showing a strong mode error in `foo` but not `foo2`.

```dart
void bar(List l) {
  print(l.length);
}

/*=T*/ foo/*<T>*/(/*=T*/ arg) {
  if (arg is List) {
    bar(arg);
  }
}

foo2(arg) {
  if (arg is List) {
    bar(arg);
  }
}

void main() {
  foo([1, 2, 3]);
}
```

The error is on the call to `bar` in `foo`:
```
[error] The argument type 'T' cannot be assigned to the parameter type 'List'.
```

@sigmundch was running into this

**Comment by jmesserly** [comment]
chatted with folks ( @leafpetersen @sigmundch ) but this is by design in the language right now.

**Comment by vsmenon** [comment]
Changed 'broken' to 'confusing'.

This is actually not a strong mode specific issue.  Type promotion - by design - doesn't kick in because `T` and `List` are unrelated.

**Comment by vsmenon** [comment]
This is one of the issues already covered in #25565 - closing in favor of that.
