### ISSUE TITLE
VM fails with misleading message on sufficiently old snapshots

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26438]
The current VM crashes on old snapshots with the message `Dart_LoadScriptFromSnapshot expects parameter 'buffer' to be a script type snapshot.`. This is a serious problem for pub users—pub stores global snapshots of globally-activated executables, and it relies on the VM failing gracefully with an exit code of 253 for outdated snapshots of any age.

For an example of a snapshot that the current VM crashes, see [the one pub uses for testing](https://github.com/dart-lang/pub/blob/2641ca6815bf4555ff8c69ddd4b0a7c9baf5694c/test/asset/out-of-date.snapshot).

I'm marking this as S1 since it can regress core pub functionality.

**Comment by nex3** [comment]
Further experimentation indicates that the VM still emits the correct exit code, even if the message has downgraded, so I'm removing the S1 label.

**Comment by iposva-google** [comment]
Apparently we are checking for the kind of the snapshot before the version. A recent change shuffled the kind bits around, so we will change them back to where they belong. As @nex3 found out, the resulting exit code is still correct, but the message can become confusing.

**Comment by rmacnak-google** [comment]
777d6be7185e576907be1298ac5c7540f41dba9a
