### ISSUE TITLE
Type constraints block downward inference

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26431]
If a type has a generic parameter with a constraint, then that parameter doesn't seem to be inferred using downward inference. See the following example:

```dart
class Foo<T extends Iterable> {}

void main() {
  // [error] Type check failed: new Foo() (Foo<Iterable<dynamic>>) is not of type Foo<List<dynamic>>
  Foo<List> foo = new Foo();
}
```

**Comment by jmesserly** [comment]
I can take a look. This might be related to a TODO, we use matchTypes for downwards constructor inference, which isn't as powerful as the technique we're using for downwards generic methods

**Comment by jmesserly** [comment]
looks like it works now. Sent you a CL that adds a regression test: https://codereview.chromium.org/2214123002
