### ISSUE TITLE
Links in tutorial pages go to API documentation front page

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#26433]
Links in our tutorials (like www.dartlang.org/docs/tutorials/httpserver/) target pages like https://api.dartlang.org/dart_io/HttpResponse.html, which are rewritten to https://api.dartlang.org/stable/1.16.0/index.html.

**Comment by kwalrath** [comment]
Thanks for the report, @karlklose. I've put the info into www.dartlang.org & api.dartlang.org issues, so I'm closing this one.
