### ISSUE TITLE
Wrong console output in WebStorm

### ISSUE THREAD

**Issue by pankleks** [dart-lang/sdk#26443]
Not sure if it's related to IDE / Debug plugin or Dart itself.

I'm debugging web page in Dartium, outputing some console log using `print`.
I have different output in Dartium console and debug console of Web Storm.

Note: Dartium console shows good data, Web Storm console shows wrong data.

What I also noticed, if I set break-point in Web Storm and execute line by line - both consoles shows right data.

I'm not dealing with any async code - only sequential execution.

![image](https://cloud.githubusercontent.com/assets/14176066/15199406/3ff02374-17de-11e6-872f-282b0f01ef6f.png)

Dart SDK 1.16.0
Web Storm: 2016.1.2

**Comment by alexander-doroshko** [comment]
Most likely the issue is at WebStorm side. To investigate we need a sample project and steps to reproduce. Please file an issue with these details in [WebStorm's issue tracker](https://youtrack.jetbrains.com/issues/Web), Dart subsystem.

**Comment by kevmoo** [comment]
@pankleks please post a link to the issue in WebStorm here. Thanks
