### ISSUE TITLE
Dart VM exposes ImmediateCallback from dart:isolate

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#26452]
Consider this program:

```
import 'dart:isolate';

main() {
  print(ImmediateCallback);
}
```

When run with the dart VM, this happens:

```
$ dart -c immediate_callback.dart 
ImmediateCallback
```

When compiled with dart2js, this happens:

```
$ dart2js immediate_callback.dart 
immediate_callback.dart:4:9:
Warning: Cannot resolve 'ImmediateCallback'.
  print(ImmediateCallback);
        ^^^^^^^^^^^^^^^^^
Dart file (immediate_callback.dart) compiled to JavaScript: out.js
```

I would expect that the type ImmediateCallback isn't exposed by dart:isolate on the Dart VM.

This typedef is defined in [runtime/lib/isolate_patch.dart](https://github.com/dart-lang/sdk/blob/master/runtime/lib/isolate_patch.dart#L80)

**Comment by peter-ahe-google** [comment]
@lrhn

**Comment by lrhn** [comment]
This type should be hidden. Patch files should not (and per original specification shouldn't be able to) introduce public names in the patched library.

**Comment by natebosch** [comment]
I think this is resolved now that the VM is using the CFE:

```
file:///tmp/a.dart:4:9: Error: Getter not found: 'ImmediateCallback'.
  print(ImmediateCallback);
        ^^^^^^^^^^^^^^^^^
```

Please reopen if this is still an issue and I'm just using a type that doesn't exist in the patch file.
