### ISSUE TITLE
Dart VM exposes ImmutableMap type from dart:core

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#26451]
Consider this program:

```
main() {
  print(ImmutableMap);
}
```

When run with the dart VM, this happens:

```
$ dart -c immutable_map.dart 
ImmutableMap
```

When compiled with dart2js, this happens:

```
$ dart2js immutable_map.dart 
immutable_map.dart:2:9:
Warning: Cannot resolve 'ImmutableMap'.
  print(ImmutableMap);
        ^^^^^^^^^^^^
Dart file (immutable_map.dart) compiled to JavaScript: out.js
```

I would expect that the type ImmutableMap isn't exposed by dart:core on the Dart VM.

**Comment by peter-ahe-google** [comment]
This class is defined in [runtime/lib/immutable_map.dart](https://github.com/dart-lang/sdk/blob/master/runtime/lib/immutable_map.dart#L6)

**Comment by peter-ahe-google** [comment]
@lrhn

**Comment by fsc8000** [comment]
I think they should just be made private, like we do for _ImmutableList.

**Comment by natebosch** [comment]
I see an error now form the CFE in the dart vm.
