### ISSUE TITLE
Typo in Iterable.where() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26459]
See https://api.dartlang.org/stable/1.16.0/dart-core/Iterable/where.html

> Iterable<E> where(bool f(E element))
> Returns a new lazy Iterable with all elements that satisfy the predicate test.
> 
> The matching elements have the same order in the returned iterable as they have in iterator.
> 
> This method returns a view of the mapped elements. As long as the returned Iterable is not iterated over, the supplied function test will not be invoked. Iterating will not cache results, and thus iterating multiple times over the returned Iterable will invoke the supplied function test multiple times on the same element.
> 

Note that in function signature name of the predicate is `f`, but everywhere in the text the predicate name is `test`

**Comment by lrhn** [comment]
Doh. Thanks for noticing.
