### ISSUE TITLE
No quick fix to implement Function.call()

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26460]
No quick fix for this red code:
![image](https://cloud.githubusercontent.com/assets/4499789/15288611/ad0eed84-1b74-11e6-9e27-a107f00bb445.png)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/1981353002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/67a500e134df0e64cf68cd117c2ea318617b978a
