### ISSUE TITLE
Support for summarized SDKs in the presence of embedders.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26467]
Flutter `analyze` currently uses SDK summaries and gets away with it despite using an embedder.  We've been lucky so far but the skew will certainly get us before long. The rub is that their `embedded_libs` picture of the SDK may differ in significant ways from any given SDK and when it does we'll hit the kinds of issues that mojo is seeing (https://github.com/dart-lang/sdk/issues/26448).

My short-term fix is to disable summaries in the `analyze` command.  The bad news is this will introduce a performance regression.  😢   (The good news is at least we're tracking it.)

In fairly short order it would be great to come up with a better solution.  This bug is a tracker for that.

**Comment by pq** [comment]
(Broadened the discussion to include `sdk_ext`s and so embrace the general `mojo` use case as well.)

**Comment by stereotype441** [comment]
This is a prerequisite for issue #26798.

**Comment by scheglov** [comment]
We now build full Flutter SDK summary, with all its additional artifacts.
