### ISSUE TITLE
Timeline.* should be empty when dart_product mode is set

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#26465]
It's possible they already are @johnmccutchan?  But if they aren't, they definitely should be.

When I recently took a trace of a flutter app for one of our customers (with some particularly slow hardware) I found that 50% of the cpu samples were in Timeline_reportCompleteEvent.  Which is OK for tracing, but definitely not something we'd want in --release mode for Flutter apps.

```
% total time, name:
53.04 Timeline_reportCompleteEvent
12.71 Timeline_getTraceClock
```

**Comment by johnmccutchan** [comment]
These calls are empty in product mode as of last week.
