### ISSUE TITLE
JS Interop: "setter is not defined" if annotation in other file

### ISSUE THREAD

**Issue by denis-aes** [dart-lang/sdk#26468]
I've got annotation like

```
class hash1{     
  external String get _id;     
  external void set _id(String _id);     
  external factory hash1(); 
}
```
You cannot pass _id to factory due to issue https://github.com/dart-lang/sdk/issues/26425
So you should use workaround and set it later, like:
```
var x = new hash1();
x._id = "someValue";
```

If annotation is used in the same file it is defined - everything works ok.

If annotation is imported and used in other file - analyzer shows warninng:

> "The setter '_id' is not defined for the class ..."

Everything compiles and works correctly, but this warning may  mislead.

Example
https://github.com/denis-aes/dartbug-setter-is-not-defined/blob/master/example/main.dart

Actual for dart 1.16.0

**Comment by jacob314** [comment]
The JS$ encoding scheme is the workaround for JS property names that are not public Dart names such as _foo, 43bar, or catch.
For this case, use
JS$_id everywhere in the dart code and the JS property _id will be referenced.
