### ISSUE TITLE
VM: ARM precompiler on Mac assumes iOS ABI

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26464]
SIMARM chooses to use the iOS ABI or the EABI based on whether the host is a Mac or not respectively.  This prevents building an AOT snapshot on a Mac host for an Android target.

**Comment by iposva-google** [comment]
cc @fsc8000

**Comment by rmacnak-google** [comment]
We have similar problems with the code alignment and stack alignment values as well.

**Comment by rmacnak-google** [comment]
Partially addressed by 85cdc0eac20e823c827d65685da8b1a9e1d9c2fe

**Comment by rmacnak-google** [comment]
9f2668c9987f0a86cac9cd46c5e3418df22e9f38
