### ISSUE TITLE
at analyzer 0.27.3 , pub build throws => Invalid argument(s): Illegal character in path

### ISSUE THREAD

**Issue by lukechi1219** [dart-lang/sdk#26469]
but when at analyzer 0.27.2 , pub build will end successfully.

my Dart sdk is 1.16.0 , on Win 10 , IDE is WebStorm.

my project is **sample** polymer-dart project created by **WebStorm** with **Stagehand**.

simillar to this on stack over flow => http://stackoverflow.com/questions/36906719/dart-invalid-arguments-illegal-character-in-path-when-building-on-windows

i found in dart:core/uri.dart 853

```
 if (segment.contains(new RegExp(r'["*/:<>?\\|]'))) {
```

the RegExp seems wrong with **:** included... for Windows path would be C:\Users\Luke...

```
Build error:
Transform WebComponents on d009|web/index.html threw error: Invalid argument(s): Illegal character in path
dart:core/uri.dart 855                                  Uri._checkWindowsPathReservedCharacters
dart:core/uri.dart 956                                  Uri._makeWindowsFileUrl
dart:core/uri.dart 738                                  Uri.Uri.file
package:analyzer/src/string_source.dart 30:45           StringSource.StringSource
package:dart_style/src/dart_formatter.dart 81:28        DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 62:12        DartFormatter.format
package:initialize/transformer.dart 340:32              _BootstrapFileBuilder._buildNewEntryPoint
package:initialize/transformer.dart 225:49              _BootstrapFileBuilder.run
package:initialize/transformer.dart 37:8                generateBootstrapFile
package:web_components/build/web_components.dart 32:29  generateWebComponentsBootstrap
package:web_components/build/web_components.dart 82:25  WebComponentsTransformer.apply.<fn>.<fn>
dart:async/zone.dart 1137                               _RootZone.runUnary
dart:async/future_impl.dart 553                         _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 639                         _Future._propagateToListeners
dart:async/future_impl.dart 426                         _Future._completeWithValue
dart:async/future_impl.dart 481                         _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 41                   _microtaskLoop
dart:async/schedule_microtask.dart 50                   _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149               _RawReceivePortImpl._handleMessage

dart:core                                               Uri.Uri.file
package:analyzer/src/string_source.dart 30:45           StringSource.StringSource
package:dart_style/src/dart_formatter.dart 81:28        DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 62:12        DartFormatter.format
package:initialize/transformer.dart 340:32              _BootstrapFileBuilder._buildNewEntryPoint
package:initialize/transformer.dart 225:49              _BootstrapFileBuilder.run
package:initialize/transformer.dart 37:8                generateBootstrapFile
package:web_components/build/web_components.dart 32:29  generateWebComponentsBootstrap
package:web_components/build/web_components.dart 82:25  WebComponentsTransformer.apply.<fn>.<fn>

```

here's my pubspec.yaml

```
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  analyzer: <0.27.4
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives

```

below is full dep

```
C:\tools\dart-sdk\bin\pub.bat upgrade
Resolving dependencies...
> analyzer 0.27.3 (was 0.27.2) (0.27.4-alpha.6 available)
  args 0.13.4+2
  async 1.11.0
  barback 0.15.2+7
  browser 0.10.0+2
  charcode 1.1.0
  cli_util 0.0.1+2
> code_transformers 0.4.2+2 (was 0.4.2+1)
  collection 1.7.0
+ convert 1.1.1
+ crypto 0.9.2+1 (1.1.1 available)
  csslib 0.13.2
  dart_style 0.2.4
  glob 1.1.2
  html 0.12.2+2 (0.13.0 available)
  initialize 0.6.2+2
  logging 0.11.3
  package_config 0.1.3
  path 1.3.9
  plugin 0.1.0 (0.2.0 available)
  polymer 1.0.0-rc.17
  polymer_elements 1.0.0-rc.8
  polymer_interop 1.0.0-rc.9
  pool 1.2.4
  reflectable 0.5.4
  source_maps 0.10.1+1
  source_span 1.2.2
  stack_trace 1.6.5
  string_scanner 0.1.4+1
+ typed_data 1.1.3
  utf 0.9.0+3
  watcher 0.9.7+2
  web_components 0.12.3
  when 0.2.0
  which 0.1.3
  yaml 2.1.9

```

**Comment by brunoleguernic** [comment]
I have the same problem under Windows 7. I try Linux it's good.
analyzer 0.27.3 (0.27.4-alpha.6 available)
  args 0.13.4+2
  async 1.11.0
  barback 0.15.2+8
  browser 0.10.0+2
  charcode 1.1.0
  cli_util 0.0.1+2
  code_transformers 0.4.2+2
  collection 1.7.0
  convert 1.1.1
  crypto 0.9.2+1 (1.1.1 available)
  csslib 0.13.2
  dart_style 0.2.4
  glob 1.1.2
  google_maps 2.0.7 (3.1.0 available)
  html 0.12.2+2 (0.13.0 available)
  initialize 0.6.2+2
  intl 0.12.7+1
  js_wrapping 0.1.2 (0.2.0+1 available)
  logging 0.11.3
  mailer 1.0.0
  mime 0.9.3
  options_file 0.11.0
  package_config 0.1.3
  path 1.3.9
  petitparser 1.5.3
  plugin 0.1.0 (0.2.0 available)
  polymer 1.0.0-rc.17
  polymer_elements 1.0.0-rc.8
  polymer_interop 1.0.0-rc.9
  pool 1.2.4
  reflectable 0.5.4
  source_maps 0.10.1+1
  source_span 1.2.2
  sqljocky 0.14.1
  stack_trace 1.6.5
  string_scanner 0.1.4+1
  typed_data 1.1.3
  unittest 0.11.6+4 (0.12.4+1 available)
  utf 0.9.0+3
  watcher 0.9.7+2
  web_components 0.12.3
  when 0.2.0
  which 0.1.3
  yaml 2.1.9

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
The RegExp is not (or at least: should not be) applied to the first segment of absolute paths. There is special handling for that.

Is there any way to figure out the exact path that this is failing for?

**Comment by lukechi1219** [comment]
I think the root caust may not the dart sdk, maybe code_transformers.

I tried to add log by editing dart file in sdk folder by add print() in dart:core/uri.dart line: 853 

if (segment.contains(new RegExp(r'["*/:<>?\\|]'))) {

however sdk seems run in snapshot... so editing sorce dart file has no effect...

if I want to add log in dart:core/uri.dart

do I have to re-build whole sdk? Is there any easier way?...

**Comment by natebosch** [comment]
Pub build is no longer supported. Check out the replacement: https://github.com/dart-lang/build/blob/master/docs/getting_started.md
