### ISSUE TITLE
IntelliJ debugger showing instance fields as local variables

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26471]
As of 039473f34947c8dd74cbfaa705e2e560287923bd, when I use the debugger in IntelliJ and I view a context, all of the instance fields show up both as children of "this" and as top-level entries. This clutters the view and makes it hard to distinguish between instance fields and local variables.

I'm guessing that the problem is in the VM because I have not recently updated either IntelliJ or the Dart plugin.

**Comment by alexander-doroshko** [comment]
@bwilkerson May be at IDE side anyway. Can you please paste a screenshot?

**Comment by johnmccutchan** [comment]
@rmacnak-google FYI

**Comment by johnmccutchan** [comment]
@bwilkerson I don't think we've changed anything on the VM side that would cause this.

**Comment by bwilkerson** [comment]
Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/5840555/15329589/1489a816-1c0e-11e6-8a12-00bfc95902a5.png)

There are three local variables (at the end of the top-level list), the rest are local variables.

**Comment by alexander-doroshko** [comment]
Thanks for the screenshot. This is done at IDE level, feel free to close the issue here.

`this` node is collapsed by default, but fields of `this` are usually of interest. So at some point I decided to show them at top level together with local vars and parameters. This is a subject to discuss.

**Comment by alexander-doroshko** [comment]
I can add 'field' icon for fields to distinguish from locals, or just remove them from top level.

**Comment by bwilkerson** [comment]
Personally, I would prefer to have them removed from the top level. While it's true that the fields are often of interest, (a) sometimes they're not and (b) having them grouped under `this` is a well-known way of representing them (every modern debugger I can think of does it that way).

Also, I suspect that having them be duplicated will be confusing to many users. If they remain at the top-level then they definitely need to be marked as fields and you might as well remove the `this` node entirely.

But please at least leave an option for the old behavior. It's much more familiar to most people.

**Comment by alexander-doroshko** [comment]
Ok, done both: 'Field' icon (with static/final/const modifier if needed) and removed fields from top level.

**Comment by bwilkerson** [comment]
Thanks!
