### ISSUE TITLE
dartdevc invocation issues

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26479]
When I build the current SDK and run `dartdevc`, I get the following output:

```
Could not find an option named "dart-sdk".

Usage: dartdevc <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  compile   Compile a set of Dart files into a JavaScript module.
  help      Display help information for dartdevc.

Run "dartdevc help <command>" for more information about a command.
```

It looks like the invocation script is trying to pass a `--dart-sdk` option that isn't recognized. This also seems to happen with 1.17.0-dev.3.0.

**Comment by jmesserly** [comment]
This was fixed in https://github.com/dart-lang/dev_compiler/issues/505 & rolled forward to that commit in https://github.com/dart-lang/sdk/commit/95117b6086362de49c3d4e802985830e69cba7f7 ... but it was very recent (I think last night :) )
