### ISSUE TITLE
public_member_api_docs should not trigger for setters that have getters with docs

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#26481]
If a getter has docs already, there's no reason to generate a public_member_api_docs lint for a setter with the same name.  The dartdoc tool will apply the getter's dartdoc to the set as well.

/cc @pq

**Comment by pq** [comment]
Spot on. Tracked over here: https://github.com/dart-lang/linter/issues/237.

Hoping to get a crack at it this week.

**Comment by abarth** [comment]
Ah, thanks.  I remembered talking this issue over with you but I couldn't find the bug report when I looked for it.

**Comment by pq** [comment]
NP.  It's hard to track issues across multiple repos.  To make things a little easier, I added a `Customer-Flutter` label to the linter issue tracker so now at least we can do a single query:

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3ACustomer-Flutter+

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/linter/commit/199e981f1a30b69812466ab33510b655dd2180ad and integrated as of https://github.com/flutter/flutter/pull/4015 and https://github.com/flutter/flutter/pull/4069.

**Comment by pq** [comment]
Fixed in https://github.com/dart-lang/linter/commit/199e981f1a30b69812466ab33510b655dd2180ad.
