### ISSUE TITLE
Android precompilation harness not forwarding vm arguments to runtime step

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26485]
E.g.,

> Command[precompiler]: DART_CONFIGURATION=ReleaseAndroidARM out/ReleaseAndroidARM/dart_bootstrap --snapshot=/b/build/slave/vm-precomp-android-release-be/build/sdk/out/ReleaseAndroidARM/generated_compilations/precompiler/tests_language_type_variable_identifier_expression_test --snapshot-kind=app-aot --use-blobs --no-sim-use-hardfp --enable_type_checks --ignore-unrecognized-flags --package-root=out/ReleaseAndroidARM/packages/ /b/build/slave/vm-precomp-android-release-be/build/sdk/tests/language/type_variable_identifier_expression_test.dart

...

> Executing adb -s 0713a1e70059a965 shell /data/local/tmp/precompilation-testing/dart_precompiled_runtime --run-app-snapshot=/data/local/tmp/precompilation-testing/test --use-blobs ignored.dart ; echo AdbShellExitCode:  $?
> Stdout:
> VM initialization failed: Wrong features in snapshot, expected 'release no-asserts no-type-checks arm-eabi softfp' found 'release asserts type-checks arm-eabi softfp'

Note that the snapshot generation step has the flag `--enable_type_checks` but run step does not.

@fsc8000 @mkustermann

**Comment by fsc8000** [comment]
I'll take a look.

**Comment by fsc8000** [comment]
Proposed fix: https://codereview.chromium.org/1988133003

**Comment by fsc8000** [comment]
Fixed via 6c778cab08e687bfdb1606a73f96c4689715555a.
