### ISSUE TITLE
LinkedHashMap uses isValidKey if no custom equal and hashCode provided

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26498]
According LinkedHashMap constructor documentation (https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedHashMap/LinkedHashMap.html)

> If using methods like operator[], remove and containsKey together with a custom equality and hashcode, an extra isValidKey function can be supplied. 

According the above if no custom `equal` and `hashCode` functions specified then isValidKey should be ignored. But it isn't so. Proof:

``` dart
import "dart:collection";

bool isValidKey(var potentialKey) {
  print('isValidKey called');
  return (potentialKey is int) && potentialKey < 100;
}

main() {
  LinkedHashMap<int, num> map = new LinkedHashMap<int, num>(isValidKey: isValidKey);

  map[1] = 1.1;
  print(map[1]);
  print(map.containsKey(1));
  print(map.remove(1));

  map[101] = 101.1;
  print(map[101]);
  print(map.containsKey(101));
  print(map.remove(101));

  print(map);
}
```

In the programm above `isValidKey` allows keys < 100 only. The output is the foloowing:

```
isValidKey called
1.1
isValidKey called
true
isValidKey called
1.1
isValidKey called
null
isValidKey called
false
isValidKey called
null
{101: 101.1}
```

As you can see isValidKey is called even  no custom `equal` and `hashCode` functions specified

**Comment by sgrekhov** [comment]
The similar issue for LinkedHashSet is #26499

**Comment by lrhn** [comment]
The text should be improved. The `isValidKey` parameter is never ignored. It's intended for cases where you have custom `equals` or `hashCode` functions, but if `isValidKey` is provided, it's treated as if you did specify the default `equals` and `hashCode` functions.
