### ISSUE TITLE
LinkedHashSet.from() documentation small issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26496]
Have to be a verbalist... Please see https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedHashSet/LinkedHashSet.from.html

> Creates a linked hash set as by new LinkedHashSet<E>() and adds each element ofelements to this set in the order they are iterated.

Please, add a space between _of_ and _elements_

**Comment by floitschG** [comment]
Thanks.
