### ISSUE TITLE
isValidKey is not ignored in LinkedHashSet constructor if equals or hashCode are omitted

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26499]
According LinkedHashSet constructor documentation (https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedHashSet/LinkedHashSet.html)

> If equals or hashCode are omitted, the set uses the elements' intrinsic Object.operator== and Object.hashCode, and isValidKey is ignored since these operations are assumed to work on all objects.

But it isn't ignored. Proof:

``` dart
import "dart:collection";

bool isValidKey(var potentialKey) {
  print('isValidKey called');
  return potentialKey < 100;
}

main() {
  LinkedHashSet<int> set = new LinkedHashSet<int>(isValidKey: isValidKey);

  set.add(1);
  print(set.contains(1));

  set.add(101);
  print(set.contains(101));

  print(set);
}
```

This programm produces the following output:

```
isValidKey called
true
isValidKey called
false
{1, 101}
```

`isValidKey` is called in spite of omitted `equals` and `hashCode`

**Comment by sgrekhov** [comment]
The similar issue for LinkedHashMap is #26498

**Comment by lrhn** [comment]
Same as for `LinkedHashMap` - the behavior is correct, the text should be updated.

**Comment by lrhn** [comment]
Documentation updated.
