### ISSUE TITLE
Compilation failure building VM on Debian

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26492]
There is a warning, treated as an error, when compiling on Debian.  The commit with this line is from CL "Initial isolate reload support", https://codereview.chromium.org/1965823002

Here is the error message:
runtime/vm/compiler.cc: In static member function 'static dart::RawObject* dart::Compiler::EvaluateStaticInitializer(const dart::Field&)':
runtime/vm/compiler.cc:1568:11: error: variable 'thread' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]

**Comment by johnmccutchan** [comment]
PTAL https://codereview.chromium.org/1998713002/
