### ISSUE TITLE
Fixed point numeric types

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26494]
## PROBLEM

Flutter needs a layout unit that has sub-pixel precision so that we can do accurate layout and painting operations on high-density displays. Layout and paint are our hottest code paths and there are numerous variables, arguments, and properties that would use this type.

Layout units are in a smallish range. In the common case, we would expect these numbers to be in the range -1e6 to +1e6, with an accuracy of ±0.02 or so.

Currently we use doubles.
## DESIRES

We would like a numeric type with the following all equally important properties:
- distinguished infinite values: it should be possible to represent +∞ and -∞. We use infinities extensively. _doubles succeed here, int fails._
- fractional: two values that are 1/64th apart should be distinguishable. _doubles succeed here within the range of expected values, though the exact precision varies which is suboptimal; int fails._
- associative: modulo rounding, it should not matter if we add then subtract, or subtract then add. `(a + b) - c` vs `a + (b - c)`. _doubles fail here, int succeeds._
- distributive: modulo rounding, it should not matter if we add then multiply, or multiply then add. `a * (b + c)` vs `(a * b) + (a * c)`. _doubles fail here, int succeeds._
- unboxed: since this is the hottest code path, we would like to use the fastest possible solution for computations, i.e. functions using this type should compile to functions doing computations on registers. _doubles and int succeed here<sup>1</sup>._
- tagged: since this is the hottest code path, we would like to use the fastest possible solution for storage too, i.e. objects of this type should store the value literally instead of using pointers. _doubles fail here, but int succeeds<sup>1</sup>._
- trivial literal: literals for this type should look exactly like doubles. _doubles and int succeed here._
- fast: this should use the fastest possible instructions on the underlying hardware.

We could also live with a literal that looked like a double but was then suffixed with a particular character, if that character was meaningful. For example, `0.1px` would be reasonable. It would be better if there was no suffix though.
## PROPOSAL

Create a new subtype of `num` that has the literal syntax of a double, but that is stored like a smi, except that the stored value is shifted left by six bits, and there is a special tag to represent infinities. Call this pixels. Then, when compiling, if you see a double literal, but the type that is expected is a pixels, convert it to this fixed-point form.
## MORE DETAILS

We could live with any precision that was a power of two (for performance) greater than 1/(2^6) (1/64th), so long as the efficient range easily covered the core range -1e6 .. +1e6.

Chrome has [a similar concept](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/platform/LayoutUnit.h) in their C++ code. Chrome originally tried 1/60, but changed to 1/64 for performance.

Graphics hardware typically solves this problem using floating point math far from zero. Such a solution might work here also, though it may be harder to reason about.

You can see where we currently work around the problems that double gives us by searching for "`_applyFloatingPointHack`" in our repo, for instance [in the text painter code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_painter.dart#L66) or [in the box painter code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_painter.dart#L16).

---

<sup>1</sup> based on https://www.dartlang.org/articles/numeric-computation/

**Comment by Hixie** [comment]
For the record, we (Flutter) don't think we need this any more, at least not for now.

**Comment by munificent** [comment]
Thanks for the update!
