### ISSUE TITLE
`Cannot invoke a non-function` warning for implementers of emulated function classes

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#26509]
Trying to invoke an instance of a class that implements an "emulated function" class results in a `Cannot invoke a non-function` analyzer warning.

This does not happen for classes that extend the same class.

``` dart
class EmulatedFunction implements Function {
  void call(arg1, arg2) {}
}

abstract class Implementer implements EmulatedFunction {}

abstract class Extender extends EmulatedFunction {}

main() {
  Implementer implementer;
  Extender extender;

  implementer.call(1, 2);
  implementer(1, 2); // warning: 'implementer' is not a method

  extender.call(1, 2);
  extender(1, 2);
}
```

In Dartpad: https://dartpad.dartlang.org/da83b664e157a6f0f35aa48ccc52e829

Is this expected behavior?

**Comment by bwilkerson** [comment]
I believe that your example should work.

**Comment by greglittlefield-wf** [comment]
The above Dartpad no longer exhibits this issue in Dart 2.5.2. Closing as fixed.
