### ISSUE TITLE
dart2js typed_data toList method loses type information.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26501]
``` dart:
import "dart:typed_data";
main() {
  print(new Uint8List(1) is List<int>);  // true
  print(new Uint8List(1) is List<String>);  // false
  print(new Uint8List(1).toList() is List<int>);  // true
  print(new Uint8List(1).toList() is List<String>);  // true ??
}
```

The `toList` call should return a `List<int>`. It gets its behavior from `UnmodifiableListBase<int>` (as far as I can see) which should return an actual `List<int>`. It seems the generic type parameter to the underlying `ListMixin` gets lost somewhere along the way.

A similar problem occurs with `"ab".codeUnits.toList()` (which also has a generic mixin as the source of its `toList` method).

**Comment by rakudrama** [comment]
This is the same as issue #20085

**Comment by sigmundch** [comment]
@rakudrama fixed this when adding getRuntimeTypeArgumentIntercepted
