### ISSUE TITLE
Running multi-tests with `DartOptions`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26506]
Multitests seem to preclude the use of `DartOptions`. When combined, test runs fail like this:

```
Test configuration: dart2js_d8_release_x64_checked
Unhandled exception:
'file:///usr/local/google/home/eernst/devel/dart/work/sdk/tools/testing/dart/test_suite.dart': Failed assertion: line 1550 pos 12: '!isMultitest || dartOptions == null' is not true.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

To reproduce: Add a new test `tests/language/multi_options_test.dart` which contains the following:

``` dart
// DartOptions=

library multi_option_test;

main() {
  int i = "42"; /// 1: static type warning, dynamic type error
}
```

Then run any one of these commands:

```
tools/test.py -mrelease --checked -cdart2js -rd8 language/multi_options
tools/test.py -mrelease -cdart2js -rd8 language/multi_options
tools/test.py -mrelease -cnone -rvm language/multi_options
```

Many other commands behave similarly, presumably because this has nothing to do with `-c`, `-r`, etc.

I first noticed this for a non-empty DartOptions (`// DartOptions=--generic-method-syntax`), so the assertion violation is not caused by its emptiness.

**Comment by whesse** [comment]
Yes, vm and dart options in comments inside the test are incompatible with multitests.  There are two separate systems of parsing a test to handle special comments in them, the multitest system and the options system, and so a test has to decide which system to use.
