### ISSUE TITLE
Please merge the revisions below into stable channel

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#26507]
@whesse @mit-mit @kasperl @iposva-google 

The changes fix a thread id recycling problem causing hangs on Windows reported here: https://github.com/dart-lang/sdk/issues/26400. Customers report that the changes resolve the issue.

Revisions:
1. 5f59a954f816ad0f46472eb4da05e714dbb7e117 : Fixes bug
2. 18ec8dddd913398215747e7de3ecfb7f35c62e1c : Adds back eventhandler thread joins that shouldn't have been removed.

This merged cleanly

**Comment by mit-mit** [comment]
We are scheduled to release a new stable next week (1.17), so at this time I don't think it makes sense to spin a new 1.16 stable build. I asked in 26400 and did not hear any objections there.

**Comment by whesse** [comment]
We already made the build, but we have compile failures I am working on (not due to the source).  So it will be released, once we get it all built.

**Comment by zanderso** [comment]
Please wait to close until the build is released.

**Comment by zanderso** [comment]
As mentioned in the bug above, a customer is experiencing daily hangs on a production server. I think it is inappropriate that it is taking 10+ days to get them a fix after it has landed. I believe that @whesse has all the bits ready. Can we please do this patch release, now?

**Comment by whesse** [comment]
OK, unless I hear otherwise i will release it tomorrow.

**Comment by zanderso** [comment]
It looks like this is done. Thanks!
