### ISSUE TITLE
Make identity() constructor documentation consistent for different collections

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26503]
HashSet.identity() constructor documentation (https://api.dartlang.org/stable/1.16.0/dart-collection/HashSet/HashSet.identity.html) reads:

> Effectively a shorthand for:
> `new HashSet<E>(equals: identical, hashCode: identityHashCodeOf)`

Please note type parameter E specified. For HashMap, LinkedHashMap and LinkedHashSet identity() constructors documentation has no type parameter. For example:

> Effectively a shorthand for:
> 
> `new LinkedHashSet(equals: identical, hashCode: identityHashCodeOf)`

Please make documentation consistent

**Comment by floitschG** [comment]
Thanks.
