### ISSUE TITLE
String unicode equivalence comparison?

### ISSUE THREAD

**Issue by Anrock** [dart-lang/sdk#26502]
```String::operator==``` is documented not checking for unicode equivalence. No way to normalize string either. 
So how to compare ```'Am\xe9lie'``` with ```'Ame\u{301}lie';``` and get ```true```?

**Comment by floitschG** [comment]
Dart's core library doesn't provide any means to normalize unicode. Full unicode treatment would explode the size of a Dart VM, and there was also the issue that we couldn't correctly translate it to JavaScript (without producing huge executables).

/cc @alan-knight Does the intl library support this in any way?

**Comment by alan-knight** [comment]
For the same reasons, the Intl package doesn't support normalization. JS
now has
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
so
you can  use that, but it isn't available according to that page in either
IE or Safari.

**Comment by floitschG** [comment]
Closing this issue. It's something we have an eye on, but there is no active plan on including unicode normalization to Dart.

**Comment by Chinmay-KB** [comment]
Has there been any work on this topic? I tried to find but either could not find or did not understand
