### ISSUE TITLE
Code Generation at Runtime / Compile-time

### ISSUE THREAD

**Issue by ScottPierce** [dart-lang/sdk#26513]
As far as I can tell, the dart vm cannot generate a class / code at runtime, nor can it generate code at compile time (similar to Java Annotation Processors). Adding such functionality would be very useful. 

Is this functionality on the dart roadmap at all?

**Comment by a14n** [comment]
You can take a look at the [source_gen package](https://pub.dartlang.org/packages/source_gen). I used it for [zengen](https://pub.dartlang.org/packages/zengen) and it works well.

/cc @kevmoo

**Comment by mraleph** [comment]
I am assuming that this issue is stale. This is not really a VM issue to begin with.
