### ISSUE TITLE
Precompilation debug failures

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26515]
Starting with f0a4c407099b6f8d0eaea815f0fccc8584abf7ee, I'm seeing failures running the precompilation test suite in debug mode.

runtime/vm/precompiler.cc:1689: error: Want to drop class Library:'dart:io' Class: ZLibCodec, but it has 1 instances

Presumably this is because we are now evaluating dead const initializers, which may reference dead const instances. Not sure where the incoming reference is from though, since the phases that remove dead fields and functions happen before phase that attempts to remove the dead class.

@fsc8000

**Comment by fsc8000** [comment]
I could reproduce this with --trace-precompiler on. 
@mraleph pointed out that handles created in Field::ToCString keeps class objects alive.

I added handle scopes to ensure that no handles created before DropClasses() keep stuff alive: https://codereview.chromium.org/2009513002/

**Comment by fsc8000** [comment]
Fixed via 3344a6f6f437757cfc2f5306ffde23e645c266e9.
