### ISSUE TITLE
strong mode least upper bound doesn't handle fuzzy arrows correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26512]
This broken code allows a function expecting a string to be called with an int with no check.  It looks like the least upper bound code is not accounting for the treatment of `dynamic` parameters as `bottom`.

```dart
typedef String TakesA<T>(T item);

void main() {
  TakesA<int> f;
  TakesA<dynamic> g;
  TakesA<String> h;
  g = h;
  f = f ?? g;
}
```

**Comment by jmesserly** [comment]
while fixing LUB, I noticed that GLB has the same issue

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2215873002
