### ISSUE TITLE
LinkedListEntry.next of the last element in the LinkedList contains link to the first element

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26522]
There are no any mentions in LinkedList documentation (https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedList-class.html) that the last element of the list shows the first element as its next and the first element links to the last element of the list as the previous one. Example:
```dart
class MyLinkedListEntry<E> extends LinkedListEntry {
  E value;
  MyLinkedListEntry(this.value);

  String toString() {
    return "($value)";
  }
}

main() {
  LinkedList list = new LinkedList();

  MyLinkedListEntry<int> entry1 = new MyLinkedListEntry<int>(1);
  list.add(entry1);
  print("entry1.next=" + entry1.next.toString());
  print(list);

  MyLinkedListEntry<int> entry2 = new MyLinkedListEntry<int>(2);
  list.add(entry2);
  print("entry1.next=" + entry1.next.toString());
  print("entry2.next=" + entry2.next.toString());
  print(list);

  MyLinkedListEntry<int> entry3 = new MyLinkedListEntry<int>(3);
  list.add(entry3);
  print("entry1.next=" + entry1.next.toString());
  print("entry2.next=" + entry2.next.toString());
  print("entry3.next=" + entry3.next.toString());
  print(list);
}
```
The output is:
```
entry1.next=null
((1))
entry1.next=(2)
entry2.next=(1)
((1), (2))
entry1.next=(2)
entry2.next=(3)
entry3.next=(1)
((1), (2), (3))
```
The same is true for the first element (`entry.previous` returns the last element)

1. I don't think that the first and last elements of the LinkedList should contain links to each other
2. If this is by design then documentation should contain this information
3. If this is by design shouldn't the `previous` and `next` properties of only element in the list return this element?

**Comment by floitschG** [comment]
I broke this, when I made the collection library strong-mode clean.
