### ISSUE TITLE
Expose full Reviver API in JsonDecoder?

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/sdk#26527]
Currently we can use the `new JsonCodec.withReviver` to listen for key-value pairs, but it would be nice if the whole ` _BuildJsonListener` class was exposed so we could get more contextual information (entering arrays or objects, etc.)

Here's my use case: I'm connecting to a json result from CouchDB. If  `_BuildJsonListener` were exposed and inheritable, I could process that information and feed it to my client in chunks rather than wait for the entire object to validate.

**Comment by lrhn** [comment]
One problem with this is that the JSON decoder is platform specific. The _BuildJsonListener only exists in the VM implementation, and not in dart2js. In the dart2js version, the internal JavaSCript `JSON.parse`  parser is used, and it doesn't support the features you are requesting.

It's not impossible to port the VM parser to dart2js, but it would be mostly unnecessary and will likely increase the footprint of the compiled JS code significantly.

**Comment by llamadonica** [comment]
I noticed that after I wrote this, and it looks like javascript's `JSON.parse` can't  pass data to its reviver callback. 

Thanks for the reply, anyway :smile:
