### ISSUE TITLE
Checked mode should allow this Function downcast.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#26528]
If a class implements `Function` by overriding `noSuchMethod`, checked mode should permit a downcast as it does when a class implements `Function` by directly implementing `call`.

``` dart
int test(int callback(int x)) {
  return callback(5);
}

class FunctionTypeTester1 implements Function {
  Function _toCall;
  FunctionTypeTester1(this._toCall);
  call(int x) => _toCall(x);
}

class FunctionTypeTester2 implements Function {
  Function _toCall;
  FunctionTypeTester2(this._toCall);
  @override
  dynamic noSuchMethod(Invocation invocation) =>
      (invocation.memberName == #call)
      ? Function.apply(_toCall, invocation.positionalArguments)
      : super.noSuchMethod(invocation);
}

int inc(int x) => x + 1;

void main() {
  var f1 = new FunctionTypeTester1(inc);
  int z1 = test(f1);
  print(z1);

  var f2 = new FunctionTypeTester2(inc);
  int z2 = test(f2);
  print(z2);
}
```

Rather, this program currently produces:

```
6
Unhandled exception:
type 'FunctionTypeTester2' is not a subtype of type '(int) => int' of 'callback' where
  FunctionTypeTester2 is from file:///usr/local/google/home/zra/mojo2/function_type_test.dart

#0      test (file:///usr/local/google/home/zra/mojo2/function_type_test.dart:4:14)
#1      main (file:///usr/local/google/home/zra/mojo2/function_type_test.dart:32:12)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

The rationale being that the spec allows `Function` to be implemented either way, so the particular way that is chosen should be opaque to checked-mode type-checking.

/cc @crelier @gbracha

**Comment by lrhn** [comment]
You can *implement* anything using a `noSuchMethod`, but it doesn't change the type of the object.
You can have an object implement all the methods of an interface using `noSuchMethod`, but unless you write `implements ThatInterface`, the class isn't assignable to the interface type. 

Function types work the same way. The specification does not assign a function type to an object if its class doesn't have a call method. If you have a particular function type that you want to implement, you currently have to make an interface class with a call method of that type, and then make your object implement that interface.

It would be nice if you could implement a function type directly, but the `implements` declaration requires a class type, not a function type.

So, the VM is correct with the current specification.

**Comment by zanderso** [comment]
It isn't clear to me why a class that implements `Function` with `call` and one the implements `Function` with `noSuchMethod` shouldn't be assignable to the same types. In my particular case, I am using `noSuchMethod` instead of `call` because I would like instances of the class to be assignable to *any* function type. It doesn't appear there is any other way to do this.

**Comment by lrhn** [comment]
In this case, your object does not implement the function type `int->int`. It may implement `Function`, but that doesn't make it assignable to a variable expecting an `int->int` function. The `Function` type is not a sub-type of `int->int`, it's the other way around.

Adding a `noSuchMethod` _never changes the type of the object_. It can't really, since you can't see which interfaces or function types it actually implements. All it does is to remove static warnings about not implementing all members of the interface and intercept invalid calls at runtime. 

In particular, you may *implement* a `call` method using `noSuchMethod`, but there is no way to see which function type it has, if any, from the presence of the `noSuchMethod` alone. If you want your object to satisfy a type test, you must declare it to have the required type somehow.

So when the `noSuchMethod` doesn't affect the validity of the assignment, we just have to see whether a class with `implements Function` is assignable to `int->int`, and it isn't. You need an actual `int->int` function type to do that. 

You can get that particular function type by either having an `int call(int x);` method or implementing an interface which has such method. In this case, you can simply add the `int call(int x);` abstract method to your `FunctionTypeTester2` class.

**Comment by zanderso** [comment]
Okay, that's all clear.

> `noSuchMethod` won't make you implement a function type (interface).

I guess my problem is that this is not useful for anything. I can implement `Function` using `noSuchMethod`, but I can't actually pass instances around anywhere. If I knew exactly what specific function type I wanted to implement in advance, I would just implement `call` and not `noSuchMethod`. I'm only using `noSuchMethod` because I don't know in advance the types of the functions I'm going to be wrapping. Rather, I'm trying to write a generic wrapper that works for any function, so I need to be able to pass it around as any function type.

It seems that the type-checker is already looking inside a class that implements `Function` to see what the type of the `call` method is. I don't think that's anywhere in the spec. It seems that, if it doesn't already allow it, the spec should be updated to allow a `Function` implemented with `noSuchMethod` to be assignable to any function type. Otherwise, we're in the strange situation where you can implement `Function` with `noSuchMethod`, but can't actually use it for anything.

**Comment by fsc8000** [comment]
Can't you do an explicit cast using 'as'?

**Comment by zanderso** [comment]
I have tried both `test(f2 as dynamic)` and `test(f2 as IntIntFunction)`, where `IntIntFunction` is `typedef int IntIntFunction(int x)` and both give the same error.

**Comment by fsc8000** [comment]
Never mind my question: as-cast will give the same error...

But I wonder as well why I can't do:

```
typedef int callback(int x);

class A implements callback {
}
```

**Comment by lrhn** [comment]
@fsc8000 
I agree, it would be convenient to be able to implement a function type as an interface.
It'd basically be a shorthand for introducing an anonymous class with a call method with that signature and then implement the class interface.

**Comment by zanderso** [comment]
A more specific interface would help in this case, but in the program I'm trying to write, I don't know the function types in advance [1], so declaring a more specific interface won't help.

[1] The functions come from the generated bindings code for Mojo. I have some control over what these functions look like, but since they are part of the public Dart API for Mojo they have to look nice and be fairly regular. For more background, I'm working on this issue: https://github.com/domokit/mojo/issues/777, and I'm trying to provide a nice migration path to the new API. I can go into more detail here if that would be useful.

**Comment by zanderso** [comment]
I have worked around this for the time-being by adding:

```dart
  dynamic call([
      dynamic a1, dynamic a2, dynamic a3, dynamic a4, dynamic a5,
      dynamic a6, dynamic a7, dynamic a8, dynamic a9, dynamic a10,
      dynamic a11, dynamic a12, dynamic a13, dynamic a14, dynamic a15,
      dynamic a16, dynamic a17, dynamic a18, dynamic a19, dynamic a20]);
```

to my class, but it would be nicer not to have to do this.

**Comment by lrhn** [comment]
What you want is a way to dynamically change the runtime type of the object, or at least have it be acceptable as any type. I can see a use for such a feature.

There is no way to infer a type from an implementation of `noSuchMethod`, so just implementing that won't be enough, you'll need something more, which the language doens't currently have.

**Comment by zanderso** [comment]
Reopening because my work-around is not a fix. Please stop closing this issue until it is addressed in a meaningful way.

**Comment by lrhn** [comment]
Fair enough.
This has been phrased as a bug report against either the VM or strong mode, and as such, there is no issue, everything is working as intended.

I'll mark it as a feature request against the language instead.

**Comment by zanderso** [comment]
> working as intended

I don't agree that this arrangement could have been the original intention of this feature, but I am okay with the current disposition of the issue.

**Comment by lrhn** [comment]
In Dart 2, the type shenanigans here are just not allowed, and you can no longer implement `Function`.
