### ISSUE TITLE
Can't access mixin properties within type assertion block, within IDE.

### ISSUE THREAD

**Issue by dustinlessard-wf** [dart-lang/sdk#26533]
As a consumer, I expect to use 

``` dart
(obj as Mixin).mixinName
```

in the same manner that I would use

``` dart
if(obj is Mixin) {
obj.mixinName;
}
```

Consider this:

``` dart
///
class Mixin{
  ///
  String mixinName = 'customMixin';
}

///
class ParentClass{
  ///
  String name = 'parentClass';
}

///
class ChildClass extends ParentClass with Mixin{
  ///
  String childName = 'childClass';
}

///
void testIfMixin(ParentClass obj) {
  if(obj is Mixin){
    print(obj.mixinName);
  }

  if(obj is Mixin){
    print((obj as Mixin).mixinName);
  }

  if(obj is ChildClass) {
    obj.childName;
  }
}

```

Result:
![screen shot 2016-05-25 at 10 52 51 am](https://cloud.githubusercontent.com/assets/2326518/15544493/e82d87ba-2266-11e6-9ee3-83c3a3c06021.png)

**Comment by kevmoo** [comment]
@dustinlessard-wf I'm guessing this is errors/warnings in the Editor – runtime is okay?

**Comment by dustinlessard-wf** [comment]
Correct @kevmoo , these are errors/warning in the IDE.  Runtime is ok : https://dartpad.dartlang.org/bfe4eb226f69cf49843f24e275a8f77e

**Comment by srawlins** [comment]
This is working as specified in the language; we do not promote to non-subtypes.
