### ISSUE TITLE
VM rejects valid dart program due to incorrect handling of rethrow

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#26530]
The following example works fine on dart2js but not on the DartVM:

```
$ cat test.dart
main() {
  var good = true;

  var x = 0;
  try {
    try {
      throw x++;
    } on int catch (e) {
      good = good && (e == 0);
      x++;
      try {
        x++;
        rethrow;
      } finally {
        x++;
      }
    }
  } catch (e) {
    good = good && (e == 0);
    x++;
  }

  if (!good) {
    throw 'Error';
  }
}
$ dart test.dart
'file:///.../test.dart': error: line 13 pos 9: rethrow of an exception is not valid here
        rethrow;
        ^
$ dartj2 test.dart --out=/tmp/x.js
$ third_party/d8/linux/d8 /tmp/x.js 
$ echo $?
0
```

According to the specification, a `rethrow` is valid **iff** it occurs inside a catch handler (which it does here) and it's semantic is to rethrow the same exception that the catch handler caught AFAIK.

/cc @mhausner @kmillikin

**Comment by kmillikin** [comment]
The parser is testing:

```c++
    // Check if it is ok to do a rethrow.
    if ((try_stack_ == NULL) || !try_stack_->inside_catch()) {
      ReportError(statement_pos, "rethrow of an exception is not valid here");
    }
```

But it should be testing if it is inside the catch block of any try, not just the nearest enclosing try.

**Comment by mhausner** [comment]
https://codereview.chromium.org/2075813003/ fixes this

Thank you for the repro case and finding the cause.
