### ISSUE TITLE
Build of ARM version of dart executable fails on our ARM hardware - libc mismatch.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26539]
Since updating our builder to trusty ubuntu, and installing the up-to-date arm cross-compiler, the arm dart executable requires glibc 2.16, which isn't present on our target.  The error message is: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by out/ReleaseXARM/dart)

We need to get the OS on our arm tester updated to one with glibc 2.16 to fix this.

**Comment by whesse** [comment]
Do we know what systems our users are using, and what libc versions they have? 
Note that this is a change in the builder that builds it, not a change in the source of the SDK.

@mkustermann @ricowind

**Comment by ricowind** [comment]
I think that chromium is using a pulled down glibc to build against, eliminating this problem (assuming that we could link against an older version). Maybe investigate if you can do that (it may be hard, both @sgjesse  and myself looked at doing this for fletch last year, but getting it working with our gyp files was problematic).
Here is the script that polls down the sysroot:
https://chromium.googlesource.com/chromium/chromium/+/trunk/build/linux/install-arm-sysroot.py

**Comment by ricowind** [comment]
Also, if you where to get this working, we could eliminate the need for wheezy chroot, since we could also just use an old sysroot for compiling that.

**Comment by mit-mit** [comment]
@whesse does this block releasing 1.17?

**Comment by whesse** [comment]
No, we can build and release in many ways, and it doesn't affect the source
tree.

**Comment by mit-mit** [comment]
Thanks, bumping milestone to 1.18

**Comment by mit-mit** [comment]
@whesse any news on this?

**Comment by whesse** [comment]
This is fixed - the cross-compiling builder is reverted to ubuntu precise, and the arm build remains as it was previously.
