### ISSUE TITLE
Compiler object now found in try dart unit tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26538]
The try-dart tests at try/poi/poi_test fail after the commit of https://codereview.chromium.org/2000323006

This commit makes a change to try/poi/poi.dart, but maybe a test is also needed to the test files.
The failures are shown on the bots dart2js-linux-jsshell-3-4-be and dart2js-linux-jsshell-4-4-be

**Comment by whesse** [comment]
Can we file a merge-to-dev request for this fix? We are now in cherry-pick season.

**Comment by hterkelsen** [comment]
Filed #26551
