### ISSUE TITLE
Type poluttion of ListIterator implementation regresses for-in performance

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#26546]
In the real-world applications `ListIterator` implementation is usually megamorphic (seen more than 4 classes), this leads to a drastic drop in performance because we don't do a good job removing that megamorphism even if we know the type of iterable at the inlining point. 

The test below demostrates the drop in performance of the for-in loop due to this type pollution:

```
$ xcodebuild/ReleaseX64/dart test.dart
Mono 10
Poly 28
Mega 120
```

``` dart
import 'dart:collection';

abstract class MyList extends Object with ListMixin implements List<int> {
  final list = [1,2,3,4,5,6];
  get length => list.length;
  operator[](int i) => list[i];
}

class A extends MyList { }
class B extends MyList { }
class C extends MyList { }

class H {
  final list = new List.generate(1000, (i) => i);
}

class H0 extends H {
  sum() {
    var s = 0;
    for (var i in list) s += i;
    return s;
  }
}

class H1 extends H {
  sum() {
    var s = 0;
    for (var i in list) s += i;
    return s;
  }
}

class H2 extends H {
  sum() {
    var s = 0;
    for (var i in list) s += i;
    return s;
  }
}

measure(name, f) {
  for (var i = 0; i < 10000; i++) f();
  final stopwatch = new Stopwatch()..start();
  for (var i = 0; i < 10000; i++) f();
  print("${name} ${stopwatch.elapsedMilliseconds}");
}

main() {
  measure("Mono", new H0().sum);

  for (var i in [1,2,3,4].map((x) => x));
  for (var i in new A());
  for (var i in new B());
  measure("Poly", new H1().sum);  // ListIterator implemenation is polymorphic.

  for (var i in new C());
  measure("Mega", new H2().sum);  // ListIterator implementation is megamorphic
}
```

**Comment by mraleph** [comment]
I am assigning to myself because we are going to explore approaches to rectify this inside the optimizing compiler, e.g. an additional round of type propagation and a round of inlining would remove the overhead.

However ideally we would like to have a feature that would allow to duplicate `ListIterator` implementation per iterable type.

**Comment by gustav3d** [comment]
Hows it going ?

**Comment by mraleph** [comment]
> Hows it going ?

In  what sense? 

FWIW ae8e6705c0e1dd624ec45843879294199c11e368 made the microbenchmark from the issue faster by changing underlying representation of the megamorphic call in IL so there is no longer any performance cliff associated with it.
