### ISSUE TITLE
Documentation of Queue.remove() doesn't specify which element is removed

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26541]
Please see https://api.dartlang.org/stable/1.16.0/dart-collection/Queue/remove.html

> Remove a single instance of value from the queue.

What if there are several instances of value in the queue? Documentation should either specify that "first element in iteration order is removed" either clearly say that this behaviour is implementation-specific

**Comment by bkonyi** [comment]
Looks like this removes the first instance found in the queue. I'll update the documentation.

**Comment by bkonyi** [comment]
As per @lrhn on the CL:

> I think I'd prefer to say that it's unspecified which element is removed if the value occurs more than once in the queue.

> The use-case for that is, say, a ReverseQueue wrapping a queue and swapping front and back.
It then doesn't have a way to remove the *last* instance of a value, so it cannot implement "remove".
(The only other asymmetric operation is addAll, and that can be simulated using a sequence of adds).

Closing.
