### ISSUE TITLE
spec for pushing sources to the VM over the service protocol

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26549]
This is a tracking issue to have a spec or some docs for pushing sources to the VM over the service protocol. Some notes from our conversation:

- this would likely use the binary portion of the websocket transport
- it will support pushing either 1 source at a time, or n sources (a batch mode for performance reasons)
- it will need to support both dart source files, and non-dart files (assets, and things like the .packages file)

@johnmccutchan @turnidge

**Comment by johnmccutchan** [comment]
An initial brain dump:

Layout on disk:

base path => /tmp/foobarXVDF/...
package root path => /tmp/foobarXVDF/packages/...

Life cycle:

Development environments are owned by a connected client. When the client
disconnects, the environment may be cleaned up automatically.

Spawning:

Embedder specific. Left out of this proposal.

Service Protocol Additions:

Creation:

-> "DevelopmentEnvironment.new"

<- "id": "/tmp/foobarXVDF",
   "basePath": "/tmp/foobarXVDF"
   "packageRootPath": "/tmp/foobarXVDF/packages"

Deletion:

-> "DevelopmentEnvironment.delete" +
    "id": "/tmp/foobarXVDF"

Sync:

-> "DevelopmentEnvironment.syncPackage"
  "id": "/tmp/foobarXVDF",
  "packageName": "example"
  "sources": ["package_root/relative/path/name", "data", "name", "data"]

<- "OK"

-> "DevelopmentEnvironment.syncFiles"
  "id": "/tmp/foobarXVDF",
  "sources": ["base_path/relative/path/name", "data"]

<- "OK"

List:

-> "DevelopmentEnvironment.listFiles"
  "id": "/tmp/foobarXVDF",

<- "files": ["/path/...", "/path/...b"]

**Comment by devoncarew** [comment]
Some questions:

- is it important to send back the `basePath` and the `packageRootPath` to the client on the create? I would think that just the `id` is enough.
- why the distinction between basePath and packageRootPath? Is the client not expected to send over a .packages file - will the VM only look for packages in a `packages/` directory?
- when syncing, do I need to send files for packages as a unit, and separate from other files? I guess I'm not clear on the different between `syncPackage` vs `syncFiles`
- what parts of the new protocol methods are going over the regular json-rpc String channel, and what parts over the binary portion of the channel? How is that binary portion encoded?

**Comment by johnmccutchan** [comment]
@devoncarew 

- Sending back basePath and packageRootPath is needed so that the client (Atom) can trivially rebase the uris onto the host machine's filesystem (think mapping stack trace / breakpoint uris back to files on host machine).

- We don't need to ship (or rewrite) a .packages file because we can make the embedder look for packages under a canonical packages/ directory.

- My current thinking is that packages are synced separately. This allows us to control precisely how packages are laid out in the development environment file system. The only difference between syncPackage and syncFiles is that syncPackage takes a package name along with a set of files.

- Not clear which parts will go over json-rpc as text v. binary. For Q2 prototype we might just base64 encode all data.

**Comment by johnmccutchan** [comment]
@turnidge and I discussed my straw man and have the following notes:

- Drop returning of basePath and packageRootPath from the create command.
- Make it possible to have a development environment persist across clients
- Add a read RPC (to be used by tests mostly)

**Comment by johnmccutchan** [comment]
@turnidge I wonder if drop the basePath and multiple development are running in the same VM -- how do we differentiate their stack trace messages?

**Comment by turnidge** [comment]
We are considering using a new uri scheme for managed source.  Something like:

```
dart-fs://environment-name/path/file.dart
```

**Comment by devoncarew** [comment]
Cool. The important thing from my perspective is that the client is able to map a local source location to a VM uri, and map back from a VM uri to a local source location.

**Comment by johnmccutchan** [comment]
Note that Todd landed https://github.com/dart-lang/sdk/commit/f7242f21373f994be697c4052afed6c1b0d24a82 which changes the way devfs works. It now returns a base url that is a file:/// (on the device). All files written will relative to the base url that was returned when the devfs was created.
