### ISSUE TITLE
analysis server doesn't always recognize when `pub get` has been performed

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26548]
From https://github.com/flutter/flutter/issues/4031, we've seen cases where the analysis server doesn't recognize that the `.packages` file has changed on disk. A reanalyze sources will fix the issue. Perhaps related to file watching code?

**Comment by bwilkerson** [comment]
Possibly. The two most likely scenarios are that (a) server is not being notified that the file has changed or (b) for some reason it's deciding that nothing has changed so nothing needs to be done. I don't remember, though, having any code to try to optimize the case where a `.packages` file contains the same map as before, so (a) seems more likely.

**Comment by bwilkerson** [comment]
Do we have a way to reproduce this behavior?

**Comment by devoncarew** [comment]
From reading the original bug, it looks like it happened right after project creation, at a kiosk at a trade show; @sethladd might have more details.

**Comment by zoechi** [comment]
Does `pub run` update the `.packages` file or should this be `pub get` or `pub upgrade`?

**Comment by devoncarew** [comment]
`pub get`; good catch :)

**Comment by devoncarew** [comment]
closing as assumed stale
