### ISSUE TITLE
In AOT + Observatory mode the app crashes when accessing Isolate info

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#26550]
The running in AOT + Observatory mode the app crashes when isolate info is requested using the VM service protocol. This can be reproduced both via the JSON RPC API and using the Observatory UI (open Observatory home page and click on the isolate link; observe the crash).

@rmacnak-google has more info about the bug.

/cc @rmacnak-google @johnmccutchan

**Comment by rmacnak-google** [comment]
e3f5760f6647bdb54d11819c5087087a823a4f8a
