### ISSUE TITLE
VM Isolate.spawn changes content of Platform.packageRoot/Config

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26555]
When you do `Isolate.spawn` you should get an isolate that is as close as possible to the one doing the spawning. 
If the initial isolate has not received any explicit package resolution information (--package-config or --package-root command-line parameter), the `Platform.packageRoot` and `Platform.packageConfig` values are empty. This triggers "automatic configuration" where the VM searches for (or assumes) a .packages file or packages/ directory in various places.

If that happens and you then do an `Isolate.spawn` call, the new Isolate will have `Platform.packageRoot` or `Platform.packageConfig` set to the result of the implicit search. They should still be null since they represent the command line/`spawnUri` parameters and the user hasn't specified any originally or when calling `Isolate.spawn`.

**Comment by mit-mit** [comment]
@a-siva, who can look at this? We need to get this work completed in 1.18.

**Comment by a-siva** [comment]
@lrhn could you point me to the test case you used for this bug.

**Comment by lrhn** [comment]
I'm using the test `standalone/packages_file_test`.
It currently contains some extra added code marked as "TEMPORARY FIX FOR ISSUE #26555". If that code is removed, the bug is hit and detected.

**Comment by a-siva** [comment]
This appears to work as expected,  I wrote a simple test as follows:

import 'dart:isolate';
import 'dart:io';
child(args) {
  var msg = args[0];
  var packageRoot = Platform.packageRoot;
  print("Child isolate : Platform.packageRoot = $packageRoot");
  var packageConfig = Platform.packageConfig;
  print("Child isolate : Platform.packageConfig = $packageConfig");
  var reply = args[1];
  reply.send('re: $msg');
}
void main([args, port]) {
  var packageRoot = Platform.packageRoot;
  print("Main isolate : Platform.packageRoot = $packageRoot");
  var packageConfig = Platform.packageConfig;
  print("Main isolate : Platform.packageConfig = $packageConfig");
  ReceivePort port = new ReceivePort();
  Isolate.spawn(child, ['hi', port.sendPort]);
  port.listen((msg) {
    port.close();
    print(msg);
  });
}

and this produces the correct output:
Main isolate : Platform.packageRoot = null
Main isolate : Platform.packageConfig = null
Child isolate : Platform.packageRoot = null
Child isolate : Platform.packageConfig = null
re: hi

Another test that uses spawnUri

import 'dart:isolate';
import 'dart:io';
main() {
  var packageRoot = Platform.packageRoot;
  print("Main isolate : Platform.packageRoot = $packageRoot");
  var packageConfig = Platform.packageConfig;
  print("Main isolate : Platform.packageConfig = $packageConfig");
  ReceivePort port = new ReceivePort();
  port.listen((msg) {
      port.close();
  });
  Isolate.spawnUri(Uri.parse('/tmp/spawn_child.dart'),
                   ['hi'], port.sendPort);
}

contents of '/tmp/spawn_child.dart'

import 'dart:isolate';
import 'dart:io';
void main(List<String> args, SendPort replyTo) {
  var packageRoot = Platform.packageRoot;
  print("Child isolate : Platform.packageRoot = $packageRoot");
  var packageConfig = Platform.packageConfig;
  print("Chile isolate : Platform.packageConfig = $packageConfig");
  var data = args[0];
  replyTo.send('re: $data');
}

and this produces the corret output:
Main isolate : Platform.packageRoot = null
Main isolate : Platform.packageConfig = null
Child isolate : Platform.packageRoot = null
Chile isolate : Platform.packageConfig = null


Please provide a test case that demonstrates the problem.

**Comment by a-siva** [comment]
Ok I see the problem now, if I import a package in the main isolate then it retains the value, e.g:

add the line
import 'package:foo/foo.dart';
to isolate.dart and then I trigger the problem.

Now I have a simple unit test to work on instead of the one in packages_file_test ......

**Comment by lrhn** [comment]
Good. I guess this is one of the remaining cases where it matters whether you have a package: import or not (which it never should).

**Comment by a-siva** [comment]
Submitted https://github.com/dart-lang/sdk/commit/da1a5534b4578511c58b6b367caca6abab5854de to fix this

**Comment by kevmoo** [comment]
Closed via https://github.com/dart-lang/sdk/commit/da1a5534b4578511c58b6b367caca6abab5854de ?

**Comment by dgrove** [comment]
@a-siva should this be closed?
