### ISSUE TITLE
Coluld you please delete a package for me

### ISSUE THREAD

**Issue by luisvt** [dart-lang/sdk#26567]
the package is this one: https://pub.dartlang.org/packages/resource_demo

I uploaded by mistake, is just a demo, and shouldn't be publish

**Comment by zoechi** [comment]
You know of http://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package ?

**Comment by mit-mit** [comment]
Hi @luisvt, please follow the instructions under 'How do I delete a package?' here:
https://www.dartlang.org/tools/pub/faq.html

**Comment by fsc8000** [comment]
Reopening... From the faq: "If, however, you really want your package deleted, file an issue and the Pub authors will take down your package."

**Comment by whesse** [comment]
Yes, I will delete your package.

**Comment by mit-mit** [comment]
Sorry, my bad, I misread what repo this was filed in for another one. Yes,
Bill please go ahead.

**Comment by mit-mit** [comment]
@whesse did you have a chance to look at this?

**Comment by whesse** [comment]
Package is deleted.

**Comment by luisvt** [comment]
thanks
