### ISSUE TITLE
No doc generated. (Linux) (Topic moved)

### ISSUE THREAD

**Issue by Songbird0** [dart-lang/sdk#26566]
(I've moved my topic here, sorry for double post)
Hi !

While some hours, I'm trying to generate my project doc, but it don't work... (0 parsed files)
My pubspec.yaml:
name: random
dependencies:
  js: ^0.3.0
  intl: ^0.12.4
environment:
  sdk: ">=1.16.0"

Do you know where is my error ? Or it's a bug ?

Thanks for advance !

Songbird.
![screenshot - 27052016 - 10 12 06](https://cloud.githubusercontent.com/assets/13397428/15602093/7ff8ea16-23f3-11e6-9e76-c211698ab9dd.png)

**Comment by mit-mit** [comment]
Hi @Songbird0, can you include additional details on what command you are running to generate docs, and what your file layout looks like?

**Comment by Songbird0** [comment]
> can you include additional details on what command you are running to generate docs

Sure.


My project skeleton:

```
├── myapp.dart
├── packages
├── pubspec.lock
└── pubspec.yaml

```

In myapp.dart file:

```
/// This is a dartdoc comment !
/// and another
class MyApp
{
	MyApp()
	{
		
	}
}
```

Next, I type the command **dartdoc** in my root directory (named 'random').
Result:

> ~/Documents/random$ dartdoc
> Generating documentation for 'random' into /home/songbird/Documents/random/doc/api/
> 
> Parsed 0 files in 1.7 seconds.
> 
> documenting random
> Documented 0 libraries in 2.0 seconds.
> 
> Success! Docs generated into /home/songbird/Documents/random/doc/api


My dart file hasn't been parsed, dartdoc not completed.

So, what I see when my browser display the index.html file:

![screenshot - 30052016 - 23 39 55](https://cloud.githubusercontent.com/assets/13397428/15658696/df2d8b58-26bf-11e6-9cfe-b5f2bd24f807.png)

Thanks for your help,

Songbird.

**Comment by mit-mit** [comment]
I believe dartdoc assumes that the library files are in a lib directory, @pq can you confirm?

Try to create your project using [stagehand](https://github.com/google/stagehand) and use the default file structure it gives you (using `stagehand package-simple`) -- that should work.

**Comment by pq** [comment]
Yes.  I think that's right.  Looking at the docs, this doesn't seem well expressed though.  Might benefit from emphasis?

cc @keertip.

**Comment by Songbird0** [comment]
It work ! :D 
Thanks for your help, my documentation has been completed.

**Comment by pq** [comment]
Great to hear.  We'll look at clarifying our tool docs.

Cheers!
