### ISSUE TITLE
dartdevc -h broken

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26560]
When running `dartdevc -h` or `dartdevc --help`, I see:

```
Could not find an option named "dart-sdk".
```

**Comment by devoncarew** [comment]
This is the dartdevc binary from `1.17.0-dev.6.0 (Thu May 26 12:22:23 2016) on "macos_x64"`.

**Comment by nex3** [comment]
Duplicate of #26479?

**Comment by devoncarew** [comment]
Yup - closing.
