### ISSUE TITLE
Figure out a way to test precompiled code on iOS devices using test.py

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26571]
@mraleph @rmacnak-google @mkustermann 

The main issue is to figure out how to automate the xcode build process that is used for precompiled code.

**Comment by rmacnak-google** [comment]
Is there a way to build standalone for iOS?

**Comment by fsc8000** [comment]
No, and there are other missing pieces, e.g. there seem to be no adb-equivalent for iOS.

**Comment by rmacnak-google** [comment]
Flutter uses `ios-deploy` and `iproxy`.
