### ISSUE TITLE
VM failure on co19 precedence tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26573]
The two co19 tests 

co19/Language/Reference/Operator_Precedence/precedence_12_Shift_t02
co19/Language/Reference/Operator_Precedence/precedence_15_unary_prefix_t04

Are failing on all VM runs after the co19 roll, which landed 6 months of changes and additional tests.  Please see if the test or the vm is wrong.

**Comment by lrhn** [comment]
On Tue, May 31, 2016 at 1:51 AM, William Hesse <notifications@github.com>
wrote:

> The two co19 tests
>
> co19/Language/Reference/Operator_Precedence/precedence_12_Shift_t02
>

Test is wrong.

It contains the line:
  Expect.notEquals(2 & (8 >> (2 & 3)), 2 & 8 >> 2 & 3);
which attempts to check that the associtativity is correct, but happens to
compute the same result in a different way (8 >> (2 & 3) == 8 >> 2 == 2 ==
2 & 3 == (8 >> 2) & 3)


> co19/Language/Reference/Operator_Precedence/precedence_15_unary_prefix_t04
>
Test is wrong. Contains the line:

  Expect.equals(c * (++e), c * ++e);

which should (apparently) check that the two expressions are equivalent ("c
* x" returns x), but forgets that ++e has a side effect and 2 != 3.

(Also, (c * ++) isn't valid syntax, so I'm not sure what is really being
checked).


> Are failing on all VM runs after the co19 roll, which landed 6 months of
> changes and additional tests. Please see if the test or the vm is wrong.
>
They also fail the same way on dart2js.

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by whesse** [comment]
Please file this info in a co19 issue

**Comment by hterkelsen** [comment]
Filed https://github.com/dart-lang/co19/issues/58 and https://github.com/dart-lang/co19/issues/59

**Comment by mhausner** [comment]
Seems there is no VM bug here. co19 bugs are filed.
