### ISSUE TITLE
async co19 test fails in release or checked mode on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26574]
co19/Language/Expressions/Function_Invocation/async_invokation_t04

fails with a runtime error, only on Windows, but only in release or checked modes, not in debug unchecked.

**Comment by lrhn** [comment]
Test is flawed. It assumes that `new DateTime.now()` has advanced between two async microtasks. The granularity of Windows timers probably prevents that from being visible. 
I guess debug mode is slow enough that it works anyway.

**Comment by whesse** [comment]
Please file an issue on Dart-lang/co19 and either update the status file with it, or refer to it from this one, to avoid committing.
