### ISSUE TITLE
registerElement

### ISSUE THREAD

**Issue by sorenbronsted** [dart-lang/sdk#26570]
document.registerElement fails when extending InputElement

```
import 'dart:html';

class BarElement extends InputElement {
  BarElement.created() : super.created() {
    print('BarElement created!');
  }
}

main() {
  document.registerElement('x-bar', BarElement);
  var myBar = new Element.tag('input', 'x-bar');
}

```
Gives the flowing exception:

`Exception: HierarchyRequestError: Custom element BarElement is a native InputElement should be derived from HtmlElement or SvgElement.`

The documentation says. "The class being registered must either subclass HtmlElement or SvgElement."

It works if I extend HtmlElement instead.

**Comment by zoechi** [comment]
If you extend a DOM element you need to add `extendsTag: 'input'`

https://dartpad.dartlang.org/4f0bafcab443d66a188157c38c9eb033

See also http://stackoverflow.com/questions/26314402/extendtag-in-dart-custom-element

**Comment by sorenbronsted** [comment]
Ok thanks.  I have tried that in version 1.16, and that is where I get the
error. What version is Dartpad running on?


2016-05-29 21:22 GMT+02:00 Günter Zöchbauer <notifications@github.com>:

> If you extend a DOM element you need to add extendsTag: 'input'
>
> https://dartpad.dartlang.org/4f0bafcab443d66a188157c38c9eb033
>
> See also
> http://stackoverflow.com/questions/26314402/extendtag-in-dart-custom-element
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26570#issuecomment-222377792>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACWVFZrfUbEPKuB3BxglwxW5UKtetXlFks5qGedxgaJpZM4IpVpm>
> .
>



-- 
Søren Brønsted
Løvstikkevej 44
2300 København S
+45 31 49 32 22
www.bronsted.dk

**Comment by zoechi** [comment]
I don't know what version Dartpad is running. What error do you get when you add `extendsTag: 'input'`?

**Comment by sorenbronsted** [comment]
That is the one I wrote about, which is different that mentioned on
stackoverflow.

2016-05-30 8:45 GMT+02:00 Günter Zöchbauer <notifications@github.com>:

> I don't know what version Dartpad is running. What error do you get when
> you add extendsTag: 'input'?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26570#issuecomment-222422689>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACWVFdWSVMjhNTRPgoA5KrUFtpS4gg32ks5qGodugaJpZM4IpVpm>
> .
>



-- 
Søren Brønsted
Løvstikkevej 44
2300 København S
+45 31 49 32 22
www.bronsted.dk

**Comment by zoechi** [comment]
But your code above doesn't include `extendsTag: 'input'`

**Comment by sorenbronsted** [comment]
Sorry, you are correct, and when I use it with the extendsTag it works in
version1.16. Sorry for the trouble.

2016-05-30 9:38 GMT+02:00 Günter Zöchbauer <notifications@github.com>:

> But your code above doesn't include extendsTag: 'input'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26570#issuecomment-222431196>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACWVFa43uf9BxDs3Xmq97u3sf7ZA17TMks5qGpPvgaJpZM4IpVpm>
> .
>



-- 
Søren Brønsted
Løvstikkevej 44
2300 København S
+45 31 49 32 22
www.bronsted.dk

**Comment by zoechi** [comment]
No prob. Would you mind closing this issue, there seems to be nothing left for the Dart team to do.
