### ISSUE TITLE
DoubleLinkedQueue.removeWhere and retainWhere may modify the queue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26587]
According https://api.dartlang.org/stable/1.16.0/dart-collection/DoubleLinkedQueue/removeWhere.html

> The test function must not throw or modify the queue.

The same is true for retainWhere. It doesn't work for DoubleLinkedQueue

``` dart
import "dart:collection";

main() {
  DoubleLinkedQueue queue = new DoubleLinkedQueue();
  queue.addAll([-3, -2, -1, 0, 1, 2, 3, -1]);

  bool throwFunction(var element) {
    if (element < 0) {
      return true;
    } else {
      queue.remove(element);
      return false;
    }
  }

  queue.removeWhere(throwFunction);
  print(queue); // prints {}
}
```

This programm produces no any error. The same is true for retainWhere. There are no this issue for LinkedQueue. It produces  

```
Unhandled exception:
Concurrent modification during iteration: Instance of 'ListQueue'.
```

DoubleLinkedQueue also should throw an error in this case

**Comment by lrhn** [comment]
Throwing a concurrent modification error is always "best effort" - the requirement is that you *must not* do something, but not necessarily that doing it will get caught. 

We should check whether the DoubleLinkedQueue implementation ends up doing something *wrong* if you modify the queue during iteration, or if it's actually perfectly safe (which is unlikely, but not impossible).

**Comment by lrhn** [comment]
Actually, the implementation is safe. It detects a concurrent modification if you remove the *current* entry from the queue during iteration, and throws. Otherwise it continues following the links, which is a reasonable behavior.
