### ISSUE TITLE
Please merge revision #586bcb7d9e5c46c84a3c9d1f43f26343da78548a  into 1.17 stable

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#26591]
@whesse @mit-mit @kasperl
Please merge for WebKit (dart/dartium/blink/releases/2454_1)  this commit 586bcb7d9e5c46c84a3c9d1f43f26343da78548a [CL](https://codereview.chromium.org/2023313002)

You should also cherry-pick the DEPS file change in dart commit # 5a9b6003605bdf864ae9f4c9c4b709efcda9fe0b [CL](https://codereview.chromium.org/2032563002/) to point to the above WebKit change.

This fixes Dartium crashing if debugging Dart code in an iFrame 

This merged cleanly

**Comment by mit-mit** [comment]
Landed in https://github.com/dart-lang/sdk/commit/25b5232470d2036c593c4ee34a7e0e29f9cdd12d

**Comment by mit-mit** [comment]
Closing, @kevmoo confirmed in #26117 that this works in 1.17.0-dev.6.1
