### ISSUE TITLE
After clone on linux and run index.html from chrome or browser DnD not working

### ISSUE THREAD

**Issue by satinder007** [dart-lang/sdk#26599]
Hi , I am like that functionality but after cloning in linux and then running index.html from browser drag and drop not working . pointer is showing means element dragging but not dropping . Please help for that .

**Comment by satinder007** [comment]
Yes you can clone it from git hub :

git clone https://github.com/dart-lang/dart-samples

then go into :
dart-samples/html5/web/dnd/basics

there have index.html and I run it simply from chrome but dropping not
working .

**Comment by alan-knight** [comment]
The problem is that the sample attempts to just set the innerHtml to the result, it's enclosed in a meta tag, and the sanitizer disallows it.  https://github.com/dart-lang/dart-samples/issues/101
