### ISSUE TITLE
Suggest private names even when partial name is public

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#26598]
If the user typed `getF` I think it would be helpful to show completions for both `getF` and `_getF`, since the user might not remember if the desired method is private.  It might also help with the ergonomics of typing private names.

(Of course, only suggest members that are visible in the current library.)

**Comment by bwilkerson** [comment]
@jwren @danrubel

**Comment by jwren** [comment]
Please provide more information, I was unable to get this to be reproduced.  See screenshot.
![screenshot from 2016-06-08 11 15 32](https://cloud.githubusercontent.com/assets/1533520/15905707/b5f2c792-2d6a-11e6-8429-970e420a1369.png)

**Comment by asgerf** [comment]
Thanks for investigating.  It appears the issue is specific to the Atom plugin.

I have reopened the issue in Atom plugin repo (https://github.com/dart-atom/dartlang/issues/1029).

**Comment by jwren** [comment]
@devoncarew for the context for dart-atom/dartlang#1029

**Comment by sgjesse** [comment]
Opened again. Wrong issue number in https://github.com/dart-lang/sdk/commit/f9404b969ba0b244fbff6dc8aa0388c57f3ad577.

**Comment by natebosch** [comment]
I don't think there is anything to do in the analysis server. Tracking at https://github.com/dart-atom/dart/issues/1029
