### ISSUE TITLE
In batch mode, analyzer_cli produces nondeterministic output for parts used in multiple libraries

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26592]
Consider a part file such as `tests/co19/src/Language/Libraries_and_Scripts/Parts/part_0.dart`, which is included as a part of at least two libraries (`compilation_t01.dart` and `compilation_t04.dart`, in the same directory).  When included as part of `compilation_t01.dart`, the part file has errors, due to a duplicate definition of the top-level variable `foo`.  When included as part of `compilation_t04.dart`, the part file has no errors.

If analyzer_cli is operated in batch mode, and is asked to first analyze `compilation_t01.dart`, and then `compilation_t04.dart`, it reports that `part_0.dart` has errors in both cases.  The reason this happens is that a single context is re-used for both analyses (to save time).  Since analyzer_cli doesn't have any understanding of part relationships, it simply asks the context to report the errors in the part file in both cases.  When it's asked for the second time, the context has seen two libraries that include the part, so it reports the union of the errors from the two libraries.

This is causing flaky errors in the analyzer buildbot, since the bot uses multiple concurrent analyzer_cli processes to speed up analysis, and the presence or absence of errors when analyzing `compilation_t04.dart` depends on what files have previously been analyzed by the same analyzer_cli process.

**Comment by bwilkerson** [comment]
One possible solution is to remove the files being analyzed after analysis is complete when running in batch mode. We don't bother under normal circumstances because it doesn't cause any problems, but it is clearly causing problems here.

**Comment by srawlins** [comment]
Just a note that `analyzer_cli` (and `dartanalyzer`) are no longer external tools, but are still used for those `co19` tools.

**Comment by keertip** [comment]
closing as stale.
