### ISSUE TITLE
Instance member redefinition and super access

### ISSUE THREAD

**Issue by branoh** [dart-lang/sdk#26590]
## Problem description

I've noticed a strange behaviour when an instance member is redefined in a subclass and accessed through `super.member`.

`Dart Programming Language Specification`, page 39, point 7 says about instance member definition with the same name in class and its superclass this:
```
7. If you define an instance member named m, and your superclass has an
instance member of the same name, they override each other. This may or
may not be legal.
```

However, if the instance member is defined in both superclass and its class, it is possible to change value of superclass' instance member and still keeping the original value of the other member which is supposed to be the same(as far as I know).
What is strange that the value set by `super.myMember = 'some value';` is actually accessible only from the subclass.

## Example code

```
class ClassA {
  String someField;
  
  ClassA() {
    this.someField = "value A";
    print("Class A constructor: this: '${this.someField}' , default: '${someField}'");
  }
  
  printField() {
    print("print class A this: '${this.someField}' , default: '${someField}'");
    someField = "value A";
    print("print class A this: '${this.someField}' , default: '${someField}'");
  }
}

class ClassB extends ClassA {
  String someField;
  
  ClassB() {
    print("B constructor: super: '${super.someField}' , this: '${this.someField}' , default: '${someField}'");
    someField = "value B";
    print("B constructor changed value. super: '${super.someField}' , this: '${this.someField}' , default: '${someField}'");
  }
  
  printField() {
    super.printField();
    print("print class B super: '${super.someField}' , this: '${this.someField}' , default: '${someField}'");
    super.someField = "value B";
    print("print class B super: '${super.someField}' , this: '${this.someField}' , default: '${someField}'");
    super.printField();
  }
}

main() {
  ClassB classB = new ClassB();
  classB.printField();
}
```

### Output

```
Class A constructor: this: 'value A' , default: 'value A'
B constructor: super: 'null' , this: 'value A' , default: 'value A'
B constructor changed value. super: 'null' , this: 'value B' , default: 'value B'
print class A this: 'value B' , default: 'value B'
print class A this: 'value A' , default: 'value A'
print class B super: 'null' , this: 'value A' , default: 'value A'
print class B super: 'value B' , this: 'value A' , default: 'value A'
print class A this: 'value A' , default: 'value A'
print class A this: 'value A' , default: 'value A'
```

If the statement that instance members with the same name override each other, IMHO, there should always be the same value in the output, no matter whether accessed through `super.member`, `this.member` or just `member`.

**Comment by lrhn** [comment]
The behavior you are seeing is correct and intended. An object has one "slot" for each field declared in its class and any of its super-classes, even if they happen to have the same names. The slot introduces a hard-wired getter and setter that accesses that particular slot. Those getters and setters may get overriden in sub-classes, but the field's slot is never affected.

So your initial example, you have one field (a slot) in the superclass and one field (another slot) in the subclass. Instances of the subclass will have two slots with only one accessible getter and setter. The slots can be used to store two different values (and it is probably wasting space if you only use one of them). The subclass getter and setter override the superclass getter and setter, and as usual, the subclass is the only one who can access the overridden superclass members (that's a very important property for several reasons).

So, as a general rule: Don't override fields with fields, it's most likely not what you want to do.

**Comment by branoh** [comment]
Thank you for the explanation!

I do agree with the general rule and I wouldn't do it in a "real life". I just got curious whether it is really intended or not while working on my master's thesis and figuring out what one can or cannot do with the overridden members.

**Comment by zoechi** [comment]
There is also this linter rule http://dart-lang.github.io/linter/lints/overriden_field.html

In strong mode overriding a field is an error.

**Comment by branoh** [comment]
That's great! I was thinking that at least some warning about field overriding would be nice. As it is present in a strong mode, it's fine. I didn't check the strong mode behaviour before writing this post. Thank you!
