### ISSUE TITLE
There is overhead in sending large data to isolates

### ISSUE THREAD

**Issue by Paullo612** [dart-lang/sdk#26595]
When message received by isolate, it content is explicitly converted to string. It takes a long time to do so for large binary data when compiled with dart2js. Seems like this string is used for debugging purposes only.

https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/isolate_helper.dart#L1209

**Comment by floitschG** [comment]
Thanks.
Looks like this (very old) code was just for debugging.
