### ISSUE TITLE
Precompilation debug failures

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26607]
```
FAILED: precompiler-dart_precompiled debug_x64 co19/LibTest/core/int/toDouble_A01_t01
Expected: Pass 
Actual: Crash
Unexpected compile-time error.
CommandOutput[precompiler]:

stderr:
runtime/vm/precompiler.cc:2714: error: expected: use_speculative_inlining


Command[precompiler]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart_bootstrap --snapshot=/usr/local/google/home/rmacnak/dart4/sdk/out/DebugX64/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01 --snapshot-kind=app-aot --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /usr/local/google/home/rmacnak/dart4/sdk/tests/co19/src/LibTest/core/int/toDouble_A01_t01.dart
Took 0:00:12.211972

Command[assemble]: DART_CONFIGURATION=DebugX64 gcc -shared -m64 -o /usr/local/google/home/rmacnak/dart4/sdk/out/DebugX64/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01/libprecompiled.so /usr/local/google/home/rmacnak/dart4/sdk/out/DebugX64/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01/snapshot.S
Did not run

Command[remove_assembly]: DART_CONFIGURATION=DebugX64 rm /usr/local/google/home/rmacnak/dart4/sdk/out/DebugX64/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01/snapshot.S
Did not run

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --run-app-snapshot=/usr/local/google/home/rmacnak/dart4/sdk/out/DebugX64/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01 --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /usr/local/google/home/rmacnak/dart4/sdk/tests/co19/src/LibTest/core/int/toDouble_A01_t01.dart
Did not run

Short reproduction command (experimental):
    python tools/test.py --exclude-suite pkg -cprecompiler -rdart_precompiled -t960 co19/LibTest/core/int/toDouble_A01_t01
```

@fsc8000 @mraleph

**Comment by whesse** [comment]
This test is also failing on ARM precompilation, crashing on one bot and timing out on another:

FAILED: precompiler-dart_precompiled release_simarm co19/LibTest/core/int/toDouble_A01_t01
Expected: Pass 
Actual: Crash
Unexpected compile-time error.
CommandOutput[precompiler]:

stderr:
dart_bootstrap(36188,0xa43e4000) malloc: *** mach_vm_map(size=8388608) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc


Command[precompiler]: DART_CONFIGURATION=ReleaseSIMARM xcodebuild/ReleaseSIMARM/dart_bootstrap --snapshot=/b/build/slave/vm-noopt-simarm-mac-1-2-be/build/sdk/xcodebuild/ReleaseSIMARM/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01 --snapshot-kind=app-aot --ignore-unrecognized-flags --package-root=xcodebuild/ReleaseSIMARM/packages/ /b/build/slave/vm-noopt-simarm-mac-1-2-be/build/sdk/tests/co19/src/LibTest/core/int/toDouble_A01_t01.dart
Took 0:00:30.086075

Command[assemble]: DART_CONFIGURATION=ReleaseSIMARM clang -dynamiclib -m32 -o /b/build/slave/vm-noopt-simarm-mac-1-2-be/build/sdk/xcodebuild/ReleaseSIMARM/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01/libprecompiled.dylib /b/build/slave/vm-noopt-simarm-mac-1-2-be/build/sdk/xcodebuild/ReleaseSIMARM/generated_compilations/precompiler/tests_co19_src_LibTest_core_int_toDouble_A01_t01/snapshot.S
Did not run

**Comment by whesse** [comment]
Marked in status file tests/co19/co19-runtime.status.

It looks like the test started failing with commit of
https://codereview.chromium.org/2033553002
