### ISSUE TITLE
Moving engine into runtime

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26605]
Plan to move [engine](https://github.com/flutter/engine) into [runtime](https://github.com/dart-lang/sdk/tree/master/runtime).

**Comment by Hixie** [comment]
Please keep me in the loop regarding your plans for this, as it affects my work on the Flutter license screen. Thanks.

**Comment by johnmccutchan** [comment]
@Hixie Acknowledged. I plan on focusing on this is around the 25th and will keep you in the loop.
