### ISSUE TITLE
Please merge 551eee3 to DEV.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26604]
@whesse @mit-mit @kasperl

Please merge [`551eee3`](https://github.com/dart-lang/sdk/commit/551eee30e5581cf81d3f1ccef9653ad28a27c9bd) to DEV. This change pulls in a patched linter.  The fixed linter addresses a broken lint rule (reported in https://github.com/dart-lang/sdk/issues/26596).  Otherwise, the changes introduced between this version of the linter and the previous are minor and should introduce no issues (and the linter travis build is [green](https://travis-ci.org/dart-lang/linter)).

Thanks!

**Comment by mit-mit** [comment]
Commit: https://github.com/dart-lang/sdk/commit/ade8d513194afa8e315b0844e839f49810a0bbcb

**Comment by whesse** [comment]
Merged in 1.17.0-dev.6.2
