### ISSUE TITLE
Editing is painfully slow

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26603]
I'm currently editing sdk/lib/html/dart2js/html_dart2js.dart and the editing experience is painfully slow. (I sometimes need to wait several seconds before I can continue typing).

I'm aware that this is a non-standard use case (43900 lines, and hundreds of errors), but maybe you can use this as a stress-test (and even fix some low-hanging fruits).

As an example, try to add a few new classes in front of the `class Window`.

**Comment by bwilkerson** [comment]
@jwren @alexander-doroshko

**Comment by alexander-doroshko** [comment]
@floitschG Even if analyzer is slow it shouldn't affect IDE typing performance, so this issue is at IDE side. Please file and issue in [WebStorm's issue tracker] (https://youtrack.jetbrains.com/issues/Web), Dart subsystem.

**Comment by floitschG** [comment]
Done: https://youtrack.jetbrains.com/issue/WEB-21906
