### ISSUE TITLE
loadLibrary() returns Future<bool> instead of Future<LibraryMirror>

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26609]
Please see https://api.dartlang.org/stable/1.16.1/dart-mirrors/LibraryDependencyMirror/loadLibrary.html

> Future < LibraryMirror > loadLibrary()
> Returns a future that completes with a library mirror on the library being imported or exported when it is loaded, and initiates a load of that library if it is not loaded.

In fact it returns Future < bool >. Proof:

``` dart
import "some_lib.dart" deferred as p;

onLoad(loadSucceeded) {
  print(loadSucceeded.runtimeType.toString()); // prints bool
  print(loadSucceeded); // prints true
}

main() {
  p.loadLibrary().then(onLoad);
}
```

Tested on Dart VM version: 1.17.0-dev.6.1 (Wed Jun 01 11:40:17 2016) on "windows_x64"

**Comment by natebosch** [comment]
Appears to be some confusion - the namespace `as p` is _not_ a `LibraryDependencyMirror` - it's a separate syntax concept. The docs you're linking to are for a method on a class within the mirrors.

`loadLibrary` only returns a `Future`.
https://www.dartlang.org/guides/language/language-tour#lazily-loading-a-library
