### ISSUE TITLE
Weird autocompletion suggestion

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26612]
![image](https://cloud.githubusercontent.com/assets/405837/15780047/0d9bc10c-29a0-11e6-8228-a23bfa64ea13.png)

Why is this `dom.ScrollAlignment` shown at all?

**Comment by alexander-doroshko** [comment]
This is WebStorm's 'middle matching' feature. Not related to Analysis Server.

**Comment by bwilkerson** [comment]
While I like the feature in general, I do think that matches that start with the entered partial identifier should be sorted closer to the top of the list than those that contain it somewhere in the middle. I don't know about other people, but I rarely start typing in the middle of an identifier. The only case I can think of is when I've forgotten that there is a prefix as part of the name.

**Comment by zoechi** [comment]
Definitely. The ones matching from the start this should be sorted first (treated as exact matches).
Perhaps I should choose a different color for highlighting the matching part, I didn't even recognize this entry is relevant at all ;-)

**Comment by alexander-doroshko** [comment]
In general we get positive feedback on middle matching.
Sorting is a separate question, I agree that seeing this variant as the first one in the list is not expected. This can be deicussed in WebStorm's issue tracker.

**Comment by zoechi** [comment]
Thanks for the feedback, sorry for the noise.
Created https://youtrack.jetbrains.com/issue/WEB-21916

**Comment by alexander-doroshko** [comment]
@zoechi Just curious, is this a bunch of manually created constants that you use to add //ignore comments? There's an [easier way to do it](https://youtrack.jetbrains.com/issue/WEB-14468#comment=27-1441876).

**Comment by alexander-doroshko** [comment]
Oh, I got it, those are not constants, but manually created live templates.
Live Templates in completions list are always shown AFTER real code-related completion variants. So looks like IDE is right, 'dom.ScrollAlignment' should be the first one.

Well, now you can simple delete all ign* live templates and use IDE's suppress feature.

**Comment by alexander-doroshko** [comment]
And one more tip. If you want to insert live template, but do not want to see any completion variants at all there are 2 more ways except Code Completion:
- Type live template abbreviation and press Tab. For example `sout<Tab>`
- If you do not remember abbreviation press Ctrl+J (Cmd+J), this will show all live templates available in current context.

**Comment by alexander-doroshko** [comment]
As for sorting code-related items in WebStorm's completion list, those that match at the beginning are already showed before middle-matches.
