### ISSUE TITLE
Please merge d357913 to dev

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26610]
Please merge d3579131c80434941855ce9cf1ebaee85767a4aa to DEV.

This change makes converters implement ChunkedConverters again. This avoids a wide-spread breakage due to same packages depending on it.

/cc @whesse @mit-mit

**Comment by mit-mit** [comment]
@whesse this was merged, right?

**Comment by whesse** [comment]
Merged in version 1.17.0-dev.6.3
