### ISSUE TITLE
The escape sequence \uD is not valid code point

### ISSUE THREAD

**Issue by luisvt** [dart-lang/sdk#26620]
When creating string that contains unicode between `\uD800` and `\uE000` I get next error:

```
The escape sequence \uD is not valid code point
```

For example having this code:

```dart
    print('\uD834\uDF06');
```

throws me an error similar to this:
```
Unable to spawn isolate: 'file:///file.dart': error: line 13 pos 23: invalid code point
    print('\uD834\uDF06');
                      ^
```

My Operating system is Linux Mint 17.3 and dart version is `1.17.0-dev.6.4`

**Comment by lrhn** [comment]
Dart string literals only allow valid code points, not individual code units. That made more sense when Dart strings were code point sequences, but now that they are UTF-16 code unit sequences, we might want to reconsider it.

There are workarounds. For `'\uD834\uDF06` the workaround is easy because it's a valid surrogate pair so you can just write `"\u{1D306}"`. Another workaround is `new String.fromCharCodes([0xd823,0xdf06])` which works for any code unit.

**Comment by alan-knight** [comment]
I think this is somewhat inconsistent. There are definitely some tests that do produce this, and it's valid in JavaScript, so I think we had removed some similar checks in Dartium. It was last August, but I can't seem to find the CL right now.

**Comment by luisvt** [comment]
I also tried using `\u{D834}` and it didn't work. Maybe I should use `\u{0D834}`.

**Comment by lrhn** [comment]
> I also tried using `\u{D834}` and it didn't work. Maybe I should use `\u{0D834}`.

That won't work either, it means exactly the same thing.

You can't have a single code point in the range U+D800..U+DFFF in a string literal. It's not a valid UTF-16 sequence, and string literals can only generate valid Unicode strings.
The reason that `\u{1d306}` works is that it adds an entire surrogate pair as one, not two individual surrogate code points.

Mind you, I'm not saying it isn't annoying. I usually only hit it while writing unit tests. If you are using strings to store binary data then you get into problems much easier (you might want to just store values in the range 0.255 then, both the VM and most JavaScript engines have special treatment of Latin-1 strings)..

**Comment by alan-knight** [comment]
I note that it works fine in dart2js, although the analyzer claims there's an error.
