### ISSUE TITLE
The "pub" script in the repo doesn't support ARM

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26621]
The sdk/bin/ directory in the dart-sdk repository has various shell scripts. The "dart" shell script tries to find the "best" out/ directory and run dart from there. The "pub" shell script, however, only looks for ReleaseX64.

This means that when you're using a local Dart repo checkout on an ARM system, and have locally built the tools, the "pub" script doesn't work, even though the "dart" one does.

Copying the logic from the "dart" script to the "pub" script fixes it.

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/pub#1422

**Comment by nex3** [comment]
Re-opening here because the pub script is in the SDK repo and usually only touched by SDK maintainers.
