### ISSUE TITLE
No default value is specified for Isolate errorAreFatal 

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26627]
The [description ](https://api.dartlang.org/stable/1.16.1/dart-isolate/Isolate/spawn.html) for constructor `Isolate.spawn()` reads:

> Future<Isolate> spawn(void entryPoint(message), message, {bool paused: false, bool errorsAreFatal, SendPort onExit, SendPort onError})
> ...
> If the errorAreFatal, onExit and/or onError parameters are provided, the isolate will act as if, respectively, setErrorsFatal, addOnExitListener and addErrorListener were called with the corresponding parameter and was processed before the isolate starts running.

There is no default value for the parameter `errorsAreFatal`. It is also not specified how the created (without the parameter) `Isolate` instance will handle the errors. The following sample code shows that by default `Isolate` instance is terminated on Dart VM version: 1.16.1 (Tue May 24 12:27:14 2016) on "windows_x64". (this behavior corresponds to `errorAreFatal:true`)
```dart
import "dart:isolate";
import "dart:async";

void entryPoint(SendPort sendPort) {
  // this should awake the isolate from suspended state, caused by error
  new Future.delayed(new Duration(seconds:2)).then(
      (_) {
        sendPort.send("finish");
      }
  );
  sendPort.send("hello");
  sendPort.send(", "+1); // cause an error that should stop the isolate
  sendPort.send("world");
}

main() async {
  ReceivePort receivePort = new ReceivePort();
  List receivedData = [];
  receivePort.listen(
     (data){
        print(data);
        receivedData.add(data);
     }
  );
  Isolate isolate = await Isolate.spawn(entryPoint, receivePort.sendPort);
  await new Future.delayed(new Duration(seconds:1));
  ReceivePort pingPort = new ReceivePort();
  pingPort.listen(
     (data) {
        print("receive ping back");
        receivedData.add(data);
     }
  );
  print("send ping");
  isolate.ping(pingPort.sendPort, response:"ping");
  await new Future.delayed(new Duration(seconds:2));
  receivePort.close();
  pingPort.close();
  print("receivedData: $receivedData");
}
```

**Comment by mit-mit** [comment]
CC @lrhn
