### ISSUE TITLE
Dart API documentation. Don't expose _internal interfaces

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26643]
For example see https://api.dartlang.org/stable/1.16.0/dart-core/Set-class.html

> Inheritance Object Iterable<E> Set
> Implements EfficientLength
> Implemented by CssClassSet HashSet SetMixin

EfficientLength is not part of public API but part of dart._internal and users should not know about it. It's part of implementation

**Comment by lrhn** [comment]
This is really an issue for the DartDoc tool. It is a private interface, but it *is* implemented by `Set`, so it's a matter of not displaying it.

Maybe we can avoid the problem by making an internal `class _Collection extends Iterable implements EfficientLength {}` in `dart:collection` and use that as a superclass of `Set`, `List` and `Queue`. Let's ask the dart-doc people if that would be enough to hide it.

**Comment by anders-sandholm** [comment]
Closing as I expect this to be handled in the new issue created in the dartdoc repo's issue tracker.
