### ISSUE TITLE
Style guide/Dart-formatter: Allow trailing commas in parameter and argument lists.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26649]
This is the formatting-specific issue for #26644. That issue has the details.

This might warrant an entry in the style guide to say how trailing commas should be used.
The formatter needs to handle trailing commas without ignoring them and format according to the style guide (https://github.com/dart-lang/dart_style/issues/509).

**Comment by munificent** [comment]
> This might warrant an entry in the style guide to say how trailing commas should be used.

Eventually, yes, but for now, I want to leave it unspecified and do some ethnography—lets see how the natives decide to use it in the wild.

Thanks for the tracking bug!

**Comment by munificent** [comment]
Fixed in dartfmt by: https://github.com/dart-lang/dart_style/issues/509

Closing this for the style guide since we don't currently plan to give guidance for this.
