### ISSUE TITLE
Memory leak when using countdown timer

### ISSUE THREAD

**Issue by dustinlessard-wf** [dart-lang/sdk#26654]
When we do something like :

``` dart
void doSomething {
new Timer(delay, () {
        this.doSomethingElse();
        doOtherThings();
      });
}
```

We expect the callback function to execute once, then the Timer becomes available for garbage collection.  This isn't the case.  In addition, the object where we execute `doSomethingElse` is also not eligible for garbage collection.

This was tested in Dartium (Dart 1.15.0) by doing:

``` dart
customTimer = new Timer(delay, () {
        this.doSomethingElse();
        doOtherThings();
      });

developer.inspect(customTimer);

```

And then checking the retaining path on the timer:

![screen shot 2016-06-08 at 11 17 00 am](https://cloud.githubusercontent.com/assets/2326518/15899680/8e69a5d8-2d6a-11e6-8ba6-c218e3334c4a.png)

A workaround has been to explicitly call `cancel` on the timer, after the callback function has executed (but not within the callback function itself), but this seems like something that should have happened automatically?

**Comment by floitschG** [comment]
I had a short look:
- in the VM implementation, the callback is cleared when the timer is invoked.
- in Dartium I would expect the same. The '_state' field of the inspected variable (the timer) is 'null' and as such the timer is inactive. The callback is only passed to `window._setInterval`, so if the closure is retained, then it would need to be there.
- in dart2js the internal "_handle" field is also cleared as soon as the callback is invoked.

Tbh I have troubles understanding the 'retaining path' of the observatory. Maybe it's including objects that haven't been GCed yet?
Maybe @johnmccutchan is better at interpreting it.

**Comment by alan-knight** [comment]
There are definitely known memory leaks in Dartium with the conversion to using JS Interop. It does seem like these should only arise if using operations that end up calling out to JS. But it's possible that Timers do in the browser?  Does this affect dart2js, or is it purely a Dartium problem. If so, unless it's enough of a problem to make development difficult, we'd probably consider it a lower priority.  @terrylucas

**Comment by floitschG** [comment]
How does a user disable these JS-interop retained-paths when debugging memory-leaks?

**Comment by dustinlessard-wf** [comment]
Additionally, 
updated to Dart 1.17.0 and reran this test in Dartium and found that Observatory reports the object is retained despite cancelling the timer.

Is the accuracy of the retaining path in Observatory in question? Is there another way to verify if an object is eligible for garbage collection?

This is some test code that illustrates the issue being observed:
```dart
import 'dart:developer' as developer;
import 'dart:async';

const Duration delay = const Duration(seconds: 10);

class CustomClass{

  Timer timer;

  CustomClass(){
    timer = new Timer(delay, this.printTime);
  }

  void printTime() {
    print(new DateTime.now());
  }

  void dispose(){
    timer.cancel();
  }
}

void useCustomClass(){
  CustomClass customClass = new CustomClass();
  developer.inspect(customClass);
  customClass.dispose();
}

main() async {
  useCustomClass();
}
```

The retaining path from Observatory:
![screen shot 2016-06-08 at 2 36 41 pm](https://cloud.githubusercontent.com/assets/2326518/15906360/74fc5b56-2d86-11e6-9cc5-e676d1542c7a.png)

**Comment by johnmccutchan** [comment]
@rmacnak-google for retaining path question

**Comment by rmacnak-google** [comment]
@dustinlessard-wf The retaining path is accurate, there is a leak here.

@alan-knight Timers in Dartium are implemented in terms of window.setTimeout/setInternal. The closure passed to setTimeout is maintaining a reference to the user's callback action even after the timer has been cancelled. It seems odd that this closure should be referenced after the timer has been cancelled, but there is a persistent handle keeping it alive, which I guess is how the JS-interop leaks manifest?

@floitschG The VM cannot tell if an object is alive because of JS-interop.

**Comment by alan-knight** [comment]
+ @jacob314  JS-interop expert

**Comment by kevin-quaver** [comment]
What is the status on this? I see the issue was closed, but I'm trying to force a garbage collection on a custom class with a Timer in it, but Observatory is still reporting the custom class' currently allocated instance is 1.

**Comment by terrylucas** [comment]
No more work is being on Dartium as of Dart 1.25.0-dev.6.0 (this includes Chromium 50). Please consider trying out the Dart Dev Compiler this is the replacement for a quick dev/debug cycle going forward.

Dartium was designed for a quick dev/debugging cycle.  Part of JSInterop with Chromium resulted in leaks that we decided was not as important in the developer dev cycle.
