### ISSUE TITLE
analyzer: Allow read-only access to initializing formals.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26658]
This is the analyzer specific issue for #26655. That issue has the details.

**Comment by floitschG** [comment]
Please also add a hint, when users capture the final parameter (and the field is not final). Otherwise there would be an observable difference between the captured variable and the variable in the body:

``` dart
class A {
  var x;
  var f;
  A(this.x) : f = () => x {   // <=== warn here.
    x++;
    print(f());
  }
}
```

Erik will add (or update) tests to show the intended behavior.

**Comment by bwilkerson** [comment]
I'm sure there are bugs in analyzer, but an initial implementation was added (https://codereview.chromium.org/2335693002/) that gives us the right semantics in terms of resolution.

I know that the requested hint hasn't been implemented yet.

**Comment by eernstg** [comment]
The remaining steps in this task are taken in #27895, hence closing this one and marking it complete in #26655.
