### ISSUE TITLE
Isolate with errorsAreFatal:false is terminated on second error

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26652]
According to [description ](https://api.dartlang.org/stable/1.16.1/dart-isolate/Isolate/spawn.html) of constructor `Isolate.spawn()` 

> If the errorAreFatal, onExit and/or onError parameters are provided, the isolate will act as if, respectively, setErrorsFatal, addOnExitListener and addErrorListener were called with the corresponding parameter and was processed before the isolate starts running.

The [description](https://api.dartlang.org/stable/1.16.1/dart-isolate/Isolate/setErrorsFatal.html) for `Isolate.setErrorsFatal` reads:

> Set whether uncaught errors will terminate the isolate.
> If errors are fatal, any uncaught error will terminate the isolate event loop and shut down the isolate.

The following sample code shows that Isolate is terminated after second error.

``` dart
import "dart:isolate";
import "dart:async";

void entryPoint(SendPort sendPort) {
  new Future.delayed(new Duration(seconds:1)).then(
      (_) {
        sendPort.send("second");
        sendPort.send(", "+2); // cause an error that should suspend the isolate
        sendPort.send("attempt");
      }
  );
  new Future.delayed(new Duration(seconds:2)).then(
      (_) {
        sendPort.send("third");
        sendPort.send(", "+3); // cause an error that should suspend the isolate
        sendPort.send("attempt");
      }
  );
  new Future.delayed(new Duration(seconds:3)).then(
      (_) {
        sendPort.send("finish");
        sendPort.send(", "+4); // cause an error that should suspend the isolate
        sendPort.send("attempt");
      }
  );
  sendPort.send("hello");
  sendPort.send(", "+1); // cause an error that should suspend the isolate
  sendPort.send("world");
}

main() {
  ReceivePort receivePort = new ReceivePort();
  List receivedData = [];
  receivePort.listen(
     (data){
       print(data);
        receivedData.add(data);
        if (data=="finish") {
          receivePort.close();
          print(receivedData);
        }
     }
  );
  Isolate.spawn(entryPoint, receivePort.sendPort, errorsAreFatal:false);
}
```

Output:

> hello
> second

Expected output:

> hello
> second
> third
> finish

Dart VM version: 1.16.1 (Tue May 24 12:27:14 2016) on "windows_x64"

However another sample code works as expected:

``` dart
import "dart:isolate";

void entryPoint(SendPort sendPort) {
  ReceivePort receivePort = new ReceivePort();
  receivePort.listen(
      (data) {
        print("isolate received: $data");
        print("aa"+1);
        print("message after error");
      }
  );
  sendPort.send(receivePort.sendPort);
  print("aa"+1);
}

main() {
  ReceivePort errorPort = new ReceivePort();
  errorPort.listen((e)=>print(e));

  ReceivePort receivePort = new ReceivePort();
  receivePort.listen(
      (data){
        data.send("test1");
        data.send("test2");
        data.send("test3");
        data.send("test4");
      }
  );
  Isolate.spawn(entryPoint, receivePort.sendPort, errorsAreFatal:false);
}
```

**Comment by lrhn** [comment]
I'm investigating. It seems the new isolate isn't actually terminating, it just gets stuck somehow.

**Comment by lrhn** [comment]
Looking at it more, the problem goes away if, in `timer_impl.dart`, the call to `_runTimers`  in `_handleMessage` gets wrapped in `try/finally` with the following call to `_notifyEventHandler` in the finally block.

Looking at `_runTimers`, the call to `callback` in there probably also needs to be guarded so the following code is updated in the case of a throw.

**Comment by alsemenov** [comment]
The problem is still reproducible on at least Dart VM version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"

**Comment by bkonyi** [comment]
Looks like this is working for `Dart VM version: 2.0.0-edge.541dd195bb536e69d992a7ee47d1c1884fb43456 (Fri Jun 15 16:24:24 2018 +0000) on "linux_x64`. Closing.
