### ISSUE TITLE
JS Interop bug - cannot invoke JS method

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#26653]
This issue was redirected from the Angular's Issue tracking to here. [Original issue](https://github.com/angular/angular/issues/9056#issuecomment-224599891)

**The problem**
Can't invoke JS class instance method from Dart under a set of circumstances:

* The name of the method must be `open`
* Parameters and return type of the method does not seem to affect behavior
* The name of the class does not affect the behavior
* The function must be a method of a class
* First invocation to the method must happen from inside an Angular 2 Component
* If an invocation to the method happens say right after calling bootstrap, all is well.
* Happens with transpiled code only, Dartium seem to be OK.

**Reproduction**
```
git clone https://github.com/daniel-v/angular2_js_interop.git
pub get && pub serve
# open in non-dartium browser and click on button
```

**Expected behaviour**
Upon clicking on the button, a console log message appears without any errors: `open called`

Dart 1.16.1
Angular 2.0.0-beta.17
JS 0.6.0

**Comment by anders-sandholm** [comment]
Moved to #26667
