### ISSUE TITLE
Observatory: Label GCs roots in retaining path / inbound references

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26663]
Retaining paths currently stop at an object that is reachable from a root, but it isn't always clear kind of root it is. It would be nice to label the root with something like "object store", "stack", "class table", "persistent handle", etc.

**Comment by johnmccutchan** [comment]
:clap: :clap: :clap:

**Comment by rmacnak-google** [comment]
@bkonyi 5f32027e1d096aeffa092918f9249151f198ea9b
