### ISSUE TITLE
RandomFileAccess.lockSync throws if it can't get a lock

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26665]
It would be nice if there was a way to make it block until it got the lock.
Similarly with the async variant. It would be great if one could tell it to just wait until it got the lock.
Maybe with a timeout, since there'd be no way to cancel the lock otherwise (short of closing the file?).

**Comment by zanderso** [comment]
We can probably do this in a non-breaking way by adding blocking modes to `FileLock`. I will take a look.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2050413002/
