### ISSUE TITLE
add hint for "throw throw"

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#26670]
To reproduce, copy this into dartpad:

main() {
  throw throw "hello";
}

There is no warning or hint, even in strong mode.

**Comment by floitschG** [comment]
Fwiw, it's a completely benign mistake.
It has the correct behavior and doesn't cost during execution.

**Comment by bwilkerson** [comment]
This would make a good lint rule.

**Comment by pq** [comment]
> This would make a good lint rule.

👍 

Closing here.  If folks want to pursue, please open a fresh request on the [linter proper](https://github.com/dart-lang/linter/).
