### ISSUE TITLE
Incorrect "dead code" hint after try/catch

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26676]
The following code generates a "dead code" hint on the line marked `// not dead yet`:

    main() {
      try {
        return f();
      } catch (e) {
        print('exception caught: $e');
      }
      print('after try statement'); // not dead yet
    }
    
    f() {
      throw 'foo';
    }

However, running this program indicates that the code is clearly not dead:

    $ sdk/bin/dart test.dart
    exception caught: foo
    after try statement

**Comment by stereotype441** [comment]
Note that this bug appears to have been introduced in 38e8d9702bb6a02fcb640a8c42044e7455892eeb.

**Comment by bwilkerson** [comment]
@srawlins Want to take a look at fixing this?

**Comment by srawlins** [comment]
Eek. I'm on vacation until Tuesday. But I'll look at it then if it's not
resolved yet.

**Comment by stereotype441** [comment]
Fix submitted for review: https://codereview.chromium.org/2054323002/
