### ISSUE TITLE
Bogus dead code hints with labeled break

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26677]
The following code:

```dart
void main() {
  loop: while (true) {
    switch (true) {
      case false: break;
      case true: break loop;
    }
  }

  print("not dead!");
}
```

prints "not dead!", but the analyzer (tested against f5ef3232ea367ec890de27095f2ef749b0859c7c) emits a dead code hint for that line:

```
$ dartanalyzer test.dart 
Analyzing [test.dart]...
[hint] Dead code (test.dart, line 9, col 3)
1 hint found.
```

Note that this also means that legitimate warnings like missing `return` statements aren't emitted in similar situations.

**Comment by srawlins** [comment]
Sorry about this, @nex3. Working on a fix.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/6b2c857cbb9f1d75d88916e24ac72bb3914e4807.
