### ISSUE TITLE
Difficult to avoid "dead code" hint without introducing warning

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26673]
The following code generates a "dead code" hint at the line marked `// "dead" code`:

    f(a) async {
      switch (a) {
      case 0:
        try {
          g();
        } finally {
          return 1;
        }
        break; // "dead" code
      default:
        break;
      }
    }

    g() {}

This is a problem because although the "break" statement is unreachable, it is mandated by the spec ("It is a static warning if the last statement of the statement sequence s<sub>k</sub> is not a <b>break</b>, <b>continue</b>, <b>return</b> or <b>throw</b> statement.").

Indeed, attempting to remedy the hint by deleting the offending `break;` statement causes analyzer to print the warning:

    The last statement of the 'case' should be 'break', 'continue', 'return' or 'throw'

This situation has arisen as a result of the recent improvement to dead code detection (38e8d9702bb6a02fcb640a8c42044e7455892eeb).  If that commit is reverted, then there is no "dead code" warning at the site of the break.

Suggested fix: suppress the "dead code" hint if the code identified as dead is a "break" statement and is the last statement of a case.

Note that in the case of the code above, there is a clumsy workaround: move the `return 1;` statement outside of the "finally" block.

**Comment by bwilkerson** [comment]
@munificent @leafpetersen

There's another possibility, which is to change the spec. Many users have questioned this requirement, both from the perspective of wanting analyzer to be smarter (as with the code above) to wondering why we need to type `break` at all rather than just define that as the default behavior.

**Comment by stereotype441** [comment]
Regarding the idea of making a spec change, just to be clear, I think you are suggesting the following changes:

a. change runtime behavior so that every case ends in an implicit "break"
b. remove the static warning if a case doesn't end in an explicit break/continue/return/throw.

Rather than:

c. change the static warning to "it is a static warning if the last statement of the statement sequence s<sub>k</sub> is *reachable*"

(Note that *c* is dodgy because the spec doesn't define what "reachable" means)  Assuming you are talking about *a* and *b* rather than *c*, I like it as a long term plan.  However, even if we make that change, I think we should still do the suggested fix I proposed above, as a short term fix.  After all, a spec change will take some time to percolate through to all the implementations, whereas users will start seeing this bogus hint starting with 1.18.0 (which was just released).

**Comment by bwilkerson** [comment]
Fair enough.

**Comment by bwilkerson** [comment]
@srawlins In case you're interested.

**Comment by munificent** [comment]
> a. change runtime behavior so that every case ends in an implicit "break"

While the explicit `break;` is tedious, it preserves compatibility with users' expectations coming from C, C++, Java, C#, JS, etc.

Instead of trying to make `switch()` a slightly more modern statement form, I'd rather introduce honest-to-God pattern matching, likely as a separate statement. But maybe that's just me.

**Comment by zoechi** [comment]
I have worked with other languages that require the `break` for years. I'm still prone to forget it. I wouldn't miss it for one second.

Pattern matching would still be an interesting feature to have :)

**Comment by bwilkerson** [comment]
So to be clear, I wasn't actually proposing any specific solution, just suggesting that we might want to take another look at the switch statement with an eye toward making it easier for users to use. I don't care whether that's by making the `break` implicit, defining reachability, or by replacing it completely. It might even be the case that the right answer is to do none of the above and just leave it alone.

**Comment by srawlins** [comment]
I can make a simple whitelist change to allow for mandated dead statements. If anyone wants to continue the spec change suggestion, I think that discussion should continue on a new issue.

**Comment by stereotype441** [comment]
@srawlins agreed.  I'll open a separate bug for the spec discussion.

**Comment by srawlins** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/6e58ff0575e57a68e73a2fc2438c9e713810cb25.
