### ISSUE TITLE
exception from the analysis server when changing git branches

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26672]
No stack trace for this unfortunately, but we saw this exception from the analysis server, when driven by `flutter analyze --watch --flutter-repo`. The user (@Hixie) was switching git branches.

/cc @pq @bwilkerson 

```
Task failed: ComputeConstantDependenciesTask for element @null in source .../flutter/packages/flutter_tools/lib/src/commands/analyze.dart
Error from the analysis server: Task failed: ComputeConstantDependenciesTask for element @null in source .../flutter/packages/flutter_tools/lib/src/dart/analysis.dart
```

**Comment by devoncarew** [comment]
Dart VM version: 1.17.0 (Mon Jun  6 14:12:55 2016)

**Comment by pq** [comment]
Hmmm.  Bummer there's no stack trace.  Where is the `@null` defined?  Or maybe that won't give us any clues...

**Comment by devoncarew** [comment]
I think we're missing code in the flutter analyze wrapper to write out the stack trace. I'll add that in to help with future issues -

**Comment by bwilkerson** [comment]
Thanks!

**Comment by pq** [comment]
Closing in favor of follow-on reports with more context.
