### ISSUE TITLE
Why I can not stop on breakpoint in Dartium, when breakpoint is not in entry point file?

### ISSUE THREAD

**Issue by sharikovvladislav** [dart-lang/sdk#26674]
Hi, 

I am doing Tour of heroes 2 tutorial. I have this code now: https://github.com/sharikovvladislav/angular2-hero-app

I noticed, that I can not debug `onSelect` handler in `app_component.dart` file.

I open app in Dartium. Also, I open DevTools. I set up breakpoint in `main.dart` file in `main` function. When I reload page, Dartium stops on the breakpoint. After that, I tried to stop in `onSelect` handler in `app_component.dart` file and realized, that Chrome doesn't stop on this breakpoint. Look this line: https://github.com/sharikovvladislav/angular2-hero-app/blob/a4ba11adbb75cd0d33fd184d250b9517cf20866d/lib/app_component.dart#L94. I put info message to console, when `onSelect` handler fires. I got this message in console, also application works as expected. But Chrome doesn't stop in onSelect handler. Why?

**Comment by zoechi** [comment]
I guess this is the answer http://stackoverflow.com/questions/26822902/breakpoints-in-dartium-not-working
Would be interesting though if this can be fixed in WebStorm so that breakpoints work on code in the `packages` directory. This is a common pitfall.

**Comment by terrylucas** [comment]
Please retry with Dart 1.24.2 Stable (Dartium 50).
