### ISSUE TITLE
Assert keyword

### ISSUE THREAD

**Issue by Songbird0** [dart-lang/sdk#26687]
Hi there ! 

I want to use "assert" keyword for write strong programs.
But, I've a problem: when the assertion state is **false**, exception isn't raised.
For example:
```dart
void main()
{
    String myString = null;
    assert (myString != null); //nothing
}
```

Have you same problem ?

Thanks for your help.

**Comment by fsc8000** [comment]
Are you running in --checked mode?

**Comment by Songbird0** [comment]
For native Dart program, it works, but when I compile dart program, it don't work.

I make an error ?

**Comment by lrhn** [comment]
How do you compile the program?

**Comment by Songbird0** [comment]
Hi,

Like this:
`dart2js -o mytest.dart.js mytest.dart`

**Comment by zoechi** [comment]
`assert()` is only executed in checked mode (development only). For `dart2js` you need to pass `-c` See also https://www.dartlang.org/tools/dart2js/

**Comment by Songbird0** [comment]
Ohw, ok. I didn't know. 
Thanks for your help ! :)
