### ISSUE TITLE
window.navigator.languages returns null on Internet Explorer / Edge

### ISSUE THREAD

**Issue by brianneal-wf** [dart-lang/sdk#26683]
It appears `window.navigator.languages` returns null on IE/Edge. Thus there doesn't seem to be a way to get at the user's language preferences on IE. 

Should navigator abstract away what browser we are running on and do whatever IE specific magic it needs to retrieve this setting for us?

**Comment by parlough** [comment]
I'm going to close this as IE and legacy Edge are no longer supported.

All modern browsers [support](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages#browser_compatibility) this API now and for posterity, legacy Edge added support sometime during EdgeHTML 16 release cycle.

If anyone has issues using these libraries on recent browser versions, please open a new issue. Thanks! :D
