### ISSUE TITLE
Flutter `analyze` slow down between dev.6.1 and dev.6.2

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26697]
It looks like somewhere between `1.17.0-dev.6.1` and `1.17.0-dev.6.2` a change was introduced that takes the time to `flutter analyze` the flutter repo from ~25s to ~30s.  We're tracking this on our dashboard where the [CL to pull in 6.1](https://github.com/flutter/flutter/commit/24dbf31a85df42e9687c208e7c66acdba8baa23f) accounts for the bump seen here.

![screen shot 2016-06-13 at 3 08 03 pm](https://cloud.githubusercontent.com/assets/67586/16024853/d2900b64-3178-11e6-9a9e-966527bab841.png)

FWIW: I confirmed with a git bisect as well.

There is no difference in the packages used by the flutter `analyze` command which makes me suspect a VM issue (though I'm just as happy to be proven wrong).  Are there any more details I can collect to help narrow this down?

Thanks in advance!

**Comment by a-siva** [comment]
Between 1.17.0-dev.6.1 and 1.17.0-dev.6.2 we turned background compilation off by default because of some stability issues. It has been turned back on in 1.18.0-dev.0.0

**Comment by pq** [comment]
Aha!  Fantastic.  Thanks for the quick follow-up.  I'll try `1.18.0-dev.0.0` and see how we fare.

**Comment by pq** [comment]
Confirmed that `1.18.0-dev.0.0` fixes it.  Thanks again! 👍

**Comment by keertip** [comment]
@a-siva, so can we assume that the stability issues are fixed in `1.18.0-dev.0.0`?

**Comment by mraleph** [comment]
@keertip I have fixed those flakey issues that we have seen with background compilation and put in some addition checks. that's why we re-enabled it. whether or not we fixed it entirely - nobody knows, but I have not seen a flake on dart2js bot so far.

**Comment by keertip** [comment]
Good to know, thanks!

On Tue, Jun 14, 2016 at 5:21 AM, Vyacheslav Egorov <notifications@github.com
> wrote:

> @keertip <https://github.com/keertip> I have fixed those flakey issues
> that we have seen with background compilation and put in some addition
> checks. that's why we re-enabled it. whether or not we fixed it entirely -
> nobody knows, but I have not seen a flake on dart2js bot so far.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26697#issuecomment-225864181>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACFzuMRXd6rp9Uy-yzYYNNMjCel3ykidks5qLpzJgaJpZM4I0ypi>
> .
>



-- 
Keerti
