### ISSUE TITLE
window.performance.memory producing unexpected results in content-shell and dartium

### ISSUE THREAD

**Issue by sebastianmalysa-wf** [dart-lang/sdk#26693]
Using the following code I get roughly 15 MB in content-shell and roughly 10 MB in Dartium (opened with --enable-precise-memory-info) when calling window.performance.memory.usedJSHeapSize regardless of maintaining a reference to an object that should result in a larger usedJSHeapSize: 

``` dart
@TestOn('browser') // for content-shell only

import 'dart:async';
import 'dart:html';
import 'package:test/test.dart'; // for content-shell only

main () async { 

List<Uri> uriList = [];

for (int i = 0; i < 1000000; i++) {
 uriList.add(Uri.parse('localhost$i'));
 // window.performance.memory // if this is added here a huge usedJSHeapSize results
}

new Future.delayed(new Duration(seconds: 30), (){
 print(uriList.length);
});

new Timer(new Duration(seconds: 20), () {
 window.performance.memory.totalJSHeapSize;
 window.performance.memory.usedJSHeapSize;
});
```

If the same code is run within Chrome (opened with --enable-precise-memory-info) a fairly consistent usedJSHeapSize of roughly 200 MB results. I've also monitored the uriList object in Observatory and know that it should take up 96 MB and that it doesn't get garbage collected. Additionally, if window.performance.memory is added within the above loop, just after the Uri is added to uriList, a very high usedJSHeapSize in both the content-shell and Dartium of roughly 700 MB results. The major difference between the results from the various tests I've conducted (content-shell, Dartium and Chrome) seem not very accurate (Chrome seems the most promising). However, the results are almost always highly consistent. I'm curious if there is a way to get an accurate usedJSHeapSize reading from content-shell or Dartium using window.performance.memory or if there is a problem with window.performance.memory.

**Comment by sebastianmalysa-wf** [comment]
***Update: 

'''dart
import 'dart:async'
import 'dart:html'

const Duration delay = const Duration (seconds: 20);

main () async {
print(window.performance.memory.usedJSHeapSize);

for (int i = 0; i < 1000000; i++){
 window.performance.memory;
}

new Future.delayed(new Duration(seconds: 30), (){
 print(window.performance.memory.usedJSHeapSize);
});

new Timer(delay, () {
print(window.performance.memory.usedJSHeapSize);
});
}
'''

When running the above code in content-shell and Dartium (with --enable-precise-memory-info) the usedJSHeapSize is roughly 700 MB. When the same code is executed in Chrome (with --enable-precise-memory-info) the result is roughly 7 MB. This discrepancy makes me wonder if there is a potential issue with window.performance.memory when used on content-shell and Dartium. Should the usedJSHeapSize be growing every time window.performance.memory is called?

**Comment by kevmoo** [comment]
Closing: not concerned with Dartium any more
