### ISSUE TITLE
warning The getter 'key' is not defined for the class 'KeyboardEvent'.

### ISSUE THREAD

**Issue by Zectbumo** [dart-lang/sdk#26707]
I am getting an error in Dartium and Chrome when trying to access the key property on a KeyboardEvent object. I tested this on DartPad and I see a warning. Oddly enough the app works. Although maybe it is because DartPad is on Dart V1.16.0 and I'm running Dart V1.17.1.
https://dartpad.dartlang.org/1ba18057a006a6654086783dc43ea5c2
https://gist.github.com/1ba18057a006a6654086783dc43ea5c2

**Comment by zoechi** [comment]
Looks like a dup of #26699

**Comment by anders-sandholm** [comment]
Thanks @zoechi - does indeed look like a dup of #26699.
