### ISSUE TITLE
Dartium JS interop patch doesn't escape dollar signs in identifiers

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#26718]
```dart
@JS()
library js_interop_dollar_test;

import 'package:js/js.dart';

@JS()
external void $jsMethod();

main() {
  $jsMethod();
}
```

The above code works compiled to JS, but in Dartium, in throws this error:
```
Exception: No top-level getter or setter 'jsMethod' declared.

NoSuchMethodError: method not found: 'jsMethod'
Receiver: top-level
Arguments: [...]
```

Note the `.dart_js_interop_patch.dart` file:
```dart
import 'dart:js' as js_library;

/**
 * Placeholder object for cases where we need to determine exactly how many
 * args were passed to a function.
 */
const _UNDEFINED_JS_CONST = const Object();

patch $jsMethod() {
  return js_library.JsNative.callMethod(js_library.context, '$jsMethod',[]);}
```

The dollar sign in `$jsMethod` should be escaped, otherwise it incorrectly tries to interpolate the rest of the method name.

**Comment by jacob314** [comment]
Fixed by
https://github.com/dart-lang/sdk/commit/e010460709cb952c59715ea2c2c3473408fa4838
Note that the syntax is 
JS$someMethod

**Comment by jacob314** [comment]
Full fix provided by https://github.com/dart-lang/sdk/commit/96ca5db7e5ad4a7c259376b7ce1bf2d694ccf479
