### ISSUE TITLE
`INVALID_USE_OF_PROTECTED_MEMBER` flagging refs in doc comments.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26713]
See for example:

<img width="624" alt="screen shot 2016-06-15 at 9 25 02 pm" src="https://cloud.githubusercontent.com/assets/67586/16105498/cf7f2b3a-333f-11e6-9d22-9cc818eff6b4.png">

My initial instinct is that we don't want this behavior and that these refs in doc comments are OK.

This test repros:

```dart
  void test_invalidUseOfProtectedMember_in_docs_OK() {
    Source source = addSource(r'''
import 'package:meta/meta.dart';

class A {
  @protected
  int a() => 42;
}

/// OK: [A.a].
f() {}
''');
    computeLibrarySourceErrors(source);
    assertNoErrors(source);
    verify([source]);
  }
```

Marking this as P1 since it's potentially a dev roll blocker.

cc @bwilkerson, @Hixie for thoughts.

**Comment by pq** [comment]
FWIW locations flagged in the flutter repo:

```
[hint] The member 'debugFillDescription' can only be used within instance members of subclasses of 'RenderObject' (packages/flutter/lib/src/rendering/debug.dart, line 74, col 101)
[hint] The member 'computeMaxIntrinsicWidth' can only be used within instance members of subclasses of 'RenderBox' (packages/flutter/lib/src/rendering/grid.dart, line 236, col 18)
[hint] The member 'computeMinIntrinsicWidth' can only be used within instance members of subclasses of 'RenderBox' (packages/flutter/lib/src/rendering/grid.dart, line 220, col 18)
[hint] The member 'computeMaxIntrinsicHeight' can only be used within instance members of subclasses of 'RenderBox' (packages/flutter/lib/src/rendering/grid.dart, line 268, col 18)
[hint] The member 'computeMinIntrinsicHeight' can only be used within instance members of subclasses of 'RenderBox' (packages/flutter/lib/src/rendering/grid.dart, line 252, col 18)
[hint] The member 'build' can only be used within instance members of subclasses of 'StatelessWidget' (packages/flutter/lib/src/widgets/framework.dart, line 1609, col 23)
[hint] The member 'setState' can only be used within instance members of subclasses of 'State' (packages/flutter/lib/src/widgets/framework.dart, line 772, col 52)
[hint] The member 'debugFillDescription' can only be used within instance members of subclasses of 'Element' (packages/flutter/lib/src/widgets/framework.dart, line 294, col 21)
[hint] The member 'build' can only be used within instance members of subclasses of 'StatelessWidget' (packages/flutter/lib/src/widgets/framework.dart, line 1619, col 23)
[hint] The member 'build' can only be used within instance members of subclasses of 'State' (packages/flutter/lib/src/widgets/framework.dart, line 1639, col 23)
[hint] The member 'build' can only be used within instance members of subclasses of 'State' (packages/flutter/lib/src/widgets/framework.dart, line 1650, col 22)
[hint] The member 'build' can only be used within instance members of subclasses of 'StatelessWidget' (packages/flutter/lib/src/widgets/framework.dart, line 1626, col 23)
[hint] The member 'build' can only be used within instance members of subclasses of 'StatelessWidget' (packages/flutter/lib/src/widgets/framework.dart, line 483, col 42)
```

**Comment by Hixie** [comment]
That is pretty funny.

But yeah. All refs in dartdocs should be allowed. We have bugs on file about making even more references allowed, e.g. having dartdocs be able to reference anything in the project, not just anything that's imported (or having dart-doc specific imports).

**Comment by bwilkerson** [comment]
I agree. It isn't useful to restrict references in Dartdoc based on visibility.

**Comment by zoechi** [comment]
I find it quite useful to get hints when I have references in dartdoc that can't be resolved because they might have been missed in refactorings or whatever. What's the purpose of using reference style in docs when they can't be resolved. As far as I understand using `` ` ` `` instead of `[]` would make more sense in such cases. Maybe I'm misinterpreting something...

**Comment by bwilkerson** [comment]
I think we're making a distinction between "can't be resolved" and "can be resolved to something that shouldn't be referenced in code in this context". It's definitely useful to know when you're referencing something that doesn't exist.

And (I think) we're not talking about references to library-private names either. Those still won't be resolved and will result in a warning.

What we are talking about are warnings based on visibility annotations like `@protected`, where the name is visible, based on Dart's rules, but which has been marked as something that ought not to be used for other reasons.

**Comment by Hixie** [comment]
Right. When I say all refs should be allowed, I mean all actual references that can be resolved, not that we shouldn't check anything.

**Comment by pq** [comment]
https://codereview.chromium.org/2078493002/
