### ISSUE TITLE
Update dependencies in pkg/analyzer and release

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26711]
- [x] html (support 0.13.0)
- [x] package_config (support 1.0.0)
- [x] string_scanner (support 1.0.0)

Will have to update DEPS and changes analyzer_cli, etc

Many things that use pkg/analyzer are not getting the latest version of pkg/crypto, pkg/convert because the latest version has not been published

**Comment by devoncarew** [comment]
+1. I notice version skew between the warnings reported by the latest dev sdk and that reported by the last published analyzer version (`0.27.4-alpha.13`).

**Comment by kevmoo** [comment]
Ping? Not burning the world down, but it is causing some version skew across some important packages.

**Comment by nex3** [comment]
This is blocking dart-lang/test#414. We need to upgrade analyzer to get better parsing, but if we do so its constraints mean our other dependencies are no longer strong-mode clean 😕.

**Comment by nex3** [comment]
Also, it looks like analyzer 0.27.3 is incompatible with crypto 2.0.0 for whatever reason.

**Comment by devoncarew** [comment]
It looks like the source in the sdk repo supports the latest packages. A non-dev version of the `analyzer` package hasn't been published since April (and has the older crypto dep). I think the resolution here is to publish a new non-dev version.

/cc @bwilkerson

**Comment by mit-mit** [comment]
We should get this assigned to someone now that it's tagged P1. @bwilkerson who can work on this?

**Comment by bwilkerson** [comment]
> ... who can work on this?

Anyone. It doesn't even need to be someone on the analyzer team.

I'm not sure, based on the comments, what all needs to be done. My best guess is that analyzer's pubspec needs to be updated to allow html 0.13.0 (because it's in the checklist) and that we need to publish a non-alpha version of analyzer. Is that sufficient? What are the criteria for success?

**Comment by bwilkerson** [comment]
The version constraints for html have been updated (https://codereview.chromium.org/2202573002/). Is there anything else needed before we publish a non-alpha version?

**Comment by bwilkerson** [comment]
Version 0.27.4 of analyzer has now been published. Can someone please let me know whether this solves the problem.

**Comment by mit-mit** [comment]
@kevmoo, are we good?

**Comment by kevmoo** [comment]
We're good! Thanks!
