### ISSUE TITLE
Memory leak getImageData?

### ISSUE THREAD

**Issue by infowdoawnd** [dart-lang/sdk#26717]
I am getting a memory leak when calling 
context.getImageData(0, 0, canvas.width, canvas.height); in a loop.

I am using dartium version 45.0.2454.104.
Vm version is 1.17.0-dev.6.0

**Comment by zoechi** [comment]
What about Chrome? Dartium is development only and memory leaks are kinda expected.

**Comment by infowdoawnd** [comment]
I was hoping it'd work in Dartium aswell, I haven't succeeded in compiling it to javascript because I had some errors, I'll try to figure that out then. Thanks
