### ISSUE TITLE
Analyzer gives confusing errors for default values that use unknown identifiers

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26710]
``` dart
class A { A({ bool argument: BogusValue.bogus }); }
void main() { }
```

->

```
[error] Default values of an optional parameter must be constant (test.dart, line 1, col 30)
[warning] Undefined name 'BogusValue' (test.dart, line 1, col 30)
```

The second message is the real error. The first message is very confusing, because:
- It can appear far before the second, e.g. if you sort errors by severity and you have a lot of errors.
- It says that the value isn't a constant, which has nothing to do with the actual error. Typically the error is actually that you've forgotten an import, or some such. Reading the message about not being a constant can send you entirely down the wrong path when trying to debug it.

**Comment by srawlins** [comment]
Similar to #35828 and #32764

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/302660
