### ISSUE TITLE
Failure in dart2js HTMLOutputElement test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26714]
The test co19/LayoutTests/fast/dom/HTMLOutputElement/htmloutputelement_t01
fails on linux Firefox 47.  This reproduces locally on linux with firefox. The failure is suppressed in
tests/co19/co19-dart2js.status.

The output is:
Actual: RuntimeError
  type: sync_exception
              value: Exception: TypeError: J.getInterceptor$x(...).get$value is not a function
                    Stack: J.get$value$x@http://127.0.0.1:41703/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2170:12
                    dart<.main@http://127.0.0.1:41703/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2062:38
                    dartMainRunner@http://127.0.0.1:41703/root_dart/tools/testing/dart/test_controller.js:311:5
                    @http://127.0.0.1:41703/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2544:7
....

The output in a local browser console is:
{
  "type": "sync_exception",
  "value": "Exception: TypeError: J.getInterceptor$x(...).get$value is not a function\nStack: J.get$value$x@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2170:12\ndart<.main@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2062:38\ndartMainRunner@http://127.0.0.1:52671/root_dart/tools/testing/dart/test_controller.js:311:5\n@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2544:7\n@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2530:7\n@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:2524:4\n@http://127.0.0.1:52671/root_build/generated_compilations/dart2js/tests_co19_src_LayoutTests_fast_dom_HTMLOutputElement_htmloutputelement_t01/test.js:17:2\n",
  "timestamp": 0.045
}

**Comment by alan-knight** [comment]
In Chrome the result of htmlFor is a DOMTokenList. In Firefox it is a DOMSettableTokenList, whose prototype is Function. As a result it suffers from the same problem as in #25155

**Comment by whesse** [comment]
Another test failing with the same error is co19/LayoutTests/fast/dom/icon-size-property_t01, failing on FF.

Suppressing it in the status file

**Comment by whesse** [comment]
This is fixed by the new dom dart2js implementation from Dartium 50, I think.
The tests are no longer failing.
Removing the status lines.
