### ISSUE TITLE
dynamic calls to object members on null don't work

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26719]
null should support Object members (e.g. `null.toString()`, `null.hashCode` should work). If it ends up as a dcall, then we don't find the method correctly.

This may not be a dynamic helper bug ... it may be that we shouldn't have generated this call as a dynamic call. In my case it was an explicit nSM call: `dynamic d; Invocation i; d.noSuchMethod(i);` ... that call was generated as `dsend(d, 'noSuchMethod', i)` which seems wrong.

**Comment by floitschG** [comment]
Is this a DDC bug?

**Comment by jmesserly** [comment]
oops! yes, I got my wired crossed.

**Comment by jmesserly** [comment]
moved to https://github.com/dart-lang/dev_compiler/issues/594

**Comment by jmesserly** [comment]
Leaf reminded me (https://github.com/dart-lang/dev_compiler/issues/594#issuecomment-227504353) it might be an Analyzer bug in how these calls are marked, e.g. it might be incorrectly marking them as dynamic calls. Maybe that's what I was thinking. But I'll re-file with a better description and appropriate labels (analyzer-strong-mode) if that turns out to be the case :)
