### ISSUE TITLE
co19 shadow dom tests fail on chrome 51

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26729]
6 dom tests are failing on chrome 51, mainly because of a change that you can't have two shadow trees at once.  Please investigate, and see whether this should be filed as a co19 issue instead.  The failing tests are

LayoutTests/fast/dom/shadow/olderShadowRoot_t01: RuntimeError #
LayoutTests/fast/dom/shadow/shadowdom-for-input-spellcheck_t01
LayoutTests/fast/dom/shadow/shadowdom-for-input-type-change_t01
LayoutTests/fast/dom/shadow/shadowroot-clonenode_t01
LayoutTests/fast/dom/shadow/shadowroot-host_t01
WebPlatformTest/shadow-dom/html-elements-and-their-shadow-trees/test-004_t01

and an example failure is
FAILED: dart2js-chrome release_ia32 co19/LayoutTests/fast/dom/shadow/olderShadowRoot_t01
Expected: Pass 
Actual: RuntimeError
              type: sync_exception
              value: Exception: InvalidStateError: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts an user-agent shadow tree.
                    Stack: Error: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts an user-agent shadow tree.
                        at Error (native)
                        at main (http://127.0.0.1:62432/root_build/generated_compilations/dart2js/co19_domshadow_olderShadowRoot_t01/test.js:1713:78)
                        at dartMainRunner (http://127.0.0.1:62432/root_dart/tools/testing/dart/test_controller.js:311:5)
                        at http://127.0.0.1:62432/root_build/generated_compilations/dart2js/co19_domshadow_olderShadowRoot_t01/test.js:2203:7
                        at init.currentScript (http://127.0.0.1:62432/root_build/generated_compilations/dart2js/co19_domshadow_olderShadowRoot_t01/test.js:2189:7)
                        at http://127.0.0.1:62432/root_build/generated_compilations/dart2js/co19_domshadow_olderShadowRoot_t01/test.js:2200:5
                        at http://127.0.0.1:62432/root_build/generated_compilations/dart2js/co19_domshadow_olderShadowRoot_t01/test.js:2208:3
              timestamp: 0.033

**Comment by athomas** [comment]
LayoutTests have been deleted.
