### ISSUE TITLE
Isolate.spawnUri() inconsistent specification

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26720]
The [description ](https://api.dartlang.org/stable/1.17.1/dart-isolate/Isolate/spawnUri.html) for method Isolate.spawnUri() reads:

> Future<Isolate> spawnUri(Uri uri, List<String> args, message, {bool paused: false, SendPort onExit, SendPort onError, bool errorsAreFatal, bool checked, Map<String, String> environment, Uri packageRoot, Uri packageConfig, bool automaticPackageResolution: false})
>
> Creates and spawns an isolate that runs the code from the library with the specified URI.
> 
> The isolate starts executing the top-level main function of the library with the given URI.
> 
> The target main must be callable with zero, one or two arguments. Examples:
> 
> main()
> main(args)
> main(args, message)
> When present, the parameter args is set to the provided args list. When present, the parameter message is set to the initial message.

Please, take a look at parameters `args` and `message`. In the method `spawnUri` `args` is required to be of type `List<String>`, while `message` is `dynamic`. It is not clear why the type of `args` is restricted to `List<String>`, while isolate target function `main` accepts `args` of any type and type of `message` is not restricted at all. 

It seems that parameter `args` is redundant, single parameter `message` would be enough (as in method [Isolate.spawn()](https://api.dartlang.org/stable/1.17.1/dart-isolate/Isolate/spawn.html)). If it is necessary to pass several values, they can be packed into `List` and passed as single value.

**Comment by lrhn** [comment]
The reason for the `args` argument is that `spawnUri` spawns a Dart *script* file like if it was run from the command line. The `main` function of a script takes the two parameters - the `List<String>` for command line parameters and the `message` to allow `spawnUri` to send a non-string value as well.

It's mainly for backwards compatibility. We could just have one parameter which can be anything, but this is simpler to handle for existing code which assumes that the first argument is a string list.
