### ISSUE TITLE
Dartium exception (1.17.1)

### ISSUE THREAD

**Issue by markhats** [dart-lang/sdk#26726]
I've just updated to the latest stable Dart SDK (1.17.1) and Dartium. I was previously using 1.14.0. I now get an error when trying to run/debug my app in Dartium:

```
Unhandled exception:
The null object does not have a getter 'reflectedType'.

NoSuchMethodError: method not found: 'reflectedType'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      setupJsTypeCache (dart:js:654)
#3      _generateInteropPatchFiles (dart:js:672): http://localhost:63342/Autograph/web/autograph.html_bootstrap.dart
```

If I revert back to my previous version of Dartium (39.0.2171.0) but keep the 1.17.1 SDK it seems to eliminate the error, so it seems to be an issue with the latest Dartium.

**Comment by dougreese** [comment]
I am seeing this with SDK version 1.20.1 and Dartium 45.0.2454.104 (64-bit) on OS X.  No issues with the code generated with `pub build`.

**Comment by terrylucas** [comment]
Please re-try with Dart 1.24.2 Stable
