### ISSUE TITLE
co19 shadow-disable_t01 test makes following test time out on ie11 Win8

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26737]
About half the time, the test that runs after co19/LayoutTests/fast/dom/shadow/shadow-disable_t01 will time out, and the report will say that the test didn't start on the browser.
This is happening on ie11 on Windows 8.

Something this test is doing makes the following test fail, but I can't see immediately what that would be.

Skipping this test on ie11, in tests/co19/co19-dart2js.status.

**Comment by athomas** [comment]
We will disable all the LayoutTests soon.
