### ISSUE TITLE
Disallow user defined classes that implement Future

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#26732]
Motivation: this makes it possible to fully align JS Promise and Dart Future.
In JS, you can create custom Promise classes by subclassing Promise but you cannot just duck type an object to be a Promise (equivalent of implements vs. extends in Dart).

There are only a few existing user defined Dart Future classes and it is not clear all of them really play well with dart:async as it is possible some parts of dart:async depend on future objects being instances of the _Future class.

**Comment by nex3** [comment]
There are several classes in the `async` package that implement `Future`: `ResultFuture`, `DelegatingFuture`, and `TypeSafeFuture`. All of these are used in the ecosystem, and the last one in particular is very widely-used since it's the best strong-mode-safe way of casting the generic type of a `Future`.

Currently the `Future` class cannot be extended. Even if it could, it's not clear to me how extension would work for these types; they all work by wrapping and forwarding to an inner instance of `Future`.

**Comment by jacob314** [comment]
Chatted offline with @nex3 to see what the best way to support the functionality provided by these 3 classes.
Preliminary conclusions are it would make the most sense to add the cast functionality provided by `TypeSafeFuture` and friends directly to `Future` as the behavior is crucial for strong mode.

`ResultFuture` on the other hand can be implemented as a user mode `Future` subclass as long as `Future` has a constructor with the same behavior of the JavaScript `Promise` constructor. The behavior provided by this constructor is similar to that of `Promise` except that it is possible to subclass the type of the resulting `Future`
Example of the anticipated `Future` constructor which would be efficient to implement in Dart2JS:
```dart
class Future<T> {
  Future<T>(executor(resolve(T value) , reject(reason)));
}
```

**Comment by nex3** [comment]
To integrate well with Dart's error-handling, I'd expect that to be:

```dart
class Future<T> {
  Future<T>(void executor(void resolve(T value), void reject(error, [StackTrace stackTrace]));
}
```

**Comment by leafpetersen** [comment]
cc @floitschG @lrhn @eernstg @munificent 

Is this something we should consider?  There are definitely things out there which implement Future, so seems non-trivial.

**Comment by lrhn** [comment]
There are definitely classes implementing `Future`. Most are wrappers of some sort, like [DelegatingFuture](https://github.com/dart-lang/async/blob/master/lib/src/delegate/future.dart), but I'm sure some are being more clever. I've generally tried to avoid classes that *extend* `Future`, but I'd be surprised if someone else haven't made one.

I think it's not going to be a viable change to disallow those classes now.

**Comment by munificent** [comment]
👍  to what @lrhn said. It would be helpful, but the cat's already out of the bag.

**Comment by eernstg** [comment]
If the right solution is to prevent `extend` but allow `implement` for this particular class, we could just postpone this issue until we have the right tool for dealing with it, i.e., some general feature that allows us to declare "you can/cannot extend/implement/mix-in/... this class". At that time it may still be too much of a disruption to change `class Future` to `interface Future` (or whatever syntax we'll use for that) in ordrer to prevent subclassing, but it's then a library issue, not a language issue.

So I agree that we should not introduce special rules for `Future` at this point.

**Comment by lrhn** [comment]
We already prevent subclassing of `Future` because all constructors are factory constructors. That's not sufficient to allow the compiler to assume that all `Future` instances are JS `Promise` objects.

**Comment by floitschG** [comment]
Normally, all of `dart:async` is ok with user-supplied futures. We do have shortcuts, but never rely on them. (If we do, it's a bug).

Can't dart2js/DDC recognize, that a class implements `Future` and then subclass `Promise`?

**Comment by dgrove** [comment]
@leafpetersen I presume this can be closed?

**Comment by leafpetersen** [comment]
No planned.
