### ISSUE TITLE
dart2js fails test language/regress_18713

### ISSUE THREAD

**Issue by mhausner** [dart-lang/sdk#26743]
```
class T<X> {
  final Type tType = X;
  Type get getTType => X;
}

class S<Y> {
  final Type sType = Y;
  Type get getSType => Y;
}

class TS<A, B> = T<A> with S<B>;

main() {
  var ts = new TS<int, String>();
  print(ts.sType);
  print(ts.tType);
  print(ts.getSType);
  print(ts.getTType);
}
```

The above code is essentially the test case tests/language/regress_18713_test.dart. The expected output is 

String
int
String
int

but dart2js prints 

String
int
int
int

**Comment by sigmundch** [comment]
(this is being tracked directly in .status files, so closing the redundant bug entry)
