### ISSUE TITLE
AOT optimizer should be able to inline [] and []= especially for typed data.

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#26749]
Currently AOT optimizer does not inline `[]` and `[]=` even if the receiver type is known. 

If we would like to eliminate excessive boxing unboxing - we need to look into enabling inlining for these methods.

**Comment by fsc8000** [comment]
We'd need a bounds check that does not deoptimize for that.

**Comment by mraleph** [comment]
Yep.

Alternatively we should just whitelist them for normal inlining and see how good is the code. 

They have relatively optimizable implementation:

```dart
  double operator[](int index) {
    if (index < 0 || index >= length) {
      throw new RangeError.index(index, this, "index");
    }
    return _getIndexedFloat64(index);
  }
```

if `index` is known to be a smi we should be able to produce good code for this.

**Comment by rmacnak-google** [comment]
@aartbik This is done, right?

**Comment by aartbik** [comment]
Yes, this was pretty much my starter project.
