### ISSUE TITLE
Invalid argument when handling Service Worker registration Future

### ISSUE THREAD

**Issue by tomconnell-wf** [dart-lang/sdk#26753]
I am using Dart SDK 1.17.1.

This code

```
import 'dart:async';
import 'dart:html';

void main() {
  Future serviceWorkerRegistration =
      window.navigator.serviceWorker.register('sw.js');

  serviceWorkerRegistration.then(
    () { print('ermagerd registered'); }
  );
}
```

running in Dartium results in 

> Exception: Invalid argument(s): Attempt to pass Function 'Closure: () => dynamic' to JavaScript via without calling allowInterop or allowInteropCaptureThis

I don't see any documentation or indication that I should be using dart:js in anyway, so I'm a little perplexed, and thinking this may be a bug.

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK. Dartium is not supported.
