### ISSUE TITLE
Add indexOfList(List<T> subList) method to List class

### ISSUE THREAD

**Issue by Google-Cat** [dart-lang/sdk#26759]
We have indexOf(T element) method, that find element in list, but there isn't method, that finds a sublist in list. In Java language there is a special `Collections` class.

**Comment by Google-Cat** [comment]
Something like that:
`int indexOfArray(List<E> sourceArray, List<E> subArray) {
    for (int k = 0; k < sourceArray.length - subArray.length + 1; k++) {
      for (int c = 0; c < subArray.length; c++) {
        if (sourceArray[c + k] != subArray[c]) {
          break;
        }
        if (c == subArray.length - 1) {
          return k;
        }
      }
    }
    return -1;
  }`

**Comment by lrhn** [comment]
This is fairly specialized functionality, and it is something that can work perfectly well as a static function in a helper package, so I don't expect us to add it to the `List` class. The bar for adding to the `List` class is pretty high by now.

I can see some cases where a specialized version could be more efficient, e.g., searching in a `Unit8List` using KMP or BMH string search algorithms (which relies on the limited range of the values), but if that is actually important, adding it to just `Uint8List` or `TypedDataList` is more likely than adding the function to the core `List` interface.
