### ISSUE TITLE
Unittest package can be deleted in Windows checkout

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26758]
Now that the windows build has been moved to the "out" directory, I think we have some scripts, like clobber, that delete the whole "out" directory, and follow windows symbolic links in the out/[build]/packages directory to delete the lib directories of the packages in their original location.

The unittest package is different from the others, in that it is not a git checkout, but an untarred download from cloud storage.  So it does not detect that it has changed, since its checked out hash still agrees with the hash of the tar file it downloaded.

So future runs in this checkout are missing the unittest package.

To fix this problem once it occurs, we can remove the tar file third_party/pkg/unittest.tar.gz, so it is re-downloaded and extracted.  The problem can be avoided by finding the code that removes "out", and
ensuring it does not follow links on windows, or by removing the whole "packages" directory, replacing it with a .packages file.  This is a high priority, so this is what we will rely on to fix the problem.

@johnmccutchan

**Comment by johnmccutchan** [comment]
@fsc8000 FYI

**Comment by whesse** [comment]
This problem should have been fixed, by replacing the package root with the .packages file.  There are no longer any symbolic links to the third_party/pkg/unittest directory, so no way to delete it by accident.

The error will still occur if someone deletes the unittest directory, or files within it, but that should be a very rare occurence.
