### ISSUE TITLE
Documentation for Expression class in analyzer package is wrong

### ISSUE THREAD

**Issue by ddrone** [dart-lang/sdk#26760]
Here's a class in question: https://www.dartdocs.org/documentation/analyzer/0.27.3/analyzer.dart.ast.ast/Expression-class.html

Its documentation provides following grammar fragment:

> expression ::=
> 
>    [AssignmentExpression]
>  | [ConditionalExpression] cascadeSection*
>  | [ThrowExpression

Which is clearly wrong as it doesn't cover whole lot of other expressions available (like binary expressions or string literals)

**Comment by bwilkerson** [comment]
The language spec defines:

```
expression:
    assignableExpression assignmentOperator expression |
    conditionalExpression cascadeSection* |
    throwExpression
;
```

The comment defines the syntax consistent with the spec.

**Comment by lrhn** [comment]
The reason that the grammar is sufficient is that `conditionalExpression` covers more than just the conditional expression - it allows the conditional expression, but also has a fallback to any of the lower precedence operators if they are not followed by a `?`.
