### ISSUE TITLE
AOT: range analysis and type propagation should cooperate to convert CheckedSmiOp into unchecked variants

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#26761]
When I AOT compile 

``` dart
void loop() {
  final arr = [1, 2, 3, 4];
  var sum = 0;
  for (var i = 0; i < arr.length; i++) {
    sum += arr[i];
  }
  return sum;
}
```

I expect it to use unchecked smi operations for `i` - however it does not. Even though it knows that `arr.length` always returns a smi.

We need to extend our range analysis to handle this sort of code or at least handle certain patterns.

**Comment by fsc8000** [comment]
This case should be covered by speculatively inlining the smi-ops. I'll investigate...

**Comment by mraleph** [comment]
Well, we do inline smi-ops speculatively, but `CheckedSmiOp` does not participate in range analysis so we don't know that they all can be turned into unchecked `BinarySmiOp` operations.

**Comment by fsc8000** [comment]
Yes, we should be able to make the < operation a pure smi-op. the compile type of the < comparison is known smi. The result type of array load arr[i] is not known statically, therefore sum += arr[i] can't be a BinarySmiOp.

**Comment by mraleph** [comment]
@fsc8000 I am talking about `i`, `sum` is entirely different matter of course.

**Comment by fsc8000** [comment]
Partially fixed by my CL: The examle now uses only unchecked smi ops for ```i```.

However, for operations that can deoptimize (e.g. overflow) we need to use range information to be able to specialize them.

**Comment by fsc8000** [comment]
Closing this for now since the example now works as expected.

**Comment by mraleph** [comment]
I just checked and for `i++` we still emit so the issue is still present: 

```
        ;; ParallelMove rax <- C, rcx <- S+1
0x7fe090deee2c    488b4de0               movq rcx,[rbp-0x20]
0x7fe090deee30    48c7c002000000         movq rax,2
        ;; v25 <- CheckedSmiOp:14(+, v14, v7)
0x7fe090deee37    f6c101                 testb rcx,1
0x7fe090deee3a    0f85d0000000           jnz 0x7fe090deef10
0x7fe090deee40    4889ca                 movq rdx,rcx
0x7fe090deee43    4803d0                 addq rdx,rax
0x7fe090deee46    0f80c4000000           jo 0x7fe090deef10
```

**Comment by mraleph** [comment]
I lost my original reproduction, but here is another variant:

```dart
void loop(arr) {
  // final arr = [1, 2, 3, 4];
  var sum = 0;
  for (var i = 0; i < arr.length; i++) {
    sum += arr[i];
  }
  return sum;
}

main() {
  loop([1, 2, 3, 4]);
}
```

Here we end up producing code that quite bad. 

Basically it does work for small variants, but if anything disables speculative inlining then you end up with `CheckedSmiOp` instead of `BinarySmiOp`.

We have to approaches - either change the way we do speculative inlining or decouple that and smi-optimizations.

**Comment by alexmarkov** [comment]
`CheckedSmiOp` instruction was removed from the compiler. AOT compiler now uses `BinaryInt64Op` instructions in the examples above.
