### ISSUE TITLE
Poor (or no at all) hierarchy info for classes/methods from the SDK and 3rd party packages

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26762]
The problem is with search_getTypeHierarchy() method. Analysis Server doesn't return information about subclasses of a specific class until you open those subclasses in the editor. I know that analyzer parses all the files lazily, so I prepared the following single-file project and opened the file in the editor:

```
import 'dart:collection';
import 'dart:typed_data';
import 'dart:html';

Iterable a;
List b;
Uint16List c;
TouchList d;
ListBase e;
```

Analysis is complete, so analyzer knows about all referenced classes.
If I ask for superclasses of ListBase I get correct information:
![image](https://cloud.githubusercontent.com/assets/4499789/16312898/7f9c514c-397f-11e6-8e5c-0a4ba77dd709.png)

It proves that Analysis Server at this point knows that ListBase is a subclass of Iterable. But if I ask for subclasses of Iterable I get absolutely nothing:
![image](https://cloud.githubusercontent.com/assets/4499789/16312901/847bbb08-397f-11e6-9c5e-f9addfc38a67.png)

If I open Iterable in the editor (thus letting analyzer smell it and some other files), Analysis Server starts giving some subclasses information:
![image](https://cloud.githubusercontent.com/assets/4499789/16312908/89209ea8-397f-11e6-8d51-6fc12f185d43.png)

The more SDK classes I open in the editor the more complete is class hierarchy.
But I expect that analyzer knows class hierarchy from the very beginning because these classes are used in my code and therefore known to analyzer.

**Comment by alexander-doroshko** [comment]
From conversation with @scheglov:
>   Analysis Server can index only fully resolved units.
  But when we use List, we don't need the fully resolved Iterator class, we need just its partially resolved element.
  Of course even these partially resolved elements have enough information to index type hierarchies.
  It just should be implemented.

> Even worse in case of using SDK summaries.   Because when we serve SDK element models from its summary we don't have resolved ASTs at all.
  So, there is nothing to index.
  It also can be solved.
  When we create SDK summary we also create its index files.
  And index implementation can (already) consume multiple index files - e.g. for SDK, packages and local projects.
  But again, this is something to finish implementing - add these index files to SDK and consume them.

**Comment by scheglov** [comment]
WIP https://dart-review.googlesource.com/c/sdk/+/57760

**Comment by scheglov** [comment]
[This CL](https://dart-review.googlesource.com/c/sdk/+/58041) enables discovery for all SDK libraries, so when something is being searched, and we see a name reference in an SDK library, we analyze and index this library. So, this enables type hierarchies for SDK types, and search for references.

**Comment by scheglov** [comment]
This is fixed now.
We show all classes that we able to find in SDK and packages.
The first search / hierarchy it will take some time to index all files and resolve interesting ones.
But subsequent requests in the same analysis server session, or after restart, are fast.

![image](https://user-images.githubusercontent.com/384794/41172476-d591aeaa-6b08-11e8-8c70-c05ceb86de8f.png)

**Comment by alexander-doroshko** [comment]
Awesome! Thanks a lot!
