### ISSUE TITLE
Feature request: sorted imports

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26764]
_From @DaveShuckerow on May 12, 2016 20:17_

When I add an import by pressing alt-enter on an unknown name, is it possible to place it in the import list alphabetically instead of at the end of the list?

_Copied from original issue: dart-atom/dartlang#985_

**Comment by bwilkerson** [comment]
What server protocol does alt-enter end up using that would need to change in order to implement this request?

**Comment by devoncarew** [comment]
I believe this is a quick fix? Let me verify.

**Comment by devoncarew** [comment]
Yup, the import library quick fix for unrecognized symbols.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Step 1.
https://codereview.chromium.org/2138843002

**Comment by scheglov** [comment]
Step 2.
https://codereview.chromium.org/2143023002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/bf731dfcd5eb1b7623cda68a75b5f9ddb4bcc20e
