### ISSUE TITLE
Dart specification of initialization of instance variables is insufficient and doesn't match implementations.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26765]
The specification specifies everything about instance variables with initializers in a single paragraph.
That paragraph has several problems:
- it doesn't specify the order variable initializer expressions are evaluated in,
- it requires all variable initializer expressions on the object to be executed before executing the constructors, including superclass fields. All implementations initialize instance variables only for the current class, and then handle the superclass variables when calling the super constructor.
- it specifies that all initializer expressions are evaluated in a scope that only applies to the initialiers of the actual class, not those of superclasses.
- it doesn't specify that instance variables without initializer expressions are initialized to `null`.

The specification should be made to match the actual implementations. It should specify which order instance variable initializer expressions are evaluated in (or state that it's unspecified, but existing code might depend on the actual order). It should ensure that all instance variables are initialized.

**Comment by eernstg** [comment]
I believe this issue has been addressed in 843bb96813. Closing; @lrhn, please reopen if needed.
