### ISSUE TITLE
Warn when creating a list of shared containers

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26776]
It would be nice, if users get a warning when they write something like:
`new List.filled(5, [])` or `new List.filled(499, {})`.

It's very likely, that users actually wanted to use `new List.generate(5, (_) => [])` instead.

**Comment by srawlins** [comment]
`List.filled(5, [])` (creating a list of size 5, where each element is an empty list) is fine. I don't think either of these constructors is used too much, and you'd find out pretty quick if you used the wrong one. I'm closing this as not high value.
