### ISSUE TITLE
Fix anomaly in subtyping

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26779]
Assume `class DynList extends List<dynamic> { .. }`. We would presumably expect the subtype relation `DynList <: List<int>` to hold. However, the spec (looking at the one marked 'Aug 19, 2015') does not justify that conclusion:
1. `DynList <: List<int>`, because (per def. of `<:`, p141) of 2.
2. `DynList << List<int>`, because of 3 and 4 and bullet 10 (transitivity).
3. `DynList << List<dynamic>`, because of bullet 4 (direct supertype).
4. `List<dynamic> << List<int>`, because of 5 and bullet 7 (generic covariance).
5. `dynamic << int`.

But the proof obligation `dynamic << int` cannot be fulfilled, because `dynamic` does not get substituted by `\bottom` anywhere else than in the definition of `<:`. It does not help if we try to show `DynList <: List<int>` via `DynList <: List<dynamic>` and `List<dynamic> <: List<int>` (both of which are provable), because `<:` is not transitive.

So in order to get the desired subtyping relationship we'd need to make the adjustment that the "direct supertype" case performs the substitution of `\bottom` for `dynamic`. In order to do that we will of course need to check that this does not have any unintended consequences.

(Thanks to Fabio Strocco and Anders Møller for noting that there was an anomaly in this area).

**Comment by eernstg** [comment]
Status for tools with respect to this issue:

The tools in standard mode do apply the proposed update already: `dart --checked`, `dart2js --checked` plus `d8 out.js`, and `dartanalyzer` accept code relying on the proposed subtype relation without static type warnings (so it's an upcast/downcast and not a "sidecast"). Here's the code:

```dart
class C<X> {}
class D extends C<dynamic> {}

main() {
  D d = new D();
  C<int> cInt = d; // Spec says not sub- nor supertype, tools say OK (upcast).
  d = cInt; // Same situation (downcast).
}
```

Strong mode is probably not affected by this adjustment. `dartanalyzer --strong` emits an `Unsound implicit cast` warning at both commented lines above. In the documentation of strong mode at https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md#generics it is explicitly stated that `MyList` is not a subtype of `List<int>` which in this context corresponds directly to "`DynList` is not a subtype of `List<int>`", and "`D` is not a subtype of `C<int>`", which causes the warnings for assignments in both directions. It is a consequence of the fact that `dynamic` corresponds to `\top` and not to `\bottom` in strong mode generics. It seems likely that the proposed change has no impact on strong mode, because the "missing" substitution of `\bottom` for `dynamic` never occurs anyway.

**Comment by leafpetersen** [comment]
See also #22033

**Comment by eernstg** [comment]
The reasoning behind this issue was applicable to Dart 1, but since `dynamic` is a top type in Dart 2 it is now irrelevant. Closing.
