### ISSUE TITLE
dartanalyzer not giving me a warning when I have a bogus @override

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#26787]
Example:
```dart
abstract class A {}

class B extends A {
  @override     // <-- Override what?  This should be a dartanalyzer warning.
  final int x;

  B(this.x);
}

void main() {
  new B(1);
}
```

```
> dartanalyzer --strong foo.dart
Analyzing [foo.dart]...
No issues found
```
Grr...  Example of where such a warning would have helped:
https://github.com/google/charted/blob/master/lib/charts/themes/quantum_theme.dart#L133

**Comment by bwilkerson** [comment]
We seem to catch this for methods, but not for implicit getters / setters.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2182773002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/7808f167ec32d5cbf9be129724180c391802a9f3
