### ISSUE TITLE
flag to disable implicit dynamic in generic type annotations

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26784]
no-implicit-dynamic still allows things like:

``` dart
class C<T> { T t; C(this.t); }
void main() {
  C c = new C(42);
  c.t.oops();
}
```

If we require that to be written as `C<dynamic>` it makes the dynamic dispatch a bit more obvious. I think what we'd want to do here is interpret `C` as `C<Object>`, that way the simple syntax can still be used, but it becomes safer statically if someone is using this flag.

Context https://github.com/dart-lang/sdk/issues/25573#issuecomment-228823689

**Comment by jmesserly** [comment]
CC @leafpetersen @munificent  -- I left this one lower priority as I'm not sure if we have a current need for it.

**Comment by leafpetersen** [comment]
Agreed, probably lower priority in my mind.

**Comment by jmesserly** [comment]
@zoechi just hit this as well, so I bumped the priority

**Comment by srawlins** [comment]
`no-implicit-dynamic` now produces an error on the code in the description:

```none
$ cat 26784.dart 
class C<T> { T t; C(this.t); }
void main() {
  C c = new C(42);
  c.t.oops();
}
$ dartanalyzer --no-implicit-dynamic 26784.dart 
Analyzing 26784.dart...
  error • Missing type arguments for generic type 'C<dynamic>' at 26784.dart:3:13 • strong_mode_implicit_dynamic_type
1 error found.
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
```
