### ISSUE TITLE
Build summaries for Flutter SDK and core packages

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26798]
This is a prerequisite for issue #26797.

**Comment by scheglov** [comment]
We [build Flutter SDK summaries](https://github.com/flutter/flutter/commit/d3fd8ddd6f041a2ec96bda2c4904ad8b6836868b), [unlinked Flutter package summaries](https://github.com/flutter/flutter/commit/0774a6748e0d1829512d551e375eb46940d3c35f), and we build and use unlinked and linked summaries [for pub](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/summary/pub_summary.dart).
