### ISSUE TITLE
Remove type propagation of top level variables and static fields from analyzer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26794]
This is a prerequisite for issue #26793.

**Comment by stereotype441** [comment]
After discussion with @bwilkerson, it's become clear that:

- This task does not strictly block #26793.  We can safely enable AST-based summaries by default now, because no consumers of summaries currently make use of propagated types.  We may instead consider this task to block #26791 and #26799.
- It is not necessary to remove propagated types completely from analyzer; it is sufficient to remove type propagation of top level variables and static fields, since the other uses of propagated types are confined to block function bodies, and hence do not affect any of the analysis that we do using summaries.

I will change the bug summary accordingly.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2288223003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/09b851c97f5c3672001b85c4267bb1a82c855cfc
