### ISSUE TITLE
Crash in compiler when compiling leap.dart (flaky)

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26803]
A crash on the buildbot, that only occurred once, showed the compiler crashing:

../../out/ReleaseIA32/dart-sdk/lib/async/future.dart:764:1:
Internal Error: The compiler crashed when compiling this element.
Object _nonNullError(Object error) =>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (1.18.0-edge.17e0b56025bdc6e03e56dabd4f0efd1b37cc279b), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Bad state: no elements
#0      Link.head (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/util/link.dart:8)
#1      OrderedTypeSet.forEach (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/ordered_typeset.dart:98)
#2      Types.computeLeastUpperBoundInterfaces.getSupertypesAtDepth (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/dart_types.dart:1580)
#3      Types.computeLeastUpperBoundInterfaces (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/dart_types.dart:1590)
#4      Types.computeLeastUpperBound (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/dart_types.dart:1713)
#5      TypeCheckerVisitor.visitConditional (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:1834)
#6      Conditional.accept (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/tree/nodes.dart:951)
#7      TypeCheckerVisitor.analyze (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:441)
#8      TypeCheckerVisitor.visitReturn (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:1709)
#9      Return.accept (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/tree/nodes.dart:1511)
#10     TypeCheckerVisitor.analyze (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:441)
#11     TypeCheckerVisitor.visitFunctionExpression (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:666)
#12     FunctionExpression.accept (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/tree/nodes.dart:1111)
#13     TypeCheckerTask.check.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:68)
#14     CompilerTask.measure (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:58)
#15     TypeCheckerTask.check.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:62)
#16     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1563)
#17     TypeCheckerTask.check (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/typechecker.dart:61)
#18     _CompilerResolution.computeWorldImpact.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:2020)
#19     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#20     _CompilerResolution.computeWorldImpact (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:2001)
#21     Compiler.analyzeElement.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1053)
#22     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#23     Compiler.analyzeElement (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1040)
#24     Compiler.analyze.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1075)
#25     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#26     Compiler.analyze (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1057)
#27     ResolutionWorkItem.run (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/resolution.dart:43)
#28     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:961)
#29     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#30     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:960)
#31     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#32     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:957)
#33     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1563)
#34     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:955)
#35     QueueFilter.processWorkItem (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/enqueue.dart:954)
#36     Enqueuer.forEach (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/enqueue.dart:645)
#37     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:954)
#38     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#39     Compiler.emptyQueue (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:953)
#40     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:990)
#41     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#42     Compiler.processQueue (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:967)
#43     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:841)
#44     CompilerTask.measureSubtask (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:171)
#45     Compiler.compileLoadedLibraries (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:797)
#46     Compiler.runInternal.<anonymous closure> (file:///b/build/slave/dart2js-linux-drt-2-2-be/build/sdk/pkg/compiler/lib/src/compiler.dart:707)
#47     _RootZone.runUnary (dart:async/zone.dart:1204)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#49     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#50     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#51     _Future._completeWithValue (dart:async/future_impl.dart:477)
#52     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

make: *** [out/ReleaseIA32/obj/gen/leap.dart.js] Error 253

**Comment by fsc8000** [comment]
I tried reproducing this again by compiling leap.dart in a loop for a while to check if this could be a VM issue, but it seems not reproducible anymore, and I have not seen it occur on the buildbot again either.
