### ISSUE TITLE
Modify IntelliJ handling of line endings to work with summaries

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26800]
This is a prerequisite for issue #26799.

**Comment by devoncarew** [comment]
@jwren, my understanding is that we only encounter the IntelliJ / line-ending issue on windows - that it reports file offsets as if the file didn't have carriage returns on that platform. Is there an issue to enable the use of summaries w/ IntelliJ on non-windows platforms? It seems like that would be a good way to turn things on incrementally.

**Comment by jwren** [comment]
@devoncarew CR+LF can be encountered on other types of machines.  The point that I made was that right now the only summaries that we have support for is for the Dart SDK, which has no instances of CR+LF, meaning for any machine (windows or otherwise), it wouldn't be an issue to turn summaries on.

**Comment by alexander-doroshko** [comment]
Windows version of Dart SDK does have CR+LF :)

**Comment by alexander-doroshko** [comment]
Also there's no guarantee that user project files or 3rd party packages on Mac/Linux have only native line breaks. Even though there are no summaries for these files Analysis Server doesn't have an option to normalize EOLs for non-SDK files only.

**Comment by alexander-doroshko** [comment]
Line endings handling at IntelliJ IDEA side is done. Since version 2016.3 JetBrains IDEs will work fine with summaries. Public EAPs will start in August, for now it is possible to run IntelliJ IDEA Community Edition + Dart plugin from sources.

**Comment by bwilkerson** [comment]
Thank you!
