### ISSUE TITLE
HOT RELOAD: Teach test.py how to run tests under a reload stress test

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26809]
**tools/test.py:**
- [x] Add a new mode to test.py `--hot-reload`

**bots:**
- [ ] Get a Linux Debug and Linux Release bot running with `--hot-reload`

**reload test failures**
Test failures under lib/ (ignoring [mirrors](https://github.com/dart-lang/sdk/issues/26836)):

- `python tools/test.py --hot-reload -t120 lib/async/stream_transformation_broadcast_test`
- `python tools/test.py --hot-reload -t120 lib/async/stream_transformer_test`
- `python tools/test.py --hot-reload -t120 lib/convert/utf85_test`

Many test failures are caused by this [assert failure](https://github.com/dart-lang/sdk/issues/26837)

**vm_reload:**
- [X] Run with --identity-reload and --reload-every=N
- [X] Determine a sane value of N
- [X] How can we scale N based on the complexity of the test? start reloading early and geometrically back off after each reload.

**VM:**
- [ ] Add a --shallow-reload flag which doesn't actually do the I/O for the scripts. Ryan thinks this could make a big performance improvement in reload time for the bots.

**Comment by rmacnak-google** [comment]
Some thoughts on scaling:
 - We might have the gaps between reloads grow geometrically so short tests hit at least one reload and long tests aren't swamped.
 - We might let other events in the system trigger a reload: setup a reload to occur a few stack checks after a GC or deopt, or after every N compilations.

**Comment by johnmccutchan** [comment]
Related CLs:

https://codereview.chromium.org/2114083002/
https://codereview.chromium.org/2118923002/

**Comment by johnmccutchan** [comment]
Test failures under lib/ (ignoring [mirrors](https://github.com/dart-lang/sdk/issues/26836)):

- `python tools/test.py --hot-reload -t120 lib/async/stream_transformation_broadcast_test`
- `python tools/test.py --hot-reload -t120 lib/async/stream_transformer_test`
- `python tools/test.py --hot-reload -t120 lib/convert/utf85_test`

**Comment by johnmccutchan** [comment]
Closing this issue because we have a separate issue around bringing the bots online.
