### ISSUE TITLE
HOT RELOAD: Optimizing reload

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26807]
Both the reload code and the become are already annotated with timeline blocks. We can revise the current timeline blocks over time).

- [ ] Establish baseline times for reloading dart2js while compiling X
- [ ] Figure out what X is (probably something smallish so that the dart2js run doesn't take too long)
- [ ] Make debug and release reload as quickly as possible

How to run dart2js:

In your top level `sdk/` run the following once:

`$ ln -s sdk/lib/ lib`

In `pkg/compiler` run the following:
`$ gdb --args ../../out/ReleaseX64/dart --timeline-dir=. --reload-every=500000 bin/dart2js.dart --categories=all path/to/entry.dart`

**Comment by rmacnak-google** [comment]
VerifyMaps is quite slow and has quadratic complexity.

**Comment by johnmccutchan** [comment]
I think this is mostly done.
