### ISSUE TITLE
AnnotationElementImpl has no associated AST

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26811]
I found the following message in my log files.

2016-06-27 10:53:58,490 [1126923]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.18.0-edge.9445281b0c18dcd766e0e2e2d06b6519357cc47f, server version 1.15.0, FATAL error: Failed to handle request: {clientRequestTime: 1467050033088, params: {file: /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/lib/src/generated/sdk.dart, offset: 5410}, method: edit.getFixes, id: 22}
AnalysisException: Cannot compute RESOLVED_UNIT for /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/lib/src/generated/sdk.dart in /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/lib/src/generated/sdk.dart
Caused by Unexpected exception while performing ComputeConstantDependenciesTask for element @null in source /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/lib/src/generated/sdk.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:697)
#5      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1316)
#6      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:743)
#7      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:34)
#8      AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:738)
#9      EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:157)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _rootRun (dart:async/zone.dart:946)
#12     _CustomZone.run (dart:async/zone.dart:826)
#13     _CustomZone.runGuarded (dart:async/zone.dart:724)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#15     _rootRun (dart:async/zone.dart:950)
#16     _CustomZone.run (dart:async/zone.dart:826)
#17     _CustomZone.runGuarded (dart:async/zone.dart:724)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by The null object does not have a getter 'arguments'.

NoSuchMethodError: method not found: 'arguments'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:350)
#3      ComputeConstantDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:1937)
#4      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#5      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#6      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#7      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#8      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:697)
#9      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1316)
#10     AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:743)
#11     runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:34)
#12     AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:738)
#13     EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:157)
#14     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#15     _rootRun (dart:async/zone.dart:946)
#16     _CustomZone.run (dart:async/zone.dart:826)
#17     _CustomZone.runGuarded (dart:async/zone.dart:724)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#19     _rootRun (dart:async/zone.dart:950)
#20     _CustomZone.run (dart:async/zone.dart:826)
#21     _CustomZone.runGuarded (dart:async/zone.dart:724)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:702)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1316)
#2      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:743)
#3      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:34)
#4      AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:738)
#5      EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:157)
#6      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#7      _rootRun (dart:async/zone.dart:946)
#8      _CustomZone.run (dart:async/zone.dart:826)
#9      _CustomZone.runGuarded (dart:async/zone.dart:724)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#11     _rootRun (dart:async/zone.dart:950)
#12     _CustomZone.run (dart:async/zone.dart:826)
#13     _CustomZone.runGuarded (dart:async/zone.dart:724)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by srawlins** [comment]
Closing as stale. Please re-open if you encounter this again.
