### ISSUE TITLE
Flaky: web_socket test fails somtimes on simarm/dbc/dbc64 debug checked

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26814]
standalone/io/web_socket_test is failing about half the time (in the --short-socket-read and --short-socket-write versions) on simarm debug checked on linux.  Putting a flaky marker in the status file standalone.status.

The error is:
stderr:
Unhandled exception:
Expect.equals(expected: <1005>, actual: <null>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      SecurityConfiguration.checkCloseStatus (file:///mnt/data/b/build/slave/vm-linux-debug-simarm-be/build/sdk/tests/standalone/io/web_socket_test.dart:57:12)
#3      SecurityConfiguration.testRequestResponseClientCloses.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-simarm-be/build/sdk/tests/standalone/io/web_socket_test.dart:101:17)

**Comment by kasperl** [comment]
Also happens on simdbc64. Widening flaky marker in https://github.com/dart-lang/sdk/commit/3ecfa623855791e610e8c6ff89ef3c40495ad8b8.

**Comment by sjindel-google** [comment]
DBC is obsolete.
