### ISSUE TITLE
Run analyzer tests on dart2js only on a special bot

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26813]
The analyzer tests that are too slow are being skipped or marked slow on all the dart2js bots.
If there is value in compiling the analyzer and all its tests with dart2js, and then running them in d8, jsshell, and browsers, we should do that on a special bot, with builder tag dart2js_analyzer.

Changing the status file so the slow analyzer tests only run on that special bot.

**Comment by athomas** [comment]
Looks like this was completed but not closed.
