### ISSUE TITLE
Equivalent "throws" keyword in dart ?

### ISSUE THREAD

**Issue by Songbird0** [dart-lang/sdk#26816]
Hi, there !

**Note**:
In fact, isn't really a technical problem, just a question.

----

When I write a method like this in java:
```java
public void greetings(final String message) throws Exception
{
     if(!message == null && !message.equals(""))
     {
        //do something
     }
     else
         throw new Exception("An error was occurred");
}
```
The exception throwing are 'dispatched'.
But this syntax isn't allowed in Dart, so what is equivalent of the throws keyword in Dart ?

Thanks for advance !

**Comment by floitschG** [comment]
Dart does not support checked exceptions.
We recommend documenting the thrown exceptions in the function's dartdoc.

Note, that many believe that Java made a mistake in introducing checked exceptions. If you have time, google for "checked exceptions mistake". There are lots of interesting articles.

**Comment by Songbird0** [comment]
Ok, thanks !
