### ISSUE TITLE
Using .call on a known function type should not be a dynamic call

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26812]
This code:

```dart
void f(int x) => print(x);
void main() {
  f.call("hello");
}
```

gets no errors or warnings in strong mode.  Since we know the type of `f`, which should treat this as a regular call, and issue an error.

**Comment by jmesserly** [comment]
P1 because I think this is blocking someone?

**Comment by jmesserly** [comment]
Marking P2 ... Leaf has a workaround from the DDC side :)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2226903003
