### ISSUE TITLE
HtmlElement.style.setProperty don't work for CSS variables

### ISSUE THREAD

**Issue by Milek7** [dart-lang/sdk#26819]
Following code don't do anything:
`document.body.style.setProperty("--somevar", "100px");`
Same code executed in JavaScript correctly sets CSS variable (visible in element inspector)

**Comment by zoechi** [comment]
What behavior do you expect?
What browser did you test?
Can you provide a repository with a minimal example that demonstrates what you tried to accomplish and allows to reproduce?

**Comment by Milek7** [comment]
Tested in Chromium and Firefox.
Example: https://github.com/Milek7/dartsdk-26819
First row should have green background set by Dart.
Second row have green background set by javascript eval called by context.callMethod.

**Comment by zoechi** [comment]
Packed it in a [**DartPad**](https://dartpad.dartlang.org/0f57b34b9323724e5f7108c700c6303c)

**Comment by leonsenft** [comment]
Any update on this? Just ran into this issue.

It seems like all properties are validated in some way before being set. For example, 

```dart
document.body.style.setProperty('color', '12px')
```

doesn't work, but

```dart
document.body.style.setProperty('color', 'red')
```

does.

I'm guessing support for CSS variables was never considered and as a result they're treated as invalid properties and not applied? Are there any compelling reasons to actually drop properties like this? Why can't we just honor whatever the user wants to set?

**Comment by zacharydenton** [comment]
The issue here seems to lie with the _browserPropertyName function in the dart:html CssStyleDeclaration.setProperty definition. Given a property like --custom-property, it will return -webkit---custom-property (depending on the browser), which the browser then rejects as an invalid style (similar to how the browser rejects color: 12px in @leonsenft's example).

**Comment by alan-knight** [comment]
So, without really understanding CSS variables, it seems like there's not a way to check if they're defined, so it would be more appropriate if the setProperty did not just assume that if we don't have property x, we must mean browserPrefix-x and also checked the prefixed version. That is, something like

```
    if (_supportsProperty(_camelCase(propertyName))) {
      name = propertyName;
    } else if _supportsProperty(Device.cssPrefix + propertyName) { // Also needs camelcasing? Also don't recompute.
      name = Device.cssPrefix + propertyName;
    } else {
      // We don't know what it is, just pass it through, and don't try to case normalize it.
      name = propertyName;
   }
```

Does that make sense?

**Comment by leonsenft** [comment]
Setting a variable via `setProperty` *is* defining it, so we definitely don't want to check if it's declared already: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by alan-knight** [comment]
https://codereview.chromium.org/2976213002

**Comment by leonsenft** [comment]
It seems like this has been fixed (at least in the latest version of DartPad)! Thanks.
