### ISSUE TITLE
Create missing override should not add `void` return type on setters

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26821]
```dart
abstract class ConverterServiceConsumer {
  set converterService(ConverterService service);
}
```
execute quick fix on
```dart
class MockToDatastoreConverter extends conn.ToDatastoreConverter implements ConverterServiceConsumer {}
```
results in

```dart
class MockToDatastoreConverter extends conn.ToDatastoreConverter implements ConverterServiceConsumer {
  @override
  void set converterService(ConverterService service) {
    // TODO: implement converterService
  }
}
```
then I get
> avoid return type on setters

because of

```yaml
linter:
  rules:
    - avoid_return_types_on_setters
```

**Comment by bwilkerson** [comment]
Unless, of course, you've enabled the lint that requires types everywhere.

@scheglov

**Comment by zoechi** [comment]
I think it shouldn't, even with "return types everywhere".
The return type on setters doesn't fulfill any purpose. It can't be anything but `void` anyway. Using the return value from a setter should be (or already is) a warning.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2123333002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/dc425004085a4bd4706528a593649f02c37bd921

**Comment by lrhn** [comment]
Just for the record: It's not a warning to use the return value of a setter, because it's impossible. The value of an assignment expression is the value being assigned, any value returned by a setter is silently ignored.
