### ISSUE TITLE
Checked mode doesn't work on Mac

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/sdk#26827]
I run dartium from terminal with --checked flag, it has that flag in version page, in command line section:
> /usr/local/Cellar/dart/1.17.1/Chromium.app/Contents/MacOS/Chromium --checked --no-sandbox --enable-avfoundation --flag-switches-begin --flag-switches-end

But seems checked mode is not working. I don't see any warnings or exceptions. But my colleague see type annotation exceptions.

What do I wrong, how to check situation to browser or my mistake?

**Comment by mraleph** [comment]
You should use `DART_FLAGS` environment variable to activate checked mode as described [here](https://www.dartlang.org/tools/dartium/)

```
DART_FLAGS='--checked'              \
  path/Chromium.app/Contents/MacOS/Chromium
```

**Comment by kelegorm** [comment]
Ok, I just don't understand what to do with that "text". I'm not guru on unix system. [Here](https://www.dartlang.org/tools/dartium/) it was described as command-line flags and no one word about environment variables. May be you may consider make it more clear in docs. Or just screw off stupid guys like me.

**Comment by kelegorm** [comment]
Ok, I got it. Need to add to file ~/.bash_profiles one line:
> export DART_FLAGS="--checked"
Use double quotes there, not single.

and then run from terminal dartium as you usual do. I run it with 'dartium' command.

It won't work until you restart your terminal to get updated 'bash_profiles'. And no need to call whole app name, you may have it linked with word 'dartium' if you have installed it with brew.

**Comment by mraleph** [comment]
@kelegorm you just paste it in your terminal (replacing `path/Chromium.app/Contents/MacOS/Chromium` with `/usr/local/Cellar/dart/1.17.1/Chromium.app/Contents/MacOS/Chromium`):

```
$ DART_FLAGS='--checked' /usr/local/Cellar/dart/1.17.1/Chromium.app/Contents/MacOS/Chromium
```

`--checked` is not a Chromium flag, so you can't just pass it to `Chromium` binary directly. I agree that documentation might be a bit unclear about the distinction - but the command line provided there works.

**Comment by kelegorm** [comment]
ok, got it about why flag doesn't work, thank you.
