### ISSUE TITLE
Package tests fail on windows with incorrect path expectation

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26828]
8 package tests are failing on Windows with errors like:

FAIL: AbstractContextManagerTest | test_setRoots_addFolderWithPackagespec
  Expected: '/home/somebody/.pub/cache/unittest-0.9.9/lib/unittest.dart'
    Actual: 'E:\\b\\build\\slave\\pkg-win-be\\build\\sdk\\home\\somebody\\.pub\\cache\\unittest-0.9.9\\lib\\unittest.dart'
     Which: is different.

The main bug for this is filed on the pub repo: https://github.com/dart-lang/pub/issues/1429
Status files are suppressing these failures:  pkg/pkg.status.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2142143002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/94a41e0d2e64de6241edc686240928f95d2b1da6

**Comment by whesse** [comment]
Please update the status for this test that now passes.  The first comment on the bug says which status files need to be updated when the bug is fixed.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/94a41e0d2e64de6241edc686240928f95d2b1da6
https://github.com/dart-lang/sdk/commit/139c7e21e22ca0eb77aa3fd13c010f66ce2337fe
https://github.com/dart-lang/sdk/commit/454f9edddd5e73ae0f8abf25ade83c363a9509ba

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/0e855cbf53f97c46563bd87f6cc200d97204fc9d

**Comment by scheglov** [comment]
See also https://dart-review.googlesource.com/c/sdk/+/7843
