### ISSUE TITLE
Annotation shown as not executed in coverage report

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26826]
![image](https://cloud.githubusercontent.com/assets/405837/16567607/fd167e46-4220-11e6-9dae-16c926633168.png)

I think the line with `@override` should not be reported as `not executed`
I'm not sure about other annotations.

**Comment by floitschG** [comment]
Tentatively assigning to analyzer.
If it's a coverage issue, please reassign.

**Comment by bwilkerson** [comment]
It is not an analyzer issue; not sure which area covers the coverage tool issues.

**Comment by kevmoo** [comment]
First would be to check if the service protocol (observatory) is reporting the correct lines here.

@johnmccutchan ?

**Comment by johnmccutchan** [comment]
@turnidge
