### ISSUE TITLE
pub global activate shows wrong error message about pub-cach/bin in PATH

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#26829]
After making a package globally available I get this error message:

```bash
Warning: Pub installs executables into ~/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"~/.pub-cache/bin"
```
I don't know why pub thinks it is not on my path????
Everything works as expected but this message is a bit annoying.
 
![screenshot-1607063](https://cloud.githubusercontent.com/assets/116654/16612341/c6c1f54a-4366-11e6-9522-0c315e7c0bb6.jpg)

- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64"
Pub 1.17.1

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1430

**Comment by 4gmayank** [comment]
`echo 'export PATH=/usr/local/bin:$PATH' >>~/.bash_profile`
Then restart the application and terminal for refresh

**Comment by Akshath1727** [comment]
even i got the same error.... it got resolved after adding 

**export PATH="$PATH":"~/.pub-cache/bin"**
line to .bashrc file and restarting the pc
