### ISSUE TITLE
Error from analysis_getNavigation() - IntelliJ / Dart Analysis-Server fails AGAIN!!! 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#26831]
After a few weeks of programming for Android I am back on my Dart-project and what happens... I'm stuck because Analysis-Server is not able to analyze my project anymore. (I upgraded to El Captain and Dart 1.17.1) 

Here is what IntelliJ-log shows: `2016-07-06 13:01:34,523 [ 207751]   INFO - yzer.DartAnalysisServerService - Error from analysis_getNavigation(), file = /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/lib/mdl.dart, SDK version = 1.17.1, server version = 1.15.0, error code = GET_NAVIGATION_INVALID_FILE: Error during `analysis.getNavigation`: invalid file.` 

This is crap! 
dartanalyzer on the commandline:
```bash
$ dartanalyzer lib/mdl.dart
Analyzing [lib/mdl.dart]...
No issues found
> MaterialDesignLite $ pwd
/Volumes/Daten/DevLocal/DevDart/MaterialDesignLite
```

It's so incredibly annoying!!! Over and over just problems with Analysis server. If my Dart codebase would not be so large I would switch to JS/TS immediately. 

**No analysis, not code completion, nothing  - an IDE that works like Notepad. GREAT.**

-----
IntelliJ IDEA 2016.2
Build #IU-162.1121.10, built on July 5, 2016
Licensed to Mike Mitterer
You have perpetual fallback license for this version
Subscription is active until December 3, 2017
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64"
Pub 1.17.1

**Comment by alexander-doroshko** [comment]
@MikeMitterer Is this the only suspicious line in idea.log? Please attach full log, it may give us more info.

Also, I guess Analysis Server team would benefit from having special logs from the server. To get logs please do the following:
- In the IDE open Help | Find Action, type "registry", open Registry
- In the Registry type "dart", find "dart.server.additional arguments" property, set its value to `--instrumentation-log-file=/some/path/das_log.txt` (change /some/path/ to any writable folder)
- In Dart Analysis tool window click Restart Dart Analysis Server button, or just close/open the IDE. Reproduce the problem.

das_log.txt file will contain info to analyze. But note that it may include contents of your project files, so if your project is not open source, do not make your das_log.txt file public by attaching here. Instead send it by email to someone from the Dart Analyzer team, for example to @bwilkerson or @scheglov.

**Comment by MikeMitterer** [comment]
BTW: "Reformat with Dart Style" fails too:
idea.log:
`2016-07-06 13:24:27,798 [1581026]   WARN - rt.ide.actions.DartStyleAction - Unexpected response from edit_format, formatResult is null `

**Comment by MikeMitterer** [comment]
Thanks @alexander-doroshko here is the log. das_log.txt will follow.
[idea.log.zip](https://github.com/dart-lang/sdk/files/349650/idea.log.zip)

**Comment by alexander-doroshko** [comment]
BTW is this the project you have problems with: https://github.com/MikeMitterer/dart-material-design-lite?
I cloned it, did `pub get` for the root and some of samples, browsed some code, but had no issues. Code highlighting and completion works fine to me.

**Comment by MikeMitterer** [comment]
OK - here it is:
[das_log.txt.zip](https://github.com/dart-lang/sdk/files/349659/das_log.txt.zip)

Yes - thats the project. Maybe the das_log tells you more. On line 10 it shows "INVALID_FILE_PATH_FORMAT"....

**Comment by alexander-doroshko** [comment]
Thanks! Server failed to initialize project roots, so obviously nothing works. I guess the problem is that one of the paths in the "excluded" is just empty, here's a formatted snippet:
```
{
  "id": "3",
  "method": "analysis.setAnalysisRoots",
  "params": {
    "included": [
      "/Volumes/Daten/DevLocal/DevDart/BeanValidator.Dart",
      ...
    ],
    "excluded": [
      ...
      "/Volumes/Daten/DevLocal/DevJava/MobileAdvertising/classes",
      "",
      "/Volumes/Daten/DevLocal/DevDart/MaterialDesignLiteSite/.pub",
      ...
    ],
    "packageRoots": {}
  },
  "clientRequestTime": 1467805368856
}
```
To find out where it came from I need to check your `*.iml` files. Most likely the problem came from MobileAdvertising.iml or MaterialDesignLiteSite.iml, but also may be from some other one. Can you please attach these or all iml files and also .idea folder zipped?

**Comment by MikeMitterer** [comment]
Hope I got everything. I also added DevDart-Tree - it shows my local tree (/Volumes/Daten/DevLocal/DevDart/...) + SS that show the according project structure

[MobileAdvertising.zip](https://github.com/dart-lang/sdk/files/349856/MobileAdvertising.zip)

**Comment by alexander-doroshko** [comment]
@MikeMitterer I believe the problem is cause by the following line
```
<excludeFolder url="" />
```
in 2 files: `MaterialDesignLiteSite.iml` and `MaterialIcons.iml`.

I'm afraid I have no idea how this line appeared there, do you?

The problem should go away if you remove these lines. You can edit IMLs right from the IDE without closing the project (Go To File by name and edit), then click Save button and Restart Dart Analysis Server form the Dart Analysis tool window. Then see if "INVALID_FILE_PATH_FORMAT" is gone from the das_log file.

**Comment by MikeMitterer** [comment]
Phuuu!!! Not to believe - this really solves my problem + I found a few more .iml's with such an entry.
Thanks for your help!!!!! You want to try Austrian beer? I'll send you some - just to say Thanks! Send me your private address under office@mikemitterer.at

**Comment by alexander-doroshko** [comment]
@MikeMitterer Any chance to meet you at [Dart Summit](https://www.dartlang.org/events/2016/summit/)? ;)

**Comment by MikeMitterer** [comment]
@alexander-doroshko Sure! Meet your there! German Weißbier included ;-)

**Comment by alexander-doroshko** [comment]
I've pushed a fix to make sure that IDE doesn't send incorrect paths in case of misconfiguration like in your case. Still no idea how it could appear. UI doesn't allow to add invalid entries. Any idea?

Also there are few things that may be tuned in your project setup. Not a big deal, just to have cleaner project structure:

1. Remove excluded folders that do not exist. They are rendered like this in Project Structure dialog: 
![image](https://cloud.githubusercontent.com/assets/4499789/16623328/24aa703a-43a6-11e6-8075-510a3ef9a71a.png)

2. You have a great many of nested excluded folders configured. You may leave only root ones. Example from `MaterialDesignLite.iml`:
```
      <excludeFolder url="file://$MODULE_DIR$/build" />
      <excludeFolder url="file://$MODULE_DIR$/build/samples/mdl_animation/packages/mdl/_templates/article/web/packages" />
      <excludeFolder url="file://$MODULE_DIR$/build/samples/mdl_button/packages/mdl/_templates/android/web/fonts/packages" />
    ...
      <excludeFolder url="file://$MODULE_DIR$/lib/_templates" />
      <excludeFolder url="file://$MODULE_DIR$/lib/_templates/android/packages" />
      <excludeFolder url="file://$MODULE_DIR$/lib/_templates/android/web/fonts/packages" />
    ...
```
Leave only `build` and `_templates` for this example. You can fix it both from Project Structure dialog (recommended) or by editing IML files.

**Comment by MikeMitterer** [comment]
Thanks for your suggestion - I'll removed it but I din't add all these includes by hand... Don't know where they come from!

**Comment by MikeMitterer** [comment]
I someone finds this report - the following snipped could be helpful:
```bash
find . -iname "*.iml" -exec grep -l 'excludeFolder url=""' \;
```

**Comment by alexander-doroshko** [comment]
IntelliJ's Find In Path with file name filter works fine as well :)
BTW I've made IDE tolerant to incorrect root settings, so when my fix lands problems like yours won't be actual any more.
