### ISSUE TITLE
HOT RELOAD: Crash after deoptimization

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26833]
fyi @johnmccutchan 

Repro:
```
out/DebugX64/dart --print-ast --print-flow-graph --disassemble --trace-deoptimization --trace-deoptimization-verbose --trace-compiler --trace-reload --reload-every=50000 --ignore-unrecognized-flags --package-root=out/ReleaseX64/packages/ tests/language/regress_26453_test.dart
```

It looks like we don't generate the same AST for the closure bar, when we regenerate the unoptimized code after reload. The result is a mismatch with deopt ids.

Crash:
```
runtime/vm/deferred_objects.cc: 123: error: expected: continue_at_pc != 0
```

**Comment by fsc8000** [comment]
The mismatch comes from compile-time constants that are not present in the constant cache when the inner function bar() is recompiled after isolate reload.

**Comment by johnmccutchan** [comment]
@fsc8000 We attempt to preserve the right compile-time constants.

@turnidge we should meet with Florian today and try and get to the bottom of this.
