### ISSUE TITLE
dartfmt disagrees with dart-up-and-running example

### ISSUE THREAD

**Issue by Zectbumo** [dart-lang/sdk#26830]
I actually prefer the formatting in the switch example on [Dart Up and Running Switch Case](https://www.dartlang.org/docs/dart-up-and-running/ch02.html#switch-and-case) but dartfmt seems to dissagree.

dartlang.org:
```
var command = 'CLOSED';
switch (command) {
  case 'CLOSED':
    executeClosed();
    continue nowClosed;
    // Continues executing at the nowClosed label.

nowClosed:
  case 'NOW_CLOSED':
    // Runs for both CLOSED and NOW_CLOSED.
    executeNowClosed();
    break;
}
```

dartfmt:
```
var command = 'CLOSED';
switch (command) {
  case 'CLOSED':
    executeClosed();
    continue nowClosed;
  // Continues executing at the nowClosed label.

  nowClosed: case 'NOW_CLOSED':
    // Runs for both CLOSED and NOW_CLOSED.
    executeNowClosed();
    break;
}

```

**Note:**
nowClosed: case 'NOW_CLOSED':

I wrote the issue here instead of the issue tracker on www.dartlang.org in hopes that dartfmt would change and not the example itself. I think having the label on the same line as the case statement destroys readability of the the switch block and should be on a separate line indented however you think makes most sense.

**Comment by lrhn** [comment]
FWIW, I think both are wrong :)
I prefer the label on a separate line, but it should be indented the same as the `case`.

**Comment by floitschG** [comment]
@munificent: If this is a dartformat bug, please transfer it to dartformat.
@kwalrath: if it isn't please transfer it to the web-issue tracker.

Thanks

**Comment by munificent** [comment]
Already a formatter bug: https://github.com/dart-lang/dart_style/issues/43

:)

(For what it's worth, virtually zero code in the wild uses labels, so improving dartfmt's handling of them has never been a priority. Note that both this bug and Kathy's original one both refer to the exact same example. If we were to take that code out of the docs, that would probably eliminate almost all known uses of labels.)
