### ISSUE TITLE
HOT RELOAD: Bring reload stress test bots online and keep them green

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26843]
We need a debug and release Linux x64 bot for testing hot reload functionality. 

Building both debug and release:

./tools/build.py -mdebug,release runtime

Testing both debug and release and checked / non-checked:

./tools/test.py -mdebug,release --checked --hot-reload
./tools/test.py -mdebug,release --hot-reload

**Comment by johnmccutchan** [comment]
@a-siva @rmacnak-google FYI

**Comment by whesse** [comment]
If we don't get the bots by Monday, I can put up the new builders, sharing
existing bots, so they can be tested.

On Fri, Jul 8, 2016 at 8:10 PM, John McCutchan <notifications@github.com>
wrote:

> @a-siva <https://github.com/a-siva> @rmacnak-google
> <https://github.com/rmacnak-google> FYI
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26843#issuecomment-231431914>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AErapzBXUeblGMeXXOsx8YVNX7Gea0_vks5qTpKEgaJpZM4JIQ-7>
> .
>



-- 
William Hesse

**Comment by johnmccutchan** [comment]
@whesse Sounds good to me. 

Once we get the new bots they should be classified under 'vm-misc' with the names:

- vm-linux-release-x64-hot-reload-stress
- vm-linux-debug-x64-hot-reload-stress
