### ISSUE TITLE
Annotations should always invoke the constructor

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26840]
@jacob314 suggests that annotations should always invoke the constructor:
From https://github.com/dart-lang/sdk/issues/26322#issuecomment-231226953:

> This is a general issue with annotations in Dart2JS and Dart. I think the most user friendly solution is to have
> @AnyAnnotation 
> be syntactic sugar for
> @AnyAnnotation()
> if AnyAnnotation is a class.
> This is consistent with how some other languages handle annotations, makes the code users write more terse, and avoids these entirely confusing compile errors altogether.

**Comment by munificent** [comment]
Duplicate of #13582.
