### ISSUE TITLE
Number literal syntax - allow underscores or other way to make number more readable

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26845]
This is likely a 2.x feature.

I would like to be able to use underscores inside number literals to break up long runs of digits.
For example `1000000000` is harder to understand than `1_000_000_000`.

Today I saw  `x & 0x3FFFFFF` with a comment saying the result fits in 30 bits.
If you count the `F`s, you will see there is an error, but the error has gone unnoticed for several years.
If underscores were permitted, the following difference might be more apparent to the developer or reviewer:

```
x & 0x_3FF_FFFF     vs     x & 0x_3FFF_FFFF
```

I would want the exact placement of underscores not be prescribed, the same literal might warrant different structure depending on context. In some byte-oriented code `0x3F_FF_FF_FF` might make more sense.

This feature would also make binary literals (`0b_1111_1111` = 255) more useful.

**Comment by zoechi** [comment]
See also #2995

**Comment by lrhn** [comment]
That feature is on my (rather long) list of conveniences I'd like too.

My design would only allow underscores between *digits*, so `0x3FFF_FFFF`, not `0x_3FFF_FFFF`, but apart from that I agree.

**Comment by rakudrama** [comment]
I found another example of the initial problem of a wrong literal: fc67a19feb0a3cbd2ae4fb5da4d317112eb016f1

**Comment by lrhn** [comment]
I reasonably often see code like `100 * 1000 * 1000` to dodge the issue. That could just have been `100_000_000`.

**Comment by srawlins** [comment]
I think we can close this in favor of https://github.com/dart-lang/language/issues/2 in the new language repo; 20 upvotes today.

**Comment by lrhn** [comment]
Now that you have linked the two, I agree :)

**Comment by 89z** [comment]
https://github.com/dart-lang/language/issues/1
https://github.com/dart-lang/language/issues/2

https://github.com/dart-lang/sdk/issues/26845
https://github.com/dart-lang/sdk/issues/2995
