### ISSUE TITLE
The stream class is missing a 'isNotEmpty'.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26841]
Apparently we forgot to add `isNotEmpty` to the Stream API. (at least that's what dartdoc states).

This should be fixed with Dart 2.

**Comment by floitschG** [comment]
Remove `.isEmpty` and `.length` instead.

**Comment by dgrove** [comment]
I take it that this isn't happening, @lrhn and @leafpetersen ?

**Comment by leafpetersen** [comment]
Certainly not for Dart 2.  @lrhn do you want to leave this open for a future release or close?

**Comment by mateusfccp** [comment]
Well, many year later and I am still waiting for this.

**Comment by lrhn** [comment]
I wouldn't wait too hard. I don't think it's a particularly useful functionality on a stream. Unlike an iterable, you usually can't replay a stream, so the moment the `isNotEmpty` returns `true`, you've already lost the entire content of the stream. There might be situations where that's useful, but they'll be rare enough that it's unlikely to be worth the breaking change to add it to `Stream`.

It's annoying that we have `isEmpty`, but not `isNotEmpty`, but the error is probably that we have `isEmpty` at all.

So, let's just admit that this isn't planned.
