### ISSUE TITLE
Firefox: vertexAttribDivisorAngle$2 is not a function

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#26850]
Full error: `TypeError: J.getInterceptor$x(...).vertexAttribDivisorAngle$2 is not a function`

I got this error while working with `ANGLE_instanced_arrays`. `getSupportedExtensions` indicates that this extension is supported. The same code is working in Chrome.

My code snippet:
```
// Get ANGLE extension.
gl.AngleInstancedArrays ext = _ctx.getExtension('ANGLE_instanced_arrays');

// Load divisors.
divisors.forEach((String attrib, int divisor) {
  ext.vertexAttribDivisorAngle(shaderProgram.attributes[attrib], divisor);
});

ext.drawElementsInstancedAngle(
    mode, length, GlIndexBuffer.indexBufferType, offset, count);
```

`print(ext)` gives `[object ANGLE_instanced_arrays]` (I would expect `[object AngleInstancedArrays]`, Chrome gives `Instance of 'AngleInstancedArrays'`). I have no idea how to debug this any further.

**Comment by hermanbergwerf** [comment]
Not sure if it helps but somehow this also affects the Midori browser.

**Comment by rakudrama** [comment]
If you put this before your other script tags, does it start to work?

```html
<script>
    (dartNativeDispatchHooksTransformer =
      window.dartNativeDispatchHooksTransformer || []).push(function (hooks) {
      var getTag = hooks.getTag;
      hooks.getTag = function (obj) {
        var tag = getTag(obj);
        if (tag == 'ANGLE_instanced_arrays') return 'AngleInstancedArrays';
        return tag;
      };
      return hooks;
    });
</script>
```

**Comment by rakudrama** [comment]
@hermanbergwerf, I don't know much about WebGL extensions and how they are supposed to work.
I wonder if you could be so kind as to construct a minimal but complete stand-alone 'demo' that uses the feature. I would use it to debug the issue and then convert it into a regression test to improve our test coverage.

**Comment by hermanbergwerf** [comment]
The snippet did not work. This specific extension enables a feature called instanced drawing. This means that the same vertices can be drawn in a loop. Using a special function (`glVertexAttribDivisor`), you can specify how attributes are repeated (`0` means attribute is retrieved by vertex index, `1` means each instance gets the next attribute, etc.) In my case this is useful for drawing a lot of imposter particles. I'll put together a small demo later today that demonstrates this. I can drop a Dartpad link here or should I open a PR?

**Comment by hermanbergwerf** [comment]
Ok, here is a neat little demo: https://dartpad.dartlang.org/7545df09a040ee2e17077df1480fd0c8

**Comment by hermanbergwerf** [comment]
When can I expect this to work in dart2js?

**Comment by alan-knight** [comment]
It should work in bleeding edge now.
