### ISSUE TITLE
Analyzer fails to detect use of initializing formal in closure signature.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#26860]
This regression test fails:
language/regress_26855_test/4

class C {
  C();
  C.f4(int g(this.x));  /// 4: compile-time error
}

**Comment by scheglov** [comment]
https://codereview.chromium.org/2178123003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f8c32c5ea1a7f7ce0786af3c30a8f70d01b361f0
