### ISSUE TITLE
Generalize assert syntax

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26865]
With reference to https://github.com/dart-lang/sdk/issues/17682 for background, the analyzer should be adjusted such that it accepts arguments to `assert` parsed as `expression`, rather than requiring the more restrictive `conditionalExpression`.

The language team discussed this issue and came up with an analysis concluding that we will make this change: https://gist.github.com/eernstg/50a327addd96035d5393a507c0ea2d9a.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2140673004/
