### ISSUE TITLE
Initializing formals may crash dart2js in host-checked mode

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#26867]
These regression tests using initializing formals crash dart2js in host-checked mode:
regress_26855_test/1: Crash
regress_26855_test/2: Crash
regress_26855_test/3: Crash
regress_26855_test/4: Crash

Example:
FAILED: dart2js-d8 release_ia32 language/regress_26855_test/1
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[dart2js]:

stdout:
out/ReleaseIA32/generated_tests/language/regress_26855_test_1.dart:7:15:
Error: Initializing formal parameter only allowed in generative constructor.
void f1(int g(this.x)) {}  /// 1: compile-time error
              ^^^^^^
out/ReleaseIA32/generated_tests/language/regress_26855_test_1.dart:7:1:
Internal Error: The compiler crashed when compiling this element.
void f1(int g(this.x)) {}  /// 1: compile-time error
^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:
- the name and version of your operating system,
- the Dart SDK build number (build number could not be determined), and
- the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'LocalParameterElementX' is not a subtype of type 'FunctionElement' of 'functionDeclaration' where
  LocalParameterElementX is from file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/elements/modelx.dart
  ParameterElement is from file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/elements/elements.dart
  FunctionElement is from file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/elements/elements.dart
#0      ParameterElementX.ParameterElementX (file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:1786:23)
#1      ErroneousInitializingFormalElementX.ErroneousInitializingFormalElementX (file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:1869:9)
#2      SignatureResolver.createFieldParameter (file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/resolution/signatures.dart:209:20)
#3      SignatureResolver.visitSend (file:///b/build/slave/dart2js-linux-d8-hostchecked-4-5-be/build/sdk/pkg/compiler/lib/src/resolution/signatures.dart:179:12)

[...]

**Comment by sigmundch** [comment]
this is fixed with --use-kernel
