### ISSUE TITLE
AudioNode.connectNode suppresses the return type introduced in later Chrome IDL

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26862]
See https://github.com/dart-lang/sdk/issues/26740 and https://codereview.chromium.org/2118633002

In Chrome 46 connectNode has no return type, but in later versions it does. The method is in a template, so right now we manually suppress that return type. This will be broken as soon as we roll dart:html to a version that does have a valid return type. Adding this as a reminder, and assigning it an arbitrary future release where I think the roll should be done.

**Comment by alan-knight** [comment]
@rakudrama @floitschG

**Comment by kevmoo** [comment]
Are we planning to get this in for 1.19?

**Comment by kevmoo** [comment]
@terrylucas @alan-knight Ping?

**Comment by mit-mit** [comment]
Clearing milestone as this is a bit out (needs a new dartium roll)
