### ISSUE TITLE
CAN_BE_NULL_AFTER_NULL_AWARE too aggresive

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#26874]
CAN_BE_NULL_AFTER_NULL_AWARE triggers even with method calls that are defined on [Null](https://api.dartlang.org/stable/1.17.1/dart-core/Null-class.html):

```dart
void main() {
  String a = null;
  // Analyzer warning: The expression uses '?.', so can be 'null'
  print(a?.length.hashCode);
}
```

https://dartpad.dartlang.org/0980bcd5579ed5643c5ac6f87d06fac0

In this case, `hashCode` is defined on Null.

For justification on why anyone would want to do this, we want to generate a hashCode on an instance of a class whose attributes might have null values, such as [this `hashCode` method](https://github.com/dart-lang/html/blob/9e79e1be3692eeeffe7837fac6adb73389da6e2d/lib/dom.dart#L47..L52) from package:html.

**Comment by lrhn** [comment]
For the record, I think this is so uncommon that we should change the language to let `something?.foo.bar` evaluate to `null` when `something` is `null`, instead of trying to read `bar` off `null`.
Then this code would have to be written as `(something?.foo).hashCode`.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2320573003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/114fcdb839e2b0ba8902fb5422aa55fb02d74aec
