### ISSUE TITLE
'Write a Server App' html tags on CodeLab

### ISSUE THREAD

**Issue by kalenm00028** [dart-lang/sdk#26870]
I was just walking through the 'Write a Server App' tutorial on https://dart-lang.github.io/server/codelab/, and was confused for a minute upon reaching Step 7, editing pubspec.yaml.  The line that's supposed to be added in is "**http_server: ^0.9.5+1**", but the snippet actually reads "\<b>http_server: ^0.9.5+1\</b>".  It's nothing major, but might be confusing to people not too familiar with the material.  Thanks!

**Comment by floitschG** [comment]
Thanks.

@kwalrath : I can't find the repo this should be under, so I just assigned it area-documentation for now.

**Comment by Sfshaza** [comment]
The file is here:  https://github.com/dart-lang/server/blob/gh-pages/codelab/index.md

Fixed.
