### ISSUE TITLE
Seg fault from VM when loading extensions

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#26879]
Seeing a seg fault in the VM 1.18.0-dev.4.0 when loading code with `dart-ext:user_extension`

#0  0x00007ffff7190e6c in __strncmp_ssse3 () from /usr/grte/v4/lib64/libc.so.6
#1  0x00000000005a776b in dart::bin::Extensions::LoadExtension(char const*, char const*, _Dart_Handle*) ()
#2  0x00000000005aa8eb in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) ()
#3  0x0000000000883822 in dart::Parser::CallLibraryTagHandler(Dart_LibraryTag, dart::TokenPosition, dart::String const&) ()
#4  0x00000000008849e6 in dart::Parser::ParseLibraryImportExport(dart::Object const&, dart::TokenPosition) ()
#5  0x0000000000885b0f in dart::Parser::ParseLibraryDefinition(dart::Object const&) ()
#6  0x000000000085a861 in dart::Parser::ParseTopLevel() ()
#7  0x000000000085a481 in dart::Parser::ParseCompilationUnit(dart::Library const&, dart::Script const&) ()
#8  0x00000000006cc0bb in dart::Compiler::Compile(dart::Library const&, dart::Script const&) ()
#9  0x00000000005e3c8e in dart::CompileSource(dart::Thread*, dart::Library const&, dart::Script const&, _Dart_Handle**) ()
#10 0x00000000005e6b66 in Dart_LoadLibrary ()
#11 0x00000000005aa1cf in dart::bin::Loader::ProcessResultLocked(dart::bin::Loader*, dart::bin::Loader::IOResult*) ()
#12 0x00000000005aa064 in dart::bin::Loader::ProcessQueueLocked(bool (*)(dart::bin::Loader*, dart::bin::Loader::IOResult*))
   ()
#13 0x00000000005aa86d in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) ()
#14 0x00000000005a042e in dart::bin::CreateIsolateAndSetupHelper(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, char**, int*) ()
#15 0x000000000059f9e2 in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) ()
#16 0x00000000005a0e62 in dart::bin::main(int, char**) ()
#17 0x00000000005a16d9 in main ()

**Comment by skybrian** [comment]
Based on what Chris was saying before he left on vacation, the reason this is new is that the analyzer is somehow depending on a library with a native extension when it didn't before.

**Comment by skybrian** [comment]
Most likely the native library isn't in the right place. Perhaps the VM error is that it should be giving us a proper error message about a missing file, rather than segfaulting.

**Comment by johnmccutchan** [comment]
I've built a local reproduction. The root issue is that we haven't encountered dart-ext imports from packages when running without a package root (only a packages file).

**Comment by johnmccutchan** [comment]
@a-siva FYI

**Comment by skybrian** [comment]
I take back what I said. The dependency wasn't in the Analyzer; it's in Google-specific code.

**Comment by johnmccutchan** [comment]
CL up here https://codereview.chromium.org/2146093002/

**Comment by whesse** [comment]
If this fixes the issue, please file a merge-to-dev request for this CL.

**Comment by johnmccutchan** [comment]
@whesse done: https://github.com/dart-lang/sdk/issues/26885
