### ISSUE TITLE
HOT RELOAD: Support reloading deferred libraries

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26878]
We need to handle deferred libraries specially during reload. Currently all deferred library tests are marked skip in the status files.

**Comment by turnidge** [comment]
I submitted a change to explicitly disallow deferred libraries when reloading, so at least the system will handle it more gracefully until we fix this.

77b99396e8c9251d816ed45eab8479dee812a397

There was one odd test that I still saw passing (spuriously) despite the change:

```
deferred_super_dependency_test: Pass, Crash # Requires deferred libraries
```

Probably could bear some investigation.

**Comment by mraleph** [comment]
Closing as outdated.
