### ISSUE TITLE
HOT RELOAD: Add a debug pass over the heap which verifies that all canonical objects canonicalize to themselves

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26883]

**Comment by johnmccutchan** [comment]
@a-siva

**Comment by johnmccutchan** [comment]
@a-siva I've landed the enum fix https://github.com/dart-lang/sdk/commit/133c087cdb98267a4d7a38c47ec919c115766408 you should be able to turn this on.

**Comment by johnmccutchan** [comment]
Related:

https://github.com/dart-lang/sdk/issues/27802
https://github.com/dart-lang/sdk/issues/27803

**Comment by a-siva** [comment]
https://chromiumcodereview.appspot.com/2490233004/
