### ISSUE TITLE
base/trace_event/etw_manifest/BUILD dir causes conflict in bazel

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#26882]
Having a directory named `BUILD` creates problem when running bazel, as bazel uses `BUILD` files to specify targets.

Could this be renamed?

**Comment by zanderso** [comment]
We DEPS in //base. The file names are not under our control. @johnmccutchan.

**Comment by a-siva** [comment]
This has been fixed in the import script into google3 (the script now ignores 'base')
