### ISSUE TITLE
webgl test status difficult with infrastructure

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26898]
I thought it better to at least make a bug for this rather than leave it as comments in the status file.

We have webgl extension tests that pass on bots with certain graphics configurations, and not on others. In particular, my issue is with 
LayoutTests/fast/canvas/webgl/context-destroyed-crash_t01 
LayoutTests/fast/canvas/webgl/context-lost-restored_t01
LayoutTests/fast/canvas/webgl/context-lost_t01

which on Firefox pass on the Windows 7/IE11 bot, but not elsewhere. Writing the condition for this is tricky and likely to be misleading anyway, so I'm leaving them as Pass, RuntimeFailure for the moment. And they're co19 tests, but it's not something co19 can fix.

**Comment by alan-knight** [comment]
@rakudrama

**Comment by athomas** [comment]
We plan to stop running the tests and the new workflow made them easy to approve.
