### ISSUE TITLE
analyzer warns with wrong number of arguments on a "dynamic" variable

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26899]
(not strong mode)

``` dart
//@proxy
class C {
  bar(String s) { print(s); }

  noSuchMethod(Invocation i) {
    print(i);
  }
}
main() {
  dynamic c = new C();
  // [warning] 1 positional arguments expected, but 2 found
  c.bar('hi', 'world');

  // [hint] The argument type 'int' cannot be assigned to the parameter type 'String'. 
  c.bar(42);
}
```

The hint makes sense, but the warning is based on the propagated type. We shouldn't do that, right?

This is a warning in Dart 1 mode. (Strong mode promotes it to an error, because it doesn't know the value was computed via propagated type info).

Interestingly, for this error message, I couldn't even find a HintCode for it.

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen who were also mystified by this :)

**Comment by bwilkerson** [comment]
> The hint makes sense, but the warning is based on the propagated type. We shouldn't do that, right?

Correct. This should be producing a hint, not a warning.

**Comment by jmesserly** [comment]
assumed stale
