### ISSUE TITLE
Please merge revision 7af8d6e5a4f981e06a29e28db180ca4badd2f0f9 and 4bfdaa83b2c5c6f90f410e7eea4729f8f65d3440 into dev channel

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26897]
@whesse @mit-mit @kasperl 

BUG: https://github.com/dart-lang/sdk/issues/26894

patch: https://codereview.chromium.org/2155823002

@keertip @a-siva

**Comment by mit-mit** [comment]
Doesn't look like https://codereview.chromium.org/2155823002 landed?

**Comment by whesse** [comment]
Merged in 1.18.0-dev.4.2.
