### ISSUE TITLE
Failure when running test that has a package with native code

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#26894]
VM 1.18.0-dev.4.0

Test fails to run with failure related to the native code. The test is run using `dart --packages packagesDir scriptFile`.

'package:sync_socket/src/socket.dart': error: line 20 pos 1: native function 'connect' (2 arguments) cannot be found
int _connect(String host, String service) native 'connect';
^

**Comment by johnmccutchan** [comment]
I believe this [CL](https://codereview.chromium.org/2153203002/) fixes the issue. Please confirm @keertip

**Comment by keertip** [comment]
Yes, it does fix the problem. Thanks!
