### ISSUE TITLE
A `switch` statement compiled by dart2js has a different behavior from dart VM

### ISSUE THREAD

**Issue by Keksinautin** [dart-lang/sdk#26900]
Dart code (`test.dart`):

```
int c = 2;
switch (c) {
  case 2:
  default:
    print('def!');
}
```

`dart test.dart` => prints `def!`. It is checked for 1.15.0, 1.16.0 and 1.17.1 versions.
But `dart2js test.dart -o test.js && node test.js` => prints `def! def!`. It is checked for the same versions.
In compiled js file we can see:

```
main: function() {
      switch (2) {
        case 2:
          H.printString("def!");
        default:
          H.printString("def!");
      }
    }
```

I do not think it is correct compiling. What do you think?

url for reproducing: https://dartpad.dartlang.org/fccb0510e8da10831ee690959f94a5b6

**Comment by DisDis** [comment]
Please add reproduce url  https://dartpad.dartlang.org/fccb0510e8da10831ee690959f94a5b6
