### ISSUE TITLE
Zone updates in 1.18 break a number of Angular zone tests

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26906]
All succeed in 1.17

See @kevmoo for repro details

Suspect commit: dart-lang/sdk@6a7c037

**Comment by mit-mit** [comment]
CC @mit-mit

**Comment by alan-knight** [comment]
Reverted the suspect commit and it seems to be working for me. Landed on Dart bots now.

**Comment by alan-knight** [comment]
There seems to be a bug in Angular2 that the el function is defined in two places, so it doesn't compile with dart2js. If I fix that it runs there as well.

**Comment by kevmoo** [comment]
> There seems to be a bug in Angular2 that the el function is defined in two places, so it doesn't compile with dart2js. If I fix that it runs there as well.

Awesome!

**Comment by kevmoo** [comment]
Fixed by 30b489578d9ee587d2ca622346e2051a869fb994 – thanks @alan-knight 

Will open a merge request separately
