### ISSUE TITLE
Please merge 30b48957 into 1.18

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26907]
Provides fix for 1.18 block issue https://github.com/dart-lang/sdk/issues/26906

**Comment by whesse** [comment]
Also merge bde8d3efc6f7558edda6a1cad879ff4a264ddabe , before merging 30b489578d9ee587d2ca622346e2051a869fb994 .

This picks up some follow-up commits, that were not reverted.

**Comment by whesse** [comment]
Merged in 1.18.0-dev.4.3

**Comment by kevmoo** [comment]
@whesse can close? as fixed?

**Comment by whesse** [comment]
This, or a new issue, will need to be opened when we reland the changes we
rolled back.  @floitch.

**Comment by mit-mit** [comment]
Created https://github.com/dart-lang/sdk/issues/26922 to track getting zone tasks landed again. Closing this bug as the merge for 1.18 was completed.
