### ISSUE TITLE
Need a quick fix to add the keyword 'async' to a function body

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26905]
when there is a StaticWarningCode.UNDEFINED_IDENTIFIER_AWAIT error being reported within the function body.

@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2162523003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/55fcc035720a40ed2bda726eb9ecad78fd6fb08f
