### ISSUE TITLE
Ignore variables named `_`, `__`, ... even when `implicit-dynamic:false`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26915]
These names are usually used for unused parameters.

![image](https://cloud.githubusercontent.com/assets/405837/16957788/28a05e74-4dde-11e6-8b6d-49520c09c4c2.png)

In Polymer apps I have a lot of methods where a specific signature is expected by Polymer but the parameters passed by default are often not relevant:

``` dart
  @reflectable
  void searchStringChanged(_, [__]) {
    if (dataView == null) {
      return;
    }
    updateFilter();
  }
```

adding `dynamic` everywhere is cumbersome for something that should communicate that it is unused

```
  void searchStringChanged(dynamic _, [dynamic __]) {
```

**Comment by srawlins** [comment]
`Implicit-dynamic: false` is dead. Closing as stale.
