### ISSUE TITLE
Uri class query parameters contains '?' char

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#26917]
While working on uri manipulations, see query params contains a '?' char, which should not be the case.

Not sure in when the split and assignment is happening, but seeing test failures due to this.

**Comment by mit-mit** [comment]
CC @whesse

**Comment by whesse** [comment]
I think https://codereview.chromium.org/2167573002/ is a fix for this.  I will land it, and cherry-pick it.

**Comment by mit-mit** [comment]
Closing as this was reverted. https://github.com/dart-lang/sdk/issues/26934 tracks bringing it back once test issues are resolved.

**Comment by floitschG** [comment]
Could you please provide an example.

**Comment by lrhn** [comment]
I have found the problem - it was in `_SimpleUri.replace` where the copy of the query includes the leading `?`.
