### ISSUE TITLE
Symbols::Compact does not drop all unneeded symbols when precompiling

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#26916]
If you compile Flutter Gallery into a snapshot and then look which symbols were written you will find strings like `add_yMMMMEEEEd`. However if you look at the generated methods you will discover that `add_yMMMMEEEEd` was not actually compiled. 

This happens because `Symbols::Compact` does not compact away symbols that are retained by `TokenStream`s.

We are not writing `TokenStream` objects themselves into the snapshot (see `Script::to_snapsot` which excludes `tokens_` for `Snapshot::kAppNoJIT`), but we are still including symbols which are only referred from token streams. 

/cc @rmacnak-google @fsc8000 @mkustermann

**Comment by rmacnak-google** [comment]
db48637ab39adfc79e981a60ab9e3d0b59671323
