### ISSUE TITLE
dart:html, document.createDocumentFragment fails on tr, td, tbody, thead and tfooter tags

### ISSUE THREAD

**Issue by soloproyectos** [dart-lang/sdk#26910]
The document.createDocumentFragment() function fails on 'tr', 'td', 'tbody', 'thead' and 'tfooter' tags.

```dart
final fragment = document.createDocumentFragment();
fragment.appendHtml('<td>First Column</td>');

// prints 0 elements
print(fragment.children.length);
```

**Comment by zoechi** [comment]
I guess this is not supported by the browser. You can just press <kbd>F12</kbd>` and paste `document.createDocumentFragment('<td>First Column</td>').children` into the browser console

![image](https://cloud.githubusercontent.com/assets/405837/16944224/ce4a1246-4d9f-11e6-9b38-01a2efd0b8cf.png)

I assume you need to insert valid HTML and `<td>` on it's own is not valid.

**Comment by soloproyectos** [comment]
That's correct. But I forgot to mention that I'm using a NullTreeSanitizer class to create document fragments:

```dart
class NullTreeSanitizer implements NodeTreeSanitizer {
  void sanitizeTree(node) {}
}

final fragment = document.createDocumentFragment();
fragment.appendHtml('<td>First Column</td>', treeSanitizer: new NullTreeSanitizer());
```
There should be no problem when creating non-standard html. In any case, I suspect that it is a browser-side problem, not a Dart fault.

**Comment by zoechi** [comment]
I added above code into Chrome (not Dartium) devtools and it didn't work, therefore it's unlikely that is related to Dart.

**Comment by alan-knight** [comment]
Yes, that's Chrome that's rejecting it, not Dart.
