### ISSUE TITLE
Problem with appendHtml method (style 'missing')

### ISSUE THREAD

**Issue by Songbird0** [dart-lang/sdk#26918]
Hi, there ! 

I'll write a client-side program for 'inject' html code for coloration parser, so I've used the appendHtml method for html injection, but there is no color...

For example:
```dart
import 'dart:html';
import 'dart:convert';
void main()
{
  var str = '<span id="test" style="background-color: white;">p</span>';
  var sanit = const HtmlEscape(const HtmlEscapeMode(name:'injector', escapeLtGt:false, escapeQuot:false, escapeApos:false, escapeSlash:false)); //that's not the solution
  document.body.appendHtml(sanit.convert(str));
  querySelector("span#test").style.color='pink'; //Solution, but not pretty...
}
```
Where is my error ?

Thanks for your help !

**Comment by zoechi** [comment]
Did you get any output in the console? Can you create a dartpad.dartlang.org to reproduce?

**Comment by alan-knight** [comment]
appendHtml already sanitizes its input, and inline styles are not allowed by default. Escaping it yourself ahead of time won't help, it will just get double escaped. You need to either explicitly allow the things you want

```
  document.body.appendHtml(str, validator: new NodeValidatorBuilder.common()..allowInlineStyles());
```

or, for the case where you have constant html that you wrote yourself, and you're very sure that you won't ever be including user content, you can skip the sanitization entirely

```
  document.body.appendHtml(str, treeSanitizer: NodeTreeSanitizer.trusted);
```

**Comment by Songbird0** [comment]
It's ok, thanks all ! :)
