### ISSUE TITLE
Add reverse method to Iterable

### ISSUE THREAD

**Issue by dragostis** [dart-lang/sdk#26928]
`Iterable<E>` has no `reverse` method. This method would come in handy especially when wanting to do fold right on an interable:
```
// current
iterable.toList().reversed.fold(...)

// proposed
iterable.reverse().fold(...)
```

Where `reverse()` would have a similar effect to `toList().reversed`.

**Comment by lrhn** [comment]
The problem with `reverse` is that there are no performance guarantees. Most implementations would have to just do `Iterable<T> get reversed => new IterableWrapper<T>(this.toList().reversed);`.

That makes `.toList().reversed` and `.reversed()` equivalent, and you don't need two ways to do the same thing.

We are not planning on adding new members to `Iterable` at this point unless it's extremely important and/or useful.

(There are a few collections that can actually reverse their members in constant time: `LinkedHash` based structures, tree-based (ordered) structures, queues and `List`, but there is no easy way to see if you have one of those).
