### ISSUE TITLE
analyzer should resolve operator references in dartdoc

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26929]
From this dartdoc issue: https://github.com/dart-lang/dartdoc/issues/1087

We should resolve references to operators in dartdoc comments. The form I've seen them in has been this:

```
/// foo [Object.operator==] bar
```

but I'm not sure there is an expected form. In any case, we should provide a way to link to them from dartdoc.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2168833003/
