### ISSUE TITLE
Search for references to a static method returns too many results

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26926]
Open the analyzer package, find the class `FastUri`, select the static method `parse`, and search for references. The resulting list will include references to the static method `parse` in the superclass. But, unlike an invocation of an instance method, none of the references to the static method from the superclass can ever result in the method in the subclass being invoked. They should not be in the result set.

@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2176173004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/dd18f931541b03768f71d0878c502f9ee5f46f5a
