### ISSUE TITLE
Change debian package to use SHA256 or SHA512

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#26923]
apt-get will desupport SHA1 by January 1st, 2017, at which point our debian package will stop working:
https://wiki.debian.org/Teams/Apt/Sha1Removal

It as already causing warnings when running apt-get update:
```
user@vm:~$ sudo apt-get update
Reading package lists... Done 
W: https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release.gpg: Signature by key 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 uses weak digest algorithm (SHA1)
W: https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release.gpg: Signature by key 3B068FB4789ABE4AEFA3BB491397BC53640DB551 uses weak digest algorithm (SHA1)
user@vm:~$ 
```

We need to move to SHA256 or SHA512.

**Comment by mit-mit** [comment]
Some more comments here: http://askubuntu.com/a/776599

**Comment by whesse** [comment]
This issue has already been fixed.  The repositories are signed with SHA256 sums, and the key to sign the repository has also been updated.  The chromium issue tracking this, for all google properties, is https://bugs.chromium.org/p/chromium/issues/detail?id=596074

There should be no warnings when fetching the SDK from the repo.
