### ISSUE TITLE
[vm_service] return empty "breakpoints" array rather than null in --profile mode

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#26938]
Most clients, including Observatory UI and `package:vm_service_client` (and by extension Flutter), expect a non-null "breakpoints" from the `getIsolate` request. However, currently the VM service returns null. This breaks `flutter drive` in `--profile` mode, which we use for performance testing.

**Comment by rmacnak-google** [comment]
fd63b906c02af936fff96b2e5e60aca16a779e1a
