### ISSUE TITLE
Editing generic method type argument comment doesn't update quick fix list

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26935]
Similar to #26911

I have code like

![image](https://cloud.githubusercontent.com/assets/405837/17022629/5dc9daf4-4f4f-11e6-8cbf-eb3189c750b4.png)

then I add the type parameter

![image](https://cloud.githubusercontent.com/assets/405837/17022615/469840c8-4f4f-11e6-91f1-75443d52d4e0.png)

Then I want to convert the inline function style to a block body using the quick fix.

I need to edit something else (adding a space) to get the quick fixes shown

![image](https://cloud.githubusercontent.com/assets/405837/17022687/b23274a2-4f4f-11e6-9a19-bffa82941589.png)

It's not important to me to get this fixed if you think this issue is not serious enough to invest the time until proper generic method syntax becomes available.
Feel free to close.

```
Dart VM version: 1.19.0-edge.db48637ab39adfc79e981a60ab9e3d0b59671323 (Wed Jul 20 13:09:21 2016) on "linux_x64"
```

**Comment by bwilkerson** [comment]
@leafpetersen Any word on how soon we can add generic method support?

**Comment by leafpetersen** [comment]
Syntactic support in the VM should happen this quarter - I believe that is the last remaining platform.
