### ISSUE TITLE
Bring back reverted fast-mode Uri class

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#26934]
This was reverted in the 1.18 end game due to test failures. Please investigate and bring back in once resolved.

https://github.com/dart-lang/sdk/commit/ca4930357635d36d43433334271cdfd658a3a746

**Comment by mit-mit** [comment]
@lrhn was this landed again?

**Comment by lrhn** [comment]
>
> @lrhn <https://github.com/lrhn> was this landed again?
>

Not yet, probably tomorrow.

**Comment by mit-mit** [comment]
Per discussion with @lrhn this does not block 1.19, so removing milestone field.

**Comment by mit-mit** [comment]
@lrhn was this re-landed?

**Comment by lrhn** [comment]
It landed in revision afbbbb97.
