### ISSUE TITLE
Remove packages: dartdap 0.0.10 and dartdap 0.0.11

### ISSUE THREAD

**Issue by hoylen** [dart-lang/sdk#26933]
Please remove these two versions of [dartdap](https://pub.dartlang.org/packages/dartdap):

- dartdap 0.0.10
- dartdap 0.0.11

I screwed up the semantic versioning and these are incompatible with dartdap 0.0.9. Although the methods invocation has not changed, the exceptions thrown are very different and that can make existing code not work properly.

I'll republish as a new version 0.1.0.
Thanks.

**Comment by nex3** [comment]
In this situation, I'd suggest just adding a new 0.0.12 version with the same dependencies as 0.0.11 but without the breaking changes. Pub will always prefer 0.0.12, so it'll effectively hide 0.0.11 and 0.0.10.

**Comment by hoylen** [comment]
Ok. Thanks.

I'll do that.
