### ISSUE TITLE
dart:io HttpRequest docs page is completely blank

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#26943]
While trying to figure out how to sent HTTP requests from the server, I followed a link to [this page](https://api.dartlang.org/stable/1.17.1/dart-io/HttpRequest/HttpRequest.html) detailing the `HttpRequest` class from `dart:io`. The page is completely blank:

![docs](https://cloud.githubusercontent.com/assets/1078012/17055809/34a2ee00-5007-11e6-9da9-e7ad2b9e10dc.png)

**Comment by DanTup** [comment]
Actually, I realise now this page is for the *constructor*, not the class. Still, it doesn't seem useful like this; there should be something (if there are no constructors, some text, or the page should not exist?)?

**Comment by kevmoo** [comment]
Eh. Basically means there is a ctor defined with no documentation. Agreed: it's weird. But not interesting to fix.
