### ISSUE TITLE
Incremental analysis broken by modifying const variable

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26942]
I have `--finer-grained-invalidation` enabled and I'm using 1.18.0-dev.4.0.

Repro steps:
- Open an IntelliJ project analyzing `analyzer`.
- Open the file `test/src/context/mock_sdk.dart`
- Wait for analysis to finish.
- Modify the third argument to _MockSdkLibrary() in the definition of `_LIB_CORE`, by adding a blank line.

Observed behavior: analyzer shows the error messages `'const' variables must be constant value` and `'const' lists must have all constant values`, at the site of the usage of `_LIB_CORE` in `_LIBRARIES`.  Deleting the blank line does not get rid of the error.  To get rid of the error I must reanalyze sources.

**Comment by scheglov** [comment]
I was not able to reproduce this in bleeding edge.

**Comment by stereotype441** [comment]
Confirmed that the problem doesn't happen with bleeding edge.  It appears to have been fixed by 50a9fd807a69d8307b41ed2b129b7efb97390ede.
