### ISSUE TITLE
AST-based summary generation type infers block-bodied closures incorrectly

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26947]
Consider a declaration like this (from the "observe" library):

```
final _identRegExp = () {
  const identStart = '[\$_a-zA-Z]';
  const identPart = '[\$_a-zA-Z0-9]';
  return new RegExp('^$identStart+$identPart*\$');
}();
```

The type inferred for this variable should be `RegExp`.  However, when AST-based summaries are in use, the inferred type is `dynamic`, because AST-based summaries do not record the contents of block-based function bodies, so they cannot see the type that is being returned.

This problem only affects API-level variables (those that are visible outside of function bodies).  Local variables are unaffected.

I will shortly be adding a strong-mode warning to alert the user when a declaration like the one is found.  The workaround is to add an explicit type annotation to the variable.

**Comment by jmesserly** [comment]
UNSAFE_BLOCK_CLOSURE_INFERENCE warning is gone, so I'm guessing this has been fixed/is stale
