### ISSUE TITLE
Unable to create const Symbol from String

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#26950]
The following code passes the analyzer tests, but doesn't work.

```dart
class Wrapper {
  final Symbol s;
  const Wrapper(String name) 
    : s = const Symbol(name);
}
```

The runtime error:

> expression is not a valid compile-time constant

Is it actually wrong?

**Comment by kevmoo** [comment]
You can pass const values into a ctor – but you cannot create them from arguments.

It must still be valid to call `new Wrapper` – which is broken since the call to `const Symbol` is there.
