### ISSUE TITLE
Broken Link in api.dartlang.org doc

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#26961]
[https://api.dartlang.org/stable/1.17.1/dart-indexed_db/dart-indexed_db-library.html](https://api.dartlang.org/stable/1.17.1/dart-indexed_db/dart-indexed_db-library.html)

has a link under section _Other Resources_ to **Use IndexedDb** that is broken.

cheers
Steve Lympany

**Comment by kevmoo** [comment]
@alan-knight care to look?

**Comment by bkonyi** [comment]
Link is no longer broken. Closing.
