### ISSUE TITLE
DateInputElement value is inconsistent

### ISSUE THREAD

**Issue by korsvanloon** [dart-lang/sdk#26968]
Setting and subsequently getting the valueAsNumber from a DateInputElement changes the value somehow.

```dart
var input = new DateInputElement();
var value = 1468533600000;
input.valueAsNumber = value;
print(value); // prints 1468533600000
print(input.valueAsNumber); // prints 1468454400000
assert(input.valueAsNumber == value); // fails
```

I suspect it has something to do with utc, but I'm not sure what's going on.

I see the same behaviour with valueAsDate.

On Chromium Version 45.0.2454.104 (64-bit)

**Comment by zoechi** [comment]
Have you tried in plain JS?

**Comment by korsvanloon** [comment]
You're right, it's a JS issue.

```javascript
var input = document.createElement('input');
input.type = 'date';
var date = new Date(2014, 1, 1);
var value = date.getTime(); 
console.log(value); // 1391209200000
input.valueAsNumber = value;
console.log(input.valueAsNumber); // 1391126400000
```

So what's the deal here?

**Comment by zoechi** [comment]
probably the same as #26951

**Comment by korsvanloon** [comment]
No, I think I know what went wrong.
The date I inserted was local, but the date input field expects utc. The date input field then might round the local date (which is an hour different from utc) to a value with a utc day-precision.

Does that make sense?

This passes, but if I remove `.utc` it fails.
```dart
var input = new DateInputElement();
var value = new DateTime.utc(2016,1,1); // local
input.valueAsNumber = value.millisecondsSinceEpoch;
assert(value.millisecondsSinceEpoch == input.valueAsDate.millisecondsSinceEpoch);
```
