### ISSUE TITLE
Please merge 5923966da3388666f5d7692f2876666cad8b9255 to dev

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26963]
This gives widespread performance improvements on Firefox.
Can this make it into 1.18?

https://github.com/dart-lang/sdk/commit/5923966da3388666f5d7692f2876666cad8b9255

**Comment by mit-mit** [comment]
Does this fix a performance regression introduced in 1.18, or is this a perf enhancement not currently in any shipped release?

**Comment by whesse** [comment]
I don't think we can put it into the release without going through the google3 test cycle again.  By releasing 1.18.0 without it, it will go into 1.19.0-dev.0.0 immediately, which will go into google3, so we will get the assurance we need to put it into a patch release 1.18.1.  So I will relabel this as merge-to-stable, and we will discuss whether it meets the bar or not.

**Comment by mit-mit** [comment]
I agree with that approach.

**Comment by whesse** [comment]
I have created a new dev channel release, 1.19.0-dev.1.0, which includes this fix. I would like to see it go through all our testing, including internal testing, before patching to stable. Does this sound good to you?

**Comment by whesse** [comment]
Merged in 1.18.1
