### ISSUE TITLE
Observatory crash in Flutter

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#26976]
As of July 27th, I can't open Observatory on my flutter app built with --profile.

Here's what I see in dev console:

![screen shot 2016-07-27 at 2 33 29 pm](https://cloud.githubusercontent.com/assets/5479/17193284/32240f48-5407-11e6-9161-35de2ac16c0b.png)

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@rmacnak-google Any idea?

**Comment by sethladd** [comment]
Chatted with @B3rn475 and discovered we have a version of dart that does have a bug in observatory UI. It should be fixed as of https://github.com/dart-lang/sdk/commit/cb468c2c47d5cbf1d8d5f6cea2d56c102513f86f so we'll ask Flutter to update.

Will close this one, as head of master of dart should be working.

**Comment by sethladd** [comment]
Opened https://github.com/flutter/flutter/issues/5106 to track on the Flutter side.

**Comment by B3rn475** [comment]
Looking at the actual JS exception we figured out that it is related to the
Polymer double registration bug that was solved on Sunday.

I'm trying to rebuild the flutter engine on my machine to check that the
latest version is not affected by the bug.

---
Carlo BERNASCHINA

Google Intern

**Comment by pq** [comment]
Have we confirmed that this fixes it?  If so, maybe @whesse could do another roll?

**Comment by johnmccutchan** [comment]
@pq Observatory is built from the runtime that is DEPSed in and not from the SDK

**Comment by B3rn475** [comment]
I built the flutter engine using the latest SDK commit and Observatory is
working fine.

Tested on Android.

---
Carlo BERNASCHINA

Google Intern

**Comment by pq** [comment]
Ah, cool.  Thanks!

**Comment by sethladd** [comment]
Just a friendly update: Observatory work with Flutter again :) Thanks!
