### ISSUE TITLE
Improve implementation of finally clauses in the VM.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#26975]
Since the same finally clause can be invoked from different locations, its code is duplicated at these various locations. In order to copy the corresponding ast, the same finally clause is parsed multiple times, causing various undesirable side effects (see issue #26948 for an example).

The implementation should be modified to treat the code of a finally clause as a subroutine invoked from different numbered locations. The index of the calling location is passed as an argument (or local variable) to the finally code, which implements a switch statement branching back to the calling location depending on the index. Obviously, this will have to work with optimized code (and osr too?) and async code.

**Comment by a-siva** [comment]
@alexmarkov @aam is this assertion about finally calls code being duplicated still valid?

**Comment by alexmarkov** [comment]
@a-siva Yes, `finally` code is duplicated on each control flow exit out of the `try` block (see `TranslateFinallyFinalizers` in runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc and its uses).

However, I'm not sure treating `finally` as subroutine and adding a switch statement to dispatch after executing `finally` makes sense, as it would result in slower code, and most likely would require a lot of additional complexity (for example consider stack maps which can be different depending on the call site of the `finally` subroutine).
