### ISSUE TITLE
js-util object in dart:html has failing tests on IE

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26978]
The test js_util_test, introduced with the js_util object in 
https://codereview.chromium.org/2150313003
has failures on Windows IE browsers

html/js_util_test/callConstructor
fails on both ie10 and ie11

html/js_util_test/hasProperty
and
html/js_util_test/getProperty
fail on ie10

The error on callConstructor is:
FAILED: dart2js-ie11 release_ia32 html/js_util_test/callConstructor
Expected: Pass 
Actual: RuntimeError
 <p>Expectation: 
                                <a href="#testFilter=callConstructor html object">
                                  callConstructor html object
                                </a>.
                              </p>
                              <pre>Test failed: Caught NullError: Object doesn't support this action (Error 445)</pre>
                            </td>
                          </tr><tr><td></td><td colspan="2"><pre>http://127.0.0.1:51224/root_build/generated_compilations/dart2js/tests_html_js_util_test/test.js 15444:13  callConstructor
                    http://127.0.0.1:51224/root_build/generated_compilations/dart2js/tests_html_js_util_test/test.js 16718:9   main__closure.call$0
                    http://127.0.0.1:51224/root_build/generated_compilations/dart2js/tests_html_js_util_test/test.js 18389:9   &lt;fn&gt;

**Comment by whesse** [comment]
ie10 failures are obsolete, only ie11 failure on html/js_util_test/callConstructor remains

**Comment by Markzipan** [comment]
Closing this since IE11 is no longer supported by our web targets.
