### ISSUE TITLE
exclude part files from resolution entrypoint

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#26974]
When given a list of entrypoints, we should exclude part files if any is given.

**Comment by joshualitt** [comment]
Closing because I can't tell if this is still relevant. Please reopen if this is still something we should do.

**Comment by sigmundch** [comment]
It was meant to capture what we do with a modular compiler when it just has a list of inputs to process. I believe this should be supported already somehow by the kernel worker (given that the modular compilation for ddc must be handling this already), so this should be OK to close.
