### ISSUE TITLE
Please merge https://github.com/dart-lang/sdk/commit/f3ad2b77cc2a76341c3aabcbf37e5d779b3d5d18 to 1.18 stable

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#26989]
Please merge https://github.com/dart-lang/sdk/commit/f3ad2b77cc2a76341c3aabcbf37e5d779b3d5d18 to stable 1.18.

This CL fixes issue 26941 which was reported by the flutter team.

@crelier

**Comment by whesse** [comment]
Merged in 1.18.1
