### ISSUE TITLE
Analyzer false-positive with switch statement

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#26984]
The analyzer reports a warning with this code in Dart 1.18

```dart
enum E { a, b }

String foo(E e) {
  switch (e) {
    case E.a:
      return 'a';
    case E.b:
      return 'b';
  }
}
```

`This function declares a return type of 'String', but does not end with a return statement`

The `switch` covers all the cases so I think this is a bug. This used to work with Dart 1.17.

**Comment by srawlins** [comment]
`e` can be null, in which case the flow falls out of the function without returning. Reference bug: #26606 .
