### ISSUE TITLE
AOT compiler does not need to attach environments

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#26986]
Currently we attach environments to all instructions that can deoptimize (including calls, for lazy deoptimizations). However this just wastes memory/time during compilation and increases value liveness (leading to spilling on some occasions) for nothing because lazy deoptimization can't occur in the precompiled mode.

The only part of the precompiler pipeline that still needs environments to properly function is try/catch implementation - which uses them to emit try/sync code. 

We should look into not attaching environments when they are not needed and also refactoring try/catch implementation to not rely on environments if possible.

**Comment by fsc8000** [comment]
Environments are detached for instructions that don't deoptimize. We could try make CanDeoptimize always return false for AOT.
