### ISSUE TITLE
Analyzer incorrectly reports "In constant expressions, operands of this operator must be of type 'bool', 'num', 'String' or 'null'" for == operator with enum operand

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26980]
``` dart
enum MyEnum { a, b }

class Test {
  const Test(MyEnum arg) : value = arg == MyEnum.a ? 0 : 1;
  final int value;
}

void main() {
  Test q = const Test(MyEnum.a);
  Test r = const Test(MyEnum.a);
  print(identical(q, r));
}
```

VM prints "true", showing that the const expression is fine.

Analyzer says:

```
[error] In constant expressions, operands of this operator must be of type 'bool', 'num', 'String' or 'null' (test.dart, line 4, col 36)
```

**Comment by bwilkerson** [comment]
Or showing that the VM has a bug :-)

The language spec says that a constant expression can be (among other things):

An expression of one of the forms e1 == e2 or e1 != e2 where e1 and e2 are constant expressions that evaluate to a numeric, string or boolean value or to null.

It doesn't whitelist enum values. Actually, it doesn't allow enum constants anywhere in constant expressions. I'm guessing this was an oversight.

**Comment by Hixie** [comment]
I think if there's a bug, it's in the spec and the analyzer, not in the VM. :-)

**Comment by lrhn** [comment]
We could allow any compile-time constant value of a class that doesn't override `Object.==` as the left-hand side of a constant `==` operation, but that's probably a little too clever to be actually useful (that would make it a breaking change to add `operator==` to a class with a const constructor, which it isn't now).

Allowing enums is probably fine and useful.

**Comment by dnfield** [comment]
It seems like the following should be possible (or at least it seems to make sense), but it is not as a result of this:

```
class Test2 {
  const Test2({Object opt1, Object opt2}) : assert(opt1 == null || opt2 == null);
}
```

**Comment by dnfield** [comment]
After reading https://github.com/dart-lang/sdk/issues/30288#issuecomment-325015484 - it seems like I just need to use `identical` instead of `==` and it's all fine.  While that makes some sense, it seems like it should be possible to interpret `opt1 == null` as being identical to `identical(opt1, null)` (or at least hint the user that that would work here).

**Comment by eernstg** [comment]
Apparently, the implementation of this feature was never requested explicitly. I just created #33408 to make that happen. I'm closing this because the 'area-language' part was resolved already in Oct 2017 with commit f11f2ed2bda046d5a7af2c34910ed09bed678e82.

**Comment by eernstg** [comment]
Oops, I was looking at [this comment](https://github.com/dart-lang/sdk/issues/26980#issuecomment-396098246) and concluding that this issue was about comparison with `null`. It actually started out as an issue about comparison of enum values, and that has not yet been addressed: Reopening.

**Comment by dnfield** [comment]
Yes, sorry I got confused between the two issues as well.

**Comment by a-siva** [comment]
Flutter code has been fixed and a language issue has been created allowing '==' on Enum values, closing this.
