### ISSUE TITLE
Please merge https://github.com/dart-lang/sdk/commit/11d340c51d7d916c3c4068c341c6e5fe48a6bf40 to stable

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#26982]
Please merge
https://github.com/dart-lang/sdk/commit/11d340c51d7d916c3c4068c341c6e5fe48a6bf40
to the 1.18 stable branch.

This CL fixes issue https://github.com/dart-lang/sdk/issues/26948 raised by the fiber team.

@crelier @zanderso

**Comment by whesse** [comment]
I have created a new dev channel release, 1.19.0-dev.1.0, which includes this fix.  I would like to see it go through all our testing, including internal testing, before patching to stable.  Does this sound good to you?

**Comment by crelier** [comment]
Sounds good to me.Thanks.

**Comment by whesse** [comment]
Merged in 1.18.1
