### ISSUE TITLE
How to get response's authorization token?

### ISSUE THREAD

**Issue by Matrix-Zhang** [dart-lang/sdk#26991]
I post formdata to server's login path with the following code:
```
var data = {"username": username, 'password' : password};
HttpRequest.postFormData(Service.serverUrl + "/login", data).then((response) {
if (response.status == 200) {
    response.responseHeaders.forEach((key, value){
        print(key);
        print(value);
    });
}});
```
The server response headers are:
```
authorization:ShelfAuthJwtSession eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0Njk4NDEzNjQsImV4cCI6MTQ2OTg0MzE2NCwiaXNzIjoiY2xvdWRfc2NhbGVfc3lzdGVtIiwic3ViIjoiQ0xPVUQtU0MtVkVORE9SIiwiYXVkIjpbbnVsbF0sInNpZCI6IjJmNGUxOGMwLTRjMzAtMTFlNi1hMmExLWFmMjY5MDNiNTBjOCIsInRzZSI6MTQ2OTkyNzc2NH0.OoEuYlsItdwjciyZxDTcMi29JSUyZcrZ_2EApkTA12c 
content-type:text/plain; charset=utf-8 
date:Sat, 30 Jul 2016 01:16:04 GMT 
server:dart:io with Shelf 
transfer-encoding:chunked 
x-content-type-options:nosniff 
x-frame-options:SAMEORIGIN 
x-xss-protection:1; mode=block`
```
But it only prints the content-type header— the other headers not included. Why is that?

**Comment by zoechi** [comment]
AFAIK you shouldn't send the authorization header this way anyway. Pass it from the server to the client using a secure HTTP-only cookie and the browser will send it to the server automatically with each request.

**Comment by Matrix-Zhang** [comment]
I use shelf_auth JWT session in server side.
So i just need change http to https, the browser will do everything ?

**Comment by zoechi** [comment]
That's the idea. If you are able to access the token using JS in the browser then your whole JWT setup gets a lot less secure.
