### ISSUE TITLE
Analyzer: Support "&&=" and "||=" operators

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26997]
This is the analyzer-specific issue for #26996. That issue has the details.

**Comment by bwilkerson** [comment]
An initial implementation has been committed (https://codereview.chromium.org/2199323002/). The support is behind a flag, but there is no user-visible way to set the flag. Waiting on shared tests to make the feature user-visible.

**Comment by bwilkerson** [comment]
@munificent Should this be closed?

**Comment by eernstg** [comment]
I believe we should just get it done, and I don't yet see it working in `dartanalyzer` (nor in `dart` for that matter). The spec update has not been landed yet, but it might be obvious (it's a 3 value domain, and it must shortcut, and it should be similar to other compound assignment operators ;-).

**Comment by bwilkerson** [comment]
There was support in analyzer behind a flag, but now that analyzer is on the fasta parser we've lost that support.

Is this an approved 2.1 language feature? I don't remember seeing it on the list, and we're getting very close to shipping, so I don't know that it's reasonable to add new changes at this date. Should we push this to 2.2?

**Comment by eernstg** [comment]
I don't think it's on any short list, in particular certainly not 2.1, but I do think that the whole language team considers it to be an oversight that we don't yet have it, and it should just be done when possible. Don't we have a place for things that just need to be done, even though it won't be right now? ;-)

**Comment by bwilkerson** [comment]
I'm happy to see us improve the quality of Dart, and I think this change would do so. To explain, I was reacting to "just get it done", which sounded like a call to immediate action. It's a non-zero amount of work, so I'd like to see it scheduled.

Perhaps we should create a "Dart2.2" milestone and add a meta issue to it to implement this in both analyzer and front_end.

**Comment by eernstg** [comment]
> reacting to "just get it done"

Oops, those words were not well-chosen, sorry about that. I just meant that it would be a good idea to keep this issue open, as opposed to closing it and forgetting all about this topic (after all, it looks pretty much like an oversight that those forms of compound assignment are not supported). I think it would be a good idea to put it on such a milestone.

**Comment by eernstg** [comment]
Thanks! I just created an issue in the language repo requesting a clarification.

**Comment by srawlins** [comment]
Since the language issue has been moved to https://github.com/dart-lang/language/issues/23, and is not scheduled or prioritized, I think we should close this until there is a clear expectation and action item.
