### ISSUE TITLE
HtmlElement#scroll: property is not a function

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#26994]
When trying to call a scroll() method with `el.scroll(0,100);` on an html element (div) I get the following:

```
Uncaught Unhandled exception:
: property is not a function
#0      Blink_JsNative_DomException.callMethod (dart:_blink:23416)
#1      BlinkElement.scroll_Callback_2_ (dart:_blink:4898)
#2      Element.scroll (dart:html:15674)
#3      SelectComponentBehaviors.focusCurrentOption (http://localhost:3000/assets/components/select.dart:197:28)
#4      _LocalInstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:534)
#5      _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:530)
#6      Component.behave.<anonymous closure> (package:nest_ui/component.dart:99:12)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      Component.behave (package:nest_ui/component.dart:96:16)
#9      SelectComponent.focusNextOption (http://localhost:3000/assets/components/select.dart:107:10)
#10     SelectComponent.SelectComponent.<anonymous closure> (http://localhost:3000/assets/components/select.dart:41:27)
```

Dart VM version: 1.18.0, Dartium.

**Comment by zoechi** [comment]
Why do you think this is a bug? 
To reproduce: https://dartpad.dartlang.org/4194b74b90e6fe49ed061b7b82bee0a3

**Comment by snitko** [comment]
You're using `scrollTop`. Change that to `scroll(0, 150)` for example you'll see the following error in that very same dartpad: `The method 'scroll' is not defined for the class 'Element'.`, even though the method is there in the documentation: https://api.dartlang.org/stable/1.18.0/dart-html/Element/scroll.html

**Comment by alan-knight** [comment]
This is a bug. There shouldn't be a method named scroll, it should be scrollTo according to the IDL for the Dartium version. But neither of them is listed in MDN, and neither of them seems to exist in JS in Chrome 52. So probably the right answer is to not use them.

For Window.scroll we suppress the two variations (one with an options object, the other with two numbers) and have a single one that takes three arguments. We're not doing that for the version on Element. But it looks like rolling Dartium might just delete those methods anyway.

**Comment by alan-knight** [comment]
Also, most of these are behind a RuntimeEnabled flag in the IDL, so they probably shouldn't be included. The Window.scroll with only two numbers seems to be the only one that you could expect to work in a browser.

**Comment by alan-knight** [comment]
See also #24582
