### ISSUE TITLE
Strong mode error when constant has inferred type parameter bound

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26993]
The following code:
```dart
    class C<T extends num> {
      final T x;
      const C(this.x);
    }
    void f() {
      const x = const C(0);
    }
```
Generates the strong mode error `The object type 'C<num>' cannot be assigned to a variable of type 'C<int>'`.  The problem may be worked around by specifying the type explicitly, e.g. `const x = const C<int>(0);`, or `const x = const C<num>(0);`.

**Comment by zoechi** [comment]
Looks like a dup of #/26912

**Comment by jmesserly** [comment]
good catch. that's bonkers. It looks like an early stage of inference concluded `C<int>` which is correct, and then something later on blew that away and replaced it with the implicit `C<num>` instantiation. Off hand I have no idea what could cause that. Did it happen in an editing scenario or just straight up CLI?

One other guess is we're setting the inferred type in one place in the AST but not in some other place. For InstanceCreationExpression the type ends up in a bunch of places, so maybe there's some inconsistency in the resulting AST leading to some code to see one type and some other code to see a different type.

**Comment by jmesserly** [comment]
BTW, one way to eliminate a lot of these would be to refactor InstanceCreationExpression so it looks more like the other generic function/method nodes. If we could handle things more uniformly, it's less likely we'd hit unique bugs in constructors compared with generic functions.

**Comment by jmesserly** [comment]
@stereotype441 ... so it looks like this message is a hint, not a strong mode error? Running your repro I get:
```
[hint] The value of the local variable 'x' is not used
[info] The object type 'C<num>' cannot be assigned to a variable of type 'C<int>' 
```
if so, this looks like the typical issue we get where the propagated types/hint system does not have as much info as Strong Mode's inference.

**Comment by jmesserly** [comment]
(still good to fix, but not as scary as I thought, at least we aren't rejecting valid code or getting corrupted types in our data structures)

**Comment by jmesserly** [comment]
Strangely I do see an error when I write it as a test case: VARIABLE_TYPE_MISMATCH. It comes from constant evaluation. Perhaps constant evaluation will need to take into account inference? If so it's strange we didn't see this before with downwards inference. Unclear yet what's going on.

**Comment by jmesserly** [comment]
Got it. We need to update the static element for the InstanceCreationExpression to take into account the inferred type argument. Prescient comment `// TODO(jmesserly): should we fix up the staticElement as well?` ... doh :)
