### ISSUE TITLE
base/OWNERS file format differs from what is used internally

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#27008]
This is part of the flutter code and gets pulled in through DEPS.

This causes a conflict when we try to do the internal sdk push. Can this file be renamed or something to make the process smooth?

fyi @dgrove, @a-siva

**Comment by keertip** [comment]
base/OWNERS 
    base/allocator/OWNERS 
    base/android/OWNERS 
    base/android/java/src/org/chromium/base/OWNERS 
    base/debug/OWNERS 
    base/files/OWNERS 
    base/i18n/OWNERS 
    base/ios/OWNERS 
    base/mac/OWNERS 
    base/memory/OWNERS 
    base/metrics/OWNERS 
    base/numerics/OWNERS 
    base/prefs/OWNERS 
    base/strings/OWNERS 
    base/test/OWNERS 
    base/test/android/OWNERS 
    base/test/expectations/OWNERS 
    base/test/ios/OWNERS 
    base/third_party/nspr/OWNERS 
    base/third_party/superfasthash/OWNERS 
    base/threading/OWNERS 
    base/trace_event/OWNERS 
    base/win/OWNERS 
    build/OWNERS 
    build/android/OWNERS 
    build/android/buildbot/OWNERS 
    build/android/lint/OWNERS 
    build/android/pylib/OWNERS 
    build/android/pylib/device/OWNERS 
    build/android/pylib/gtest/filter/OWNERS 
    build/config/OWNERS 
    build/config/android/OWNERS 
    build/git-hooks/OWNERS 
    build/ios/OWNERS 
    build/linux/OWNERS 
    build/mac/OWNERS 
    build/sanitizers/OWNERS 
    build/slave/OWNERS 
    build/toolchain/OWNERS 
    buildtools/checkdeps/OWNERS 
    buildtools/clang_format/OWNERS 
    buildtools/third_party/libc++/OWNERS 
    buildtools/third_party/libc++abi/OWNERS

**Comment by johnmccutchan** [comment]
@keertip Is this still an issue?

**Comment by dgrove** [comment]
This (for both OWNERS and BUILD) was fixed with a small bit of scripting.
