### ISSUE TITLE
DDC's sdk JS needs to be included in the sdk

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27001]
it looks like maybe we could do this in utils/dartdevc/dartdevc.gyp, but I don't know how to do anything in GYP

**Comment by jmesserly** [comment]
@vsmenon any ideas here? we need to copy dart_library.js and dart_sdk.js so they're available and match the version of DDC in the DEPS file

**Comment by jmesserly** [comment]
btw, thanks to @nex3 for finding this :)

**Comment by vsmenon** [comment]
@jakemac53 @sigmundch 

We should probably copy everything under `lib/js`.

**Comment by sigmundch** [comment]
2 ideas: you can put the files directly somewhere under `sdk/_internal/*` like we do with `js_runtime` for dart2js, or you can use gyp/GN to copy the files. The gyp/GN rule would be similar to what the analyzer folks did to generate strong.sum under the sdk. For example, see

https://github.com/dart-lang/sdk/blob/bb02e814dc09b7b718192638da5c58fbbd2e2216/utils/dartanalyzer/dartanalyzer.gyp#L51

**Comment by vsmenon** [comment]
Here's CL:

https://codereview.chromium.org/2416783005/

**Comment by nex3** [comment]
What's the intended process for users to find and use these sources?

**Comment by vsmenon** [comment]
See related in #27607
