### ISSUE TITLE
HOT RELOAD: Rename reload bots

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27005]
Assuming I understand what each bot is running today, they should be renamed as follows:

vm-linux-debug-x64-live-reload-be -> vm-linux-debug-x64-reload-be
vm-linux-debug-x64-stress-reload-be -> vm-linux-debug-x64-reload-rollback-be

vm-linux-release-x64-live-reload-be -> vm-linux-release-x64-reload-be
vm-linux-release-x64-stress-reload-be -> vm-linux-release-x64-reload-rollback-be

**Comment by johnmccutchan** [comment]
@rmacnak-google FYI

**Comment by johnmccutchan** [comment]
*ping*

**Comment by whesse** [comment]
Done.

**Comment by johnmccutchan** [comment]
Thanks Bill!
