### ISSUE TITLE
Requesting coverage data from a Flutter app uses too much memory

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#27010]
Requesting full isolate coverage data from a Flutter app uses too much memory and causes the app to be killed.

@kaiyuanw ran into this trying do a multi-device test framework. With an iPhone 6 and an Nexus 9, the Nexus 9 can back with data but the iPhone 6 got killed for using too much memory.

**Comment by turnidge** [comment]
@rmacnak-google - I see you made a commit that references this.  Can we close this now?
