### ISSUE TITLE
`polymer_interop` doesn't work with analyzer ^0.27.3

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#27012]
See  https://github.com/dart-lang/polymer_interop/issues/44 don't know if it is a `polymer_interop` ora an `analyzer` issue.

**Comment by bwilkerson** [comment]
@jakemac53 Is this related to the work you've been doing recently on transformer support?

**Comment by jakemac53** [comment]
I haven't done any work on these transformers recently, everything seems fine with analyzer 0.24.0 though which is what I get if I pub upgrade on `polymer_interop`.

Fwiw the polymer_interop package doesn't directly use analyzer at all, this seems to be coming from one of the transformers. Closing in favor of dart-lang/polymer_interop#44.
