### ISSUE TITLE
Error message "Relative paths for dart extensions are not supported" can be confusing

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#27014]
In 6fd8fd79875ec2869b7861b51bafeda592311d58 the error message "Relative paths for dart extensions are not supported" was introduced. I found it misleading as first I thought that the paths had to be absolute (the opposite of relative) - which did not make much sense.

As far as I can see it has to be a very particular relative path.

/cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@sgjesse My commit did not introduce the message (I copied it from somewhere under bin/ probably dartutils.cc). I may have made a mistake when incorporating it though. Please feel free to change this code.

**Comment by zanderso** [comment]
I've updated the error message to match what the VM allows here: https://github.com/dart-lang/sdk/commit/b990bc37948b750c4f6985a8575adae4aaee1dee
