### ISSUE TITLE
Analyzer "build mode" should detect unsafe use of a source file in multiple build units

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27025]
DDC requires that each source file be compiled into exactly one build unit, otherwise mysterious behaviors can result.  In a modular build system (e.g. one constructed using Bazel using build mode), the analyzer should be able to detect violations of this requirement by noting it has been passed multiple summaries that mention the same source file.

**Comment by vsmenon** [comment]
I just hit this internally.  How hard would it be to fix at this level?

@jakemac53

**Comment by jakemac53** [comment]
The dart_ddc_bundle rule does have an option to do this check `check_duplicate_srcs`, but its not enabled by default.

**Comment by vsmenon** [comment]
What happens if we turn it on?  Are things breaking?
