### ISSUE TITLE
Please merge 508dbbe1c9056b76f3317fcea79cc63815df167c to dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27024]
This rolls dev_compiler to 9cc982b90f57c6132f648b0041c0b03bd23fcbfc in DEPS
This is needed by internal users.

**Comment by whesse** [comment]
I had to cherry-pick all the auto-updates to DEPS, to make them apply cleanly:
8230749e116805bba2aee62321815b0b3a5526cb 
eb2b2bcda9c86052eac06f3561ce2e79cc338e0e 
3d58d8a7d801fafd71bea8e8556049ba61a4e092
 91d079b7cf8782993d44e7475b51dd46d7c49e2a
 508dbbe1c9056b76f3317fcea79cc63815df167c

Merged in 1.19.0-dev.2.3
