### ISSUE TITLE
No code completion in import with no end-of-line marker

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27020]
Create a Dart file with the following content:

```
import '

```

Requesting completions after the quote will produce a reasonable list. Now remove the blank line and request completions. It now reports that there are no suggestions.

@jwren @danrubel

**Comment by DanTup** [comment]
I don't think it's specifically end-of-line marker; adding any character after the cursor position causes the completion to work:

```
// In all cases, cursor is after the apostrophe when completion invoked:
import ' <-- fails
import '' <-- works
import 'a <-- works
import '\n <-- works
```

**Comment by DanTup** [comment]
FYI - this seems to affect completion for `part"..."` too.

**Comment by DanTup** [comment]
Actually, it's slightly different with part - a closing quote doesn't fix the issue like it does for import:

```dart
import "" // works
part "" // fails
```
