### ISSUE TITLE
(analysis.getNavigation) startLine/startColumn are 0 for SDK files

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27035]
From @DanTup:

I'm implementing "Go To Definition" and I've noticed in the results that the startLine/startColumn is not provided for files in the SDK (offset is provided, so I presume this data is known/can be calculated).

```
SND: {"id":"7","method":"analysis.getNavigation","params":{"file":"m:\\Coding\\Applications\\NewsWoWBot\\lib\\twitter_api.dart","offset":974,"length":0}}
RCV: {"id":"7","result":{"files":["M:\\Apps\\Dart\\lib\\core\\uri.dart"],"targets":[{"kind":"METHOD","fileIndex":0,"offset":11895,"length":5,"startLine":0,"startColumn":0}],"regions":[{"offset":970,"length":5,"targets":[0]}]}}
```

**Comment by scheglov** [comment]
[First step](https://codereview.chromium.org/2223113002) toward solution - add line information into summaries.

**Comment by scheglov** [comment]
Fixed.

https://github.com/dart-lang/sdk/commit/43fef756ae79b614ad6ff87995430d5059d51626

**Comment by DanTup** [comment]
Excellent, thanks!
