### ISSUE TITLE
Pub build in production mode breaks

### ISSUE THREAD

**Issue by AlexNPavel** [dart-lang/sdk#27030]
Hello, I've recently been having an issue with the pub build command when run in production. I was testing my project using pub serve and everything was fine until I ran a pub build and the code broke in one spot. I'm not 100% sure what went wrong, but my code would not work correctly until I ran pub build in debug mode (pub build --mode debug). My code is a polymer project and the break happens in a spot where I'm not really sure what gets triggered. From what I can tell, what seems to be happening is that an iron-signal that I am firing doesn't get caught correctly when my project is built in production mode. You can see the offending code here: https://github.com/AlexNPavel/dartrix/tree/317e857996877dc3af578bcce52b25bca78873bc

I am currently hosting the debug mode version of the output through GitHub pages, but this is obviously not ideal and must be fixed. 

Note: My dart SDK version is 1.18.0 (the latest version in Arch Linux).

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/pub#1439

**Comment by zoechi** [comment]
I'd expect this to be a Polymer-dart issue instead of a pub issue.

**Comment by mit-mit** [comment]
Good point @zoechi, a was probably too fast on the trigger.

**Comment by AlexNPavel** [comment]
Dart on Arch Linux has been updated to v1.19.0 and after that update, I can build my app in production mode without anything breaking. Thus, I believe the issue is resolved.

**Comment by AlexNPavel** [comment]
Actually, it's still occuring, but I think I found the bug. I have no idea if this is a polymer or dart bug, so I'll just reopen this issue for now.
It seems that on the initial load, the app works fine and renders everything correctly. However, on a subsequent load, it will not process everything correctly. If you clear the cache and reopen the app, it works fine again. I have a working example of the broken code here: https://dartrix.alexpavel.com/

I'm not sure if this is a dart, polymerdart, or potentially chrome bug (note that it doesn't work in firefox yet, you must use chrome for the site to work).

**Comment by AlexNPavel** [comment]
The broken version of the site has moved to https://dartrix-test.alexpavel.com. A working version (built in debug mode) is now on https://dartrix.alexpavel.com.
