### ISSUE TITLE
throw and ?? are non-associative

### ISSUE THREAD

**Issue by elaru** [dart-lang/sdk#27031]
```
print(x ?? throw 'something');
```
yields an _unexpected token_ error in analyzer and Dart VM, but bot of these work fine:
```
print(x ?? (throw 'something'));
print(x ? x : throw 'something');
```
I understand why `throw` is not associative with regular infix operators, but this looks wrong to me.

Cheers,
Philipp

**Comment by lrhn** [comment]
The grammar production for `??` is: 
```
ifNullExpression:
  logicalOrExpression (‘??’ logicalOrExpression)*
```
and `throw` is an `expression`:
```
expression:
    assignableExpression assignmentOperator expression |
    conditionalExpression cascadeSection* |
    throwExpression
    ;
```
which means that it's not producable by `logicalOrExpression`. So, the analyzer and VM are both correct that `e1 ?? throw e2` is invalid syntax.

**Comment by elaru** [comment]
My question aimed more at the reasoning why the grammar wouldn't allow the `throw` expression in that place, but now it's obvious that throw isn't a logicalOr. Thanks!
