### ISSUE TITLE
Pub Tar issue

### ISSUE THREAD

**Issue by esnortel** [dart-lang/sdk#27039]
1.17.1 added in a change for cross-platform issues with tar (https://github.com/dart-lang/pub/issues/1411), unfortunately the ustar format doesn't handle large user ids. We use Active Directory and the user ids for our developers are large (876765912), the tar command errors out when this happens. stderr is not caught and there is no evidence that the command fails until the tar file is examined and is unreadable.

The error message that tar generates is
tar: catalina.out: Numeric user ID too largeNumeric group ID too large

pub version - 1.17.1
platform - mac (10.11.5), centos 7, windows

**Comment by mit-mit** [comment]
This issue was moved to dart-lang/pub#1438
