### ISSUE TITLE
Allow config-specific import configurations to be set/evaluated for back-ends

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27045]
Currently analyzer's implementation of config-specific imports parses the extended syntax of the import statement and then drops the "configuration" part on the floor.  This is sufficient for use of the analyzer within an IDE, since in principle all of the config-specific variants of an import should expose the same API.  However, it means that when analyzer is used as a front end for a compiler (as it is for DDC), config-specific imports do not take effect.

To allow back-ends to support config-specific imports, we need to provide a way for them to tell the analyzer what the configuration is, and have the analyzer take this into account when resolving the imports.

Note that this resolution logic needs to be written in such a way that it works both during normal resolution and during summary linking (so that AST-based summaries will be properly resolved, and so that summaries can be re-linked if/when the configuration changes).

**Comment by scheglov** [comment]
@bwilkerson is working on this as https://codereview.chromium.org/2345773003/ for normal resolution.

**Comment by scheglov** [comment]
The normal resolution case is done by @bwilkerson in https://github.com/dart-lang/sdk/commit/22040876bf78d8a13294990d198b48109b70473e.

**Comment by scheglov** [comment]
CL for selecting import/export URIs while resynthesizing.
https://codereview.chromium.org/2353433002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f5a616834ea322eecfef4a0b705b9a195d8204dd
