### ISSUE TITLE
Account for the syntax of config-specific imports in unlinked summaries

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27044]
Unlinked summaries currently don't encode the "configuration" part of the syntax for configuration-specific imports.  We need to add this information before we'll be able to support evaluating configurations in the analyzer, otherwise we won't be able to re-link the summaries properly if the configuration changes.  (Nor will we be able to link them properly in the first place, when using AST-based summaries).

**Comment by scheglov** [comment]
https://codereview.chromium.org/2342893002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/cfe56b9241f7ef1e8acecd64f05c4254a667cd02
