### ISSUE TITLE
Change builders to not require glibc 2.16

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#27048]
When we rolled BoringSSL in https://github.com/dart-lang/sdk/commit/fc42f03c1341ace95408ad107c60d6a2935a7ce9, we ended up requiring glibc 2.16 which for linux users means upgrading to trusty. 

Per discussion in https://github.com/flutter/flutter/pull/5295, this does not work for Flutter. For example, this makes it really hard to build flutter apps in Travis.

We should change the builders to compile against an older version of glibc so that trusty is not required.

**Comment by mit-mit** [comment]
This blocks 1.19

**Comment by kevmoo** [comment]
Fixing this will also (hopefully) fix our use of Travis - another plus.

**Comment by mit-mit** [comment]
Looking at the bots, this seems to be working now, closing

**Comment by kevmoo** [comment]
I ran a angular2 build on travis w/ this commit – https://travis-ci.org/dart-lang/angular2/jobs/151294698

Also looks good 😄
