### ISSUE TITLE
Connection terminated during handshake

### ISSUE THREAD

**Issue by emandere** [dart-lang/sdk#27057]
I am getting an error 'Connection Terminated during handshake' when running pub get when starting up an application using docker. I  have attached a trace file
[output.txt](https://github.com/dart-lang/sdk/files/414201/output.txt)

**Comment by nex3** [comment]
This just indicates a networking issue. It's probably temporary, but if you're seeing it consistently, you may have a firewall blocking connections to pub.dartlang.org.
