### ISSUE TITLE
Mixins do not inherit call from an implemented class

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#27058]
## Problem:
If you have a mixin that implements a class, that has `call` defined, you are not able to call the object. Other methods work including manually calling the `call()` method on the object. 

## Dartpad with repro:
https://dartpad.dartlang.org/77ad167d1f94e4e8f42f1c21f547ac28

**Comment by greglittlefield-wf** [comment]
Is this a dupe of https://github.com/dart-lang/sdk/issues/26509?

**Comment by jacehensley-wf** [comment]
Yup, closing in favor of the original.
