### ISSUE TITLE
(Request) Add a getOutline method (or similar) to the analysis service

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27064]
Currently you can only get outlines via subscription and not on-demand. Our [current implementation](https://github.com/Dart-Code/Dart-Code/pull/45) subscribes when required, gets the data, then unsubscribes. This doesn't match the VS Code API very well (which just asks us for the data when the user invokes the list/search). I'm aware VS Code might not be using this the same way as other IDEs (that often show all the outline while the file is open) so this request might not be all that useful for others.

While we could subscribe at file open and keep all this data in memory, it seems a bit wasteful if the server already also has it in-memory. It would be great if we could request this (like we can for other things, like hovers).

**Comment by bwilkerson** [comment]
Given that you only need this information when the user explicitly requests it, it makes sense to have an explicit request for it. It sounds, though, like you could get by for a (hopefully) short time by using the notification, so I didn't mark this as a high priority issue.

**Comment by DanTup** [comment]
Yeah, I'd agree. Our current implementation isn't too bad; we do use all the data we need and it comes through quick.

(#27062 would be much more beneficial of the two).

**Comment by pq** [comment]
Hey @DanTup , in a round-up of old issues I see this one but wonder where we are on the ask. Should we keep this ticket open?  Anecdotally, your current implementation cointinues to work great! 🎉

**Comment by DanTup** [comment]
I'm not fussed on this now. At the time I was trying hard not to maintain any state in the editor as it felt redundant, but I ended up having to do it for a couple of things; so we just stash outlines (and a few others) statically now and allow the extension to read it at any time (there were some races where we try to read them before we've received them, but I think they're fixed now by just checking in a small loop for up to a few seconds if we really need them and they're not here yet).

So, since probably nobody wanted this except me and I don't need it anymore, we can close.
