### ISSUE TITLE
The http server in the test scripts requires a package root

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27065]
The new package spec file (.packages) format is not handled by the test http server.

This should break dartium testing without dart2js, but not other platforms.

Add support to the server for the .packages file.

**Comment by kevmoo** [comment]
@nex3 make a package that builds on shelf to do this - https://github.com/dart-lang/pub_server

Is our test http server written in Dart?

**Comment by whesse** [comment]
@terrylucas @alan-knight 
The removal of the build and test package-root has landed, and many dartium tests are broken because of this.  I can work on this immediately, but can't guarantee a fix until monday.  I'd like to leave the package-root change landed, if you don't mind too much, and I'll try fixing it tonight.  What do you think?

**Comment by whesse** [comment]
Fixed in https://codereview.chromium.org/2354863002/ and https://codereview.chromium.org/2347423003/
