### ISSUE TITLE
Internal fragmentation in _GrowableList's backing _List

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27067]
The backing _List uses 3 words in the non-variable part (header, type parameter, length).
Since objects are allocated in multiples of 2 words, the variable part is only fully used for odd lengths.
_GrowableList could avoid wasting the last word by allocating a backing list in odd lengths.

I hacked the code to put _capacity_`| 1` in several places to make the length odd.
In a large dart2js compile, this reduced the number of _List allocations by 3% (I assume due to the growth pattern 3 - 7 - 15 - 31 instead of  2 - 4 - 8 - 16). Actual resident footprint after GC is reduced by 0.1%

**Comment by ErikCorryGoogle** [comment]
This was fixed as part of https://codereview.chromium.org/2949803002/ "New growth strategy for growable arrays" committed as ec963f028198ec5871840491ba78b096ad0b819
