### ISSUE TITLE
Cannot access properties of GamepadButton after dart2js

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#27073]
dart2js seems to generate incorrect code for accessing `pressed` and `value` of `GamepadButton`.

**How to reproduce**
Run this code (and a html with `<div id="output"></div>`) and press a button on a connected gamepad:
```dart
import 'dart:html';

main() async {
  querySelector('#output').text = 'waiting for gamepadconnected';
  window.on['gamepadconnected'].listen((GamepadEvent event) {
    var result = isPressed(event.gamepad.buttons[0]);
    querySelector('#output').text =
        'Buttone X pressed (gamepadconnected): $result';
  });

  while (true) {
    await window.animationFrame;
    window.navigator.getGamepads().forEach((gamepad) {
      if (gamepad != null) {
        var result = isPressed(gamepad.buttons[0]);
        querySelector('#output').text =
            'Buttone X pressed (loop): $result';
      }
    });
  }
}

bool isPressed(GamepadButton button) {
  try {
    return button.pressed;
  } catch (e) {
    querySelector('#output').text = e;
    throw e;
  }
}
```

**Expected result**
Buttone X pressed (loop): false
or 
Buttone X pressed (loop): true

**Result in Chrome and Firefox after dart2js**
NoSuchMethodError: method not found: 'get$pressed' (button.get$pressed is not a function)

**Additional Info**
Using the console and executing `button.pressed` (and `button.value`) works just fine. Doesn't look like there is a need for `get$` when generating the JS code.

**Comment by floitschG** [comment]
@rakudrama: if this is a html-library bug, please reassign.
