### ISSUE TITLE
Improve documentation of refactoring errors (RefactoringProblemSeverity)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27078]
In the analysis server docs there isn't a lot of info on `RefactoringProblemSeverity`. Specifically, it's not clear:

- What types of things will go into each category
- Which categories should we abort refactoring on and which are safe to go ahead (eg. should a warning be a reason to abort or not? we're assuming yes for now)

**Comment by scheglov** [comment]
https://codereview.chromium.org/2312073003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/7343da76bafb16f0a0be21d801e5be8890d4a62b
