### ISSUE TITLE
Allow abstract getters/setters to override fields

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27070]
I recently tried to write some code like this:

``` dart
    class Base {
      bool b = false;
    }

    abstract class Mixin {
      bool get b;
      void f() {
        useValueOf(b);
      }
    }

    class Derived extends Base with Mixin {
      void g() {
        b = true;
        f();
      }
    }
```

This resulted in a strong mode error, since the abstract getter `bool get b` technically overrides the field `bool b = false`.

I think in this particular case it would be ok to permit this, since the purpose of the error is to ensure that DDC can safely compile code that accesses the field directly, without danger that a derived class will override the field with getters/setters.  In this case there's no danger, because the "overriding" getter is abstract, so code in Derived that refers to `b` is still referring to the field.

Would it be possible to change the rule from "fields can't be overridden" to "fields can't be concretely overridden"?

**Comment by srawlins** [comment]
The dartanalyzer no longer produces an error for the above code:

```
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ cat 27070.dart 
class Base {
      bool b = false;
    }

    abstract class Mixin {
      bool get b;
      void f() {
        useValueOf(b);
      }

      useValueOf(bool bb) { }
    }

    class Derived extends Base with Mixin {
      void g() {
        b = true;
        f();
      }
    }
$ dartanalyzer --preview-dart-2 27070.dart 
Analyzing 27070.dart...
No issues found!
$ dartanalyzer --preview-dart-2 --strong 27070.dart 
Analyzing 27070.dart...
No issues found!
