### ISSUE TITLE
HOT RELOAD: Possibly class confusion after many reloads

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27077]
A generic tracking issue for a bug that @Hixie might be running into where the VM becomes confused about classes after many reloads.

**Comment by johnmccutchan** [comment]
@Hixie Could you share any information you have around this issue?

**Comment by Hixie** [comment]
Not sure. I've twice seen an exception saying that some class I didn't expect did not have some method or other. It was the same class both times. I don't recall what the class was. I do recall that I couldn't see any way for the variable in question to end up containing that class. I'll let you know more if I see it again.

**Comment by johnmccutchan** [comment]
@Hixie I suspect we have some kind of bug here it might actually be related to the cannot forward VM heap object bug.

**Comment by johnmccutchan** [comment]
Possibly related: https://github.com/dart-lang/sdk/issues/27059

**Comment by Hixie** [comment]
I just saw it again. It was my first change. The class I unexpectedly saw was "LayoutId", which is a Flutter class.

It happened after I renamed a class's field. I then restarted the app entirely, did one no-op hot reload successfully, did nothing except rename a field, hot reloaded, and got an exception that didn't make sense.

**Comment by johnmccutchan** [comment]
@Hixie Thanks, that's super helpful.

**Comment by johnmccutchan** [comment]
Reproduction steps:

1. $ flutter run --hot
1. \<perform hot reload\>
1. rename a field in a class that is already instantiated
3. \<perform hot reload\>

**Comment by Hixie** [comment]
Steps to repro:

Run Flutter Gallery from tip of tree in hot mode.
Open `//flutter/packages/flutter/lib/src/widgets/image.dart`
Do a global search and replace in that file to replace `_imageInfo` with `_imageData`. This should have no effect, as the reassemble should cause the image data to get reloaded synchronously from the cache.

Instead, this happens:
```
I/flutter : ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during a service extension callback for "ext.flutter.reassemble":
I/flutter : type 'LayoutId' is not a subtype of type 'State<StatefulWidget>' of 'function result' where
I/flutter :   LayoutId is from package:flutter/src/widgets/basic.dart
I/flutter :   CustomMultiChildLayout is from package:flutter/src/widgets/basic.dart
I/flutter :   State is from package:flutter/src/widgets/framework.dart
I/flutter :   StatefulWidget is from package:flutter/src/widgets/framework.dart
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      StatefulElement.state (package:flutter/src/widgets/framework.dart:2080:38)
I/flutter : #1      StatefulElement._reassemble (package:flutter/src/widgets/framework.dart:2085:16)
I/flutter : #2      Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:1361:13)
I/flutter : #3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:2029:14)
I/flutter : #4      Element._reassemble (package:flutter/src/widgets/framework.dart:1360:5)
I/flutter : #5      BuildableElement._reassemble (package:flutter/src/widgets/framework.dart:1953:22)
I/flutter : #6      _ProxyElement._reassemble (package:flutter/src/widgets/framework.dart:2192:22)
I/flutter : #7      Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:1361:13)
I/flutter : #8      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2741:16)
I/flutter : #9      Element._reassemble (package:flutter/src/widgets/framework.dart:1360:5)
I/flutter : #10     BuildableElement._reassemble (package:flutter/src/widgets/framework.dart:1953:22)
...
Reassembling application failed.
```
