### ISSUE TITLE
HOT RELOAD: Develop fuzzer testing strategy

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27076]
We should have a pair (debug-x64, release-x64) of bots that runs the test under fuzzing mutations

The mutations must result in a successful reload or reject:
- We need to develop a class of edits that can be done to the source base under reload (while still letting the test succeed)
- We should develop a class of edits that will lead to a rejected reload (while still letting the test succeed)

At each reload stress test point, randomly apply one of the edits and continue.

**Comment by johnmccutchan** [comment]
@hixie FYI

**Comment by Hixie** [comment]
A particular test that would be interesting would be mutating the source in a random (possibly not valid) way and then mutating it back, and seeing if the code still behaves as it did before (and in particular, that there's no crash or unexpected exception). If you log what changes you made, you'd be able to then reproduce the sequence of steps that led to a failure.

**Comment by mraleph** [comment]
Assuming that this is stale because no work has been happening or slated to happen.
