### ISSUE TITLE
Linter: report on missing trailing commas

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#27086]
Now that the formatter respects trailing commas, our users would like to add a lint to report when a trailing comma is missing. This will help enforce trailing commas in the build system.

**Comment by pq** [comment]
@sethladd : Are you proposing a lint that flags ALL places where trailing commas are permitted?

**Comment by dvdwasibi** [comment]
+1

We are using the formatter and linter as precommit checks in our build system for our Flutter application.

**Comment by lrhn** [comment]
I don't think you want *all* possible trailing commas. That would be every function declaration and every function call with at least one argument, e.g., `int.parse("42",)`.

So, you need to specify in which places you *do* want to require a trailing comma.
Maybe "every function declaration or invocation where the closing parenthesis is not on the same line as the final argument/parameter"? And you probably want the comma to be on the same line as the (end of) the last argument, not, say:
```
foo(
  42
,);
```

And you definitely also want to restrict that lint to your own code, because library code will not follow that format.

**Comment by bwilkerson** [comment]
The auto-format doc (https://github.com/flutter/flutter/wiki/Early-Access:-Auto-Formatting) says:

    The rule for adding a trailing comma is simple. Always add a trailing comma at the end
    of a parameter list in functions, methods, and constructors where you care about
    keeping the formatting you crafted.

So should the lint only require trailing commas in parameter lists? (Of course, I have no idea how to statically determine whether "you care about keeping the formatting you crafted", so there might be a lot of false positives.)

**Comment by dvdwasibi** [comment]
Yeah, I was thinking commas for parameter lists. 

cc @jxson & @yyoon

**Comment by pq** [comment]
Paging @Hixie! 😉

**Comment by lrhn** [comment]
Looking at the example in the auto-formatter, I count eight places where a trailing comma could be added, but wasn't (vs. six that were added). If the analyzer should tell you where you need commas, and not give lots of false positives, you need to explain very precisely where you want them and where you don't. :)

**Comment by Hixie** [comment]
I don't think a lint makes sense. You're either using an autoformatter or you're not. If you're not, then you don't care either way. If you are, then the trailing comma will immediately change the format and so by the time the analyzer runs it'll have no way to know if it's a "good" trailing comma or not.

The only possible use case I can see is for wanting to be told when the formatter is going to change the format but would not if there was a trailing comma, or vice versa, for when you are transitioning a codebase from not using the formatter to using it. But that, I think, is an issue for the formatter, not the linter.

**Comment by dvdwasibi** [comment]
Just talked with @yyoon and we came to the conclusion that this is probably something that has to be done/checked by humans.

@sethladd Feel free to close the issue if no other team needs this.

**Comment by sethladd** [comment]
Thanks for the follow-up!
