### ISSUE TITLE
Linter should allow '$' in camel case identifiers

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#27080]
The enum class [generator](https://github.com/google/enum_class.dart#enum-classes-for-dart) uses _$ as a prefix for generated constants and methods. This conflicts with the lints [constant_identifier_names](https://dart-lang.github.io/linter/lints/constant_identifier_names.html) and [non_constant_identifier_names](https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html)

It seems useful to be able to use '$' to signify a special identifier like this.

**Comment by kevmoo** [comment]
@pq should be moved to the linter repo?

https://github-issue-mover.appspot.com/

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#287
