### ISSUE TITLE
Switching to the fast-startup emitter by default

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#27089]
This is a tracking bug for everything that needs to happen before we can turn on `--fast-startup` by default:
- [x] bot coverage
  - [x] bots can run with the flag (see #27085)
  - [x] triage test failures
- [x] js-interop
- [x] custom elements
- [x] dump-info
- [ ] document the `--fast-startup` flag
- [ ] dart:mirrors

/cc @rakudrama @jacob314

**Comment by floitschG** [comment]
/sub.

**Comment by sigmundch** [comment]
quick update: triagging in progress... 

See: https://github.com/dart-lang/sdk/commit/fbd56da2f0e3d2cf996c471c14038ff8d7fc5daa for the tests that are pending to get js-interop working.

**Comment by sigmundch** [comment]
js-interop support added in https://github.com/dart-lang/sdk/commit/ee42a0a0aa078577915401eafee465d977076b95

**Comment by sigmundch** [comment]
and custom element support fixed in 997581ccecec70d8c91ad468c4c2a001f334e870

**Comment by sigmundch** [comment]
dump-info was added long ago at https://github.com/dart-lang/sdk/commit/3e557730ac8d8d0c75e871c7fcacf9b55e0e611a, we do not plan to add support for dart:mirrors here, so the only thing missing is to document the flag.

**Comment by leonsenft** [comment]
@sigmundch Didn't this land recently?

**Comment by sigmundch** [comment]
Yes! thanks for pinging, this is now complete! woo hoo!
