### ISSUE TITLE
Analyzer's parser should allow `const factory C() native "string"`

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#27082]
In `_parseConstructor` the Analyzer's parser signals an error when it sees `const` and `factory` without `external`.  In the Dart VM's core library implementation there are const factory constructors that are not external (thay have `NativeBody` bodies).

I'd like to use the Analyzer to parse these files, so I'd like the Analyzer to allow such constructors.  It should trust that the VM knows what it's doing with native function bodies.

Note that there is another check later in the function that if `const` is seen then it is also an error to have a body.   This should also be changed to allow such constructors to have native function bodies.

In the longer-term we should change the VM's core library implementation to remove `native`, mark these `external`, and provide an annotation telling the VM how to find the implementation.

@lrhn

**Comment by kmillikin** [comment]
I'm currently patching the analyzer sources to work around this, but it would be great if I didn't have to.  My fix for this is:

```
diff --git a/pkg/analyzer/lib/src/generated/parser.dart b/pkg/analyzer/lib/src/generated/parser.dart
index d3f7475..89cd949 100644
--- a/pkg/analyzer/lib/src/generated/parser.dart
+++ b/pkg/analyzer/lib/src/generated/parser.dart
@@ -5576,7 +5527,8 @@ class Parser {
           true, ParserErrorCode.MISSING_FUNCTION_BODY, false);
       if (constKeyword != null &&
           factoryKeyword != null &&
-          externalKeyword == null) {
+          externalKeyword == null &&
+          body is! NativeFunctionBody) {
         _reportErrorForToken(ParserErrorCode.CONST_FACTORY, factoryKeyword);
       } else if (body is EmptyFunctionBody) {
         if (factoryKeyword != null &&
@@ -5586,7 +5538,7 @@ class Parser {
               ParserErrorCode.FACTORY_WITHOUT_BODY, factoryKeyword);
         }
       } else {
-        if (constKeyword != null) {
+        if (constKeyword != null && body is! NativeFunctionBody) {
           _reportErrorForNode(
               ParserErrorCode.CONST_CONSTRUCTOR_WITH_BODY, body);
         } else if (externalKeyword != null) {
```

**Comment by bwilkerson** [comment]
I think you should commit those changes to the main repo.

**Comment by kmillikin** [comment]
OK.  I didn't know if I was supposed to edit sources in `generated` :)

Take a look at https://codereview.chromium.org/2310883002/

**Comment by kmillikin** [comment]
This is fixed.
