### ISSUE TITLE
Add a "num1 ** num2" operator as a shortcut for pow(num1, num2)

### ISSUE THREAD

**Issue by Runemoro** [dart-lang/sdk#27081]
Adding an exponentiation operator, like `**` in python, would make code more readable and faster to type. The way it works right now, it's easier to type `x * x * x` (5 characters) instead of `pow(x, 3)` (8 characters).

Also, it makes more sense to use an operator rather than a function, since we usually use [infinix notation](https://en.wikipedia.org/wiki/Infix_notation) with exponentiation, as well as addition, subtraction, multiplication and division (we write a + b, a * b, a ^ b instead of sum(a, b), product(a, b), pow(a, b)).

**Comment by zoechi** [comment]
Dup of #1859
