### ISSUE TITLE
adding bot configurations for dart2js to cover `--fast-startup` 

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#27085]
@whesse - long ago @floitschG wrote a new emitter for dart2js. It seems promising to switch over to use this new emitter by default in the future, but before we do so we need to test it in our bots across all browsers.

The emitter is enabled by passing the `--fast-startup` option to dart2js. While we are in transition, we practically need to have full coverage of dart2js with and without the flag. Would it be possible to set this up?

/cc @rakudrama @jacob314

**Comment by whesse** [comment]
I have started working on this.

**Comment by sigmundch** [comment]
Thanks Bill, let me know if we can be of help!

**Comment by whesse** [comment]
Committed as a change to the buildbot recipe.  All new runs of all the dart2js builders should now include a --fast-startup step running all the tests with that option.  If there are failures, please mark them in the status files and file bugs for them, to turn the bots green again.  If things are working right, a variable $fast_startup in a status file expression should be true if the flag is passed in - check an example to be sure.

**Comment by sigmundch** [comment]
Awesome! Thanks so much Bill!

**Comment by sigmundch** [comment]
It appears that test.py fails if we try to give it `--fast-startup`. Have the changes to the testing scripts in the SDK repo landed as well?

**Comment by whesse** [comment]
Nope. I'll land them now.
