### ISSUE TITLE
failure in package:dart_style using a .packages file

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27095]
There seems to be a new failure in the dart_style package, when it is tested using the --no-package-symlinks option to pub.

https://github.com/dart-lang/dart_style/issues/521

**Comment by mit-mit** [comment]
Note that the option was renamed to --no-package-dir in https://github.com/dart-lang/sdk/commit/38dccc88ffa9ab190154a1f40b36d5ab0d3be728

**Comment by mit-mit** [comment]
Marking this as P1 -- we are hoping to make this the default configuration in 1.20.

**Comment by whesse** [comment]
Fixed in CL https://codereview.chromium.org/2252013002/

**Comment by whesse** [comment]
Fixed
