### ISSUE TITLE
failure in package:intl test using a .packages file

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27094]
A test seems to have started failing when we switched to using the package spec file

https://github.com/dart-lang/intl/issues/121

**Comment by mit-mit** [comment]
Note that the option was renamed to --no-package-dir in https://github.com/dart-lang/sdk/commit/38dccc88ffa9ab190154a1f40b36d5ab0d3be728

**Comment by mit-mit** [comment]
Marking this as P1 -- we are hoping to make this the default configuration in 1.20.

**Comment by whesse** [comment]
This does not reproduce locally.  I can try more to reproduce locally.  It does not look like a blocker for 1.19.

**Comment by mit-mit** [comment]
Lowering to P2. This won't block the release, but would be good to get some more certainty.

**Comment by whesse** [comment]
The failure has now disappeared on the buildbot, after 1.19.0-dev.7.0 was released.  Since it never reproduced locally, I'm closing the issue.
