### ISSUE TITLE
Can't call super.super

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27099]
We have RenderBox, which defines some basic features. One of the things it does is have a default behaviour for intrinsic dimensions (essentially return zero).

We have RenderShiftedBox, extending RenderBox, which implements a ton of logic for render boxes that have one child that is slightly shifted. One of the things RenderShiftedBox does is assume that your intrinsic dimensions come from your child.

We have RenderOverflowBox. It does everything RenderShiftedBox does, except that it wants to have a behaviour for intrinsic dimensions that is equal to RenderBox's behaviour.

So in RenderOverflowBox, we want to be able to implement the intrinsic dimensions by calling super.super's intrinsic dimension logic.

**Comment by lrhn** [comment]
The abstraction of a superclass is such that the subclass don't know, and can't know, how the superclass was declared. All it can see is the actual members exposed by the superclass and the total interfaces implemented. Whether a member is declared in the superclass itself or inherited from further up the chain is invisible.
That's a good thing. It means that it is *not* a breaking change to move a method from a subclass to a parent class or vice versa. You can insert intermediate classes in an inheritance chain without breaking anything.
If you allow a `super.super.foo` invocation, that abstraction is gone. It matters not just which methods a class has, but also where in its inheritance chain that method is defined.

No `super.super`!

In this case, I would see if `RenderOverflowBox` could be made to not extend `RenderShiftedBox` and instead make them both extend an abstact superclass that has all the things the two have in common, and not the things where they differ.
(In general, I'm always suspicious when a concrete class extends another concrete class. It's not always wrong, but it's a good hint that there might be a better model).

**Comment by Hixie** [comment]
RenderShiftedBox is abstract. It has 7 methods, most of which are used as-is by most of its concrete subclasses, though they all override something or other in there. It just happens that in this case, the behavior that RenderOverflowBox wants to override RenderShiftedBox with is also the behavior that its grandsuperclass already has. Not having super.super means we either have to use a mixin (not possible here because of https://github.com/dart-lang/sdk/issues/15101), or we have to have the base class expose this under two names just so one can be called directly (bad API design, people will end up calling the other name and thus miss the overrides in most cases) or we have to have code duplication.

By the way, I disagree that moving a method from a subclass to a parent or vice versa is not a breaking change. It's totally a breaking change, because it is a change to the parent so anyone inheriting from the parent would break. It's also a breaking change because it is a change to the subclass so anyone mixing that subclass in would break.

I similarly disagree that you can insert (non-empty) intermediate classes in an inheritance chain without breaking anything. For example, you'll break anyone who is mixing in the two classes on either side of the intermediate class and is expecting the result to be equal to inheriting from the subclass (they'll instead get an analyzer error saying that they're not implementing the members from the intermediate class).

**Comment by lrhn** [comment]
You *should* be able to split a class into two classes, like 
```dart
class C extends D {
  foo()...
  bar()...
}
```
into
```dart
class FooD extends D {
   foo()...
}
class C extends FooD {
   bar()...
}
```
without breaking any clients of `C` or `D`. 
It is true that you currently can't if someone uses `C` as a mixin, but that's bad. Mixins break class encapsulation because the superclass leaks. It sucks, and I hope we can fix that instead of breaking classes further.

Moving things to a public superclass is more questionable, because it does change the signature of the superclass, but it *should not* change anything for clients of the subclass. 
If the class is used as a mixin then it should be intended as a mixin, and then rules are (currently) different, but the author of the class knows that it's a mixin class.

**Comment by eernstg** [comment]
FYI, note that similar issues were discussed in https://github.com/dart-lang/sdk/issues/26194.

In short, if you want to have a class C containing mixins M1 and M2, both declaring a `foo` method, and the `foo` methods do not call super (so you can't just call the nearest one from C and get all of them executed), you can instead include mixins M1, M1aux, M2, M2aux where M1aux declares `.. fooM1(..) => super.foo(..)` and similarly for M2aux. The "helper mixins" M1aux and M2aux serve as renaming devices for M1.foo and M2.foo, and then C is free to call any or all of them under the new names fooM1 and fooM2.

**Comment by Hixie** [comment]
I just ran into another case of this.

I have a deep class hierarchy. It has an elaborate toString protocol. One of the classes wants to mix in an unrelated class that also implements toString. I want my subclass to call the supersuperclass' toString, bypassing the mixin's.

**Comment by lrhn** [comment]
Then make the superclass toString available through a different name.
Instead of 
```
class Foo extends Bar with Baz { toString() => super.super.toString(); }
``` 
do
```dart
class _ToStringRename { _toString() => super.toString(); }
class Foo extends Bar with _ToStringRename, Baz { toString() => super._toString(); }
```
This is no different from what you'd have to do if you wrote `Baz` directly as a subclass of `Foo`, and for some reason wanted to have a `toString` and be able to ignore it in further subclasses.

**Comment by Hixie** [comment]
In this case the Mixin was under my control, and I added a method:

```dart
   String superToString() => super.toString();
```

...and in the subclass I called `super.superToString()`.

But (a) I don't always control the mixin and (b) it seems pretty obvious to me that this is in no way better than just calling "super.super.toString".
