### ISSUE TITLE
Debian package builder is broken

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27105]
The builder that builds our linux debian packages (source packages and release packages) is broken since rolling BoringSSL.  I have installed a Debian Jessie chroot on it, to replace the Debian Wheezy chroot, but it isn't fully working yet.  This is needed to release stable 1.19, and to release any dev releases as .deb packages and docker files.  Highest priority for me, so it should be done by Monday Aug 22.

**Comment by whesse** [comment]
I think that I have fixed the problem, by mounting /proc in the chroot, as I should have done originally.  Now running it to see if it is working.

**Comment by mit-mit** [comment]
This was resolved.
