### ISSUE TITLE
Add VFS File.writeAsStringSync()

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27109]

**Comment by bwilkerson** [comment]
We should clean up existing uses of writeAsBytesSync. We also need to clean up MemoryResourceProvider, which currently has separate maps for string and byte content but doesn't keep them in sync. I think we want one map, and my guess is that we use strings more often than bytes.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2265593002/
