### ISSUE TITLE
Reference error in yielded function when running in js

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#27112]
Invoking a function yielded from another function can cause a reference error if the yielded function contains references that are not used elsewhere (my best interpretation of the issue) when run as js.

https://dartpad.dartlang.org/bbc3c826d299793e48b7d72d3b6bdd62

``` dart
main()  {
// This will throw 'Uncaught TypeError: str.toUpperCase$0 is not a function'
// unless the line below is outcommented
  // shout('rhubarb');
  yieldFunction().first('rhubarb');
}

Iterable<Function> yieldFunction() sync* {
  yield shout;
}

void shout(String str) {
  print(str.toUpperCase());
} 
```

**Comment by joshualitt** [comment]
This seems to be working now.
