### ISSUE TITLE
Future.then() inference does not work if there is `whenComplete()` invocation.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27113]
```dart
import 'dart:async';

class A {
  static Future<bool> myTest(Future<int> base) {
    return base.then((int value) {
      return value == 0;
    }).whenComplete(() {
      print('whenComplete');
    });
  }
}
```

This code causes `WARNING: Unsound implicit cast from Future<dynamic> to Future<bool> ([my_test] bin/test.dart:5)`.

The warning goes away if we remove the `whenComplete` invocation.

It seems to me that this `whenComplete` invocation should not change the return type. The documentation says that its return value is always ignored:

```dart
  /**
[cut]
   * The future returned by this call, `f`, will complete the same way
   * as this future unless an error occurs in the [action] call, or in
   * a [Future] returned by the [action] call. If the call to [action]
   * does not return a future, its return value is ignored.
[cut]
   * If the call to [action] returns a [Future], `f2`, then completion of
   * `f` is delayed until `f2` completes. If `f2` completes with
   * an error, that will be the result of `f` too. The value of `f2` is always
   * ignored.
[cut]
   */
  Future<T> whenComplete(action());
```

**Comment by keertip** [comment]
@leafpetersen

**Comment by jmesserly** [comment]
just curious, is this a regression?

**Comment by scheglov** [comment]
At least in some fashion yes, it is.
This code is warnings free when not in strong mode.
I don't know yet whether this is related to some recent changes to `Future`.

**Comment by jmesserly** [comment]
simplified repro:
```dart
import 'dart:async';
main() {
  Future<int> base;
  Future<bool> f = base.then((x) { return x == 0; }).whenComplete(() {});
  Future<bool> g = base.then((x) => x == 0).whenComplete(() {});
}
```
First one fails, second one works.

At least two things are going wrong here:
* we don't do downward inference on MethodInvocation targets
* upwards inference seems to work incorrectly when block+return is used

**Comment by scheglov** [comment]
Maybe one more case with missing upward inference for block+return, without `whenComplete`.

```
import 'dart:async';

class A {
  Future<int> base;
  Future<bool> get h {
    var ttt = base.then((int value) {
      return value == 0;
    });
    return ttt;
  }
}
```

**Comment by jmesserly** [comment]
> upwards inference seems to work incorrectly when block+return is used

ah, I see. If we're in a Future union context, we disable upwards inference from "return" completely. That's probably not right. Also the fact that we're trying to do inference from `dynamic | Future<dynamic>` is probably not great either.

@scheglov -- just saw your reply as I was typing this. Yeah it doesn't related to "whenComplete" although we may have an issue there too w.r.t. MethodInvocation targets (if so I'll file that separately).

**Comment by jmesserly** [comment]
by the way, if you use triple-backslash followed by "dart", for example:

    ```dart

it will syntax highlight automatically ... i tend to just fix this in people's comments because it's a lot nicer looking with colors :)

**Comment by scheglov** [comment]
Ah, yes, I know it, but forget to apply this knowledge :-)

**Comment by jmesserly** [comment]
filed https://github.com/dart-lang/sdk/issues/27114 for the methodinvocation target issue.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2262753002/
