### ISSUE TITLE
Clicks on linked class and method names don't open corresponding declarations on cpu profile table)

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27116]
It used to work.

**Comment by johnmccutchan** [comment]
@scheglov please provide more detail, I'm not sure what isn't working.

**Comment by scheglov** [comment]
When I click on the underlined method name here:
![image](https://cloud.githubusercontent.com/assets/384794/17819547/4bcba124-65fd-11e6-8913-314f4775ad68.png)
I expect that a new page with the method code is open.
Instead nothing happens.

If I click in the right callers/callees tables, selection in the left table is changes to this method.

**Comment by scheglov** [comment]
There is a bug in this version - its Stack% is always the same as Execution%.
![image](https://cloud.githubusercontent.com/assets/384794/17938313/4fa4e536-69da-11e6-9047-d6436f416337.png)
