### ISSUE TITLE
Allow downcasts in self-assignment operators

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27110]
Forgive me if this has already been filed or discussed. I couldn't find an issue. Consider:

```dart
class Foo {
  dynamic operator +(other) => null;
}

main() {
  Foo foo = new Foo();
  foo = foo + 1; // OK.
  foo += 1;      // Error.
}
```

Strong mode reports a type error on the self-assignment (because `dynamic` is not of type `Foo`), but not on the expanded form on the previous line.

My intuition is that a self-assignment would allow an implicit cast just like the manual form does. Am I missing something? Is this just a bug?

**Comment by lrhn** [comment]
It is definitely a bug that the two forms behave differently.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2271223004/

**Comment by jmesserly** [comment]
Reopening because this broke DDC. We'll need to mark it in a different way. Also should double check if pre/postfix ops have the same problem.

**Comment by jmesserly** [comment]
Progress: https://codereview.chromium.org/2362563004 but I need to check unary increment ops.

**Comment by jmesserly** [comment]
... and unary ops are now included in the fix.
