### ISSUE TITLE
Please merge revisions 49020b819ca13695c4adfbcd6ce1c09229a99b6c and c98c9c304a13caf28ea7b9de45a690503954e452 into dev channel

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27119]
@whesse @mit-mit @kasperl @dgrove @keertip @nex3 

This fixes two strong mode regressions in inference related to Futures that are blocking the internal roll.
https://github.com/dart-lang/sdk/issues/27101
https://github.com/dart-lang/sdk/issues/27113

These hashes should be merged (corresponding to the issues above):
49020b819ca13695c4adfbcd6ce1c09229a99b6c
c98c9c304a13caf28ea7b9de45a690503954e452

These two CLs, cherry picked in the order listed, merge cleanly, build, and pass all analyzer tests.

**Comment by whesse** [comment]
Merged in 1.19.0-dev.7.2
