### ISSUE TITLE
Improve the output of print(someJsObject)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27117]
With the use of interop, it'll be common for folks to print(someObject) which may be a native JS object. While in many cases we don't provide a "pretty" output, because of tricks that ClosureCompiler and others do with their types, we could certainly improve the experience.

Here's an example of `window.console.debug(...)` vs `print(...)` of the same object.

![screen shot 2016-08-19 at 11 13 20 am](https://cloud.githubusercontent.com/assets/17034/17819715/22ee19ac-65fe-11e6-830b-d88681a3c6c2.png)

While `Lf { idToken: ...}` is not perfect, it's much more useful than `[object Object]`

Could we create a slightly more helpful output here? Even something opt-in could be really useful.

See discussion here: https://github.com/Janamou/firebase3-dart/pull/11#issuecomment-240949922

**Comment by jacob314** [comment]
Should be trivial to make print redirect to console.log instead of calling toString and then redirecting to console.log.

**Comment by floitschG** [comment]
print takes a String. Redirecting it to console.log wouldn't change anything.
We can't just change the signature of `print`, since the underlying zones trust the string type.

**Comment by kevmoo** [comment]
> print takes a String. Redirecting it to console.log wouldn't change anything.

No, it takes `Object`. https://api.dartlang.org/stable/1.19.0/dart-core/print.html

There is a *bunch* of logic with dart2js compiled code to figure out a reasonable toString for unknown objects. I'm just talking about expanding it to be a bit more helpful.

**Comment by floitschG** [comment]
Yes. that was confusing.
What I meant to say: the underlying `printToConsole` function takes a String.

Admittedly, we could make `printToConsole` take an Object too, but then the output would be different depending on whether there is a zone or not. (And we are not going to change the API for zones).

I do agree that it would be nice to have the output of JS-objects be nicer. However, it's not as easy as just removing the `line = "$object";` from the core's `print` method.

**Comment by cup** [comment]
https://github.com/dart-lang/sdk/issues/29377
