### ISSUE TITLE
Wrong compound assignment in checked mode

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27125]
Example is the following:

```dard
main() {
  int i = 0;
  i ??= 1.5; // no error in checked mode
  print(i);

  i = 1.5; // error in checked mode
  print(i);
}
```

According to the spec ??= should produce the same errors as =.

**Comment by eernstg** [comment]
I believe this behavior is as specified.

Checked mode is concerned with the runtime behavior only, and the spec (16.19.1 Compound Assignment) specifies that `v ??= e` is equivalent to `((x) => x == null ? v = e : x)(v)`, so in the example you'd get the value zero, detect that it is not `==` to null, and yield zero, without evaluating `1.5` and without assigning anything to `i`. So the checked mode violation never occurs, and it is correct to proceed as indicated in your comments.

We are aware that these rewriting specifications are incomplete (they are invalid in cases where `e` contains `await`), but that doesn't matter in this case.
