### ISSUE TITLE
Add 'pathContext' to VFS Resource

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27120]
We often pass around both `Folder` or `File`, and also `ResourceProvider`, just because we need to know `PathContext`. So, it would be nice to make `Resource` to be able to return its `PathContext` and/or the whole `ResourceProvider`.

**Comment by srawlins** [comment]
`Resource` now has a `provider` (its ResourceProvider): https://pub.dev/documentation/analyzer/latest/file_system_file_system/Resource/provider.html
