### ISSUE TITLE
Analyzer summary building failing on Debian

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27126]
@bwilkerson @scheglov 

Our linux releases on Debian are broken, because the step that generates summaries is failing.
This is a P0 for me - we can't release stable 1.19 until we can build the debian packages for the SDK.

The problem seems to be that the summary generator can't find the SDK root, with sdkPath = FolderBasedDartSdk
        .defaultSdkDirectory(PhysicalResourceProvider.INSTANCE)
        .path

bacause Platform.resolvedExecutable is returning null.

Im currently debugging it, to see why this is happening when compiling the source from a tar file on Debian, but I would like your help.  First, is it unexpected that resolvedExecutable is null?  We seem to be running a snapshot of ddc when this happens.  Second, can you succeed without finding the sdkPath, or is this a key step in generating the summaries?

Here is the error output:

Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:654:14)
#3      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:641:26)
#4      _buildMultipleOutputs (file:///mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart:103:10)
#5      main (file:///mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart:53:28)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
utils/dartanalyzer/dartanalyzer.target.mk:26: recipe for target 'out/ReleaseX64/obj/gen/sdk_summary_bundle.bin' failed
make: *** [out/ReleaseX64/obj/gen/sdk_summary_bundle.bin] Error 255
make: *** Waiting for unfinished jobs....
rm utils_compiler_compiler_gyp_dart2js_target_generate_snapshots.intermediate
BUILD FAILED
chrome-bot@vm153-m3:/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart$ 

The command that is running to produce this output is:
LD_LIBRARY_PATH=/mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/lib.host:/mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd utils/dartanalyzer; mkdir -p /mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/obj/gen; "/mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/dart" "--package-root=/mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/packages/" ../../pkg/analyzer/tool/summary/build_sdk_summaries.dart single-output "/mnt/data/b/build/slave/linux-distribution-support-debian_wheezy-be/build/sdk/tmp/dart-1.20.0-edge.d5ba4e02b115a5d63c5dda376a7c5bbf61d48f47/dart/out/ReleaseX64/obj/gen/sdk_summary_bundle.bin"

**Comment by whesse** [comment]
Verified that out/ReleaseX64/dart is printing "null" when running

import "dart:io";

main() {
  print(Platform.resolvedExecutable);
}


But when I take the same executable, copy it over to my ubuntu system, and run the same program, it prints the path to the executable, not "null".  

I think this problem is up to me to figure out, since it is all down to Platform.resolvedExecutable returning null on Debian.

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by whesse** [comment]
When we print out Platform.executable instead of Platform.resolvedExecutable, we get the correct path to the dart binary.  So now I have to go into the native implementation of resolvedExecutable to find the problem.

**Comment by whesse** [comment]
I found the problem.  resolvedExecutable goes to /proc/self/exe to find the path, and I didn't have /proc mounted correctly in my chroot.  Fixing it fixes the problem.  Thanks for listening.

**Comment by stereotype441** [comment]
Phew!  Glad to hear it.  I was just starting to look at the code and wasn't coming up with any good ideas for a workaround :)
