### ISSUE TITLE
when debugging, the tokenPos returned for frames can be negative

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27128]
When debugging, the tokenPos returned for frames can be negative (and doesn't match any token positions for the given script).

To repro:
- clone https://github.com/flutter/flutter
- in the packages/flutter_tools package, run bin/main.dart, with a breakpoint on line 8 (`executable.main(args);`)
- step in once
- you'll be in a frame in `dart:async`; the frame above has a reported tokenPos of -214

This is for 1.19.0-dev.7.0.

**Comment by johnmccutchan** [comment]
Context for whoever looks at this bug while I'm out on vacation. Negative token positions are synthetic source positions. More information is here: https://github.com/dart-lang/sdk/blob/master/runtime/vm/token_position.h

The debugger should be converting this positions into real source position before sending it over the wire.

**Comment by johnmccutchan** [comment]
cc @turnidge @rmacnak-google
