### ISSUE TITLE
`readdir_r` is deprecated in recent glibc versions.

### ISSUE THREAD

**Issue by sladage** [dart-lang/sdk#27121]
sdk/runtime/bin/directory_linux.cc:123
sdk/runtime/bin/directory_linux.cc:282

General recommendation seems to be to use `readdir` instead, not sure what the implications would be since `readdir_r` is thread safe unlike `readdir`.

**Comment by floitschG** [comment]
See https://github.com/dart-lang/sdk/pull/27093

**Comment by floitschG** [comment]
That pull request was merged.
