### ISSUE TITLE
Implementation differences between JSString.split and DartString.split

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27127]
I am working on removing facades from https://github.com/dart-lang/angular2 post removing the TypeScript version as the source of truth, and part of this is removing a large amount of 'facades' that allowed the Dart and JS version to work mostly the same.

Having a tough time removing one of the facades, `StringWrapper`, which re-implements `split` in (seemingly?) the same way it is implemented in JS. A couple questions:

1. Is this a split API difference or a RegExp API difference?
2. How does JS interop within Dart deal with it? Any known/filed issues I'm missing?
3. Lastly, any recommendations other than keeping this code?

See live example on DartPad (`ngFacadeSplit` is the JS-like implementation):
https://dartpad.dartlang.org/37a53b0d5d4cced6c7312b2b965ed7fd

**Comment by floitschG** [comment]
This is a difference in the `split` function.
Apparently I was even the reviewer (although I really have no memory about it): https://codereview.chromium.org/677013002/

/cc @lrhn

**Comment by lrhn** [comment]
It's a `split` API difference. JS split includes all captures in the regexp between the parts, Dart does not.

JS interop (not my expertise, so I'm guessing) shouldn't have to deal with it. If you something as a Dart string, it uses the Dart split semantics, if you call the JavaScript split function, it does the JS thing.

As for keeping a wrapper - I'd rather go through the code and see which cases call `split` and expect JS behavior, then make a static helper method with that behavior and call it directly. That's much more readable than a wrapper class (if that is what `StringWrapper` is).
