### ISSUE TITLE
Partially types local variables

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27135]
This code has a surprising hint `INFO: The argument type '(dynamic) → int' cannot be assigned to the parameter type '(String) → dynamic'. ([my_test] bin/test2.dart:3)`

```dart
void foo() {
  List myList = getListOfString();
  myList.map((type) => 42);
}

List<String> getListOfString() {
  return const <String>[];
}
```

**Comment by jmesserly** [comment]
just a guess, but hints usually come from propagated types, and their interaction with strong mode's stricter isAssignableTo/isSubtypeOf on TypeSystem.

If that's the cause here, it may be worth 100% disabling propagated types in strong mode, because this pattern of bug comes up a lot.

**Comment by scheglov** [comment]
Yes, I think we should disable propagated types in strong mode.
If strong mode is the only future, it's crazy to have more than one set of types.
And if something is not good enough in strong mode, then we either accept that this feature is not something what users should expect, or it should be implemented in strong mode itself.

@bwilkerson @stereotype441
