### ISSUE TITLE
Cannot look at types / methods in Observatory

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27137]
I used to look sometimes at methods code in Observatory - both Dart and generated native.

But now the corresponding Web pages are always blank.

For example:

![image](https://cloud.githubusercontent.com/assets/384794/17911875/fe16fa3c-6944-11e6-89b6-aaa4beab727f.png)

![image](https://cloud.githubusercontent.com/assets/384794/17911881/0542e1a4-6945-11e6-8e72-c0df7e313a5e.png)

**Comment by B3rn475** [comment]
It should have been fixed by https://github.com/dart-lang/sdk/commit/416ffffab5caf6ca985578e9b0053d6c7a3de655

**Comment by scheglov** [comment]
ACK, it works for me now.
