### ISSUE TITLE
Search does not work on Observatory virtual collection pages

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27136]
I need to find a class to look at its heap statistics, check its methods, etc.

Again, this used to work.

**Comment by johnmccutchan** [comment]
We are moving all views in Observatory to use a virtual collection. We are moving to virtual collections for performance reasons. Virtual collections do not work with browser search (CTRL+F) but we can add custom search functionality to each view.

**Comment by scheglov** [comment]
Please, add search functionality.
I often search on the "cpu profile (table)" page to find how well a method I'm currently interested in works. Scrolling through thousands of other methods is very inconvenient. And sorting by method name is actually rarely useful to see the whole picture once I found the method.

**Comment by johnmccutchan** [comment]
@scheglov The original title is more accurate. Browser search works on the vast majority of pages within Observatory. It is only virtual collections that do not interact with browser search well.

We will address this but the top priority right now is finishing the removal of Polymer from Observatory.

**Comment by scheglov** [comment]
OK, understood.
Thanks.
