### ISSUE TITLE
Building SDK fails (`./tools/build.py`)

### ISSUE THREAD

**Issue by vynes** [dart-lang/sdk#27131]
I'm on Gentoo.

Running: `./tools/build.py --verbose --mode release --arch x64 create_sdk`

Output:

make -j 2 BUILDTYPE=ReleaseX64 V=1 create_sdk
  g++ '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Iruntime  -Werror -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -g3 -ggdb3 -fno-rtti -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_android.o.d.raw  -c -o out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_android.o runtime/bin/log_android.cc
  g++ '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Iruntime  -Werror -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -g3 -ggdb3 -fno-rtti -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_linux.o.d.raw  -c -o out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_linux.o runtime/bin/log_linux.cc
<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]
<built-in>: note: this is the location of the previous definition
cc1plus: all warnings being treated as errors
make: *** [runtime/libdart_builtin.host.mk:2834: out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_android.o] Error 1
make: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make: *** [runtime/libdart_builtin.host.mk:2834: out/ReleaseX64/obj.host/libdart_builtin/runtime/bin/log_linux.o] Error 1
BUILD FAILED

**Comment by whesse** [comment]
The problem is that Gentoo gcc is patched to automatically define _FORTIFY_SOURCE, so when we define it explicitly, there is a problem.  Lots of other projects have hit this error on Gentoo.

I would fix this by removing line 3551,
                  '_FORTIFY_SOURCE=2',
from build/common.gypi, in your checkout of Dart.

**Comment by vynes** [comment]
After removing that line I still get the same error.

**Comment by whesse** [comment]
Try running "gclient runhooks", to regenerate the makefiles from gyp, after making that change.  Do the compilation commands still include an explicit -D_FORTIFY_SOURCE?

**Comment by vynes** [comment]
I did a `gclient runhooks` and removed that line again (3550 for me). Same error.
Yes, the commands still include -D_FORTIFY_SOURCE.

**Comment by whesse** [comment]
If that line is being restored when you runhooks, then maybe you have a managed checkout.  Make sure that the line "managed" : False is in your .gclient file in the directory containing "sdk".

If that line is being restored, then it doesn't have an effect when you runhooks and regenerate the make files.

**Comment by vynes** [comment]
I reverted and resynced, changed managed from True to False and deleted that line again.
-D_FORTIFY_SOURCE=2 is still present.
I get the same error, but this time only once instead of twice:


make -j 2 BUILDTYPE=ReleaseX64 V=1 create_sdk
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/adler32.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/adler32.o third_party/zlib/adler32.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/compress.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/compress.o third_party/zlib/compress.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/crc32.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/crc32.o third_party/zlib/crc32.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/deflate.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/deflate.o third_party/zlib/deflate.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzclose.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzclose.o third_party/zlib/gzclose.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzlib.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzlib.o third_party/zlib/gzlib.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzread.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzread.o third_party/zlib/gzread.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzwrite.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/gzwrite.o third_party/zlib/gzwrite.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/infback.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/infback.o third_party/zlib/infback.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inffast.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inffast.o third_party/zlib/inffast.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inflate.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inflate.o third_party/zlib/inflate.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inftrees.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/inftrees.o third_party/zlib/inftrees.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/trees.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/trees.o third_party/zlib/trees.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/uncompr.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/uncompr.o third_party/zlib/uncompr.c
  cc '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Ithird_party/zlib  -w -UHAVE_CVAR_BUILT_ON_SEM -Wextra -Wno-unused-parameter -Wvla -g3 -ggdb3 -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/zutil.o.d.raw  -c -o out/ReleaseX64/obj.target/zlib_dart/third_party/zlib/zutil.o third_party/zlib/zutil.c
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/create_resources.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/resources_gen.cc" --outer_namespace dart --inner_namespace bin --table_name service_bin --root_prefix bin/ bin/vmservice/loader.dart bin/vmservice/server.dart bin/vmservice/vmservice_io.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/builtin_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::_builtin_source_paths_ --library_name dart:_builtin bin/builtin.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/io_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::io_source_paths_ --library_name dart:io ../sdk/lib/io/io.dart ../sdk/lib/io/bytes_builder.dart ../sdk/lib/io/common.dart ../sdk/lib/io/crypto.dart ../sdk/lib/io/data_transformer.dart ../sdk/lib/io/directory.dart ../sdk/lib/io/directory_impl.dart ../sdk/lib/io/eventhandler.dart ../sdk/lib/io/file.dart ../sdk/lib/io/file_impl.dart ../sdk/lib/io/file_system_entity.dart ../sdk/lib/io/http.dart ../sdk/lib/io/http_date.dart ../sdk/lib/io/http_headers.dart ../sdk/lib/io/http_impl.dart ../sdk/lib/io/http_parser.dart ../sdk/lib/io/http_session.dart ../sdk/lib/io/io_resource_info.dart ../sdk/lib/io/io_sink.dart ../sdk/lib/io/io_service.dart ../sdk/lib/io/link.dart ../sdk/lib/io/platform.dart ../sdk/lib/io/platform_impl.dart ../sdk/lib/io/process.dart ../sdk/lib/io/service_object.dart ../sdk/lib/io/secure_server_socket.dart ../sdk/lib/io/secure_socket.dart ../sdk/lib/io/security_context.dart ../sdk/lib/io/socket.dart ../sdk/lib/io/stdio.dart ../sdk/lib/io/string_transformer.dart ../sdk/lib/io/websocket.dart ../sdk/lib/io/websocket_impl.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/io_patch_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::io_patch_paths_ --library_name dart:io bin/common_patch.dart bin/directory_patch.dart bin/eventhandler_patch.dart bin/file_patch.dart bin/file_system_entity_patch.dart bin/filter_patch.dart bin/io_service_patch.dart bin/platform_patch.dart bin/process_patch.dart bin/service_object_patch.dart bin/socket_patch.dart bin/stdio_patch.dart bin/secure_socket_patch.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/html_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::html_source_paths_ --library_name dart:html ../sdk/lib/html/dartium/html_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/html_common_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::html_common_source_paths_ --library_name dart:html_common ../sdk/lib/html/html_common/html_common.dart ../sdk/lib/html/html_common/css_class_set.dart ../sdk/lib/html/html_common/device.dart ../sdk/lib/html/html_common/filtered_element_list.dart ../sdk/lib/html/html_common/lists.dart ../sdk/lib/html/html_common/conversions.dart ../sdk/lib/html/html_common/conversions_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/js_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::js_source_paths_ --library_name dart:js ../sdk/lib/js/dartium/js_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/js_util_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::js_util_source_paths_ --library_name dart:js_util ../sdk/lib/js_util/dartium/js_util_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/blink_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::blink_source_paths_ --library_name dart:_blink ../sdk/lib/_blink/dartium/_blink_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/indexeddb_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::indexeddb_source_paths_ --library_name dart:indexed_db ../sdk/lib/indexed_db/dartium/indexed_db_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/cached_patches_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::cached_patches_source_paths_ --library_name cached_patches.dart ../sdk/lib/js/dartium/cached_patches.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/web_gl_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::web_gl_source_paths_ --library_name dart:web_gl ../sdk/lib/web_gl/dartium/web_gl_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/metadata_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::metadata_source_paths_ --library_name metadata.dart ../sdk/lib/html/html_common/metadata.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/websql_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::websql_source_paths_ --library_name dart:web_sql ../sdk/lib/web_sql/dartium/web_sql_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/svg_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::svg_source_paths_ --library_name dart:svg ../sdk/lib/svg/dartium/svg_dartium.dart
  LD_LIBRARY_PATH=/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.host:/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd runtime; mkdir -p /home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen; python tools/gen_library_src_paths.py --output "/home/curvian/SDK/dart-sdk/sdk/out/ReleaseX64/obj/gen/webaudio_gen.cc" --input_cc bin/builtin_in.cc --include bin/builtin.h --var_name dart::bin::Builtin::webaudio_source_paths_ --library_name dart:web_audio ../sdk/lib/web_audio/dartium/web_audio_dartium.dart
  g++ '-DNDEBUG' '-D_FORTIFY_SOURCE=2' -Iruntime -Ithird_party -Ithird_party/zlib -Ithird_party/boringssl/src/include  -Werror -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -g3 -ggdb3 -fno-rtti -fno-exceptions -fstack-protector -Wa,--noexecstack -m64 -msse2 -O3 -ffunction-sections -fno-omit-frame-pointer  -MMD -MF out/ReleaseX64/.deps/out/ReleaseX64/obj.host/libdart_io/runtime/bin/io_natives.o.d.raw  -c -o out/ReleaseX64/obj.host/libdart_io/runtime/bin/io_natives.o runtime/bin/io_natives.cc
<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]
<built-in>: note: this is the location of the previous definition
cc1plus: all warnings being treated as errors
make: *** [runtime/libdart_io.host.mk:3066: out/ReleaseX64/obj.host/libdart_io/runtime/bin/io_natives.o] Error 1
make: *** Waiting for unfinished jobs....
BUILD FAILED

**Comment by whesse** [comment]
Oops- when I grepped for "FORTIFY" before in the repo, using "git grep FORTIFY", I missed a second place where it appears in the gyp files.  Please also remove line 14 from tools/gyp/configurations_make.gypi, which reads 
           '_FORTIFY_SOURCE=2',

**Comment by vynes** [comment]
Building fine now, thank you.

**Comment by whesse** [comment]
You're welcome.
