### ISSUE TITLE
Inbound references are incomplete

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27147]
Why the first two references don't have their `referenced by` filled?

![image](https://cloud.githubusercontent.com/assets/384794/17950740/f73c3efc-6a11-11e6-99e0-ad3a2c2f22f6.png)

**Comment by johnmccutchan** [comment]
@scheglov Please provide a command line to reproduce this issue and steps from within Observatory.

**Comment by scheglov** [comment]
As with the other issue - I don't have exact reproduction, but it seems to happen for every `_File` from `file_impl.dart`.

**Comment by johnmccutchan** [comment]
@scheglov Carlo needs to know how to run your program under the Observatory.

**Comment by scheglov** [comment]
Yeah, I understand.
Unfortunately my program is not easy to run :-(

But the example in https://github.com/dart-lang/sdk/issues/27146 shows both problems, I think.

**Comment by B3rn475** [comment]
Is this still reproducible after https://github.com/dart-lang/sdk/commit/942918347c16624e6d7dd7678bbb45e1e503de3a ?

**Comment by scheglov** [comment]
Well, yes, it is.
Maybe I just don't know something and this reference from a list is expected?

![image](https://cloud.githubusercontent.com/assets/384794/17953780/1feeab64-6a2b-11e6-8442-ceee29cdc8b6.png)

**Comment by B3rn475** [comment]
The main problem is that in my version that list doesn't show up.
As you can see in the picture in https://github.com/dart-lang/sdk/issues/27146
Are there any exception the the console log?
If you use 1.18 is the list visible?

**Comment by johnmccutchan** [comment]
@scheglov We tracked down the _List(1) reference -- it is a side effect of computing strongly reachable instances for a class.

https://github.com/dart-lang/sdk/issues/27156

**Comment by johnmccutchan** [comment]
@scheglov Also, FYI, if the "referenced by" is empty that indicates that the object is being held onto by the VM internally.

**Comment by scheglov** [comment]
Thank you, guys.
You're awesome.

**Comment by rmacnak-google** [comment]
The missing internal references would be covered by #26663.
