### ISSUE TITLE
Heap snapshot hierarchical ingoing references

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27145]
See the screenshot.

So, I see that most strings are references from _List.
Cool.
Now, from where these _List instances, which reference strings, are referenced?
Without this I cannot track down why are the end are these strings are not GCed.

![image](https://cloud.githubusercontent.com/assets/384794/17950558/e251d3ae-6a10-11e6-9563-01f924826ce9.png)

**Comment by rmacnak-google** [comment]
The grouping isn't recursive, so there is currently no way to ask "Who references _Lists that reference _OneByteStrings." It is something I'd like to eventually add, along with a similar filter to the dominator tree view that merges siblings with the same class.

If you have a particular string you think should be garbage, you can explore why it still alive with the retaining path and inbound references tools on the instance view.

**Comment by scheglov** [comment]
No, I don't have a specific object.

I'm trying to answer the question "Why the hell do we use so much memory?" :-)

My approach to this would be: OK, we have too many strings, but why? Ah... Most of them are in _List(s), which are in Map(s), which are in AnalysisCacheEntry(s). Hm... OK, Observatory, I'd like to see instances of AnalysisCacheEntry instances which reference String (i.e. some action "Show instances on this reference path" in heap snapshot). Let's open couple of these AnalysisCacheEntry and analyze their fields. Ha! They are all for the CONTENT analysis result, which should not happen - we should flush CONTENT once we computed TOKEN_STREAM. Let's debug and fix this. Nice, now we use 30% less memory!  Well, there are still more String instances than I'd like to have. Who's the next biggest source of references to them?...

**Comment by rmacnak-google** [comment]
Merged dominator tree was added a long time ago.
