### ISSUE TITLE
The analyzer should parse asserts in initializer lists.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27142]
See #27141 for details.

The analyzer should accept an `assert` "expression" (like an assert statement without a trailing `;`) as an element in initializer lists. This should be enabled by passing an `--assert-initializer` flag to the analyzer.

As an initial implementation, the analyzer can skip analyzing the assertion completely.

It would be great if it could also evaluate any assert in a const context (in an initializer of a const constructor which is used to create a compile-time constant value). This would enable earlier errors for the team that is experimenting with the feature.

**Comment by eseidelGoogle** [comment]
FYI @pq

**Comment by bwilkerson** [comment]
As of https://codereview.chromium.org/2282233002/ the analyzer now accepts the new syntax if the flag `enableAssertInitializer` is included in the `language` section of the analysis options file.

The syntax is not yet captured in the AST structure, nor is any error checking performed, but this should allow clients to begin to experiment with using the feature without complaints from the analyzer.

**Comment by sethladd** [comment]
Thanks! We'll give it a shot.

**Comment by sethladd** [comment]
Hi @bwilkerson thanks for starting this feature.

Could we add support for checking if the constructs inside of initializer asserts are valid?

See https://github.com/flutter/flutter/issues/5865#issuecomment-255211114 which I read as "surprised that a call to `any` was allowed in an initializer const assert".

We're not confident that we're using this feature correctly until the analyzer warns/hints to us if we've used non-const expressions in initializer const asserts.

Thanks!

**Comment by bwilkerson** [comment]
I believe that https://codereview.chromium.org/2492633002/ implements the rest of the analysis for this feature. Note that the formatter doesn't yet understand the new syntax.

**Comment by sethladd** [comment]
Thanks for the patch. Cc @munificent to check if there is a formatter issue
to track

**Comment by bwilkerson** [comment]
There is, and we're in the middle of getting the formatter updated.

**Comment by bwilkerson** [comment]
(https://github.com/dart-lang/dart_style/issues/522)

**Comment by bwilkerson** [comment]
The formatter now correctly handles the new syntax as well.

**Comment by lrhn** [comment]
Does it check for the condition being a potentially constant expression in a const constructor?

**Comment by bwilkerson** [comment]
I'll double check.

**Comment by sethladd** [comment]
@lrhn : when you said "it" did you mean analyzer or formatter?

**Comment by bwilkerson** [comment]
Analyzer. The formatter only cares about syntactic errors.

**Comment by bwilkerson** [comment]
I had missed that case. Taken care of by https://codereview.chromium.org/2483213010/.

**Comment by sethladd** [comment]
Thanks @bwilkerson !

@pq @keertip did this get into the latest roll of Dart SDK for Flutter? Or, will it be in the next roll?

**Comment by pq** [comment]
That would be the next roll.

FWIW that's stalled pending #6840 but hope to get that squared away with a little help from the upstream package maintainer.

**Comment by sethladd** [comment]
Cool, no worries. Thanks for the update!

**Comment by sethladd** [comment]
Hi! I tried to test this, but analyzer tells me the option is unknown:

```
~/tmp $ dartanalyzer --assert-initializer const_asserts.dart 
Could not find an option named "assert-initializer".
Usage: dartanalyzer [options...] <libraries to analyze...>
-D, --D                            Define environment variables. For example, "-Dfoo=bar" defines an environment variable named "foo" whose value is "bar".
    --dart-sdk                     The path to the Dart SDK.
    --options                      Path to an analysis options file.
-p, --package-root                 The path to a package root directory (deprecated). This option cannot be used with --packages.
    --packages                     The path to the package resolution configuration file, which supplies a mapping of package names to paths. This option cannot be used with --package-root.
    --[no-]strong                  Enable strong static checks (https://goo.gl/DqcBsw)
    --no-implicit-casts            Disable implicit casts in strong mode (https://goo.gl/cTLz40)
    --no-implicit-dynamic          Disable implicit dynamic (https://goo.gl/m0UgXD)
-b, --batch                        Read commands from standard input (for testing).
    --format                       Specifies the format in which errors are displayed.
    --machine                      Print errors in a format suitable for parsing (deprecated).
    --version                      Print the analyzer version.
    --lints                        Show lint results.
    --no-hints                     Do not show hint results.
    --ignore-unrecognized-flags    Ignore unrecognized command line flags.
    --fatal-hints                  Treat hints as fatal.
    --fatal-warnings               Treat non-type warnings as fatal.
    --fatal-lints                  Treat lints as fatal.
    --package-warnings             Show warnings from package: imports.
    --show-package-warnings        Show warnings from package: imports (deprecated).
    --warnings                     Show warnings from SDK imports.
    --show-sdk-warnings            Show warnings from SDK imports (deprecated).
    --x-perf-report                Writes a performance report to the given file (experimental).
-h, --help                         Display this help message.
                                   Add --verbose to show hidden options.

-v, --[no-]verbose                 Verbose output.
    --url-mapping                  --url-mapping=libraryUri,/path/to/library.dart directs the analyzer to use "library.dart" as the source for an import of "libraryUri".

For more information, see http://www.dartlang.org/tools/analyzer.
~/tmp $ dartanalyzer --version
dartanalyzer version 1.22.0-dev.5.0~/tmp $ 
```

@bwilkerson what did I do wrong? :)

**Comment by bwilkerson** [comment]
To the best of my knowledge there is no command-line flag for this option (we only create command line flags when absolutely essential). There is instead a "language" option named "enableAssertInitializer" in the analysis options file.

**Comment by sethladd** [comment]
Ah, thanks @bwilkerson . I updated the description of this issue and removed the instructions to use the CLI argument.

**Comment by scheglov** [comment]
[Validating](https://codereview.chromium.org/3003363002) assert conditions in analyzer.
