### ISSUE TITLE
Analysis server documentation

### ISSUE THREAD

**Issue by ddrone** [dart-lang/sdk#27149]
There are some notes related to analysis server in https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server, but I have a couple of (hopefully minor) issues with them:
1. There is no described way to actually run analysis server. Trying to check out SDK repository and running `dart bin/server.dart` leads to immediate server because it fails with an error message
2. The only way to read the API docs is to check out repository and open docs/api.html locally. It would be more nice to have them hosted somewhere

**Comment by bwilkerson** [comment]
1. You're right, we ought to document that.

You should be able to run from sources. If you post the error message I can try to help you figure out what's wrong. But the preferred approach is to run the snapshot in `<pathToSdk>/bin/snapshots/analysis_server.dart.snapshot`.

2. You can also use a convenient tool provided by github for reading HTML: https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html.

Out of curiosity, what do you want to use the server to do?

**Comment by ddrone** [comment]
1. I'll try to run it again and will post error message / snapshot file today.
2. IMO it will be helpful to have link to htmlpreview in README.md. I can do a PR for that if there's no objections.

I want to give a try at implementing a client for continuously showing error messages, as I'm not particularly satisfied with one available in IntelliJ plugin (I want to have more filtering / grouping capabilities)

**Comment by bwilkerson** [comment]
> I can do a PR for that if there's no objections.

No objection; we're always happy to take contributions!

**Comment by alexander-doroshko** [comment]
> I want to have more filtering / grouping capabilities

@ddrone, just curious what filtering / grouping capabilities do you miss? Feature request in [YouTrack](https://youtrack.jetbrains.com/issues/Web) (Dart subsystem) is welcome.

Also, IntelliJ's Dart plugin is [open source](https://github.com/JetBrains/intellij-plugins/tree/master/Dart), so you can add required filtering / grouping for yourself or even submit a pull request.

**Comment by ddrone** [comment]
@alexander-doroshko, the easiest example is that I'm not interested in seeing every occurrence of the same warning in a file, just writing it once and adding a counter would suffice. Also I have a bunch of other ideas with presentation of errors I want to explore and I don't really want to touch IntelliJ's code for that

**Comment by alexander-doroshko** [comment]
> I'm not interested in seeing every occurrence of the same warning in a file, just writing it once and adding a counter would suffice

You are reading our minds! :) We've discussed related feature of the Dart Analysis view just few days ago. I think we'll implement something in this area.

> a bunch of other ideas

Ideas are always welcome!

**Comment by ddrone** [comment]
Running snapshot as described in the first comment works, thanks.

**Comment by bwilkerson** [comment]
I'm guessing this issue was either resolved or is now stale.
