### ISSUE TITLE
Retaining path does not look good

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27146]
![image](https://cloud.githubusercontent.com/assets/384794/17950666/851ebed0-6a11-11e6-957a-ae8c65b1e055.png)

**Comment by johnmccutchan** [comment]
@scheglov Please provide a command line to reproduce this issue and steps from within Observatory.

**Comment by scheglov** [comment]
I don't have exact reproduction, but it seems to happen for every `_File` from `file_impl.dart`.

**Comment by johnmccutchan** [comment]
@scheglov How does Carlo run your program under the Observatory?

**Comment by scheglov** [comment]
I don't know for sure if this is the same problem, but I can reproduce something like this on.

```dart
import 'dart:io';

main() {
  var f = new MyFile('/Users/scheglov/Source/Dart/sdk.git/sdk/my.diff');
  f.entry.readAsBytesSync();
  while (true) {}
}


class MyFile {
  final File entry;

  MyFile(String path): entry = new File(path);
}
```

![image](https://cloud.githubusercontent.com/assets/384794/17951383/9adc4f1c-6a16-11e6-860a-2714e4b57ea7.png)

**Comment by B3rn475** [comment]
Can you give us some other information?
The same code on my workstation returns this:
![screenshot from 2016-08-24 16 29 20](https://cloud.githubusercontent.com/assets/2686902/17951608/3e020172-6a18-11e6-94a1-d0fb54446f76.png)

**Comment by B3rn475** [comment]
I finally reproduced it.

**Comment by scheglov** [comment]
```
$ dart --version
Dart VM version: 1.20.0-edge.d8eb5ffb573b28135a21ea2c7340f69c7578f831 (Wed Aug 24 11:35:14 2016) on "macos_ia32"
```
