### ISSUE TITLE
Published versions of analyzer have FastUri incompatible with SDK 1.19.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27159]
In order for Analyzer's `FastUri` class to work, its implementation of `hashCode` must match the implementation in the SDK (because analyzer mixes `FastUri`s and `Uri`s inside `Map`s).

In version 1.19 of the SDK, `Uri`'s implementation of `hashCode` was changed, and `FastUri` was updated accordingly.  However, since releases of analyzer to pub are not coupled with SDK releases, this means that there are published versions of analyzer that will break when SDK 1.19 is released.

Two versions of analyzer are affected: 0.27.5 and 0.28.0.

To work around the problem, we plan to add a static final boolean variable to analyzer which determines whether `Uri` uses a new or an old implementation of `hashCode` (by attempting to hash a hardcoded URI).  This boolean will determine the behavior of `FastUri.hashCode`.

This fix needs to be cherry-picked to the historic releases of analyzer, and released as 0.27.6 and 0.28.1, respectively.

**Comment by scheglov** [comment]
Fix `FastUri` to be compatible with both old and new VMs.
https://github.com/dart-lang/sdk/commit/08a682500c1b67ed979d8a40d8b5e44191dca27c

**Comment by scheglov** [comment]
I published `0.27.6` and `0.28.1` with the same `FastUri` implementation.

**Comment by stereotype441** [comment]
Should we archive the branches used to publish these versions, in case we need to do further bug fixes to them?

**Comment by scheglov** [comment]
I don't know what this means in git :-(
I suspect that `git cl land` would attempt to land this in bleeding edge.
So, I just applied the changes to the corresponding branches #85551ad and #261ef2b, published `analyzer` and rolled the changes back.
