### ISSUE TITLE
Strange Error: "Unterminated multi-line comment"

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#27157]
If I have a `/*` sequence inside a comment the analyzer reports a `Unterminated multi-line comment`

The minimum file needed to reproduce is:

```dart
/*/*/
```

But every configuration like
```dart
/*
   var foo = new Foo();
/*
   var bar = new Bar(foo);
*/
```
It is useful during debugging.

**Comment by bwilkerson** [comment]
Multi-line comments are allowed to nest in Dart. Hence, something like:

```
/*
x
/*
y
*/
z
*/
```

is a single, valid comment.
