### ISSUE TITLE
Analyser should not require empty list to be typed in `typedlist ?? []` construct

### ISSUE THREAD

**Issue by parren-google** [dart-lang/sdk#27153]
For code like

```
void foo(List<Foo> typedlist) {
  var safelist = typedlist ?? [];
}
```

the analyser currently says:

```
The argument type 'EfficientLength' cannot be assigned to the parameter type 'Iterable'.
```

It can be fixed with

```
var safelist = typedlist ?? <Foo>[];
```

It would be nice if it inferred this instead.

**Comment by bwilkerson** [comment]
Have you enabled strong-mode?

**Comment by parren-google** [comment]
I have since a while now. Just tried with strong mode, and cannot repro the problem.

**Comment by bwilkerson** [comment]
Thanks for letting us know. I'm going to assume that this has been fixed.
