### ISSUE TITLE
After running `pub get` the analysis server completion list for imports does not include new module

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27165]
1. Add a new package (eg. `html` to `pubspec.yaml`)
2. Run `pub.get`
3. In a Dart file, invoke completion in an `import '';`

The completion list has all modules that existed when the analysis server was started up, but doesn't include the newly-downloaded module.

(If this is not a bug and the IDE should be sending something to trigger a refresh of these, please let me know!)

**Comment by bwilkerson** [comment]
I'm guessing that there is a cached list of available libraries that isn't being flushed correctly.

**Comment by danrubel** [comment]
All caching was removed from the completion services as of https://github.com/dart-lang/sdk/commit/6d5efd3175140b4ddfbc00da72eb38608aea5cb2 on Dec 17 last year as part of my completion services overhaul.

**Comment by DanTup** [comment]
I cannot repro this issue in 1.22 so this seems fixed. I'm not sure why it occurred in Sep 2016 if it was fixed in Dec 2015, maybe there was another change since.
