### ISSUE TITLE
meta pub package contains more code than found here

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#27166]
meta's [1.0.2 pub package](https://pub.dartlang.org/packages/meta)  includes a [library named 'extras'](https://www.dartdocs.org/documentation/meta/1.0.2/extras/extras-library.html), yet no such library exists [in this repo](https://github.com/dart-lang/sdk/tree/master/pkg/meta/lib). Did someone accidentally `pub publish` an extra file?

**Comment by bwilkerson** [comment]
Yes, I did. I've been debating between publishing a 2.0.0 that removes it and a 1.0.3 that marks it as deprecated.

**Comment by srawlins** [comment]
👅  I have no opinion. Just wanted to make sure it was known.

**Comment by floitschG** [comment]
Can this be closed?

**Comment by bwilkerson** [comment]
The published version of meta contains a file that shouldn't be there. It hasn't been removed, so I don't think so.

**Comment by srawlins** [comment]
meta [1.1.2](https://www.dartdocs.org/documentation/meta/1.1.2/) no longer includes 'extras'. This is fixed.
