### ISSUE TITLE
Pub build failed in Eclipse plugin

### ISSUE THREAD

**Issue by Vincent-ILM** [dart-lang/sdk#27163]
Hi,

When I try to execute "Run pub build - minified" / "Run pub build - debug" in eclipse

This message appear:
Pub build failed, [64] Directory names are not allowed if "--all" is passed.

Usage: pub build [options] [directories...]
-h, --help      Print this usage information.
    --mode      Mode to run transformers in.
                (defaults to "release")

    --all       Use all default source directories.
-D, --define    Defines an environment constant for dart2js.
    --format    How output should be displayed.
                [text (default), json]

-o, --output    Directory to write build outputs to.
                (defaults to "build")

Run "pub help" to see global options.
See http://dartlang.org/tools/pub/cmd/pub-build.html for detailed documentation.

But when I run it in command line, all works fine:
pub build

Loading source assets... 
Loading script_inliner transformers... (1.1s) 
Building myProject... 
[Info from Dart2JS]:
Compiling myProject|web/dart/main.dart...
[Info from Dart2JS]:
Took 0:00:12.813310 to compile myProject|web/dart/main.dart.
Built 95 files to "build".

eclipse version: neon (4.6.0)
dart-sdk version: 1.19.0-dev.7.3
dart editor version: 1.12.0.201509241517

Cordially,
Vincent.

**Comment by devoncarew** [comment]
Hi @Vincent-ILM, thanks for the feedback! Unfortunately, the eclipse based tooling is no longer supported. If you're feeling very handy, you can try patching and building the codebase here: https://github.com/dart-lang/eclipse3. Otherwise I would suggest trying more recent analysis server based products, like the IntelliJ plugin: https://www.dartlang.org/tools/jetbrains-plugin.

**Comment by Vincent-ILM** [comment]
Thanks for reply and work on it, have you got some ideas on which files are impacted for this bug in the eclipse plugin?

**Comment by openconcerto** [comment]
Dear Devon,
Please keep in mind that a lot of Java developer prefer using Eclipse... (for a lot of good reasons, like performance, price, UI...).
Splitting the Dart community is not the best way to extend the user base and generate good reviews.
Regards,
