### ISSUE TITLE
dartanalyzer reports warning instead of error

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27161]
```dart
List l = new List();
l.add("string");

List<int> li = new List<int>();

li = l;

print(l2[0]);
```

Analyzer (in strong mode) reports on this: [warning] Unsound implicit cast from List< dynamic > to List< int >

There should be an error, not warning! Otherwise it's possible circularity that we want to avoid (see https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md)

```dart
  List<String> ls = new List<String>();
  List l = new List();
  List<int> li = new List<int>();

  ls.add("abc");
  li.add(123);

  l = ls;
  li = l;

  print(li[0]);
```

In a strong mode analyzer reports 
[warning] Unsound implicit cast from List< dynamic > to List< int > 
[hint] A value of type 'List< String >' cannot be assigned to a variable of type 'List<int>' 
1 warning and 1 hint found.

And no error! 

Tested on Dart VM version: 1.19.0-dev.7.3 (Tue Aug 23 03:02:14 2016) on "windows_x64"

**Comment by leafpetersen** [comment]
This is working as intended.  We currently allow implicit downcasts in strong mode. In DDC, which is the only platform that currently implements the runtime checks required for soundness, there will be a runtime cast inserted on the assignment to `li`, which fail at runtime.  On other platforms, strong mode is not *yet* enough to guarantee soundness, but we expect to have implementations of this on other platforms as well in the near future.

That said, there is a new flag that will be available in v19 (and is already available in the dev channel) that will turn implicit downcasts such as the ones in your example into errors.  Run the analyzer with `--strong --no-implicit-casts` to get this behavior.  We'd love to get feedback on this feature, so if you turn it on please let us know how it goes.
