### ISSUE TITLE
IsolateRunnable event is not showing up in 1.19.0-dev.7.3

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27168]
Here is a report from the end user using 1.19.0-dev.7.3

Have there been any changes to the Observatory protocol in this version?

I'm having issues getting debugging working in Dart Code; it seems that whereas in 1.18.1 we got an IsolateRunnable event at the start, it never arrives in 1.19.0-dev.7.3.

A comparison of communications can be seen here:

https://github.com/Dart-Code/Dart-Code/issues/129#issuecomment-242520992

It causes the app to just remain paused at startup.

(it's possible this is something we're doing wrong; but 1.18.1 does seem to work..)

On Wed, 24 Aug 2016 at 12:14 'Michael Thomsen' via Dart Announcements <announce@dartlang.org> wrote:

The first release candidate, RC0, of version 1.19 of the Dart SDK is now ready for testing. This release candidate is version 1.19.0-dev.7.3 from the dev channel. Please download it and test it against your apps.

The changelog has more details. We look forward to your feedback, so we can release it into the stable channel. Please test your packages and apps, and report issues.

**Comment by a-siva** [comment]
@rmacnak-google

**Comment by DanTup** [comment]
We believe this was just a timing issue in our code - in 1.18 we were already listening when the isolate was created, but in 1.19 it was being created before we were listening.

**Comment by DanTup** [comment]
This was indeed our error and is now fixed. This can be closed (I can't close as I didn't raise). Apologies!
