### ISSUE TITLE
Add a mechanism to Analysis Server to retrieve item-to-be-renamed for a rename refactor

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27178]
This was discussed a little in Analyzer-Discuss:

https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/PLdn5Y4DWaQ

The current rename behaviour can result in something that is not directly under the cursor being renamed. Eg.:

```dart
import 'dart:async';
```

Initiating a rename on the word `import` will result in the provided value being added as an alias:

```dart
import 'dart:async' as newName;
```

This is great functionality, but IDE tooling doesn't know this is going to happen and therefore pre-populating the rename dialog with the word `import` is very misleading. A similar issue exists when performing rename on the call to a default constructor, which adds a new named constructor.

There are a couple of ways this could be fixed, but I think the most flexible would be to have a mechanism where you can ask the analysis server what item would be renamed if you sent a rename for a specific location.

In the above example, the returned value would be an empty string for the import (since there is no current alias). However it the code had been:

```dart
import 'dart:async' as async;
```

Invoking a request for the rename item for `import` would now return the name `async`. This would allow the editor to correctly populate the input box with the existing alias.

Similarly, for constructors, the name of the constructor to be renamed should be returned (empty string in the case of the default).

As a work around, we are using `feedback.oldName` (compared with the word under the cursor) and aborting the rename if these don't match. The user experience is bad though, as we've already allowed the user to perform the rename at this point (however we may be able to improve this once Code supports pre-filling the box - we can just send a dummy refactor and examine `feedback.oldName` in the result but not actually perform the refactor).

**Comment by DanTup** [comment]
Thinking about this more, the implementation of this might be as simple as reusing some of the existing code - basically the equivilent of sending a refactor request and returning the `oldName` property.

It'd be extra nice if the returned info could explain what the item is too so that the user can be given a hint about what they're providing (an alias for an import, a new name for a constructor, a new name for a class).

**Comment by DanTup** [comment]
@bwilkerson Actually, now I re-read the spec, the rename refactoring has a `validateOnly` property that looks like it might be intended to support this. If this includes the `oldName` then possibly there's nothing to do here?

**Comment by bwilkerson** [comment]
It isn't clear from the spec. It's possible that the `validateOnly` flag might only return any errors that would have resulted. We'll have to investigate.

@scheglov Do you know whether `validateOnly` would satisfy this request?

**Comment by scheglov** [comment]
We already return a textual description of the element that will be renamed.

```
elementKindName ( String )

The human-readable description of the kind of element being renamed (such as “class” or “function type alias”).
```

![image](https://cloud.githubusercontent.com/assets/384794/18036574/f2f80696-6d22-11e6-8c25-27534a5816e5.png)

![image](https://cloud.githubusercontent.com/assets/384794/18036580/058cfd98-6d23-11e6-89a8-531edc11cca8.png)

**Comment by DanTup** [comment]
Great; so is sending a rename request with `validateOnly=true` the correct way to get this info prior to rendering the rename box? Will the `oldName` value be returned in that case too?

**Comment by scheglov** [comment]
Yes, `oldName` and `elementKindName` are filled and returned very early, for any rename refactoring, even without options.

**Comment by DanTup** [comment]
Excellent; in that case it sounds like everything in this request is actually already provided! :-)
