### ISSUE TITLE
File close()

### ISSUE THREAD

**Issue by normcf** [dart-lang/sdk#27177]
This fileclose.dart code:

```
import 'dart:html';
Test test;
class Test {
  ButtonElement be;
  File f1;

  Test() {
    be = document.querySelector('#testfile');
    be.onClick.listen(pressed);
  }

  void pressed(MouseEvent me) {
    print("button pressed.");
    String s1 = "12345", s2 = "abcdef";
    List<Object> ls = new List<String>();
    ls.add(s1); ls.add(s2);
    f1 = new File(ls,"testfile");
    f1.close();
  }
}
void main() {
  test = new Test();
}
```

with this fileclose.html:

```
<html><body>
<button id="testfile">PressMe</button>
<script type="application/dart" src="fileclose.dart"></script>
<script data-pub-inline src="../packages/browser/dart.js"></script>
</body></html>
```

Gives this exception in dartium 1.18 and 1.19:
`Uncaught Unhandled exception:`
`: property is not a function`
`#0      Blink_JsNative_DomException.callMethod (dart:_blink:23416)`
`#1      BlinkBlob.close_Callback_0_ (dart:_blink:1544)`
`#2      Blob.close (dart:html:2267)`
`#3      Test.pressed (http://192.168.1.200/etact/test/fileclose.dart:20:8)`

Interestingly, pub builds it without complaint, but it still fails in Chrome Version 52.0.2743.116 (64-bit) with:

`fileclose.dart:20 Uncaught TypeError: t1.close is not a function`

According to the documentation `File.close` is a function (inherited from Blob.close).

**Comment by kevmoo** [comment]
@terrylucas ?

**Comment by alan-knight** [comment]
The bug is that File.close does not exist in JS and should be removed from Dart. It's listed as experimental in MDN, but is not present in either Chrome or Firefox current versions.

**Comment by kevmoo** [comment]
@alan-knight sounds like something we could just remove, right? Could you take this?

**Comment by alan-knight** [comment]
Well, remove is not quite so trivial. It's a special case of #24582. We could explicitly suppress it, but that's awfully ugly.

**Comment by normcf** [comment]
Thanks for looking into this.  I'll close this now as it looks like the issue is already being addressed.
