### ISSUE TITLE
dart2js executes (broken) code without error

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27175]
This code:

```dart
class MyClass {
  String name;
  String doc;

  MyClass(String name, String doc, this.doc);
}

main() {
  var a = new MyClass("test", "test", "test");
  print(a.name);
}

Will error when run in the VM:

```shell
c:\Users\danny\Desktop\DartSample>dart test.dart
'file:///c:/Users/danny/Desktop/DartSample/test.dart': error: line 5 pos 41: duplicate formal parameter 'doc'
  MyClass(String name, String doc, this.doc);
```

However in dartpad it will just print `null` without an errors. I believe the behaviour of these should match.

**Comment by lrhn** [comment]
We are in the process of changing the specified behavior.
It used to be the VM which was incorrectly rejecting this program, but we are actually making its behavior correct, and the other implementations are in the process of being made compatible (see #26655).
