### ISSUE TITLE
vm/DirectoryRename and DirectoryCreateDelete seem flaky

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#27188]
I often get flaky failure messages on DirecotryRename and DirectoryCreateDelete. Here are some example cases:

https://build.chromium.org/p/client.dart/builders/vm-win-product-x64-be/builds/685/steps/vm%20tests/logs/stdio

https://build.chromium.org/p/client.dart/builders/vm-win-product-x64-be/builds/680/steps/vm%20tests/logs/stdio

https://build.chromium.org/p/client.dart/builders/vm-win-release-ia32-be/builds/2864/steps/steps/logs/stdio

cc: @whesse @a-siva

**Comment by whesse** [comment]
It is strange that it is happening in product mode and not in debug or release mode.  I checked the runtime/tests/vm/vm.status file, and there is no mention of those tests there.  What could the difference be in product mode?

**Comment by sigmundch** [comment]
I've seen the failures in release mode too though (see https://build.chromium.org/p/client.dart/builders/vm-win-release-ia32-be/builds/2864/steps/vm%20tests/logs/stdio)

**Comment by floitschG** [comment]
I had a short look. It looks like the directory tests work directly on `/tmp/` (or `c:/TEMP`) and have the potential to interfere with each other (and any other file there).
We should update the tests to create a temp directory first (even though that makes the test kind of redundant: create a temp directory, to test creating a directory...

**Comment by zanderso** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/682a4d0036687120f03f2ec10b32995492cb5e08

**Comment by floitschG** [comment]
This won't be enough, when multiple configurations (debug, release, ...) are running on the same machine. They could still interfere with each other.
Also, there is no guarantee, that there isn't another program that uses `/tmp/create_delete_test_name` or `/tmp/rename_test_name` for other purposes.

I think the only correct way to run the tests is to use `Directory_CreateTemp` and work in that directory.

**Comment by zanderso** [comment]
For work on porting to Fuchsia there is a lot of value in keeping these tests simple and self contained. I don't think there is sufficient value in working around the problems you mention to make the changes you suggest, especially since there have been no flakes on the bots since the change.

**Comment by whesse** [comment]
I think it is quite straightforward to also add a nesting call to dart::bin::Directory::CreateTemp(name) in these tests, and they are just as self-contained - the C++ class Directory contains both methods.
This would make them perfectly free of race conditions.  But if the problem has disappeared, we don't absolutely need to do it.  I just want to note this here, so if it recurs, we know how to fix it.  We could also add a comment or a TODO at the site, but having it in the issue should be enough.
