### ISSUE TITLE
vm crashes in HttpClient

### ISSUE THREAD

**Issue by zengyun261** [dart-lang/sdk#27181]
``` dart
  HttpClient client = new HttpClient();

  start() async {
    while(true) {
      var req = await client.postUrl(...);
      req.write(....);
      var resp = await req.close();
      await resp.drain();
      print(resp.statusCode);
    }
  }

  for(int i = 0; i < 100; i++) {
    start();
  }
```

bin/eventhandler_win.h: 439: error: expected: !HasPendingRead()
dart 1.19.0 + win10

**Comment by lrhn** [comment]
So you are doing 100 simultaneous requests.
Can you say anything more about the requests or the responses. I can't reproduce this on Windows 7, so I'll have to find a Win10 machine.
