### ISSUE TITLE
Please merge 5d6c03e40d00a28fff4b6dd15591b27a2f751235 into stable channel

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#27184]
Please merge 5d6c03e40d00a28fff4b6dd15591b27a2f751235 into 1.19.0 stable channel. This picks up a new version of dartdoc. The dartdoc shipped in the current stable version is broken.

**Comment by devoncarew** [comment]
@whesse, ping, dartdoc is broken in `1.19.0` when generating docs for packages.

**Comment by whesse** [comment]
Merged in stable 1.19.1.
