### ISSUE TITLE
Click on an object on cpu profile (table) replaces the page

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27191]
I think this is too intrusive.
Building these tables, sorting them and finding an interesting object - all is gone after a single click.
Maybe Observatory should always open a new page?

**Comment by B3rn475** [comment]
By single click you mean selecting an element from the list or navigating to that element's page?
In the first case it would be a bug, but I can't reproduce it.
I the second case I think that can be interesting

**Comment by scheglov** [comment]
Yes, sorry, of course navigating to that element's page.
