### ISSUE TITLE
pub get runs forever

### ISSUE THREAD

**Issue by sigi77** [dart-lang/sdk#27204]
Resolving the dependencies doesn't seem to finish. When I remove [google_oauth2_client](https://pub.dartlang.org/packages/google_oauth2_client) it runs quickly. 

pubspec.yaml:

name: intranet_angular2
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  google_oauth2_client: ^0.4.2
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1445
