### ISSUE TITLE
Bug in 'yield*' implementation in DartVM

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#27205]
The pub.dartlang.org site encountered an issue after upgrading to new package dependencies via `pub upgrade`. I managed to reduce the issue to the following test case:

```dart
import 'dart:io';
import 'dart:async';
import 'package:http/http.dart' as http;

Stream<List<int>> forwardStream(Stream<List<int>> stream) async* {
  yield* stream;
}

Future<Stream<List<int>>> load(http.Client client) async {
  var response = await client.send(
      new http.Request('GET', Uri.parse('https://www.google.com')));
  return forwardStream(response.stream);
  // return response.stream;
}

fetchContent(http.Client client) async {
  var subscription;

  var completer = new Completer();

  var stream = await load(client);
  subscription = stream.listen((List<int> data) {
    print('Data: ${data.length}');

    print(' --> pausing');
    subscription.pause();
    Timer.run(() {
      print(' --> resuming');
      subscription.resume();
    });
  }, onDone: () {
    print('Done');
    completer.complete();
  });

  return completer.future;
}

main() async {
  var client = new http.Client();

  for (int i = 0; i < 5; i++) {
    print('Iteration $i');
    await fetchContent(client);
    print('Iteration $i - done\n');
  }

  client.close();
}
```

Running this results in the following output:
```
$ dart test.dart
 time dart bin/server.dart
Iteration 0
Data: 8001
 --> pausing
 --> resuming
Data: 3524
 --> pausing
 --> resuming
dart bin/server.dart  0.35s user 0.05s system 2% cpu 15.556 total
$ echo $?
0
```

Please notice that the for loop was not iterated 5 times! (the 15 seconds come due to the timeout of http keep alive connections of the http client).

Now compare this with the code not using `forwardStream()`:

```
$ time dart bin/server.dart
Iteration 0
Data: 8036
 --> pausing
 --> resuming
Data: 3427
 --> pausing
 --> resuming
Done
Iteration 0 - done

Iteration 1
Data: 8167
 --> pausing
 --> resuming
Data: 3370
 --> pausing
 --> resuming
Done
Iteration 1 - done

Iteration 2
Data: 7934
 --> pausing
 --> resuming
Data: 3510
 --> pausing
 --> resuming
Done
Iteration 2 - done

Iteration 3
Data: 7492
 --> pausing
 --> resuming
Data: 3964
 --> pausing
 --> resuming
Done
Iteration 3 - done

Iteration 4
Data: 7842
 --> pausing
 --> resuming
Data: 3606
 --> pausing
 --> resuming
Done
Iteration 4 - done

dart bin/server.dart  0.35s user 0.05s system 44% cpu 0.916 total
```

**Comment by mkustermann** [comment]
@lrhn @floitschG  Could you please confirm that the code is correct and that this is a VM bug?

**Comment by lrhn** [comment]
It is a VM bug. There is a problem when the stream is paused at the moment the `yield*` stream sends its done event. In that case, the continuation isn't scheduled (because the stream is paused), but the bit to say that it's waiting isn't set either, so when the stream is resumed, it doesn't think it needs to do anything to continue.

CL: https://codereview.chromium.org/2297013003/

**Comment by mkustermann** [comment]
@whesse @kevmoo 
Was this fix included in any recent stable release?

**Comment by whesse** [comment]
No, this is not in any stable release.  It is in dev releases from 1.20.0-dev.2.0 onward.
If you need it in stable, file a merge-to-stable request.
1.20.0 stable is scheduled for October 6 as a target date.

**Comment by kevmoo** [comment]
And we can always release a dev SDK on our pub site.
