### ISSUE TITLE
Documentation issue on dart-lang/sdk Wiki Contributing 

### ISSUE THREAD

**Issue by aravindame** [dart-lang/sdk#27200]
There are some issues related to dart-lang/sdk Wiki page( https://github.com/dart-lang/sdk/wiki/Contributing ). In the coding style category Google C++ style guide link which is redirecting to the http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml is giving an 404 error that says The requested URL /svn/trunk/cppguide.xml was not found on this server.

**Comment by rmacnak-google** [comment]
Updated link to https://google.github.io/styleguide/cppguide.html.
