### ISSUE TITLE
Request to delete package from pub.dartlang.org

### ISSUE THREAD

**Issue by jonmccracken-wf** [dart-lang/sdk#27209]
Can you please remove [w_comments](https://pub.dartlang.org/packages/w_comments), which was uploaded accidentally? I've read through the FAQ, which recommended opening an issue to do this. Can you please remove it?

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package/25131121#25131121

You can prevent accidental publishing by adding this to your `pubspec.yaml`

```yaml
publish_to: none
```

**Comment by devingray-wf** [comment]
Thanks @zoechi - We've changed our pubspec.yaml.  Can this be removed?

**Comment by whesse** [comment]
Done.
