### ISSUE TITLE
VM service broken in profile mode

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#27211]
Steps to reproduce as of https://github.com/flutter/flutter/commit/ed6e7fa06f85ff6c3a66a5d0ab69aad70a5da506:

- `flutter run --profile`
- open observatory in the browser

Another way to reproduce is:

- `flutter run --profile --trace-startup`

A log message "Ignoring error posting over WebSocket." is printed that seems to be coming from [this line](https://github.com/dart-lang/sdk/blob/d418dde65bc6c25840d2d6b0890d4ce4ae3ec0ef/runtime/bin/vmservice/server.dart#L66)

/cc @turnidge @rmacnak-google

**Comment by turnidge** [comment]
@rmacnak-google - Could this be related to the recent work you've done on websocket:

**Comment by rmacnak-google** [comment]
This is a bug in the flutter build. https://github.com/flutter/flutter/issues/5627
