### ISSUE TITLE
X in close box for notifications is not centered

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#27215]
![screen shot 2016-08-31 at 3 04 16 pm](https://cloud.githubusercontent.com/assets/4804200/18148058/6af99aae-6f8c-11e6-91d7-3fff66a47f03.png)

The hover circle and the close-x for a notification are no longer centered.  See screenshot.

**Comment by B3rn475** [comment]
It is a CSS bleed that will be fixed in the next days when I convert the page

**Comment by B3rn475** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/876f49999a37a5e1281867ec0e4a0e1917ac2a7e
