### ISSUE TITLE
Null or Undefined Reference Exception in IE 10 with dart2js CSP Mode Enabled

### ISSUE THREAD

**Issue by todbachman-wf** [dart-lang/sdk#27212]
We are experiencing an issue running a project in IE10 using compiled JS from dart2js with CSP mode enabled. I have created a reduced test-case that exhibits the issue with no external dependencies:

_pubspec.yaml_:

``` yaml
name: ie_csp_bug
transformers:
- $dart2js:
     csp: true
```

_web/main.dart_:

``` dart
void main() {
  print(Uri.parse('https://google.com/?a=b').queryParameters);
}
```

_web/index.html_:

``` html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>IE CSP Bug</title>
</head>
<body>
<script src="main.dart.js"></script>
</body>
</html>
```

Here is the resulting error we see when running this app in IE10:

![image](https://cloud.githubusercontent.com/assets/8091340/18142541/51f11fac-6f7b-11e6-9520-3fd1c04c7670.png)

When I debug it, the highlighted line of code below fails because prototype is eventually `Undefined` in that loop:

![image](https://cloud.githubusercontent.com/assets/8091340/18142888/c1760684-6f7c-11e6-9b03-4e8a878feab4.png)

Simply switching CSP mode to `false` in the `pubspec.yaml` fixes the issue. However, we do require CSP-compliant JS in our production applications so this has become a roadblock.

**Comment by whesse** [comment]
Is this issue still live?  We are dropping IE10 testing, because IE10 is past EOL, and its browser share is minimal.  Reopen if still live and important.
