### ISSUE TITLE
dart2js produces compile error for 'multiple' initialization of final field

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27226]
Please see #12539
dart2js produces compile error on the code

class C {
  final v = 1;

  C() : v = 2 {}
}

In a non-strong mode there should be only static warning and runtime error.

**Comment by srawlins** [comment]
There is no more non-strong mode, and this behavior is now consistent across analyzer, vm, and dart2js.

dart2js: `Fields can't be initialized in the constructor if they are final and have already been initialized at their declaration.`

```none
$ dartanalyzer 27226.dart 
Analyzing 27226.dart...
  error • Fields can't be initialized in the constructor if they are final and have already been initialized at their declaration at 27226.dart:4:9 • field_initialized_in_initializer_and_declaration
1 error found.
srawlins-macbookpro:dart-language srawlins$ dart 27226.dart 
27226.dart:4:11: Error: 'v' is a final instance variable that has already been initialized.
  C() : v = 2 {}
          ^
27226.dart:2:9: Context: 'v' was initialized here.
  final v = 1;
        ^
```
