### ISSUE TITLE
Remove ignored type failures

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27223]
_From @vsmenon on August 25, 2016 16:49_

This was a temporary workaround until generic methods.  We should eliminate this:

https://github.com/dart-lang/dev_compiler/blob/master/tool/input_sdk/private/ddc_runtime/operations.dart#L272

_Copied from original issue: dart-lang/dev_compiler#630_

**Comment by jmesserly** [comment]
CC @leafpetersen

**Comment by vsmenon** [comment]
Note, this is currently blocked on lack of typed angular templates.  Related to #27255.

**Comment by vsmenon** [comment]
I'd start with Angular Dart apps.  Possible source of type failures:

- Handwritten code - which we should just fix.
- Generated code from protobufs.
- Generated code from ng2 templates.
- Generated code from pageloader / mirrors.

At this point, we don't know where most ignored errors are coming from.  Pageloader will only trigger problems in tests though.

**Comment by dgrove** [comment]
@vsmenon is this targeted for 1.24?

**Comment by vsmenon** [comment]
No, good progress with angular this q.  Still issues in Zone code.

**Comment by matanlurey** [comment]
Vijay let's get a breakdown of known issues and we can work on it this/next
week.

**Comment by vsmenon** [comment]
Note, this is now primarily blocked on #30225

**Comment by jmesserly** [comment]
internally this is also blocked by code that uses mirrors to populate Dart class fields, often in unsound ways that bypasses field type checks.

**Comment by munificent** [comment]
As we go through and fix existing code that has these failures, here's a bit of verbiage we can use in commit logs to let people know what's going on:

```
In strong mode, a generic type instantiated with dynamic is not a
subtype of all types. You can't pass a List<dynamic> to something
expecting, say, List<int>.

These errors are usually detected statically, and most of those have
been fixed. However, sometimes this becomes a runtime cast, as in:

main() {
  // Store a List<dynamic> in a variable of type dynamic.
  dynamic d = [];

  // Implicit runtime downcast from dynamic to List<String>.
  List<String> s = d;
}

In order to ease the migration to strong mode, DDC has been ignoring
these cast failures when they involve certain commonly used types. We
are now in the process of actively fixing those errors.
```

**Comment by natebosch** [comment]
Are these still ignored in the external SDK?

**Comment by vsmenon** [comment]
Should not be, but the hook is still there for internal.
