### ISSUE TITLE
Cannot see strongly reachable instances

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27222]
I click on `+` and nothing happens.

![image](https://cloud.githubusercontent.com/assets/384794/18182307/4a48ee1e-7044-11e6-905a-2a2e95c7597c.png)

**Comment by B3rn475** [comment]
Is this happening with all the classes or with this one in particular?
From the `Loading...` message on the bottom I guess there was an exception.
Can you attach the stack trace from the developer tools?

**Comment by scheglov** [comment]
It happens for all classes.
And sometimes the page is completely empty.

I'm attaching the whole console on the class page refresh.

[127.0.0.1-1472764692775.txt](https://github.com/dart-lang/sdk/files/450723/127.0.0.1-1472764692775.txt)
