### ISSUE TITLE
Analysis Server completion results should include info on where to insert imports

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27220]
I noticed on completion results there's this field:

> `importUri (optional String)`
> The import to be added if the suggestion is out of scope and needs an import to be added to be in scope.

However there's no information on where it should be inserted. It might not be safe to insert at `offset: 0` as the file might have a header comment.

It would be better if the response also contained an offset of where to insert (which should probably be after the last existing import, if one exists) or a source edit to apply to the document instead.

**Comment by alexander-doroshko** [comment]
@DanTup It looks like in most cases Analysis Server simply doesn't suggest items that are not available in context. E.g. you can't complete `Fut` to `Future` if there's no `import 'dart:async'`. First you have either to type `Future` and use a quick fix to insert import, or to write import manually.

Related https://github.com/dart-lang/sdk/issues/25298 and https://github.com/dart-lang/sdk/issues/21931.

**Comment by DanTup** [comment]
Yeah; I'd never actually seen a result for something not-imported, but since it was documented I figured maybe it was possible.

> in most cases

Is it *most*, or *all*? If it never occurs, removing it from the docs might be a good idea (it seems kinda broken in its current form because of not providing a location to import).

**Comment by bwilkerson** [comment]
We would like to reserve the ability to start suggesting available but not yet imported names.

**Comment by DanTup** [comment]
But won't the API need to change to support that anyway (to provide the location to add the import)? It doesn't seem that in the current form we could implement this ready to automatically take advantage of the "future feature"?

**Comment by bwilkerson** [comment]
It would certainly be better if we provided an edit, and I expect we will, but clients could (theoretically) take advantage of the info by figuring out where to insert the URI.

**Comment by DanTup** [comment]
This field no longer exists (and completions with imports are handled differently), so there's nothing to do here.
