### ISSUE TITLE
Impossible to debug failing tests

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27229]
I have a failing pub test, but no way to debug it.
I can find ways to run the test, but the IDE does not provide any way to set a breakpoint and debug the code. (At least I couldn't find any).

Eventually I ended up creating a new build-configuration that just executes 'dart' directly on the failing test file. That at least, gave me a way to set a breakpoint in the main of the that file, but I was unable to set a breakpoint in the package that was failing.

Update: the breakpoint not triggering is probably because Pub is running commands...
Edit: removed breakpoint screenshot.

**Comment by anders-sandholm** [comment]
YouTrack, area-analyzer?

**Comment by alexander-doroshko** [comment]
> but I was unable to set a breakpoint in the package that was failing

When you run test as an ordinary Dart app breakpoints should works anywhere: own code, packages and SDK. In case of file from package make sure you set breakpoint in the original file, not in its symlink from any of numerous 'packages' folders.

**Comment by alexander-doroshko** [comment]
Debugging VM tests that are started via 'pub run test' is not possible at the moment. Tracked as https://github.com/dart-lang/test/issues/50 and/or https://github.com/dart-lang/test/issues/459.

In my understanding the problem could also be solved by being able to pass VM options to the VM that executes tests (when starting tests via `pub run test`). For example this could be solved if `pub run` started program in a separate isolate (currently it spawns separate OS process). Related issues are https://github.com/dart-lang/pub/issues/1018 and https://github.com/dart-lang/pub/issues/1204.

**Comment by jwren** [comment]
Thanks @alexander-doroshko !

**Comment by alexander-doroshko** [comment]
Debugging of tests executed by the Dart VM is possible starting from IntelliJ IDEA 2017.1 (available as EAP now) and Dart SDK 1.22+.
