### ISSUE TITLE
dev_compiler: Non-nullable type annotation syntax

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27234]
This is the dev_compiler-specific issue for #27231. That issue has the details.

**Comment by jmesserly** [comment]
should only need to plumb through the option, as we'll get the parsing "for free" from analyzer: https://github.com/dart-lang/sdk/issues/27232

**Comment by jmesserly** [comment]
DDC has all analyzer flags now.

presumably we'll need to investigate again once CFE replaces analyzer.
