### ISSUE TITLE
Stepping using OverAsyncSuspension can occasionally keep running

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27238]
When stepping at an async location (`OverAsyncSuspension`), the VM can occasionally keep running. I was able to narrow this down to a reproducible case (reproducible in a not-yet-released version of IntelliJ, and in the Observatory). To repro:

- set a breakpoint at `Future future1`
- run
- hit bp
- continue stepping
- at the line `await future2`, hitting step will not step, but continue execution until the app finishes

```dart
import 'dart:async';

main() async {
  Future future1 = new Future.value(); // set breakpoint here, then async step
  Future future2 = new Future.value();

  await future1;
  await future2;

  print('foo1'); // stepping doesn't stop here
  print('foo2');
  print('foo3');
  print('foo4');
}
```

**Comment by johnmccutchan** [comment]
@rmacnak-google FYI

**Comment by mhausner** [comment]
@devoncarew, what do you mean with 'occasionally keeps running'? Is it an intermittent problem?

**Comment by mhausner** [comment]
I can't reproduce this using the Observatory debugger. When stepping on a await statement, the debugger stops at the beginning of main (which it probably should not) and when stepping again, stops at the next await or the print statement.

**Comment by devoncarew** [comment]
Sorry, I meant occasionally in general code. I was able to get it down to that repro above, which was consistent for me. I don't recall the version of the sdk I was using; I _suspect_ `1.19.0-dev.5.0`, given the timeframe and that flutter was on that release for quite a while.

**Comment by devoncarew** [comment]
I am able to repro this with `1.20.0-dev.5.0` as well.

**Comment by mhausner** [comment]
Thanks. I'm now able to repro it when I use 'next-async' instead of 'next'. Interestingly, 'next' works fine for me.

**Comment by johnmccutchan** [comment]
@mhausner 'next' is smart and 'next-async' is dumb (and should probably be removed). The implementation of 'next' is here:

```dart
Future smartNext() async {
    if (isolatePaused()) {
      var event = isolate.pauseEvent;
      if (event.atAsyncSuspension) {
        return asyncNext();
      } else {
        return syncNext();
      }
    } else {
      console.print('The program is already running');
    }
  }
```

**Comment by johnmccutchan** [comment]
@devoncarew Your debugger should only issue an OverAsyncSuspension if the program is currently paused at an async suspension. Does your client have logic like the above?

**Comment by devoncarew** [comment]
Yes, it does: https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcess.java#L300

**Comment by johnmccutchan** [comment]
I think I have a reproducible service protocol test here:

https://codereview.chromium.org/2359543002

The test does not stop at the `print('foo1')` line after stepping over the second await.

**Comment by mhausner** [comment]
This is fixed at 74e779d4fecf3f15802895b8b10b7692316b0f3b.

**Comment by johnmccutchan** [comment]
The test you added to the fix regularly flakes on Windows:

https://build.chromium.org/p/client.dart/builders/vm-win-release-x64-be/builds/3159/steps/vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment]
I'm confused about what could be OS specific.

**Comment by mhausner** [comment]
Fixed the test a while ago. It wasn't OS specific, but timing dependent and apparently the right circumstances only happened on Windows.
