### ISSUE TITLE
IntelliJ-plugin: Non-nullable type annotation syntax

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27237]
This is the IntelliJ-plugin-specific issue for #27231. That issue has the details.

**Comment by munificent** [comment]
cc @jwren

**Comment by anders-sandholm** [comment]
not sure how to label this issue? Should it be moved to youtrack?

**Comment by jwren** [comment]
We have an area-intellij now in github.

**Comment by alexander-doroshko** [comment]
@jwren time to close?
