### ISSUE TITLE
Continuous integration testing of strong mode against flutter

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27230]
We'd like to get continuous (or nightly) testing of strong mode analysis on flutter running, perhaps on travis.  This is intended not as a presubmit (keep it green), but rather as a canary to give more runway to the flutter rolls, and for the analyzer team to get early visibility into the impact of breaking changes.  

We could probably fairly easily just add this to the dev compiler travis bots:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/.travis.yml

It's not really a dev compiler issue though, so might make more sense to have a different instance.

@kevmoo @sethladd @pq thoughts?

**Comment by leafpetersen** [comment]
Assigning to @pq for now, feel free to lob it back as appropriate.

**Comment by sethladd** [comment]
Really cool idea.

**Comment by bwilkerson** [comment]
@leafpetersen I'm guessing that this can be closed now. Please re-open if not.
