### ISSUE TITLE
Future.wait doesn't give time to callers to install error-handlers.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27249]
https://codereview.chromium.org/2311923002/

**Comment by lrhn** [comment]
To be honest, I wouldn't mind if this case threw an error synchronously. It's an error in either iteration or calling `Future.then` and that just shouldn't happen. If it does happen, the error does not come from any of the futures, so putting it into the result future could be a little confusing.

On the other hand, having asynchronous functions report all their errors in the returned future seems to make some people happy.
