### ISSUE TITLE
Low Priority! Misspelling of 'deferred' in dart2js comments

### ISSUE THREAD

**Issue by nicklansley** [dart-lang/sdk#27240]
When dart2js writes out the JavaScript code file, a misspelling of the word  'deferred'  as 'deferered' is apparent in the following comment, always on line 13 of output code (bold mine):

12 // dartDeferredLibraryLoader(uri, successCallback, errorCallback):
13 //    if this function is defined, it will be called when a **deferered** library
14 //    is loaded. It should load and eval the javascript of `uri`, and call
15 //    successCallback. If it fails to do so, it should call errorCallback with
16 //    an error.

It's annoying only insofar as IDE spellcheckers keep highlighting it!

**Comment by floitschG** [comment]
Thanks. Will fix immediately.
