### ISSUE TITLE
dart process for WebStorm consumes 110% CPU for long time

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/sdk#27248]
I have a mixed source type project: 30 Dart, 1000 PHP
When load this into WebStorm, the Dart analyze runs for about 20s, then progress bar disappears, however after some time (1 hour) I noticed hot MacBook and about half of battery. I found that the process dart is up and consumes 110% CPU. 

When I load just the Dart portion to WebStorm everything works fine.

**Comment by devoncarew** [comment]
We've since re-written the implementation (the analysis driver re-write), so I'm closing this issues as assumed fixed.
