### ISSUE TITLE
Add isDeprecated flag to analysis server getHover responses

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27244]
There's an `isDeprecated` flag on `CompletionSuggestion` but no equivilent on `getHover`. It would be useful to show this info in the tooltips too.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2310153002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f4186fb463cdefd6fd242bfd00909f301dc8a32d
