### ISSUE TITLE
remove "_uncheckedWhitelist" in code_generator

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27255]
Complete hack as a work-around until pkg/angular2 is generating strong code.

Blocked by https://github.com/dart-lang/angular2/issues/48

**Comment by vsmenon** [comment]
_From @jmesserly on August 25, 2016 16:43_

thanks to @vsmenon for reminding me to file an issue on this

**Comment by vsmenon** [comment]
Waiting on typed ng.dart templates to remove this whitelist.

**Comment by dgrove** [comment]
This is waiting for the new AngularDart code generator, so should be moved to 1.24. Do you agree, @vsmenon ?

**Comment by vsmenon** [comment]
Yes, moved it.

**Comment by dgrove** [comment]
This seems unlike for 1.24, given that AngularDart hasn't yet switched to the new code generator. Thoughts?

**Comment by matanlurey** [comment]
We should experiment with how far off we are internally, but yes, won't be in time for 1.24.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2928483002/
