### ISSUE TITLE
expose analyzer configuration options w/ same flags as analyzer_cli

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27252]
DDC should use the same flags. Now that we're part of the same repository/SDK build, it would be feasible to have shared code in package:analyzer_cli

For example, https://github.com/dart-lang/sdk/issues/27251 would be fixed by this.

**Comment by jmesserly** [comment]
I marked this high pri because it's the sort of thing where doing it sooner will fix a lot of other bugs. Also package:test integration with DDC was blocked on this.

**Comment by vsmenon** [comment]
This should be fixed by #27511

**Comment by jmesserly** [comment]
yeah, I think they're duplicates.
