### ISSUE TITLE
implicit downcasts in op assign may not be reified correctly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27254]
_From @jmesserly on August 25, 2016 22:23_

I'm fixing https://github.com/dart-lang/sdk/issues/27110, and I discovered these casts are not marked in an unambiguous way, so it's likely we're inserting the implicit cast in the wrong place.

_Copied from original issue: dart-lang/dev_compiler#632_

**Comment by vsmenon** [comment]
_From @jmesserly on August 29, 2016 16:50_

ah, apparently we get an exception, not a missing cast. Bumping priority, @stereotype441 I'll have a look now. Thanks @leafpetersen for alerting me to this.

**Comment by vsmenon** [comment]
_From @jmesserly on August 29, 2016 17:53_

Hmmm, actually I'm going to change how Analyzer marks this so DDC doesn't pick it up. Working on the back end of this change made me notice a few things that were suboptimal about my previous Analyzer CL.

**Comment by jmesserly** [comment]
was fixed in https://github.com/dart-lang/sdk/commit/adc71ab396ed16b0a7b565fc7d2232170af2dcf7
