### ISSUE TITLE
type parameter bounds for generic methods/functions

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27256]
_From @jmesserly on April 28, 2016 20:26_

The initial implementation will not validate type bounds.

We actually have the same issue with generic classes. But there, it can only be triggered via JavaScript interop, because `C<InvalidType>` would be rejected at compile time. Generic methods must handle this at run time for dynamic calls.

Since we represent these types as a function like `(T, S) => dart.functionType(...)`, once option is to generate an assertion in the body. Same trick would work for generic classes, although we might not want it there, because it would be triggered (once) for every class, whereas if we look up a runtime type signature of a generic method, we're already in the dynamic dispatch code path.

_Copied from original issue: dart-lang/dev_compiler#532_

**Comment by vsmenon** [comment]
_From @jmesserly on April 28, 2016 20:36_

(Note, if we ever want mirror support for type bounds, we'll need to store this in a way we can get at it. https://api.dartlang.org/stable/1.16.0/dart-mirrors/TypeVariableMirror-class.html -- that's pretty obscure though, unclear where mirrors is headed for DDC)

**Comment by vsmenon** [comment]
_From @jmesserly on April 28, 2016 23:23_

Oh also: we'll need to instantiate to bounds at runtime in dcall/dsend. This is not implemented yet. ~~Perhaps we can do default values on the type parameters.~~ edit: nvm, that would require everything to include `dart.dynamic`, there are probably better approaches

**Comment by jmesserly** [comment]
Note, this also affects our ability to do subtype checks on the bounds given two generic function types..

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2867493002/
