### ISSUE TITLE
expose no-implicit-* in ddc

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27251]
Currently, analyzer-cli has flags for `--no-implicit-cast` and `--no-implicit-dynamic`.  Should these be exposed in dev_compiler as well?

FWIW, analyzer-cli has options - e.g., linting / disabling strong mode - that don't make sense in dev_compiler, so it's not obvious which ones should or should not be plumbed through (or whether we ought to be considering a more significant refactor).

@jmesserly @leafpetersen

**Comment by jmesserly** [comment]
Filed https://github.com/dart-lang/sdk/issues/27252 for the more general issue. We could also add this one as a one-off if you need it sooner.

**Comment by vsmenon** [comment]
@danrubel - we can close this, right?  :-)

**Comment by danrubel** [comment]
Fixed as part of https://codereview.chromium.org/2598593003/
