### ISSUE TITLE
Implement dput checks robustly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27258]
_From @vsmenon on May 8, 2015 16:58_

dput needs to check:
- [x] NSM for non-existent fields (for JS types too?)
- [ ] Writability (final fields, methods, no setter)
- [x] Type check - value passed in must be a subtype of field / setter type

dload needs to check:
- [x] NSM for non-existent fields (for JS types too?)

_Copied from original issue: dart-lang/dev_compiler#170_

**Comment by jacob314** [comment]
Updated checkboxes

**Comment by jmesserly** [comment]
Just tested, all of the writability checks work except final fields. We are checking the type though, which is interesting.
```
$ cat test.dart
```
```dart
class C {
  final x = "hello";
  get y => ", ";
  m() => "world!";
}

main() {
  dynamic c = new C();
  print(c.x + c.y + c.m());

  try { c.x = 1; } catch(e) { print('c.x= throws $e'); }
  try { c.x = '1'; } catch(e) { print('c.x= throws $e'); }
  try { c.y = '2'; } catch(e) { print('c.y= throws $e'); }
  try { c.m = '3'; } catch(e) { print('c.m= throws $e'); }
  print(c.x);
  print(c.y);
  print(c.m);
}
```
```
$ ddc test.dart 
```
```
hello, world!
c.x= throws Type 'int' is not a subtype of type 'String'
c.y= throws NoSuchMethodError : method not found: 'Symbol("y")'
Receiver: Instance of 'C'
Arguments: ["2"]
c.m= throws NoSuchMethodError : method not found: 'Symbol("m")'
Receiver: Instance of 'C'
Arguments: ["3"]
1
, 
Closure: () -> dynamic from: function () { [native code] }
```

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2847893002/
