### ISSUE TITLE
Support loading files via non-file: URIs

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27266]
_From @nex3 on July 27, 2016 23:23_

Currently the dev compiler only supports compiling sources with `file:` URIs. To match other implementations, it should support `http:`, `https:` and `data:` URIs as well.

This is blocking dart-lang/test#414, which needs to be able to compile from HTTP to support `pub serve`.

_Copied from original issue: dart-lang/dev_compiler#609_

**Comment by vsmenon** [comment]
_From @jmesserly on July 28, 2016 5:5_

(marked P1 if it's a blocker)

I can see how data could work, but what is http(s) supposed to do for a command line compiler? I don't see any code in analyzer_cli for it,  and none of those URI schemes seem to work for dartanalyzer (as far as I can tell). If there's some way to make this work in Analyzer I'm all for it. (And probably we should implement it in pkg:analyzer so DDC doesn't need custom logic, and all front ends can get the same URI support...)

**Comment by vsmenon** [comment]
_From @jmesserly on July 28, 2016 5:7_

Aside, the idea of a compiler needing to support HTTP is a bit crazy on principle :). But I can see how we got there with our crazy concurrency story :|

**Comment by vsmenon** [comment]
_From @jmesserly on August 11, 2016 19:58_

Hey @nex3 did you have thoughts on how we could support this? It didn't look like Analyzer has support for these URI schemes but I may have missed something.

**Comment by vsmenon** [comment]
_From @nex3 on August 11, 2016 20:6_

I don't really know the internals of analyzer that well... you may have to add support for other URI schemes in its code. Doesn't it have a fairly separate abstraction for reading inputs that you can hook into?

**Comment by nex3** [comment]
I believe this is no longer blocking `test`.

**Comment by jmesserly** [comment]
assuming stale. if we want other URI schemes in the future, we should start by making sure Analyzer/CFE support them. (DDC does not do file loading for Dart files, it relies on its front ends for URI resolution and loading)
