### ISSUE TITLE
implement dart:mirrors

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27268]
_From @vsmenon on May 27, 2015 18:28_

Implement the dart:mirrors API.  We should be able to map this to our dynamic invocation code / metadata.

_Copied from original issue: dart-lang/dev_compiler#199_

**Comment by vsmenon** [comment]
The basic parts of this (i.e., the parts used by angular) are landed.  This is still missing a lot of features - general method / function mirrors, parameter names, etc.

**Comment by vsmenon** [comment]
Angular is now using parameter annotations as well (only for constructors).

**Comment by vsmenon** [comment]
_From @jmesserly on July 13, 2015 17:13_

> Angular is now using parameter annotations as well (only for constructors).

should be easy to implement now, given that we track parameter types?

**Comment by vsmenon** [comment]
Yeah, we've already got code for class-level annotations too, mainly we just need to decide how we want to encode it.

**Comment by vsmenon** [comment]
Angular is now using `ClassMirror.owner`:

https://api.dartlang.org/1.13.0/dart-mirrors/DeclarationMirror/owner.html

This will require us to embed a pointer in classes back to the containing library in generated code.

**Comment by vsmenon** [comment]
Some more items required for Angular apps in mirrors mode:
- [ ] Implement DeclarationMirror.owner
- [ ] Implement LibraryMirror.uri
- [ ] Instance var / getter / setter / method mirrors
- [ ] Fix ClassMirror.newInstance support factory constructors

All of these will require additional compile-time metadata.

**Comment by vsmenon** [comment]
_From @eernstg on April 20, 2016 8:58_

I guess the intended workflow is such that 'reflectable' would not be helpful here, as long as it is running as a pub transformer?

**Comment by vsmenon** [comment]
Yes, this is just a convenience to run Angular2 apps without transformation.

**Comment by vsmenon** [comment]
_From @srawlins on August 1, 2016 17:47_

LibraryMirror.uri is important for some rare cases of unit testing: https://github.com/dart-lang/test/issues/110 requires this to find assets for a test.

**Comment by vsmenon** [comment]
Bumping and taking.  We need some of this for testing support.

**Comment by matanlurey** [comment]
@vsmenon I imagine you can close this?

**Comment by jmesserly** [comment]
yup! closing this now that we have deprecation plan: https://github.com/dart-lang/sdk/issues/32294
