### ISSUE TITLE
unittest tests are broken in karma runner

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27261]
_From @jmesserly on August 25, 2016 20:4_

as @vsmenon noticed, this seems to have been the case prior to our recent requirejs module change, but the breakage is more obvious now (actually reported as a failure).

Some of these tests (html ones?) are very fragile in Karma because they do a full page refresh and tend to corrupt the HTML page state.

for now I'm disabling these tests but we'll need to investigate them. What may make sense is to switch most of our tests to running in node, which would be a lot more debuggable and easy to isolate. We could then keep a handful of HTML ones.

_Copied from original issue: dart-lang/dev_compiler#631_

**Comment by vsmenon** [comment]
Looks like the reporting isn't hooked up properly to karma.  If I uncomment this line:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/test/browser/language_tests.js#L831

it prints:

```
	            220 passed,
	            3 failed
	            
	            168 errors
```

But karma only sees it as one test.

**Comment by jmesserly** [comment]
yeah that matches what I was seeing. I couldn't really triage them well because the reporting seems to be confused about which test is failing.
