### ISSUE TITLE
--package-root argument should accept a URI

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27265]
_From @nex3 on July 28, 2016 0:18_

It looks like the `--package-root` argument assumes that it's a filesystem path. To match other Dart tools, it should accept a URI instead.

This is blocking dart-lang/test#414

_Copied from original issue: dart-lang/dev_compiler#611_

**Comment by nex3** [comment]
@danrubel Did https://codereview.chromium.org/2598593003/ fix this?

**Comment by danrubel** [comment]
Not sure.

**Comment by nex3** [comment]
I tried it, and it looks like it's not yet fixed.

**Comment by jmesserly** [comment]
I believe package-root is gone in favor of the packages file
