### ISSUE TITLE
dart2js: array index moved ahead of bounds check

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27270]
The access for `a[i]` has been moved ahead of the bounds check:

```dart
var g;
sideEffect() { g = 1; }
foo(a, i) {
  var kill = false;
  if (false) kill = true;
  if (kill) sideEffect();
  if (a.length.isEven) {
    print(a[i] + 1);
  } else {
    print(a[i] + 1);
    print('---');
  }
}

main() {
  foo([1,2,3,4], 0);
  foo([], 0);
}

```

```js
    foo: function(a, i) {
      var t1, t2;
      t1 = a.length;
      t2 = a[i] + 1;
      if ((t1 & 1) === 0) {
        if (i >= t1)
          return H.ioore(a, i);
        P.print(t2);
      } else {
        if (i >= t1)
          return H.ioore(a, i);
        P.print(t2);
        P.print("---");
      }
    },
    main: function() {
      B.foo([1, 2, 3, 4], 0);
      B.foo([], 0);
    }
```

We seem to be 'saved' by the fact that JavaScript is happy with undefined indexes and CodeMotion appears not to hoist a dependent chain of operations, so the maximum two calls to CodeMotion means the value is used at most once before the check.

This appears to be related to the fact that we insert checks where needed rather than remove them when they are found to be unnecessary. HIndex has nothing to make it dependent on the check. We should make it 'witnessed' on the HBoundsCheck or other instruction(s) that makes it safe (like HTypeKnown has a data dependency on the HInvokeDynamic for receiver type strengthening.)

In the short term we should probably make HIndex unmovable.

**Comment by rakudrama** [comment]
Fixed: https://github.com/dart-lang/sdk/commit/74fee40234d73f738db8950b793460d0ae4399dd

**Comment by FMorschel** [comment]
@rakudrama why did you pin this after fixing? Was it by mistake?

**Comment by rakudrama** [comment]
> [@rakudrama](https://github.com/rakudrama) why did you pin this after fixing? Was it by mistake?

Yes, by mistake.
