### ISSUE TITLE
package:meta: @mustCallSuper should not apply to 'implements'

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27275]
Example case:

```dart
import 'package:meta/meta.dart';

/// An interface for a living breathing animal on Earth.
///
/// Animals are different sizes and may need to eat more or less.
abstract class Animal {
  /// Eat [food]. Throws exception if the animal is still hungry after eating.
  @mustCallSuper
  void eat(Food food) {
    if (isHungry) {
      throw 'Was not fed enough food!';
    }
  }

  bool get isHungry;
}
```

In this example, I'd assume that `extends Animal` triggers a warning I missed `super.eat`:

```dart
class TinyAnimal extends Animal {
  bool _isHungry = false;

  @override
  void eat(Food food) {
    _isHungry = false;
  }

  @override
  bool get isHungry => _isHungry;
}
```

However, this will _also_ (incorrectly) trigger a warning. I _can't_ call super:

```dart
class LargeAnimal implements Animal {
  bool _isHungry = false;

  @override
  void eat(Food food) {
    if (!food.isLargeAmount) {
      throw 'Large animals need large amounts of food!';
    }
    _isHungry = false;
  }

  @override
  bool get isHungry => _isHungry;
}
```

**Comment by bwilkerson** [comment]
Either that, or there should also be a hint if a class that has methods annotated with `@mustCallSuper` is implemented.

@Hixie Any thoughts?

**Comment by Hixie** [comment]
Yeah, this seems legit.

We should probably require that classes be annotate as @mixin or @interface to be used with "with" or "implements", which would address this somewhat, but that's another (already filed) bug.

**Comment by matanlurey** [comment]
In this specific case though I'd like `Animal` to be both implementable and extendable by default (Dart idioms that we see across the code base and I think are well respected). I could see the value of having `@mixin` (you _must_ mix me in) or `@interface` (you _must_ implement me), but I think those are somewhat separate.

**Comment by Hixie** [comment]
Oh yeah I'm not saying this would be required. A package would have to opt-in to this kind of thing for sure.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2348383006/

**Comment by matanlurey** [comment]
Thanks Brian!
