### ISSUE TITLE
the package bots are broken from the use of the --package-root flag

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27271]
The package bots pass `--package-root` flag into `test`, which doesn't support it anymore.

Breakage here: https://build.chromium.org/p/client.dart/builders/pkg-mac-be/builds/6555/steps/third_party%20pkg%20tests/logs/stdio

It looks like the flag was removed a few months ago: https://github.com/dart-lang/test/commit/41cb03b5b3ac529278f1e054bed9531f4d8bf09a#diff-6b8cc6265c6197edeb3a49e33b206620

But is still in use by the package bots here: https://github.com/dart-lang/sdk/blob/master/tools/bots/bot.py#L268

@nex3  @whesse

**Comment by whesse** [comment]
Fixed with https://codereview.chromium.org/2346483007
