### ISSUE TITLE
Specification issue in 16.1 Constants

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27279]
Please see Dart specification, 4th Edition (December, 2015) 16.1 Constants

> On the other hand, since implementations are free to compile code late, some
> compile-time errors may manifest quite late.
> const x = 1/0;
> final y = 1/0;
> class K {
> m1() {
> var z = false;
> if (z) {return x; }
> else { return 2;}
> }
> m2() {
> if (true) freturn y; g
> else f return 3;g
> }
> }
> An implementation is free to immediately issue a compilation error for x,...

There is no error for x and y here. Their value is Infinity. The following code should produce a compile error.
```dart
const x = 1 % 0;
final y = 1 % 0;

```

**Comment by lrhn** [comment]
Agree. I think there is at least one other place in the spec with the same problem. The operator should be either `%` or (more likely) `~/`.
