### ISSUE TITLE
Observatory: better error reporting when connecting remotely

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#27282]
I used Observatory > Connect to a VM and made a connection to localhost:12345 (where no service is running), I don't see any errors in the Observatory UI, but clicking on the connection shows a page with no data (name, address, version are blank and there are no isolates). But if I click again on Observatory > Connect to a VM it lists the connection, and shows it's connected.

If I open the web debugger I see error message on the console:

  WebSocket connection to 'ws://localhost:12345/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
  Uncaught NetworkRpcException(Canceling request: WebSocket closed due to error)

If I have the DevTools console open while doing this, it drops me into the debugger.

I would expect that when the Observatory UI attempts to make a network connection and it fails, some kind of error dialog pops up immediately with a message about the connection failure, and it shouldn't be listed as "connected" in the UI.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2340973002/

**Comment by skybrian** [comment]
Thanks!
