### ISSUE TITLE
Consistent mechanism for specifying platform/configuration

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#27283]
Today, the analyzer is using `sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart`, and dart2js is using `sdk/lib/dart_client.platform`. Given the redundancy between the two, it'd be nice to decide on one approach and use it across the board.

**Comment by lrhn** [comment]
We originally decided on the `libraries.dart` as the unified approach.
Anyone know why dart2js is now using something else? Is some feature missing from the `libraries.dart` file?

**Comment by sigmundch** [comment]
@lrhn - @sigurdm can provide more details, I cc'd you on an email chain that contains more details as well.

**Comment by bwilkerson** [comment]
The details would be interesting to others on the team as well. Can someone please provide a summary here?

**Comment by sigurdm** [comment]
`libraries.dart` works with a closed world of platforms/categories (server, client). 
When we made dartino using dart2js frontend we had a new platform that the main repo did not know about - therefore I introduced the platform files so we could configure the compiler frontend to know about a new platform without editing the dart2js source, but by pointing it to different one.
The analyzer has in parallel introduced a similar but different system of `_embedder.yaml` files describing the core library. One important difference is that the _embedder.yaml file is autodetected by existing in some package, whereas the platform file is pointed at by the executable (dart2js/dartino).

The dart VM, as far as I know gets its set of core libraries from the embedder - and doesn't care about libraries.dart.

Dartino is no longer an issue, but Flutter has its own set of core libraries too, so we have at least 3 platforms (client, server, flutter and perhaps "client+server" that is used by dart2js for testing).

I don't have any preferences on how to configure this. But I feel the approach of one data file describing each platform makes the tools more independent of the current set of platforms.

The code for configuring the platform in dart2js is not very tangled, so it should be relatively easy to adjust dart2js to use whatever format everyone can agree upon, or go back to `libraries.dart`.

**Comment by lrhn** [comment]
I fully agree that having each platform provide its own description is simpler and more extensible.

When designing something like that, it's important to focus on who the consumer of the file is. I'm guessing that the consumer of `_embedder.yaml` is the analyzer, so its purpose is to expose the API of the platform specific libraries so the user program can be analyzed when those libraries are imported.

Since you picked a different format, I'm guessing that you needed something slightly different. It's hard to make one size fit all, but I don't think it's impossible, it just takes work.

I do think we should select a single format, and external files are fine to me, but we current have three different approaches at the same time, and that's at least two too much :).





I have issues with the "embedder" name of `_embedder.yaml`, but that's secondary :)

**Comment by sigurdm** [comment]
I mainly picked a different format because I was unaware of the _embedder.yaml files.

**Comment by bwilkerson** [comment]
Personally, I'd like to move away from the `_embedder.yaml` file; I don't think it's reasonable for a package to determine the SDK, and there are no clear rules for what to do when there are multiple packages that do so. So far there is only one package that defines such a file, but I think the flutter libraries should be rolled into the (then singular) SDK. It isn't any worse to have a flutter-specific library than it is to have a web-specific library. Then we can use a single format in the SDK for all of the `dart:` libraries.

**Comment by cbracken** [comment]
Adding for x-ref purposes: #28836

We could probably de-dupe these.

**Comment by sigmundch** [comment]
Yes, let's close this in favor of #28836

We started an effort to unify using a `libraries.json` file. This is now used by the CFE and indirectly by the vm, dart2js, ddk, and flutter. My hope is to try to migrate analyzer from using libraries.dart to start using libraries.json instead.
