### ISSUE TITLE
Android timing out on precompiled vm tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27294]
On the builders like https://build.chromium.org/p/client.dart/builders/vm-precomp-android-release-1-3-be
we seem to be getting 2 to 4 random timeouts per build, when running tests.
These tests take 8 minutes and time out, and it is different tests that do it on each run.
So something is making the phones unstable.

This seems to have started Sep 9, with the roll of co19, so one of the first things to do is to see if it goes away if we stop running the co19 tests on them.  But this may be misleading, since that also means we run many fewer tests, and maybe the number of tests we run is affecting this.  I will also try manually running revisions from before the co19 roll, to see if the problem reproduces.

**Comment by whesse** [comment]
Skipping all co19 tests on android precompiled, to see if the problem disappears.  Will reenable them by section, to see if they return.

**Comment by whesse** [comment]
Random timeouts on Android precompiled vm tests are now on less than 10% of the runs.  The run on android seems to fail with exit code 15, and then timeout.  One of them had a clear error, an uncaught exception, but it didn't terminate for 8 minutes, timing out.  So something may be wrong with the error detection.

**Comment by fsc8000** [comment]
Should we try re-enabling these?
