### ISSUE TITLE
async_await_js_transform_test needs update to match changes in CL 2322323002

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27295]
CL 2322323002 changed some invocations from getting 4 arguments to 3 arguments in the transformation of code that implements async/await.

This breaks tests/compiler/dart2js/async_await_js_transform_test.dart, cf.
https://chromegw.corp.google.com/i/client.dart/builders/dart2js-linux-jsshell-3-4-be/builds/2531/steps/dart2js%20unit%20tests/logs/stdio vs.
https://chromegw.corp.google.com/i/client.dart/builders/dart2js-linux-jsshell-3-4-be/builds/2532/steps/dart2js%20unit%20tests/logs/stdio
because that test still expects 4 arguments.

**Comment by floitschG** [comment]
https://codereview.chromium.org/2335583003/
