### ISSUE TITLE
DDC isn't renaming invalid static method names

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27297]
These restrictions are only applied to static fields, not methods:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/compiler/js_names.dart#L287

We may need these for static methods as well:

http://www.ecma-international.org/ecma-262/6.0/#sec-arguments-exotic-objects

Safari 10 is complaining about the following generated code from package:stack_trace's Frame class:

``` javascript
    static caller(level) {
      if (level === void 0) level = 1;
      if (dart.notNull(level) < 0) {
        dart.throw(new core.ArgumentError("Argument [level] must be greater than or equal " + "to 0."));
      }
      return src__trace.Trace.current(dart.notNull(level) + 1).frames[dartx.first];
    }
```

Chrome and FF don't seem to have a problem with it though.

**Comment by jmesserly** [comment]
This may be a Safari bug... I'd have to track down old CL discussion, but first thing I would try is switching it to Object.defineProperty instead, and see if that works. But yeah, if not, we should treat static methods same as fields.

**Comment by vsmenon** [comment]
@alan-knight FYI - we're still hitting this on the newly released Safari 10.

**Comment by vsmenon** [comment]
Here's the current error message on Safari 10:

```
Safari 10.0.0 (Mac OS X 10.11.6) ERROR
  TypeError: Attempting to change configurable attribute of unconfigurable property.
  at /Users/vsm/dart/sdk/pkg/dev_compiler/gen/codegen_output/pkg/stack_trace.js:170
```

Getting similar with `Object.defineProperty` as well.

**Comment by vsmenon** [comment]
And if I try to inspect the existing `caller` property, I get:
```
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in strict mode.
```

**Comment by vsmenon** [comment]
@alan-knight

**Comment by jmesserly** [comment]
It looks like this was fixed in Safari (tested in a strict mode function in the console) ... we can investigate if it shows up again
