### ISSUE TITLE
Analyzer publicly is behind internal repo (pub publish?)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27301]
The latest `analyzer` package via pub still uses `PrintWriter`, while the latest version internally uses `StringBuffer` - it's hard to create code targeting some parts of the analyzer while we're out of sync.

Can be solved via pub publish perhaps?

It looks like we are synced to 60e6faa7c3357ab519fc88b3f51f39b5419eb257 internally.

**Comment by scheglov** [comment]
We continue making breaking changes to `analyzer`.
So, I would not like to publish an official `0.29.0` yet.
Would publishing `0.29.0-alpha.1` suffice for your goals?

@bwilkerson

**Comment by bwilkerson** [comment]
The other possibility is to revert this change until we're closer to being ready to publish.

I'm certainly fine with publishing an alpha version, though, if that works for @matanlurey.

**Comment by matanlurey** [comment]
If you can publish even a non-production version it will mean I can at least dev against what we have internally, otherwise I'll have to stop github development until it catches up :-/

**Comment by scheglov** [comment]
OK, I published `0.29.0-alpha.0`.
