### ISSUE TITLE
Calling an abstract method via "super" doesn't get caught by analyzer

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27300]
The analyzer does not complain about this:
```dart
abstract class A { void test(); }
class B extends A { void test() { super.test(); } }
```

**Comment by zoechi** [comment]
I'd rather have this as a lint to be able to opt-out. 
What if the overriding method doesn't care what overridden implementation does exactly, but just wants to do something before or after. 
The abstract class can get a default implementation added without breaking anything.

**Comment by Hixie** [comment]
The code above will crash at run time. The analyzer should report it, since it's statically provable that the code will crash at run time. It's basically the entire purpose of the analyzer. :-)

**Comment by zoechi** [comment]
If it crashes, then definitely. Sorry for the nose.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2364733002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/77ba5fd0871ecec19fc06806d5c2649de95f9b7c
