### ISSUE TITLE
Verify that element model resynthesized correctly when config-specific imports are present

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27304]
This issue tracks the implementation work for config-specific imports within the summary resynthesizer.  We need to ensure that when config-specific imports are in place the resynthesized element model is correct in two respects:
1. Elements representing import and export directives point to the LibraryElement corresponding to the selected configuration.
2. References are correctly resolved according to the selected configuration (e.g. if `class A extends B {}`, and `B` is obtained from a config-specific import, then `B` should be resolved to the correct element).

Note: I believe this task only requires writing tests; assuming that the summary linker has been properly modified to support config-specific imports (see #27045), the existing resynthesizer should resynthesize the element model correctly.

**Comment by scheglov** [comment]
I think the CL for resynthesizing with configured imports already includes required tests.
Well, maybe it should have been one [issue](https://github.com/dart-lang/sdk/issues/27045) - implementation and tests go hand in hand.
https://codereview.chromium.org/2353433002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f5a616834ea322eecfef4a0b705b9a195d8204dd
