### ISSUE TITLE
implement configuration specific imports

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27302]
_From @jmesserly on June 22, 2016 23:36_

See SDK bug: https://github.com/dart-lang/sdk/issues/24581

Guessing this should be pretty easy, mostly plumbing through the right configuration to Analyzer.

CC @alan-knight 

_Copied from original issue: dart-lang/dev_compiler#595_

**Comment by vsmenon** [comment]
_From @anders-sandholm on September 13, 2016 10:53_

When do you expect to see this land?

Would be great to get this landed. Look's like this might be the last bit missing in enabling a re-write of package http to use config-specific imports instead of mirrors.

**Comment by vsmenon** [comment]
Not scheduled yet.

**Comment by mit-mit** [comment]
Any news here? We now have actual usage of this in the SDK; see [package resource](https://pub.dartlang.org/packages/resource).

Updating to P1.

**Comment by vsmenon** [comment]
This should fixed by #27511 ( @bwilkerson - is there anything more?) - I'll up that to P1 as well.

**Comment by bwilkerson** [comment]
Not that I know of, except that there is now discussion of de-scoping configuration specific imports.

**Comment by vsmenon** [comment]
@munificent - not sure what the status of this is.  It might just work.  @jmesserly plumbed some support for defined variables recently.  Do we need this for 1.5 or earlier?

**Comment by mit-mit** [comment]
We need this for 1.22; Flutter also needs it now.

**Comment by munificent** [comment]
> @munificent - not sure what the status of this is.

Me either. I handed it off to @floitschG ages ago.

>  Do we need this for 1.5 or earlier?

No, it's not a [1.5 milestone language issue](https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aarea-language%20milestone%3A1.50%20).

**Comment by mit-mit** [comment]
> No, it's not a 1.5 milestone language issue.

Correct. This *pre-dates* 1.50, and should have been completed long ago. Can we please just get this done now?

CC @dgrove in case additional discussion is needed.

**Comment by dgrove** [comment]
I believe the only work here is on the Dart analyzer. I'll talk with the
analyzer team today about this.

**Comment by vsmenon** [comment]
Just tried it.  It basically already works.  This makes it more useful:

https://codereview.chromium.org/2578573003/
