### ISSUE TITLE
strip annotations when building the SDK to JS

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27312]
_From @jmesserly on April 13, 2016 18:25_

it's extra overhead for no benefit. Especially bad for dart:html with its dart2js annotations

_Copied from original issue: dart-lang/dev_compiler#493_

**Comment by vsmenon** [comment]
I think this is fixed now.  You need `--emit-metadata` to keep annotations.  We're not building the sdk with that option.
