### ISSUE TITLE
Crash with "Invalid build root."

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27328]
_From @hterkelsen on April 28, 2016 17:46_

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/dev_compiler/issues

Please include the information below in your report, along with
any other information that may help us track it down. Thanks!

```
dartdevc arguments: compile -o a.js /usr/local/google/home/het/Code/ddc_test/hello.dart
dart --version: 1.16.0-dev.5.0 (Wed Apr 13 04:21:21 2016) on "linux_x64"
```

```
Invalid build root.  /usr/local/google/home/het/Code/dev_compiler/ does not contain /usr/local/google/home/het/Code/ddc_test/hello.dart
#0      jsLibraryName (package:dev_compiler/src/compiler/code_generator.dart:3864:5)
#1      CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:199:32)
#2      CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:141:18)
#3      ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:95:26)
#4      CompileCommand.run (package:dev_compiler/src/compiler/command.dart:56:36)
#5      CommandRunner.runCommand.<anonymous closure> (package:args/command_runner.dart:176:22)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      CommandRunner.runCommand (package:args/command_runner.dart:129:16)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:103:29)
#9      Future.Future.sync (dart:async/future.dart:168)
#10     CommandRunner.run (package:args/command_runner.dart:103:11)
#11     _runCommand.<_runCommand_async_body> (file:///usr/local/google/home/het/Code/dev_compiler/bin/dartdevc.dart:61:18)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

That file definitely exists though...

```
$ ls /usr/local/google/home/het/Code/ddc_test/hello.dart
/usr/local/google/home/het/Code/ddc_test/hello.dart
```

_Copied from original issue: dart-lang/dev_compiler#530_

**Comment by jmesserly** [comment]
_From @vsmenon on April 28, 2016 17:49_

So the "--build-root" defines a root.  Library names (inside the generated JS) are relative to this root directory.  If not passed in, it defaults to the current working directory.  The compiler is complaining that the compiled file is not within the build root directory.

You can fix by passing --build-root /usr/local/google/home/het/Code/ddc_test.

**Comment by jmesserly** [comment]
_From @hterkelsen on April 28, 2016 17:52_

Got it. Adding the build root made it work. Still, I don't think this should cause the compiler to crash.

**Comment by jmesserly** [comment]
_From @vsmenon on April 28, 2016 17:54_

Yeah, we should give a better error.  No reason we can't catch / report an error at the entry point and give a nicer error.

**Comment by jmesserly** [comment]
but if it's crashing without build-root, that's a bug :)

**Comment by jmesserly** [comment]
@hterkelsen @vsmenon -- have a look at how we handle a missing `-o` option, same trick should work.
However -- we really really should autodetect pubspec.yaml. Requiring a build root is super annoying and has no user benefit 99% of the time

**Comment by jmesserly** [comment]
just hit this again. I'm going to fix it, it makes it hard to iterate on a small test

**Comment by jmesserly** [comment]
started a refactor, it's not quite as straightforward as I was hoping, going to leave for now but hope we can pick this back up after P1's are fixed

**Comment by a-siva** [comment]
I get a similar crash with command line
    dartdevc arguments: --dart-sdk=/usr/local/google/home/asiva/workspace/dart-be/sdk/out/ReleaseX64/dart-sdk --library-root=~/tmp -o /tmp/out.js /usr/local/google/home/asiva/tmp/hello.dart
    dart --version: 1.21.0-edge.103881d01c6aa2ab385f66bda0c2f5feb9cbb206 (Wed Oct 26 01:02:55 2016) on "linux_x64"
```
Invalid library root. /usr/local/google/home/asiva/workspace/dart-be/sdk/~/tmp/ does not contain /usr/local/google/home/asiva/tmp/hello.dart
#0      jsLibraryName (package:dev_compiler/src/compiler/code_generator.dart:5544)
#1      CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:254)

**Comment by jmesserly** [comment]
Yeah, invalid library root is a bit problem too :(. See https://github.com/dart-lang/sdk/issues/27262

**Comment by jmesserly** [comment]
this is a dupe of the other library-root bug
