### ISSUE TITLE
Support new JS annotation correctly

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27338]
_From @vsmenon on April 15, 2016 17:3_

I've seen the following code:

``` dart
@JS('window.location.href')
external String get _url;
```

Presumably this works in Dartium and Dart2JS?  It breaks in DDC. 

@jacob314 

_Copied from original issue: dart-lang/dev_compiler#498_

**Comment by vsmenon** [comment]
@jacob314 - is this still an open?  I think I've seen apps using it.
