### ISSUE TITLE
Fix HTML members where obj.someMethod(undefined) behaves differently from obj.someMethod()

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27340]
_From @jacob314 on May 2, 2016 23:40_

Fix HTML members where obj.someMethod(undefined) behaves differently from obj.someMethod()

Fixing this should also improve runtime performance as the fix will reduce one level of indirection in methods called.

_Copied from original issue: dart-lang/dev_compiler#544_

**Comment by vsmenon** [comment]
@jacob314 @jmesserly 

Is this still true?  I think Jenny fixed the correctness issue recently by using `apply` and forwarding all arguments:

```
    [dartx.beginPath](...args) {
      return this.beginPath.apply(this, args);
    }
```

(There is still a separate perf / code size issue - i.e., we could omit the above if we always invoked `beginPath` instead of `[dartx.beginPath]`.)

**Comment by jmesserly** [comment]
ah, yes, I fixed it! good catch :)
