### ISSUE TITLE
rationalize bazel module-root/bazel-mapping flags in ddc

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#27348]
There is some overlap between these flags. Likely both are required as a single module could contain files from genfiles and regular directories but it is possible there is an elegant solution to eliminate bazel-mapping.

**Comment by jmesserly** [comment]
how does this interact with https://github.com/dart-lang/sdk/issues/27262 ?

**Comment by jmesserly** [comment]
I think this is obsolete (or covered by other module-root bugs)
