### ISSUE TITLE
node wrapper for dart:io

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27349]
_From @jmesserly on January 29, 2016 18:8_

We can now compile & run on nodejs. But we don't have a dart:io impl.

_Copied from original issue: dart-lang/dev_compiler#436_

**Comment by jmesserly** [comment]
_From @Kleak on April 22, 2016 9:52_

Hey maybe i can help on this task.

I'm wrapping nodejs with the js package : [nodejs.dart](https://gitlab.com/grimshield/nodejs.dart)
And a beginning of electron : [electron.dart](https://gitlab.com/grimshield/electron.dart)

The only problem i have is that i am not able to launch generated js file in node with this CL 
dartdevc --v8-binary node -o build --modules node example/test_ddc_example.dart

it throw an error:
```
Error: Cannot find module 'dart/_runtime'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/kleak/Work/test_ddc/build/test_ddc_example.js:2:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by jmesserly** [comment]
_From @vsmenon on April 22, 2016 12:26_

Have you tried the preliminary node usage instructions near the end of #485 ?

**Comment by jmesserly** [comment]
_From @Kleak on April 22, 2016 12:37_

Nop, thanks, i will retry with this :)

**Comment by jmesserly** [comment]
yeah you may want to sync to "master" as well. The newer compiler won't generate "dart/_runtime" anymore, it should be trying to `require("dart_sdk")`

**Comment by jmesserly** [comment]
_From @Kleak on May 5, 2016 17:57_

ok is there a starting point where i can look how to wrap an API ? Or is it the same as with the js package ?

**Comment by Kleak** [comment]
Has i have saied i have started a wrap of node.js, this wrap follow the node.js api.
My question is : do you want the api of this be the same as the dart api ? 
if not i have move the source to github so you can take a look :)

[nodejs.dart](https://github.com/electron-dart/nodejs.dart)

All the api are not cover for the moment but the basic is almost here.

**Comment by hermanbergwerf** [comment]
Yeah this would be pretty cool. I'm building an HTML server and I want to use PugJS to render templates. I thought of creating a PugJS wrapper but realized dart:io server stuff is probably not portable to JavaScript. What is the current state of that?

**Comment by Kleak** [comment]
The library is here https://github.com/electron-dart
Not all the nodejs api is covered at this time but you have all the base.
Also this package follow the nodejs api and the electron api not the dart one.

If you have question dont hesitate yo open issues ;)

**Comment by vsmenon** [comment]
No immediate plans to do this.
