### ISSUE TITLE
Extra parentheses / precedence issue with metalet?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27347]
_From @ochafik on April 12, 2016 1:33_

``` dart
class Foo { int bar; }
main() {
  var foo = new Foo();
  print(foo..bar = 1);
}
```

Compiles very lispily:

``` js
core.print(((() => {
  foo.bar = 1;
  return foo;
})()));
```

_Copied from original issue: dart-lang/dev_compiler#489_

**Comment by jmesserly** [comment]
this sounds like an issue with js_ast precedence+printer, as that's the guy responsible for adding parens. In any case worth keeping open

**Comment by vsmenon** [comment]
Is this a bug or an output readability issue?

**Comment by jmesserly** [comment]
it is just a readability issue

**Comment by jmesserly** [comment]
MetaLet is obsolete once we migrate to Kernel/CFE. Also we could backport the Kernel approach pretty easily to DDC.
