### ISSUE TITLE
Implement assert() messages in dev_compiler

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27342]
_From @vsmenon on August 26, 2015 21:38_

This adds optional messages to an assert.

See DEP: https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md

Main bug: https://github.com/dart-lang/sdk/issues/24213

_Copied from original issue: dart-lang/dev_compiler#303_

**Comment by jmesserly** [comment]
behind a flag? Aren't *we* entirely behind a flag? ;)

**Comment by jmesserly** [comment]
(experimental language flags to an experimental compiler, we must go deeper :) )

edit: in seriousness though, I think analyzer's flag will protect us, since they're the ones doing the parsing.

**Comment by jmesserly** [comment]
oh shoot, i realized we're blocked on analyzer: https://github.com/dart-lang/sdk/issues/24217

**Comment by vsmenon** [comment]
@bwilkerson can you assign this back to me when #24217 is closed?  The DDC part should be really easy.

**Comment by dgrove** [comment]
@lrhn Can you provide an update?

**Comment by lrhn** [comment]
As far as I can see, it's implemented in dart2js and the analyzer behind flags.
I have an old CL for the VM, but it hasn't aged gracefully, so I'm working on a rewrite.

**Comment by munificent** [comment]
I'll take on the DDC side of this.
