### ISSUE TITLE
implement deferred libraries

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27343]
_From @jmesserly on August 31, 2015 16:14_

_Copied from original issue: dart-lang/dev_compiler#305_

**Comment by jmesserly** [comment]
@vsmenon just hit this

**Comment by vsmenon** [comment]
@jmesserly - can you help @munificent get started on this?  will we need any hooks in the module layer for this?

Note, we can break this into:
- [ ] Support the syntax (lib.loadLibrary().then(...)
- [ ] Actual deferring

Only the first is P1.

**Comment by jmesserly** [comment]
If you don't want to make it actually lazy, you shouldn't need anything but supporting the syntax.

**Comment by vsmenon** [comment]
That sounds like a great step 1.  Ideally, we'd enforce the laziness as well.  Let me refine the list above.

**Comment by munificent** [comment]
The P1 is done. Filed separate tracking bugs for the other two parts of this, #27776 and #27777.
