### ISSUE TITLE
Consider a website that generates JS code from Dart via DDC

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27346]
_From @sethladd on February 6, 2016 15:10_

I'm really curious what the output is of DDC. Is that documented anywhere (as examples)? Or, maybe switch dartpad.dartlang.org over to it? Or, maybe DDC can be self hosted and we can build a tiny app with DDC, compiled with DDC, to show how DDC translates Dart to JS? :)

_Copied from original issue: dart-lang/dev_compiler#442_

**Comment by jmesserly** [comment]
Here's an example: https://github.com/dart-lang/dev_compiler/tree/master/test/codegen/sunflower
Output: https://github.com/dart-lang/dev_compiler/tree/master/test/codegen/expect/sunflower

We've got a bunch of things in the works that will improve output (ES6 modules/destructuring for example are implemented but not turned on until we get Atom/Chrome support)

**Comment by jmesserly** [comment]
> Or, maybe DDC can be self hosted and we can build a tiny app with DDC, compiled with DDC, to show how DDC translates Dart to JS?

yeah that's a cool idea. Maybe a flavor of https://dartpad.dartlang.org/?

**Comment by jmesserly** [comment]
_From @lukechurch on February 17, 2016 18:34_

cc

**Comment by jmesserly** [comment]
_From @ochafik on February 17, 2016 18:43_

Chatted with @lukechurch about dartpad:
- Uses in-process analyzer, so strong mode linting might just be a matter of `new AnalysisOptionsImpl()..strongMode = true`
- Uses Analysis server for code completion: strong mode may or may not bring additional value there, but switching to it might be an "all-in" change
- Would be able to call into DDC if we provide a clean entry point function, not using files (for instance, using the same file system abstraction as the new transformer)

**Comment by jmesserly** [comment]
Awesome! Sounds great to me.

**Comment by jmesserly** [comment]
_From @lukechurch on February 23, 2016 19:48_

@ochafik I spent a few minutes looking into this - it is pretty easy to get strong mode in.

However it seems that with strong mode on the analyzer is crashing a lot. Which version of analyzer should I be using - and whom should I filed bugs for? DDC or Analyzer?

Or am I jumping the gun completely?

**Comment by jmesserly** [comment]
_From @leafpetersen on February 23, 2016 20:18_

This would be great to have, thanks for looking into it!  All strong mode crashes/bugs go in the sdk repo, area-analyzer.  You can add analyzer-strong-mode if you think it's strong mode specific, either way it will get triaged appropriately.  Stack traces are always helpful if possible.  DDC codegen bugs/crashes go in the DDC repo, but I presume that you're not there yet.

Assuming that you are just using strong mode for now (and not DDC), then I don't think it matters which version of analyzer you have, except that we're fixing bugs/adding features daily, so the fresher the better from that perspective.  If you're using DDC, then you probably want to stay with what has been published to pub, since currently the bleeding edge analyzer will sometimes get ahead of DDC.

**Comment by jmesserly** [comment]
@lukechurch I've very surprised to hear about "strong mode" crashes! Please send those our way ASAP, we have users starting to use strong mode in their IDE/command line, so those are serious issues.
 
https://github.com/dart-lang/sdk/issues/new

You can use this label to get our attention: https://github.com/dart-lang/sdk/labels/analyzer-strong-mode
Or CC myself or @leafpetersen

**Comment by jmesserly** [comment]
_From @Andersmholmgren on February 24, 2016 7:6_

Or auto submit a crash report if analyser crashes in dartpad ;-)

**Comment by jmesserly** [comment]
this might make more sense to file for Dart Pad? but I moved here for now.

**Comment by matanlurey** [comment]
+1 to this. I'd love to see a checkbox in DartPad that says "using DDC."

/cc @lukechurch and @devoncarew

**Comment by jmesserly** [comment]
assuming stale. if this issue is still relevant it should be filed elsewhere.
