### ISSUE TITLE
Add categories to API docs, and adjust front page to match.

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#27357]
http://api.dartlang.org should use categories to separate server-side (dart:io) from HTML (dart:html et al) from general-purpose libraries (dart:core, dart:async, etc.). See the Flutter API docs at http://docs.flutter.io for an example of categories (DART CORE, FLUTTER, FLUTTER_DRIVER, ...). 
- [the script flutter uses to generate API docs](https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart) (note `--use-categories`)
- [the SDK's doc generation script](https://github.com/dart-lang/sdk/blob/master/tools/bots/dart_sdk.py#L46) (BuildDartdocAPIDocs)

**Comment by kwalrath** [comment]
It seems that `--use-categories` works only for libraries within packages, but I'll test to make sure.

**Comment by srawlins** [comment]
Categories has landed! https://api.dartlang.org/dev/
