### ISSUE TITLE
non-strong mode SDK still used after turning on strong mode in analysis_options

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27358]
`WARNING: Unsound implicit cast from Iterable<dynamic> to Iterable<String> ([strong_silly] bin/main.dart:8)`

```dart
main() {
  var lines = <String>[];
  var paths = <String>[];

  var finder = new RegExp('');

  for (String line in lines.skip(1)) {
    paths.addAll(finder.allMatches(line).map((m) {
      var item = m.group(1);

      return item;
    }));
  }
}
```

Dart VM version: 1.20.0-dev.4.0 (Fri Sep  9 02:20:50 2016) on "macos_x64"

**Comment by kevmoo** [comment]
CC @jmesserly @leafpetersen

**Comment by kevmoo** [comment]
Then I got fancy

```dart
main() {
  var lines = <String>[];
  var paths = <String>[];

  var finder = new RegExp('');

  for (var line in lines.skip(1)) {
    paths.addAll(finder.allMatches(line).map/*<int>*/((m) {
      var item = m.group(1);

      return item;
    }));
  }
}
```

```
ERROR: The type '((Match) → dynamic) → Iterable<dynamic>' is declared with 0 type parameters, but 1 type arguments were given ([strong_silly] bin/main.dart:8)
WARNING: Unsound implicit cast from Iterable<dynamic> to Iterable<String> ([strong_silly] bin/main.dart:8)
```

Doesn't `map` have a type paramater? Weirdness...

**Comment by kevmoo** [comment]
FYI: this only happens if I don't restart the analyzer after changing `.analysis_options`

After restart, all is good. 😕

**Comment by jmesserly** [comment]
> FYI: this only happens if I don't restart the analyzer after changing .analysis_options

sounds like a bug where the AnalysisContext was not in Strong Mode. @bwilkerson might be the best person to take a look. I don't know what is responsible for noticing a change in .analysis_options and making sure we analyze against the strong mode SDK.

**Comment by jmesserly** [comment]
@kevmoo I tried to capture that in the subject

**Comment by scheglov** [comment]
https://codereview.chromium.org/2361203004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/09b0bba932c3403b7fa414eec69048af69f85621

**Comment by jmesserly** [comment]
Nice!
