### ISSUE TITLE
Support for @checked on fields

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27363]
```dart
import 'package:meta/meta.dart';

class A {
  get foo => '';
  set foo(_) {}
}

class B extends A {
  @checked
  int foo;
}
```

Currently this code reports an error `ERROR: Invalid override. The type of B.foo= ((int) → void) is not a subtype of A.foo= ((dynamic) → void). ([analyzer] bin/test.dart:10)`. 

But if I encapsulate the field, then it works fine.

```dart
import 'package:meta/meta.dart';

class A {
  get foo => '';
  set foo(_) {}
}

class B extends A {
  int _foo;

  int get foo => _foo;

  void set foo(@checked int foo) {
    _foo = foo;
  }
}
```

Can / should we make it work similarly for the field case?

**Comment by scheglov** [comment]
@keertip

**Comment by jmesserly** [comment]
Great question! -- @leafpetersen thoughts?

**Comment by leafpetersen** [comment]
This sounds good to me.

**Comment by leafpetersen** [comment]
@sethladd

**Comment by sethladd** [comment]
Thanks! I'll ask if we can queue this up to test out and send over feedback.

**Comment by sethladd** [comment]
Related to https://github.com/dart-lang/sdk/issues/25578

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2346143003/

**Comment by leafpetersen** [comment]
If this doesn't already, we may want to consider making this imply `@virtual`.  There's kind of no point otherwise, and I'm not sure there's any benefit in requiring both annotations.

**Comment by jmesserly** [comment]
@leafpetersen - here's a possible counter example?
```dart
abstract class BaseView {
  List<View> get children { ... }
}
// intended to be sealed
class MyAppView {
  @checked final children = <MyChildView>[];
}
```

**Comment by jmesserly** [comment]
I'd hit send too fast, updated above example.

**Comment by leafpetersen** [comment]
Ah good point.
