### ISSUE TITLE
vm/cc tests of dart2js must use .packages instead of package root

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27369]
The vm cc tests use a shortcut to resolve packages in some of their tests, like vm/cc/Dart2JSCompileAll.

This needs to be fixed, and it looks like it may need async dart code to run.  The tests will be marked as failing until then.  I have a partial solution CL that loads and stores the .packages file, but using it to resolve URLs is a TODO.

The failing tests are
vm/cc/Dart2JSCompilerStats
vm/cc/Dart2JSCompileAll

**Comment by whesse** [comment]
CL is https://codereview.chromium.org/2342323003

**Comment by a-siva** [comment]
The Dart2JSCompileAll benchmark has been reworded to use a dill file and does not need a way of resolving package root.
