### ISSUE TITLE
Analyzer doesn't skip comments

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27368]
Example of the code:

```dart
abstract class A<T> {
  B foo([var param]);
  B/*<E>*/ bar/*<E>*/([var/*=E*/ param]);
}

class B<T> {}

class C implements A {
  @override
  B foo([var param]) => null;

  @override
  B bar([var param]) => null;
}

main() {
}
```

Dartanalyzer in a strong mode reports:
[error] Invalid override. The type of C.bar (([dynamic]) ΓåÆ B<dynamic>) is not a subtype of A<dynamic>.bar (<E>([E]) ΓåÆ B<E>). (tst_1.dart, line 13, col 3)

Tested on dartanalyzer version 1.19.1
Dart VM version: 1.19.1 (Wed Sep 07 09:07:46 2016) on "windows_x64"

**Comment by leafpetersen** [comment]
I'm not sure I understand where the bug is?  That's an invalid override. Strong mode should never ignore the generic method comment syntax, I don't think.  This seems to be working as intended to me, let me know if I've misunderstood something.
