### ISSUE TITLE
Dartium build breaks after change to allow OS-provided root certs

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27377]
The commit https://github.com/dart-lang/sdk/commit/139db22be5f515b49270f6eae80ff7ecbfab1620 breaks builds of dartium.

The error is unresolved external symbol "char const * const dart::bin::commandline_root_certs_file" (?commandline_root_certs_file@bin@dart@@3PBDB) referenced in function "bool __cdecl dart::bin::ProcessRootCertsFileOption(char const *,class dart::bin::CommandLineOptions *)" (?

Full error:
FAILED: dart_bootstrap.exe dart_bootstrap.exe.pdb 
E:\b\depot_tools\python276_bin\python.exe gyp-win-tool link-with-manifests environment.x86 True dart_bootstrap.exe "E:\b\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:dart_bootstrap.exe @dart_bootstrap.exe.rsp" 1 mt.exe rc.exe "obj\dart\runtime\dart_bootstrap.dart_bootstrap.exe.intermediate.manifest" obj\dart\runtime\dart_bootstrap.dart_bootstrap.exe.generated.manifest ..\..\build\win\compatibility.manifest
dart_bootstrap.main.obj : error LNK2019: unresolved external symbol "char const * const dart::bin::commandline_root_certs_file" (?commandline_root_certs_file@bin@dart@@3PBDB) referenced in function "bool __cdecl dart::bin::ProcessRootCertsFileOption(char const *,class dart::bin::CommandLineOptions *)" (?ProcessRootCertsFileOption@bin@dart@@YA_NPBDPAVCommandLineOptions@12@@Z)
dart_bootstrap.main.obj : error LNK2019: unresolved external symbol "char const * const dart::bin::commandline_root_certs_cache" (?commandline_root_certs_cache@bin@dart@@3PBDB) referenced in function "bool __cdecl dart::bin::ProcessRootCertsFileOption(char const *,class dart::bin::CommandLineOptions *)" (?ProcessRootCertsFileOption@bin@dart@@YA_NPBDPAVCommandLineOptions@12@@Z)
dart_bootstrap.exe : fatal error LNK1120: 2 unresolved externals

@zanderso @terrylucas @alan-knight

**Comment by zanderso** [comment]
Should be fixed by https://github.com/dart-lang/sdk/commit/509e6f3eb3353fa677716e01094d4f39b26398c8

**Comment by zanderso** [comment]
Build is fixed.
