### ISSUE TITLE
Command-line analyzer doesn't correctly locate analysis options file

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27375]
If the working directory is above a package, then analyzer appears to not find the analysis options file in that package, even when analyzing a file inside the package. For example, in the root of the SDK checkout, run:

```
dartanalyzer pkg/analyzer_cli/tool/perf.dart
```

This will be run without strong mode enabled despite the fact that the options file in `analyzer_cli` specifies that the project is strong mode. I think it ought to search from the directory containing the file being analyzed rather than the working directory.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2355413005

**Comment by scheglov** [comment]
75a4f968beb01b2023500e0e6a09c605d474064f

**Comment by scheglov** [comment]
The changes was rolled back because of multiple test failures.

**Comment by pq** [comment]
@scheglov : I *think* that fix got re-applied and we can close this.  Or?

**Comment by scheglov** [comment]
Yes, it got.

**Comment by pq** [comment]
Groovy.  Thanks for confirming!
