### ISSUE TITLE
Wrong analyzer error message when unnamed constructor returns wrong type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27387]
The code is the following:

``` dart
abstract class I<T> {
  factory I() {
    return new C<T>();
  }
}

class C<T> implements I {
}

main() {
  new C();
  new I();
}
```

Analizer output (in a strong mode) is: `[error] The return type 'C<T>' is not a 'I<T>', as defined by the method ''`

Note empty method name in an error message. Tested in dartanalyzer version 1.20.0-dev.5.0

**Comment by jmesserly** [comment]
Thanks for filing this! Referring to the unnamed constructor with `''` is confusing.

However it is not a strong mode specific error, so I'm going to adjust the labels.
Here is the non-strong-mode repro:
```dart
abstract class I<T> {
  factory I() {
    return new C<T>();
  }
}

class C<T> {
}

main() {
  new C();
  new I();
}
```
```
[warning] The return type 'C<T>' is not a 'I<T>', as defined by the method ''.
```
