### ISSUE TITLE
lib_env_test/has_[no_]io_support has changed on browsers

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27398]
The status of the tests 
 language/library_env_test/has_no_io_support
 language/library_env_test/has_io_support
has swapped on browsers using dart2js.  Now 
language/library_env_test/has_no_io_support passes, and
language/library_env_test/has_io_support fails.

This is on linux ff, chrome, drt, windows chrome, at least.
Status updated in tests/language/language_dart2js.status

**Comment by lrhn** [comment]
I recently fixed a bug in how dart2js detects whether io is available. That could cause the issue.

**Comment by sigmundch** [comment]
closing as obsolete.
