### ISSUE TITLE
Change the default of pub get/update --packages-dir to false

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27399]
- [x] Complete https://github.com/dart-lang/pub/issues/1450
- [ ] Pull latest pub into SDK

**Comment by mit-mit** [comment]
How is this going?

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/pub/issues/1450#issuecomment-249731843 – @munificent is "on it"

**Comment by munificent** [comment]
https://codereview.chromium.org/2377063002/

**Comment by mit-mit** [comment]
Marking pub work item complete. We still need to merge this to 1.20.

**Comment by kevmoo** [comment]
Closed by https://github.com/dart-lang/sdk/commit/c20e2a0883a43a75ac18d5db6f8d32dfabf34f83
