### ISSUE TITLE
Regression on map literal inference?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27408]
Tests with this snippet started triggering strong mode errors.  The variable `map` below is inferred to have type `Map<Object, int>` even though `n(b)` could return a string.

```dart
main() {
  bool b = false;

  var map = {
    b: 0,
    m(b): n(b),
    b ? 1 : "foo": 2,
  };

  map['42'] = "hello";
}

m(bool b) => b ? 2 : "bar";
n(bool b) => b ? 3 : "baz";
```

The error is on the assignment to `map['42']`:
```
[error] A value of type 'String' cannot be assigned to a variable of type 'int' (mapinfer.dart, line 12, col 15)
```

**Comment by vsmenon** [comment]
@jmesserly @leafpetersen This seems to have also popped up yesterday.

BTW, the following assignments trigger no error:
```
  int x = n(b);
  String y = n(b);
```

suggesting the problem is inferring the type of `map`, not `n`.

**Comment by jmesserly** [comment]
@vsmenon - we ignore "dynamic" in inference. m/n return dynamic so those are ignored.

whether it's a good idea I'm not sure. Interesting data.

**Comment by jmesserly** [comment]
it was caused by this design change: https://github.com/dart-lang/sdk/commit/8c25a41accf52265a89bcc2ffac3bdb7c271f9fb

**Comment by leafpetersen** [comment]
@jmesserly maybe we should chat about this today and decide whether this is the behavior we want or not.

**Comment by jmesserly** [comment]
Agreed, I've definitely heard some feedback that "ignore dynamic" may have had a larger effect than anticipated. FWIW, it'd be super easy to revert https://github.com/dart-lang/sdk/commit/8c25a41accf52265a89bcc2ffac3bdb7c271f9fb, it's basically a 1-line change

**Comment by jmesserly** [comment]
if we're going to do it, before the next roll to dev branch/internal codebase would be a good time IMO
