### ISSUE TITLE
SuperExpression.staticType points to unexpected type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27404]
When analyzing code like this:

```
class A { f() {} }
class B extends A { f() { super.f(); } }
```

Analyzer sets the `staticType` of `super` to the InterfaceType of `B`.  I would have expected it to set it to `A`.

Complication: what should we do if there are mixins involved, e.g.:

```
class A { f() {} }
class M { f() {} }
class B extends A with M { f() { super.f(); } }
```

Arguably, in this case, the `staticType` of `super` should point to the synthetic class `A with M` which is implicitly defined by `B`'s "extends" clause.  But analyzer has no such entity in its element model.

**Comment by stereotype441** [comment]
@jwren FYI

**Comment by scheglov** [comment]
I believe that `super` should not have any type at all.
It is not really an expression, it is a "qualifier".

**Comment by stereotype441** [comment]
Fair enough.  What was I thinking four years ago? :)
