### ISSUE TITLE
DDC is broken by removal of element summaries

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27403]
this happened in a recent Analyzer CL.

DDC needs to emit summaries for command line users, as well as for its own build SDK step. We're currently broken until this is fixed.

**Comment by bwilkerson** [comment]
@scheglov @stereotype441

**Comment by jmesserly** [comment]
CC @vsmenon @scheglov @stereotype441 

I'm trying to fix it but I haven't gotten it working yet.
Here is my progress: https://codereview.chromium.org/2353133004

**Comment by jmesserly** [comment]
It looks like the summaryDataStore being null isn't supported, I'll have to study further what changed. There must be a way to get it working since it works in Analyzer CLI...

**Comment by stereotype441** [comment]
If there are no input summaries, you should be able to just construct a SummaryDataStore passing it an empty list for `summaryPaths`.

**Comment by jmesserly** [comment]
awesome thanks for the help, I'm getting closer for sure...

**Comment by jmesserly** [comment]
I think I got past most of it. The problem I have now is trying to figure out how to get DDC's build of its own SDK working.

**Comment by scheglov** [comment]
If you mean the summary of DDC's SDK, then you might want to look at analyzer's implementation.
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/summary/summary_file_builder.dart

**Comment by jmesserly** [comment]
ah I think I got that part working.

**Comment by jmesserly** [comment]
@scheglov it's tricky because we treat the SDK more or less like a normal input to DDC, so it runs through the same summarization. Kind of like if you replaced that script with normal analyzer_cli "build mode".

... but yeah it does seem to work now. I had to be careful about not adding the SDK bundle when we're compiling the SDK itself.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2353133004/

**Comment by jmesserly** [comment]
thanks so much everyone for helping me on this 🎉
