### ISSUE TITLE
<unknown Dart function> uses >50% in Observatory

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27409]
This did not happen couple of weeks ago.

As you understand, this makes this profiling information not so useful.

I run VM with the following flags: `--observe --max_profile_depth=128 --collect_code=false --code_comments=true --old_gen_growth_rate=2800`. Should I make some changes?

![image](https://cloud.githubusercontent.com/assets/384794/18721044/74d48d42-7fe3-11e6-8867-667e796f9120.png)

**Comment by rmacnak-google** [comment]
Not actionable without a reproduction.
