### ISSUE TITLE
Socket.connect with out-of-range port number crashes program with "Valid outside expected range"

### ISSUE THREAD

**Issue by hoylen** [dart-lang/sdk#27416]
If an invalid port number (i.e. a number that is outside the range of 0 to 65535) is passed into the [Socket](https://api.dartlang.org/stable/1.19.1/dart-io/Socket/connect.html) `connect` method, the program crashes with an error message that says:

    Value outside expected range

It doesn't thrown an exception, but simply crashes.

Here's an example:

```dart
try {
    var s = await Socket.connect("localhost", 65536); // invalid port number
} catch (e) {
    print("Got exception: $e"); // never gets to here
}
print("Got to here"); // never gets to here
```
The `connect` method _should_ thrown an exception which can be caught by the program. It does throw exceptions in other situations, such as an port that is not being listened to.

With the current behaviour, there is no way for the program to recover from the error. The program can only check the value themselves, before calling `Socket.connect`, instead of relying on catching exceptions for error handling.

**Comment by sgjesse** [comment]
This is caused by
```
Dart_PropagateError(Dart_NewApiError("Value outside expected range"));
```
in [`socket.cc`](https://github.com/dart-lang/sdk/blob/60ede136178f38f0ae71052f5b0cafc2f0b663da/runtime/bin/socket.cc#L885)

These API errors cannot be caught, and the Dart code in `dart:io` should make sure not to pass invalid arguments to the native implementation.

**Comment by hoylen** [comment]
Yes, that would work: changing the Dart code in `dart:io` to check the range before passing it to the native implementation, and throwing an exception if it is not in range.

Alternatively, can the native implementation be changed to not be an API error? API errors can't be caught, but does it have to be an API error? That seems to be the only use of `Dart_newApiError` in [socket.cc](https://github.com/dart-lang/sdk/blob/60ede136178f38f0ae71052f5b0cafc2f0b663da/runtime/bin/socket.cc#L885). Elsewhere, it raises a Dart exception using `Dart_SetReturnValue(args, DartUtils::NewDartOSError())` -- though I don't know if that is appropriate in this situation.

**Comment by johnmccutchan** [comment]
@zanderso
