### ISSUE TITLE
js-interop: Missing documentation for v0.6.1

### ISSUE THREAD

**Issue by smrw** [dart-lang/sdk#27415]
On pub.dartlang.org/packages/js, the documentation is for version 0.6.0. And www.dartdocs.org/documentation/js/0.6.1/ does not exist. It seems there was a build failure for the documentation (see www.dartdocs.org/documentation/js/0.6.1/log.txt)

**Comment by kwalrath** [comment]
It looks like js's dependency on 1.19 is the issue. @astashov, now that 1.19.1 has fixed the dartdoc breakage, could we update dartdocs.org to use that?

**Comment by astashov** [comment]
Can I start using the dev version again? 1.20.whatever-dev?

**Comment by kwalrath** [comment]
Yes, I think so. At least, I don't know of any reason why it wouldn't work, and it seems good to use the latest.

**Comment by srawlins** [comment]
This issue is for `package:js`, rather than `dart:js`. Switching labels.

**Comment by kwalrath** [comment]
The link http://www.dartdocs.org/documentation/js/0.6.1/ now forwards to https://pub.dartlang.org/documentation/js/0.6.1/, which looks ok to me. I'm closing this.
