### ISSUE TITLE
Enable using pub summaries by default (remove the flag)

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27420]
Currently [Summary discovery for packages downloaded from pub](#26792) is implemented in analyzer and analysis server, but it requires using `--enable-pub-summary-manager` flag to enable the feature. The reason is that we want to dogfood it before enabling for wider audience. Unfortunately using pub summaries (and dogfooding `--enable-pub-summary-manager`) requires a new version of IntelliJ.

**Comment by natebosch** [comment]
I don't think I can find this flag anymore and the meta issue is closed.
