### ISSUE TITLE
Dart analyzer (strong mode) allows wrong type for assert argument 

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#27426]
The `assert` statement expects either bool argument or function with no arguments, returning `bool`.
The following code demonstrates the problem:

``` dart
foo()  {
  return 1;
}

main() {
  assert (foo);
}
```

Dart analyzer  (strong mode) does not find any issue in this code.
There is no boolean conversion for strict mode, so I believe some issue should be reported for this code.

**Comment by alsemenov** [comment]
issue #26002 is also actual for strong mode.
The code 
```
bool foo(x) {
  return false;
}

main() {
  assert (foo);
}
```
does not cause any issues with Dart analyzer (strong mode)

**Comment by lrhn** [comment]
Looks like a bug. If you try to assing `foo` to a variable of type `()->bool`, you do get a warning, so the type check is missing for assert.

**Comment by srawlins** [comment]
`assert` now only accepts a bool, not a function. This bug is obsolete.
