### ISSUE TITLE
html apis that take optional parameters don't work anymore

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27429]
_From @jmesserly on August 22, 2016 16:22_

running sunflower I see this error:
```
TypeError: Failed to execute 'stroke' on 'CanvasRenderingContext2D': parameter 1 is not of type 'Path2D'.(…)
```
it's coming from this method:
```dart
  /// Draw a small circle representing a seed centered at (x,y).
  void draw(CanvasRenderingContext2D context) {
    context
      ..beginPath()
      ..lineWidth = 2
      ..fillStyle = color
      ..strokeStyle = color
      ..arc(x, y, radius, 0, TAU, false)
      ..fill()
      ..closePath()
      ..stroke();
  }
```
The code that implements "stroke" is:
```js
    [dartx.stroke](path) {
      return this.stroke(path);
    }
```
The runtime value there is "undefined"

_Copied from original issue: dart-lang/dev_compiler#628_

**Comment by vsmenon** [comment]
_From @jmesserly on August 22, 2016 16:22_

@jacob314 seen anything like this before?

**Comment by vsmenon** [comment]
The nicest solution would be to handle this caller side.  I.e., anything calling a DOM API that simply forwards just calls the forwarded API instead.

E.g., generate `context.stroke()` instead of `context[dartx.stroke]()`.

This wouldn't work for overridable methods (e.g., CustomElements) though.  The old solution in dart2js / dartium was something like:

```
    [dartx.stroke](path) {
      if (path == void 0) {
        return this.stroke();
      } else {
        return this.stroke(path);
      }
    }
```

**Comment by kevmoo** [comment]
Hitting this with `clip()` call when I pass in zero arguments.

**Comment by jmesserly** [comment]
I can help out with this. Question for @vsmenon if you see this:
> This wouldn't work for overridable methods (e.g., CustomElements) though.

I think you meant "this wouldn't work for methods that are renamed in dart:html or have custom implementations" ? Because that's the main reason we symbolize methods: so any Dart code implemented things don't clobber methods on the native classes.

**Comment by jmesserly** [comment]
(e.g. we use symbols for JSArray even though it's a sealed type, so the Dart methods don't show up there. dart:html types are a bit different in that we can often directly call the native method, skipping the wrapper)

**Comment by vsmenon** [comment]
Thanks for taking this!

Yes, something like `append` to `appendChild` would be tricky.  If we have a rename and optional args, we might need to do the explicit dispatch.  But, you're right, that's not the common case.  :-)  

It seems like members that are straight pass-throughs to JS could always be treated and code-gen'ed as such (no symbol in the first place).

BTW, you might be interested in #27672 if you need to recover this from the sdk summary.

**Comment by jmesserly** [comment]
I think we're okay at the moment recovering things from the SDK summary? If not, we'd be super broken on travis.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2454173003 pretty straightforward fix for the functionality. We may want to get rid of the wrappers at some point, but that's a harder to untangle.

**Comment by jmesserly** [comment]
filed https://github.com/dart-lang/sdk/issues/27677 to track possible future performance/code size improvements
