### ISSUE TITLE
DDC error threading constructor super calls

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27421]
The following Dart code prints `null` in DDC and `false` in the VM.  In the DDC generated code, the constructor for `C` is not calling `super`.

```dart
abstract class A {
  bool _x = false;
}

abstract class B extends A {
  
}

class C extends B {
  C() {
  }
}

main() {
  var b = new C();
  print(b._x);
}
```

**Comment by jmesserly** [comment]
Class C is generated incorrectly:
```js
  test.C = class C extends test.B {
    new() {
    }
  };
```
I guess Analyzer does not create an implicit super in this case.

**Comment by jmesserly** [comment]
got a fix. seeing if any existing tests covered it, otherwise I'll add this one.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2365053003/
