### ISSUE TITLE
Dart analyzer report private members as undefined

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#27435]
Dart analyzer report private members as undefined.
The following code demonstrates this:
lib.dart

``` dart
class ClassWithPrivateMembers {
 static var _staticvar = "abyrvalg";
}
```

test.dart

``` dart
import "lib.dart";

main() {
  ClassWithPrivateMembers._staticvar = 1;
}
```

Dart analyzer output:

> [warning] The setter '_staticvar' is not defined for the class 'ClassWithPrivateMembers'.

In strong mode it is an error message.

I suggest to improve the message. It should state that `_staticvar` is a private member of class `ClassWithPrivateMembers` and is not accessible in the current context.

**Comment by keertip** [comment]
Don't see this error anymore.
