### ISSUE TITLE
service/debugger_location_test is timing out a lot

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27434]
PID 22454 - process
TID 22454:
#0  0x0000000000961c93 dart::ObjectSet::Contains(dart::RawObject*) const
#1  0x0000000000961668 dart::VerifyPointersVisitor::VisitPointers(dart::RawObject**, dart::RawObject**)
#2  0x00000000008c40f8 dart::RawArray::VisitArrayPointers(dart::RawArray*, dart::ObjectPointerVisitor*)
#3  0x00000000008bf0a6 dart::RawObject::VisitPointers(dart::ObjectPointerVisitor*)
#4  0x000000000086388b dart::HeapPage::VisitObjectPointers(dart::ObjectPointerVisitor*) const
#5  0x000000000086553b dart::PageSpace::VisitObjectPointers(dart::ObjectPointerVisitor*) const
#6  0x0000000000711103 dart::Heap::VerifyGC(dart::MarkExpectation) const
#7  0x0000000000710fea dart::Heap::Verify(dart::MarkExpectation) const
#8  0x00000000007810cb dart::Isolate::Shutdown()
#9  0x000000000066f89a dart::Dart::ShutdownIsolate()
#10 0x000000000058bfcc Dart_ShutdownIsolate
#11 0x000000000057a892 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#12 0x000000000057c2e6 dart::bin::main(int, char**)
#13 0x000000000057cca9 main
#14 0x00007f8f6ea5ef45 __libc_start_main
#15 0x000000000057a4a8 _start
TID 22455:
#0  0x00007f8f6eb37a13 epoll_wait
#1  0x00000000005cf9b5 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x00000000005cb10e dart::bin::ThreadStart(void*)
#3  0x00007f8f6fa36184 start_thread
#4  0x00007f8f6eb3737d __clone
TID 22456:
#0  0x00007f8f6fa3a7be pthread_cond_timedwait@@GLIBC_2.3.2
#1  0x0000000000863216 dart::Monitor::WaitMicros(long)
#2  0x0000000000953a1f dart::ThreadInterrupter::ThreadMain(unsigned long)
#3  0x0000000000861fbe dart::ThreadStart(void*)
#4  0x00007f8f6fa36184 start_thread
#5  0x00007f8f6eb3737d __clone
TID 22483:
#0  0x00007f8f6fa3a404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x000000000086323e dart::Monitor::WaitMicros(long)
#2  0x000000000065fc0a dart::BackgroundCompiler::Run()
#3  0x0000000000955147 dart::ThreadPool::Worker::Loop()
#4  0x0000000000954f8a dart::ThreadPool::Worker::Main(unsigned long)
#5  0x0000000000861fbe dart::ThreadStart(void*)
#6  0x00007f8f6fa36184 start_thread
#7  0x00007f8f6eb3737d __clone
TID 22519:
#0  0x00007f8f6fa3a404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00000000005cbf1c dart::bin::Monitor::WaitMicros(long)
#2  0x00000000005d6952 dart::bin::ExitCodeHandler::ExitCodeHandlerEntry(unsigned long)
#3  0x00000000005cb10e dart::bin::ThreadStart(void*)
#4  0x00007f8f6fa36184 start_thread
#5  0x00007f8f6eb3737d __clone

FAILED: none-vm debug_x64 service/debugger_location_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/debugger_location_test.dart
Observatory listening on http://127.0.0.1:51004
** Signaled to run test queries on 51004

Loading VM...
Done loading VM
Running debugger_location_test.dart [1/23]
Paused with PauseBreakpoint
Running debugger_location_test.dart [2/23]
Running debugger_location_test.dart [3/23]
Running debugger_location_test.dart [4/23]
Running debugger_location_test.dart [5/23]
Running debugger_location_test.dart [6/23]
Running debugger_location_test.dart [7/23]

bit length overflow
code 18 bits 6->7
Running debugger_location_test.dart [8/23]
Running debugger_location_test.dart [9/23]

bit length overflow
code 17 bits 6->7

bit length overflow
code 18 bits 6->7

bit length overflow
code 18 bits 6->7
Running debugger_location_test.dart [10/23]
Running debugger_location_test.dart [11/23]
Running debugger_location_test.dart [12/23]
Running debugger_location_test.dart [13/23]
Running debugger_location_test.dart [14/23]
Running debugger_location_test.dart [15/23]
Running debugger_location_test.dart [16/23]
Running debugger_location_test.dart [17/23]
Running debugger_location_test.dart [18/23]
Running debugger_location_test.dart [19/23]
Running debugger_location_test.dart [20/23]
Running debugger_location_test.dart [21/23]
Running debugger_location_test.dart [22/23]
Running debugger_location_test.dart [23/23]
** Killing script
** Process exited

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/debugger_location_test.dart
Took 0:02:00.163575

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 --packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages service/debugger_location_test

**Comment by johnmccutchan** [comment]
@turnidge

**Comment by johnmccutchan** [comment]
The test runs slowly on my Z620 so I've split it into separate tests:

https://codereview.chromium.org/2376433003/
