### ISSUE TITLE
Analyzer reports a bogus hint when a list is assigned in a try and then mapped

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27449]
When run on the following code:

```dart
main(List<String> args) {
  var list;
  try {
    list = <String>[];
  } on FormatException catch (_) {
    return;
  }

  list.map((value) => '$value');
}
```

the analyzer reports

```
[hint] The argument type '(dynamic) → String' cannot be assigned to the parameter type '(String) → dynamic'.
```

for the `.map()` line. I'd either expect downward inference to cause the function argument to be typed as `String`, or I'd expect the whole thing to be dynamic because `list` was declared without an initializer.

This appears in 1.19 and bleeding edge, but not in 1.18.

**Comment by jmesserly** [comment]
This looks like another propagated type hint creeping up. I thought we'd disabled it for strong mode but perhaps not yet. Leaf were you looking into it? If not pretty easy for me to track down.

**Comment by jmesserly** [comment]
The same issue is also covered by this bug with some discussion: https://github.com/dart-lang/sdk/issues/27135

**Comment by leafpetersen** [comment]
All yours if you want it.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2380863003/
