### ISSUE TITLE
URI parsing on Windows

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#27450]
There is a problem parsing the URI when running in the windows command line. The file path gets truncated down to just `c:`

It does work fine when compiling with --no-source-maps.

```
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --modules=legacy --single-out-file --inline-source-map -p packages\ -o gen\js.js package:js/js.d
art
    dart --version: 1.19.1 (Wed Sep 07 09:07:46 2016) on "windows_x64"

Invalid argument(s): Uri c: must have scheme 'file:'.
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:73:7)
#1      Context.fromUri (package:path/src/context.dart:834:18)
#2      fromUri (package:path/path.dart:354:32)
#3      placeSourceMap.transformUri (package:dev_compiler/src/compiler/compiler.dart:506:37)
#4      placeSourceMap (package:dev_compiler/src/compiler/compiler.dart:510:27)
#5      JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:426:11)
#6      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:455:16)
#7      _compile (package:dev_compiler/src/compiler/command.dart:149:12)
#8      compile (package:dev_compiler/src/compiler/command.dart:51:5)
#9      main.<main_async_body> (file:///c:/Users/nshahan/code/dart-sdk/sdk/pkg/dev_compiler/bin/dartdevc.dart:51:16)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by kevmoo** [comment]
@vsmenon Are we going to look at this for 1.21?

**Comment by vsmenon** [comment]
No, it will slip.  Updated milestone.

**Comment by vsmenon** [comment]
@nshahan - do you have time to retry your CL?

**Comment by nshahan** [comment]
@vsmenon I don't think it makes sense to work on this until we can reliably run `bazelify init` and `bazel build` on Windows. Without that, there is no realistic tests scenario for us to try. We could possibly use `tools/global_compile.dart` to try and test with but that is what got me into the situation where I ended up reverting my change. It worked fine with global_compile.dart, but broke with blaze/bazel on linux.

**Comment by vsmenon** [comment]
@jakemac53 @alan-knight 

FYI - this is one of the issues we'll need to fix for DDC / Win.  Note, Nick had a fix above but had to revert for some reason.

**Comment by jakemac53** [comment]
See also https://github.com/dart-lang/sdk/issues/28752 and https://github.com/dart-lang/sdk/issues/27797 which might be duplicates or are at least related?
