### ISSUE TITLE
Dartanalyzer allows fields override in a strong mode for mixins

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27452]
In a strong mode it is prohibited to override fields. Therefore Analyzer in a strong mode reports an error for the following code

``` dart
class A {
  int x = 0;
}
class M {
  int x = 1;
}
class C extends A with M {
}
main() {
}
```

Analyzer output in this case is

>  [error] Field declaration A.x cannot be overridden in M.

But it doesn't report any issues for the following code

``` dart
class A {
  int x = 0;
}
class M {
  int x = 1;
}
class C = A with M;
main() {
}
```

It should be the same error in the case above. 
Tested on dartanalyzer version 1.20.0-dev.7.0

**Comment by bwilkerson** [comment]
My understanding is that strong mode is going to be relaxed to allow field overriding, so this might become a non-issue.

**Comment by jmesserly** [comment]
> My understanding is that strong mode is going to be relaxed to allow field overriding, so this might become a non-issue.

whatever the default, we still need something to indicate fields are sealed, though. So this bug is important to get fixed.

**Comment by jmesserly** [comment]
merging this into https://github.com/dart-lang/sdk/issues/27502#issuecomment-289844376

**Comment by jmesserly** [comment]
Digging deeper, this appears more serious than I thought and affects much more than fields. I've filed: https://github.com/dart-lang/sdk/issues/29426
