### ISSUE TITLE
VM doesn't initialize lazy variable correctly if it has been read during initialization.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27466]
Spec says:
> Non-constant variable declaration with initializer. If d is of one of the forms ... and no value has yet been stored into `v` then the initializer expression `e` is evaluated. If, during the evaluation of `e`, the getter for `v` is invoked, a `CyclicInitializationError` is thrown. If the evaluation succeeded yielding an object `o`, let `r` = `o`, otherwise let `r` = `null`. In any case, `r` is stored into `v`. The result of executing the getter is `r`.

The code:
```dart
final foo = bar;
get bar {
  try {
    return foo ?? 1;
  } catch (e) { 
    print(e); 
  }
  try {
    return foo ?? 2;
  } catch (e) { 
    print(e); 
  }
  return 42;  
}
main() {
 print(foo);
}
```
should execute the `bar` getter, then throw twice reading the `foo` getter, then successfully return 42 and initialize the `foo` variable to 42 and return and print that.
Instead it prints "2"
That mans that the second reading of `foo` must succeed in reading `null` and hence the `bar` call returns `2` and `foo` is then initialized to `2`. 
So the *final* variable `foo` is read successfully twice, once yielding `null` and once yielding `2`, which is not a valid outcome.

**Comment by mhausner** [comment]
Fixed in d643234264c541955e3aec6e9157916e8e47270e
