### ISSUE TITLE
Dart2js leaks internal JS object during lazy variable initialization.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27467]
Example:

``` dart
final foo = bar;
get bar {
  try {
    return foo ?? 1;
  } catch (e) {
    print("1:$e");
  }
  try {
    return foo ?? 2;
  } catch (e) {
    print("2:$e");
  }
  return 42;  
}
main() {
 print(foo);
}
```

This code should print `42`. Instead it prints `[object Object]`.
The second call of the `foo` getter inside the `bar` getter doesn't throw, even though it is also happening during initialization of the the `foo` variable. It returns this unexplainable object.
Trying to `print(foo.runtimeType)` fails, suggesting that this is an internal JS object leaking, and not a Dart object.

**Comment by rakudrama** [comment]
I agree that the dart2js result is wrong.

What I am not sure of is why the result is `42`.
If the initializer fails, the result should be `null`. The initializer fails at `foo ??  1`, storing `null` into foo according to spec 8.1.

**Comment by rakudrama** [comment]
dart2js matches the VM behaviour with `--fast-startup`.

**Comment by rakudrama** [comment]
Fix available: https://codereview.chromium.org/2620123002/

**Comment by rakudrama** [comment]
Fixed by above CL
