### ISSUE TITLE
CompilationUnitElement with null library in index

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27463]
Count: 3
Session Id: 1473963205925.353

Message: Failed to handle request: {clientRequestTime: 1473969929324, params: {file: xxx.dart, offset: 2739, includePotential: true}, method: search.findElementReferences, id: 4883},
StackTrace: The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _PackageIndexRequester.getUnitId (package:analysis_server/src/services/index/index.dart:474)
#3      _PackageIndexRequester.findElementId (package:analysis_server/src/services/index/index.dart:347)
#4      _PackageIndexRequester.getRelations (package:analysis_server/src/services/index/index.dart:445)
#5      _ContextIndex.getRelations.<anonymous closure> (package:analysis_server/src/services/index/index.dart:255)
#6      _ContextIndex._mergeLocations.<_mergeLocations_async_body> (package:analysis_server/src/services/index/index.dart:316)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#8      _rootRun (dart:async/zone.dart:1154)
#9      _CustomZone.run (dart:async/zone.dart:1034)
#10     _CustomZone.runGuarded (dart:async/zone.dart:932)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#12     _rootRun (dart:async/zone.dart:1158)
#13     _CustomZone.run (dart:async/zone.dart:1034)
#14     _CustomZone.runGuarded (dart:async/zone.dart:932)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
This must be some kind of race condition.
I have never been able to reproduce it :-(

**Comment by srawlins** [comment]
Closing until someone can reproduce it.
