### ISSUE TITLE
Missing override errors on name collisions and default values

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27476]
Analyzer has stopped report errors (in a strong mode) in many cases. A couple of examples:

``` dart
class A {
  static var f;
}
abstract class B extends A {
  f();
}
class C extends B {
  f() {}
}
main() {
  new C().f();
}
```

Output:
**analyzer 1.20.0-dev.10.0 strong mode:** 
No issues found
**analyzer 1.20.0-dev.10.0 nostrong mode:** 
[warning] 'f' collides with a static member in the superclass 'A'
[warning] 'f' collides with a static member in the superclass 'A'
**analyzer 1.19.1 strong mode:** 
[error] 'f' collides with a static member in the superclass 'A'
[error] 'f' collides with a static member in the superclass 'A'

Another example

``` dart
class A {
  foo([x = 1]) {}
}
class C extends A {
  foo([x = '']);
}
main() {
  new C().foo(1);
}
```

Output:
**analyzer 1.20.0-dev.10.0 strong mode:** 
No issues found
**analyzer 1.20.0-dev.10.0 nostrong mode:** 
[warning] Parameters cannot override default values, this method overrides 'A.foo' where this positional parameter has a different value
**analyzer 1.19.1 strong mode:** 
[error] Parameters cannot override default values, this method overrides 'A.foo' where this positional parameter has a different value

**Comment by mit-mit** [comment]
Tagging as potential 1.120 blocker

**Comment by zoechi** [comment]
Isn't the first case correct?
A class doesn't inherit static members. I don't see a conflict.

**Comment by lrhn** [comment]
You don't inherit static members, but for some, probably very good, reason the specification does prohibit declaring an instance method with the same name as a static method of a superclass.

Section 10.1:
> It is a static warning if a class C` declares an instance method named `n` and an accessible static member named `n` is declared in a superclass of C.

Here "accessible" isn't really necessary, If it's not accessible, then it's a private from another library, and then it won't have the same /name/ as any declaration in the current library.

**Comment by mit-mit** [comment]
Removing blocking 1.20 tag and lowering to P2.

**Comment by jmesserly** [comment]
Yeah I don't think it's a blocker, but great catch though.

**Comment by jmesserly** [comment]
this still repros, and neither the CFE nor Analyzer report it.

**Comment by leafpetersen** [comment]
Note that the first example is now permitted by the spec.

**Comment by srawlins** [comment]
The second example now has a warning reported by the analyzer:

> Parameters can't override default values, this method overrides 'A.foo' where this positional parameter has a different value.

I think this was fixed with the Summary2 work.
