### ISSUE TITLE
Renaming Constructors 1.20.0-dev.10.0

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#27475]
Summary: 
The past few builds have allowed us to use refractor to rename constructors. If one isn't declared it simply creates a new one with the name: ClassName.NewName(); and if the constructor is declared, it simply changes the last part.
This is all well and good, but for some reason it allows us to rename it to ClassName.ClassName(); which results in a runtime error. The other way around (renaming the class name to the constructor name) is not allowed. 
Shouldn't, renaming a constructor to the class name, either not be allowed, or simply revert to the default name: ClassName(); ?

What steps will reproduce the problem?
Create a new project with the sample content, named Dart Package. Open the projectName_example.dart file. Place the curser over "Awesome()" in line 7. Do a rename (shift + F6 or in the Refractor menu), and write "Awesome".
This happened in both WebStorm, IntelliJ.

What is the expected output? What do you see instead?
Expected:
Either a compile time error telling us there's a conflict between class name and constructor ID,
or that this is allowed and will run fine.

Actual:
The compiler allows the name, but a runtime error occurs. See screen shot.
![skaermbillede 2016-10-04 09 38 57](https://cloud.githubusercontent.com/assets/20222678/19066201/5d8711d4-8a18-11e6-98d2-ed3468c7464f.png)

What version of the product are you using?
Dartium 1.20.0-dev.1.10.0

On what operating system?
Windows 10 Enterprise (64bit)
Mac OS (64 bit)

**Comment by jwren** [comment]
Could you look in your logs to see if you see this exception:

[3750250]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.20.0-dev.5.0, server version 1.17.0, error: Exception from fix contributor: DefaultFixContributor
The null object does not have a method 'getContents'.

NoSuchMethodError: method not found: 'getContents'
Receiver: null
Arguments: [Instance of 'FileSource']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CorrectionUtils.CorrectionUtils (package:analysis_server/src/services/correction/util.dart:693)
#3      addLibraryImports (package:analysis_server/src/services/correction/util.dart:36)
#4      FixProcessor._addFix (package:analysis_server/src/services/correction/fix_internal.dart:387)
#5      FixProcessor._addFix_insertSemicolon (package:analysis_server/src/services/correction/fix_internal.dart:1591)
#6      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:233)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#8      _rootRun (dart:async/zone.dart:1154)
#9      _CustomZone.run (dart:async/zone.dart:1034)
#10     _CustomZone.runGuarded (dart:async/zone.dart:932)
....

FYI:  @bwilkerson @alexander-doroshko

**Comment by bwilkerson** [comment]
@scheglov has a pending CL to fix the NPE.

**Comment by scheglov** [comment]
@jwren I don't think that this Quick Fix exception has anything to do with the refactoring. The corresponding change [was landed](https://github.com/dart-lang/sdk/commit/f69311914618d46136cdc81709470c6eb6d2f66a).

@lrhn 
I don't see anything in the [specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) that does not allow to give the constructor the same name as the class name. It says `It is a compile-time error if id is the name of a member declared in the immediately enclosing class.`. Analyzer, DDC and dart2js are fine with such constructor names. VM isn't, that's true.

**Comment by scheglov** [comment]
We still might want to warn users that they should not name constructors like this.
https://codereview.chromium.org/2399533003

Unfortunately IDEA [does not show](https://github.com/dart-lang/sdk/issues/27497) non-fatal problems right now.

**Comment by lrhn** [comment]
I agree. The spec doesn't actually rule out that `Foo.Foo` can be used as a constructor name.

It also doesn't disallow using the same `id` as an inherited member, and explicitly not so:
> 10.9.1 Inheritance and Overriding
> ...
>25. The identifier of a named constructor cannot be the same as the name of a member declared (as opposed to inherited) in the same class (10.6).

so code like
```dart
class C {
  int get x => 42;
}
class D extends C {
   D.x();
}
main() {
  print(new D.x().x);
}
```
should be valid (and works in Dart2js).

I'm guessing that the reason to have the rule against same name as a member declared in the *same* class is that it would make a redirecting generative constructor confusing: `D() : this.x()` where `x` refers to a `D.x` constructor and not the `x` getter. Not ambiguous, just slightly confusing.
