### ISSUE TITLE
Missing syntax coloring

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#27478]
The following bit of Flutter code is not syntax colored correctly in IntelliJ. The highligting is missing on the three last named args to `FixedColumnCountGridDelegate`.

Using IDEA 2016.2.4 with Dart plugin 162.2233.

``` dart
import 'package:flutter/material.dart';

class foo {
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text('Foo')),
        body: new ScrollableGrid(
          delegate: new FixedColumnCountGridDelegate(
              columnCount: 2,
              columnSpacing: 20.0,
              rowSpacing: 20.0,
              padding: new EdgeInsets.only(top: 20.0, left: 20.0)),
        ));
  }
}
```

![screen shot 2016-10-04 at 13 06 40](https://cloud.githubusercontent.com/assets/13644170/19072058/6c92dbfc-8a33-11e6-8a0b-353445aaa4b4.png)

**Comment by mit-mit** [comment]
Still repros. @bwilkerson did someone take a peek at this?

**Comment by bwilkerson** [comment]
As far as I know, no. Nobody has had a chance to look at it yet.

@scheglov Do you have any ideas?

**Comment by scheglov** [comment]
Actually the highlighting for `columnSpacing` is not missing, it is just different.
All other names of named parameters `appBar`, `body`, `delegate` and `columnCount` are field initializing parameters, so by some reason they are highlighted as **fields**. But `columnSpacing` is highlighted just as a name of a parameter, which it seems is not highlighted much in your IDEA settings. But for me it is highlighted pretty well.

![image](https://cloud.githubusercontent.com/assets/384794/20072152/2923cdfe-a4dc-11e6-9bf4-c8e83e228ec3.png)

I think actually that leaking fields into highlighting of clients is bad though.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2484883002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f05952303785fc9d130bd1ad92c0ae2d4eedb867
