### ISSUE TITLE
Analyzer cache flushing should flush all related results together

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27472]
Analyzer cache flushing currently treats each analysis result as independent.  But in reality there are many analysis results that point to the same underlying data (e.g. RESOLVED_UNIT1-RESOLVED_UNITn, which all point to the same AST data structure).  This means that flushing an individual entry from the cache isn't guaranteed to reclaim any significant amount of memory.  We have to flush a lot of entries, and then the amount of memory actually reclaimed is uncertain, because the only data structures that get garbage collected are the ones for which _all_ of the cache entries pointing to them have been flushed.

This means that we have to set analyzer's caching conservatively in order to avoid running out of memory; that in turn means that we do more flushing than necessary, which leads to unnecessary recomputation, hurting analyzer performance.

We really should change the way the cache works so that all related analysis results are flushed together.

**Comment by natebosch** [comment]
Is this still relevant after the migration to the Driver model? Will it be relevant after the migration to CFE?

**Comment by scheglov** [comment]
No, this is not relevant anymore.
We stopped updating task model, and plan to remove it ASAP.
Analysis Driver does not use this cache.
