### ISSUE TITLE
Analyzer cache flushing can cause incorrect analysis

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27482]
We have at least one situation in the analyzer where two tasks write to the same part of the element model: ResolveUnitTypeNamesTask sets types to `dynamic` if there is no explicit type in the source code, and InferInstanceMembersInUnitTask overwrites those types with inferred types.

This interacts poorly with cache flushing.  Since the analyzer flushes cache entries independently regardless of what underlying data structure they refer to (#27472), this means that under memory pressure, it's possible that the results of ResolveUnitTypeNamesTask may be flushed, but the results of InferInstanceMembersInUnitTask won't be flushed.  If this happens, then later, the analyzer may try to re-execute ResolveUnitTypeNamesTask to restore the flushed data.  As a result, the inferred types will be overwritten again with `dynamic`.  However, since InferInstanceMembersInUnitTask wasn't flushed, there will be nothing to trigger type inference to re-execute, so the element model will be left with incorrect types.  This has been observed to cause incorrect analysis results when analyzing large codebases.

(Note: I don't know if there are any other situations in which two tasks write to the same data; this is the one example I'm aware of.)

Fixing #27472 would be sufficient to fix this bug, however it seems like it would make analyzer more robust and easier to reason about if we established the invariant that no task overwrites data stored by previous tasks; this would ensure that re-executing ResolveUnitTypeNamesTask would not overwrite the data stored by InferInstanceMembersInUnitTask.

**Comment by skybrian** [comment]
What do you think about disabling cache flushing altogether for the dartanalyzer command? Do you think anyone would run out of memory?

**Comment by stereotype441** [comment]
I don't know.  I would need to do some research into the memory usage of dartanalyzer with typical project sizes.

However even if we did that, this issue would remain when running the analyzer in interactive scenarios (like under analysis server); in those scenarios I don't believe it is safe to turn off flushing.

**Comment by leafpetersen** [comment]
Just a quick thought that occurred to me.  Could we just add an extra boolean input to all of the strong mode related tasks that indicates whether we're computing a full result (and hence want to mutate the AST) vs re-computing a flushed entry (and hence don't want to mutate the AST)?

I don't know if there's enough state around to know which case we're in, but if so this might fix this for the short term.

**Comment by stereotype441** [comment]
@leafpetersen unfortunately I don't think there's enough state around for us to do that.

Konstantin discussed two other approaches this morning: (a) store a boolean in the CompilationUnitElement to indicate whether type inference has already been done for that unit; if it has, then the next time ResolveUnitTypeNames task runs, it will avoid modifying the element model.  (b) Change the cache flushing logic so that whenever the output of ResolveUnitTypeNamesTask is flushed, we flush the output of InferInstanceMembersInUnitTask as well (this guarantees that inference will be re-done in the event of a flush).

I'm currently going with (b), because I'm having an easier time reassuring myself of its correctness properties.  I will post more information when I have it.

**Comment by stereotype441** [comment]
Candidate fix out for review: https://codereview.chromium.org/2480783003/
