### ISSUE TITLE
Please merge revision #2e80071cfec6062934ae98a34d331bba14bf3d62 into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27498]
@whesse @mit-mit @kasperl

This fixes https://github.com/dart-lang/sdk/issues/27454 - a bug in strong mode sub-typing.  The bug was exposed by an earlier fix.

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
2e80071cfec6062934ae98a34d331bba14bf3d62

This merged cleanly.

**Comment by vsmenon** [comment]
fyi - @jmesserly @bwilkerson

**Comment by mit-mit** [comment]
This is tagged 1.21, was 1.20 intended (no merge would be needed for 1.21 as we will do full pushed).

If you meant 1.20, what is the severity of this issue (i.e., what is the user impact if we don't include it)?

**Comment by vsmenon** [comment]
Sorry, yes.  1.20.  User impact is hard failure when invoking DDC in come cases - pretty severe.

**Comment by mit-mit** [comment]
We would have to spin a new release candidate, and add a few days to the release and we are already running late. I understand severity, but what about exposure: how likely is a strong mode user to hit this?

**Comment by vsmenon** [comment]
It's a test, not user code, so I'm not sure to be honest.

**Comment by jmesserly** [comment]
it's very unlikely to be hit in practice. It's an erroneous recursive pair of typedefs.

**Comment by vsmenon** [comment]
in that case, it should be reasonably safe to skip for 1.20.

**Comment by mit-mit** [comment]
Thanks, closing. If it later turns out to be a problem externally please reactivate and we can spin a stable patch.

**Comment by mit-mit** [comment]
@whesse FYI
