### ISSUE TITLE
error: Missing pending deopt entry

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27496]
From last night:

https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-reload-be/builds/391/steps/vm%20tests/logs/stdio
https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-reload-be/builds/391/steps/checked%20vm%20tests/logs/stdio
https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-reload-be/builds/393/steps/vm%20tests/logs/stdio
https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-reload-be/builds/393/steps/checked%20vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment]
@fsc8000 @rmacnak-google

**Comment by johnmccutchan** [comment]
https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-reload-be/builds/699/steps/vm%20tests/logs/stdio

**Comment by fsc8000** [comment]
The links above have expired, but this is fixed, right? @rmacnak-google

**Comment by fsc8000** [comment]
Re-labeling this as a language issue. There is nothing VM-specific we can do,  except reducing the overhead of try-catch to as close to zero as possible. The case of empty try-finally is already fixed.

**Comment by fsc8000** [comment]
Undo: Edited wrong issue...

**Comment by a-siva** [comment]
Is this fixed and can be closed?

**Comment by fsc8000** [comment]
Yes, I think this was failing after enabling the new lazy deopt mechanism, but is fixed now.
