### ISSUE TITLE
Specify strong mode "top level" inference

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27499]
We've spent a lot of time discussing strategies around how we handle type inference of "top level" declarations—top level variables and static fields. There is what strong mode currently implements, and the revised rules we've considered informally.

The next step is to write up the set of rules we want to commit to.

Edit by @eernstg Feb 2018: Note that this is now essentially one of the subtasks of #31228.

**Comment by leafpetersen** [comment]
Proposal is now here for consideration: https://github.com/dart-lang/sdk/pull/28218 .

**Comment by leafpetersen** [comment]
Tracking bug for implementation here:  https://github.com/dart-lang/sdk/issues/28219

**Comment by anders-sandholm** [comment]
Can we close this one?

**Comment by eernstg** [comment]
No Dart 2 milestone: This is now considered a subtask of #31228, which has a Dart 2 milestone.

**Comment by leafpetersen** [comment]
I have a pull request out with a specification for this.
