### ISSUE TITLE
Native function cannot be found when using a script snapshot

### ISSUE THREAD

**Issue by amaurel** [dart-lang/sdk#27493]
Dart VM version: 1.20.0-dev.10.0 (Thu Sep 29 16:53:30 2016) on "linux_x64"

I've built a native lib wich works fine when the script is run using dart source code

```
dart main.dart
```

after generating a script snapshot using the following command 

```
dart --snapshot=main.snapshot main.dart
```

an exception occurs when running the snapshot

```
dart main.snapshot 

Unhandled exception:
'package:sci_native/src/sci_native_base.dart': error: line 28: native function 'Fill_sequence_uint32' (1 arguments) cannot be found
  static void fill_sequence_uint32(Uint32List order)
```

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by mit-mit** [comment]
@amaurel does it repro with the same code using SDK 1.19 stable?

**Comment by mit-mit** [comment]
@rmacnak-google can we repro this internally?

**Comment by johnmccutchan** [comment]
The library tag handler (embedder callback that loads scripts) does a bunch of extra work to support extensions. Using native extensions in a script snapshot has likely never been supported or worked.

**Comment by amaurel** [comment]
SDK 1.19 stable don't load the library and throws  "Relative paths for dart extensions are not supported"

**Comment by rmacnak-google** [comment]
Duplicate of #21180.
