### ISSUE TITLE
Unexpected warning from dart analyzer in strong mode about type dynamic

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#27495]
The Dart Programming Language Speciﬁcation version 1.11 reads:

> Type dynamic has methods for every possible identiﬁer and arity, with
> every possible combination of named parameters. These methods all have dy-
> namic as their return type, and their formal parameters all have type dynamic.
> Type dynamic has properties for every possible identiﬁer. These properties all
> have type dynamic.
> _From a usability perspective, we want to ensure that the checker does not
> issue errors everywhere an unknown type is used. The deﬁnitions above ensure
> that no secondary errors are reported when accessing an unknown type._

The following code demonstrates the problem:
```dart
typedef func();
typedef int func2(int x);

main() {
  dynamic x = null;
  int z = x.z; // ok
  func f = x.razorsedge; // ok
  func2 f2 = x.andromeda; // warning in strong mode
}
```
Output:

> dartanalyzer.bat --strong --enable_type_checks test.dart
> Analyzing [test.dart]...
> **[warning] Unsound implicit cast from dynamic to (int) -> int (D:\dev\dart\co19\Language\Types\Type_dynamic\test.dart, line 8, col 14)**
> [hint] The value of the local variable 'z' is not used (D:\dev\dart\co19\Language\Types\Type_dynamic\test.dart, line 6, col 7)
> [hint] The value of the local variable 'f' is not used (D:\dev\dart\co19\Language\Types\Type_dynamic\test.dart, line 7, col 8)
> [hint] The value of the local variable 'f2' is not used (D:\dev\dart\co19\Language\Types\Type_dynamic\test.dart, line 8, col 9)
> 1 warning and 3 hints found.

The problem is observed only in strong mode.
Dart VM version: 1.19.1 (Wed Sep 07 09:07:46 2016) on "windows_x64"

**Comment by alsemenov** [comment]
Similar problem:
```dart
class A {
}
class B<T> {
}

main() {
  A a = () {} (); // ok
  B<int> b = () {} (); // static warning in strong mode
}
```

> dartanalyzer.bat --strong --enable_type_checks test.dart
> Analyzing [test.dart]...
> [warning] Unsound implicit cast from dynamic to B<int> (D:\dev\dart\co19\Language\Types\Interface_Types\test.dart, line 8, col 14)
> [hint] The value of the local variable 'a' is not used (D:\dev\dart\co19\Language\Types\Interface_Types\test.dart, line 7, col 5)
> [hint] The value of the local variable 'b' is not used (D:\dev\dart\co19\Language\Types\Interface_Types\test.dart, line 8, col 10)
> 1 warning and 2 hints found.

**Comment by jmesserly** [comment]
This is intentional behavior. Implicit downcasts to composite types, like `int -> int` or `List<int>` are much more likely to fail in strong mode, because we do not allow `List<dynamic> <: List<int>`.

Strong Mode's subtyping rules do not work like Dart 1 spec. That's the whole point of strong mode :). CC @leafpetersen @vsmenon

**Comment by alsemenov** [comment]
I am still not clear in which cases warning appears.
Consider the first code example. 
```dart
 func f = x.razorsedge; // ok
```
Why this line is ok?
`func` is `()->dynamic`, assigning `dynamic` to it cause no warnings.
However, if we assign `dynamic` to `(int)->dynamic`, warning will appear.

**Comment by leafpetersen** [comment]
Strong mode currently tries to give warnings on assignments that may cause cast failures on the checked mode VM but not on DDC.  All of the standard Dart subtypes of `() -> dynamic` are also strong mode subtypes, but standard Dart subtypes of `(int) -> dynamic` include `(dynamic) -> dynamic` which is not a strong mode subtype, and so code that ran correctly in checked mode might hit an error on DDC here.  Hence the warning.
