### ISSUE TITLE
Analyzer in a strong mode doesn't generate "The constant creation cannot use a type parameter" error

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27492]
```dart
class S<U> {
  const S();
}
class A<T> {
  test() {
    const S<T>(); //type variable as a type argument
  }
}
main() {
  new A<int>().test();
}
```
For the code above Analyzer in nostrong mode generates "The constant creation cannot use a type parameter" error. But in a strong mode analyzer output is "No issues found"

Another similar issue
```dart
class C<T> {
  test() {
    const <T>[null, null];
  }
}
main() {
  new C().test();
}
```
Analyzer in a nostrong mode produces "Constant list literals cannot include a type parameter as a type argument, such as 'T'" and "No issues found" in a strong mode

Tested in dartanalyzer version 1.20.0-dev.10.0

**Comment by jmesserly** [comment]
This was intentional. We allow constants to depend on type parameters in strong mode.
