### ISSUE TITLE
No compile error in analyzer if type parameter is used in a static member

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27491]
According to the Dart specification (4th Edition, December 2015) "16.33 Identifier Reference"

> Evaluation of an identifier expression e of the form id proceeds as follows:
> Let d be the innermost declaration in the enclosing lexical scope whose
> name is id or id =. If no such declaration exists in the lexical scope, let d be
> the declaration of the inherited member named id if it exists.
> ...
> If d is a type parameter T, then the value of e is the value of the actual
> type argument corresponding to T that was passed to the generative constructor
> that created the current binding of this. If, however, e occurs
> inside a static member, a compile-time error occurs.

But, in fact, analayzer doesn't produce a compile error in this case. Example:

``` dart
class A<T> {
  static Type func() => T;
}
main() {
  A.func();
}
```

Analyzer (in both strong and nostrong modes) finds no any issues in the code above.
Tested on dartanalyzer 1.20 and 1.19.1

VM produces an error "cannot access type parameter 'T' from static function"

**Comment by srawlins** [comment]
The analyzer now reports the following diagnostic:

> error • Static members can't reference type parameters of the class. • 27491.dart:2:25 • type_parameter_referenced_by_static
