### ISSUE TITLE
Finalize Future flattening in strong mode

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27503]
The fact that futures implicitly "flatten" at runtime makes statically typing code that works with them harder. In some cases, code that accepts a `Future<T>` really effectively takes a `Future<T>|T`, which Dart cannot represent.

Strong mode currently has some ad hoc rules around `Future.then()` to make it work nicer, but those rules are kind of hacky and don't extend to user-defined methods that work in a similar fashion. See [here](https://github.com/dart-lang/sdk/issues/27101#issuecomment-240549134) and the following comments.

To finish off strong mode, we need to decide what the real rules we want here are, commit to them, and describe and implement them fully. A couple of options:
1. Stick with the current ad hoc rules.
2. Define a special `Async<T>` which works roughly like a special case union type of `Future<T>|T`.
3. Full-fledged union types.

**Comment by sureshg** [comment]
👍 for Full-fledged union types.

**Comment by nex3** [comment]
I'd love `Async<T>` in the short term and full-fledged union types in the long term.

**Comment by leafpetersen** [comment]
status: language team is ok with the `Async<T>` proposal (possibly with a different name).  @lrhn is writing up the informal spec to be shared for wider feedback and then implementation.

**Comment by floitschG** [comment]
We are going to implement `FutureOr<T>`: https://github.com/dart-lang/sdk/issues/28006
