### ISSUE TITLE
Finalize and specify rules for local variable inference

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27500]
The type inference rules for local variables declared without a type are pretty well-tested at this point, but I think there are a couple of corners to hammer out and then we need to add them to the spec.

Edit by @eernstg Feb 2018: Note that this is now essentially one of the subtasks of #31228.

**Comment by floitschG** [comment]
Status update:
Ideally we would like to spec the rules for 1.50, but no other team should be affected, if this issue slips.

**Comment by leafpetersen** [comment]
started:  I am working on this in the background, but as noted above, this is purely a spec issue with no implementation dependencies, so lower priority.

**Comment by eernstg** [comment]
No Dart 2 milestone: This is now considered a subtask of #31228, which has a Dart 2 milestone.

**Comment by srawlins** [comment]
I think this can be closed in favor of the local variable inference rules being written for Null Safety Dart.
