### ISSUE TITLE
Non-overridable members

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27502]
Dart specifies that all members, including fields, can be overridden by subclasses or implemented by interfaces.

dev_compiler does not support overriding fields because it forces fields to be compiled to larger, slower JS. Strong mode in turn therefore makes overriding a field a static error.

When investigating instances of that error, Leaf discovered almost every single case where a field was being overridden was in fact bad code. In most cases, the intent for the "field" was actually to declare an abstract getter/setter.

Flutter (among others) have requested to be able to declare that some members cannot be overridden.

The language has committed to at least declaring fields that can and cannot be overridden or implemented. We have not yet decided:
- If other members can be configured in the same way.
- What the default should be for fields.
- What the default should be for other members.
- What the syntax should be.
- What the semantics are, especially around implicit interfaces.

This bug is to decide and implement those.

See also: #24928, #27385, #27452, #27372.

**Comment by rmacnak-google** [comment]
Non-overrideable members is completely contrary to the Dart object model.  A limitation of one implementation should not poison the language.

**Comment by floitschG** [comment]
Status update:
DDC needs to implement support for it.
Strong mode should removed the check.
Assuming that the implementation for DDC works as expected (with no overhead for normal fields), the language team doesn't take any action for 1.50.

**Comment by jmesserly** [comment]
FYI, DDC support for this should be implemented, and I left support for Analyzer to easily re-add if needed. The "isVirtual" getter is hard coded to return true now, but it would be easy to have it return false if `@sealed` is present. (https://github.com/dart-lang/sdk/commit/1c504f89452d52f902a8c3591bde0f172452de21)

**Comment by jmesserly** [comment]
In other words, LMK if y'all want to add Analyzer support for `@sealed`, it's a trivial change.

**Comment by lrhn** [comment]
DDC now allows overriding fields.
