### ISSUE TITLE
Implementation of VirtualMemory::FreeSubSegment on Windows

### ISSUE THREAD

**Issue by jaens** [dart-lang/sdk#27505]
The comment in `runtime/vm/virtual_memory_win.cc` is not exactly accurate:

```
  // On Windows only the entire segment returned by VirtualAlloc
  // can be freed. Therefore we will have to waste these unused
  // virtual memory sub-segments.
```

You can call `VirtualAlloc` with the `MEM_RESET` flag to achieve an effect similar to `madvise(MADV_DONTNEED)`. Better than doing nothing. :)

I think you can also call `VirtualFree` with the `MEM_DECOMMIT` flag which should do something similar to `unmap()`.

**Comment by zanderso** [comment]
In order to avoid conflating this change with other changes that appear to have caused some memory problems on Windows, the above change was reverted. I am reopening this to remind me to re-land when the problems from the other changes clear up.

**Comment by mraleph** [comment]
@zanderso do you want to reland the change? If not - please close the issue.

**Comment by zanderso** [comment]
Sure let's try it: https://dart-review.googlesource.com/c/sdk/+/52520

**Comment by zanderso** [comment]
This causes a crash in the FreeVirtualMemory unit test on the bots that needs some investigation:
```
run_vm_tests --ignore-unrecognized-flags FreeVirtualMemory
exit code:
3
stdout:
Running test: FreeVirtualMemory
stderr:
===== CRASH =====
version=2.0.0-edge.b641826ccf056036eca63515be7ea4ad23792266 (Tue Apr 24 22:14:48 2018 +0000) on "windows_ia32"
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00CA7BF2
Dumping native stack trace for thread 1790
  [0x00ca7bf2] dart::VirtualMemory::Truncate
  [0x00ca7bf2] dart::VirtualMemory::Truncate
  [0x00677830] dart::Dart_TestFreeVirtualMemory
  [0x0046b73e] main
  [0x00f285ce] invoke_main
  [0x00f28470] __scrt_common_main_seh
  [0x00f2830d] __scrt_common_main
  [0x00f28648] mainCRTStartup
  [0x7544336a] BaseThreadInitThunk
  [0x778592b2] RtlInitializeExceptionChain
  [0x77859285] RtlInitializeExceptionChain
-- End of DumpStackTrace
```

**Comment by mraleph** [comment]
I uploaded a fixed version of the CL https://dart-review.googlesource.com/c/sdk/+/52642
