### ISSUE TITLE
content-shell libfontconfig.so.1.8.0 issue

### ISSUE THREAD

**Issue by eukreign** [dart-lang/sdk#27512]
After much struggling with trying to get content-shell to run on Ubuntu 16.04 I finally discovered that if I added `libfontconfig.so.1.8.0` from an older Ubuntu install `content_shell` started working.

It would be nice if this library was bundled with content-shell to make it easier to use just as `libfreetype.so.6` is bundled.

This is the error I was getting before:

```
$ content_shell --dump-render-tree http://google.com
[102579:102579:1005/103451:286605162663:FATAL:fontconfig_util_linux.cc(127)] Check failed: FcConfigSetCurrent(FcConfigCreate()). 
Aborted (core dumped)
```

**Comment by Aetet** [comment]
@kevmoo Any progress on this?

**Comment by kevmoo** [comment]
Any ideas, @whesse ?

**Comment by whesse** [comment]
I think it would be good to document the workaround better, and write up precise instructions for fixing this.
I'm not sure that the process of adding the library and bundling it in is worth it.  If it is, then precise instructions will help us do it.

 
- things should be tested with dart2js and browsers

**Comment by eukreign** [comment]
The alternative would be to compile content_shell/dartium with a more recent upstream chromium source. This fontconfig issue was fixed upstream a while ago.

Bundling a Ubuntu 15.10 libfontconfig.so.1.8.0 with content_shell seems like the quickest and simplest solution. Especially, if the near term goal is to deprecate Dartium.

**Comment by whesse** [comment]
We can't update our builds from ubuntu 12, because there are still some users on it, even though it is EOL next spring, so we would have to make a separate build for newer OS versions.  What are the instructions for people to download the file and copy it to the right directory?

**Comment by eukreign** [comment]
An old build does work in a newer version of Ubuntu, you just have to bundle those old build libs. For instance, below I'm using `libfontconfig` from Ubuntu 14.04 on Ubuntu 16.04.

Here are the instructions for installing a working copy of `content_shell` on Ubuntu 16.04 amd64 (may work on 16.10 amd64 as well):

Fetch `content_shell`:
```bash
curl https://storage.googleapis.com/dart-archive/channels/stable/release/1.21.0/dartium/content_shell-linux-x64-release.zip > content_shell-1.21.0-stable.zip
unzip -qo content_shell-1.21.0-stable.zip
ln -sfn drt-linux-x64-stable-1.21.0.0/ content_shell
```

Fetch the old `libfontconfig`:
```bash
curl -O http://security.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1_2.11.0-0ubuntu4.2_amd64.deb
```

Extract just the `.so` to `content_shell/lib` directory:
```bash
dpkg --fsys-tarfile libfontconfig1_2.11.0-0ubuntu4.2_amd64.deb | tar xOf - ./usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0 > content_shell/lib/libfontconfig.so.1
```

Add the `content_shell` directory to your `PATH` and then test that it works:
```
content_shell --dump-render-tree http://google.com
```

**Comment by eukreign** [comment]
Here is a `fab` command I use to keep dartium and content_shell updated on my workstation, maybe it will help someone. It has the advantage that you can keep multiple versions of dartium and content_shell around and switch between them (it just changes the symbolic links if you have some version already):

```python
def getdartium(version='1.21.0', channel='stable'):
    "get dartium and content-shell for linux, on Mac use homebrew"

    BIN = os.path.expanduser('~/bin')
    DOWNLOAD = os.path.join(BIN, 'downloads')
    if not os.path.exists(BIN):
        os.mkdir(BIN)
    if not os.path.exists(DOWNLOAD):
        os.mkdir(DOWNLOAD)

    paths = []
    with lcd(BIN):

        for app in ('content_shell', 'dartium',):

            zipfile = os.path.join(DOWNLOAD, '{}-{}-{}.zip'.format(app, version, channel))

            if not os.path.exists(zipfile):
                url = (
                    'https://storage.googleapis.com/dart-archive/channels/{}/release/'
                    '{}/dartium/{}-linux-x64-release.zip'.format(channel, version, app)
                )
                local("curl {} > {}".format(url, zipfile))

            outdir = local('unzip -l {} | head -n 4 | tail -n 1'.format(zipfile), capture=True)
            outdir = outdir.split(' ')[-1]

            if not os.path.exists(os.path.join(BIN, outdir)):
                local("unzip -qo {}".format(zipfile))

            local("ln -sfn {} {}".format(outdir, app))
            paths.append(os.path.join(BIN, app))

        lib = 'libfontconfig1_2.11.0-0ubuntu4.2_amd64.deb'
        libfile = os.path.join(DOWNLOAD, lib)
        if not os.path.exists(libfile):
            liburl = (
                'http://security.ubuntu.com/ubuntu/pool/main/f/fontconfig/'+lib
            )
            local("curl {} > {}".format(liburl, libfile))

        local(
            "dpkg --fsys-tarfile {} | tar xOf - ./usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0"
            " > content_shell/lib/libfontconfig.so.1".format(libfile)
        )

    not_present = [path for path in paths if path not in os.environ['PATH']]
    if not_present:
        print("Add to your environment:")
        print('export PATH="%s:$PATH"' % ':'.join(not_present))
```

**Comment by kevmoo** [comment]
Dartium & content-shell will not be supported in Dart2
