### ISSUE TITLE
Update analyzer and tests to support new async/async*/sync* checks

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27514]
16d806b0aa4b1100e1dffe6940e80014070b1bba changed the specification for return type warnings on methods declared with `async`, `async*`, or `sync*`.  Analyzer needs to be updated to reflect these changes.  Also, tests need to be written in `tests/language` to validate these changes.

**Comment by leafpetersen** [comment]
Note that strong mode already has this restriction, I believe, so it may be possible to just reuse at least some of the code paths and tests.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
