### ISSUE TITLE
Update analyzer and tests to support new part file restriction

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27515]
cc6d93b57c697e2afc86431e5b580dc2c1ae89a7 changed the specification so that it is an error for a library to reference the same part URI twice (even if the part file is empty).  Analyzer needs to be updated to reflect this change.  Also, a test should be written in `tests/language` to validate this change.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2401463004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/26cc95d8b4ad09971cef55c196cc632de8f97be0
