### ISSUE TITLE
Refactor analyzer-cli / ddc to share command-line / config logic

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27511]
Logic around resolvers, summaries, and other context setup should be shared as much as possible.  Ideally, this file in DDC and related setup calls into shared (with analyzer-cli) code instead:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/context.dart

This will ensure analyzer-cli and ddc take consistent options and reduce work when adding new ones.

**Comment by jmesserly** [comment]
this was also filed as https://github.com/dart-lang/sdk/issues/27252

**Comment by danrubel** [comment]
Once https://codereview.chromium.org/2598593003/ lands, you'll be able to use all of the standard analysis options command line flags such as --options and --enable-strict-call-checks

**Comment by nex3** [comment]
@danrubel Does that mean this has been fixed?

**Comment by danrubel** [comment]
Yes. Fixed.
