### ISSUE TITLE
Dart analyzer should give an error for a final field without initializer

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#27510]
The following code fails with compilation error on execution:

``` dart
final int v;

main() {
  print(v);
}
```

Output:

> dart --checked final_or_static_initialization_t01.dart
> 'file:///D:/dev/dart/co19/Language/Variables/final_or_static_initialization_t01.dart': error: line 16 pos 11: missing initializer for final or const variable
> final int v;

This is expected behavior for Dart VM, however Dart Analyzer produce only warning instead of error:

> dartanalyzer.bat --strong --enable_type_checks final_or_static_initialization_t01.
> dart
> Analyzing [final_or_static_initialization_t01.dart]...
> [warning] The final variable 'v' must be initialized (D:\dev\dart\co19\Language\Variables\final_or_static_initialization_t01.dart, line 16, col 11)
> 1 warning found.
> 
> dartanalyzer.bat  --enable_type_checks final_or_static_initialization_t01.dart
> Analyzing [final_or_static_initialization_t01.dart]...
> [warning] The final variable 'v' must be initialized (D:\dev\dart\co19\Language\Variables\final_or_static_initialization_t01.dart, line 16, col 11)
> 1 warning found.

I believe, Dart Analyzer should behave the same way (i.e. produce error) as Dart VM in this case.

Dart VM version: 1.19.1 (Wed Sep 07 09:07:46 2016) on "windows_x64"

**Comment by srawlins** [comment]
The analyzer now reports an error:

> error • The final variable 'v' must be initialized. • 27510.dart:1:11 • final_not_initialized
