### ISSUE TITLE
Remove generalized tear-offs from the VM

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27520]
This is the VM issue for https://github.com/dart-lang/sdk/issues/27518.

**Comment by zanderso** [comment]
This is a breaking change, and is therefore not suitable for the 1.50 milestone.

**Comment by munificent** [comment]
@dgrove specifically asked it to be added to 1.50. As I note in the meta bug, there are zero usages of it within Google. I don't know if there are any outside, but if there are, they are bound to be few.

There's a sort of "tree falls in the woods, does it make sound" question about whether removing a feature which has no users is a breaking change or not. If no programs are broken, I wouldn't classify it as a breaking change.

**Comment by fsc8000** [comment]
Completely agree with @zanderso . And apart from being a breaking change, what is the exact benefit of removing this language feature?

**Comment by dgrove** [comment]
Reasons for its deletion:

* it's not implemented across the toolchain
* has no users.

There is a lot of work to get this implemented everywhere, and we do not
believe that it's worth this effort.

**Comment by munificent** [comment]
Every feature adds complexity to the language, adds cognitive load to users, increases the effort it takes for a new user to learn Dart, must be implemented and optimized and maintained, needs to be documented, and occupies portions of the grammar that could be used for other things. It interacts with other features and gets in the way of other ways of accomplishing the same goal.

Every language feature begins its life quite deep in debt. It pays off that debt by making the lives of as many users possible as much better as possible.

Generalized tear-offs didn't meet that requirement. It's a fairly complex feature, and it sits right in the middle of the expression grammar and even takes up a unique token. It is redundant—and more verbose!—with the existing tear-off syntax for cases where both work. It provides no solution for many similar problems, such as wanting to create a "tear-off" that invokes a method with a given receiver.

The fact that it has no users, and no users have clamored for it to be fully implemented is a good sign that it does not meet a real user need. The fact that no one on the language team is excited about it is another good sign.

Since it is unused, we have an easy opportunity to just delete it now and unburden ourselves from cost of the finishing implementing it, maintaining, etc. This also frees us up to design a better solution in the future, which we have pretty good ideas for.

**Comment by fsc8000** [comment]
> 
* it's not implemented across the toolchain
* has no users.

The second point could be be a consequence of the first line. There could be users of the Dart VM using it.

**Comment by zanderso** [comment]
You are using a overly-narrow definition of "within Google", one that your colleagues working in the open source world may object to. For example, tear-offs are used in the Mojo bindings and embedder, e.g. here: https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/io/mojo_patch.dart#L193. The API that suggests using tear-offs is public:

https://fuchsia.googlesource.com/mojo/+/master/dart/packages/mojo/src/proxy.dart#370

I don't feel it is my responsibility to audit all users of this API be they internal or external.

I'm not disagreeing with the decision to remove the feature, but I do object to the timing. The 1.50 plan states that it will have only "high-priority language enhancements (not breaking changes)". This change seems low-priority and breaking, which violates both of these requirements.

**Comment by zoechi** [comment]
I think it would be great to add a warning for when it's used as soon as possible.
Is there an easy way to check if it's used?
@munificent how did you check the Google code base?

It might be that I use it somewhere. I know I had a need once but worked around it passing closures but I might have changed that later to use tear-offs. 
I wouldn't mind changing the code to get rid of tear-offs.

**Comment by munificent** [comment]
> Is there an easy way to check if it's used?

If you grep for something like `\w+#\w+`, it should turn them up, I believe.

> I know I had a need once but worked around it passing closures but I might have changed that later to use tear-offs. 

Yeah, you never *need* to use generalized tear-offs. You can always just make a closure.

**Comment by anders-sandholm** [comment]
Wish there was an easy way to check all of github for use of "#" but https://help.github.com/articles/searching-code/ says "You can't use the following wildcard characters as part of your search query: . , : ; / \ ` ' " = * ! ? # $ & + ^ | ~ < > ( ) { } [ ]. The search will simply ignore these symbols."

**Comment by munificent** [comment]
I just pulled down the latest version of every package on pub. With some grep hackery, I determined **there are zero usages of generalized tear-offs on pub.dartlang.org.**

**Comment by dgrove** [comment]
After reviewing all of the data, we will make this change for 1.50 .

**Comment by mit-mit** [comment]
Moving to 1.22 per release discussion, deprecation warning will happen in 1.21 (see #27742).

**Comment by mit-mit** [comment]
After discussion with Dan, moving this to 1.22.

@a-siva let's get this removed!

**Comment by mit-mit** [comment]
@a-siva is someone working on this?

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/commit/c69cbb586f29ed67b949cf8661d4d22b922a2339
