### ISSUE TITLE
StrongMode: Type not assignable (clearly it is)

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#27522]
quiver has a [StreamBuffer](https://github.com/google/quiver-dart/blob/master/lib/src/async/stream_buffer.dart#L49) that implements [StreamConsumer](https://api.dartlang.org/stable/1.19.1/dart-async/StreamConsumer-class.html)

``` dart
class StreamBuffer<T> implements StreamConsumer<dynamic/*T|List<T>*/> {
```

Elsewhere I'm using a `StreamController<T>`:

``` dart
_controller = new StreamController<Foo>();
_queue = new StreamBuffer<Foo>();
_controller.stream.pipe(_replyQueue);
```

The error is:
`The argument type 'StreamBuffer<Foo>' cannot be assigned to the parameter type 'StreamConsumer<Foo>'. (argument_type_not_assignable)`

Which appears to be an error in the analyzer.

**Comment by leafpetersen** [comment]
`StreamController<Foo>.stream.pipe` expects a `StreamConsumer<Foo>`.  A `StreamBuffer<Foo>` is a `StreamConsumer<dynamic>` which cannot be used where a `StreamConsumer<Foo>` is expected.  The `StreamConsumer` interface is naturally contra-variant, but there's no way to express this in Dart.

**Comment by jmesserly** [comment]
also note, that `/*T|List<T>*/` comment doesn't do anything. To analyzer StreamBuffer only implements `StreamConsumer<dynamic>`, which is not assignable to `StreamConsumer<T>`

**Comment by leafpetersen** [comment]
I think that perhaps having a bottom type available would allow Quiver to fix this: https://github.com/dart-lang/sdk/issues/27488 .  I think it would work by making `StreamBuffer` implement `StreamConsumer<Bottom>`, and implementing `addStream` to take `Stream<dynamic>` (which is a valid contra-variant override).

**Comment by jtmcdole** [comment]
Note; I wrote the StreamBuffer and it use to have `StreamConsumer<T>`,  @munificent changed that in https://github.com/google/quiver-dart/commit/1c7d0f535ed348127b399ca67eea44d7cb8bae32 to just remove an "as". I'll revert that and see if it goes away.

**Comment by leafpetersen** [comment]
If you're willing to put an impedance matcher in there, I think you can work around this by wrapping the `StreamBuffer` in a `DelegatingStreamSink`.

https://www.dartdocs.org/documentation/async/1.11.2/async/DelegatingStreamSink-class.html

@nex3

**Comment by leafpetersen** [comment]
Discussion on the quiver end here:  https://github.com/google/quiver-dart/issues/308

**Comment by jmesserly** [comment]
assuming stale
