### ISSUE TITLE
Add client-id/client-version to Analysis Server API docs

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27521]
@skybrian [mentioned](https://github.com/Dart-Code/Dart-Code/issues/188) that the analysis server takes a `client-id` and `client-version` that could be useful in the analysis server instrumentation logs.

Currently there's no mention of these in [the API docs](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html) but if there's value in them then it seems like it would be beneficial to document them so that other integrators will supply them.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2397293002/
