### ISSUE TITLE
Document Dart 1.5 strong mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27530]
Complete written description of strong mode for Dart 1.5.

**Comment by leafpetersen** [comment]
Downcast restrictions need to be covered by this: https://github.com/dart-lang/sdk/issues/27564 .

**Comment by leafpetersen** [comment]
Status: in progress.  See subcomponents on generic methods, least upper bound, instantiate to bounds.

**Comment by mit-mit** [comment]
Where are we at with this? Is it on track to finish in Q4?

**Comment by mit-mit** [comment]
Moving to 1.22 for completion.

**Comment by mit-mit** [comment]
@leafpetersen is this likely to complete in 1.22, or should we move to 1.23?

**Comment by leafpetersen** [comment]
Local inference spec in progress here: dart-lang/sdk#28218

Toplevel inference spec here: dart-lang/sdk#28218

More TODO.

**Comment by anders-sandholm** [comment]
Can we close this and focus on #31228?
