### ISSUE TITLE
Allow run co19 tests with '--supermixin' flag

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27532]
In dartanalyzer super() calls in mixin are allowed behind --supermixin flag (see #23772). Some co19 tests, that checks super() calls in mixin fail because tests are run without this flag. If I manually add '--supermixin' flag to tools/testing/dart/co19_test.dart COMMAND_LINES variable, then "Unknown test option --supermixin" error occurs. Please allow --supermixin flag in a test runner

**Comment by whesse** [comment]
The --supermixin flag has been removed from the dart executable, so it should not be passed when runtime == dart.
Supermixins are apparently not implemented in dart2js or ddc, so there is nothing to do there, according to #23770 

It seems to me that adding a test option called --analyzer-options, which would contain options to pass on the analyzer, would be the best way to pass options to the analyzer.  There is also an .analysis_options file, which the analyzer searches for in the current working directory, so you should be able to put your setting in that file, in the directory that you run test.dart from.

**Comment by jmesserly** [comment]
oops, I messed up the issue number. Sorry!

**Comment by srawlins** [comment]
`--supermixin` no longer exists in `dartanalyzer` either, as of Dart 2.1.
