### ISSUE TITLE
Exception in fix contributor

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27539]
The line numbers are wrong, but I suspect that #2 in on line 482 (though it's possible I'm wrong).

Dart analysis server, SDK version 1.17.0-dev.4.1, server version 1.15.0, error: Exception from fix contributor: DefaultFixContributor
The null object does not have a getter 'end'.

NoSuchMethodError: method not found: 'end'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:471)
#3      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:246)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _rootRun (dart:async/zone.dart:946)
#6      _CustomZone.run (dart:async/zone.dart:826)
#7      _CustomZone.runGuarded (dart:async/zone.dart:724)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#9      _rootRun (dart:async/zone.dart:950)
#10     _CustomZone.run (dart:async/zone.dart:826)
#11     _CustomZone.runGuarded (dart:async/zone.dart:724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2411063002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/2a000e1587482e6c5e252a8ac1b713aa628648f4
