### ISSUE TITLE
No warning and error in analyzer with --supermixin flag if mixin extends wrong class

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27531]
According Dart specification (4th edition, December 2015), 12.1 Mixin Application

> Let MA be a mixin derived from a class M with direct superclass Sstatic.
> Let A be an application of MA. It is a static warning if the superclass of A
> is not a subtype of Sstatic.

In other words if you write something like
`class C = A with M;`
Both A and M should extends the same class. But:

``` dart
class Sstatic {
}
class M extends Sstatic {
}
class NoSstatic {
}
class SuperA extends NoSstatic {
}
class A = SuperA with M;

main() {
  new A();
}
```

Run this code in dartanalyzer with --supermixin option and there will be no warning in a nostrong mode and no error in a strong one.

**Comment by srawlins** [comment]
The analyzer now reports:

>  error • The class 'M' can't be used as a mixin because it extends a class other than Object. • 27531.dart:9:23 • mixin_inherits_from_not_object
