### ISSUE TITLE
html/element_classes_test is failing on Firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27535]
The test html/element_classes_test is failing on firefox, on both linux and Windows.

The error is 
FAILED: dart2js-ff release_x64 html/element_classes_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

...
 <tr>
                            <td>14</td>
                            <td class="unittest-fail">
                              FAIL
                            </td>
                            <td>
                              <p>Expectation: 
                                <a href="#testFilter=contains-bad">
                                  contains-bad
                                </a>.
                              </p>
                              <pre>Expected: throws
                      Actual: &lt;Closure 'main__closure15'&gt;
                       Which: did not throw
                    </pre>
                            </td>
                          </tr><tr><td></td><td colspan="2"><pre>http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 1271:17   H.wrapException
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 21120:13  Y.SimpleConfiguration.prototype.onExpectFailure$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 21098:7   Y._ExpectFailureHandler.prototype.fail$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 7544:9    G.expect
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 21543:7   K.main_closure12.prototype.call$0
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 20425:20  M.InternalTestCase_run_closure0.prototype.call$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 3373:16   P._rootRunUnary
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 13095:14  P._CustomZone.prototype.runUnary$2
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 11474:14  P._FutureListener.prototype.handleValue$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 11855:44  P._Future__propagateToListeners_handleValueCallback.prototype.call$0
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 3153:15   P._Future__propagateToListeners
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 11663:7   P._Future.prototype._completeWithValue$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 11776:7   P._Future__asyncComplete_closure0.prototype.call$0
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 3364:14   P._rootRun
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 13088:14  P._CustomZone.prototype.run$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 13001:14  P._CustomZone.prototype.runGuarded$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 13210:14  P._CustomZone_bindCallback_closure.prototype.call$0
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 3195:9    P._microtaskLoop
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 3201:9    P._startMicrotaskLoop
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 11383:7   P._AsyncRun__initializeScheduleImmediate_internalCallback.prototype.call$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 10271:14  H.invokeClosure_closure0.prototype.call$0
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 9291:18   H._IsolateContext.prototype.eval$1
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 591:20    H._callInIsolate
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 1455:18   H.invokeClosure
                    http://127.0.0.1:33355/root_build/generated_compilations/dart2js-sdk/tests_html_element_classes_test/test.js 1474:18   H.convertDartClosureToJS.&lt;fn&gt;.&lt;fn&gt;
                    </pre></td></tr>

**Comment by sigmundch** [comment]
this test is failing now on all browsers, I'm closing the bugs since, besides notifications, we are not really using the bug tracker to track the status of our tests.
