### ISSUE TITLE
Exception in search engine

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27542]
I don't know why this is being reported back as a failure for analysis.setPriorityFiles. My best guess is that we're trying to send some subscribed to notification in response, but it seems like there must be a better way to report this error.

Dart analysis server, SDK version 1.20.0-dev.7.0, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1474551288311, params: {files: [x.dart, y.dart]}, method: analysis.setPriorityFiles, id: 801}
The null object does not have a method 'accept'.

NoSuchMethodError: method not found: 'accept'
Receiver: null
Arguments: [Instance of '_ContainingElementFinder']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      SearchMatch.element (package:analysis_server/src/services/search/search_engine.dart:166)
#3      getSubClasses.<getSubClasses_async_body>.<anonymous closure> (package:analysis_server/src/services/search/hierarchy.dart:127)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#5      ListIterable.toSet (dart:_internal/iterable.dart:230)
#6      getSubClasses.<getSubClasses_async_body> (package:analysis_server/src/services/search/hierarchy.dart:127)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#8      _rootRunUnary (dart:async/zone.dart:1158)
#9      _CustomZone.runUnary (dart:async/zone.dart:1037)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#13     _Future._complete (dart:async/future_impl.dart:467)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#15     SearchEngineImpl.searchAllSubtypes.<searchAllSubtypes_async_body> (package:analysis_server/src/services/search/search_engine_internal.dart:34)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#17     _rootRunUnary (dart:async/zone.dart:1158)
#18     _CustomZone.runUnary (dart:async/zone.dart:1037)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#20     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#21     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#22     _Future._complete (dart:async/future_impl.dart:467)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#24     SearchEngineImpl._addMatches.<_addMatches_async_body> (package:analysis_server/src/services/search/search_engine_internal.dart:111)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#26     _rootRunUnary (dart:async/zone.dart:1158)
#27     _CustomZone.runUnary (dart:async/zone.dart:1037)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#29     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#30     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#31     _Future._complete (dart:async/future_impl.dart:467)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#33     Index._mergeLocations.<_mergeLocations_async_body> (package:analysis_server/src/services/index/index.dart:141)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#35     _rootRunUnary (dart:async/zone.dart:1158)
#36     _CustomZone.runUnary (dart:async/zone.dart:1037)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#38     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#39     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#40     _Future._complete (dart:async/future_impl.dart:467)
#41     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#42     _ContextIndex._mergeLocations.<_mergeLocations_async_body> (package:analysis_server/src/services/index/index.dart:319)
#43     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#44     _rootRun (dart:async/zone.dart:1146)
#45     _CustomZone.run (dart:async/zone.dart:1026)
#46     _CustomZone.runGuarded (dart:async/zone.dart:924)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#48     _rootRun (dart:async/zone.dart:1150)
#49     _CustomZone.run (dart:async/zone.dart:1026)
#50     _CustomZone.runGuarded (dart:async/zone.dart:924)
#51     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#54     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#55     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by scheglov** [comment]
https://codereview.chromium.org/2409403002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/56bde6da2884ccfb72436b13a4a41c15f59365d1
