### ISSUE TITLE
Type annotation errors are ignored in strong mode.

### ISSUE THREAD

**Issue by sureshg** [dart-lang/sdk#27552]
In strong mode with linter enabled, the below code shows `Specify type annotation` warning
```
new Future.value("Hello Dart!");
```
but it does allow to provide invalid generic type with no error/warning, e.g: 
```
new Future<int>.value("Hello Dart!");
```

**`Dart VM version: 1.20.0-dev.10.1 (Wed Oct  5 03:36:34 2016) on "macos_x64"`**

**Comment by leafpetersen** [comment]
This is working as intended unfortunately.  Currently the argument to `Future<T>.value` is typed as  `dynamic` to allow either a `Future<T>` or a `T` to be passed as the argument.  There is a tracking bug here: https://github.com/dart-lang/sdk/issues/27503 covering efforts to improve this.
