### ISSUE TITLE
Allow `=` as separator for named parameter default value.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27559]
We have `foo([x = 42])` and `foo({x: 42})` as the ways to specify default values for parameters.

That means that changing your function from a positional parameter to a named parameter is not just changing the `[]` to `{}`, you also have to change `=` to `:` - but it still means exactly the same thing (default value). This breaks the rule about similar things having similar syntax.

Even without changing from one type of parameter to another, I still regularly write `=` for named parameters. There is simply nothing to remind me that it's not `=`.

It might be cute that it 1) looks like a map or 2) looks like how the function is called, but the former is only true in trivial cases and the latter isn't helping anyway - it's not like positional parameter default values looks like arguments in a function call.

- [x] language spec (#27634)
- [x] analyzer (#27635)
- [x] intelliJ
- [x] dart2js (#27636)
- [x] vm (#27637)

**Comment by kasperpeulen** [comment]
This is also how named default parameters are done in ES2015:

<img width="547" alt="screen shot 2016-10-11 at 09 57 59" src="https://cloud.githubusercontent.com/assets/1035299/19262783/37b54f8a-8f99-11e6-896c-614ca86e41ce.png">

**Comment by lrhn** [comment]
(Closing this, assuming the "intellij" checkmark is correct, the remaining ones were fixed by the same CL).

**Comment by munificent** [comment]
Magnificent! If only all language features could be implemented in one giant commit!

You should also update the CHANGELOG and otherwise let people know that this change exists. 🎉

**Comment by lrhn** [comment]
Changelog was https://github.com/dart-lang/sdk/commit/ac76d3eb9f8997c74af0821b5182fa83422bf0ab
About letting people know ... probably a good idea :)

**Comment by lyrachord** [comment]
OK, you do, I do not. It's the life. 👎 

= should just be the assignment symbol.
There is no semantics between the default value with name and the name.
JS version is not brilliant reason for this change.
