### ISSUE TITLE
dart2js: Compiler crash

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#27553]
packages/inversion/src/renderer.dart:23:68:
The compiler crashed when compiling this element.
`Matrix4 _orthographicMatrix, _viewMatrix = new Matrix4.identity(), _modelMatrix = new Matrix4.identity();
                                                                   ^^^^^^^^^^^^ (Pointing at _modelMatrix)
`
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:
- the name and version of your operating system,
  Ubuntu 16.04
- the Dart SDK build number (build number could not be determined), and
  VM Version 1.19.1
- the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on inversion|web/entrypoint.dart threw error: Class 'Identifier' has no instance getter 'assignmentOperator'.

NoSuchMethodError: method not found: 'assignmentOperator'
Receiver: Instance of 'Identifier'
Arguments: []
dart:core                                                      Object.noSuchMethod
package:compiler_unsupported/src/ssa/builder.dart 1784         SsaBuilder.buildLazyInitializer
package:compiler_unsupported/src/ssa/builder.dart 1210         SsaBuilder.build
package:compiler_unsupported/src/ssa/builder.dart 122          SsaBuilderTask.build.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1549            CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/ssa/builder.dart 113          SsaBuilderTask.build.<fn>
package:compiler_unsupported/src/common/tasks.dart 63          CompilerTask.measure
package:compiler_unsupported/src/ssa/builder.dart 111          SsaBuilderTask.build
package:compiler_unsupported/src/ssa/builder.dart 62           SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 1629  JavaScriptBackend.codegen
package:compiler_unsupported/src/compiler.dart 1074            Compiler.codegen
package:compiler_unsupported/src/common/codegen.dart 251       CodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 946             Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176         CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 945             Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176         CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 942             Compiler.emptyQueue.<fn>.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1549            CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 940             Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/enqueue.dart 954              QueueFilter.processWorkItem
package:compiler_unsupported/src/enqueue.dart 645              Enqueuer.forEach
package:compiler_unsupported/src/compiler.dart 939             Compiler.emptyQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176         CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 938             Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 975             Compiler.processQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176         CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 952             Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 877             Compiler.compileLoadedLibraries.<fn>
package:compiler_unsupported/src/common/tasks.dart 176         CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 771             Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 681             Compiler.runInternal.<fn>

Build failed.

**Comment by ds84182** [comment]
When the line is changed from

```dart
Matrix4 _orthographicMatrix, _viewMatrix = new Matrix4.identity(), _modelMatrix = new Matrix4.identity();
```

to

```dart
Matrix4 _orthographicMatrix;
Matrix4 _viewMatrix = new Matrix4.identity(), _modelMatrix = new Matrix4.identity();
```

the build succeeds.

**Comment by sigmundch** [comment]
Thanks for filing the bug and for the details for how you fixed this.

Here is a reduced test program that also reproduces the issue:
```dart
var x, y = [];
main() => y;
```

**Comment by sigmundch** [comment]
@hterkelsen @rakudrama - probably something worth fixing while you work on the kernel-ssa updates

**Comment by efortuna** [comment]
Fixed with https://codereview.chromium.org/2471543004
