### ISSUE TITLE
Dynamic calls on Rectangle.left fail

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27551]
I think this has something to do with the "extension type" stuff, but I don't understand it very well. I'm in the process of getting the Rectangle tests working in dev_compiler, and I discovered that inside `Rectangle.==()`, it does a dynamic call to `.left` on the RHS which is also a Rectangle. That fails. A repro is:

```dart
import 'dart:math';

main() {
  Rectangle rect = new Rectangle(1, 2, 3, 4);
  print(rect.left);
  print((rect as dynamic).left);
}
```

This prints:

```
1
null
```

We probably don't want to be doing a dynamic send inside `==` anyway (type propagation after `if (other is! Rectangle) return false` should fix that), so I can workaround it there for now, but it's an issue in user code.

**Comment by jmesserly** [comment]
the culprit here was the same as https://github.com/dart-lang/sdk/issues/27632
