### ISSUE TITLE
Analyzer server tests on windows started breaking massively

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27557]
At some point between commit 7c784cea9f91a40d66350ed4b08e0422a25ba0ad on Sep 29, 2016 and commit 154bd389dbebb5999940dc2d6abec43202d1dfb0 on Oct 4, 2016, most analyzer_server tests started failing on Windows.  Before this point, there were only 2 failures on the bot, and after this point, there were 73 failures.

Bleeding-edge SDKs for windows can be downloaded from cloud storage, with URLs like:
gs://dart-archive/channels/be/raw/hash/5e5f3cfa608eb8f30e5d0611d56b231ee1ba0c6c/sdk/dartsdk-windows-x64-release.zip

replacing the hash with the hash of the desired commit.

**Comment by whesse** [comment]
I was able to reproduce this by downloading the sdk for build 460, 4e9a4737465e7d0ebbaff0cf86e9b13469e05765
and checking out the repo at that hash, and it produced only 2 errors.

The command I ran on windows was:
D:\src\sdk\sdk>python tools\test.py -mrelease --use-sdk --build-directory=D:\src
\be_sdk\build460\ pkg/analysis_server -c none -r vm
                           
Using binary search, I found that the 2 errors changed to 73 errors with commit
https://github.com/dart-lang/sdk/commit/ef2a3b982cccdd407eb5f2ca74f4a95364c8d7ce

I also notice that the second commit after this one, https://github.com/dart-lang/sdk/commit/154bd389dbebb5999940dc2d6abec43202d1dfb0, is labeled "fix some failures on the windows bots", and it includes a line which assumes that the current drive is C:.  But my local machine has the builds on D:, and our test builders build and test on the E: drive.

Marking the analysis_server tests as skip on windows, in [sdk]/pkg/pkg.status.

**Comment by bwilkerson** [comment]
Yes, I'm aware of the breakage. We made that change so that the bots would give us an accurate picture of what's going on with the tests.

I would prefer that you didn't mark the tests as failing. I have no way to run the tests under Windows locally, so the bots are the only way for me to get a characterization of the reason for the failures. I am actively working on getting the tests to pass, but this will prevent that work, leaving our code untested on Windows.

**Comment by whesse** [comment]
We will have to get another way for you to run the tests locally, because we cannot leave a column red on the buildbot.  I'll follow up offline

**Comment by bwilkerson** [comment]
I don't see why not, it's been red for a very long time (since it was created, according to one source). Changing it now will only prevent me from making progress on fixing the issue. Can we at least agree to wait until I have a way to run the tests locally?

**Comment by bwilkerson** [comment]
Assuming that this is stale.
