### ISSUE TITLE
Analyzer strong mode allows no strong subtyping

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27564]
Look at the following example of the code:

``` dart
class A {}

class C extends A {}

void main() {
  C c = new A();
}
```

In a strong mode analyzer produces an error "[error] Type check failed: new A() (A) is not of type C" and this is an expected result. You can't assign A to type C. But let's rewrite the example above in the following way:

``` dart
class A {}

class C extends A {
  A get a => new A();
}
void main() {
  C c = new C().a;
}
```

Instance of A assigned to variable of type C and analyzer (1.19.1 and 1.20.0-dev.10.2) finds no issues here. There should be an error as well

**Comment by leafpetersen** [comment]
This is working as (currently) intended.  In the first example, the implied downcast is statically guaranteed to fail based on simple inspection of the initializer, and so we issue an error.  In the second example, the mediating interface of the getter leaves open the possibility that the value that reaches the downcast will be an instance of `C` and so the downcast might succeed.  This is an additional strong mode restriction which needs to be specified here: https://github.com/dart-lang/sdk/issues/27530 .

**Comment by leafpetersen** [comment]
using the implicit-cast:false analyzer option is the current way to opt out of this behavior.
