### ISSUE TITLE
Support extends clause with type bounds on dartium

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#27568]
Writing 

```dart
@JS()
class Foo<T extends Bar> {
  ...
}
```
causes problems in Dartium as the Dart VM does not accept the generated patch file as
@patch class Foo<T> {
  ...
}

instead of 
```dart
@patch class Foo<T exends Bar> {
  ...
}
```

We either need to increase the complexity of the patch file generation significantly or extend the existing 
ignore_patch_signature_mismatch flag in the dart vm to allow this case.
Given JS interop only emits static and factory constructor methods that do not reference the type arguments, the type mismatch errors should be generally harmless.

**Comment by lrhn** [comment]
For the record, the original patch file specification did not require type parameters on the patch class. A `patch class` was not a class signature or declaration, just a way to specify the name of the class that the actual patch members belong to.

I think it might have *allowed* the type annotation, for documentation reasons, but omitting it should be allowed.

**Comment by jacob314** [comment]
Fixed by
https://github.com/dart-lang/sdk/issues/27568

@lrhn thanks for the background information!
