### ISSUE TITLE
Mocking better (or at all!) in a fully static/non-nullable Dart

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27563]
We talked about this a little in Seattle today.

Mockito uses `noSuchMethod` to metaprogram/implement missing methods in runtime based on features/API from the Java [Mockito](http://mockito.org/) and uses [Matcher](https://github.com/dart-lang/matcher) to define what is legal.

Already, this breaks down in strong-mode:

``` dart
import 'package:mockito/mockito.dart';

class Animal {
  String eat(Food food) { ... }
  void move({int x, int y}) { ... }
}

class MockAnimal extends Mock implements Animal {}

void main() {
  var animal = new MockAnimal();
  when(animal.eat(any)).thenReturn('Yum!');
  //              ^^^
  //              Is type: Matcher, which is not of type Food.
}
```

This _used_ to work pre-strong mode, but now requires a hacky `typed` API:

``` dart
// Approximately how `typed` is implemented
typed(matcher) {
  _recordTypedMatcherForLaterUse(matcher);
  return null;
}

void main() {
  var animal = new MockAnimal();

  // Ugly
  when(animal.eat(typed(any)).thenReturn('Yum!');

  // Even uglier. We can't guarantee what order named parameters will be called on, so we
  // need users to manually record the name of the argument.
  when(animal.move(x: typed(any, name: 'x'), y: typed(any, name: 'y')).then(...);
}
```

So we lose the nice idiomatic Dart feel and more error-prone boilerplate is involved.

Unfortunately, even _this_ fix relies on a hacky solution that always returns null... What happens when we introduce non-nullables, i.e., imagine this:

``` dart
// Assume this is in a version of Dart with non-nullability by default.
void main() {
  when(animal.eat(typed(any)).thenReturn('Yum!');
  //             ^^^^^^^^^^^
  //             The only value legal here is Food. How do we say "any food"?
}
```

We _maybe_ can get around this by again, being bad, assuming this works in static Dart:

``` dart
dynamic typed(matcher) {
  _recordTypedMatcherForLaterUse(matcher);
  return new Object() as dynamic;
}
```

I've outline an alternative API idea in https://github.com/dart-lang/sdk/issues/27562 that could help, if we could do something like:

``` dart
T any<T>() => implement(T, _AnyMatcher);
//            ^^^^^^^^^^^^^^^^^^^^^^^^^
//            Create a new anonymous subclass of T, i.e.
//            class _Anonymous${T} extends _AnyMatcher implements T {
//              noSuchMethod(_) {}
//            }
```

This would allow removing the `typed` API, as well as working properly/legally in strong-mode.

/cc @srawlins

**Comment by matanlurey** [comment]
Note that is could _also_ be done properly with code generation, but it seems really unfortunate to require a code-generation step for something like this - maybe I could change my mind if we had some static meta-programming/macros.

**Comment by lrhn** [comment]
The API is hacky. It uses the same method call for two things:
```dart
when(animal.eat(any)).thenReturn('yum');
...
animal.eat(hay);
```
That's going to be hard to do in a typed setting because the first call is not type-correct.
It used to work because the type might be wrong, but the call actually works because `noSuchMethod` don't care about types or signatures at all.

Maybe it would be better if it was instead written:
```dart
when(animal).eat(any).thenReturn('yum');
```
That way the "programming interface" for the animal is not the animal itself, it's a new object returned by `when` which can program the `animal`. 

You can even use cascades then:
```dart
when(animal)..eat(any).thenReturn('yum')..isEating.thenReturn(true);
```
(if that makes sense at all).

**Comment by matanlurey** [comment]
We found a solution for the near term, because @srawlins is very smart.

If we ever want to introduce non-nullability, we will need a real solution.
