### ISSUE TITLE
Inconsistent handling of invalid -D options

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27567]
Create a file named `test.dart` containing:

```
main() {
  print('"${new String.fromEnvironment('foo')}"');
}
```

If you run `dart -D test.dart` from the command line, the VM prints "No value given to -D option" and then runs the program. This seems reasonable.

But if you run `dart -Dfoo test.dart` from the command line, the VM prints "No value given to -D option", then tries to load `-Dfoo` as a file and dies. This seems like unfortunate behavior. If it has recognized the `-D` option as being invalid, shouldn't it then discard it, as in the previous case?

**Comment by a-siva** [comment]
In one case it is treating it as an error and in the other case as a warning. Should be easy to make it consistent.

**Comment by bwilkerson** [comment]
I just tested one more case. If you run `dart -D=bar test.dart` from the command line, the VM prints "No value given to -D option", then tries to load `-D=bar` as a file and dies.
