### ISSUE TITLE
Element.classes throws TypeError in dev_compiler

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27579]
Two HTML tests are currently failing—"element_classes_test" and "element_classes_svg_test"—because when they call `.classes` on an Element, it throws:

```
Type 'JSArray<CssClassSet>' is not a subtype of type 'List<CssClassSetImpl>'.
```

**Comment by jmesserly** [comment]
oh wow. Sounds like we might have some unsound typing in there.

**Comment by jmesserly** [comment]
duping against https://github.com/dart-lang/sdk/issues/29901 that seems to have some discussion
