### ISSUE TITLE
NoSuchMethodError message for calling an int is hard to understand

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27571]
``` dart
void x() { }

main() {
  var x = 1;
  // ...much later...                                                                                                                                                                                     
  x();
}
```

=>

```
Class 'int' has no instance method 'call'.

NoSuchMethodError: method not found: 'call'
Receiver: 1
Arguments: []
```

It can be really hard to figure out what's going on here. The message is very confusing.

**Comment by mhausner** [comment]
Confusing maybe, but very accurate. Function x() is shadowed by variable x. If x contained a closure, all would be well.

**Comment by Hixie** [comment]
It now says:
```
NoSuchMethodError: Class 'int' has no instance method 'call'.
Receiver: 1
Tried calling: call()
```

It's still very confusing and we should definitely make this better. Here would be a better message that uses the same style as the current message:

```
NoSuchMethodError: Attempted to use variable 'x' of type 'int' as a function. Since type 'int' does not define a method 'call', this is not possible.
Receiver: 1 (value of variable x)
Tried calling: int.call()
```

Even better IMHO would be:

```
Attempted to use variable 'x' of type 'int' as a function. Since type 'int' does not define a method 'call', this is not possible.
Were you trying to call the method named 'x' defined on line 1 of main.dart? It was shadowed by the variable with the same name on line 4 of main.dart.
For information on shadowing identifiers, see: https://...
For information on using 'call' to make arbitrary objects callable, see: https://...
```

**Comment by mraleph** [comment]
Currently you get this compile time message for the snippet in the first comment:

```console
file:///tmp/x.dart:6:4: Error: The method 'call' isn't defined for the class 'dart.core::int'.
Try correcting the name to the name of an existing method, or defining a method named 'call'.
  x();
   ^
```

Dynamic invocation would still produce the old message. 

If you think that it is still confusing please reopen - but it seems this issue is stale because nothing has happened for two years.

**Comment by mhausner** [comment]
I would like the error message to also remind me to put on sunscreen if necessary. But now that Dart is compiled ahead of time, you'd have to predict the weather at runtime.

**Comment by Hixie** [comment]
I can't reopen (I am not a member of the Dart organisation, I guess), but FWIW, I think it's very confusing for the message to mention "call".

The more useful we make the error messages the better the experience. I think it is perfectly reasonable for us to try to get the messages to be as useful as suggested in https://github.com/dart-lang/sdk/issues/27571#issuecomment-254963638 above.
