### ISSUE TITLE
Set.difference arguments disagree in SDK vs dev_compiler (Set<E> vs Set<Object>)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27573]
Hit this trying to compile pkg/collection w/ DDC.

Help?

CC @vsmenon @leafpetersen 

The dev_compiler version was updated on March 5, 2015 (to Set<Object>, which is good)
SDK version hasn't been changed since Mar 13, 2013

**Comment by floitschG** [comment]
The core library's version looks fine to me. I don't know why DDC has `Set<E>`.

Somehow related: why does api.dartlang.org not show `Set<Object>`? https://api.dartlang.org/stable/1.20.0/dart-core/Set/difference.html

**Comment by kevmoo** [comment]
No! The SDK has `Set<E>` – DDC has (the correct version, IMHO) `Set<Object>`

**Comment by lrhn** [comment]
It probably should have been `Set<Object>` for symmetry with `intersection` and similarity with `removeAll`. 
Changing it now will be a breaking change for strong mode - that makes all existing implementations have covariant parameter overrides which isn't strong-mode sound.

**Comment by kevmoo** [comment]
> Changing it now will be a breaking change for strong mode

Ironically, DDC (at least for its copy of the SDK) is already shipping the break 😄

**Comment by floitschG** [comment]
Aah. I looked at the wrong place.
The SetMixin has `Set<Object>`. (This is probably the reason that DDC has it fixed).
This is just a mistake in the interface.

**Comment by vsmenon** [comment]
What do you guys think is the right fix?

**Comment by floitschG** [comment]
It should be safe to change `Set` in the core library.

**Comment by lrhn** [comment]
Agree, if all the existing implementations have the other behavior anyway, and they do if the use `SetBase` or `SetMixin`, then we should just fix the interface.

**Comment by vsmenon** [comment]
Sounds like `package:collection` will need to be fixed as well from @kevmoo 's original message.
