### ISSUE TITLE
Arguments not given to NoSuchMethodError when calling static in another library

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27572]
When you call a static method that doesn't exist, the arguments are included in the message:

```dart
main() {
  iotest(bool);
}
```
=>
```
No top-level method 'iotest' declared.

NoSuchMethodError: method not found: 'iotest'
Receiver: top-level
Arguments: [Type: class 'bool']
```

...except if the name is qualified and refers to another library:

```dart
import 'dart:io' as io;

main() {
  io.test(bool);
}
```
=>
```
No top-level method 'io.test' declared.

NoSuchMethodError: method not found: 'io.test'
Receiver: top-level
Arguments: [...]
```

(Notice the last line.)

**Comment by fsc8000** [comment]
Thanks for the report! This seems like a bug in the VM where we don't evaluate the arguments before throwing the NSM.

**Comment by Hixie** [comment]
There's a TODO in the NoSuchMethodError code that references this.
See also https://codereview.chromium.org/2405353002/.

**Comment by fsc8000** [comment]
My CL fixes this issue, but I could not yet get rid of the TODO mentioned because there are a few other places where arguments are not passed (or we pass null instead of an empty list)

**Comment by Hixie** [comment]
Null instead of empty list is fine (the Dart code treats them the same way now). Do you know what cases are left where we pass no arguments when we should pass some? I couldn't find any others when I was looking for them.

**Comment by fsc8000** [comment]
I only found the corner case of unresolved ```external static``` function invocations, where we don't pass the arguments on.

For getters we pass ```null```, but those don't have any arguments, so the current code works as expected for getters.

**Comment by Hixie** [comment]
external statics are only something the SDK itself can do, right? Maybe we should just not worry about that case... :-)

**Comment by fsc8000** [comment]
Correct! It is only used inside the SDK, and there should not be any external functions that don't have an implementation there.
