### ISSUE TITLE
Dart Snapshot with Native Extension Code Fails

### ISSUE THREAD

**Issue by ashishgupta02** [dart-lang/sdk#27574]
Dart Snapshot generated code fails to execute if contains native extension code. This lack of feature severely effects when Intellectual Property of code needs to be protected. Dart version 1.20-dev-10.2.

**Comment by rmacnak-google** [comment]
Note that script snapshots do not provide obfuscation. It is possible to recover the program source (without comments) from a script snapshot.

**Comment by ashishgupta02** [comment]
Yes I am aware that obfuscation is currently unavailable in snapshot, but it is better then nothing. Although thanks for looking into the issue.

**Comment by ashishgupta02** [comment]
Thanks .. looks like it is working !
