### ISSUE TITLE
Confusing inference for List<Object> foo = ['foo', 'bar']

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#27586]
``` dart
List<Object> foo = ['foo', 'bar']
```

should result in foo having runtime type `List<Object>` not `List<String>`
This was broken in a recent dart dev compiler roll.

**Comment by jmesserly** [comment]
Yeah we always prefer most precise type information (for better or worse). I chatted with Leaf earlier and will take a look at improving the inference, so it prefers downwards info. The tricky part to this is that we sometimes have imprecise downward info for nested generic methods, and we don't want those types to take priority.

**Comment by jmesserly** [comment]
related: #27625

**Comment by matanlurey** [comment]
We hit a nasty instance of this internally (thanks @leafpetersen).

If this _isn't_ fixed/addressed soon, I'd recommend clearly documenting this (as best you can) in the DDC usage/strong-mode guide - it was definitely very confusing (and the stack trace you get offers almost nothing to help fix it).

**Comment by leafpetersen** [comment]
Cross referencing: https://github.com/dart-lang/sdk/issues/27933

**Comment by jmesserly** [comment]
> If this isn't fixed/addressed soon, I'd recommend clearly documenting this (as best you can) in the DDC usage/strong-mode guide - it was definitely very confusing (and the stack trace you get offers almost nothing to help fix it).

Hi @matanlurey - can you explain what you mean by stack trace? If the compiler/analyzer threw an error that sounds like a different bug.
