### ISSUE TITLE
Address memory leak issue with loading of kernel IR files

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27588]
// TODO(kustermann): Memory leak!
    kernel::KernelReader\* reader = new kernel::KernelReader(buffer, buffer_len);
    const Object& tmp = reader->ReadProgram();
    if (tmp.IsError()) {
      return Api::NewHandle(T, tmp.raw());
    }

**Comment by mraleph** [comment]
I think this was fixed by moving kernel binary data into the heap. Please reopen if it is still an issue.
