### ISSUE TITLE
HOT RELOAD: Reconsider semantics around deleted enum values

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27580]
@gbracha suggests replacing them with a different class that throws when `index` is accessed.

**Comment by johnmccutchan** [comment]
@turnidge @rmacnak-google

**Comment by rmacnak-google** [comment]
Related: In Squeak, any deleted class `Foo` is automatically renamed to `ObsoleteFoo`.

**Comment by a-siva** [comment]
John this is fixed right with the change you made to have all deleted enum values have a sentinel value that is illegal when accessed.

**Comment by johnmccutchan** [comment]
Yes, fixed.
