### ISSUE TITLE
String length Bug

### ISSUE THREAD

**Issue by lymp** [dart-lang/sdk#27584]
```
main(List<String> args) {
  List SL="".split('-');
  int len=SL.length;
  print("SL= $SL");
  print("Length = $len");
}

```
outputs:

SL= []
Length = 1

The length should be zero.

**Comment by kulshekhar** [comment]
From the [docs](https://api.dartlang.org/stable/1.20.1/dart-core/String/split.html):

> If this string is empty, the result is an empty list if pattern matches the empty string, and it is [""] if the pattern doesn't match.

> ```dart
> var string = '';
> string.split('');                       // []
> string.split("a");                      // ['']
> ```

The length calculation seems fine.

**Comment by lrhn** [comment]
Correct - the result of `"".split("-")` is the one-element list containing the empty string, so the output is correct.
