### ISSUE TITLE
Perform an operation on every instance of a class

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27581]
Two passes:

1) Build up a list of all instances of a class.
2) Perform an operation on each instance.

@gbracha @turnidge @rmacnak-google

**Comment by rmacnak-google** [comment]
The most general facility being

```
import 'dart:developer';

class Foo {
   // Reload to add field
   String x = 'defaultValue';
}

// In the debugger evaluate
for (var foo in allInstancesOf(Foo)) foo.x = 'defaultValue';
```

**Comment by mraleph** [comment]
This does not look like something we are going to implement any time soon. Closing as stale. 

@rmacnak-google please reopen if we think this is needed.
