### ISSUE TITLE
DateTime add(new Duration(days:1)) does not handle daylight switch

### ISSUE THREAD

**Issue by jorgjanke** [dart-lang/sdk#27597]
Duration "days: 1" is converted to 24h
This causes issues when switching from/to daylight/standard time: 

```
void main() {
  DateTime theDay = new DateTime(2016,10,30);
	DateTime dateLast = new DateTime(2016,12,3);
  Duration ONE_DAY = new Duration(days: 1);
  while (!theDay.isAfter(dateLast)) {
    print(theDay);
    theDay = theDay.add(ONE_DAY);
  }
}
```
output:
2016-11-04 00:00:00.000
2016-11-05 00:00:00.000
2016-11-06 00:00:00.000
**2016-11-06 23:00:00.000**
2016-11-07 23:00:00.000
2016-11-08 23:00:00.000

Solution: Duration must store Days - I suggest also storing months, ... to properly convert + maintain ISO Duration 1M1DT

**Comment by lrhn** [comment]
That would be a significiant change to `Duration`. It's also difficult to actually compute the difference between two `DateTime` objects in days and months. Days is doable, months requires some guessing as to which is correct. How many days are there from January 28 to March 1? (I'm sure we can do *something*, but it's less clear that it won't be the wrong thing in some cases).

My guess is that working with *dates* and *time zones* at the same time is a mistake. It would be better to have a `Date` class that only works with dates and doesn't include `Time`. Then `DateTime` can be used mainly as a timestamp, which it does amiably.

**Comment by jorgjanke** [comment]
Well, the Duration implementation is basically half there when compared to the ISO Duration standard. The "day" support is a shortcut - and the doc should at least state that a day=24h and that it does not handle daytime/standard time switch.

**Comment by floitschG** [comment]
We will update the docs (both for the `Duration` class, as well as for `DateTime.add`.

It's a bit unfortunate that we used the same name (`Duration`) for a class that is not related to the ISO standard, so I can see where the confusion comes from. With additional comments this should hopefully be more clear, and less error-prone. (If you see other areas that would need more documentation/warnings, please let us know.)

As for the initial request:
We explicitly kept the `Duration` class simple to avoid these issues. A `Duration` really represents a specific duration (in microseconds) and is independent of where it is applied. This is the reason, that `Duration` does not have support for months or years.

As Lasse showed, making `Duration` context-aware comes with lots of interesting problems and questions, and is not something we can easily retrofit (even if we wanted).

**Comment by floitschG** [comment]
Just updated the documentation.
Hope other users won't fall into the same trap.
Thanks.
