### ISSUE TITLE
Dartium download link is broken

### ISSUE THREAD

**Issue by ainjayla** [dart-lang/sdk#27598]
https://storage.googleapis.com/dart-archive/channels/stable/release/1.20.1/dartium/dartium-macos-ia32-release.zip gives:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>

**Comment by whesse** [comment]
This should be fixed by now.  The MacOS Dartium build was changed to 64-bit, and the link didn't change.  It should be correct now on the website, with x64 replacing ia32 in the url.
