### ISSUE TITLE
Element.noSuchMethod breaks analysis server checks

### ISSUE THREAD

**Issue by eukreign** [dart-lang/sdk#27599]
I'm using the standard `dart:html` APIs to build Custom Elements and this means I have a lot of classes extending `HtmlElement`/`Element`.

The problem is that if you extend `Element` it has an implementation for `noSuchMethod()` way up the inheritance path (in `JSObject`). It appears that the Dart analysis service throws its hands up when it finds a class with `noSuchMethod()`.

Here is an example:

![screenshot from 2016-10-17 13-43-43](https://cloud.githubusercontent.com/assets/69960/19448477/fcf5b8fe-946f-11e6-9a93-ab3a148b48c0.png)
https://dartpad.dartlang.org/5f0b6acae7fb19c37c29dbb653948ee7

The expectation is that both `FooConcrete` and `FooConcrete2` should exhibit the same error regarding a missing getter implementation. But because `FooConcrete2` extends `Element` which has `noSuchMethod()` no error is produced.

**Comment by bwilkerson** [comment]
This is actually working as intended. Section 10.4 of the specification reads:

> It is a static warning if an abstract member m is declared or inherited in a concrete class C unless:
> • m overrides a concrete member, or
> • C has a noSuchMethod() method distinct from the one declared in class Object.

Because FooConcrete2 has an implementation of noSuchMethod() that is not the one declared in class Object, no error is expected.

While it would be useful for you to get an error here, it was felt that if you're explicitly handling missing methods via noSuchMethod then you probably don't want the error.

**Comment by eukreign** [comment]
The problem is not at all with Dart or the analysis server. I'm sorry if the wording in my issue was misleading.

The problem is that `Element` has a `noSuchMethod()` implementation and this limits the developer ergonomics of building Custom Elements.

The solution is for `Element` to not have `noSuchMethod()`, that is the goal of this github issue.

Is there another issue tracker I should use for `dart:html`?

**Comment by bwilkerson** [comment]
Nope, I just misunderstood.

**Comment by alan-knight** [comment]
It's not dart:html that has that method, it's dart:js. I believe the use of that is Dartium-specific, so an alternative would be for the analyzer to use the dart2js version of the library. @jacob314

**Comment by jacob314** [comment]
The Analyzer should be using the dart2js version of dart:html which does not use noSuchMethod. The use of NoSuchMethod in Dartium is an implementation detail.

**Comment by eukreign** [comment]
In the meantime is there a workaround? Is changing which version the analyzer uses a simple config change?

**Comment by eukreign** [comment]
The recently released version of Dart appears to use the dart2js version of `dart:html` but this also has a `noSuchMethod` way up the inheritance path. This time the offending parent class is `Interceptor` in `js_runtime/lib/interceptors.dart`.

https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/interceptors.dart#L364

**Comment by rakudrama** [comment]
Interceptor.noSuchMethod cannot be changed - it is required for correct JavaScript code generation.
The implementation is the 'same' as Object.noSuchMethod, just slightly different for low level reasons.
The tool needs to special-case ignore this one.

**Comment by matanlurey** [comment]
`noSuchMethod` semantics has been changed for Dart 2.0.
