### ISSUE TITLE
Mis-formatted error text in spec

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27593]
Section 16.30 Await Expressions contains the following text:

> It is a compile-time error if the function immediately enclosing _a_ is not declared asynchronous.

It is currently formatted as non-normative text, but I believe that it is intended to be normative.

**Comment by lrhn** [comment]
I think it was *intended* to be a commentary - the reason `await f(x)` is a syntax error in a non-async function is that the syntax isn't valid there, it's just an identifier followed by another expression which is not a valid expression. 
However, the specification isn't actually *saying* that anywhere, it's just insinuating it by saying that `await` cannot be used as an identifier in an async function.

What it should say is:

>In an asynchronous function (marked with `async` or `async*`), `await` and `yield` are considered reserved words, In a synchronous function, or outside of functions, `await` and `yield` are not reserved.
> The await-expression (`await expression;` ) only matches when `await` is a reserved word, so it can only be used inside an asynchronous function, likewise the `await for` statement and the `yield` statement.
> Writing `await f();` in a synchronous function is a syntax error because there is no grammar production matching it. (Notice that `await [42]` and `await (f())` are both valid expressions in synchronous functions, but mean something else in asynchronous functions because `await` is not an identifier).

(Or something like that).

**Comment by eernstg** [comment]
No milestone now: An update in the area described above is needed, but with [this CL](https://dart-review.googlesource.com/c/sdk/+/37500) `await` and `yield` will be modified to be reserved words, which implies that the wording should be quite different. However, this will not block Dart 2.

**Comment by eernstg** [comment]
Closing: This spec text was revised extensively in da6938a5b2ac2c7bc3ce92dac7e18a7577e92284. It is still commentary, as it should be, but there is now a more accurate [explanation](https://github.com/dart-lang/sdk/blob/da6938a5b2ac2c7bc3ce92dac7e18a7577e92284/docs/language/dartLangSpec.tex#L10575).
