### ISSUE TITLE
Product build exits with --no-profiler

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#27601]
We use to build `Release` builds while running with the `--no-profiler` flag (older VMs used `--no-profile` flag) to save some some memory. We've moved to `Product` builds and the dartvm exists when presented with the `--no-profiler` flag.

It would be nice to ignore `--no-profiler` when it doesn't matter instead of exiting unexpectedly.

**Comment by johnmccutchan** [comment]
You can pass `--ignore-unrecognized-flags` and the VM will ignore any flags it does not recognize.

**Comment by jtmcdole** [comment]
Thanks for that info - I'll give it a try.
