### ISSUE TITLE
dartdevc should use now SDK-shipped js and summary files

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27607]
Use the files now in the SDK release.
Couldn't we remove/hide these options? Or at least explain that they will have good defaults

```
--dart-sdk                     Dart SDK Path
--dart-sdk-summary             Dart SDK Summary Path
```

**Comment by jmesserly** [comment]
yes definitely. `--dart-sdk-summary` should be removed. `--dart-sdk` should be made internal to the API or hidden, it only exists for us to build the SDK summary.

**Comment by vsmenon** [comment]
Right now, it appears that the dartdevc snapshot in the built SDK is using the analyzer's summary by default.  It could instead use the ones shipped under `dart-sdk/lib/_internal/dev_compiler`.

Note, we don't use `dart_sdk.js` to compile.  But, if someone wants to run with the DDC SDK, they'd need to also use one under `dart-sdk/lib/_internal/dev_compiler`.

**Comment by jmesserly** [comment]
yeah. we should probably move that out of _internal, since folks need to be able to include it.

**Comment by kevmoo** [comment]
I believe @stereotype441 was working around this internally, too – would be good to get this straightened out

**Comment by jmesserly** [comment]
@kevmoo I think @vsmenon is looking into this but let me know if I can help

**Comment by vsmenon** [comment]
Any thoughts on where to move it?  E.g.,
```
dart-sdk/lib/dev_compiler
```

**Comment by nex3** [comment]
`lib/` seems confusing to me, since that directory mostly contains Dart source files which are used in a very different way than this JS. Maybe `dart-sdk/asset`?

**Comment by jmesserly** [comment]
@vsmenon are you looking at this? If not I'll grab it tomorrow. In addition to the JS files, we also need to include the corresponding SDK summaries.

**Comment by vsmenon** [comment]
@jmesserly it's all yours.  :-)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2474523003/
