### ISSUE TITLE
DDC HTML bootstrap code needs to move out of dart_library

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27605]
This code won't kick in for other module formats: 

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/js/legacy/dart_library.js#L130

It needs to be moved elsewhere.

**Comment by jmesserly** [comment]
this should be generated into the SDK JS file, right?

**Comment by vsmenon** [comment]
Yeah, I think so.

**Comment by vsmenon** [comment]
And perhaps the devtools hook as well?

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/js/legacy/dart_library.js#L165

**Comment by vsmenon** [comment]
Ha - that's why I'm not seeing nice formatting in devtools when I run with modules!=legacy.

@jacob314
