### ISSUE TITLE
Some StrongMode codes missing from ErrorCode.values.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#27608]
Including:

* [STRONG_MODE_DOWN_CAST_IMPLICIT_ASSIGN](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/error/codes.dart#L5445)
* [STRONG_MODE_COULD_NOT_INFER](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/error/codes.dart#L5469)

I think that's all. Can we add these to [ErrorCode.values](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/error/error.dart#L672)? Thanks!

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2430873002/
