### ISSUE TITLE
Fail to run a chrome app in dartium with .packages

### ISSUE THREAD

**Issue by jmarichez** [dart-lang/sdk#27603]
running a chrome app in dartium is failing due to symlink removal.
Same chrome app works fine when built in JS and run in chrome browser

**Comment by zoechi** [comment]
How does it work when you load it using `pub serve`?

**Comment by jmarichez** [comment]
It works with pub serve and launch with localhost.
It fails when launched from chromium under chrome://extensions

Envoy? de mon iPhone

Le 18 oct. 2016 ? 22:46, G?nter Z?chbauer <notifications@github.com<mailto:notifications@github.com>> a ?crit :


How does it work when you load it using pub serve?

-
