### ISSUE TITLE
Some Windows VM slaves are running out of memory

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27602]
Timing out on all tests.  Find out what is the problem with https://build.chromium.org/p/client.dart/builders/vm-win-debug-x64-be
and
https://uberchromegw.corp.google.com/i/client.dart/builders/vm-win-debug-ia32-be
and maybe
https://uberchromegw.corp.google.com/i/client.dart/builders/vm-win-debug-ia32-russian-be

Answer: Just-in-time debugging was enabled on these bots, and all crashes were popping up a message box to start the debugger.  These thousands of boxes were keeping processes alive and hogging memory.  Disabled jit debugging with instructions in https://msdn.microsoft.com/en-us/library/k8kf6y2a(v=vs.85).aspx

**Comment by whesse** [comment]
@rmacnak-google 

It looks like we got an assert failure in the vm, and it popped up a "open debugger?" message box for every test, that never got closed.  Disabled JIT debugging.  This may have been enabled since VS 2015 was installed, and we never hit assert failures (calling "abort") before now.

**Comment by whesse** [comment]
The checkboxes in VS 2015 JIT settings didn't fix it.  I had to go into the registry and delete keys, as suggested in http://stackoverflow.com/questions/5668338/how-to-disable-visual-studio-debugger

I deleted 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug\Debugger
and
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\AeDebug\Debugger

**Comment by whesse** [comment]
Change made on vm210-m3, vm250-m3, vm139-m3, vm146-m3, and vm209-m3.

**Comment by rmacnak-google** [comment]
Somewhat related as another source of dialogs: 9dfbd3d2fa4dd9c53f60740fac732b26c16ba00b
