### ISSUE TITLE
Redirection from const to non-const constructor partially allowed with weird behavior

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#27617]
It seems the analyzer (both strong and weak) and the Dart VM allow redirecting from a const constructor to a non-const constructor, but dart2js doesn't. Dart VM even allows printing from such a constructor and side-effects!

Example (code in comments shows other interesting situations):

```
class Foo {
  final String greeting;

  Foo._(this.greeting) {
    print('>>> checking!');
    i = 1;
    if (greeting == null) throw 'null!!!';
  }

  const Foo.hi() : this._('hi');
  const Foo.nullses() : this._(null);
}

int i = 0;
const h = const Foo.hi();
//const n = const Foo.nullses();

main() {
//  print(new Foo.hi().greeting);
//  print(new Foo.nullses().greeting);

  print(h.greeting);
  print(i);
//  print(n.greeting);
}
```

[Dartpad](https://dartpad.dartlang.org/0fe524eb39ef6d799b2a98f6cf733cf7)

The code above doesn't result in analyzer warnings.

In dart2js it crashes with:

```
Error compiling to JavaScript:
[error on line 9] 'const' constructor cannot call a non-const constructor.
```

In Dart VM (in both checked and unchecked modes) the code runs fine and prints:

```
>>> checking!
hi
1
```

**Comment by mhausner** [comment]
Fixed in f73ea62c999f4ad1f4f42832e0fa97a37ed49235

**Comment by yjbanov** [comment]
Thanks for the quick VM fix! However, https://github.com/dart-lang/sdk/commit/f73ea62c999f4ad1f4f42832e0fa97a37ed49235 does not fix the analyzer. Reopening (but ok if that's tracked as a separate issue).

**Comment by mhausner** [comment]
Recycling the bug. Remaining issue is with Analyzer.
