### ISSUE TITLE
Allow implicit dynamic to be inferred from explicit dynamic

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27624]
Consider the following code:

```dart
class Foo {
  List<dynamic> values;

  Foo(Iterable<dynamic> values)
      : values = new List.unmodifiable(values);
}
```

When I run `dartanalyzer --strong --no-implicit-dynamic` on this, I get:

```
[error] Missing type arguments for generic type 'List<dynamic>'. Either add an explicit type like 'dynamic', or enable implicit-dynamic in your Analyzer options.
```

This seems counterproductive. I'm explicitly declaring types at my API boundaries, and I expect them to be inferred elsewhere, just like they would be if I'd written `<String>` instead of `<dynamic>`.

**Comment by jmesserly** [comment]
merging into https://github.com/dart-lang/sdk/issues/26781
