### ISSUE TITLE
Analyzer return exit code 0 even if errors were found

### ISSUE THREAD

**Issue by ugolova** [dart-lang/sdk#27628]
Example of project to recreate issue: https://github.com/ugolova/rembrandt

Steps to recreate issue:
1) I already have an error in file:
`List<String1> brushes = new List<String>(); //String1 classname is error`
2) I run analyzer in strong mode on my project.
3) Output of analyzer:
  `C:\Program Files\Dart\dart-sdk\bin\dartanalyzer.bat --strong --format=machine lib/
  ERROR|STATIC_TYPE_WARNING|NON_TYPE_AS_TYPE_ARGUMENT|C:\\Users\\yulii.lyubeznikov\\WebstormProjects\\rembrandt\\lib\\painter_rembrandt.dart|8|10|7|The name 'String1' is not a type and
 cannot be used as a parameterized type
`

4) Analyzer error code is 0 

**It is not correct**, because if analyzer find error, it should exits with code 3.

Because of that there is no exception generated. So, I couldn't detect on my continious integration server in my other big project while building process, that there are an analyzer errors. So my code may become not so good and pure. It is a really important for me, please fix it ASAP.

Thanks.

P.S. I added grind task to project, so I could run analyzer easily, just write into console 'pub run grinder analyze'

**Comment by natebosch** [comment]
I can (no longer) reproduce an exit code of 0 from `dartanalyzer.bat` when there are failures.
