### ISSUE TITLE
Implicit dynamic complains about Object-typed generics

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27625]
If I have the following Dart code:

``` dart
class Foo {
  final List<Object> values;

  Foo(Iterable<Object> values)
      : values = new List.unmodifiable(values);
}
```

and I run `dartanalyzer --strong --no-implicit-dynamic` on it, I get:

```
[error] Missing type arguments for generic type 'List<dynamic>'. Either add an explicit type like 'dynamic', or enable implicit-dynamic in your Analyzer options.
```

I'd expect the analyzer to infer `List<Object>`. If I change `<Object>` to `<String>`, inference works as expected.

**Comment by jmesserly** [comment]
oh shoot. I'll need to check if my current CL makes this better. Yeah, we're not recording type constraints in some cases.

**Comment by jmesserly** [comment]
(when the constraint is trivial, like top type)

**Comment by jmesserly** [comment]
related: #27586
