### ISSUE TITLE
Strong mode inference failure messages are very hard to diagnose

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27620]
Strong mode inference now issues an error when there is no solution to the inference constraints.  The error messages don't do a good job of pointing out why the inference is failing.  It shouldn't be hard to pinpoint the spot where the conflicting constraints come from, and we should do so.

See for example here: https://github.com/dart-lang/sdk/issues/27618 .

cc @jmesserly @bwilkerson @srawlins

**Comment by jmesserly** [comment]
we fixed this a while ago :)
