### ISSUE TITLE
implicit-downcasts in analysis_options doesn't work

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27622]
If I have the following `.analysis_options` file:

```yaml
analyzer:
  strong-mode:
  - implicit-downcasts: false
  - implicit-dynamic: false
```

and the following Dart file (taken from [this example](https://www.dartlang.org/guides/language/analysis-options)):

```dart
// test.dart

void main() {
  Object o = new Object();
  String s = o;  // Implicit downcast
  String s2 = s.substring(1);
}
```

and I run `dartanalyzer test.dart`, it only reports:

```
[hint] The value of the local variable 's2' is not used
```

The same is true if I run `dartanalyzer --strong --no-implicit-casts test.dart`. However, if I delete `.analysis_options` and run `dartanalyzer --strong --no-implicit-casts test.dart`, I get:

```
[error] A value of type 'Object' cannot be assigned to a variable of type 'String'
[hint] The value of the local variable 's2' is not used
```

I've tested this against Dart 1.20.1 and 1.19.0. I think the `implicit-dynamic` flag has the same issue, but I don't know of a simple file to test it on.

**Comment by jmesserly** [comment]
I believe you're looking for `implicit-casts: false`

**Comment by nex3** [comment]
That's not what [the docs](https://www.dartlang.org/guides/language/analysis-options) say...

**Comment by nex3** [comment]
Even if I change `implicit-downcasts` to `implicit-casts` in the analysis options file, the results are the same.

**Comment by jmesserly** [comment]
> That's not what the docs say...

@Sfshaza - where would the best place to be for filing a documentation bug? The flag has always been called `implicit-casts` (https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md#disable-implicit-casts, https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/task/options.dart#L71)

@nex3 -- does it behave any better if you restart analysis server? We've seen bugs in the past where e.g. strong-mode will not be enabled correctly until a restart.

**Comment by nex3** [comment]
I'm not using the server, I'm just using the CLI.

**Comment by jmesserly** [comment]
Oh. I'm not familiar with under what conditions the CLI will use analysis_options. Does strong mode seem to be working at all?

**Comment by nex3** [comment]
I'm not sure. What's a good test case for that?

**Comment by jmesserly** [comment]
```dart
class C {
  int x() => 0;
}
class D extends C {
  Object x() => 'hi'; // strong mode: invalid override
}
```

**Comment by jmesserly** [comment]
@nex3 could this be the bug you are seeing: https://github.com/dart-lang/sdk/issues/26959

**Comment by nex3** [comment]
> ```dart
> class C {
>   int x() => 0;
> }
> class D extends C {
>   Object x() => 'hi'; // strong mode: invalid override
> }
> ```

If I analyze this with `dartanalyzer` and the `.analysis_options` file listed above, it emits no errors. Same if I replace `implicit-downcasts` with `implicit-casts`.

**Comment by jmesserly** [comment]
yeah, that means it's not running in strong mode. I believe you're seeing #26959 -- Analyzer CLI does not use analysis_options

**Comment by nex3** [comment]
I don't think that's it—I'm analyzing files, not directories, and if I write

```yaml
analyzer:
  strong-mode: true
```

strong mode works fine.

**Comment by jmesserly** [comment]
this works for me:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```
the problem is the leading "-", it's a YAML map not a list.
This was noted in [the docs I wrote](https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md#disable-implicit-casts), so it looks like this is a problem with the live documentation.

Move this to https://github.com/dart-lang/site-www/issues?

**Comment by bwilkerson** [comment]
dartanalyzer, wrongly in my opinion, is sensitive to the current working directory. I think this sometimes causes problems with discovery of options files. I'm not sure that's what's happening in this case, though.

**Comment by jmesserly** [comment]
I believe this has been moved to https://github.com/dart-lang/site-www/issues/161. thanks @nex3 !
