### ISSUE TITLE
*ngSwitchWhen parsing bug in Dartium

### ISSUE THREAD

**Issue by dustin486** [dart-lang/sdk#27621]
Hello,

I am working on a project and was very confused last night when some simple code would not work. I was doing all of the testing from Dartium and it would not properly parse a ngSwitchWhen statement. I decided to test it today in Vivaldi and Chrome and it works as expected, but will not work at all in Dartium. The switches for "F", "H", and default work fine, but "FO" does not work at all.

```
<span *ngSwitchWhen="'F'">F switch</span>
<span *ngSwitchWhen="'FO'">FO switch</span>
<span *ngSwitchWhen="'H'">H switch</span>
<span *ngSwitchDefault>Default switch</span>   
```

**Comment by vsmenon** [comment]
What's the parse error you are getting?  Is it in the JS console?

**Comment by dustin486** [comment]
There is no parse error, the JS console is clean. It just doesn't parse and goes to the default switch instead.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/angular2#150
