### ISSUE TITLE
Analyzer support for Dart 1.50 non strong mode generic methods.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27641]
We have an informal specification for Dart 1.50 generic methods here:

https://docs.google.com/document/d/1nccOSkdSyB9ls7TD8gUqIu6Wl2J_9bTSOoMCEIoAiQI/edit#heading=h.dnanv15dn1me

The analyzer should remove the partial support for error checking on generic methods (or make them into hints as warranted).

The only static errors for Dart 1.5 non strong mode generic methods are syntax errors, and errors for using a generic method parameter for an `is` check as in `x is T`, or as a type literal.

**Comment by kulshekhar** [comment]
Can the linked document be publicly shared?

**Comment by eernstg** [comment]
Here's a public version of the [informal specification of generic method syntax](https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c) that Leaf mentioned. Note that we do not commit to the contents of this file, things may still change!

**Comment by bwilkerson** [comment]
I believe that https://codereview.chromium.org/2487583002/ correctly converts errors to hints in the non-strong-mode case.

As far as I know the only remaining step is to remove the flag, so please let me know when doing so is appropriate.

**Comment by leafpetersen** [comment]
At some point there should be a non-strong mode error when a generic method parameter is used directly in an `is` check (e.g. `x is T`).  Note though that `x is List<T>` is not an error.  

This error is just transitional, to ensure that users do not rely on instance check behavior that will differ between strong mode and non-strong mode.

**Comment by bwilkerson** [comment]
Error, warning, or hint?

**Comment by leafpetersen** [comment]
It is an error.

**Comment by leafpetersen** [comment]
Also note, the error is only in an 'is' check, not in a cast expression ('x as T').

**Comment by bwilkerson** [comment]
I believe that https://codereview.chromium.org/2479293004/ adds the required error. As far as I know, that's everything except for removing the flag. Please let me know if you know differently.

**Comment by eernstg** [comment]
Sounds good! I'll return with more info when we have a robust plan for how to remove the flag in a way that doesn't disrupt google3.

**Comment by eernstg** [comment]
We've got the CLs now, for enabling this feature by default (see #27501).

**Comment by bwilkerson** [comment]
Does that mean that I should commit the CL now, or are we still waiting?

**Comment by eernstg** [comment]
Keep it back a little bit: We had a lot of things going on today and I haven't yet done the global pre-submit test run. I'll give a heads up when it's done, which should be tomorrow.

**Comment by dgrove** [comment]
@eernstg can you provide an update?

**Comment by eernstg** [comment]
Please check #27501 for the current status.

**Comment by eernstg** [comment]
The language group discussed the situation and agreed that it is OK to proceed to land the [analyzer CL](https://codereview.chromium.org/2494873004) and then handle the error-to-hint adjustments afterwards.

**Comment by dgrove** [comment]
@bwilkerson when can the CL for this be landed? 

cc @kevmoo

**Comment by bwilkerson** [comment]
Committed
