### ISSUE TITLE
Problematic error recovery on missing expression in field access

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27646]
_From @lukechurch on October 21, 2016 5:55_

Plugin 0.1.2

PLMK if you would prefer this to be refiled in the Dart SDK repo.

<img width="1383" alt="screen shot 2016-10-21 at 06 52 47" src="https://cloud.githubusercontent.com/assets/2978182/19588074/13a9444c-975b-11e6-829e-5897defd854a.png">

A missing expression in the map access causes 24 parse errors to be listed in the problems view. This masks the useful warning 'WARNING: The argument type 'Map<int, Color>' cannot be assigned to the parameter type 'Color'. ([flutterTestProject] lib/main.dart:40)'.

Actual code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new FlutterDemo(),
    ),
  );
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  _FlutterDemoState createState() => new _FlutterDemoState();
}

class _FlutterDemoState extends State<FlutterDemo> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Flutter Demo'),
      ),
      body: new Center(
        child: new Text(
            'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
            style: new TextStyle(color: Colors.blue[] )

            ),

      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

_Copied from original issue: flutter/flutter-intellij#359_

**Comment by devoncarew** [comment]
_From @pq on October 21, 2016 12:49_

I think this probably should be tracked on the analyzer proper (or Dart Plugin) but it doesn't seem out of line to track it here too since it's very much user-impacting.

To know where it should be fixed, we need to suss out what parser (analyzer or IntelliJ) could do better recovery.

cc @bwilkerson @alexander-doroshko for context on parser errors...

**Comment by devoncarew** [comment]
_From @alexander-doroshko on October 21, 2016 13:2_

Problems listed in the Dart Analysis tool window come from the Analysis Server, not from Dart plugin's parser.

**Comment by devoncarew** [comment]
_From @pq on October 21, 2016 13:9_

Great.  Thanks!  In that case, paging @scheglov and @bwilkerson.   This seems like a great candidate for improved parser recovery.

**Comment by devoncarew** [comment]
_From @pq on October 21, 2016 13:11_

FWIW I've added a new `analyzer` label to tag issues that derive from analyzer.  I'm thinking there should be a corresponding bug on the SDK as well but will defer to @bwilkerson on how we wants to manage that.

**Comment by devoncarew** [comment]
I'll bump this over to the sdk repo proper.

**Comment by devoncarew** [comment]
@bwilkerson for triage

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2444453002/
