### ISSUE TITLE
when reanalyzing, the analysis server should flush info from the .analysis_options file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27656]
When a client issues an `analysis.reanalyze` call, the analysis server should also flush info from the .analysis_options file. @Sfshaza ran into an issue where changing an analysis options file over to strong mode didn't take effect even after a reanalyze call (it was necessary to restart IntelliJ).

**Comment by zoechi** [comment]
or use use the kill analyzer feature (no button anymore though)

**Comment by devoncarew** [comment]
Yeah, we would like `analysis.reanalyze` to work for this.

**Comment by bwilkerson** [comment]
This turned out to be user error. Server correctly detects changes to the analysis options file and re-analyzes as appropriate.
