### ISSUE TITLE
Analyzer has no compatible package:test version while developing 0.30.0.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27654]
Because analyzer and test are interdependent, there is no good way of writing a pubspec for 0.30.0-dev...
because no test version accepts 0.30.0 of the analyzer.

Disabling pkgbuild/pkg/analyzer until 0.30.0 lands and a compatible test version is released and in DEPS.
Please remove this status change, and close issue, then.

@bwilkerson @stereotype441 @keertip @munificent

**Comment by munificent** [comment]
@nex3

**Comment by nex3** [comment]
Can you use `dependency_overrides`?

**Comment by whesse** [comment]
I tried using dependency_overrides (for test, in analyzer's pubspec), but it didn't seem to work.  It should be the correct solution - could you try and make it work?  Maybe I just didn't know how.

**Comment by nex3** [comment]
When I add

```yaml
dependency_overrides:
  test: "^0.12.0"
```

to `pkg/analyzer/pubspec.yaml` and run `pub get`, it completes successfully. If it's not working on the package bots, I think that's probably an infrastructure issue.

**Comment by pq** [comment]
This one is happily behind us.  Closing as stale.
