### ISSUE TITLE
NoSuchMethodError.toString should handle _Type.call() case

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27651]
...or maybe _Type.call() itself should be implemented and throw a NoSuchMethodError with an appropriate message.

This situation occurs when you have code that omits the "new" in a call like this:

``` dart
  var x = Timer();
```

Right now it says:

```
NoSuchMethodError: Class '_Type' has no instance method 'call'.
Receiver: Type: class 'Timer'
Tried calling: call()
```

This is highly unclear and we've seen experienced Dart engineers in usability studies get mildly confused by it. We should instead say something like:

```
NoSuchMethodError: Attempted to use type 'Timer' as a function. Since types do not define
a method 'call', this is not possible. Did you intend to call the Timer constructor and
forget the 'new' operator?
Receiver: Type: class 'Timer'
Tried calling: Timer()
```

See also https://github.com/dart-lang/sdk/issues/27571.

**Comment by vsmenon** [comment]
BTW, this should always be a static error (and a static error during AOT compilation, not a runtime one).   Are you not seeing a static error?

**Comment by lrhn** [comment]
The Dart spec doesn't make it a compile-time error to try to call an object that isn't a function. It should be caught in strong mode because the static type isn't callable, but in spec mode, it's just a static warning/runtime error.

**Comment by Hixie** [comment]
I totally agree that the analyzer should do a better job of reporting this as well, but this issue is specifically about the exception that is thrown.

**Comment by fsc8000** [comment]
https://codereview.chromium.org/2507493003/ improves the error message: e.g.

```
Unhandled exception:
NoSuchMethodError: Attempted to use type 'A' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the A constructor and forget the 'new' operator?
Receiver: Type: class 'A'
Tried calling: A(1, 2, 4)
```
