### ISSUE TITLE
Coveralls coverage for DDC is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27652]
The tag here points into the unknown:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/README.md

Broke during the migration from the old github repo.

@kevmoo

**Comment by kevmoo** [comment]
- [ ] Enable coveralls for sdk repo
- [ ] Add coveralls private token to travis environment for sdk
- [ ] Verify that it works

**Comment by kevmoo** [comment]
@vsmenon 

See https://travis-ci.org/dart-lang/sdk/jobs/170102200#L519

Looks like we need to update the coverage script?

**Comment by jmesserly** [comment]
we're not using travis for DDC anymore
