### ISSUE TITLE
In Flutter, Object.runtimeType allocates thousands of objects (straight into the old generation so they rarely get GC'ed)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27663]
When running a Flutter application that animates continually and creates a lot of new widgets each frame, Flutter calls runtimeType many times. This results (according to the Allocation Profile in Observatory) in many hundreds of _Type objects being allocated per second. They go straight into the old GC generation so we allocate megabytes of these before GC kicks in to get rid of them.

Here's a sample Flutter app that tickles this scenario. To use it, run `flutter create`, then replace the `main.dart` it created with the code below and run `flutter run`.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyHomePage());
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin {

  Animation<double> _animation;

  void initState() {
    _animation = new AnimationController(
      lowerBound: 0.0,
      upperBound: 100.0,
      duration:	const Duration(seconds: 10),
      vsync: this,
    )..addListener(() { setState(() { }); })
     ..repeat();
  }

  @override
  Widget build(BuildContext context) {
   return new MaterialApp(
     home: new Scaffold(
       appBar: new AppBar(
         title: new Text('Demo'),
       ),
       body: new Stack(
         children: <Widget>[
           new Positioned(
             top: _animation.value,
             left: 10.0,
             right: 10.0,
             child: new Text('Animating...'),
           ),
         ],
       ),
     ),
   );
  }
}
```

**Comment by rmacnak-google** [comment]
@a-siva @crelier 

I'm thinking the native for `Object.runtimeType` should allocate in new space and only move the type to old space if it creates a new canonical type.

**Comment by a-siva** [comment]
I would have expected these to be canonicalized always, is the canonicalization failing or are we not canonicalizing at all?

**Comment by mraleph** [comment]
I have just landed a CL (f4ec20abac2286604565e9d5a6d1d744849c964d) that should significantly reduce amount of allocated `_Type` objects.

**Comment by mraleph** [comment]
@a-siva even though they are canonicalized they are all allocated in Old space because `Type::New` has `kOld` as default value for `space` argument.

**Comment by crelier** [comment]
We used to clone types to old space on canonicalization. I am not sure why this changed, maybe due to background compilation requirements?
Anyway, I sent a cl that should resolve this.
