### ISSUE TITLE
Hot reload should run initializers for new instance fields

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27666]
We saw this in both Flutter usability studies last week, and then I ran into it today myself:

When you add an instance or static field with a static initializer to a class, you expect the field to start off with the value of the initializer, not null. It is really confusing when you think it has a particular value, but it actually has the value null.

cc @johnmccutchan, @rmacnak-google

**Comment by rmacnak-google** [comment]
Static initializers in Dart run lazily. The first time you access a new static field, the initializer will run and you shouldn't see null unless the initializer evaluated to null. If you're seeing that, it sounds like a bug that isn't specific to hot reload. Do you have an example that reproduces this?

**Comment by Hixie** [comment]
Install Flutter, connect a phone to your computer, then run:
```
flutter create dummy
cd dummy
flutter run
```
Edit `lib/main.dart` to add `final String test = 'foo';` to `MyApp`, and change the line that instantiates `MyHomePage` to look as follows:
```dart
      home: new MyHomePage(title: 'Flutter Demo "$test"'),
```

Then, hit `r` in the `flutter run` console.

The app toolbar changes to `Flutter Demo "null"`.

**Comment by rmacnak-google** [comment]
Oh, _instance_ fields.

**Comment by Hixie** [comment]
Hm, interesting. I could have sworn I'd also seen this fail with static fields but I can't reproduce that.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2489723003/
