### ISSUE TITLE
Autocompletion / Analyzer - the never ending story...

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#27665]
First I must say Analyzer is getting better and better but if feels still somehow late beta.

My problem is not so easy to describe - you have see it. Check out the attached video.
~0:31 

I'm in DeviceEditInplace which inherits from MdlTemplateComponent. The base class for MdlTemplateComponent is MdlComponent. MdlComponent has the "query" function.

Analyzer finds the function but I have to click around, hit strg+space (autocompletion) several times and after a while it recognizes what I want... - a bit annoying.

[analyzer_autocompletion.mp4.zip](https://github.com/dart-lang/sdk/files/550928/analyzer_autocompletion.mp4.zip)

**Comment by bwilkerson** [comment]
@danrubel @scheglov

**Comment by bwilkerson** [comment]
I hope and suspect that this has been addressed by now.
