### ISSUE TITLE
Hot reload should update constants whose initialisers changed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27667]
It's common to have a bunch of constants and want to try tweaking them to find the right set of values that makes the UI pretty.

**Comment by johnmccutchan** [comment]
@Hixie Can you provide me a concrete example that you'd like to work?

**Comment by Hixie** [comment]
Sure. Start from the template Flutter app.
There's a line that says `title: 'Flutter Demo Home Page'`.
Replace that with `title: appTitle` and add a `const appTitle = 'Flutter Demo Home Page'`. Hot reload.
Change the value of the constant. Hot reload.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2474193002

**Comment by johnmccutchan** [comment]
@turnidge FYI the change in semantics
