### ISSUE TITLE
DDC: Wrong constructor when extending a js annotated class?

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#27673]
Extending an `@JS` annotated class will produce a class trying to invoke the `new()` method that doesn't exist in that case:
### Dart

```
@JS('OneJS')
class One {
  ...
}

class Two extends One {
}
```
### Generated code

```
class Two extends dart.global.OneJS {
  constructor() {
    new();
  }
 }
```

No constructor should be generated in this case.

**Comment by dam0vm3nt** [comment]
@vsmenon @jacobr

**Comment by jmesserly** [comment]
What we should generate is probably more like:
```js
class Two extends dart.global.OneJS {
  constructor(...args) {
    super(); // if needed
    this.new(...args);
  }
  new() {
    // dart constructor logic goes here, otherwise should be empty
  }
 }
```

tricky part is there's a lot of permutations depending on what constructors the JavaScript type has. 

For example if the JS type had a constructor:
```dart
@JS('OneJS')
class One {
  One(x, y);
  ...
}
class Two extends One {
  int z;
  Two(x, y, this.z) : super(x, y) {
  }
}
```
should generate something like:
```js
class Two extends dart.global.OneJS {
  constructor(x, y, ...args) {
    super(x, y);
    new(...args);
  }
  new(z) {
    this.z = z;
  }
 }
```

**Comment by jmesserly** [comment]
I think we had a bug on the old issue tracker about this, but essentially extending JS types from Dart is not supported to my knowledge (by any Dart implementation). It will be fairly straightforward to implement in DDC, but I'm not sure about other impls.

**Comment by dam0vm3nt** [comment]
But that's one of @jacobr targets that showed as next step for js-interop in the summit, and it would be a nice thing to have in order to better integrate with the web platform. Why not letting the user declare the constructor in the js facade (like you did in the example, maybe marking it external), that way it should be his/her responsibility to override it and it should be obvious what to do.

**Comment by jmesserly** [comment]
yeah totally agree @dam0vm3nt

**Comment by dam0vm3nt** [comment]
In the end this is just what you do with normal dart classes. Btw @jacobr also mentioned the other way around : extending Dart classes from js...

**Comment by dam0vm3nt** [comment]
@jacob314 , @jmesserly any news on this one ?

**Comment by jmesserly** [comment]
wish I could help, but this is @jacob314 's area.

**Comment by vsmenon** [comment]
We're not likely to support this any time soon.
