### ISSUE TITLE
DDC : casting to an @JS facade breaks the code

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#27675]
If you try to cast an object coming from js to an `@JS` annotated class the generated DDC code will throws because the JS constructor lacks the static `_check` or `as` methods:
### dart

```
@JS('OneJS')
class One {
  ...
}

createSomething(what) {
 if (what=='One') {
  return new One();
 }
}


One one = createSomething('one');
```
### generated code:

```
...
let one = pkg$.OneJS._check(...);
```

@vsmenon @jacobr

**Comment by jacob314** [comment]
Fixed by adding type objects for JS interop types in DDC in early november.
