### ISSUE TITLE
int literals should be double literals

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27678]
The following isn't currently possible:

``` dart
double i = 0;
```

We commonly get complaints from our users that they receive the runtime error "type 'int' is not a subtype of type 'double'", or the analyzer warning "A value of type 'int' cannot be assigned to a variable of type 'double'", whenever they put literal numerics in their code. Literal numerics are very common in Flutter code. The problem is caused by users using integer literals where we expect doubles.

We would like to be able to accept integer literals where doubles are expected, with no runtime overhead (i.e. with the conversion done at compile time).

It seems like this should be relatively straight-forward in a strong mode environment.

**Comment by lrhn** [comment]
I can promise you that this is on our radar, and it is doable in a strongly typed setting - if you remember to type the variable.
```dart
var x = 0;
double y = x;  // whoops, x was probably inferred as int, definitely not as double.
```

**Comment by rmacnak-google** [comment]
s/strongly/statically/

**Comment by lrhn** [comment]
Indeed. I was trying to refer to "strong mode" colloquially, but that sentence actually means something else and it is indeed wrong.

Dart is strongly typed, and always has been. With "strong mode", it's also statically typed (except when the program is dynamic).

**Comment by natebosch** [comment]
Relevant issue on the language repo: https://github.com/dart-lang/language/issues/3
And solution proposal: https://github.com/dart-lang/language/issues/4

Is it worth keeping this issue in the SDK open until the feature is implemented or should we close and track on the language repo?

**Comment by jayphelps** [comment]
This is [supported in Dart 2.1](https://medium.com/dartlang/announcing-dart-2-1-improved-performance-usability-9f55fca6f31a#ae33)

**Comment by mraleph** [comment]
This is done ✅
