### ISSUE TITLE
Globally activated binaries now expect the package to be in hosted/pub.dartlang.org/[pkg]

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27670]
Repo

1. With Dart 1.20.1 (gold) – `pub global activate pubviz`
2. Use `pubviz` – see that it works
3. Upgrade to `1.21.0-dev.2.0`
4. Run `pubviz`

## Expected:

```
Wrong script snapshot version, expected 'e367676b71613c7a688c5cae19dce834' found '5975a88a2cd91acf880909d213afc261'
Wrong script snapshot version, expected 'e367676b71613c7a688c5cae19dce834' found '5975a88a2cd91acf880909d213afc261'
```

Then in runs

## Actual

```
Wrong script snapshot version, expected 'e367676b71613c7a688c5cae19dce834' found '5975a88a2cd91acf880909d213afc261'
Wrong script snapshot version, expected 'e367676b71613c7a688c5cae19dce834' found '5975a88a2cd91acf880909d213afc261'
Could not find a file named "pubspec.yaml" in "/Users/kevmoo/.pub-cache/hosted/pub.dartlang.org/pubviz-2.3.7".
```

This is *very* new and unexpected behavior.

**Comment by kevmoo** [comment]
CC @nex3 @munificent

**Comment by nex3** [comment]
The version of pub in the SDK [didn't change](https://github.com/dart-lang/sdk/compare/1.20.1...1.21.0-dev.2.0#diff-946813de8d9b30857edae58aec4f3a7fR94) between those two versions, so I'm guessing this issue comes from elsewhere in the SDK (although it's possible an SDK change triggered a pub bug). Can you post the `--verbose` output?

**Comment by kevmoo** [comment]
Well, shucks. Just tried going back to `1.20.1` clean install of pubviz – then back to `1.21.0-dev` – no repo.

Will need to dig some some. Stay tuned.

**Comment by kevmoo** [comment]
Gah! This might be with packages activated before 1.20 or something.

Closing for now.
