### ISSUE TITLE
Switching an async function to `async *` doesn't update analysis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27689]
Start with some Dart code in IntelliJ.

``` dart
Future foo() async { ... }
```

Start by updating the return type to `Stream`

``` dart
Stream foo() async { ... }
```

Dart analyzer: `WARNING: Functions marked 'async' must have a return type assignable to 'Future'.`

Cool.

Now, update method to be `async*`

``` dart
Stream foo() async* { ... }
```

Expected: no errors/warnings
Actual: `WARNING: Functions marked 'async' must have a return type assignable to 'Future'.`

Work-around: reanalyze all.

**Comment by skybrian** [comment]
Happened to me as well. Another workaround is to delete the 'S' in Stream and add it back again.

**Comment by bwilkerson** [comment]
@scheglov Is this related to incremental analysis?

**Comment by scheglov** [comment]
https://codereview.chromium.org/2498873004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/b2c94a8a8987f70254232f8b6c837799d0cc3368
