### ISSUE TITLE
dev compiler should warn if an input src already exists in a summary

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#27686]
I don't think there is a valid use case for this anyways, and it would help a bit with the bazel rules.

**Comment by jmesserly** [comment]
... or issue an error?

**Comment by jakemac53** [comment]
I would be fine with that as well :). However it might be a breaking change... it might be best to start it out as a warning and then upgrade to an error in a later release?

**Comment by jmesserly** [comment]
I'm inclined to say this should be an error at the Analyzer/CFE level, rather than DDC (as it's something any modular compiler could hit, such as summary build). We haven't needed this in a while so I'm going to close, I do think we could reopen for the front-ends though.

**Comment by jakemac53** [comment]
I think we have build rule level checking for this now internally anyways.
