### ISSUE TITLE
Code complete named param should be a String, but is offered a Typography

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27688]
_From @sethladd on October 27, 2016 14:27_

![screen shot 2016-10-27 at 4 23 04 pm](https://cloud.githubusercontent.com/assets/5479/19771047/d6d6478e-9c61-11e6-978f-f36936218c45.png)

`fontFamily` is what I'm trying to complete. It can take a String. Notice how the first option is a Typography. If I hit enter, Typography is inserted.

_Copied from original issue: flutter/flutter-intellij#387_

**Comment by bwilkerson** [comment]
@scheglov

**Comment by sethladd** [comment]
> Maybe we should explicitly prioritize suggestions with the same type as the type of a parameter.

That sounds reasonable. In the absence of other info, let's offer types that match what the arguments expect. Thanks!

**Comment by danrubel** [comment]
In order to do this, we need IJ to display completion results in the order specified by Analysis Server `relevance` field.

**Comment by bwilkerson** [comment]
@jwren @alexander-doroshko Any thoughts?

**Comment by alexander-doroshko** [comment]
IntelliJ IDEA does use `relevance` field. Additionally it may bubble up the most frequently (or recently) used items.

**Comment by jwren** [comment]
Earlier in the year I was doing exactly this- having the type information be used to either remove suggestions, or to have the relevance changed.  There is a lot of opportunity, especially as no one owns completions as a full time role right now.

**Comment by bwilkerson** [comment]
We are now using the type of the parameter when ranking suggestions.
