### ISSUE TITLE
Hot reload breaks native extensions

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#27682]
When I reload an isolate via the Dart service protocol (`_reloadSources` with `isolateId` as parameter), it seems like native extensions are not reloaded, or somehow unloaded. I get errors saying my native function cannot be found. I could put together a small example library to demonstrate this but perhaps this already rings a bell.

The issue can in theory be replicated by cloning this repo: https://github.com/hermanbergwerf/fltk-dart, and following these instructions:
1. `make compile-fltk`
2. `make generate-bindings`
3. `make compile-ext`
4. `dart bin/flfn_serve.dart test/flfn/hello_world.dart`
5. Make a modification to `dart bin/flfn_serve.dart test/flfn/hello_world.dart` (just saving without modification should actually be enough). This error should be in the stdout:

```
Unhandled exception:
'package:fltk/src/fl/core.dart': error: line 40 pos 1: native function 'fldart::check' (0 arguments) cannot be found
int check() native 'fldart::check';
^

#0      runAsync.<anonymous closure> (package:fltk/src/fl/core.dart:26:19)
#1      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

There might be some environment dependent issues with replicating these steps though, for example because some libraries are missing.

@johnmccutchan

**Comment by hermanbergwerf** [comment]
Interestingly, the error also happens when there are no changes (I didn't really think about that at first), leaving me wondering how the source reload decides which libraries are affected (in the case of 0 changes I would say no libraries are affected). Also, from the code in the native extension loader, it seems the extension name resolver is attached to a library, so why is the library that imports this extension  (the FLTK library), affected by the hot reload?

**Comment by hermanbergwerf** [comment]
I looked around through the sources a bit. For anyone reading this who is not familiar with the VM source, the libraries that have changed seem to be resolved here: https://github.com/dart-lang/sdk/blob/89560c68a0660c752025339154271cccc3bc12dc/runtime/vm/isolate_reload.cc#L452.

**Comment by johnmccutchan** [comment]
@hermanbergwerf I suspect we have a small bug in how we handle native extensions in reload. I will look at this soon.
