### ISSUE TITLE
Options for named param aren't helpful

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27687]
_From @sethladd on October 27, 2016 11:13_

Trying to figure out what goes into a textTheme. Here's what I saw:

![screen shot 2016-10-27 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/5479/19765141/1e10bff0-9c47-11e6-9a31-4520327f3a9b.png)

In the above, not sure that "const" and "false" are that useful here.

![screen shot 2016-10-27 at 1 12 41 pm](https://cloud.githubusercontent.com/assets/5479/19765140/1da99064-9c47-11e6-81f9-bacd1046d9ab.png)

In the above, "AboutDialog" probably isn't what I want.

_Copied from original issue: flutter/flutter-intellij#386_

**Comment by devoncarew** [comment]
_From @lukechurch on October 27, 2016 11:13_

+1!

@danrubel I think this is the issue I was trying to show you before of code completion not behaving well on named params.

**Comment by bwilkerson** [comment]
We now take the type of the parameter into account when ranking suggestions, so this has probably been addressed to at least some extent.
