### ISSUE TITLE
tests/compiler/dart2js/kernel/visitor_test.dart is failing after the Kernel roll

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#27684]
Majority of failures are caused by mixin transformer trying to access VM only class `_InvocationMirror`.

**Comment by jensjoha** [comment]
That sounds to be my fault.
I did not consider dart2js when creating an _InvocationMirror.
Do we have other ways to create "Invocation" objects (for noSuchMethod)?

**Comment by sigmundch** [comment]
In dart2js we have an internal type that implements Invocation (JsInvocationMirror under sdk/_internal/js_runtime/lib/js_helper.dart), but it is not publicly exposed. One option here would be to add an external factory constructor to `Invocation` (like we do for List) and add code for it on dart2js and the vm patch files. If we so, it would be nice if we can make such constructor private.

I'm curious though - how is the super transformer using the `Invocation` objects? dart2js does poorly with noSuchMethod, so I want to make sure we can handle the output of the transformation without a problem.

**Comment by jensjoha** [comment]
For super property get, super property set and super method invocation:

If the target (lets say 'foo') cannot be found, noSuchMethod is called instead: (as dictated by the specs) either a proper noSuchMethod from the super (or supers super etc) saying cannot find 'foo', or if a non-proper noSuchMethod is found (e.g. one taking 0 arguments) Objects noSuchMethod saying cannot find 'noSuchMethod'.

In all cases it becomes a DirectMethodInvocation to the correct noSuchMethod, with a newly created _InvocationMirror as the argument. It is the last part that is wrong when doing dart2js...

**Comment by kmillikin** [comment]
We will add an external factory constructor (or a top-level function, whichever makes most sense) as @sigmundch suggests, and provide separate VM and dart2js implementations in the patch files.

It will be easier to do that once we've moved everything into the SDK, so we'll wait for that.  We expect that to be a matter of weeks and hopefully only one.

**Comment by jensjoha** [comment]
A few notes so we don't forget:

- noSuchMethod shouldn't be called on these tests so this particular bug shouldn't be triggered here.
(For some reason it cannot find "setRange" on a class "NativeTypedArray+ListMixin+FixedLengthListMixin#1").

- Once we get this fixed, we should create baseline tests that actually *should* trigger this.
