### ISSUE TITLE
De-dupe 4+ copies of _JenkinsSmiHash

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27698]
Currently 6 copies. Even when we cleanup dev_compiler, there will be 4.

We could add this to `dart:math` or `dart:collection` – per https://github.com/dart-lang/sdk/issues/11617

Otherwise, `dart:_internal` would be nice at least to cleanup the SDK versions.

``` bash
> git grep -A 1 'class _JenkinsSmiHash' -- *.dart
pkg/dev_compiler/tool/input_sdk/lib/html/dart2js/html_dart2js.dart:class _JenkinsSmiHash {
pkg/dev_compiler/tool/input_sdk/lib/html/dart2js/html_dart2js.dart-  // TODO(11617): This class should be optimized and standardized elsewhere.
--
pkg/dev_compiler/tool/input_sdk/lib/math/jenkins_smi_hash.dart:class _JenkinsSmiHash {
pkg/dev_compiler/tool/input_sdk/lib/math/jenkins_smi_hash.dart-  // TODO(11617): This class should be optimized and standardized elsewhere.
--
runtime/observatory/lib/object_graph.dart:class _JenkinsSmiHash {
runtime/observatory/lib/object_graph.dart-  static int combine(int hash, int value) {
--
sdk/lib/html/dart2js/html_dart2js.dart:class _JenkinsSmiHash {
sdk/lib/html/dart2js/html_dart2js.dart-  // TODO(11617): This class should be optimized and standardized elsewhere.
--
sdk/lib/html/dartium/html_dartium.dart:class _JenkinsSmiHash {
sdk/lib/html/dartium/html_dartium.dart-  // TODO(11617): This class should be optimized and standardized elsewhere.
--
sdk/lib/math/jenkins_smi_hash.dart:class _JenkinsSmiHash {
sdk/lib/math/jenkins_smi_hash.dart-  // TODO(11617): This class should be optimized and standardized elsewhere.
```

**Comment by lrhn** [comment]
Moving the class to `dart:_internal` works for everything except `observatory/lib/object_graph.dart` which is not considered an internal library so it can't see `dart:_internal`.

**Comment by bwilkerson** [comment]
There is also an implementation in the analyzer package.

**Comment by lrhn** [comment]
Unless we make the implementation public (e.g., in `dart:collection`) then we can't share the implementation with packages (or the observatory code for that matter).

**Comment by bwilkerson** [comment]
True. That's why I think we should make the implementation public. It's useful for code outside the SDK and it's inefficient to require everyone to have a separate copy.

**Comment by lrhn** [comment]
But then I might want to design the API a little better. Not having a class with static functions is a good start (that's against the style guide).

Maybe make a `Hash` *class* so `jenkinsSmiHash` is an instance of that, and you can easily replace your hash implementation by using another object, instead of just relying on static functions. Something that generalizes to other hash algorithms.

Definitely more complicated than two functions that just gets the job done, but doesn't generalize at all.

**Comment by matanlurey** [comment]
Ping. This is a question I get asked a lot - and I have lots of packages that use `package:quiver` just for simple hash functions. Can we prioritize https://github.com/dart-lang/sdk/issues/11617? Heck, I'll write the PR, but would be nice to get this done.

**Comment by lrhn** [comment]
See https://dart-review.googlesource.com/c/sdk/+/73360

**Comment by kevmoo** [comment]
> See https://dart-review.googlesource.com/c/sdk/+/73360

🎵  I'm so excited...and I just can't hide it! 🎵

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sdk/commit/9f3b7cf4c6418ad35dc5b2e63a2f50c8aba5cbc7

**Comment by kevmoo** [comment]
Close to landing: https://dart-review.googlesource.com/c/sdk/+/214126

**Comment by kevmoo** [comment]
Another one coming: https://dart-review.googlesource.com/c/sdk/+/214181

**Comment by kevmoo** [comment]
Almost 5 years later!
