### ISSUE TITLE
Interop: Allow me to mark a member as JS-only

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27694]
Sometimes my needs for a JS API don't match up perfectly with my needs for a Dart API, and I'd like a way to control the shape of my JS API without negatively affecting the Dart API. A way to indicate that a member is only intended for use in JS would go a long way towards making this possible.

I propose that we add an annotation to `package:js`, perhaps `@jsOnly`, to indicate this. The analyzer and dev compiler would error if a JS-only member was used in Dart, and it would be an error to annotate an override method as JS-only. It would probably be fine if they were accessible via dynamic dispatch or mirrors, though. Dartdoc also wouldn't emit documentation for JS-only methods.

**Comment by bwilkerson** [comment]
@jacob314

**Comment by srawlins** [comment]
CC @srujzs in case you've encountered this recently.

An old issue but maybe still valid.

**Comment by bwilkerson** [comment]
@dcharkes Is this useful for the future of interop, or is this now obsolete?

**Comment by srujzs** [comment]
@nex3 Not sure if this is still desired, especially with extension types. I'm a little confused on the request either way - maybe an example could help me understand? Why not just not declare the interop member if you don't ever want it to be used?

**Comment by nex3** [comment]
The existence of `@internal` should be sufficient for me here.
