### ISSUE TITLE
`..` operator shall support `[]=` operator

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#27697]
Would be nice if `..` operator supports `[]=` operator. Then once can write some expressions concisely.

``` dart
Map toModelMap() => toMap()..['key'] = 'value';
```

instead of

``` dart
Map toModelMap() {
    Map map = toMap();
    map['key'] = 'value'
    return map;
 }
```

The use case is similar to the one mentioned in the issue https://github.com/dart-lang/sdk/issues/27696.

**Comment by lrhn** [comment]
Cascades do support indexed assignments. I use it like `new List(3)..[0] = v1..[1] = v2..[2] = v3`.

Hmm. There does seem to be a problem with dart2js, though. It currently doesn't work in Dartpad.
See: https://dartpad.dartlang.org/f25d40b81b7ab0d4e6bdb5d6ba19ba73

**Comment by lrhn** [comment]
Seems the problem isn't the cascades, it's only *printing* `new List()` that fails (calling `toString` works, so it's a problem with the print of dartPad, so lowering priority).
