### ISSUE TITLE
`add` method for `Map`

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#27696]
`Map` doesn't have `add(key, value)` method. It has `addAll(Map)` though. I can understand that generally `add(key, value)` is redundant because one can use `[]=` operator.

But i hit this use case very often:

``` dart
Map toModelMap() {
    Map map = toMap();
    map['key'] = 'value'
    return map;
 }
```

With `add(key, value)`, this can be concisely written as:

``` dart
Map toModelMap() => toMap()..add('key', 'value');
```

Right now, this can be written as:

``` dart
Map toModelMap() => toMap()..addAll({'key': 'value'});
```

But creates an unnecessary Map object and also is more verbose.

**Comment by zoechi** [comment]
`..[x]=y` works fine https://dartpad.dartlang.org/08c842de8fae2831a6a13050f82e3707

**Comment by anders-sandholm** [comment]
@zoechi thanks for checking and for the dartpad link.
