### ISSUE TITLE
Analyzer incorrectly issues "unused" warning on variables being used by ??=

### ISSUE THREAD

**Issue by martin88l** [dart-lang/sdk#27705]
The following has an unused warning on the variable _a:
import 'dart:async';
class A {
  var _a;
  
  void doSomething() {
    _a ??= new Future(() => _a = null);
  }
}

However, _a is used with ??= so that we don't create multiple futures doing the same work.

**Comment by pq** [comment]
This looks fixed to me (maybe in https://github.com/dart-lang/sdk/commit/6c7eeb2697d2a84ec68a501f4939c935d8e8abca?).  (I can no longer reproduce.)
