### ISSUE TITLE
One hour error in DateTime substraction for specific date

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27712]
co19 tests 
co19/LibTest/core/DateTime/add_A01_t02 
co19/LibTest/core/DateTime/subtract_A01_t02
fail because of this issue.

```dart
main() {
  DateTime dt = new DateTime(2002, 2, 3, 4, 5, 6, 7);
  print(dt);
  dt = dt.add(new Duration(days: -31, hours: 0, minutes: 0, seconds: 0, milliseconds: 0));
  print(dt);
}
```
This code produces the following output:

> 2002-02-03 04:05:06.007
> 2002-01-03 05:05:06.007

The same result is also observed for the following code:

```dart
main() {
  DateTime dt = new DateTime(2002, 2, 3, 4, 5, 6, 7);
  print(dt);
  dt = dt.subtract(new Duration(days: 31, hours: 0, minutes: 0, seconds: 0, milliseconds: 0));
  print(dt);
}
```
Date is correct, but time is shifted by one hour. There is no DST in my timezone, falling on subtracted time.

Tested on Dart VM version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"
Timezone on my machine is (UTC+07:00) Barnaul, Gorno-Altaysk

**Comment by whesse** [comment]
Daylight savings time was observed in 2002 in Russia, and the Windows time routines (and Dart) give exact date-time calculations for dates close to the present year (I think from 1970 onward).  Only for distant dates do they rely on extrapolating the current DST and time zone rules.  According to Wikipedia, the history for Russia is:
Observed DST in 1917-1919 and 1921 (some areas), 1981-2010. 2011-2014, used permanent DST. In 2014, left permanent DST and switched to permanent standard time.[6]

There has been a recent windows update, that introduced your time zone.
Trying the calculation in the similar time zones, on my Windows 7 machine, doesn't give the result you show, but it does not have your recent update.
Try the same calculation in other products, like Excel, and see if you get the same result.

**Comment by whesse** [comment]
I would suggest changing the test to one that uses a range only in the summer, or only in winter, to avoid hitting this issue.

**Comment by sgrekhov** [comment]
co19 issue created and fixed
https://github.com/dart-lang/co19/issues/82
