### ISSUE TITLE
Weird file being generated

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#27713]
I tried DDC with `bazelify` 

```
 (master) $ bazelify serve
Building server via bazel...

WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
____Loading package: 
____Loading...
____Found 1 target...
____Building...
____[3 / 10] Compiling @build//:build with ddc
ERROR: /home/zoechi/.cache/bazel/_bazel_zoechi/3e443aaa6a6cf1824cc4980f306f0a94/external/dart_style/BUILD:25:1: Summarizing Dart library @dart_style//:dart_style (strong mode) failed: Worker process sent response with exit code: 15..
FileSystemException(path=external/dart_style/lib/src/._error_listener.dart; message=Failed to decode data using encoding 'utf-8')
```

Before I run `bazelify serve` I purged the `~/.pub-cache/hosted/pub.dartlang.org` directory and the `.pub` directory and then run 
```
pub upgrade
bazelify
```

(I had to change the `BUILD` file a bit because I didn't have an `web/index.html` but instead a `web/dashboard_layout_demo.html` which was not properly recognized everywhere.)

I don't know where this file comes from. It's not in the `dart_style` repo. Might have existed at the uploader of the `dart_style` package, therefore the dart_style repo might be the right place to file the issue but perhaps DDC shouldn't fail at such a file anyway:

![image](https://cloud.githubusercontent.com/assets/405837/19888488/33c9c6f2-a02f-11e6-8348-0594d03e6076.png)

> Dart VM version: 1.21.0-edge.a850b4c977a5b177abe17864006657111d835840 (Mon Oct 31 18:04:44 2016) on "linux_x64"

**Comment by anders-sandholm** [comment]
@kevmoo

**Comment by jmesserly** [comment]
is there a way of triaging bazelify/build issues? this does not look related to DDC itself.

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/bazel#68
