### ISSUE TITLE
We should consider a hint/lint for unnecessary type annotations

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#27718]
As we clean up libraries for strong mode I'm seeing some cargo-cult type annotations getting added because the code matches some pattern where it looked like a type annotation was necessary. The result is a littering of type annotations that would get inferred anyway which makes the code noisier and gives a bad impression of how much manual work needs to be done to satisfy strong mode.

If we have a hint where types could otherwise be inferred on things like method calls, ctors, collection literals then we could cut back on some of this.

It might be hard to set a balance on what level of explicit types we want to allow for style reasons.

**Comment by leafpetersen** [comment]
Yes, this would be nice.  I've also thought that it might be nice to have a tool (maybe part of an intern project) that would eliminate these.  Kind of a dart format for the types.

**Comment by srawlins** [comment]
The think the lint request, https://github.com/dart-lang/linter/issues/1634, is a good request for this.
