### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by frank-rollpin** [dart-lang/sdk#27710]
Win 10, Dart SDK 1.20.1

@anonymous
@JS()
class GuiEvent {
  external set edges(List v);
  external set event(Event v);
  external set nodes(List v);
  external set pointer(Object v);

  external List get edges;
  external Event get event;
  external List get nodes;
  external Object get pointer;

  String type;
}

The compiler crashed when compiling this element.
class GuiEvent {

Stack trace:

Build error:
Transform Dart2JS on xamgle|web/datagrok.dart threw error: RangeError (index): Invalid value: Valid value range is empty: 0
dart:core                                                           List.[]
package:compiler_unsupported/src/ssa/optimize.dart 2245             SsaLoadElimination.visitCreate.<fn>
package:compiler_unsupported/src/elements/common.dart 382           ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField.fieldFilter
package:compiler_unsupported/src/elements/common.dart 350           ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember.<fn>
package:compiler_unsupported/src/util/link_implementation.dart 120  LinkEntry.forEach
package:compiler_unsupported/src/elements/modelx.dart 2765          ClassElementX.forEachLocalMember
package:compiler_unsupported/src/elements/common.dart 350           ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember
package:compiler_unsupported/src/elements/common.dart 386           ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField
package:compiler_unsupported/src/ssa/optimize.dart 2242             SsaLoadElimination.visitCreate
package:compiler_unsupported/src/ssa/nodes.dart 1530                HCreate.accept
package:compiler_unsupported/src/ssa/optimize.dart 2214             SsaLoadElimination.visitBasicBlock
package:compiler_unsupported/src/ssa/optimize.dart 2173             SsaLoadElimination.visitGraph
package:compiler_unsupported/src/ssa/optimize.dart 47               SsaOptimizerTask.optimize.runPhase.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/ssa/optimize.dart 47               SsaOptimizerTask.optimize.runPhase
dart:core                                                           List.forEach
package:compiler_unsupported/src/ssa/optimize.dart 91               SsaOptimizerTask.optimize.<fn>
package:compiler_unsupported/src/common/tasks.dart 63               CompilerTask.measure
package:compiler_unsupported/src/ssa/optimize.dart 57               SsaOptimizerTask.optimize
package:compiler_unsupported/src/ssa/ssa.dart 41                    SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 1654       JavaScriptBackend.codegen
package:compiler_unsupported/src/compiler.dart 972                  Compiler.codegen
package:compiler_unsupported/src/common/codegen.dart 242            CodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 840                  Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 839                  Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 836                  Compiler.emptyQueue.<fn>.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1640                 CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 834                  Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/enqueue.dart 842                   QueueFilter.processWorkItem
package:compiler_unsupported/src/js_backend/enqueuer.dart 589       CodegenEnqueuer.forEach
package:compiler_unsupported/src/compiler.dart 833                  Compiler.emptyQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 832                  Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 873                  Compiler.processQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 846                  Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 754                  Compiler.compileLoadedLibraries.<fn>
package:compiler_unsupported/src/common/tasks.dart 176              CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 648                  Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 558                  Compiler.runInternal.<fn>

**Comment by frank-rollpin** [comment]
I have figured out that one of the packages the app was using imported dart:io. Removing that dependency solved the issue.

**Comment by anders-sandholm** [comment]
While dart:io admittedly does not make much sense in the context of dart2js, I don't think dart2js should be crashing though.

**Comment by joshualitt** [comment]
I believe we fail more gracefully in this case now. Please reopen if this is still a problem.
