### ISSUE TITLE
SDK 1.20.1 has a regression in Code Completion in WebStorm

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/sdk#27721]
for more details please see https://intellij-support.jetbrains.com/hc/requests/797430

If you are unable to view mentioned request, feel free to contact me. This is serious usability issue with the SDK.

Thank you,
Tomáš

**Comment by alexander-doroshko** [comment]
@anders-sandholm Code completion is powered by the Dart Analysis Server, I'm changing area to analyzer.

@tomas-rokos Your private conversation with JetBrains support is definitely not visible to others. Please write issue details / steps to reproduce right here.

**Comment by tomas-rokos** [comment]
[das_log.txt](https://github.com/dart-lang/sdk/files/572590/das_log.txt)

**Comment by b-strauss** [comment]
I use IntelliJ IDEA and I have the same problem. Dart analysis is horribly slow, barely unusable.

**Comment by anders-sandholm** [comment]
@mit-mit 
@bwilkerson

**Comment by bwilkerson** [comment]
@scheglov Can you take a look at this?

**Comment by scheglov** [comment]
I was not able to reproduce the problem.
When I import `part of myslenkar;` into the corresponding library with the code
```dart
library myslenkar;
import 'dart:html';
part 'test.dart';
```
...and I continue typing `Eleme`, I get completion with `Element` suggestion.

**Comment by b-strauss** [comment]
My issue is related to #25109, I use a forked version of flutter. If I exclude all flutter code and use a simple dummy dart file it works.

**Comment by tomas-rokos** [comment]
I also cannot easily reproduce it in small sample. It probably requires some larger project, also as I mentioned in my JetBrains support chat it works fine in declaring variable in the class context, but doesn't work in method context.

**Comment by bwilkerson** [comment]
I suspect that this has been addressed by now. If not, please reply and I'll re-open the issue.
