### ISSUE TITLE
(...)->void must be a subtype of (...)->dynamic.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27727]
Strong mode needs to allow functions that return `void` when a function that returns `dynamic` is expected.

Example use case:

``` dart
T run<T>(T f()) {
  print("running");
  var t = f();
  print("done running");
  return t;
}

void printRunning() { print("running"); }
run<dynamic>(printRunning);
```

Ideally, we would like to write `void` in the generic type (or infer it): #27504 

While this issue should stand on its own, it decreases the priority of #27504.

**Comment by leafpetersen** [comment]
@bwilkerson @jmesserly There's an analyzer and a DDC component to this, could you each take the respective parts?

**Comment by jmesserly** [comment]
Yeah I can take a shot at this. Shouldn't be too hard.

**Comment by dgrove** [comment]
I'll split this up into analyzer and DDC pieces.

**Comment by jmesserly** [comment]
thanks. I don't mind doing both BTW, it's probably pretty simple.

**Comment by leafpetersen** [comment]
Status: out for implementation.

**Comment by jmesserly** [comment]
Huh. I might be missing something but this seems to be implemented already in Analyzer strong mode.

**Comment by jmesserly** [comment]
DDC also appears to work already. I added an Analyzer and DDC test using the code example provided. Tentatively closing, let me know if there was something else we'd like to fix here.
