### ISSUE TITLE
generic_methods_generic_function_parameter_test.dart contains type errors.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27728]
The test `generic_methods_generic_function_parameter_test.dart` in b05f160352cf451a15fd408ded1a9a4c0c6e657a (and in many other commits) uses syntax-only support for generic methods in the vm based on the `--generic-method-syntax` option.

This feature is now being supported more widely, and this causes an issue to surface that may not have affected the vm: That test contains constructs which causes static type warnings in the analyzer (and in dart2js, btw) when enabling generic method support.

In particular, one issue is that it calls `bar<int>(1, 2, 3)` in a context where the type of the first argument of `bar` is `T`, which is a type argument of the enclosing class, and there is no justification for typing `1` as a `T`.

In order to work with other tools as we implement the feature behind `--generic-method-syntax` everywhere and enable it by default, this test should be adjusted to eliminate the static type warnings. I assume this would be possible without destroying the ability of this test to serve its original purpose for the vm. A good check on the type correctness is that it passes the dartanalyzer type checks with the following options:
```
analyzer:
  language:
    enableGenericMethods: true
```

**Comment by a-siva** [comment]
I changed the test case as follows:
class C<T extends num> {
  bar<V extends num>(T t, int u, V v) => t + u + v;
  foo<U extends num>(bar<V>(T t, U u, V v)) => bar<int>(1, 2, 3);
}

main() {
  var c = new C<int>();
  Expect.equals(6, c.foo<int>(c.bar));
}

I still see warnings from the analyzer :+1: 
Analyzing [tests/language/generic_methods_generic_function_parameter_test.dart]...
[warning] The argument type 'int' can't be assigned to the parameter type 'T'. (/usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/language/generic_methods_generic_function_parameter_test.dart, line 11, col 57)
[warning] The argument type 'int' can't be assigned to the parameter type 'U'. (/usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/language/generic_methods_generic_function_parameter_test.dart, line 11, col 60)
2 warnings found.

What is wrong now?

**Comment by eernstg** [comment]
In the body of `foo`, `bar` has type `<V>(T, U, V) -> dynamic`, so `1` should be assignable to `T`. But `T` could be `double` to which `int` isn't assignable, so the type checker is forced to reject it; similarly for `2`. We could use `1 as num, 2 as num` to make the invocation typable, but that introduces a hint (I don't know if that will disrupt anything).

Otherwise we can do this:
```dart
class C<T extends num> {
  num n = 1;
  bar<V extends num>(T t, int u, V v) => t + u + v;
  foo<U extends num>(bar<V>(T t, U u, V v)) => bar<int>(n, n, 3);
}

main() {
  var c = new C<int>();
  print(6 == c.foo<int>(c.bar));
}
```
