### ISSUE TITLE
Several testson DBC failing a IsRegister() assertion

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#27731]
FAILED: none-vm debug_simdbc64 language/null_test/none
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/locations.h: 241: error: expected: IsRegister()

FAILED: none-vm release_simdbc64 corelib/list_unmodifiable_test
FAILED: none-vm release_simdbc64 lib/mirrors/hierarchy_invariants_test
FAILED: none-vm release_simdbc64 lib/mirrors/mirrors_reader_test

**Comment by fsc8000** [comment]
I'm looking at this failure: It seems that constants introduced by inlining get:runtimeType cause the crash.
