### ISSUE TITLE
dummy_compiler_test is erroneous

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#27744]
Due to import of 'package:kernel' in dart2js, utils/dummy_compiler_test and utils/recursive_import_test are trying to compile a program with compile-time errors. 

This might be the underlying reason for why Dartium now fails on these.

**Comment by johnniwinther** [comment]
This might be related to #27441

**Comment by sigmundch** [comment]
it seems that we are importing 'package:kernel/kernel.dart' in one place, but we might be able to import directly 'package:kernel/ast.dart' instead and get rid of the transitive link to dart:io. 

I have a fix out for review here: https://codereview.chromium.org/2485093003/
