### ISSUE TITLE
Dartium: array reduce does not respect `initialValue` argument in JS interop

### ISSUE THREAD

**Issue by uberolerass** [dart-lang/sdk#27741]
This problem only seems to manifest itself in a dev context where:

1) Dartium is running in Dart mode
2) The `reduce` function is called in JS on an array which was passed down through JS interop (the `js` package)

In this case the function prototype does not have [the `initialValue` parameter ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) and any JS code that relies on it will fail.

Concrete example: [the fuzzy library](https://github.com/mattyork/fuzzy/blob/master/lib/fuzzy.js) has a `filter` function that takes in an array. It uses `.reduce` on line 115-130 and passes `[]` as the initial value. Calling the function through a facade generated by `js_facade_gen` will fail when Dartium is serving Dart content. It works fine in compiled mode on all browser I tested, however, including Dartium.

**Comment by anders-sandholm** [comment]
@uberolerass just wondering if this work fine with dart2js?

Not clear if this is a Dartium or dart:js issue - feel free to re-assign.

**Comment by uberolerass** [comment]
@anders-sandholm sorry, my description was not clear enough. It works perfectly when the code is compiled to JS in all browsers I tested (Dartium, Firefox, Chrome, Safari). The issue only appears when running the _Dart_ version in Dartium. But since this is what we do most of the time when developing it's a big issue since it basically means that any JS library that we interop with that relies on the `initialValue` arg of the `reduce` function doesn't work in development.

**Comment by anders-sandholm** [comment]
OK. Thanks for the clarification. 

I see that @jacob314 self-assigned this. He is our resident js-interop expert, so @uberolerass you should be in good hands now.

**Comment by uberolerass** [comment]
Awesome! Thanks guys. FYI we're using Dart 1.20.1 together with Chromium (Dartium) 45.0.2454.104 (64-bit).
