### ISSUE TITLE
Windows Dart.exe causes warning popup about dart file not being executable.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27749]
When I run a freshly compiled dart.exe (Win7 x64, VS 2015), on a freshly created dart file, I get a warning popup:
<img width="342" alt="unexe" src="https://cloud.githubusercontent.com/assets/4865287/19977268/5259b4cc-a1f3-11e6-9a61-1deda0c483c1.png">
It's caused by the `LoadLibraryW` call in `Extensions::LoadExtensionLibrary` which is called during startup to attempt to load a compiled snapshot.
```
main > ReadAppSnapshot > ReadAppSnapshotDynamicLibrary > Extensions::LoadExtensionLibrary
```

It's annoying, but likely harmless, and when I continue the code runs as expected.

Is this something that the Dart application can avoid (or should I try to disable something in Windows)?

**Comment by johnmccutchan** [comment]
@rmacnak-google FYI

**Comment by lrhn** [comment]
Seems fixed to me. Thanks!
