### ISSUE TITLE
Add kernel linux builder to waterfall, remove kernel-rasta builders from internal waterfall

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27743]
The repository of the kernel recipe dart-kernel will need to change.

@mkustermann

**Comment by mkustermann** [comment]
@whesse  Maybe we could make a new 'kernel' category to make the existing vm category not bigger than it is already.

**Comment by mkustermann** [comment]
I'll take care of this now!

**Comment by whesse** [comment]
Thanks

**Comment by mkustermann** [comment]
This should be done now. We've added debug/release for JIT and precompilation.
