### ISSUE TITLE
StreamSubscription.pause resumption docs unclear

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27756]
It's not clear what should happen if you pass a Future to StreamSubscription.pause and _also_ call StreamSubscription.resume. Does doing one mean you shouldn't do the other?

**Comment by Hixie** [comment]
It seems that _StreamIterator.moveNext assumes that you can call resume() without first calling pause(), so presumably that means the StreamSubscription protocol is that you ignore resume() calls when they would bring the count negative.

**Comment by lrhn** [comment]
That is correct. Calling `pause` increments a pause counter and pauses if the counter was zero, `resume` decrements it if the pause count is positive and resumes when it hits zero. The future is just used as `future.whenComplete(this.resume)`, nothing fancy.

I think the `pause(future)` feature was too speculative. I have never needed it, or seen it used.
