### ISSUE TITLE
no type error when one side of a conditional expression is the wrong type

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#27753]
In DartPad, there is no type error for this code, even in strong mode:

```dart
main() {
  String x1 = "x" == 3 ? true : "hello";
  String x2 = "x" == 3 ? "hi" : true;
  print(x1);
  print(x2);
}
```

It seems like it should be an error to assign a boolean to a string.

**Comment by a14n** [comment]
I think it's because of implicit casts. `"x" == 3 ? true : "hello"` has type `Object` that can be cast to `String`.

It's reported as error with :

```
analyzer:
  strong-mode:
    implicit-casts: false
```

```
ERROR: A value of type 'Object' cannot be assigned to a variable of type 'String' (test.dart:2)
ERROR: A value of type 'Object' cannot be assigned to a variable of type 'String' (test.dart:3)
```

**Comment by lrhn** [comment]
This is indeed an unfavorable interaction between finding the least upper bound of the conditional expression branches to be `Object` and implicit down-casts allowing `Object` to be assigned to anything.
It is working as the specification says it should.
I hope we'll eventually be able to do better.

**Comment by skybrian** [comment]
That's unfortunate. I wonder if we should handle this as a special case in strong mode?

**Comment by jmesserly** [comment]
@skybrian Indeed! That's covered by https://github.com/dart-lang/sdk/issues/25368

**Comment by skybrian** [comment]
Okay, I guess this one is a dup then.
