### ISSUE TITLE
Not seemingly possible to tell the system/analyzer "subclasses must be immutable"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#27750]
Flutter widgets should be immutable, for both Stateless and Stateful widgets. We don't seem to have a way to tell the system/analyzer that "all subclasses of StatelessWidget and StatefulWidget should be immutable. Please complain if they aren't."

Strawman:

* `@immutable` annotation for class hierarchies that must be immutable
* lint/hint to warn/complain if a non-final field was added to a subclass whose parent is marked with @immutable

Thanks!

**Comment by bwilkerson** [comment]
This came up in a different context earlier. Here's what I had spec'd out:
```
/// Used to annotate a class `C`. Indicates that `C` and all subtypes of `C`
/// must be immutable.
///
/// A class is immutable if all of the instance fields of the class, whether
/// defined directly or inherited, are `final`.
///
/// Tools, such as the analyzer, can provide feedback if
/// * the annotation is associated with anything other than a class, or
/// * a class that has this annotation or extends, implements or mixes in a
///   class that has this annotation is not immutable.
const _Immutable immutable = const _Immutable();
```

If I recall correctly, the reason it hasn't already made it into the meta package is because I hadn't gotten any confirmation that the definition of 'immutable' that I included above was what was being asked for. If you can confirm that this is the correct definition, then I'll put together the CL to add the annotation (with a lint to follow).

**Comment by sethladd** [comment]
> A class is immutable if all of the instance fields of the class, whether defined directly or inherited, are `final`.

That's an excellent place to start. :)

Thank you!

cc @hixie

**Comment by Hixie** [comment]
Yeah, just not allowing non-final fields would be a vast improvement over today's status and would prevent most problems.

Ideally, @immutable would take a string argument that was displayed as part of the error message, so that we could annotate `Widget` with a pointer to documentation about how to build widgets specifically.

(Long term we'd love to get deep immutability, but that would be gated on things like immutable List, Map, and Set literals.)

**Comment by bwilkerson** [comment]
The annotation is now available in meta (https://codereview.chromium.org/2476673004/). Hints to follow.

**Comment by sethladd** [comment]
Thanks!!

**Comment by sethladd** [comment]
Once the analyzer can provide hints for this annotation, please ping https://github.com/flutter/flutter/issues/6892 and we'll give it a whirl. Thanks!

**Comment by sethladd** [comment]
Hi! Any luck on making the analyzer report if something marked with @immutable isn't actually immutable? We'd like to start using this in examples and our code. Thanks!

**Comment by bwilkerson** [comment]
I would love to do it right now, but as with everything (sigh), it's a matter of priorities. Right now I'm trying to get 1.23 critical work done. How urgent is this? (And when will be become urgent?)

And, of course, contributions are always welcome. :-)

**Comment by sethladd** [comment]
Are analyzer plugins ready? Maybe we can do this ourselves, which would be cool to try.

Ideally, we'd have this in by mid-May, so users after that date begin their Flutter journey with @immutable on by default. But, we're not technically blocked on this. Just want to start off people on the right foot.

**Comment by bwilkerson** [comment]
> Are analyzer plugins ready?

No, not yet. I'm planning to get back to them after the 1.23 work. But even if they were, this kind of hint should be available to everyone, not just Flutter users. :-)

> Ideally, we'd have this in by mid-May ...

I'll try to remember to tackle it fairly soon after 1.23, but don't hesitate to ping me occasionally. The delay is not from lack of interest on my part, but could be from forgetfulness.

**Comment by bwilkerson** [comment]
It seemed easier to do it than to remember to return to it (and it was a fun diversion), so...

https://codereview.chromium.org/2775863004/

**Comment by kevmoo** [comment]
Closed in https://github.com/dart-lang/sdk/commit/4f28d97ac23605a280b6ad26d78d83655018af0f

**Comment by Hixie** [comment]
OMG! Fantastic, thanks!

**Comment by bwilkerson** [comment]
You're welcome. Let me know when you find bugs.

**Comment by sethladd** [comment]
Very cool, thank you!

Is this on track for 1.23 ?

**Comment by bwilkerson** [comment]
As far as I'm aware, we have not yet entered cherry pick for 1.23, so this should be included in the next full build.

**Comment by sethladd** [comment]
Awesome. I opened https://github.com/flutter/flutter/issues/6892 for us to try this, once a roll is done.

**Comment by sethladd** [comment]
cc @yjbanov
