### ISSUE TITLE
DDC should never fail when invoked with --help as the only command line argument

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#27752]
In https://github.com/dart-lang/sdk/blob/master/utils/dartdevc/BUILD.gn at the moment we have to pass:

```
--dart-sdk ../../sdk --dart-sdk-summary ../../pkg/dev_compiler/lib/sdk/ddc_sdk.sum --help
```

to create a snapshot with training data during the SDK build. The default values for the arguments seem to assume that the SDK is already there, but while building the SDK it won't be.

In any case, whether DDC is running in the intended environment or not, `--help` should just work.

/cc @vsmenon

**Comment by kevmoo** [comment]
DDC folks: `pkg/args command_runner` makes this trivially easy.

See https://www.dartdocs.org/documentation/args/0.13.6/command_runner/command_runner-library.html

**Comment by vsmenon** [comment]
Simple fix here:

https://codereview.chromium.org/2473143003/

**Comment by jmesserly** [comment]
@kevmoo -- DDC used to use command runner, but had to move away from it because we don't have any commands. I really liked it, though.
