### ISSUE TITLE
Analyzer FR: Detect when futures are not properly chained

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#27768]
Consider the following innocent looking code:

```Dart
Future<String> runSomeOp() {
  return someOp().then((_) {
    log("Finished!");
  });
}

// Much later in code

void someMethod() {
  runSomeOp().then((value) {
    print('Happily use $value');
  });
}
```

The intent here is to attach multiple callbacks to the same future, not to chain the futures. The correct code is one dot away:

```Dart
Future<String> runSomeOp() {
  return someOp()..then((_) {
    log("Finished!");
  });
}

// Much later in code

void someMethod() {
  runSomeOp().then((value) {
    print('Happily use $value');
  });
}
```

I was hoping Analyzer can catch cases like this because it knows the method is expected to return a Future<String> and the ```then``` block has no return statement.

**Comment by zoechi** [comment]
This might help http://dart-lang.github.io/linter/lints/unawaited_futures.html

**Comment by mehmetf** [comment]
It seems I need to get used to async/await then, thanks!

**Comment by zoechi** [comment]
it's not hard to get used to async/await :D

**Comment by lrhn** [comment]
The problem here is compounded by your function-without-a-return-statement because that still effectively returns `null` and `null` is assignable to `String`. That means that the program isn't doing anything visibly wrong.
