### ISSUE TITLE
VM with hot reload crashes on co19 test

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27773]
The test co19/LibTest/isolate/ReceivePort/take_A01_t02 crashes often on the reload bot and always on the reload-rollback bot. 
See https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-reload-be/builds/1133/steps/checked%20vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment]
@lrhn The crash only began after you landed https://github.com/dart-lang/sdk/commit/9ebef9af7c7086a4e0f935b3ebd29aa4e990da91

Please revert your CL and fix the issue.

**Comment by lrhn** [comment]
The CL works (it's a 3-line change to library code) and it didn't change internal VM code. The VM doesn't crash when running normally, so this looks more like a bug in the reload code that just happens to now be triggered by this test.
Or, in other words, it's not something I can fix.

**Comment by johnmccutchan** [comment]
@lrhn Actually you can address this failure:

```
runtime/vm/isolate.cc: 1783: error: Isolate did not reload before exiting and --check-reloaded is enabled.

Dumping native stack trace for thread 743a
  [0x000000000082b005] dart::Profiler::DumpStackTrace(bool)
  [0x000000000082b005] dart::Profiler::DumpStackTrace(bool)
  [0x00000000005be32d] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x00000000006fa415] dart::Isolate::Shutdown()
  [0x000000000062dde9] dart::Dart::ShutdownIsolate(dart::Isolate*)
  [0x00000000006f9df8] Unknown symbol
  [0x000000000071b97c] dart::MessageHandler::TaskCallback()
-- End of DumpStackTrace```

Your test spawns an isolate and then doesn't execute much code before exiting.

**Comment by fsc8000** [comment]
The assertion is too strict here, because it's perfectly fine to have an isolate that does not perform any work. I'd just remove the assert.

**Comment by johnmccutchan** [comment]
@fsc8000 The purpose of the assert is to make sure that the reload bots are actually reloading code. If we removed the assertion the bots might not actually do a reload and still pass.

**Comment by lrhn** [comment]
So the problem is that the test is fine, but it's not compatible with the reload-bot testing, so it should just be skipped for those bots?

**Comment by johnmccutchan** [comment]
@lrhn Skipped or invoke a bit more code before exiting an isolate.

**Comment by fsc8000** [comment]
Agree, skip it for the reload bots for now.

**Comment by johnmccutchan** [comment]
@fsc8000 just reminded me that this is a co19 test. I missed that part. Skipping is the best approach.
