### ISSUE TITLE
ddc loses constness of fromEnvironment constructors

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27784]
The following analyzes fine in strong mode:

```dart
const bool _foo = const bool.fromEnvironment("dart.foo");

void main() {
  print(_foo);
}
```

In DDC, it fails at compile time with:
```
[error] The constructor being called isn't a const constructor.
```

If I run with the `strong.sum` in the SDK (as opposed to DDC's own), DDC is able to compile.  It appears that when we patch and build the sdk and summary, we're losing the `const` for `fromEnvironment`.

**Comment by jmesserly** [comment]
it ends up busted in gen/patched_sdk `factory bool.fromEnvironment(String name, {bool defaultValue: false}) {` ... I think you just found the first ever bug in the patch_sdk script! :D

bumping because this affects all "external const" declarations in SDK

**Comment by jmesserly** [comment]
it could be something with the `external const factory` as those aren't actually valid in normal Dart code.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2503803004/
