### ISSUE TITLE
2.5x frame build performance difference between iPhone 6 and Nexus 5

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#27783]
Not sure if this gap is expected, but we see that iPhone 6 is 2.5x _faster_ than Nexus 5 at building frame data (should be mostly Dart code), with the iPhone 6 averaging at ~3.3ms/frame and the Nexus 5 averaging at ~8.0ms. This is visible in the `flutter_gallery__transition_perf` and `flutter_gallery_ios__transition_perf` benchmarks.

To reproduce in flutter/flutter:

```
> cd dev/devicelab
> dart bin/run.dart -t flutter_gallery__transition_perf
> dart bin/run.dart -t flutter_gallery_ios__transition_perf
```

The numbers will be saved to `examples/flutter_gallery/build/transitions.timeline_summary.json`.

@a-siva

**Comment by rmacnak-google** [comment]
This difference seems in line with the difference in "native" code performance.

Comparing a Nexus 4 with an iPod Touch 6th gen, I measure
iOS = 3.07x Android on the C version of DeltaBlue (from UW)
iOS = 4.32x Android on a C++ version of Richards (richards_deutsch_acc_virtual from Wolczko)
iOS = 2.99x Android on average_frame_build_time_millis for the Flutter gallery

@fsc8000

**Comment by yjbanov** [comment]
Thanks for the analysis!
