### ISSUE TITLE
ddc should handle fromEnvironment constructors at compile time

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27785]
If we compile the example in #27784, we get a runtime error:

```
/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1995
    throw obj;
    ^
Unsupported operation: bool.fromEnvironment can only be used as a const constructor
```

(Note, we normally compute and canonicalize constants at runtime.)

**Comment by jmesserly** [comment]
thanks for filing! I am already looking at this as part of 27784.

**Comment by jmesserly** [comment]
related https://github.com/dart-lang/sdk/issues/16846

**Comment by vsmenon** [comment]
Thanks!  I looked a little into this, but had to move to something else.

I was thinking we'd want to initialize `ConstantEvaluationEngine` with `context.declaredVariables` and use that to compute.

We'd need #27511 as well (everything would just be false/default until then)

**Comment by jmesserly** [comment]
Oh lovely, the behavior is undocumented and unspecified: https://github.com/dart-lang/site-www/issues/37

Think I've tracked it down by hunting old bugs and issues. Incidentally this is yet another thing where analyzer-cli has support and DDC doesn't (oh, just saw you noticed this as well) ... even better, it can't be parsed with the standard arg parser(!!) ... brilliant. I may be able to string this together without the (bigger) fix for #27511 ... will keep you posted.

**Comment by jmesserly** [comment]
oh and thanks for the note about ConstantEvaluationEngine, hadn't gotten there yet 👍

**Comment by jmesserly** [comment]
On AnalysisContext it's context.declaredVariables.define ... I think that should end up being used for constant evaluation if we set up the context correctly

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2503803004/
