### ISSUE TITLE
Checked in sdk is broken on MIPS

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#27798]
/home/rmacnak/dart1/sdk/tools/sdks/linux/dart-sdk/bin/dart-mips: relocation error: /home/rmacnak/dart1/sdk/tools/sdks/linux/dart-sdk/bin/dart-mips: symbol __gnu_compact_pr2, version CXXABI_1.3 not defined in file libstdc++.so.6 with link time reference

**Comment by rmacnak-google** [comment]
This prevents running the test suite. Copying a locally build VM on top of the checked in one works around the problem.

**Comment by whesse** [comment]
This looks like a dynamic library version mismatch problem.  What version of glibc and libstdc do you have?  What system are you running on?  We haven't rebuilt mips for a long time, so you are welcome to check in your built version, or send it to me.  Is it mipsle?

**Comment by rmacnak-google** [comment]
Debian 8.6, mipsel

gcc --version
gcc (Debian 4.9.2-10) 4.9.2

/sbin/ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6) => /usr/lib/mipsel-linux-gnu/libstdc++.so.6

/sbin/ldconfig -p | grep libc.so
	libc.so.6 (libc6, OS ABI: Linux 2.6.32) => /lib/mipsel-linux-gnu/libc.so.6

I didn't make note of the Debian version I had the last time this worked, but it's possible it stopped working for me due to an update.  Would a binary rebuilt against these newer libraries still be compatible with, say, the mips bots?

**Comment by whesse** [comment]
The ldd -v command will show you which versions of the libraries are needed by the dart executable, and which ones you have.  You can check both the checked-in executable and the one you built yourself.  You can also search the missing function name, to see when it was introduced (or discontinued).  The mips bots haven't run for a long time - I'll be building new ones from the toolkits used by our clients - two separate ones, and checking them on the hardware.

**Comment by whesse** [comment]
Mips support removed.  Closing bug.
