### ISSUE TITLE
Add typedef void VoidCallback(); to dart:core

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#27791]
Would it be possible to add the follow declaration to `dart:core`

```dart
typedef void VoidCallback();
```

I keep needing this typedef and it seems ugly to redeclare it in every package.

Thanks!

/cc @floitschG

**Comment by a14n** [comment]
The [func package](https://pub.dartlang.org/packages/func) already contains some predefined typedef. [VoidFunc0](https://github.com/dart-lang/func/blob/master/lib/func.dart#L20) in this case.

**Comment by abarth** [comment]
I guess I'm a weird duck in that I'm writing code that can't depend on packages.

**Comment by lrhn** [comment]
I'm guessing the reason the func package is discontinued is that the language has added syntax for expressing function types directly. You can now write `void Function()` anywhere you would write `VoidCallback` and get the same result, without any need to import or declare the type.

We don't plan to add function type aliases for simple types like this, we recommend just usig the function type syntax.

**Comment by Hixie** [comment]
:-(

`void Function()` does not make it clear that it is intentional that the type used in one place matches the type used in another. Also, it's less readable than `VoidCallback`.

**Comment by lrhn** [comment]
I tend to disagree about the readability. Reading `void Function()` tells me exactly what the function type is, where reading `VoidCallback` means I have to look up what it actually means - like how many arguments it accepts.

**Comment by Hixie** [comment]
Mostly it's less readable just because function signature literals are hard to read in general (they have multiple keywords, parentheses, etc) vs a single word. I agree that `VoidCallback` is less self-documenting (though that's not that much of a problem in practice since we expose our documentation aggressively).
