### ISSUE TITLE
Moving an enum from one file to another breaks hot reload

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27804]
I hugely refactored an application I'm writing, moving a number of classes and enums from one monolithic file to a half-dozen other files. One in particular was an enum "HouseOfRoovesPage" which moved from main.dart to common.dart. When I had no more analyzer warnings, I hot reloaded, and got:
```
I/flutter (32428): type 'HouseOfRoovesPage' is not a subtype of type 'HouseOfRoovesPage' of ':switch_expr' where
I/flutter (32428):   HouseOfRoovesPage is from
I/flutter (32428):   /data/user/0/com.yourcompany.houseOfRooves/cache/house-of-rooveswzcahx/lib/main.dart
I/flutter (32428):   HouseOfRoovesPage is from
I/flutter (32428):   /data/user/0/com.yourcompany.houseOfRooves/cache/house-of-rooveswzcahx/lib/common.dart
```

**Comment by mit-mit** [comment]
CC @johnmccutchan

**Comment by johnmccutchan** [comment]
This is working as intended. We cover the matching semantics in our talk. In Dart it is perfectly legal to have class X in libA and a different class X in libB. So during reload, we have no way of pairing the class X from libA with class X moved to libB. We would need some way for the programmer to specify their intention here.

**Comment by Hixie** [comment]
That's fine, but there's still a bug. The old type was entirely gone, as were all references to it. So it shouldn't have survived the hot reload in any way.

**Comment by johnmccutchan** [comment]
The old type is probably retained by instances of the old enum class

**Comment by Hixie** [comment]
The old type shouldn't have been able to be retained, since there was no way for the code to even refer to it. Is the problem maybe that if I change the type of a field, it doesn't consider that a removal/addition?

**Comment by johnmccutchan** [comment]
@Hixie do you have a small reproduction of this? I'd like to spend some time seeing what is going on inside the VM.

**Comment by Hixie** [comment]
Sure. Create an app with the following `main.dart` and an empty `test.dart`:

```dart
import 'package:flutter/widgets.dart';

import 'test.dart';

void main() {
  runApp(new MyHomePage());
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

enum TestEnum { a }

class _MyHomePageState extends State<MyHomePage> {
  TestEnum _value = TestEnum.a; // LINE A

  @override
  Widget build(BuildContext context) {
    switch (_value) {
      case TestEnum.a:
      case TestEnum.b:
        break;
    }
    return new Text('Hello.');
  }
}
```

Now, move the line marked `LINE A` to `test.dart` and hot reload.

I would expect the `_value` field to be considered removed and readded with a new type, and for everything to keep working. Instead I get:

```
I/flutter ( 6352): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6352): The following assertion was thrown building MyHomePage(dirty; state: _MyHomePageState(490012294)):
I/flutter ( 6352): type 'TestEnum' is not a subtype of type 'TestEnum' of ':switch_expr' where
I/flutter ( 6352):   TestEnum is from /data/user/0/com.yourcompany.b27804/cache/27804ckwsta/lib/main.dart
I/flutter ( 6352):   TestEnum is from /data/user/0/com.yourcompany.b27804/cache/27804ckwsta/lib/test.dart
I/flutter ( 6352):
I/flutter ( 6352):
I/flutter ( 6352): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6352): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6352): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6352):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6352):
I/flutter ( 6352): When the exception was thrown, this was the stack:
I/flutter ( 6352): #0      _MyHomePageState.build (/data/user/0/com.yourcompany.b27804/cache/27804ckwsta/lib/main.dart:19:13)
I/flutter ( 6352): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2869:23)
I/flutter ( 6352): #2      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2758:5)
I/flutter ( 6352): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1763:33)
I/flutter ( 6352): #4      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:313:20)
I/flutter ( 6352): #5      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:166:5)
I/flutter ( 6352): #6      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:648:15)
I/flutter ( 6352): #7      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:583:9)
I/flutter ( 6352): #8      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.reassembleApplication (package:flutter/src/rendering/binding.dart:232:5)
I/flutter ( 6352): #9      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.reassembleApplication (package:flutter/src/widgets/binding.dart:362:32)
I/flutter ( 6352): #10     BindingBase.registerSignalServiceExtension.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/foundation/binding.dart:146:17)
I/flutter ( 6352): (elided 3 frames from package dart:async)
I/flutter ( 6352): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by johnmccutchan** [comment]
@Hixie Should LINE A actually be moved up to the enum definition?

**Comment by Hixie** [comment]
Uh, yeah, sorry, I'm an idiot. Fixed the snippet.

**Comment by johnmccutchan** [comment]
Thanks. This does seem like something we should handle better. @turnidge thoughts?

**Comment by FMorschel** [comment]
Maybe related to https://github.com/dart-lang/sdk/issues/56583. Hot reloading (no change to enum) makes the VM crash. There are some commits to it.

**Comment by FMorschel** [comment]
Only now have I noticed this is an old issue. Sorry, could this be closed then?

**Comment by rmacnak-google** [comment]
The old value of TestEnum.a persists across reload in the instance of _MyHomePageState. Because hot reload does not receive structured edits, only the old and new program, it sees the removal of TestEnum from the main library and the addition of TestEnum to the other library as unrelated and does not forward main.TestEnum.a to lib.TestEnum.a.

With the introduction of static typing, type safety requires this to fail sooner (a8b3773054c283ac9057522c491a1f9f7a4fe68e), and this will now fail a type check when loading _MyHomePageState._value.
