### ISSUE TITLE
Deleted enum value instances need to become a per enum class deleted sentinel after a hot reload

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27802]
Deleted enum value instances could sometimes be retained in the heap as canonical objects after a hot reload but these instances are not in the canonical constants list of the class leading to assertions if we do a strict check of all canonical objects. These enum instances are also in a weird state as their indexes are not valid. It would be more consistent to have all these instances become a per enum class deleted sentinel object.

Test case failure : run_vm_tests - IsolateReload_EnumDelete

**Comment by rmacnak-google** [comment]
Another possibility is to clear the canonical bit on deleted enum values.

**Comment by johnmccutchan** [comment]
@rmacnak-google Yes, Siva and I discussed that option too. Our current thinking is that by making it obvious when we are dealing with a deleted enum value it will save us debugging hassle in the future.
