### ISSUE TITLE
Implement (...)->void must be a subtype of (...)->dynamic in Analyzer

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#27808]
Analyzer implementation of #27727 .

**Comment by dgrove** [comment]
@jmesserly can you give an update here?

**Comment by jmesserly** [comment]
yeah I started a CL for this, but have gotten a few P1 interrupts. Chatted w/ @dgrove sounds like we want this in say, the next month. Totally doable IMO.

**Comment by jmesserly** [comment]
tagging as strong mode per the original bug

**Comment by jmesserly** [comment]
well, it seems to work already: https://codereview.chromium.org/2520043002/

we check top (and bottom) before void in the subtype relation, so this is the behavior I'd expect.
