### ISSUE TITLE
Analyzer no longer infers type of final class fields

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#27805]
In SDK 1.19.1 and several previous minor versions the type of final class fields was inferred. Here's an example from Webstorm, issue is the same in Dartpad:

![screen shot 2016-11-11 at 09 59 42](https://cloud.githubusercontent.com/assets/6475621/20209950/63cc2d5c-a7f7-11e6-859d-7f27a03c0fba.png)

This is no longer the case in SDK 1.20.1 or 1.21.0-dev.5.0:

![screen shot 2016-11-11 at 10 01 10](https://cloud.githubusercontent.com/assets/6475621/20209957/6e7c8cd8-a7f7-11e6-8daa-ae4418282a10.png)

Needless to say this is quite annoying if you have a large codebase relying on this inference.

**Comment by bwilkerson** [comment]
@jmesserly Was this intentional, or is this a bug we need to look into?

**Comment by alexeieleusis** [comment]
This makes me so sad, I even wrote a linter rule...
As a user of the SDK I think this is a bug.

**Comment by alexeieleusis** [comment]
The workaround is to add the type annotation?

**Comment by leafpetersen** [comment]
This is definitely a bug, though I'm not sure where.  The command line analyzer is definitely inferring a type for that field as of 1.21.0-dev.1.0  - I just tested it.

I also just tried this code in Intellij 2016.2.5 with the same Dart version, and I get completions for all of the expected methods (substring, etc).

I also just tried this code in DartPad, and I also see the completions.

Are you quite sure that you have strong mode turned on?

**Comment by leafpetersen** [comment]
I updated to 1.21.0-dev.5.0, and I still see no issue.  Here's a screenshot from Intelij 2016.2.5 EAP on MacOS running the 1.21.0-dev.5.0 64 bit showing both the correct completions and an error where I assigned `hest` to a variable of type `String`, which would not show up if inference was not happening:

<img width="882" alt="screen shot 2016-11-11 at 9 27 51 am" src="https://cloud.githubusercontent.com/assets/8484504/20224028/3e267e96-a7f1-11e6-8ccd-14a027eb193c.png">

**Comment by lassedamgaard** [comment]
@leafpetersen No I definitely do not have strong mode turned on. Is that required for this to work? If so that requirement was introduced in 1.20

**Comment by bwilkerson** [comment]
Ah, right. I do vaguely remember now that we changed that behavior. We effectively had two implementations and they were not being kept consistent, so we decided to remove the non-strong-mode implementation. We strongly recommend that folks switch over to using strong mode; it brings a lot of benefits.

**Comment by lassedamgaard** [comment]
OK, I hadn't planned on enabling strong mode yet but it probably makes sense. Regardless of whether this one is fixed or not, it would be awesome if the differences in analyzer capabilities in strong mode vs "weak" (?) mode were documented somewhere, at least for the stuff that doesn't obviously depend on strong mode such as this.
