### ISSUE TITLE
support assert in initializer list

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27809]
Main issue: https://github.com/dart-lang/sdk/issues/27141
Analyzer change was here: https://codereview.chromium.org/2492633002/

it looks like we need to support the AssertInitializer node.

**Comment by munificent** [comment]
This is not a 1.50 feature, so kicking out of the milestone. (I think we accidentally got it confused with assert *messages*, which are in 1.50).

**Comment by jmesserly** [comment]
yeah. fwiw it's probably super easy to implement tho

**Comment by bwilkerson** [comment]
For analyzer it would just be a matter of removing the flag and enabling it by default.

**Comment by munificent** [comment]
Yeah, but it's not clear if this is a feature we actually want to commit to. The request is from Flutter and, last I heard, we aren't sure if they are still even interested in it. I don't want to push it forward unless we on the team think it's important and/or a customer really cares about it.

**Comment by jmesserly** [comment]
it's kind of useful for const objects. There's no other way to add invariant checks for them. That said one can usually just avoid const.

**Comment by lrhn** [comment]
The checks you can do on const objects is also limited to what can be checked by a potentially const expression, which can be quite limiting.

**Comment by munificent** [comment]
> There's no other way to add invariant checks for them.

The workaround I've seen is to lazily check the invariant in the properties and methods on the object when it's used. That delays the error, which is a drag, but const is kind of a drag many times.

You're right that the feature is definitely potentially useful. It's just not clear if it's useful *enough*.

**Comment by jmesserly** [comment]
I may pick this up as part of https://github.com/dart-lang/sdk/issues/29346

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/37866
