### ISSUE TITLE
analysis options "include" directive

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#27817]
Enhance the analyzer to support a new `include:` declaration in `.analysis_options` and `analysis_options.yaml` files. The `include:` declaration references another options file using a relative file path or a package:// uri.
```
include: package:dart.tools.lint/analysis_options.yaml
```
and
```
include: relative/reference/to/another/.analysis_options
```
Each option file can have at most one include: declaration referencing a single analysis options file. Circularity between analysis options files is expressly not supported.

Tasks
- [x] update `AnalysisOptionsProvider` to support `include` directive - https://github.com/dart-lang/sdk/commit/68ba3cfe51eb1f2873c2d718b1af03f695df90fc
- [x] update [ContextManager](https://github.com/dart-lang/sdk/blob/d0ee9613d46c920af838664124ea1f8a082f3909/pkg/analysis_server/lib/src/context_manager.dart#L481) to use revised `AnalysisOptionsProvider` functionality - https://github.com/dart-lang/sdk/commit/9ec75473230b8d30c69519beef3b5b24ac96b82c
- [x] update [ContextBuilder](https://github.com/dart-lang/sdk/blob/96750cd5cb734b98cf979331a3664587faa6b7e5/pkg/analyzer/lib/src/context/builder.dart#L341) to use revised `AnalysisOptionsProvider` functionality - https://github.com/dart-lang/sdk/commit/abffe25b7d5bd894962f48b7a388e07a3e56e3bf
- [x] update dartanalyzer cmdline to support `include` directive - https://github.com/dart-lang/sdk/commit/aff6b796f3d12ba5c0f0d3796bc26b0aa50651d5
- [x] update GenerateOptionsErrorsTask to report invalid `include` directives - https://github.com/dart-lang/sdk/commit/0d15f1d892afebc7bc1186857f3eeb585406b692
- [ ] update [BazelWorkspace](https://github.com/dart-lang/sdk/blob/c6ad6fa114421ada6e89968c5b5d5832b30e32cd/pkg/analyzer/lib/src/generated/bazel.dart#L142)  to look for an analysis options file in a known location relative to the workspace root if no analysis options are found using the existing search functionality.
- [ ] update navigation from `include` directive to referenced analysis options file
- [ ] code completion for include paths in analysis options file
- [ ] watch for changes in included options files and update analysis if they change

**Comment by danrubel** [comment]
Thanks for noticing that. I've now updated the initial comment to reflect this.

**Comment by mklim** [comment]
For anyone else who happens to stumble on this issue while they're debugging like I did, for some reason quotes are a problem for the tool even though presumably the value is supposed to be a string. The `include` value needs to be specified without any quoting at all. I think this may already be implied by @dnfield's comment above but while I was reading it I thought it was originally about the `package:` format, not the inclusion or lack of quotes.

```yaml
# Good.
include: path/to/analysis_options.yaml
```

```yaml
# BAD. 404 file not found.
include: 'path/to/analysis_options.yaml'
```

```yaml
# BAD. 404 file not found.
include: "path/to/analysis_options.yaml"
```

**Comment by srawlins** [comment]
Closing as complete; "include" directives have been around for a while; anything unimplemented should be it's own issue.
