### ISSUE TITLE
BytesBuilder.takeBytes should explicitly provide a Uint8List

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27818]
...so that it can be statically proved that you can obtain a ByteBuffer from the result. Flutter is going to be relying on this all over the place. For example, we're going to rely on File.readAsBytes providing a Uint8List. We already rely on the UTF8 decoder actually returning a Uint8List.

**Comment by floitschG** [comment]
This is extremely dangerous. None of these functions promise a `Uint8List`. It could easily be that they return a `const <int>[]` for some empty list here or there.

**Comment by whesse** [comment]
It is unclear from your reply whether you mean the proposed change is dangerous, or that the status quo is dangerous, and should be changed so the proposed change is safe.  Could you clarify, and suggest a resolution?

@lrnh

**Comment by Hixie** [comment]
We agree that our current code is dangerous, but we don't really have a choice. This is performance-critical code. That's why we'd like the APIs changed to be explicitly always returning raw buffers. It should be a backwards-compatible change.

**Comment by tvolkert** [comment]
https://dart-review.googlesource.com/c/sdk/+/101742

**Comment by tvolkert** [comment]
Breaking change request: https://github.com/dart-lang/sdk/issues/36900

**Comment by tvolkert** [comment]
This is implemented now.
