### ISSUE TITLE
'flutter create' lets me create an all-numeric app name, but 'flutter run' fails with such a name

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27811]

**Comment by Hixie** [comment]
Wow, numeric app names are an issue. pub fails because of the number in pubspec.yaml, flutter fails because of the number if flutter.yaml, adb fails because of the number in AndroidManifest.xml...

**Comment by mit-mit** [comment]
@Hixie this sounds like a Flutter, not Dart issue?

**Comment by Hixie** [comment]
Wow yes, no idea why I put this in the wrong repo. My bad. I think I've been filing too many SDK bugs at home recently...
