### ISSUE TITLE
name == ((ActionName) actionname).name; shows expected to find ";"

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#27815]
This simple class:
```dart
class ActionName {
    final String name;
    const ActionName(this.name);

    String toString() => name;

    bool operator==(final Object actionname) {
        if(!(actionname is ActionName)) {
            return false;
        }

        return name == ((ActionName) actionname).name;
    }

    int get hashCode => name.hashCode;
}
```
Gives me the following error messages:
```
ERROR: Expected to find ';' ([mdl] lib/src/flux/action.dart:56)
ERROR: Expected an identifier ([mdl] lib/src/flux/action.dart:56)
ERROR: Expected to find ')' ([mdl] lib/src/flux/action.dart:56)
```
It works with `return name == (actionname as ActionName).name;` 
(which is also prettier) but in my opinion the above code should also be valid

**Comment by eernstg** [comment]
It looks like you are trying to use Java-style syntax for a cast. However, the Dart grammar uses `as` for that construct (section 'Type Cast' in the spec) and the Java-style syntax is simply a syntax error, as reported.
