### ISSUE TITLE
No import quick fix where I expect one

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#27820]
I would expext an "add import" quickfix like below but here I don't get one

![image](https://cloud.githubusercontent.com/assets/405837/20297353/6e394c7c-ab10-11e6-8949-b02f3e6f5920.png)

![image](https://cloud.githubusercontent.com/assets/405837/20297379/8a47a422-ab10-11e6-8469-27144c15c2e6.png)

I don't know what context causes this. (Annotation, array literal, `const`, ...)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2546993004

**Comment by scheglov** [comment]
It was fixed, but I forgot to close it.
