### ISSUE TITLE
Bogus const warnings, when variables are const

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#27829]
False positive on B_STR below: Const variables must be initialized with a constant value.

const A_STR = 'str';
const B_STR = A_STR + 'b';

These then propagate through to create additional warnings such a "Const maps must only have const values.", etc

**Comment by jwren** [comment]
This is with version: 1.21.0-dev.3.0

**Comment by devoncarew** [comment]
@bwilkerson, can you take a look (or triage appropriately)? Thanks!

**Comment by jwren** [comment]
Update from Paul and myself- this is an elusive bug.  Paul had an idea of what CL (post the current SDK version number) I tried it and out and issue was gone, but when we switched my IJ back to the current stable SDK where I had seen it, the issue had also gone away.

**Comment by bwilkerson** [comment]
Is this with or without strong mode enabled?

**Comment by jwren** [comment]
With it enabled.

**Comment by srawlins** [comment]
This is now fixed. In both strong and not so strong:

```
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
$ cat 27829.dart 
const A_STR = 'str';
const B_STR = A_STR + 'b';
$ dartanalyzer 27829.dart 
Analyzing 27829.dart...
No issues found!
$ dartanalyzer --strong 27829.dart 
Analyzing 27829.dart...
No issues found!
```
