### ISSUE TITLE
The latest version of Dartium is no longer supported by Webstorm 2016.3

### ISSUE THREAD

**Issue by ClintFarmer** [dart-lang/sdk#27826]
Webstorm 2016.3 has been released and it has adapted the latest version of Chrome's debugging protocol. Stated [here](https://youtrack.jetbrains.com/issue/WEB-24182), any Chromium version less than 54 will not work for console logging.

**Comment by devoncarew** [comment]
This is also tracked as https://youtrack.jetbrains.com/issue/WEB-24182.

**Comment by alexander-doroshko** [comment]
Fixed since IntrelliJ IDEA 2016.3.1 and WebStorm 2016.3.2.
