### ISSUE TITLE
Iterable.where() should be generic and return an iterable with the given type

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27827]
The following code is sound but the analyzer can't tell:

```dart
new Directory('packages')
    .listSync()
    .where((FileSystemEntity entity) => entity is Directory)
    .where((Directory dir) { // ERROR HERE
      // ...
    });
```

If `where` was defined as `Iterable<T> where<T extends E>(...)` then the above could work (might even work automatically given type inference?).

**Comment by pq** [comment]
cc @bwilkerson

**Comment by alexeieleusis** [comment]
I have had to deal with this issue too, but `where` is about predicates, not types, how should it behave when the predicate is not a test for a type?

**Comment by Hixie** [comment]
presumably if you don't give the type explicitly, it would just return an `Iterable<E>`. (Maybe it would have to be annotated with `@optionalTypeArgs`?)

**Comment by lrhn** [comment]
I'd rather add a new method to do type-filtering, like `Iterable<T> Iterable.of<T>()`.
The `where` is used for many other things, and doesn't generally need the type parameter, even if it's declares as `<T extends E>` so we have a good default if it's omitted.

(I don't know what `@optionalTypeArgs` is, but I can assure you that it won't be in the platform libraries) :)

**Comment by Hixie** [comment]
I'd be totally on board with `.of<T>` too. :-)

(`@optionalTypeArgs` lets you enable the `require all type annotations` lint but still have some type annotations be optional. The platform libraries will presumably have to add it anywhere they declare a generic type where sometimes it makes no sense to give a type. For example, the Flutter framework uses it for GlobalKey, since the type argument only makes sense if you're going to use the `currentState` getter, but if you're using the key with a stateless widget there's no type that could make sense.)

**Comment by Hixie** [comment]
Just ran into this again. This is definitely going to become a bigger paint point in Dart 2.0.

**Comment by srawlins** [comment]
Is this now solved with [Iterable.cast()](https://api.dartlang.org/dev/2.0.0-dev.47.0/dart-core/Iterable/cast.html) and [Iterable.retype()](https://api.dartlang.org/dev/2.0.0-dev.47.0/dart-core/Iterable/retype.html)?

**Comment by eernstg** [comment]
The following works with `dart2js --preview-dart-2` 2.0.0-dev.47.0 and it might be what you're looking for:

```dart
main() {
  Iterable<num> xs = [1, 2.2, 3, 4.2];
  xs.whereType<int>()
      .where((int i) => i > 1)
      .forEach((int i) { print(i); }); // Prints '(3)'.
}
```
The vm prints `UnimplementedError: whereType is not yet supported`, but it's coming soon.

**Comment by natebosch** [comment]
Dart 2.0 contains `whereType` and `cast` and the lint `prefer_iterable_wheretype`. I don't think there is anything else to do here.
