### ISSUE TITLE
Dart analyzer always performs full project rescan

### ISSUE THREAD

**Issue by pinnisi** [dart-lang/sdk#27833]
I have a very large dart project (about 1600 .dart files growing), every time I make a little change in a file analyzer seems to perform a full project scan, slowing my work a lot.

I have Dart 1.20.1 with latest webstorm

**Comment by pinnisi** [comment]
seems fine with new intellij dart plugin 163.8651

**Comment by bwilkerson** [comment]
Then I'm going to assume the problem was solved. Let us know if you see this behavior again.
