### ISSUE TITLE
Js-Interop: Not possible to get raw error event from window

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27836]
I'm prototyping a Zone-free alternative to a global exception handler for Angular Dart.

(https://github.com/matanlurey/error_handler)

In the VM and Dartium, I'd use `runZoned(startAppFn, onError: (e, s) { ... }` in `main`.

However, in DDC and dart2js, I'd like to use `window.addEventListener('error')`:

https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror.html:

> At first glance the Error object isn’t very special. It contains 3 standardized properties: message, fileName, and lineNumber. Redundant values that already provided to you via window.onerror.

> The valuable part is a non-standard property: **Error.prototype.stack**. This stack property tells you at what source location each frame of the program was when the error occurred. The stack trace can be a critical part of debugging an error. And despite being non-standard, this property is available in every modern browser

- Doesn't require running most of the framework in a try/catch to report errors
- Already supported by any modern browser environment

I tried a few different approaches before opening this bug:

1. Using `dart:html` and `window.onError.listen((ErrorEvent e) { ... })`:

[ErrorEvent][doc_error_event] looks like it needs a manual update/triage - the `error` getter is annotated as a type `Object`, where-as I'd need it to be typed `Error` (or something that lets me get the `stack` property).

This would be my preferred mechanism - and I'd delegate `package:stack_trace` to clean it up.

[doc_error_event]: https://api.dartlang.org/stable/1.20.1/dart-html/ErrorEvent-class.html

2. Using `package:js`

I _thought_ I could be clever and try to get direct access to the raw window object:

```dart
@JS('window')
library error_handler.src.js_interop;

@JS()
external void addEventListener(String event, void callback(JsErrorEvent e));

abstract class JsErrorEvent {
  JsError get error;
}

abstract class JSError {
  String get stack;
}
```

It looks like, however, Dart is automatically wrapping it into the `ErrorEvent` object from `dart:html` - and I can't "force" it not to wrap.

3. Use a custom bit of JS and JS-interop with that

This currently works:

```js
(function() {
  window.addEventListener('error', function(event) {
    if (window.$dartErrorHandler) {
      window.$dartErrorHandler(event.error, event.error.stack);
    }
  });
})();
```

```dart
@JS('window')
library error_handler.src.js_interop;

import 'package:js/js.dart';
import 'package:stack_trace/stack_trace.dart';

@JS(r'$dartErrorHandler')
external set _jsErrorHandler(void callback(e, s));

set jsErrorHandler(void callback(Object e, Trace s)) {
  _jsErrorHandler = allowInterop((e, s) {
    callback(e, new Trace.parse(s));
  });
}
```

---

Am I expecting something that isn't supported? Is it a bug? What's my best way forward?

/cc @ferhatb

**Comment by alan-knight** [comment]
For option 1, the error property is typed "any" in the IDL, so it isn't clear to me that it would always be an Error object. But I also don't find an Error interface. It's possible that you could define an Error class via JS interop and cast to that, but I'm not sure about that.  @jacob314 for JS interop options.

**Comment by jacob314** [comment]
@matanlurey  what you are looking for is:
import 'package:js/js_util.dart' as js_util;

js_util.getProperty(someEvent, 'stack')
