### ISSUE TITLE
DDC dart-jsinterop-quill example can't watch for files

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#27840]
**SDK version:** 1.21.0-dev.6.0
**Platform:** MacOS 10.12.1
**Bazel release:** 0.4.0-homebrew
**Node version:** 7.1.0

Running https://github.com/vsmenon/dart-jsinterop-quill with the provided instructions did not perform the incremental compilation as expected.  `tool/watch.dart` did not seem to pick up the changes to the filesystem in order to trigger a bazel recompilation.

Running Webpack seems to be working as expected; running webpack in one terminal, and running`make` instead of `dart tool/watch.dart` in another terminal reloaded the libraries in the browser.

**Comment by vsmenon** [comment]
Hmm, I just tried with 1.21.0-dev.6.0 on the Mac, and `dart ./tool/watch.dart` does seem to still work for me.  Is it silent for you or crashing?  Which file are you editing?

**Comment by johnpryan** [comment]
I'm editing the `captains_log.dart` file, changing the quill theme.  

If I change line 43 of `watch.dart` to:

```
    file.watch(events: FileSystemEvent.MODIFY).listen((e) {
      print('file modified');
      run(process, messageGrouper, command);
    });
```

I don't see any logs in the console when I modify `captains_log.dart`

**Comment by johnpryan** [comment]
After debugging some more, the issue is with WebStorm.  If I edit the file with a different editor, the app is reloaded.

Feel free to close this issue.

**Comment by vsmenon** [comment]
Thanks for the update!

**Comment by johnpryan** [comment]
For future reference: WebStorm has a "safe write" feature that needs to be turned off.
