### ISSUE TITLE
Analyzer test failures on Windows - discrepency between 2 platforms

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#27845]
I ran the tests for analyzer package on both Linux and Windows 10 with SDK version 1.20.1. 
I expected to see the same results on both platforms or minor deviations. 

Windows:
```
11374 PASSED, 202 FAILED, 44 ERRORS
```

Linux:
```
11584 PASSED, 7 FAILED, 29 ERRORS
```

Since I have little insight into what is and what should be, all I can do it let you guys know that 195 more tests failing seems significant enough to warrant a "I noticed this, is this OK?" issue.

**Comment by srawlins** [comment]
Closing as stale.
