### ISSUE TITLE
VM Service: Document VM extension APIs

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27848]
The [VM service docs](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) currently don't describe how to invoke VM service APIs at all. In fact, they misleadingly say:

> An RPC response is a JSON object (http://json.org/). The response always specifies an
_id_ property to pair it with the corresponding request. If the RPC
was successful, the _result_ property provides the result.

This is definitely not the case for service extensions, which are allowed to return any JSON-encodable object.

**Comment by nex3** [comment]
See dart-lang/vm_service_client#11, which was caused by this confusion.

**Comment by turnidge** [comment]
You say that the doc doesn't "describe how to invoke service APIs at all".  But the doc specifies that the protocol "uses JSON-RPC 2.0", which specifies how to invoke rpcs.  So I don't understand that part, sorry, not trying to be obtuse here.  Maybe you meant something else?

You are quoting part of service.md that describes the "id" property.  The "id" property is required by the JSON-RPC spec on all responses.  The vm service documentation is paraphrasing this for expositional purposes.  Looking at the code in runtime/lib/developer.dart at the function _postResponse (line 145), it looks like the "id" field is being added automatically for service extension responses.  So are you saying that you get back a JSON response which doesn't have an "id" property?  Or are you talking about the *result* (the payload) of the response?

Do you think you could attach an example of the raw request/response that you are seeing that does not conform to the specification?  This would be concrete and would clarify a lot.

Thanks!

**Comment by nex3** [comment]
> You say that the doc doesn't "describe how to invoke service APIs at all". But the doc specifies that the protocol "uses JSON-RPC 2.0", which specifies how to invoke rpcs. So I don't understand that part, sorry, not trying to be obtuse here. Maybe you meant something else?

Sorry, I meant to write "service extension APIs."

> You are quoting part of service.md that describes the "id" property. The "id" property is required by the JSON-RPC spec on all responses. The vm service documentation is paraphrasing this for expositional purposes. Looking at the code in runtime/lib/developer.dart at the function _postResponse (line 145), it looks like the "id" field is being added automatically for service extension responses. So are you saying that you get back a JSON response which doesn't have an "id" property? Or are you talking about the result (the payload) of the response?

You're right. A better quote would be:

> By convention, every response returned by the Service Protocol is a subtype of Response and provides a type parameter which can be used to distinguish the exact return type. In the example above, the Version type is returned.

Extension APIs are an exception to this, since their responses have no restrictions.

> Do you think you could attach an example of the raw request/response that you are seeing that does not conform to the specification? This would be concrete and would clarify a lot.

```json
{
  "jsonrpc": "2.0",
  "method": "ext.hypotheticalExtensionMethod",
  "params": {},
  "id": "1"
}
```

```json
{
  "jsonrpc": "2.0",
  "result": "Not a subtype of Response",
  "id": "1"
}
```

**Comment by turnidge** [comment]
Ok, I get it.  I will consider whether we'd rather restrict extensions or document the unexpected exception to the rule.

**Comment by nex3** [comment]
Restriction extensions at this point would be a breaking change, both in theory and in practice. I know Flutter in particular would be broken.

cc @yjbanov

**Comment by yjbanov** [comment]
I'm not sure I understand the following statement:

> are allowed to return any JSON-encodable object

There's a very specific definition of JSON _object_. However, there are other kinds of _value_ that JSON supports. See http://www.json.org.

A JSON-encodable _Dart_ object is defined by the library used to serialize to JSON, the most popular being `dart:convert`. I would therefore expect `String`, `num`, `bool`, `Map`, `List` all be JSON-encodable, in addition to the `toJson` convention on custom types, as well as [revivable custom types](https://api.dartlang.org/stable/1.20.1/dart-convert/JsonCodec/JsonCodec.withReviver.html).

In all cases, however, maps, lists, numbers, booleans, strings and nulls are encodable.

**Comment by turnidge** [comment]
Yegor,

All other service protocol RPC results are maps with a Type property.  The
only exceptions are the extension rpcs.

Natalie,

I realize it would break compatibility.

**Comment by yjbanov** [comment]
I just re-read @nex3's original description and realized that I misunderstood it. It makes perfect sense. Please disregard https://github.com/dart-lang/sdk/issues/27848#issuecomment-262093810.

JSON-RPC 2.0 [requires](http://www.jsonrpc.org/specification#response_object) that all responses are JSON Object. The method-specific value is supposed to be packed in the `result` property. So I wouldn't oppose to making the protocol spec-compliant, but let's coordinate so Flutter is not broken during the transition. I can pin dependency versions according to the plan we decide on.

**Comment by turnidge** [comment]
Yegor,

I believe that your responses are currently compatible with the JSON-RPC
spec, because we take whatever result you return and wrap it in the
appropriate map with an id field for you.  I believe that the issue at hand
is whether the extension rpcs should conform to the convention used by the
rest of the VM Service protocol, which further restricts the kinds of
payloads that are returned in the "result" property.

Todd

**Comment by yjbanov** [comment]
Gotcha. From where I stand, such a restriction would seem arbitrary, but judging by my messages above I obviously do not fully understand how VM service is supposed to work :)
