### ISSUE TITLE
Incorrect behavior when setter and static method has the same name

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/sdk#27843]
In specification 10.7:
>It is a static warning if a class C declares a static method named n and has
a setter named n =.

But this code
```dart
void main() {
  new Foo();
}

class Foo {
  Foo() {
    bar(42);
  }

  void set bar(int value) {
    print("setter");
  }

  static void bar(int value) {
    print("static");
  }
}
```
causes no warnings, even in strict mode, and prints `static`. But dart2js fails with error `Duplicate definition of 'bar'`.

**Comment by srawlins** [comment]
Analyzer now reports:

> Class 'Foo' can't define static member 'bar' and have instance member 'Foo.bar' with the same name.
