### ISSUE TITLE
feature request: analysis server to support the language-server-protocol

### ISSUE THREAD

**Issue by joeblew99** [dart-lang/sdk#27854]
Raising this as a suggestion to support:
https://github.com/Microsoft/language-server-protocol

A standard for language servers has been announced and is being used already and supports about 10 already.

This means that you can use VsCode,  intelli, etc or a cloud based IDE and they all use the same mechanism for integrating your language into the IDE.

In terms of LOE, this really makes things much more DRY for the dart-services team. One API to support for all IDE's !!

Also, interestingly this is a a cloud IDE that support the language server protocol
https://dzone.com/articles/eclipse-che-50-announced-at-checonf-2016

BTW, Google Cloud Shell currently users the older Eclipse Orion.

**Comment by bwilkerson** [comment]
Jow,

Thanks for the suggestion.

The analysis server uses a similar protocol that was developed before the
Microsoft protocol was published. It's currently being used by several
IDEs, including IntelliJ, VS Code, and vim.

A couple of people have written adapter layers that convert between the
two. In fact, that's how the Dart VS Code plugin (
https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code) is
implemented. I haven't personally used VS Code, but I know enough about the
plugin that I'd recommend that VS Code users should try it out.

Brian

**Comment by joeblew99** [comment]
i use the Dart VS code plugin every day. Yep its solid.

But i have to use intelliJ to get Flutter debugging. intelliJ is very heavy

Anyway, closing...

**Comment by DanTup** [comment]
> In fact, that's how the Dart VS Code plugin (https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code) is implemented.

FWIW, this isn't actually the case. I did investigate this but they APIs didn't fit together perfectly and there was a lot missing (like no syntax highlighting!). I figured there wasn't a lot of advantage to the protocol (I'm still having to map A to B) unless it was used by more than one integration.

If the protocol grows to include the missing things and is adopted by more editors, I might re-visit it.

@joeblew99 Glad to hear Dart Code is working well for you! Flutter support is planned (though not started). You can subscribe to https://github.com/Dart-Code/Dart-Code/issues/198 if you're interesting in updates :-)

**Comment by joeblew99** [comment]
makes sense. It too new and i noticed the Dart API provides allot more.

Oh Flutter support !!! You made my day dude. I really hate intelliJ - its
so heavy!

**Comment by DanTup** [comment]
@joeblew99 FYI - I've made a pre-release version with Flutter integration and looking for feedback - see https://github.com/Dart-Code/Dart-Code/issues/318 :-)

**Comment by joeblew99** [comment]
@DanTup thanks for the tip.
I moved on from Dart to golang for mobile apps and desktop apps, so was too late for me.

**Comment by vogella** [comment]
> @DanTup If the protocol grows to include the missing things and is adopted by more editors, I might re-visit it.

https://langserver.org/ lists a lot of clients which supports the language server protocol.

**Comment by natebosch** [comment]
langserver.org also lists a server for Dart.
https://github.com/natebosch/dart_language_server shims the analysis server to follow the protocol.
