### ISSUE TITLE
AnalysisServer.execution_createContext() doesn't work in 1.21.0-dev.7.0

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27856]
Works fine with SDK 1.20.1,
but with 1.21.0-dev.7.0 (Windows, x64) Analysis Server doesn't respond anything to [AnalysisServer.execution_createContext()](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_execution.createContext) request.

**Comment by devoncarew** [comment]
@scheglov @bwilkerson

**Comment by scheglov** [comment]
https://codereview.chromium.org/2524453002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/e769868325202095eccd7beb1546f0dd77d99fef

**Comment by devoncarew** [comment]
@whesse, we're seeing this issue in the dev sdk that flutter is on; just to confirm that this fix is planned for the next dev sdk?

**Comment by keertip** [comment]
A dev9.0 was built this morning which has this fix.
