### ISSUE TITLE
Argument value is null in JS callback function in dart2js while working fine in Dart/Dartium

### ISSUE THREAD

**Issue by tomaszkubacki** [dart-lang/sdk#27852]
Lets assume we are using chart.js package from pub and got registered JS click callback like this:

 onClick: js.allowInteropCaptureThis(([t,a,b]){
      JsObject obj = new JsObject.fromBrowserObject(b[0]);
      int index = obj["_index"];
      print(index); //prints null only in dart2js version!!
 }
We would expect that print(index) prints actual index of clicked pie chart item.
And this code works ok in Dart/Dartium (prints actual index on click) but not in dart2js version (always prints null)

Steps to reproduce:

1. clone this repo https://github.com/tomaszkubacki/dart_chart-bug 
2. do pub get and pub build
3. run app (eg pub serve) and open with web browser
4. click pie chart item
5. expect to see printed number in dev console but null is printed instead

**Comment by jacob314** [comment]
The problem is you cannot merge package:js code and dart:js as package:js does not use wrapping.
Dartium you can often get away with it, but in Dart2js you will get inconsistent behavior.
Here is a fixed version of your code that uses
package:js/js_util.dart instead dart:js

```dart
// Copyright (c) 2016, Tomasz Kubacki. All rights reserved. Use of this source code
// is governed by a BSD-style license that can be found in the LICENSE file.

import 'dart:html';
import 'dart:math' as math;
import 'package:chartjs/chartjs.dart';
import 'package:js/js.dart';
import 'package:js/js_util.dart' as js_util;


void main() {
  var ctx = (querySelector('#canvas') as CanvasElement).context2D;
  var rnd = new math.Random();
  var months = <String>["January", "February", "March", "April", "May", "June"];

  var config = new ChartConfiguration(
      type: 'pie', data:
  new LinearChartData(labels: months, datasets: <ChartDataSets>[
    new ChartDataSets(
        label: "",
        backgroundColor: [
          "#2196F3",
          "#F44336",
          "#673AB7",
          "#009688",
          "#E91E63",
          "#673AB7",
          "#FF9800",
          "#8BC34A",
          "#607D8B",
          "#3F51B5"
        ],
        data: months.map((_) => rnd.nextInt(100)).toList())
  ])
  ,
      options: new ChartOptions(responsive:false, onClick: allowInteropCaptureThis(([t,a,b]){
    if(b != null && b is List && b.length > 0){
      var obj = b[0];
      int index = js_util.getProperty(obj, "_index");
      print(index); ///!!!BUG - this is always null on dartjs and correct in dart/dartium
    }
  }) ) );

  var chart = new Chart(ctx, config);
  chart.update();
}

```

**Comment by tomaszkubacki** [comment]
Thanks @jacob314 !
