### ISSUE TITLE
New analysis driver doesn't respect "exclude" declaration in .analysis_options

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27868]
Repro:
- In IntelliJ, add `enable-new-analysis-driver` to the registry option `dart.server.additional.arguments`.
- Open the folder `pkg/analyzer_cli` in IntelliJ.

Expected result: no errors or warnings, due to the fact that `pkg/analyzer_cli/.analysis_options` contains the option:

    exclude:
      - 'test/data'

Observed result: many errors and warnings produced for source files located inside `pkg/analyzer_cli/test/data`.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2522543007/
