### ISSUE TITLE
vm/dart/hello_fuchsia_test fails on dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27867]
The new test runtime/tests/vm/dart/hello_fuchsia_test.dart fails on dartium

Marking as fail in runtime/tests/vm/vm.status

@terrylucas @zanderso

**Comment by a-siva** [comment]
Why is this test running on dartium? I will update the status file to skip this test.

**Comment by whesse** [comment]
Also skip it on dart2js - it is failing on the browsers.  The vm tests should not be specific to a specific runtime.  I don't think this is the place for this test - it should be in the tests/standalone directory, or if there are tests specific to the fuchsia embedding rather than the standalone embedding, then there should be a tests/standalone/fuchsia or tests/fuchsia directory.

**Comment by whesse** [comment]
I have a CL to skip it on dart2js, so I will close the issue when it is landed.
