### ISSUE TITLE
Provide a way to keep gen_snapshot from reading its source code paths

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/sdk#27860]
On Flutter we saw a failure when running gen_snapshot on our build servers:

    Error: 'dart:_internal-patch/class_id.dart': error: line 8 pos 3: native function 'ClassID_byName' (1 arguments) cannot be found
         static int _lookup(String name) native "ClassID_byName";

This occurred because the gen_snapshot binary incorporates the fully-qualified paths to some of the Dart library source code used to build it.  gen_snapshot will look at those paths and use the version of the libraries at that location if present.  (If the path does not exist, it will fall back to libraries that are statically linked into the binary)

The build server does separate builds of both the Flutter engine (including gen_snapshot) and the Flutter framework.  When the framework's copy of gen_snapshot runs, it will pick up the library sources from the engine source tree.  The engine source tree might be synced to a different version of Dart than the one expected by the framework, resulting in incompatible libraries.

We would like a way to force gen_snapshot to always use the statically linked version of the libraries and never read them from elsewhere in the filesystem.

@a-siva @eseidelGoogle

**Comment by cbracken** [comment]
It appears as though we're running into this again. 

Example of a framework built against a new (Dart 1.24) engine where the latest engine build on the machine was 1.23-based:
https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac/builds/3609/steps/flutter%20build%20apk%20stocks/logs/stdio

Example of a framework built against an older (Dart 1.23) engine where the latest engine build on the machine was 1.24-based:
https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac/builds/3600/steps/flutter%20build%20apk%20stocks/logs/stdio

**Comment by jason-simmons** [comment]
I noticed that LoadPatchFiles() in runtime/bin/builtin.cc is trying to read the patch files from the paths used during the build of the engine.  If nothing is present at that path, then it will fall back to a copy of the patch sources that is linked into gen_snapshot.

Does the behavior in LoadPatchFiles also need to be gated behind a flag like use_corelib_source_files?

**Comment by Hixie** [comment]
IMHO we should fix this by removing the path from the data entirely. We really don't want to be shipping files that mention "build slaves" to our customers.

**Comment by a-siva** [comment]
landed https://codereview.chromium.org/2903693003 to fix this immediate issue.

Will look at some further cleanups in a follow up cl to remove this option of falling back to the sources, with the new front end pipeline I think this makes less sense.

**Comment by a-siva** [comment]
landed https://codereview.chromium.org/2921513002 to get rid of any references to source paths and build slaves.
