### ISSUE TITLE
createElementNS-namespace-errors_t01 test is failing on Firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27873]
The co19 test co19/LayoutTests/fast/dom/createElementNS-namespace-errors_t01 started failing with a runtime error on Firefox 50.  The error is

 Exception: null: Error: Argument 3 of Document.createElementNS can't be converted to a dictionary

I think this might be connected to what it says at https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS

It says, about the third, optional argument:
An optional ElementCreationOptions object containing a single property named is, whose value is the tag name for a custom element previously defined using customElements.define(). For backwards compatibility with previous versions of the Custom Elements specification, some browsers will allow you to pass a string here instead of an object, where the string's value is the custom element's tag name. See Extending native HTML elements for more information on how to use this parameter.
The new element will be given an is attribute whose value is the custom element's tag name. Custom elements are an experimental feature only available in some browsers.

So, maybe we are passing an empty string or null there, and it wants a dictionary, or something.

Marking as failing in tests/co19/co19-dart2js.status.

**Comment by alan-knight** [comment]
First guess, without looking, is that it reacts badly if we pass null instead of not passing the parameter at all. We might have to tweak that manually or add it to a list.

**Comment by athomas** [comment]
LayoutTests have been deleted.
