### ISSUE TITLE
Two webgl tests now failing on Firefox 50

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27872]
The tests
co19/LayoutTests/fast/canvas/webgl/buffer-data-array-buffer_t01
and
co19/LayoutTests/fast/canvas/webgl/gl-enum-tests_t01
are now failing on Firefox, returning the wrong error codes.

The buffer test has error
 Exception: Expect.fail('getError expected: NO_ERROR. Was 0x501 : ')
and the gl-enum-tests has failure
Exception: Expect.fail('getError expected: 0x500. Was 0x502 : test #14 should return INVALID_ENUM.')

Tests are marked failing in tests/co19/co19-dart2js.status.

**Comment by athomas** [comment]
LayoutTests have been deleted.
