### ISSUE TITLE
corelib/list_test fails on dart2js Firefox 50

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27871]
There is a new failure in corelib/lib_test when the dart2js output is run on the new Firefox version, 50.  This is on both linux and windows.  This will be noted in the status file tests/corelib/corelib.status.
This seems like a big error - if list operations are broken on Firefox, that is important.

Failures are:
dart2js-ff release_x64 corelib/list_test/01 RuntimeError
dart2js-ff release_x64 corelib/list_test/none RuntimeError

Error message is 
value: Exception: Expect.throws: Unexpected 'NoSuchMethodError: method not found: 'forEach$1' (J.getInterceptor$ax(...).forEach$1 is not a function)'
                    J.forEach$1$ax@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:5227:12
                    dart<.testGrowableListOperations_testConcurrentModification_testForEach_closure.call$0@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:4744:9
                    dart<.Expect_throws@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:3881:9
                    dart<.testGrowableListOperations_testConcurrentModification_testForEach.call$1@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:4738:9
                    dart<.testGrowableListOperations_testConcurrentModification.call$1@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:4700:9
                    dart<.testGrowableListOperations@http://127.0.0.1:33777/root_build/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/test.js:4257:9

**Comment by whesse** [comment]
Also see #28014

**Comment by rakudrama** [comment]
These tests no longer fail after Firefox uodated past verion 50.
