### ISSUE TITLE
Function-type not compatible.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27874]
While making the test package strong-mode clean, I ran into a case where strong mode wouldn't let me return a function.

Patch Set 4: https://codereview.chromium.org/2515303002/#ps4
https://codereview.chromium.org/2515303002/diff/60001/lib/src/frontend/expect_async.dart

"The return type '([dynamic]) → T' isn't a 'Func1(A) → T', as defined by the
method 'expectAsync1'"

The returned function is:
``` dart
const _PLACEHOLDER = const Object();
...
T max1([a0 = _PLACEHOLDER]) => max6(a0);
```

The issue is fixed by adding `Object` as type for `max1`.

``` dart
T max1([Object a0 = _PLACEHOLDER]) => max6(a0);
```

It's difficult to see, why `Object` would be better than `dynamic`.

/cc @vsmenon

**Comment by jmesserly** [comment]
I believe this was related to fuzzy arrows. should be fixed now.
