### ISSUE TITLE
Wrong type of ArgumentError.message

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27889]
`ArgumentError.message` propertry has type dynamic. But the only way to set this property is to use constructor `ArgumentError.value(value, [ String name, String message ])` where message type is String. If so, I think, property type should be changed to String

**Comment by lrhn** [comment]
Sadly, the `message` field can also be set using the `ArgumentError([this.message])` constructor which is typed as `dynamic` for historical reasons.
