### ISSUE TITLE
Open sockets survive a full VM reload

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27898]
I haven't carefully verified this but I suspect the following scenario can occur:

1. Start an app (e.g. a Flutter app).
2. In that app, open a network socket with `Socket.connect`.
3. Restart the VM that is running the app without terminating the host process. In Flutter terms, this is a "full reload" (`R`). This is a common thing to do when developing an app, e.g. after it has experienced an unrecoverable error.
4. I believe at this point the socket is still open and can no longer be closed.

This is problematic in particular when writing an app that talks to an IoT device that can only accept one connection at a time. For example, hypothetically, if one were writing a mobile app remote control for a Sharp LC-70UD27U TV. I'm just giving this as an example, I'm not saying it's what I was doing or anything.

cc @johnmccutchan

**Comment by ds84182** [comment]
Heh, thats oddly specific :laughing: 

Anyways I've experienced while developing an IRC bot. After using the `vm restart` command in the debugger the connection to the IRC server stays alive. I have no clue if the same happens for a `ServerSocket`, but that could be something else to test.

**Comment by johnmccutchan** [comment]
@zanderso what is the life cycle of sockets?

The full reload (R) kills the old isolate and spawns a new one. How long are the sockets from the old isolate  going to stay around for?

**Comment by zanderso** [comment]
If neither side explicitly closes the connection, the open socket appears to languish in the eventhandler, whether or not the Dart object wrapping the socket disappears. The person who designed the socket lifetime probably didn't anticipate any sort of reload. I think it should be straightforward to attach a finalizer to the Dart object at the point where we write the native field, but I'll have to investigate whether that finalizer should directly call close(), or whether it should try to poke the eventhandler to get it to call close().

**Comment by johnmccutchan** [comment]
@zanderso Thanks for the clarification. We will need to the sockets closed as soon as the isolate dies. I don't think it matters whether or not we call "close" because the isolate is *dead*.

**Comment by johnmccutchan** [comment]
Thanks @zanderso !
