### ISSUE TITLE
dev_compiler: Allow read-only access to initializing formals by default

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27894]
This is the dev_compiler specific issue for #27891; please refer to that issue for additional information.

**Comment by jmesserly** [comment]
fyi, I don't think we'll have to do anything once analyzer fixes https://github.com/dart-lang/sdk/issues/27895, other than make sure we have a test case.

**Comment by eernstg** [comment]
Test cases: Please check out `tests/language/initializing_formal_*_test.dart` and `tests/language/parameter_initializer5_test.dart` (the former ones are test cases for this feature; the latter one used to test that the access was a compile-time error, and it has been adjusted now that it isn't an error any more).

**Comment by vsmenon** [comment]
I had a CL to flip the flag, but it's obsoleted by Brian's flipping it on by default.  I had checked the tests - they pass.  Now that it's on, we should migrate them over:

https://codereview.chromium.org/2534293002/

**Comment by vsmenon** [comment]
Closing, as it's on by default.  I'll land the tests on review.
