### ISSUE TITLE
analyzer: Allow read-only access to initializing formals by default

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27895]
This is the analyzer specific issue for #27891; please refer to that issue for additional information.

**Comment by eernstg** [comment]
When ready, please remove the `DartOptions` directives from the tests,
```
tests/language/initializing_formal_*_test.dart
tests/language/parameter_initializer5_test.dart
```
such that it will be tested that the affected tools (the analyzer and dart2js) actually enable initializing formal access without the `--initializing-formal-access` flag.

**Comment by bwilkerson** [comment]
This is enabled by default as of https://codereview.chromium.org/2532953004/.

I have not yet updated the tests.

**Comment by eernstg** [comment]
I can see that https://codereview.chromium.org/2532953004/ was committed as 7e067a6fc8933b99585c1cf6c49f184014ea745f. Thanks! I'll mark the analyzer subtask as done on https://github.com/dart-lang/sdk/issues/27891 now, because developers do not depend on the test updates to use this feature.

**Comment by eernstg** [comment]
@bwilkerson, please close this one when the tests have been updated (I believe that's the only missing piece---otherwise please indicate what else is missing).

**Comment by bwilkerson** [comment]
The tests were updated here: https://codereview.chromium.org/2540843002/
