### ISSUE TITLE
"Invalid override" error from analyzer in strong mode

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#27890]
Given the following minimal example:

```dart
abstract class X<R> {
  R foo();
}

class Y extends X<Null> {
  foo() {
    print("Hello");
  }
}
```

in a strong mode project everything seemingly looks good.
Once I change something in the foo method (e.g. add another print statement) I get the error "ERROR: Invalid override. The type of Y.foo (() → dynamic) is not a subtype of X<Null>.foo (() → Null).".

I can make the error go away again by either
* Select all, cut, (wait until the error goes away), paste => the error is still gone.
* Add "Null" as a return type for foo, the error goes away, optionally remove the return type again and the error is still gone.

Dart analyzer from the command line finds no errors in the above code.

I'm using IntelliJ IDEA.

**Comment by jmesserly** [comment]
I can't reproduce this anymore ... hoping it's been fixed.

What should happen: inference should decide the return type of `foo()` is `Null`, and it should stay that way.

What I think used to happen: inference filled in `Null` the first time. But analyzer got in a weird state where it analyzed the code in Dart 1 mode (or maybe ran tasks out of order), filling in `dynamic` the second time. The architecture of analyzer is pretty different now, should it should be resistant to this sort of bug.
