### ISSUE TITLE
pkg/meta: @mustCallSuper does not understand operators?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27896]
I'd expect this to be warning free:

```dart
import 'package:meta/meta.dart';

class A {
  @mustCallSuper
  operator==(Object o) => o is A;
}

class B extends A {
  @override
  operator==(Object o) => o is B && super == o;
}
```

But it's not.

(The error message is also wrong, it should say _does not invoke_, but it says _does invoke_)

**Comment by natebosch** [comment]
The "does" -> "does not" has been fixed. The existed of the warning still exists.
