### ISSUE TITLE
"pub" doesn't work on ReleaseARM builds

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27909]
I have the Dart SDK's `.gclient` file at `/home/ianh/dev/dart-sdk`. I run `gclient sync`, then `./tools/build.py -m release -a arm runtime`. I have `/home/ianh/dev/dart-sdk/sdk/sdk/bin` in my path. If I run `pub get` I get:

```
/home/ianh/dev/dart-sdk/sdk/sdk/bin/pub: line 85: /home/ianh/dev/dart-sdk/sdk/sdk/../out/ReleaseARM/dart-sdk/bin/dart: No such file or directory
```

**Comment by mit-mit** [comment]
CC @whesse

**Comment by whesse** [comment]
You also need to build the create_sdk target, so the dart-sdk directory is built, with all of the tools like dart2js, pub, dartanalyzer, dartfmt, and so on.

**Comment by whesse** [comment]
Fixed the wiki page Building-Dart-SDK-for-ARM-processors to show create_sdk instead of runtime as the default build command.

**Comment by Hixie** [comment]
cool thanks.
