### ISSUE TITLE
Analyzer quick-fix to insert a method has bad formatting when inserted into an empty class

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27903]
It's very unlikely you'd have an empty class, but given the following code:

```dart
class danny {
  b a;

  method1() async {
    await a.fred();
  }

  method2() {}

  method3() {}

  method4() {}
}

class b {}
```

If you invoke `Create method 'fred'` in `method1` it results in the following:

```dart
class danny {
  b a;

  method1() async {
    await a.fred();
  }

  method2() {}

  method3() {}

  method4() {}
}

class b {  fred() {
  }
}
```

There should be a newline in front of the inserted code. I found a few similar issues when you don't have an empty class (I ended up with the first inserted line being indented too far) but was unable to repro; not sure exactly what that looked like.

I don't know if it's intended that quick fixes are intended to always result in correctly-formatted inserts - if not, then feel free to ignore this.

**Comment by zoechi** [comment]
Formatter issue should be reported in https://github.com/dart-lang/dart_style

When I format your code with `dartfmt` I get

```dart
class danny {
  b a;

  method1() async {
    await a.fred();
  }

  method2() {}

  method3() {}

  method4() {}
}

class b {
  fred() {}
}
```

**Comment by DanTup** [comment]
@zoechi This isn't an issue with the formatter; that works fine. It's about whether code generated by analyzer quick-fixes should be formatted correctly when generated. I understand if this isn't a goal, but I thought it was worth raising while I had it in front of me in case it was expected to be indented correctly.

**Comment by zoechi** [comment]
Missed the "quick-fix" sorry for the noise. I also think this should be fixed

**Comment by DanTup** [comment]
It wasn't all that clear in the original message/title - I updated the title after your comment to hopefully make it clearer!

**Comment by bwilkerson** [comment]
I don't know that it's a goal that the quick fixes always insert code consistent with the formatter (because the formatter evolves over time), but it should produce something nicer than this.

@scheglov in case you're interested

**Comment by scheglov** [comment]
https://codereview.chromium.org/2538143003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/666d4efce2c8b110aabe44139151e5e0581d9576
