### ISSUE TITLE
browser/package_resolve_browser_hook_test fails with CSP (content security policy)

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27914]
The test
browser/package_resolve_browser_hook_test
is failing on the drt-csp-minified bots, because the content security policy prohibits
what the test is trying to do without some special headers.

Marked as failing in tests/isolate/isolate.status.

**Comment by sigmundch** [comment]
Thanks for updating the test status. We could update the test to not include an inline script tag, but seems overkill for what this is testing. I updated the status to SkipByDesign.
