### ISSUE TITLE
Hot reload stress test bot that runs simdbc

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27918]
@whesse @a-siva

**Comment by johnmccutchan** [comment]
Bill,

The request is for a simdbc version of the vm-reload bots.

Thanks,
John

**Comment by johnmccutchan** [comment]
@whesse ping

**Comment by whesse** [comment]
Sorry, I thought I had asked a followup question, but I can't find it in my mail or the issue tracker.  Which OS should this run on - linux or macos?

I have added both possibilities to the dart-vm recipe in the following commit: https://chromium-review.googlesource.com/#/c/415732/

**Comment by whesse** [comment]
I have created a CL that adds both a linux-release and mac-release builder running simdbc64 and reload:
https://chromium-review.googlesource.com/#/c/416881/

**Comment by johnmccutchan** [comment]
@whesse MacOS would be ideal.

**Comment by whesse** [comment]
Bots are up and running (and failing).  Reopen this issue if they need any changes.

**Comment by johnmccutchan** [comment]
@whesse Hi bill,

could we have one debug mac bot and one release mac bot instead of linux and mac release bots?

It's important that we get debug coverage here too.

Thanks,
John

**Comment by whesse** [comment]
The bot will be slower, because we don't have any extra mac bots, I'll have to ask for them.  Do you want the linux bot at all?

**Comment by johnmccutchan** [comment]
The linux bot isn't necessary.

**Comment by athomas** [comment]
Seems this was actually done at the time. Closing.
