### ISSUE TITLE
add more details to deferred load errors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#27927]
Consider adding more details about the reason behind a failure on a deferred load. For example besides saying:

  DeferredLoadException: 'Loading http:/.../main.dart.js_11.part.js failed`

we could include why it failed. For example:

 - A 404 would say:
  DeferredLoadException: 'Loading http:/.../main.dart.js_11.part.js failed`, because the asset was not found.

 - An error while running the script, could say:
  DeferredLoadException: 'Loading http:/.../main.dart.js_11.part.js failed`, because the downloaded chunk appears invalid and produced errors while we tried to load it.

**Comment by sigmundch** [comment]
other errors may include: 
- chunk is outdated (e.g. it's hash doesn't match the expected hash)

**Comment by srawlins** [comment]
An event log is now included in the exception. If the file is missing:

```
DeferredLoadException: 'Loading file:///Users/srawlins/code/dart2js-bug/build/main.dart.js_1.part.js failed: [object Event]
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from file:///Users/srawlins/code/dart2js-bug/build/main.dart.js_1.part.js
 - download failed: main.dart.js_1.part.js (context: js-failure-wrapper)
'
```

If the file fails to parse:

```
DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'bYxuV4kOmGGTDE+Z46nWkF66jjg=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from file:///Users/srawlins/code/dart2js-bug/build/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (bYxuV4kOmGGTDE+Z46nWkF66jjg=)
'
```

Close?

**Comment by sigmundch** [comment]
thanks for looking Sam, yes let's close
