### ISSUE TITLE
Method DoubleLinkedQueue.removeWhere works incorrectly in some special cases.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#27920]
Dart API reads about the `DoubleLinkedQueue.removeWhere(bool test(E element))` method:

The test function must not throw or modify the queue.

Common practice is to throw some special exception in such cases. However, nothing special happens:

1. If test function removes an element, finally all the elements are removed and queue.length returns negative value
2. If test function adds an element to the queue, dart hangs.
3. If test function throws an error, some elements are removed and error is thrown.

I use Dart version 1.21.0-dev.7.0 on Windows.

Below are code examples.

1. Queue length becomes negative number here:

``` dart
import "dart:collection";
DoubleLinkedQueue queue = new DoubleLinkedQueue.from([1, 3, 3, 4, 5, 6]);
bool testModify(var element) {
  queue.removeFirst();
  return true;
}
main() {
  queue.removeWhere(testModify);
  print(queue);
  print(queue.length);
}
```

Sample output is:
{}
-6

2. Dart hangs when runs the following code in checked and non-checked mode:

``` dart
import "dart:collection";
DoubleLinkedQueue queue = new DoubleLinkedQueue.from([1, 3, 3, 4, 5, 6]);
bool testModify(var element) {
  queue.add(2);
  return true;
}
main() {
  queue.removeWhere(testModify);
}
```

3. The following code just catches an exeption :

``` dart
import "dart:collection";
DoubleLinkedQueue queue = new DoubleLinkedQueue.from([1, 3, 3, 4, 5, 6]);
bool testThrow(var element) {
  if(element < 4) return true;
  else throw new Error();
}
main() {
  try { queue.removeWhere(testThrow); } on Object catch(e) { print(e); };
  print(queue);
  print(queue.length);
}
```

Sample output is:
Instance of 'Error'
{4, 5, 6}
3

**Comment by floitschG** [comment]
Dart does not specify what should happen when a requirement is not satisfied. Sometimes it verifies them, sometimes it's just too costly to check them and the behavior is undefined. From time to time, we can add checks in asserts (like the concurrent-modification checks in some Iterables), but in other cases the cost would be too high (going from a linear algorithm to a squared one, or adding too much code).

The `DoubleLinkedQueue` seems to fall into the latter category:
- checking that elements aren't removed or added would require us to have a vision of the whole list, which is hard to do for a linked list.
- checking for thrown exceptions would slow down the code; probably even in unchecked mode. Even adding an `if (isChecked)` would increase the size of the function and make it less likely to be inlined. We can't add a `try/catch` in an `assert`.

@lrhn: wdyt?

**Comment by lrhn** [comment]
The three problems here are actually pretty diverse.

The negative element count means that we can get into a completely incorrect state. If we can fix that, I think we should (and I'm working on that).

The infinite loop when you keep adding elements while trying to remove all elements is what I would characterize as "you asked for it, you got it". A similar thing can likely happen for `queue.addAll(queue)`.
We *can* definitely make tests that are harder to avoid (like keeping a modification counter that is updated on any add or remove), but it's a matter of diminishing returns.

Successfully surviving when a test function throws is working as intended. That's the goal to aim for - we should allow user code to crash, and that can interrupt the operation at any point. We make no guarantee about which elements have been removed from the collection afterwards, it can be between zero and all of the ones that has been checked, but it should not leave the collection in an internally inconsistent state (negative length is a good example of something that must not happen).

**Comment by sgrekhov** [comment]
The current implementation of `DoubleLinkedQueue.removeWhere()` checks that removed element is still in the queue
https://github.com/dart-lang/sdk/blob/b6a0c50bf697598be75c3bf590e473ecf9cddf55/sdk/lib/collection/queue.dart#L366-L386

For that it checks `entry._queue` value
https://github.com/dart-lang/sdk/blob/b6a0c50bf697598be75c3bf590e473ecf9cddf55/sdk/lib/collection/queue.dart#L371-L374

But this is a weak check. For example `clear()` method doesn't touch `entry._queue` value. https://github.com/dart-lang/sdk/blob/b6a0c50bf697598be75c3bf590e473ecf9cddf55/sdk/lib/collection/queue.dart#L444-L448

So, if  `test` modifies queue by calling `clear()` then removed entries still contain links to the queue anf this check doesn't work. And we can get negative `length` values

**Comment by lrhn** [comment]
Good catch. The `clear` method should clear all the entries as well.
