### ISSUE TITLE
Only top level JS annotations should be allowed to contain dots

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#27926]
The following should generate a static error as the ```@JS``` annotation for location is not top level but contains a dot.

```dart
@JS('goog.maps')
class Maps {
  @JS('current.loc');
  external static location;
}
```

If you  want to access location as a static you should instead be required to write

```dart
@JS('goog.maps.current')
class Current {
  @JS('loc');
  external static location;
}
```

There isn't much benefit from supporting dot within ```@JS``` annotations on static member names the meaning
of static ```@JS``` annotations containing dots is confusing.

**Comment by daniel-v** [comment]
Just ran into this. DDC warned me with a link to this issue. Big, big 👍 for properly informing me about it.
