### ISSUE TITLE
Doc request for "So I want to move to strong mode"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#27944]
You've convinced me I want to move to strong mode. :)  How do I do it?

I saw http://news.dartlang.org/2016/11/dart-strong-mode-and-ahead-of-time_30.html and I'm sold. Is there a "follow this guide" or "do these things" doc?

Thanks!

**Comment by kwalrath** [comment]
Shams is working on this. I'll move this bug to site-www.

**Comment by sethladd** [comment]
Great to hear!

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-www#177
