### ISSUE TITLE
WebRTC wrappers are incomplete / buggy in DDC

### ISSUE THREAD

**Issue by KeatonTech** [dart-lang/sdk#27949]
# Describe your issue compiling with DDC
The DDC wrappers for WebRTC classes like RTCPeerConnection and RTCDataChannel are missing some methods defined in the dart:html spec. These issues do not occur when using dart2js. On a blank page, this code will fail when compiled with DDC:

```dart
var pc = new RtcPeerConnection({
  "iceServers": [{"url": "stun:stun.l.google.com:19302"}]
}, null);
pc.onIceCandidate.listen((Event e){});
```
With the error `Cannot read property 'listen' of undefined`

This particular problem is fixed by including WebRTC's adapter.js polyfill (dart2js's HTML wrapper does not require it, so this is already a notable difference). However, that seems to merely kick the error down the line a bit, since the following code fails no matter what:

```dart
var pc = new RtcPeerConnection({
  "iceServers": [{"url": "stun:stun.l.google.com:19302"}]
}, null);
var dc = pc.createDataChannel("files");
dc.onOpen.listen((Event e){});
```

Again with the same error about the event stream being undefined.

From digging around in the Chrome inspector, it appears the Dart runtime thinks `dc` is a generic HTML EventHandler class, not an instance of RTCDataChannel (which inherits from EventHandler). No data channel methods (send() or close()) are callable in Dart, although they do show up in the web inspector so they are properties of the object that Dart is wrapping.

# Does this error show up at build time or at run time?
Only shows up at runtime, no errors or warnings during build. Also, the dart2js build works fine.

# Include repro instructions. How can we try to build (or run) this code?
See the two above examples, you can run those in an empty Dart project with just a 'dart:html' import. I tested it in Chrome 54 although I doubt any browser will have the correct behavior.

Adapter.js is located at https://github.com/webrtc/adapter/blob/master/release/adapter.js

**Comment by jacob314** [comment]
Good news is this issue is fixed with Chrome 55 which is now the stable.
The nice thing about DDC is as browsers handle web standards better DDC gets better.

**Comment by jacob314** [comment]
https://codereview.chromium.org/2596143002/ verifies that the RTC behavior you wanted to use works.
