### ISSUE TITLE
IntelliJ and dartanalyzer fail to recognize syntax error using '=' instead of ':' for named parameter default

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/sdk#27948]
IntelliJ and dartanalyzer don't show errors when '=' is used instead of ':' to specify the default value of a named parameter. It fails in [dartpad](https://dartpad.dartlang.org/01d2f29d425b359b8dff377abca6fff5), and at runtime.

```
void example(int x, {String foo= 'defaultfoo'}) {
  print('x: $x, foo: $foo');
}
void main() {
  example(17);
  example(99, foo: 'hi');
}
```

**Comment by devoncarew** [comment]
Possibly a regression? I don't see a warning in the latest sdk (`1.21.0`) - DartPad is based on `1.19.0`.

**Comment by zoechi** [comment]
The syntax was changed recently to allow `=` to allow the same syntax as for default values for optional positional parameters. https://github.com/dart-lang/sdk/issues/27637

**Comment by alexander-doroshko** [comment]
I confirm that it's not an issue with IntelliJ 2016.3 and Dart SDK 1.12

**Comment by devoncarew** [comment]
> The syntax was changed recently to allow 

Thanks!
