### ISSUE TITLE
Doc comment for `TypeInterface.interfaces` is misleading

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#27947]
The [doc comment](https://github.com/dart-lang/sdk/blob/cec2a1cab24c5cf9e50a1387d7eee0021aa035b1/pkg/analyzer/lib/dart/element/type.dart#L350) states that *all* interfaces implemented are returned. I think it should be updated to read that *declared* interfaces are returned with an expanded description of what this means. As it reads today I would expect it to match the behavior of an `is` check, but it does not.

In the latest dev sdk the interfaces for `List` went from `[Iterable, EfficientLength]` to `[EfficientLengthIterable]` and this was a breaking change for us because we were depending on this call to return a list containing `Iterable`. We need to do extra work to verify that `Iterable` is in the transitive set of interfaces.

**Comment by srawlins** [comment]
There is no longer a TypeInterface class. :(
