### ISSUE TITLE
Deep type inference bug

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/sdk#27954]
```dart
Set<Set<int>> ssi() => ssd();
Set<Set<dynamic>> ssd() => new Set.from(new Set.from(["string"]));
```
works fine and causes runtime errors, but
```dart
Set<int> si() => sd();
Set<dynamic> sd() => new Set.from(["string"]);
```
fairly produces `WARNING: Unsound implicit cast from Set<dynamic> to Set<int>`?

**Comment by jmesserly** [comment]
hi, thanks for the report!

I'm not sure I understand what the bug is. Could you explain what you expect to happen?

Note that `Set<T>.from` takes an `Iterable`, not an `Iterable<T>`: https://api.dartlang.org/stable/1.20.1/dart-core/Set/Set.from.html so it will not cause inference to happen on that array type (`["string"]` will be a `List<dynamic>`).

**Comment by Adamovskiy** [comment]
Sorry for extra complicated example, it turned that problem is more general:
```dart
Set<Set<dynamic>> a;
Set<Set<int>> b = a;
````
unsafe cast, no warning.

**Comment by zoechi** [comment]
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```
![image](https://cloud.githubusercontent.com/assets/405837/20916400/e99cd93e-bb8b-11e6-9b61-94081defde20.png)

**Comment by Adamovskiy** [comment]
@zoechi thank you, did not expect that it is turned off by default.

**Comment by jmesserly** [comment]
fair point! DDC will do a runtime check. I do wonder if we should have a composite downcast warning here? @vsmenon @leafpetersen  .... the cast is from `Set<Set<dynamic>>` to `Set<Set<int>>`

**Comment by jmesserly** [comment]
yeah I think you're right there's a bug here. This feels odd:
```dart
Set<Set<dynamic>> a;
Set<Set<int>> b = a; // no warning

Set<dynamic> c;
Set<int> d = c; // warning
```

**Comment by vsmenon** [comment]
The intent of that "composite downcast" warning was to warn on an implicit cast that would always succeed in non-strong mode but potentially (probably?) fail in strong mode at runtime.

So, yeah, the lack of warning feels like a bug to me.

**Comment by leafpetersen** [comment]
I think --no-implicit-casts is the right solution here, probably not worth putting more effort into refining the off-by-default downcast composite warnings now.
