### ISSUE TITLE
Please merge revision 40bf5d321ea22fd9813d344ca2a0b06de5ec9784 into dev channel

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#27955]
@whesse @mit-mit @kasperl

This support `dynamic` as type argument to a generic method invocation, for instance `m<dynamic>()`.

Revision to merge: 40bf5d321ea22fd9813d344ca2a0b06de5ec9784

This merged cleanly

**Comment by whesse** [comment]
Merged in version 1.21.0-dev.11.2
