### ISSUE TITLE
DDC not properly handling functions with universal types

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27952]
The following test should print `42`.  Instead, it prints:
```
Closure: (Object) -> JSObject<undefined> from: o => T.as(a)
```

Here's the test:

```dart
h/*<T>*/(a) {
  return a as dynamic/*=T*/;
}

Object foo(f(Object a), Object a) {
  return f(a);
}

void main() {
  var x = foo(h, 42);
  print(x);
}
```

**Comment by leafpetersen** [comment]
This CL from @jmesserly resolves this issue:

https://codereview.chromium.org/2540903003/

**Comment by jmesserly** [comment]
that CL landed. We should also fix runtime checks on the DDC side, if they aren't already fixed.

**Comment by leafpetersen** [comment]
Closing.

**Comment by jmesserly** [comment]
thanks for trying that out! it looks like we still haven't implemented correct RTTI here (based on the `JSObject<makeGenericFnType>`) so I've opened https://github.com/dart-lang/sdk/issues/28079
