### ISSUE TITLE
Undefined type parameter when not specified in new

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/sdk#27953]
Assignment of new instance of class with type parameter in case of parameter specified for variable, but not specified for constructor, does not causes "Unsound implicit cast" error in strong-mode, using type parameter in constructor or via .. also looks like it was inferenced. But inside this object its type is dynamic:
```dart
class Foo<T> {
    Foo();
    Foo.from(T t);
    void use(T t) {}
    void printType() => print(T);
}

Foo<String> a = new Foo(); // Ok
Foo<String> b = new Foo.from(10); // Ok: analyze error
Foo<String> c = new Foo()..use(10); // Ok: analyze error

void main() {
    a.printType(); // dynamic
    b.printType(); // dynamic
    c.printType(); // dynamic
}
```

**Comment by floitschG** [comment]
How do you execute the program?
So far, only DDC uses the inferred types at runtime.

**Comment by Adamovskiy** [comment]
Just `pub serve`/`pub build` with `dart_to_js_script_rewriter` (I suppose it means no DDC). In fact, analyzer's ability to force use of `new Foo<String>()` form would help here.

**Comment by munificent** [comment]
I think the real issue may be that dart2js does not yet support reifying type arguments that were filled in by inference.

**Comment by sigmundch** [comment]
Correct - strong mode is currently only supported in analyzer + DDC. When dart2js accepts strong mode it will also be able to adapt the inferred types. At that point the reified type will be consistent with what you expect.

**Comment by matanlurey** [comment]
Dart2JS supports this in Dart2
