### ISSUE TITLE
Mixin application classes need to be decorated with libraries

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#27957]
In `ClassFinalizer::ResolveMixinAppType`, mixin application superclass types and mixin class types are resolved (correctly).  Then a mixin application class name is constructed from the raw names of these classes, and a class with this name is looked up (by name!) in the library of the mixin application and used if found.

This disregards that any of the involved classes can have the same name as a class from another library.  For example:

```dart
// superclass1.dart
library superclass1;

class Superclass {
  void m() { print('Superclass1'); }
}
```

```dart
// superclass2.dart
library superclass2;

class Superclass {
  void m() { print('Superclass2'); }
}
```

```dart
import 'superclass1.dart' as s1;
import 'superclass2.dart' as s2;

class Mixin {}
class C1 = s1.Superclass with Mixin;
class C2 = s2.Superclass with Mixin;

main() {
  var c1 = new C1(), c2 = new C2();
  c1.m();
  c2.m();
}
```

Will print 'Superclass1' twice but should print 'Superclass1', 'Superclass2'.  Similar things would happen if the mixin classes had a name collision.

**Comment by crelier** [comment]
Thanks for the report!

I guess an easy fix would be not to reuse application classes (no lookup by name). Otherwise, we need to somehow encode the libraries in the name.

@mhausner what do you think?

**Comment by crelier** [comment]
https://codereview.chromium.org/2540323005/ is out for review.

**Comment by mhausner** [comment]
The fix looks good.
