### ISSUE TITLE
Implement generic function type syntax in the analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27969]
This is the analyzer-implementation issue for #27527.

At the moment we only really need the new syntax in typedefs. Eventually, we want to make this syntax usable for fields and locals, but it's not yet as high a priority. If you find the time to make it work there too, please guard it behind a (different) flag.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec i linked from the meta-issue https://github.com/dart-lang/sdk/issues/27527

**Comment by kevmoo** [comment]
@bwilkerson is cranking on it

**Comment by jmesserly** [comment]
@bwilkerson happy to take a look at continuing this one through resolution (I noticed you already landed the parser/AST support?)

**Comment by bwilkerson** [comment]
Yes, the parser/AST support is in, but there is a flag in the parser that disables it. We can't re-enable it until 1.22 has built, which will make it hard to test any resolution work.

That said, I'm happy to let you finish the work. I had already started working on resolution when we decided to move the support from 1.22 to 1.23, and I've sent you a CL with what I'd gotten done.

**Comment by mit-mit** [comment]
The branch is open for 1.23, so would be good to get this one moving again!

**Comment by bwilkerson** [comment]
Yep. The next step was committed yesterday, but had to be temporarily reverted because of a problem with the way dartk was being built. I believe that's been fixed, so I'm planning on re-landing it today.

**Comment by mit-mit** [comment]
@bwilkerson was this landed?

**Comment by bwilkerson** [comment]
Unfortunately, no. It is requiring more effort than I had originally anticipated.

**Comment by dgrove** [comment]
Any further updates? Is this likely to make it for 1.23?

**Comment by bwilkerson** [comment]
I have a CL that I will commit in the morning that gets the shared tests to pass. At that point I'll probably consider this issue to be closed, and we can open individual issues as we discover specific cases that aren't yet working.

**Comment by bwilkerson** [comment]
Not all the tests are passing; I missed the ones in language-strong. Will look at those today.

**Comment by bwilkerson** [comment]
I was wrong, all of the tests I know of related to generic function types appear to be passing. (The others were related to generic methods and my changes happened to have fixed a couple of those cases.) Hence, I'm going to close this and expect to see other issues opened as specific problems are discovered.

**Comment by floitschG** [comment]
The analyzer still crashes on the generated tests.

Try to patch in https://codereview.chromium.org/2707033004 to have more tests.

**Comment by bwilkerson** [comment]
Are the generated tests not run on the bots?

**Comment by floitschG** [comment]
Not yet.

**Comment by leafpetersen** [comment]
Filed two specific issues here:

https://github.com/dart-lang/sdk/issues/29236
https://github.com/dart-lang/sdk/issues/29237

**Comment by leafpetersen** [comment]
git cl patch 2707033004 seems to work.

**Comment by leafpetersen** [comment]
https://github.com/dart-lang/sdk/issues/29360

**Comment by mit-mit** [comment]
#29360 is being merged. Anything else we need, or can we close this one?

**Comment by bwilkerson** [comment]
The analyzer passes all known tests, including the generated tests. I'm going to close this and request that any newly discovered deficiencies of the implementation be opened as new issues and *not* be assigned to the 1.23 milestone.
