### ISSUE TITLE
Generic local functions are not parsed correctly by the analyzer

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27965]
```
main() {
  local<T>(){ print("foo"); }
  local<List>();
}
```
VM is fine with this program, but analyzer reports a bunch of issues (SDK 1.21.0-dev11.1)

**Comment by mit-mit** [comment]
Looks like this landed; can we resolve this?

https://github.com/dart-lang/sdk/commit/b4820d6a631496afe42d61a7e6e9ffe46711447e

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2551533002/
