### ISSUE TITLE
Improve docs on Map.keys() and Map.values()

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#27968]
https://api.dartlang.org/stable/1.20.1/dart-core/Map/keys.html
https://api.dartlang.org/stable/1.20.1/dart-core/Map/values.html

Are these snapshots of the map, or are they views on the map (i.e. will changes to the underlying map be reflected in the iterable)?

**Comment by sethladd** [comment]
cc @lrhn

**Comment by tvolkert** [comment]
From the top-level docs: "Modifying the map while iterating the keys or values may also break the iteration."

Didn't see that until @Hixie pointed it out though, as I was looking in the method-level docs -- we should reiterate the behavior in the method docs.

**Comment by sethladd** [comment]
PR submitted: https://github.com/dart-lang/sdk/pull/27972
