### ISSUE TITLE
Implement generic function type syntax in dart2js

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27967]
This is the dart2js-implementation issue for #27527.

At the moment we only really need the new syntax in typedefs. Eventually, we want to make this syntax usable for fields and locals, but it's not yet as high a priority. If you find the time to make it work there too, please guard it behind a (different) flag.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec i linked from the meta-issue https://github.com/dart-lang/sdk/issues/27527

**Comment by floitschG** [comment]
Was reverted. Targetting 1.23 now.
