### ISSUE TITLE
Implement generic function type syntax in the VM.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27966]
This is the VM-implementation issue for #27527.

At the moment we only really need the new syntax in typedefs. Eventually, we want to make this syntax usable for fields and locals, but it's not yet as high a priority. If you find the time to make it work there too, please guard it behind a (different) flag.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec i linked from the meta-issue https://github.com/dart-lang/sdk/issues/27527

**Comment by mit-mit** [comment]
@a-siva FYI for assignment

**Comment by a-siva** [comment]
CL being code reviewed (https://codereview.chromium.org/2643523002/)
