### ISSUE TITLE
Implement generic function type syntax in DDC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27971]
This is the DDC-implementation issue for #27527.

At the moment we only really need the new syntax in typedefs. Eventually, we want to make this syntax usable for fields and locals, but it's not yet as high a priority. If you find the time to make it work there too, please guard it behind a (different) flag.

See #27969 for the analyzer issue.

**Comment by jmesserly** [comment]
FYI -- I'm not sure we will need to do any changes at all to DDC, as we already support universal function types, so fixing Analyzer side should give this to us for free.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec i linked from the meta-issue https://github.com/dart-lang/sdk/issues/27527

**Comment by vsmenon** [comment]
@floitschG are there tests for this?

Once #27969 is done, we should sanity check that those tests pass in DDC.  I don't think there is anything else to do.

**Comment by jmesserly** [comment]
@vsmenon I just remembered we two bugs related to universal functions, however they exist with or without the explicit syntax support: https://github.com/dart-lang/sdk/issues/28105, https://github.com/dart-lang/sdk/issues/28079

**Comment by vsmenon** [comment]
Marking this as done on the DDC side - I don't anticipate any work beyond the analyzer issue and the bugs Jen referenced.

**Comment by jmesserly** [comment]
Reopening. Discovered DDC does not support the syntax due to introduction of a new Analyzer AST node (rather than implement it purely using the existing types).
`Unimplemented GenericTypeAliasImpl: typedef T2T = T Function<T>(T t)`

**Comment by jmesserly** [comment]
I'm working on this now, though.

**Comment by jmesserly** [comment]
i've got a CL with syntax support working, however we still need proper runtime representation and subtype checks for strong mode (see https://github.com/dart-lang/sdk/issues/28079)
