### ISSUE TITLE
Request to add generic methods to the Language Tour

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#27975]
https://www.dartlang.org/guides/language/language-tour doesn't seem to have generic methods.

The 1.21 changelog mentions it support generic methods. https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

Here is the "information specification" : https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c

Thanks!

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/site-www#181
