### ISSUE TITLE
Observatory port display improvements

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#27977]
*Isolate Summary*
- Display pending message count next to isolates.

*VM port map and message handler*
- List of Port IDs that are owned by a message handler.
- Display native message handlers along side isolate message handlers
- Display message queue sizes

**Comment by johnmccutchan** [comment]
@a-siva

**Comment by rmacnak-google** [comment]
For message queues, we'll want both the number of pending messages and the combined size of the pending messages.
