### ISSUE TITLE
Please merge revision #24ffedcef0a6661b3de31867780b33b8c179d69c into the current release channel

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27980]
@whesse @mit-mit @kasperl
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
https://github.com/dart-lang/sdk/issues/27974

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
24ffedcef0a6661b3de31867780b33b8c179d69c

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
This merged cleanly

**Comment by whesse** [comment]
Merged in 1.21.0-dev.11.3.
