### ISSUE TITLE
Implicit cast WhereIterable to List without warning

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/sdk#27984]
Even in strong mode result of `Iterable#where()` (instance of `WhereIterable`) can be used as `List` without any warning, but with runtime exceptions, cause it has no `List`-specific methods (like work with indexes) in case of dart2js, or assigning to variable of type `List` in DartVM:
```dart
List<int> notList = [1,2,3].where((_) => true); // exception in DartVM
print(notList.indexOf(2)); // exception in browser
```
We have a lot of such bugs in our project - it is really easy to forget to call `toList()` after `where()`.

**Comment by zoechi** [comment]
I copied your code into a dart file in my project and got

![image](https://cloud.githubusercontent.com/assets/405837/20875200/1faa8356-bab9-11e6-9cee-485db43543d2.png)

You might want to add to `.analysis_options`

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**Comment by bwilkerson** [comment]
@leafpetersen @jmesserly

**Comment by Adamovskiy** [comment]
@zoechi thank you, did not expect that it is turned off by default.
