### ISSUE TITLE
Please merge revision ab6bc6dbfd7bcadfddd6b312926590f6dd832267 into the current release channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27981]
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
#27760
#27957

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
https://github.com/dart-lang/sdk/commit/ab6bc6dbfd7bcadfddd6b312926590f6dd832267

https://github.com/dart-lang/sdk/commit/3276a2ea26d67f251f9cc3b42a71a58e82c313cc

@kevmoo @mit-mit

**Comment by whesse** [comment]
Merged in 1.21.0-dev.11.3.
