### ISSUE TITLE
VM doesn't send isolate exit event when last isolate action is to throw.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27990]
Example:
```dart
import "dart:async" show Timer;
import "dart:isolate" show Isolate, RawReceivePort;

main() {
  Isolate.spawn(spawnMain, null,
                paused: true, errorsAreFatal: false).then((i) {
    var port = new RawReceivePort();
    port.handler = (msg) {
      if (msg is List) {
        print("Error: ${msg[0]}");
      } else {
        print("isolate terminated: $msg");
        port.close();
      }
    };
    i.addOnExitListener(port.sendPort, response: "right answer!");
    i.addErrorListener(port.sendPort);

    i.resume(i.pauseCapability);
  });
}

spawnMain(_) {
  for (int i = 0; i < 5; i++) {
    Timer.run(() {
      throw "Error $i";
    });
  }
  // Timer.run(() {});
}
```
Running this code on the VM prints five errors and then hangs. If I remove the comment before the last `Timer.run` call, it correctly prints five errors and then prints `isolate terminated: ...` and exits.

That means that the "isolate exit" message isn't sent. It seems to only happen when the last action of the isolate was to throw.

It's not clear whether it's because the spawned isolate doesn't actually exit, or because it forgets to send the message, in either case it's wrong.

**Comment by a-siva** [comment]
#28039

**Comment by a-siva** [comment]
#[https://github.com/dart-lang/sdk/issues/28050](url)

**Comment by natebosch** [comment]
This does not repro for me on the 2.0 SDK.
