### ISSUE TITLE
Migrate strong mode version of tests from pkg/dev_compiler to tests

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27992]
We should move these files out so that kernel and other tools can use them for testing strong mode.  On the DDC side, we'll need to patch:
- test/codegen_test.dart
- test/not_yet_strong_tests.dart (should this be moved / modified?)
- test/browser/language_tests.js (if the names are changed from "corelib" to "corelib_strong")

**Comment by munificent** [comment]
Done: https://github.com/dart-lang/sdk/commit/6c757957db8c31969c8a4c7b6e1693e1d93555bf
