### ISSUE TITLE
Update dart2js status for Chrome 55

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27991]
The buildbots have updated to Chrome 55, and some tests have started failing.  Please look at these, triage, and create issues for them.  Then update the status files to turn the columns green.

The columns affected by the update are:
https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-1-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-2-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-3-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-4-4-be

https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-chrome-be

https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie10chrome-1-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie10chrome-2-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie10chrome-3-4-be
https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie10chrome-4-4-be

**Comment by sigmundch** [comment]
I submitted a CL updating the status. 

Bill - I recall you mentioned the logs for the bots should be accessible via GCS? what's the right way to do so?

I think for these kind of updates (e.g. a browser update), we need to automate as much as possible the status updates, otherwise we waste too much time on this.

**Comment by whesse** [comment]
The buildbot logs are available at two places: from the buildbot server, and from cloud storage.  If you click on a particular build, like https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-1-4-be/builds/3178 , you can see two links on most lines, the second one in brackets.  That second one is to the browser of the cloud storage logs.  The logs are available through APIs, they aren't just up there as files.  Details of programmatic access are at https://luci-logdog.appspot.com/app/

**Comment by sigmundch** [comment]
Thanks Bill - I'll follow up on email with some questions.
