### ISSUE TITLE
Some broken links in the Analyzer docs

### ISSUE THREAD

**Issue by kulshekhar** [dart-lang/sdk#27994]
- Broken link to `element model` In the first paragraph [here](https://www.dartdocs.org/documentation/analyzer/0.29.1/analyzer.dart.ast.ast/analyzer.dart.ast.ast-library.html)
- Broken link to `AST structure` and `type.dart` in the first and second paragraphs respectively [here](https://www.dartdocs.org/documentation/analyzer/0.29.1/analyzer.dart.element.element/analyzer.dart.element.element-library.html)

I came across just these but there might be more.

**Comment by srawlins** [comment]
Fixed.
