### ISSUE TITLE
Specify FutureOr<T>

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28007]
This is the spec issue for https://github.com/dart-lang/sdk/issues/28006

The meaning of `FutureOr<T>` should be specified for
- [x] 1.50
- [x] strong mode.

**Comment by dgrove** [comment]
@floitschG can you please provide an update?

**Comment by floitschG** [comment]
I'm not aware of any progress.

**Comment by mit-mit** [comment]
Informal specification: https://gist.github.com/lrhn/d6815f9556acb3dc8f91d2c680ea0e54

**Comment by eernstg** [comment]
`FutureOr` has been specified in the language specification as of 90dc2101a6e2b4ddd5cc5839925773ed2fda3e5f.
