### ISSUE TITLE
Isolate.terminateCapability is not correct

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28003]
The [description of Isolate.terminateCapability](https://api.dartlang.org/stable/1.20.1/dart-isolate/Isolate/terminateCapability.html) reads:

> Capability terminateCapability
> read-only
> Capability granting the ability to terminate the isolate.
> 
> This capability is used by kill and setErrorsFatal. If the capability is not the correct termination capability of the isolate, including if the capability is null, then calls to those methods will have no effect.

It is not clear how to use this property or how `kill` use it. Besides the property is read-only, so there is no way to change it or make invalid.
Probably, the property is set by `kill` and `setErrorsFatal`?

**Comment by lrhn** [comment]
The property final and is set by the `Isolate` constructor. It never changes.

You can create `Isolate` instances without the terminate capability. This allows you to pass references to your isolate to somebody else to inspect, without leaking the ability to terminate the isolate.

I'll see if I can make the documentation clearer.

**Comment by lrhn** [comment]
I have landed some improved documentation, I hope it makes things a *little* clearer.
