### ISSUE TITLE
Allow pub server to run a secure connection / pub serve fails if HTTP Strict Transport Security (HSTS) is enabled

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28001]
E.g. with python you can specify a certfile and a keyfile then it runs a secure connection
```python
    import http.server
    import socketserver
    import ssl

    PORT = 7000

    # 0.0.0.0 allows connections from anywhere
    httpd = http.server.HTTPServer(('0.0.0.0', PORT), http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./jetty.crt', keyfile='./jetty.key', server_side=True)

    print("serving at port", PORT)
    httpd.serve_forever()
```

We need something like this for pub (and also for tests via content-shell or dartium)

**Comment by MikeMitterer** [comment]
If HTTP Strict Transport Security is enabled on the server side the server tells the client to switch to https - if pub server cannot handle this request it brings a 404

**Comment by MikeMitterer** [comment]
It's quite annoying! I have to turn off https on the server side because pub is not able to serve a secure connection.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1484
