### ISSUE TITLE
Support FutureOr<T> in DDC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28009]
This is the DDC issue for #28006

`FutureOr<T>` is the union of `Future<T>` and `T`.

**Comment by jmesserly** [comment]
yay! I don't think we'll need to do much besides ensure we handle this in our runtime subtype relation & can reify it appropriately.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec is linked from #28006

**Comment by jmesserly** [comment]
CL out https://codereview.chromium.org/2647833002/
