### ISSUE TITLE
Support FutureOr<T> in the analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28008]
This is the analyzer issue for https://github.com/dart-lang/sdk/issues/28006

There are two cases for the analyzer:
1. in non strong-mode `FutureOr<T>` should be treated as `dynamic`.
2. in strong-mode `FutureOr<T>` is the union of `Future<T>` and `T`.

**Comment by jmesserly** [comment]
yay! 🎉 

I think the following is needed for Analyzer:
- [ ] in non-strong mode treat it as dynamic
- [ ] remove magic fakes this type for Future.then
- [ ] remove Future flattening
- [ ] remove the places we flatten away FutureUnion (e.g. InferenceContext getType, StrongInferenceTypeSystem._infer)
- [ ] make sure this type is correctly handled by strong mode's LUB/GLB/subtype relation (IIRC it is at least partially implemented)
- [ ] is anything for type promotion needed?

@leafpetersen or others, feel free to add anything I missed to above list

**Comment by leafpetersen** [comment]
I believe that eliminating Future flattening should be done separately (and after), since it will be a migration process (we will need to eliminate all of the places that it is explicitly used).

We have an informal spec that describes type promotion, LUB/GLB etc.  We will share it for feedback shortly.

**Comment by jmesserly** [comment]
thanks. I've removed the bullet about Future flattening, we'll keep that around for now

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec is linked from #28006

**Comment by jmesserly** [comment]
here's the spec: https://gist.github.com/lrhn/d6815f9556acb3dc8f91d2c680ea0e54

**Comment by jmesserly** [comment]
Analyzer fix is ready (https://codereview.chromium.org/2647833002) still working on DDC support (https://github.com/dart-lang/sdk/issues/28009) which is needed for that CL to be sent out.

**Comment by devoncarew** [comment]
Hey Jen - checking on 1.22 issues - do you have an approx. eta for this? Thanks!

**Comment by bwilkerson** [comment]
@jmesserly ping

**Comment by jmesserly** [comment]
I was out sick Friday. I'm picking it back up today.
