### ISSUE TITLE
FunctionElementImpl.computeNode() doesn't work when two functions are on the same line

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#28017]
Found using this source code in a test:

"foo(x,y,z) => null;"
"match(a) => foo(a,1,2);"

In the test, both function elements appeared to point to the node of the first function. Adding a newline after the first semicolon fixes it.

I'm suspecting an off-by-one error in NodeLocator?

**Comment by srawlins** [comment]
This bug certainly is stale.
