### ISSUE TITLE
analyzer should warn about missing returns in blocks

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#28018]
https://dartpad.dartlang.org/538e83c288c48522186c9272c23c3aff

```
void main() {
  // Blocks defined with {} need a return statement.
  List<int> foo = [1,2].map((int i) {
    i + 1; // Analyzer should warn here!
  }).toList();
  print('$foo');

  // => doesn't need a return, this will work fine.
  List<int> bar = [1,2].map((int i) => i + 1).toList();
  print('$bar');
}
```

Output:
```
[null, null]
[2, 3]
```

This came up due to:
http://stackoverflow.com/questions/41008787/tabbarselection-no-such-method-error

**Comment by eseidelGoogle** [comment]
https://github.com/dart-lang/sdk/issues/26554 may be related?

**Comment by bwilkerson** [comment]
Yes, I think the two issues are asking for the same thing, so I'm going to close this one.
