### ISSUE TITLE
'Target of URI does not exist' doesn't show up with --enable-new-analysis-driver (IDEA only)

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#28016]
To reproduce, I created a trivial project with one file that contains:

```
import 'asdf.dart';
```

When using Atom and --enable-new-analysis-driver, I see this error:
Target of URI doesn't exist: 'asdf.dart'.foo.dart, line 1

If I create a new IDEA project for the same file, I don't see this error. Instead I see:
INFO: Unused import. (foo.dart:1)

If I remove --enable-new-analysis-driver in the IDEA registry and restart analysis server, then I do see the error. (And after putting the flag back, it is gone again.)

So, it appears there is some interaction between IDEA and --enable-new-analysis-driver that prevents 'Target of URI doesn't exist' from showing up, but it doesn't happen with Atom?

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Does your Analysis Server version include 4bc3ecd650109562efda1f610a243fc3b629ef4e?

I suspect that Atom might not actually use `--enable-new-analysis-driver`.

**Comment by alexander-doroshko** [comment]
My observation: bleeding-edge SDK does highlight 'Target of URI does not exist' error with new analysis driver. SDK 1.21-dev reports unused import instead.

**Comment by scheglov** [comment]
Thank you for confirming that it works, Alex.

The new analysis driver is targeted for `1.22`.

**Comment by skybrian** [comment]
I upgraded to Paul's latest build and it works now.

(For Atom, it is logging the --enable-new-analysis-driver flag so I know the analysis server is getting it.)
