### ISSUE TITLE
Typo in num.== operator documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28019]
See https://api.dartlang.org/stable/1.20.1/dart-core/num/operator_equals.html

> If you can avoid NaN values, the remaining doubles do have a proper eqality relation, and can be used safely.

Note ...**eqality**...

**Comment by lrhn** [comment]
Some documentation is more eqal than other.
Good catch :)

**Comment by lrhn** [comment]
Fixed. Thanks.
