### ISSUE TITLE
Please, improve description for Isolate.current

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28021]
The [description for static property Isolate.current](https://api.dartlang.org/stable/1.20.1/dart-isolate/Isolate/current.html) reads:

> Isolate current
> Return the current Isolate.
> 
> The isolate gives access to the capabilities needed to inspect, pause or kill the isolate, and allows granting these capabilities to others.

The word current is vague and confusing. For example, I have started two isolates, which one is considered as current? Please, add some definition of `current`

Also it worth to mention whether this property can be null.

**Comment by lrhn** [comment]
We generally don't specify that something can't be null, we only say if it can be null. When we say that this is an isolate instance, it means that it isn't null.

Will work on describing what "current" means.

**Comment by lrhn** [comment]
Have updated documentation.
