### ISSUE TITLE
Analyzer: Core libraries sometimes seem "double" imported...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28023]
Resulting in errors like:

```
ERROR: Element 'List' from SDK library 'core.dart' is implicitly hidden by 'core.dart'.
```

It's not cleanly reproducible but it does happen from time to time.

**Comment by kulshekhar** [comment]
I can confirm seeing this today. I never encountered this before the latest update. I'm running `Dart VM version: 1.21.0-dev.11.3 on "linux_x64"`.

Reloading the editor (VS Code) made this go away.

**Comment by matanlurey** [comment]
Ping, it looks like this occurring a lot more than I thought:

https://github.com/dart-lang/sdk/issues/14158#issuecomment-269394969

/cc @patkujawa-wf

**Comment by eseidel** [comment]
When the analyzer gets into this state for me it's no longer giving me other useful errors, just these bogus ones.

**Comment by MikeMitterer** [comment]
I have the same one:

```ERROR: Element 'String' from SDK library 'core.dart' is implicitly hidden by 'core.dart'. ([mobiad_rest_ui_mdl_mmui_media_sample] web/main.dart:547)```

![capturfiles-20170130_012631](https://cloud.githubusercontent.com/assets/116654/22423021/ea7136e0-e6ef-11e6-94cf-463555005320.png)

**Comment by jimmyff** [comment]
I'm getting this too.

> Element 'print' from SDK library 'core.dart' is implicitly hidden by 'core.dart'

**Comment by jsiedentop** [comment]
I've got the same error. I could solve it by commenting an import out (once 'dart:io' and the other time 'dart:async'). I believe, it was not necessary wich one I've choose. I think by changing the an import, the analyzer refreshed the whole file. My SDK Version was 1.22.1 (actual sdk in stable channel).

**Comment by patkujawa-wf** [comment]
I rely on the analyzer as it's used in PyCharm (likely the same for all JetBrains IDEs), and I've found that cutting and pasting the line that the error points too causes the analyzer to re-evaluate and fix itself (maybe not every time, but I think quite often). However, it's often easier to just kill and restart the analyzer or restart pycharm.

**Comment by matanlurey** [comment]
I haven't seen this in ~6 months, so closing.
