### ISSUE TITLE
Move Null to the bottom in the Analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28027]
This is the analyzer issue for #28024

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation

**Comment by kevmoo** [comment]
Still on for 1.22

**Comment by scheglov** [comment]
https://codereview.chromium.org/2638183002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/0160332713fb955916deac2b216f2e872f3b479b
