### ISSUE TITLE
Add FutureOr<T> to the core libraries

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28029]
This is the library implementation issue for https://github.com/dart-lang/sdk/issues/28006

We believe that a `class` is the easiest to deal with. Dartdocs, navigation, completion, ... should just work.

``` dart
/// The union of `Future<T>` and `T`.
///
/// This is a magic class that is recognized by our tools. It is used in places where 
/// functions accept a `Future<T>` and a `T`.
///
/// Note: this type is interpreted as `dynamic` in non strong-mode.
class FutureOr<T> {
  FutureOr._();  // Add private constructor, so that it is not subclassable and instantiable.
}

**Comment by munificent** [comment]
Does this issue also track updating the rest of the core libraries to use `FutureOr<T>` in places like `Future.then()`?
