### ISSUE TITLE
Move Null to the Bottom (VM)

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28025]
This is the VM issue for https://github.com/dart-lang/sdk/issues/28024

From what I can see, this should only affect `is` checks and function types:

`List<Null> is List<A>` should return `true` (especially in checked mode).

`(A a) => ...`  should be a subtype of `Function(Null)`

**Comment by a-siva** [comment]
@crelier

**Comment by lrhn** [comment]
This is a Gist of our discussion/design document: https://gist.github.com/lrhn/c8cd36899c44c45c14a7786105132066

The tl;dr is to just treat `Null` as a subtype of other types in
* Generic type parameters: `List<Null>` is-a `List<int>`.
* Function types: `int Function(int)` is-a `int Function(Null)`

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation

**Comment by crelier** [comment]
I'm reading the design document above and notice some missing type arguments in this paragraph, probably due to some missing code formatting:

> This makes a difference where we have composite types. A List is-not-a List and a (int)→int function is-not-a (Null)→int function, even though they *could *be - they are extensionally compatible but not compatible in the type system.

I suppose you meant: `List<Null> is-not-a List<int>`

**Comment by lrhn** [comment]
Good catch, (all?) formatting issues should be fixed now so all type parameters are visible.
