### ISSUE TITLE
Heap snapshot tree expansion fails to load

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#28031]
In a Flutter application (take hello world), grab a heap snapshot and then start expanding the [x] box on some rows. It quickly stops functioning. I suspect that we've exhausted the ID ring space. This makes the heap snapshot unusable for Flutter applications.

**Comment by johnmccutchan** [comment]
@rmacnak-google @a-siva @turnidge

**Comment by johnmccutchan** [comment]
I think the right fix is:

1) Force tenure all objects before constructing a heap graph.
2) For old-space objects, don't use the ObjectIdRing and instead use some combination of the raw object address + cid for the id. For example: '/direct/<memory_address>/<cid>'

Looking up the object, we can then scan the page containing 'memory address' and only return the object if there is an object starting at that memory address with the cid.

**Comment by rmacnak-google** [comment]
Addressed by the use of a virtual table for the display, which greatly reduced pressure on the object id ring.
