### ISSUE TITLE
BazelPackageUriResolver shouldn't assume third_part/dart layout

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#28038]
Today the analyzer will go into `Bazel` mode if it sees a `blaze-genfiles` or `bazel-genfiles` directory, but that mode assumes all pub packages live at `third_party/dart/$package` in the main repo.

For external users this is not generally the case, instead local bazel repositories are used which are at a different path. This means that analysis server reports all `package:` imports as missing today in the external world (at least for users of the [bazel](https://github.com/dart-lang/bazel) dart package).

P.S. One more [use case](https://youtrack.jetbrains.com/issue/WEB-24605): `package:` imports become red in a standard Dart app if `WORKSPACE` file is there in a parent folder.

**Comment by bwilkerson** [comment]
Where are they located in the external case?

**Comment by natebosch** [comment]
Today they're located in the same place they would be without bazel. We can use `.packages` to know the paths.

It's a relatively safe assumption that even if we pick different locations for bazel dependencies we'll be able write a `.packages`

**Comment by bwilkerson** [comment]
So, just to make sure I'm understanding, if we first look for a .packages file and only build a BazelPackageUriResolver when one isn't found, we should be doing the right thing?

**Comment by jakemac53** [comment]
We won't be able to see generated files that way, but it would be a step in the right direction for now.

**Comment by natebosch** [comment]
Long term we may want to consider extending `.packages` to allow multiple paths per package.

**Comment by kevmoo** [comment]
> Long term we may want to consider extending .packages to allow multiple paths per package.

Uh...that's a bit scary. We should figure out how to teach the analysis server (generally) how to map a non-bazel path to its associated gen file location

**Comment by natebosch** [comment]
Multiple paths in `.packages` let's us keep the implementation details separate which will be useful if we decide to change how packages are laid out.
We could potentially have a file with a relative path per package and a list of roots instead

**Comment by bwilkerson** [comment]
So, back to the short term, we need to look for a .packages file and use the content of that file to try to resolve the URI first, then fall back to what we do today in order to find generated packages?

**Comment by natebosch** [comment]
Yes, that sounds good in the short term.

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by kevmoo** [comment]
This completely borks our bazel workflow

![screen shot 2017-02-06 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/17034/22673021/66968198-ec8c-11e6-9e0e-68d8956454ba.png)
![screen shot 2017-02-06 at 4 49 48 pm](https://cloud.githubusercontent.com/assets/17034/22673024/68e59010-ec8c-11e6-91a1-52a98bd7829d.png)

**Comment by skybrian** [comment]
What does your bazel repo look like? Where are there .packages files?

**Comment by kevmoo** [comment]
I have a `.packages` in the root of the repo. Right next to `WORKSPACE`.

**Comment by skybrian** [comment]
Is this how we expect open source Bazel users to do it, normally? Everything shares a common .packages file?

**Comment by kevmoo** [comment]
> Is this how we expect open source Bazel users to do it, normally? Everything shares a common .packages file?

Good question. Initially, we expect most folks to have one Dart project per WORKSPACE. This means the .packages file will be at the root.

We're not investing time (yet) into folks building out projects that look anything like our internal setup.

**Comment by natebosch** [comment]
For the alpha version of bazel integration we expect everyone to have a single `.packages` file.
We will have to solve the problem of where to find generated files at some point, but we could potentially get by without it for now.

**Comment by bwilkerson** [comment]
This CL (https://codereview.chromium.org/2681153002/) should take care of the case where there's a .packages file. Let me know when there's a concrete plan for handling generated files.

**Comment by kevmoo** [comment]
The fix – https://github.com/dart-lang/sdk/commit/f364eb1ab8820b0e4d0d604ce9b91e9723a9071e – landed in `1.23.0-dev.0.0`

I'm running `1.23.0-dev.0.0` now – and still seeing the issue.
![screen shot 2017-02-20 at 3 59 56 pm](https://cloud.githubusercontent.com/assets/17034/23145761/a98a0610-f785-11e6-99ef-751d538e0394.png)

**Comment by bwilkerson** [comment]
Can you point me to the sample project so that I can reproduce the bug?

**Comment by kevmoo** [comment]
- Sync down pop-pop-win https://github.com/dart-lang/sample-pop_pop_win/tree/sdk28038
- check out the `sdk28038` branch
- `pub get`
- `pub run dazel init`

This should create a WORKSPACE file in the root of the package directory.

Open intelliJ.

I guess you could just add a WORKSPACE file to the root of any package and see what happens.

**Comment by bwilkerson** [comment]
I wasn't able to get bazel installed, so I couldn't `pub run dazel init`. So instead I created an empty file name "WORKSPACE" in the root of the checkout. I opened it in IntelliJ and there are no errors. What am I missing?

**Comment by jakemac53** [comment]
Try adding a `bazel-genfiles` or `bazel-bin` folder instead? I think that
is actually what the analyzer is using to switch modes, not the WORKSPACE
file.

**Comment by bwilkerson** [comment]
It uses either "READONLY" or "WORKSPACE" (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/bazel.dart#L256).

**Comment by bwilkerson** [comment]
I don't know how to fix this issue unless I can reproduce it.

**Comment by kevmoo** [comment]
Just updated with `Dart VM version: 1.23.0-dev.1.0 (Sun Feb 19 20:50:00 2017) on "macos_x64"` – seems fixed.

Will close and reopen if I see it again.

Thanks!
