### ISSUE TITLE
Dartium doesn't write to stdout or stderr on Windows

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28034]
On Linux, Dartium prints some information to its standard IO streams, including which Observatory ports it's bound for each page. The `test` package relies on this information to determine the Observatory URL and remote debugging URL when running tests, and other automation tools may use it too.

I can force Dartium to log to stdout by passing `--enable-logging=stderr`. This is a usable workaround, but it behaved the same way across operating systems by default.

**Comment by terrylucas** [comment]
Will not fix.
