### ISSUE TITLE
Weird errors with dart2js and checked mode with functions and Object arguments

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28045]
With dart2js & checked mode, I get the following exception when running the code at the bottom:

```
Uncaught Error: type 'constructor' is not a subtype of type '(($int, String) -> void) -> void'
    at Object.wrapException (js_helper.dart:1730)
    at RuntimeFunctionType._check$2 (js_helper.dart:3538)
    at RuntimeFunctionType._assertCheck$1 (js_helper.dart:3521)
    at Object.main (game_web.dart:3)
    at iterable.dart:276
    at init.currentScript (iterable.dart:276)
    at iterable.dart:276
    at iterable.dart:276
wrapException @ js_helper.dart:1730
_check$2 @ js_helper.dart:3538
_assertCheck$1 @ js_helper.dart:3521
main @ game_web.dart:3
(anonymous) @ iterable.dart:276
init.currentScript @ iterable.dart:276
(anonymous) @ iterable.dart:276
(anonymous) @ iterable.dart:276
```

```dart
void main() {
  doWeird(oneArgFunc);
  print('works');
  doWeird(oneArgFuncWeird);
  print("don't get here");
}

oneArgFunc(arg) => null;

oneArgFuncWeird(Object arg) => null;

doWeird(OnHijackCallback callback) => null;

typedef void OnHijackCallback(HijackCallback callback);

typedef void HijackCallback(int stream, String sink);
```

CC @rakudrama

**Comment by kevmoo** [comment]
Currently this is breaking `pkg/shelf` tests when run w/ dart2js.

**Comment by kevmoo** [comment]
FYI @sigmundch – this breaks with the latest `pkg/test` `expectAsyncN` methods – I'm guessing we'll see a LOT of folks hit this.

**Comment by kevmoo** [comment]
Recent changes to make pkg/test strong-mode clean have raised this issue.

**Comment by sigmundch** [comment]
So it appears the issue was that we weren't checking that functions are subtypes of object. Funnily this doesn't come up that easily because the compiler optimizes away checks like `is Object`, so you need these nested scenarios to reproduce it.

Note that you can also see this issue without check mode by doing `is` checks on typedefs. For example:
```dart
typedef void T(void callback());
void m(Object arg) {}
main() => print('${m is T}');
```

incorrectly prints `false`.

CL https://codereview.chromium.org/2599073002/ is out for review
