### ISSUE TITLE
Support for incremental kernel files so it is possible to do incremental compilation using the new Dart Front end

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28052]
Support for incremental kernel files so it is possible to do incremental compilation of flutter sources that have changed and push the generated intermediate files to the device.

#28051 is dependent on this feature.

Discussion:

Status: on the Kernel team's road map (and OKRs) for Q4. Kernel already supports separate compilation at the library level. A kernel binary can contain external libraries that do not have implementations but a list of required members. On the kernel_sdk fork we already had a hybrid mode where some libraries were compiled from binary and some (the SDK libraries) were assumed to exist. (They were compiled from source, but that's not important here. They can just as easily be compiled from a separate binary.)

For the hot reload scenario, we will want to rely on the existing hot reload support in the VM as much as it makes sense.

**Comment by a-siva** [comment]
@kmillikin

**Comment by kmillikin** [comment]
We're starting on this: the VM will have a binary for the `dart:` core libraries and the front-end will only send over the application (and a patch to `_getMainClosure` in `dart:_builtin`).  @jensjoha

**Comment by mraleph** [comment]
Related issue: #29172

**Comment by a-siva** [comment]
This issue can be closed as done right? I believe support having incremental kernel files exists.
