### ISSUE TITLE
Support for core snapshots in the Dart binary when using kernel so we do not go through the corelib bootstrapping process on startup

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28056]
Currently we always start an isolate by reading a kernel file that has information about all the core libraries and information about the application script. We should retain the notion of starting up from a snapshot of the core libraries and load only the kernel file associated with the application on startup.

**Comment by a-siva** [comment]
Lazy finalization of classes is being worked on as part of this effort to generate core snapshots when running with kernel.

**Comment by dgrove** [comment]
@a-siva do you need this prior to Dart2 Stable?

**Comment by a-siva** [comment]
This can be done only when we deprecate Dart1 from the VM, otherwise we end up with multiple snapshots making the executable big. Do we want to link Dart2 stable with Dart1 deprecation, probably not, maybe we could have a milestone 'DeprecateDart1' and move this under that bucket.

**Comment by dgrove** [comment]
I'd like to link Dart2 Stable with Dart1 deletion (if we decide that's infeasible, we can create a new milestone).

**Comment by mraleph** [comment]
Request for clarification: I thought we are deprecating the core snapshots - and instead use Kernel as a replacement? or are we planning to still support the snapshotting but only use it for core libraries?

**Comment by rmacnak-google** [comment]
We do start isolates from a core snapshot containing kernel. Fixed many months ago.
