### ISSUE TITLE
Core libraries still use generic methods comment-based syntax

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28060]
I noticed that our core libs still use the comment-based syntax for generic methods. Not sure if that's intentional? See https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/iterable.dart#L157

I wanted to see how Dart uses generic methods to teach myself. Perhaps others will, too?

Thanks!

**Comment by lrhn** [comment]
See: https://codereview.chromium.org/2529393002/
It might be triggering some problems with dart2js mirrors, so it's not landed yet.

**Comment by matanlurey** [comment]
:-/ It would have been nice to get this in the same release as the generic method feature.

**Comment by sethladd** [comment]
Thanks for the update, @lrhn

**Comment by srawlins** [comment]
This has landed.
