### ISSUE TITLE
Add ability to load the dart front end using an application snapshot

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28065]
Generate an application snapshot of dart front end when we generate the core library snapshot and load this into the kernel isolate during VM start up. This should shave the time used for compiling sources when executing the dart front end.

**Comment by rmacnak-google** [comment]
We should consider doing this for the service isolate as well.

**Comment by mhausner** [comment]
@rmacnak-google has implemented this in 9eb216a495f8917ba1bcc55d2555d8203a76c09f

**Comment by a-siva** [comment]
Did we figure out if we were going to link in the snapshot into the executable or leave it as a file in the sdk directory?
