### ISSUE TITLE
Ensure all source level debugging works without regressions when in kernel mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28063]
- Evaluation of expressions when in a debugger currently uses the VM parser, we need to use the kernel isolate for expression evaluation.

- Come up with a scheme for referring to the source files which were used to generate the kernel files

- Kernel does a lot of de-sugaring of the sources to make things easier in the backend.
  - We need to investigate the effect of this on source level debugging, notables cases which need
  - investigation and fixing if need be are
  - async single stepping (step over, step into, step out etc.)
  - async stack traces 
    Discussion:
    ==> Debugging is only in terms of the original source. The intermediate outputs of transformations just do not exist as Dart code at a URI.
    ==> Transformations around async await statements will need to support source level debugging.

**Comment by kmillikin** [comment]
We're still missing an implementation of expression evaluation, which is issue #31755.  I'll close this one but please reopen more fine-grained issues if there are other missing features or improvements.
