### ISSUE TITLE
Documentation List.sublist(start, [end]) issue with the end equal to start

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28074]
Please see List.sublist documentation (https://api.dartlang.org/stable/1.21.0/dart-core/List/sublist.html)

> Returns a new list containing the objects from start inclusive to end exclusive.

But what if start equals to end? Then, according to the text above, the value should be included (as start) and excluded (as end) at the same time.
The current behaviour returns an empty list in this case.  I believe this is ok, just add it to the documentation

**Comment by lrhn** [comment]
Ack, the usual problem of not having defined what a "range" is, so we have to rewrite the inclusive/exclusive thing everywhere, and remember handle the empty case.

**Comment by eernstg** [comment]
The interpretation that I would consider natural is that the included objects are the ones whose indices are greater-equal than `start` and less than `end`. Maybe we could just use that wording?: 'Returns a new list containing the objects whose indices are greater-equal than `start` and less than `end`, preserving their order.'

**Comment by lrhn** [comment]
Yes, I was thinking something like that too. It's always a question about how precise one should be vs. readability. Maybe " ... containing exactly the elements at indices .... ".
(I don't want to talk about the "index of an object" since the same object can occur more than once, so object/element at an index is better).

**Comment by hooluupog** [comment]
Hi, not only the "startIndex equals to endIndex" description is confusing me,but also this sentence "a new list containing the objects " is confusing.Does the sublist just a reference to the origin list or a new created list(with new memory allocation)?
 Quoting the JavaDoc of `List.subList(int, int)`:
>Returns a **view** of the portion of this list between the specified fromIndex, inclusive, and toIndex, exclusive. (**If fromIndex and toIndex are equal, the returned list is empty**.) **The returned list is backed by this list**, so non-structural changes in the returned list are reflected in this list, and vice-versa. The returned list supports all of the optional list operations supported by this list.

IMO,The description from JavaDoc is accurate and intuitive despite somewhat verbose.
