### ISSUE TITLE
Killing an isolate doesn't kill its unshared server sockets

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28081]
When I kill an isolate, I'd expect any `ServerSocket`s it's created to be closed (unless those sockets are marked as shared). This would match the behavior of killing a Dart process. Instead those sockets seem to remain open without any way of interacting with them.

For example:

```dart
import 'dart:async';
import 'dart:io';
import 'dart:isolate';

main() async {
  var rp = new ReceivePort();
  print("spawning isolate");
  var isolate = await Isolate.spawnUri(new Uri.dataFromString(r"""
    import "dart:async";
    import "dart:io";
    import "dart:isolate";

    main(_, SendPort port) async {
      var socket = await ServerSocket.bind("localhost", 0);
      print("bound server socket");
      socket.listen(null);
      port.send(socket.port);
    }
  """), [], rp.sendPort);

  var port = await rp.first;
  print("connecting client socket");
  var socket = await Socket.connect("localhost", port);
  socket.listen(null, onDone: () => print("socket closed"));

  print("killing isolate");
  isolate.kill();
}
```

I'd expect this to print "socket closed", but it never does.

**Comment by kevmoo** [comment]
@lrhn @floitschG could one of ya'll take a look at this?

**Comment by zoechi** [comment]
Sounds similar to #27898

**Comment by lrhn** [comment]
@sgjesse for possible insights.

**Comment by zanderso** [comment]
The VM registers weak persistent handles on the Dart objects with native fields that wrap C++ wrappers around file descriptors for files and sockets (and a few other things). See, e.g.:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/file.cc#L72

and after the change referenced above:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/socket.cc#L984

When the Dart objects are GC'd the finalizers registered with the handles close the file descriptors, either directly in the case of files, or indirectly through the event handler in the case of sockets.

The specific case that @lrhn mentions, in which the event handler or IO service opens a file or socket but the requesting isolate is killed before the native wrapper object and the finalizer can be set up, is probably the only remaining situation where we may still leak a file or socket. Something relatively simple like setting up the native wrapper objects before sending the requests to the event handler and IO service would probably be sufficient, though.

**Comment by franklinyow** [comment]
@lrhn 
Please re-evaluate this and do one of the following:

1. Add it to a milestone if it is still P1
2. Change priority label and add milestone if no longer P1
3. Close, if this issue is no longer needed

**Comment by aam** [comment]
This is no longer seems to be a problem:

```
import 'dart:async';
import 'dart:io';
import 'dart:isolate';

child(SendPort port) async {
  var socket = await ServerSocket.bind("localhost", 0);
  print("bound server socket");
  socket.listen(null);
  port.send(socket.port);
}

main() async {
  var rp = new ReceivePort();
  print("spawning isolate");
  var isolate = await Isolate.spawn(child, rp.sendPort);

  var port = await rp.first;
  print("connecting client socket");
  var socket = await Socket.connect("localhost", port);
  socket.listen(null, onDone: () => print("socket closed"));

  print("killing isolate");
  isolate.kill();
}
```

```
─➤  xcodebuild/ReleaseX64/dart isolate-socket.dart                                                                                                                                                               spawning isolate
bound server socket
connecting client socket
killing isolate
socket closed
^C
```
