### ISSUE TITLE
Performance of command line dart with new front-end running dart programs is acceptable

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28088]
@mhausner @a-siva @sigmundch Please populate this issue with performance targets for specific benchmarks.

**Comment by zanderso** [comment]
Friendly ping. Please fill in targets here. @johnmccutchan

**Comment by johnmccutchan** [comment]
```
$ time dart hw.dart
hello world

real	0m0.139s
user	0m0.130s
sys	0m0.035s
```

**Comment by fsc8000** [comment]
More importantly, larger apps should perform equally well:
```
$ time out/ReleaseX64/dart-sdk/bin/dart2js ~/examples/hello.dart 

real	0m0.553s
user	0m0.506s
sys	0m0.233s
```

**Comment by johnmccutchan** [comment]
@fsc8000 I agree your number is better.

**Comment by johnmccutchan** [comment]
Here is dart2js being run from source:

```
$ time ./out/ReleaseX64/dart pkg/compiler/lib/src/dart2js.dart ~/hw.dart 

real	0m2.518s
user	0m3.010s
sys	0m0.463s
```

**Comment by rmacnak-google** [comment]
#28585 (Kernel front-end increases memory footprint by over 5x)

**Comment by mraleph** [comment]
I am closing this issue as not actionable. We are in progress of switching irrespective of current performance characteristics - which means we deemed the performance acceptable.
