### ISSUE TITLE
FutureOr not visible in dartium drt

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28084]
For some reason, the VM can't see the type `FutureOr` that has been added to `dart:async`.

Affected tests:
```
python tools/test.py -mrelease -rdrt -t240 lib/async/future_or_bad_type_test/implements
python tools/test.py -mrelease -rdartium -t240 lib/async/future_or_bad_type_test/implements
```

It turns out that the test is negative, and drt/dartium now accidentally pass, but that shouldn't be the case.

**Comment by terrylucas** [comment]
@a-siva

Siva should FutureOr work in the VM?
