### ISSUE TITLE
@JS("JSON.parse") annotation gives me exceptions (I'm new)

### ISSUE THREAD

**Issue by hydroper** [dart-lang/sdk#28085]
I'm following [Web Libraries](https://webdev.dartlang.org/guides/web-programming) at [js 0.6.1 | Pub Package Manager page](https://pub.dartlang.org/packages/js).

**Test input**

(module.dart)
```dart
import 'dart:html';

@JS("JSON.stringify") // The issue is here.
external String stringify(obj);

void hello() {
  window.alert('test');
}
```

(main.dart)
```dart
import './module.dart';

void main() {
  hello();
}
```

**Expected behavior:** No compilation errors.

**Actual**

(module.dart exceptions)
```
Ln.: 3 — Cannot resolve 'JS'.
Ln.: 3 — Not a compile-time constant.
Ln.: 3 — Not a compile-time constant² (same column.).
Ln.: 1 — Invalid @JS(...) annotation.

The compiler is broken.
```

**Comment by ds84182** [comment]
You forgot to import the js package in module.dart with:

`import "package:js/js.dart";`

Dart also has built-in support for encoding JSON. [Check the dart:convert library docs for more info](https://api.dartlang.org/stable/1.20.1/dart-convert/dart-convert-library.html).

**Comment by hydroper** [comment]
@ds84182 Thanks! I've not found any advice on this import. I was just testing it
