### ISSUE TITLE
Create transformer for switch statements with continue

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#28080]
If I have the code:

```dart
main() {
  int x = 2;
  switch (x) {
    a: case 1:
      print('1');
      break;
    case 2:
      print('2');
      continue a;
  }
}
```

then `dartk` outputs

```
static method main() → dynamic {
  core::int x = 2;
  #L1:
  switch(x) {
    #L2:
    case 1:
      {
        core::print("1");
        break #L1;
      }
    #L3:
    case 2:
      {
        core::print("2");
        continue #L2;
      }
  }
}
```

But in JavaScript, you can't have a `continue` inside of a `switch statement`. We need a transformation that takes the above code and returns something like:

```dart
main() {
  int x = 2;
  var target;
  case (x) {
    case 1: target = 1; break;
    case 2: target = 2; break;
  }
  l: while (true) {
    switch (target) {
      case 1:
        print('1');
        break l;
      case 2:
        print('2');
        target = 1;
        continue l;
    }
  }
}
```

**Comment by lrhn** [comment]
You can only use case expressions that are numbers, strings, or don't override Object.operator== (aka, uses identical), so just `var target = x;` should be sufficient.

Bonus points for putting case 1 after case 2 and having the continue work by fall-through :)

**Comment by efortuna** [comment]
I'm going to say this is much less necessary now that I've implemented the complex switch statement: https://codereview.chromium.org/2648443004/ Shall we close this?

**Comment by mraleph** [comment]
@efortuna @hterkelsen ping. Is this still an active issue?

**Comment by hterkelsen** [comment]
Let's close this since @efortuna implemented complex switch
