### ISSUE TITLE
Performance of initial load and startup of a flutter app with the new front-end

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28089]
and typical edit/refresh cycle.

@mhausner @a-siva @sigmundch @johnmccutchan Please populate this issue with performance targets for specific benchmarks.

**Comment by johnmccutchan** [comment]
Data from the Flutter performance bots shows that starting the Flutter Galley application from source takes ~4500 milliseconds.

**Comment by mraleph** [comment]
Flutter has been switched to the Dart 2 pipeline.
