### ISSUE TITLE
Isolate.addOnExitListener() throws exception on invalid response argument

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28094]
The [description for method Isolate.addOnExitListener()](https://api.dartlang.org/stable/1.21.0/dart-isolate/Isolate/addOnExitListener.html) reads:

> void addOnExitListener(
> SendPort responsePort, {
> Object response
> })
> Asks the isolate to send response on responsePort when it terminates.
> ...
> If the isolate is already dead, no message will be sent. **If response cannot be sent to the isolate, then the request is ignored.** It is recommended to only use simple values that can be sent to all isolates, like null, booleans, numbers or strings.

However the following sample code shows that invalid response value causes an exception to be thrown instead of being ignored.

```dart
import "dart:isolate";
import "dart:async";

void entryPoint(message) {
  new Future.delayed(new Duration(minutes:2)).then(() => print("Isolate finished"));
}

main() async {
  Isolate isolate = await Isolate.spawn(entryPoint, null);
  ReceivePort onExit = new ReceivePort();
  isolate.addOnExitListener(onExit.sendPort, response:onExit);
}
```

Output:

> λ d:\dev\dart\dart-sdk\bin\dart  test3.dart
> Unhandled exception:
> Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
> #0      Isolate._sendOOB (dart:isolate-patch/isolate_patch.dart:484)
> #1      Isolate.addOnExitListener (dart:isolate-patch/isolate_patch.dart:511)
> #2      main.<main_async_body> (file:///D:/dev/dart/co19/LibTest/isolate/Isolate/test3.dart:11:11)
> #3      _RootZone.runUnary (dart:async/zone.dart:1404)
> #4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
> #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
> #6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
> #7      _Future._complete (dart:async/future_impl.dart:467)
> #8      _SyncCompleter.complete (dart:async/future_impl.dart:52)
> #9      Isolate.spawn.<spawn_async_body> (dart:isolate-patch/isolate_patch.dart:339)
> #10     _RootZone.runUnary (dart:async/zone.dart:1404)
> #11     _FutureListener.handleValue (dart:async/future_impl.dart:131)
> #12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
> #13     _Future._propagateToListeners (dart:async/future_impl.dart:667)
> #14     _Future._complete (dart:async/future_impl.dart:467)
> #15     _SyncCompleter.complete (dart:async/future_impl.dart:52)
> #16     Isolate._spawnCommon.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:438)
> #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Dart VM version: 1.21.0 (Wed Dec 07 06:52:21 2016) on "windows_x64"

**Comment by alsemenov** [comment]
I think, the description of the method should be changed to match it behavior. Otherwise there is no way to understand whether the method completed successfully or just silently ignored the input. Besides, there is no strict definition of which values are ignored and which not. Therefore different platform may accept/ignore different values, which makes the will lead the same code to fail on one platform and to succeed on another.

**Comment by alsemenov** [comment]
The same problem is observed in method Isolate.ping()

**Comment by floitschG** [comment]
Started a CL: https://codereview.chromium.org/2634353002/
