### ISSUE TITLE
Out of memory issues when running dartk in batch mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28096]
Our buildbots are running dartk in batch mode and the `--mode=debug --compiler=dartk --runtime=vm` is very flaky. It often runs out of memory.

Example is (from [buildbot failure](https://build.chromium.org/p/client.dart/builders/vm-kernel-linux-debug-x64-be/builds/255/steps/vm%20tests/logs/stdio)):
```

FAILED: dartk-vm debug_x64 co19/LibTest/collection/ListQueue/ListQueue_class_A01_t01
Expected: Pass 
Actual: DartkCrash
Unexpected compile-time error.
CommandOutput[dartk]:

stderr:
Exhausted heap space, trying to allocate 16 bytes.


Command[dartk]: DART_CONFIGURATION=DebugX64 tools/dartk_wrappers/dartk --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/tests/co19/src/LibTest/collection/ListQueue/ListQueue_class_A01_t01.dart --sdk out/DebugX64/patched_sdk --link --target=vm --out /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/dartk/tests_co19_src_LibTest_collection_ListQueue_ListQueue_class_A01_t01/out.dill
Took 0:00:01.385131

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/dartk/tests_co19_src_LibTest_collection_ListQueue_ListQueue_class_A01_t01/out.dill
Did not run

Short reproduction command (experimental):
    python tools/test.py -cdartk -t120 co19/LibTest/collection/ListQueue/ListQueue_class_A01_t01
```

/cc @kmillikin @mraleph @asgerf

**Comment by mkustermann** [comment]
Do you think someone from the analyzer team might be able to help? Since it makes our builders flaky it would be nice if we could find a good owner for this issue.

**Comment by mraleph** [comment]
Can runner detect OOM errors of the batch mode dartk and simply retry the test at least once?

**Comment by mkustermann** [comment]
Yes, we can re-run on dartk crashes. Here's a [CL](https://codereview.chromium.org/2576693002/) but that will also re-try on normal compiler crashes (and test.py annoyingly will print things to stdio in case of retries).

But this should not close this issue, because the dartk batch runner shouldn't OOM.

**Comment by asgerf** [comment]
Some objects from the analyzer AST and element model seem to be retained between runs. I can't get observatory to show the retaining path for these objects, so the question of how they are retained is still at large - it could be either dartk or analyzer that is at fault.

**Comment by mraleph** [comment]
This is obsolete with a switch to Fasta + Front-End Isolate model.
