### ISSUE TITLE
analyzer error when overriding generic method

### ISSUE THREAD

**Issue by Bluenuance** [dart-lang/sdk#28093]
```

abstract class A {
  T add<T extends num>(T first, T second);
}

class B extends A {
  double add<double>(double first, double second) {
    return first + second;
  }
}
```

gives me:
ERROR: The operator '+' isn't defined for the class 'Object'.

**Comment by lrhn** [comment]
You aren't actually doing what you thing you are doing here.
When you write
```
double add<double>(double first, double second) {
```
you are declaring a method that takes a type argument. The type parameter is named `double` and it shadows the `double` type from `dart:core`. Basically, it's exactly the same as:
```dart
T add<T>(T first, T second) {
```
The analyzer correctly warns you that the `+` operator isn't defined for all allowed types that `T` can represent.

**Comment by Bluenuance** [comment]
sorry but I don't get it, I mean in this example ok, but it was just some example to make it easier to understand...
now here from the real code base I have:

```
abstract class Matrix  {
  bool approximately<T extends Matrix>(T other, double delta);
}

class Matrix2 extends Matrix {
  @override
  bool approximately<Matrix2>(Matrix2 other, double delta) {
    for(int i = 0; i < storage.length; i++) {
      if ((storage[i] - other.storage[i]).abs() > delta) {
        return false;
      }
    }    
    return true;
  }
}
```

the Analyzer tells me:
"ERROR: The getter 'storage' isn't defined for the class 'Object'."
so he cannot infer that "other" is a Matrix2 but assumes it is an Object (even though the base class tells it extends Matrix)

**Comment by bwilkerson** [comment]
That's the same situation. I think you're thinking of
```
bool approximately<Matrix2>(Matrix2 other, double delta) {
```
as meaning "override the generic method `approximately`, but use `Matrix2` as the type for `T`, leaving me with a non-generic implementation". But what it really means is "override a generic method with another generic method, but in this generic method define to the type parameter to have the name `Matrix2`". What you wrote is equivalent to
```
bool approximately<S>(S other, double delta) {
```
The only difference between the method in `Matrix2` and the method in `Matrix` is that the subclass doesn't define a bound for the type parameter.

There is, unfortunately, no way to do what I think you're trying to do.

**Comment by lrhn** [comment]
There is no way to do it, nor should there be.

The superclass is specifying a generic method. Any class implementing the superclass should be usable in (at least) all the same ways as the superclass, that's what substitution is about.

If the subclass method isn't generic, then a program like:
```dart
Matrix x = new Matrix2();
x.approximately<Matrix3>(new Matrix3(), 0.5);
```
would look type-correct, but actually not be correct. If you can use `Matrix3` as a type parameter to the `approximately` method of a `Matrix`, you should be able to use it for *all* `Matrix` instances, also those that are `Matrix2`.

**Comment by Bluenuance** [comment]
thanks a lot for the detailed answers!
seems quite a lot of "unsafe" code slipped in without strong mode
