### ISSUE TITLE
Code completion is suggesting types that make no sense in context

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28108]
I'm using VSCode which I presume uses Analysis Server for all of its code completion.

I am adding code for `body` in a Flutter scaffold, which can/must be a Widget. Here is what I see:

![screen shot 2016-12-14 at 10 52 08 am](https://cloud.githubusercontent.com/assets/5479/21196169/8a524570-c1eb-11e6-8c55-c73e593d83c3.png)

I'm surprised I'm seeing Color as the first result, because that's not a widget and wouldn't work here.

Can we filter/sort on suggestions that are a subtype of the expected type?

**Comment by sethladd** [comment]
cc @lukechurch @scheglov

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/27688
