### ISSUE TITLE
Support generic methods in Kernel to IL translation

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28109]
We need to make decision about support for generic methods in Kernel to IL translation and either implement generic methods semantics or bump priority of type reification transformation.

A lot of code in the Kernel-to-IL translation can be made obsolete if we transform this stuff away before Kernel reaches VM.

**Comment by kasperl** [comment]
Let's bump the priority of the type reification transformation and keep this outside the VM.

FYI @karlklose @peter-ahe-google

**Comment by sjindel-google** [comment]
The type reification transformation has been abandoned, and this has been implemented in the VM.
