### ISSUE TITLE
Implement new strong mode instantiate to bound rules in analyzer

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28100]
This is the analyzer-specific tracking issue for #27526.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation per status update from @leafpetersen in email this this is ready.

**Comment by kevmoo** [comment]
Triag: still a go for 1.22

**Comment by scheglov** [comment]
Started implementing the [Proposal 2](https://github.com/dart-lang/sdk/issues/27526#issuecomment-260021397).

[The first step](https://codereview.chromium.org/2641213002/) is to report errors for type parameter bounds without required type arguments.

**Comment by scheglov** [comment]
[The second step](https://codereview.chromium.org/2640143007) - actual instantiate to bounds implementation.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/919d70d0cb99ea9d8cc9dcc4f41e6b7fd95be82d
