### ISSUE TITLE
Specify new strong mode instantiate to bound rules

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28101]
This is the language spec issue for #27526.

**Comment by dgrove** [comment]
@floitschG can this be assigned to the right person?

**Comment by eernstg** [comment]
We have a feature spec for this: [instantiate-to-bound.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md). It still remains to integrate this material into the [language specification](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex).

**Comment by eernstg** [comment]
No milestone now: Other issues of a similar nature have a milestone pertaining to the feature specification, but [instantiate-to-bound.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md) has been landed and is not expected to need updates.

**Comment by eernstg** [comment]
Closing: This feature has been made part of dartLangSpec.tex, with d118c7f94eeac2373ec583e9f69ef22c434fe744 as the last commit.
