### ISSUE TITLE
Support overriding fields in DDC

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28119]
This is the DDC part of meta-issue https://github.com/dart-lang/sdk/issues/28117.
https://github.com/dart-lang/sdk/issues/27385 tracks supporting this via an `@virtual` modifier, however the 1.50 design does not require such a modifier on field overrides.

**Comment by jmesserly** [comment]
DDC supports this once the fix lands for https://github.com/dart-lang/sdk/issues/27385

it's based on Analyzer marking fields as `isVirtual`, DDC itself doesn't use `@virtual`

so any change to Analyzer will be picked up by DDC (see https://github.com/dart-lang/sdk/issues/28120), it is unclear to me what the affect will be on internal code performance/size. Someone should try it out once fix lands for https://github.com/dart-lang/sdk/issues/27385

**Comment by vsmenon** [comment]
We need to ensure this does not regress large app experience for our customers before we drop the modifier.

**Comment by mit-mit** [comment]
> We need to ensure this does not regress large app experience for our customers before we drop the modifier.

@vsmenon what is the plan and schedule for that testing?

**Comment by vsmenon** [comment]
Once Jen's change lands internally, we will test the effect of marking all fields `isVirtual`/`@virtual` on code size and load time.

**Comment by mit-mit** [comment]
The fix [looks to be](https://github.com/dart-lang/sdk/blob/1.22.0-dev.2.0/pkg/dev_compiler/lib/src/compiler/class_property_model.dart) in 1.22.0-dev.2.0, let me figure out when that can be rolled.

**Comment by kasperl** [comment]
Can this be closed? If the analyzer marks fields as virtual as part of fixing #28120 there's no work to be done here, right?

**Comment by kasperl** [comment]
Who owns this, @vsmenon / @leafpetersen? This is blocking the 1.23 release so we need an owner now.

**Comment by kasperl** [comment]
This is the issue we talked about yesterday, @dgrove. It doesn't appear to have had an assignee ever.

**Comment by leafpetersen** [comment]
There was a request to use this bug for updates.  I have an AR to take measurements of the code size and latency cost for DDC of turning this on by default.  I've been pulled back into the internal roll today and likely will be tomorrow as well, so no progress to report.

**Comment by kasperl** [comment]
Proposed CL here: https://codereview.chromium.org/2691433004/.

**Comment by kasperl** [comment]
Blocked on #28809.

**Comment by vsmenon** [comment]
Our plan is to do #28801 to devirtualize most fields and treat the rest as virtual (i.e., what we were doing on `@virtual` but by default).  #28801 will assume #28809.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2781443003/
