### ISSUE TITLE
Incorret end value in RangeError.checkValidRange()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28116]
Please see https://api.dartlang.org/stable/1.21.0/dart-core/RangeError/checkValidRange.html. 

> Throws if the range is not valid for an indexable object with the given length. A range is valid for an indexable object with a given length
> 
> if 0 <= [start] <= [end] <= [length]

RangeError.checkValidRange() implementation is the following:
```dart
static int checkValidRange(int start, int end, int length,
                            [String startName, String endName,
                             String message]) {
  // Comparing with `0` as receiver produces better dart2js type inference.
  // Ditto `start > end` below.
  if (0 > start || start > length) {
    if (startName == null) startName = "start";
    throw new RangeError.range(start, 0, length, startName, message);
  }
  if (end != null) {
    if (start > end || end > length) {
      if (endName == null) endName = "end";
      throw new RangeError.range(end, start, length, endName, message);
    }
    return end;
  }
  return length;
}
```
If `start` value breaks the limits the `RangeError.range()` is thrown. 
First. `if (0 > start || start > length) {` Allowed value for start is 0 <= [start] <= [end]. There should be
`if (0 > start || start > end) {`

Second. `length` is used as a `maxValue` argument in `RangeError.range()` constructor call. But, again, maximum allowed value for `start` is `end`. So `end` should be used as a `maxValue` in `RangeError.range()` call

**Comment by lrhn** [comment]
This code is quite deliberate, and it works.

If `0 <= start <= end <= length` then it doesn't throw.
If any one of those requirements fail to be true, including the transitive `start <= length`, then it throws. 

It doesn't report all the possible errors, only the first one it finds, and it tries to do as few comparisons as possible. That is why it does all the start tests first and then checks if `end` is null. If `end` is indeed null, then the test is done. If we compared `start` to `end` first, then we had to do the `end == null` check even earlier.

So, there *is* a requirement that `start <= length`, and if the inputs fail that test, then something is *seriously* wrong. I think it's more important to report that problem than how it relates to the (probably also wrong) value for `end`.

A good optimizing compiler can turn a range check into a single comparison and jump. I'm hoping for that too! :)
