### ISSUE TITLE
`analysis.getNavigation` not implemented for the new driver?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28125]
When I try and navigate to declaration (in VSCode), I get no results:

```
1481860315804:Req:{"id"::"392","method"::"analysis.getNavigation","params"::{"file"::"/Users/devoncarew/projects/dartdoc/lib/src/markdown_processor.dart","offset"::1118,"length"::0}}
1481860315805:Res:{"id"::"392","result"::{"files"::[],"targets"::[],"regions"::[]}}
```

I do get results for IntelliJ for the same project and location; I expect that IntelliJ is using the navigation events for navigation information? VSCode is not - it is making explicit `analysis.getNavigation` calls each time.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2582753003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/eaca15cd4da4ac93ac26c5dc9b5b36a9138a5362
