### ISSUE TITLE
Analyzer, support overriding fields in strong mode

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28120]
This is the Analyzer part of meta-issue #28117.

Analyzer currently rejects an override with _"Field declaration [field] cannot be overridden in SubClass."_. This should be removed.

**Comment by leafpetersen** [comment]
This is blocked on resolution of finding an implementation strategy for DDC.

**Comment by bwilkerson** [comment]
> This is blocked on resolution of finding an implementation strategy for DDC.

Is there an issue tracking the need for this strategy? (More importantly, is someone working on developing the strategy?

**Comment by leafpetersen** [comment]
This is blocked on https://github.com/dart-lang/sdk/issues/28809, and probably https://github.com/dart-lang/sdk/issues/28801 .  Once those are resolved, we can flip the bit here.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2781443003/
