### ISSUE TITLE
Update core libraries to use FutureOr<T>

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28122]
Once it's available (#28006), we need to use it in places like `Future.then()`, etc.

**Comment by mit-mit** [comment]
@floitschG what is the status on this one?

**Comment by jmesserly** [comment]
oh shoot. I think this is blocked on Analyzer support: https://github.com/dart-lang/sdk/issues/28008, I'm working on that though. For strong mode it's probably best to fix them both in the same atomic CL--that way I can remove strong mode's FutureOrT hacks the same time as using them for real. Also will get better testing that it doesn't regress any existing Dart 1 code.

**Comment by jmesserly** [comment]
well, I'll fix at least ".then" because strong mode hard coded it, it may be best to leave the others (e.g. listed in https://gist.github.com/lrhn/d6815f9556acb3dc8f91d2c680ea0e54) to y'all

**Comment by mit-mit** [comment]
After discussion with Florian, moving this to 1.23. We will complete the language feature in 1.22 (bug https://github.com/dart-lang/sdk/issues/28006) and then have the core library usage of that follow in 1.23.

**Comment by jmesserly** [comment]
@mit-mit that sounds like a great idea.

**Comment by mit-mit** [comment]
@floitschG @jmesserly can we remove 'blocked' from this?

**Comment by jmesserly** [comment]
> @floitschG @jmesserly can we remove 'blocked' from this?

yup! it's unblocked now.

**Comment by dgrove** [comment]
Any updates here?
