### ISSUE TITLE
Chrome 56 will disable fetching scripts with invalid type/language attribute

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28124]
Not sure if this is how pkg/browser does things or what.

Seems critical to fix, though.

![screen shot 2016-12-15 at 2 20 03 pm](https://cloud.githubusercontent.com/assets/17034/21245786/7496b5e2-c2d9-11e6-9559-ef587f51275a.png)

**Comment by alan-knight** [comment]
It seems like this is not critical. Kevin investigated and as I understand it Chrome disallows the Dart script, but then successfully runs the appropriate JS. Kevin, if that's right can we close or downgrade this?

**Comment by kevmoo** [comment]
Seems like it. We need to ponder this RE future things. But for now seems
like we are good
