### ISSUE TITLE
Please, clarify description for Isolate.kill(): default value for parameter priority

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28132]
The [description for method Isolate.kill() ](https://api.dartlang.org/stable/1.21.0/dart-isolate/Isolate/kill.html)reads:

> void kill({
> int priority: BEFORE_NEXT_EVENT
> })
> Requests the isolate to shut down.
> 
> The isolate is requested to terminate itself. The priority argument specifies when this must happen.
> 
> The priority must be one of IMMEDIATE or BEFORE_NEXT_EVENT. The shutdown is performed at different times depending on the priority:

Since parameter `priority` is optional, it may be omitted. The method's behavior is not clear in this case. Please, clarify.

**Comment by lrhn** [comment]
The parameter has a documented default value of `Isolate.BEFORE_NEXT_EVENT`, so if the parameter is omitted, it will use that value. 
We usually don't repeat that information in the documentation - but perhaps we should.
