### ISSUE TITLE
js-interop: Interop not working on example case on Dartium

### ISSUE THREAD

**Issue by charlieyouakim** [dart-lang/sdk#28145]
I'm getting an info warning while adding your interop example with Stringify:
```
import 'dart:html';
import 'package:js/js.dart';

@JS("JSON.stringify")
external String stringify(obj);

void hello() {
  window.alert(stringify({'id': 1}));
{
```
```info: The @JS() annotation can only be used if it is also declared on the library directive.```

When I run the code and call hello elsewhere, the alert fails and I get the following error in the Dartium console:
```
EXCEPTION: NoSuchMethodError: No top-level method 'stringify' declared.
Receiver: top-level
Tried calling: stringify()
```
This happens in Dartium and works in Chrome.

dart v 1.21 on Mac
0.6.1 of js.dart

**Comment by zoechi** [comment]
As the error message says, the `@JS()` annotation is required on the library directive

```dart
@JS()
library my_project.stringify;

import 'dart:html';
import 'package:js/js.dart';

@JS("JSON.stringify")
external String stringify(obj);

void hello() {
  window.alert(stringify({'id': 1}));
{
```

or

```dart
```dart
@JS('JSON')
library my_project.stringify;

import 'dart:html';
import 'package:js/js.dart';

@JS()
external String stringify(obj);

void hello() {
  window.alert(stringify({'id': 1}));
{
```

**Comment by charlieyouakim** [comment]
Thank you!

**Comment by zoechi** [comment]
@charlieyouakim If this solves your issue, please consider closing the issue.

**Comment by charlieyouakim** [comment]
No error. Only issue now is the output is incorrect. Output is {} in Dartium. Should be {"I'd": 1}.

Should I create a new issue?

**Comment by a14n** [comment]
The output is correct. It's mentioned on the [js package README](https://pub.dartlang.org/packages/js) :

>you cannot simply pass a Dart Map object – they are "opaque" in JavaScript.

You have to use either an anonymous js Dart interface (a Dart class with both the `@JS()` and `@anonymous` annotations) or use `jsify({'id': 1})` with `import dart:js_util;`

**Comment by charlieyouakim** [comment]
Ah. It was written as to pass a Json object, but I can see the issue. Thank
you.
