### ISSUE TITLE
Update changelog wrt. configuration specific imports

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28140]
Configuration specific imports status (re https://github.com/dart-lang/sdk/issues/24581) needs an entry in changelog.md

**Comment by kevmoo** [comment]
There are still some open issues calling this "done" – let's hold off documenting it.

**Comment by mit-mit** [comment]
This will unfortunately not complete in 1.22 :-(. Moving to 1.23.

**Comment by dgrove** [comment]
Talking w/ @kevmoo , we're not going to be done with this feature for awhile. Let's remove this from the 1.23 milestone.

**Comment by srawlins** [comment]
I think this issue should be closed until we re-define this feature.
