### ISSUE TITLE
Error in rename refactoring

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28149]
I was attempting to rename a public instance method to be private and the following exception was thrown:

NoSuchMethodError:: The getter 'types' was called on null.
Receiver:: null
Tried calling:: types:#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::44)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::47)
#2      Search.classMembers.<classMembers_async_body> (package::analyzer/src/dart/analysis/search.dart::51)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart::async-patch/async_patch.dart::27)
#4      _rootRunUnary (dart::async/zone.dart::1158)
#5      _CustomZone.runUnary (dart::async/zone.dart::1037)
#6      _FutureListener.handleValue (dart::async/future_impl.dart::131)
#7      _Future._propagateToListeners.handleValueCallback (dart::async/future_impl.dart::637)
#8      _Future._propagateToListeners (dart::async/future_impl.dart::667)
#9      _Future._completeWithValue (dart::async/future_impl.dart::477)
#10     _Future._asyncComplete.<anonymous closure> (dart::async/future_impl.dart::528)
#11     _rootRun (dart::async/zone.dart::1150)
#12     _CustomZone.run (dart::async/zone.dart::1026)
#13     _CustomZone.runGuarded (dart::async/zone.dart::924)
#14     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::951)
#15     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#16     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#17     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::394)
#18     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#19     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)

**Comment by scheglov** [comment]
https://codereview.chromium.org/2613683005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/e6634d67f407e453f3b3944973de05f2d8718802
