### ISSUE TITLE
directory.renameSync() can produce non-deterministic OSError

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28147]
Consider the test in https://gist.github.com/tvolkert/94d03c6ccb20b7e85a23d6738c338e2a

Running that test via `pub run test` usually succeeds, yet occasionally, it produces a FilesystemException whose underlying OSError has the following messages instead of the expected "No such file or directory".

- OS Error: Undefined error: 0, errno = 0

In a similar (larger) test suite from which this sample was derived, I also witnessed the following OSErrors:

- OS Error: File exists, errno = 17
- OS Error: Not a directory, errno = 20
- OS Error: Directory not empty, errno = 66

While it always throws a FileSystemException, it's very disconcerting that the underlying OSError isn't deterministic and points to there possibly being a bug in the runtime.

This was observed on OS X 10.11.6.

**Comment by zanderso** [comment]
- You don't need to add any randomness to createTempSync(). It's already calling mkdtemp().
- It looks like we're calling stat() on the path for the directory, and if the path exists, checking if it's a directory. If it's not a directory, we generate an OSError, but sicne stat() succeded errno may not have a meaningful value. This means that the OSError will be created using whatever random thing errno was previously set to (supposing that stat doesn't set it on success, which it seems not to be doing.)

I'll come up with a fix.

**Comment by tvolkert** [comment]
re: the randomness, I'm not doing so in my real test - that's a remnant of my paranoia while testing this behavior. :-)
