### ISSUE TITLE
Strong mode error on super call for generic method with type bound

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28141]
I'm getting a static error on the call to `super.create` that `[error] 'S' doesn't extend 'T'`:

```dart
class A<T> {
  A<S> create<S extends T>() => new A<S>();
}

class B extends A {
  A<S> create<S>() => super.create<S>();
}
```

There is no `T` at that point (and to the extent there is, it's `dynamic`).

@leafpetersen

**Comment by jmesserly** [comment]
taking a look. probably a simple fix.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2653873002/
