### ISSUE TITLE
dart2js/kernel/impact_test times out in checked mode on vm

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28157]
The unit test for dart2js, tests/compiler/dart2js/kernel/impact_test.dart, now takes more than 4 minutes running on the vm in checked mode on our linux builders.

Running in unchecked mode it only takes 30 seconds on my local machine, versus 3 minutes 40 seconds for checked mode.

I will skip the test in checked mode in the status file.  If we can split the test, or make it faster, then we can run it again in checked mode.  It is already marked slow, which is why it is given 4 minutes, rather than 1 minute.  It is also fine to leave it as is, if it is important as a stress test.

**Comment by johnniwinther** [comment]
We don't run unittests in unchecked mode, so we currently never run this test.

**Comment by johnniwinther** [comment]
The test is partially reenabled in https://github.com/dart-lang/sdk/commit/b699aba744bf857d0187c7a5afc8e9c702e4d9db
