### ISSUE TITLE
Consider Dartdoc part of the declaration

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28151]
When I place the cursor somewhere inside a declaration in the editor pane, IntelliJ nicely selects the declaration in the outline pane. But if I place the cursor in the Dartdoc preceding a declaration, IntelliJ selects the containing element (for example, if the Dartdoc is on a method, IntelliJ selects the class). I would find it much more helpful if IntelliJ considered the Dartdoc to be part of the declaration and selected the declaration with which the Dartdoc is associated.

By the way, IntelliJ correctly considers annotations to be part of the declaration, but this leads to a small inconsistency. If the Dartdoc is before any annotations then you get the behavior described above, but if the Dartdoc follows one or more annotations then the Dartdoc is considered part of the declaration. I'm sure this is true of other kinds of comments as well, and you could consider solving the problem for all comments, but I don't really care about those cases.

**Comment by alexander-doroshko** [comment]
Moved to https://youtrack.jetbrains.com/issue/WEB-25496.

**Comment by bwilkerson** [comment]
Note that this could also be fixed by letting the plugin get outline information from analysis server, which already includes the comment in the range, rather than computing it yourself.

**Comment by alexander-doroshko** [comment]
Since 2017.3 Structure View is backed by the Analysis Server, so this issue has automatically become addressed.
