### ISSUE TITLE
Introduce generation of missing enums as quick fix

### ISSUE THREAD

**Issue by mosauter** [dart-lang/sdk#28154]
I suggest a "generate missing cases" quickfix would be cool 😃 

![image](https://cloud.githubusercontent.com/assets/9122366/21345260/c739638e-c69f-11e6-904f-83cb387d630a.png)

![image](https://cloud.githubusercontent.com/assets/9122366/21345118/293dd070-c69f-11e6-8fad-af59eb4abb93.png)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by srawlins** [comment]
This is also one of our more upvoted requests. I think I can take this on.

**Comment by srawlins** [comment]
Oops, there is already a "add missing case clauses" quick fix. I see it in VS Code and in IntelliJ. Marking this as complete.
