### ISSUE TITLE
language/assert_message_test fails on Dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28150]
The test language/assert_message_test is failing on Dartium and content_shell with compiler=none.

The failure is noted in tests/language/language.status.

**Comment by mhausner** [comment]
The failure is most likely that the test framework is not setting the required VM flag --assert-message. Without this flag, the test fails due to syntax errors.

**Comment by mhausner** [comment]
I'm removing the VM flag, so this failure will go away automatically.

**Comment by mhausner** [comment]
This is resolved with b7cb4095f1e52bf6ae0226c32c6019cf067b4b30
