### ISSUE TITLE
"WARNING: Unsafe use of a block closure in a type-inferred variable outside a function body."

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28159]
The fix is to add generics to the constructor `new StreamSinkTransformer.fromHandlers` but the message here does not help me understand that.

From `pkg/test`

```dart
/// A sink transformer that wraps data and error events so that errors can be
/// decoded after being JSON-serialized.
final _transformer = new StreamSinkTransformer.fromHandlers(
    handleData: (data, sink) {
      ensureJsonEncodable(data);
      sink.add({"type": "data", "data": data});
    }, handleError: (error, stackTrace, sink) {
      sink.add({
        "type": "error",
        "error": RemoteException.serialize(error, stackTrace)
      });
    });
```

CC @leafpetersen @stereotype441

**Comment by srawlins** [comment]
I can't recreate this locally with dummy `ensureJsonEncodable` and `RemoteException.serialize` and Dart 2.0.0-dev.6.0. Can you give a reproduction case, @kevmoo ?

**Comment by kevmoo** [comment]
This is a year old. Might could be fixed...

**Comment by kevmoo** [comment]
Perhaps due to top-level inference getting better? @leafpetersen ?

**Comment by stereotype441** [comment]
@kevmoo yes, the code to report that error was removed in 27ab6478b9072dfc7cabbc63a36dc3adef463998 as part of improvements to type inference.

Curiously, the error message itself lingers in the codebase, with nothing hooked up to it.  I'll clean it up shortly.

**Comment by natebosch** [comment]
We can't repro this error anymore and I can't find that error message with some initial grepping so I think this is resolved.
