### ISSUE TITLE
Support `covariant` marker in the analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28167]
This is the analyzer issue for #27486.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation

**Comment by kevmoo** [comment]
@munificent are you going to do this work for the analyzer?

**Comment by munificent** [comment]
No, I think @bwilkerson was planning on it. (I'm working on the reification of covariant tear-offs in DDC. Or at least, I will once we figure out what the types are supposed to be.)

**Comment by bwilkerson** [comment]
I believe that the parser work is complete, so the information should now be represented in the AST structure. I am making progress on the changes necessary to get the data into the element model.

**Comment by munificent** [comment]
Cool. Are you planning to publish a release of analyzer with this? How will be able to use it with dart_style?

**Comment by bwilkerson** [comment]
Yes. We plan to publish a 0.29.x release of analyzer that has support for both this and the temporarily postponed generic function type syntax. It won't actually parse either syntax, so you'll probably have to test dart_style against bleeding edge analyzer to ensure that it works when the syntax is actually used, but it will be forward compatible with bleeding edge analyzer. How soon do you need that?

**Comment by keertip** [comment]
Need a published version for dartdoc too!

**Comment by bwilkerson** [comment]
Yep. The same version should work for both.

**Comment by bwilkerson** [comment]
I believe that with https://codereview.chromium.org/2642683006/ the support is now in analyzer.
