### ISSUE TITLE
_Closure.hashCode is really expensive

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28161]
In Flutter land we stick closures in maps all the time, when registering listeners so that we can unregister them later.

In a profile I just did, where I expected layout and paint to dominate the results, the top three hits were pthread_getspecific (?), Window_render (which is paint), and Closure_hashCode (2.48% globally).

It looks like _Closure.hashCode does string manipulation and doesn't cache anything, this should be easy to optimise. :-)

**Comment by fsc8000** [comment]
Caching is one thing. The other cost is a call into C++ from Dart code on every hashCode invocation. We need a inline-assembly fast pasth to avoid that. I suspect part of the phtread_getspecific has to do with calling into the C++ runtime.

Which application did you run to obtain the profile?

**Comment by Hixie** [comment]
my dummy app on my huge factor branch, but it should be reproducible in any app that uses the framework, just move your finger about and tap the screen a lot.

**Comment by fsc8000** [comment]
I have an initial optimization that caches the hash code in the closure data object https://codereview.chromium.org/2598623002/ sent out for review.

In a microbenchmark that does nothing else than _Closure.hashCode this yields ~10x speedup.

**Comment by fsc8000** [comment]
Once I have my local engine build working again, I'll check whether Closure_hashCode disappears from the profile with my change.

**Comment by fsc8000** [comment]
@Hixie Would you be so kind to confirm if this fixes the issue once this CL is rolled into the engine?

I did some ad-hoc measurements with Flutter gallery, but I did not see a similar high percentage in the first place: Without my change I saw around 0.5% spent in Closure_hashCode. With my CL it went to <0.1%. It seems to improve things. There is potential to speed it up even more by using an assembly intrinsic.

**Comment by Hixie** [comment]
Unfortunately my dummy app changed (I forgot to make a copy to verify this) so it'll be hard for me to guarantee that it's been fixed. But I'll definitely keep an eye out for this and let you know if it's not better.

Thanks for the very prompt patch!
