### ISSUE TITLE
Switch to `covariant` in DDC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28168]
This is the DDC issue for #27486.

**Comment by vsmenon** [comment]
This should be done now.  Are there language tests for this?

**Comment by mit-mit** [comment]
Removing blocked; analyzer support in https://github.com/dart-lang/sdk/issues/28167 was completed.

@kevmoo who should this one be assigned to?

**Comment by kevmoo** [comment]
@mit – @devoncarew should run w/ that...

**Comment by devoncarew** [comment]
This looks DDC specific; assigning to @vsmenon to triage -

**Comment by vsmenon** [comment]
Looks like nothing further is needed beyond updating tests.  Tests work with `@checked` replaced with `covariant`:

https://codereview.chromium.org/2653493004
