### ISSUE TITLE
ZLibEncoder in browser

### ISSUE THREAD

**Issue by normcf** [dart-lang/sdk#28178]
I want to use the ZLibEncoder in my browser code, but it's only available in dart:io which is not available in Dartium (and I presume in dart2js).  I know there is a lot of dart:io that cannot be in the browser, but this (and ZLibDecoder) seem like they're pure computation.  I'm wondering why they're not in dart:convert with the other Transformers?  It seems like dart:convert should be usable in both browser and server.

**Comment by anders-sandholm** [comment]
@lrhn @floitschG

**Comment by lrhn** [comment]
The `ZLibDecoder` of `dart:io` actually uses zlib internally. It doesn't have a Dart implementation that can just be moved to the browser.
You need to either have the compression available as a browser native, or have a Dart or JS implementation to use it in the browser. You can't use the one from dart:io, so I'll have to say no to this request.

You might be able to use https://pub.dartlang.org/packages/archive (which I just found by searching, I don't know anything else about it).
