### ISSUE TITLE
File.rename() inconsistent when target entity exists as non-file

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28171]
Context: tests in https://gist.github.com/tvolkert/fdca2b521d22f5d19fcf0a29505d7b5f

The first test passes, because `File.rename()` (and `File.renameSync()`) throws (as expected) when you try to rename the file to a name that references an existing directory.

However, the second test fails, because if you try to rename the file to a name that references an existing symlink to a directory, it doesn't throw (which you'd expect it to).

**Comment by tvolkert** [comment]
@zanderso

**Comment by zanderso** [comment]
This is a call (almost) directly to rename(2), which has the same behavior, and it is consistent across Linux/Mac/Android. I think we should probably stick with the platform's choice, in this case.
