### ISSUE TITLE
Flakiness: VM gets stuck on shutdown because of background compiler?

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#28188]
We have a lot of flakiness on the VM bots because of timeouts that happen on tests that usually don't take that long to run.

Today alone I've seen these fail because of timeouts:
- none-vm-checked debug_x64 language/vm/lazy_deopt_vm_test
- none-vm-checked debug_x64 corelib/big_integer_huge_mul_vm_test
- none-vm release_simarm64 standalone/io/file_read_special_device_test
- none-vm release_simarm64 standalone/io/process_set_exit_code_test
- none-vm release_x64 co19/LibTest/isolate/Isolate/spawn_A04_t05
- none-vm release_ia32 standalone/io/http_server_close_response_after_error_test
- precompiler-dart_precompiled release_arm language/assignable_expression_test/none
- precompiler-dart_precompiled release_arm corelib/regexp/look-ahead_test
- precompiler-dart_precompiled release_arm language/getter_override2_test/03

I saw the stack trace below and thought I'd looked suspicious:

-----

FAILED: none-vm release_simarm64 standalone/io/process_set_exit_code_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: PID 24166 - process
    TID 24166:
    #0  0x00007fd76d359404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x00000000007dfa06 dart::Monitor::WaitMicros(long)
    #2  0x00000000008c2ac2 dart::ServiceIsolate::Shutdown()
    #3  0x00000000006419c6 dart::Dart::Cleanup()
    #4  0x00000000005a65c5 Dart_Cleanup
    #5  0x0000000000590f76 dart::bin::main(int, char**)
    #6  0x00000000005912a9 main
    #7  0x00007fd76c37df45 __libc_start_main
    #8  0x00000000005969db _start
    TID 24167:
    #0  0x00007fd76c456a13 epoll_wait
    #1  0x00000000005d4665 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x00000000005cefe9 dart::bin::ThreadStart(void*)
    #3  0x00007fd76d355184 start_thread
    #4  0x00007fd76c45637d __clone
    TID 24169:
    #0  0x00007fd76d359404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x00000000007dfa06 dart::Monitor::WaitMicros(long)
    #2  0x00000000006352dd dart::BackgroundCompiler::Run()
    #3  0x00000000008fa39d dart::ThreadPool::Worker::Loop()
    #4  0x00000000008fa56f dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000007dee46 dart::ThreadStart(void*)
    #6  0x00007fd76d355184 start_thread
    #7  0x00007fd76c45637d __clone

**Comment by mkustermann** [comment]
After investigating these timeouts more and landing https://github.com/dart-lang/sdk/commit/8347d26d7e419aff46c646acf44fd6da1cbda2ec which captures stack traces of threads of leaked dart processes (i.e. not tests themselves, but child processes of tests), I encountered [this buildbot failure](https://build.chromium.org/p/client.dart/builders/vm-linux-release-simarm64-be/builds/4113/steps/vm%20tests/logs/stdio):

```
FAILED: none-vm release_simarm64 standalone/io/test_extension_fail_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: PID 30774 - process
    TID 30774:
    #0  0x00007f9d8bf9c404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x00000000007e07d6 dart::Monitor::WaitMicros(long)
    #2  0x00000000008c3c82 dart::ServiceIsolate::Shutdown()
    #3  0x0000000000642386 dart::Dart::Cleanup()
    #4  0x00000000005a67c5 Dart_Cleanup
    #5  0x0000000000591176 dart::bin::main(int, char**)
    #6  0x00000000005914a9 main
    #7  0x00007f9d8afc0f45 __libc_start_main
    #8  0x0000000000596bdb _start
    TID 30775:
    #0  0x00007f9d8b099a13 epoll_wait
    #1  0x00000000005d4f65 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x00000000005cf299 dart::bin::ThreadStart(void*)
    #3  0x00007f9d8bf98184 start_thread
    #4  0x00007f9d8b09937d __clone
    TID 30777:
    #0  0x00007f9d8bf9c404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x00000000007e07d6 dart::Monitor::WaitMicros(long)
    #2  0x0000000000635c9d dart::BackgroundCompiler::Run()
    #3  0x00000000008fb67d dart::ThreadPool::Worker::Loop()
    #4  0x00000000008fb84f dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000007dfc16 dart::ThreadStart(void*)
    #6  0x00007f9d8bf98184 start_thread
    #7  0x00007f9d8b09937d __clone
    
    

stdout:
ERR: Unhandled exception:
ball
#0      Cat.throwMeTheBall (file:///tmp/dart_test_extension_failjK49Hg/test_extension.dart:19:72)
#1      main.<anonymous closure> (file:///tmp/dart_test_extension_failjK49Hg/test_extension_fail_tester.dart:20:23)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)



OUT: * 1057d Setting working directory: /mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk
* 1057d Working directory URI: file:///mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/
* 1057d Resolving script: /tmp/dart_test_extension_failjK49Hg/test_extension_fail_tester.dart
* 1057d Resolved entry point to: file:///tmp/dart_test_extension_failjK49Hg/test_extension_fail_tester.dart



ERR: Native extension path must be absolute, or simply the file name: extension/test_extension



OUT: * e740b Setting working directory: /mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk
* e740b Working directory URI: file:///mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/
* e740b Resolving script: /tmp/dart_test_relative_extension_failak8i5X/test_relative_extension_fail_tester.dart
* e740b Resolved entry point to: file:///tmp/dart_test_relative_extension_failak8i5X/test_relative_extension_fail_tester.dart





Command[vm]: DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/tests/standalone/io/test_extension_fail_test.dart
Took 0:04:30.153256

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimarm64 -t240 standalone/io/test_extension_fail_test
```

Which looks like what this bug report is about.

But the `taskkill` step also killed a leaked process, which looks like this:
```

***************** Killing dart *****************
Hanging process info:
  PID: 30836
  Command line: out/ReleaseSIMARM64/dart --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/tests/standalone/io/test_extension_fail_test.dart
  Stack:
    PID 30836 - process
    TID 30836:
    #0  0x00000000005f9d7c base::internal::SpinLockDelay(int volatile*, int, int)
    #1  0x00000000005f9c3c SpinLock::SlowLock()
    #2  0x00000000005fc368 tcmalloc::CentralFreeList::InsertRange(void*, void*, int)
    #3  0x00000000005f73a2 tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int)
    #4  0x00000000005f744a tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned long)
    #5  0x0000000000adbe94 tc_cfree
    #6  0x00007f9d8afdb1d0 __run_exit_handlers
    #7  0x00007f9d8afdb1f5 exit
    #8  0x00000000005db73c dart::bin::Process::TerminateExitCodeHandler()
    #9  0x0000000000591171 dart::bin::main(int, char**)
    #10 0x00000000005914a9 main
    #11 0x00007f9d8afc0f45 __libc_start_main
    #12 0x0000000000596bdb _start
Killed pid: 30836
```

=> This issue is probably the same as Issue 28246 . Merging this into Issue 28246.
