### ISSUE TITLE
No import quick fix for annotation on parameter

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28186]
![image](https://cloud.githubusercontent.com/assets/405837/21424907/19b7c734-c846-11e6-9fe1-da7777cf5db7.png)

I would like to add imports `Optional` and `SkipSelf` but no quick fix is provided.

**Comment by zoechi** [comment]
Weird, when I add another parameter I get the import quick fixes

![image](https://cloud.githubusercontent.com/assets/405837/21425678/eeccaa4e-c84a-11e6-9290-441e18db021d.png)

Just tested it - it is because of `this.`.
If I change it to `this.padding` (and add the field) I don't get the import quick fix.

**Comment by scheglov** [comment]
I'm unable to reproduce this with the latest analyzer and analysis server.
