### ISSUE TITLE
ImageData.runtimeType has changed in Dartium

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#28183]
With https://github.com/dart-lang/sdk/commit/d9f80a9ac16f7a55ddf1b5a1791b01c93beba8f4 the implementation class of the (abstract) dart:typed_data class Uint8ClampedList changed to _Uint8ClampedList.

It is still intended to report 'Uint8ClampedList' from .runtimeType.toString().  For some reason I don't yet understand, this doesn't happen in Dartium which reports '_Uint8ClampedList'.

**Comment by fsc8000** [comment]
Type.toString does not always use the class name. e.g. runtimeType of 42 is not _Smi, but int. See UserVisibleName in object.cc.

You need to make sure that Class::UserVisibleName returns the correct string - Uint8ClampedList in this case.
