### ISSUE TITLE
Flaky co19 HTML test: LibTest/html/Element/isContentEditable_A01_t01 is flaky on Safari

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#28187]

**Comment by kasperl** [comment]
Marked as flaky in b85f0906a490ee00e20966f25fb7dd9ed9fc41c8.

**Comment by jensjoha** [comment]
isContentEditable_A02_t01 has started behaving the same... Marking the [same](https://codereview.chromium.org/2700763002)
