### ISSUE TITLE
Stream#first docs are incomplete

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#28195]
The docs currently say "Returns the first element of the stream."
which is not true for a broadcast stream.
In reality, for a broadcast stream, it returns a `Future` that completes
with the first element of the stream that is fired after `first` is called
(which includes the possibility of the future never completing if there is no such event).
Nothing in the remaining docs clarifies this point.
The following demonstrates these semantics:

```dart
import 'dart:async';

Future main() async {
  var sc = new StreamController<int>.broadcast();
  var s = sc.stream;
  sc.add(1);  // this is the real 1st element on the stream.

  var second = s.first; // claims to be first, but it's really second.
  sc.add(2);
  print(await second);  // prints 2.

  print(await s.first); // never completes.
}
```

**Comment by zoechi** [comment]
I'd say the documentation to `broadcast stream` implies that

> A broadcast stream allows any number of listeners, and it fires its events when they are ready, whether there are listeners or not.
> ...
>  If a listener is added to a broadcast stream while an event is being fired, that listener will not receive the event currently being fired.

**Comment by lrhn** [comment]
That might be a little too implied. We should probably add some text to the effect that listening on a broadcast stream can be treated as listening on a new stream containing only the events emitted after you listen.
