### ISSUE TITLE
dart2js 1.21.0 regression

### ISSUE THREAD

**Issue by andrey-zakharov** [dart-lang/sdk#28196]
Finally pin the issue.
Found that is my app failing in js mode with "left hand wrong assignment" from js, actually `index.html.polymer.bootstrap.js`. There was such generated code (pub build --mode=debug) among section with a lot prototypes assignments:

`C.DefaultWidgetEditor+ContainerView_methods = Y.DefaultWidgetEditor_ContainerView.prototype;`
and a lot of 
`C.PolymerElement+ChangeNotifier+UserNotifications_methods = U.PolymerElement_ChangeNotifier_UserNotifications.prototype;
  C.PolymerElement+ChangeNotifier_methods17 = Z.PolymerElement_ChangeNotifier.prototype;
  C.PolymerElement+ChangeNotifier_methods23 = S.PolymerElement_ChangeNotifier0.prototype;
  C.PolymerElement+ChangeNotifier_methods28 = L.PolymerElement_ChangeNotifier1.prototype;
  C.PolymerElement+ChangeNotifier_methods16 = T.PolymerElement_ChangeNotifier2.prototype;
  C.PolymerElement+ChangeNotifier_methods15 = Y.PolymerElement_ChangeNotifier3.prototype;
  C.PolymerElement+ChangeNotifier_methods26 = T.PolymerElement_ChangeNotifier4.prototype;
  C.PolymerElement+ChangeNotifier_methods25 = R.PolymerElement_ChangeNotifier5.prototype;
  C.PolymerElement+ChangeNotifier_methods22 = Q.PolymerElement_ChangeNotifier6.prototype;
  C.PolymerElement+ChangeNotifier_methods7 = U.PolymerElement_ChangeNotifier7.prototype;
  C.PolymerElement+ChangeNotifier_methods21 = D.PolymerElement_ChangeNotifier8.prototype;
  C.PolymerElement+ChangeNotifier_methods8 = E.PolymerElement_ChangeNotifier9.prototype;
  C.PolymerElement+ChangeNotifier_methods10 = S.PolymerElement_ChangeNotifier10.prototype;
  C.PolymerElement+ChangeNotifier_methods12 = Y.PolymerElement_ChangeNotifier11.prototype;
  C.PolymerElement+ChangeNotifier_methods31 = F.PolymerElement_ChangeNotifier12.prototype;
  C.PolymerElement+ChangeNotifier_methods32 = Y.PolymerElement_ChangeNotifier13.prototype;
  C.PolymerElement+ChangeNotifier_methods11 = Q.PolymerElement_ChangeNotifier14.prototype;
`
at the end of section.

Just simple reverting dart to 1.20.1-1 fixes this issue.

this section for dart 1.21.0
http://pastebin.com/FbBbt7LW

for dart 1.20.1-1
http://pastebin.com/Vp1hYvgS

**Comment by andrey-zakharov** [comment]
Code was generated by such classes
`@CustomTag('pane-widget-editor')
class PaneWidgetEditor extends DefaultWidgetEditor with ContainerView implements IWidgetEditor {`

and

`@CustomTag('default-widget-editor')
class DefaultWidgetEditor extends PolymerElement implements IWidgetEditor`

**Comment by sigmundch** [comment]
Thanks for filing this issue @andrey-zakharov! It's possible that this is a bug in dart2js, but we need to investigate.

I'm trying to reproduce this locally, but I might need some additional help from you in order to do so. I tried creating small examples with the patterns you show using plain custom elements or polymer elements, but so far I haven't reproduced this successfully. Could you provide us small gist of code for us that we can use to reproduce the problem?

Also - do you see this problem still happening in the latest dev release (1.22.0-dev.3.0)?

**Comment by rakudrama** [comment]
From @sigmundch :

Here is an isolated repro:

@MirrorsUsed(targets: const ["M"])
library m;

import 'dart:mirrors';
import 'dart:html';


class Base extends DivElement {
  Base.created() : super.created() {
    return;
    return;
  }
}

class M extends Base with Mix1 {
  M.created() : super.created() {}
}

class Mix1 {
}

main() {
  reflectClass(M);
}

**Comment by rakudrama** [comment]
Fixed: https://github.com/dart-lang/sdk/commit/9338844b10f89ed68b606a33c4cde788cfc72bfb
