### ISSUE TITLE
building the Dart VM with tsan seems to not work anymore

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28216]
The command
( setenv GYP_DEFINES tsan=1 ; setenv DART_USE_GN 1 ; tools/build.py  create_sdk)
does not build a TSAN enabled binary

I had to manually edit out/DebugX64/args.gn and add the following
use_custom_libcxx = true
is_tsan = true
to get it to build correctly.

The gyp build instructions also do not seem to work anymore:
export CC="third_party/clang/linux/bin/clang -fsanitize=thread"
export CXX="third_party/clang/linux/bin/clang++ -fsanitize=thread"
export C_INCLUDE_PATH=third_party/clang/linux/lib/clang/3.4/include/
export CPLUS_INCLUDE_PATH=third_party/clang/linux/lib/clang/3.4/include/
export CC_host="third_party/clang/linux/bin/clang -fsanitize=thread"
export CXX_host="third_party/clang/linux/bin/clang++ -fsanitize=thread"
gclient runhooks
tools/build.py create_sdk
produces errors as the override of tcmalloc library does not seem to happen.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2614493002/ -- for GN.

For gyp there is no tsan argument defined, so that would have to be added, and tcmalloc excluded if it is set.

**Comment by zanderso** [comment]
I've added a fix to that CL for the gyp build as well. Note that both builds currently fail due to race reports from gen_snapshot.
