### ISSUE TITLE
ThreadInterruptsEnabled(), DisableThreadInterrupts() and EnableThreadInterrupts() are inherently racy

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28215]
The scheme used to enable/disable thread interrupts seems to be inherently racy and shows up as data races in a TSAN run.

The interrupting thread sees the state and decides to interrupt thread while at the same time the thread could decide it does not want to be interrupted. At this point the interrupting thread still goes ahead and interrupts the thread.

Instead we could have the thread interrupter always interrupt the thread and the signal handler could filter out signals when it does not want to be interrupted.

```cpp
 static void ThreadInterruptSignalHandler(int signal,
                                           siginfo_t* info,
                                           void* context_) {
    if (signal != SIGPROF) {
      return;
    }
   Thread* thread = Thread::Current();
    if (thread == NULL) {
      return;
    }  
    if (!thread->ThreadInterruptsEnabled()) {
      return;
    }
    ......
}
```

This would avoid the racy situation.

On windows this would still be an issue as we suspend/resume threads, we could suspend the thread and look at the state (at least it won't be racy).

**Comment by johnmccutchan** [comment]
The scheme is inherently racy (as are signals) but it helps us not pester (e.g. force early return from system calls) threads that remain disabled. Can we just suppress this TSAN warning?

**Comment by mraleph** [comment]
@a-siva do you think we are going to do something in this area?
