### ISSUE TITLE
Analyzer stops working if a WORKSPACE file is present 

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#28212]
The analyzer server will stop processing "package:" import URI if a WORKSPACE file is present in the package folder.

## How to reproduce : 

 - create a demo project with at least one import with "package:" uri (e.g. : 'package:logging/logging.dart'
 - open with an IDE (e.g. Atom), see that analyzer is working
 - close the IDE
 - create an empty WORKSPACE file beside `pubspec.yaml`
 - reopen the IDE, see that `package:` uri are not processed anymore
 - close the IDE
 - delete the WORKSPACE file
 - reopen the IDE : the package uri are working again.

**Comment by zoechi** [comment]
There should be an issue for this already.

**Comment by dam0vm3nt** [comment]
I searched for "WORKSPACE" in the issues and didn't found anything. Anyway I was almost going crazy because of this.

**Comment by alexander-doroshko** [comment]
Looks like https://github.com/dart-lang/sdk/issues/28038

**Comment by dam0vm3nt** [comment]
@alexander-doroshko that's exactly the same. I'll close this one then.
