### ISSUE TITLE
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-9 mentions "stacktrace"

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28227]
catch(e, stacktrace) is no longer the perferred syntax according to the analyzer.  "stacktrace" can be removed.

There is an example at:
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-9
which uses the old syntax.

**Comment by lrhn** [comment]
I don't think there is any official "preferred" syntax for `catch` clauses. You can capture the stack trace or not, depending on what you want, and that hasn't changed. The example that you link to *uses* the stack trace, so it is perfectly fine to capture it.

I can understand if the analyzer gives a hint if you capture a stack trace and don't use it. That would be a reasonable "unused variable" hint.

**Comment by eseidel** [comment]
Ah, yeah, i just misread the warning. I thought it was telling me not to use that syntax, it was just telling me the variable was unused.
