### ISSUE TITLE
Webgl : getParameter : GLenum vs GLint

### ISSUE THREAD

**Issue by jox81** [dart-lang/sdk#28223]
Hello, 
is there a way to make the difference between the returned value of the gl.getParameter( ) function ?

if the result is an int, is it a GlInt or a glEnum ?

Let say we have : 

`
Object result = gl.getParameter(RenderingContext.BLEND_SRC_RGB);
`

in my case result is an int = 1

I know from [Kronos specifications](https://www.khronos.org/registry/webgl/specs/1.0/) that this parameter should return an enum
`gl.BLEND_SRC_RGB	GLenum`

How can i make the différence by code ?

**Comment by jox81** [comment]
And if, for any other parameter, the getParameter function return a '0', how can i know if it means:
static const int NO_ERROR = 0;
or
static const int NONE = 0;

in fact, with the returned value, i'm trying to find the matching enum Name....

**Comment by terrylucas** [comment]
GLEnum maps to a int and the constant is an int too in Dart.
