### ISSUE TITLE
Analyzer doesn't properly ignore generic method type parameters in spec mode.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28236]
I'm adding generic type parameters to the core libraries (https://codereview.chromium.org/2529393002).

In practice, they should act the same as the existing comment-based type parameters (that is, ignored in spec mode, only meaningful in strong mode).

When running `tools/tests.py -cdart2analyzer -rnone`, I get warnings like:
```
FAILED: dart2analyzer-none release_x64 benchmark_smoke/benchmark_smoke_test
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|ARGUMENT_TYPE_NOT_ASSIGNABLE|/usr/local/google/home/lrn/dart/co/sdk/third_party/pkg/stack_trace/lib/src/chain.dart|204|16|8|The argument type '<T extends num>(T, T) → T' can't be assigned to the parameter type '(dynamic, dynamic) → dynamic'.
WARNING|STATIC_WARNING|ARGUMENT_TYPE_NOT_ASSIGNABLE|/usr/local/google/home/lrn/dart/co/sdk/third_party/pkg/stack_trace/lib/src/trace.dart|289|18|8|The argument type '<T extends num>(T, T) → T' can't be assigned to the parameter type '(dynamic, dynamic) → dynamic'.
```

The line of the error is using `max` from `dart:math` as a function parameter, and `max` has been made generic. The analyzer seems to leak the strong-mode generic function type into spec mode checking. In spec mode, there is no such thing as a generic function type.

Similarly, it gives warnings like:
```
WARNING|STATIC_TYPE_WARNING|INCONSISTENT_METHOD_INHERITANCE|/usr/local/google/home/lrn/dart/co/sdk/third_party/pkg/collection/lib/src/wrappers.dart|290|7|15|Inconsistent declarations of 'fold' are inherited from (dynamic, (dynamic, E) → dynamic) → dynamic, <T>(T, (T, E) → T) → T.
```
where the generic type leaks and the override with a non-generic method causes a warning.

**Comment by jmesserly** [comment]
taking a look.

ARGUMENT_TYPE_NOT_ASSIGNABLE -- this one is pretty easy, we need to make sure generic tear offs are instantiated (to their bounds)

INCONSISTENT_METHOD_INHERITANCE -- I'll have to take a look where this one originates from, but we definitely want to remove the generic function types when ERROR_VERIFIER is taking a look at things.

One fix that would probably hit both of these at once would be to change the subtyping rule to instantiate to bounds before doing function subtype checks.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2621433003/
