### ISSUE TITLE
Prevent tools/test.py from including the "pkg" test suite in it's default selector list

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28237]
Currently the entire VM team is forced to pass `--exclude-suite=pkg` to `tools/test.py` because 
  * the "pkg" suite is in the [default test selector list](https://github.com/dart-lang/sdk/blob/master/tools/testing/dart/test_options.dart#L14)
  * the `pkg/pkg.status` file is not up-to-date
  * the buildbot does not seem to be running these tests

Furthermore, I assume almost all of the packages are using `package:test` and should probably be run via `pub run test` instead of the way `tools/test.py` does it. Is that a valid assumption?

We can take either of the following actions now:
  * add a buildbot which tests it and get the status file up-to-date
  * skip all pkg tests in `pkg/pkg.status` for the VM
  * remove `pkg` from the default test selector list when running VM tests (would be my preference)

/cc @whesse @ErikCorryGoogle

**Comment by lrhn** [comment]
I believe https://build.chromium.org/p/client.dart.packages/console is a build-bot running (some) packages. 

It's definitely not being kept green, though, probably because most people don't know about it.

**Comment by mkustermann** [comment]
An additional point: Even if we ran some of these tests on the red package builders: These packages are usually using `package:test` which has a per sub-test timeout (e.g. of 20 seconds) and running these tests with a **debug vm** will cause sub-tests to timeout sometimes (though they would be successful if given more time).

That's because `package:test` doesn't increase the sub-test timeout if we run in debug mode.

**Comment by whesse** [comment]
I have a CL out to do this, but we also need to land changes on the buildbots at the same time.  CL for sdk repo is https://codereview.chromium.org/2610943002/
