### ISSUE TITLE
Dartk-vm tests crash

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28238]
See: https://build.chromium.org/p/client.dart/builders/vm-kernel-linux-release-x64-be/builds/567/steps/vm%20tests/logs/stdio

After landing generic type parameters on core library classes, some tests started crashing.
I'll suppress the errors for now.

**Comment by lrhn** [comment]
Suppression committed as https://github.com/dart-lang/sdk/commit/821eeb1aac756e6fad7384ba4c19c1ef298773cc

**Comment by jensjoha** [comment]
Background: I want to run (and get something useful out of) 'python tools/test.py -cdartk -mrelease service'  --- pretty much everything crashes with the same error as above.

Hacky workaround (instead of the status file updates):

```diff
diff --git a/runtime/vm/kernel_to_il.cc b/runtime/vm/kernel_to_il.cc
index 98f83f875c..ada614f4cd 100644
--- a/runtime/vm/kernel_to_il.cc
+++ b/runtime/vm/kernel_to_il.cc
@@ -430,7 +430,7 @@ void ScopeBuilder::VisitTypeParameterType(TypeParameterType* node) {
     // factory constructor function.
     HandleSpecialLoad(&result_->type_arguments_variable,
                       Symbols::TypeArgumentsParameter());
-  } else {
+  } else if (!function.is_static()) {
     // The type argument vector is stored on the instance object. We therefore
     // need to capture `this`.
     HandleSpecialLoad(&result_->this_variable, Symbols::This());
```
