### ISSUE TITLE
kernel baseline tests fail on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28243]
The following tests have runtime errors on Windows:
kernel/test/baseline_type_propagation_test
kernel/test/baseline_spec_mode_test
kernel/test/baseline_strong_mode_test
@asgerf  @kmillikin 

These failures are now noted in the status file pkg/pkg.status.
The reported error is

00:09 +0 -1: argument.dart
  NoSuchMethodError: The getter 'enclosingLibrary' was called on null.
  Receiver: null
  Tried calling: enclosingLibrary
  dart:core                                   Object.noSuchMethod
  pkg\kernel\test\baseline_tester.dart 63:50  runBaselineTests.<fn>.<async>
  dart:async                                  _SyncCompleter.complete
  package:kernel/analyzer/loader.dart 754:5   DartLoaderBatch.getLoader.<async>
  dart:async                                  _SyncCompleter.complete
  package:kernel/analyzer/loader.dart 773:3   createPackages.<async>
  ===== asynchronous gap ===========================
  dart:async                                  _Completer.completeError
  pkg\kernel\test\baseline_tester.dart 81:8   runBaselineTests.<fn>.<async>
  dart:async                                  _SyncCompleter.complete
  package:kernel/analyzer/loader.dart 754:5   DartLoaderBatch.getLoader.<async>
  dart:async                                  _SyncCompleter.complete
  package:kernel/analyzer/loader.dart 773:3   createPackages.<async>
  ===== asynchronous gap ===========================
  dart:async                                  _asyncThenWrapperHelper
  pkg\kernel\test\baseline_tester.dart        runBaselineTests.<fn>
  
00:09 +0 -1: arithmetic.dart
00:12 +0 -2: arithmetic.dart
  NoSuchMethodError: The getter 'enclosingLibrary' was called on null.
  Receiver: null
  Tried calling: enclosingLibrary
  dart:core                                   Object.noSuchMethod
  pkg\kernel\test\baseline_tester.dart 63:50  runBaselineTests.<fn>.<async>
  dart:async                                  _SyncCompleter.complete
  package:kernel/analyzer/loader.dart 754:5   DartLoaderBatch.getLoader.<async>

**Comment by mraleph** [comment]
@kmillikin & @asgerf please check if this is a still the case and if it matters - if it does not please close.

**Comment by jensjoha** [comment]
These tests doesn't seem to exist anymore. I will remove the status entries, and close this issue if nothing breaks.

**Comment by jensjoha** [comment]
Nothing seems to have broken. Closing.
