### ISSUE TITLE
int.clamp() should statically return int if the arguments are ints

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28249]
I'm playing around with getting some code to not have any implicit downcasts. I'm running to an error in:

```dart
int current;
int max;
int value;
current = value.clamp(0, max);
```

The core library at runtime does ensure you get an int back if both arguments are ints, but the static signature of `clamp()` is just:

```dart
num clamp(num lower, num upper);
```

I think `int` should override that to:

```dart
T clamp<T extends num>(T lower, T upper);
```

But I'm not sure if that's right.

**Comment by munificent** [comment]
cc @floitschG @lrhn @leafpetersen

**Comment by lrhn** [comment]
I can't remember if we allow a non-generic method to be overridden by a generic one. If we don't, then this is not possible. If we do, then my only problem is all the other places that should potentially get the same treatment (including, e.g., `operator+`, which can't be generic).

**Comment by munificent** [comment]
> my only problem is all the other places that should potentially get the same treatment

We'll need to fix them too. :)

**Comment by leafpetersen** [comment]
> I can't remember if we allow a non-generic method to be overridden by a generic one

We don't.

**Comment by floitschG** [comment]
We will remove `clamp` from `num` and specialize the method on `int`.

**Comment by mraleph** [comment]
fyi: Flutter heavily uses `clamp` with doubles.

https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=clamp&type=

Consider specializing for `double` too and also providing a simpler version (e.g. less handling of corner cases)

**Comment by floitschG** [comment]
Yes. We will do the same for `double`.
(There is another bug for `double.clamp`).

Not sure yet, if we want to treat `-0.0` and `NaN` (non-)specially in the `double` version.

**Comment by lrhn** [comment]
We have now fixed the static typing for null safety.
