### ISSUE TITLE
dart2js: using dart:mirrors swaps values of named default parameters

### ISSUE THREAD

**Issue by wobuntu** [dart-lang/sdk#28259]
I'm writing a web app for my bachelor thesis and encountered the following problem:
A class instance is created with dart:mirrors using the following line:
```
_components[name] = classMirror
			.newInstance(const Symbol(""), positionalParam, namedParam)
			.reflectee;
```
Both, positionalParam and namedParam are empty and the called constructor is defined as:
```
MyClass({
				List<Btn> myList: null,
				int myFirstParam: 1,    // --> 5
				int mySecondParam: 2,   // --> 6
				int andSoOn: 3,         // --> 7
				int anotherOne: 4,      // --> 4
				int anotherOne: 5,      // --> 2
				int andAgain: 6,        // --> 8
				int evenOneMore: 7,     // --> 9
				int almostDone: 8,      // --> 3
				int lastParam: 9        // --> 1
				})

// Note: @MirrorsUsed(target: "MyClass, otherClass, andSoOn") is used.
```

Everything works fine in dartium but after compiling the code with dart2js to javascript, the default values are received by the wrong parameters, eg. "myFirstParam" receives the value 5 from "anotherOne" in aboves example (see comments for actually received values).

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
