### ISSUE TITLE
"unresolved implicit call to super constructor"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28252]
If I run the following in the context of `flutter test`, I get a compile-time error "unresolved implicit call to super constructor":

```dart
abstract class _Root { }
abstract class _MixinA { }
abstract class _MixinB { }
abstract class _Subclass extends _Root with _MixinA, _MixinB { }
abstract class _MixinC implements _Subclass {
  var test;
}
class _Concrete extends _Subclass with _MixinC { }

void main() {
  new _Concrete();
}
```

**Comment by Hixie** [comment]
Looks like this reproduces if you enable `--error-on-bad-override`.

**Comment by a-siva** [comment]
Yes the debug assertion stack trace when --error-on-bad-override is used : 
Dumping native stack trace for thread 8df
  [0x000000000098d4a6] dart::Profiler::DumpStackTrace()
  [0x000000000098d4a6] dart::Profiler::DumpStackTrace()
  [0x00000000005fdbd5] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x000000000063f096] dart::ClassFinalizer::FinalizeClass(dart::Class const&)
  [0x000000000063ec7c] dart::ClassFinalizer::FinalizeClass(dart::Class const&)
  [0x000000000063e521] dart::ClassFinalizer::ResolveAndFinalizeMemberTypes(dart::Class const&)
  [0x000000000063ecb1] dart::ClassFinalizer::FinalizeClass(dart::Class const&)
  [0x0000000000690310] dart::Compiler::CompileClass(dart::Class const&)
  [0x000000000086653c] dart::Class::EnsureIsFinalized(dart::Thread*) const
  [0x0000000000897830] dart::Class::LookupFunction(dart::String const&, dart::Class::MemberKind) const
  [0x000000000092ef2f] dart::Parser::ParseNewOperator(dart::Token::Kind)

The assertion is triggered for class Class: _Root@15132886&_MixinA@15132886&_MixinB@15132886
The class finalization trace seems to indicate we are not applying mixin members from the right class:
Applying mixin members of Library:'file:///usr/local/google/home/asiva/tmp/issue28252.dart' Class: _MixinB@15132886 to Library:'file:///usr/local/google/home/asiva/tmp/issue28252.dart' Class: _Root@15132886&_MixinA@15132886&_MixinB@15132886 at pos 32
Done applying mixin members of Library:'file:///usr/local/google/home/asiva/tmp/issue28252.dart' Class: _MixinB@15132886 to Library:'file:///usr/local/google/home/asiva/tmp/issue28252.dart' Class: _Root@15132886&_MixinA@15132886&_MixinB@15132886

Shouldn't it be applying mixin members from Class _MixinA@15132886&_MixinB@15132886 ?

@crelier @mhausner

**Comment by crelier** [comment]
The class finalization trace looks fine to me, but the --error-on-bad-override functionality looks broken to me. It forces the wrong finalization order. In class_finalizer.cc:1526, it claims to finalize the super class, but iterates instead on the interfaces. I do not think people use this flag much and nobody noticed it was broken for a long time. I will look at it tomorrow.

Now, of course, this does not explain the "unresolved implicit call to super constructor" error of this report. It may have to do with the fact that _SubClass is both implemented and extended, and we may finalize things in the wrong order. I'll check tomorrow too.

**Comment by crelier** [comment]
The finalization order of mixin application classes is very fragile and can be disrupted by the use of the --error-on-bad-override flag. Also, the flag forces interfaces to be finalized in the wrong order. The cloning of the super class constructor requires the super class to be finalized before this cloning occurs.

As a side note, --error-on-bad-override indeed checks overrides in the whole graph of super interfaces, and not just the super classes.

A cl fixing the finalization of mixin applications will follow shortly.
