### ISSUE TITLE
run_vm_tests should support running tests through kernel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28264]
Our cc tests often load code dynamically. 

Right now we are skipping these tests on the Kernel bots but we should instead enable running them through dartk isolate.

**Comment by mraleph** [comment]
I am working on running all tests through DFE isolate which should enable this.

**Comment by mraleph** [comment]
We are running `co19 language kernel` tests through the DFE isolate. However we still can't run vm tests. 

This is blocked on #29172

**Comment by jensjoha** [comment]
The blocked-on issue is closed.

**Comment by mraleph** [comment]
@aam I think vm tests are running. Please reopen if this is not the case.
