### ISSUE TITLE
Dart2js should not let const/final declarations introduce a setter.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28268]
Example:
```dart
const x = 42;  // same with "final".
set x(v) { print(v); }
main() {
  x = "Hello world!";
}
```
The language semantics specifies that this should call the setter and print the string. Instead dart2js reports:
```
concon.dart:2:5:
Error: Duplicate definition of 'x'.
Try to rename or remove this definition.
set x(v) { print(v); }
    ^
concon.dart:1:7:
Info: Existing definition of 'x'.
const x = 42;
      ^
concon.dart:5:3:
Warning: Duplicate definition of 'x'.
Try to rename or remove this definition.
  x = "Hello world";
  ^^^^^^^^^^^^^^^^^
Error: Compilation failed.
Error Compiling concon.dart
```
Final declarations, and const declarations are final, don't introduce a setter. The setter (line 2) introduces a setter named `x=` which is not related to final/const variable.

**Comment by natebosch** [comment]
CFE on the VM or Dart2Js gives

```
main.dart:2:5: Error: Conflicts with member 'x'.
set x(v) { print(v); }
    ^
main.dart:1:7: Error: Conflicts with setter 'x'.
const x = 42;  // same with "final".
      ^
main.dart:4:3: Error: Setter not found: 'x'.
  x = "Hello world!";
  ^
```

Analyzer does not give an error on the setter definition but does give 

```
  error • Constant variables can't be assigned a value at main.dart:4:3 • assignment_to_const
  error • A value of type 'String' can't be assigned to a variable of type 'int' at main.dart:4:7 • in
```

I suspect that is the desired behavior for Dart2 so if anything this is a missing error in analyzer - is it worth keeping this issue open for that?

**Comment by lrhn** [comment]
You can argue that a `const` should be treated different than a normal field (the spec doesn't). but even then a *final* field should definitely not conflict with a setter.

A final field introduces a getter. That getter does not conflict with the similarly named setter

This is still wrong.
