### ISSUE TITLE
Enable mixin a @JS class

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#28260]
It would be nice if `package:js` could allow mixin a `@JS` annotated class and have DDC produce the usual ES6 code for mixins : 

## dart:

    @JS()
    class MyBehavior {
      external get thing;
    }

    @JS()
    class Something {
    }

    class MyType extends Something with MyBehavior {
    }

## ES6

    class MyType extends MyBehavior(dart.global.Something) {
      ....
    }

**Comment by jacob314** [comment]
How valuable is this feature? I don't see how we would support it in dart2js or dartium so it is a bit of a harder sell for DDC.

**Comment by dam0vm3nt** [comment]
My opinion is that this is coherent with one of the DDC targets : to produce a more idiomatic js code. So as dart classes get translated into es6 classes so should dart mixin. At least when interoperating with js code.

Another reason is that it makes more simple to interopetate with es6 framework like for example polymer.

As for the differences between DDC and dart2js I think that they already produce different code so this should be an issue as long as semantic is preserved.

**Comment by dam0vm3nt** [comment]
On the other side I have to admit that there's no such a thing like "ES6 mixin". That's only a "code convention". But there are reasons to think that that's the closest aproximation to a mixin in ES6, see for example [here](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/).

To apply this approach only to @JS annotated classes used as mixin should not be a big problem, while extending such approach to native dart mixin indeed is more complicated. 

 1 . How would you dedide that a class is worth behaving as a mixin and thus translate it in a different way ? 
 2. Should a class elected to become a possible mixin be translated in two different ways ?

For point 1 I think there's already a logic that check if a class can be used as mixin, in the analyzer for sure.

For point 2 a "mixable" class could be translated in the following way:

## Dart version
```dart

class MyDartMixin {
   String prop;
   String method(String x) {
       ...
    }
}
```

## Translated ES6

```javascript

MyDartMixin_asMixin = (otherclass) => class _MyDartMixin extends otherclass {
   _MyDartMixin() {
           super();
          new();
   }
   
   new() {
       this.prop=null;
   }

  method(x) {
     ...
  }

}

MyDartMixin = MyDartMixin_asMixin(Object)

```

**Comment by matanlurey** [comment]
I think its unlikely this will happen.
