### ISSUE TITLE
Add `lookup` function to `Map`

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28272]
It would be convenient to have a method on `Map` that makes a lookup and runs a callback function if the value doesn't exist yet (and returns it):

``` dart
var map = { "foo": 499 };
map["foo"]; // => 499
map["bar"];  // => null
map.lookup("bar", () => 32);  // => 32
```

This would potentially also be useful during the migration to non-nullable types. We could then make the index operator throw if the entry is not in the map.

**Comment by rakudrama** [comment]
Note that this is also competing with the existing idioms

```dart
var value = map[key] ??= createDefaultValue();  // inserted
var value = map[key] ?? createDefaultValue();   // not inserted
```

which, unlike `putIfAbsent` and `lookup`, is allocation-free in the not-absent case (no closure).

**Comment by peter-ahe-google** [comment]
Good point, Stephen. Unfortunately, the existing idiom doesn't handle the case where null is desired and stored in the map. Often, it is useful to avoid null, but not always.

**Comment by floitschG** [comment]
Closing for now.
We haven't made a final decision yet, but this method would/will be revisited with non-nullable types (and their changes to the core libraries). No need to keep this bug open.

**Comment by greglittlefield-wf** [comment]
Should this issue be reopened now that nnbd work is further along? Or is it being tracked internally/elsewhere?

I'm also thinking of a use-case where `null` is a valid value in the map, but if it isn't present I'd like to default it to something different (similar to the notion of `undefined` in JavaScript) when assigning a nullable variable.
