### ISSUE TITLE
Inconsistent failure behavior between Link.update() and Link.rename()

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28275]
Context: the tests in https://gist.github.com/tvolkert/23d61b638f1dcb588a2eabf7b79c3837

In Link.update(), if the entity's path resolves to a directory, then the errno is EINVAL.  Yet in Link.rename(), if the destination path resolves to a directory, then the errno is EISDIR.  It seems like they should exhibit consistent behavior in how they respond to a collision with a directory.

**Comment by tvolkert** [comment]
@zanderso

**Comment by zanderso** [comment]
This was fixed by https://github.com/dart-lang/sdk/commit/5e2898887b92758afef1966f17977931430fdd91
