### ISSUE TITLE
language/vm/optimized_stacktrace_test crashed on windows release ia32

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28276]
Will mark Pass, Crash in the status file.

**Comment by mraleph** [comment]
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by mkustermann** [comment]
There's been no entry in the flakiness database. Assuming stale.
