### ISSUE TITLE
Link.rename() allows callers to overwrite regular files

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28277]
Context: the tests in https://gist.github.com/tvolkert/266ba6b6cc85c448ccc644a3347461d7

(the first test succeeds; the second test fails).

In Link.update(), if the entity's path resolves to a regular file, then an exception is thrown with an errno of EINVAL. Yet in Link.rename(), if the destination path resolves to a regular file, then no exception is thrown at all - the link is renamed and replaces the file.

It seems like Link.rename() should throw if the destination path resolves to a non-link (it already does throw if it resolves to a directory).

**Comment by tvolkert** [comment]
@zanderso

**Comment by zanderso** [comment]
The behavior of Link.rename() is consistent with the POSIX rename(2) call. For both Link.update() and Link.rename(), the existing path must be a valid symlink, or an error is indicated.
