### ISSUE TITLE
Analyzer does not have a warning for @VisibleForTesting

### ISSUE THREAD

**Issue by sebastianmalysa-wf** [dart-lang/sdk#28273]
The documentation for the VisibleForTesting annotation suggests that the analyzer will provide feedback if "the annotation is associated with a declaration not in the 'lib' folder of a package or the declaration is referenced outside of its defining library or a library which is in the 'test' folder of the defining package (https://github.com/dart-lang/sdk/blob/37890f995f68bf2074649faa5c4662716baf4381/pkg/meta/lib/meta.dart#L123-L133)." The analyzer does not seem to provide any feedback around this annotation. Currently the annotation is great for documentation purposes, but it would be even better if the analyzer caught the circumstances above and provided a warning. Are there any plans to do this?

**Comment by bwilkerson** [comment]
Yes, we plan to provide this warning, but I don't know how quickly we'll get to it.

**Comment by sebastianmalysa-wf** [comment]
Thank you for the quick response, knowing that it's in the pipeline is very helpful.

**Comment by srawlins** [comment]
Fixed with 14629098dd947ee0f206bbbb1e258c275e282f88.
