### ISSUE TITLE
Turn off swap on Dart's build slaves.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28271]
Try this: turn off swap on Dart's build slaves.

(Martin:) Before I forget it, I had recently a thought: While debugging these flaky timeouts, I was looking into one of the bots and noticed that they actually have a swap partition enabled.

So I was wondering if it would make sense to turn "sudo swapoff" on these machines (or rather get that into the machine images).

For us it's better if a test crashes with OOM than if we start swapping and get plenty of unrelated test timeouts.
Just a thought.

**Comment by athomas** [comment]
Moving to new infrastructure, re-open if still relevant there.
