### ISSUE TITLE
Analyzer should not treat const declarations as introducing a setter

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28270]
Example:
```dart
const x = 42;
set x(v) { print(v); }
main() {
  x = "Hello world!";
}
```
The language semantics specifies that this should be perfectly correct code that calls the setter and prints the string. Instead the analyzer reports:
```
Analyzing [concon.dart]...
[warning] Constant variables can't be assigned a value. (/test/concon.dart, line 5, col 3)
1 warning found.
```
Const declarations are final and don't introduce a setter. The setter (line 2) introduces a setter named `x=` which is not related to final/const variable.
(There is no problem if `x` was declared final, only if it's declared const).

**Comment by srawlins** [comment]
The analyzer no longer reports an error or warning for this code.
