### ISSUE TITLE
I wish for code completion to give me options from a const Map

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28289]
Flutter has some big const maps (e.g. Color) that we've seen all of our UX study participants use. They get this far: `Colors.blue` and then try to code complete. Nothing happens :(

`blue` is a big const map. Could the analyzer provide code completion options for const maps? Or at least give me map operators when I'm trying to code complete a variable that is a map. And, then if I code complete again, shows me all keys for the map. (because it's a const map)

or, maybe it does and we just need to wire it up more?

Thanks!

**Comment by bwilkerson** [comment]
Yes, it's quite possible for server to provide these suggestions. Not sure how much work is involved, but we have the information we need.

**Comment by bwilkerson** [comment]
I suspect that this issue has been addressed in other ways now. Please re-open if not.

**Comment by sethladd** [comment]
Hi. Just tested, doesn't appear to be working in DartPad at least:

![screen shot 2017-06-20 at 2 00 03 pm](https://user-images.githubusercontent.com/5479/27355709-d747f546-55c0-11e7-9cfa-4bf5fecabf20.png)

**Comment by srawlins** [comment]
I'm not sure what else is expected when typing `map.`. These are the properties and methods on a `Map`.

**Comment by bwilkerson** [comment]
I don't think there's anything more we can suggest for `map.^`, but it might be interesting to suggest the known keys for `map[^]`.

**Comment by natebosch** [comment]
> `blue` is a big const map.

It's not a `Map`. It does defines `operator []`, but that operation cannot be used in a const context.

It might still be worth implementing support for `const Map` instances and `map[^]`, however I do not believe that will satisfy the original request.

**Comment by bwilkerson** [comment]
I'm guessing that this feature would no longer be useful, so I'm going to close the issue.
