### ISSUE TITLE
No static error when invoking an Object

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28284]
As far as I can tell, this does not produce a static error in strong mode:

```dart
Object o;
o("Objects are functions?!");
```

Shouldn't it? dev_compiler also compiles this without error or warning, translating the invocation to a dcall.

**Comment by munificent** [comment]
cc @vsmenon

**Comment by vsmenon** [comment]
Apparently this has been an issue for a while?

#21938

**Comment by munificent** [comment]
Oh, wow. Old bug is old. We should fix that. I'll mark this as a duplicate.
