### ISSUE TITLE
Confusing error when calling function with wrong argument types

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28286]
If I run this with dev_compiler:

```dart
try {
  dynamic fn = (int n) => null;
  fn("not int");
} catch (error) {
  print(error);
}
```

It correctly throws an error. Win! However, the error it throws is NoSuchMethod:

```
NoSuchMethodError : method not found: 'Symbol("call")'
Receiver: Instance of '(int) -> dynamic'
Arguments: ["not int"]
```

which is kind of confusing. The function does have a `call` method. It's just the argument type was wrong. I think a CastError would make more sense?

Heh, and now that I look in the source, I see:

```dart
  ...

  if ($_checkApply($ftype, $args)) {
    if ($typeArgs != null) {
      return $f.apply($obj, $typeArgs).apply($obj, $args);
    }
    return $f.apply($obj, $args);
  }

  // TODO(leafp): throw a type error (rather than NSM)
  // if the arity matches but the types are wrong.
  // TODO(jmesserly): nSM should include type args?
  return callNSM();
}
```

The fix should just be to add an else to that `_checkApply()` if and throw a better error.

cc @leafpetersen @vsmenon

**Comment by vsmenon** [comment]
The last commit should fix @munificent 's example, but it still doesn't always throw the 'right' exception when both a `TypeError` and an `NoSuchMethodError` apply:

```dart
void main() {
  Function f = (String str) => print(str);
  f(42, 38);
}
```

In checked mode, dart2js and the VM (and the spec) throw a `NoSuchMethodError` while DDC throws a `TypeError`.  We'll need to refactor `_checkApply` to check for these in the right order.

**Comment by jmesserly** [comment]
Fixed! this now prints: `Type 'String' is not a subtype of type 'int'`
