### ISSUE TITLE
Roll Dartium to Chrome 50

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28280]

**Comment by mit-mit** [comment]
@kevmoo did we complete this roll?

**Comment by terrylucas** [comment]
Dartium 50 is rolled, building and running tests on the Dartium integration bots.  Both Mac, Linux and Windows versions build.  There are ~180 failing tests failing out of ~18K tests and ~195 failing checked mode tests.

Jacob is hoping to get the Dev Console to start working again (there was a major refactoring of the dev console code in Chromium 50) next week.  I'm working on fixing the failing tests and rolling out the new dart:html (50 idls).

Expect a release in a few weeks (hope to make 1.23)

**Comment by AndrewLugg** [comment]
Would it be possible to build in ffmpeg into the build that is put on the website? It can be built by a googler with out licencing issues. It would just need to be left off the open source version.

**Comment by terrylucas** [comment]
Andrew,

I would be hesitant to try in put this in roll 50 (Chromium version 50).  Chrome/Chromium has no intention to support ffmpeg its a convience.  In addition, I'm not sure it would even work with 50 - it quite a bit of work with Chromium 58, etc.

https://cs.chromium.org/chromium/src/third_party/ffmpeg/README.chromium

In addition, the rolling instructions for Chromium with ffmpeg is quite involved see the 19 page doc on "Chromium FFmpeg Roll Instructions"

https://docs.google.com/document/d/14bqZ9NISsyEO3948wehhJ7wc9deTIz-yHUhF1MQp7Po/edit#heading=h.ab31taackhkc

**Comment by AndrewLugg** [comment]
Ffmpeg is in Chrome, just not chromium. The problem comes from that; Dartium is suppose to be as close to Chrome as it can be, with Dart VM.

Our company runs into problems without the codecs, as we develop using the WebAudioAPI, and the only codec that works on all browsers is AAC (and WAV, but filesizes), which is fine once we get it into Chrome or Safari, but all our development occurs in Dartium, which doesn't work. As more people migrate to WebAudioAPI this will become a bigger problem for developers.

**Comment by kevmoo** [comment]
@AndrewLugg we're quite limited here. The only folks that can deploy capital-C "Chrome" is the Chrome team. There are limitations with codec licensing, etc that limit us to only building on the completely open-source Chromium project.

We're working hard on a fast JS dev model that doesn't require Dartium at all: `dev_compiler` (also called DDC). 

Source: https://github.com/dart-lang/sdk/tree/master/pkg/dev_compiler
Video from our March summit: https://youtu.be/oH6czEQwHdE

**Comment by whesse** [comment]
This issue is not closed - it is the main issue for releasing Dartium 50, currently milestone 23.  The side issue of ffmpeg should not have been on this issue.

**Comment by dgrove** [comment]
Terry - this is going to miss 1.23, right? If that's the case, can you please move to 1.24?

**Comment by terrylucas** [comment]
Yes I will move to 1.24  :-(

**Comment by dgrove** [comment]
@terrylucas - ETA for this is this week, right?

**Comment by terrylucas** [comment]
This week or early next week Bill has a problem with the integration bots.
Preventing exhaustive testing.

**Comment by terrylucas** [comment]
Bill should have the bots working tonight or tomorrow again (that's the
integration bots for me).  I can't move to latest Dart without them running.

**Comment by whesse** [comment]
The integration bots are working again.

**Comment by terrylucas** [comment]
Thanks, yep forced a bunch of builds once the first Linux built earlier
today.  The rest are still running - looks good.

**Comment by dgrove** [comment]
@terrylucas can you provide an update here?

**Comment by terrylucas** [comment]
### Dartium
- DevConsole works well in Dartium (thanks jacobr)
- re-generated sdk/libs from Chrome 50 IDLs landed (dart:html, dart:indexed_db, dart:svg, dart:web_audio, dart:web_gl) landed [https://codereview.chromium.org/2871193002](https://codereview.chromium.org/2871193002)
- Dartium 50 landed in Dart's master branch [https://github.com/dart-lang/sdk/commit/f27144d7b5b7f8063eb3ac0d90c23c87a40e7163](https://github.com/dart-lang/sdk/commit/f27144d7b5b7f8063eb3ac0d90c23c87a40e7163) 

### Dartium status and sdk/lib Issues
- Dartium bots on all platforms green ~10 known test failures 
- dart2js bots are mostly green (about 20 errors outstanding to fix)
- Need to review about 60 errors with webgl (tests that are now passing) again dart2js Chrome.

### google3 Issues
- Dartium runs on google3 awaiting TAP run (sans scuba updates there are 100s need to regen w/ new numbers)
- content_shell not loading looks like a font issue (investigating)
- awaiting results on Dartium 50 run is ipv6-only on May 15 (ipv6-only is turned on June 1)

**Comment by whesse** [comment]
The dart2js chrome bots are testing dart2js output on Chromium's content_shell, using the content_shell built in Dartium.  So this has just been updated from 45 to 50.  But because we are not using the built-in Dart VM in the Dartium content_shell at all, we could just as easily use Chromium's content_shell.  Then we would be testing up-to-date versions of the Chrome DOM, more like the dart2js-linux bots that use Chrome.

I suggest this is the best way to fix these bots, but it will also involve a change to the status files.  So fixing the status files for Dartium 50 is an OK first step, or we could immediately jump to testing against Chrome 58 content_shell.

**Comment by terrylucas** [comment]
Bill's right we could use Chromium's content_shell but I'm tempted to wait until post Dartium 50 (good check that our content_shell is working especially with the font change needed for forge).  Moving forward, post Dartium 50, it seems that we won't be building any content_shells w/ VM so we should migrate to Chromium's 58 content_shell with a Dart's sdk/lib IDLs from Chromium 58 too.

The goal is to re-gen sdk/lib from IDLs every release or so of Chrome.

**Comment by whesse** [comment]
I can't find a download link for Chromium's or Chrome's content_shell, so we may need to upload it to cloud storage.  This would be a manual step, which we would need to do each time we wanted to test new versions.  I'm happy to leave this for a few months, while Dartium 50 is active.

**Comment by terrylucas** [comment]
I'm investigating if the font loading change, that forge needs in content_shell, can be built as an extension so we don't have to deal with building a new content_shell with each version of Chromium.

**Comment by terrylucas** [comment]
The roll is complete other items mentioned are now separate issues.
