### ISSUE TITLE
Function parameters need names for their arguments, not just types

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28281]
I get a warning in strong mode that disappears if I declare a parameter as void callback(T t) instead of void callback(T).  Is this intended?  The argument name in the function parameter is just a dummy name, and  should not have an effect, I think.  Here is the code:

class A<T> {
  void forEach(void callback(T t)) { 
    _nodes.forEach(callback);
  }

  Set<T> _nodes;
}

If the declaration is changed to
  void forEach(void callback(T)) {

then an error appears, claiming the type of callback is void <- (dynamic)

@floitschG

**Comment by lrhn** [comment]
This is the wonders of the current function type notation - if you only write one identifier, it is the name, not the type, of the parameter. The code
```
void forEach(void callback(T)) {
```
is equivalent to:
```
void forEach(void callback(dynamic T)) {
```
so the error is correct.

**Comment by floitschG** [comment]
We are working on a long-term plan to change the syntax for functions. At the moment this looks like the correct behavior. Closing as such.
