### ISSUE TITLE
Extending a @JS annotated class now fails in DDC (branch ddc-1.21.0-dev.11.3)

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#28291]
After the introduction of `lazyJSType` extending a `@JS` annotated class fails.

For example when extending "Polymer.Element" the code produced before was : 

    app_grid_style.AppGrid = class AppGrid extends dart.global.Polymer.Element {
     new() {
      super.new();
     }
    };

While now is : 

    app_grid_style.AppGrid = class AppGrid extends dart.lazyJSType(() => dart.global.Polymer.Element, "Polymer.Element") {
     new() {
      super.new();
     }
    };

This produces the error : `Class extends value [object Object] is not a constructor or null`

@vsmenon @jacob314

**Comment by jacob314** [comment]
We'll add some tests to make sure we don't break this functionality in ddc going forward.
It is purely a bug that we are emitting a lazyJSType in the extends clause. That makes no sense.

**Comment by dam0vm3nt** [comment]
great! thanks.
