### ISSUE TITLE
Calling dart function from js via window.opener fails

### ISSUE THREAD

**Issue by sorenbronsted** [dart-lang/sdk#28297]
I works in dartium but not chromium on Ubuntu when transpiled to javascript with with dart2js.
I have attached an sample. which show the error. Run it with pub serve and look in the console when other.html is loaded in another tab.
[sandbox.zip](https://github.com/dart-lang/sdk/files/692213/sandbox.zip)

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.

(Dartium is no longer supported)
