### ISSUE TITLE
Typo in String.padLeft() and padRight() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28298]
Please see
https://api.dartlang.org/stable/1.21.0/dart-core/String/padLeft.html
https://api.dartlang.org/stable/1.21.0/dart-core/String/padRight.html

> Pads this string on the left if it is shorther than width.

There should be **shorter** . The same type is in padRight()

**Comment by lrhn** [comment]
Has been fixed.
