### ISSUE TITLE
Renaming the same variable twice

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#28300]
Summary:
When renaming the same variable twice in a row, the changes from the first time, don't appear to be recognized.

What steps will reproduce the problem?
Create a new project generating sample code for a simple console application.
Replace the content of the main method with something like
```
  for (int i=0; i<10; i++){
    print(i);
  }
```
Place the curser over one of the 'i's and rename it to 'n'.
Try to rename the same 'n' again

What is the expected output? What do you see instead?

Expected:
The text box for 'Rename Local Vaiable' window should say 'n' as default.

Actual:
The default value is still 'i', and if you try to change it back to 'i', you get the following error message: "The new name must be different than the current name."
If you give it third name ie. 'm', only the marked one will be renamed, while the rest are still 'n'.

What version of the product are you using?
Dart version: 1.22.0-dev.5.0
![rename1](https://cloud.githubusercontent.com/assets/20222678/21766161/1393f3f2-d66d-11e6-9bf6-007b3a0b5966.png)
![rename2](https://cloud.githubusercontent.com/assets/20222678/21766165/1809c74a-d66d-11e6-8b88-aafa9f3f7b95.png)
![rename3](https://cloud.githubusercontent.com/assets/20222678/21766167/1a27c90a-d66d-11e6-9028-d4c0410526b1.png)

On what operating system?
Windows 10 (64bit) (was also the case when I tried the same on a Mac)

Please provide any additional information below.
If you rename the same variable from a different location, it seems to work as expected. If you start to rename something else, cancel and then go back, it also seems to work.
The same issue goes for renaming other things like methods, classes etc.

**Comment by mit-mit** [comment]
I can't seem to repro this. I'm using MacOS Sierra with IntelliJ IDEA 2016.3 and Dart SDK 1.22.0-dev.5.0.

@ksdboasit looks like you are using WebStorm? Which version?

**Comment by ksdboasit** [comment]
Oh, forgot to mention that, sry.
WebStorm 2016.3.2 in the screenshots, but the same thing happens (for me) in IntelliJ.

Just tried the same thing on our newer Mac (Sierra) with IntelliJ 2016.3. Same thing.

**Comment by mit-mit** [comment]
@devoncarew can you repro this?

**Comment by devoncarew** [comment]
I can repro it. I do not see the issue if - between the refactorings - I click away from the variable and then click back. Possibly some caching on the IntelliJ side?

/cc @alexander-doroshko @scheglov

**Comment by scheglov** [comment]
This looks as a server issue.
I see that the second time DAS returns the old `oldName` in the refactoring response.

```
debugStream: 1483981974071 => {"id":"15","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/domain_analysis.dart","offset":15688,"length":0,"validateOnly":true},"clientRequestTime":1483981974071}
debugStream: 1483981974072 <= {"id":"15","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":15686,"length":6,"elementKindName":"local variable","oldName":"stream"}}}
```

**Comment by alexander-doroshko** [comment]
For the reference: some more issues about renaming: https://github.com/dart-lang/sdk/issues/26497, https://github.com/dart-lang/sdk/issues/26331, https://github.com/dart-lang/sdk/issues/28097. Disclaimer: I didn't check if they are still actual.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2626433002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/266280f0c4f543c9c7ebb49971bcb80fb09a63f5
