### ISSUE TITLE
co19/Language/Types/Interface_Types/subtype_t27/t28 are too slow on debug precompiler

### ISSUE THREAD

**Issue by DmitryOlshansky-google** [dart-lang/sdk#28318]
This caused numerous timeouts lately.
```
FAILED: dartkp-dart_precompiled debug_x64 co19/Language/Types/Interface_Types/subtype_t28
Expected: Pass 
Actual: Timeout
CommandOutput[dartk]:
CommandOutput[precompiler]:
diagnostics: PID 19367 - process
    TID 19367:
    TID 19368:
    TID 19369:
    TID 20205:
    TID 20206:
    
    eu-stack: dwfl_thread_getframes tid 19367: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 19368: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 19369: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 20205: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 20206: Operation not permitted
    eu-stack: Couldn't show any frames.
```

**Comment by fsc8000** [comment]
Which buildbot was this (link)? There seems to be an issue with dumping stack traces of test that time out on some bots. We need to get at least a stack trace before changing the test expectations. Otherwise we won't notice them later.

**Comment by ErikCorryGoogle** [comment]
This runs in 1:59 now and sometimes still times out.  Changing from Slow to Timeout.
Example timeout: https://uberchromegw.corp.google.com/i/client.dart/builders/vm-kernel-precomp-linux-debug-x64-3-4-be/builds/330/steps/vm%20tests/logs/stdio
