### ISSUE TITLE
Missing concrete implementation for generic override mismatch

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#28313]
For this generic override mismatch the analyzer generates a 'missing concrete implementation' warning instead of an 'override mismatch':

```
abstract class A<E> {
  T f<T>(T a, T b(T c, E d));
}

abstract class B<E> implements A<E> {
  T f<T>(var a, T b(T c, E d)) => null; // 'var a' should have been 'T a'
}

class C<E> extends B<E> implements A<E> {}
```
generates `Missing concrete implementation of 'f'. (override.dart, line 9, col 7)` for the last line.

**Comment by lrhn** [comment]
I'm assuming this is with strong mode enabled?

Is it a mismatching override at all? You change the `a` parameter type from `T` to `dynamic`, which should be a safe override for all types `T`.

**Comment by johnniwinther** [comment]
It is _not_ with strong mode enabled.

**Comment by lrhn** [comment]
In that case, the types should be identical, all the type parameters should just be `dynamic`. I'm guessing this is similar to #28236.

**Comment by srawlins** [comment]
Analyzer now only reports:

> error • A value of type 'Null' can't be returned from method 'f' because it has a return type of 'T'. • a.dart:6:35 • return_of_invalid_type

I'm also confused about `var` inheriting...

**Comment by johnniwinther** [comment]
Given that the is was with Dart 1 semantics and that the analyzer correctly infers `var a` as `T a` for Dart 2 semantics we can close this issue.
