### ISSUE TITLE
String.replaceFirstMapped() and replaceAllMapped() documentation issues

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28311]
Please see https://api.dartlang.org/stable/1.21.0/dart-core/String/replaceFirstMapped.html

1. No valid range for [start] argument described. Please, add something like "If start is provided, it must be an integer in the range 0 .. string.length"

2.  

> If the value returned by calling replace is not a String, it is converted to a String using its toString method, which must then return a string.

Please, add the same statement to the  String.replaceAllMapped() documentation (https://api.dartlang.org/stable/1.21.0/dart-core/String/replaceAllMapped.html)

**Comment by floitschG** [comment]
https://codereview.chromium.org/2637103002/

I don't think we want to add the 2nd paragraph to the comments: the function type clearly requires to get a `String` back, so the only thing we need to worry about, is `null`.

@lrhn: should `null` be allowed or should we explicitly throw?

**Comment by lrhn** [comment]
Agree on the string.

We generally only say if a type *includes* null, the default is that null is not allowed (which will make non-null by default an easier switch!)

In practice, it works, but I don't want to document it, and when we go non-null-by-default, it will become non-nullable String as return type.

**Comment by sgrekhov** [comment]
Both `replaceAllMapped() `and `replaceFirstMapped()` have the same function type.
https://api.dartlang.org/stable/1.21.0/dart-core/String/replaceFirstMapped.html

> String replaceFirstMapped(
> Pattern from,
> String replace(
> Match match
> ), [
> int startIndex = 0
> ])

https://api.dartlang.org/stable/1.21.0/dart-core/String/replaceAllMapped.html

> String replaceAllMapped(
> Pattern from,
> String replace(
> Match match
> )
> )

But `replaceFirstMapped()` documentation contains statement about what is going on if not a String is returned, but `replaceAllMapped()` not. See an example, demonstrating why documentation should be consistent below

```dart
class C {
  String toString() {
    return "C";
  }
}

main() {
  print("1231".replaceFirstMapped("1", (m) {return new C();})); // prints C231, this is according to the documentation
  print("1231".replaceAllMapped("1", (m) {return new C();})); // prints C23C, documentation doesn't describe this case
}
```
