### ISSUE TITLE
Default constructor of Expando missing from autocomplete suggestions

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#28317]
```
// Copyright (c) 2017, Luke Church. All rights reserved. Use of this source code
// is governed by a BSD-style license that can be found in the LICENSE file.

import 'package:dart_mini_tests/dart_mini_tests.dart' as dart_mini_tests;

main(List<String> arguments) {
  print('Hello world: ${dart_mini_tests.calculate()}!');

  Expando<List<int>> exp = new E^

}

class A {

}
```

Code completion at ^ request results in no completion UI being displayed. 

![image](https://cloud.githubusercontent.com/assets/2978182/21813276/99e74a68-d74d-11e6-9d72-1abc7a435159.png)

intelliJ version:

```
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016
```
using Dart v1.21.0

**Comment by natebosch** [comment]
This shows up in the list of completion suggestions for me (at least when using `dart_language_server` but I'd assume intelliJ behaves the same).
