### ISSUE TITLE
User-defined list and map subtypes should be Isolate-serializable

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28328]
Currently, user-defined lists and maps aren't isolate-serializable (see [this comment](https://github.com/dart-lang/sdk/issues/28287#issuecomment-271662287)). The specific instance underneath an interface is an implementation detail, so this sets users up for pain when they don't realize they're passing a non-core collection implementation, or worse when the implementation of a type returned by a library changes between versions. Users also generally expect Isolate-serializability to be a superset of JSON-serializability, which supports user subclasses.

**Comment by lrhn** [comment]
This was fixed on Jan 12.
There is nothing inherently unserializable about user-defined lists or maps between "similar" isolates (spawned from the same root isolate using only `Isolate.spawn`, so should be running the same code).
As usual, anything that includes a closure cannot be serialized, but plain objects of any type should work.

**Comment by nex3** [comment]
> This was fixed on Jan 12.
> There is nothing inherently unserializable about user-defined lists or maps between "similar" isolates (spawned from the same root isolate using only `Isolate.spawn`, so should be running the same code).

Was this also fixed for sending these types between different isolates?
