### ISSUE TITLE
package:js is not converting Date objects in Chrome (Works in Dartium)

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#28329]
This is happening using Dart 1.21.0

Steps to reproduce:

1. clone https://github.com/johnpryan/dart-js-date-bug
2. run `pub serve`
3. observe a `DateTime` is displayed in Dartium
4. observe a `DateTime` is NOT displayed in Chrome

@jacob314

**Comment by johnpryan** [comment]
This is also difficult to work around because in Chrome, the object is a `JSObject`, not `JsObject` which throws a deprecation error at runtime: 

```dart
var date = new Date("10 06 2014");
```
```dart
@JS()
library date;

import 'package:js/js.dart';

external DateTime get date;
external num get time;
```
```dart
import 'dart:js';
import 'package:example/date.dart';
import 'package:js/js_util.dart';

void main() {
  print("date = ${date} is type ${date.runtimeType}");
  if (date is JSObject) {
    var timeNum = date as JSObject;
    var result = callMethod(timeNum, "getTime", []);
    var dateResult = new DateTime.fromMillisecondsSinceEpoch(result);
    print("RESULT = $dateResult");
  }
}
```

```
js_helper.dart:1730 Uncaught Error: Cannot resolve type 'JSObject'.
    at Object.wrapException (js_helper.dart:1730)
    at Object.throwTypeError (js_rti.dart:316)
    at StaticClosure.dart.main (main.dart:12)
    at _IsolateContext.eval$1 (isolate_helper.dart:462)
    at Object.startRootIsolate (isolate_helper.dart:120)
    at iterable.dart:276
    at iterable.dart:276
    at init.currentScript (iterable.dart:276)
    at iterable.dart:276
    at iterable.dart:276
```

**Comment by johnpryan** [comment]
I think this is a duplicate of https://github.com/dart-lang/sdk/issues/25886 - feel free to close if that's the case.

**Comment by daniel-v** [comment]
@johnpryan might be a duplicate. However I am still experiencing this issue. I use Dart 1.24.2. dart2js output does not not convert DateTime objects to Dates.

**Comment by johnpryan** [comment]
package:js seems to still be returning a JSObject, which is now not publicly available from dart:js:

https://github.com/johnpryan/js_date_test

**Comment by daniel-v** [comment]
Thanks for the heads up.

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.

(There is no longer Dartium, for example)

**Comment by johnpryan** [comment]
I can't re-open this issue, but the example provided still does not return a DateTime:

```
type = Mon Oct 06 2014 00:00:00 GMT-0700 (Pacific Daylight Time) is type NativeJavaScriptObject
```

**Comment by johnpryan** [comment]
How would one go about fixing this (using the Dart 2 SDK)? Right now a JS method needs to be used https://github.com/apptreesoftware/pikaday-dart/blob/master/lib/pikaday_dart_helpers.dart#L10
