### ISSUE TITLE
Analyzer error in analyzer unit test "all_the_rest_test"

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28339]
After turning on analyzer tests of the pkg unit tests, we see one failure on the buildbots:

WARNING|STATIC_WARNING|INVALID_OVERRIDE_NAMED|/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/pkg/analyzer/test/generated/all_the_rest_test.dart|365|8|5|Missing the named parameter 'packages' to match the overridden method from 'reset({List<List<String>> packages}) → void' from 'ResolverTestCase'.

Marking this in the status file pkg/pkg.status

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/41f8d695b0ab0e42e27426715121432cb4d08de1
