### ISSUE TITLE
Typo in Symbol() constructor documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28331]
Please see https://api.dartlang.org/stable/1.21.0/dart-core/Symbol/Symbol.html

> any of the above preceeded by any number of qualifiers, where a qualifier is a non-private identifier followed by '.'

Note ... **preceeded** ...

**Comment by natebosch** [comment]
I no longer see a typo in "preceded" on https://api.dartlang.org/stable/2.0.0/dart-core/Symbol/Symbol.html
