### ISSUE TITLE
Memory leaks in isolate reload tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28349]
cc/IsolateReload_ChangeInstanceFormat7: Fail
cc/IsolateReload_ClassAdded: Fail
cc/IsolateReload_ComplexInheritanceChange: Fail
cc/IsolateReload_ConstFieldUpdate: Fail
cc/IsolateReload_ConstantIdentical: Fail
cc/IsolateReload_ConstructorChanged: Fail
cc/IsolateReload_DanglingGetter_Class: Fail
cc/IsolateReload_DanglingGetter_Instance: Fail
cc/IsolateReload_DanglingGetter_Library: Fail
cc/IsolateReload_DanglingSetter_Class: Fail
cc/IsolateReload_DanglingSetter_Instance: Fail
cc/IsolateReload_DanglingSetter_Library: Fail
cc/IsolateReload_DirectSubclasses_GhostSubclass: Fail
cc/IsolateReload_DirectSubclasses_Success: Fail
cc/IsolateReload_EnumAddition: Fail
cc/IsolateReload_EnumDelete: Fail
cc/IsolateReload_EnumEquality: Fail
cc/IsolateReload_EnumIdentical: Fail
cc/IsolateReload_EnumIdentityReload: Fail
cc/IsolateReload_EnumReorderIdentical: Fail
cc/IsolateReload_EnumValuesToString: Fail
cc/IsolateReload_ExportedLibModified: Fail
cc/IsolateReload_FunctionReplacement: Fail
cc/IsolateReload_Generics: Fail
cc/IsolateReload_ImplicitConstructorChanged: Fail
cc/IsolateReload_ImportedLibModified: Fail
cc/IsolateReload_ImportedMixinFunction: Fail
cc/IsolateReload_LibraryDebuggable: Fail
cc/IsolateReload_LibraryHide: Fail
cc/IsolateReload_LibraryImportAdded: Fail
cc/IsolateReload_LibraryImportRemoved: Fail
cc/IsolateReload_LibraryLookup: Fail
cc/IsolateReload_LibraryShow: Fail
cc/IsolateReload_LiveStack: Fail
cc/IsolateReload_MainLibModified: Fail
cc/IsolateReload_MixinChanged: Fail
cc/IsolateReload_PendingSuperCall: Fail
cc/IsolateReload_PrefixImportedLibModified: Fail
cc/IsolateReload_SavedClosure: Fail
cc/IsolateReload_SavedClosure: Fail
cc/IsolateReload_SimpleConstFieldUpdate: Fail
cc/IsolateReload_SmiFastPathStubs: Fail
cc/IsolateReload_StaticTearOffRetainsHash: Fail
cc/IsolateReload_StaticValuePreserved: Fail
cc/IsolateReload_StaticValuePreserved: Fail
cc/IsolateReload_SuperClassChanged: Fail
cc/IsolateReload_TearOff_AddArguments2: Fail
cc/IsolateReload_TearOff_AddArguments: Fail
cc/IsolateReload_TearOff_Class_Identity: Fail
cc/IsolateReload_TearOff_Instance_Equality: Fail
cc/IsolateReload_TearOff_Library_Identity: Fail
cc/IsolateReload_TearOff_List_Set: Fail
cc/IsolateReload_TopLevelFieldAdded: Fail
cc/IsolateReload_TypeIdentity: Fail
cc/IsolateReload_TypeIdentityGeneric: Fail
cc/IsolateReload_TypeIdentityParameter: Fail

**Comment by rmacnak-google** [comment]
@johnmccutchan

**Comment by johnmccutchan** [comment]
Why do we care about memory leaks in cc tests? These processes are short lived.

**Comment by nex3** [comment]
@rmacnak-google I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.
