### ISSUE TITLE
Memory leak in log tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28347]
cc/Log_Basic: Fail
cc/Log_Block: Fail
cc/Log_Macro: Fail

**Comment by rmacnak-google** [comment]
@johnmccutchan

**Comment by johnmccutchan** [comment]
Why do we care about memory leaks in cc tests? These processes are short lived.

**Comment by mraleph** [comment]
@johnmccutchan before you look at it you don't know if this is a leak in the test or in the actual code we are shipping to the users. hence it's better to have test code that does not leak - makes finding actual leaks easier.

**Comment by johnmccutchan** [comment]
@mraleph https://codereview.chromium.org/2651013002/
