### ISSUE TITLE
Permission issues with stack sampling on linux

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28343]
The testing scripts are capturing stack traces of tests which time out which is very beneficial for debugging flaky tests.

It seems on some linux machines the `chrome-bot` user doesn't have permission for sampling stacks. We should find out why and fix it so we can get proper stack traces for all timeouts.

Example from [this failure](https://build.chromium.org/p/client.dart/builders/pkg-linux-release-be/builds/1994/steps/package%20unit%20tests/logs/stdio):
```
FAILED: none-vm-checked release_x64 pkg/kernel/test/baseline_type_propagation_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: PID 5042 - process
    TID 5042:
    TID 5044:
    TID 5046:
    TID 5051:
    TID 5055:
    TID 5067:
    TID 5816:
    TID 6182:
    
    eu-stack: dwfl_thread_getframes tid 5042: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5044: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5046: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5051: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5055: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5067: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 5816: Operation not permitted
    eu-stack: dwfl_thread_getframes tid 6182: Operation not permitted
    eu-stack: Couldn't show any frames.
```

on `slave84-c3`. It might be that all ComputeEngine slaves are having this issue.

/cc @mraleph @whesse

**Comment by fsc8000** [comment]
This is a buildbot configuration issue. I already opened an issue with Chrome infrastructure about this.

**Comment by mkustermann** [comment]
So I've looked into this and eu-stack is using ptrace to attach to the process. It seems like ptrace is disabled on the ComputeEngine VMs.

The way to fix it is:
```
# echo 0 > /proc/sys/kernel/yama/ptrace_scope
```

Turns out that chrome infrastructure is in fact installing a sysctl file to configure this, but it gets probably overruled:

```
# grep ptrace_scope /etc/sysctl.d/*
/etc/sysctl.d/10-ptrace.conf:kernel.yama.ptrace_scope = 1
/etc/sysctl.d/99-chrome-bot.conf:kernel.yama.ptrace_scope = 0
/etc/sysctl.d/99-gce.conf:kernel.yama.ptrace_scope=1
```

I think they get loaded in this order, so the `99-gce.conf` file overrides the settings the others have set.

**Comment by mkustermann** [comment]
@whesse Could you let CIT know about this setting and the fact that the GCE image overrides it? Would be nice to get this into the image.

**Comment by mkustermann** [comment]
I've made this change now manually on 21 `-c3` slaves. The change will persist until the next restart, but fortunately that doesn't happen very often.

**Comment by fsc8000** [comment]
@mkustermann Issue tracking this: https://bugs.chromium.org/p/chromium/issues/detail?id=646989

**Comment by mkustermann** [comment]
@fsc8000 Thanks for the link.

**Comment by mkustermann** [comment]
Chrome infrastructure rolled out a change which renamed the sysctl file (`99-chrome-bot.conf` -> `99-zz-chrome-bot.conf`) to make it get sourced last.
