### ISSUE TITLE
Broken link on Contributing page

### ISSUE THREAD

**Issue by ddrone** [dart-lang/sdk#28358]
URL: https://github.com/dart-lang/sdk/wiki/Contributing
"WritingApiDocumentation" link is broken

**Comment by mit-mit** [comment]
I think that bullet should be updated to something like this:

  * Improve the API reference docs at [api.dartlang.org](https://api.dartlang.org) by editing doc comments in the [Dart SDK repo](https://github.com/dart-lang/sdk/tree/master/sdk/lib). For more information on how to write API docs, see [Effective Dart: Documentation](https://www.dartlang.org/guides/language/effective-dart/documentation).

@kevmoo please review

**Comment by kevmoo** [comment]
Sounds good, @mit-mit – going to send a pull request?

**Comment by mit-mit** [comment]
No PRs on the wiki, I'll just edit it

**Comment by mit-mit** [comment]
Updated, closing
