### ISSUE TITLE
analyzer and front_end have a cyclic dependency that cannot be resolved by pub

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#28352]
Since they live in the same repo, does it make sense to change the dependency to be a path?
Running `pub get` in the linter was failing and this was one of the reasons.

**Comment by stereotype441** [comment]
Actually pub is ok with cyclic dependencies provided that its version constraint solver can find a set of compatible versions.  The issue at this point is that linter depends on a version of analyzer that doesn't exist (0.30.0-alpha.1).  I believe Phil is working on this.

**Comment by pq** [comment]
Yep.  Slowly working this out.

cc @bwilkerson

**Comment by alexeieleusis** [comment]
I think this is no longer a problem, contributing to the linter is a breeze again!
