### ISSUE TITLE
Missing support for '=' in named parameters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28364]
dartk appears to be missing support for using an equal rather than a colon between a named parameter and its default value. Output from test failures can be seen here: https://build.chromium.org/p/client.dart/builders/vm-kernel-precomp-linux-debug-x64-4-4-be/builds/362/steps/vm%20tests/logs/stdio.

**Comment by mraleph** [comment]
Seems to work in Fasta now.
