### ISSUE TITLE
Create patch release of 1.21 to back patch fix for issue 28072

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28375]
We have an external customer who has hit https://github.com/dart-lang/sdk/issues/28344 which
is a duplicate of  https://github.com/dart-lang/sdk/issues/28072 that has been fixed in 
1.22 dev release.

The custoomer is enquiring about the possibility of a patch release for 1.21 dev?

**Comment by whesse** [comment]
We will make a patch release with this fix.

**Comment by whesse** [comment]
Is the commit 53e93e8b053674b1a260d01156c92165438f8d36 the one that needs to be merged?  Does it merge cleanly?  Are there any other commits it is dependent on?  Instructions for making a merge-to-stable issue are at https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-dev-channel

**Comment by whesse** [comment]
Cherry-picking 53e93e8b053674b1a260d01156c92165438f8d36 to stable.

The commit merges cleanly.

**Comment by whesse** [comment]
The commit has been merged in version 1.21.1.
