### ISSUE TITLE
Uri.origin issue for empty host

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28377]
```dart
  var uri = new Uri(scheme: "http", host: "", port: 8080);
  print(uri.toString()); // http://:8080
  print(uri.origin); // Exception Bad state: Cannot use origin without a scheme: http://:8080
```
Origin is described at https://www.w3.org/TR/2011/WD-html5-20110405/origin-0.html#origin and I didn't find any limitations for an empty host there. Therefore, I believe, there should be no error.

If, though, an empty host is prohibited, then an error message `Cannot use origin without a scheme` is wrong

**Comment by lrhn** [comment]
The error message is wrong.
HTTP Uris don't generally allow omitting the host or authority. It's not something we check in the `Uri` class, but here we are handling an HTTP specific thing (since `origin` only works for HTTP[S] at all), and it doesn't make sense to have an HTTP origin with no host.

**Comment by lrhn** [comment]
Now has specific error message for the no-host case.
