### ISSUE TITLE
Test standalone/io/http_close_test has become flaky

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#28380]
This test became noticeably flaky after commit https://github.com/dart-lang/sdk/commit/51197954224cc98439670f08e0b5553c643b4e96.

Possibly there was a bug introduced in this change, or else the change made existing flakiness more likely to occur.  I am marking the test as flaky for now and not reverting the change so we can see if it seems to have other effects.

**Comment by kmillikin** [comment]
@lrhn

**Comment by mraleph** [comment]
I see other HTTP related flakes on the bots as well. Lasse could you please take a look given that you touched the code last?

**Comment by lrhn** [comment]
The triggering CL has been reverted.
I'm still unable to reproduce the problem locally, so I have no idea what is causing it.

**Comment by kmillikin** [comment]
We don't have an easy way to see if this test is still flaky.  In any case, it's marked in the status file.

The status files are probably a better place to look for presumed flaky tests (they're all marked there, and they don't necessarily all have issue filed against them).  Since this issue just repeats what's in the status file, I'm closing it.

**Comment by cskau-g** [comment]
The test should now be unflaky and state file exceptions have been removed.
