### ISSUE TITLE
one source for analysis options

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#28385]
We currently read analysis options from both `.analysis_options` and `analysis_options.yaml` files.
As part of Dart 2.0, I suggest we
- [-] add a new hint to detect `.analysis_options` files and recommend that they be renamed<br/>(land this as part of Dart 1.5) - https://codereview.chromium.org/2655073005/
- [x] update docs to reference `analysis_options.yaml`
- [x] update stagehand to generate `analysis_options.yaml` - https://github.com/google/stagehand/pull/362
- [x] update flutter repo
- [x] update sdk repo
- [x] remove support for reading `.analysis_options` files (completed in https://github.com/dart-lang/sdk/commit/8329bd7ca81e4ff0706cbc9603e2a1ca295ee3a8)

We could take the additional step of migrating analysis options into the `pubspec.yaml` file and do away with *both* of the above files.

**Comment by bwilkerson** [comment]
I like the idea of getting rid of the `.analysis_options` file.

I don't like the idea of integrating the options into the `pubspec.yaml` file because (a) not all projects use pub and (b) we'd still need the analysis options file format to support "included" options.

**Comment by travissanderson-wf** [comment]
how about a Dart-specific name for this file so that it calls itself out better in a busy root directory? I'd like `dart_analysis.yaml` or `dart_config.yaml` for a more general-purpose name

**Comment by johnbland-wf** [comment]
Changing the filename seems fine. Using a more specific name would be helpful to not conflict potential filenames from projects. Something more like `dart_analyzer.yaml` or `analyzer_config.yaml`

Of course moving it to `pubspec.yaml` works too.

**Comment by johnbland-wf** [comment]
Hehe... @travissanderson-wf beat me to it. :-) #quickdraw

**Comment by munificent** [comment]
> We currently read analysis options from both .analysis_options and analysis_options.yaml files.

Do we have numbers on how many existing uses of the former and the latter there are? Seems like we should coalesce to whichever is more common. In my personal experience, I've only ever seen `.analysis_options`. I didn't even know the latter was a thing.

**Comment by danrubel** [comment]
Some build systems do not support dot-files, thus I'd like to remove support for `.analysis_options`. I don't have any strong preferences as to the name we choose other than `analysis_options.yaml` is already in use.

**Comment by munificent** [comment]
I see [**3,045** .analysis_options files](https://github.com/search?utf8=%E2%9C%93&q=.analysis_options+in%3Apath&type=Code&ref=searchresults) and only [**72** analysis_options.yaml ones](https://github.com/search?utf8=%E2%9C%93&q=analysis_options.yaml+in%3Apath&type=Code&ref=searchresults).

I understand the motivation for the change, but it's going to be painful to 98% of existing uses.

**Comment by danrubel** [comment]
Hmmm.... Good point.

**Comment by Stargator** [comment]
I've only ever seen analysis_options.yaml from seeing a co-worker's Dart project and when I did the Tour of Heroes tutorial.

So I would have though the yaml file to be more prevalent.

I *highly* discourage merging with pubspec.yaml. While yes, pub is the current package manager. As we have seen in the NodeJS community, a contender for package manager may come later as more people get their hands on pub and may not like some design choices.

So it would be better to keep the analysis tooling separate from the package management tooling

**Comment by kwalrath** [comment]
What's the plan for `.analysis_options`? We have a note about it in https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file — basically that we expect support for the `.analysis_options` name to go away in the future, so use `analysis_options.yaml`. Is that note still correct? 

![image](https://user-images.githubusercontent.com/2164483/43093798-eb864a10-8e65-11e8-8167-720d70a99cbd.png)

**Comment by bwilkerson** [comment]
Yes, that's still the plan. I'm not sure when we will disable recognizing the old name, but we still plan to do so.

**Comment by kevmoo** [comment]
Now wouldn't be a bad idea – before Dart2 goes out!

**Comment by bwilkerson** [comment]
If we had the resources to do it now, I'd agree.

**Comment by kevmoo** [comment]
> Now wouldn't be a bad idea – before Dart2 goes out!

Sorry. I take that back. We're not going to do a merge-to-dev for this.

@kwalrath – I think it'd be fine to not mention it AT ALL in our docs. If folks are using `.analysis_options` they will get a warning in analyzer, I think...

**Comment by kwalrath** [comment]
@kevmoo I don't see any such warning when running the analyzer on a directory that contains `.analysis_options`:

```
t2$ dartanalyzer .
Analyzing t2...
No issues found!
t2$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.69.0
```

**Comment by kevmoo** [comment]
I *think* there is a hint w/ the analysis service.

**Comment by devoncarew** [comment]
I believe this was largely completed in https://github.com/dart-lang/sdk/commit/8329bd7ca81e4ff0706cbc9603e2a1ca295ee3a8 (~March 2020).

**Comment by kwalrath** [comment]
Sounds like I should update https://dart.dev/guides/language/analysis-options#the-analysis-options-file to say that `.analysis-options` is no longer supported.

Is that right?

**Comment by kevmoo** [comment]
> Sounds like I should update https://dart.dev/guides/language/analysis-options#the-analysis-options-file to say that `.analysis-options` is no longer supported.
> 
> Is that right?

YES!!!

**Comment by devoncarew** [comment]
> Is that right?

Yup; support for the older file was removed several stable releases ago.

**Comment by kwalrath** [comment]
Looks like it went away in [2.8](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#281---2020-05-06).
