### ISSUE TITLE
Quick fix suggests to import library from SDK by relative path

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28388]
SDK 1.22.0-dev.7.0
![image](https://cloud.githubusercontent.com/assets/4499789/21938968/b538cf3e-d9ce-11e6-8ecd-1be0b1a43785.png)

**Comment by alexander-doroshko** [comment]
(regression since SDK 1.22.0-dev.5.0)

**Comment by asashour** [comment]
Not able to reproduce with `Dart SDK version: 2.15.0-82.0.dev`.
