### ISSUE TITLE
Potential usages are not found since SDK 1.22.0-dev.5.0

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28386]
```
class Foo {
  var bar;
}

main(Foo x, var y) {
  x.bar; // hard reference  
  y.bar; // potential usage  
}
```
Potential usage is not reported by the Analysis Server starting from SDK 1.22.0-dev.5.0 and up to the latest 1.22.0-dev.7.0

**Comment by bwilkerson** [comment]
@scheglov Was this change intentional?

**Comment by scheglov** [comment]
This is a known issue.
Not sure if we actually want this feature.

**Comment by bwilkerson** [comment]
As a developer, I do.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2653493006

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/a483610a96ff59cb3142f9cc64a69e896c854a5c
