### ISSUE TITLE
Usages of classes/methods/etc. from the SDK source code are not found

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28387]
Windows 10, SDK 1.22.0-dev.7.0 x64. Usages of `bool` class are not reported by the analysis server. Minimal file to reproduce:
```
bool b;
```

**Comment by bwilkerson** [comment]
@scheglov Is this expected?

**Comment by scheglov** [comment]
Yes, this is is a known issue.

**Comment by scheglov** [comment]
This was a long multi-step implementation process...
The problem is fixed in fcd5f16d100937264f8949423fb0c6d4cbe0286d.

**Comment by scheglov** [comment]
Test that it actually works and does not regress.
https://codereview.chromium.org/2651103004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ebe04d131bea289b976b200c0455ebc40c71db72
