### ISSUE TITLE
JS interop works in Chrome, doesn't work in Dartium

### ISSUE THREAD

**Issue by helikopterodaktyl** [dart-lang/sdk#28393]
I'm trying to interact with cannon.js 3D physics library. I have generated a dart facade using the generation tool. It doesn't show any errors (works) on Chrome, but throws this on Dartium:

Class 'JSObjectImpl' has no instance method 'addBody'

Example code: https://github.com/helikopterodaktyl/cannondartrepro

Reproduction steps:
1. clone the repository
2. run pub serve
3. open localhost:8080, first using Chrome, then using Dartium

Dart VM version: 1.21.1 (Fri Jan 13 01:50:41 2017) on "windows_x64"

**Comment by kevmoo** [comment]
Not concerned with Dartium any more
