### ISSUE TITLE
DDC call methods in cascades are broken

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28394]
This Dart code:

```dart
void main() {
  var g = (int x) {print(x); return 0;};
  var f = () => g;
  var a0 = g.call(0);
  var a1 = g..call(1);
  var a2 = f().call(2);
  var a3 = f()..call(3);
}
```

Produces this JS:

```js
  tmp__test.main = function() {
    let g = dart.fn(x => {
      core.print(x);
      return 0;
    }, intToint$());
    let f = dart.fn(() => g, VoidToFn());
    let a0 = g(0);
    let a1 = ((() => {
      g(1);
      return g;
    })());
    let a2 = dart.dcall(f(), 2);
    let a3 = f();
    dart.dcall(/* Unimplemented unknown name */call, 3);
  };
```

I think that the `dcall` in the def of `a2` will work, but is unnecessary.

The code for `a3` just looks broken.

Is this something strong mode should be rejecting (i.e. something we don't want to support)?

**Comment by jmesserly** [comment]
DDC actually crashes on this example now. It looks like Analyzer is not resolving this correctly.

**Comment by srawlins** [comment]
Analyzer no longer crashes on this example.

**Comment by nshahan** [comment]
Looks resolved now in the kernel version of ddc.
