### ISSUE TITLE
Trying to optimise Imports

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#28403]
Analyzer%20Feedback%20from%20IntelliJ%0A%0A%23%23%20Version%20information%0A%0A-%20%60IDEA%20171.2272.15%60%0A-%20%601.21.1%60%0A-%20%60WS-171.2272.15,%20JRE%201.8.0_112-release-b676x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.12.2%20unknown,%20screens%202560x1440,%201200x1920%60%0A%0A%23%23%20Exception%0A%0APlease%20append%20the%20contents%20of:%0Afile:///private/var/folders/2j/ls4q_sd155q7lkksb0jbg6500000gn/T/report1.txt%0A%0A%60%60%60%0ADart%20analysis%20server,%20SDK%20version%201.21.1,%20server%20version%201.17.0,%20FATAL%20error:%20Failed%20to%20handle%20request:%20%7BclientRequestTime:%201484441488641,%20params:%20%7Bfile:%20/Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart%7D,%20method:%20edit.organizeDirectives,%20id:%204579%7D%0AAnalysisException:%20Cannot%20compute%20DART_ERRORS%20for%20/Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart%0ACaused%20by%20Unexpected%20exception%20while%20performing%20GatherUsedLocalElementsTask%20for%20source%20/Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart%0A%230%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:333)%0A%231%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%232%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%233%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%234%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1186)%0A%235%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%236%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1184)%0A%237%20%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:362)%0A%238%20%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:972)%0A%239%20%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:118)%0A%2310%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A%2311%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2312%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2313%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1150)%0A%2315%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2316%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2317%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2318%20%20%20%20%20Timer._createTimer.%3Canonymous%20closure%3E%20(dart:async-patch/timer_patch.dart:16)%0A%2319%20%20%20%20%20_Timer._runTimers%20(dart:isolate-patch/timer_impl.dart:385)%0A%2320%20%20%20%20%20_Timer._handleMessage%20(dart:isolate-patch/timer_impl.dart:414)%0A%2321%20%20%20%20%20_RawReceivePortImpl._handleMessage%20(dart:isolate-patch/isolate_patch.dart:148)%0A%0ACaused%20by%20Bad%20state:%20Unable%20to%20find%20(LogRecord%20entry)%20→%20void%20in%20[(null%20entry)%20→%20dynamic]%0A%230%20%20%20%20%20%20ElementImpl.findElementIndexUsingIdentical%20(package:analyzer/src/dart/element/element.dart:3153)%0A%231%20%20%20%20%20%20FunctionElementImpl.identifier%20(package:analyzer/src/dart/element/element.dart:4391)%0A%232%20%20%20%20%20%20ElementLocationImpl.ElementLocationImpl.con1%20(package:analyzer/src/dart/element/element.dart:3193)%0A%233%20%20%20%20%20%20ElementImpl.location%20(package:analyzer/src/dart/element/element.dart:2911)%0A%234%20%20%20%20%20%20ElementImpl.hashCode%20(package:analyzer/src/dart/element/element.dart:2800)%0A%235%20%20%20%20%20%20_HashSet._hashCode%20(dart:collection-patch/collection_patch.dart:564)%0A%236%20%20%20%20%20%20_HashSet.add%20(dart:collection-patch/collection_patch.dart:600)%0A%237%20%20%20%20%20%20UsedLocalElements.addElement%20(package:analyzer/src/generated/resolver.dart:10460)%0A%238%20%20%20%20%20%20GatherUsedLocalElementsVisitor.visitFunctionExpression%20(package:analyzer/src/generated/resolver.dart:3471)%0A%239%20%20%20%20%20%20FunctionExpressionImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:5330)%0A%2310%20%20%20%20%20NodeListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:7814)%0A%2311%20%20%20%20%20ArgumentListImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:431)%0A%2312%20%20%20%20%20RecursiveAstVisitor.visitArgumentList%20(package:analyzer/dart/ast/visitor.dart:596)%0A%2313%20%20%20%20%20ArgumentListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:427)%0A#14%20%20%20%20%20MethodInvocationImpl.visitChildren%20(package:analyzer/

**Comment by ds84182** [comment]
Unescaped:

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2272.15`
- `1.21.1`
- `WS-171.2272.15, JRE 1.8.0_112-release-b676x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.2 unknown, screens 2560x1440, 1200x1920`

## Exception

Please append the contents of:
file:///private/var/folders/2j/ls4q_sd155q7lkksb0jbg6500000gn/T/report1.txt

```
Dart analysis server, SDK version 1.21.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1484441488641, params: {file: /Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart}, method: edit.organizeDirectives, id: 4579}
AnalysisException: Cannot compute DART_ERRORS for /Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart
Caused by Unexpected exception while performing GatherUsedLocalElementsTask for source /Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (LogRecord entry) → void in [(null entry) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4391)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this on a newer version of Dart.
