### ISSUE TITLE
Incorrect output from modulus operation with negative number

### ISSUE THREAD

**Issue by xaguzman** [dart-lang/sdk#28408]
I stomped on this yesterday:

```dart
void main(){
  print('-2200 % 1000');  // I expected -200, got 800
}
```

See this [dartpad](https://dartpad.dartlang.org/48241343870e6b434f02da901c5dc14b)

**Comment by sigmundch** [comment]
Note that Dart % is the Euclidean modulo operator rather than remainder (JavaScript % is remainder). If you need reminder, in Dart it's a method on `num`, so your example above:

```dart
main() => print((-2200).remainder(1000));
```

Will print `-200` as you expected.
