### ISSUE TITLE
VM Service Protocol 3.5: ReloadReport has a field success not status

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#28400]
Hello :)

Actual response from reloadSources with dart 1.21.1:
```
{type: ReloadReport, success: true, details: {savedLibraryCount: 15, loadedLibraryCount: 1, finalLibraryCount: 16, shapeChangeMappings: []}}
```

runtime/vm/service/service.md says:
```
class ReloadReport extends Response {
  // Did the reload succeed or fail?
  bool status;
}
```

Mainly, status should be changed to success at least. This also means that the vm_service_drivers package needs to be updated.

Thanks,
 Andreas

**Comment by johnmccutchan** [comment]
@BlackHC thanks for pointing this out. The spec should be success and not status.
