### ISSUE TITLE
Continuing to error

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#28402]
Analyzer%20Feedback%20from%20IntelliJ%0A%0A%23%23%20Version%20information%0A%0A-%20%60IDEA%20171.2272.15%60%0A-%20%601.21.1%60%0A-%20%60WS-171.2272.15,%20JRE%201.8.0_112-release-b676x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.12.2%20unknown,%20screens%202560x1440,%201200x1920%60%0A%0A%23%23%20Exception%0A%0APlease%20append%20the%20contents%20of:%0Afile:///private/var/folders/2j/ls4q_sd155q7lkksb0jbg6500000gn/T/report.txt%0A%0A%60%60%60%0ADart%20analysis%20server,%20SDK%20version%201.21.1,%20server%20version%201.17.0,%20error:%20Task%20failed:%20GatherUsedLocalElementsTask%20for%20source%20/Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart%0AUnexpected%20exception%20while%20performing%20GatherUsedLocalElementsTask%20for%20source%20/Users/rayk/WebstormProjects/uncertainty/lib/shared/logger.dart%0A%230%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:333)%0A%231%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%232%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%233%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%234%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1186)%0A%235%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%236%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1184)%0A%237%20%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:362)%0A%238%20%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:972)%0A%239%20%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:118)%0A%2310%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A%2311%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2312%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2313%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1150)%0A%2315%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2316%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2317%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2318%20%20%20%20%20Timer._createTimer.%3Canonymous%20closure%3E%20(dart:async-patch/timer_patch.dart:16)%0A%2319%20%20%20%20%20_Timer._runTimers%20(dart:isolate-patch/timer_impl.dart:385)%0A%2320%20%20%20%20%20_Timer._handleMessage%20(dart:isolate-patch/timer_impl.dart:414)%0A%2321%20%20%20%20%20_RawReceivePortImpl._handleMessage%20(dart:isolate-patch/isolate_patch.dart:148)%0A%0ACaused%20by%20Bad%20state:%20Unable%20to%20find%20(LogRecord%20entry)%20→%20void%20in%20[(null%20entry)%20→%20dynamic]%0A%230%20%20%20%20%20%20ElementImpl.findElementIndexUsingIdentical%20(package:analyzer/src/dart/element/element.dart:3153)%0A%231%20%20%20%20%20%20FunctionElementImpl.identifier%20(package:analyzer/src/dart/element/element.dart:4391)%0A%232%20%20%20%20%20%20ElementLocationImpl.ElementLocationImpl.con1%20(package:analyzer/src/dart/element/element.dart:3193)%0A%233%20%20%20%20%20%20ElementImpl.location%20(package:analyzer/src/dart/element/element.dart:2911)%0A%234%20%20%20%20%20%20ElementImpl.hashCode%20(package:analyzer/src/dart/element/element.dart:2800)%0A%235%20%20%20%20%20%20_HashSet._hashCode%20(dart:collection-patch/collection_patch.dart:564)%0A%236%20%20%20%20%20%20_HashSet.add%20(dart:collection-patch/collection_patch.dart:600)%0A%237%20%20%20%20%20%20UsedLocalElements.addElement%20(package:analyzer/src/generated/resolver.dart:10460)%0A%238%20%20%20%20%20%20GatherUsedLocalElementsVisitor.visitFunctionExpression%20(package:analyzer/src/generated/resolver.dart:3471)%0A%239%20%20%20%20%20%20FunctionExpressionImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:5330)%0A%2310%20%20%20%20%20NodeListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:7814)%0A%2311%20%20%20%20%20ArgumentListImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:431)%0A%2312%20%20%20%20%20RecursiveAstVisitor.visitArgumentList%20(package:analyzer/dart/ast/visitor.dart:596)%0A%2313%20%20%20%20%20ArgumentListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:427)%0A%2314%20%20%20%20%20MethodInvocationImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:7426)%0A%2315%20%20%20%20%20RecursiveAstVisitor.visitMethodInvocation%20(package:analyzer/dart/ast/visitor.dart:992)%0A#16%20%20%20%20%20MethodInvocationImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:7

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
