### ISSUE TITLE
Dart's @MirrorsUsed annotations don't work when importing with `part` (dart2js)

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#28406]
I have a bunch of `@MirrorsUsed(targets: '...')` annotations, however the problem with them is that because all `part` statements go below them, `dart2js` complains. For example, here's how it goes in the file:

    library foo;
    @MirrorsUsed(targets: "foo.BarClass")
    import "dart:mirrors";
    part "bar_class.dart";

And, when compiled, `dart2js` shows the following warning:

    Hint: Can't find 'BarClass' in the library 'foo'.
    Is 'BarClass' spelled right?

The compiled file works, but the resulting file size is significantly larger than it should be precisely because `dart2js` cannot make use of the mirror annotation.

Is there a way to make this work with `part`?

**Comment by zoechi** [comment]
cross-link http://stackoverflow.com/questions/41668863/darts-mirrorsused-annotations-and-part-directives-how-to

**Comment by snitko** [comment]
Yes, sorry, was not sure which is a better place to ask. Let me know which post should I remove.

**Comment by zoechi** [comment]
You can keep both. I just want to make sure whatever Google search brings up first will lead to the answer for the next one running into the same issue ;-)

**Comment by snitko** [comment]
I believe I misdiagnosed the problem. I will close the issue now. Apologies.

**Comment by sigmundch** [comment]
thanks for the update!
