### ISSUE TITLE
dartk: Calling a setter via function syntax should work

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28418]
From `tests/language/setter_no_getter_call_test.dart`:

```dart
import "package:expect/expect.dart";

var topLevelClosure;

get topLevel => topLevelClosure;
set topLevel(var value) { }

initialize() {
  print("initializing");
  topLevelClosure = (x) => x * 2;
}

main() {
  initialize();
  var x = topLevelClosure(2);
  Expect.equals(4, x);

  x = topLevel(3); // dartk rewrites it to NSM
  Expect.equals(6, x);
}
```

/cc @kmillikin & #28263

**Comment by lrhn** [comment]
I'm not absolutely sure that this should work. Are you sure the example is correct?
If the spec says so, I fear that might just be an accident.

The `topLevel(3)` call should try to call the non-existing getter for `topLevel`, then call the result as a function. That's reasonably rewritten into a NSM throw.
In the original test case, there is also a `get topLevel => topLevelClosure;` declaration that makes this work. Without that, it's a runtime error.

**Comment by mraleph** [comment]
@lrhn one line got accidentally omitted from the test.

```dart
get topLevel => topLevelClosure;
```

**Comment by mraleph** [comment]
Fasta is doing the right thing here.
