### ISSUE TITLE
fasta: Exception/Stacktrace variables in catch block should be final

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28410]
From the `language/try_catch_on_syntax_test` test.

/cc @kmillikin & #28263

**Comment by mraleph** [comment]
Still happens with fasta, see:  

`language/try_catch_on_syntax_test/10`
`language/try_catch_on_syntax_test/11`

**Comment by peter-ahe-google** [comment]
Proposed fix: [CL 2775163003](https://codereview.chromium.org/2775163003).
