### ISSUE TITLE
pub.dartlang.org won't work thru firewall but github does

### ISSUE THREAD

**Issue by theiceguy** [dart-lang/sdk#28419]
Make it so all pub packages are mirrored in github, and can be downloaded via github.

**Comment by lrhn** [comment]
That's not really a thing the Dart team can do. Pub packages are managed by their individual authors, and while most of them do use github, not all do, and we don't want to force anyone to do so (even if we could).

If you're only talking about the Dart team authored packages, then *most* of them are on Github, like https://github.com/dart-lang/collection. A few only exists inside the SDK repo, but that is technically on Github (https://github.com/dart-lang/sdk/tree/master/pkg). 

Is there a specific package you are interested in?

**Comment by theiceguy** [comment]
Maybe we just need a sample pubspec.yaml where all the base packages are pulled down from github?  And there is no dependency whatsoever on pub.dartlang.org.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1501
