### ISSUE TITLE
jinja2, required for html library generation, requires markupsafe module

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28414]
The scripts to generate the html libraries, like tools/dom/scripts/go.sh, require a python module called markupsafe to be installed on your system.

This should be documented by a README file in tools/dom or tools/dom/scripts, and it would be good to make go.sh and/or dom.py emit a helpful warning message.

The dependency is there because of the use of the jinja2 templating system: http://jinja.pocoo.org/docs/2.9/intro/#markupsafe-dependency

A different issue discusses moving from the jinja2 templating system to a dart system like moustache:
#24937

**Comment by alan-knight** [comment]
Seems related to #23593
