### ISSUE TITLE
Please, clarify Isolate.removeErrorListener() description

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28415]
The [description](https://api.dartlang.org/stable/1.21.0/dart-isolate/Isolate/removeErrorListener.html) for method Isolate.removeErrorListener() reads:

> void removeErrorListener(
> SendPort port
> )
> Stop listening for uncaught errors through port.
> 
> **The port should be a port that is listening for errors through addErrorListener.** This call requests that the isolate stops sending errors on the port.
> 
> If the same port has been passed via addErrorListener more than once, only one call to removeErrorListener is needed to stop it from receiving errors.
> 
> **Closing the receive port at the end of the send port** will not stop the isolate from sending errors, they are just going to be lost.

Please, clarify two issues:

1. Supplied port is not listening, i. e. it was not supplied to addErrorListener() earlier. Will `removeErrorListener()` throw error or just do nothing?

2. What does `Closing the receive port at the end of the send port` means? I guess, it means calling method `close()` on `ReceivePort` instance that corresponds to given send port. Anyways, I think it should be stated in more clear words.

**Comment by floitschG** [comment]
@lrhn had already done most of the work.

A small follow-up CL: https://codereview.chromium.org/2829723002
