### ISSUE TITLE
infra: Get compute engine slaves to have apport disabled and core_pattern set correctly for our slaves

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28439]
To allow us to do core dump archiving, we need a pid-specific core pattern and need to prevent apport from taking control over it.

Disabling apport in `/etc/default/apport`:
```
# set this to 0 to disable apport, or to 1 to enable it
# you can temporarily override this with
# sudo service apport start force_start=1
enabled=0
```

We should also get `/proc/sys/kernel/core_pattern` set to:
```
$ echo 'core.%p' >  /proc/sys/kernel/core_pattern  
```

I think both of these things can be handled via puppet so it doesn't necessarily need to be in the image.

@whesse Could you follow up with CIT about this?

/cc @mraleph

**Comment by mraleph** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=686652

**Comment by mkustermann** [comment]
Was fixed.
