### ISSUE TITLE
Clarify what methods are on Null and bottom

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28430]
Issue https://github.com/dart-lang/sdk/issues/28024 tracks moving Null to the bottom of the type hierarchy.  We need to clarify in the specification what methods are available on the `Null` type (and the `bottom` type if the answer is different).

The natural answer based on a substitutability principle is that all methods should be allowed to be called on `Null`, and this has been the de facto interpretation of the current Dart spec for `bottom` (even though it does not make this explicit).

```dart
List<int> l = new List<Null>();
l[0].abs(); 
```

A substitution principle suggests that replacing `l` with its definition should still be well-typed.

This is not definitive though.  We can certainly choose to provide stronger checking, and it's not clear that there are practical reasons not to.   There are certainly good reasons to do the stronger checking.  The use of `Future<Null>` to indicate a `Future` whose value should not be used is very suggestive.  We would lose substantial static checking if all uses of the result of a `Future<Null>` became valid.

```dart
Future<Null> dontUseMyResult f = ...;
dontUseMyResult.then((n) => n.abs()); // No warnings?
```

cc @floitschG @lrhn @eernstg @munificent @scheglov @bwilkerson @stereotype441

**Comment by leafpetersen** [comment]
Assigning to @lrhn since you wrote up the initial spec - please assign back to me if you'd prefer me to take this.

**Comment by leafpetersen** [comment]
For what it's worth, I think my preference is to treat `Null` as having nothing but the `Object` methods.

When and if we add `Nothing` (aka true non-nullable `bottom`) we should treat this as having all methods, since that matches the expected use cases (`throw` and functions which do not return).

We could consider in the meantime treating `bottom` (that is, the static type of `throw` in the current spec draft) as also having all methods.  Essentially then for the meantime `bottom` and `Null` become variants on a common bottom type, much as `dynamic` and `Object` are equivalent types with different error and warning behavior.

**Comment by lrhn** [comment]
The idea behind the spec documentation (for Dart 1) is that `Null` is only extending `Object`. It has no other methods (which is clear since it's declared as `class Null { }`).

For *subtyping* and *assignability*, it's considered a subtype of any type, extended to type parameters and function return types in the predictable way, but it is not actually *extending* those types. It's a subtype by fiat, not by subclassing.

**Comment by leafpetersen** [comment]
Sounds good to me - I think this matches my preferences as well.  Does this need to be clarified in the spec, or do you feel it's already implied?  It wasn't clear to me reading through it that this was the intended interpretation, for what it's worth.

**Comment by munificent** [comment]
SGTM too.

**Comment by lrhn** [comment]
I think the spec is correct as-is, but for clarity, I might add some commentary (https://codereview.chromium.org/2641873003/).
It already says: 
> The `Null` class declares no methods except those also declared by `Object`.

There might be a few other edge cases that we need to consider (like in an async function, a plain `return;` is only allowed if `Future<Null>` is assignable to the return type, but that's all future types now - probably safe, but a slight change from before, and probably to be changed again when we can write `Future<void>`).
