### ISSUE TITLE
Retry failing tests with flaky statuses

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28447]
As part of the gardening effort, we're adding a lot of flaky statuses to the status files, e.g. "Pass, Timeout", "Pass, RuntimeError", etc.. One thing we might do to avoid missing consistent failures in these tests, rather than flaky failures, is to re-run them when they fail. If we re-run them, say, 5 times and never see a successful run in those 5 times, the test should be reported as failing, and the buildbot should turn red.

**Comment by mraleph** [comment]
I don't think we should even have tests like this in the code base. Marking test "Pass, Timeout" is like sweeping the issue under the rug. Instead of rerunning tests we should work towards cleaning status files from these expectations.

**Comment by zanderso** [comment]
@mraleph I agree, but that sounds like a longer-term effort. At the moment, there is no notification that a test with a flaky status marker is failing on every run. That is, there is no notification if a change causes a test marked "Pass, Timeout" or "Pass, RuntimeError" to go from passing most of the time to failing all of the time. Until we get rid of the flaky statuses altogether, we should have some way of signaling consistent failure.
