### ISSUE TITLE
Frequent reanalysis of project

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28448]
While trying to edit in the analyzer, I have the impression that the IDE is only half of the time working with a complete analysis. Completion and navigation frequently doesn't work and the "analyzing" status line is active frequently.

IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_102-google-v7-137518472-137512069 amd64
JVM: OpenJDK 64-Bit Server VM by Google Inc.

artanalyzer version 1.22.0-edge.626cd0a4d4f9473bcb3dc7821e3c92a409461f5f

**Comment by bwilkerson** [comment]
Have you updated the `dart.server.additional.arguments` registry entry to include `--enable-new-analysis-driver`?

**Comment by bwilkerson** [comment]
@floitschG ping

**Comment by floitschG** [comment]
No. I have/had done no such thing.

**Comment by bwilkerson** [comment]
Then you're almost certainly using the old analysis driver, which is known to have this kind of issue. If you switch to using the new driver (in a bleeding edge build) and still see the problem, please let us know.

**Comment by floitschG** [comment]
Sounds good.
Closing this issue then.
