### ISSUE TITLE
Debugging inconsistencies 

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28453]
In the following code the debugger can stop at lines "var x", "x = 43", "var y", "y = x", but not at line "x = libVariable".

```dart
var libVariable;

main() {
  libVariable = 42;
  print(libVariable);
  var x;
  x = 43;
  print(x);
  x = libVariable;
  print(x);
  var y;
  y = x;
  print(y);
}
```

And we can normally next over awaits, but it doesn't work for "await for". In the following example, the first block next's nicely, but the second block doesn't. It instead stops at the "naturalsTo" part 4 times (!) before going into "_RootZone.runUnary".

```dart
import 'dart:async';

main() async {
  {
    // This works nicely
    int count = 0;
    Stream<int> stream = naturalsTo(5);
    StreamIterator<int> iterator = new StreamIterator(stream);
    while(true) {
      if (!await iterator.moveNext()) break;
      print(iterator.current);
      count++;
    }
    print("Saw $count numbers.");
  }
  {
    // This doesn't
    int count = 0;
    await for (var num in naturalsTo(5)) {
      print(num);
      count++;
    }
    print("Saw $count numbers.");
  }
}

Stream<int> naturalsTo(int n) async* {
  int k = 0;
  while (k < n) {
    k++;
    yield k;
  }
  yield 42;
}
```

**Comment by mhausner** [comment]
Added additional debug step checks in 197f1411001f47e3504f670ad155230452570c0d

**Comment by jensjoha** [comment]
Just revisited this and realized and I reported two issues in one (where one was fixed).
I'm leaving this closed, but submitted https://github.com/dart-lang/sdk/issues/28916 for the stepping over await for thing.
