### ISSUE TITLE
Lisense section of README.md should mention PATENTS

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#28455]
PATENTS is a part of license language, I think.

**Comment by mit-mit** [comment]
Please see https://github.com/dart-lang/sdk/blob/master/PATENTS

**Comment by Cat-sushi** [comment]
I meant that README.md should mention the PATENTS file as well as the LICENS file.

**Comment by Cat-sushi** [comment]
Newly I've filed another issue. #28471
