### ISSUE TITLE
HandshakeException: Handshake error in client ... waiting for 1 threads to check in

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28451]
I just had a Dart program running in a Dart VM on a Raspberry Pi die with the following messages:

```
HandshakeException: Handshake error in client (OS Error: errno = 0)
Attempt:11 waiting for 1 threads to check in
Attempt:12 waiting for 1 threads to check in
Attempt:13 waiting for 1 threads to check in
Attempt:14 waiting for 1 threads to check in
Attempt:15 waiting for 1 threads to check in
Attempt:16 waiting for 1 threads to check in
Attempt:17 waiting for 1 threads to check in
Attempt:18 waiting for 1 threads to check in
Attempt:19 waiting for 1 threads to check in
Attempt:20 waiting for 1 threads to check in
Attempt:21 waiting for 1 threads to check in
Attempt:22 waiting for 1 threads to check in
Attempt:23 waiting for 1 threads to check in
Attempt:24 waiting for 1 threads to check in
Attempt:25 waiting for 1 threads to check in
Attempt:26 waiting for 1 threads to check in
Attempt:27 waiting for 1 threads to check in
Attempt:28 waiting for 1 threads to check in
Attempt:29 waiting for 1 threads to check in
...
Attempt:612 waiting for 1 threads to check in
Attempt:613 waiting for 1 threads to check in
Attempt:614 waiting for 1 threads to check in
Attempt:615 waiting for 1 threads to check in
$
```

The handshake issue seems to be a message from BoringSSL. The script was doing various things with HTTP and WebSocket objects at the time.

I have no other information, sorry. I can't easily give you reproduction code since it was all tightly coupled with the random home automation hardware I have hooked up to my network.

**Comment by rmacnak-google** [comment]
@a-siva I've seen safepoints behave this way before when my Pi was running low on memory.

**Comment by a-siva** [comment]
@rmacnak-google what test were you running when you went low on memory? We could simulate that on a regular desktop by setting a low new and old space limit.

**Comment by rmacnak-google** [comment]
Random tests sometimes display this behavior when running the test suite with multiple cores. I think you have the get unlucky to have just the right amount of memory remaining to get this behavior instead of a quick crash.

**Comment by mraleph** [comment]
This has been open for 1 year with no progress. Assuming stale. Please reopen if the issue is still present.
