### ISSUE TITLE
Debugger doesn't stop on 'break' and 'continue'

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28473]
Say I have something like this:
```dart
while(true) {
  if(something_complicated) {
    break;
  }
  ...
}
print("After loop");
```

It would be useful to be able to next through the code, and also stop on the 'break' (equivalently for 'continue'). Currently it just goes directly to the print after the loop when I 'next' on the if statement.

As a side note, debugging plain javascript in Chrome does allow me to do this. Debugging the dart2js javascript in chrome doesn't show me being on the break or continue line (when keeping the source map stuff), but does seem to have 'an extra stopping position' when stepping.

**Comment by mhausner** [comment]
To implement this, we'd have to add DebugStepCheck calls in front of break and continue jumps, at the price of performance of unoptimized code, and code size.

**Comment by jensjoha** [comment]
The same argument could be made against every insertion of DebugStepCheckInstr.

Grep'ing in in the patched_sdk yields 50 usages of "continue;" and 190 usages of "break;". This naturally doesn't count user-code, but still it seems like relatively low numbers to me.

Of course it shouldn't be my decision, but as as a comparison, instrumenting runtime/vm/flow_graph_builder.cc to print a line for every insertion of DebugStepCheckInstr and then running
```dart
main() {
  print("Hello World!");
}
```

prints the instrumentation text 2039 times.

**Comment by mhausner** [comment]
Compiling a hello world program with dart2js inserts just shy of 900 DebugStepChecks if I instrument EffectGraphVisitor::VisitJumpNode. CL to follow.

**Comment by mhausner** [comment]
This has been checked in at cc8139350d1afa0410dd75a27f685877e106cf03
