### ISSUE TITLE
The "PATENTS" file should be mentioned by the "Lisense" section of "README.md" file as well as the "LICENSE" file

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#28471]
The License section of the README.md file already mention existence of the file of LICENSE, on the other hand it doesn't mention the existence of the file of PATENTS.
To avoid misunderstanding, The "PATENTS" file should be mentioned by the "Lisense" section of "README.md" as well as the "LICENSE" file, I think.

For example, following makes things better,

See [LICENSE](https://github.com/dart-lang/sdk/blob/master/LICENSE) and [PATENTS](https://github.com/dart-lang/sdk/blob/master/PATENTS).

**Comment by mit-mit** [comment]
LICENSE and PATENTS are legal documents, so not something we can just change. But I like the idea of linking to PATENTS from the readme.

**Comment by Cat-sushi** [comment]
Thank you.
