### ISSUE TITLE
"Unused import" analyzer message should say which import

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28482]
This message:

```
[info] Unused import. (foo.dart:22:8)
```

...would be more useful in certain situations if it mentioned what the import was. For example, say you are looking at the output of the analyzer from a bot, and it lists 5 unused imports. You've deleted two, then you went to lunch, then you came back. You don't remember how many you did. Now the line numbers aren't quite right any more, and it's hard to guess which are unused. If it mentioned the path of the unused import, you could just go based on the paths instead of the line numbers.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/37140
