### ISSUE TITLE
How do I create a constructor reference?

### ISSUE THREAD

**Issue by gnardini** [dart-lang/sdk#28485]
Sorry if this isn't the place for this type of questions, please direct me to somewhere else if needed.

Suppose I have the following:

```dart
class SomeClass {
  SomeClass(this.var);
  static SomeClass fromString(String value) => new SomeClass(value);

  final String var;
} 

List<String> someList = ...;
someList.map((value) => new SomeClass(value)); // (1)
someList.map(SomeClass.fromString); // (2)
```
I don't like (1) because I think it's unnecessarily verbose.
I don't like (2) because, even though it's better, using fromString is kind of weird, at first glance it looks like a constructor, which is confusing. Also, it's just acting as a 'man in the middle', which I'd like to avoid.
I would like to use a reference to the default constructor. In Java, I'd do `someList.map(SomeClass::new);`. Is it possible to do something like that on Dart?

Of course, thanks a lot for your help and for making this great language :) I'm sorry if this question has been asked before (it probably has), but I couldn't find an answer :(

**Comment by zoechi** [comment]
Currently constructor tear-offs are not supported. Your (1) and (2) are the ways to go.
They were in a while but the syntax wasn't satisfying and they removed it recently, to come up with a better solution eventually.

For support question you can ask on StackOverflow, https://gitter.im/dart-lang/TALK-general, https://groups.google.com/a/dartlang.org/forum/#!forum/misc and probably others

**Comment by gnardini** [comment]
Thanks for the quick answer! I'll keep an eye out for the new solution :)
