### ISSUE TITLE
Dart2js/VM/Analyzer doesn't catch conflict between constructor and mixin.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28487]
Example:
```dart
class C {
  C.foo() { print("Hello"); }
}
class M {
  foo() { print("World"); }
}
class D = C with M;
main() {
  new D.foo().foo();
}
```
Prints "Hello" then "World" in VM, prints "Hello" then crashes in dart2js, finds no problems in analyzer.

This should be a compile-time error - there is a conflict between the implicit D.foo constructor and the mixed-in D.foo instance method. If those had been written in the same class, all implementations do catch the conflict, but the mixin application is subject to the same rules (spec says that if a class with the same instance declarations and constructors would have a compile-time error, so would the mixin application).

(Odd corner, probably not worth fixing before switching to the common front-end, and even if it is, it's probably only for the analyzer).

**Comment by srawlins** [comment]
dart2js, CFE, and analyzer still accept this program. Should this still be an error?

**Comment by srawlins** [comment]
Reading this again; @lrhn @eernstg should this still error? dart2js still accepts this.

**Comment by eernstg** [comment]
I don't see a reason why this would be an error, and I also don't see any error messages (or unexpected behaviors) from any tools when the same class body declares a constructor with a name of the form `A.foo` and an instance member named `foo`.

```dart
class C {
  C.foo() {
    print("Constructor");
  }
}

mixin M {
  void foo() => print("Method");
}

class D = C with M;

class A {
  A.foo() {
    print('Constructor');
  }
  void foo() => print('Method');
}

void main() {
  D.foo().foo();
  A.foo().foo();
}
```

It is true that the mixin application `C with M` gives rise to an implicitly induced constructor whose name is `D.foo`, but that's no worse than the coexistence of the constructor `A.foo` and the instance method `foo` in `A`.

The crash in dart2js would be seen with `dart compile js` today. I don't see any crashes there, either.

I believe this issue can be closed.

**Comment by lrhn** [comment]
Agree, not a bug.

There is no rule against a constructor with the same base name as an instance member.
There can't be a static member with the same base name as a constructor, because they're invoked in the same way, but constructor base names are not in the lexical scope so they never intercept either instance members.
