### ISSUE TITLE
Type system should treat function valued getters as methods?

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#2849]
Given

interface I { int f();}

class C1 implements I {
&nbsp;&nbsp;&nbsp;int f() =&gt; 1;
}

typedef int G();

is

class C2 implements I {
&nbsp;&nbsp;G get f() {return () =&gt; 2;}
}

a legitimate implementation of I? Currently, this is disallowed.  Yet some have requested such functionality. After all, 

new C2().f();

works just as well as

new C1().f();

**Comment by lrhn** [comment]
With the type system of Dart 2, we are going in the opposite direction from this.
I can guarantee that this will not happen short of another complete replacement of the type system.
