### ISSUE TITLE
Typo in Uri.replace() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28490]
Please see https://api.dartlang.org/stable/1.21.1/dart-core/Uri/replace.html

> This method is different from Uri.resolve which overrides in a hierarchial manner, and can instead replace each part of a Uri individually.

Note ...hierarchial... There should be ...hierarchi**C**al...

**Comment by kevmoo** [comment]
Good catch!

https://codereview.chromium.org/2655883002
