### ISSUE TITLE
Allow application provided extensions to Observatory

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#28496]
One possibility:

* Application runs own web server on a random port.
* Application registers a label and Uri via some to-be-defined function in `dart:developer`.
* Observatory shows list of links next to Isolate, when user clicks link, navigate to an Observatory page that has an iframe embedded in it. The iframe loads the Uri registered.

Some thoughts:

* Application page will probably need to know the Uri to the service protocol port. Should we pass this as a Uri query parameter? Or via some other mechanism?

**Comment by johnmccutchan** [comment]
@B3rn475 FYI

**Comment by mraleph** [comment]
Nothing is happening in this area, AFAIK. Assuming stale.
