### ISSUE TITLE
Better typing for Future methods

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28494]
Can we use generic methods and/or `FutureOrT` to type the rest of the `Future` methods more precisely?  I hit this one in our internal code base:

https://api.dartlang.org/stable/1.21.1/dart-async/Future/forEach.html

Seems like it ought to be something like:
```dart
Future<S> forEach<S, T>(Iterable<T> input, S f(T element))
```

**Comment by floitschG** [comment]
The return type is not typeable yet. We need to wait for `void` to be allowed as generic type.

https://codereview.chromium.org/2657563003
