### ISSUE TITLE
Field-less mixins should be allowed for const constructors.

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#28492]
Const constructors should be allowed if mixed-in classes have no fields:

```
class Super {}
class Mixin {}
class Class extends Super with Mixin {
  const Class(); // This is currently not allowed.
}
```

**Comment by lrhn** [comment]
See also https://github.com/dart-lang/sdk/issues/9745

**Comment by eernstg** [comment]
Closing: As of 63c6851dd01514e9d9e6cb96da0430e15b66d576, constructor forwarding does just [that](https://github.com/dart-lang/sdk/issues/28492#issuecomment-274796650). Created #32223 to put this into the implementation pipeline.
