### ISSUE TITLE
ddc not scheduling async function correctly?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28509]
This code prints one way in dart2js and vm and another with ddc.  

```dart
import 'dart:async';

foo() {
  print('running foo');
  return 'foo';
}

bar() async {
  print('running bar');
  return 'bar';
}

main() async {
  var f = new Future(foo);
  var b = await bar();

  await f;
}
```

In dart2js / vm, we get:
```
running bar
running foo
```

In ddc, we get:
```
running foo
running bar
```

**Comment by vsmenon** [comment]
@lrhn - does the spec require an order in the example above?  Is `await` supposed to map to a microtask?

**Comment by vsmenon** [comment]
@jmesserly @floitschG

**Comment by jmesserly** [comment]
@vsmenon is it possible our SDK code is just out of date here? that seems the most likely guess. I doubt it has anything to do with async/await -- which is a syntactic transform. Try reproducing with Future.then?

**Comment by jmesserly** [comment]
see also -- my FutureOr change which had some implementation changes to future_impl:
https://codereview.chromium.org/2647833002/diff/160001/pkg/dev_compiler/tool/input_sdk/lib/async/future_impl.dart

there might be other updates we need in dart:async.

**Comment by vsmenon** [comment]
You're right.  If I replace `main` with:

```
main() async {
  var f = new Future(foo);
  bar().then((_) {
    f.then((_) {});
  });
}
```

I see the same ordering difference.

**Comment by jmesserly** [comment]
ahhh nice!!! yeah we're rly behind especially on dart:async, so missing any recent bug fixes. should really do a roll for all that. it was super easy to roll future, at least.

**Comment by vsmenon** [comment]
After chatting with @jmesserly - the spec is clear on `await`.  The question is whether the `async` function should be scheduled via microtask.

**Comment by jmesserly** [comment]
fyi, dart2js uses _asyncHelper:
```dart
dynamic _asyncHelper(dynamic object,
    dynamic /* int | _WrappedAsyncBody */ bodyFunctionOrErrorCode,
    Completer completer) {
  if (identical(bodyFunctionOrErrorCode, async_error_codes.SUCCESS)) {
    completer.complete(object);
    return;
  } else if (identical(bodyFunctionOrErrorCode, async_error_codes.ERROR)) {
    // The error is a js-error.
    completer.completeError(unwrapException(object),
    getTraceFromException(object));
    return;
  }

  _awaitOnObject(object, bodyFunctionOrErrorCode);
  return completer.future;
}

/// Awaits on the given [object].
///
/// If the [object] is a Future, registers on it, otherwise wraps it into a
/// future first.
///
/// The [bodyFunction] argument is the continuation that should be invoked
/// when the future completes.
void _awaitOnObject(object, _WrappedAsyncBody bodyFunction) {
  Function thenCallback =
      (result) => bodyFunction(async_error_codes.SUCCESS, result);

  Function errorCallback = (dynamic error, StackTrace stackTrace) {
    ExceptionAndStackTrace wrappedException =
        new ExceptionAndStackTrace(error, stackTrace);
    bodyFunction(async_error_codes.ERROR, wrappedException);
  };

  if (object is _Future) {
    // We can skip the zone registration, since the bodyFunction is already
    // registered (see [_wrapJsFunctionForAsync]).
    object._thenNoZoneRegistration(thenCallback, errorCallback);
  } else if (object is Future) {
    object.then(thenCallback, onError: errorCallback);
  } else {
    _Future future = new _Future();
    future._setValue(object);
    // We can skip the zone registration, since the bodyFunction is already
    // registered (see [_wrapJsFunctionForAsync]).
    future._thenNoZoneRegistration(thenCallback, null);
  }
}

typedef void _WrappedAsyncBody(int errorCode, dynamic result);
```

initial call is with "null" object and then a body function. So it looks like 1 more tick than DDC's implementation, because it desugars into something like:
```dart
return new Future.value(null).then( ... what DDC does ... )
```

**Comment by jmesserly** [comment]
oh, and also one more tick for the completer.complete

**Comment by vsmenon** [comment]
Here's a more detailed test:
```dart
import 'dart:async';

foo() {
  print('running foo');
  return 'foo';
}

bar() async {
  print('running bar');
  return 'bar';
}

main() async {
  var f = new Future(foo);
  var b = bar();
  print('before microtasks');
  Zone.current.scheduleMicrotask(() => print('last microtask'));
  await b;
  await f;
}
```

Dart2JS and the VM:
```
before microtasks
running bar
last microtask
running foo
```

DDC:
```
before microtasks
last microtask
running foo
running bar
```

**Comment by vsmenon** [comment]
@jmesserly - do you know how `Completer.complete` is scheduled?

**Comment by vsmenon** [comment]
Assuming that's the path it's going down ... maybe not?

**Comment by lrhn** [comment]
I think the important part of this example is `new Future(foo)`. The `Future` constructor schedules its argument as a *timer* task (like `Timer.run`), which won't run until after the current microtask queue is empty.
Future completion always happens in the current microtask queue, and `await` is triggered by future completion, so that should happen in the current microtask queue too.

So, the (only) correct order is "bar" then "foo".

`Completer.complete` (for a non-sync completer) uses a microtask.

(And, just FYI, `sheduleMicrotask` is a top-level function in `dart:async` that forwards to `Zone.current.scheduleMicrotask`, so you don't need the prefix).

**Comment by vsmenon** [comment]
Thanks, for the clarification, @lrhn !

We were scheduling `new Future(...)` as a timer task (just using the dart2js lib code here), but our helper to execute async functions (e.g., `bar`) was also scheduling the body of the async function as a timer task instead of a microtask.

**Comment by vsmenon** [comment]
Should be fixed as of:

https://github.com/dart-lang/sdk/commit/a91cc9cc9e3f90e648685fb3cef92b36ab75e332
