### ISSUE TITLE
Regression in strong mode analyzer for dart:js api

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28507]
This code now shows a warning in tip-of-tree dartanalyzer (with strong).  It shows no warning in dartanalyzer 1.22.0-dev.4.0.

```dart
import 'dart:js';

typedef dynamic Func(String x, String y);

Func bar(Func f) {
  return allowInterop(f);
}
```

The signature of `allowInterop` is:
```dart
Function /*=F*/ allowInterop/*<F extends Function>*/(Function /*=F*/ f)
```

The new warning appears to be a bug.

**Comment by vsmenon** [comment]
Is this related to recent changes around extending `Function`?  @leafpetersen @bwilkerson

**Comment by bwilkerson** [comment]
That change (https://codereview.chromium.org/2643073002/) only creates hints, and only if you define a class named `Function` or use `Function` in either an `extends` or `with` clause. (There was an earlier version that also flagged uses of `Function` in `implements` clauses, but that wouldn't account for this either.)

I'm not seeing anything on bleeding edge. What is the code (name) for the warning that you're seeing?

**Comment by vsmenon** [comment]
Not sure how to get the code.  I'm running a bleeding edge dartanalyzer on the code in comment 1 and seeing:

```
~/dart/sdk/out/ReleaseX64/dart-sdk/bin/dartanalyzer --strong func2.dart
Analyzing [func2.dart]...
[warning] Unsafe implicit cast from 'Function' to '(String, String) → dynamic'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (/Users/vsm/ddctest/func2.dart, line 7, col 10)
1 warning found.
```

**Comment by bwilkerson** [comment]
I'm not getting any errors reported on the command-line either.
```
$dartanalyzer --strong test.dart
Analyzing [test.dart]...
No issues found
```
Unfortunately, that message is used for several different errors, making it hard to track down where it's coming from in the code.

@jmesserly Any idea what would cause this?

**Comment by vsmenon** [comment]
Did you build a bleeding edge dartanalyzer today?

**Comment by bwilkerson** [comment]
Yep. Specifically I'm using 9264c1191a61b3964011d43c8ba9b58b71a3c380.

**Comment by vsmenon** [comment]
I synced to that exact branch and see it.  I also see if I just invoke analyzer_cli/bin directly:

```
dart ~/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart --strong func2.dart 
Analyzing [func2.dart]...
[warning] Unsafe implicit cast from 'Function' to '(String, String) → dynamic'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (/Users/vsm/ddctest/func2.dart, line 7, col 10)
1 warning found.
```

where `func2.dart` is:

```
import 'dart:js';

typedef dynamic Func(String x, String y);

Func bar(Func f) {
  return allowInterop(f);
}
```

I'm in a directory with no `.analysis_options` FWIW.

**Comment by bwilkerson** [comment]
I have an `.analysis_options` file (that enables strong mode) in the parent directory, but I added it to the command-line anyway. I tried every combination of having or not having both the file and the command-line argument, and got no warnings in any combination. I have no guess as to why we'd be getting different results.

**Comment by leafpetersen** [comment]
I also see this.  Interestingly, if I copy allowInterop into the test file, the error goes away (see below).  Could this have something to do with summarization of the SDK?

```dart
import 'dart:js';

Function/*=F*/ allowInterop2/*<F extends Function>*/(Function/*=F*/ f) {
  return null;
}

typedef dynamic Func(String x, String y);

Func bar(Func f) {
  if (true) {
    return allowInterop(f);
  } else {
    return allowInterop2(f);
  }
}
```

```
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 1.22.0-edge.ed40bd3eca9afbc52995cce871b94b80f680ecc1leafp-macbookpro:sdk leafp$ 
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --strong ~/tmp/test.dart
Analyzing [/Users/leafp/tmp/test.dart]...
[warning] Unsafe implicit cast from 'Function' to '(String, String) → dynamic'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (/Users/leafp/tmp/test.dart, line 11, col 12)
[hint] Dead code. (/Users/leafp/tmp/test.dart, line 12, col 10)
1 warning and 1 hint found.
```

**Comment by vsmenon** [comment]
FWIW, I originally saw this on travis - see the very end where we run analyzer on ddc itself:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/195243255/log.txt

This is a bot that we allow to fail (it builds the latest sdk), so it's not obvious when it started.

**Comment by bwilkerson** [comment]
(slaps forehead) Of course. I copied the declaration into the file to save time. Thanks for figuring out what the difference is.

@scheglov It does seem reasonable that this could be a summary issue. Does the strong mode summary information include generic method information specified via comments?

**Comment by scheglov** [comment]
Yes, we do include generics in comments when building summaries in strong mode.

**Comment by scheglov** [comment]
But there is a strange thing.

It seems that in spec mode we build `dart-sdk/lib/js/dartium/js_dartium.dart`, but in strong mode we build `dart-sdk/lib/js/dart2js/js_dart2js.dart`.

Although this does not explain why we don't use type parameters later, even the `js_dart2js.dart` has them.

**Comment by scheglov** [comment]
Hm... It seems that we don't use strong mode summary bundle for SDK.

```
/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseIA32/dart-sdk/bin/dartanalyzer --strong /Users/scheglov/dart/test/bin/test.dart
Analyzing [/Users/scheglov/dart/test/bin/test.dart]...
[getSummarySdkBundle] path: /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseIA32/dart-sdk/lib/_internal/spec.sum
[warning] Unsafe implicit cast from 'Function' to '(String, String) → dynamic'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (/Users/scheglov/dart/test/bin/test.dart, line 6, col 10)
1 warning found.
```

**Comment by scheglov** [comment]
I think this is a regression introduced in [this CL](https://github.com/dart-lang/sdk/commit/aff6b796f3d12ba5c0f0d3796bc26b0aa50651d5).
It moves updating `AnalysisOptions` after `_setupSdk()`.

**Comment by bwilkerson** [comment]
@danrubel Could you take a look at this?

**Comment by leafpetersen** [comment]
What's the status of this?  I'm a little concerned with the implications of not using the strong mode summary bundle.  Should I be worried?

**Comment by keertip** [comment]
We don't use summaries for analyzer tests internally too, so this is showing up in google3.

**Comment by jacob314** [comment]
FYI this issue looks like it was also hitting me landing some strong mode fixes for the coverage package.
Failing analyzer test
https://travis-ci.org/dart-lang/coverage/jobs/198081695
Hack to the SDK to remove the comment syntax hacks which makes the incorrect strong mode error for package:coverage go away.
https://codereview.chromium.org/2667813002
