### ISSUE TITLE
Connected to Observatory, no cpu profile data

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28512]
I'm trying to find out why running shared tests with `dartanalyzer` is slow.
So, I updated `sdk.git/sdk/sdk/bin/dartanalyzer` to include `--observe:5000`.

![image](https://cloud.githubusercontent.com/assets/384794/22304724/7c47aeca-e2ed-11e6-9e40-1c2a2efeaa45.png)

But when I connect to Observatory, cpu profile information is completely empty.
Why?
@johnmccutchan 

![image](https://cloud.githubusercontent.com/assets/384794/22304681/4ff13bde-e2ed-11e6-95fe-e76120c6cf31.png)

**Comment by johnmccutchan** [comment]
It says right in the profile that 0 samples were collected. So the CPU profiler is not able to sample the application.

What architecture are you running on? What revision of the VM are using you?

How can I replicate your exact build configuration?

@rmacnak-google Is this using the new app snapshot stuff?

**Comment by johnmccutchan** [comment]
Also, is the analyzer being spawned from another process (e.g. InteillJ / Dart )?

**Comment by scheglov** [comment]
`Dart VM version: 1.22.0-edge.e2bb8409ab0905bc3d8d76adc6e7e665ee903743 (Tue Jan 24 16:02:37 2017) on "macos_ia32"`

Yes, I think it should be easy to replicate.

With the changes to `sdk.git/sdk/sdk/bin/dartanalyzer` that I described above, run:

```
./tools/build.py --mode release --arch ia32 create_sdk
./tools/test.py --mode release --arch ia32 --compiler dart2analyzer --runtime none --progress color --report --tasks=1
```

I think `test.py` runs Dart, and it then runs `sdk.git/sdk/sdk/bin/dartanalyzer` which runs `dart`.

**Comment by johnmccutchan** [comment]
This is a known issue. When Dart spawns a process, the child process does not get the profile signals. This is a bug in dart:io.
