### ISSUE TITLE
can no longer run snapshots using a uri reference

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28511]
With `1.22.0-dev.9.1` we can no longer run snapshots from uris:

```
./bin/dart file:///Users/devoncarew/projects/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot
```

We use `file:` uris when invoking pub when running unit tests in IntelliJ.

Just to compare, this does work (full file paths):

```
./bin/dart /Users/devoncarew/projects/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot
Pub is a package manager for Dart.

Usage: pub <command> [arguments]
...
```

/cc @a-siva

**Comment by a-siva** [comment]
pub.dart.snapshot is now a full application snapshot with code etc. and is not expected to be used in that manner but through the pub script that is provided in the sdk bin/pub.

Is there a reason for IntelliJ to invoke it using './bin/dart <path to pub> ......' as opposed to just invoking './bin/pub ......' for running the unit tests?

**Comment by devoncarew** [comment]
Adding @alexander-doroshko and @stevemessick, who have more context here about why we're invoking the pub snapshot and not the `./bin/pub` script.

**Comment by devoncarew** [comment]
Looks like this was discussed in https://github.com/dart-lang/pub/issues/1504.

**Comment by a-siva** [comment]
Can this be made a duplicate of https://github.com/dart-lang/pub/issues/1504

**Comment by devoncarew** [comment]
Yup; closing.
