### ISSUE TITLE
Analyzer doesn't support function-typed parameters with generic arguments

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#28515]
This code, when added to StrongModeStaticTypeAnalyzer2Test, demonstrates the problem:

    test_genericFunction_parameter() async {
      await resolveTestUnit(r'''
    void g(/*=T*/ f/*<T>*/(/*=T*/ x)) {}
    ''');
      expectFunctionType('f', '<T>(T) → T',
          elementTypeParams: '[T]', typeFormals: '[T]');
      SimpleIdentifier f = findIdentifier('f');
      ParameterElementImpl e = f.staticElement;
      FunctionType type = e.type;
      FunctionType ft = type.instantiate([typeProvider.stringType]);
      expect(ft.toString(), '(String) → String');
    }

(Thanks to @scheglov for the repro)

**Comment by stereotype441** [comment]
This is not going to be feasible to fix for the 1.22 release, but I've prepared a CL which causes function-typed parameters with generic arguments to generate an error (so that users won't be confused): https://codereview.chromium.org/2656303004/

I will work on a proper fix for 1.23.

**Comment by stereotype441** [comment]
Downgrading to P2, since c9b692e8d9e5d6217e73f1a892081cf0f482f3e5 has landed.

**Comment by stereotype441** [comment]
Note that since analyzer uses summaries internally even when analyzing just a single file, in effect this means that function-typed parameters with generic arguments are completely unsupported.  I've retitled the bug accordingly.

**Comment by eernstg** [comment]
It's only failing with the direct syntax, it's possible to express the same thing with a type alias:

```dart
typedef F = T Function<T>(T);

// Can't write it directly, looks like the scope for `T` is never created.
// void g(T f<T>(T x)) {}

void g(F f) { print(f.runtimeType); }

main() {
  g(<X>(X x) => x); // Prints '<T1>(T1) => T1': OK!
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/100620 adds support for type parameters in function-typed formal parameters to summary2.

**Comment by scheglov** [comment]
We fully switched to summary2, so the issue is fixed.
