### ISSUE TITLE
Await on expression of type FutureOr<T> should have type T

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28526]
Submitted for your approval:

```dart
import 'dart:async';

Future<T> foo<T>() async {
  FutureOr<T> i = null;
  return await i;
}
```

I think this code should be kosher. If `i` is a T, then awaiting it will just produce the T. If `i` is a Future<T>, then awaiting it again produces a T. So in both cases, the `await` expression should have result type T. Since we are in an async function, returning that implicitly wraps it in Future, so the returned value Future<T> should match the declared type Future<T>.

When I analyze this using bleeding edge (59a9861743da492f33dd8347b80c74a18ca8ed52), I get:

```
[error] The return type 'Future<FutureOr<T>>' isn't a 'Future<T>', as defined by the method 'foo'. (~/temp.dart, line 5, col 10)
```

Looks like it's just not flattening the type in the await?

**Comment by leafpetersen** [comment]
The title is a little misleading: I don't think it's really a future flattening issue.  It's that 

await i has type T
  if i has type FutureOr<T> 

should be true.

**Comment by munificent** [comment]
I have a couple of (failing, obviously) tests for this here:

https://codereview.chromium.org/2659813003/

**Comment by jmesserly** [comment]
yeah this seems like a visitAwaitExpression issue during resolution, should be a very small fix

**Comment by jmesserly** [comment]
Oh funny, this is actually fixed in my pending inference CL. Not sure if I caught it there or add the fix to the wrong branch (been bouncing between them a lot). Well that makes it easy :)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2655273008/
