### ISSUE TITLE
FutureOr<T> does not handle type parameters?

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28527]
I'm not sure what's going on or if this is related to #28526, but I ran into another issue:

```dart
import 'dart:async';

void foo<T>(T t) {
  FutureOr<T> i = t;
}
```

I think this code should be correct, but it produces:

```
[error] A value of type 'T' can't be assigned to a variable of type 'FutureOr<T>'. (~/temp.dart, line 4, col 19)
```

If I take out the generics:

```dart
import 'dart:async';

void foo(int t) {
  FutureOr<int> i = t;
}
```

Then it analyzes without error.

**Comment by munificent** [comment]
I have a couple of (failing, obviously) tests for this here:

https://codereview.chromium.org/2659813003/

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2655273008/
