### ISSUE TITLE
Unhelpful code completion options in constructor params

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28529]
Tried to see what other named parameters I could provide. Here's what I saw:

![screen shot 2017-01-25 at 12 03 26 pm](https://cloud.githubusercontent.com/assets/5479/22307072/7c2462f4-e2f6-11e6-881d-ae8e312aa38c.png)

Can we do something better here? Can we show only named parameters?

Thanks!

**Comment by sethladd** [comment]
From https://github.com/Dart-Code/Dart-Code/issues/250

**Comment by bwilkerson** [comment]
Interestingly enough, I tried this using a method with only named parameters, and the completions included only the parameter names:

![image](https://cloud.githubusercontent.com/assets/5840555/22353657/6488e418-e3d6-11e6-99cd-31c4e446aafb.png)

@danrubel It looks like we handle this case for methods but not for constructors.

**Comment by sethladd** [comment]
Good find.

**Comment by danrubel** [comment]
Fixed https://codereview.chromium.org/2671533002/
