### ISSUE TITLE
Analyzer should warn if part-of URI doesn't match importing library.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28522]
When CL https://codereview.chromium.org/2640853005 lands, the analyzer needs to
- report a warning if the URI of a `part of` declaration doesn't match the URI of the library file doing the `part` inclusion.
- report a warning if the library name of a `part of` declaration doesn't match the name of the library doing the `part` inclusion. It already does this in some cases, but no longer does it in the case where the including library has no name (which previously prevented `part` inclusion and was handled at the `part` declaration).

The analyzer can also remove the `enableUriInPartOf` flag.

**Comment by floitschG** [comment]
Is this done?
When I tried it on the command line I got a warning.

**Comment by floitschG** [comment]
ping

**Comment by lrhn** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
I don't currently have time to look at this, but would be happy to review a CL if that would be useful.
