### ISSUE TITLE
Analysis server support for completion in analysis_options.yaml

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#28534]
I'm not sure if I've already raised this but can't find it. I'd love to add completion for `analysis_options.yaml` to Dart Code, but it seems like something other editors would like too. Is it something you'd consider adding in the analysis server? (`pubspec.yaml` would be good too).

(@bwilkerson)

**Comment by bwilkerson** [comment]
Yes, we've also talked about that several times. It keeps not making it to the top of our priority list, but I definitely think that's the right place for it.

**Comment by bwilkerson** [comment]
This is now supported.
