### ISSUE TITLE
Instantiate to bound errors for constructors issued prematurely.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28539]
The following code should be valid, because inference will fill in the type parameters to the `Foo` constructor call.  Instead an error is issued prematurely because `Foo` has no default bounds.

```dart
class Bar<T> {}

class Foo<T extends Bar<T>> {
  Foo(T y);
}

class Baz extends Bar<Baz> {}

void test() {
  Baz a;
  var x = new Foo(a);
}
```

**Comment by leafpetersen** [comment]
This doesn't seem to reproduce, can we close?

**Comment by bwilkerson** [comment]
Closing as obsolete. Please re-open if that's not the case.
