### ISSUE TITLE
Wrong placement of --strong silently noops

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#28546]
I just opened a bug regarding type inference where I thought I had validated the behavior in strong mode, but I was wrong:

https://github.com/dart-lang/sdk/issues/28541

Turns out I had run the command `dartanalyzer --strong test.dart` instead of `dartanalyzer test.dart --strong`. The latter ignored my `--strong` flag with no error.

This definitely threw me off and could be improved

**Comment by srawlins** [comment]
No more `--strong`.
