### ISSUE TITLE
Possible instability due to FutureOr<T> work

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#28540]
We're seeing some preliminary indications from some Google internal code that https://github.com/dart-lang/sdk/commit/0e00b3e5c83e4173d442bf287eb99d1dd12cb09b may be causing failures in some analyzer clients (possibly pub, but I'm not certain yet).

I'm posting this bug as a placeholder so that we don't accidentally release 1.22 before we get to the bottom of the problem.  I'll update this bug as I find out more information.

**Comment by mit-mit** [comment]
Internal issue is b/34771169

**Comment by stereotype441** [comment]
Ok, I've finished investigating the issue.  The problem was that we had some internal tests that were attempting to integrate the latest (unpublished) version of packages analyzer and code_transformers.  These tests failed because the mock SDK in the code_transformers package (https://github.com/dart-lang/code_transformers/blob/master/lib/src/dart_sdk.dart) failed to contain a definition of `FutureOr<T>` (which analyzer relies upon as of 0e00b3e5c83e4173d442bf287eb99d1dd12cb09b).

I want to take two additional actions before closing this bug:
* Update code_transformers to add a definition of `FutureOr<T>` to its mock SDK.
* Modify analyzer so that it does not require a definition of `FutureOr<T>` to be present in the SDK (this will ensure that new analyzers will continue to work with older SDKs).

However, there is no need to block the 1.22 release waiting for those actions to be completed.

**Comment by stereotype441** [comment]
Pull request for code_transformers is here: https://github.com/dart-lang/code_transformers/pull/55

**Comment by stereotype441** [comment]
Ok, pull request was accepted.  Also I landed a fix to analyzer so that it will continue to work with older SDKs that don't have a definition of `FutureOr<T>`: 79b810ebc051b2f9ebb6cc77d22565457398e97d
