### ISSUE TITLE
A formal type parameter declared by a generic function cannot be passed as a value

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28543]
(This issue was derived from #28517; @bwilkerson: This should be suitable for your needs, such that you can finish what you had started doing there.)

The following program is accepted by the analyzer (1.22.0-dev.2.0) in spec (i.e., non-strong) mode:
```dart
void test<T>() {
  print(T);
}

void main() {
  test<double>();
}
```
However, `print(T)` should be a compile-time error according to the [informal spec](https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c): 'It is a compile-time error if `X` is used as a type literal (e.g., `foo(X)`), or in an expression on the form `e is X` or `e is! X`', where `X` is a formal type parameter of an enclosing generic method.

Update (July 2017): `on T` in a try/catch is also a compile-time error.

**Comment by srawlins** [comment]
I think this is all legal syntax now.
