### ISSUE TITLE
Please merge revision #39977ac6ec58516f5db5ac4df9fa2426fc19dac5 into dev channel

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#28544]
@ricowind @whesse @kasperl

fix #28526, await FutureOr<T>
fix #28527, FutureOr<T> subtyping with type parameters

https://github.com/dart-lang/sdk/commit/39977ac6ec58516f5db5ac4df9fa2426fc19dac5 (merges cleanly)

**Comment by whesse** [comment]
Merged in 1.22.0-dev.10.1.

**Comment by jmesserly** [comment]
thank you! :)
