### ISSUE TITLE
dartk: Add support for specifying roots for dartk

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28559]
Sometimes we need to include more libraries than just the transitive dependency graph of the application's `main`. For example in precompilation mode, we might need the `vmservice_io:main()` as well (or other roots the VM or the embedder invokes).

`gen_snapshot` has support for this already via ` --embedder_entry_points_manifest=<file>` and we should add similar support for dartk.

This will also allow  us to remove the `dart:vmservice_io` from the normal vm target (because normal applications in JIT mode don't need this library).

/cc @mraleph @kmillikin

**Comment by mkustermann** [comment]
Some support for adding roots has been added to `package:kernel`. I have done an experiment some time ago in [cl/2704393002](https://codereview.chromium.org/2704393002) which allows tree shaking the core libraries in kernel.

Though the roots from the VM (i.e. the roots which are available via lists) are not complete (e.g. the VM always expects intensified functions to be available, so we could not shake them ...).

Also the precompiler will be able to shake more than we can do in Dart.

Generally speaking there are two things:
   * [ ] Make the VM pass the roots to fasta (embedder roots and the roots it has itself)
   * [ ] Make fasta use the roots to ensure we **include transitively all necessary libraries**
   * [ ] Make fasta use the roots to **tree-shake the application**

/cc @mraleph @peter-ahe-google

**Comment by mkustermann** [comment]
This issue is quite old and the kernel->vm work has been taken over by others some time ago, so I'll unassign me.

@kmillikin I suspect that this has been solved already?

**Comment by kmillikin** [comment]
Yes, we have a solution in the form of back-end-specific targets.  The details will probably change, but the support is working.
