### ISSUE TITLE
Summaries do not support invalid mixin checking

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#28553]
Found by code inspection during the review of https://codereview.chromium.org/2661803002/.  I haven't yet verified a repro for this bug.

We never implemented summary support for recording in the element model whether a class contains a reference to `super`.  This means that if the user has "supermixin" support disabled, and they try to mix in a class that references `super`, and the class being mixed in comes from a summary, no error will be reported.

Fixing this bug will carry an unfortunate runtime cost: it would require traversing the entire AST of any class declaration when forming the unlinked summary of that class, to search for references to `super`.  (Without the fix, we can avoid recursing into method bodies and some initializers, which saves a lot of time).

**Comment by srawlins** [comment]
Summaries have likely been updated to support supermixins etc.
