### ISSUE TITLE
Typo in Uri.resolveUri() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28556]
Please see https://api.dartlang.org/stable/1.21.1/dart-core/Uri/resolveUri.html

> Updated to handle the case where the base URI is just a relative path - that is: when it has no scheme or authority and the path does not start with a slash.

There should be ...when it has no scheme **AND NO** authority...

**Comment by lrhn** [comment]
Good point. I was probably going for "neither scheme nor authority", but missed the mark with the current wording.
