### ISSUE TITLE
Please add https://github.com/brendan-duncan/archive to DEPS

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28552]
I'm sorry.
It seems too complicated and multi step process.
Probably it would be easier and faster it you guys will do this.

CC @ricowind

**Comment by scheglov** [comment]
Never mind.
I found out that performance of `archive` on creating large `tar` files is abysmal. 
With `99%` is spent in allocating output buffers and shuffling data around...
This is hopeless.

**Comment by scheglov** [comment]
OK, it's not so bad.

Just archive's TarEncoder takes about 1000 ms for analyzer.
With archive's GZipEncoder, about 2400 ms.
If dart:io's GZIP instead, then 1240 ms.

I think for now we can afford spending 1250 ms to write a limited number of crash dumps.
So, I still would like to get `archive` in `third_party`.

**Comment by athomas** [comment]
Is this still needed?

**Comment by athomas** [comment]
Assuming this is obsolete.
