### ISSUE TITLE
CFE should not produce external methods with a body

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28565]
```
Language/Functions/External_Functions/not_connected_to_a_body_t01
``` 

/cc #28263

**Comment by mraleph** [comment]
This test is still failing with fasta.

**Comment by mraleph** [comment]
Repurposing this bug to track CFE specific issue. To avoid accidental backend bugs CFE should avoid producing methods which are simultaneously marked as external and have a body.

**Comment by johnniwinther** [comment]
I'm not sure I follow. The mentioned test, `Language/Functions/External_Functions/not_connected_to_a_body_t01`, generate this output:

```
library /*isNonNullableByDefault*/;
import self as self;
import "../../../Utils/expect.dart" as exp;
import "dart:core" as core;

import "file:///c:/src/dart-repo1/sdk/tests/co19/src/Utils/expect.dart";

external static method f() → dynamic;
external static method g([dynamic x = #C1]) → dynamic;
external static method h({dynamic x = #C1}) → dynamic;
static method main() → dynamic {
  exp::Expect::throws(() → void {
    self::f();
  }, (dynamic e) → core::bool => e is{ForNonNullableByDefault} core::NoSuchMethodError);
  exp::Expect::throws(() → void {
    self::g();
  }, (dynamic e) → core::bool => e is{ForNonNullableByDefault} core::NoSuchMethodError);
  exp::Expect::throws(() → void {
    self::h();
  }, (dynamic e) → core::bool => e is{ForNonNullableByDefault} core::NoSuchMethodError);
}
```
where `f`, `g` and `h` have no body - as seen by the `;` right after the return type.

**Comment by mraleph** [comment]
Sorry, I did not add additional information: https://github.com/dart-lang/sdk/issues/49912 shows that `external` constructors have non-`null` bodies, e.g. 

```dart
class A {
  external const A();
}
```

will have an `EmptyStatement` for the body.
