### ISSUE TITLE
"break methodname" doesn't work consistently for async functions

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28561]
If I have an async function "xyz" that hasn't been compilede yet, I can add a breakpoint by saying "break xyz" - I will get a message saying something like "Future breakpoint 1 added at file.dart:1:1". And it works and everything's fine.

Once the function has been compiled though (e.g. if I wait until I am actually stepping in the method "xyz"), saying "break xyz" gives me the message "Unable to set breakpoint at xyz".

It seems to be caused by all functions being "debuggable" until proven otherwise, i.e. in case 1 above it's debuggable. The the function is compiled it's set as not debuggable because it's async (case 2 above).

**Comment by ZichangG** [comment]
Hi, I failed to reproduce the problem with my script here. Could you please help me to address the problem?
```
import 'dart:async';

void xyz() async {
  var str = await generate();
  print(str);
}

String generate() {
  return "randomstring";
}

main() {
  xyz();
}
```
I run with `./dart --observe --pause-isolates-on-start test.dart`. Then typed `break xyz` in debugger without continuing or stepping. It replied with `Unable to set breakpoint at xyz` instead of `Future breakpoint ...`.

**Comment by ZichangG** [comment]
After testing, It will not allowed to set breakpoints in both cases. It is uniform now and case will be closed.

**Comment by jensjoha** [comment]
I would certainly have hoped for a different solution.
While "consistency" is nice, we also have to think of the user. As a user of the debugger, I would certainly expect to be able to break on a method - whether it's async or not.

And "uniform" is only in these two cases - for a non-async method we can still say "break methodName".
Can't we add that for all cases? So that is one says "break asyncMethodName" it automatically "redirects" to the async_op inner-function?
