### ISSUE TITLE
Windows Console and Unicode

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28571]
It seems like Dart cannot properly print unicode characters to the Windows console (`cmd.exe` or `powershell.exe` seem to be equally affected). Example `test.dart` Program:

```dart
main() {
  print("These are three black spades: ♠♠♠");
}
```

Actual console output of `dart test.dart`:
```shell
These are three black spades: ΓÖáΓÖáΓÖá
```

Ideally, this should have shown the three spades, or - in case those are not available in the font used in the console - it should have show Unicode's missing character symbol (e.g. �).

While researching this issue on the web I realized that properly printing Unicode to the Windows console is actually fairly hard to do. However, it seems like the people over at Python just figured out how to properly do this in python 3.6.0, which was just released last month. Example `test.py` program:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

print("These are three black spades: ♠♠♠")
```

Actual console output of `python test.py` (requires python 3.6.0!):
```shell
These are three black spades: ♠♠♠
```

Yeah! \o/

It would be most awesome-st if Dart could also fix the unicode printing behavior on Windows. That would really help us in Flutter, where we make extensive use of unicode in console output (https://github.com/flutter/flutter/issues/7714).

In case it is helpful, here are the relevant discussions around fixing this in python:
* http://bugs.python.org/issue1602 - bug discussing the issue (has been open for 7 years, relevant bits for fixing the issue are towards the end)
* https://www.python.org/dev/peps/pep-0528/ - Python Enhancement Proposal describing the fix
* https://hg.python.org/cpython/rev/6142d2d3c471 - commit including the fix

From the python discussions, it seems like `WriteConsoleW()` from the Windows API should be used to write strings to the console in order to get unicode support.

**Comment by kevmoo** [comment]
@nex3 has dealt with this before -- may have some more context

**Comment by nex3** [comment]
I just avoid writing Unicode characters on Windows :disappointed:. If we could find a way to make them work, that would be rad.

**Comment by mit-mit** [comment]
I gave this a try on Windows using C#:

```
        static void Main(string[] args)
        {
            Console.OutputEncoding = System.Text.Encoding.UTF8;
            Console.WriteLine("These are three black spades: ♠♠♠");
        }
```

This did not work; the output was:
![before](https://cloud.githubusercontent.com/assets/13644170/22473761/3118c032-e7da-11e6-9aa6-7d49ea8c137b.PNG)

However, if I configure the encoding property on the console:
```
            Console.OutputEncoding = System.Text.Encoding.UTF8;
            Console.WriteLine("These are three black spades: ♠♠♠");
```

it works:
![after](https://cloud.githubusercontent.com/assets/13644170/22473759/2dd8a540-e7da-11e6-90fe-7ca773436ff2.PNG)

**Comment by mit-mit** [comment]
https://msdn.microsoft.com/en-us/library/system.console.outputencoding

**Comment by goderbauer** [comment]
Thanks for looking at it. It looks like both of your code samples (working and not working) are the same. To avoid future confusion, it might be worth correcting that :)

**Comment by mit-mit** [comment]
Sorry, fixed

**Comment by goderbauer** [comment]
Is it possible to set the OutputEncoding of the Console to UTF8 from dart to fix this problem?

**Comment by fsc8000** [comment]
I think yes, but it's a bigger change to the libraries because it would have to be done in an platform-independent way in the io library.

For Windows as a stop-gap, you could try running ```chcp 65001``` from your Dart program. (and save the currently active code page first using just ```chcp``` to restore it before exit) It's not the desired solution, but may get you running.

When I do this it prints the spades correctly:
```
import 'dart:io';
main() {
  Process.runSync("chcp", ["65001"], runInShell: true);  // Or the async version Process.run
  print("These are three black spades: ♠♠♠");
  stdout.writeln("These are three black spades: ♠♠♠");
}
```
Output:
```
C:\src\dartgit\sdk>out\ReleaseX64\dart uni.dart
These are three black spades: ♠♠♠
These are three black spades: ♠♠♠
```

**Comment by goderbauer** [comment]
Interestingly, `stdout.encoding` claims to be `Instance of 'Utf8Codec'` on Windows. Shouldn't this be something else if the terminal is not setup to display unicode characters?

**Comment by zanderso** [comment]
Investigated this a bit. We can use SetConsoleOutputCP to set the code page to CP_UTF8:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms686036(v=vs.85).aspx

This is sufficient for calls to print(), But for calls through `stdout` we have the problem that we are explicitly setting the output mode to _O_BINARY:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/file_win.cc#L254

as a fix for https://github.com/dart-lang/sdk/issues/19334.

This causes a disconnect between the way that write() interprets the data, and the way that the console interprets the data. To fix this disconnect, we need to set the mode for stdout to something like _O_WTEXT, and we'll need to add some stuff to the Dart API to do that. I'm thinking a getter/setter on Stdout, which I'm going to start working on.

**Comment by nex3** [comment]
As I user, I think my expectation would be for `write`, `writeln`, `writeAll`, and `writeCharCode` to write in _O_WTEXT mode, and for `add` to write in _O_BINARY mode. Can we do that?

**Comment by zanderso** [comment]
Starting work on this here: https://codereview.chromium.org/2698813002

@nex3  That will at least break standalone/io/stdio_nonblocking_test as \n will be translated to \r\n in non-binary mode. I think at first, I'd prefer it if this didn't try to have too many smarts built in.

**Comment by nex3** [comment]
I think requiring manual configuration is likely to trip up a lot of people who'll expect Unicode to work—or who'll just assume it can't possibly work. The `\r\n` issue doesn't seem that bad to me in comparison.

**Comment by zanderso** [comment]
Sent the change for review. Decided to go with @nex3's suggestion, and only write in binary mode for add(). Also decided not to expose setting the mode in the Dart API since I'm not sure if there's a use-case for it. If someone has a concrete use-case, we can revisit.

**Comment by nex3** [comment]
@zanderso Can you add a note about this to the changelog?

**Comment by zanderso** [comment]
Done

**Comment by nex3** [comment]
Thanks!

**Comment by goderbauer** [comment]
I just gave it a shot on Flutter and it seems to work great! Thank you so much for fixing it, @zanderso!

**Comment by goderbauer** [comment]
I have noticed that after this change sometimes the Windows console breaks when running another command after running a dart script. See second last line:

![terminal_broken](https://cloud.githubusercontent.com/assets/1227763/23525206/7cf48372-ff42-11e6-8132-68417902ef4f.png)

This started to appear right after I switched to the first Dart version that included this change. It also doesn't happen every time I execute a dart script. I've not discovered what the pattern is yet, unfortunately.

**Comment by zanderso** [comment]
Hmm that's odd. I had only noticed this happening in our test suite for tests that don't exit cleanly and reset the console's code page back to the default. Could you file a new bug and include repro steps? Thanks!

**Comment by rostopira** [comment]
Still an issue
I've tried to print some Cyrillic chars on Windows 7 
`print` and `stdout.writeln` produce same result
![0-02-04-a80c93ac4c21a9c97303bcd55bb2e72665d7d5f30b60507d0c84e894937222d5_1c6d953eed9890](https://user-images.githubusercontent.com/16724952/54138704-0afdc400-4431-11e9-8fc3-f173f1a37ab6.jpg)
