### ISSUE TITLE
Dart_StringToCString should be removed from the Dart API and replaced with safer equivalents

### ISSUE THREAD

**Issue by lexprfuncall** [dart-lang/sdk#2857]
As Dart strings are permitted to contain an arbitrary number of U+0000 code points, it is not possible to safely and securely marshal Dart strings into C strings.

I am in the process of adding Dart_StringToBytes which takes a Dart string and returns an array of UTF-8 code units and a length.  I believe this function, along with a function to compare a Dart string with an array of UTF-8 code units, should be sufficient to replace the uses of Dart_StringToCString.

**Comment by iposva-google** [comment]
We decided that the convenience trumps the concern of short C strings. Keeping this as is, returning a UTF-8 string.
