### ISSUE TITLE
feature request IJ-plugin: provide complete statement

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28576]
In Java, JavaScript, C++... if I press CTRL+Shift+Enter it completes the statement. E.g. adds parentheses or adds semicolon. This is an issue in IJ since **2013!!!!**

It can't be so hard to implement... PLEASE guys!
https://youtrack.jetbrains.com/issue/WEB-10363

**Comment by devoncarew** [comment]
From talking to the engineers, the implementation _is_ not trivial to implement, but - also from them - would be valuable as well :) Likely implemented in the analysis server and exposed through IntelliJ.

**Comment by MichaelRFairhurst** [comment]
+@mk13 this is good for us to know

**Comment by stevemessick** [comment]
The implementation is still in progress, but it is now available for preview. You need the latest IntelliJ 2017.1+ release and the current dev-channel Dart SDK to use it. Please file new issues for problems with the implementation.
