### ISSUE TITLE
Remove unsafe implicit cast warnings in Flutter code base

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#28588]
The Flutter analysis options currently contain:

  `strong_mode_down_cast_composite: ignore`

Enabling those warnings leads to >100 warnings in the Flutter code base like these:

```
[warning] Unsafe implicit cast from 'Map<dynamic, dynamic>' to 'Map<String, dynamic>'. 
[warning] Unsafe implicit cast from '(ByTooltipMessage) → Finder' to '(SerializableFinder) → Finder'.
...
```

I suspect that a lot of these will require changes to the Flutter code base, but we should make sure that the type system isn't making this unnecessarily hard. 

Reproduction steps:
```
   $ git clone https://github.com/flutter/flutter.git
   $ cd flutter
   $ bin/flutter update-packages
   <<comment out the strong_mode_down_cast_composite in .analysis_options_repo>>
   $ bin/flutter analyze --flutter-repo
```

**Comment by kasperl** [comment]
We believe we can get rid of this warning and turn it into a lint that users can enable if they want help finding areas where runtime checks might fail for them.

**Comment by kasperl** [comment]
We have reached the decision to turn off the `strong_mode_down_cast_composite` warning by default, but we will do it in a few steps. First, we will turn it off by default in Flutter projects but keep it on for web projects.

It looks like analysis options are dealt with in a lot of places in the analyzer code base, @pq? It feels hard to manipulate the options map and add the ignore there, so here's a suggestion on how to turn this off for Flutter projects by passing down the `hasFlutterDependency` flag to the strong mode checker: https://codereview.chromium.org/2703253006/.

Do you have cycles to look at this, Phil, and figure out what the best path forward is?

**Comment by pq** [comment]
> Do you have cycles to look at this, Phil, and figure out what the best path forward is?

👍   Happy to take a look.

**Comment by kasperl** [comment]
Turned the warning into a hint in fa2a3a1afa1a1e0eb748783472b25214d53aceec.

**Comment by kasperl** [comment]
Finally landed turning this into a lint in 2fe848502c6d6b95b2e77a408645faf058c6fb60.

**Comment by mit-mit** [comment]
@kasperl are you still working on this?

**Comment by kasperl** [comment]
@mit-mit The work is done, but it hasn't been rolled into Flutter yet. We could turn this into a Flutter issue blocked on rolling the Dart SDK dependency past the next dev channel release -- and close this one. That's probably the best approach.

**Comment by kasperl** [comment]
@mit-mit This change will be in 1.23.0-dev.6.0. Will go ahead and close this issue.

**Comment by kasperl** [comment]
Filed https://github.com/flutter/flutter/issues/8783. Closing this one.

**Comment by leafpetersen** [comment]
What was the final resolution of this?  I don't see it surfacing as a hint.  Is it now an opt in lint?  If so, what are the instructions for enabling it?

**Comment by pq** [comment]
I believe it's now only shown if you have strong warnings enabled.  I'm not sure how that gets done though!  (Not seeing an option in `dartanalyzer`...)

cc @bwilkerson who may know

**Comment by leafpetersen** [comment]
If by strong warnings, you mean AnalysisOptionsImpl.strongModeHints, I think that's only available programmatically, and is really more of a testing feature for us at this point.

**Comment by pq** [comment]
I think that's right -- and was under the impression that was the desired approach...  I'll leave it to @kasperl to clarify though!

**Comment by leafpetersen** [comment]
Ok.  For context, I'm writing the changelog, and I want to know what to say about this.  That is, should I be saying "this is gone" or "this is now opt in via path XXX", or...

**Comment by kasperl** [comment]
You can opt in through an analysis options file - explicitly requesting to
turn the specific hint into a warning or an error.

**Comment by leafpetersen** [comment]
Can you elaborate more?  I've not been able to surface this in any way, even as a hint.  Adding

```
  errors:
    down_cast_composite: error
```
to an analysis options file still doesn't surface it in any way that I can see.

**Comment by kasperl** [comment]
Ack, @leafpetersen. I've messed this up. The strong mode checker filters out hints aggressively without consulting the analysis options.

Fix here: https://codereview.chromium.org/2784473004/

**Comment by DanTup** [comment]
> We have reached the decision to turn off the `strong_mode_down_cast_composite` warning by default

Is there any more info on the reasons for this decision? To me it seems really strange that "opting in to strong mode" would not give you protection against this by default.

A colleague asked me today why his `analysis_options.yaml` file wasn't working and it turned out to be that he didn't know about this option and had concluded that strong mode was broken or "not strong". From the outside, based on only the info in this case it seems like the default was changed based on it being easy for some existing code rather than doing what's best for Dart code going forwards. I don't understand why the Flutter code can't be a) changed b) have explicit casts added or c) continue to opt-out if they really want (IMO a/b are best since the decision about whether it's valid can be made on a case-by-case basis).
