### ISSUE TITLE
Language Tour doesn't mention covariant

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28583]
`covariant` is a new language feature coming for Dart. I didn't find an open issue to add it to the Language Tour.

An example, with a useful explanation, is here: https://github.com/dart-lang/sdk/commit/c3f1212a9c5b1105a604b575c9999d7a29ab1d3d#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR53

**Comment by sethladd** [comment]
cc @kwalrath

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-www#227
