### ISSUE TITLE
analyzer warns about an override not being so

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#28587]
In the following case:

```dart
typedef B Function1<A, B>(A a);

abstract class Foo<A> {
  Foo<B> map<B>(Function1<A, B> f);
}

class IterableFoo<T> implements Iterable<T>, Foo<T> {
  final Iterable<T> _data;
  IterableFoo.fromIterable(Iterable<T> data) : _data = data;

  @override
  IterableFoo<S> map<S>(Function1<T, S> f) => new IterableFoo.fromIterable(_data.map(f));
}
```

I get a `[hint] Method doesn't override an inherited method.` but there is no warning for using `f` in Iterable.map the use looks correct, the error probably lies in the fact that there are two ways to express such functions.

**Comment by a14n** [comment]
Isn't there a typo in your code snippet ? Using `Foo<A, B>` as type of parameter in `Foo#map` should lead to:

>WARNING: The type 'Foo' is declared with 1 type parameters, but 2 type arguments were given.

**Comment by bwilkerson** [comment]
There probably shouldn't be a hint when the names match, even if there are other problems.

That said, a function type is not a subtype of an interface type (unless the interface type implements a `call` method), so in addition to the issue that @a14n pointed out, it seems like there should have been a warning / error about the parameter type of `IterableFoo`'s `map` method not matching the parameter type of `Foo`'s `map` method.

**Comment by alexeieleusis** [comment]
Thanks for the observation, fixed the method signature. Probably a different issue now.

**Comment by alexeieleusis** [comment]
I found a way to solve my problem, not sure if should leave this report open in case is valuable for the analyzer.

**Comment by srawlins** [comment]
This is still how the language specifies overrides and subtyping.
