### ISSUE TITLE
Stop supporting '@virtual' annotation on fields to allow field overrides in strong mode

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#28589]
Related to #27385 that introduced the support.

**Comment by kasperl** [comment]
This is blocked on #28120 which in return is blocked on #28119.

**Comment by leafpetersen** [comment]
I don't think we need to do anything for this in 1.23, once https://github.com/dart-lang/sdk/issues/28120 happens the code enabling this can be deleted at any point in the future.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2781443003/
