### ISSUE TITLE
kernel bots should run (and status files should cover) the full test suite

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28584]
I naively tried to run `test.py -mrelease -cdartk` and got various errors. Turns out the bots are only running the suites `co19 kernel langauage` and the status files only cover these suites.

@mkustermann @mraleph

**Comment by mkustermann** [comment]
This has been fixed some time ago in [cl/461825](https://chromium-review.googlesource.com/c/461825/).
