### ISSUE TITLE
Limit integers to 64 bits.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28595]
We have reason to believe that compiled Dart code (in particular AOT compiled code) could be much smaller if we could restrict ints to no more than 64 bits. We assume that we can keep the big int support around, but just get rid of the automatic promotion to big ints on overflow (and the corresponding demotion going back to smaller ints again).

Here are the steps we will take to evaluate this.

 - [x] Let the VM throw on 64-bit overflows behind a flag (--limit-ints-to-64-bits)
 - [x] Turn on the flag for Flutter and figure out what tweaks we need to make it 64-bit clean
 - [ ] Try the flag on dart2js, pub, DDC, etc.
 - [x] Expose big int class so users can opt into using bit ints

If that appears to be doable, we will:

 - [ ] Turn on throwing on 64-bit overflows for all users of the VM

Finally, we need to decide if the overflow behavior should be wrapping around or remain throwing. If we decide to wrap around it will have an impact on our range analysis code.

**Comment by kasperl** [comment]
Assigned to Regis, who will try to complete the first step (add flag to throw on overflows).

**Comment by crelier** [comment]
Defining a new error in the core library for this experiment is rather painful, so I'll use the existing RangeError to report a 64-bit overflow.

**Comment by crelier** [comment]
Under review: https://codereview.chromium.org/2708213004
This CL introduces a flag --limit-ints-to-64-bits in the VM in order to investigate the use of Bigint.
A RangeError with the message "Integer operand requires conversion to Bigint" is
thrown when a Bigint gets allocated. However, parsing a Bigint literal in Dart
source will not throw the RangeError (as long as the literal is not used).

Note that with the flag set to true, it is not possible to build the SDK, because crypto code using Bigint gets used.

Also, about 250 tests out of ~15000 fail.

**Comment by sethladd** [comment]
> requires conversion to Bigint

How does one convert to Bigint?

**Comment by crelier** [comment]
Feel free to try the flag and let me know if it triggers a RangeError too easily in some cases that I could further tune.
If it is easier for you, you can change the default value of the flag from false to true prior to a build by editing sdk/runtime/vm/flag_list.h:104.

**Comment by sethladd** [comment]
@crelier would you be willing to open an issue for Flutter over at https://github.com/flutter/flutter/issues/new for us to track the experiment?

**Comment by crelier** [comment]
@sethladd sure, see https://github.com/flutter/flutter/issues/8331

**Comment by mraleph** [comment]
@floitschG @alexmarkov @crelier Is there anything left on the VM side regarding this issue? 

If not - I am going to remove area-vm label.

**Comment by crelier** [comment]
I cannot think of anything left. The corresponding flutter tracking bug is closed and I think we can close this one as well. I will let @floitschG and @alexmarkov comment.

**Comment by alexmarkov** [comment]
VM and Flutter switched to use limited 64-bit integers long ago, so I think we can close this issue.

**Comment by mraleph** [comment]
I think the missing chunk of work is migrating users like dart2js and DDC to use `BigInt` explicitly where necessary. Closing this one.
