### ISSUE TITLE
Test language/not_enough_positional_arguments_test is wrong

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28590]
There are multiple issues here:
1. /01 tries to invoke a non-existing constructor; this is a compile-time error by the specification. (It is also unrelated to the number of positional arguments)
2. /02 and /05 try to invoke a super constructor with incompatible arguments; I'd argue that this *should* be a compile-time error, too.

dart2js produces compile-time errors for these and this has status file entries: https://github.com/dart-lang/sdk/issues/12838, and dartk is failing /02 due to producing a compile-time error.

@lrhn @johnniwinther

**Comment by lrhn** [comment]
To be precise, the spec is completely silent on what it means to call a super-constructor with the wrong number/names of arguments. We should fix that.

I would like it to be a compile-time error, and it definitely will be in Strong Mode, but Dart 1 makes a lot of statically detectable errors into warnings+runtime errors.

In either case, it's probably not a high priority to make everybody agree before we move to the common front-end, and I have no problem with dartk producing a compile-time error.

**Comment by lrhn** [comment]
The tests have been updated for Dart 2.
