### ISSUE TITLE
stdin.lineMode = false throws on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28599]
When setting `stdin.lineMode` to `false` on Windows, I am getting an exception. Example `main.dart`:

```dart
import 'dart:io';

main() {
  stdin.lineMode = false;
}
```

If I run this on windows with `dart.exe main.dart`, I am getting the following error:
```shell
Unhandled exception:
StdinException: Error setting terminal line mode, OS Error: The parameter is incorrect.
, errno = 87
#0      Stdin.lineMode= (dart:io-patch/stdio_patch.dart:82)
#1      main (file:///C:/Users/goderbauer/Desktop/main.dart:4:8)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

From Microsoft's documentation (https://msdn.microsoft.com/en-us/library/ms686033) it looks like enabling and disabling lineMode is supported on the platform (see `ENABLE_LINE_INPUT` value). Therefore, the exception is unexpected.

I am encountering the error while making Flutter work on Windows (https://github.com/flutter/flutter/issues/138).

**Comment by fsc8000** [comment]
On Windows, echoMode can't be used without lineMode enabled. One fix would be to do:
```
import 'dart:io';

main() {
  stdin.echoMode = false;
  stdin.lineMode = false;
}
```

When enabling echoMode, you'd need:

```
stdin.lineMode = true;
stdin.echoMode = true;
```

Let me know if this works for you!

**Comment by goderbauer** [comment]
Thanks for looking into it. That should work for us. Might be worth documenting these platform-specific differences in the dart docs?

**Comment by thosakwe** [comment]
Getting this error in Windows 10 on v1.23.0!!!! Not sure how to fix it.

**Comment by leonardoInf** [comment]
This should not be closed as this issue exists in 2020.

**Comment by mraleph** [comment]
@leonardoInf see the explanation in this comment https://github.com/dart-lang/sdk/issues/28599#issuecomment-277370165. You need to disable `echoMode` first. This is documented in the docs (see https://api.dart.dev/dev/2.9.0-1.0.dev/dart-io/Stdin/lineMode.html)

> On Windows this mode can only be disabled if echoMode is disabled as well.
