### ISSUE TITLE
c919/LayoutTests/fast/canvas/webgl/get-active-test_t01 fails on firefox

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28593]
Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rff --fast-startup -t60 --use-sdk --dart2js-batch --reset-browser-configuration co19/LayoutTests/fast/canvas/webgl/get-active-test_t01

@floitschG

**Comment by floitschG** [comment]
Test fails also without `--fast-startup`.

**Comment by mraleph** [comment]
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by athomas** [comment]
LayoutTests have been deleted.
