### ISSUE TITLE
Registering SIGTERM handler fails on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28603]
Registering a SIGTERM handler on Windows with `ProcessSignal.SIGTERM.watch().listen(..)` yields a strange **error** that the operation was **successfull**:

```shell
SignalException: Failed to listen for SIGTERM, osError: OS Error: The operation completed successfully.
, errno = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1138)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I ran into this issue while porting Flutter Tools to Windows (https://github.com/flutter/flutter/issues/138).

**Comment by a-siva** [comment]
On Windows we seem to support only SIGHUP and SIGINT, but we fail to set the appropriate
error code as a result the error message returns says successful.
