### ISSUE TITLE
Infer cases where `@virtual` is implicit

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28601]
I understand this is likely related to #28117 and other issues related to `@virtual` and field overrides, but I wasn't sure which bug I should attach this example to.

If we make field overrides available by default, this is a non issue. Otherwise, I've run into some cases where we could infer that the field is virtual based on the fact that a class extends or implements and interface that declares a getter. 

Here is an example:

```
import 'package:meta/meta.dart';

class A {
  int get f => null;
}

class B extends A {
  @virtual int f;
}

class C extends B {
  int get f => super.f;
}
```

The `@virtual` is currently required to be strong clean.

/cc @leafpetersen @vsmenon - feel free to merge this with other issues

**Comment by zoechi** [comment]
Is this still valid? #28117

**Comment by leafpetersen** [comment]
Closing since fields are becoming virtual by default.
