### ISSUE TITLE
Code completion on overides not offering suggestions

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#28608]
See e.g: https://dartpad.dartlang.org/f4e41229e2c16df41a5b8edc74c03437

Code completion on the 'd' should offer to override 'doSomething' but doesn't.
This would be very helpful when attempting to find the method to override in visitor patterns.

**Comment by bwilkerson** [comment]
I have an implementation of this that is 90% complete, but there was some issue in the communication between server and client that prevented it from working.

**Comment by DanTup** [comment]
Possibly this is done? @pq https://github.com/flutter/flutter-intellij/issues/1110

**Comment by pq** [comment]
Yep.  This is done on the server side. Thanks!
