### ISSUE TITLE
`return` without value should be allowed for function returning Null (but analyzer complains)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28602]
The inconsistency here is highly surprising:

```dart
import 'dart:async';

Future _test1() async {
  return;
}

Future<dynamic> _test2() async {
  return;
}

Future<Null> _test3() async {
  return;
}

_test4() {
  return;
}

dynamic _test5() {
  return;
}

Null _test6() {
  return; // analyzer complains about this line
}

main() async {
  print(await _test1() is Null);
  print(await _test2() is Null);
  print(await _test3() is Null);
  print(_test4() is Null);
  print(_test5() is Null);
  print(_test6() is Null);
}
```

**Comment by Hixie** [comment]
To be clear, I think that the better fix here is to have the analyzer not complain about `return` missing a value when the return type is Null. This is a relatively common pattern, e.g. a `Future<Null>`'s `then<Null>` method takes a closure that's supposed to return a `Null` but we don't want to have to explicitly say it.

**Comment by zoechi** [comment]
Isn't `void` a better way to indicate just that?

```dart
void _test6() {
```
AFAIK it's currently worked on to be able to use
```dart
Future<void>
```
instead of
```dart
Future<Null>
```

Just curious because I'm not able to see the purpose of `Null` being used as return type.

**Comment by Hixie** [comment]
`Future<void>` and `f.then<void>` would be a fine solution too.

**Comment by eernstg** [comment]
I added a reference to this issue in the language team issue about allowing `void` as a type argument.

**Comment by lrhn** [comment]
I don't think this should have changed. 
The odd case is that `Future<Null>` is being used as a stand-in for `Future<void>`. The solution is to allow `Future<void>`, not to allow `Null` to stand in for `void` as well.
