### ISSUE TITLE
Debug_InterruptIsolate crashed on vm-linux-debug-x64-be

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28606]
```
FAILED: none-vm debug_x64 vm/cc/Debug_InterruptIsolate
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

stdout:
Running test: Debug_InterruptIsolate
Done: Debug_InterruptIsolate


stderr:
Waiting for isolate to be created
Waiting for isolate to be interrupted
Waiting for isolate to be shut down
Complete
../../runtime/vm/malloc_hooks.cc: 270: error: expected: MallocHooksState::initialized()


Command[run_vm_unittest]: DART_CONFIGURATION=DebugX64 out/DebugX64/run_vm_tests --ignore-unrecognized-flags Debug_InterruptIsolate
Took 0:00:00.135797

Short reproduction command (experimental):
    python tools/test.py -t120 vm/cc/Debug_InterruptIsolate
```

Crash dump is available at 

https://storage.cloud.google.com/dart-temp-crash-archive/d7400804-4d2e-4ba7-90d2-793f1518b47a/debug_x64_run_vm_tests.tar.gz
https://storage.cloud.google.com/dart-temp-crash-archive/d7400804-4d2e-4ba7-90d2-793f1518b47a/core.26866.tar.gz

**Comment by mraleph** [comment]
Why was this closed? I think it's a different crash. It crashes on 

```
../../runtime/vm/malloc_hooks.cc: 270: error: expected: MallocHooksState::initialized()
```

**Comment by a-siva** [comment]
Submitted https://codereview.chromium.org/2671133002/ to fix the flaky test.

**Comment by mraleph** [comment]
@a-siva thanks! 

there is another (or multiple other) MallocHooks related shutdown race: see #28638. Will that one be fixed too by this CL or is it a different race?

**Comment by a-siva** [comment]
That one looks different, I will take a look.

On Mon, Feb 6, 2017 at 11:31 PM, Vyacheslav Egorov <notifications@github.com
