### ISSUE TITLE
content_shell being uploaded in the wrong place

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28615]
See https://travis-ci.org/dart-lang/angular2/jobs/197544350#L637

It seems that things are being uploaded, but with a nested `dartium` in the path

Expected: `https://storage.googleapis.com/dart-archive/channels/dev/release/latest/dartium/content_shell-linux-x64-release.zip`

Actual: `https://storage.googleapis.com/dart-archive/channels/dev/release/latest/dartium/content_shell-linux-x64-release.zip`

**Comment by whesse** [comment]
Fixed.  This happened when a run of the promote script failed, and left the dartium directory behind.  Renamed the dartium/dartium directory to d2, then back to dartium.
