### ISSUE TITLE
IntelliJ Test support broken in 1.22.0-dev.10.3

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28618]
IntelliJ runs the snapshot directly – but it seems they need to pass in another flag to support the old snapshot format

https://github.com/dart-lang/sdk/wiki/Snapshots#application-snapshots

May need to talk to VM team
```
/Users/kevmoo/homebrew/opt/dart/libexec/bin/dart --checked file:///Users/kevmoo/homebrew/opt/dart/libexec/bin/snapshots/pub.dart.snapshot run test:test -r json /Users/kevmoo/source/github/dart2js_info
Testing started at 3:13 PM ...
file:///Users/kevmoo/homebrew/opt/dart/libexec/bin/snapshots/pub.dart.snapshot is not a valid UTF-8 script

Process finished with exit code 253
```

**Comment by devoncarew** [comment]
What version of the Dart plugin / webstorm?

**Comment by fsc8000** [comment]
Unrelated: why pass ```--checked``` to pub? pub itself should run in unchecked mode.

**Comment by kevmoo** [comment]
IntelliJ IDEA 2016.3.1
Build #IU-163.9166.29, built on December 9, 2016
Licensed to Dart Language / Kevin Moore
Subscription is active until October 5, 2017
For non-commercial open source development only.
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by a-siva** [comment]
I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/28511

**Comment by devoncarew** [comment]
Yup, this is a dup. Kevin, Alex released a version of the plugin Friday with a fix for this. That fix is available for IntelliJ version 2016.3.3 and higher I believe. We have an outstanding request to push some changes back to 2016.3.1 (or more correctly, to see if we can expand the version range of the 2016.3 Dart plugin to cover 2016.3.1 as well).

**Comment by jwren** [comment]
Kevin, can you confirm that 2016.3.3 fixes the issue for you?

**Comment by kevmoo** [comment]
Yup!

Of course the pain here is diagnosing this...

IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Licensed to Dart Language / Kevin Moore
Subscription is active until October 5, 2017
For non-commercial open source development only.
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by kevmoo** [comment]
I guess this was addressed in Intellij. Closing.

**Comment by alexander-doroshko** [comment]
Published Dart plugin update compatible with IntelliJ IDEA 2016.3.1 (Build 163.9166.*)

**Comment by kzhdev** [comment]
I have the same issue in WebStorm.

/usr/local/opt/dart/libexec/bin/dart --ignore-unrecognized-flags --checked --trace_service_pause_events file:///usr/local/opt/dart/libexec/bin/snapshots/pub.dart.snapshot run test:test -r json /Users/kzhao/repo/matcher_test/test/matcher_test_test.dart
Testing started at 10:52 PM ...
file:///usr/local/opt/dart/libexec/bin/snapshots/pub.dart.snapshot is not a valid UTF-8 script

Process finished with exit code 253

**Comment by kevmoo** [comment]
@kzhdev which version of IntellliJ And Dart are you sing?

**Comment by kzhdev** [comment]
@kevmoo 

CLion 2016.1.2
Build #CL-145.972, built on May 18, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by kzhdev** [comment]
@kevmoo Sorry, wrong software. Here is the one:

WebStorm 2016.2.4
Build #WS-162.2228.20, built on October 18, 2016
Licensed to TRADING TECHNOLOGIES / Kun Zhao
You have perpetual fallback license for this version
Subscription expired on December 2, 2016
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by alexander-doroshko** [comment]
@kzhdev, so as you can see from the previous comments, the issue if fixed long ago in 2016.3.x and more recent IDE updates.

**Comment by kzhdev** [comment]
@kevmoo 

More color on this. It is pretty easy to reproduce. Just create an new Console Application through WebStorm and run the test.

Tests on Dart package Package project is working fine.

**Comment by kzhdev** [comment]
@alexander-doroshko Oh, I thought that just for IntelliJ. Too bad, I can't upgrade to 2016.3 that is not free. :(

**Comment by alexander-doroshko** [comment]
Dart SDK 1.22 was released on February 14, 2017, way later than WebStrom 2016.2 that you use. WebStrom 2016.3 was already available at that moment. You shouldn't expect the IDE to be future-compatible with all the upcoming SDKs.
