### ISSUE TITLE
Wrong character is not encoded by Uri.encodeFull()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28621]
Please see https://api.dartlang.org/stable/1.21.1/dart-core/Uri/encodeFull.html

> All characters except uppercase and lowercase letters, digits and the characters !#$&'()*+,-./:;=?@_~ are percent-encoded. This is the set of characters specified in in ECMA-262 version 5.1 for the encodeURI function .

But ECMA-262 version 5.1 https://www.ecma-international.org/ecma-262/5.1/ doesn't include "#" character. Therefore it should be encoded but the current version of Uri.encodeFull() doesn't encode it. Please, change documentation and the implementation

**Comment by lrhn** [comment]
The specification of `encodeURI` in ES5 states that:

> Let *unescapedURISet* be a String containing one instance of each character valid in *uriReserved* and *uriUnescaped* plus “#”.

This is the "unescapeSet" used to avoid escaping in the general Encode algorithm called by `encodeURI`, so `#` is not encoded by `encodeURI`.

**Comment by sgrekhov** [comment]
Ok, thank you for clarification. Didn't notice that. Another issue filled then #28623
