### ISSUE TITLE
analyze-libraries suite analyzes 4 new libs when using --use-sdk

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28620]
When running test.py -cdart2analyzer -rnone, we run the analyze-libraries test suite, which analyzes all the libraries in sdk/lib or [build dir]/dart-sdk/lib, depending on if --use-sdk is passed.

In the dart-sdk/lib, there are copies of 4 libraries from pkg: analyzer, analysis_server, dev_compiler, and front_end.

These currently don't analyze cleanly in this context, or don't have the right status lines, so we are skipping them for now.  The skip marker is in tests/lib/analyze_library.status

We should make them pass, and remove the skip lines.

**Comment by whesse** [comment]
Somehow, the tests are failing on the bot while passing locally.  Suppressing analyze_libraries on the bots with use_sdk, until this is resolved

**Comment by srawlins** [comment]
Since the test runners and tests and build configs have changed so much recently, I suspect this has been fixed. Please re-open if not.
