### ISSUE TITLE
An inconsistent result when encounter a negative 0 with toString function in dart2js

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#28622]
For example,
if foo is a 0 number.
```(-foo).toString()``` in Browser and DartVM env. will be "0"
But dart2js will be this code.
```J.toString$0$(J.$negate$n(foo))```
the result will be "-0.0"

Here is the source code from dart2js:
```
toString$0: function(receiver) {
    if (receiver === 0 && 1 / receiver < 0)
      return "-0.0";
    else
      return "" + receiver;
  },
```

**Comment by zoechi** [comment]
Sounds like https://github.com/dart-lang/sdk/issues/4984#issuecomment-276725901

**Comment by lrhn** [comment]
It is indeed #4984.
