### ISSUE TITLE
Fasta unit tests fail when run with --use-sdk on bots

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28629]
Our unit test runners download the built SDK from the builders, so they don't have the patched_sdk libraries that the fasta unit tests need.

Fasta will eliminate its dependence on these libraries in the future, so that is probably the best way to fix this bug.

Suppressing the tests when run with --use-sdk in pkg/pkg.status:
front_end/test/fasta/compile_test
front_end/test/fasta/kompile_test
front_end/test/fasta/outline_test

@peter-ahe-google

**Comment by peter-ahe-google** [comment]
Summary of our conversation:

* The tests will be skipped when run with --use-sdk. There's no way around that: the tests won't work on the bots (as they don't have the built SDK), but they'll work locally if you have built the runtime target.

* Within a few business days (and later today if nothing else catches fire), Bill will update the recipes for the vm-kernel bots. These bots will then run pkg/front_end/test/fasta, which should be helpful to everyone involved in the kernel project.

@mraleph @kmillikin

**Comment by jensjoha** [comment]
Is this fixed?

**Comment by whesse** [comment]
I believe the vm-kernel bots are running the tests in pkg/front_end, as shown in the following log:
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-kernel-linux-release-x64-be%2F6101%2F%2B%2Frecipes%2Fsteps%2Ffront-end_tests%2F0%2Fstdout

Examples of tests being run are:
Done none-vm-checked release_x64 pkg/front_end/test/fasta/shaker_test: pass
Done none-vm-checked release_x64 pkg/front_end/test/fasta/tool_test: pass
Done none-vm-checked release_x64 pkg/front_end/test/fasta/uri_translator_test: pass
Done none-vm-checked release_x64 pkg/front_end/test/fasta/messages_test: pass
Done none-vm-checked release_x64 pkg/front_end/test/fasta/parser/token_stream_rewriter_test: pass
Done none-vm-checked release_x64 pkg/front_end/test/fasta/type_inference/type_schema_environment_test: pass

**Comment by jensjoha** [comment]
So yes, the recipes have been updated and this issue can be closed?

**Comment by whesse** [comment]
I'm not sure if it should be left open until the underlying issue of the unit tests needing patched libraries is fixed

**Comment by whesse** [comment]
@athomas

**Comment by peter-ahe-google** [comment]
We need to remove these sections from the status file and fix whatever issue we find.

**Comment by peter-ahe-google** [comment]
Fixed in 62d225571959b49402bc5daa3faac591732b1022. Remaining issues moved to other bugs.
