### ISSUE TITLE
Dart Observatory traces no longer load in Chrome about:tracing

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#28628]
Chrome: Version 57.0.2987.19 (Official Build) dev (64-bit) (mac)
<img width="803" alt="screen shot 2017-02-03 at 10 12 57 am" src="https://cloud.githubusercontent.com/assets/11857803/22602835/c141e69a-e9f9-11e6-82a7-3ade30080158.png">

Trace: https://ufile.io/a641c

**Comment by eseidelGoogle** [comment]
This is using flutter/flutter@acc7d110c0a3a2d98a13f534ecb3720178971de0

**Comment by fsc8000** [comment]
@johnmccutchan

**Comment by johnmccutchan** [comment]
Tracing now assumes there is a name property of a Sample event.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2681463003
