### ISSUE TITLE
# character is percent-escaped in Uri.dataFromString() constructor

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28623]
```dart
main() {
  Uri uri = new Uri.dataFromString("#");
  print(uri.toString()); // prints data:,%23
}
```
According to the https://api.dartlang.org/stable/1.21.1/dart-core/Uri/encodeFull.html this character should not be escaped. The same issue presents in Uri.dataFromBytes() constructor

**Comment by lrhn** [comment]
Like #28604, this is actually the required behavior from RFC 2397 for `data:` URIs.
