### ISSUE TITLE
Need APIs to recreate (the code for) an annotated member

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28631]

**Comment by scheglov** [comment]
Context?

**Comment by matanlurey** [comment]
Currently we are casting `ElementAnnotation` to `ElementAnnotationImpl`, and doing:

```dart
ElementAnnotationImpl annotation;

var params = annotation.annotationAst.arguments.arguments.map((e) {
  return e.toString();
}).toList();

// Something like, but not exactly:
return 'const ${annotation.name}($params)';
```

I'd like to be able to "recreate" an annotation without hacking into the expression AST.

**Comment by scheglov** [comment]
Do you have code for the file that contains the annotated `Element`?

**Comment by matanlurey** [comment]
No, just the summaries.

**Comment by scheglov** [comment]
OK, hypothetically, if there were an accessor `ElementAnnotation.code`, which would return the exactly same code as it was in the original file, how would you use it? Just code without imports does not seem very useful.

**Comment by matanlurey** [comment]
Currently I need to "record" some information, i.e. translate

```dart
@SomeAnnotation(foo: 'someValue')
@AnotherThing(bar: const Thing())
class MyClass {}
```

To approximately the following in another file:

```dart
void initMetadata() {
  metadataMap[MyClass] = [
    const SomeAnnotation(foo: 'someValue'),
    const AnotherThing(bar: const Thing()),
  ];
}
```

**Comment by scheglov** [comment]
What will you do with this code?

```Dart
const myValue = 'someValue';
@SomeAnnotation(foo: myValue)
@AnotherThing(bar: const Thing())
class MyClass {}
```

**Comment by scheglov** [comment]
BTW, there is `AstNode.toSource() -> String`.
So, you don't need to `hack into` annotation ASTs.

**Comment by matanlurey** [comment]
@scheglov:

> What will you do with this code?
> 
> ```Dart
> const myValue = 'someValue';
> @SomeAnnotation(foo: myValue)
> @AnotherThing(bar: const Thing())
> class MyClass {}
> ```

Right now? We _crash_ 😦 - but I'd like this to work in the future by outputting:

```dart
const SomeAnnotation(foo: 'someValue')
```

> BTW, there is `AstNode.toSource() -> String`.
> So, you don't need to `hack into` annotation ASTs.

We were originally trying to operate entirely on the `Element` model. If that's not possible I can definitely change the code to use the simpler `toSource`.

**Comment by scheglov** [comment]
The AST that is returned from `ElementAnnotationImpl.annotationAst` *is* from the `Element` model. Sure, it's AST, but this AST is resynthesized from summary - you don't need the original Dart files, only summaries.

**Comment by lrhn** [comment]
In your future, you probably also need to handle:
```dart
import "somelib.dart" as p;
import "someOtherLib.dart" as q;
const myValue = const p.Something.clever(q.myConstant);
@SomeAnnotation(foo: myValue);
class MyClass {}
```
Recreating a const value as source requires more than knowledge about the *value*, you also need to know which constructor to use to create the value, and which libraries to import to get to those constructors (if it's even possible, they might be private). 

If you can constrain the problem suitably, so you are not trying to solve the completely general "const value -> source" problem, I think you'll make your job *much* easier :)

**Comment by matanlurey** [comment]
Just wanted to de-escalate this issue, potentially. If the analyzer team is OK with us shipping using `ElementAnnotationImpl` from `lib/src` and accessing the `astNode` - this isn't a P1.

**Comment by bwilkerson** [comment]
I'd rather that you didn't, and especially that you didn't need to, but given time constraints, that might be the better option.

**Comment by jcollins-g** [comment]
It looks like dartdoc will need this for displaying annotations [issue #1268](https://github.com/dart-lang/dartdoc/issues/1268).  I just wrote the exact same casting hack in order to get something working initially, though dartdoc only requires the toSource() from the Annotation node.

**Comment by bwilkerson** [comment]
As Konstantin pointed out (in https://github.com/dart-lang/sdk/issues/28631#issuecomment-279104052) the work described in https://github.com/dart-lang/sdk/issues/28631#issuecomment-279101237 is effectively duplicating `toSource()`.

But their future need (of making this work with all code) is more than what I think dartdoc needs.

**Comment by bwilkerson** [comment]
So, thinking about this more, I think that the non-dartdoc case will need two pieces of data: an expression that, when executed, will produce the same value that the compiler would have created when it encountered the annotation and a list of imports that need to be added to the library into which the expression will be placed. We'll need to be careful that the imports cannot conflict with any other imports, probably by always adding prefixes (that follow a pattern that clients of this API can be careful to not collide with).

Does that sound reasonable? Can anyone think of anything I'm missing?

**Comment by matanlurey** [comment]
OK, I have more concrete issue:

```dart
const someToken = const OpaqueToken('blahBlahBlah');

@Component(
  providers: const [
    const Provider(someToken, useValue: 'Woohoo'),
  ],
)
```

I'm able to evaluate this annotation to a `DartObject`, but then I'm unable to get the identifier name, `someToken`, from within that array of providers. There doesn't seem to be any hidden `DartObjectImpl` where I can go back to the AST safely. 

This is the blocking issue right now that I need guidance around :-/

(It might just involve changing Angular, but I want to only do that if necessary)

**Comment by matanlurey** [comment]
I could traverse the element.annotationAst... But ugh.

**Comment by matanlurey** [comment]
OK, I got this to work without doing any more hacking.

We still will need help to resolve the `useValue: ` portion of this though.

/cc @alorenzen

**Comment by matanlurey** [comment]
Here is one of the most tricky examples:

```dart
@Component(
    selector: 'root',
    providers: const [
      Registry,
      // 'someHeaderProvider' is a top-level function in another file.
      const Provider(HeaderProvider, useValue: prefix.someHeaderProvider)
    ],
)
```

How can we re-create "prefix.someHeaderProvider"?

**Comment by bwilkerson** [comment]
> OK, I got this to work without doing any more hacking.

I'd be interested in getting more detail on how you got that to work, perhaps by e-mail.

> We still will need help to resolve the useValue: portion of this though.
> ...
> How can we re-create "prefix.someHeaderProvider"?

(@natebosch This applies to your issue as well.)

Neither ElementAnnotation nor DartObject have enough information to make either of those possible. We'll need to add some additional support, based on the information in the AST, that produces the code you need.

Instances of DartObject represent the value of a constant, not the computation of the constant. They are used to allow the analyzer to perform constant value comparison in order to catch certain errors (such as having the same value appear in two `case` clauses within a `switch` statement. You need something much different, and it's going to need to rely on information in the AST.

We have at least two places where this is needed now, so I'd really encourage everyone to contribute to a solution in the 'analyzer' package that can be shared.

**Comment by matanlurey** [comment]
I definitely agree, re: contributing a solution.

I've scheduled a meeting next Tuesday with me Andrew Nate and you to sync.

**Comment by MichaelRFairhurst** [comment]
I think problems go deeper here, too.

```
enum _PrivateEnum {
  _PrivateValue
}

const public = [_PrivateValue]
```

```
import "...";

@Component(
  .... public[0] ...
)
...
```

this will need to be turned into `public[0]` by toSource, not `_PrivateValue`.

This strikes me as challenging enough that we maybe need a language feature, something like,

```
  return _PrivateValue from 'path/to/file.dart`.
```

Maybe if we had first-class code generation, we could ensure its only used by generated code.

**Comment by matanlurey** [comment]
It depends - if this was a `part` file (or we had extension libraries) you could refer to it.

**Comment by MichaelRFairhurst** [comment]
ah, yes, so code generators can do that to work around the privacy problem?

**Comment by bwilkerson** [comment]
There will always be the possibility of code that cannot be reconstructed.
But if we have a utility that generates code to recreate a constant, and it
can return a special value to indicate that the code cannot be generated,
then we can have a hint for users that their code isn't going to work with
the code generator they're using.

**Comment by MichaelRFairhurst** [comment]
Can we allow const reflection only?

```
void initMetadata() {
  metadataMap[MyClass] = [
    const MyClass.SomeAnnotation,
    const MyClass.AnotherThing
  ];
}
```

if its only allowed at the const level, could still use tree shaking, etc. And would be reflection without requiring dart mirrors.

**Comment by jcollins-g** [comment]
For the dartdoc use-case only:  https://codereview.chromium.org/2713243003

**Comment by bwilkerson** [comment]
@MichaelRFairhurst I'm not sure what you mean by "const reflection". We're not using reflection (in the mirrors sense, anyway), but yes, we're talking about annotations, so everything in the annotation must, by definition, be a const.

**Comment by MichaelRFairhurst** [comment]
Is there any way to something like the following?

```
class MyAnnotation {
  ...
}

@MyAnnotation(foo: bar)
class MyClass {
  ...
}

print(MyClass.annotations[MyAnnotation].foo);
```

Although my original thoughts about limiting this to const were not fully thought out.

**Comment by bwilkerson** [comment]
If you're asking about the ability to access metadata at run-time (in the same VM in which the annotated classes were loaded), then I believe the only way to do that is via reflection (mirrors or reflectable or some such).

But that isn't the scenario being discussed here. This is a request for analyzer to provide an API that can be used at analysis-time to produce code that, when executed by a VM, will produce the same object that is produced by compiling the annotation. The big distinction here is between analysis-time and run-time.

**Comment by bwilkerson** [comment]
I believe that we decided that we have a work-around for this, so it is no longer blocking 1.23. Let me know if I've misunderstood.

**Comment by kevmoo** [comment]
I talked to Andrew today – he's thinking the workaround will be too
painful. I'll start a thread to discuss...

**Comment by natebosch** [comment]
I've started a repo that demonstrates the usage we're hoping to achieve. We still need to flesh out all the edge cases, but this should get us started.

https://github.com/natebosch/recreate-const-test/blob/master/test/annotation_recreation_test.dart

I've implemented a trivial version that works for annotations without arguments, and shown how it fails once we introduce arguments.

**Comment by matanlurey** [comment]
So, FWIW, we got pretty far here without needing additional support.

No promises everything will "just work" when we move to the CFE, but we have test cases.
