### ISSUE TITLE
Analyzer should collect all the information it needs to reproduce a crash and automatically file a bug when it does so

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28633]
(This should be opt-in, for obvious reasons.)

The analyzer frequently crashes for me. It's always in really obscure cases like when I've just switched branches or when I've made some obscure syntax error that I've fixed by the time the analyzer crashes (because it read all the files up front then parsed then then crashed a minute later), or some such, and so I can never reproduce it.

I would love it if there was some way I could opt-in to having such crashes automatically wrap up all the input that it saw, zip it up, and upload it to github or wherever you need it to fix the crashes.

**Comment by bwilkerson** [comment]
Actually, there already is. Just pass the command-line argument `--instrumentation-log-file=...` when starting up the analysis server (where the ellipsis is replaced by the absolute path (not URI) of the file you want it to write to). In IntelliJ you can do this by opening the 'Registry...' dialog ('Help' > 'Find Action...', the type 'Registry') and adding this to the entry named 'dart.server.additional.arguments'. The file will be overwritten every time you restart the analysis server.

**Fair warning:** the file contains all of the communications with the server, including the content of any files that were opened, all of the activity of server, including which files were analyzed, and other potentially sensitive data. Sending it via private e-mail is much safer than posting it to somewhere like github.

**Comment by Hixie** [comment]
Ah, cool. Then please consider this bug to just be about the part where the uploading happens automatically. :-)

**Comment by bwilkerson** [comment]
Yep. We're looking into that.

**Comment by Hixie** [comment]
awesome!

**Comment by srawlins** [comment]
@MichaelRFairhurst @scheglov is this fixed with our recent crash reporting work?

**Comment by MichaelRFairhurst** [comment]
Unfortunately no. Only internally. Externally we have to go through PDDs etc

**Comment by jcollins-g** [comment]
PDD now approves of external crash reporting.   It is now switched on under approved circumstances.   I'm not sure what "automatically file a bug" would mean in this context, but closing as fixed as we should now have the data to make judgments on whether it should be reported.
