### ISSUE TITLE
Why 34 != 34?

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/sdk#28643]
I have if check to compare two numbers, both of the numbers are from a map. Some how the comparison failed although both numbers are identical. Please see attached screenshot both algo['ownerId'] and userId are 34, int type.

![screen shot 2017-02-06 at 12 01 27 pm](https://cloud.githubusercontent.com/assets/1855243/22659740/757199f0-ec64-11e6-9a4c-19209d8733f6.png)

**Comment by kzhdev** [comment]
I am on Dart VM version: 1.22.0-dev.10.3 (Wed Feb  1 11:16:36 2017) on "macos_x64"

**Comment by kzhdev** [comment]
My bad. I have a typo in my code.

**Comment by floitschG** [comment]
Thanks for the fast update. This would have probably been an annoying bug to track down.

**Comment by kzhdev** [comment]
@floitschG It took me a while to find out it was a typo. :) Sorry for the false alarm.
