### ISSUE TITLE
Phrase 'constructor function' should not be used.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28641]
In Sect. 'Type of a function' of the language specification, the phrase _constructor function_ is used, and its return type is specified.

This phrase is never used elsewhere in the specification, and it is not obvious that it is well-defined. It is also not obvious that it should have a return type (constructors are procedures, they don't return anything).

**Comment by lrhn** [comment]
It might make a little sense for factory constructors, which do return something, but not for generative constructors which only initialize an existing object, they don't return the object (the `new` operator does that).

**Comment by eernstg** [comment]
No milestone now: This correction is independent of Dart 2.

**Comment by eernstg** [comment]
Closing: The above-mentioned wording is not present in dartLangSpec.tex today.
