### ISSUE TITLE
VM crash dump archiving on Windows builders

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#28648]
Similar to what we do on Linux (see https://codereview.chromium.org/2640093005/)

@mkustermann @mraleph @whesse

**Comment by mkustermann** [comment]
The documentation for configuring this in the registry should be [here on msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181.aspx)

I'll take an attempt at this.

**Comment by mkustermann** [comment]
This is blocked ATM on [crbug.com/691971](https://bugs.chromium.org/p/chromium/issues/detail?id=691971).

**Comment by mkustermann** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/31065
