### ISSUE TITLE
Incorrect DDC runtime cast failure.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28642]
We're seeing DDC runtime cast failures as follows:

```
Casting value of type '(dynamic) -> void' to incompatible type '(bottom) -> FutureOr<void>)'
```

This cast should succeed.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2671113002/

**Comment by whesse** [comment]
Is this error really in 1.22, and a blocker?  So we should merge the fix?

**Comment by leafpetersen** [comment]
Yes, I will file a merge request.

**Comment by leafpetersen** [comment]
https://github.com/dart-lang/sdk/issues/28654
