### ISSUE TITLE
Several shared tests crashing on Windows

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28645]
There are several 'standalone' tests that are crashing on Windows because analyzer is creating invalid file paths.

**Comment by eernstg** [comment]
Gardening: Adjusted the status of packages_option_only_test, because it has had outcome CompileTimeError rather than Crash in 13 out of the past 20 builds (ending in 2620) on analyzer-win7-release-be.

**Comment by eernstg** [comment]
Gardening: Adding empty_packages_file_option_test status of `Pass, Crash` with reference to this issue, because it has crashed almost every time in builds 2581 .. 2620. When it fails we get `stderr: Invalid argument(s): Illegal character in path` which matches this issue.

**Comment by whesse** [comment]
Many status lines referring to this issue are removed in CL https://dart-review.googlesource.com/c/sdk/+/12240

**Comment by peter-ahe-google** [comment]
This may be fixed by https://dart-review.googlesource.com/46065.
