### ISSUE TITLE
strong mode: argument type mismatch error should be a implicit downcast warning

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28651]
Consider this example:
```dart
main(arg) async {
  List list = <int>[1];
  Iterable iterable = list;
  <int>[2].addAll(list);
  <int>[2].addAll(iterable);
}
```

Today you get:
```
[error] The argument type 'List' can't be assigned to the parameter type 'Iterable<int>'. (... line 5)
[warning] Unsafe implicit cast from 'Iterable<dynamic>' to 'Iterable<int>'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (... line 6)
```

I was honestly surprised to get the first error. I thought I was going to get a warning just like in the second case. This feels a bit like a usability issue: `List` is more precise than `Iterable`, so I wouldn't consider that switching to `Iterable` for my variable would change the behavior of the checker in some noticeable way.

/cc @leafpetersen

**Comment by leafpetersen** [comment]
Assignability `A <==> B` is currently defined (in strong mode) as `A <: B` or `B <: A`.  That is, we allow downcasts or upcasts, but not sideways casts.  Neither of those are true here.  We could choose to relax assignability more to all cross casts of generics when the classes are in a subclass relation.  I'm not super keen on making downcasts even more permissive though - we already let an amazing amount of stuff slide.

**Comment by sigmundch** [comment]
I think what made this surprising is that there are two paths to do get from `List` to `Iterable<int>`: an upcast followed by a downcast (`List -> Iterable -> Iterable<int>`), or an implicit generic downcast followed by an upcast (`List -> List<int> -> Iterable<int>`).

As a user the former one has the feel of a side-cast, but the latter doesn't. In fact, my first reaction was that the system didn't recognize that `List<int>` is a valid argument here.

I think relaxing this rule will match users' expectation better in these scenerios.

**Comment by leafpetersen** [comment]
This isn't new to strong mode, by the way.  Dart 1.0 has the same issue (not for dynamic, since dynamic is magic, but use Object instead and you get the same behavior).

What is the rule that you think you would like?

**Comment by sigmundch** [comment]
Ah - thanks for highlighting that. 

The rule I have in mind would treat the base type and the type-args as separate kind of subtyping relations: in a way we do have a distinction between a base-type downcast and a downcast-composite. We can say a side-cast is one where you do a upcast and a downcast on the same kind of subtyping relation (e.g. `List -> Iterable -> Set` is invalid, so is `Iterable<int> -> Iterable -> Iterable<String>`), but if you do a a mix of upcast on one and downcast on the other, then we don't label it as a side-cast and allow it without a static warning (but a possible runtime check). For example, this would allow an upcast on the base type and downcast on type-args (`List -> Iterable -> Iterable<int>`) or the reverse (`List -> List<int> -> Iterable<int>`).

Thoughts?

**Comment by leafpetersen** [comment]
So if you have `A<T>` and `B<S, R>`, and `A` and `B` are subclass/implements related, then find the (or in general "a", since their may be multiple) instantiation of the subclass at the superclass, then recurse on the arguments?  So if `B` is the superclass, then find the minimal `M` and `N` such that `A<T> <: B<M, N>`, and then check that `M <==> S` and `N <==> R`.  

Yeah, you could do that.  I personally feel like we already delay way too much to runtime type errors, so I'm not super keen on further relaxing things.

cc @munificent @eernstg @floitschG @lrhn

**Comment by lrhn** [comment]
My fears is that it's going to make some things easy and nice, and potentially other things undecidable.
With that definition, we can alternate between doing super-types and sub-type relations which might allow unrestricted expansions on the types you are comparing.
Not an expert, so looping in @johnniwinther.

**Comment by johnniwinther** [comment]
`tests/language/least_upper_bound_expansive_test.dart` to the rescue! In this test we the following classes:

```
class N<T> {}
class C1<T> extends N<N<C1<T>>> {}
```

To determine `N<C1<int>> <==> C1<num>` we start by finding `N` as the common superclass and `N<N<C1<num>>` as the instantiation of `C1<num>` at `N`. Now we need to compare the type arguments, i.e. determine `C1<int> <==> N<C1<num>>`. Again we find `N` as the common superclass now with `N<N<C1<int>>` as the instantiation of `C1<int>` at `N`. Next we need to compare the type arguments, i.e. determine `N<C1<int>> <==> C1<num>` but we are now back to where we started.

This means that with multiple instantiations (allowing `class C implements A<B1>, A<B2>`) this approach is [undecidable](http://www.cis.upenn.edu/~bcpierce/papers/variance.pdf) and without multiple instantiations decidability is unknown (pending a conclusion on the decidability of Java subtyping).

**Comment by leafpetersen** [comment]
I'm going to close this - downcast composite is only available as an opt in warning now, so refining it really isn't a priority.
