### ISSUE TITLE
Please merge: 15527f136f984af2707ef52969ea5391aa6b49fc, ac85576979a199b3d9307448077a2792eec7acff, a3b4366f11bee47b818b263b75adf0617f319563,  5817ba47e26469fa276c3a87bfdbcd6996894b96 to dev channel

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28654]
@whesse @mit-mit @kasperl @keertip @srawlins 

These are the last known blockers for 1.22.  They merge cleanly on top of dev.10.4 .

Restore Future.then ad hoc inference:
15527f136f984af2707ef52969ea5391aa6b49fc 

Instance method tearoffs are strict:
ac85576979a199b3d9307448077a2792eec7acff

Allow inference of Null:
a3b4366f11bee47b818b263b75adf0617f319563

Fix top and bottom type casts in DDC:
5817ba47e26469fa276c3a87bfdbcd6996894b96

**Comment by whesse** [comment]
Merged in 1.22.0-dev.10.5
