### ISSUE TITLE
strong mode typing with LineSplitter

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28650]
Not sure if this is a known issue or a user error :-), I'm also not sure what's the best area for this: it involves strong mode and the LineSplitter type in the core libraries, so I added both areas for now.

Here is a sample program:

```dart
import 'dart:async';
import 'dart:io';
import 'dart:convert';

main(arg) async {
  var s1 = new File(arg[0]).openRead().transform(UTF8.decoder);
  var s2 = s1.transform(const LineSplitter());
  int i = 0;
  await for (String line in s2) {
    print('${i++}: $line');
  }
}
```

Running `dartanalyzer --strong` on this file yields the error:
```
[error] The type 'Stream<List<String>>' used in the 'for' loop must implement Stream with a type argument that can be assigned to 'String'. 
```

The error comes from inferring s2 as `Stream<List<String>>`. Typing it as `Stream<String> s2` yields an error on the assignment instead. So today I can only get this program to work by declaring `Stream s2` with no type-args.

I'm not familiar enough with the type-system around streams to understand this. Is `await for` doing some implicit flattening and needs some kind of union type like with FutureOr? Is the code actually wrong in this case?

/cc @leafpetersen @floitschG

**Comment by leafpetersen** [comment]
I believe this is an analyzer configuration issue that has been fixed in bleeding edge, and has been cherry-picked to the dev-4.0.

https://github.com/dart-lang/sdk/issues/28507

If you still see this with a version that includes that fix, please let me know ASAP.

**Comment by sigmundch** [comment]
Indeed - in bleeding edge seems OK. Thanks Leaf.
