### ISSUE TITLE
Uri.file() constructor  issue for Windows semantics

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28659]
Please see https://api.dartlang.org/stable/1.21.1/dart-core/Uri/Uri.file.html

> With Windows semantics, backslash ("\\") and forward-slash ("/") are used to separate path segments, except if the path starts with "\\\\?\\" in which case, only backslash ("\\") separates path segments.

```dart
main() {
  Uri uri = new Uri.file(r"\\?\c:\a\b", windows: true);
  print(uri.path); // /c:/a/b
}}
```
According to the documentation from the above a beckslash ("\\") should be used as a path separator. Tested on Windows x64

**Comment by lrhn** [comment]
Documentation should be made clearer. The `\` is only ever used as a path segment separator in the *input* path. The resulting URI always uses `/` since `\` is not a valid URI character.

**Comment by lrhn** [comment]
Fixed.

**Comment by osa1** [comment]
If you've encountered this issue in your code, you need to use [`Uri.toFilePath`](https://api.dart.dev/stable/3.5.0/dart-core/Uri/toFilePath.html) instead of `Uri.path` to get a valid path on Windows.
