### ISSUE TITLE
no such method not called on properties of dart:html objects

### ISSUE THREAD

**Issue by TedSander** [dart-lang/sdk#28658]
# Describe your issue compiling with DDC
noSuchMethod is not called on get calls for properties of MouseEvent does not get called.

# Does this error show up at build time or at run time? run time

# Include repro instructions. How can we try to build (or run) this code?

Using mockito

class MockMouseEvent extends Mock implements MouseEvent {}

final mock = new MockMouseEvent();
final point = new Point(0,0);
when(mock.client).thenReturn(point);

var client = mock.client;

Expected:
Will return point

Actual:
noSuchMethod is never called on MockMouseEvent and mockito does not have an opportunity to return a value.

Tried to implement this in another way and it also doesn't work:
class MockMouseEvent extends Mock implements MouseEvent {
  @override
  Point client = new Point(0, 0);
}

**Comment by alan-knight** [comment]
Is this with DDC? It isn't clear from the description, and I think we might be playing games with noSuchMethod in Dartium.

**Comment by TedSander** [comment]
Yes sorry it is DDC. I thought that the issue tracker was just for that. Didn't realize it was a more general one. Vijay is looking at the issue.

**Comment by vsmenon** [comment]
Here's a smaller repro based on @davidmorgan 's internal test:

```dart
import 'dart:html' as html;

class Mock {
  noSuchMethod(Invocation i) {}
}

@proxy
class MockLocation extends Mock implements html.Location {
  String href = "";
  String get hash => href.substring(href.indexOf("#"));

  Uri get _uri => Uri.parse(href);

  String get pathname => _uri.path;
  String get search => _uri.query;
  String get origin {
    try {
      return Uri.parse(href).origin;
    } catch (e) {}
    return '';
  }

  void assign([String url]) {
    href = url;
  }
}

void main() {
  var mock = new MockLocation();
  mock.href = "foo";
  html.Location loc = mock;
  print(loc.href);
}
```

I suspect we're not handling fields in the mocked class correctly.

**Comment by vsmenon** [comment]
The bug is with field specifically.  A workaround for now: If `MockLocation`'s `href` is changed to a getter/setter (on a private variable), the code works.
