### ISSUE TITLE
LayoutTests need to be retriaged

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28663]
@alan-knight marked a chunk of co19 layout-tests as "Everything below this point is associated with co19 Issue 747". However that issue has been closed a long time ago: https://github.com/dart-lang/co19/issues/11

These tests should be retriaged.

**Comment by nex3** [comment]
@alan-knight I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by athomas** [comment]
LayoutTests have been deleted.
