### ISSUE TITLE
Bug in _Utf8StringBuffer

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28667]
The code from [_Utf8StringBuffer](https://github.com/dart-lang/sdk/blob/master/runtime/lib/convert_patch.dart#L1530) contains:

```dart
  void addCharCode(int char) {
    assert(char >= 0);
    assert(char <= MAX_UNICODE);
    if (partialState != NO_PARTIAL) {
      if (allowMalformed) {
        partialState = NO_PARTIAL;
        addCharCode(0xFFFD);
      } else {
        throw new FormatException("Incomplete UTF-8 sequence", utf8);
      }
    }
    ...
  }

```

I think there is no field/parameter called **utf8** in

@lrhn

**Comment by mkustermann** [comment]
Same is true for `runtime/bin/socket_patch.dart`:

```dart
class _NativeSocket {
  getOption(SocketOption option) {
    if (option is! SocketOption) throw new ArgumentError(options);
    ...
}
```

"options" vs. "option"

@whesse  How can we don't test the patched sdk for warnings?

**Comment by mkustermann** [comment]
I've discovered another bug which we didn't catch because we don't run analyzer on the patch files (kevin fixed it in https://github.com/dart-lang/sdk/commit/fdb4c100e0914677fd274b0deff91e6c818a6878)

**Comment by lrhn** [comment]
Good catch. A nice case of failing-in-a-throw, which isn't detected because we don't specify which error we throw.

**Comment by parlough** [comment]
Both mentioned cases were fixed in https://github.com/dart-lang/sdk/commit/327d8d1b0d680459b970bd662149509e063baf0d and this class of errors would be caught now.
