### ISSUE TITLE
Uri.file() issue for colon (":") in path

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28660]
Please see https://api.dartlang.org/stable/1.21.1/dart-core/Uri/Uri.file.html

> Examples using non-Windows semantics:

```dart
// C:
new Uri.file("C:", windows: false);
```
In fact:
```dart
  Uri uri = new Uri.file(r"C:", windows: false);
  print(uri.path); // C%3A
  Uri uri = new Uri.file(r":", windows: false);
  print(uri.path); // :
```
Why, for non-Windows semantics colon is encoded in the first case and non encoded in the second one?

Tested on Windows x64. Please make documentation and implementation consistent

**Comment by lrhn** [comment]
The reason the first colon is encoded is that `C:` looks like a scheme, so if you did `Uri.parse(new Uri.file("C:", windows: false).toString())`, you would not get the same URI back. The string ':' does not look like an URI scheme, so if you parse it back, it'll become a path again.
This was a recent fix to the `Uri` class, the documentation here wasn't updated.

The scheme is definitely missing in the latter example.

**Comment by sgrekhov** [comment]
Retested. No missing scheme issue. Sorry
