### ISSUE TITLE
Empty returns in functions returning Null should not be allowed in spec mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28668]
My change in https://github.com/dart-lang/sdk/commit/a3b4366f11bee47b818b263b75adf0617f319563 unintentionally changed the spec mode behavior as well.  This needs to be fixed, regardless of decisions about the strong mode behavior. 

cc @lrhn @floitschG @eernstg @munificent

**Comment by dgrove** [comment]
Any updates here?

**Comment by leafpetersen** [comment]
https://codereview.chromium.org/2752423003/
