### ISSUE TITLE
Please merge branch ddc-1.22.0-dev.10.5 into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28669]
@whesse @kasperl

This merges in the last 7 commits (landed on master).  These have already been patched into the internal branch of DDC and are needed to unblock the next internal roll:

https://github.com/dart-lang/sdk/commits/ddc-1.22.0-dev.10.5

Note, cherry-picking these CLs required regenerating the summary files and fixing one test expectation, but otherwise merged cleanly.

**Comment by whesse** [comment]
Merged in j1.22.0-dev.10.6
