### ISSUE TITLE
--no-error-notification Not Working

### ISSUE THREAD

**Issue by PamardGoogle** [dart-lang/sdk#28674]
I try to disable getting errors for all the files with the --no-error-notification flag. But I receive all the errors in all the files and it seems --no-error-notification is not disabling this behavior.

 Logs:

1486159845321:Noti:{"event"::"server.connected","params"::{"version"::"1.17.0","pid"::178954,"sessionId"::"1486159845024.8738"}}
1486159857819:Req:{"id"::"2","method"::"analysis.setAnalysisRoots","params"::{"included"::["/tmp/analysis_server_test247026551"],"excluded"::[]}}
1486159858004:Res:{"id"::"2"}
1486159858027:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/a/lib/h.dart","errors"::[]}}
1486159858035:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/a/lib/src/test.dart","errors"::[]}}
1486159858036:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/a/lib/e.dart","errors"::[]}}
1486159858038:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/b/lib/space.dart","errors"::[]}}
1486159858040:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/b/lib/world.dart","errors"::[]}}
1486159858043:Noti:{"event"::"analysis.errors","params"::{"file"::"/tmp/analysis_server_test247026551/dart/tools/cida/testproject/lib/helloworld.dart","errors"::[]}}

**Comment by srawlins** [comment]
Pietro is refering to the analysis server binary, documented here:

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html

**Comment by bwilkerson** [comment]
Yes, I believe that this is a bug in server. That said, it should be easy to work around it by ignoring the notification.

**Comment by devoncarew** [comment]
@srawlins @bwilkerson it looks like that cli arg is deprecated (https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html). I'll close this issue as working as expected - please let us know if this is blocking an important use case.
