### ISSUE TITLE
make frontend strong clean

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28673]
This is a meta-bug to track what needs to be done to make `package:front_end` strong clean.

General errors pending to be fixed in `package:front_end`:
* [ ] Incorrect type annotations
* [ ] Covariant overrides
* [ ] Covariant closures to forEach
* [ ] Downcast composite warnings

Issues that should be fixed in the language:
* [ ] #28646
* [x] #28601 

[This CL][1] will fix the first 3 and temporarily ignore all the downcast composite warnings. The downward composite warnings are clearly cases that will fail at runtime in strong mode, so we can't ignore them indefinitely. There are a few changes that will help fix them:
* [ ] add generics to stack_listener `push` `pop` and `popList`
* [ ] avoid union types:
    * [ ] split optional arguments as a separate stack entry (see [outline_builder][2])
    * [ ] see if we can flatten nested statement blocks differently (see [body_builder][3]).

We are delaying those changes until we set up some infrastructure that lets us track if those changes have any visible runtime performance effect.

[1]: https://codereview.chromium.org/2675603002
[2]:https://github.com/dart-lang/sdk/blob/41685ccf9a3c65bef48a7e71859443c8124c2cbd/pkg/front_end/lib/src/fasta/source/outline_builder.dart#L372
[3]:https://github.com/dart-lang/sdk/blob/41685ccf9a3c65bef48a7e71859443c8124c2cbd/pkg/front_end/lib/src/fasta/kernel/body_builder.dart#L243

**Comment by kasperl** [comment]
Fields are now virtual by defaults and the composite downcast warnings are opt-in.

**Comment by mraleph** [comment]
I am pretty sure this is done by now.
