### ISSUE TITLE
Out-of-memory on Windows ia32-debug VM tests

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28687]
Example:
```
FAILED: none-vm-checked debug_ia32 vm/cc/Script
Expected: Pass 
Actual: Crash
...
stderr:
e:\b\build\slave\vm-win-debug-ia32-be\build\sdk\runtime\vm\scavenger.cc: 402: error: Out of memory.
Dumping native stack trace for thread 1538
Stack dump aborted because GetAndValidateIsolateStackBounds.
```

Doesn't reproduce, but happened on:
https://build.chromium.org/p/client.dart/builders/vm-win-debug-ia32-be/builds/3183/steps/checked%20vm%20tests/logs/stdio

Please investigate.

**Comment by nex3** [comment]
@johnmccutchan I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by johnmccutchan** [comment]
Nothing to do here. The windows bot ran out of memory and the test failed because it couldn't allocate.
