### ISSUE TITLE
language/bad_raw_string_test/{03,none} failing when compiled by dartkp.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#28680]
Message (see https://build.chromium.org/p/client.dart/builders/vm-kernel-precomp-linux-release-x64-2-4-be/builds/968/steps/vm%20tests/logs/stdio):
```
FAILED: dartkp-dart_precompiled release_x64 language/bad_raw_string_test/03
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[dartk]:
CommandOutput[precompiler]:
CommandOutput[assemble]:
CommandOutput[remove_assembly]:
```

I'm skipping the test for `$compiler=dartkp` now, so please fix and reenable.

**Comment by whesse** [comment]
The test /03 may fail on linux and macos and pass on Windows, as noted in #28664 
I don't know what would make the none case fail.

**Comment by nex3** [comment]
@peter-ahe-google Is dartk still a going concern?

**Comment by nex3** [comment]
@peter-ahe-google I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by peter-ahe-google** [comment]
Thank you @nex3, I'll take a look.

**Comment by peter-ahe-google** [comment]
Proposed "fix": https://codereview.chromium.org/2743943002
