### ISSUE TITLE
Please support Dart specific predefined variables in IntelliJ / File and Code Templates

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28684]
IJ has a nice way to create new Files - "File and Code Templates". What I'm missing is some predefined Dart-specific variables. There is a variable PACKAGE_NAME but it is empty - don't know if this is a bug or if package_name points to something else which is not set in my case.

Please check out my SS - you'll see what I mean
![capturfiles-20170208_124721](https://cloud.githubusercontent.com/assets/116654/22736284/acc8ff16-edfd-11e6-9f8b-8543ec0b72da.png)

**Comment by alexander-doroshko** [comment]
I don't think there's anything on SDK end that should be done to support it. 
`${PACKAGE_NAME}` variable in IntelliJ IDEA is for Java package. Please see my comment to the [issue](https://youtrack.jetbrains.com/issue/WEB-19260) that you have filed in JetBrains issue tracker.
Requests to add other Dart-specific predefined variables are also welcome there. In some cases you may find custom variables useful.
I think this request can be closed here.

**Comment by MikeMitterer** [comment]
Great - Thanks!
