### ISSUE TITLE
File.copy() is broken on Windows if the source contains forward slashes

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28699]
If I have a file `foo\bar` on Windows and I run `new File("foo/bar").copy("elsewhere")`, it fails complaining that "The system cannot find the path specified." This violates the expectation that Windows supports both types of slash.

**Comment by zanderso** [comment]
I'm not able to reproduce this. I tried the program below:

```dart
main() async {
  Directory foo = new Directory('foo');
  File bar = new File('foo/bar');
  File elsewhere = new File('elsewhere');
  try {
    await foo.create();
    await bar.create();
    await bar.copy('elsewhere');
  } finally {
    await foo.delete(recursive: true);
    await elsewhere.delete();
  }
}
```

Is there some other way to repro this?

**Comment by nex3** [comment]
I saw this on an Appveyor bot and I didn't have time to come up with a clean repro. I'll try to do so later.

**Comment by nex3** [comment]
I haven't had time to find a clean repro, so I'm going to close this for now. I'll reopen if I find one later.
