### ISSUE TITLE
Completions should show a list of named parameters

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#28691]
In the context of a Flutter `new Widget(|)` where the actual class is some subclass of Widget that has a list of named parameters, the completion list returned should list all the named parameters. (The vertical bar illustrates the location of the editing caret when Ctrl-Space is typed.)

**Comment by mit-mit** [comment]
Here is a concrete example: Say the user has just created a new Flutter app using the standard template. They are looking at lines 78-80:

```
        child: new Text(
          'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
        ),
```

They now desire to make the text bold, but isn't sure that the right option is. Typing Ctrl-Space just before the paren on line 80 should list out all the named params on Text:

```
TextAlign textAlign
bool softWrap
TextOverflow overflow
double textScaleFactor
int maxLines
```

**Comment by mit-mit** [comment]
@danrubel any thoughts on this?

**Comment by sethladd** [comment]
Yes please :)

**Comment by danrubel** [comment]
You mean like this (see pic below)? This behavior is already part of Dart SDK 1.22.0-dev.10.6.
If there is a situation where you are not seeing this, please let me know and I can dig.

![image](https://cloud.githubusercontent.com/assets/2891888/22946553/c072b2ba-f2c5-11e6-8c44-5d92e1992829.png)

**Comment by mit-mit** [comment]
Ah, great, I see it now!

One question: Could we sort the named parameters above type completions when completing on "nothing"?

![screen shot 2017-02-15 at 13 11 38](https://cloud.githubusercontent.com/assets/13644170/22973953/50199dc4-f380-11e6-9870-b17ac83403f2.png)

**Comment by danrubel** [comment]
The Analysis Server returns **only** the named parameters as completion suggestions because those are the only valid completions in this situation. All of the other entries are added by IntelliJ.

**Comment by mit-mit** [comment]
Ugh, yes. @devoncarew how do we get the list to reflect just the parameters?

**Comment by alexander-doroshko** [comment]
IntelliJ doesn't add anything itself to the completion list received from the server.

**Comment by danrubel** [comment]
My completion service tests for situations like this indicate that the completion suggestions only include named parameters, but maybe I'm missing something here. I'll run a local test here to verify exactly what is being sent across the wire.

**Comment by danrubel** [comment]
I tested this with a Dart SDK built from head yesterday all looks good.
1) Analysis Server only suggests named arguments in this situation
2) Alexander is correct that IntelliJ only shows what the Analysis Server provides

Once Flutter pulls the latest Dart SDK, this will no longer be an issue.

![image](https://cloud.githubusercontent.com/assets/2891888/22994542/48283b74-f395-11e6-872f-7b73a3c3118c.png)

**Comment by sethladd** [comment]
Very cool, thanks for the update!

**Comment by devoncarew** [comment]
🎉
