### ISSUE TITLE
3 front-end unit tests are failing if only runtime (no summaries) is built.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28698]
Running pkg/front_end tests on a buildbot that only builds runtime and runtime_kernel causes three tests to fail because summary files are missing from sdk/lib/_internal.

pkg/front_end/test/incremental_kernel_generator_test
pkg/front_end/test/incremental_resolved_ast_generator_test
and
pkg/front_end/tool/perf_test
all fail because
sdk/lib/_internal/strong.sum
and
sdk/lib/_internal/spec.sum
have not been built.

Marking as skip until this can be fixed, because they will fail on the buildbots and pass on local runs, if no --use-sdk flag is passed, depending on what has been built.

A good solution would be for the runtime_kernel target to build these files, if that makes sense for the developers of kernel.

**Comment by stereotype441** [comment]
Agreed that it would be good for the runtime_kernel target to build these files.  @whesse @peter-ahe-google do either of you have the expertise to make this change?  I don't know how to modify the runtime_kernel target to build these files.

**Comment by peter-ahe-google** [comment]
@whesse can you help us make that change?

@mkustermann @mraleph any concerns regarding changing the build files?

**Comment by jensjoha** [comment]
I cannot reproduce this locally.
2 out of 3 status entries updated here no longer exist, and the remaining one (perf_test) doesn't seem necessary anymore. I'm currently running the trybots to verify.
Assuming that's correct, can this issue be closed? Or @whesse do you have some additional insight?

**Comment by whesse** [comment]
No comment from my end.  If the original failures are no longer happening, and the reason is not longer valid, then it should be dropped.

**Comment by peter-ahe-google** [comment]
I don't think we need the summaries anymore as we use dill files.
