### ISSUE TITLE
lldb is very slow when profiler is enabled

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28702]
Debugging on Mac via `lldb` is very slow when profiler is enabled. Currently when using lldb one has to run VM with `--no-profiler` to get reasonable performance. This is most likely due to SIGPROF signals flooding lldb.

We need to either reflect this somewhere in documentation or disable profiler under the debugger. 

(see https://developer.apple.com/library/content/qa/qa1361/_index.html for detecting profiler)

**Comment by johnmccutchan** [comment]
In the past lldb would not work when running with the profiler enabled. It would stop for each SIGPROF.
