### ISSUE TITLE
Uri.parse() issue for data scheme

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28700]
Uri.parse() doesn't percent-escape path for data scheme

```dart
  print(Uri.parse("data:text/plain,some data")); // data:text/plain,some data
  // Compare with:
  print(new Uri(scheme: "data", path: "text/plain,some data")); // data:text/plain,some%20data
```

This issue exists for data scheme only. For other schemas path is escaped
```dart
  print(Uri.parse("http:text/plain,some data")); // http:text/plain,some%20data
```

The same issue exists for DataUri.parse()
```dart
  print(UriData.parse("data:text/plain,some data").contentText); // some data
  print(new UriData.fromString("some data").contentText); // some%20data
```

**Comment by lrhn** [comment]
The `UriData` isn't currently normalizing. Maybe it should be.
At least we should not put invalid data back into a `Uri` object, which is happening here.

As usual, normalizing comes at a performance cost.

**Comment by lrhn** [comment]
It is now normalized to some extent.
