### ISSUE TITLE
Invocation should provide factory constructors

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28706]
There are times where you need to synthesize an `Invocation` object.  When this need arises, the current solution is to manually define a class that implements `Invocation` and returns the data you wish to synthesize.  For example:

```
class _MethodInvocationProxy extends Invocation {
  _MethodInvocationProxy(
    this.memberName,
    this.positionalArguments,
    this.namedArguments,
  );

  @override
  final Symbol memberName;

  @override
  final List<dynamic> positionalArguments;

  @override
  final Map<Symbol, dynamic> namedArguments;

  @override
  final bool isMethod = true;

  @override
  final bool isGetter = false;

  @override
  final bool isSetter = false;
}
```

@abarth says he's seen this pattern repeated in various projects.  If it's a fairly common pattern, it'd be nice to just provide the functionality in the SDK itself, via various factory constructors.

***Proposal***:

```
Invocation.method(
  Symbol memberName, {
  List<dynamic> positionalArguments,
  Map<Symbol, dynamic> namedArguments,
});

Invocation.getter(Symbol memberName);

Invocation.setter(Symbol memberName, dynamic value);
```

**Comment by rmacnak-google** [comment]
I see no issue implementing this on the VM.

@rakudrama Thoughts on dart2js?

**Comment by rakudrama** [comment]
I see no problem for dart2js.

If you make them external patched factory constructors with dummy (throwing) dart2js implementations, we can fix them later.
Specify whether the symbol for Invocation.setter includes the '=' (probably should).
FWIW we try to avoid noSuchMethod in dart2js apps.

**Comment by tvolkert** [comment]
+1 for the symbol for Invocation.setter including the '='

**Comment by srawlins** [comment]
The Invocation gained a handful of new constructors around Dart 2.1. https://api.dart.dev/stable/2.8.0/dart-core/Invocation-class.html
