### ISSUE TITLE
Expose better coverage options in dart2js

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28709]
Go beyond the existing `traceCalls`environment flag.

* Make it a normal compiler flag
* Just log to an ES6 Map to make it fast
* Make it easy to get the data out via the console.

https://github.com/dart-lang/sdk/blob/af4b2b8e30f6bce0da2790e7ec5853caedefa165/pkg/compiler/lib/src/js_backend/backend.dart#L338

**Comment by rakudrama** [comment]
For function coverage:

If you really want it fast, log to a typed array.

* Allocate a coverage ID to each function, with the IDs being compact [0..N).
* Ensure that the coverage array is in a global visible to all code, e.g.  `$.coverage`.
* Used/not-used:  `$.coverage[ID]=1`, Uint8Array.
* Frequency profiling: `++$.coverage[ID]`, Uint32Array.
* The array can be swapped out to get separate profile info for different phases / actions.
* Provided the array is swapped out asynchronously, we can teach the optimizer that `$.coverage[ID]=1` is idempotent in non-async code.
* The array can be processed into a map is desired.

Is there any use case for edge coverage (caller - callee)?
This could tell you _how_ some code is active.
Tracking single edges might not be enough to understand what is going on (e.g. calling a wrapped method).

**Comment by kevmoo** [comment]
Don't think we need to get that fancy.

```javascript
var myMap = new Map();
myMap.set(1234, true);
myMap.set(2345, true);
Array.from(myMap.keys());
// [1234, 2345]
```

Edges: sure! But let's get the easy thing done first!

**Comment by matanlurey** [comment]
@grouma is now working on methods using the built-in Chrome coverage tool.

I think we can close this.
