### ISSUE TITLE
dart_developer_disabled_env_test fails on dartium

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28718]
It appears that the environment variable test is failing on dartium, needs investigation.

FAILED: none-dartium-checked release_x64 standalone/dart_developer_disabled_env_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dartium]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.084
        },
        {
              type: window_onerror
              value: window.onerror called: 
                    
                    http://127.0.0.1:56939/root_build/generated_tests/none-dartium-checked/tests_standalone_dart_developer_disabled_env_test/test.dart:0:
                    Exception: Expect.isFalse(true) fails.
                    
                    
              timestamp: 0.085
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 0.086
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /b/build/slave/dartium-mac-x64-inc-be/build/src/dart/tests/standalone/dart_developer_disabled_env_test.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    </head>
                    <body>
                      <h1> Running /b/build/slave/dartium-mac-x64-inc-be/build/src/dart/tests/standalone/dart_developer_disabled_env_test.dart </h1>
                      <script type="text/javascript" src="/root_dart/tools/testing/dart/test_controller.js">
                      </script>
                      <script type="application/dart" src="/root_build/generated_tests/none-dartium-checked/tests_standalone_dart_developer_disabled_env_test/test.dart" onerror="scriptTagOnErrorCallback(null)" defer="">
                      </script>
                      <script type="text/javascript" src="/root_dart/pkg/browser/lib/dart.js"></script>
                    
                    </body>
              timestamp: 0.086
        },
  ]
  

stderr:

BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  

To retest, run:  /b/build/slave/dartium-mac-x64-inc-be/build/src/dart/tools/sdks/mac/dart-sdk/bin/dart /b/build/slave/dartium-mac-x64-inc-be/build/src/dart/tools/testing/dart/http_server.dart -p 56939 -c 56941 --build-directory=/b/build/slave/dartium-mac-x64-inc-be/build/src/out/Release/ --runtime=dartium --packages=/b/build/slave/dartium-mac-x64-inc-be/build/src/dart/.packages

Command[dartium]: /b/build/slave/dartium-mac-x64-inc-be/build/src/dart/tools/sdks/mac/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:56939/root_build/generated_tests/none-dartium-checked/tests_standalone_dart_developer_disabled_env_test/test.html?crossOriginPort=56941
Took 0:00:00.104585

Short reproduction command (experimental):
    python tools/test.py -mrelease -rdartium --checked -t60 standalone/dart_developer_disabled_env_test

===
=== 1 test failed
===

**Comment by johnmccutchan** [comment]
The root cause of the test failure is https://github.com/dart-lang/sdk/issues/14651

**Comment by johnmccutchan** [comment]
The test relies on VMOptions being respected. Dartium does not.

**Comment by a-siva** [comment]
I saw some failures in dart2js too, could it be the same issue for dart2js too.

Maybe we just adjust the status file to skip these tests on dartium

**Comment by a-siva** [comment]
FAILED: dart2js-jsshell release_x64 standalone/dart_developer_env_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
Dart file (/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/tests/standalone/dart_developer_env_test.dart) compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js

CommandOutput[jsshell]:

stdout:
computeCurrentScript@out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js:23:13
get currentScript@out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js:55:37
@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:799:9
@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:794:4
@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:23:2



stderr:
/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:287:17 Error: 
Stack:
  H.wrapException@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:287:17
  K.Expect__fail@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:559:13
  K.Expect_isTrue@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:556:7
  N.main@/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:566:7
  @/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:816:7
  @/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:800:7
  @/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:794:4
  @/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js:23:2


Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --fast-startup --packages=/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/.packages /b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/tests/standalone/dart_developer_env_test.dart --out=/b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js
Took 0:00:00.503504

Command[jsshell]: DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/tools/testing/bin/jsshell -f out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js -f /b/build/slave/dart2js-linux-jsshell-2-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_standalone_dart_developer_env_test/out.js
Took 0:00:00.069611

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rjsshell --fast-startup -t60 --use-sdk --dart2js-batch --reset-browser-configuration standalone/dart_developer_env_test


===
=== 1 test failed
===

**Comment by a-siva** [comment]
I believe this command also fails similarly
python tools/test.py -mrelease -cdart2js -rd8 --checked --minified --fast-startup -t120 --use-sdk --dart2js-batch --reset-browser-configuration standalone/dart_developer_env_test

**Comment by johnmccutchan** [comment]
My CL also skips both tests when the compiler is dart2js.
