### ISSUE TITLE
Minified dart2js sometimes outputs duplicate JS function parameters

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#28727]
We recently ran into an issue where a class with a large-ish inheritance hierarchy started behaving oddly in dart2js, but only in the minified version.

After a lot of time debugging, I tracked down the cause to be duplicate function parameters in the JS output.
* Unminified output:
    ```js
    function MenuNavbarComponent(_menu_navbar$_renderedToolbarModelIds, _$MenuNavbarComponentImplMixin_$defaultConsumedProps, RenderPerformance__endMetric, RenderPerformance_performanceLabel, BatchedRedraws_shouldBatchRedraw, _FluxComponentMixin__subscriptions, _typedPropsCache, _props, _react$_state, _ref, _jsRedraw, _jsThis, _setStateCallbacks, _transactionalSetStateCallbacks, _prevState, _nextState, nextProps, $ti) {
    ```
    (Fuller output for more context: https://gist.github.com/greglittlefield-wf/1303afdb5f89b6923bf7ea2aca26e1a3)

* Minified output:
    ```js
    function aqQ(ch, wT$, dU$, e0$, H$, I$, Q, a, b, c, d, e, f, r, x, y, z, r) {
    ```

Note that in the minified version, the parameter `r` appears twice, which results in the field `_transactionalSetStateCallbacks` being initialized to the value of `$ti`.

This error has been tested and reproduced in Dart 1.21.1 and 1.22.0-dev.10.3.

---

Also, I wrote a regex to help spot this issue ([Rexexper](https://regexper.com/#function(%3F%3A%20%5Ba-zA-Z0-9%5C%24_%5D%2B)%5C((%3F%3A%5Ba-zA-Z0-9%5C%24_%5D%2B%2C)*(%5Ba-zA-Z0-9%5C%24_%5D%2B)%2C(%3F%3A%5Ba-zA-Z0-9%5C%24_%5D%2B%2C)*%5C1(%3F%3A%2C%5Ba-zA-Z0-9%5C%24_%5D%2B)*%5C))):
```js
/function(?: [a-zA-Z0-9\$_]+)\((?:[a-zA-Z0-9\$_]+,)*([a-zA-Z0-9\$_]+),(?:[a-zA-Z0-9\$_]+,)*\1(?:,[a-zA-Z0-9\$_]+)*\)/
```
...which ended up helping me find another instance of this issue:
```dart
function x8(b,c,c){this.b=b
this.c=c
this.$ti=c
this.$deferredAction()}x8.builtin$cls="x8"
if(!("name" in x8))x8.name="x8"
$desc=$collectedClasses$.x8[1]
x8.prototype=$desc
x8.$__fields__=["b","c"]
x8.prototype.slz=function(a){return this.b=a}
x8.prototype.gtd=function(){return this.c}
```
I'll have to dig more into what that's doing...

**Comment by greglittlefield-wf** [comment]
Wrote a tool to check for this issue using that regex, for use in CI until this issue is fixed: https://gist.github.com/greglittlefield-wf/02ad8f731d48e74507d9f372882bb2ea

**Comment by rakudrama** [comment]
This happens with the combination of `--csp` and `--minify`.
Fix out for review: https://codereview.chromium.org/2690583003/

**Comment by kevmoo** [comment]
Landed! https://github.com/dart-lang/sdk/commit/6af28fcb70010f5804410890e5ac2b29858808a6
