### ISSUE TITLE
Analysis server exception in Fuchsia project

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#28729]
Exception from analysis server (running from Atom)

### what happened

1. Clone the fuchsia tree.
2. rm -rf out (if you have it)
3. Open fuchsia/apps/modules in Atom
4. Edit a Dart file.
5. Save the file.

When I did the above, I got this exception.  I presume this has to do with the fuchsia build support in the analysis server.  (I'm not expecting analysis to work---just not to throw an exception.)

/cc @pylaligand 

### version information

- Dart SDK 1.22.0-dev.10.6
- Atom 1.14.1
- dartlang 0.6.45

### the exception

Failed to handle request: {params: {included: [/Users/abarth/git/fuchsia/apps/modules/contact/contact_flutter, /Users/abarth/git/fuchsia/apps/modules/email/email_flutter, /Users/abarth/git/fuchsia/apps/modules/email/email_service, /Users/abarth/git/fuchsia/apps/modules/email/map, /Users/abarth/git/fuchsia/apps/modules/email/tools, /Users/abarth/git/fuchsia/apps/modules/email/usps, /Users/abarth/git/fuchsia/apps/modules/email/youtube_related_videos, /Users/abarth/git/fuchsia/apps/modules/email/youtube_video, /Users/abarth/git/fuchsia/apps/modules/gallery, /Users/abarth/git/fuchsia/apps/modules/packages/config, /Users/abarth/git/fuchsia/apps/modules/packages/config_flutter, /Users/abarth/git/fuchsia/apps/modules/packages/contact_api, /Users/abarth/git/fuchsia/apps/modules/packages/email_api, /Users/abarth/git/fuchsia/apps/modules/packages/email_session_store, /Users/abarth/git/fuchsia/apps/modules/packages/fixtures, /Users/abarth/git/fuchsia/apps/modules/packages/flutter-http, /Users/abarth/git/fuchsia/apps/modules/packages/models, /Users/abarth/git/fuchsia/apps/modules/packages/music_api, /Users/abarth/git/fuchsia/apps/modules/packages/util, /Users/abarth/git/fuchsia/apps/modules/packages/widgets, /Users/abarth/git/fuchsia/apps/modules/packages/widgets_meta, /Users/abarth/git/fuchsia/apps/modules/tools/dartfmt_extras, /Users/abarth/git/fuchsia/apps/modules/tools/widget_specs], excluded: [], packageRoots: {}}, method: analysis.setAnalysisRoots, id: 4}  (fatal)

```
NoSuchMethodError: The method 'getSourcesWithFullName' was called on null.
Receiver: null
Tried calling: getSourcesWithFullName("/Users/abarth/git/fuchsia/apps/modules/gallery/lib/screens/common/widgets_gallery.dart")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1506)
#3      _rootRunUnary (dart:async/zone.dart:1158)
#4      _CustomZone.runUnary (dart:async/zone.dart:1037)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#10     _rootRunUnary (dart:async/zone.dart:1158)
#11     _CustomZone.runUnary (dart:async/zone.dart:1037)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#14     _DelayedData.perform (dart:async/stream_impl.dart:590)
#15     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#17     _rootRun (dart:async/zone.dart:1146)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

**Comment by bwilkerson** [comment]
Actually, I don't think it's related to the Gn support.

**Comment by scheglov** [comment]
What is `fuchsia tree`?

**Comment by scheglov** [comment]
Cannot reproduce.

I cloned `https://github.com/fuchsia-mirror/modules` and opened it in IDEA.
There is a lot of errors because of unresolved URIs.

When I change `/Users/scheglov/dart/fuchsia/modules/email/email_flutter/lib/embedded_child_builders.dart` Analysis Server sees the change and performs analysis. No exceptions.

**Comment by scheglov** [comment]
I imported several modules separately into IDEA, changed a file outside of IDEA, still see new errors, but not exceptions.

**Comment by scheglov** [comment]
The CL [was landed](https://github.com/dart-lang/sdk/commit/663b7f665e63eb9062028022d47dd24c56b789ff). Changes to IDEA Dart plugin still should be made.

**Comment by abarth** [comment]
> What is fuchsia tree?

https://fuchsia.googlesource.com/manifest/#Creating-a-new-checkout

(Although @bwilkerson doesn't think it's related.)

**Comment by scheglov** [comment]
When I open `fuchsia/apps/modules` in IDEA, there is a crash in `GnWorkspace`.

```
FileSystemException(path=/Users/scheglov/dart/fuchsia/out/; message=Directory listing failed)

#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:285:7)
#1      GnWorkspace._getOutDirectory (package:analyzer/src/generated/gn.dart:205:12)
#2      GnWorkspace.find (package:analyzer/src/generated/gn.dart:259:31)
#3      ContextBuilder.createWorkspace (package:analyzer/src/context/builder.dart:256:31)
#4      ContextBuilder.getAnalysisOptions (package:analyzer/src/context/builder.dart:389:27)
#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:152:31)
#6      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1838:48)
#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1169:39)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1211:16)
#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:868:9)
#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:1230:22)
#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:303:12)
#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:242:16)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:892:45)
```

**Comment by pylaligand** [comment]
That last one is definitely GN-related and I can fix it.

**Comment by scheglov** [comment]
Please reopen if this is still a problem.
