### ISSUE TITLE
Need core dump support on windows slaves, support archiving them on buildbot

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28735]
Similar to our linux buildbot slave setup we need support for archiving coredumps/minidumps/... on test failure crashes on windows. Then we need to change our core dump archiving code to upload them to GCS (to the gs://dart-temp-crash-archive iirc)

/cc @fsc8000 @mraleph

**Comment by mkustermann** [comment]
Here is an [example crash](https://build.chromium.org/p/client.dart/builders/vm-win-release-ia32-be/builds/5427/steps/vm%20tests/logs/stdio).

**Comment by mraleph** [comment]
Duplicate of #28648
