### ISSUE TITLE
Analyzer should provide a hint for generic type annotation in const expressions

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28750]
```
@override
  Iterator<E> get iterator => const <E>[].iterator;
```
with `.analysis_options` containing 

```yaml
analyzer:
  strong-mode: true
```
doesn't result in a hint

See also #28551

**Comment by lrhn** [comment]
That's not a hint. It's a plain and simple compile-time error. You cannot use non-constant parts (anything that doesn't have the same value on every evaluation) in a const expression, and that includes type variables.

**Comment by srawlins** [comment]
Yeah I feel like this should be P1. I see that the error exists in the front_end package, so I assume analyzer will just start showing these errors when it cuts over?

**Comment by eernstg** [comment]
By the way, when it's fixed and the error is reported as it should be you may still need to do such a thing. The standard solution is to use the bottom type: `const <Null>[].iterator`.

**Comment by natebosch** [comment]
I now see `const_with_type_parameters` errors from analyzer.
