### ISSUE TITLE
My daily "Dart Analyzer Error"

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28760]
- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.21.1 (Fri Jan 13 01:40:43 2017) on "macos_x64"
Pub 1.21.1

NPM: 4.1.2

IntelliJ IDEA 2017.1 EAP
Build #IU-171.3019.7, built on February 7, 2017
IntelliJ IDEA EAP User
------------
Analyzer%20Feedback%20from%20IntelliJ%0A%0A%23%23%20Version%20information%0A%0A-%20%60IDEA%20171.3019.7%60%0A-%20%601.21.1%60%0A-%20%60IU-171.3019.7,%20JRE%201.8.0_112-release-b702x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.11.6%20unknown,%20screens%201920x1080,%201920x1080,%202560x1440%60%0A%0A%23%23%20Exception%0A%0APlease%20append%20the%20contents%20of:%0Afile:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report.txt%0A%0A%60%60%60%0ADart%20analysis%20server,%20SDK%20version%201.21.1,%20server%20version%201.17.0,%20error:%20Task%20failed:%20ComputeConstantDependenciesTask%20for%20element%20TestOn(null%20expression)%20→%20TestOn%20in%20source%20/Users/mikemitterer/.pub-cache/hosted/pub.dartlang.org/test-0.12.19/lib/src/frontend/test_on.dart%0AUnexpected%20exception%20while%20performing%20ComputeConstantDependenciesTask%20for%20element%20TestOn(null%20expression)%20→%20TestOn%20in%20source%20/Users/mikemitterer/.pub-cache/hosted/pub.dartlang.org/test-0.12.19/lib/src/frontend/test_on.dart%0A%230%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:333)%0A%231%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%232%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%233%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%234%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1186)%0A%235%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%236%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1184)%0A%237%20%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:362)%0A%238%20%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:972)%0A%239%20%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:118)%0A%2310%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A%2311%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2312%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2313%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1150)%0A%2315%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2316%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2317%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2318%20%20%20%20%20Timer._createTimer.%3Canonymous%20closure%3E%20(dart:async-patch/timer_patch.dart:16)%0A%2319%20%20%20%20%20_Timer._runTimers%20(dart:isolate-patch/timer_impl.dart:385)%0A%2320%20%20%20%20%20_Timer._handleMessage%20(dart:isolate-patch/timer_impl.dart:414)%0A%2321%20%20%20%20%20_RawReceivePortImpl._handleMessage%20(dart:isolate-patch/isolate_patch.dart:148)%0A%0ACaused%20by%20NoSuchMethodError:%20The%20getter%20'iterator'%20was%20called%20on%20null.%0AReceiver:%20null%0ATried%20calling:%20iterator%0A%230%20%20%20%20%20%20Object._noSuchMethod%20(dart:core-patch/object_patch.dart:44)%0A%231%20%20%20%20%20%20Object.noSuchMethod%20(dart:core-patch/object_patch.dart:47)%0A%232%20%20%20%20%20%20ConstantEvaluationEngine.computeDependencies%20(package:analyzer/src/dart/constant/evaluation.dart:307)%0A%233%20%20%20%20%20%20ComputeConstantDependenciesTask.internalPerform%20(package:analyzer/src/task/dart.dart:1982)%0A%234%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:321)%0A%235%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%236%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%237%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%238%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1186)%0A%239%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%2310%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1184)%0A%2311%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:362)%0A%2312%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:972)%0A%2313%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:118)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A#15

**Comment by natebosch** [comment]
We are not able to repro stack traces with very old versions of the analyze. Please file a new issue if this is still a problem with the latest SDK.
