### ISSUE TITLE
Merge 339d16fbc5d6 to 1.22 stable (fixes #28757).

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#28766]
This should merge cleanly, as it is a 2-line change.

Commit: [339d16fbc5d6](https://github.com/dart-lang/sdk/commit/339d16fbc5d611fbbcf46235c290c615589ecc87)
Fixed issue: [#28757](https://github.com/dart-lang/sdk/issues/28757)

**Comment by mit-mit** [comment]
fyi @whesse

**Comment by whesse** [comment]
Will merge in the first patch release.  I plan to wait about 2-3 days to see if more merge requests come in, since this should not be blocking anyone's work (it won't hit code completion while typing, since that uses the analyzer).

**Comment by whesse** [comment]
This was merged in version 1.22.1.

**Comment by mit-mit** [comment]
This fixes https://github.com/dart-lang/sdk/issues/28757
