### ISSUE TITLE
Merge 6af28fcb7 to 1.22 stable (fix for Dart2js WRT long parameter lists)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28765]
**HAVE NOT** verified this merges cleanly. Will need a dev to run at this. Opening now to track for customer.

This is the commit: https://github.com/dart-lang/sdk/commit/6af28fcb70010f5804410890e5ac2b29858808a6

This is the issue: https://github.com/dart-lang/sdk/issues/28727

**Comment by mit-mit** [comment]
Closing, @whesse merged this in https://github.com/dart-lang/sdk/commit/d7cd0ae781bdc8af94cb94f177e6d6ee47f21344
