### ISSUE TITLE
running dart2js output gives "Uncaught TypeError: H.createRuntimeType is not a function"

### ISSUE THREAD

**Issue by andersonalex1** [dart-lang/sdk#28764]
[sf2.zip](https://github.com/dart-lang/sdk/files/772639/sf2.zip)

In this project, the example/sf2.html runs fine with Dartium, but after compiling to JS, Chrome shows this error: "Uncaught TypeError: H.createRuntimeType is not a function"

Steps:
- Unzip and load project in Intellij
- Expand example folder and debug the sf2.html in Dartium - it should load and play some sound
- Compile it to JS and open it in Chrome. It doesn't play, and checking the console in Chrome shows the above error.

Observations:
For a lighter version that still shows the problem, in sf2.dart, comment out "new SF2Tester()" and uncomment "new WebAudioTester();" In the WebAudioTester class (bottom of same file), I find that the problem doesn't happen if I comment out either the "if (AudioContext == null)..." block or the call to "_sfLoader.loadSoundFont()...". But neither of these calls alone causes the issue - they have to both exist for the error to happen. Also, I can put a return statement at the beginning of the loadSoundFont() method, and the problem still happens.

I'm seeing the same problem both in the current release as well as current dev (1.22.0-dev.10.6).

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.
