### ISSUE TITLE
Weird analyzer error 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28775]
ERROR: Evaluation of this constant expression throws an exception. 

![image](https://cloud.githubusercontent.com/assets/405837/22969224/fb07bfa8-f36d-11e6-9fe0-6fc6c0b6a008.png)

![image](https://cloud.githubusercontent.com/assets/405837/22969272/2a973cf8-f36e-11e6-9d6b-ebe966cd36fc.png)

```
Dart VM version: 1.23.0-edge.affb7865826160978c43a112b3da8c95cd22fb72 (Tue Feb 14 07:37:13 2017) on "linux_x64"
```

**Comment by bwilkerson** [comment]
Any idea how to reproduce this?

**Comment by zoechi** [comment]
@bwilkerson actually no. 
That's quite a complex project and it shows only in these two files, but there are a lot of similar files.

Also restarting the analysis server didn't change anything

A suspicion is that it might be related to #28780 where dart2js throws because it thinks it's not a valid constant expression.
This file is in the same directory ('lib/model')

**Comment by zoechi** [comment]
It's definitely caused by #28780. 

I published the project https://github.com/bwu-dart-playground/dartsdk_issue_28780/blob/master/lib/model/property_metadata.dart#L15

![image](https://cloud.githubusercontent.com/assets/405837/23157483/bd13c3a6-f81b-11e6-804a-17822d2d8956.png)

```
Dart VM version: 1.23.0-edge.bb72892e335f2ab69aeb0ef3dec5d7f150c80953 (Fri Feb 17 16:16:58 2017) on "linux_x64"
```
