### ISSUE TITLE
Merge fix for #28678 into 1.22

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#28776]
Commit: 67a93da99eb11ada7d8267243c6824d5c67de91c

@whesse

**Comment by fsc8000** [comment]
Add these commits (test status file updates): 031af9e89990d39ca73cfe8726ab018c038e8b7e and bbd687197bc96b4d7a0555d3f0cd0e1e64c2b672

**Comment by whesse** [comment]
This was merged in version 1.22.1.

**Comment by mit-mit** [comment]
This fixes https://github.com/dart-lang/sdk/issues/28678
