### ISSUE TITLE
JsonEncoder constructor documentation is outdated

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28772]
Please see https://api.dartlang.org/stable/1.21.1/dart-convert/JsonEncoder/JsonEncoder.html

> const JsonEncoder([
> dynamic toEncodable(
> nonSerializable
> )
> ])

`object` is better name for the `toEncodable` argument than `nonSerializable` (argument can be serializable)

> The JSON encoder handles numbers, strings, booleans, null, lists and maps directly.

It handles maps with a string keys only. Please update the documentation.

Issues from the above exist for JsonEncoder.withIndent() constructor as well (https://api.dartlang.org/stable/1.21.1/dart-convert/JsonEncoder/JsonEncoder.withIndent.html)

**Comment by kevmoo** [comment]
@sgrekhov Pull requests welcome! You can even edit the file in github and create a pull request, if you like.

**Comment by sgrekhov** [comment]
@kevmoo, please review https://github.com/dart-lang/sdk/pull/28787

**Comment by kevmoo** [comment]
Closed with https://github.com/dart-lang/sdk/commit/9afdbfdca0408c327e92c5ecebf6e382553f9ff0
