### ISSUE TITLE
Assert should accept a trailing comma.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28786]
I ran into this today trying to use trailing commas to make it consistent with the rest of a method:

```dart
assert(
  someExpression > 0,
  'A positive non-zero integer is required for $someExpression',
);
```

Regardless of whether this is good style or not, both the analyzer and dartfmt choked :-/

**Comment by lrhn** [comment]
Perhaps it should never have looked like a method call. Now it does, so maybe we should make it consistent with that.

**Comment by eernstg** [comment]
Note that the language _has_ been changed since this issue was closed, cf. issue #29959.
