### ISSUE TITLE
if/else promotion with FutureOr could be improved

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28783]
Currently if I write:

```dart
import 'dart:async';

Future<int> plus1(FutureOr<int> value) {
  if (value is Future<int>) {
    return value.then((n) => n + 1);
  } else {
    return new Future.value(value + 1);
  }
}
```

I get `[error] The operator '+' isn't defined for the class 'FutureOr<int>'` in the `else` clause. In principle, the analyzer has enough information to figure out that `value` is of type `int` in the `else` block, since it's either that or `Future<int>` and the former option has already been eliminated.

I expect that it isn't realistic to solve this until we start working on union types (#4938) more seriously, but I wanted to get it documented.

**Comment by leafpetersen** [comment]
+1

We discussed adding this, but held off for the initial feature.  @bwilkerson this would be a good thing to consider when you get cycles to follow up on the proposal for improved type promotion that you wrote up in the fall.

**Comment by bwilkerson** [comment]
Agreed. I'm basically waiting until the language team has time to consider it again.

**Comment by bwilkerson** [comment]
See also #28768.

**Comment by jmesserly** [comment]
moving to area-language for triage

**Comment by leafpetersen** [comment]
This is planned for the nnbd release, and is tracked [here](https://github.com/dart-lang/sdk/issues/40014).
