### ISSUE TITLE
Equivalent API to Java's Pattern.quote()

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28784]
We should provide an API method that takes a string and returns the string safe for inclusion in a `RegExp` (as a literal value).  This is the functional equivalent of Java's `Pattern.quote()` method -- http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#quote(java.lang.String)

**Proposal**

```
class RegExp {
  static String quote(String input);
}
```

**Comment by tvolkert** [comment]
`RegExp.escape(String)` would work as a name too.

**Comment by nex3** [comment]
Duplicate of #4706 :confused:.
