### ISSUE TITLE
vm/optimized_stacktrace_test very slow on kernel-debug build

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28788]
When running locally with --no-dfe (i.e. without the kernel isolate) it passes in < 20 seconds.

Log files show that the stacktraces are not the same every time…
Running it locally outside the test.py so it isn’t killed, I can attach observatory and see that it’s still going (in kernel-service.dart$main).

Finishes locally in less than 2 minutes (~1:15) if I remove "--optimization-counter-threshold=10" and "--stacktrace-every=3" from what's run.
Finishes locally in ~5 minutes if I remove "--stacktrace-every=3" from what's run.

It seems to me that in debug mode these things slow down the kernel isolate too much.

Will skip the test for now (https://codereview.chromium.org/2697283002/).

**Comment by nex3** [comment]
@fsc8000 I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.
