### ISSUE TITLE
Supply a cross-platform way of launching a browser

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#28781]
Something like https://docs.python.org/2/library/webbrowser.html

**Comment by matanlurey** [comment]
Why wouldn't this go in something like `package:web_browser`, similar to python?

**Comment by xster** [comment]
Oh, that makes sense

**Comment by zoechi** [comment]
The test package seems to do that already. Might be helpful to look up the code there and pack it into a new  package.

**Comment by srawlins** [comment]
This is still not functionality that needs to be implemented in the SDK itself. Someone can write a package to do this.

**Comment by lrhn** [comment]
As @srawlins said, not something we plan to handle in the SDK.
