### ISSUE TITLE
custom/document_register_template_test has timed out a lot lately on IE10

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28792]
Has timed out 5 out of last 41 builds on dart2js-win7-ie10chrome-1-4-be.

For now, trying to mark as slow.

**Comment by nex3** [comment]
@alan-knight I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by whesse** [comment]
IE10 support is dropped - browser has been EOL for more than a year.
