### ISSUE TITLE
Remove support for @checked once code has been migrated to use covariant

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28797]
Once major code bases (e.g. Flutter) have migrated to `covariant` from `@checked`, we should deprecate and then remove support for `@checked`.

cc @sethladd

**Comment by a14n** [comment]
Flutter has migrated via flutter/flutter#8300

**Comment by leafpetersen** [comment]
I think this can now be done at any point that is convenient.

**Comment by zoechi** [comment]
dart2js doesn't seem to support `covariant` yet

**Comment by leafpetersen** [comment]
@zoechi can you elaborate?  It was marked as implemented here: https://github.com/dart-lang/sdk/issues/28165 , so if there's something missing we should follow up on it.  Note though that dart2js just implements the Dart 1.0 semantics, which is just to ignore it (since Dart 1.0 functions are covariant already).
