### ISSUE TITLE
analysis.getNavigation will return non-empty results for whitespace locations

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28799]
This was caught by a (yet-to-be-committed) integration test. Will update once that lands.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/integration/analysis/get_navigation_test.dart#L44

**Comment by DanTup** [comment]
I removed the `@failingTest` annotation on the test here as it was fixed along with a related issue I found while testing LSP (invoking Go-to-Def on a comment would navigate to a definition for a reference elsewhere in the same comment).
