### ISSUE TITLE
Support python3 in our various build and test scripts

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28793]
We use Python for a bunch of our internal tools and automation. I believe many of them currently don't work under Python 3. That makes it harder for external users that don't have Python 2.7 installed to get up and running.

We should probably get those scripts working under both 2 and 3, deprecate them if they aren't needed anymore, or rewrite them in Dart where appropriate.

**Comment by eseidelGoogle** [comment]
I thought python 2 and 3 were mutually exclusive?  There is a conversion tool, but I think once you've converted you can't go back. :)
https://wiki.python.org/moin/Python2orPython3

**Comment by jcollins-g** [comment]
It's possible to write Python code that runs in both, but the TL;DR is that
it is annoying to do so.  This is a somewhat out of date guide but will
give you the general idea:

http://python-future.org/compatible_idioms.html

If we decide to do it, making our Python tooling work in both will be an
exercise in in using and/or finding compatible idioms along these lines.

Janice

**Comment by DanTup** [comment]
I don't know how much more effort (if any) it'd be to rewrite in Dart over making work in both Pythons, but that would not only eliminate another dependency but it's also good dog-fooding (or "putting your money where your mouth is"). Most people wanting to hack on Dart are going to have an SDK already whereas Python might not be available (for ex., most Windows users trying out Dart probably don't have either Python).

**Comment by srawlins** [comment]
CC @athomas @whesse Python 2 is EOL in < 2 months, on Jan 1, 2020. https://pythonclock.org/

**Comment by SchoolGuy** [comment]
So just a ping from my side as I am packaging in openSUSE if I have time. If we get this Py3 I could try to build an openSUSE/Fedora/CentOS/... Specfile to make Dart available on these distributions if legal is fine with it. But since no Py2 packages are accepted to openSUSE Leap and Tumbleweed Dart will not be available there...

**Comment by natebosch** [comment]
I made some changes in my dev setup and hit this again - python2 has not been maintained for over a year now and we shouldn't be asking authors to install it to contribute to the SDK.

Do we have a timeline for this?

**Comment by jubalh** [comment]
> So just a ping from my side as I am packaging in openSUSE if I have time. If we get this Py3 I could try to build an openSUSE/Fedora/CentOS/... Specfile to make Dart available on these distributions if legal is fine with it. But since no Py2 packages are accepted to openSUSE Leap and Tumbleweed Dart will not be available there...

Actually I wanted to do this > 1 year ago.
Today came here to check whether the scripts have already been ported to Python3 because I wanted to create a dart package again :-)

Would be interesting if someone is working on it right now and how many scripts are actually affected.

**Comment by jubalh** [comment]
```
find . -name '*.py' | wc -l
140
```

So would a PR which converts all of these to Python3 be accepted?

**Comment by athomas** [comment]
@jubalh Yes, certainly. Feel free to tag me in the PR.

We could rewrite some things in Dart, because of the checked-in SDK, we always have a working Dart SDK available after a `gclient sync` but we should be careful not to slow down the build by doing that (some of the python scripts are tiny utilities used by the GN build files).

**Comment by a-siva** [comment]
//cc @a-siva

**Comment by athomas** [comment]
There's a CL in review now. I don't expect it to land before April.

https://dart-review.googlesource.com/c/sdk/+/192182

**Comment by SchoolGuy** [comment]
To anyone who is related to the dart project on this issue: Is it of interest if I would create RPMs (and everything related to that) for Dart (and when done Flutter) from the stable releases? If noone is interested I would drop that effort (because it is huge to automate all everything or to manually keep track of everything).

**Comment by athomas** [comment]
It could be interesting. Currently we sign our packages with internal tooling, but if we land support to build the packages externally we might be able to integrate this with our internal tooling to actually produce the signed packages when we do releases. I can't speak for the Flutter side, I see the currently offer snap packages.

I'd prefer if we continue this discussion on a separate issue (feel free to mention me in the issue). If you could give me an outline of what you'd like to do we can see if we can reconcile that with our release process and avoid you doing work that will result in wasted efforts.

**Comment by jubalh** [comment]
>  If noone is interested I would drop that effort (because it is huge to automate all everything or to manually keep track of everything).

I'm not sure why you think you are alone in this. As mentioned in https://github.com/dart-lang/sdk/issues/28793#issuecomment-790744625 I plan to do this since a long time.
Also I requested the creation of the devel project devel:languages:dart in OBS several months ago.

**Comment by jubalh** [comment]
@athomas just a reminder that after all the python2 things are gone the build instructions in the wiki might need updating: https://github.com/dart-lang/sdk/wiki/Building
