### ISSUE TITLE
Implement local class hierarchy analysis for DDC

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28801]
Implement module-level class hierarchy analysis for DDC

We can use this to determine which private and non-escaping public fields can be safely devirtualized.

**Comment by vsmenon** [comment]
Note, this should go ahead and assume #28809 is in effect.

**Comment by kasperl** [comment]
Any progress on this?

**Comment by jmesserly** [comment]
> Any progress on this?

Nope. I was pulled into strong mode work and haven't gotten to look at this yet. I'll try and start it today.

**Comment by dgrove** [comment]
any update here?

**Comment by jmesserly** [comment]
update: just landed a chance that got DDC's build green (https://github.com/dart-lang/sdk/commit/132ddcaacfa4f47df0e7656b6648cf5a11e181ba), plus a couple of other CL's needed for rolling our inference changes into internal code (https://github.com/dart-lang/sdk/commit/f3f814b89976510e5b4a3c5e39679c46a781e546, https://github.com/dart-lang/sdk/commit/4f9fff9ebd6f22051e438f33b3585e25bb91ccd5). So now I can focus on this one.

**Comment by jmesserly** [comment]
The great irony of this bug is I had it implemented almost 2 years ago ;)
https://codereview.chromium.org/1090313002/
https://github.com/dart-archive/dev_compiler/issues/52#issuecomment-94581196

probably that CL is wayyyyy too obsolete to be relevant now! Anyway I hope this one won't take very long.

**Comment by jmesserly** [comment]
update: I'm getting really close on this one. Nearly finished implementation & shifting to testing it soon.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2781443003/
