### ISSUE TITLE
deprecate execution.setSubscriptions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28806]
I see this exception:

```
Bad state: Should not be used with the new analysis driver, stackTrace:
  #0      ContextManagerImpl.folderMap (package:analysis_server/src/context_manager.dart:561:7)
  #1      ContextManagerImpl.analysisContexts (package:analysis_server/src/context_manager.dart:557:53)
  #2      AnalysisServer.analysisContexts (package:analysis_server/src/analysis_server.dart:434:22)
  #3      ExecutionDomainHandler._reportCurrentFileStatus (package:analysis_server/src/domain_execution.dart:218:44)
  #4      ExecutionDomainHandler.setSubscriptions (package:analysis_server/src/domain_execution.dart:167:9)
```

**Comment by devoncarew** [comment]
IntelliJ, atom, and vscode don't use this server request. The only client I can find that uses it is the older Eclipse client. One option here - if implementation is not straightforward - it to deprecate the API call and change the implementation into a no-op.

@scheglov @bwilkerson

**Comment by scheglov** [comment]
My vote is to remove it altogether.
It does not have clients, and any service that requires analysis of all files is expensive.

**Comment by bwilkerson** [comment]
I would prefer to deprecate it. Removing it is a breaking change and I'd like to minimize the number of breaking change versions of the server protocol.

**Comment by devoncarew** [comment]
I re-purposed this issue to one for deprecating `execution.setSubscriptions`.

**Comment by devoncarew** [comment]
(done)
