### ISSUE TITLE
IntelliJ (Analyzer?): Dartdoc [Class.method] not recognized

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28819]
Reproduction case:

```dart
/// Type signature for [BuildContext.visitChildren].
typedef void ElementVisitor(Element element);

abstract class BuildContext {
  void visitChildren(ElementVisitor visitor);
}
```

Only `BuildContext` is highlighted as recognized as a symbol in the dartdoc but:

1. I can't control-click through to it
2. `.visitChildren` is not highlighted
3. Strangely enough, `comment_references` lint recognizes it is valid
4. On https://docs.flutter.io/flutter/widgets/ElementVisitor.html, it *is* recognized

<img width="479" alt="screen shot 2017-02-17 at 9 07 17 am" src="https://cloud.githubusercontent.com/assets/168174/23075235/84651920-f4f0-11e6-96f7-637175973028.png">

**Comment by devoncarew** [comment]
I believe the library defining ElementVisitor does not import `framework.dart` (the library defining BuildContext). The analyzer is doing the right thing here. Dartdoc has a special mode when generating flutter docs to try and locate references that were not imported (that aren't in scope), but that are uniquely identifiable in the context of the other things we're documenting at the time.

**Comment by zoechi** [comment]
Wouldn't `visitChildElements` need to be static for this to work?
I'd expect a different syntax to be required for that (or the samantics for the existing changed in doc comments)

**Comment by bwilkerson** [comment]
From the perspective of the tools, it doesn't matter whether it's an instance or static member. From the perspective of the user, it's convenient to not require a different syntax. Therefore, it seems reasonable to me for the tools to permit either.

**Comment by srawlins** [comment]
We've reworked comment reference resolution at least twice recently. Closing as stale; please re-open if you can still reproduce.
