### ISSUE TITLE
remove bin/snapshots/utils_wrapper.dart.snapshot from the sdk

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28818]
We're shipping utils_wrapper.dart.snapshot in the sdk, but it's not called by any of the scripts in bin/ and is not user facing; removing it would save 4MB.

It's still referenced from tools/testing/dart/test_suite.dart and test_runner.dart, but is likely a no-longer-needed artifact from when dart2js and dartdoc tried some snapshot sharing.

**Comment by joshualitt** [comment]
This file appears to be gone now.
