### ISSUE TITLE
Analyzer: Built-in identifier as prefix is not detected as a compile-time error.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28813]
This is the analyzer specific sub-issue for #28811, which has the details.

The test `built_in_identifier_prefix_test.dart` implies that built-in identifiers should be accepted as the declared names of library prefixes, which is not the case.

The test should be adjusted accordingly, and the analyzer should detect and flag such prefix names as compile-time errors.

Cf. the spec change (#28817), usages as in #28811 should also be flagged as compile-time errors (it is not just a malformed type).

**Comment by eernstg** [comment]
In [this CL](https://dart-review.googlesource.com/c/sdk/+/21080), `built_in_identifier_prefix_test.dart` has been split into several tests, and the new tests contain updated expectations.

There are still some issues: `dynamic<int>` is accepted, `typedef Function() x = null;` causes a crash, `operator Function() x = null;` is not a compile-time error (even though it uses a built-in identifier in a type annotation), and 19 other issues (marked as Issue 28813 in the status file).

**Comment by natebosch** [comment]
I get a bunch of `build_in_identifier_as_prefix_name` when I try - @scheglov is this done?

**Comment by srawlins** [comment]
Yes, I think these have all been handled now.
