### ISSUE TITLE
dartdevc: Built-in identifier as prefix is not detected as a compile-time error.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28816]
This is the dartdevc specific sub-issue for #28811, which has the details.

Presumably, fixing the analyzer as per #28813 will take care of this.

**Comment by eernstg** [comment]
In [this CL](https://dart-review.googlesource.com/c/sdk/+/21080), `built_in_identifier_prefix_test.dart` has been split into several tests, and the new tests contain updated expectations.

There is still one issue: `dynamic<int>` is accepted, but I've shaped the test such that it is considered to be a compile-time error in strong mode. Please get in touch if you think it should not be an error.

**Comment by jmesserly** [comment]
yeah, the analyzer fix (#28813) will take care of this. DDC relies on its front ends (Analyzer/CFE) to produce compile time errors
