### ISSUE TITLE
Incorrect placement of Labeled Statement in tested loops

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#28825]
Consider the following code (borrowed from a Dart test):

     L0:
      while (index++ != 2)
      {
        while (true) {
          var e = getNonInt();
          Expect.equals(42, e + 2);
          if (e != null) continue L0;
          while (true) use(e);
        }
      }

If you run dartk.dart on this, you get the following output:

     while (!(let final dynamic #t1 = index in let final dynamic #t2 = index = #t1.+(1) in #t1).==(2))
          #L1:
          {
            while (true) {
              dynamic e = foo::getNonInt();
              exp::Expect::equals(42, e.+(2));
              if(!e.==(null))
                break #L1;
              while (true)
                foo::use(e);
            }
          }

I believe this is incorrect, as this puts the label as the first statement *in* the while statement with its target as the Block, whereas in in the original the target of the label is the while statement itself.

**Comment by kmillikin** [comment]
The Kernel language doesn't have continue (in loops, it does have continue in switch statements).  Continue to a loop is desugared into a break from the loop's body.

I think this is working as intended.

**Comment by efortuna** [comment]
I walked over this with Stephen to verify the error. This has nothing to do with whether it's a continue or a break (continue #label and break #label are simply goto statements). 

In the old version, when you "goto" label L0, the condition portion of the while loop then gets evaluated again, which in this case also increments `index`. This is necessary because `index` is updated exclusively in that condition statement. If instead you GOTO #L1 in the kernel version, index never gets updated and this loop can never terminate. 

(I admit this is terrible code, but we should be able to handle it, especially since we were able to handle it before. This is testInNestedWhileLoop2 in the dart2js_extra/bailout_on_continue_test.dart)

**Comment by kmillikin** [comment]
kernel doesn't provide unrestricted goto --- it just has break which is a jump out of an enclosing statement.

You can view `break #L1` as a goto to the end (not the beginning) of the statement labeled L1.  The semantics of Kernel should be such that that is the end of the loop body in the example, and the end of a while loop body should be followed by reevaluating the condition.

**Comment by efortuna** [comment]
got it. I'll investigate how we can deal with this case in kernel then.
