### ISSUE TITLE
support patching in fasta

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28822]
(this is already in progress, just filing a bug to be able to refer to it from a TODO in our code)

Fasta currently depends on a `patched_sdk`, it needs to be able to do patching directly. This will eliminate the need of building this extra folder in our build bots and benchmark builders.

**Comment by sigmundch** [comment]
/cc @keertip who wants to follow along for bazel integration.

@peter-ahe-google - just to know where we are at: I believe this is working now for vm_platform.dill, and you plan to add next vm_platform_strong and afterwards the dart2js_platform.dill file, correct?

**Comment by keertip** [comment]
Currently we are generating the non strong vm_platform.dill. We need this done to make the switch over to generating strong mode platform.dill

**Comment by keertip** [comment]
@kmillikin

**Comment by efortuna** [comment]
this affects dart2js in that I believe it is needed for my work in getting dart2js+kernel building correctly in google3 (dart2js_platform.dill)

**Comment by peter-ahe-google** [comment]
I assume that the dart2js team will take care of moving away from `patched_sdk` and let me know if they encountered any issues.

**Comment by mraleph** [comment]
Is somebody working on moving vm strong platform away from using patched_sdk?

@keertip do I understand correctly that this is blocking internal testing of VM Dart 2.0 configuration?

**Comment by keertip** [comment]
Slava, yes, that is correct. Currently I am running the VM+FE internally with the non strong vm platform.

**Comment by sigmundch** [comment]
I've started working on getting the dart2js patching to work

@peter-ahe-google I have assumed you have in your pipeline to do the vm-strong, correct?

**Comment by sigmundch** [comment]
quick update: dart2js support landed, so I'm removing customer-dart2js now. We do need to get support for the vm-strong to get bazel unblocked on that.

**Comment by keertip** [comment]
This is blocking testing the vm in strong mode internally.

**Comment by kmillikin** [comment]
I'll take this one in order to get it fixed as soon as possible.

**Comment by kmillikin** [comment]
Issue #31974 has more details.

**Comment by peter-ahe-google** [comment]
Proposed fix [change 36641](https://dart-review.googlesource.com/c/sdk/+/36641).

**Comment by keertip** [comment]
@peter-ahe-google  thanks for the timely fix! 

With commit [71dba8a0](https://github.com/dart-lang/sdk/commit/71dba8a0e5a1903090110fd462c35d652bbea1e8) the VM build requires both the legacy and strong platform dill files. This is(would have been) a blocker for internal  rolls.
