### ISSUE TITLE
bug: unnecessary warning on covariant field/setter override

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28821]
This program:

```dart
abstract class A {
  num get x;
  set x(covariant num _);
}

class B extends A {
  int x;
}
```

Produces this error in strong mode:
```
[error] Invalid override. The type of 'B.x=' ('(int) → void') isn't a subtype of 'A.x=' ('(dynamic) → void'). (x.dart, line 7, col 3)
```

The base setter is already marked as covariant, so the error seems unnecessary. Switching to a setter/getter pair in the child class (with no covariant marker) or adding a covariant marker to the field works around this error.

**Comment by peter-ahe-google** [comment]
If the P1 tag was added due to CL 2698213003, then I want you to know that it's no longer a problem for us.

**Comment by bwilkerson** [comment]
Test added in https://codereview.chromium.org/2707263005/

**Comment by scheglov** [comment]
https://codereview.chromium.org/2757143002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/a94f43334a900905292d8f31123db2a97dcdf490
