### ISSUE TITLE
Add handleNoVariableInitializer

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28833]
`Parser.parseVariableInitializerOpt` should generate an event like:

`handleNoVariableInitializer`

This way we can stop relying on type tests in `endInitializedIdentifier`.

See discussion in [CL 2699423002](https://codereview.chromium.org/2699423002/diff/1/pkg/front_end/lib/src/fasta/analyzer/ast_builder.dart#newcode316).

**Comment by jensjoha** [comment]
`handleNoVariableInitializer` seems to have been added - can we close this issue?
