### ISSUE TITLE
DartAnalyzer doesn't terminate for Object extends Object under some conditions

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#28837]
```
$ dartanalyzer --version
dartanalyzer version 1.22.0
```

```$ dartanalyzer test.dart``` doesn't terminate for:

```
class Object extends Object { }

class A extends Object { }

class B extends A implements D {
  static E() { }
}
```

**Comment by lukechurch** [comment]
I'm requesting that this bug be treated as a priority. If it doesn't occur in others usages of the tooling, such as Analysis server, please reprioritise accordingly.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2708773002/
