### ISSUE TITLE
Duplicate @required quick fixes.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#28830]
Test source:

```
void foo({@required int x, @required int y}) {

}

x () {
  foo();
}
```

<img width="576" alt="screen shot 2017-02-19 at 11 02 19 am" src="https://cloud.githubusercontent.com/assets/67586/23105365/fe63bb52-f692-11e6-9e50-2d755ee6d92d.png">

Also, consider pluralizing if there are more than one?

See: https://github.com/flutter/flutter-intellij/issues/553

**Comment by pq** [comment]
OK, it looks like this is because there are two errors.

<img width="814" alt="screen shot 2017-02-19 at 11 17 18 am" src="https://cloud.githubusercontent.com/assets/67586/23105500/3150fa50-f695-11e6-9130-185afcc4101b.png">

(And each is proposing a fix.)

**Comment by pq** [comment]
cc @scheglov  @bwilkerson for thoughts

**Comment by bwilkerson** [comment]
We should fix it so that there is a single error produced per invocation. To make the message nice we'll probably need to do something like we do for "missing implementation" messages (I think we have 5 messages there).

**Comment by pq** [comment]
👍 

As a point of reference, here's how that looks:

<img width="459" alt="screen shot 2017-02-19 at 1 35 26 pm" src="https://cloud.githubusercontent.com/assets/67586/23106830/4f220534-f6a8-11e6-9b98-2fcbb980d67a.png">


Following that lead we could replace the message with something like:

    Missing required parameters `x` and `y`.

**Comment by pq** [comment]
After a bit of exploration and conversation, the plan is to keep this one error per missing param (so that we don't lose details).  We'll cycle back and consider improving the UX down the road when other bits to support `@reqiured` are in place (e.g., better code gen for code completion).

**Comment by scheglov** [comment]
One possible solution could be to generate one error per missing param, but the first one with a different error code, and use it as a marker/activator to generate one quick fix for every missing argument.

**Comment by pq** [comment]
👍  I like that idea.  I'll slate that for a follow-up.

**Comment by pq** [comment]
Here's where we are (before @scheglov's refinement in a future change).

![grab](https://cloud.githubusercontent.com/assets/67586/23191518/ef97036a-f852-11e6-9fb9-4f7efcdf47fc.png)

![screen shot 2017-02-21 at 4 26 16 pm](https://cloud.githubusercontent.com/assets/67586/23191525/f29b6394-f852-11e6-9298-500411afd241.png)
