### ISSUE TITLE
add a quick assist to convert slash star dartdoc comments to slash slash comments

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28840]
So, for `/** ... */` dartdoc comments, the quick fix would offer to convert to `/// ...`.

**Comment by zoechi** [comment]
Should that do line breaking as well? With `/// ` there is one char less space for comment text than with ` * `.

**Comment by bwilkerson** [comment]
It would be harder to do, given that some line breaks are significant, so I wouldn't bother. It would be nice, though, to have a formatter (possibly as part of dart_style) that would format doc comments.

**Comment by zoechi** [comment]
> possibly as part of dart_style
rather unlikely dart-lang/dart_style#430

**Comment by bwilkerson** [comment]
Sigh. I know, but it seems useful to be able to format comments, and foolish to have two formatting tools.

**Comment by bwilkerson** [comment]
And for the record, in case anyone wants to address this, from an implementation perspective this would be a quick assist, not a fix. (It changes where the implementation lives in server.)

**Comment by bwilkerson** [comment]
This functionality now exists (and might have existed when the issue was created).
