### ISSUE TITLE
fasta: redirecting factories are not resolved across platform.dill border

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28859]
```dart
main() {
  new Map();
}
```

compiles down to 

```
  static method main() → dynamic {
    core::Map::•<dynamic, dynamic>();
  }
```

However it should actually compile down to an invocation of the `LinkedHashMap` constructor to which the `Map` redirects to.

This most likely happens because `RedirectingFactoryBody` does not actually survive serialization/deserialization when `platform.dill` is generated.

**Comment by peter-ahe-google** [comment]
Good point, I'm pretty sure I know what the problem is.
