### ISSUE TITLE
String interpolation fails on object that is not String and toString() returns null

### ISSUE THREAD

**Issue by ranquild** [dart-lang/sdk#28856]
Title explains issue. Minimal reproduce:

```
class Text {
  @override
  String toString() => null;
}

void main() {
  Text text = new Text();
  String string = '${text}';
}
```

https://dartpad.dartlang.org/bf550031d53b43c11c2355032f1d2003

**Comment by kmillikin** [comment]
It does what the spec says it should:

> An interpolated string ‘s1${e}s2’ is equivalent to the concatenation of the strings ‘s1’, e.toString()
and ‘s2’.

In this case, `s1` and `s2` are empty strings and the expression should be the same as `'' + text.toString() + ''` which throws.  (You might argue that it isn't equivalent because it doesn't throw the same thing.)

The spec does say that e.toString() is a string, but I think that's a spec bug (issue #25853).

**Comment by lrhn** [comment]
Kevin is correct. The spec has been made more explicit about the interpolation, but the conclusion is still the same - if the call to `toString` doesn't return a *string*, the interpolation expression throws.

You could call `toString` again on the returned object, but when do you stop?
```dart
class FooledYou {
  dynamic toString() => this;
}
main() {
  var f = new FooledYou();
  var y = "<$f>";  // infinite recursion - or just throw immediately?
}
```
We opted for throwing immediately. If your `toString` returns a non-string, something is *wrong*. Trying to "fix" that in any way is likely to just hide the wrongness, not expose it, so this is failing early.

(If we get non-nullable types, expect `toString` to have a non-nullable return type!)

**Comment by kmillikin** [comment]
You can change Text.toString to return null.toString() (if that was your intent).
