### ISSUE TITLE
Fasta tokens should implement precedingComment feature.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#28850]
As discussed here: https://codereview.chromium.org/2686363002/diff/1/pkg/front_end/lib/src/fasta/analyzer/token_utils.dart#newcode53

Rather than including comments in the token stream (which complicates parsing), Fasta's token stream should omit comments, but when comment tokenization is enabled, `Token` should support a `precedingComment` getter which makes it possible to navigate from a non-comment token to the comments that precede it.

**Comment by danrubel** [comment]
https://codereview.chromium.org/2731863002/
