### ISSUE TITLE
VM crash in `RandomAccessFile.truncateSync` on Windows

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28852]
https://gist.github.com/tvolkert/1a1a566423c1623371174b17e55fdc39

If you run that test on Windows, the VM crashes. On other platforms, you get a `FileSystemException` with an `EINVAL` errno.

@zanderso

**Comment by tvolkert** [comment]
FYI @goderbauer

**Comment by zanderso** [comment]
Looks like we're missing a call to `_set_invalid_parameter_handler`

https://msdn.microsoft.com/en-us/library/a9yf33zb.aspx
