### ISSUE TITLE
Strong mode top level inference regression

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28862]
The test code below passes the dart analyzer in strong mode with no errors in version 1.23.0-dev.0.0 .  In version 1.23.0-dev.1.0, the field `m` fails to be inferred as `MyList<int>`, and a downcast composite is reported on the assignment in main.

```dart
class MyList<T> {
  final List<T> _list;
  MyList(List<T> list) : _list = list;
}

class Test {
  final m = new MyList([0]);
}

void main() {
  Test test;
  MyList<int> list = test.m;
}
```

**Comment by leafpetersen** [comment]
cc @scheglov @stereotype441 

I see some commits in the range between those two tags related to turning off the task model which make me wonder if we switched over to a different implementation of top level inference?

**Comment by scheglov** [comment]
Yes, `analyzer_cli` was switched to using the new analysis driver, which uses summary based type inference.

**Comment by leafpetersen** [comment]
I see this in Intellij pointed at bleeding edge as well, so presumably also there?

**Comment by scheglov** [comment]
Yes, Analysis Server was switched to using the new analysis driver since the very beginning of `1.23`.

**Comment by bwilkerson** [comment]
@scheglov Is this a result of replacing the task model? If so, do you know what step(s) are missing in the new code?

**Comment by scheglov** [comment]
Inference for instantiation was not implemented in linker.
I'm working on this now.

**Comment by scheglov** [comment]
Fix for processing `invokeConstructor`.
https://codereview.chromium.org/2711733003

**Comment by scheglov** [comment]
Fix for constructors with field formal parameters.
https://codereview.chromium.org/2710943007

**Comment by scheglov** [comment]
I think this is fixed now.
https://github.com/dart-lang/sdk/commit/02da0fb1dda0a04f78e211c77c96ee1581c6a907

**Comment by leafpetersen** [comment]
Great, thanks!
