### ISSUE TITLE
NoAnalysisErrorsIntegrationTest.test_detect_simple_error() fails with the new driver

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28869]
With the new analysis driver, this integration test fails:

```
analysis_server_integration | analysis | NoAnalysisErrorsIntegrationTest | test_detect_simple_error
  Expected: null
    Actual: [
    AnalysisError:{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/private/var/folders/00/0w978000h01000cxqpysvccm003j4x/T/analysisServerIkbPk6/test.dart","offset":21,"length":1,"startLine":2,"startColumn":13},"message":"Expected to find ';'.","correction":"","code":"expected_token","hasFix":true}
  ]
```

What is the use case for disabling error notification (`noErrorNotification: true` / `--no-error-notification`) with the analysis server? If the use case is not longer relevant, we can turn the cli flag into a no-op.

**Comment by bwilkerson** [comment]
The only use case that I'm aware of was to support an earlier version of the IntelliJ plugin (before we had the analysis view), but I believe that they have now stopped using this API.

**Comment by bwilkerson** [comment]
However, removing support would be a breaking change to the server API, and I don't think we should tackle that until a few more large changes to the analyzer / server code bases have been made.

**Comment by devoncarew** [comment]
I suspect this option is only available through the cli (`--no-error-notification`)? If so, we should be able to get some certainty into whether it is or is not used by active clients.

**Comment by bwilkerson** [comment]
Yes, it is only available at start up via a command-line argument.

**Comment by devoncarew** [comment]
fixed in https://codereview.chromium.org/2713053002/
