### ISSUE TITLE
dart/runtime/observatory:pub_build_observatory fails if HTTP proxy is configured

### ISSUE THREAD

**Issue by jamesr** [dart-lang/sdk#28865]
https://github.com/dart-lang/sdk/blob/master/runtime/observatory/BUILD.gn#L121 calls out to pub to build part of the observatory, which apparently includes some source transformers.  These transformers fail to load if an http proxy is configured on the system, even though they are loading off of the filesystem.  Example (from a fuchsia build):
```
$ env http_proxy=http://example.com:9999/ ../../dart/tools/observatory_tool.py --sdk=True --dart-executable host_x64/dart_bootstrap --directory gen/observatory_copy/dart/runtime/observatory/ --command build observatory/build


WARNING: Your system cannot run the checked-in Dart SDK. Using the
bootstrap Dart executable will make debug builds slow.
Please see the Wiki for instructions on replacing the checked-in Dart SDK.

https://github.com/dart-lang/sdk/wiki/The-checked-in-SDK-in-tools

To use the dart_bootstrap binary please update the PubCommand function
in the tools/observatory_tool.py script.


Running command "['/ssd/fuchsia/out/debug-x86-64/host_x64/dart_bootstrap', '/ssd/fuchsia/dart/third_party/pkg/pub/bin/pub.dart', 'build', '-DOBS_VER=1.23.0-edge', '--output', '/ssd/fuchsia/out/debug-x86-64/observatory/build']"
Command failed: /ssd/fuchsia/out/debug-x86-64/host_x64/dart_bootstrap /ssd/fuchsia/dart/third_party/pkg/pub/bin/pub.dart build -DOBS_VER=1.23.0-edge --output /ssd/fuchsia/out/debug-x86-64/observatory/build
output: Warning: the revision of pub in DEPS is 53327f4a7ca2ddd20a40f6a94db61ac136371b03,
but 9000daf329445d06e2404d4bb9020cf742b7308a is checked out in ../../../../../../../dart/third_party/pkg/pub.

Loading source assets...
Loading dart_to_js_script_rewriter, initialize/build/loader_replacer, initialize, observe, smoke/src/default_transformer, web_components/build/mirrors_remover and web_components transformers...
Transformer library "package:initialize/transformer.dart" not found.
```

This has proven extremely confusing for several Fuchsia developers.  It can be worked around by setting 'no_proxy' in the environment before running this step.  The package in question exists on disk and is referred to in the .packages file by a 'file:///' URL, so something must be broken about the transformer library loading.

/cc @johnmccutchan @a-siva

**Comment by johnmccutchan** [comment]
@nex3 @munificent is this a known issue with pub build?

**Comment by anders-sandholm** [comment]
The combination of proxy settings and Pub is fragile.
How can we give Pub users a better experience in this context?

**Comment by nex3** [comment]
It's not so much pub that's fragile as the `dart:io` APIs it uses. If we made those APIs proxy-aware somehow (I'm not sure what the standard is there), it would help all Dart applications that deal with networking.

**Comment by jamesr** [comment]
Why are proxy settings meaningful when doing a pub build involving a .packages file with only file:// URLs?

**Comment by nex3** [comment]
Transformers use HTTP to load transformed Dart code into isolates.

**Comment by jamesr** [comment]
You mean it runs an HTTP server bound to localhost to load up the files from disk?  Why?

**Comment by nex3** [comment]
Because those files may be transformed by transformers, and the Dart VM needs to load the output of those transformations.

**Comment by jamesr** [comment]
OK, so an HTTP server is used as a cross-platform streaming transport mechanism for the possibly-transformed output.

Stepping back, it seems that attempting to have fuchsia developers build the observatory is not a good idea.  Do we have another way for developers working on fuchsia and building the Dart VM to get a usable observatory?  @zanderso @johnmccutchan

**Comment by matanlurey** [comment]
Just to clarify - `pub build` is only used for building web applications, right?

Are you trying to build a web application @jamesr?

**Comment by jamesr** [comment]
Not directly - we're building the Dart VM.  Part of that build is building the observatory, which is a web application.  We want to end up with an observatory in some fashion, as we'd like to debug Dart applications, and (at least to some extent) the observatory can change along with the VM.  In practice, changes to the Dart VM that are relevant to our developers are far more common than changes to the observatory UI.

**Comment by matanlurey** [comment]
OK, got it. It seems to me we should be able to entirely disable any concept of pub server/transformers for these types of builds - ping me internally if you'd like and I can chat more.

**Comment by jamesr** [comment]
Since the observatory uses dart2js, which I believe is a pub transform, I don't think that would work out for us.  I'd be happy to be mistaken about this.

**Comment by johnmccutchan** [comment]
A simple fix would be for the Observatory build step to temporarily clear any HTTP_PROXY environment variable before invoking pub build.

**Comment by johnmccutchan** [comment]
Invoke pub without HTTP_PROXY: https://codereview.chromium.org/2724483003/

**Comment by jamesr** [comment]
Thank you!
