### ISSUE TITLE
remove unused --build-mode flags?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28867]
I don't see any use of the following build-mode flags (for the dartanalyzer tool):

```
    --build-summary-only-diet              Diet parse function bodies.
    --build-summary-output                 Specifies the path to the file where the full summary information should be written.
```

Are these important to keep, or an artifact of previous use cases? `--build-mode` is not user facing so these should be low risk to remove.

@stereotype441

**Comment by stereotype441** [comment]
Yes, I believe is it safe to remove these.

**Comment by natebosch** [comment]
`build-summary-only-diet` is removed
`build-summary-output` is still there and I think can be removed

**Comment by srawlins** [comment]
`dartanalyzer` is deprecated and `dart analyze` does not support these flags.
