### ISSUE TITLE
Add information about --trust-primitives --trust-type-annotations flags to dart2js

### ISSUE THREAD

**Issue by ranquild** [dart-lang/sdk#28886]
Currently those flags are not listed on site or with `dart2js -h -v`, but they enable generation of much better javascript. Those flags are game changers actually, it would be very helpful to get detailed information about those flags in documentation and/or in dart2js help output.

**Comment by sigmundch** [comment]
fixed in https://github.com/dart-lang/sdk/commit/d60fe4de18ad66cde11d5bcc31f520b1262d7ea5
