### ISSUE TITLE
IntelliJ/WebStorm should forward PUB_ENVIRONMENT on to pub when invoked

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28893]
When calling pub, intelliJ should set an environment variable PUB_ENVIRONMENT=IntelliJ_IDEA (or similar. Same as --client-id passed to AS)

If the PUB_ENVIRONMENT is set in the Jetbrains process, it should be included when calling pub, using a colon as a separator.

PUB_ENVIRONMENT=existing_var:IntelliJ_IDEA

**Comment by devoncarew** [comment]
> If the PUB_ENVIRONMENT is set in the Jetbrains process, it should be included when calling pub, using a colon as a separator.

When would this happen?

**Comment by devoncarew** [comment]
(just not clear on the use case for that second part)

**Comment by kevmoo** [comment]
If the plugin is run in a test harness of sorts, will help us understand the usage is not a "normal user"

**Comment by devoncarew** [comment]
fixed in https://github.com/JetBrains/intellij-plugins/pull/487
