### ISSUE TITLE
Dart in the browser completely broken and unusable, both Dartium and Dazel

### ISSUE THREAD

**Issue by Meai1** [dart-lang/sdk#28897]
I don't know whether nobody uses dart(ium) or my computer is haunted by voodoo magic?

**Reproduction:** 
Type: `querySelector("anything")` into the dartium console.
I attached a code sample too but you should get this error literally just by writing querySelector("anything") into the dartium console. But if you use the code sample, if you get any error other than what I posted in this issue it's probably an error in the code sample, just disregard it.
[test.zip](https://github.com/dart-lang/sdk/files/801507/test.zip)

**Tested on:**
Linux Centos7 (Dart 1.22 + 1.22.1)
Doesn't work, error: 

> Exception: NoSuchMethodError: Class 'JSObjectImpl' has no instance method 'querySelector'.
> Receiver: Instance of 'JSObjectImpl'
> Tried calling: querySelector("#id")

Windows 10 (Dart 1.21)
Doesnt work, error: 
> Exception: type 'JSObjectImpl' is not a subtype of type 'Document' of 'function result' where
>   JSObjectImpl is from dart:js
>   Document is from dart:html

Also: pub serve crashes. (no visible error)

Linux Centos7 (Dart 1.14)
Everything works, BUT not really usable because I keep getting a win32 popup on every refresh telling me to download a newer version of Dart.
I tried this only because I felt crazy, it seemed dart used to work better before. And apparently it did.

**Dazel:**
If you dont want to support Dartium that's fine. But I cant get dazel to work EITHER. 
So literally nothing works right now, I cannot use dart at all in the browser.

[errors.txt](https://github.com/dart-lang/sdk/files/801517/errors.txt)

The errors seem to be referencing this file:

[BAZEL.txt](https://github.com/dart-lang/sdk/files/801514/BAZEL.txt)

**Comment by matanlurey** [comment]
This is probably due to your use of the `web_components` package - I don't know if it's supported on the latest versions of Dartium (web components have changed quite a bit). I'd recommend removing that from your `pubspec.yaml` and trying again.

One of our community contributors now maintains PolymerDart - @dam0vm3nt - maybe he can help you if you are actually trying to use Polymer.

**Comment by Meai1** [comment]
Linux Centos7 (Dart 1.22.1)
No, the problem also exists with the dependencies section completely removed. 
I have tried your recommendation from gitter as well, same error.
(remove dependencies + pub cache repair + pub get)

**Comment by Meai1** [comment]
Ok it seems that  `<script src="document-register-element.js"></script>` was somehow causing this problem, I guess sorry about that but that really didnt occur to me as a possibility. Dazel still isnt working though, not sure if this is the right place. The pub serve crash was also real, but I think the pub cache repair fixed it.

**Comment by natebosch** [comment]
Filed https://github.com/dart-lang/bazel/issues/148 for what looks like (one of the) issues with dazel.

Keep in mind that dazel is very experimental and we don't expect it to work quite yet for most use cases - but we're iterating on it :)

I think you can solve the immediate problem by moving dazel from `dependencies` to `dev_dependencies`

**Comment by Meai1** [comment]
it went a little further with dazel, but then I get a different error: (dart 1.22.0)

`____[120 / 166] Compiling @pub_watcher//:watcher with ddc
ERROR: /home/pc/.cache/bazel/_bazel_pc/d67929f6031216904504ae482dab484c/external/pub_isolate/BUILD.bazel:10:1: Compiling @pub_isolate//:isolate with ddc failed: Worker process sent response with exit code: 1..
[error] The named parameter 'priority' isn't defined. (package:isolate/isolate_runner.dart, line 104, col 20)
[error] The named parameter 'priority' isn't defined. (package:isolate/isolate_runner.dart, line 110, col 22)
`

**Comment by dam0vm3nt** [comment]
Hi. If you want to use latest web components standard you have to take a look at this : https://pub.dartlang.org/packages/html5 

It uses a cousin of dazel (polymerize). More info on the homepage.
It works on chrome but not on dartium unless you load some polyfill too because dartium itself doesn't supports latest standards.

Otherwise you can use the normal polymer. I'll post a link to latest polymer-dart packages.

**Comment by Meai1** [comment]
@dam0vm3nt nothing works for me wow:

`[pc@localhost html5]$ polymerize init --rules-version=v0.0.11
[pc@localhost html5]$ bazel build html5
.............
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/pc/.cache/bazel/_bazel_pc/254055cf27cdb3256c284d536da4f5ed/external/js/BUILD:8:1: Polymerizing ../js/js.js failed: polymerize failed: error executing command bazel-out/host/bin/external/polymerize_tool/polymerize -o /tmp/out bazel -T bazel-out/local-fastbuild/bin/external/js/js_template.map -M 'js=external/js/js' --bower-needs ... (remaining 13 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/pc/.cache/bazel/_bazel_pc/254055cf27cdb3256c284d536da4f5ed/execroot/html5/bazel-out/host/bin/external/polymerize_tool/polymerize.runfiles/__main__/../polymerize_tool/polymerize.py", line 18, in <module>
    exit(polymerize(sys.argv[1:]))
  File "/home/pc/.cache/bazel/_bazel_pc/254055cf27cdb3256c284d536da4f5ed/execroot/html5/bazel-out/host/bin/external/polymerize_tool/polymerize.runfiles/__main__/../polymerize_tool/polymerize.py", line 10, in polymerize
    'PATH': '/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:%s' % (DART_HOME)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Target //:html5 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.038s, Critical Path: 0.08s
`

**Comment by dam0vm3nt** [comment]
Can you give me more info on your system? Like os version, dart version and
which's the path where dart is installed?

Also try issue a pub upgrade before running polymerize init again.

Thanks

Il Dom 26 Feb 2017, 10:26 Meai1 <notifications@github.com> ha scritto:

**Comment by Meai1** [comment]
@dam0vm3nt I tried this on 2 different OS now, Centos7 Dart 1.22.1 and Opensuse 42.2 Dart 1.22
Same error, also tried your pub upgrade but it didnt do anything.

**Comment by dam0vm3nt** [comment]
k, that's the reason. polymerize assume dart sdk in /usr/bin (like when installed with debian packages). I'm adding an option for polymerize to set your custom path.

**Comment by dam0vm3nt** [comment]
even better: i'll make polymerize assume `which dart` as the default, this way you shouldn't even need to specify it. Sorry for the inconvenient!

**Comment by dam0vm3nt** [comment]
actually here's where it expect to find it at the moment : 

 - `/usr/lib/dart/bin`

**Comment by dam0vm3nt** [comment]
K, now it should work on your system too.

 - [here](https://github.com/dam0vm3nt/html5_demo) you can find a demo project using the `HTML5` lib: in the sample a new component is created and defined. Works only in chrome for now because I haven't added polyfills for htmlimports and other standards not yet supported by all browsers.
 - please **update** polymerize to `0.4.6` with a ``pub global activate polymerize`, then follow the demo instructions

You can override the dart bin path with a `DART_HOME` environment library or explicitly with `--dart-bin-path` option :  `polymerize init --dart-bin-path=<my_dart_bin_path>`.

please feel free to add issues to the html5 lib or demo project if you have any other problem.
