### ISSUE TITLE
MissingCompileTimeError in regress_28217_test

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28902]
On vm-kernel-precomp-linux-release-x64-2-4-be and vm-kernel-linux-release-x64-be, since https://github.com/dart-lang/sdk/commit/de56824429a59dffa06cf0bc34b134515fa53bd2, regress_28217_test has been failing due to a 'MissingCompileTimeError'.

However, fasta actually prints 'Error: Method not found: 'a'.' on stdout, so it seems likely that it is the exit code which doesn't indicate any failures.

**Comment by nex3** [comment]
@kmillikin I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by jensjoha** [comment]
This is outdated.
