### ISSUE TITLE
vm-linux-debug-x64-reload-be failures

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28906]
The bot vm-linux-debug-x64-reload-be has had failures in all 11 recent builds numbered 1319-1329, but with several different tests (the number in front is the number of occurrences of a failure for that test):
```
    1 checked co19/Language/Statements/Yield_and_Yield_Each/Yield_Each/execution_async_t07
    1 checked co19/LibTest/isolate/ReceivePort/isEmpty_A01_t01
    1 co19/Language/Statements/Continue/async_loops_t06
    1 co19/LibTest/isolate/ReceivePort/transform_A01_t01
    1 corelib/date_time7_test
    1 standalone/io/pipe_server_test
    2 checked corelib/regexp/regress-regexp-codeflush_test
    2 checked standalone/io/raw_secure_server_closing_test
    2 co19/LibTest/isolate/ReceivePort/any_A01_t01
    2 standalone/io/web_socket_error_test
    3 checked standalone/array_bounds_check_generalization_test
    9 standalone/array_bounds_check_generalization_test
```
These tests  were all marked `none-vm debug_x64` or `none-vm-checked debug_x64`, and the latter ones have the word `checked` in the list above.

I haven't changed the status for these tests, because it seems likely that a commit near [3a1b7](https://github.com/dart-lang/sdk/commit/3a1b7bdfcaa9374f76807062914ebae29d389408) introduced an issue which affects all these different tests, and several others may come up even if these ones are marked as flaky.

**Comment by eernstg** [comment]
The following test failures in the builds 1502-1515 on the bot vm-linux-debug-x64-reload-rollback-be seem to be closely related to the failures reported above (because of the timing of the problem and the apparent randomness of the affected tests - I'm guessing that these two bots do very similar things).

With 'none-vm' or 'none-vm-checked' and then 'debug_x64 co19', we had the following failures (all crash):
```
  1 Language/Expressions/Function_Invocation/async_cleanup_t06
  1 LibTest/typed_data/Uint64List/Uint64List_A01_t02
  1 LibTest/typed_data/Uint64List/fillRange_A01_t01
  1 checked  LibTest/core/RegExp/hasMatch_A01_t02
```
These failures occurred for 'none-vm-checked debug_x64 standalone' (also all crash):
```
  1 io/raw_secure_server_closing_test
  1 io/secure_bad_certificate_test
  8 io/secure_socket_alpn_test
```

**Comment by nex3** [comment]
@johnmccutchan I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by johnmccutchan** [comment]
Nothing to do here.
