### ISSUE TITLE
fix strong mode errors in dart:math min, max

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#28909]
@munificent 's CL here: https://codereview.chromium.org/2386493003 will need to be re-landed in the SDK once we unfork. Opening this as a tracking bug.

**Comment by jmesserly** [comment]
the idea is to make min/max external and implement using a patch version in DDC.

**Comment by munificent** [comment]
Fixed in: https://codereview.chromium.org/2858353003/
