### ISSUE TITLE
create_sdk.py is not hermetic, uses host strip

### ISSUE THREAD

**Issue by kulakowski** [dart-lang/sdk#28900]
The call sites are here: https://github.com/dart-lang/sdk/blob/master/tools/create_sdk.py#L241

This in particular leads to

    [11920/11982] ACTION //dart:create_sdk(//build/toolchain/fuchsia:arm64)
    strip: Unable to recognise the format of the input file `/slice/fuchsia/out/debug-aarch64/dart-sdk.tmp/bin/dart'

when building the sdk for arm64 on Fuchsia.

**Comment by mit-mit** [comment]
@whesse

**Comment by zanderso** [comment]
A quick fix would be to pass the path to strip to create_sdk.py. Longer term we should think about moving the create_sdk.py functionality to the GN script.

@kulakowski do you know how to get the path to the current toolchain's `strip` in GN?

**Comment by zanderso** [comment]
It looks like there's not a good way to find this path. I'm just going to disable stripping in create_sdk.py in the Fuchsia build. The binaries that Fuchsia ends up with in the SDK it builds I think will still be stripped since the Fuchsia toolchain definitions pass a path for strip.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2720613004/

**Comment by zanderso** [comment]
Fuchsia will need to roll dart to https://github.com/dart-lang/sdk/commit/6c08487f4776841201585bdd771c35596548f87e to pick up the change.
