### ISSUE TITLE
Analyzer options-finding changing?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#28913]
Either this is an unintended bug or just an undocumented feature 😄 

Take a directory with a dart file and an `.analysis_options` file:

#### `~/code/dart-inference-1/b.dart`

```dart
class A {
  A();
  factory A.b() => new B();
}

class B extends A {
  int b = 7;
}

void main() {
  var x = new A.b();
  print(x.b);
}
```

#### `~/code/dart-inference-1/.analysis_options`

```yaml
analyzer:
 strong-mode: true
```

Let's run the 1.22.0-dev.9.0 analyzer, from `~`:

```
~$ dartanalyzer --version
dartanalyzer version 1.22.0-dev.9.0~$ dartanalyzer ~/code/dart-inference-1/b.dart
Analyzing [/Users/srawlins/code/dart-inference-1/b.dart]...
No issues found
```

And how about HEAD analyzer:

```
~$ code/dart-repo3/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 1.23.0-edge.b86388e3ed2a82c3a0fc53dea6f2726e335342b9
~$ code/dart-repo3/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer ~/code/dart-inference-1/b.dart
Analyzing /Users/srawlins/code/dart-inference-1/b.dart...
[error] The getter 'b' isn't defined for the class 'A' at code/dart-inference-1/b.dart:12:11 (undefined_getter).
1 error found.
```

Interesting. Looks like the analysis options is being read in the HEAD, but not 1.22.0-dev.9.0. I don't see anything about this in [the CHANGELOG.md](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md)

(If I remove the analysis options file, then HEAD analyzer does not analyze in strong mode.)

**Comment by srawlins** [comment]
CC @danrubel

**Comment by bwilkerson** [comment]
I believe that this should be viewed as a fix to previously broken behavior. Is this causing a problem, or was it just a change you noticed?

**Comment by srawlins** [comment]
The new behavior makes sense, so it is causing a problem only in that it was unexpected. Should be documented.

**Comment by danrubel** [comment]
Good point. I made this change to `dartanalyzer` so that it finds analysis options files using the same code analyzer functionality that analysis server uses. Needless to say, I should have updated the change log at the same time. 

https://github.com/dart-lang/sdk/pull/28928

**Comment by danrubel** [comment]
Documentation change landed. Please reopen if you find additional problems. Thanks!
