### ISSUE TITLE
recursive type hangs analyzer in _OverrideChecker

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#28926]
Given code like:
```dart
class Clonable<T> implements Clonable<Clonable<T>> {}
```
_OverrideChecker._checkAllInterfaceOverrides hangs in this code:
```dart
    // Helper function to collect all reachable interfaces.
    find(InterfaceType interfaceType, Set result) {
      if (interfaceType == null || interfaceType.isObject) return;
      if (result.contains(interfaceType)) return;
      result.add(interfaceType);
      find(interfaceType.superclass, result);
      interfaceType.mixins.forEach((i) => find(i, result));
      interfaceType.interfaces.forEach((i) => find(i, result));
    }

    // Check all interfaces reachable from the `implements` clause in the
    // current class against definitions here and in superclasses.
    var localInterfaces = new Set<InterfaceType>();
    var type = resolutionMap.elementDeclaredByClassDeclaration(node).type;
    type.interfaces.forEach((i) => find(i, localInterfaces)); // HANG HERE
    _checkInterfacesOverrides(node, localInterfaces, seen,
        includeParents: true);
```
`find` keeps trying to expand the interfaces forever.

**Comment by jmesserly** [comment]
the code here is already erroneous, FWIW.

**Comment by bwilkerson** [comment]
Which code do you mean by "the code here"? The example, or the implementation?

**Comment by jmesserly** [comment]
the example: `class C<T> implements C<C<T>> {}` gives `[error] 'C' can't implement itself.`

**Comment by bwilkerson** [comment]
So, the first time into `find` the interface type is `C<C<T>>`, the second time it's `C<C<C<T>>>`, etc. The consequence is that the `result` set never contains the interface type so we never terminate.

We could potentially also pass in a set of elements and use the elements to stop recursion, but I'm not sure whether that would lead to other errors (though it's probably better than an infinite loop :-).

**Comment by jmesserly** [comment]
this still reproduces.

**Comment by scheglov** [comment]
This part of `_OverrideChecker` was rewritten and moved into `InheritanceManager2` in 9185294e7a80943b05be50ea3305173217da62cc. This code does not cause infinite recursion anymore.
