### ISSUE TITLE
FutureOr conditional expression typing issue

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#28927]
I'm running into a typing issue similar to #28783, but in the context of a conditional expression (`?:`)
```dart
  FutureOr<bool> routerCanDeactivate(next, prev) =>
      someExpression
          ? true
          : methodReturningFutureBool();
```
Under 1.22.1, this results in an analyzer warning:
> WARNING: Unsafe implicit cast from 'Object' to 'FutureOr<bool>'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime.

But the analyzer is happy if I put an explicit cast (which IMHO should be unnecessary):
```dart
  FutureOr<bool> routerCanDeactivate(next, prev) =>
      someExpression
          ? true as FutureOr<bool> // <================== cast
          : methodReturningFutureBool();
```
@leafpetersen @bwilkerson @nex - I wasn't sure if you'd want a separate issue for this, or whether you'd prefer clumping it up with #28783. It felt like `?:` might have its typing rules handled separately from if-then-else statements. Anyhow, I'll let you mark this as a dup if you want to merge the issues.

cc @kwalrath @matanlurey

**Comment by leafpetersen** [comment]
Different from #28783, but basically a dup of https://github.com/dart-lang/sdk/issues/25368 .  Definitely something I want to fix when I get a chance.  Current behavior allows really bad code, and gives an error on correct code.  Sadness.

**Comment by Lootwig** [comment]
@leafpetersen https://github.com/dart-lang/sdk/issues/25368 was closed with "being covered by null safety", but doesn't resolve this issue. Below code still throws a compiler error for the getter in dart 2.14.4.

```dart
import 'dart:async';

class X {
  FutureOr<int> get f => true ? Future.value(12) : 13;
}
```

**Comment by leafpetersen** [comment]
Maybe.  I'm a little hesitant about introducing `FutureOr` where there wasn't one to begin with. We'd have to evaluate carefully what side effects result.

**Comment by bwilkerson** [comment]
@leafpetersen This looks like a language issue rather than an implementation issue. If you agree I'll move this over to the language repo.
