### ISSUE TITLE
analyzer produces linter warnings in dependencies

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28930]
since a few days

![image](https://cloud.githubusercontent.com/assets/405837/23450668/b69c31ce-fe5c-11e6-8fac-8dd82dc3d616.png)

This file is from `build_runner-0.3.0` a hosted dependency.
Same with `dart:xxx` packages.

> Dart VM version: 1.23.0-edge.804f3dfdd8c4cbe3cc2c517f98b7d4a192256a0e (Tue Feb 28 02:51:01 2017) on "linux_x64"

> IntelliJ IDEA 2017.1 EAP

**Comment by bwilkerson** [comment]
@danrubel Any idea what might have changed that would cause this to happen?

**Comment by zoechi** [comment]
Just a wild guess, because I just saw the comment https://github.com/dart-lang/sdk/issues/28383#issuecomment-283363697

**Comment by danrubel** [comment]
Need some clarification here...

Is this a Flutter project? There was a recent change that upgraded a specific Flutter related linter hint to a warning.

In addition, I recently updated `dartanalyzer` to [find the analysis options in the same way](https://github.com/dart-lang/sdk/commit/abee739921f4770fa6b69c5256803adc4fae4d08) that analysis server does (see [change log](https://github.com/dart-lang/sdk/commit/bfb8e82c6e306091de676e806feea50aa41180ec)). In addition, you can use `dartanalyzer --verbose /path/to/some/file.dart` and it will [echo the analysis options file used](https://github.com/dart-lang/sdk/commit/0c290ae4563560713b801c59614718b5ad4a28e3). Hopefully that will help track down the issue.

**Comment by zoechi** [comment]
@danrubel it's not a Flutter project. I saw it in a normal console application project and an Angular project.

I'm using `analysis_options.yaml`, but I don't understand how this might be related.

**Comment by danrubel** [comment]
`analysis_options.yaml` determines what analysis is performed and whether it appears as an error, warning, or hint. That said, it sounds like you have not changed that file, yet you are now seeing new warnings. Not sure I can help here.

**Comment by zoechi** [comment]
No, I haven't changed the `analysis_options.yaml`. #28962 seems to be about the same problem.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2734673002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/24d5466a72a34cfe1fca15bb6f546553dc3bf4ea
