### ISSUE TITLE
FileSystemException: Cannot open file, path = 'build\win_toolchain.json'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28931]
I wanted to run co19 tests in FF on Windows but got `FileSystemException: Cannot open file, path = 'build\win_toolchain.json', errno = 2)`

Steps that I performed:
1) got the latest version of SDK sources by git clone...
2) Changed  sdk\tools\testing\dart\co19_test.dart to 
```dart
const List<List<String>> COMMAND_LINES = const <List<String>>[
// Dart2js FF runner
  const <String>['-mrelease', '-rff', '-cdart2js', '--use-sdk' ],
  const <String>['-mrelease', '-rff', '-cdart2js', '--use-sdk', '--checked'],
];
```
3) Uploaded all missing third party libraries (packege_resolver, http, http_parser etc)
4) Run dart tools\testing\dart\co19_test.dart  and got the error:
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'build\win_toolchain.json' (OS Error: The system cannot find the file specified.
, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:352)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

How to resolve this?

**Comment by floitschG** [comment]
@whesse not sure the area is correct. Please update if I was wrong.

**Comment by whesse** [comment]
To run the tests, you need to check out all the dependencies by checking out the SDK sources using gclient, not just a git checkout of dart-lang/sdk.  Follow the instructions at https://github.com/dart-lang/sdk/wiki/Building

After a gclient sync, you should be able to run the tests without actually building, by downloading the SDK for your platform and unzipping it into a directory.  You would have to use the --use-sdk option for tests, and the --sdk option with a directory path telling where the SDK has been unzipped.

The co19_test.dart file in /tools/testing/dart is just meant as a helper file, to make it easier to run some test configurations and summarize their results.  If it isn't working, run the configurations directly.

Note that firefox on windows is not run in the --checked mode, but is run in the --fast-startup mode.  See the tests run by the builder dart2js-win7-ie11ff-2-4-be to see which test command lines are run on the windows builders, at an address like https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie11ff-1-4-be

Using "git grep" to look for "win_toolchain.json" in the source, we see that a line was added to test_configurations.dart last month, that tries to fetch info from that file.  The comment says that this
file is created by gclient runhooks, which will in turn be run by gclient sync.

**Comment by sgrekhov** [comment]
gclient sync helped. Thank you
