### ISSUE TITLE
Spec: In checked mode, `void` should allow any value.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28936]
This is the specification issue for #28935.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by terrylucas** [comment]
@dgrove
Dan is this a feature we want post 1.24 Dartium?

**Comment by anders-sandholm** [comment]
@eernstg seems like this is in the spec. Ready to close?

**Comment by eernstg** [comment]
Done in 122345e3568e3191a7a91af2686c18d8ed40369f, closing.
