### ISSUE TITLE
DDC: allow void as a type argument.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28947]
This is the DDC issue for #27504.

**Comment by floitschG** [comment]
Please make sure to claim this issue when starting work on it. I intend to help out when I have the time, and we want to avoid duplicated work.

**Comment by vsmenon** [comment]
@leafpetersen 

Is there a runtime component to this?  Not sure if there is any DDC work here once it's supported in the front end.

**Comment by leafpetersen** [comment]
I believe that we already implement the runtime component of this.

**Comment by vsmenon** [comment]
Marking as done.  DDC runtime checking should already handle.
