### ISSUE TITLE
spec: `void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28942]
This is the spec issue for https://github.com/dart-lang/sdk/issues/28939.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment]
Punting to 1.25, in agreement with Kasper: The 1.24 release does not depend on the concrete spec change, and the issue is well-understood.

**Comment by lrhn** [comment]
Landed as 26d6e3596d034024605ecf9dcfa489b544fa6245.
