### ISSUE TITLE
VM: allow void as a type argument

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28945]
This is the VM issue for #27504.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by crelier** [comment]
It is not clear to me what feature is required here. It is easy to syntactically allow void as a type argument (see referenced cl), but I need to know how to handle void in type tests (non-strong mode and strong mode). So we need a spec or at least a set of dart tests setting some expectations. Thanks.

**Comment by eernstg** [comment]
Right, you do of course need that, as do others---and I'll be writing such a spec (in the form of a standalone informal spec, as usual). We're GoogleServing today, but I'll get started writing it tomorrow.
