### ISSUE TITLE
Unicode output doesn't work in PowerShell ISE on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28948]
While https://github.com/dart-lang/sdk/issues/28571 fixed Unicode output in PowerShell.exe and Cmd.exe, it is unfortunately still broken in PowerShell ISE.

PowerShell ISE is a new host application for Windows PowerShell, which is far more powerful then the old  host application used by PowerShell.exe and Cmd.exe ([details from Microsoft](https://msdn.microsoft.com/en-us/powershell/scripting/core-powershell/ise/introducing-the-windows-powershell-ise)).

One thing that is better in PowerShell ISE compared to plain PowerShell.exe and Cmd.exe is that PowerShell ISE supports displaying all Unicode characters (e.g. 🔥) whereas PowerShell.exe and Cmd.exe are limited to the small set of Unicode characters included in the default console font ("Consolas" or "Lucida Console").

Ideally, when Unicode output gets fixed in PowerShell ISE, I'd like to recommend PowerShell ISE as the best way to interact with Flutter because it will have the prettiest output.

/cc @zanderso @a-siva

**Comment by goderbauer** [comment]
Might be related:

```dart
import 'dart:io';

void main() {
	print(stdout.hasTerminal);
}
```

This little program prints `false` when executed from PowerShell ISE and `true` when printed from PowerShell.exe or Cmd.exe.

**Comment by zanderso** [comment]
Dug into this a little. As indicated by @goderbauer's comment, stdout in PowerShell ISE is connected to a pipe and not a terminal. As such, our options at the sending side of the pipe are a bit limited. There are hacky ways of detecting that PowerShell ISE is at the other end of the pipe, but I'm not sure there's a way to do it that we want to bake in to the VM.

OTOH, there is a workaround from Dart code. After some experimenting, I've found that PowerShell ISE appears to do the right thing with BOMs. Before writing anything else to stdout, if you put the UTF8 BOM on the pipe, like so:

```dart
stdout.add([0xEF,0xBB,0xBF]);
```

It correctly interprets the following data as UTF8, and prints Unicode characters as expected (AFAICT).

It might make sense to do something from flutter_tool like:

```dart
if (Platform.isWindows && !stdout.hasTerminal) {
  stdout.add([0xEF,0xBB,0xBF]);
}
```

before anything else can be printed.

**Comment by goderbauer** [comment]
Wow. That's an interesting work around :)

I can confirm that it sort-of works if the BOM is really the first thing that gets printed to the console. However, it's hard to grantee that. In our case, the dart script is actually wrapped in a batch script which might print something before dart is launched and in that case the BOM bytes are actually printed as "ï»¿" and don't have the desired effect.

**Comment by zanderso** [comment]
Right. PowerShell ISE decides how to interpret the rest of the bytes depending on the presence or absence of a BOM at the start of the stream. I don't think there's any Windows API call we can use in the Dart VM that would convince it to do otherwise. Even if that API call did exist, we don't really have enough information to decide where we should be using it. All we know is that stdout is a pipe.

Maybe reseting or clearing the console right before invoking Dart would make it respect the BOM from flutter_tool? Maybe try outputing the BOM from your shell script instead of from Dart? I'm not sure what the right thing to do here is.
