### ISSUE TITLE
dart2js: `void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28941]
This is the dart2js issue for https://github.com/dart-lang/sdk/issues/28939.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment]
Addressed by [this CL](https://codereview.chromium.org/2866213004/).

**Comment by eernstg** [comment]
Addressed in 9928c5cb805dedf73b83ab051069e7a2e8cb0e06, 935aeb43ce8993bb8ec6e48bce378149120c6618.
