### ISSUE TITLE
analyzer: `void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28940]
This is the analyzer issue for https://github.com/dart-lang/sdk/issues/28939.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment]
Addressed by [this CL](https://codereview.chromium.org/2870363003/).

**Comment by eernstg** [comment]
Landed in 6cb0966401f2a53196358945c0f78a32c575a8dc.
