### ISSUE TITLE
Spec: allow void as a type argument

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28944]
This is the specification issue for https://github.com/dart-lang/sdk/issues/27504.

**Comment by dgrove** [comment]
This should be targeted for 1.24, right? 

/cc @munificent

**Comment by terrylucas** [comment]
@dgrove
Dan is this a feature we want post 1.24 Dartium?

**Comment by anders-sandholm** [comment]
this is covered by #30597
