### ISSUE TITLE
API to know the memory use of Dart VM

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#28951]
It will be great if there is an API to know the memory use, so we can monitor the health status of a long-running server. For example, we can restart the VM if the consumption is too much (usually a leak, #27414).

**Comment by zoechi** [comment]
I expected https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#vm to provide that, but memory isn't mentioned.

**Comment by zanderso** [comment]
We already collect this information and expose it through the service protocol/Observatory, but I think we could/should add something to dart:io Platform for this. @floitschG @bkonyi

**Comment by zanderso** [comment]
Added in https://github.com/dart-lang/sdk/commit/9ce608e89d6b68d84f529fd9dab18f2bc61f5a8e
