### ISSUE TITLE
Analyzer Feedback / Unexpected exception

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28953]
![capturfiles-20170302_085402](https://cloud.githubusercontent.com/assets/116654/23497981/d2ea1386-ff25-11e6-8613-2444a499fff7.png)

I changed Line 24. While typing something like `level: ???? - cant remember what exactly` but here it crashed.
`level: Level.INFO` is correct - I had something else before.

[report.txt](https://github.com/dart-lang/sdk/files/813059/report.txt)

The following lines are generated by IJ - I left them how they were generated:
---
Analyzer%20Feedback%20from%20IntelliJ%0A%0A%23%23%20Version%20information%0A%0A-%20%60IDEA%20171.3566.24%60%0A-%20%601.22.1%60%0A-%20%60IU-171.3566.24,%20JRE%201.8.0_112-release-724-b5x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.11.6%20unknown,%20screens%201920x1080,%201920x1080,%202560x1440%60%0A%0A%23%23%20Exception%0A%0APlease%20append%20the%20contents%20of:%0Afile:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report.txt%0A%0A%60%60%60%0ADart%20analysis%20server,%20SDK%20version%201.22.1,%20server%20version%201.17.0,%20error:%20Task%20failed:%20GatherUsedLocalElementsTask%20for%20source%20/Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/unit/events/StatsChangedEvent_test.dart%0AUnexpected%20exception%20while%20performing%20GatherUsedLocalElementsTask%20for%20source%20/Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/unit/events/StatsChangedEvent_test.dart%0A%230%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:333)%0A%231%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%232%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%233%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%234%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1199)%0A%235%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%236%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1197)%0A%237%20%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:369)%0A%238%20%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:997)%0A%239%20%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:158)%0A%2310%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A%2311%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2312%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2313%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1150)%0A%2315%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2316%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2317%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2318%20%20%20%20%20Timer._createTimer.%3Canonymous%20closure%3E%20(dart:async-patch/timer_patch.dart:16)%0A%2319%20%20%20%20%20_Timer._runTimers%20(dart:isolate-patch/timer_impl.dart:385)%0A%2320%20%20%20%20%20_Timer._handleMessage%20(dart:isolate-patch/timer_impl.dart:414)%0A%2321%20%20%20%20%20_RawReceivePortImpl._handleMessage%20(dart:isolate-patch/isolate_patch.dart:148)%0A%0ACaused%20by%20Bad%20state:%20Unable%20to%20find%20()%20→%20Null%20in%20[()%20→%20dynamic]%0A%230%20%20%20%20%20%20ElementImpl.findElementIndexUsingIdentical%20(package:analyzer/src/dart/element/element.dart:3162)%0A%231%20%20%20%20%20%20FunctionElementImpl.identifier%20(package:analyzer/src/dart/element/element.dart:4425)%0A%232%20%20%20%20%20%20ElementLocationImpl.ElementLocationImpl.con1%20(package:analyzer/src/dart/element/element.dart:3202)%0A%233%20%20%20%20%20%20ElementImpl.location%20(package:analyzer/src/dart/element/element.dart:2920)%0A%234%20%20%20%20%20%20ElementImpl.hashCode%20(package:analyzer/src/dart/element/element.dart:2809)%0A%235%20%20%20%20%20%20_HashSet._hashCode%20(dart:collection-patch/collection_patch.dart:564)%0A%236%20%20%20%20%20%20_HashSet.add%20(dart:collection-patch/collection_patch.dart:600)%0A%237%20%20%20%20%20%20UsedLocalElements.addElement%20(package:analyzer/src/generated/resolver.dart:10562)%0A%238%20%20%20%20%20%20GatherUsedLocalElementsVisitor.visitFunctionExpression%20(package:analyzer/src/generated/resolver.dart:3522)%0A%239%20%20%20%20%20%20FunctionExpressionImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:5347)%0A%2310%20%20%20%20%20NodeListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:8044)%0A%2311%20%20%20%20%20ArgumentListImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:431)%0A%2312%20%20%20%20%20RecursiveAstVisitor.visitArgumentList%20(package:analyzer/dart/ast/visitor.dart:605)%0A%2313%20%20%20%20%20ArgumentListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:427)%0A%2314%20%20%20%20%20MethodInvocationImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:7656)%0A%2315%20%20%20%20%20RecursiveAstVisitor.visitMethodInvocation%20(package:analyzer/dart/ast/visitor.dart:1013)%0A#16%20%20%20%20%20MethodInvocation

**Comment by alexander-doroshko** [comment]
@stevemessick Any idea why auto-reports from Mike are malformed? (Other example [here](https://github.com/dart-lang/sdk/issues/28760)). All other users seem to submit correctly rendered analysis server errors.

**Comment by MikeMitterer** [comment]
I'm on Mac 10.11.6.

IntelliJ IDEA 2017.1 EAP
Build #IU-171.3566.24, built on February 21, 2017
IntelliJ IDEA EAP User
Expiration date: March 23, 2017
JRE: 1.8.0_112-release-724-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

Dart-Plugin:  171.3583

**Comment by MikeMitterer** [comment]
Just got another error: #28956
This time the report looks OK - din't change anything. Just clicked on the link IJ provides

**Comment by natebosch** [comment]
We are not able to repro analyzer stack traces from old versions of the SDK. If you get similar problems with an up to date please SDK please file a new issue.
