### ISSUE TITLE
CrossARM build of sdk has error message

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28954]
Building the sdk with -mrelease -aarm create_sdk gives a GN error, but seems to work, otherwise:

whesse@mcvoodie:~/ssd/sdk$ tools/build.py -mrelease -aarm create_sdk
ninja -C out/ReleaseX64 create_sdk
ninja: Entering directory `out/ReleaseX64'
[1317/1317] STAMP obj/create_sdk.stamp
GetBuildConf: Cross-build of arm on x64

GetBuildConf: Cross-build of arm on x64

ninja -C out/ReleaseXARM runtime
ninja: Entering directory `out/ReleaseXARM'
[1/1] Regenerating ninja files
ERROR at build arg file (use "gn args <out_dir>" to edit):1:12: Build argument has no effect.
arm_arch = "armv7"
           ^------
The variable "arm_arch" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view possible args, run "gn args --list <builddir>"
[2346/2346] STAMP obj/runtime.stamp
GetBuildConf: Cross-build of arm on x64

GetBuildConf: Cross-build of arm on x64

@rmacnak-google @zanderso

**Comment by zanderso** [comment]
This issue was fixed by various changes.
