### ISSUE TITLE
lib_strong tests are failing on dartanalyzer in strong mode

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28969]
These tests should be made strong-mode clean (or correct if they are testing strong-mode warnings/errors).

The tests that are failing because package:unittest is not strong-mode clean should be fixed
by changing them to use package:expect or some other light test library, not by changing them
to use package:test, which has too many dependencies to be used in core lib tests.
We haven't yet settled on a best replacement for unittest.

The status file at tests/lib_strong/lib_strong.status has the following section added:

convert/ascii_test: StaticWarning # Issue 28823
convert/chunked_conversion_json_decode1_test: StaticWarning # Issue 28823
convert/chunked_conversion_utf82_test: StaticWarning # Issue 28823
convert/chunked_conversion_utf83_test: StaticWarning # Issue 28823
convert/chunked_conversion_utf85_test: StaticWarning # Issue 28823
convert/encoding_test: StaticWarning # Issue 28823
convert/json_utf8_chunk_test: StaticWarning # Issue 28823
convert/latin1_test: StaticWarning # Issue 28823
convert/streamed_conversion_json_utf8_decode_test: StaticWarning # Issue 28823
convert/streamed_conversion_json_utf8_encode_test: StaticWarning # Issue 28823
convert/streamed_conversion_utf8_decode_test: StaticWarning # Issue 28823
convert/streamed_conversion_utf8_encode_test: StaticWarning # Issue 28823
convert/utf8_encode_test: StaticWarning # Issue 28823
convert/utf8_test: StaticWarning # Issue 28823
html/canvas_test: StaticWarning # Issue 28823
html/canvasrenderingcontext2d_test: StaticWarning # Issue 28823
html/cross_domain_iframe_test: StaticWarning # Issue 28823
html/cssstyledeclaration_test: StaticWarning # Issue 28823
html/custom/created_callback_test: CompileTimeError # Issue 28823
html/custom/document_register_basic_test: CompileTimeError # Issue 28823
html/custom/document_register_type_extensions_test: CompileTimeError # Issue 28823
html/custom/element_upgrade_test: CompileTimeError # Issue 28823
html/debugger_test: CompileTimeError # Issue 28823
html/element_animate_test: StaticWarning # Issue 28823
html/form_data_test: StaticWarning # Issue 28823
html/history_test: StaticWarning # Issue 28823
html/indexeddb_2_test: StaticWarning # Issue 28823
html/js_interop_1_test: StaticWarning # Issue 28823
html/js_typed_interop_default_arg_test/default_value: MissingCompileTimeError # Issue 28823
html/native_gc_test: StaticWarning # Issue 28823
html/request_animation_frame_test: StaticWarning # Issue 28823
html/transition_event_test: StaticWarning # Issue 28823
html/url_test: StaticWarning # Issue 28823
html/wheelevent_test: StaticWarning # Issue 28823
html/worker_test: StaticWarning # Issue 28823
html/xhr_test: StaticWarning # Issue 28823
mirrors/deferred_mirrors_metadata_test: StaticWarning # Issue 28823

**Comment by srawlins** [comment]
Closing as stale; we've migrated type systems once again since this was filed, and migrated all of the tests. If there are still failures, it should probably be tracked with a new bug.
