### ISSUE TITLE
Another bogus "Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"" warning.

### ISSUE THREAD

**Issue by ktullavik** [dart-lang/sdk#28967]
When changing a variable with unary operators, the analyser don't seem to invalidate its
assumptions - and produces false warnings.

Example, both inner conditionals in this function give bogus warnings:

```
    void test() {
        int b = 2;
        if (b > 0) {
            b--;
            if (b == 0) {
                return;
            }
            if (b > 0) {
              return;
            }
        }
    }
```
Funny enough, the warning _would_ be appropriate for the outer conditional.
Dart SDK version: 1.22.1

**Comment by bwilkerson** [comment]
@alexeieleusis

**Comment by mraleph** [comment]
@ktullavik  `b` is equal to 1 inside the outer condition after `b--` so `b == 0` evaluates to `false` and `b > 0` evaluates to `true` unconditionally. what is bogus about the warning?

**Comment by alexeieleusis** [comment]
These cases are indeed not considered in the rule, there is a bug reported for it and a PR out https://github.com/dart-lang/linter/pull/412 should land soon.

**Comment by alexeieleusis** [comment]
By the way, the rule does not try to infer the value of the variable, and should not warn about anything inside the outer `if` statement precisely because of the mutation to `b`.

**Comment by ktullavik** [comment]
@mraleph the warning is not dependant on the value of b.

**Comment by mraleph** [comment]
@ktullavik no matter which *constant* value you select for the initial value of `b` conditions like `b == 0` and `b > 0` would always be constant - because `b` value after `b--` is *known*. They might be different depending on the constant value of `b` you selected, but they are nevertheless known in compile time.

Compare your example with 

```dart
void test(bool x) {
  int b = x ? 2 : 1;
  if (b > 0) {
    b--;
    if (b == 0) {
        return;
    }
    if (b > 0) {
      return;
    }
  }
}
```

Here indeed conditions are not constant.

**Comment by ktullavik** [comment]
@mraleph 
Yes sorry, I should have made b unknown in the example to avoid confusion.
But it's irrelevant. The wrong analyser assumption is caused by the outer conditional,
not by the value of b.

**Comment by srawlins** [comment]
This linter rule is removed.
