### ISSUE TITLE
dart:html library mentions Dart Editor at the very top

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#28965]
https://api.dartlang.org/stable/1.22.1/dart-html/dart-html-library.html

Aside from the formatting issues, the text references the Dart Editor.

**Comment by alan-knight** [comment]
I'm not sure what to write, but If somebody wants to write some updated/formatted text I will happily  put it in the right template. @kevmoo ?

**Comment by kevmoo** [comment]
@kwalrath @Sfshaza would one of ya'll take a stab at updating this verbiage?

**Comment by srawlins** [comment]
This has been fixed, woohoo! https://api.dartlang.org/dev/2.0.0-dev.65.0/dart-html/dart-html-library.html
