### ISSUE TITLE
VM service should accept URIs instead of file paths for hot reload

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28972]
(cross-posted from https://github.com/flutter/flutter/issues/8502)

To be truly portable, the following calls should accept real platform-independent URIs (instead of platform-specific file paths) on the remote (VM) side:

- https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/devfs.dart#L203
- https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/devfs.dart#L273
- https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/vmservice.dart#L850
- https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/vmservice.dart#L853
- https://github.com/goderbauer/flutter/blob/b8a53749c1bd542e4c5588c332e01e2a8790f852/packages/flutter_tools/lib/src/vmservice.dart#L717

/cc @johnmccutchan

**Comment by goderbauer** [comment]
I just gave this a shot. It partially works (https://github.com/flutter/flutter/pull/8701), but in the following places it still expects file paths instead of URIs:
* https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/vmservice.dart#L850
* https://github.com/flutter/flutter/blob/17057bb44b7c10b2b4603cd09b266d9379f65ba2/packages/flutter_tools/lib/src/vmservice.dart#L853
* https://github.com/goderbauer/flutter/blob/b8a53749c1bd542e4c5588c332e01e2a8790f852/packages/flutter_tools/lib/src/vmservice.dart#L717

**Comment by johnmccutchan** [comment]
@goderbauer [_flutter.runInView](https://github.com/goderbauer/flutter/blob/b8a53749c1bd542e4c5588c332e01e2a8790f852/packages/flutter_tools/lib/src/vmservice.dart#L717) is actually implemented inside Flutter engine.

I will fix the other two.

**Comment by johnmccutchan** [comment]
@goderbauer I debugged this and the other two work with Uris without issue. It's likely an issue in Flutter's file loader if Uris don't work.

I've updated our existing unit test to pass Uris in this [CL](https://codereview.chromium.org/2738133005)

**Comment by goderbauer** [comment]
Okay, thanks for looking into it. I'll see where this breaks in Flutter then.
