### ISSUE TITLE
Debugging StringConcatenation doesn't work the same on simdbc as on other platforms

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28975]
E.g. with
```dart
main() {
  String world = "world";
  print("Hello, $world");
}
```
setting a breakpoint on main and 'next'ing through it on e.g. linux it stops at
* "(" in main
* "=" on line 2
* ")" on line 3 (after '$world"')
* "print on line 3
* "}" on line 4

On SIMDBC64 for instance it skips the ")" on line 3 (after '$world"') part.
Se also tests
service/next_through_catch_test
service/next_through_simple_async_test
service/next_through_simple_linear_2_test

**Comment by alexmarkov** [comment]
Closing this issue as SIMDBC64 mode was removed a while ago.
