### ISSUE TITLE
Observatory and checked mode

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28978]
We can run the service tests in checked mode (and some bots do).

There's an issue with uninitialized fields though:

Edit runtime/observatory/tests/service/service.status to not allow field_script_test to fail and run
```
python tools/test.py -mrelease --checked -t60 service/field_script_test 
```

I get
```
[...]
** Killing script
Unexpected exception in service tests: type 'Sentinel' is not a subtype of type 'Instance' of 'value' where
  Sentinel is from package:observatory/service.dart
  Instance is from package:observatory/service.dart
[...]
```

It seems that observatory injected into the vm does never run in checked mode though.

If I apply the following patch
```
diff --git a/runtime/observatory/lib/src/service/object.dart b/runtime/observatory/lib/src/service/object.dart
index 954f24e6a5..731bf025e1 100644
--- a/runtime/observatory/lib/src/service/object.dart
+++ b/runtime/observatory/lib/src/service/object.dart
@@ -3202,6 +3202,9 @@ class Field extends HeapObject implements M.Field {
     if (mapIsRef) {
       return;
     }
+    if (map['staticValue'] is! Instance) {
+      print("Field staticValue for $name is not an instance! Should now fail in checked mode.");
+    }
     staticValue = map['staticValue'];

     guardNullable = map['_guardNullable'];
```

I get "Field staticValue for tests is not an instance! Should now fail in checked mode." (also printed to the terminal when loading the observatory in the vm, btw.)

Looking at field 'tests' via observatory in the browser it says "static value: <not initialized>", so it seems that this is somewhat the expected outcome. That doesn't change that whenever a field isn't initialized a non-Instance is assigned to a variable that typed to be an Instance though.

**Comment by rmacnak-google** [comment]
Stale.
