### ISSUE TITLE
Renaming a "library part file" breaks the library

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28977]
I renamed the file "StatsRecordPerPeriodType.dart" to "StatsType.dart" - this should also rename the part-directive in model.dart

![capturfiles-20170307_012130](https://cloud.githubusercontent.com/assets/116654/23656250/26465a82-0339-11e7-948b-010e654c4d1c.png)

**Comment by alexander-doroshko** [comment]
Works correctly to me. Is 'Search for references' enabled in your Rename dialog?
![image](https://cloud.githubusercontent.com/assets/4499789/23658061/1f150bdc-0352-11e7-984d-b7ae6cf09e47.png)

**Comment by MikeMitterer** [comment]
@alexander-doroshko ???? Hmmm - I think this is selected by default but I'm not sure if it was when I renamed that particular file. If I rename something in Java - *it just works* as expected - I don't have to check if a checkbox is ticked or not. Maybe this was the problem.

**Comment by alexander-doroshko** [comment]
Yes, it is selected by default, but once you unselect it - next time it is unselected as well. The same for Java.
If you can't reproduce with the option checked I think the issue can be closed.
