### ISSUE TITLE
File names could be shortened a bit in casual stack traces when shown in IDEs

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28979]
File names take up a lot of space in casual stack traces:

```
#0      doWork.<doWork_async_body> (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart:5:5)
<asynchronous suspension>
#1      doWork (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart)
#2      doWork.<doWork_async_body> (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart:8:9)
<asynchronous suspension>
#3      doWork (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart)

```

Would be great if we could shorten them a bit.

**Comment by rmacnak-google** [comment]
The Dart standard requires StackTrace.toString() to report function activations exactly: no omitted frames (e.g., from inlining), no synthetic frames, no obfuscation, and precise source locations. The base stack traces should not be lossy.

**Comment by mit-mit** [comment]
Sure, but surely that doesn't prevent us from post-processing it to make it more usable to the developer when used in a tooling context?

**Comment by zanderso** [comment]
@mit-mit If the idea is to post-process with tooling, would you mind editing the issue title and/or applying the right labels for that? Thanks!

**Comment by mit-mit** [comment]
cc @devoncarew should this actually be in the tools tracker?

**Comment by devoncarew** [comment]
We do some work in the flutter framework to make traces more appealing, and may do as well in flutter_tools. If we move this issue over, it would be nice to first verify that traces aren't already post-processed.

**Comment by dgrove** [comment]
@devoncarew can you please apply the right area tag for this? (it's not clear to me where this should land)

**Comment by devoncarew** [comment]
I'll move this to the flutter repo.

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter#19291
