### ISSUE TITLE
Analyzer: "Create N missing overrides" imports naughty files

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28987]
I am implementing the [`Builder`][builder] class from `package:build`, so I wrote in lib/base.dart:

```dart
import 'package:build/build.dart';

abstract class AbstractBuilder implements Builder {
  String doThing(BuildStep buildStep);
}
```

[builder]: https://www.dartdocs.org/documentation/build/0.7.2/build/Builder-class.html

When I was writing a test for this class, I wrote:

```dart
import 'package:my_package/base.dart';

class MyBuilder extends AbstractBuilder {}
```

I then used the quick-fix 'create N missing overrides':

<img width="346" alt="screen shot 2017-03-07 at 8 46 05 pm" src="https://cloud.githubusercontent.com/assets/168174/23690534/3e1810b8-0377-11e7-831a-31c74349018a.png">

And got what I wanted, great! But it for auto-adding imports, it chooses package-privates, i.e.:

```dart
import 'package:build/src/asset/id.dart';
import 'package:build/src/builder/build_step.dart';
```

I expected it instead to import the public library, `package:build/build.dart`.

**Comment by zoechi** [comment]
dup of #27819 ?

**Comment by matanlurey** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/27819.
