### ISSUE TITLE
Remove suppression of compile-time warning regarding _getMainClosure

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28989]
I've added this code to body_builder.dart:

```
      if (isDartLibrary &&
          node.name.name == "main" &&
          library.uri.path == "_builtin" &&
          member?.name == "_getMainClosure") {
        return new NullLiteral()..fileOffset = node.fileOffset;
      }
```

This should be removed when `_getMainClosure` no longer refers to `main` via special scoping rules.

**Comment by jensjoha** [comment]
`_getMainClosure` was removed from _builtin in 8b7af73daafedacf0f239d17096703420937af69 - but it appears to still exist in flutter.
