### ISSUE TITLE
Detect function key press on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#28984]
In Flutter's Hot Reload mode we give users the option to reload the app by pressing F5 (see [1]). On POSIX platforms, we use the ANSI code for F5 (see [2]) to detect the keypress. However, that doesn't seem to be available on Windows. In fact, as far as I can tell, there is no mechanism available in Dart on Windows to detect function key key-presses.

It would be cool if the Dart VM could provide a platform-independet way of detecting key presses of F1-F12.

[1] https://github.com/flutter/flutter/blob/644e7b131d99c3123e50a6c803bb2e70c59a60f6/packages/flutter_tools/lib/src/run_hot.dart#L244
[2] https://github.com/flutter/flutter/blob/3d079414ada61db813e87ddc9c12714765799e9f/packages/flutter_tools/lib/src/base/logger.dart#L260

**Comment by zanderso** [comment]
Looks like we need to set up:

https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

This may help with colors as well.

**Comment by goderbauer** [comment]
+1 to wiring this up.

It's my understanding that we'd also get color if dart would set `ENABLE_VIRTUAL_TERMINAL_PROCESSING` in addition to `ENABLE_VIRTUAL_TERMINAL_INPUT`.

**Comment by zanderso** [comment]
It looks like these console modes are Windows 10 only =( But wiring this up is probably the right thing to do, anyway. Just wanted to let you know.

**Comment by goderbauer** [comment]
I am aware of that. In fact, not all Windows 10 versions support it. Microsoft added it in "[Windows 10 Threshold 2 (v1511)](http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-(v1511)-Console-Host-Enhancements)". 

Ideally, there would be some way for Flutter to check from Dart if enabling Virtual Terminal Processing was successful or not because we should only then print ANSI escape sequences. Printing those sequences while it is disabled (or not available on older versions) would be bad.

**Comment by goderbauer** [comment]
On my Windows 10 system that reports `Platform.ansiSupport` as `true` I still cannot seem to read function key presses.

**Comment by goderbauer** [comment]
My mistake. I was accidentally running with an old Dart version. I can confirm that this works now! Thanks for the fix!

**Comment by zanderso** [comment]
Need to reopen this as there is a conflict between ENABLE_VIRTUAL_TERMINAL_INPUT and ENABLE_PROCESSED_INPUT, which causes ctrl-c to be ignored when function key presses are detected.

https://codereview.chromium.org/2763543003/

**Comment by goderbauer** [comment]
An update from the Flutter-side: After some discussion, we completely removed all functionality related to detecting function key presses because it doesn't work great on any of the platforms we support. So, this particular issue is no longer relevant for Flutter. Having Ctrl+C work and being able to print ANSI colors is much more important for us.

**Comment by zanderso** [comment]
In that case, I'll close the issue again.
