### ISSUE TITLE
Free of non-malloc'd pointer on mac release x64

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28991]
On commit 09b5d6f619c415fcf885bffd868c1f09c1cd9989 but this looks like a flaky failure.

FAILED: none-vm-checked release_x64 standalone/io/raw_secure_server_socket_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
asyncStart main
unittest-suite-wait-for-done
asyncStart testSimpleBind
asyncStart testInvalidBind
asyncStart testInvalidBind 2
asyncStart testInvalidBind 3
asyncStart testSimpleConnect
asyncStart testSimpleConnectFail 0
asyncStart testSimpleConnectFail 1
asyncStart testSimpleConnectFail 2
asyncStart testSimpleConnectFail 3
asyncStart testSimpleConnectFail 4
asyncStart testSimpleConnectFail 5
asyncStart testServerListenAfterConnect
asyncStart testSimpleReadWrite(true, true, false, false, false
asyncStart testSimpleReadWrite(true, false, false, false, false
asyncStart testSimpleReadWrite(false, true, false, false, false
asyncStart testSimpleReadWrite(false, false, false, false, false
asyncStart testSimpleReadWrite(false, false, true, true, false
asyncStart testSimpleReadWrite(false, false, true, false, false
asyncStart testSimpleReadWrite(true, true, false, false, true
asyncStart testSimpleReadWrite(false, false, true, true, true
asyncStart testPausedSecuringSubscription false false
asyncStart testPausedSecuringSubscription true false
asyncStart testPausedSecuringSubscription false true
asyncStart testPausedSecuringSubscription true true
asyncEnd main
asyncEnd testSimpleBind
asyncEnd testInvalidBind 3
asyncEnd testInvalidBind 2
asyncEnd testInvalidBind
asyncEnd testPausedSecuringSubscription false true
asyncEnd testPausedSecuringSubscription true true
asyncEnd testPausedSecuringSubscription true false

stderr:
dart(8845,0x7000013d0000) malloc: *** error for object 0x7fd835013580: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Command[vm]: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --enable_asserts --enable_type_checks --short_socket_write --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-x64-be/build/sdk/.packages /b/build/slave/vm-mac-release-x64-be/build/sdk/tests/standalone/io/raw_secure_server_socket_test.dart
Took 0:00:03.095399

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 standalone/io/raw_secure_server_socket_test

**Comment by nex3** [comment]
@rmacnak-google I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by rmacnak-google** [comment]
Stale.
