### ISSUE TITLE
Confusing description for Completer.isCompleted

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28997]
The description for [Completer ](https://api.dartlang.org/stable/1.21.1/dart-async/Completer/Completer.html)constructor reads:

> Completer()
> Creates a new completer.
> 
> The general workflow for creating a new future is to 1) create a new completer, 2) hand out its future, and, at a later point, 3) invoke either complete or completeError.
> 
> **The completer completes the future asynchronously. That means that callbacks registered on the future, are not called immediately when complete or completeError is called. Instead the callbacks are delayed until a later microtask.**

The description for property [Completer.isCompleted](https://api.dartlang.org/stable/1.21.1/dart-async/Completer/isCompleted.html) reads:

> bool isCompleted
> Whether the future has been completed.

I think the `isCompleted` description is ambiguous.
It is not clear, when `isCompleted` returns true: right after the call to `complete` or `completeError` or after future callbacks are executed.

**Comment by lrhn** [comment]
That does need improvement - in both places.

The `isComplete` actually says whether `complete` or `completerError` has been called. 

Since you can call `complete` with a non-completed `Future`, that doesn't directly correspond to whether the completer's future is completed, and it's not just delayed until a later microtask - it might never complete if the provided future doesn't.

**Comment by srawlins** [comment]
The [docs](https://api.dartlang.org/dev/dart-async/Completer/isCompleted.html) have been improved to include such text:

> Reflects whether complete or completeError has been called. A true value doesn't necessarily mean that listeners of this future have been invoked yet, either because the completer usually waits until a later microtask to propagate the result, or because complete was called with a future that hasn't completed yet.
