### ISSUE TITLE
static generic method throws Exception in Dartium / looks fine for Analyzer

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28996]
#This function: (Original: https://github.com/MikeMitterer/dart-material-design-lite/blob/mdl-1.x/lib/src/observable/ObservableList.dart#L287)

```dart
class ABC {
    ...
    static bool _defaultUpdateCallback<T>(final dom.HtmlElement element, final T item) {
        return false;
    }
}
```
throws an Exception in Dartium. Analyzer is happy with it.

![capturfiles-20170309_090958](https://cloud.githubusercontent.com/assets/116654/23741330/3b088cb8-04a8-11e7-800c-8f27947273ab.png)

**Comment by MikeMitterer** [comment]
I commented this part out on the mdl-1.x branch because I need a working version...

**Comment by zoechi** [comment]
I tried to reproduce but I didn't get an error. Are you sure you have the latest Dartium?

(mine is from bleeding edge)
```
Chromium	45.0.2454.104 (Developer Build) (64-bit)
Revision	7558afb6379171d7f96b2db68ae9d2b64b2c5544
OS	Linux 
Blink	537.36 (@abaaf1d0b6b6483140b5dca34e80fc259833ddf7)
JavaScript	V8 4.5.103.35
Dart	1.23.0-edge.634a9a673aaee35f75ba8884f3ebdd6b26c7cbda
```

**Comment by floitschG** [comment]
Looks like your Dartium doesn't recognize generic functions.

What Dartium version are you using?

**Comment by terrylucas** [comment]
Please retry with Dartium 50 (Dart 1.24.2 Stable)
