### ISSUE TITLE
Cannot reference internal mixin when multiple nested mixins

### ISSUE THREAD

**Issue by manuelF** [dart-lang/sdk#29003]
# Describe your issue compiling with DDC
A double mixin is not correctly exporting the internal one, making it impossible to use with sourcegen'd mixin like package built_value or enum class.

# Does this error show up at build time or at run time?

Run time

# Include repro instructions. How can we try to build (or run) this code?

Following DDC test:
``` dart
// DO NOT SUBMIT

import 'package:test/test.dart';

void main() {
  test('mixin works', () {
    expect(new UsesMixin().test, 'test');
  });
}

class UsesMixin extends Object with TestMixin { }

abstract class TestMixin = Object with TestMixin2;

abstract class TestMixin2 {
  String get test => 'test';
}
```

**Comment by vsmenon** [comment]
@jmesserly I'm guessing that the `dart.mixin` helper is only looking at mixin methods on the class (`TestMixin`) and not the base class (`TestMixin2`) as the latter is almost always `Object`.  This appears to be rare (only?) case where that's not true.

**Comment by jmesserly** [comment]
I don't understand what's going on here; mixins are/were only supposed to apply a single level. Perhaps ClassTypeAlias is some sort of special case. 
(we have a bunch of bugs about ClassTypeAlias: https://github.com/dart-lang/sdk/issues/29004)

**Comment by jmesserly** [comment]
In particular here, you can see ClasstypeAlias is the culprit:
```dart
class UsesMixin extends Object with TestMixin {}
abstract class TestMixin2 {
  String get test => 'test';
}

// abstract class TestMixin = Object with TestMixin2; // works
abstract class TestMixin extends Object with TestMixin2 {} // doesn't work

main() => print(new UsesMixin().test);
```
That said, the spec section ([12.1 Mixin Application](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf)) is pretty unclear. TestMixin is rejected if it extends anything other than Object. This example doesn't work:
```dart

class UsesMixin extends Object with TestMixin {}
abstract class A {
  String get a => 'A';
}
abstract class B {
  String get b => 'B';
}
abstract class TestMixin = Object with A, B;
main() {
  var u = new UsesMixin();
  print(u.a + u.b);
}
```
I guess there's a special case for one and only one mixin, allowing you to (essentially) give it a new name.

**Comment by manuelF** [comment]
Ping on this. Any progress?

**Comment by jmesserly** [comment]
> Ping on this. Any progress?

Unfortunately no! @vsmenon is out sick and I'm working on some other things to unblock the roll into our internal codebase. We'll post updates once we get to this one.

I think it should be possible to workaround this easily: just use the other mixin, not the renamed one. So `class UsesMixin extends Object with TestMixin2 { }` in your example. Alternatively you can extend it: `class UsesMixin extends TestMixin { }`, as long as `Object` was the other thing. (`extends Object with TestMixin` is more or less equivalent to the shorter `extends TestMixin`)

**Comment by davidmorgan** [comment]
Friendly ping.

The workarounds don't work too well for us, unfortunately. We use this in a pattern for interacting with generated code:

https://github.com/google/built_value.dart/blob/master/example/lib/enums.dart#L46

We can't refer to the other mixin because it's private.

Using "extends" could work, but this is awkward; the mixin is only generated if you refer to it, so we need a canonical way to refer to it, and the generator enforces this. We'd have to update the generated and all users.

So, we'll likely want to wait for the DDC fix.

**Comment by vsmenon** [comment]
I'll take a look at this.

**Comment by vsmenon** [comment]
This should be fixed now.
