### ISSUE TITLE
pkg/front_end/lib/src/fasta/README.md outdated

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#29000]
Getting started: We build a 64-bit version, then set-up environment variables for 32-bit version

Create an Outline File: Asked to run a file that doesn't exist.
```
dart pkg/front_end/lib/src/fasta/bin/outline.dart pkg/compiler/lib/src/dart2js.dart
```
 => doesn't exist
if we instead try to run
```
dart pkg/front_end/tool/fasta/outline.dart pkg/compiler/lib/src/dart2js.dart 
```
I get warnings and nits though it seems to work.

Create a Platform Dill File: Asked to run a file that doesn't exist.
If we instead run 
```
dart pkg/front_end/tool/fasta/compile_platform.dart platform.dill
```
I'm being told I'm holding it wrong. (also, the "Frequently used options" lists a "-o"  doesn't seem to match the usage "compile_platform [options] patched_sdk output").
Anyways, when compiling I get a platform.dill in out/ReleaseX64/patched_sdk/platform.dill --- I'll copy that to proceed.

Compiling a Program: Asked to run a file that doesn't exist.
If we instead run
```
dart pkg/front_end/tool/fasta/compile.dart pkg/front_end/test/fasta/hello.dart
```
it seems to work.
We're asked to run it using $DART_AOT_VM pkg/front_end/test/fasta/hello.dart.dill => now I finally feel that I setup environment variables for something I didn't compile... Updating that and it works...

Using dartk and the Analyzer AST: Asked to run a file that doesn't exist.
I can't seem to find a "kompile.dart" so I'll skip the rest here.

Running Tests:
Scanner gives me 
```
4 failed:
parser/pkg/front_end/test/fasta/function_type_recovery: Fail
parser/tests/language/bad_raw_string_test: Fail
parser/tests/language/generic_function_typedef2_test: Fail
parser/tests/language_strong/bad_raw_string_test: Fail
```

Then - running outline, compile, kompile and language - gives me
```
InputError: The environment variable 'DART_CONFIGURATION' isn't defined. It should be something like 'ReleaseX64', depending on which configuration you're testing.
```

Starting test test over with that set (i.e.
```
DART_CONFIGURATION=ReleaseX64 dart -c pkg/testing/bin/testing.dart --config=pkg/front_end/test/fasta/testing.json
```
) I get lots of output and it generally doesn't seem happy.

(and then it starts testing something that is very slow (226 passed tests and 1 failed test after ~6 minutes, totaling 1% out of the apparent 17000+ tests that is expected to pass) -- though now I'm digressing) 

Anyways --- it seems that the file is ripe for an update.
I could do some of it, but as I'm not sure that is actually still relevant I'm creating this issue instead.

/cc @peter-ahe-google

**Comment by peter-ahe-google** [comment]
Thank you. I've created a separate file that documents how to test Fasta, but this file still needs to be updated.

**Comment by peter-ahe-google** [comment]
Proposed fix: https://codereview.chromium.org/2740323002
