### ISSUE TITLE
Flutter Analyzer: error and hint reporting can obscure simple syntax errors

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#29005]
_From @HansMuller on March 9, 2017 19:31_

If you remove the trailing comma from line 53 in examples/flutter_gallery/lib/demo/shrine/shrine_data.dart, 360 errors and 146 hints are generated. No error is reported on line 53.

```
const List<Product> _allProducts = const <Product> [
  const Product(
    name: 'Vintage Bluetooth Radio' // line 53 OOPS
    imageAsset: 'packages/flutter_gallery_assets/shrine/products/radio.png',
    ...
  ),
  ...
];
```
Ideally there'd just be one error report, for line 53.

_Copied from original issue: flutter/flutter#8682_

**Comment by pq** [comment]
_From @Hixie on March 9, 2017 20:6_

This should be filed in the https://github.com/dart-lang/sdk/issues/new repo.

**Comment by pq** [comment]
@bwilkerson : is this an easy opportunity for improved parser recovery?

**Comment by pq** [comment]
Relevant fix in flight: https://codereview.chromium.org/2744043002/ 👍

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2744043002/
