### ISSUE TITLE
dart:html request onReadyStateChange stream receives type Event instead of ProgressEvent

### ISSUE THREAD

**Issue by manuelF** [dart-lang/sdk#29002]
# Describe your issue compiling with DDC
dart:html request onReadyStateChange stream receives type Event instead of ProgressEvent

# Does this error show up at build time or at run time?
Run time

# Include repro instructions. How can we try to build (or run) this code?
```dart
      final request = new HttpRequest();
      request.onReadyStateChange.listen((_) {
        print('hello')
      }
      request.open('post', "some valid url")
      request.send()
```

At runtime this code produces a type error, Listener for ProgressEvent receives type Event.
Workaround is to change onReadyStateChange to onLoad listener which works fine.

**Comment by manuelF** [comment]
Repro test:

import 'dart:html';
import 'package:test/test.dart';

void main() {
  test('http works', () {
    final request = new HttpRequest();
    request.onReadyStateChange.listen((_) {});
    request.open('post', 'nowhere');
    request.send('');
  });
}

**Comment by Blimster** [comment]
Any update to this issue?

**Comment by vsmenon** [comment]
Dug into this a bit.  It looks like a type error in `dart:html` introduced in the generation scripts:

https://github.com/dart-lang/sdk/blob/master/tools/dom/scripts/htmleventgenerator.py#L234

I see nothing in the DOM specs that suggests this should have ever been a `ProgressEvent`.

**Comment by vsmenon** [comment]
@alan-knight @terrylucas  I'm having problems running `go.sh` - can one of you please change the line above to:

```
  'XMLHttpRequest.readystatechange': ('readyStateChange', 'Event'),
```

and regen?

**Comment by vsmenon** [comment]
@terrylucas - I couldn't get this to work (running `go.sh`) in linux or mac.

**Comment by vsmenon** [comment]
@terrylucas - is this still an open?

**Comment by terrylucas** [comment]
Its part of this CL https://dart-review.googlesource.com/c/sdk/+/24501

Which is the Chrome 63 roll (pretty big but the event fires and the tests/lib_2/html/xhr_test.dart is now fixed and passes.
