### ISSUE TITLE
co19/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01 is slow

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#29010]
This has timed out a couple times today ([example](https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-safari-1-3-be/builds/4114/steps/dart2js%20safari%20co19%20tests/logs/stdio), [example](https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-safari-1-3-be/builds/4119/steps/dart2js%20safari%20co19%20fast-startup%20tests/logs/stdio)). Normally I'd just mark it slow, but it's in the "fast" directory which suggests that it's not supposed to be slow.

**Comment by sigmundch** [comment]
I wonder if this is really a flaky test - maybe something for co19 folks to investigate?

When the test passes, the test takes maybe 6 seconds:
```
0:00:06.257230 - dart2js - dart2js-safari release_x64/co19/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01
```

so this timeout could be that something is failing but it is being reported as a Timeout by the test infrastructure for some reason?

Maybe we can mark it 'Pass, Timeout' for now?

/cc @alan-knight

**Comment by alan-knight** [comment]
Yes, it might be something to file a co19 bug against, although it consistently passes locally for me, and quickly, so it's not clear how much they can do about something that's only happening on our bots. It's an event test, so I assume that when it times out the event just isn't getting received. Or maybe it's crashing in a way that doesn't get reported. Sigh.

**Comment by athomas** [comment]
LayoutTests have been deleted.
