### ISSUE TITLE
Improve Future API

### ISSUE THREAD

**Issue by Aetet** [dart-lang/sdk#29026]
It will be useful if Future will has API for retrieve current status of Future and sync value if it is resolved or rejected.

It may be need for UI frameworks like angular for example, where we need avoid async code for templates and treated like sync:

```
Future apiRequest = someRequest();
<div *ngIf="apiRequest.status == Future.Loading">
Loading indicator
</div>
<div *ngIf="apiRequest.status == Future.Resolved">
   Show your result {{apiRequest.getValue()}}
</div> 
```

Proposal for promise API:
https://github.com/thejameskyle/proposal-promise-access-internal-fields

**Comment by lrhn** [comment]
The `Future` class is intended for asynchronous use, and adding a way to *also* use it asynchronously isn't something we want to do - it's just complicating the API without giving you more power than you already have. It's also something that every implementation of `Future` will have to implement as well.

It's preferable to put that burden only on the cases where the behavior is actually useful, which means providing  tools to capture the result of a future. The `Result` class in `package:async` does that:
```dart
import "package:async/async.dart";
...
var result;
Result.capture(future).then((v) { result = v; });
```
That will set `result` to the actual result when the future completes. Until then `result` is `null`.
You can wrap this in a class if you want to reuse the code, but it's so small that it's probably not necessary.

If you really want the same object to be both a `Future` and give access to the result synchronously, thenthe  class  `ResultFuture` from `package:async` does exactly that. It is itself still a  `Future`, wrapping and forwarding to the original, but it also stores the result (as a `Result`) when the future completes.
```dart
import "package:async/async.dart";

var something = new ResultFuture(future);
...
if (something.result != null && something.result.isValue) {
  print(something.asValue.value);
}
```

As an addition to the existing `Future` API, it's not something we plan to do.
