### ISSUE TITLE
False positive for "field could be final" lint

### ISSUE THREAD

**Issue by dave26199** [dart-lang/sdk#29029]
It appears to miss use of inline update in a return statement. In this code snippit it tells me _x could be final.

```
class C {
  int _x = 0;

  int getX() {
    return _x++;
  }
}
```

**Comment by alexeieleusis** [comment]
What version of the analyzer are you using? That bug was fixed earlier this week, probably need to wait for the next release.

Thanks for the report!

I'll check it anyway.

**Comment by pq** [comment]
This got fixed a bit ago, with a test here:

https://github.com/dart-lang/linter/blob/5d0797cea2f85a9a5416c2cc3fd2b29dbf9a0397/test/rules/prefer_final_fields.dart#L31

Cheers!
