### ISSUE TITLE
Fasta should accept URIs in part-of declarations.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29047]
A part-of declaration can be `part of "library-file.dart";`.
Change has now landed in VM, dart2js and (partly) analyzer.

The Fasta parser also needs to handle the grammar.

**Comment by jensjoha** [comment]
`$ cat library-file.dart
part 'part.dart';

main() {
  foo();
}

$ cat part.dart
part of "library-file.dart";

foo() => print("Foo!");

$ pkg/front_end/tool/fasta compile library-file.dart --strong
```

seems to work fine.

Can this issue be closed?
