### ISSUE TITLE
Case where dart2js doesn't produce setter (possibly due to Function yielded from sync*)

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/sdk#29046]
I have an example where dart2js does not produce a setter for a field where the setter is used, causing an error. I've attached an almost-minimal example [here](https://gist.github.com/anonymous/a5a00f3bd17767c78c0393e78ddcb4af).

When running the compiled javascript it will cause: `TypeError: test.set$foo is not a function`. If I use something other than a sync* (for example a List<_ConditionerFunc>) then it well create the setter, so I'm thinking it's related to sync*

Dart v1.22.1 on Linux (Arch). Fails on Chrome, works on Dartium.

**Comment by llamadonica** [comment]
Even more reduced case [here](https://gist.github.com/llamadonica/b3354cff87574915860ef5a54a48b27e)

**Comment by rakudrama** [comment]
This appears to be a global type inference bug.
The analysis thinks the yield-ed closure is never called.

**Comment by rakudrama** [comment]
Fixed via https://github.com/dart-lang/sdk/commit/a7a1811f18fe580e8876efed3ee1685800e678d5
