### ISSUE TITLE
Analyzer should improve error messages around part-of messages.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29048]
I have landed (and hope to see it stick) the CL that enables URIs in part-of declarations.

Previously, the only allowed syntax was: `part of library.name;` which required the library to have a library declaration. Now it's also possible to do `part of "library.dart";`, which means that you can have parts of libraries that have no library declaration.

To enable this, I flipped a flag in the analyzer, and disabled all warnings about libraries with `part` declarations an no `library` declaration.

The analyzer should warn if:
- A part-of file has a `part of library.name;` declaration and `library.name` isn't the name of the including library, or
- A part-of file has a `part of "string";` declaration, and the URI you get from resolving `string` with the part library's URI as base, is not that URI of the including library.

Some of these are not handled, because they bailed out at the "part in library with no name" case before.

**Comment by srawlins** [comment]
In the first case, the analyzer now has two warnings, one for an unnamed library, and one for a named library:

```none
Analyzing lib.dart...                  1.4s

  error • lib.dart:1:6 • The library is unnamed. A URI is expected, not a library name 'libb', in the part-of directive. Try changing the part-of directive to a URI, or try
          including a different part. • part_of_unnamed_library

1 issue found.
```

and

```
Analyzing lib.dart...                  1.4s

  error • lib.dart:3:6 • Expected this library to be part of 'lib', not 'libb'. Try including a different part, or changing the name of the library in the part's part-of
          directive. • part_of_different_library

1 issue found.
```

In the second case, the analyzer also produces a warning:

```
Analyzing lib.dart...                  1.4s

  error • lib.dart:3:6 • Expected this library to be part of 'file:///Users/srawlins/code/dart-sdk/sdk/lib.dart', not 'file:///Users/srawlins/code/dart-sdk/sdk/xx'. Try
          including a different part, or changing the name of the library in the part's part-of directive. • part_of_different_library

1 issue found.
```
