### ISSUE TITLE
Wrong coverage info

### ISSUE THREAD

**Issue by valotas** [dart-lang/sdk#29044]
Tried manually with Observatory but coveralls shows that too. At [line 9 of my tmpl.dart](https://coveralls.io/builds/10518995/source?filename=lib%2Fsrc%2Ftmpl.dart#L9) I have a miss while I do have a [test for it](https://github.com/valotas/mustache4dart/blob/issue55/coverage/test/mustache_test.dart#L88).

If I run only [`mustache_test.dart`](https://github.com/valotas/mustache4dart/blob/issue55/coverage/test/mustache_test.dart), I see the hit at the Obeservatory. If I run [`mustache_all.dart`](https://github.com/valotas/mustache4dart/blob/issue55/coverage/test/mustache_all.dart) I don't.

**Comment by a-siva** [comment]
A number of fixes have gone in since this issue was filed and the reproduction example is non null safe code.

**Comment by a-siva** [comment]
If the issue can be reproduced with newer code please open a new issue for it.
