### ISSUE TITLE
Re-enable default flutter analysis options in bazel workspace

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#29042]
As a stop-gap measure for our internal customers, I'm updating `dartanalyzer` and the analysis server so that they do not use the default flutter analysis options file, `package:flutter/analysis_options_user.yaml`, when analyzing in a bazel workspace.

This is less than ideal and I hope to work toward a better solution in the long term.

**Comment by danrubel** [comment]
Nope. That didn't work. 

Instead, I added an option to explicitly enable/disable using the default flutter analysis options file.
https://codereview.chromium.org/2745653012/

**Comment by srawlins** [comment]
Internal customers are now OK.
