### ISSUE TITLE
Weird line endings in many co19 tests

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29073]
I've noticed a number of co19 tests with weird line endings.

For example, `Language/Expressions/Identifier_Reference/built_in_not_dynamic_t01.dart`.

This is very confusing. When I `cat` this file, I see this:

```
main() {
} abstract foo;
```

However, the content of the file is really:

```
main() {
abstract foo;\r}
```

**Comment by whesse** [comment]
The people making the co19 tests are using Windows machines, so this sort of thing is happening.  We can file a co19 issue requesting they scan the entire codebase, and fix these.

**Comment by peter-ahe-google** [comment]
I've filed https://github.com/dart-lang/co19/issues/113.
