### ISSUE TITLE
MessageEventInit error on FF

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29071]
A couple tests started failing recently on FF with the following error:

Firefox 52.0.0 (Mac OS X 10.12.0)  lib/html/messageevent_test FAILED
	'ports' member of MessageEventInit can't be converted to a sequence.
	new@lib/js/amd/dart_sdk.js:77536:16
	messageevent_test.main/<@gen/codegen_output/lib/html/messageevent_test.js:13:19
	minitest.test@gen/codegen_output/pkg/expect.js:442:7
	messageevent_test.main@gen/codegen_output/lib/html/messageevent_test.js:12:5
	@test/browser/language_tests.js:820:24
	
Firefox 52.0.0 (Mac OS X 10.12.0)  lib/html/serialized_script_value_test FAILED

**Comment by jmesserly** [comment]
I don't see any current failures in the status for this test. Going to assume stale
