### ISSUE TITLE
Analyzer gives erroneous warning for regress_29025_test

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#29081]
The analyzer should not give a StaticWarning for the test language/regress_29025_test.dart:

FAILED: dart2analyzer-none release_x64 language/regress_29025_test
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|ARGUMENT_TYPE_NOT_ASSIGNABLE|/usr/local/google/home/regis/dart3/sdk/tests/language/regress_29025_test.dart|24|13|2|The argument type 'F(D) → D' can't be assigned to the parameter type 'D'.
WARNING|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/regis/dart3/sdk/tests/language/regress_29025_test.dart|26|12|7|A value of type 'E' can't be assigned to a variable of type 'F(E) → E'.
WARNING|STATIC_WARNING|ARGUMENT_TYPE_NOT_ASSIGNABLE|/usr/local/google/home/regis/dart3/sdk/tests/language/regress_29025_test.dart|27|13|2|The argument type 'F(E) → E' can't be assigned to the parameter type 'E'.

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseX64 sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/usr/local/google/home/regis/dart3/sdk/.packages --format=machine --no-hints /usr/local/google/home/regis/dart3/sdk/tests/language/regress_29025_test.dart
Took 0:00:02.299718

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2analyzer -rnone -t240 language/regress_29025_test

typedef T F<T>(T t);

class B<T extends F<T>> {}
class C<T extends F<C<T>>> {}

class D extends B<D> {
  D foo(D x) => x;
  D call(D x) => x;
  D bar(D x) => x;
}

class E extends C<E> {
  C<E> foo(C<E> x) => x;
  C<E> call(C<E> x) => x;
  C<E> bar(C<E> x) => x;
}

main() {
 F<D> fd = new D();
 var d = fd(fd);
 print(d);
 F<E> fe = new E();
 var e = fe(fe);
 print(e);
}

**Comment by fishythefish** [comment]
This should be fixed due to https://dart-review.googlesource.com/c/sdk/+/116141.
