### ISSUE TITLE
ReloadSources: import 'asd'; crashes Dart VM

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#29085]
When I reload sources after adding `import 'asd';`, the VM crashes with 
"Process finished with exit code 132 (interrupted by signal 4: SIGILL)"

It would be nice to catch this and not die.

(`import 'dart:asd'` fails gracefully with 'The built-in library 'dart:asd' is not available on the stand-alone VM.')

Thanks,
 Andreas

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2748353004

**Comment by BlackHC** [comment]
Thank you!
