### ISSUE TITLE
stdin should have a hasTerminal property

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29083]
`stdout` does have `hasTerminal`, but `stdin` doesn't. Seems like an oversight since it is possible that one is connected to a terminal and the other one isn't.

Checking if `stdin` is connected to a terminal is particularly important for setting `echoMode` or `lineMode`, which (at least on Windows) throw an exception if `stdin` is not connected to a terminal.

/cc @zanderso

**Comment by tvolkert** [comment]
Just ran into the need for this in automated tests within Google - can we bump the priority from `P3` to something higher?

**Comment by zanderso** [comment]
I agree we should add `hasTerminal` to `stdin` for the sake of uniformity. As a workaround, does `stdioType(stdin)` help?

**Comment by tvolkert** [comment]
```
FileSystemException: Error retrieving socket type, path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:46)
#1      _StdIOUtils._socketType (dart:io-patch/stdio_patch.dart:39)
#2      stdioType (dart:io/stdio.dart:401)
```

**Comment by tvolkert** [comment]
It's possible that the VM was in the process of shutting down in the most recent stack trace, and that it affected the ability to call `stdioType()`

```
FileSystemException: Error retrieving socket type, path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:46)
#1      _StdIOUtils._socketType (dart:io-patch/stdio_patch.dart:39)
#2      stdioType (dart:io/stdio.dart:401)
#3      AnsiTerminal.singleCharMode= (package:flutter_tools/src/base/terminal.dart:66)
#4      ResidentRunner._resetTerminal (package:flutter_tools/src/resident_runner.dart:752)
#5      ResidentRunner._cleanUpAndExit (package:flutter_tools/src/resident_runner.dart:565)
```

**Comment by zanderso** [comment]
That exception indicates that there is a problem with the underlying file descriptor. For example the other end of the pipe is closed, which eventually results in the `onDone` callback to `stdin.listen` being called. That could be the case if your program is ending.

**Comment by tvolkert** [comment]
You can reproduce this easily in the Flutter repo:

```
$ git clone git@github.com:flutter/flutter.git
$ cd flutter/examples/hello_world
$ echo "q"|../../bin/flutter run
```
