### ISSUE TITLE
analyzer machine format does not escape newlines

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#29095]
`STRONG_MODE_COULD_NOT_INFER` might be the first analyzer error [with newlines in the message](https://github.com/dart-lang/sdk/blob/strong_mode_inference/pkg/analyzer/lib/src/generated/type_system.dart#L2040..L2066). These do not get escaped in the `--format=machine` output of analyzer:

```
ERROR|COMPILE_TIME_ERROR|STRONG_MODE_COULD_NOT_INFER|/blah.dart|787|20|10|Couldn't infer type parameter 'T'.

Inferred type 'dynamic' does not work with constraints:
  Argument 'prCr' inferred as '(dynamic, CoOp, LaVa<dynamic>) → EnSiSeClPr' must be a '(F, CoOp, T) → P'.
The type 'dynamic' was inferred from:
  Return type declared as 'FiTy<F, T, P>' used where a 'FiTy<dynamic, dynamic, CoPr<dynamic>>' is required.

Consider passing explicit type argument(s) to the generic.
```

I'm hoping that processors of the machine format are not expected to handle these. Newlines are supposed to be the record separator in this format. Instead maybe encode `\n`?

**Comment by srawlins** [comment]
CC @jmesserly @skybrian @bwilkerson

**Comment by bwilkerson** [comment]
Is this is creating problems for you? (Does it need to be a P1 issue?)

**Comment by skybrian** [comment]
Sounds like it. It will break our analyzer tests whenever this error appears, since the parser will give up.

(Longer term, this is a good reason to switch to JSON.)

**Comment by bwilkerson** [comment]
(We won't switch, for backward compatibility reasons, but we could add a new 'json' format.)

**Comment by jmesserly** [comment]
Thanks! I can take a look at this since it's related to my CL.

**Comment by jmesserly** [comment]
@skybrian I can escape these pretty easily, but is there any way to verify that my fix works? Where does the code that consumes machine format live?

**Comment by bwilkerson** [comment]
You could get a first approximation by running analyzer with `--format=machine` on a file that will produce a multi-line error message and see whether it outputs `\n` in place of line feeds.

**Comment by srawlins** [comment]
This issue is high priority for me, but I can also do the fix, if called upon. I also just wanted to make sure of the answer on whether the machine format _should_ escape those newlines (looks like no one is objecting to that).

If `\n` is replaced with `\\n`, then we can unescape it when parsing the machine output (same as if the message has `\\|` in it).

**Comment by jmesserly** [comment]
yeah, that sounds right @srawlins

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2770493003
