### ISSUE TITLE
Please, clarify EventSink description

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29099]
The interface [EventSink ](https://api.dartlang.org/stable/1.21.1/dart-async/EventSink-class.html)declares the following methods:

> void add( T event )
> Send a data event to a stream.
> 
> void addError( errorEvent, [ StackTrace stackTrace ])
> Send an async error to a stream.
> 
> void close()
> Close the sink. **No further events can be added after closing**.

It is not clear what will happen if `add` or `addError` is called after the event sink is closed.
Whether supplied events will be silently ignored or some exception will be thrown?
Or may be implementors of the interface are free to select the behavior?

Also description of `close` mention only events, but not errors.

**Comment by natebosch** [comment]
We now say "Must not be called on a closed sink."

Should we explicitly call out what will happen if you do? cc @lrhn

**Comment by lrhn** [comment]
No. We use the term "must not" for anything that isn't allowed. It most likely means that an `Error` will be thrown, but we prefer to not overspecify error condition.

**Comment by natebosch** [comment]
Sounds good. In that case I don't think there is anything else to do here.
