### ISSUE TITLE
issue21159_test crashed on VM.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29094]
Issue21159_test just crashed on the buildbot.
See attached core file and the tar.gz.

https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-reload-rollback-be/builds/3438/steps/checked%20vm%20tests/logs/stdio

```
FAILED: none-vm-checked release_x64 language/issue21159_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
../../runtime/vm/isolate.h: 455: error: Mismatched number of calls to disable_background_compiler and enable_background_compiler.
Dumping native stack trace for thread 36b5
Stack dump aborted because GetAndValidateThreadStackBounds.


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --enable_asserts --enable_type_checks --hot-reload-rollback-test-mode --ignore-unrecognized-flags --packages=/b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/.packages /b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/language/issue21159_test.dart
Took 0:00:01.043648

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked --hot-reload-rollback -t60 --builder-tag no_ipv6 language/issue21159_test



--- Uploading into gs://dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/ (https://storage.cloud.google.com/dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'core.13993.tar.gz', 'gs://dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/core.13993.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/core.13993.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/core.13993.tar.gz)
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'release_x64_dart.tar.gz', 'gs://dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/release_x64_dart.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/release_x64_dart.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/23dd9380-9c3f-443c-bf86-f086e3b02d25/release_x64_dart.tar.gz)
--- Done ---
```
[core.13993.tar.gz](https://github.com/dart-lang/sdk/files/848731/core.13993.tar.gz)
[release_x64_dart.tar.gz](https://github.com/dart-lang/sdk/files/848732/release_x64_dart.tar.gz)

**Comment by crelier** [comment]
The test language/issue_22780_test/01 is apparently causing the same issue.

**Comment by johnmccutchan** [comment]
@fsc8000 can you take a look at this?

**Comment by a-siva** [comment]
Thread 1 (Thread 0x7f8b6b79b700 (LWP 14005)):
#0  0x00007f8b6c304c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f8b6c308028 in __GI_abort () at abort.c:89
#2  0x0000000000861b59 in dart::OS::Abort () at ../../runtime/vm/os_linux.cc:421
#3  0x0000000000678546 in dart::DynamicAssertionHelper::Fail (
    this=0x7f8b6b6a3bd0, format=<optimized out>)
    at ../../runtime/platform/assert.cc:42
#4  0x00000000006b887e in enable_background_compiler (this=0x2dfd400)
    at ../../runtime/vm/isolate.h:453
#5  dart::BackgroundCompiler::Enable () at ../../runtime/vm/compiler.cc:2118
#6  0x00000000007a367a in dart::IsolateReloadContext::Reload (
    this=<optimized out>, 
    force_reload=<error reading variable: access outside bounds of object referenced via synthetic pointer>, root_script_url=<optimized out>, 
    packages_url_=<optimized out>) at ../../runtime/vm/isolate_reload.cc:653
#7  0x000000000079beb1 in dart::Isolate::ReloadSources (this=0x2dfd400, 
    js=<optimized out>, force_reload=true, 
    root_script_url=0x6 <error: Cannot access memory at address 0x6>, 
    packages_url=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, 
    dont_delete_reload_context=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at ../../runtime/vm/isolate.cc:1104
#8  0x00000000009ae271 in DRT_HelperStackOverflow (isolate=<optimized out>, 
    thread=<optimized out>, zone=<optimized out>, arguments=...)
    at ../../runtime/vm/code_generator.cc:1628
#9  dart::DRT_StackOverflow (arguments=...)
---Type <return> to continue, or q <return> to quit---
    at ../../runtime/vm/code_generator.cc:1544
#10 0x00007f8b6d55f61b in ?? ()
#11 0x0000000001acc900 in ?? ()
#12 0x0000000000000000 in ?? ()

**Comment by fsc8000** [comment]
@johnmccutchan Didn't https://codereview.chromium.org/2759933005/ fix this?
