### ISSUE TITLE
Odd output of pub in Git Bash and Cygwin on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29102]
```
goderbauer@eseidel0-w MINGW64 /c/src/flutter/dev/tools (master)
$ pub.bat get
find: ‘>     bin [’: No such file or directory
Resolving dependencies...
Got dependencies!
```

The output `find: ‘>     bin [’: No such file or directory` seems odd. Other than that, it seems to work as expected.

**Comment by goderbauer** [comment]
Related: https://github.com/flutter/flutter/issues/8860.

**Comment by kevmoo** [comment]
Has this changed w/ the new windows stdout/err work?

**Comment by goderbauer** [comment]
> Has this changed w/ the new windows stdout/err work?

Nope. Previous Dart versions also had the same problem.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1540
