### ISSUE TITLE
In 1.23.0-dev.9.0 Ctrl+C doesn't work on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29104]
It's all in the title. I am running the following script on Windows Version 10.0.14393 and I am unable to exit out of it with Ctrl+C:

```dart
import 'dart:async';

main() async {
  while(true) {
    print(1);
    await new Future.delayed(new Duration(seconds: 1));
  }
}
```
In addition to that, when I register a ProcessSignal handler for SIGINT it is never called when pressing Ctrl+C.

/cc @zanderso

**Comment by zanderso** [comment]
This does not repro on Windows 7. I'll give it a shot on Windows 10 later today.

**Comment by goderbauer** [comment]
I just tried it on my other Windows 10 machine: same problem.

**Comment by zanderso** [comment]
The documentation does not mention this, but it appears as though `ENABLE_PROCESSED_INPUT` is ignored when `ENABLE_VIRTUAL_TERMINAL_INPUT` is set. We will probably have to disable `ENABLE_VIRTUAL_TERMINAL_INPUT` to restore the correct Ctrl+C behavior.
