### ISSUE TITLE
Strong mode gives odd const-related errors when using aliased imports

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#29109]
Bug is reproducible on all versions from `1.23.0-dev.0.0` to `1.23.0-dev.9.0`.

**.analysis_options**
```yaml
analyzer:
  strong-mode: True
```

**lib1.dart**
```dart
import 'lib2.dart';

const q = const <int, MyClass>{0: const MyClass()};
```

**lib2.dart**
```dart
import 'lib3.dart' as lib3;

class MyClass {
  final int param;
  const MyClass([this.param = lib3.value]);
}
```

**lib3.dart**
```dart
const int value = 12345;
```

---

The sources above give the following analyzer output (line number is always 1):
```
ERROR: The values in a const map literal must be constant. (lib1.dart:1)
ERROR: Invalid constant value. (lib1.dart:1)
ERROR: Const variables must be initialized with a constant value. (lib1.dart:1)
```

There're no errors when importing `lib3.dart` without alias.

**Comment by bwilkerson** [comment]
Not only should these errors not be produced, but they are being associated with the wrong location.

**Comment by apwilson** [comment]
I'm also getting the "Invalid const error" on some comments I have at the top of my dart file.

**Comment by scheglov** [comment]
There are three problems here.

1. We don't evaluate `lib3.value` constant correctly because when we resynthesize we don't set the element for `lib3`.

2. When we evaluate `const MyClass()` in `lib1.dart`, we walk to the `MyClass` const constructor in `lib2.dart`, and report the (1) problem using the `ErrorReporter` for `lib1.dart`.

3. When we summarize and resynthesize, we don't store offsets of AST nodes, so we actually cannot report problems at correct locations.

**Comment by scheglov** [comment]
[The CL](https://codereview.chromium.org/2815713003) for fixing prefix element resynthesis.

This does not change (2) or (3).

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/38e8b1509e8c983cd454c86d1f10561dc0de1ae0

**Comment by pylaligand** [comment]
I just tested this change with @apwilson's files and we still get `ERROR: Invalid constant value. (my_file.dart:1)`.

**Comment by scheglov** [comment]
@pylaligand Which SDK version did you try?

**Comment by pylaligand** [comment]
Just built the full SDK from sources while sync'd at your change.

**Comment by scheglov** [comment]
I cannot reproduce, there are no errors with the latest SDK on the test case from the first comment.

**Comment by pylaligand** [comment]
Ok, filed https://github.com/dart-lang/sdk/issues/29358 instead.

**Comment by lexaknyazev** [comment]
Will this be merged into 1.23 release?

**Comment by scheglov** [comment]
Given than RC0 was just published, probably not. @mit-mit

**Comment by mit-mit** [comment]
Is this a regression from the previous stable release (1.22)?

**Comment by lexaknyazev** [comment]
@mit-mit 
Yes.

**Comment by mit-mit** [comment]
@scheglov why what there no merge request for this?

Also, can you elaborate why the fix only is for problem 1, and not 2 and 3?

**Comment by scheglov** [comment]
It was deemed to be a rare problem. We went through almost the whole two releases internally without anyone reporting anything like this.

(2) was fixed as https://github.com/dart-lang/sdk/commit/19353f9e633313e9b7452a51e9a80b09a16d25f0.

(3) might be a problem for some users of analysis APIs, but is not a problem for analyzer_cli and analysis_server.

**Comment by mit-mit** [comment]
We may need a 1.23 patch release, so please file a merge bug

**Comment by scheglov** [comment]
OK, I've opened a merge request.

**Comment by whesse** [comment]
We are nearing the release of 1.24, without having made a 1.23 patch release and merged this.
Is it ok to wait an estimated 1-2 weeks for the release of 1.24 to get this in? It is already in for internal users.
