### ISSUE TITLE
Kernel unittest expectations need rebase after dartformatting

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29114]
After CL https://codereview.chromium.org/2747113004, the kernel unit tests fail because they have
some expectation files specifying line numbers in the kernel source.  Please run the scripts to
create new baselines for these tests.

The first error of this type, from the builder pkg-linux-release-be, is:

FAILED: none-vm-checked release_x64 pkg/kernel/test/baseline_strong_mode_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 +0: external.dart
[error] dynamic is not a subtype of dart.async::_BroadcastSubscription (dart:async/broadcast_stream_controller.dart:327:9)
[error] dynamic is not a subtype of dart.async::_BroadcastSubscription (dart:async/broadcast_stream_controller.dart:334:9)
00:12 +1: covariant_generic.dart
00:14 +2: store_load.dart
00:15 +3: arithmetic.dart
00:16 +4: redirecting_factory.dart
00:17 +5: DeltaBlue.dart
00:18 +6: fallthrough.dart
00:19 +7: escape.dart
00:20 +8: unused_methods.dart
00:21 +9: static_setter.dart
00:21 +10: uninitialized_fields.dart
00:22 +11: null_aware.dart
00:23 +12: named_parameters.dart
00:24 +13: optional.dart
00:25 +13 -1: optional.dart
  Output of `optional.dart` changed for strong-mode.
  Command to reset the baseline:
    rm pkg/kernel/testcases/strong-mode/optional.baseline.txt
  Command to see the diff:
    diff -cd pkg/kernel/testcases/strong-mode/optional.{baseline,current}.txt
  
  package:test                                fail
  pkg/kernel/test/baseline_tester.dart 78:13  runBaselineTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                  _Completer.completeError
  pkg/kernel/test/baseline_tester.dart 86:7   runBaselineTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                  _asyncThenWrapperHelper
  pkg/kernel/test/baseline_tester.dart 40:27  runBaselineTests.<fn>

**Comment by mkustermann** [comment]
Fixed by ad7d04f76aefb1b031d08a2e8b7646f7875245f5
