### ISSUE TITLE
Line markers 'Has implementations', 'Is overridden' do not work since SDK 1.23

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#29113]
Analysis Server never sends [analysis.implemented](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#notification_analysis.implemented) notification (SDK 1.23-dev.9.0).

**Comment by johnpryan** [comment]
FWIW, this is causing https://youtrack.jetbrains.com/issue/WEB-26628

**Comment by scheglov** [comment]
Enabling, even if not very efficient.
https://codereview.chromium.org/2942753002

See also https://github.com/dart-lang/sdk/issues/28880
