### ISSUE TITLE
Why allow multiple combinators in importSpecification?

### ISSUE THREAD

**Issue by gabrc** [dart-lang/sdk#29116]
According to the *Dart Language Specification*, **importSpecification** allows multiple **combinator**s. This is also allowed by the compiler. 

However, there does not seem to be any good reason to use multiple combinators. Should the use of multiple combinators be deprecated?

**Comment by lrhn** [comment]
There is never a need for more than one combinator, as long as we only have the current combinators.

It's not a problem, though, so we have no plan to change it.
If we ever add more combinators, say a "rename" combinator, then it might become useful to have more than one.
