### ISSUE TITLE
resolveSymbolicLinksSync always throws on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29117]
`resolveSymbolicLinksSync ` seems to always throw an exception on Windows. As an example I have the following program in `test.dart`:

```dart
import 'dart:io';

main() {
  var f = new File('test.dart');
  print(f.resolveSymbolicLinksSync());
}
```

When executed on Windows 10.0.14393 it throws the following exception:
```
Unhandled exception:
FileSystemException: Cannot resolve symbolic links, path = 'test.dart' (OS Error: The system cannot find the file specified.
, errno = 2)
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:678)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:346)
#2      main (file:///C:/src/test.dart:5:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Flutter users are running into this issue, see https://github.com/flutter/flutter/issues/8882.
Possibly related to https://github.com/dart-lang/sdk/issues/29096.

**Comment by goderbauer** [comment]
Giving an absolute path doesn't throw. The following works as expected:

```dart
var f = new File('C:\\src\\test.dart');
print(f.resolveSymbolicLinksSync());
```

This also works as expected:

```dart
var f = new File('test.dart');
print(f.absolute.resolveSymbolicLinksSync());
```

Looks like just relative paths don't work on Windows? They seem to work on my Linux machine, though.

**Comment by zanderso** [comment]
This doesn't reproduce on Windows 7. I'll be able to try on a Windows 10 machine later today or early next week.

**Comment by zanderso** [comment]
I haven't been able to get this to reproduce on Windows 10, either. @goderbauer Could you give some more detailed instructions?

**Comment by goderbauer** [comment]
It's working for me as well today... Sorry for the trouble, I am closing this.
