### ISSUE TITLE
Use trained snapshot to build DDC in SDK

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29119]
DDC is currently not trained (actually trained on help).  

I tried training it on itself, but had to revert due to a DDC windows bug:

https://github.com/dart-lang/sdk/commit/1bd92d4f04f44aa00ce63345cd161d5fa773fab0

**Comment by vsmenon** [comment]
This was the win break:
```
[1/5] ACTION //utils/dartdevc:dartdevc(//build/toolchain/win:x86)
FAILED: gen/dartdevc.dart.snapshot 
E:/b/depot_tools/python276_bin/python.exe ../../build/gn_run_binary.py compiled_action dart.exe --packages=E:/b/build/slave/dart-sdk-windows-be/build/sdk/.packages --snapshot=E:/b/build/slave/dart-sdk-windows-be/build/sdk/out/ReleaseIA32/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/ --unsafe-force-compile -o out.js ../../pkg/dev_compiler/bin/dartdevc.dart
Command failed: ./dart.exe --packages=E:/b/build/slave/dart-sdk-windows-be/build/sdk/.packages --snapshot=E:/b/build/slave/dart-sdk-windows-be/build/sdk/out/ReleaseIA32/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/ --unsafe-force-compile -o out.js ../../pkg/dev_compiler/bin/dartdevc.dart

output: We're sorry, you've found a bug in our compiler.


You can report this bug at:


    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler


Please include the information below in your report, along with


any other information that may help us track it down. Thanks!


    dartdevc arguments: --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/ --unsafe-force-compile -o out.js ../../pkg/dev_compiler/bin/dartdevc.dart


    dart --version: 1.23.0-edge.9f2668c9987f0a86cac9cd46c5e3418df22e9f38 (Mon Mar 20 14:52:56 2017) on "windows_ia32"


```


Invalid library root. E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/\ does not contain E:\b\build\slave\dart-sdk-windows-be\build\sdk\pkg\dev_compiler\bin\dartdevc.dart


#0      jsLibraryName (package:dev_compiler/src/compiler/code_generator.dart:5950:5)


#1      CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:271:32)


#2      CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:195:18)


#3      ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:218:26)


#4      _compile (package:dev_compiler/src/compiler/command.dart:182:25)


#5      compile (package:dev_compiler/src/compiler/command.dart:60:5)


#6      main (file:///E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)


<asynchronous suspension>


#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)


#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by vsmenon** [comment]
@jakemac53 - fyi

**Comment by jakemac53** [comment]
It ended up being quite easy to write a basic driver that can run ddc as a worker (basically just implements the bazel side of the protocol), and I am getting a significant performance improvement from doing that versus running ddc as an app snapshot, so this is no longer a blocker.
