### ISSUE TITLE
Determine locale from Dart

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29126]
On Linux and MacOS you can read the env variable `LANG` to get the current locale (e.g. `en-us`), but no good way exists to do this on Windows. Can a function for this be added to Dart's standard library?

Background: In Flutter we are seeing reports of crashes on certain language versions of Windows and it would be good if we could report what language a user is using in our analytics.

It also seems like a call like this will be needed to make `package:intl` and `package:usage` work properly on Windows:
- https://github.com/dart-lang/intl/issues/12
- https://github.com/dart-lang/usage/issues/100

**Comment by zanderso** [comment]
`Platform.localeName` will be in the first 1.24 dev release, and should be used by platform:intl shortly thereafter.
