### ISSUE TITLE
Inconsistencies in descriptions of classes and interfaces in dart:async package

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29122]
The following interfaces are defined in the [dart:async](https://api.dartlang.org/stable/1.21.1/dart-async/dart-async-library.html) package (only essential information is cited):

> EventSink&lt;T&gt;
> **Implements Sink&lt;T&gt;**
> An interface that abstracts creation or handling of Stream events.
> 
> add(T event) → void
> Send a data event **to a stream.**
> addError(errorEvent, [ StackTrace stackTrace ]) → void
> Send an async error **to a stream.**
> close() → void
> Close the sink. No further events can be added after closing.

- Interface `Sink` is described as "A generic destination for data." So it would be logical to expect `EventSink` to be destination for events (data and errors) as well instead of "abstraction for creation and handling Stream events". 
- It is not clear what stream is mentioned in methods descriptions. Judging by description `EventSink` is not related to any stream.

> StreamConsumer&lt;S&gt;
> Abstract interface for a "sink" accepting multiple entire streams.
> 
> A consumer can accept a number of consecutive streams using addStream, and when no further data need to be added, the close method tells the consumer to complete its work and shut down.
> 
> **This class is not just a Sink<Stream> because it is also combined with other Sink classes, like it's combined with EventSink in the StreamSink class.**
> 
> The Stream.pipe accepts a StreamConsumer and will pass the stream to the consumer's addStream method. When that completes, it will call close and then complete its own returned future.
>
> addStream(Stream&lt;S&gt; stream) → Future
> Consumes the elements of stream.
> close() → Future
> Tells the consumer that no further streams will be added.

The highlighted sentence looks strange. `StreamConsumer` is not a descendant of `Sink` and essential methods are different. 

>StreamSink&lt;S&gt;
>Implements:  EventSink&lt;T&gt;, StreamConsumer&lt;S&gt;
> A object that accepts stream events both synchronously and asynchronously.
> 
> **A StreamSink unifies the asynchronous methods from StreamConsumer and the synchronous methods from EventSink.**

The highlighted sentence is confusing. Methods of `StreamConsumer` are synchronous, but events are handled by `StreamConsumer` asynchronously. Methods of `EventSink` are synchronous and, according to `EventSink`description, there are no requirements to handle events either synchronously or asynchronously. Both ways are allowed for `EventSink` implementations.

> StreamController&lt;T&gt;
> Implements: StreamSink&lt;T&gt;
>A controller with the stream it controls.
>This controller allows sending data, error and done events on its stream. This class can be used to create a simple stream that others can listen on, and to push events to that stream.

It is not mentioned how events are handled or published. Since `StreamController` implements `StreamSink` one might think that `add` and `addError` publish events synchronously, while `addStream` publish events asynchronously (i.e. on arrival from another stream). However

> SynchronousStreamController&lt;T&gt;
> A stream controller that delivers its events synchronously.
> 
> A synchronous stream controller is intended for cases where an already asynchronous event triggers an event on a stream.
> 
> Instead of adding the event to the stream in a later microtask, causing extra latency, the event is instead fired immediately by the synchronous stream controller, as if the stream event was the current event or microtask.
>
> add(T data) → void
> **Adds event to the controller's stream.**
> addError(Object error, [ StackTrace stackTrace ]) → void
> **Adds error to the controller's stream.**
> addStream(Stream<T> source, { bool cancelOnError: true }) → Future
> **Receives events from source and puts them into this controller's stream.**

- Now it becomes clear that `StreamController` publish events asynchronously, right? 
- Descriptions of `add`, `addError`, `addStream` do not mention about synchronous event handling. Probably only `addStream` is synchronous.

P.S. Sorry for long quotes, but it is necessary to put everything together to see the inconsistencies.

**Comment by floitschG** [comment]
Thanks! These comments are very much appreciated (even if we are sometimes slow to respond).

I uploaded https://codereview.chromium.org/2822173002/ (which has also a change for throwing when the sink is closed).

**Comment by floitschG** [comment]
Had to revert.
