### ISSUE TITLE
pkg/analy*/.../check_all_test failing after reformat of source files

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29133]
After the CL, , which reformatted source files, some tests that check expected sources are failing.  Please update the expectations of these tests, and then re-enable them in pkg/pkg.status.  They only seem to fail on linux.

The failing tests are at least:
pkg/analysis_server/tool/spec/check_all_test
pkg/analyzer_plugin/tool/spec/check_all_test
pkg/analyzer/tool/summary/check_test

and the test output is like:

FAILED: none-vm-checked release_x64 pkg/analyzer_plugin/tool/spec/check_all_test
Expected: Pass 
Actual: Fail
CommandOutput[vm]:

stdout:
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/lib/protocol/protocol_generated.dart' does not have expected contents.
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/test/integration/support/integration_test_methods.dart' does not have expected contents.
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/test/integration/support/protocol_matchers.dart' does not have expected contents.
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/lib/protocol/protocol_constants.dart' does not have expected contents.
Please regenerate using:
  out/ReleaseX64/dart-sdk/bin/dart /b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/tool/spec/generate_all.dart

Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/build/slave/pkg-linux-release-be/build/sdk/.packages /b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/tool/spec/check_all_test.dart
Took 0:00:07.349551

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 --use-sdk pkg/analyzer_plugin/tool/spec/check_all_test

**Comment by whesse** [comment]
Duplicate of #29134

**Comment by whesse** [comment]
Issue #29134 doesn't list the two other failing tests, or the status file that needs to be updated when it is fixed.

**Comment by bwilkerson** [comment]
It includes both CLs that need to be reverted in order for the issue to be closed. I'd really prefer to have a single issue for this one problem. If you think it would be useful, then please copy the other failing test information to that issue.
