### ISSUE TITLE
Build DDC SDK as part of regular build process

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29139]
We currently build the DDC SDK artifacts (e.g., dart_sdk.js and corresponding sum file) as part of our presubmit script (pkg/dev_compiler/tool/build_sdk.sh).  We later copy these files as part of the SDK build into the generated output directories.

We should just build it as part of the SDK build in the first place and stop checking in the generated artifacts into the repo.

**Comment by jmesserly** [comment]
depending on when @munificent is free to look at this I might, because it's getting really painful since we unforked our SDK and added inline source maps. (breaks code review tool, causes merge failures every time, etc)

**Comment by vsmenon** [comment]
Bob has a CL in progress:

https://codereview.chromium.org/2794133002/

:-)

**Comment by jmesserly** [comment]
yeah ... it doesn't actually remove build_sdk or change our tests to run against the SDK tho, so it won't help until we get some follow ups.

**Comment by dgrove** [comment]
Any updates here?

**Comment by munificent** [comment]
Nothing huge. My in-progress CL has a lot of the right stuff in there, but is missing pieces too (chiefly, it doesn't get the tests using the built SDK).

I have a local CL that gets a stub GN step in place that only copies the checked in SDK to the location where it *will* be built to, and then has create_sdk pulling from that. I want to get a few more pieces working before I send that out.

Florian (and to a lesser degree me) fixed a bunch of errors in the SDK which is a step in the direction too. When I get the SDK building with GN, I want it to fail the build if there are any errors. That means I'd like to get to zero SDK errors before we switch over.

**Comment by dgrove** [comment]
Is this still targeted for 1.24?

**Comment by munificent** [comment]
Oh, dang. I didn't realize this was slated for 1.24. :(

I'm working on getting the DDC tests going through test.dart first, which in turn means I'm doing some refactoring on test.dart. I probably won't have this all done in time for 1.24 unless it's really important to.

**Comment by vsmenon** [comment]
This shouldn't block 1.24.

**Comment by munificent** [comment]
This is done now. :)
