### ISSUE TITLE
Ship a compatible version of require.js under sdk/lib/dev_compiler/amd

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29140]
When compiling ddc using amd modules (the first strategy I am targeting right now), users currently need to grab their own copy of require.js or point at a cdn. 

I propose that we ship a compatible version with the sdk, and then the transformer will copy that file next to your entry point script and edit your html to go from:

```<script type="application/dart" src="main.dart"></script>```
to
```<script data-main="main.dart" src="require.js"></script>```

**Comment by jakemac53** [comment]
cc @kevmoo @jmesserly

**Comment by jmesserly** [comment]
seems reasonable to me 👍

**Comment by vsmenon** [comment]
We probably need to:

[] add requirejs github to DEPS or download the built file as part of gclient runhooks
[] copy it alongside amd/dart_sdk.js into the built sdk as part of the build process
[] update whatever license we need to appropriately

@whesse - that sound right?

**Comment by whesse** [comment]
Yes, follow the procedure in the wiki for adding third-party dependencies.

**Comment by vsmenon** [comment]
Thanks, this is the relevant wiki page:

https://github.com/dart-lang/sdk/wiki/Adding-and-Updating-Dependencies
