### ISSUE TITLE
Crash from IntelliJ IDEA

### ISSUE THREAD

**Issue by KOGI** [dart-lang/sdk#29151]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-171.3780.107`
- `1.22.1`
- `IU-171.3780.107, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1680x1050, 1680x1050`

## Exception

Please append the contents of:
file://D:\System\Users\Bob\AppData\Local\Temp\report.txt

```
```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source D:\code\engine\lib\src\models\services\model_service.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source D:\code\engine\lib\src\models\services\model_service.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (LNResponse parsedResponse) → dynamic in [(null parsedResponse) → dynamic, (null error) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4425)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10562)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)
#17     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7653)
#18     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)
#20     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#21     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#22     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#24     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#25     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#26     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#27     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#28     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#30     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7536)
#31     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#32     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3532)
#33     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7527)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#35     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#36     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#37     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3502)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#40     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#41     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#43     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3105)
#44     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#45     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#46     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#47     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#48     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#49     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#50     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#51     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#52     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#53     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#54     _rootRun (dart:async/zone.dart:1146)
#55     _CustomZone.run (dart:async/zone.dart:1026)
#56     _CustomZone.runGuarded (dart:async/zone.dart:924)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#58     _rootRun (dart:async/zone.dart:1150)
#59     _CustomZone.run (dart:async/zone.dart:1026)
#60     _CustomZone.runGuarded (dart:async/zone.dart:924)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#62     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#63     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#64     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

```
1490298494903 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\fb_request.dart","errors":[]}}
1490298494903 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\fb_page.dart","errors":[]}}
1490298494903 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\json_patch.dart","errors":[]}}
1490298494904 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\sip_credential.dart","errors":[]}}
1490298494904 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\account_service.dart","errors":[]}}
1490298494905 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\health.dart","errors":[]}}
1490298494905 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\line.dart","errors":[]}}
1490298494905 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\models\\event.dart","errors":[]}}
1490298494905 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\activity.dart","errors":[]}}
1490298494907 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\katana_engine.dart","errors":[]}}
1490298494912 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\user_connection.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"D:\\code\\engi
1490298494914 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\avatar.dart","errors":[]}}
1490298494916 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\channel_routes.dart","errors":[]}}
1490298494921 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\models\\user.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"D:\\code\\engine\
1490298494923 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\reports_routes.dart","errors":[]}}
1490298494926 => {"id":"458","method":"analysis.updateContent","params":{"files":{"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart":{"type":"add","content":"part of katana_
1490298494926 => {"id":"459","method":"edit.getAssists","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","offset":496,"length":0},"clientRequestTime":1490
1490298494933 => {"id":"460","method":"edit.getFixes","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","offset":496},"clientRequestTime":1490298494933}
1490298494944 <= {"id":"458","result":{}}
1490298494944 <= {"id":"459","result":{"assists":[]}}
1490298495042 => {"id":"461","method":"edit.getFixes","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","offset":496},"clientRequestTime":1490298495042}
1490298495152 <= {"id":"460","result":{"fixes":[]}}
1490298495153 <= {"id":"461","result":{"fixes":[]}}
1490298495155 <= {"event":"analysis.highlights","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":22},{"
1490298495157 <= {"event":"analysis.navigation","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","regions":[{"offset":8,"length":13,"targets":[0]},{"offse
1490298495157 <= {"event":"analysis.overrides","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","overrides":[]}}
1490298495157 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","locat
1490298495159 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\src\\models\\services\\model_service.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","locat
1490298495163 <= {"event":"analysis.errors","params":{"file":"D:\\code\\engine\\lib\\katana_engine.dart","errors":[]}}
1490298495190 <= {"event":"server.error","params":{"isFatal":false,"message":"Task failed: GatherUsedLocalElementsTask for source D:\\code\\engine\\lib\\src\\models\\services\\model_service
```

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
