### ISSUE TITLE
Merge fix for #29080 to dev

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#29154]
Could you merge these CLs to the dev branch?

These two commits should merge cleanly in this order:

1. Fix two bugs with async stack traces: ef7487a7a8b8604401cfafabe6bd2555b6847f17

2. Ensure unoptimized code when collecting awaiter return stack trace: 537eacb525575b422361fcfc5692e8f1b2820850

**Comment by whesse** [comment]
I'm going to do a full push to dev, we aren't in Cherry pick season yet.

**Comment by fsc8000** [comment]
Sgtm
