### ISSUE TITLE
Analyzer strong-mode error in 0.29.8 preventing dartdevc compile

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29150]
When trying to naively compile (all srcs under lib) analyzer 0.29.8 and sdk version 1.23.0-dev.9.1 with dartdevc I get the following errors:

```
[error] Type parameter bound types must be instantiated. (package:analyzer/src/generated/java_core.dart, line 129, col 31)
[error] The named parameter 'growable' isn't defined. (package:analyzer/src/generated/static_type_analyzer.dart, line 728, col 58)
[error] The named parameter 'growable' isn't defined. (package:analyzer/src/generated/type_system.dart, line 1536, col 9)
[error] Missing concrete implementation of 'Uri.isScheme'. (package:analyzer/src/util/fast_uri.dart, line 12, col 7)
```

Presumably you should also see these errors in your editor if you go back to that version of the analyzer, but I haven't confirmed. The most current version does not give me these errors (in my editor at least).

Ideally, we could backport these fixes to a 0.29.8+1 release.

This is currently blocking packages that depend on analyzer from running dartdevc without any special configuration to disable or customize how dartdevc runs on their deps. Eventually we want to be in a place where analyzer isn't compiled for those apps, but the extra cost is only extra code compiled and/or shipped to the browser at dev time, so its worth unblocking things now.

cc @stereotype441 @bwilkerson @kevmoo

**Comment by jakemac53** [comment]
I will actually just take a look at this today and see if I can resolve it, assuming I should work on the analyzer-0.29 branch?

**Comment by bwilkerson** [comment]
Yes, you should make your changes to the analyzer-0.29 branch.

**Comment by jakemac53** [comment]
Fixed (as far as analyzer is concerned) by https://github.com/dart-lang/sdk/pull/29159
