### ISSUE TITLE
AOT: Improve optimization of as-casts

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#29153]
as-expressions should be optimized in the same way as is-tests. The two should be handled in a consistent way across the compiler. Right now, there are some discrepancies: For example we can compile is-tests as cid range-checks, but can't do it as-expressions yet.

AOT compiled example:
```
class A { }

class B extends A { }

class C extends A { }
```

```x is A``` is compiled to a cid range check ```_classRangeCheck(x, cid_A, cid_C)```

where as ```x as A``` is compiled as a generic ```AssertAssignableInstr``` which generate a lot of extra code. Instead ```x as A``` could be compiled to:
```
_classRangeCheck(x, cid_A, cid_C) || x == null ? x : throw TypeError
```

**Comment by MichaelRFairhurst** [comment]
Landed in bffe47e678578f852dd19cddf919d62fd8da7fad
