### ISSUE TITLE
kernel to il layer needs to be updated to support latest async debugging features

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#29158]
1. A call to _asyncStarMoveNextHelper is needed in kernel to il translation layer -- See https://codereview.chromium.org/2768103002/diff/40001/runtime/vm/parser.cc

It's unclear where this call goes in kernel_to_il.

2. The :async_op variable is null in kernel_to_il when it shouldn't be? -- See https://codereview.chromium.org/2766353005

**Comment by johnmccutchan** [comment]
@kmillikin @jensjoha

**Comment by kmillikin** [comment]
The second issue was fixed.  I don't see a call to `_asyncStarMoveNextHelper` in the VM's async transformation, but I'm not sure if it's still needed.  Perhaps someone on the VM team can take a look and verify whether this is even still an issue.

**Comment by alexmarkov** [comment]
In non-PRODUCT Dart 1 mode, a call to _asyncStarMoveNextHelper(stream) is generated right before a call to moveNext() in `await for` loops in https://github.com/dart-lang/sdk/blob/c99268feb946513831350d2f34891d8853981ede/runtime/vm/parser.cc#L9346-L9360

This call does the following: if there is an active debugger, single stepping and VM flag `--async_debugger` was set (it is true by default in non-PRODUCT mode), then  _asyncStarMoveNextHelper sets breakpoint to a stream's _generator closure and continues execution. It would skip any interleaving code until it reaches closure which implements async* function.

In Dart 2 mode this call is not generated. However, single stepping from `await for` into async* function works with one caveat: it stops one extra time at the async* function declaration before jumping to a particular yield point. This behavior looks fine. Until we discover any problems, we can postpone generation of _asyncStarMoveNextHelper call.

**Comment by jensjoha** [comment]
Well... I am actually working on that, basically having a CL ready to go... I see now that I should have assigned this to me though...

**Comment by dgrove** [comment]
Given that this isn't part of Dart2Stable's requirements, can work on this wait until Dart2Stable is out?

**Comment by jensjoha** [comment]
This should now be fixed.
