### ISSUE TITLE
In 1.23-dev SDK libraries appear to be not-debuggable by default (in 1.22, they were)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#29155]
I don't know if this is a deliberate change or maybe a bug but in 1.23-dev SDKs it seems that libraries are not debuggable by default. In 1.22 they were.

Previously in Dart Code I only sent `setLibraryDebuggable` when I needed to mark libraries a not-debuggable but with 1.23-dev it seems that I need to explicitly send calls for every library to mark them as debuggable.

I'm testing this by trying to step into the `print` function:

```dart
main() {
  while (true) {
    print("Hello, world!"); // <-- breakpoint here, press F11
  }
}
```

Is this expected?

@johnmccutchan @mhausner

**Comment by johnmccutchan** [comment]
@DanTup - yes we've restored the old default behaviour which is that dart:* are not debuggable by default.

**Comment by DanTup** [comment]
@johnmccutchan Thanks for confirming! Is there a good place for me to keep up-to-date with changes like this that might affect Dart Code (without having all the details of every commit!)?
