### ISSUE TITLE
Remove 'Phase 1' and 'Phase 2' from asynchrony support docs

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29162]
When people search or want to read about async await in Dart, they find this page:
https://www.dartlang.org/articles/language/await-async

It says  "Dart Language Asynchrony Support: Phase 1" and is dated 2014. It looks like we're not done yet. I think the 'Phase' is an implementation detail at the moment, as we have full async support.

The second 'phase' is here:
https://www.dartlang.org/articles/language/beyond-async

Let's definitely remove the 'Phase', and either rename to something else (async/await vs */yield) or merge the two phases into one doc. The resulting doc(s) should probably be in the language tour.

Alternately, just add a big link to https://www.dartlang.org/guides/language/language-tour#asynchrony-support from the top of both these articles.

**Comment by natebosch** [comment]
cc @kwalrath

**Comment by atsansone** [comment]
This has been updated in the docs. Phase 1 is now a codelab. Phase 2 is gone. Neither mention phases. Closing.
