### ISSUE TITLE
Missing kernel nodes for completeness

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29169]
- [x] Exports (with metadata)
- [x] Imports (with metadata)
- [x] Annotations on libraries
- [x] typedefs (with metadata)
- [ ] redirecting factory constructors #29841
- [x] Annotations on VaribleDeclaration
- [ ] Export scopes

**Comment by peter-ahe-google** [comment]
@asgerf

**Comment by asgerf** [comment]
Could someone clarify what are these AST nodes are needed for?

**Comment by peter-ahe-google** [comment]
They are needed for modular compilation.

**Comment by peter-ahe-google** [comment]
And to implement dart:mirrors.

**Comment by asgerf** [comment]
CL out of imports/exports https://codereview.chromium.org/2852373002

**Comment by peter-ahe-google** [comment]
In addition to export declarations, we also need a way to preserve the export scope of a library.

**Comment by sigmundch** [comment]
@kmillikin - we were wondering if you had any updates on these changes, they will really help unblock some work in the FE. 

(sorry for the duplicate post, I just asked a similar question on a related bug but this bug is tracking a few more of the items).

**Comment by stefantsov** [comment]
Annotations on VariableDeclaration were added in https://github.com/dart-lang/sdk/commit/e7a29d8dfbf873917096e00d3468bfd08aaca867 (see #30035).
