### ISSUE TITLE
'webkitIDBKeyRange' is deprecated

### ISSUE THREAD

**Issue by jptrainor** [dart-lang/sdk#29167]
I'm seeing the following warning in the latest Android Chrome webview that uses Dart's indexeddb implementation:

'webkitIDBKeyRange' is deprecated and will be removed in M57, around March 2017. Please use 'IDBKeyRange' instead. See https://www.chromestatus.com/features/5775330191081472 for more details.

Dart SDK version: 1.22.1
navigator.userAgent:
"Mozilla/5.0 (Linux; Android 5.1.1; Nexus 4 Build/LMY48T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36"

**Comment by natebosch** [comment]
We have a fallback to `IDBKeyRange` and I think this has been working since this was filed.
https://github.com/dart-lang/sdk/blob/3cf7d6a9c7fffc0f9a0728599a9eff69a83c068a/sdk/lib/indexed_db/dart2js/indexed_db_dart2js.dart#L121-L122
