### ISSUE TITLE
Please, specify execution order of Future callbacks

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29168]
The [description ](https://api.dartlang.org/stable/1.21.1/dart-async/Future-class.html)for class dart:async:Future reads:

> Futures can have more than one callback-pair registered. Each successor is treated independently and is handled as if it was the only successor.

Please, specify the order of execution the `Future` callbacks or explicitly state that order is undefined.

**Comment by lrhn** [comment]
We should probably say that it's undefined. It's actually in registration order, except that it might be possible to get an out-of-order call by adding a listener after completing the future, but before the already registered callbacks are called. Maybe. So, let's go for "undefined".
