### ISSUE TITLE
confusing debugger behavior for uncaught exception in async function

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#29200]
Using  1.23.0-dev.10.0 (as shipped by Flutter):

To reproduce, here is a simple program that throws a NoSuchMethodError:

```
main(List<String> args) async {
  var f = new Foo();
  print(f.a.length);
  print('Should not get here');
}

class Foo {
  String a;
}
```

In IDEA I set a breakpoint at the first line in main and run the program. When paused at the breakpoint, I open Observatory and go to the debugger. Then press 'n':

```
Paused at breakpoint 1 at main.dart:2:15
$ n
Continuing...
Paused at main.dart:3:11
$ n
Continuing...
Paused at main.dart:3:13
$ n
Continuing...
Paused at main.dart:5:1
```

It jumps from line 3 to line 5 (at the end of main), but there isn't any indication why it stopped there. In a larger program this is mysterious (since it also stopped a couple lines after the end of main).

If you remove 'async' and debug it again, the behavior is clear: it stops in Object._noSuchMethod with a message:

```
Paused at an unhandled exception (type 'continue' or [F7] to exit the isolate')
```

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2815863002
