### ISSUE TITLE
Strong-mode implicit downcast error in analyzer's task model

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#29204]
When experimenting with strong-mode in kernel, I noticed an implicit downcast that fails in the analyzer's task model.

The error occurs in the initialization of these two top-level fields:
```dart
// analyzer/lib/src/task/dart.dart
const ResultCachingPolicy<Element> ELEMENT_CACHING_POLICY =
    const SimpleResultCachingPolicy(-1, -1);

final ResultDescriptor<CompilationUnitElement> COMPILATION_UNIT_ELEMENT =
    new ResultDescriptor<CompilationUnitElement>(
        'COMPILATION_UNIT_ELEMENT', null,
        cachingPolicy: ELEMENT_CACHING_POLICY); // <-- implicit downcast here
```

The `ELEMENT_CACHING_POLICY` is a `SimpleResultCachingPolicy<Element>` after strong-mode inference, but is expected to be a `ResultCachingPolicy<CompilationUnitElement>` in the construction of `COMPILATION_UNIT_ELEMENT`.

**Comment by srawlins** [comment]
I'm closing this as stale; if there is a more recent bug report, we'll follow up there. Please comment or re-open here with a closed, reproducible example if this is still a problem.
