### ISSUE TITLE
Please, clarify Future.doWhile() description 

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29202]
The [description](https://api.dartlang.org/stable/1.21.1/dart-async/Future/doWhile.html) of `dart:async:Future.doWhile()` reads:

> Future doWhile(dynamic f())
>
> Performs an async operation repeatedly until it returns false.
> 
> The function f is called repeatedly while it returns either the bool value true or a Future which completes with the value true.
> 
> If a call to f returns false or a Future that completes to false, iteration ends and the future returned by doWhile is completed.
> 
> If a future returned by f completes with an error, iteration ends and the future returned by doWhile completes with the same error.
> 
> The f function must return either a bool value or a Future completing with a bool value.

Please, clarify cases:

1. function `f` throws error.
2. function `f` returns value neither `bool` nor `Future<bool>`

**Comment by lrhn** [comment]
The parameter will now be typed as as `FutureOr<bool>`, so we don't need to say what happens if it returns something else - it's just an error.
I'll update the docs to include the case where f throws synchronously in the case where it returns an error future.

**Comment by alsemenov** [comment]
One more case to clarify: with what value future, returned by `doWhile`, completes?
I do understand that the value is not really important, but for the sake of documentation completeness, please, clarify.

**Comment by lrhn** [comment]
Good point. The returned value is `null`. 
In the longer run, it should probably be `Future<void>` since there is no usable value, but we don't allow that yet.

**Comment by alsemenov** [comment]
Please, clarify how `f` is executed synchronously or asynchronously? Does it depend on returned by `f` value type (i.e. `bool` or `Future`). For example, if `f` always returns `true` or `false`, will all calls to `f` will be finished, when `doWhile` returns? What about first execution of `f`: is it performed before `doWhile` returns or at the next iteration of the event loop?

**Comment by lrhn** [comment]
We don't plan on describing exactly when `f` is called. 
The first call currently happens immediately, before `doWhile` returns, but we have no plan to promise that, and it could easily change in the future. The following calls may or may not be delayed when a bool is returned. They currently are delayed, but they don't need to be.
