### ISSUE TITLE
Fetching VM service timeline results in a lot of allocations

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#29207]
Running the Flutter Gallery transitions perf test results in ~6 TB allocated (cumulative), almost all of which appears to happen during timeline fetching. The total allocated at any given moment never exceeds ~85 MB.

Repro instructions:
1. git clone git@github.com:flutter/flutter.git
1. cd flutter/examples/flutter_gallery
1. Attach a physical device
1. flutter drive --profile --trace-startup -t test_driver/transitions_perf.dart -d YOUR_DEVICE
1. Profile the heap (e.g., using Instruments on macOS)
1. The test in question requests the timeline immediately after the "Dialog" test. At this point, total allocations spike from ~40 GB to 6TB

/cc @johnmccutchan

**Comment by cbracken** [comment]
Profile of the above from Instruments: [FlutterGalleryAllocations.trace.zip](https://github.com/dart-lang/sdk/files/883452/FlutterGalleryAllocations.trace.zip)

**Comment by johnmccutchan** [comment]
@rmacnak-google FYI. This is likely our TextBuffer allocation strategy. Because JSONStream is append-only we could probably use a page/block allocator instead of the exponential growth + copy.

**Comment by rmacnak-google** [comment]
Exponential growth would only account for 2x overhead in cumulative allocations versus a block allocator no?

@bkonyi Seems like a good problem for your malloc profiler

**Comment by bkonyi** [comment]
@rmacnak-google When I was testing the native memory profiler I noticed that service requests to the VM caused a lot of allocations, particularly if Observatory requests the VM object or the native memory profile tries. I was seeing numbers in the many TBs allocated by calls to PrintJSONStream and TextBuffer resizing, so seeing 6TB of allocations doesn't surprise me.
