### ISSUE TITLE
Please merge revision 37330be1b9b631baa3d426c9484d5e9714ad1a9b into dev channel

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#29208]
@whesse @mit-mit @kasperl
<Describe the problem this merge is fixing - include issue numbers if applicable>
This change is necessary for dartdoc to generate docs for the generic function type support, #27527 (dartdoc [#1321](https://github.com/dart-lang/dartdoc/issues/1321)).

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
37330be1b9b631baa3d426c9484d5e9714ad1a9b

\<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here\>
This merged cleanly.

**Comment by jcollins-g** [comment]
@bwilkerson

**Comment by whesse** [comment]
This is merged into 1.23.0-dev.11.1
