### ISSUE TITLE
DDC "strong mode" failures need better messages

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29216]
DDC currently throws on `is` and `as` checks where the result would differ from non-strong Dart - primarily to avoid silently different behavior.

The error message is confusing though and doesn't indicate the intent:

```
Strong mode is-check failure: () -> int does not soundly subtype G(() -> String)
```

**Comment by jmesserly** [comment]
going to close this as obsolete, since the feature is going away soon!
