### ISSUE TITLE
Please merge revision DDC fixes into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29217]
@whesse @mit-mit @kasperl
These are fixes blocking the latest internal roll.

Please merge: 
2d5665d419f2aeee2c2e9d71b8f091a0f900d5e5
1dc8ab732ea2aec6d29dde594cdaf23047c9f29c

I've created a branch with these fixes rebased and conflicts resolved:
https://github.com/dart-lang/sdk/commits/ddc-dev

@keertip @srawlins

**Comment by whesse** [comment]
Merged in 1.23.0-dev.11.2.  This release had failures, and is superseded by -dev.11.3, which also has this merge.
