### ISSUE TITLE
pkg/meta: Add a README.md + update CHANGELOG.md for 1.0.5

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29220]
re: https://pub.dartlang.org/packages/meta

I'm happy to do this by the way, though I'd prefer to do via GitHub PR if that's OK.

/cc @bwilkerson

**Comment by bwilkerson** [comment]
I don't mind. But the package has already been published.

**Comment by matanlurey** [comment]
I imagine we can do a 1.0.5+1 but would be good to get into HEAD at least.

**Comment by bwilkerson** [comment]
Yeah, we should definitely get it into head. The "I don't mind" was shorthand for "I agree we should do this and I don't mind if you do it." The "But" was just letting you know something that might be useful information, not a "don't bother because it's too late".

**Comment by srawlins** [comment]
Fixed with 0d876c60ada65a719563a1f06f02ac9a39c7cf16.
