### ISSUE TITLE
Dart2js sometimes produces an executable that does nothing

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29226]
This issue is to track a specific aspect of https://github.com/dart-lang/sdk/issues/24914, namely the fact that sometimes dart2js produces an executable that does nothing.  See that bug for details.

Note that #24914 has been closed due to the fact that the tests it mentions are no longer run with dart2js.  However the underlying issue of dart2js producing a do-nothing executable still needs to be addressed.

**Comment by joshualitt** [comment]
This may definitely still be an issue, but this bug is quite old, and without a simple repro its difficult to verify.

If this issue is still occurring, please file a new bug with a repro.
