### ISSUE TITLE
Generic function types used as variable declarations are misinterpreted

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29237]
The code below should have no errors, but on bleeding edge shows an error on the call to `y`.  

It looks to me as if perhaps the variable declaration `Foo y` is being interpreted as declaring `y` to have type `T -> int` with `T` unbound, instead of `<T>(T) -> int`.

```
Analyzing /Users/leafp/tmp/test.dart...
    error • The method '(T) → int' is declared with 0 type parameters, but 1 type arguments were given at /Users/leafp/tmp/test.dart:21:3 • wrong_number_of_type_arguments_method
    error • The argument type 'String' can't be assigned to the parameter type 'T' at /Users/leafp/tmp/test.dart:21:13 • argument_type_not_assignable
```

```dart
typedef Foo = int Function<T>(T x);
int foo<T>(T x) => 3;
void test1() {
  Foo y = foo;
  // These two should be equivalent
  foo<String>("hello");
  y<String>("hello"); // error here
}
```

**Comment by jmesserly** [comment]
My guess for this bug and https://github.com/dart-lang/sdk/issues/29236 is that the "typedef Foo" is not creating a FunctionTypeImpl that is generic (type.typeFormals.isNotEmpty). It's possible it's being treated as equivalent to `typedef in Foo<T>(T x);`

**Comment by mit-mit** [comment]
Should this be 1.23 @kevmoo ?

**Comment by leafpetersen** [comment]
My take is that this is pretty much the core of analyzer support for generic function types, so either we push the feature off, or this bug is 1.23.  Marking it 1.23 now, since the feature is currently still marked 1.23.

**Comment by dgrove** [comment]
@bwilkerson can you please take a look ASAP?

**Comment by leafpetersen** [comment]
I think Brian is out, I'm taking a look now to see if I can make some progress on it.

**Comment by jmesserly** [comment]
Awesome! Let me know if I can help at all.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2798663003/

**Comment by leafpetersen** [comment]
I think this is still broken for return types and fields (at least).

```dart
typedef Foo = int Function<T>(T x);
int foo<T>(T x) => 3;
Foo bar() => foo;
void test1() {
  bar()<String>("hello");
}

class A {
  Foo f;
  void test() {
    f<String>("hello");
  }
}
```

```
Analyzing /Users/leafp/tmp/test.dart...
    error • The method '(T) → int' is declared with 0 type parameters, but 1 type arguments were given at /Users/leafp/tmp/test.dart:5:3 • wrong_number_of_type_arguments_method
    error • The argument type 'String' can't be assigned to the parameter type 'T' at /Users/leafp/tmp/test.dart:5:17 • argument_type_not_assignable
    error • The method '(T) → int' is declared with 0 type parameters, but 1 type arguments were given at /Users/leafp/tmp/test.dart:11:5 • wrong_number_of_type_arguments_method
    error • The argument type 'String' can't be assigned to the parameter type 'T' at /Users/leafp/tmp/test.dart:11:15 • argument_type_not_assignable
4 errors found.
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2814443005

**Comment by jmesserly** [comment]
I think this CL landed so we can close the bug out ... feel free to reopen if there's more to it!

**Comment by devoncarew** [comment]
@scheglov, does your commit still need to be merged into 1.23 stable?

**Comment by scheglov** [comment]
It does, but that's not the end yet :-(
Brian and I found at least three other problems with generic functions.

**Comment by jmesserly** [comment]
I found one in DDC too, so you're not alone :)

**Comment by bwilkerson** [comment]
@jmesserly Just FYI: there was a commit this morning that fixed the last known problem in the parser. That might well have caused follow-on issues in DDC, so you should re-test. The summary work that Konstantin is doing might also be causing problems for DDC, so you might need to wait for his work before you can be sure of the status of DDC.
