### ISSUE TITLE
some tests compile slowly

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29234]
in particular:

language/classes_static_method_clash_test
language/large_class_declaration_test

Based on the 30-60s time, I have a feeling some O(N^2) is going on.
I don't know if time is lost in the Analyzer or in DDC.

Together these two tests take about as much build time as the other 5000 tests.

**Comment by vsmenon** [comment]
It also feels like `build_sdk.sh` has gotten slower.

**Comment by scheglov** [comment]
Command line analyzer can analyze these files in about `3 seconds`. Not too fast, but this is for cold VM and caches, and is not even close to `30-60 seconds`.

```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ time d-ra tests/language/classes_static_method_clash_test.dart tests/language/large_class_declaration_test.dart
Analyzing tests/language/classes_static_method_clash_test.dart, tests/language/large_class_declaration_test.dart...
     hint • Dead code at tests/language/classes_static_method_clash_test.dart:14:3 • dead_code
1 hint found.

real	0m3.135s
user	0m4.146s
sys	0m0.425s
```

**Comment by vsmenon** [comment]
We'll probably need to chase this on the ddc side more:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/tests/language_strong] time dartanalyzer --strong large_class_declaration_test.dart 
Analyzing [large_class_declaration_test.dart]...
No issues found

real	0m2.072s
user	0m2.310s
sys	0m0.221s
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/tests/language_strong] time ddc large_class_declaration_test.dart 

real	0m27.413s
user	0m29.517s
sys	0m1.494s
```

**Comment by ErikCorryGoogle** [comment]
I'd like to repro this.  How do I build DDC?

**Comment by vsmenon** [comment]
The `dartdevc` binary is build as part of the sdk:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/tests/language_strong] time dartdevc large_class_declaration_test.dart -o /tmp/large_class_declaration_test.js

real	0m27.724s
user	0m30.188s
sys	0m1.297s
```

or just execute the dart file directly:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/tests/language_strong] time ../../pkg/dev_compiler/bin/dartdevc.dart large_class_declaration_test.dart -o /tmp/large_class_declaration_test.js

real	0m30.518s
user	0m32.701s
sys	0m1.503s
```

Lots of slowness.  :-/

(the `ddc` above is a convenience script in `pkg/dev_compiler/tool`).

**Comment by ErikCorryGoogle** [comment]
Looks like quadratic code in _RenameVisitor._finishNames in pkg/dev_compiler/lib/src/compiler/js_names.dart.  There are lots of pending renames and for each of them we build a new set of all names.  Each time we do that, the set is one bigger, so it goes quadratic.

Since this does  not look related to the VM I won't be looking more at this issue.

**Comment by vsmenon** [comment]
Thanks Erik!
