### ISSUE TITLE
Future.forEach(input, f) should continue immediately, if f returns non-Future

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29239]
The [description](https://api.dartlang.org/stable/1.21.1/dart-async/Future/forEach.html) for dart:async:Future reads:

> Future forEach(Iterable input, dynamic f(element))
> Perform an async operation for each element of the iterable, in turn.
> 
> Runs f for each element in input in order, moving to the next element only when the Future returned by f completes. Returns a Future that completes when all elements have been processed.
> 
> The return values of all Futures are discarded. Any errors will cause the iteration to stop and will be piped through the returned Future.
> 
> **If f returns a non-Future, iteration continues immediately. Otherwise it waits for the returned Future to complete.**

According to the description, the following sample code should run synchronously:
```dart
import "dart:async";

main() {
  print("main start");
  Future.forEach([0,1,2,3,4], print);
  print("main finish");
}
```
Output:

> main start
> 0
> main finish
> 1
> 2
> 3
> 4

Expected output:

> main start
> 0
> 1
> 2
> 3
> 4
> main finish

Dart VM version: 1.22.1 (Tue Feb 21 14:29:45 2017) on "windows_x64"

**Comment by lrhn** [comment]
The text doesn't match because `f` might be a synchronous operation (if it returns a non-future).

We are not going to promise when `f` is called. It may be called synchronously or not. If it returns a non-future, the loop may continue immediately or later. Still, the text could be better.
