### ISSUE TITLE
Intermittent NoSuchMethodError in Flutter unit test

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/sdk#29230]
One of the Flutter unit tests is occasionally failing with a NoSuchMethodError in an unexpected place.

Log at https://build.chromium.org/p/client.flutter/builders/Mac/builds/3140/steps/test.dart/logs/stdio
  (search for "Card Collection smoke test")

To reproduce it, go to dev/manual_tests in the Flutter source tree and run:
    ../../bin/flutter test

I usually need to run the test 10-20 times to reproduce a failure.

The failure starts with a stack trace like:
    The following NoSuchMethodError was thrown during performLayout():
    Class 'int' has no instance getter 'offstage'.
    Receiver: 0
    Tried calling: offstage

    When the exception was thrown, this was the stack:
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
    #2      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:985:20)
    ...

_computeIntrinsicDimension should be calling RenderOffstage.computeMinIntrinsicWidth, which reads the "offstage" property of the "this" object.  Most of the time this works as expected, but in a failing run it looks like "offstage" is being read from an int.

**Comment by rmacnak-google** [comment]
The background compiler and the mutator are racing creating the implicit closure for the tear off of computeMinIntrinsicWidth. One of them wins the race and becomes the one pointed to by the parent function, and the loser now incorrectly believes it is not an implicit closure function.

Shell: thread=0x7fefec0009b0 create implicit closure for RenderOffstage.computeMinIntrinsicWidth
Shell: thread=0x7feffc0f0af0 create implicit closure for RenderOffstage.computeMinIntrinsicWidth
Shell: thread=0x7feffc0f0af0 RenderOffstage.computeMinIntrinsicWidth_computeMinIntrinsicWidth is_implicit=0
