### ISSUE TITLE
VM doesn't recognize new function type as type parameter.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29243]
Example code:
```dart
int Function() x = () => 42;
int Function(int Function()) y = (int Function() x) => x();
List<int Function()> l = <int Function()>[()=>42, x];  // Error
main() {
  print(y(l[1]));
}
```
causes the error message:
```
'functype.dart': error: line 4 pos 1: unexpected token 'List'
List<int Function()> l = <int Function()>[()=>42, x];
^
```
Removing the `<int Function()>` on line 4 makes the code work. This runs in dart2js, but also crashes the analyzer.

**Comment by crelier** [comment]
I just looked at this and it is a bug (even 2 separate bugs!) in the look-ahead parsing code in the VM, which does not recognize the line as a variable declaration.
I'll fix it tomorrow.

**Comment by crelier** [comment]
I fixed this issue, but I cannot upload the cl including the regression test, because dartfmt is not able to parse it :-)

I'll file a separate bug.

**Comment by crelier** [comment]
I filed https://github.com/dart-lang/dart_style/issues/616

**Comment by crelier** [comment]
I also filed https://github.com/dart-lang/sdk/issues/29335
