### ISSUE TITLE
Remove "PkgBuildTestSuite" from test.dart, make it a separate test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29246]
Testing that all the packages in the checkout can successfully run pub get, and optionally some pub build commands, doesn't fit well in the system of running tests and reporting results in test.dart, and would be simpler as a standalone test program.  This would also simplify test.dart code.

This suite is currently run on the pub pkg builders by running tools/test.py .... pkgbuild.
Most of the class PkgBuildTestSuite, and the functions discoverPackagesInRepository(),
        discoverSamplesInRepository() can be pulled out of tools/testing/dart/test_suites.py and simplified, to make this simpler test program.

**Comment by whesse** [comment]
@peter-ahe-google @dgrove

**Comment by munificent** [comment]
I think this was done wasn't it? I don't see any reference to it in test_runner anymore. If I'm wrong, feel free to re-open.

**Comment by whesse** [comment]
Yes, you removed them.  They weren't adding much value.  Many of our packages now have GitHub unit testing running through actions, for things like checking out their dependencies.

https://codereview.chromium.org/2801143003

**Comment by munificent** [comment]
> Yes, you removed them.

Haha! *[no memory of this Gandalf meme.gif]*
