### ISSUE TITLE
Support for ALPN on MacOS again

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#29240]
The `dart:io` implementation had support for ALPN on all platforms since around `1.8.0` but the [switch to  SecureTransport API](https://codereview.chromium.org/1721283002) removed that functionality on MacOS in version `1.16.0`.

ALPN support is necessary for building http/2 and gRPC libraries in Dart, so it would be nice if we could get this functionality working again somehow.

Let's keep this as a tracking bug other issues can refer to.

**Comment by zanderso** [comment]
Ben has landed support in https://github.com/dart-lang/sdk/commit/644862bf966e6c079460258807ab3364b7e3759a, which switches to BoringSSL and uses the system keystore for trusted root certs on Mac, (and does a lot of other great refactoring as well!)

@bkonyi I think we can probably close this issue after updating the changelog and removing/deprecating the `alpnSupported` flag.

/cc @kevmoo @jakobr-google @kasperl

**Comment by zanderso** [comment]
This should hopefully help unblock https://github.com/dart-lang/sdk/issues/22655 on Mac.

**Comment by mkustermann** [comment]
This is great, @bkonyi. Thanks a lot!
