### ISSUE TITLE
Please merge revision 17b1e30d045c4bbf2b156b66a973e0fdaba136f0 into dev channel

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#29249]
@whesse @mit-mit @kasperl
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
This makes the dartdoc that supports generic-feature-types link in with the SDK.  #27527, dart-lang/dartdoc#1321

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
17b1e30d045c4bbf2b156b66a973e0fdaba136f0

\<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here\>
This merged cleanly, tested that dartdoc was able to generate SDK and a package dartdoc.

**Comment by jcollins-g** [comment]
Corrected with the right revision.

**Comment by whesse** [comment]
This will go in the next cherry-pick, which probably won't be for about 18 hours.  Is this key to the work on landing in google3?  Or can it wait to see if more cherry-pick requests arrive today?

**Comment by jcollins-g** [comment]
It can likely wait; this isn't a google3 blocker AFAIK

**Comment by whesse** [comment]
Merged in 1.23.0-dev.11.5
