### ISSUE TITLE
Future.doWhile() incorrectly handles synchronous errors

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29257]
According to [description](https://api.dartlang.org/stable/1.21.1/dart-async/Future/doWhile.html) of method Future.doWhile() and information in #29202 any errors (either synchronous or asynchronous) should be propagated to the `Future` returned by the `doWhile`.
The following code demonstrates the problem:
Error thrown by `f1` is caught and propagated as expected.
But error in `f2` is not caught. In non-checked mode returned Future even completes normally.
```dart
import "dart:async";

int num = 0;

Future check(String name, dynamic f()){
  num = 0;
  return Future.doWhile(f).then(
      (value) {
        print("doWhile($name) completed with $value");
      },
      onError: (e) {
        print("doWhile($name) completed with error $e");
      }
  );
}

main() async {

  dynamic f1() {
    print(num);
    if (num == 2) throw "@";
    num++;
    return new Future.value(num < 5);
  }

  dynamic f2() {
    print(num);
    if (num == 2) return "@";
    num++;
    return new Future.value(num < 5);
  }

  await check("f1", f1); // ok
  await check("f2", f2); // not ok
}
```
Output:

> λ d:\dev\dart\dart-sdk\bin\dart  test2.dart
> 0
> 1
> 2
> doWhile(f1) completed with error @
> 0
> 1
> 2
> doWhile(f2) completed with null
>
> λ d:\dev\dart\dart-sdk\bin\dart --checked test2.dart
> 0
> 1
> 2
> doWhile(f1) completed with error @
> 0
> 1
> 2
> Unhandled exception:
> type 'String' is not a subtype of type 'bool' of 'keepGoing' where
>   String is from dart:core
>   bool is from dart:core
> 
> #0      Future.doWhile.<anonymous closure> (dart:async/future.dart:449)
> #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
> #2      _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1370)
> #3      _RootZone.runUnary (dart:async/zone.dart:1404)
> #4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
> #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
> #6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
> #7      _Future._completeWithValue (dart:async/future_impl.dart:477)
> #8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
> #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
> #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> #11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
> #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Expected output:
> 0
> 1
> 2
> doWhile(f1) completed with error @
> 0
> 1
> 2
> doWhile(f2) completed with error TypeError

Dart VM version: 1.22.1 (Tue Feb 21 14:29:45 2017) on "windows_x64"

**Comment by lrhn** [comment]
Technically (always a good sign of evasiveness!) the error is not in `f` or in its return value - `f` returns fine and its returned future completes without a hitch, it's just that the value is incorrectly typed. We generally don't promise where we catch type errors (if at all), so in checked mode it can happen at any typed boundary. We don't promise that because it would mean that we have to wrap all user-supplied code in try/catch statements, which would likely be costly.

So, not going to fix this.
I have an open CL that would change place where `f` is called to (effectively):
```
FutureOr<bool> result = f();
```
In strong mode, that should fail immediately (which is inside a try/catch). 
In Dart 1, `FutureOr<bool>` is just dynamic, so we won't catch it there. So, consider this being fixed for 2.0.

**Comment by leafpetersen** [comment]
Has this been fixed?  @lrhn did you land the CL you mention above?

**Comment by lrhn** [comment]
Yes, the type of `result` that the call to `f` is assigned to is now `FutureOr<bool>`.
