### ISSUE TITLE
@immutable is too aggressive

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#29267]
```dart
@immutable
class Foo {
  static const int bar = 0;
}
```

Triggers the `@immutable` lint even though the non-final field is a static constant.  Probably all static fields should be ignored for the purpose of `@immutable`

/cc @bwilkerson @pq

**Comment by sethladd** [comment]
Good catch :)

**Comment by abarth** [comment]
Fix in https://codereview.chromium.org/2805443002

**Comment by pq** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/c25cd4da33f4b0e96a5ab75274bc209662e4f187.
