### ISSUE TITLE
Let Observatory timeline's 'profiles' be segmented buttons instead of a dropdown

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#29275]
Small nit quality of life improvement.

Consider the following (flutter) developer's workflow:
1- put in test code and timeline traces
2- flutter run --profile
3- click the observatory link
4- open timeline
5- click profiles dropdown
6- click on dart developer (most useful for flutter developers)
7- do stuff
8- click refresh

The repeat from 1 maybe 20 times until whatever that needs figuring out is figured out. Any reduction of human steps (5-6) in the workflow could reduce friction. 

Note: perhaps 2-6 is a flutter specific issue since profile mode apps can't be hot reloaded.

**Comment by rmacnak-google** [comment]
@B3rn475

**Comment by B3rn475** [comment]
@xster the VM has a parameter to enable the streams at startup `--timeline_streams=Compiler,Dart,GC`.
If we add this parameter in the flutter tools too and forward it to the VM we can remove completely steps 5 and 6 by just starting flutter using `flutter run --profile --timeline_streams=Compiler,Dart,GC`
