### ISSUE TITLE
enums should be allowed in constant expressions

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29278]
It's common in Flutter code to use enums heavily. Since these are always entirely known at compile time, it is unfortunate that they cannot be used in constant expressions. (Constant expressions with enums would allow us to assert things about arguments based on enums in constant constructors which would allow big performance wins in widget trees which could be constant in principle but can't today because of this issue.)
```dart
enum X { a, b }
const bool foo = X.a == X.b; // <-- won't compile
void main() {
  print(foo);
}
```

**Comment by lrhn** [comment]
I agree, we should extend `==` to also cover enum values.
You can use `identical(X.a, X.b)` until that happens.

**Comment by srawlins** [comment]
Not sure when this changed, but this now works in the VM 😕 . It does not work [in dart2js](https://dartpad.dartlang.org/831264cd34821de8bc5552f1b97b669e), and the analyzer is unhappy about it still.

**Comment by lrhn** [comment]
It shouldn't work. The language specification has not been changed to allow this.
(We still should, but it hasn't happened yet).

**Comment by bergwerf** [comment]
This would also be nice for writing assert statements in a const constructor for an enum class field. I was trying to do this:
```dart
class ExprSymbol {
  final SymbolType type;
  final num value;
  final int argumentCount;

  const ExprSymbol(this.type, this.value, this.argumentCount)
      : assert(type == SymbolType.number ? argumentCount == 0 : argumentCount != null);
}
```

**Comment by gnudles** [comment]
consider also:
enum Fruit {
  apple,
  banana
}
const int a = Fruit.apple.index+1;

**Comment by srawlins** [comment]
I think the original request can be closed in favor of https://github.com/dart-lang/language/issues/312 in the new language repo.

(That enhancement doesn't address other requests above like enum fields in const classes, or accessing an enum's index and using `+` in a const context.)

**Comment by mit-mit** [comment]
Closing as this is now being tracked in https://github.com/dart-lang/language/issues/312

If you voted on the present issue, I'd encourage you to vote on issue 312 above in the language repo.

**Comment by mshenawy22** [comment]
Enums produce an error in switch expressions Case expressions must be constant

**Comment by lrhn** [comment]
Enums are constants. They also have primitive equality, so they should work in switches.

The problem here was that they did not work with `==` in constant expressions.
