### ISSUE TITLE
native members can't be be overridden by a user defined mixin

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29273]
This test demonstrates the bug:

https://codereview.chromium.org/2805483003/diff/1/tests/lib_strong/html/html_mock_test.dart

We're not properly handling methods inherited via mixin.

(edit by @jmesserly: see my [comment below](https://github.com/dart-lang/sdk/issues/29273#issuecomment-292384130) for a repro that doesn't use HTML or mocks)

**Comment by jmesserly** [comment]
I think I can fix this along with #29233 ... I'm going to merge _collectMockMethods into our other code that is building a model of the class hierarchy (ClassPropertyModel) ... it handles virtual fields and native type extension methods, so it's not surprising that the mock support didn't correctly interact with those two features.

**Comment by jmesserly** [comment]
... yup, _extensionsToImplement has a similar issue.

**Comment by jmesserly** [comment]
I'm pretty sure that mocks and HTML are unrelated. It's mostly that we don't support implementing native type methods via mixin. For example:
```dart
import 'dart:collection';

class BrokenFirstGetter {
  get first => 9999;
}
class ListMock extends ListBase with BrokenFirstGetter {
  final _list = [];
  int get length => _list.length;
  void set length(int x) { _list.length = x; }
  operator[](x) => _list[x];
  void operator []=(x, y) { _list[x] = y; }
}

main() {
  List x = new ListMock();
  x.add(42);
  print(x); // [42]
  print(x.first); // VM: 9999, DDC: 42
}
```
... i'll work on a fix and add that as a test. Also going to update the subject.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2803673007/
