### ISSUE TITLE
Please merge revision #5c3bcff375bae0f2ca383aca49f71a3b63c469e2 into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29298]
@whesse @mit-mit @kasperl
This fixes a new bug on async & foreign futures exposed in the current internal 1.23 roll.  This CL fixes an internal test and unblocks that roll.

This is the revision to merge:
#5c3bcff375bae0f2ca383aca49f71a3b63c469e2

It does not merge cleanly onto dev.

I've rebased and regenerated DDC artifacts in this branch - please merge this in:

https://github.com/dart-lang/sdk/commits/ddc-1.23.0-dev.11.5

**Comment by vsmenon** [comment]
@srawlins @keertip

**Comment by whesse** [comment]
Thanks - having a branch is much easier for me than having a merge CL.

**Comment by whesse** [comment]
Merged in 1.23.0-dev.11.6
