### ISSUE TITLE
fuzzy arrows and covariant generics require more checks

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29295]
related to #27259, we're missing tests in covariant generic casts:
```dart
typedef F(x);
main() {
  F f = (int hi) => print(hi.isEven);
  List<dynamic> l = <String>['1'];
  l.map(f).toList();
}
```
DDC doesn't catch this at all and prints 'null'. VM does:
```
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance getter 'isEven'.
Receiver: "1"
Tried calling: isEven
```

**Comment by leafpetersen** [comment]
Just to be clear, my preferred solution for this is not adding more checks, but getting rid of fuzzy arrows.

**Comment by jmesserly** [comment]
Good point Leaf! I've filed: https://github.com/dart-lang/sdk/issues/29299 and I'll mark this one blocked until we can get our internal code cleaned up w.r.t. fuzzy arrows and change static type system behavior.

**Comment by jmesserly** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/29630

**Comment by jmesserly** [comment]
We're removing fuzzy arrow support from DDC runtime, so this is obsolete.
