### ISSUE TITLE
DDC incorrectly handling abstract overload of concrete member

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29304]
This is a fairly obscure example, but I noticed it in our code.  The following:

```dart
class A {
  void foo(int x) {
    print(x + 1);
  }

  void noSuchMethod(Invocation i) {
    print('Not implemented ${i.memberName}');
  }
}

abstract class B extends A {
  void foo(Object x);
}

class C extends B {
}

void main() {
  var c = new C();
  c.foo('hello');
}
```

prints

```
hello1
```

i.e., it's passing a `String` to `A.foo`.

What is the correct behavior?

**Comment by vsmenon** [comment]
@leafpetersen - thoughts on the correct behavior?  VM checked mode throws a checked mode exception in `A.foo`.  We don't want to do a check there of course.

**Comment by vsmenon** [comment]
Filing as language as I'm not entirely sure what the right behavior should be here going forward.

**Comment by leafpetersen** [comment]
I don't think this is NSM specific is it?  If I take out the NSM, the same problem persists.  I think this code should be rejected. I'm mildly surprised that it's not a static warning in Dart 1.0.

**Comment by vsmenon** [comment]
The NSM is what prevents the static warning today.

**Comment by leafpetersen** [comment]
I don't see any static warnings if I take out the NSM from that code.

**Comment by vsmenon** [comment]
@leafpetersen is correct.  I don't see any difference - static or runtime - due to the NSM.  Updated the bug title.

**Comment by lrhn** [comment]
I agree that class `C` is invalid on its face, and due to inheriting `A.foo`, there will not be a noSuchMethod forwarder added, so it is simply rejected as a class declaration.

**Comment by jmesserly** [comment]
This example is statically rejected now, so we can close this.
