### ISSUE TITLE
dart2js transpiled WebGL2 code works in dartium but not in chrome (ddc is other way round) 

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/sdk#29308]
First off, Dartium 45 supports WebGL2 when configured properly.
To activate WebGL2 support launch dartium with "--enable-unsafe-es3-apis" 
you may also need to enable the following under chrome://flags :
* Override software rendering list 
* Enable WebGL Draft Extensions

You can make sure that webgl2 is working in dartium at  http://webglreport.com/?v=2

The problem can be reproduce with the webgl2 branch of the chronosgl library: https://github.com/ChronosTeam/ChronosGL/tree/webgl2

First  try the straight up dart example/simple/simple.html in dartium - this should work

Next transpile the example with dart2js
make simple_example
which will print a url to try
that url works with dartium 45 but not on any current chrome version

Next  transpile the example with ddc
make -f Makefile.lib simple_example
which will also print a url to try
that url works on recent chrome but not dartium 45

**Comment by sigmundch** [comment]
/cc @alan-knight @vsmenon 

Could this be a result of a mismatch between IDL files? Dart2js's `dart:html` implementation is generated from the IDL files of chromium-45, so this mismatch could cause the program to fail in the current chrome. DDC might be using a different `dart:html` library, but I'm not sure.

**Comment by vsmenon** [comment]
@terrylucas is looking at WebGL2

DDC output won't run on Chrome 45 (e.g., Dartium) in general - it targets ES6 features that require Chrome 47/48 or later.

They should be using roughly the same dart:html.

**Comment by terrylucas** [comment]
Robert has a private version of Dartium 50 that works with the WebGL2
that's exposed in Chromium 50.

As I roll Dartium 50 to Dart2JS I/Robert can check on chronosgl working.
The DDC part is certainly later...

**Comment by robertmuth** [comment]
The private version of Dartium 50 now works with all example/* from 
https://github.com/ChronosTeam/ChronosGL/tree/webgl2

DDC transpiled code for example/simple works in both Chrome 57 and Dartium 50.

No change on the dart2js side. The transpiled code for example/simple does NOT run in Chrome 57.

**Comment by jwt-sgg** [comment]
When will an updated Dartium be made available for everyone?

**Comment by terrylucas** [comment]
Soon, we are still fixing bugs / adjusting to changes that occurred between
Chromium 45 and Chromium 50.  I would anticipate a new Dartium and
dart:html (et. al libraries) for dart2js  with the release of Dart 1.24

Terry.

**Comment by terrylucas** [comment]
Fixed for Dartium, dart2js and DDC.
