### ISSUE TITLE
Add additional logic to the analysis server import suggestion quick-fix

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29303]
Context here: https://github.com/flutter/flutter/issues/9022

When suggesting imports for types (`Future`), we should prefer dart: libraries (`dart:async`).

We may also want to add a bit more heuristics in order to handle exports better. For instance, if there are two matches for libraries the symbol comes from, we should give less weight to libraries from `src` directories. This will help in cases where a symbol is defined in a private library but exported from a more general public library (like `package:flutter/src/material/card.dart` and `package:flutter/material.dart`).

/cc @scheglov, @bwilkerson

**Comment by scheglov** [comment]
We [already prefer](https://github.com/dart-lang/sdk/blob/483066a6971b1cdd0485370683d58cab73f1159b/pkg/analysis_server/test/services/correction/fix_test.dart#L3354) public libraries over private ones.

Then we [already prefer](https://github.com/dart-lang/sdk/blob/483066a6971b1cdd0485370683d58cab73f1159b/pkg/analysis_server/test/services/correction/fix_test.dart#L3297) libraries that declare a symbol over exports.

With [this CL](https://codereview.chromium.org/2808803003) we will prefer SDK imports over other imports.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/3be10faaeed71a186dcb9651812cb6619839f506
