### ISSUE TITLE
FieldElement.isEnumConstant is true for index and values.

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/sdk#29306]
Enums create two internal fields: `index` and `values`. 
However, the analyzer marks `isEnumConstant` as true for every single field, including `index` and `values`. 
It should set `isEnumConstant = false` for these values.

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/element/element.dart#L4239

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2815093002/
