### ISSUE TITLE
dart2js compile time regression with VM change "Allow dispatch to use a range of Class-ids in tests"

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29302]
https://github.com/dart-lang/sdk/commit/ae8e6705c0e1dd624ec45843879294199c11e368 caused a 7% regression on the CompileAngular2 suite 

A more recent dart2js change caused dart2js to have a more spectacular regression and time out on corelib/regexp/pcre_test
The revert https://github.com/dart-lang/sdk/commit/9f10c4898cf6906e0ea341b15da9c285a161c318 has some timing information. (This change was expected to be neutral.)

The performance regression seems to be contained in the **==** operations in Setlet.remove

If I make the following change, dart2js runs faster.
Setlet.remove and Setlet.contains are not all that dissimilar, so it might be an interesting place to understand what is going wrong.

I will re-commit my change with this modification, and remove it later when the underlying cause is addressed.

```
        if (users.remove(current)) {
          if (--usersInCurrentBlock == 0) break;
        }
--->
        if (users.contains(current)) {
          users.remove(current);
          if (--usersInCurrentBlock == 0) break;
        }

```

Further info from Slava:
----

Something seems to be going south with app snapshots:

╭─ ~/src/dart/sdk ‹test›
╰─$ time out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out2.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out2.js
out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors   163.39s user 3.28s system 102% cpu 2:41.93 total

╭─ ~/src/dart/sdk ‹test›
╰─$ time sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out3.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out3.js
sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode         16.02s user 0.86s system 124% cpu 13.599 total

The code is running **10x slower from app snapshot**. This particular degradation is caused by Erik's commit ae8e6705c0e1dd624ec45843879294199c11e368 - so I asked him to take over and dig into this. 

I am suggesting that we might want to revert it if we can't figure this out today. Additionally as we are in danger of hitting this in the wild on 1.23 we should cherry pick the revert into the 1.23

---------------------------

Here are the numbers:

With Erik's change reverted:

╭─ ~/src/dart/sdk ‹test›
╰─$ time out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out4.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out4.js
out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors   17.61s user 0.62s system 108% cpu 16.809 total
╭─ ~/src/dart/sdk ‹test›
╰─$ time sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out4.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out4.js
sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode         20.21s user 0.94s system 118% cpu 17.862 total

With both Erik's change and your change reverted: 

╭─ ~/src/dart/sdk ‹test›
╰─$ time out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out4.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out4.js
out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors   18.73s user 0.98s system 107% cpu 18.418 total
╭─ ~/src/dart/sdk ‹test›
╰─$ time sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --fast-startup --packages=.packages tests/corelib/regexp/pcre_test.dart --out=out4.js
Dart file (tests/corelib/regexp/pcre_test.dart) compiled to JavaScript: out4.js
sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode         22.59s user 1.14s system 116% cpu 20.355 total

**Comment by ErikCorryGoogle** [comment]
There's a patch that special-case reverts the changes to the == operation.
Performance results here: http://146.148.43.81:8080/Comparison#targetA%3Ddart2js-compile%3BmachineTypeA%3Dlinux-x64%3BrevisionA%3D58964%3BpatchA%3Derikcorry-dart2jsregress%3BtargetB%3Ddart2js-compile%3BmachineTypeB%3Dlinux-x64%3BrevisionB%3D58919%3BpatchB%3DNone

CL here: https://codereview.chromium.org/2798333004

Performance improves in general, but does not wipe out the regression.  I have a more complicated change in the pipeline that more-than wipes out the regression, but we could commit this one as a temporary workaround.

**Comment by rakudrama** [comment]
I'm assuming this is stale
