### ISSUE TITLE
Analyzer GET_NAVIGATION_INVALID_FILE: Error during `analysis.getNavigation`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29316]
I get lots of

> 2017-04-10 11:10:31,516 [1282916]   INFO - yzer.DartAnalysisServerService - Error from analysis_getNavigation(), file = /app_code_generator.dart, SDK version = 1.24.0-edge.021d99e05deae069352f5b8d2c00f1ef0b1f00f3, server version = 1.18.0, error code = GET_NAVIGATION_INVALID_FILE: Error during `analysis.getNavigation`: invalid file. 

and the Analyzer then somehow silently stops working and no Analyzer view becomes available in IDEA

I had to go back to 

> Dart VM version: 1.24.0-edge.9f10c4898cf6906e0ea341b15da9c285a161c318 (Thu Apr  6 22:05:46 2017) on "linux_x64"

to make it work again

**Comment by alexander-doroshko** [comment]
`GET_NAVIGATION_INVALID_FILE` is usually not related to the SDK version or not working analysis. It's just an info message that usually causes no problems. `/app_code_generator.dart` path looks incorrect indeed. Not sure why IDE tries to ask for the navigation info for it. What is the real location of `app_code_generator.dart` file?

**Comment by zoechi** [comment]
`lib/app_code_generator/app_code_generator.dart`

**Comment by alexander-doroshko** [comment]
May I take a look at the whole log file(s)?

**Comment by zoechi** [comment]
[idea.zip](https://github.com/dart-lang/sdk/files/909730/idea.zip)

**Comment by alexander-doroshko** [comment]
Did you have `app_code_generator.dart` file open when those `GET_NAVIGATION_INVALID_FILE` were being printed? Do you know how to reproduce so many lines in log? IMO it shouldn't depend on SDK version.

**Comment by zoechi** [comment]
I wasn't able to get analysis results in IDEA until I reverted to the mentioned Dart version. I tried one or two versions in between which didn't solve the issue either.

I don't know how to reproduce. 
I just tried to get IDEA to show analysis results (after upgrading Dart, `pub upgrade` and adding the newest linter rules from the last linter version).

**Comment by alexander-doroshko** [comment]
I guess server instrumentation logs will help.

**Comment by zoechi** [comment]
How do I get them?

**Comment by alexander-doroshko** [comment]
Find Action (Ctrl+Shift+A), type 'Registry', open it, set `--instrumentation-log-file=/some/path/to/log.txt` as a value of the `dart.server.additional.arguments` property, restart Analysis Server.

**Comment by zoechi** [comment]
I now get the error with the correct path in the log
The only difference I'm aware of is, that I currently don't have any other IDEA projects opened (I had when I originally reported the issue).

All I did after starting the IDE and opening the project.
The analyzer starts analyzing and then dies shortly afterwards.

[idea.zip](https://github.com/dart-lang/sdk/files/910254/idea.zip)

**Comment by zoechi** [comment]
It seems I used an analyzer snapshot with the angular_analyzer_plugin applied.
I started again with a fresh install and now I got this behavior only after installing the angular_analyzer_plugin.

**Comment by alexander-doroshko** [comment]
Ok, so not an IDE issue :).
Note that if you decide to attach server instrumentation logs here or in any other issue - logs may contain sources of the files that you edit. So if you do not want to make them public you may send logs to those who are interested directly.

**Comment by bwilkerson** [comment]
@MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment]
Hmm, we don't do any navigation. We don't even load a server plugin.

Could it be related to the fact that we report errors for html? Then causes DAS to look for navigation in that html?

**Comment by bwilkerson** [comment]
What html file? (I thought the issue was caused by trying to get navigation in `app_code_generator.dart`.)

**Comment by MichaelRFairhurst** [comment]
Ah, didn't see the filename.

@zoechi what version was your analyzer before you installed the plugin?

**Comment by zoechi** [comment]
The version included in the Dart version mentioned in the initial post.
I tried to reproduce today, but wasn't able to.
I will investigate further and post an update when I find out more.

**Comment by zoechi** [comment]
This is the issue I'm currently struggling with #29322

**Comment by zoechi** [comment]
I haven't seen this in a while. I'll reopen when I run into it again.
