### ISSUE TITLE
Confusing error when iterating over a null

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29323]
This code:

```dart
void main() {
  List list;
  for (var o in list) {
    print(o);
  }
}
```

triggers this error:

```
/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9578
          throw e;
          ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at iterator.main (/Users/vsm/ddctest/iterator.js:10:15)
```

**Comment by vsmenon** [comment]
Couple options:
(1) Generate an explicit `notNull` on `list` above.
(2) Handle it somehow after the exception is thrown.  E.g., when we map the stack trace to Dart or at catch sites.

**Comment by jmesserly** [comment]
@vsmenon -- it should be pretty easy to fix this with your recent change to make JS TypeError print better right?

**Comment by Markzipan** [comment]
The updated error message is 
```
TypeError: list is not iterable
```

So that's a bit better.

**Comment by nshahan** [comment]
This error seems understandable enough now. We can create a new issue in the future if we want a different runtime error.
