### ISSUE TITLE
Standalone embedder does not support overriding .packages path in reloadSources RPC

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#29332]

**Comment by johnmccutchan** [comment]
Fixed in the following commits:

https://github.com/dart-lang/sdk/commit/99c6a18a1bc2a4f13d8dd027a597fdca0f2d6e0c
https://github.com/dart-lang/sdk/commit/9af072399ed06d7a060c0936cf2d6d4d66e57f7f
https://github.com/dart-lang/sdk/commit/024ccd30956aa64f021f677240fee39f02c1e52c

**Comment by BlackHC** [comment]
Thank you!
