### ISSUE TITLE
Analyzer crashes on tests/language/regress_29243_test.dart

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#29335]
FAILED: dart2analyzer-none release_x64 language/regress_29243_test
Expected: Pass 
Actual: Crash
CommandOutput[dart2analyzer]:

stderr:
NoSuchMethodError: The getter 'typeParameterContext' was called on null.
Receiver: null
Tried calling: typeParameterContext
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      GenericFunctionTypeElementImpl.enclosingTypeParameterContext (package:analyzer/src/dart/element/element.dart:4898:41)
#3      ElementImpl&TypeParameterizedElementMixin.allEnclosingTypeParameterTypes (package:analyzer/src/dart/element/element.dart:8712:12)
#4      GenericFunctionTypeElementImpl.type (package:analyzer/src/dart/element/element.dart:4950:23)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1667:22)
#6      _ResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:1459:31)
#7      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:7285:57)
#8      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:8322:18)
#9      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:524:11)
#10     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89:9)
#11     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#12     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88:13)
#13     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:966:65)
#14     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1744:15)
#15     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:955:20)
#16     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:506:37)
<asynchronous suspension>
#17     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133:60)
<asynchronous suspension>
#18     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:177:11)
<asynchronous suspension>
#19     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:123:18)
<asynchronous suspension>
#20     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699:50)
<asynchronous suspension>
#21     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245:36)
<asynchronous suspension>
#22     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167:20)
<asynchronous suspension>
#23     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:143:22)
<asynchronous suspension>
#24     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:865:45)
<asynchronous suspension>
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:157)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:132)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:96)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#46     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#49     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#50     _StreamController._add (dart:async/stream_controller.dart:628)
#51     _StreamController.add (dart:async/stream_controller.dart:574)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#53     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#57     _StreamController._add (dart:async/stream_controller.dart:628)
#58     _StreamController.add (dart:async/stream_controller.dart:574)
#59     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#60     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1744:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:955:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:506:37)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133:60)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:177:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:123:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699:50)
<asynchronous suspension>
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245:36)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167:20)
<asynchronous suspension>
#10     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:143:22)
<asynchronous suspension>
#11     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:865:45)
<asynchronous suspension>
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#15     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#16     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#17     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#18     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:157)
#19     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:132)
#20     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#21     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#28     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#29     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#30     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#31     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:96)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#36     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#37     _StreamController._add (dart:async/stream_controller.dart:628)
#38     _StreamController.add (dart:async/stream_controller.dart:574)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#40     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#43     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#44     _StreamController._add (dart:async/stream_controller.dart:628)
#45     _StreamController.add (dart:async/stream_controller.dart:574)
#46     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseX64 sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/usr/local/google/home/regis/dart2/sdk/.packages --format=machine --no-hints /usr/local/google/home/regis/dart2/sdk/tests/language/regress_29243_test.dart
Took 0:00:02.486382

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2analyzer -rnone -t240 language/regress_29243_test

**Comment by bwilkerson** [comment]
@scheglov Is this related to your recent revert?

**Comment by scheglov** [comment]
No, it's not related to the rolled back [change](d2a1bdff4a2b53ef627152fda9f720e754ce7def).

But it looks like something that I missed in 7696ec5f31e32939728641c28caf0d607fcbdbba.

**Comment by scheglov** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/54f845cfd2bcb36213e10ff5ea994d1cd86e9bee.
