### ISSUE TITLE
Coverage misses lines

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#29330]
I know it would be more sensible that somehow I screwed up my code. But I am pretty sure I found a line that is executed but that does not appear in coverage reports. Its this line: https://github.com/eqdb/eqlib/blob/577fa73ef68d0560c03456da972f53eb5d0501fc/lib/src/codec.dart#L147. Tested here: https://github.com/eqdb/eqlib/blob/577fa73ef68d0560c03456da972f53eb5d0501fc/test/codec_test.dart#L46.

When I add a print prior to the line the print is executed. When I look in the observatory the line is not covered. When I remove the line my test fails (it expects an argument error as you can see in the code mentioned above). My code was different at first where 2 lines were also not covered: https://github.com/eqdb/eqlib/blob/bc0c42fd1aea353a1e71c2ba668b65373364dacf/lib/src/codec.dart#L140
 (I changed it in an attempt to fix the coverage). There are some mentions of a related function being deoptimized (no clue why). If you want to reproduce this, it should be sufficient to clone the repository (http://github.com/eqdb/eqlib), and run `dart -c --observe test/all.dart`.

**Comment by bergwerf** [comment]
I seem to have run into the same issue again. Dart version `Dart VM version: 1.25.0-dev.13.0 (Thu Aug 24 09:34:17 2017) on "linux_x64"`. I suddenly noticed in codecov that some lines were not covered that were covered before even though nothing was changed about those tests or that code. I don't understand how this is possible since the Dart version did not change (I checked in TravisCI where the coverage is generated and uploaded to codecov), only the number of tests. Below is a screenshot of the lines that are not covered. When I run `dart -c --observe test/all.dart`, the output contains the printed 'hello', yet is appears as uncovered. I also don't understand why line 62 is not covered while line 63 and 64 are covered. This is in a different repository than previously.

![image](https://user-images.githubusercontent.com/4458965/29965023-55a8ca76-8f0c-11e7-83c5-bc3cdea567ea.png)

I also checked out older versions and verified the lines were indeed covered there. This is the exact commit where the lines suddenly got uncovered, and I see nothing that might cause that: https://github.com/qedb/expr/commit/aad1f8958d03429207e72661d95867cf06fe8923 (in fact, if I change the test that checks for an argument error, the test fails). Deeper digging reveals that changing the order of the tests causes this (https://github.com/qedb/expr/commit/aad1f8958d03429207e72661d95867cf06fe8923#diff-9021fd2f223c6afe851939839013f247R20).
It seems there is some very weird entropy in the Dart observatory. I really don't like this. I really want an explanation.

Please have a look at this. This seems like a really serious issue. If you need help to reproduce it with my code, feel free to ask.

**Comment by rmacnak-google** [comment]
Likely fixed by 074b43c863f1b72a207f8c930ccda58980411d36
