### ISSUE TITLE
Please merge 5 revisions into dev channel

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#29341]
@whesse @mit-mit @kasperl

These fix some issues with the parsing of generic type aliases.

Please merge, in order:

492eab84ece070ff262b958d0786fa42db9645df
e520fc2a455c16ef5e2bd798ab08a1842c08134d
23f08ec04a1907e43469f080601822431128cd60
e30b56ccbe36686612fc53e1c5da04905eaef969
b277f1023c8a6e553603498710e757c5c7a2c8f1

**Comment by kevmoo** [comment]
@bwilkerson wanna check `30b56ccbe36686612fc53e1c5da04905eaef969` – doesn`t seem to resolve...

**Comment by devoncarew** [comment]
@bwilkerson, perhaps you meant e30b56ccbe36686612fc53e1c5da04905eaef969 ?

**Comment by bwilkerson** [comment]
Sorry, yes, that should have been e30b56ccbe36686612fc53e1c5da04905eaef969.

**Comment by kevmoo** [comment]
:smile: fixed...will delete this conversation

**Comment by whesse** [comment]
Merged in version 1.23.0-dev.11.8
