### ISSUE TITLE
raw_synchronous_socket_test: testShutdown is flaky

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#29343]
Output:

FAILED: none-vm product_x64 standalone/io/raw_synchronous_socket_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
Echo test failed in client.

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:464:5)
#1      Expect.isTrue (package:expect/expect.dart:133:5)
#2      testShutdown (file:///b/build/slave/vm-linux-product-x64-be/build/sdk/tests/standalone/io/raw_synchronous_socket_test.dart:400:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1371)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#7      _Future._complete (dart:async/future_impl.dart:468)
#8      _cancelAndValue (dart:async/stream_pipe.dart:63)
#9      Stream.get:first.<anonymous closure> (dart:async/stream.dart:990)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#14     _StreamController._add (dart:async/stream_controller.dart:628)
#15     _StreamController.add (dart:async/stream_controller.dart:574)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Command[vm]: DART_CONFIGURATION=ProductX64 out/ProductX64/dart --ignore-unrecognized-flags --packages=/b/build/slave/vm-linux-product-x64-be/build/sdk/.packages /b/build/slave/vm-linux-product-x64-be/build/sdk/tests/standalone/io/raw_synchronous_socket_test.dart
Took 0:00:00.396849

Short reproduction command (experimental):
    python tools/test.py -mproduct -t60 --builder-tag no_ipv6 standalone/io/raw_synchronous_socket_test

===
=== 1 test failed
===

Failing expect condition is (socket.available() == 0)

**Comment by zanderso** [comment]
Reading throws because the socket is closed for reading, but there can still be data available for reading in OS buffers, so it looks like this ASSERT is bogus.

**Comment by bkonyi** [comment]
Fixed the flakiness in commit 4ebaac3d29593c8f16220a9cf57a77a8e8535a97. Will remove the bad ASSERT as well.
