### ISSUE TITLE
Please merge 5 revisions into dev channel

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#29345]
@whesse @mit-mit @kasperl

These fix some issues with the parsing of generic type aliases.

Please merge, in order:

f0ae30dca5ada7fc18d7b0c42fc05ff9aa3a64d0
214308773419d67e9380dca38c7332dbd8496988
7696ec5f31e32939728641c28caf0d607fcbdbba
5f28891e617cb109ba3e7a5849dfcb791b8ae3a7
54f845cfd2bcb36213e10ff5ea994d1cd86e9bee

**Comment by whesse** [comment]
Merged in version 1.23.0-dev.11.8
