### ISSUE TITLE
implement case labels

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29352]
_From @jmesserly on July 22, 2015 21:20_

https://github.com/dart-lang/dev_compiler/blob/1c029d0902387059b16866c0c41489e7739ea89a/lib/src/codegen/js_codegen.dart#L2512

rarely used outside tests, but async tests trip on this, so hit while looking at #221. I doubt we need a readable solution, rather just a legal translation or some sort.

_Copied from original issue: dart-archive/dev_compiler#263_

**Comment by jmesserly** [comment]
for now I just commented out those tests.
maybe an intermediate fix would be to not generate invalid code :) ... right now we skip the case label, but we generate `continue label;` which makes JS parser unhappy.

**Comment by vsmenon** [comment]
We're seeing this internally now.

**Comment by jmesserly** [comment]
Hmmm. Mostly pretty straightfoward except for `continue;` with an outer loop. That (apparently) goes to the outer loop in Dart (even though switch is otherwise a target for break/continue labels). So if we introduce a loop to use for switch-continue, we'll have to introduce a label for the outer loop & adjust plain `continue`.

**Comment by davidmorgan** [comment]
Any ETA on this please -- so we can decide to work around or wait. Thanks!

**Comment by vsmenon** [comment]
It's probably a few weeks out (Jenny is out).  Can we work around?  It's usually pretty easy to do in source.

**Comment by jmesserly** [comment]
I suspect we'll get this fix when we move to the new front end/kernel (perhaps by using an optional lowering pass). If not, well, we can address it. I think thus far we've been able to work around it.

**Comment by vsmenon** [comment]
@Markzipan - is this still open?  The test here appears to work now: https://github.com/dart-lang/sdk/issues/36345

**Comment by Markzipan** [comment]
This was fixed for DDK but not DDC. We can close this for now since labels are such a rarely used feature (and we're switching to DDK).
