### ISSUE TITLE
Precompiler fails if signature function's parent is not erased.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#29366]
This is an old issue, but the failure mode is new. It now fails with an assert in precompiler.cc:1010:
`ASSERT(!function.IsRedirectingFactory());
`

To reproduce, comment out this line in class_finalizer.cc:594:
`signature.set_parent_function(Function::Handle());
`

And run any test in the precompiler, for example:
python tools/test.py -cprecompiler -rdart_precompiled -t960 vm/dart/error_stacktrace_test

**Comment by rmacnak-google** [comment]
I think this failure is correct and we should be erasing the parent function. A signature function X may be created based on a function Y that the tree shaker will remove and become the canonical function for that signature. References to X from surviving functions with the same signature should not cause Y to be included in the snapshot.

**Comment by crelier** [comment]
Thanks for looking into this. Your conclusion matches my comments in the source, but I was still puzzled on how the parent can be erased. Anyway, this is not critical anymore. I was afraid I would need to keep the parent to fully support nested generic functions, but with my new approach, this won't be necessary. Closing the bug.
