### ISSUE TITLE
inputElement with EventStreamSubscription not being marked for garbage collection

### ISSUE THREAD

**Issue by mayorbyrne** [dart-lang/sdk#29363]
I've been trying to properly dispose of an event listener I have added to an inputElement, but am having trouble figuring out why it sticks around after running a garbage collection.

I am creating an inputElement like this:
```js
_inputElement = new InputElement()
  ..type = "text"
  ..style.width = "343px"
  ..style.border = "none"
  ..style.outline = "none"
  ..style.borderRadius = "0"
  ..value = "";

new HtmlObject(_inputElement)
  ..x = 5
  ..y = 5
  ..addTo(this);
```

I am adding an event listener like this:
```js
EventStreamSubscription _subscription = _inputElement.onMouseDown.listen((e){
  print('mouse down');
});
```

I am removing the listener like this:
```js
_subscription.cancel();
```

When I check the allocation profile (in Observatory) of the class this code is inside, I see one "currently allocated" instance. After clicking "GC" on the observatory menu, the count remains at 1. If I remove the _subscription altogether from the above code, the count correctly goes down to 0 after running garbage collection. I've also tried nulling out the subscription after the cancel, but I receive the same results.

I'd like to know if I'm correctly adding (and removing) the listener to the inputElement. Any information you can provide as to why this may be happening would be greatly appreciated.

**Comment by mayorbyrne** [comment]
I'm not sure if it's worth noting here, but the garbage collection will only happen if there is no subscription (as mentioned above), and only if I also do not interact with the inputElement. It seems if I call .focus(), .blur(), or .select() on the inputElement, it will remain in allocation.

**Comment by vsmenon** [comment]
Dartium does have some memory leaks around JS interop and DOM access (which happens via JS).  I suspect that is what you are seeing here.  Reference cycles between the Dart VM and the JS VM aren't properly collected.  Note, these are collected when compiling to JS - everything is in the JS VM at that point.
