### ISSUE TITLE
LineSplitter.fuse() method is not seen for analyzer in a strong mode

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29372]
```dart
import "dart:convert";

class TestConverter extends Converter<List<String>, String> {
  String convert(List<String> lst) {
    String s = "";
    for (int i = 0; i < lst.length; i++) {
      s += "+" + lst[i];
    }
    return s;
  }
}

main() {
  LineSplitter ls = new LineSplitter();
  Converter fused = ls.fuse(new TestConverter());
...
}
```

The code above works well and produces no issues in analyzer nostrong mode. But in a strong mode analyzer reports
` error - The method 'fuse' isn't defined for the class 'LineSplitter'`

Tested on Windows x64, dartanalyzer version 1.23.0-dev.11.7

**Comment by vsmenon** [comment]
@floitschG - is this due to strong-mode only typing changes on `LineSplitter`?

**Comment by floitschG** [comment]
Yes.
Closing.
