### ISSUE TITLE
Please merge revision 2a2de1aa2380b1338749bc18c94d953c904f485d into dev channel

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#29374]
@whesse @mit-mit @kasperl
This is to fix a slowdown on Dart2JS that only occurs on some builds, but causes a factor 10 slowdown sometimes.  The issue is that we get too many deopts and a critical function (HInstruction.removeFromList) is not optimized.  The workaround is a partial revert of my change ae8e6705c0e1dd624ec45843879294199c11e368 and ensures we use a megamorphic cache call more eagerly for the == operator.  The megamorphic cache never deopts, avoiding the issue.

<Describe the problem this merge is fixing - include issue numbers if applicable>
https://github.com/dart-lang/sdk/issues/29302

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
2a2de1aa2380b1338749bc18c94d953c904f485d

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
This merged cleanly

**Comment by ErikCorryGoogle** [comment]
Some builds have fast dart2js and some have a slow dart2js snapshot.  Unfortunately the 64 bit Mac build from http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.23.0-dev.11.10/sdk/ built at 18-Apr-2017 07:23 is one of the slow ones.  The Linux and Mac 32bit ones seem to be OK :-/

**Comment by whesse** [comment]
If we rebuild, is there a chance we will get a faster version of the 64-bit Macos SDK?  We could then patch it in to the others.

**Comment by ErikCorryGoogle** [comment]
Yes, that might happen.

Concretely it would be the dart2js snapshot you would want to move into the others.

It would probably be better to take this patch though.

**Comment by whesse** [comment]
Merged in 1.23.0-dev.11.11
