### ISSUE TITLE
Annotation that the argument for a parameter should be a constant

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29381]
`Intl.message` has an `examples:` parameter. See https://www.dartdocs.org/documentation/intl/0.14.0/intl/Intl/message.html

The Map parameter is unused at run time.
The documentation does state: "The examples map must be a valid const literal map".
However, users don't always remember the `const`. It is very expensive to create a map for each call to message().

What we need is a way to enforce that the map is a constant, perhaps an annotation on the parameter that the corresponding argument at the call site must be a constant.

**Comment by bwilkerson** [comment]
If we don't want to add language support to specify that a parameter is required to be a constant value (such as by allowing the `const` modifier to be applied to parameters), then, yes, we could add an annotation for it.

**Comment by matanlurey** [comment]
Is there anyway to repurpose `@literal` for this? @bwilkerson 

It might be confusing to have multiple annotations that all mean "please use const".

**Comment by bwilkerson** [comment]
I wouldn't have a problem using `@literal` on parameters, though I presume that when used for a parameter it wouldn't have the same caveat.

**Comment by lrhn** [comment]
Constant objects in Dart are not intrinsically special. They are objects just like any other instance of the same class. They may have been created at runtime and then canonicalized (that's what the dev-compiler does).

It's easier to say that an expression must be a constant expression than it is to say that a value must be constant. It's technically possible to mark a parameter as `const` and then require that all arguments to it are constant. However, it complicates function types. A `void Function(const List)` must be a super-type of `void Function(List)` (A function accepting `List` can be used wherever a function expecting `const List` is expected, beacuse you can pass constant lists to both). 

All in all, I don't see the benefit of such a feature as outweighing the costs in complexity.

**Comment by natebosch** [comment]
Have we decided that this isn't worth a change in the language? Should we move back to area-analyzer to implement a static check outside of the language?

**Comment by bwilkerson** [comment]
Do we want to be able to apply the annotation to an operator (`int operator+(@mustBeConst p) ...`)? It would be consistent to allow it, but I'm not sure there's much value.

Do we want to be able to apply the annotation to a setter (`void set(@mustBeConst p) ...`)? It could be an interesting way to ensure that a field's value is always a constant, but again I'm not sure there's much value.

**Comment by mosuem** [comment]
The CL for this feature is [here](https://dart-review.googlesource.com/c/sdk/+/357701) in case of any comments.

**Comment by lrhn** [comment]
I would apply the annotation to operator and setter parameters. 
Operators are just methods with funny names, and special calling conventions. And just omitting setters feels inconsistent.

Consider whether we'd want:
```dart
@mustBeConst
String id = "";
```
to apply the `@mustBeConst` to the implicit getter. (That's what we do with other parameter modifiers, like `covariant`.)

**Comment by dcharkes** [comment]
@mosuem and I discussed whether we want propagate consts, and this can lead to a space explosion as detailed in (https://github.com/dart-lang/language/issues/2776#issuecomment-1385393297).

Also, when doing propagation, we quickly get into the question whether control flow should be supported and whether string concatination or any other const-able operation should be supported as discussed above. These can lead to more space explosion.

For now, the use cases in https://github.com/dart-lang/native/issues/153 don't seem to need it.

**Comment by matanlurey** [comment]
This was landed in https://github.com/dart-lang/sdk/commit/b3212540931b06f05f2b149b51284b9cc0298d4a.

In the next Dart release (or sooner if you use an unstable release), the analyzer should trigger for `@mustBeConst`.
