### ISSUE TITLE
Catch deferred loading error doesn't work in Dartium

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#29397]
```
try {
	await setting.loadLibrary();
} catch (ex) {
	//handle offline
}
setting.start();
```
it works in Chrome, doesn't work in Dartium

**Comment by anders-sandholm** [comment]
Version in use?

**Comment by jimmyshiau** [comment]
1.22.1

**Comment by terrylucas** [comment]
How is this working?  loadLibrary is a Future not an async function.  I don't believe await can be used on a function not marked as async.  Aren't you getting an analyzer error?

  try {
    setting.loadLibrary().then((_) {
        setting.start();
    });
  } catch (ex) {
    print("ERROR: $ex");
  }
