### ISSUE TITLE
do not hint that LHS of ??= is unused

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29393]
It appears analyzer it's not recognizing the ??= operator as a use of its LHS. For example, you get a hint of a field being unused in this program:

```dart
class A {
  var _wasDone;
  doOnce() {
    _wasDone ??= doSomething();
  }
  doSomething() {
    print('hi');
    return true;
  }
}

main() {
  var a = new A();
  a.doOnce();  // prints 'hi'
  a.doOnce();  // does nothing
}
```

**Comment by bwilkerson** [comment]
In the given example, I believe that the hint is correct. If the only place a field is referenced is in code that assigns the field, then there would be no observable semantic change if the field were removed.

**Comment by rakudrama** [comment]
The field is initialed to `null`.
It is then tested by ??= and found to be `null`, causing doSomething() to be called and the result, `true` assigned to the field.
Subsequent times it is tested and found to be not null.

The field can be thought of as an 'is-initialized' bit. You can't remove it without changing the program behaviour.

**Comment by bwilkerson** [comment]
Ah, right. I should have seen that.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2832013002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/8f2061e6e34cdef1ce1754467f9f9233912a9414
