### ISSUE TITLE
Adding an import causes type inference to fail

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29398]
Note: I will soon be submitting code to work around this bug, so to reproduce it check out c890c487fe92fb96a2f56b20d7d00c58f571406d.

In IntelliJ, edit the file `pkg/front_end/lib/src/fasta/kernel/frontend_accessors.dart` and add the following import at the top:

    import 'package:front_end/src/fasta/kernel/fasta_accessors.dart' show BuilderHelper;

This produces a large number of "Invalid override" errors.  It's not obvious why the presence of this import would have any effect--my best guess is that it's changing the behavior of the summary linker by putting frontend_accessors.dart and fasta_accessors.dart in the same library cycle.

**Comment by stereotype441** [comment]
@scheglov would you mind having a look at this?  I don't want to distract myself from collaborating with folks in Aarhus.

**Comment by scheglov** [comment]
Absolutely.
Most probably I will able to fix this tomorrow.

**Comment by scheglov** [comment]
I can reproduce it now in a test case.

a.dart
```dart
import 'b.dart';
class A1 {
  int _foo() => 1;
}
class A2 extends A1 {
  _foo() => 2;
}
```

b.dart
```dart
import 'a.dart';
class B extends A2 {}
```

When we link `b.dart`, we perform instance type inference for `B`, which causes us to perform type inference for `A2`. But the instance of `InstanceMemberInferrer` uses the instance of `InheritanceManager` that is configured with the `b.dart` library. So, we cannot inference the return type of `A2._foo`, but we still mark the `A2` element as `hasBeenInferred`.

It seems to me that we should not lock `InstanceMemberInferrer` to use a single `InheritanceManager` instance. We probably should get these instances from `ClassElement` instances, from their `LibraryElement`, so from `LibraryElementInBuildUnit` which know their `InheritanceManager` instances.

**Comment by stereotype441** [comment]
Aha, that explains it!  Thanks for tracking it down.

I like your proposed approach for solving it--let me know if there's anything I can do to help.

**Comment by bwilkerson** [comment]
The `InheritanceManager` holds on to a lot of memory. It isn't clear to me that we want to the element model to hold on to them, despite the fact that the element model is more ephemeral than it used to be.

**Comment by scheglov** [comment]
[The CL](https://codereview.chromium.org/2832893002) is out for review.
Not so brave as I hoped, just using a provider instead of an instance.
Not the 'inheritanceManager' accessor on `LibraryElement`.

**Comment by scheglov** [comment]
FWIW, preliminary measurements show that during analysis of my workspace (analyzer, analysis_server, front_end, dart2js, kernel) we create about `7300` instances of `InheritanceManager` with total size of about `33 MiB` (this excludes size of `Element` instances). This is about `5 KiB` per instance in average.
![image](https://cloud.githubusercontent.com/assets/384794/25247580/13e4de50-25c0-11e7-8660-c299adb20fb7.png)

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ddf683c73290e32fc846aa28c3c0b211540a3624

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ddf683c73290e32fc846aa28c3c0b211540a3624
