### ISSUE TITLE
Type variables and generalized function types confuses me

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29404]
This just blows my mind:

```
class C<T> {
  T Function<T>() Function<T>() Function<T>() t;
}

main() {
  print(new C<T Function<T>() Function<T>() Function<T>()>().runtimeType);
}
```

Is there anyway we could tweak the syntax so that type variables are declared to the left of their usage?

I'm used to this notation:

∀T.()->∀T.()->∀T.()->T

In this case, it easier to see that the last T refers to the last type variable declared.

I think this is why both C++ and Java has the type variables before the return type.

**Comment by munificent** [comment]
Removing area-spec since this is a question about the choice of syntax itself and not the verbiage for how it's specified.

**Comment by floitschG** [comment]
We discussed this again in our language meeting, but decided that we won't change the function-type syntax.

Reasons:

1. it's extremely hard to find a syntax that checks every box and is readable in every circumstance.
2. the current problem also arises with normal methods: `Map<T, List<List<List<List<int>>>>> foo<T>()`. It's a bit weirder to construct, but then again: the examples you provide aren't very common either.
3. the current syntax has some nice properties wrt disambiguation (not needed) and is future-proof wrt nullable types. (At least, from what we expect).

**Comment by lrhn** [comment]
I admit that ` T Function<T>() Function<T>() Function<T>()` is unreadable, but that's because of the naming conflict. If it was written ` R Function<R>() Function<S>() Function<T>()`, then I find it more readable - as higher-order generic function types go, they are never going to be *easy*.
An expression of that type would be:
```dart
<T>() => <S>() => <R>() => null as R;
```
I hope they will be rare.

**Comment by peter-ahe-google** [comment]
Could you provide examples of other syntaxes you tried but rejected?

**Comment by peter-ahe-google** [comment]
?
