### ISSUE TITLE
Missing helpful error message when an expression refers an unknown variable or method

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29401]
![image](https://cloud.githubusercontent.com/assets/405837/25221928/20c84a98-25b7-11e7-96bc-b3fc02aa081a.png)

It seems any usage of an unknown variable or method is treated as `dynamic` and then I get the information that no type can be derived from the expression.
It would be much more helpful to get the information what part of the expression references and unknown variable or method.

**Comment by zoechi** [comment]
Dart VM version: 1.24.0-edge.a73c8d0de14d003ec02250b55f09505891edf375 (Wed Apr 19 16:47:36 2017) on "linux_x64"

**Comment by bwilkerson** [comment]
@scheglov I suspect this diagnostic is a result of type inference. Any chance we have or can get this information?

**Comment by zoechi** [comment]
Just to be sure there is no misunderstanding. The problem was that some reference (`globals` or `form`) didn't exist. I run into this quite a lot and it's really cumbersome to find the mistake.

This is with strong mode and most linter rules enabled (not sure if this is relevant).

**Comment by scheglov** [comment]
Could you publish your enabled set of lints and maybe a test case?
As it is reported now, it would be time consuming for me to try to reproduce this.

**Comment by zoechi** [comment]
I reduced `analytics_options.yaml` to

```yml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
and created a reduced reproduction file containing 

```dart
class FormComponentProperty {}

class Item {
  dynamic data;
}

class Globals {}

class GlobalsService {
  // Globals globals;
}

class FormComponent {}

class Foo {
  Item selectedItem;
  GlobalsService globalsService;

  FormComponentProperty get _dataSourceProperty {
    final formComponent = selectedItem?.data as FormComponent;
    if (formComponent == null) {
      return null;
    }
    return globalsService.globals.findFormComponentPropertyByType(formComponent,
        propertyType: GlobalComponentPropertyType.fhirDataSource);
  }
}
```
Which results in 

![image](https://cloud.githubusercontent.com/assets/405837/25450791/53c41c66-2ac0-11e7-843b-e36ec8a35b6e.png)

In this example when the mouse is positioned over the line below `propertyType: GlobalCompo...` or comment in `// Globals globals;` the error message shows an additional line with more information.
But that doesn't always seem to be the case. 
I'll post such an examples when I run into it again. 
This one should allow to reproduce anyway.

**Comment by zoechi** [comment]
With
```yml
analyzer:
  strong-mode: true
#    implicit-casts: false
#    implicit-dynamic: false
```
I get the expected result that `.globals` is unknown

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
