### ISSUE TITLE
Errors are ignored in broadcast StreamController without listeners

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29403]
The [description](https://api.dartlang.org/stable/1.22.1/dart-async/StreamController/StreamController.broadcast.html) for constructor StreamController.broadcast() reads:

> StreamController.broadcast({
> void onListen(),
> void onCancel(),
> bool sync: false
> })
> A controller where stream can be listened to more than once.
> ...
> The controller does not have any internal queue of events, and if there are no listeners at the time the event is added, it will just be dropped, or, **if it is an error, be reported as uncaught**.

The following sample code shows that errors are just ignored:
```dart
import "dart:async";

main() {
  StreamController controller = new StreamController.broadcast();
  try {
    controller.addError("lost error");
    print("'lost error' is ignored");
  } catch (e) {
    print("caught $e");
  }
}
```
Output:
>'lost error' is ignored

Expected output:
>caught 'lost error'

Dart VM version: 1.22.1 (Tue Feb 21 14:29:45 2017) on "windows_x64"

**Comment by anders-sandholm** [comment]
Unclear to me if this is a VM or async issue. Re-label as you see fit.

**Comment by lrhn** [comment]
Still appears to be the case. Not sure if we really want to make the error into an async uncaught error now, but we should document that it isn't.

**Comment by sgrekhov** [comment]
Documentation has been updated. The current behavior is according to the spec now. Closing this issue
