### ISSUE TITLE
Fix mirror for protobuf

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29418]
Our mirror for protobuf (used by DEPS):

https://chromium.googlesource.com/external/github.com/dart-lang/dart-protobuf.git

has stopped updating - presumably because the repo changed from `dart-protobuf` to `protobuf`.  I've patched DEPS to point directly to github for now.

**Comment by vsmenon** [comment]
@whesse @jakobr-google

**Comment by zanderso** [comment]
It looks like this issue may be slipping through the cracks, but keeping these DEPS pointing at the mirror is something that we need to do to support Fuchsia's build of the Dart SDK. I'll bump the priority.

**Comment by athomas** [comment]
Closing, uses the protobuf uses the mirror.
