### ISSUE TITLE
Analzyer doesn't correctly resolve package paths when inside a folder named `packages`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#29414]
This was raised by @abarth at https://github.com/Dart-Code/Dart-Code/issues/275 but based on comments from @bwilkerson it sounds like the analysis server should handle this for us. I've stripped the flutter repo right down to make a really simple repro (attached).

The folder structure looks like this:

```text
flutter-set-me-as-analysis-root/
   |- packages/
      |- flutter/
         |- .packages
         |- pubspec.lock
         |- pubspec.yaml
         |- lib/
            |- foundation.dart
            |- src/
               |- widgets/
                  |- drag_target.dart
```

The `drag_target.dart` file just contains `import 'package:flutter/foundation.dart';` and the .packages folder contains `flutter:lib/`. It seems like the pubspec.yaml should cause the `flutter` folder to be treated as a root and the package resolved correctly, however it doesn't seem to (it seems to use the `flutter-set-me-as-analysis-root` folder as a root for resolving packages.

[repro.zip](https://github.com/dart-lang/sdk/files/946501/repro.zip)

**Comment by DanTup** [comment]
Whoops, I forgot the logs. Here's the Dart Code log (analyzer communication) as well as the instrumentation file.

[analyzer.instrum.txt](https://github.com/dart-lang/sdk/files/946535/analyzer.instrum.txt)
[analyzer.txt](https://github.com/dart-lang/sdk/files/946534/analyzer.txt)

**Comment by bwilkerson** [comment]
My first guess is that server might be getting confused because this is inside a directory named 'packages', which used to have special meaning in the Dart ecosystem (being the thing that `.packages` files replaced).

**Comment by DanTup** [comment]
@bwilkerson Looks like you guess right.. Renaming it to `packages2` results in the error going away and an `unused import` warning (in the repro I deleted all the code).

Is this something you think should change in the analyzer or should naming folders `packages` continue to be avoided?

**Comment by bwilkerson** [comment]
It needs to change in analyzer. I'm just not sure how soon that's likely to happen, though there's a chance that we will get to it this quarter as part of a larger arc of work.

**Comment by DanTup** [comment]
Thanks for the info; I'll put some notes about this on the original DC issue. Thanks!

**Comment by abarth** [comment]
@bwilkerson What's involved in removing the special case for directories named "packages"?  My understanding is that the Dart ecosystem has fully converted to `.packages` files at this point.

**Comment by alexander-doroshko** [comment]
Would be great to remove the `--packages-dir` flag from the `pub` tool to complete the story! :)

**Comment by bwilkerson** [comment]
Yeah, the fact that `pub` can still generate `packages` directories is a complicating factor.

The biggest implementation issue is that the logic to find context roots is spread out across numerous places in the code base. One of my tasks this quarter is to unify that into a single consistent piece of code, and this problem should be fixed as part of that work (if someone doesn't fix it before then).

**Comment by DanTup** [comment]
> One of my tasks this quarter is to unify that into a single consistent piece of code, and this problem should be fixed as part of that work (if someone doesn't fix it before then).

Was any progress made on this (or is it still planned)? I'd love to remove the workaround in Dart Code since it has some "issues"!

**Comment by bwilkerson** [comment]
It's still planned, but now it's targeted for Q3, assuming nothing higher priority comes up.

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/commit/7cbd0f55b5b6c47c64cb9ee2267862c0f08f0d95

🎉🎉🎉

Thanks @devoncarew! Could we bump the server version so I know when I don't have to use my workaround?

**Comment by devoncarew** [comment]
We can; do you mind making a PR for it?
