### ISSUE TITLE
upgrade chrome on mac bots

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29413]
/cc @whesse @mkustermann 

chrome got upgraded on the linux bots and we started seeing some failures as a result. I updated all the status files (mostly co19 tests) and managed to rdesktop to the win bots to force an update of chrome there.

For some reason I've not been able to connect to the mac bots using vnc. I'm now requesting a graceful reboot and see if that lets me connect, but it could very well be an issue with my setup.

**Comment by whesse** [comment]
I also know all the commands to do a command line upgrade of chrome on the
Mac bots, so I will do that now.

**Comment by whesse** [comment]
Connecting to the mac bots requires a special vnc client, I think, free-something.
I connected with ssh to the one mac bot running chrome, and updated with:

curl https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg -o chrome.dmg
open chrome.dmg
sudo rm -rf /Applications/Google\ Chrome.app
(Note the final slash on one arg, but not the other, in the next line.  This is needed.)
sudo cp -R /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/

Test with:
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version

sudo shutdown -r now

**Comment by sigmundch** [comment]
Ah, thanks! I was trying to do it on the commandline and didn't know how (because landing on the help chrome internal page triggers an update I even tried running chrome and set it's address to chrome://help from the commandline, but no luck there). Glad to hear there are some easy steps for that!
