### ISSUE TITLE
Extra invalid fields for unrecognized union type in comment syntax

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29424]
Given a class that looks like this, which is valid Dart but has invalid comment syntax (invented union type):

```dart
import 'dart:async';

abstract class A {
  Future/*<String | List<int>>*/ futureStringOrInt();
}
```

If you analyze that in strong mode you get a ClassElementImpl with two fields whose name is the empty string, one with a type of `Future<String>` and one with the type of `List<int>`. The return type of the method looks like it ends up just being `dynamic` as well.

Below is a pretty printed linked summary of that file:

```
{
  version: 1.0,
  linkedLibraryUris: ["file:///..."],
  unlinkedUnitUris: ["file:///..."],
  library "file:///...": {
    dependencies[0]: {uri: "file:///..."},
    dependencies[1]: {
      parts[0]: "dart:async/async_error.dart",
      parts[1]: "dart:async/broadcast_stream_controller.dart",
      parts[2]: "dart:async/deferred_load.dart",
      parts[3]: "dart:async/future.dart",
      parts[4]: "dart:async/future_impl.dart",
      parts[5]: "dart:async/schedule_microtask.dart",
      parts[6]: "dart:async/stream.dart",
      parts[7]: "dart:async/stream_controller.dart",
      parts[8]: "dart:async/stream_impl.dart",
      parts[9]: "dart:async/stream_pipe.dart",
      parts[10]: "dart:async/stream_transformers.dart",
      parts[11]: "dart:async/timer.dart",
      parts[12]: "dart:async/zone.dart",
      uri: "dart:async"
    },
    dependencies[2]: {
      parts[0]: "dart:core/annotations.dart",
      parts[1]: "dart:core/bool.dart",
      parts[2]: "dart:core/comparable.dart",
      parts[3]: "dart:core/date_time.dart",
      parts[4]: "dart:core/double.dart",
      parts[5]: "dart:core/duration.dart",
      parts[6]: "dart:core/errors.dart",
      parts[7]: "dart:core/exceptions.dart",
      parts[8]: "dart:core/expando.dart",
      parts[9]: "dart:core/function.dart",
      parts[10]: "dart:core/identical.dart",
      parts[11]: "dart:core/int.dart",
      parts[12]: "dart:core/invocation.dart",
      parts[13]: "dart:core/iterable.dart",
      parts[14]: "dart:core/iterator.dart",
      parts[15]: "dart:core/list.dart",
      parts[16]: "dart:core/map.dart",
      parts[17]: "dart:core/null.dart",
      parts[18]: "dart:core/num.dart",
      parts[19]: "dart:core/object.dart",
      parts[20]: "dart:core/pattern.dart",
      parts[21]: "dart:core/print.dart",
      parts[22]: "dart:core/regexp.dart",
      parts[23]: "dart:core/set.dart",
      parts[24]: "dart:core/sink.dart",
      parts[25]: "dart:core/stacktrace.dart",
      parts[26]: "dart:core/stopwatch.dart",
      parts[27]: "dart:core/string.dart",
      parts[28]: "dart:core/string_buffer.dart",
      parts[29]: "dart:core/string_sink.dart",
      parts[30]: "dart:core/symbol.dart",
      parts[31]: "dart:core/type.dart",
      parts[32]: "dart:core/uri.dart",
      uri: "dart:core"
    },
    importDependencies: [1, 2],
    numPrelinkedDependencies: 3,
    defining compilation unit: {
      references[0]: {kind: unresolved},
      references[1]: {name: "Future", dependency: 1 (dart:async), numTypeParameters: 1, unit: 4},
      references[2]: {name: "String", dependency: 2 (dart:core), unit: 28},
      references[3]: {name: "List", dependency: 2 (dart:core), numTypeParameters: 1, unit: 16},
      references[4]: {name: "int", dependency: 2 (dart:core), unit: 12},
      apiSignature: [204, 148, 237, 176, 180, 17, 0, 124, 30, 244, 107, 55, 244, 26, 208, 252],
      classes[0]: {
        name: "A",
        codeRange: {length: 74, offset: 22},
        executables[0]: {
          name: "futureStringOrInt",
          codeRange: {length: 20, offset: 74},
          inferredReturnTypeSlot: 3,
          isAbstract: true,
          nameOffset: 74
        },
        fields[0]: {
          codeRange: {length: 16, offset: 43},
          inheritsCovariantSlot: 1,
          nameOffset: 59,
          type: {reference: 1 (Future), typeArguments: [{reference: 2 (String)}]}
        },
        fields[1]: {
          codeRange: {length: 9, offset: 61},
          inheritsCovariantSlot: 2,
          nameOffset: 70,
          type: {reference: 3 (List), typeArguments: [{reference: 4 (int)}]}
        },
        isAbstract: true,
        nameOffset: 37
      },
      codeRange: {length: 97},
      imports: [{uri: "dart:async", uriEnd: 19, uriOffset: 7}, {isImplicit: true}],
      lineStarts: [0, 21, 22, 41, 95, 96],
      publicNamespace: {names: [{name: "A"}]}
    }
  },
  apiSignature: "edb1f63e53624083aa2aaa8137f00a95",
  dependencies: [{apiSignature: "aac9eb543fe396e5b6f2607aa4f77106", includesDartUris: true}],
  unlinkedUnitHashes: ["5ca1a4cf0fc7c01760903989fad07b6d"]
}
```

This is causing dartdevc to choke on the unnamed field.

**Comment by bwilkerson** [comment]
So the first thing I'll note is that the code above currently produces compilation errors, and I might suggest that ddc should test for compilation errors and refuse to produce output for files containing compilation errors. (If ddc really does need to produce partial output for invalid code, then it really needs to guard against this kind of AST structure, because this isn't the only way to get this structure to be produced.) Either of those solutions would solve this problem.

But the second thing I'll note is that it probably wouldn't be too hard to fix the parser such that if the "type" in a comment isn't a single valid type it will just be dropped as if the comment weren't one of the special comments. That doesn't solve the general problem, though, it only solves this particular manifestation of it, so I'd still recommend one of the two approaches given above.

What do you think?

**Comment by jakemac53** [comment]
Generally yes, dartdevc would error out earlier on this code. However if you add the `--unsafe-force-compile` flag it will attempt to compile it anyways, and give you the error about empty field names.

I think it make sense for the analyzer to just throw away things like this and treat it like a normal comment. For instance if you have a place where you really want a union type you should be able to add a comment that looks roughly like this to describe the types you actually accept.

**Comment by bwilkerson** [comment]
> However if you add the `--unsafe-force-compile` flag it will attempt to compile it anyways ...

Which means that ddc will have to deal with invalid code like this without depending on analyzer to sanitize the code for them. For example, try to compile the following:
```
import 'dart:async';

abstract class A {
  Future<String | List<int>> futureStringOrInt();
}
```
(exactly as above except removing the comment markers).

> I think it make sense for the analyzer to just throw away things like this ...

If the comment form were going to be around longer I think I'd actually argue against that. After thinking about it a little longer I realized that the downside of this change is that analyzer would stop giving errors when users have invalid code in these comments, and that means that a user could think that they've correctly specified a type when they haven't. That could be extremely confusing. However, given that the comment form should be going away fairly soon, I don't care as much.

But on the flip side, given that ddc needs to deal with this AST no matter what we do in terms of comments, I don't think it makes any sense to spend time on analyzer. We just need to fix ddc.

**Comment by jakemac53** [comment]
This is more of a comment syntax issue in general I guess, but IMO the above dart code should be correct and valid, even in strong mode. Since it can't be parsed as an actual type it should be ignored. Essentially, I shouldn't be able to type anything in comments that causes my app to fail (maybe it would be a hint?). I don't know if the comment syntax is actually spec'd out to say this is the correct behavior or what though.

In any case, if the comment syntax is going away then I don't think this matters at all, and I agree it probably isn't worth putting time into fixing.

**Comment by bwilkerson** [comment]
I never saw any kind of specification for the comment syntax, unless you count the implementation as a de facto spec.

> ... if the comment syntax is going away ...

It isn't needed any more because the generic method syntax is fully supported, it's just a question of how long we need to give users in order to allow them to migrate to the real syntax.

**Comment by jakemac53** [comment]
This also might just be more of an analyzer_cli issue - it will happily produce summaries for this file without errors, and the summary will be wrong. I don't think it does any error checking, although that is probably for performance reasons?

**Comment by bwilkerson** [comment]
Yes, I believe that the cli's build mode assumes that all files will be valid. And yes, I believe that was for performance reasons.

If you're running into files that have been committed with errors, then that's a slightly different problem :-).

**Comment by jakemac53** [comment]
This is more about being able to compile arbitrary packages which weren't created using strong mode analyzer with as high of a success rate as possible (as I said where I came across this it was a 2 year old change).

Ideally as few packages as possible will actually need changes to work in strong mode, and this seems like a bit of a `gotcha` case to me where old comments will break things.

**Comment by jmesserly** [comment]
I think this is fixed (comment syntax is gone)
