### ISSUE TITLE
strong mode does not check ClassTypeAlias syntax form

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29426]
Strong mode does not check ClassTypeAlias syntax form.

This affects all of our checking. For example, consider this from our tests:
```dart
class A {}
class B {}

abstract class I {
    m(A a);
}

class M {
    m(B a) {}
}

class /*error:INCONSISTENT_METHOD_INHERITANCE*/T1
    extends Object with /*error:INVALID_METHOD_OVERRIDE_FROM_MIXIN*/M
    implements I {}

// BUG BUG BUG these should also have errors
class T2 = Object with M implements I;
class T3 extends T2 {}
```
T2/T3 produces no errors at all, unlike the (very similar) T1.

**Comment by bwilkerson** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/29448.

**Comment by jmesserly** [comment]
@bwilkerson -- see above, this is not at all related to fields! I think maybe my description was confusing. I will remove the "originally reported at" line :)

**Comment by jmesserly** [comment]
Also BTW: I have a CL in progress :)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2837173002/
