### ISSUE TITLE
Crash in dartk-vm debug-x64 fuzz test.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29439]
FAILED: dartk-vm debug_x64 lib/mirrors/invocation_fuzz_test/smi
Expected: RuntimeError 
Actual: Crash

See: https://build.chromium.org/p/client.dart/builders/vm-kernel-linux-debug-x64-be/builds/1328/steps/vm%20tests/logs/stdio

**Comment by whesse** [comment]
Permalink to the log: https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-kernel-linux-debug-x64-be%2F1328%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout

**Comment by kmillikin** [comment]
The crash seems to be fixed and the test is now timing out, possibly hanging.
