### ISSUE TITLE
analysis server (behind IDE) stopped respecting excludes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29430]
I have an IntelliJ project with 4 Dart packages as content root

In one package I have a directory  `tmp` with some invalid code and and `analysis_options.yaml` file with
```yml
  exclude:
    - 'tmp/**'
```
Since updating to 
> Dart VM version: 1.24.0-edge.3dbe0099a249247c14f38301ccf3dfaeee97fe3c (Fri Apr 21 01:54:41 2017) on "linux_x64"

I get errors reported from this `tmp` directory.

**Comment by bwilkerson** [comment]
Is this with the command-line analyzer, or with analysis server?

**Comment by zoechi** [comment]
IDEA integrated analysis server

**Comment by devoncarew** [comment]
@zoechi, if you close all the files, and re-analyze (re-start the analysis server), do you still see these issues? I'm wondering if these only show up once you've opened files in `tmp/`.

**Comment by zoechi** [comment]
Can't reproduce anymore. Thanks for having a look.

**Comment by zoechi** [comment]
I again had this. 
Not sure yet when this is happening. I'll keep observing and update when I know more.

**Comment by rkirsling** [comment]
`exclude` seems to be completely non-operational in 1.25.0-dev.4.0.

Minimal repro:

**foo/bar.dart**
```dart
main() {}
```
**analysis_options.yaml**
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - foo/bar.dart

linter:
  rules:
    - always_declare_return_types
```
**CLI**
```
λ dartanalyzer .
Analyzing test...
  error • Missing return type for 'main' at foo/bar.dart:1:1 • strong_mode_implicit_dynamic_return
  lint • Declare method return types at foo/bar.dart:1:1 • always_declare_return_types
1 error and 1 lint found.
```

**Comment by devoncarew** [comment]
@rkirsling, excludes doesn't currently work with the command-line analyzer.

**Comment by rkirsling** [comment]
Hmm, that's good to know, but I'd already confirmed that the above happens in VSCode and WebStorm, and only switched to the CLI to try to create a "least common denominator" scenario.

**Comment by zoechi** [comment]
Excludes also don't work for me anymore (imported or not)

[✓] Flutter (Channel master, v0.5.8-pre.215, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.215 at /Users/zoechi/flutter/flutter
    • Framework revision eda03e2586 (22 hours ago), 2018-08-02 12:02:32 +0200
    • Engine revision a76054f4b6
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

**Comment by devoncarew** [comment]
@rkirsling, thanks again for the repo. I don't see the issue when I create a project as above; I do see it as soon as I open the `foo/bar.dart` file. The exclusions aren't respected by the priority files set by the IDE - ones open and focused by the user.

@zoechi, does this sound like your issue as well, or something different?

**Comment by rkirsling** [comment]
@devoncarew Yeah, I can confirm that `exclude` seems to work from the CLI with my steps above as of `2.0.0-dev.69.5`.

**Comment by amreniouinnovent** [comment]
@rkirsling still facing the issue
I used this command dartanalyzer --options analysis_options.yaml .
version: dartanalyzer version 2.5.0-edge.b5aeaa67960c03e528b76c5cfa55059a058de34
related issue
https://github.com/dart-lang/sdk/issues/28463
https://github.com/dart-lang/linter/issues/1650

**Comment by pq** [comment]
FWIW @stereotype441 et al., there's another related report in https://github.com/dart-lang/linter/issues/320#issuecomment-628241212.

**Comment by srawlins** [comment]
@amreniouinnovent since you are indicating the command line `dartanalyzer`, your issue is https://github.com/dart-lang/sdk/issues/45000. This issue is for the analysis server which does work for IDEs.

**Comment by srawlins** [comment]
Unfortunately, I think we need a good reproducible repro for this issue to make progress. Steps from "open IDE" to "unexpected analysis appears." Please report if you have good steps! 🤞
