### ISSUE TITLE
Typo in CompressionOptions documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29438]
Please see https://api.dartlang.org/stable/1.23.0/dart-io/CompressionOptions/clientMaxWindowBits.html

> int clientMaxWindowBits
> final
> Sets the Max Window Bits for the Client.

and https://api.dartlang.org/stable/1.23.0/dart-io/CompressionOptions/serverMaxWindowBits.html

> int serverMaxWindowBits
> final
> Sets the Max Window Bits for the Server.

These fields are final and cannot be used as setters

**Comment by srawlins** [comment]
Fixed.
