### ISSUE TITLE
Dart 1.23 (strong mode) can not infer the type well

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#29437]
With the following code:

```
const dur = const Duration(seconds: 10);
final val = dur.inSeconds;
```

Dart 1.23 (dartanalyzer) said "hint • The type of 'val' can't be inferred because of the use of the instance getter 'inSeconds'"

> Note: there is no such issue in Dart 1.22.1

**Comment by mit-mit** [comment]
@floitschG language or analyzer issue?

**Comment by bwilkerson** [comment]
I believe that analyzer is implementing the specification correctly.

**Comment by mit-mit** [comment]
But the implementation changed in 1.23 (the original bug text says it worked in 1.22.1)?

**Comment by leafpetersen** [comment]
Strong mode top level inference restrictions  (https://github.com/dart-lang/sdk/pull/28218) were incrementally rolled out in 1.23 (note that we issue a hint not an error).  These will become errors in 1.24.

**Comment by tomyeh** [comment]
Sorry, I don't get it. Does it mean I have to specify the type explicitly even though it can be inferred from the expression? And, this restriction is only applied to top-level variables, while local variables has no such limitation?

**Comment by leafpetersen** [comment]
We've rolled back the proposed restrictions to top level inference.  This should work again.
