### ISSUE TITLE
ValidateStackFrameIteration is flaky with low --optimization_counter_threshold

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#29440]
This test fails about 1 time in 20 on a loaded machine. Can't repro in debug mode.  Start tests on all CPUs in another window, then run about 20 times:

./out/ReleaseX64/run_vm_tests --optimization_counter_threshold=5 ValidateStackFrameIteration

Also fails on SIMMIPS and SIMARM64.  The error is:

../../runtime/vm/verifier.cc: 55: error: Invalid object pointer encountered 0x7f4c19410fa0

The object in question is not in the allocated_set_.  It is a Type object that looks pretty valid.

**Comment by rmacnak-google** [comment]
I suspect this was fixed by 466385ceb6cb03835d5e860e6aeff689e62fd5a0. Previously, allocation in the background compiler (which is more active with a low threshold) could still continue between building the object set and checking the pointers.
