### ISSUE TITLE
Dart 1.23: analyzer tries to infer a variable declared as dynamic

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#29443]
In Dart 1.23, without strong-mode: the analyzer tries to infer the type of a variable declared as `dynamic`.

in `main.dart`
```dart
import 'lib1.dart';

void main() {
  dynamic myB = getB();
  myB.foo();
}

class A {}

A getB() => new B();
```
In `lib1.dart`
```dart
import 'main.dart';
class B extends A {
  foo() {}
}
```

The analyzer reports: 
INFO: The method 'foo' isn't defined for the class 'A'. (main.dart:5)

As I have declared `myB` as dynamic, I think the analyzer should not give me a warning.

Note that I don't have a warning if A and B are in the same file.

**Comment by bwilkerson** [comment]
I don't know why it makes a difference whether the class `B` is defined in the same or a different file, but I can tell you that type propagation, which is the feature that's causing this behavior, will be removed in favor of the strong-mode type inference feature in the relatively near future.

**Comment by bwilkerson** [comment]
Type propagation has been removed, so I'm assuming that this is stale. Please let us know if you're still seeing this problem.
