### ISSUE TITLE
Need clarification on strong mode semantics of field overrides

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#29448]
See https://github.com/dart-lang/sdk/issues/29426 for some background.

For a while strong mode disallowed fields in subclasses that overrode fields in superclasses. IIRC, this included getters and setters. Then I thought we had relaxed that. Now we're being asked to produce diagnostics of some form. I need a clearly written specification of what the semantics are in strong mode, including errors and warnings that should be produced.

**Comment by jmesserly** [comment]
errr, I think this bug was a misunderstanding! I'm going to close it out :)
