### ISSUE TITLE
Invalid encoding in filename crashes the VM

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#29451]
### Steps to reproduce:

1. In Linux...
2. Create an empty directory
3. In the directory, create a file named `¶.txt`
4. Install the `convmv` tool: `sudo apt-get install convmv`
5. Convert the filename to Windows encoding: `convmv --notest -f UTF-8 -t ISO-8859-1 ¶.txt`
6. Create a `test.dart` file in the same directory, like so: https://gist.github.com/tvolkert/36ad0283101269d8bdaf76c7311b1370
7. run `dart test.dart`

### Result

The VM crashes with the following message:

```
$ dart test.dart 
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
```

### Notes

This may happen on other platforms as well, but the existence of the `convmv` tool makes it easiest to reproduce on Linux.

**Comment by a-siva** [comment]
Are you expecting us to support such filenames or the bug is to ensure the VM produces a sane Dart exception?

**Comment by tvolkert** [comment]
It should produce a sane Dart exception.  I'm operating under the assumption that a VM crash is never the right behavior.

**Comment by Hixie** [comment]
It shouldn't even produce an exception. There's nothing that says file systems should use UTF-8 as far as I can tell. The right behaviour is for the file names to be returned as byte sequences.

**Comment by aam** [comment]
Can you really return just a byte stream without assuming some encoding?
For example, if we assume that you can't have '/' in a filename, does it mean that you parse the filename as a ASCII stream, UTF-8 stream or use some other encoding?

**Comment by Hixie** [comment]
> Can you really return just a byte stream without assuming some encoding?

Sure, that's what Uint8List is.

> For example, if we assume that you can't have '/' in a filename, does it mean that you parse the filename as a ASCII stream, UTF-8 stream or use some other encoding?

For display purposes you can probably assume UTF-8, but the actual file name (which is what this API is dealing with) is just a stream of bytes, as far as I can tell.  See for example the discussion at https://www.j3e.de/linux/convmv/man/

**Comment by Pacane** [comment]
I've hit this too with flutter this week. It was very hard to diagnose.

**Comment by Hixie** [comment]
We are getting an increasing number of reports of this as Flutter extends past US-ASCII environments.

**Comment by bkonyi** [comment]
I'm going to make this throw a `FileSystemException` for now just so it's clear what's causing the error.  We still need to figure out whether or not we want to extend the file system APIs to support arbitrary byte buffers or if there's a better way of handling non-UTF-8 encodings.

**Comment by Hixie** [comment]
Maybe it should throw a NotImplementedError or some such, to make it clearer that we understand that it's a bug on our part.

**Comment by bkonyi** [comment]
Sure, that sounds reasonable. I'll do that instead.

**Comment by dgrove** [comment]
@bkonyi - can you please move this to Dart2-beta3/beta4/stable, or remove the milestone?

**Comment by bkonyi** [comment]
I've moved it to the beta3 milestone for now. @zanderso, let's discuss this and #32583 next week.

**Comment by dgrove** [comment]
Any updates here?

**Comment by zanderso** [comment]
I think the right approach would be for @bkonyi to take over https://github.com/dart-lang/sdk/pull/32583.

**Comment by bkonyi** [comment]
Yes, I'll take it over.

**Comment by bkonyi** [comment]
Initial work for synchronous FileSystemEntity methods is [done](https://dart-review.googlesource.com/c/sdk/+/51580/1). Will hopefully get the async methods updated soon.
