### ISSUE TITLE
Please merge revision #38e8b1509e8c983cd454c86d1f10561dc0de1ae0 into stable channel

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#29450]
@whesse @mit-mit @kasperl
<Fill in the labels for Milestone and Area to indicate what the merge applies to. E.g. if you're requesting a merge to fix an issue in Dart2JS, set the area to Area-Dart2JS. If this is a request to merge to stable please change the MergeToDev label to MergeToStable>

<Describe the problem this merge is fixing - include issue numbers if applicable>
This fixes (1) from https://github.com/dart-lang/sdk/issues/29109#issuecomment-293317477

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
38e8b1509e8c983cd454c86d1f10561dc0de1ae0

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
This merged cleanly

**Comment by whesse** [comment]
We have now released stable 1.24, which contains this revision.
