### ISSUE TITLE
URI parser does not support RFC 6874

### ISSUE THREAD

**Issue by raggi** [dart-lang/sdk#29456]
Currently the URI parser explodes on scoped IPv6 addresses. The URI standard was extended by RFC 6874 to support scopes.

The end result is that specifying an address such as:

`http://[fe80::a%25en1]`

Results in the following error:

```
FormatException: FormatException: Illegal IPv6 address, an IPv6 part can only contain a maximum of 4 hex digits (at character 15)
http://[fe80::a%25en1]
```

The expected result is that this resolves to `fe80::a%en1`.

**Comment by tamird** [comment]
https://dartpad.dartlang.org/8ed6391bce8ea079b5b83651e7e03646

**Comment by zanderso** [comment]
Marking P1 to match Fuchsia issue CONN-93.

**Comment by sethladd** [comment]
Yes please :) Just ran into this, it's blocking an important workflow. Thanks for the help!

**Comment by a-siva** [comment]
CL where work on this is progressing https://dart-review.googlesource.com/c/sdk/+/103544

**Comment by sethladd** [comment]
Thank you!

**Comment by tamird** [comment]
Update: parsing works, but making requests to such URIs does not. Filed https://github.com/dart-lang/sdk/issues/37570.

**Comment by IkkiRama** [comment]
kontol
