### ISSUE TITLE
Remove @override setting in IntelliJ

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#29462]
We no longer require @override to override fields: https://github.com/dart-lang/sdk/issues/28117

Does that mean we can remove this setting in IntelliJ?
![screen shot 2017-04-25 at 12 49 11](https://cloud.githubusercontent.com/assets/13644170/25381890/c6755916-29b5-11e7-905e-57504fa2da02.png)

**Comment by alexander-doroshko** [comment]
@mit-mit this option is not related to the analysis server or any other part of the SDK. Quick fixes / quick assists from the SDK are not configurable and AFAIK they do insert `@override` when possible. This IDE setting is for similar actions that are implemented at IDE side without using the analysis server.

**Comment by mit-mit** [comment]
Sorry, I don't know what that means. Can you give an example of how this is used?

**Comment by alexander-doroshko** [comment]
@mit-mit I mean I by chance noticed an issue filed in the Dart SDK issue tracker and decided to mention that this setting in IntelliJ is not related to anything from the Dart SDK git repository, so probably this is not the best place to track/discuss.

**Comment by alexander-doroshko** [comment]
Background info:
Quick fix to implement missing members that comes from the Analysis Server is not configurable and as of now it always inserts `@override`:
![image](https://cloud.githubusercontent.com/assets/4499789/25387318/17048eca-29d3-11e7-83dc-e55b796f7010.png)

The Dart plugin also has its own actions to override or to implement members. Implementation is fully at the plugin end, it doesn't use Analysis Server. Shortcuts are `Ctrl+I` and `Ctlr+O`, also available via Generate menu (`Cmd+N` or `Ctrl+Enter`). These actions do use the setting from your screenshot. Issues related to these IDE-level actions are welcome in https://youtrack.jetbrains.com/issues/WEB
![image](https://cloud.githubusercontent.com/assets/4499789/25387570/fa122c72-29d3-11e7-862a-65ff0e6d7723.png)

**Comment by mit-mit** [comment]
Thanks, I understand. We can close this.
