### ISSUE TITLE
Support Iterable.addAll(null)

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#29470]
Seems sensible in the spirit of .add(null) being allowed and the various nullable operators like ?.

**Comment by lrhn** [comment]
An iterable like `List` or `Set` does allow `add(null)`, but it actually adds the `null` value to the collection, it doesn't ignore the value.
I don't expect that you want `.addAll(null)` to add `null` to the collection, more likely you do want it to be ignored (considered equivalent to an empty collection).
The `addAll` method expects a collection, and giving it no collection is different from giving it an empty collection. Allowing `null` to be passed is more likely to hide an error than it is to be deliberate, so silently ignoring it has drawbacks too.
If Dart gets non-nullable types, the `addNull` method will likely use a non-nullable `Iterable<E>` as argument type.

So, all in all, we don't plan to allow this.

**Comment by xster** [comment]
I don't feel strongly about this/feel free to ignore: wouldn't the differentiation come from
`.addAll(null)` and `.addAll(new Iterable<E>.empty())` or something equivalent though?
