### ISSUE TITLE
FutureOr is exported by dart:async, but is unused?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29474]
`Dart VM version: 1.24.0-dev.0.0 (Fri Apr 21 05:37:22 2017) on "macos_x64"`

```dart
// Unused import.
import 'dart:async';
import 'dart:convert';
import 'dart:io';

String _cachedFeed;

FutureOr<String> getPackages() async {
  final packagesAtom = Uri.parse('https://pub.dartlang.org/feed.atom');
  return _cachedFeed ??= await new HttpClient()
      .getUrl(packagesAtom)
      .then((r) => r.close())
      .then(UTF8.decodeStream);
}
```

**Comment by lrhn** [comment]
The analyzer reports that the `dart:async` import is unused.

**Comment by bwilkerson** [comment]
I cannot reproduce this on bleeding edge using either the command-line analyzer or the analysis server. Can you tell me how to reproduce the behavior you're seeing?

**Comment by matanlurey** [comment]
I encountered it while writing https://github.com/matanlurey/dart-future-examples/blob/master/bin/5_using_future_or.dart (before I used `Future` explicitly).

**Comment by matanlurey** [comment]
I haven't seen this in ~6 months.
