### ISSUE TITLE
The analyzer crashes with funtion type literal as type bound.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29483]
Example:
```dart
class C<T extends num Function(num)> {
//class C<T extends numfun> {
  final T func;
  C(this.func);
}
main() {
  var c = new C<int Function(int)>((int x)=>x*2);
  print(c.func(21));
}
typedef num numfun(num x);
```
This fails to compile. If switching to the commented out line instead, it will work, so the problem is with recognizing the new function type syntax in the type parameter bound, not function types in general.

The stack trace starts with:
```
Invalid argument(s): Cannot resolve a GenericFunctionTypeImpl
#0      TypeParameterBoundsResolver._resolveTypeParameters (package:analyzer/src/generated/resolver.dart:8928:17)
```

**Comment by bwilkerson** [comment]
Obviously analyzer shouldn't crash.

That said, I seem to recall having been told at one point that generic function types were not going to be supported as bounds for type parameters. Has that changed?

**Comment by leafpetersen** [comment]
It is a static error to instantiate a generic with a *generic* function type, or to use a generic function type as a bound on a generic type variable.  Regular function types are ok, even if they use the new syntax.

**Comment by leafpetersen** [comment]
Meta issue for the error filed here: https://github.com/dart-lang/sdk/issues/29484

**Comment by eernstg** [comment]
> It is a static error to instantiate a generic with a generic function type ..

I'm not sure where that came from. I've commented in more detail on #29484.

**Comment by jmesserly** [comment]
for unrelated reasons (@leafpetersen using this syntax in a test case for #30601), I ended up fixing this. Will send the CL out shortly

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3008053002/
