### ISSUE TITLE
dartanalyzer yields errors yet return code is 0

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#29498]
Branched off of https://github.com/dart-lang/sdk/issues/29429.

/cc @bwilkerson

**Comment by pylaligand** [comment]
Any progress on this? It's getting in the way of integrating Dart analysis into our build which would be a big productivity boost.

**Comment by bwilkerson** [comment]
@devoncarew Sounds like it might be related to #29423. Let me know if it isn't.

**Comment by devoncarew** [comment]
Likely the same issue - I'll investigate.

**Comment by devoncarew** [comment]
@pylaligand, #29423 is fixed, closing this out as I suspect it's the same issue
