### ISSUE TITLE
Analyzer Feedback from IntelliJ - NoSuchMethodError: Class 'PropertyAccessorElementForLink_Executable' has no instance getter 'identifier'

### ISSUE THREAD

**Issue by kostaa** [dart-lang/sdk#29500]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.4249.40`
- `1.23.0`
- `WS-171.4249.40, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050`

## Exception

Please append the contents of:
[report.txt](https://github.com/dart-lang/sdk/files/962624/report.txt)

file://C:\Users\ADAMKO~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: D:\repo__at\x-obsolate-at-client-rui\common\lib\entity.dart
NoSuchMethodError: Class 'PropertyAccessorElementForLink_Executable' has no instance getter 'identifier'.
Receiver: Instance of 'PropertyAccessorElementForLink_Executable'
Tried calling: identifier
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      PropertyAccessorElementForLink_Executable.noSuchMethod (package:analyzer/src/summary/link.dart:4467)
#3      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3216)
#4      ExecutableElementForLink_NonLocal

**Comment by bwilkerson** [comment]
@scheglov Would you have time to look into this? The full stack trace is in the attached report file.

**Comment by scheglov** [comment]
I think this is fixed already.
But I was not able to find the commit with the fix.

**Comment by bwilkerson** [comment]
Then I'm going to close this issue.

@kostaa Thank you for the report! If you continue to see this issue after updating to the next dev or stable build, please let us know.

**Comment by kostaa** [comment]
Thanks will do.
