### ISSUE TITLE
Dart error

### ISSUE THREAD

**Issue by getdbjs** [dart-lang/sdk#29505]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4249.39`
- `1.23.0`
- `IC-171.4249.39, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 1280x800  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/1c/0tsnw91j4kq0k2bgxxfr2nmc0000gn/T/report1.txt

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Could not initialize the library map from [/Users/davidebausach/sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart, /Users/davidebausach/sdk/lib/_internal/libraries.dart]

FileSystemException(path=/Users/davidebausach/sdk/lib/_internal/libraries.dart

**Comment by lrhn** [comment]
The `libraries.dart` file has moved to `sdk/lib/_internal/sdk_library_metadata/lib/`.
This was probably done to make it work like a dart package so you can import it as `package:sdk_library_metadata/libraries.dart`.

The analysis server version is 1.18, which suggests that it's fairly old compared to the SDK.
I don't use IDEA myself, so I can't say how it finds the analysis server to use.
