### ISSUE TITLE
redirectingFactoryConstructorSignature is not used

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#29501]
The language specifies redirecting factory constructors, and defines their grammar in `redirectingFactoryConstructorSignature`, but nothing else in the grammar seems to make use of that production.

**Comment by eernstg** [comment]
That's right, it is orphaned in the language specification. In Dart.g in the [ANTLR grammar CL](https://codereview.chromium.org/2688903004) this problem has been fixed: it is one of the cases under `declaration`. I've noted in Dart.g that this issue reports the same problem.

**Comment by eernstg** [comment]
No milestone now: This correction is part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).

**Comment by eernstg** [comment]
Closing: Fixed in e163637d1537ccc9ccde1d25ca87b82286aa634d.
