### ISSUE TITLE
Bug on null aware operator on dynamic receiver

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29504]
This code:

```dart
final dynamic hello = "hello";

void main() {
  var exception = hello;
  print(exception?.runtimeType);
}
```

throws this exception:

```
/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9691
          throw e;
          ^
NoSuchMethodError : method not found: 'Symbol("runtimeType")'
Receiver: "hello"
Arguments: []
```

**Comment by vsmenon** [comment]
@jmesserly - can you take a look?  Hitting this on an internal test (worked around that for now).

**Comment by jmesserly** [comment]
oh gosh, we may not be copying the dynamic call marker when we desugar `?.`. I wonder if we have a similar problem with casts. Probably not, since they are reified, unlike dynamic calls.

**Comment by jmesserly** [comment]
Ah just took a look. We do generate a dcall, however, we should be generating an Object member call. However ... that is probably a bug in Analyzer's marking of these nodes, rather than DDC, but I'll double check that.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2848153002/
