### ISSUE TITLE
Issues with dartium layout test expectation files

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#29514]
Some change seemed to cause the dartium layout tests result in different output (at least when running locally), namely the VM prints now:

    CONSOLE INFO: Observatory listening at http://127.0.0.1:52753/
    ...

Unfortunately the port number is random, so it changes every time, making the layout tests fail.

Currently there are 2 tests affected:

        LayoutTests/dart/inspector/debugger-eval-on-call-frame-expected.txt
        LayoutTests/dart/inspector/evaluate-in-console-expected.txt

The VM recently got support for disabling the observatory prints using `-DSILENT_OBSERVATORY=true`.

So I've attempted to change how we run the dartium layout tests by using this new flag. But unfortunately, it seems like `DART_FLAGS` cannot be used to set the `-D` compile-time constants.

So I'll just mark these two tests in the `TestExpectation` file as failing for now.

**Comment by mkustermann** [comment]
I don't seem to have permission to land [cl/2855573003](https://codereview.chromium.org/2855573003/) on our blink `release/2454_1`.

@terrylucas Maybe you could take a look at this.

**Comment by terrylucas** [comment]
Thanks Martin I'll get it checked in today.
