### ISSUE TITLE
Several Fasta tests failing

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29511]
front_end/test/fasta/bootstrap_test: Fail, Slow
front_end/test/fasta/compile_test: Fail, Slow
front_end/test/fasta/kompile_test: Fail, Slow
front_end/test/fasta/strong_test: Fail, Slow
front_end/test/fasta/outline_test: Fail

**Comment by rmacnak-google** [comment]
dc19d42c547ab759df4c081e97b0ed5c20e4e8e1 and 3a612c7b73fcee4e3bd7dd704d4ba84a9564381c seem like the most related changes in the blame window.

@scheglov @danrubel

**Comment by scheglov** [comment]
It works for me on dc19d42c547ab759df4c081e97b0ed5c20e4e8e1, which also includes 3a612c7b73fcee4e3bd7dd704d4ba84a9564381c.

**Comment by scheglov** [comment]
It started failing at ac40d0bb8e98f981780344fe365ebee2e401319b.
@asgerf
