### ISSUE TITLE
Please, clarify description of StreamTransformer

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29523]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/StreamTransformer-class.html) of class dart:async:StreamTransformer reads:

> The target of a Stream.transform call.
> 
> **The Stream.transform call will pass itself to this object and then return the resulting stream.**
> 
> It is good practice to write transformers that can be used multiple times.

The highlighted sentence is confusing. It is not clear what is passed: `Stream` instance, `Stream.transform` method or `Stream.transform` call. Destination is also not clear: `StreamTransformer` can not be a destination, I believe destination should be some method of `StreamTransformer`. My guess is that `Stream` instance is passed to method `StreamTransformer.bind`.

Method `bind` has the following description:

> Stream&lt;T&gt; bind(
>   Stream&lt;S&gt; stream
> )
> Transform the incoming stream's events.
> 
> Creates a new stream. When this stream is listened to, it will start listening on stream, and generate events on the new stream based on the events from stream.
> 
> **Subscriptions on the returned stream should propagate pause state to the subscription on stream.**

It is not clear, whether the highlighted sentence is already implemented or descendant classes should implement this?

The description of the StreamTransformer constructor reads:

> const StreamTransformer(
> StreamSubscription&lt;T&gt; transformer(
> Stream&lt;S&gt; stream,
> bool cancelOnError
> )
> )
> Creates a StreamTransformer.
> 
> **The returned instance takes responsibility of implementing (bind).** When the user invokes bind it returns a new "bound" stream. Only when the user starts listening to the bound stream, the listen method invokes the given closure transformer.
> 
> **The transformer closure receives the stream, that was bound, as argument and returns a StreamSubscription.** In almost all cases the closure listens itself to the stream that is given as argument.
> 
> The result of invoking the transformer closure is a StreamSubscription. The bound stream-transformer (created by the bind method above) then sets the handlers it received as part of the listen call.

I believe the transformer closure receives the original (source) stream, but not the "bound" stream that is returned by method `bind`.

The description of the StreamTransformer.fromHandlers constructor reads:

> StreamTransformer.fromHandlers({
> void handleData(
> S data,
> EventSink&lt;T&gt; sink
> ),
> void handleError(
> Object error,
> StackTrace stackTrace,
> EventSink&lt;T&gt; sink
> ),
> void handleDone(
> EventSink&lt;T&gt; sink
> )
> })
> Creates a StreamTransformer that delegates events to the given functions.

It is not clear, whether the returned instance implements method `bind`?

Summary:
1. The purpose and implementation of method `bind` are not clear.
2. Confusing description of constructor  StreamTransformer .

**Comment by floitschG** [comment]
CL in progress: https://codereview.chromium.org/2864863002/

(Feel free to comment there as well)
