### ISSUE TITLE
VM [Kernel] High use of old space in DFE mode

### ISSUE THREAD

**Issue by DmitryOlshansky-google** [dart-lang/sdk#29527]
This is connected to https://github.com/dart-lang/sdk/issues/29206 as it is likely a result of eager class finalization as well.

In short a typical benchmark in DFE mode would allocate: 4MB of strings, 1.7Mb of functions and 1.3Mb of Fields. All of this would pile up in the old space. In normal mode it would amount to measly 100's of Kbs.

This affects benchmarks StarryStrings and SunspiderGolemRegexDNA as those seem to allocate in the old space directly.

**Comment by a-siva** [comment]
This is being worked on in https://github.com/dart-lang/sdk/issues/28056, closing this as a duplicate.
