### ISSUE TITLE
Analyzer doesn't distinguish different mixin applications of the same classes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29522]
Example:
```dart
class M {}
class N {}
class C = Object with M, N;
class D = Object with M;
class E = D with C;  // Warning, D doesn't implement "C::Object&M"
```
There are two classes defined as `Object with M` here, `D` and the superclas of `C`. Those are different classes and neither is a subtype of the other.

Spec says:

> Let M<sub>A</sub> be a mixin derived from a class M with direct superclass S<sub>static</sub>.
> Let A be an application of M<sub>A</sub>. It is a static warning if the superclass of A
> is not a subtype of S<sub>static</sub>.

Therefore these declarations should cause a static warning because the superclass of the mixin application `E` is `D` which is not a subtype of the supertype of class `C`.

**Comment by peter-ahe-google** [comment]
This may be a language issue, and @lrhn will mull it over.

**Comment by lrhn** [comment]
This issue no longer applies since mixins can no longer be derived from classes with a supertype other than `Object`.

(Consider it mulled).
