### ISSUE TITLE
Importing! service_worker crashes my app with CastError- 'Casting form DartObjection to MdlComponent' is not possible

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#29521]
I already filed a bug report here: https://github.com/isoos/service_worker/issues/3 because first I thought it's a service_worker-bug...
 
However - if I include!!! service_worker-lib, not function is used, only service_workers default objects are generated, it crashes my app. I'm using core:js for adding properties to browserObjects (I upgrade standard HTML Elements).

It crashes only in Chrome with the very strange error message `CastError - DartObject to incompatible type MdlComponent` - what the heck is going on here? It works with Dartium btw.

Do you have a solution for me? I'm not really sure if this is a bug or if I'm just missing something.

Here is the GH-Repo: https://github.com/MikeMitterer/dart-sunshine
Master works but the test_cast_error branch fails: https://github.com/MikeMitterer/dart-sunshine/tree/test_cast_error

This video shows the crash. (0:58)
[dart_bug-service_worker.mp4.zip](https://github.com/dart-lang/sdk/files/969625/dart_bug-service_worker.mp4.zip)

**Comment by matanlurey** [comment]
I believe `package:js` would be required for doing this, unfortunately.
