### ISSUE TITLE
Windows dartium buildbots failing on integration branch

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29536]
The integration buildbots on Windows are failing to run the dartium tests.  Dartium is crashing when loading the driver page, that is supposed to run tests in an iframe.

I will try downloading the Dartium created by the integration-full builder, and testing it locally, to see if this reproduces.

We have some spare Windows slaves, so I can give the -inc builder and the -full builder dedicated machines, but this requires restarting the buildbot master.

**Comment by whesse** [comment]
The most recent build on win-full-integration reproduces the failure when we download the dartium that was built, and run tests locally.  I will see if earlier uploads of dartium have the same problem.

**Comment by terrylucas** [comment]
The April 28th (11AM-2PM) build was a good Windows build of Dartium 50.

**Comment by whesse** [comment]
Here is a stack trace from the crash in the driver window:
We are in a method "addClient" with this == null.

The weird thing is that this is called from the lines:
    if (scriptResource) {
        scriptResource->addClient(new ScriptLoadedCallback(m_loadCallback->completeURL(url), this, scriptResource));

so it is hard to see how this (scriptResource) could be null.  Unless the ScriptLoadedCallback constructor could somehow set it to null.  The type of this object is "    PassRefPtrWillBeRawPtr<ScriptResource> scriptResource = m_loadCallback->requestScript(request);

So it looks like it could be a pointer inside m_loadCallback, that could be reset to zero in the call to completeURL inside the addClient parameters.

All this is inside DartApplicationLoader.cpp, so it makes sense that this is where the problem can lie.


>	chrome_child.dll!blink::Resource::addClient(blink::ResourceClient * client) Line 607	C++
 	chrome_child.dll!blink::DartApplicationLoader::fetchScriptResource(const WTF::String & url) Line 843	C++
 	chrome_child.dll!blink::DartApplicationLoader::libraryTagHandlerCallback(Dart_LibraryTag tag, _Dart_Handle * library, _Dart_Handle * urlHandle) Line 666	C++
 	chrome_child.dll!dart::Parser::CallLibraryTagHandler(Dart_LibraryTag tag, dart::TokenPosition token_pos, const dart::String & url) Line 6126	C++
 	chrome_child.dll!dart::Parser::ParseLibraryImportExport(const dart::Object & tl_owner, dart::TokenPosition metadata_pos) Line 6310	C++
 	chrome_child.dll!dart::Parser::ParseLibraryDefinition(const dart::Object & tl_owner) Line 6409	C++
 	chrome_child.dll!dart::Parser::ParseTopLevel() Line 6485	C++
 	chrome_child.dll!dart::Parser::ParseCompilationUnit(const dart::Library & library, const dart::Script & script) Line 630	C++
 	chrome_child.dll!dart::Compiler::Compile(const dart::Library & library, const dart::Script & script) Line 301	C++
 	chrome_child.dll!dart::CompileSource(dart::Thread * thread, const dart::Library & lib, const dart::Script & script, _Dart_Handle * * result) Line 5244	C++
 	chrome_child.dll!Dart_LoadScript(_Dart_Handle * url, _Dart_Handle * resolved_url, _Dart_Handle * source, int line_offset, int column_offset) Line 5309	C++
 	chrome_child.dll!blink::DartApplicationLoader::processLibrary(const WTF::String & url, const WTF::String & source, int lineNumber) Line 562	C++
 	chrome_child.dll!blink::DartApplicationLoader::findDependences(const WTF::String & url, const WTF::String & source, int lineNumber) Line 547	C++
 	chrome_child.dll!blink::DartApplicationLoader::process(const WTF::String & url, const WTF::String & source, int lineNumber) Line 594	C++
 	chrome_child.dll!blink::DartApplicationLoader::processRequests(_Dart_Isolate * isolate, const blink::ScriptSourceCode & sourceCode, WTF::PassRefPtr<blink::DartApplicationLoader::Callback> loadCallback) Line 278	C++
 	chrome_child.dll!blink::DartController::evaluate(const blink::ScriptSourceCode & sourceCode, blink::ScriptLoader * loader) Line 932	C++
 	chrome_child.dll!blink::ScriptLoader::executeScript(const blink::ScriptSourceCode & sourceCode, double * compilationFinishTime) Line 468	C++
 	chrome_child.dll!blink::`anonymous namespace'::doExecuteScript(blink::Element * scriptElement, const blink::ScriptSourceCode & sourceCode, const WTF::TextPosition & textPosition, double * compilationFinishTime) Line 75	C++
 	chrome_child.dll!blink::HTMLScriptRunner::executePendingScriptAndDispatchEvent(blink::PendingScript * pendingScript, blink::ScriptStreamer::Type pendingScriptType) Line 221	C++
 	chrome_child.dll!blink::HTMLScriptRunner::executeScriptsWaitingForParsing() Line 345	C++
 	chrome_child.dll!blink::HTMLDocumentParser::prepareToStopParsing() Line 284	C++
 	chrome_child.dll!blink::HTMLDocumentParser::processParsedChunkFromBackgroundParser(WTF::PassOwnPtr<blink::HTMLDocumentParser::ParsedChunk> popChunk) Line 510	C++
 	chrome_child.dll!blink::HTMLDocumentParser::pumpPendingSpeculations() Line 587	C++
 	chrome_child.dll!blink::HTMLDocumentParser::resumeParsingAfterScriptExecution() Line 1037	C++
 	chrome_child.dll!blink::HTMLDocumentParser::notifyScriptLoaded(blink::Resource * cachedResource) Line 1074	C++
 	chrome_child.dll!blink::PendingScript::streamingFinished() Line 109	C++
 	chrome_child.dll!blink::ScriptStreamer::notifyFinished(blink::Resource * resource) Line 577	C++
 	chrome_child.dll!blink::PendingScript::notifyFinished(blink::Resource * resource) Line 183	C++
 	chrome_child.dll!blink::Resource::checkNotify() Line 245	C++
 	chrome_child.dll!blink::Resource::finish() Line 317	C++
 	chrome_child.dll!blink::ResourceLoader::didFinishLoading(blink::WebURLLoader * __formal, double finishTime, __int64 encodedDataLength) Line 443	C++
 	chrome_child.dll!content::WebURLLoaderImpl::Context::OnCompletedRequest(int error_code, bool was_ignored_by_handler, bool stale_copy_in_cache, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & security_info, const base::TimeTicks & completion_time, __int64 total_transfer_size) Line 778	C++
 	chrome_child.dll!content::WebURLLoaderImpl::RequestPeerImpl::OnCompletedRequest(int error_code, bool was_ignored_by_handler, bool stale_copy_in_cache, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & security_info, const base::TimeTicks & completion_time, __int64 total_transfer_size) Line 928	C++
 	chrome_child.dll!content::ResourceDispatcher::OnRequestComplete(int request_id, const ResourceMsg_RequestCompleteData & request_complete_data) Line 408	C++
 	chrome_child.dll!IPC::MessageT<ResourceMsg_RequestComplete_Meta,std::tuple<int,ResourceMsg_RequestCompleteData>,void>::Dispatch<content::ResourceDispatcher,content::ResourceDispatcher,void,void (__thiscall content::ResourceDispatcher::*)(int,ResourceMsg_RequestCompleteData const &)>(const IPC::Message * msg, content::ResourceDispatcher * obj, content::ResourceDispatcher * sender, void * parameter, void (int, const ResourceMsg_RequestCompleteData &) * func) Line 118	C++
 	chrome_child.dll!content::ResourceDispatcher::DispatchMessageW(const IPC::Message & message) Line 568	C++
 	chrome_child.dll!content::ResourceDispatcher::OnMessageReceived(const IPC::Message & message) Line 124	C++
 	chrome_child.dll!content::`anonymous namespace'::DispatchMessageTask::run() Line 31	C++
 	chrome_child.dll!scheduler::WebTaskRunnerImpl::runTask(scoped_ptr<blink::WebTaskRunner::Task,std::default_delete<blink::WebTaskRunner::Task> > task) Line 69	C++
 	chrome_child.dll!base::internal::Invoker<base::IndexSequence<0>,base::internal::BindState<base::internal::RunnableAdapter<void (__cdecl*)(scoped_ptr<mojo::edk::NodeController,std::default_delete<mojo::edk::NodeController> >)>,void __cdecl(scoped_ptr<mojo::edk::NodeController,std::default_delete<mojo::edk::NodeController> >),base::internal::PassedWrapper<scoped_ptr<mojo::edk::NodeController,std::default_delete<mojo::edk::NodeController> > > >,base::internal::InvokeHelper<0,void,base::internal::RunnableAdapter<void (__cdecl*)(scoped_ptr<mojo::edk::NodeController,std::default_delete<mojo::edk::NodeController> >)> >,void __cdecl(void)>::Run(base::internal::BindStateBase * base) Line 354	C++
 	chrome_child.dll!base::debug::TaskAnnotator::RunTask(const char * queue_function, const base::PendingTask & pending_task) Line 51	C++
 	chrome_child.dll!scheduler::TaskQueueManager::ProcessTaskFromWorkQueue(scheduler::internal::WorkQueue * work_queue, scheduler::internal::TaskQueueImpl::Task * out_previous_task) Line 292	C++
 	chrome_child.dll!scheduler::TaskQueueManager::DoWork(base::TimeTicks run_time, bool from_main_thread) Line 200	C++
 	chrome_child.dll!base::internal::Invoker<base::IndexSequence<0,1,2>,base::internal::BindState<base::internal::RunnableAdapter<void (__thiscall scheduler::TaskQueueManager::*)(base::TimeTicks,bool)>,void __cdecl(scheduler::TaskQueueManager *,base::TimeTicks,bool),base::WeakPtr<scheduler::TaskQueueManager>,base::TimeTicks &,bool>,base::internal::InvokeHelper<1,void,base::internal::RunnableAdapter<void (__thiscall scheduler::TaskQueueManager::*)(base::TimeTicks,bool)> >,void __cdecl(void)>::Run(base::internal::BindStateBase * base) Line 354	C++
 	chrome_child.dll!base::debug::TaskAnnotator::RunTask(const char * queue_function, const base::PendingTask & pending_task) Line 51	C++
 	chrome_child.dll!base::MessageLoop::RunTask(const base::PendingTask & pending_task) Line 478	C++
 	chrome_child.dll!base::MessageLoop::DoWork() Line 598	C++
 	chrome_child.dll!base::MessagePumpDefault::Run(base::MessagePump::Delegate * delegate) Line 34	C++
 	chrome_child.dll!base::MessageLoop::RunHandler() Line 440	C++
 	chrome_child.dll!base::RunLoop::Run() Line 36	C++
 	chrome_child.dll!base::MessageLoop::Run() Line 294	C++
 	chrome_child.dll!content::RendererMain(const content::MainFunctionParams & parameters) Line 220	C++
 	chrome_child.dll!content::RunNamedProcessTypeMain(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & process_type, const content::MainFunctionParams & main_function_params, content::ContentMainDelegate * delegate) Line 395	C++
 	chrome_child.dll!content::ContentMainRunnerImpl::Run() Line 764	C++
 	chrome_child.dll!content::ContentMain(const content::ContentMainParams & params) Line 19	C++
 	chrome_child.dll!ChromeMain(HINSTANCE__ * instance, sandbox::SandboxInterfaceInfo * sandbox_info) Line 87	C++
 	chrome.exe!MainDllLoader::Launch(HINSTANCE__ * instance) Line 184	C++
 	chrome.exe!wWinMain(HINSTANCE__ * instance, HINSTANCE__ * prev, wchar_t * __formal, int __formal) Line 231	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]

**Comment by whesse** [comment]
I have found the problem, and fixed it.  Windows Dartium 50 is passing tests, with my fix.
There was a PassRefPtr being used after it was copied to another pointer, and so it was null.
I changed it to a RefPtr, so it doesn't get set to null.
I'll attach the CL to this issue when it is ready.

**Comment by dgrove** [comment]
@whesse can this be closed?

**Comment by whesse** [comment]
Yes.
