### ISSUE TITLE
Please, clarify description of Stream.asyncExpand()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29541]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/asyncExpand.html) of method dart:async:Stream.asyncExpand() reads:

> Stream&lt;E&gt; asyncExpand<E>(
>   Stream&lt;E&gt; convert(
>     T event
>   )
> )
> Creates a new stream with the events of a stream per original event.
> 
> This acts like expand, except that convert returns a Stream instead of an Iterable. The events of the returned stream becomes the events of the returned stream, in the order they are produced.
> 
> If convert returns null, no value is put on the output stream, just as if it returned an empty stream.
> 
> The returned stream is a broadcast stream if this stream is.

Please, clarify the following cases:
1. How errors in source (i.e. original) stream are handled? 
  - Are they supplied to `convert`? 
  - Are they just copied to resulting stream? 
  - Is it fail-fast handling? (i.e. first error terminates the resulting stream)
2. Is it ok if `convert` returns Stream instance that never finishes? (i.e. endless stream)
3. The order of the events in resulting stream. For example, source stream produce two events A and B. For event A `convert` produce events A1 and A3. Event B appears in the source stream before event A3 is generated. `convert` produces events B2 and B4 for event B. So, in what order events appear in the resulting stream? Is it A1, B2, A3, B4 or A1, A3, B2,B4?
4. When resulting stream generates `done` event?

**Comment by lrhn** [comment]
Errors in the original stream are forwarded to the returned stream, just in `expand` (which should be covered by "acts like `expand`", but we might want to be explicit).
The error doesn't terminate anything, it's just forwarded (like `expand`).
They are not supplied to `convert` (and they can't be, the `convert` function expects `T` values).

It's perfectly fine to return an infinite stream or (indistinguishably) a stream that never emits any events. There is nothing special about that, it works like any other stream - we act on events and wait between them. There is nothing special to say about that case, and there never really is. 

What we should perhaps say (Ad. 3 and 40 is that the returned stream ends when the source stream ends, and that the source stream is paused between receiving a stream from `convert` and that stream ending, so the result is A1, A3, B2, B4, and we won't call `convert` with `B` until the stream form `A` is done. That's not clear from the documentation, and it's not obvious from comparing to the synchronous `expand`.

**Comment by alsemenov** [comment]
Also I forgot item 5. `convert` throws error.

**Comment by lrhn** [comment]
If convert throws, then, like `expand`, the error is put into the returned stream.

**Comment by srawlins** [comment]
I believe all of the questions have been answered in the new documentation text: https://api.dartlang.org/dev/2.1.0-dev.7.0/dart-async/Stream/asyncExpand.html
