### ISSUE TITLE
pkg/analyzer_cli/test/driver_test crashes if there is not a dart installation in the PATH

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29549]
I'm not sure if having a dart installation in PATH is intended to be a prerequisite for running the tests or not, but either way something other than a crash would be good.

Running
  python tools/test.py -mrelease --checked -t60 pkg/analyzer_cli/test/driver_test

without a dart sdk in my path, I see the crash below.

First adding a dart sdk to my path fixes it.

cc @scheglov 

FAILED: none-vm-checked release_x64 pkg/analyzer_cli/test/driver_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 ESC[32m+0ESC[0m: Driver options todosESC[0m
00:00 ESC[32m+0ESC[0mESC[31m -1ESC[0m: Driver options todosESC[0m
  NoSuchMethodError: The getter 'shortName' was called on null.
  Receiver: null
  Tried calling: shortName
  dart:core                                                       Object.noSuchMethod
  package:analyzer/src/summary/resynthesize.dart 210:58           SummaryResynthesizer.getLibraryElement.<fn>
  dart:collection                                                 _HashVMBase&MapMixin&&_LinkedHashMapMixin.pu

**Comment by srawlins** [comment]
I'll close this as stale. If it's still a problem, it would be ~P4.
