### ISSUE TITLE
Experimental flag for allowing/disallowing assignment casts

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29546]
The experimental analyzer `--no-implicit-casts` flag disallows all implicit casts.  We should have a `--[no-]assignment-casts` flag that affects only assignment casts (`A x = e`).  Specifying `--assignment-casts` should allow assignment casts, but no others.

cc @Hixie

**Comment by Hixie** [comment]
Flutter would use this to see if we have any implicit casts we aren't expecting. (We currently use assignment implicit casts as a work-around for "as" introducing new checks in release builds; we plan to move those to "as" once the VM has strong mode.)

**Comment by leafpetersen** [comment]
https://codereview.chromium.org/2976963002/
