### ISSUE TITLE
Override "annotation"

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#2954]
We need some way to indicate overrides:

1. This will prevent overridden methods from defaulting to a superclass when the method call is renamed in the superclass and the caller, but not the subclass. If the subclass's overriden method is annotated, then the subclass should fail static analysis at compile time.

2. This will offer devel-time support for refactorings

**Comment by rmacnak-google** [comment]
There is a standard annotation 'override' in dart:core.
