### ISSUE TITLE
Crash in Dartium 50 on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29556]
A new (rare) crash in Dartium 50 on Windows showed up when reporting an error.  This may be another problem with a smart pointer being set to zero when it is used somewhere else.  The code is

void ConsoleMessage::setCallStack(PassRefPtr<ScriptCallStack> callStack)
{
    m_callStack = callStack;
    if (m_callStack && !m_callStack->isEmpty() && !m_scriptId) {
        m_url = m_callStack->topSourceURL();
        m_lineNumber = m_callStack->topLineNumber();
        m_columnNumber = m_callStack->topColumnNumber();
    }
}

The crash is in m_callStack->isEmpty().
m_callStack is not null (its contained m_ptr is not null).
The contained pointer points to a stacktrace, and its m_stacktrace is null.

bool ScriptCallStack::isEmpty() const
{
    return m_stackTrace->isEmpty();
}

Watch:
-		m_callStack	{m_ptr=0x5972f448 {m_stackTrace={m_ptr=0x00000000 <NULL> } } }	WTF::RefPtr<blink::ScriptCallStack>

and the stack trace is

 	chrome_child.dll!blink::ScriptCallStack::isEmpty() Line 88	C++
>	chrome_child.dll!blink::ConsoleMessage::setCallStack(WTF::PassRefPtr<blink::ScriptCallStack> callStack) Line 100	C++
 	chrome_child.dll!blink::Document::logExceptionToConsole(const WTF::String & errorMessage, int scriptId, const WTF::String & sourceURL, int lineNumber, int columnNumber, WTF::PassRefPtr<blink::ScriptCallStack> callStack) Line 2950	C++
 	chrome_child.dll!blink::ExecutionContext::reportException(WTF::PassRefPtr<blink::ErrorEvent> event, int scriptId, WTF::PassRefPtr<blink::ScriptCallStack> callStack, blink::AccessControlStatus corsStatus) Line 163	C++
 	chrome_child.dll!blink::DartUtilities::reportProblem(blink::ExecutionContext * context, _Dart_Handle * result, const WTF::String & sourceURL) Line 1310	C++
 	chrome_child.dll!blink::DartApplicationLoader::callEntryPoint() Line 485	C++
 	chrome_child.dll!blink::DartApplicationLoader::load(WTF::PassRefPtr<blink::DartErrorEventDispatcher> errorEventDispatcher) Line 378	C++
 	chrome_child.dll!blink::DartController::loadAndRunScript(const WTF::String & url, _Dart_Isolate * isolate, WTF::PassRefPtr<blink::DartScriptInfo> info) Line 873	C++
 	chrome_child.dll!blink::DartController::scheduleScriptExecution(const WTF::String & url, _Dart_Isolate * isolate, WTF::PassRefPtr<blink::DartScriptInfo> info) Line 852	C++
 	chrome_child.dll!blink::DartDomLoadCallback::ready() Line 793	C++
 	chrome_child.dll!blink::DartApplicationLoader::process(const WTF::String & url, const WTF::String & source, int lineNumber) Line 599	C++
 	chrome_child.dll!blink::ScriptLoadedCallback::notifyFinished(blink::Resource * cachedResource) Line 772	C++
 	chrome_child.dll!blink::Resource::checkNotify() Line 245	C++
 	chrome_child.dll!blink::Resource::finish() Line 317	C++
 	chrome_child.dll!blink::ResourceLoader::didFinishLoading(blink::WebURLLoader * __formal, double finishTime, __int64 encodedDataLength) Line 443	C++
 	chrome_child.dll!content::WebURLLoaderImpl::Context::OnCompletedRequest(int error_code, bool was_ignored_by_handler, bool stale_copy_in_cache, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & security_info, const base::TimeTicks & completion_time, __int64 total_transfer_size) Line 778	C++
 	chrome_child.dll!content::WebURLLoaderImpl::RequestPeerImpl::OnCompletedRequest(int error_code, bool was_ignored_by_handler, bool stale_copy_in_cache, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & security_info, const base::TimeTicks & completion_time, __int64 total_transfer_size) Line 928	C++

**Comment by terrylucas** [comment]
Should be fixed a number of StackCallStack failures was fixed across all platforms.
