### ISSUE TITLE
Dart SDKs contain a empty `util` folder

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#29557]
The downloadable Dart SDK .zip files (e.g. [this one](https://storage.googleapis.com/dart-archive/channels/stable/release/1.23.0/sdk/dartsdk-macos-x64-release.zip)) appear to contain an `util` folder that seems to have no contents inside it? Why is this included?

**Comment by athomas** [comment]
Closing, the current SDKs don't have that folder: https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.2/sdk/dartsdk-macos-x64-release.zip
