### ISSUE TITLE
[Kernel] Catch on type variable doesn't work

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29553]
The test [tests/language/generic_field_mixin4_test.dart](https://github.com/dart-lang/sdk/blob/8e19729b8913c4225ef84e863193e36879947727/tests/language/generic_field_mixin4_test.dart#L13) seems to treat the type variable in catch as dynamic.

I've attached the compiled file: [generic_field_mixin4_test.dart.dill.zip](https://github.com/dart-lang/sdk/files/975736/generic_field_mixin4_test.dart.dill.zip)

**Comment by jensjoha** [comment]
I'll take a look.
