### ISSUE TITLE
Decide how "instantiate to bounds" should handle implicit type parameter bounds

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29561]
If I'm not mistaken, the analyzer implementation of strong mode currently treats a missing type parameter bound as different from a bound of `Object`:

    class C<T> {}
    C c; // equivalent to: C<dynamic> c;

    class D<T extends Object> {}
    D d; // equivalent to: D<Object> d;

This is problematic for two reasons:

- Kernel doesn't record enough information to distinguish a missing type parameter bound from a bound of `Object`.
- The Dart 1.0 spec says that a missing type parameter bound is equivalent to a bound of `Object`, and this makes intuitive sense.

For now, at @leafpetersen's suggestion, I'm implementing front_end's "instantiate to bounds" algorithm to instantiate both bounds as `dynamic`.  But in the long run it might be better to instantiate them both as `Object`.  This might be a large breaking change, so we need to investigate and figure out what to do.

**Comment by peter-ahe-google** [comment]
Can't we just make the bound of C.T `dynamic` and that of D.T `Object`?

**Comment by stereotype441** [comment]
Peter and I discussed this over VC.  Just to fill in anyone else who is reading the bug report: making the bound of C.T `dynamic` doesn't replicate analyzer behavior, because *inside* the class declaration, analyzer treats the bound as `Object`.  It's possible that we may be able to make a hack to BodyBuilder to achieve the same effect, though.

**Comment by scheglov** [comment]
Is there decision?

**Comment by stereotype441** [comment]
I believe @leafpetersen was going to run an experiment.  Leaf, did you get a chance to investigate this?

**Comment by leafpetersen** [comment]
I ran an experiment on this a while back.  It was massively breaking unfortunately.  Closing this as infeasible.
