### ISSUE TITLE
latent breakpoints cannot be listed or removed

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#29566]
When Observatory receives an addBreakpointWithScriptUri() and the script isn't ready yet, it creates a "latent breakpoint" to be added later. These breakpoints don't show up in the breakpoint list and removing them fails.

This causes confusion in debuggers when a breakpoint is added and removed before the script has finished loading. The latent breakpoint can appear at an arbitrary time in the future, causing execution to stop at a breakpoint that should no longer exist.

In particular, in Flutter, it's possible for a debugger to set a breakpoint at a location that won't be loaded until the user does their first hot reload. If the user sets a breakpoint and removes it before the first hot reload, it creates a phantom.

See:
* https://github.com/flutter/flutter-intellij/issues/983
* https://github.com/flutter/flutter-intellij/issues/991

**Comment by a-siva** [comment]
Thanks for tracking this down.

We maintain breakpoints in two lists in the debugger object
- breakpoint_locations_
- latent_locations_

When listing breakpoints in the isolate or when removing breakpoints we don't seem to account for the latent_locations_ list.

**Comment by aam** [comment]
I'm working on a fix for this.
Meanwhile, Brian, I was curious if there is a way to configure passing of additional parameters (f.e. --local-engine) to flutter script invoked by IntelliJ Flutter plugin?

**Comment by skybrian** [comment]
In the run configuration, there is an Additional arguments field. Maybe that will work?

(I'm not sure if it puts the flag in the right place for `--local-engine`, though. I'm unfamiliar with this flag and it seems not to be documented?)

**Comment by aam** [comment]
Yes, it does seem to work. Thanks!

The flag is used when you want flutter to use the updated engine code: https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md#working-on-the-engine-and-the-framework-at-the-same-time

**Comment by aam** [comment]
This should be fixed in dart sdk repo now.
This fix will get into Flutter next time the engine is sync'ed with the dart vm repo.

**Comment by skybrian** [comment]
I'm seeing a future breakpoint listed, but not all breakpoints are listed.

For an example, see: https://github.com/flutter/flutter-intellij/issues/991#issuecomment-303207381

Looking at the VM code, breakpoint id's are numbered sequentially, so breakpoint #1 is being created and stored somewhere, but it doesn't show up until later.

I think I should have this patch? This is using:

$ ~/software/flutter/bin/cache/dart-sdk/bin/dart --version
Dart VM version: 1.24.0-dev.3.0 (Thu May  4 03:43:40 2017) on "linux_x64"

**Comment by aam** [comment]
I don't think dev.3.0 has this patch

===
$ git merge-base --is-ancestor 5f9ec0abe8e9d5d268d5a6710da00018e0ccb193 1.24.0-dev.3.0
$ echo $?
1
===

**Comment by aam** [comment]
It should be in dev.5.0:
```
$ git merge-base --is-ancestor 5f9ec0abe8e9d5d268d5a6710da00018e0ccb193 1.24.0-dev.5.0
$ echo $?
0
```

**Comment by skybrian** [comment]
Okay, thanks!
