### ISSUE TITLE
dart2js: Emit fewer deferred parts by merging unrelated small parts.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29572]
Analysis of a large app (minified).

Of the 370 parts, most are quite small:
146 of size 0-1999
67 of size 2000-9999
89 of size 10000-99999
60 of size 100000-999999

Many parts are small and could be merged with unrelated parts and still stay quite small.

- [ ] It appears that 53 of the parts are completely empty. This should be investigated.
- [ ] Since the overhead of an empty part is currently 1080 bytes, all parts < 2k could be merged into one part that is less than 100k, even if completely unrelated.

**Comment by robbecker-wf** [comment]
I have the same issue with a large app. There are many small part files often with 1 field in them. I'd love some more control over dart2js part decisions. Perhaps that is a command line flag(s) with a minimum or maximum part file size? Or perhaps be able to specify via an annotation in code some sort of override on how the file should be parted.

**Comment by joshualitt** [comment]
I'm closing this issue because we've implemented part file merging into bundles(--merge-fragments-threshold) as well as a much more powerful model of merging in the form of program split constraints.
