### ISSUE TITLE
Observatory UI doesn't run in browser, shows "loading" next to Isolate, and clicks go to blank white pages

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29577]
When opening observatory in Chrome, I only see the static (pre-load) content, and the JS console says: 

    Refused to execute script from 'http://127.0.0.1:52266/packages/web_components/dart_support.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

![screen shot 2017-05-07 at 13 04 15](https://cloud.githubusercontent.com/assets/919717/25784648/b52d969a-3325-11e7-8e5b-7c822ca14df5.png)

Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"
Chrome Version 58.0.3029.81 (64-bit)

**Comment by kasperl** [comment]
Are you "monitoring" the Observatory issues, @a-siva?

**Comment by filiph** [comment]
Talked to @rmacnak-google about this.

This happens because the code is at `stdin.readLineSync()` when I open the Observatory UI. So Observatory cannot obtain any data from the VM, as the VM is busy synchronously waiting for input. The MIME type error is unrelated.

Here's a screenshot of what the UI looks like, in case others have this issue:

![screen shot 2017-05-08 at 11 32 06](https://cloud.githubusercontent.com/assets/919717/25819230/30cd071a-33e2-11e7-9869-67c16e3a7a0c.png)

Note the 'loading Isolate 123456789' message at the bottom.

We talked about ways to make this clear to the user but I it doesn't look like there's a simple solution. I'll close this issue but feel free to reopen if there are any ideas on how to make this edge case clearer to the user.

**Comment by rmacnak-google** [comment]
More specifically, only the isolate running `stdin.readLineSync()` is blocked, not the whole VM. If there were other isolates not at blocking calls, they would load properly.

In the future, we might be clever and timeout if the response from an isolate takes too long, either presume it is blocked or try to check the isolate's tag to see it is in the middle of a native call, and display a message saying the isolate might be blocked.
