### ISSUE TITLE
ensure that we're analyzing non-dart files (analysis_options.yaml, for example)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29570]
Specifically, we have several issues we can report for `.analysis_options` and `analysis_options.yaml` files; we should ensure that we're analyzing at least these file types, so we can get warnings (like this one: https://codereview.chromium.org/2655073005/).

**Comment by jamesderlin** [comment]
If this issue is actually about making dartanalyzer report errors in `analysis_options.yaml`, could you change the issue title so that this is easier to find?  The current one is confusing.

**Comment by srawlins** [comment]
We are, now.
