### ISSUE TITLE
js-interop: @JS('window') is now suddenly needed?

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#29575]
**Describe the issue you're seeing**
Putting @JS() at the beginning of the file should use the global namespace for getting references (e.g. `window`). I get errors now saying `self.*` is not defined. If I put `@JS('window')` before library instead it works.

**Does it happen in Dartium or when compiled to JavaScript?**
When compiled

* Dart SDK version: *use `dart --version`*
Dart VM version: 1.24.0-dev.3.0
* pkg/js version: *look at `pubspec.lock`*
0.6.1

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.
