### ISSUE TITLE
Cannot add breakpoint inside a function

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29581]
Setting breakpoint on line 6 of this script won't stop execution:

```
main(List<String> args) {
  closure("foo");
}

Func closure = (text) {
  print("boo!");  // <-- BREAKPOINT HERE
};

typedef void Func(String text);
```

The script works fine and runs to completion. But any breakpoint inside a function defined like that one will be ignored. IntelliJ marks it as an "Invalid" breakpoint (with an 'x') during execution:

![screen shot 2017-05-08 at 11 56 08](https://cloud.githubusercontent.com/assets/919717/25820236/72cc9e02-33e5-11e7-9e5d-01bc1ef519c3.png)

(IntelliJ explains the 'Invalid' breakpoint icon as "Shown when the breakpoint is set on a commented or non-executable line indicating that such breakpoint would not be hit.")

Repro: [no-breakpoint-inside-function.zip](https://github.com/dart-lang/sdk/files/984559/no-breakpoint-inside-function.zip)

**Comment by devoncarew** [comment]
I can repro this. I get this error back from the setBreakpoint call:

```
{"jsonrpc":"2.0","error":{"code":102,"message":"Cannot add breakpoint","data":{"request":{"method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/566349011","scriptUri":"file:///Users/devoncarew/projects/untitled4_repro/bin/main.dart","line":"6"}},"details":"addBreakpointWithScriptUri: Cannot add breakpoint at line '6'"}},"id":"7"}
```

and in the observatory UI, it doesn't appear as a line where we can set breakpoints:

<img width="541" alt="screen shot 2017-05-09 at 7 58 33 am" src="https://cloud.githubusercontent.com/assets/1269969/25857270/6595c490-348d-11e7-981c-d144ae2e441e.png">

**Comment by sivachandra** [comment]
This issue is not yet fixed for the case when dfe is used.

**Comment by a-siva** [comment]
The milestone 1.25 on this bug can be removed right? It is fixed in the existing product and needs fixing  when --dfe is used which is not a 1.25 milestone requirement

**Comment by sivachandra** [comment]
Yes, removed the 1.25 milestone.
