### ISSUE TITLE
ARM snapshots are not created

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29580]
Cross-compiling ARM and ARM64 builds with tools/build.py create_sdk creates Intel X64 snapshots, and copies them into the dart-sdk/bin/snapshots directory of the build directory out/ReleaseXARM or out/RELEASEXARM64.

This is a mistake in the build process, since the shapshot generation tool should have support for generating cross-platform snapshots.

The dart executable on ARM and ARM64 can run dart2js from the dart2js source in the source checkout, by using the sdk/bin/dart2js command in the checkout.  But when trying to run the snapshot from the SDK's copy of dart2js, it produces the error

 Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override use_field_guards use_osr x64-sysv' but the VM has 'release no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override use_field_guards use_osr arm64'

@sortie

**Comment by whesse** [comment]
Generation of the dart2js snapshot for XARM or XARM64 is working now, but it takes 2000 seconds.  Is this something that could be optimized? It is one of the longest operations in all our building and testing.

**Comment by rmacnak-google** [comment]
Can you check out/ReleaseXARM/args.gn for that bot? I suspect it will be missing dart_snapshot_kind, which is a new GN argument I added in the change above. Running build.py alone won't cause it to pick up any new arguments we set in gn.py, so it's probably doing the default of generating a full app-jit snapshot, which for a cross build involves running the training set for dart2js under the simulator. Running gn.py (or removing the out directory) should set the flag so it will do a script snapshot instead.  We'll update generate_buildfiles hook to include the cross builds.

**Comment by whesse** [comment]
It wasn't a bot, it was building locally, and yes, I was missing that argument.
