### ISSUE TITLE
Please merge revision 73f45d6230a370273234e5d147a86dfc4c869caf into dev channel

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29583]
@whesse @mit-mit @kasperl

This fixes a bug where an async function was started in the root zone instead of the current zone.

**Comment by keertip** [comment]
@whesse, can you put out a dev.3.1? we need this fix for google3. Thanks!

**Comment by whesse** [comment]
Merged in 1.24.0-dev.4.0
