### ISSUE TITLE
Dart-analyzer fails when platform libraries uses `part of "dart:core";` in its parts.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29598]
The commit https://github.com/dart-lang/sdk/commit/540bb7a0ec8d97ad76a67e722c154ef85540c187 caused a lot of spurious analyzer errors.
See, e.g.: https://build.chromium.org/p/client.dart/builders/analyze-linux-be/builds/890/steps/analyze%20analyzer_plugin/logs/stdio

**Comment by lrhn** [comment]
Blocks #29592 which is scheduled for 1.24. Please consider upgrading priority.

**Comment by devoncarew** [comment]
Is #29592 really a requirement for 1.24? It seems like this could be moved to 1.25, given that we're late into the cherry-pick season for 1.24.

@bwilkerson, can you find an owner?

**Comment by lrhn** [comment]
The blocked issue has been moved to 1.25. We still want to make the switch as early as possible, but 1.24 isn't the goal any more.

**Comment by dgrove** [comment]
#25292 is still in 1.24 . I presume it should be moved to 1.25, and will do that.

**Comment by lrhn** [comment]
I've uploaded a new CL: https://codereview.chromium.org/2911903002/
The change is that the back-reference from the part file now uses `part of "core.dart";` instead of `part of "dart:core";`.
This is preferable because that's the style we want to use in other places, so the platform libraries should do the same, and lead by example.

There is a problem with platform libraries using parts: Resolving "string.dart" relative to "dart:core" isn't giving anything useful (it gives "dart:string.dart" which is just wrong). So, there is special-casing of platform library parts in the analyzer that makes sense of this (reputedly it becomes "dart:core/string.dart"). We need that special casing to work in the other direction as well, so when "string.dart" does `part of "core.dart";` it will correctly recognize that as being part of "dart:core".

**Comment by mit-mit** [comment]
Any updates on getting this resolved?

**Comment by bwilkerson** [comment]
As far as I know, nobody has started looking at this.

**Comment by lrhn** [comment]
As I remember it, just try patching in the CL, rebuild the SDK and then run tests with the analyzer (`tools/test.py -j32 -cdart2analyzer -rnone`) and see how much fails. That's effectively what I did when I committed the CL.
It fails lot, and the way it fails suggests that some libraries are not recognized as being platform libraries, like "X is not assignable to Object".

**Comment by bwilkerson** [comment]
Right. So as I mentioned above: I tried applying the patch I downloaded from the review tool, but git said it was invalid. Sorry for my ignorance, but how do I get a patch I can apply?

**Comment by lrhn** [comment]
Ack, my bad, didn't catch that.
I use `git cl patch 2661603002` to patch in the CL on top of the most recent tip-of-tree. Then I run the tests normally  and get 498 errors, including such interesting errors as:
```
FAILED: dart2analyzer-none release_x64 analyze_library/lib/_internal/js_runtime/lib/typed_data_patch
Expected: Pass
Actual: CompileTimeError
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|REDIRECT_TO_INVALID_RETURN_TYPE|c:\\src\\dart\\sdk\\sdk\\lib\\_internal\\js_runtime\\lib\\typed_data_patch.dart|172|49|13|The return type 'NativeInt32x4' of the redirected constructor isn't assignable to 'Int32x4'.
WARNING|STATIC_WARNING|REDIRECT_TO_INVALID_RETURN_TYPE|c:\\src\\dart\\sdk\\sdk\\lib\\_internal\\js_runtime\\lib\\typed_data_patch.dart|92|35|15|The return type 'NativeUint8List' of the redirected constructor isn't assignable to 'Uint8List'.
...
```
and lots and lots of errors per failing test .
Another one is:
```
WARNING|STATIC_WARNING|PART_OF_DIFFERENT_LIBRARY|c:\\src\\dart\\sdk\\sdk\\lib\\isolate\\isolate.dart|19|6|17|Expected this library to be part of 'dart:isolate', not 'dart:isolate/isolate.dart'.
```
This is actually ... sort-of rational behavior because the part containst `part of "isolate.dart";` and its URI is ... well, I don't actually know - parts of `dart:`-libraries don't really have an URI, but it's probably something like `dart:isolate/partname.dart`, but it isn't important as long as the file gets loaded correctly, and I'm assuming there is some hackery going on that allows `part "partname.dart";` to work inside `dart:isolate`. We need just need that hackery to work in the other direction too.

That would be the preferable outcome. Worst case, if that is completely impossible, we could go back to the part saying `part of "dart:isolate";`. It's not as nice to read when you are actually editing the platform libraries, but the number of people affected by that is fairly small. An earlier version of the CL tried that, and it didn't work either.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2967503002/

**Comment by lrhn** [comment]
This worked! Yey!
Sadly, after discussion with Fasta, we'll go back to using `part of "dart:core";` which only *almost* works.
The CL for that was https://codereview.chromium.org/2974433002/
but it causes failures in pkg/analyzer and analyzer tests: 
https://luci-milo.appspot.com/buildbot/client.dart/analyzer-linux-release-be/5819
Sorry about that. :(

**Comment by bwilkerson** [comment]
Just FYI: I'm on vacation for the next week and a half, so if you need it sooner than that you'll need to talk to Devon to get it staffed.

**Comment by lrhn** [comment]
This turned out to be more complication than it's worth. Since `dart:core` is no a normal URI (not hierarchical), then logic to map back to `dart:core` doesn't work well for Fasta.
It's not a priority since it doesn't affect any users. If we ever decide to remove the old `part of` format, we'll have to fix this, but until then, it's probably not going to happen.
