### ISSUE TITLE
lib_strong/html/svgelement_test is failing since Chrome 50 roll

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29594]
See for example https://build.chromium.org/p/client.dart/builders/analyzer-mac10.11-release-strong-be/builds/1159/steps/analyze%20strong%20tests/logs/stdio

I will make a change to the .status file to turn the bot green again.

**Comment by bwilkerson** [comment]
@terrylucas

**Comment by alan-knight** [comment]
See also https://github.com/dart-lang/sdk/issues/25665.
