### ISSUE TITLE
Some issues in Dartium 50

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29605]
```dart
  void _onKeyPress(KeyboardEvent event) {
    if (event.keyCode == KeyCode.ESC && isVisible) {
                 ^^^
      isVisible = false;
    }
  }
```

I get 
```
EXCEPTION: NoSuchMethodError: Class 'KeyboardEvent' has no instance getter '_keyCode'.
Receiver: Instance of 'KeyboardEventImpl'
Tried calling: _keyCode
STACKTRACE: 
dart:html                                                         KeyboardEvent.keyCode
package:bwu_ng_mdl/src/layout/drawer/drawer_component.dart 46:15  DrawerComponent._onKeyPress
dart:async                                                        _ZoneDelegate.runUnary
package:angular2/src/core/zone/ng_zone.dart 184:21                NgZone._runUnary
```
> Dart VM version: 1.24.0-edge.ca3d90c4cd7155709a7836d0830b1f712925a8cd (Thu May 11 19:41:00 2017) on "linux_x64"

I don't get the error with 
> Dart VM version: 1.24.0-edge.5e5aa2ea9e372776db7e5b1803d488410eb0c8e8 (Wed May 10 01:06:50 2017) on "linux_x64"

**Comment by zoechi** [comment]
Weirdly, the screenshots don't really show the difference but on my screen the tabs and content is like zoom level 75% is set. 
For quite some time I had the same "zoom level" in Dartium (when set to 100%) like in Chrome.
A few months ago it was like zoome level 120% in Dartium compared to Chrome for several months.

**Comment by zoechi** [comment]
related to #28280

**Comment by leonsenft** [comment]
This is a deprecated field, perhaps it's been dropped?

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by zoechi** [comment]
@leonsenft thanks for the pointer and sorry for the noise.

**Comment by zoechi** [comment]
It's used in [angular2_components](https://github.com/dart-lang/angular_components/blob/4518e633682dcf985a23da0e96ed5e39c41abde3/lib/src/components/button_decorator/button_decorator.dart#L84) all over the place, therefore I'll reopen and let someone else decide.

**Comment by terrylucas** [comment]
Please try this on a newer Dartium 50 roll (Tues May 16 or later).

**Comment by zoechi** [comment]
@terrylucas the `keyCode` issue seems fixed.

The size issue is the same.

Breakpoints don't work in Intellij-IDEA with Dartium 50. 
Should I create an issue in the Jetbrains issue tracker or is it too early?

**Comment by zoechi** [comment]
@terrylucas done, and yes, therefore closing
