### ISSUE TITLE
Member.baseElement is used inconsistently

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#29600]
I don't know whether this is causing any bugs, but the method `Member.baseElement` is being used in a seemingly inconsistent way. It appears that some of the code expects that `baseElement` will always return a non-member and that other code is careful to invoke `baseElement` _until_ it returns a non-member. The getter, as things are currently implemented, is _not_ required to return a non-member. We should (a) clearly document the expected behavior of the getter (whether the current behavior or a strictly non-member implementation) and (b) check the current invocation sites to make sure they're consistent with the decided on implementation.

**Comment by jcollins-g** [comment]
This showed up in dartdoc as difficulty resolving some comment references as we expected baseElement to always return a non-Member.

**Comment by jcollins-g** [comment]
Some more details:  The reason it created a bug for dartdoc was we have linkages to specific elements and are doing comparisons saying essentially "if(memberThingy.baseElement == this.element) { hurray() }".   It's a way to leverage analyzer's canonicalization and easily enough corrected by a loop to get baseElements until we have a non-Member.  

If analyzer is doing anything like these comparisons internally (or if its users are), that seems to me to be the likeliest sort of bug this would cause.
