### ISSUE TITLE
Inconsistent type inference behavior of block-type vs expression-type closures

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29606]
Consider the following code:

    typedef num FunctionReturningNum();

    main() {
      Object o = 1;
      FunctionReturningNum a = () => o;
      FunctionReturningNum b = () { return o; }
    }

Type inference currently infers a return type of `Object` for the closure in `a`, and a return type of `num` for the closure in `b`.

The behavior of expression-type closures should be changed to match that of block-type closures.

**Comment by jensjoha** [comment]
This no longer seem to be the case. @stereotype441  can we close?

**Comment by stereotype441** [comment]
This issue was fixed in the front end in b75502513a67555396dd787552e0efabfe27b905.  But this bug is about the analyzer.  Since the analyzer hasn't yet been migrated to the front end, I am planning to replicate this bug fix in the analyzer.  So I would like to leave this bug open until then.

**Comment by jensjoha** [comment]
OK, thanks for clearing that up.

**Comment by leafpetersen** [comment]
@stereotype441 The example above no longer reproduces on bleeding edge.  Should we close this?

**Comment by stereotype441** [comment]
Confirmed that this has been fixed.
