### ISSUE TITLE
Snapshot files are different across builds

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#29609]
It would be ideal if building the same sources produced exactly the same bits (in the same order) in the snapshot.

```
zra@zach:~/dart/sdk$ ./tools/gn.py -m release -a x64
zra@zach:~/dart/sdk$ ./tools/ninja.py -m release -a x64 create_sdk
zra@zach:~/dart/sdk$ ls -la out/ReleaseX64/dart-sdk/bin/snapshots/
total 114884
drwxr-x--- 3 zra eng     4096 May 12 13:20 .
drwxr-x--- 3 zra eng     4096 May 12 13:20 ..
-rw-r----- 1 zra eng  6757728 May 12 13:20 analysis_server.dart.snapshot
-rw-r----- 1 zra eng 34208448 May 12 13:20 dart2js.dart.snapshot
-rw-r----- 1 zra eng 17017248 May 12 13:20 dartanalyzer.dart.snapshot
-rw-r----- 1 zra eng 34482048 May 12 13:20 dartdevc.dart.snapshot
-rw-r----- 1 zra eng  5486112 May 12 13:20 dartdoc.dart.snapshot
-rw-r----- 1 zra eng  5367680 May 12 13:20 dartfmt.dart.snapshot
-rw-r----- 1 zra eng 10333920 May 12 13:20 pub.dart.snapshot
drwxr-x--- 3 zra eng     4096 May 12 13:20 resources
-rw-r----- 1 zra eng  3964448 May 12 13:20 utils_wrapper.dart.snapshot
zra@zach:~/dart/sdk$ rm -rf out
zra@zach:~/dart/sdk$ ./tools/gn.py -m release -a x64
zra@zach:~/dart/sdk$ ./tools/ninja.py -m release -a x64 create_sdk
zra@zach:~/dart/sdk$ ls -la out/ReleaseX64/dart-sdk/bin/snapshots/
total 114556
drwxr-x--- 3 zra eng     4096 May 12 13:22 .
drwxr-x--- 3 zra eng     4096 May 12 13:22 ..
-rw-r----- 1 zra eng  6753632 May 12 13:22 analysis_server.dart.snapshot
-rw-r----- 1 zra eng 34088608 May 12 13:22 dart2js.dart.snapshot
-rw-r----- 1 zra eng 17057920 May 12 13:22 dartanalyzer.dart.snapshot
-rw-r----- 1 zra eng 34232672 May 12 13:22 dartdevc.dart.snapshot
-rw-r----- 1 zra eng  5486112 May 12 13:22 dartdoc.dart.snapshot
-rw-r----- 1 zra eng  5367680 May 12 13:22 dartfmt.dart.snapshot
-rw-r----- 1 zra eng 10333920 May 12 13:22 pub.dart.snapshot
drwxr-x--- 3 zra eng     4096 May 12 13:22 resources
-rw-r----- 1 zra eng  3960352 May 12 13:22 utils_wrapper.dart.snapshot
```

@rmacnak-google What is the reason these are different? How difficult would it be to make the results the same every time.

**Comment by rmacnak-google** [comment]
One source of non-determinism is the hashing of const instances by address, which influences the order that the serializer encounters objects.  @a-siva might have some thoughts on the cost of using the weak tables instead.

The order that sources are loaded could also create non-determinism. I don't remember if the loader can give responses in a different order than the requests, but suspect it does not.

**Comment by rmacnak-google** [comment]
Symbol compaction and collecting token streams for the VM isolate also depend on object iteration order, which is non-deterministic with concurrent sweep.

**Comment by peter-ahe-google** [comment]
We can probably learn something from @ErikCorryGoogle, @rakudrama, and @floitschG  regarding ordering of constants. If memory serves me right, they have all been involved in dart2js constants.

**Comment by davidmorgan** [comment]
Big +1 on this issue; any build system that uses caching is going to need deterministic output. We have such a build system at google ;) http://google-engtools.blogspot.ch/2011/09/build-in-cloud-distributing-build-steps.html and so this is quite a big deal for us.

Thanks.

**Comment by rmacnak-google** [comment]
While I'm noticing, WriteStream::Align also doesn't zero the skipped bytes.

**Comment by rmacnak-google** [comment]
CC @athomas

**Comment by zanderso** [comment]
Closing this one in favor of https://github.com/dart-lang/sdk/issues/31427
