### ISSUE TITLE
Analysis Server error: Analyzer Feedback 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#29613]
[report.txt](https://github.com/dart-lang/sdk/files/1000228/report.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4073.35`
- `1.23.0`
- `IU-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1920x1080, 1920x1080, 2560x1440`

# Exception

Please append the contents of:
file:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report.txt

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: /Volumes/Daten/DevLocal/DevDart/MobiAd.Device.Simulator/test/unit/stores/ChooseSimulationAction_test.dart
Element mismatch in /Volumes/Daten/DevLocal/DevDart/MobiAd.Device.Simulator/test/unit/stores/ChooseSimulationAction_test.dart at /Volumes/Daten/DevLocal/DevDart/MobiAd.Device.Simulator/test/unit/stores/ChooseSimulationAction_test.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:53)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511)
#2      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#3      _HashVMBase

**Comment by bwilkerson** [comment]
@scheglov

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
