### ISSUE TITLE
No dart2js specific platform.dill in sdk

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#29626]
The published sdk doesn't contain a dart2js specific platform.dill files which is need to support kernel based compilation with dart2js.

**Comment by sigmundch** [comment]
Since we'll embed the front-end as a library as well, I expect that this is not a requirement but an optimization we want for our users (to avoid parsing the sdk from sources on every compile), correct?

If so - I think we should move this to area-sdk

**Comment by sigmundch** [comment]
fixed in de7e14436c
