### ISSUE TITLE
Please, clarify how Stream.distinct() handles errors

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29627]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/distinct.html) for method dart:async:Stream.distinct() reads:

> Stream&lt;T&gt; distinct([
> bool equals(
> T previous,
> T next
> )
> ])
> Skips data events if they are equal to the previous data event.
> 
> The returned stream provides the same events as this stream, except that it never provides two consecutive data events that are equal.
> 
> Equality is determined by the provided equals method. If that is omitted, the '==' operator on the last provided data element is used.
> 
> The returned stream is a broadcast stream if this stream is. If a broadcast stream is listened to more than once, each subscription will individually perform the equals test.

Please, clarify how errors are handled:
1. Errors in the original stream (are they just copied?)
2. Errors thrown by `equals` (are they added to returned stream? does first error stops further processing?)

**Comment by lrhn** [comment]
The errors are forwarded, that's part of "the same events" since we generally include errors in events.

Errors in `equals` is indeed added to the returned stream. It doesn't stop further processing, and it doesn't update what the most recently emitted data event is.

**Comment by alsemenov** [comment]
In case of `equals` throws, please, clarify whether error is considered as `equals` returns `true` or `equals` returns `false`? I.e. what data will be in returned stream in case of `equals` throws
