### ISSUE TITLE
make ServerPlugin generic over AngularDriver

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#29621]
Might be nice to have `ServerPlugin` be `ServerPlugin<T extends AnalysisDriver>`, so I can access `driverMap` as `Map<String, AngularAnalysisDriver>` (if the plugins default type is `Map<String, T>`).

First suggestion, I'll try to keep them coming!

**Comment by bwilkerson** [comment]
Given that we're going to replace references to `AnalysisDriver` with a real public API, I'm going to close this in favor of that work.
