### ISSUE TITLE
String.split() on empty string results in array of length '1'

### ISSUE THREAD

**Issue by tmst** [dart-lang/sdk#29628]
''.split(' ').length
1

I believe this to be incorrect. The result of the analogous operation in Python yields '0'.

**Comment by zoechi** [comment]
Seems similar to https://github.com/dart-lang/sdk/issues/27123#issuecomment-241326601

**Comment by floitschG** [comment]
Yes. This is the same issue. (Thanks again @zoechi )

Dart (for the better or worse) uses the same semantics as JavaScript here...

Closing.
