### ISSUE TITLE
Analyzer error from Double slashes in import URL should be improved

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#29631]
Double slashes within an import URL do not cause a warning or error as the files correctly load. However, the resulting types will cause issues as they are determined to be from an incompatible package.

For example:

import 'some/path//location/test.dart';

is valid but loaded types will likely be incompatible with those loaded from an existing API.

**Comment by bwilkerson** [comment]
In case you happen to know: does the VM normalize the URI, or do you end up with errors there as well?

**Comment by grouma** [comment]
I'm not sure. Is there an easy way to test this?

**Comment by bwilkerson** [comment]
That depends on your definition of "easy" :-)

I wrote a small test, and the VM (in checked mode) prints:
```
Unhandled exception:
type 'C' is not a subtype of type 'C' of 'c' where
  C is from package:test_pkg/bug/def.dart
  C is from package:test_pkg/bug//def.dart

#0      use (package:test_pkg/bug/use.dart:3:12)
#1      main (file:///Users/brianwilkerson/dart/test_pkg/lib/bug/main.dart:5:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
It appears that analyzer is correct and that the VM considers these to be different libraries (and hence different classes).

**Comment by grouma** [comment]
I see. The warnings / errors provided by the analyzer is misleading. I stumbled into this scenario with a typo in the import URL. Took some head scratching and a second pair of eyes to see my silly mistake.

**Comment by bwilkerson** [comment]
We could definitely do better with the error message! Seems like we should be able to tell you if there's a small difference in the URI's that you might have a typo somewhere (and maybe even where).

**Comment by keertip** [comment]
Very unlikely that this will be addressed.
