### ISSUE TITLE
Roll 50 failures on Safari

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#29632]
LayoutTests/fast/events/event-fire-order_t01
LayoutTests/fast/dom/icon-size-property_t01
LayoutTests/fast/dom/HTMLOutputElement/htmloutputelement_t01

All 3 of these fail on the Safari bot, but pass locally. The first two pass with the error that length is not a function, the last one with target is not defined.

**Comment by athomas** [comment]
LayoutTests are no more.
