### ISSUE TITLE
dart2js: Smaller and more efficient deferred library guard

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29637]
Deferred library guards are converted early to library calls.
Each call contains the key for the test and a uri for the error message.

- It would be more efficient if the guard was understood by the optimizer to eliminate repeated guards
- The key (the same used for loading deferred libraries) could be reduced to an index for an array-based check, and the uri could be stored in an array to avoid being repeated in the code

```js
    call$1: function(_) {
      H.checkDeferredIsLoaded("column_customizer_adapter", "package:ads.awapps2.infra.column_customizer/table_view_adapter.template.dart");
      X.initReflector839();
      H.checkDeferredIsLoaded("column_customizer_adapter", "package:ads.awapps2.infra.column_customizer/table_view_adapter.template.dart");
      return C.C_Deferred;
    },
```

There are not many cases of this, so it making ot P3.
https://github.com/dart-lang/sdk/issues/29635 is a related issue - the uri might be moved into the metadata referenced there.

**Comment by rakudrama** [comment]
Some customers would like the URI to be absent from the .js.
The map from deferred key to URI could be stored in the sourcemap file.

**Comment by sigmundch** [comment]
I believe this was fixed by https://github.com/dart-lang/sdk/commit/17ed3cb5b304f3bc1cff1a3352953b9de9f99297
