### ISSUE TITLE
Unexpected behavior of Stream.distinct()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29638]
The description of dart:async:Stream.distinct() reads:

> Stream<T> distinct([
> bool equals(
> T previous,
> T next
> )
> ])
> Skips data events if they are equal to the previous data event.
> 
> The returned stream provides the same events as this stream, except that it never provides two consecutive data events that are equal.
> 
> Equality is determined by the provided equals method. If that is omitted, the '==' operator on the last provided data element is used.
> 
> **The returned stream is a broadcast stream if this stream is. If a broadcast stream is listened to more than once, each subscription will individually perform the equals test.**

The following sample code shows that `equals` is called with unexpected arguments and unexpected number of times.
```dart
import "dart:async";

bool equals(Object p, Object n) {
  print("equals($p,$n)");
  return false;
}

main(List<String> args) {
  Stream s = new Stream.fromIterable([1, 2, 3, 4]);
  Stream d = s.asBroadcastStream().distinct(equals);
  int length = args.length>0 ? int.parse(args[0]) : 1;
  List<Future> results = new List.generate(length, (_) => d.toList());
  Future.wait(results).then(print);
}
```
Output
> dart.exe  --checked test2.dart 1
> equals(1,2)
> equals(2,3)
> equals(3,4)
> [[1, 2, 3, 4]]

In case of single subscriber everything is correct.
If there are more subscribers, results are unexpected.
> dart.exe  --checked test2.dart 2
> equals(1,1)
> equals(1,2)
> equals(2,2)
> equals(2,3)
> equals(3,3)
> equals(3,4)
> equals(4,4)
> [[1, 2, 3, 4], [1, 2, 3, 4]]

Expected output (order of lines can be different):
> dart.exe  --checked test2.dart 2
> equals(1,2)
> equals(1,2)
> equals(2,3)
> equals(2,3)
> equals(3,4)
> equals(3,4)
> [[1, 2, 3, 4], [1, 2, 3, 4]]

Dart VM version: 1.23.0 (Fri Apr 21 03:13:00 2017) on "windows_x64"

**Comment by lrhn** [comment]
Good catch. It's a bug in `_DistinctStream` - the "previous" store is on the stream, not the subscription, so when you do multiple subscriptions on the same stream, everything blow up.

**Comment by alsemenov** [comment]
If `equals` returns `p==n` instead of `false`, the result for second subscription will be completely wrong:
>[[1, 2, 3, 4], []]

**Comment by lrhn** [comment]
Exactly, because it shares the "last seen" between multiple listeners, so when the first listener sees "1", it means that the next listener drops it.
