### ISSUE TITLE
Changelog: `void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29646]
This is the changelog issue for #28939.

**Comment by whesse** [comment]
Is this issue finished now?  Can it be closed?

**Comment by eernstg** [comment]
Yes, it landed in 9820535bc17ac92bbb80bdf98274efd1a38cdaf7 on 2017-05-18.

**Comment by zoechi** [comment]
Does this mean that using `=>` is now fine for setters?

**Comment by floitschG** [comment]
Yes. It will be.
I believe we haven't yet changed the analyzer's check, though.

**Comment by eernstg** [comment]
My conclusion was that the analyzer already covers setters with the same code that handles other functions. It's active from 6cb0966401f2a53196358945c0f78a32c575a8dc, 2017-05-11, and that seems to be included in 1.24.0-dev.5.0.
