### ISSUE TITLE
Commit "Use kernel frontend ..." causes compilation failure on MacOS

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29645]
The symbols need to be sorted somehow, on Mac.  Perhaps in the header file?

Reverted commit d91f228766a2c1708bec8f62bbe2756e4a529f5e
with https://codereview.chromium.org/2884383005/

Error is:[942/1007] PACKAGE FRAMEWORK 'Chromium Framework.framework', POSTBUILDS
FAILED: Chromium Framework.framework 
./gyp-mac-tool package-framework 'Chromium Framework.framework' A && 
...
 && tools/build/mac/verify_order _ChromeMain "${BUILT_PRODUCTS_DIR}/${EXECUTABLE_PATH}"); G=$?; ((exit $G) || rm -rf 'Chromium Framework.framework') && exit $G) && touch 'Chromium Framework.framework'
tools/build/mac/verify_order: unordered symbols in /b/build/slave/dtmimacbe/build/src/out/Release/Chromium Framework.framework/Versions/A/Chromium Framework:
_Dart_CompileSourcesToKernel
ninja: build stopped: subcommand failed.

**Comment by aam** [comment]
Just wanted to confirm - I don't think I will be able to avoid temporary breakage because the fix for the above will require one submit to Dartium repo(https://codereview.chromium.org/2887183003 in review) and ore more submit to Dart repo to pull Dartium repo with the change(similar to https://github.com/dart-lang/sdk/commit/a96e92050836b642c0d0df362b0763c821e243a2).

@terrylucas

**Comment by whesse** [comment]
I think it could be done without breaking:  The submit to Dartium repo can be done before the breaking change to Dart, then the Dart change and the Dartium DEPS roll can be in the same CL.

If not, then yes, breaking temporarily is OK.

**Comment by aam** [comment]
Ah, right. Or perhaps Dart Dartium DEPS can be rolled forward after the order is changed in Dartium, but before new method is introduced in Dart. This is to separate potential problems introduced by the roll itself.
Is there particular person who normally does the Dartium roll?

**Comment by aam** [comment]
adding @alan-knight while Terry is offline.

**Comment by aam** [comment]
Reassigning to @alan-knight to land prerequisite https://codereview.chromium.org/2888283003/. This cl rolls forward dependency on dartium.deps/DEPS  to include updated order file.

**Comment by alan-knight** [comment]
Yes, I wanted to wait on that until we'd pulled the dev version this morning, and then the bots seemed to be in a very unstable state at the moment, so I'm waiting a bit.

**Comment by aam** [comment]
Makes sense, Alan. No rush. Thanks for the update!
