### ISSUE TITLE
Analysis Plugin arch: edit required to see errors

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#29641]
Looks like I don't have an easy means to start analyzing files until they are edited.

Should `analysis_plugin` scan the directory on start, and report `fileAdd` events for the starting contents?

(put both bug and enhancement, because its a bug, that could be fixed via enhancing the plugin lib)

**Comment by bwilkerson** [comment]
Yes, the plugin needs to scan the directory when an `analysis.setContextRoots` request is received. I'm guessing that `ServerPlugin` can do that in `handleAnalysisSetContextRoots` so that subclasses don't need to worry about it.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2886343002/
