### ISSUE TITLE
language/bool_check_test with --enable-asserts brings out a semantic ambiguity

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29647]
Boolean conversion may be considered to be associated with a typing issue, for example, "for `if (e)..`, is the value of `e` a boolean?". In production mode, `true` will select the 'then' branch and all other values will select the 'else' branch (so everything else than `true` is false, including `null`). In checked mode `true` will select 'then', `false` will select 'else', and every other value (including `null`) will throw an `AssertionError`.

Both the Dart VM and dart2js have an `--enable-asserts` option, and it is intended to enable `assert` without enabling the checks associated with type annotation based assertions in checked mode. So this is a point in the spectrum between production mode and checked mode.

However, the Dart VM enables the `assert(v != null)` which is part of boolean conversion, and dart2js does not. The former could be supported by the fact that it is specified to be an `assert`, and the latter could be supported by the fact that `--enable-asserts` should enable user specified assertions, not the implicitly generated ones.

With this discrepancy, the test `language/bool_check_test.dart` cannot succeed with the option `--enable-asserts` for both the Dart VM and dart2js.

At this point (May 18, 2017), the test has been marked in  `language/language_dart2js.status` as having a RuntimeError.

If we decide that the boolean conversion assertions should _not_ be enabled, the Dart VM and the test will need to be adjusted, otherwise dart2js will need to be adjusted to enable those assertions.

**Comment by lrhn** [comment]
The `--enable-asserts` flag makes sense for strong mode, since there is no checked/production mode switch any more (well, there is, it's just only affecting actual asserts, not "type assertions").

For Dart 1 (because boolean conversion is not a thing in strong mode/Dart 2 anyway), dart2js should have an assertion in checked mode, so I see no reason to not have it in `--enable-asserts` mode.

On the other hand, there is no formal specification of `--enable-asserts` for Dart 1, so I really don't care if the tools act differently, and I we should only be checking our `language` tests in checked mode and production mode, not this odd and unspecified hybrid.
That is, I don't care if that particular test doesn't work with `--enable-asserts`, it's not testing real language semantics. Non-standard semantics can do whatever they want, they're just not Dart semantics.

**Comment by eernstg** [comment]
It sounds reasonable that we will not have a notion of a boolean conversion in Dart 2 / strong mode. As long as we do not have non-null types, this means that expressions which are subject to boolean conversion in Dart 1.x will now be forced to have type `bool`, and hence they can have the values `true`, `false`, and `null`. Presumably there will be a new, custom rule saying that it is a dynamic error if the value is `null`, now that we don't have boolean conversion.

The specification verbiage on this topic will probably not say that "it works like `assert(v != null)`", because that would mean that this is not checked by default, only when running with `--enable-asserts`, and I would expect Dart 2 / strong mode to check for `null` in this situation under all circumstances.

This means that `--enable-asserts` will not have any effect on the treatment of locations which are today subject to boolean conversion, which could be taken as an argument that it should also have no effect on boolean conversion in Dart 1.x.

**Comment by eernstg** [comment]
I'd suggest closing this (area-language) issue, noting that Dart 2 requires a boolean assignable expression wherever boolean conversion used to happen. This means that there will not be anything special about the condition of an `if` statement etc., it will be handled exactly like any other location expecting a value of type `bool`, and it is a run-time error if the value turns out to be `null`. We don't generally specify which error is thrown.

Concretely, the spec never mentions `TypeError`, only CyclicInitializationError, NoSuchMethodError, AbstractMethodError (presumably obsolete), AssertionError, AbstractClassInstantiationError (obsolete), ConcurrentModificationError, and CastError (only for `as` expressions), and there is no indication which error must occur at the point where we have failuer at a type check which was generated implicitly due to assignability.

We might want to introduce an "exact type"-ish diagnostic message in the case where the static type is `Null`, rather than just upcasting it to `bool` (and we may wish to do the same thing in other similar situations like `(null as String).substring()`), but we can do that in another issue.

So, @lrhn, @leafpetersen, do you agree that we can close this and conclude as stated above?

**Comment by eernstg** [comment]
Closing: As of 5fab3242f4716c6f14036019acbb55a3fefe282b there is no notion of boolean conversion any more, and it is a run-time error when `null` is encountered in those situations where boolean conversion used to be applied. This eliminates the special case which caused the ambiguity ("boolean conversion uses an actual `assert`, but it's compiler generated, so should we treat it like a user-written `assert`, or should we treat it like a compiler generated run-time check?"). Without that ambiguity, this issue is now obsolete.
