### ISSUE TITLE
Please, clarify Stream.every() description

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29652]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/every.html) for dart:async:Stream.every() reads:

> Future&lt;bool&gt; every(
> bool test(
> T element
> )
> )
> Checks whether test accepts all elements provided by this stream.
> 
> Completes the Future when the answer is known. If this stream reports an error, the Future will report that error.

Please, clarify the case when `test` throws error. Will the returned future be completed with that error?

**Comment by srawlins** [comment]
The [docs](https://api.dartlang.org/dev/dart-async/Stream/every.html) now contain the sentence:

> If this stream contains an error, or if the call to test throws, the returned future is completed with that error, and processing stops.
