### ISSUE TITLE
Support new compile-time errors for initialization clashes

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29656]
A recent [update to the language specification](https://codereview.chromium.org/2843733002/) includes two new compile-time errors for initialization conflicts: It is a compile-time error to have an initializer or an initializing formal initializing a final variable with an initializing expression. The rationale is that similar situations are already compile-time errors. For example:

```dart
class C {
  final x = 42; // A final instance variable with an initializer.
  C(this.x); // Compile-time error: `x` is initialized already, and final.
  C.someName(): x = 41; // Compile-time error: `x` is initialized already, and final.
}
```
Tool specific issues:

- [x] analyzer #29657.
- [x] vm #29658.
- [x] dart2js #29659.
- [x] vm-kernel #29900.

**Comment by a-siva** [comment]
What about something like this:

class C {
  final x = 42;
  C.someName() {
    x = 100;  // Should this also be a compile time error ??? currently the VM produces a runtime error.
  }
}

The runtime error reported is  Class 'C' has no instance setter 'x='.

**Comment by eernstg** [comment]
No, the treatment of that setter invocation is unchanged, the addition to the spec only deals with initializer lists and initializing formals vs. locally initialized final variables:
```
It is a compile-time error if $k$'s initializer list contains an initializer for
a final variable $f$ whose declaration includes an initialization expression.
...
It is a compile-time error if $k$ includes an initializing formal for a final variable
$f$ whose declaration includes an initialization expression.
```

**Comment by srawlins** [comment]
All child bugs are closed. @eernstg looks like we can close?

**Comment by eernstg** [comment]
Indeed, thanks!
