### ISSUE TITLE
Optimize basic intercepted operations

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#2965]
Right now, we're using certain non-inlined helpers for implementing the basic intercepted operations:

$.ge = function(a, b) {
&nbsp;&nbsp;if ($.checkNumbers(a, b) &equals;&equals;&equals; true) {
&nbsp;&nbsp;&nbsp;&nbsp;return a &gt;= b;
&nbsp;&nbsp;}
&nbsp;&nbsp;return a.operator$ge$1(b);
};

This needs to be faster (either through manual or automatic inlining of the helpers). This issue is related to issue #2964.

**Comment by rakudrama** [comment]
Closing as obsolete - we don't do interceptors that way anymore.
