### ISSUE TITLE
Please, clarify how Stream.expand() handles errors

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29653]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/expand.html) for dart:async:Stream.expand() reads:

> Stream&lt;S&gt; expand&lt;S&gt;(
> Iterable&lt;S&gt; convert(
> T value
> )
> )
> Creates a new stream from this stream that converts each element into zero or more events.
> 
> Each incoming event is converted to an Iterable of new events, and each of these new events are then sent by the returned stream in order.
> 
> The returned stream is a broadcast stream if this stream is. If a broadcast stream is listened to more than once, each subscription will individually call convert and expand the events.

Please, clarify how errors are handled:
1. Errors in the original stream. (are they just copied to resulting stream?)
2. Errors thrown by `convert' (are they just added to resulting stream? Do they stop further processing?)
3. Errors thrown by `Iterable` returned by `convert`?

**Comment by srawlins** [comment]
The [current docs](https://api.dartlang.org/dev/dart-async/Stream/expand.html) contain this information.
