### ISSUE TITLE
Make dart2js-drt builders use upstream content_shell instead of our legacy dartium-based content_shell

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#29655]
Our `dart2js-drt-*` builders became flaky after chrome-50 roll into dartium. There is not really a reason (afaik) for us to use the dartium-based content_shell we build ourselves for running dart2js output.

We could consider removing runs of dart2js output on drt entirely if it provides little value in addition to the existing browser tests we have. The dart2js team should maybe decide this. Though we should be careful, since `dart2js-drt` seems to be the only configuration where we run with `--csp`.

If we keep the `dart2js-drt` builders, we should switch to upstream content_shell from chrome instead, which might not have the flakiness issue.

/cc @whesse @sigmundch

**Comment by whesse** [comment]
We are removing drt builders and support for drt in the recipes.  We propose removing content_shell support completely in the testing scripts, since it adds little value.

**Comment by matanlurey** [comment]
I'm guessing we no longer care about ContentShell.

**Comment by whesse** [comment]
We have removed content_shell (dumprendertree) support from the test scripts, because it has been replaced in chromium with headless chromium, which works completely differently.  If we want to use headless chromium, we should implement support for it from scratch.
