### ISSUE TITLE
Invalid sourcemaps for some files

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#29663]
@leafpetersen reported, and I can repro, that 

../pkg/dev_compiler/tool/ddw lib_strong/async/catch_errors22_test.dart

creates a sourcemap that Chrome is rejecting as either being not sorted or having duplicates. Unfortunately Chrome doesn't say where, and the error gets reported from C++ code.

**Comment by alan-knight** [comment]
Calling this high. It's not clear how often it occurs, but when it does it makes the entire sourcemap invalid.

**Comment by jmesserly** [comment]
Debugging this test seems to work now in latest Chrome
