### ISSUE TITLE
Introduce warning when using MIPS build flag

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/sdk#29678]
We are very likely to discontinue support for MIPS because it is not being used (at least to the best of our knowledge) and results in actual extra work for maintaining our VM implementation.

- [ ] We should display a warning when building with the flag for MIPS, e.g. "Warning: MIPS architecture is unlikely to be supported in upcoming releases. Please consider using another architecture and/or file an issue explaining your specific use of and need for MIPS support."
- [ ] Along with this, we should also include a line in the change log explaining our plans for MIPS, e.g. "As of this release, we'll show a warning when using the MIPS architecture. Unless we learn about any critical use of Dart on MIPS in the meantime, we're planning to deprecate support for MIPS starting with the next stable release."

**Comment by sekharnadiminti** [comment]
@anders-sandholm , Is there any specific modules/ APIs that needs to be implemented / tweaked  if start building App ( with Flutter 3.24 and Dart 3.5 )for MIPS platform.

In addition do we need to  tweak JIT and AOT compilers as well ? If yes, can you please throw some light on how to do that .

**Comment by mraleph** [comment]
@sekharnadiminti you can look at https://github.com/dart-lang/sdk/commit/ac16656161d8a525189e3f8ac3eaed0846f7b8f1 to estimate amount of changes needed in the Dart SDK. At the very least for every file `*_arm64{.cc,.h}` there needs to be a corresponding `_mips` variant. Implementing support for a new architecture is a fairly significant undertaking.

**Comment by sekharnadiminti** [comment]
@Slava Egorov,

Thank you so much for your help !! This will really help me plan further
work on this project for MIPS platform

**Comment by sekharnadiminti** [comment]
@mraleph ,
Do we need to make any other changes in flutter engine layer or Dart SDK changes alone sufficient enough ?
As the targeted platform is based on Linux running on MIPS platform, I am anticipating some customization needed at embedder ( backend) . This part may be uncovered after I start running one sample app .Before that, If I needed to do some obvious changes on the flutter side , Please share the information.

Thank you so much for your guidance.
-- Chandra sekhar N

**Comment by mraleph** [comment]
> Do we need to make any other changes in flutter engine layer or Dart SDK changes alone sufficient enough ?

Most likely just build system changes and some wiring in the `flutter` CLI to support targeting MIPS.

**Comment by sekharnadiminti** [comment]
> > Do we need to make any other changes in flutter engine layer or Dart SDK changes alone sufficient enough ?
> 
> Most likely just build system changes and some wiring in the `flutter` CLI to support targeting MIPS.

Thank you for the response
