### ISSUE TITLE
Instructions for cross-compiling to Pi are out of date

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29675]
The instructions on this page no longer work:
https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Raspberry-Pi

It now says:
```
The --toolchain flag is only supported by the gyp build.
When using the GN build, set the toolchain and sysroot using gn.py.
```

...but it doesn't say what that actually means so I'm not really sure where to go from here.

**Comment by Hixie** [comment]
In fact most of the wiki pages about how to build Dart are out of date.

**Comment by Hixie** [comment]
The following steps seemed to work, after downloading the toolchain mentioned on the wiki page, except that I then ran into https://github.com/dart-lang/sdk/issues/29676:
```
tools/gn.py --arch=arm --toolchain-prefix=arm=/home/ianh/dev/pi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf- --mode release
tools/build.py --arch=arm --mode release
```

**Comment by zanderso** [comment]
I'll update the Raspberry Pi instructions after the fix for #29676 lands.

**Comment by marcinsydor** [comment]
I've cloned [the repository](https://github.com/raspberrypi/tools). But tools folder does not contain `gn.py` file.

**Comment by zanderso** [comment]
tools/gn.py is in the Dart SDK tree.

**Comment by marcinsydor** [comment]
Thanks, I'm new to Raspberry Pi and it looks I need to read more to understand how all it works. Do you know if there are any instructions how to install dart sdk on the latest Raspberry Pi 3 B?

**Comment by zanderso** [comment]
On a Pi 3, one of our pre-built arm64 SDK builds may work: https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.2/sdk/dartsdk-linux-arm64-release.zip

**Comment by zanderso** [comment]
Updated the Wiki page.

**Comment by marcinsydor** [comment]
I've tested that pre-built SDK yesterday but when I'm typing `./dart --version` I'm getting an error `-bash: ./dart: cannot execute binary file: Exec format error`.
