### ISSUE TITLE
dart2js: `void` arrow setters should allow any rhs type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29680]
This is the dart2js specific issue for #29679. The feature is already supported, so this turned out to be an extension of the test suite only.

**Comment by eernstg** [comment]
Given that this just adds some tests, we could live with a later milestone. But for now I'll try to get it into 1.24.

**Comment by dgrove** [comment]
1.24 is very soon. This doesn't look like a hard requirement, so moving to 1.25.

**Comment by eernstg** [comment]
Landed in 8aef60a78f2043a51c0d36b3b809f30e10ea3ed2, I was just waiting for the tree to be reopened.
