### ISSUE TITLE
improve error message on final-static

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29697]
Current error for:
```dart
  class A {
    final static String X = "";
  }
```
says
```
Error: Can't have modifier 'static' here.
Try removing 'static'.
  final static String X = "";
        ^^^^^^
```
Maybe the suggestion should be: try moving 'static' earlier?
Maybe we should recover from this and just provide a warning?

**Comment by peter-ahe-google** [comment]
FWIW, recovering from this problem should be easy: the parser reports a recoverable error.

I agree that the error message needs to be improved.

**Comment by jensjoha** [comment]
Current error message:
```
tmp.dart:2:11: Error: The modifier 'static' should be before the modifier 'final'.
Try re-ordering the modifiers.
    final static String X = "";
          ^
```
Which seems to be what was wanted --- can we close this issue?

**Comment by peter-ahe-google** [comment]
Thank you, Jens!
