### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rishirdua** [dart-lang/sdk#29696]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4073.35`
- `1.24.0-dev.3.0`
- `IU-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-75-generic unknown, screens 1920x1200, 1920x1200`

**Comment by devoncarew** [comment]
@rishirdua, there should be a stack trace associated w/ this feedback report; can you append? Thanks for the report (and please re-open when you have the trace).
