### ISSUE TITLE
Please, describe method Stream.fold()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29694]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/fold.html) of method dart:async:Stream.fold() reads:

> Future&lt;S&gt; fold&lt;S&gt;(
> S initialValue,
> S combine(
> S previous,
> T element
> )
> )
> Reduces a sequence of values by repeatedly applying combine.

Please, provide more information about the method.
Here are some helper questions:
1. When the returned future is completed?
2. `combine` returns `Future` instance. (Is it allowed?)
3. Is it like List.fold()?
4. Error handling
4.1 errors in original stream
4.2 `combine` throws error
4.3 is it fail-fast? (i.e. first error stops further handling)

**Comment by lrhn** [comment]
1. When the stream completes.
2. The return type of `combine` is S. That can be a future, but the `fold` method doesn't do anything special in that case.
3. It is exactly like List.fold.
4. It cancels on the first error (it returns a future so it has to, it can only report one result), either from the original stream or from the `combine` call.
