### ISSUE TITLE
Webstorm debugger doesn't display variables in nested async

### ISSUE THREAD

**Issue by sestegra** [dart-lang/sdk#29699]
I'm not sure if the issue is on Dart itself or on Webstorm.
See issue on Webstorm database.
https://youtrack.jetbrains.com/issue/WEB-27049

If you put a breakpoint on 'return x;' statement, 'x' variable isn't displayed on Webstorm Variables panel.

``` dart
import 'dart:async';

Future<String> foo() async {
  var x = "x";
  return x;
}

Future<Null> main() async {
  String x;
  print("Start");
  x = await foo();
  print(x);
  print("End");
}
```

**Comment by alexander-doroshko** [comment]
Looks like this can be closed as fixed quite a while ago.
