### ISSUE TITLE
override_field_test/03 should be extended

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29703]
# TBF: we should check conflicts not only for methods, but for accessors too

This line was in the status file.  Changing to an issue, and putting the issue on the test status line:

override_field_test/03: Fail # Issue XXXXX

No comments or info should be in status files, only issue numbers on the same line as the test they apply to.

**Comment by keertip** [comment]
This can be closed, as there have been changes made to the status files and this may not be an issue anymore.
