### ISSUE TITLE
Crash on windows after IO thread change

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29702]
The test "standalone/io/many_directory_operations_test" is crashing on windows ia32 after the change that creates more io threads dynamically, https://github.com/dartlang/sdk/commit/3310e0cebd9c95cd508fdb5ef061b73422c72f85
"[dart:io] Remove collisions from IO Service port dispatch"

This needs to be fixed, and the fix needs to be cherry-picked to the 1.24 dev branch before it can be released as stable.

FAILED: none-vm debug_ia32 standalone/io/many_directory_operations_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
_beginthreadex error: 12 (Not enough space)
e:\b\build\slave\vm-win-debug-ia32-be\build\sdk\runtime\vm\thread_pool.cc: 359: error: Could not start worker thread: result = 12.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2903013002
