### ISSUE TITLE
Pub serve in DDC mode doesn't work for project from web/subdir

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#29704]
Environment: Windows 10, Dart SDK 1.24.0-dev.5.0. 
Steps:
- Unzip the [attached project](https://github.com/dart-lang/sdk/files/1025571/anagram_in_subdir.zip), run `pub get`.
- Run `pub serve` from the command line.
- Open `http://localhost:8080/subdir/index.html` in Chrome. The app works just fine.
- Restart pub in DDC mode: `pub serve --compiler=dartdevc`.
- Open `http://localhost:8080/subdir/index.html` in Chrome. The app doesn't load.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/pub#1622
