### ISSUE TITLE
IntelliJ crash during Angular2 usage

### ISSUE THREAD

**Issue by mk13** [dart-lang/sdk#29708]
I've been noticing this issue this morning; haven't seen it yesterday; this occurred after I updated my sdk to the latest to get some recent changes.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4249.39`
- `1.24.0-dev.4.0`
- `IU-171.4249.39, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 1440x900, 1200x1920  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/83/h011zfcd1x3d5nshw8mb8wj000d2hp/T/report444.txt

```
Dart analysis server, SDK version 1.24.0-dev.4.0, server version 1.18.0, error: Analysis failed: /Users/maxkim/dart/angular2-dart-analyzer/playground/lib/transclusion_component.dart context: exception_20170524_092849_015
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:128)
#1      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1068)
#2      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:1006)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:236)
#4      _HashVMBase

**Comment by scheglov** [comment]
The crash logs are written into the ~/.dartServer/.analysis-driver folder.
There is also a lot of other files.
But we need only exception* files.

Could you please archive these files and either mail, or share them is some other way with Brian and me?

**Comment by mk13** [comment]
Sure I'll email it to both of you right now.

**Comment by mk13** [comment]
Additional note: this is only occurring during NESTED angular2 projects. 

So if the root project doesn't have angular2 imported, but some sub-project does, I see this issue. On the other hand if the root project contains angular2, it's working perfectly fine.

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
