### ISSUE TITLE
unhelpful type inference in assertion

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#29712]
At pkg/compiler/lib/src/compiler.dart, at about line 1449, there is this assertion:

```
      // `true ==` prevents analyzer type inference from strengthening element
      // to AnalyzableElement which incompatible with some down-cast to ElementX
      // uses.
      assert(true == element is AnalyzableElement,  /// <<<<<<<<
          failedAt(element, 'Element $element is not analyzable.'));
      ...
        Node tree = _compiler.parser.parse(element);
```

If I remove the `true ==`, I get a warning at the call to parse that element is an AnalyzableElement, not the required ElementX.

The problem is that in this code, element is _both_ AnalyzableElement and ElementX.
AnalyzableElement extends Element
ElementX extends Element
So the assertion that element is AnalyzbleElement should not invalidate that we can downcast to ElementX.

**Comment by bwilkerson** [comment]
I suspect (but haven't verified) that this isn't type inference, but rather the type propagation that is only used in analyzer.

**Comment by lrhn** [comment]
In either case, the specification does not allow type propagation to pass from assert condition to the following code, so the language part of this question is clear.
(In time, I hope it will, but improved type propagation is not here yet).

**Comment by bwilkerson** [comment]
Given that analyzer no longer does type propagation, I'm assuming that this is stale. Please let us know if you're still seeing this problem.
