### ISSUE TITLE
cascading operators break strong mode type checking

### ISSUE THREAD

**Issue by zelam** [dart-lang/sdk#29718]
https://dartpad.dartlang.org/645ed8079bc07d4976a6cc773a2fa269

Derived d = new Base()..val = 'd';
Derived e = new Base();

I expect both those lines to have a compile time error in strong mode, but only the second line does

**Comment by leafpetersen** [comment]
Note that ``--no-implicit-casts` will make both of those errors.  But agreed, the code that looks for "stupid" downcasts should also catch cascades.

**Comment by jmesserly** [comment]
this is now being tracked in https://github.com/dart-lang/sdk/issues/30542
