### ISSUE TITLE
Quick Documentation in Intellij dropping generic method parameters from signatures

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29714]
Stream.transform has the following signature:

```dart
  Stream<S> transform<S>(StreamTransformer<T, S> streamTransformer)
```

Quick documentation in Intellij shows the following:

![image](https://cloud.githubusercontent.com/assets/8484504/26419266/f395b8b2-4073-11e7-9a39-33542c5beb44.png)

Note that the generic method parameter is missing (but referenced in the type).

Running from bleeding edge Dart SDK  (1.24) 

```
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.21, built on April 19, 2017
Licensed to Dart Language / Leaf Petersen
Subscription is active until October 5, 2017
For non-commercial open source development only.
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2909943004/
