### ISSUE TITLE
[Strong mode] Should error out if a function does not declare return type

### ISSUE THREAD

**Issue by postmasters** [dart-lang/sdk#29726]
Some code to demonstrate the problem:

```dart
class LongClassName {
  LongC1assName() {
    ...
  }
}
```
Typos like this are common enough and they are really hard to spot. It would be nice to forbid such function declaration.

**Comment by matanlurey** [comment]
Does `--no-implicit-dynamic` catch this?

https://www.dartlang.org/guides/language/analysis-options#specifying-strong-mode

**Comment by postmasters** [comment]
Yes, that flag works. How about defaulting that flag to true?

**Comment by postmasters** [comment]
(Or for that matters, all the "strong" flags to true?)

**Comment by matanlurey** [comment]
/cc @leafpetersen would know more about plans on defaulting.

Internally we have a strict one-version policy, and defaulting to true would mean upgrading all lines of Dart - quite an effort. I'm not sure we are there yet.

**Comment by srawlins** [comment]
`--no-implicit-dynamic` requires massive changes to most any idiomatic Dart package. I recommend enabling the [always_declare_return_types](http://dart-lang.github.io/linter/lints/always_declare_return_types.html) linter rule.
