### ISSUE TITLE
Please merge branch ddc-dev into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29729]
@whesse @mit-mit @kasperl 
These are fixes (since dev) for internal DDC bugs and have been already rolled internally.  See last two commits here:

https://github.com/dart-lang/sdk/commits/ddc-dev

The master CLs did not merge cleanly.  I've rebased them onto the dev branch and uploaded to a ddc-dev branch.  Please merge that branch in.

**Comment by dgrove** [comment]
landed c0637fccd8a28b2cc84249957046d00f6c3a3cc3 for 1.24.0-dev.6.3
