### ISSUE TITLE
Web: Global exception handling

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29727]
AngularDart uses `runZoned` and `Zone#runGuarded` to catch and handle uncaught exceptions, collect them, and forward to an interface (called `ExceptionHandler`) that customers can override to log exceptions, for example, to a backend service like [sentry.io](https://sentry.io).

Below is an example of the code we have to generate as a result:

```dart
ButtonElement _el_1;

build() {
  _el_1.addEventListener('click', eventHandler0(ctx.onClick));
}
```

Where `eventHandler0` is implemented as:

```dart
VoidFunc1 eventHandler0(VoidFunc0 handler) {
  return (event) {
    markPathToRootAsCheckOnce();
    if (NgZone.isInAngularZone()) {
      handler();
    } else {
      appViewUtils.eventManager.getZone().runGuarded(handler);
    }
  };
}
```

We'd like to simplify this to:

```dart
VoidFunc1 eventHandler0(VoidFunc0 handler) {
  return (event) {
    markPathToRootAsCheckOnce();
    handler();
  };
}
```

Unfortunately, this means that if `handler()` throws an exception, it is not forwarded to `ExceptionHandler`, so production cannot log to a service. For example, here is [how sentry tells users to setup logging in JavaScript](https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror.html):

> ```js
> window.onerror = function (msg, url, lineNo, columnNo, error) {
>   var errorData = {
>      name: ex.name, // e.g. ReferenceError
>      message: ex.line, // e.g. x is undefined
>      url: document.location.href,
>      stack: ex.stack // stacktrace string; remember, different per-browser!
>    };
>    $.post('/logger/js/', {
>      data: errorData
>    });
>   return false;
> }

Ideally, we'd like a good hook to do this in Dart, but that also would maintain Dart semantics, and be compatible with Dart sourcemaps, etc. I don't know too much about this world, though I'm willing to learn.

**Comment by vsmenon** [comment]
@terrylucas 

What happens `Window.onError` in Dart?

https://api.dartlang.org/stable/1.23.0/dart-html/Window/onError.html

**Comment by floitschG** [comment]
Also filed https://github.com/dart-lang/sdk/issues/29775

I just did a short test with `window.onError`, and that seemed to work. (I don't know how to return "false" to the `onerror` callback, since we transform the callback into a stream. Do we have a common pattern in the html lib for that?)

**Comment by matanlurey** [comment]
We have other requirements now that would prevent us from using `window.onError`.

Closing as unneeded for now.
