### ISSUE TITLE
Please merge revision 5919a12038920d5084116bd101e8013b789765bb into dev channel

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29724]
@whesse @mit-mit @kasperl 

This fixes serving apps from a subdirectory of `web` on windows, with ddc (see https://github.com/dart-lang/pub/issues/1622).

5919a12038920d5084116bd101e8013b789765bb

This merged cleanly

**Comment by jakemac53** [comment]
Note that I will have a few more coming as well, if you want to late and do them all at once.

**Comment by dgrove** [comment]
Any more? I'll be doing this integration pretty soon.

**Comment by jakemac53** [comment]
There are two more coming, but one is still out for review and the other is blocked on it (but has lgtm).

**Comment by dgrove** [comment]
OK - I'll go ahead with this one for tonight.

**Comment by jakemac53** [comment]
Sgtm, thanks!

**Comment by jakemac53** [comment]
97b750425db5568aa16f3cf0fd808d933151e2dd is also ready now

**Comment by dgrove** [comment]
https://github.com/dart-lang/sdk/commit/5919a12038920d5084116bd101e8013b789765bb no longer merges cleanly against dev.

**Comment by jakemac53** [comment]
Closing as we talked offline, looks like dev got moved up to a more recent version somehow....

**Comment by dgrove** [comment]
It turns out that 5919a12038920d5084116bd101e8013b789765bb was already picked in 83c8cbd70005e58102f2a8457c8b4340808251bf .

**Comment by dgrove** [comment]
97b750425db5568aa16f3cf0fd808d933151e2dd was merged in f5af3861966da44deb3092182433fd2436cb7b68
