### ISSUE TITLE
Please merge commit 93864c0db92d0a4066912507cbf5466b50996cc3 into dev channel

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29720]
@whesse @mit-mit @kasperl 

Commit 93864c0db92d0a4066912507cbf5466b50996cc3 reverts c94bebf28937e5250b2d6486503848645be142b1, which caused assertion failures in compilation on DBC.

**Comment by dgrove** [comment]
Merged in f5af3861966da44deb3092182433fd2436cb7b68
