### ISSUE TITLE
incorrect generated code for local shadowing parameter

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29733]
_From @jmesserly on January 11, 2016 22:11_

This doesn't work in Chrome 47:

``` dart
foo(a) {
  var a = 123;
  return a;
}
main() {
  print(foo(42));
}
```

Generates as:

``` js
  // ... module boilerplate ...
  'use strict';
  let dartx = dart.dartx;
  function foo(a) {
    let a = 123;
    return a;
  }
  dart.fn(foo);
  function main() {
    core.print(foo(42));
  }
  dart.fn(main);
```

Error will be something like:

```
> (function() { 'use strict'; return (a) => { let a = 123; return a; }; })()
VM399:2 Uncaught SyntaxError: Identifier 'a' has already been declared(…)
```

Seems to be same error with `function` or `=>`

I'll have to see what our compiler thinks is happening, but possibly this is just a fix in the JS renamer, to understand that JS treats locals and parameters as the same scope. (But Dart does not, therefore they should be two distinct JS temp variables in the JS AST we construct. The renamer should understand that renaming is necessary in this case to preserve semantics.)

Thanks to @jacob314 for catching this in Angular2.

_Copied from original issue: dart-archive/dev_compiler#409_

**Comment by jmesserly** [comment]
It looks like our Dart->JS transpile generates:

``` dart
  JS.Expression visitSimpleIdentifier(SimpleIdentifier node) {
    // <snip lots of cases that don't apply>
    return new JS.Identifier(name);
  }
```

The renamer isn't allowed to rename a JS.Identifier even if it wanted to.

Usually this is fine because ES6 block scope is pretty close to Dart's, but we'll have to do something about that difference between parameters and the top level of the function body.

**Comment by jmesserly** [comment]
probably the fix here is to add a new scope to reflect the Dart scope structure (rather than rename the variables)

**Comment by sircco** [comment]
i just hit that bug and it prevented me to use ddc althought dartium and dart2js worked fine

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2961863003
