### ISSUE TITLE
Kernel flow graph is built out of order

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29737]
The initial DebugStepCheckInstr and the sequence for the saving the current async stack trace are built after the function body and then appended to the beginning of the entry block. They manually save and restore the context level to account for this. The sequences should instead be built when needed and appended to the end of the entry block and not mess with the context level.

Also, the entry sequences vary between the VM flow graph builder and the kernel flow graph builder.
VM:
DebugStepCheckInstr
save async stacktrace
CheckStackOverflowInstr
build context

Kernel:
build context
save async stacktrace
DebugStepCheckInstr
CheckStackOverflowInstr

**Comment by a-siva** [comment]
@kmillikin @mraleph

**Comment by kmillikin** [comment]
I need more context for this issue.

We shouldn't consider it a bug that the graph is built out of order, where we take the behavior of the classic builder as the definition of what it means to be built in order.

The order in which instructions are created seems like an implementation detail so long as they are correct and occur in the correct order in the graph.

The classic flow graph builder and the Kernel flow graph builder put instructions together in a different way and use the state of the visitor in a different way, so it's natural that they might sometimes be different.  The only advantage of sticking to the "classic" order is that it makes it easy to compare the two implementations side-by-side, but that seems minor.

There does seem to be an issue with the way we call _asyncStackTraceHelper in the Kernel flow graph, I'll file a separate issue to track that.

For the second point, I observe a different order than you do.  Classic builder has (1) _setAsyncThreadStackTrace, (2) DebugStepCheck, (3) CheckStackOverflow, (4) AllocateContext:

```
B0[graph]:2
B1[target]:0
    t0 <- LoadLocal(:current_context_var @-8)
    t0 <- LoadField(t0, 72, immutable=0)
    PushArgument(t0)
    StaticCall:4( _setAsyncThreadStackTrace@7048458 t0)

    DebugStepCheck()

    CheckStackOverflow:6()

    t0 <- LoadLocal(:current_context_var @-8)
    t0 <- LoadField(t0, 24, immutable=0)
    PushArgument(t0)
    t0 <- Constant(#0)
    PushArgument(t0)
    t0 <- InstanceCall:54( ==, t0, t0)
    t1 <- Constant(#true)
    Branch if StrictCompare:56(===, t0, t1) goto (9, 10)
B10[target]:64
    goto:10 B2
B2[join]:8 pred(B10)
    t0 <- AllocateContext(5) T{Context}
    t1 <- LoadLocal(:tmp_local-15 @-15)
    t2 <- LoadLocal(:current_context_var @-8)
    StoreInstanceField({16}, t1, t2)
    t0 <- DropTemps(0, t0)
    StoreLocal(:current_context_var @-8, t0)
```

While the Kernel flow graph builder has (1) DebugStepCheck, (2) _setAsyncThreadStackTrace, (3) CheckStackOverflow, (4) AllocateContext.  That is, the first two are switched:

```
B0[graph]:2
B1[target]:0
    DebugStepCheck()

    t0 <- LoadLocal(:current_context_var @-7)
    t0 <- LoadField(t0, 24, immutable=0)
    PushArgument(t0)
    StaticCall:56( _setAsyncThreadStackTrace@7048458 t0)

    t0 <- LoadLocal(:current_context_var @-7)
    t0 <- LoadField(t0, 64, immutable=0)
    StoreLocal(:switch_expr @-8, t0)
    t0 <- LoadLocal(:switch_expr @-8)
    t1 <- Constant(#0)
    Branch if StrictCompare:48(===, t0, t1) goto (7, 8)

B7[target]:52
    CheckStackOverflow:4()
    t0 <- LoadLocal(:current_context_var @-7)
    t1 <- LoadLocal(:current_context_var @-7)
    t2 <- LoadLocal(:temp0 @-13)
    StoreInstanceField({80}, t1, t2)
    DropTemps(1)
    goto:8 B2

B2[join try_idx 0]:6 pred(B7)
    t0 <- AllocateContext(2)
    t1 <- LoadLocal(:temp0 @-13)
    t2 <- LoadLocal(:current_context_var @-7)
    StoreInstanceField({16}, t1, t2)
    StoreLocal(:current_context_var @-7, t0)
```

Is it observable (and correct) to have _setAsyncThreadStackTrace before DebugStepCheck?  Can we commit a test case that requires the correct order?

**Comment by kmillikin** [comment]
Filed https://github.com/dart-lang/sdk/issues/29771 to track the issue with _asyncStackTraceHelper.

**Comment by rmacnak-google** [comment]
I'm more concerned about the context level getting out of sync if the flow graph builder doesn't build fragments in order, since this can sometimes affect only the debugger and not normal program execution.

The ordering of _setAsyncThreadStackTrace and DebugStepCheck/StackOverflowCheck should be observable in the stack trace you get evaluating an expression in the debugger. I don't think one can step to this particular DebugStepCheck because the debugger would normally try to skip through the switch, though it might be possible to stay stopped there if it is reached as a breakpoint instead of via stepping.

**Comment by rmacnak-google** [comment]
Assumed stale.

**Comment by sjindel-google** [comment]
This is being addressed in https://dart-review.googlesource.com/c/sdk/+/67345, as part of breaking up untangling the spaghetti-code that has piled up in BuildGraphOfFunction.
