### ISSUE TITLE
Debugging with Dartium v. 1.24-dev.6.0

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#29743]
Summary:
There seems to be a problem when debugging web apps. I'm using https://github.com/dart-lang/sample-pop_pop_win here as an example, but I encountered the same problem in other samples. The current line in the code isn't marked, and the debug window shows an alarming number of unknowns.
The problem appears to be in dartium, since when I select new SDK with old Dartium it works fine, but old SDK with new Dartium results in the same error.

What steps will reproduce the problem?
1. Get a copy of Pop Pop Win at https://github.com/dart-lang/sample-pop_pop_win
2. Open the project in WebStorm 2017.1.3
3. Enable Dart support and get dependencies.
4. Set a breakpoint at \lib\src\stage\game_element.dart:131 (the void click(...) method)
5. Run index.html in debug mode and click on any balloon.
6. Maybe "Step Over" a couple of times.

What is the expected output? What do you see instead?
Expected:
WebStorm takes you to the tab with the breakpoint and highlights the current line, and the highlighting follows as you forward a few steps. Usual debug stuff in the debugger window.

Actual:
Not taken to the relevant tab, and position in code not highlighted, as well as a lot of "unknowns" in the debugger window.
![debugframe2017-05-30 10 37 09](https://cloud.githubusercontent.com/assets/20222678/26576681/095bc172-452a-11e7-963e-8b7dd86f3cea.png)

What version of the product are you using?
WebStorm (version 2017.1.3)
    • Dart 1.24-dev.6.0
    • Dartium 1.24-dev.6.0

On what operating system?
Windows 10

**Comment by alexander-doroshko** [comment]
Caused by Dartium sending `"Debugger.scriptFailedToParse"` events instead of `"Debugger.scriptParsed"`. Duplicate of https://github.com/dart-lang/sdk/issues/29640

**Comment by devoncarew** [comment]
Closing as a dupe, but thanks for the detailed bug info!
