### ISSUE TITLE
Please merge revisions into dev channel (pub related)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29741]
@whesse @mit-mit @kasperl @dgrove @kevmoo 

Updates the changelog to highlight changes in pub, and update to get new command line arg and pubspec configuration options (command line option changed from --compiler to --web-compiler).

1d9a2e8a950b96bd3296795746f07e08c666b7b6
5aba20af0d43420d1e1e781a2af039fe20b158d3

These both merged cleanly

**Comment by whesse** [comment]
Merged in 1.24.0-dev.6.5
