### ISSUE TITLE
Collisions on private mixin members that are static

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#29751]
Is the restriction added via https://github.com/dart-lang/sdk/issues/28809 supposed to also affect static members of mixins?

Example:
- a.dart
    ```dart
    class Mixin1 {
      static const _staticConstant = 1;
    }
    class Mixin2 {
      static const _staticConstant = 2;
    }
    ```

- b.dart
    ```dart
    import 'a.dart';
    
    class C extends Object with Mixin1, Mixin2 {}
    ```

- Error:
    > error: The private name _staticConstant, defined by Mixin2, conflicts with the same name defined by Mixin1. (private_collision_in_mixin_application at [over_react] lib/b.dart:3)

Ideally, I'd expect them not to, since you can't access static members without qualifying with them with the mixin name, and static members generally don't affect inheritance.

I realize that there may be restrictions introduced by the solution to https://github.com/dart-lang/sdk/issues/28809 that cause static members to be affected, but I'd hope that, eventually, the example above would not cause strong mode errors.

**Comment by lrhn** [comment]
I'd say that this should not happen.
The static members are completely ignored by mixin application (the "mixin derived from the class" of `Mixin1` does not contain any static methods), so there is no overlap.
