### ISSUE TITLE
improve DDC constructor speed

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29753]
I modified an example to use ES5 constructors here:
https://gist.github.com/jmesserly/e1c8d5bbda897b5837d3810a019832f1

performance seems to be significantly better than what we're doing now (even after some attempts to optimize our current pattern).

EDIT: another benefit is named constructors and unnamed ones will share more logic

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen

**Comment by vsmenon** [comment]
Thanks, @jmesserly !  Bumping to P1 and 1.25 assuming @leafpetersen 's measurements confirm this is a perf bottleneck.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2934623003/
