### ISSUE TITLE
Allow "!" for negation in status files

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#29756]
The status file expression format doesn't support negation. To get around that, it synthesizes some properties like "unchecked" from "checked" and "unminified" from "minified". That's not very discoverable.

Instead, it may be worth supporting "!" directly.

**Comment by lrhn** [comment]
Immediate workaround: The expression `$foo` is equivalent to `$foo == true`, so you can write `$checked != true` instead of `! $checked`.

Still, it should be easy to add and nice to read, so I'll try adding it.

**Comment by lrhn** [comment]
It was easy (or maybe it falsely appeared so), so CL: https://codereview.chromium.org/2913963002/
