### ISSUE TITLE
Please merge revision b987a126c541590cd201d54bc1002dd603cc86af into 1.24 dev channel

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#29761]
@whesse @mit-mit @kasperl

1.24 MergeToDev

New gclient DEPS file validator does not support the python code used to import our Dartium DEPS file.  These changes fix most of the problems.

74907cc8911535743d373ef5e7b70da69998a4b5 (wheese DEPS change)
b987a126c541590cd201d54bc1002dd603cc86af

This merged cleanly

**Comment by terrylucas** [comment]
Also, [b987a12](https://github.com/dart-lang/sdk/commit/b987a126c541590cd201d54bc1002dd603cc86af) pulls in a WebKit [CL](https://codereview.chromium.org/2915643002) that fixes IntelliJ unable to debug with Dartium.

**Comment by whesse** [comment]
And also pull in 499cb29c70ec381783360dd31d1f08461ea29960

**Comment by whesse** [comment]
Merged in 1.24.0-dev.6.5
