### ISSUE TITLE
Only enable native syntax in dart-ext libraries.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29763]
Fasta should be able to tell if a library needs the native syntax by being able to tell if a library is loaded as dart-ext.

It's possible that we need to extend kernel-service to make this information available.

**Comment by sigmundch** [comment]
Wouldn't it be sufficient to see the imports on that same library?

I thought that `native` was used in files that contain the `dart-ext` import.

**Comment by sigmundch** [comment]
oops, github misinterpreted my commit message.

**Comment by peter-ahe-google** [comment]
I think you're right.

**Comment by MrBirb** [comment]
@mit-mit This one as well?

**Comment by mit-mit** [comment]
Yes, closing as irrelevant due to https://github.com/dart-lang/sdk/issues/45451
