### ISSUE TITLE
The wrong argument is passed to _asyncStackTraceHelper

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#29771]
In the Kernel flow graph builder, we call _asyncStackTraceHelper and pass it the value in the context slot for :async_op.  However, we call the function before the context slot is initialized by Kernel code, so we are passing null.

Since the call to _asyncStackTraceHelper is added in the VM and the initialization of :async_op is done in Kernel code, it seems tricky to inject the call in the correct place.  It's probably simplest to change the Kernel async transformer to always add an explicit call to _asyncStackTraceHelper and make that function do nothing when FLAG_causal_async_stacks is false.

**Comment by rmacnak-google** [comment]
@aam ran into this trying to run the flutter_gallery app.

**Comment by aam** [comment]
This will become a highly visible problem on our path to switch Flutter to new frontend.
