### ISSUE TITLE
Dartium bots should not run tests if the build step fails

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29770]
See https://luci-milo.appspot.com/buildbot/client.dart/dartium-linux-x64-inc-be/3927

If the build fails, the test will just be running against some old or inconsistent build artifact. It also increases the time before the bot gets to a change that fixes the build.

@whesse @terrylucas

**Comment by athomas** [comment]
Dartium is going away in Dart 2.0.
