### ISSUE TITLE
Isolate.current.addErrorListener should use window.onerror in dart2js/DDC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29775]
Currently, there is no easy way to listen to uncaught errors.
dart2js/DDC should use `window.onerror` to listen to uncaught errors, when users start listening to the errors through `Isolate.current.addErrorListener`.

Currently assigning to the Isolate library, but it's a dart2js/DDC specific issue.

@sigmundch

**Comment by srawlins** [comment]
Web support for dart:isolate has been removed. [Announcement](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/djfFMNCWmkE).
