### ISSUE TITLE
Inconsistent direct subclasses information when super and subclass come from different snapshots

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#29774]
If `class A` comes from one snapshot `S0` (e.g. core libraries) and `class B extends A` comes from different snapshot `S1` (e.g. script snapshot) then we don't update array that tracks the list of direct subclasses of `A` when we load `S1` - `S1` contains `class B` in the type-finalized state, so in reality we will never update the direct subclasses array. 

This breaks optimizations that rely on this array, e.g. CHA. 

Here is a repro:

```dart
class _DebugDuration extends Duration {
  const _DebugDuration() : super(milliseconds: 42);
}

foo(x, y) {
  for (var i = 0; i < 100000; i++) {
    if (x != y) throw "";
  }
}

main(args) {
  final v = const Duration(milliseconds: 42);
  foo(v, new _DebugDuration());
}
```

(tried at 56e93fa2b0e1256addfe396858c572c216f28ab5)

```
╭─ ~/src/dart/sdk ‹56e93fa2b0›
╰─$ out/ReleaseX64/dart --snapshot-kind=script --snapshot=/tmp/x.snap  t/x.dart                                                                                                                                141 ↵
╭─ ~/src/dart/sdk ‹56e93fa2b0›
╰─$ out/ReleaseX64/dart /tmp/x.snap 
Unhandled exception:

#0      foo (file:///usr/local/google/home/vegorov/src/dart/sdk/t/x.dart:8)
#1      main (file:///usr/local/google/home/vegorov/src/dart/sdk/t/x.dart:14)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

We can fix things up by updating direct subclasses array whenever we finalize the class, instead of updating it when we finalizing types-in-class, but in general we need to make sure that there are no other situations like that when snapshoting. 

/cc @ErikCorryGoogle @rmacnak-google

**Comment by ErikCorryGoogle** [comment]
Slava's repro only works on the VMs with my CL in it, but add --max-polymorphic-checks=0 to trigger it on any recent VM.

**Comment by rmacnak-google** [comment]
Other cases I can think where loading some application libraries mutates core libraries:
 - the is_implemented bit, which can affect type test optimizations much like CHA
 - the arrays tracking canonical instances and types, which we've already handled
 - the array in the object store tracking all closure functions, which I don't think we update, but no closure functions should appear in a script snapshot anyway because it is saved before running any application code

**Comment by ErikCorryGoogle** [comment]
Should this bug be closed now?

**Comment by rmacnak-google** [comment]
Script snapshots no longer exist.
