### ISSUE TITLE
Provide opt-in object allocation tracking in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29781]
We've done some experimental work to support tracking the allocation sites of objects in DDC so that on cast failures we can point back to the original source location from which the object was allocated.  Customers have indicated that this would be valuable.  

We need to do this in a way that avoids slowing down normal execution.  If it proves to be too slow to track all objects, it would be sufficient to track a user-specified set of classes, since generally this feature will be used when tracking down a specific cast failure.

**Comment by natebosch** [comment]
@jmesserly - is there any chance of this happening or should we close this out?

**Comment by jmesserly** [comment]
It could happen. The question is: what should the UX be? If we have some concrete use cases, then we could implement something for those.

(It would probably require a compiler flag to opt-in. Other than that we have a lot of flexibility.)

**Comment by vsmenon** [comment]
No plans to do this.
