### ISSUE TITLE
Analyzer: Unresolved identifiers do not trigger warnings

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29783]
In AngularDart, users create metadata annotations like so:

```dart
@Component(
  /// List of other [Type] objects used to generate Dart code for the .html template.
  directives: const [ ... ],
)
class Foo {}
```

If one or more identifiers in the `directives: const [ ... ]` list are not resolved, i.e.:

```dart
class Bar {}

@Component(
  /// Oops: I meant to type 'Bar'.
  directives: const [Bear],
)
class Foo {}
```

`computeConstantValue` actually still works, returning an empty `List<DartObject>`. This is confusing to our users, because the error message we give them when we can't find a directive they used in their template (i.e. `<bar></bar> <-- No directive "bar" found.`) is similar to if they omitted it entirely.

Internally, using Bazel, there are a few cases where this occurs (internal issue b/38433857):

```dart
import 'package:bar/bar.dart';

@Component(
  directives: const [Bar],
)
```

Everything is fine as the _analyzer_ is concerned at development time (i.e. an IDE wouldn't report any problem) but they might be missing the dependency from their Bazel `BUILD` file:

```build
dart_library(
  deps = [], # Oops, we need "//third_party/dart/bar" here!
)
```

And the same issue as above occurs. 

Questions:

1. Is it possible to have analysis fail, early, if something cannot be resolved?
2. If not, what should I do to give users a better error message that can help them resolve the issue?

Specifically, it would be nice if analysis fails if at least one `import` statement failed to resolve, or at minimum, we could report that to the user, i.e. something like:

> WARNING: Could not resolve package:bar/bar.dart. Did you declare this dependency?

/cc @jakemac53 @stereotype441

**Comment by bwilkerson** [comment]
In the case where an identifier is undefined, I would have expected that analyzer would have produced errors. The API you're using doesn't have any way to report those errors, but you can ask the context for the errors associated with that source and see whether there are any.

In the case where the identifier is being resolved even though it shouldn't be, I don't understand why it wouldn't be able to produce a DartObject representing the value of the identifier. Is this a case where it's succeeding in one environment but then failing in another?

**Comment by matanlurey** [comment]
> In the case where an identifier is undefined, I would have expected that analyzer would have produced errors. The API you're using doesn't have any way to report those errors, but you can ask the context for the errors associated with that source and see whether there are any.

Is there a cost to doing that? 99.9% of libraries won't have errors, so if possible I wouldn't want to check for errors just in case after already resolving - does that make sense?

> 
> In the case where the identifier is being resolved even though it shouldn't be, I don't understand why it wouldn't be able to produce a DartObject representing the value of the identifier. Is this a case where it's succeeding in one environment but then failing in another?

I think I miscommunicated - an identifier that can't be resolved is triggering other identifiers that _can_ be not to be resolved either.

**Comment by bwilkerson** [comment]
> Is there a cost to doing that?

Error information is cached so we don't need to re-analyze anything to get the errors. It should be fairly inexpensive.

**Comment by matanlurey** [comment]
Thanks. I'll see what I can do on that end.

**Comment by matanlurey** [comment]
Moved to https://github.com/dart-lang/build/issues/295.
