### ISSUE TITLE
Clone vm-kernel-linux-(debug/release)-x64-be buildbots but for mac

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29785]
This is the follow-up to https://github.com/dart-lang/sdk/issues/29723

**Comment by mkustermann** [comment]
During my gardening shift I've added vm-kernel-mac builders to FYI. Once they are green we can move them over to the main buildbot.

**Comment by aam** [comment]
Thank you Martin!

**Comment by mkustermann** [comment]
Slava made status file updates to it and moved it to the main buildbot. So this should be fixed.
