### ISSUE TITLE
DDC runtime has unnecessary checks

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29789]
Our runtime is largely written in Dart.   In places where we're not careful with types (and some places where we are are) unnecessary runtime checks are creeping in to potentially performance important code.  We should audit the generated code for our runtime and keep an eye on this.  Examples:

- [x] FunctionType._process has a dsend.
- [x] Dart.Typedef has a check on the return of the functionType getter.  This shouldn't be needed at all, and should at most be done once when _functionType is set.
- [x] dart.getFunctionType has a check on args
- [x] _dartSymbol has a check ([CL 2934623003](https://codereview.chromium.org/2934623003/))
- [x] _canonicalMember has a check
- [x] checks and dsends in debugger and formatter code (split out to https://github.com/dart-lang/sdk/issues/29834)
- [x] Lots of checks in JSArray (some may be necessary, but not all)

**Comment by vsmenon** [comment]
Some checks removed:

https://codereview.chromium.org/2927763004/

**Comment by jmesserly** [comment]
_dartSymbol is fixed in https://codereview.chromium.org/2934623003/

**Comment by jmesserly** [comment]
CL out shortly to fix all of these, except debugger stuff which I split out: https://github.com/dart-lang/sdk/issues/29834

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2932043003
