### ISSUE TITLE
DDC shouldn't use analysis_options.yaml to determine errors

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#29792]
In some repos we've started turning some hints into errors to pick up tighter checks in Travis. When running pub server with `--web-compiler=dartdevc` these impact what DDC considers an error, so compilation can fail when it otherwise wouldn't.

For example with a line like [this](https://github.com/dart-lang/source_gen/blob/4462deafefe0ec2057c62f4541b8b932dd735838/analysis_options.yaml#L4) pretty much any Angular project wouldn't be able to use DDC since `.template.dart` files tend to have unused imports.

I think this can be avoided by configuring as `warnings` instead of `errors`, but it probably doesn't make sense for DDC to let this configuration 'leak' into it's behavior.

**Comment by leafpetersen** [comment]
I think this is a dup of https://github.com/dart-lang/sdk/issues/29713, re-open if not.
