### ISSUE TITLE
Null-coalescing operator with a "throw" expression messes with dart2js ineterceptors

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#29790]
Reduced test case (see on Dartpad: https://dartpad.dartlang.org/35b1478eec218cf4275a588ff7e679c8)
```dart
main() {
  var mayBeNull = new DateTime.now().millisecondsSinceEpoch != 1 ? 'foo bar baz' : null;
  var nullCoalescedString = mayBeNull ?? (throw new Error());
  print(nullCoalescedString.runtimeType); // prints 'String'
  print(nullCoalescedString.indexOf('bar')); // prints `null` unexpectedly
}
```

Replacing `(throw new Error())` with other expressions results in correct behavior, with the `indexOf` line printing `4` instead of `null`. Expressions I tried:
* a number literal (this is a strong mode error, so it's not completely relevant)
* a call to a `void` function (this is a strong mode error, so it's not completely relevant)
* a string literal
* `null`

**Comment by greglittlefield-wf** [comment]
Interestingly enough, it also happens in this simplified case... (thanks @georgelesica-wf)
```dart
main() {
  var nullCoalescedString = 'foo bar baz' ?? (throw new Error());
  print(nullCoalescedString.runtimeType); // prints 'String'
  print(nullCoalescedString.indexOf('bar')); // prints `null` unexpectedly
}
```

**Comment by natebosch** [comment]
On DartPad today the second example prints `4` instead of `null` so it looks like this was fixed.
