### ISSUE TITLE
Can we update d8?

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#29794]
Our version of d8 is from 2014. While I take pleasure in working with vintage artisan tools from bygone eras, it means we cannot run DDC tests on it since it is older than most ES 6 features (!).

Is it possible to upgrade to a newer version?

**Comment by whesse** [comment]
Updated linux and windows d8 to 6.1.0 (candidate) in CL https://codereview.chromium.org/2985473002/

We still need to do MacOS, building locally if we can't download one.

**Comment by munificent** [comment]
Thanks!
