### ISSUE TITLE
Deferred dart:js library not work if loadLibrary in the other library

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#29796]
Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"

```
library a;

import 'dialogs.dart' deferred as dialog;

/**
 * Handle offline
 */
Future loadDialogLib(void onReady(_))
=> dialog.loadLibrary().then(onReady)
    .catchError(handleDeferedLoadingError);

void openDialogA() {
  loadDialogLib((_)//works fine
    =>  dialog.DialogA.open());
}
```

```
library b;

import 'a.dart' show loadDialogLib;
import 'dialogs.dart' deferred as dialog;

void openDialogB() {
  loadDialogLib((_)//error
    =>  dialog.DialogB.open());
}
```

```
NoSuchMethodError: No top-level getter 'dialog.DialogB' declared.
Receiver: top-level
Tried calling: dialog.DialogB
```

**Comment by vsmenon** [comment]
I believe this is working as intended.  Each deferred import (i.e., the import, not the target) must be explicitly loaded via `loadLibrary`.  In other words, `dialog` is not available to `b` until `b` imports it.

In general, this allows implementations to aggressively defer parts of `dialog` only used by `b` even if it needs to loads other parts (those used by `a`) earlier.

@floitschG - is this correct?

**Comment by lrhn** [comment]
I agree that this is working as intended.
Each *import* must be loaded individually.
