### ISSUE TITLE
BodyBuilder doesn't handle local function type parameters

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29798]
Consider the following code:

    main() {
      T f<T>(List<T> l) => l[0];
      var x = f([0]);
    }

In strong mode, Fasta generates the following errors:

    pkg/front_end/testcases/inference/foo.dart:9:3: Warning: 'T' isn't a type.
      T f<T>(List<T> l) => l[0];
      ^
    pkg/front_end/testcases/inference/foo.dart:9:15: Warning: 'T' isn't a type.
      T f<T>(List<T> l) => l[0];
                  ^

And generates the following compiled output:

    static method main() → dynamic {
      function f(core::List<invalid-type> l) → invalid-type
        return l.{core::List::[]}(0);
      invalid-type x = f.call(<invalid-type>[0]);
    }

I'm worried that this might be a symptom of a design flaw in the BodyBuilder, because AFAICT it tries to interpret the local function return type (`T`) before it even reaches the type parameter declaration (`<T>`), so it has no way of resolving the former to the latter.

There are similar problems with closures, e.g.:

    main() {
      var x = (<T>(List<T> l) => l[0])([0]);
    }

However with closures the problem is not as worrisome because the type parameter declaration always appears at the beginning of the closure.

**Comment by peter-ahe-google** [comment]
I'm also concerned about this, but I'll find a way to deal with it. Most likely, I'll modify the parser so I can tell that T is a function return type and delay scope lookup.

There's a similar problem for generalized function types.

**Comment by peter-ahe-google** [comment]
With [CL 2985673002](https://codereview.chromium.org/2985673002/) all type variables declarations events are reported before parsing the return type. All that remains is creating the type variables in BodyBuilder similarly to how it is already done for generalized function types.

**Comment by peter-ahe-google** [comment]
We're getting close now.

It turns out that erasure transformer didn't correctly erase the new type variables but that is fixed with [CL 2993993002](https://codereview.chromium.org/2993993002).

There's a number of tests that crash due to error recovery related to named function expressions, but besides that [CL 2993333002](https://codereview.chromium.org/2993333002) is looking good.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 2994973002](https://codereview.chromium.org/2994973002).
