### ISSUE TITLE
dartdevc: Include file dart_stack_trace_mapper.js.map

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29807]
Cross-filed from @chalin on an internal thread:

```
[web]  GET Served 3 cached assets.
[web]  GET Served 3 cached assets.
[web]  GET dart_stack_trace_mapper.js.map → Could not find asset angular_quickstart|web/dart_stack_trace_mapper.js.map.

```

To avoid this 404ing for users and them thinking they are missing files or steps, it would be nice to provide a null/empty file for `dart_stack_trace_mapper.js.map`, and make our user experience a little better.

/cc @jacob314 @vsmenon

**Comment by vsmenon** [comment]
It looks like this file is built.  Does it need to be installed under `dart-sdk`, @jacob314 ?

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk] find xcodebuild/ -name dart_stack_trace_mapper.js.map
xcodebuild//ReleaseX64/dev_compiler/build/web/dart_stack_trace_mapper.js.map
```

**Comment by matanlurey** [comment]
Tiny ping. This seems to have regressed, now I'm missing two `.map` files:

```
Build completed successfully
[web] GET Served 2 cached assets.
[web] GET Served 3 assets.
[web] GET dart_stack_trace_mapper.js.map → Could not find asset shipbuzz_web|web/dart_stack_trace_mapper.js.map.
[web] GET main.dart.bootstrap.js → shipbuzz_web|web/main.dart.bootstrap.js
[web] GET dart_sdk.js → shipbuzz_web|web/dart_sdk.js
[web] GET web__main.js → shipbuzz_web|web/web__main.js
[web] GET dart_sdk.js.map → Could not find asset shipbuzz_web|web/dart_sdk.js.map.
[web] GET web__main.js.map → shipbuzz_web|web/web__main.js.map
[web] GET Served 3 cached assets.
[web] GET Served 2 cached assets.
[web] GET dart_stack_trace_mapper.js.map → Could not find asset shipbuzz_web|web/dart_stack_trace_mapper.js.map.
[web] GET Served 4 cached assets.
[web] GET dart_sdk.js.map → Could not find asset shipbuzz_web|web/dart_sdk.js.map.
```

/cc @jakemac53 in case this is a `pub` issue.

**Comment by jakemac53** [comment]
I don't see either of these files in the shipped sdk (would expect them under `lib/dev_compiler/web`), but pub also isn't set up to serve them even if they did exist.

If I remember correctly the dart sdk sourcemap doesn't work with pub for some reason (but support could be added).

**Comment by unicomp21** [comment]
could we please get some empty files?

**Comment by jakemac53** [comment]
Another option is to make pub not log a big ugly red message on 404's. Not having a sourcemap for a JS file is not an error.

**Comment by matanlurey** [comment]
We no longer use pub serve
