### ISSUE TITLE
dartanalyzer and dartdevc showing inconsistent errors

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29803]
_From @chalin on June 6, 2017 13:3_

Dart2js doesn't report any errors, but when I do `pub build --web-compiler=dartdevc` on the AngularDart doc example [toh-5](https://github.com/angular-examples/toh-5), I get:
```nocode
Building angular_tour_of_heroes...
Building dartdevc modules...
Error compiling dartdevc module:angular_tour_of_heroes|lib/lib__hero_detail_component.template.js
[error] Element 'Location' from SDK library 'dart:html' is implicitly hidden by 'location.dart'. (package:angular_tour_of_heroes/hero_detail_component.template.dart, line 251, col 84)
[error] Element 'Location' from SDK library 'dart:html' is implicitly hidden by 'location.dart'. (package:angular_tour_of_heroes/hero_detail_component.template.dart, line 252, col 54)

Please fix all errors before compiling (warnings are okay).
```
The above is an excerpt from [this Travis build log](https://travis-ci.org/dart-lang/site-webdev/jobs/239936772).

While I expect differences between dart2js and the ddc, this isn't a difference in behavior that I'd expect. Note that running the `dartanalyzer` over toh-5 results in `No issues found!`.

cc @kwalrath @kevmoo @vsmenon

_Copied from original issue: dart-archive/dev_compiler#636_

**Comment by floitschG** [comment]
Shouldn't this be fixed with https://github.com/dart-lang/sdk/issues/29146 ?

**Comment by vsmenon** [comment]
Yes, though I don't that made it into 1.24.

**Comment by vsmenon** [comment]
@chalin `dartanalyzer` should give the same errors if you're running with `--strong`.

**Comment by vsmenon** [comment]
I'll go ahead and close as that error is no longer an error (at least for 1.25).

**Comment by chalin** [comment]
@vsmenon - I don't get that error under 1.24 strong mode:
```nocode
toh-5 > dartanalyzer --version
dartanalyzer version 1.24.0-dev.6.8

toh-5 > dartanalyzer --strong --lints -v .
Analyzing toh-5...
Loaded analysis options from /Users/chalin/git/site-webdev/examples/ng/doc/toh-5/analysis_options.yaml
Analysis options: strong = true
Analysis options: lints = true
No issues found!
```

Bottom line: are you saying that this is a genuine error (i.e., that the ddc is right and that the dart analyzer will be catching up soon?

**Comment by vsmenon** [comment]
No - the opposite.  It was accidental that we made this an error.  Will be downgraded to a warning or hint.

I'm surprised that the analyzer and ddc are out of sync though.  This might be a versioning issue of some sort.

**Comment by vsmenon** [comment]
To be clear, it is an issue of sorts.  `Location` in `location.dart` is shadowing the one in `dart:html`.  But all our tools will pick (and type-check against) the one in `location.dart` over the one in `dart:html`, so it's not a real error - just a Dart resolution rule.

**Comment by vsmenon** [comment]
@chalin - are you running the `dartanalyzer` on the actual package where `dartdevc` is showing the error?  Both use the same `analyzer` code to report errors, but the former (by default) stops at package boundaries I think.

**Comment by vsmenon** [comment]
And, are we sure these are all at the same version?

**Comment by chalin** [comment]
> are you running the dartanalyzer on the actual package where dartdevc is showing the error?

Yes.

> And, are we sure these are all at the same version?

I'm unsure how I could manage to use different versions of pub / ddc / analyzer. Here is a log of the tools run over the same code. I also print out the `--version`:
```nocode
toh-5 > dart --version
Dart VM version: 1.24.0-dev.6.8 (Mon Jun  5 15:26:29 2017) on "macos_x64"

toh-5 > pub --version
Pub 1.24.0-dev.6.8

toh-5 > pub build --web-compiler=dartdevc
Loading source assets... 
Loading angular2/transform/codegen, test/pub_serve and dart_to_js_script_rewriter transformers... (5.5s)
Loading angular2 and angular2/transform/reflection_remover transformers... (4.9s)
Building angular_tour_of_heroes... (1.6s)
Building dartdevc modules... (33.7s)
Error compiling dartdevc module:angular_tour_of_heroes|lib/lib__hero_detail_component.template.js

[error] Element 'Location' from SDK library 'dart:html' is implicitly hidden by 'location.dart'. (package:angular_tour_of_heroes/hero_detail_component.template.dart, line 251, col 84)
[error] Element 'Location' from SDK library 'dart:html' is implicitly hidden by 'location.dart'. (package:angular_tour_of_heroes/hero_detail_component.template.dart, line 252, col 54)

Please fix all errors before compiling (warnings are okay).

Build failed.

toh-5 > pub build --web-compiler=dart2js
Loading source assets... 
Loading angular2/transform/codegen, test/pub_serve and dart_to_js_script_rewriter transformers... 
Loading angular2 and angular2/transform/reflection_remover transformers... (5.8s)
Building angular_tour_of_heroes... (1.0s)
[Info from Dart2JS]:
Compiling angular_tour_of_heroes|web/main.dart...
[Dart2JS on angular_tour_of_heroes|web/main.dart]:
2 warning(s) suppressed in package:angular_tour_of_heroes.
[Info from Dart2JS]:
Took 0:00:14.617546 to compile angular_tour_of_heroes|web/main.dart.
Built 975 files to "build".

toh-5 > dartanalyzer --version
dartanalyzer version 1.24.0-dev.6.8

toh-5 > dartanalyzer --strong --lints -v .
Analyzing toh-5...
Loaded analysis options from /Users/chalin/git/site-webdev/examples/ng/doc/toh-5/analysis_options.yaml
Analysis options: strong = true
Analysis options: lints = true
No issues found!
```

**Comment by kevmoo** [comment]
@chalin – the template code is generated – so it's not visible by dartanalyzer when it's run

**Comment by chalin** [comment]
Yeah, I have to keep in mind that the ddc does a whole program analysis on all generated code + all packages. Anyhow, apparently this particular error (about Location) is a known issue.

**Comment by kevmoo** [comment]
@chalin can we close this one then?

**Comment by kevmoo** [comment]
This is just weirdness due to transformed code. Closing.
