### ISSUE TITLE
compiler/dart2js/analyze_test.dart is broken

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29802]
```
$ python tools/test.py -m release -ax64 --checked --use-sdk --reset-browser-configuration dart2js/analyze_test
...
Malformed output from dartanalyzer:
No dart files found at: /usr/local/google/home/aam/dart-sdk1/sdk/tests/compiler/dart2js/path
Running analyzer took: 0:00:01.120994.

stderr:
Non-empty output from analyzer.

```
culprit seems to be https://github.com/dart-lang/sdk/commit/d935a7fd00f8727ff730dff2a0273999fa7faaa7

**Comment by scheglov** [comment]
I'm going to [revert](https://codereview.chromium.org/2922303002) this change.

@peter-ahe-google But it seems that there was a compilation problem originally.

**Comment by scheglov** [comment]
[Reverted](https://github.com/dart-lang/sdk/commit/433b7904c27dea2dca5f6fa650c99c553d9b5874)

**Comment by peter-ahe-google** [comment]
Thank you, Alex and Konstantin. I'll take a look at this. I think I need to addd a test which analyzes package:testing.
