### ISSUE TITLE
What is the correct way to know whether a library is valid to send a setLibraryDebuggable request for?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#29813]
I'm currently sending `setLibraryDebuggable` request for all libraries in an isolate when my debugger attaches. However, when trying to attach to a Flutter app I got the following error:

> setLibraryDebuggable: illegal 'libraryId' parameter: libraries/@9040228

It seems to be because this libraryId was `dart._internal`:

```js
{
  "type":"@Library",
  "fixedId":true,
  "id":"libraries/@9040228",
  "name":"dart._internal",
  "_vmName":"dart._internal@9040228",
  "uri":"dart:_internal"
}
```

I can exclude this library by name so I never send `setLibraryDebuggable` for it, but I don't know whether there may be others like this in future. What's the convention for libraries that cannot be sent? Will they all start with `dart:_`? Should I exclude anything with a `_vmName`?

**Comment by DanTup** [comment]
For now I'm excluding anything that starts `dart:_` but it'd still be nice to have confirmation if this is a reasonable rule.

**Comment by gatefifty** [comment]
Hi DanTup, where are you getting the libraryId from? I am trying to enable debugging on a library but cant see where this can be accessed?

**Comment by mraleph** [comment]
@bkonyi @rmacnak-google could you provide and answer to this issue (e.g. is this expected to work for private internal libraries - if it is not expected to work then we should mark it as such and close an issue).

**Comment by mraleph** [comment]
Note that this prevents debugging of `dart:_http` implementation - so maybe we should permit it?
