### ISSUE TITLE
Generate .dill file for dart:vmservice_io alone (without platform.dill included)

### ISSUE THREAD

**Issue by sivachandra** [dart-lang/sdk#29818]
Currently, the way to produce the .dill file for dart:vmservice_io is to do this:

./pkg/front_end/tool/fasta compile --compile-sdk=xcodebuild/ReleaseX64/patched_sdk/ dart:vmservice_io -o vmservice_io.dill

However, the produced vmservice_io.dill file has platform.dill included. There should be a way to produce vmservice_io.dill without the platform.dill included.

**Comment by a-siva** [comment]
@sigmundch

**Comment by peter-ahe-google** [comment]
This issue is blocked on the following:

- [ ] Specifying the location of the SDK sources ([CL 2929783002](https://codereview.chromium.org/2929783002/) addresses this).
- [ ] `platform.dill` already includes dart:vmservice_io.
- [ ] We don't yet have a solution for modular compilation.

**Comment by sigmundch** [comment]
@peter-ahe-google what do yo have in mind that we need to do for modular support? In particular, we have modular compilation available via this API: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/kernel_generator.dart#L125, this is not exposed on command-line tools yet, so we need to do that. My plan was to start moving all of our tools away from using fasta.dart and internally calling the fasta APIs, but instead to build them on top of the public APIs in `kernel_generator.dart`.

**Comment by peter-ahe-google** [comment]
@sigmundch that may be all that's needed for modular compilation.

**Comment by sigmundch** [comment]
I believe all the pieces needed for this are implemented now. I'm closing this tentatively, but feel free to reopen this if I missed something.

Note: the `patch_sdk.dart` script is still embedding platform.dill within vmservice_io.dill because of an issue on the vm-side (which we are tracking in #30111).
