### ISSUE TITLE
1.24-dev.6.8: Strange error messages while debugging

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#29811]
Summary:
I'm getting some strange errors when mousing over code while debugging. If this is a a new feature, feel free to disregard everything below this point.

What steps will reproduce the problem?
1. Start a new Dart project with StageXL Web App generated sample content (any of the samples will produce the same issue, but this one doesn't require a breakpoint to avoid termination).
2. Wait for dependencies to be resolved and run index.html in debug mode.
3. Open main.dart and mouse over for example renderLoop (line 17).
4. Observe a ReferenceError

What is the expected output? What do you see instead?
Expected:
Didn't really expect anything to happen

Actual:
Got an error message as seen on the screenshot.
![skaermbillede 2017-06-07 15 55 54](https://user-images.githubusercontent.com/20222678/26882574-0f670b40-4b9b-11e7-978f-adbe6437634e.png)

What version of the product are you using?
Dart/Dartium 1.24-dev.6.8, 1.23 (last stable version for reference)
WebStorm 2017.1.3, 2016.3.6
intelliJ Ult 2017.1.3

On what operating system?
Windows 10(64bit)
macOS Sierra

Please provide any additional information below.

As mentioned before, I don't know if this is intentional, but for a moment I thought I had broken the internet or something.

**Comment by mit-mit** [comment]
Tagging as potential 1.24 issue.

**Comment by mit-mit** [comment]
@devoncarew is this in IJ or somewhere deeper in the platform?

**Comment by alexander-doroshko** [comment]
This is in the Dart plugin, I think you can close it here and file in https://youtrack.jetbrains.com/issues/WEB instead.

**Comment by devoncarew** [comment]
I opened https://youtrack.jetbrains.com/issue/WEB-27221 (and will close this issue).
