### ISSUE TITLE
Confusing hot reload rejection message: "Original class ... is prefinalized and replacement class ... is not"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29816]
I switched branch from a branch that contained the patch in https://github.com/flutter/flutter/pull/10553 to a branch that didn't (or vice versa, maybe?), and I got the following when I hot reloaded:

```dart
Initializing hot reload...                                
Hot reload was rejected:
Original class ('Library:'package:flutter/src/widgets/gesture_detector.dart' Class: GestureRecognizerFactory') is prefinalized and replacement class ('Library:'package:flutter/src/widgets/gesture_detector.dart' Class: GestureRecognizerFactory') is not 
```

That message is hard to read (with its embedded paths and weird capitalisation in the parentheticals) and I have no idea what it means.

**Comment by Hixie** [comment]
cc @rmacnak-google 

FWIW, I think GestureRecognizerFactory was a typedef before the hot reload and became a class afterwards.

**Comment by rmacnak-google** [comment]
It was probably the typedef <-> class as you suggest. The prefinalized property only applies to VM defined classes like String or List (that can't be changed during a reload anyway) or function typedefs.

I'll update the error to be more specific like the enum <-> class restriction.
