### ISSUE TITLE
Document dartdevc errors/warnings (and their remedies)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#29825]
See [this comment](https://github.com/dart-lang/site-webdev/pull/700#discussion_r120690736) in the dartdevc FAQ review.

**Comment by chalin** [comment]
Included in this it would be nice if there was some guidance on how to trace errors back to their source (which may be something of a challenge when the code is generated -- e.g., from the 
AngularDart template compiler).

**Comment by jmesserly** [comment]
I think this is area-documentation? Also these error codes come from Analyzer/CFE (DDC simply displays errors that were produced by the front end)

**Comment by nshahan** [comment]
@kwalrath Is this issue still relevant? I'm happy to keep it open if we still want to address this somehow.

**Comment by kwalrath** [comment]
> @kwalrath Is this issue still relevant? I'm happy to keep it open if we still want to address this somehow.

Nobody seems to be missing this, so I'm fine with closing this issue

**Comment by nshahan** [comment]
Closing this issue because it and the comments are based on the analyzer version of DDC which has been deleted. If there is still confusion with the source of errors please feel free to open a new issue.
