### ISSUE TITLE
Static analysis warning when "is double|int" is found

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29823]
As mentioned internally by @munificent it would be nice to re-enable these checks:

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/resolver.dart#L1923

Perhaps when an `analysis_options.yaml` has "ensure_js_compatibility: true" (or similar).

**Comment by munificent** [comment]
I *think* this was about the warnings we used to (still do?) show around `if (foo is double)` or `if (foo is int)` where the behavior may not do what users expect on the web.

I don't know if those warnings are still shown or not, but whatever the status is, I expect that it's the status we intend it to be. :) Also, long term, I expect that WASM will make this a moot point.
