### ISSUE TITLE
DDC fails on chartjs.dart

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29839]
Repro:

1) Sync https://github.com/firebase/firebase-dart
2) cd firebase-dart

```console
> pub serve example
```

3) `http://localhost:8080/realtime_database/index.html`

See how it works

Next.

```console
> pub serve example --web-compiler dartdevc
```
No compiler errors, but the app doesn't load. Look at the Chrome console.

![screen shot 2017-06-12 at 9 42 17 am](https://user-images.githubusercontent.com/17034/27023597-7f64546e-4f53-11e7-9856-a6af78747584.png)

See https://github.com/firebase/firebase-dart/issues/109

**Comment by kevmoo** [comment]
CC @vsmenon @jacob314 – any thoughts here?

**Comment by vsmenon** [comment]
The currently ignored cast fail is probably because `_JsonMap` is a `Map<String, dynamic>`.

For the other, we'd need more info.  You should be able to set a breakpoint at the point of error (or just have devtools pause on exception).  What is the value of `initializeApp`?

**Comment by kevmoo** [comment]
`initializeApp`  is undefined. The parent object `src__interop__firebase_interop` is just  an empty object.

**Comment by vsmenon** [comment]
Sounds like a module loading problem.  Are you seeing any other errors in the console?  

@jakemac53

**Comment by kevmoo** [comment]
FYI: this CL fixed it https://github.com/firebase/firebase-dart/commit/c1b6c28c1c18c54971b15d11f2b556cb868b6f0a

**Comment by kevmoo** [comment]
So it's clear that dart2js and DDC disagree about what's required – or not – for interop

**Comment by vsmenon** [comment]
Ah, looks like that library is empty except for JS interop symbols:

https://github.com/firebase/firebase-dart/commit/c1b6c28c1c18c54971b15d11f2b556cb868b6f0a#diff-0557e31917d66dacec97729d4c7a880cR22

**Comment by kevmoo** [comment]
It works fine w/ dart2js, though.

**Comment by jakemac53** [comment]
cc @jacob314 who might know more...

**Comment by vsmenon** [comment]
DDC seems to require `JS`.  Dart2JS seems okay with just `external`.  Assigning to @jacob314 to clarify expectation.

@kevmoo - looks like the initial cast error is unrelated - can that be fixed in source?

**Comment by kevmoo** [comment]
Fixed cast error: https://github.com/firebase/firebase-dart/commit/e96bd43625d4ca253f2389ac311c4e197be684c1

**Comment by kevmoo** [comment]
@jacob314 ping?

**Comment by jacob314** [comment]
@jmesserly was recently looking at cleaning up the DDC code generation for js interop.
We should match the dart2js behavior as the meaning of the
external methods is unambiguous.

**Comment by vsmenon** [comment]
We think this is obsolete.
