### ISSUE TITLE
stack_trace performance in DDC

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29831]
We have been seeing performance issues with the stack_trace package in DDC, both in terms of run time and memory. We should investigate what is going on here and see if there are ways to improve it.

IIRC, stack_trace uses some amount of parsing `StackTrace.toString()` so it's possible DDC's traces do not look like what it expects, and that affects optimizations? That's just a guess though.

**Comment by matanlurey** [comment]
I thought that stack_trace was lazy but I could be wrong :)

**Comment by jmesserly** [comment]
It might depend on what features are being used from the package? We were seeing a lot of Zone related things in the stack trace, which reminded me of the async stack trace support (needs to record info every time the Zone schedules an async task). I'm not sure, but it looks like it touches on things that haven't been optimized in DDC (StackTrace, Zones)

**Comment by leafpetersen** [comment]
Just a note on this: profiling some tests to see why they were running slowly, I saw quite a bit of time spent creating stack traces.

**Comment by jmesserly** [comment]
@leafpetersen -- do you know if we're still seeing this?

**Comment by leafpetersen** [comment]
I believe that stack traces are basically opt in at the moment, though Bolt may add its own layer of stack tracing.  I don't think this is a high level issue at the moment, so probably can be closed.
