### ISSUE TITLE
docs for dart:js and dart:js_util

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29833]
We should clarify the docs for `dart:js` and `dart:js_util` to clarify the difference, when you'd use one vs. the other, and the relationship to `package:js`.

@jacob314 @kwalrath

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/5438 where we are planning to document Dart's upcoming JS interop story, as well as https://github.com/dart-lang/sdk/issues/33350 which will properly deprecate these library.
