### ISSUE TITLE
Allow custom location of analysis options files in analysis server

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#29845]
In the Fuchsia tree, options files are not always located in one of the ancestors of a Dart package's directory - this way we can share a common set of options across packages in various projects. It would be nice to have the analysis server configurable so that the right options are picked for a given workspace, just like packages files can.

/cc @devoncarew @bwilkerson

**Comment by bwilkerson** [comment]
Given a directory containing a Dart package, if there is no analysis options file in that directory or any parent directory, where should server look for this file?

**Comment by pylaligand** [comment]
Our build files point to the options files.

I guess the point here is not how we'll find the files, but that a given workspace type should be able to customize the search just like they do for .packages files.

**Comment by devoncarew** [comment]
We have some custom logic for locating flutter analysis options files (/cc @danrubel). I believe that logic is really a one-off solution. I think we would want any configuration to be on disk. The only other option I can think of (cli flags to the analysis server) would likely have a lot of issues.

**Comment by pylaligand** [comment]
Any more ideas for this? I'm working on switching our build analysis to using the server instead of the CLI, but I'm currently unable to point the server to the correct set of options.

**Comment by bwilkerson** [comment]
We can't use command-line arguments to server, it won't work in the case where server is being used in an IDE. So, we need a way to find options files by looking on disk.

I strongly dislike the idea of having different lookup rules based on the kind of workspace the code is in, but that's probably what we effectively have for the Flutter case as well. Sigh.

The cleanest design would be for the normal look-up algorithm to have a fallback: if the options file isn't found in the normal way and if the directory is in a workspace, then ask the workspace for the location of the default options file.

**Comment by pylaligand** [comment]
Another option would be to let package authors to specify options via their pubspec.yaml, e.g. with:
```
options: /path/to/options.file
```

**Comment by bwilkerson** [comment]
Package authors can already do the equivalent by writing an `analysis_options.yaml` file that only contains
```
include: /path/to/options.file
```
Is that sufficient?

**Comment by pylaligand** [comment]
That looks like exactly what I need, will give it a shot.

**Comment by pylaligand** [comment]
This seemed to work, and will also help when looking at our code in IDEs which is great!

The last case which I need to solve is for packages which do not have an explicit set of options; in the Fuchsia build we automatically apply a default set. Would it be reasonable to add an argument to the analysis server to define that default, i.e. the set that gets applied when an appropriate set could not be located? That would not be workspace-dependent at all.

**Comment by bwilkerson** [comment]
The problem with adding arguments to the server is that they then apply to _all_ projects that are opened, whether it's appropriate or not. Having a location in which to search when using a GnWorkspace would at least limit this to projects using that kind of workspace. I believe that we have such a default for BazelWorkspace, so it's not without precedent.

**Comment by pylaligand** [comment]
I think I'll make it so that including an analysis options file is mandatory in the Fuchsia tree. No more changes needed on the server side!
