### ISSUE TITLE
Representing compile-time errors in AST

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29840]
Some clients of Kernel would like to keep as much information about an error as possible, including code that would otherwise be a compile time error.

For example, consider this snippet:

    const x = [];

In this case, Fasta will generate this:

    const x = throw new _CompileTimeError("Not a compile-time constant");

This is a semantic error, and we can easily represent the syntax of the erroneous expression, as it is just a ListLiteral.

For this reason, it would be useful to extend InvalidExpression to include:

1. A throw expression that generates a compile-time error.
2. A JSON string representing the error.

Similar extensions should be added to InvalidInitializer, InvalidStatement, and InvalidType.

Furthermore, errors can occur at other levels, for example in the signature of a Procedure. For this reason, it would be useful to be able to be able to add error information at the following levels:

* Member, for example, error in signature.
* Class, for example, error in hierarchy.
* Library, for example, error in library declarations.

**Comment by kmillikin** [comment]
The first part of this is landed: static errors are represented as InvalidExpression in any context where we can reasonably put an expression.  Still to do:

- [ ] InvalidExpression should represent a source span not a source location
- [ ] Binary files should have a (probably per-library) list of errors and warnings
- [ ] InvalidExpression should have some mechanism of holding an AST node for the purposes of error recovery

**Comment by johnniwinther** [comment]
This is done.
