### ISSUE TITLE
Please merge revision #b3a90540f11b2bc6b96d512b28473b8b5f602dc1

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#29849]
@whesse @mit-mit @kasperl

Dartium running in checked mode will not play sound e.g., pop-pop-win.

Problem is the decodeAudioData is returning a Promise and not a Future which throws an exception in checked mode (VM is more robust problem was in 45 too). Should call convertNativePromiseToDartFuture for Dartium.  The demo pop-pop-win uses the stageXL library and its catching the exception and silently failing.

[Fixed Issue](https://github.com/dart-lang/sdk/issues/29810)

Merge this commit b3a90540f11b2bc6b96d512b28473b8b5f602dc1

This merged cleanly

**Comment by whesse** [comment]
Will wait until this lands in a dev version, and also see if more merge requests come in.  So no action for a few days.

**Comment by jakemac53** [comment]
Fwiw, I will have another merge request soon for two pub + ddc bugs that came up (https://github.com/dart-lang/pub/pull/1637, and https://github.com/dart-lang/pub/pull/1636). One of those is pretty nasty and would definitely be worth a stable release. I expect to have it ready today.

**Comment by terrylucas** [comment]
+whesse

FYI

**Comment by jakemac53** [comment]
Sent out https://github.com/dart-lang/sdk/issues/29858 with my updates

**Comment by whesse** [comment]
Merged in 1.24.1
