### ISSUE TITLE
Code is fine with dartanalyzer, but gives a static error with DDC

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#29857]
See also  https://github.com/dart-lang/intl/issues/135
From package intl

dartanalyzer --strong --show-package-warnings test/number_format_test.dart

shows only two expected deprecation hints. But 

cd ~/<dart-sdk-dir>/pkg/dev_compiler
tool/ddc <path>/intl/test/number_format_test.dart

gives

[error] Couldn't infer type parameter 'T'.

Tried to infer 'dynamic' for 'T' which doesn't work:
  Type parameter 'T' declared to extend 'num'.
The type 'dynamic' was inferred from:
  Parameter 'a' declared as     'T'
                but argument is 'int'.
  Parameter 'b' declared as     'T'
                but argument is **'dynamic'.**

Consider passing explicit type argument(s) to the generic.

 (package:intl/src/intl/date_format_helpers.dart, line 143, col 42)

The error seem plausibles - the code in question is well pre-Dart 1.0. But why doesn't it show up with the analyzer.

@vsmenon suggested maybe DDC is going via a summary path and invoking analyzer isn't. The code is also in the main Intl package, so I'd expect it's being used, including with DDC, all over the place.

**Comment by jakemac53** [comment]
Fwiw, in 1.24 stable this test compiles and runs fine with pub + dartdevc, minus one small tweak. You can patch in https://github.com/jakemac53/intl/commit/1497564b9d36b814c149367837cbef4b679e322c and run `pub serve --web-compiler=dartdevc` followed by `pub run test -p chrome --pub-serve=8080` to run the test.

**Comment by alan-knight** [comment]
@jakemac53  Note - to see this you actually have to be using the old version of intl that's in the SDK. Running with pub serve may not do that.

**Comment by jmesserly** [comment]
fyi, the usual reason for Analyzer CLI to differ from DDC is this bug: https://github.com/dart-lang/sdk/issues/25837
