### ISSUE TITLE
Every object is `null` when using Dartium 50, WebStorm 2017.1.2 on Windows 10

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#29854]
I've seen this behavior on 2 machines. Rolling back Dartium works.

**Comment by zoechi** [comment]
and 2017.1.4 on Mac

**Comment by terrylucas** [comment]
@alexander-doroshko

Can you investigate on the WebStorm side on what you're not getting from Dartium?  For most objects I'm seeing null, scalars (strings, ints, etc. are valid), many dart:html items like button, div seem to appear too.  However, many others are null.

A good simple example to try is from the https://github.com/dart-lang/dart-tutorials-samples
use the anagram sample

Setting a BP on the generateNewLetters(); line in the function:

void newletters(Event e) {
  letterpile.children.clear();
  result.children.clear();
  generateNewLetters();
}

will show both this and e as null?

**Comment by jwren** [comment]
@terrylucas I know before the roll you tested it against IJ, which version and platform works?

Also, is the issue presenting itself in the Webstorm 2017.2 EAP or Ultimate 2017.2 EAP?

FYI: Alex is out on vacation next week.

**Comment by terrylucas** [comment]
Tested to make sure BPs worked (and some variables do display values) however it looks like others do not.  I also tried with 2017.2 EAP and it fails the same way.  In particular, in the anagram example the instance for e displays as null.

**Comment by alexander-doroshko** [comment]
I'm OOO till June, 26. The first step is to see what Dartium sends to the IDE, maybe it is sending nulls instead of real var values. To get these logs click Help -> Find Action, type `Registry`, open it, search for `js.debugger.wip.log` property, set it to some log file path like `/foo/bar/log.json`. This file will be rewritten on each debug session.

**Comment by alexander-doroshko** [comment]
@terrylucas @jwren I compared debug logs and see some difference between Dartium 1.23 and 1.24.1 that I think leads to nulls as var values. I played with the anagram project and a single breakpoint in `void newletters(Event e)`. Note that `this` is expected to be `null`, but `e` - not, it is expected to be `MouseEvent`. IDE sends `"Runtime.getProperties"` request and receives `"handleResult"` event. The difference is that the response from Dartium 1.24.1 includes `"value":null` for the `e` variable, but response from Dartium 1.23 doesn't contain `"value"` attribute at all. See attached screenshot. I'm not an expert in the protocol so can't say for sure whether it is a Dartium fault or IDE incorrectly interprets the response or both. I'll be able to ask colleagues after vacation unless you know the answer.
![image](https://user-images.githubusercontent.com/4499789/27243189-6c771e92-52e9-11e7-816e-5f2740c2ecbf.png)

**Comment by jwren** [comment]
@alexander-doroshko Thanks for looking into the issue.  I am not familiar with the protocol requirements/ expectations either.

**Comment by terrylucas** [comment]
Thanks Alexander I found the same thing.  Its looks like for subtype that
its a new part of the Protocol (whether it should be null I not sure), as
for nested value I'm not sure but I've started debugging it.

**Comment by terrylucas** [comment]
Have a fix for this [CL](https://codereview.chromium.org/2945063002/)

**Comment by terrylucas** [comment]
Released in 1.24.2 stable
