### ISSUE TITLE
vm/cc/ScriptSnapshotsUpdateSubclasses fails on dartk

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#29850]
The test was introduced in a79290cd8efa7b06c84483e7b5e6d874271e3c2b and fails with that revision.

Reproduction: `python tools/test.py -c dartk --builder-tag no_ipv6 --vm-options --no-enable-malloc-hooks vm/cc/ScriptSnapshotsUpdateSubclasses`

**Comment by sivachandra** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/3289dd2bff9fb6be4c537fba4485f4bf63a55e1f.
