### ISSUE TITLE
Provide a way to compile dart:vmservice_io to dill without depending on patched_sdk

### ISSUE THREAD

**Issue by sivachandra** [dart-lang/sdk#29859]
To compile dart:vmservice_io to dill currently, we trick fasta by copying vmservice_io related files over to the patched_sdk and compile as follows:

fasta compile --sdk=patched-sdk/ --platform=patched_sdk/outline.dill dart:vmservice_io

Since vmservice_io is part of the "sdk", fasta is able to resolve the URI dart:vmservice_io and compile it. So potentially, if patched_sdk is gone after https://github.com/dart-lang/sdk/issues/29835 is fixed, this trick will not work. Hence, there should be a different way to compile dart:vmservice_io which does not depend on patched_sdk.

@peter-ahe-google @sigmundch @a-siva

**Comment by sigmundch** [comment]
I think [this comment I just made on your CL][1] relates to this, I'll paste it here just to keep the discussion in a single place:

> It is actually possible to avoid the copying if we set here the location
of vmservice.dart in the source tree instead. This wasn't possible a
couple weeks ago, but now the input to the compiler is a .json file
describining where to find the sources. That .json file is created using
this `locations` map here. Note that to make it work this needs to be a
relative path from the the json file, which is emitted in the
patched_sdk folder (e.g. out/ReleaseX64/patched_sdk/libraries.json) and
there may be small differences depending on the architecture
(win/mac/linux).
>
> Question: do you need to continue using `dart:*` URIs for these
libraries? Or can they be a regular script or a script with a native
extension? If you must use dart:*, then we can skip the copying, if
however it is possible to make them a script, I'd rather move in that
direction.


[1]: https://codereview.chromium.org/2931193002/diff/1/tools/patch_sdk.dart#newcode204

**Comment by sigmundch** [comment]
I realize that there was some implicit context in the CL, so to be more clear:
* I think we can start by not copying the files under patched_sdk and instead generate relative paths to these sources when we build the `libraries.json` file that fasta consumes

* if vmservice continues to be a `dart:*` library, we need to still provide to the front-end the libraries.json that includes a way to resolve it. Even if the rest of the sdk is loaded from `platform.dill`. Right now the file is located based on the `--sdk` flag, but we might want to provide an explicit flag for this file instead.

* eventually it will be nice if we can stop using `dart:*` URIs for this script.

**Comment by sivachandra** [comment]
I tried this (following the first option suggested by @sigmundch):

1. Create a directory vmservice_sdk in the build dir. In there, add a lib/libraries.json with contents:

```
{
  "libraries": {
    "vmservice_io": "../../../../runtime/bin/vmservice/vmservice_io.dart",
    "_vmservice": "../../../../sdk/lib/vmservice/vmservice.dart"
  }
}
```
2. Compile dart:vmservice_io as follows:

```
fasta compile --sdk=vmservice_sdk/ --platform=patched_sdk/outline.dill dart:vmservice_io --packages=../../.packages -o vmservice_io.dill
```

This works, and probably that is all there is for this issue. @a-siva, what do you think? I am not sure if we should go ahead and do this change right away as we want to move to snapshots anyway.

About vmservice_io not being a dart:* library, I am not sure if it is trivially possible to make it such. That it is a special dart:* library is baked into many places. Moreover, it imports dart:_vmservice, which is not possible outside of a dart:* library.

**Comment by sigmundch** [comment]
> About vmservice_io not being a dart:* library, I am not sure if it is trivially possible to make it such. That it is a special dart:* library is baked into many places. 

For me, this is enough reason to try something else - I like the idea of cleaning things up, but if it is too much work, I rather delay it until after we have everything working.

Your suggested approach is interesting: it has the nice effect of restricting the compiler to not resolve any other dart:* library to a file while building the vm-service, so everything else should be already included in the outline.dill.

@peter-ahe-google WDYT?

> Moreover, it imports dart:_vmservice, which is not possible outside of a dart:* library.

Oh I wasn't explicit about this, but I was thinking that we switch both `dart:vmservice_io` and `dart:_vmservice`, so we would not longer have the restriction on importing the library.

**Comment by peter-ahe-google** [comment]
Fasta is designed so it is flexible with respect to how the platform is read, and using libraries.json like @sivachandra suggests is how it is intended to be used.

Personally, I would avoid defining a new platform to implement the vm service, but that's a different discussion.
