### ISSUE TITLE
Please merge revision #b5717a77ae79121b7b97335bcc040bbef9115d8f

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29858]
@whesse @mit-mit @kasperl

This addresses one major issue with the pub + dartdevc integration (modules not adjusting as package structure changes) and a few other minor issues that came up.

Merge this commit b5717a77ae79121b7b97335bcc040bbef9115d8f

This _does not_ merge cleanly due to CHANGELOG.md update, cl is here https://codereview.chromium.org/2930413005 which omits the changelog entries, let me know if I should add the entries into the 1.24 section (but that seems weird to have bug fixes right below the release notes....).

**Comment by whesse** [comment]
We will add a CHANGELOG section for 1.24.1.  Often it just contains the bug references and a brief description, but that change from the CL is certainly small enough to fit there.  Plan to merge this change later today, if everyone agrees we are done with fixing the problems.

**Comment by whesse** [comment]
Merged in 1.24.1
