### ISSUE TITLE
Intl.select does not document that examples should be const

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29864]
The `Intl.message` documentation specifies that the `examples` parameter must be a const literal map.  `Intl.select` has an `examples` parameter which is forwarded to a call to `Intl.message`, but there is no documentation for `Intl.select` that indicates that it must be const.

See also: https://github.com/dart-lang/sdk/issues/29381 .

**Comment by dgrove** [comment]
This should be in the dart-lang/intl repo. Moving to there.

**Comment by dgrove** [comment]
move to https://github.com/dart-lang/intl/issues/140
