### ISSUE TITLE
Dartium incremental build failing

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29868]
There seems to be a build dependency missing, because we have had incremental builds on windows failing with the error:
...\src\out\release\gen\protoc_out\net\quic\proto\cached_network_parameters.pb.cc : fatal error C1083: Cannot open precompiled header file: 'net_quic_proto.precompile.h.pch': No such file or directory

Once this happens, it keeps happening on the builder until a clobber is done (the "out" directory is removed).

So it looks like the dependency of the task that compiles cached_network_parameters.pb.cc on the task that creates net_quic_proto.precompile.h.pch is missing, or the files listed as inputs and outputs are wrong.
Something is wrong in that the file is not created.

Permanent logs:
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdartium-win-ia32-inc-be%2F3087%2F%2B%2Frecipes%2Fsteps%2Fbuild_dartium%2F0%2Fstdout

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdartium-win-ia32-inc-be%2F3086%2F%2B%2Frecipes%2Fsteps%2Fbuild_dartium%2F0%2Fstdout

**Comment by whesse** [comment]
This needs to be fixed, otherwise I have to manually log in to the buildbot every day.

**Comment by whesse** [comment]
This needs to be fixed urgently, it is taking me 15 minutes every day to work around this.

**Comment by terrylucas** [comment]
I'm looking at it Bill.

**Comment by terrylucas** [comment]
Where are the script files that are run when Windows Incremental bots for Dartium.  I'd like to understand why the pre-compiled header is deleted when no changes have happened in either *.cc,*.cpp or *.h

**Comment by whesse** [comment]
The only difference between the incremental and non-incremental builder is that the non-incremental builder runs the command:

    if '-inc-' not in builder_name:
      build_dir = api.path.abspath(api.path['checkout'].join('out'))
      api.file.rmtree('clobber', build_dir)

Unless something is really wrong, everything in the "out" directory is deleted on the non-incremental builder.  And the "out' directory shouldn't be touched in the incremental builder.

All that the incremental builder runs is task_kill, build, and buildbot_steps. The build step is called by:
api.python(
          'build dartium',
          api.path['checkout'].join('dart', 'tools', 'dartium', 'build.py'),
          args=['--mode=Release'])

Aren't these precompiled files in the out directory?  I can't imagine what is deleting them.  Idea: Could the step that regenerates them be in a race condition with the step reading them, so they are being rewritten (and thus deleted) at the point in time they are being read?
Is there a way to make the step that is using them specify them as an input file, and are they listed as an output file for the step that makes them, so just adding the dependency will avoid this?

The script that runs is the recipe https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/dart/dartium.py

and after building, this script calls 
https://github.com/dart-lang/sdk/blob/master/tools/dartium/buildbot_annotated_steps.py

**Comment by whesse** [comment]
Clobber isn't working on that bot.  One workaround would be to make clobber work.  I can do that without much trouble.  If you can't make progress on fixing the build, I'll do that.

**Comment by terrylucas** [comment]
Bill can you do the clobber workaround.

**Comment by whesse** [comment]
Can one of you besides Terry land the recipe change in my CL?  It is
lgtm'd, but nobody landed it.
https://chromium-review.googlesource.com/c/569961/

**Comment by aam** [comment]
We are hitting it today where both [dartium-win-ia32-inc-be](https://uberchromegw.corp.google.com/i/client.dart/builders/dartium-win-ia32-inc-be) and [dartium-win-ia32-be](https://uberchromegw.corp.google.com/i/client.dart/builders/dartium-win-ia32-be) fail with the same error: 
```
FAILED: obj/chrome/browser/ui/webui/browser_ui.version_ui.obj 
ninja -t msvc -e environment.x86 -- "E:\b\depot_tools\win_toolchain\vs2013_files\4087e065abebdca6dbd0caca2910c6718d2ec67f\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\chrome\browser\ui\webui\browser_ui.version_ui.obj.rsp /c ..\..\chrome\browser\ui\webui\version_ui.cc /Foobj\chrome\browser\ui\webui\browser_ui.version_ui.obj /Fdobj\chrome\browser_ui.cc.pdb 
e:\b\build\slave\dtmwinbe\build\src\chrome\browser\ui\webui\version_ui.cc : fatal error C1083: Cannot open precompiled header file: 'browser_ui.precompile.h.pch': No such file or directory
[2/139] STAMP obj\dart\runtime\generate_version_cc_file.actions_depends.stamp
[3/139] ACTION Generating ANGLE Commit ID
ninja: build stopped: subcommand failed.
```

**Comment by whesse** [comment]
I've landed it.
