### ISSUE TITLE
mustCallSuper does not work when used on methods declared in mixins

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#29861]
The following code produces no warnings, even though I'd expect it to warn about `B.foo` not calling super.
```dart
class Mixin {
  @mustCallSuper
  foo() {}
}

class A extends Object with Mixin {}

class B extends A {
  @override
  foo() {}
}
```

**Comment by zoechi** [comment]
related to dart-lang/linter#194
I guess this repo would be the right place for the bug report

**Comment by dgrove** [comment]
@greglittlefield-wf is this when you're running on the VM?

**Comment by greglittlefield-wf** [comment]
@dgrove I believe this issue is specific to the analyzer, and not the runtime.

**Comment by srawlins** [comment]
dartanalyzer 2.9.1 reports on B.foo.

>   hint • This method overrides a method annotated as '@mustCallSuper' in 'Mixin', but doesn't invoke the overridden method. • 29861.dart:11:3 • must_call_super
