### ISSUE TITLE
mustCallSuper warns for non-concrete overrides

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#29860]
I get an error when overriding `mustCallSuper` with a non-concrete override:

```dart
class A {
  @mustCallSuper
  foo() {}
}

class B extends A {
  @override
  foo();
}
```
> info: This method overrides a method annotated as @mustCallSuper in 'A', but does not invoke the overridden method.

I would expect not to get a warning here, since the overridden `foo` can't call super, since it's a declaration and not an implementation.

**Comment by greglittlefield-wf** [comment]
I'm not seeing this Dart 2.4.0, so I think it can be closed!

**Comment by kevmoo** [comment]
Thanks for letting us know!
