### ISSUE TITLE
DDC null initializes optional parameters

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29866]
Optional parameters with no defaults result in generated code like the following:

```
    if (message === void 0) message = null;
```

I believe that we do not distinguish between `undefined` and `null`, so this seems like we should elide the null initialization here.

**Comment by jmesserly** [comment]
yeah, I'm pretty sure this predates our undefined/null distinction. Sending fix out shortly!

**Comment by jmesserly** [comment]
So ... this turns out to be required for semantics :(
```dart
main() {
  Function(int) f = ([x = 123]) => print(x);
  g([x]) => f(x);
  g();
}
```
This makes me worried about our use of `undefined` as `null`. We do seem to be correctly null initializing parameters, variables, and fields. I think `undefined` may have been added for JS interop, but I'm not sure.

**Comment by jmesserly** [comment]
I think we need to close this as ByDesign -- open to other ideas tho!
