### ISSUE TITLE
Dart2js should be strong mode clean

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29867]
Currently, dart2js can't be analyzed in strong mode.

**Comment by peter-ahe-google** [comment]
I couldn't find another bug that tracks this. I've started on this while I'm gardening.

**Comment by peter-ahe-google** [comment]
Chipping away at the problem with [CL 293882300](https://codereview.chromium.org/2938823002/).

**Comment by natebosch** [comment]
It's running in the Dart 2 VM now - must be strong mode clean.
