### ISSUE TITLE
No devtools console output or input in Dartium

### ISSUE THREAD

**Issue by patkujawa-wf** [dart-lang/sdk#29873]
Happened after upgrading to 1.24.0 (via brew). I did a `brew switch 1.23.0` and the console for that version was then also not working. I did a full uninstall and reinstall, and still no console.

![image](https://user-images.githubusercontent.com/6391742/27147618-ad29505e-50fa-11e7-895e-3cc9b2ce43f1.png)

I was launching it via `DART_FLAGS='--checked --load_deferred_eagerly' open /Applications/Chromium.app`, but same issue when opening via `open /Applications/Chromium.app`.

**Comment by dgrove** [comment]
@terrylucas - can you please take a look?

**Comment by daftspaniel** [comment]
Same issue on Linux  Ubuntu MATE 17.04.

**Comment by terrylucas** [comment]
I believe I've narrowed this done to the fact that debuggerModel could come up null in some edge cases causing a fatal error trying to call addEventListener.  Only happened in some obscure cases most pages with just JS seem to work.

See [CL](https://codereview.chromium.org/2941143002/)

**Comment by patkujawa-wf** [comment]
Thank you! Will this be incorporated into the dartium that ships with dart 1.24.0, or do we need to wait for the next version?

**Comment by terrylucas** [comment]
I should make it into the next 1.24 stable -- I'll keep you posted.  Working on one more fix for WebStorm debugging that needs to make it into 1.24 stable.

**Comment by jimmyff** [comment]
Also having this issue since upgrading to 1.24.0 via brew. 1.24.1 doesn't fix.

![screen shot 2017-06-20 at 14 31 23](https://user-images.githubusercontent.com/298850/27381099-6571d6c6-5679-11e7-9288-16f39ef69219.png)

**Comment by terrylucas** [comment]
Released in 1.24.2
