### ISSUE TITLE
Quick fix to create missing overrides should add public libraries instead of privates

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#29872]
Repro
I'm getting quick fixes adding import
```dart
import 'package:flutter/flutter/src/foundation/tree_diagnostics_mixin.dart';
```
instead of 
```dart
import 'package:flutter/foundation.dart';
```

when I define
Library A
```dart
class Foo implements TreeDiagnosticsMixin {
}
```

Library B
```dart
class Bar implements Foo {
}
```
Quick fix to "create missing overrides" imports the src import. If I instead wrote
```dart
class Foo implements TreeDiagnosticsMixin
```
the quick fix to resolve the missing class TreeDiagnosticsMixin will correctly show the import from package:flutter/foundation.dart

**Comment by srawlins** [comment]
I think we strongly prefer public libraries now, but I'm not really sure of the mechanism. I'll close this because this hasn't been touched in ~6 years, but if it's still a problem, please re-open.
