### ISSUE TITLE
Inference failing with ?? operator – in inconsistent ways

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29876]
```dart
void foo(Iterable source) {
  print((source ?? []).toSet());
  //                   ^ no problem
  new List.from((source ?? []).toSet());
  //                           ^ no problem
}

class Platform {
  factory Platform(Iterable<String> uses) =>
      new Platform._((uses ?? []).toSet());
  //                              ^ warning
  // The method 'toSet' isn't defined for the class 'Object' at foo.dart:x:y
  // undefined_method

  Platform._(Set<String> items);
}
```

**Comment by kevmoo** [comment]
Dart VM version: 1.25.0-dev.0.0

**Comment by kevmoo** [comment]
Fun twist if you change it to ```(uses ?? <String>[])``` all is good.

Guessing this is a LUB/GUB thing?

CC @leafpetersen

**Comment by kevmoo** [comment]
Most weird is just that it's inconsistent

**Comment by lrhn** [comment]
Pretty certainly a problem with unifying `Iterable<String>` and `List<dynamic>`. Neither is a subtype of the other, so LUB finds ... something. It doesn't find `Itearble<dynamic>` and it doesn't infer that the list should be `<String>[]` (because unification can work with anything, it doesn't impose any constraints).

**Comment by kevmoo** [comment]
So the bug is the other instances not showing a warning?

From mobile. Sorry for brevity and/or spelling.

**Comment by leafpetersen** [comment]
No actually downwards inference should work for this one.  We push the type from the LHS of `??` into the RHS, and should be using that to infer `List<String>`.

I can't reproduce this on 1.25.0.  Are you sure you have strong mode on?  If I don't turn on strong mode, I get the error you report.

The fact that you're seeing a warning and not an error is also suggestive.

**Comment by bwilkerson** [comment]
@kevmoo Ping.

**Comment by kevmoo** [comment]
Gah. User error. I was mucking w/ `implicit-casts: false` and forgot to copy things over.

😞  sorry...
