### ISSUE TITLE
dartdevc does not work on safari

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#29875]
Dart SDK version: 1.24.0 (Mon Jun 12 08:22:15 2017) on "macos_x64"
Safari version: 10.1.1 (12603.2.4)

Steps to reproduce:

1. Create the starter AngularDart project in WebStorm
2. run `pub serve --web-compiler=dartdevc`
3. open Safari and navigate to localhost:8080
4. observe the app doesn't load.  There is an error in console: `TypeError: null is not an object (evaluating 'lines[0].match(/[<][@](.+):\d+:\d+$/)[1]')` 

Screenshot:

![screen shot 2017-06-14 at 2 15 51 pm](https://user-images.githubusercontent.com/1145719/27155018-04617d72-510c-11e7-8c98-1a7c15630f91.png)

**Comment by dgrove** [comment]
Thanks for the information - the dev compiler isn't expected to work on Safari yet, but we're hoping it will be working there soon.

**Comment by vsmenon** [comment]
This has been fixed:
https://github.com/dart-lang/pub/issues/1631

Not sure if that's going out in a 1.24 or a 1.25 dev release.  @jakemac53 may know.

**Comment by jakemac53** [comment]
I am pretty sure this made it into 1.24.1 and 1.25.0-dev.1.0
