### ISSUE TITLE
Fasta parser should handle "native" declarations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29871]
Currently the Fasta parser doesn't handle "native" declarations.  The way they are supported is that the parser reports an unrecoverable error, and then the listener fixes things up and tells the parser to resume.  This means that if we want to allow "native" declarations when using other listeners, we either need to duplicate the error recovery logic or do some other kind of hack (see for example https://codereview.chromium.org/2939823002/diff/1/pkg/front_end/lib/src/incremental/unlinked_unit.dart#newcode61)

Peter and I discussed this and the fix we are imagining is to add "native" support to the parser, with a corresponding listener event for it.  If we still want to preserve the current behavior (where most listeners generate an error), we might consider making the default implementation of that listener method report an error.

**Comment by jensjoha** [comment]
This is fixed, right? The parser seems to support native:

https://github.com/dart-lang/sdk/blob/0c03458717742f9250911f6d2e92c778dd721b14/pkg/front_end/lib/src/fasta/parser/parser.dart#L3967-L3981
