### ISSUE TITLE
Suggestions on the "Import library" fixes from dart analysis server

### ISSUE THREAD

**Issue by yyoon** [dart-lang/sdk#29877]
(originally filed at Dart-Code/Dart-Code#320)

The "Import library" code fix is useful, but could be improved in a few ways.

* If the import declarations are already sorted, insert the new import in the right place. For now I have to import and then sort as a two step process.
* If the file being imported is in the current package, please consider offering the relative path import as an option.
* Also please consider offering an option to import the desired library with `show Foo` at the end. For instance, we do `import 'dart:convert' show JSON;` a lot in our project.

**Comment by srawlins** [comment]
The first two items are now implemented.

The third is tracked at https://github.com/dart-lang/sdk/issues/32234.
