### ISSUE TITLE
support for unlinked binary format

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29883]
(we've had some several discussions about this, just wanted to file a bug to track it and make sure we are aligned on the plan)

Use cases we want to support:
  * **small script .dill files**: today, to make them valid .dill files they include outlines of the platform libraries, which makes a simple hello-world program as large as 600K. Without outlines it can be as small as 80 bytes.

  * **partial programs for hot reload**: hot reload accepts a partial program for a reload, this partial program shouldn't need to include outlines of the code that the VM already has and didn't change.

  * **avoid "linking" for reload**: the current incremental compiler still needs to link all of the libraries that will be sent to the VM, it however already has generated kernel for each library separately. It would be nice if we could just concatenate the binary format of each library without having to do linking of the canonical names in memory.

Notes: today it appears that partial programs are working in the VM, but they are not supported elsewhere. For example, the package:kernel package doesn't have support for it and will not be able to do a text dump for debugging.

**Comment by jensjoha** [comment]
As you mention, this is already supported in the VM.
Being able to text dump a "partial" dill file to text was added in 3692c0285a5f1422fa70ac4c50e1415c66a3c065.

Are there other missing pieces or can we close this issue?

**Comment by sigmundch** [comment]
Cool that you added support for dumping partial kernel, We can probably delete this script I created earlier that asked you to load the other .dill files in order to do the printing:
https://github.com/dart-lang/sdk/blob/master/pkg/front_end/tool/_fasta/dump_partial.dart

The only missing piece I can think of is to get rid of linking in the future. That was motivated by how the incremental compiler worked, and might no longer be relevant with the leaner minimal IKG we have today.

I'm inclined to close this bug and simply come back to the linking question as a possible optimization if we need it for hot reload in the future.

**Comment by kmillikin** [comment]
I think doing better on this is on our radar for all kinds of reasons, and we don't need to have a specific issue to track it.
