### ISSUE TITLE
Dartanalyzer errors in projects with one contentroot and multiple nested dart projects

### ISSUE THREAD

**Issue by vadimtsushko** [dart-lang/sdk#29889]
I often use specific project layout when I put set of related dart projects into one parent directory. 
In IDE (I use WebStorm) I used to just open this parent directory 

After upgrading to SDK 1.24.0 this stop working for me. `import` statements bacame underscored with red lines, with error message `resource not found`

I've tried some usual remedies: Removed pub cache, have tried stable and dev release of SDK, have updgraded WebStorm from 2017.1.2 to 2017.1.4 - nothing worked out. 
Only the downgrade to SDK 1.23 helped. I'm on Windows 10.

When I raised this question on https://gitter.im/dart-lang/TALK-general István Soós wrote that he had the same experienve with SDK 1.24.0 and IndellyJ IDEA. For him too only downgrade to 1.23.0 worked out.
On https://groups.google.com/a/dartlang.org/forum/#!topic/misc/5UE9MpkG8XM Петър Събев reported same problems with same project layout in InteliJ IDEA

I've found that if instead of opening parent directory I add sibling projects as additional content-roots - errors disappear too. That worked for Петър Събев too

I've tried to reproduce that bug and make test repo https://github.com/vadimtsushko/dir_with_subprojects , but with such small projects (or small set of related projects) it did not reproduce

**Comment by vadimtsushko** [comment]
I opened my project in old way so I can upload snapshot with errors. It looks like dartanalyzer works fine when it run from the dart project directory (in my example on snapshot - I run `C:\ProjecAlt\infovizion_project_root\infovizion\dartanalyzer bin` )
But when I run dartanalyzer from parent dir ( `C:\ProjecAlt\infovizion_project_root\dartanalyzer infovizion\bin` ) I get just the same errors that in WebStorm IDE. Looks like that somehow linked

![image](https://user-images.githubusercontent.com/1159274/27186630-5f415022-5202-11e7-82c1-a1a02ffe4ee3.png)

**Comment by sanmadjack** [comment]
I am experiencing this issue as well. All was well until the 1.24 update, same occurring with 1.24.1.

**Comment by vadimtsushko** [comment]
Update: After a while I started to get these errors in project with multiple content roots too. So my workaround actually does not work for me anymore. I'm switching to SDK 1.23 for now.

**Comment by marcingryska** [comment]
I've encountered the same issue  using WebStorm 2017.1.4. Everything had worked fine untilI upgraded Dart SDK into 1.24.

**Comment by devoncarew** [comment]
@jwren, can you take a look at this one?

**Comment by jwren** [comment]
This issue feels related to https://youtrack.jetbrains.com/issue/WEB-27223, location of .packages files, etc, but it is fixes a known issue, it is not a recent change.

I will talk with @bwilkerson

**Comment by bwilkerson** [comment]
I suspect that this is on the analysis server side, but have not yet had time to investigate to confirm that.

**Comment by jwt-sgg** [comment]
I am having a similar issue. I do not use nested projects as described above, but I do use libraries in local directory packages which are in sibling directories to the main project(s). Everything other than the Analyzer works fine in 1.24.

**Comment by vadimtsushko** [comment]
@jwren For me and three persons who commented here (sanmadjack, marcingryska, jwt-sgg)  plus István Soós at gitter and Петър Събев at dart misc - problems start with upgrade to 1.24.0

I temporarily downgraded to 1.23.0 and this problem disappeared for me.

**Comment by matanlurey** [comment]
I'm also seeing this issue you can reproduce by opening this repository:

https://github.com/dart-lang/build

This worked fine prior to `1.24`.

**Comment by devoncarew** [comment]
As a data-point, I don't see issues when cloning that repo, running pub in the sub-dirs, and running tuneup from the top-level `build/` dir (tuneup is analysis server based).

**Comment by matanlurey** [comment]
iIt might be IDE specific, but I use IntelliJ and it's sad 😢

**Comment by bwilkerson** [comment]
@matanlurey I tried to get more data on this, but need more information.

I started by cloning the `build` repo to my local disk, then I opened the top-level directory in IntelliJ. There were lots of errors, so I ran `pub upgrade` in each of the subdirectories containing `pubspec.yaml` files. All of the errors went away and it appears to be fine.

Are invalid errors the indication that there's a problem, or is there something else that I should be looking for?

FWIW: I'm running the bleeding edge version of the SDK, so it's possible that the problem has been corrected but that the fix didn't make it into the stable/dev release.

**Comment by devoncarew** [comment]
@matanlurey, can you describe your project setup for `build/`? One project, one module, one content root? one project, multiple modules, one content root per module? One project, one module, multiple content roots for that module?

**Comment by matanlurey** [comment]
1. Git clone
2. Open 'build' folder directly `File -> Open`
3. Right click on every pubspec.yaml and run "pub get/upgrade"

At least, this used to work without configuring anything else in IntelliJ

**Comment by bwilkerson** [comment]
I used `File -> New -> Module from Existing Sources...` to open the `build` directory.

Then I tried using `File -> Open` and it still appears to be fine.

I'll ask again: Are invalid errors the indication that there's a problem, or is there something else that I should be looking for?

**Comment by devoncarew** [comment]
I git cloned, ran pub in the subdirs, and opened in IntelliJ (`idea .`) - no more configuration, and I didn't see issues.

**Comment by vadimtsushko** [comment]
In my experience errors start to appear only after i go to some dart file in editor.  Webstorm temporarily shows message like 'resolving paths' in status bar. Then import statements in dart file start to show errors.  Sorry for phone typing

**Comment by bwilkerson** [comment]
I tried opening and even editing files. The only errors I saw were those I introduced while typing.

**Comment by marcingryska** [comment]
@devoncarew  Using WebStorm I have very similar impressions as  @vadimtsushko  that issue firstly appears after opening a particular .dart file in code editor. Since then it's present permanently.  Thus it could be that one doesn't see errors straight after opening IDE or after doing get/upgrade on pubspec.

**Comment by vadimtsushko** [comment]
So I've tried to reproduce it on `build` repo and I have same errors

![image](https://user-images.githubusercontent.com/1159274/27476106-e2bf14f6-5820-11e7-9031-f8e461e5b055.png)


Steps to reproduce: 

 - Install dart v.1.24.1
 - Install IntelliJ IDEA Community Edition  v 217.1.4
 - Add Dart Plugin
 - clone https://github.com/dart-lang/build
 - File -> Open  parent repo directory - `build`
 - Click on `pubspec.yaml` file in `e2e_example`
 - Configure project for Dart
 - Run `Pub: get dependencies` context menu action on `pubspec.yaml` 
 - Open file `e2e_example/tool/build.dart` (So far there are no errors)
 - Try to go to source on `PhaseGroup` - I'm on Windows and do it pressing the Ctrl key and clicking left mouse button on `PhaseGroup()` at line 13
 

After some dart analyzer work there is red lines all over the projects and 1805 errors in the Dart analyzer output

**Comment by bwilkerson** [comment]
I was able to reproduce the described problem, but only within the `e2e_example` directory. If I open any files in other subdirectories I don't see any errors.

The problem is in the `build/analysis_options.yaml`, which contains the following:
```
analyzer:
  ...
  exclude:
    - bazel-*
    - e2e_example/**
```
Because server was told not to analyze this directory it did not create an analysis context for this directory. When these files are opened we attempt to analyze them anyway, but in a context in which we do not know how to resolve any of the `package:` URIs.

@kevmoo When I remove that exclusion everything is analyzed correctly and the errors do not appear. I don't know why this directory is excluded from analysis; it seems like it would be useful to know if changes to the other packages have broken the example.

This is a less than optimal UX, so it would be nice to do something about it, but I doubt that it will happen soon.

The important question is: are the other manifestations of this issue also due to having excluded some portions of code from analysis, or was the `build` package a red-herring.

**Comment by vadimtsushko** [comment]
I forked `build` package to https://github.com/vadimtsushko/build and deleted `- e2e_example/** ` line from `build/analysis_options.yaml`
After cloning that repo I went to `build/too/create_test_all.dart` instead of e2e_example and still got the same errors. ( That is Windows 2008 R2 server with Dart version 1.24.2 )

![image](https://user-images.githubusercontent.com/1159274/27583649-7ede0b14-5b4e-11e7-8548-10db4cfcc48b.png)

In my own project there is no analysis_options.yaml file in the root directory, and analysis_options.yaml files of the individual projects have simplest form: 

```
analyzer:
  strong-mode: true
```

**Comment by bwilkerson** [comment]
Thanks for trying that!

I did the same thing and cannot reproduce it using the bleeding edge version. At this point I'm inclined to believe that the bug has been fixed but not yet released.

**Comment by vadimtsushko** [comment]
Just tried this and with  1.25.0-dev.3.0 with `build` package errors disappear for me.
Will try to swich to bleeding edge on my computer tomorrow and check on my projects

**Comment by vadimtsushko** [comment]
On bleeding edge SDK my internal projects works without errors now.
Thank you

**Comment by bwilkerson** [comment]
I'm glad to hear that it's working for you!

**Comment by xavierhainaux** [comment]
Is it possible to have a fix for this in the 1.24 branch?

We are stuck in 1.23 because of this.
Dart 1.25-dev doesn't have Dartium, we cannot use it right now.

This seems to happen only on Windows with Webstorm. (I think this is when there is an uppercase letter in the path of the project).

**Comment by marcingryska** [comment]
We are also forced to keep 1.23. 
Concering our case, problem exists also on Linux with Webstorm (Ubuntu 16.04 LTS + WebStorm 2017.1.4)

**Comment by vadimtsushko** [comment]
I work on v 1.25 with last available Dartium without apparent problems. I was advised aabout that by @zoechi who use dartium with v1.25 himself.

**Comment by devoncarew** [comment]
> I work on v 1.25 with last available Dartium without apparent problems.

This is what I was going to recommend - the 1.24 Dartium will work with 1.25.
