### ISSUE TITLE
Closure conversion: handle closures in LocalInitializers

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#29887]
Currently closures in LocalInitializers aren't converted. We don't use LocalInitializers extensively now, so a helper transformation may be required to test that.

**Comment by stefantsov** [comment]
Started working on it: https://codereview.chromium.org/2944433002

**Comment by sjindel-google** [comment]
Someone along the way implemented part of it, and I've recently pushed a fix to it: https://codereview.chromium.org/2971293002/

However, the technique that was introduced places context declarations in let-bindings, which are only available to individual initializers, and so is incorrect when the same argument is captured by closures in multiple initializers.

**Comment by sjindel-google** [comment]
Fixed in https://codereview.chromium.org/2981603002/.
