### ISSUE TITLE
Observatory unable to see class allocations in Flutter

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#29880]
In Flutter is not possible to trace the allocations of a class.
The tree always displays the last frame.

![screenshot from 2017-06-14 16 48 42](https://user-images.githubusercontent.com/2686902/27159387-7295d774-5121-11e7-8a05-037e76b2c406.png)

**Comment by rmacnak-google** [comment]
Most likely cause is the stack walker getting stuck.

**Comment by rmacnak-google** [comment]
f80aed850806ccff0308d6f99a47d04789707a80
