### ISSUE TITLE
Constant list/map is modifiable

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29897]
The following does not throw in DDC.

```dart
void main() {
  List<String> list = const [];
  list.add("hello");
  print(list);
}
```

On the VM, it generates:
```
Unhandled exception:
Unsupported operation: Cannot add to an unmodifiable list
```

EDIT(jmesserly): Maps need to be fixed as well

**Comment by jmesserly** [comment]
Maps have the same problem.

For List, I think it works with the `List.unmodifiable constructor`, but we're not marking const lists

I think List.filled is also marking the length fixed (incorrectly). It looked like we can do some cleanup/optimizations to the List constructors in core_patch

**Comment by jmesserly** [comment]
FYI -- I believe lists are fixed now. Maps are not yet.

**Comment by terrylucas** [comment]
The const list tests, checking for immutability, are passing!

language_2/const_objects_are_immutable_test.dart currently fails for const map.  I've marked language_2_dartdevc.status to expect this test to fail and associated the failure with this issue.

**Comment by jmesserly** [comment]
thanks! I'll probably roll in a fix with the Map optimization CL I'm working on
