### ISSUE TITLE
new DateTime throws NPE when year is larger than 275760

### ISSUE THREAD

**Issue by rkj** [dart-lang/sdk#29894]
Example code on DartPad:
https://dartpad.dartlang.org/892f0b17c43c9b80bb5a974359eb544b

**Comment by lrhn** [comment]
This is expected behavior.

The JavaScript `Date` class requires the date to be withing 100_000_000 days of the epoch, which puts the maximal day at 13th of September 275760.
```dart
print(DateTime.utc(275760, 9, 13, 0, 0, 0, 0)); // works
print(DateTime.utc(275760, 9, 13, 0, 0, 0, 1)); // throws
```
For local dates, the limit is the same since the UTC epoch, so the precise hour may differ, but it's roughly the same time.
