### ISSUE TITLE
Access to File.readAsBytes result is slower than expected

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#29892]
Can't provide a small repro atm, but here is my observation:

Data access in this code
```dart
// Load data from file
final bytes = new File('data.bin').readAsBytesSync() as Uint8List;
// Do lots of random access with different aligned typed views (Float32, Uint16)
```
is about 2 times slower than here:
```dart
// Load data from file
final bytes = new Uint8List.fromList(new File('data.bin').readAsBytesSync());
// Do lots of random access with different aligned typed views (Float32, Uint16)
```

Same applies to async version of `File.readAsBytes`.

**Comment by lexaknyazev** [comment]
Observatory shows that about 45% of time is being spent within *Native* (`TypedData_GetFloat32`, `TypedData_GetUint16`) in the first (slow) case. In the second (fast) case, *Native* takes only 10%,

**Comment by floitschG** [comment]
@zanderso, @a-siva  Assigning to `dart:io` for now. Could be a VM perf problem, too.

**Comment by zanderso** [comment]
It's likely that we'll need the full example in order to diagnose this.

**Comment by lexaknyazev** [comment]
Here's the smallest example, that I could isolate. Run each version with `--observe` and compare _Native_ time.

**Slow**
```dart
import 'dart:io';
import 'dart:typed_data';

class Foo {
  Uint8List data;
  Foo(this.data);
}

const kSize = 10 * 1024 * 1024;

void main() {
  new File('tmp.bin').writeAsBytesSync(new Uint8List(kSize));

  final foos = <Foo>[new Foo(null), new Foo(new Uint8List(kSize))];

  for (var foo in foos) {
    if (foo.data == null) {
      final data = new File('tmp.bin').readAsBytesSync() as Uint8List;
      if (data != null) {
        foo.data = data;
      }
    }

    for (var e in new Uint8List.view(foo.data.buffer)) {}
  }
}
```

**Fast**
```dart
import 'dart:io';
import 'dart:typed_data';

class Foo {
  Uint8List data;
  Foo(this.data);
}

const kSize = 10 * 1024 * 1024;

void main() {
  new File('tmp.bin').writeAsBytesSync(new Uint8List(kSize));

  final foos = <Foo>[new Foo(null), new Foo(new Uint8List(kSize))];

  for (var foo in foos) {
    if (foo.data == null) {
      final data = new Uint8List.fromList(new File('tmp.bin').readAsBytesSync());
      if (data != null) {
        foo.data = data;
      }
    }

    for (var e in new Uint8List.view(foo.data.buffer)) {}
  }
}
```

When both elements of `foos` array contain similarly-produced `data` field (i.e., both from `File` or both from `new Uint8List(kSize)`), _Native_ time is alike in both programs.

**Comment by lexaknyazev** [comment]
@zanderso 
> It's likely that we'll need the full example in order to diagnose this.

Example code above has the same unusual _Native_ CPU time share as a real application.
VM shows that the slow version deopts:
```
== Deoptimizing code for 'file:///C:/dart/dev/slow.dart_::_main', frame,
Eager deopt fp=0000008731efe8b0 pc=00000268cdbe50cb
Deoptimizing (reason 4 'CheckClass') at pc=00000268cdbe50cb fp=0000008731efe8b0 'file:///C:/dart/dev/slow.dart_::_main' (count 0)
Deoptimizing 'file:///C:/dart/dev/slow.dart_::_main' (count 0)
  Function: file:///C:/dart/dev/slow.dart_::_main
  Line 15: '    for (var e in new Uint8List.view(foo.buffer)) {}'
  Deopt args: 0
Switching 'dart:typed_data__TypedListIterator@6027147_moveNext' to unoptimized code because guard on field 'Field <_TypedListView@6027147._typedData@6027147>: final' was violated.
Switching 'dart:typed_data__Uint8ArrayView@6027147_[]' to unoptimized code because guard on field 'Field <_TypedListView@6027147._typedData@6027147>: final' was violated.
Switching 'file:///C:/dart/dev/slow.dart_::_main' to unoptimized code because guard on field 'Field <_TypedListView@6027147._typedData@6027147>: final' was violated.
```

**Comment by lexaknyazev** [comment]
@floitschG @zanderso
Have you had a chance to diagnose this yet?

**Comment by mraleph** [comment]
Taking a look

**Comment by mraleph** [comment]
This is a regression originally introduced by `ae8e6705c0e1dd624ec45843879294199c11e368` at least for the microbenchmark case 

In `Uint8ArrayView.operator[]` we have a polymorphic call to `_TypedList._getUint8` with receivers `_Uint8List` and `_ExternalUint8Array`. To reach good performance we need to polymorphically inline it. Those methods are natives and have no Dart bodies, so their inlining is handled by `PolymorphicInliner::TryInlineRecognizedMethod`. 

However in the polymorphic inliner we only reach recognized method inlining if we have a single cid call target: 

```cpp
bool PolymorphicInliner::TryInliningPoly(const TargetInfo& target_info) {
  if ((!FLAG_precompiled_mode ||
       owner_->inliner_->use_speculative_inlining()) &&
      target_info.IsSingleCid() &&
      TryInlineRecognizedMethod(target_info.cid_start, *target_info.target)) {
    owner_->inlined_ = true;
    return true;
  }
  // ...
```

Which means that after `ae8e6705c0e1dd624ec45843879294199c11e368` we no longer inline `_TypedList._getUint8` and friends at polymorphic call-sites - because they are never represented as single-cid call target as all children of `_TypedList` have the same `_getUint8` method. 

@ErikCorryGoogle - please take a look.

**Comment by mraleph** [comment]
When I disable cid range expansion here is what I get (with `const kSize = 10 * 10 * 1024 * 1024`):

```
╭─ ~/src/dart/sdk ‹master›
╰─$ time out/ReleaseX64/dart t/bench-fast.dart
out/ReleaseX64/dart t/bench-fast.dart  0.94s user 0.81s system 102% cpu 1.717 total
╭─ ~/src/dart/sdk ‹master›
╰─$ time out/ReleaseX64/dart t/bench-slow.dart
out/ReleaseX64/dart t/bench-slow.dart  1.17s user 0.69s system 102% cpu 1.811 total
```

**Comment by ErikCorryGoogle** [comment]
Thanks for tracking this down!

I have a suggested fix here: https://codereview.chromium.org/2956653002

**Comment by mraleph** [comment]
@lexaknyazev how much you can share about your full code in which you are using Dart?

I am really interested in assessing if our approach to implementing typed array views scales well for real world use cases.

**Comment by lexaknyazev** [comment]
@mraleph 
The product hasn't been officially released yet, but I can point to the preview repo and datasets.

Source tree (will replace master branch soon): 
https://github.com/KhronosGroup/glTF-Validator/tree/dev

Dataset: 
https://github.com/KhronosGroup/glTF-Sample-Models/

Cmd-line (`cd` to dataset dir, assuming that source snapshot was created from `/bin/gltf_validator.dart`):
```
$ dart gltf_validator.snapshot -r -p -w ./2.0/
```

**Comment by mraleph** [comment]
This issue has been fixed.
