### ISSUE TITLE
pub serve with ddc will stop working when editor temp files get removed

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#29890]
When using an editor that creates temporary files `pub serve` with `dartdevc` get confused and stops working with the error messages:

    Build error:
    Failed to load source asset package|lib/my_temporary_file: ....

and then, for instance

    [web] GET index.dart.js → Could not find asset package|web/.moduleConfig.

You need to restart `pub serve` to make things work again. Using an editor that doesn't create tmp files is a temporary workaround.

**Comment by alexander-doroshko** [comment]
Probably the same problem was with IntelliJ's 'safe write' feature that creates temporary files on save (https://github.com/dart-lang/sdk/issues/29749#issuecomment-305018589).

**Comment by jakemac53** [comment]
Yes that is what I assume - it isn't clear to me how this is actually causing an issue because the dartdevc integration should be ignoring anything that doesn't have a `.dart` extension..... we might just be triggering some sort of general barback bug.

**Comment by jakemac53** [comment]
Ya, my current intuition is that the call to `barback.getAllAssets` is what is actually failing. Previously this would only happen if you did a "pub build", but now it gets called a lot more often (any time after you do a refresh and have made an edit since the last refresh effectively).

**Comment by jakemac53** [comment]
Ok, this actually seems to be a general issue with `pub serve`.

You can repro by running the following whenever using pub serve with transformers:

```
mv lib/some_file.dart lib/some_file.dart_bak ; mv lib/some_file.dart_bak lib/some_file.dart
``` 

You may need to run it a few times but eventually you get a stack trace like this:

```
Build error:
Failed to load source asset angular_components_example|lib/app_component.dart_bak: Could not find asset angular_components_example|lib/app_component.dart_bak.
package:pub/src/barback/pub_package_provider.dart 116:28  PubPackageProvider._assertExists
package:pub/src/barback/pub_package_provider.dart 110:5   PubPackageProvider.getAsset
===== asynchronous gap ===========================
package:barback/src/graph/asset_cascade.dart 146:48       AssetCascade.updateSources.<fn>
dart:async                                                new Future.sync
package:barback/src/graph/asset_cascade.dart 146:15       AssetCascade.updateSources
package:barback/src/graph/package_graph.dart 194:34       PackageGraph.updateSources.<fn>.<fn>
dart:async                                                new Future.sync
package:barback/src/graph/package_graph.dart 280:11       PackageGraph._inErrorZone.<fn>
dart:async                                                runZoned
package:barback/src/graph/package_graph.dart 279:5        PackageGraph._inErrorZone
package:barback/src/graph/package_graph.dart 194:7        PackageGraph.updateSources.<fn>
dart:collection                                           _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach
package:barback/src/graph/package_graph.dart 191:42       PackageGraph.updateSources
package:barback/src/barback.dart 94:14                    Barback.updateSources
package:pub/src/barback/asset_environment.dart 670:17     AssetEnvironment._watchDirectorySources.<fn>
```

**Comment by jakemac53** [comment]
FYI, there is a workaround for intellij users which is to disable the safe write feature.

You can do this by going to file -> settings ->appearance and behavior -> system settings, and then unchecking the `Use "safe write"` box under "Synchronization".

**Comment by jakemac53** [comment]
Also it turns out this isn't an issue for dart2js/dartium in pub serve because they call `getAsset` not `getAllAssets`, and the former can succeed even if the build failed.

**Comment by jakemac53** [comment]
My current strawman proposal to fix this is to just add a slight delay into pub serve before sending updates/deletes to barback. We will collect file updates until there have been non for some duration of time (amount TBD, probably somewhere between 10-100ms, possibly configurable). Once things stabilize then we send all the updates to the barback/dartdevc environments at once.

This generally solves this issue without targeting specific editors, as well as helping with things like "save all" potentially triggering multiple builds.

cc @nex3 @munificent

**Comment by Crazywater** [comment]
I found this thread when I got

`Could not find asset angular2|lib/.moduleConfig.`

when upgrading an older project.

`rm -r .pub` solved it.

**Comment by munificent** [comment]
Adding a delay to batch up a number of writes close in time is reasonable, but I'm not crazy about using that to work around an actual *failure*. I've been down the road of adding arbitrary delays to work around OS problems. It always always always ends in tears and regret.

Can we make `getAllAssets()` resilient to that error like `getAsset()` is?
