### ISSUE TITLE
Zone should offer a way to register to be notified when an uncaught error is detected

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29907]
Suppose you use a library that does not respect Zones (for example, because it throws an error in response to a callback invoked by the VM embedder, or because it explicitly walks up the Zone chain to the root and runs things there).

Currently, exceptions thrown by that library are always reported to the console in an uncatchable manner.

It would be nice if there was a way to register to be notified of such errors so that they could be reported for analytics or sent to an in-process debugging environment or some such.

**Comment by lrhn** [comment]
You can use [`Isolate.current.addErrorListener`](https://api.dartlang.org/stable/1.24.1/dart-isolate/Isolate/addErrorListener.html) to be notified about uncaught errors hitting the root zone.
You probably also want to set uncaught errors to be non-fatal.

(VM embedder callbacks should probably just be bound to the current zone before passing them to the embedder, then they should work. For code deliberately run with `Zone.ROOT.run`, you can't prevent that - but perhaps we should remove `Zone.ROOT` in Dart 2 so code doesn't have a way to escape its current zone - you can't walk the zone chain manually, there is no `Zone.parent` getter).

**Comment by yjbanov** [comment]
> You can use `Isolate.current.addErrorListener`

Nice! I'll give it a try.

**Comment by yjbanov** [comment]
`Isolate.current.addErrorListener` doesn't like my "regular Dart Instance" implementation of `SendPort`:

```dart
void main() {
  Isolate.current.addErrorListener(new ErrorReportingSendPort());
  runApp(new CrashyApp());
}

class ErrorReportingSendPort implements SendPort {
  @override
  void send(dynamic error) {
    print('Isolate.current.addErrorListener caught: $error');
  }
}
```

Result:

```
E/flutter (18057): Unhandled exception:
E/flutter (18057): Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
E/flutter (18057): #0      Isolate._sendOOB (dart:isolate-patch/isolate_patch.dart:512)
E/flutter (18057): #1      Isolate.addErrorListener (dart:isolate-patch/isolate_patch.dart:590)
E/flutter (18057): #2      main (file:///Users/yjbanov/code/flutter/crashy/lib/main.dart:13)
E/flutter (18057): #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
E/flutter (18057): #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by yjbanov** [comment]
After some discussion with @rmacnak-google and @jason-simmons we found one possible workaround for Flutter. Since we have a custom embedder (including a custom event loop) we could capture microtask errors in it and feed the error back to Dart via `Dart_Invoke`. However, this feels a bit hacky. It would be great if we could do this without customizing the embedder.

**Comment by yjbanov** [comment]
Since this is closely related to zones, cc @floitschG

**Comment by lrhn** [comment]
While it would be clever to create your own `SendPort` that doesn't actually send anything, you probably have to use a real `SendPort`. Those can be sent to any isolate, which arbitrary objects cannot.
```dart
var errors = new RawReceivePort((e) { print("Uncaught: ${e[0]}"); });
Isolate.current.addErrorListener(errors.sendPort);
```

**Comment by yjbanov** [comment]
I'm closing this. `Isolate.current` does not work due to Flutter's custom embedder. It works in the standalone VM. We're also fixing our interaction with zones.
