### ISSUE TITLE
Should we use csel for comparisons in the ARM64 backend?

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#29908]
ARM64 has csel instructions which are branchless ways to select between two values. Perhaps we should use those instead of a double branch in ComparisonInstr::EmitNativeCode

We need to try both and see what is faster and/or more compact.  Currently we use branching in ComparisonInstr::EmitNativeCode but we use csel other places.

**Comment by rmacnak-google** [comment]
Somewhat related, we use branching for LoadClassIdMayBeSmi on x64 but conditional moves on arm64. I would expect the same style (probably conditional moves) to be best on both architectures.
