### ISSUE TITLE
DDC fails on ElementList#classes#add

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29901]
This works in Dart2js/Dartium/etc:

```dart
import 'dart:html';

void main() {
  var successMessageDiv = querySelectorAll('.alert-success');
  successMessageDiv.classes.add('hidden'); 
}
```

It does not in DDC, with the error:

```
Type 'JSArray<CssClassSet>' is not a subtype of type 'List<CssClassSetImpl>'
```

**Comment by vsmenon** [comment]
There is a type error in `dart:html` in this constructor:

```
class _MultiElementCssClassSet extends CssClassSetImpl {
  final Iterable<Element> _elementIterable;

  // TODO(sra): Perhaps we should store the DomTokenList instead.
  final List<CssClassSetImpl> _sets;

  factory _MultiElementCssClassSet(Iterable<Element> elements) {
    return new _MultiElementCssClassSet._(
        elements, elements.map((Element e) => e.classes).toList());
  }
  ...
}
```

The `elements.map((Element e) => e.classes).toList()` returns a `List<CssClassSet>`.  `List<CssClassSetImpl>` is expected.

If that `Impl` is correct / wanted, should change to: 
`new List<CssClassSetImpl>.from(elements.map((Element e) => e.classes)`

**Comment by vsmenon** [comment]
@terrylucas

**Comment by terrylucas** [comment]
@rakudrama
 
This is not something that changed in the 50 roll.  However, it's certainly easy enough to change  (darttemplate), my only concern is if there's any dart2js perf issue between "from" and "toList" I suspect they perform the same.  Might want to wait for Stephen to return he has a bunch of special case code in CSS that might have JS implications?  Plus I'd like to test a change like this immediately to see if anything degrades again wait for SRA.

**Comment by terrylucas** [comment]
Is this a blocker that needs to be changed before SRA returns?  If so, we can track the perf issue when SRA is back.

**Comment by terrylucas** [comment]
Looks like I can quickly find out if it tanks anything in dart2js.  So I'm okay making the change.  I assume you need this fixed soon?

**Comment by vsmenon** [comment]
Here's another repro:

```
import 'dart:html';

void foo(ElementList list) {
  list.classes.add('foo');
}

void main() {
  foo(document.querySelectorAll('body'));
}
```

@grouma is hitting on an internal app.

**Comment by vsmenon** [comment]
@terrylucas - can you take a look?

**Comment by terrylucas** [comment]
Ready for review CL https://dart-review.googlesource.com/c/sdk/+/59340
