### ISSUE TITLE
Dart VM Kernel: Support new compile-time errors for initialization clashes

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#29900]
This is the vm kernel specific issue for #29656, which has the details. The vm kernel needs to make it a compile-time error to have these initialization conflicts.

**Comment by a-siva** [comment]
bkonyi@ Why does this have the 1.25 milestone tag, I presume the issue is kernel specific right?

**Comment by bkonyi** [comment]
@a-siva, yes this particular bug is kernel specific. The other related issues were also labeled with the 1.25 milestone so I just tagged this as well. I'm guessing it shouldn't be?

**Comment by jensjoha** [comment]
The example provided in 29656 gives an error when compiling with fasta and `--strong` (though only a warning without the `strong`).
Can we close this issue?
