### ISSUE TITLE
DDC breaks when mixin has named factory constructor

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#29902]
Reduced test case
```dart
abstract class Mixin {
  factory Mixin.named() => null;
}

class Class extends Object with Mixin {}
```

Error:

> $ dartdevc -o o.js test.dart
> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!
>     dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/1.24.1/libexec -o o.js test.dart
>     dart --version: 1.24.1 (Wed Jun 14 07:48:25 2017) on "macos_x64"
> ```
> NoSuchMethodError: The getter 'isSynthetic' was called on null.
> Receiver: null
> Tried calling: isSynthetic
> #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
> #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
> #2      CodeGenerator._hasUnnamedConstructor (package:dev_compiler/src/compiler/code_generator.dart:2255)
> #3      CodeGenerator._hasUnnamedSuperConstructor (package:dev_compiler/src/compiler/code_generator.dart:2248)
> #4      CodeGenerator._superConstructorCall (package:dev_compiler/src/compiler/code_generator.dart:2234)
> #5      CodeGenerator._emitImplicitConstructor (package:dev_compiler/src/compiler/code_generator.dart:2061)
> #6      CodeGenerator._emitClassMethods (package:dev_compiler/src/compiler/code_generator.dart:1486)
> #7      CodeGenerator.visitClassDeclaration (package:dev_compiler/src/compiler/code_generator.dart:949)
> #8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
> #9      CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
> #10     CodeGenerator._emitTypeDeclaration (package:dev_compiler/src/compiler/code_generator.dart:541)
> #11     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/compiler/code_generator.dart:612)
> #12     List.forEach (dart:core-patch/array.dart:73)
> #13     CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:348)
> #14     CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:232)
> #15     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:222)
> #16     _compile (package:dev_compiler/src/compiler/command.dart:186)
> #17     compile (package:dev_compiler/src/compiler/command.dart:60)
> #18     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:53)
> <asynchronous suspension>
> #19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
> #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
> 
> ```

**Comment by jmesserly** [comment]
This has been fixed.
