### ISSUE TITLE
How do you @deprecate without a library element?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29927]
For example, assume `package:foo/bar.dart`:

```dart
@deprecated
library foo.bar;
```

What is the ... equivalent, without a library declaration?

**Comment by lrhn** [comment]
There is no way to annotate the library without having a declaration for it.
That's slightly annoying, but it happens so rarely that it's not really an issue.

I know the DartDoc tool assumes that a doc-comment preceeding the first import is a library comment if there is no library declartion. I don't know if anyone does the same with annotations. It's not strictly correct, but it might be useful.

**Comment by bwilkerson** [comment]
Given that users rarely want to document directives, always associating the first doc comment with the library seemed like a reasonable choice. But it isn't clear that users don't and won't want to have annotations on directives. We could potentially special case `@deprecated`, but I'd prefer not to (unless we do something like add a `@Target('library')` annotation for annotations :-).

**Comment by zoechi** [comment]
@bwilkerson I think it's easier to just add a library declaration instead.
Or do you plan to get rid of `library` entirely?

**Comment by lrhn** [comment]
There are no current plans to remove the library declaration at the current time.
Having a place to put documentation and annotations is one reason for keeping it.

**Comment by a14n** [comment]
What if we were allowed to omit library name?

```dart
@deprecated
library;
```

**Comment by lrhn** [comment]
I have no personal problem with that, bit it's a very low-priority change since you can just write `@deprecated library deprecated_library_foo;`.

**Comment by bwilkerson** [comment]
@matanlurey Has your question been answered? (Should we close this issue?)

**Comment by matanlurey** [comment]
I don't like the answer, but yes. It feels like we made a change to the specification without thinking about how it would impact tooling. I like @a14n's suggestion as a way to somewhat recover, though.
