### ISSUE TITLE
Change @Deprecated(arg) to be useful or remove

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29928]
Right now the contract is as such where "arg" is supposed to be a date. I see almost no places, ever, where this is actually used - either a string (description) is entered, or a version number. Can we either `@deprecate` `@Deprecated()` _or_ change the description to make it more clear what we expect?

**Comment by lrhn** [comment]
The current documentation says:
>This can be specified, for example, as a date, as a release number, or as relative to some other change (like "when bug 4418 is fixed").
I don't see how it supposes a date, it explicitly allows a description or a version number.

**Comment by floitschG** [comment]
The documentation looks up to date.
