### ISSUE TITLE
Test of dwarf stack traces not run on buildbot

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#29948]
The test tests/standalone/dwarf_stack_trace_test.dart depends on dwarf stack traces and thus is not run when testing with --use-blobs. There is currently no configuration on the buildbot in which this test runs.

The test broke in commit 2dcd56ef435630c7a776508f312310e7fa8a7e88, since the code formatting performed in that commit violated the "Keep the 'throw' and its argument on separate lines." comment on line 11, messing up the specific line numbers that the test depends on.

**Comment by askeksa-google** [comment]
@whesse

**Comment by whesse** [comment]
Is there a configuration you would like to add to the buildbot?  On an existing builder (column), or as a new builder?

**Comment by askeksa-google** [comment]
@rmacnak-google do you know if there are other tests depending on not being run with --use-blobs, or is it just this one?

**Comment by rmacnak-google** [comment]
That should be the only test that requires running from a shared library. I thought that we had a least one AOT bot that was still configured to use shared libraries, but it seems we don't. Send a CL to adjust the Linux x64 bots.

**Comment by jensjoha** [comment]
Something at least changed. It failed. I updated the test (https://codereview.chromium.org/2945273002/)

**Comment by rmacnak-google** [comment]
It failed because I changed two of the bots to run with shared libraries instead of blobs.

**Comment by jensjoha** [comment]
So. "Test of dwarf stack traces not run on buildbot" => it is now. Can we close?
