### ISSUE TITLE
VM freezes / generic type syntax

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/sdk#29949]
Report from @spebbe. 

The pattern below --- which is being used as a workaround for restrictions around mixin inheritance in dart2js --- types and runs as expected (?) when abusing the “commented” type syntax, but freezes on the latest dart vm when using normal syntax. dart2js generates good code for both variants. 

```dart
abstract class Flab {
}

abstract class Florbable<F, A> {
  F get florb;
}

abstract class Flirbable<F, A> implements Florbable<F, A> {
  F get flirb => florb;
}

// Works: class Florb<A, B> extends Flab with Florbable<Florb/*<A, dynamic>*/, B>, Flirbable<Florb/*<A, dynamic>*/, B> {
class Florb<A, B> extends Flab with Florbable<Florb<A, dynamic>, B>, Flirbable<Florb<A, dynamic>, B> {
  @override Florb<A, dynamic> get florb => this;
}

main() {
  print(new Florb<int, String>().flirb);
}
```

**Comment by a-siva** [comment]
We seem to get into a deep recursion, not sure why the trail is not working.

#0  0x0000000000b9cf8d in TypeAt (this=0x18efa96f0, index=<optimized out>)
    at ../../runtime/vm/object.cc:4827
#1  dart::TypeArguments::IsSubvectorEquivalent (this=0x18efa9710, other=..., 
    from_index=5, len=2, trail=0x0) at ../../runtime/vm/object.cc:4707
#2  0x00000000008a5c66 in dart::ClassFinalizer::CheckRecursiveType (cls=..., 
    type=..., pending_types=<optimized out>)
    at ../../runtime/vm/class_finalizer.cc:694
#3  0x00000000008a72b6 in dart::ClassFinalizer::FinalizeTypeArguments (
    cls=..., arguments=..., num_uninitialized_arguments=4, 
    bound_error=0x3b8a980, pending_types=0x39c1b78, instantiation_trail=0x0)
    at ../../runtime/vm/class_finalizer.cc:971
#4  0x00000000008a747c in dart::ClassFinalizer::FinalizeTypeArguments (
    cls=..., arguments=..., num_uninitialized_arguments=4, 
    bound_error=0x3b8a980, pending_types=0x39c1b78, instantiation_trail=0x0)
    at ../../runtime/vm/class_finalizer.cc:981
#5  0x00000000008a747c in dart::ClassFinalizer::FinalizeTypeArguments (
    cls=..., arguments=..., num_uninitialized_arguments=4, 
    bound_error=0x3b8a980, pending_types=0x39c1b78, instantiation_trail=0x0)
    at ../../runtime/vm/class_finalizer.cc:981
#6  0x00000000008a747c in dart::ClassFinalizer::FinalizeTypeArguments (
    cls=..., arguments=..., num_uninitialized_arguments=4, 
    bound_error=0x3b8a980, pending_types=0x39c1b78, instantiation_trail=0x0)
    at ../../runtime/vm/class_finalizer.cc:981

**Comment by crelier** [comment]
Reduced to this test case:

```
abstract class S { }
abstract class M<T> { }
abstract class N<T> { }
class C<T> extends S with M<C<T>>, N<C<T>> { }
main() {
  new C<int>();
}
```
The problem is indeed with the instantiation trail that should not be interrupted, as wrongly indicated in the comment. CL on its way.
