### ISSUE TITLE
Pub build/serve: allow common module type with DDC

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/sdk#29953]
This is a follow up to my question in Gitter channel.

I'm working on [node_interop](https://github.com/pulyaevskiy/node-interop) and [firebase_functions_interop](https://github.com/pulyaevskiy/firebase-functions-interop) libraries which allow compiling and using Dart apps in Node environment.

Currently compilation is done by `pub build` using `dart2js` and is working well. With introduction of DDC in Pub I'm exploring ways of leveraging it for building Node apps and enabling better workflow.

Main limitation, as I understand it, is that Pub only allows compiling to AMD/requirejs modules, while node uses `common` module type.

As far as I know DDC itself supports common modules so the issue is more about adding a new option to pub build/serve.

There are quite a few use cases where allowing Dart-to-Node workflow can be very beneficial:

* Building mobile apps with Flutter and Firebase. Flutter already exposes Firebase functionality, however Firebase Functions are Node-only at this point which introduces two different developer environments. Enabling Dart-made cloud functions would allow code-sharing and coherent workflow for developers.
* Building Node-based integrations like Dart plugins for Atom and VSCode. VSCode is currently written in TypeScript (cc @DanTup )
* AWS Lambda runs on Node so it should be possible to write an interop library for Dart as well.

As much is I would like to use DartVM instead of Node, the reality right now is different and Node is ubiquitous.
Having simple and efficient Dart-to-Node-workflow would be a good reason for developers of different backgrounds to try out Dart as well.

Extra item for this (or follow up) discussion: adding new `node` platform to `pub run test` so that running tests can be as simple as `pub run test -p node`.

Below, Firebase Realtime Database Function from the tutorial `makeUppercase` written in Dart in action:

![kapture 2017-06-20 at 10 38 22](https://user-images.githubusercontent.com/441756/27348015-79b5cb88-55a7-11e7-8ded-7da27d3b0f91.gif)

**Comment by jakemac53** [comment]
cc @vsmenon @kevmoo

**Comment by pulyaevskiy** [comment]
To clarify a bit: this is not necessarily a blocker for a Dart-to-Node workflow, as you can see I managed to get Firebase Functions working with new JS interop. 

I'm trying to understand the extent of how it can make the workflow more efficient and friendly.

Right now I have a transformer to prepend node preamble to the output of dart2js and the way I run tests is basically:

```bash
pub build node_test/ # I separate Node-integration tests in it's own folder
node build/node_test/some_test_file_test.dart.js # multiplied by the number of test files
```

There is not much documentation on DDC so I'm looking for some help to understand how we can improve in this area and if DDC can help.

I also assume DDC is still not advisable for the "release" mode because it lacks such things like tree-shaking.

**Comment by srawlins** [comment]
Neither `pub serve` nor `pub build` are valid commands any more. This bug is obsolete.

```none
$ pub serve
Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2

$ pub build
Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2

$ pub --version
Pub 2.0.0-dev.63.0
```
