### ISSUE TITLE
Please merge revision #97d188418a3160f8d3734583cce707bfdc827f47 into 1.24.1 stable

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#29950]
@whesse @mit-mit @kasperl
1.24.1 MergeToStable

<Describe the problem this merge is fixing - include issue numbers if applicable>
This fixes to commits made to WebKit by updating the DEPS that pulls in the changes:

- Fix DevConsole crash with JS.  Issue https://github.com/dart-lang/sdk/issues/29873
      See [CL](https://codereview.chromium.org/2941143002)
- Fix debugging in WebStorm, NULL returned for JS objects. Issue https://github.com/dart-lang/sdk/issues/29854
      See [CL](https://codereview.chromium.org/2945063002)

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
97d188418a3160f8d3734583cce707bfdc827f47

This did not merged cleanly here's the merged DEPS https://codereview.chromium.org/2946043002

**Comment by whesse** [comment]
This is merged in 1.24.2
