### ISSUE TITLE
some numbers in service protocol results are encoded in hex

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29958]
Similar to https://github.com/dart-lang/sdk/issues/29957, the results from `_getCpuProfile` contain a `codes` field with a list of maps. One of the fields is `ticks`, which believe should be a list of integers. Instead, they are encoded as strings, and some value look to be using ~a hexadecimal encoding (`100a1d530`); I believe only decimal is supported in json.

```json
{
  "kind":"Native",
  "inclusiveTicks":"5",
  "exclusiveTicks":"5",
  "code":{"type":"@Code","kind":"Native","name":"dart::TextBuffer::EscapeAndAddCodeUnit(unsigned int)","_optimized":false,"start":"100a1d530","end":"100a1da07","function":{"type":"@Function","name":"dart::TextBuffer::EscapeAndAddCodeUnit(unsigned int)","_kind":"Native"}},
  "ticks":["100a1d530","1","1","100a1d541","1","1","100a1d961","1","1","100a1d9f1","2","2"]
}
```
@a-siva, @sivachandra, @B3rn475

**Comment by rmacnak-google** [comment]
The hex numbers are pc values. These are intentionally encoded as strings because they may overflow JS numbers, which would produce bogus merging when displaying the profile.
