### ISSUE TITLE
dart2js createInvocationMirror included in part instead of main JS output

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/sdk#29969]
In attempting to implement a feature in a large application, I ran into a strange RTE when running the dart2js output. For context, the change I made was comprised of the following:

- Pulling in a new version of a library that includes a new transformer that looks for classes with a certain annotation and inserts/augments a method.
- Leveraging this transformer by annotating certain classes.

In other words, the only change to the source code was an additional annotation on a few classes and the result of the transformer, which was minimal (just a method that nulls-out fields on the class; if you'd like you can see the full transformer implementation here: https://github.com/Workiva/w_common/pull/34).

Annotating certain classes worked as expected, whereas annotating other classes resulted in the following RTE:

```
js_helper.dart:1739 Uncaught Error: NoSuchMethodError: method not found: 'createInvocationMirror' (H.createInvocationMirror is not a function)
    at _$SessionExpirationPropsImpl.call$0 (main.dart.js:117378)
    at session_module.dart:274
    at _wrapJsFunctionForAsync_closure.$protected (async_patch.dart:202)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (async_patch.dart:226)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (async_patch.dart:176)
    at _RootZone.dart._RootZone.runUnary$2.func [as runUnary$2] (zone.dart:1371)
    at _FutureListener.handleValue$1 (future_impl.dart:129)
    at _Future__propagateToListeners_handleValueCallback.call$0 (future_impl.dart:631)
    at Object._Future__propagateToListeners (future_impl.dart:660)
    at _Future._complete$1 (future_impl.dart:464)
```

I originally thought it was an issue with the `_$SessionExpirationPropsImpl` which is a class that gets generated by a (different) transformer, but after inspecting the transformed and built outputs, everything looked as expected. Additionally, the code path from this stack trace was completely unrelated to the changes I had made, which made me more confident that it wasn't the changed source code that was causing this exception – at least not directly.

I also noticed a pattern that when I annotated classes that were not deferred loaded, it worked fine, but when I annotated classes that were behind a deferred import (and thus were included in a part and not the main bundle), it failed.

In comparing the outputs of `pub build --mode=debug` with and without the offending annotation, I discovered that the `createInvocationMirror` definition (which I believe is provided by dart2js) was being moved from the main JS bundle to one of the many parts.

> Here is what that definition looks like:
>
> ```js
>   createInvocationMirror: function($name, internalName, kind, $arguments, argumentNames) {
>     return new H.JSInvocationMirror($name, internalName, kind, $arguments, argumentNames, null);
>   },
> ```

When that definition gets moved to a part, any usage of `createInvocationMirror` will obviously fail until that part is loaded.

I tried to come up with a reduced test case, but didn't have any luck. I'm not at all familiar with the inner workings of dart2js or the logic that determines how the resulting code is divided into parts. I'm hoping that with the above context, someone more familiar with these pieces might have an idea as to what is going on here.

**Comment by sigmundch** [comment]
@evanweible-wf sorry it has taken us a while to take a look.

When we divide code into deferred libraries, we are tracing what's being used and try to assign code to different output units based on the usage patterns. It is possible that the tracing has a bug and missed to track uses of createInvocationMirror.

These uses are a bit implicit when we generate a `noSuchMethod` call. This can be when you explicitly use `noSuchMethod` on when you call certain methods that we know are not there (e.g. super.notExistingMethod`. It is possible that we are tracking some but not all of these uses.

I was just able to create a small repro as follows:
```dart
import 'lib.dart' deferred as l;

main() {
  new Y().m();

  l.loadLibrary().then((_) { new l.A().f(); });
}

class Y { noSuchMethod(i) => print('$i'); }
```

lib.dart:
```dart
class A extends B {
  f() => super.f();
}
class B {}
```

It appears we noticed the use from `super.f`, but didn't notice the use from `Y.m`, and end up putting `createInvocationMirror` in the deferred library.



Until we have a fix for this in our compiler, you might be able to workaround it by adding in your main program some code that will make us notice this use of noSuchMethod, for instance:
```dart
main() {
  ...
  // workaround for this bug:
  try { new _Workaround().foo(); } catch (e) {}
}

class _Workaround { foo() => super.foo(); }
```

Hope this helps!

**Comment by evanweible-wf** [comment]
Thanks for the insight and workaround @sigmundch!

**Comment by joshualitt** [comment]
Closing this bug due to the work around and the fact that mirrors is no longer supported on web.

**Comment by sigmundch** [comment]
Quick clarification note: `createInvocationMirror` is still supported as part of the language. The term mirror was used because it is a reflective-like feature (noSuchMethod receives a descriptor of the invocation, which is very reflective in nature), but it is not coupled with the `dart:mirrors` API (the piece we don't support).

That said, I would be surprised if this bug is still an issue. Since Dart 2 we have much tighter rules about how noSuchMethod is used, and since the use of the CFE the compiler has a more precise model of noSuchMethod than it did when this was first filed. Just as an example, the repro above will report several compile-time errors if it's not modified first.
