### ISSUE TITLE
Analysis Server does not pick up regenerated part file in lib directory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29968]
Repro (in IntelliJ)

* Setup: `lib/main.dart` & `lib/main.g.dart` – where `main.g.dart` is a `part of` `main.dart`.
* Delete `main.g.dart`.

Result: see analyzer warnings as expected.

* Undelete/recreate `main.g.dart`

Expected: analyzer warnings go away
Actual: warnings remain.

Workaround: restart analysis server.

SDK: 1.25.0-dev.2.0 (saw it in dev.1.0 too – not sure if it's a regression)

Fun note: doing this in the bin directory acts as expected 🤷‍♂️

**Comment by bwilkerson** [comment]
@scheglov I saw something similar, but mine was inside the lib directory. It wasn't a generated file, but I referenced a file that I had not yet created and got the expected error. When I created the file by hand (by pasting it from somewhere else) the error remained. Is there state somewhere that isn't getting updated when a file is created?

**Comment by scheglov** [comment]
https://codereview.chromium.org/2959903005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/166c47d771e515a978c3f587056d0f856ceff8cd
