### ISSUE TITLE
WebGL co19 tests flaky on dart2js Linux bots

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#29961]
I'm seeing a number of flakes in WebGL related tests on the dart2js Linux bots. e.g. co19/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01 in https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-chromeff-1-4-be/builds/5335/steps/dart2js-chrome-co19%20tests/logs/stdio
or
co19/LayoutTests/fast/canvas/webgl/tex-image-and-sub-image-2d-with-image-data-rgba5551_t01 in https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-chromeff-2-4-be/builds/4957/steps/dart2js-chrome-co19-fast-startup%20tests/logs/stdio

These tests don't seem to be suppressed there, but I don't see how they should ever be passing at all if there's no ability to do WebGL on those machines.
@whesse @terrylucas

**Comment by karlklose** [comment]
`co19/LayoutTests/fast/canvas/webgl/tex-image-and-sub-image-2d-with-image-data-rgba5551_t01` still fails sometimes on the `dart2js-linux-chromeff-2-4-be` bot, and so do
`co19/LayoutTests/fast/canvas/webgl/tex-image-and-sub-image-2d-with-image-data-rgb565_t01` and
`co19/LayoutTests/fast/canvas/webgl/texImage2DImageDataTest_t01`

**Comment by whesse** [comment]
These tests are running in the xvfb virtual X client.  xvfb supports GL, so webGL works on these browsers.

**Comment by jensjoha** [comment]
More of these failures:

https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-chromeff-4-4-be/builds/5440/steps/dart2js-chrome-co19%20tests/logs/stdio

Interesting lines from the log:
```
              value: Exception: Expect.fail('Unable to fetch WebGL rendering context for Canvas')
                    Stack: Expect.fail('Unable to fetch WebGL rendering context for Canvas')

[...]

BrowserOutput.stderr:
  [1:5:0810/221328.731677:ERROR:video_layer_impl.cc(329)] Not implemented reached in virtual void cc::VideoLayerImpl::AppendQuads(cc::RenderPass *, cc::AppendQuadsData *)
```

**Comment by athomas** [comment]
My plan is to resolve this by implementing Step 1 in https://docs.google.com/document/d/1SmJjRsd9eXeaUMM8s9XKKywSOTN8UqAEQ2qWXgzf33Q/edit#

**Comment by athomas** [comment]
We will instead remove the LayoutTests.
