### ISSUE TITLE
No mechanism to tell generate_patched_sdk what custom host toolchain to use

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29966]
Dart //runtime/vm:patched_sdk rule has to run with adjusted host toolchain because toolchain this build step runs in has to match word size of target architecture.
So, for example, when targeting android arm 32-bit architecture, when building on linux 64-bit machine, patched_sdk rule has to run with linux-x86 host tool chain, rather than linux-x64,so it match android arm 32-bit.

When using this rule from flutter .gn-files there seem to be no way to communicate to that rule which custom host toolchain(dart_host_toolchain, determined by flutter) to use. So the workaround is to copy patched_sdk rule over to flutter .gn-files and use dart_host_toolchain in that copy.

@rmacnak-google

**Comment by aam** [comment]
Unfortunately, copying generate_patch_sdk.gni(which provides template used by patched_sdk) is not sufficient to fix the patched sdk generation problem for Flutter. The reason is that patch_sdk.dart needs standalone Dart patched sdk, so Flutter generate_vm_patched_sdk has dependency on //dart/runtime/vm:patched_sdk, which fails to build correctly since it uses host_toolchain instead of dart_host_toolchain.

@sigmundch

**Comment by aam** [comment]
@rmacnak-google , what do you think of copying logic from toolchain.gni into flutter/tools/gn, so dart_host_toolchain is populated in args.gn 
```
    # Modify host_toolchain into dart_host_toolchain so it matches word size of target_cpu
    if args.target_os == 'android' and aot and gn_args['target_cpu'] == 'arm':
      if sys.platform.startswith('linux'):
        gn_args['dart_host_toolchain'] = "//build/toolchain/linux:clang_x86"
      elif sys.platform.startswith('darwin'):
        gn_args['dart_host_toolchain'] = "//build/toolchain/mac:clang_i386"
    elif args.target_os == "ios" and not args.simulator:
      if gn_args['target_cpu'] == 'arm':
        gn_args['dart_host_toolchain'] = '//build/toolchain/mac:clang_i386'
      elif gn_args['target_cpu'] == 'arm64':
        gn_args['dart_host_toolchain'] = '//build/toolchain/mac:clang_x64'
``` consumed in generate_patch_sdk.gni:
```
declare_args() {
  dart_host_toolchain = host_toolchain
}
...
      deps += [ "$_dart_root/runtime/bin:dart_bootstrap_host_arch($dart_host_toolchain)" ]
...
              "$_dart_root/runtime/bin:dart_bootstrap_host_arch($dart_host_toolchain)",
...
```

**Comment by aam** [comment]
@abarth who introduced toolchain.gni back in https://github.com/flutter/engine/pull/2905

**Comment by abarth** [comment]
Neat.

**Comment by aam** [comment]
This was addressed with https://codereview.chromium.org/2944103003/
