### ISSUE TITLE
Spikes on hotReloadVMReloadMilliseconds have gotten worse (Flutter benchmarks)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29973]
The spikes on our hot_mode_dev_cycle__benchmark hotReloadVMReloadMilliseconds benchmark have been getting worse:

![screenshot from 2017-06-21 16 24 42](https://user-images.githubusercontent.com/551196/27410716-2858e8d6-569e-11e7-8091-3d30b7b183f7.png)

**Comment by a-siva** [comment]
@rmacnak-google

**Comment by a-siva** [comment]
I looked at the current trend of this benchmark and see that the occasional spikes are not in the same order as they were when this issue was opened. Closing this bug, if you think otherwise please reopen it.
