### ISSUE TITLE
(Flutter) GC pauses causing animation jank

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29971]
The app attached below visibly janks. Looking at a timeline trace (a sample is attached below), it seems to be partly caused by long GCs; in the trace attached, you can see two 11ms GCs right in the middle of layout. (It would be less problematic if they were scheduled to trigger between frames rather than in the middle of frames, but 11ms is probably too long at any time.)

application: [main.dart](https://github.com/dart-lang/sdk/files/1093013/jank.dart.txt)
trace: [timeline.json](https://github.com/dart-lang/sdk/files/1093018/timeline.json.txt)

**Comment by rmacnak-google** [comment]
@a-siva 

It's weak handle processing, so this could be time in the VM or the engine.

**Comment by a-siva** [comment]
Checked a profile of this app again with the latest bits and did not see any 11ms GCs, the max GC time I saw was 2 ms.
