### ISSUE TITLE
TouchEvent.supported always true in Dartium

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/sdk#29997]
The following always returns true in Dartium (v45 and v50) when SDK 1.24.1 is used:
`print("TouchEvent.supported: ${TouchEvent.supported}");`

It works correctly in Chrome et al after dart2js, and also correctly in Dartium when SDK < 1.24 is used.

System: MBP, OSX Sierra

**Comment by matanlurey** [comment]
Dartium is no longer supported.
