### ISSUE TITLE
[reload] Consider using coverage data to suggest when a restart may be needed

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29999]
Based on discussion with @eseidelGoogle 

Users are sometimes surprised when hot reload doesn't have an effect on their program, often because the part of the program they changed does not run again after a reassemble. To mitigate this, we might alert users to the presence of code that was changed but not executed, by resetting coverage data after a hot reload and checking after a reassemble completes (or fails) for changed functions without coverage data.

@bkonyi

**Comment by eseidelGoogle** [comment]
@rmacnak-google and I were noodling about how to increase confidence-in/understanding-of hot reload.  Let us know if something like this would help, or how high on your list of changes something like this would rank, @mit-mit @devoncarew.

**Comment by a-siva** [comment]
Closing bug as this feature has been added.
