### ISSUE TITLE
js-interop error mixin dart:js and a package:js facade implementing dart:html#Event

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#29992]
(tested on dart2js from sdk-1.24.x and sdk-1.23.x)

The original issue isoos/pwa#10 was reported as a problem using both `package:google_maps` and `package:pwa`.

Here is a simple reproduction where the following js error occurs : 

>Uncaught TypeError: J.getInterceptor$asx(...).$index is not a function

- page.html
```html
<!DOCTYPE html>
<script type="application/dart" src="page.dart"></script>
<script src="packages/browser/dart.js"></script>
```

- page.dart
```dart
import 'lib.dart'; // note that this import is not used !
import 'dart:js';
void main() {
  print(context['Object']['defineProperty']);
}
```

- lib.dart
```dart
@JS()
library lib;
import "dart:html" show Event;
import "package:js/js.dart";
@anonymous
@JS()
abstract class A implements Event {}
```

**Comment by jacob314** [comment]
anonymous classes implementing dart:html types unfortunately isn't supported.
