### ISSUE TITLE
standalone/io/skipping_dart2js_compilations_test fails on the vm-precomp bots

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#30008]
I'm seeing a failure for standalone/io/skipping_dart2js_compilations_test on 4 vm-precomp bots (including precomp-linux-debug-x64-be and precomp-linux-product-x64-be).

https://build.chromium.org/p/client.dart/builders/precomp-linux-debug-x64-be/builds/730/steps/vm%20tests/logs/stdio

The repro case is here:

```
python tools/test.py -m product -c precompiler -r dart_precompiled --builder-tag no_ipv6 standalone/io/skipping_dart2js_compilations_test
```

I believe this failure may have been previously masked by some status file exclusions (for code that transitively imported dart:mirrors). Those exclusions were removed here https://github.com/dart-lang/sdk/commit/dd5c779b4359004e63103449a9357d9b8c2715ed in order to fix bot issues introduced by upgrading to the latest package:http (https://github.com/dart-lang/sdk/commit/ebffa49eac88627181233fbb2a29482eb5c72c66).

**Comment by devoncarew** [comment]
When I print out stderr from the process result here: https://github.com/dart-lang/sdk/blob/master/tests/standalone/io/skipping_dart2js_compilations_test.dart#L135, I see

```
VM initialization failed: Precompiled runtime requires a precompiled snapshot
```

**Comment by devoncarew** [comment]
https://codereview.chromium.org/2954283002/

**Comment by devoncarew** [comment]
https://codereview.chromium.org/2961623002

**Comment by munificent** [comment]
Since this is just a test of the SDK's test runner, I don't think we care about it in this config.
