### ISSUE TITLE
Dart analyzer incorrectly marks function as unused if it is a concrete implementation of a stub specified in a mixin

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#30007]
This may be related to issue #30005. I'll use the same example as in that issue.

Consider the following interface specification, and a partial implementation of that interface provided by a mixin class:

```
@interface
abstract class MyInterface {

  void doThingA();

  void doThingB();

}

@mixin
abstract class MyInterfacePartialImplementation
implements MyInterface {

  @override void doThingA() {
    // ... do A-like things that we know will be the same across all implementations
  }

  @override void doThingB() {
    // ... do B-like things that we know will be the same across all implementations

   ...

    // ... but ensure that we also do one implementation-specific thing that we can't possibly know about
    // at interface time - but we know it's going to be necessary, so we want to insist an implementor
    // provides it

    this._doImplementationSpecificThingB();
  }

  void _doImplementationSpecificThingB(); // Stub out the implementation-specific thing
    // so any implementor of this interface consuming this mixin will be required to implement it.

}
```

Any implementor of this interface can get almost all the implementation functionality they require simply by including the mixin; they need only implement the stub specified by the mixin:

```
@implementation
class SomeImplementationOfMyInterface
extends Object
with MyInterfacePartialImplementation
implements MyInterface {

  @override void _doImplementationSpecificThingB() {
    // a concrete, implementation-specific implementation of the stub required by the mixin
  }

}
```

However, dart analyzer incorrectly marks the concrete implementation of  _doImplementationSpecificThingB() as unused, even though it is invoked from the mixed-in function doThingB(). Furthermore, removing the concrete implementation entirely does not result in any analysis error, even though a function required by the mixin is now missing completely and the implementation no longer fulfils the interface specified by the mixin. The problem did not occur in 1.23.x.

**Comment by ajrcarey** [comment]
I suspect the problem may be to do with the use of underscores specifying private member functions rather than public. Removing the underscores corrects the behaviour.

**Comment by bwilkerson** [comment]
Are `SomeImplementationOfMyInterface` and `MyInterfacePartialImplementation` in the same library?

**Comment by ajrcarey** [comment]
Sorry for the delay in replying. No, they're not, and the conversation in #30005 honed in on that aspect as well. This was the first attempt to consume the mixin class from a different package. It makes sense that the package private functions cannot be mixed in.

So, it's appropriate for the analyzer to be marking those functions as unused in this case. I do think the analyzer should be complaining about the situation for different reasons, which I've listed in #30005 .
