### ISSUE TITLE
dart2js considers ints to be doubles

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#30001]
in the dart vm, `1 is double` is false.
but in dart2js, `1 is double` is true.
according to dart's type hierarchy, `int` is _not_ a subtype of `double`, so this seems like a dart2js bug.

here's 1 way this can manifest as trouble downstream:
someone sees a function f that returns the output of `double.parse`.
`double.parse` declares that it returns a `double`, but this friendly soul observes that sometimes
`double.parse` actually outputs an `int` (e.g. [here](https://dartpad.dartlang.org/40a277d021e6df0188cd82ebf97a1509) not realizing that dartpad uses dart2js semantics) and so changes the return type of f to `num` because they were afraid that some client
might receive an `int`, think it's a `double`, and induce a bug.
this forces all consumers of f to update their code, and so on.

now `int` and `double` both extend `num`, and `double` mysteriously has no extra methods.
or, to look at it from another perspective, it's mysterious that `num` has methods that
seem more appropriate for doubles than all numbers, like `round`, `truncate`.
so an `int` can _duck type_ as a `double`.
perhaps this is how dart2js can mostly get away with this,
but woe to anyone writing this code:
```dart
num numScoops({bool userLikesIcecream}) => userLikesIcecream ? 1.5 : 1;

void main() {
  var n = numScoops(userLikesIcecream: false);
  print(n is double
      ? "here's a little extra for you!"  // in dart2js, user gets confused
      : "icecream's all we got");
}
```

**Comment by sigmundch** [comment]
@trinarytree - unfortunately this is a bug that cannot be fixed in dart2js.

Take a look at https://github.com/dart-lang/sdk/issues/1533 for more details.

**Comment by sigmundch** [comment]
FWIW, I agree with you that this surprising behavior is not ideal, so I hope the language can be improved to highlight warn about this. For example, maybe there should be a warning if code has checks for `is double` and `is int`, since we know that they might have inconsistent semantics based on the target platform.

@floitschG @munificent - are there plans to address this in the language?

**Comment by munificent** [comment]
No concrete plans that I am aware of though I personally would like to do a better job of helping users deal with cases like this.

**Comment by zoechi** [comment]
What about a warning in dart2js about using `is double` or `is int`?

**Comment by munificent** [comment]
I thought it had that warning, but maybe it disappeared at some point?
