### ISSUE TITLE
Strong mode toggle on DartPad appears to be "reversed"

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#30017]
For example:
https://dartpad.dartlang.org/35ef608a771ee788e8edb266bab97e14

With "strong mode" off, this should have no errors (but currently has a type error). 

With strong mode enabled, it should have a type error (but currently doesn't).

**Comment by mit-mit** [comment]
![screen shot 2017-06-26 at 16 48 43](https://user-images.githubusercontent.com/13644170/27545141-6191ccf4-5a8f-11e7-8f9c-1c668f127375.png)

**Comment by mit-mit** [comment]
Note: fix still to be deployed, we will update again when that has happened.

**Comment by lukechurch** [comment]
Fixed version is now serving
