### ISSUE TITLE
add a Platform.operatingSystemVersion field

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#30018]
In dart:io, we have a `Platform.operatingSystem` field with the OS name. It would be useful to have a similar field for the operating system version. The specific use case I have for it is for reporting analytics - windows 7, windows 10, ...

**Comment by devoncarew** [comment]
See also https://github.com/dart-lang/usage/issues/101.

**Comment by zanderso** [comment]
To support such an API across platforms, we'd probably have to return whatever string we get from the OS.
- Windows: [IsWindows*OrGreater() from versionhelpers.h](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx)
- MacOS: [sysctlbyname("kern.osrelease")](https://stackoverflow.com/questions/11072804/how-do-i-determine-the-os-version-at-runtime-in-os-x-or-ios-without-using-gesta)
- Linux, Android, Fuchsia: [uname()](http://man7.org/linux/man-pages/man2/uname.2.html)
