### ISSUE TITLE
Analyzer error returning `this` in a generic method

### ISSUE THREAD

**Issue by adamlofts** [dart-lang/sdk#30012]
The following:

```
abstract class A {}

class B implements A {
  T query<T extends A>() {
    return this;
  }
}

main() {
  print(new B().query());
}
```
Runs fine in both checked and unchecked mode.

The analyzer complains in weak and strong mode both of which seem wrong to me:
```
dartanalyzer --strong bin/test.dart 
Analyzing bin/test.dart...
  error • The return type 'B' isn't a 'T', as defined by the method 'query' at bin/test.dart:6:12 • return_of_invalid_type
1 error found.
```
```
dartanalyzer --no-strong bin/test.dart 
Analyzing bin/test.dart...
  warning • The return type 'B' isn't a 'T', as defined by the method 'query' at bin/test.dart:6:12 • return_of_invalid_type
1 warning found.
```

**Comment by eernstg** [comment]
This is actually working as intended. There is no subtype relationship among the types here: T is an unknown type which must satisfy T extends A, and B is another subtype of B. Assignability allows for upcasts and downcasts, but this requires an upcast (to A) followed by a downcast (to T). So the analyzer should complain.
