### ISSUE TITLE
dart2js svg::Rect used for FF, Safari and IE not working

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#30014]
failing test that tries to implement the Rect interface. Apparently , svg::Rect used to only implement x, y, width, and height, but now it also has blink_jsObject:

FAILED: dart2analyzer-none-checked release_ia32 co19/LayoutTests/fast/svg/getbbox_t01
Expected: Pass
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_TWO|/mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/svg/getbbox_t01.dart|63|7|6|Missing concrete implementation of setter 'Rect.blink_jsObject' and getter 'Rect.blink_jsObject'

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --enable_asserts --enable_type_checks --show-package-warnings --enable-async --package-root=out/ReleaseIA32/packages/ --machine --no-hints /mnt/data/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/co19/src/LayoutTests/fast/svg/getbbox_t01.dart
Took 0:00:00.010000

**Comment by athomas** [comment]
LayoutTests have been deleted.
