### ISSUE TITLE
Observatory integration into external IDEs

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#30023]
We want to provide a standard way to integrate Observatory into external IDEs.

In order to do not require control on the browser hosting Observatory the command are going to be send back to the IDE via custom Events.

**Comment by johnmccutchan** [comment]
Another use case:

Observatory debugger wants flutter tools to perform a hot reload on its behalf.

**Comment by B3rn475** [comment]
@devoncarew

**Comment by devoncarew** [comment]
> We want to provide a standard way to integrate Observatory into external IDEs

We could restate this slightly to `'we want the Observatory to be aware of other connected clients'`. An IDE could provide the 'open file:line' service, and flutter tools could provide the 'hot reload app' service.

**Comment by B3rn475** [comment]
Design document for external services registration and invocation:
https://docs.google.com/document/d/1C__cum1a9UzFi8Lt8xNp0CJ4WELMtjYG4a645AwmxBo/edit#heading=h.fb7fkbehjw3r

**Comment by B3rn475** [comment]
Should we consider this issue as Closed? Or should we wait for the integration of the other pages?

**Comment by devoncarew** [comment]
I think we can close this and open more specific issues as they arise.
