### ISSUE TITLE
Allow a final block declaration in Class definitions

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/sdk#30024]
There seems to be a general pattern of Class fields that are final to be grouped together e.g.

```
class TableBuilder {

  final int _width;
  final int _height;

  final List<TableCellElement> _listAll = new List<TableCellElement>();
  final List<List<TableCellElement>> _gridAll = new List<List<TableCellElement>>();
  final TableElement table = new TableElement()

  int count = 1;
  String name = "Davy"
}
```

This can be difficult to read though overall having the finalised fields together helps in understanding a Class.

Suggestion is for a new final block declaration syntax (one per class) - behaviour unchanged:

```
class TableBuilder {

  final { 
   int _width;
   int _height;

   List<TableCellElement> _listAll = new List<TableCellElement>();
   List<List<TableCellElement>> _gridAll = new List<
      List<TableCellElement>>();
   TableElement table = new TableElement();
  }

  int count = 1;
  String name = "Davy";
}
```

I am not totally convince this is the correct syntax but worth a discussion. It's a bit more than syntactic sugar (of less typing) as a lint could enforce good organisation and encourage things to be final (for optimisation/robustness). However as the grouping of finals is not 100% (things may be better grouped logically) - I am not sure this feature would have enough general usefulness. There's also the question of consistency - const blocks too? Could get messy?

**Comment by lrhn** [comment]
Things could definitely get messy. 

Another issue is that it breaks locality - looking at a declaration doesn't tell you the entire story, you have to look *n* lines up to see that it's actually inside a `final` block.

The inside of a `final`-block would only allow field declarations. That means that changing something from a field to a getter/setter pair require moving them (I'd do that anyway, but not everybody agrees).
Some prefer to write fields and associated getters/setters near each other, which wouldn't be possible.

It really is just syntactic sugar (it's equivalent to making the fields final individually). It might encourage grouping, but if we don't even encourage that in writing now (the style guide is silent on member ordering), I don't see that as a convincing argument for adding the block.
Also, it now adds a choice that users have to make every time they make a class - should they have a `final`-block or individual final fields? What if they only have one field? That's more user complexity right there, and it gives no advantage to clients of the class - they just see the getters anyway.

All in all, it's worth considering, but I don't personally see the advantages overcoming the added complexity.

**Comment by zoechi** [comment]
Perhaps just a quickfix on field declarations to add/remove `final`, `const`, and `static` (`static` also for other members) would be a better option.

For classes that for example represent database records or some JSON response, another level of abstraction is probably not that helpful.
