### ISSUE TITLE
Add common deployment flags to `dart2js -hv`

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#30022]
See https://github.com/dart-lang/site-webdev/issues/783.

Is there any reason why we shouldn't document these flags?

**Comment by sigmundch** [comment]
Agree, we should add it. No reason not to do so.

**Comment by kwalrath** [comment]
Should we also add corresponding options to pub (https://webdev.dartlang.org/tools/pub/dart2js-transformer#options)?

It looks like the option names should be `trustPrimitives`, `trustTypeAnnotations`, and `fastStartup`.

**Comment by sigmundch** [comment]
Possibly, I'm not sure if it is worthwhile though, we can still use the `commandLineOptions` flag:
```
   $dart2js:
    commandLineOptions: [--fast-startup, --trust-primitives, --trust-type-annotations]
```

**Comment by kwalrath** [comment]
It's just that the docs say: 

> In addition to the options previously listed, commandLineOptions is available as a fallback for cases where a new command-line option has been added to dart2js, but a corresponding configuration option has not yet been added to pub.

Maybe we should change that to say "...available for command-line options that have no corresponding configuration option in pub."

**Comment by sigmundch** [comment]
I like that. Long term though, I agree Kathy that if some of these options are used all the time, we should expose them. The reason I'm not sure it is worthwhile at this moment, is that this is likely going to change soon when strong mode is supported in dart2js.

/cc @munificent in case you prefer to expose dart2js options in pub differently.

**Comment by kwalrath** [comment]
I've updated that text in dart-lang/site-webdev/pull/791.

**Comment by munificent** [comment]
What are `-hv`? If they are common/useful, I think it's reasonable to expose them in pub. If they aren't used commonly, relying on `commandLineOptions` seems OK to me.

**Comment by zoechi** [comment]
I'd expect `--trust-primitives, --trust-type-annotations` to become default/obsolete in Dart 2.0 when dart2js supports strong mode. In Dart 1.x it's about how much one wants to buy into strong typing.

**Comment by munificent** [comment]
> I'd expect `--trust-primitives`, `--trust-type-annotations` to become default/obsolete in Dart 2.0 when dart2js supports strong mode.

Me too.

**Comment by kwalrath** [comment]
So maybe `fastStartup` would still need to be an option? (I'm fine with waiting, though.)

**Comment by floitschG** [comment]
I don't think `--trust-primitives` is made obsolete by strong mode.

**Comment by matanlurey** [comment]
@floitschG Any particular reason why not?

**Comment by sigmundch** [comment]
@matanlurey - trust-primitives assumes that input *values* of primitive operations are valid, not just that they have the right type. This includes arguments to operators are assumed to be non-null and that index operation arguments are assumed to be in range (e.g. `list[i]`)

**Comment by joshualitt** [comment]
I'm going to close this bug due to age, and because we currently document the -O options. Please reopen this bug if there are still additional flags we should document.
