### ISSUE TITLE
Fasta doesn't support annotations on typedefs

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30034]
While trying to implement type inference on annotations, I discovered that Fasta appears to discard annotations on typedefs.  For example, in the following code the annotation `@Foo()` is dropped:

```dart
class Foo {
  const Foo();
}

@Foo()
typedef void F();
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2987983004

**Comment by sigmundch** [comment]
it seems this was fixed by @scheglov change, please reopen if I'm mistaken
