### ISSUE TITLE
Kernel can't represent annotations on locals, parameters, or type parameters

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30035]
Kernel has no way of representing the annotations `@Foo()` in the following code:

```dart
class Foo {
  const Foo();
}

void test(@Foo() x) {
  @Foo()
  var y;

  @Foo()
  void f() {}
}

class C<@Foo() T> {}
```

**Comment by stereotype441** [comment]
Any idea when we can expect this to get fixed?  It came up in https://dart-review.googlesource.com/c/sdk/+/5296

**Comment by kmillikin** [comment]
I guess it suffices to add a list of metadata annotations to TypeParameter and VariableDeclaration?  Dima, will you do that?

**Comment by stefantsov** [comment]
Yep, I'm on it.

**Comment by stefantsov** [comment]
The annotations are added in https://github.com/dart-lang/sdk/commit/e7a29d8dfbf873917096e00d3468bfd08aaca867.
