### ISSUE TITLE
User defined hashCode not correctly invoked on emulated functions

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30030]
The following fails in DDC:

```dart
import 'package:expect/expect.dart';

typedef int Func(int x);

class MyFunc {
  Func _fn;

  MyFunc(this._fn);

  int call(int x) => _fn(x);

  int get hashCode => _fn.hashCode;

  bool operator==(Object other) => other is MyFunc && other._fn == _fn;
}


void main() {
  Func f = (x) => x + 1;
  Func g = (x) => x - 1;

  var myf1 = new MyFunc(f);
  var myf2;
  myf2 = new MyFunc(f);
  var myg = new MyFunc(g);

  Expect.equals(myf1.hashCode, myf2.hashCode);
  Expect.equals(myg.hashCode, g.hashCode);
  Expect.equals(myf1, myf2);
  Expect.notEquals(myf1, myg);
}
```

**Comment by vsmenon** [comment]
Interestingly, we compute the right `hashCode` for `myf1`, but not `myf2`.  For the former, we determine it's non-nullable and generate `myf1.hashCode`.  For the latter, we generate `dart.hashCode(myf2)` just in case its null.

Something is broken about the dispatch in the latter.

**Comment by jmesserly** [comment]
oh funny, this came up in Leaf's CL for `==`. the problem is with dart:_runtime operations.dart, `hashCode` ... functions are hard coded to use identity based hashcodes.

**Comment by jmesserly** [comment]
A few other problems we found so far:

* hashCode does not support method tearoffs
* various places that call `dart.bind` like implicit-this, dload, don't handle Object members.
* dynamic tear off of Object members does not seem to work (it does not even seem to generate dload correctly)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2962263002/
