### ISSUE TITLE
No compile-time error for initialization clash

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#30036]
According to #29656 there should be a compile error for the following code

```dart
class C {
  final x = 1;
  C() : this.x = 2 {}
}

main() {
  try {
    new C();
  } catch(e) {
    print("Runtime exception: " + e.toString()); 
  }
}
```
This programm can be run without any compile error. Output is 
```
Runtime exception: 'file://...': error: line 39 pos 9: final field 'x' is already initialized.
  C() : this.x = 2 {}
        ^
```
There should be compile time, not a runtime error
Tested on Dart VM version: 1.25.0-dev.3.0 (Fri Jun 23 04:25:18 2017) on "windows_x64"

**Comment by natebosch** [comment]
This example has a static error in both CFE and analyzer now.
