### ISSUE TITLE
Removed files not recognized as removed

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30032]
I had one file `a.dart` and a second file `b.dart` that imported `"a.dart"` (in case the style of import is important. If I delete `a.dart`, the import in `b.dart` isn't marked as being invalid. This persists even if I restart the analysis server.

**Comment by bwilkerson** [comment]
@scheglov Is server finding the summary for `a.dart` and not checking to see whether the file currently exists? If so, should we remove the summary when a file is deleted?

This might be related to #29968.

**Comment by scheglov** [comment]
I was not able to reproduce this issue.
The test in https://codereview.chromium.org/2959903005 does remove/re-add and the error is reported after remove.

**Comment by bwilkerson** [comment]
I don't have time right now to try to reproduce it, so I'll close this.
