### ISSUE TITLE
Dart2js: Assert in initializer list.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30038]
We have decided to make asserts in initializer lists part of the language. Dart2js needs to implement the feature.
See: `docs/language/informal/assert-in-initializer-list.md` for a description of the feature.

**Comment by sigmundch** [comment]
We'll implement this after we migrate to use the shared FE, but we will keep the old pipeline as is for the time being.

**Comment by rakudrama** [comment]
We should hold off on implementing the feature until Kernel has defined what it looks like.
https://github.com/dart-lang/sdk/issues/30914

**Comment by dgrove** [comment]
Any updates on this, @sigmundch ?

**Comment by sigmundch** [comment]
This is already implemented.
