### ISSUE TITLE
Precompiled runtime includes JIT compiler

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#30045]
Due to the way the VM code is linked together currently, the precompiled runtime VM includes all the code for the JIT compiler, even though that code is never used. This is about a megabyte worth of code.

If we make sure that the precompiled runtime build does not contain references to any part of the compiler, the compiler code will be left out automatically by the linker.

To achieve this, we need to designate a set of compiler-specific source files and make certain that all references to any symbol in these files are either in one of the compiler-specific files themselves or is guarded by #if !defined(DART_PRECOMPILED_RUNTIME).

There is almost such a set in these .cc files:

ast, cha, compiler, constant_propagator, deferred_objects, deopt_instructions, flow_graph*, intermediate_language*, intrinsifier*, locations, parser, regexp_assembler_ir

plus, possibly, if we want to dig a bit deeper:

assembler*, stub_code*

There is some code here and there to move or guard for this to hold, though.

**Comment by a-siva** [comment]
Can this be closed?

**Comment by askeksa-google** [comment]
This CL is still pending: https://codereview.chromium.org/2976723003/

**Comment by askeksa-google** [comment]
Reopened because the last change caused a 63% increase in AOT snapshot size of Flutter Gallery. @rmacnak-google Did you notice what kind of content constituted the size growth?

**Comment by rmacnak-google** [comment]
The biggest effect was on the instructions portion of the snapshot (see https://github.com/dart-lang/sdk/issues/30472). My guess is that one of the compiler flags accidentally got a new value.

**Comment by jason-simmons** [comment]
I traced the difference to a change in FLAG_unbox_numeric_fields.

PrecompilationModeHandler should set unbox_numeric_fields to false, but that was lost when it was moved to runtime/vm/compiler.cc
