### ISSUE TITLE
Information needed for type inference is lost during error recovery

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30040]
There are two of analyzer's old type inference tests that I can't get to pass in the new front end due to the way Fasta handles error recovery (it replaces the erroneous code with "throw" expressions, so the information that would be needed by type inference is lost):

```
inference/constructors_too_many_positional_arguments: Fail
inference/future_then_explicit_future: Fail
```

On the one hand, it may not be worth trying to fix these failures, considering that there are errors in the test cases and I think it's reasonable for a user to expect type inference to fail when the code is erroneous.

On the other hand, we may need to change Fasta handles error recovery in order to interface with analyzer; if we do so it may be worth trying to get these tests to pass.

cc: @peter-ahe-google

**Comment by peter-ahe-google** [comment]
This is blocked on #29840.

**Comment by johnniwinther** [comment]
Fixed
