### ISSUE TITLE
Native SignalInfo objects are leaked on Isolate shutdown

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30042]
If an Isolate shuts down without canceling a watched signal, the relevant entry in the list of SignalInfo (https://github.com/dart-lang/sdk/blob/master/runtime/bin/process.h#L162) objects will be leaked. This also has the effect that the default signal handler will not be restored if the last Isolate to watch a signal shuts down without canceling.

The solution is probably to clean up the SignalInfo object from the native finalizer attached to the _NativeSocket Dart object for the signal subscription.

**Comment by bkonyi** [comment]
@zanderso, could you point me to where this _NativeSocket finalizer is defined/set?

**Comment by zanderso** [comment]
It's here: https://github.com/dart-lang/sdk/blob/master/runtime/bin/socket.cc#L959

It looks like you'll have to plumb the signal number and maybe also the isolate's main port id through along with the socket so that you can call `Process::ClearSignalHandler` from a possibly new kind of finalizer attached there.

**Comment by bkonyi** [comment]
Fixed (here)[https://dart-review.googlesource.com/c/sdk/+/46125].
