### ISSUE TITLE
Dart 1.0 spec unclear about runtime type of function expressions; implementations disagree

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30044]
The spec section `Function Expressions` defines the static return type of function expressions based on the function body, but doesn't say anything about the runtime type (except that it implements the built-in class `Function`).  A reader might reasonably infer that the runtime type of a function expression is the same as its static type (I made exactly this assumption in my work on the new front end).  But the VM and dart2js don't behave this way.  With the VM, the runtime return type of a function expression appears to always be `dynamic`.  With dart2js, the runtime return type of a function expression appears to be `dynamic` for sync functions, `Iterable` for sync* functions, `Future` for async functions, and `Stream` for async* functions.

For now, I will update the new front end so that when strong mode is off, it behaves the same as the VM.  However, the spec should be clarified, and then we should adjust the behavior of the implementations to match.

**Comment by lrhn** [comment]
Not only does it not say what the runtime type is, it doesn't actually say what the runtime *value* is. Luckily implementations agree that it's a callable object that does what you expect :)

The type difference is annoying, and while I prefer the dart2js approach, I don't think it's worth changing anything at the current point.

In Dart 2, I expect the static return type to become the runtime return type as well, by upwards inference if the downwards inference hasn't mandated another type – even if it is one place where the inferred type cannot be written explicitly if you want it.

**Comment by lrhn** [comment]
The specification now specifies the static type of each type of expression.
