### ISSUE TITLE
Output from test package being duplicated as of Dart 1.23.0

### ISSUE THREAD

**Issue by micahbeeman-wf** [dart-lang/sdk#30055]
When I upgraded from Dart 1.22.1 to 1.23.0 I noticed the output from the test package contains duplicated lines in stack traces for failures. The included output shows the line containing "26:61" displaying twice when executed using Dart 1.23.0 and once when executed using Dart 1.22.1. It appears something has changed in Dart 1.23.0 regarding stack traces, is this a regression or an intentional change? Duplicated output seems unintentional.

**Dart 1.23.0 output:**

00:01 +0 -1: Given that I am testing the Element.findAllWithError method and I request an element which is not present in the page [E]
  Exception: 
  
  ERROR: Unable to locate any 'Not There' items on the right side of the page. 
  
  The elements were sought using the following criteria: By.id(this-id-is-not-there)
  
  
  package:w_webdriver_utils/src/element.dart 508:7                                  Element.findAllWithError
  test/findAllWithError_Integration_tests/findAllWithError_test_failing.dart 26:61  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                        _Completer.completeError
  package:w_webdriver_utils/src/element.dart 513:3                                  Element.findAllWithError
  ===== asynchronous gap ===========================
  dart:async                                                                        _asyncThenWrapperHelper
  package:w_webdriver_utils/src/element.dart 503:76                                 Element.findAllWithError
  test/findAllWithError_Integration_tests/findAllWithError_test_failing.dart 26:61  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                        Future.Future.microtask
  test/findAllWithError_Integration_tests/findAllWithError_test_failing.dart 25:80  main.<fn>.<fn>

**Dart 1.22.1 output:**

00:01 +0 -1: Given that I am testing the Element.findAllWithError method and I request an element which is not present in the page
  Exception: 
  
  ERROR: Unable to locate any 'Not There' items on the right side of the page. 
  
  The elements were sought using the following criteria: By.id(this-id-is-not-there)
  
  
  package:w_webdriver_utils/src/element.dart 508:7                                  Element.findAllWithError.<async>
  ===== asynchronous gap ===========================
  dart:async                                                                        _Completer.completeError
  package:w_webdriver_utils/src/element.dart 528:3                                  Element.findAllWithError.<async>
  ===== asynchronous gap ===========================
  dart:async                                                                        _asyncThenWrapperHelper
  package:w_webdriver_utils/src/element.dart                                        Element.findAllWithError
  test/findAllWithError_Integration_tests/findAllWithError_test_failing.dart 26:61  main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                                                                        Future.Future.microtask
  test/findAllWithError_Integration_tests/findAllWithError_test_failing.dart        main.<fn>.<fn>

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/test#660
