### ISSUE TITLE
Create a Dart Code of Conduct.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#30051]
Follow-up from https://github.com/dart-lang/linter/pull/718.

The gist is to add a simple [code of conduct](https://opensource.guide/code-of-conduct/)  in the spirit of other inclusive OSS projects (and the advice of [github](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)).

As per @anders-sandholm's suggestion, this file would live in the root of the SDK as well standard template repo so it is automatically included in new repos going forward.  Existing projects like the [linter](https://github.com/dart-lang/linter) can manually sync up.

**Comment by kwalrath** [comment]
We'll be doing this on www.dartlang.org. See dart-lang/site-www#539.

**Comment by pq** [comment]
This is fixed, and live here: https://www.dartlang.org/code-of-conduct

Thank you!
