### ISSUE TITLE
VM: gen_snapshot does not escape paths with spaces when generating depfiles

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#30059]
This will break users that have their Flutter project in a directory whose name includes a space

@cbracken

**Comment by cbracken** [comment]
@jakobr-google 
FYI for the gradle code that parses this here:
https://github.com/flutter/flutter/blob/2d79ce8419db5b72a3b67e072e76edb43903d3ea/packages/flutter_tools/gradle/flutter.gradle#L344
