### ISSUE TITLE
Exception in JavaScript compiled by dartdevc: Type 'MappedListIterable<int, String>' is not a subtype of type 'List<String>

### ISSUE THREAD

**Issue by Blimster** [dart-lang/sdk#30066]
The following code throws an exception with message 'Type 'MappedListIterable<int, String>' is not a subtype of type 'List<String>' in JavaScript compiled by dartdevc (dart 1.25.0-dev.4.0):
```dart
void main() {
  f([1, 2, 3].map((e) => e.toString()));
}

void f(List<String> p) {
}
```

**Comment by zoechi** [comment]
I think you need to add `.toString()` 
```dart
void main() {
  f([1, 2, 3].map((e) => e.toString()).toList());
}

void f(List<String> p) {
}
```
or change the parameter type
```dart
void main() {
  f([1, 2, 3].map((e) => e.toString()));
}

void f(Iterable<String> p) {
}
```

**Comment by matanlurey** [comment]
This is a valid bug. An `Iterable` is not a `List`:

> ```dart
> void main() {
>   // f ( Iterable<String> )
>   f([1, 2, 3].map((e) => e.toString()));
> }
>
> void f(List<String> p) {
> }
```

You should use `toList`:

```dart
f([1,2,3]).map((e) =>e.toString()).toList();
```

If you'd like to see this error _statically_, you can enable `--no-implicit-casts`.

/cc @leafpetersen

**Comment by lrhn** [comment]
The comments are correct, the `Iterable.map` method returns an `Iterable` that is not a `List`, so the error is correct.

**Comment by Blimster** [comment]
Didn't notice the importance of disabling implicit down casts so far... thought enabling strong is enough for dartdevc... sorry.
