### ISSUE TITLE
Issue of importing Polymer dependencies in AngularDart

### ISSUE THREAD

**Issue by imtusharrai** [dart-lang/sdk#30060]
Resolving dependencies...
Package polymer has no versions that match >=1.0.0 <2.0.0 derived from:
- name_your_startup depends on version ^1.0.0
Process finished with exit code 1

**Comment by zoechi** [comment]
Polymer isn't maintained anymore. 
Polymer 2 for Dart is maintained by the community. 
See https://pub.dartlang.org/packages/polymerize.
Polymerize depends on DDC. Angular2 support for DDC is still work in progress. 
You have to try if it already works for your project.

**Comment by srawlins** [comment]
Closing as the polymer package is not maintained.
