### ISSUE TITLE
Exception in JavaScript compiled by dartdevc: Type 'JSArray<num>' is not a subtype of type 'List<double>

### ISSUE THREAD

**Issue by Blimster** [dart-lang/sdk#30065]
The following code throws an exception with message 'Type 'JSArray&lt;num&gt;' is not a subtype of type 'List&lt;double&gt;' in JavaScript compiled by dartdevc:
```dart
void main() {
  f([1.0]);
}

void f(List<num> data) {
}
```
Dart SDK 1.25.0-dev.4.0

**Comment by zoechi** [comment]
```dart
f(<num>[1.0]);
```
should fix it.
Not sure if it should accept it without `<num>`

**Comment by matanlurey** [comment]
This seems like a valid bug. /cc @vsmenon

**Comment by lrhn** [comment]
Agree. A `List<double>` is-a `List<num>` and a `JSArray` is-a `List`, so it seems like it should work.

**Comment by vsmenon** [comment]
On my phone, but that is a valid error message. List of num is not a
subtype of List of double because num is not a subtype of double.

**Comment by lrhn** [comment]
`List<num>` is indeed not a subtype of `List<double>`, but there is no `List<double>` type assertion in the program that can fail like that, so the *error* is spurious.
The only actual assignment is of a `JSArray<num>` to a `List<num>` parameter variable. That one is valid. Even if type inference had made the list literal into `JSArray<double>`, it would still have worked.

**Comment by floitschG** [comment]
I just tried to reproduce, but (at least on trunk) the given program worked without problems.

**Comment by vsmenon** [comment]
Ahh, didn't actually see the code on my phone - now I can.  :-)

I cannot repro though.  That code works for me without exception on trunk and 1.25.0-dev.4.0.  It should be just fine with or without the suggested `<num>`.

@Blimster - are you sure there is nothing else to the program and that is exactly what is throwing?

**Comment by Blimster** [comment]
@vsmenon - You are right. The exception was caused a little bit deeper in my code. Here is the code snipped to reproduce the exception.

```dart
void main() {
  f([1.0]);
}

void f(List<num> p) {
  p as List<double>;
}
```

`[1.0]` is a list of doubles. So I thought, I could cast it to `List<double>`, even if the doubles are stored in a `List<num>`.

**Comment by vsmenon** [comment]
Ahh, that makes sense.  Here's what's going on.  In this statement:

```
f([1.0]);
```

the type of the list is actually unspecified.  Dart strong mode infers the type (which DDC reifies).  It uses both the contents (`1.0` here) and the context (`f` expects `List<num>`) to infer a type.  The context happens to take precedence.  The reason for that was to allow this:

```
void f(List<num> p) {
  p.add(42);
}
```

If `p` was actually a `List<double>`, this would throw (since we don't auto coerce `int` to `double`).

You can avoid this by explicitly typing the list:

```
f(<double>[1.0]);
```

That supersedes both the contents and the context.

**Comment by Blimster** [comment]
Ok, I didn't know that context is used to infer types. Is there any documentation about the rules of type inference?

From my point of view, this issues can be closed.
