### ISSUE TITLE
building dartlang on solaris fails

### ISSUE THREAD

**Issue by vanpupi** [dart-lang/sdk#30069]
I try to build dartlang following https://github.com/dart-lang/sdk/wiki/Building but it fails on my solaris zone. 
Everything is available (g++, python27,....) but the build fails with:

Unknown platform: sunos5

There are a lot of files which are checking on the os, so a list where solaris would need to be added int the code (or a new build script) would be nice.

**Comment by mraleph** [comment]
Solaris is not a supported operating system for Dart VM at the moment.

**Comment by vanpupi** [comment]
Difficult to understand. Solaris doesn't necessary mean sparc. It should be possible to run this on x86_64 solaris as well. 
If the code available, it should be possible to build it.

Can you indicate which specific code is needed, as this can be easily foreseen.

**Comment by mraleph** [comment]
There are plenty of OS specific code in the VM in addition to architecture specific one. 

Certainly, supporting x86_64 Solaris is simpler than supporting Sparc. But you will still need to look through a bunch of OS specific code and make it work for Solaris, e.g. some files that need to be copied and specialized for Solaris.

https://github.com/dart-lang/sdk/blob/master/runtime/vm/os_linux.cc
https://github.com/dart-lang/sdk/blob/master/runtime/vm/os_thread_linux.cc
https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_linux.cc
https://github.com/dart-lang/sdk/blob/master/runtime/bin/socket_base_linux.cc
https://github.com/dart-lang/sdk/blob/master/runtime/platform/utils_linux.h

**Comment by vanpupi** [comment]
I will check out this code. 
I also saw that in a lot of py-scripts the os check is done over and over again. 
Which ones are necessary to adapt to add the sunos5 so that the build can succeed?

**Comment by mraleph** [comment]
The best strategy might be just to search for linux in build scripts and put sunos5 next to it everywhere.
