### ISSUE TITLE
Add a code fix for "the method x is not defined but a constructor is"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30077]
This compiler error was so useful that I expected there would be a code-fix to insert `new` for me, but it appears not :(

![Code fix](https://user-images.githubusercontent.com/1078012/27876941-c59964fa-61b0-11e7-8785-61983f4447f9.png)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2965063002/

**Comment by DanTup** [comment]
That was quick! Thanks 😁
