### ISSUE TITLE
Several warnings when building platform.dill

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30072]
These warnings were introduced with 62bc61b367b14bfe3a265eaddcce0574e0059985.

We should revert this change until the code is free of warnings.

**Comment by lrhn** [comment]
I'd rather remove the warnings than revert the change that caused it.

**Comment by peter-ahe-google** [comment]
I won't be able to remove the warning on a short notice. I have several pressing issues on my plate already, and I don't think the changes made in 62bc61b367b14bfe3a265eaddcce0574e0059985 are high priority.

**Comment by rmacnak-google** [comment]
Please try to keep in mind that a correct GN build produces no output.

1bfd01c1f7a57fed039ce8ab95df2a5f14cf63b6

**Comment by peter-ahe-google** [comment]
Thank you, Ryan.

**Comment by leafpetersen** [comment]
Is there a plan/ETA for re-applying this?
