### ISSUE TITLE
Dart2JS doesn't tree-shake operators in some cases

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#30076]
DartSDK 1.25.0-dev.4.0
```dart
class A {
  String value;

  A(this.value);

  // used
  A mul(A other) {
    print('multiply-function');
    return new A('${int.parse(value) * int.parse(other.value)}');
  }

  // unused
  A operator * (A other) {
    print('multiply-operator');
    return new A('${int.parse(value) * int.parse(other.value)}');
  }
}

void main() {
  print(new A('1').mul(new A('2')));
}
```

In this case, `A`'s overridden `*` operator is not used, but it is being compiled to JS (release mode, formatted):
```javascript
...
["", "", , F, {
	"^": "",
	F: function() {
		P.u("multiply-function")
		P.u(new F.x(H.a(J.v(H.k("1", null, null), H.k("2", null, null)))))
	},
	x: {
		"^": "b;v:a<",
		l: function(a, b) {
			P.u("multiply-operator")
			return new F.x(H.a(J.v(H.k(this.a, null, null), H.k(b.gv(), null, null))))
		}
	}
}, 1]
...
```

This likely happens because `*` is being used in a non-constant expression in function`mul` (because using any other operator fixes this issue). However, `int.parse` can't return an instance of `A`, so compiler should detect unused code.

**Comment by lexaknyazev** [comment]
Adding `--trust-type-annotations` does the trick. Is it expected behavior? If so, this issue may be closed.

**Comment by sigmundch** [comment]
Yes indeed - dart2js is conservative because the `onError` handler can technically return anything. With `--trust-type-annotations` this is contained and we see that `int.parse` effectively does return an int.
