### ISSUE TITLE
Please, clarify description for Stream.skip()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30088]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/skip.html) for method dart:async:Stream.skip() reads:

> Stream&lt;T&gt; skip(
> int count
> )
> Skips the first count data events from this stream.
> 
> The returned stream is a broadcast stream if this stream is. For a broadcast stream, the events are only counted from the time the returned stream is listened to.

Please, clarify the folowing cases:
- errors in input stream (propagated or ignored or propagated only after first `count` data events or first error breaks everything?)
- input stream contains less events than `count`
- when the returned stream sends `done` event?
- when the input stream is unsubscribed?

**Comment by lrhn** [comment]
Addressed by 32a2d2079af113dfcca50e9388cc578d6073dc5a
