### ISSUE TITLE
Failure in observatory_ui/virtual_tree/element_test

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30087]
See, e.g., https://build.chromium.org/p/client.dart/builders/dart2js-win7-ie11ff-2-4-be/builds/4891/steps/dart2js-ff-observatory_ui%20tests/logs/stdio

Likely caused by commit 6be07a30bce87a884d0cf3cd904d28ee5ad2bc18

**Comment by whesse** [comment]
Please paste a permanent link to the log (the link inside brackets, to the logdog log) and include the key part of the log inline in the message:
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-win7-ie11ff-2-4-be%2F4891%2F%2B%2Frecipes%2Fsteps%2Fdart2js-ff-observatory_ui_tests%2F0%2Fstdout

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-mac10.11-safari-1-3-be%2F5720%2F%2B%2Frecipes%2Fsteps%2Fdart2js-safari-observatory_ui_tests%2F0%2Fstdout

value: window.onerror called: 
                    
                    http://127.0.0.1:61366/root_build/generated_tests/dart2js-safari-sdk/runtime_observatory_tests_observatory_ui_virtual_tree_element_test/element_test.js:2519:
                    Unsupported operation: NaN.floor()

**Comment by lrhn** [comment]
Please make that log link easily accessible on the waterfall.
I see no such link in my normal work-flow.

**Comment by whesse** [comment]
Click on the column, then on an individual build, or click on the build number.  I cannot change what appears in the waterfall popup.

**Comment by whesse** [comment]
There is also a browser plugin that will automatically show the new UI
