### ISSUE TITLE
Bogus hints from strong_mode_top_level_instance_getter

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#30085]
The following code:

```dart
import 'dart:async';

class Bar {
  final stream = new StreamController<int>().stream;
}
```

Produces this hint:

```
  hint • The type of 'stream' can't be inferred because of the use of the instance getter 'stream' at test.dart:4:46 • strong_mode_top_level_instance_getter
```

This seems bogus: the type of the getter is clearly `Stream<int>`.

Verified as of 1.25.0-dev.4.0.

**Comment by scheglov** [comment]
WAI. See [the specification](https://github.com/dart-lang/sdk/blob/8f2be46aac7705ab6a1024a795aaf977519a8be2/docs/language/informal/toplevel-inference.md). Search for `Note: specifically, references to instance fields and instance getters are disallowed here.`

**Comment by nex3** [comment]
@leafpetersen What's the motivation behind this behavior? It's very counterintuitive.

**Comment by leafpetersen** [comment]
This is going away.  See here for more discussion:  https://github.com/dart-lang/sdk/issues/29221

The motivation was to avoid some implementation difficulties around ordering of inference (note that top level declarations and instance fields can be mutually recursive).  We've decided that the impact on user code was too large and are pushing forward with a more general recursive implementation in the new front end.  In the meantime, the old front end will have slightly inconsistent behavior in some hopefully very rare corner cases.
