### ISSUE TITLE
callable mock objects are not implemented

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30108]
```dart
class Foo {
  int call() => 1;
}
class MockFoo extends Mock implements Foo {}

Foo foo = new MockFoo();
when(foo.call()).thenReturn(2);
foo();  // runtime error in DDC: "foo is not a function"
```

**Comment by jmesserly** [comment]
When we search for "call" methods to decide if a class is callable, I suspect we only search for concrete ones. There's an implied call method, because of the presence of `noSuchMethod` and an implemented interface.

**Comment by vsmenon** [comment]
Note, if we explicitly type `foo` as `dynamic`, it works as expected.

The comment here is not quite right in the mock / interface case:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/compiler/code_generator.dart#L1839

**Comment by jmesserly** [comment]
yeah, I think we can extend the search for "call" to include interfaces. That will also nicely pick up the nSM case. (since nSM is only relevant when a "call" method is present)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2977943002/

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2975273002/
