### ISSUE TITLE
Please, clarify description for Stream.skipWhile()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30101]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/skipWhile.html) for dart:async:Stream.skipWhile() reads:

> Stream&lt;T&gt; skipWhile(
> bool test(
> T element
> )
> )
> Skip data events from this stream while they are matched by test.
> 
> Error and done events are provided by the returned stream unmodified.
> 
> Starting with the first data event where test returns false for the event data, the returned stream will have the same events as this stream.
> 
> The returned stream is a broadcast stream if this stream is. For a broadcast stream, the events are only tested from the time the returned stream is listened to.

Please, clarify the case if `test` throws error.

**Comment by lrhn** [comment]
Addressed by 32a2d2079af113dfcca50e9388cc578d6073dc5a

**Comment by alsemenov** [comment]
Is it true, that after `test` is failed first time, the `test` is not called anymore for next events?

**Comment by lrhn** [comment]
Yes.
