### ISSUE TITLE
GN generation step for SDK is very slow due to copy_tree.py invocations

### ISSUE THREAD

**Issue by jamesr** [dart-lang/sdk#30105]
Generating ninja files for the Dart SDK takes 1.6-2.6 seconds in a Fuchsia build on OS X (depending on how things parallelize).  Almost all of that time is spent shelling out to copy_tree.py 31 times.  None of these are individually very expensive, but the overhead of shelling out to a subprocess is 40-70ms which adds up.  A more efficient way to accomplish this at GN generation time would be to run one script with a bunch of arguments, although that might be tricky to structure cleanly.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2992353002/
