### ISSUE TITLE
Dart Analyzer producing incorrect error reports

### ISSUE THREAD

**Issue by jwt-sgg** [dart-lang/sdk#30113]
I had been following this bug: https://github.com/dart-lang/sdk/issues/29889#issuecomment-310622504
But I appear to be having a different issue since using the latest dev SDK release fixed the problem other users were seeing.  

I have projects that import packages from local directories using the following pubspec.yaml dependencies.

dependencies:
  browser: any
  dragon:
    path: ../dragon

The applications will build and run fine, but the Dart Analyzer reports errors in any file that is a 'part of' the application library (the file with main seems to be analyzed fine though).  It appears the imported libraries from local directories are not being loaded for the application files and hence the types declared in those libs are not found.

**Comment by zoechi** [comment]
What Dart version? Any concrete error messages.

**Comment by jwt-sgg** [comment]
I see it in 1.24.0 and 1.25.0-dev.4.0.0.  It started when I switched from 1.22.1 to 1.24.0 (1.22.1 did not have this problem).

The errors are that Dart Analyzer is misreporting "Undefined Class 'X'", and "Classes can only extend other  classes", etc.  Basically the analyzer doesn't know any of the imported types from my local directory pacakages/libs.

**Comment by bwilkerson** [comment]
Can you confirm that the paths in the `.packages` file are valid? (Just trying to rule out one possible source of error.)

**Comment by jwt-sgg** [comment]
Yes, they are valid.  The apps build and run without any problems.

**Comment by natebosch** [comment]
Parts seem to be working with the current analyzer. If you are still having this issue against the latest SDK please add a comment with repro instructions and we can take a look.
