### ISSUE TITLE
Please, clarify description for Stream.periodic()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30122]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/Stream.periodic.html) of dart:async:Stream.periodic() reads:

> Stream.periodic(
> Duration period, [
> T computation(
> int computationCount
> )
> ])
> Creates a stream that repeatedly emits events at period intervals.
> 
> The event values are computed by invoking computation. The argument to this callback is an integer that starts with 0 and is incremented for every event.
> 
> If computation is omitted the event values will all be null.

According to description of class [Duration](https://api.dartlang.org/stable/1.24.2/dart-core/Duration-class.html), Duration instances can be negative. Please, clarify the behaviour of Stream.periodic() if `period` is negative. Does it cause error or treated as zero value?

**Comment by srawlins** [comment]
@lrhn I just tried a `Stream.periodic` with a negative Duration, and found that it ~~works~~ doesn't crash 😝 .

Is this a bug? I think I'd be in favor of disallowing a negative Duration...
