### ISSUE TITLE
Support for Macports?

### ISSUE THREAD

**Issue by paxperscientiam** [dart-lang/sdk#30126]
Hello!

As per [this (last comment)](https://trac.macports.org/ticket/52322), it does not seem possible to create a "port" of the sdk.

Is there a workaround for this [issue](https://www.chromium.org/developers/how-tos/get-the-code/working-with-release-branches)?:
>Note: it is usually NOT possible to sync and build a release branch (i.e. with consistent third_party DEPS); refer to the internal documentation (go/ChromeReleaseBranches) for that. The instructions below show how to check out a release branch only for a specific project (e.g. src.git).

Thank you.

**Comment by rmacnak-google** [comment]
I don't think that issue with Chromium's release branches is relevant for Dart. It should be possible to reproduce any Dart release by checking out the relevant commit from this repository and running gclient sync.

**Comment by a-siva** [comment]
Marking as resolved.
