### ISSUE TITLE
git cl upload presubmit check should not look at files that aren't being uploaded

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#30129]
`git cl upload` fails because two files residing my repo directory (not part of the git repo, just sitting there) are not formatted.

```
$ git status
On branch meta
Your branch is ahead of 'origin/master' by 1 commit.

Changes not staged for commit:
	modified:   CHANGELOG.md
	modified:   pubspec.yaml

no changes added to commit
$ git commit -am "Bump meta to 1.1.0"
[meta eed6dc4] Bump meta to 1.1.0
 2 files changed, 22 insertions(+), 1 deletion(-)
$ git cl upload
=====================================
NOTICE: Rietveld is being deprecated. You can upload changes to Gerrit with
  git cl upload --gerrit
or set Gerrit to be your default code review tool with
  git config gerrit.host true
=====================================
Running presubmit upload checks ...

** Presubmit ERRORS **
File output does not match dartfmt.
Fix these issues with:
/Users/srawlins/code/dart-repo3/sdk/tools/sdks/mac/dart-sdk/bin/dartfmt -w \
/Users/srawlins/code/dart-repo3/sdk/7641.dart \
/Users/srawlins/code/dart-repo3/sdk/d.dart

Presubmit checks took 3.1s to calculate.
```

A) Neither of those files are checked in.
B) Neither of those files are part of this commit.

**Comment by jacob314** [comment]
Closing as I don't think this will ever be above the line in terms of implementation priority.

Feel free to reopen if this is higher priority than I realise. I would generally expect the right solution is to add a directory to the .gitignore if you should really be able to upload a commit without including the changes.
Similarly, formatting the 7641.dart and d.dart file in the example you give doesn't seem like a bad solution unless these are files that should be in the .gitignore.
