### ISSUE TITLE
Better analyzer error messages for constants

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#30125]
For this example
```dart
main() {
  const bool a = const A(1).value == 1;
  print(a);
}

class A {
  final int value;
  const A(this.value);
}
```
The analyzer says:
```
$ dartanalyzer test.dart
Analyzing test.dart...
    error • Const variables must be initialized with a constant value at test.dart:2:18 • const_initialized_with_non_constant_value
1 error found.
```

Comparing this with e.g. dart2js:
```dart
$ dart2js test.dart
test.dart:2:18:
Error: Not a compile-time constant.
  const bool a = const A(1).value == 1;
                 ^^^^^^^^^^^^^^^^
test.dart:2:18:
Error: Not a compile-time constant.
  const bool a = const A(1).value == 1;
                 ^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

Here it is crystal clear what is not a valid compile-time constant.

**Comment by srawlins** [comment]
CC @kallentu this was not labeled with 'analyzer-constants'; if you're interested. I noticed the behavior is the same today.

**Comment by kallentu** [comment]
This should be more specific now actually. On my most rebased version of Dart locally, that example code produces `CompileTimeErrorCode.CONST_EVAL_PROPERTY_ACCESS [26, 16, "The property 'value' can't be accessed on the type 'A' in a constant expression."`

**Comment by srawlins** [comment]
Oh excellent, I thought I noticed no behavior change on the master channel at DartPad, but that's not a perfect way of testing. Sounds like we can close?

**Comment by kallentu** [comment]
I usually test with DartPad too! I only noticed this when I tried to debug it.

But yes, closing.
