### ISSUE TITLE
IntelliJ: New `Function` syntax not supported?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30120]
This is fine in DartPad, run in the VM/dart2js/etc:

```dart
Map<String, void Function()> get events => {};
```

Not so in IntelliJ:

<img width="340" alt="screen shot 2017-07-09 at 3 36 20 pm" src="https://user-images.githubusercontent.com/168174/27998141-6298366a-64bc-11e7-8750-3df8e0745172.png">

Turns out I was running an older version on my MacBook at home (2016.3.7). It would be ideal if the Dart plugin for IntelliJ was able to tell that the SDK I had installed (1.24.2) was too new for the version of IntelliJ I had installed.

**Comment by matanlurey** [comment]
**EDIT**: I updated, and there is still no syntax recognition:

```
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
Licensed to Dart Language / Matan Lurey
Subscription is active until October 5, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.2
```

<img width="350" alt="screen shot 2017-07-09 at 3 43 01 pm" src="https://user-images.githubusercontent.com/168174/27998165-586ea7ea-64bd-11e7-8ea5-966ffdcd92a6.png">

**Comment by alexander-doroshko** [comment]
@matanlurey Looks like you have an old Dart SDK configured in your IntelliJ IDEA 2017.1.5 project. I do not see any problems with this syntax and SDK 1.23+.

**Comment by matanlurey** [comment]
I will check when I get home, you are likely correct @alexander-doroshko. I guess this does bring back to the original point, I'd really like IntelliJ/The Dart Plugin to help me out here - i.e. see I have `1.24.0` installed but I'm still using < that.

**Comment by jwren** [comment]
We currently do support this, in IntelliJ, go to

`File > Settings > Languages & Frameworks > Dart > Enable "Check SDK update"`

choose in the combo between `Stable channels` or `Stable and Dev channels`

It is enabled by default, perhaps it got disabled somehow?

**Comment by matanlurey** [comment]
Interesting. I'll assume I disabled it.
