### ISSUE TITLE
rolling flutter engine to top of tree Dart sdk results in some tests failing intermittently

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30128]
Rolling flutter engine to top of tree Dart SDK results in some tests failing intermittently and needs investigation. This is a blocker as flutter would like to roll forward.

**Comment by goderbauer** [comment]
When running a flutter app with a local engine I am also seeing random hangs: sometimes after `flutter run` the Android screen just gets stuck at a black screen when starting the app. Sometimes that app stops responding while scrolling through a list, etc.

**Comment by a-siva** [comment]
Is this a local engine without rolling to top of tree Dart SDK?

**Comment by goderbauer** [comment]
Yeah, that's for the local engine as it is currently checked in to flutter/engine.

**Comment by a-siva** [comment]
looks like https://github.com/flutter/engine/pull/3862 should resolve this issue
