### ISSUE TITLE
Typo in lastAccessed() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#30137]
Please see https://api.dartlang.org/stable/1.24.2/dart-io/File/lastAccessed.html

> Returns the date and time when the file was last accessed, if the information is available.
> Throws a FileSystemException if the operation fails.

Please, change it to

> Returns a Future< DateTime > that completes with the date and time when the file was last accessed, if the information is available.
> If the operation fails then the future completes with a FileSystemException .

The same issue exists in [lastModified()](https://api.dartlang.org/stable/1.24.2/dart-io/File/lastModified.html), [setLastAccessed()](https://api.dartlang.org/stable/1.24.2/dart-io/File/setLastAccessed.html) and [setLastModified()](https://api.dartlang.org/stable/1.24.2/dart-io/File/setLastModified.html) documentation

**Comment by srawlins** [comment]
Fixed.
