### ISSUE TITLE
Can't set breakpoint in test

### ISSUE THREAD

**Issue by NevRA** [dart-lang/sdk#30136]
I can't set breakpoint in Dartium in below code: 

```
@TestOn("browser")
import 'package:test/test.dart';

void main() {
  group('simple tests', () {
    test("2+2", () {
      expect(2+2, 4);
    });
  });
}
```

It worked fine in 1.21 but since 1.23+ (maybe 1.22 too) it doesn't work.

To confirm: 
1) serve project: **pub serve test --port 8081** 
2) run test with pause: **pub run test -p dartium --pub-serve=8081 test/app_test.dart --pause-after-load**
3) try to set breakpoint in Dartium on line: **expect(2+2, 4);** and release pause in Dartium

P.S. Breakpoints in regular code works perfect.
P.P.S Issue related only for browser tests, vm tests works ok.

**Comment by avilladsen** [comment]
I've run into the same issue. I'm on Dart 1.24.2 with Dartium 50. Setting breakpoints works as expected in Chrome (version 61 beta).

Could this be a regression of #26080?

While unsuccessfully trying to find a way around it, I made a [demo](https://github.com/avilladsen/test_dartium_breakpoint_skip) for this issue if that's helpful.

**Comment by zoechi** [comment]
Adding a `print('xxx');` and setting a breakpoint there often works for me when other breakpoints don't work. I know, an ugly hack, but it helps to unblock.
Dartium is going away anyway.

**Comment by avilladsen** [comment]
No luck with the `print('xxx');` trick.
Fair point that Dartium is going away. I'd be happy to move away from it as soon as I can replace content_shell with headless chrome (waiting on dart-lang/test#391).
