### ISSUE TITLE
Unable to catch DDC run-time errors in tests

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#30134]
Below is an excerpt from an Angular test I'm working on that works in Dartium. I'm using [package:test](https://pub.dartlang.org/packages/test) to expect that a particular error is thrown from Angular-generated code upon component creation.

```dart
import 'dart:async';

import 'package:angular/angular.dart';
import 'package:angular_test/angular_test.dart';
import 'package:test/test.dart';

void main() {
  test('example', () async {
    final testBed = new NgTestBed<TestExampleComponent>();
    // Test bed creation invokes a method on null when attempting to listen to the output
    // stream, resulting in a 'NoSuchMethodError'.
    expect(testBed.create(), throwsInAngular(new isInstanceOf<NoSuchMethodError>()));
  });
}

@Component(
  selector: 'example',
  template: '',
)
class ExampleComponent {
  @Output()
  Stream<String> get output => null;
}

@Component(
  selector: 'test-example',
  template: '<example (output)="onOutput(\$event)"></example>',
  directives: const [ExampleComponent],
)
class TestExampleComponent {
  void onOutput(String event) {}
}
```

The issue is in DDC, the error that's thrown is no longer a `NoSuchMethodError`, but instead a JavaScript `TypeError` (not the same as the Dart `TypeError`). I can solve this problem by using a catch-all try-catch block, but this is highly undesirable as it could mask unexpected errors.

Is there a solution for catching DDC run-time errors?

**Comment by vsmenon** [comment]
https://codereview.chromium.org/2979613002
