### ISSUE TITLE
need basic documentation for key types in dart:html

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#3013]
A few key elements in dart:html (e.g., Element, Node, Event) could use some actual documentation. What we've got looks very incomplete.

**Comment by srawlins** [comment]
[Element](https://api.dartlang.org/1.12.1/dart-html/Element-class.html) is pretty well documented now.

[Node](https://api.dartlang.org/1.12.1/dart-html/Node-class.html) and [Event](https://api.dartlang.org/1.12.1/dart-html/Event-class.html) seem to have well-documented methods as well; the classes themselves are not documented.

Should this issue be closed? specified? split?
