### ISSUE TITLE
use custom uri in front_end unit tests

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30141]
Consider using custom uris instead of `file:` Uris + a memory file system.

Reason for doing so: make unit tests more self explanatory, since all data would be coming from an in-memory file system.

Reasons for not doing so: making sure we do have coverage of file:* URIs in our unit tests. We have coverage via the vm tests, but it might be nice to cover some coverage ourselves. An option though could be to simply use a tmp folder for that purpose.

Note: there are several dependencies in the compiler on `file:*` Uris that we need to get rid of first befor we make this change. We should do that regardless. I know at least source_loader.dart has a check about `file:*` URIs

**Comment by peter-ahe-google** [comment]
Note: we're not testing file URIs by making mock URIs that have the scheme "file". Instead we're adding hacks somewhere to *prevent* testing of file URIs.

**Comment by sigmundch** [comment]
Forgot to mark this as closed. Fix landed in bc1dd524bab5e89b07fcd37077af33fcb84e43f7
