### ISSUE TITLE
Please, clarify description for Stream.takeWhile()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30144]
The description for method dart:async:Stream.takeWhile() reads:

> Stream&lt;T&gt; takeWhile(
> bool test(
> T element
> )
> )
> Forwards data events while test is successful.
> 
> The returned stream provides the same events as this stream as long as test returns true for the event data. The stream is done when either this stream is done, or when this stream first provides a value that test doesn't accept.
> 
> Stops listening to the stream after the accepted elements.
> 
> Internally the method cancels its subscription after these elements. This means that single-subscription (non-broadcast) streams are closed and cannot be reused after a call to this method.
> 
> The returned stream is a broadcast stream if this stream is. For a broadcast stream, the events are only tested from the time the returned stream is listened to.

It is possible to conclude from the description that if `test` throws error, then it is considered as `test` failure and events are not added to returned stream no more. However it is not clear whether the error (thrown by `test`) is added to the returned stream.

**Comment by srawlins** [comment]
The text for takeWhile has been updated to include content about this stream throwing: https://api.dartlang.org/dev/2.1.0-dev.7.0/dart-async/Stream/takeWhile.html
