### ISSUE TITLE
Remove AbstractClassInstantiationError class

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30148]
My understanding is that in 2.0, it's a compile error to instantiate an abstract class, so there is no corresponding runtime semantics for this and no runtime error. Given that, this class shouldn't be needed any more, should it?

@leafpetersen @floitschG

**Comment by lrhn** [comment]
Agree. On our list of 2.0 changes.

**Comment by munificent** [comment]
Looks like this didn't happen in 2.0 and it's a breaking change to remove it now, so closing this out.
