### ISSUE TITLE
Consider extracting Flutter vmservice_sky into separate .dill from platform.dill

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30158]
As a follow-up to https://codereview.chromium.org/2972323002, consider extracting vmservice packages into separate .dill and use that .dill when compiling Flutter script like so:
```
var options = new CompilerOptions()                                            
     ..target = new FlutterFastaTarget(new TargetFlags())                       
     ..packagesFileUri = Uri.base.resolve('.packages')                          
     ..compileSdk = true                                                        
     ..linkedDependencies = [UriToPlatformDill, UriToVmServiceDill])]           
     ..onError = errorHandler; 
var scriptDill = kernelForProgram(scriptEntryUri, options);
```

**Comment by a-siva** [comment]
We are not going with a separate vmservice_io.dill file, command line VM has been switched to have just one vm_platform.dill file (see https://github.com/dart-lang/sdk/commit/c29b19fb34d545caa227f6c16fa06bddc6da1114).
So closing this
