### ISSUE TITLE
analyzer/test/src/summary/resynthesize_kernel_test fails on windows

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30165]
https://codereview.chromium.org/2980863003/ seems to be the culprit.

Not sure whether "file:///" references in resynthesize_kernel_test.dart makes sense on Windows.

**Comment by scheglov** [comment]
It does not fail per se, it times out.
@stereotype441 marked the test [as slow](https://github.com/dart-lang/sdk/commit/66b4efaa306e5ed9b55423b884b6378491cf80a2).

**Comment by aam** [comment]
Got you, thanks!
