### ISSUE TITLE
Run strong mode analyzer tests on analyzer bot

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30182]
The current "analyze tests" step on the analyzer bots is:

```
./tools/test.py --mode=release --arch=x64 --use-sdk --compiler=dart2analyzer \
    --runtime=none --progress=buildbot --report --time --write-debug-log \
    --write-test-outcome-log --copy-coredumps
```

Now that we are starting to migrate tests to Dart 2.0, it would be good to run analyzer tests in strong mode, at least for the tests that support it. That means splitting the above into two separate steps:

**"analyze tests"**

```
./tools/test.py --mode=release --arch=x64 --use-sdk --compiler=dart2analyzer \
    --runtime=none --progress=buildbot --report --time --write-debug-log \
    --write-test-outcome-log --copy-coredumps \
    --exclude-suite=corelib_2,language_2,lib_2
```

**"analyze strong tests"**

```
./tools/test.py --mode=release --arch=x64 --use-sdk --compiler=dart2analyzer \
    --runtime=none --progress=buildbot --report --time --write-debug-log \
    --write-test-outcome-log --copy-coredumps \
    --strong corelib_2 language_2 lib_2
```

**Comment by whesse** [comment]
We already have analyzer-strong bots, that run test.py on all test suites, and have the builder tag "strong".
They already run test.py --strong.

It is the status files in the test suites that say that 

[ $compiler == dart2analyzer && $builder_tag == strong ]
*: Skip # Issue 28649

So we just need to add the new strong test suites to the default test suites, and say they should be skipped if the builder tag is not "strong".  Do we want the other components, like dart2js and the vm, to run the new test suites?

**Comment by whesse** [comment]
I see there are already status file markers in language_2 that should make test.py pass with no failures when running the tests on various runtimes, with and without the --strong option.  So why aren't we just running these new test suites on all bots?

**Comment by munificent** [comment]
We are. I'll close this out.

Eventually, we may want to split things up so that we don't bother to run the "_2" tests on weak mode at all to minimize the amount of status file churn we have to do, but, so far, it doesn't seem too bad.
