### ISSUE TITLE
Incorrect MutableRectangle with width or height equal double.NEGATIVE_INFINITY

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#30186]
According to https://api.dartlang.org/stable/1.24.2/dart-math/MutableRectangle/MutableRectangle.html

> The width and height should be non-negative. If width or height are negative, they are clamped to zero.

the creation a MutableRectangle with negative width or height should create a MutableRectangle with width or height clamped to zero.
However, the test below
```dart
import "dart:math";

main() {
  MutableRectangle r = new MutableRectangle(2, 1,
      double.NEGATIVE_INFINITY, double.NEGATIVE_INFINITY);
  print(r);
}
```
reports
```dart
Rectangle (2, 1) NaN x NaN
```

**Comment by lrhn** [comment]
Good catch. We do some tricky double/int math to ensure that the zero has the same type as the original (so -4 becomes -0 and -4.0 becomes -0.0). That math apparently isn't clever enough to handle infinities.
