### ISSUE TITLE
Please, clarify description for Stream.toList()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30187]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/toList.html) for method dart:async:Stream.toList() reads:

> Future&lt;List&lt;T&gt;&gt; toList()
> Collects the data of this stream in a List.

Please, clarify 
 - how errors in the stream are handled? Ignored or used to complete the returned future?
 - the completion value of returned future instance. The future is completed with `List<T>` instance. What is the order of elements in returned list. Which elements are included into the list?
 - when the returned future is completed?

**Comment by alsemenov** [comment]
The same problems are observed in [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/toSet.html) of method Stream.toSet()

**Comment by natebosch** [comment]
The doc comment now reads:

>Collects all elements of this stream in a List.
>
>Creates a List<T> and adds all elements of the stream to the list in the order they arrive. When the stream ends, the returned future is completed with that list.
>
>If the stream contains an error, the returned future is completed with that error, and processing stops.

I think the `toSet()` documentation needs to be updated with similar wording.
