### ISSUE TITLE
Please, clarify description for Stream.where()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30199]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/where.html) for method dart:async:Stream.where() reads:

> Stream&lt;T&gt; where(
> bool test(
> T event
> )
> )
> Creates a new stream from this stream that discards some data events.
> 
> The new stream sends the same error and done events as this stream, but it only sends the data events that satisfy the test.
> 
> The returned stream is a broadcast stream if this stream is. If a broadcast stream is listened to more than once, each subscription will individually perform the test.

Plase, clarify how errors thrown by `test` are handled.
Is the first error stop further event processing?
Are errors added to returned stream? 
Are they considered as `test` failure for given event?

**Comment by natebosch** [comment]
Today the docs say "If the test function throws, the data event is dropped and the error is emitted on the returned stream instead."
