### ISSUE TITLE
roll dart_style in dev channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30190]
As discussed in #30164 in the future we'd roll dart_style in sync with the tools/sdks/

Since this is just the first time around, at this moment the dart_style version in DEPS has already been updated in `master`. @whesse - could you please cherry-pick a similar roll in the dev channel and copy the dartfmt binaries under `tools/sdks/`?

Thanks!

**Comment by whesse** [comment]
The default binaries have already been updated to 1.25.0-dev.7.0, which has dart_style at 1.0.7, which is the current version, so this is already done.
