### ISSUE TITLE
language/vm/optimized_stacktrace_test crashed on simarm64-mac

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30198]
The test language/vm/optimized_stacktrace_test crashed on vm-noopt-simarm64-mac-be in builds 2783-2786. Note that the same test also crashed on Windows (#28276).

Reported error: `uncaught exception std::bad_alloc`, in [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-noopt-simarm64-mac-be%2F2786%2F%2B%2Frecipes%2Fsteps%2Ftest_vm%2F0%2Fstdout).

**Comment by eernstg** [comment]
Same test crashes on [vm-precomp-android-release-3-3-be/builds/3420](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-precomp-android-release-3-3-be%2F3420%2F%2B%2Frecipes%2Fsteps%2Ftest_vm%2F0%2Fstdout), but with a native stack dump.

Yet another: [vm-precomp-win-simarm64-3-4-be/builds/2245](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-precomp-win-simarm64-3-4-be%2F2245%2F%2B%2Frecipes%2Fsteps%2Ftest_vm%2F0%2Fstdout), this time with a `Fail` rather than crashing.

**Comment by johnniwinther** [comment]
The test is now skipped in `$compiler == precompiler && $runtime == dart_precompiled` by https://codereview.chromium.org/2978303002/

**Comment by alexmarkov** [comment]
`language/vm/optimized_stacktrace_test` and `language_2/vm/optimized_stacktrace_test` are currently passing (and not flaky) on all configurations.
