### ISSUE TITLE
Change DDC bots to use d8 instead of drt

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30193]
Dartium content shell is going away. DDC doesn't actually use the "Dart-ness" of drt. It just used it since it can also execute ES6 JS. Once d8 is updated (#29794), the bots should use that as the runtime.

**Comment by jmesserly** [comment]
Should we also have a DDC+Chrome bot to test browser behavior? I think some tests require a browser to be present

**Comment by munificent** [comment]
Instead of d8, we changed the bots to use Chrome, but that accomplishes the key goal of moving off drt.
