### ISSUE TITLE
Re-enable core-dump archiving on Linux

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30205]
The bots need to be re-configured after a reboot. Add back the line here after that:

https://github.com/dart-lang/sdk/blob/master/tools/utils.py#L736

/cc @whesse @mkustermann

**Comment by mkustermann** [comment]
Closing in favor of one bug which covers all of the remaining issues with coredumps: https://github.com/dart-lang/sdk/issues/31065
