### ISSUE TITLE
Add package:mockito to mirror

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30204]
https://github.com/dart-lang/mockito.git

See https://github.com/dart-lang/sdk/commit/fcc205e1a6cf95fac35aee4b772831f422dfab5d

**Comment by zanderso** [comment]
Dependencies directly on github in our DEPS file can block Dart rolls into Fuchsia. In the future please create the mirror first before landing changes to the DEPS file. See the comment here:

https://github.com/dart-lang/sdk/blob/master/DEPS#L29

And the detailed procedures here:

https://github.com/dart-lang/sdk/wiki/Adding-and-Updating-Dependencies#third-party-source-dependencies

@whesse @devoncarew @a-siva

**Comment by athomas** [comment]
Fixed a long time ago.
