### ISSUE TITLE
Analyzer  exception on build

### ISSUE THREAD

**Issue by vnerozin** [dart-lang/sdk#30200]
Dart 1.24.2
WebStorm 2017.2
macOS 10.12.5

AnalysisException: Cannot compute LIBRARY_ELEMENT for Instance of 'AssetBasedSource'
Caused by Mismatch in DeclarationResolver while resolving google_maps|lib/util/async.dart
Could not find element with name "" at 637
Path to root: FunctionExpressionImpl, DefaultFormalParameterImpl, FormalParameterListImpl, FunctionExpressionImpl, FunctionDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3464:5)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2833:5)
#2      DeclarationResolver._findAtOffset (package:analyzer/src/generated/resolver.dart:2780:7)
#3      DeclarationResolver.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:2536:33)
#4      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5265:15)
#5      DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3420:20)
#6      RecursiveAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:1497:10)
#7      DeclarationResolver.visitDefaultFormalParameter (package:analyzer/src/generated/resolver.dart:2432:40)
#8      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3415:15)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7749:20)
#10     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4765:17)
#11     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:1587:10)
#12     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4761:15)
#13     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5270:18)
#14     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:1611:10)
#15     DeclarationResolver.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:2544:43)
#16     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5265:15)
#17     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5116:26)
#18     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:1599:10)
#19     DeclarationResolver.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:2525:37)
#20     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5109:15)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7749:20)
#22     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452:21)
#23     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449:10)
#24     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445:15)
#25     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2328:10)
#26     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1080:33)
#27     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#28     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#29     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#30     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#31     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#32     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:696:12)
#33     ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:167:25)
#34     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#35     ListIterable.toList (dart:_internal/iterable.dart:218)
#36     ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:168:10)
#37     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:109:26)
#38     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:187:15)
#39     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:109:14)
#40     _rootRunUnary (dart:async/zone.dart:1128)
#41     _CustomZone.runUnary (dart:async/zone.dart:1012)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#43     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#44     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#45     _Future._completeWithValue (dart:async/future_impl.dart:478)
#46     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#47     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:187:15)
#48     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:99:48)
#49     _rootRun (dart:async/zone.dart:1120)
#50     _CustomZone.run (dart:async/zone.dart:1001)
#51     _CustomZone.runGuarded (dart:async/zone.dart:901)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

package:analyzer/src/context/context.dart 728:7           AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 696:12          AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 167:25   ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                            ListIterable.toList
package:code_transformers/src/resolver_impl.dart 168:10   ResolverImpl._performResolve.<fn>
dart:async                                                _Future.then
package:code_transformers/src/resolver_impl.dart 154:28   ResolverImpl._performResolve
package:code_transformers/src/resolver_impl.dart 90:14    ResolverImpl.resolve.<fn>
dart:async                                                _Future.whenComplete
package:code_transformers/src/resolver_impl.dart 88:37    ResolverImpl.resolve
package:code_transformers/src/resolvers.dart 63:17        Resolvers.get
package:build_barback/src/analyzer/resolver.dart 48:44    BarbackResolvers.get
dart:async                                                new Future.microtask
package:build_barback/src/analyzer/resolver.dart 47:61    BarbackResolvers.get
package:build/src/builder/build_step_impl.dart 54:61      BuildStepImpl.resolver
package:source_gen/src/builder.dart 31:36                 GeneratorBuilder.build
dart:async                                                new Future.microtask
package:source_gen/src/builder.dart 30:43                 GeneratorBuilder.build
package:build/src/generate/run_builder.dart 35:21         runBuilder.buildForInput
dart:async                                                new Future.microtask
package:build/src/generate/run_builder.dart 29:51         runBuilder.buildForInput
dart:async                                                Future.wait
package:build/src/generate/run_builder.dart 41:31         runBuilder.<fn>
dart:async                                                runZoned
package:build/src/builder/logging.dart 12:38              scopeLog
package:build/src/generate/run_builder.dart 41:9          runBuilder
dart:async                                                new Future.microtask
package:build/src/generate/run_builder.dart 25:48         runBuilder
package:build_runner/src/generate/build_impl.dart 554:13  BuildImpl._runBuilder
dart:async                                                _StreamIterator.moveNext
package:build_runner/src/generate/build_impl.dart 442:34  BuildImpl._runPhases.<fn>
dart:async                                                new Future.microtask
package:build_runner/src/generate/build_impl.dart 440:50  BuildImpl._runPhases.<fn>
dart:async                                                Future.wait
package:build_runner/src/generate/build_impl.dart 440:20  BuildImpl._runPhases
dart:async                                                new Future.microtask
package:build_runner/src/generate/build_impl.dart 429:42  BuildImpl._runPhases
package:build_runner/src/logging/logging.dart 19:28       logWithTime
dart:async                                                new Future.microtask
package:build_runner/src/logging/logging.dart 16:70       logWithTime
package:build_runner/src/generate/build_impl.dart 146:26  BuildImpl.runBuild.<fn>
dart:async                                                _asyncThenWrapperHelper
package:build_runner/src/generate/build_impl.dart 78:28   BuildImpl.runBuild.<fn>
package:stack_trace                                       Chain.capture
package:build_runner/src/generate/build_impl.dart 78:11   BuildImpl.runBuild

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
