### ISSUE TITLE
[1.24.0 - 1.24.2] Analysis Server fails on nested pubspecs

### ISSUE THREAD

**Issue by PiMihai** [dart-lang/sdk#30215]
I am having an analyzer / packages related issue on 1.24.0 - 1.24.2 when I try having a multi-project solution. While pub seems to get the packages just fine and all projects are running as expected, when I try importing a package, the analyzer cannot seem to find it (import "package:" has no suggestions either)

1.23.0 works fine under the same scenario.

I am using the builds available via chocolatey.
I am using the DartCode VSCode extension by Danny Tuppeny.

Sample solution layout :

![image](https://user-images.githubusercontent.com/2708308/28413219-7946500e-6d4f-11e7-8b44-1d5b663a0732.png)
(Windows 10 Insider Build 16241)

The picture demonstrates this with a hosted package (test) but the same happens with git or local packages.

This seems to be related to #22907 

Please let me know if you need any further information.
Thank you!

**Comment by georgelesica-wf** [comment]
We're seeing this problem in mixed Dart+Go projects. FWIW I am seeing it in both Gogland and VSCode on Mac OS. I can provide more details if necessary.

**Comment by srawlins** [comment]
This has been re-vamped several times. Presuming fixed. Please file a new issue if this is still a problem on a recent version of Dart.
