### ISSUE TITLE
Some fasta front end tests are failing and need investigation

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30212]
The following tests are failing after the recent change to Dart_LoadScript to account for working with dart front end. Not sure why they are failing, needs investigation.

front_end/test/fasta/bootstrap_test: Skip
front_end/test/fasta/compile_test: Skip
front_end/test/fasta/strong_test: Skip

**Comment by sigmundch** [comment]
Hi Siva - could we revert the change to Dart_LoadScript until we have a fix?

These 3 tests internally run hundreds of tests and provide the core test coverage we have for the front-end.

**Comment by a-siva** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/000bec45acb7260b82ccc570a5652012a6c4b2a4
