### ISSUE TITLE
Possible vm crash in dart::Intrinsifier::Intrinsify

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30222]
In a [log from vm-mac-release-ia32-be build 21010](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-mac-release-ia32-be%2F21010%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fvm-mac-release-ia32-be%2F21010%2F%2B%2F%2A%2A%2Fstderr), a `python ../../tools/observatory_tool.py ..` command fails (search 'thread 1303' to find it in the log) with a stack trace that includes `VMService.messageHandler`, `dart::DRT_CompileFunction`, and `dart::Intrinsifier::Intrinsify`.

The python command just prints a usage message and `ninja: build stopped: subcommand failed`, but the stack trace seems to imply that the process that caused this failure is a Dart VM, hence the `area-vm` label.

The issue seems to be unrelated to the commit where it occurred (3e563c6e9e3814948b49eb4ef408471829f69b85).

**Comment by mraleph** [comment]
Note enough information to act at this point.
