### ISSUE TITLE
subtle capture bug involving type parameter bounds

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30236]
if this test is added to strong_mode_test:
```dart
  test_genericMethod_nestedCaptureBounds() async {
    await resolveTestUnit(r'''
class C<T> {
  /*=T*/ f/*<S extends T>*/(/*=S*/ x) {
    new C<S>().f/*<int>*/(3);
    new C<S>().f; // tear-off
    return null;
  }
}
''');
    MethodInvocation f = findIdentifier('f/*<int>*/(3);').parent;
    expect(f.staticInvokeType.toString(), '(int) → S');
    FunctionType ft = f.staticInvokeType;
    expect('${ft.typeArguments}/${ft.typeParameters}', '[S, int]/[T, S extends T]');

    expectIdentifierType('f;', '<S₀ extends S>(S₀) → S');
  }
```
it fails, as we end up thinking the function type is `<S₀ extends S₀>(S₀) → S`

There are some bugs in `FunctionTypeImpl.toString()` (searching for free vars does not visit bounds, and it does not do a simultaneous substitution) however fixing those does not seem sufficient. I think the bug is in TypeParameterMember.from.

**Comment by srawlins** [comment]
I'm closing this as stale; if there is a real-world bug (outside the proposed unit test), we can follow that.
