### ISSUE TITLE
GLB/LUB do not handle generic functions

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30237]
for example:
```dart
void main() {
  var isEven = new DateTime.now().millisecond.isEven;
  var f = isEven ? <T>(T t) => t : <U>(U t) => t;
  print(f<int>(42)); // The method '(<bottom>) → Object' is declared with 0 type parameters, but 1 type arguments were given
}
```
even worse:
```dart
void main() {
  var isEven = new DateTime.now().millisecond.isEven;
  var f = isEven ? <T>() => 42 : <U>() => 42;
  print(f());
}
```
prints the internal closure used for generic method dispatch (this function object should never be exposed to user code):
```
Closure: NativeJavaScriptObject from: () => {
    return 42;
  }
```

**Comment by scheglov** [comment]
This still fails.
```dart
typedef F1 = T Function<T>();
typedef F2 = U Function<U>();

main() {
  F1 a;
  F2 b;
  F1 c = a ?? b;
}
```

`error: A value of type '() → Object' can't be assigned to a variable of type '<T>() → T'. (invalid_assignment at [test] bin/test.dart:7)`

But when I change both `a` and `b` to be either `F1` or `F2`, then their types become identical objects, and returned from `getLeastUpperBound(t1, t2)` as `t1`, which does have type parameters.

Found this while working on a change for nullability, which we don't check yet, but we get non-identical `FunctionType` instances, so don't take the shortcut.

**Comment by jmesserly** [comment]
Yeah, wow, _functionLeastUpperBound does not handle generic functions at all, same for GLB. (Not sure why I thought it was fixed, oops!)
