### ISSUE TITLE
Analyzer ignores type tests for generics with restrictions

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#30230]
This works:

```dart
class Foo {
  int get length => 0;
}

class Bar<T> {
  bool test(T obj) => obj is Foo && obj.length > 3;
}
```

However, the following

```dart
class Foo {
  int get length => 0;
}

abstract class Baz {}

class Test<T extends Baz> {
  bool test(T obj) => obj is Foo && obj.length > 3;
}
```

fails with `The getter 'length' isn't defined for the class Baz`. 

I can have a class that extends Foo and implements Baz so I would think the second block is also valid.

**Comment by mehmetf** [comment]
It is worth noting that the following works:

```dart
class Foo {
  int get length => 0;
}

abstract class Baz {}

class Test<T extends Baz> {
  bool test(T obj) => obj is Foo && (obj as Foo).length > 3;
}
```

**Comment by leafpetersen** [comment]
This is working as intended currently.  Instance checks like `obj is Foo` only promote if the static type of `obj` is a supertype of `Foo`.  Here, `T extends Baz`, and `Foo` is not a subtype of `Baz`, so we don't promote.  

The reason for this is that if we promote to `Foo`, then you lose access to the `Baz` methods.  

We've discussed always promoting anyway, and we've discussed implementing additional type system features that would allow both sets of methods to be available, but we have no concrete plans to change this.  For the time being this is working as intended.

cc @munificent @eernstg @lrhn @floitschG @bwilkerson

**Comment by mehmetf** [comment]
Thanks for clarifying. The particular instance where this is appearing can be alleviated if we allow restrictions to be more expressive. Like in Java:

```java
interface Foo {
  boolean foo();
}

interface Bar {
  int bar();
}

class SuperBar implements Foo, Bar {
  public boolean foo() { return true; }
  public int bar() { return 1; }
}

class Baz<T extends Foo & Bar> {
  final T baz;

  Baz(T baz) {
    this.baz = baz;
  }
}


public class Test {
  public static void main(String [] args) throws Exception {
    new Baz<>(new SuperBar());
  }
}
```

Has this been discussed for Dart?

**Comment by leafpetersen** [comment]
It has been discussed.  When I mentioned "additional type system features" above, this is basically what I was referring to.  `A & B` can be thought of as an intersection type, and we've talked speculatively about using intersection types in some form or another (possibly limited).  There are a lot of usability concerns around them though.  There are no concrete proposals around this that I'm aware of right now.
