### ISSUE TITLE
Publish pkg/analyzer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30239]
* I'm hitting this issue w/ the new Function syntax. the package: https://github.com/dart-lang/sdk/issues/30228
* Would love to get support in for the latest pkg/argrs - https://github.com/dart-lang/sdk/commit/4d642466fbb70f2fbd290d93b858102239459212
* Blocking this PR for angular - https://github.com/dart-lang/angular/pull/550

**Comment by kevmoo** [comment]
CC @natebosch

**Comment by kevmoo** [comment]
@devoncarew good opportunity to bump the pubspec constraint on the SDK, too 😄

**Comment by bwilkerson** [comment]
There have been breaking changes, so we will need to publish an alpha version (or update the whole world, which is undesirable given that there are several more breaking changes that are likely to occur in the very near future). Would an alpha version work for you?

**Comment by devoncarew** [comment]
What @bwilkerson said; sounds like we'll either need to backport the fix for #30228 to `0.30.0` (branch from when we published and patch that fix in), or push a new alpha release. We're planning on doing an alpha shortly anyway - the angular analyzer needs it - so this path would be the easiest for us.

**Comment by natebosch** [comment]
IMO waiting for an alpha will be OK - if there are breaking changes then any package using `source_gen` would need to have updates to be able to use this anyway - for now we'll probably avoid thew new syntax where it breaks us.

**Comment by pq** [comment]
FWIW I'm planning to push `0.31.0-alpha.0` later this AM (https://codereview.chromium.org/2986863002/) 👍 .

**Comment by pq** [comment]
UPDATE: `analyzer` is published; compatible `test` on the way (https://github.com/dart-lang/test/issues/670).

**Comment by bwilkerson** [comment]
@kevmoo Does the 0.31.0-alpha.0 version solve your needs?

**Comment by kevmoo** [comment]
I think so. We need to bump to 1.25.0-dev, too

The only failures here - https://travis-ci.org/dart-lang/angular/builds/258682543 – are because we're running Dartium (which hasn't been revved since 1.24)

**Comment by kevmoo** [comment]
I still want to leave this open to track publishing 0.31.0

**Comment by pq** [comment]
Update [10/23]: when a new analyzer goes out, we can land https://github.com/dart-lang/linter/pull/816, which updates linter to stop using the deprecated `enableAssertInitializer` flag.

**Comment by kevmoo** [comment]
Could linter just use the alpha that's out there?

I'm guessing most users just what's in the SDK, right?

**Comment by pq** [comment]
So we are currently using the latest analyzer but you bring up a good point: we could theoretically publish a fresh one.  To do that, I expect we'll need a new `kernel` and `front_end` as well...
