### ISSUE TITLE
Tests failing with dartanalyzer in non-strong mode: corelib_2 and ddc.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30245]
Three tests have started failing on the dartanalyzer in non-strong mode, with MissingCompileTimeError failures.

in tests/corelib_2/corelib2.status:
[ $compiler == dart2analyzer && !$strong ]
symbol_reserved_word_test/05: MissingCompileTimeError
symbol_test/04: MissingCompileTimeError

in pkg/pkg.status:
[ $compiler == dart2analyzer ]
dev_compiler/test/codegen_test: MissingCompileTimeError

**Comment by whesse** [comment]
The tests started failing with commit https://github.com/dart-lang/sdk/commit/f334284967ea5be01f64ec2653fef1018bc9055c by @munificent

**Comment by jcollins-g** [comment]
I'm about to create a similar situation with duration2_test, as it is a static-only verification test from a dart 2.0 perspective.  @munificent, is it alright to just have Skip for non-strong mode in this case?

**Comment by eernstg** [comment]
Note that the added status entry for symbol_test describes the correct behavior for the analyzer in Dart 1.x (non-strong) mode:
```
[ $compiler == dart2analyzer && !$strong ]
symbol_test/04: MissingCompileTimeError # Issue 30245
```
In this situation, the type of the variable `y` is `dynamic` and hence `print(new Symbol(y));` is not a compile-time error, and hence it is _not_ "an issue" that this error is missing.

Conversely, the type of `y` is inferred as `int` in strong mode, and hence `new Symbol(y)` is not type correct. That is a compile-time error in strong mode so `//# 04: compile-time error` is fine in that case.

So we could update the status file to say
```
[ !$strong ]
symbol_test/04: SkipByDesign # Only a compile-time error in strong mode`
```
I created [a CL](https://codereview.chromium.org/2991793002) doing that, which would partially resolve this issue.

**Comment by munificent** [comment]
> Note that the added status entry for symbol_test describes the correct behavior for the analyzer in Dart 1.x (non-strong) mode

This may be true, but we are no longer testing Dart 1.x. Our tests are for 2.0. If the test doesn't correctly represent a 2.0 expectation, the test should be changed. :)

**Comment by eernstg** [comment]
Right, which is exactly why I suggested setting this up such that the test fits strong mode, and all we need to do when no tools run `!$strong` anymore is to delete the `[ !$strong ]` section of the status file (because no runs will match that section anyway) and all the `$strong` requirements elsewhere (because they'll be always-true).

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/32501 addresses the DDC part of this issue

**Comment by vsmenon** [comment]
Is this something we still care about?

**Comment by munificent** [comment]
Pretty sure we don't care about non-strong mode anymore. :)
