### ISSUE TITLE
Fasta code is has strong mode analyzer errors after interface fix

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30244]
The CL https://codereview.chromium.org/2981183003 fixed strong mode type checking for all interface inheritance, and exposed errors in the analyzer code.

The test dart2js/analyze_test is now marked as "Slow, Fail" in tests/compiler/dart2js/dart2js.status
The test pkg/front_end/test/fasta/analyze_test is now marked as failing in pkg/pkg.status.
This needs to be fixed so we can restore strong-mode testing of fasta and analyzer

**Comment by whesse** [comment]
The log showing the errors is at https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-kernel-mac-release-x64-be%2F619%2F%2B%2Frecipes%2Fsteps%2Ffront-end_tests%2F0%2Fstdout

And the errors are:
FAILED: none-vm-checked release_x64 pkg/front_end/test/fasta/analyze_test
Expected: Pass Slow 
Actual: Fail
CommandOutput[vm]:
stdout:
tools/patch_sdk.dart utils/kernel-service/kernel-service.dart
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:254:3: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE] Invalid override. The type of 'ErroneousElementX.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:253:3: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE] Invalid override. The type of 'ErroneousElementX.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/ssa/kernel_ast_adapter.dart:367:3: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE] Invalid override. The type of 'KernelAstAdapter.getConstructorBody' ('(Constructor) → MemberEntity') isn't a subtype of 'KernelToElementMapForBuilding.getConstructorBody' ('(Constructor) → FunctionEntity').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1698:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1360:45: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'ClassElement.origin' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1864:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1820:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1360:45: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1698:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1335:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1864:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1820:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1859:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1815:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1353:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1708:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.declaration' ('() → Element') isn't a subtype of 'ClassElement.declaration' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'ClassElement.patch' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1325:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1353:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1864:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1820:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1698:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1360:45: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'ClassElement.patch' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1353:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1703:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1855:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'ClassElement.origin' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1811:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.implementation' ('() → Element') isn't a subtype of 'ClassElement.implementation' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1855:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1811:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.implementation' ('() → Element') isn't a subtype of 'ClassElement.implementation' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1855:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1811:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.declaration' ('() → Element') isn't a subtype of 'ClassElement.declaration' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1855:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1811:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'ClassElement.patch' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1703:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'ClassElement.patch' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.declaration' ('() → Element') isn't a subtype of 'ClassElement.declaration' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1703:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'ClassElement.origin' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1703:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1353:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1859:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1815:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1335:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1708:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1325:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.declaration' ('() → Element') isn't a subtype of 'ClassElement.declaration' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.implementation' ('() → Element') isn't a subtype of 'ClassElement.implementation' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1708:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1325:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1859:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1815:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1057:39: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'ClassElement.origin' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1698:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1360:45: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1042:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.implementation' ('() → Element') isn't a subtype of 'ClassElement.implementation' ('() → ClassElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1335:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1864:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1820:30: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1859:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1815:28: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1325:37: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1335:34: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'ElementCommon.patch' ('() → Element') isn't a subtype of 'FunctionElement.patch' ('() → FunctionElement').
/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/compiler/lib/src/serialization/modelz.dart:1708:32: error:
[STRONG_MODE_INVALID_METHOD_OVERRIDE_FROM_BASE] Base class introduces an invalid override. The type of 'Element.origin' ('() → Element') isn't a subtype of 'FunctionElement.origin' ('() → FunctionElement').
Running analyzer took: 0:01:52.971425.
stderr:
Non-empty output from analyzer.
#0      analyzeUris (package:testing/src/analyze.dart:260:5)
<asynchronous suspension>
#1      Analyze.run (package:testing/src/analyze.dart:40:12)
#2      SuiteRunner.analyze (package:testing/src/run.dart:222:21)
<asynchronous suspension>
#3      main.<anonymous closure> (package:testing/src/run_tests.dart:158:45)
<asynchronous suspension>
#4      withErrorHandling (package:testing/src/error_handling.dart:16:19)
<asynchronous suspension>
#5      main (package:testing/src/run_tests.dart:143:33)
#6      main (file:///b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/front_end/test/fasta/analyze_test.dart:12:10)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Command[vm]: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/pkg/front_end/test/fasta/analyze_test.dart
Took 0:01:54.540699
Short reproduction command (experimental):
    python tools/test.py -m release --checked pkg/front_end/test/fasta/analyze_test
Done none-vm-checked release_x64 pkg/front_end/test/fasta/analyze_test: fail
Done none-vm-checked release_x6

**Comment by sigmundch** [comment]
Note many of these failures are in the dart2js codebase, and they appear as false negatives to me.

I am reaching out on the original CL to follow up on this. I believe the fix might be in analyzer and not on the app itself.

**Comment by peter-ahe-google** [comment]
Just like we can't break google3 when updating the analyzer, neither can we break existing tests.

One procedure to follow is to run tests before submitting a CL and filing P1 bugs against code bases that need to be updated. When I've worked on updating javac in google3, and when I first implemented type checking in dartc, this worked well and people were really responsive to updating their code.

**Comment by sigmundch** [comment]
agreed, I believe it was not detected so clearly because the analyzer tests on the dart2js bots were already red earlier that day from a different problem (an accidental broken import when Johnni moved a dart2js test file).

The fix is on its way
