### ISSUE TITLE
No type arguments in RedirectingFactoryBody

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30258]
So, this code cannot be represented.

```dart
class C<T, U> {
  factory C() = D<U, T>.named;
  C._();
}
class D<T, U> extends C<U, T> {
  D.named() : super._();
}
```

**Comment by peter-ahe-google** [comment]
Thank you for reporting this.

**Comment by peter-ahe-google** [comment]
Work in progress: [CL 2996063002](https://codereview.chromium.org/2996063002).

The CL reifies the type arguments, but doesn't yet use that information to compute the correct type arguments when calling the constructor that is the final redirection target.

**Comment by stereotype441** [comment]
This appears to have been taken care of.  As of ec9c927b180f35f17d94f7fae7c97e94e9482056 we can now use `RedirectingFactoryBody.typeArguments`.
