### ISSUE TITLE
Dev compiler should intrinsify Angular's looseIdentical

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30250]
looseIdentical is performance critical in angular code, and DDC doesn't optimize away the overhead of the call.  The compiler should intrinsify this.  We've discussed doing this via an annotation on the method.

**Comment by natebosch** [comment]
AFAICT Angular no longer uses this method, and is also mostly focused on dart2js for optimizations at this level.

@matanlurey let me know if there are any patterns that the angular team feels needs to be a priority for optimization in DDC.
