### ISSUE TITLE
Is switch on .runtimeType valid?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30257]
This code:
```dart
class  A {}

void main() {
  var x = new A();
  switch (x.runtimeType) {
    case A: print("hello");
  }
}
```
Is accepted by the analyzer, and runs on the VM and DDC with no errors.  Dart2js rejects it with the following error:

```
leafp-macbookpro:sdk leafp$ rundart.sh dart2js -o test.js ~/tmp/test.dart
../../../tmp/test.dart:6:10:
Error: 'case' expression type 'TypeImpl' overrides 'operator =='.
    case A: print("hello");
         ^
Error: Compilation failed.
```

Is this valid code and dart2js is buggy here, or is this invalid code that should be rejected statically or dynamically?

cc @sigmundch @lrhn @munificent

**Comment by sigmundch** [comment]
This has come up a few times in the past - @floitschG has a lot of additional context, @rakudrama had a proposal on how to fix this in dart2js.

See these older issues describing the underlying problem:
https://github.com/dart-lang/sdk/issues/17123
https://github.com/dart-lang/sdk/issues/17207
https://github.com/dart-lang/sdk/issues/21553

Note in particular discussions about canonicalization of generic types, and ideas about treating raw vs generic types differently in the dart2js implementation.

**Comment by leafpetersen** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/21553 .
