### ISSUE TITLE
InvalidType for generic closure

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30265]
```Dart
final f = <U, V>(U x, V y) => y;
```

Analyzer infers:
```Dart
final <U,V>(U, V) → V f;
```

Front-End infers:
```Dart
<U extends dart.core::Object, V extends dart.core::Object>(invalid-type, invalid-type) → invalid-type
```

**Comment by sigmundch** [comment]
I believe this is blocked on support for local type variables, which @peter-ahe-google is currently working on.

**Comment by sigmundch** [comment]
Turns out we also had #29798 to track this, I'll close this issue as a duplicate.
