### ISSUE TITLE
Notification.requestPermission() throws an exception every time in dartium

### ISSUE THREAD

**Issue by alxnddr** [dart-lang/sdk#30263]
Hi everyone, I have an issue with Notification.requestPermission() in dartium - it throws an exception all the time:
```VM507:1 Uncaught Unhandled exception:
type 'JSObjectImpl' is not a subtype of type 'Future' of 'function result' where
  JSObjectImpl is from dart:js
  Future is from dart:async

#0      Notification._requestPermission (dart:html:30767)
#1      Notification.requestPermission (dart:html:30774)
#2      PushSubscriptionService._ensureNotificationsEnabled
...
```
Dart SDK and Dartium 1.24.1

Am I doing something wrong?

**Comment by alxnddr** [comment]
Same with `window.navigator.serviceWorker.register(serviceWorkerUrl)`

**Comment by zoechi** [comment]
As a workaround until it is fixed
https://pub.dartlang.org/packages/service_worker
(and https://pub.dartlang.org/packages/pwa) provide a `package:js` based way to use this API

Not sure if it will be fixed. Dartium is or will be derprecated.
