### ISSUE TITLE
@required doesn't catch that a constructor isn't being called at all

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30261]
When you have a constructor with only named arguments, subclasses that don't have any constructors or don't call the constructor explicitly are defined to implicitly call the constructor with no arguments. However, `@required` isn't catching those cases.

```dart
class A { A({ @required this.foo }); final int foo; }
class B extends A { } // no error here
```

**Comment by srawlins** [comment]
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/30117; please follow along there.

**Comment by srawlins** [comment]
Duplicate of #30117
