### ISSUE TITLE
Dart Analyzer not recognizing package imports in Webstorm

### ISSUE THREAD

**Issue by arthurdaniel** [dart-lang/sdk#30274]
Analyzer Feedback from IntelliJ.

I am using WebStorm 2017.2  (172.3317.70, built on July 14, 2017) And the latest stable release of  Dart (1.24.2) and I am receiving errors for almost of my imports (except  dart core packages eg. dart:async). eg: 
                        error: Target of URI doesn't exist: 'package:charted/charted.dart'. 

 I have run pub get within WebStorm, and tried pub upgrade and pub get via command line as well. When this did not work I also tried pub cache repair with no prevail.  The errors seem to only affect the Dart analyser in Webstorm.

The application builds with no problems and all packages work fine when using pub build in terminal. This problem only arises when I upgraded dart and Webstorm.  When I make changes to the project the analysis server has to catch  up, and will often change its mind about whether or not the URI error  persists.   Since I have made no changes to my pubspec.yaml files or the project  itself, and the project still builds fine in cmd line, is this a  potential bug with analyser or perhaps Webstorm plugin?

**Comment by zoechi** [comment]
I have seen similar issues popping up several times recently at SO, Gitter, ..., and encountered it myself.
I was able to make it work again, but don't know what exactly made it work or how to produce it.

**Comment by bwilkerson** [comment]
It is likely a bug in analyzer, but I don't know where.

Given some directory `dir` that you are opening as the root of a project/module, and some library within `dir` that contains import directives, where is the `.packages` file relative to those two?

**Comment by arthurdaniel** [comment]
This is the general structure to my project. 

proj-dir/
   client/
      lib/
          components/
             app_component.dart
	     dashboard/
                dashboard_component.dart
          services/
      .packages
      web/
          main.dart
      pubspec.yaml
   server/
      lib/
      pubspec.yaml
      .packages

**Comment by bwilkerson** [comment]
And are you opening `proj-dir`? If so, there have been other reports that a bug is preventing us from correctly handling the case of having multiple subdirectories containing `.packages` files, and you might be running into that issue.

**Comment by arthurdaniel** [comment]
Yes I am, OK that may be the issue.  It's worth noting that before I updated Webstorm and dart, I was not experiencing this issue. I tried to roll back to the previous versions that I was using, but I still experience the same problem.

**Comment by arthurdaniel** [comment]
I am now using the latest dev build 1.25.0-dev.9.0 and I am no longer seeing this issue.

**Comment by bwilkerson** [comment]
I'm glad to hear that! I'll close this issue, assuming that the issue was fixed. Please open a new issue or add to this one if you have similar problems in the future.
