### ISSUE TITLE
Kernel generated by FE should have strong-mode type checks

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30270]
(this is not a new request, but I realized that we didn't have a tracking bug for it)

/cc @kmillikin @stefantsov

**Comment by sigmundch** [comment]
as discussed in our last sync up, our plan is to take the existing type inference implementation in the front-end, and include type checking and insertion of type checks at that point.

**Comment by stereotype441** [comment]
As of 9aa3a0eec0d1ab3841d294fe5aa89cd338f60828 I believe the front end inserts all the necessary runtime checks and forwarding stubs due to generic covariance.  I'm just beginning to work on adding runtime checks due to implicit downcasts.

**Comment by stereotype441** [comment]
As of 327adac2354a51d2b120662a7fc486c3dd27f91f I believe the front end inserts all the necessary runtime checks due to implicit downcasts.  Runtime check insertion is now complete.
