### ISSUE TITLE
Unused top-level private variables / constants are not caught by the analyzer

### ISSUE THREAD

**Issue by yyoon** [dart-lang/sdk#30286]
Just noticed that unused private global variables / constants are not caught by the analyzer.

Since these are meant to be only used within the same source file, I would expect these would be detected as UNUSED_ELEMENT and be reported by the analyzer.

**Comment by kevmoo** [comment]
I'm sure this exists somewhere already, but I totally agree.

**Comment by bwilkerson** [comment]
This appears to have been fixed. Please provide a test case if you're still seeing this on the latest 2.0 branch.
