### ISSUE TITLE
//utils/compiler:patched_dart2js_sdk target spams the console

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30282]
It looks like the change here https://github.com/dart-lang/sdk/commit/de7e14436c57649e5786c7aa60660c1959ff6975 adding //utils/compiler:patched_dart2js_sdk to the create_sdk target causes console spam during a successful SDK build.

```
[446/652] ACTION //utils/compiler:patched_dart2js_sdk(//build/toolchain/linux:clang_x64)
warning: patch not found for bool.fromEnvironment: external const factory bool.fromEnvironment(String name, {bool defaultValue : false});
warning: patch not found for int.fromEnvironment: external const factory int.fromEnvironment(String name, {int defaultValue});
warning: patch not found for String.fromEnvironment: external const factory String.fromEnvironment(String name, {String defaultValue});
```

Please ensure that a successful GN build produces no console output. Thanks!

**Comment by sigmundch** [comment]
Thanks Zach, I'll take a look - we were tracking this issue also in https://github.com/dart-lang/sdk/issues/30157

**Comment by sigmundch** [comment]
(it's a bug in the compiler rather an an issue in the libraries, that's why I left it emitting the output and not make the target fail)

**Comment by zanderso** [comment]
Thanks!
