### ISSUE TITLE
Update pkg/kernel dependency on pkg/args

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30281]
Currently excludes v1

**Comment by jensjoha** [comment]
It seems that you updated the dependency in b7a9f2ae7cd1e49eeef3457a8277533ee79c5c2b.
Can we close this issue?

**Comment by kevmoo** [comment]
Yup!

Fixed in https://github.com/dart-lang/sdk/commit/b7a9f2ae7cd1e49eeef3457a8277533ee79c5c2b
