### ISSUE TITLE
Requesting analyzer support for "trailing/closing tag" feature

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#30285]
We quickly explored the usefulness of ["closing tags" for Flutter code](https://github.com/Dart-Code/Dart-Code/issues/383), and our initial users seem to find it helpful. We'd like to explore how to do this "for real" which we believe requires help/support from the analyzer, in order to improve robustness of the feature and help make it available in IntelliJ.

I'll defer to @DanTup for further explanation and technical requests.

**Comment by DanTup** [comment]
The current implementation linked above uses getHovers to retrieve offset/length information for the constructor calls. To know where constructors are it uses a combination of highlights and outlines. The whole thing is rather inefficient!

The idea is to implement a new notification in the analysis server that can provide all of the require info for rendering these decorations for an entire file in a single message - something like an array of `int offset/int length/string label`.

With assistance, I hope to contribute this feature :-)

**Comment by DanTup** [comment]
This work is now pretty much complete (PRs #30332, #30372 and #30411). There may be some tweaks but I believe the API is stable (or at least, future changes will be non-breaking).

There are some cases where invalid code may result in misplaced labels (see #30370) though hopefully parser improvements will correct these in future.

@bwilkerson I think we're both happy any future changes will be non-breaking, so is it possible to bump the analyzer API version now? I think I'd like to ship an update to Dart Code to switch to this (though still behind a flag) to get some more feedback (eg. @devoncarew has concerns about this appearing in too many places).

**Comment by bwilkerson** [comment]
Alex seems to think the API is good for IntelliJ as well, so yes, I think we should bump the API level and call this done. Thanks for adding this!

**Comment by DanTup** [comment]
@bwilkerson Is it just a case of updating the spec and then re-running the generation script? I can send a PR, or if it's easier for you to do, feel free. Thanks!

**Comment by bwilkerson** [comment]
There's one other place to update, so I did it myself (https://codereview.chromium.org/3002513002/).

**Comment by DanTup** [comment]
Excellent; thanks!

> while still marked experimental

I'm not sure if you saw [my previous comment](https://github.com/dart-lang/sdk/pull/30332#issue-248250214) about this - experimental didn't seem to work on this (a notification) so it's not actually marked as such. I don't think it's a problem here (I don't expect any changes will be breaking), but want to make sure you realise!

**Comment by devoncarew** [comment]
> Note: This does not include experimental="true" because it didn't seem to work on notifications:
> Exception: analysis.closingLabels: Unexpected attribute in notification: experimental
> #0      ApiReader.checkAttributes.<anonymous closure> (file:///Users/danny/Dev/Google/sdk/pkg/analysis_server/tool/spec/from_html.dart:127:9)

Probably something we should add support for, just so we can message the stability of the APIs properly -

**Comment by bwilkerson** [comment]
Devon has updated the generator and marked the notification as experimental, so I think we can close this issue.

**Comment by DanTup** [comment]
Great; thanks! 👍

**Comment by sethladd** [comment]
Thank you all for the discussions, reviews, comments, and brainstorming!!

**Comment by DanTup** [comment]
Btw, I'm expecting to ship an update to Dart Code tomorrow that uses this API. I can see Flutter seems to already have this (I'm not sure how though, the SDK version looks like it's about 5 days old, yet the analysis server is returning 1.18.4!) so if you have the original preview flag turned on, it'll just switch over :-)

**Comment by DanTup** [comment]
I was mistaken; I was still pointing at the local analysis server =)

I'm going to hold off pushing the update until SDK 1.25.0-dev.10.0 is pushed so I can give it a final test before Dart Code switches over to it. I'll post back when I do, so people can try it out.

**Comment by DanTup** [comment]
I've shipped Dart Code v2.4.0. This includes an implementation of "closing tags" that uses the analysis server (you must be using at least `1.25.0-dev.11.0` which was released yesterday; flutter is also using it if you update).

It's still behind a flag (though there's a new flag name `dart.previewClosingLabels` since it's flutter-specific - the old flag still works) to get some more feedback (it now appears for all Dart!).

Please try it out and send feedback here -> https://github.com/Dart-Code/Dart-Code/issues/383
