### ISSUE TITLE
Dart Precomp VM crashes in tests

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#30289]
Test failures started in either 385b88f2894d9d5482ae27c0ea052e943c280750 or f32d1b2bcdf5647bdfb2001970e896934ecdcce5 but I don't see how either of them could be the cause. Supressions are 
regress_27671_test: RuntimeError
export_double_same_main_test: Skip  # Crashes
export_ambiguous_main_negative_test: Skip # Crashes
optimized_stacktrace_test: Skip # Crashes
export_ambiguous_main_negative_test: Skip # Crashes

**Comment by rmacnak-google** [comment]
The latter incorrect removed a status file header: https://github.com/dart-lang/sdk/commit/f32d1b2bcdf5647bdfb2001970e896934ecdcce5#diff-a55644977cabe5d21f8600c3a2593adfL143
