### ISSUE TITLE
element_classes_test contains-bad fails on Chrome

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#30291]
This test seems to be failing because we expect an exception on a query for empty string but aren't getting one. Though we do if we just do that exercise manually. So something is going on, and it's invalidating that whole test. Might be a Chrome 60 change.

**Comment by sigmundch** [comment]
this test is failing now on all browsers, I'm closing the bugs since, besides notifications, we are not really using the bug tracker to track the status of our tests.
