### ISSUE TITLE
Dependent project can't see ext imports to make suggestions

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30297]
### Reproduction steps:
Example project: https://github.com/JFixby/DartImportsExample

class B located in the ```project_a/lib/folderB1/class_b_file.dart```

class D located in the ```project_d/lib/class_d_depends_on_b.dart``` 
content:
```
class D {
  B instanceOfB = new B();
}

```

### What was done
   open suggestions

### What is expected
  to see proposal to add ```import 'package:project_a/folderB1/class_b_file.dart';```

### What is actually happening
no suggestions

![image](https://user-images.githubusercontent.com/1580663/28777536-d5ec89c2-75fb-11e7-802c-062ac957210d.png)

has to do a manual import instead

### Setup
IDEA version: community 2017.2
Dart plugin:  172.3317.48

**Comment by bwilkerson** [comment]
@scheglov I think this will be covered by the work you're planning on doing in this area.

**Comment by JFixby** [comment]
I suggest import resolution should be managed by IDE and a runtime environment, not by a .dart file.

**Comment by zoechi** [comment]
@JFixby what do you mean by

> I suggest import resolution should be managed by IDE and a runtime environment, not by specifying a file path in a .dart file.

**Comment by zoechi** [comment]
Ok, it's described in more detail in #30299

**Comment by JFixby** [comment]
This issue is a the real pain in a butt.

![image](https://user-images.githubusercontent.com/1580663/29334742-c1b0197e-8208-11e7-98e8-339165a24e8f.png)

**Comment by JFixby** [comment]
Can you please add a temporary feature where I can click on a desired file with a command like `copy import path` so the buffer will contain full import path.

Right now I'm clicking `copy relative path`
![image](https://user-images.githubusercontent.com/1580663/29334880-35b00d52-8209-11e7-8ebe-bde9b84a2115.png)

and it gives me something like `lib/api/io/hash.dart` that I have to past into my code and make it an actual import statement by adding the `import "package:bla_bla_blla...";`

**Comment by zoechi** [comment]
Seems to be a dup or related to #21931 perhaps also #24257

**Comment by scheglov** [comment]
I believe this was fixed.
Twice.
First time with available declarations.
And then re-implemented using `NotImportedContributor`.
