### ISSUE TITLE
new HashMap(equals: ...) gives weird results in VM and dart2js

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#30303]
If you use `new HashMap(equals: (a,b) => null)` ([docs](https://api.dartlang.org/stable/1.19.1/dart-collection/HashMap/HashMap.html)), you can get weird results in dart2js ([DartPad](https://dartpad.dartlang.org/26958c12a8823964063639edf7e971d5)):

```dart
import 'dart:collection';

void main() {
  var x = new HashMap(equals: (a,b) => null);
  x..[1]=2..[1]=3..[1]=5..[2]=7;
  print(x);  // => {1: null, 1: null, 1: null, 2: null}

  var y = new HashMap();
  y..[1]=2..[1]=3..[1]=5..[2]=7;
  print(y);  // => Instance of '_HashMap'
}
```

But different, and also weird, results in the VM:

```
$ dart a.dart
{1: 5, 1: 3, 1: 2, 2: 7}
{1: 5, 2: 7}
```

😮 

Basically:

* None of the values should be `null` when I never inserted a null (dart2js).
* I don't think HashMap should allow double entries... (VM)

Let me know if I should restrict this ticket to one backend, and open a 2nd ticket for the other, or if this is acceptable behavior 😄 .

**Comment by lrhn** [comment]
Working as "intended". The compare functions should return a boolean. Returning `null` will be a type error with null safety, and should throw in Dart 2.0.
If it doesn't throw, but treat `null` as false (Dart 1 style), then it's an inconsistent equality function which claims that *no* key is equal to what you are trying to look up (or add). That precisely explains the behavior.
