### ISSUE TITLE
export pkg:front_end/src/fasta/kernel/utils serializeProgram, move it to pkg:kernel

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30300]
serializeProgram is used by Flutter tools app to write kernel binary into a file. Currently serializeProgram is internal to front_end package, so it makes sense to export it. 
Also like @sigmundch [suggested](https://github.com/flutter/flutter/pull/11395#discussion_r129429334) it makes sense to move it to kernel package.

**Comment by jensjoha** [comment]
It doesn't seem to be used in flutter anymore - is this still a valid issue?

**Comment by aam** [comment]
Yeah, it's obsolete now.
