### ISSUE TITLE
Dart linter non_constant_identifier_names NPE

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#30304]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4073.35`
- `1.25.0-dev.7.0`
- `IU-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-83-generic unknown, screens 3840x2160`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.7.0, server version 1.18.2, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl in FormalParameterListImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object

**Comment by alexeieleusis** [comment]
The referenced file contains paths and filenames that I prefer not to share publicly, ping me if you think they are needed. I didn't notice when this error happended, it was in the IDE log window.

**Comment by bwilkerson** [comment]
I suspect that this is fixed in bleeding edge; it appears to be due to a bug related to having formal parameters without names (when using the new function type syntax). Does that seem reasonable?

@pq Just FYI

**Comment by pq** [comment]
Aha!  I think this one was fixed in https://github.com/dart-lang/linter/commit/ced90f3bb2e182cba56811e553b5673869b71128 and is in `0.1.35` which I just pushed into the SDK this AM.
