### ISSUE TITLE
When geolocation is disabled dart.sdk die [ At least in Firefox ]

### ISSUE THREAD

**Issue by dnp1** [dart-lang/sdk#30313]
Hey guys,

I'm a firefox user concerned about privacy, so I've followed the steps [here](https://wiki.archlinux.org/index.php/Firefox/Privacy#Disable_geolocation)  to improve my privacy.

One of those steps is disable geo localization on firefox.

So, when I run my app in firefox I get, in console:

`TypeError: navigator.geolocation is undefined`

**Comment by sigmundch** [comment]
Thanks for filing the issue! @dnp1 - we might need more details to understand where this is coming from so the right people can take a look.

Is `navigator.geolocation` used in your app? Can you show us a small example that reproduces this problem so we can run that locally? How do you run the app? In particular, I'm not sure if you were running it using DDC (the dart dev-compiler) or dart2js.

Based on your title, the fact that you mentioned dart_sdk leads me to believe this might be in DDC?

**Comment by dnp1** [comment]
Hello,

Theres no explicit reference to navigator.geolocation.

I'm running just **pub serve**.

My application is an angulardart web app

**Comment by vsmenon** [comment]
We need to fix our polyfill here:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/tool/input_sdk/private/ddc_runtime/runtime.dart#L83

It should check to see if `window.navigator.geolocation` is defined first.

**Comment by eloyleonardo** [comment]
If you completely disable geo localization in browser (e.g. in firefox change the config geo.enabled to false) the error keep occurring.
