### ISSUE TITLE
DDC memory leak in worker mode

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30314]
While implementing DDC batch mode for compiling tests (with a slightly different interface, but practically equivalent to the existing `--persistent_worker` used by bazel) memory usage seems to grow forever. This causes noticeable performance degradation when the process gets in the 1-2GB.

My guess would be some Analyzer cache, given that it has a lot of global caches, and DDC does not. But it could be something else.

**Comment by jmesserly** [comment]
CC @vsmenon @jakemac53 ... have we seen anything like this in our bazel builds? It seems like it could be affecting performance.

It's really sneaky too ... when I'm watching our ~4000 language tests scroll by, you can see it slow down as it goes, with successive compiles taking longer and longer. And you can see the `dart` process memory usage grow from very small to very large.

**Comment by jmesserly** [comment]
A few more notes:
* you don't have to reach 4000 compiles to encounter problems, as test.dart uses workers. I'm seeing problems starting from 300-500 range
* we are using `AnalysisEngine.instance.clearCaches()` but that appears to be insufficient
* for now I'm capping it at 100 compiles before test.dart restarts the worker.

**Comment by jakemac53** [comment]
We have periodically had complaints about this for all our workers that use the analyzer, we could track the number of compiles done in the worker fairly easily and make them shut themselves down, but we need to experiment to see how well blaze handles it when workers die like that.

**Comment by jmesserly** [comment]
Yeah ... I'm also curious to investigate this with Observatory and see if I can figure out what might be going on.

**Comment by jakemac53** [comment]
I did a bit of digging with the angular bazel workers, I don't know how to use observatory very well but it seems likely that the [StringCanonicalizer](https://github.com/dart-lang/sdk/blob/c2f7f52e42009e7b1598d61d272af55f9712c663/pkg/front_end/lib/src/fasta/scanner/string_canonicalizer.dart#L24) class is the culprit, or at least a good place to start looking? The [StringToken](https://github.com/dart-lang/sdk/blob/56402976cd9538e0f9ff5dc250439bbb0973594b/pkg/front_end/lib/src/fasta/scanner/token.dart#L107) class has a static final instance of that and I think that might be causing issues.

**Comment by vsmenon** [comment]
Thanks, Jake - it looks like the leak is tied to switching to the new frontend analyzer.

@sigmundch @peter-ahe-google - Is there anything we should do to explicitly clear state?  We're seeing memory leaks across separate runs (same VM) in blaze worker mode.  See Jake's previous comment.

We've been calling this in between compilation requests:

https://github.com/dart-lang/sdk/blob/6c757957db8c31969c8a4c7b6e1693e1d93555bf/pkg/dev_compiler/bin/dartdevc.dart#L68

Jake - are you seeing similar in the summary worker as well?

**Comment by sigmundch** [comment]
We use the scanner as a ephemeral component in the front_end codebase (we create a new instance and toss it after tokenizing a file). @danrubel - in our integration with analyzer, are we keeping it around in memory instead? could we switch to create a new scanner like we do in the FE?

**Comment by vsmenon** [comment]
If it's in memory, should it be cleared in `clearCaches`?  This is what DDC is calling:

```
AnalysisEngine.instance.clearCaches();
```

**Comment by jakemac53** [comment]
@vsmenon Yes we do the same call to `AnalysisEngine.instance.clearCaches()` everywhere afaik.

**Comment by jakemac53** [comment]
fwiw, I tried adding a `clear` method to `StringCanonicalizer` and a `static clearCanonicalizedStrings` method to `StringToken` which calls clear on its static instance, and then adding a call to that to the `clearCaches` method. This seemed to help some but it didn't completely resolve the issue.

**Comment by jakemac53** [comment]
Actually, this does seem to keep the ddc workers under 1GB of ram, the ng2 workers are still seeing memory leaks but probably due to some other issue.

**Comment by danrubel** [comment]
@sigmundch The current fasta scanner integration with analyzer calls `fasta.scanString`. That method creates a new fasta scanner, performs the scan, discards the scanner, and only returns the results.

**Comment by sigmundch** [comment]
sorry I didn't look close enough to see the cache was in a static it all makes sense now. Glad to hear that @jakemac53 workaround deals with the issue.
