### ISSUE TITLE
[Feature Request] GZip snapshot files

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#30315]
Problem: snapshots are too damn high... er.. big..  (>1MB).
Solution: Add an option to gzip them!
Note: The dartvm is linked against zlib already, so win-win?

**Comment by zanderso** [comment]
@a-siva @rmacnak-google

**Comment by rmacnak-google** [comment]
To clarify, do you mean script snapshots or app snapshots? Is the concern here network/download size or disk size?

App snapshots use file-mapped memory and the bulk of their content is used directly, so I don't think it makes sense for the version on disk to be compressed, though it would make sense to compress them during a download.

For script snapshots, the whole thing is converted anyway, so embedder-level gzipping seems reasonable. The standalone VM already has gzip as you mention, and it even uses to decompress Observatory.

**Comment by jtmcdole** [comment]
Script right now, since we only *download* script snapshots. I don't think we can yet have an app snapshot for applications using native extensions.
