### ISSUE TITLE
Reset terminal settings to their original values on standalone VM exit.

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#30318]
In the Mac and Linux stdio implementations, we have the following implementation for `stdin.echoMode`:
```cc
bool Stdin::SetEchoMode(bool enabled) {
  struct termios term;
  int status = NO_RETRY_EXPECTED(tcgetattr(STDIN_FILENO, &term));
  if (status != 0) {
    return false;
  }
  if (enabled) {
    term.c_lflag |= (ECHO | ECHONL);
  } else {
    term.c_lflag &= ~(ECHO | ECHONL);
  }
  status = NO_RETRY_EXPECTED(tcsetattr(STDIN_FILENO, TCSANOW, &term));
  return (status == 0);
}
```

This makes it impossible to set `echo` and `echonl` terminal settings separately. In a default terminal on both Mac and Linux, I get `echo` defaulted true and `echonl` defaulted false. The current implementation makes it impossible to return the terminal to its default settings if `echoMode` is ever modified.

**Comment by zanderso** [comment]
It looks like this might not be possible on Windows. I suspect that we should instead just try to reset the terminal to the state we found it in when the VM process exits. This is already partially done for windows in //runtime/bin/platform_win.cc. That should be extended to cover the modes modified in stdio_win.cc, and the same approach should be used for the other platforms.

**Comment by bkonyi** [comment]
This issue should be fixed for POSIX platforms after [this CL lands](https://dart-review.googlesource.com/c/sdk/+/45746). We'll need to revisit this for Windows since this isn't as simple as we thought (see #32172).

**Comment by bkonyi** [comment]
This should now be fixed for Windows after [this CL lands](https://dart-review.googlesource.com/c/sdk/+/46680).
