### ISSUE TITLE
mixin application classes missing charOffset

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#30316]
For dart2js we need all classes to have charOffsets.
For unnamed mixin applications, preferably this corresponds to the 'with' keyword.
We need this for stable output, all classes are sorted by location to make the general order correspond to the original source.

P1 since this is blocking dart2js.

**Comment by sigmundch** [comment]
Some challenges here:
 * unnamed mixins are being shared - we need to pick a canonical location that is stable

Question to discuss: how to support this with modular compilation?

**Comment by peter-ahe-google** [comment]
Unnamed mixin applications have no charOffset as they're synthetic classes and canonicalized.

You can make output stable by sorting them based on position, then name. Please schedule a video call with me if this isn't a satisfactory solution for you.
