### ISSUE TITLE
New heap always reported as full even if it is not

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#30311]
The new heap is always reported to be full by the `Scavenger`.

Run script:
```dart
import 'dart:async' show Timer, Duration;

final waste = [];

void topLevel(period) {
  new Timer.periodic(period, (Timer t) {
    waste.add(new List.filled(10000, 5));
  });
}

main() {
  topLevel(const Duration(seconds: 1));
}
```
Open Observatory in the `Allocation Profile` page

**Comment by dnunez02** [comment]
The new space uses top_ to determine how many words the new space is using. However, that information is in the mutator thread local state now.

I will update the appropriate functions to use the proper data.

**Comment by dnunez02** [comment]
https://codereview.chromium.org/2992153002/
