### ISSUE TITLE
Lexer offsets wrong for '0e'

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#30321]
```
int x = 0e;
```

highlights an extra character compared to

```
int x = .0;
```

and even

```
int x = 0.;
```

reports yet another different range.

This screws with tools that attempt to use the tokenizer like our angular analyzer, causing range errors if we attempt to slice dart code up by these offsets.

**Comment by MichaelRFairhurst** [comment]
see https://github.com/dart-lang/angular_analyzer_plugin/pull/410, at least we have a workaround for a simple reproduction.

**Comment by MichaelRFairhurst** [comment]
Also, seems like `0.` is a different set of errors related to it expecting a getter ie `0.toFloat()`

**Comment by bwilkerson** [comment]
@danrubel

**Comment by danrubel** [comment]
Confirmed.

Using analyzer's scanner...
![image](https://user-images.githubusercontent.com/2891888/29146269-609ba380-7d2e-11e7-8063-8f0b8d220be2.png)

Using fasta's scanner...
![image](https://user-images.githubusercontent.com/2891888/29146539-9e8be474-7d2f-11e7-966a-fcf1af15b0d1.png)

I'll investigate further.
