### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#30329]
[report2.txt](https://github.com/dart-lang/sdk/files/1201661/report2.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-171.4694.29`
- `1.24.2`
- `WS-171.4694.29, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 3840x2160, 3840x2160`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: C:\odw\sdk\core\bin\element.dart context: exception_20170804_171213_574
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4204)
#2      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:594)
#3      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:458)
#4      Object

**Comment by bwilkerson** [comment]
@scheglov Do you know whether this has been fixed in bleeding edge?

**Comment by scheglov** [comment]
Probably not fixed yet.
The corresponding "if" branch is still there.

**Comment by jfphilbin** [comment]
Any idea what I've done to cause this error.  I've tried to back out, by undoing changes, but haven't been successful.

**Comment by bwilkerson** [comment]
No, sorry, I can't tell from the stack trace what might have caused this. The only clue I have is that it's trying to de-serialize a reference to a type whose return type is "synthetic". I can't tell how the type being referenced was declared.

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
