### ISSUE TITLE
Image loading fails

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30338]
This bug is reproducible in the standalone Dart VM:

```dart
import 'dart:async';
import 'dart:io';

Future main() async {
  var client = new HttpClient();
  var uri = Uri.parse("`<image file>`");

  print('>>> getUrl($uri)');
  var request = await client.getUrl(uri);
  var response = await request.close();
  print('>>> status: ${response.statusCode}');
  var bytes = await response.fold(<int>[], (buffer, bytes) => buffer..addAll(bytes));
  print('>>> bytes read: ${bytes.length}');
}
```
This prints:

$ dart lib/image_load.dart
>>> getUrl(`<image file>`)
>>> status: 200
>>> bytes read: 0
Compare this to curl:

$ curl -s -D - `<image file>` -o /dev/null
HTTP/1.1 200 OK
Date: Mon, 07 Aug 2017 17:20:51 GMT
Server: Apache
Connection: Upgrade
Last-Modified: Thu, 11 Aug 2016 18:16:47 GMT
ETag: "a68d-539cfc4d721c0"
Accept-Ranges: bytes
Content-Length: 42637
Cache-Control: max-age=31536000
Expires: Tue, 07 Aug 2018 17:20:51 GMT
Content-Type: image/jpeg
$ curl -s `<image file>` | wc -c
   42637

**Comment by a-siva** [comment]
Added this here to track the Hamilton issue reported earlier @yjbanov @eseidelGoogle

**Comment by eseidelGoogle** [comment]
The critical part of this issue is understanding what it is.  If we can work-around it on the client or server side.  Right now all our customer knows is that some of the images on their server just fail to load in flutter for unknown reasons.

**Comment by zanderso** [comment]
The server is returning status: 200 with connection: Upgrade in the response header, which confuses the Dart http response header parser. It expects that if the server requests a connection upgrade, then the status couldn't have been 200. Here is a fix that causes the response header parser to ignore 'connection: Upgrade' unless the status is 426 UPGRADE REQUIRED or 101 SWITCHING PROTOCOLS.

https://codereview.chromium.org/2993873002

**Comment by zanderso** [comment]
Should have also noted that that is the behavior that we are observing from Chrome, Firefox, curl, and Android.
