### ISSUE TITLE
Strange initialization order when constructor parameters have same name as instance properties

### ISSUE THREAD

**Issue by cedx** [dart-lang/sdk#30331]
OS : Windows 10 & Ubuntu 17.04
Dart VM : 1.24.2

Behavior observed with the Dart CLI, not tested with Dart2js.

When I have constructor initializers, I can't use parameters with the same name as object properties. When I do this, the initializers are applied after the constructor body, not before as [said in the documentation](https://www.dartlang.org/guides/language/language-tour#initializer-list).

```dart
class Finder {

  Finder({List<String> path, List<String> extensions}): path = path ?? [], extensions = extensions ?? [] {
    print('Path (constructor): ${path}');
    print('Extensions (constructor): ${extensions}');
  }

  final List<String> extensions;
  final List<String> path;
}

main() {
  var finder = new Finder();
  print('Path (main): ${finder.path}');
  print('Extensions (main): ${finder.extensions}');
}
```

Expected output:
```
Path (constructor): []
Extensions (constructor): []
Path (main): []
Extensions (main): []
```

Current output:
```
Path (constructor): null
Extensions (constructor): null
Path (main): []
Extensions (main): []
```

If I use different names for constructor parameters, the initializers are normally applied before the constructor body:

```dart
Finder({List<String> pathParam, List<String> extensionsParam}): path = pathParam ?? [], extensions = extensionsParam ?? [] {
  print('Path (constructor): ${path}');
  print('Extensions (constructor): ${extensions}');
}
```

Output:
```
Path (constructor): []
Extensions (constructor): []
Path (main): []
Extensions (main): []
```

**Comment by lrhn** [comment]
The behavior is correct.
What happens is that the `path` in the constructor refers to the parameter, not the instance field. The parameter was `null`, so that is what you see. The field was initialized to an empty list because `path ?? []` evaluates to the empty list, but the `path` parameter wasn't changed.

Try changing the constructor print-lines to:
```dart
print('Path (constructor): ${this.path}');
print('Extensions (constructor): ${this.extensions}');
```
(That is, prefix the field names with `this.` to avoid referring to the parameter).

**Comment by cedx** [comment]
Of course!!! Sorry for the trouble, and a big thanks.
