### ISSUE TITLE
Loading native extensions from packages fails on Windows

### ISSUE THREAD

**Issue by dergemkr** [dart-lang/sdk#30334]
If you have a package with this layout,

    lib/
        example.dart
        example_native.dll

and example.dart imports `dart-ext:example_native`, anybody that attempts to load `package:example/example.dart` will get the following error when the VM tries to load the native extension:

    The specified module could not be found.

The underlying issue seems to be in loader.cc/loader.dart. The scheme is not stripped from library_uri properly for Windows paths. (e.g. If library_uri is `file:///C:/dev/example/lib`, the loader will try to load the DLL in `//C:/dev/example/lib/`.)

I should have a fix up shortly but don't have a good way of testing it on non-Windows platforms at the moment.

**Comment by dergemkr** [comment]
Code review opened at https://codereview.chromium.org/2996583002/

**Comment by ds84182** [comment]
Any update on this? Kinda makes native extensions annoying to use on Windows.

**Comment by dergemkr** [comment]
I'll address the comments on the code review by the end of the week. I dropped the ball on this one.

**Comment by dergemkr** [comment]
I couldn't upload a new patch set against the old code review. I opened a new code review here with the previous comments addressed: https://dart-review.googlesource.com/c/sdk/+/35101

**Comment by JohnWall2016** [comment]
This bug still exists in dart-sdk 2.3 for windows. There is no plan to fix it?

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
