### ISSUE TITLE
Meta-issue for discussion of the proposal to interpret numeric literals according to typed context

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30348]
This issue is to provide a forum for community discussion and feedback related to the proposal to interpret numeric literals as either doubles or integers depending on the typed context in which they appear.

This entry will be updated when a proposal is available.

cc @munificent @eernstg @floitschG @lrhn

**Comment by natebosch** [comment]
I think this is superseded by https://github.com/dart-lang/language/issues/4 and https://github.com/dart-lang/sdk/issues/34355

Those issues have more context so I'm closing this one.
