### ISSUE TITLE
Meta-issue for discussion of implicit new and const

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30341]
This issue is to provide a forum for community discussion and feedback related to the proposal to make new and const optionally implicit in Dart 2.0.

An initial proposal is here: https://github.com/dart-lang/sdk/blob/master/docs/language/informal/optional-new-const.md .

cc @munificent @eernstg @floitschG @lrhn

**Comment by brianegan** [comment]
Omg yes, this would make Flutter even better :D

**Comment by eernstg** [comment]
We now have draft informal specs for [optional const](https://gist.github.com/eernstg/4f498836e73d5f003928e8bbe1683d68) and [optional new](https://gist.github.com/eernstg/7e819b44acd8dd9d71f0cc510b618a3d). They will move to the [SDK repo](https://github.com/dart-lang/sdk/tree/master/docs/language/informal) soon.

**Comment by eernstg** [comment]
They have been moved to the SDK repo now: [optional const](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/optional-const.md), [optional new](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/optional-new.md).

**Comment by leafpetersen** [comment]
Just as an update, the major remaining point of discussion is whether to make things that can be const be const, even if they are not in a const context.  That is, should:

```
var x = C();
```

where `C` has a const constructor, result in `x` being bound to a const object or a non-const object.

**Comment by lrhn** [comment]
Dart 2 landed without this last feature (sadly). We hope that it will be possible to add it in a later version, but the original design didn't work well because it required effectively calling a const constructor to figure out whether the expression was const or not.
