### ISSUE TITLE
Meta-issue for discussion of the Dart 2.0 mixin proposal

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30342]
This issue is to provide a forum for community discussion and feedback related to the proposal to add explicit syntax for mixins in Dart 2.0.

An initial proposal is here: https://github.com/dart-lang/sdk/blob/master/docs/language/informal/mixin-declaration.md.

cc @munificent @eernstg @floitschG @lrhn

**Comment by rmacnak-google** [comment]
This change also requires breaking changes to dart:mirrors, which the proposal neglects.

**Comment by matanlurey** [comment]
How much real code do we have with mirrors + mixins being a critical user journey?

(Not trolling, I tried finding a single case and I couldn't)

**Comment by leafpetersen** [comment]
This is not planned for the release of 2.0.

**Comment by natebosch** [comment]
There is more discussion and context at https://github.com/dart-lang/language/issues/7 which I think supersedes this proposal. I think we should close this one in favor of that one.

@rmacnak-google I added a comment there noting you had concerns about breaking changes in `dart:mirrors`
