### ISSUE TITLE
Meta-issue for discussion of fixed sized integers.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30343]
This issue is to provide a forum for community discussion and feedback related to the proposal to make integers fixed precision in Dart 2.0.

Initial proposal here: https://docs.google.com/document/d/1h0Hcr3r-0hDbQNHdLetXCRQMfPb_xZe3ZNN1sxlVGEk/edit .

cc @munificent @eernstg @floitschG @lrhn

**Comment by leafpetersen** [comment]
Updated with initial proposal.

**Comment by zoechi** [comment]
A public version of above linked proposal can be found in https://gist.github.com/floitschG/a5e1a2287260135ba2ce787626284ce3
@floitschG I hope it's fine to post the link here.

**Comment by ktullavik** [comment]
How do I detect if an integer overflows?

**Comment by lrhn** [comment]
There is no trivial way to test for overflow. Dart integers will act the same as C/C++/C#/Java 64-bit signed integers, which means silent overflow. If you write `0x100000001 * 0x100000001`, the result will be `0x200000001`.

If you expect that an overflow might happen, you can manually check first:
```dart
if (0x7FFFffffFFFFffff ~/ 0x100000001 < 0x100000001) print("would overflow");
```

If experience from those other languages tells us anything, it is that you usually won't care and that's fine, and in a few cases [you should have](https://research.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html).

**Comment by stevenroose** [comment]
I have a hard time finding any release notes on how exactly integers change in Dart 2, apart from [this document](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md), which is just a proposal.

Also, where can we find an alternative for a big int implementation (apart from the one in the bignum package)?

**Comment by lrhn** [comment]
The linked document is not just a proposal, it is the design document for the change and is what is being implemented.

We have added a `BigInt` class to `dart:core`. it will end up using the existing `int` implementation on the VM, but will also be available when compiled to JavaScript.

**Comment by stevenroose** [comment]
> Status: Under implementation.
> 
> This document discusses Dart's plan to switch the int type so that it represents 64-bit integers instead of bigints. It is part of our continued effort of changing the integer type to fixed size (issue).
> 
> We propose to set the size of integers to 64 bits. Among all the investigated options, 64-bit integers have the smallest migration cost, and provide the most consistent and future-proof API capabilities.

:)

That's great! (The document mentions the class to be in typed_data, but I indeed couldn't find it there. I guess the JS implementation of the class is more optimized for JS, like the JS BigInteger libs do. Perfect, thanks!

**Comment by sgrekhov** [comment]
@lrhn Does the current (working) version of the specification include this change?

**Comment by lrhn** [comment]
Not yet. The spec is in CL https://dart-review.googlesource.com/c/sdk/+/38020/2/docs/language/dartLangSpec.tex#3258, but it needs a little clean-up before it can land.

**Comment by lrhn** [comment]
The spec has landed. It says that integers are 64-bit numbers, unless they aren't (which is allowed because of JavaScript).

**Comment by stevenroose** [comment]
I have an open issue for an implementation of `toBytes()` and
`fromBytes()`. Could support for binary conversion land in the first Dart 2
stable release? Or will it be postponed? Javas `BigInteger` has it and
`package:bignum.BigInteger` also did.

**Comment by natebosch** [comment]
is there anything else to discuss on this issue @leafpetersen ?

**Comment by leafpetersen** [comment]
@lrhn Any comments on the question around toBytes and fromBytes?  Otherwise I think this can be closed.

**Comment by lrhn** [comment]
I don't think the `int` class should have `toBytes` or `fromBytes` since it can't be implemented consistently across platforms.

It's exceedingly simple to get the bytes for a 64-bit integer:
```dart
  var bytes = (Int64List(1)..[0] = value).buffer.asUint8List();
```
so it's not something that we desperately need helper functions for.

The subject of this issue is complete, and whether to add to/from-byte functionality has its own issue, so closing here.

**Comment by stevenroose** [comment]
Hmm, my comment seems to have been intended for the `BigInt` class, not the int type.
