### ISSUE TITLE
[feature request] auto wrap if-statement

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30358]
Example:
```
if (confition) action();
```
or 
```
if (confition)
action();
```

On ```Reformat Code``` should become:
```
if (confition) {
       action();
}
```

With explicit braces it easier to tell what actually belongs in the if block, it saves others from adding the braces later (or creating a bug by forgetting to), and it makes all your if statements uniform instead of some with braces and some without.

No braces is error-prone. For example, let's say you are temporarily commenting out code to debug something:
```
if(condition) 
//      statement;
otherStatement;
```

Or adding code:
```
if(condition) 
    statement;
    otherStatement;
}//some brace that may look like it belongs here but actually is from another statement above the IF
```

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/dart_style#647
