### ISSUE TITLE
Meta-issue for discussion of the proposal to allow some closures to be used as const values

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30351]
This issue is to provide a forum for community discussion and feedback related to the proposal to allow closures to be used as const values under certain circumstances.

This entry will be updated when a proposal is available.

cc @munificent @eernstg @floitschG @lrhn

**Comment by natebosch** [comment]
I think this is the same as https://github.com/dart-lang/sdk/issues/4596 which has more context so I'll close this one
