### ISSUE TITLE
VM is tests with generics

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#30361]
From the specifications:

```
16.34 Type Test

[...]

Evaluation of the is-expression e is T proceeds as follows:
The expression e is evaluated to a value v. Then, if T is a malformed or
deferred type (19.1), a dynamic error occurs. Otherwise, if the interface of the
class of v is a subtype of T, the is-expression evaluates to true. Otherwise it
evaluates to false.
```

So if I have something like types.dart:
```
f<A>(int x) {
  print(x is A);
}

class C<A> {
  p(int x) {
    print(x is A);
  }
}

main() {
  print("Through functions:");
  print("");

  print("int is int:");
  f<int>(42);

  print("int is String:");
  f<String>(42);

  print("int is string:");
  f<string>(42);

  print("");
  print("Through classes:");
  print("");

  C c = new C<int>();
  print("int is int:");
  c.p(42);

  c = new C<String>();
  print("int is String");
  c.p(42);

  c = new C<string>();
  print("int is string");
  c.p(42);

  print("");
  print("Directly:");
  print("");

  print("int is int");
  print(42 is int);

  print("int is String");
  print(42 is String);

  print("int is string");
  print(42 is string);
}
```

I wouldn't expect to get (I ran with '--reify_generic_functions'):
```
Through functions:

int is int:
true
int is String:
false
int is string:
true

Through classes:

int is int:
true
int is String
false
int is string
true

Directly:

int is int
true
int is String
false
int is string
Unhandled exception:
'[...]/types.dart': malformed type: line 51 pos 15: cannot resolve class 'string' from '::'
  print(42 is string);
              ^


#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:82)
#1      main ([...]/types.dart:51:15)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

(notice that 'string' is with lowercase 's').
So the last one - without generics - is what the specs seems to want.
But what's happening with
```
int is string
true
```
?

@sjindel-google (who ran into this).

**Comment by eernstg** [comment]
This is working as intended: The invocation `f<string>(42);` will pass `dynamic` as the type argument, because `string` is a name which is undefined in the given context, and `42 is T` will return true when the value of `T` is `dynamic`. A similar thing happens for `c.p(42);`.

**Comment by sjindel-google** [comment]
Is this behavior correct for strong mode as well?

**Comment by lrhn** [comment]
No, in strong mode, the type argument is actually passed and used, and Dart 2 will do that too.

Dart 1 does not have generic functions, but we have added the syntax so code can choose to support strong mode Dart anyway and be prepared for the future.

**Comment by eernstg** [comment]
In this particular case the type arguments were actually passed (for the class because that's always the case, and in the generic function due to '--reify_generic_functions').

But in strong mode (and in the upcoming Dart 2) there can't be any surprising behavior at run time, because the expressions `f<string>(42);` and `new C<string>();` are compile-time errors.

**Comment by sjindel-google** [comment]
Even with strong mode enabled in the VM via "-c", the check returns "true" without any errors or warnings.
