### ISSUE TITLE
Optional argument names

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30362]
My concern is only that when you change function declaration between 
```Dart
void doThing( Object p1, Object p2 );
``` 
and 
```Dart
void doThing( { Object p1, Object p2 } );
``` 
```Dart
void doThing( [ Object p1, Object p2 ] );
``` 
```Dart
void doThing( Object p1, { Object p2 } );
``` 
and so on.

Then you have to go and fix each line calling this function, even if you didn't change anything in the callings  from technical point of view:
```Dart
doThing(p1: x, p2: y); // is still the same call, right?
```

The proposal is to allow optional argument names.

For example for the following contract:
```Dart
void doThing(Object p1, Object p2);
```
to make it possible to call the function in both ways
```Dart
doThing(x, y);
```
and 

```Dart
doThing(p1: x, p2: y);
```

**Comment by anders-sandholm** [comment]
@lrhn do you have the original issue # for reference? Then we can close this one.

**Comment by lrhn** [comment]
I must have missed the "Close and comment" button.
I inteded to say that this is the same as, or very similar to, #30255, and the same comments apply.
