### ISSUE TITLE
Increase VM symbol table load factor without impacting performance

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30378]
The change here:

https://github.com/dart-lang/sdk/commit/c4b821cc813cd48e0584da7d5afffa74629025c6

Increased the VM isolate's symbol table load factor from 0.375 to 0.9. This saved ~100KB in memory footprint, but regressed Flutter hot restart performance:

https://github.com/dart-lang/sdk/issues/30371

It would be good to figure out how to increase the load factor of `UnorderedHashSet` in //runtime/vm/hash_table.h without hurting performance so much.

**Comment by rmacnak-google** [comment]
Obsolete after https://dart-review.googlesource.com/c/sdk/+/93962
