### ISSUE TITLE
Hot restart perf regression (~4400ms to ~6000ms)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30371]
After we rolled Dart from 82e9557aa78cc1ff43ea60bc443758558bbe4d99 to 69817eea182384b40ef658d578fd49cac00c5874, the hotRestartMillisecondsToFrame metric for hot_mode_dev_cycle__benchmark (mac host), hot_mode_dev_cycle_linux__benchmark, and hot_mode_dev_cycle_win__benchmark all regressed by about the same proportion.

**Comment by alexmarkov** [comment]
@zanderso 

Bisected this regression to the commit https://github.com/dart-lang/sdk/commit/c4b821cc813cd48e0584da7d5afffa74629025c6

In order to reproduce the problem, run the following command line in the flutter_gallery:
```
flutter run --hot --benchmark --verbose --local-engine-src-path <ENGINE_SRC> --local-engine android_debug_unopt
```
and check "Restarted app in" in the output.

**Comment by zanderso** [comment]
Golem showed only a 2% slowdown in compilation on the change, but it's possible that hot reload is hitting the symbol table a bit harder. I'll take a look.
