### ISSUE TITLE
Add Iterable.groupBy

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#30376]
Iterable.groupBy would be great!

(I'm opening a new issue, instead of re-opening #11159, because the discussion over there was largely about how it would be hard to do without Dart 2.0. I'm opening this issue in the context of Dart 2.0. If this is not the right workflow, we can re-open #11159, and close this.)

```dart
class Iterable<E> {
  Map<F, Iterable<E>> groupBy<F>(F Function(E) groupingFn);
}
```

Some examples:

```dart
["Aardvark", "Antelope", "Zebra", "Bison", "Alligator"].groupBy((e) => e[0]);
// ==> {"A": ["Aardvark", "Antelope", "Alligator"], "B": ["Bison"], "Z": ["Zebra"]}

[1,2,3,4,5,6,7,8,9].groupBy((e) => i % 4);
// ==> {0: [4, 8], 1: [1, 5, 9], 2: [2, 6], 3: [3, 7]}

{"Maine": ["Acadia"], "Missouri": [],
 "Montana": ["Glacier", "Yellowstone"], "Rhode Island": []}
    .groupBy((k, v) => v.isEmpty);
// ==> {true: [Entry("Missouri", []), Entry("Rhode Island", [])],
//      false: [Entry("Maine", ["Acadia"]), Entry("Montana", ["Glacier", "Yellowstone"])}
```

(That last one assumes we get an iterator over key/value pairs in Map (#7088) that yields Entry objects. But if its a List or a Pair or a Tuple, whatever.)

I think this is a useful method to have, and also it is expected from developers in other languages. Python2 has [groupby](https://docs.python.org/2/library/itertools.html#itertools.groupby); Ruby has [Enumerable#group_by](https://ruby-doc.org/core-2.1.1/Enumerable.html#method-i-group_by), Rust's itertools has [GroupBy](https://docs.rs/itertools/*/itertools/structs/struct.GroupBy.html); It is not to be found in Go, JavaScript (so people use [Underscore.js](http://underscorejs.org/#groupBy)).

Java 8's Collectors has [groupingBy](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html) which I think is very well thought out; it has a few overloaded variations (could implement similar things in Dart with named arguments), like including a "reduction operation", something like:

```dart
["Aardvark", "Antelope", "Zebra", "Bison", "Alligator"]
    .groupBy((e) => e[0], reduce: (grouping) => grouping.length);
// ==> {"A": 3, "B": 1, "Z": 1}
```

Probably unnecessary in Dart, as we have other first class functional means, especially if Map gets a map function (#9590):

```dart
["Aardvark", "Antelope", "Zebra", "Bison", "Alligator"]
    .groupBy((e) => e[0]).map(grouping) => grouping.length);
// ==> {"A": 3, "B": 1, "Z": 1}
```

**Comment by lrhn** [comment]
I'd type it as `Map<K,List<E>> groupBy<K>(K key(E element))` (that is, a map to lists, not iterables).
You have to go through the entire iterable before you can return a map because you don't know the keys before that. At that point, you will have collected and distributed all the values anyway, so there is no reason to use an `Iterable` for the values in the map.

**Comment by floitschG** [comment]
We then also need a `Stream.groupBy -> Future<Map<K, List<T>>`.

**Comment by rkj** [comment]
+1 for this, seems Flutter went ahead and added it: https://docs.flutter.io/flutter/package-collection_collection/groupBy.html
could this at least be moved into quiver?

**Comment by matanlurey** [comment]
@rkj: This is just normal `package:collection`: 
https://pub.dartlang.org/documentation/collection/latest/collection/groupBy.html

@leafpetersen @lrhn feel free to re-open if you still plan to do this.

**Comment by vukisoft** [comment]
This would still be useful as using a top level groupBy breaks the fluent method calls.

groupBy(list.map(..).where(..), (item) => ..)
vs
list.map(..).where(..).groupBy((item) => ..)

**Comment by mraleph** [comment]
@vukisoft note that you can now use [static extension methods](https://medium.com/dartlang/extension-methods-2d466cd8b308) if you want to achieve fluent method calls.
