### ISSUE TITLE
Analyzer function type parameters are not correctly scoped

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30379]
In the following, `G` and `H` are entirely equivalent, and neither of them are subtype related to `F<T>` for non-trivial `T`, but `F<T>` and `G` (but not `H`) are considered assignable.

```dart
typedef F<T> = int Function<S>(T x);
typedef G = int Function<T>(T x);
typedef H = int Function<Q>(Q x);

void test(bool b) {
   int Function<T>(F<T> f) f1;
   int Function<T>(G f) f2;
   int Function<T>(H f) f3;
   f1 = f2; // Should be error, IS NOT
   f1 = f3; // Should be error, is
   f2 = f1; // Should be error, IS NOT
   f2 = f3; // Should be ok, is
   f3 = f1; // Should be error, is
   f3 = f2; // Should be ok, is
}
```

**Comment by jmesserly** [comment]
this might be related: https://github.com/dart-lang/sdk/issues/30375

**Comment by jmesserly** [comment]
working through the types:

f1 is `<T> (<S> T -> int ) -> int`
f2 is `<T> (<T'> T' -> int ) -> int`
f3 is `<T> (<Q> Q -> int ) -> int`

The fact that f2 has the problems is scary... f2 and f3 should be identical.

We did have a capture bug here: https://github.com/dart-lang/sdk/issues/29778#issuecomment-317149157 ... any time we create a synthetic function type we hit major problems with substitutions. That could be related.

Another problem that scared me recently when reading the code, is whether our "fresh" type variables are actually treated as non-equal to existing type variables or to other "fresh" type variables that have the same name. I worried that synthetic type variables might be falling back to name-based equality. (analyzer uses name-based equality for elements, where the name is "fully-qualified". but I don't know if this even takes into two type variables declared in the same scope, like each `T` for f1/f2/f3, or if it takes into account synthetic type variables that don't have any parent chain.)

**Comment by jmesserly** [comment]
@leafpetersen I can help look into this if you have not started already

**Comment by leafpetersen** [comment]
All yours if you want it, though not sure it's top priority.  Just getting a test written to be sure that the new front end does the right thing might be a good start.

**Comment by srawlins** [comment]
This is now fixed. In the example, there are errors reported on lines 9, 10, 11, and 13:

```
Analyzing 30379.dart...
  error • A value of type 'int Function<T₀>(int Function<T>(T))' can't be assigned to a variable of type 'int Function<T>(int Function<S>(T))'. • 30379.dart:9:9 • invalid_assignment
  error • A value of type 'int Function<T>(int Function<Q>(Q))' can't be assigned to a variable of type 'int Function<T>(int Function<S>(T))'. • 30379.dart:10:9 • invalid_assignment
  error • A value of type 'int Function<T>(int Function<S>(T))' can't be assigned to a variable of type 'int Function<T₀>(int Function<T>(T))'. • 30379.dart:11:9 • invalid_assignment
  error • A value of type 'int Function<T>(int Function<S>(T))' can't be assigned to a variable of type 'int Function<T>(int Function<Q>(Q))'. • 30379.dart:13:9 • invalid_assignment
4 errors found.
```
