### ISSUE TITLE
Add support in the dart VM build process to enable boot strapping of the Dart Front End

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30374]
Currently the dart VM build process uses the C++ VM parser to run the Dart Front End, this needs to change as we will be deleting the C++ VM parser. We need a scheme of storing a bootstrapped version of the Dart Front End as a kernel dill file and use taht to bootstrap the build process.

**Comment by dgrove** [comment]
@a-siva is this needed prior to Dart2 Stable?

**Comment by a-siva** [comment]
This is again something we need before deprecating Dart1, maybe under the bucket 'DeprecateDart'

**Comment by a-siva** [comment]
This is done, closing issue.
