### ISSUE TITLE
DDC does not understand the syntax for generic function types

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30375]
see function_type50_test, testF4:
```dart
Expect.isTrue(m4 is List<A> Function<A>(List<Function> x));
```

Judging by DDC's output, it looks like Analyzer creates a synthetic typedef of some sort for `List<A> Function<A>(List<Function> x)` ... however, when DDC generates code for that, the typedef is backed by a non-generic function type.

DDC does support generic function types if they're declared with named typedefs, so my guess is it's something a bit quirky in the element model, that we aren't handling correctly in _emitType

**Comment by jmesserly** [comment]
function_type58_test appears to be failing for the same reason

**Comment by matanlurey** [comment]
Related to https://github.com/dart-lang/sdk/issues/30758?

**Comment by jmesserly** [comment]
this has been fixed a while ago.
