### ISSUE TITLE
Analyzer parser recovery: premature closing labels created by code errors

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30370]
I'm working in implementing a "closing labels" feature in the analysis server (#30285). During testing I noticed that this bad code results in labels being inserted in a bad place:

![Bad label positioning](https://user-images.githubusercontent.com/1078012/29089998-22719258-7c76-11e7-85fd-7464a9f92d9e.png)

The greyed "comments" are being inserted on the line where the associated nodes are ending (according to the AST), the highlighted code is the code I accidentally inserted where a type name should be. It seems like it should be possible to do a better job here (I believe it's the semi-colon throwing things off; but there's a compile error that the semicolon is not expected and if you take it away, I believe the nodes end at the correct places).

@bwilkerson suggests this might not be worth tackling in the current parser, though it might be a good cast to handle/test with the new parser.

**Comment by bwilkerson** [comment]
@danrubel @lukechurch

**Comment by DanTup** [comment]
Here's another one (lmk if you want another case).. Adding ` a` onto the end of this `null` caused a similar thing - a load of invocation nodes to end too early (again, the ` a` is unexpected and if you ignore it completely, you should get the correct endings).

<img width="962" alt="screen shot 2017-08-11 at 14 23 22" src="https://user-images.githubusercontent.com/1078012/29214899-cb455302-7ea0-11e7-8f12-31b287683290.png">

**Comment by DanTup** [comment]
These things are all handled much better now:

<img width="702" alt="Screenshot 2022-05-24 at 12 00 19" src="https://user-images.githubusercontent.com/1078012/170020827-10d392e9-34e8-4dbe-a1ae-b454a00c6ac1.png">

<img width="606" alt="Screenshot 2022-05-24 at 12 05 52" src="https://user-images.githubusercontent.com/1078012/170020834-cf55f4a7-f5f3-42f7-8aea-e12d2d9c7bf0.png">
