### ISSUE TITLE
Analysis Server Crash on RegExp with r'' String

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30373]
Causes a crash.

```dart
static final _removePrecedingComma1R = new RegExp(r'\(\s*,');
```

# Version information

- `IDEA IU-171.4073.35`
- `1.25.0-dev.7.0`
- `IU-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-83-generic unknown, screens 1920x1080, 1920x1080`

**Comment by bwilkerson** [comment]
I am not able to reproduce this behavior on bleeding edge on my Mac, so it's possible that this has been fixed. 1.25.0-dev.9.0 is now available. Could you confirm whether this is still a problem on the latest dev release?

**Comment by matanlurey** [comment]
This is the internal build, so I don't have an option of trying the latest until it lands.

**Comment by bwilkerson** [comment]
The latest landed yesterday (but probably after I asked you to try it).

**Comment by bwilkerson** [comment]
I'm going to assume this was fixed. Please re-open if that's not the case.
