### ISSUE TITLE
support failed reloads/rebuilding deltas in incremental generator

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30377]
Loading a `delta` produced by the incremental compiler can fail if the VM and host are not on the same baseline. This can happen when there were file transfer errors (the first delta never arrived), or when a delta was discarded by the VM (e.g. the new program tried to upgrade an enum into a class, which the VM rejects).

To recover from this, the VM and the host service sending deltas need to be able to track the consistency of their baseline.

Proposals out there:
 1. do bookkeeping in the the host service, extend the incremental compiler API to let the host service indicate that a library must be present.
  2. provide feedback to the incremental generator as to whether a new-delta should be "committed" in its internal state. This way an incremental compile + reload can be treated as an atomic operation.

In terms of APIs, (1) would look like this:
```dart
class IncrementalKernelGenerator {
   void invalidate(Uri uri, {bool force});
   DeltaProgram computeDelta();
}
```
The host service would simply call `invalidate(uri, force: true)` for all libraries in a rejected delta is rejected. That way, next time `computeDelta` is invoked, the incremental generator will include again code for those libraries that were rejected:
```dart
  doReload() async {
     // This is the same as today:
     invalidateModifiedFiles();
     var delta = generator.computeDelta();
     var result = await sendReloadRequest(delta.newProgram)

     // New logic:
     if (!result.isSuccess) {
       // Reload was rejected and the VM is still using the old baseline.
       // Ensure rejected libraries are part of the next delta again, so 
       // it can be applied on top of the old baseline.
       for (var lib in delta.newProgram) {
          generator.invalidate(lib.importUri, force: true);
       }
     }
```

(2) would move some of this logic behind the incremental generator. The API might look like this:
```dart
class IncrementalKernelGenerator {
  void invalidate(Uri uri);
  DeltaProgram computeDelta();
  void acceptLastDelta();
  // OR:
  void rejectDelta(DeltaProgram delta);
}
```

If we had some notion of history in the incremental generator, we could also store an index for each call to computeDelta, and optionally provide a baseline index for what to compute a delta from. A rejected delta can be ignored by providing the same baseline index again to computeDelta:

```dart
class DeltaProgram {
   Program newProgram;
   int newBaselineIndex;
}

class IncrementalKernelGenerator {
   void invalidate(Uri uri);
   DeltaProgram computeDelta({int baselineIndex});
}
```

This last approach would require more work internally: we'd need to add the notion of history to the kernel-driver, or the notion of "uncommited" changes.

**Comment by scheglov** [comment]
1. I'm not going to fix the "file transfer error" case in IKG. Right now it looks as something completely unrelated to IKG. If there is a bug in the transfer mechanism, fix it. If this can be a transient error, resend the file.

2. For rejected changes, it is easier to work not with rollbacks, but with commits.
2.1. IKG gives the client a new `DeltaProgram`.
2.2. The client sends it to the VM.
2.2.1. If VM accepts the delta, the client calls `IKG.commit(delta)`. So, any libraries which are not changed next time, will not be included into the next delta.
2.2.2 If VM rejects it (here I think that it rejects it completely, not just pieces of it), the client does not commit the delta. Then the next delta will include all the libraries of the not committed delta, and  plus new changes libraries.
2.3. The expectation is that the client will not request a new delta before committing the previous one.

**Comment by sigmundch** [comment]
> I'm not going to fix the "file transfer error" case in IKG. 

Agree IKG doesn't need to do anything about it - I was using it as an example for one of the possible reasons a reload could fail.

> ... it is easier to work not with rollbacks, but with commits.

That makes sense. Some follow up questions:

  * `rejectDelta(delta)` - this is a rollback, so we are discarding this option, correct?

  * `invalidate(force:true)` - this is a rollback but outside IKG. Do you still prefer not to do this either? It seemed like the simplest implementation to me.

  * `commitDelta(delta)` - do you need the delta argument (if not, this would be like the `acceptLastDelta()` example above)

  * how much work it ill be to add support for `commitDelta`? Is the work needed for it also useful for kernel-driver in other scenarios?

**Comment by scheglov** [comment]
Actually, we could have both `rejectLastDelta()` and `acceptLastDelta()`, and enforce that one of them must be invoked before the next `computeDelta()`.

`KernelDriver` don't need commit/rollback features, it works with whatever is the latest. Delta support is [IKG only feature](https://github.com/dart-lang/sdk/blob/06e94bc36007bbbdafa44b694b3aac55d17e7ebc/pkg/front_end/lib/src/incremental_kernel_generator_impl.dart#L77).

**Comment by sigmundch** [comment]
Sounds like a plan then.

Two other API ideas
* change the `DeltaProgram` API instead:

```dart
class DeltaProgram {
   Program newProgram;

   void accept();
   void reject();
}
```

* Or, add an argument to `computeDelta`:
```dart
  DeltaProgram computeDelta({sincePreviousDelta: false});
```

With the accept/reject methods, we need to have a check in `computeDelta` to ensure that something was called. With the optional argument in `computeDelta` the default is to reject, and if you explicitly say 'true', we commit and move on to the next delta.

I think the argument to computeDelta can be the easier to use/least error prone.

**Comment by scheglov** [comment]
Methods in `DeltaProgram` given an illusion that you can accept / reject different deltas at different times. While actually it is always the last delta.

Additional argument for `computeDelta()` seems less clear. I'd prefer to have explicit APIs that perform an action. `Compute - send - accept`, vs. `Compute - send - rememberState - waitForChangesToFiles - Compute(withTheRememberedState)`.

**Comment by sigmundch** [comment]
> Methods in DeltaProgram give an illusion that you can accept / reject different deltas at different times. While actually it is always the last delta.

valid point

> I'd prefer to have explicit APIs that perform an action. 

sounds good.

I am not sold on whether to require both accept/reject or have one be the default. Do you prefer one or the other for any reason? If we have a default, I'd the default should be to reject until you call `accept`.  This would make delta's always applicable and `accept` is now an optimization to keep deltas as small as possible. Thoughts?

**Comment by scheglov** [comment]
It is easier for me to think in terms of explicit actions.

What is the use case in implicit reject?
It might keep correctness, but why not drive the client into a more optimal scenario and force to use explicit actions?

**Comment by sigmundch** [comment]
> What is the use case in implicit reject?

Nothing specific comes to mind, just brainstorming openly about the alternatives.

Sounds like we have a plan in place.
```dart
class IncrementalKernelGenerator {
  void invalidate(Uri uri);
  DeltaProgram computeDelta();
  void acceptLastDelta();
  void rejectLastDelta();
}
```

**Comment by scheglov** [comment]
ACK

**Comment by scheglov** [comment]
https://codereview.chromium.org/2996843002
