### ISSUE TITLE
Dart Analyzer doesn't enforce a Widget return type when described in a typedef

### ISSUE THREAD

**Issue by maryx** [dart-lang/sdk#30389]
Given this sample code snippet:
```dart
class Foo extends StatelessWidget {
  final FooBuilder builder;
  final Widget child;

  Foo({this.builder, this.child});

  @override
  Widget build(BuildContext context) => builder(
        context,
        child,
      );
}

typedef Widget FooBuilder(
  BuildContext context,
  Widget child,
);

class Bar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Foo(
      builder: (
        BuildContext context,
        Widget child,
      ) {
        new Container();
      },
    );
  }
}
```
I would expect the Dart Analyzer to show an error under the line that says `new Container();`, since I never actually return anything inside the `return new Foo(...)` call, and it should be returning a Widget.
An real example of this is here:  https://github.com/fuchsia-mirror/modules-video/blob/master/modules/video/lib/src/widgets/scrubber.dart#L164 where if I comment out L164, the code still builds fine, but the widget doesn't show up since it was never returned.

I'm not familiar enough with typedefs to know if it really is a typedef issue or if it's something else.

**Comment by jmesserly** [comment]
simplified repro:
```dart
class Foo {
  final FooBuilder builder;

  Foo({this.builder});

  Foo build() {
    return new Foo(builder: () {
      new Foo();
    });
  }
}

typedef Foo FooBuilder();
```
It still reproduces. Taking a look.

**Comment by jmesserly** [comment]
even simpler:
```dart
main() {
  int Function() f = () {};
}
```
the problem is we infer `() {}` as having type `() -> Null` which is not what I would expect. It prevents us from detecting the missing return (functions with `Null` return type are allowed to omit a return). @leafpetersen does that seem right to you? I'm tempted to fix it. I feel like the inferred return type should prefer the context type. I'm not sure if `Null` was done on purpose or not.

**Comment by jmesserly** [comment]
missing returns are covered by https://github.com/dart-lang/sdk/issues/28233, merging this into that issue
