### ISSUE TITLE
Strong mode analyzer inconsistent about when types must match

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30385]
Consider this code:

```dart
class A { }
class B extends A { }

void test<T>(T v) { }

void main() {
  final A x = new A();
  test<B>(x); // no error

  test<B>(new A()); // strong_mode_invalid_cast_new_expr
}
```

Why are these different?

**Comment by Hixie** [comment]
For the record, I would have expected an error in both cases.

**Comment by bwilkerson** [comment]
@leafpetersen

**Comment by leafpetersen** [comment]
You've asked me about this before.  :)  Our previous discussion of which led to these two issues being filed:

https://github.com/dart-lang/sdk/issues/29548
https://github.com/dart-lang/sdk/issues/29547

Strong mode makes implicit downcasts an error when it can immediately prove that the cast will fail.  It's not smart enough to track the fact that `x` is definitely an `A` and not a `B` in your example, but it does notice when you try to cast a fresh instance of `A` to a `B`.

The `--no-implicit-casts` flag will make both of those an error.

**Comment by Hixie** [comment]
Why would we not make implicit downcasts an error in general? They're not sound, right? I thought the point was to be sound.

**Comment by Hixie** [comment]
So as @leafpetersen said, you can turn off implicit casts, that's `implicit-casts: false` in your analysis options. Unfortunately that isn't ready for prime time yet. Filed https://github.com/dart-lang/sdk/issues/30402 on some issues I found trying to turn that on.

**Comment by jmesserly** [comment]
removing implicit downcasts is now tracked in https://github.com/dart-lang/sdk/issues/31410
