### ISSUE TITLE
Allow more fine-grained analysis_options per file-glob

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#30386]
exclude is handy - it'd also be nice if we could get more control than on/off based on file.

I might want `implicit_dynamic: false` for my production code in `lib/` but not for `test/`.

This could plausibly solve, or at least help with, https://github.com/dart-lang/sdk/issues/29713 too. If we want to say that the analyzer (IDE, dartanalyzer cli) and compiler (DDC) have to share the same config we might be able to get away with carefully constructing our file globs to tune it the way we want.

Regardless of whether we end up with some other solution to distinguish DDC behavior I think having different errors in my IDE for test vs lib code could be handy.

**Comment by matanlurey** [comment]
Honestly this is somewhere I'd hope we agree on even an informal "module" specification, as this would help incremental standalone compilation (via `dartdevc`), and for tooling like code generation, but also in this case too.

**Comment by natebosch** [comment]
Yeah an agreed upon definition of a 'module' could help a number of our tools from having to redefine it and would solve this use case.

**Comment by matanlurey** [comment]
@kevmoo Is this something we can try to do (informally)?

**Comment by kevmoo** [comment]
> Is this something we can try to do (informally)?

What do you mean by 'informally'?

**Comment by matanlurey** [comment]
A module format for pub packages that can be shared across tools

**Comment by natebosch** [comment]
Closing as a dup of #34069 even though it's newer because it has more interesting discussion.
