### ISSUE TITLE
Disallow downgrading errors that would cause undefined behavior

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#30387]
Forked from https://github.com/dart-lang/sdk/issues/29713

We have `--unsafe-force-compile` - that should be the only way to allow undefined behavior at runtime.

Currently it's also possible to downgrade an error using analysis_option.yaml. There might be other flags picked up from the dartanalyzer arguments which could get the compiler into that state so we should double check.

**Comment by jmesserly** [comment]
this will be obsolete once we move to dartdevk/CFE (fortunately!)

**Comment by natebosch** [comment]
We're effectively moving to DDK with `build_web_compilers` 2.0.0 and I don't think this is an issue anymore.
