### ISSUE TITLE
Iterable.map, forEach and expand have bad parameter name.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30399]
`Iterable.map`, `forEach` and `expand` use `f` as parameter name.

Is there a better name?

**Comment by natebosch** [comment]
Also `any` and `every` - these should probably get named `test` to match a few other methods.
`map` and `expand` could use `convert` to match `Stream`
`forEach` could use `action` to match `Stream` - and the same can be fixed in `Map.forEach`

**Comment by lrhn** [comment]
Fixed in f5a1dd57a10796b9adf7e34bc22f367e3817a60a
