### ISSUE TITLE
Analyzer improvement for switch statements

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#30398]
When a switch has to return a value, the reported error is not always accurate. For example:
```
int function(MyEnum input) {
  switch (input) {
    ...
  }
}
```
Even when all enumeration cases are present a default block is necessary according to the analyzer. This kind of defeats the advantage of having warnings about missing enum values, and it forces adding completely unnecessary codes. Also, and I think this  is an issue with how if statements are processed, this also gives an error (last statement of case should be ...)
```
switch (input) {
  case 1:
    if (...) {
      return 1;
    } else {
      return 2;
    }
}
```

**Comment by bwilkerson** [comment]
> Even when all enumeration cases are present a default block is necessary according to the analyzer.

I'd guess that you don't have an explicit case for `null`, even though `null` is a valid value for `input`.

> ... I think this is an issue with how if statements are processed ....

Actually, it's an issue with the way the spec is written. Analyzer is confirming to the spec.

**Comment by bergwerf** [comment]
Hmm, fair point about null. It might be possible to have an analyzer rule
that default should only be used for null and cases for every enum value
should still be present. But I'm not sure if that would fit within the
priorities of the analyzer.

As for the if/else, I see this is not an issue with the analyzer. It has
been bugging me every time though. Maybe the spec can be updated in this
regard.

**Comment by zoechi** [comment]
I guess your `null` issue would be fixed with non-nullable types (if this is still on the table - I assume so).

**Comment by bergwerf** [comment]
I have not yet heard of non-nullable types. That would be amazing! (for many other things too)

**Comment by srawlins** [comment]
@bergwerf I'm going to close this as it seems your example has been solved. Additionally, the if/else case is frustrating, but has been captured in https://github.com/dart-lang/sdk/issues/28042.
