### ISSUE TITLE
Add a setter for `List.first|last`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30407]
I ❤️ 💘 😍 `T get first` and `T get last` for the `List` interface - 💝 it.

It makes really sad I can't use the same great API to _set_ the first or last element:

```dart
void main() {
  var list = [1];
  list.add(2);
  list.first = 0;
  list.last = 3;
  print(list); // [0, 3]
}
```

That would make me _very_ happy. It looks easily inline-able too!

**Comment by lrhn** [comment]
I'm positive to this change (https://github.com/dart-lang/sdk/commit/f528beb9f2f99ac1716b077ee66fb62cb32a4636) :smile:

**Comment by matanlurey** [comment]
I think was done? @lrhn

**Comment by matanlurey** [comment]
Looks like it was done:

```dart
void main() {
  var x = [1, 2];
  x.first = 2;
  x.last = 3;
  print(x);
}
```
