### ISSUE TITLE
Clarify Set / HashSet interface documentation to mention mutability

### ISSUE THREAD

**Issue by rkj** [dart-lang/sdk#30400]
Currently it doesn't mention anything about what happens when objects inside set are changed, and it can easily lead to incorrect behavior:
https://gist.github.com/d05a813d1104986a6f5c21ce09d8c172

**Comment by matanlurey** [comment]
Sorry, what language exists where this is a feature?

**Comment by rkj** [comment]
I mean "To mention that entries must not be mutated while stored in the set" or sth like that

**Comment by rkj** [comment]
The set interface doesn't mention it at all right now

**Comment by matanlurey** [comment]
Fair (and I see [Java's Set](https://docs.oracle.com/javase/7/docs/api/java/util/Set.html) does that), but I can't believe someone honestly thought the default behavior of `Map` or `Set` allowed for mutable hash codes...
