### ISSUE TITLE
Add default methods to allow evolutions on classes

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#30416]
I really like Dart implicit interface (every classes can be used as interface) but it makes harder to make evolutions on classes.
For instance it's almost impossible today to add a method to `Map` or `List` without releasing  a major version.
In Java, interfaces can evolve with the addition of default methods. Those methods are implemented only based on the interface methods.

I wondered if something like that could be done in Dart.

For instance, we could add a method `groupBy` on `Map` :

```dart
class Map<K,V> {
  // new method that will be used by classes implementing Map without defining groupBy
  default Map<K,List<E>> groupBy<K>(K key(E element)) {
    // my implementation that does not used private members
  }
}

class MyMap<K,V> implements Map<K,V> {
}
```

and my class `MyMap` that implements `Map` would have the new method without breakage. It would break only if the implementation as a method with the same name but with different parameters.

WDYT?

**Comment by matanlurey** [comment]
+1. We strongly need either this _or_ something like C#'s extension methods.

Otherwise it is too painful to evolve any library, which leads to a lot of fragmentation.

**Comment by eernstg** [comment]
In the language team we have discussed adding support for default methods for a while, using exactly the same motivation as given here (to allow widely used interfaces to grow). I've added a reference to this issue in an internal language design issue.

**Comment by matanlurey** [comment]
The lack of something like this just made a ~5 minute task into a ~5 hour one :(

**Comment by a14n** [comment]
See dart-lang/language#884

**Comment by lrhn** [comment]
Yep, deferring this to the language repo issue.
