### ISSUE TITLE
Add keywords field to pubspec.yaml

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#30418]
Search results on https://pub.dartlang.org/ could be improved with the addition of keywords for packages. It could also improve the home page by listing packages via popular keywords. For prior art, see https://crates.io/ and http://doc.crates.io/manifest.html

From the previous link:
```toml
# This is a list of up to five keywords that describe this crate. Keywords
# are searchable on crates.io, and you may choose any words that would
# help someone find this crate.v
keywords = ["...", "..."]
```

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/pub#1686
