### ISSUE TITLE
Please, clarify description for Stream.asBroadcastStream()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30412]
The [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/asBroadcastStream.html) for dart:async:Stream.asBroadcastStream() reads:

> Stream<T> asBroadcastStream({
> void onListen(
> StreamSubscription&lt;T&gt; subscription
> ),
> void onCancel(
> StreamSubscription&lt;T&gt; subscription
> )
> })
> Returns a multi-subscription stream that produces the same events as this.
> 
> The returned stream will subscribe to this stream when its first subscriber is added, and will stay subscribed until this stream ends, or a callback cancels the subscription.
> 
> If onListen is provided, it is called with a subscription-like object that represents the underlying subscription to this stream. It is possible to pause, resume or cancel the subscription during the call to onListen. It is not possible to change the event handlers, including using StreamSubscription.asFuture.
> 
> If onCancel is provided, it is called in a similar way to onListen when the returned stream stops having listener. If it later gets a new listener, the onListen function is called again.
> 
> Use the callbacks, for example, for pausing the underlying subscription while having no subscribers to prevent losing events, or canceling the subscription when there are no listeners.

Please, clarify:
1. When `onListen` is called? Is it called for every new listener of returned stream? Or it is called only for first such listener? Or may be it is called when returned stream subscribes to the original stream?
2. When 'onCancel` is called? Is it called for every listener that cancels subscription or only for the last one?

The following sample code demonstrates current behaviour:
```
import "dart:async";

main() {
  Stream s = new Stream.periodic(new Duration(milliseconds:100), (i)=>i).take(10);

  Stream b = s.asBroadcastStream(
      onListen:(ss) { print("onListen");},
      onCancel:(ss) { print("onCancel");}
  );

  int count1 = 3, count2 = 2, count4 = 2, count5 = 3;

  StreamSubscription ss1, ss2, ss4, ss5;
  ss1 = b.listen((v) {print("1: $v"); if (--count1==0) ss1.cancel();});
  ss2 = b.listen((v) {print("2: $v"); if (--count2==0) ss2.cancel();});
  b.listen(print, onDone:() { print("done3");}).cancel();

  new Future.delayed(new Duration(milliseconds:500), ()  {
    ss4 = b.listen((v) {print("3: $v"); if (--count4==0) ss4.cancel();});
    ss5 = b.listen((v) {print("4: $v"); if (--count5==0) ss5.cancel();});
  });
}
```
Output:

> onListen
> 1: 0
> 2: 0
> 1: 1
> 2: 1
> 1: 2
> onCancel
> onListen
> 3: 5
> 4: 5
> 3: 6
> 4: 6
> 4: 7
> onCancel

Which means `onListen` is called only for the first listener, when there were no listeners and `onCancel` is called only for the last listener. Both are not obvious from the description. Especially for the 'onCancel`:

> If onCancel is provided, it is called in a similar way to onListen when the returned stream stops having listener.

Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"

**Comment by lrhn** [comment]
Documentation has been updated. https://dart-review.googlesource.com/c/sdk/+/201567
