### ISSUE TITLE
Add categories to pubspec.yaml

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#30419]
Search results on https://pub.dartlang.org/ could be improved with the addition of categories for packages. It could also improve the home page by listing packages via popular categories. These categories must match a pre-defined list. For prior art, see https://crates.io/ and http://doc.crates.io/manifest.html

From the previous link:
```toml
# This is a list of up to five categories where this crate would fit.
# Categories are a fixed list available at crates.io/category_slugs, and
# they must match exactly.
categories = ["...", "..."]
```

**Comment by mnordine** [comment]
Related: https://github.com/dart-lang/sdk/issues/30418

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/pub#1685
