### ISSUE TITLE
Future class should mention that it doesn't like Future as generic argument.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30415]
You generally cannot create a Future of a Future.

We should mention this explicitly in the documentation of the Future class.

**Comment by lrhn** [comment]
Alternatively, we should drop that requirement, which I think is our plan anyway.

You can make a `Future<Future<int>>` if you really want to, and the `Completer<Future<int>>` has a complete method with type `void Function(FutureOr<Future<int>>)`. In a typed setting, we will distinguish the `Future<int>` and `Future<Future<int>>` arguments of the `FutureOr` union type and "do the right thing".

We need to be careful around `Future<Object>`, though. A `Completer<Object>`'s `complete` method has type `void Function(FutureOr<Object>)`, so if you pass a `Future<int>` to that, will it unpack it or not - either is valid (I think it should unpack *once*, but not recursively, which is also what I want `await` to do in the Dart 2 spec).

**Comment by lrhn** [comment]
With Dart 2.0, this is no longer the case. You can make a `Future<Future<int>>`, and you can complete a `Completer<Future<int>>` with a `Future<int>` without getting into problems.
(You *shouldn't* have a future of a future - something which eventually resolves to something which eventually resolves to an `int` ... should just eventually resolve to that `int`. There can be situations where you want two different chances to emit errors, though).
