### ISSUE TITLE
Analyzer server reports bogus

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#30424]
I am working on flutter on this branch: https://github.com/goderbauer/flutter/tree/foo23

If I run `flutter analyze --flutter-repo --watch` it shows zero issues.
If I go back one revision with `git checkout f1f5d4f3a8f4ee5a59c6fe0ea263ee294585de87`, above command now shows 23 issues, which are all false. If I restart the analyze command, it now shows 15 issues, which are still all false. If I delete `~/.dartServer` and restart the flutter analyze command it shows (correctly) 0 issues again.

@Hixie

**Comment by bwilkerson** [comment]
@scheglov Sounds like we're taking stale data from the cache. Any ideas about what might be causing this?

**Comment by scheglov** [comment]
This fails.
What should I check out?
Where should I run `flutter analyze --flutter-repo --watch`?

```
$ git clone https://github.com/goderbauer/flutter/tree/foo23
Cloning into 'foo23'...
remote: Not Found
fatal: repository 'https://github.com/goderbauer/flutter/tree/foo23/' not found
```

**Comment by goderbauer** [comment]
It's on a branch:
```
$ git clone https://github.com/goderbauer/flutter
$ cd flutter
$ git checkout origin/foo23
```
In there you can run the commands I mention in my first post. The flutter executable is in `./bin/flutter`.

**Comment by scheglov** [comment]
I have much more errors.

```
dart/issue30424/flutter ((6953d9134...))$ ./bin/flutter analyze --flutter-repo --watch
[cut]
  error • The function 'expect' isn't defined. • packages/flutter_test/test/widget_tester_test.dart:243:5
  error • The function 'expect' isn't defined. • packages/flutter_test/test/widget_tester_test.dart:246:5
72637 issues found • analyzed 1157 files, 3.21 seconds
```

**Comment by goderbauer** [comment]
Before the analyze command you probably also need to run "flutter
update-packages --upgrade".

**Comment by scheglov** [comment]
Thanks. I can reproduce the problem.

**Comment by scheglov** [comment]
This turned out to be a bug in summary linker when one of the libraries in resynthesized.
It is not caused by stale data in the cache.

The reason why this problem does not happen with empty cache is that in this case we relink all libraries together. So, none of the libraries in resynthesized, and we inherit `covariant` flag correctly.

This CL will fix the linker to resynthesize `covariant` flag while linking.

https://codereview.chromium.org/2994913002

**Comment by goderbauer** [comment]
Thank you so much for the quick turn-arround on this!

Once your fix is submitted, will this just be part of the next Dart SDK dev release?

**Comment by bwilkerson** [comment]
> Once your fix is submitted, will this just be part of the next Dart SDK dev release?

Yes.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/befe86b6a36d7a60ea72c56bbf5ab07b4a5d4fa0
