### ISSUE TITLE
assert function arguments aren't run in dev compiler

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#30426]
In the dev compiler, the following code does not print and does not raise an AssertionError.

```dart
main() {
  assert(() {
    print('assert body run');
    return false;
  });
}
```

Boolean expression asserts, however, work as expected.
```dart
main() {
  assert(false); // throws AssertionError
}

**Comment by vsmenon** [comment]
This was fixed a few weeks in bleeding edge (just tested).
