### ISSUE TITLE
DDC cannot tear off a function with contravariant use of generic in its return type (improper type check)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30427]
This is a variation on #30423, where the contravariant use of the generic type is in the return type of the tear off rather than in an argument.  Consider the following code:

```dart
typedef void F<T>(T x);
typedef F<T> G<T>();
class C<T> {
  F<T> _x;
  C(this._x);
  F<T> f() => _x;
}
void g(C<num> c) {
  c.f; // (1)
}
void h1(int i) {}
void h2(num n) {}
main() {
  g(new C<int>(h1));
}
```

This passes static type checks in strong mode and is compiled without complaint by DDC.  At runtime, an exception is thrown at (1).  This alone is unsurprising, since one possible way of restoring soundness is to type check the tear off.  However, the exception message is concerning.  It says: `Type '() -> F((int) -> void)' is not a subtype of type 'F((num) -> void)'`.

I would have expected DDC to check that the runtime type of `c.f` was a subtype of its static type.  And indeed, `() -> F((int) -> void)` is the correct runtime type of `c.f`.  (Note that `F(...)` in the type signature just tells the user that the type originated in the typedef of F.  This is equivalent to the type `() -> (int) -> void`.)  However, `F((num) -> void)` is not the correct static type of `c.f`.  It should be `() -> (num) -> void`.

The generated code for `g` confirms that we appear to be checking against the wrong type:

```javascript
covariant_subtyping_tearoff_experiment_test.g = function(c) {
  FOfnum()._check(dart.bind(c, 'f'));
};
```

If we change `main` to:
```dart
main() {
  g(new C<num>(h2));
}
```

there should no longer be any type error.  But DDC now throws the exception `Type '() -> F((num) -> void)' is not a subtype of type 'F((num) -> void)'`.

It seems that DDC is trying to check that the runtime type of the tear off matches its static type, but it's actually checking that the runtime type of the tear off matches its static *return* type.

**Comment by stereotype441** [comment]
@jmesserly FYI

**Comment by jmesserly** [comment]
(moved to strong mode, DDC itself does not place these checks.)

**Comment by jmesserly** [comment]
Yeah, this is also the flaw of our tests that check *where* we place casts, but not *what* type we're casting to. Doh! :)

Should be an easy fix. Will send CL shortly.
