### ISSUE TITLE
building from source on fedora 25 (x64)

### ISSUE THREAD

**Issue by crunch3** [dart-lang/sdk#30435]
Executing: ./tools/build.py --mode release --arch x64 create_sdk
I get the following...
gn gen --check in out/ReleaseX64
Traceback (most recent call last):
  File "/home/mike/Downloads/dart-lang/sdk/tools/gn.py", line 496, in <module>
    sys.exit(Main(sys.argv))
  File "/home/mike/Downloads/dart-lang/sdk/tools/gn.py", line 483, in Main
    results = pool.map(RunCommand, commands, chunksize=1)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
Tried to run GN, but it failed. Try running it manually:
        $ python /home/mike/Downloads/dart-lang/sdk/tools/gn.py -m release -a x64 -               -os host -v
Traceback (most recent call last):
  File "./tools/build.py", line 616, in <module>
    sys.exit(Main())
  File "./tools/build.py", line 609, in Main
    mode, arch) != 0:
  File "./tools/build.py", line 489, in BuildOneConfig
    args = BuildNinjaCommand(options, target, target_os, mode, arch)
  File "./tools/build.py", line 471, in BuildNinjaCommand
    if UseGoma(out_dir):
  File "./tools/build.py", line 429, in UseGoma
    return 'use_goma = true' in open(args_gn, 'r').read()
IOError: [Errno 2] No such file or directory: 'out/ReleaseX64/args.gn'

**Comment by rmacnak-google** [comment]
Did you get an error when you `gclient sync`d? I suspect it failed or got interrupted if you're missing out/ReleaseX64/args.gn.

**Comment by crunch3** [comment]
I didn't have gclient.  I used git clone https://github.com/dart-lang/sdk/ in a dart-lang directory.
I deleted the sdk, re-cloning with git and got the same error.  gn.py (496 lines worth) is present in tools.
....... so, I installed the depot_tools and building!

**Comment by wzhuzhu** [comment]
on fc26, build ok.
step:
~~~
sudo yum -y install git subversion make gcc-c++  libstdc++.i686
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=$PATH:`pwd`/depot_tools
mkdir dart-sdk
cd dart-sdk
gclient config https://dart.googlesource.com/sdk.git
gclient sync
cd sdk
./tools/build.py --mode release --arch x64 create_sdk
~~~

**Comment by MuhammadAlaeldin** [comment]
I made the steps and terminal shows me that. what the solution to build dart sdk ?

```
ninja -C out/ReleaseX64 create_sdk
ninja: Entering directory `out/ReleaseX64'
ninja: error: loading 'build.ninja': No such file or directory
BUILD FAILED

```
