### ISSUE TITLE
Insert imports on paste: wrong imports position if previously there were no imports in the file

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#30430]
This is about `AnalysisServer.edit_importElements` method. E.g. if you copy `new Random();` in some green file and then paste it here:
```
main() {
  <caret>
}
```
you'll get 
```

import 'dart:math';main() {
  new Random();
}
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/3002643002/
