### ISSUE TITLE
Please do a couple merges for dart2js into -dev

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30449]
@whesse @mit-mit @kasperl

These are all related to deferred loading:
 - fix an issue reported by an internal customer: the fix was done over 2 commits: f1e34ffd11 and cf43d4603c
 - add more diagnostic for deferred loading failures: 9c4b1991b438b8479497ec8c0e79728fe9403bc9

These have been cherry-picked for our customers internally, but it would be good to ensure that they are also included in the -dev channel.

**Comment by mit-mit** [comment]
Do you actually mean dev, or do you mean these should be shipped in a new stable patch build (i.e., 1.24.3) ?

**Comment by whesse** [comment]
I have just pushed a new full push to dev, that includes these commits (if they are on master), 1.25.0-dev.11.0.

**Comment by sigmundch** [comment]
perfect, -dev was all that we needed, thanks!
