### ISSUE TITLE
analysis server quick fix providing incorrect offsets

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#30444]
More details here: https://youtrack.jetbrains.com/issue/WEB-28309

For the create local variable quick fix, it looks like the analysis server is providing source locations that are based on locations _after_ the fix would be applied.

**Comment by alexander-doroshko** [comment]
Clarification: [Linked Edits](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#type_LinkedEditGroup) should have offsets that are valid AFTER source changes are applied, but looks like they do not. Yes, all the details are in https://youtrack.jetbrains.com/issue/WEB-28309.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2997073002/
