### ISSUE TITLE
My application crashes the Dart compiler

### ISSUE THREAD

**Issue by Bikeman868** [dart-lang/sdk#30441]
D:\Git\Martin\Urchin\Urchin.Server.Owin\Ui>pub build 
Loading source assets...
Building Urchin.ui...
[Info from Dart2JS]:
Compiling Urchin.ui|web/main.dart...
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

OS Version: Windows 10 Pro
Hardware: Micorsoft Surface with i5-4300U CPU @ 1.90GHz 2.5 GHz 4GB RAM
Dart SDK: Version 1.24.2

Steps to reproduce:
1. Download source code from https://github.com/Bikeman868/Urchin/tree/1605063cea002ecf3125e78aea8facf901f7d4fd
2. Open a command window
3. Change to the Urchin.Server.Owin\Ui folder
4. pub get
5. pub build

**Comment by zoechi** [comment]
Is `D:` a network drive? Can you try to move the project to `C:`? Does that change anything?

**Comment by sigmundch** [comment]
@Bikeman868 on my linux machine I was not able to reproduce the crash. I wonder if this is a windows specific issue.

Was there a stack trace after the compiler error message you saw above? Could you attach it here as well? It might provide a clue of what's going on.

**Comment by Bikeman868** [comment]
Thanks for looking into this for me. It turned out that my SDK install was missing some folders (not sure how) and re-installing the SDK fixed the issue.
