### ISSUE TITLE
Suggestions should ignore letter case

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30446]
![image](https://user-images.githubusercontent.com/1580663/29337642-4d387226-8212-11e7-842d-fc9653f7f702.png)

Developers aren't suppose to remember if it is `.Host` or `.host`.

**Comment by alexander-doroshko** [comment]
See Settings (Preferences) | Editor | General | Code Completion | Case sensitive completion. The default value is 'First letter'. You may change it to 'None'.

**Comment by JFixby** [comment]
Thank you. Sorry for the noise.
