### ISSUE TITLE
[feature request] suggestions should be searched by occurrences

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30447]
Example from Eclipse:

![image](https://user-images.githubusercontent.com/1580663/29337800-05a7caa0-8213-11e7-8b7d-b6d8572056c4.png)

**Comment by alexander-doroshko** [comment]
It is, isn't it?
![image](https://user-images.githubusercontent.com/4499789/29338317-4b182512-821d-11e7-9ee3-69fed64f6f74.png)

**Comment by JFixby** [comment]
![image](https://user-images.githubusercontent.com/1580663/29362378-1063fe7c-828c-11e7-874f-0ad0210df9ce.png)

Right it was because of the case https://github.com/dart-lang/sdk/issues/30446#
