### ISSUE TITLE
Dart2JS can't compile with generic method named `set`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#30457]
https://dartpad.dartlang.org/0e7d8c32d6ad60967d6198ef8f70090a

```dart
main() {
  new Foo().set();
}

class Foo {
  void set<T>() => print('ran');
}
```

```
Error compiling to JavaScript:
main.dart:6:3:
Error: Unexpected token 'void'.
  void set<T>() => print('ran');
  ^^^^
main.dart:2:3:
Warning: The method 'set' is not defined for the class 'Foo'.
  new Foo().set();
  ^^^^^^^^^^^^^^^
Error: Compilation failed.
```

Originally reported at https://github.com/dart-lang/angular/issues/582 - cc @JackHerring, @jrote1

We allow the method name without a generic argument, and we allow the generic argument with a different method name - This seems to be a small gap in our parsing.

**Comment by matanlurey** [comment]
There is a similar bug for `get` you can probably de-dupe with.

**Comment by sigmundch** [comment]
yep, likely the same issue as https://github.com/dart-lang/sdk/issues/29349

**Comment by natebosch** [comment]
Ah yeah same issue - that one looks like it has more detail.
