### ISSUE TITLE
dartdevc testing failing on a testname containing hyphen "-".

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30450]
Running test.py -cdartdevc -rchrome is failing on a test whose filename contains a hyphen, because the constructed HTML and JS try to use that filename as an identifier, I think, and the hyphen is the minus operator.  This happens with co19 strong_mode branch test LayoutTests/fast/selectors/specificity-overflow_t01.test. The test.html page that causes the error says:
(error on the line with >>>>> (added))

...
// Don't try to bring up the debugger on a runtime error.
window.ddcSettings = {
  trapRuntimeErrors: false
};
</script>
<script type="text/javascript"
        src="/root_dart/third_party/requirejs/require.js"></script>
<script type="text/javascript">
requirejs(["specificity-overflow_t01", "dart_sdk", "async_helper"],
>>>>>>>>>>>>>>>>    function(specificity-overflow_t01, dart_sdk, async_helper) {  
  dart_sdk.dart.ignoreWhitelistedErrors(false);
  
  // TODO(rnystrom): This uses DDC's forked version of async_helper. Unfork
  // these packages when possible.
  async_helper.async_helper.asyncTestInitialize(function() {});
  dart_sdk._isolate_helper.startRootIsolate(function() {}, []);
  dartMainRunner(specificity-overflow_t01.specificity-overflow_t01.main);
});
</script>
</body>
</html>

**Comment by whesse** [comment]
A CL with a (hackish) fix for this is https://codereview.chromium.org/3001773002
@munificent

**Comment by whesse** [comment]
And dots are also changed to $46 by requirejs, so the line in the hack is

dartMainRunner(billbillxx["${testName.replaceAll('-', '\$45').replaceAll('.', '\$46')}"].main);

**Comment by munificent** [comment]
Can we just rename the test file?

**Comment by whesse** [comment]
There are thousands of them.  The change I have is more correct than the
current behaviour, I think.

**Comment by whesse** [comment]
dartdevc and dartdevk are still not executing tests from co19, but it doesn't seem to be a problem about hyphens anymore.

**Comment by vsmenon** [comment]
I think this is fixed now.
