### ISSUE TITLE
VM should provide the location of outline.dill/platform.dill to the kernel-service.

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30456]
Right now kernel-service is trying to infer this based on the layout of the repo. Instead the VM should provide the information so that it is consistent with how it will internally find those .dill files itself.

At this time, the VM uses the  --kernel-binaries flag for this, so we should forward the value of that flag to the kernel-service and provide it as the sdkRoot in the FE compiler options.

Until we fix issue #30111 we should continue to specify the CompilerOptions.sdkSummary explicitly (but instead of inferring it from the dart executable
https://github.com/dart-lang/sdk/blob/35f6d5da1bebfce3b25b328a37084b09b85c97fb/utils/kernel-service/kernel-service.dart#L53, we should infer it from the sdkRoot/kernel-binaries folder). Once #30111 is fixed, it should be sufficient to pass the CompilerOptions.sdkRoot only, and the compiler will then find the `outline.dill` file from there.

**Comment by aam** [comment]
https://codereview.chromium.org/3001013002/ has potential fix.

**Comment by aam** [comment]
Fix landed.
