### ISSUE TITLE
Please move function-type syntax doc to this repo

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/sdk#30459]
@eernstg has a doc that describes function-type syntax, but it's in a [personal gist file](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa) on GitHub. It should be in the language spec but, failing that, please move it to [this repo](https://github.com/dart-lang/sdk/tree/master/docs/language).

I'm going to be linking to this file from www.dartlang, so please let me know when it's been moved so I can update the link.

cc @kwalrath @kevmoo 

Thx!

**Comment by eernstg** [comment]
Right, every informal spec which becomes part of the language should be in the docs/language/informal directory, and it will be integrated into the language specification monograph.

The first step has in fact already been taken for this document (current version [here](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-function-type-alias.md)). So you should be OK already!
