### ISSUE TITLE
Support generic methods in Fasta

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#30455]
Fasta's support for generic methods is not yet complete, and has several bugs, which can evidenced by disabling type erasure and running Fasta's output through the verifier.

When these issues are resolved, we may continue implementing support for generic methods in the VM.
This issue number is used as a tag through the VM source to indicate where this support is incomplete due to the currently inability to test it.

**Comment by peter-ahe-google** [comment]
Did you also turn on strong mode when you disabled erasure?

**Comment by sjindel-google** [comment]
My understanding is that strong mode is enabled/disabled on a test-by-test basis -- it's given as a parameter to the vm_fasta target.

Currently, were are only performing erasure in this target when strong mode is off, but it seems that most tests run in this way.

**Comment by sigmundch** [comment]
@peter-ahe-google I recall you did a bunch of fixes for type-variables/generics in the last few weeks. Is this still an open issue?

Just trying to figure out whether there are still issues to work on before we disable erasure.

**Comment by peter-ahe-google** [comment]
I think this is still an issue.

@sjindel-google I'd like a bit more details about how to reproduce this problem. For example:

1. Apply this patch.
2. Run this command.

**Comment by sjindel-google** [comment]
There are two problems:

1. Fasta generates invalid output on some programs which is hidden by erasure.

The VM's default behavior for generic methods (in the absence of the "reify" flags) is to replace type-parameters with dynamic. So even if generic method type parameters are not erased, the VM will do it itself. Even so, fasta generates invalid kernel for some programs with generic methods, which the VM cannot read.

To evidence this, disable erasure in `vm_fasta.dart` and run:
```
python tools/test.py -m release --checked -t 240 pkg/front_end/test/fasta/bootstrap_test
```

2. VM support for generic methods in Kernel is incomplete.

The support Regis has implemented in the VM for actual generic methods has not been fully ported to the kernel reader. When `--reify` and `--reify-generic-functions` are supplied to the VM, it will not erase type parameters on generic methods. However, since support for running kernel code with these is incomplete, the VM will crash when erasure is disabled and these flags are passed. 

To evidence this, disable erasure in `vm_fasta.dart` and run:
```
python tools/test.py -m release -c dartk --vm-options "--reify --reify_generic_functions" co19
```

**Comment by a-siva** [comment]
@crelier

**Comment by peter-ahe-google** [comment]
@sjindel-google please add the following information to this bug:

1. A patch that applies to the sdk repository.

2. A single command that fails, not all of the co19 test suite.

**Comment by sjindel-google** [comment]
Patch:
```
diff --git a/test.dart b/test.dart
new file mode 100644
index 0000000000..fcf70b833d
--- /dev/null
+++ b/test.dart
@@ -0,0 +1,5 @@
+void iser<X>(x) {
+  print(x is X);
+}
+
+main() => iser<int>("hi");
```

Repro:
```
DART_CONFIGURATION=ReleaseX64 ./pkg/front_end/tool/fasta compile test.dart
MODE=ReleaseX64 out/$MODE/dart --reify --reify_generic_functions -c test.dart.dill
```

The last command outputs "true" when it should output "false".

**Comment by sjindel-google** [comment]
Type erasure is dead.
