### ISSUE TITLE
Consider optimizing `is List` in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30464]
Checking that a value is a `List<dynamic>` is quite common in performance critical JSON (de)serialization code.  It seems like we should be able to generate a fast path cutoff that would catch the common case where the `List` is a `JsArray`.

**Comment by jmesserly** [comment]
a quick check indicates that we'd be much faster checking for a property (on the instance) vs an instanceof. (I think dart2js may do something similar)

**Comment by jmesserly** [comment]
FYI, I'm looking at general fixes for class/interface types too, But a fast path for `is List` (and `is Map`?) does sound like a good start, as fixing all interfaces and especially generics is a bit more complex. :)

**Comment by jmesserly** [comment]
Another updated: there's various private types we test like in the SDK:

- JSArray.is
- JSExtendableArray.is
- JSFixedArray.is
- JSIndexable.is
- JSMutableArray.is
- JSObject.is
- JSSyntaxRegExp.is
- JSArray._check

I'm going to see what these are about, but they all seem like candidates for optimization.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3003613002/
JSArray should be mostly fixed by the new class type checks.

I haven't looked at the other ones yet.
