### ISSUE TITLE
Duplicate the vm-kernel build bots with strong mode enabled

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30469]
It would be great if we could duplicated the existing four vm-kernel builders to test strong mode.

@stereotype441 @sigmundch

**Comment by sigmundch** [comment]
that would be awesome!

I believe we need to do some work on the VM to allow the test scripts to require strong mode.

@aam - would it be easy to add to the VM another flag to pass to kernel-service so it can run in strong-mode?

**Comment by aam** [comment]
@sigmundch , sure, should be really straightforward.

**Comment by athomas** [comment]
Closing, all the vm-kernel bots run tests in strong and not strong mode. Not sure when that has changed.
