### ISSUE TITLE
Constant canonicalization of maps error in DDC

### ISSUE THREAD

**Issue by mkj-gram** [dart-lang/sdk#30466]
The test language_2/compile_time_constant_k_test.dart fails, because of what seems to be incorrect constant canonicalization of maps. The following reduced test should provoke the issue:

```dart
import "package:expect/expect.dart";

const x = const { 'a': 4 };
const x2 = const {'a': 4};

main() {
  Expect.identical(x2, x);
}
```

**Comment by jmesserly** [comment]
this is fixed in https://dart-review.googlesource.com/c/sdk/+/8167
