### ISSUE TITLE
DDC fails to substitute type parameters when generating a forwarding stub

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30461]
Consider the following code:

```dart
import 'package:expect/expect.dart';

typedef F<T>(T x);

class B<T> {
  void f(F<T> x) {}
}

abstract class I<U> {
  void f(U x);
}

class C<V> extends B<V> implements I<F<V>> {}

void acceptsObject(Object o) {}

void acceptsNum(num n) {}

bool isTypeError(e) => e is TypeError;

void g(I<F<num>> i) {
  i.f(acceptsObject);
  // i.f has static type (F<num>)->void, or ((num)->void)->void.  Which means we
  // are statically allowed to pass acceptsNum to it.  However, if i's runtime
  // type is C<Object>, then it extends B<Object>, so its f function requires
  // its argument to be F<Object>.  This means that passing acceptsNum to f
  // would violate soundness (since acceptsNum has type F<num>, and F<num> is a
  // supertype of F<Object>).  So we expect a type error here.
  Expect.throws(() {
    i.f(acceptsNum);
  }, isTypeError);
}

void main() {
  g(new C<Object>());
}
```

Running this test with DDC leads to the exception `ReferenceError: T is not defined`.  The generated code at the site of the exception is:

```javascript
let FOfT = () => (FOfT = dart.constFn(covariant_subtyping_bug_test.F$(T)))();
```

And indeed, there is no definition of `T` in scope.

It appears that what has happened is that DDC synthesized a forwarding stub for the class `C` equivalent to the following Dart code:

```dart
class C<V> extends B<V> implements I<F<V>> {
  void f(F<T> x) => super.f(x);
}
```

But it should have substituted `V` for `T` (since `T` represents the type argument of `B`, and `C<V>` extends `B<V>`) and generated:

```dart
class C<V> extends B<V> implements I<F<V>> {
  void f(F<V> x) => super.f(x);
}
```

I'll submit a CL adding this test case to `tests/language_strong` shortly.

**Comment by stereotype441** [comment]
@jmesserly @leafpetersen FYI

**Comment by jmesserly** [comment]
thanks I will have a look. yeah, it's looks like DDC has the raw uninstantiated method from the superclass. OverrideChecker in Analyzer was supposed to be marking the MethodElement/ParameterElement with the correct substitutions already in place, I'll have to see how that got lost. (It would be tricky to fix from the DDC side, as the logic for doing it exists in OverrideChecker)

**Comment by jmesserly** [comment]
Probably this will be an Analyzer Strong Mode fix but we'll see. It's possible CodeChecker is jumping to the raw element. Either way they need to be in agreement :)

**Comment by jmesserly** [comment]
this was a bug in both DDC and analyzer :) ... OverrideChecker was discarding the substitution information, but even fixing that, DDC was also discarding the substitution information (by jumping to the `.enclosingElement` of the parameter). I've fixed both, about to send out a CL.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3008053002/
