### ISSUE TITLE
Performance regressions (snapshot size, velocity tracker microbenchmark)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30472]
When we rolled the Flutter engine from fef7d827d6e22830ee6c88e8260f118a6b3fbcd9 to a246501917b8b77e856db253817ce7c2cc25b9c2 in https://github.com/flutter/flutter/pull/11643, which included rolling Dart from 734beef0624a9b246e892c95ca0c301c5d318331 to 491390eeaa7974f44a8931d10a899c39c0df8dda in https://github.com/flutter/engine/pull/3984, the following benchmarks regressed:

*App size benchmarks:*
basic_material_app__size release_size_in_bytes
basic_material_app_ios__size release_size_in_byte
complex_layout__build aot_snapshot_size_instructions
complex_layout__build aot_snapshot_size_isolate
complex_layout__build aot_snapshot_size_rodata
complex_layout__build aot_snapshot_size_total
flutter_gallery__build aot_snapshot_size_instructions
flutter_gallery__build aot_snapshot_size_isolate
flutter_gallery__build aot_snapshot_size_rodata
flutter_gallery__build aot_snapshot_size_total
flutter_gallery_win__build aot_snapshot_size_instructions
flutter_gallery_win__build aot_snapshot_size_isolate
flutter_gallery_win__build aot_snapshot_size_rodata
flutter_gallery_win__build aot_snapshot_size_total

*Build time benchmarks:*
basic_material_app__size build_time_millis (maybe? hard to tell due to noise)

*Execution time benchmarks:*
microbenchmarks velocity_tracker_iteration

**Comment by Hixie** [comment]
![image](https://user-images.githubusercontent.com/2686902/29391530-c84f661e-82ac-11e7-8264-2ef64028d382.png)
![image](https://user-images.githubusercontent.com/2686902/29391556-f6a02d50-82ac-11e7-8d89-8ccc8147a327.png)

**Comment by jason-simmons** [comment]
Traced this to https://github.com/dart-lang/sdk/commit/8ee4436355cf8434b99893fa014980adb17f572e

That PR mostly involved #define DART_PRECOMPILED_RUNTIME.  Flutter probably needs an update to its build scripts.  In an android_release build, it looks like we're defining DART_PRECOMPILER but not DART_PRECOMPILED_RUNTIME.

**Comment by rmacnak-google** [comment]
That change doesn't expect any change on Flutter's side. It's only effect should be a smaller VM in the engine.

**Comment by Hixie** [comment]
@rmacnak-google Are you looking into fixing this issue, or is this something we should be chasing ourselves?

**Comment by jason-simmons** [comment]
This was caused by https://github.com/dart-lang/sdk/commit/8ee4436355cf8434b99893fa014980adb17f572e accidentally flipping the unbox_numeric_fields flag.

That change has been reverted.

**Comment by Hixie** [comment]
Ah, interesting. In that case there were at least three separate regressions in that roll. I'll file another bug for the stuff that was in this bug but didn't get fixed by that revert.

https://github.com/dart-lang/sdk/issues/30521
