### ISSUE TITLE
Strong mode runtime semantics in dart2js

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30476]
for the tests language_2/function_type/*_test, dart2js does not implement the strong mode `is` checks or the correct runtime function type for the tear off

**Comment by jmesserly** [comment]
dart2js is on Dart 2 now

**Comment by rakudrama** [comment]
`language_2.status` contains:
```
[ $compiler != dartdevc && !$checked ]
function_type/*: Skip # Needs checked mode.
```

Since `$checked` has no meaning in Dart 2, all tests are run as `!$checked` and these tests have not been run on dart2js.
Reopening, since 10 of the tests fail.
