### ISSUE TITLE
Add error to spec for use of a final variable in a for-in loop

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30489]
The specification should be updated to make it clear that there should be an error if a final variable declared outside the for-in loop is used as the loop variable in a for-in loop.

**Comment by eernstg** [comment]
[This CL](https://codereview.chromium.org/2998073002/) addresses assignments to final variables and also the special case with for-in.

**Comment by eernstg** [comment]
Addressed by [commit 6ef388db](https://github.com/dart-lang/sdk/commit/6ef388db9dc8f1a03187b56f0324697744e71aa3).
