### ISSUE TITLE
Clarify "is equivalent to"

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30488]
The specification should be updated to make it clear whether statements of the form "is equivalent to" apply to both static errors and runtime semantics or only the latter. See https://github.com/dart-lang/sdk/issues/30483#issuecomment-323363083 for some context.

**Comment by lrhn** [comment]
A specification should be unambiguous.

**Comment by eernstg** [comment]
Addressed in [this CL](https://codereview.chromium.org/2998173002/).

**Comment by eernstg** [comment]
Closed in [this commit](https://github.com/dart-lang/sdk/commit/3744197e3ce238c3efbc0dbdce7bb3ea8673ba26).
