### ISSUE TITLE
ddc_web_compiler.js is running during DDC startup?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30497]
I see evaluation of dart2js code in finishClasses from ddc_web_compiler.js during DDC startup.  I'd like to understand what this is doing and why, whether it only happens with dev tools open, and whether it happens on the main isolate or in parallel.

Tentatively assigning to @jacob314 since I think this might be devtools extension related code.

**Comment by leafpetersen** [comment]
@jacob314 Can you comment on this?  Is this a DDC extension thing?

**Comment by jacob314** [comment]
That is an extension thing. Alan is working on running the extension ddc_web_compiler.js in the extension's frame or on a worker which will also fix this issue.

**Comment by leafpetersen** [comment]
Great, thanks!

**Comment by jmesserly** [comment]
@alan-knight is this fixed now?

**Comment by Markzipan** [comment]
This bug seems to be out of date - closing.
