### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#3049]
See Eiffel for an example of core language support, C#/.NET and Java (including http://go/cofoja developed at Google) for less pretty but fully functional implementations.

This is a complex feature, filing now so it can be considered at the appropriate time.

(It might appeal to the people who have been asking for non nullable types.)

The major pieces that are needed are:
1. Tagging with predicates
   1.1 Tagging of classes with predicates: invariants
   1.2 Tagging of methods with predicates: preconditions, postconditions, (exceptional postconditions)
2. New keywords or functions for use in postconditions
   2.1 &quot;result&quot; refers to the method result
   2.2 &quot;old(foo)&quot; refers to the value of foo on method entry
3. Contract evaluation at runtime: execute before and after method invocations
   3.1 But not when evaluating a contract predicate
   3.2 With facility to enable/disable contracts by library
   3.3 With invariants ignored for &quot;private&quot; method calls (whatever this means for Dart)
   3.4 Inheriting contract predicates from superclasses, interfaces
4. A way to disable contracts and have the code execute as quickly as if there were no contracts

**Comment by chalin** [comment]
FYI. The addition of native C# support for **method contracts** was discussed at the [Jan 21, 2015 C# Design Meeting](https://github.com/dotnet/roslyn/issues/98). The issue used to track this specific feature is https://github.com/dotnet/roslyn/issues/119.
