### ISSUE TITLE
Improve the error message for assignment to final local variables

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30490]
Given the following code:
```
main() {
  final x = 0;
  x = 42;
}
```
Analyzer produces an error message that discusses the absence of a setter, but local variables do not induce getters and setters, so the error is confusing.

**Comment by srawlins** [comment]
The analyzer now produces a much more readable error:

```none
  error • The final variable 'x' can only be set once. • 30490.dart:3:3 • assignment_to_final_local
  hint • The value of the local variable 'x' isn't used. • 30490.dart:2:9 • unused_local_variable
```
