### ISSUE TITLE
gen_snapshot fails to run from kernel

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30504]
Given dill file instead of dart source, gen_snapshot fails:
```
out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-blobs --vm_snapshot_data=vm_snapshot_data --isolate_snapshot_data=isolate_snapshot_data --vm_snapshot_instructions=vm_snapshot_instr --isolate_snapshot_instructions=isolate_snapshot_instr --embedder_entry_points_manifest=dart_vm_entry_points.txt hello.dart.dill
Error: Dart_LoadScript: Unable to load script 'file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/hello.dart.dill' correctly.
```

It seems to fail in Dart_LoadScript("vmservice_io.dart") call made from vmservice_impl.cc VmService::Setup, called from gen_snapshot.cc CreateServiceIsolate. It seems that in main.cc embedder, before calling VmService::Setup telling it to skip loading from source we load vmservice from kernel first:
```
Dart_Handle library = Dart_LoadKernel(dfe.kernel_vmservice_io());
```

Sounds like we should be doing the same in gen_snapshot.

@sivachandra , what do you think?

**Comment by sivachandra** [comment]
@aam Likely yes. You are probably pointing to this change: https://codereview.chromium.org/2949323002/

**Comment by aam** [comment]
Apologies, analysis in second paragraph `It seems to fail...` is incorrect. Actually it fails because filename passed to the gen_snapshot is different from the url in the dill file itself. `hello.dart.dill` is  the filename, `hello.dart` is what is in the dill file. If I rename generated `hello.dart.dill` kernel binary to `hello.dart`, `gen_snapshot` works fine.

**Comment by aam** [comment]
Call at https://github.com/dart-lang/sdk/blob/master/runtime/vm/dart_api_impl.cc#L5074 is where it fails to find loaded script using `.dill`-file name.

@a-siva , in https://github.com/dart-lang/sdk/commit/33c50e93741bae4a2d675a3690c9a4906befc2a5 we changed how load kernel binaries, using Dart_LoadScript instead of Dart_LoadKernel. Perhaps you have some thoughts on whether tying .dill filename to the script name in the dill file was intended consequence of that change ?

**Comment by aam** [comment]
Difference between gen_snapshot and main(standalone vm embedder) is in that main.cc loads .dill kernel file via LoadKernel at https://github.com/dart-lang/sdk/blob/master/runtime/bin/main.cc#L850, while gen_snapshot tries to load .dill file with Dart_LoadScript.

**Comment by aam** [comment]
Difference between gen_snapshot and main(standalone vm embedder) is that main.cc loads scripts kernel via LoadKernel(https://github.com/dart-lang/sdk/blob/master/runtime/bin/main.cc#L850), while gen_snapshot uses LoadScript.

**Comment by aam** [comment]
eac18a3 did not quite fix the problem. It seems that `LoadKernelProgram` actually returns NULL in case of success, not valid handle to loaded program : https://github.com/dart-lang/sdk/blob/eac18a324c168de509f056a2bfcd3cdb56a312e4/runtime/vm/dart_api_impl.cc#L4985

**Comment by a-siva** [comment]
https://codereview.chromium.org/3009663002/ fixes the return value from LoadKernelProgram

**Comment by jensjoha** [comment]
Should the closing of this issue indicate that the command given at the top should work now?

For me it still crashes horribly: In "SetupStubNativeResolver" it creates a string (something like "import 'bla';") and then in "Dart_LoadLibrary" it passes it on to "LoadKernelProgram" (because I->use_dart_frontend() is true) where it is cast to kernel::Program* and we try to read it as such.

**Comment by aam** [comment]
@jensjoha , how do you get the .dill file you run `gen_snapshot` against? For me `gen_snapshot` for manually compiled .dill file fails with expected message that `dart:_vmservice` is not found, but flutter gallery .dill file produced by flutter tools works fine.
```
╰─➤  out/ReleaseX64/dart --packages=.packages pkg/front_end/tool/_fasta/compile.dart --platform=out/ReleaseX64/patched_sdk/platform.dill hello.dart
╰─➤  out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-blobs --vm_snapshot_data=vm_snapshot_data --isolate_snapshot_data=isolate_snapshot_data --vm_snapshot_instructions=vm_snapshot_instr --isolate_snapshot_instructions=isolate_snapshot_instr --embedder_entry_points_manifest=dart_vm_entry_points.txt hello.dart.dill
Error: Library 'dart:_vmservice' is not loaded. Did you forget to call Dart_FinalizeLoading?
```

**Comment by jensjoha** [comment]
I just compiled with fasta
```
out/ReleaseX64/dart pkg/front_end/tool/_fasta/compile.dart --packages=.packages --platform=out/ReleaseX64/patched_sdk/platform.dill helloworld.dart
```

content of helloworld.dart:
```
main() {
  print("Hello, World!");
}
```
