### ISSUE TITLE
BrowserClient incorrectly parses content-type in IE11

### ISSUE THREAD

**Issue by d3v-cl** [dart-lang/sdk#30507]
IE11 on Windows 8.1 (using BrowserStack) incorrectly parses the headers so that the content-type header is available as '\ncontent-type' only.

As a small workaround I've added:
```
class HttpClientStrippedHeaders extends BrowserClient {
  @override
  Future<StreamedResponse> send(BaseRequest request) async {
    StreamedResponse response = await super.send(request);
    if (response.headers.containsKey('\ncontent-type')) {
      print('Content-type header has been parsed as "\\ncontent-type".\n' +
          'Will add the same value under "content-type".');
      response.headers['content-type'] = response.headers['\ncontent-type'];
    }
    return response;
  }
}
```

It is possible that our nginx server adds an incorrect header, when IE11 tries to retrieve a file.
However I've intercepted the request using netcat and replayed it:

`ncat -l -p 12345 | tee outgoing.log`

using the content of outgoing log I've retrieved the file and don't see anything special:
```
ncat --ssl api.holibri.com 443
GET /holibri/v1/countries/list?alt=json HTTP/1.1
Accept: */*
Content-Type: application/json; charset=utf-8
Referer: https://api.holibri.com/#/home
Accept-Language: en-US
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: api.holibri.com
Pragma: no-cache
Cookie: _ga=GA1.2.1956608909.1503331417; _gid=GA1.2.1901566558.1503331417; _gat=1

HTTP/1.1 200 OK
Server: nginx/1.13.0
Date: Mon, 21 Aug 2017 16:08:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
access-control-allow-credentials: true
cache-control: no-cache, no-store, must-revalidate
access-control-allow-origin: *
pragma: no-cache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
expires: 0
Strict-Transport-Security: max-age=31536000

97
["AT","DE","SI","HU","BE","NL","LU","DK","PL","SK","CZ","BG","FR","GB","IT","HR","RO","RS","FI","SE","EE","IE","LV","NO","PT","ES","GR","MT","TR","CY"]
0
```

If I don't go through the nginx https proxy, but retrieve the data directly from our dart program, this bug does _not_ exist!

**Comment by floitschG** [comment]
Do you have a way to reproduce this issue?

**Comment by close2** [comment]
I have created a minimal demo app, which displays this bug.
The README also describes our setup.

https://github.com/close2/dart_bug_30507

**Comment by sgjesse** [comment]
This sems to be an issue in the browser. I looked at the hex-dump of the headers received from https://api.holibri.com/holibri/v1/countries/list?alt=json (using curl), and they look fine - all header lines are correctly terminated with \r\n.

The Dart [`BrowserClient`](https://github.com/dart-lang/http/blob/master/lib/browser_client.dart) uses the Dart binding of `XMLHttpRequest` in the browser, and in particular for the headers the api [`getAllResponseHeaders`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders). The string from that API is then processed in [Dart code](https://api.dartlang.org/stable/1.24.2/dart-html/HttpRequest/responseHeaders.html) to provide the headers in the `Response` object.

It would be interesting to see the exact content of `getAllResponseHeaders` in this situation, both from a Dart and JavaScript application, as the source of the error most likely lies there.

It is still odd that this only happens with the nginx server as proxy. One thing to note here is that the all-lowercase headers are passed "as-is" from the Dart server, whereas the others are "rewritten" by nginx. Not that I can see why that should make a difference.

**Comment by d3v-cl** [comment]
Hello
I can confirm, that this is not a dart bug.
A simple javascript version with `getAllResponseHeaders` fails as well.

FYI:
I've added the javascript version as index2.html to my dart_bug_30507 git repository.
![screenshot_20170825_153841](https://user-images.githubusercontent.com/365042/29716436-b530c0a4-89ab-11e7-8b99-3530b1d436b2.png)

**Comment by floitschG** [comment]
Closing.
