### ISSUE TITLE
Missing quickfix "update import" when `hide` is used in `import`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30503]
![image](https://user-images.githubusercontent.com/405837/29495683-60ec1c72-85c4-11e7-9624-53835f236fa0.png)

when I comment out `hide` user

![image](https://user-images.githubusercontent.com/405837/29495699-9a99447c-85c4-11e7-81db-0ca5460adac9.png)

I get the "update import" option, but I think I should also get it when `hide User` is there.

**Comment by bwilkerson** [comment]
Agreed. We need to update FixProcessor._addFix_importLibrary_withElement to understand `hide` clauses.

**Comment by asashour** [comment]
Another question, what happens when the user tries to expose the 'hidden' function, e.g.

```dart
import 'dart:math' hide max show min;

void f() {
  max(1, 2);
}
```

Should we say: `Update library import`, or `Unhide 'max'`?

<hr>

The requester test case:

```dart
import 'dart:math' hide atan show min;

void f() {
  max(1, 2);
}
```

should have 'Update library import' to add `max`, instead of 'Import library'

**Comment by bwilkerson** [comment]
The labels for a fix (or assist) should describe what it's going to do. We could say "Update import of '<uri>'", or we could be more specific about how it's going to be updated and say something like "Show '<name>' from '<uri>' or "Unhide '<name>' from '<uri>'" depending on how the import will be updated.

For something like
```
import 'dart:math' hide max show min;

void f() {
  max(1, 2);
}
```
We actually need to do both: remove the hide clause and add `max` to the show clause. (I suspect that having both a hide and show clause is rare though, so I'm not sure it's worth having a third message for it.)

**Comment by FMorschel** [comment]
> We actually need to do both: remove the hide clause and add max to the show clause. (I suspect that having both a hide and show clause is rare though, so I'm not sure it's worth having a third message for it.)

In this case the "update" would be fine I think.

Just to point out: some work related to `show` is being worked on https://github.com/Dart-Code/Dart-Code/issues/5238.

**Comment by FMorschel** [comment]
I just would like to point out that there is an issue for warning when you have either two combinations of `show`/`hide` since you only need one to achieve any hiding goal

> You never need more than one `show` or one `hide` combinator to achieve any hiding-goal.

From [@lrhn's comment on #56879](https://github.com/dart-lang/sdk/issues/56879#issuecomment-2405873036)

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/390630
