### ISSUE TITLE
Verify that Windows10 GCE bots on swarming can run Dart2js-chrome and dart2js-ie recipes

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30505]
We have not yet run any browser testing on Windows10.  Please test, using led, that the dart2js browser tests work with the chrome and ie runtime options, on the Windows bots in the Dart.LUCI pool.

**Comment by athomas** [comment]
dart2js-ie seems to work fine once IE is configured (close the first run wizard with "Don't use recommended settings" and allowing popups).

**Comment by athomas** [comment]
dart2js-chrome has been running for a while. IE is still work in progress.
