### ISSUE TITLE
Scanning input "0e" results in token "0e0" followed by token "NaN"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#30508]
This is failing one of my tests:

https://travis-ci.org/dart-lang/angular_analyzer_plugin/jobs/266892772#L1269

Repro (IgnoringAnalysisErrorListener is a class in my project, though)

```
import 'package:analyzer/src/dart/scanner/reader.dart';                          
import 'package:analyzer/src/dart/scanner/scanner.dart';                       
import 'package:angular_analyzer_plugin/src/ignoring_error_listener.dart';

void main() {                                                                    
  final reader = new CharSequenceReader('0e');                                   
  final scanner =                                                                
      new Scanner(null, reader, new IgnoringAnalysisErrorListener());            
  final res = scanner.tokenize();                                                
  print(res);                                                                    
  print(res.next);                                                               
  print(res.next.next.type);                                                     
}               
```

prints

```
0e0
NaN
EOF
```

@danrubel

**Comment by bwilkerson** [comment]
My guess is that `new IgnoringAnalysisErrorListener()` is the same as `AnalysisErrorListener NULL_LISTENER`.

@MichaelRFairhurst Are you using the bleeding edge version of analyzer and front_end, or are you using the latest published versions?

**Comment by MichaelRFairhurst** [comment]
This is bleeding edge.

And ooh, I'll see if I can drop that class from our project in favor of the
official one!

**Comment by MichaelRFairhurst** [comment]
Ping @danrubel. Just as a clarification, this issue still exists and is unrelated to `NULL_LISTENER`.

**Comment by danrubel** [comment]
Will dig into this tomorrow.
