### ISSUE TITLE
DDC runtime should move `getExtensionType` off of the fast(er) path

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30510]
I see `getExtensionType` showing up on profiles sometimes.  Several of our runtime helpers call this on the default path (e.g. `dart.toString` and `dart.hashCode`).  My understanding is that most of the time this property will not be present, and so this is likely a slow check.  We may wish to refactor this either to check for a property that is always present except in extensions, or else to only check if all other possibilities have failed.

**Comment by jmesserly** [comment]
I have a CL that makes some progress on this. Note: the quick fix is to inline it.

**Comment by jmesserly** [comment]
Should be fixed now. We never check it as part of Object member dispatch now, it's only used in dispatching dynamic operations.
