### ISSUE TITLE
VM: Support generalized void

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30516]
This is the VM specific issue for issue #30176, which contains the details.

This issue was created in order to have a suitable issue number to refer to in status files.

The implementation of support for generalized void in the VM should be coordinated with that of other tools, and in particular most or all of it may be provided by the common front end. Hence, please do not start implementing this in the VM at this point.

**Comment by a-siva** [comment]
A sample code in flutter that could use this feature to avoid strong mode errors
```
typedef void GestureTapCancelCallback();
GestureTapCancelCallback onTapCancel;
T invokeCallback<T>(String name, RecognizerCallback<T> callback, { String debugReport() }) {
}
main() {
  invokeCallback<void>('spontaneous onTapCancel', onTapCancel);
}

```

**Comment by crelier** [comment]
The VM parser has been [fixed](https://github.com/dart-lang/sdk/commit/0f08aababa506a10482488adcb56286f729f9386) to support the sample above involving void as the type argument of a generic function, as in  `invokeCallback<void>(...)`.
However, 'void' as type annotation is not yet supported, so this issue remains open for now.

**Comment by a-siva** [comment]
How about the following cases
- void allowed as a parameter type e.g - f(void a) {}
- void as a variable type e.g - void v = null;
I suppose these are allowed per the informal spec.

But when I run the VM parser on these examples I get an error.

**Comment by crelier** [comment]
These cases have not been fixed yet, the reason I left the bug opened. Are we supposed to support this now? My understanding was that only void as type argument was supported at this time. I can start working on it if full support is needed now.

**Comment by a-siva** [comment]
I don't know yet if these cases are critical will let you know if I run into these patterns in flutter.

**Comment by lrhn** [comment]
The sooner we support the full new syntax, the sooner we can start migrating the libraries to use it.
