### ISSUE TITLE
dart2js: Support generalized void

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30515]
This is the dart2js specific issue for issue #30176, which contains the details.

This issue was created in order to have a suitable issue number to refer to in status files.

The implementation of support for generalized void in dart2js should be coordinated with that of other tools, and in particular most or all of it may be provided by the common front end. Hence, please do not start implementing this in dart2js at this point.

**Comment by kmillikin** [comment]
This should be supported in dart2js now as of https://github.com/dart-lang/sdk/commit/9bdf2489b54841567005eaff7033f3451a047b37 which enabled support in the CFE.
