### ISSUE TITLE
DDC allows mutating constant map

### ISSUE THREAD

**Issue by mkj-gram** [dart-lang/sdk#30526]
The test compile_time_constant_a_test fails to throw an UnsupportedError when mutating a constant heap.
 To reproduce:

python tools/test.py -m release -c dartdevc -r chrome --strong --use-sdk language_2/compile_time_constant_a_test

**Comment by jmesserly** [comment]
thanks for reporting this! I'm going to merge it into https://github.com/dart-lang/sdk/issues/29897
