### ISSUE TITLE
main.cc and gen_snapshot.cc have a lot of duplicated code related to option processing

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30534]
Move all this code into a shared file.

**Comment by mkustermann** [comment]
Wasn't the plan at some point to get rid of `gen_snapshot` entirely?

**Comment by zanderso** [comment]
Oops. I started working on this here before seeing this issue: https://dart-review.googlesource.com/#/c/sdk/+/4608/

**Comment by mraleph** [comment]
@zanderso thanks for doing this, Zach! I did not get to it yet anyway. I will take a look.
