### ISSUE TITLE
Unable to submit some issues

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30537]
The "Open issue submission form?" link in IntelliJ is broken in the latest version, at least for some issues. It opens to the issue tracker, but the content is truncated in a way that makes it virtually useless for tracking down the issue.

I have seen this in my own configuration, and there are reports that users are also seeing it (https://github.com/dart-lang/sdk/issues/30333#issuecomment-324670957).

**Comment by devoncarew** [comment]
@stevemessick

**Comment by zoechi** [comment]
I reported it also in https://youtrack.jetbrains.com/issue/WEB-28443

**Comment by alexander-doroshko** [comment]
@devoncarew has fixed [WEB-28443](https://youtrack.jetbrains.com/issue/WEB-28443) and [WEB-35878](https://youtrack.jetbrains.com/issue/WEB-35878) so I think this issue can be closed here. I don't have permissions to close.
