### ISSUE TITLE
Improper behavior of ClassHieararchy.getInterfaceMember when multiple members inherited

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30547]
The documentation for `ClassHierarchy.getInterfaceMember` says, in part:

> Returns the possibly abstract interface member of [class_] with the given [name].
> ...
> If multiple members with that name are inherited and not overridden, the member from the first declared supertype is returned.

This doesn't match the spec.  The spec says:

> If multiple superinterfaces of an interface define a member with the same name *m*, then at most one member is inherited. That member (if it exists) is the one whose type is a subtype of all the others. If there is no such member, then:
> * A static warning is given.
> * ...

(The second bullet is irrelevant because in Dart 2.0 the static warning becomes an error)

This causes trouble with a source file like this one:

```dart
abstract class I1 {
  void f(int i);
}
abstract class I2 {
  void f(Object o);
}
abstract class C implements I1, I2 {}
class D extends C {
  void f(Object o) {}
}
void g(C c) {
  c.f('hi');
}
main() {
  g(new D());
}
```

To resolve `g`'s call to `c.f`, the front end calls `ClassHierarchy.getInterfaceMember`, which returns `I1.f`.  This is a problem because in Dart 2.0, it's not legal to pass the string `'hi'` to `I1.f`.  (Note: the front end doesn't yet generate the proper error message for this).  But according to the spec, the call resolves to `I2.f`, since `I2.f`'s type is a subtype of `I1.f`'s type.  So there should be no error, since it is legal to pass `'hi'` to `I2.f`.

**Comment by stereotype441** [comment]
I can think of three ways to fix this:
* Change the implementation (and documentation) of `ClassHierarchy.getInterfaceMember` to match the spec.  This will require access to the `TypeEnvironment` in order to do the necessary subtype tests.  We'll need to be careful about caching, since the front end uses ClassHierarchy as part of type inference, and the results of type inference will affect which interface member gets inherited.  We'll also need to take care to make sure the error condition is recovered well.
* Keep `ClassHierarchy.getInterfaceMember` as is, and have the front end insert synthetic abstract methods as necessary to ensure the right behavior.  (In the example above, the front end would insert a synthetic `void f(Object o);` into class `C`).
* Replace `ClassHierarchy.getInterfaceMember` with `ClassHierarchy.getInterfaceMembers` and require the caller to deal with the situation where there are multiple matching members.  (We probably should put the necessary logic in a common place, e.g. `TypeEnvironment.computeInheritedMember`, so that the logic doesn't get replicated at each call site).

@scheglov and @kmillikin, what do you think?  I'm leaning toward the second option, because it seems similar to the "forwarding stubs" that we know we're going to have to add anyway (to deal with covariant generic parameters).

**Comment by scheglov** [comment]
Will front-end insert synthetic abstract methods always, or only as needed? Isn't it equivalent to implementing `ClassHierarchy.getInterfaceMembers` in front-end? OK, you did this.

The second option SGTM. We might also make `ClassHierarchy.getInterfaceMember` throw `StateError` if there is more when one member.

**Comment by leafpetersen** [comment]
There is definitely some funkiness left around override checking in the analyzer/strong mode, so it's good to push on these questions.  Currently override checking is split between the strong mode checker (which does extra checks) and the regular analyzer override checker which does some baseline checking, and it's very possible we are missing things.

For this specific case, it seems to me that the spec is right, and the implementations are wrong.  At `C`, we can soundly choose the type which is a subtype of all others (I2.f), and only need to ensure that the concrete implementation (if any, whether inherited or provided) is a subtype of that.  So this error seems unnecessary to me, and also doesn't seem to me to match the spec. 

cc @jmesserly @sigmundch who did a lot of the strong mode override checking thinking.

**Comment by jmesserly** [comment]
If you're implementing strong mode checking, I would suggest looking at CodeChecker and _OverrideChecker in pkg/analyzer/lib/src/task/strong/checker.dart

It's < 2k lines and is our complete strong mode checking for overrides, covariance, implicit casts, and dynamic call sites.

**Comment by jmesserly** [comment]
but yes agree with y'all, the call to `C.f` is legal.

A perhaps more interesting case?
```dart
abstract class I1 {
  void f(int i);
}
abstract class I2 {
  void f(String o);
}
abstract class C implements I1, I2 {}
class D extends C {
  void f(Object o) {}
}
void g(C c) {
  c.f('hi');
}
main() {
  g(new D());
}
```
currently this is an error on `c.f`

**Comment by stereotype441** [comment]
@jmesserly yeah, that example is a good test case as well.  My understanding of Dart 2.0 is that your example should have a compile error at the site of the declaration of `C` saying that inconsistent declarations of `f` are inherited.  Whether or not there is a further error in `g` is kind of open to interpretation, since it depends how the first error is recovered from.  The spec text in the second bullet point (which I dropped from my quote at the top of this bug) says that `C` inherits a member `f` taking a single argument with type dynamic, and does not specify its return type (!).  So going by that, there would be no error at the site of the call `c.f`.  But I suspect we're probably going to drop that text from the spec when we go full Dart 2.0, since at that point it's really just an error recovery question.

**Comment by leafpetersen** [comment]
On the more interesting case: we could compute a GLB and make the interface of `C.f` be `Object -> void`.  I've been trying to avoid relying more on GLB and LUB though, since they are unpredictable, and make for difficult error messages (since they invent new types that aren't in the program anyway).

I would prefer to keep this an error.  The user can put an explicit declaration for `f` in `C` with their own choice of types to use as the merge if they really want to do this.

**Comment by stereotype441** [comment]
@leafpetersen +1

**Comment by stereotype441** [comment]
This was fixed some time ago, but I forgot to update the test cases and close out the bug.  Test cases updated here: https://dart-review.googlesource.com/#/c/sdk/+/16700
