### ISSUE TITLE
String.split does not actually return a List<String> in dart2js/VM

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30548]
https://api.dartlang.org/stable/1.24.2/dart-core/String/split.html

in strong mode this causes a soundness problem. I fixed this bug in DDC in https://github.com/dart-lang/sdk/commit/d0072fa73fcb5421e49ba7e86818b891c70303d8

**Comment by jmesserly** [comment]
Hmmm, string_patch in VM looks correct. However this simple test fails in checked mode, and it prints `List` as the runtimeType
```dart

main() {
  var list = 'a,b,c'.split(',');
  list.add(42); // does not throw
  print('split return type is ${list.runtimeType}'); // prints List
  list = <String>['a', 'b', 'c'];
  print('list type is ${list.runtimeType}'); // prints List<String>
  list.add(42); // throws in checked mode
}
```

**Comment by ErikCorryGoogle** [comment]
This is still an issue for dart2js, but the VM-based solutions get this right.

On the other hand, the API docs make no mention of the returned list being growable, so I removed that from the test.

**Comment by lrhn** [comment]
Dart2js returns the result of the JS `split` function directly, which means that the list behaves as a `List<dynamic>`, not a `List<String>`. It will have to store the `String` type parameter on the result somehow.

**Comment by rakudrama** [comment]
Fixed for dart2js by https://github.com/dart-lang/sdk/commit/8a7c3331dff54e8c9226b7c16080af464eda7d2e
