### ISSUE TITLE
Nullable cascade operator?

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#30541]
There's already a `?.`. Why not a `?..`?

**Comment by zoechi** [comment]
a use case where this would be useful?

**Comment by xster** [comment]
Say you lazily create something or discard/nullify something with one particular lifecycle and update it if it exists on a different set of events

**Comment by zoechi** [comment]
Sorry, I assumed the wrong directory (thought it was Angular) and removed my comment shortly after I posted. 
I think a concrete use case is still helpful ;-)

**Comment by lrhn** [comment]
No particular reason except that it has never been added. It's not significantly different from a normal `?.` operation.
It's worth considering.

**Comment by srawlins** [comment]
This is being added as part of NNBD; see spec here: https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md
