### ISSUE TITLE
Multiple inheritance should resolve to the method whose signature is a subtype of the others

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30552]
This is the analyzer equivalent of front end/kernel bug #30547.  I'm mostly filing the bug so I can link to it from test cases--it may not be worth trying to fix in analyzer, since eventually analyzer is going to be based on the new front end.

The spec says:

> If multiple superinterfaces of an interface define a member with the same name *m*, then at most one member is inherited. That member (if it exists) is the one whose type is a subtype of all the others. If there is no such member, then:
> * A static warning is given.
> * ...

Which means that following code should be ok, because the version of `f` inherited by `C` should be the one from `I2`, which is safe to pass a String to:

```dart
abstract class I1 {
  void f(int i);
}
abstract class I2 {
  void f(Object o);
}
abstract class C implements I1, I2 {}
class D extends C {
  void f(Object o) {}
}
void g(C c) {
  c.f('hi');
}
main() {
  g(new D());
}
```

But in strong mode, analyzer issues this warning at the site of `g`'s call to `c.f`: `The argument type 'String' can't be assigned to the parameter type 'int'`.

**Comment by bwilkerson** [comment]
@scheglov I've verified that this is implemented correctly in `InheritanceManager2`, so I'm guessing that we just need to finish replacing `InheritanceManager`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/78182 will fix this.

**Comment by scheglov** [comment]
This was fixed with using `InheritanceManager3`.
