### ISSUE TITLE
Type.toString for function types is inconsistent between implementations

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30551]
given:
```dart
main() {
  var f = (int x) => 42;
  print(f.runtimeType);
}
```
DDC prints `(int) -> int`
VM prints `(int) => int`
dart2js prints `main_closure`

if we change to a generic:
```dart
main() {
  var f = <T>(T x) => x;
  print(f.runtimeType);
}
```
DDC prints `<T>(T) -> T`
VM prints `(dynamic) => dynamic`
dart2js prints `main_closure`

dartanalyzer uses yet another scheme. It's similar to DDC, but handles nested generic function types that reuse the same name (adding a subscript for clarity if necessary), and it uses the unicode arrow symbol.

It would be nice to have these consistent, as it's useful in function type tests.

**Comment by floitschG** [comment]
It would definitely be nice, if they printed the same thing, but how would those be useful in function type tests? As soon as you use minification the `toString`s of runtime types can't be trusted anymore.

**Comment by jmesserly** [comment]
DDC now matches the VM. Eventually it might be nice to match Dart2's function syntax but not a high priority imo. Closing as not planned.
