### ISSUE TITLE
Add import quick fix positioning issue

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30577]
![image](https://user-images.githubusercontent.com/405837/29866614-3766b56c-8d79-11e7-87c4-82daa2b414dc.png)

results in

![image](https://user-images.githubusercontent.com/405837/29866647-4b62459a-8d79-11e7-9f36-01d17a53fe99.png)

Dart VM version: 1.25.0-dev.8.0 (Mon Jul 24 14:17:21 2017) on "macos_x64"

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/54307
