### ISSUE TITLE
Analyzer crashing several times a minute

### ISSUE THREAD

**Issue by michschn** [dart-lang/sdk#30581]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.9.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-92-generic unknown, screens 3840x2160, 1200x1920`

# Exception

Please append the contents of:
contact michschn@google.com
file:///tmp/report372.txt

```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, error: Analysis failed: 
RangeError (byteOffset): Invalid value: Not in range 0..1664, inclusive: 15728686
#0      _ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:2860)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      StringReader.read (package:front_end/src/base/flat_buffers.dart:663)
#3      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:826)
#4      Object

**Comment by sigmundch** [comment]
@stereotype441 @scheglov - this appears like the flat-buffer readier is failing to load a summary file? Could this be an issue in the summary file or some kind of version mismatch? (I know FB has backward compatibility, so I'm not sure if the latter is possible)

**Comment by scheglov** [comment]
I think I might have made an [incompatible change](https://github.com/dart-lang/sdk/commit/a092694280299cea34f1db204cf9a258baad9c76). Although I hoped that it will work, because I also incremented the version data version number in `AnalysisDriver`.

As an experiment try to remove the `~/.dartServer` folder and see if this fixes the problem.

**Comment by bwilkerson** [comment]
I'm guessing that this is no longer an issue, so I'm closing it. Please re-open if that isn't true.
