### ISSUE TITLE
When built from kernel Const constructors don't build up type argument information

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30588]
With https://github.com/flutter/flutter/commit/541afae45b10a764e46d176ea249c4dc122eb557 Flutter gallery example works fine without kernel, but fails on assert with kernel on seemingly missing type information
```
[ +236 ms] I/flutter (30542): localizations dynamic, ()
[        ] I/flutter (30542): localizations dynamic, (dynamic)
[  +30 ms] I/flutter (30542): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY 
...
[        ] I/flutter (30542): When the exception was thrown, this was the stack:
[  +84 ms] I/flutter (30542): #0      _AssertionError._doThrowNew (dart:core)
[        ] I/flutter (30542): #1      _AssertionError._throwNew (dart:core:2848:5)
[        ] I/flutter (30542): #2      _loadAll (package:flutter/src/widgets/localizations.dart)
[        ] I/flutter (30542): #3      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:363:62)
[        ] I/flutter (30542): #4      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:328:5)
```
That is with 
```
 print('localizations $type, ${output.keys}');
```
added to `_loadAll` before `  assert(!output.containsKey(type));` .

It shows that without kernel before and after [change](https://github.com/flutter/flutter/commit/541afae45b10a764e46d176ea249c4dc122eb557) types are as expected
```
[  +92 ms] I/flutter (30059): localizations WidgetsLocalizations, ()
[        ] I/flutter (30059): localizations MaterialLocalizations, (WidgetsLocalizations)
```
but with kernel after the change types are all resolved to `dynamic`
```
[ +253 ms] I/flutter (29612): localizations dynamic, ()
[   +2 ms] I/flutter (29612): localizations dynamic, (dynamic)
```

@kmillikin  @sigmundch

**Comment by aam** [comment]
It seems like [newly introduced code](https://github.com/flutter/flutter/commit/541afae45b10a764e46d176ea249c4dc122eb557#diff-736ca556147289e26be278775c3ef344R105) relies on template argument type `T` being available at runtime.
Without kernel it is available, but with kernel it's only available as `dynamic`.
I don't think this is as expected, but not sure.

@peter-ahe-google @a-siva

**Comment by matanlurey** [comment]
Class types are reified at runtime in Dart 1.x (not requiring Kernel), that is:

```dart
class FooData extends LocalizationsDelegate<Foo> { ... }
```

`FooData.type` will return `Foo` in Dart 1.x.

**Comment by sigmundch** [comment]
Seems like there is an issue with type-variables and constants.

Here is a small repro of the problem:

```dart
class A<T> {
  const A();
  Type get type => T;
}

class B extends A<String>{
  const B();
}

main() {
  print(const B().type);
}
```

If you run it in the VM without the FE, this prints "String", with the FE, this prints "dynamic".

**Comment by sigmundch** [comment]
Note that doing `new B().type` instead of `const B().type` does print "String".

**Comment by peter-ahe-google** [comment]
@mkustermann @jensjoha could you take a look at this? I think this may be a problem on the VM side.

**Comment by aam** [comment]
indeed, @peter-ahe-google , the issue seems to be with kernel flow graph builder where https://github.com/dart-lang/sdk/blob/b460a25459fa261fac1c4c548bcf43c4e23a897f/runtime/vm/kernel_binary_flowgraph.cc#L5678 seems to exit const constructor invocation too soon.

**Comment by peter-ahe-google** [comment]
You are in luck then, @jensjoha is much faster at fixing bugs than I am ;-)

**Comment by aam** [comment]
Thanks all for troubleshooting this!

**Comment by jensjoha** [comment]
https://codereview.chromium.org/3007123002/.

**Comment by aam** [comment]
Thanks, @jensjoha , it is indeed fixed!
