### ISSUE TITLE
Cpu profiler in observatory hits an assert fault.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30584]
As part of building the dart sdk, the following command is issued (the actual command does not include the --observe flag and uses the release build of dart):

`/usr/local/google/home/regis/dart1/sdk/out/DebugX64/dart --observe --packages=/usr/local/google/home/regis/dart1/sdk/.packages --snapshot=/usr/local/google/home/regis/dart1/sdk/out/ReleaseX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit /usr/local/google/home/regis/dart1/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk /usr/local/google/home/regis/dart1/sdk/sdk --dart-sdk-summary /usr/local/google/home/regis/dart1/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /usr/local/google/home/regis/dart1/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /usr/local/google/home/regis/dart1/sdk/pkg/dev_compiler/bin/dartdevc.dart
`

While the command is running, clicking on cpu profile in the observatory results in this assert fault:
```
Observatory listening on http://127.0.0.1:8181/
../../runtime/vm/object.cc: 14407: error: expected: !IsFunctionCode()
Dumping native stack trace for thread 11461
  [0x0000000000c5e817] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000c5e817] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000d8a136] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x0000000000b4f757] dart::Code::GetInlinedFunctionsAtInstruction(long, dart::GrowableArray<dart::Function const*>*, dart::GrowableArray<dart::TokenPosition>*) const
  [0x0000000000c5c66f] Unknown symbol
  [0x0000000000c5b450] Unknown symbol
...
```

Note that the crash does not happen if you wait until the command is "paused on exit" before clicking on cpu profile.

**Comment by B3rn475** [comment]
I'm able to reproduce the crash even after `PauseExit`.

The problem is related to loading a `Release` snapshot from a `Debug` VM.
That shouldn't be done.

@a-siva as @crelier suggested we should probably inform the user if it is possible.
