### ISSUE TITLE
IntelliJ plugin: Support generalized void

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30598]
This is the IntelliJ plugin specific issue for #30176, which has the details.

**Comment by alexander-doroshko** [comment]
done for the upcoming 2017.3 release

**Comment by devoncarew** [comment]
🎉

**Comment by jwren** [comment]
@eernstg To test the support download the 2017.3 EAP here (https://confluence.jetbrains.com/display/IDEADEV/IDEA+2017.3+EAP), when it is available.
