### ISSUE TITLE
[crash] Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30595]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3757.52`
- `1.24.2`
- `IC-172.3757.52, JRE 1.8.0_152-release-915-b10x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception
[report2.txt](https://github.com/dart-lang/sdk/files/1269083/report2.txt)

File that cause the crash
```dart
import "dart:async";

typedef F1 = Stream<T> Function<T>(Iterable<T> values);
typedef F2 = Stream<T> Function<T>(Iterable<T> values, {bool Function(T element) isError});
typedef F3 = Stream<T> Function<T>(Iterable<T> values, {bool isError(T element)});
typedef Stream<T> F4<T>(Iterable<T> values);
typedef Stream<T> F5<T>(Iterable<T> values, {bool isError(T element)});

void test1(F1 f) {}
void test2(F2 f) {}
void test3(F3 f) {}
void test4(F4 f) {}
void test5(F5 f) {}

int main() {
  test1(null);
}
```

**Comment by jmesserly** [comment]
This is working now. I believe it was fixed when I landed support for resolving the new syntax.
