### ISSUE TITLE
Some html extension member names are not getting defined

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30591]
I believe that this CL:  https://github.com/dart-lang/sdk/commit/4466c461f0ab748137cd9f873626318fc733f221

changed the way that we generate extension member symbols from doing them on demand in defineExtensionMembers to defining them eagerly up front.  The html class CssStyleDeclarationBase induces a call to defineExtensionMembers with `transitionDuration` as one of the arguments.  Previously, this would have result in a symbol being defined on dartx for that extension member.  I don't see a new symbol showing up in the CL above corresponding to that though, and I'm seeing internal test failures where `let $transitionDuration = dartx.transitionDuration` results in `$transitionDuration` being `undefined`.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3011763002/
