### ISSUE TITLE
Language specification: Support generalized void

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30597]
This is the language specification specific issue for #30176, which has the details.

Edit, Mar 19, 2018: At this point the feature specifications have been landed, so the language design decisions are in place; the missing part is updating dartLangSpec.tex accordingly.

**Comment by eernstg** [comment]
A feature spec about generalized void has been landed and is available [here](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md). The language specification has not yet been extended to include anything on the topic.

**Comment by eernstg** [comment]
Added milestone for reaching the level where the updated feature spec has been landed (resolving CLs 35680, 35920, 38060, 35740).

**Comment by eernstg** [comment]
For the generalized void feature, we currently have the following open CLs:

- [Make nonvoid-to-void return an error](https://dart-review.googlesource.com/c/sdk/+/35680).
- [Make for-in on a void iterator an error](https://dart-review.googlesource.com/c/sdk/+/35920).
- [Allow void expressions as `?:` branches](https://dart-review.googlesource.com/c/sdk/+/35740).
- [Allow void-to-void data flow](https://dart-review.googlesource.com/c/sdk/+/38060).

**Comment by eernstg** [comment]
For the record, some discussions on the topic of the CLs mentioned in the previous comment took place in this issue: #30177 (on generalized void in the analyzer).

**Comment by dgrove** [comment]
Is there an update on status of this?

**Comment by eernstg** [comment]
Done, finally. ;)

**Comment by eernstg** [comment]
Actually, what's done is the actual language design (the conceptual foundation, the formal rules), but it's all in feature specs, dartLangSpec.tex has not been updated yet. So I'm reopening this, having edited the initial comment on this issue to indicate what's missing.

**Comment by eernstg** [comment]
Done in 5b3b1996a83c36d063c0de1db9f1303f83a087bc.
