### ISSUE TITLE
While editing analysis_options.yaml

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30608]
Analyzer%20Feedback%20from%20IntelliJ# Version information- `IDEA IU-172.3968.16`- `1.25.0-dev.15.0`- `IU-172.3968.16, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1920x1200, 3360x1890  Retina`# ExceptionPlease append the contents of:file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report2.txt```Dart analysis server, SDK version 1.25.0-dev.15.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/zoechi/dart/bwu_product/bwu_product_server], excluded: [/Users/zoechi/dart/bwu_product/bwu_product_server/.idea, /Users/zoechi/dart/bwu_product/bwu_product_server/.pub, /Users/zoechi/dart/bwu_product/bwu_product_server/build]}, clientRequestTime: 1504373584874}NoSuchMethodError: The getter 'contextRoot' was called on null.Receiver: nullTried calling: contextRoot#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)#2      ContextManagerImpl._checkForAnalysisOptionsUpdate (package:analysis_server/src/context_manager.dart:906)#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1411)#4      _rootRunUnary (dart:async/zone.dart:1128)#5      _CustomZone.runUnary (dart:async/zone.dart:1012)#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)#12     _rootRunUnary

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/6262
