### ISSUE TITLE
DDC needs to check generic types when the bound depends on a generic argument

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30601]
Take the following program
``` dart
class A<T> {
  A<E> foo<E extends T>() => new A<E>();
}


class C {}

main() {
  var a1 = new A<C>();
  A<Object> a2 = a1;
  var bug = a2.foo();
  print(bug.runtimeType);
}
```

When the `foo` method is called, it needs to dynamically check that the provide generic argument `E` is a subtype of `T`. This program should thus throw at runtime. Currently it prints `A<Object>`.

/cc @jmesserly

**Comment by jmesserly** [comment]
this should be marked by Analyzer as a covariance check. I'll see if I can figure out what is going on here. Might be a problem with the covariance annotations or with the generated checks.

**Comment by leafpetersen** [comment]
Note that a check is only required when the bound mentions a covariant parameter covariantly (or the method overrides another method which does so.  Examples:

```dart
class A<T> {
  // Check required
  A<E> foo<E extends T>() => new A<E>();
  // No check required
  A<E> bar<E extends void Function(T)> => new A<E>();
}

class B extends A<num> {
  // Check needed
  A<E> foo<E extends num>() => new A<E>();
  // No check needed
  A<E> bar<E extends void Function(num)> => new A<E>();
}

A<E> Function<E extends T>() foo<T>() {
  // No check needed, since T is a sound generic parameter.
   A<E> inner<E extends T>() => new A<E>();
   return inner;
}
```

**Comment by jmesserly** [comment]
Sigh, it's the TypeParameterMember vs TypeParameterElement equality bug that gets me every time :( ... we look to see if `E extends T` has a cast, but we find `{T/T}E extends T` ... which is the same semantically, but not `==` in the Analyzer Element model.

CC @leafpetersen  ... I wish we could clean this up in Analyzer somehow. The way the lazy substitutions are implemented is quite a bug farm, especially with generic functions/methods. I suppose it becomes moot once we migrate to Kernel, at least.
