### ISSUE TITLE
"Hot reload was rejected:  error: wrong number of type arguments for class 'State'"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30606]
The dill file produced by the incremental kernel generator fails a hot reload with the wrong number of type arguments error for class 'State'

Still investigating the root cause of this failure (IKG bug or kernel reader failure).

**Comment by a-siva** [comment]
aam@ have created this issue to track the failure you have been seeing when trying to reload using the incremental kernel generator.

**Comment by sigmundch** [comment]
Just curious - any updates on what the issue was, has this been addressed?

**Comment by aam** [comment]
This seems to be an obsolete now, but I don't have a record of how it got eventually solved(back in August).
