### ISSUE TITLE
Dart is getting hung while using high CPU

### ISSUE THREAD

**Issue by bitsmaker** [dart-lang/sdk#30607]
I am building a web app using dart that has in its 'web' directory two sub-directories called 'data' and 'img' along with the other default directories. The 'img' directory has about 82000 png files using 1.1 GB. The 'data' directory has about 500 json files using 26M. The application is such that the user does not have to view all the data from all the files at once. Only small chunks will be sent.

When I issue a 'pub serve' command it utilizes 100% CPU and gets hung. I let it run for several hours and it never came back. Using the 'top' command I could see that 'dart' was using the maximum CPU. I removed those two directories from the web directory and pub worked and did not hang.

Is there anything I can do to prevent the hanging issue from happening?

Thanks for all your help!

P.S This happens on the latest of both stable and dev builds as well as DDC

**Comment by floitschG** [comment]
This issue was moved to dart-lang/pub#1696
