### ISSUE TITLE
Cannot resolve 'Uint32Array'

### ISSUE THREAD

**Issue by orklann** [dart-lang/sdk#30611]
Compile the following code to Javascript via dart2js

```dart
import 'dart:html';

main() {
  var array = new Uint32Array(12);
}
```

and get `Cannot resolve 'Uint32Array'.` warning.

```
est.dart:4:19:
Warning: Cannot resolve 'Uint32Array'.
  var array = new Uint32Array(12);
                  ^^^^^^^^^^^
Compiled 3,679,323 characters Dart to 37,443 characters JavaScript in 2.13 seconds
Dart file (test.dart) compiled to JavaScript: test.js
```

dart version: `Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"`

**Comment by ds84182** [comment]
You're looking for [Uint32List](https://api.dartlang.org/stable/1.24.2/dart-typed_data/Uint32List-class.html).

[More details about dart:typed_data here.](https://api.dartlang.org/stable/1.24.2/dart-typed_data/dart-typed_data-library.html)

**Comment by orklann** [comment]
@ds84182 Uint32List looks fine, but I am wondering why my code did not work, Uint32Array is defined in `dart:html` package.

**Comment by lrhn** [comment]
I don't see `Uint32Array` defined in [dart:html](https://api.dartlang.org/stable/1.24.2/dart-html/dart-html-library.html). Can you say where you saw it?

**Comment by orklann** [comment]
@lrhn It's here. http://commondatastorage.googleapis.com/dartlang-api-docs/10275/dart_html/Uint32Array.html

**Comment by lrhn** [comment]
Ah, I was ... not aware of that API doc. I guess nobody else were either—it hasn't been updated since 2012. I recommend only relying on api.dartlang.org for up-to-date documentation.

**Comment by orklann** [comment]
@lrhn  OK, thanks for help, I will use `Uint32List` instead.
