### ISSUE TITLE
Analyzer not showing casting error

### ISSUE THREAD

**Issue by marcinsydor** [dart-lang/sdk#30617]
The code:
```
void main() {
  var a = 5.5;
  var b = 4.3;
  num c = a + b;
  var d = 0;
  d = c;
  print('d: $d');
}
```
The bellow error is only detected in DDC.

`"CastError: Casting value of type 'double' to type 'int' which is incompatible in strong mode"`

**Comment by floitschG** [comment]
This is again an implicit downcast, which is allowed in Dart.

**Comment by bwilkerson** [comment]
Do you have strong mode enabled for analysis? (It's implicitly enabled when you use DDC, but not when you use the analyzer.)

**Comment by marcinsydor** [comment]
Yes,
```
web:
  compiler:
    debug: dartdevc
``` 
in analysis_options.yaml file.

**Comment by bwilkerson** [comment]
I've never seen that before, and have no idea what it does. But I do know that it doesn't enable strong mode in the analyzer. To enable strong mode in the analyzer you need to add the following:
```
analyzer:
  strong-mode: true
```

**Comment by marcinsydor** [comment]
That's generated by stagehand package. Bare-Bones Web App... It's debugging and it's enabling ddc. I thought it also enabling strong mode for the analyzer. I'm clear how it works now.

So I've added to 
```
analyzer:
  strong-mode: true
``` 
to analysis_options.yaml file.
But the analyzer still not showing me that error.

**Comment by marcinsydor** [comment]
Sorry, I've been enabling properly strong mode in my last projects. I only used that generated code on one example. And just have not noticed it.  But as written above the analyzer still not showing the error.

**Comment by zoechi** [comment]
disable implicit-casts as shown in https://www.dartlang.org/guides/language/analysis-options

**Comment by marcinsydor** [comment]
@zoechi  I read that doc before and disabled implicit cast but some for reason it did not work for me that time. Now it works which is great. Thanks for that. 
I'm only still not clear why it's not set to false as default in strong mode. I thought to work with DDC we need only set only this `strong-mode: true`. I use someone's else lib where strong mode set to true but I really can't use it with DDC.
@floitschG wrote that implicit downcast is allowed in dart. But does it mean in dart <= 1.24.2? What about 2.0?

**Comment by lrhn** [comment]
Implicit downcasts will also be allowed in Dart 2. 
Disabling them in the analyzer is a lint that you can enable for your own project if you want to, but the language allows it.

**Comment by marcinsydor** [comment]
Ok,
