### ISSUE TITLE
io/secure_server_closing_test times out on CQ on Mac OS

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#30618]
FAILED: none-vm release_x64 standalone/io/secure_server_closing_test
Expected: Pass 
Actual: Timeout

https://luci-logdog.appspot.com/v/?s=dart%2Fled%2Fathom_google.com%2Fa807c9b6e6e940045dc7676a153e11294f2a9dfd32c15e063ffe80a92badc95e%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout

**Comment by zanderso** [comment]
The status file contains the following lines for this issue:
```
[ $builder_tag == swarming && $system == macos ]
io/*: Skip # Issue 30618
```
Please note that this causes *all* `dart:io` tests to be skipped, not just io/secure_server_closing_test.
