### ISSUE TITLE
Async marker on function expression need special return types in fasta

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#30629]
Async marker on function expression need special return types in fasta:

  () sync* {} // return type is Iterable<dynamic>
  () async {} // return type is Future<dynamic>
  () async* {} // return type is Stream<dynamic>

**Comment by peter-ahe-google** [comment]
@stereotype441 have you already implemented this for strong mode?

**Comment by stereotype441** [comment]
@peter-ahe-google Yes, strong mode support for this is fully implemented in front_end.  See the test coverage in `pkg/front_end/testcases/inference/block_bodied_lambdas_*.dart`.

**Comment by peter-ahe-google** [comment]
Can we get this working without strong mode?

**Comment by stereotype441** [comment]
Sure.  Should be addressed by https://dart-review.googlesource.com/4141

**Comment by peter-ahe-google** [comment]
Thank you, Paul!

**Comment by sigmundch** [comment]
I realize that https://github.com/dart-lang/sdk/issues/31414 has not landed yet, but once it does, this bug will be visible again (the type will be handled correctly in strong mode, but not in legacy mode)

**Comment by stereotype441** [comment]
Unassigning myself because I’m not actively working on this issue right now.

**Comment by johnniwinther** [comment]
This is obsolete
