### ISSUE TITLE
Gardening: dart2js-win8-ie11-3-4-be gets 'The debug timer of test.dart expired'

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30625]
dart2js-win8-ie11-3-4-be builds 2697-2717 are all red (except 2707-8: purple), with no failing individual tests, but with 'The debug timer of test.dart expired' (e.g., [log for build 2716](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-win8-ie11-3-4-be%2F2716%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fdart2js-win8-ie11-3-4-be%2F2716%2F%2B%2F%2A%2A%2Fstderr), search for 'debug timer').

The same message was reported in the gardening log on April 12th, but no further actions were taken back then.

**Comment by athomas** [comment]
Restarting the machine wasn't enough. It recovered for a few test steps but started failing again in the same build [2709](https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-win8-ie11-3-4-be/builds/2709).

**Comment by whesse** [comment]
No failures due to this in the past 10 days.  Closing the issue.
