### ISSUE TITLE
DDC closures map to obscure JS names

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30636]
Similar to #30634 

```dart
void foo(int x) {
  var f = (y) => throw 'error in foo';
  f(x);
}

void main() {
  foo(42);
}
```

results in:

```
    at dart.throw (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:5062:27)
    at dart.fn.y (/Users/vsm/ddctest/stacktest2.js:11:34)
    at dart._checkAndCall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:4856:14)
    at dart.dcall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:4861:15)
    at stacktest2.foo (/Users/vsm/ddctest/stacktest2.js:12:8)
    at stacktest2.main (/Users/vsm/ddctest/stacktest2.js:16:14)
```

@jmesserly @jacob314

**Comment by jmesserly** [comment]
How's that trace being printed? And what's the desired behavior here?

We can't do better than JS will let us, and it is an anonymous (unnamed) function.

Does it work differently if source maps are enabled? I'm guessing that's how most folks will run this.

Dart VM says `foo.<anonymous closure>`. That's neat, but I don't think we have access to the enclosing scope name.

When I translate this code to JS, without the `dart.fn` call, Chrome picks up the name `f` from the `var f =`. Which is cool, arguably better than VM. So it seems that our `dart.fn((y) => ...)` is where Chrome infers the `dart.fn.y` from. We could delay the `dart.fn` call for the special case of a variable initialized to a closure, but it's not a general solution.

Ultimately these are all just heuristics, and it's very browser dependent. Firefox for example is able to understand our pattern (even with a wrapper `fn` call) and conclude `f`, whereas Safari does not seem to show the anonymous function stack frame at all. I'd need to investigate more, in all cases browser optimizations may be interfering with the stack. Inventing names for anonymous functions is a best effort sort of thing, and I imagine that no JS VM wants to pay a performance cost for it.

**Comment by jmesserly** [comment]
One idea, `dart.fn` could become `anonymousFn` ... not sure if that would help. We can basically generate `const anonymousFn = dart.fn` at the top of the module and use that for closures.

**Comment by vsmenon** [comment]
That trace is from Node.  Chrome dev tools trace looks about the same though.

The confusing thing (to me) is the heuristic to fallback to parameter names (`dart.fn.y` above).  In this particular case, showing `f` seems most informative.
