### ISSUE TITLE
AOT compiler has few optimization for `is` and `as` checks that are not enabled for JIT

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30632]
We need to evaluate if they should just be ported to JIT environment if they are beneficial.

**Comment by alexmarkov** [comment]
Related issue: https://github.com/dart-lang/sdk/issues/30571

**Comment by mkustermann** [comment]
After 1c7731db6084fbdbb879ba7a602718af24d3bdee we use type testing stubs always - in JIT as well as AOT.
