### ISSUE TITLE
Incorrect implicit downcast error in async functions with FutureOr

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30638]
The following code, when analyzer with `--strong --no-implicit-casts` produces type errors on both function returns:

```dart
import 'dart:async';
typedef FutureOr<String> Stuff();
Stuff stuff = () async => stuff2();
Future<String> stuff3() async => stuff2();
Stuff stuff2;
```

```
[error] The return type 'Future<FutureOr<String>>' isn't a 'Future<String>', as defined by the method ''. (/Users/leafp/tmp/ddctest.dart, line 5, col 27)
[error] The return type 'Future<FutureOr<String>>' isn't a 'Future<String>', as defined by the method 'stuff3'. (/Users/leafp/tmp/ddctest.dart, line 7, col 34)
```

As far as I can tell, there should be no error here: there is no implicit downcast.

Oddly enough, DDC (correctly) does not insert a downcast, so this error must presumably be coming from somewhere other than the checker.

cc @natebosch @jmesserly @stereotype441

**Comment by jmesserly** [comment]
It's `StaticWarningCode.RETURN_OF_INVALID_TYPE` from ErrorVerifier, most likely `_checkForReturnOfInvalidType`. I thought we'd disabled most of `ErrorVerifier` type checking in strong mode (because CodeChecker in checker.dart supersedes it), but I guess we missed some checks. It probably does not understand `FutureOr<T>`

**Comment by leafpetersen** [comment]
Possibly related example from @nex3 

```dart
import 'dart:async';

bool c = true;

Future<void> test() async {
  Future<int> a = new Future.value(3);
  Future<dynamic> b = new Future<dynamic>.value(3);
  if (c) {
    return a;
  } else {
    return b;
  }
}
```

**Comment by leafpetersen** [comment]
Another example reported in #31398 

```dart
import 'dart:async';

Future<int> fn(int interpolation) async {
  return runCallback(() => 1);
}

T runCallback<T>(T callback()) {
  return callback();
}
```
