### ISSUE TITLE
gracefully handle when type parameters don't match type args

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30643]
Fasta compiles this program in correctly:

**a.dart**:
```dart
Map<String> foo; // Note that Map takes 2 type arguments
```

In checked mode (the default when you run `./pkg/front_end/tool/fasta compile --platform out/ReleaseX64/patched_sdk/platform.dill a.dart`), we hit this assertion failure:
```
package:front_end/src/fasta/kernel/kernel_class_builder.dart': Failed assertion: line 83 pos 12: 'arguments == null || cls.typeParameters.length == arguments.length': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      KernelClassBuilder.buildTypesWithBuiltArguments (package:front_end/src/fasta/kernel/kernel_class_builder.dart:83:12)
#3      TypeDeclarationAccessor.buildType (package:front_end/src/fasta/kernel/fasta_accessors.dart:1029:21)
#4      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1718:17)
```

With assertions disabled, we also produce unexpected results. In particular, we:
 * don't report an error message in scenarios like these and
 * we return an interface type with an incomplete number of type-arguments (we include the ones we got, but we don't fill in as dynamic the missing arguments). This may break invariants about the kernel IR: an interface type doesn't always has the same number of type arguments as expected by the underlying class.

I suggest we change this behavior, as follows:
  * remove the assertion: instead report an error message and build a valid type.
  * change recovery to return the rawType or to fill in the rest of the arguments.

For context: this came up when running fasta in checked mode within dart2js and shows up in about 50 language tests containing malformed code (I'm guessing the dartk/vm tests are not covering fasta in checked mode?)

@peter-ahe-google I've assigned myself to work on a fix, but let me know if had a different plan in mind or prefer to work on it directly.

**Comment by peter-ahe-google** [comment]
The assertion should remain. It's not right place to fix the problem or report the error. I would prefer to go over the details in a video call.

**Comment by jensjoha** [comment]
This seems to have been fixed: I get a warning in non-strong-mode and an error in strong mode, and never hit an assert.
Can we close this issue?
