### ISSUE TITLE
Feature request: Separate geometry.dart from the rest of dart:ui?

### ISSUE THREAD

**Issue by emshack** [dart-lang/sdk#30653]
My team is working on a command-line tool in Dart that we would like to use the `geometry.dart` classes Size, Rect and Offset for. Would it be possible down the line to decouple `geometry.dart` from the rest of `dart:ui` so that it could be used in a headless context? We are also using Flutter elsewhere in the project (not in the command-line tool), so writing our own versions of these classes or copying the `geometry.dart` file into our codebase would mean extra code to convert our local versions to those in `dart:ui` used by Flutter.

@mishadynin
@krisgiesing

**Comment by lrhn** [comment]
The `dart:ui` library is part of the Flutter project, not the Dart platform (in particular, `geometry` is https://github.com/flutter/engine/blob/master/lib/ui/geometry.dart).
I recommend requesting this in [the Flutter repository](https://github.com/flutter/engine/blob/master/lib/ui/geometry.dart) instead.

**Comment by emshack** [comment]
Ah, thanks, will do!

**Comment by lrhn** [comment]
Super. Closing the issue here then.
