### ISSUE TITLE
Enum type tests broken in DDC

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30659]
The following regressed recently in DDC.  It's printing true.

```dart
enum Foo {
  f1,
  f2
}

void main() {
  print("hello" is Foo);
}
```

**Comment by vsmenon** [comment]
@jmesserly - any ideas on this one?

**Comment by jmesserly** [comment]
yes ... enums skip most of the class decl logic so they might be missing the `addTypeTests` call.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/4609
