### ISSUE TITLE
dartk --checked test failures

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30667]
Few co19/Language/Expressions/Functions_Expressions tests -cdartk --checked fail with exception of the form:
```
Unhandled exception:
type '(int, [int]) => Future' is not a subtype of type '(int, [int]) => int' of 'ffp1'
#0      main (file:///usr/local/google/home/aam/p/d/dart-sdk1/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_async_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)
```

Language/Expressions/Function_Expressions/static_type_dynamic_asyncs_t03: RuntimeError
Language/Expressions/Function_Expressions/static_type_dynamic_async_t03: RuntimeError
Language/Expressions/Function_Expressions/static_type_form_3_asyncs_t03: RuntimeError
Language/Expressions/Function_Expressions/static_type_form_3_syncs_t03: RuntimeError

The tests expect static warning per below, but get runtime error instead. 
```
 * @assertion The static type of a function literal of the form
 * (T1 a1,...,Tn an, {Tn+1 xn+1: d1,...,Tn+k xn+k: dk}) sync* {s} is
 * (T1,...,Tn, {Tn+1 xn+1,...,Tn+k xn+k}) -> Iterable.
 * In any case where Ti, 1 <= i <= n + k, is not specified, it is considered
 * to have been specified as dynamic.
 * @description Checks that it is a static type warning if a function literal
 * of the form (T1 a1,...,Tn an, {Tn+1 xn+1 = d1,...,Tn+k xn+k = dk}) sync* {s}
 * with two parameters is assigned to a variable of a function type with the
 * same parameters and Future return type.
 * @static-warning
```

What is expected semantic of Dart 1.0 static warning behavior in Dart 2.0 with Frontend? @peter-ahe-google can you please help clarify?

**Comment by peter-ahe-google** [comment]
I think the tests are buggy. They're trying to provoke a static warning which will lead to a runtime error in checked mode. So they also need to catch the exception in checked mode.

**Comment by mraleph** [comment]
Checked mode does not exist anymore.
