### ISSUE TITLE
DDC: language_2/label_test.dart: Helper.test7() fails with runtime error

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/sdk#30675]
Marked as RuntimeError in tests/language_2/language_2_dartdevc.status for now (https://dart-review.googlesource.com/c/sdk/+/4800).

Error thrown is `SyntaxError: Label 'L' has already been declared` when running the test using dartdevc.

**Comment by vsmenon** [comment]
Test:

https://github.com/dart-lang/sdk/blob/master/tests/language_2/label_test.dart

**Comment by Markzipan** [comment]
Closing since this passes on DDC now
