### ISSUE TITLE
pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart use fake file URIs

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30673]
I'm unable to get hot_reload_e2e_test to work after I've implemented patching. The problem is that I can't tell which URIs refer to real files and which don't.

In addition, the first test doesn't report failure although this is printed:

    Error: SDK libraries specification not found: xcodebuild/ReleaseX64/patched_sdk/lib/libraries.json.
    Normally, the specification is a file named 'libraries.json' in the Dart SDK install location.
    dart:async: Error: Not found: dart:async.

After fixing this problem, I get this error:

    runtime/bin/common_patch.dart: Error: File file:///Users/ahe/w/dart-sdk/sdk/runtime/bin/common_patch.dart does not exist.

This file does exist.

**Comment by peter-ahe-google** [comment]
This is how I've attempted to fix the problem:

```
diff --git a/pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart b/pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart
index d862007b78..b64f827209 100644
--- a/pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart
+++ b/pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart
@@ -176,7 +176,7 @@ Future<IncrementalKernelGenerator> createIncrementalCompiler(
     String entry, FileSystem fs) {
   var entryUri = Uri.base.resolve(entry);
   var options = new CompilerOptions()
-    ..sdkRoot = sdkRoot
+    ..sdkRoot = Uri.base.resolve("sdk/")
     ..packagesFileUri = Uri.parse('file:///.packages')
     ..strongMode = false
     ..compileSdk = true // the incremental generator requires the sdk sources
```

**Comment by sigmundch** [comment]
Sent out https://dart-review.googlesource.com/c/sdk/+/5294

It required a fix in hybrid-file-system and kernel driver to allow using custom uris
