### ISSUE TITLE
Broken link in dart:io description

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30686]
The [description](https://api.dartlang.org/stable/1.24.2/dart-io/dart-io-library.html) of dart:io package refers to the WebSocket usage sample:

> Check out the [dartiverse_search](https://github.com/dart-lang/sample-dartiverse-search) sample for a client/server pair that uses WebSockets to communicate.

The referenced repository https://github.com/dart-lang/sample-dartiverse-search does not exist on GitHub and I failed to guess the correct URL for it.

**Comment by srawlins** [comment]
Fixed.
