### ISSUE TITLE
Improve error messages regarding missing .dill files

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30685]
```
$ xcodebuild/ReleaseX64/dart --dfe=xcodebuild/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=missing_directory pkg/front_end/testcases/hello.dart
The platform binary is not a valid Dart Kernel file.$ 
```

The following is missing from this error message:

* A trailing newline.
* A file name.
* An OS error message (from strerror).

```
$ xcodebuild/ReleaseX64/dart --dfe=xcodebuild/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=xcodebuild/ReleaseX64 pkg/front_end/testcases/hello.dart
Could not read dart:vmservice_io binary file.$
```

The following is missing from this error message:

* A trailing newline.
* A file name.
* An OS error message (from strerror).

**Comment by zguo93** [comment]
Update:
--dfe: Invalid input will not trigger error reporting anymore. It will jump back to normal compilation workflow, which compile the .dart file into .dill file first.
--kernel-binaries: This flag has been removed.
