### ISSUE TITLE
"Cascade consecutive method invocations on the same reference" analyzer hint suggests using cascades when not appropriate

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#30682]
Hi everyone,

I _love_ method cascades in Dart, and I _love_ that the dart analyzer (and therefore IntelliJ) can suggest to me appropriate points in my code where I can use cascades. These are great features.

However, I've noticed a situation where the analyzer recommends using a cascade, but doing so actually changes the logic of the program. The analyzer shouldn't be recommending a cascade in this situation.

Here's an example.

```
main() {
  List<int> x;

  x ??= <int>[];
  x.add(1);

  print(x);
}
```

The analyzer recommends changing the code to use a method cascade, like this:

```
main() {
  List<int> x;

  x ??= <int>[]
    ..add(1);

  print(x);
}
```

This has introduced a bug because now the add() method call will only be executed if x is null. This wasn't the case before. In the code snippet above, x will indeed be null at that point, so the code still works. But consider this slightly more complex example, where x might not be null:

```
List<int> x;

main() {
  initialiseAndAdd(1);
  initialiseAndAdd(2);

  print(x); // Expect [1, 2]
}

void initialiseAndAdd(int b) {
  x ??= <int>[];

  x.add(b);
}
```

This works correctly because the add() method will always be called, whether the list variable was null upon entry into the function or not. But analyzer recommends using a cascade here, resulting in:

```
List<int> x;

main() {
  initialiseAndAdd(1);
  initialiseAndAdd(2);

  print(x); // Expect [1, 2], but get just [1]
}

void initialiseAndAdd(int b) {
  x ??= <int>[]
    ..add(b);
}
```

Implementing the analyzer's recommendation has broken the program because now the add() method will only be called if the list variable was null on entry into the function. Following the analyzer's advice here has introduced a bug into the program.

**Comment by matanlurey** [comment]
I don't believe "the analyzer" recommends a cascade, rather a user-authored lint rule does:
https://dart-lang.github.io/linter/lints/cascade_invocations.html

You might want to file here:
https://github.com/dart-lang/linter

**Comment by bwilkerson** [comment]
We'll take linter issues in either place.

cc/ @alexeieleusis

**Comment by alexeieleusis** [comment]
Thank you for the detailed report @ajrcarey.
I just tried to reproduce with `Dart VM version: 1.25.0-dev.9.0` and did not see the behavior you report, can you please confirm what version you are using?

**Comment by alexeieleusis** [comment]
The linter does not trigger  with `Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"`

**Comment by zoechi** [comment]
Is this a dup of dart-lang/linter#86

**Comment by ajrcarey** [comment]
@alexeieleusis: this is 1.25.0 with a custom patch to handle #30006. I'm reluctant to move away from it until 1.25 hits stable and I can verify the stable release correctly includes the fix for #30006. The operating system is arch linux 64 fully patched.

`Dart VM version: 1.25.0-edge.e451f16db0e4fb52352a51360432ad7eea4057ad (Thu Jul  6 04:22:52 2017) on "linux_x64"`

@zoechi: I don't know if it's a duplicate exactly, but it certainly could be related. I'd agree with the comment made there by sgonyea on 8 Mar that null-aware operators need to be handled correctly by the linter.

If this has already been fixed in dev builds, then that's great - in which case my apologies for the unnecessary report.

**Comment by alexeieleusis** [comment]
Actually what I find confusing is that 1.24 does not reproduce the behavior either.

**Comment by bwilkerson** [comment]
That could be due to any number of changes since 1.24. The important question is whether the bug exists on the bleeding edge of the SDK with the DEPS file changed to pull in the bleeding edge of the linter package.

**Comment by alexeieleusis** [comment]
Fair point, I added a test and did not see it fail, will double check. Should I build the SDK and run the linter tests using that? It's been awhile since the last time I built the SDK for the last time, fingers crossed my setup still works.

**Comment by ajrcarey** [comment]
@alexeieleusis That sounds like a lot of trouble for a bug that may already be fixed. Let me quickly download the latest dev of 1.25.0-dev16.4 and see if I still encounter the problem. I'll then switch back to my custom 1.25.0.

**Comment by ajrcarey** [comment]
@alexeieleusis I confirm the problem is no longer present in 1.25.0-dev.16.4. Great! Sorry for the 
unnecessary report.

For interests' sake I went back and looked at 1.24.2 as well and the problem definitely does occur there, at least on my system.

**Comment by bwilkerson** [comment]
@ajrcarey Thanks for confirming that!

**Comment by alexeieleusis** [comment]
yay! thanks

**Comment by AbhiShake1** [comment]
the same is suggested in this code snippet:
messageMap.removeWhere(
        (key, value) => key == 'author' || key == 'id',
      );
      
could anyone tell what i can do as per linter please?

**Comment by bwilkerson** [comment]
Sorry, but I can't reproduce the issue from the snippet. Could you provide a more complete example?

**Comment by AbhiShake1** [comment]
sorry, it was kinda stupid on my  end. i misinterpreted the warning. here is a snippet giving warning;

final messageMap={};
messageMap.removeWhere(
(key, value) => key == 'author' || key == 'id',
);

and this  is what i did later:

final messageMap={}..removeWhere(
(key, value) => key == 'author' || key == 'id',
);
