### ISSUE TITLE
32bit glibc required for building?

### ISSUE THREAD

**Issue by ethanjyx** [dart-lang/sdk#30692]
Hey there, I am trying to build on CentOS.

After I ran gclient sync and trying to build, I got an error:
```
bash: /data/users/jyx/third-party2/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
```
It looks like the dart binary pulled over from source requires a 32-bit glibc after some research online. Although I can definitely do that, is there a way for me to remove this restraint? Thanks

**Comment by rmacnak-google** [comment]
What build step is failing? The build is supposed to fall back to a bootstrap VM if it cannot execute the pre-built one.

@zanderso

**Comment by ethanjyx** [comment]
Basically after gclient sync, I get everything and try to run `./tools/build.py --mode release --arch x64 create_sdk`, then I got that error

**Comment by ethanjyx** [comment]
As an alternative question, how is `/data/users/jyx/third-party2/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart` generated? It is relying on 32-bit glibc, can we point it to 64-bit glibc?

**Comment by ethanjyx** [comment]
If I understand correctly, `/data/users/jyx/third-party2/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart` is the prebuilt library, and it is built upon glibc32, this seems to be causing issues on my machines  which do not support glibc32.

Also yes, a bootstrap VM does not seem to have launched.

I am building on CentOS 64 bit only, there is a strong restriction that I do not use glibc32.

**Comment by ethanjyx** [comment]
Any thoughts? Currently blocked by this. Thanks

**Comment by zanderso** [comment]
Can you give the full error message that you get during the build, including the step that fails?

Can you grab the output of `ldd /data/users/jyx/third-party2/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart` ?

If you wouldn't mind, it would be helpful to put a debug print in build/prebuilt_dart_sdk.gni that gives the value of `prebuilt_dart_exe_works`.

As a quick hack to make progress, can you try downloading a prebuilt 64-bit SDK from https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.2/sdk/dartsdk-linux-x64-release.zip and dropping it in tools/sdks/linux/dart-sdk ?

**Comment by whesse** [comment]
I would second the recommendation to copy a 64-bit dart executable from the 64-bit SDK, and copy it over the dart in tools/sdks/linux/dart-sdk/bin

I believe the check for the SDK executable may just look to see if the file is there, and not if it actually runs.  Or if the build step that used the SDK originally did the check to see if it ran, but there is a new build step depending on it that does not check if it runs, and does not have a backup path.

We should check that by putting a crashing binary in place of dart, and making sure the backup path with bootstrap SDK still works.

**Comment by zanderso** [comment]
@ethanjyx were you able to try any of these things? Thanks!

**Comment by zanderso** [comment]
@whesse The check that sets `prebuilt_dart_exe_works` tries to run the binary. It should be sufficient to try to build from a checkout that doesn't have a pre-built SDK.

**Comment by zanderso** [comment]
I have done the experiment of doing a build after moving the prebuilt SDK out of the way, and the create_sdk build succeeds.

**Comment by ethanjyx** [comment]
Thanks for your responses.

Yes I got it working after pulling in the 64-bit prebuilt SDK.

**Comment by ethanjyx** [comment]
Haven't got time to get debugging print yet for the 32-bit one. But I think what would make sense is to change the build script to check if the environment has 64-bit glibc or 32-bit glibc.
