### ISSUE TITLE
Incorrect description of OSError.message.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#30698]
Please see [OSError.message](https://api.dartlang.org/stable/1.24.2/dart-io/OSError/message.html) documentation:

> String message
> final
> Error message supplied by the operating system. null if no message is associated with the error.

It declared, that null is returned, if no message is associated with the error. 
However, Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:55:05 2017) on "linux_x64" returns "" (empty String).

**Comment by srawlins** [comment]
This has been fixed.
