### ISSUE TITLE
Fasta incorrectly promotes Iterable<E> to List<dynamic> in strong mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30699]
In the code below Fasta in strong mode would promote `iterable` to `List<dynamic>` after `iterable is List` check. According to @eernstg this is incorrect.

```dart
  void setAll(int index, Iterable<E> iterable) {
    if (iterable is List) {
      setRange(index, index + iterable.length, iterable);
    } else {
      for (E element in iterable) {
        this[index++] = element;
      }
    }
  }
```

**Comment by eernstg** [comment]
Note that the approach used in strong mode for filling in missing type arguments is 'instantiate to bound'. We haven't had a specification of that feature so far. A [proposed informal specification](https://gist.github.com/eernstg/6deffcde2cbe79f8ba499b3aac950900) of that mechanism is being discussed.

**Comment by kasperl** [comment]
It's wrong because `List` and `List<dynamic>` aren't subtypes of `Iterable<E>` in strong mode so there should be no promotion.

**Comment by stereotype441** [comment]
Agreed.  It looks like I forgot to implement this feature of type promotion.  Working on a fix now.

**Comment by stereotype441** [comment]
Should be addressed by https://dart-review.googlesource.com/c/sdk/+/5887
