### ISSUE TITLE
VM doesn't support new Function syntax at all?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30696]
DartPad (i.e. dart2js/analyzer):
https://dartpad.dartlang.org/ae90ff646d90c6cb5feff668d5da30c3

My computer (latest dev build, but doesn't work at stable either):

```
Matans-MacBook-Pro:din matan$ dart --version
Dart VM version: 1.25.0-dev.4.0 (Thu Jun 29 02:23:46 2017) on "macos_x64"
```

```dart
void main() {
  print(new Channel((b) => b.name = 'test').name);
}

class Channel {
  factory Channel(void Function(ChannelBuilder builder) build) {
    final builder = new ChannelBuilder();
  	build(builder);  
    return builder.build();
  }
  
  final String name;
  
  Channel._(this.name);
}

class ChannelBuilder {
  String name;
  
  Channel build() => new Channel._(name);
}
```

---

This seems to work fine in the analyzer (provided you are using a -dev build, it crashes at stable), and fine in dart2js, and I _assume_ DDC, but cannot be parsed in the standalone Dart VM:

```
Matans-MacBook-Pro:din matan$ dart e2e/test.dart
Unhandled exception:
'file:///Users/matan/git/din/e2e/test.dart': error: line 6 pos 35: ',' or ')' expected
  factory Channel(void Function() build) {
                                  ^
#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

I'm a little curious how this feature was considered done since it seems like it mostly didn't work in the analyzer, and doesn't work at all in the VM, but maybe I'm just missing something or I'm writing some sort of corner case - but it doesn't seem like that?

**Comment by zanderso** [comment]
It looks like you're using 1.25.0-dev.4.0, but VM support is in only after 1.25.0-dev.5.0. https://github.com/dart-lang/sdk/commit/f78076d595b0fa11306deede981477733183576d

Can you try with an up to date SDK?

**Comment by matanlurey** [comment]
My assumption (via [@mit-mit's announcement Jun 13th](https://groups.google.com/a/dartlang.org/forum/#!topic/announce/3E2rX4nuarM)) was that this worked as of `1.24.xx` releases, but thanks for pointing that out, my homebrew was many many versions behind. Closing.
