### ISSUE TITLE
StreamSubscription should have getters/setters for the handlers

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30702]
`StreamSubscription` currently has `onData`, `onError` and `onDone` functions that take the new handler.
That feels odd.

-> Make them setters and add corresponding getters.
Either keep the name, or change to `dataHandler`, `doneHandler`, `errorHandler`.
This would correspond to dart:isolate names.

**Comment by lrhn** [comment]
It would have been nice if we had setters as well. With the current Dart class and type restrictions, we cannot have methods and setters with the same base name, and we cannot change the `onDone` method into a getter with type `void Function(void Function())` and add a setter with argument type `void Function()`.

So, it would be a breaking change to replace the `onX` methods, and adding a setter with a different name, like `doneHandler`, and then slowly migrating to that, is probably not worth it.

We can reconsider this for Dart 3.0 (but probably not even there).
I'd consider defining extension setters in `package:async` for people who want it.
