### ISSUE TITLE
BidirectionalIterator should not be in dart:core

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30707]
Suggest to move it to dart:collection

**Comment by matanlurey** [comment]
Why not go one-step further and use `package:collection`? I've never seen this used.

**Comment by srawlins** [comment]
CC @lrhn we could write this into package:collection and officially deprecate BidirectionalIterator in dart:core so that we can delete it in Dart 3 without fanfare.

**Comment by lrhn** [comment]
There is only one use of `BidirectionalIterator` in the platform libraries (`String.runes` of type `Runes`), so there is no need for an interface.
We could move it to `package:collection`, in case someone else uses it, or just remove it completely. Any subclass implementing it will still keep working if you use its exact type, you just can't use `BidirectionalIterator<int>` as a type any more.

The safest option is obivously to keep it.

**Comment by lrhn** [comment]
Having now implemented another class with bi-directional iteration, I chose not to use `BidirectionalIterator` because its method names didn't fit the new class. So, reusability is not a reason to keep the class.

**Comment by mateusfccp** [comment]
This class has been deprecated in 2.18 and removed in 3.0.

Shouldn't this issue be closed?

**Comment by parlough** [comment]
Good catch :)

Fixed by https://github.com/dart-lang/sdk/commit/81b137d8fe7c68fd524605c0f3e62800faca7ea6
