### ISSUE TITLE
double constants should be lower case

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30709]
Since the convention is to have constants as lower case.

**Comment by lrhn** [comment]
Change `NOT_A_NUMBER` to `nan` too. Consider dropping `negativeInfinity` since it's just `-double.infinity`.

**Comment by srawlins** [comment]
This appears to be done. https://api.dartlang.org/stable/2.0.0/dart-core/double-class.html

**Comment by leafpetersen** [comment]
yup.
