### ISSUE TITLE
Function.apply needs to take type arguments

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30712]
There is currently no way to do a Function.apply with type arguments.

**Comment by lrhn** [comment]
We decided not to do this.

The options are:
1. Have multiple `Function.applyX<T1,,,TX>(...)`  methods, one for each arity of type parameters (up to some limit).
2. Have on `Function.apply<...>` which is magically variadic in its type arguments.
3. Have `Function.apply` take type arguments as an `Iterable<Type>`.

Number 3 breaks the invariant that you cannot turn a `Type` object into a type parameter. Our ahead-of-time compilers rely on the fact that only types used as type arguments *somewhere* in the program can ever become the values of type variables. Allowing a `Type` object to be reified as a type variable value will break this, and make tree-shaking types much harder.

Number 2 is too magical. We don't want to, effectively, make `Function.apply` part of the *language*.

Number 1 is too impractical and limited.

All in all, the problem hasn't been that big. You can call any function dynamically using `Function` or `dynamic`, so you only have to use `Function.apply` when you don't even know the *number* of arguments at compile-time. This is exceedingly rare.
