### ISSUE TITLE
Duration constants should be lower-case.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30711]
By convention all constants should be lower case.

**Comment by srawlins** [comment]
This appears to be done: https://api.dartlang.org/stable/2.0.0/dart-core/Duration-class.html

**Comment by srawlins** [comment]
This appears to be done: https://api.dartlang.org/stable/2.0.0/dart-core/Duration-class.html

**Comment by leafpetersen** [comment]
yup.
