### ISSUE TITLE
Front end does not instantiate to bounds on bare types

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30724]
The front end compiles the following code:
```dart
library test;
class A<T extends num> {}
class B<T extends num, S extends T> {}
class C<S extends num, T extends C<S,T>> {}
A a = new A();
B b = new B();
C c = new C();
```
to the kernel representation:
```
...
static field self::A<dynamic> a = new self::A::•<core::num>();
static field self::B<dynamic, dynamic> b = new self::B::•<core::num, core::num>();
static field self::C<dynamic, dynamic> c = new self::C::•<core::num, self::C<core::num, self::C<core::num, dynamic>>>();
```
Note that in the `new` expressions, the types have been correctly instantiated to their bounds, but in the explicit types for the variable declarations, they are instantiated with `dynamic`.

The correct kernel representation would be:
```
static field self::A<core::num> a = new self::A::•<core::num>();
static field self::B<core::num, core::num> b = new self::B::•<core::num, core::num>();
static field self::C<core::num, self::C<core::num, self::C<core::num, dynamic>>> c = new self::C::•<core::num, self::C<core::num, self::C<core::num, dynamic>>>();
```
I suspect there are similar problems for every syntactic structure that can name a type.

**Comment by scheglov** [comment]
Note, not just for `InterfaceType`.
The same feature and issue exists also for typedefs.
```dart
typedef O F<I extends num, O extends num>(I p);
F f; // <num> -> num
```

**Comment by kmillikin** [comment]
Resolved in https://github.com/dart-lang/sdk/commit/1f3b493dccb2a91c2a36ebbcbb97ceeba7b91e5b.

**Comment by scheglov** [comment]
FYI, there were two more failing tests in Analyzer.
I don't say that the new types are incorrect, just reporting a change.

1. `test_instantiateToBounds_boundRefersToEarlierTypeArgument`:
```dart
class C<S extends num, T extends C<S, T>> {}
C c;
```
  Was:
```dart
class C<S extends num, T extends C<S, T>> {
}
C<num, C<num, dynamic>> c;
```
  With FrontEnd:
```dart
class C<S extends num, T extends C<S, T>> {
}
C<num, C<num, C<dynamic, dynamic>>> c;
```

2. `test_instantiateToBounds_boundRefersToLaterTypeArgument`:
```dart
class C<T extends C<T, U>, U extends num> {}
C c;
```
  Was:
```dart
class C<T extends C<T, U>, U extends num> {
}
C<C<dynamic, num>, num> c;
```
  With FrontEnd:
```dart
class C<T extends C<T, U>, U extends num> {
}
C<C<C<dynamic, dynamic>, num>, num> c;
```

**Comment by leafpetersen** [comment]
The analyzer answers for both tests are correct.  This is this current draft spec, and I am basically signed off on it.  https://dart.googlesource.com/sdk/+/refs/changes/42/14042/77/docs/language/informal/instantiate-to-bound.md

The TLDR of the proposed algorithm is:

- Topo sort the bounds based on variable dependency
- Visiting each cycle in dependency order:
  - replace all variables from previous cycles with their already computed default bounds
  - make the computed default bounds for the current cycle be the greatest closure with respect to the variables from the current cycle
    - that is, for each variable in the current cycle, substitute Null for contravariant occurrences and dynamic for covariant occurrences.

**Comment by stefantsov** [comment]
Thanks for pointing to the examples of incorrect behavior. I'm working on the fix: https://github.com/dart-lang/sdk/issues/31778.
