### ISSUE TITLE
standalone_2/env_test fails after the recent restructuring of command line option processing

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#30726]
FAILED: none-vm debug_x64 standalone_2/env_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
No value given to -D option
Unhandled exception:
Could not load "file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/-Dvar": FileSystemException: Cannot open file, path = '/usr/local/google/home/asiva/workspace/dart-tot/sdk/-Dvar' (OS Error: No such file or directory, errno = 2)
null

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart -Dvar -D -D=var -Dvar=invalid -Dvar=valid -Dvar --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-tot/sdk/.packages /usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/standalone_2/env_test.dart
Took 0:00:00.567795

Short reproduction command (experimental):
    python tools/test.py standalone_2/env_test

===
=== 1 test failed
===

**Comment by a-siva** [comment]
@zanderso @mraleph

**Comment by zanderso** [comment]
Why didn't this show up testing locally or on the buildbot?

**Comment by a-siva** [comment]
The test.py script was missing standalone_2 in the list of directories and hence we missed this test.
