### ISSUE TITLE
Handling of invalid URIs in directives

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30725]
1. Empty URI.
```dart
import '';
```
I think this should be an error.
It should not be resolved to the URI of the script.

2. Invalid URI.
```dart
import '[a]';
```
This should be an error, but actually causes an exception.
```
  FormatException: Invalid character (at character 1)
  [a]
  ^
  
  dart:core                                                              _Uri.resolve
  package:front_end/src/fasta/source/source_library_builder.dart 153:35  SourceLibraryBuilder.resolve
  package:front_end/src/fasta/source/source_library_builder.dart 173:21  SourceLibraryBuilder.addImport
  package:front_end/src/fasta/source/outline_builder.dart 180:15         OutlineBuilder.endImport
  package:front_end/src/fasta/parser/parser.dart 373:14                  Parser.parseImport
  package:front_end/src/fasta/parser/parser.dart 329:14                  Parser.parseTopLevelKeywordDeclaration
  package:front_end/src/fasta/parser/parser.dart 274:14                  Parser.parseTopLevelDeclarationImpl
  package:front_end/src/fasta/parser/parser.dart 263:13                  Parser.parseTopLevelDeclaration
  package:front_end/src/fasta/parser/parser.dart 252:15                  Parser.parseUnit
  package:front_end/src/fasta/source/source_loader.dart 161:37           SourceLoader.buildOutline
```

**Comment by askeksa-google** [comment]
The test test_parts_invalidUri_nullStringValue, which is marked as failing because of this issue, is failing for a third reason, namely the presence of string interpolation in a part URI:
```dart
part "${foo}/bar.dart";
```

**Comment by scheglov** [comment]
Do you triage sub-reasons of different kinds of invalid URIs, or argue that `test_parts_invalidUri_nullStringValue` is incorrectly marked as failing because of this issue? I think even URIs with interpolation (which is not allowed by the specification) should be handled without exceptions.

**Comment by askeksa-google** [comment]
Certainly. I am just classifying that particular case as belonging to this issue, as I have an upcoming CL (fixing https://github.com/dart-lang/sdk/issues/30997) which handles the second case but not the first and the third.

**Comment by askeksa-google** [comment]
Resolving the empty string to the URI of the script is correct behavior. The other cases have been fixed.
