### ISSUE TITLE
js_util library should be removed for dart 2.0

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30722]
The `dart:js_util` has only deprecated functionality and is available through package:js_util.

It should be removed for dart 2.0.

**Comment by matanlurey** [comment]
Uh, I don't think it can?

https://github.com/dart-lang/sdk/blob/master/pkg/js/lib/js_util.dart#L1-L8:

```dart
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Allows interoperability with Javascript APIs.
library js_util;

export 'dart:js_util'
```

/cc @jacob314

**Comment by srawlins** [comment]
It could be marked deprecated though.
