### ISSUE TITLE
How to use source maps and DDC?

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#30727]
This is the error I have when navigating to a dart DDC webpage:
![selecao_005](https://user-images.githubusercontent.com/6199518/30461527-788c05d8-9995-11e7-9238-3692f23b0726.png)

This is the same error but within Dartium:
![selecao_006](https://user-images.githubusercontent.com/6199518/30461579-c9bc1ef2-9995-11e7-8430-3fafe93fc3ab.png)

The Enable JavaScript source maps is enabled in my chrome settings.

What else do I need to do to be able to see the original files that threw the error?

Angular 4
Dart VM version: 1.24.2 (Thu Jun 22 15:42:21 2017) on "linux_x64"

**Comment by jodinathan** [comment]
just talked to @jakemac53 and it wasn't using DDC.
I thought the dartdevc flag wasn't need anymore but it is.
Then I tested some error and it threw the correct file within the exception using DDC.
However, the above incorrect error file was thrown using dart2js and my configuration is:

`- $dart2js:
    checked: false
    csp: false
    minify: false
    sourceMaps: true
    suppressHints: true
    suppressWarnings: true
    terse: true
    verbose: true
    environment: { JS: "true" }`

shouldn't the source maps work there?

**Comment by matanlurey** [comment]
Consider opening in `dart-lang/build` if you still have an issue.
