### ISSUE TITLE
VM: New typedef doesn't support annotations on parameters

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30732]
i.e. this is invalid, but it seems to work in other backends:

```dart
typedef GatewayClientFactory = Future<GatewayClient> Function(
  WebSocketFactory factory,
  String url, {
  @required RestClient rest,
});
```

**Comment by eernstg** [comment]
That's an issue with the informal spec. It seems that annotations are meaningful and needed on a normal parameter type as well as a named parameter type? In any case, it would be a surprising exception if named parameters in these Function types support metadata, but other parameters don't.

We've had the old style function typed parameter declaration for a long time with support for metadata (`foo(@bar int f(@Baz(14) String s))`), so there is no new expressive power here to define (or worry about ;-).

I've created a CL adding this metadata support, to be discussed and possibly accepted by the language team. So getting it implemented in the tools is at least a couple of steps down the road.

**Comment by matanlurey** [comment]
No worries, just wanted to double-check. Thanks!
