### ISSUE TITLE
Crash in dart2js with kernel

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30736]
The test language_2/custom_await_stack_trace_test crashes the dart2js compiler when it is run with the 
--dart2js-with-kernel flag.
An example failure is at https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-linux-d8-minified-2-5-be%2F7518%2F%2B%2Frecipes%2Fsteps%2Fdart2js-with-kernel-d8_tests%2F0%2Fstdout

The top of the stack trace is
The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(_LinkedCustomHashSet.E) in j:closure_call(_LinkedCustomHashSet__LinkedCustomHashSet_closure.call).
#0      failedAt (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:55)
#1      LocalsHandler.readLocal (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:322)
#2      TypeBuilder.addTypeVariableReference (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:124)
#3      KernelSsaGraphBuilder.pushIsTest (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3396)
#4      KernelSsaGraphBuilder.visitIsExpression (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3356)
#5      IsExpression.accept (package:kernel/ast.dart:2688)
#6      KernelSsaGraphBuilder.visitReturnStatement (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:995)

**Comment by sigmundch** [comment]
Thanks for filing the bug - most likely this is a test that was migrated and it's status was not added with the migration CL.

At this time we are actively working on a few hundred crashes in the kernel pipeline and we are using the .status file to track things down, so I'll close this bug to track everything in one place.  If you run into similar ones in the future, feel free to update the .status file and skip creating a bug if you like.
