### ISSUE TITLE
Setting up local functions is currently costly, prefer code duplication instead.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30737]
In pkg/front_end/lib/src/fasta/parser/parser.dart:

* Users of the method `parseStuff` should probably use tear-offs.
* The method parseType is probably hot and might benefit from not having local functions. Perhaps a class would be better?

**Comment by peter-ahe-google** [comment]
Updated initial comment to include reference to parser.dart.

**Comment by danrubel** [comment]
I believe that I have removed all local functions in `parser.dart`.
Please re-open if I have missed something.
