### ISSUE TITLE
Add function to rethrow with a provided stacktrace.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30741]
Add a static rethrow method (with a different name since `rethrow` is reserved) that can synchronously throw an object and a stack trace. Currently there is no way to reuse an existing stack trace when throwing synchronously in a sync function, but you can do `await new Future.error(object, stackTrace)` in an `async` function. It's occasionally useful, and we have the functionality anyway (`_rethrow` in `dart:async/zone.dart`), so we should allow it in sync functions too.

Maybe as a static on `Error`: `void Error.throwWithStack(Object error, [StackTrace stackTrace]);` (maybe no need to make the stack trace optional, but it can then get the stackTrace from `error` if it implements `Error`).

**Comment by travissanderson-wf** [comment]
it seems like this would also address https://github.com/dart-lang/sdk/issues/10297

**Comment by alanrussian** [comment]
+1 I ran into a case where I needed to do this.

**Comment by nex3** [comment]
It would also be cool to have `rethrow foo` to mean "throw `foo` with the same stack trace that would be used with `rethrow;`".

**Comment by Hixie** [comment]
Being able to throw or rethrow an exception at a particular stack trace (i.e. to preserve the original stacktrace) would be very valuable for something like https://github.com/flutter/flutter/pull/34626.

**Comment by marcglasberg** [comment]
I need this to improve error handling for the [AsyncRedux](https://pub.dev/packages/async_redux) package. I currently have this code, which may loose the StackTrace.

```
    } catch (error) {
      dynamic processedError = _processError(error, action, afterWasRun);

      // Error is meant to be "swallowed".
      if (processedError == null)
        return;

      // Error was not changed. Rethrows.
      else if (identical(processedError, error))
        rethrow;

      // Error was changed. Rethrows, but looses stacktrace due to Dart architecture.
      // See: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/O1OKnYTUcoo
      // See: https://github.com/dart-lang/sdk/issues/10297
      // This should be improved when this issue is solved: https://github.com/dart-lang/sdk/issues/30741
      else
        throw processedError;
    }
```

**Comment by bsutton** [comment]
I would add my support to this. In [DCli](https://github.com/bsutton/dcli)  I use waitFor within my own waitForEx. The aim of waitForEx is to repair the stack trace the users sees the 'expected' stack trace rather than the microtask stack trace.

```dart
T waitForEx<T>(Future<T> future) {
  Exception exception;
  T value;
  try {
    value = cli.waitFor<T>(future);
  }
  // ignore: avoid_catching_errors
  on AsyncError catch (e) {
    if (e.error is Exception) {
      exception = e.error as Exception;
    } else {
      Settings().verbose('Rethrowing a non DCliException $e');
      rethrow;
    }
  }

  if (exception != null) {
    // recreate the exception so we have a full
    // stacktrace rather than the microtask
    // stacktrace the future leaves us with.
    final stackTrace = StackTraceImpl(skipFrames: 2);

    if (exception is DCliException) {
      throw exception.copyWith(stackTrace);
    } else {
      /// Want to change this so we can throw the original exception with the repaired stack trace.
      throw DCliException.from(exception, stackTrace);
    }
  }
  return value;
}

```

**Comment by nex3** [comment]
> It looks like this code lets me throw with a stacktrace:
> 
> ```dart
> Zone.current.handleUncaughtError(exception,stacktrace);
> ```

That's not *throwing* in the proper sense because it can't be handled by `try`/`catch`/`finally` blocks. It just simulates the behavior of creating a `Future` with an error that isn't handled.

**Comment by lcuis** [comment]
> > It looks like this code lets me throw with a stacktrace:
> > ```dart
> > Zone.current.handleUncaughtError(exception,stacktrace);
> > ```
> 
> That's not _throwing_ in the proper sense because it can't be handled by `try`/`catch`/`finally` blocks. It just simulates the behavior of creating a `Future` with an error that isn't handled.

Argh, too bad, thanks for your answer @nex3 !

**Comment by lcuis** [comment]
I believe this is better. Can you please let me know what you think @nex3 ?

I followed the instructions here:
https://github.com/dart-lang/sdk/wiki/Building

Before building, I added this method to the list of classes below in `dart-sdk/sdk/sdk/lib/async/zone.dart`:
```dart
  throwWithStackTrace(Object exception,StackTrace stackTrace){
    _rethrow(exception,stackTrace);
  }
```
- Zone
- _CustomZone
- _RootZone

I created a dart command line project with the following main pointing to the previously built dart sdk:
```dart
import 'dart:async';

main() {
  try {
    List<int> list = [];
    print(list[0]);
  } catch (error1, st1) {
    print("caught error1: ${error1.toString()} with st1: ${st1.toString()}");
    try {
      Zone.root.throwWithStackTrace(error1, st1);
    } catch (error2, st2) {
      print("caught error2: ${error2.toString()} with st2: ${st2.toString()}");
    }
  }
}
```

I got the following expected output running it:
```
caught error1: RangeError (index): Invalid value: Valid value range is empty: 0 with st1: #0      List.[] (dart:core-patch/growable_array.dart:260:36)
#1      main (file:///.../main.dart:6:15)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

caught error2: RangeError (index): Invalid value: Valid value range is empty: 0 with st2: #0      List.[] (dart:core-patch/growable_array.dart:260:36)
#1      main (file:///.../main.dart:6:15)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)


Process finished with exit code 0
```

**Comment by nex3** [comment]
@rrousselGit To be clear, this isn't something you'll be able to do unless/until the Dart core library adds an explicit API for it. No such API exists today.

**Comment by rrousselGit** [comment]
But I don't mind working on that if the amount of work is reasonable.
  
What would be needed to update the Dart core library to add this API?

**Comment by kristijorgji** [comment]
I also need a rethrow keyword or function for error handling.


```
    } catch (e) {
      _currentRequestCursor = null;
      _dataController.addError(e);
      _networkController.add(NetworkState.error(e.toString()));

      if (!(e is Exception)) {
        rethrow e; // in order to log to error reporting tool
      }
    }
```

if i use normal `throw` there the stack trace would be overwritten and not useful. 
With a `rethrow` functionality would be perfect for error handling

**Comment by mraleph** [comment]
@kristijorgji just write `rethrow;` - this will rethrow `e` while preserving `st`.

**Comment by mkustermann** [comment]
@kristijorgji Additionally to what @mraleph said, there's now a new function which can be used to programatically trow exception with custom stacktrace ([Error.throwWithStackTrace](https://api.dart.dev/be/185382/dart-core/Error/throwWithStackTrace.html))
