### ISSUE TITLE
Reconsider adding `&`, `|` and `^` as operators on bool.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30740]
See: #27396, #7934, #1080, #530

**Comment by jeffque** [comment]
I have this [comment of yours](https://github.com/dart-lang/sdk/issues/530#issuecomment-443135516) in another issue:

> For the record, since Dart 2.1, the `bool` class has had non-short-circuit operators `&`, `|` and `^`.

So, this one is outdated, right? This should then be closed, as the bitwise operators are now available

**Comment by eernstg** [comment]
Right, thanks!
