### ISSUE TITLE
Consider make `Itearator.current` throw instead of returning null when there is no current.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30749]
That behavior would be better suited for non-nullable types.

It's a non-trivial change, and it makes the `current` getter of most iterators much more complicated.

**Comment by floitschG** [comment]
A `for in` loop should treat the `Iterator` of non-nullable collections as non-nullable. If necessary it should do the null check. In many cases it can optimize it away.
There is no need to change the Iterator.
