### ISSUE TITLE
Make `new List(null)` be equivalent to `new List()`. 

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30750]
We have tricky special-casing around the `List` constructor for no good reason.
To just create an empty growable list, you can just write `[]`, so the `new List()` isn't important to recognize.

Non-growable lists are rare in practice, and this special-casing was introduce so that compilers could statically recognize that `new List(n)` creates a fixed-length list. Nobody actually optimizes based on this, so it's unnecessary complication.

**Comment by rakudrama** [comment]
"Nobody actually optimizes based on this"
I'm not sure what 'this' refers to, and by 'nobdy' do you mean developers or compilers?

This suggestion would be harmful to dart2js code quality.

dart2js optimizes based on the presence of the List constructor argument (as if there were two overloaded constructors).
Having a `null` argument return a different type would make things more difficult.
In the case of `new List(n)`, type analysis would sometimes fail to tell if `n` is always `null` or never `null`,  resulting in the type analysis being unable to tell if the list was fixed or growable and apply optimizations based on the list kind.

```dart
foo1(n) {
  var a = new List(n);
  for (var e in a) print(e);
  return a;
}

foo2(n) {
  var a = new List()..length = n;
  for (var e in a) print(e);
  return a;
}
```

```js
    foo1: function(n) {
      var a, _i;
      a = new Array(n);
      a.fixed$length = Array;
      for (_i = 0; _i < n; ++_i)
        H.printString(H.S(a[_i]));
      return a;
    },
    foo2: function(n) {
      var a, t1, _i;
      a = [];
      C.JSArray_methods.set$length(a, n);
      for (t1 = a.length, _i = 0; _i < a.length; a.length === t1 || (0, H.throwConcurrentModificationError)(a), ++_i)
        H.printString(H.S(a[_i]));
      return a;
    },
```

**Comment by lrhn** [comment]
I mean compilers, and I was apparently wrong that the optimization is not being used.

**Comment by lrhn** [comment]
The constructor is removed with null safety.
