### ISSUE TITLE
Consider moving `Sink` to `dart:collection`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30754]
The `Sink` class doesn't really belong in `dart:core`. It's only really used for collections, so move it to `dart:collection`.

**Comment by matanlurey** [comment]
What in `dart:collection` uses `Sink`?

**Comment by lrhn** [comment]
Good point. Lists are not actually sinks because they only have `add`, not `close`.
The only two classes directly implementing `Sink` are in `dart:convert` (`ChunkedConversionSink`) and `dart:async` (`EventSink`).

We should figure out where `Sink` is used (that is, where something *expects* a `Sink`, and move the declaration there. If we can't actually find significant uses, maybe we should just remove the class entirely.

**Comment by lrhn** [comment]
Not changing this now.
