### ISSUE TITLE
Remove `Set.retainAll`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30753]
The `retainAll` method takes an iterable as argument. That's not providing the primitives necessary to implement `retainAll`, so the internal implementation is always fairly expensive and complicated.

Instead of having an expensive function, just make the user use `retainWhere` and then they have to figure out how to make the predicate cheap if they want it.

**Comment by rakudrama** [comment]
We are talking about 10 lines of code, not many pages, so I don't think implementation 'difficulty' should be the guiding principle. 

We have `union`, `difference`, `intersection`.
If one of these has an in-place Iterable analogue, all should.
They are `addAll`, `removeAll` and `retainAll`.

The implementation could be more efficient by building a set of `this.lookup()` values then clearing and adding them back to 'this'.
clear-and-add-back could be implemented efficiently in an implementation by 'stealing' the fields of the temporary set if it has the same implementation.
This outline is O(max(argument.length, result.length))

Is it possible to implement this O(argument.length) with other APIs?

**Comment by lrhn** [comment]
There are numerous ways to implement `retainAll`:
- this.removeAll(this.toSet().removeAll(other))
- this.retainWhere((newSetLikeThis()..addAll(other)).contains)
- (internal) foreach other: lookup entry in self and mark it. Remove all unmarked entries
etc.

I'm not saying it can't be implemented, only that it's far more complicated than the similar methods because it requires find elements that you *don't* look up. All `Set` implementations need to implement it, which is a source of extra complexity (usually turned into time complexity by using one of the first two implementations above).
