### ISSUE TITLE
Need option to customize generated code for enum classes.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#30764]
dart2js puts the toString value in a field in the enum object, alongside the index.
(dart2js used to generate code similar to the kernel front end, with a map to string values.)
Moving the string into the instance removed the need for the map, and made it possible to tree-shake the names of enum members that are not used.
(In practice we can never tree-shake the map because all real programs contain dynamic.toString()).

Avoiding the maps was a JavaScript code size saving and startup cost saving which we need to maintain.

We also want the ability to generate different schemes for different lookups - for example, storing only the name and pre-pending the "Class." on each call to toString(), but only when that would save space, or have a common superclass for the (index, _name) pair to reduce the number of toString() methods.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/16526

**Comment by sjindel-google** [comment]
Enum classes in kernel are now marked as such in the binary format, allow backends to rewrite them however they please.
