### ISSUE TITLE
Analyzer: Non-recoverable state with new Function

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30760]
```sh
$ dart --version
> Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:47:12 2017) on "macos_x64"
```

The following code will at least for me, silently crash the analyzer:

```dart
class Writer {
  Future<T> writeIfAbsent<T>(String key, T Function<T> ifAbsent) {

  }
}
```

Do you see the problem? I didn't 😢 , I needed to write `T Function<T>()`.

Once I did that, the analyzer kicked back in again, but without it I lost basic syntax highlighting and everything else in my file. Unlike other occasions, I didn't get any sort of error/crash, and hitting "restart analysis server" in IntelliJ did nothing to help.

**Comment by jmesserly** [comment]
This appears to be fixed now. (but definitely reopen if we see it again with a new SDK build)
