### ISSUE TITLE
Remove AbstractClassInstantiationError

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30771]
In Dart 2, trying to instantiate an abstract class is a compile-time error, there is no need for a runtime error class.

**Comment by mraleph** [comment]
What happens if you try to instantiate an abstract class through mirrors?

**Comment by lrhn** [comment]
The mirror system gives you an error. It's free to decide which error to use. It can declare its own AbstractInstantiationError if it wants to, but it doesn't need to be in dart:core.

**Comment by lrhn** [comment]
Yes.
