### ISSUE TITLE
Don't let classes be both `EventSink` and `StreamConsumer`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30776]
The `Sink` ,`EventSink`, `StreamConsumer`, `StreamSink` proliferation of interfaces might be overkill. It's a complexity and implementation cost everywhere something is both an `EventSink` and `StreamConsumer` because it has to handle the interaction between `addStream` and `add`. 
I'd prefer to never be both. Make things `EventSink`s, and make `StreamSink` be an `EventSink` with an `StreamConsumer asStreamConsumer()` method. Then it's clear that you can do `add` on the `EventSink` while doing `addStream` on the `StreamConsumer`, and it's the user's job to not interleave incorrectly.

**Comment by natebosch** [comment]
Would this be a new analyzer hint? How would we prevent this from the core library?

**Comment by lrhn** [comment]
No plans to change the current API.
