### ISSUE TITLE
`Stream.toList` should take `{growable:true}` argument

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30774]
For symmetry with `Iterable`.

**Comment by matanlurey** [comment]
One issue today with these optional named arguments is that it makes `dart2js` sad, transforming all sites of `streamInstance.toList()` to `streamInstance.toList(true)`.

How would this be implemented? Wouldn't you have to internally create a list, and then call `.toList(growable: false)` if `growable` is false in this function? Is that worth doing?

**Comment by lrhn** [comment]
It doesn't really make sense. The `growable: false` on iterables makes sense because some iterables know their length efficiently. Those can create and fill a fixed-length list efficiently.
Streams never know their length. 
So, this is jus a wish for unnecessary consistency.
