### ISSUE TITLE
Change analyzer to enable strong mode by default

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30789]
Now that we've flipped to 2.0.0...

**Comment by devoncarew** [comment]
Some initial work here: https://dart-review.googlesource.com/c/sdk/+/9789 to add a hint when an analysis options file has `strong-mode: false`.

**Comment by kevmoo** [comment]
Hint for false landed as 5883eb9904104046bccb9a7879554f5b0ad8372b

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/52461
