### ISSUE TITLE
//sdk:write_version_file should depend on //tools/VERSION

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30794]
Changing the VERSION file, for example, leaves `pub --version` outdated.

Workaround: delete the build output directory.

**Comment by whesse** [comment]
@zanderso knows more about the build rules than I do.

**Comment by zanderso** [comment]
pub (and the other snapshots) are correctly rebuilt on touching //tools/VERSION, but the version file in the resulting SDK doesn't currently have a deps on //tools/VERSION, and so doesn't get regenerated.
