### ISSUE TITLE
Typo in Link.target() and Link.targetSync()documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#30801]
Please see [Link.target()](https://api.dartlang.org/stable/1.24.2/dart-io/Link/target.html) documentation

> If the link does not exist, or is not a link, the future completes with a FileSystemException.

Only Link class has target() method.  It cannot be "not a link"

**Comment by srawlins** [comment]
@sgrekhov I think it is very possible to say `var link = new Link('path/to/a/not/link');`, or even use a path to a non-existent entity, in which case "If the link does not exist, or is not a link" could be true.

**Comment by sgrekhov** [comment]
It is possible to create a Link pointing to not a link or to a not existing entity but it is impossible to call .target() method on not a link object. In other words
```dart
import "dart:io";
main() {
  var link = new Link('path/to/some/entity');
  link.target(); // FileSystemException, link does not exist (link.createSync() was not called)
}
```
The case above is ok. Link does not exist, and future completes with FileSystemException. But here `link` is a Link object. We cannot call .target() method on object with is not a Link
```dart
import "dart:io";
main() {
  dynamic link = new Directory('path/to/a/directory');
  link.target(); // NoSuchMethodError
}
```

**Comment by srawlins** [comment]
You are commenting on the documentation of Link.target, not Directory.target.

In Link.target, the documentation says:

> If the link does not exist, or is not a link, the future completes with a FileSystemException.

This is correct.

```
$ cat /Users/srawlins/a.dart 
import 'dart:io';

main() {
  var link = new Link('/Users/srawlins/a.dart');
  link.target(); // FileSystemException, link does not exist (link.createSync() was not called)
}

$ dart /Users/srawlins/a.dart 
Unhandled exception:
FileSystemException: Cannot get target of link, path = '/Users/srawlins/a.dart' (OS Error: No such file or directory, errno = 2)
```

**Comment by sgrekhov** [comment]
Seems that we don't understand each other. What I meant, is that there cannot be the case when "the link exists but is not a link". Therefore "or is not a link" can be removed. If I'm wrong, please show an example.

**Comment by srawlins** [comment]
I'm not sure why we're miscommunicating either 🙁 My example is [here](https://github.com/dart-lang/sdk/issues/30801#issuecomment-436299337). `/Users/srawlins/a.dart` does exist, and it is not a link. It is a file. `link.target()` threw a FileSystemException in that case.

**Comment by sgrekhov** [comment]
Got it. Sorry for my misunderstanding. Documentation is correct. Closed

**Comment by srawlins** [comment]
Phew, just miscommunication then! Thanks so much for opening these issues, @sgrekhov !!!

These issues really help the Dart team see where we lack documentation. I hope we can prioritize more work improving and correcting the documentation!
