### ISSUE TITLE
Possible leak in generator/stream

### ISSUE THREAD

**Issue by postmasters** [dart-lang/sdk#30807]
This simple code, trivially modified from https://www.dartlang.org/articles/language/beyond-async#fine-print, shows increasing "peak memory" number in Observatory.

```dart
import 'dart:async';

Stream<int> leak() async* {
  int i = 0;
  while (true) {
    yield await i++;
  }
}

Future<int> main() async {
  leak().listen((i) {
    if ((i % (1 << 20)) == 0) {
      print(i);
    }
  });
  return 0;
}
```

**Comment by matanlurey** [comment]
@lrhn or @floitschG can you take a look at this? @postmasters is an internal customer.

**Comment by lrhn** [comment]
Running this using a freshly built `sdk/out/ReleaseX64/dart` with options `--observe` and `--profiler_native_memory`, the peak memory grows to 96.3M and stops there. There is no significant difference in then *heap* memory between 72M and 96M, so it's not heap memory that's leaking.
(The native memory profiler doesn't have any samples, so I can't say what is actually happening).

In any case, this seems to be internal to the VM, not a Dart-level library issue, so I'll forward this to the VM engineers.

**Comment by a-siva** [comment]
Tried running the above code for about an hour and the process memory was seemed to stabilize after some time.
Closing issue, if some growth is still observed with the latest versions of Dart please reopen.

![image](https://user-images.githubusercontent.com/8633293/131197694-8ed03ec2-0854-4dba-a0da-f5782fcaa2dd.png)
