### ISSUE TITLE
VM: Static requirements on type annotations for initializing formals

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30819]
This is the VM specific issue for #30816, which has the details.

This is for Dart 2.0. If the VM will not report any compile-time errors separately (relying on the common front end to do so) then this may be a no-op. Otherwise, the vm should report compile-time errors as described in #30816.

**Comment by leafpetersen** [comment]
Closing this because I think this is probably a no-op for the VM, since it's a static type error that should be handled by the front end (tracked separately).  @a-siva @mraleph let me know if you disagree.
