### ISSUE TITLE
Allow separate analysis options for different tools that use the analyzer

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#30827]
I might want more a more restrictive set of errors in `dartanalyzer` to block my submits in Travis, but  the default set of errors in `dartdevc` when I compile so I can be loose during my dev cycle. In my IDE I'd want to see the same severity for diagnostics as will be used in Travis.

Branching the conversation from https://github.com/dart-lang/sdk/issues/29713 since we never got a new issue filed for distinct config for different tools.

This could also solve https://github.com/dart-lang/sdk/issues/30422 since we could configure those for tools other than DDC.

**Comment by bwilkerson** [comment]
FWIW: It is no longer clear to me that we will have any tools other than the analysis server and the command-line analyzer that use the analyzer, so it's no longer clear to me that any other tools should be using the analysis options files (and hence that there's any need to allow for multiple such files).

But if there is a need for different tools to have different options, and alternative to having multiple analysis options files is to have support within a single analysis options file to specify which tools a given option applies to.

**Comment by natebosch** [comment]
As far as I can tell `ddc` no longer honors the changes to diagnostic severity from `--options` which was the original issue so I don't think we have any user visible impact here.

Hopefully soon we'll migrate to a kernel backed implementation and the analyzer will indeed be the only tool that is configured by analysis options.
