### ISSUE TITLE
dart2js: Static requirements on type annotations for initializing formals

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30820]
This is the dart2js specific issue for #30816, which has the details.

This is for Dart 2.0. If dart2js will not report compile-time errors separately (relying on the common front end to do so), this may be a no-op. Otherwise, dart2js should report the compile-time errors as described in #30816.

**Comment by leafpetersen** [comment]
I think this is a no-op, since dart2js should be getting static errors from the new front end, agreed @sigmundch ?

**Comment by sigmundch** [comment]
correct, thanks!
