### ISSUE TITLE
Type-inference error not equating dynamic and Object

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30829]
/cc @leafpetersen 

Take the following code:

``` dart
void foo(void Function(Object) f) {  }

void main() {
  var f = (dynamic x) { };
  foo(f);
}
```
 This should work: `f` has type `dynamic -> void`, or as the inference currently infers: `dynamic -> Null`.

However I get the following error message:
```
The argument type '(dynamic) → Null' can't be assigned to the parameter type '(Object) → void'.
```

I can remove this error message in two ways:
1. change from `dynamic` to `Object`  (which should be the same thing).
2. change the return type from `Null` to `void` (by making it a nested function).

Neither should be necessary.

**Comment by leafpetersen** [comment]
It will work as soon as I land the change to eliminate fuzzy arrows... :)

Changing the return type is a red herring - making a nested function changes it from a function typed variable (fuzzy arrow type) which can be re-assigned, to a concrete function which cannot be re-assigned (non-fuzzy arrow).

https://github.com/dart-lang/sdk/issues/29630
