### ISSUE TITLE
Hot-Reload: Should set owner of closure functions to be patched class with old script (similar to other functions)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#30824]
It seems like a hot-reload causes existing/old functions to get a new PatchClass as an owner, which holds on to the old script (read: sources) and allows therefore re-compilation of them.

Though currently this owner re-writing happens only for top-level and class-level functions but not for others. In particular we found that closure functions will not get the new PatchClass as owner.  See [object_reload.cc:Class::PatchFieldsAndFunctions](https://github.com/dart-lang/sdk/blob/8562c8ff1bdcbdc43baed287f6979599a16ea386/runtime/vm/object_reload.cc#L341)

Instead hot-reload will end up changing the old owner of closure functions to the newly created classes (which refer to new scripts / sources) as owners. It only seems to work because looking up the scripts for closures happens via following the parent chain instead of the owner.

/cc @mraleph @sivachandra

**Comment by sivachandra** [comment]
As pointed out in #30823, this issue has been solved in a different way and can be closed.
