### ISSUE TITLE
Fasta cannot parse native top-level functions

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30839]
```dart
import 'dart-ext:x';
int m(a) native 'string';
```

```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:2:10: Error: Expected a function body or '=>'.\nint m(a) native 'string';\n         ^";
}
```

We need to decide whether we keep ability to parse native top-level functions in Analyzer and Fasta, or we remove it everywhere.

**Comment by scheglov** [comment]
Ah, that's a good guess.
Yes, we use `NoneTarget` in analyzer's `KernelContext`.

[This CL](https://dart-review.googlesource.com/#/c/sdk/+/8404) will switch it to a target that enables VM's native.

**Comment by jensjoha** [comment]
Does this mean that this issue can be closed?

**Comment by scheglov** [comment]
Yes, this issue has been fixed.
