### ISSUE TITLE
Strong mode type promoted bounds should not be inferred in reified positions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30832]
The following example causes a type promoted type variable to be inferred in a reified position.   We have no representation of intersection types at runtime.  DDC currently just reifies this using the type variable alone, which is unsound, since it results in the lambda being annotated with a reified parameter type of `Object` even though the body of the lambda assumes that it receives only integers.

The simplest fix for this, I think, is to just make inference strip off the promotion when inferring type type variables or lambda parameter/return types.  For the code below, this would make the inferred type of the lambda parameter `T`, and hence the `x.isEven` call would be ill-typed.

```dart
class A<T> {
  A(T x);
  void foo(T x) {}
}


f<T>(T x) {
  var g;
  if (x is int) {
     var a = new A(x);
     var f = a.foo;
     f = (x) {print(x.isEven);};
     g = f;
  }

  g("hello");
}

void main() {
  f<Object>(3);
}
```

cc @jmesserly @stereotype441

**Comment by MichaelRFairhurst** [comment]
@leafpetersen is this still potentially going to drive any potential work to be included in NNBD due to the similarity between type promotion and nullability promotion?

**Comment by leafpetersen** [comment]
Not sure what you're asking - the bug still exists in the NNBD world, and still needs to be fixed.  There may be more places where it can crop up in NNBD, I guess?  For example, `<T extends int?>(T x) => x!` needs to have type `T <T extends int?>Function(T)`, not `T&int <T extends int?>Function(T)` .  Rolling out the general fix for this as part of the NNBD opt in might make sense as a way of avoiding an additional breaking change.

**Comment by leafpetersen** [comment]
This has since been fixed.
