### ISSUE TITLE
dart2js with kernel doesn't keep track of setter symbols

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30847]
Take the following code (adapted from `mock_writable_final_field_test.dart`):

``` dart
class Mock {
  noSuchMethod(Invocation i) {
    print("${const Symbol("x=")} == ${i.memberName}: ${const Symbol("x=") == i.memberName}");
  }
}

main() {
  new Mock().x = 499;
}
```

Without kernel this code works fine.
In minified mode, *with kernel*, we have the following output:
```
Warning: 'saN' is used reflectively but not in MirrorsUsed. This will break minified code.
Symbol("x=") == Symbol("saN"): false
```

It seems like dart2js is not mapping the setter-symbols.

Related: #17526.

**Comment by srawlins** [comment]
This now prints `Symbol("x=") == Symbol("x="): true` (if you change the access to `(new Mock() as dynamic).x = 499;` to satisfy Dart 2's type system).
