### ISSUE TITLE
Fasta does not recover after a missing identifier

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30840]
```dart
print(x) {}
main() {
  print(is String);
}
```

Expected: a single error reported, and a synthetic identifier inserted.

Actual: the whole function is nuked.

```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:3:9: Error: Expected an expression, but got 'is'.\n  print(is String);\n        ^";
}
```

@bwilkerson @danrubel

**Comment by peter-ahe-google** [comment]
Thank you.

There are actually two problems here:

1. The parser isn't able to recover from this expression. I think @danrubel will get to that.

2. Fasta doesn't handle parser errors well and completely destroys the program replacing it with a synthetic main method called `#main` that just throws a string.

**Comment by peter-ahe-google** [comment]
@bwilkerson will fix the first problem.

**Comment by bwilkerson** [comment]
I believe that the first issue should be fixed with https://dart-review.googlesource.com/c/sdk/+/7558.

**Comment by bwilkerson** [comment]
This issue might be impacted by https://dart-review.googlesource.com/c/sdk/+/12040.

**Comment by scheglov** [comment]
Yes, also no failing tests in Analyzer marked with this issue.
