### ISSUE TITLE
Analyzer: Still crashing on GenericFunctionType

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30858]
```dart
final _disposeListeners = <void Function()>[];
```

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.9.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-87-generic unknown, screens 1920x1080, 1920x1080`

# Exception

```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, error: Analysis failed: .../lib/security.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:551)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:357)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:551)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:715)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:784)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:984)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1148)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4364)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:466)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1014)

**Comment by MichaelRFairhurst** [comment]
I had a fix for this quite a long while ago, but my fix caused a secondary issue. It's a pretty deep issue related to synthetic generic element types which I've not had much luck with. Latest solution involved turning off an assertion and is up for review: https://dart-review.googlesource.com/c/sdk/+/20481 but it may not be a viable solution. We'll have to wait for an analyzer member with more familiarity to decide.

**Comment by jmesserly** [comment]
RE: synthetic generic element types, here are some possibly related bugs: https://github.com/dart-lang/sdk/issues/30379 and https://github.com/dart-lang/sdk/issues/29778#issuecomment-317149157

If I recall, synthetic function types are not hooked up to their enclosingElement scope, so FunctionTypeImpl cannot determine which type parameters belong to the function type and which ones belong to enclosing scopes. This means some operations do not work correctly on them (such as equality, instantiation, substitution).

**Comment by MichaelRFairhurst** [comment]
Fix landed in https://dart-review.googlesource.com/c/sdk/+/20481. However, it has some limitations. I'll make new tickets regarding those limitations.

**Comment by MichaelRFairhurst** [comment]
https://github.com/dart-lang/sdk/issues/31804 is that new ticket.

**Comment by MichaelRFairhurst** [comment]
This was reverted, I currently think https://dart-review.googlesource.com/c/sdk/+/33660 is its best chance at being solved, though it won't handle

```
final _disposeListeners = <void Function<T>()>[];
```

**Comment by MichaelRFairhurst** [comment]
Another quick update, looks like this temp solution is better than I'd realized.

```
final _disposeListeners = <void Function<T>()>[];
```

works. You have to go so far as

```
final _disposeListeners = <void Function<T>(Function<G>(G, T))>[];
```

to get a crash.

Assuming that fix actually lands...

**Comment by MichaelRFairhurst** [comment]
Landed, no commit bot issues, looks like this is now ready to be put to bed at least for a while longer :)
