### ISSUE TITLE
Fasta should recognize cyclic generative constructors

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#30856]
Fasta should recognize

```dart
class A {
  A.a() : this.b();
  A.b() : this.a();
}
```

Fasta should mark both of `A`'s constructors as cyclic.

**Comment by peter-ahe-google** [comment]
We need to do the tortoise and hare here as well. We're currently detecting cycles in supertypes and redirecting factory bodies. This needs to be detected as well.
