### ISSUE TITLE
Test fails on dartjs - chrome with signed/unsigned compare

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30853]
Language/Classes/Instance_Methods/Operators/allowed_names_t01 is failing with a check that -8 and a number that is 2^32 - 8 are not equal, in javascript.

So it may be the javascript in chrome, or it may be our translation to javascript, that is the problem.

This is a flaky failure on linux dart2js chrome.  Permanent link to a failure log is 
https://luci-logdog.appspot.com/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8967829586295606432%2F%2B%2Fsteps%2Fdart2js_co19_tests_shard_5%2F0%2Fstdout

Marking the test as flaky in tests/co19/co19-dart2js.status in the  $runtime == chrome section.

**Comment by whesse** [comment]
Also failing on dart2js-d8.  Added to that section in co19-dart2js.status.

**Comment by rakudrama** [comment]
I don't see any failures on the bots - when did this flake, and which bot
(maybe you provided this info and I don't understand how to read the
failure log).

If the status of this test changed, it is probably a dart2js regression
that needs to be tracked down.
The -8 comes from a constant expression (~7) so it should be canonicalized
to uint32 at compile time, which would be independent of where the code is
run.

The only line with anything resembling -8 is compiled to:

      X.Expect_equals(4294967288, 4294967288, null);

I don't see how this could 'flake'. There is simply no way the optimized
program can produce -8.

It is clutching at straws, but perhaps there is a transient VM bug that
causes constant folding in dart2js to occasionally result in -8?

Is there a way to capture the generated code for failing tests on the bots
to see what the generated code was for the failed tests?

**Comment by whesse** [comment]
The link to the log showing the d8 version of the flake is at https://luci-logdog.appspot.com/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8967743996260024640%2F%2B%2Fsteps%2Fdart2js_co19_tests_shard_5%2F0%2Fstdout

so click on the link and search for failed:

The link to the bot run containing that log is
https://ci.chromium.org/swarming/task/38c2c594e3426b10?server=chromium-swarm.appspot.com

The link at the top is from the chrome run that failed.
I can only suggest running the test repeatedly locally, hoping to reproduce.

**Comment by mraleph** [comment]
If we want to diagnose this (given that suspicion that it might be a flake in either Dart VM or V8 itself) then we need to dump generated compilation artifact when test fails. Without it we can't really narrow it down. 

Can we teach test framework to dump +5 lines around every frame in the exception stack trace? 

If compiled JS is correct then it's a flake in V8 interpreting that JS. If compiled JS is incorrect then it is a flake in VM. 

Narrowing down the flake in VM would be very hard - because of the batch mode and various non-determinism involved. We might have to resort to taking the dump of the whole process once this particular test fails and uploading it to the cloud storage.

**Comment by mraleph** [comment]
I am trying to reproduce this locally by running dart2js from source with reduced `--optimization-counter-threshold`, but so far I had no luck.

**Comment by mraleph** [comment]
Resulting JavaScript does not seem to trigger V8's optimizing compiler so flake in V8 is unlikely. I guess we have to operate under assumption that is a flake in VM.

**Comment by mraleph** [comment]
I have hit some similarly looking flakes with `--optimization-counter-threshold=50 --no-background-compilation`. I will starting digging into this on Monday, classifying this as a VM issue:

```dart
Expected: Pass
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
tests/language/precedence_test.dart:82:17:
Warning: The operator '~' is not defined for the class 'num'.
  Expect.equals(~++x + 7, (~4) + 7);
                ^^^^
tests/language/precedence_test.dart:87:17:
Warning: The operator '~' is not defined for the class 'num'.
  Expect.equals(~ --x + 7, (~4) + 7);
                ^^^^^
tests/language/precedence_test.dart:26:18:
Warning: The getter 'isEven' is not defined for the class 'num'.
  Expect.equals(!(++x).isEven, false);
                 ^^^^^^^^^^^^
Compiled 1,767,037 characters Dart to 43,237 characters JavaScript in 0.54 seconds
Dart file (/usr/local/google/home/vegorov/src/dart/sdk/tests/language/precedence_test.dart) compiled to JavaScript: out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js

CommandOutput[d8]:

stdout:
out/ReleaseIA32/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:255: Expect.equals(expected: <4294967299>, actual: <3>) fails.
          throw e;
          ^
Expect.equals(expected: <4294967299>, actual: <3>) fails.
    at Object.wrapException (/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:553:17)
    at Object.Expect__fail (/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:868:15)
    at Object.Expect_equals (/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:865:9)
    at main (/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:953:9)
    at action (out/ReleaseIA32/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:267:31)
    at eventLoop (out/ReleaseIA32/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:250:9)
    at self.dartMainRunner (out/ReleaseIA32/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:268:5)
    at /usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:1227:7
    at init.currentScript (/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:1213:7)
    at /usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js:1224:5



Command[dart2js]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --packages=/usr/local/google/home/vegorov/src/dart/sdk/.packages /usr/local/google/home
/vegorov/src/dart/sdk/tests/language/precedence_test.dart --out=/usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_language_precedence_test/out.js
Took 0:00:00.604770

Command[d8]: DART_CONFIGURATION=ReleaseIA32 /usr/local/google/home/vegorov/src/dart/sdk/third_party/d8/linux/d8 out/ReleaseIA32/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseIA32/generated_compilations/dar
t2js-sdk/tests_language_precedence_test/out.js
Took 0:00:00.190447
```

**Comment by mraleph** [comment]
This was indeed a bug in VM's range analysis. Should be fixed now. Thanks for looping me in @rakudrama

**Comment by rakudrama** [comment]
Thanks for a prompt diagnosis and fix.
