### ISSUE TITLE
DDC should only attempt to initial static variables once.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30852]
DDC tries to run the initialization of static fields multiple times, when the initialization expression throws.

The spec mandates that it should just put `null` in the field and not invoke the RHS again.

`language/lazy_static3.test` fails because of this.

``` dart
var x = throw 499;

main() {
  try {
    print(x);
  } catch (e) {
    print("in catch");
    print(x);  // This should just print `null`.
  }
}
```

**Comment by jmesserly** [comment]
note, DDC does not execute static field initialization multiple times, rather the second error is from the cyclic initialization guard, which is never cleared when `x` throws an exception.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/8240

**Comment by floitschG** [comment]
This fixed the provided example, but `lazy_static3_test` is still failing, and now `lazy_static8_test` is failing too.
Looks like DDC is not resetting lazy statics to `null` when there was an error.

**Comment by jmesserly** [comment]
DDC doesn't run Dart 1 tests under `language`, so we'll not see these until they're ported to language_2 or language_strong. It looks like lazy_static3_test does exist, though. It's an easy fix to get that one passing.

I don't see how lazy_static8_test expected behavior follows from the spec. This was noted in the dart2js bug (https://github.com/dart-lang/sdk/issues/27467), which was fixed to match VM behavior rather than the spec. Not sure what to do there.

**Comment by floitschG** [comment]
I'm porting those tests right now. Which is why I need this issue number.

**Comment by jmesserly** [comment]
if/when someone has bandwidth to pick this up for DDC, this change to the SDK seems to fix both tests:
```js
  // ... inside the JS code for defineLazyField ...
  function cycleError() {
    dart.throwCyclicInitializationError(name);
  }
  desc.get = function() {
    if (init == null) return value;
    let f = init;
    if (f === cycleError) f();
    init = cycleError;
    try {
      value = f();
      init = null;
      return value;
    } catch (e) {
      init = null;
      value = null;
      throw e;
    }
  };
```

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/52282
