### ISSUE TITLE
incremental compiler vs batch compiler 4x slower on flutter_gallery

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30869]
I see first compilation of Flutter gallery sample taking 7 seconds for batch compiler vs 30 seconds for incremental compiler when executed via Flutter engine [frontend_server](https://github.com/flutter/engine/blob/master/frontend_server/lib/server.dart#L139)

I think something is up with frontend_server incremental compiler invocation as it can't be that slow if I understand IKG correctly, but not sure what. Can you folks, @scheglov @sigmundch , please, share ideas?

```
╰─➤  time $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/android_debug_unopt/flutter_patched_sdk --incremental $FH/flutter/examples/flutter_gallery/lib/main.dart | grep "total$"
$FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart  --sdk-root     30.89s user 1.43s system 119% cpu 27.028 total
grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} "total$"  0.00s user 0.00s system 0% cpu 27.027 total
```
```
╰─➤  time $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/android_debug_unopt/flutter_patched_sdk $FH/flutter/examples/flutter_gallery/lib/main.dart | grep "total$"
$FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart  --sdk-root    7.20s user 0.69s system 168% cpu 4.693 total
grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} "total$"  0.00s user 0.00s system 0% cpu 4.692 total
```

@a-siva

**Comment by scheglov** [comment]
I ran it under Observatory and see that RecursiveContinuationRewriter uses `80%` of total compilation time. Given that it is so slow, I guess it process every library, now just new libraries. Unfortunately it is not documented, so I don't know for sure, but hopefully it is possible to run it just for new libraries, not for the whole `Program`.

@kmillikin Could you comment about module vs. global transformation for this transformation?

![image](https://user-images.githubusercontent.com/384794/30765161-08a37620-9fa3-11e7-8319-712ecb7cba43.png)

**Comment by scheglov** [comment]
As an experiment I ran both versions without `RecursiveContinuationRewriter` and get comparable numbers - `3.6 seconds` for non-incremental and `4.8 seconds` for incremental.

**Comment by aam** [comment]
@kmillikin , @scheglov , was this addressed? Who should be the owner of this issue?

30 seconds IKG means that user won't be able to do hot-reload for 30 seconds after starting Flutter app on the device. That does not sound reasonable.

**Comment by scheglov** [comment]
I did nothing to address this.
It seems that it belongs to owners of the transformation and/or Flutter target.

And I agree, it is not reasonable to wait so long.
We cannot afford running not incremental transformation during incremental compilation.

**Comment by sigmundch** [comment]
@aam - thanks for following up here!

There is a general issue with transformers + IKG, which is why I created #30958. I believe we need a general design that makes IKG less vulnerable to changes that add transformations on one target or another. 

We have a sync up with the kernel-team tomorrow and plan to discuss this with them. There are many ideas in the air and we haven't discussed what's feasible, so it's hard to say what the solution would be at this time (e.g. we could be limiting all transformations to work incrementally, or we could say that no transformations are run in IKG but all transformations are run after linking happens). I hope we'll have more answers tomorrow morning, then it will be more clear who will own fixing this.

**Comment by aam** [comment]
Fixed via https://github.com/flutter/engine/pull/4169
