### ISSUE TITLE
Analyzer cannot find 'bool' on Windows

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30862]
Edit: Note that the commit d2f887e37bf75be418a891ab59abeaafc44d0ea9 and was reverted due to the widespread and seemingly flaky test failures. So this issue is no longer relevant for the current master branch, but the information given below might still be useful in debugging and re-landing that CL.

---

Recently there has been much redness on Windows analyzer bots: analyzer-win7-release-be build 7232-7238, analyzer-win7-release-strong-be build 3843-3848.

One recurring problem is that it `Couldn't find 'bool' in 'file:///C:/sdk/lib/core/core.dart'`; for instance, a search for `Couldn't find 'bool'` gets 102 hits in [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-strong-be%2F3848%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-strong-be%2F3848%2F%2B%2F%2A%2A%2Fstderr) and 110 hits [here](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-be%2F7238%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-be%2F7238%2F%2B%2F%2A%2A%2Fstderr).

**Comment by scheglov** [comment]
This should help.

https://dart-review.googlesource.com/#/c/sdk/+/7840
