### ISSUE TITLE
Analyzer: Kernel test subtests now unexpectedly passing

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30863]
Edit: Note that the commit d2f887e37bf75be418a891ab59abeaafc44d0ea9 and the status file changes mentioned below were reverted due to the widespread and seemingly flaky test failures. So this issue is no longer relevant for the current master branch, but the information given below might still be useful in debugging and re-landing that CL.

---

As shown in [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-linux-release-be%2F7513%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-linux-release-be%2F7513%2F%2B%2F%2A%2A%2Fstderr) pkg/analyzer/test/generated/strong_mode_kernel_test is now failing due to a change in behavior in subtests concerned with strong mode inference involving `FutureOr`:
```
00:10 [32m+45[0m[31m -1[0m: StrongModeLocalInferenceTest_Kernel | test_futureOr_methods4 [1m[31m[E][0m[0m
  Test passed - expected to fail.
```
Similarly, from [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-strong-be%2F3753%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-strong-be%2F3753%2F%2B%2F%2A%2A%2Fstderr):
```
00:09 [32m+29[0m[31m -1[0m: StrongModeLocalInferenceTest_Kernel | test_futureOr_assignFromValue [1m[31m[E][0m[0m
  Test passed - expected to fail.
```
The file `pkg/analyzer/test/generated/strong_mode_kernel_test.dart` seems to use in-source status management rather than status files:
```
  @override
  @failingTest
  test_futureOr_methods4() async {
    return super.test_futureOr_methods4();
  }
```
so I did not attempt to adjust the status of the relevant subtests. The behavior seems to be flaky (this test failed as described in analyzer-linux-release-strong-be build 3984 and succeeded in build 3985, and the commit 5daf3c6d9d0cd16d40a06b78b2f95f5011297872 in between only changed some Coq files with mathematical proofs, that the analyzer presumably doesn't depend on..).

Instead I marked the whole strong_mode_kernel_test as `RuntimeError, Pass` in pkg.status. **Please take action** to handle the failure by editing `test_futureOr_methods4` or whatever is appropriate, and then correct or remove the status entry for  strong_mode_kernel_test.

**Comment by eernstg** [comment]
The test pkg/analyzer/test/generated/resolver_kernel_test has an essentially identical problem, cf. [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-strong-be%2F3759%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-strong-be%2F3759%2F%2B%2F%2A%2A%2Fstderr):
```
00:06 [32m+28[0m[31m -1[0m: TypePropagationTest_Kernel | test_forEach_async [1m[31m[E][0m[0m
  Test passed - expected to fail.
```
and [this one](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-be%2F7378%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-be%2F7378%2F%2B%2F%2A%2A%2Fstderr):
```
00:06 [32m+29[0m[31m -1[0m: TypePropagationTest_Kernel | test_forEach_async_inheritedStream [1m[31m[E][0m[0m
  Test passed - expected to fail.
```
A `RuntimeError, Pass` entry for resolver_kernel_test has been created in pkg.status as well. **Please take action** to handle this in the appropriate (in-source?) way and then remove this status entry.

**Comment by scheglov** [comment]
I found a reason why it was flaky.

https://dart-review.googlesource.com/c/sdk/+/7782
