### ISSUE TITLE
complex_layout_scroll_perf_ios performance regressions

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30868]
The following benchmarks regressed with the Dart roll in https://github.com/flutter/flutter/pull/12205:
* complex_layout_scroll_perf_ios__timeline_summary average_frame_rasterizer_time_millis
* complex_layout_scroll_perf_ios__timeline_summary missed_frame_rasterizer_budget_count

It did also improve some benchmarks (reverting them to their earlier state, fixing an earlier regression, see https://github.com/dart-lang/sdk/issues/30786):
* flutter_gallery_ios__transition_perf average_frame_build_time_millis
* flutter_gallery_ios__transition_perf missed_frame_build_budget_count

**Comment by a-siva** [comment]
The regressions in these benchmarks appear to be fixed with consistent results starting 11/21/2017,
closing the bug. If you think otherwise please reopen it.
