### ISSUE TITLE
Inline functions parameter type override

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#30878]
In Dart 2 I am seeing infos about some typing (`uses_dynamic_as_bottom`) and I don't know how I would get around it.

Basically I have something like:

```dart
new A()
  ..func = (int a) {};
```

Where A.func is of type`Function(dynamic a)`

If I make it `Function(Object a)` then it becomes an error: 

"A value of type '(int) → Null' can't be assigned to a variable of type 'Function(Object) → dynamic'."

I put together a dartpad of a few things to try and make something work and clarify some rules for myself, but I couldn't find a way to make inline functions like that work.

https://dartpad.dartlang.org/22a4849f9f0d2fcd3813024df252adf0

Thanks!

**Comment by vsmenon** [comment]
We took a mis-step here.  Our intent is to make `dynamic` in your example work like `Object` - i.e., a static error.

Details here:

https://github.com/dart-lang/sdk/issues/29630

**Comment by jacehensley-wf** [comment]
Oh okay, that makes sense. So should I type the parameters to `Null`?

**Comment by vsmenon** [comment]
For `A.func`?  I think that would work.

@leafpetersen

**Comment by leafpetersen** [comment]
Making `A.func` typed to take `Null` will allow any unary function to be assigned to it.  Note though that you will need to cast it to a different function type (or use a dynamic call) to call it then with anything except `Null`.   That is:

```dart
Function(Null) f = (int x) => x + 1;
f(3); // This will fail, because of an implied downcast of `3` to `Null`
(f as Function(int))(3); // This will work
(f as dynamic)(3); // This will work.
```

**Comment by jacehensley-wf** [comment]
> you will need to cast it to a different function type

That shows as an unnecessary cast info

---
So is there no "bottom" type that isn't null? Something like "Anything"? Because typing the parameter to `Object` doesn't work and neither does `dynamic`.

```dart
Function(Object) f2 = (int x) => x + 1; // warning
f2(3);
(f2 as Function(int))(3);
(f2 as dynamic)(3);
  
Function(dynamic) f3 = (int x) => x + 1; // info
f3(3);
(f3 as Function(int))(3);
(f3 as dynamic)(3);
```

**Comment by leafpetersen** [comment]
> That shows as an unnecessary cast info

Bug.  Filed it here https://github.com/dart-lang/sdk/issues/30897 .
