### ISSUE TITLE
Crash in dart vm when running test.py

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30883]
Twice in the past day we have seen failures where the Dart vm running the test scripts (the test runner, test.py) has failed in native code, with the message

Dart_StringToCString expects argument 'object' to be of type String.

There is no stack trace in either Dart or C for this, only this line and an exit code of 255.
Neither the test scripts nor the checked-in version of the Dart SDK has changed recently, though I plan to update the Dart SDK very soon.  The present version is 1.25.0-dev.7.0, and we are now at dev version 2.0.0-dev.1.0.

If this continues to fail flakily like this, it will be very hard to debug, because we aren't getting a trace.
In that case, our best hope is to update the checked-in SDK.  We will wait and see, but if you have any ideas about how to get a stack trace, let me know.

The failure log is at

https://ci.chromium.org/swarming/task/38d68b7090fc4710?server=chromium-swarm.appspot.com

**Comment by mkustermann** [comment]
Can this be closed in favor of https://github.com/dart-lang/sdk/issues/30990 ?

**Comment by athomas** [comment]
Duplicate.
