### ISSUE TITLE
Building dart on rodete results in binaries using a newer version of GLIBCXX

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#30882]
I've opted into the rodete upgrade on my linux machine, built the sdk with the dart2js_bot target and then tried to run a sharded test on LUCI (using an Ubuntu 14.04 bot). That fails because the dart executable built on rodete requires GLIBCXX_3.4.21. @whesse @zanderso 

Running "dart2js" command: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --packages=/b/swarming/w/ir/.packages /b/swarming/w/ir/runtime/tests/vm/dart/double_to_smi_test.dart --out=/b/swarming/w/ir/out/ReleaseIA32/generated_compilations/dart2js/runtime_tests_vm_dart_double_to_smi_test/out.js

FAILED: dart2js-d8 release_ia32 vm/dart/double_to_smi_test
Expected: Pass 
Actual: CompileTimeError
Unexpected compile-time error.
CommandOutput[dart2js]:

stderr:
/b/swarming/w/ir/sdk/bin/../../out/ReleaseIA32/dart: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /b/swarming/w/ir/sdk/bin/../../out/ReleaseIA32/dart)

**Comment by zanderso** [comment]
For 32-bit Linux we use the host gcc with the host sysroot as default. You can specify the Debian wheezy sysroot, which has lower glibc requirements, by manually invoking //tools/gn.py with: `./tools/gn.py -m release -a ia32 --wheezy`. For the 64-bit Linux build, we use clang, which should also have a lower glibc requirement as well.

**Comment by zanderso** [comment]
I should have also mentioned: If you're able to try the above and can get something to work, I think I'm not sure what action there is to take. We're stuck using the host gcc for ia32 on Linux because clang miscompiles some inline assembly in tcmalloc.
