### ISSUE TITLE
Can't rename typedef in type parameter

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#30884]
Dart SDK 2.0.0-dev.1.0, IntelliJ IDEA 2017.2.4 Build #IU-172.4155.36, Plugin 172.4155.35

Try to rename `MyFunction` with Shift-F6:
```dart
typedef void MyFunction();

void foo<T>() {}

void main() {
  foo<MyFunction>();
}
```

**Comment by devoncarew** [comment]
I can repro this. IntelliJ does offer to refactor, but the reference from the type arg is not updated.

**Comment by bwilkerson** [comment]
Test added in https://dart-review.googlesource.com/c/sdk/+/38484.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/38784
