### ISSUE TITLE
Incorrect "unnecessary cast" hint.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30897]
The following program produces an "unnecessary hint" cast from the analyzer.

```dart
void main() {
  Function(Null) f = (String x) => x;
  (f as Function(int))(3); 
}
```

The cast here is definitely necessary.

**Comment by leafpetersen** [comment]
This showed up again, causing some confusion.

**Comment by leafpetersen** [comment]
This popped up again fixing internal code with a slightly different repro:

```dart
class A {}

class B<T extends A> {
  void foo() {
    T Function(T) f;
    A Function(A) g;
    g = f as A Function(A);
  }
}
```

I suspect that the unnecessary cast code might be using Dart 1 subtyping. 

cc @vsmenon @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/54715
