### ISSUE TITLE
expose a stable and supported method of bootstrapping applications

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#30893]
Today there is at least one special thing you have to do when bootstrapping an application, which is to import the `dart_sdk` module and call `dart_sdk._isolate_helper.startRootIsolate(() => {}, []);`. In debug mode there are additional things such as `dart_sdk._debugger.registerDevtoolsFormatter();` etc.

See [here](https://github.com/dart-lang/pub/blob/9e216e0a5e415aa12cf7f356547a3cb7b14f23a1/lib/src/dartdevc/dartdevc.dart#L208) for the nitty details of what pub does, as well as [here](https://github.com/dart-lang/pub/blob/9e216e0a5e415aa12cf7f356547a3cb7b14f23a1/lib/src/dartdevc/dartdevc.dart#L147) which is more related to stack trace mapping I think.

Ideally, all this code would live in the SDK and be hidden under a single entrypoint method that we can invoke which is stable and handles the details.

**Comment by vsmenon** [comment]
Closing in favor of: #31516
