### ISSUE TITLE
type_promotion_functions_test requires rewrite for Dart 2.0

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#30895]
Comment from Erik Ernst on https://dart-review.googlesource.com/c/sdk/+/7440/1/tests/language_2/type_promotion_functions_test.dart:

> Dart 2 will not have the notion of 'more specific than', so we should use `<:` (subtype) rather than `<<` (more specific than). This affects many locations in several tests, but I'll only mention it here.
> 
> However, in Dart 2 these subtype relationships depend on the treatment of `dynamic` ('fuzzy arrows' makes `dynamic` the bottom type in some cases, but fuzzy arrows are currently being eliminated so this test will need to be updated at some point in the future for that).
> 
> With the current behavior, we have the following subtype relationships (it is slightly different if we accept a 'hint: uses_dynamic_as_bottom'):
> 
>   funcDynToDyn == funcDynToVoid // For subtyping in Dart 2, void == Object == dynamic
>   funcDynToA <: funcDynToDyn
> 
> this means that the following are examples where there is no subtype relationship:
> 
>   FuncDynToDyn </: FuncAtoDyn
>   FuncDynToDyn </: FuncDynToA
> 
> Among the ones which are expected to hold according to the comment, only FuncDynToA <: FuncDynToVoid actually holds! Furthermore, a number of function literals appear in the code, and their dynamic type will be affected by inference, which means that the outcome of running the code may be different. For instance, a variant of this test where a print statement is inserted in each if-body shows that only some of the if-bodies get executed. In that case, of course, we won't be testing the behaviors expected from the statements in that if-body.
> 
> This basically means that the entire analysis which was behind tho formulation of this test has to be re-done, and lots of things may have to be changed, in order to express the correct expectations according to the language.
> 
> I would recommend that this particular test is somehow labeled "MUST BE REWRITTEN FROM SCRATCH".
> 
> Maybe it should simply be taken out of this block, or it could have a status entry which is a new issue which describes its actual behavior, MissingCompiletimeError or whatever it needs, and then refers to an issue which says that this test must be rewritten because of the above deep incompatibility between Dart 1.x and Dart 2 in this area.

Test is currently skipped for strong mode.

**Comment by eernstg** [comment]
I fixed the test and landed the update in 69790e7eb4145bad22b15fcc47c1a42d4c1322e7.

(There wasn't actually an 'area-language' issue here, but this test was based on Dart 1 function type subtype rules, and that caused a substantial portion of the code and its expected outcomes to be plain wrong for Dart of today).
