### ISSUE TITLE
vm reload fails flakily on lib_2/async/stream_periodic4_test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30904]
On the bot
https://luci-milo.appspot.com/buildbot/client.dart/vm-linux-debug-x64-reload-be/
the test lib_2/async/stream_periodic4_test started failing flakily after the commits of
https://dart-review.googlesource.com/c/sdk/+/8732
https://dart-review.googlesource.com/c/sdk/+/8702
https://dart-review.googlesource.com/c/sdk/+/8164

An example failure log is at
https://luci-milo.appspot.com/buildbot/client.dart/vm-linux-debug-x64-reload-be/3056

This flaky status is now noted in status file
tests/lib_2/lib_2.status

FAILED: none-vm debug_x64 lib_2/async/stream_periodic4_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 +0: stream-periodic4
00:21 +0 -1: stream-periodic4 [E]
  Expected: <false>
    Actual: <true>
  
  package:test/src/frontend/expect.dart 164:30                  fail
  package:test/src/frontend/expect.dart 158:3                   _expect
  package:test/src/frontend/expect.dart 68:3                    expect
  tests/lib_2/async/stream_periodic4_test.dart 23:9             runTest.<fn>

**Comment by a-siva** [comment]
Checked the current test results on this test and it appears to be green for tall the VM bots including the reload bots.
Closing the issue.
