### ISSUE TITLE
Add curl to linux dependencies on "Building" wiki page

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#30913]
Some linux distros (e.g. minimal installation of Ubuntu 17.04) don't include `curl` by default. Because of this, `gclient sync` fails at some point. 

Please, consider changing this line:
```
sudo apt-get install g++ git make python
```
to
```
sudo apt-get install g++ git make python curl
```
[here](https://github.com/dart-lang/sdk/wiki/Building#linux).

**Comment by mraleph** [comment]
Done
