### ISSUE TITLE
Frontend needs to implement fixed-size integer semantics during const evaluation

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30916]
With fixed-sized integers, the frontend needs to implement 64-bit wrap-around integer semantics during const-evaluation (for the VM).

See https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md for the proposed semantics.

Note that const-evaluation should yield the same result as during runtime. It's not completely obvious which parts of expressions are const and which ones aren't and if they had different semantics that would be very confusing.

**Comment by anders-sandholm** [comment]
@sjindel-google

**Comment by mkustermann** [comment]
At least for AOT we plan on using the kernel2kernel constant evaluation transformation in [package:kernel/transformations/constants.dart](https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/transformations/constants.dart).

I have an in-progress change which fixes a few necessary things before it can be enabled by default. These changes include also adding support for doing the wrap-around semantics during the const evaluation.

**Comment by kmillikin** [comment]
We don't do constant evaluation in the front end (yet).  We are aware of the differences in integer semantics and we're unlikely to implement something that ignores it.
