### ISSUE TITLE
Analyzer does not reject a generic function type used as type argument

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30929]
The informal spec on generic functions states: "It is a compile-time error if a generic function type is used as an actual type argument."

This should be detected by the analyzer, but is not.
See tests/language_2/generic_function_type_as_type_argument_test.dart
and https://dart-review.googlesource.com/c/sdk/+/9369

**Comment by srawlins** [comment]
This is recently allowed in the spec! Something like Dart 2.15.
