### ISSUE TITLE
Analyzer warns about unreachable code when it's still reachable.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30936]
See: https://dartpad.dartlang.org/19992615f7f2c93faf55fd6e2251d625
```dart
void main(args) {
  parseArgs(["--"]);
}
void parseArgs(args) {
  search: {
    for (var arg in args) {
      if (arg == "--") break search;
    }
    print("does not contain --");
    return;
  }
  // Potentially more complex code that you don't want in the loop.
  print("contains --");
}
```
It reports the final print line as unreachable, even though that line is actually executed.

It seems to not recognize a break in a labeled the block as a way to exit that block before reaching the return statement.

**Comment by srawlins** [comment]
The analyzer now reports nothing for this code (both with and without `--enable-experiment=non-nullable`).
