### ISSUE TITLE
Analyzer changed resolution of typedef reference

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30932]
```dart
typedef void F<T>(T t);
F<int> f;
```

Used to be:
```dart
FunctionType(element=FunctionTypeAliasElement) f;
```

With [this CL](https://dart-review.googlesource.com/c/sdk/+/9421/2):
```dart
FunctionType(element=GenericFunctionTypeElement) f;
```

where the `GenericFunctionTypeElement` is a `function` of a `GenericTypeAliasElement `.

This breaks a [DDC test](https://luci-logdog.appspot.com/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8967172948324827616%2F%2B%2Fsteps%2Fddc_tests%2F0%2Fstdout).

**Comment by jmesserly** [comment]
Thanks! Yeah I think that test is not right (and we have a DDC bug too). Correct behavior should be:
```diff
diff --git a/tests/language_2/type_literal_test.dart b/tests/language_2/type_literal_test.dart
index 4260696f7c..94e3750ebe 100644
--- a/tests/language_2/type_literal_test.dart
+++ b/tests/language_2/type_literal_test.dart
@@ -42,12 +42,9 @@ main() {
   testType(new Box<Box<Foo>>().typeArg, "Box<Foo>");
 
   // Typedef.
-  testType(Func, "Func((bool) -> int)");
-  testType(GenericFunc, "GenericFunc((bottom) -> int)");
-
-  // TODO(rnystrom): This should print "GenericFunc<int>", but that isn't
-  // implemented yet.
-  testType(new Box<GenericFunc<int>>().typeArg, "GenericFunc((int) -> int)");
+  testType(Func, "Func");
+  testType(GenericFunc, "GenericFunc");
+  testType(new Box<GenericFunc<int>>().typeArg, "GenericFunc<int>");
 
   // Literals are canonicalized.
   Expect.identical(Foo, Foo);
```

**Comment by jmesserly** [comment]
In other words, DDC should always preserve the typedef name and type arguments in its TypeRep.toString. It looks like we had a bug already for `GenericFun` and now we also lose the fact that it is even a typedef (vs a normal function type).

**Comment by nshahan** [comment]
This issue is related to analyzer based DDC and is out of date. All of the type_literal_test variations from the language suite are now passing in DDC.
