### ISSUE TITLE
Allow annotations on enum constants

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30934]
See error code ANNOTATION_ON_ENUM_CONSTANT

Why the restriction? Hitting this here: https://github.com/dart-lang/json_serializable/issues/38

**Comment by lrhn** [comment]
The spec indeed doesn't allow annotations on enum item declarations. 
That's is probably an oversight, so we should just fix it in Dart 2.

**Comment by kevmoo** [comment]
Duplicate of #23441
