### ISSUE TITLE
Kernel (Fasta) does not report an error when a generic function type is used as a type argument

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30931]
The informal spec on generic functions states: "It is a compile-time error if a generic function type is used as an actual type argument."

This should be detected by fasta, but is not. There seem to be an issue parsing the test as well.
See tests/language_2/generic_function_type_as_type_argument_test.dart
and https://dart-review.googlesource.com/c/sdk/+/9369

**Comment by peter-ahe-google** [comment]
Thank you. This seems like a low priority right now, but hopefully I'll be able to soon get back in a mode where I bring the number of test failures down.

**Comment by kmillikin** [comment]
Elevating the priority to ensure that this makes it into Dart 2.1.
