### ISSUE TITLE
Dart 2.0 Await does not work for transformed stream that returns future

### ISSUE THREAD

**Issue by shahrin-14** [dart-lang/sdk#30937]
For the following code, await works.
``` dart
  if(!(await targetDirectory.exists())) {
    print("Directory $targetPath does not exist");
    return;
  }

  await targetDirectory.list(recursive: true, followLinks: false) //this await works
    .listen((FileSystemEntity targetEntity) {
        ...
      },
      onError: (e) { print(e.toString()); }
      onDone : () { outputStream.close(); }
    ).asFuture();

  printLog("Finished");
  //operationFile.flushBuffer("sourceLastModified");
}
```

But for the following code, await does not work.
 ``` dart
  File progFile = new File("$progFilename");
  await (progFile.create());
  Stream<List<String>> inputStream = planFile.openRead();

  await inputStream //this await does not work
    .transform(UTF8.decoder)       // Decode bytes to UTF8.
    .transform(new LineSplitter());// Convert stream to individual lines.
    .listen((String line) {        // Process results.
        ...
      },
      onDone: () { print('File is now closed.'); },
      onError: (e) { print(e.toString()); }
    ).asFuture();
```

For something seemingly similar, I expect similar behaviour.

**Comment by floitschG** [comment]
What does "does not work" mean?

Note that 'asFuture' overwrites the `onDone` and `onError` handlers, so in both examples the two functions will not trigger.

**Comment by natebosch** [comment]
I believe this is working as intended given that `asFuture` overrides `onDone` and `onError`. If you believe this is still a problem please add a comment explaining what you expect should be happening and we will reopen.

**Comment by dmvvilela** [comment]
How can i make this work? I need it not to listen, but to return a future.. I udnerstand this guys problems lol..

**Comment by natebosch** [comment]
If you need a `Future` representing the end of the stream without listening you can use `.drain()`.  https://api.dartlang.org/stable/2.3.1/dart-async/Stream/drain.html

If you need to listen and want to handle the completion and error as a `Future` (rather than with the `onError` and `onDone` callbacks`, you'd structure something like


```dart
void doStuff(Stream someStream) async {
  try {
    await someStream.listen(handleValues).asFuture();
    performOnDone();
  } catch(e) {
    performOnError();
  }
}
```

**Comment by dmvvilela** [comment]
Yeah, i did it with callbacks. I guess you can use completers too right? I still dont know what asFuture() does though..

**Comment by natebosch** [comment]
> I still dont know what asFuture() does though..

It's what allowed me to use the `try/catch` and to put `performOnDone();` as the next statement after an `await` rather than having to put it in `onError` and `onDone` respectively.
