### ISSUE TITLE
Dart2js does not report an error when a generic function type is used as a type argument.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30930]
The informal spec on generic functions states: "It is a compile-time error if a generic function type is used as an actual type argument."

This should be detected by dart2js, but is not. There seem to be an issue parsing the test as well.
See tests/language_2/generic_function_type_as_type_argument_test.dart
and https://dart-review.googlesource.com/c/sdk/+/9369

**Comment by sigmundch** [comment]
Thanks @crelier - both issues should be handled in the parser, which happens to already be the parser from fasta, so I'm closing this in favor of the other bug you filed in #30931
