### ISSUE TITLE
Running dart2js in checked mode can cause it to crash

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30956]
In sdk/pkg/compiler/lib/src/resolution/resolution_strategy.dart, on line 300, there is a return that causes a `String` to be returned from a closure. The closure was passed in as the first argument in an assert statement (line 251), where it is expected to return a `bool`. When the VM executing dart2js is run in checked mode, it is possible for this assert to cause an exception to be thrown (other than the normal AssertionError) and this causes dart2js to crash.

**Comment by joshualitt** [comment]
I'm going to close this issue due to its age and the lack of a detailed repro. Please reopen this issue if it is still occurring.
