### ISSUE TITLE
Specify asserts in initialization lists

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30967]
We have an informal specification:

https://github.com/dart-lang/sdk/blob/master/docs/language/informal/assert-in-initializer-list.md

But that only works on casual Fridays. For the remainder of the week, we need a formal suit and tie specification.

**Comment by lrhn** [comment]
This specification landed in a72f46def8899b6f1a7fc5609f3b503c5d79b16f.

**Comment by munificent** [comment]
Awesome, thanks!
