### ISSUE TITLE
Forwarding stub for a mixin implementation cannot be representend without binding a name twice

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30965]
Consider the following source code (adapted from `pkg/front_end/testcases/runtime_checks/covariant_generic_parameter_in_interface_mixin.dart`):

```dart
class B {
  void f(int x) {}
}
abstract class I<T> {
  void f(T x);
}
class M {
  void f(int x) {}
}
class C = B with M implements I<int>;
void g(I<num> i) {
  i.f(1.5);
}
main() {
  g(new C());
}
```

At compile time, the call from `main` to `g` is properly typed (since `C` <: `I<int>` <: `I<num>`), and the call from `g` to `I.f` is properly typed (since `I<num>.f` has type `(num) -> void`).  However, at run time the call to `I.f` resolves to `M.f`, which requires its argument to be `int`.  So we need a runtime type check to verify that the type of the argument to `f`.  This runtime type check can't be compiled into `M`, since, in a modular compilation scenario, the need for a runtime type check isn't discovered until `C` is encountered.  Therefore the runtime type check must somehow be inserted into `C`.

The way we have decided to address this is to have the front end create a forwarding stub inside class `C`:

```dart
  void f(int /*@covariance=genericImpl*/ x) => super.f(x);
```

With the understanding that the call from `C.f` to "super" resolves to the mixed in method `M.f`.

However, when I tried to implement this in the front end, I encountered the kernel error:

```
root::.../sdk/pkg/front_end/testcases/runtime_checks/covariant_generic_parameter_in_interface_mixin.dart::C::@methods::f is already bound
```

It seems that kernel considers all of the mixed in methods to be bound in the namespace of the mixin application, so it is not possible to also bind this name to the forwarding stub.

**Comment by kmillikin** [comment]
The call to `i.f` at runtime actually targets the method `f` in the mixin application class (and not `M.f`) but that method is implicit until after mixin elimination makes it concrete.  Before mixin elimination the class C looks like:

```
class C = self::B with self::M implements self::I<core::int> {
  constructor •() → void
    : super self::B::•()
    ;
}
```

And after transformation we copy the methods from the mixin class in and make this a regular class:

```
class C extends self::B implements self::I<core::int>, self::M {
  constructor •() → void
    : super self::B::•()
    ;
  method f(core::int x) → void {}
}
```

The transformation is written to assume that mixin application classes do not have any methods, so we don't detect the duplicate method until we try to serialize and then we discover the duplicate name, which gives the unhelpful message you see.

One possibility is to add the forwarding stub to C and then in the mixin transformation, when copying methods from M into C, check for an existing forwarding stub with the same name and just make it a method with (a copy of) the body. 

(Is this a problem that can only arise with named mixin applications?  Anonymous ones do not have a body to add the forwarding stub to, but they are abstract and shouldn't be instantiated.)

**Comment by stereotype441** [comment]
This has been addressed.
