### ISSUE TITLE
Remove flag and default --assert_initializer to enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30976]
Asserts in initializers will be a fully-supported feature in 2.0 (#30968), so the VM should enable it by default and remove the flag.

**Comment by a-siva** [comment]
landed https://github.com/dart-lang/sdk/commit/af550c9b6ce1e7a4803fa8e830a1da7cf3ea8612

**Comment by munificent** [comment]
Thanks!

**Comment by munificent** [comment]
This is the right commit: fa57f54572bb006b4a7e8f9b946285f5498721df.
