### ISSUE TITLE
Remove flag and turn on --enable-assert-initializers by default

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30977]
Asserts in initializers will be a fully-supported feature in 2.0 (#30968), so the analyzer should enable it by default and remove the flag.

**Comment by bwilkerson** [comment]
@munificent Does this work need to be coordinated with anything else, or is it reasonable to do it now?

**Comment by munificent** [comment]
If you remove the flag entirely such that it's an *error* to pass it, then you'll want to check with the Flutter folks to make sure any scripts they have that drive the analyzer stop passing that flag.

If you simply default assert initializers on and allow but ignore the flag, then you should be able to flip it on whenever you like.

**Comment by bwilkerson** [comment]
CL is out for review.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/10740

There was no command-line flag, only an option in the analysis options file. Analyzer will now produce a hint that the option is not valid and will ignore it.

**Comment by munificent** [comment]
> There was no command-line flag, only an option in the analysis options file. 

Are you sure? In analyzer_cli, I see:

```dart
        enableAssertInitializer = args['enable-assert-initializers'],
```

**Comment by bwilkerson** [comment]
No, I somehow managed to miss that when I looked. I did manage to remove the code that makes use of the argument, so it's now a no-op to include it, but I should at least mark the option as being deprecated.

**Comment by bwilkerson** [comment]
I left the flag so that it won't break existing clients, but cleaned up the references to it (https://dart-review.googlesource.com/c/sdk/+/11260).
