### ISSUE TITLE
Arg0 of Process.start is corrupted in started subprocess

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30971]
This is rumored to be caused by https://codereview.chromium.org/3007703002 , "Add namespaces for File IO".

This is affecting test.dart: When the checked-in SDK is updated to a version containing this issue, the dartanalyzer-hostchecked and dart2js-hostchecked bots crash all tests they run, and that is because the dartanalyzer_developer and dart2js_developer bash scripts refer to $0 and $BASH_SOURCE.  If the scripts are changed to not use those variables, the tests stop crashing.

When this issue is fixed, let me know, and I will release a new dev build with this fix.
@keertip @srawlins @mraleph @zanderso

**Comment by zanderso** [comment]
Fix in progress here: https://dart-review.googlesource.com/#/c/sdk/+/10205/
