### ISSUE TITLE
Not constant map that looks like a statement is not parsed

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30983]
```dart
f() {
  {'a' : 0, 'b' : 1}.length;
}
```

```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:2:8: Error: Expected ';' before this.\n  {'a' : 0, 'b' : 1};\n       ^";
}
```

**Comment by peter-ahe-google** [comment]
Another instance of deprecated_InputError. Please keep reporting these issues, I really appreciate the reproduction tests. Let me know if this is blocking you.

**Comment by bwilkerson** [comment]
This issue might be impacted by https://dart-review.googlesource.com/c/sdk/+/12040.

**Comment by scheglov** [comment]
Yes, also no failing tests in Analyzer marked with this issue.
