### ISSUE TITLE
Invalid use of a reserved word causes damaged kernel

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30986]
```dart
f() {
  typedef x;
}
```

```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:2:11: Error: Expected ';' before this.\n  typedef x;\n          ^";
}
```

**Comment by peter-ahe-google** [comment]
Also an instance of deprecated_InputError. Let me know if this becomes a blocker for you.

**Comment by bwilkerson** [comment]
This issue might be impacted by https://dart-review.googlesource.com/c/sdk/+/12040.

**Comment by scheglov** [comment]
I don't see any failing test in Analyzer that is marked with this issue.
So, I guess you fixed it!
