### ISSUE TITLE
// "Document" comment in main.dart.js code crashes webpage load

### ISSUE THREAD

**Issue by pslavers** [dart-lang/sdk#30992]
G'Day,
Please compare the results of attempting to load the following web pages in Chrome, or Edge:
   sudoku.geobits.com/index,html
   sudoku.geobits.com/with_comment/index,html

The first loads successfully, the second does not.
The difference is that in the former the comment at line 32071 has been removed.
Comment is:
'// "Document", so we check for the xmlVersion property, which is the empty'

This *MAY* just be a windows LFCR issue, I cannot tell as I don't have a LINUX box on which to test.
It *MAY* also be a server problem, but I ran on a local server and got the same problem.

For the time being, the work around is to remove the comment by hand.

I love working in AngularDart, thanks for a great language.
Cheers,
Phil.

**Comment by anders-sandholm** [comment]
Looks like there might be an issue in IE with a comment in 
sdk/lib/_internal/js_runtime/lib/native_helper.dart

**Comment by pslavers** [comment]
G'Day,
If the double quotes (both sets) are removed from around the word Document in the comment on line 562, the problem goes away. Perhaps it is better to fix the comment remover, but as a work-around there could be a ban on double quotes in // comments.
Hope this helps,
Cheers,
Phil.
