### ISSUE TITLE
VM: Error message refers to generated name.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30993]
The following program can be executed with `dart --checked` version 1.25.0-dev.16.4, producing an output which includes `type 'int' is not a subtype of type 'String' of 'value' where ..`:
```dart

class C {
  int i = 42;
  String s;
  foo() {
    s = i;
  }
}

main() {
  new C().foo();
}
```
Surely, it is just because `s = i` is an invocation of the implicitly generated setter `s=`, and that setter has an argument named `value`. But that setter was generated implicitly, and the developer can't know the name of its argument. In a more complex setting, developers may start chasing things named 'value' for a while.

So maybe that case should be detected, and something about "calling the setter `s=`" could be reported, rather than talking about 'value'?

**Comment by a-siva** [comment]
@crelier can something be done about this error message? I am suspecting it is coming from the dst_name computed from the argument passed to TypeCheck in runtime_entry.cc

**Comment by crelier** [comment]
That's a pretty bad error message, indeed. We should be able to detect the implicit setter where dst_name is set and we should replace 'value' by the field name 's'.
I'll have a look.
