### ISSUE TITLE
StreamController API docs still refer to onSubscriptionStateChange

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#30995]
Reported by Kyaw:

https://groups.google.com/a/dartlang.org/d/msg/misc/Mmg9Zzl1MTk/MTj7xT4MAQAJ

https://api.dartlang.org/stable/1.24.2/dart-async/StreamController-class.html

cc @floitschG (who started the thread in 2013)

**Comment by kevmoo** [comment]
@kwalrath – fixed in bleeding edge? https://api.dartlang.org/be/154136/dart-async/StreamController-class.html

**Comment by natebosch** [comment]
Yeah the docs no longer reference it.
