### ISSUE TITLE
New pattern for generics in DDC

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#31003]
We need to switch DDC's generic classes to be less polymorphic.

The goal will be to split out the ES6 class, which will be shared between all instances regardless of their generic type, and the TypeRep instance that will know about type arguments, as well as how to perform any operations we need (e.g. instantiate or test related types like `E` or `Iterable<E>` from `JSArray<E>`).

Storing the a complete TypeRep is needed so we can handle subclassing (e.g. `Derived<T> extends Base<List<T>>` can still find all the correct types needed by `Base<T>` with correctly substituted `T`), and also have a single pointer on the instance.

(We could potentially store the typerep in the `constructor` property, as that slot is currently used for the type info by JS and DDC. However that would need performance testing to make sure it doesn't regress anything due to special treatment in engines.)

**Comment by jmesserly** [comment]
This is high priority because we need to do either completely before or completely after the kernel migration :)

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen 

... so I tried this out. Some observations:

V8 head is /way/ better than node 8.6.0 version for DDC code. Here's one example:
```
# node (older V8)
polymorphic-reads(RunTime): 353.8570417551309 us.
polymorphic-writes(RunTime): 353.2320734722713 us.
type-tests-and-allocations(RunTime): 425.3509145044662 us.
# d8 (V8 from earlier today)
polymorphic-reads(RunTime): 51.237382794486855 us.
polymorphic-writes(RunTime): 161.87778227438284 us.
type-tests-and-allocations(RunTime): 296.07698001480384 us.
```

When I manually edit the generics in this benchmark, it makes the last benchmark a tad slower, but it speeds up the reads benchmark:
```
polymorphic-reads(RunTime): 28.03908648656227 us
```
... presumably because reads are less polymorphic between different generic class instantiations. One easy hack to see that is to create a base class with the non-generic methods, and then extend it from the generic class.

I was also able to speed up the polymorphic-writes benchmark with this particular code:
```js
  add(t) {
    this.constructor[checkT](t);
    this[_t] = t;
  }
  // where checkT is defined on the TypeRep instance as:
    this[checkT] = (obj) => T._check(obj);
```

Seems promising, although the biggest boost is from V8 in this benchmark.

**Comment by jmesserly** [comment]
I'm also cleaning up mixins in this change, which should see some improvements:

- mixin classes are defined in the output (helps with debugging, maybe perf)
- unroll mixins so each mixin class is a single composition of a base class and a mixin (should speed up construction a lot)
- constructors are emitted based on what the mixin actually needs, rather than via reflection and varargs (also speeds up construction)

**Comment by jmesserly** [comment]
Related bug: https://github.com/dart-lang/sdk/issues/31050

**Comment by vsmenon** [comment]
Bumping to P2.

**Comment by jmesserly** [comment]
we still want to do this, but it needs to wait for the CFE/Kernel switch to finish so we aren't fixing it in two compilers :) marking this blocked

**Comment by Markzipan** [comment]
Fixed by: https://github.com/dart-lang/sdk/commit/e7658520bb4a88c95416ebe83abe59e329335bc6
