### ISSUE TITLE
Error in dartdoc blocking Dart roll in Flutter

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#31008]
dartdoc:stderr: Generation failed: Unknown type GenericFunctionTypeElementImpl
https://travis-ci.org/flutter/flutter/jobs/283373111

@jcollins-g @aam

**Comment by rmacnak-google** [comment]
This type seems to come from the analyzer.
@bwilkerson @scheglov

**Comment by aam** [comment]
I found that upgrading to dartdoc to 0.13.0+3 worked in the past: https://github.com/flutter/flutter/commit/f6fe8dc7e3e961c067432e74f8a5fc089d7559b7#diff-a1ec403951c0ee8a36a3b4d2bc1fa797

**Comment by bwilkerson** [comment]
@jcollins-g

**Comment by jcollins-g** [comment]
Yes, you need >=0.13.0+3.

**Comment by jcollins-g** [comment]
The longer version is that 0.13.0+3 eliminates that fatal error, but in order to generate docs somewhat correctly you also need a release with dart-lang/dartdoc#1506 and dart-lang/dartdoc#1509.  I'll be releasing a version with that soon, hopefully tomorrow.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/dartdoc#1510
