### ISSUE TITLE
Gerrit doesn't check for CLAs

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31018]
On github every PR had an automatic check for CLA. The same thing should happen on Gerrit, so that we can more easily accept external patches through Gerrit.

**Comment by athomas** [comment]
Created b/69162736.

**Comment by athomas** [comment]
Gerrit should now require a signed CLA when uploading. The CQ should also reject patches without a signed CLA. I will do some testing and then close this issue.
