### ISSUE TITLE
Add int.to method to get a range

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#31016]
```dart
class int {
  Iterable<int> to(int value) sync* {
    for (int i = this; i <= value; i++) yield i;
  }
}
```

**Comment by anders-sandholm** [comment]
@floitschG

**Comment by lrhn** [comment]
This has been requested before, and one usability cinch is that it's very unclear whether [value] itself is included in the range. This implementation includes it, other requests expects it not to.

The existing way to do it is `new Iterable<int>.generate(value)`, which is obviously longer.

**Comment by a14n** [comment]
From a readability point of view the following 2 first options seem to be the best:

* `5.to(10)`
* `int.range(5, 10)`
* `new Iterable<int>.generate(6, (i) => i + 5)`
* `new Iterable<int>.generate(11).skip(5)`

Is it enoughly used to become an `int` method, that's the question.

**Comment by floitschG** [comment]
Your comment illustrates the problem with `to`: the expectations for the second argument of `to` vary wildly.
You seem to assume that it is included (otherwise your examples don't match up).

However, in most cases, the `to` is *not* included: `list.sublist`, `list.getRange`, ...

**Comment by passsy** [comment]
This can now be solved with extensions. I.e. [dartx](https://pub.dev/packages/dartx#rangeto) has a `int.rangeTo(int)` method.

```dart
// upwards with default step size 1
for (var i in 1.rangeTo(5)) {
  print(i); // 1, 2, 3, 4, 5
}
// downwards with custom step
for (var i in 10.rangeTo(2).step(2)) {
  print(i); // 10, 8, 6, 4, 2
}
```

**Comment by lrhn** [comment]
Not planned as a method on `int`.

If you want it anyway, you can use this extension:
```dart
extension IntRange on int {
  /// An iterable starting at this value and ending just before [end].
  /// 
  /// Iterates from `this` to [end] in steps of [step].
  /// Starts at `this`, and adds multiples of [step] until reaching or passing [end].
  /// The [end] must not be before the start unless [step] is negative.
  /// If [end] is equal to the start, the iterable is empty.
  ///
  /// The [step] must not be zero.
  Iterable<int> to(int end, {int step = 1}) {
    if ((end < this) != (step < 0)) {
      throw ArgumentError.value(end, "end", "Must be greater than start unless step is negative");
   }
   if (step == 0) throw ArgumentError.value(step ,"step", "Must not be zero");
   if (step > 0) {
     return () sync* {
       for (var i = this; i < end; i += step) yield i;   
     }();
  } else {
    return () sync* {
       for (var i = this; i > end; i += step) yield i;
    }();
  }
}
```
