### ISSUE TITLE
Weird analysis info: uses_dynamic_as_bottom

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#31010]
I'm running the analysis server at HEAD.

Here's my code:
```dart
typedef void Announcer(int);

class Thing {
  final Announcer _field;

  Thing(this._field);

  @override
  String toString() => _field.toString();
}

void announce(int value) {
  print('Value is $value!');
}

main(List<String> args) {
  new Thing(announce);
}
```

The analysis service is not happy:
```
  info • A function of type '(int) → void' can't be assigned to a variable of type '(dynamic) → void' at lib/main.dart:17:13 • (uses_dynamic_as_bottom)
```

The error goes away if I don't specify `strong-mode: true` in my options file.

Not sure if I'm holding it wrong here...

**Comment by matanlurey** [comment]
You're accidentally not specifying type information - in this case `Announcer` is typed a function that takes a parameter named `int`.

I believe this issue has been raised to the language team - but for the time being try `typedef void Announcer(int x)`.

**Comment by pylaligand** [comment]
That makes good sense, thanks for the explanation!
