### ISSUE TITLE
Future.forEach() doesn't play nice with --no-implicit-dynamic

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#31012]
If I analyze the following code with `--no-implicit-dynamic`:

```dart
import 'dart:async';

Future main() async {
  var list = <int>[1, 2, 3];
  await Future.forEach(list, (i) => null);
}
```

I get this error:

```
  error • Missing parameter type for 'i' at test.dart:5:31 • strong_mode_implicit_dynamic_parameter
```

This seems bogus; `Future.forEach()` has generic types:

```dart
Future forEach<T>(Iterable<T> elements, FutureOr action(T element))'
```

and I'm passing in a fully-typed list, so I'd expect it to infer that the function parameter was an `int`.

cc @leafpetersen @jmesserly

**Comment by jmesserly** [comment]
`i` in `(i) => null` is inferred as `dynamic`. Dart 2's inference is not able to take information from earlier arguments and apply them to later ones. This is equivalent to the `Iterable.fold` case, essentially. So, this is currently as designed, by I hope it changes in the future. Merging this into https://github.com/dart-lang/sdk/issues/25490
