### ISSUE TITLE
Add 'reset' method to IncrementalKernelGenerator in addition to accept/reject

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31021]
Please consider adding `reset` method to `IncrementalKernelGenerator` so that client can abandon its accepted state and receive full kernel program on next invocation of `computeDelta`.

This is needed to support 'restart' mode of Flutter tools operation where current VM state is abandoned and Dart program is started from scratch - from complete kernel program.

Thanks!

cc @a-siva

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/11962

**Comment by aam** [comment]
Thank you @scheglov !
