### ISSUE TITLE
GamepadList needs to be polyfilled for DDC

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#31029]
lib_2/html/gamepad_test generates RuntimeError.  Test is marked as such in the status.  After talking with @vsmenon  I have a fix for the DDC that I'll create to fix the problem.

**Comment by robertmuth** [comment]
This seems to mostly work but I cannot call .length on the GamepadList object 
nor can I use indexing, e.g.:


var pads = HTML.window.navigator.getGamepads();

pads.length => exception
pads[0] = > exception

**Comment by terrylucas** [comment]
Have a fix will submit soon.

**Comment by terrylucas** [comment]
See CL https://dart-review.googlesource.com/#/c/sdk/+/49740
