### ISSUE TITLE
Dartdoc does not narrow parameter types in descendants

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#31020]
Lets consider class [dart:io:Socket](https://api.dartlang.org/stable/1.24.2/dart-io/Socket-class.html) as an example. Its description reads:

> abstract class Socket
>Implements Stream&lt;List&lt;int&gt;&gt;, IOSink

Lets look at the methods and properties of the class Socket
On the front page:

> [first](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/first.html) → Future&lt;List&lt;int&gt;&gt;
> Returns the first element of the stream.
> read-only, inherited

Following the link:

> Future&lt;T&gt; first
> Returns the first element of the stream.
> 
> Stops listening to the stream after the first element has been received.

Please, note that &lt;List&lt;int&gt;&gt; is now replaced by T, which is confusing.
The same situation is observed for property `last`.

For methods situation is a bit different. On the front page:

> [distinct](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/distinct.html)([bool equals(T previous, T next) ]) → Stream&lt;List&lt;int&gt;&gt;
> Skips data events if they are equal to the previous data event.
> inherited

Following the link:
> Stream&lt;T&gt; distinct([bool equals(T previous, T next ) ])
> Skips data events if they are equal to the previous data event.

Please, notice that parameter type T is replaced wih actual type sometimes.

> pipe(StreamConsumer&lt;List&lt;int&gt;&gt; streamConsumer) → Future
> Pipe the events of this stream into streamConsumer.
> inherited

**Comment by anders-sandholm** [comment]
@alsemenov, thanks for filing the issue. 
Dartdoc has it's own issue tracker at https://github.com/dart-lang/dartdoc/issues. 
I'll move the issue over there.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/dartdoc#1512
