### ISSUE TITLE
Command "add final field formal parameters" added all not initialized fields to constructor

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#31026]
Raised by @Cododoc [against Dart Code](https://github.com/Dart-Code/Dart-Code/issues/431#issuecomment-334743118), but this functionality is supplied by the analysis server.

---

Example:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
}
```

Step 1 - Create constructor for final fields:
Set cursor to the _idGenerator line. Press Ctr+. and select "Create constructor for final fields". You get:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;

  MyTestClass(this._idGenerator);
}
```

Step 2 - Add new final field.
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
  final IdGenerator _idGenerator2; // <-- new final field

  MyTestClass(this._idGenerator);
}
```

Step 3 - add final field formal parameters.
Set cursor on constructor line. Press Ctrl+. and select "add final field formal parameters". You get:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
  final IdGenerator _idGenerator2; // <-- new final field

  MyTestClass(this._idGenerator, this.id, this._idGenerator2);
}
```
## Problem
**this.id** was added, but should not. It is not final field.

As workaround you can set null to id. Then command "add final field formal parameters" will work fine.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/12100
