### ISSUE TITLE
SqlTransaction probably needs a polyfill for DDC sdk

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#31036]
SqlTransaction returns as NativeJavaScriptObject

**Comment by terrylucas** [comment]
Need to update DDC SDK to polyfill this.

**Comment by jakobr-google** [comment]
Same error as #30947 and #31017 (NativeJavaScriptObject instead of the expected type), so they probably need the same kind of magic.

**Comment by terrylucas** [comment]
Thanks its on my list of all the polyfills to add.  I might do this sooner
rather than later since I have 4-5 to do now.

Terry.

**Comment by terrylucas** [comment]
The below code block "Simple test" will fail, on this line:

`    completer.complete(transaction);
`

with the runtime error:

_Type 'NativeJavaScriptObject' is not a subtype of type 'FutureOr<SqlTransaction>' in strong mode_

After talking with jacobr/@vsmenon the problem is there are classes of polyfill not attached to the window object that will require JS to Dart mapping.  For Example SQLTransaction (JS class) maps to SqlTransaction (Dart) class.  But would need to be mapped on loading of dart:web_sql or some other lazy type mechanism.

When fixed assign back to me to look at other classes to add to this list.

**Simple test:**
```
import 'dart:async';
import 'dart:html';
import 'dart:web_sql';

Future<SqlTransaction> transaction(SqlDatabase db) {
  final completer = new Completer<SqlTransaction>.sync();
  db.transaction((SqlTransaction transaction) {
    completer.complete(transaction);
  }, (SqlError error) {
    completer.completeError(error);
  });

  return completer.future;
}

main() {
  final db = window.openDatabase('test_db', '1.0', 'test_db', 1024 * 1024);
  var tx;
  return transaction(db).then((transaction) {
    tx = transaction;
  });
}
```

**Comment by terrylucas** [comment]
Also,
```
FileSystem fs;

getFileSystem() {
  return window.requestFileSystem(100).then((FileSystem fileSystem) {
    fs = fileSystem;
  });
}
```
causes:
_Uncaught Type 'NativeJavaScriptObject' is not a subtype of type 'FutureOr<FileSystem>' in strong mode_

Once these are fixed other will I'm sure show up too.

**Comment by terrylucas** [comment]
Fixed see CL https://dart-review.googlesource.com/c/sdk/+/31800
