### ISSUE TITLE
`isInSdk` returns false for some `dart:` libraries.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#31045]
It looks like the check today sees if the [`name` starts with `dart.`](https://github.com/dart-lang/sdk/blob/9cdfb2ffc45cd612174da3575cc38f86c9f3e0ac/pkg/analyzer/lib/src/dart/element/element.dart#L6489). This misses some cases such as [`dart:_js_helper`](https://github.com/dart-lang/sdk/blob/db8b20107b45a7678811f2c057ace223e821585b/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L5) which have a specified library name which doesn't start with `dart.`.

Instead it could possibly check if the `source.uri.scheme == 'dart'`?

**Comment by natebosch** [comment]
cc @vsmenon, @jmesserly 

The `isInSdk`getter can also return `true` for stuff _not_ in the SDK. For example: `package:collection/equality.dart`

https://github.com/dart-lang/collection/blob/830c420f0cd0a8fa3330e59d9d738ee6ee2e1a05/lib/equality.dart#L7

It looks like `source.isInSystemLibrary` does the scheme check, so we'll switch to using that everywhere.

**Comment by jmesserly** [comment]
DDC used to be paranoid about using isInSystemLibrary, but it looks like some usage of isInSdk has crept into it (sometimes guarded by a URI check, which is safe, but not always).

**Comment by jmesserly** [comment]
DDC patch removing remaining usage of isInSdk: https://dart-review.googlesource.com/c/sdk/+/42463

**Comment by bwilkerson** [comment]
I believe that this change (https://dart-review.googlesource.com/c/sdk/+/48760) should fix the problem. Let me know if that's not the case.
