### ISSUE TITLE
Dart roll into Flutter is blocked due to asserts referencing 'this'

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31047]
https://travis-ci.org/flutter/flutter/jobs/285811359 are the failures, and https://github.com/dart-lang/sdk/commit/98a253186c651e945f56f52b8e6b29f928b5e01c seems to be the culprit.

**Comment by aam** [comment]
@a-siva

**Comment by crelier** [comment]
There is no bug in the VM. There was a bug that I fixed. The problem is on the flutter side. They need to change their code.
