### ISSUE TITLE
Console noise on successful //runtime/vm:compile_strong_platform step

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#31044]
On a successful build of the create_sdk target, there is a message printed to the console by the target //runtime/vm:compile_strong_platform.

```
[565/714] ACTION //runtime/vm:compile_strong_platform(//build/toolchain/linux:clang_x64)
Note: strong mode support is preliminary and may not work.
```

Please remember that a successful GN build step should produce no console output.

@peter-ahe-google @sigmundch

**Comment by sigmundch** [comment]
Thanks Zach, I will fix this shortly.

https://dart-review.googlesource.com/c/sdk/+/12322
