### ISSUE TITLE
DDC does not run all field initializers

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#31058]
Context: language_2/final_field_initialization_order_test: RuntimeError

Summary:

...
// no errors or warnings
class MixedFields extends OneField {
  final b = new Mark('b');
  var c = new Mark('c');
  final d = new Mark('d');
  MixedFields();
  MixedFields.c0() : c = new Mark('cc');
  MixedFields.c1()
      : c = new Mark('cc'),
        super();
}

...
  Expect.equals('b.c.d.cc.a.', run(() => new MixedFields.c0())); // RuntimeError!!!!!
  Expect.equals('b.c.d.cc.a.', run(() => new MixedFields.c1())); // totally fine
...

the c0() line does not work, a RuntimeError occurs
the c1() line is fine.

**Comment by jmesserly** [comment]
fixing this along with https://github.com/dart-lang/sdk/issues/27809

(DDC+Kernel already has the fix, now backporting it to DDC+Analyzer)

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/37866
