### ISSUE TITLE
debianpackage-linux-be has no /usr/bin/dart

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31055]
As shown in [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdebianpackage-linux-be%2F3301%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fdebianpackage-linux-be%2F3301%2F%2B%2F%2A%2A%2Fstderr), the buildbot `debianpackage-linux-be` is failing (and it has been failing in all builds 3278-3301, at least). It seems to be during the 'Sanity check installation' step, due to `could not find /usr/bin/dart`. Here is the full log text for that step:
```
Dart already installed, removing
Running: sudo dpkg -r dart
(Reading database ... 21854 files and directories currently installed.)
Removing dart (2.0.0-edge.5b01aaa4e5cf04ad0bf80a08e4cb40314ab7eae2-1) ...
Running: sudo dpkg -i /mnt/data/b/build/slave/debianpackage-linux-be/build/sdk/out/src_and_installation/dart_2.0.0-edge.bb1b39deaf2a024f0a5215105000c40ac68e0ee5-1_amd64.deb
Selecting previously unselected package dart.
(Reading database ... 20550 files and directories currently installed.)
Preparing to unpack .../dart_2.0.0-edge.bb1b39deaf2a024f0a5215105000c40ac68e0ee5-1_amd64.deb ...
Unpacking dart (2.0.0-edge.bb1b39deaf2a024f0a5215105000c40ac68e0ee5-1) ...
Setting up dart (2.0.0-edge.bb1b39deaf2a024f0a5215105000c40ac68e0ee5-1) ...
Assumed installed, but could not find /usr/bin/dart
```
Maybe that `.deb` package is incomplete? I've marked this issue with `area-infrastructure` because the symptoms involve setup, no actual tests involved.

**Comment by athomas** [comment]
Closing, the builder is green.
