### ISSUE TITLE
language_2/f_bounded_quantification5_test fails on dart2js minified checked without kernel

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#31053]
The new migrated test language_2/f_bounded_quantification5_test
fails on all dart2js configurations with --minified --checked without --dart2js-with-kernel.
This occurs on brower and non-browser runtimes.
The status is marked in language_2/language_2_dart2js.status.

**Comment by whesse** [comment]
This may not be important, because language_2 tests will eventually all be run with dart2js-with-kernel only.

**Comment by eernstg** [comment]
I believe this issue has been subsumed by #31054 which addresses the underlying problem in `language_2/f_bounded_quantification5_test.dart` and 10 other tests, so I'll close this issue.
