### ISSUE TITLE
Have coredump archiving support across all our buildbot

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31065]
We have had support for coredumps on subsets of builders for some time. Though there remain a number of issues:

  * modifications to the rootsfs are not persistent on our `-c3` GCE slaves, which mean after a forceful reboot (which happens randomly) they loose their state
  * similarly windows registry changes necessary to make it work get overriden by the puppet daemon running on the windows slaves, so that support is not guaranteed to work either
  * there might be more builders we could enable the coredump support

Since I'm not familiar with the new swarming setup (neither with the CQ setup) and I also don't have cycles to work more on this, it would be great if our new eng-prod team could take this up again.

The code for performing the archiving sits in [tools/utils.py](https://github.com/dart-lang/sdk/blob/master/tools/utils.py#L1026) and will be enabled in `tools/test.py` if the `--copy-coredumps` is present. In addition to the archiving support mentioned, there are changes required to system images:
  * on linux: see [crbug.com/686652](https://bugs.chromium.org/p/chromium/issues/detail?id=686652) / [crbug.com/691980](https://bugs.chromium.org/p/chromium/issues/detail?id=691980) (still pending)
  * on windows: see [crbug.com/691971](https://bugs.chromium.org/p/chromium/issues/detail?id=691971) (still pending)

(Due to auto-restarts of -c3 slaves (which causes them to loose rootfs modifications) the core dumping support was disabled in 3e354bcc58742b5acd22a9e7168f055aff2b6d6e and 336478d7d9db88bfa874d4a718b6b0e221af4768 ).

So we should:
  * [ ] Get all necessary rootfs modifications into puppet config / system image on linux and windows with help from CIT
  * [ ] Enable `--copy-coredumps` on all builders where it makes sense (i.e. in recipes where it's still missing)
  * [x] Re-enable the support (i.e. revert 3e354bcc58742b5acd22a9e7168f055aff2b6d6e and 336478d7d9db88bfa874d4a718b6b0e221af4768)

I'll merge the other remaining issues into this one.

@athomas / @whesse  Do you think you could take this over?

**Comment by athomas** [comment]
It's re-enabled on Linux for test matrix-based builders now.

**Comment by athomas** [comment]
Some issues aren't resolved, yet:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8933016726891808688/+/steps/vm_tests/0/stdout

**Comment by athomas** [comment]
Since 
5ce132a (tagged with #34746 by accident) this is working again on Linux. For shards we're copying the dump to isolated out instead.

**Comment by athomas** [comment]
AFAIK the issues were addressed by the work done by @mraleph and me. Please re-open if I'm wrong.
