### ISSUE TITLE
Unable to iterate enum fields using dart:mirrors with dartdevc

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#31079]
Using `2.0.0-dev.3.0`, I was unable to iterate enum class fields using `dart:mirrors` when using `pub serve --web-compiler dartdevc` even though dart2js seems to be working fine. The code looks like this:
```dart
for (final d in classMirror.declarations.values) {
  if (d is VariableMirror && d.isStatic && d.simpleName != #values) {
   final name = MirrorSystem.getName(d.simpleName);
    if (name == input) {
      return classMirror.getField(d.simpleName).reflectee;
    }
  }
}
```

Is this an unimplemented feature? (I noticed that `ClassMirror.isEnum` is unavailable). For me this is quite critical as I'm trying to implement a zero marginal cost layer between the frontend application and the database using reflection.

**Comment by matanlurey** [comment]
It's not clear in the current version, but `dart:mirrors` is not really supported in `dartdevc`.

https://github.com/dart-lang/sdk/issues/30538 says:

> In Dart 2.0, our web products — dart2js and dartdevc — will no longer support dart:mirrors and dart:isolate. Support for those has been limited and problematic in many ways for years, so the simplest solution that gives us the most room for future improvement is to not support them at all.

@bergwerf: > For me this is quite critical as I'm trying to implement a zero marginal cost layer between the frontend application and the database using reflection.

Then you won't want to use reflection, even in `dart2js` there is no "zero marginal cost" option once you import and use `dart:mirrors`. DDC only implements a small unpublished subset of `dart:mirrors` as we are migrating some mirrors-only code to use code generation. Once that is done, the compiler for both dart2js and dartdevc will throw when it sees mirrors at all (similar to Flutter).

**Comment by bergwerf** [comment]
I mean zero cost in terms of programming/maintenance. I view the
performance/codesize problem of mirrors as premature optimization (in
particular for my use case).
Do you recommend any tools for code generation?

**Comment by matanlurey** [comment]
I'd highly recommend

* https://pub.dartlang.org/packages/build
* https://pub.dartlang.org/packages/build_runner
* https://pub.dartlang.org/packages/source_gen

All of them are in the same ecosystem of packages.

Decent example of a package: https://github.com/dart-lang/json_serializable/tree/master/json_serializable
