### ISSUE TITLE
Please clarify HeaderValue.parse(String valueSeparator: ...) argument

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31080]
Please clarify how `valueSeparator` argument of [HeaderValue.parse()](https://api.dartlang.org/stable/1.24.2/dart-io/HeaderValue/parse.html) method should work? I'm unable to figure out how it works/should work from its current behaviour. Please show an example

**Comment by sgrekhov** [comment]
Any update on this? @sortie you changed HeaderValue behavior by thic change https://dart-review.googlesource.com/c/sdk/+/136620

Now the test below works. Is this correct?

```dart
  String toParse = "value1, param1=val1, param2=val2";
  HeaderValue parsed = HeaderValue.parse(toParse, valueSeparator: ",");
  Expect.equals("value1", parsed.value);
  Expect.mapEquals({}, parsed.parameters);

  toParse = "value1,param1=val1,param2=val2";
  parsed = HeaderValue.parse(toParse);
  Expect.equals("value1,param1=val1,param2=val2", parsed.value);
  Expect.mapEquals({}, parsed.parameters);

  toParse = "value1; param1=val1; param2=val2";
  parsed = HeaderValue.parse(toParse, valueSeparator: ";");
  Expect.equals("value1", parsed.value);
  Expect.mapEquals({"param1": "val1"}, parsed.parameters);

```

**Comment by sortie** [comment]
Case 1 and 2 are the intended behavior

Case 3 is an interesting corner case that I hadn't thought of where valueSeparator and parameterSeparator have the same value. Arguably that should have parsed as the empty parameters. I'll make a change to the Dart SDK to parse it as such, since the current behavior seems inconsistent and surprising.

**Comment by sortie** [comment]
I implemented a fix to make case 3 consistent in: https://dart-review.googlesource.com/c/sdk/+/140869

**Comment by sgrekhov** [comment]
@sortie thank you. I'll change co19 tests accordingly as soon as CL is landed

**Comment by sortie** [comment]
Done

**Comment by sgrekhov** [comment]
co19 tests updated
