### ISSUE TITLE
Stack trace for DDC doesn't match VM's

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#31089]
The stack trace for DDC is JS looking compared to the simplified VM e.g.,

```
#0      new SomeClass (file:///usr/local/google/home/terry/dart-sdk-git/sdk/tests/language_2/stacktrace_demangle_ctors_test.dart:15:5)
#1      main (file:///usr/local/google/home/terry/dart-sdk-git/sdk/tests/language_2/stacktrace_demangle_ctors_test.dart:31:9)
#2      _startIsolate.<anonymous closure> (dart:isolate:1252:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate:1142:12)
```
The DDC trace is:

`#0     new stacktrace_demangle_ctors_test.SomeClass.new #0`

With source maps should be more like "new SomeClass"

**Comment by jmesserly** [comment]
this is working if you have source maps enabled. They should be there in Chrome. On nodejs they can be enabled with the source-map-support package. Using Dart's package:stack_trace will also format them in a Dart way.

if there's another scenario we're missing, let us know.
