### ISSUE TITLE
Can't find ')' to match '('.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31098]
{
          "isFatal": false,
          "message": "Captured exception",
          "stackTrace": "Can't find ')' to match '('.\n#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:74)\n#1      Parser.isFunctionExpression (package:analyzer/src/generated/parser.dart:515)\n#2      Parser.isFunctionDeclaration (package:analyzer/src/generated/parser.dart:471)\n#3      Parser.parseNonLabeledStatement (package:analyzer/src/generated/parser.dart:4248)\n#4      Parser.parseStatement2 (package:analyzer/src/generated/parser.dart:4843)\n#5      Parser.parseBlock (package:analyzer/src/generated/parser.dart:997)\n#6      Parser.parseFunctionBody (package:analyzer/src/generated/parser.dart:3268)\n#7      Parser.parseFunctionDeclaration (package:analyzer/src/generated/parser.dart:3347)\n#8      Parser.parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:2126)\n#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:1998)\n#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1890)\n#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:571)\n#12     FileState.parse.\u003canonymous closure\u003e (package:analyzer/src/dart/analysis/file_state.dart:387)\n#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)\n#14     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:386)\n#15     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:429)\n#16     FileTracker.verifyApiSignature.\u003canonymous closure\u003e (package:analyzer/src/dart/analysis/file_tracker.dart:220)\n#17     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)\n#18     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)\n#19     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)\n#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:834)\n\u003casynchronous suspension\u003e\n#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1717)\n\u003casynchronous suspension\u003e\n#22     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1660)\n#23     new AnalysisServer (package:analysis_server/src/analysis_server.dart:378)\n#24     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)\n#25     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)\n#26     Driver.start.\u003canonymous closure\u003e (package:analysis_server/src/server/driver.dart:430)\n#27     _rootRun (dart:async/zone.dart:1124)\n#28     _CustomZone.run (dart:async/zone.dart:1021)\n#29     runZoned (dart:async/zone.dart:1499)\n#30     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:470)\n#31     Driver.start (package:analysis_server/src/server/driver.dart:429)\n#32     main (file:///build/work/becb93f4369461770223f6bdd406acf7/google3/third_party/dart_lang/v2_0_0_dev_3_0/pkg/analysis_server/bin/server.dart:100)\n\u003casynchronous suspension\u003e\n#33     _startIsolate.\u003canonymous closure\u003e (dart:isolate-patch/isolate_patch.dart:263)\n#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)\n",
          "time": "2017-10-13T17:23:36.603Z"
        }

**Comment by peter-ahe-google** [comment]
JSON decoded the stacktrace:

```
Can't find ')' to match '('.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:74)
#1      Parser.isFunctionExpression (package:analyzer/src/generated/parser.dart:515)
#2      Parser.isFunctionDeclaration (package:analyzer/src/generated/parser.dart:471)
#3      Parser.parseNonLabeledStatement (package:analyzer/src/generated/parser.dart:4248)
#4      Parser.parseStatement2 (package:analyzer/src/generated/parser.dart:4843)
#5      Parser.parseBlock (package:analyzer/src/generated/parser.dart:997)
#6      Parser.parseFunctionBody (package:analyzer/src/generated/parser.dart:3268)
#7      Parser.parseFunctionDeclaration (package:analyzer/src/generated/parser.dart:3347)
#8      Parser.parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:2126)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:1998)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1890)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:571)
#12     FileState.parse.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:387)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#14     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:386)
#15     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:429)
#16     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:220)
#17     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#18     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#19     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:834)
<asynchronous suspension>
#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1717)
<asynchronous suspension>
#22     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1660)
#23     new AnalysisServer (package:analysis_server/src/analysis_server.dart:378)
#24     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#25     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:430)
#27     _rootRun (dart:async/zone.dart:1124)
#28     _CustomZone.run (dart:async/zone.dart:1021)
#29     runZoned (dart:async/zone.dart:1499)
#30     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:470)
#31     Driver.start (package:analysis_server/src/server/driver.dart:429)
#32     main (file:///build/work/becb93f4369461770223f6bdd406acf7/google3/third_party/dart_lang/v2_0_0_dev_3_0/pkg/analysis_server/bin/server.dart:100)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by danrubel** [comment]
I tracked down this stack trace, and the error is in code from sometime before commit e7f26dc76935178f944b92cdd70a078e9123712b on Wed Oct 4 18:34:49 2017 +0000

It appears that an ErrorToken is escaping the analyzer's scanner proxy and causing an error in the analyzer's parser. The proxy translates and removes all ErrorTokens at the beginning of the token stream, so my supposition is that under some unknown condition an ErrorToken is not being moved to the head of the stream by the fasta scanner recovery code. I don't yet have a way to reproduce the problem and have not found the problem through manual code inspection.

**Comment by danrubel** [comment]
I worked with @lukechurch to try to recreate this problem by running a test harness over lots of code samples with no luck. Either its a borked installation or my supposition on how it's happening is incorrect. 

Please let me know if you see this again and hopefully we can reach out to the user for more details.

**Comment by scheglov** [comment]
I will add a way for Analysis Server to catch exceptions during parsing, and store the exception with the corresponding content. Just as we do for analysis, it helped to find some of the tricky errors. Not all of course, but better than nothing :-)

https://dart-review.googlesource.com/c/sdk/+/17561

**Comment by danrubel** [comment]
Good idea. Thanks!

**Comment by danrubel** [comment]
Closing as we have switched to the fasta parser.
