### ISSUE TITLE
Typo in description of dart:async:Stream.last

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#31095]
The description of dart:async:Stream.last reads:

> Future&lt;T&gt; last
> Returns the last element of the stream.
> 
> **If an error event occurs before the first data event, the resulting future is completed with that error.**
> 
> If this stream is empty (a done event occurs before the first data event), the resulting future completes with a StateError.

I believe the highlighted sentence should be:

> If an error event occurs before the **last** data event, the resulting future is completed with that error.

**Comment by alsemenov** [comment]
Actually, even if the error is the last event in the stream, the returned future is completed with that error.
Here is the sample code, demonstrating this:
```dart
import "dart:async";

main() {
  Stream s = new Stream.fromFutures([new Future.value(1), new Future.error("error")]);
  s.last.then(print, onError:(e) => print(e));
}
```
So I think the highlighed statement should be like this:
> If an error event occurs in the stream, the resulting future is completed with the first error, that apears in the stream.

**Comment by natebosch** [comment]
Doc now reads "If this stream emits an error event, the returned future is completed with that error and processing stops." which I think addresses the concern.
