### ISSUE TITLE
Have a way of testing source map generation

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#31101]
Do we have a good way of testing that our source maps produce useful output for the browsers, or finding regressions when we change it or when the browsers do? We've had issues (e.g. #29663 ) where Chrome either refuses to parse our source maps or doesn't do the right thing with them in edge cases like breakpoints on single-line functions.

It seems like we'd have to have a way of scripting the devtools or some other level of verifying the browser's interpretation in different circumstances. This seems difficult, but at least some level of smoke test would be good.

**Comment by jmesserly** [comment]
this has been implemented (there are source map testing suites for DDC/DDK)
