### ISSUE TITLE
Tests for recovery for class fail in unchecked mode

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31100]
Run this without `--checked` flag.

`dart pkg/analyzer/test/src/fasta/recovery/partial_code/test_all.dart`

It fails because tests are marked as failing, but actually pass.

See `assert(className == name.name);` in `AstBuilder`.

**Comment by jensjoha** [comment]
Cannot reproduce. @scheglov can we close this issue?

**Comment by scheglov** [comment]
I cannot reproduce it either now.
So yes, we can close it.
