### ISSUE TITLE
Provide pinvoke/golang-like interop with C

### ISSUE THREAD

**Issue by Meai1** [dart-lang/sdk#31112]
**Goal:**

C
```
// gcc -shared -fPIC library.c -o locationOnDisk.so
int my_c_function(char* bla){
      printf(bla); 
      fflush(0);
}

```

Dart
```
@CLibrary("locationOnDisk.so")
external int my_c_function(String bla);

void main() {
   my_c_function("HI"); // works!
}

```

When the dartvm starts up / encounters an external function it should look for a matching function that it can dynamically load from a .so on disk. Ideally the native .so should not need to include any dart specific headers or libraries, it should be pure C.
Please advise on whether this is wanted and how it should be implemented.

**Comment by rmacnak-google** [comment]
`dart:ffi` provides interop with C.
