### ISSUE TITLE
Unable to bind InternetAddress.LOOPBACK_IP_V6

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31111]
I'm creating HttpServer instance using `bind()` method. This works well for `String` address and for `InternetAddress.LOOPBACK_IP_V4` adress, but not for `InternetAddress.LOOPBACK_IP_V6`.

```dart
import "dart:io";
main() async {
  HttpServer server = await HttpServer.bind(InternetAddress.LOOPBACK_IP_V6, 0);
}
```
This produces 
`SocketException: Failed to create server socket (OS Error: Failed to start accept), address = ::1, port = 0`

Tested on Dart VM version: 2.0.0-dev.3.0 (Wed Oct 04 03:08:03 2017) on "windows_x64"

**Comment by srawlins** [comment]
This example works for me. I'm on MacOS. Is this still a problem in recent Dart versions? Maybe a Windows bug?

```
$ cat 31111.dart 
import "dart:io";
main() async {
  HttpServer server = await HttpServer.bind(InternetAddress.LOOPBACK_IP_V6, 0);
  print('done');
  server.close();
}
$ dart 31111.dart 
done
srawlins-macbookair:code srawlins$ dart --version
Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"
```

**Comment by sgrekhov** [comment]
Works for me as well. Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "windows_x64"
Seems it was fixed.

**Comment by srawlins** [comment]
Woohoo good news!
