### ISSUE TITLE
Dart Analyzer Error while manually refactoring a child widget to a variable

### ISSUE THREAD

**Issue by sarah-fernandez** [dart-lang/sdk#31120]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4392136`
- `1.25.0-dev.11.0`
- `AI-171.4392136, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-66-generic unknown, screens 1366x768`

# Exception

Please append the contents of:
file:///tmp/report.txt

[report.txt](https://github.com/dart-lang/sdk/files/1389860/report.txt)

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Failed to handle completion domain request: {id: 565, method: completion.getSuggestions, params: {file: /home/sarah/IdeaProjects/horizontal_scaffold/lib/main.dart, offset: 5137}, clientRequestTime: 1508217380345}
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      _OpTypeAstVisitor.visitNamedExpression.<anonymous closure> (package:analyzer_plugin/src/utilities/completion/optype.dart:745)
#3      Object

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://dart-review.googlesource.com/11940. The fix should be included in the next dev release.
