### ISSUE TITLE
IKG can't it seems to produce kernel files with sources.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31139]
Incremental Kernel Generator doesn't seem to include source text into generated dill file even if `embedSourceText` is set to `true`.

**Comment by scheglov** [comment]
Is this a problem with the bleeding edge SDK?
I think it was fixed in https://dart-review.googlesource.com/c/sdk/+/4140

**Comment by aam** [comment]
Ah, apologies. Yes, source code is embedded.
My confusion though was that size of kernel file didn't change when I flipped `embedSourceText` from `false` to `true`. I assumed that source code is never embedded, but now it looks like it is always embedded. Is it as expected(that you can't produce incremental kernel file without source code)?
Batch compile treats `embedSourceText` correctly it seems.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/15240

Just curious - is there a use case when we don't want sources?

**Comment by aam** [comment]
> Just curious - is there a use case when we don't want sources?

This looks unlikely at this point. Previously there were thoughts to handle(transfer) sources independently from kernel file, but that sounds unnecessary complicated.

Also, potentially we want to always skip source code when building core `platform.dill` kernel file.
