### ISSUE TITLE
toString generated for enum classes contains unresolved method invocation without an interfaceTarget

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31134]
```dart
enum Foo {
  A, B, C
}
```

results in 

```
   method toString() → core::String
      return const <core::int, core::String>{0: "Foo.A", 1: "Foo.B", 2: "Foo.C"}.[](this.{=inf::Foo::index});
 ```

Notice that invocation of `[]` lacks appropriate interface target, even though receiver type is known.

**Comment by kmillikin** [comment]
We will change our encoding of enums because neither dart2js nor the VM are fully satisfied with it.  Let's discuss it next week.

**Comment by rakudrama** [comment]
I opened https://github.com/dart-lang/sdk/issues/30764 but perhaps we can have the front-end generate one form that is acceptable to VM / DDC / dart2js.

What would be best for dart2js tree shaking is for the enum values to hold the toString() strings and the toString() method to be shared.

```dart
corelib:
class _Enum {
  final int index;
  final String _name;
  const _Enum(this.index, this._name);
  String toString() => _name;
}

class Foo extends corelib._Enum {
  const Foo(int index, String _name) : super(index, _name);  // constructor somehow hidden.
  static const A = const Foo(0, 'Foo.A');
  static const B = const Foo(1, 'Foo.B');
  static const C = const Foo(2, 'Foo.C');
  static const values = <Foo>[Foo.A, Foo.B, Foo.C];
}
```

@mraleph Is this acceptable or do you have other constraints?

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/16526
