### ISSUE TITLE
Enable strong mode tests for the FE

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31147]
We need to add end to end test coverage for running the FE & VM in strong mode

Some action items:

*  [x] add any necessary flags to test.py
*  [x] pass through the strong flag to the FE in the VM kernel-service
*  [x] create status file entries
*  [x] add the new configuration to the bot recipes (include also CQ)

**Comment by sigmundch** [comment]
/cc @aam @a-siva - could you help us with item 2 above? 

If you like, we can VC to coordinate some of the work we need for this.

**Comment by mraleph** [comment]
We still have not reached parity on non-strong mode version, do we really want to chase both at the same time?

**Comment by aam** [comment]
to answer @sigmundch question above - sure we can

**Comment by sigmundch** [comment]
@mraleph - we basically need to be able to have some testing of strong mode beyond the FE unit tests. The strong-mode check-insertion is getting more mature and it would be very valuable to test it with the language suite. 

Today we enabled the inference algorithm by default and throw away the data just so we get some coverage on the existing pipeline, but now that we need to do check-insertion, I feel we need to do something else.

I however don't see this as chasing both at the same time: I expect Peter and Aske will continue focused on reaching parity in the non-strong case, while Paul will be mainly pushing down on strong-mode DartkCrashes.

Another option could be to add a "-c dartk -r none" configuration (which I've been wanting to do independently) and only add support for "--strong" in that configuration for now.

Other ideas?

**Comment by a-siva** [comment]
I agree it is good to get some end to end testing started so that fundamental issues if any that come can be planned for. Having the --strong option kind of working would also enable us to run it through flutter gallery and other samples to see if the flutter code exposes different patterns.
It doesn't need to run in the buildbot as a waterfall configuration, would be sufficient initially if we could run the tests suite with the --strong option.

**Comment by mraleph** [comment]
I agree that we need testing. I just want to understand preconditions to flipping our default configuration to DFE.

@aam Did you start on wiring `--strong` through to the DFE isolate? If you did not yet, then I am gonna do it myself as I need this for testing my core library changes.

**Comment by aam** [comment]
@mraleph no, I haven't yet started, so sounds good.

**Comment by sigmundch** [comment]
Sent tiny CL changing test.py so it can pass through "--strong" to the VM in the `-c none` and `-c dartk` configurations: https://dart-review.googlesource.com/c/sdk/+/15820

**Comment by sigmundch** [comment]
Thanks Slava for plumbing the flag!

Unless someone else is working on this already, I'll be working on the remaining tasks (.status files and changing the bot recipes)

**Comment by sigmundch** [comment]
@mraleph - my plan was to initially add this on the bots only for the dartk/vm configuration, do you also want this for the dartkp/dart_precompiled configuration at this time?

**Comment by mraleph** [comment]
@sigmundch We certainly want this for dartkp as well, but I did not actually test if it works myself 

I have made dartk configuration run with `--strong` (previously everything was just failing to even reach main) with [this CL](https://dart-review.googlesource.com/c/sdk/+/15884).

Now we have the following for `lib_2` and `language_2`:

```
language_2 [02:23 | 100% | + 4422 | -  356]
lib_2      [01:25 | 100% | +  634 | -   56]
```

**Comment by sigmundch** [comment]
All set- landed support for this in the bots. I still have one more follow up CL to remove *_2 tests from the non-strong configurations and to add the strong-tests to the try bots, but we should be getting coverage as soon as the recipe changes get deployed to the bots.
