### ISSUE TITLE
In Flutter vmservice observatory code needs to be loaded from kernel file

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31145]
Currently vmservice observatory code is loaded from the sources embedded into flutter engine https://github.com/flutter/engine/blob/master/runtime/dart_init.cc#L197, parsed by VM. It needs to be loaded from kernel file instead.
Application bundle has platform.dill that contains dart:_vmservice, but service isolate initialization logic needs that kernel file sooner, before application bundle is made available and loaded into the engine. 
It sounds like it has to be built and embedded into the engine as part of the engine build.

@a-siva wdyt?

**Comment by a-siva** [comment]
We could embed the platform.dill file into the engine but this is going to significantly increase the engine binary size (4.2 MB). Current size of the stripped android_debug engine is 13.7 MB.
Another option might be to change the current implementation of Dart_Init to not implicitly start the service isolate as part of it but instead have the embedder code explicitly start the service isolate when it is ready and has all the necessary files required to boot an isolate.

**Comment by aam** [comment]
One interesting issue I found is with https://github.com/flutter/engine/blob/master/shell/common/diagnostic/diagnostic_server.cc#L64 which basically compiles and loads https://github.com/flutter/engine/blob/master/shell/common/diagnostic/diagnostic_server.dart from the source code.
Not sure why it done this way rather than put into vmservice_sky? @jason-simmons might know (based on https://github.com/flutter/engine/pull/2579)

**Comment by aam** [comment]
I have https://dart-review.googlesource.com/c/sdk/+/15920 out which includes diagnostic server into flutter patched sdk.

**Comment by aam** [comment]
Fix is in https://github.com/flutter/engine/commit/ec19da1c8098b321672a3770ec0b4e84bd0621e9
