### ISSUE TITLE
[Dart2JS] a serious bug that BoundClosure caches a wrong prototype target

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#31149]
It's hard to reproduce it in this simple example (this cannot reproduce the issue, but similar concept)
```
main () {
  var foo = new Foo();
  Function.apply(foo.emitAll, ['test foo']);
  var bar = new Bar();
  Function.apply(bar.emitSuper, ['test bar']);
}
class Foo extends EventEmitter {
  void emitAll(String event, [dynamic data]) {
    Function.apply(this.emit, [event, data]); 
  }
}
class Bar extends EventEmitter {
  void emit(String event, [dynamic data]) {
    print('error>> bar $event');
  }
  void emitSuper(String event, [dynamic data]) {
    // if we invoke Foo.emitAll before this emitSuper, then the BoundClosure 
    // will use "function (a25){return this._self.emit$1(a25);}"
    //  instead of "function () {return  f.apply(s(this), arguments);}"
    Function.apply(super.emit, [event, data]); 
  }
}
```
The above example that `Foo.emitAll()` uses `Function.apply(this.emit, ...)` (it should be "super.emit", because it didn't override it) to invoke the super.emit function and then the other class `Bar` uses the same way in `emitSuper()` by `Function.apply(super.emit)` to invoke its super function, but it overrides the same `emit()` function in its body. 
This usage will make dart2js to use a wrong `BoundClosure` in JS env. if we invoke "Foo.emitAll" before "Bar.emitSuper".

**Note:** to workaround this issue is to change the "Foo.emitAll" by using `this.emit(event, data);` instead of `Function.apply(this.emit, [event, data]);`.

After compiling to JS, it seems the issue happens in this code
```
$prototype[callName] = trampoline;
      for (t1 = functions.length, i = 1; i < t1; ++i) {
        stub = functions[i];
        stubCallName = stub.$callName;
        if (stubCallName != null) {
          t2 = isStatic ? stub : H.Closure_forwardCallTo(receiver, stub, isIntercepted);
          $prototype[stubCallName] = t2;
        }
      }
```
The "t2" will use "function (a25){return this._self.emit$1(a25);}" instead of "function () {return  f.apply(s(this), arguments);}" to a wrong BoundClosure for the above concept.

### Here is the whole test code attachment.
`Dart version: 1.24.2`
`OS env: Mac and Ubuntu`

The attached testing code work well on Dartium, but after compiling to js, it will fail to run if we invoke the code in different order.
[dart2jsBug.zip](https://github.com/dart-lang/sdk/files/1397535/dart2jsBug.zip)
It contains three project source code, "dart2jsBug", "socket_io", and "socket_io_client".
You can run the following steps to reproduce it.
1. run `pub get` under "dart2jsBug" project.
2. run `pub run test/server.dart` under "dart2jsBug" project to run a socket server project.
3. run `pub build --mode=debug test/` under "dart2jsBug" project to compile them to JS code.
4. run `open build/test/index.html` under "dart2jsBug" to open a chrome to run the testing code on JS env. (you should see the "Actual" wrong result)
5. open "main.dart" under "dart2jsBug/test" folder to comment out `socket.io.emitAll('test');` this line, and then do the step3~4 again and you should see the "Expected" result.

Note: the whole example work well on Dartium without Dart2JS.

#### Actual:
 ![screen shot 2017-10-19 at 3 20 38 pm](https://user-images.githubusercontent.com/201100/31760056-0bda2fba-b479-11e7-8a74-267b68234db4.png)

As you can see the "Console" didn't print anything on it, but the "Frames" data panel print so many messages "fromServer"...

#### Expected:
![screen shot 2017-10-19 at 3 21 54 pm](https://user-images.githubusercontent.com/201100/31760183-6fcca7b4-b479-11e7-8ba6-cc8c36c7e54d.png)

As you can see the "Console" will print a lot of messages as the same as the "Frames" data panel did.

**Comment by matanlurey** [comment]
Please re-open if the problem persists with the latest Dart2JS.
