### ISSUE TITLE
Kernel precompiled mode stacktrace positions

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#31150]
Currently we have some failures in kernel precompiled mode, e.g. "language_2/const_nested_test".
One can see how to execute it by running "python tools/test.py -m release -c dartkp -r dart_precompiled language_2/const_nested_test -v" which should also allow one to rerun the compiled code with something like "DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=.packages out/ReleaseX64/generated_compilations/dartkp/tests_language_2_const_nested_test/out.aotsnapshot".

This gives us a stacktrace (as said, it's currently a failing test):
```
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:504)
#1      Expect.isTrue (package:expect/expect.dart:133)
#2      getClosure.foo ([...]/tests/language_2/const_nested_test.dart:22)
#3      main ([...]/tests/language_2/const_nested_test.dart:41)
#4      _startIsolate.<anonymous closure> (dart:isolate:1252)
#5      _RawReceivePortImpl._handleMessage (dart:isolate:1142)
```

but line 22 -- which as I read it should be a call to "Expect.isTrue" is "Expect.equals(1, MIN);". It's probably line 27 that fails instead  (i.e. "Expect.isTrue(identical(s, 'MIN = $MIN  MAX = $MAX  MASK = $MASK'));").

I can also "force" weird stuff in other places. E.g. with this file:
```
lalala() {
  const MIN = 2 - 1;
  const foo = 420;
  print(foo + MIN);
  throw "Hello";
}

main() {
  lalala();
}
```
I get
```
421
Unhandled exception:
Hello
#0      lalala ([thefile].dart:5)
#1      main ([thefile].dart:9)
#2      _startIsolate.<anonymous closure> (dart:isolate:1252)
#3      _RawReceivePortImpl._handleMessage (dart:isolate:1142)
```
which seems correct. But with this file:
```
lalala() {

  const foo = 420;
  print(foo);
  throw "Hello";
}

main() {
  lalala();
}
```
(where I cleared the "const MIN" and removed the "+ MIN" part in print, i.e. the stacktrace should be the same) produces this:
```
420
Unhandled exception:
Hello
#0      lalala ([thefile].dart:5)
#1      main ([thefile].dart:1)
#2      _startIsolate.<anonymous closure> (dart:isolate:1252)
#3      _RawReceivePortImpl._handleMessage (dart:isolate:1142)
```

Now all of the sudden the call from main is on line 1...

Trying to dig in to this a bit it seems that very fishy things are going on, for instance in "CodeSourceMapBuilder::WriteChangePosition" it claims that TokenPosition 76 belongs to function "_StringBase@0150898._interpolateSingle@0150898" in script "Script(dart:core)", translating to line 1 of the file (despite line 1 being comments about copyright) and that the function itself claims to start at position 171574 (function->token_pos().value(), which btw translates to line 5388 which sounds more likely).
In total there are lots of claims for line 1 in "CodeSourceMapBuilder::WriteChangePosition" - though that should basically never happen because of copyright headers etc.

cc @mraleph

**Comment by dgrove** [comment]
@a-siva any updates on this?

**Comment by dgrove** [comment]
ping

**Comment by a-siva** [comment]
This seems to work as intended, I tried it today and the stack trace produced is
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:566)
#1      Expect.isTrue (package:expect/expect.dart:133)
#2      getClosure.foo (file:///usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language_2/const_nested_test.dart:27)
#3      main (file:///usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language_2/const_nested_test.dart:41)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
