### ISSUE TITLE
EXCEPTION: NullError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by supermuka** [dart-lang/sdk#31159]
I am using Firebase library (https://pub.dartlang.org/packages/firebase).

With Dart SDK 1.24.2 works fine.

But with the last Dev Dart SDK 1.25, the follow error occur:

EXCEPTION: NullError: Right-hand side of 'instanceof' is not callable
STACKTRACE: 
dart:_runtime                                                   LazyJSType.new._check
packages/firebase/src/database.dart 394:66                      js.allowInterop.dart.fn.d
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:57738  <fn>
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:42000  t.inorderTraversal
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:41979  t.inorderTraversal
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:46174  t.inorderTraversal
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:52333  t.forEachChild
https://www.gstatic.com/firebasejs/4.2.0/firebase.js 320:57696  t.forEach
packages/firebase/src/database.dart 395:20                      src._database.DataSnapshot._fromJsObject.forEach
packages/preco_mi/src/entidade/entidade_component.dart 47:23    async.src._top.level.database.ref.once.then.dart.fn.e

**Comment by Janamou** [comment]
Seems to happen in this foreach method: https://github.com/Janamou/firebase-dart/blob/master/lib/src/database.dart#L393
