### ISSUE TITLE
Severe memory leak in fasta

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31151]
Original ID: 45c119bddb30c0f605dfec3db6d070a9b157ad3b

Compiling
```
typedef var Function(var arg);
```

uses > 16Gb of memory, resulting in the process being killed by the os.

**Comment by peter-ahe-google** [comment]
Dan, I'm pretty sure this is an infinite loop in the parser. OutlineBuilder.endTopLevelFields is called repeatedly with the beginToken having charOffset 8.

**Comment by peter-ahe-google** [comment]
@bwilkerson
