### ISSUE TITLE
analyzer: "return_of_invalid_type" on ?? return

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31169]
```yaml
analyzer:
  strong-mode: true
```

```bash
$ dart --version
Dart VM version: 2.0.0-dev.3.0 (Wed Oct  4 03:03:29 2017) on "macos_x64"
```

The following triggers an **error** in the strong-mode analyzer:

```dart
import 'dart:async';

void main() {
  _currentLogger.log('test');
}

class Logger {
  void log(String message) {}
}

final _defaultLogger = new Logger();
// ignore: return_of_invalid_type
Logger get _currentLogger => Zone.current[#currentLogger] ?? _defaultLogger;
```

It doesn't in earlier versions of the analyzer (like on DartPad):
https://dartpad.dartlang.org/091cf8ac03704f58afd405119e551003

I would have _sort_ of expected this maybe with `implicit-casts: false`, but even turning this option off doesn't make this work. I didn't actually try it in the VM, Dart2JS, or DDC, though.

**Comment by leafpetersen** [comment]
Are you quite sure that you don't have an analysis_options file lying around with implicit-casts set to false?  I can't repro this on fairly recent bleeding edge: I get the error with implicit-casts off, no error with implicit-casts on.

**Comment by bwilkerson** [comment]
@matanlurey Is this still an issue, or can we close it?

**Comment by matanlurey** [comment]
I haven't seen this again, lets close it.
