### ISSUE TITLE
Need equivalent of Java's DataInputStream and DataOutputStream

### ISSUE THREAD

**Issue by markmclaren2** [dart-lang/sdk#31166]
I'm trying to do in Dart what I would do in Java like this:
```
DataOutputStream dout = new DataOutputStream(new FileOutputStream("test.bin"));
out.writeInt(123);
out.writeFloat(4.0f);
out.writeUTF("Hello");

DataInputStream in = new DataInputStream(new FileInputStream("test.bin"));
int x = in.readInt();
float y = in.readFloat();
String name = in.readUTF();

```
[A similar issue raised in 2012](https://github.com/dart-lang/sdk/issues/5768) has been closed with the comment "By using dart:typeddata and the new IOSink(writeBytes), it's now possible to do this".  Well it may be *possible*, but it is far from clear to me how to do it.  Could someone please show how to rewrite the above code in Dart?  

If it takes more than 10 lines, please consider adding specialised classes to dart like [this one by TomCaserta](https://github.com/TomCaserta/dart_io/blob/master/lib/data_input.dart).  (Tom's version is lacking in that it doesn't handle streams, doesn't implement readLong properly, and has a bug when trying to read a UTF string at the end of the byte array)

**Comment by lrhn** [comment]
Not planning this for the platform libraries. It might be a good fit for `package:typed_data`.

**Comment by Binozo** [comment]
Still no real equivalent in 2023

**Comment by Hellomik2002** [comment]
Is there any solution ?
