### ISSUE TITLE
Should superclass static methods collide with subclass instance methods in Dart 2.0

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31165]
In Dart 1.0, the following is a warning:

```dart
class A {
  static foo() {}
}

class B extends A {
  foo() {}
}

main() {
  var a = new B();
}
```

Strong mode does not issue a warning for this code.

It seems fairly library author unfriendly to make adding a static method to a class a breaking change.

Should Dart 2.0 follow strong mode in this?

cc @lrhn @floitschG @eernstg @munificent @rakudrama @jmesserly

**Comment by leafpetersen** [comment]
See also https://github.com/dart-lang/sdk/issues/26734

**Comment by rakudrama** [comment]
Context - this warning would make it impractical to land the proposed Object.hash feature.

**Comment by lrhn** [comment]
I actually thought we already removed (or agreed to remove) that warning.
It's bad enough in Dart 1, because there is no good reason for the warning, but it would be much worse in Dart 2 if it becomes an error.

Definitely follow strong mode here!

**Comment by eernstg** [comment]
Agreed, let's stop emitting diagnostic messages for this situation!

I don't think we can construct a scenario where an existing expression `e` will call the instance method, and then we add the static method in a superclass, and then `e` silently changes its semantics and calls the static method --- that's the potential danger that I see, but as far as I can see it's just not possible.

**Comment by munificent** [comment]
> Definitely follow strong mode here!

👍

**Comment by eernstg** [comment]
Cool, I created an issue for doing this: #31201.

**Comment by eernstg** [comment]
Spec update done in 1c4358d459c75a429dceae61ef8e948e43b8378c, closing.
