### ISSUE TITLE
js-interop: Wrapping JS-objects into Dart-class

### ISSUE THREAD

**Issue by alexd1971** [dart-lang/sdk#31160]
How to wrap js-object having dash in property name with `@anonimous` Dart-class? JS-object like this:
```
{
  . . .
  'some-property': 'value'
  . . .
}

**Comment by jacob314** [comment]
You need to use
package:js/js_util.dart
to get and set that property.
You couldn't access that property with dot syntax in JS. The goal with JS interop is only to support properties that could be accessed with normally in JS.
To access this property fro dart you would write

```
import 'package:js/js_util.dart' as js_util;

Object getSomeProperty(Object someJsObject) {
  return js_util.getProperty(someJsObject, 'some-property');
}

**Comment by alexd1971** [comment]
Thanks. This works
