### ISSUE TITLE
VM's dart.math::{max,min} are not strong mode clean

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31162]
And are hard to strong mode clean without using completely unnecessary explicit casts.

They contain the following code (for handling the difference between `-0.0` and `0.0`)

```dart
T min<T extends num>(T a, T b) {
  if (b is double) {
    if (a is double) {
      if (a == 0.0) {
        return (a + b) * a * b;  // double is not assignable to T
      }
    }
  }
  return a;
}
```

This code triggers `double is not assignable to T` error.

One solution is to add an explicit cast `((a + b) * a * b) as T`.

However it seems another solution might be to change type promotion rules and allow promotion of type parameters, e.g. when variable of type `T` is promoted to `T extends double` so does type parameter itself. 

/cc @leafpetersen @floitschG

**Comment by leafpetersen** [comment]
> However it seems another solution might be to change type promotion rules and allow promotion of type parameters, e.g. when variable of type T is promoted to T extends double so does type parameter itself.

Hmm.  There may be some limited conditions this would be valid, but not in general.  In general, if you have `a : T` where `T extends B`, and you know that `a is S`, then you know that `a : T & B & S`.  In this case, we have `a : T & num & double`, i.e. `a : T & double`.  I think what you are observing is that the fact that `double` is final and that we have a value of type`T & double` implies that `T` is either `num` or `double`, and in either case assigning a `double` to it is valid.

This is true, but the reasoning feels somewhat ad hoc.  Is there a general rule here that I'm missing?

It could still be worth having an ad hoc rule for `double` and `int`, I suppose - they are important special cases.

For `min` and `max` specifically, I think the core library team plans to move these off of instances and onto the `double` and `int` classes as static methods, which should resolve this case ( @floitschG correct me if I'm wrong here).

**Comment by mraleph** [comment]
Yeah, I had confused myself. Obviously knowing that some value is both `T` and `S` does not give us any relation between `T` and `S`.
