### ISSUE TITLE
Abstract async method generates invalid kernel

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#31208]
An abstract method which is not plain sync results in invalid kernel being generated (since the method stays both abstract and not plain sync), which is then worked around later, as described here:

https://dart-review.googlesource.com/c/sdk/+/11501/2/pkg/front_end/lib/src/fasta/parser/parser.dart#3307

We should fix the front-end to generate valid kernel.

**Comment by sjindel-google** [comment]
Why is it invalid for an abstract method to be async in kernel?
