### ISSUE TITLE
There should be a vmservice_io_strong.dill file

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31203]
Currently there is only vmservice_io.dill compiled in the "legacy" mode.

To work around non-strong-mode-compliance of vmservice_io.dill we will temporary disable type checks in the service isolate even when VM is running in the checked mode.

**Comment by aam** [comment]
There is https://github.com/dart-lang/sdk/issues/31145 that tracks migration off loading from source code for vmservice service isolate in Flutter engine.

**Comment by a-siva** [comment]
We don't have a separate vmservice_io.dill file anymore, it is part of vm_platform.dill after https://github.com/dart-lang/sdk/commit/c29b19fb34d545caa227f6c16fa06bddc6da1114
So it is not necessary to have a vmservice_io_strong.dill file, closing this issue.
