### ISSUE TITLE
Validity check for "part of" uses wrong base dir

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#31211]
The check of whether a part mentions the correct file in its "part of" declaration uses the library's path, rather than that of the part, as the base directory for resolving the path in the "part of".

In `main.dart`:
```dart
part 'subdir/part.dart';

main() {}
```
In `subdir/part.dart`:
```dart
part of '../main.dart';
```

Compiling `main.dart` gives this warning:
```
main.dart: Warning: Using 'subdir/part.dart' as part of 'main.dart' but its 'part of' declaration says '../main.dart'.
```

**Comment by jensjoha** [comment]
This doesn't not seem to be a problem anymore. @askeksa-google  can you confirm?
