### ISSUE TITLE
Improve testing of generic functions

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31219]
Generic functions are not well tested, as evidenced by the recent discovery of #31213.
We should add more tests that for generic functions, methods and function types, to improve coverage
esp. in Fasta and the nascent generic functions support in the VM.

**Comment by a-siva** [comment]
The plan was to see if we could get the co19 folks to write more comprehensive tests for generic functions and strong mode. 
/cc @anders-sandholm

**Comment by matanlurey** [comment]
Is there any reason the language team can't write tests for their own language features?

**Comment by anders-sandholm** [comment]
@a-siva thanks for looping me in. 

Yes, we are planning on expanding co19, the Dart language conformance test suite, to cover 2.0 and hence also strong mode and generic functions. I filed #31229 for tracking this. 

While expanding the conformance test suite will help, it will most likely not remove the need for implementation-specific tests as well for e.g. generic functions. Ideally, DDC would already have a bunch of these tests given that is was developed along side the definition of strong mode. But there will likely be other tests that are specific to the Analyzer, the VM, etc.

That said, I look forward to having the full spec and conformance tests in place.

**Comment by a-siva** [comment]
Who should own this bug? I would like to add a milestone of 2.0-beta1 for this bug

**Comment by anders-sandholm** [comment]
I'd suggest someone on the VM team own it, if the bug is about adding more tests that are specific to the VM or close it if you believe it is covered by the more general #31229.

**Comment by a-siva** [comment]
I think you have covered it well in #31229, will close this.
