### ISSUE TITLE
analyzer: @override and super interfaces

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31225]
The following works fine @ stable but not @ google head, i.e.
`Dart VM version: 2.0.0-dev.3.0+google3-v2.0.0.dev.3.0 (google3) on "linux_x64"`

```dart
abstract class A {
  set count(int count);
}

abstract class B implements A {}

class C implements B {
  @override
  int count;
}
```

Triggers a `override_on_non_overriding_field` on C.count. It didn't before.

**Comment by matanlurey** [comment]
Never-mind, made a silly mistake :)

**Comment by prestonvanloon** [comment]
This is the first result (of 9 unhelpful results) on Google when searching for `override_on_non_overriding_field`, could you elaborate on what the solution is?
