### ISSUE TITLE
Finalize feature specification of strong mode

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/sdk#31228]
My apologies if this issue already exists somewhere. If so, pls merge/close.

Would be great if we could use this as a meta issue to track what is still missing in order for us to have a complete feature specification for strong mode. 

This will be useful for our teams implementing strong mode as well as for completing/expanding our co19 test suite.

@floitschG @leafpetersen @eernstg @lrhn @munificent 

- [x] New type rules and type system in the formal spec (e.g., sub-typing, ...) (eernst) [informal spec by @leafpetersen  underway](https://dart-review.googlesource.com/c/sdk/+/30927)
- [x] Capture "Ambiguities must be explicitly resolved" in a feature spec regarding sub-classing and class hierarchies (eernst) ([informal spec underway](https://dart-review.googlesource.com/c/sdk/+/40080))
- [ ] Feature specification of type inference #?????? (eernst) 
- [x] Optional new and const (including auto-const)

@eernstg edited the bullet list above to indicate that auto-const is now included rather than being discussed; the [CL](https://dart-review.googlesource.com/c/sdk/+/3160) has been landed.

Note the following issues whose requests are subsumed by or at least overlapping the requests in this issue:

- #27500 requests local inference specification.
- #27499 requests global inference specification.
- #16443 closely related to "Ambiguities must be explicitly resolved" ([CL](https://dart-review.googlesource.com/c/sdk/+/40080) on that).
- #30597 requests specification of generalized void; a related CL: [void-to-void data flow](https://dart-review.googlesource.com/c/sdk/+/38060).

**Comment by eernstg** [comment]
I wrote a [CL](https://dart-review.googlesource.com/c/sdk/+/14525) for extending [dartLangSpec.tex](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex) with support for generic functions. An obvious next step would be to update all the subtype rules (which includes deleting all references to '<<'/'more specific than').

Apart from that, the most recent additions to [the 'informal' directory](https://github.com/dart-lang/sdk/tree/master/docs/language/informal) were created in order to clarify various Dart 2 features, so they would serve as a source of additional topics to handle.

**Comment by eernstg** [comment]
Work is ongoing: [Said CL](https://dart-review.googlesource.com/c/sdk/+/14525) about generic functions has been landed as 673d5f0a665085153d25f8c39495eacdb010ca64. Feature spec about Dart 2 subtyping written by @leafpetersen in [this CL](https://dart-review.googlesource.com/c/sdk/+/30927).

**Comment by eernstg** [comment]
Added milestone for reaching the level where feature specs have stabilized, but the formal spec may not yet have been updated.

**Comment by eernstg** [comment]
Wrote a proposed feature spec in [this CL](https://dart-review.googlesource.com/c/sdk/+/40080) for the 'Ambiguities must be explicitly resolved' item.

**Comment by eernstg** [comment]
[This CL](https://dart-review.googlesource.com/c/sdk/+/3160) addresses the 'Optional new and const' item, may probably land as-is.

**Comment by eernstg** [comment]
Updated the [initial message](https://github.com/dart-lang/sdk/issues/31228#issue-268740515) by adding links to CLs aimed at closing bullet points in this issue.

**Comment by a-siva** [comment]
Somebody needs to own this issue, the assignee field is blank.

**Comment by eernstg** [comment]
I've assigned myself at this point, but note that it's actually a 'Type: meta' issue (where there is often no assignee) and remaining work is: Land the subtyping feature spec (by @leafpetersen), clarify the situation on inference feature specs (@leafpetersen has written several documents in the area), review the feature spec proposal on conflict resolution (by @eernstg), and decide on the relationship between `void` and data flow (that is, choosing at most one of the [above-mentioned](https://github.com/dart-lang/sdk/issues/31228#issue-268740515) CLs [3a](https://dart-review.googlesource.com/c/sdk/+/35740), [3b](https://dart-review.googlesource.com/c/sdk/+/38060)).

**Comment by dgrove** [comment]
Moving to the "Dart 2 Stable" milestone

**Comment by eernstg** [comment]
Closing: All specification tasks requested here are complete except for inference, and that is handled in the individual issues mentioned above.
