### ISSUE TITLE
Update imports on paste: should have a way to disable it

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31239]
![screen shot 2017-10-27 at 2 05 01 pm](https://user-images.githubusercontent.com/17034/32125244-df639cfc-bb1f-11e7-8594-c1197c4efb14.png)

Unless it's perfect – for all users, it's just annoying. The checkbox should be just "don't ask again" and then save the default to the answer the user picks – yes/no

**Comment by kevmoo** [comment]
Also, the `No` text doesn't seem centered...

**Comment by alexander-doroshko** [comment]
@kevmoo You'll find an option to disable the feature completely in Preferences.

**Comment by kevmoo** [comment]
> @kevmoo You'll find an option to disable the feature completely in Preferences.

I'd rather have it inline here. ESPECIALLY if we don't end up fixing all of these edge cases.

**Comment by alexander-doroshko** [comment]
Ok, switched from `Always update, don't ask again` to `Remember, don't ask again` that also remembers `No` answer.
Feel free to close this issue.

**Comment by kevmoo** [comment]
Awesome! Thanks!

**Comment by kevmoo** [comment]
Will leave it open until I get the latest...

**Comment by devoncarew** [comment]
Hey, to weight in here -

We should avoid if at all possible showing the user model dialogs as they're typing. Long term, I think we want:

- a setting in the preference dialog to disable (which Alex says we have today)
- no dialog prompt when the user hits paste
- for the auto-managed imports to just work; to insert correct imports when those can be determined, and to make no changes to the imports if there's a situation where we can't reason about code well (incorrect code, truly ambiguous imports, ...)

**Comment by keertip** [comment]
Closing as stale and our focus has changed over time.
