### ISSUE TITLE
VM throws incorrect exception for implicit downcast

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31236]
Consider the following code:

```dart
class A {}
class B extends A {}
void main() {
  B b;
  A a = new A();
  b = a; // (1)
}
```

Strong mode requires a `TypeError` to be thrown at (1); accordingly, the front end compiles this as `b = a as B;` (this functionality was added in 6f9d6965fec8285d275f13eff9df3ca1db97b9d2).

Normally, an "as" check throws a `CastError` when an "as" check fails.  So to signal that this "as" check should throw a `TypeError`, the front end sets the `AsExpression.isTypeError` flag (see https://github.com/dart-lang/sdk/blob/6f9d6965fec8285d275f13eff9df3ca1db97b9d2/pkg/kernel/binary.md#binary-format).  The VM needs to use this flag to determine what kind of exception to throw when the "as" check fails.

I'll upload a failing test illustrating this bug shortly.

**Comment by stereotype441** [comment]
Test is here: https://dart-review.googlesource.com/c/sdk/+/17042

**Comment by mraleph** [comment]
@sjindel-google could you take a look at fixing Kernel->IL translation to throw the right error?

**Comment by sjindel-google** [comment]
I can't reproduce this error. I've cherry-picked your revision, removed the line from `language_2/language_2_kernel.status` marking the test as failure, and the test still passes.

**Comment by sjindel-google** [comment]
My CI: I wasn't running with `--strong`. I'll look into it.

**Comment by stereotype441** [comment]
Thanks!  Sorry I wasn't clearer about how to repro the bug.
