### ISSUE TITLE
Missing return in overridden method should give an error if it doesn't match the inferred return type

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#31237]
I would expect the following to give an analysis error in strong mode, but it doesn't ([dartpad here](https://dartpad.dartlang.org/1e51f6daad13051e297bd9ee48adac9e)):
```
import 'dart:async';

abstract class AsyncThing {
  Future doAsync();
}

class IncorrectAsyncThing implements AsyncThing {
  // Doesn't return a Future!
  doAsync() {
    print('hello');
  }
}
```

It only gives an error about a mismatched return type if you have an explicit return.

cc @leafpetersen

**Comment by leafpetersen** [comment]
Note that inference correctly fills in the return type, but I think the code that emits the missing return hint doesn't look for an inferred type.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/62727
