### ISSUE TITLE
dartanalyzer does not fail if options file includes a bogus file

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#31232]
My package has an `analysis_options.yaml` file which simply imports another options file using an `include` directive with a relative path. If that path is incorrect, the analyzer finds no error and reports success. If I fix the path, it finds an analysis error and reports failure.

Dart version: `Dart VM version: 1.25.0-dev.11.0 (Wed Aug 23 04:58:17 2017) on "linux_x64"`

**Comment by pylaligand** [comment]
I'm observing similar behaviors with `dartanalyzer version 2.0.0-edge.64656316ec45936102c143e02a0342abf4e26f76`.

/cc @bwilkerson

**Comment by srawlins** [comment]
Analyzer will now report such issues, for example:

```none
$ dartanalyzer analysis_options.yaml 
Analyzing analysis_options.yaml...
  warning • The include file package:pedantic/analysis_options.yamlx in /Users/srawlins/code/dart-mockito/analysis_options.yaml cannot be found. • analysis_options.yaml:1:11 • include_file_not_found
1 warning found.
```

There is still a shortcoming in that analysis_options.yaml is not analyzed by default. Follow https://github.com/dart-lang/sdk/issues/29570 for updates on that aspect.
