### ISSUE TITLE
On imports, make analyser complain about wrong capitalization.

### ISSUE THREAD

**Issue by ktullavik** [dart-lang/sdk#31241]
Windows, IntelliJ
Dart SDK: 1.24.2

This is the second or third time I've been dumbfounded by really strange issues, like _is_ statements not working for certain types. Only to discover that some import path in some file was wrongly capitalized. Could you please make the analyzer catch this? It behaves as if imports are case insensitive.

**Comment by lrhn** [comment]
This is likely a symptom of running on Windows. If you miscapitalize a file name, you get distinct URIs that both load the same file (because the Windows file system is case insensitive).
If the analyzer doesn't treat those as separate libraries, it is doing it wrong.
