### ISSUE TITLE
IntelliJ generates wrong "override" method

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31249]
This is how the base method is defined:
```dart
abstract class MaterialDialog {
...
    Future<MdlDialogStatus> show({ final Duration timeout, Future onDialogInit(final String dialogId) }) {
        ...
}
```

This is what IJ generates:
```dart
class SetTimeFrameDialog extends MaterialDialog {
...
    @override
    Future<MdlDialogStatus> show(
        {final Duration timeout, Future onDialogInit(Future onDialogInit(final String dialogId))}) {

    } 
...
```
It doubles somehow **Future onDialogInit**

![capturfiles-20171030_055606](https://user-images.githubusercontent.com/116654/32184157-aa83e392-bd9b-11e7-9717-db89faa2c35d.png)

**Comment by srawlins** [comment]
While refactoring the CreateMissingOverrides fix, I looked into this, and it appears to be fixed. 🎉
