### ISSUE TITLE
FrontEnd should be able to parse SDK libraries from source

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31243]
If there are declarations that are required by FrontEnd itself, or one of the transformers, and these come from patches, then these patches should be included with the deployment SDK and loaded during SDK libraries compilation.

**Comment by jensjoha** [comment]
I have a hard time understanding this issue, but I think it has to do with patch files. To my knowledge patch file are understood by fasta now.

**Comment by scheglov** [comment]
If patch files are supported, this is just great.
And yes, we can close this issue.
Thanks!
