### ISSUE TITLE
ddc doesn't work on ios webkit

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#31248]
Prior to the latest ios 11/safari release, this demo worked great on ios:

https://github.com/bp74/StageXL_Samples/tree/master/web/_old/text_field

Now, it gets hung-up.

pub serve output:
jdavis@ubuntu16024:~/repo/github/StageXL_Samples$ pub serve --hostname 10.0.0.32
Loading source assets... 
Loading dart_to_js_script_rewriter transformers... 
Serving stagexl_samples web on http://10.0.0.32:8080
Build completed successfully
[web] GET Served 4 assets.
[web] GET _old/text_field/index.dart.js → stagexl_samples|web/_old/text_field/index.dart.js
[web] GET Served 2 assets.
[web] GET _old/text_field/index.dart.bootstrap.js → stagexl_samples|web/_old/text_field/index.dart.bootstrap.js
[web] GET _old/text_field/dart_sdk.js → stagexl_samples|web/_old/text_field/dart_sdk.js
[web] GET web___old__text_field__index.js → stagexl_samples|web/web___old__text_field__index.js
[web] GET Served 4 cached assets.
[web] GET Served 2 cached assets.
[web] GET Served 2 cached assets.
[web] GET packages/stagexl/lib__stagexl.js → stagexl|lib/lib__stagexl.js
[web] GET _old/text_field/dart_sdk.js → (cached) stagexl_samples|web/_old/text_field/dart_sdk.js

**Comment by unicomp21** [comment]
same example works on my old ipad 2

**Comment by unicomp21** [comment]
just realized it's due to new dart dartdevc compiler, closing

**Comment by unicomp21** [comment]
The issue mentioned above for dartdevc does "not" happen for safari on latest macos 11.  However, there are definitely issues for safari on the latest ios 11.  This needs to be sorted.

**Comment by matanlurey** [comment]
AFAIK, DartDevC is not officially supported on anything but Chrome today.

I know that we've had decent success of running it on Firefox, but I don't know about Edge/Safari.

/cc @vsmenon

**Comment by unicomp21** [comment]
ios/safari is a pretty big market.  The plan is to no longer support ios/safari?

**Comment by unicomp21** [comment]
think I may have been confused, so I guess the plan is to keep dart2js around and never replace it with dartdevc?

**Comment by kevmoo** [comment]
Dartdevc is the DEV compiler. Meant to be fast and generate pretty readable
JS.

dart2js is meant to generate small, fast JS – even if it's a bit slower.

**Comment by unicomp21** [comment]
dartdevc doesn't run on chrome/ios11

**Comment by vsmenon** [comment]
Repurposing this bug.  DDC doesn't yet work on ios-webkit - both safari and chrome use that.

ES6 support (DDC requirement) looks pretty good (see far right):

https://kangax.github.io/compat-table/es6/

**Comment by jmesserly** [comment]
I don't think we're planning to take any action here for DDC? Support will come as soon as the browser has enough ES6 support. Closing because I think this bug is stale.
