### ISSUE TITLE
Link to dart:collection in docs

### ISSUE THREAD

**Issue by raphalvessa** [dart-lang/sdk#31246]
The link to `dart:collection` in https://api.dartlang.org/stable/dart-core/dart-core-library.html and https://api.dartlang.org/stable/dart-core/Iterable-class.html is broken.

**Comment by kevmoo** [comment]
@jcollins-g is this syntax `[dart:collection](#dart-collection)` even supported by dartdoc?

Is there an "official" way to refer to a `dart:*` library?

**Comment by jcollins-g** [comment]
There is no way to do this with dartdoc's help, at present.

**Comment by kevmoo** [comment]
https://dart-review.googlesource.com/c/sdk/+/44582

**Comment by kevmoo** [comment]
Good find, @raphalvessa !
