### ISSUE TITLE
modInverse broken by implicit downcast checks

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31256]
I will shortly be committing a change which causes implicit downcasts to be explicitly represented in kernel code for compound assignments, e.g.

```dart
int x;
num y;
x += y;
```

will be compiled as though it had been written:

```dart
int x;
num y;
x = (x + y) as int;
```

For reasons I don't understand, this causes mysterious breakages in a few corelib tests of modInverse.  For example, `python tools/test.py -m release -c dartk --strong corelib_2/big_integer_arith_vm_test/modInv` produces:

```
Unhandled exception:
type 'int' is not a subtype of type 'int' where
  int is from dart:core
  int is from dart:core

#0      int.modInverse (dart:core)
#1      testBigintModInverse (file:///usr/local/google/home/paulberry/dart1/sdk/out/ReleaseX64/generated_tests/corelib_2/big_integer_arith_vm_test_modInv.dart:256:22)
#2      main (file:///usr/local/google/home/paulberry/dart1/sdk/out/ReleaseX64/generated_tests/corelib_2/big_integer_arith_vm_test_modInv.dart:433:5)
#3      _startIsolate.<anonymous closure> (dart:isolate:1252:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate:1142:12)
```

**Comment by sjindel-google** [comment]
This test also fails if you run it with the VM `--enable_type_checks`, even without your change.

The source of the failure you're seeing is that you've caused type checks to be emitted into `BigInt.modInverse` even when the `--enable_type_checks` flag is not passed.

**Comment by sjindel-google** [comment]
I've learned that Fasta is responsible for adding all necessary type checks when `--strong` is provided. In this view, there's a bug in the `BigInt.modInverse` which causes a typing inconsistency with Strong Mode.
https://dart-review.googlesource.com/c/sdk/+/18841

**Comment by sjindel-google** [comment]
The reason for the confusing error, btw, is that the `int` on the left is `Smi` whereas the `int` on the right is `BigInt`.
