### ISSUE TITLE
analyzer warns unnecessarily on nested mixins

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#31250]
Tested in 2.0.0-dev.5.0.

I believe the following code snippet should be legal, even without the VM's supermixin flag:

```
class AChainedMixin {}
class ATestMixin extends Object with AChainedMixin {}
class AParentClass {}
class AClass extends AParentClass with ATestMixin {}
```

However, the analyzer warns on the last line for ATestMixin, claiming:
```
error: The class 'ATestMixin' can't be used as a mixin because it extends a class other than Object. 
```

The VM suggests it really is legal by parsing and running correctly constructions like this, AFAICT.

**Comment by bwilkerson** [comment]
I tried a slightly more complete example:
```
main() {
  AClass x = new AClass();
  print(x.a());
  print(x.b());
  print(x.c());
}

class AChainedMixin {
  String a() => 'a';
}

class AClass extends AParentClass with ATestMixin {
  String c() => 'c';
}

class AParentClass {}

class ATestMixin extends Object with AChainedMixin {
  String b() => 'b';
}
```
The VM produces the following output:
```
Unhandled exception:
NoSuchMethodError: Class 'AClass' has no instance method 'a'.
Receiver: Instance of 'AClass'
Tried calling: a()
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      main (file:///Users/brianwilkerson/dart/personal_test/test.dart:8:11)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```
which seems to imply that `AClass` doesn't inherit from `ATestMixin`.

**Comment by jcollins-g** [comment]
Reordering indicates `x.b()` and `x.c()` both work, suggesting to me that while `AClass` does successfully mix-in `ATestMixin`,  `AChainedMixin` doesn't apply.

**Comment by jcollins-g** [comment]
It might be that the warning just needs to be a bit clearer, and the VM should prevent this case altogether to avoid confusion?

**Comment by lrhn** [comment]
The class `class ATestMixin extends Object with AChainedMixin {}` has the superclass `Object with AChainedMixin` (which is an anonymous class introduced by the mixin application). The mixin derived from that class (if one could be derived) would be the empty mixin declared by the `{}`.

If you had written it as `class ATestMixin = Object with AChainedMixin;` instead, there wouldn't be an extra layer on top of the mixin application, so the superclass would be `Object` and you would be allowed to derive a mixin from the class.

In your more complex example, where I assume you use the super-mixin feature, you get the same issue - the mixin derived from `ATestMixin` only contains a declaration of `b`, the declaration of `a` is in the superclass of `ATestMixin`, so it's not included in the mixin.

**Comment by srawlins** [comment]
It is as @lrhn . The original example features this warning:

> error • The class 'ATestMixin' can't be used as a mixin because it extends a class other than Object. • a.dart:5:40 • mixin_inherits_from_not_object

Changing ATestMixin to a class application removes the error.
