### ISSUE TITLE
Improve analyzer error translation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31259]
https://dart-review.googlesource.com/c/sdk/+/17680 adds a new error to `pkg/front_end/messages.yaml` which is not covered by the `AstBuilder.addCompileTimeError` method.  This causes the test `analyzer/test/src/fasta/message_coverage_test` to fail.  As @bwilkerson points out in the code review, it doesn't make sense to fix the test by adding the new error to `AstBuilder.addCompileTimeError`, because the new error is reported during type inference, not during AST building.

For the moment I'm disabling the test to get myself unblocked.  In the long term we should probably create an "error mapper" object/function that maps *all* errors and change AstBuilder to use that function.  Once we've done that it would make sense to add the new error to the "error mapper".

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/18148
