### ISSUE TITLE
recursive call on locally defined async function is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31269]
The following throws in DDC:

```dart
import 'dart:async';

Future<int> test(int n) async {
  Future<int> _foo(int n) async {
    if (n == 0) return 0;
    int m = await _foo(n-1);
    return m + 1;
  }

  return await _foo(n);
}

main() async {
  int x = await test(10);
  print(x);
}
```

The error is:
```
Type 'String' is not a subtype of type 'int' in strong mode
```

It should print `10` (as in the VM).  Note, if I change the recursive call to `_foo` to call `test`, it runs as expected in DDC.

**Comment by jmesserly** [comment]
I can take a look ... if I had to guess, this could be caused by our giving friendly names to async functions for call stacks. That may result in shadowing the outer name with the inner one.

**Comment by vsmenon** [comment]
Jenny - this is fixed by your recent CL, right?

**Comment by jmesserly** [comment]
yup!
