### ISSUE TITLE
[kernel] Binary representation of SuperPropertyGet/Set lack file offset

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31266]
With `super` resolution done in VM, absence of file offset in SuperPropertyGet/Set nodes binary representation results in loss of VM source location association. So, for example, stepping through the `super` property get/set operations in VM is affected.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/18184

**Comment by aam** [comment]
Awesome, thanks!
