### ISSUE TITLE
Analyzer: Future<void> requiring return statement?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31278]
As of `dev-6.0`:

```dart
Future<void> doThing() async {
  return;
}
```

... lints the `return` statement with:

```
warning: Missing return value after 'return'. (return_without_value at [...])
```

If I change it to `return null;`, the warning goes away. Interestingly enough, `Future<Null>` is fine:

```dart
Future<Null> doThing() async {
  return;
}
```

-----

~~On a related note - what is the status of `Future<void>`? I didn't try compiling/running the code.~~

**EDIT**: Thanks @munificent - I see that full support is not planned until after the FE migration.

**Comment by lrhn** [comment]
You should probably be allowed to not return, or use `return;` , with a return type of either `void` *or* `FutureOr<void>` (or `FutureOr<FutureOr<void>>`, etc).

Maybe something like:
> A type is "voidable" if it is `void` or it is `FutureOr<T>` and `T` is voidable. It's an error if a function body contains `return;` or can reach the end of the body without throwing or returning, unless the function's return type is voidable. It is an error if a function body contains `return expr;` and the function's return type is `void`.

The `FutureOr<void>` type is a little tricky. Any value can be assigned to it, so it's not that different from `dynamic`, `void` or `Object`, and it's not `void`. There are operations you can do on it - it's just that if it\s not `Future<void>`, you're not supposed to use it.
