### ISSUE TITLE
Analyzer: Cannot find definition of new typedef

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31274]
Reproduction case at dev-6.0:

```dart
import 'dart:async';

typedef _RunGuarded = T Function<T>(
  T Function(), {
  void Function(Object, StackTrace) onError,
});

main() {
  _RunGuarded runGuarded = runZoned;
  return runGuarded(() {

  }, onError: (error, trace) {

  });
}
```

Neither `error` or `trace` above have any (noticeable) types (both show up as `dynamic` on hover in IntelliJ), and I can't control-click on `onError`. That might be intended, but it's confusing as I assumed it would take me to my typedef.

**EDIT**: Type inference seems to work, just not on the parameter location. I.e. if I reference `trace` in the function body, it has a type.

**Comment by bwilkerson** [comment]
It isn't intentional. It's probably another symptom of having incomplete support for the generic function type syntax.

**Comment by matanlurey** [comment]
I haven't seen this in a while
