### ISSUE TITLE
main cannot accept arguments in strong mode

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31270]
Consider the following program:
```dart
main(List<String> args) {
  print(args);
}
```

This works fine if I run it normally using the VM, but if I pass the "--strong" flag to the VM I get the following error:
```
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'main'
Receiver: Closure: (List<String>) => dynamic from Function 'main': static.
Tried calling: main()
Found: main(List<String>) => dynamic
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

This happens whether I supply arguments on the command line or not.

**Comment by lrhn** [comment]
I'm guessing some type check should be changed from (effectively) `is Function(dynamic)` to `is Function(null)`.

**Comment by lrhn** [comment]
Turns out we already had a lot of RuntimeError expectations in strong-mode tests for this reason. I'm tweaking the status files now :)
