### ISSUE TITLE
dartanalyzer and analysis service can't agree on problems with options file

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#31282]
Using the analyzer CLI version `dartanalyzer version 2.0.0-edge.64656316ec45936102c143e02a0342abf4e26f76`, I can analyze a package with a custom set of options fine. However, using the analysis server from the same SDK, I get a warning saying the options file contains the `language: enableAssertInitializer` attribute which does not exist anymore and analysis consequently fails.

**Comment by bwilkerson** [comment]
Wow! I'm not sure why `dartanalyzer` isn't reporting that. Are you asking for `--hints`? In any case, the option is no longer valid because it's enabled by default.

That said, the presence of the option should be causing analysis to fail. So there are at least two problems.

**Comment by pylaligand** [comment]
I have `--fatal-lints` enabled (the CLI does not seem to recognize a `--hints` flag).

**Comment by srawlins** [comment]
Should be fixed; we've switched the command line tool to more closely align with the DAS behavior from an IDE, as it now uses DAS. Please re-open if this is still an issue.
