### ISSUE TITLE
Front end treats strong mode errors as warnings

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31286]
Most Dart 1.0 warnings are errors in Dart 2.0.  The error reporting mechanisms in the front end currently treat most of these cases as warnings, regardless of whether the front end is running in strong mode.

We need these conditions to be reported as errors in strong mode.

**Comment by sjindel-google** [comment]
Moreover, Fasta doesn't patch up the generated Kernel after encountering these errors, so we are left with
ill-typed Kernel.

**Comment by askeksa-google** [comment]
Commit reverted due to test failures.
