### ISSUE TITLE
Co19 no_such_method_t01 test broken by bc9645509ecb

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31288]
The test `co19/Language/Expressions/Property_Extraction/Super_Getter_Access_and_Method_Closurization/no_such_method_t01` seems to have been broken for dartk and dartkp runs by bc9645509ecbbb873a13990687ff6c6d363a0f2c.

I'll update the status files shortly.

**Comment by sivachandra** [comment]
I am not sure it was broken by the change you specified. The buildbot run with that change was green: https://uberchromegw.corp.google.com/i/client.dart/builders/vm-kernel-linux-release-x64-be/builds/5125

**Comment by sivachandra** [comment]
I am confused. The test passed on the bot but fails for me locally.

**Comment by stereotype441** [comment]
It looks like the buildbot computed the blamelist incorrectly.  Build 5125 checked out edc4cb1f90d49dd1d0cf7bdfe6f22406f0e5970d, which is one commit before bc9645509ecbbb873a13990687ff6c6d363a0f2c; it incorrectly includes bc9645509ecbbb873a13990687ff6c6d363a0f2c in its blamelist.

If you look at build 5126 you'll see the problem reproduced on the buildbot.

**Comment by aam** [comment]
+@sgrekhov 

I think test should use `Expect.mapEquals` instead of `Expect.equals` to validate empty name map:

```
    Expect.mapEquals(const{}, i.namedArguments);
```

**Comment by sjindel-google** [comment]
No, the test is checking that `i.namedArguments` is *exactly* the canonical constant empty map.

**Comment by aam** [comment]
> No, the test is checking that i.namedArguments is exactly the canonical constant empty map.

Question is whether it is correct expectation that `namedArguments` is canonical constant empty map when there are no named arguments, though?

**Comment by eernstg** [comment]
It is overly specific to require the canonical constant empty map/list for these objects. The language specification has been adjusted (by Lasse) recently with respect to this topic, and it states that these objects are "an immutable/unmodifiable list with the same elements as.." or "an immutable/unmodifiable map with the same keys and values as..". We may need to be yet another bit explicit on this, but it is already clear that it is too strict to require `identical()`, and the intention is that only the elements/keys/values should be compared. So the test needs to be adjusted.

**Comment by eernstg** [comment]
PS, fun fact: The language specification had `evaluates to the value of \code{\CONST{} []}` for getter invocations of `noSuchMethod` in August 2013 when it was added (commit 59611b2414f81f2cf3bfe5f221970bab2a646e99). So it used to be specified as tested, and it's been changed in c620e827b7e5187c417c46d80ee650e6588ef54a, Sep 2017.

**Comment by sjindel-google** [comment]
We're waiting on the resolution of https://github.com/dart-lang/co19/issues/127 to fix this test.

**Comment by sgrekhov** [comment]
dart-lang/co19#127 fixed
