### ISSUE TITLE
Auto-configuration for Tests in IntelliJ/Dart plugin

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31292]
Say I have a unit-test marked with `@TestOn("browser")` or with `@TestOn("chrome")`

If I run a test the first time, when it generates the Dart-Test in IntelliJ it should automatically add the Test runner option "-p chrome"

![capturfiles-20171107_101402](https://user-images.githubusercontent.com/116654/32485873-2e349088-c3a5-11e7-92cf-dcd9b4586182.png)

**Comment by alexander-doroshko** [comment]
@MikeMitterer I don't think the feature is related to the Dart SDK :). YouTrack request is welcome: https://youtrack.jetbrains.com/issues/Web

**Comment by alexander-doroshko** [comment]
Note that you do not need to start a known-to-fail run, instead, you may select 'Create ...' option from the right-click menu and tune the option before the first start.

**Comment by MikeMitterer** [comment]
@alexander-doroshko No, I'm sure it's a Plugin-Thing. I'm never sure where to put UI/Plugin issues... However I create one on the IJ-side.

I know the "Create ..." option and it is great for global settings. But in this case it doesn't really help. About 70% of my Dart-Tests should run everywhere - so they are not marked. ~30% are Browser only. Defining an option in "Create..." (-p chrome) results in having the -p option for all new created test which is wrong for 70% of all the tests.

**Comment by MikeMitterer** [comment]
https://youtrack.jetbrains.com/issue/WEB-29608

**Comment by alexander-doroshko** [comment]
>  Defining an option in "Create..." (-p chrome) results in having the -p option for all new created tests. 

No, no, no :). What you are saying is true for the **Default** run configuration that is configured in Run | Edit Configurations dialog. 'Create...' option which is in the right-click menu creates one run configuration, but doesn't touch default settings.

**Comment by alexander-doroshko** [comment]
> I'm never sure where to put UI/Plugin issues... 

What is powered by the Analysis Server from the Dart SDK goes here. What is plugin-specific (like creating run configurations) goes to the plugin issue tracker.

**Comment by MikeMitterer** [comment]
Uhhh - shame! I never use this option because I'm creating tests based on my own Dart-Test-Template via "New". Anyway thanks for pointing me to "Create" but I think my feature-request is still valid...

**Comment by alexander-doroshko** [comment]
Yes, the request is valid of course.
