### ISSUE TITLE
Error functionality required, test passing on error

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#31295]
Here is a real life problem I have now with testing in a form of a Short, Self Contained, Correct (Compilable), Example:

```Dart
import 'package:dart_test_fail_project/dart_test_fail_project.dart';
import 'package:test/test.dart';

void main() {
  test('calculate', () {
    bool success = tryToCallSomeComponent();
  });
}

bool tryToCallSomeComponent() {
  bool success = true;
  try {
    /**
        begin routine
     */
    doBeginActionWithPotentialException();

    /**
        Exception was not thrown at this point.
        Now we do some intermediate check.
        The result should be valid.
        Otherwise the test should report invalid state and throw an error.
     */
    expect(calculate(), 42);

    /**
        end routine
     */
    doEndActionWithPotentialException();

    return success;
  } catch (e, s) {
    /**
        Should catch regular exceptions.

        But catches test failures also.

        The expect() failed but test passed.
     */
    print(e);
    print(s);
  }

  return !success;
}

```

What is happening: 
```calculate()``` returns ```43``` and the test should fail. Instead the ```TestFailure``` exception is cached by the try/catch. The test is reported as passed.

Root cause:
Dart lang is missing errors.

```
An Error is a subclass of Throwable that indicates serious
problems that a reasonable application should not try
to catch. Most such errors are abnormal conditions. 
```

```TestFailure```  thrown by the ```expect``` should extend/implement ```Error```-class and no one  should be able to catch it intentionally or unintentionally.

Example project to reproduce the issue: https://github.com/JFixby/dart_test_fail_project

**Comment by JFixby** [comment]
The same for ``` assert(calculate() == 42);```

**Comment by JFixby** [comment]
Temp workaround:

Replace ```expect(a,b)``` with ```test_expect(a,b)```
```
Future<Null> test_expect(expected, value) async {
     expect(expected, value);
}
```

this will throw ```TestFailure``` outside of any try/catch scope

**Comment by srawlins** [comment]
It is [not recommended](https://www.dartlang.org/guides/language/effective-dart/usage#avoid-catches-without-on-clauses) to catch without using an `on` clause which would also prevent the situation you are experience. This is basically exactly what `on` is for.

Another feature that the test package provides is [throwsA](https://pub.dartlang.org/documentation/test/latest/test/throwsA.html), which is much more expressive than testing that your code throws via try/catch.

**Comment by JFixby** [comment]
The point is: failed `expect()` suppose to fail test. 
Instead, it throws something that stacks somewhere in code caught by some "try/catch".
I understand what you propose, but that is just a crutch.
