### ISSUE TITLE
flutter_gallery AOT snapshot is 1.5MB bigger than six months ago (performance regression)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31302]
In May, the flutter_gallery AOT snapshot was 9.5MB. It's now 11MB:

![flutter_gallery__build___aot_snapshot_size_total___regression](https://user-images.githubusercontent.com/551196/32511945-2c712cfc-c3aa-11e7-84b1-0f7f1b3b76b0.png)

Obviously the gallery has also grown in scope in that time, which doesn't help. :-)

**Comment by a-siva** [comment]
Do we have numbers on the current size of the AOT snapshot after these CLs were landed.

**Comment by Hixie** [comment]
10729KB for `aot_snapshot_size_total flutter_gallery__build`
10728KB for `aot_snapshot_size_total flutter_gallery_win__build`
11352KB for `aot_snapshot_size_total flutter_gallery__preview_dart_2_build`

Not sure why it's 1KB smaller when built on Windows rather than on Mac...

![flutter_gallery__build___aot_snapshot_size_total___regression_2](https://user-images.githubusercontent.com/551196/33291960-73653388-d37c-11e7-8dc4-d7945b631faf.png)

**Comment by rmacnak-google** [comment]
A slow size increase over such a long period of time is not actionable.

**Comment by Hixie** [comment]
To be clear, the extent to which this was meant to be actionable is more along the lines of systemic changes (better monitoring, different processes to help change the direction of the growth, changes to team priorities, etc) rather than any specific code change or revert of specific commits.
