### ISSUE TITLE
Error using super's ctor with optional parameters

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/sdk#31314]
Dart Analyzer shows error when classes constructor uses super's one with optional parameters. No error appears at runtime.

To reproduce issue create two classes like below in separate packages:

    // package one
    class A {
      A(param1, [param2]);
    }
    
    // package two
    class B extends A {
      B() : super(null);
    }

It shows: "error: The class 'A' doesn't have an unnamed constructor."

**Comment by zoechi** [comment]
What Dart version?

**Comment by kelegorm** [comment]
1.24.2

**Comment by ranquild** [comment]
Same code works fine on Linux

**Comment by kelegorm** [comment]
Sorry, it's real issue, I was wrong about test case. I'll figure out what else need to reproduce that bug.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
