### ISSUE TITLE
Dart Analyzer doesn't show not-implemented errors.

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/sdk#31315]
Dart Analyzer doesn't show not-implemented errors if interface class goes from other package. Error about unimplemented method fires at runtime like:

    NoSuchMethodError: Class 'A' has no instance getter 'b'.

**Comment by kelegorm** [comment]
Here is one more case: you can't see unimplemented warnings if class extends HtmlElement (or PolymerElement in dart polymer 1).

    class VisAppRouting extends HtmlElement implements ISomeInterface {
      VisAppRouting.created() : super.created();
    }
    
    abstract class ISomeInterface {
      someMethod();
    }

**Comment by zoechi** [comment]
What unimplemented warning do you expect for extending HtmlElement?

Extending inherits the implementation, implementing doesn't, therefore `VisAppRouting` needs to implement `someMethod` directly.

**Comment by bwilkerson** [comment]
> Extending inherits the implementation, implementing doesn't, therefore `VisAppRouting` needs to implement `someMethod` directly.

Correct. And if you remove the `extends HtmlElement` clause you get an error telling you so. But analyzer doesn't produce the error if the extends clause is there.

I believe that this is a result of the fact that `HtmlElement` inherits a non-abstract implementation of `noSuchMethod` from `Interceptor`. The spec says that this method inhibits the error:

> It is a static warning if an abstract member _m_ is declared or inherited in a concrete class _C_ unless:
> • _m_ overrides a concrete member, or
> • _C_ has a _noSuchMethod()_ method distinct from the one declared in class _Object_.

Hence, I believe this is working as intended.

**Comment by kelegorm** [comment]
Hm, it's bad for developing. As Dart is mainly front-end language and using of HtmlElement class is usual and almost unavoidable, it makes really hard to use mixins and interfaces with *Element classes.

I hope it's some subject to change, at least as linter rule.
