### ISSUE TITLE
Analyzer doesn't complain about generic properties

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#31322]
The analyzer doesn't produce any errors about the following code:

```dart
T get value<T> => null;
```

However, this is invalid. The VM and dart2js both fail to parse it, and DDC complains that `T` is undefined.

**Comment by srawlins** [comment]
Oof, the analyzer now reports this issue, but it reports 9 issues. :/  I think there is another recovery issue flagged for such top-level members, but I'm not sure, so I'll leave this open for now.

**Comment by srawlins** [comment]
The recovery has improved, and there is no recovery issue when this getter is included in a class. I'll close it as the root issue is resolved.
