### ISSUE TITLE
VM doesn't report source locations for implicit downcast errors

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31327]
Consider the following program:
```dart
void f(num n, int i) {
  i = n; // (1)
}
main() {
  f(1.5, 0);
}
```

When run in strong mode, this program should produce an error at the line marked (1), due to a failure in the implicit downcast from `num` to `int`.

If I run the program in strong mode on the VM, using the front end, I see the following output:
```
Unhandled exception:
type 'double' is not a subtype of type 'int' where
  double is from dart:core
  int is from dart:core

#0      f (file:///usr/local/google/home/paulberry/dart2/sdk/pkg/front_end/testcases/foo.dart)
#1      main (file:///usr/local/google/home/paulberry/dart2/sdk/pkg/front_end/testcases/foo.dart:6:3)
#2      _startIsolate.<anonymous closure> (dart:isolate:1252:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate:1142:12)
```

Note that the first line of the stack trace has no line number.  By contrast, if I run the same program in checked mode (without --strong and without using the front end), the output is:
```
Unhandled exception:
type 'double' is not a subtype of type 'int' of 'i' where
  double is from dart:core
  int is from dart:core

#0      f (file:///usr/local/google/home/paulberry/dart2/sdk/pkg/front_end/testcases/foo.dart:2:7)
#1      main (file:///usr/local/google/home/paulberry/dart2/sdk/pkg/front_end/testcases/foo.dart:6:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

When an implicit downcast error occurs in a large function, the lack of line number information can make it very difficult to track down the source of the problem.

**Comment by kmillikin** [comment]
Fix is here: https://dart-review.googlesource.com/c/sdk/+/20663
