### ISSUE TITLE
Provide ProtectedFileByteStore constructor that doesn't take protectedDuration, assumes infinity.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31323]
https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/byte_store/protected_file_byte_store.dart#L37 requires `protectionDuration`, however it would be nice to be able to skip it effectively saying that protected entities are staying in cache forever.

Basically, if we update set of protected keys to always reflect current compiled state, there is no reason for us to ever remove protected keys from cache.

**Comment by scheglov** [comment]
You can get equivalent behavior by using very long duration, e.g. `new Duration(days: 365 * 100)`. `100 years` should be enough for any practical purpose.

**Comment by aam** [comment]
You can, but it looks weird on client side and is not tidy in ProtectedFileByteStore where you can bypass this time check completely: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/byte_store/protected_file_byte_store.dart#L90

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/19442

**Comment by jensjoha** [comment]
It seems that this issue can be closed, any objections?
