### ISSUE TITLE
Analyzer: Parsing trailing comma in assert in initializer list fails

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31320]
The following program causes dartanalyzer (version 2.0.0-dev.6.0) to stop with a syntax error:
```dart
class C {
  C() : assert(true,);
}
```
and so does this one:
```dart
class C {
  const C.n2() : assert(true, "Message",);
}
```
Presumably, trailing commas in `assert` in an initializer list has not yet been implemented.

**Comment by zoechi** [comment]
see also #29959, #30039

**Comment by eernstg** [comment]
Thanks for noticing these very similar issues! 

#30039 is an area-language issue which was closed with 'The behavior is currently correct' before it was decided to add trailing comma support to assert.

#29959 is similar to this one, mentions that the feature is now part of the language and the spec has been updated. It has 'area-language' as well, but it also includes references to two committed CLs where the analyzer is modified to support trailing commas in asserts (563720617c9a25dba653a2eddeebe42000556789, f93da679a12d93c45048fbb0f2e8c654eaec42d7). 

However, the analyzer still doesn't handle trailing commas in asserts in initializer lists, hence this issue.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/29520
