### ISSUE TITLE
dart2js refines local on calls to calls to locals

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#31333]
dart2js refines local on calls to calls to locals:

foo(f()) {
  f().bar(); // f is 'refined' to be the receiver 'bar' call
}

`dart2js_extra/local_function_call2_test` fails.

**Comment by rakudrama** [comment]
Is this in inferrer and/or ssa/types_propagation?

**Comment by sigmundch** [comment]
inference - Johnni added the regression tests here: https://dart-review.googlesource.com/c/sdk/+/19566
