### ISSUE TITLE
Type inference for indexed sets could be improved

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31336]
Consider the following code:
```dart
T f<T>() => null;
class C {
  void operator[]=(int index, value) {}
  operator[](double index) => null;
}
void g(C c) {
  c[f()] = null; // (1)
  c[f()] ??= null; // (2)
  c[f()] += null; // (3)
}
```

Currently the front end uses an empty context when inferring the type of the index in an indexed set, so all three calls to `f()` above will get inferred as `f<dynamic>()`.  (This mimics the behavior of the analyzer).

But it seems like we could do better.  In (1), we could clearly use `int` as the the type context, causing `f()` to be inferred as `f<int>()`.

It's less clear what we should do for (2) and (3), since in these statements the value returned from `f()` is used both for the call to `operator[]` and `operator[]=`, and those two methods specify different types for the index.  Possible solutions:
- Use the least upper bound for the context, so `f()` would be inferred as `f<num>()`.
- Use the type from `operator[]` for the context, so `f()` would be inferred as `f<double>()` (and an error would be reported, since `double` is not assignable to `int` in the call to `operator[]=`)
- Use the type from `operator[]=` for the context, so `f()` would be inferred as `f<int>()` (and an error would be reported, since `int` is not assignable to `double` in the call to `operator[]`)

(Of course, in most reasonable code the index types from `operator[]` and `operator[]=` will be the same, so these three solutions will be equivalent)

**Comment by stereotype441** [comment]
@leafpetersen FYI

**Comment by lrhn** [comment]
I believe we no longer allow the types of an index-set and index-get to be unrelated.
