### ISSUE TITLE
Flakiness with vm-precomp windows-simarm64 bots

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#31342]
windows-simarm64 bots have been sporadically failing with timeouts. I updated the status files while gardening accordingly.

**Comment by efortuna** [comment]
(Slava, feel free to assign to someone else, just putting you on this since we talked about it)

**Comment by mraleph** [comment]
Duplicate of #29261. (Fix is coming)

**Comment by mraleph** [comment]
Duplicate of issue #29261

**Comment by mraleph** [comment]
Duplicate of #29261
