### ISSUE TITLE
Additional generic types in constructors

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#31360]
It would be nice to have
```
Map.fromIterable<T>(Iterable<T> iterable, {K key(T element), V value(T element)});
```
Rather than
```
Map.fromIterable(Iterable iterable, {K key(element), V value(element)});
```
Since it takes out some very useful type checking and inference.

**Comment by eernstg** [comment]
This is a known proposal, and likely to happen. The issue created for collecting comments on this idea is here: #30355.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/26392 and https://github.com/dart-lang/sdk/issues/26391
