### ISSUE TITLE
have the analysis server benchmarks support a `--preview-dart-2` flag

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31364]
This would enable the new CFE for the analysis server, and would allow us to do comparison benchmarks between the new and old front-ends.

@bwilkerson @scheglov @sortie

**Comment by devoncarew** [comment]
For this, the analysis server would also need to support a `--preview-dart-2` flag.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/20640

**Comment by devoncarew** [comment]
https://dart-review.googlesource.com/c/sdk/+/20941
