### ISSUE TITLE
Content security violation in load_in_correct_order_test

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31361]
On dart2js-linux-drt-csp-minified-be, the test `dart2js_extra/deferred/load_in_correct_order_test` in configurations `dart2js-drt release_x64` and `dart2js-drt-checked release_x64` has been failing for a while (builds 3176-3183, at least) with the following error message at the core:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src 'self'
```

**Comment by sigmundch** [comment]
Thanks!

I just fixed it by skipping this test in CSP. The code purposely breaks CSP so we have no intention to run it in that configuration.
