### ISSUE TITLE
Nondeterministic results for front_end with test language_2/generic_constructor_mixin3_test

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31368]
I am working on a CL that performs type checking of invocation arguments in the front end, and I'm seeing strange results for the test language_2/generic_constructor_mixin3_test, depending how much of the test suite I run.

If I run `python tools/test.py -m release -c dartk --strong language_2`, then tests `language_2/generic_constructor_mixin3_test/none` and `language_2/generic_constructor_mixin3_test/01` both pass.

If I run `python tools/test.py -m release -c dartk --strong language_2/generic_constructor_mixin3_test`, then test `language_2/generic_constructor_mixin3_test/none` gets a RuntimeError, and `language_2/generic_constructor_mixin3_test/01` gets a CompileTimeError.  I see similar results if I run `python tools/test.py -m release -c dartk --strong language_2/generic_constructor_mixin3_test/none` or `python tools/test.py -m release -c dartk --strong language_2/generic_constructor_mixin3_test/01` directly.

For now I'm going to update the status file to allow both possible outcomes for each test.

**Comment by jensjoha** [comment]
This doesn't seem to be a front-end issue, but rather a test.py issue... I have a fix in flight nonetheless.
