### ISSUE TITLE
Dart:io should use lowerCamelCase for publicly visible constants.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31366]
The Dart style guide recommends lowerCamelCase for constants. Dart platform libraries used to use SCREAMING_CAPS.
The platform libraries are changing to the recommended style for Dart 2.0, and dart:io should do that too.

**Comment by zanderso** [comment]
`dart:io` constants outside of `dart:_http` are updated. Updating `dart:_http` constants is in-progress here: https://dart-review.googlesource.com/c/sdk/+/58620.

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/58620 has landed. Can this be closed?

**Comment by zanderso** [comment]
Yes, I think this is all set.
