### ISSUE TITLE
FutureOr<T> type is transformed by VM into dynamic

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31377]
In ` ClassFinalizer::ResolveTypeClass` we have:

```cpp
  // Replace FutureOr<T> type of async library with dynamic.
  if ((type_class.library() == Library::AsyncLibrary()) &&
      (type_class.Name() == Symbols::FutureOr().raw())) {
    Type::Cast(type).set_type_class(Class::Handle(Object::dynamic_class()));
    type.set_arguments(Object::null_type_arguments());
  }
```

I don't think this is correct treatment for this type in strong mode.

**Comment by crelier** [comment]
My understanding is that, at run time, `FutureOr<T>` is synonym with `dynamic`, whether in strong mode or not. The `FutureOr<T>` type has only a different meaning for the static analyzer, so it should be enough for the VM to map that type to `dynamic` and it is not necessary to preserve the type and adjust the strong mode type tests.
Am I not understanding this correctly?

Here for reference is a quote from the language spec:

> The built-in type declaration FutureOr, which is declared in the library
> dart:async, defines a generic type with one type parameter (14). If the FutureOr
> type, optionally followed by type arguments, is used as a type, it denotes the
> dynamic type. As such, the FutureOr type cannot be used where dynamic
> cannot be used as a type. If the type arguments applied to FutureOr would issue
> static warnings if applied to a normal generic class with one type parameter,
> the same warnings are issued for FutureOr, even though the type arguments are
> otherwise ignored. The name FutureOr as an expression denotes the same Type
> object as dynamic.
> The FutureOr type is reserved for future use, for cases where a value can be
> either an instance of the type type or the type Future<type>. Such cases occur
> naturally in asynchronous code. Using FutureOr instead of dynamic will allow
> some tools to provide a more precise type analysis.

**Comment by mraleph** [comment]
Hmm. I wonder if this is still true in Dart 2.0 I would expect that `FutureOr<T>` has runtime semantics there.

@leafpetersen @lrhn @eernstg can we get clarification what is the semantics of `FutureOr<T>`?

**Comment by lrhn** [comment]
In strong-mode/Dart 2, `FutureOr<T>`  is a type separate from `dynamic`. 
It's a super-type of `T` and of `Future<T>`, and a subtype of `Object`. It's also covariant, so if `S` <: `T`, `FutureOr<S>` <: `FutureOr<T>`.

This allows strong mode to use an occurrence of `FutureOr<T>` to infer the `T`, like in `Future<S> then<S>(FutureOr<S> handler(T value), ...)`.

The `dynamic` meaning was just a way to allow the *syntax* during transition, so the same library code could be used for Dart 1 and DDC (similarly to the ignored type parameters on functions).

**Comment by leafpetersen** [comment]
Yes, `FutureOr` type is reified.  There are no objects of that type, but it is reified as part of other types.  The following test:

```dart
import 'dart:async';

void show<T>() => print(T);
void test1() {
  print("Is checks work");
  show<FutureOr<int>>();
  print(3 is FutureOr<int>);
  print(new Future.value(3) is FutureOr<int>);
  print("hello" is FutureOr<int>);
  print(new Future.value("hello") is FutureOr<int>);
}
void test2() {
  print("FutureOr is reified");
  show<List<FutureOr<int>>>();
  var li = <FutureOr<int>>[];
  var ls = <FutureOr<String>>[];
  print(li is List<FutureOr<int>>);
  print(li is List<FutureOr<String>>);
  print(ls is List<FutureOr<int>>);
  print(ls is List<FutureOr<String>>);
}
void main() {
  test1();
  test2();
}
```

gives the following output on DDC:

```dart
Is checks work
FutureOr<int>
true
true
false
false
FutureOr is reified
List<FutureOr<int>>
true
false
false
true
```

**Comment by crelier** [comment]
Thanks for the clarification. I guess I was looking at an outdated spec.
It would be great to commit that test.

**Comment by leafpetersen** [comment]
@crelier I'll follow up with you off line about spec and tests.

**Comment by eernstg** [comment]
[Spec update](https://dart-review.googlesource.com/c/sdk/+/25301) upcoming.
