### ISSUE TITLE
Crashes on vm app_jit.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31376]
FAILED: app_jit-vm debug_x64 language/issue23244_test
Expected: Pass
Actual: Crash

FAILED: app_jit-vm debug_x64 lib_2/isolate/compile_time_error_test/none
Expected: Pass
Actual: Crash

Happened since seemingly unrelated change 0b58c4bd10df3f41baa.

**Comment by mraleph** [comment]
Ryan, could you take a look?

**Comment by rmacnak-google** [comment]
We end up with an improperly canonicalized type before snapshotting.

```Instance `Type: (@0x7efd9cbf0a61 H32e00c20) class 'DoubleLinkedQueueEntry', args:[TypeArguments: (415556156) [Type: (@0x7efd9cbf0a91 H378f5536) class 'DoubleLinkedQueueEntry', args:[TypeArguments: (471402404) [TypeRef: DoubleLinkedQueueEntry<...> (@0x7efd9cbf0a91 H378f5536)] [TypeParameter: name E; index: 1; class: _DoubleLinkedQueueEntry@3220832; bound: Object]]] [TypeParameter: name E; index: 1; class: _DoubleLinkedQueueEntry@3220832; bound: Object]]` is not canonical!```
