### ISSUE TITLE
Add a bigint class to dart:core

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31382]
Since dart is moving to 64-bit integers, we should add a bigint class to dart:core.

Would also fix #10245.

**Comment by matanlurey** [comment]
Related: https://github.com/tc39/proposal-bigint.

**Comment by lrhn** [comment]
The `BigInt` class has landed. It works in both JavaScript and native, so code can start using it.
It's not platform optimized yet.
See: https://dart-review.googlesource.com/29593
