### ISSUE TITLE
test.dart should pass --strong to the dart-precompiled runtime

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31385]
It appears that the --strong flag is not plumbed through when invoking the dart_precompiled runtime.

For example:
```
./tools/test.py -m release -c dartkp --strong corelib_2/iterable_generate_test
```

fails for this reason.

/cc @mraleph @whesse

**Comment by alexmarkov** [comment]
@crelier, it looks like this was fixed in your CL: https://github.com/dart-lang/sdk/commit/a38ac7cf127f4611c873c2f2d523c06ce06b1342.

**Comment by crelier** [comment]
Yes, this is exactly what I noticed yesterday. Siva provided the fix and I updated the status files in the cl you are referencing. Closing.
