### ISSUE TITLE
port dart2js Utf8Decoder acceleration to DDC 

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#31393]
dart2js commit: https://github.com/dart-lang/sdk/commit/3836c70a8150bc33a695788deee346b940b40769

If the following changelog entry is committed, update from 'dart2js' to 'JavaScript': https://dart-review.googlesource.com/c/sdk/+/21526

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/54529
