### ISSUE TITLE
Failed to create server socket

### ISSUE THREAD

**Issue by liupeng110** [dart-lang/sdk#31399]
essHandle, int *, base::TimeDelta)
Done. Made 4940 targets from 995 files in 11096ms
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$ ./buildtools/ninja -C out/debug-x86-64
ninja: Entering directory `out/debug-x86-64'
out/debug-x86-64
[918/22252] ACTION //third_party/dart/runtime/observatory:pub_build_observatory(//build/toolchain/fuchsia:x64)
FAILED: observatory/build/web/main.dart.js
/usr/bin/env ../../third_party/dart/tools/observatory_tool.py --sdk=True --silent=True --directory /mnt/g/ijk/fuchsia/code/fuchsia/out/debug-
x86-64/gen/observatory_copy/third_party/dart/runtime/observatory/ --command build /mnt/g/ijk/fuchsia/code/fuchsia/out/debug-x86-64/observator
y/build
Command failed: /mnt/g/ijk/fuchsia/code/fuchsia/third_party/dart/tools/sdks/linux/dart-sdk/bin/dart /mnt/g/ijk/fuchsia/code/fuchsia/third_par
ty/dart/tools/sdks/linux/dart-sdk/bin/snapshots/pub.dart.snapshot build -DOBS_VER=2.0.0-edge --output /mnt/g/ijk/fuchsia/code/fuchsia/out/deb
ug-x86-64/observatory/build
output: Failed to create server socket (OS Error: Address already in use, errno = 98), address = ::1, port = 53234

ERROR: Observatory failed to build. What should you do?

1. Revert to a working revision of the Dart VM
2. Contact zra@, rmacnak@, dart-vm-team@
3. File a bug: https://github.com/dart-lang/sdk/issues/new

[923/22252] CXX obj/third_party/dart/runtime/lib/libdart_lib_nosnapshot_with_precompiler.regexp.o
ninja: build stopped: subcommand failed.
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$ out/debug-x86-64
bash: out/debug-x86-64: Is a directory
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$

**Comment by liupeng110** [comment]
bash: out/debug-x86-64: Is a directory
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$

**Comment by liupeng110** [comment]
in  windows 10 ‘s child  linux

**Comment by liupeng110** [comment]
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$ cat /proc/version
Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014
zhang@LP:/mnt/g/ijk/fuchsia/code/fuchsia$

**Comment by vsmenon** [comment]
@zanderso @rmacnak-google - fyi

**Comment by zanderso** [comment]
`pub build` is setting up a server to listen on ipv6 loopback on port 53234, and it is failing because the port is already in use.

@liupeng110 was this a transient failure, or does this happen every time?

**Comment by liupeng110** [comment]
I upgraded my operating system to Ubuntu 16.04  LTS

**Comment by liupeng110** [comment]
I think that is why I am making mistakes

**Comment by liupeng110** [comment]
At Ubuntu 14.04.5 LTS, the ifconfig command can not be used

**Comment by rmacnak-google** [comment]
@munificent Why does `pub build` open a server socket at all?

**Comment by liupeng110** [comment]
This port is random   eg 53234  51352   36212 ...

**Comment by munificent** [comment]
Pub needs to dynamically load the user's transformers. It does that by spawning isolates and loading them into those. The code for those transformers may itself be dynamically modified by previous transformers, so pub uses an HTTP URI as the entrypoint and serves up the code for the transformers from its own internal server.

(Also, at the time we wrote this, there was no way to even control the package root directory the VM used to load code into isolates. Without using HTTP, the spawned isolate would try to resolve "package:" URIs relative to *the pub application itself* instead of within the user's package.)

cc @nex3
