### ISSUE TITLE
Crash in Flutter app

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31403]
I was writing a simple demo app. The app allows the user to press buttons and adds text to a Text widget in response. I can't provide a way to replicate the state because I had done at least one hot-reload, but don't know what changed. Below is the content of the Console view in IntelliJ. The app was being run on a Pixel XL.

```
Performing hot reload...
Reloaded 1 of 467 libraries in 1,055ms.
I/zygote  (16941): Do partial code cache collection, code=30KB, data=29KB
I/zygote  (16941): After code cache collection, code=30KB, data=29KB
I/zygote  (16941): Increasing code cache capacity to 128KB
F/libc    (16941): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 17061 (ui_thread)
I/Choreographer(16941): Skipped 34 frames!  The application may be doing too much work on its main thread.
Application finished.
```

**Comment by a-siva** [comment]
Is it possible for you to see if this replicates again for you and then maybe give us your demo app and steps you did to replicate the problem.

**Comment by natebosch** [comment]
Given how long we've gone without a repro I don't think this issue retains it's value. Feel free to reopen if we have enough information to investigate.
