### ISSUE TITLE
Error recovery for invalid assignment produces mal-typed kernel code

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31417]
I will shortly be making a change to how the front end handles invalid assignments.  Consider:

```dart
f(int x) {
  String y;
  var z = y = x; // Invalid assignment of x (an int) to y (a String)
}
```

With the change, the type of `z` will be inferred as `int` (consistent with the informal type inference spec), but the kernel code generated will be equivalent to `int z = y = (x as String)`.  Although in practice this will not lead to soundness problems (since the only `int` value that will pass the "as" check is `null`, and `null` is safe to assign to `z`), technically this is mal-typed kernel code, since `x as String` has type `String`, which is not assignable to `int`.

The error recovery logic needs to be changed to explicitly throw an exception; since the type of a `throw` expression is `Bottom`, this will be properly typed.

**Comment by jensjoha** [comment]
The provided example code now produce the following kernel (in strong mode):

```
library;
import self as self;
import "dart:core" as core;

static method f(core::int x) → dynamic {
  core::String y;
  core::int z = y = let final dynamic #t1 = x in let dynamic _ = null in invalid-expression "tmp.dart:3:15: Error: A value of type 'dart.core::int' can't be assigned to a variable of type 'dart.core::String'.\nTry changing the type of the left hand side, or casting the right hand side to 'dart.core::String'.\n  var z = y = x; // Invalid assignment of x (an int) to y (a String)\n              ^";
}
```

So it appears that this issue can be closed. Any objections?

**Comment by stereotype441** [comment]
No objection from me.
