### ISSUE TITLE
Intent to implement: `noSuchMethod` forwarding methods.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31426]
In Dart 2, the semantics of `noSuchMethod` will include generated forwarding methods. For the details, please consult the informal specification [nosuchmethod-forwarders.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/nosuchmethod-forwarding.md).

Note that some discussions leading up to this feature can be found here: #30140.

## Action items

In general, all implementations will receive support for this feature from the common front end. In `dartdevc`, the specified approach has been in effect for a while, and only minor adjustments will be needed, if any. Hence we only have the following subtasks:

- [x] Common front end (#31424).
- [x] dartdevc (#31425).

**Comment by natebosch** [comment]
The linked CFE issue is closed and AFAIK this is implemented and working everywhere.
