### ISSUE TITLE
Common front end: `noSuchMethod` forwarding methods.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31424]
This is the front end specific issue for #31426, which has the details.

**Comment by alexmarkov** [comment]
/cc @kmillikin @mraleph 

FYI: CHA-based devirtualization of method calls (in precompiler) relies on the presence of the forwarding methods for noSuchMethod().

```dart
abstract class Interf {
  void foo();
}
class A implements Interf {
  void foo() { ... }
}
class B implements Interf {
   noSuchMethod(Invocation i) { ... }
}

Interf ii = new B();

ii.foo();
```

Without forwarding method foo() -> noSuchMethod() in B, devirtualization incorrectly discovers that the only implementation of Interf.foo() is in A and replaces ii.foo() with direct call to A.foo().

**Comment by kmillikin** [comment]
I will implement this, and then remove the special handling in the DDK back end.

**Comment by eernstg** [comment]
The document [nosuchmethod-forwarding.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/nosuchmethod-forwarding.md) has been under discussion for a while. It has been landed just now. The main change is clarification, and I believe that it should be easier to read now, but the changes **should not affect the implementation** (it now talks about 'induced' forwarding methods corresponding to 'implicitly forwarded method signatures' of a class relative to its interface, and the dynamic semantics gets simpler because there is no notion of generating anything, the methods "are just there all the time", just like 'induced' getters and setters corresponding to variable declarations).

**Comment by vsmenon** [comment]
This is now blocking an internal flutter test.

**Comment by sjindel-google** [comment]
After discussion with Regis and Slava, it appears that this feature should be implemented primarily in the VM, re-using the existing "no-such-method" dispatching machinery.

What we need from the CFE is that each abstract method that needs a forwarding implementation be marked with a specific bit indicating this.

**Comment by sjindel-google** [comment]
I've created #32628 to track the VM implementation of this feature.

**Comment by sjindel-google** [comment]
We also need the CFE to add/ensure corresponding abstract methods exist in each class where the stubs need to be added. E.g.:

```dart
class C {
void foo();
}

class D implements C {
dynamic noSuchMethod(...) {}
}
```

CFE needs to add an abstract method for `foo` to `D` with this bit set.

**Comment by sjindel-google** [comment]
There are a few remaining bugs, but overall the feature is complete.
