### ISSUE TITLE
run  fuchsia.sh  error  

### ISSUE THREAD

**Issue by liupeng110** [dart-lang/sdk#31432]
log------
zhang@lp:/mnt/g/ijk/fuchsia/code$ ./fuchsia.sh
: not foundh: 2: ./fuchsia.sh: clear
: not foundh: 3: ./fuchsia.sh:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libsdl1.2-dev' instead of 'libsdl-dev'
E: Unable to locate package build-essential
: not foundh: 8: ./fuchsia.sh:
mkdir: cannot create directory ‘/mnt/g/ijk/fuchsia/code/fuchsia\r’: No such file or directory
mkdir: cannot create directory ‘/mnt/g/ijk/fuchsia/code/fuchsia\r’: No such file or directory
mkdir: cannot create directory ‘/mnt/g/ijk/fuchsia/code/fuchsia\r’: No such file or directory
./fuchsia.sh: 11: cd: can't cd to fuchsia
ERROR: cannot find .jiri_root
ERROR: jiri: unknown command "update\r"

Command jiri is a multi-purpose tool for multi-repo development.

**Comment by lrhn** [comment]
This seems like a Fuchsia related issue, not Dart. I'm not sure which Fuchsia project this would belong to, but check where you received the Fuchsia code from and file an issue there.

**Comment by zanderso** [comment]
There is no fuchsia.sh in the Dart or Fuchsia repos. Maybe it would be better to try to get help with what you're trying to do on Fuchsia's IRC channel?
