### ISSUE TITLE
ddc makeGenericType crash on 2.0.0-dev.8.0 and earlier

### ISSUE THREAD

**Issue by spebbe** [dart-lang/sdk#31434]
Hi! Attached is a minimal project that runs fine in the dart vm and dart2js, but fails at run time with:
```
require.js:143 Uncaught ReferenceError: L is not defined
    at dartz.Either$.dart.generic.Either (either.dart:28)
    at Object.makeGenericType [as Either$] (dart_sdk.js:sourcemap:3751)
    at either.dart:28
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

‘L’ is most likely referring to the first type parameter on Either<L, R>, source code at: https://github.com/spebbe/dartz/blob/0.7.1/lib/src/either.dart

This is in 2.0.0-dev.8.0, straight forward 'pub serve' + chrome 62. It fails in the same and/or various other ways with older versions of the sdk/ddc, including 1.24.2.

All referenced sources are strong mode clean according to the analyzer.

UPDATE: Forgot to attach example project originally...

[either_problem.tar.gz](https://github.com/dart-lang/sdk/files/1495363/either_problem.tar.gz)

**Comment by vsmenon** [comment]
This is sufficient to demonstrate the problem:

```
class TraversableOps<L, R> {
}

class Either<L, R> extends TraversableOps<Either<L, Object>, R> {
}

void main() {
  var either = new Either<int, String>();
  print(either.runtimeType);
}
```

**Comment by vsmenon** [comment]
This is the corresponding snippet of generated code:
```
either.Either$ = dart.generic((L, R) => {
  class Either extends either.TraversableOps {}
  (Either.new = function() {
  }).prototype = Either.prototype;
  dart.addTypeTests(Either);
  Either.prototype[_is_Either_default] = true;
  return Either;
}, Either => {
  dart.setBaseClass(Either, either.TraversableOps$(either.Either$(L, core.Object), R));
});
```

The problem is in the call to `setBaseClass`.  I think we need to thread through the type params:

```
(Either, L, R) => {
  dart.setBaseClass(Either, either.TraversableOps$(either.Either$(L, core.Object), R));
}
```
