### ISSUE TITLE
[kernel] DispatchCategories are not preserved by the Cloner

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31438]
The cloner (`clone.dart`) doesn't copy over the `DispatchCategory` for `PropertyGet`, `PropertySet` and `MethodInvocation`.

This could cause transformation to unnecessarily convert the dispatch categories on some nodes to `DynamicDispatch`, resulting in performance regressions.

**Comment by stereotype441** [comment]
This is my mistake and I'm willing to look into this, but the kernel team is more familiar with the cloner and I'm currently trying to finish implicit downcast insertion ASAP.  Someone on the kernel team may be able to fix it a lot sooner than I can.

**Comment by sjindel-google** [comment]
I'm happy to make the change, but before I do, are there any other related AST changes that weren't updated in the cloner which I should address as well?

**Comment by stereotype441** [comment]
Looking through the changes I've made to `pkg/kernel/lib/ast.dart`, it looks like there are.  These commits all add fields to ast.dart and fail to update clone.dart:
- dca8a9acf5d7dd37a3a1653c349eea91dd42cc13
- 9a0e962e674a3fac9baefde046882456bdf4f0a8
- a811daca97943df3524002e3135398fbdfc385d8
- 034a8f37a4acf4562e8c73948693bacae6bed683
- 1c57563a315cca4f9ff0cde727f6574f546f4309

I'm really sorry about this--I didn't realize clone.dart needed to be updated.

**Comment by sjindel-google** [comment]
No worries. I have my own list of files to update when I change `ast.dart`, but we should definitely document it somewhere, and write tests as much as possible. For example, we could test that the cloner is kept up to date by testing that `serialize(clone(deserialize(X))) = X`.
