### ISSUE TITLE
Kernel PropertySet node doesn't have a DispatchCategory.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31437]
The `PropertySet` node needs to have a dispatch category associated with it (like `MethodInvocation`) so backends can determine when they need to check the argument.

Of course, the FE also needs to populate this field appropriately. I've added "P1: high" because this is partially blocking #31312.

**Comment by stereotype441** [comment]
Note from IM discussion: @sjindel-google is planning to add the property to `PropertySet`.  Then he will turn over the bug to me to add the front end code that populates it.

**Comment by sjindel-google** [comment]
I've added the property.
