### ISSUE TITLE
io.InternetAddress.type spec is incorrect

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31433]
Dart API Specification reads about the io.InternetAddress.type:

`InternetAddressType type read / write The type of the InternetAddress specified what IP protocol.`

However, actually this is a read-only field which cannot be modified.

Definitely, this is a error is Spec and it should be a getter like the `InternetAddress.address` field.

**Comment by natebosch** [comment]
It no longer says "read / write".
https://api.dartlang.org/stable/2.0.0/dart-io/InternetAddress/type.html
