### ISSUE TITLE
I'd like more user friendly VM stack traces

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31447]
The patched-nature of the VM SDK/Runtime is less-than-user-friendly.

For example, here is a stack trace I hit debugging Flutter (https://github.com/flutter/flutter/issues/13190):

```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#9      _Future._completeWithValue (dart:async/future_impl.dart:478)
#10     Future.wait.<anonymous closure> (dart:async/future.dart:392)
#11     _rootRunUnary (dart:async/zone.dart:1128)
#12     _CustomZone.runUnary (dart:async/zone.dart:1012)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#16     _Future._complete (dart:async/future_impl.dart:468)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#19     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:30)
#21     _rootRunUnary (dart:async/zone.dart:1128)
#22     _CustomZone.runUnary (dart:async/zone.dart:1012)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#24     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#25     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#26     _Future._complete (dart:async/future_impl.dart:468)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
```

I realize you can use `package:stack_trace`, but it would be nice to agree on some sort of shared experience for VM and Web, and remove the need to wrap everything in another package/zone just to get easier-to-read stack traces.

**Comment by lrhn** [comment]
Can you be more precise about what you are asking for?
Do you just want to omit the private methods from the SDK, or also the public methods on private SDK classes (that's probably too much), or something else entirely?

For comparison, just removing private methods gives you:
```
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5     Future.wait.<anonymous closure> (dart:async/future.dart:392)
#6     _CustomZone.runUnary (dart:async/zone.dart:1012)
#7     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#9     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#11     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
#12     _rootRunUnary (dart:async/zone.dart:1128)
#13     _CustomZone.runUnary (dart:async/zone.dart:1012)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51)
```

**Comment by matanlurey** [comment]
That's definitely a good start. I might even suggest removing private classes from the SDK?

```
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      Future.wait.<anonymous closure> (dart:async/future.dart:392)
#4     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
```

**Comment by lrhn** [comment]
Removing all the private classes would probably be confusing - there is no connection between those four entries, it's incredibly hard to figure out what's going on. Even if it might make a little sense here, other situations would loose all context. 
Private classes may be the actual classes you are interacting with (`_GrowableList`, `_Future`, `_SyncCompleter` are all objects that the user is directly interacting with). It would be bad if `_GrowableList.forEach` was missing when you do `[1,2,3].forEach(doSomething)`. 

Another approach, one I actually implemented in V8 at some point, is to only show the *first* SDK method that is called from a non-SDK method, and not any SDK method called from from another SDK method. That is, show only the user/SDK boundary, not what goes on inside the SDK. We could also drop initial SDK frames (when called from the system).
For the original stack trace, that would yield:
```
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
#4      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#5      Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
```
(I find it somewhat suspicious that a package calls a private SDK method directly, I'm assuming it's rewritten `async` magic).

**Comment by matanlurey** [comment]
@lrhn:

> Removing all the private classes would probably be confusing - there is no connection between those four entries, it's incredibly hard to figure out what's going on. Even if it might make a little sense here, other situations would loose all context. 

Yeah it's a silly idea, but it looked it work _above_. I realize it falls apart in other places.

> Private classes may be the actual classes you are interacting with (`_GrowableList`, `_Future`, `_SyncCompleter` are all objects that the user is directly interacting with). It would be bad if `_GrowableList.forEach` was missing when you do `[1,2,3].forEach(doSomething)`. 

Yeah I hear you. I actually think your idea/implementation below fixes this for me anyways.

> Another approach, one I actually implemented in V8 at some point, is to only show the *first* SDK method that is called from a non-SDK method, and not any SDK method called from from another SDK method. That is, show only the user/SDK boundary, not what goes on inside the SDK. We could also drop initial SDK frames (when called from the system).

❤️ this. I _think_ this is what `pkg/stack_trace` does (/cc @nex3), but I'm not 100% sure.

> For the original stack trace, that would yield:
> ```
> #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
> #2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
> #3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
> #4      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
> #5      Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
> ```

Yup, this is much better for most users.

> (I find it somewhat suspicious that a package calls a private SDK method directly, I'm assuming it's rewritten `async` magic).

You're probably right. I wonder if just making or rewriting or those a bit would help, i.e.:

```
> #4      await
```

**Comment by nex3** [comment]
> ❤️ this. I _think_ this is what `pkg/stack_trace` does (/cc @nex3), but I'm not 100% sure.

`stack_trace` does basically this in terse mode, yeah. We also fold together frames from the `stack_trace`, and we provide an API for users to customize exactly which frames are folded.

**Comment by rmacnak-google** [comment]
The Dart standard rightly requires StackTrace.toString() to report function activations exactly: no omitted frames, no synthetic frames, no obfuscation, and precise source locations. The base stack traces should not be lossy.
