### ISSUE TITLE
Analysis server suggests non-Dart files as imports

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31448]
Copied from https://github.com/Dart-Code/Dart-Code/issues/452#issuecomment-346705346.

Simple reproduction is type `import 'package:flutter/`, and wait for auto-complete.

<img width="596" alt="screen shot 2017-11-23 at 2 10 26 pm" src="https://user-images.githubusercontent.com/168174/33189520-49cf06ec-d058-11e7-99cd-675fd9d96845.png">

... I imagine anything but a `.dart` file will never succeed, so why suggest it?

**Comment by devoncarew** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/23700.
