### ISSUE TITLE
DDC-generated is-checks have wrong outcome for generic function types

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#31455]
The following test throws a run-time error for dartdevc.

```dart
import 'package:expect/expect.dart';

typedef int Foo<T>(T a, [String b]);

int foo(bool a, [String b]) => null;

main() {
  Expect.isFalse(foo is Foo, 'foo is Foo');
}
```

**Comment by stefantsov** [comment]
Related CL: https://dart-review.googlesource.com/c/sdk/+/23676

**Comment by leafpetersen** [comment]
This is currently "as intended" but soon to be deprecated behavior.  See here for details: https://github.com/dart-lang/sdk/issues/29630 .

You can work around it for now if needed by using `Foo<Object>` instead of `Foo` (which is implicitly `Foo<dynamic>`.
