### ISSUE TITLE
js-interop: class call() integration

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#31452]
As questioned [here at StackOverflow](https://stackoverflow.com/questions/47466943/jquery-and-dart-interop-with-call) i'm wondering how to achieve a jQuery interop both with _jQuery("#id")_ and _jQuery.fn.pluginX_ with a call() method.
Did my best trying but doesn't seems to be achievable
In case it isn't what about adding that to the js-interop API?

**Comment by dgrove** [comment]
This was answered in the same SO thread.
