### ISSUE TITLE
switch flutter runtime to use a core snapshot in kernel mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31457]
Currently we ship a vm_platform.dill file alone with the flutter runtime, we should switch flutter runtime to include a core snapshot in the executable in kernel mode too and drop vm_platform.dill in the set of files sent over to the device.

**Comment by a-siva** [comment]
This has not happened yet,  we are gated on the restructuring that @chinmaygarde is doing to the engine code, moving milestone to 2.0-alpha-2

**Comment by rmacnak-google** [comment]
https://github.com/flutter/engine/commit/60bb5da33c72ac91d4ec7033a9d72fdcdf4c8450
