### ISSUE TITLE
DDC: Browser event listeners receive JSObject<CustomEvent>' instead of Event

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#31454]
This is a bug I haven't seen before, but unfortunately it's preventing any further development of my application.

I'm using `package:angel_client/browser.dart`, which has an `authenticateViaPopup` method that calls `window.on['token']`, the subscription to which is assigned to a variable as follows:

```dart
var wnd = window.create(...);
StreamSubscription<Event> sub = wnd.on['token'].listen(...);
```

However, when the event is fired, I get the following error:

```
Type 'JSObject<CustomEvent>' is not a subtype of type 'Event'
```

There is no workaround I have been able to find. I'm running Dart SDK 1.24.2.

**Comment by matanlurey** [comment]
Have you tried `addEventListener` instead? @thosakwe (as a work around)

**Comment by thosakwe** [comment]
Thanks for the suggestion, Matan. Unfortunately, I get the same result both ways.

**Comment by thosakwe** [comment]
I wasn't able to resolve this (besides, I'm using 1.24.2, so there's not so much of way to fix this, is there?).

However, I found a workaround. Instead of opening a separate browser window for OAuth, I redirect the user to the OAuth page, and then after creating a JWT on the server side, send them to a route `/token?token=<the jwt>` in my Angular app. Works perfectly well, and is simple.
