### ISSUE TITLE
Can't deprecate enum values

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#31460]
We recently found ourselves wishing to rename an enum value, and planned to deprecate the old value while simultaneously introducing the new value.

```dart
enum Values {
  @Deprecated('Use Values.bar')
  foo,
  bar,
}
```
Unfortunately, it appears as though the `Deprecated` annotation isn't supported on enum values, and the above example yields the following error
```
Enum constants can't have annotations.
```
What's the reasoning or technical limitation preventing this? Could we see support for this?

**Comment by lrhn** [comment]
I don't think there is a technical problem, it was just never added to the grammar.

We can definitely consider adding it.

**Comment by leonsenft** [comment]
Okay, thanks!

**Comment by eernstg** [comment]
FYI: The required specification update is [currently under construction](https://dart-review.googlesource.com/c/sdk/+/54242).

**Comment by eernstg** [comment]
The specification update has been accepted by the language team (as of 2f781e46b01e22541cd74ab82e57e72bdea3793e).

**Comment by lrhn** [comment]
Blocked on #33082

**Comment by eernstg** [comment]
It should not be blocked, #33082 had no remaining tasks so I just closed it.

**Comment by natebosch** [comment]
Analyzer and other tools don't choke on having the annotation on an enum and the analyzer correctly hints at usage points.
