### ISSUE TITLE
Provide different error codes for transient failures vs consistent failures

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#31465]
Currently pub provides the same error code (69) for networking failures (which can be transient, and thus retried) and consistent failures (such as incorrect paths, unreadable files, etc.). It would be much preferred to have a separate code for the latter.

Upstream Flutter issues: https://github.com/flutter/flutter/issues/13178

**Comment by mit-mit** [comment]
cc @nex3

**Comment by nex3** [comment]
The [exit code schema](http://www.freebsd.org/cgi/man.cgi?query=sysexits) we use doesn't draw a distinction between "transient" and "consistent" failures, but I think it does make sense to use exit code 66 ("An input file did not exist or was unreadable") when a path dependency doesn't exist.

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub#1747
