### ISSUE TITLE
dart2js: possible bug in RTI for type variables

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31471]
```dart
class A<T> {
  Type get type => T;
}

class C {}
class D {}

class B extends A<D> {}

main() {
  print(new A<C>().type);
  // print(new A<D>().type);
  print(new B().type);
}
```

This program prints "C and D" in the VM, but "C" and "dynamic" in dart2js. If we comment out the middle line, it prints "C, D, D" in both.

**Comment by karlklose** [comment]
Could you diff the output when the line is commented out and when not? Maybe we forget to emit class `D` in the first case, so that the constructor is `null`, which is interpreted as `dynamic`.

**Comment by joshualitt** [comment]
I believe this is fixed on TOT. Please reopen if it is still an issue.
