### ISSUE TITLE
dartanalyzer doesn't report error to ddc on internal library import

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31473]
The following works right now in DDC:

```
import "dart:_internal";
main() =>  print(POWERS_OF_TEN);
```

but should trigger this error:

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/error/error.dart#L139

This is not in the list of errors given to DDC via the analyzer:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/module_compiler.dart#L198

If I run the analyzer normally (dartanalyzer on the snippet above), the error is reported.

I suspect this is an analyzer build mode issue, but not sure.  

Low priority, as we hope to deprecate this path soon.

**Comment by srawlins** [comment]
DDC no longer uses analyzer.
