### ISSUE TITLE
HttpClient.addCredentials() doesn't add authorization to HTTP request

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31476]
In the code below I call addCredential() before sending HTTP request, but on server side request desn't have Authorisation header

```dart
import "dart:io";
import "dart:convert";

main() async {
  var localhost = InternetAddress.LOOPBACK_IP_V4.address;

  String helloWorld = "Hello test world!";
  HttpServer server = await HttpServer.bind(InternetAddress.LOOPBACK_IP_V4, 0);
  server.listen((HttpRequest request) {
    print(request.headers); // user-agent: Dart/2.0 (dart:io)
                            // accept-encoding: gzip
                            // content-length: 0
                            // host: 127.0.0.1:54956
    request.response.write(helloWorld);
    request.response.close();
    server.close();
  });

  HttpClient client = new HttpClient();
  client.addCredentials(Uri.parse("http://${localhost}:${server.port}/xxx"),
      "realm", new HttpClientDigestCredentials("co19-test", "password"));

  client.getUrl(Uri.parse("http://${localhost}:${server.port}/xxx"))
      .then((HttpClientRequest request) {
    return request.close();
  }).then((HttpClientResponse response) {
    response.transform(UTF8.decoder).listen((content) {
    });
  });
}
```

`HttpClient.addCredentials()` works only if called from `HttpClient.authenticate=` callback. But in this case client sends to the server unauthorised request, server processes unauthorized requests, sets AUTHORIZATION_REQUIRED header, sends response to the client, after that, on client side, `authenticate` callback is called and authorisation is sent to the server. Why, `HttpClient `doesn't sent authorization at once if `addCredentials()` was called before sending HTTP request?

If the current behaviour is intended, then, please, add it to the `HttpClient.addCredentials()` documentation

**Comment by sgrekhov** [comment]
Sorry, I fugured out the problem. I used HttpClientDigestCredentials instead of HttpClientBasicCredentials in addCredentials call. Updated code works.

**Comment by dazza5000** [comment]
I am not seeing the credentials being added on the first request. Did you get yours to work with postUrl?
