### ISSUE TITLE
io.IOSink.addStream method specification is incomplete

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31478]
Dart API Spec reads about the dart:io IOSink.add(List<int> data) method:
`This function must not be called when a stream is currently being added using addStream.`
Indeed, calling `add` method after `addStream` causes `BadStateError`.
However, the same is true for two `addStream` calls as well: if I call `addStream` twice in the code, `BadStateException` occurs as well.
I believe, Spec should reflect it in `addStream` method description also.

**Comment by anders-sandholm** [comment]
@zanderso @a-siva

**Comment by lrhn** [comment]
Good point. You can't add anything while adding a stream, and yes, that includes another stream. It should say that.
