### ISSUE TITLE
dart --version prints the version to stderr instead of stdout

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#31481]
We are improving the output of flutter doctor and run into this interesting issue. 

Given that the intended use of --version is the actually print the version, I would think stdout should be used. Thoughts?

**Comment by ZichangG** [comment]
May I ask the reason of using stdout instead of stderr? What issue do you have?

**Comment by mehmetf** [comment]
Not a blocker. I filed this for two reasons:

- Why would version be printed stderr? Especially if I asked for the version. It doesn't make much sense.
- We can't use standard process utils to parse the output and ended up creating this:

```dart
      final ProcessResult result = processManager.runSync(<String>[dartSdkBin.path, '--version']);
      // https://github.com/dart-lang/sdk/issues/31481
      // We can use the process utils directly when this is fixed instead of parsing stderr.
      _engineDartVersion = result.stderr.trim().replaceAll('Dart VM version: ', '');
```

which is fine but annoying.

**Comment by ZichangG** [comment]
That's a good point. 
But It has been like that since day 1. Now there are many tools relying on this. Switching to stdout would be a breaking change.
