### ISSUE TITLE
Protobuf generation fails when run with front end

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#31480]
Running the [dart-protoc-plugin](https://github.com/dart-lang/dart-protoc-plugin) with the VM+FE fails with the message
--dart_out: protoc-gen-dart: Plugin output is unparseable:

The file lib/src/dart_options.pb.dart this line which hides 'void' from dart:core

///
//  Generated code. Do not modify.
///
// ignore_for_file: non_constant_identifier_names,library_prefixes
library dart_options_dart_options;

// ignore: UNUSED_SHOWN_NAME
import 'dart:core' show int, bool, double, String, List, override;

which could be the issue.

**Comment by kmillikin** [comment]
There are two issues in the front end, both of which need to be fixed:

- Treat `void` as a reserved word (again)

- Add an option to the VM+FE to suppress warnings.  (The API for the protoc plugin is to read from stdin and write to stdout.  The list of warnings produced on stdout can't be understood by protoc.)

**Comment by keertip** [comment]
Kevin, could you make this a priority? I can't continue testing in google3 until this is fixed.

**Comment by keertip** [comment]
Yes, we would want to run the vm with the suppress warnings flag. We have other instances in the internal workflow where the stdout from the cli is used - as in the case of analyzer.

**Comment by kmillikin** [comment]
@lrhn @peter-ahe-google 

This is the issue where `void` is implicitly hidden from `dart:core` by not showing it.

**Comment by kmillikin** [comment]
I have a fix for the first issue, involving the reserved word `void`, here: https://dart-review.googlesource.com/c/sdk/+/24940

The second issue, involving suppressing warnings, still affects the plugin because there are other warnings besides the bogus ones due to `void`.  Unfortunately, I've run out of time to fix that today (expected fix: tomorrow).

**Comment by peter-ahe-google** [comment]
Proposed fix for warnings, [print them on stderr](https://dart-review.googlesource.com/25341).

**Comment by kmillikin** [comment]
I think both of the underlying problems are now fixed.  Please reopen this issue if you see the same or related problems.
