### ISSUE TITLE
[Gardening] Investigate new failures in vm-kernel-precomp

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#31498]
The cl https://dart-review.googlesource.com/24740 caused new failures to be investigated.
See kernel status files referencing this issue.

**Comment by crelier** [comment]
Actually, all failures were caused by passing tests.
Lines in status files have been removed for:
language_2/generic_no_such_method_dispatcher_test
language_2/no_such_method_subtype_test
language_2/mock_writable_final_field_test

They were all refering to issue #31424

**Comment by mraleph** [comment]
That's because these failures were coming from VM specific global transformations enabled via `strong-aot` flag and @kmillikin essentially disabled those transformations. 

@alexmarkov is working on re-enabling them.
