### ISSUE TITLE
Error during refactoring

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31497]
In the attached file (zipped), when trying to rename field `_m` of class `_Classic` to `_modulus` I get the following error.

```
Server error: NoSuchMethodError: The method 'intersects' was called on null.
Receiver: null
Tried calling: intersects(Instance of 'SourceRange')
```

[bigint.zip](https://github.com/dart-lang/sdk/files/1518136/bigint.zip)

**Comment by bwilkerson** [comment]
Was there a stack trace showing where the call is?

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
The problem was "fixed" in https://dart-review.googlesource.com/c/sdk/+/31460, but I was not able to reproduce it. Now I can, thanks!

  Renaming `B.bar` to `foo` triggers the problem.

```dart
class A {
  int foo;

  A(this.foo);
}

class B {
  int bar;

  B(this.bar);

  void referenceField() {
    bar;
  }
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/38100
