### ISSUE TITLE
Crash in VM after 9b7b91ee662b

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31496]
The tests
* language_2/deep_nesting1_negative_test
* language/deep_nesting1_negative_test

crash on ReleaseIA32 on the vm-linux-release-ia32-asan-be bot.

See: [log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-release-ia32-asan-be%2F11341%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout) and [log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-release-ia32-asan-be%2F11341%2F%2B%2Frecipes%2Fsteps%2Fchecked_vm_tests%2F0%2Fstdout).

I'll land status updates as `Crash, Pass` to avoid figuring out exactly which targets are affected.

**Comment by mraleph** [comment]
These tests are now passing. No marks in status files. Assuming stale issue.
