### ISSUE TITLE
Handling page faults in Dart coroutines

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#31493]
For Dart, we need a single-threaded coroutine scheduler which can multiplex coroutines based on page faults.  Both for Windows and Linux.

https://youtrack.jetbrains.com/issue/KT-21308

**Comment by mraleph** [comment]
Before getting a coroutine scheduler, Dart would need to get coroutiness.

**Comment by unicomp21** [comment]
With async/await, dart does have a form of coroutines.  There needs to be an "awaitable" concept which can handle page faults, re-invoke a scheduler, and continue w/ next coroutine where the data dependency is loaded in memory.  Could be simple as something which sits atop typed arrays, and allows one to await a memory page before looking at it's contents.
