### ISSUE TITLE
Analyzer does not warn on function calls on Object

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31509]
This is the analyzer version of #21938.

For the analyzer, the change should be fairly straightforward: we just need to hardcode the `enableStrictCallChecks` option to `true`.

**Comment by bwilkerson** [comment]
Does `enableStrictCallChecks` have other effects that shouldn't be enabled? Some of the comments (https://github.com/dart-lang/sdk/issues/21938#issuecomment-346412797 and https://github.com/dart-lang/sdk/issues/21938#issuecomment-347523847) lead me to think that this would also flag the use of `call` on functions, and that this isn't a desired state.

**Comment by stereotype441** [comment]
@bwilkerson Taking a quick glance through the code, I believe you may be right.  So I guess this task may be a little more involved than just switching on the flag.

**Comment by mit-mit** [comment]
I believe the desired end-state is to remove the `enableStrictCallChecks` flag entirely, and to replace it with this behaviour: https://github.com/dart-lang/sdk/issues/21938#issuecomment-349312598. I asked language folks to confirm.

**Comment by mit-mit** [comment]
The good language folks confirmed that this is the expected behavior:

```dart
void test(dynamic d, Object o, Function f) {
  d(); //# 01: ok
  o(); //# 02: compile-time error
  f(); //# 03: ok
  d.call; //# 04: ok
  o.call; //# 05: compile-time error
  f.call; //# 06: ok
  d.call(); //# 07: ok
  o.call(); //# 08: compile-time error
  f.call(); //# 09: ok
}
```

**Comment by mit-mit** [comment]
Hi @bwilkerson, any update on this issue?

**Comment by stereotype441** [comment]
@mit-mit looking at tests/language_2/language_2_analyzer.status, it looks like the analyzer currently fails test case 2 (it allows `o();` and shouldn't - the test in question is called `object_has_no_call_method_test`).  I've added this to #31638 to make sure it isn't forgotton.  Hopefully either @scheglov or I can get to it soon.

**Comment by stereotype441** [comment]
I'm working on this.

**Comment by stereotype441** [comment]
Reopening issue since the fix was reverted
