### ISSUE TITLE
[Dart 2.0] dart2js compiled Angular app does not report strong-mode type error

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#31512]
### Summary

A Dart 2.0.0-dev.8.0 dartdevc compiled Angular app raises a type error when an `int` is assigned to a(n implicitly) `String` typed field. The same app compiled with dart2js runs fine without any type errors being reported.

I'm **unsure if this is due to a problem with Angular, dart2js** and/or the **dartdevc**. I think it might be due to dart2js, so I'll start by opening the issue here.

### Details

The issue occurs for the Angular **two-way binding example** ([live example][ex], [description][doc]). The example's root app class contains the following [field declaration][fontSizePx]:

```dart
  var /*String|int*/ fontSizePx = '16';
```

This field is used in the [app template][template] as follows:

```html
  <my-sizer [(size)]="fontSizePx" #mySizer></my-sizer>
```

In the two-way binding `[(size)]="fontSizePx"`, when `size` changes inside `my-sizer`, the updated **`int`** value gets assigned to `fontSizePx`.

Under Dart 1.x non-strong mode, this didn't cause any problems because `fontSizePx` was interpreted as `dynamic`.

**It is my understanding that under Dart 2.0, `fontSizePx` has static type `String`** (so I will need to change the declaration from `var` to `dynamic` if the app is to run properly under strong mode). But my point is that the ddc-compiled app reports the type error, but the dart2js-compiled app does not.

I'm assuming that apps compiled with one or the other should have the same behavior.

### Repro

- **Download** a [zip of the site-webdev project from the **5-dev branch**@7381e7792c][5-dev-zip]
- Unzip
- `cd` to the repo root. 
- <code>cd <a href="https://github.com/dart-lang/site-webdev/tree/master/examples/ng/doc/template-syntax">examples/ng/doc/template-syntax</a></code>
- `pub get`

To see the type error:

- `pub serve --web-compiler=dartdevc`
- Open Chrome at [localhost:8080/#two-way](http://localhost:8080/#two-way)
- In Chrome, open the JS console.
- Click either the `[+]` or `[-]` buttons just below the "Two-way Binding" heading.

You should see the following in the console:

```nocode
EXCEPTION: Type 'int' is not a subtype of type 'String' in strong mode
```

with a reference to this line of code:

```js
[_handle_sizeChange_381_0]($event) {
  this.ctx.fontSizePx = core.String._check($event);
}
```

Repeat the steps above but for `pub serve` and no error will be reported.

cc @matanlurey @kwalrath @kevmoo 

[doc]: https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/template-syntax#two-way
[ex]: https://webdev-dartlang-org-dev.firebaseapp.com/examples/template-syntax/#two-way
[fontSizePx]: https://github.com/angular-examples/template-syntax/blob/a36919f12a72ee404cd7b17ed63240a303a9d53a/lib/app_component.dart#L99
[template]: https://github.com/angular-examples/template-syntax/blob/a36919f12a72ee404cd7b17ed63240a303a9d53a/lib/app_component.html#L326
[5-dev-zip]: https://github.com/dart-lang/site-webdev/archive/7381e7792cb1e82344bd76b5a3785ee67430a076.zip

**Comment by chalin** [comment]
Btw, @nshahan, this is the same example app for which `pub build --mode=debug` **sometimes hangs** (https://github.com/dart-lang/angular_components/issues/198). I was going to fix the field type declaration to see if that solved the hanging build problem, but I can't get it to hang anymore :-/.

**Comment by matanlurey** [comment]
There is no strong mode in Dart2JS yet, which is why you don't get any errors.

Only DDC will give you those errors. I'm closing because I don't think there is any other action here other than using a different compiler to get errors and waiting for Dart 2.0 to release.

**Comment by chalin** [comment]
> There is no strong mode in Dart2JS yet ...

Oh! For some reason I thought that there was.

> I'm closing because I don't think there is any other action here other than using a different compiler to get errors and waiting for Dart 2.0 to release.

Yes, that makes sense; I'll use the ddc to debug strong mode errors.

**Comment by chalin** [comment]
> Only DDC will give you those errors.

@kevmoo, @matanlurey: so, under Dart 2-dev, should we only test AngularDart example apps using the DDC? Said another way: is there any reason to run all tests twice (once using dart2js and once using DDC) given that dart2js doesn't implement strong mode?
