### ISSUE TITLE
Is there any order guarantee for Future.then ?

### ISSUE THREAD

**Issue by kezhuw** [dart-lang/sdk#31529]
```dart
import 'dart:async';

void main() {
  Future<String> future = new Future<String>.value('s');
  
  future.then((String s) {
    print("1");
  });

  future.then((String s) {
    print("2");
  });
}
```

[DartPad](https://dartpad.dartlang.org/161eb6282ac3cf0e0a0054bd0b0ee201) Outputs:

```
1
2
```

Is `Future.then` has any means similar to FIFO ? Or this is just a implementation detail which should not be considered as a guarantee ?

I think it would be better a implementation detail, but I found no hit from `Future`'s documentation. If there is documentation related to this situation, please point it out. If not, it would be better to document this situation.

**Comment by lrhn** [comment]
The current implementation does guarantee that the future callbacks are invoked in the order they were added. 

The behavior of adding a calling after the future has completed is very different from callbacks added before the future completes, but they should still happen in the correct order *as long as* microtasks are executed in the order they are scheduled. Since you can override `scheduleMicrotask` in zones, we cannot guarantee order completely.

**Comment by kezhuw** [comment]
Seems that I can conclude to this ?

The execution order of callbacks registered to the same future without chaining is indeterminate.

I think this is the correct choice, after all, we are in asynchronous world.

**Comment by natebosch** [comment]
@lrhn - where do you think is the best place to document this? The `Future` class? `Future.then`?

**Comment by lrhn** [comment]
Probably on `Future` itself. It applies to all of `then`, `catchError` and `whenComplete`. The one thing we do specify is that a future *must not* deliver any result in response to registering a listener, and that we endeavor to deliver the results in a *consistent* order (asynchronous programs are deterministic as long as they do not rely on external delays, including timers, or on deliberate randomness), so executing the same program on the same version of the platform will generally run the same way.

**Comment by alexeyinkin** [comment]
This is documented now: https://github.com/dart-lang/sdk/blob/27479d62bea7f98815413f88f95c238a97de2624/sdk/lib/async/future.dart#L220-L222

**Comment by lrhn** [comment]
Might need a little more tweaking, but let's consider this issue fixed.
