### ISSUE TITLE
Type in in HttpClient.open() documentation?

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31528]
See [HttpClient.open()](https://api.dartlang.org/stable/1.24.2/dart-io/HttpClient/open.html) and [HttpClient.openUrl()](https://api.dartlang.org/stable/1.24.2/dart-io/HttpClient/openUrl.html)

> The Host header for the request will be set to the value host:port. This can be overridden through the HttpClientRequest interface before the request is sent. NOTE if host is an IP address this will still be set in the Host header.

What does NOTE mean? Example below shows how IP address in a host can be overridden

```dart
import "dart:io";
import "dart:convert";

main() async {
  String helloWorld = "Hello test world!";
  HttpServer server = await HttpServer.bind("127.0.0.1", 0);
  server.listen((HttpRequest request) {
    print(request.headers.host); // dartlang.org
    print(request.headers.port); // 111
    request.response.write(helloWorld);
    request.response.close();
    server.close();
  });

  HttpClient client = new HttpClient();
  client.open("get", "127.0.0.1", server.port, "/Xxx")
      .then((HttpClientRequest request){
    request.headers.host = "dartlang.org";
    request.headers.port = 111;
    return request.close();
  }).then((HttpClientResponse response) {
    response.transform(UTF8.decoder).listen((content) {
      print(content); // Hello test world!
    });
  });
}
```
Tested on Dart VM version: 2.0.0-dev.8.0 (Fri Nov 17 14:04:05 2017) on "windows_x64"

**Comment by anders-sandholm** [comment]
I think it just means what it says. I.e., even if the host is an IP address - as opposed to a proper host name like dartlang.org - this will still be set in the Host header. This is independent of the ability to override. 

Maybe swapping sentence 2 and 3 (re override and NOTE) would make the documentation less confusing.
