### ISSUE TITLE
Wrong info in HttpClient.open() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31527]
Please see [HttpClient.open()](https://api.dartlang.org/stable/1.24.2/dart-io/HttpClient/open.html) and [HttpClient.open()](https://api.dartlang.org/stable/1.24.2/dart-io/HttpClient/openUrl.html)

> The Host header for the request will be set to the value host:port

In fact, Host header is set to host and Port header is set to port value. Example
```dart
import "dart:io";
import "dart:convert";

var localhost = InternetAddress.LOOPBACK_IP_V4.address;

main() async {
  String helloWorld = "Hello test world!";
  HttpServer server = await HttpServer.bind(localhost, 0);

  server.listen((HttpRequest request) {
    print(request.headers.host); // 127.0.0.1
    print(request.headers.port); // port value
    request.response.write(helloWorld);
    request.response.close();
    server.close();
  });

  HttpClient client = new HttpClient();
  client.open("get", localhost, server.port, "/Xxx")
      .then((HttpClientRequest request){
    return request.close();
  }).then((HttpClientResponse response) {
    response.transform(UTF8.decoder).listen((content) {
      print(content); // Hello test world!
    });
  });
}
```
Tested on Dart VM version: 2.0.0-dev.8.0 (Fri Nov 17 14:04:05 2017) on "windows_x64"

**Comment by natebosch** [comment]
Note that `request.headers.port` is "the port part of the 'host' header for the connection."

This is being split on the receiving end, not the sending end.

https://api.dartlang.org/stable/2.0.0/dart-io/HttpHeaders/port.html

I think this was just a misunderstanding of behavior.
