### ISSUE TITLE
cinterop tool for strong mode dart

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#31524]
Kotlin has it, dart should have it as well.  Having such a tool would also be huge for the flutter team in that objective-c and android interop could be generated.

**Comment by anders-sandholm** [comment]
@mit-mit @mravn-google

**Comment by unicomp21** [comment]
Forgive the off-topic, thought this was useful too ...
https://github.com/dart-lang/sdk/issues/31493

**Comment by mit-mit** [comment]
This is bug https://github.com/flutter/flutter/issues/7053 on the Flutter side. If this is important to you, please consider adding a 'thumbs-up' on the topmost comment in that bug.

**Comment by parlough** [comment]
Closing this in favor of https://github.com/dart-lang/sdk/issues/34452 which is now also closed as Dart now has FFI and C interop support, as well as experimental support for [Objective-C](https://dart.dev/interop/objective-c-interop). You can find an overview at https://dart.dev/interop/c-interop.

Thanks all! If you'd like to see further improvements, check out the https://github.com/dart-lang/sdk/labels/library-ffi label for currently tracked work or open a new issue :)
