### ISSUE TITLE
Fasta doesn't handle function type variables with generic bounds

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#31531]
Fasta doesn't handle function type variables with generic bounds:

`typedef F = void Function<T extends List<int>>();`

Reports (weird) errors about `void` not allowed and expected `;` after `void` and more....

**Comment by peter-ahe-google** [comment]
Dan, this is probably a bug in parseType.

**Comment by danrubel** [comment]
This has been fixed.
