### ISSUE TITLE
Support configuring package resolution in FE

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31549]
In build systems like bazel, the analysis server used within the IDE needs to customize package resolution rules. This customization cannot be done by creating a .packages file because we cannot list all the possible packages that the user may need.

Analyzer in the past achieved this by creating custom package-uri translation rules. I believe we could achieve a similar result by letting clients of the FE specify a [Packages][1] object as an option (instead of just a .packages file).

[1]: https://github.com/dart-lang/package_config/blob/master/lib/packages.dart#L19

**Comment by dgrove** [comment]
@sigmundch were there any updates to this?

**Comment by sigmundch** [comment]
No - however, I don't believe this is needed for 2.0 at this time. 

It is needed for integrating analysis server with the FE in an IDE in bazel, which is a goal a bit further down. I've updated the milestone.

**Comment by dgrove** [comment]
Because the Analyzer FE won't be replaced by CFE in Q2, removing from the 2.0 milestone.

**Comment by sigmundch** [comment]
(closing as obsolete)
