### ISSUE TITLE
Need a script to kernel-compile and VM-run strong mode Dart scripts

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#31544]
Followup to https://github.com/dart-lang/sdk/issues/31534#issuecomment-349250440.

cc @kwalrath @kevmoo 

This probably should be attached to a meta/planning issue, but I can't find one atm.

**Comment by munificent** [comment]
I'm going to close this out because I assume we don't need it now that the VM uses kernel and Dart 2 by default.
