### ISSUE TITLE
Suppress warning from FE when VM+FE is used to execute code

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#31552]
Issue [31480](https://github.com/dart-lang/sdk/issues/31480) moves the warning generated by FE during execution to stderr. There are cases when we want to suppress these warning all together - analysis, running tests.

Add a flag to FE to suppress warnings to be used when vm is invoked with --dfe flag?

**Comment by keertip** [comment]
@peter-ahe-google

**Comment by peter-ahe-google** [comment]
I agree that flag is nice to have. We've previously had problems building compilers on top of the VM when it emits warnings that can't be suppressed. For example, if the VM emits a warning when running dart2js, a user of dart2js may think that the warning is about their code.

**Comment by kmillikin** [comment]
Would it be enough to have a Dart environment variable (`const bool.fromEnvironment`) or an OS environment variable (`Platform.environment`) that we could read from a script?  That would be very easy to add.

Plumbing a flag from the VM to the FE isolate seems more complicated, and we might want to delegate that to the VM team if it's what we actually need.

**Comment by peter-ahe-google** [comment]
Relying on environment variables tends lead to problems long term. People set these environment variables because one person tells them to, and then they don't notice errors in another project the next day.

**Comment by kmillikin** [comment]
@bkonyi plumbed the flag through the VM to Fasta.  I will implement code to respect it in Fasta.
