### ISSUE TITLE
dart_bootstrap should not need kernel binaries when compiling AOT snapshots

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31560]
Currently we need to pass `--kernel-binaries` even when compiling the fully linked Kernel binary into an AOT snapshot. 

We should not need to do that. This can also lead to incorrect code generated if we end up loading parts of the Isolate from one binary (e.g. vm_platform) and parts of the isolate from another binary (input kernel).

**Comment by alexmarkov** [comment]
Commit 0352170a8f27547c55fa445c2e3f4ae870084ebc removes the requirement to specify --kernel-binaries option. If this option is not specified, then the kernel file from the command line is treated as fully linked and platform classes are used from that binary. '-c dartkp --strong' configuration of the test tool and pkg/vm/tool/precompiler2 run in this mode.

If --kernel-binaries is specified, platform libraries are still loaded from the vm_platform.

**Comment by a-siva** [comment]
We don't have the --kernel-binaries option anymore.
