### ISSUE TITLE
[VM] make --strong without --dfe an error

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#31561]
Followup to @mraleph's comment in https://github.com/dart-lang/sdk/issues/31534#issuecomment-349650139

Could you also make `--dfe` report an error until it is actually implemented?

cc @kwalrath @kevmoo

**Comment by a-siva** [comment]
@sivachandra is working on cleaning up some of the options that the VM uses when running with
the common front end. The goal is to have a single --preview-dart-2 option that turns on Dart 2.0 which
would be strong mode by default.
This will be addressed by that change.

**Comment by a-siva** [comment]
We are making --strong the default for --preview_dart_2 and the --dfe option is not a requirement for running dart with the new front end. This bug is obsolete with the new --preview_dart_2 option.
