### ISSUE TITLE
Unary bitwise complement "~" in dart2js is wrong

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#31569]
for example,

```
var i = 0;
print(~i);
```

It should print `-1` not `4294967295`

Dart2js will compile it to
```~i >>> 0```
Not `~i` only

**Comment by rakudrama** [comment]
dart2js and DDC chose to restrict bit operations to the range [0, 2^32).
The other choice was [-2^31, 2^32).
The unsigned range makes more code 'just work'.
See: https://github.com/dart-lang/sdk/issues/25493
