### ISSUE TITLE
Some custom element tests are failing when compiled using dartdevc

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#31568]
I don't know exactly what's going on, but I'm leaving a bug here mainly to reference it in the status file. Here's what I see:

1. The test calls `document.registerElement()`.
2. That eventually calls `_registerCustomElement()` in the SDK.
3. That calls `_interceptors.findInterceptorConstructorForType(type)` for the given class.
4. That returns `null`.
5. `_registerCustomElement()` throws an ArgumentError.

**Comment by matanlurey** [comment]
FWIW, these aren't used. So I'd keep this priority pretty low (even post Dart 2 is fine)

**Comment by munificent** [comment]
Yup, that's the plan. Filing the bug so I can forget about it and make it future-Bob's problem. :)

**Comment by jmesserly** [comment]
I think this is covered by https://github.com/dart-lang/sdk/issues/27311
