### ISSUE TITLE
Analysis server integration test failures with --use-cfe

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31571]
### ListPostfixCompletionTemplatesTest_UseCFE
- [ ] test_list_postfix_completion_templates

### GetRefactoringTest_UseCFE
- [ ] test_rename

### GetFixesTest_UseCFE
- [ ] test_has_fixes
- [ ] test_no_fixes

### GetAssistsTest_UseCFE
- [ ] test_has_assists

### GetStatementCompletionTest_UseCFE
- [ ] test_statement_completion

### FindElementReferencesTest_UseCFE
- [ ] test_badTarget
- [ ] test_findReferences

### FindMemberDeclarationsTest_UseCFE
- [ ] test_findMemberDeclarations

### FindMemberReferencesTest_UseCFE
- [ ] test_findMemberReferences

### GetTypeHierarchyTest_UseCFE
- [ ] test_getTypeHierarchy

### StatusTest_UseCFE
- [ ] test_status

### UpdateContentTest_UseCFE
- [ ] test_updateContent_list

### AnalysisErrorIntegrationTest_UseCFE
- [ ] test_super_mixins_disabled

### SetGeneralSubscriptionsTest_UseCFE
- [ ] test_options

### AnalysisHighlightsTest_UseCFE
- [ ] test_highlights

### GetNavigationTest_UseCFE
- [ ] test_navigation
- [ ] test_navigation_no_result

### AnalysisGetHoverIntegrationTest_UseCFE
- [ ] test_getHover

### SetPriorityFilesTest_UseCFE
- [ ] test_options

### OverridesTest_UseCFE
- [ ] test_overrides

### ReanalyzeTest_UseCFE
- [ ] test_reanalyze

### ReanalyzeTest_UseCFE
- [ ] test_reanalyze_concurrent

### AnalysisNavigationTest_UseCFE
- [ ] test_navigation

### DeleteContextTest_UseCFE
- [ ] test_delete

### MapUriTest_UseCFE
- [ ] test_mapUri

**Comment by devoncarew** [comment]
out of date

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
