### ISSUE TITLE
dart2js: Combination of generic function invocation and Function types not implemented

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31572]
With dart2js (from e299963a3ce37584ec7277c230235beae26554fe, 2.0.0-dev.7.0, and probably all versions this year), the following program claims a syntax error:

```dart
main() => print(f<String Function(int)>(null));
```

This syntax is allowed (the actual argument to `print` is an invocation of a generic function where the actual type argument is a `Function` type). Here's the report:

```
scratch.dart:1:26:
Error: Expected ')' before this.
main() => print(f<String Function(int)>(null));
                         ^^^^^^^^
Error: Compilation failed.
```

The problem also exists when invoked as `dart2js --use-kernel ..`.

One known part of the problem is that `isValidMethodTypeArguments` in 'parser.dart' hasn't been updated to take the new style `Function` types into account, and in particular `tryParseType` expects only the syntax we had before those types were added. Other parts of the parser may also be unprepared for this kind of syntax once `isValidMethodTypeArguments` is updated such that an attempt will be made to parse a generic function invocation.

**Comment by sigmundch** [comment]
this seems to now be handled correctly by the CFE
