### ISSUE TITLE
need to start testing ARM/ARM64 dartk and dartkp configurations

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31573]
We need to ensure coverage for this configurations as they are the ones that we are going to be shipping. 

@athomas do we have free buildbot slaves that can be used for this? If we do I can update recipes myself, just let me know. Otherwise please see if we can get slaves from somewhere.

**Comment by whesse** [comment]
We can ask for more arm64 slaves, but there are currently no arm slaves on buildbot.  We are discussing how to solve this problem.  We can use the existing arm64 slaves for multiple builders while waiting for more.

**Comment by mraleph** [comment]
Intel slaves are fine too - we can at least start testing SIMARM/SIMARM64.

**Comment by athomas** [comment]
Could we do this on LUCI? I don't see any reason why we couldn't.

We need ARM bots there as well.
We already have Intel bots.
We probably don't need any recipe changes, only update the test matrix and I can do the necessary setup in LUCI if we need a new builder there.

What will be the build.py and test.py commands we want to run?

**Comment by mraleph** [comment]
@athomas 

I think this would be a good start:

```
# DartK
tools/build.py -m release -a simarm,simarm64 runtime_kernel
tools/test.py -m release -c dartk -a simarm,simarm64
tools/test.py -m release -c dartk -a simarm,simarm64 --strong  language_2 corelib_2 lib_2 standalone_2

# DartKP
tools/build.py -m release -a simarm,simarm64 runtime_kernel dart_precompiled_runtime
tools/test.py -m release -c dartkp -r dart_precompiled -a simarm,simarm64
tools/test.py -m release -c dartkp  -r dart_precompiled -a simarm,simarm64 --strong  language_2 corelib_2 lib_2 standalone_2
```

**Comment by athomas** [comment]
Is there some plan to make these tests faster somehow? Or alternatively, can we run a smaller suite than what was suggested?
I have tried running "tools/test.py -m release -c dartk -a simarm" and that takes ~2 hours to reach 10%. For reference, buildbot runs "test.py -mrelease '--arch=simarm'" in ~30 minutes (100% of twice as many tests).

**Comment by mraleph** [comment]
Yes, we are going to switch dartk configuration to use batch mode Fasta compiler instead of  `--dfe=` isolate. 

I have filed an issue for this: #31585, once we land that we can move on with landing buildbot configuration.

**Comment by athomas** [comment]
First test runs of the new builders (non-precomp):
https://chromium-swarm.appspot.com/task?id=3a729aae75c79110
https://chromium-swarm.appspot.com/task?id=3a729c9bf0cc0310
https://chromium-swarm.appspot.com/task?id=3a729d40bc17d610
https://chromium-swarm.appspot.com/task?id=3a729d66c92f5e10

LUCI configuration is mostly completed. I still need to setup email notifications and enable them in the scheduler.

**Comment by athomas** [comment]
The builders are now enabled in the scheduler. To setup email notifications, I need to know where to send them, because I don't have blamelist support on LUCI, yet.

@mraleph Which email address should be notified? And when ([on failure, on change, on success](https://github.com/luci/luci-go/blob/master/luci_notify/api/config/notify.proto#L48))?

**Comment by a-siva** [comment]
I am going to change the milestone of this bug to 2.0 alpha-2, we will track all stability issues on that milestone.

**Comment by dgrove** [comment]
@athomas Any updates on this?

**Comment by athomas** [comment]
The configurations mentioned in https://github.com/dart-lang/sdk/issues/31573#issuecomment-350220405 are all running now. The remaining issue for this is blamelist emails which is tracked elsewhere: https://bugs.chromium.org/p/chromium/issues/detail?id=808193
