### ISSUE TITLE
isolate suite was not migrated to Dart 2

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31588]
When I try running it on VM I see a lot of failures on `-c dartk --strong`.

I am going to update status files.

@a-siva should this suite be migrated to Dart 2?

**Comment by a-siva** [comment]
We discovered that the isolate tests were migrated to lib_2/isolate during the migration process.
All the tests in tests/isolate directory should be skipped when running in dartk or dartkp modes.
@sivachandra is taking care of making the change to skip all tests in tests/isolate under dartk or dartkp modes.
