### ISSUE TITLE
Restore batch mode compiler support for dartk and dartkp configurations

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31585]
Currently we use kernel isolate in all dartk and non-strong dartkp modes. This allows us to compile to Kernel transparently, but leads to a lot of issues and bad performance of tests especially in simulated architectures (40x slower tests on SIMARM+dartk configuration) and precompiler mode. 

Plan:

- [x] Restore pure batch mode support: run persistent compiler runner in background, compile to dill files on disk, pass those to the VM. 
- [x] Switch dartkp on all architectures to this mode.
- [x] Switch dartk on SIM* architectures to use this mode.

Some tests that need to perform on the fly compilation (Isolate and reload tests) would continue to use `--dfe` for now.

**Comment by mkustermann** [comment]
Enabled in -cdartkp --strong in 8c38a415dead901d369d9c5826c52ef53a395f95

**Comment by alan-knight** [comment]
The CL caused regressions, talked to Martin and reverted it in https://dart.googlesource.com/sdk/+/af0b27480a30bea4c87ab34b8d4f712319fcd3f5

**Comment by mkustermann** [comment]
A re-land of that CL is [in-progress](https://dart-review.googlesource.com/c/sdk/+/28400) and more CLs are in preparation.

**Comment by mkustermann** [comment]
So this has been working for a while, I've kept the bug open so far for the following things:

  * [ ] Make use of a new IKG api to make the batch compiler faster, there's a todo in [pkg/vm/bin/gen_kernel.dart](https://github.com/dart-lang/sdk/blob/215839843439b37598deee8bcc394fdc8c52a052/pkg/vm/bin/gen_kernel.dart#L102) to do that  (this is purely a performance optimization)
  * [ ] Make isolate tests work (currently we skip them). The issue with spawn function is tracked at https://github.com/dart-lang/sdk/issues/31698 and spawning from uri simply won't work for batch mode. The only thing we could consider is white-listing a few spawn-uri-using-tests to use the kernel isolate. But this seems to me too complicated/hackisch and we don't gain a lot from it. So I have no plans of implementing this.

Will close this issue therefore.
