### ISSUE TITLE
When code completing on a constructor argument, I'm shown options like "new" when what I want is the enum values

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#31592]
I'm writing Flutter code, which is a lot of constructors with named parameters. These named parameters have type annotations, and some of them expect Enums.

Expected: when I try to code complete a constructor param that is expecting an enum, I'd like the top result to be the enum. This is what I expect:

<img width="792" alt="screen shot 2017-12-08 at 1 01 18 pm" src="https://user-images.githubusercontent.com/5479/33787955-75acc6a0-dc24-11e7-976e-05692b761f29.png">

Actual: when I try to code complete, instead I see very general options like "new" and "const".

<img width="713" alt="screen shot 2017-12-08 at 1 01 28 pm" src="https://user-images.githubusercontent.com/5479/33787964-846f2520-dc24-11e7-959b-4b4f6f1355bd.png">

Especially with the case of enums, I'm hoping the code completion engine can give me the enum as the top result.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew @mit-mit

**Comment by mit-mit** [comment]
@bwilkerson what would it take to support this? I agree it's very annoying when writing Flutter code.

**Comment by bwilkerson** [comment]
I agree as well. I wasn't sure what it would take, so I started looking at the code and I think it isn't too hard to make a small improvement.

**Comment by sethladd** [comment]
Thanks for taking a look! The idea is to prefer Enum values when completing a parameter that expects an Enum?

**Comment by bwilkerson** [comment]
Yeah. The first step that I sketched out just uses the type of the parameter to prioritize suggestions of the right type, which results in having the enum values and the name of the enum at the top of the list, but a little more tweaking should allow us to get the values to always be at the top. It should also improve the order for non-enum suggestions.

(In test code similar to your example, the results were effectively equivalent to having the first three suggestions be "MainAxisSize.min", "MainAxisSize", and "MainAxisSize.max". Not perfect, but a step in the right direction. Thinking out loud: Maybe we should just remove the name of the enum from the list, knowing that we're going to suggest each of the individual values separately anyway.)

**Comment by sethladd** [comment]
> the first three suggestions be "MainAxisSize.min", "MainAxisSize", and "MainAxisSize.max"

Sounds like a great start.

**Comment by bwilkerson** [comment]
I believe that this has largely been addressed.
