### ISSUE TITLE
Remove int64 overflow checking in Integer::New

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31600]
This code exists only to support the Flutter-int64 experiment, and will be dead before Dart 2.0 ships.

**Comment by dgrove** [comment]
Is this code still live?

**Comment by alexmarkov** [comment]
Yes, this code is still live. It is useful as long as old VM parser is used. After removing old VM parser, these overflow checks can be turned into assertions.

So, I think this issue is a part of post-Dart 2 cleanup and it is not a prerequisite to shipping Dart 2.
