### ISSUE TITLE
Analyzer needs a way to parse references in documentation comments

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31604]
Examples of references:

```dart
/// Simple identifier [num].
class C<T extends num> {}
```

```dart
import 'dart:async' as async;

/// Qualified identifier [async.Future].
class C {}
```

```dart
/// Constructor reference with `new` [new C.named] or without [C.named].
class C {
  C.named();
}
```

```dart
import 'dart:async' as async;

/// Qualified reference to a static method [async.Future.wait].
class C {}
```

```dart
import 'dart:async' as async;

/// Operator reference with `operator` kerword [num.operator+],
/// or without it [num.+].
class C {}
```

References are resolved in the context of the commented entity.
```dart
/// Reference to the [T] type parameter to [v].
typedef void F<T>(T v); 

class C {
  /// Process the given [value] and return [T].
  T foo<T>(int value) => null;
}
```
![image](https://user-images.githubusercontent.com/384794/33848111-a27b04fa-de61-11e7-8259-0d5683e39c46.png)

References in/to documentation of local functions are also supported.
```dart
main() {
  /// Process the given [value] and return [T].
  T foo<T>(int value) => null;
  
  /// This calls [foo].
  void bar() {}
}
```
![image](https://user-images.githubusercontent.com/384794/33848268-047901fc-de62-11e7-93b9-cd03e97f3033.png)

References are not arbitrary expressions, they are only references - up to tree identifiers, and optional `new` prefix, optional `operator` keyword and might be an operator name instead of an identifier. No invocation arguments.

We can parse these references in `AstBuilder`, see https://dart-review.googlesource.com/c/sdk/+/28040. But we need a way to resolve them. Currently we don't do any resolution in `AstBuilder`, and apply resolution later, after `BodyBuilder` performed it.

**Comment by danrubel** [comment]
I've modified the fasta parser to parse comment references in dartdoc:

* https://dart-review.googlesource.com/c/sdk/+/68202
* https://dart-review.googlesource.com/c/sdk/+/68700
* https://dart-review.googlesource.com/c/sdk/+/68520
* https://dart-review.googlesource.com/c/sdk/+/68461
* https://dart-review.googlesource.com/c/sdk/+/68780

Please let me know if there is any other parser changes you need.

**Comment by DanTup** [comment]
@scheglov I came across this issue while looking for something else - as far as I can tell all of the examples above work as expected, so is this done/can be closed?

**Comment by scheglov** [comment]
Yes, thank you.
