### ISSUE TITLE
Support for type arguments in redirecting factory constuctors

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31605]
The kernel I get from front-end has `invalid-expression` and does not include type arguments.

```dart
class A<T> implements B<T> {
  A(int a);
  A.named(double a);
}
class B<U> {
  factory B.one(int b) = A<U>;
  factory B.two(double b) = A<U>.named;
}
```

```kernel
library;
import self as self;
import "dart:core" as core;

class A<T extends core::Object> extends core::Object implements self::B<self::A::T> {
  constructor •(core::int a) → void
    : super core::Object::•()
    ;
  constructor named(core::double a) → void
    : super core::Object::•()
    ;
}
class B<U extends core::Object> extends core::Object {
  static field dynamic _redirecting# = <dynamic>[self::B::one, self::B::two];
  static factory one<U extends core::Object>(core::int b) → self::B<self::B::one::U>
    let dynamic #redirecting_factory = self::A::• in invalid-expression;
  static factory two<U extends core::Object>(core::double b) → self::B<self::B::two::U>
    let dynamic #redirecting_factory = self::A::named in invalid-expression;
}
```

See also https://github.com/dart-lang/sdk/issues/30258

**Comment by eernstg** [comment]
You may have noted that the grammar in the language specification does not allow for passing type arguments after `=` in a redirecting factory constructor declaration. Could that in some indirect manner be the source of the problem?

In any case, the specification of checks applied to redirecting constructors have been updated substantially in [this CL](https://dart-review.googlesource.com/c/sdk/+/28140), which also adds `typeParameters?` to the syntax.

**Comment by scheglov** [comment]
Hm... I think the specification allows type arguments in redirection.
See http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf

![image](https://user-images.githubusercontent.com/384794/33899285-e2204886-df1f-11e7-929f-9bb38e186e25.png)

![image](https://user-images.githubusercontent.com/384794/33899310-f172fedc-df1f-11e7-8650-1a4dc01e5034.png)

**Comment by eernstg** [comment]
Good catch, it does indeed allow type arguments already, and it's reverted now.

**Comment by stefantsov** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/ec9c927b180f35f17d94f7fae7c97e94e9482056.
