### ISSUE TITLE
 Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in GenericTypeAliasImpl in CompilationUnitImpl

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#31607]
[report.txt](https://github.com/dart-lang/sdk/files/1550568/report.txt)

Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.3727.108`
- `1.24.2`
- `WS-173.3727.108, JRE 1.8.0_152-release-1024-b6x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Giorgio\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in GenericTypeAliasImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
