### ISSUE TITLE
Flaky test: co19/LayoutTests/fast/css/sheet-collection-link_t01 on windows-dart2js-ie11

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#31602]
Example log: `https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-win7-ie11ff-3-4-be%2F6271%2F%2B%2Frecipes%2Fsteps%2Fdart2js_ie11_co19-fast-startup_tests%2F0%2Fstdout`

**Comment by athomas** [comment]
Layout tests have been deleted.
