### ISSUE TITLE
Please eliminate src-Folder in lib

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31603]
This folder makes absolutely no sense. 
https://www.dartlang.org/guides/libraries/create-library-packages

Either it is a small package then everything can go into `lib/mypackage.dart` or it is a package that needs more structure then additional file can go under `lib/mypackage/sub1.dart` `lib/mypackage/sub2.dart` `lib/mypackage/sub3.dart`

**Comment by matanlurey** [comment]
Thanks for your feedback!

This is currently a `pub` only thing (not part of the language). There is no plan to change this.
