### ISSUE TITLE
Confusing analyzer hint around accidental fuzzy-arrow case

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#31615]
Tested on 2.0.0-dev.10.0.

Without an explicit typedef, the following code has two mutually contradictory hints from the analyzer:

```dart
R aFunction<R, A>(R f(A), A param1) => f(param1);
String anotherFunction(String param1) => "Hello, ${param1}.";
/// Analyzer hint: "A function of type (String) -> String can't be assigned
///                 to a variable of type '(dynamic) -> String'"
String aTestFunction() => aFunction(anotherFunction, "hello");
/// Analyzer hint: "Unnecessary cast."
String aTestFunction2() => aFunction(anotherFunction as String Function(dynamic), "hello");
/// ???
```

With one, however, the conflict is resolved.
```dart
typedef functionWithParam = R Function<R, A>(A param);

R aFunction<R, A>(functionWithParam, A param1) => functionWithParam(param1);
String anotherFunction(String param1) => "Hello, ${param1}.";
/// No more hint!
String aTestFunction() => aFunction(anotherFunction, "hello");
/// Analyzer hint: "Unnecessary cast."
String aTestFunction2() => aFunction(anotherFunction as String Function(dynamic), "hello");
/// ???
```

I think the first example should be hinted the same way as the second.

**Comment by bwilkerson** [comment]
@MichaelRFairhurst

**Comment by jcollins-g** [comment]
Never mind on the second code sample.  It has a subtle bug -- that functionWithParam on line 3 doesn't actually refer to the typedef but is interpreted as a dynamic parameter.  Fixing that bug makes the situation worse -- now instead of a hint we get a warning.

I'm not entirely sure what the right resolution is here, now.

**Comment by jcollins-g** [comment]
This is an example of the user (me) accidentally creating a fuzzy-arrow case by declaring a parameter with `R f(A)`, which uses the old style Dart meaning of `R f(dynamic A)` rather than `R Function(A) f`, which is what I intended.  Some sort of analyzer help in figuring out that I did this would have been useful, but thanks for the assist @stereotype441!

**Comment by srawlins** [comment]
The analyzer now reports one diagnostic, a valid one, I think:

> error • The argument type 'String Function(String)' can't be assigned to the parameter type 'String Function(dynamic)'. • a.dart:5:37 • argument_type_not_assignable

Close?
