### ISSUE TITLE
Platform.script.path issue on Windows

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31610]
On Windows `Platform.script.path` returns value like `/D:/dart/tmp/tst.dart`. Please note '/' at the beginning of the path. On Windows absolute path should not be started with '/'

tested on Dart VM version: 2.0.0-dev.10.0 (Mon Dec 4 17:07:49 2017 +0100) on "windows_x64"

**Comment by whesse** [comment]
Platform.script is returning a URL.  URL.path returns the path part of the URL.  What you want is the native file path from a file:// URL, which is URL.toFilePath.  So you should call Platform.script.toFilePath().
