### ISSUE TITLE
add support for dart-ext uri's 

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#31618]
The front end's PhysicalFileSystem does not have support for dart-ext uri's, should support it.

**Comment by keertip** [comment]
cc @sigmundch

**Comment by sigmundch** [comment]
Unlike #31594 - I believe this may require some additional work to properly support native extensions in the VM.

**Comment by keertip** [comment]
cc @a-siva

**Comment by sigmundch** [comment]
Just to share my thoughts about this bug:
 - changes in the FE are small: we need to add a file-system that accepts this scheme and simply returns an empty file. We might want to compose this together with the solution we do for #31594.
 - the FE needs to annotate the libraries where these imports occur (or preserve the imports in the LIbraryDependencies so they are available to the VM when they load the kernel program)
 - during deserialization the VM needs to retrieve this information and properly load the native extension.
