### ISSUE TITLE
Remove support for fuzzy arrows from the analyzer

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31637]
This might be as simple as removing the flag 'dynamic is bottom' from use sites in the analyzer.

**Comment by devoncarew** [comment]
@leafpetersen is working on this - he's added a hint, which will become an error. We can then remove support.

**Comment by leafpetersen** [comment]
Tracking bug for the fuzzy arrow elimination is here:  https://github.com/dart-lang/sdk/issues/29630

**Comment by leafpetersen** [comment]
Not quite, but very close.  When internal code is green, I will delete the last bit of support for it.

**Comment by dgrove** [comment]
Any updates @leafpetersen ?
