### ISSUE TITLE
Optional type arguments lint should support generic methods

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#31639]
_From @leafpetersen on December 13, 2017 10:4_

The @optionalTypeArgs annotation specifies that the type arguments to a class should be allowed to be elided even if linting options require explicit type arguments.

This annotation does not currently work for generic methods.  This test code:

```dart
 @optionalTypeArgs
  static void g<T>() {}
  void test() {
    // Currently allowed
    g<dynamic>();
   // Currently disallowed, should be allowed 
    g(); 
   }
```

Produces this error:

```
[error] Missing type arguments for generic method 'g<T>'.
```

This annotation should work for generic methods as well.

cc @pq @Hixie @mit-mit 

_Copied from original issue: dart-lang/linter#851_

**Comment by pq** [comment]
@bwilkerson : my first thought was that this was popping up from the `always_specify_types` lint but now I'm thinking it's actually coming out of `analyzer` via the `IMPLICIT_DYNAMIC_TYPE` error code (see: [codes.dart](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/error/codes.dart#L4940)). Regardless, the lint should be fixed too I suspect but should I open another issue on the analyzer?

**Comment by pq** [comment]
Correction: I think the lint is actually OK.

Test to verify in flight here: https://github.com/dart-lang/linter/pull/852.

**Comment by pq** [comment]
_From @bwilkerson on December 13, 2017 15:17_

> I'm thinking it's actually coming out of analyzer via the IMPLICIT_DYNAMIC_TYPE error code ...'

We definitely need to understand where the error is being generated and why. It says "[error]", which implies to me that it isn't from a lint, so there's a good chance you're right.

If it is from an error in the spec, then we have a decision to make. In the past we have always followed the convention that errors could not be suppressed by annotations unless the annotation is documented in the spec as having that effect. I'm not even sure whether the spec has been updated to include this error. But in either case, I'm hesitant to violate the convention.

@leafpetersen Does the specification include a description of this error? If so, do we want to move `optionalTypeArgs` to dart:core so that it's behavior can be included in the spec?

**Comment by pq** [comment]
Moved from the linter.  Feel free to re-categorize as you see fit.

FYI @bwilkerson @leafpetersen

**Comment by leafpetersen** [comment]
I commented on the linter issue.  I think there's still a linter bug, but it's not the one I filed - it's with the always_specify_types lint.  In any case, this warning comes from --no-implicit-dynamic, which is fine.
