### ISSUE TITLE
Support assert in initializers in the analyzer

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31634]
The full syntax should already be supported, but not all error messages are being generated. Start by determining which error messages need to be generated and then implement them.

There are also potential implications for constant evaluation that need to be looked at.

**Comment by scheglov** [comment]
Language issue: https://github.com/dart-lang/sdk/issues/30968
Informal specification: https://github.com/dart-lang/sdk/blob/master/docs/language/informal/assert-in-initializer-list.md

**Comment by bwilkerson** [comment]
Two CL's in flight:
add evaluation support: https://dart-review.googlesource.com/c/sdk/+/32100.
add check for non-bool expressions: https://dart-review.googlesource.com/c/sdk/+/31963.

**Comment by bwilkerson** [comment]
Both have now landed, so I believe this arc of work is complete.
