### ISSUE TITLE
error listener API (using CompilationMessage) doesn't report Code, or analyzerCode, or args.

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#31644]
We have code for adapting a Message object into an AnalysisError.

However, the `onError` callback accepts `CompilationMessage`s, which seem to be a less powerful datastructure than `Message`. Notably, it has `String` for `code` instead of the `Code` object itself; and that `String` is not built using the `analyzerCode` but rather the normal code. We also don't get the `args` from the `Message` class either.

We also can't look up the analyzer code via fasta code in any way that I can see...I have it set up to do the string processing to turn `InvalidAssignment` into `INVALID_ASSIGNMENT` for now, but that is not a good idea long term.

There is no workaround I can see from not getting the args.

cc @stereotype441 @bwilkerson @scheglov @devoncarew

**Comment by sigmundch** [comment]
FWIW - I believe we should move away from "CompilationMessage" and just expose "Message" and "Severity" directly. 

This came up in a different context recently, but we haven't had the chance to discuss it in detail. To start the conversation, I created this CL that basically moves in the direction you are suggesting:

https://dart-review.googlesource.com/c/sdk/+/27880

**Comment by jensjoha** [comment]
Isn't this fixed by using "ProblemHandler onProblem" instead of "ErrorHandler onError"?

**Comment by MichaelRFairhurst** [comment]
A few updates: one is that we no longer need the args, we are using the error string directly.

Looks like there have been changes already to `CompilationMessage` already to support `Severity` and `analyzerCode`. So we don't need to use `ProblemHandler onProblem`, and I don't think we need this ticket anymore at all.

I did make a CL to switch, which I'll document here: https://dart-review.googlesource.com/c/sdk/+/33143 but it looks like we don't need it.
