### ISSUE TITLE
NS_ERROR_NOT_INITIALIZED in TimerImpl on Firefox 57.0 dart2js

### ISSUE THREAD

**Issue by snrnats** [dart-lang/sdk#31650]
I'm getting crash reports from a DartWeb application compiled with dart2js, DartSDK version **1.24.2**. According to reports it simetimes happen on Firefox 57.0.x on every OS. I wasn't able to reproduce the issue myself. Here are two slightly different deobfuscated stack traces:

`[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: https://gambino-slots.storage.googleapis.com/browser/gambino.dart.js?v=release_1.17.2_efb935f36527df9cb65f0fbb162b012eae6e9b27 :: aFy ::
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1410:17                 TimerImpl.periodic
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1406:3                  TimerImpl.periodic
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 129:12                     Timer._createPeriodicTimer
packages/$sdk/lib/async/zone.dart 1193:10                                              _rootCreatePeriodicTimer
packages/$sdk/lib/async/zone.dart 1092:12                                              _CustomZone.createPeriodicTimer
packages/$sdk/lib/async/timer.dart 81:12                                               Timer.periodic
packages/common/src/analytics/client_events_tracking/client_events_tracker.dart 29:16  ClientEventsTracker._initialize
packages/common/src/analytics/client_events_tracking/client_events_tracker.dart 80:5   ClientEventsTracker.flush
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19                     _wrapJsFunctionForAsync
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5                      _wrapJsFunctionForAsync.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19                     _awaitOnObject.<anonymous function>
packages/$sdk/lib/async/zone.dart 1128:37                                              _rootRunUnary
packages/$sdk/lib/async/zone.dart 1012:12                                              _CustomZone.runUnary
packages/$sdk/lib/async/future_impl.dart 129:12                                        _FutureListener.handleValue
packages/$sdk/lib/async/future_impl.dart 636:36                                        _Future._propagateToListeners.handleValueCallback
packages/$sdk/lib/async/future_impl.dart 665:13                                        _Future._propagateToListeners
packages/$sdk/lib/async/future_impl.dart 468:7                                         _Future._complete
packages/$sdk/lib/async/future_impl.dart 51:5                                          _SyncCompleter.complete
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 164:3                      _asyncReturn
packages/common/src/analytics/client_events_tracking/client_events_sender.dart 32:56   ClientEventsSender.uploadEvents
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19                     _wrapJsFunctionForAsync
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5                      _wrapJsFunctionForAsync.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19                     _awaitOnObject.<anonymous function>
packages/$sdk/lib/async/zone.dart 1128:37                                              _rootRunUnary
packages/$sdk/lib/async/zone.dart 1012:12                                              _CustomZone.runUnary
packages/$sdk/lib/async/future_impl.dart 129:12                                        _FutureListener.handleValue
packages/$sdk/lib/async/future_impl.dart 636:36                                        _Future._propagateToListeners.handleValueCallback
packages/$sdk/lib/async/future_impl.dart 665:13                                        _Future._propagateToListeners
packages/$sdk/lib/async/future_impl.dart 478:5                                         _Future._completeWithValue
packages/$sdk/lib/async/future_impl.dart 510:7                                         _Future._asyncComplete.<anonymous function>
packages/$sdk/lib/async/zone.dart 1120:12                                              _rootRun
packages/$sdk/lib/async/zone.dart 1001:12                                              _CustomZone.run
packages/$sdk/lib/async/zone.dart 901:14                                               _CustomZone.runGuarded
packages/$sdk/lib/async/zone.dart 926:20                                               _CustomZone.bindCallback.<anonymous function>
packages/$sdk/lib/async/schedule_microtask.dart 41:5                                   _microtaskLoop
packages/$sdk/lib/async/schedule_microtask.dart 50:5                                   _startMicrotaskLoop
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9                       _AsyncRun._initializeScheduleImmediate.internalCallback
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48                      invokeClosure.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16                  _IsolateContext.eval
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                   _callInIsolate
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14                      invokeClosure
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                      convertDartClosureToJS`

`[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: https://gambino-slots.storage.googleapis.com/browser/gambino.dart.js?v=release_1.17.2_efb935f36527df9cb65f0fbb162b012eae6e9b27 :: aFx :: line 1767"  data: no]
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1398:17         TimerImpl
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 1369:3          TimerImpl
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 121:12             Timer._createTimer
packages/$sdk/lib/async/zone.dart 1184:10                                      _rootCreateTimer
packages/$sdk/lib/async/zone.dart 1084:12                                      _CustomZone.createTimer
packages/$sdk/lib/async/timer.dart 51:12                                       Timer
packages/$sdk/lib/async/timer.dart 90:5                                        Timer.run
packages/common/src/future/ContextMarshaller.dart 5:5                          ContextMarshaller.marshalAsync
packages/features/src/common/ui/common/scroll_icon_download_watcher.dart 57:5  ScrollIconDownloadWatcher.onDownloadFailed
packages/common/src/downloading/composite_download_watcher.dart 18:7           CompositeDownloadWatcher.onDownloadFailed
packages/common/src/downloading/batch_downloader.dart 44:5                     BatchDownloader._onFailed
packages/common/src/downloading/batch_downloader.dart 22:7                     BatchDownloader.onDownloadStateChanged
packages/syd/src/engine/events/event_stream.dart 25:7                          EventStream._dispatchEvent
packages/syd/src/engine/events/event_dispatcher.dart 7:5                       EventDispatcher.dispatchEvent
packages/syd/src/engine/events/event_stream.dart 25:7                          EventStream._dispatchEvent
packages/syd/src/engine/events/event_dispatcher.dart 7:5                       EventDispatcher.dispatchEvent
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19             _wrapJsFunctionForAsync
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5              _wrapJsFunctionForAsync.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19             _awaitOnObject.<anonymous function>
packages/$sdk/lib/async/zone.dart 1128:37                                      _rootRunUnary
packages/$sdk/lib/async/zone.dart 1012:12                                      _CustomZone.runUnary
packages/$sdk/lib/async/future_impl.dart 129:12                                _FutureListener.handleValue
packages/$sdk/lib/async/future_impl.dart 636:36                                _Future._propagateToListeners.handleValueCallback
packages/$sdk/lib/async/future_impl.dart 665:13                                _Future._propagateToListeners
packages/$sdk/lib/async/future_impl.dart 468:7                                 _Future._complete
packages/$sdk/lib/async/future_impl.dart 51:5                                  _SyncCompleter.complete
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 164:3              _asyncReturn
packages/syd/src/engine/resources/pools/texture_resource_pool.dart 32:5        TextureResourcePool.loadResourceDataByDescription
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19             _wrapJsFunctionForAsync
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5              _wrapJsFunctionForAsync.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19             _awaitOnObject.<anonymous function>
packages/$sdk/lib/async/zone.dart 1128:37                                      _rootRunUnary
packages/$sdk/lib/async/zone.dart 1012:12                                      _CustomZone.runUnary
packages/$sdk/lib/async/future_impl.dart 129:12                                _FutureListener.handleValue
packages/$sdk/lib/async/future_impl.dart 636:36                                _Future._propagateToListeners.handleValueCallback
packages/$sdk/lib/async/future_impl.dart 665:13                                _Future._propagateToListeners
packages/$sdk/lib/async/future_impl.dart 478:5                                 _Future._completeWithValue
packages/$sdk/lib/async/future_impl.dart 510:7                                 _Future._asyncComplete.<anonymous function>
packages/$sdk/lib/async/zone.dart 1120:12                                      _rootRun
packages/$sdk/lib/async/zone.dart 1001:12                                      _CustomZone.run
packages/$sdk/lib/async/zone.dart 901:14                                       _CustomZone.runGuarded
packages/$sdk/lib/async/zone.dart 926:20                                       _CustomZone.bindCallback.<anonymous function>
packages/$sdk/lib/async/schedule_microtask.dart 41:5                           _microtaskLoop
packages/$sdk/lib/async/schedule_microtask.dart 50:5                           _startMicrotaskLoop
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9               _AsyncRun._initializeScheduleImmediate.internalCallback
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48              invokeClosure.<anonymous function>
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16          _IsolateContext.eval
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16           _callInIsolate
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14              invokeClosure
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14              convertDartClosureToJS`

**Comment by joshualitt** [comment]
I'm closing this issue due to age and the lack of an explicit repro. Please reopen this issue if it is still occurring.
