### ISSUE TITLE
io.Stdout.Encoding API Spec is incomplete

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31651]
Descriptio of io.Stdout.Encoding field in Dart API Spec is incomplete. See https://api.dartlang.org/stable/1.24.2/dart-io/Stdout/encoding.html.

Now it contains just a piece of the source code:

```
Source
Encoding get encoding => _sink.encoding;
void encoding=(
Encoding encoding
)
Source
void set encoding(Encoding encoding) {
  _sink.encoding = encoding;
}
```

It should contain a description and look like the one described for io.IOSink.encoding:
`The Encoding used when writing strings. Depending on the underlying consumer this property might be mutable.`

**Comment by natebosch** [comment]
This class now picks up the doc from the implementation in `IOSink`. I don't know if there used to be a local `@override` that was causing the docs to get lost, or if there was a change in dartdoc. Either way, this documentation exists now.

https://api.dart.dev/stable/3.0.5/dart-io/Stdout/encoding.html
