### ISSUE TITLE
Some links on api.dartlang.org don't work since 1.24.3

### ISSUE THREAD

**Issue by Stargator** [dart-lang/sdk#31654]
On the Dart core page there is at least one link in the body of the page for dart:collection -> https://api.dartlang.org/stable/1.24.3/#dart-collection

Found on this line:
> For other kinds of collections, check out the dart:collection library.

I don't know know of any other broken links on this page or any of the other pages. Suggest some kind of link validator is executed.

**Comment by Stargator** [comment]
Note: I used this page to check the website: https://error404.atomseo.com/SeoCheck/Report/api.dartlang.org/2017-12-14/free?from=

When it was done it found:
* 96 Broken links on your site (internal)
* 1 Broken link from your site to external resources
* 7 Broken anchor on your web pages

**Comment by kevmoo** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/31246
