### ISSUE TITLE
Process.start fails to capture some stdout output from the spawned process.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#31666]
I was trying to run a process, and echo its stderr and stdout to the console at the same time as capturing the stdout for processing, but some of the stdout is always missed.  It seems like `Process.exitCode` is not flushing the stdout stream from the process when the process exits, and then stdout gets flushed after `Process.exitCode` closes it's own stdout stream, so the `listen` is never called for that output.

Consider the following program:
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

Future<String> startProcess(String executable, List<String> args) async {
  stderr.write('Running "$executable ${args.join(' ')}".\n');
  final List<int> output = <int>[];
  final Process process = await Process.start(executable, args);
  process.stdout.listen((List<int> event) {
    output.addAll(event);
    stdout.add(event);
  });

  final int exitCode = await process.exitCode;
  if (exitCode != 0) {
    stderr.write('Running "$executable ${args.join(' ')}" failed with $exitCode.\n');
    exit(exitCode);
  }
  return new Future<String>.value(UTF8.decoder.convert(output).trim());
}

Future<Null> main(List<String> argList) async {
  final List<List<String>> commands = <List<String>>[
    <String>['/bin/echo', 'first result'],
    <String>['/bin/echo', 'second result'],
    <String>['/bin/echo', 'third result'],
  ];
  final List<String> results = <String>[];
  for (List<String> args in commands) {
    final String executable = args.removeAt(0);
    final String result = await startProcess(executable, args);
    results.add(result);
  }
  int resultIndex = 0;
  print('\nResults:');
  for (String result in results) {
    print('$resultIndex: $result');
    resultIndex++;
  }
}
```

The output **should** be:
```
Running "/bin/echo first result".
first result
Running "/bin/echo second result".
second result
Running "/bin/echo third result".
third result

Results:
0: first result
1: second result
2: third result
```
But it is consistently missing the first result, and sometimes the second or third result as well:
```
Running "/bin/echo first result".
Running "/bin/echo second result".
first result
second result
Running "/bin/echo third result".
third result

Results:
0: 
1: second result
2: third result
```

I've also tried using the ProcessManager in "package:io/io.dart" to spawn a process and it has similar results, although it doesn't ever echo the 'first result' line to the stdout.

This is on Linux (Ubuntu), with dart version:
Dart VM version: 1.25.0-dev.11.0 (Wed Aug 23 04:58:17 2017) on "linux_x64"

**Comment by zanderso** [comment]
Both child process exit codes and child process stdout are communicated to the Dart Isolate by the event handler thread with an Isolate message. The event handler thread uses epoll(), kqueues, overlapped IO, etc. to wait for events from child processes. Ready events from the eventhandler thread are not sent to the Dart Isolate in any particular order. It is entirely possible that your Dart isolate receives the message for the exit code before the last message for data from stdout.

It should be possible to avoid the race by passing `onDone` and/or `onError` callbacks to `listen` that complete a future, and use that future as well as process.exitCode to indicate that the process is finished and that all of the output has been captured.

Please let me know if that doesn't work out.

**Comment by gspencergoog** [comment]
OK, so this works as expected:

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

Future<String> startProcess(String executable, List<String> args) async {
  stderr.write('Running "$executable ${args.join(' ')}".\n');
  final List<int> output = <int>[];
  final Completer<int> completer = new Completer<int>();
  final Process process = await Process.start(executable, args);
  process.stdout.listen((List<int> event) {
    output.addAll(event);
    stdout.add(event);
  }, onDone: () async => completer.complete(await process.exitCode));

  final int exitCode = await completer.future;
  if (exitCode != 0) {
    stderr.write('Running "$executable ${args.join(' ')}" failed with $exitCode.\n');
    exit(exitCode);
  }
  return new Future<String>.value(UTF8.decoder.convert(output).trim());
}

Future<Null> main(List<String> argList) async {
  final List<List<String>> commands = <List<String>>[
    <String>['/bin/echo', 'first result'],
    <String>['/bin/echo', 'second result'],
    <String>['/bin/echo', 'third result'],
  ];
  final List<String> results = <String>[];
  for (List<String> args in commands) {
    final String executable = args.removeAt(0);
    final String result = await startProcess(executable, args);
    results.add(result);
  }
  int resultIndex = 0;
  print('\nResults:');
  for (String result in results) {
    print('$resultIndex: $result');
    resultIndex++;
  }
}
```
This code makes sense, when reading it, but the docs for [Process.exitCode](https://api.dartlang.org/stable/1.24.3/dart-io/Process/exitCode.html) should really mention that streams may not be flushed by the time exitCode completes, since as it reads right now, it just says "Returns a Future which completes with the exit code of the process when the process completes." Which, while technically correct, doesn't really lead the developer the right direction. My assumption (obviously) when I read that was that the exitCode future would complete with the same criteria for completion as onDone.
