### ISSUE TITLE
hot reload initial sync getting slower (performance regression)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31669]
There's a clear trend in how long it takes to do the `hot_mode_dev_cycle__benchmark hotReloadInitialDevFSSyncMilliseconds`. In a month we've gone from 5.5s to 6.2s:
![hotreloadinitialdevfssyncmilliseconds_regression](https://user-images.githubusercontent.com/551196/34066533-ea130d60-e1c4-11e7-835b-34cf34708f30.png)

**Comment by aam** [comment]
One thing that jumps out is that the app is actually getting larger, meaning more bytes have to be transferred to the device.
For example, comparing today's 4d2c2aaaa vs 2a26f29c9d from Nov, 13 you see number of bytes synchronized increased from 14,255,476 to 15.058,892.

Largest contributors to the size growth seems to be assets:

filename | bytes
-- | --
build/flutter_assets/packages/flutter_gallery_assets/animated_flutter_lgtm.gif: | 456,449
build/flutter_assets/packages/flutter_gallery_assets/animated_flutter_stickers.webp: | 89,088

**Comment by Hixie** [comment]
we have the resources on the device already right? do we have to send them again if they haven't changed?

**Comment by aam** [comment]
Currently, first time around(this is the initial sync) we send everything, for successive hot-reloads will only send changes.

**Comment by Hixie** [comment]
We should do something like compare hashes or something on the initial sync, and skip sending the data we already have. That might massively increase the speed of the initial sync.

**Comment by aam** [comment]
Obsolete now.
