### ISSUE TITLE
Installing Dart (1.24.3) on Mac is not possible - homebrew has still 1.24.2

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31674]
IntelliJ shows already that 1.24.3 is available...

```
brew info dart
dart-lang/dart/dart: stable 1.24.2, devel 2.0.0-dev.12.0
The Dart SDK
https://www.dartlang.org/
/usr/local/Cellar/dart/1.23.0 (2,373 files, 588.8MB)
  Built from source on 2017-04-21 at 18:53:53 with: --with-content-shell --with-dartium
/usr/local/Cellar/dart/1.24.0 (3,039 files, 656.4MB)
  Built from source on 2017-06-13 at 08:18:13 with: --with-content-shell --with-dartium
/usr/local/Cellar/dart/1.24.1 (3,041 files, 656.5MB)
  Built from source on 2017-06-16 at 08:10:07 with: --with-content-shell --with-dartium
/usr/local/Cellar/dart/1.24.2 (3,041 files, 656.4MB) *
  Built from source on 2017-06-23 at 14:26:49 with: --with-content-shell --with-dartium
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Options
--with-content-shell
	Download and install content_shell -- headless Dartium for testing
--with-dartium
	Download and install Dartium -- Chromium with Dart
--devel
	Install development version 2.0.0-dev.12.0
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app
```

### OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G18013
Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

### Software installed -----------------------------------------------------------
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
Pub 1.24.2

NPM: 5.6.0

**Comment by Stargator** [comment]
This should probably be brought up at: https://github.com/dart-lang/homebrew-dart
