### ISSUE TITLE
https://github.com/dart-lang/sdk/issues/31668 seems to have caused a regression in aot_snapshot compilation times 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31673]
[#31668](https://github.com/dart-lang/sdk/issues/31668) which was a merge of Dart into the engine seems to have caused regressions in the aot snapshot compilation times.

Please investigate.

**Comment by mraleph** [comment]
@a-siva #31668 is not a merge but an issue and we already know what the cause is, no need to investigate. See my comment on #31668.

**Comment by mraleph** [comment]
Duplicate of #31668
