### ISSUE TITLE
Testing shared options

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#3168]
There is a number of options that should be supported by most of our Dart implementations:

\* setting the package root.

\* turning on checked mode (aka developer mode).

\* turning on assertions.

We need to be able to test these options, and we need to agree on the &quot;command line syntax&quot; for these options. This bug is about testing the options, not the concrete command line syntax.

Bill and I discussed this and we think it could be implemented by adding a tag similar to VMOptions, but unlike VMOptions, these options would be expected to be understood by all implementations, and it would be a test failure to reject an option (so this is not compatible with --ignore-unrecognized-options).

For example, to test an option for setting the package root, lets assume --package-root=&lt;path&gt; could look like this:

my_test.dart:
// DartOptions=--package-root=my_test_package_root
# import('package:foo.dart', prefix: 'foo');

main() {
&nbsp;&nbsp;Expect.equals(42, foo.x);
}

my_test_package_root/foo.dart
var x = 42;

And a negative test could look like this:
my_negative_test.dart
// DartOptions=--package-root=no_such_directory
main() {}

**Comment by matanlurey** [comment]
Most of these options no longer exist in Dart2.
