### ISSUE TITLE
dartdevc doesn't work on IE 11

### ISSUE THREAD

**Issue by BorisNaguet** [dart-lang/sdk#31689]
Hello,

I have to do some tests on IE-11, and apparently it only works if I comment dartdevc.

### SDK Version:
1.24.2

### IE version:
```
Version: 11.0.9600.18837CO 
Update: 11.0.48 (KB4047206)
```

### To reproduce: 
* create a new "barebone web" project with IntelliJ
* run it 
* it opens correctly in IE (and everywhere else)
* uncomment the last 3 lines in pubspec (dartdevc)
* re-run
* it works in Chrome but not IE 11 

### Issue:
The console has this message:
`';' expected`
and points to that line (in `main.dart.bootstrap.js`):
`for (let moduleName of Object.getOwnPropertyNames(modulePaths)) {`

Apparently you can use `for in` (since IE 6) `let` (since IE 11 only), but not `for of`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility

Thanks

**Comment by matanlurey** [comment]
IE11 is not supported for dartdevc:
https://webdev.dartlang.org/tools/dartdevc/faq#what-browsers-does-dartdevc-work-with
