### ISSUE TITLE
Cannot set breakpoint

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#31686]
Running the following script with e.g. out/ReleaseX64/dart --pause_isolates_on_start --enable-vm-service:54975 <file.dart> with the file being

```
var x = [
  () {
    print("hello 1");
  },
  () {
    print("hello 2");
  }
];

main() {
  x[0]();
  x[1]();
}
```

and opening observatory I want to set a breakpoint on the "hello 1" line, but I cannot click it. Heading to the debugger and writing "break <file>:3" (a workaround that seems to sometimes work on other stuff) I'm told "Unable to set breakpoint at <file>:3".

Only after setting a breakpoint in main and stepping into a few times (so x is evaluated I think) I can set the breakpoint.

**Comment by rmacnak-google** [comment]
@sivachandra has made some changes in this area

**Comment by ZichangG** [comment]
The breakpoints can be set now.
