### ISSUE TITLE
dart:io APPEND field should be marked as const in Dart API Spec

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31697]
dart:io APPEND Spec reads:
```
APPEND = FileMode.APPEND
The mode for opening a file for reading and writing to the end of it. The file is created if it does not already exist.
```
It should be marked as const because actually it's a constant and cannot be changed.
So, description should look loke one for` FileMode.APPEND` field:
`dynamic APPEND = **const** FileMode._internal(2)`
See here:  https://api.dartlang.org/stable/1.24.3/dart-io/APPEND-constant.html

Some other fields from dart:io Constants section in the Spec are also not marked `const`: READ, WRITE, WRITE_ONLY, WRITE_ONLY_APPEND.

**Comment by floitschG** [comment]
Marking as a dartdoc issue.
The constant itself is `const`.

``` dart
const APPEND = FileMode.APPEND;
```
The `const` in front of it makes the variable constant.
However, dartdoc doesn't show this in the documentation.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/dartdoc#1576
