### ISSUE TITLE
Piping WebSockets cannot be well-typed in 'strong' mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31696]
Consider the following simplification of some vm-service tests.

import 'dart:io';
import 'dart:async';

foo(Stream<String> stream, WebSocket websocket) {
  stream.pipe(websocket);
}

This produces the error 

a.dart:5:15: Error: A value of type 'dart._http::WebSocket' can't be assigned to a variable of type 'dart.async::StreamConsumer<dart.core::String>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.async::StreamConsumer<dart.core::String>'.
  stream.pipe(websocket);

WebSocket should implement something like StreamConsumer<String|List<int>>, but there's no way to write this, so it only implements StreamConsumer<dynamic>. What is the recommended work around?

**Comment by a-siva** [comment]
On Sat, Dec 16, 2017 at 3:54 AM, Leaf Petersen <leafp@google.com> wrote:
If I'm reading the example right, this is a place where you really want contravariant generics, which we don't have (yet).  Three possible approaches jump to mind, happy to discuss further on Monday:

- Sometimes it's possible to use functions, which do give you contravariance.  I suspect that's not feasible here.

- A slightly unpleasant workaround (I think) is to manually do the pipe yourself:

```
websocket.addStream(stream).then((_) => websocket.close());
```

I think that works out, but could be missing something.

- Probably best solution: I think this is an instance of something that Lasse was explaining to me yesterday, and I think (hope) the solution is to use the new Stream methods that we are in the process of landing.  :}  I think you will want to do:

foo(Stream<String> stream, WebSocket websocket) {
  stream.retype<Object>.pipe(websocket);
}

Lasse, does that seem right?  I'm guessing that your implementation of pipe will pass the retyped stream, which will check each element as necessary?

It should work, yes. The implementation of Stream.pipe is:
Future pipe(StreamConsumer<T> streamConsumer) {
    return streamConsumer.addStream(this).then((_) => streamConsumer.close());
}
The retyped stream will likely not change that.

**Comment by a-siva** [comment]
cc @leafpetersen @lrhn @rmacnak-google

**Comment by rmacnak-google** [comment]
external_service_asynchronous_invocation_test: CompileTimeError # Issue 31696
external_service_disappear_test: CompileTimeError # Issue 31696
external_service_notification_invocation_test: CompileTimeError # Issue 31696
external_service_registration_test: CompileTimeError # Issue 31696
external_service_registration_via_notification_test: CompileTimeError # Issue 31696
external_service_synchronous_invocation_test: CompileTimeError # Issue 31696

**Comment by a-siva** [comment]
@leafpetersen has the implementation of the new Stream methods landed?

**Comment by leafpetersen** [comment]
Yes, this landed in dev.22.   It has been rolled into flutter, and should land in google3 today.

**Comment by dgrove** [comment]
What is the status on this?

**Comment by a-siva** [comment]
I believe all of these errors were fixed.
