### ISSUE TITLE
[JS interop] Add `deleteProperty` function to `dart:js_util` (or `package:js_util`?)

### ISSUE THREAD

**Issue by cedx** [dart-lang/sdk#31692]
`dart:js_util` has `getProperty`, `hasProperty` and `setProperty` functions... but no `deleteProperty` function mimicking the [`delete`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) operator.

Sometimes, it can be very useful to delete a property from a JS object used a map. Currently, I'm using a binding with the [`Reflect.deleteProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty) JS method, but the `Reflect` class is quite new, it is not supported by all browsers and JS platforms.

**Comment by floitschG** [comment]
This issue was moved to fluidic/js_util#1

**Comment by matanlurey** [comment]
That's not the right package... We provide a js_util.

**Comment by cedx** [comment]
Closing this issue : it is not really a priority, and the `Reflect` class is now available in all browsers and JS runtimes.
