### ISSUE TITLE
A bunch of simdbc tests fail after https://dart-review.googlesource.com/c/sdk/+/30389

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#31695]
After https://dart-review.googlesource.com/c/sdk/+/30389 which turned on strong mode for a bunch of vm tests, strangely the simdb64 bots failed on an *additional* set of tests separate from the other architectures, even though the particular tests shouldn't be arch-specific. Filing bug to investigate.

**Comment by rmacnak-google** [comment]
@mraleph @mkustermann I suspect these failures are related to batch mode rather than DBC per-se.

**Comment by mkustermann** [comment]
Going forward, please do not globally skip huge parts of a test suite, like `io/*: Skip`.

The new configurations we are testing now, namely dartk-simarm/simarm64/simdbc64 are too slow to run in normal mode, so we run these in batch mode. Currently this implies that isolate spawning doesn't quite work as usual, so we only skip those tests which spawn isolates. A comment explaining this is available in almost any kernel status file.

**Comment by mraleph** [comment]
Yes, these tests (at least some that I looked at) spawn isolates and spawn isolates end up running from source. I see two solutions: 

* run these (and only these tests) through `--dfe` isolate as a stop gap.
* make at least `Isolate.spawn(...)` work without reloading all sources but instead using already available DILL binary (i filed #31698).
