### ISSUE TITLE
Analyzer or DDC build script doesn't understand generic function types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31699]
I have a CL: https://dart-review.googlesource.com/c/sdk/+/26620
When trying to build the DDC SDK, I get the following error:
```
$ tool/build_sdk.sh 
*** Patching SDK
*** Compiling SDK to JavaScript
[error] Analysis of generic function typed parameters is not yet supported. (dart:core/set.dart, line 101, col 46)
```
That source line in `set.dart` contains the following declaration:
```dart
  static Set<T> castTo<S, T>(Set<S> source, {Set<R> newSet<R>()}) =>
      new CastSet<S, T>(source, newSet);
```

This should be a perfectly valid generic function type, so this seems like a problem with the analyzer (guessing it's the analyzer based on the error message talking about "Analysis").

Workaround: Change the parameter syntax to `{Set<R> Function<R>() newSet}` and it works without warning.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
