### ISSUE TITLE
Add dartk, dartkp Windows buildbots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31707]
Considering https://github.com/dart-lang/sdk/issues/31706, it seems pretty important now we add Windows dartk, dartkp buildbots.

@alexmarkov

**Comment by athomas** [comment]
I've tried running a dartk build and it fails in the front-end test step:

https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2F18680c15298a4e420a621cd30b6cce16292e535f11111eb562bf913dc1e6c4b5%2F%2B%2Fsteps%2Ffront-end_tests%2F0%2Fstdout

The linked issue also remains unsolved.

Is dartk even ready be tested on Windows?

**Comment by aam** [comment]
Original issue https://github.com/dart-lang/sdk/issues/31706 about running dartk/dartkp tests on Wnidows was fixed by d9173c09496990020c05ae8326655579f3746007. You should be able to confirm that `python tools/test.py -m release -c dartk service/get_ports_rpc_test` works now.

The errors in https://github.com/dart-lang/sdk/issues/31707#issuecomment-356684267 is something different, not part of dartk or dartkp configuration tests: `python tools/test.py -m release -c none --checked pkg/front_end/test/mixin_export_test`. Still should be fixed of course.

**Comment by athomas** [comment]
https://chromium-swarm.appspot.com/task?id=3af9e510f532eb10

There are also problems in the other steps as well.
40 failures without strong mode: https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2F18680c15298a4e420a621cd30b6cce16292e535f11111eb562bf913dc1e6c4b5%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout
All tests fail in strong mode: https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2F18680c15298a4e420a621cd30b6cce16292e535f11111eb562bf913dc1e6c4b5%2F%2B%2Fsteps%2Fstrong_vm_tests%2F0%2Fstdout

**Comment by aam** [comment]
Thanks @athomas . I believe it is critical that the team is aware of all of these dartk/dartkp/frontend tests, which fail specifically on Windows. Hopefully setting up Wiindows buildbot for dartk, dartkp is the step in that direction. Or do you see all tests passing as a prerequisite for buildbot set up?

**Comment by athomas** [comment]
Normally we only put green builders on the main console. We could just not put it on the main console for now.

There's also a bug in LUCI where each failing build takes out one of our builders for ~20mins, so a always failing builder is bad for cycle times on the console and CQ as well.

**Comment by aam** [comment]
> All tests fail in strong mode: 

https://dart-review.googlesource.com/c/sdk/+/34025 should address this.

**Comment by athomas** [comment]
Thanks, it did: https://chromium-swarm.appspot.com/task?id=3afd7e93fb7a8a10

**Comment by athomas** [comment]
Getting close: https://chromium-swarm.appspot.com/task?id=3b12f1adf7fa8710

**Comment by athomas** [comment]
I've re-enabled the window precomp bot, but it immediately fails:
Test configurations: dartkp_dart_precompiled_release_x64_strong dartkp_dart_precompiled_release_x64_strong
Running "vm_compile_to_kernel" command: set DART_CONFIGURATION=ReleaseX64 & set DART_VM_FLAGS=--limit-ints-to-64-bits & C:\b\s\w\ir\cache\builder\sdk\pkg\vm\tool\gen_kernel --aot --strong-mode --sync-async --platform=out/ReleaseX64/vm_platform_strong.dill -o C:/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartkp-strong/runtime_tests_vm_dart_byte_array_test/out.dill C:\b\s\w\ir\cache\builder\sdk\runtime\tests\vm\dart\byte_array_test.dart
CreateProcessW failed 193
Process error:
  Command: C:\b\s\w\ir\cache\builder\sdk\pkg\vm\tool\gen_kernel --batch ([--aot, --strong-mode, --sync-async, --platform=out/ReleaseX64/vm_platform_strong.dill, -o, C:/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartkp-strong/runtime_tests_vm_dart_byte_array_test/out.dill, C:\b\s\w\ir\cache\builder\sdk\runtime\tests\vm\dart\byte_array_test.dart])
  Error: ProcessException: %1 is not a valid Win32 application.
  Command: C:\b\s\w\ir\cache\builder\sdk\pkg\vm\tool\gen_kernel --batch
step returned non-zero exit code: 1

https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8954405349461037856%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_10%2F0%2Fstdout

**Comment by athomas** [comment]
These builders are now fully working with the exception of blamelist emails which is tracked elsewhere:
https://bugs.chromium.org/p/chromium/issues/detail?id=808193
