### ISSUE TITLE
Analyzer: Function type in for-loops crashes/can't parse

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31708]
This works in Dart2JS, but on the analyzer from

`Dart VM version: 2.0.0-dev.8.0+google3-v2.0.0.dev.8.0 `

... it crashes ...

```dart
void main() {
  final fns = [
    () => print('Hello World'),
  ]
  for (Null Function() fn in fns) {
    fn();
  }
}
```

... and this fails parsing entirely ...

```dart
void main() {
  final fns = [
    () => print('Hello World'),
  ]
  for (void Function() fn in fns) {
    fn();
  }
}
```

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Is this something you could look at?

**Comment by eernstg** [comment]
How did you make dart2js accept it without the semicolon before `for`? ;-) Anyway, the vm also barfs at `void` when the semicolon is added, so maybe there should be an issue for the vm as well. I searched for issues reporting problems with the vm parser around Function types and void, and I think I've seen an issue about that, but I couldn't find it right now.

**Comment by MichaelRFairhurst** [comment]
This is fixed for the analyzer, though the VM may still need it so I'll search for/make a new issue for that.
