### ISSUE TITLE
Add Dart_Print function to dart_api.h for easy debugging

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#31713]
Would be nice to have an easy way to do debug prints out-of-the-box when developing Dart native extensions.

**Comment by bkonyi** [comment]
@a-siva, should I just be hooking this into the OS::Print methods or does something else need to be done here?

**Comment by bkonyi** [comment]
@tejainece what exactly are you looking to print here? It might not make the most sense to actually do the printing within the VM since then we have to deal with how and where the printing is done. Would a method along the lines of `Dart_Handle ToCString(Dart_Handle obj, const char** out)` work instead?

**Comment by bkonyi** [comment]
Closing this for now due to lack of activity. Feel free to reopen if this is something we want to look into.

**Comment by thosakwe** [comment]
I feel like a `Dart_Handle ToCString(Dart_Handle obj, const char** out)` would be nice, but
it is also something relatively simple to just write in one's own code:

```c
Dart_Handle ToCString(Dart_Handle obj, const char** out) {
  Dart_Handle toStringMethod = Dart_NewStringFromCString("toString");
  Dart_Handle string = Dart_Invoke(obj, toStringMethod, 0, nullptr);
  return Dart_String_ToCString(string, out);
}
```

**Comment by a-siva** [comment]
Wouldn't it be equally easy to write a print to file function in one's own code, something like

fprintf(stream, "%s\n", Dart_ToCString(obj));

where Dart_ToCString(Dart_Handle obj) returns a C string.
