### ISSUE TITLE
dart2js generic method tasks

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#31718]
1. Basic passing of type parameters should ensure simple corelib classes have the right type:

- [x] Add generic method parameters as extra function parameters.
- [x] Add new selectors and their JS property encodings for passing/receiving type parameters.
- [x] Generate stubs to default missing type arguments (initial version can pass dynamic aka null).
- [x] Update closure conversion to handle generic methods/local functions.

2. Slightly more advanced basic features

- [x] Ensure closure conversion captures type parameters.
- [x] Ensure Function.apply works with static generic methods (it should...).

3. Generic function types

- [x] Modify type generator to generate **{func:...}** form generic function types.
- [x] Implement formatting for generic function types.
- [x] Modify subtype checker to compare generic function types.
  - This can be mostly tested by creating generic classes instantiated with types that contain generic function types -  `<Function(R <R>Function())>[] is T`.
 - [x] Add checking for bounds in the environment

4. Signatures
- [x] Generate $signature methods via SSA codegen queue.
- [x] Add new J-element type J-signature.
- [x] Create the required J-signature entities.
- [x] Create SSA graph for a J-signature entity.
- [x] Attach generated code to the correct closures.
- [x] Attach generated code to the correct tear-offs.

5. Instantiations
- [x] Create a base Instantiation class (subclass of Closure)
- [x] Have dart2js generate subclasses Instantiation1, Instantiation2, ... for each number of type parameters used by a generic method.
- [x] Add **call$xxx** forwarding stubs to these classes.

6. Misc
- [x] Ensure instantiation closures have an informative toString() 
- [x] Update RTI optimization to handle RTI need triggered by generic methods

**Comment by sigmundch** [comment]
Now that we have the simpler instantiation - what items on this list are blocking?

I believe the checks for type bounds is one (3.4, which @efortuna is fixing). Anything else?

**Comment by sigmundch** [comment]
quick update: we are down to 2 items (checklist is now updated)

Non blocking items have been moved to a separate bug #32691

**Comment by sigmundch** [comment]
update: signature tearoffs have a working solution. New feature development is complete, but we are now fixing bugs in closure calls (function.apply).

**Comment by rakudrama** [comment]
The feature is implemented.
