### ISSUE TITLE
Improve HttpClientRequest documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31721]
Please see [HttpClientRequest](https://api.dartlang.org/stable/1.24.3/dart-io/HttpClientRequest-class.html) API documentation

> HttpClientRequest is an IOSink. Use the methods from IOSink, such as writeCharCode(), to write the body of the HTTP request

If HttpClientRequest is an IOSink, then, please, specify which object is a target (StreamConsumer) of this IOSink

**Comment by floitschG** [comment]
There isn't any `StreamConsumer` for this `IoSink`.
The idea of an `IOSink` is to accept data in certain ways (`write`, `add`, `flush`). All the data written this way become the body of the HTTP request.

In this case I don't think that the documentation is ambiguous or wrong.
If you disagree (for example by pointing to other documentation that made you think that the request should be passed to some `StreamConsumer`), please reopen.

**Comment by sgrekhov** [comment]
For example, see [IOSink.addError()](https://api.dartlang.org/stable/1.24.3/dart-io/IOSink/addError.html)

> Passes the error to the target consumer as an error event.

HttpClienRequest is an IOSink, so it's unclear from the current documentation what object is a consumer of an error added by HttpClienRequest.addError(). That's why I filled this issue
