### ISSUE TITLE
IOSink.addError() issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31723]
According to the [IOSink.addError()](https://api.dartlang.org/stable/1.24.3/dart-io/IOSink/addError.html)

> This operation is non-blocking. See flush or done for how to get any errors generated by this call.

Current implementations of IOSink (I tested HttpClientRequest and an instance of IOSink returned by IOSinc() factory constructor) allow several addError() calls but only result of the first call is transfered to the consumer. Is this an expected bahaviour? If so, may be, then, it makes sense to add it to the documentation?

Example (program below prints only ERROR 1):

```dart
import "dart:async";
import "dart:io";

class MyStreamConsumer<List> extends StreamConsumer<List> {
  Future<dynamic> addStream(Stream<List> stream) {
    stream.toList().then((x) {
      print("Should not be here!");
    }, onError: (error, StackTrace st) {
      print(error); // ERROR 1
    });
    return new Future(() {});
  }
  Future close() { return new Future(() {}); }
}

main() async {
  StreamConsumer consumer = new MyStreamConsumer();
  IOSink sink = new IOSink(consumer);
  sink.addError("ERROR 1");
  sink.addError("ERROR 2");
  await sink.close();
}
```

**Comment by floitschG** [comment]
This is working as intended.

Whenever a stream goes to a Future (like with `toList`, `first`, ... the future can only get completed once.
In this case, the first error completes the future with an error and then cancels the subscription.

If you replace the `toList` with a call to `listen` you get both errors:
``` dart
import "dart:async";
import "dart:io";

class MyStreamConsumer<List> extends StreamConsumer<List> {
  Future<dynamic> addStream(Stream<List> stream) {
    stream.listen(print, onError: (error, StackTrace st) {
      print(error);
    });
    return new Future(() {});
  }
  Future close() { return new Future(() {}); }
}

main() async {
  StreamConsumer consumer = new MyStreamConsumer();
  IOSink sink = new IOSink(consumer);
  sink.addError("ERROR 1");
  sink.addError("ERROR 2");
  await sink.close();
}
```

We should probably document this better on the functions that go from `Stream` to `Future`.

**Comment by natebosch** [comment]
It looks like all the instance methods that return `Future` from a `Stream` are documented with error behavior.
