### ISSUE TITLE
Analysis server suggests "wrap with new widget" in non-Flutter project

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31720]
`Dart VM version: 2.0.0-dev.8.0 (Fri Nov 17 13:56:30 2017) on "macos_x64"`

I have code like the following:

```dart
void example([Iterable<String> names]) {
  names ??= [
  ];
}
```

If I highlight over `names ??=` I see:

<img width="325" alt="screen shot 2017-12-23 at 12 44 44 pm" src="https://user-images.githubusercontent.com/168174/34322560-1ab92a10-e7df-11e7-8ceb-d08a050199bc.png">

**Comment by stevemessick** [comment]
Cannot reproduce with Dart SDK 1.25.0-dev.11.0.

**Comment by bwilkerson** [comment]
@matanlurey I'm not seeing this either. Can you confirm whether this still occurs for you after you update?

**Comment by matanlurey** [comment]
@stevemessick:

> Cannot reproduce with Dart SDK 1.25.0-dev.11.0.

But we're currently on 2.0.0-dev, not 1.25.0?

I haven't seen this again in a while, so I'll close for now.
