### ISSUE TITLE
Incorrect maximum length of the datagram

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#31733]
According to [RawDatagramSocket.receive()](https://api.dartlang.org/stable/1.24.2/dart-io/RawDatagramSocket/receive.html)

> The maximum length of the datagram that can be received is 65503 bytes.

However, the test below demonstrates receiving the datagram of 65507 bytes length.

> 65507

```dart
import "dart:async";
import "dart:io";

int sentLength = 65507;

main() {
  var address = InternetAddress.LOOPBACK_IP_V4;
  RawDatagramSocket.bind(address, 0).then((producer) {
    RawDatagramSocket.bind(address, 0).then((receiver) {
      Timer timer2;
      List<int> sList = new List<int>(sentLength);
      for (int i = 0; i < sentLength; i++) {
        sList[i] = i & 0xff;
      }

      producer.send(sList, address, receiver.port);
      producer.close();

      List<int> rList;

      receiver.listen((event) {
        var datagram = receiver.receive();
        if (datagram != null) {
          rList = datagram.data;
          print(rList.length);           // received datagram.data length
        }
        if (timer2 != null) timer2.cancel();
        timer2 = new Timer(const Duration(milliseconds: 200), () {
          receiver.close();
        });
      });
    });
  });
}
```
Reproduced with Dart VM version: 2.0.0-dev.14.0 (Wed Dec 20 10:43:00 2017 +0100) on "linux_x64".

**Comment by sgrekhov** [comment]
The issue still exists. `Dart SDK version: 2.19.0-81.0.dev (dev) (Tue Aug 9 14:51:36 2022 -0700) on "windows_x64" `

**Comment by rmacnak-google** [comment]
@brianquinlan This test flaked recently. RawDatagramSocket.receive should probably remove the maximum length claim, as IPv6 jumbograms might produce much larger datagrams.
