### ISSUE TITLE
analyzer does not warn about recursive typedef

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#31736]
I had a typo and had:
```dart
// Why isn't this an analyzer error?
typedef void RecursiveTypedef(RecursiveTypedef);
```

The actual value in my program was supposed to have a class in the argument which was closely named to the typedef and I happened to typo.

The analyzer just treats that as "dynamic", presumably assuming it's a variable name?

**Comment by bwilkerson** [comment]
Correct. This is an old-style function type alias, which means that types are optional for parameters but identifiers are not. Hence, the name `RecursiveTypedef` within the parentheses is taken to be the name of the parameter, not a reference to the type.

You should see the expected error if you replace the declaration with:
```
typedef RecursiveTypedef = void Function(RecursiveTypedef);
```
