### ISSUE TITLE
Dart2js tests use sample-sunflower, which has been deleted

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#31740]
The sourcemaps and end2end tests of compiler/dart2js use third_party/sunflower.  The repository sample-sunflower has been deleted from github/dart-lang long ago, and the only reason the tests are still working is that the mirror of it on chromium.googlesource.com/external/github.com/dart-lang/sample-sunflower.git was not deleted.

The tests should be changed to use some dart code that is in third_party or in sdk, and is not from a deleted repo.  I have changed DEPS so that other third_party repositorys are fetched from dart.googlesource.com, but have left sample-sunflower fetching from chromium.googlesource until
this issue is resolved.

I don't know who deleted the sunflower sample, but it could be recreated from the chromium.googlesource mirror if needed.

@kevmoo @sigmundch @efortuna

**Comment by kevmoo** [comment]
Very weird. I would have been the first to move it, but it wan't me. It's not here - https://github.com/dart-archive

**Comment by joshualitt** [comment]
This appears to be fixed at TOT.
