### ISSUE TITLE
Analyzer: @visibleForTesting enforcement should support configuring test code location

### ISSUE THREAD

**Issue by robertoscaramuzzi** [dart-lang/sdk#31742]
Our (Flutter) project has testing infrastructure code in a testing/lib directory, and Flutter screenshot tests in a directory that is named slightly differently from /test/ . 

Usage of @visibleForTesting API from these directories is currently flagged by the analyzer.

The analyzer should provide an option to configure the location of test code (e.g by an analysis_options.yaml setting)

**Comment by bwilkerson** [comment]
Is this a convention that you encourage packages that use Flutter to follow? (I'm wondering whether we really need to make it configurable or whether it should just understand these conventions.)

**Comment by robertoscaramuzzi** [comment]
Putting test infrastructure in a testing directory is common practice at Google (which is where I work) and used universally both for Flutter and Angular code. There isn't much prior art on where to locate the screenshot tests, and we could probably change that if necessary.

**Comment by natebosch** [comment]
nit: common practice is to put test infrastructure in a testing _package_. This matches your description (`testing/lib`) but I want to make it clear that despite the way these look nested these are not part of the package they are testing. The separate `BUILD` file, and separate `lib/` directory make these separate packages in the Dart (and bazel) sense.

**Comment by robertoscaramuzzi** [comment]
Generally the structure will be:
- mypackage
  - lib
  - test
  - testing
    - lib
The code in mypackage/testing/lib is relevant to the code in mypackage/lib but can be accessed by tests for any package (subject to bazel visibility rules). Bazel enforces that only tests can access code in testing packages via the testonly = 1 parameter.

A common case in Angular is for testing/lib to contain page objects for a component in mypackage/lib. Any tests for a component that includes the component in mypackage/lib might use the corresponding page object.

For VM or Flutter apps, a common case might be that mypackage/lib has an RPC service implementation and testing/lib has a corresponding fake for tests.

Our screenshot tests are for the app as a whole and are at the top-level of our directory tree.

**Comment by bwilkerson** [comment]
So, if some declaration has an annotation of `@visibleForTesting`, then it should be visible within both the `test` directory and the `testing` package that is a sibling of the `test` directory, but nowhere else.

Is that correct, or should it also be visible to the screenshot tests? What about other `testing` packages?

**Comment by natebosch** [comment]
When you're doing this in google your structure is:

- mypackage
  - *BUILD*
  - lib
  - test
  - testing
    - *BUILD*
    - lib

Outside of bazel we don't support nesting like this. Inside bazel the separate `BUILD` files are turning this into separate packages. As far as the analyzer is concerned your structure is logically:

- mypackage
  - *BUILD*
  - lib
  - test
- mypackage.testing
  - *BUILD*
  - lib

**Comment by robertoscaramuzzi** [comment]
@natebosch : I realize that packages don't nest (similarly to Java).
@bwilkerson: likely any package which ends in 'testing' should be able to access any @visibleForTesting member. For example you could have a function in testing that builds up a complicated object that needs fakes from other packages. Ideally the packages would provide fakes in their own testing package but maybe they just provided a @visibleForTesting constructor for one of their objects.

Similarly, I think tests should be able to access @visibleForTesting code from other packages.

For screenshot tests our use case right now is to identify UI elements. Flutter provides the ability to add a key to an element, and the driver for screenshot tests needs to have that key to be able to identify an element to tap on, so yes, we need the ability to access @visibleForTesting code from screenshot test code.

**Comment by matanlurey** [comment]
Why do we need this in all in Blaze/Google? Just use `testonly = 1`?

**Comment by robertoscaramuzzi** [comment]
@visibleForTesting enforcement is more granular in that it warns you if members marked as such are used outside tests. testonly = 1 can't help you with that, since it works at the (bazel) package level.

The problem is that as it now stands it's too strict because testing infrastructure needs to access @visibleForTesting members too.

**Comment by matanlurey** [comment]
Sorry, what is the problem? You're talking about inside Google, which can use `visibleForTesting`. You also have the option of creating targets that are only visible to your testing code. I want to make sure we aren't creating `package:meta`-based annotations soley for the (mis)-use within Google, when you already have other good viable options.

**Comment by robertoscaramuzzi** [comment]
I'm sorry, Matan, I don't understand your last comment.

@visibleForTesting already exists and is used extensively, to mark members in production code that expose implementation details for testing purposes. I realize this is a code smell but it's sometimes unavoidable.

The Dart analyzer just added enforcement of @visibleForTesting. That's a good thing, and it can't be done using testonly = 1.

This issue was opened because the enforcement of this annotation is currently too strict and causes false positives when @visibleForTesting code is called from testing infrastructure.

**Comment by matanlurey** [comment]
> `@visibleForTesting already exists and is used extensively, to mark members in production code that expose implementation details for testing purposes. I realize this is a code smell but it's sometimes unavoidable.`

You don't need to do this. You can use `lib/src` and `testing` targets (internally, with Bazel).

> The Dart analyzer just added enforcement of `@visibleForTesting`.

I believe @srawlins did, and we can roll it back if we need to. So this isn't a priority.

**Comment by srawlins** [comment]
I'm open to allowing code from _any_ Dart file in a path with `/test/` or `/testing/`.

For example, in the **io** package, [`SharedStdIn`](https://www.dartdocs.org/documentation/io/0.3.1/io/SharedStdIn-class.html) is `@visibleForTesting`, but is [exported](https://github.com/dart-lang/io/blob/master/lib/io.dart#L9) as a public class. So it looks like it is meant to be accessible to other packages, but only for testing purposes.

**Comment by matanlurey** [comment]
@srawlins:

> I'm open to allowing code from any Dart file in a path with `/test/` or `/testing/`.

That sounds fine to me for now.
