### ISSUE TITLE
--pause-isolates-on-exit does not pause exit()

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31747]
The following simple program does not pause on exit with --pause-isolates-on-exit or --observe option:

```dart
import 'dart:io';

main() {
  print("Calling exit...");
  exit(1);
}
```

```
$ dart --pause-isolates-on-exit test_exit.dart
Calling exit(1)...
$
```

**Comment by jcollins-g** [comment]
I can confirm that this is still a problem in Dart 2.0.0-dev.69.5 on Linux.

**Comment by bergwerf** [comment]
I am also affected by this `Dart VM version: 2.0.0-dev.69.5 (Unknown timestamp) on "linux_x64"`.

**Comment by jcollins-g** [comment]
This is still a problem. @a-siva could you take a look at this?  The workaround is fairly trivial but ugly, especially if you want to exit outside of main().

**Comment by sortie** [comment]
I just hit this problem and was confused for a little while, at least the structure of this code let me use exitCode and have all futures exit, but that's not always easily the case for me.

**Comment by jcollins-g** [comment]
@bkonyi Is there an alternative to exit that immediately exits an isolate (and, presumably, allows the pause)?  That would seem to be the right thing to use, then, and a strong pointer to it would be a good idea in the docs.

**Comment by bkonyi** [comment]
> @bkonyi Is there an alternative to exit that immediately exits an isolate (and, presumably, allows the pause)? That would seem to be the right thing to use, then, and a strong pointer to it would be a good idea in the docs.

Some of the methods in `Isolate` allow for the pausing or shutdown of an isolate, particularly `Isolate.pause` and `Isolate.kill`. `Isolate.kill` will kill the currently isolate and the isolate will be paused before completely shutting down. I'm not sure what effect this would have on `exitCode` if it's set and the last isolate is killed, shutting the VM down gracefully.

Another option would be to use the functionality in `dart:developer`, particularly the [debugger function](https://api.dartlang.org/stable/2.1.0/dart-developer/dart-developer-library.html) which stops execution at that line as if there were a breakpoint. Calling that function before an `exit` would achieve the same effect as the isolate pausing on exit.
