### ISSUE TITLE
Need --optimization-counter-threshold= builder for dartk-strong

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31753]
Just today I've discovered that there are a number of failures when running with low --optimization-counter-threshold, namely these:

```
tools/test.py -m release -c dartk --strong --vm-options=--optimization-counter-threshold=50

Failures:
	service/break_on_default_constructor_test
	service/step_through_constructor_test
	isolate/illegal_msg_mirror_test
	isolate/spawn_function_custom_class_test
	isolate/nested_spawn_test
	isolate/spawn_function_test
	isolate/nested_spawn2_test
	isolate/illegal_msg_function_test
	isolate/message2_test
	isolate/unresolved_ports_test
	isolate/message_test
	isolate/static_function_test
	isolate/cross_isolate_message_test
	isolate/raw_port_test
	isolate/timer_isolate_test
	isolate/request_reply_test
	isolate/isolate_complex_messages_test
	lib_2/mirrors/invocation_fuzz_test/smi
	service/break_on_default_constructor_test
	service/step_through_constructor_test
	isolate/illegal_msg_mirror_test
	isolate/spawn_function_custom_class_test
	isolate/nested_spawn_test
	isolate/spawn_function_test
	isolate/nested_spawn2_test
	isolate/illegal_msg_function_test
	isolate/message2_test
	isolate/unresolved_ports_test
	isolate/message_test
	isolate/static_function_test
	isolate/cross_isolate_message_test
	isolate/raw_port_test
	isolate/timer_isolate_test
	isolate/request_reply_test
	isolate/isolate_complex_messages_test
	lib_2/mirrors/invocation_fuzz_test/smi
```

We already have an opt-counter threshold for the normal JIT, we should get one for dartk-strong as well.

/cc @mraleph @a-siva 

@athomas If our pool is big enough, could you add such a builder?

**Comment by athomas** [comment]
The non-kernel builders that set --optimization-counter-threshold set it to '5', is there are reason to have it on 50 here?

**Comment by athomas** [comment]
Also, for the sim builders we limit the strong mode test steps to these suites:
language_2, corelib_2, lib_2, standalone_2
Should this builder also do that?

**Comment by mkustermann** [comment]
There's no reason why it is 50, it's just a bit faster for me to run the tests. Let's use 5 as with the other one.

Regarding the test suites, I'll delegate to @mraleph @a-siva

**Comment by mraleph** [comment]
We should run all test suites and on simulators as well. If we want to skip something this should be done in status files not on buildbots. @athomas is it possible to remove limitations from simulator bots?

**Comment by athomas** [comment]
Notes from offline discussion:
* All vm kernel builders should run roughly the same steps (they might differ in case there are special options):

0. ("frontend tests": discuss with @peter-ahe-google )
1. "vm tests" tools/test.py -cdartk
2. "strong vm tests" tools/test.py --strong -cdartk

* Exclusion of suites will be done in the status files (e.g. language vs language_2)

**Comment by athomas** [comment]
CL for the test matrix changes: https://dart-review.googlesource.com/#/c/sdk/+/31984
Still WiP until I understand what to do with the front-end test step.

I will create another one for the LUCI config.

**Comment by athomas** [comment]
Builder is now green with the status fixes (https://dart-review.googlesource.com/c/sdk/+/33881) and will appear on the console shortly.
