### ISSUE TITLE
Invalid assignment error for a self-recursive call with a function type.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31759]
```dart
void _mergeSort<T>(T Function(T) list, int compare(T a, T b), T Function(T) target) {
  _mergeSort(list, compare, target);
  _mergeSort(list, compare, list);
  _mergeSort(target, compare, target);
  _mergeSort(target, compare, list);
}
```

This reports two errors:
```
Expected 0 errors of type StaticTypeWarningCode.INVALID_ASSIGNMENT, found 2 (114, 99)
```

**Comment by stereotype441** [comment]
Thank you for reporting this!  This is a subtle one: what's happening is that the front end isn't instantiating a fresh type variable when inferring the type argument in the call from `_mergeSort` to itself.  So it thinks that the types match exactly without the need for any constraints, and therefore it infers that the call is `_mergeSort<dynamic>(list, compare, target)`.

I'll start working on a fix.
