### ISSUE TITLE
Dart sdk build (gclient sync) fails on Windows Subsystem Linux

### ISSUE THREAD

**Issue by Prabhakar-17** [dart-lang/sdk#31754]
Hi,

I am referring this link (https://github.com/dart-lang/sdk/wiki/Building) to build the dart-sdk. gclient sync fails, please refer the attached screenshot for detailed error message.
<img width="960" alt="gclient_sync_error" src="https://user-images.githubusercontent.com/28021552/34525314-76e08bce-f0c4-11e7-85a7-f3005aabdd4f.PNG">

**Comment by mraleph** [comment]
I don't think building Dart in this way is supported (there are also known issues with running Dart within Linux subsystem on Windows). Supported ways is to build on Windows using MSVC toolchain or build on Linux.

Any reason why you would want to build SDK inside Linux subsystem?

**Comment by Prabhakar-17** [comment]
@mraleph Thank you, using MSVC toolchain looks like a little extra effort, I believe things should have been little simpler, to avoid this I thought of building on WSL (Windows subsystem for Linux) assuming that it should work similar to Linux.

I am setting up the environment to contribute to the dart-sdk repo. I prefer using bash as compared to windows terminal.

**Comment by anitha2602** [comment]
Hi,

I am trying to build v8 on WSL, when I do fetch v8, I am getting this error as attached below

![vpython_error](https://user-images.githubusercontent.com/64005001/79733456-cb332c80-8312-11ea-878e-00e920645fad.PNG)

Could anyone please help me with this!

Thanks

**Comment by mraleph** [comment]
@anitha2602 maybe you should V8 team for help with building V8 - this has nothing to do with Dart SDK.

**Comment by mraleph** [comment]
Right now we do not support building Dart on WSL.
