### ISSUE TITLE
Fasta should copy default values of forwarding constructors

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#31767]
Kernel should copy default values of forwarding constructors. 

For instance
```
class C {
  C({a: 0});
}
class M {}
class D = C with M;
```` 
the `a` parameter in constructor `D.` has `null` and not `0` as its default argument.

**Comment by askeksa-google** [comment]
Slightly extended test case to show that this is only a problem when the mixin is applied outside of an extends clause:
```dart
class C {
  C({a: 0}) {
    print(a);
  }
}
class M {}
class D = C with M;
class E extends D {}
class F extends C with M {}

main() {
  new C();
  new D();
  new E();
  new F();
}
```
Prints:
```
0
null
null
0
```

**Comment by peter-ahe-google** [comment]
Fasta isn't adding these constructors correctly:

* Fasta doesn't add constructors to anonymous mixin applications (the VM's mixin transformer adds the constructor in this case, and correctly clones the default values).

* Fasta adds constructors to named mixin applications, but forgets to clone the default values (in this case, the VM's mixin transformer uses the constructor added by Fasta).

**Comment by peter-ahe-google** [comment]
Part 1: create all the constructors in Fasta, not in the transformer: https://dart-review.googlesource.com/c/sdk/+/79241

**Comment by peter-ahe-google** [comment]
As expected, the CL above changes @askeksa-google's example to output:

```
0
null
null
null
```

**Comment by lrhn** [comment]
This does not appear to work yet. Example:
```dart
class C {
  final int w;
  C.foo(int x, [int y = 0, int z = 0]) : w = p("x", x) + p("y", y) + p("z", z);
}

int p(String name, int value) {
  print("$name = $value");
  return value;
}

mixin M on C {
  int get w2 => w * w;
}

class D = C with M;

main() {
  C.foo(1, 2);  // Prints: x = 1, y = 2, z = 0
  D.foo(1, 2);  // Prints: x = 1, y = 2, z = null, then throws `null` error.
}
```
