### ISSUE TITLE
VM handling literal 9223372036854775808 incorrectly with --limit-ints-to-64-bits

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31769]
Given the following:
```
main() => print(9223372036854775808);
```

The VM is silently overflowing.  It fails on larger numbers.

```
dart --limit-ints-to-64-bits int64.dart 
-9223372036854775808
```

@a-siva

**Comment by vsmenon** [comment]
I.e., it triggers a compile-time error on larger numbers.  It works correctly on smaller numbers.  Looks like a boundary case bug.

**Comment by alexmarkov** [comment]
VM relies on the common front-end to correctly report compile-time errors related to large integers.

The support of large integers in the old VM parser is incomplete: old parser does not detect error in this particular corner case (9223372036854775808). It accepts all correct integer literals and rejects all incorrect except 9223372036854775808. The literal 9223372036854775808 is special because it is valid in a limited context (when used in 'unary-'), but invalid in all other contexts according to the spec. For simplicity, old VM parser allows it in all contexts (the plan is to replace old parser with CFE anyway).

Note that this corner case is related to reporting of compile-time errors only. The run-time semantics is all there. For example, int.parse("9223372036854775808") throws an exception.

See also discussion in https://github.com/dart-lang/sdk/issues/31479.

**Comment by vsmenon** [comment]
Thanks for the clarification!

I think it's fine to mark as won't fix then (or, more accurately, it'll be fixed moving to the new front end).

This may be causing similar errors in CFE and Analyzer until they are also running on a VM with the CFE though.

**Comment by alexmarkov** [comment]
> This may be causing similar errors in CFE and Analyzer until they are also running on a VM with the CFE though.

Could you please clarify how this is possible? Unless CFE/Analyzer/dart2js/DDC have '9223372036854775808' literals in their own source code (I can't find any), they should run the same way on VM with and without CFE. The run-time semantics of integers in the VM is the same with and without CFE and it is supposedly complete.

**Comment by a-siva** [comment]
@vsmenon can you clarify ?

**Comment by vsmenon** [comment]
It would appear in the source code it is analyzing / compiling, not its own source.

The analyzer uses the VM's implementation of `int.parse` on literals it analyzes.  It has (or recently had) a problem where it handled:

`-9223372036854775808`

as

`- int.parse("9223372036854775808")`

With bigints, that's fine.

**Comment by rakudrama** [comment]
The fixnum/int64 tests run into the same problem described by Vijay -
int.parse.  This is dart2js crashing the same way as DDC crashes.


00:14 +0: compiling test/int64_test.dart
test/int64_test.dart:767:12:
Internal Error: '9223372036854775808': FormatException: Invalid radix-10 number
9223372036854775808
    check(-9223372036854775808); // Int64.MIN_VALUE
           ^^^^^^^^^^^^^^^^^^^
The compiler is broken.


For now we will make dart2js use the VM with the old unbounded ints. We
will eventually make dart2js use BigInt, but it is a non-trivial task.

There is a separate issue that one might reasonably want to handle 64-bit
unsigned int values.
Should int.parse have an option where it accepts the full range of unsigned
64-bit values and returns the corresponding signed value?

**Comment by alexmarkov** [comment]
According to the [spec](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md)
```dart
int.parse("9223372036854775808")
```
should fail (throw FormatException). When running on the recent VM, it throws FormatException, so the behavior of VM / core lib is correct in this case.

The problem you refer is related to dart2js/DDC implementation not being updated for this language change and there are separate issues about that: https://github.com/dart-lang/sdk/issues/31762, https://github.com/dart-lang/sdk/issues/31763.

**Comment by natebosch** [comment]
This issue has wandered a bit - the original issue of not statically rejecting the example `main() => print(9223372036854775808);` has been fixed. Both analyzer and CFE statically indicate that the int doesn't fit in 64 bits.

The other referenced issues about Dart2Js not running with 64 bit ints have been separately resolved.
