### ISSUE TITLE
DDC fails when running on Dart VM with fixed-size integers

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31763]
Reproduction:
```
DART_VM_OPTIONS=--limit-ints-to-64-bits tools/test.py -m release -c dartdevc -r chrome --checked --strong corelib_2/int_parse_radix_test/none
```

Failure:
```
Runtime error:
Expect.equals(expected: <-0.0>, actual: <-9223372036854776000>) fails.
at Object.dart.throw (http://127.0.0.1:35118/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4912:29)
    at Function._fail (http://127.0.0.1:35118/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:365:17)
    at Function.equals (http://127.0.0.1:35118/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:121:21)
    at int_parse_radix_test_none.main (http://127.0.0.1:35118/root_dart/out/ReleaseX64/generated_compilations/dartdevc-checked-strong/multitest_corelib_2_int_parse_radix_test_none/int_parse_radix_test_none.js:69:20)
```

It looks like DDC generated Dart literal '-9223372036854775808' to JS as '-null'.

**Comment by vsmenon** [comment]
@kmillikin @leafpetersen @rakudrama 

Kevin: will this be a compile-time error in Kernel?

**Comment by leafpetersen** [comment]
cc @lrhn @floitschG 

My understanding is that this should be a compile time error.  There's some question as to whether `-9223372036854775808` should be a compile time error when compiling to JS or not: it's representable, so arguably it should be allowed.

**Comment by alexmarkov** [comment]
According to the [informal spec](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md), -9223372036854775808 is a valid integer literal and should not cause compile time errors. AFAIK CFE/kernel follows the spec.

**Comment by leafpetersen** [comment]
A right, sorry.  Try `-18446744073709551616`.  The point being, there are integers which are precisely representable as 64 bit doubles, but not as 64 bit ints.  Should we statically reject them as literals (they can arise dynamically) or should we allow them?

**Comment by vsmenon** [comment]
Note, JavaScript will silently convert `-9223372036854775808` to `-9223372036854776000`.  We should probably make that literal in Dart a static error on the web (post 2.0).

In general, we've also got bugs around boundary values.  Filed: #31769 #31770 #31771.  I think both DDC and DDC-Kernel will work correctly once those are fixed.

**Comment by rakudrama** [comment]
If I can write

```dart
main() {
  var a = 10000000000; // ten zeroes
  print(a * a);
}
```
and on DDC and dart2js it prints `100000000000000000000`  (20 zeroes approx 1.35 x 2^66)
should I not be allowed to use that greater-than-2^63 number as a literal?

**Comment by lrhn** [comment]
The argument would be that it's likely an error, and we prevent you from doing likely errors. It's for your own protection.
If you actually write:
```dart
main() {
  var a = 1_0000_0000_0000_0000_0000;
  print(a);
}
```
and the VM prints 7766279631452242000, you would be surprised - because you (users in general) expect integer literals to be exact.

**Comment by jmesserly** [comment]
I don't see a failure anymore (with either dartdevc or dartdevk). Assuming stale.
