### ISSUE TITLE
pause_on_unhandled_async_exceptions{,2}_test timeouts on vm-kernel-linux-release-simdbc64

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#31765]
[A](https://ci.chromium.org/p/dart/builds/b8958381792699440768) [lot](https://ci.chromium.org/p/dart/builds/b8958390651689100128) [of](https://ci.chromium.org/p/dart/builds/b8958397261154075872) [timeouts](https://ci.chromium.org/p/dart/builds/b8958412245378227392) [happened](https://ci.chromium.org/p/dart/builds/b8958414120042387792) [recently](https://ci.chromium.org/p/dart/builds/b8958420154316361360) [on](https://ci.chromium.org/p/dart/builds/b8958474860876643968) [the](https://ci.chromium.org/p/dart/builds/b8958538105365577232) [bots](https://ci.chromium.org/p/dart/builds/b8958365484469136624).

The tests that experience the timeouts are the following:
* service/pause_on_unhandled_async_exceptions2_test
* service/pause_on_unhandled_async_exceptions_test

The timeouts seem exclusive to bot vm-kernel-linux-release-simdbc64.

I'm not sure if that's an infrastructure issue or not.

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued.
