### ISSUE TITLE
Writing to existing files on Windows causes the SDK to crash

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#31760]
Using Dart VM version: 2.0.0-dev.15.0 on "windows_x64"

Discovered while updating package:watcher to make use of package:test.

On windows calling

`new File(fullPath).writeAsStringSync(contents);`

where `fullPath` is an existing file causes the SDK to crash.

See:
https://github.com/dart-lang/watcher/blob/master/test/utils.dart#L285

**Comment by bkonyi** [comment]
@grouma, are you still seeing this? I can't reproduce a crash locally.

**Comment by bkonyi** [comment]
Closing for now. Feel free to reopen if there's still an issue.
