### ISSUE TITLE
analyzer appears to parse -9223372036854775808 incorrectly (with VM's --limit_ints_to_64_bits)

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31771]
Given the following:

```
main() => print(-9223372036854775808);
```

the analyzer is creating an IntegerLiteral with value null.  Under the new 64-bit semantics this should be a valid number.  It appears though, that the analyzer is handling as: `-int.parse("9223372036854775808")` instead of `int.parse("-9223372036854775808")`.

The former correctly throws a FormatException.

FYI - @bwilkerson

**Comment by bwilkerson** [comment]
I have changes in flight (https://dart-review.googlesource.com/c/sdk/+/31841, though it had to be reverted because of status file changes I didn't have time to make) to support the new semantics in analyzer. Hope to get those landed this week.

**Comment by bwilkerson** [comment]
The change has landed and analyzer now finds no errors:
```
$ dart --limit_ints_to_64_bits pkg/analyzer_cli/bin/analyzer.dart test.dart
Analyzing test.dart...
No issues found!
```
