### ISSUE TITLE
dartdevc failure on clean install from source

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#31774]
Error below. 

```
timsneath@glinux-timsneath:~$ dartdevc
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/local/google/home/timsneath/dart-sdk/sdk/sdk
    dart --version: 2.0.0-edge.f107599b71d2cc4b3374c5c69619507ac04e0d66 (Thu Jan 4 17:59:16 2018 +0000) on "linux_x64"

FileSystemException(path=/usr/local/google/home/timsneath/dart-sdk/sdk/sdk/lib/_internal/ddc_sdk.sum; message=Cannot open file)
#0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:186:7)
#1      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:489:21)
#2      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:405:43)
#3      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#4      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:405:18)
#5      new SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:41:22)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:347:18)
#7      new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:86:30)
#8      _compile (package:dev_compiler/src/analyzer/command.dart:133:22)
#9      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#10     main (file:///usr/local/google/home/timsneath/dart-sdk/sdk/pkg/dev_compiler/bin/dartdevc.dart:27:16)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

Installed Dart 2.0 from the instructions here: https://github.com/dart-lang/sdk/wiki/Building

Used this command to build:
```
./tools/build.py --mode release --arch x64 create_sdk
```

**Comment by rakudrama** [comment]
I see this often on the build bots after committing an (unrelated, I assume) dart2js change.

**Comment by vsmenon** [comment]
Hmm, this is a recent build that broke.

https://ci.chromium.org/buildbot/client.dart/ddc-mac-release-be/3658

It appears the copy_dev_compiler_summary never happened:

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fddc-mac-release-be%2F3658%2F%2B%2Frecipes%2Fsteps%2Fbuild_dart%2F0%2Fstdout

I see:

```
STAMP obj/sdk/copy_dev_compiler_summary.inputdeps.stamp
```

but no corresponding `COPY`/`ACTION`/`STAMP`.

**Comment by vsmenon** [comment]
@munificent @whesse @zanderso Any tips for chasing this down?  

I'm trying to figure out why this step didn't happened:

https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn#L559

Is GN looking at this obj/sdk/copy_dev_compiler_summary.inputdeps.stamp, the individual source file times, or some combination?

**Comment by zanderso** [comment]
You can invoke ninja directly with the flag `-d explain` to get some more information:
```
$ ninja -C out/ReleaseX64 -d explain create_sdk
```
but it might not help too much if it's failing to build something you thought it should build. I'll be able to take a closer look myself sometime tomorrow.

**Comment by vsmenon** [comment]
Thanks, Zach - that helps me repro.

If I do the following:

```
$  touch sdk/lib/_internal/js_runtime/lib/js_string.dart && ninja -v -C out/ReleaseX64 create_sdk
```

I see the expected step:

```
[62/87] ln -f gen/utils/dartdevc/ddc_sdk.sum dart-sdk/lib/_internal/ddc_sdk.sum 2>/dev/null || (rm -rf dart-sdk/lib/_internal/ddc_sdk.sum && cp -af gen/utils/dartdevc/ddc_sdk.sum dart-sdk/lib/_internal/ddc_sdk.sum)
```

But if I do:

```
$  touch sdk/lib/_internal/js_runtime/lib/js_string.dart && ninja -v -C out/ReleaseX64 dartdevc_test
```

I don't (and I see 82 steps instead of 87).

But, `dartdevc_test` depends on `create_sdk`:

https://github.com/dart-lang/sdk/blob/master/utils/dartdevc/BUILD.gn#L284

**Comment by zanderso** [comment]
We are confusing ninja by deleting some files from the build output directory during the build that it thinks are clean. https://dart-review.googlesource.com/c/sdk/+/33700 should help.

**Comment by zanderso** [comment]
I believe the above CL should have fixed this issue. Please feel free to reopen if it still reproduces.
