### ISSUE TITLE
Front-end appears to parse -9223372036854775808 incorrectly (with VM's  --limit_ints_to_64_bits)

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31770]
Note, this is only when the VM itself is running with 64-bit ints (--limit_ints_to_64_bits).

Or at least, I think we're getting bad kernel nodes.

The following code:

```
main() => print(-9223372036854775808);
```

is generating:
```
9223372036854776000
```
with DDK.

DDK is getting an IntLiteral whose value is -9223372036854775808, but it's parent appears to be a unary negation of the negative value:
```
-9223372036854775808.{dart.core::int::unary-}()
```

The generated JS is, correspondingly, 
```
- -9223372036854775808
```

@kmillikin @peter-ahe-google 

This may be related to or due to #31769

**Comment by sjindel-google** [comment]
I cannot reproduce this error:

```
$ cat test.dart
main() => print(-9223372036854775808);
$  out/ReleaseX64/dart --dfe=pkg/vm/bin/kernel_service.dart --kernel-binaries=out/ReleaseX64 --strong --reify-generic-functions --limit-ints-to-64-bits --packages=$HOME/src/dart-sdk/sdk/.packages test.dart                                                            
-9223372036854775808
```

**Comment by sjindel-google** [comment]
This is not strictly a bug: the unary negation, modulo 64-bits, of -9223372036854775808 is still -9223372036854775808. However, the extra negation is unnecessary.

**Comment by vsmenon** [comment]
It would not be a (strictly) bug if all platforms had the same `int` semantics.  :-)

In general, we'll need to be defensive about compiling with 64-int (VM semantics) and running with double (JS semantics).

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/33943
