### ISSUE TITLE
Please mirror test_descriptor and test_process

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#31772]
I'm pulling the latest dart_style into the repo, and it uses those two new packages, which are replacements for the old scheduled_test package dart_style used to use. Those packages are ours:

https://github.com/dart-lang/test_descriptor
https://github.com/dart-lang/test_process

For now, I'll have the DEPS file point directly to those URIs with a TODO mentioning this bug.

cc @whesse

**Comment by whesse** [comment]
The two repos are now mirrored to dart.googlesource.com, so the DEPS change can use the dart_git variable, or if it has landed, a followup CL can change the references to use that variable.

The repos are not mirrored to chromium.googlesource.com/external/github.com/dart-lang, and none of our code or DEPS will be fetching them from that location.

**Comment by whesse** [comment]
Example:
Var("dart_git") + "test_descriptor.git" + Var("test_descriptor_tag")
Var("dart_git") + "test_process.git" + Var("test_process_tag")

**Comment by munificent** [comment]
Thanks!
