### ISSUE TITLE
HttpOverrides API doesn't work for flutter_test package

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31785]
The flutter_test package needs to override the HttpClient globally, but currently dart:io only supports doing that within a zone. The flutter_test package isn't in control of the root zone.

With our current mocking solution we just override a global function that is used by anyone who wants to construct an HttpClient, but that won't work if we switch to dart:io.HttpClient.

cc @sethladd

**Comment by matanlurey** [comment]
Can `flutter_test` always start `main()` in its own Zone?

pkg/test does something like this now.

**Comment by Hixie** [comment]
`flutter test` could, but that doesn't necessarily first import `flutter_test`. `flutter_test` is just a package a test can import and use, it's not required (and indeed can't be required) for all tests run with `flutter test`.

**Comment by nex3** [comment]
Would something like https://github.com/dart-lang/test/issues/377 work for this?

**Comment by Hixie** [comment]
I don't really see how? Ideally the test writer wouldn't have to even know about this. The flutter_test library just wants to hook a bunch of global hooks, it doesn't want to require that the test author worry about it. The simplest solution I can see here is to not use Zones at all and just have a global variable, like we already do.

**Comment by nex3** [comment]
Doing this in `test` with zero user intervention would be possible with https://github.com/dart-lang/test/issues/710, although last I heard worker plugins were not something the build team was excited about, since they mean the test runner has to be responsible for spawning tests (as opposed to the build tool).

**Comment by zanderso** [comment]
Does setting ‘HttpOverrides.global’ work? https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/overrides.dart#L44

**Comment by Hixie** [comment]
HttpOverrides.global is exactly what we need, yet! I did not see that in the documentation for some reason.
