### ISSUE TITLE
DDK doesn't support fromEnvironment constructors 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31781]
The following generates a runtime error.  With DDC, it prints `false`.

```dart
void main() {
  print(const bool.fromEnvironment('dart.isVM'));
}
```

**Comment by vsmenon** [comment]
@jmesserly 

@sigmundch - is there a list of env variables we need to support by default?

**Comment by sigmundch** [comment]
Mainly: `dart.library.io` and `dart.library.html` (and for that matter `dart.library.*` where * is any of the platform libraries that distinguish the platform, for example it might be good to include `dart.library.ui` to recognize flutter).

But those two would be all you need to make this test pass:

https://github.com/dart-lang/sdk/blob/master/tests/language_2/conditional_import_test.dart
