### ISSUE TITLE
dart2js - make compilation independent of host 'int' implementation

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#31788]
dart2js relies on unbounded precision int values during compilation. This is a problem when the VM uses 64-bit ints https://github.com/dart-lang/sdk/issues/31762.

We should use `BigInt` instead of `int`, but it is not that simple because the whole constant system embeds the assumption that the compile time value representing an int constant value can be represented by an int. The assumptions are deep - for example, it is assumed that the compile time value representing an int implements `num`.

- [x] Clean up ConstantValue hierarchy to minimize representation assumptions.
- [x] Clean up uses of constant values.
- [x] Clean up range analysis - might need to model ranges using BigInt.
- [x] Replace `int` with `BigInt`.

**Comment by efortuna** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/55500

**Comment by sigmundch** [comment]
Woohoo!

I just realized that we have one more step: we need to remove where we use `--no_limit_ints_to_64_bits` in our scripts and snapshots :). We added them all together in 0c04eb53c76, so I expect it might just be a CL partially reverting it.

**Comment by dgrove** [comment]
Any updates on this, @efortuna ?

**Comment by efortuna** [comment]
I have a CL with the change implemented. I am in the process up updating the status files as a result (there are a lot of status file changes). Should be done by EOD today.

**Comment by efortuna** [comment]
Committed!

**Comment by alexmarkov** [comment]
Yay! Can we remove --no_limit_ints_to_64_bits from VM now?
