### ISSUE TITLE
Meta  issue to track progress of --preview-dart-2 being turned on by default in flutter

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31789]
This meta issue has been created to track blocker issues that prevent running flutter
apps in strong mode.

**Comment by a-siva** [comment]
Current blocker issues 
- #31656 which seems to be dependent on #30674, #31118 (these issues are causing compile time errors)

**Comment by mit-mit** [comment]
@a-siva Leaf completed the roll, so flutter/flutter is now on `Dart 2.0.0-dev.16.0`, so I marked that complete in your blocker list.

**Comment by mit-mit** [comment]
Hi @a-siva what is blocking this now?

**Comment by mraleph** [comment]
@mit-mit I would say mixins are blocking this now, we are not blocked from resolving individual issues but mixins is a big-big-big problem. I think it even is blocking SDK roll.

**Comment by a-siva** [comment]
I moving the milestone of this to 2.0-alpha-2 and changed the description to make this the meta issue to track turning the --preview-dart-2 flag on by default in flutter.
