### ISSUE TITLE
hotReloadVmReloadMilliseconds benchmark is showing massive regression

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31796]
hotReloadVmReloadMilliseconds benchmark is showing massive regression
26 ms => 483 ms

This is without the --preview-dart-2 flag.

**Comment by aam** [comment]
More discussion on this at https://github.com/flutter/flutter/commit/8da5af55c513511da75042c0a9d4beaf0597af5e#commitcomment-26656877

**Comment by aam** [comment]
https://github.com/flutter/flutter/pull/13934 should fix this.
