### ISSUE TITLE
would like a Flutter refactoring to be able to swap a child with its parent ('Swap with parent')

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#31806]
Consider:
```dart
...
new Column(
  children: <Widget>[
    new A(
      child: new B(
        ...
      ),
    ),  
  ],
),
...
```

The move widget up/down mechanism doesn't allow B to be swapped up with A

**Comment by bwilkerson** [comment]
@stevemessick

**Comment by bwilkerson** [comment]
@devoncarew @scheglov

**Comment by scheglov** [comment]
@xster, do you have a use case for this when writing Flutter code? I assume that you ran into this situation; we're having trouble here imagining a scenario for a swap refactoring. The title of the issue seems to indicate this would be more of a 'make the node a sibling of it's parent'.

**Comment by xster** [comment]
It's fairly common when writing Flutter. Say under a Column, you have a Padding, a GestureDetector and a DecoratedBox and you want to experiment with various permutations of the hierarchical ordering. Currently, you can't swap between the first child under Column and its descendants.

**Comment by scheglov** [comment]
Hm... It must have been fixed.
This works for me now.

Do I still misunderstand the problem, or it is really fixed now?

```dart
import 'package:flutter/material.dart';

main() {
  new Column(
    children: <Widget>[
      new Padding(
        padding: const EdgeInsets.all(8.0),
        child: new Center(
          heightFactor: 0.5,
          child: new Text('foo'),
        ),
      ),
    ],
  );
}
```

When activated on `new Center`:

![image](https://user-images.githubusercontent.com/384794/36001512-530c8576-0cdb-11e8-80b7-bbe7e1acb10b.png)

It gives in result:
```dart
import 'package:flutter/material.dart';

main() {
  new Column(
    children: <Widget>[
      new Center(
        heightFactor: 0.5,
        child: new Padding(
          padding: const EdgeInsets.all(8.0),
          child: new Text('foo'),
        ),
      ),
    ],
  );
}
```

**Comment by xster** [comment]
Ummmm might have been recently fixed somewhere. Will test.

**Comment by escamoteur** [comment]
I think this could be closed
