### ISSUE TITLE
Implement support for _extractTypeArguments in the VM

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31805]
Please see issue #31371 for more details on why _extractTypeArguments is needed.

This issue tracks support for _extractTypeArguments in the VM

**Comment by crelier** [comment]
Working on it, as well as on two features required in the VM to support _extractTypeArguments:
1) Support calling generic functions via DartEntry::InvokeFunction().
2) Support native generic functions. These are currently allowed, but type arguments are ignored, and therefore not accessible from the C++ side.
