### ISSUE TITLE
Analyzer: Dart 2 allows a non-platform library to shadow a declaration from a platform library.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31836]
If two different library imports introduce different declarations with the same name, and that name is referenced by the importing library, it's a compile time error, except that if all but one of the declarations are from platform libraries, then the name refers to the declaration from the non-platform library.
In Dart 1, that case also caused a warning. In Dart 2, we decided to remove the warning instead of upgrading it to an error.

So, Dart 2 implementations should not have any problem with:
```dart
import "lib1.dart";  // shadows identical from dart:core
main() {
  print(identical());  // 42!
}
```
and
```dart
library lib1;
int identical() => 42;
```
It should cause neither warning nor error.

**Comment by scheglov** [comment]
Was fixed in db8b6bc549232b47d0a54e679a0da6119381aec6.
