### ISSUE TITLE
analyzer ConstantVerifier reports wrong errors

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#31835]
In [linter `prefer_const_constructors`](https://github.com/dart-lang/linter/blob/59f5941cb672ef055c58ba87bf6991db91fa0a3e/lib/src/rules/prefer_const_constructors.dart#L90-L106) we use ConstantVerifier to test if const can be used to instanciate an object. In the following case, no lint is trigger:

```dart
// a.dart
class A {
  const A();
  static const A instance = const A();
}

// b.dart
import 'a.dart';
class B {
  const B(this.v);
  final B v;
}
f1() => new B(A.instance); // should LINT but nothing
```

The last line is not linted because the evaluation of `const B(A.instance)` with `ConstantVerifier` triggers 2 errors: `CompileTimeErrorCode.INVALID_CONSTANT` and `CompileTimeErrorCode.CONST_WITH_NON_CONSTANT_ARGUMENT`. However using `const` instead of `new` does not trigger error with analyzer.

Note that using `new B(const A());` triggers correctly a lint to use `const B(const A())`. So the issue seems to be with constant fields defined in an other library.

(tested with 2.0.0-dev.15.0 and 1.25.0-dev.11.0)

**Comment by a14n** [comment]
The issue seems to be that `ConstantExpressionsDependenciesFinder` do not collect identifiers pointing on const elements.

I tried some changes and make it work

```diff
index b097c0e..88b00cc 100644
--- a/pkg/analyzer/lib/src/dart/constant/utilities.dart
+++ b/pkg/analyzer/lib/src/dart/constant/utilities.dart
@@ -124,6 +124,17 @@ class ConstantExpressionsDependenciesFinder extends RecursiveAstVisitor {
   }

   @override
+  void visitSimpleIdentifier(SimpleIdentifier node) {
+    final element = node.staticElement;
+    if (element is PropertyAccessorElement &&
+        element.variable is ConstVariableElement) {
+      _find(node);
+    } else {
+      super.visitSimpleIdentifier(node);
+    }
+  }
+
+  @override
   void visitListLiteral(ListLiteral node) {
     if (node.constKeyword != null) {
       _find(node);
``` 

Unfortunately this change makes some tests failed and I don't know what should be done to make tests succeed.

**Comment by bwilkerson** [comment]
It looks like there's a typo in the example. The classes `A` and `B` are not related to each other, so the use of an instance of `A` as an argument to the constructor for `B`, which expects a `B` is not valid. Try changing the type of the field `v` to `A`.

Perhaps the constant evaluator doesn't check assignability in some case where it ought to.

**Comment by a14n** [comment]
Sorry I made a typo when copying the test I made. My test didn't have the typo. I just redo the test with the following code and face the same issue.

```dart
// a.dart
class A {
  const A();
  static const A instance = const A();
}

// b.dart
import 'a.dart';
class B {
  const B(this.v);
  final A v;
}
B f1() => new B(A.instance); // should LINT but nothing
```

Note that I see the same kind of issue for the [upcoming version of `prefer_const_declarations`](https://github.com/dart-lang/linter/pull/880) (that also use ConstantVisitor) with the following code:

```dart
// a.dart
class A {
  const A();
  static const A instance = const A();
}

// b.dart
import 'a.dart';
void main() {
  final a = A.instance; // should LINT but nothing
}
```
