### ISSUE TITLE
Remove deprecated_InputError from Fasta

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#31833]
Sometimes Fasta handles errors by giving up. This breaks analyzer integration and incremental compilation, and needs to be fixed before either can be considered ready for early access testing.

Concretely, these methods needs to be removed:

* KernelTarget.handleInputError
* KernelTarget.erroneousProgram

However, before these methods can be removed, we need to stop throwing deprecated_InputError in Fasta. This means that the following 25 uses of `deprecated_inputError` need to be removed:

1. `pkg/front_end/lib/src/fasta/io.dart:import 'deprecated_problems.dart' show deprecated_inputError;`
2. `pkg/front_end/lib/src/fasta/io.dart:    return deprecated_inputError(uri, -1, message);`
3. `pkg/front_end/lib/src/fasta/kernel/kernel_procedure_builder.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
4. `pkg/front_end/lib/src/fasta/kernel/kernel_procedure_builder.dart:      return deprecated_inputError(fileUri, initializer.fileOffset,`
5. `pkg/front_end/lib/src/fasta/kernel/kernel_procedure_builder.dart:        deprecated_inputError(fileUri, initializer.fileOffset,`
6. `pkg/front_end/lib/src/fasta/kernel/kernel_procedure_builder.dart:      deprecated_inputError(fileUri, initializer.fileOffset,`
7. `pkg/front_end/lib/src/fasta/kernel/kernel_type_variable_builder.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
8. `pkg/front_end/lib/src/fasta/kernel/kernel_type_variable_builder.dart:      return deprecated_inputError(null, null,`
9. `pkg/front_end/lib/src/fasta/quote.dart:import 'deprecated_problems.dart' show deprecated_inputError;`
10. `pkg/front_end/lib/src/fasta/quote.dart:    deprecated_inputError(null, null, message);`
11. `pkg/front_end/lib/src/fasta/source/diet_listener.dart:    show Crash, deprecated_InputError, deprecated_inputError;`
12. `pkg/front_end/lib/src/fasta/source/diet_listener.dart:      return deprecated_inputError(`
13. `pkg/front_end/lib/src/fasta/source/source_library_builder.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
14. `pkg/front_end/lib/src/fasta/source/source_library_builder.dart:      deprecated_inputError(fileUri, -1,`
15. `pkg/front_end/lib/src/fasta/source/source_library_builder.dart:      deprecated_inputError(`
16. `pkg/front_end/lib/src/fasta/source/source_loader.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
17. `pkg/front_end/lib/src/fasta/source/source_loader.dart:      return deprecated_inputError(`
18. `pkg/front_end/lib/src/fasta/source/source_loader.dart:        return deprecated_inputError(uri, -1, e.message);`
19. `pkg/front_end/lib/src/fasta/source/stack_listener.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
20. `pkg/front_end/lib/src/fasta/source/stack_listener.dart:      deprecated_inputError(`
21. `pkg/front_end/lib/src/fasta/source/stack_listener.dart:    throw deprecated_inputError(uri, token.charOffset, message.message);`
22. `pkg/front_end/lib/src/fasta/testing/environment_variable.dart:import '../deprecated_problems.dart' show deprecated_inputError;`
23. `pkg/front_end/lib/src/fasta/testing/environment_variable.dart:    deprecated_inputError(`
24. `pkg/front_end/lib/src/fasta/testing/environment_variable.dart:    deprecated_inputError(`
25. `pkg/front_end/lib/src/fasta/testing/environment_variable.dart:    deprecated_inputError(`

**Comment by peter-ahe-google** [comment]
P1 as I think this is a show-stopper for hot reload (incremental compilation).

**Comment by danrubel** [comment]
I believe this has been accomplished. Please reopen if that is not the case.
