### ISSUE TITLE
ResynthesizeKernelStrongTest timeouts

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#31832]
ResynthesizeKernelStrongTest was switched to FrontEndCompiler in https://github.com/dart-lang/sdk/commit/8ed12e00ce75782401d434ab402641fd2a713114 which led to timeouts on the bots [pkg-win7-release-be](https://uberchromegw.corp.google.com/i/client.dart/builders/pkg-win7-release-be/builds/9114), [analyzer-win7-release-strong-be](https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer-win7-release-strong-be/builds/6105), and [analyzer-win7-release-be](https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer-win7-release-be). It now fails to complete in 4 minutes, and was able to do so previously in less than 40 seconds.

@scheglov What do you think is the best solution? Is there an easy way to make the test faster? I talked to @athomas about the issue, and he doesn't mind increasing the time limit beyond 4 minutes, so please contact him if there is no easy way of making the test faster.

**Comment by scheglov** [comment]
It is suspicious that failures happen only on Windows.
Looking into [the first log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fpkg-win7-release-be%2F9114%2F%2B%2Frecipes%2Fsteps%2Fpackage_unit_tests%2F0%2Fstdout) it seems to me that the problem is not with the speed, but with URIs.

```
00:01 [32m+0[0m[31m -1[0m: ResynthesizeKernelStrongTest | test_class_abstract [1m[31m[E][0m[0m
  dart:_internal: Internal problem: The URI 'C%3A%5Csdk%5Clib%5C_internal%5Cinternal.dart' has no scheme.
  package:front_end/src/fasta/problems.dart 29:3                      internalProblem
  package:front_end/src/fasta/source/source_loader.dart 123:14        SourceLoader.tokenize
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                      _Completer.completeError
  package:front_end/src/fasta/source/source_loader.dart               SourceLoader.tokenize
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                           _CustomZone.registerCallback
  dart:async/zone.dart 964                                            _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                              scheduleMicrotask
  dart:async/future.dart 198                                          new Future.microtask
  package:front_end/src/fasta/source/source_loader.dart 117:50        SourceLoader.tokenize
  package:front_end/src/fasta/source/source_loader.dart 176:26        SourceLoader.buildOutline
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                           _CustomZone.registerCallback
  dart:async/zone.dart 964                                            _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                              scheduleMicrotask
  dart:async/future.dart 198                                          new Future.microtask
  package:front_end/src/fasta/source/source_loader.dart 175:65        SourceLoader.buildOutline
  package:front_end/src/fasta/loader.dart 162:13                      Loader.buildOutlines
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                           _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40                     _asyncThenWrapperHelper
  package:front_end/src/fasta/loader.dart 157:38                      Loader.buildOutlines
  package:front_end/src/fasta/kernel/kernel_target.dart 226:20        KernelTarget.buildOutlines
```

  I will try it locally on Windows to see why we get such URIs.

**Comment by scheglov** [comment]
This is a bug in the resynthesizer and the test.
This CL should fix both.
https://dart-review.googlesource.com/c/sdk/+/33982
