### ISSUE TITLE
Add Dart 2.0 migration stubs to packages that implement Stream, StreamTransformer, and Converter

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#31847]
To help with the migration and changes to the core libs,  stubs will be added to a number of core packages that implement these interfaces to ensure that these packages remain unbroken during the transition. These migration stubs can be replaced by full implementations at any time.

Stub template here: https://gist.github.com/lrhn/b99fe5f73a10b3b1a91579853056d08b .

Packages to be updated:

- [x] _discoveryapis_commons
  - [x] PR: https://github.com/dart-lang/discoveryapis_commons/pull/11
  - [x] Roll internal
- [x]  async
  - [x] Initial update: https://github.com/dart-lang/async/pull/45
  - [x] Roll Deps
  - [x] Roll internal
  - [x] Clean up interim APIs: https://github.com/dart-lang/async/issues/53
    - https://github.com/dart-lang/async/pull/54
- [x]  bazel_worker
- [x]  grpc
- [x] http2
- [x] http_server
  - [x] PR: https://github.com/dart-lang/http_server/pull/39
  - [x] Roll internal
- [x] mime
  - [x] PR: https://github.com/dart-lang/mime/pull/16
  - [x] Roll deps
  - [x] Roll internal
- [x] shuttlecock
  - [x] First PR here: https://github.com/alexeieleusis/shuttlecock/pull/41
  - [x] Roll internal
  - [x] Second PR is prepared in a branch: https://github.com/leafpetersen/shuttlecock/tree/corelib_2_2_2
  - [x] Roll internal
- [x] stream_transform
  - [x] PR: https://github.com/dart-lang/stream_transform/pull/42
     - published as 0.0.10
  - [x] Roll internal
- [x] testing
  - [x] https://dart-review.googlesource.com/37864
- [x] utf
  - [x] PR: https://github.com/dart-lang/utf/pull/6
  - [x] Roll deps
  - [x] Roll internal
- [x] vm_service_client
  - [x] PR: https://github.com/dart-lang/vm_service_client/pull/24
  - [x] Roll internal
- [x] watcher
  - [x] PR: https://github.com/dart-lang/watcher/pull/47
  - [x] Roll deps
  - [x] Roll internal
- [x] web_socket_channel
  - [x] PR: https://github.com/dart-lang/web_socket_channel/pull/11
  - [x] Roll deps
  - [x] Roll internal

**Comment by keertip** [comment]
cc @anders-sandholm @lrhn @matanlurey @grouma @srawlins

**Comment by leafpetersen** [comment]
cc @lrhn @anders-sandholm @keertip @grouma @matanlurey @srawlins @vsmenon @dgrove @kevmoo

**Comment by leafpetersen** [comment]
Closing this, since the API changes are all done.  If we need package updates for *uses* of defaultValue, I'll file a separate issue.
