### ISSUE TITLE
`class Maps` is no good for Dart 2.0

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#31843]
The [Maps methods](https://github.com/dart-lang/sdk/blob/master/sdk/lib/collection/maps.dart#L241) have no generics. You get a USES_DYNAMIC_AS_BOTTOM warning for the following code ([dartpad](https://dartpad.dartlang.org/735bdad7d2c3db95bbd197cf135ceab7)):

```dart
import 'dart:collection';

void main() {
  Map<int, int> m = {1: 2, 2: 3};
  Maps.forEach(m, (int a, int b) => print(a*b));
}
```

I propose we delete it :grin: 

TODO

* [x] Breaking change announcement
* [ ] Clean up internal code
* [ ] Land it

**Comment by srawlins** [comment]
CC @lrhn @leafpetersen

**Comment by lrhn** [comment]
The entire `Maps` class is scheduled for removal in Dart 2. It was intended as helper methods when you had to implement the `Map` methods, but that has been subsumed by mixins. If you need a class to implement `Map`, use either `MapMixin` or `MapBase`.

**Comment by srawlins** [comment]
Sounds good.

**Comment by leafpetersen** [comment]
I think we can be pretty lightweight with this one since I don't expect much if any use.  How about:

TODO
 - [ ] Breaking change announcement
 - [ ] Clean up internal code
 - [ ] Land it

**Comment by lrhn** [comment]
Removal CL is ready: https://dart-review.googlesource.com/c/sdk/+/39880
Internal code is down to one usage (AFAICS).

**Comment by leafpetersen** [comment]
Did the CL removing this land yet?

**Comment by srawlins** [comment]
Not yet. Waiting on @cbracken to release quiver, so that we don't break everyone's travis by deleting Maps w/o a `pub get`able quiver version that doesn't use it.

**Comment by cbracken** [comment]
v0.28.1 published on pub.
