### ISSUE TITLE
incorrect handling of operator== methods that return null

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#31854]
DDC assumes `==` will always return a non-null value, but consider:
```dart
class C {
  operator ==(x) => null;
}
main() {
  var c = new C();
  if (c == c) {} else { print('oops! silently coerced null'); }
}
```
results in:
```
$ ./tool/ddc test.dart 
oops! silently coerced null

$ dart -c test.dart
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      main (test.dart:6:9)
```
This is difficult to fix without adversely affecting performance/code size. The naive fix (treat `==` as nullable) would not be acceptable.

As a band-aid, we could inject a not-null check for the return value(s) of a user-defined `operator==` method. That would prevent the incorrect coercion. It would reject some programs that are technically correct under the current specification, however.

Returning null from `==` does not occur in practice, because programmers assume == should not return null, even though Dart does not enforce it. There is some precedent for the language specifying special rules for return values of operator methods (`[]=` discards the return value). So we could consider a small change to enforce this at the language level. It will have to happen anyway once we introduce non-null types (CC @leafpetersen).

The real fix would be to generate a second method stub for every user defined == method. The stub method adds the not-null check. We call the "not null equals" stub whenever we require a not-null value. This approach would also let us optimize `int get length`, another method that suffers from nullability of primitive types. This requires no language changes.

**Comment by leafpetersen** [comment]
@lrhn Any thoughts about changing this in the language?  I'd be fine with the restriction, and it would probably help on AOT native as well.

**Comment by lrhn** [comment]
I would not touch it now. If/when we get non-nullable types, we make `Object.operator==` return non-nullable bool.

If it's a compilation problem for DDC, then I'd probably just ignore it. It's a non-language-correct compilation optimization, but hardly the only one, and compared to different integers, I'm not sure anyone would even notice. When they compile with dart2js afterwards, they'll probably turn off all type checks anyway.

What I would like is the analyzer implicitly assuming that implementations of `==`, `hashCode`, and `toString` should return non-null values, so any explicit return of `null` will be caught.

The `[]=` isn't really relevant, it's just a special kind of setter. We don't have special treatment of any a method that actually does return a value.

**Comment by jmesserly** [comment]
going to close this out based on discussion above (resolution: not planned)
