### ISSUE TITLE
Missing error for inherited field conflicting with a method

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31850]
```dart
class A {
  final int m = 0;
}
class B extends A {
  m() {}
}
```

```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ pkg/front_end/tool/fasta compile --strong /Users/scheglov/dart/test/bin/test.dart
Note: strong mode support is preliminary and may not work.
```

No error is reported.

**Comment by scheglov** [comment]
See the specification, `10.2 Getters`.

![image](https://user-images.githubusercontent.com/384794/34794758-8cfd98e4-f604-11e7-9f0c-dc691322a8b0.png)

**Comment by scheglov** [comment]
The same problem when a method is declared in the superclass, and with getters and setters.

**Comment by kmillikin** [comment]
As of 8f6c6c2a8edd514cdb6533541189a6572318facd we signal this error:

```
[snip]/override-mess.dart:6:3: Error: Can't declare a member that conflicts with an inherited one.
  m() {}
  ^
[snip]/override-mess.dart:2:13: Context: This is the inherited member.
  final int m = 0;
```

An error (legacy Dart warning) is signaled when you declare a method and inherit a getter or setter, or declare a getter or setter and inherit a method, or inherit both a method and a getter or setter.
