### ISSUE TITLE
Ensure Dart1 and Dart2 can be used together 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#31859]
From #31807

> Will Dart2 run Dart1 programs or
> will there be a way to have Dart1 and Dart2 installed at the same time?

 @dgrove
> The SDK is gradually moving to running Dart 2 only. As the SDK gets to Dart 2 only, you'd need a separate SDK installed to run Dart 1.

 @zoechi
> Don't you think this will cause issues if people use Dart apps that are not yet ported?
> There can't be 2 dart.exe in the path at the same time.
> Sorry for the noise in this thread, is it worth creating a new issue for that?

 @dgrove
> Can you open a new issue?

**Comment by matanlurey** [comment]
I don't understand this issue? You would need to have the Dart 1 SDK installed to run Dart 1 apps.

**Comment by natebosch** [comment]
Someone from the community could try making a `dvm` version manager helper to make it easier to have multiple SDKs on the same computer and switch between them.

I don't think we'll reasonably be able to keep dart 1 semantics around in the VM or elsewhere.

**Comment by zoechi** [comment]
@matanlurey sure, but how can I if both use `dart.exe`

I'd expect this to be easier if the Dart team considers it in the design.
There was and is a lot of work done to avoid breaking changes,
 but then installing Dart2 on a system rendering all existing Dart1 tools unusable is just ignored. 
That seems weird to me.

What about `pub` and `dart.exe` forwarding to Dart1 if it recognizes a Dart1 package or executable and the `DART1_SDK_PATH` env variable is set?

Just a first idea to initiate some brainstorming.

**Comment by matanlurey** [comment]
It's no different than if you started using a new language feature (like generic functions) on an older version of the SDK that couldn't parse/recognize it. While it's possible we could provide a convenience to forward to an older version of tooling, it's not likely this is something we'd do ourselves. The community of course is welcome!
