### ISSUE TITLE
Upload sdk 2.0

### ISSUE THREAD

**Issue by caoyarzom** [dart-lang/sdk#31862]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4127.31`
- `2.0.0-dev.16.0`
- `WS-173.4127.31, JRE 1.8.0_152-release-1024-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1280x800, 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/nm/_jmwx_c94dsb6bxp161w0hgw0000gp/T/report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: /Users/tinguinito/angular-examples/angular_tour_of_heroes/test/app_test.dart context: exception_20180111_150829_692
NoSuchMethodError: The getter 'units' was called on null.
Receiver: null
Tried calling: units
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:3715)
#3      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3520)
#4      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3559)
#5      _HashVMBase

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
