### ISSUE TITLE
Remove warning when a non-platform library introduces the same name as a platform library

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31866]
Quoting from a comment by @lrhn in https://dart-review.googlesource.com/c/sdk/+/33662:

> In Dart 2 there should not be a warning when a non-platform library (not "dart:...") import introduces the same name as a platform-library. The non-platfrom version should implicitly shadow the platform library version.

**Comment by bwilkerson** [comment]
Duplicate of #31836.
