### ISSUE TITLE
Kernel reader crashes during service tests running in static mode

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#31868]

**Comment by rmacnak-google** [comment]
add_breakpoint_rpc_kernel_test: RuntimeError # Issue 31868
async_next_test: RuntimeError # Issue 31868
async_scope_test: RuntimeError # Issue 31868
async_single_step_exception_test: RuntimeError # Issue 31868
async_single_step_into_test: RuntimeError # Issue 31868
break_on_function_test: RuntimeError # Issue 31868
breakpoint_in_parts_class_test: RuntimeError # Issue 31868
breakpoint_two_args_checked_test: RuntimeError # Issue 31868
caching_test: RuntimeError # Issue 31868
causal_async_stack_contents_test: RuntimeError # Issue 31868
causal_async_stack_presence_test: RuntimeError # Issue 31868
causal_async_star_stack_contents_test: RuntimeError # Issue 31868
causal_async_star_stack_presence_test: RuntimeError # Issue 31868
debugger_location_second_test: RuntimeError # Issue 31868
debugger_location_test: RuntimeError # Issue 31868
debugging_inlined_finally_test: RuntimeError # Issue 31868
debugging_test: RuntimeError # Issue 31868
developer_service_get_isolate_id_test: RuntimeError # Issue 31868
get_object_rpc_test: RuntimeError # Issue 31868
get_object_store_rpc_test: RuntimeError # Issue 31868
get_stack_rpc_test: RuntimeError # Issue 31868
issue_25465_test: RuntimeError # Issue 31868
issue_27238_test: RuntimeError # Issue 31868
issue_27287_test: RuntimeError # Issue 31868
local_variable_declaration_test: RuntimeError # Issue 31868
mixin_break_test: RuntimeError # Issue 31868
next_through_assign_call_test: RuntimeError # Issue 31868
next_through_assign_int_test: RuntimeError # Issue 31868
next_through_call_on_field_in_class_test: RuntimeError # Issue 31868
next_through_call_on_field_test: RuntimeError # Issue 31868
next_through_call_on_static_field_in_class_test: RuntimeError # Issue 31868
next_through_catch_test: RuntimeError # Issue 31868
next_through_closure_test: RuntimeError # Issue 31868
next_through_create_list_and_map_test: RuntimeError # Issue 31868
next_through_for_each_loop_test: RuntimeError # Issue 31868
next_through_for_loop_with_break_and_continue_test: RuntimeError # Issue 31868
next_through_function_expression_test: RuntimeError # Issue 31868
next_through_implicit_call_test: RuntimeError # Issue 31868
next_through_is_and_as_test: RuntimeError # Issue 31868
next_through_multi_catch_test: RuntimeError # Issue 31868
next_through_new_test: RuntimeError # Issue 31868
next_through_operator_bracket_on_super_test: RuntimeError # Issue 31868
next_through_operator_bracket_on_this_test: RuntimeError # Issue 31868
next_through_operator_bracket_test: RuntimeError # Issue 31868
next_through_simple_async_with_returns_test: RuntimeError # Issue 31868
next_through_simple_linear_2_test: RuntimeError # Issue 31868
next_through_simple_linear_test: RuntimeError # Issue 31868
parameters_in_scope_at_entry_test: RuntimeError # Issue 31868
positive_token_pos_test: RuntimeError # Issue 31868
regress_28443_test: RuntimeError # Issue 31868
regress_28980_test: RuntimeError # Issue 31868
rewind_optimized_out_test: RuntimeError # Issue 31868
rewind_test: RuntimeError # Issue 31868
set_library_debuggable_test: RuntimeError # Issue 31868
steal_breakpoint_test: RuntimeError # Issue 31868
step_into_async_no_await_test: RuntimeError # Issue 31868
step_over_await_test: RuntimeError # Issue 31868
step_through_arithmetic_test: RuntimeError # Issue 31868
step_through_constructor_calls_test: RuntimeError # Issue 31868
step_through_constructor_test: RuntimeError # Issue 31868
step_through_function_2_test: RuntimeError # Issue 31868
step_through_function_test: RuntimeError # Issue 31868
step_through_getter_test: RuntimeError # Issue 31868
step_through_property_get_test: RuntimeError # Issue 31868
step_through_property_set_test: RuntimeError # Issue 31868
step_through_setter_test: RuntimeError # Issue 31868
step_through_switch_test: RuntimeError # Issue 31868
step_through_switch_with_continue_test: RuntimeError # Issue 31868

**Comment by mraleph** [comment]
@jensjoha can you look at this if you have free cycles?

**Comment by mraleph** [comment]
I am marking this P0 until we know the reason for crashes.

**Comment by mraleph** [comment]
(@rmacnak-google fwiw there is no such thing as "static" mode)
