### ISSUE TITLE
Fuzzy arrow / dynamic as bottom is a hint, but should be a warning

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#31874]
We stumbled over the `grpc-dart` repo not passing `uses_dynamic_as_bottom` by coincidence despite that repo running analysis on travis. The issue is that we currently report this as just a hint, which doesn't fail the build:

```
$ dartanalyzer lib test
Analyzing lib, test...
  hint • A function of type '(Socket) → void' can't be assigned to a variable of type '(dynamic) → FutureOr<void>' at lib/src/client/connection.dart:108:22 • uses_dynamic_as_bottom
```

Shouldn't this at least be a warning?

**Comment by mit-mit** [comment]
cc @leafpetersen

**Comment by vsmenon** [comment]
This will eventually become an error.  Not sure it's worth making it a warning as an intermediate step.

**Comment by leafpetersen** [comment]
It might be worth making this a warning, if we can do so without breaking the internal builds (we're currently working on eliminating the hint internally).  Making it a warning earlier might help us avoid accidental regressions.  I'll look into it.

In the meantime if you want to protect against this, you can put the following in your analysis options file:

```
analyzer:
  errors:
    uses_dynamic_as_bottom: warning
```

**Comment by leafpetersen** [comment]
@srawlins if we promoted this from hint to warning, could we keep it from breaking builds internally?

**Comment by srawlins** [comment]
It won't break anything internally.

**Comment by leafpetersen** [comment]
I have a CL for this, but have to land a CL making our tests clean first.  Mostly done, hoping to land today.

**Comment by leafpetersen** [comment]
CL here: https://dart-review.googlesource.com/c/sdk/+/34506
