### ISSUE TITLE
Support unboxed mints on arm64

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31877]
Currently `FlowGraphCompiler::SupportsUnboxedMints() { return false; }` on ARM64 as well as the BinaryInt64Instr is not implemented on ARM64.

/cc @mraleph @mkustermann

**Comment by mraleph** [comment]
@ErikCorryGoogle is gonna start on this /cc @alexmarkov

**Comment by ErikCorryGoogle** [comment]
Fixed now
