### ISSUE TITLE
local_function_test broken on dart2js

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#31879]
After the three commits
e6363dd1bb4d14325bdd1af88eec47ec29d2aaac
107f611d4ed0890789056984519d890548b99afe
7568a4e4ce14b4d93506f1c37f9877df2628dcd6
the two tests
language/local_function_test
dart2js_extra/local_function_call_test
have a runtime error on all dart2js configurations, both browser and non-browser.

Marking this failure in tests/language/language_dart2js.status and
tests/compiler/dart2js_extra/dart2js_extra.status

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/50680
