### ISSUE TITLE
Analyzer: remove widget

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#31888]
Create an function analogous to 'wrap in new widget' that removes the widget instead and places its child in its place, balancing the parentheses and dealing with the whitespace.

**Comment by bwilkerson** [comment]
@stevemessick

**Comment by johnpryan** [comment]
This can be closed I think

**Comment by FMorschel** [comment]
> This can be closed I think

I'm completely sure of that. @srawlins, @bwilkerson, sorry for the ping.
