### ISSUE TITLE
Test language_2/void_type_usage_test.dart not discriminating closely enough

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31883]
The test `language_2/void_type_usage_test.dart` does not discriminate with sufficient precision, which means that it may seem to succeed by having a compile-time error (for the about 200 subtests with expected outcome `//# compile-time error`), but the static analysis still may not have detected the _intended_ fault in the source code.

For instance, the subtest `param_plus_eq` is intended to verify that the following statement is a compile-time error, where `x` is a variable of type `void`:
```dart
  x += 1;  //# param_plus_eq: compile-time error
```
This is a compile-time error because the value of the expression `x` is used in a non-trivial manner (we have about 6 specific situations where such a value can be used, and this is not one of them), but it is also a compile-time error because the type `void` does not have an `operator +`, which is required for `+=`. So it may seem to succeed, but the error may still not be the desired one.

Similarly, the following is a compile-time error because the expression `x` of type `void` cannot be evaluated to serve as the condition for a `while` statement:
```dart
  while (x) {};  //# param_while: compile-time error
```
Given that `void` is a top type (like `Object` and `dynamic`), it should be allowed to have such a condition of type `void` and implicitly downcast it to `bool` as needed for `while`, and the statement should then be OK, except for the fact that it uses the value of `x` at all. However, the test currently succeeds with `dartanalyzer --strong` because there is a compile-time error --- but the error says "Conditions must have a static type of 'bool'" rather than something like "The value of an expression of type `void` can only be used in 6 specific situations listed in generalized-void.md". ;-)

All in all, this means that in a number of subtests, `language_2/void_type_usage_test.dart` does not currently discriminate between some right and wrong reasons for succeeding with outcome `compile-time error`, and this might justify a different approach (e.g., something like the "unit tests" used for testing dart2js, where it is possible to check that a specific error is emitted).

**Comment by MichaelRFairhurst** [comment]
We should probably also test that `extends`/`implements`/`with` void is an error.

I also have tests for some other things; depending on how conclusive we want to be:

```
void main() {
  void x;
  switch(x) { ...; }
  x();
  (x)();
  x.foo;
  x.foo = null;
  x?.foo;
  list[x];
  list[x] = null;
  x[0];
  x ? null : null;
  await x;
```

These may be overkill; however; these were cases that I wrote before implementing them in the analyzer, where each has a different path.

**Comment by eernstg** [comment]
Thanks for the input! We should indeed check those things, they are justified both from a black-box perspective ("this kind of expression exists, we should test it") and a white-box perspective ("if this is omitted, some code in the analyzer never gets tested").

**Comment by MichaelRFairhurst** [comment]
Also, in `void_type_function_types_test`, is this a mistake?

line 95:
`  Expect.isTrue(h2 is `**`H2`**`);`
`  Expect.isTrue(h2 is G2);`
`  Expect.isTrue(h2 is `**`H2`**`);`          
`  expects`**`F2`**`(h2);`
`  expectsG2(h2);`
`  expects`**`H2`**`(h2);`

Looks to me like the first line was supposed to be `Expect.isTrue(h2 is `*`H2`*`);`. This is repeated with h1, h3, ...

**Comment by MichaelRFairhurst** [comment]
OK another suggestion regarding either the test or the spec;

Should `for(void x in ys)` be allowed? Regarding for loops, the spec only says void is allowed:

```
In the initialization and increment expressions of a for-loop
```

If I'm not mistaken, `void x` there is neither?

In then gives an example which is incomplete: "for (e1; e2; e3) {..}, e1 and e3 may have type void."

I'm assuming that this is an error in the informal spec rather than an error in the test (which seems to have very thoroughly tested that `for(void x in ...)` is allowed).

**Comment by eernstg** [comment]
Here's [the CL](https://dart-review.googlesource.com/c/sdk/+/35922) which changes lines 95 and 102 as mentioned.

**Comment by eernstg** [comment]
About `for (var x in <void>[]) {}` and similar constructs: The discussion is being taken in https://github.com/dart-lang/sdk/issues/30177#issuecomment-358815290 and later comments.

**Comment by eernstg** [comment]
Cleanup occurs here: https://dart-review.googlesource.com/350921.
