### ISSUE TITLE
Analyzer: auto-complete to offer constructions, literals and anonymous closures

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#31885]
Something like this https://dart-review.googlesource.com/c/sdk/+/21880 for functions that take a WidgetBuilder or a IndexedWidgetBuilder which are common in flutter

**Comment by bwilkerson** [comment]
Server doesn't currently propose closures when completing a function-valued argument, but it could. It could also be made to propose list and map literals when appropriate. I think both are worth considering as general improvements (rather than one-off fixes).

**Comment by xster** [comment]
Ya, rather than a one off fix, I would prefer it to let argument auto-completes instantiate anything appropriate such as a function with the signature pre-filled, a constructor factor, a map literal etc.

**Comment by bwilkerson** [comment]
I believe that this request has largely been handled at this point. If there are areas that still need work, please let us know.
