### ISSUE TITLE
Analysis Server overlays need to be HTML escaped

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#31906]
Generics in the code get lost unless we escape the `<` to `&lt`.

I have not had a chance to get set up to try it, but I think we just need to use `HtmlEscape` around here https://github.com/dart-lang/sdk/blob/ff008ca37ade57b28edee37183f4eaa5604e7c9c/pkg/analysis_server/lib/src/status/diagnostics.dart#L972

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/35811
