### ISSUE TITLE
Missing compile-time errors from IncrementalCompiler

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#31909]
All these incremental tests are failing after I modified the test suite to complain if compile-time errors are expected but none were reported.

This change is introduced in [change 34740](https://dart-review.googlesource.com/34740).

```
incremental/dartino/compile_time_error_004.incremental: Fail
incremental/dartino/compile_time_error_field_becomes_removed_function.incremental: Fail
incremental/dartino/fix_compile_time_error_in_field.incremental: Fail
incremental/dartino/override_field_with_method_conflict.incremental: Fail
incremental/dartino/override_getter_with_method_conflict.incremental: Fail
incremental/dartino/override_method_with_field_conflict.incremental: Fail
incremental/dartino/override_method_with_getter_conflict.incremental: Fail
```

**Comment by jensjoha** [comment]
These are not related to incremental compilation.
First 3 are errors in the test (fix on the way), the remaining 4 are "normal" fasta issues also demonstrated by tests like language_2/field_override* and language_2/override_field_method*.
