### ISSUE TITLE
io/addlatexhash_test fails on Windows/dartk-vm: "Uri e: must have scheme 'file:'"

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#31903]
Build: https://chromium-swarm.appspot.com/task?id=3afd7e93fb7a8a10
Log: https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2F031f85f65c6387b3e898de770db079c856e047f14d2aa40235171b60557feeeb%2F%2B%2Fsteps%2Ffront-end_tests%2F0%2Fstdout

Related to #31707

FAILED: dartk-vm release_x64 standalone_2/io/addlatexhash_test
Expected: Pass
Actual: RuntimeError
--- Command "vm" (took 03.000977s):
set DART_CONFIGURATION=ReleaseX64 & pkg\vm\tool\dart2.bat --ignore-unrecognized-flags --packages=e:\b\s\w\ir\cache\builder\sdk\.packages e:\b\s\w\ir\cache\builder\sdk\tests\standalone_2\io\addlatexhash_test.dart
exit code:
255
stderr:
Unhandled exception:
Invalid argument(s): Uri e: must have scheme 'file:'.
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:75:7)
#1      Context.fromUri (package:path/src/context.dart:963:18)
#2      fromUri (package:path/path.dart:387:32)
#3      execDir (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:12:35)
#4      execDir (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:12:7)
#5      dartRootDir (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:13:47)
#6      dartRootDir (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:13:7)
#7      testSameHash (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:77:17)
#8      runWithTempDir (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:206:9)
#9      main (file:///e:/b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/addlatexhash_test.dart:216:3)
#10     _startIsolate.<anonymous closure> (dart:isolate:1254:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate:1146:12)

**Comment by lrhn** [comment]
One line of the test contains `path.fromUri(Platform.executable)`.
Since `Platform.executable` is not a URI (documented as being a path), that seems incorrect. It could probably use `Platform.resolvedExecutable`.

**Comment by eernstg** [comment]
Resolved in [this CL](https://dart-review.googlesource.com/c/sdk/+/34661), commit dd7093e7a9d1c34ded9c50fe7f20f190c6ee7446.
