### ISSUE TITLE
use of the new incremental kernel generator does not provide the accept/reject functionality

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31919]
The new incremental kernel generator does not provide the accept/reject functionality which is currently used in the hot reload implementation of flutter tools.

The flutter pull request https://github.com/flutter/engine/pull/4541 works around this issue by removing these commands from the front end server. This functionality needs to be restored so we can work

Here is a proposal from the front end team for this -

Any user of computeDelta can collect the lists it computes and combine them to keep in sync with the VM's expectations. However, this isn't a feature that the front-end team needs to own, or that reasonably belong in the front-end team. We need to provide sufficient stable API to support the VM's use case, and I believe we do:

* You can collect the deltas returned by computeDelta().
* You can track if the VM rejected or accepted a delta. When a delta is accepted, it and all older deltas can be discarded.
* If you have more than one delta, they can be combined by always selecting the newest version of a given library, like this:

```
// Deltas sorted by age, the oldest first.
List<Program> deltas;
Map<Uri, Library> combined = <Uri, Library>{};
for (Program delta in deltas) {
  for (Library library in delta.libraries) {
    combined[library.importUri] = library;
  }
}
return new Program(libraries: combined.values.toList());
```

Alternatively, the deltas can be combined eagerly. In this case, the invariant would be that deltas that haven't been accepted yet are tracked in a combined program, and that the combined program is set to null when accepted.

**Comment by peter-ahe-google** [comment]
Let me know if there's anything I can do to assist with this.

**Comment by a-siva** [comment]
This can be marked as completed correct, I thought both the command line VM and flutter have implemented this functionality ?

**Comment by aam** [comment]
That's correct.
