### ISSUE TITLE
dartkp seems to "inherit via implements" when non-trivial `noSuchMethod` is present

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31911]
Consider the following test, considered as being 'tests/language_2/scratch_test.dart':
```dart
import 'package:expect/expect.dart';

class A {
  int foo(String s) => s.length;
}

class B {
  noSuchMethod(_) => 31;
}

class C implements A {
  noSuchMethod(_) => 41;
}

class D extends B implements A {}

void test(A a, int i) {
  Expect.equals(i, a.foo('Hello!'));
}

main() {
  test(new C(), 41); //# 01: ok
  test(new D(), 31); //# 02: ok
}
```
Execution with the following setup fails:
```
> tools/test.py -m release -c dartkp -r dart_precompiled --strong --host-checked -t 960 --builder-tag no_ipv6 language_2/scratch
```
The failure report includes the following:
```
Unhandled exception:
Expect.equals(expected: <31>, actual: <6>) fails.
#0      Expect._fail (package:expect/expect.dart:562)
#1      Expect.equals (package:expect/expect.dart:124)
#2      test (file:///usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64/generated_tests/language_2/scratch_test_02.dart:20)
#3      main (file:///usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64/generated_tests/language_2/scratch_test_02.dart:25)
...
Unhandled exception:
Expect.equals(expected: <41>, actual: <6>) fails.
#0      Expect._fail (package:expect/expect.dart:562)
#1      Expect.equals (package:expect/expect.dart:124)
#2      test (file:///usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64/generated_tests/language_2/scratch_test_01.dart:20)
#3      main (file:///usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64/generated_tests/language_2/scratch_test_01.dart:24)
```
Surprisingly, the invocation of `foo` on an instance of `C` or `D` seems to run the code from `A.foo`, even though `A` is not a superclass of `C` or `D`. Might this be a generated forwarder that doesn't just forward to `noSuchMethod`?

**Comment by alexmarkov** [comment]
In this test, devirtualization transformation (performed in AOT mode) replaces a.foo invocation with direct call to A.foo. It happens as devirtualization doesn't see targets for this invocation in C and D.

As soon as CFE generates forwarding methods foo() for noSuchMethod in C and D, devirtualization will stop doing this incorrect transformation.

This issue is duplicate to https://github.com/dart-lang/sdk/issues/31424.

**Comment by alexmarkov** [comment]
We switched from using CHA-based devirtualization to TFA-based devirtualization in Dart 2 AOT.
TFA-based devirtualization does not depend on the presence of forwarding methods for noSuchMethod, so this test now works.
