### ISSUE TITLE
List, List<T>, fixed and unmodifiable List have different hidden classes in V8

### ISSUE THREAD

**Issue by ranquild** [dart-lang/sdk#31910]
Faced situation where dart code compiled to js was x20 slower, than hand-written js version. It turned out that problem was with different hidden classes for List's. Here is trivial example demonstrating issue (node 8.5):

```
node --allow-natives-syntax
> var array1 = new Array()
undefined
> var array2 = new Array()
undefined
> var array3 = new Array()
undefined
> array3.$ti = [1]
[ 1 ]
> %HaveSameMap(array1, array2)
true
> %HaveSameMap(array1, array3)
false
> 
```

Same is for fixed (https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/js_array.dart#L97) and unmodifiable (https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/js_array.dart#L105) lists. 

As I see it is problem with language/compiler that it is so easy to ruin performance on such not-obvious things. What are you thoughts?

**Comment by mraleph** [comment]
Do you have a reproduction of your performance issue? We are aware that different array "variants" have different hidden classes, however the expectation is that it should not lead to such a drastic difference in performance - this sounds more like a performance issues in the V8 to me. However hard to say without looking at the actual example.

**Comment by ranquild** [comment]
@mraleph Thanks, I will try to create simple example to demonstrate performance issue. I somehow managed to deoptimize standard dart sorting function by calling it with different List variant in a loop.
