### ISSUE TITLE
Analyzer crashes if you run "git clean".

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31918]
In one window:
```
flutter update-packages; flutter analyze --watch --flutter-repo
```
Once that's started, in another, at the root of the flutter repo (careful, this deletes files):
```
git clean -xffd
```
The analyzer then crashes.

**Comment by Hixie** [comment]
cc @pq @devoncarew

**Comment by bwilkerson** [comment]
Duplicate of #31961.
