### ISSUE TITLE
Transformed type is not picked up with inference - Dart 2.0.0-dev.17

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31914]
See https://travis-ci.org/dart-lang/pub_server/jobs/329567888#L442
Perhaps related to https://github.com/dart-lang/sdk/issues/31884

with 
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

```dart
foo() async {
  String value;
  var thing = new Stream<List<int>>.fromIterable(<List<int>>[
    <int>[5]
  ]);

  await for (var item in thing.transform(UTF8.decoder)) {
    /// `error: A value of type 'dynamic' can't be assigned to a variable of type 'String'. (invalid_assignment at [pub_server] example/example.dart:29)`
    value = item;
  }
}
```

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
That error message is *very* suspicious. There are no values with type `dynamic`.
I'm guessing it means that an *expression* with type `dynamic` is not assignable to `String`.

It looks very related to 31884. The type of `item` should be inferred as `String`, but apparently it isn't.

**Comment by leafpetersen** [comment]
I can reproduce in dev.17, but not in dev.18, assuming fixed.
