### ISSUE TITLE
Too many runtime checks with sdk types with disabled checked mode

### ISSUE THREAD

**Issue by ranquild** [dart-lang/sdk#31921]
Almost all sdk code from dart:core, dart:collection relies on runtime checks of arguments. For example:

https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/js_array.dart#L619
```
void operator []=(int index, E value) {
    checkMutable('indexed set');
    if (index is! int) throw diagnoseIndexError(this, index);
    if (index >= length || index < 0) throw diagnoseIndexError(this, index);
    JS('void', r'#[#] = #', this, index, value);
  }
```

variable index is already typed as int, so checking it in runtime for every call should be not necessary. Similar issue with index checking. Ideally I would like to have all type/index checks enabled/disabled with flag so it would be possible to compile dart to performant js code for production after testing.

What do you think about it? Is this in plans for dart 2.0?

**Comment by lrhn** [comment]
In Dart 2.0, those checkes will be removed from the code. Since Dart 2 is always running in checked mode, extra checks are not needed to preserve sanity. (Because it's also a sound type system, most of those checks can be omitted, so it's not as expensive a checked mode as in Dart 1).

**Comment by ranquild** [comment]
@lrhn Thanks, is it possible to test dart 2.0 version of dart2js compiler?

**Comment by dgrove** [comment]
Not yet - it's on the way.

**Comment by matanlurey** [comment]
Closing this as there is no actionable issue at this time other than waiting for Dart2.
