### ISSUE TITLE
Cannot resolve ChunkedConverter in SDK version 2.0.0-dev.18.0

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#31937]
Did not have this issue with version 2.0.0-dev.16.0. Error output follows:

Working dir: C:\acr\odw\sdk\core
C:\tools\dart\dev\sdk\current\bin\pub.bat upgrade
Resolving dependencies...
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.18.0 for the following packages:

analyzer, args, barback, benchmark_harness, bignum, boolean_selector, browser, charcode, cli_util, collection, convert, coverage, crypto, csslib, glob, grinder, html, http, http_multi_server, http_parser, io, isolate, js, json_rpc_2, logging, matcher, meta, mime, multi_server_socket, node_preamble, package_config, package_resolver, path, plugin, pool, pub_semver, quiver, shelf, shelf_packages_handler, shelf_static, shelf_web_socket, source_map_stack_trace, source_maps, source_span, stack_trace, stream_channel, string_scanner, term_glyph, test, typed_data, utf, version, vm_service_client, watcher, web_socket_channel, yaml

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
+ analyzer 0.29.5 (0.30.0+4 available)
+ args 0.13.7 (1.2.0 available)
+ async 2.0.3
+ barback 0.15.2+14
+ benchmark_harness 1.0.4
+ bignum 0.1.0
+ boolean_selector 1.0.2
+ browser 0.10.0+1 (0.10.0+2 available)
+ charcode 1.1.1
+ cli_util 0.1.2+1
+ collection 1.14.5
+ convert 1.1.1 (2.0.1 available)
+ coverage 0.9.3 (0.10.0 available)
+ crypto 2.0.2+1
+ csslib 0.14.1
+ fixnum 0.10.6
+ glob 1.1.5
+ grinder 0.8.1
+ html 0.13.2+2
+ http 0.11.3+16
+ http_multi_server 2.0.4
+ http_parser 3.1.1
+ io 0.3.1
+ isolate 0.2.3 (1.1.0 available)
+ js 0.6.0 (0.6.1 available)
+ json_rpc_2 2.0.7
+ logging 0.11.3+1
+ matcher 0.12.1+4
+ meta 1.1.2
+ mime 0.9.5
+ multi_server_socket 1.0.1
+ node_preamble 1.4.0
+ package_config 1.0.3
+ package_resolver 1.0.2
+ path 1.5.1
+ plugin 0.2.0+2
+ pool 1.3.4
+ pub_semver 1.3.2
+ quiver 0.27.0
+ shelf 0.7.2
+ shelf_packages_handler 1.0.3
+ shelf_static 0.2.7
+ shelf_web_socket 0.2.2
+ source_map_stack_trace 1.1.4
+ source_maps 0.10.4
+ source_span 1.4.0
+ stack_trace 1.9.1
+ stream_channel 1.6.3
+ string_scanner 1.0.2
+ term_glyph 1.0.0
+ test 0.12.30
+ test_tools 0.7.0 from path C:/acr/odw/test_tools
+ typed_data 1.1.5
+ utf 0.9.0+3
+ version 1.0.2
+ vm_service_client 0.2.4
+ watcher 0.9.7+6
+ web_socket_channel 1.0.6
+ yaml 2.1.13
Changed 59 dependencies!
Precompiling executables...
Failed to precompile coverage:collect_coverage:
'package:convert/src/hex/encoder.dart': malformed type: line 20 pos 13: cannot resolve class 'ChunkedConverter' from 'HexEncoder'
    extends ChunkedConverter<List<int>, String, List<int>, String> {
            ^
Failed to precompile coverage:format_coverage:
'package:convert/src/hex/encoder.dart': malformed type: line 20 pos 13: cannot resolve class 'ChunkedConverter' from 'HexEncoder'
    extends ChunkedConverter<List<int>, String, List<int>, String> {
            ^
Failed to precompile coverage:run_and_collect:
'package:convert/src/hex/encoder.dart': malformed type: line 20 pos 13: cannot resolve class 'ChunkedConverter' from 'HexEncoder'
    extends ChunkedConverter<List<int>, String, List<int>, String> {
            ^
Precompiled grinder:_boot.
Precompiled grinder:grinder.
Precompiled grinder:init.
Failed to precompile test:test:
'package:convert/src/percent/decoder.dart': malformed type: line 29 pos 13: cannot resolve class 'ChunkedConverter' from 'PercentDecoder'
    extends ChunkedConverter<String, List<int>, String, List<int>> {

**Comment by kevmoo** [comment]
Sorry. I believe this is a known issue. You'll need to upgrade to the latest convert & coverage packages.

**Comment by kevmoo** [comment]
Perhaps not! https://travis-ci.org/dart-lang/googleapis_auth/jobs/330576915

Will take a look...

**Comment by kevmoo** [comment]
This is related to https://github.com/dart-lang/sdk/issues/31940 – you're getting an old version of convert here. The core issue has been fixed. Expect a SDK roll tomorrow (-dev.19) tomorrow
