### ISSUE TITLE
constant expressions that throw should be a compile-time error

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#31936]
The spec has this to say:

> It is a compile-time error if an expression is required to be a constant expression but its evaluation would throw an exception.

But we don't implement this semantics in the Kernel compilation pipeline.  For instance, from `corelib_2/string_from_environment3_test`:

```dart
  const String.fromEnvironment(null); // //# 03: compile-time error
```

We have to come up with a design to (1) evaluate these at Dart->Kernel compile time (and possibly canonicalize them at link time), (2) evaluate and canonicalize these at Kernel link time, or (3) adopt a semantics for Kernel that requires the back ends to evaluate them and signal a compile-time error.

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.

**Comment by kmillikin** [comment]
This should be fixed by `constant-update-2018`, but I still see some test status file entries with this issue number so it needs verification.

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
