### ISSUE TITLE
No analyzer hint for unused label

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#31930]
Take the following snippet:

```dart
void main() {
  label: while (true) {
    break;
  }
}
```

The `label` label is unused, without a hint about it. 😆  not the highest priority but...

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/36181

**Comment by srawlins** [comment]
Oh my gosh, I love this. Thank you!
