### ISSUE TITLE
Assert in Type::IsEquivalent can be triggered by cyclic_type_test

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#31944]
Repro: Patch in the new hash table probing order from https://dart-review.googlesource.com/c/sdk/+/34760
Run: ./tools/test.py -m debug -a x64 language/cyclic_type_test

Result: ../../runtime/vm/object.cc: 17209: error: expected: type_arg.IsEquivalent(other_type_arg, trail)

The hash table works correctly, but it causes two types to be compared with each other that were not previously compared.  The following patch increases the hash table size, so that the collisions do not occur, which causes the problem to disappear because Type::IsEquivalent is not called with those two types.

diff --git a/runtime/vm/hash_table.h b/runtime/vm/hash_table.h
index 704523008e..96a5745333 100644
--- a/runtime/vm/hash_table.h
+++ b/runtime/vm/hash_table.h
@@ -118,7 +118,7 @@ class HashTable : public ValueObject {
     // find an empty slot).  This is described in Knuth's The Art of Computer
     // Programming Volume 2, Chapter 6.4, exercise 20 (solution in the
     // appendix, 2nd edition).
-    intptr_t num_entries = Utils::RoundUpToPowerOfTwo(num_occupied + 1);
+    intptr_t num_entries = Utils::RoundUpToPowerOfTwo(num_occupied + 1) * 4;
     return kFirstKeyIndex + (kEntrySize * num_entries);
   }

**Comment by ErikCorryGoogle** [comment]
This has now started failing on the bots even without the hash table change, so plan to disable the test on the VM:

https://dart-review.googlesource.com/c/sdk/+/35961

**Comment by crelier** [comment]
Erik, any idea what is causing this test to start failing, if it is not the hash table change?

**Comment by ErikCorryGoogle** [comment]
I don't really understand the type system so it's a bit hard to say.  Basically there are two types in the system that assert if you compare them with each other.  The hash table will compare random types with each other, depending on their pseudo-random hash codes, so this will be triggered occasionally.

**Comment by crelier** [comment]
The hash table change resulted in types (and type argument vectors) being processed in a different order, which unveiled a previously existing bug in recursive type finalization. A null type argument, which can be encountered in a type argument vector still being flattened during finalization, was not handled properly. A cl is on its way.
