### ISSUE TITLE
Copy web_components/webcomponents-lite.min.js into observatory source

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31947]
This is the only file used from https://pub.dartlang.org/packages/web_components

The current version in the package was copied from Polymer – and has not been maintained.

Once this is done, web_components and initialize can be removed from https://github.com/dart-lang/observatory_pub_packages

**Comment by kevmoo** [comment]
CC @jakemac53 RE deprecating initialize
CC @jensjoha @rmacnak-google RE observatory
CC @devoncarew RE observatory futures

**Comment by jakemac53** [comment]
Fyi, this is the original repo where the latest js file can found https://github.com/webcomponents/webcomponentsjs

**Comment by sigmundch** [comment]
I also believe that observatory should be including the `dart_support.js` file. It seems it is not being included today, which could basically mean that it is not being used in IE11 at this time.

If this is intended to be supported in IE11 - you probably need both files, if not, you could drop the dependency on webcomponents-lite.js entirely.
