### ISSUE TITLE
implicit-casts: false | Argument type not assignable?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31943]
`Dart 2.0.0-dev.8.0` with `implicit-casts: false`.

Happy to close if this is fixed in a newer SDK version.

```dart
class Foo {
  static Foo of(dynamic something) {
    return new Foo(
      // error:
      // The argument type 'List' can't be assigned to the parameter type 'List<MetaType>'.
      // (argument_type_not_assignable)
      something is Iterable ? new Foo(something.map(of)) : <Foo>[],
    );
  }

  final List<Foo> listOfFoo;

  const Foo(this.listOfFoo);
}
```

... is there something I'm missing?

**Comment by zoechi** [comment]
Shouldn't it be

```dart
something is Iterable ? [new Foo(something.map(of))] : <Foo>[],
```
(added `[]`)

if the constructor expects a `List<Foo>`?

**Comment by lrhn** [comment]
Also needs a `toList()` after the `map` call. You need an implicit cast to allow an iterable to be used as a list (and it will fail at run-time anyway).

**Comment by matanlurey** [comment]
You're both right, but I guess I just couldn't understand the error message:

`The argument type 'List' can't be assigned to the parameter type 'List<MetaType>'.`

... how do we get that fixed?

**Comment by matanlurey** [comment]
This looks stale.
