### ISSUE TITLE
Analyzer: Generic type not inferred by constructor arguments

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/sdk#31955]
For the following declaration in Dart 2.0-dev19, the analyzer shows an error for both public named constructors, 'String can't be assigned to T'.

```dart
class Thing<T> {
  Thing.string(String s) : this._(s);
  Thing.integer(int i) : this._(i);
  
  Thing._(this.value);
  
  T value;
}
```

I expected that `T` would be inferred by the constructor invocation. The constructors execute correctly at runtime.

**Comment by lrhn** [comment]
Inference only works at invociations, the declaration must be able to handle all valid type arguments.
Someone can write the code `new Thing<bool>.string("gotcha")`, and that would be statically valid according to the declaration, so we can't allow that declaration.
There is not a way to specialize a constructor to only allowing *some* valid type arguments. That's annoying in some cases (I've had the same problem). It would be nice if you oculd say `Thing<T extends String>.string(String s) : this._(s);` and have a constructor that can only be invoked on a `Thing<String>`, but that is not possible.

So, in this case you can either make the constructors into static functions:
```dart
Thing<String> string(String s) => new Thing<String>._(s);
Thing<int> integer(int i) => new Thing<int>._(i);
```
or make subclasses for the types::
```dart
class StringThing extends Thing<String> {
  StringThing(String s) : super(s);
}
... IntegerThing too ...
```
