### ISSUE TITLE
Give more info on the plugins page - like where the plugin is loaded from

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31951]
![screen shot 2018-01-19 at 2 14 19 pm](https://user-images.githubusercontent.com/17034/35174133-12607f9a-fd23-11e7-8240-2b883cd6cdde.png)

Tell me this is loaded from `$HOME/.dartServer/.plugin_manager/7f0037722791de64448be80c593153f7/analyzer_plugin`

Then I can go look to see the contents of the `.packages` file to understand which version of things got loaded, etc.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/36120
