### ISSUE TITLE
Publish a PDF version of the current language specification ...

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#31957]
... so that we can host a link to it from the [dartlang.org Language Specification](https://www.dartlang.org/guides/language/spec) page (which is currently being edited to include information about Dart 2).

This is a followup request from https://github.com/dart-lang/site-www/pull/523#discussion_r162825595.

cc @anders-sandholm @kwalrath

**Comment by kwalrath** [comment]
@chalin could implement this.

**Comment by chalin** [comment]
Done using the repo I had build a little while back: https://github.com/chalin/dart-spec-and-grammar

Here is the direct link to the most recent PDF of the Language Specification: https://github.com/chalin/dart-spec-and-grammar/blob/master/doc/dartLangSpec.pdf

I'm unsure if this is what you had in mind, but by using this repo, building the PDF version of the spec is automated, as is syncing with dart-lang/sdk to get the latest revision, as is extracting the **grammar** and generating [markdown](https://github.com/chalin/dart-spec-and-grammar/blob/master/doc/grammar-AUTOGENERATED-DO-NOT-EDIT.md) and plain text versions of the grammar. I especially like to be able to view [grammar diffs, such as this one between 1.15 and 2-dev@HEAD](https://github.com/chalin/dart-spec-and-grammar/commit/e232bd176f7f22b1a2d1db666d99f49059323953#diff-fbe0cd5ee4ecc053badc89300b23559e).

**Comment by eernstg** [comment]
Closing: Today there is a stable language specification (currently 2.2) and a 'bleeding edge' language specification on the [Dart Language Specification](https://www.dartlang.org/guides/language/spec) page.
