### ISSUE TITLE
Webgl2 INVALID_VALUE: shaderSource: string not ASCII for shader strings

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#31967]
The following occurred to me using `2.1.1-dev.0.1`, `webdev`, and `Chrome Version 73.0.3648.0 (Official Build) canary (64-bit)`.

I am following a basic WebGL2 tutorial and decided to use Dart instead of JS, but I am having problems with the shaders.

I have a basic setup, which you can see here as well as my shaders: https://gist.github.com/parlough/6f8f979272ea0372042e6f0969a28114

When I attempt to load the shaders, Chrome used to give me the error `INVALID_VALUE: shaderSource: string not ASCII`. I even tried to encode then decode the string with ASCII but that resulted in the same error.

I tried asking around for if I was doing something wrong, but I couldn't find anything standing out obviously and no one else had any input. This may be user error on my part, but either way thanks for your help.

Using the latest versions of everything I now get this error:

<img width="943" alt="screen shot 2018-12-26 at 15 02 39" src="https://user-images.githubusercontent.com/18372958/50457191-64b91c80-091f-11e9-8ed4-1cc0b22d89e4.png">

**Comment by zoechi** [comment]
I get a different error [**DartPad example**](https://dartpad.dartlang.org/fc0c83779a67cf445311bdd11ef135aa) (not 2.0.0 though)

> Exception: Failed to create shader!

**Comment by parlough** [comment]
That is just the exception I throw if the shader failed to be created.

This error persists on `Dart 2.0.0-dev.63.0` and `Chrome Canary Version 69.0.3479.0 (Official Build) canary (64-bit)` within DartPad.

![image](https://user-images.githubusercontent.com/18372958/42194837-7757d850-7e3b-11e8-9df9-83218b512cfa.png)
