### ISSUE TITLE
Android Studio generated error.

### ISSUE THREAD

**Issue by jodynickel** [dart-lang/sdk#31965]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `1.25.0-dev.11.0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.13.0-25-generic unknown, screens 1920x1080, 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file:///tmp/report.txt
[report.txt](https://github.com/dart-lang/sdk/files/1654493/report.txt)

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 594, method: edit.getFixes, params: {file: /home/jnickel/src/timer-app/lib/io-services.dart, offset: 225}, clientRequestTime: 1516677017950}
Invalid argument(s): Invalid line number: 6

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
