### ISSUE TITLE
Dev compiler output not usable without pub serve

### ISSUE THREAD

**Issue by Meai** [dart-lang/sdk#31978]
**Problem:**
Pub serve (or serious custom server configuration) is required to use the dev compiler output because the output files are trying to load from weird places:

`URL:http://localhost:8080/packages/stagexl/src/internal/video_loader.ddc.js`
The actual file is here:
`C:\Users\pc\Desktop\sample-pop_pop_win\.dart_tool\build\generated\stagexl\lib\src\internal\video_loader.ddc.js`

There is no folder I could be using as htdocs/wwwroot for that url to load successfully.

**Desired:**
Output file can be referenced from the index.html naively and it will work with any webserver without extra configuration, preferrably even without any server at all and just from file://

**Comment by natebosch** [comment]
Questions or bugs for the `build_runner` system can be filed at https://github.com/dart-lang/build/issues

In this case you want the `--output` or `-o` options to `build`, `serve`, or `watch` to write the files to a directory with paths that match the requests.

**Comment by Meai** [comment]
Thank you, that option was not documented.
