### ISSUE TITLE
Error compiling dartdevc module:front_end|lib/lib__src__fasta__io.js

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#31971]
Version: 2.0.0-dev.19.0

```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
```
dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/2.0.0-dev.19.0 --dart-sdk-summary=/usr/local/Cellar/dart/2.0.0-dev.19.0/lib/_internal/ddc_sdk.sum --modules=amd --dart-sdk=/usr/local/Cellar/dart/2.0.0-dev.19.0 --module-root=/private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG --library-root=/private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end --summary-extension=linked.sum --no-summarize -o /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__io.js --no-source-map -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__analyzer.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/yaml/lib__yaml.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/source_span/lib__source_span.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/charcode/lib__charcode.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/charcode/lib__ascii.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/charcode/lib__html_entity.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/path/lib__path.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__collection.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_1.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_2.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_3.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_4.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/collection/lib__shared_5.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/string_scanner/lib__string_scanner.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__exception__exception.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__dart__ast__token.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/convert/lib__convert.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/typed_data/lib__typed_data.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/typed_data/lib__typed_buffers.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/crypto/lib__crypto.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__scanner__reader.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__shared_1.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__scanner__errors.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__base__errors.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/glob/lib__glob.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/async/lib__async.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/async/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/async/lib__shared_1.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/package_config/lib__packages.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/package_config/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/package_config/lib__packages_file.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__dependency_walker.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__dart__ast__syntactic_entity.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__builder__builder.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__modifier.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__ast.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__target__flutter.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure_conversion.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure__context.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__frontend__accessors.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__clone.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure__clone_without_body.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure__info.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure__invalidate_closures.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__closure__mock.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__async.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__kernel.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__binary__ast_to_binary.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__binary__tag.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__binary__ast_from_binary.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__erasure.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__insert_covariance_checks.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__log.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/logging/lib__logging.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__insert_type_checks.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__type_checker.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__mixin_full_resolution.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__sanitize_for_vm.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__setup_builtin_library.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__treeshaker.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__generic_types_reification.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__reify_transformer.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__analysis__program_analysis.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__asts.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__verifier.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__transformation__remove_generics.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__transformation__transformer.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__transformation__binding.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__transformations__reify__transformation__builder.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__parser__dart_vm_native.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__target.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__ticker.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__translate_uri.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__io.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__scanner__io.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__combinator.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__source__unhandled_listener.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__source__stack_listener.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__type_inference__type_inference_engine.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__base__instrumentation.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__type_inference__type_schema_environment.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__type_inference__type_schema.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__dill__dill_class_builder.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__kernel__redirecting_factory_body.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__operator.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__import.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__builder__ast_factory.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__kernel__kernel_shadow_ast.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__kernel__utils.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__source__scope_listener.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__kernel__kernel_ast_factory.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__source__diet_parser.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__fasta__kernel__verifier.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__application_root.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/package_config/lib__discovery.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/package_config/lib__shared_1.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/kernel/lib__frontend__super_initializers.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/meta/lib__meta.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__context__context_root.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__shared_1.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__base__jenkins_smi_hash.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/args/lib__args.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/args/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/plugin/lib__manager.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/html/lib__dom.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/html/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/utf/lib__utf.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/csslib/lib__parser.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/csslib/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/watcher/lib__watcher.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__src__scanner__scanner.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/isolate/lib__isolate_runner.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/isolate/lib__ports.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/isolate/lib__shared_0.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/isolate/lib__runner.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/analyzer/lib__dart__ast__resolution_base_classes.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__compiler_options.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__compilation_error.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__file_system.linked.sum -s /private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/lib__physical_file_system.linked.sum --url-mapping=package:front_end/src/fasta/io.dart,/private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/front_end/src/fasta/io.dart --options=/private/var/folders/y_/y0dr0qpj1_ngqmd6y71h2kf80000gn/T/pub_BnDRiG/packages/_internal_/analysis_options.yaml package:front_end/src/fasta/io.dart
    dart --version: 2.0.0-dev.19.0 (Fri Jan 19 08:01:12 2018 +0100) on "macos_x64"
```
Bad state: Unable to find unlinked summary: package:front_end/src/fasta/io.dart
#0      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:241)
#1      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:275)
#2      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:222)
#3      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:238)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:570)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:568)
#7      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:714)
#8      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:687)
#9      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:184)
#10     _compile (package:dev_compiler/src/analyzer/command.dart:187)
#11     compile (package:dev_compiler/src/analyzer/command.dart:57)
#12     _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43)
<asynchronous suspension>
#13     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33)
<asynchronous suspension>
#18     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)

```

**Comment by jmesserly** [comment]
do you recall how this was invoking DDC? It looks like it's from a build system.

**Comment by jumperchen** [comment]
run with `pub build --web-compiler=dartdevc` mentioned from this [dartdevc guide](https://webdev.dartlang.org/tools/dartdevc).

**Comment by jmesserly** [comment]
Gotcha, thanks! That sounds like a pub build issue, then. (DDC is getting invalid input: the summary info was missing for package:front_end/src/fasta/io.dart)

We do need a better error message. The error is coming from Analyzer summary deserialization, however, so I'm not totally sure what the right error message is. (I guess DDC could wrap `computeLibraryElement` and if we get an error from Analyzer, print it and return a failure exit code)

**Comment by munificent** [comment]
Moving this back to just `area-dev-compiler` for improving the error message. Now that `pub build` is gone, we won't be doing anything in pub for this.
