### ISSUE TITLE
kernel debug bot getting lots of flakes with "pthread error: 22 (Invalid argument)" lately

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#31979]
E.g.
```
=== Failure summary:
FAILED: dartk-vm debug_x64 co19/LibTest/collection/LinkedHashMap/LinkedHashMap.fromIterable_A02_t01
Expected: Pass
Actual: Crash
--- Command "vm" (took 02.000925s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/DebugX64 --no-background-compilation --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/tests/co19/src/LibTest/collection/LinkedHashMap/LinkedHashMap.fromIterable_A02_t01.dart
exit code:
-6
stderr:
Stack dump aborted because no current Dart thread.
../../runtime/vm/os_thread_linux.cc: 425: error: pthread error: 22 (Invalid argument)
Aborting re-entrant request for stack trace.
--- Re-run this test:
python tools/test.py -c dartk -r vm --vm-options --no-enable-malloc-hooks co19/LibTest/collection/LinkedHashMap/LinkedHashMap.fromIterable_A02_t01
===
=== 1 test failed
===
Archiving coredumps for crash (if possible):
----> Crash(co19/LibTest/collection/LinkedHashMap/LinkedHashMap.fromIterable_A02_t01: binary.debug_x64_dart 4843)
--- Uploading into gs://dart-temp-crash-archive/4b53b657-312f-40fb-baeb-3c2ae40bd343/ (https://storage.cloud.google.com/dart-temp-crash-archive/4b53b657-312f-40fb-baeb-3c2ae40bd343/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'debug_x64_dart.tar.gz', 'gs://dart-temp-crash-archive/4b53b657-312f-40fb-baeb-3c2ae40bd343/debug_x64_dart.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/4b53b657-312f-40fb-baeb-3c2ae40bd343/debug_x64_dart.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/4b53b657-312f-40fb-baeb-3c2ae40bd343/debug_x64_dart.tar.gz)
--- Done ---
```

```
=== Failure summary:
FAILED: dartk-vm debug_x64 language_2/await_in_cascade_test
Expected: Pass
Actual: Crash
--- Command "vm" (took 03.000436s):
DART_CONFIGURATION=DebugX64 pkg/vm/tool/dart2 --no-background-compilation --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/tests/language_2/await_in_cascade_test.dart
exit code:
-6
stderr:
Stack dump aborted because no current Dart thread.
../../runtime/vm/os_thread_linux.cc: 425: error: pthread error: 22 (Invalid argument)
Aborting re-entrant request for stack trace.
--- Re-run this test:
python tools/test.py -c dartk -r vm --strong --vm-options --no-enable-malloc-hooks language_2/await_in_cascade_test
===
=== 1 test failed
===
Archiving coredumps for crash (if possible):
----> Crash(language_2/await_in_cascade_test: binary.debug_x64_dart2 760)
--- Uploading into gs://dart-temp-crash-archive/b6c85766-06f3-4d7c-b192-fc4deb479083/ (https://storage.cloud.google.com/dart-temp-crash-archive/b6c85766-06f3-4d7c-b192-fc4deb479083/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'debug_x64_dart2.tar.gz', 'gs://dart-temp-crash-archive/b6c85766-06f3-4d7c-b192-fc4deb479083/debug_x64_dart2.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/b6c85766-06f3-4d7c-b192-fc4deb479083/debug_x64_dart2.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/b6c85766-06f3-4d7c-b192-fc4deb479083/debug_x64_dart2.tar.gz)
--- Done ---
```

```
=== Failure summary:
FAILED: dartk-vm debug_x64 co19/LibTest/typed_data/Uint8ClampedList/setRange_A01_t01
Expected: Pass
Actual: Crash
--- Command "vm" (took 03.000258s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/DebugX64 --no-background-compilation --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/tests/co19/src/LibTest/typed_data/Uint8ClampedList/setRange_A01_t01.dart
exit code:
-6
stderr:
Stack dump aborted because no current Dart thread.
../../runtime/vm/os_thread_linux.cc: 425: error: pthread error: 22 (Invalid argument)
Aborting re-entrant request for stack trace.
--- Re-run this test:
python tools/test.py -c dartk -r vm --vm-options --no-enable-malloc-hooks co19/LibTest/typed_data/Uint8ClampedList/setRange_A01_t01
===
=== 1 test failed
===
Archiving coredumps for crash (if possible):
----> Crash(co19/LibTest/typed_data/Uint8ClampedList/setRange_A01_t01: binary.debug_x64_dart 5889)
--- Uploading into gs://dart-temp-crash-archive/6320a568-d723-4db0-a115-b71afd0fa3a9/ (https://storage.cloud.google.com/dart-temp-crash-archive/6320a568-d723-4db0-a115-b71afd0fa3a9/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'debug_x64_dart.tar.gz', 'gs://dart-temp-crash-archive/6320a568-d723-4db0-a115-b71afd0fa3a9/debug_x64_dart.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/6320a568-d723-4db0-a115-b71afd0fa3a9/debug_x64_dart.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/6320a568-d723-4db0-a115-b71afd0fa3a9/debug_x64_dart.tar.gz)
--- Done ---
```

(and many more.)

/cc @mraleph

**Comment by a-siva** [comment]
@crelier  was able to get a coredump on a similar crash and extract stack traces from it. Here are the relevant traces
Thread 1 (Thread 0x7f54edbbe700 (LWP 75897)):
#0  0x00007f54f5ae6fcf in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f54f5ae83fa in abort () from /lib/x86_64-linux-gnu/libc.so.6
---Type <return> to continue, or q <return> to quit---
#2  0x0000000000aa6329 in dart::OS::Abort () at ../../runtime/vm/os_linux.cc:379
#3  0x0000000000de22fe in dart::DynamicAssertionHelper::Fail
(this=0x7f54edbbdbe0,
    format=<optimized out>) at ../../runtime/platform/assert.cc:42
#4  0x0000000000aa863c in dart::Monitor::Exit (this=<optimized out>)
    at ../../runtime/vm/os_thread_linux.cc:425
#5  0x000000000096111c in dart::MonitorLocker::~MonitorLocker
(this=0x7f54edbbdc48)
    at ../../runtime/vm/lockers.h:143
#6  0x00000000009ddce0 in dart::MessageHandler::EnsureTaskForIdleCheck (
    this=0x38622a0) at ../../runtime/vm/message_handler.cc:185
#7  0x00000000009df7c6 in dart::IdleNotifier::Task::Run (this=<optimized out>)
    at ../../runtime/vm/message_handler.cc:730
#8  0x0000000000be5fac in dart::ThreadPool::Worker::Loop (this=0x38223c0)
    at ../../runtime/vm/thread_pool.cc:381
#9  0x0000000000be5e01 in dart::ThreadPool::Worker::Main (args=58860480)
    at ../../runtime/vm/thread_pool.cc:436
#10 0x0000000000aa7841 in dart::ThreadStart (data_ptr=<optimized out>)
    at ../../runtime/vm/os_thread_linux.cc:135
#11 0x00007f54f68ff494 in start_thread (arg=0x7f54edbbe700) at
pthread_create.c:333
#12 0x00007f54f5b9ca8f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f54f557f700 (LWP 75654)):
#0  munmap (start=0x7f54f42e1000, length=5278016)
    at ../../third_party/tcmalloc/gperftools/src/malloc_hook_mmap_linux.h:190
#1  0x00000000007432a8 in dart::bin::MappedMemory::Unmap (this=0x381e0f0)
    at ../../runtime/bin/file_linux.cc:100
#2  0x0000000000716d7d in ~MappedMemory (this=0x381e0f0)
    at ../../runtime/bin/file.h:28
#3  dart::bin::MappedAppSnapshot::~MappedAppSnapshot (this=0x3816cc0)
    at ../../runtime/bin/snapshot_utils.cc:41
#4  0x0000000000716d9e in dart::bin::MappedAppSnapshot::~MappedAppSnapshot (
    this=0x3816cc0) at ../../runtime/bin/snapshot_utils.cc:37
---Type <return> to continue, or q <return> to quit---
#5  0x0000000000746497 in dart::bin::IsolateData::~IsolateData (this=0x3832140)
    at ../../runtime/bin/isolate_data.cc:52
#6  0x0000000000713ce6 in dart::bin::DeleteIsolateData (callback_data=0x3832140)
    at ../../runtime/bin/main.cc:608
#7  0x00000000009ae253 in dart::Isolate::Shutdown (this=0x383cd00)
    at ../../runtime/vm/isolate.cc:1876
#8  0x00000000009618d4 in dart::Dart::ShutdownIsolate ()
    at ../../runtime/vm/dart.cc:726
#9  0x0000000000962461 in dart::Dart::ShutdownIsolate (isolate=0x383cd00)
    at ../../runtime/vm/dart.cc:718
#10 0x00000000009cf203 in dart::RunKernelTask::ShutdownIsolate
(parameter=58969344)
    at ../../runtime/vm/kernel_isolate.cc:149
#11 0x00000000009dec84 in dart::MessageHandler::TaskCallback (this=0x38622a0)
    at ../../runtime/vm/message_handler.cc:508
#12 0x00000000009df713 in dart::MessageHandlerTask::Run (this=0x381e290)
    at ../../runtime/vm/message_handler.cc:27
#13 0x0000000000be5fac in dart::ThreadPool::Worker::Loop (this=0x3822000)
    at ../../runtime/vm/thread_pool.cc:381
#14 0x0000000000be5e01 in dart::ThreadPool::Worker::Main (args=58859520)
    at ../../runtime/vm/thread_pool.cc:436
#15 0x0000000000aa7841 in dart::ThreadStart (data_ptr=<optimized out>)
    at ../../runtime/vm/os_thread_linux.cc:135
#16 0x00007f54f68ff494 in start_thread (arg=0x7f54f557f700) at
pthread_create.c:333
#17 0x00007f54f5b9ca8f in clone () from /lib/x86_64-linux-gnu/libc.so.6
