### ISSUE TITLE
Fuchsia ioctl for fetching network interfaces is changing

### ISSUE THREAD

**Issue by mpcomplete** [dart-lang/sdk#31970]
See https://fuchsia-review.googlesource.com/c/garnet/+/114775

I have a patch to update socket_base_fuchsia.cc to use the new ioctl.

**Comment by rmacnak-google** [comment]
@zanderso

**Comment by zanderso** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/04e91a3ef562516504b107e742d6ed4476b34ced
