### ISSUE TITLE
strong mode inference/type-check issues with deferred loading checks

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31987]
I'm seeing some errors in the strong-mode inference (or type checker) when I add some deferred loading checks.

To repro: comment out the `check_deferred_read` status line in strong.status, and  run `pkg/front_end/tool/fasta testing strong/check_deferred_read`. You should see the following error:
```
> 
In null::test at ...pkg/front_end/testcases/check_deferred_read.dart:9:
    Unresolved method invocation
```

For reference here is the [test file][0]. You can see in the [generated code][1] the deferred load check we inject.

So far, I've only seen the error when accessing a top-level variable. For instance, I have a [CL in flight][2] where I'm adding also checks on a static field, but I do not see the problem there.

@stereotype441 could you take a look or point me in the right direction?

[0]: https://dart.googlesource.com/sdk/+/dcb7ad3a1032bab4116969650c4379f87cffc79c/pkg/front_end/testcases/check_deferred_read.dart#9
[1]: https://dart.googlesource.com/sdk/+/dcb7ad3a1032bab4116969650c4379f87cffc79c/pkg/front_end/testcases/check_deferred_read.dart.strong.expect#8
[2]: https://dart-review.googlesource.com/c/sdk/+/36383

**Comment by stereotype441** [comment]
Taking a look now

**Comment by stereotype441** [comment]
The problem is that the kernel objects generated by `makeDeferredCheck` aren't part of the shadow hierarchy, so they can't be type inferred.  Fix is here: https://dart-review.googlesource.com/#/c/sdk/+/37082

**Comment by sigmundch** [comment]
Ah, thank you! That makes complete sense.
