### ISSUE TITLE
add test.py configuration for only fasta

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31985]
For example, enable:
```
test.py -c dartk -r none
```

Most pieces exist (since we have support for running dark standalone for the mobile targets), but the configuration above currently produces an error (test.py says it is not supported).

@askeksa-google - you said that you normally use a configuration like the one above, are those the parameters you use? or something else?

/cc @peter-ahe-google - Bill and I discussed this yesterday, once we add this configuration, I'll update the dart2js scripts so that any expectation that is from fasta goes in it's own `$fasta` section, and so that the `$dart2js_with_kernel` sections focus on dart2js specific stuff.

**Comment by askeksa-google** [comment]
I have used
```
test.py -c dartdevk -r none
```
which does run Fasta (though not only Fasta) and runs through quite quickly.

**Comment by athomas** [comment]
"test.py -cfasta" was added at some point.
