### ISSUE TITLE
Code completion of annotations fails at end of file

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31989]
Attempt to code complete at the end of a file containing
```
const annotation = 0;

@ann
```
There are no suggestions.

My guess is that the parser isn't recovering, so the annotation doesn't exist in the AST, and hence server can't compute suggestions.

@danrubel Seems like we should either "fix" recovery, or make code completion work for identifiers that are not in the AST. What do you think?

**Comment by danrubel** [comment]
Good question. To the extent possible, I like tokens to appear in the AST rather than be skipped. That makes dealing with them easier. If we were to add it to the AST, would we attach it to a new synthetic top level field?

**Comment by bwilkerson** [comment]
A top-level field has marginally fewer synthetic tokens than a class, and that's generally the criteria we use, so that sounds reasonable.

**Comment by srawlins** [comment]
This appears to be fixed. I get suggestions at this position today.
