### ISSUE TITLE
CFE Incremental compiler API needs to be extended to support expression evaluation

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31982]
Notes taken by @kmillikin during quick sync up on 1/24 between @kmillikin , @aam, @sjindel-google, @rmacnak-google 

1. Expression evaluation based on incremental compiler.
2. Code is compiled as if it were a static or instance method in a class or top-level wrt. a library.
3. Free values will be passed as parameters.
4. Position is indicated by a (class + static|instance) or else a library.
5. Can we support breaking in the expression itself?
6. This should all work with hot reload, so if you break and evaluate some expressions, then continue, you should continue with the reloaded code.  This seems like a separate issue.
7. We can piggyback on the VM's expression function, which can point to the Kernel representation of a procedure.
8. We need a way to serialize a single procedure so the VM can compile it.
9. The function should be compiled in strong mode.

cc: @a-siva

**Comment by aam** [comment]
cc @peter-ahe-google

**Comment by peter-ahe-google** [comment]
@rmacnak-google the incremental compiler already supports using a new entry point. This entry point could be an in-memory file object. @rmacnak-google could we then to something similar to how it works in Smalltalk? Or do we also need a notion of context?

**Comment by rmacnak-google** [comment]
@peter-ahe-google 

Some background for the non-Smalltalkers. If we're suspended in an activation like

```Smalltalk
foo: local1
    | local2 |
    local2 := 4.
    halt. "Debugger stops here"
    ^local1 * local2
```

then to evaluate `local1 + local2`, the compiler generates a method like

```Smalltalk
DoItInContext: context
    ^(context tempAt: 1) + (context tempAt: 2)
```

and the debugger invokes the method passing in the object that represents the suspended activation.

The Dart VM doesn't have anything that behaves like a Smaltalk context object. Instead the Dart VM generates a function like

```dart
evaluate(local1, local2) => local1 + local2
```
and the debugger invokes it with the relevant values fished out from the stack. I think we should stick with this approach for Dart.

**Comment by dgrove** [comment]
This should be marked as a P1, since it's blocking P1 #31981
