### ISSUE TITLE
fasta is mixing up type parameters from different classes

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31996]
Here is a simplified repro:
```dart
abstract class B<T> {}
abstract class C<T> {}
class Base implements B {}
class Child1 extends Base implements C<int> {}
class Child2 extends Base implements C<double> {}
main(){}
```

Compile via: `pkg/front_end/tool/fasta compile repro.dart`, and you get:
```
m3.dart:5:7: Error: 'Child2' can't implement both '#lib1::C<dart.core::int>' and '#lib1::C<dart.core::double>'
class Child2 extends Base implements C<double> {}
      ^
```

Note that `Child2` doesn't implement `C<int>`.

@kmillikin @peter-ahe-google - marking as P1 since this is blocking integration of dart2js in bazel. Apps fail with this error: it comes up a lot with implementations of `Comparable` (e.g. `Child1 extends Base implements Comparable<Child1>`)

**Comment by sigmundch** [comment]
I managed to bisect this and found that it was regressed in 3fcede3c7f57a9b3457cae83d928694b864f01bd

**Comment by sigmundch** [comment]
Just curious if you have any updates on this issue?

**Comment by peter-ahe-google** [comment]
Sorry, no progress so far.

**Comment by sigmundch** [comment]
Updated to P0 - turns out this is causing hundreds of breakages in our integration branch.

**Comment by kmillikin** [comment]
I've asked @askeksa-google to take a look.  We might also be able to revert the change in https://github.com/dart-lang/sdk/commit/3fcede3c7f57a9b3457cae83d928694b864f01bd after we get mixin type inference landed.

**Comment by peter-ahe-google** [comment]
I don't think we can revert 3fcede3, as we need to detect multiple uses of the same interface.

**Comment by kmillikin** [comment]
@askeksa-google discovered that this was an incorrect optimization in the class hierarchy that was already present before https://github.com/dart-lang/sdk/commit/3fcede3c7f57a9b3457cae83d928694b864f01bd but was only detected and reported as an error by that change.  A fix is on the way.

**Comment by askeksa-google** [comment]
The fix causes some failures due to missing onAmbiguousSupertypes callback from DDC and Analyzer. This is tracked in https://github.com/dart-lang/sdk/issues/32091

**Comment by sigmundch** [comment]
Thank you, that's great news!
