### ISSUE TITLE
need super-mixins flag in Fasta to alter warnings/errors around super calls

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31994]
When compiling Flutter we get a slew of errors like this:

```dart
compiler message: file:///usr/local/google/home/vegorov/src/flutter-clean/flutter/packages/flutter/lib/src/rendering/binding.dart:295:11: Error: Superclass has no method named 'hitTest'.
compiler message:     super.hitTest(result, position); // ignore: abstract_super_member_reference
compiler message:  
```

The error comes from this code:

```dart
/// An object that can hit-test pointers.
abstract class HitTestable { // ignore: one_member_abstracts
  // This class is intended to be used as an interface with the implements
  // keyword, and should not be extended directly.
  factory HitTestable._() => null;

  /// Check whether the given position hits this object.
  ///
  /// If this given position hits this object, consider adding a [HitTestEntry]
  /// to the given hit test result.
  void hitTest(HitTestResult result, Offset position);
}

/// The glue between the render tree and the Flutter engine.
abstract class RendererBinding extends BindingBase with ServicesBinding, SchedulerBinding, HitTestable {
  // This class is intended to be used as a mixin, and should not be
  // extended directly.
  factory RendererBinding._() => null;

  @override
  void hitTest(HitTestResult result, Offset position) {
    // ...
    // This super call is safe since it will be bound to a mixed-in declaration.
    super.hitTest(result, position); // ignore: abstract_super_member_reference
  }

}
```

as you can see the error is valid because Dart language conflates the notion of a class and a mixin together. You can also see that the error is suppressed in the analyzer.

To make Flutter builds error free we need a way to perform a similar suppression in CFE, while retaining correctness. 

/cc @kmillikin @peter-ahe-google @leafpetersen @lrhn

**Comment by lrhn** [comment]
This code should only be accepted with the "super-mixins" flag enabled. In that case, it should be accepted and an invalid super-invocation is a dynamic error (like in Dart 1).

Without that flag, any method that callas a super-method *must* have an actual implementation of said method in its superclass.

**Comment by mraleph** [comment]
Then we need super-mixins flag in the front-end

**Comment by a-siva** [comment]
Please see step 0 in the document linked from #31542 for more details on plan agreed upon by the language team.

**Comment by mraleph** [comment]
Update on this: I have discussed this with @askeksa-google - instead of setting up new flags and plumbing them through FE we are just going to just suppress these errors in pkg/vm integration layer.

If there are no objections to it - I will implement this tomorrow.

**Comment by peter-ahe-google** [comment]
This is already supported:

* Don't use `CompilerOptions.onError` and `CompilerOptions.reportMessages`.
* Instead use `CompilerOptions.onProblem`

**Comment by mraleph** [comment]
Keeping this open to track the implementation
