### ISSUE TITLE
dart2.bat may fail to run sometimes

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32003]
When `DART_CONFIGURATION` is unset, this line:
https://github.com/dart-lang/sdk/blob/7d6c27347b1dee0ea90343d3c9c767d924ceabdc/pkg/vm/tool/dart2.bat#L16-L17
sets `DART_CONFIGURATION` to ` =`, and subsequent execution fails.

**Comment by aam** [comment]
Thanks for the bug report!

https://dart-review.googlesource.com/c/sdk/+/37841 with the fix.
