### ISSUE TITLE
analyzer sometimes returns GenericFunctionTypeElementImpls with null names using AnalysisDriver

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32005]
Switching dartdoc over to `AnalysisDriver` has revealed that the analyzer sometimes returns `GenericFunctionTypeElementImpl` elements with names that are null where with `AnalysisContext`, it returned the empty string.  I have a workaround.

This seems to happen in declarations that look like:

https://github.com/dart-lang/dartdoc/blob/41f004303fbdf3f97412e624ef48d9869c84ffc4/testing/test_package/lib/example.dart#L490

but not declarations that look like:

https://github.com/dart-lang/dartdoc/blob/41f004303fbdf3f97412e624ef48d9869c84ffc4/testing/test_package/lib/example.dart#L234

Tested on 0.31.0-alpha.2.

**Comment by matanlurey** [comment]
I think this is WAI. We have the following workaround in AngularDart/SourceGen:

https://github.com/dart-lang/source_gen/blob/19a33605da392d11490f86bccc11a606c7e5be94/lib/src/utils.dart#L43-L61

**Comment by jcollins-g** [comment]
Yes, workaround is easy, filed in case this was unintended behavior.

**Comment by jcollins-g** [comment]
More precisely:  I don't know if it is intended behavior for the name to be null, rather than the empty string.  I've seen a lot of nameless Elements in my time on dartdoc, but I haven't encountered nulls before being returned from name.  I would expect the empty string, since of course, this is an anonymous function...

**Comment by jcollins-g** [comment]
@matanlurey Also, I'll note that since moving to analysis driver, dartdoc's workaround similar to AngularDart/SourceGen has had to change.  We now sometimes (?) have to pop up more than one element to get a name:

https://github.com/dart-lang/dartdoc/pull/1598/files#diff-4d22582de7e25fdddcfff99652835a1eL4644

**Comment by srawlins** [comment]
Closing as stale; might still be an issue, but Dartdoc is linking things OK.
