### ISSUE TITLE
add a new analyzer bot testing --preview-dart-2

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32006]
We'd like to get some CI test coverage of the analyzer with the `--preview-dart-2` flag; this is an issue to track that.

We'd also need to update status files for tests around optional new / const; however I'm not sure what status file predicate we should use for that.

/cc @jwren @bwilkerson @athomas @whesse

**Comment by athomas** [comment]
To move this forward, please add a step (and optionally a builder) to the test matrix:
https://github.com/dart-lang/sdk/blob/master/tools/bots/test_matrix.json#L1254

The test matrix documentation hasn't landed, yet, but you can find it here for now:
https://dart-review.googlesource.com/c/sdk/+/36483/2/tools/bots/README.md

Once the change to the test matrix has landed, dart-engprod will update configurations and consoles. Should there be any questions, I'll happily assist.

**Comment by athomas** [comment]
If the test matrix changes are too involved for some reason, you could also specify the test steps like  they are specified here: https://github.com/dart-lang/sdk/issues/32123

**Comment by devoncarew** [comment]
We have some coverage here now.
