### ISSUE TITLE
package:js: How to use libraries that have modules.export

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/sdk#32016]
I'm trying to use a very simple JS package (or at least one with a very simple interface): https://github.com/mohsen1/json-formatter-js

Apart from trying with "nodejs interop" packages, I tried a simple js interop like this:
```dart
@JS()
class JSONFormatter {
  external JSONFormatter(JsObject json);
  external render();
}
```

Nothing seems to work, though.

**Comment by matanlurey** [comment]
I don't believe we support the ES6 module format at this time, at least not in Dart2JS.

/cc @jmesserly would know best, I think.

**Comment by jmesserly** [comment]
@jacob314 might know more about this. I believe folks have gotten node.js interop to work (at least in Electron), though I'm not entirely sure how that is accomplished.

But yes I don't believe DDC/dart2js have the capability of generating the appropriate `import` or `require(...)` for a JS module (should be straightforward to implement, though).

**Comment by jmesserly** [comment]
merging into https://github.com/dart-lang/sdk/issues/25059
