### ISSUE TITLE
complex_layout_scroll_perf__memory regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32020]
complex_layout_scroll_perf__memory end_total_kb (and diff_total_kb but that one is more noisy) regressed noticeably after we rolled the engine in https://github.com/flutter/flutter/pull/14244.

That roll included two commits.

The first seems rather harmless: https://github.com/flutter/engine/pull/4582
The second was a Dart roll: https://github.com/flutter/engine/pull/4581

**Comment by jason-simmons** [comment]
This was caused by a change to GC policy: https://github.com/dart-lang/sdk/commit/670038cd5bbd1bf53a08aef71c21e5444fbc6a21

**Comment by Hixie** [comment]
Ok, cool. I'll rebaseline the benchmarks then.

**Comment by a-siva** [comment]
I guess the benchmark has been rebaselined, closing issue.
