### ISSUE TITLE
flutter_gallery compilation from Kernel seems to spend a lot of time canonicalizing doubles

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32024]
```console
-   16.81%  gen_snapshot  gen_snapshot         [.] dart::Class::LookupCanonicalDouble
   - dart::Class::LookupCanonicalDouble
      - 99.98% dart::Double::NewCanonical
         - 99.76% dart::Number::CheckAndCanonicalize
            - 99.99% dart::kernel::TranslationHelper::Canonicalize
               - 99.60% dart::kernel::StreamingConstantEvaluator::EvaluateDoubleLiteral
                  - dart::kernel::StreamingConstantEvaluator::EvaluateExpression
                     - 99.24% dart::kernel::StreamingConstantEvaluator::RunFunction
                        - 99.98% dart::kernel::StreamingConstantEvaluator::EvaluateConstructorInvocationInternal
                           + 99.93% dart::kernel::StreamingConstantEvaluator::EvaluateExpression
```

Legacy pipeline spends only 2% here. I think this comes from pulling in animated icon constants (see commit https://github.com/flutter/flutter/commit/85b5b88e0b66959982e2a073771bd49b25dd6641) which are gigantic and full of doubles. 

However these constants are not referenced by flutter_gallery so it seems we have an issue with treeshaking - or we are not lazy enough in our constant evaluation.

**Comment by mraleph** [comment]
This caused a massive regression in AOT compilation time on flutter_gallery when flutter/flutter@85b5b88 was landed - `gen_snapshot` times went from 12 seconds to 17 seconds on my machine. 

@jensjoha if you have time please look at this. 

Otherwise I will get to it next week.

**Comment by jensjoha** [comment]
Canonicalization clearly isn't geared for this:

doubles:
https://github.com/dart-lang/sdk/blob/a42135073d67b697793e4ade63bf9887e371892b/runtime/vm/object.cc#L4410-L4431

mints:
https://github.com/dart-lang/sdk/blob/a42135073d67b697793e4ade63bf9887e371892b/runtime/vm/object.cc#L4433-L4454

E.g. save this program as foo.dart, and run `dart foo.dart 10000 double > foo2.dart; time dart foo2.dart` and compare that to `dart foo.dart 100000 double > foo2.dart; time dart foo2.dart`

```
main(List<String> args) {
  String type = "double";
  int count = 10000;
  int offset = 0;
  for (String entry in args) {
    if (entry == "double")
      type = "double";
    else if (entry == "int")
      type = "int";
    else if (entry == "mint") {
      type = "int";
      offset = (2 << 62) + 42;
    } else if (int.parse(entry, onError: (_) => -1) > 0) {
      count = int.parse(entry);
    }
  }
  print("main() {");
  print("  List<$type> data = <$type>[];");
  for (int i = 0; i < count; i++) {
    String entry = "${i + offset}";
    if (type == "double") entry += ".42";
    print("  data.add($entry);");
  }
  print("  print(data.last);");
  print("}");
}
```

On my machine that's something like ~0.5 seconds and ~12 seconds.
Similarly if you say "mint" instead of "double"...

**Comment by jensjoha** [comment]
So there seems to be at least 3 problems:

1) Canonicalization does a linear search and thus isn't geared for many doubles and mints.
2) static const fields is not tree shaked. For details see below.
3) In the kernel pipeline we seem to canonicalize the same double (from the same position in the dill file) twice for ~60.000 doubles when running on the flutter_gallery dill file.


Details for #1: See above.

Details for #2:
Adding some debug-printing to `Double::NewCanonical(double value)` and compiling a (somewhat old) version of `flutter_gallery` with and without this patch:
```
diff --git a/examples/flutter_gallery/lib/main.dart b/examples/flutter_gallery/lib/main.dart
index bd04ff6ec..a3a861b17 100644
--- a/examples/flutter_gallery/lib/main.dart
+++ b/examples/flutter_gallery/lib/main.dart
@@ -12,3 +12,7 @@ import 'gallery/app.dart';
 void main() {
   runApp(const GalleryApp());
 }
+
+class FooNotUsed {
+  static const not_used = const [ 1.42, 2.42, 3.42, 4.42 ];
+}
```
i.e. with 4 additional - unreferenced - doubles added in both `--preview-dart-2` and not mode (i.e. running `gen_snapshot`on a dill file vs on a dart file) I get the data summarized below:

gen_snapshot on dill file:
==========================
plain:
Inserting double 0.52 at position 15369
[...]
ReadOnlyData(CodeSize): 5032288
[...]

with 4 additional unused floats:
Inserting double 0.52 at position 15373
[...]
ReadOnlyData(CodeSize): 5032320
[...]

Total of 4 new doubles inserted and 32 bytes spend in ReadOnlyData.

gen_snapshot on dart file:
==========================
plain:
Inserting double 0.897029702970297 at position 15475
[...]
ReadOnlyData(CodeSize): 5046848
[...]

with 4 additional unused floats:
Inserting double 0.897029702970297 at position 15479
[...]
ReadOnlyData(CodeSize): 5046880

Total of 4 new doubles inserted and 32 bytes spend in ReadOnlyData.

Details for #3: Debug print added to EvaluateDoubleLiteral, running `sort` and `uniq -cd` on the output reveled as much.

**Comment by jensjoha** [comment]
Created https://github.com/dart-lang/sdk/issues/32077 for issue # 1 above.
In the AOT case most of the problems was solved with a053e3bd98f94465c796f255f0e74af16b36bf3c.

**Comment by rmacnak-google** [comment]
Re constants not tree-shaken: const field are tree-shaken, but once an object ends up in a canonical table we don't remove it. We'd have to make all the constant tables weak and rehash them after a GC like we do for the symbol table.

**Comment by mraleph** [comment]
@rmacnak-google do we even need to write these canonical tables out in AOT? The only users of `Double::NewCanonical` are parser and compiler. I would expect that no new constants are created after the compilation is finished - so no reason to lookup anything.

**Comment by mraleph** [comment]
I guess it for non "primitive" objects canonical tables can still be used when sending constants across isolate boundaries, right? but double identity is undetectable so we should be able to simply drop the whole table.

**Comment by rmacnak-google** [comment]
Right, they're needed for isolate messaging. I think today we still need the table of doubles to successfully canonicalize something like `const [0.0]` because we look for a list with identical elements by address.

**Comment by jensjoha** [comment]
Status:
- 1 and 3 should have been fixed (a053e3bd98f94465c796f255f0e74af16b36bf3c, 9fbbd2dd41c16fb96a3d3d495dd3c23f29408e98, 90a7599d056bdea27cf198268158ad6bb5b0bb3f)
- 2 is no longer reproducible so has probably also been fixed (possibly by a053e3bd98f94465c796f255f0e74af16b36bf3c ?).

**Comment by jensjoha** [comment]
@mraleph I think we can close this issue, do you agree?

**Comment by mraleph** [comment]
SGTM
