### ISSUE TITLE
Pull in latest pub – with change to hidden directory (.pub -> .dart_tool/pub)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32030]
https://github.com/dart-lang/pub/commit/df4f2e6c9149852e7bcf2facf7d6205af74bb698

If we're really going to run with this

1) Create a doc (or meta bug) to track the places that should be updated
    - stagehand
    - open source templates
    - github ignores for languages
    - site-www
3) email dart-core-eng an FYI
4) email announce@ an FYI

CC @kwalrath

**Comment by mit-mit** [comment]
Please socialize with the flutter team, as it will also impact all flutter templates, packages, and plugins.

**Comment by kevmoo** [comment]
Would like to get this in for -dev.32 – so @alexander-doroshko can validate IntelliJ support

**Comment by kevmoo** [comment]
> Please socialize with the flutter team, as it will also impact all flutter templates, packages, and plugins.

@mit-mit – emailed internal teams and posted to misc - https://groups.google.com/a/dartlang.org/forum/#!topic/misc/JICjwA7AOro

**Comment by Hixie** [comment]
FWIW, I just learnt of this for the first time. Apparently I am not subscribed to the lists mentioned above.

**Comment by kevmoo** [comment]
Got in the changelog, but no email was sent https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#other-features

😕
