### ISSUE TITLE
Issues Building on Windows

### ISSUE THREAD

**Issue by loic-sharma** [dart-lang/sdk#32036]
Hello,

The [wiki on building the sdk](https://github.com/dart-lang/sdk/wiki/Building) is missing some dependencies for Windows:

1. "Desktop development with C++" Visual Studio workload - Visual Studio by itself is not enough
1. Windows 10 SDK
1. Python 2.7 - Chromium's depot tools provides "python.bat", but the build requires "python.exe" in the path.

**Comment by lexaknyazev** [comment]
Regarding 2) - afair, only debuggers are needed from SDK. There was a relevant [VS installer issue](https://developercommunity.visualstudio.com/content/problem/53705/error-the-debugger-is-not-properly-installed-run-s.html) about that some time ago, not sure whether new installs require SDK.

Regarding 3) - this could be worked around by manually changing build script, see #31745.

**Comment by loic-sharma** [comment]
2) That is correct, it complained about the debugger. I have VS2017 Community/Enterprise on my computer, and this wasn't enough.

3) That would help, but, you'll still run into issues if you have Python 3 installed.

**Comment by lexaknyazev** [comment]
With changed extension (as in that issue), I've got no conflict with Python 3 since the only `python.bat` in PATH is in `depot_tools`. However for `gclient` commands to work, `depot_tools`'s python must be the first entry in PATH:
```
>where python
c:\depot_tools\python.bat
C:\Program Files\Python36\python.exe
```
