### ISSUE TITLE
Failure in `standalone_2/io/raw_server_socket_cancel_test`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32045]
The following failure was observed (cf. [this log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-win-release-x64-be%2F10663%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fvm-win-release-x64-be%2F10663%2F%2B%2F%2A%2A%2Fstderr)) on vm-win-release-x64-be, build 10663:
```
FAILED: none-vm-checked release_x64 standalone_2/io/raw_server_socket_cancel_test
Expected: Pass
Actual: Crash
--- Command "vm" (took 01.000796s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart.exe --enable_asserts --enable_type_checks --reify-generic-functions --limit-ints-to-64-bits --sync-async --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-release-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-release-x64-be\build\sdk\tests\standalone_2\io\raw_server_socket_cancel_test.dart
exit code:
3
stdout:
unittest-suite-wait-for-done
unittest-suite-success
stderr:
Stack dump aborted because no current Dart thread.
--- Re-run this test:
python tools/test.py -m release --checked standalone_2/io/raw_server_socket_cancel_test
```
Maybe a bug in the io library?

Note that this issue is similar (in nature and in the time where it was observed) to #32046.

**Comment by eernstg** [comment]
Note that https://github.com/dart-lang/sdk/issues/28182 is concerned with the same test, but it's a timeout on Mac so it seems unrelated.

**Comment by cskau-g** [comment]
I've tried to reproduce this error locally on a Windows machine but I am unable to.
Given the age and lack of activity on this issue I think we'll have to declare this obsolete.

If however this issue pops up again, please feel free to re-open.
