### ISSUE TITLE
firstWhere throws when provided orElse: null if no items matched (expectation was null returned)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32041]
The [`firstWhere` docs](https://api.dartlang.org/stable/1.24.3/dart-core/Iterable/firstWhere.html) say that if there's no matching element a `StateError` will be thrown unless you provide an `orElse` argument. However I was just caught out that if I pre-filter the list with another `.where()` which matches no elements, a `StateError` is thrown regardless of the `orElse`:

```dart
[1]
  .where((a) => a > 10)
  .firstWhere((a) => a == 0, orElse: null);
```

```text
Bad state: No element
    at Object.wrapException (<anonymous>:611:17)
    at WhereIterable.firstWhere$2$orElse (<anonymous>:1302:17)
    at Object.main (<anonymous>:1372:54)
```

IMO this behaviour seems wonky (and different to other similar methods from other languages I've used) - it means chaining `where`s and then a `firstWhere` isn't the same as putting all the conditions in the `firstWhere` (which seems to encourage a single `firstWhere` with a long set of conditions), however if that's how it's expected to be I think there should be a mention in the docs that an empty input will always throw regardless of the condition of the `orElse` argument.

**Comment by DanTup** [comment]
Oh dear, I see what's happening... `orElse: null` of course is the same as not passing `orElse`! That's a bit unfortunate... should there be some sort of `undefined` value? ;-)

Probably related: #7939

In C#'s LINQ there's a `.FirstOrDefault`, `.SingleOrDefault` which are used quite a bit; would something similar be considered?

**Comment by lrhn** [comment]
The `orElse` parameter is a function, not a value. That's occasionally annoying, but also strictly more powerful than passing a single value. It also allows you to actually use `null` as a default by calling as:
```dart
someIterable.firstWhere(test, orElse: () => null);
```

**Comment by zoechi** [comment]
I have yet to run into a case where I want `firstWhere` to throw :-/

**Comment by DanTup** [comment]
> The `orElse` parameter is a function, not a value

Whoops! Makes sense now (well, kinda).

> I have yet to run into a case where I want `firstWhere` to throw :-/

I can't think of one off the top of my head, but in C#/LINQ we definitely used `First()` and `FirstOrDefault()` a fair bit (and same for Single's). `FirstOrDefault` was definitely more common though (and the opposite for `Single` because that was really used specifically to crash if something is not as expected).

**Comment by zoechi** [comment]
@DanTup when the collection is expected to also contain `null`. I can imagine such cases, but I never run into one myself, so the default case "throwing" is IMHO annoying.

**Comment by DanTup** [comment]
Sure, I'll go with it's a bad default - I just think there's a place for both and both could be made easy (like they are in C# where there are just two methods, `First` and `FirstOrDefault`). While `FirstOrDefault` doesn't let you customise the default value, you can easily append `?? someValue` on the end (for nullables at least).

**Comment by fryette** [comment]
@DanTup am I right that for now firstOrDefault not exists?

**Comment by DanTup** [comment]
@fryette I don't think so. You might be able to implement it with [an extension method](https://medium.com/dartlang/extension-methods-2d466cd8b308) that just calls `firstWhere` with an `orElse` though :-)

**Comment by hecker** [comment]
@DanTup Is this a good way to solve this?

```
/// Returns the first element that matches the provided test or null if no match is found.
T? firstWhereOrNull(bool Function(T element) test) {
    final list = where(test);
    return list.isEmpty ? null : list.first;
}
```

**Comment by DanTup** [comment]
@hecker this issue is quite old and `firstWhereOrNull` has since been added to `package:collection`:

https://pub.dev/documentation/collection/latest/collection/IterableExtension/firstWhereOrNull.html

I would use it from there (that package has many other similar variants of iterable methods). The implementation looks like this:

```
T? firstWhereOrNull(bool Function(T element) test) {
  for (var element in this) {
    if (test(element)) return element;
  }
  return null;
}
```

I think your implementation may behave slightly differently for `Iterable<T>`s (I think calling `isEmpty` and `first` could cause two enumerations of the iterable?).
