### ISSUE TITLE
Failure in `standalone_2/io/wait_for_event_isolate_test`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32046]
The following failure was observed (cf. [this log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-win-release-x64-be%2F10664%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout)) on vm-win-release-x64-be, build 10664:
```
FAILED: none-vm release_x64 standalone_2/io/wait_for_event_isolate_test
Expected: Pass
Actual: Crash
--- Command "vm" (took 01.000615s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart.exe --reify-generic-functions --limit-ints-to-64-bits --sync-async --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-release-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-release-x64-be\build\sdk\tests\standalone_2\io\wait_for_event_isolate_test.dart
exit code:
3
stdout:
unittest-suite-wait-for-done
unittest-suite-success
stderr:
Stack dump aborted because no current Dart thread.
--- Re-run this test:
python tools/test.py -m release standalone_2/io/wait_for_event_isolate_test
```
Maybe a bug in the io library?

Note that this issue is similar (in nature and in the time where it was observed) to #32045.

**Comment by cskau-g** [comment]
I've tried to reproduce this error locally on a Windows machine but I am unable to.
Given the age and lack of activity on this issue I think we'll have to declare this obsolete.

If however this issue pops up again, please feel free to re-open.
