### ISSUE TITLE
rti_need_test changes behavior depending on expectation.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32055]
With my CL, https://dart-review.googlesource.com/c/sdk/+/32541, the `dart2js/rti/rti_need_test` test fails with the error:
```
sdk/lib/_internal/js_runtime/lib/js_array.dart:19:1:
Info: HERE: Object: class(JSArray) (PartialClassElement)
 expected: class: JSArray:checked,deps=[EmptyIterable,List,ListIterable,SetMixin,SubListIterable],explicit=[JSArray],implicit=[JSArray.E],indirect,needsArgs
 actual: class: JSArray:checked,deps=[List],explicit=[JSArray],implicit=[JSArray.E],indirect,needsArgs
class JSArray<E> extends Interceptor implements List<E>, JSIndexable {
^^^^^
```
If I change the expectation to the "actual" output, the test now fails with errors on both `List` and `JSArray`. It's a Heisenbug!

**Comment by sigmundch** [comment]
My guess is that the behavior is different with our old frontend and the new frontend.

The expectation normally is used for both, but when their behavior differs, there is a way to be more specific. @johnniwinther is the expert here, so he can help with this.
