### ISSUE TITLE
Items missing from code-completion when using the await keyword

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32056]
I was just working on some tests for the vs code validator in `flutter doctor` and noticed something unexpected with the code completion. The code is part of #14463.

Here's the working/correct code (the validate method returns a Future):

<img width="786" alt="screen shot 2018-02-06 at 08 55 35" src="https://user-images.githubusercontent.com/1078012/35850132-b873f0e6-0b1b-11e8-9512-03685a40d911.png">

I deleted `installedWithExtension` and invoked code completion, but `installedWithExtension` wasn't listed in the completion:

<img width="688" alt="screen shot 2018-02-06 at 08 55 46" src="https://user-images.githubusercontent.com/1078012/35850160-ca08f2e8-0b1b-11e8-8fb0-5744e7044e66.png">

If I remove the `await` then it showed as expected:

<img width="717" alt="screen shot 2018-02-06 at 08 55 57" src="https://user-images.githubusercontent.com/1078012/35850176-d85f5b8e-0b1b-11e8-9cdb-a8965f4a8559.png">

(@bwilkerson lmk if there's value in cc'ing you in cases like this; I don't know how cases are normally triaged and whether this makes it easier/more efficient!)

**Comment by bwilkerson** [comment]
> I don't know how cases are normally triaged ...

We have a (rotating) person assigned to triage issues by adding an area label, then people in each area that do further triage, such as whether the issue represents a bug, what the priority is, etc.

I usually do the triage for area-analyzer, so it's fairly likely that I'll see a report like this without being cc'd, but it also doesn't hurt anything if I see it before the area is assigned because I can also assign the area (and won't triage it twice).

**Comment by DanTup** [comment]
@bwilkerson I'm not sure I feel any more knowledgeable about whether it's better to notify or not =) So, in the interests of adding to the notifications you probably get tons of, I'll skip notifying you (unless it's something I have a specific question for you) - though lmk if you decide you'd prefer the other.

**Comment by bwilkerson** [comment]
Given the code
```
class C {
  static Future<int> method() async => 0;
}
void f() {
  String s = await C..toString();
}
```
(which might be too simple to trigger the bug) we now suggest `method` both with and without the `await`, so I'm closing this issue.
