### ISSUE TITLE
dart2js --strong: missing rti in forwarding constructor

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32069]
@johnniwinther is this a know problem? It appears to require `--strong`.

```dart
main() {
  var m1 = {'hello':['hi','howdy'], 'bye':[]};
  var m = new Map<String, List<String>>.unmodifiable(m1);
  print(m);
  print(m is Map<String, List<String>>);
  print(m is Map<List<String>, String>);
}
```

- compiled with `--use-kernel --strong`: wrong, prints the same for both print-is statements.
- `--disable-rti-optimization`: also wrong.
- add `.runtimeType`: also wrong.
- compiled without `--strong`: correct: prints **true**; **false**
- also correct on old pipeline.

The delegated constructors (new ConstantStringMap<K, V>._(....)) have `dynamic` as type arguments.

**Comment by johnniwinther** [comment]
It's not a known problem. I'll look into it.
