### ISSUE TITLE
when const factory redirects to a generic const constructor type argument is not reified 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32068]
```dart
 class A {
   const factory A() = B<String>;
   const A.empty();
 }

 class B<T> extends A {
   const B() : super.empty();

   toString() => '${T}';
 }

 void main() {
   print(const A());
 }
```

```console
$ pkg/vm/tool/dart2 t/redirection.dart
dynamic
```

should print `String`. 

This caused Flutter test failures (e.g. `test/material/input_decorator_test.dart`)

I am not sure if it is VM or CFE or Kernel issue.

/cc @a-siva @kmillikin

**Comment by kmillikin** [comment]
@stefantsov can you take a look at this, and kick it over to @sjindel-google if it turns out to be a VM issue?

**Comment by stefantsov** [comment]
Good news: with the changes in [the currently WIP CL](https://dart-review.googlesource.com/c/sdk/+/37744) the script above does print `String`.  I'm in the process of making this CL and all of the dependent CLs pass the tests and reviews.
