### ISSUE TITLE
implicit setters lack appropriate runtime check in Dart 2 mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32065]
```dart
class A<T> {
   T f;
 }

 void main() {
   A<num> a = new A<int>();
   a.f = 1.0;
 }
```

expected to throw but does not.

This makes `test/foundation/covariant_templates_test.dart` Flutter test fail.

**Comment by crelier** [comment]
Kernel does not generate a regular body graph for implicit setters. Therefore, the argument check did not happen. A cl adding the check to the special code for implicit setters is out for review.
