### ISSUE TITLE
Near-clash on setter names not detected

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32063]
This is a corner case which will be resolved after Dart 2 is in place. Hence it is currently classified as low priority.

Consider the following program:
```dart
class A {
  void set n(value) {}
}

class B extends A {
  static void n() {}
}

main() => new B();
```
The language specification has

```
It is a static warning if a class $C$ declares a static method named $n$ and
has a setter named $n=$.
```
Presumably, such a static warning should be a compile-time error in Dart 2, but the situation is not detected. A similar behavior occurs for the following:
```dart
class A {
  static void n() {}
  static void set n(value) {}
}

void main() {
  new A();
}
```
Note the associated language specification issue #23739.

**Comment by srawlins** [comment]
Analyzer now reports:

> Class 'B' can't define static member 'n' and have instance member 'A.n' with the same name.
