### ISSUE TITLE
Regex performance performs poorly compared to nodejs

### ISSUE THREAD

**Issue by kokizzu** [dart-lang/sdk#32071]
```
reverse-complement
Dart | 23.94 | 1,712,776 | 555 | 29.44 | 52% 35% 15% 23%
Node.js | 4.14 | 243,736 | 1103 | 4.40 | 26% 21% 7% 53%

regex-redux
Dart | 30.08 | 454,592 | 685 | 32.24 | 10% 5% 81% 13%
Node.js | 4.22 | 596,420 | 432 | 4.24 | 100% 0% 0% 1%

pidigits
Dart |   | Failed |  
Node.js |   | Bad Output
```

http://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=dart&lang2=node

**Comment by DisDis** [comment]
Hi @kokizzu
You need to cache 'new RegExp(replacements[++i])'.

**Comment by mraleph** [comment]
@kokizzu `reverse-complement` or `pidigits` do not use RegExp-s at all, only `regex-redux` does.

We have improved some regexp performance last year (e.g. see 7887c34a29b015fcf7411bafc27ace0d4a1e73e7) but afaik Benchmarks Game is using an older VM. 

Do you experience any performance issues with RegExp in your code?

@DisDis I don't think caching helps - each replacement is only used once as far as I can see.

**Comment by kokizzu** [comment]
@mraleph nope, just thinking probably those benchmark result could sway away Dart possible adopters

**Comment by mraleph** [comment]
Okay, I don't think there is anything immediately actionable here. Please reopen if some of your code runs slowly.
