### ISSUE TITLE
dart2js compiler crashes when a native operation return function type.

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#32075]
dart:html (Chrome 63 roll) exposes a typedef

```
typedef void CustomElementConstructor();

CustomElementConstructor _registerElement_1(type) native;
```

Using either the typedef or "void Function ()" or "Function ()" as the return type will crash the compiler.

Work around is to use just Function as the return type.

Would be nice to not lose the more explicit typing information of a Function that void with no parameters.

**Comment by terrylucas** [comment]
When this is fixed I need to remove _completeResultType method in systemhtml.py as well as fix template code that overrides to return Function instead of CustomElementConstructor.

**Comment by jifalops** [comment]
Is it currently possible to register a custom element in dart 2?

**Comment by kevmoo** [comment]
We're going to deprecate this API.
