### ISSUE TITLE
Interim support for limited fuzzy arrows

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32074]
In order to give internal code cleanup more time to happen while we focus on external code (flutter), the front end should suppress certain errors (or turn them into warnings) as described in this issue.  

Specifically, in any assignability check (e.g, an assignment to a variable or other location, passing a parameter, etc) which checks that something of type `From` can be assigned to something of type `To`, normally there is an error if neither `From <: To` nor `To <: From` is true.  In the case that `To` is a function type and `From <: To'`  is true then the error should be suppressed or turned in to a warning; where `To'` is the same as `To` except that all parameters (named and positional) with type `dynamic` have been replaced with a parameter of type `Null`.

Note that this does not apply on override checks (which do not use assignability) nor does it apply recursively in depth subtyping: is is only the top level function type that should be rewritten to replace `dynamic` with `bottom`.

This is not a sound subtyping.  For flutter framework code, this warning is treated the same as an error, and so there should be no issue, but if the native compilers want to be defensive against this it should be valid to place an implicit downcast on the assignment (which will fail at runtime).  cc @mraleph 

DDC with kernel will need to run this code, and so if we wish to be able to test out DDC with this in place there needs to be a way to suppress such an implicit cast (if it is placed).  cc @vsm @jmesserly 

Dart2js with kernel will need to run this code, but will likely be running with implicit downcasts disabled.  They will likely want to test with implicit downcasts enabled as well though, and so I believe that they will also want to be able to suppress these implicit casts (if they are placed).  cc @sigmundch 

cc @kmillikin

**Comment by jmesserly** [comment]
RE: DDC

> DDC with kernel will need to run this code, and so if we wish to be able to test out DDC with this in place there needs to be a way to suppress such an implicit cast (if it is placed). cc @vsm @jmesserly

FYI - this should be easy to implement in DDC w/ Kernel. Presumably, we'll also want to use a dynamic call on all function types that have fuzzy arrows, similar to what we currently do in DDC w/ Analyzer.

**Comment by leafpetersen** [comment]
What's the status on this?

**Comment by kmillikin** [comment]
Not started, planned for the week after this one.

**Comment by lrhn** [comment]
Just to be double-check and be precise: This affects both static and run-time checks, right?
```dart
void Function(dynamic) foo = (int x) {};  // Static warning, run-time allowed.
foo("why not");  // Run-time error.
```
Am I understanding it correctly? (Ignore it if there is some "exact type" exception that catches this degenerate example).

**Comment by leafpetersen** [comment]
> Not started, planned for the week after this one.

@srawlins Given the recent downwards trajectory of fuzzy arrow errors in internal code it seems likely that you will have everything cleaned up by then, WDYT?  If so, we could just take this off the plan.  @kmillikin definitely check in with us before starting it.

cc @dgrove

**Comment by leafpetersen** [comment]
> Just to double-check and be precise: This affects both static and run-time checks, right?

This issue doesn't request support for a runtime check, though they are free to add one.  
  - DDC is not on the CFE, so it gets the (mostly) right runtime check from the analyzer
  - dart2js will not do the runtime check in the time frame that this error -> warning suppression happens
  - For native (VM), the FE can either keep this as an error, add a runtime check, or just live with the short-term unsoundness.

**Comment by srawlins** [comment]
@leafpetersen Hmm, I'm not sure if there is a real "trajectory" or "momentum". We have ~33% the number of fuzzy arrows today as we did at the beginning of January. Let me keep an eye on these through the week, and I'll post back before Friday EOD.

**Comment by srawlins** [comment]
We did not make that much headway in the last week (we're at like ~30% remaining), but I'd really like to avoid this interim support. I think with some more manpower we can avoid a situation where internal code status blocks language/implementation progress for more than a week. WDYT leafpetersen@?

**Comment by leafpetersen** [comment]
I'll try to make some time to work on this in the next week.

**Comment by leafpetersen** [comment]
This is not needed, @srawlins has completed the migration. 🎉 🍾
