### ISSUE TITLE
Incorrect prefer_const_constructors

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32081]
```
Analyzing /usr/local/google/home/rmacnak/topaz1/topaz/shell/armadillo_user_shell/lib...
  error • Prefer const with constant constructors at package:armadillo_user_shell/armadillo_user_shell_model.dart:148:9 • prefer_const_constructors
```

```
148:        new ContextQuery(selector: <String, ContextSelector>{});
```

Note the map is mutable/non-const so the ContextQuery instantiation must not be const.

topaz @23a890a2d29ab83ce304f2c39ea4480298d8b849
dart @1451cfd741e69cc5465dd0ce2709ffa119394aaf

**Comment by pq** [comment]
I believe this is fixed (cc @a14n).  If not, let's open a fresh issue on the linter proper: https://github.com/dart-lang/linter.

Thanks!
