### ISSUE TITLE
need a mode in which results of the native methods are type checked

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32090]
Currently we don't type checks results produced by native methods so errors like incorrect type annotations or native code not setting type argument properly are discovered very late. 

We need to inject a type check into return from native methods to avoid cryptic failures that need a lot of time to track them down.

/cc @a-siva

**Comment by crelier** [comment]
The type check was emitted in checked mode only.  It is now emitted in strong mode as well, both in kernel and in VM. A changelist is on its way.
