### ISSUE TITLE
Fasta type inference needs support for RedirectingFactoryConstructor

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#32105]
[CL 37744](https://dart-review.googlesource.com/c/sdk/+/37744) makes fasta emit special Kernel nodes: instances of RedirectingFactoryConstructor.  Currently those aren't accounted for by the type inference in fasta.

/cc @stereotype441 @kmillikin

**Comment by johnniwinther** [comment]
@stefantsov Is there any work left here?

**Comment by stefantsov** [comment]
Yes and no.  Yes: the new kind of Kernel nodes that represent redirecting factories still isn't emitted by the CFE.  No: since we don't emit those nodes, it's not a problem to not have inference working for them.

**Comment by johnniwinther** [comment]
I'm closing this in favor of #42939
