### ISSUE TITLE
Incorrect offset in quick assist

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#32106]
Reproducible with Dart SDK 2.0.0-dev.24. It's a regression compared to SDK 1.24.3.
Consider this code:
```
main() {
  print('foo');
}
```
Select `print('foo');` and invoke `Surround with 'try-catch'` quick assist. Analysis Server returns the following [SourceChange](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#type_SourceChange):

![image](https://user-images.githubusercontent.com/4499789/36029422-331e32da-0db4-11e8-8c9f-a903bb0165ed.png)
Underlined offset=131 is incorrect, the value should be 72. It's the last LinkedEditGroup that should stop on `// TODO` text.

P.S. The problem was caught by a test from the Dart plugin source code. We have tests only for 2 quick assists because our goal is to test the integration, not the quick assists themselves. So there might be other quick assists with a similar problem.

**Comment by alexander-doroshko** [comment]
@bwilkerson @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/41420
