### ISSUE TITLE
Use same prebuilt SDK in dart-lang/sdk and Fuchsia

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32112]
dart-lang/sdk uses a download_from_google_storage rule in the DEPS file. This doesn't work for Fuchsia because they don't use gclient.

Fuchsia uses (a copy of) tools/download_latest_dev_sdk.py. This doesn't work for dart-lang/sdk because it uses a special SDK with ARM versions of the VM added.

@whesse @zanderso

**Comment by athomas** [comment]
Is this still relevant? We're using CIPD packages now, and fuchsia could use them, too. We're no longer doing the ARM hack either.
