### ISSUE TITLE
Superclasses are not instantiated to bounds

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32115]
In example below raw type `X` is instantiated to bounds, while `extends X` turns into `X<dynamic>`:

```dart
class B { }
class X<T extends B> { }
class Y extends X {}

void main() {
  print(new Y() is X);  // prints `false`
}
```

This is causes obscure failures on Flutter tests, e.g. `test/material/expansion_panel_test.dart`.

**Comment by mraleph** [comment]
/cc @leafpetersen @lrhn Can you clarify what should be the result of this?

Should it print `true` or should it be a compile time error?

**Comment by eernstg** [comment]
We currently do not have a notion of instantiate-to-bound in dartLangSpec.tex, but raw generic classes do receive a type argument list of the form `<dynamic, ..., dynamic>`, also when used as a superclass.

We have no proposals where type arguments for the superclass are inferred.

Hence, Dart 2 semantics (though not specified explicitly) should be to use instantiate-to-bound on `X` as a superclass, so we get `class Y extends X<B> {}`. The type test in `main` is then `new Y() is X<B>`, so it should print `true`.

**Comment by leafpetersen** [comment]
Yes, I agree with @eernstg .

**Comment by kmillikin** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/83c33372bfe9121d31e333169ff6c77bbbf70f5a
