### ISSUE TITLE
DartDevCompiler fails without any helpful information

### ISSUE THREAD

**Issue by dustinlessard-wf** [dart-lang/sdk#32119]
While attempting to build a library using the Dart Dev Compiler:
```shell
pub build --web-compiler=dartdevc --all --verbose --trace
```
an error is encountered with no hint on where the issue is:

```shell
#left out other parts for brevity
MSG : Building dartdevc modules...
FINE: Building dartdevc modules finished (20.385s).
ERR : Build failed.
```

This library passes the static analysis checks by the Analyzer package with strong-mode enabled.  Is there any other way to get more details on the reason this is failing?

**Comment by vsmenon** [comment]
@jakemac53 - this should be filed on build?

**Comment by jakemac53** [comment]
This looks like its going through pub not build, can you run with `--verbose` and link a gist with the entire contents of the log?

**Comment by matanlurey** [comment]
@dustinlessard-wf We don't expect to offer much support for DDC through `pub build/serve` at this point, due to the fact that `build_runner` offers much better (and long-term) support. Could you try that instead?

(Feel free to re-open if I'm mistaken)
