### ISSUE TITLE
2.0.0-dev.23.0: Analyzer broke the world

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32117]
~~I can't tell from this error message what is wrong, or how to fix this:~~

https://github.com/dart-lang/angular/issues/867

There is also nothing in the CHANGELOG describing why a new error was introduced:

https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

**EDIT**: [Mockito](https://pub.dartlang.org/packages/mockito) uses the following pattern:

```dart
when(<invocation>).then(<configuration>).
```

This means that the following is/used to be possible:

```dart
import 'package:mockito/mockito.dart' show Mock, verify;

abstract class Cat {
  void meow();
}

class MockCat extends Mock implements Cat {
  @override
  noSuchMethod(i) => super.noSuchMethod(i);  
}

void main() {
  Cat cat = new MockCat();
  cat.meow();
  // error: The expression here has a type of 'void', and therefore cannot be used.
  // (use_of_void_result at ...)
  verify(cat.meow()).called(1);
}
```

... this ... can't be an _error_ right now, maybe a _warning_ or _hint_ that can be ignorable in the future, unless we have a fix for `package:mockito` and similar. We will never be able to roll this into google3 😢

**Comment by srawlins** [comment]
CC @MichaelRFairhurst

**Comment by srawlins** [comment]
What version of Mockito is this on? I think this is fixed in Mockito master.

**Comment by srawlins** [comment]
I can publish a mockito release today. https://github.com/dart-lang/mockito/pull/95

(Publishing a fix for mockito does not close this issue. Matan's questions should be resolved:

* There is nothing in the CHANGELOG
* Should this be an _error_ now?

)

**Comment by leafpetersen** [comment]
cc @MichaelRFairhurst @eernstg @lrhn 

My understanding was that no void restrictions were landing without google3 being cleaned up and ready for them.

**Comment by leafpetersen** [comment]
I may just go ahead and revert https://dart-review.googlesource.com/c/sdk/+/39881 tomorrow (Sunday PST) so that we get a dev build on Monday (CET) without it.

**Comment by srawlins** [comment]
I'm pretty sure @MichaelRFairhurst _did_ clean up google3 first, including a fix to mockito. We just didn't (and [haven't](https://github.com/dart-lang/mockito/pull/95)) release it yet. I don't think a rollback is needed.

**Comment by MichaelRFairhurst** [comment]
Yep google3 is cleaned up. Sorry guys for not coordinating a rollout of this externally first, and changelog updates. I will do the former in a CL right now.

**Comment by MichaelRFairhurst** [comment]
https://dart-review.googlesource.com/c/sdk/+/40505

**Comment by srawlins** [comment]
Mockito 2.2.3 published. https://pub.dartlang.org/packages/mockito

**Comment by MichaelRFairhurst** [comment]
Thanks @srawlins!!

**Comment by leafpetersen** [comment]
I think this is resolved, closing.
