### ISSUE TITLE
Add quickfix for "Only static fields can be delcared as const" to mark static

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32128]
I always forget to write `static` on consts inside my classes (in C# consts didn't need the static keyword). My first instinct is to invoke a quick fix, but there isn't one:

<img width="286" alt="screen shot 2018-02-12 at 20 32 55" src="https://user-images.githubusercontent.com/1078012/36118166-ff6472ba-1033-11e8-8312-778d343178f3.png">

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/40640
