### ISSUE TITLE
Analyzer "clean up imports" action deletes imports that are not yet generated

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#32124]
The "ctrl+o" to clean up imports in IntelliJ (which I believe is provided via the analyzer) has a serious flaw: it removes imports of files that do not exist.

This is particularly a problem with generated files, because it is commonly the case that generated files do not exist (yet).

If a source file imports a generated part file, and the part file does not exist yet, and I hit "ctrl+o", then the import of the part file is simply removed.

I think the simplest fix would be to never remove imports of files that cannot be found. I don't think there needs to be a special case for generated files; I don't see a downside to simply ignoring imports of things that can't be found, because they likely indicate a problem that the user has to sort out somehow. (By running pub get, running codegen, or fixing them to point to something else).

Thanks!

**Comment by bwilkerson** [comment]
It might be removing imports for files that don't exist, but it also might be removing unused imports, and just having no way to know that a non-existent import is being used because we couldn't find any identifiers defined by the import. (Removing unused imports is an intentional part of cleaning up imports.) If that is the case, we should consider marking all imports as used (for this purpose) when there are unresolved symbols in the code.

**Comment by devoncarew** [comment]
> I think the simplest fix would be to never remove imports of files that cannot be found.

This is one of the uses of 'organize imports' however; people do use it to remove imports that are no longer referenced.

If the main issue is with removing currently unused imports for generated files, special casing generated file imports sounds reasonable to me.

> If that is the case, we should consider marking all imports as used (for this purpose) when there are unresolved symbols in the code.

Marking all imports in this case sounds good; we could also just mark imports we thought were referring to generated files (by the file name pattern).

**Comment by davidmorgan** [comment]
Discussed w/Brian and Devon. Seems like the best option is: if there are unresolved symbols, don't auto-remove imports (of any type). This covers the generated files case well without needing special casing for it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/48705
