### ISSUE TITLE
Please configure front-end CQ and build bot

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32123]
I'd like to have a CQ and build bot configuration that tests the newly added $compiler == fasta to test.dart.

Concretely, please run the following steps:

* Build SDK (same as vm-kernel bots)

* Unit tests:

```
./tools/test.py -mrelease -ax64 -cnone -rvm -pline -t240 \
  --checked --report --time 'pkg/(kernel|front_end|fasta)'
```

* Fasta SDK tests:

```
./tools/test.py -mrelease -ax64 -cfasta -rnone -pline -t240 \
  --time --report --strong
```

* Fasta legacy mode SDK tests:

```
./tools/test.py -mrelease -ax64 -cfasta -rnone -pline -t240 \
  --time --report
```

Note, the "Unit tests" step is similar to the "front-end tests" step on vm-kernel builders. But instead of completely removing this step, we should run only pkg/front_end/test/fasta/strong_test.dart and pkg/front_end/test/fasta/compile_test.dart. Unfortunately, these are the long running tests, but they do test the VM as well. For these build bots, it could make sense to not use test.py to run them.

**Comment by athomas** [comment]
The builders are now configured and showing on the consoles.
