### ISSUE TITLE
include amount collected in the service protocol GC event

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32121]
It would be useful if the service protocol's GC event contained information about the amount of memory collected in each heap (new and old). When graphing the memory used over time, this would help better indicate the before and after memory used (the GC event contains info about the after amount, and if we had the delta we could also show the before amount).

**Comment by devoncarew** [comment]
(the amount if time that the GC took is already passed through in the `time` HeapSpace field)

**Comment by bkonyi** [comment]
This might not be possible given the concurrency of the garbage collector. From what I understand, the GC event is sent well before the sweeper has finished cleaning up memory, so any memory usage values at the time of the GC event won't necessarily be representative of the memory that is used after the collection.

cc @rmacnak-google

**Comment by devoncarew** [comment]
The GC event currently contains the memory usage before the GC? Not the memory usage after collection?

**Comment by bkonyi** [comment]
Yes and no, as it's likely racy depending on whether or not the sweeper finishes before the event is raised. Basically, the values in the GC event shouldn't be relied upon as a source of truth when it comes to determining the amount of memory reclaimed during a GC.

**Comment by devoncarew** [comment]
Gotcha, thanks for the update. Sounds like the info isn't readily available. It would be nice to be able to have the memory usage before and after the collect - it would give us a higher resolution in a memory usage graph - but it's not a critical feature.
