### ISSUE TITLE
kernel-service: Calling main resulted in an error: isolate terminated by vm

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#32134]
Sometimes the string `kernel-service: Calling main resulted in an error: isolate terminated by vm` gets added to the output when running a dill file on simarm64 build.

Steps to reproduce:

1) file `hello.dart`:
```
void main() {
  print("Hello, world!");
}
```

2) Compile to dill file: `pkg/front_end/tool/fasta compile hello.dart`

3) Compile simarm64: `./tools/build.py --mode=debug --arch=simarm64 runtime`

4) Create symbolic link to dart executable: `ln -s out/ReleaseSIMARM64/dart lala_exe`. I don't think this step is not strictly necessary, but seems to increase how often it happens. (at least I'm pretty sure I reproduced it without it as well - but it definitely doesn't happen as often).

5) Run dill file with symbolic link in a loop: `for i in `seq 200`; do ./lala_exe hello.dart.dill; done`

Eventually (probably) you'll see something like this:
```
Hello, world!
Hello, world!
kernel-service: Calling main resulted in an error: isolate terminated by vmHello, world!
Hello, world!
Hello, world!
```

This causes the bot `vm-kernel-linux-release-simarm64` to fail on `standalone_2/io/platform_resolved_executable_test/05` once in a while.

**Comment by jensjoha** [comment]
Marked in status file.

**Comment by mraleph** [comment]
This causes bad flakiness on the bots. We need to investigate. /cc @a-siva

**Comment by ianloic** [comment]
This caused flakes on the Fuchsia bots when I started running out FIDL generated dart through `dartfmt`. It looks like errors are being reported with `OS::Print` in [kernel_isolate.cc](https://github.com/dart-lang/sdk/blame/master/runtime/vm/kernel_isolate.cc#L209) which on Linux at least just prints to stdout - not where I'd prefer errors to go...

It looks like @rmacnak-google was the last to touch that line in `kernel_isolate.cc`.

**Comment by rmacnak-google** [comment]
The underlying issue is that when the standalone VM runs from a kernel file instead of source, the main isolate can finish and shut down the VM before the kernel isolate finishes starting up.
