### ISSUE TITLE
Last property does not work for io.Stdin.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#32132]
DART API Spec reads about the `io.Stdin.last` property:
```
Future<T> last
Returns the last element of the stream.
If an error event occurs before the first data event, the resulting future is completed with that error.
If this stream is empty (a done event occurs before the first data event), the resulting future completes with a StateError

```
However, it seems like it's impossible to get the `last` property for `stdin`.

The following code demonstrates this (tried with dart 2.0 on Windows ):
``` dart
import "dart:io";

main(List<String> args) async {
  await stdin.last.then((List<int> l) { print("LAST"); });
}
```
When I run it from the terminal, I am just entering any input strings a lot of time and nothing happens.
"Last" string is never printed in stdout.

The `first` property looks OK. When I run the following code:

``` dart
import "dart:io";

main(List<String> args) async {
  await stdin.first.then((List<int> l) { print("FIRST"); });
}
```
I enter one input line in stdin, after this "FIRST" string appears in stdout an program exits.

**Comment by lrhn** [comment]
Do you ever *close* the stdin, e.g., by doing CTRL+D (Unix) or CTRL+Z (Windows) in the console?

A stream cannot know what its last event is until it closes, otherwise there might be more events later.

Testing (on Windows) does print "LAST" when I enter CTRL+Z.

**Comment by iarkh** [comment]
Thank you for the answer!

You are correct, "LAST" is printed if I enter Ctrl-Z on my Windows desktop, so it seems it's expected behavior. I've tried to print Ctrl-C and it did not work for me (indeed, now I see that it's expected behavior too).

In my Linux environment Ctrl-D (also tried ctrl-d) does not work for me... If I click Ctrl-C - no "LAST" string in stdout. 

Seems like it depends on the terminal settings (stty), however I see that eof character is really set to ctrl-D there, so haw can I correctly get an info about the stream closing symbol?

Here are my stty settings:
```
iarkh@medan-calc:~/dart/test/LibTest/io/Stdin$ stty --all
speed 38400 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke
```

**Comment by natebosch** [comment]
I'm not sure if we'll be able to help with getting `EOF` from your particular terminal setup. I seem to have trouble getting `crtl-d` to work on linux, but on my mac it works fine - it's a quirk of the terminal or shell though as far as I can tell - `dart` behaves the same as `cat` when it comes to recognizing `EOF`.

If you want to reliably see the behavior of your program when it encounters the end of the `stdin` stream you can run with something like `echo -n 'full stdin input' | dart scrip.dart`
