### ISSUE TITLE
Core library Future implementation assertion violation

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32141]
Line 473 of future_impl.dart (in `_completeWithValue`) has the following assertion:

```dart
    assert(value is! Future);
```

However, on line 507, `_completeWithValue` is called from `_asyncComplete` in a context where it is only guaranteed that the argument is not `Future<T>` for some specific `T`.

```dart
    if (value is Future<T>) {
```

If `T` is itself a `Future`, then the assertion above canl fail.  The example code below when run with ddc or the dart VM in dart 2 mode reproduces the issue.

run with

```
dart -c --preview-dart-2 
```
or
```
pkg/dev_compiler/tool/ddc
```

```dart
import 'dart:async';
 
void main() {
  new Future<Future<int>>.value(new Future<int>.value(3));
}
```

cc @lrhn

**Comment by lrhn** [comment]
Appears to be fixed.
