### ISSUE TITLE
corelib: casting of an unmodifiable map allows the underlying to be modified

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32147]
I would expect that `UnmodifableMapView` and `Map.unmodifiable` to have no sequence of operations that allow the map to be modified.

The following does not throw and mutates the 'protected':
```
new UnmodifiableMapView<num,num>(<num,num>{1: 37}).cast<int,int>().clear();
```

**Comment by lrhn** [comment]
Good point. The `MapView` `cast` and `retype` forwards to the wrapped map. That's actually unsafe for `UnmodifiableMapView` because it loses the unmodifiability.
