### ISSUE TITLE
Restrict behavior of callable classes

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32152]
In Dart 2.0, we would like to change to the behavior of callable classes (classes containing a `.call` method) so that they are no longer considered a subtype of the function type of their `.call` method.

Instead, to support almost all existing code, the call method will be implicitly torn off where statically detectable (but dynamic invocation of a class with a call method will still be allowed).

Rationale: This feature has never paid its way as far as complexity it adds to the type system and the implementations.  It has been (and probably still is) the source of various bugs.  It also complicates our calling conventions in generated code - we cannot assume a function is actually a function.  In general, we believe fixing google3 code will be faster than properly implementing and will probably result in better generated code.

Test cases for this change were added to the `tests/language_2` subdirectory in f0a6330db005acbe6514d26931b5fcb9782321d2.

This is an overall tracking bug.  Individual implementations are tracked in their own sub-bugs:
- [x] specification text #32153
- [x] front end #32064
- [x] VM #32154
- [x] dart2js #32155
- [x] analyzer #32156
- [x] DDC #32157
- [ ] Verify tests are passing
- [ ] Documentation

**Comment by srawlins** [comment]
I don't know that we're going to document callable classes more than they are. Should this be closed?

**Comment by stereotype441** [comment]
> I don't know that we're going to document callable classes more than they are. Should this be closed?

I'm in favor of closing it
