### ISSUE TITLE
Restrict behavior of callable classes - DDC implementation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32157]
This is the DDC component of meta-bug #32152.  See the meta-bug for details.

**Comment by vsmenon** [comment]
We'll need to land the DDC bits from this CL:

https://dart-review.googlesource.com/c/sdk/+/39680

@stereotype441 - are you planning on doing this (task is assigned to you)?

**Comment by stereotype441** [comment]
Yes, I'm planning to do this after all internal code is fixed up.  Note that https://dart-review.googlesource.com/c/sdk/+/39680 needs to be modified a bit to make the tear-off null-aware.  My current work-in-progress is here: https://dart-review.googlesource.com/#/c/sdk/+/43482

**Comment by vsmenon** [comment]
Great - thanks!
