### ISSUE TITLE
Restrict behavior of callable classes - VM implementation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32154]
This is the VM component of meta-bug #32152.  See the meta-bug for details.

**Comment by mraleph** [comment]
Regis, if you have some free slot please take a look at this.

**Comment by a-siva** [comment]
@crelier It appears that there is still a missing piece with regards to callable classes
(see the CL from Jenny https://dart-review.googlesource.com/c/sdk/+/45141). Apparently
'implements Function' should be ignored in Dart 2 and something like
clas B { }
class D implements Function {
  B call(B b) => b;
}
D d = new D();
print(d is Function);
Should print false, in the VM we print true now.

**Comment by crelier** [comment]
Ah, OK. I was not aware of this restriction.
Sure, I'll take care of it. Thanks!
