### ISSUE TITLE
Restrict behavior of callable classes - analyzer implementation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32156]
This is the analyzer component of meta-bug #32152.  See the meta-bug for details.

**Comment by jmesserly** [comment]
not quite ready to send out, but I'm working on this in https://dart-review.googlesource.com/c/sdk/+/45141

**Comment by stereotype441** [comment]
Marking as P1 since it is the last checkbox on P1 bug #31638, which in turn is the last checkbox on P1 bug #31640.
