### ISSUE TITLE
fasta testing compiler configuration fails without an explicit runtime

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#32169]
Many of the compilers can guess a default runtime and vice versa.  Not fasta:

```
$ tools/test.py -m release -c fasta --strong -v language_2/generic_function_bounds_test
Unhandled exception:
unreachable
#0      Compiler.defaultRuntime (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/configuration.dart:654:5)
#1      OptionsParser._expandConfigurations.<anonymous closure> (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/options.dart:588:62)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:342)
#4      List.addAll (dart:core-patch/dart:core/growable_array.dart:188)
#5      OptionsParser._expandConfigurations (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/options.dart:588:18)
#6      OptionsParser._createConfigurations (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/options.dart:533:12)
#7      OptionsParser.parse (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/options.dart:463:12)
#8      main (file:///home/kmillikin/dart.git/sdk/tools/testing/dart/main.dart:31:31)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```

@whesse @athomas @peter-ahe-google

**Comment by whesse** [comment]
Yes, I agree that runtime none should be the default here.

**Comment by peter-ahe-google** [comment]
If the compiler can select the default runtime, I want it to select the mode as well.

**Comment by peter-ahe-google** [comment]
[Proposed fix](https://dart-review.googlesource.com/c/sdk/+/41661).

**Comment by lrhn** [comment]
While we are at it, any chance of DDC and dartk automatically selecting strong mode? :)

**Comment by peter-ahe-google** [comment]
I've already sent out the CL.

**Comment by peter-ahe-google** [comment]
What I mean: I've already sent out the CL, so it is too late requesting additional features.

**Comment by peter-ahe-google** [comment]
FWIW, I'm personally more concerned with making strong mode the default. We should remove the --strong option and add a --legacy option instead. However, this is a really big change that I don't feel I have time to embark on right now.

**Comment by kmillikin** [comment]
I just tried it and it works as expected.

**Comment by kmillikin** [comment]
@lrhn at least right now, you do not need --strong when testing DDC or DDK.  I'm not sure if it's the compiler or the test suite that selects it.  There are defaults for architecture, mode, and --strong:

```
$ tools/test.py -cdartdevc,dartdevk -rnone,chrome language_2 -pdiff
Test configurations: dartdevc_none_release_x64_strong dartdevk_none_release_x64_strong dartdevc_chrome_release_x64_strong dartdevk_chrome_release_x64_strong
```

**Comment by lrhn** [comment]
Woot, someone already fixed it, and didn't tell me! Thanks! :)
