### ISSUE TITLE
Implement non-speculative version of int64 multiplication for 32-bit platforms

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32163]
Currently, BinaryInt64OpInstr with op_kind = kMUL performs deoptimization on 32-bit platforms (32-bit arm and ia32). As a consequence, this instruction can't be used in AOT-generated code, and integer multiplication is generated as a call (+ accompanying boxing/unboxing).

It would be more efficient to implement non-speculative integer multiplication and use it in AOT.

/cc @mraleph

**Comment by mraleph** [comment]
Duplicate of #31878
