### ISSUE TITLE
Confusing error message on type argument mismatch

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32178]
I'm getting this error from the analyzer:

```
[ARGUMENT_TYPE_NOT_ASSIGNABLE] The argument type 'List<MapEntry> (.../sdk/lib/core/list.dart)' can't be assigned to the parameter type 'List<MapEntry> (.../sdk/lib/core/list.dart)'.
```

Note that I'm formatting the machine readable format differently from how the analyzer normally prints messages.

The problem is the MapEntry argument. One version is from package:kernel/ast.dart the other is from dart:core.

**Comment by srawlins** [comment]
Duplicate of #29058, which has more examples.
