### ISSUE TITLE
Surprising claim about subtyping with FutureOr.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32176]
Consider the following program:
```dart
import 'dart:async';
FutureOr<void> foo(void t) => t;
main() => foo(42);
```
We get the following response (where `n015.dart` contains the above program):
```
> dartanalyzer --version
dartanalyzer version 2.0.0-dev.26.0
> dartanalyzer --strong n015.dart
Analyzing n015.dart...
  error • The return type 'void' isn't a 'FutureOr<void>', as defined by the method 'foo' at n015.dart:6:31 • return_of_invalid_type
1 error found.
```
It is currently being debated whether that situation should be a compile-time error, but it's not because of the typing relation between `T` and `FutureOr<T>` for any `T`. The specification has the following:
```
The \code{FutureOr<$T$>} type is a non-class type with the following
type relations:
\begin{itemize}
    \item{} $T$ <: \code{FutureOr<$T$>}.
    \item{} \code{Future<$T$>} <: \code{FutureOr<$T$>}.
    \item{} If $T$ <: $S$ and \code{Future<$T$>} <: $S$
        then \code{FutureOr<$T$>} <: $S$.
        \commentary{In particular, \code{FutureOr<$T$>} <: \code{Object}.}
\end{itemize}.
```
so in particular `void <: FutureOr<void>`.

The reason why the program currently has a compile-time error is that `foo` is an "arrow" function (`=>`) whose return type is not `void`, in which case it is not allowed for its returned expression to have type `void`.

Even if we accept [void-to-void data flows](https://dart-review.googlesource.com/c/sdk/+/38060) then we will still need a special permission relating to `FutureOr<void>`, or it will remain an error to have such a "void body" in a non-void arrow function&mdash;but it's not a subtype error, it is specifically a "discard that value!" error.

**Comment by srawlins** [comment]
This is still the response analyzer gives. 🤷

**Comment by eernstg** [comment]
This issue was rather vague in the first place, probably also because some of the rules were being debated. The treatment of `void` has been stable for quite a while now, and I believe we can close it:

The null-safety rules about return statements in non-generator, synchronous (i.e., non-async) functions includes the following:

> It is a compile-time error if [the return statement] `s` is `return e;`,
> [the declared return type] `T` is neither `void` nor `dynamic`,
> and [the static type of `e`] is `void`.

There would not have been an error if the function were `async` (and that makes sense, too), but there is no exception for the regular non-async function. So the should be reported, and it is working as intended (in the analyzer as well as the CFE).
