### ISSUE TITLE
Editing assists add new/const even when run in dart 2 mode

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#32175]
Repro steps:
1. Enable dart 2 preview in the editor
1. Use the editing assist to 'Center widget'

Expected result: assist adds `Center(child: ...)`
Actual result: assist adds `new Center(child: ...)`

**Comment by mit-mit** [comment]
cc @scheglov

**Comment by devoncarew** [comment]
We should likely try and match the surrounding code style here, or key off a user preference or analysis options file setting?

**Comment by mit-mit** [comment]
I'd be much bolder and always omit these when using Dart 2 for Flutter. I see no reason why we could encourage manually adding `new`/`const` for Flutter code.

**Comment by mit-mit** [comment]
(We can always add a setting later if there is lots of demand for it)

**Comment by devoncarew** [comment]
From some discussion, a setting available in the analysis options file, and falling back to the --preview-dart-2 state, would likely hit satisfy most use cases.

**Comment by devoncarew** [comment]
We may delay implementing an analysis options setting until we know there's need for it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/42320
