### ISSUE TITLE
Analyzer references break when void is used as a type parameter

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#32170]
Analyzer will fail to resolve references in classes that use `void` as a type parameter. For example:

```dart
abstract class A<T> {
  T foo();
}

class B implements A<void> {
  @override
  void foo() {
    int x = 300;
    String y = 'hello';
    print('$x $y');
  }
}
```

If I open this in IntelliJ, I can't go to the declaration of any identifiers in the body of `B`.

I'm using this version of analyzer:
Analysis server version: 1.18.4
Dart SDK: 2.0.0-dev.20.0 (Mon Jan 29 16:25:01 2018 +0100) on "linux_x64"

**Comment by bwilkerson** [comment]
This appears to be working in IntelliJ using the bleeding edge build, so it appears to have been fixed in the last few days. Please let me know if you're still seeing this after updating.

**Comment by hterkelsen** [comment]
It still doesn't work for me, even with a bleeding edge Dart SDK.

**Comment by bwilkerson** [comment]
I'm not sure how to reproduce this. When I paste the sample code into an empty file I am able to navigate from every identifier in `B`. Are there any errors being reported in the instrumentation log?

**Comment by hterkelsen** [comment]
There are no exceptions reported, but I don't know how to turn on instrumentation for the analysis server in IntelliJ.

I can repro the problem by following these steps:

1. Start IntelliJ and do "Create New Project" at the project select screen.
2. Create a Dart project and opt out of generating code
3. Create a new Dart file called "bug.dart"
4. Copy-paste the code above
5. Try to "Go To Reference" of any identifier in `B`.

Here's what I am using:

IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017

Analysis server version: 1.18.6
Dart SDK: 2.0.0-edge.ec9c927b180f35f17d94f7fae7c97e94e9482056 (Wed Feb 14 22:03:23 2018 +0000) on "linux_x64"

**Comment by hterkelsen** [comment]
I just installed IntelliJ 2017.3 and it works properly now. Seems like a bug in IntelliJ 2017.2?

**Comment by bwilkerson** [comment]
I suppose it's possible. @jwren Does that seem reasonable to you?

**Comment by jwren** [comment]
If it is working fine in 2017.3, then this is a no-op, and probably a bug that has been fixed.  Please re-open if you see the behavior in 2017.3 or 2018.1.
