### ISSUE TITLE
Incorrect `selection` returned in quick fixes from analysis server

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32184]
Copied from https://github.com/Dart-Code/Dart-Code/issues/573

We're using the `selection` that comes back with the assist, but it seems to be at the end of the inserted text.

Example:

```dart
import 'package:flutter/material.dart';

class Danny extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Center(child: const Text('test'));
  }
}
```

I put my cursor in the middle of the word `Center` (position 155) and invoke "Add widget padding":

```js
{"id":"15","method":"edit.getAssists","params":{"file":"m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart","length":0,"offset":155}}
```

The assist comes back like this:

```js
{
	"message": "Add widget padding",
	"edits": [
		{
			"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart",
			"fileStamp": 0,
			"edits": [
				{
					"offset": 146,
					"length": 39,
					"replacement": "new Padding(\r\n      padding: const EdgeInsets.all(8.0),\r\n      child: const Center(child: const Text('test')),\r\n    )"
				}
			]
		}
	],
	"linkedEditGroups": [],
	"selection": {
		"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart",
		"offset": 263
	}
}
```

The final doc looks like this:

```dart
import 'package:flutter/material.dart';

class Danny extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Padding(
      padding: const EdgeInsets.all(8.0),
      child: const Center(child: const Text('test')),
    );
  }
}
```

The selection given was 263, which is where the `);` is but we would expect it to remain in the middle of the word `Center` (225/226?).

**Comment by bwilkerson** [comment]
@scheglov It appears the conversation has migrated.

I'll just ask the question: Do we really want the selection to remain in the middle of `Center`, or do we want the selection to be at the beginning of the inserted widget? I'm just questioning what the dev process looks like. What does a user typically want to do after wrapping a widget in this way?

**Comment by DanTup** [comment]
Personally, I think when wrapping with a widget, I'd prefer the cursor to stay on the same constructor it was before. I'm not so sure about if you were doing "swap with parent" etc. though.

That said; I think both of your suggestions would be reasonable, I don't think either would feel like a bug as the current behaviour does.

**Comment by scheglov** [comment]
I'm removing `selection` field value for these Flutter related Quick Assists.
We decided that we don't want to move caret under the user.

https://dart-review.googlesource.com/c/sdk/+/41920
