### ISSUE TITLE
Ensure error parity with AstBuilder regarding change 41720

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32181]
@danrubel added a number of compile-time errors in [change 41720](https://dart-review.googlesource.com/c/sdk/+/41720). We should make sure that these errors are also reported by Fasta, and that we're using the same error code.

**Comment by askeksa-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/41720 was abandoned. Is this issue still valid?
