### ISSUE TITLE
front-end issues an error when returning supertype A from async function returning Future<B>, where B is subclass of A

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32185]
```dart
import 'dart:async';

class A { }
class B extends A { }

A f() => null;

Future<B> g() async => f();

void main() {

}
```

results in 

```console
$ pkg/vm/tool/dart2 /tmp/yyy.dart                                     254 ↵
file:///tmp/yyy.dart:8:24: Error: A value of type '#lib1::A' can't be assigned to a variable of type 'dart.async::FutureOr<#lib1::B>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.async::FutureOr<#lib1::B>'.
Future<B> g() async => f();
                       ^
file:///tmp/yyy.dart:8:24: Error: A value of type '#lib1::A' can't be assigned to a variable of type 'dart.async::FutureOr<#lib1::B>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.async::FutureOr<#lib1::B>'.
Future<B> g() async => f();
   
```

Analyzer does not report an error here unless I run it with `--no-implicit-casts`. 

@leafpetersen @eernstg @lrhn can you confirm which behavior is correct?

**Comment by eernstg** [comment]
The first relevant location for checking `g` is this one:
```
It is a static warning if the declared return type of a function
marked \ASYNC{} is not a supertype of \code{Future<\mbox{$T$}>}
for some type $T$.
```
So `Future<B>` must be a supertype of `Future<T>` for same type `T`, which is of course true.

Next, `\subsection{Return}` says:
```
It is a static type warning if the body of $f$ is marked \ASYNC{} and
the type \code{Future<$flatten(T)$>} (\ref{functionExpressions}) may not
be assigned to the declared return type of $f$.
```
So `Future<flatten(A)>`, i.e., `Future<A>`, should be assignable to `Future<B>`, which it is (as a downcast). So I can't see any errors.

**Comment by leafpetersen** [comment]
The analyzer behavior is correct.  We do downwards inference using `FutureOr<B>` as the return context (since either may be returned), but the assignability check is more relaxed for async functions because of the flattening.  I suspect that the new front end is just checking that the type of the returned value is assignable to the return context type (which is normally correct), but for async functions, you need to check against both branches of the `FutureOr` individually.

**Comment by eernstg** [comment]
It is actually possible for a type `T` to be such that `Future<flatten(T)>` is a subtype of `Future<num>`, but all four of `T <: num`, `T <: Future<num>`, `num <: T`, `Future<num> <: T` are false. As far as I can see, this means that it is not always sufficient to check against both branches individually (cf. #32233).

**Comment by lrhn** [comment]
The type relations here are `B <: A` and `B <: FutureOr<B>`, but with not relation between `A` and `FutureOr<B>`, so there is no implicit downcast. Same if you consider the returned value to be a `Future<A>` (`Future<flatten(actual return expression type)>`), there is no direct type relation between `Future<A>` and `FutureOr<B>`.

I think we need to handle `FutureOr` specially in assignability checks, and allow assignment if the asignee is assignable to either of the types of the union, not just to the union itself.

(I also think that we should allow assigning `Iterable<int>`  to `List<num>` and vice versa - it's silly that we disallow `List<num> l = x as Iterable<int>;` but do allow the *less precise* `List<num> l =x as Iterable<num>;`).

**Comment by eernstg** [comment]
The immediate issue here is that the check for assignability wrt "both branches of `FutureOr<T>`" for an `async` function with declared return type `Future<T>` does not fully implement the specification, and #32233 is a counterexample.

**Comment by leafpetersen** [comment]
> As far as I can see, this means that it is not always sufficient to check for assignability against both branches individually

Ah right, because of `FutureOr`.  There's a long standing bug open about this, I linked it from the issue you opened.

**Comment by leafpetersen** [comment]
> I think we need to handle FutureOr specially in assignability checks, and allow assignment if the asignee is assignable to either of the types of the union, not just to the union itself.

Yeah, I've thought about it.  We can always relax this at some point.  I can't say that making implicit downcasts more forgiving has been top of my TODO list... :)  And I haven't seen this show up much, if at all, in code.

**Comment by kmillikin** [comment]
This isn't actually fixed, there are still some cases that we do not get right.

**Comment by kmillikin** [comment]
I think this is fixed again.
