### ISSUE TITLE
Cannot launch web tests with vm + frontend

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#32199]
Unable to use the vm running with the front end to launch web tests. Errors out with dart:html not found message.

Using 2.0.0-dev.23.0

**Comment by a-siva** [comment]
I think this is a front end issue. 
We had made special changes in the VM to embed the html sources in the VM and enabled it in the dart_bootstrap version. I am assuming if you have a way for the front end to find dart:html it should all work.

**Comment by keertip** [comment]
Not sure I understand what is dart_bootstrap. Is that the striped down vm binary?

**Comment by sigmundch** [comment]
@keertip - is the import to dart:html guarded on a conditional import? (I assume that the VM before didn't support importing dart:html either).

**Comment by keertip** [comment]
Its not a conditional import. Saw this a couple of days ago, but unable to reproduce it. Running the hello web test,no tests are run, but no messages either. Will investigate further and update issue.

**Comment by keertip** [comment]
Cannot reproduce this with the latest sources, so closing the issue. Sorry for the spam.
