### ISSUE TITLE
Rewrite a bunch of VM tests to make them strong mode clean

### ISSUE THREAD

**Issue by sivachandra** [dart-lang/sdk#32190]
The following VM tests have to be re-written to make them work cleanly in strong mode.

- [ ] cc/DartAPI_ImportLibrary3: Fail
- [ ] cc/DartAPI_IsolateSetCheckedMode: Fail
- [ ] cc/DartAPI_LazyLoadDeoptimizes: Crash
- [ ] cc/DartAPI_NativePortPostInteger: Crash
- [ ] cc/DartAPI_NativePortReceiveInteger: Timeout
- [ ] cc/DartAPI_NativePortReceiveNull: Timeout
- [ ] cc/DartAPI_NewNativePort: Crash
- [ ] cc/DartGeneratedArrayLiteralMessages: Crash
- [ ] cc/FullSnapshot1: Crash
- [ ] cc/IsolateReload_LibraryImportAdded: Crash
- [ ] cc/IsolateReload_LibraryImportRemoved: Fail
- [ ] cc/IsolateReload_LibraryLookup: Crash
- [x] cc/Mixin_PrivateSuperResolutionCrossLibraryShouldFail: Fail
- [x] cc/StackMapGC: Crash

**Comment by a-siva** [comment]
All required tests have been rewired to run in Dart 2 mode.
