### ISSUE TITLE
Broken geoposition.coords in Firefox

### ISSUE THREAD

**Issue by chochief** [dart-lang/sdk#32203]
`window.navigator.geolocation.getCurrentPosition(enableHighAccuracy: true).then((Geoposition geoposition) => print('lat ${geoposition.coords.latitude}'));`

`window.navigator.geolocation.watchPosition(enableHighAccuracy: true).listen((Geoposition geoposition) => print('lat ${geoposition.coords.latitude}'));`

Google Chrome 64.0.3282.167 - without errors
Firefox 58.0.2 Firefox 57.0 Firefox 58.0b11 - error when trying to get properties of geoposition.coords

Dart VM version: 1.24.3 (Wed Dec 13 18:05:29 2017) on "windows_x64"

**Comment by zoechi** [comment]
What's the exact error message?

**Comment by chochief** [comment]
![2018-02-16_14-37-42](https://user-images.githubusercontent.com/36546090/36325936-ce4afb12-1372-11e8-8837-049da2b01e57.png)

**Comment by matanlurey** [comment]
Unfortunately we are no longer updating Dart SDK 1.24.3.

Quite a bit of work has been put in the 2.0.0-dev channel, so this might already be fixed.
