### ISSUE TITLE
cascade target hover doesn't work in DDC

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#32209]
After the fix for #32083, cascade targets aren't hoverable at least in some cases

This is likely due to how cascade targets work in Analyzer. `_getTarget` will find the real target, but that means the same node could end up marked twice, possibly breaking the source mapping.

**Comment by jmesserly** [comment]
CC @vsmenon

**Comment by jmesserly** [comment]
This also may be specific to JS.MetaLet.

I would love for MetaLet to work more like DDK's handling of LetExpression. It tackles how to emit temporary variables without needing function blocks, which likely improves performance. That may be best to attack as a different bug, or putting off until we migrate to Kernel (at which point, it becomes moot).

**Comment by jmesserly** [comment]
We also cannot put source locations on JS.TemporaryId because it uses identity equality. That can be fixed by splitting the declaration and references to the temporary variable into 2 classes. I'm in favor of that & DDK needs it too, if it ever has spans on temp variables. (My assumption was that temps would not have source locations, however, at least for DDC there are some cases where they could have reasonable source locations.)

**Comment by vsmenon** [comment]
This may be related.  If I step through `main` below, dev tools pause 4 times on the line with just `f` and not any of the `bar` call sites cascaded from it.

```
class Foo {
  String greeting = "hello ";
  void bar(String name) {
    print('$greeting $name');
  }
}

void main() {
  var f = new Foo();

  f
    ..bar('world')
    ..bar('solar system')
    ..bar('galaxy')
    ..bar('universe');
}
```

**Comment by jmesserly** [comment]
> This may be related. If I step through main below, dev tools pause 4 times on the line with just f and not any of the bar call sites cascaded from it.

yes that's expected (cascade target is marked multiple times due to how cascades are represented in Analyzer). Since DDK does not have an equivalent problem with cascades, I didn't push much on it yet.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/42084
