### ISSUE TITLE
AST InstanceCreationExpression bug

### ISSUE THREAD

**Issue by mk13** [dart-lang/sdk#32208]
Given the following:

```
class MyClass<A, B, C> {
  MyClass.someNamed(...) { ... }
}
```

In:
```
new MyClass.someNamed(...)
```
If n is the InstanceCreationExpression that represents above, then:
`n.constructorName.type.name.name` is 'MyClass.someNamed' with
`n.constructorName.name` being null. From my understanding, it should still be 'MyClass' and 'someNamed' respectively.

Interestingly, in the the following code:
```
new MyClass<Foo, Bar, Baz>.someNamed(...) { ... }
```
It seems correct where `n.constructorName.type.name.name` is 'MyClass' and `n.constructorName.name` is 'someNamed'.

**Comment by bwilkerson** [comment]
This is a known issue.

Unfortunately, at the time that the parser is parsing this expression, we cannot tell the difference between `prefix '.' typeName` and `typeName '.' constructorName`. The parser defaults to the first, with the intention that we would re-write the expression in the resolver, but that work never happened. We hope that this will be fixed when we move analyzer to the common front end.
