### ISSUE TITLE
remove library-root option from DDC and don't generate very long library names

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#32211]
We should choose short names for local use, at least (and possibly for export as well), and remove the `library-root` flag.

A simple heuristic would be to just take the file name without extension, rather than `jsLibraryName` which is the full export name (includes path).

As a related issue, we should also shorten the library names in the export path. As long as we can see the set of library URIs in a JS module (with its Dart summary), we can choose a short, reasonable looking unique name. That also lets us remove the legacy `library-root` flag for file URIs.

**Comment by jmesserly** [comment]
tagging performance because this affects code size and likely JS parse times/memory usage.

**Comment by jmesserly** [comment]
Ah, this happens because of how we generate ES6 export/import. Currently export/import name must match the local name we're using. That's fixable, but it's also a nice property to have & will look nicest when we've moved over to modules.

So it might be easier to attack the `library-root` issue directly, and have DDC assign short non-conflicting names for each library in a module. I think this will be easier to implement in DDK, where (I think) we can see which libraries belong to which summaries. I'm not sure if we have that information in Analyzer (without re-parsing the summary or something like that).

**Comment by jmesserly** [comment]
Yet another way to attack this one is to use library names less often. For classes/top-level functions, we can usually use a local variable instead. That would have a big benefit to code size for some of the code I'm seeing.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/42885

**Comment by nex3** [comment]
> I like this idea, but we can't implement a flag right now because there's no place for DDC to save extra info in Analyzer summaries/Kernel IL files. Also DDC consumes summaries that are built by other tools (e.g. Analyzer CLI). I believe this is done to get more build parallelism. But it means we can't transmit any information between separately compiled modules. (Most modular compilers do not have this restriction, and it would be nice to see it lifted for DDC.)

Would it still be possible to use my default de-duplication scheme immediately?

> For our debugger UI, we already emit a URI->library object map, so it shouldn't be too difficult to provide an API for importing via Dart library URI. That would provide a reliable way of importing libraries from JS without relying on the compiler's library naming scheme.

I'm curious to hear more about this... where does this file go? How would it be used by downstream `dartdevc` invocations exactly?

**Comment by jmesserly** [comment]
> Would it still be possible to use my default de-duplication scheme immediately?

yes, something similar is implemented in https://dart-review.googlesource.com/c/sdk/+/42885

> I'm curious to hear more about this... where does this file go? How would it be used by downstream dartdevc invocations exactly?

It's runtime data. So we could use it to provide a reliable import from JS, for example, by making that mapping the default export:
```js
import fooPkg from 'foo';
let bar = fooPkg['package:foo/bar.dart'];
```
That isn't implemented yet, currently it relies on string-based global module table, so it looks like:
```js
let fooPkg = dart.getModuleLibraries('foo');
let bar = fooPkg['package:foo/bar.dart'];
```

**Comment by nex3** [comment]
Oh, interesting. Not super friendly as far as consuming Dart from JS is concerned, but that does seem like a reasonable stopgap solution until DDC can embed information in the summary.

**Comment by nshahan** [comment]
The `--library-root` option was removed along with the analyzer based DDC.
