### ISSUE TITLE
VM silently accepts generic `is T`.

### ISSUE THREAD

**Issue by rkirsling** [dart-lang/sdk#32213]
I was shocked to discover just now that the following returns `true` for all inputs:
```dart
bool check<T>(Object value) => value is T;
```
I now realize this is [documented](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/doc/GENERIC_METHODS.md#using-generic-method-type-parameters) as a not-yet-supported feature, but the documentation suggests that the VM and dart2js will produce a helpful error. This is not true in `2.0.0-dev.26.0`.

I see that dart2js does give a [warning](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/diagnostics/messages.dart#L1206):
```
Warning: Method type variables do not have a runtime value.
Try using the upper bound of the type variable, or refactor the code to avoid needing this runtime value.
```
But the VM silently accepts the code (_and the linter has nothing to say about it either_).
Needless to say, silence is pretty disastrous, as the user has every reason to expect this to work. 😅

**Comment by rkirsling** [comment]
Looks like the 1.x error was: `The type parameter 'T' can't be used in a type test.`

**Comment by rkirsling** [comment]
Evidently the error was intentionally removed in #30530; it's just that the feature still isn't enabled by default. 😕

**Comment by zoechi** [comment]
You could try `--preview-dart-2`. I believe this is the new path that will become the default soon.

**Comment by mraleph** [comment]
I think this is the intended behavior during the transition period. Once we flip Dart 2 to be default (which is still few months away by our estimates) the code will start behaving as expected.
