### ISSUE TITLE
Analyzer in strong mode does not error for some illegal casts

### ISSUE THREAD

**Issue by aemino** [dart-lang/sdk#32218]
Consider the following code
```dart
abstract class A {}

abstract class B implements A {}

class C extends A with B {}

abstract class D implements B {}

// needs to be two letters to use `as`
abstract class EE implements D, C {}

void main() {
  final E = new C() as EE;
}
```
No error occurs when I attempt to cast `C` to `EE`, while an error does occur on the VM or in dart2js.

I've tested dartanalyzer v1.24.3 in strong mode as well as dartanalyzer v2.0.0-dev.26.0 with and without `--preview-dart-2`.

**Comment by bwilkerson** [comment]
That's correct, and I believe that it's working as intended. The type cast essentially tells the compilers and analyzers to assume that you know what you're doing and to defer checking until run time.
