### ISSUE TITLE
Implement `--preview-dart-2` option for `pub run`

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#32214]
Are there plans to implement `--preview-dart-2` option for `pub run`?

See https://github.com/flutter/flutter/pull/14728#discussion_r168903155 for context.

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/sdk/issues/32188

**Comment by kevmoo** [comment]
CC @a-siva

**Comment by nex3** [comment]
I'd love to add this, but we need support from the isolate library first. I've filed https://github.com/dart-lang/sdk/issues/32253 to track that.

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub#1807
