### ISSUE TITLE
"Import library" quickfix doesn't appear for constructor calls without new/const

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32220]
Copied from https://github.com/Dart-Code/Dart-Code/issues/588 (@lukef)

----------

Dart-Code: 2.9.0-beta.1
Code: 1.20.1 (1.20.1)

If you use a class definition that you have not yet imported and you're omitting the `new` keyword then the quickfix to add an import does not appear:

<img width="389" alt="screen shot 2018-02-18 at 7 56 27 am" src="https://user-images.githubusercontent.com/37941/36353892-4e027772-1481-11e8-8e75-d981e37be0c9.png">

If you add the `new` keyword and try again then it will work:

<img width="561" alt="screen shot 2018-02-18 at 7 56 43 am" src="https://user-images.githubusercontent.com/37941/36353893-5914e262-1481-11e8-9089-79c25ea61940.png">

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/42340
