### ISSUE TITLE
need a precompiler bot running with --vm-options=--obfuscate

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32229]
We are getting customers using obfuscation so we need to ensure that our obfuscation code does not regress.

**Comment by athomas** [comment]
The first build was bright red, though:
https://ci.chromium.org/p/dart/builders/luci.dart.try/vm-kernel-precomp-obfuscate-linux-release-x64-try/1

**Comment by mraleph** [comment]
I don't think dartkp-obfuscate is doing what it should be doing:

```
$ python tools/test.py -m release -n dartkp-obfuscate-linux-release-x64 co19/Language/Errors_and_Warnings/static_warning_t01

Test configuration:
    custom configuration(architecture: x64, compiler: none, mode: release, runtime: vm, system: linux, vm-options: [], timeout: null, preview-dart-2)
```

Note that in custom configuration `compiler` is `none` and `runtime` is `vm` (I should be `dart_precompiled`).

**Comment by dgrove** [comment]
Any updates here?

**Comment by athomas** [comment]
The bot is running and working (as in, running all tests, but it isn't green) since the last commit, referenced above.
