### ISSUE TITLE
Analysis server tests fail on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32226]
The analysis server tests seem to fail on my Windows PC (though work fine on my Mac). They're passing the builds so I presume there's something "different" about my machine (though possibly whatever it is isn't isolated to just me).

I'm investigating this now; but raising a case as somewhere to dump notes and in case it ends up needing code changes.

The failure reasons vary, but they're mostly things like null pointers or missing data. Seems like some expected data (metadata for the SDK?) isn't being loaded - though the analysis server actually runs (outside of the tests) correctly.

<details>
<summary>Example failure</summary>
<code><pre>
00:00 [32m+0[0m: test001-1[0m
00:00 [32m+0[0m[31m -1[0m: test001-1 [1m[31m[E][0m[0m
  Expected 'toString' but found none:
    []
  package:test/src/frontend/expect.dart 165:30                  fail
  test\completion_test_support.dart 46:7                        CompletionTestCase.assertHasCompletion
  test\completion_test_support.dart 88:9                        CompletionTestCase.runTest.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                     _rootRunUnary
  dart:async/zone.dart 1031                                     _CustomZone.runUnary
  dart:async/future_impl.dart 129                               _FutureListener.handleValue
  dart:async/future_impl.dart 633                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 662                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 51                                _SyncCompleter.complete
  dart:async-patch/dart:async/async_patch.dart 292              _completeOnAsyncReturn
  test\domain_completion_util.dart 92:3                         AbstractCompletionDomainTest.getSuggestions
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                     _rootRunUnary
  dart:async/zone.dart 1031                                     _CustomZone.runUnary
  dart:async/future_impl.dart 129                               _FutureListener.handleValue
  dart:async/future_impl.dart 633                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 662                               _Future._propagateToListeners
  dart:async/future_impl.dart 342                               _Future._addListener.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 391           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 238                               _Future.then
  test\completion_test_support.dart 85:38                       CompletionTestCase.runTest
  test\completion_test.dart 2512:23                             CompletionTestBuilder.buildTests.<fn>
  package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                 Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 247:23                  Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 247:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/declarer.dart 143:66                 Declarer.test.<fn>
  package:test/src/backend/invoker.dart 404:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 403:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 172                                    new Future
  package:test/src/backend/invoker.dart 403:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 390:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 390:9                   Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 444:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 389:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 388:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 200                                    new Future.microtask.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113        _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166        _RawReceivePortImpl._handleMessage
</pre></code>
</details>

**Comment by DanTup** [comment]
@scheglov suggested enabling debug output to stdout via PerformanceLog and looking at which files it analyses, and whether these files exist in the memory file system. If I've done this correctly, this is the output I get:

```text
+++ Analyzing.
	+++ Create unlinked for C:\project\bin\test.dart.
	--- Create unlinked for C:\project\bin\test.dart in 61 ms.
	+++ Create unlinked for C:\lib\core\core.dart.
	--- Create unlinked for C:\lib\core\core.dart in 0 ms.
	+++ Compute analysis result for C:\project\bin\test.dart.
		+++ Create library context.
			+++ Append library files.
			--- Append library files in 0 ms.
			+++ Load linked bundles.
				Loaded 1 linked bundles.
			--- Load linked bundles in 0 ms.
			+++ Link bundles.
				Linked 1 bundles.
			--- Link bundles in 42 ms.
		--- Create library context in 131 ms.
	--- Compute analysis result for C:\project\bin\test.dart in 171 ms.
```

Suggests it's loading `core.dart` and "Loaded 1 linked bundles", not sure if that's correct. I'm gonna figure out why breakpoints aren't working and see if I can debug further.

**Comment by DanTup** [comment]
Ok, I'm really confused!

The class `SummaryResynthesizer` has a constructor that calls `_buildTypeProvider`. That method looks like this:

```dart
  void _buildTypeProvider() {
    _coreLibrary = getLibraryElement('dart:core') as LibraryElementImpl;
    _asyncLibrary = getLibraryElement('dart:async') as LibraryElementImpl;
    SummaryTypeProvider summaryTypeProvider = new SummaryTypeProvider();
    summaryTypeProvider.initializeCore(_coreLibrary);
    summaryTypeProvider.initializeAsync(_asyncLibrary);
    _typeProvider = summaryTypeProvider;
  }
```

So this method seems to build and set the `_typeProvider` field. However, when it runs for me, inside `getLibraryElement` it tries to *use* `typeProvider` if the library being asked for is not already in `_resynthesizedLibraries` (so it seems like `dart:core` and `dart:async` are expected to already be in `_resynthesizedLibraries`. However, since this is being called from the constructor, I don't understand how `_resynthesizedLibraries` was supposed to have been populated? `getLibraryElement` seems to be the only place that is populating this, but the first time it's hit is when it's called for `dart:core` and then it fails.

I can't get breakpoints working here for some reason, but gonna see if I can dig through this on my Mac and see what's different.

**Comment by DanTup** [comment]
> I can't get breakpoints working here for some reason

Of course, they work on Mac 😢

**Comment by DanTup** [comment]
Ok, getting further...

On my Mac, when we get into package_bundle_reader's `getLinkedSummary` there are 5 items in `_dataStore.linkedMap`; the testing dart file and `dart:core`, `dart:async`, `dart:math`, `dart:_internal`.

On my Windows PC, only the test file is there. That's why the summary is not being found and it's taking the code path that tries to use `_typeProvider` and crashes.

Working on figuring out why the others aren't there...

**Comment by DanTup** [comment]
Ok, the libraries aren't loaded because of this line in the `LibraryContext.forSingleLibrary` constructor:

```dart
if (library.exists || library == targetLibrary) {
```

`exists` returns false because `_fsState._resourceProvider.getFile(path)` throws:

```text
FileSystemException(path=C:\lib\core\core.dart; message=File "C:\lib\core\core.dart" does not exist.)
```

So, I added some logging in `memory_file_system.dart` in the `newFile` method and I see:

```text
00:00 +0: AnalysisHoverTest | test_class_abstract
new file: \lib\core\core.dart
new file: \lib\async\async.dart
new file: \lib\collection\collection.dart
new file: \lib\convert\convert.dart
new file: \lib\math\math.dart
new file: \lib\html\dartium\html_dartium.dart
new file: \lib\internal\internal.dart
new file: C:\lib\_internal\sdk_library_metadata\lib\libraries.dart
new file: C:\project\bin\test.dart
```

I think I'm starting to see why it doesn't work; but I'm not sure why it works on the build bots!

**Comment by DanTup** [comment]
So, these paths being added to the memory file system are coming from `mock_sdk.dart`. The paths are consistent in the definitions and the mapping from `dart:xxx` to the path, so I'm guessing that the code on one side (the code handling the imports) it's doing some fixing up for Windows (eg. `/lib/core/core.dart` is becoming `C:\lib\core\core.dart`) which means it doesn't match.

Than just rigging the `mock_sdk` to match what's expected on Windows, probably we should find a way to make these naturally the same (eg. perform the same fixing up as we write the mock files into the memory file system).

I'm still kinda baffled about these working on the build bots; (@bwilkerson @scheglov lmk if you have any ideas!)

**Comment by DanTup** [comment]
@bwilkerson @scheglov PR #32230 fixes a large number of the tests for me, and the fix looks reasonable (other code in this method is calling this convert).

I'll dig into the remaining failures; though we should definitely look at why this wasn't causing failures in the build processing in case they're not running correctly (or the results not being interpreted correctly).

**Comment by DanTup** [comment]
Next one...

<details>
<summary>Example failure</summary>
<code><pre>
00:09 [32m+467[0m[31m -1[0m: analysis_server | analysis | GetErrorsTest | test_errorInPart [1m[31m[E][0m[0m
  Exception: Expected errors at result
  package:analysis_server/protocol/protocol_generated.dart 779:9     new AnalysisGetErrorsResult.fromJson
  package:analysis_server/protocol/protocol_generated.dart 788:16    new AnalysisGetErrorsResult.fromResponse
  test\analysis\get_errors_test.dart 148:16                          GetErrorsTest._getErrors
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                     _Completer.completeError
  test\analysis\get_errors_test.dart                                 GetErrorsTest._getErrors
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                          _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77                    _asyncThenWrapperHelper
  test\analysis\get_errors_test.dart 145:61                          GetErrorsTest._getErrors
  test\analysis\get_errors_test.dart 60:45                           GetErrorsTest.test_errorInPart
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                          _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77                    _asyncThenWrapperHelper
  test\analysis\get_errors_test.dart 46:28                           GetErrorsTest.test_errorInPart
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 531              _LocalInstanceMirror._invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 527              _LocalInstanceMirror.invoke
  package:test_reflective_loader/test_reflective_loader.dart 253:35  _runTest.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26       StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14       StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                          _rootRunUnary
  dart:async/zone.dart 1031                                          _CustomZone.runUnary
  dart:async/future_impl.dart 129                                    _FutureListener.handleValue
  dart:async/future_impl.dart 633                                    _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 662                                    _Future._propagateToListeners
  dart:async/future_impl.dart 477                                    _Future._completeWithValue
  dart:async/future_impl.dart 507                                    _Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48       StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 925                                           _CustomZone.runGuarded
  dart:async/zone.dart 965                                           _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                              _microtaskLoop
  dart:async/schedule_microtask.dart 50                              _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 391                _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416                _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                          _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 238                                    _Future.then
  package:test_reflective_loader/test_reflective_loader.dart 253:8   _runTest
  package:test_reflective_loader/test_reflective_loader.dart 126:18  defineReflectiveTests.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                      Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                          _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77                    _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                      Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                       Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                          _CustomZone.registerCallback
  dart:async/zone.dart 964                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 247:23                       Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 1501                                          runZoned
  package:test/src/backend/invoker.dart 247:5                        Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                      Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 1501                                          runZoned
  package:test/src/backend/declarer.dart 158:13                      Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                          _CustomZone.registerCallback
  dart:async/zone.dart 964                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/declarer.dart 143:66                      Declarer.test.<fn>
  package:test/src/backend/invoker.dart 404:25                       Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                          _CustomZone.registerCallback
  dart:async/zone.dart 964                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 403:31                       Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                         new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48       StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 925                                           _CustomZone.runGuarded
  dart:async/zone.dart 965                                           _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48       StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 949                                           _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21                    Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382                _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416                _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                          _CustomZone.registerCallback
  dart:async/zone.dart 964                                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                           new Timer
  dart:async/timer.dart 87                                           Timer.run
  dart:async/future.dart 172                                         new Future
  package:test/src/backend/invoker.dart 403:15                       Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                          _CustomZone.registerCallback
  dart:async/zone.dart 964                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 390:27                       Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 1501                                          runZoned
  package:test/src/backend/invoker.dart 390:9                        Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 444:15                       Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 389:7                        Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                          Chain.capture.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 1501                                          runZoned
  package:stack_trace/src/chain.dart 99:12                           Chain.capture
  package:test/src/backend/invoker.dart 388:11                       Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11          LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31           _LiveTest.run
  dart:async/future.dart 200                                         new Future.microtask.<fn>
  dart:async/zone.dart 1122                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 925                                           _CustomZone.runGuarded
  dart:async/zone.dart 965                                           _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                          _rootRun
  dart:async/zone.dart 1023                                          _CustomZone.run
  dart:async/zone.dart 925                                           _CustomZone.runGuarded
  dart:async/zone.dart 965                                           _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                              _microtaskLoop
  dart:async/schedule_microtask.dart 50                              _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 391                _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416                _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165             _RawReceivePortImpl._handleMessage
</pre></code>
</details>

**Comment by DanTup** [comment]
Ok, this next one is also path-related. The test has this:

```dart
test_errorInPart() async {
    String libPath = '$testFolder/main.dart';
    String partPath = '$testFolder/main_part.dart';
```

I can fix it by doing:

```dart
String libPath = join(testFolder, 'main.dart');
String partPath = join(testFolder, 'main_part.dart');
```

However there are quite a few tests building paths as strings so I don't know if this is the preferred way. I'm gonna change them locally for now so I can see if there are any remaining failures but I won't send a PR until @bwilkerson or @scheglov confirm this is the way we want to fix this.

**Comment by bwilkerson** [comment]
I think we originally designed MemoryResourceProvider to always use a posix path style no matter which platform the tests were actually running on, but then realized that that meant that we were not adequately testing on Windows so we changed it. I suspect there are lots of tests that use an explicit `/` in paths when they ought to be using `join`. So, yes, I think this is the right change to make.

That said, we should probably be using the `join` defined by the resource provider's context rather than the top-level join.

**Comment by DanTup** [comment]
@bwilkerson I'm getting there, though I may need input on this one:

`analysis\notification_analyzedFiles_test.dart` (`test_significant_change`)

This test involves a filename `/foo.dart` which ends up as `\\foo.dart`. It's not clear whether I can change this to `join(projectPath, 'foo.dart')` or whether this file is supposed to be outside of analysis roots (in which case maybe we should have some shared variable for a temp location or something?).

**Comment by DanTup** [comment]
> That said, we should probably be using the `join` defined by the resource provider's context rather than the top-level join.

Thanks for confirming - I'll change these over before I push.

**Comment by DanTup** [comment]
@bwilkerson Will continue tomorrow though I'm a little stumped on this one, maybe you have ideas (it'll become easier once I've sorted my breakpoint issues on Windows, but in the meantime I'm `printf`-debugging`!). Many failures are down to findSdk failing. I added a throw in FolderBasedDartSdk suspecting a path issue:

`throw "CREATING FOLDER BASED SDK FOR " + this._sdkDirectory.path;`

And I get this message:

```text
00:00 +0 -1: AnalysisDomainHandlerTest | test_updateContent_badType [E]
  CREATING FOLDER BASED SDK FOR \
  package:analyzer/src/dart/sdk/sdk.dart 495:5                       new FolderBasedDartSdk
  package:analyzer/src/context/builder.dart 408:36                   ContextBuilder.findSdk.<fn>
  dart:collection-patch/dart:collection/collection_patch.dart 143    _HashMap.putIfAbsent
  package:analyzer/src/generated/sdk.dart 148:19                     DartSdkManager.getSdk
  package:analyzer/src/context/builder.dart 407:23                   ContextBuilder.findSdk
  package:analyzer/src/context/builder.dart 278:19                   ContextBuilder.createSourceFactory
  package:analyzer/src/context/builder.dart 180:16                   ContextBuilder.buildDriver
  package:analysis_server/src/analysis_server.dart 1193:48           ServerContextManagerCallbacks.addAnalysisDriver
  package:analysis_server/src/context_manager.dart 1159:19           ContextManagerImpl._createContext
  package:analysis_server/src/context_manager.dart 1201:16           ContextManagerImpl._createContexts
  package:analysis_server/src/context_manager.dart 770:9             ContextManagerImpl.setRoots
  package:analysis_server/src/analysis_server.dart 893:22            AnalysisServer.setAnalysisRoots
  package:analysis_server/src/domain_analysis.dart 340:12            AnalysisDomainHandler.setAnalysisRoots
  package:analysis_server/src/domain_analysis.dart 265:16            AnalysisDomainHandler.handleRequest
  test\domain_analysis_test.dart 519:33                              AnalysisTestHelper.handleSuccessfulRequest
  test\domain_analysis_test.dart 442:5                               AnalysisTestHelper.createSingleFileProject
  test\domain_analysis_test.dart 148:12                              AnalysisDomainHandlerTest.test_updateContent_badType
```

I'm guessing the `\` is supposed to be the path of the actual SDK that's running the tests? I'm not really sure where the code for that is (I've tried going through the stack with no joy), but this is also starting to look like it's outside of test code (though I'm certain the issue is isolated to tests, since the server runs on its own).

**Comment by bwilkerson** [comment]
I traced it back a bit, and the path is coming from an instance of `DartSdkManager`. The stack trace above doesn't show me where the manager is being created, but based on the test, I'd guess it's happening in `sdk/pkg/analysis_server/test/analysis_abstract.dart` on line 126. You could try running the test in isolation (by adding a `@soloTest` annotation to the test method) to confirm that.

That said, the test looks like it's doing the right thing, and I would have expected the result of `resourceProvider.convertPath('/')` to be `'C:\'` on Windows.

**Comment by DanTup** [comment]
Thanks; I'll do some digging tomorrow!

**Comment by DanTup** [comment]
@bwilkerson You were spot on with `DartSdkManager`, there a bunch of tests just doing `new DartSdkManager('/'` so I'll work through making sure adding `resourceProvider.convertPath(` fixes them.

**Comment by DanTup** [comment]
Turns out there are lots of paths in tests! This is turning out to be quite a lot of work!

I'm down to:

Some of the remaining ones are complicated and I'll need some help (eg. plugins failing to load; or tests that I can fix but look like they might be intended to be doing something different with paths because they have posix/windows suffixes). I think it makes sense to try and get the ones that are fixed reviewed before going any further, so I'm pushing all my changes to a branch and I'm gonna test/fix up anything on Mac/Linux that got broken and then I'll push them for review.

**Comment by bwilkerson** [comment]
I'm always supportive of breaking work up into smaller incremental CLs, so getting what you have now reviewed is a good plan. If I'd known in advance how much was going to have to change, I would have suggested getting one file at a time to work, but there's no point in splitting it up now.

**Comment by DanTup** [comment]
Yeah, sorry about that - I also didn't realise it'd be so big :)

The last 5 changesets are one-per-file, so I could break them into separate pushes if you think this one is too big. Otherwise I'll avoid getting carried away with the rest and keep them smaller (I'm actually also a fan of small changes; but my workflow for this was a bit all over the place!).

I'll avoid working on any more until this is all done and merged because I think I'll need input on some of the others and I already have quite a few issues&PRs open between here and Flutter so I want to get some closed off before opening more!

**Comment by DanTup** [comment]
```text
00:59 +4273 -73: Some tests failed.
```

Down to 73 failures, hoping to clear more of these today.

**Comment by bwilkerson** [comment]
Fantastic progress! Thanks for doing this! I'm eager to see what the numbers look like after all the CL's you put out today.

**Comment by DanTup** [comment]
I think there should just be a handful once these all land. I emailed you about a few of them (inc. some that are "failing" because they're marked as failing but actually passing for me) and I think a few are due to #32277 and #32278. I'll get an updated list shortly.

**Comment by DanTup** [comment]
Ok, we're down 22 fails now (4324 passes).

It's the end of my week so I'll pick the remaining open review and your emails about the other tests on Monday and hopefully we'll soon be at parity with the other platforms 😃

**Comment by DanTup** [comment]
@bwilkerson Ok, it's hard to be exact because fixes are across branches, but I believe once all changes in Gerrit are dealt with, we're down to:

```text
CompletionDomainHandlerTest | test_import_uri_with_trailing [E]
CompletionDomainHandlerTest | test_partFile [E]
CompletionDomainHandlerTest | test_partFile2 [E]
```

Top one I believe is failing because of #32277; the bottom two I haven't figured out yet. They do have paths in them, but when I wrap `convertPathForImport` around them they still don't seem to return the expected results. I'll come back to these later today.

**Comment by DanTup** [comment]
Once we review/land https://dart-review.googlesource.com/c/sdk/+/43961 I believe all tests are good on Windows. I can do a final pull and run of them after that happens to be sure but then I think we should consider unskipping them in the status file.

**Comment by bwilkerson** [comment]
Agreed. The sooner we stop skipping them the less chance there is that they'll regress without our noticing.

**Comment by DanTup** [comment]
Using 063a244a7fca14e2e2e33cea25394141f4eea817 and dev31 SDK I'm seeing all tests passing on my Windows machine:

```text
01:17 +4376: All tests passed!
PS M:\Coding\Applications\Google\dart-sdk\sdk\pkg\analysis_server> git rev-parse HEAD
063a244a7fca14e2e2e33cea25394141f4eea817
```

@bwilkerson I've pushed https://dart-review.googlesource.com/c/sdk/+/44063 with a change to un-skip and kicked off the dry run.

Note: There are still some tests skipped analysis server tests in this file that may need reviewing, for ex:

> analysis_server/test/analysis/get_errors_test: Skip # runtime error, Issue #22180

That issue is marked as fixed but the test is still being skipped.

**Comment by DanTup** [comment]
There were some failures on the buildbots - looks like there are "benchmarks" that rely on `curl` so fail on Windows. We'll need to skip these again for now.

@bwilkerson PowerShell does have an invoke-webrequest (aliased to `curl`) that might allow these to run there. Let me know if you think it's worthwhile me taking a stab at them.

**Comment by DanTup** [comment]
Moving discussion to #32355 so we can close this one off :-)
