### ISSUE TITLE
VM with kernel times out on Windows running service/pause_on_start_then_step_test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#32225]
The test
runtime/observatory/tests/service/pause_on_start_then_step_test.dart
times out on dartk (dart vm with kernel)  configurations on Windows.

The test times out, taking more than a minute, on most runs and strong-mode runs.
When it doesn't time out, it takes about 15 seconds in normal mode and strong mode.  So there is
a flaky issue making the test take at least 4 times longer, probably hanging.  So instead of marking "Slow", I am marking as "Skip" in the status files, and filing this issue to find and fix the problem.

Example failures are on the build:
https://ci.chromium.org/p/dart/builds/b8954163518012478704

and the command to reproduce is
build/tools.py -mrelease runtime_kernel
out\ReleaseX64\dart.exe --preview_dart_2 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=.packages runtime\observatory\tests\service\pause_on_start_then_step_test.dart

**Comment by a-siva** [comment]
Checked the current test results page and found this test to be 'green' on the configurations for which it is run.
Closing the issue.
