### ISSUE TITLE
strong mode and mirrors

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32232]
We are currently skipping type checks on all functions that are invoked statically, because front-end guarantees that arguments are type checked on the caller's side. 

However mirrors violate this assumption. We need to revisit mirrors implementation to ensure that mirrors themselves type check static invocations.

/cc @rmacnak-google

**Comment by mraleph** [comment]
Here is a tandem issue https://github.com/dart-lang/sdk/issues/34194

**Comment by rmacnak-google** [comment]
Omitting type checks is an illegal optimization in the front-end. There is no closed world, and the front-end cannot know that arguments are checked on the caller's side. This is illegal both because of mirrors and because of hot reload.

**Comment by mraleph** [comment]
> There is no closed world, and the front-end cannot know that arguments are checked on the caller's side.

Front-end does not omit any type checks. Strictly speaking FE does not even insert any type checks for parameters - it leaves that to backends.

Backends of course need to optimize for the fast and common path - so VM does not generate any type checks for parameters of constructors and static functions because those are expected type to be checked statically. 

This implies that dynamic code paths should be type checked in full - we have needed functionality for that in the form of dynamic invocation forwarders. We just don't use it in mirrors. We should cover this with tests and then implement necessary logic in calls and setters.

> This is illegal both because of mirrors and because of hot reload.

That's what this bug is about - mirrors implementation needs to be adjusted for this optimization. The optimization itself is important for keeping common path fast, so mirrors will have to pay the price of checking as being on the infrequent path.

Similarly hot reload probably needs to reject reloads that violate strong mode. However hot reload is can actually be considered being on the common path - so we need to take that into account. 

If we think that heap safety violations are infrequent then we can just reject reloads that violate it. 

e.g. when changing in the type of the field we can scan instances and see if they all can be migrated without type violations. 

Alternatively we can disable entry point based optimizations when hot reload is enabled: but that would penalize debug mode performance on Flutter.

I thought we already have an issue for this, but apparently we don't - so I filed one https://github.com/dart-lang/sdk/issues/34201

[Flutter's debug mode actually became snappier with a switch to strong mode - because strong mode enables us to skip a lot of type checks compared to checked mode which was just checking everything]

**Comment by bkonyi** [comment]
Not yet. I'm going to talk to @rmacnak-google about what needs to be done here since I'm not terribly familiar with the mirrors implementation at this point.

**Comment by alexmarkov** [comment]
Test lib_2/mirrors/invocation_fuzz_test crashes and times out due to insufficient type checks when doing calls through mirrors.

**Comment by dgrove** [comment]
Is this on target for 2.1?

**Comment by a-siva** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/79081 is being reviewed.

**Comment by bkonyi** [comment]
I left this open since there was some tests that needed to be updated (see [here](https://dart-review.googlesource.com/c/sdk/+/79824)) which I didn't want to forget about. Now that change is up for review, I'll close this.
