### ISSUE TITLE
Add quick fix for "Import package:x show y"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32234]
Currently if you reference a function from a package that you haven't imported you get a fix to import it. It's be nice if there was an additional fix that imports with a `show` for just that function (there's already a fix to add new functions to existing imports, so this would make it easier to minimise what you're importing).

**Comment by zoechi** [comment]
I almost always use `show`. I think it makes code much easier to understand when it shows where certain identifiers come from. Especially UI code often has a lot of components/widget imports and imports for other stuff.
I'm in favor of making this more convenient.

**Comment by FMorschel** [comment]
Related to https://github.com/dart-lang/sdk/issues/55842.

**Comment by FMorschel** [comment]
> I think it makes code much easier to understand when it shows where certain identifiers come from.

I think then you can have some interest on:
- https://github.com/dart-lang/sdk/issues/56584 
- https://github.com/dart-lang/sdk/issues/56935
- https://github.com/dart-lang/sdk/issues/56350

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/396564
