### ISSUE TITLE
`implicit-casts: false` not recognized by Dart 2 analyzer?

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#32235]
Suppose I have this `analysis_options.yaml`:

```
analyzer:
  strong-mode:
    implicit-casts: false
```

and this Dart code:

```dart
main() {
  List<dynamic> strings = ["not", "ints"];
  List<int> numbers = strings; // <=== implicit downcast
  print(numbers);
}
```

Running the dartanalyzer under 1.24.3 I get, as I would expect:

```nocode
error • A value of type 'List' can't be assigned to a variable of type 'List<int>' at lib/strong_analysis.dart:24:27 • invalid_assignment
```

Running the Dart 2-dev.26 analyzer I get "**no issues found**".

If I run the Dart 2 analyzer with `--no-implicit-casts` then I get the expected error. It is as if the analysis options in the YAML file aren't being processed.

I'm feeling that there must be something silly that I'm missing, but I'm just not seeing it.

cc @kwalrath @matanlurey @stereotype441

**Comment by stereotype441** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Is this something that's likely to be effected by the work you're doing in the command-line analyzer?

**Comment by srawlins** [comment]
CC @devoncarew who addressed a similar bug recently, I think.

**Comment by DanTup** [comment]
I don't seem to be able to get this to work (in Flutter) even with `--no-implicit-casts` passed to the analyzer. Is there any workaround?

I've fixed a couple of crashes in flutter_tools recently where I'd made errors (for ex. `List<String> x = strings.followedBy(otherStrings)` should've been `Iterable` or had `.toList()`). It feels a bit dangerous now we crash at runtime if we can't see this in the editor.

**Comment by srawlins** [comment]
@DanTup It works for me with the flag:

```
$ cat e.dart 
main() {
  List<dynamic> strings = ["not", "ints"];
  List<int> numbers = strings; // <=== implicit downcast
  print(numbers);
}
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.68.0
$ dartanalyzer --no-implicit-casts e.dart 
Analyzing e.dart...
  error • A value of type 'List' can't be assigned to a variable of type 'List<int>' at e.dart:3:23 • invalid_assignment
1 error found.
```

What version of dartanalyzer are you running? Does your analysis_options have anything that would ignore certain errors?

**Comment by devoncarew** [comment]
@DanTup, can you re-verify? I do see issues reported on the analysis server code base, when adding:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

to the analysis options file.

**Comment by DanTup** [comment]
Ok, now I'm more confused :)

I tried again and turned it on in `flutter_tools` (by setting it in the `analysis_options.yaml` in the repo root, as the package one has an `include`). I got a load of new errors (so it works), yet the code from the top post here does not give any errors:

<img width="630" alt="screen shot 2018-07-18 at 7 38 34 am" src="https://user-images.githubusercontent.com/1078012/42864249-af25270a-8a5d-11e8-8811-1e3e7b5d5aab.png">

I tried it in a few places, including files that had other errors (like this one) and there are no complaints. Not sure if I've misunderstood something or it's not working correctly?

**Comment by DanTup** [comment]
If I run `dartanalyzer --no-implicit-casts` on the same file it's also not reported. So I don't think this is related to the setting being ignored, but rather that this code does not produce errors?

**Comment by DanTup** [comment]
Yeah, that had crossed my mind. You could argue that putting the type on the left looks deliberate and therefore it's working-as-intended. I'm not sure who can make that call though (apparently it worked the other way in v1).

Personally, I wouldn't have written the type there (which would avoid the issue), but in the Flutter codebase there's a lint enabled that requires type names. I guess it's the combination of these causing me grief. I don't know if the reasons for each make it a reasonable trade-off, though that's a bit of a tangent from this issue.

**Comment by stereotype441** [comment]
@srawlins are you working on code related to this?

**Comment by srawlins** [comment]
@stereotype441 no I am not.
