### ISSUE TITLE
Returning a `FutureOr` in an asynchronous function fails

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32233]
Consider the following program:
```dart
import 'dart:async';
FutureOr<int> foo() => 42;
Future<num> bar() async => foo();
main() => bar();
```
The analyzer in strong mode responds as follows (when the program is stored in `n020.dart`):
```
> dartanalyzer --version
dartanalyzer version 2.0.0-dev.26.0
> dartanalyzer --strong n020.dart
Analyzing n020.dart...
  error • The return type 'Future<FutureOr<int>>' isn't a 'Future<num>', as defined by the method 'bar' at n020.dart:5:28 • return_of_invalid_type
1 error found.
```
Presumably, this means that the returned expression in `bar` is checked in a manner which does not precisely correspond to the _flatten_ function (from the language specification, sections Function Expressions and Return):
```
If \code{$T =$ FutureOr<$S$>} then $flatten(T) = S$.
...
It is a static type warning if the body of $f$ is marked \ASYNC{} and
the type \code{Future<$flatten(T)$>} (\ref{functionExpressions}) may not
be assigned to the declared return type of $f$.
```
But `Future<int>` may be assigned to `Future<num>` so the program should be accepted. Note that analysis of the same program succeeds with `dartanalyzer --preview-dart-2`.

**Comment by leafpetersen** [comment]
Probably related: https://github.com/dart-lang/sdk/issues/30638
