### ISSUE TITLE
Prefix names are lexically scoped.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32248]
The analyzer is treating prefix names as special in some cases and lexically scoped in other cases.
It should treat the prefix name as lexically scoped in all cases, so:
```dart
import "dart:core" as prefix;
class C {
  var prefix = 42;
  prefix.int get foo => this.prefix;  // prefix in prefix.int should not refer to the import.
}
```
See #32200 for more detail.

**Comment by eernstg** [comment]
Note that #38373 reports another situation where the analyzer resolves a name in a type as a prefix, even though the same name is declared in nearer a lexical scope (also as an instance member).

**Comment by srawlins** [comment]
The analyzer now reports this error:

> error • The prefix 'prefix' can't be used here because it is shadowed by a local declaration. • a.dart:4:3 • prefix_shadowed_by_local_declaration

So I think this has been fixed?

**Comment by eernstg** [comment]
I agree.

@scheglov, I'll close this issue&mdash;please reopen it if you think there are any remaining issues with lexical scoping and import prefixes.
