### ISSUE TITLE
dart2js: Implementing `call` method on a JS interop class adds `$isFunction: 1` to common Interceptor

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/sdk#32249]
Which breaks all the descendant interceptors, like `JSBool`.

Example declaration:

```dart
@JS()
@anonymous
abstract class DatabaseService {
  external Database call([App app]);
}
```

Also for some reason for the above declaration I get `$isDatabaseService: 1` also declared on `Interceptor` while interceptor for this class extends from `JavaScriptObject`. It would probably make more sense to put `$isDatabaseService: 1` either on actual interceptor with the same name or at least `JavaScriptObject`?

**Comment by rakudrama** [comment]
Thanks for the report.

This is the same bug as https://github.com/dart-lang/sdk/issues/26838 which has been fixed by putting `$isDatabaseService: 1` on the interceptor for `JavaScriptObject`.

**Comment by pulyaevskiy** [comment]
Thanks, this is great news! I assume it’s going to be part of next 2.0.0-dev release?
