### ISSUE TITLE
analyzer warning related to missing flutter assets and asset responsiveness

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32250]
When referencing a flutter asset in a pubspec, say `assets/images/heart.png`, the analyzer will complain if the asset doesn't exist on disk.

```
assets/images/heart.png
assets/images/1.5x/heart.png
assets/images/2.0x/heart.png
```
 The analyzer currently doesn't know about responsive assets, so if the first file on disk doesn't exist, it would still complain, even if the flutter framework at runtime would load either `1.5x/heart.png` or `2.0x/heart.png`.

Is missing the main image - `assets/images/heart.png` - but having a size specific sub-image - an error we should complain about, or something expected and normal? In order words, if we can locate any size for the specified asset, we should consider it to exist (and be well-formed)?

/cc @bwilkerson @xster @szakarias @alardizabal

**Comment by devoncarew** [comment]
@szakarias, can you comment? My guess is that we should not create a warning about an entry in the pubspec assets section if the explicit file doesn't exist (`assets/images/heart.png`), as long as one of the variants does exist?

**Comment by devoncarew** [comment]
(also /cc'ing @mit-mit and @mravn-google, as they're likely better informed about the asset system than I am)

**Comment by szakarias** [comment]
Yes, that is correct. The main asset entry (the one not in a resolution-specific subfolder) does not need to correspond to a real file if we have at least one variant.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/45841
