### ISSUE TITLE
Add library to allow easier Java arithmetic conversion

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/sdk#32254]
I am trying to convert a program from Java to Dart. I am having trouble because of the rounding differences between Java and Dart.
e.g.
### Dart

    stdout.write("out="+(8/12).toString());
    out=0.6666666666666666
### Java

    System.out.println("out="+8/12);
    out=0

It looks like Dart is treating 8 as a double, whereas Java treats 8 as an int and 8.0 as a double ?

Perhaps implementing a rounding mode as available in Java would allow for easier code conversion ?
[Java Rounding Mode](https://docs.oracle.com/javase/7/docs/api/java/math/RoundingMode.html)

**Comment by Rockvole** [comment]
I just checked, and :
### Java
    System.out.println("out="+8.0/12.0);
    out=0.6666666666666666

**Comment by Rockvole** [comment]
### Dart
    int s=8;
    int t=12;
    stdout.write("out="+(s/t).toString());
    out=0.6666666666666666

**Comment by mraleph** [comment]
If you would an integer division like in Java you need to use `a ~/ b` operator.
