### ISSUE TITLE
A consistent story for enabling asserts in a checked-mode-less Dart2 world

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32255]
* dart (VM) has --enable-assert – Good!
* dart2js: advertises --checked as doing runtime checks + asserts. No explicit --enable-asserts option (that I see)
* dartdevc: ???

I'd be good if we have the alternative consistent and advertised soonish, right?

I'd also argue for a shorter "--asserts" flag – or even just leaving "--checked" around as the flag for just enabling asserts.

**Comment by kwalrath** [comment]
I like `--asserts`, although I suppose `--enable-assert` is clearer.

**Comment by rakudrama** [comment]
dart2js has `--enable-asserts`, just like the VM (also `--enable-asserts`, ending in `s`).
It is just not advertised.

**Comment by kevmoo** [comment]
> dart2js has --enable-asserts, just like the VM (also --enable-asserts, ending in s).
It is just not advertised.

Wonder if we should start advertising it 😄

**Comment by dgrove** [comment]
And DDC always has asserts enabled. So this is a doc issue.

**Comment by kwalrath** [comment]
This is covered in https://www.dartlang.org/guides/language/language-tour#assert and https://webdev-dartlang-org-dev.firebaseapp.com/tools/dart2js.
