### ISSUE TITLE
Analysis server rejects file paths in setAnalysisRoots (though docs suggest this is allowed)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32256]
In the docs it suggests that file paths are valid in setAnalysisRoots:

> If an included path represents a file, then server will look in the directory containing the file for a pubspec.yaml file. If none is found, then the parents of the directory will be searched until such a file is found or the root of the file system is reached. If such a file is found, it will be used to resolve package: URI’s within the file.

However it seems to reject these:

```text
[07:46:51]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"excluded":[],"included":["c:\\Users\\danny\\Desktop\\test.dart"]}}
[07:46:55]: <== {"id":"2","error":{"code":"UNSUPPORTED_FEATURE","message":"c:\\Users\\danny\\Desktop\\test.dart is not a folder. Only support for folder analysis is implemented currently."}}
```

**Comment by bwilkerson** [comment]
Yes, that is the intended behavior, and the lack of support is a bug. We just haven't yet had a client that needed it enough to raise the priority.

**Comment by DanTup** [comment]
Closing this because I don't believe there was any demand for this outside of VS Code, which now supports loose files through the LSP server.
