### ISSUE TITLE
Override completions don't appear if @override is already present

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32259]
@pq 

Given this code:

```dart
class Danny {
  method() {}
  int age;
}

class Danny2 extends Danny {
  meth
}
```

If I invoke completion after the word `meth` then I get an override complete. However if I put the `@override` in first, so code looks like this:

```dart
class Danny {
  method() {}
  int age;
}

class Danny2 extends Danny {
  @override
  meth
}
```

When I invoke completion after the word `meth` I don't get any completion items.

**Comment by pq** [comment]
Thanks!

cc @bwilkerson

**Comment by pq** [comment]
Thanks!

cc @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/43140
