### ISSUE TITLE
Override completions have bad selectionOffsets

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32260]
@pq 

When completing method overrides here:

```dart
class Danny {
  method() {}
  int age;
}

class Danny2 extends Danny {
  meth
}
```

I think something may be wonky with the `selectionOffset` that's coming back:

![selection](https://user-images.githubusercontent.com/1078012/36471526-a429eea2-16e6-11e8-8ddc-5715af741d0a.png)

```js
{
	"kind": "OVERRIDE",
	"relevance": 2000,
	"completion": "@override\n  method() {\n    // TODO: implement method\n    return super.method();\n  }",
	"displayText": "method() { … }",
	"selectionOffset": 59,
	"selectionLength": 22
	// ...
}
```

```text
@override\n  method() {\n    // TODO: implement method\n    return super.method();\n  }
0123456789 0123456789012 345678901234567890123456789012 3456789
```

I think if you consider "\n" as two chars, maybe this lines up - however I don't think it should be, it's just a single character to the code that's being executed (after JSON parsing).

**Comment by pq** [comment]
cc @bwilkerson

**Comment by pq** [comment]
Thanks for the report Danny!

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/43140
