### ISSUE TITLE
"Convert `part of` to uri" assist seems to return bogus paths on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32278]
While trying to fix `test_convertPartOfToUri_file_nonSibling` in `assist_test.dart` for Windows I noticed that the behaviour seems wonky.

## lib/nfoo.dart
```dart
library nfoo;

part "src/bar.dart";
```

## lib/src/bar.dart
```dart
part of nfoo;
```

Invoking the `Convert to use a URI` fix in `bar.dart` changes the source to this:

```dart
part of '..\nfoo.dart';
```

Which gives:

> Expected this library to be part of 'file:///c:/Users/danny/Desktop/DartSample/lib/nfoo.dart', not 'file:///c:/Users/danny/Desktop/DartSample/lib/src/..%0Afoo.dart'.

I think the slash should be a forwards slash, even on Windows? That seems to be what works in my testing, and is also what the test comes up with once I've fixed its other path issues (I tried just escaping it with another slash but that also resulted in errors).

**Comment by DanTup** [comment]
cc @bwilkerson @scheglov

**Comment by lrhn** [comment]
It should definitely be a forward slash. Dart imports are URI references, not system paths. All path separators must be `/`.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/43483
