### ISSUE TITLE
Delete pkg/typed_mock

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32271]
Used by anyone?

CC @devoncarew @scheglov

**Comment by scheglov** [comment]
In Analyzer and Analysis Server we migrated to mockito, and this is probably what users should do too.
So, yes, we can remove typed_mock now.

**Comment by kevmoo** [comment]
Happy to approve the CL

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/42862
