### ISSUE TITLE
Analysis server doesn't complete absolute import paths on Windows 

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32277]
Both of these imports are valid on Windows:

```dart
import "file:///C:/Users/danny/Desktop/DartSample/lib/thing.dart";
import "/C:/Users/danny/Desktop/DartSample/lib/thing.dart";
```

However if I trim the end off the filename, I don't get completion for these. Spotted while trying to fix `CompletionDomainHandlerTest` tests on Windows. For example, if I change `test_import_uri_with_trailing` to:

```dart
@soloTest
test_import_uri_with_trailing() {
  final filePath = '/project/bin/testA.dart';
  final incompleteImportText = convertPathForImport('/project/bin/t');
  newFile(filePath, content: 'library libA;');
  addTestFile('''
    import "$incompleteImportText^.dart";
    main() {}''');
  return getSuggestions().then((_) {
    expect(replacementOffset,
        equals(completionOffset - incompleteImportText.length));
    expect(replacementLength, equals(5 + incompleteImportText.length));
    assertHasResult(
        CompletionSuggestionKind.IMPORT, convertPathForImport(filePath));
    assertNoResult('test');
  });
}
```

It fails with:

```text
  expected "/C:/project/bin/testA.dart" but found
   [dart:, dart:async, dart:collection, dart:convert, dart:core, dart:html, dart:math, package:]
```

(cc @bwilkerson)

**Comment by bwilkerson** [comment]
I did a little digging, and I'm fairly confident that the problem is in `_UriSuggestionBuilder._addFileSuggestions`. It appears to be treating the content of the URI as a valid file path without first converting it from URI format to platform format. (See line 152, where `parentUri` is used.)

**Comment by DanTup** [comment]
@bwilkerson Aha, thanks! I have a fix that I'm slightly unsure of, I'll raise a review and put some notes on it for your input.

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/43961

**Comment by DanTup** [comment]
@bwilkerson I've confirmed this is working running from source locally on Windows so I'm closing - do we need to set labels/milestones etc.? (I'm not sure if they're used to produce release notes/whatever).

**Comment by bwilkerson** [comment]
No, as far as I know they're only used for planning purposes.
