### ISSUE TITLE
Meld --strong --reify-generic-functions into --preview-dart-2

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32296]
Meld --strong --reify-generic-functions into --preview-dart-2 so that we have a single opt in option to run dart 2.0 code in the command line VM

**Comment by a-siva** [comment]
This has been done, closing issue.

**Comment by zoechi** [comment]
What effect does `--strong` have that is not included in `--preview-dart-2`
What does `--preview-dart-2` contain already?
Is there a doc that provides some insight?

**Comment by a-siva** [comment]
--preview-dart-2 is the one single flag that supports Dart 2.0 semantics, please see [](https://www.dartlang.org/dart-2#strong-mode-and-static-typing) for more details.

All the other flags are internal VM development/debugging flags and are not intended for use by end users.
