### ISSUE TITLE
Categorize `dart:*` libraries on api.dartlang.org

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32297]
The current layout is flat. It's not clear which APIs are usable where.

https://api.dartlang.org/be/154136/index.html

We should group these:

- Core
  - *everything not called out below*
- VM
  - io
  - cli
- Web
  - html
  - indexed_db
  - js
  - js_util
  - svg
  - web_*

Flutter does a good job here: https://docs.flutter.io/

**Comment by kevmoo** [comment]
@jcollins-g – how hard is this to setup?

CC @whesse

**Comment by jcollins-g** [comment]
There are command line flags to organize things in packages, but there is no subpackage categorization, which is what you're asking for here.

**Comment by kevmoo** [comment]
@jcollins-g – does this become a feature request for dartdoc then?

**Comment by jcollins-g** [comment]
Yes.

**Comment by kevmoo** [comment]
Blocked by https://github.com/dart-lang/dartdoc/issues/1610

**Comment by devoncarew** [comment]
Here is how flutter does it: https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L119

**Comment by jcollins-g** [comment]
Talked offline, but to recap, flutter depends on categories aligning to packages.  Within a package (e.g. the SDK), that's a new feature.

**Comment by dgrove** [comment]
@jcollins-g Can you please move to a current milestone (Dart2 beta3/beta4/stable)?

**Comment by jcollins-g** [comment]
I believe @kevmoo already did this.

**Comment by kevmoo** [comment]
Yup...

**Comment by kevmoo** [comment]
Dartdoc fix landed in https://github.com/dart-lang/dartdoc/commit/628acf6880d54808a7fb9df699e0ebdfd487d04e - which is in 0.18.0

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/f386b367a54fd63a3bf77b06c214792f1d97fc76
