### ISSUE TITLE
Disable `dart:isolate` in DDC

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#32293]
We're no longer supporting this on the web.  We should:

- Disallow importing (by milestone 2.0-beta1)
- Eventually rip out logic (it's tied up with async, so this will require surgery)

**Comment by jmesserly** [comment]
from a `git grep 'dart:isolate' sdk/lib/ pkg/dev_compiler/` it doesn't look like dart:isolate is imported by dart:async or its patch file. Maybe we were thinking of dart:_isolate_helper. I also commented in another issue (https://github.com/dart-lang/sdk/issues/30540#issuecomment-368163798) that it does seem we have a dependency on dart:isolate from dart:io and dart:html

**Comment by jmesserly** [comment]
Update: it seems like we need to keep some of dart:isolate around, at least for now. Our test helpers for async tests (unittest and async_helper) create a dummy ReceivePort to keep the Dart VM from exiting prematurely. I don't know if there are other ways to fix that (start a timeout timer maybe?) ... for the short term I'm seeing if I can make most runtime access throw, similar to dart:io. Not a great place to end up, but it does help disable most of the functionality.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/45754 -- disables support for most of the functionality. The dummy ReceivePort class is kept around.

**Comment by jmesserly** [comment]
closing this out based on https://dart.googlesource.com/sdk/+/c9e9c1d8e9a187ce3a47adcc1a929479796b97b5
