### ISSUE TITLE
Remove 'Other resources' section from `dart:html` docs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32304]
All of these are old/broken - see https://api.dartlang.org/be/154150/dart-html/dart-html-library.html

https://github.com/dart-lang/sdk/blob/b3056d8083ccc50a5bb918a3e0e6dadb817dd9ca/tools/dom/templates/html/dart2js/html_dart2js.darttemplate#L19

CC @kwalrath

**Comment by vsmenon** [comment]
@kevmoo - what's the issue here?  The links under other resources seem to work.  If there is updated text, can you provide it?

**Comment by terrylucas** [comment]
ping?

**Comment by kevmoo** [comment]
This content at the top of `dart:html` under `Other resources` is all outdated. Just delete it.

![screen shot 2018-06-15 at 11 19 31 am](https://user-images.githubusercontent.com/17034/41483452-04713ab2-708e-11e8-945b-ecac466974c3.png)
