### ISSUE TITLE
Unexpected: `argument type '(Image) → Null' can't be assigned to the parameter type '(Image) → void'` error

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32308]
I'm seeing this in my Flutter project but suspect it's not flutter specific.

Given this repo at this revision:

https://github.com/DanTup/Flip-8/commit/5a86065a4196565149d7170f4e80b3034b0769bd

I get the following error reported:

```
file: 'file:///Users/danny/Dev/Flip-8/lib/main.dart'
severity: 'Error'
message: 'The argument type '(Image) → Null' can't be assigned to the parameter type '(Image) → void'.'
at: '37,23'
source: 'dart'
code: 'argument_type_not_assignable'
```

The code in question looks like this (the function returns `void` as far as I can tell?):

```dart
chip8 = new Chip8((Image newFrame) {
  setState(() => currentFrame = newFrame);
});
```

The constructor looks like this:

```dart

  Chip8(void Function(Image) draw) {
    _sendImage = draw;
  // ...
}
```

Versions:

```text
Dannys-MacBook:Flip-8 danny$ flutter --version
Flutter 0.1.6-pre.3 • channel master • https://github.com/DanTup/flutter.git
Framework • revision 7f03b9e41b (2 days ago) • 2018-02-23 12:49:57 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

Flutter analyze reports the error as well as my IDE:

```text
Dannys-MacBook:Flip-8 danny$ flutter analyze
Analyzing /Users/danny/Dev/Flip-8...
  error • The argument type '(Image) → Null' can't be assigned to the parameter type '(Image) → void' at lib/main.dart:37:23 • argument_type_not_assignable
  error • 'UnimplementedError' isn't a function at lib/src/chip8.dart:106:11 • invocation_of_non_function
  hint • The value of the field '_sendImage' isn't used at lib/src/chip8.dart:28:24 • unused_field
3 issues found.
(Ran in 6.4s)
```

Some additional weird things:

1. If I move the Chip8 class into the same file (main.dart) the error goes away
2. If I change the constructor signature to have `Null` like `Chip8(Null Function(Image) draw)` I get a slightly different error: `The argument type '(Image) → Null (/Users/danny/Dev/Flip-8/lib/main.dart)' can't be assigned to the parameter type '(Image) → Null (/Users/danny/Dev/Flip-8/lib/src/chip8.dart)'.`.

If I try to run the flutter app I get a similar error:

```
compiler message: lib/main.dart:37:23: Error: A value of type '(#lib1::Image) → dart.core::Null' can't be assigned to a variable of type '(dart.ui::Image) → void'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(dart.ui::Image) → void'.
compiler message:     chip8 = new Chip8((Image newFrame) {
compiler message:                       ^
```

I'm sure this is something silly, but I can't figure out what?

**Comment by mraleph** [comment]
The `Image` type [here](https://github.com/DanTup/Flip-8/blob/5a86065a4196565149d7170f4e80b3034b0769bd/lib/src/chip8.dart#L30) refers to `dart:ui.Image`. The `Image` type [here](https://github.com/DanTup/Flip-8/blob/5a86065a4196565149d7170f4e80b3034b0769bd/lib/main.dart#L37), refers to `Image` widget from [this file](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/image.dart#L110) (you get it where export chain from `package:flutter/material.dart`.

So the error seems to be valid, just very hard to grok.

**Comment by mraleph** [comment]
/cc @peter-ahe-google @kmillikin 

In the error above CFE uses `lib1::Image`, this is impossible to figure out because `lib1` is not that something a user can understand. 

The error should either explain that `lib1` is `package:flutter/material.dart` or in other way indicate where that type is coming from.

**Comment by mraleph** [comment]
Filed separate issue for CFE #32309 and analyzer #32310. Closing this one.
