### ISSUE TITLE
analyzer allows access to private libraries

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#32300]
```dart
import 'dart:_runtime' show dcall;
main() {
  dcall(1, 2);
}
```
this fails at runtime (because DDC doesn't expect you to be able to import that library from user code!) but it's not a compile error. DDK does the right thing.

**Comment by jmesserly** [comment]
I think(?) this is a regression in Analyzer, and it should still emit an error like Kernel does:
```
test.dart:1:1: Error: Can't access platform private library.
import 'dart:_runtime' show dcall;
^
```
... but we could add an extra check in DDC.

**Comment by dnfield** [comment]
I have what I believe is the same issue.

in `library.dart`:

```
library library_saple;

class Foo {
  final int bar;
  const Foo(this.bar);
}

class _FooPrivate {
  final int bar2;
  const _FooPrivate(this.bar2);
}
```

in `main.dart`:

```
import 'library.dart' as lib;

void main() {
  var foo1 = new lib.Foo(1); // OK
  var foo2 = new lib._FooPrivate(2); // shouldn't be ok
}
```

the `var foo2` triggers a warning in analyzer, but seems like it should trigger an error.  It results in an error at runtime.

**Comment by dnfield** [comment]
Might've spoken too soon on the warning - when I use a newer version of the analyzer/SDK, it does give an error.  However, Dart-Code still shows me a list, which still is likely rooted in some bug around this from the Analyzer...  Still digging.

**Comment by srawlins** [comment]
The original example now yields the following error from analyzer:

> error • Target of URI doesn't exist: 'dart:_runtime'. • 32300.dart:1:8 • uri_does_not_exist

@dnfield I think your case is a different issue; if you are still seeing this, please open a new issue.

**Comment by dnfield** [comment]
Quick experiment suggests this is no longer an issue.

**Comment by dnfield** [comment]
(the issue I was seeing I mean)
