### ISSUE TITLE
No naviagation data for EnumValue.toString()

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#32316]
```
enum Foo {Bar}
var  a = Foo.Bar.toString();
```
Analysis Server doesn't return navigation data for `toString()` method. Reproducible with SDK 2.0.0-dev.30.0.

With previous SDK versions, it jumped to `Object.toString()` as expected.

**Comment by srawlins** [comment]
Still the case :(

**Comment by srawlins** [comment]
This seems to be working again. Works in IntelliJ with recent Dart.
