### ISSUE TITLE
dart2js strong mode work items

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32333]
- [x] Strong mode sdk .dill file
- [x] https://github.com/dart-lang/sdk/issues/31718 Generic methods 
- [x] https://github.com/dart-lang/sdk/issues/32331 Generalized void
- [x] https://github.com/dart-lang/sdk/issues/32330 FutureOr
- [x] https://github.com/dart-lang/sdk/issues/32332 Generate TypeError for implicit downcasts
- [ ] https://github.com/dart-lang/sdk/issues/33037 Type bounds and type literal related tasks

**Comment by sigmundch** [comment]
(I've removed the milestone from this meta issue because each individual bug is already marked as part of the milestone)
