### ISSUE TITLE
dart2js strong: Implement full void

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32331]
`void` is allowed in any type position.

- [ ] Update runtime type representation to allow `void` in a general position
- [ ] Update type emitter to generate new prepresentation
- [ ] Update subtype rules to handle void in these positions

**Comment by sigmundch** [comment]
I believe this bug will be fixed once https://dart-review.googlesource.com/c/sdk/+/48426 lands

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/48426 has landed. Closing.
