### ISSUE TITLE
Experimenting with GLTF - Error building release dart2js

### ISSUE THREAD

**Issue by JeromePuttemans** [dart-lang/sdk#32334]
Hello, 

I'm learning to build a webgl project to use GLTF, this build correctly in debug with DDC but not in release with dart2js

Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "windows_x64"

dependencies:
  gltf:
    git: git://github.com/KhronosGroup/glTF-Validator.git

factory Gltf.fromMap(Map<String, Object> map, Context context) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Build error:
Transform Dart2JS on webgl|web/gltf/main.dart threw error: Assertion failure: Runtime type information not available for type_variable_local(toSafeList.T) in (parameter(fromMap#map), parameter(fromMap#context), BoxLocal(_box_0), ..., variable(fromMap#extensionsUsed), variable(fromMap#extensionsRequired)) for factory_constructor(Gltf#fromMap).
package:compiler_unsupported/src/diagnostics/invariant.dart 55            failedAt
package:compiler_unsupported/src/ssa/locals_handler.dart 328              LocalsHandler.readLocal
package:compiler_unsupported/src/ssa/builder.dart 1922                    SsaAstGraphBuilder.visitFunctionExpression.<fn>
package:compiler_unsupported/src/elements/common.dart 388                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField.fieldFilter
package:compiler_unsupported/src/elements/common.dart 356                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember.<fn>
package:front_end/src/fasta/util/link_implementation.dart 124             LinkEntry.forEach
package:compiler_unsupported/src/elements/modelx.dart 2985                ClassElementX.forEachLocalMember
package:compiler_unsupported/src/elements/common.dart 356                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember
package:compiler_unsupported/src/elements/common.dart 392                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField
package:compiler_unsupported/src/universe/codegen_world_builder.dart 605  ElementCodegenWorldBuilderImpl.forEachInstanceField
package:compiler_unsupported/src/ssa/builder.dart 1919                    SsaAstGraphBuilder.visitFunctionExpression
package:compiler_unsupported/src/tree/nodes.dart 1209                     FunctionExpression.accept
package:compiler_unsupported/src/ssa/builder.dart 1624                    SsaAstGraphBuilder.visit
package:compiler_unsupported/src/ssa/builder.dart 1933                    SsaAstGraphBuilder.visitFunctionDeclaration
package:compiler_unsupported/src/tree/nodes.dart 1127                     FunctionDeclaration.accept
package:compiler_unsupported/src/ssa/builder.dart 1624                    SsaAstGraphBuilder.visit
package:compiler_unsupported/src/ssa/builder.dart 1670                    SsaAstGraphBuilder.visitBlock
package:compiler_unsupported/src/tree/nodes.dart 980                      Block.accept
package:compiler_unsupported/src/ssa/builder.dart 769                     SsaAstGraphBuilder.buildMethod
package:compiler_unsupported/src/ssa/builder.dart 319                     SsaAstGraphBuilder.build
package:compiler_unsupported/src/ssa/builder.dart 114                     SsaAstBuilder.build.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1156                       CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/ssa/builder.dart 105                     SsaAstBuilder.build.<fn>
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/ssa/builder.dart 99                      SsaAstBuilder.build
package:compiler_unsupported/src/ssa/ssa.dart 91                          SsaBuilderTask.build
package:compiler_unsupported/src/ssa/ssa.dart 43                          SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 846              JavaScriptBackend.codegen
package:compiler_unsupported/src/js_backend/element_strategy.dart 176     ElementCodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 784                        Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 784                        Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 782                        Compiler.emptyQueue.<fn>.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1156                       CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 780                        Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/enqueue.dart 511                         EnqueuerStrategy.processWorkItem
package:compiler_unsupported/src/js_backend/enqueuer.dart 224             CodegenEnqueuer.forEach
package:compiler_unsupported/src/compiler.dart 776                        Compiler.emptyQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 775                        Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 797                        Compiler.processQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 794                        Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 640                        Compiler.compileLoadedLibraries.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 534                        Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 488                        Compiler.runInternal
===== asynchronous gap ===========================
package:compiler_unsupported/src/compiler.dart 313                        Compiler.run.<fn>.<fn>
dart:async                                                                new Future.sync
package:compiler_unsupported/src/compiler.dart 313                        Compiler.run.<fn>
package:compiler_unsupported/src/common/tasks.dart 178                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 310                        Compiler.run
package:compiler_unsupported/src/apiimpl.dart 265                         CompilerImpl.run.<fn>.<fn>

**Comment by lexaknyazev** [comment]
Hi, I'm the author of that package. Feel free to open an issue in its [repo](https://github.com/KhronosGroup/glTF-Validator/issues).
Development branch builds fine with dart2js though.

**Comment by JeromePuttemans** [comment]
well, after some research, I found the problem cames from me using some mirrors elements. The error message is really unclear in explaining the real problem...

**Comment by JeromePuttemans** [comment]
Hmm, after removing all aspects of mirrors in my project, I still have the problem, i definitively doesn't understand the real problem.

You're right, gltf project build correctly both in release with dartdevc and  build with dart2j !

I'll post a new issue to discuss thos in the right repo : https://github.com/KhronosGroup/glTF-Validator/issues/71
thx
