### ISSUE TITLE
dart2js strong: runtime type checks

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32332]
- [x] Implicit downcasts should generate TypeError at runtime (currently they generate CastError)
- [ ] In 'checked' mode (or 'compliance' mode), the function entry is the dynamic invocation entry. Function entry types should be checked unless type analysis can prove the types are satisfied. Internal type assertions should not be checked - there will be implicit downcasts if a check is needed.

**Comment by sigmundch** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/48459 has the last changes we need to fix this issue.
