### ISSUE TITLE
dart2js strong: Implement subtyping rules for FutureOr<T>

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32330]
The Dart 1 trick of replacing `FutureOr<T>` with `dynamic` does not work with Dart 2 subtyping.

- Static (inference, codegen)
  - [ ] Global type inference should initially be fixed to trace FutureOr<T> as a Union type mask of Future and a best approximation to T.
  - [x] Generate checks as calls to entry points that handle FutureOr correctly (either use the isSubtypeOfRuntimeType entry, or specialized entries for common cases)
  - [ ] Fix type propagation (e.g. receiver strengthening)
  - [ ] Fix any optimizations, e.g. `1 is FutureOr<num>` --> `true`

- Dynamic
  - [x] Generate representation for `FutureOr<T>`, `List<FutureOr<int>>` etc
  - [x] Create specialized js_runtime entry points is needed.
  - [x] Make subtype rule work for `FutureOr<T>` (including edge cases. e.g. `FutureOr<Object>` is a Top type)

**Comment by sigmundch** [comment]
I believe all but the global inference narrowing are done. And our current handling of FutureOr during global inference is sound, so we don't need to do anything further to get this out the door.

@johnniwinther - is that correct? If so, let's close this bug :)

**Comment by johnniwinther** [comment]
The inference part is sound so let's close this bug but open a new specifically for the inference improvements.

**Comment by sigmundch** [comment]
Awesome - tracking improvements here https://github.com/dart-lang/sdk/issues/32691
