### ISSUE TITLE
error: A value of type 'List<Type>' can't be assigned to a variable of type 'Iterable<Type>'. 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32335]
I get lots of these for classes generated by `built_value`

![image](https://user-images.githubusercontent.com/405837/36717754-99dbbd28-1b9f-11e8-9dac-24bc765c7666.png)

```dart
class _$GroupMemberSerializer implements StructuredSerializer<GroupMember> {
  @override
  final Iterable<Type> types = const [GroupMember, _$GroupMember];
```

I don't know if newer versions of `built_value` generate different code.
I can't update to latest because of an incompatible dependency,
but I think above code shouldn't cause an error.

**Comment by zoechi** [comment]
Both `GroupMember` and `_$GroupMember` are classes and navigating to them works fine, so it shouldn't be an issue with resolving the names and the error message indicates that a `List<Type>` was derived.

**Comment by zoechi** [comment]
This one seems related

```
error: The type 'List<StreamSubscription>' used in the 'for' loop must implement Iterable. 
```

![image](https://user-images.githubusercontent.com/405837/36718059-c062b4fa-1ba0-11e8-8137-0dd1501c05db.png)

**Comment by zoechi** [comment]
When I switch back to Dart `2.0.0-dev.24.0` these errors disappear.
Seems to start with `2.0.0-dev.26.0`

**Comment by zoechi** [comment]
There are tons of other errors that start showing up at `2.0.0-dev.26.0`

I get all of these errors only in IntelliJ Dart Analysis view.
When I run `dartanalyzer lib` (or `dartanalyzer --preview-dart2 lib`, `dartanalyzer --preview-dart2 ---strong lib` ) from command line
```
(rxdart_2) $ dartanalyzer --preview-dart-2 --strong lib
Analyzing lib...
No issues found!
```

**Comment by mraleph** [comment]
@stereotype441 do you know who can take a look at this?

**Comment by stereotype441** [comment]
Since it's only happening with IntelliJ's Dart Analysis view it's probably an analysis server issue.  Both of the bogus error messages sound like an issue with the analysis server failing to correctly interpret `List` as referring to the List in the standard library.  I wonder if perhaps since these are generated files, the analysis server is using an unusual URI to refer to them, which is making it think that `List` refers to a class in some other library rather than the standard library.

I believe @bwilkerson or @scheglov would be in the best position to investigate further.

**Comment by zoechi** [comment]
I'm not seeing this anymore (2.0.0-dev.35)

**Comment by mraleph** [comment]
@devoncarew can you confirm that this was fixed? 

I am closing it tentatively - but if it is just _accidentally fixed_ then please reopen.

**Comment by mcjons** [comment]
![image](https://user-images.githubusercontent.com/50258714/57174770-be44d100-6e54-11e9-94f2-c1688a1a28d2.png)

Please anyone can help me with this code. Im getting error type 'String' is not a subtype of type 'double'. Please see below code

List<String> getMonthlyAmountElement(){

  List<String> _amount= List();
  double _total;
  double _donationAmount=donationAmount;
   
  for (var i = 0; i <= 12; i++) {
        if (i > 0) {
          _total = (_donationAmount * .30) + _donationAmount;
          _donationAmount = _total;
       		_amount.add(_total.toString());
        }
            else {
              _total= _donationAmount;
          }
     }
   
  return _amount;
}

 getMonthlyAmount(){
  var monthlyAmount1= getMonthlyAmountElement();
  var listView = ListView.builder(
    itemCount: 12,
    itemBuilder: (context, index){
      return ListTile(
        leading: Icon(Icons.account_circle),
        title: Text( 'Sample'),
        
      );
    }
  );
  return listView;
}

**Comment by mcjons** [comment]
> ![image](https://user-images.githubusercontent.com/50258714/57174770-be44d100-6e54-11e9-94f2-c1688a1a28d2.png)
> 
> Please anyone can help me with this code. Im getting error type 'String' is not a subtype of type 'double'. Please see below code
> 
> List getMonthlyAmountElement(){
> 
> List _amount= List();
> double _total;
> double _donationAmount=donationAmount;
> 
> for (var i = 0; i <= 12; i++) {
> if (i > 0) {
> _total = (_donationAmount * .30) + _donationAmount;
> _donationAmount = _total;
> _amount.add(_total.toString());
> }
> else {
> _total= _donationAmount;
> }
> }
> 
> return _amount;
> }
> 
> getMonthlyAmount(){
> var monthlyAmount1= getMonthlyAmountElement();
> var listView = ListView.builder(
> itemCount: 12,
> itemBuilder: (context, index){
> return ListTile(
> leading: Icon(Icons.account_circle),
> title: Text( 'Sample'),
> 
> ```
>   );
> }
> ```
> 
> );
> return listView;
> }

I'm trying to get value from a list.

**Comment by mraleph** [comment]
@mcjons I recommend asking questions on StackOverflow instead of leaving questions on random closed issues. You are much more likely to get help there.
