### ISSUE TITLE
CFE has unsound behavior on redirecting constructors

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32343]
This code:

```
class Foo<T> {
  T x;
  Foo.from(String _init) : this._internal(x : _init);
  Foo._internal({this.x});
}

void main() {
  var f = new Foo<int>.from("hello");
  print(f.runtimeType);
  print(f.x);
  print(f.x.isEven);
  f.x = 3;
  print(f.x.isEven);
}
```

produces an error on the analyzer indicating that `String is not assignable to T`.  The CFE produces no error, and prints:

```
Foo<int>
hello
null
false
```

The inference for the redirecting constructor is going off the rails.  I could see an argument that we should go ahead and infer Foo<String> for the call to `this._internal` and then either emit an error on the cast (almost always) or insert an implicit downcast if the bound on the type argument happens to allow the downcast. 

This doesn't feel quite right though.  I think this should be treated as a downwards context.  So we're inferring the call to `Foo._internal` in a downwards context of `Foo<T>`, so we fix the type argument to `Foo._internal` to `T`, and then either the argument is valid (possibly via a downcast) or it's not.

So I think the CFE should be issuing the same error as the analyzer here.

cc @jmesserly @lrhn @stereotype441 @kmillikin

**Comment by stereotype441** [comment]
@stefantsov I know you've been working on CFE redirecting constructor behaviors - do you want to take this?

**Comment by leafpetersen** [comment]
I believe that this is also essentially the same issue:

```
typedef Id<T> = T Function(List<T>);

class Bar<T> {
  Id<T> x;
  Bar.from(Id<T> _init) : this._internal(x : _init);
  Bar._internal({this.x});
}
```
This code has no errors with the analyzer, but produces the following error with the new front end:

```
file:///Users/leafp/tmp/ddctest.dart:36:46: Error: A value of type '(dart.core::List<#lib1::Bar::T>) → #lib1::Bar::T' can't be assigned to a variable of type '(dart.core::List<dynamic>) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dart.core::List<dynamic>) → dynamic'.
```

This comes up in internal code.

**Comment by stefantsov** [comment]
From the first sight it seems like a manifestation of https://github.com/dart-lang/sdk/issues/32049.  The inference is currently not working when the type arguments are omitted on the right hand side.

@stereotype441 Sure!  If it's actually https://github.com/dart-lang/sdk/issues/32049, it has been on my radar for some time.  I would appreciate your advice on how to apply inference though.

@leafpetersen Yes, I think you are right, those two look like the same issue.

**Comment by stefantsov** [comment]
Hmm...  I think the link to https://github.com/dart-lang/sdk/issues/32049 that I left in the previous comment is not correct.  It leads to a specification issue, but what I meant was that we need to handle missing type arguments in redirecting factory constructors.

**Comment by stefantsov** [comment]
I've just realized that it has nothing to do with redirecting factory constructors.  I'm so used to the fact that when someone mentions something "redirecting" around me it's redirecting factory constructors.  But this is redirecting generative constructors.

Anyways, I'm on the way of fixing that.

**Comment by stefantsov** [comment]
I believe [CL 44463](https://dart-review.googlesource.com/c/sdk/+/44463) should fix the issue.

**Comment by stefantsov** [comment]
I think the issue is resolved by https://github.com/dart-lang/sdk/commit/c31e628c4c8ef78d0a82ef9c5a163b41b0f43835.
