### ISSUE TITLE
Naming a method `get` causes error

### ISSUE THREAD

**Issue by javad-amiry** [dart-lang/sdk#32347]
Hey. See this simple class and method:

```
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart';
import 'package:angular/angular.dart';

@Injectable()
class ApiClient {

  final Client _http;
  static final _headers = { 'Content-Type': 'application/json' };
  static final _encodedHeaders = { 'Content-Type': 'application/x-www-form-urlencoded' };

  ApiClient(this._http);

  Future<T> get<T>(String url, T f(dynamic e)) async {
    try {
      final response = await _http.get(url);
      var data = JSON.decode(response.body);
      print(data);
      if(data == null)return null;
      final ts = f(data);
      return ts;
    } catch (e) {
      _handleError(e);
      return null;
    }
  }
}
```

It causes this error:

> Unexpected token 'Future'.
>   Future&lt;T> get&lt;T>(String url, T f(dynamic e)) async {
>   ^^^^^^

and when I rename the method say `get1` the error goes away. Is this normal? I have other classes with method named `get` and works just fine. Am I missing something here?

**Comment by zoechi** [comment]
cross-ref https://stackoverflow.com/questions/49035691/naming-a-method-get-causes-error

**Comment by mraleph** [comment]
Can you specify where do you see this? Which tool (dart2js, VM, ddc, analyzer) is showing an error?

**Comment by vsmenon** [comment]
Tried a simplified repro.  This appears to work fine at tip with both analyzer and CFE.  Will close - please reopen if you're still seeing with more details (i.e., tool, version).

```
import 'dart:async';
import 'dart:convert';


class ApiClient {

  Future<T> get<T>(String url, T f(dynamic e)) async {
    return null;
  }
}

```
