### ISSUE TITLE
Expression compilation breaks after failed Hot-Reload

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32341]
Update `bad_hot_reload.dart` after fixing.

**Comment by JekCharlsonYu** [comment]
Siva, do you mind triaging and assigning a person to work on this?

**Comment by a-siva** [comment]
I believe there are set of issues against expression evaluation that are being tracked in the flutter/flutter issue list and this might be a duplicate of that

**Comment by aam** [comment]
I don't believe there is an issue in flutter tracker for this yet.

**Comment by dgrove** [comment]
Is there something actionable here?

**Comment by aam** [comment]
@dgrove wrote:
> Is there something actionable here?

It turns out that not much. https://dart-review.googlesource.com/c/sdk/+/63721 should fix the test.

**Comment by mit-mit** [comment]
Closing, we believe this was resolved
