### ISSUE TITLE
Dart 2 List<dynamic> cast in for loop w/ no-implicit-casts

### ISSUE THREAD

**Issue by jimsimon** [dart-lang/sdk#32348]
Given the following example:

```dart
main() {
  List<dynamic> strings = ["ints"];
  for (int number in strings) {
    print(number - 10);
  }
}
```

Shouldn't the line `for (int number in strings) {` raise an analyzer error?  This code currently passes the analyzer without error but blows up at runtime.  It'd be nice if the analyzer was smart enough to handle this case.

Another case that would be ideal to handle:
```dart
main() {
  List<dynamic> strings = [999, "ints"];
  for (int number in strings) {
    print(number - 10);
  }
}
```
In this case it'd be great if the analyzer raised an error instead of blowing up on the second item in the list.

I'm not sure if detecting these patterns is possible, but I was a little surprised to not see an analyzer error when I was toying around with this code.  I also suspect that the likelihood of this mistake being made in real code is probably pretty tiny since most lists won't be filled with constant values.

**Comment by jmesserly** [comment]
One option you can try is the `--no-implicit-casts` flag: https://www.dartlang.org/guides/language/sound-dart#call-dartanalyzer-with-strong-mode-enabled, https://www.dartlang.org/guides/language/analysis-options#specifying-strong-mode. There is desire to remove implicit downcasts from the language at some point, but currently they're supported.

**Comment by jimsimon** [comment]
Ah interesting!  I'll give that option a try tomorrow, thanks!

**Comment by jimsimon** [comment]
So disallowing implicit casts didn't raise any errors in this scenario.  I also tried disallowing implicit dynamic, but that just seemed to want me to use an actual type for the list instead of dynamic.  It also wanted me to declare a return type for `main`.  I could definitely see that being useful, but it's not quite the error I was looking for.

**Comment by jmesserly** [comment]
Oh gosh, that sounds like we may have a bug. When I tried to just now:
```
$ dartanalyzer --strong --no-implicit-casts test.dart 
Analyzing test.dart...
  error • The type 'List' used in the 'for' loop must implement Iterable with a type argument that can be assigned to 'int' at test.dart:3:22 • for_in_of_invalid_element_type
1 error found.
```
Does that work for you on your machine?

**Comment by jimsimon** [comment]
That worked correctly, but WebStorm doesn't for sure :-/

![image](https://user-images.githubusercontent.com/156367/36812084-f287b3c4-1c9d-11e8-8982-deba675d2791.png)

**Comment by jimsimon** [comment]
I was also surprised to see that strong mode isn't on by default in Dart 2 (it turns off if I comment out the strong-mode config in the analysis options).  I suspect that's going to change at some point in the future?

**Comment by zoechi** [comment]
You would need to pass `--preview-dart-2` to get actual Dart 2 behavior.

**Comment by jmesserly** [comment]
Ah yes I can confirm that I'm seeing the same thing, when I turn off implicit casts for my project:
```
analyzer:
  strong-mode:
    implicit-casts: false
```
I'm seeing a lot of new errors, but I'm not seeing an error about a for-in loop similar to your example. It may be something about the IDE analysis_server compared to command line dartanalyzer. So this does indeed seem like a bug with the no-implicit-casts feature.

**Comment by jimsimon** [comment]
@zoechi Thanks, I missed that part in the announcement blog post!

@jmesserly Glad to see/hear that I'm not crazy! :)

**Comment by srawlins** [comment]
The analyzer now reports the following error for this code:

> error • The type 'List<dynamic>' used in the 'for' loop must implement Iterable with a type argument that can be assigned to 'int'. • a.dart:3:22 • for_in_of_invalid_element_type
