### ISSUE TITLE
Disallow changing an inferred type by default

### ISSUE THREAD

**Issue by jimsimon** [dart-lang/sdk#32349]
It'd be great if the following code raised an error because the inferred type changed:
```dart
main() {
  var myCoolValue = 42;
  myCoolValue = 'forty-two';
  print(myCoolValue);
}
```

I suspect this kind of rule would help prevent bugs in more complex code (i.e. if 42 came from a database result and 'forty-two' came from some third party library).  I believe Rust implements something along these lines as well: [Example](https://play.rust-lang.org/?gist=c6b9afca74d96189de9c1d23690ac4ac&version=stable).

Additional syntax could also be added for backwards compatibility, maybe some sort of keyword to opt into allowing the type to change after initial inference.  Maybe require the author to explicitly say `dynamic` instead of `var`?

**Comment by jmesserly** [comment]
Good news, this is fixed in Dart 2 (or Dart 1 if you enable strong mode https://www.dartlang.org/guides/language/analysis-options#specifying-strong-mode, https://www.dartlang.org/guides/language/sound-dart#how-to-enable-strong-mode)

You should see a message like `[error] A value of type 'String' can't be assigned to a variable of type 'int'.` on the second line.

**Comment by jmesserly** [comment]
Info on Dart 2: https://www.dartlang.org/dart-2

**Comment by jimsimon** [comment]
I'm using Dart 2 and do not get an error from this code. :-/

**Comment by jmesserly** [comment]
@jimsimon how are you using Dart 2 (i.e. where did you expect to see an error but did not get it)? Some of the Dart 2 implementations are not yet complete with their checks.

**Comment by jimsimon** [comment]
I'm using the Dart plugin in WebStorm against the latest dev release from Homebrew.

**Comment by jimsimon** [comment]
FWIW, it looks like it errors out correctly on DartPad.

**Comment by jmesserly** [comment]
I believe the IDE plugin defaults to Dart 1, unless Strong Mode is set in analysis_options.yaml:
```
analyzer:
  strong-mode: true
```

**Comment by jimsimon** [comment]
Does the Dart 2 SDK still have a Dart 1 runtime?  If so, then you might be right.  I only have the Dart 2 SDK installed and the project is configured to use it.  I can poke around a bit more tomorrow and see if the setting you suggested helps, or if there's some other IDE config option I missed.  Thanks!

**Comment by jmesserly** [comment]
Yeah, most tools default (e.g. Dart VM, dart2js, Dart Analyzer) still default to Dart 1 mode, at least as far as type checking (the SDK has some API changes, and some of the new language syntax features like generic methods are implemented)

**Comment by jimsimon** [comment]
Weird, I just tried this again without changing anything and I'm getting the error as expected.  I'm going to chalk this one up to my computer running slow.  This code does still work at runtime though as I'm able to run the code without it crashing.  Is that expected with strong mode enabled?  I know analyzer errors/warnings were just hints in the past, but it's not clear if that's changing with Dart 2 and strong mode.

**Comment by jmesserly** [comment]
It will be rejected at runtime once the compilers/runtimes have fully implemented the Dart 2 checks.

**Comment by jmesserly** [comment]
p.s. thanks for trying Dart 2 and filing these reports of your experiences! It's great to get feedback.

**Comment by jimsimon** [comment]
No problem!  I've had an on again and off again relationship with Dart since it was first announced.  I'm hoping Dart 2 and beyond addresses some of my issues/concerns with the language and SDK. :)
