### ISSUE TITLE
Build of host ia32 dart in ARMv7 cross-compilation fails - result segfaults - on Debian

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#32350]
Building ARMv7 32-bit dart sdk on a Debian based linux fails because the x86 dart executable it builds (to generate the snapshots for the ARM sdk) crashes.

After upgrading to our local Debian distribution, and adding toolchain support with
sudo apt-get install g++-multilib
sudo apt-get install g++-arm-linux-gnueabihf  # For 32-bit ARM (ARMv7)
sudo apt-get install g++-aarch64-linux-gnu    # For 64-bit ARM

the build of --arch=arm fails at the end, when the host executable at
out/ReleaseXARM/x86/dart crashes.  It is needed to generate the snapshots for
the ARMv7 SDK.

A build of --arch=ia32 succeeds, and if the copy of dart is copied from out/ReleaseIA32/dart to x86/dart, then the build of --arch=arm succeeds

The equivalent situation with ARMv8 64-bit builds does not have a problem.  The dart executable at out/ReleaseXARM64/x64/dart does not crash, and both ARMv8 and X64 builds succeed.

**Comment by zanderso** [comment]
> Building ARMv7 32-bit dart sdk on a Debian based linux fails because the x86 dart executable it builds (to generate the snapshots for the ARM sdk) crashes.

How does it crash? Can you get a backtrace from a debug build? I haven't been able to reproduce this.
