### ISSUE TITLE
@proxy doesn't work anymore

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32358]
I have a class called `Json` that implements `noSuchMethod` so that you can write code like `data.foo.bar.baz` to dereference through JSON objects. It worked fine in the past, but now it gives tons of analyzer warnings.

**Comment by matanlurey** [comment]
Proxy has been removed in Dart2: https://github.com/dart-lang/sdk/issues/32251

See this commit from @lrhn with details: https://github.com/dart-lang/sdk/commit/eaf49211ceee4527040a43dbe82cc0970566964f

**Comment by matanlurey** [comment]
A bit more information: https://github.com/dart-lang/sdk/issues/30220

**Comment by Hixie** [comment]
Ok but that's a non-starter. It breaks this code in an irrecoverable way.

**Comment by matanlurey** [comment]
Lots of Dart2 breaks code in a an irrecoverable way.

You may want to setup a meeting with @leafpetersen to discuss this further, this change has already been implemented, decided, and landed (and I don't think we plan to change it).

**Comment by Hixie** [comment]
ok, will do when I get back in the office. In the meantime I'll file a feature request.

**Comment by leafpetersen** [comment]
You can still use the "NSM implements everything" path if you type things as dynamic, but the most basic property we're aiming for in Dart 2 is that if you say something has static type Widget, the Widget methods are there.  You can make a class which implements `Widget`, and use NSM to automatically implement all of the methods, but you can't make a class that implements everything everywhere.

I do think we want a feature here to replace this.  It might looks something like having some way to specify a static type which means "Treat this like a Widget for method call analysis, but do dynamic lookup on everything and don't allow it to be assigned to real Widgets".  Or it might look like some kind of delegation feature.  Or it might look like some kind of drop in extension method feature.  Or something else?  

We're definitely interested in hearing about use cases.

cc @lrhn

**Comment by lrhn** [comment]
The use case here is an object that responds to any message, but doesn't try to implement any interface. It's a non-`dynamic` type with dynamic dispatch. That is one use-case for `proxy`, but it's also a use-case that can be handled by `dynamic` itself, so it's not essential. It's not really a property of the object, it's a property of the way it's called, and floating it around like an implicitly inherited annotation isn't making that very clear.
Replacing the `Json` type with `dynamic` everywhere (writing it explicitly to avoid *inferring* `Json`) should make the program work again.

**Comment by leafpetersen** [comment]
Moving further comments over to https://github.com/dart-lang/sdk/issues/32360.
