### ISSUE TITLE
Many analysis server integration tests time out on Windows bots (marked skipped)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32356]
I re-enabled all the tests on Windows because they pass locally, however these ones are timing out on the buildbots:

```text
analysis_server/test/integration/analysis/get_navigation_test
analysis_server/test/integration/analysis/reanalyze_concurrent_test
```

I'm re-suppressing them in `pkg/pkg.status` for Windows to fix the build.

On my machine they're taking around 13 seconds (on the builbots it's > 30s).

**Comment by whesse** [comment]
The timeouts are happening inside the pkg:test or pkg:unittest framework, so we cannot affect that by changing our test.py timeout.  The tests need to be rewritten to not time out, or the framework's timeout needs to be changed for that test if possible.

The status should be changed to RuntimeError (if consistent) or Pass, RuntimeError (if flaky)

**Comment by DanTup** [comment]
I haven't dug into this, but I did just test quickly one of these tests on both Windows and my Mac a few times to see if there was a discrepancy between platforms but I see 10-17 seconds for 'test/integration/analysis/reanalyze_concurrent_test.dart` on both platforms.

Possibly some of them would work just setting as slow, but I'd rather we seem them all passing locally on a Windows machine first (they fail for various reasons for me, I haven't investigated yet and might not get chance soon).

**Comment by DanTup** [comment]
Looks like some of these are still marked as skip:

https://github.com/dart-lang/sdk/blob/6c197f7bb10b4b7508cefabfadccac00b161d76c/pkg/pkg.status#L206

I'm not sure if there's a way we can run them on the bots to see if they still time out without merging to master? (when I last looked, they were much faster than the timeout locally, but it's not clear if on the bots they were just slower (possible due to less resources/contention) or just hung).

**Comment by bwilkerson** [comment]
We can create a CL that removes the skips, then add the windows bots to the list of bots to run for the dry run.

**Comment by DanTup** [comment]
Here's a CL removing the skip:

https://dart-review.googlesource.com/c/sdk/+/72641

I see a "Choose Tryjobs" option and can see a bunch of `win` ones - is it safe to just tick all of them and run, or might some of them do special things (like build releases)? Seems I didn't include which bots failed in my original message :(

**Comment by bwilkerson** [comment]
It's safe to select all of them, but you only need to select the ones that start with "analyzer-" or "pkg-" because those are the only ones that should be running any of the analyzer tests.

**Comment by DanTup** [comment]
I ticked both of those, and they went green... I've kicked off a normal Dry Run and if it passes I guess we should land it and review the full run afterwards.

**Comment by bwilkerson** [comment]
Sounds good to me, thanks!

**Comment by DanTup** [comment]
I've landed https://dart-review.googlesource.com/c/sdk/+/72641. I'll check on it in a little while to ensure nothing broke, but it does appear to break anything and you spot it before me, feel free to revert.

**Comment by DanTup** [comment]
As far as I can tell, everything that was previously green remained green, so I believe this is resolved. If they turn out to be flaky and need reverting/investigating, feel free to re-open and/or ping me!
