### ISSUE TITLE
clang doesn't like SignalHandler::SignalHandlerTrampoline

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#32362]
At: https://github.com/dart-lang/sdk/blob/master/runtime/vm/signal_handler.h#L92

Triggers:
```
../../runtime/vm/signal_handler.h:103:5: error: non-ASM statement in naked function is not supported
    register int arg0 asm("r0") = signal;
```

This configuration doesn't have any users, and requires manually editing https://github.com/dart-lang/sdk/blob/master/build/config/arm.gni#L70 and https://github.com/dart-lang/sdk/blob/master/tools/gn.py#L153 to select it, but I wanted to file this anyway to refer to in comments.

/cc @mraleph @mkustermann

**Comment by rmacnak-google** [comment]
We've been building successfully with clang for a while.
