### ISSUE TITLE
DDC: Uses "document.", so unusable in a worker

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32371]

**Comment by vsmenon** [comment]
Is this with `package:build`?  I think that's from the bootstrap code there. 

@kevmoo ran into the same issue and hacked around it.

**Comment by kevmoo** [comment]
@matanlurey – https://github.com/dart-lang/build/issues/1059

**Comment by matanlurey** [comment]
Ah, I take this back. Thanks!
