### ISSUE TITLE
Unable to disable DDC

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#32379]
Apologies if this is the wrong place for this but I've been stuck with it for 2 days and can't find a solution. 

I'm trying to disable dart dev compiler and go back to use pub + dartium. I’ve rolled the project back which removed all reference of `dartdevc` from my `pubspec.yaml`, I’ve totally uninstalled the Dart 2.0 SDK then reinstalled stable (1.24.3), I've deleted `.pub/`, `.dart_tool/`, `.packages/`. 

However when i run `pub serve` I get dart dev compiler errors and it won't serve `.dart` files.

I've tried using `--web-compiler=none` but it just seems to ignore it and use ddc.

**Comment by vsmenon** [comment]
@jakemac53 - any ideas here?

**Comment by jakemac53** [comment]
No idea, --web-compiler=none works for me.

**Comment by jimmyff** [comment]
ahhh, so sorry to bother you both. It was my project hadn't correctly/fully rolled back. I had modifications i'd made for all the new stuff causing the errors which I had mistaken for DDC errors as CRL+C kept telling me it was `cleaning up the dartdevc environment`. 

Doing a git reset has just sorted it all out.
