### ISSUE TITLE
Add SetQueue to dart:collection

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/sdk#32386]
I need a queue that automatically sorts out duplicates. Right now I do:
```dart
final queue = new Set<Something>();
while (queue.isNotEmpty) {
  final something = queue.first;
  queue.remove(something);
  process(something);
}
```

But having a dedicated class for that would be nice. I can try to implement it, but I'll need help when it comes to benchmarking. (compare #31470?)

Also, please tell me if I should rather file this request on a different package. :)

**Comment by lrhn** [comment]
I don't see such a specialized structure being added to the platform libraries. It's more likely to be added to package:collection.

I'd probably just use a `LinkedHashSet`. Its `first` and `last` operations *should* be efficient. If they aren't, we're missing something somewhere.

**Comment by pschiffmann** [comment]
> I don't see such a specialized structure being added to the platform libraries. It's more likely to be added to package:collection.

Fair enough. I'll open a new ticket over there, thanks!
