### ISSUE TITLE
Move contributing page from wiki to top level of repo

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#32380]
https://github.com/dart-lang/sdk/wiki/Contributing is hard to find. It should instead be in the root level of the repo, as CONTRIBUTING.md, so it'll plug into GitHub's support. More info: https://blog.github.com/2012-09-17-contributing-guidelines/

I can do this, if no one objects (or wants to do it).

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/e68b838643126b65f7650b9e8266530d5e9fee4f – right, @kwalrath ?

**Comment by kwalrath** [comment]
Yes, thanks @kevmoo!
