### ISSUE TITLE
JS Interop "self.[zzz] is not a constructor" after building

### ISSUE THREAD

**Issue by mayorbyrne** [dart-lang/sdk#32387]
Hi, I'm beginning to delve into JS Interop, but having a little trouble understanding with the existing documentation. I've used it before successfully with existing libraries, but I'm not entirely sure how the magic is happening. Perhaps someone can steer me in the right direction with my issue.

For simplicity sake, I have the following code:

---
**helloWorld.js**
```js
'use strict';

function HelloWorld()
{}

HelloWorld.prototype.printMe = function()
{
  var hello = "HELLO WORLD!";
  console.log("YOU GOT HERE, " + hello);
}
```

**hello_world_interop.dart**
```dart
@JS()
library hello_world_interop;

import 'package:js/js.dart';
import 'dart:js';

@JS('HelloWorld')
class HelloWorld
{
  external factory HelloWorld();
  external void printMe();
}
```

**main.dart**
```dart
import 'package:untitled/src/hello_world_interop.dart';

void main()
{
  HelloWorld helloWorld = new HelloWorld();
  helloWorld.printMe();
}
```

**index.html**
```html
<!DOCTYPE html>

<html>
<head>
    <script defer src="main.dart" type="application/dart"></script>
    <script defer src="js/helloWorld.js"></script>
</head>

<body>

</body>
</html>
```
---

When I run this normally, I get (as expected)
![capture](https://user-images.githubusercontent.com/1082201/36903985-f49b1608-1df4-11e8-86a5-2355709f6717.PNG)

---

After building, I get
![capture](https://user-images.githubusercontent.com/1082201/36904111-5a940b5e-1df5-11e8-8721-29cf610cd88f.PNG)

---

I'm not sure where I'm going wrong. Any help would be greatly appreciated!

**Comment by jonahwilliams** [comment]
Hi @mayorbyrne - I believe the issue is that the `helloWorld.js` script hasn't loaded when `main()` executes in Dart.  To fix this just rearrange your script tags so that `main.dart` is loaded last.

DDC does some extra caching before launching main, which is why the issue only shows up in dart2js.

**Comment by mayorbyrne** [comment]
@jonahwilliams that fixed it! thanks for the information! I would never have thought of that!
