### ISSUE TITLE
Meta Issue for Flutter Test Run  (14728)

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#32381]
This is just a dummy issue to link to 
"Run flutter tests in preview-dart-2 mode on travis flutter builds." 
https://github.com/flutter/flutter/pull/14728

Will be updated during the triaging meeting

**Comment by dgrove** [comment]
After talking with @aam, the test speed issues from flutter/flutter#14728 aren't a blocker for flipping the flag. It sounds like there are still a few failing tests in Flutter with --preview-dart-2, which are being looked at.

**Comment by dgrove** [comment]
@a-siva @aam can this be removed from the I/O Beta 2 milestone? (I believe the actual bugs aren't being tracked in flutter/flutter#14728)

**Comment by aam** [comment]
@dgrove yes, we would want to have separate(different from flutter/flutter#14728) issue to track performance of `flutter test --preview-dart-2` anyway.

**Comment by dgrove** [comment]
@aam Is this still the right place to track the perf of "flutter test" for the next beta release?

**Comment by aam** [comment]
I guess yes, we can use this one now to track performance work that Jens is doing to incremental compiler here: https://dart-review.googlesource.com/c/sdk/+/47020

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/47020 was reverted, and relanded as
https://dart-review.googlesource.com/c/sdk/+/49125 .

@a-siva is there more work to do here for Beta 3?

**Comment by a-siva** [comment]
This is done and can be closed.
