### ISSUE TITLE
`int.parse` and `double.parse` are inconsistent

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#32392]
from @trinarytree (see #32383 )

if one were to redesign the interface, it should probably work like int.parse or double.parse.
unfortunately, those don't work exactly like each other.

`int.parse` has has an optional named param named `onError`.
`double.parse` has an optional positional param named `onError`.
a named param is probably better because these will often be used with anonymous function expressions. e.g.
`double.parse('e10', (_) => 1.23)`
is less readable than

`int.parse('e10', onError: (_) => 123)`
if redesigning the interface is seriously on the table, let's spin off a separate issue.

**Comment by zoechi** [comment]
looks like a dup of #16319

**Comment by vsmenon** [comment]
Yes - thanks!  I'll mark this as a dup.
