### ISSUE TITLE
Unexpected dartdoc on getHover for method argument

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32390]
Given this code:

```dart
/// This is my method taking a string.
void methodTakingString(String a) {
  print(a);
}
```

If you send a hover request for the `a` (at either location) the response includes the dartdoc from the method which seems a little weird since the description is not of the argument but of the whole method.

```text
[18:22:58]: ==> {"id":"19","method":"analysis.getHover","params":{"file":"/Users/danny/Dev/Dart-Code/test/test_projects/hello_world/lib/everything.dart","offset":608}}
[18:22:58]: <== {"id":"19","result":{"hovers":[{"offset":608,"length":1,"dartdoc":"This is my method taking a string.","elementDescription":"String a","elementKind":"parameter","isDeprecated":false,"staticType":"String"}]}}
```

**Comment by bwilkerson** [comment]
True, but dartdoc doesn't provide any way to document individual parameters. I suppose it could allow a doc comment before each parameter, but I doubt anyone would ever use it:
```
/// This is my method taking a string.
void methodTakingString(
    /// The string taken by this method.
    String a) {
  print(a);
}
```
On the other hand, it's fairly common for those parameters to be documented in the method's comment:
```
/// This is my method taking [a] and printing it.
void methodTakingString(String a) {
  print(a);
}
```
Hence, we decided to include the dartdoc in the hover for parameters.

**Comment by DanTup** [comment]
Sounds reasonable (and deliberate), so unless you think there's something to do you're free to close this!
