### ISSUE TITLE
Parse error on generic method call after super property chain

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#32393]
This generates a parse error in analyzer:

```dart
class A {
  method() {
    super.b.c<D>();
  }
}
```

Parenthesizing the super expression works around the issue:

```dart
class A {
  method() {
    (super.b).c<D>();
  }
}
```

But I believe the above syntax should be allowed to.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/45440
