### ISSUE TITLE
This VM was built without support for AOT compilation.

### ISSUE THREAD

**Issue by chaokongzwp** [dart-lang/sdk#32403]
I build the dart sdk myself, but  the can not support AOT compilation

when i build the dart source file use --snapshot-kind=app-aot

**Comment by mraleph** [comment]
@chaokongzwp If you are building Dart SDK from source you need to use `dart_bootstrap` binary, it will be in the `out/Release<arch>/dart_bootstrap`.

Please let me know if you have any other questions.

**Comment by chaokongzwp** [comment]
@mraleph thanks 
 I am a flutter developer,  I just want to kown how to custum dart  for flutter,
I compile a dart sdk with debug mode for flutter in ios system ,  I need to kown how the flutter engine run dart code in ios release mode.
