### ISSUE TITLE
cascade_invocations is too eager when type promotion is necessary

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32407]
Enable the cascade_invocations lint, then analyze this:

```dart
class A { }
class B extends A { void foo() { } }

void test(A x) {
  if (A is B) {
    final B b = x;
    b.foo();
  }
}
 
void main() { }
```

It says: `lint • Cascade consecutive method invocations on the same reference at test.dart:7:5 • cascade_invocations`

However, if you change it as suggested:

```dart
class A { }
class B extends A { void foo() { } }

void test(A x) {
  if (A is B) {
    final B b = x
      ..foo();
  }
}
 
void main() { }
```

...then now the code is no longer correct (`error • The method 'foo' isn't defined for the class 'A' at test.dart:7:9 • undefined_method`).

**Comment by lrhn** [comment]
Probably don't mean to say `if (A is B)`, but if you do `if (x is B)` the warning goes away.

**Comment by Hixie** [comment]
Oops, sorry about that typo.

I don't think it changes this bug, though. That conditional could be anything that happens to imply, in a way the analyzer can't recognize, that the cast is ok; the cascade operator isn't appropriate in this case.

**Comment by bwilkerson** [comment]
I'm having trouble thinking of a concrete example of the condition you described. I'm assuming that you actually ran into this somewhere. Can you point us at the actual code that caused the problem?

**Comment by Hixie** [comment]
Yeah, it's https://github.com/seamonkeysocial/cruisemonkey/pull/9/files#diff-e3af0e3a6e3dbe50cfde8027a6c541c8R262

**Comment by bwilkerson** [comment]
Ok, thanks. The problem arrises when the variable cannot be promoted. Sounds like the lint might be checking the wrong type at that point.

**Comment by bwilkerson** [comment]
@alexeieleusis

**Comment by leafpetersen** [comment]
The second error message is actually incorrect, see https://github.com/dart-lang/sdk/issues/30542 

The intention is that 

```
 final B b = x
      ..foo();
```

should be treated (after implicit downcast insertion) as:

```
 final B b = (x as B)
      ..foo();
```

Neither of the front ends implements this entirely yet though.

**Comment by srawlins** [comment]
CC @pq move to linter?
