### ISSUE TITLE
Flutter Log ...

### ISSUE THREAD

**Issue by zukosanti** [dart-lang/sdk#32410]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

**Comment by bwilkerson** [comment]
I suspect that some of the information didn't get copied into the issue, because I'm not seeing a description of the problem.
