### ISSUE TITLE
Pub dry run meta package issue on Flutter

### ISSUE THREAD

**Issue by lukef** [dart-lang/sdk#32418]
```
Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "macos_x64"
Flutter: master
```

If you use the `@required` annotation and combine it with `import 'package:meta/meta.dart';` then `pub publish --dry-run` will report that the `meta` package is not used. If it is replaced with `import 'package:flutter/foundation.dart';` then the problem goes away.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/pub#1830

**Comment by lukef** [comment]
Thanks! Will log pub issues correctly next time :)
