### ISSUE TITLE
Iterable.whereType returns everything in VM unless --preview-dart-2

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#32423]
I cannot get [`whereType`](https://api.dartlang.org/dev/2.0.0-dev.27.0/dart-core/Iterable/whereType.html) to work on the VM. I haven't tried using dart2js or DDC. I tried with Lists, Sets, built-in types, and my own classes:

```dart
void main() {
  var listOfNum = <num>[1, 2.2, 3, 4.4, 5];
  print(listOfNum.whereType<int>());
  print(listOfNum.whereType<double>());
  print(listOfNum.whereType<String>());

  var setOfNum = new Set<num>.from(listOfNum);
  print(setOfNum.whereType<int>());

  var a1 = new A();
  var a2 = new A();
  var b1 = new B();
  print([a1, a2, b1].whereType<B>());
  print(new Set.from([a1, a2, b1]).whereType<B>());
}

class A {}

class B extends A {}
```

```none
$ dart --version
Dart VM version: 2.0.0-dev.32.0 (Thu Mar 1 18:39:53 2018 +0100) on "macos_x64"

$ dart a.dart
(1, 2.2, 3, 4.4, 5)  # I expected (1, 3, 5)
(1, 2.2, 3, 4.4, 5)  # I expected (2.2, 4.4)
(1, 2.2, 3, 4.4, 5)  # I expected ()
(1, 2.2, 3, 4.4, 5)  # I expected (1, 3, 5)
(Instance of 'A', Instance of 'A', Instance of 'B')  # I expected (Instance of 'B')
(Instance of 'A', Instance of 'A', Instance of 'B')  # I expected (Instance of 'B')
```

**Comment by matanlurey** [comment]
@srawlins I think it only works in `--preview-dart-2` (and DDC/DDK).

... which is really confusing, to me. Owch! @leafpetersen

**Comment by srawlins** [comment]
Oh thank goodness.

```
$ dart --preview-dart-2 a.dart
(1, 3, 5)
(2.2, 4.4)
()
(1, 3, 5)
(Instance of 'B')
(Instance of 'B')
```

Can I re-use this bug then to express my [astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) that _SOME_ core lib 2 methods only work with `--preview-dart-2`?!?!

`followedBy`, `singleWhere`, etc seem to work. I haven't tried [`cast`](https://api.dartlang.org/dev/2.0.0-dev.27.0/dart-core/Iterable/cast.html) or [`retype`](https://api.dartlang.org/dev/2.0.0-dev.27.0/dart-core/Iterable/retype.html) yet...

Can we maybe write something in [CHANGELOG](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md) if we all have to live with this for a few months?

**Comment by matanlurey** [comment]
I think `.whereType` is the only one that _explicitly_ fails. I believe the others just fall back to returning `C<dynamic>` instead of `C<T>`. If you asserted against the `.runtimeType` it wouldn't be right, for example.

**Comment by mraleph** [comment]
We can also turn on reified generics outside of Dart 2 mode as a transitionary measure. 

WDYT @a-siva?

**Comment by a-siva** [comment]
you mean reified generic methods I guess, we could there maybe some surprises without type inference but otherwise it would be ok.
@srawlins you could try your test as follows - 
 dart --reify-generic-functions /tmp/junk.dart

**Comment by lrhn** [comment]
The `cast` methods also fail entirely without reified generics.

We will not have reified generics until Dart 2, but the current SDK is a Dart 2.0 development branch, so there are Dart 2 specific methods in it.

Turning on reified generics in the VM only is likely to be confusing. It won't help code that gets compiled to JavaScript by dart2js, and it might even introduce errors in some cases. I'd just wait until we switch on the common front end so we have a level playing field for all backends.

**Comment by srawlins** [comment]
OK I don't want to complicate things. If --preview-dart-2 will become default on in a few weeks, maybe we just live with the surprise. Is it worth it to put something in the CHANGELOG? Will this confuse Flutter users?

**Comment by leafpetersen** [comment]
If you think it best, go ahead and put something in the CHANGELOG, though presumably we will want to take it out for the release (we're in a really weird state with the CHANGELOG).  Alternatively, we could put an interim comment in the doc comment for whereType.

**Comment by leafpetersen** [comment]
@jakemac53 ran into this too, and in talking to him I got a little worried, not about the VM very much, but about dart2js.  Externally, most people are running tests and running their code in the same mode, so if whereType doesn't work they'll see it in tests.  But internally, people are testing with DDC and running with dart2js, which seems like a recipe for badness.

@sigmundch How long before reification of generics is turned on in dart2js?

@lrhn What do you think about making this method external and patching in a version which throws on dart2js?  Alternatively, maybe we should just make it throw always for now?

**Comment by jakemac53** [comment]
Ya this was pretty surprising to me when I ran across it.

I have a somewhat crazy idea... would it be possible to add a check for `T == dynamic` inside the constructor for `WhereIterable` and throw if that is true? That way at least we could detect somebody trying to use it in a non-dart2 context and throw a good error message, instead of returning a non-filtered list which could have untold consequences. I don't think `whereType<dynamic>` is a useful thing anyways, and we could remove the check once the flag is flipped?

**Comment by sigmundch** [comment]
> @sigmundch How long before reification of generics is turned on in dart2js?

It's about a month out or a bit more.

**Comment by srawlins** [comment]
> @lrhn What do you think about making this method external and patching in a version which throws on dart2js? Alternatively, maybe we should just make it throw always for now?

This would be my preference: if `whereType` is not wired up right (read: not implemented) when executing `dart a.dart`, then it should throw Unimplemented, assuming its just a few temporary lines to change, and doesn't require changing (many lines in) status files.

**Comment by jakemac53** [comment]
> What do you think about making this method external and patching in a version which throws on dart2js?

That still leaves the vm in a really weird state which is why I suggested the other `T == dynamic` hack - it should a more generic solution... and while its absolutely a hack I think its a relatively safe one.

**Comment by jakemac53** [comment]
cc @kevmoo

**Comment by leafpetersen** [comment]
I landed the CL disabling this whereType for now, and filed https://github.com/dart-lang/sdk/issues/32463 to track re-enabling it.

Closing this.

**Comment by jakemac53** [comment]
Thanks @leafpetersen !
