### ISSUE TITLE
jump to declaration should jump to starting dartdoc

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32420]
Currently jump to declaration jumps to the start of the declaration site. We should likely jump to the start of any dartdoc for the symbol (or, jump to the site declaration, but scroll to ensure that any dartdoc for the symbol is visible.

@scheglov @jwren @alexander-doroshko @bwilkerson

**Comment by devoncarew** [comment]
I'm not sure if the implementation here would be entirely in the analysis server, or if the analysis server would need to return additional info and IntelliJ take advantage of that.

**Comment by bwilkerson** [comment]
It currently jumps to the offset of the identifier at the declaration site (not the start of the declaration site), which seems consistent to me.

Why do you think the start of the dartdoc be more appropriate than the location of the declared identifier?

How do IntelliJ and VS Code behave for other languages?

**Comment by alexander-doroshko** [comment]
In all languages that IntelliJ supports it jumps to the start of the name identifier and I'm sure it's the best thing to do.

**Comment by bwilkerson** [comment]
I agree (which is why server currently works that way :-)

@devoncarew What's the motivation for this request?

**Comment by scheglov** [comment]
FWIW, I also think that jumping to the identifier is the correct behavior.

**Comment by devoncarew** [comment]
This came in through a gitter channel, and is I believe the behavior that I used to see in Eclipse.

**Comment by devoncarew** [comment]
Not 100% sure that it's the right thing to do, but worth filing and discussing.

**Comment by bwilkerson** [comment]
As far as I can recall, we navigated to the offset of the name in DartEditor as well, which makes me think that Eclipse worked that way too. I suppose we could try it to see.

In any case, I don't think we should deviate from the client's standard behavior without a fairly compelling reason.

**Comment by bwilkerson** [comment]
The discussion appears to have tapered off, and the resolution, as I see it, is to leave the behavior as is.
