### ISSUE TITLE
Implicit tear-off of `.call` should be allowed even when there is an implicit downcast

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32426]
Consider the following code:
```dart
abstract class I {
  void call();
}
class C implements I {
  void call([int x]) {}
}
void test() {
  I i = new C();
  void Function([int]) f = i; // (1)
}
```
Currently, this code is rejected, because we only insert an implicit tear-off of `.call` at (1) if the static type of the torn-off method is a subtype of the expected type.  But the type of the torn-off method is `void Function()`, which is a *supertype* of the expected type (`void Function([int])`).

@lrhn suggests that we should change the logic so that all that is required is for the torn-off method to be *assignable* to the expected type, and I agree.  So in the example above, `.call` would be implicitly torn off, and then the resulting value would be implicitly downcast to `void Function([int])`.

I will write some test cases for this ASAP, and then begin fixing the front end.  I've added @jmesserly as a co-assignee, since she's working on the DDC/analyzer implementation of this feature.

**Comment by jmesserly** [comment]
Sounds good to me! Thanks for looping me in. Should be a straightforward change.

**Comment by stereotype441** [comment]
Correction to the above description: the front end doesn't reject the code in question, but it produces mal-formed kernel output.  I'm working on a fix for the front end now.

**Comment by stereotype441** [comment]
Front end fix is out for review: https://dart-review.googlesource.com/c/sdk/+/45522.

@jmesserly this CL includes a test case that may be useful to you (`tests/language_2/call_method_implicit_tear_off_assignable_test.dart`).

**Comment by jmesserly** [comment]
should be fixed in https://dart-review.googlesource.com/c/sdk/+/45141
