### ISSUE TITLE
Quick-fix to add an import leaves `// ignore:` comment on the wrong line

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#32432]
Quick-fix to add an import doesn't respect `// ignore: implementation imports` comment.
![image](https://user-images.githubusercontent.com/1226812/37042857-23d4cb54-2114-11e8-9a78-190b51b854c4.png)

Generally I think it would be reasonable for the quick fix to keep all existing comments grouped with the associated import even if the comment does not have semantic meaning as in the case of ignore: comments.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/45526
