### ISSUE TITLE
Exhaustive enum switch results in "missing end return" diagnostic

### ISSUE THREAD

**Issue by Phrohdoh** [dart-lang/sdk#32433]
```dart
enum X {
  A,
  B,
  C
}

String getStringFromX(X x) {
  switch (x) {
    case X.A: return "A";
    case X.B: return "B";
    case X.C: return "C";
  }
}
```

> [dart] This function declares a return type of 'String', but doesn't end with a return statement.

If you add a `default` case to that `switch` the diagnostic goes away.

**Comment by bwilkerson** [comment]
This is working as intended.

In Dart, enums are objects, like everything else, so there's another valid value for `x`: `null`. If `null` is passed as an argument to this method, then none of the cases will be selected and the switch statement will fall through. By default it will return `null`, but that's rarely what's intended, so we warn you.

If that is what you intend, then you can work around this by adding an explicit `return null;` at the end of the method, or add an ignore comment to disable the warning.

**Comment by Phrohdoh** [comment]
I see. Thank you @bwilkerson.

**Comment by egorikem** [comment]
This is totall bullshit if you ask me, and for a modern language, this is utter nonsense. Just take a look at how it should be done, e.g. in Kotlin

**Comment by MagTuxGit** [comment]
```
String getStringFromX(X x) {
  if (x == null) return "";
  switch (x) {
    case X.A: return "A";
    case X.B: return "B";
    case X.C: return "C";
  }
}
```
This is absolutely safe, but still the warning is present.
Adding `default` to the `switch` or `return` to the end of the method ISN'T safe. If I add a new value to the enum I'll get no warnings.

**Comment by eernstg** [comment]
Note that when the upcoming null-safety support arrives, the enum type `X` will be a non-nullable type, and the need to check for null will disappear.

**Comment by merelj** [comment]
any chance something like this will ever work:
```
  static const map = {X.A: 'A', X.B: 'B', X.C: 'C'};
  String getStringFromX(X x) => map[x];
```
?

switch statement get really verbose when there are a lot of enum values...

**Comment by eernstg** [comment]
The following works fine at the top level (and you can put `map` and `getStringFromX` into a class and use `static` as well, of course):

```dart
enum X {A, B, C}

const map = {X.A: 'A', X.B: 'B', X.C: 'C'};

String getStringFromX(X x) => map[x]!;
```

The map has type `Map<X, String>`, which makes it similar to the TypeScript type `Record<X, string>`.

TypeScript conditional types allow for type-level computations that express the exhaustiveness constraint (cf. https://stackoverflow.com/questions/46641380/exhaustive-map-over-a-union-of-typed-objects), and Dart has no corresponding kind of type-level computations, so you won't get a compile-time error if you forget one of the enum values. But apart from the exhaustiveness check, it works.
