### ISSUE TITLE
Loosen checks in Dart2JS in a Web Worker

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32438]
This is forked from an internal thread with @sigmundch and others.

> As part of removing Isolates on web, I wanted to create a (very) simple example of using web workers with JS interop, enough to help inspire (some) confidence so we don't need to drop everything and add it to dart:html. Here's my WIP:
> 
> https://github.com/matanlurey/web_worker_channel 
> 
> It almost works... except that any Dart2JS code that detects it is running in a web worker listens to incoming messages as part of isolate_helper.dart (patch), and then crashes because the incoming messages don't fit the old isolate messaging scheme.
> 
> To reproduce, git clone, make sure you on the latest Dart 2.0-dev, then:
> * pub upgrade
> * pub run build_runner serve
> * Navigate to localhost:8080
> 
> This loads a DDC application (main.dart), that tries to spawn a Dart2JS* web worker (worker.dart). It loads, and then the worker crashes as soon as main.dart sends a message:
> 
> ```
> Uncaught Error: Invalid argument (index): "command"
>     at Object.wrapException (js_helper.dart:1773)
>     at Interceptor.$index (js_string.dart:472)
>     at IsolateNatives__processWorkerMessage (isolate_helper.dart:844)
>     at isolate_helper.dart:257
> ```
> 
> ... because I'm sending a String, and isolate_helper assumes all messages are a JSArray with a specific encoding. Since we are removing isolates anyway, is it possible to just no-op/remove this code, or perhaps just add a 1-liner of:
> 
> ```
> if (is_not_array) {
>   return;
> }
> ```
> 
> ... to get around this until we have time for a proper cleanup.
> 
> I can file an external bug, I just wanted to give a chance for discussion first.
> 
> _*This is because of https://github.com/dart-lang/build/issues/1059 - but we need this to work eventually anyway, hence while I'm following up here._

Here is the offending code:

https://github.com/dart-lang/sdk/blob/a1cacec5fc3482366b15fb39ef38a62ce7bd30fc/sdk/lib/_internal/js_runtime/lib/isolate_helper.dart#L843-L844

I'm going to add a tiny "if-this-is-not-a-map-or-jsobject-return":

```dart
  if (msg is! JSObject && msg is! Map) {
    // See github.com/dart-lang/issues/<this issue> for details.
    return;
  }
```

... which should unblock us until isolates are totally removed.

**Comment by kevmoo** [comment]
I think this will ALL go away when `dart:isolate` is removed from DDC/dart2js

DDC PL: https://dart-review.googlesource.com/c/sdk/+/45754/3/pkg/dev_compiler/tool/input_sdk/private/isolate_helper.dart#b1134

Related issue: https://github.com/dart-lang/sdk/issues/32684

**Comment by sigmundch** [comment]
I think we need to fix this issue first. We need to provide users a way to start using web workers and to start migrating before we delete the dart:isolate support.

**Comment by 4F2E4A2E** [comment]
@kevmoo thank you for your answer yesterday [1], I can not reply there because it got locked.

I love the fact that obsolete and unwanted stuff got completely removed, but my point is to have a documented supported alternative for the web and if there are none then to document that.

So, is [2] the official "supported" alternative for isolates on the web?


1: https://github.com/dart-lang/sdk/issues/32684#issuecomment-726385823
2: https://github.com/matanlurey/web_worker_channel
