### ISSUE TITLE
Type demotion? Can x == null demote X to Null?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32445]
Inspired by https://github.com/dart-lang/sdk/issues/32437.

The code below will always fail when `null` is provided:

```dart
void printStringLength(String x) {
  // Oops! I meant if x != null.
  if (x == null) {
    print(x.length);
  }
}
```

I know we don't quite have nullability in the language, but even something like this would be nice, and perhaps a way for Kernel/CFE to "start" understanding nullability.

**Comment by matanlurey** [comment]
After staring at this for a minute or two, I realized my answer :(

Anybody can write this (terrible) code:

```dart
class AlsoNull {
  @override
  bool operator==(o) => o == null;
}

void main() {
  var alsoNull = new AlsoNull();
  print(alsoNull == null); // true :(
  print(null == alsoNull); // false :)
}
```

I really wish `operator==` could be special cased :-/

While experimenting, I also realized the following:

```dart
void main() {
  final x = null; // inferred as dynamic, not Null. Intentional?
}
```

**Comment by matanlurey** [comment]
Another option is special case `== null` to always mean `identical(LHS, null)`?

**Comment by srawlins** [comment]
This could at least be an analyzer check.

**Comment by rakudrama** [comment]
Spec 16.23 in essence defines `a == b` as
```
  (identical(a, null) || identical(b, null)) ? identical(a, b) : a.operator==(b)
```

So `== null` is already special-cased to test against `null` before calling `operator==`.
You will never see a `null` argument inside `operator==`.
(dart2js implements this by injecting `if (identical(null, other)) return false;` in every `operator==` method except `Null.==`).


I think it would be reasonable to treat all of the following the same with respect to type promotion. (All type promotion is 'demotion')

```dart
  if (x == null) ...
  if (null == x) ...
  if (x is Null) ...
```

**Comment by lrhn** [comment]
Ob-history: The reason `==` isn't instead written as `(identical(a, b) || !identical(a, null) && !identical(b, null) && a.operator==(b))`, which would also ensure reflexivity for you and not encourage you to start your `==` with `if (identical(this, other)) return true;`, is ... NaN (aka `double.nan`).

Since `NaN` isn't equal to itself, it breaks all the rules of `==`, and prohibits this otherwise nice improvement.  Thanks IEEE 754! :)

**Comment by srawlins** [comment]
Be excited; this is coming in NNBD, and has been accepted in the spec under ["Null Promotion"](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#null-promotion).
