### ISSUE TITLE
flutter_gallery can't compile  

### ISSUE THREAD

**Issue by minggangLu** [dart-lang/sdk#32447]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4408382`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-171.4408382, JRE 1.8.0_112-release-b06x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

**Comment by zoechi** [comment]
Do you get an error message?
Can you please add the output of `flutter doctor -v`?
