### ISSUE TITLE
unable to complete a type name with --preview-dart-2

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32456]
When running in preview-dart-2, I'm unable to complete a type name. It assumes there there's an implicit `new` in from of the type, and inserts a construction call; in my case, I'm trying to complete the type name in order to reference a static field of the type.

<img width="623" alt="screen shot 2018-03-07 at 11 22 31 pm" src="https://user-images.githubusercontent.com/1269969/37121858-bc93ed02-225e-11e8-8fc0-3da3e5e6be9a.png">

@scheglov @bwilkerson

**Comment by scheglov** [comment]
Hm... I need more details about this.

It works for me when I try something like this with bleeding edge Analysis Server and IntelliJ.

```dart
class FrameInfo {
  static const Z = 1;
  
  FrameInfo.named();
}

main() {
  int foo = Fr^
}
```

![image](https://user-images.githubusercontent.com/384794/37122089-06740484-2214-11e8-8dcd-fe6902bf5251.png)

**Comment by scheglov** [comment]
Ah, I see.
If there is the default constructor, we don't suggest the class name.

**Comment by scheglov** [comment]
The reason why this happens is that there is a conflict between the class name and the default constructor. They both have the same completion text - `FrameInfo`. And we merge them in `DartCompletionRequestImpl` into one (which happens to be a constructor). This is a bug, if we expect to get both types and its constructor invocations, we should keep both separately.

**Comment by devoncarew** [comment]
Thanks!
