### ISSUE TITLE
Need buildbots for simarm64-dartkp-debug

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#32451]
We seem to have `simarm{,64}-dartkp-release` but not the debug versions of those. We need them.

Currently we hit ASSERT's in some tests in the register allocator which are most likely bugs we need to fix.

/cc @mraleph

**Comment by athomas** [comment]
simarm (without 64) is being replaced with simarm_x64 which will have a debug mode bot.

simarm64 is still relevant.

**Comment by rmacnak-google** [comment]
There are mac-arm64 debug bots covering this now.
