### ISSUE TITLE
dart2js crashes in strong mode.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32453]
With CL https://dart-review.googlesource.com/c/45501/, dart2js *crashes* on map_update_test.dart when run in strong mode. See: https://ci.chromium.org/p/dart/builders/luci.dart.try/dart2js-linux-d8-kernel-minified-try/35

**Comment by sigmundch** [comment]
Thanks Lasse, I'll just close this issue since we'll use the status file as the source of truth while we get strong mode in shape.
