### ISSUE TITLE
Add a path param to `search.getDeclerations`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32461]
Currently the document symbol search in Dart Code uses OUTLINE notifications and because of changes since it was implemented we starting some unexpected things to the user like constructor invocations (https://github.com/Dart-Code/Dart-Code/issues/656).

I think the new `search.getDeclerations` is a much better API for this if we could only filter it to a specific file. This would allow us to share the same mapping code and should make the UI presentation to the user the same (and it isn't likely to start showing strange things like the above case because it's semantically what we wanted anyway).

@bwilkerson @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/45761

**Comment by DanTup** [comment]
Awesome, thanks! I'll test it out next week and if it looks good will ask you to bump the server version.

**Comment by DanTup** [comment]
@scheglov All looks good, and I can see the server version has gone up to 1.20 since, so I'll just use that. Thanks!
