### ISSUE TITLE
MapEntry does not have a useful toString()

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#32464]
```dart
print({1: 'hi', 2: [1,2,3]});  //=> {1: hi, 2: [1, 2, 3]}
print({1: 'hi', 2: [1,2,3]}.entries); //=> (Instance of 'MapEntry', Instance of 'MapEntry')
```

I think MapEntry should have a useful `toString()` method, since it contains exactly two members. Maybe something like:

```dart
print({1: 'hi', 2: [1,2,3]}.entries); //=> (MapEntry<1, hi>, MapEntry<2, [1, 2, 3]>)
print({1: 'hi', 2: [1,2,3]}.entries); //=> (1 => hi, 2 => [1, 2, 3])
print({1: 'hi', 2: [1,2,3]}.entries); //=> (MapEntry (1: hi), MapEntry (2: [1, 2, 3]))
```

**Comment by lrhn** [comment]
The use-case here is debugging, so `MapEntry(key, value)` or something similar is reasonable.
We could go for `(key, value)` or `key: value`, but that's less readable when debugging. A `MapEntry` is not just a pair, and it's not useful for building `Map.toString` (creating intermediate strings is inefficient).
