### ISSUE TITLE
move flutter analyze off of the task model

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32478]
Context here: https://github.com/dart-lang/sdk/issues/32421

There are three modes that flutter analyze runs in, and one of them is still on the analyzer's task model. That's presenting issues; this bug tracks the work to move flutter analyze off the task model.

**Comment by devoncarew** [comment]
PR in progress: https://github.com/flutter/flutter/pull/16281

**Comment by devoncarew** [comment]
done

**Comment by devoncarew** [comment]
re-opening this - I may have to revert the flutter PR

**Comment by dgrove** [comment]
Any updates?

**Comment by devoncarew** [comment]
@scheglov has landed several performance improvements for the `flutter analyze --flutter-repo` use case - analyzing 29 separate, related packages with the main one making heavy use of exports.

We're in the process of setting up a golem test that will benchmark `flutter analyze --flutter-repo` (@sortie) using a combined view of commits from dart-lang/sdk and flutter/flutter.

We'll then look at re-landing the PR to refactor flutter analyze, and likely need to re baseline the benchmark as part of that. @Hixie, I'll reach out to you about that likely in this coming week

**Comment by dgrove** [comment]
any further updates?

**Comment by devoncarew** [comment]
Round 2 is out for review, will likely land tomorrow, and we'll then watch how things go (it's a large refactor).

**Comment by dgrove** [comment]
This is https://github.com/flutter/flutter/pull/16979 ?

**Comment by devoncarew** [comment]
Yup, that's the one.

**Comment by devoncarew** [comment]
landed
