### ISSUE TITLE
Add quick-fix to fix all of type across the whole file

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32474]
One of the things I love about the TypeScript linting in VS Code is that I can fix all instances of the same problem in one go from the quickfix menu. Eg., if I enable a new lint and there are 50 violations in a file and I know they're all safe (eg. use double quotes instead of single), it's just one operation:

<img width="339" alt="screen shot 2018-03-09 at 11 32 18" src="https://user-images.githubusercontent.com/1078012/37205679-8f40b292-238d-11e8-9ce5-de3a12204bf9.png">

It'd be great to support the same for Dart (the TS one is actually really buggy, so maybe we can be better!).

@bwilkerson I could possibly make this work without analyzer changes, but it'd end up sending a lot of requests (basically take the diagnostic from the quick fix, find all instances of it in that file, then send requests for fixes for them all and apply them together) but API changes would make it more efficient (I guess this is a similar request to #32462 but for fixes instead of assists).

**Comment by devoncarew** [comment]
A `fix all` operation sounds great! We have had requests for batch applying quick fixes, so this seems like a step in the right direction.

**Comment by bwilkerson** [comment]
Is this not implemented yet? There's certainly some support for it on the server side, but I don't know how far that support was taken.

**Comment by devoncarew** [comment]
/cc'ing @jwren who knows about it from the IntelliJ perspective (Jaime is OOO currently however)

**Comment by bwilkerson** [comment]
> However, it looks like each fix needs specific work ...

Correct. Sometimes the changes introduced by a fix are not additive. Consider, for example, the "define a method" fix for an undefined method invocation. If the same method name is invoked multiple times in a file it's important that the method is only defined once.

The simple lexical changes implemented by `dartfmt` don't have that problem because the changes are always localized.

**Comment by DanTup** [comment]
Good point - I guess in TypeScript there's probably some whitelist too then (I couldn't actually get it to give me a suggestion for creating a function now to test it - no idea why, I'm sure it used to support that!).

**Comment by HerrNiklasRaab** [comment]
Actually, this would bring tremendous benefits with relatively little work. Maybe prioritizing this, before adding new quick fixes.

**Comment by DanTup** [comment]
I recently raised https://github.com/dart-lang/sdk/issues/44258 which I guess is actually a dupe of that one. That one has a little more info about implementation (since it's now available in LSP, but not in the original protocol) so I'll close this one and keep that one open.
