### ISSUE TITLE
DDC "Uncaught ReferenceError: super$foo is not defined" when combining generics, export and async

### ISSUE THREAD

**Issue by tourn** [dart-lang/sdk#32471]
Using angular 4.0.0+2 with `pub serve --web-compiler=dartdevc` and dartdevc version 1.24.3

Combining generics, export and async like the following:

*lib/foo_public.dart*
```dart
export 'package:foo_app/src/app.dart';
```

*lib/src/app.dart*
```dart
import 'generic_thing.dart';

@Component(...)
class AppComponent {}
```

*lib/src/generic_thing.dart*
```dart
export 'child_thing.dart';

abstract class GenericThing<T> {
  Future foo() async { }
}
```

*lib/src/child_thing.dart*
```dart
import 'generic_thing.dart';

class ChildThing<T> extends GenericThing<T> {
  @override
  Future foo() async{
    super.foo();
  }
}
```

I get

```
Uncaught ReferenceError: super$foo is not defined
    at src__child_thing.ChildThing$.dart.generic.src__generic_thing.GenericThing$ (child_thing.dart:11)
    at Object.makeGenericType [as ChildThing$] (dart_sdk.js:1208)
    at ChildThing (lib__shared_0.js:11)
    at child_thing.dart:9
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
```
The problem appears to lie in the generated js [lib__shared_0.js](https://github.com/tourn/dart-dartdevc-issue/blob/55436f2e65f05ad9158d9ec6ad5c280a80698753/lib__shared_0.js#L34)

```js
  src__generic_thing.GenericThing$ = dart.generic(T => {
    const super$foo = Symbol("super$foo");                 //super$foo defined here
    //snip
    return GenericThing;
  });
  src__generic_thing.GenericThing = GenericThing();
  src__child_thing.ChildThing$ = dart.generic(T => {
    class ChildThing extends src__generic_thing.GenericThing$(T) {
      foo() {
        return dart.async((function*() {
          this[super$foo]();
        }).bind(this), dart.dynamic);
      }
      [super$foo]() {                                  // super$foo is not in scope
        return super.foo();
      }
    }
    return ChildThing;
  });
```

I created [a repo](https://github.com/tourn/dart-dartdevc-issue/tree/master) that reproduces the issue.
For convenience I added the generated [*lib__shared_0.js*](https://github.com/tourn/dart-dartdevc-issue/blob/master/lib__shared_0.js) that seems to be causing the issue. It seems to be resolved if any of these 3 things are changed:
* [`import` instead of `export` is used in *generic_thing*](https://github.com/tourn/dart-dartdevc-issue/commit/78deca78a074a3ef5045b36a84d84a44963dfe2c#diff-10e771992db0d7c9f117496f4c4638d2)
* [`async` is removed](https://github.com/tourn/dart-dartdevc-issue/commit/b8740a6ea9397c95bcc09418a7ffd3d2973a72e8#diff-10e771992db0d7c9f117496f4c4638d2)
* [generics are removed](https://github.com/tourn/dart-dartdevc-issue/commit/edae4cf8a2aabe115506ee235de22be17c158cbd#diff-10e771992db0d7c9f117496f4c4638d2)

**Comment by matanlurey** [comment]
Unfortunately DDC is/was experimental in the 1.24 (stable) branch, and there is likely bugs. The full implementation is only available in the 2.0.0-dev (dev) branch. Let us know if that works for you.
