### ISSUE TITLE
can't open this url 'https://www.dartlang.org/'

### ISSUE THREAD

**Issue by yangyudaddy** [dart-lang/sdk#32472]
can't open this url 'https://www.dartlang.org/'

**Comment by zoechi** [comment]
Which country are you from?
Does it still not work gor you? (works for me)

**Comment by matanlurey** [comment]
Hi @yangyudaddy.

If this problem persists, we will need more information:
* Your browser
* Your country
* Are you using a proxy of any kind

Thanks!

**Comment by yangyudaddy** [comment]
I use Google browser ,from China. Use a kind of VPN  ,and  I can Google but can't open .
