### ISSUE TITLE
JSON.encode w/ Maps with non-string keys fails badly.

### ISSUE THREAD

**Issue by stephanemagnenat** [dart-lang/sdk#32476]
Using DartPad from the library tour page with strong mode enabled, the following code generates a non-informative runtime error `Error:`:
```
import "dart:convert";

void main() {
  Map<int,List<String>> a = { 1: ["a", "b", "c"] };
  var jsonString = JSON.encode(a);
  print(jsonString);
}
```

After some investigation I realised that the error arose because I was using non-String key in the map passed to `JSON.encode()`. I assume that many other users might meet the same problem, and my resolution suggestion is to type the parameter to `JSON.encode` as `Map<String,X>` if that is allowed by the language.

**Comment by matanlurey** [comment]
`JSON.encode` definitely can be a non-Map (i.e. a `List`, for example).

We could coerce all keys to strings, or at minimum make the error better.

Thoughts @lrhn?

**Comment by stephanemagnenat** [comment]
Is it possible to overload `JSON.encode` for all valid types? Something like:
- `JSON.encode(Map<String,X>)`
- `JSON.encode(List)` (or some iterable)
- `JSON.encode(num)`
- `JSON.encode(String)`

That would not catch all errors (a `List<Map<int,X>>` would still be a problem) but at least it would narrow down the space of errors not caught at compile-time.

**Comment by matanlurey** [comment]
We don't have overloads. We could add specific methods, i.e,:
* encodeMap
* encodeList

Or we could use `is` checks to ensure the types are valid. I'll wait for @lrhn.

**Comment by lrhn** [comment]
JSON is dynamically inherently typed. That's probably a side-effect of coming from JavaScript.
A "json" values have any of the types `Map<String,"json">`, `List<"json">`, `num`, `String`, `bool` or `Null`. Dart does not allow you to describe such a recursive type.

We can add `encodeMap(Map<String, Object>)`, but that will only help you at the top level, it won't allow you to catch `encodeMap({"foo": {42: "bar"}});`. I'm not in favor of adding six more methods and still not fixing the actual problem. Patches on the side of an inherently dynamic API is not going to give you static typing. (We can't even guarantee that a `Map<String, String>` is JSON-encodable, one of the keys might be `null`, so static typing can't prevent all runtime errors).

I'd rather go for some kind of "JSON Conversion Scheme" that you can build programmatically, and then use as a codec for appropriately typed objects, so the programmer starts by describing the actual structure in as much detail as possible, then we can give you the static checking possible from that.

**Comment by stephanemagnenat** [comment]
Makes sense. If one day both non-null types and overloads are added, I guess the question could be revisited...

The error should be improved though, should I open another issue or change the title of this one?

**Comment by kevmoo** [comment]
Solution proposal: https://github.com/dart-lang/sdk/issues/35693

**Comment by lrhn** [comment]
No changes planned in this direction. If we do something for JSON it'll be more fundamental than tweaking the JSON encoder/decoder.
