### ISSUE TITLE
dart2js kernel strong: extra parameters on $signature

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32480]
sdk/bin/dart2js_developer --use-kernel --strong ~/play1/bug1a4u.dart --out=o3.js
[bug1a4u.dart.txt](https://github.com/dart-lang/sdk/files/1798420/bug1a4u.dart.txt)

The $signature method on enumerateLocal looks like:

```js
      $signature: function(source, fn) {
        return {func: 1, bounds: [P.Object, P.Object], ret: [P.List,,], args: [[P.Iterable, 0], {func: 1, ret: 1, args: [P.int, 0]}]};
      }
```

`(source, fn)` should be `()`.

With --checked, the extra arguments are checked too!

**Comment by efortuna** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/47662
