### ISSUE TITLE
coverage is broken because patched-in constructors are referring to the wrong script

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32489]
If you try to run flutter tests with coverage is crushes 

```console
$ cd examples/flutter_gallery
$ flutter test --preview-dart-2 --coverage /test/example_code_display_test.dart 
...
Bad state: Couldn't find line and column for token 7708 in dart:core/errors.dart.
00:39 +1 -1: loading /usr/local/google/home/vegorov/src/flutter/flutter/examples/flutter_gallery/test/example_code_display_test.dart [E]
```

Based on my preliminary analysis this happens because `kernel_loader.cc` does not do anything special for the patched-in constructors so coverage tries to locate position from `errors_patch.dart` in the `errors.dart` which does not work.

Give that it breaks coverage support I am marking this as P0.

**Comment by mraleph** [comment]
Please triage @kmillikin

**Comment by mkustermann** [comment]
@mraleph asked me to take a look, so I'll try!

**Comment by dgrove** [comment]
Can this be closed now?

**Comment by mkustermann** [comment]
After landing  60a2cfa2191bd52f799af538b84e77a5895b23c9 27bc090ca5d7f81a786168359ae5def71d4d232e 52c884dc6a4230c70759332e0ebc5204ac3dfae4 846d18414c73c131c0bf25311d751c10d000ff01 and finally aeee91ac5d295d0a38c9abf3efefcbf870d4a8b9 this issue should be fixed now.
