### ISSUE TITLE
Set up a repository for language/core library work

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32482]
Tracking issue for setting up a web presence for post Dart 2 language and core library work.  Items to consider:

- Roadmap
- Meeting notes
- Discussion issues
- Proposals (including strawman proposals)
- Archive/Log of breaking change announcements

cc @lrhn @mraleph @mit-mit @timsneath @dgrove @munificent

**Comment by matanlurey** [comment]
_Mild_ upvote for just `language` (`dart-lang/language` sounds nice to link to).

My next top pick is `evolution` (`dart-lang/evolution` also sounds nice to link to).

In any case, the brief summary is a huge 👍 👍 👍

**Comment by munificent** [comment]
All of the "dart-lang-" ones seem mostly redundant. If "core" without a prefix isn't on the table, then either "language" or "evolution" sounds good to me.

**Comment by kevmoo** [comment]
Let me know whichever – I have the keys.
