### ISSUE TITLE
Suggest symbol rename for `Name non-constant identifiers using lowerCamelCase` diagnostic

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32488]
Raised by @Phrohdoh at https://github.com/Dart-Code/Dart-Code/issues/682

----

Currently the only suggests are as follows:

<img width="302" alt="screen shot 2018-03-10 at 5 50 55 pm" src="https://user-images.githubusercontent.com/4861023/37248610-a1cc861c-248b-11e8-8b4f-d328419e2ca5.png">

It would be good to suggest something like...

> Rename to `apiQuote`

If we can generate the label dynamically.

If not:

> Rename using lowerCamelCase

**Comment by DanTup** [comment]
> If we can generate the label dynamically.

@bwilkerson @scheglov This is similar to my comment about the Flutter refactors. I think dynamic text is much better, since it gives the user more much confidence in what it's going to do (for ex. "Remove Widget" saying "Remove Column" is much clearer).

It reminds me a little of dialogs that have OK/Cancel buttons where you really read the text to check which way the logic is whereas if the buttons said "Yes, Delete" and "No, cancel" it's much simpler to understand exactly what you're telling it to do.

**Comment by bwilkerson** [comment]
We _do_ have a rename refactoring for use in cases like these. It probably won't suggest the name, but...

**Comment by scheglov** [comment]
We can generate messages to Quick Assist/Fix dynamically, with parameters.
The biggest question here is whether to use single quotes, double quotes, or no quotes at all :-)

`Rename to 'myIntegerVariable'`
`Rename to "myIntegerVariable"`
`Rename to myIntegerVariable`

![image](https://user-images.githubusercontent.com/384794/37492316-25b737da-285e-11e8-94cd-2e2f897e6388.png)

**Comment by bwilkerson** [comment]
To be consistent with diagnostic messages, we should use single quotes.

**Comment by DanTup** [comment]
No quotes looks better IMO, they don't really add anything. Ofc, if there are other similar fixes then we might want to be consistent with them.

**Comment by scheglov** [comment]
Thank you, Brian :-)

Yes, we put other names in Quick Fix messages in single quotes too, probably for the same consistency with error messages. So, single quotes it is.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/46822
