### ISSUE TITLE
search.getElementDeclerations doesn't include class constructors

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32495]
I've moved my document symbol provider over to the new `search.getElementDeclerations` API but it seems to be missing constructors that aren't named (named constructors appear fine).

![missing ctor](https://user-images.githubusercontent.com/1078012/37276336-52cbd7f8-25d9-11e8-9f6c-c060d2875346.png)

@scheglov

**Comment by bwilkerson** [comment]
Any preference for what the label ought to look like? I'd generally assume "MyClass() MyClass", but that seems a bit redundant and inconsistent with "named() MyClass". We could remove the inconsistency if named constructors also duplicated the class name, but that only increases the redundancy.

**Comment by DanTup** [comment]
@bwilkerson I struggled to come up with a good plan and hoped you'd have an idea! 😁

All of the options I can come up with seem wonky for one reason or another:

## Option 1
- `()` and `MyClass`
- `named()` and `MyClass`

## Option 2
- `MyClass()` and ``
- `MyClass.named()` and ``

## Option 3
- `MyClass()` and `MyClass`
- `MyClass.named()` and `MyClass`

TypeScript is a lame one to copy here, as it doesn't show parens/args for anything. What does your current IDE do (assuming it has some sort of symbol list or outline view)?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/46004

We will provide empty name, you can present it in the way you think is the best for users :-)

FWIW, IntelliJ includes the class name in names of constructors.
![image](https://user-images.githubusercontent.com/384794/37301273-5e731f74-25e5-11e8-956e-af2c359263fe.png)

**Comment by DanTup** [comment]
Great, thanks!

**Comment by bwilkerson** [comment]
Is there still work to be done here, or can this be closed?

**Comment by DanTup** [comment]
Yep, this is all done 👍
