### ISSUE TITLE
Flutter windows tests are showing a crash in kernel_binary.cc

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32491]
I have started an experimental CL to turn on the preview-dart-2 flag by default here https://github.com/flutter/flutter/pull/15372

This PR is showing some windows test crashing with an assertion in kernel_binary.cc
(please see https://ci.appveyor.com/project/flutter/flutter/build/1.0.10471)

```
⏩ RUNNING: cd dev\automated_tests; ..\..\bin\flutter.bat test test_smoke_test\fail_test.dart
83⏩ RUNNING: cd dev\automated_tests; ..\..\bin\flutter.bat test test_smoke_test\pass_test.dart
84Shell: e:\b\build\slave\windows_engine\build\src\third_party\dart\runtime\vm\kernel_binary.cc: 42: error: Invalid kernel binary: Indicated size is invalid.
85Shell: Stack dump aborted because no current Dart thread.
8600:00 +0 -1: loading C:\projects\flutter sdk\dev\automated_tests\test_smoke_test\pass_test.dart [E]
87  Failed to load "C:\projects\flutter sdk\dev\automated_tests\test_smoke_test\pass_test.dart":
88  Shell subprocess crashed with unexpected exit code -1073740791 before connecting to test harness.
89  Test: C:\projects\flutter sdk\dev\automated_tests\test_smoke_test\pass_test.dart
90  Shell: C:\projects\flutter sdk\bin\cache\artifacts\engine\windows-x64\flutter_tester

```

This could be related to the other crasher we are seeing in the incremental compiler.

**Comment by mraleph** [comment]
I will take a look. This might be related to general front-end issues on Windows.

**Comment by mraleph** [comment]
Underlying issue is in Garnet - it does not open binary files correctly on Windows causing them to arrive truncated into the VM. 

Fix is on review in Garnet: https://fuchsia-review.googlesource.com/c/garnet/+/131115

**Comment by aam** [comment]
Wow, nice @mraleph! How did it ever work though?

**Comment by dgrove** [comment]
https://fuchsia-review.googlesource.com/c/garnet/+/131115 is ready to submit.

**Comment by mraleph** [comment]
It's in the CQ now.

**Comment by mraleph** [comment]
I landed the fix in Garnet and rolled Garnet into Flutter.
