### ISSUE TITLE
Remove legacy mode from vm-kernel builders

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#32499]
@mraleph @a-siva @whesse
The VM team will no longer support --no-strong with the compiler dartk going forward. 

- [x] create a new builder: vm-kernel-legacy-linux-release (on CQ and CI) in the fasta group running a single step "vm legacy tests"
- [x] remove vm "no-strong" tests from vm kernel builder recipes
- [x] remove vm "no-strong" tests from vm kernel builders in test matrix
- [x] move vm kernel builders over to test matrix (removes selectors; tests will be Skipped in the status files instead; done for all except mac builders)

The first three steps should be landed at roughly the same time.

**Comment by a-siva** [comment]
test.py -cdartkp -rdart_precompiled will also imply --strong

**Comment by athomas** [comment]
Thanks, I've updated the description to reflect that.

**Comment by athomas** [comment]
To remove the test selectors, I will migrate the builders to Luci.

**Comment by athomas** [comment]
Blocked on #32603
