### ISSUE TITLE
Hot reload and anonymous closures (at least in toplevel fields)

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#32497]
On hot reload the kernel blob is updated but the anonymous closure isn't (and it points into the new kernel blob by an old offset).
Test that demonstrates on the VM available at https://dart-review.googlesource.com/c/sdk/+/46041

I'm pretty sure that's also what happens in https://github.com/flutter/flutter/issues/15214.

/cc @mraleph @rmacnak-google

**Comment by mraleph** [comment]
Ryan, can you take a look?

**Comment by rmacnak-google** [comment]
This sounds like PatchFieldsAndFunctions is somehow skipped for the top-level class.

**Comment by dgrove** [comment]
@rmacnak-google Can this issue be closed?
