### ISSUE TITLE
"can't have a part-of directive" with --preview-dart-2

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32498]
I get several
```
error: The imported library ''package:lookatmybaby_flutter/app_context.dart'' can't have a part-of directive. (import_of_non_library at [lookatmybaby_flutter] lib/app.dart:6)
```
```
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-AT)
    • Flutter version 0.2.0 at /Users/zoechi/flutter/flutter
    • Framework revision f8ac23cd86 (7 days ago), 2018-03-05 23:27:57 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68
```
I have `part`/`part of` in my built_value classes, but I don't import the parts, anywhere directly and the code worked fine so far.
The built_value classes are in an imported (shared) package.

When I disable `--preview-dart-2` in
![image](https://user-images.githubusercontent.com/405837/37282327-4fa05304-25f4-11e8-83d5-9ee2570a4fac.png)
the errors go away

**Comment by zoechi** [comment]
Actually Dart uses up all my memory until my machine gives in
![image](https://user-images.githubusercontent.com/405837/37283335-e1316a76-25f7-11e8-9870-fbd1546c1d18.png)

 an produces tons of useless errors like `Undefined name 'foo'`. Even when I go back to 2.0.0-dev.24.0 which worked well last week I'm not able to get rid of the errors. 
Using `--preview-dart-2` or not doesn't matter. 

With my comment above

> When I disable --preview-dart-2 in
> ...
> the errors go away

Just the one mentioned above goes away, and I just get different errors.

**Comment by zoechi** [comment]
Actually switching Dart version was useless, because it's a Flutter project, but switching Flutter version doesn't help either.
I switched to the `beta` channel, but I get the same behavior (huge memory use, tons of errors).

Switching Flutter channel doesn't seem to have an effect to the used Dart version.
```
 (beta) $ flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-AT)
    • Flutter version 0.1.5 at /Users/zoechi/flutter/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
```
this old version still has Dart dev.28

**Comment by zoechi** [comment]
I worked on the Angular UI the last 2 weeks, therefore it's a bit difficult for me to tell when exactly these problems started. I tried to run the Flutter app only a few days ago and there all was still fine.

**Comment by zoechi** [comment]
`flutter analyze` doesn't report any errors

![image](https://user-images.githubusercontent.com/405837/37285747-49adb692-2600-11e8-91e3-cce91eb078e8.png)

Looks like a plugin issue. I don't know when that was last updated.

**Comment by bwilkerson** [comment]
Just to clarify: which plugin do you suspect is an issue?

**Comment by zoechi** [comment]
@bwilkerson I meant the plugin that controls the analyzer. 
I guess it's the Dart plugin (or the Flutter plugin - don't know how they play together)

I created a new IntelliJ project that only includes the Angular UI package of my app and the shared package, but I still get the behavior that errors are shown for code that is fine and that memory usage goes up until the analyzer crashes and is restarted by IntelliJ (in an endless loop until I kill the `dart` task in the OS task manager or close IntelliJ)

**Comment by zoechi** [comment]
I this project (only Angular and Shared) switching back to Dart 2.0.0-dev.24 seems to solve the problem

**Comment by zoechi** [comment]
After switching to 2.0.0-dev.26 I got a dozen invalid errors shown like 
imported files not exporting specific identifiers

Deleting `~/.dartServer` fixed these invalid errors and the angular_analyzer_plugin started working again (didn't since a while)

**Comment by zoechi** [comment]
After switching to 2.0.0-dev.28 I again had to delete `~/.dartServer` to get rid of a bunch of invalid errors
![image](https://user-images.githubusercontent.com/405837/37346291-3eba845c-26cf-11e8-9990-a82370df020f.png)

**Comment by zoechi** [comment]
Update to dev.29 without problems

Upate to dev.30
![image](https://user-images.githubusercontent.com/405837/37346538-d9e6a1f4-26cf-11e8-93df-53407a0fb2e5.png)
deleting `~/.dartServer` fixed them

Update to dev.31 without problems

Update to dev.32 memory usage runs up unlimited (as mentioned before, but no wrong errors were shown)
deleting `~/.dartServer` fixes it (memory usage goes up to 624MB and stays there)

Update to dev.35
![image](https://user-images.githubusercontent.com/405837/37346783-99d0763e-26d0-11e8-9a03-fb90228dbb1b.png)
Memory usage only goes up to 350MB. After deleting `~/.dartServer` memory usage goes up to 624 again and stays there

**Comment by zoechi** [comment]
It seems this was all caused by the `~/.dartServer` cache. 
The IntelliJ project that contains Flutter, Angular, and Shared is working fine again now

**Comment by bwilkerson** [comment]
@scheglov I find it hard to imagine that the cache format has been changing with every new dev release, but I don't know what else would cause this kind of behavior. Any ideas?

**Comment by scheglov** [comment]
High memory usage happened most probably because of a problem in Angular plugin, we forgot to drain two streams. It was fixed several weeks ago.

I'm not aware of any change that would cause this library/part warning. We change data version sometimes, by other reasons.

**Comment by zoechi** [comment]
The library/part warning and all other false warnings and the high memory usage 
went away when I purged `~/.dartServer` anyway.

**Comment by bwilkerson** [comment]
Yes, that was my understanding. But the system ought not to have had that issue, and I'd like to try to ensure that it doesn't happen on every dev release by understanding what caused it.

**Comment by zoechi** [comment]
This doesn't seem to be an issue anymore.
