### ISSUE TITLE
[dartdevc] Handling of number type checks

### ISSUE THREAD

**Issue by jeroencranendonk-wf** [dart-lang/sdk#32506]
Using dartdevc version 1.24.3, the input `void main() { print(1.2 is int); }` outputs 'true' when run.

Dartdevc outputs the check as `typeof 1.2 == 'number'`, whereas dart2js uses `typeof 1.2 === "number" && Math.floor(1.2) === 1.2`.

**Comment by matanlurey** [comment]
Hi @jeroencranendonk-wf 

Unfortunately `dartdevc` in the stable (1.24) SDK is experimental, and will not be updated. The latest `dev` (2.0.0-dev) SDK is the latest. Please re-open if this problem persists at that point.
