### ISSUE TITLE
Document the expected format of file path uris when setting breakpoints on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32500]
I'm often investigating bugs relating to missed breakpoints on Windows in Dart Code and they're often caused by the format of paths being passed to the VM. Up until today, the format that seemed to work reliably was this:

`"/M:/Coding/Applications/Dart-Code/test/test_projects/hello_world/bin/main.dart"`

However today when running `flutter test` I noticed them being missed again. Seems that `flutter test` wants them in this form:

```js
"uri":"M:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\flutter_hello_world\\test\\hello_test.dart"
```

I could add this additional format, however since it's not a uri I'm concerned it might start being rejected at some point. I think it should be documented how I should send these (ideally in [this doc](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) but even just in this case would be useful) and considered a bug if the VM doesn't handle them.

**Comment by rmacnak-google** [comment]
The vm-service does not have an opinion on the format of file path URIs. It just looks for a match with some library's URI that was provided by the embedder, so this is likely an issue with the Flutter engine.

**Comment by DanTup** [comment]
Gotcha - I've moved this to https://github.com/flutter/flutter/issues/15513 then. Thanks!

**Comment by DanTup** [comment]
@rmacnak-google I think this original request here may still be valid. The fact that flutter test is behaving differently to flutter run and the Dart SDK is because there don't appear to be any documented rules about this. It doesn't make sense for each tool to have its own rules (editors need to know what format to send paths in for breakpoints and for parsing call stacks, etc.) so it seems like the format should be well-defined.
