### ISSUE TITLE
Fasta lacks constants evaluation

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#32517]
Fasta currently does not evaluate compile-time constant expressions. We have a prototype kernel-based constant evaluator and might decide to integrate that more universally in the future, but for the moment, constant evaluation is left to the individual backends to do (and report any associated errors).

Some compile-time checks depend on constant evaluation and thus can't be implemented in Fasta as it is. This issue works as an umbrella issue listing other issues related to such checks:

- #31936 constant expressions that throw should be a compile-time error
- #32557 CFE missing compile time error: const keys/switch cases should not implement ==
- #32912 CFE does not reject non-const partial instantiations for default parameter values
- #32983 Missing error on duplicated key in map literal
- #33869 A constant list can be used in a literal string, Is this expected? A contradiction to language tour
- #34175 CFE should not allow type literals which are not compile-time constants in default values of optional parameters
- #34189 All backends crash on recursive const expressions
- #34190 An overriding method can't specify a different default value
- #34191 When class has const constructor, field initializers must be const
- #34192 It is a compile-time error if actual parameters to const constructor result in invalid constant expressions
- #34204 Fasta does not detect circular constant expressions
- #34205 Static field access erroneously considered constant

Such issues should furthermore be marked with the label **requires-constant-evaluation**.

**Comment by sigmundch** [comment]
(reopened because we temporarily disabled the constant-update-2018 experiment)

**Comment by askeksa-google** [comment]
Constant evaluation is implemented but not yet enabled. Enabling it is covered by https://github.com/dart-lang/sdk/issues/36799
