### ISSUE TITLE
Spec: Static requirements on type annotations for initializing formals #30817

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32510]
This is the specification issue for the static restrictions specified in https://github.com/dart-lang/sdk/issues/30816 .

**Comment by leafpetersen** [comment]
Oops, never mind, I see the spec is already done.

**Comment by eernstg** [comment]
Ah, I forgot to mark it done. Here's the commit where it happened: https://github.com/dart-lang/sdk/commit/8562c8ff1bdcbdc43baed287f6979599a16ea386.
