### ISSUE TITLE
Missing implicit downcast in DDC for fields with override inferred types

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32515]
I believe the following code should have an implicit downcast on the initialization of the `messages` field:

```dart
abstract class A {
  final Map<String, int> messages;
}
class B extends A {
  final messages = foo();
  static foo() => {"hello": "world" as dynamic};
}

void main() {
  var b = new B();
  print(b.messages["hello"].isEven);
}
```

The analyzer seems to be correctly inferring the type of the `messages` in the subclass based on the override, but there seems to be no downcast inserted by DDC.

**Comment by jmesserly** [comment]
> The analyzer seems to be correctly inferring the type of the messages in the subclass based on the override, but there seems to be no downcast inserted by DDC.

Downcasts are the responsibility of the front end. In Analyzer checker.dart sets the "implicit cast" flag on the Expression, in Kernel the coercions are reified with AsExpression nodes.

So, most likely this is an Analyzer bug. From a quick look at CodeChecker.visitVariableDeclarationList in Analyzer, it doesn't seem aware that an inferred field is a possibility (it skips all checking if there was not a TypeAnnotation AST node present, which there is not in this case).

**Comment by bwilkerson** [comment]
@jmesserly I'm guessing that this is no longer interesting given that ddc will be moving to kernel soon. If that's true, could you please close this issue?

**Comment by jmesserly** [comment]
good catch. I tagged this bug to indicate that it will be fixed with Kernel. Not sure if we should close them until DDC is switched over (because until then, the bug exists)? I guess we could say "closed not planned"?
