### ISSUE TITLE
DartAnalyzer error

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32528]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b08x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1200, 3840x2160  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report1527.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.7, error: Analysis failed: /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/test/util.dart context: exception_20180314_131226_198
RangeError (byteOffset): Invalid value: Not in range 0..19532, inclusive: 1701686714
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4258)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      _FbList.length (package:front_end/src/base/flat_buffers.dart:845)
#3      new CompilationUnitElementInDependency (package:analyzer/src/summary/link.dart:1527)
#4      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:4065)
#5      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3871)
#6      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3910)
#7      _HashVMBase

**Comment by zoechi** [comment]
[report1527.txt](https://github.com/dart-lang/sdk/files/1810976/report1527.txt)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
The analysis cache is damaged, probably by using incompatible implementations of analyzer, which did not increment data version to prevent conflicting cache keys. You will need to clear `~/.dartServer/.analysis-driver`. Ideally you would update to the latest Dart SDK bleeding edge, to get a new analyzer, with incremented version, but I don't know your situation and if it is safe / compatible.
