### ISSUE TITLE
New analyzer code: Null-aware after non-null

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#32523]
Or something similar. While cleaning up existing NULL_AWARE_IN_LOGICAL_OPERATOR instances, I'm seeing a lot of code like this:

```dart
var foo = b && c?.d ?? false;
```

Precedence reveals that this statement is equivalent to:

```dart
var foo = (b && c?.d) ?? false;
```

which makes no sense. `p && q` is never null, so `??` doesn't make sense there. I'm not certain that this new code would be super useful when we now have NULL_AWARE_IN_LOGICAL_OPERATOR, but... probably?

CC @a14n

**Comment by bwilkerson** [comment]
I suspect that the author thought it would be equivalent to
```
var foo = b && (c?.d ?? false);
```

**Comment by srawlins** [comment]
The new Null Safety feature handles this code. "The left operand can't be null, so the right operand is never executed. • 32523.dart:4:28 • dead_null_aware_expression"
