### ISSUE TITLE
Add a mirror to github.com/dart-lang/browser

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32536]
Going to remove pkg/browser from the SDK repo

**Comment by athomas** [comment]
@kevmoo I know there has been a discussion related to this, is this still relevant?

**Comment by kevmoo** [comment]
I haven't seen motion on the other requests, so yes – please! :-)

**Comment by whesse** [comment]
Done.  The browser repo is created at dart.googlesource.com/browser, and changes to the
github dart-lang browser repo will be mirrored to it.

I ran (need to be an admin of dart.googlesource.com):
gob-ctl -deadline 300s < create_single_repo_command

where create_single_repo_command is
create {
  repo: "dart/browser"
  from: "github/dart-lang/browser"
  owner: { mdb_group: "dart-repo-team" }
  writer: { mdb_user: "gerritcodereview" }
  reader: { all: USERS }
}

copy {
  source: "github/dart-lang/browser"
  destination: "dart/browser"
  create {
    source_scope { all: USERS }
    destination_scope { mdb_group: "dart-repo-team" }
    add_refspec {
      source: "refs/heads/*"
      destination: "refs/heads/*"
    }
    add_refspec {
      source: "refs/tags/*"
      destination: "refs/tags/*"
    }
  }
}

**Comment by kevmoo** [comment]
Thanks for unblocking https://dart-review.googlesource.com/c/sdk/+/47580
