### ISSUE TITLE
pub build fails on 2.0.0-dev.37.0

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32547]
```
Dart VM version: 2.0.0-dev.37.0 (Wed Mar 14 18:26:36 2018 +0100) on "windows_x64"
```
**pubspec.yaml**
```yaml
name: bug
```

**lib\foo.dart**
```dart
final foo = true;
```

**web\main.dart**
```dart
import 'package:bug/foo.dart';

void main() {
  print(foo);
}
```

```
> pub get
Resolving dependencies...
Got dependencies!

> pub build
Loading source assets...
Building bug...
[Info from Dart2JS]:
Compiling bug|web/main.dart...
[Error from Dart2JS on bug|web/main.dart]:
Could not resolve the package 'bug' in 'package:bug/foo.dart'.
[Error from Dart2JS on bug|web/main.dart]:
package:bug/foo.dart: Not found: package:bug/foo.dart.
[Info from Dart2JS]:
Took 0:00:00.688748 to compile bug|web/main.dart.
Build failed.
```

**Comment by matanlurey** [comment]
This is likely due to the new frontend (/cc @sigmundch):
https://groups.google.com/a/dartlang.org/forum/#!topic/announce/cM0VWIK4HMU

@lexaknyazev please try adding the flag `--use-old-frontend`.

**Comment by lexaknyazev** [comment]
`pub build` works with 
```yaml
name: bug

transformers:
 - $dart2js:
     commandLineOptions: [--use-old-frontend]
```

**Comment by sigmundch** [comment]
I sent out a CL that will pass that flag from pub by default until we fix it the proper way. The CL is on the commit queue (https://dart-review.googlesource.com/c/sdk/+/46573), after it lands, I expect it will be released on the next .dev release (.dev.39).

Once you updrade to .39, you should be able to drop the extra option. I'll follow up here again once the option is removed and dart2js within pub is using the new frontend,

**Comment by lexaknyazev** [comment]
@sigmundch Given that `2.0.0-dev.39.0` fixes `pub` and has been published, should this issue be closed?

**Comment by sigmundch** [comment]
Yes, thank you.  Please remove the extra flag on your pubspec.

I was able to fix the underlying issue, so pub now is using the common front-end without hitting this issue.
