### ISSUE TITLE
Bogus prefer_const_constructors lint when using type arguments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32544]
```dart
class Test<T> { const Test(); }

Test<T> test<T>() => new Test<T>();

void main() {
  test<int>();
}
```
->
```
  lint • Prefer const with constant constructors at test.dart:3:22 • prefer_const_constructors
```
...but that's bogus, because if you actually use a const constructor here, it will fail at runtime since `T` isn't const.

**Comment by Hixie** [comment]
I just ran into this again.

**Comment by bwilkerson** [comment]
@a14n In case you're interested in looking at this. It should be fairly simple to check the invocation to see whether it has type arguments, and if so whether any of the type arguments are type parameters.

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1382
