### ISSUE TITLE
Consider eliminating noSuchMethod implementations from link.dart

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32552]
The summary linker in `pkg/analyzer/lib/src/summary/link.dart` contains a lightweight version of the element model.  In order to share code with the type inference engine, each of the linker's lightweight element classes has an `implements` clause pointing to the corresponding heavyweight element model class, and a `noSuchMethod` implementation to allow the lightweight model to implement only those methods needed at link time.

My strategy for fixing #32525 is to expand the lightweight element model to cover the needs of the ResolverVisitor class, so that the ResolverVisitor can be used to perform type inference rather than having a duplicate (buggy) implementation of type inference in the linker.  As I'm doing this, I'm finding that it's hard to have confidence in my code because only extensive testing can reveal which methods I need to add to the lightweight model to support the ResolverVisitor.  It feels like there's a significant danger of forgetting to add a method that is only used in a rare corner case.

As a lower priority code cleanup task, I'd like to try removing the `noSuchMethod` implementations from the linker.  This will probably require creating a set of reduced interfaces capturing which element model methods are needed during linking, and refactoring the resolver (and other code used by the linker) to use these reduced interfaces.

Note: an alternative fix would be to merge the linker's lightweight element model with the full element model, and adapt the resynthesizer so that it can do the type of resynthesis needed for linking.  However, considering that the new front end is likely to make a lot of this code obselete, I don't think it's worth embarking on such a large refactor.

**Comment by scheglov** [comment]
I removed all duplicate element model implementations after implementing summary2.
