### ISSUE TITLE
CFE missing compile time error: const keys/switch cases should not implement ==

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32557]
The spec doesn't allow const values that implement `==` to be used as keys in const maps, or as cases on switch statements. 

The CFE is currently not producing a compile-time error for it. 

Here is an example:
```dart
class A {
  final x;
  const A(this.x);
  operator==(y) => x < y.x;
}

const one = const A(1);
const two = const A(2);

const map = const {one: 1, two: 2};

main() {
  print(map[one]);
  print(map[two]);
  print(one == two);
}
```

Then:
```
> dart a.dart
'/a.dart': error: line 11 pos 20: key value must not implement operator ==
const map = const {one: 1, two: 2};
                   ^

> dart --preview-dart-2 a.dart
2
null
true
```

I wanted to file a bug for this issue because it accidentally hides a problem in dart2js, that `Type` cannot be used in these const contexts (see https://github.com/dart-lang/sdk/issues/17207), the sooner we handle this, the lower the chance we'll make a breaking change later on.

**Comment by lexaknyazev** [comment]
While it's clear why an arbitrary class implementing `operator ==` cannot be used as a compilation-time constant key, could `TypeImpl` be a special case? It uses a string `_typeName` which seems to be unique for each class (even when actual class names collide).

**Comment by dgrove** [comment]
With -dev.59, the Dart Analyzer produces these errors:

Analyzing /usr/local/google/home/dgrove/tmp/dart2stable/32557.dart...
  error • The constant map entry key expression type 'A' can't override the == operator at tmp/dart2stable/32557.dart:10:20 • const_map_key_expression_type_implements_equals
  error • The constant map entry key expression type 'A' can't override the == operator at tmp/dart2stable/32557.dart:10:28 • const_map_key_expression_type_implements_equals
2 errors found.

**Comment by sigmundch** [comment]
@askeksa-google - I believe this issue doesn't require constant evaluation, but only requires checking the type of the keys in a const map literal context.

**Comment by a-siva** [comment]
The Dart VM does not produce any error on the above test.

**Comment by sigmundch** [comment]
after some discussion at our dart2js meeting - I recognize that some const evaluation is needed, as a ternary expression yielding an Object as a LUB type would hide the issue.

**Comment by johnniwinther** [comment]
Also if the switch case expression is a reference to a constant of static type dynamic, like `const dynamic t = Object`, do we need to evaluate the constant to catch all cases.

**Comment by sigmundch** [comment]
Circling back to the original bug:
 * dart2js now has a workaround implemented that will check for `operator==` in switch cases.
 * we intend to delete it once the CFE implements the same feature, but we'll need a hook to add an exception to the rule.

In dart2js types are not canonicalized, so our TypeImpl implements `operator==`. However, type literals are constants and we do canonicalize them correctly, so most users will not encounter issues using type literals in switch cases. 

Because all other tools do allow Type in switch cases, the dart2js-team is inclined to omit the error in the case of TypeImpl. Instead we'll treat this as a bug: types should be canonicalized in dart2js. We have plans to fix that, but until we do, we will need a way to suppress the error when the CFE implements it.

**Comment by lrhn** [comment]
The issue with using type literals in switch cases is that you cannot use `identical` for comparison.
Example:
```dart
main() {
  var type = (<T>() => (<X>() => X)<List<T>>())<dynamic>();  // generates List<dynamic> dynamically.
  print(type == List ? "List<dynamic>" : "Not List<dynamic>");
  switch (type) {
    case List: print("List<dynamic>"); break;
    default: print("Not List<dynamic>");
  }
}
```
If you run this code in dartpad (some version of dart2js), it runs and prints:
```
List<dynamic>
Not List<dynamic>
```
That's unlikely to be what the user intends.

**Comment by sigmundch** [comment]
@lrhn are you suggesting that switches on Type should always be a compile-time error? Or that switch statements should use `==`?

**Comment by eernstg** [comment]
Discussions are ongoing, it might be allowed. But the current specification prevents case clauses from using objects with a concrete `==` operator that overrides the one in `Object`, so it is currently an error (even for an identifier/typeName which is a constant expression of type `Type`). It seems to be an unenforced one, so we have usages out there.

PS: Switch statements are already specified to use `==` (search 'Matching of a case clause' in the spec), and this has been true at least since 59611b2414f, 2013-10-07.

**Comment by kmillikin** [comment]
This should be fixed by `constant-update-2018`, but I still see some test status file entries with this issue number so it needs verification.  (Perhaps we do not catch the switch cases?)

**Comment by askeksa-google** [comment]
Yeah, the `switch` checks are not implemented. These fall in the category of "subsequent checks" which will require some Kernel format changes to support fully.

**Comment by kmillikin** [comment]
This depends on CFE constant evaluation and doesn't block it (constant evaluation).

**Comment by rakudrama** [comment]
Some updates:
- dart2js has a new `Type` implementation for which `==` is `Object.==`. 
- CFE seems to implement the error

@johnniwinther can you confirm that the CFE checks are complete?

**Comment by johnniwinther** [comment]
These checks have all been implemented.
