### ISSUE TITLE
turn on --preview-dart-2 to be default for the analysis server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32566]
This is the default for `flutter analyze`, `flutter run`, ...; the analysis server results are now inconsistent in the current master version of Flutter. We should flip the default for the analysis server to eliminate --preview-dart-2 skew issues.

**Comment by bwilkerson** [comment]
If we flip the default for the analysis server, then it also flips the default for non-Flutter packages, which will cause skew for a different set of users. Are we really ready to do that?

**Comment by zoechi** [comment]
Is there currently a way to enable `--preview-dart-2` in `analysis_options.yaml`?

**Comment by dgrove** [comment]
Yes - see
https://github.com/flutter/flutter/issues/14806#issuecomment-367463282

**Comment by devoncarew** [comment]
Landed: https://dart-review.googlesource.com/c/sdk/+/47122
