### ISSUE TITLE
Analyzer reports -0x8000000000000000 as not representable as 64-bit integer.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32585]
```
ERROR|COMPILE_TIME_ERROR|INTEGER_LITERAL_OUT_OF_RANGE|c:\\src\\dart\\sdk\\tests\\corelib_2\\bigint_from_test.dart|21|12|18|The integer literal -0x8000000000000000 can't be represented in 64 bits.
```
(reported on CL [46460](https://dart-review.googlesource.com/c/sdk/+/46460)).

Since that number is representable as a 64-bit signed integer, the analyzer is wrong.

**Comment by lrhn** [comment]
Hit me again. Please consider increasing the priority.

**Comment by lrhn** [comment]
And again.

**Comment by jmesserly** [comment]
Should be fixed in https://dart-review.googlesource.com/c/sdk/+/63023
