### ISSUE TITLE
BigInt on dart2js has bug in toString.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32589]
Example:
```dart
main() {
  var x = -36028797018963970;
  print(x);  // -36028797018963970
  print(new BigInt.from(x)); // -36028797018963968  ??
  print(new BigInt.from(x).toInt());  // -36028797018963970
}
```

**Comment by lrhn** [comment]
Also affects DDC when compiled with Kernel (analyzer fails the test for another reason), so it's probably a JS number loosing precision.

**Comment by rakudrama** [comment]
`-36028797018963970` and `-36028797018963968` are the same IEEE 754 double bit pattern.

The closest value is `-(2^55)`, which is `-36028797018963968`
So the BigInt results it correct, and the toString of the int value in 'incorrect' but cannot be fixed.

The formatting of double and int values has to be the same (we can't tell if a `dynamic` or `num` value represented by a JavaScript Number is an int or a double), so int values outside the effective 53-bit precision of the mantissa are formatted as the 'prettiest' number, which has the shortest string of non-zero digits. This prefers xxx70 over xxx68.

What we can do is issue a compile-time warning or error that `36028797018963970` cannot be represented precisely when compiling to JavaScript.

**Comment by lrhn** [comment]
Ack, my bad. It's very confusing when the `double.toString()` is an integer and it's still not the exact value :)
