### ISSUE TITLE
dart:html - add support Navigator.mediaDevices

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#32595]
all I can see is `//untriaged` in `html_dart2js.dart`. Am I correct assuming that what it means is that it's not supported currently?

I could use these features.

**Comment by kevmoo** [comment]
@daniel-v – have you tried using this API? Which version of Dart?

What doesn't work?

https://api.dartlang.org/dev/2.0.0-dev.43.0/dart-html/Navigator/mediaDevices.html

**Comment by kevmoo** [comment]
@daniel-v – this might help, too - https://github.com/dart-lang/sdk/issues/32595

**Comment by natebosch** [comment]
We have `Navigator.mediaDevices`, but it looks like we are missing some APIs on `MediaDevices`. Closing in favor of https://github.com/dart-lang/sdk/issues/35253
