### ISSUE TITLE
Remove build/serve from pub

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32593]
This is a tracking issue that will coordinate with specifics in the pub repo, etc.

- [x] Send announcement to `dart-announce@`, etc - @kevmoo owns - https://groups.google.com/a/dartlang.org/forum/#!topic/announce/R4kV3us0Sm8
- [x] Land removal in pub repo. Landed at https://github.com/dart-lang/pub/commit/5ca86eb6e7be45ade4e44cbb7402d296cdf8b32f
- [x] Blocked by Observatory moving away from `pub build` - https://github.com/dart-lang/sdk/issues/32900
- [ ] Update DEPS to include pub w/ build/serve removed
- [ ] Email `announce@`

**Comment by dgrove** [comment]
Can you add specific issues for this?

**Comment by kevmoo** [comment]
> Can you add specific issues for this?

Done!

**Comment by natebosch** [comment]
Blocked by https://github.com/dart-lang/sdk/issues/32900

**Comment by kevmoo** [comment]
> Blocked by #32900

Now closed...

**Comment by kevmoo** [comment]
Closed in 94f45c8876 – thanks @natebosch !
