### ISSUE TITLE
Sample about renaming a file is incorrect.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32591]
The Dart by Example cookbook [Renaming a file, directory, or symlink](https://www.dartlang.org/dart-vm/dart-by-example#renaming-a-file-directory-or-symlink) states that the `File` object changes path when you rename the file. That is not correct, the `File` object is immutable and doesn't change.

See also https://stackoverflow.com/questions/49352149/

**Comment by Herohtar** [comment]
Per the response to https://github.com/dart-lang/site-www/issues/685, they're not maintaining the cookbook anymore, but the example code does exist in the [dart-samples](https://github.com/dart-lang/dart-samples) repository. I submitted https://github.com/dart-lang/dart-samples/pull/109 to fix it.

**Comment by srawlins** [comment]
Er, samples is dead. Close?
