### ISSUE TITLE
Hot reload benchmarks to measure TimetoFirstFrame 

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#32598]
(Asiva) hot reload benchmarks to measure TimetoFirstFrame for hot reload after a change.

Description:  hot reload performance needs to be examined further (maybe we should have a "total time" benchmark for initial hot reload, empty hot reload, and hot reload with changes, since apparently our current numbers aren't representative of the entire round-trip)

**Comment by a-siva** [comment]
We already have a benchmark that measures TimeToFirstFrame for an initial reload without any changes, (please see hotReloadMillisecondsToFrame).
Another benchmark hotReloadMillisecondsToFrameAfterChange needs to be added.
