### ISSUE TITLE
[meta] Full Dart 2 support in Dartpad

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#32606]
- [x] Dart2 support in Dartpad frontend: https://github.com/dart-lang/dart-pad/pull/801
- [x] Dart2 support in Dartpad backend: https://github.com/dart-lang/dart-services/issues/337

**Comment by mit-mit** [comment]
cc @devoncarew @jakobr-google anything else we need to add here?

**Comment by devoncarew** [comment]
We may need an issue for an opt-out checkbox in dartpad, depending on when the backend change lands.

**Comment by dgrove** [comment]
dart2js won't be ready for this until Dart2 Beta 4.

**Comment by dgrove** [comment]
(this will be close, but isn't a requirement for Dart2Beta4)

**Comment by dgrove** [comment]
We should wait for dart2js to have strong mode fully working - that should
happen very soon.

**Comment by vsmenon** [comment]
Right.  Is there any work here beyond a green light from Dart2JS?  Do we get this for free once Dart2JS defaults to Dart 2?

**Comment by dgrove** [comment]
It will need to be pushed to the backend at that point.

**Comment by sigmundch** [comment]
dart2js update: the last blocking feature has landed in master, woohoo! As soon as a new dev release is cut, we should be able to use it in dartpad. Dart 2.0 is still not on by default, so you'd need to pass `--preview-dart-2` to the compiler

**Comment by devoncarew** [comment]
> Do we get this for free once Dart2JS defaults to Dart 2?

This will require some work on the backend; that can happen even before the latest dart2js version is available in the dev channel.
