### ISSUE TITLE
Update Safari bots

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#32605]
Safari bots are using Safari version 9.1 (March 2016).  We should update the bots to be on Safari 11.03 (Jan 2018).  My results from local tests are:

lib_2/html:  One new failure (I suspect the test has to be fixed) and 7 tests pass (these were failing after the recent Chrome 63 roll).

For co19 tests (43 tests fail) and (107 failures now succeed) - all the failures from the Chrome 63 commit now pass.

https://clicky.com/marketshare/global/web-browsers/safari/

Looks like 9.1 is at 0% global usage.

**Comment by athomas** [comment]
All macs were upgraded not that long ago.
