### ISSUE TITLE
Need bot support for `--no-preview-dart-2` to preserve coverage

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32609]
We need to flip the default value for `--preview-dart-2` in the command-line analyzer later this week (it's already been done for the analysis server). The command-line analyzer supports `--no-preview-dart-2`.

However, when we do flip it, it will cause all of the bots (as they are currently configured) to start running in `--preview-dart-2` and we won't have any coverage for the `--no-preview-dart-2` case.

We already have bots that explicitly pass the `--preview-dart-2` flag. Please add the `--no-preview-dart-2` flag added to the bots that don't explicitly have this flag so that their behavior doesn't change when we change the default.

**Comment by athomas** [comment]
- [ ] Add --no-preview-dart-2 to test.py
- [] Migrate analyzer builders to Luci (optional, but nice)
- [] Add --no-preview-dart-2 to the relevant test matrix steps
- [] Remove --preview-dart-2 when the analyzer default is flipped

**Comment by athomas** [comment]
The infrastructure aspect of this is done and the remaining test matrix changes should be very easy to do. Re-assigning this to the analyzer team. Let me know if you need further assistance.

**Comment by ezrasandzerbell** [comment]
@athomas Several flutter devs I've spoken to are encountering an error where Flutter Update installs Dart 2 and their existing code breaks. We've solved this by adding --no-preview-dart-2 to flutter run. Is this is a sustainable solution? Can you forward any existing conversation / documentation about what to expect in the coming months? Do we need to re-write our code or is this a bug in the new Flutter version?

**Comment by athomas** [comment]
@ezrasandzerbell This change is unrelated to Flutter even if the flags have the same name. Please file an issue in the flutter repo instead. I'm not actually on the Flutter team, but I found this on the Flutter wiki: https://github.com/flutter/flutter/wiki/Dart-2-Migration

**Comment by bwilkerson** [comment]
@devoncarew I don't know whether this was ever completed, but I believe that we no longer need it. I'm closing it, but feel free to re-open it if I'm wrong.
