### ISSUE TITLE
_CastListBase.sort does not provide default comparator like List.sort

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32610]
Invoking `_CastListBase.sort()` without comparator throws an error which is unexpected.

**Comment by lrhn** [comment]
True. The `CastList` sort method wraps the incoming comparator, but it forgets to check for `null`. That means that it doesn't pass `null` on.

**Comment by leafpetersen** [comment]
Moving to beta-4, since this is presumably a non-breaking fix?

**Comment by lrhn** [comment]
Fix has landed: 41264590256de42c68de406fc180e338efc9420d
