### ISSUE TITLE
Implement NSM forwarding in the VM

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32628]
Task for NSM-forwarding implementation on all backends: #31426
Task for NSM-forwarding implementation in CFE: #31424 

We plan to re-purpose the existing NSM-dispatcher machinery used for optimizing NSM calls.

**Comment by sjindel-google** [comment]
Actually, I'll leave this open until some rather important cleanup is done.

**Comment by a-siva** [comment]
Is the cleanup going to happen for the dart2 Beta 3 milestone, if not I would remove the milestone label or move it to the next milestone.

**Comment by sjindel-google** [comment]
The cleanup has already happened.
