### ISSUE TITLE
double check AudioScheduledSourceNode.start

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32624]
1.24: https://api.dartlang.org/stable/1.24.3/dart-web_audio/AudioBufferSourceNode/start.html
-dev.40: https://api.dartlang.org/dev/2.0.0-dev.40.0/dart-web_audio/AudioScheduledSourceNode/start.html
Mozilla: https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start

This change broke https://travis-ci.org/bp74/StageXL/

**Comment by terrylucas** [comment]
Ok, there were some tests in co19 and some other source code that used the start signature from AudioScheduledSourceNode those tests might be a bit old that were using
the AudioScheduledSourceNode interfaces method
    void start(optional double when);

Now that Chrome defines AudioBufferSourceNode extends AudioScheduledSourceNode I'll change AudioScheduledSourceNode start  method to start2.

**Comment by terrylucas** [comment]
Fixed with [CL](https://dart-review.googlesource.com/c/sdk/+/47760).

**Comment by terrylucas** [comment]
Committed 17a778c9cba41b601660ac38020d7fdaf69ee090

**Comment by kevmoo** [comment]
Why do we need start2? They are just optional args, right?

**Comment by terrylucas** [comment]
Because they are in two different interfaces and both interfaces are in one
interfaces.

**Comment by terrylucas** [comment]
AudioScheduledSourceNode is inherited by ConstantSourceNode
and OscillatorNode so they only support the 1 param start
However, AudioBufferSourceNode inherits AudioScheduledSourceNode which has
both starts are there.

**Comment by terrylucas** [comment]
Here's the Chrome Bug
<https://bugs.chromium.org/p/chromium/issues/detail?id=824780&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=>
I
filed they should fix their WebIDL files.
