### ISSUE TITLE
Type alias `Type` equality

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32625]
Dart only supports obtaining a `Type` representing a generic function type via a type alias. In particular, we cannot use the following standard device:

```dart
class TypeValue<X> {
  Type get type => X;
}

Type listOfInt = new TypeValue<List<int>>().type;
```

A device like `TypeValue` is needed here because `List<int>` cannot (syntactically) be used as an expression (so we can do `var foo = listOfInt;` but we cannot do `var foo = List<int>;`).

However, we cannot obtain a `Type` representing a generic function type:

```dart
Type myFunctionType = new TypeValue<X Function<X>(List<X>)>().type; // Error!
```

The reason why this fails is that it uses a generic function type as an actual type argument, and that is not supported in Dart. (It may push up the complexity of type inference, probably making it undecidable).

The problem I've encountered is that there is no way to test for equality of types using such a type alias, because type aliases test equal to themselves only, even in the situation where the body of two type aliases are the same type.

```dart
// Stuff declared in some other library which will deliver a generic function type.
typedef _GenericType = X Function<X>(List<X>);
Type complexComputation() => _GenericType;

// This is my code, I can declare `MyType` because I know which type I want to test for.
typedef MyType = X Function<X>(List<X>);

// Now try to recognize the type denoted by `MyType` when obtained from "elsewhere".
main() {
  Type t = complexComputation();
  if (t == MyType) {
    // Ah, lucky, it was `X Function<X>(List<X>)`!
    ...
  } else {
    // OK, we don't know that type, error handling or slow path or ...
    ...
  }
}
```

The point is that we simply cannot recognize `X Function<X>(List<X>)` unless we can standardize with the provider of the `Type` value that it is defined via a specific `typedef`. So we never get to run the 'lucky' code above!

That looks like a gratuitous loss of expressive power. It's OK that a type alias gives rise to a different printout in error messages and such, but I do think that it's more useful to use the underlying value of a type alias for the `==` checks. Note that a "type alias" is carefully specified to be an alias rather than a nominally distinct type; for instance, `typedef`s do not admit recursion, and the declared type gets all its subtype relationships etc. directly from expanding the type alias name to the type alias body.

The concrete setting where this prevents us from supporting generic function types as far as we otherwise could is the package reflectable.

So this is a request to ensure that `t == MyType` above evaluates to `true`, such that `Type` values for generic function types can be used as such, rather than being "fresh" (and opaque) values for each `typedef`.

**Comment by lrhn** [comment]
I thought that was already decided, and it should definitely be so. I believe we have bugs tracking this issue, e.g. #31359. The arguments there apply equally to generic function types.

Function types are *structural*, not nominative, so it shouldn't matter how a function type `Type` object is created, it should be equal to `Type` objects for the same structural type. It should even be up to alpha-equivalence of the type parameters for generic function types.

(As an aside, it would be "nice to have" if we allowed local typedefs inside functions, instead of requiring you to hoist them to top-level. I'd even accept static typedefs inside class declarations, if that makes sense).

**Comment by eernstg** [comment]
Cool! Closing as duplicate of #31359 and taking that to be evidence of a decision that type aliases should be transparent at the `Type` level and, hence, `t == MyType` should evaluate to true in the example above.
