### ISSUE TITLE
Add a builder tag to the optcounter-threshold bots

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#32627]
The bots:
vm-linux-release-ia32-optcounter-threshold-be
vm-linux-release-x64-optcounter-threshold-be

Should pass a builder tag to test.py so that status files can indicate test statuses that are specific to those configurations. Status files already indicate 'builder_tag == optimization_counter_threshold' in a few places, but that builder tag doesn't appear to be passed to test.py on any bot.

@athomas Is there some test matrix .json file that we could update manually to accomplish this?

**Comment by whesse** [comment]
Yes, the tools/bots/test_matrix.json file.  Just search for "optimization", and add the flag to the same test step.

**Comment by athomas** [comment]
builder-tag: optimization_counter_threshold
