### ISSUE TITLE
dart2js: use source locations on the users disk for sdk sources.

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32633]
When using the CFE, dart2js generates invalid source-map locations for SDK libraries. These don't point to a valid location in the user machine, but instead, they point to locations of the buildbot machine. This is because we precompile the sdk into a platform.dill file on the buildbots.

With the old frontend, we compiled the sdk from sources on the user's machine, so we correctly reported the location of the user's SDK in the source-maps.

**Comment by sigmundch** [comment]
Some possible ideas to solve this problem:
* don't use platform.dill, but always compile from sources. This could be an OK stopgap measure, but I honestly don't support this idea.
* rewrite the location in dart2js. For example, when we invoke `compile_platform`, we could add a special file-system so that all sdk references are within a custom URI domain, then we resolve these custom-uris on the user machine once we know the location of the sdk.

@peter-ahe-google @johnniwinther  - thoughts?

**Comment by nex3** [comment]
FYI this is breaking `test` package tests.

**Comment by johnniwinther** [comment]
Platform (and package) resources should use a special scheme in the resource URI. 

For instance `dart:core/object.dart` for the `core/object.dart` file in the library root folder and `dart:lib/_internal/js_runtime/lib/io_patch.dart` for the patch found in the `lib/_internal/js_runtime/lib/io_patch.dart` file in the library root folder.

Similarly package resources should use a URI like `package:foo/src/bar.dart` for the `src/bar.dart` file in the folder where `package:foo` is located.

**Comment by peter-ahe-google** [comment]
A user of the front-end has complete control over what file names are used.

I strongly disagree that you should be replacing file URIs with package URIs.

The user needs both, and we're working on making both URIs available in the Source object. See https://dart-review.googlesource.com/c/sdk/+/47442.

**Comment by johnniwinther** [comment]
Having both URIs (the abstract and the concrete) is better.

**Comment by sigmundch** [comment]
On the FE side, I agree with the proposed changes to use Source so we can get both. On the dart2js side we will leverage both on our error reporting. 

However, to address the original problem in source-maps: we need to emit a URI that will work for tools consuming the source-map files (e.g. the browser debugger). For that, we need to emit file:// URIs to the corresponding source files on disk.

Today the .dill file contains URI of this form: `file:///b/build/slave/dart-sdk-linux-dev/build/sdk/sdk/lib/async/zone.dart `. This URI is not useful to our users (the buildbot path is irrelevant to them). We could replace the "/b/build/slave/dart-sdk-linux-dev/build/" portion, but that feels brittle/hackish to me. So I propose 2 changes:
  * invoke compile_platform with a custom file system, so we get URIs of the form: `org-dartlang-sdk:///lib/async/zone.dart`
  * when emitting source-maps in dart2js, resolve the URIs based on the user's sdk, so we emit: `file:///usr/path/to/their-dart-sdk/lib/async/zone.dart`.

Using the `org-dartlang-sdk` scheme will help us make the platform.dill files agnostic of what machine was used to build them.

**Comment by dgrove** [comment]
@vsmenon @sigmundch this looks like it should move to Dart2Stable?
