### ISSUE TITLE
dart --help should list --enable-asserts as it is being decoupled from --checked in --preview-dart-2 mode

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32646]
In Dart 2-dev.40 we still have the --checked flag.

Is this going away?

Will it become an alias for `--enable_asserts`?

Our IDE tools need to make plans here.

```console
$ dart --help
Usage: dart [<vm-flags>] <dart-script-file> [<dart-options>]

Executes the Dart script passed as <dart-script-file>.

Common options:
--checked or -c
  Insert runtime type checks and enable assertions (checked mode).
```

**Comment by kevmoo** [comment]
CC @jwren @anders-sandholm @dgrove

**Comment by jwren** [comment]
I like `--enable-asserts`, but I don't have a strong preference.

**Comment by a-siva** [comment]
We already have --enable-asserts and it works with --preview-dart-2 option.

**Comment by kevmoo** [comment]
@a-siva – reopening. I want to use this to track the plan around removing `--checked` and moving `--enable-asserts` "above the fold" when you run `dart --help`

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/commit/42581e4fa6a2dd91ab16b4b7a820f57ca3ad3b19 should fix this
