### ISSUE TITLE
Homebrew (mac) installer should not install dartium and/or content-shell with -dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32642]
They are more than broken.

Something needs to be changed here: https://github.com/dart-lang/sdk/blob/26c06cdd825fb22990768fcf5c4ffb753a4ccd62/tools/apps/update_homebrew/lib/update_homebrew.dart#L112

@nex3 – any ideas how to do this cleanly-ish w/ Ruby?

**Comment by kevmoo** [comment]
...at a minimum we should warn folks...

**Comment by nex3** [comment]
This is less a Ruby question and more of a Homebrew API question, which I'm unfortunately not very familiar with.

**Comment by kevmoo** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/48000
