### ISSUE TITLE
VM: mirrors: missing annotations on inherited members with --preview-dart-2

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32643]
It appears that mirrors support is incomplete when the `--preview-dart-2` flag is passed to the vm. In particular, inherited members appear to not have any metadata.

To reproduce, execute the following from the root of the sdk checkout:
```
dart --preview-dart-2 pkg/analyzer/test/src/task/strong/inferred_type_test.dart
```
It will fail several tests, but all of those tests are annotated with the `@failingTest` annotation. The annotation is used by the `test_reflective_loader` package to mark tests that are expected to fail. The problem is that the reflected methods do not have any annotations associated with them. I suspect that this is because the methods are defined in a superclass.

To see this in the debugger, place a breakpoint in `sdk/third_party/pkg/test_reflective_loader/lib/test_reflective_loader.dart` on line 122. This is the point at which the presence or absence of the annotation is about to be tested. Execute until the member name is `test_circularReference_viaClosures`. If you inspect the result of executing `memberMirror.metadata` (which is what the code will do if you step into a couple of methods), you should see an empty list, even though the method has an annotation. (You can confirm the annotation by opening `sdk/pkg/analyzer/test/src/task/strong/inferred_type_test.dart` to line 388.)

This is blocking me from getting the analyzer tests to pass when passing `--preview-dart-2` to the VM.

**Comment by joeconwaystk** [comment]
Found a similar issue where method parameters do not retain their metadata. The following prints the empty list, when it should be a single element list containing `override`.

```dart
import 'dart:mirrors';

void main() {
  final m = reflectClass(T).declarations[#f] as MethodMirror;
  m.parameters.forEach((p) {
    print("${p.simpleName} -> ${p.metadata}");
  });
}

class T {
  void f(@override int x) {}
}
```

**Comment by kmillikin** [comment]
@rmacnak-google are you sure this is a Kernel issue?  It looks to me like the annotations are where I'd expect them, for example:

```dart
class InferredTypeTest extends self::_InferredTypeTest&AbstractStrongTest&InferredTypeMixin {
  // [snip]
  @tes::failingTest
  @core::override
  method test_circularReference_viaClosures() → void {
    super.{self::InferredTypeMixin::test_circularReference_viaClosures}();
  }
  @tes::failingTest
  @core::override
  method test_circularReference_viaClosures_initializerTypes() → void {
    super.{self::InferredTypeMixin::test_circularReference_viaClosures_initializerTypes}();
  }
  @tes::failingTest
  @core::override
  method test_instantiateToBounds_typeName_OK_hasBound_definedAfter() → void {
    super.{self::InferredTypeMixin::test_instantiateToBounds_typeName_OK_hasBound_definedAfter}();
  }
  @tes::failingTest
  @core::override
  method test_unsafeBlockClosureInference_functionCall_explicitDynamicParam_viaExpr1() → void {
    super.{self::InferredTypeMixin::test_unsafeBlockClosureInference_functionCall_explicitDynamicParam_viaExpr1}();
  }
  @tes::failingTest
  @core::override
  method test_unsafeBlockClosureInference_functionCall_explicitTypeParam_viaExpr1() → void {
    super.{self::InferredTypeMixin::test_unsafeBlockClosureInference_functionCall_explicitTypeParam_viaExpr1}();
  }
}
```
But it does look like the VM is just peeking at the annotations to look for a few specific ones and skipping all the rest (I'm looking at the loop over `annotation_count` in `KernelLoader::LoadProcedure` with all the calls to `builder_.SkipExpression`).

**Comment by kmillikin** [comment]
What I said isn't quite right.  Annotations are added to the function at the very end of `LoadProcedure`.

**Comment by kmillikin** [comment]
This actually doesn't have anything to do with mirrors.  All the annotations are present in the Kernel representation and correctly installed in the VM implementation.  This is an issue with async functions (everything will work if you run it with `--no-sync-async`).  The superclass version is async and returns `Future<void>`:

```dart
  test_circularReference_viaClosures_initializerTypes() async {
    var mainUnit = await checkFileElement('''
var x = /*info:INFERRED_TYPE_CLOSURE*/() => /*error:TOP_LEVEL_CYCLE*/y;
var y = /*info:INFERRED_TYPE_CLOSURE*/() => /*error:TOP_LEVEL_CYCLE*/x;
''');
    var x = mainUnit.topLevelVariables[0];
    var y = mainUnit.topLevelVariables[1];
    expect(x.name, 'x');
    expect(y.name, 'y');
    expect(x.initializer.returnType.toString(), '() → dynamic');
    expect(y.initializer.returnType.toString(), '() → dynamic');
  }
```
And the subclass version is not async:
```dart
  @failingTest
  @override
  void test_circularReference_viaClosures() {
    super.test_circularReference_viaClosures();
  }
```
so it ignores the Future returned by the call to `super.test_circularReference_viaClosures`.  You need to do something to make sure that the subclass version finishes after the Future returned by `super.test_circularReference_viaClosures` completes so you get a chance to observe the failure.  You could do this just by returning the Future you get from `super.test_circularReference_viaClosures()` (but then you'll have to make the return type `Future<void>`, which you might want anyway), or you can make this method async and await the super method call, or make this method async and return it.

**Comment by bwilkerson** [comment]
Thanks! We'll look into fixing that.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by kmillikin** [comment]
It may have been originally a Kernel/VM/mirrors issue when it was first investigated, but we've fixed a lot of issues in that area over the last few weeks.

**Comment by bwilkerson** [comment]
I believe that this has been fixed.
