### ISSUE TITLE
VM generic partial instantiation isn't kicking in on default arguments

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32658]
The code below should print

```
(int) => void
(int) => void
```

and does so on ddc with kernel and ddc without kernel.

Run on the VM with --preview-dart-2, it prints the following:

```
(int) => void
Unhandled exception:
type '(T) => void' is not a subtype of type '(int) => void' of 'f'
#0      new A (file:///Users/leafp/tmp/ddctest.dart)
#1      main (file:///Users/leafp/tmp/ddctest.dart:13:13)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

```dart
typedef void Foo<T>(T x);

void foo<T>(T x) {}

class A<T> {
  Foo<T> f;
  A({this.f = foo});
}

main() {
  Foo<int> f = foo;
  print(f.runtimeType);
  print(new A<int>().f.runtimeType);
}
```

**Comment by sjindel-google** [comment]
Jens, I believe you implemented this functionality in the constant evaluator. Can you investigate?

**Comment by leafpetersen** [comment]
On reflection, I'm wrong about what should be the correct behavior above.  The original code should have been rejected, see: https://github.com/dart-lang/sdk/issues/32415 .

I'll leave this as a VM bug in case you want to make the error message/failure mode more robust, but feel free to close it otherwise.
