### ISSUE TITLE
Remove Element.xtag

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32659]
https://api.dartlang.org/dev/2.0.0-dev.40.0/dart-html/Element/xtag.html

Seems a mostly abandoned effort. Main package hasn't been touched in 2 years.

https://www.npmjs.com/package/x-tag
https://github.com/x-tag/core

**Comment by kevmoo** [comment]
CC @jmesserly @sigmundch 

Looks like we haven't touched this since 2013 - https://github.com/dart-lang/sdk/commit/6a17da6b4ac4af5e5e00b162770d1d556dbd2199

**Comment by jmesserly** [comment]
yes it's super obsolete, I think it predated custom elements. It was even removed from Polymer.dart ages ago: https://github.com/dart-archive/polymer-dart/commit/179f9399b25ae1300d1895409abb4d5df6994510.

**Comment by terrylucas** [comment]
Yes, looks like it was hand coded in one of our templates should be removed.

**Comment by terrylucas** [comment]
I'll remove the custom code in  impl_Element.darttemplate  

@Creates('Null') // Set from Dart code; does not instantiate a native type.
  Element _xtag;

  /**
   * Experimental support for [web components][wc]. This field stores a
   * reference to the component implementation. It was inspired by Mozilla's
   * [x-tags][] project. Please note: in the future it may be possible to
   * `extend Element` from your class, in which case this field will be
   * deprecated.
   *
   * If xtag has not been set, it will simply return `this` [Element].
   *
   * [wc]: http://dvcs.w3.org/hg/webcomponents/raw-file/tip/explainer/index.html
   * [x-tags]: http://x-tags.org/
   */
  // Note: return type is `dynamic` for convenience to suppress warnings when
  // members of the component are used. The actual type is a subtype of Element.
  get xtag => _xtag != null ? _xtag : this;

  set xtag(Element value) {
    _xtag = value;
  }

**Comment by kevmoo** [comment]
SGTM!

**Comment by terrylucas** [comment]
Fixed https://dart-review.googlesource.com/c/sdk/+/48381
