### ISSUE TITLE
The latest update of pub dependency causes a failure in flutter 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32651]
Please see https://github.com/flutter/flutter/issues/15848

This CL seems to be culprit https://github.com/dart-lang/sdk/commit/bde48c67ec reverting this fixes the problem.

**Comment by a-siva** [comment]
Could we revert this CL from the dart tree.

**Comment by kevmoo** [comment]
Yeah. I want these changes in – but not if they are breaking folks.

**Comment by kevmoo** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/32651

Issue is understood. CL pending.

**Comment by kevmoo** [comment]
Er. sorry. should have closed https://github.com/dart-lang/sdk/issues/32655 – but already referenced that other places.

**Comment by kevmoo** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/48084

**Comment by kevmoo** [comment]
Fix landed in https://github.com/dart-lang/sdk/commit/0b2684e6297217c690d082ce6f1d0e23215b5477
