### ISSUE TITLE
make libraries.json a mandatory argument to CFE/fasta

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32657]
Now that we've added the notion of whether libraries are [`supported:*`][1] in the library-specification format, we need to have access to this information not only when creating the platform.dill files, but also during compilation of application code.

I propose that we require that all backends using fasta should provide the libraries.json file at all times. An alternative could be to store the "supported" bit in the platform.dill file itself.

At this time only dart2js uses the `supported:*` flag, so it is the only backend that provides libraries.json.

[1]: https://dart-review.googlesource.com/c/sdk/+/48060

**Comment by peter-ahe-google** [comment]
IIRC, @sjindel-google struggled with this as well when implementing conditional URIs in the first place.
