### ISSUE TITLE
SDK tests must validate pub get/upgrade

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32656]
RE https://github.com/dart-lang/sdk/issues/32655 snafu

**Comment by dgrove** [comment]
This isn't a P0, but it is something we need to address.

**Comment by matanlurey** [comment]
I opened a similar bug (and got it closed) a while ago.

I realize we are "moving fast and breaking things", but I think at some point we need to have release verification, not just an automatic process of pushing releases without end to end testing for core functionality.

**Comment by dgrove** [comment]
We will fix this.

**Comment by athomas** [comment]
Breakdown after brief chat with @kevmoo:
- [ ] Migrate pkg builders to the test matrix
- [ ] Add step(s) to pub get/pub upgrade package:shelf or test

**Comment by athomas** [comment]
Status update:
* Moved the pkg builders to the test matrix, that makes it easier for me to proceed.
* Built a prototype for the pkg integration test: works but is a bit hackish.
* Running pub is required to run scripts to release the SDK, when I built 2.0.0.49-dev I used the pub from the SDK to publish it. I will keep doing that until their is a test for this.

**Comment by dgrove** [comment]
Any further updates on this?

**Comment by athomas** [comment]
Status update:

- Discussed prototype with @whesse: I have a few issues to fix before I can land it.
