### ISSUE TITLE
2.0.0-dev.41.0 contains broken pub (can not fetch packages)

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32655]
This issue made it into the pub in that release: dart-lang/pub#1846 

Can we add a sanity check to make sure pub can fetch packages?  It's quite time consuming to debug, pin my Travis, wait for a non-broken SDK, then unpin again.

**Comment by jcollins-g** [comment]
To be clear, I'm suggesting a sanity check for this in the SDK prior to building a release version.  It should be entirely possible for pub to transiently have failures in development, that's normal, it's just sad to have them escape into the wild. :-(

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/sdk/issues/32651

**Comment by kevmoo** [comment]
CL pending https://dart-review.googlesource.com/c/sdk/+/48084

**Comment by kevmoo** [comment]
fix landed in https://github.com/dart-lang/sdk/commit/0b2684e6297217c690d082ce6f1d0e23215b5477

**Comment by jcollins-g** [comment]
Great that the base issue is addressed, but I'd like to leave this open to track adding some sort of integration test to prevent this from happening again.  In other words, this bug is open because bugs like this can reappear at any time.

**Comment by jcollins-g** [comment]
Closing -> integration test is covered by #32656
