### ISSUE TITLE
Analysis server provides private completion suggestions it shouldn't

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#32650]
Cause of https://github.com/dart-code/dart-code/issues/721 (screen shots there show this problem in action).

in `library.dart`:

```
library library_sample;

class Foo {
  final int bar;
  const Foo(this.bar);
}

class _FooPrivate {
  final int bar2;
  const _FooPrivate(this.bar2);
}
```

in `main.dart`:

```
import 'library.dart' as lib;

void main() {
  var foo1 = new lib.Foo(1); // OK, and offered as completion suggestion

  var foo2 = new lib._FooPrivate(2); // error, offered as completion suggestion for 'lib.'
                                     // but shouldn't be
}
```

the `new lib._FooPrivate(2)` triggers an error in analyzer (I initially reported that it caused a warning, but now I'm seeing an error - perhaps due to an upgrade in Dart sdk/analyzer between observations), but `_FooPrivate` is offered up as a completion suggestion by the analysis server. 

Expected behavior is that it doesn't show the private class in suggestions.

I initially thought this was related to #32300, but on further investigation it seems like a separate issue.

**Comment by natebosch** [comment]
I can't repro - is this still an issue?

**Comment by dnfield** [comment]
Doesn't seem to be anymore.  Closing!
