### ISSUE TITLE
DDC bug

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#32669]
Error compiling dartdevc module:grizzly_series|lib/lib__grizzly_series.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/lib/dart --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd --dart-sdk=/usr/lib/dart --module-root=/tmp/pub_SECTJX --library-root=/tmp/pub_SECTJX/packages/grizzly_series --summary-extension=linked.sum --no-summarize -o /tmp/pub_SECTJX/packages/grizzly_series/lib__grizzly_series.js --source-map --source-map-comment --inline-source-map -s /tmp/pub_SECTJX/packages/grizzly_scales/lib__grizzly_scales.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__collection.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_2.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_0.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_1.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_4.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_5.linked.sum -s /tmp/pub_SECTJX/packages/collection/lib__shared_3.linked.sum -s /tmp/pub_SECTJX/packages/grizzly_array/lib__grizzly_array.linked.sum -s /tmp/pub_SECTJX/packages/grizzly_primitives/lib__grizzly_primitives.linked.sum -s /tmp/pub_SECTJX/packages/meta/lib__meta.linked.sum -s /tmp/pub_SECTJX/packages/grizzly_series/lib__grizzly_series.linked.sum -s /tmp/pub_SECTJX/packages/text_table/lib__text_table.linked.sum --url-mapping=package:grizzly_series/src/series/series.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/series.dart --url-mapping=package:grizzly_series/src/series/base/series_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/base/series_fix.dart --url-mapping=package:grizzly_series/src/series/base/series_mixin.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/base/series_mixin.dart --url-mapping=package:grizzly_series/src/series/base/series_view_mixin.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/base/series_view_mixin.dart --url-mapping=package:grizzly_series/src/series/bool/bool_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/bool/bool_fix.dart --url-mapping=package:grizzly_series/src/series/bool/bool.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/bool/bool.dart --url-mapping=package:grizzly_series/src/series/bool/bool_view.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/bool/bool_view.dart --url-mapping=package:grizzly_series/src/series/int/int_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/int/int_fix.dart --url-mapping=package:grizzly_series/src/series/int/int_series.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/int/int_series.dart --url-mapping=package:grizzly_series/src/series/int/int_view.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/int/int_view.dart --url-mapping=package:grizzly_series/src/series/int/int_view_mixin.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/int/int_view_mixin.dart --url-mapping=package:grizzly_series/src/series/double/double_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/double/double_fix.dart --url-mapping=package:grizzly_series/src/series/double/double_series.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/double/double_series.dart --url-mapping=package:grizzly_series/src/series/double/double_view.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/double/double_view.dart --url-mapping=package:grizzly_series/src/series/double/double_view_mixin.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/double/double_view_mixin.dart --url-mapping=package:grizzly_series/src/series/string/string_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/string/string_fix.dart --url-mapping=package:grizzly_series/src/series/string/string_view.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/string/string_view.dart --url-mapping=package:grizzly_series/src/series/string/string_series.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/string/string_series.dart --url-mapping=package:grizzly_series/src/series/dynamic/dynamic.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/dynamic/dynamic.dart --url-mapping=package:grizzly_series/src/series/dynamic/dynamic_fix.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/dynamic/dynamic_fix.dart --url-mapping=package:grizzly_series/src/series/dynamic/dynamic_view.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/dynamic/dynamic_view.dart --url-mapping=package:grizzly_series/src/series/dynamic/dynamic_view_mixin.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/dynamic/dynamic_view_mixin.dart --url-mapping=package:grizzly_series/src/series/numeric.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/series/numeric.dart --url-mapping=package:grizzly_series/grizzly_series.dart,/tmp/pub_SECTJX/packages/grizzly_series/grizzly_series.dart --url-mapping=package:grizzly_series/src/data_frame/data_frame.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/data_frame/data_frame.dart --url-mapping=package:grizzly_series/src/utils/utils.dart,/tmp/pub_SECTJX/packages/grizzly_series/src/utils/utils.dart --options=/tmp/pub_SECTJX/packages/_internal_/analysis_options.yaml package:grizzly_series/src/series/series.dart package:grizzly_series/src/series/base/series_fix.dart package:grizzly_series/src/series/base/series_mixin.dart package:grizzly_series/src/series/base/series_view_mixin.dart package:grizzly_series/src/series/bool/bool_fix.dart package:grizzly_series/src/series/bool/bool.dart package:grizzly_series/src/series/bool/bool_view.dart package:grizzly_series/src/series/int/int_fix.dart package:grizzly_series/src/series/int/int_series.dart package:grizzly_series/src/series/int/int_view.dart package:grizzly_series/src/series/int/int_view_mixin.dart package:grizzly_series/src/series/double/double_fix.dart package:grizzly_series/src/series/double/double_series.dart package:grizzly_series/src/series/double/double_view.dart package:grizzly_series/src/series/double/double_view_mixin.dart package:grizzly_series/src/series/string/string_fix.dart package:grizzly_series/src/series/string/string_view.dart package:grizzly_series/src/series/string/string_series.dart package:grizzly_series/src/series/dynamic/dynamic.dart package:grizzly_series/src/series/dynamic/dynamic_fix.dart package:grizzly_series/src/series/dynamic/dynamic_view.dart package:grizzly_series/src/series/dynamic/dynamic_view_mixin.dart package:grizzly_series/src/series/numeric.dart package:grizzly_series/grizzly_series.dart package:grizzly_series/src/data_frame/data_frame.dart package:grizzly_series/src/utils/utils.dart
    dart --version: 2.0.0-dev.40.0 (Unknown timestamp) on "linux_x64"
```
Bad state: Unable to find unlinked summary: package:grizzly_series/src/series/series.dart
#0      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:241)
#1      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#2      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:222)
#3      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:238)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:568)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:566)
#7      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:712)
#8      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:685)
#9      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:184)
#10     _compile (package:dev_compiler/src/analyzer/command.dart:186)
#11     compile (package:dev_compiler/src/analyzer/command.dart:57)
#12     _CompilerWorker.performRequest (file:///tmp/tmpqjhHs6/dart-2.0.0-dev.40.0/dart/pkg/dev_compiler/bin/dartdevc.dart:43)
<asynchronous suspension>
#13     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33)
<asynchronous suspension>
#18     main (file:///tmp/tmpqjhHs6/dart-2.0.0-dev.40.0/dart/pkg/dev_compiler/bin/dartdevc.dart:23)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

**Comment by matanlurey** [comment]
@tejainece: What version of the Dart SDK? What build tool(s)?

**Comment by tejainece** [comment]
You can reproduce it using the following code: https://github.com/tejainece/series_plot

**Comment by tejainece** [comment]
It seems to have trouble on this line https://github.com/tejainece/series_plot/blob/master/web/bar/bar_main.dart#L1

**Comment by tejainece** [comment]
Any progress on this issue? Thanks.

**Comment by VitaliLiashchuk** [comment]
I've same bug with my project...

**Comment by natebosch** [comment]
I'm on `2.0.0-dev.45.0` and I see that there are earlier failures compiling with DDC:

```
[error] The argument type 'JsObject' can't be assigned to the parameter type 'Element'. (package:plotly/plotly.dart, line 176, col 32)

Please fix all errors before compiling (warnings are okay).
```

After this there are multiple errors like `Bad state: Unable to find unlinked summary:`

I think the "cascading" build errors may be even worse with `pub build` than they are in `build_runner`...

Given that `pub build` is deprecated in favor of `build_runner` I don't think there are any actions for us to take here. The error is more clear with `build_runner` that the failure is due to being unable to compile an earlier module. Please focus on upgrading your workflow to `build_runner` and fixing the compile error in `plotly`.

https://github.com/dart-lang/build/blob/master/docs/getting_started.md

**Comment by tejainece** [comment]
The problem seems to be because of this: https://github.com/dart-lang/sdk/issues/30

How circular dependencies are handles by DDC.
