### ISSUE TITLE
Creating resource only packages

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#32662]
Hope it's not a dupe. Didn't find any similar issues. 

We have a use case for having resource only packages like https://github.com/flutter/cupertino_icons. It generally works ok though when dependent projects bring them in, `.packages`' entry has the form
```
cupertino_icons:file:///Users/x/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.1/lib/
```
which doesn't exist since there's no lib or dart files which can cause IDE warnings. 

We can certainly make a blank directory. Though it would be good to have an officially recommended approach to this since it might be a generic repeatable problem.

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/pub#1848
