### ISSUE TITLE
concrete member overridden by abstract with different signature and noSuchMethod 

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#32660]
Here's an interesting example with noSuchMethod mocking:
```dart
class B {
  foo(int x) => x;
}

class C extends B {
  foo(int x, {int y});

  noSuchMethod(i) {
    print(i.namedArguments);
    return 42;
  }
}

main() {
  var c = new C();
  print(c.foo(123, y: 456));
}
```
I believe this should be an error, or the call to c.foo should call noSuchMethod. What actually happens in DDC is no mock member is generated (because it sees a concrete member), and it calls B.foo, printing `123`. I will need to check what CFE generates, but it may have the same issue.

Dart 1 behavior was to call C.noSuchMethod, printing `{Symbol("y"): 456}` then `42`.

If I move `foo(int x, {int y});` to an interface that is implemented by `C`, then I get the following error from DDC/Analyzer:
```
[error] Base class introduces an invalid override. The type of 'B.foo' ('(int) → dynamic') isn't a subtype of 'I.foo' ('(int, {y: int}) → dynamic'). (../../../scratch/test.dart, line 9, col 9)
```
CFE does not issue that error.

**Comment by jmesserly** [comment]
CC @leafpetersen @lrhn

**Comment by jmesserly** [comment]
Excellent, triaging this to front-end and analyzer (neither is reporting the error right now)

**Comment by stefantsov** [comment]
That may be a related issue: https://github.com/dart-lang/sdk/issues/33483.

**Comment by jensjoha** [comment]
Fixed in fasta with 40864cc6985f2ea24169c7f832bc82a6d533f48a.

**Comment by srawlins** [comment]
The analyzer now gives an error, but it seems bogus:

> error • 'B.foo' ('dynamic Function(int)') isn't a valid override of 'C.foo' ('dynamic Function(int, {int y})'). • a.dart:5:7 • invalid_override

**Comment by srawlins** [comment]
That bogus UX is https://github.com/dart-lang/sdk/issues/37993.
