### ISSUE TITLE
dartanalyzer does not find dart file.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#32673]
dartanalyzer does not find dart file in the case described below.
Put into the separate directory directory _dir1_ and a dart file:
- dir1
- test.dart
```dart
main() {
  print('--- output ---');
}
```
Run test1.dart
Variant 1: in this case datranalyzer does not find dart file.
```
> cd dir1
> dart ../test.dart 
--- output ---
> dartanalyzer ../test.dart  
Analyzing ../test.dart...
No dart files found at: ../test.dart
>
```
Variant 2: dart and datranalyzer find dart file.
```
> cd ..
> dart test.dart 
--- output ---
> dartanalyzer test.dart 
Analyzing test.dart...
No issues found!
>
```
Reproduced with Dart VM version: 2.0.0-dev.42.0 (Fri Mar 23 19:30:18 2018 +0100) on "linux_x64".
Last version with which both variants work:  Dart VM version: 2.0.0-dev.32.0 .

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Is this related to the changes you recently made to dartanalyzer?

**Comment by MichaelRFairhurst** [comment]
Yep this is almost certainly my fault!

**Comment by sgrekhov** [comment]
This isuue exists on Windows as well

**Comment by kevmoo** [comment]
Just hit this on 2.2.1-dev.0.0 – profoundly annoying!

Thoughts @MichaelRFairhurst ?

In my case, it's being hit when run against a directory `dartanalyzer .`

**Comment by MichaelRFairhurst** [comment]
Kevmoo, what's your analysis options?

As far as I know, I can only think of a "known" issue here if you are analyzing code in `..`

**Comment by kevmoo** [comment]
Oops. User error.
