### ISSUE TITLE
Bad error message for EXTRACT_METHOD refactor with invalid name

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32678]
If I invoke `EXTRACT_METHOD` and give a method name of `"""` I get back a **Fatal** message that says "Method name must begin with a lowercase letter or underscore". This is misleading, as if I send the name "Aaa" I get back the same message as just a warning.

Since fatals are blocking and are presented to the user as a complete failure, it's misleading to suggest that the reason for failure is that the name didn't start with lowercase/underscore (since when they type `Aaa` we present the same message as only a warning, with an option to proceed anyway). The message should instead state that the name is invalid.

**Comment by bwilkerson** [comment]
I agree, the messages should be different.

If you're interested in fixing this on the server side, I'm happy to point you to the relevant code.

**Comment by DanTup** [comment]
SGTM. I haven't got the sdk code up and running on my corp MacBook yet so it'll give me a proper reason to do so.

**Comment by DanTup** [comment]
@bwilkerson I've got `gclient sync` working properly now, happy to look at this if you can give some pointers for where the code/tests should be (or how I find it).

**Comment by bwilkerson** [comment]
The implementation of the refactoring is here: `sdk/pkg/analysis_server/lib/src/services/refactoring/extract_method.dart`.

There are two possible places for tests, but this one looks like the best: `sdk/pkg/analysis_server/test/services/refactoring/extract_method_test.dart`.

(I found them by searching for class names starting with `ExtractMethod`.)

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/54244
