### ISSUE TITLE
Expose ServiceWorker class

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32675]
See https://api.dartlang.org/be/154774/dart-html/ServiceWorkerContainer/controller.html
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker

**Comment by dgrove** [comment]
Why is this being added to beta 3, which is quite close?

**Comment by kevmoo** [comment]
We can bump off. Let's discuss tomorrow.

**Comment by terrylucas** [comment]
All of the other ServiceWorker interfaces are exposed this was hidden from
our 45  roll and I've removed the hidden state (removal of _).

**Comment by terrylucas** [comment]
Fixed https://dart-review.googlesource.com/c/sdk/+/48381
