### ISSUE TITLE
Expand ConstExprBuilder to handle non-const expressions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32674]
Currently, the analyzer's ConstExprBuilder class only handles constant expressions.  In order to fix #32525, we'll need to expand it to handle non-constant expressions as well.  In the process we should rename it to something that doesn't have "const" in the name (perhaps just "ExprBuilder").

**Comment by dgrove** [comment]
Since this is blocking #32525, either this should be in the Dart2-Beta 3 milestone, or the other issue should be moved out of that milestone.

**Comment by stereotype441** [comment]
@dgrove Thanks, fixed

**Comment by stereotype441** [comment]
Fixed in be3baa0b8f0038692dd6e3810869e240f8a7b674
