### ISSUE TITLE
Add `ports` to MessageEvent

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32688]
https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/ports

I see it mentioned a few places, but it's never exposed - https://api.dartlang.org/be/154793/dart-html/MessageEvent-class.html

**Comment by terrylucas** [comment]
MessageEvent.data and maybe MessageEvent.webkitInitMessageEvent (investigate this).

**Comment by kevmoo** [comment]
`.data` is already there.

Not sure where `webkitInitMessageEvent` comes in...

**Comment by terrylucas** [comment]
data is hand crafted code shouldn't be since it's marked as being hidden like (ports) in the PYTHON code.

**Comment by kevmoo** [comment]
Fun!

**Comment by leonsenft** [comment]
Just hit this trying to use [channel messaging](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging) in package:test to fix https://github.com/dart-lang/test/issues/928.

@terrylucas Any progress on this?

**Comment by leonsenft** [comment]
Was this closed by c5cfdc52797ef6ae5b13fee7babe71014b56827a? I haven't had time to test it myself.

**Comment by terrylucas** [comment]
Yes this added ports field.
