### ISSUE TITLE
Sort Members refactor doesn't sort all items as expected

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32683]
Given:

```dart
int b;
int a;
class Person {
 int b;
 int a;
 bb() {}
 aa() {}
}
dd() {}
cc() {}
```

If I sort I seem to end up with:

```dart
int a;
int b;
cc() {}
dd() {}
class Person {
 int b;
 int a;
 aa() {}
 bb() {}
}
```

It seems like the fields `a` and `b` inside the class were not sorted but I can't think of a logical reason why (the methods inside the class where and the top level variables were).

**Comment by DanTup** [comment]
Would you consider adding an offset/length to the sort refactor so people can sort just a range? That would at least let people be selective :-)

**Comment by bwilkerson** [comment]
Yes, of course we'd consider it. I just haven't heard of any desire for such support from the community.

**Comment by bwilkerson** [comment]
@DanTup Do you think we should keep this issue open? I'm guessing that at this point we probably won't actually implement it, but I'm willing to keep it open if you'd like.

**Comment by DanTup** [comment]
It can be closed. I'm writing a lot more Dart now than when I opened this and I use sort-members-on-save in some of my projects now and I don't think I'd use either sorting of fields or sorting of range myself. Since there are also zero 👍 's on this issue, it's not clear there's any demand for this.
