### ISSUE TITLE
NSM forwarders can't be partially instantiated

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32682]
We should solve this when solving #32534.

**Comment by a-siva** [comment]
Chatted with @sjindel-google, this is related to a larger issue with instantiation of local and top level method (https://github.com/dart-lang/sdk/issues/31665). This issue does not have a milestone associated with it. We should probably set it to 'dart2 beta 4' or 'Dart2 Stable' and adjust the related issues to the same milestone. We have moved this to 'Dart2 Stable' for now.

**Comment by sjindel-google** [comment]
This is solved by https://dart-review.googlesource.com/c/sdk/+/53801, which moves handling of partial instantiation into the shared prologue builder.

**Comment by sjindel-google** [comment]
This is actually still a problem:

```dart
$ echo >nsm_partial.dart <<EOF
class C {
  T foo<T>(T x);

  dynamic noSuchMethod(Invocation invoke) {
    print(invoke.typeArguments);
  }
}

void main() {
  var c = new C();
  int Function(int) k = c.foo;
  k(1);
}
EOF
$ pkg/vm/tool/dart2 nsm_partial.dart
[]
```
