### ISSUE TITLE
dart2js strong: polish and improvements

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32691]
These features where not needed for an initial release, but would be good to fix early:
- [ ] Ensure that erroneous calls through Function.apply work well for instantiation closures.
- [ ] Add support in type inference for `ir.Instantiate` and `FutureOr`
- [x] Supply default bounds for Function.apply on generic methods.

**Comment by rakudrama** [comment]
#3, Default bounds for Function.apply can be implemented by having the `"call*"` property direct to the stub that defaults the type parameters, and ensuring that stub is generated. Then defaulting to bounds will work via https://github.com/dart-lang/sdk/issues/32741 being fixed.

**Comment by sigmundch** [comment]
we are tracking individual issues now for each missing task.

See: https://github.com/dart-lang/sdk/issues/33570, https://github.com/dart-lang/sdk/issues/33569
