### ISSUE TITLE
Generates relative instead of package path when importing files under project's lib/ directory

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#32690]
_From @tamcy on March 27, 2018 14:10_

When using code completion to generate codes of missing file import, the plugin always generates a `package:` style import, even when importing from within our own package. But this can break things as ["main.dart" is imported relatively, not as a package](https://groups.google.com/d/msg/flutter-dev/4RSZlcp3x_E/n4k7xEgJCQAJ). It'd be better if relative path syntax is used.

_Copied from original issue: flutter/flutter-intellij#2015_

**Comment by pq** [comment]
_From @zoechi on March 27, 2018 14:23_

I think the conclusion to this problem was that `lib/main.dart` should always **only** contain package imports, then Dart is able to canonicalize libraries properly no matter what form the imports are in other libraries.

**Comment by pq** [comment]
_From @stevemessick on March 27, 2018 16:39_

@pq could you take a look and help decide who's best to follow up with this?

**Comment by pq** [comment]
I think the general rule is that if you use relative imports, all your imports should be relative, otherwise all should be absolute.  Problems arise when there's a mix.   In practice, I think @zoechi's advise is spot on.  FWIW, if you want the linter to keep you on the rails, you might consider enabling [`avoid_relative_lib_imports`](http://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html)...

cc @bwilkerson, in case he wants to chime in.

**Comment by pq** [comment]
(Since this is a general completion issue, moved to the SDK tracker 👍 )

**Comment by tamcy** [comment]
When develop in Flutter, the following code won't work if package imports are used.
https://gist.github.com/tamcy/0c4d6cc58f61b6de2740ede56880e8b4

**Comment by zoechi** [comment]
@tamcy that's probably because of `import 'main.dart';`
Try to avoid importing the entrypoint fie.

**Comment by pq** [comment]
@scheglov: is there anything to track here or should I close the issue?

**Comment by scheglov** [comment]
We still might get to this issue, there was same request in VS Code tracker recently.

**Comment by tenhobi** [comment]
I would also like to see some linter where I could set relative or absolute path option for my package.

**Comment by nguyenxndaidev** [comment]
I would like to have both package and relative suggestions.
How is the progress of this issue?

**Comment by keezysilencer** [comment]
It would be nice to be able to import both package and relative path.
How is it going?

**Comment by bwilkerson** [comment]
We now support both styles by offering both suggestions, so I'm going to close this issue.

**Comment by nstrelow** [comment]
@bwilkerson Which release version does include it?

**Comment by nstrelow** [comment]
Could somebody link the commit this was added to?

So I can see if my dart version already supports it. (Using Android Studio)

Thanks so much :D
