### ISSUE TITLE
Analyzer crashed

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32692]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4548.28`
- `2.0.0-dev.40.0`
- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 3440x1440, 1080x1920  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/bn/dtrksvvs32j6004mk6r0dcdw007b7h/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.40.0, server version 1.20.0, error: Analysis failed: /Users/matanl/git/angular/angular_compiler/test/emitter/injector_test.dart
RangeError (byteOffset): Invalid value: Not in range 0..1860, inclusive: 2952790061
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4278)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      StringReader.read (package:front_end/src/base/flat_buffers.dart:663)
#3      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:826)
#4      Object

**Comment by MichaelRFairhurst** [comment]
You can try `rm ~/.dartServer/.analysis-driver/*`, if you were using a buggy version before it could have corrupted your cache
