### ISSUE TITLE
MediaDevices.enumerateDevices should return a Future<MediaDeviceInfo>

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32698]
Right now (2.0.0-dev.42.0) it returns a JS `Promise` object

**Comment by terrylucas** [comment]
Fixed with support of Promises to Future code in all of the the Dart web libraries.

**Comment by kankaristo** [comment]
This doesn't seem to be fixed? It no longer returns a Promise, but it also doesn't work (`promiseToFuture` fails).

Related issue:
https://github.com/dart-lang/sdk/issues/35282

**Comment by kevmoo** [comment]
@terrylucas ?

**Comment by ollydixon** [comment]
Hey, this doesn't seem fixed. https://github.com/flutter/flutter/issues/108874
