### ISSUE TITLE
Need clarification on NSM invocation for double-type-application

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32695]
When the partial instantiation operation is performed, a dynamic invocation of the resulting closure object with type arguments must throw NSM. Which set of type arguments should be visible in the resulting `NoSuchMethodError` exception?
For example:
```dart
foo<T>() {}

void main() {
  int Function() y = foo;
  (y as dynamic)<String>();
}
```

Currently prints:
```
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'foo'
Receiver: Closure: <T>() => T from Function 'foo': static.
Tried calling: foo<String>()
Found: foo<T>() => T
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      main (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart:5:25)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by lrhn** [comment]
The invalid type *arguments* are the ones that show up.

In this case we have one invalid dynamic invocation. The function object has type `int Function()`, the invocation is `...<String>()`, so the invalid invocation has `[String]` as `typeArguments` and empty positional and named arguments.

Luckily, functions can't have user-written `noSuchMethod`s any more, so it's only about which type argument ends up in the NoSuchMethodError.

The error message is misleading. The function being called isn't `foo<T>() => T` (or even `foo<T>() => dynamic`, as I would have expected, the return type was never `T`), it's just `foo<dynamic>` which has type `dynamic Function()`. I'd *almost* accept writing it as `foo() => dynamic` as well, at least it's less misleading.
