### ISSUE TITLE
VM base-level and meta-level disagree about declarations created by mixin application

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32696]
```
class M {
  static void foo() => 1;
}
class C = Object with M;
```

C.foo() will fail with NSM, but reflectClass(C).declarations will include foo.

We had discussions back in 2013/2014 that mixin application includes static declarations, which is why mirrors behave as they do, but given the base-level semantics are a fait accompi, we should update mirrors to agree with this behavior.

**Comment by rmacnak-google** [comment]
See class_declarations_test.dart

**Comment by eernstg** [comment]
> C.foo() will fail with NSM, but reflectClass(C).declarations will include foo.

It is a bug that `reflectClass(C).declarations` includes `foo`.

As Jacob mentions, this has been discussed earlier. I remember discussions about this topic from my work on implementing reflectable, and the conclusion was clearly that static members like `foo` are not declared by the new class which is created by mixin application.

However, to my surprise, the language specification does _not_ make that completely explicit (static members are not mentioned, so there is no support for concluding that they are carried over, but it is stated explicitly that all instance members are included; similarly, the treatment of constructors is explicit and detailed).

So I created a [CL](https://dart-review.googlesource.com/c/sdk/+/49360) to clarify the situation. I just discussed this with @lrhn and he agrees that static members are dropped; @lrhn, @leafpetersen, please take a look.

**Comment by eernstg** [comment]
The clarification has now been confirmed in the language team and [landed](https://dart.googlesource.com/sdk/+/4b2b15f53e64dd4e2172516962d7586509d6355f).
