### ISSUE TITLE
SourcePosition tests are not Dart 2 compatible

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#32704]
Currently, all of the `SourcePosition_*` tests invoke the VM parser directly which means they cannot be run in Dart 2 mode. We should either:

1. Update these tests to not rely on the VM parser.
2. Rewrite these tests in such a way that they use the service protocol to determine source positions.

@a-siva

**Comment by a-siva** [comment]
In addition to the tests above the following unit tests were relying on the VM parser and don't work in the new pipeline, they need migration
cc/CompileFunctionOnHelperThread
cc/CompileFunction
cc/InvokeDynamic_CompileError
cc/InvokeStatic_CompileError
cc/DartEntry
cc/FindCodeObject
cc/Parser_TopLevel
cc/DartDynamicResolve
cc/DartStaticResolve
cc/AllocateNewObjectCodegen
cc/InstanceCallCodegen
cc/StaticCallCodegen
