### ISSUE TITLE
LibraryElementImpl's isInSdk can be fooled by libraries with unusual names

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32707]
`LibraryElementImpl.isInSdk` returns true even for libraries that aren't in the SDK, such as those in
the [collection package](https://pub.dartlang.org/documentation/collection/1.14.9/) (libraries named "dart.pkg.collection.algorithms" and so on).

Perhaps the analyzer could use other information to make this determination instead.  Tested with analyzer 0.31.2-alpha.1.

**Comment by bwilkerson** [comment]
We ought to be able to do something similar to `DartUriResolver.isDartUri(definingCompilationUnit.source.uri)`.

**Comment by natebosch** [comment]
https://github.com/dart-lang/sdk/issues/31045 - DDC and the build system avoid `isInSdk` for just this reason.

Should we close this issue as a duplicate?

**Comment by bwilkerson** [comment]
Thanks! I forgot to mark this as closed: https://dart-review.googlesource.com/c/sdk/+/48760
