### ISSUE TITLE
Since v2-dev40 a setters return value is dynamic instead of void

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32703]
In v1 stable the return type of a setter from the analyzer is `dynamic`. I noticed in v2 builds it had changed to `void` (this seems like a good change). However, since v2 dev40 it has gone back to `dynamic`.

[Discussion on the analyzer-discuss list](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/zGasW4sgjQE) suggests this is an unintended regression.

(note: I think this was the version where previewDart2 became default, so I wonder if it may be related to that)

**Comment by srawlins** [comment]
Er, I don't think this is true any longer. It should be void. Please re-open if this is still an issue.

**Comment by DanTup** [comment]
Yup, this seems good in latest code and stable. Thanks!
