### ISSUE TITLE
Generate NSM forwarders for implicit getters & setters of a field

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32722]
Consider the following example:

```dart
abstract class I {
  int foo;
//  int get foo;
//  set foo(int i);
}

class A implements I {
  dynamic noSuchMethod(Invocation inv) {
    print('noSuchMethod (${inv.memberName})');
    return 'hi';
  }
}

main() {
  A aa = new A();
  print(aa.foo);
  (aa as dynamic).foo = 'hello';
}
```

It runs without errors, returning String from I.foo getter and accepting String in I.foo setter.
If field `foo` is replaced with explicit getter and setter (commented code), type errors are correctly reported.

/cc @stefantsov @sjindel-google

**Comment by sjindel-google** [comment]
I think this should be done in the FE, with abstract methods for the getter and setter created with the `no-such-method-forwarder` flag.

**Comment by dgrove** [comment]
Is this actually needed for Dart2Stable? @kmillikin

**Comment by stefantsov** [comment]
I believe I have a fix in [CL 62151](https://dart-review.googlesource.com/c/sdk/+/62151).
