### ISSUE TITLE
extend the service protocol's getSourceReport call to add a 'since last reload' type

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32736]
We'd like to show the covered and not covered lines since the last reload in IDEs, as a way to tell the user which changed methods and lines were executed during the reassemble - and likely represented in their UI - and which ones weren't.

In order to do this, I believe we need a new type of code coverage report. The `getSourceReport()` currently takes a list of coverage types to report (`SourceReportKind`); currently `PossibleBreakpoints` and `Coverage`. I think we'll need a `SinceReload` type, that would report just for scripts that were reloaded in the last reload, and only coverage info (covered or not) for changed methods.

/cc @rmacnak-google @a-siva (and, @mit-mit)

**Comment by DanTup** [comment]
Wouldn't this be better pushed to us? Otherwise, how would we know if a method is run later (eg. a button is clicked which causes some changed code in its event handler to run)?

**Comment by devoncarew** [comment]
Yes, auto-updating as the user interacts with the app would be fantastic, but likely something like a V2.

A push notification from the VM would be very nice, and make it easier for clients to implement. If that's not feasible, we could build an API into flutter_tools that would provide that notification, based on polling the VM. We'd need a fast call to get coverage since the last reload, and some reasonable polling frequency. We could use frame events to know when to re-poll (if no new frame events, we could assume that coverage info likely hasn't changed).

**Comment by rmacnak-google** [comment]
Reload resets all usage counters, so coverage is already "since last reload". No VM change is needed.

As a performance optimization, it would be possible to add an ability to getSourceReport to filter by changes in the last reload, but this is only worthwhile if (1) "coverage only in changed functions" can be shown to be more useful than (2) "coverage everywhere since last reload". I suspect (1) often won't explain much because if a changed function doesn't run, one starts looking at the expected callers and rather quickly this will included unchanged functions.

What events in the VM do you imagine getting notifications for?

**Comment by devoncarew** [comment]
> Reload resets all usage counters, so coverage is already "since last reload". No VM change is needed.

The current coverage report includes information about covered and not covered token positions. We don't want to show 'not covered' decorations for lines that we're not reloaded, only reloaded lines that didn't run.

I also noted that the coverage call is pretty slow and not really suitable for frequently polling it (on the order of 2 seconds). Perhaps scoping this to just changed code would make the API faster as well.

We're generally not focusing here on using this API to show coverage information to the user, but using it to help the user understand what ran after the reassemble and what didn't.

> What events in the VM do you imagine getting notifications for?

The events would be useful in converting from having the IDEs poll for coverage changes to getting push events for the same.

**Comment by devoncarew** [comment]
we went a different way with the data we needed to display reload results
