### ISSUE TITLE
Differentiate between analysis server feedback and crashes

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32731]
We have had a hypothesis that the problem is in the encoding mechanism that allows the data to be sent via http. Whatever the real cause is, we need to fix it so that we can get actionable data about the analysis server.

See #32730 for an example of an issue for which the data was not correctly sent.

**Comment by devoncarew** [comment]
The user is able to provide arbitrary feedback w/o having has seen a crash, which is what I believe that issue is. We can adjust this of course, if we don't believe it to be valuable.

**Comment by devoncarew** [comment]
I believe we should rename the title for pure feedback so that it's easier to differentiate between crashes; currently, they're both `Analyzer Feedback from IntelliJ`.

**Comment by devoncarew** [comment]
Closing this as IntelliJ no longer prompts to report analysis server crashes.
