### ISSUE TITLE
Long time to work

### ISSUE THREAD

**Issue by victorshn** [dart-lang/sdk#32730]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 , screens 1366x768`

**Comment by bwilkerson** [comment]
It appears that the information about what actually went wrong was not captured. If you can reproduce the error, please try re-sending the information.
