### ISSUE TITLE
add webcomponents-lite.js in DEPS

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32742]
Tests in html/custom need webcomponents.

These were removed recently, but are pulled in indirectly via observatory packages. Because those tests use it explicitly, the webcomponents package (or at least the webcomponents-lite.js file) need to be available in the repo.

3 options:
* add the package in DEPS and pull it from https://github.com/dart-archive/web-components (this requires a mirror)
* copy the .js file in the repo directly
* use DEPS to pull the .js file directly from the polymer organization, rather than from our archive package.

The last idea seems more prone to be broken if changes happen upstream, so my inclination is for (1) or (2). 

/cc @terrylucas @kevmoo @whesse

**Comment by whesse** [comment]
Option 2 seems the simplest, if the licence can be the same (If it is created by Google, and can be moved to the Dart licence).  It also seems appropriate, since we are using only one file, for legacy support, and will not be needing to update it. Option 1 is straightforward as well, I would mirror it to dart.googlesource.com.

**Comment by sigmundch** [comment]
Thinking more about it - I'm inclined to do option 1 at this time. I'd have to follow up about the license question to be able to continue with option 2 (it is attributed to Polymer authors, which includes both internal and external developers).

FWIW - we already have https://dart.googlesource.com/web-components/ mirrored from the old location, so my guess is that we'd just need to update where the mirror origin is. Given that the mirror location exists, I'll pull it into DEPS directly from there.

**Comment by sigmundch** [comment]
I landed the DEPS change in a173784a310ca3d0dcca259fa82de6959ad517c9 - Bill please note that we might need to update where that mirror is pointing to (now to the the new dart-archive location)
