### ISSUE TITLE
Remove uses of deprecated constants from packages used by flutter and internal code 

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32749]
Identify and clean up any packages that are used by flutter or by internal code and which still use the deprecated CONSTANTS.  Main issue here: https://github.com/dart-lang/sdk/issues/31813 .

**Comment by leafpetersen** [comment]
@kevmoo I believe you looked at packages to identify ones that would need clean up.  Do you still have this data?  Can you provide this so that we can cross reference against packages used in flutter and internally?

**Comment by kevmoo** [comment]
I *DON'T* have this data – at least not directly available. We'd have to
dig through the analysis data from the package site.

Doable, but it'd take some scripting. Contact me offline...

**Comment by dgrove** [comment]
What's the next step here? Is there any further work required for beta 3?

**Comment by kevmoo** [comment]
We have 41 packages that use at least one of these constants. Some of them are used by Flutter. We need to get them updated and published...

Not sure where @nex3 is with https://github.com/dart-lang/dart2_constant

**Comment by nex3** [comment]
> Not sure where @nex3 is with https://github.com/dart-lang/dart2_constant

It's [released](https://pub.dartlang.org/packages/dart2_constant) and [announced](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/yYJIiNHwZpk).

**Comment by leafpetersen** [comment]
It's not clear to me that there is any reason that we need to have these updated and published by Beta-3, since updating the packages is non-breaking to users of the packages (including flutter).  Is there something I'm missing?  Certainly doesn't hurt to get them done ASAP though.

The intersection of @kvemoo's list of packages from the top 200 that need fixing and packages depended on by flutter is enclosed below.  There may be other flutter packages that need fixing that aren't in the top 200 though, so we need to go through and verify at some point.


These packages are used by flutter and need fixing (there may be others):

  - [ ] analyzer
  - [ ] async
  - [ ] barback
  - [ ] coverage
  - [ ] dart_style
  - [ ] image
  - [ ] intl
  - [ ] intl_translation
  - [ ] json_rpc_2
  - [ ] json_schema
  - [ ] markdown
  - [ ] matcher
  - [ ] process
  - [ ] quiver
  - [ ] shelf
  - [ ] shelf_web_socket
  - [ ] source_maps
  - [ ] test
  - [ ] usage
  - [ ] vector_math
  - [ ] yaml

**Comment by devoncarew** [comment]
What is the sdk lower bounds where the constants were introduced (or, are all available)?

**Comment by devoncarew** [comment]
I see some packages using: `sdk: '>=2.0.0-dev.30 <2.0.0'`.

**Comment by lrhn** [comment]
I believe the lower-case constants were released in 2.0.0-dev.17.0

I'm already working on the packages that are used by the SDK, but let's see if I can make proper pull requests for them.

**Comment by leafpetersen** [comment]
Added the list of packages used by the sdk to the TODO list above.

**Comment by dgrove** [comment]
@lrhn any idea when the changes for these packages can land?

**Comment by dgrove** [comment]
@lrhn any updates?

**Comment by lrhn** [comment]
I have pull requests out for all the packages in the above list that need it.
Some are entirely third-party, and I don't know how soon those will be handled. We do not control publishing of those (e.g., mustache4dart, which has a dart2 branch, but no releases of it).
Some packages are internal, and some of those are blocked on review (due to review vacation).
Some have already landed.

It's unclear what our strategy for barback is. It's not planned to be upgraded to Dart 2, so we should remove it from the SDK ASAP since it has no future.

The sooner we make the SDK Dart 2 only, the sooner such issues will be surfaced.

**Comment by leafpetersen** [comment]
@grouma what's the story on barback?

**Comment by grouma** [comment]
It's been removed entirely from pub and is no longer supported: https://github.com/dart-lang/sdk/commit/94f45c8876b2c4626462e7327f800fd33c842070

**Comment by leafpetersen** [comment]
So can we stop pulling barback into the SDK now?

**Comment by kevmoo** [comment]
I think if we update pkg:test, yes...I think...

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/55321

**Comment by dgrove** [comment]
Any updates here?

**Comment by munificent** [comment]
I haven't looked into markdown. If @srawlins doesn't reply, I'll take a look.

**Comment by srawlins** [comment]
Oh, Leaf did it.

**Comment by vsmenon** [comment]
Any updates on this?  Do we have any further changes needed on packages hosted in the sdk repo?

**Comment by kevmoo** [comment]
Here's our packages. `googleapis` is important for the Flutter folks – I think that's the only one we should worry about...

<img width="1739" alt="screen shot 2018-07-25 at 8 14 36 am" src="https://user-images.githubusercontent.com/17034/43209971-ce0bb302-8fe2-11e8-98e9-65f94eb78827.png">

**Comment by leafpetersen** [comment]
Once we have a successful roll to flutter this can be closed.

**Comment by kevmoo** [comment]
SGTM. I know there are folks in the flutter universe that use the Google
APIs – so it might come up.

**Comment by leafpetersen** [comment]
This is done, we've rolled flutter and internal.

**Comment by tonyclickspace** [comment]
chrome.dart still has instances of JSON.decode:
https://github.com/dart-gde/chrome.dart/issues/278
Not sure if that's high enough priority to re-open this.

**Comment by leafpetersen** [comment]
There's an open PR for chrome.dart (https://github.com/dart-gde/chrome.dart/pull/272), but the scope of this bug is packages used directly by flutter or internal code which I believe is now complete.
