### ISSUE TITLE
No pubspec.yaml file found.

### ISSUE THREAD

**Issue by chiefmarko** [dart-lang/sdk#32747]
I can see the pubspec.yaml file in my project, however,  project cannot run and gives the following error:

Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

I have tried opening new projects and all throw the same error. Please assist

**Comment by zoechi** [comment]
What Flutter version?
Please provide the output of `flutter doctor -v`
Purging the Flutter install directory and install it again might be worth a try.

**Comment by chiefmarko** [comment]
[√] Flutter (Channel master, v0.2.7-pre.6, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.7-pre.6 at C:\flutter
    • Framework revision 0c89920069 (32 hours ago), 2018-04-01 17:35:05 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\markk\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4548.30
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.1

[√] Connected devices (1 available)
    • RAINBOW LITE 4G • 65b6f03e • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 2 categories.

**Comment by chiefmarko** [comment]
Tried purging and re-installing flutter, dart and associated plugins to no avail

**Comment by zoechi** [comment]
Did you try accepting the licenses?

**Comment by kevmoo** [comment]
Please ask this type of question in https://stackoverflow.com/

Did you run the command in the directory w/ `pubspec.yaml`?

Closing as this doesn't seem an issue – but happy to help you figure things out.

**Comment by zoechi** [comment]
Is this when you run it on iPhone or iOS emulator or also on Android?

**Comment by chiefmarko** [comment]
Android

**Comment by zoechi** [comment]
See also flutter/flutter#16100

**Comment by saravananmnm** [comment]
still i got this error, when i run flutter clean command.

Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (8 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!
Process finished with exit code 0

![image](https://user-images.githubusercontent.com/23417457/59992997-0a99d980-966c-11e9-8d79-074483ba33b9.png)

**Comment by lightcomet** [comment]
Not sure if the pubspec.yaml should be at the root directory of your application, but I'm guessing in your case it should be at **"C:\Saravanan\Flutter_visibility\tvs_invisibility"** instead of inside the "test" subfolder. Secondly, the terminal seems to be pointing at another folder directory namely **"C:\Saravanan\Flutter_SDK\flutter"**, hence you might want to change the directory it is pointing at to the **"C:\Saravanan\Flutter_visibility\tvs_invisibility"**.

For my case, the pubspec.yaml file and the other files was at the folder **"C:\Desktop\Flutter\my_app_name\my_app_name"** when i created the new project using **"Flutter: New Project"**. In the first "my_app_name" folder, it had nothing except for another "my_app_name" folder, thus i had to move all the files to one level before which is "**"C:\Desktop\Flutter\my_app_name"** and ensure that the terminal is pointing to this directory.

**Comment by Grohden** [comment]
I was getting this one when running `flutter pub get` on a dart only lib project (which I've created with intellij interface)... the solution for me, was to use `pub get` (from dart sdk folder) instead of `flutter pub get`

**Comment by DLKenrickASU** [comment]
In case anyone else has this problem - I had this issue and then I realized I was trying to launch from the wrong folder (my app was in a sub folder). So I just needed to change directories in the terminal.
