### ISSUE TITLE
Unexpected io:Stdin.any method behaviour

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#32748]
It seems like such a behaviour depends on the terminal properties somehow, however it's absolutely unclear from the Specification.

Dart API Spec reads about the io:Stdin.any method:

> Future<bool> any(bool test(T element))
> Checks whether test accepts any element provided by this stream.
> Completes the Future when the answer is known.

The following test example calls stdin.any method and get an answer when expected line (started with the 0 symbol) appears in stundart input:
``` dart
bool test(s) { return (new String.fromCharCodes(s)).startsWith("0"); }

run() { stdin.any(test).then((x) { stdout.writeln("Get a string!"); }); }

main(List<String> args) async { 
  if(args.length == 0) 
    run(); 
  else {
    String executable = Platform.resolvedExecutable;
    String eScript = Platform.script.toString();
    await Process.start(executable, [eScript], runInShell: true).then(
        (Process process) async {
      process.stdin.writeln("1");
      process.stdin.writeln("2");
      process.stdin.writeln("3");
      process.stdin.writeln("0");
      await process.exitCode.then((int code) async { stdout.writeln("OK"); });
    });
  };
}
```

When I run it in terminal without input arguments, I enter some input lines several times, and I am observing an expected result: dart program exits after a line started with zero appeared, 

Sample output is:
> $> dart -c test.dart
> 1
> 2
> 3
> 0
> Get a string!
> 
> $

However, it seems like only first entered line is checked if I run the test example from another dart process and enter input lines programmicaly. This is a case when I pass some input args to the test. 

If I run
> $> dart -c test.dart run

parent dart  process just hangs, which means stdin.any never works in this case.

Please note that if I am commenting out extra process.stdin.writeln lines, all works fine with me. Also all is OK if I add three stdin.readLineSync(); calls in the run method call.

I. e. both
``` dart
import "dart:io";

bool test(s) { return (new String.fromCharCodes(s)).startsWith("0"); }

run() {
  stdin.readLineSync();
  stdin.readLineSync();
  stdin.readLineSync();
  stdin.any(test).then((x) { stdout.writeln("Get a string!"); }); 
}

main(List<String> args) async { 
  if(args.length == 0) 
    run(); 
  else {
    String executable = Platform.resolvedExecutable;
    String eScript = Platform.script.toString();
    await Process.start(executable, [eScript], runInShell: true).then(
        (Process process) async {
      process.stdin.writeln("1");
      process.stdin.writeln("2");
      process.stdin.writeln("3");
      process.stdin.writeln("0");
      await process.exitCode.then((int code) async { stdout.writeln("OK"); });
    });
  };
}
```

and 
``` dart
import "dart:io";

bool test(s) { return (new String.fromCharCodes(s)).startsWith("0"); }

run() { stdin.any(test).then((x) { stdout.writeln("Get a string!"); }); }

main(List<String> args) async { 
  if(args.length == 0) 
    run(); 
  else {
    String executable = Platform.resolvedExecutable;
    String eScript = Platform.script.toString();
    await Process.start(executable, [eScript], runInShell: true).then(
        (Process process) async {
      process.stdin.writeln("0");
      await process.exitCode.then((int code) async { stdout.writeln("OK"); });
    });
  };
}
```
tests are OK and produces the following output:
> $> dart -c test.dart run
> OK

I've tried this with dart 1.24 and 2.0 on my Windows 7 and Ubuntu desktops with the same result.

**Comment by ds84182** [comment]
Process.stdin is buffered, so in your first example you need a call to [flush](https://api.dartlang.org/stable/1.24.3/dart-io/IOSink/flush.html) and optionally [close](https://api.dartlang.org/stable/1.24.3/dart-io/IOSink/close.html). Otherwise your data will sit in the first process's buffer forever.

Also, when you input a newline in your terminal the stdin is effectively flushed on the terminal's side (which is why the data seems to come in as lines). If you pipe a file in the data won't come in as lines, but as arbitrary chunks of bytes.

stdin is just a stream of bytes, so if you want lines you'll have to transform stdin with [UTF8](https://api.dartlang.org/stable/1.24.3/dart-convert/UTF8-constant.html).[decoder](https://api.dartlang.org/stable/1.24.3/dart-convert/Utf8Codec/decoder.html), then with a [LineSplitter](https://api.dartlang.org/stable/1.24.3/dart-convert/LineSplitter-class.html).

Example:

```dart
stdin.transform(UTF8.decoder).transform(const LineSplitter()).any((line) => line.startsWith("0"))
```

**Comment by kevmoo** [comment]
Please reopen if you fine an issue.
