### ISSUE TITLE
dart2js: implement new nSM semantics

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32750]
* tearoff of a declared, but abstract, method, which is implemented by nSM, should be a valid tearoff object  (we don't give a nSM for reading the getter). Then calling it will call nSM. Example, `(o.foo)` in:
```dart
class A {
  abstract int foo(int y);
  noSuchMethod(Invocation m) => 0;
}
```

* in `compliance` mode, we check the return types for declared abstract methods implemented by nSM. Example, `o.foo(3);` in the code above.

* in `compliance` mode, we check the arguments types types for declared abstract methods implemented by nSM. Example, `o.foo('x');` in the code above should throw a type error, but o.foo('x', 'y') should not.

**Comment by johnniwinther** [comment]
This should be fixed through the CFE issue https://github.com/dart-lang/sdk/issues/32794 which will be resolved by adding the forwarding stubs needed for dart2js.

**Comment by sigmundch** [comment]
great, thanks for looking into it. - I'll mark this as a duplicate.

**Comment by sigmundch** [comment]
@johnniwinther - I believe there is more to this than just the CFE issue with optional args.

Here is an example in dartpad:
   https://dartpad.dartlang.org/8edeabe24a3c0ec19b047630f0a668b7

```dart
abstract class A {
  m(x);
}

class B implements A {
  noSuchMethod(Invocation i) {
    print("nsm call: ${i.memberName}");
    if (i.isGetter) print(" - tearoff");
    if (i.isMethod) print(" - method invocation");
  }
}

void main() {
  A x = new B();
  var tearoff = x.m;
  tearoff(3);
}
```

The example should get the tearoff without getting into the nSM logic, and should print:
```
nsm call: Symbol("m")
 - method invocation
```

Instead, it prints:
```
nsm call: Symbol("m")
 - tearoff
```

and because nSM returns null, it then crashes when calling the result:
```
Uncaught exception:
Cannot read property 'call$1' of undefined
```

**Comment by sigmundch** [comment]
update: this is in progress, fix is almost about to land here https://dart-review.googlesource.com/c/sdk/+/60250.
