### ISSUE TITLE
regression with latest dart roll into flutter

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32757]
The latest dart roll at revision e5d20a7749a15361ccfe47bc4c4e4becb88180b4 into flutter is causing a regression in some of the flutter tools tests 

compiler message: file:///usr/local/google/home/asiva/.pub-cache/hosted/pub.dartlang.org/file-3.0.0/lib/src/backends/record_replay/recording_file_system_entity.dart: Error: Duplicated name: '_delete'.
compiler message: file:///usr/local/google/home/asiva/.pub-cache/hosted/pub.dartlang.org/file-3.0.0/lib/src/backends/record_replay/recording_file_system_entity.dart:104:3: Error: Duplicated name: _delete
compiler message:   Future<T> _delete({bool recursive: false}) => delegate
compiler message:   ^

To reproduce run
/usr/local/google/home/asiva/workspace/flutter-roll/flutter/bin/flutter test --local-engine=host_release

in $FH/flutter/packages/flutter_tools directory.

The range of dart commits that are being used are from
c1432bf7a3669ab4484978a5ceaaf8ad16e459b5 to e5d20a7749a15361ccfe47bc4c4e4becb88180b4

**Comment by jensjoha** [comment]
Hmmm... Also

* https://github.com/google/file.dart/blob/master/lib/src/backends/record_replay/recording_random_access_file.dart#L80 is wrong
* https://github.com/xxgreg/mustache/blob/master/lib/src/renderer.dart#L92-L96 somehow doesn't do type promotion (`The method 'call' isn't defined for the class 'dart.core::Object'.`)
* and also
``` 
$ pkg/front_end/tool/fasta compile --strong pkg/analyzer/lib/analyzer.dart
pkg/analyzer/lib/src/summary/link.dart:421:3: Error: Duplicated name: enclosingElement
  final CompilationUnitElementForLink enclosingElement;
  ^
```

**Comment by jensjoha** [comment]
So it turns out that we probably have never run those tests before... So it failed before, and it still fails now. That explains why it first popped up now and why I couldn't stop reproducing it... 

(Even the dart 1 test should be run in a different way in `flutter_tools` --- at least travis runs it via `cd packages/flutter_tools; ../../bin/cache/dart-sdk/bin/pub run test -j1 -rexpanded`)

As thus, there isn't really any regression. Right?

(I'm not saying that we don't issues that should be addressed, just that it isn't anything new).

**Comment by stefantsov** [comment]
[CL 49460](https://dart-review.googlesource.com/c/sdk/+/49460) should fix the issue with private names and noSuchMethod forwarders.  It also solves the 'Duplicated name' error message when compiling analyzer.dart; although, there is another issue with that file that is likely to not be related to noSuchMethod forwarders.

**Comment by dgrove** [comment]
@a-siva can this be closed now?

**Comment by a-siva** [comment]
The roll had to be reverted because couple of tests failed in the flutter build bot, I am investigating.

**Comment by a-siva** [comment]
A roll of Dart with this has landed, bots have cycled green, so closing this issue.
