### ISSUE TITLE
Provide a way to disable ignore comments

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32767]
Add something, like a `--do-not-ignore` flag, that will allow users to see which errors are being ignored in a code base to make it easier to find and fix them.

**Comment by srawlins** [comment]
Similar to #27218 but this one is certainly easier to implement. I'm happy to take this on; I [fixed](https://dart-review.googlesource.com/c/sdk/+/29548) an `// ignore:` bug not long ago, so I can probably dive in right quick.

**Comment by kevmoo** [comment]
@bwilkerson – bonus points for flagging as errors any `// ignore:` directives that aren't ignoring anything any more...

**Comment by srawlins** [comment]
@kevmoo that would be https://github.com/dart-lang/linter/issues/347.

I think better as a lint. Dangerous to enforce behavior found in user comments.

**Comment by srawlins** [comment]
In Dart 2.13 we landed an analysis option that serves this purpose: [`cannot-ignore`](https://github.com/dart-lang/sdk/blob/75e03d78751ef83cbd434105386f9c88ac018869/CHANGELOG.md#analyzer).
