### ISSUE TITLE
The analyzer should tell what identifier is unknown instead of a hint that the result is dynamic

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32764]
![image](https://user-images.githubusercontent.com/405837/38312621-82a2e1a0-3822-11e8-8bd2-72207c92601a.png)

I think with the Dart 2 semantics this message is quite pointless.

**Comment by bwilkerson** [comment]
I agree. We have a lot of work to do to present the right set of diagnostics to users, and to not display diagnostics that only exist as a result of a prior error. We used to be able to use `dynamic` to silence most follow-on errors, but that doesn't work as well in Dart 2.

**Comment by srawlins** [comment]
Similar to https://github.com/dart-lang/sdk/issues/35828, which perhaps has more commentary.
