### ISSUE TITLE
Analysis server doesn't provide generic type arguments in completion results

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32761]
While writing this code:

```dart
class MyThing<TParam> {
  thing() {
    print(TParam.runtimeType);
  }
}
```

The name `TParam` does not appear in the completion list on line 3 as expected.

(cc @escamoteur)

**Comment by bwilkerson** [comment]
I suppose technically it ought to be included in the list, though the number of times it's useful at the beginning of an expression seems minimal at best so I'd probably sort it near the bottom.

**Comment by bwilkerson** [comment]
Type parameters are now being suggested, though they're very low on the list, so you're likely to need to type the whole name before it gets sorted to the top. Ranking is a different issue, however, so I'm going to close this issue.
