### ISSUE TITLE
dart2js type analysis: missing some inferred receiver types in strong mode

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32771]
```
import 'dart:collection';
main() {
  var a = [2,1,99,1];
  a.sort();
  print(a);
  new UnmodifiableListView(a).sort();
}
```

The comparison `comp == 0` in dualPivotQuicksort is compiled differently in strong mode:

`--trust-type-annotations`:
```js
      if (J.$eq$(compare.call$2(el2, el4), 0)) {
        for (k = less; k <= great; ++k) {
          ak = t1.$index(a, k);
          comp = compare.call$2(ak, el2);
          if (comp === 0)
```

`--strong --omit-implicit-checks`:
```js
      if (J.$eq$(compare.call$2(el2, el4), 0)) {
        for (k = less; k <= great; ++k) {
          ak = t1.$index(a, k);
          comp = compare.call$2(ak, el2);
          if (J.$eq$(comp, 0))
```

The difference is the result of `_typeInferenceMap.receiverTypeOfInvocation(node, closedWorld)` in builder_kernel.dart for the expression `comp.==(0)`:
In the --trust-type-annotations case it is `null|subclass=JSInt]`
In the --strong case it is `null`.

I'm guessing that there is no type annotation (int comp = ...) to 'trust' in strong mode so inference is missing a Narrow node. We should insert known types computed by the frontend's static type analysis.

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/50240
