### ISSUE TITLE
dart2js: allow implicit downcasts in constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32773]
Dart2js's constantifier disallows downcasts. Here is an example: 

```dart
const dynamic b = 3;
class X {
  final int n;
  const X(int a) : n = a ?? b;
}
main() {
  print(const X(2));
}
```

produces:
```sh
dart2js --preview-dart-2 repro.dart
repro.dart:4:22:
Error: Not a compile-time constant.
  const X(int a) : n = a ?? b;
                     ^
Error: Compilation failed.
Finished with a exit code: 1
```

Technically we know the value of `b` here, even though it has a static type as dynamic, we should know better that the cast will succeed and omit it.

Note: we also need to improve the error messages to provide better feedback for why something is not considered a constant. I'll file a bug on this shortly

**Comment by sigmundch** [comment]
@leafpetersen - what does the spec say about this scenario?

/cc @johnniwinther @rakudrama

**Comment by eernstg** [comment]
This topic is being updated in the spec. @lrhn has [a CL](https://dart-review.googlesource.com/c/sdk/+/36220) in the pipeline which will introduce the notion of a potentially constant type expression and give substantially more robustness to the notion of a potentially constant expression. I expect an additional update [here](https://github.com/dart-lang/sdk/blob/2676c132cbfd88befcecc544b2e902c255e44b34/docs/language/dartLangSpec.tex#L2056) saying that it is a compile-time error if the initializing expression of a const constructor initializer is not a _potentially_ constant expression (currently it says 'constant expression', which means that today it is actually a compile time error to have `class C { final x; const C(v): x = v; }`, and y'all thought that was ok, right? ;-).

In this proposal, a potentially constant expression does not rely on types, it only checks the shape of the expression. So `e1 + e2` is potentially constant if `e1` and `e2` are potentially constant, which means that it's still perfectly fine if they are both variables of type `dynamic` (there's your implicit downcast, except that _all_ casts are allowed, not just downcasts), or even if one is of type `Foo` and the other is a `String`, or whatever.

We may need to strengthen the notion of potentially constant expressions, for several reasons (or create an additional concept which is more strict). However, I do not expect the rules to be more strict than the ones we are using for expressions in general, and in particular I certainly wouldn't expect the rules to prevent things like `a + b` when `a` is `int` and `b` is dynamic, and `b + a` would very likely also be accepted.

So the answer at this point is "the specification of initializers need updates, no matter what", and then "downcasts are unlikely to be rejected".

(With `--no-implicit-downcasts` we would of course treat these downcasts just like other downcasts, but we don't specify that in detail, at least not currently.)

**Comment by sigmundch** [comment]
>  Is the issue that the implicit down-cast makes the expression look like `a + (b as num)`? 

Precisely. The new text regarding `e as T` in your CL is exactly what I was looking for. Constant evaluation will prove that `b`'s value is indeed `num`, the cast will succeed and the constant will be allowed.

Thanks for the quick answer!
