### ISSUE TITLE
dart2js: allow instantiations in constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32774]
Here is an example:
```dart
void _m<T>(T x) => null;
typedef F = void Function(Object request);

class X {
  X({F f: _m});
}

main () => print(new X());
```

in strongmode this produces:
```
repro.dart:5:11:
Error: Not a compile-time constant.
  X({F f: _m});
          ^
```

Changing the type of F to be a generic function gets rid of the error.

**Comment by sigmundch** [comment]
Similarly @leafpetersen - what does the spec say about this other scenario?

/cc @johnniwinther @rakudrama

**Comment by eernstg** [comment]
The question here is whether expressions subject to generic function instantiation can be constant. We have a proposed feature spec on generic function instantiation [here](https://dart-review.googlesource.com/c/sdk/+/47043), and in this proposal `_m` is indeed a compile-time constant, because the denoted function `_m` is top-level and the inferred type argument list (`<int>`) consists of compile-time constant type expressions. The latter is defined in [this CL](https://dart-review.googlesource.com/c/sdk/+/36220).

So, @leafpetersen & @lrhn, can we proceed with those CLs, or maybe confirm these details here, separately?

**Comment by lrhn** [comment]
I agree that the expression is constant.

The generic function is a top-level/static function, so it is itself a constant.
The type argument is compile-time constant, so this particular instantiation syntax will only ever need to create one value. That makes it viable to make it compile-time constant,.

**Comment by sigmundch** [comment]
A related question: what should we say about equality of these instantiations. For instance, what does this program print?

```dart
void _m<T>(T x) => null;
typedef F = void Function(int request);

class X {
  final F f;
  X(this.f);
}

main () {
  const F a = _m;
  F b = _m;
  var x = const X(_m);
  print(a == b);
  print(a == x.f);
  print(b == x.f);
}
```

**Comment by sigmundch** [comment]
@kmillikin @peter-ahe-google - we are trying to figure out what's the right place to handle this part of the spec. It seems that the FE might be the right place for it. Thoughts?

One approach that comes to mind is to do something similar to what we did with the deferred.loadLibrary tearoffs. We'd generate a synthetic method to represent the instantiations. In the example above, this could be:

```dart
void __m_int(int x) => _m<int>(x);
...
main() {
  const F a = __m_int;
  F b = __m_int;
  var x = const X(__m_int);
  ...
}
```

Background context: we discovered this issue while turning on strong-mode in dart2js for internal customers.

**Comment by sigmundch** [comment]
(and thanks Erik for the quick responses!)

**Comment by eernstg** [comment]
(until now &mdash; just about to go home &mdash; but thanks! ;-)

**Comment by rakudrama** [comment]
I don't think the local source rewrite would work.

Consider:
common.dart:
```dart
List<T> singleton<T>(T x) => [x];
```

Library1:
```dart
import "common.dart";
List<int> Function(int) wrap1 = singleton;
```
Library2:
```dart
import "common.dart";
List<int> Function(int) wrap2 = singleton;
```

It is not clear how the injected local functions _singleton_int could achieve `identical(wrap1, wrap2)` or even `wrap1 == wrap2`.

dart2js could do global constant de-duping, but only if we add a new kind of constant expression for instantiations.

**Comment by eernstg** [comment]
I can see how this would need to be handled carefully in a modular compilation setting, but don't we have at least some relevant techniques and data structures that are used to make the following print 'true'?:

```dart
// FILE n008a.dart.
const s1 = "Hello";

// FILE n008b.dart.
const s2 = "Hello";

// FILE n008.dart.
import 'n008a.dart';
import 'n008b.dart';

main() => print(identical(s1, s2)); // 'true'
```

**Comment by peter-ahe-google** [comment]
I think we just need to add `isConst` to Instantiation. Then we should be able to represent this as:

```
new Instantiation(new StaticGet(_m), <DartType>[coreTypes.objectClass.rawType], isConst: true);
```

What am I missing?

**Comment by sigmundch** [comment]
@peter-ahe-google - I think you are correct. We probably only need a small piece like that. Then dart2js can canonicalize them like we do with all other constants.
