### ISSUE TITLE
Deadlock in the GC

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#32786]
I'm seeing this on the buildbot today, starting with f2bf297aa47398f993d2e35e3ce7e4ea2ab47e3c but it looks unrelated to that change.

Repro with:

pkg/vm/tool/dart2 --old_gen_heap_size=10 --optimization-counter-threshold=5 --old-gen-heap-size=10 --verbose-gc --sync-async --ignore-unrecognized-flags --packages=/usr/local/google/home/erikcorry/dart/sdk/.packages /usr/local/google/home/erikcorry/dart/sdk/tests/standalone_2/map_insert_remove_oom_test.dart

It happens about 25% of the time on my workstation.

Stack trace:

#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000009f06c6 in dart::Monitor::WaitMicros (this=0x29b7978, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:444
#2  0x000000000094e1a6 in dart::MonitorLocker::WaitWithSafepointCheck (this=0x7f51f2e3ce50, thread=0x3500000, millis=0) at ../../runtime/vm/lockers.cc:17
#3  0x000000000092309d in BeginNewSpaceGC (this=0x29b6d00, thread=0x3500000) at ../../runtime/vm/heap.cc:316
#4  dart::Heap::CollectNewSpaceGarbage (this=0x29b6d00, thread=0x3500000, reason=dart::Heap::kNewSpace) at ../../runtime/vm/heap.cc:392
#5  0x0000000000922289 in CollectGarbage (this=<optimized out>, space=dart::Heap::kNew) at ../../runtime/vm/heap.cc:453
#6  dart::Heap::AllocateNew (this=0x29b6d00, size=32) at ../../runtime/vm/heap.cc:72
#7  0x0000000000957b0d in Allocate (this=0x29b79a4, size=32, space=dart::Heap::kNew) at ../../runtime/vm/heap.h:72
#8  dart::Object::Allocate (cls_id=37, size=32, space=dart::Heap::kNew) at ../../runtime/vm/object.cc:1967
#9  0x00000000009717b7 in dart::UnhandledException::New (exception=..., stacktrace=..., space=dart::Heap::kNew) at ../../runtime/vm/object.cc:15551
#10 0x0000000000914fdc in dart::ThrowExceptionHelper (thread=0x3500000, incoming_exception=..., existing_stacktrace=..., is_rethrow=false) at ../../runtime/vm/exceptions.cc:624
#11 0x0000000000957bdd in dart::Object::Allocate (cls_id=71, size=240, space=<optimized out>) at ../../runtime/vm/object.cc:1973
#12 0x000000000095b556 in New (class_id=71, len=27, space=dart::Heap::kOld) at ../../runtime/vm/object.cc:21798
#13 dart::Array::New (len=27, space=dart::Heap::kOld) at ../../runtime/vm/object.cc:21775
#14 0x0000000000b177dd in dart::FlowGraphCompiler::CreateDeoptInfo (this=0x7f51f2e3d3c8, assembler=<optimized out>) at ../../runtime/vm/compiler/backend/flow_graph_compiler.cc:877
#15 0x0000000000c1d7a6 in dart::CompileParsedFunctionHelper::FinalizeCompilation (this=0x7f51f2e3e3d0, assembler=0x7f51f2e3d740, graph_compiler=<optimized out>, flow_graph=0x30a4f60) at ../../runtime/vm/compiler/jit/compiler.cc:577
#16 0x0000000000c1eea1 in dart::CompileParsedFunctionHelper::Compile (this=0x7f51f2e3e3d0, pipeline=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:898
#17 0x0000000000c1f819 in dart::CompileFunctionHelper (pipeline=0x7f51f2e3e598, function=..., optimized=true, osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:999
#18 0x0000000000c205a6 in dart::Compiler::CompileOptimizedFunction (thread=0x3500000, function=..., osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:1266
#19 0x0000000000c21f26 in dart::BackgroundCompiler::Run (this=0x2962ed0) at ../../runtime/vm/compiler/jit/compiler.cc:1706
#20 0x0000000000ae058d in dart::ThreadPool::Worker::Loop (this=0x295e2d0) at ../../runtime/vm/thread_pool.cc:381
#21 0x0000000000ae0431 in dart::ThreadPool::Worker::Main (args=43377360) at ../../runtime/vm/thread_pool.cc:436
#22 0x00000000009efd69 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:135
#23 0x00007f51fa14b494 in start_thread (arg=0x7f51f2e3f700) at pthread_create.c:333
#24 0x00007f51f93e4a8f in clone () from /lib/x86_64-linux-gnu/libc.so.6

#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000009f06c6 in dart::Monitor::WaitMicros (this=0x29646c0, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:444
#2  0x000000000094e1a6 in dart::MonitorLocker::WaitWithSafepointCheck (this=0x7fff93facdf0, thread=0x297bb00, millis=0) at ../../runtime/vm/lockers.cc:17
#3  0x0000000000aa794f in dart::SafepointHandler::SafepointThreads (this=0x296d3a0, T=0x297bb00) at ../../runtime/vm/safepoint.cc:73
#4  0x0000000000aae19e in dart::Scavenger::Evacuate (this=0x29b6d08) at ../../runtime/vm/scavenger.cc:981
#5  0x00000000009237a4 in dart::Heap::EvacuateNewSpace (this=0x29b6d00, thread=0x297bb00, reason=dart::Heap::kFull) at ../../runtime/vm/heap.cc:381
#6  0x0000000000922482 in CollectAllGarbage (this=<optimized out>, reason=dart::Heap::kFull) at ../../runtime/vm/heap.cc:462
#7  dart::Heap::AllocateOld (this=0x29b6d00, size=48, type=dart::HeapPage::kData) at ../../runtime/vm/heap.cc:98
#8  0x0000000000957b2c in dart::Object::Allocate (cls_id=74, size=48, space=dart::Heap::kOld) at ../../runtime/vm/heap.h:76
#9  0x00000000009c9941 in New (len=21, space=dart::Heap::kOld) at ../../runtime/vm/object.cc:21244
#10 dart::OneByteString::Concat (str1=..., str2=..., space=dart::Heap::kOld) at ../../runtime/vm/object.cc:21347
#11 0x0000000000955d6d in dart::String::Concat (str1=..., str2=..., space=dart::Heap::kOld) at ../../runtime/vm/object.cc:20877
#12 0x0000000000ad713b in dart::ConcatString::ToSymbol (this=0x7fff93fad168) at ../../runtime/vm/symbols.cc:137
#13 0x0000000000adb647 in NewKey (concat=...) at ../../runtime/vm/symbols.cc:188
#14 dart::HashSet<dart::UnorderedHashTable<dart::SymbolTraits, 0l> >::InsertNewOrGet<dart::ConcatString> (this=0x7fff93fad108, key=...) at ../../runtime/vm/hash_table.h:664
#15 0x0000000000ad8a11 in dart::Symbols::NewSymbol<dart::ConcatString> (thread=0x297bb00, str=...) at ../../runtime/vm/symbols.cc:568
#16 0x0000000000ad87fb in dart::Symbols::FromConcat (thread=0x297bb00, str1=..., str2=...) at ../../runtime/vm/symbols.cc:455
#17 0x00000000008b6c99 in dart::ClassFinalizer::ResolveAndFinalizeMemberTypes (cls=...) at ../../runtime/vm/class_finalizer.cc:1577
#18 0x00000000008bbc07 in dart::ClassFinalizer::FinalizeClass (cls=...) at ../../runtime/vm/class_finalizer.cc:2699
#19 0x0000000000c1d60d in dart::Compiler::CompileClass (cls=...) at ../../runtime/vm/compiler/jit/compiler.cc:493
#20 0x000000000096b6ea in dart::Class::EnsureIsFinalized (this=0x35d1fe0, thread=0x297bb00) at ../../runtime/vm/object.cc:3188
#21 0x0000000000976c1f in dart::Class::LookupFunctionAllowPrivate (this=0x35d1fe0, name=..., kind=dart::Class::kAny) at ../../runtime/vm/object.cc:4241
#22 0x0000000000bea4de in dart::kernel::TranslationHelper::LookupStaticMethodByKernelProcedure (this=<optimized out>, procedure=...) at ../../runtime/vm/compiler/frontend/kernel_to_il.cc:639
#23 0x0000000000bd56e7 in dart::kernel::StreamingFlowGraphBuilder::BuildStaticInvocation (this=0x7fff93fae780, is_const=<optimized out>, p=<optimized out>) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:7680
#24 0x0000000000bc9460 in dart::kernel::StreamingFlowGraphBuilder::BuildExpression (this=0x7fff93fae780, position=0x2964600) at ../../runtime/vm/kernel_binary.h:220
#25 0x0000000000bd107d in dart::kernel::StreamingFlowGraphBuilder::BuildPropertyGet (this=0x7fff93fae780, p=<optimized out>) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:6767
#26 0x0000000000bc9575 in dart::kernel::StreamingFlowGraphBuilder::BuildExpression (this=0x7fff93fae780, position=0x2964600) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5199
#27 0x0000000000bdcb87 in dart::kernel::StreamingFlowGraphBuilder::BuildReturnStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:9193
#28 0x0000000000bcb9f6 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5340
#29 0x0000000000bd9cf8 in dart::kernel::StreamingFlowGraphBuilder::BuildBlock (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:8589
#30 0x0000000000bcb956 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5312
#31 0x0000000000bdc9f5 in dart::kernel::StreamingFlowGraphBuilder::BuildIfStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:9164
#32 0x0000000000bcb9e6 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5338
#33 0x0000000000bd9cf8 in dart::kernel::StreamingFlowGraphBuilder::BuildBlock (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:8589
#34 0x0000000000bcb956 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5312
#35 0x0000000000bdc9f5 in dart::kernel::StreamingFlowGraphBuilder::BuildIfStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:9164
#36 0x0000000000bcb9e6 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5338
#37 0x0000000000bd9cf8 in dart::kernel::StreamingFlowGraphBuilder::BuildBlock (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:8589
#38 0x0000000000bcb956 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement (this=0x7fff93fae780) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5312
#39 0x0000000000bcfac4 in dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction (this=0x7fff93fae780, constructor=false) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:4944
#40 0x0000000000bd084a in dart::kernel::StreamingFlowGraphBuilder::BuildGraph (this=0x7fff93fae780, kernel_offset=140735676082824) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:5152
#41 0x0000000000bf2ee8 in dart::kernel::FlowGraphBuilder::BuildGraph (this=0x7fff93fae918) at ../../runtime/vm/compiler/frontend/kernel_to_il.cc:1961
#42 0x0000000000c1bd9a in dart::DartCompilationPipeline::BuildFlowGraph (this=<optimized out>, zone=<optimized out>, parsed_function=<optimized out>, ic_data_array=..., osr_id=<optimized out>, optimized=<optimized out>)
    at ../../runtime/vm/compiler/jit/compiler.cc:163
#43 0x0000000000c1e84f in dart::CompileParsedFunctionHelper::Compile (this=0x7fff93fafae0, pipeline=0x7fff93fafc60) at ../../runtime/vm/compiler/jit/compiler.cc:815
#44 0x0000000000c1f819 in dart::CompileFunctionHelper (pipeline=0x7fff93fafc60, function=..., optimized=false, osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:999
#45 0x0000000000c1f242 in dart::Compiler::CompileFunction (thread=0x297bb00, function=...) at ../../runtime/vm/compiler/jit/compiler.cc:1186
#46 0x0000000000c1c28d in DRT_HelperCompileFunction (thread=<optimized out>, arguments=..., isolate=<optimized out>, zone=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:250
#47 dart::DRT_CompileFunction (arguments=...) at ../../runtime/vm/compiler/jit/compiler.cc:246

**Comment by a-siva** [comment]
closing as obsolete.
