### ISSUE TITLE
edit.getRefactoring (extract_method) returns a warning about method name that wasn't supplied

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32780]
I'm investigating an issue I have with some tests that handle refactorings. The cause seems to be unexpected warnings coming back for a getRefactoring.

Note: I've just sent an `updateContent` before this which I haven't had a response to, but I assume the server processes requests in-order and that I don't need to block everything waiting for a response - this may be incorrect, though I'm not sure it explains the error).

The request I send has no options for the rename (I haven't got the name yet), but the error message suggests that I provided an invalid method name.

```js
	{
		"id": "139",
		"method": "analysis.updateContent",
		"params": {
			"files": {
				"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart": {
					"edits": [
						{
							"id": "",
							"length": 40,
							"offset": 0,
							"replacement": "\nmain() {\n  print(\"Hello, world!\");\n}\n\t\t"
						}
					],
					"type": "change"
				}
			}
		}
	},
	{
		"id": "140",
		"method": "edit.getRefactoring",
		"params": {
			"file": "/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart",
			"kind": "EXTRACT_METHOD",
			"length": 23,
			"offset": 12,
			"validateOnly": true
		}
	},
	{
		"id": "139",
		"result": {}
	},
	{
		"id": "140",
		"result": {
			"initialProblems": [],
			"optionsProblems": [],
			"finalProblems": [
				{
					"severity": "WARNING",
					"message": "Method name should start with a lowercase letter."
				}
			],
			"feedback": {
				"offset": 12,
				"length": 23,
				"returnType": "void",
				"names": [],
				"canCreateGetter": false,
				"parameters": [],
				"offsets": [
					12
				],
				"lengths": [
					23
				]
			}
		}
	}
```

@bwilkerson

**Comment by DanTup** [comment]
Ok, if I comment out an earlier test (which doesn't touch these files), I see this test work - it no longer gets `finalProblems`!:

```js
[
	{
		"id": "104",
		"method": "analysis.updateContent",
		"params": {
			"files": {
				"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart": {
					"edits": [
						{
							"id": "",
							"length": 40,
							"offset": 0,
							"replacement": "\nmain() {\n  print(\"Hello, world!\");\n}\n\t\t"
						}
					],
					"type": "change"
				}
			}
		}
	},
	{
		"id": "104",
		"result": {}
	},
	{
		"id": "105",
		"method": "edit.getRefactoring",
		"params": {
			"file": "/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart",
			"kind": "EXTRACT_METHOD",
			"length": 23,
			"offset": 12,
			"validateOnly": true
		}
	},
	{
		"id": "105",
		"result": {
			"initialProblems": [],
			"optionsProblems": [],
			"finalProblems": [],
			"feedback": {
				"offset": 12,
				"length": 23,
				"returnType": "void",
				"names": [],
				"canCreateGetter": false,
				"parameters": [],
				"offsets": [
					12
				],
				"lengths": [
					23
				]
			}
		}
	}
]
```

**Comment by DanTup** [comment]
Ugh, this doesn't repro on latest code. It could be a race condition, but most likely it's fixed (Dart Code's tests run on both stable and dev, and it the failures on dev are on different tests).

I'll just mark this test as skip for Dart v1.

**Comment by bwilkerson** [comment]
> ... I assume the server processes requests in-order and that I don't need to block everything waiting for a response ...

Correct. Every request is handled in the order in which it was received.

> ... depending on what tests run before it ...

Are your tests independent of one another? Does each test start up a new instance of the server, for example?

**Comment by DanTup** [comment]
> Are your tests independent of one another? Does each test start up a new instance of the server, for example?

Not currently - they're grouped by suites. They do close all files (discarding changes) in between so in theory the behaviour should be the same - I can't think of any state the server would keep around that could affect things. We could restart it (we have a relatively quick way to restart without having to reload the extension now) but I think this way it's maybe more likely to catch bugs (even if they're not specifically the ones the tests were designed for!).

To fix the above, I basically ignore non-fatal errors during the validation stage (since they'll show up during the real rename anyway). Maybe the user would rather we tell them about their issue before they provide the new name, but this can easily be tweaked later (the original implementation would block the rename on any warning at all during the validate stage, which seems a bit aggressive, especially when the later code prompted them asking them whether to go ahead!).
