### ISSUE TITLE
dart2js: allow "* == null" in constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32791]
See spec change: https://dart-review.googlesource.com/c/sdk/+/36220/6/docs/language/dartLangSpec.tex#3168

**Comment by srawlins** [comment]
I believe this landed with const-update-2018 ([CHAGELOG](https://github.com/dart-lang/sdk/blob/2.5.0/CHANGELOG.md#language)).

**Comment by sigmundch** [comment]
thanks! yes.
