### ISSUE TITLE
Dart doesn't read Docker Container limits properly

### ISSUE THREAD

**Issue by fkorotkov** [dart-lang/sdk#32799]
I've noticed that Dart 2.0 doesn't read CPU limits properly when it is executed inside of a Docker container. Precisely, `Platform.numberOfProcessors` returns amount of host CPUs. Here is a snippet to reproduce the issue: 

```
docker run --cpus=1 -it google/dart:2.0-dev
root@ea0d883ab53c:/# echo "import 'dart:io'; main() { print(Platform.numberOfProcessors); }" > main.dart
root@ea0d883ab53c:/# dart main.dart 
4
root@ea0d883ab53c:/# 
```

As you can see I limited the container to only one CPU, but `Platform.numberOfProcessors` is equal to 4.

**Comment by rmacnak-google** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/29786
