### ISSUE TITLE
Question about template/generic functions

### ISSUE THREAD

**Issue by BenKerry** [dart-lang/sdk#32793]
Version: 2.0.0-dev.35.flutter-290c576264 (Mon Mar 12 14:25:01 2018 +0000) on "windows_x64"

While playing around with Darts template/generic functions I came across the following odd behaviour which I don't understand at all. Is this a kind of bug or expected? If this is how it should be, why it has to be this way? It doesn't make sense for me, but I have the feeling I am overseeing something important here.

#### Source Code
```dart
void test<T>() {
  if (T is int) {
    print('int');
  } else if (T is String) {
    print('String');
  } else {
    print('no int but $T');
  }
}

void main() {
  test<bool>();
  test<int>();
  test<double>();
  test<String>();
}
```
#### Output
```
$ dart lib/example.dart
no int but dynamic
no int but dynamic
no int but dynamic
no int but dynamic
```
```
$ flutter run -t lib/example.dart
I/flutter (16751): no int but dynamic
I/flutter (16751): no int but dynamic
I/flutter (16751): no int but dynamic
I/flutter (16751): no int but dynamic
```
```
$ flutter run --preview-dart-2 -t lib/example.dart
I/flutter (16167): no int but bool
I/flutter (16167): no int but int
I/flutter (16167): no int but double
I/flutter (16167): no int but String
```
#### Expected output
```
$ dart lib/example.dart
no int but bool
int
no int but double
String
```

**Comment by zoechi** [comment]
Try running with `dart --preview-dart-2 --reify-generic-functions`
This should lead to different print output.
`is` is to check if a value of a specific type.
`T` is always of type `Type`, so `T is int` will always return `false`.
Try `==` instead of `is`

**Comment by zoechi** [comment]
`--reify-generic-functions` seems to be included in `--preview-dart-2` already in
`Dart VM version: 2.0.0-dev.45.0 (Wed Apr 4 16:01:54 2018 +0200) on "macos_x64"`

**Comment by BenKerry** [comment]
All right, thanks. `==` instead of `is` did the trick.
#### Source Code
```dart
void test<T>() {
  if (T == int) {
    print('int');
  } else if (T == String) {
    print('String');
  } else {
    print('no int but $T');
  }
}

void main() {
  test<bool>();
  test<int>();
  test<double>();
  test<String>();
}
```
#### Output
```
$ dart lib/example.dart
no int but dynamic
no int but dynamic
no int but dynamic
no int but dynamic
```
```
$ dart --preview-dart-2 lib/example.dart
no int but bool
int
no int but double
String
```
