### ISSUE TITLE
Dart2: ListBase.whereType does not throw

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32797]
... which again, caused a user to use it, and almost leak into production failing in Dart2JS.

`sdk/lib/collection/list.dart`

... internal issue is b/74387404 if we need it patched.

/cc @lrhn @leafpetersen

**Comment by matanlurey** [comment]
That's what it seems like (or the DDC SDK was not regenerated).

**Comment by leafpetersen** [comment]
It's not an SDK regen thing - code search for it.
