### ISSUE TITLE
CFE does not check usage of the type `void` correctly

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#32804]
The following tests are missing a lot of compile-time errors for illegal use of `void`:
```void_type_callbacks_test
void_type_function_types_test
void_type_override_test
void_type_usage_test
```

Reproduction: `python tools/test.py -m release -c fasta --strong language_2/void_type_callbacks_test`

**Comment by askeksa-google** [comment]
Probably a duplicate of https://github.com/dart-lang/sdk/issues/30470
