### ISSUE TITLE
html: change type of registerElement2 to return void

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32809]
We noticed an issue with _registerCustomElement and registerElement2: https://github.com/dart-lang/sdk/blob/master/tools/dom/src/dart2js_CustomElementSupport.dart#L69

They are declared to return Function, but the underlying function they return is a Javascript function, not a Dart function, so the current returned value cannot be used as it is.

Because the regular registerElement API returns void, and people can create the custom elements directly by using document.createElement, we think we could simply not expose the returned constructor function entirely, and instead make registerElement2 and _registerCustomElement return void.

**Comment by sigmundch** [comment]
never mind - we found a way to declare the correct behavior here. Turns out that JavaScriptFunction does implement Function, so we can use that in the JS('') annotation.

**Comment by terrylucas** [comment]
Is it  in the @return annotation?
