### ISSUE TITLE
Meta-issue for https://github.com/flutter/flutter/issues/16328

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32818]
https://github.com/flutter/flutter/issues/16328#issuecomment-379436819

**Comment by a-siva** [comment]
@jensjoha looks like we have another incremental compilation issue, we seem to get an invalid kernel file resulting in an 'Unexpected Tag' error.

04-06 22:48:51.116  5882  5909 I flutter : The following _CompileTimeError was thrown building MyApp(dirty):
04-06 22:48:51.116  5882  5909 I flutter : 'file:///Users/tvolkert/AndroidStudioProjects/startup_namer/lib/main.dart': error: Unexpected tag 1
04-06 22:48:51.116  5882  5909 I flutter : (Something) in MyApp.build, expected a procedure, a constructor or a function node
04-06 22:48:51.116  5882  5909 I flutter :

**Comment by aam** [comment]
I believe there are two issues here: first is that our incremental compilation process doesn't recognize changes to `.packages` file which results in compilation error 
```
Performing hot reload...                                         
compiler message: Error: Could not resolve the package 'english_words' in 'package:english_words/english_words.dart'.
compiler message: package:english_words/english_words.dart: Error: Not found: package:english_words/english_words.dart.
I/flutter ( 2121): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2121): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter ( 2121): 'file:///Users/aam/projects/flutter/sample2/startup_namer/lib/main.dart': error: Unexpected tag 1
I/flutter ( 2121): (Something) in MyApp.build, expected a procedure, a constructor or a function node
```

and second error is that second attempt to hot-reload such kernel file crashes VM.

**Comment by jensjoha** [comment]
Handling of changed .packages should be fixed with https://dart-review.googlesource.com/c/sdk/+/49901.
