### ISSUE TITLE
confusing linter hints about lowerCamelCase usage.

### ISSUE THREAD

**Issue by ohir** [dart-lang/sdk#32813]
Both  `constant_identifier_names` and `non_constant_identifier_names` rules hints user
to use lowerCamelCase for respective identifier name. While it is [documented](http://dart-lang.github.io/linter/lints/) it is contradicting also in the docs. Both [constant](http://dart-lang.github.io/linter/lints/constant_identifier_names.html) and [non_constant](http://dart-lang.github.io/linter/lints/non_constant_identifier_names.html) style rules call for `lowerCamelCase`.

[constant_identifier_names](http://dart-lang.github.io/linter/lints/constant_identifier_names.html) says:
> PREFER using lowerCamelCase for constant names.

but [non_constant_identifier_names](http://dart-lang.github.io/linter/lints/non_constant_identifier_names.html) says otherwise:

> DO name non-constant identifiers using lowerCamelCase.
 
```
Dart version 2.0.0-dev.35.flutter-290c576264
Flutter (Channel beta, v0.2.3, on Linux, locale pl_PL.utf8)

% cat -n lib/foo.dart
     1	int UpperCamelVar = 0;
     2	const int UpperCamelConst = 0;

lint • Name non-constant identifiers using lowerCamelCase at lib/foo.dart:1:5 • non_constant_identifier_names
lint • Prefer using lowerCamelCase for constant names at lib/foo.dart:2:11 • constant_identifier_names
```

It is confusing for a newcomer. It is legitimate to have contradicting options on the belt but linter **should** also check its own `analysis_options.yaml` file and **warn about contradicting options**. IMHO of course.

**Comment by zoechi** [comment]
I don't get what is contradicting.
According to the Dart style guide constant and non-constant names should use `lowerCamelCase`.
The Dart team decided that there is no good reason to use different styles for constants and non-constants, so both should use the same.

**Comment by ohir** [comment]
@zoechi 
> "constants and non-constants [so] both should use the same".

So both linter messages should just say **"Use `lowerCamelCase` for identifiers. Use `UpperCamelCase` for Types"**.
Reported confusion stems from two separate messages, way different in wording, describing the same class of undesirable style.

Alas in the docs I see two separate points `DO name other identifiers using lowerCamelCase` and `PREFER using lowerCamelCase for constant names`. In my opinion `PREFER` has no place in Style Guide at all. The very existence of lint-enforced Style Guide is about consistency. If I internalize Style Guide and abide to it I should not be distracted by *Maybe*'s regarding meaning of the seen form.

**Comment by zoechi** [comment]
Your take is that the style guide should be absolute, the Dart teams take is that some rules are just too controversial to be forced onto everybody and therefore the teams should figure out for themselves how important certain rules are for them.

You can of course try to convince the Dart team to change the style guide, but I guess the chances are better if you first try to convince the Dart community to agree on a set of rules and then ask the Dart team to update the style guide accordingly.

**Comment by ohir** [comment]
:) OK. I just tried to convince the Dart team with this issue. Now I humbly accept the answer and close.

**Comment by zoechi** [comment]
@ohir I'm not part of the Dart team. I just tried to get more information out what the issue is about exactly.
