### ISSUE TITLE
Test CFE with optional new/const on large code bases

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32820]
dartfmt with Leaf’s extra hacks here: https://github.com/dart-lang/dart_style/tree/no-new-const-context
Result of running that on DDC, sdk libraries, and dart2js here: https://dart-review.googlesource.com/c/sdk/+/50100
Result of running that on flutter/examples here: https://github.com/leafpetersen/flutter/tree/optional_new_const

(this is part of the work for finishing optional new/const)

**Comment by leafpetersen** [comment]
I ran my version of dartfmt on a flutter checkout (including all of the dart files in the repo) to remove all new keywords and all unnecessary const keywords.  Then I ran the current flutter engine (version listed below) on all of the flutter examples that I could figure out how to run, plus a selection of open source projects (again, removing new and const from each app in addition to the framework).  I saw no new/const related compile failures.  More details below.

```
Flutter 0.2.11-pre.16 • channel unknown • unknown source
Framework • revision 1846ce1d5a (2 hours ago) • 2018-04-10 12:44:21 -0700
Engine • revision 6474647f52
Tools • Dart 2.0.0-dev.46.0.flutter-ef926f98f5
```

From flutter/examples/, all of the following compile and run
```
flutter_gallery
flutter_view
stocks
platform_channel
```
From: https://github.com/Solido/awesome-flutter#open-source-apps

These compile and run:
```
flutter_planets_tutorial
friendly_chat step 5
flutter_news // needed pubspec updates, has Dart 2 runtime errors, but compiles and loads
Fluvies // runtime errors, but compiles and loads
plantly // compiles and loads
```

These have unrelated compile failures:
```
cooking-app-flutter // createHttp
lime_flutter // unrelated Dart 2 errors
flitch // Flutter API change on InputDecoration?  hideDivider not there?
wiki-flutter // Unrelated Dart 2 errors
dart_hub // Unrelated Dart 2 errors
CryptoShadow // Unrelated Dart 2 errors
```

These had missing dependencies, or other setup required (e.g. setting up FireBase accounts) that I couldn't quickly resolve
```
Meme Chat
Flitter
NewsBuzz
DroidKaigi2018-flutter
Heroes Companion
CryptoShadow
Trovami
Music Player
```

**Comment by dgrove** [comment]
Is there any remaining work to do here, @kmillikin ?

**Comment by dgrove** [comment]
Closing this, as testing for Beta 3 is complete.
