### ISSUE TITLE
Type errors should always help differentiate same-named distinct classes

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#32825]
This error

```
  error • The argument type 'List<Foo> (/usr/lib/google-dartlang/lib/core/list.dart)' can't be assigned to the parameter type 'List<Foo> (/usr/lib/google-dartlang/lib/core/list.dart)' at c.dart:5:13 • argument_type_not_assignable
```

does not give sufficient information if the error is because of multiple different classes called `Foo`. This has come up several times recently because we're doing a migration which involves forking classes to new versions with the same name that have to coexist for a while.

```
// a.dart
class Foo {}
List<Foo> get foos => <Foo>[];

// b.dart
class Foo {}

void takesFoos(List<Foo> foos) {}

// c.dart
import 'a.dart';
import 'b.dart';

void main() {
  takesFoos(foos);
}
```
It may be that it makes to have a code path that deals specifically with the error being due to same-named distinct classes, since this is potentially so confusing.

**Comment by a-siva** [comment]
Could you specify which tool you were running ?

**Comment by davidmorgan** [comment]
The error message comes from the analyzer, via DDC.

**Comment by srawlins** [comment]
Duplicate of #32178
