### ISSUE TITLE
Analyzer doesn't recognize consts from different files when created with implicit const

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32823]
The command line analyzer incorrectly reports an error when the argument of a switch case is a constant **from another file** created with an implicit const.  See the example below.  Tested with

dartanalyzer version 2.0.0-dev.43.0

and also with bleeding edge with both of these patched in:
 https://dart-review.googlesource.com/c/sdk/+/50120.
 https://dart-review.googlesource.com/c/sdk/+/49834.

Error messages are:
```dart
  error • Const variables must be initialized with a constant value at /Users/leafp/tmp/ddctest.dart:9:13 • const_initialized_with_non_constant_value
  error • Const variables must be initialized with a constant value at /Users/leafp/tmp/ddctest.dart:10:13 • const_initialized_with_non_constant_value
  error • Case expressions must be constant at /Users/leafp/tmp/ddctest.dart:13:12 • non_constant_case_expression
```

Note that implicit  const created values are recognized as const from the current file, but not from a separate file.

lib.dart
```dart
class C {
  const C();
  static const C WARNING = C();
  static const C ERROR = const C();
}
```

test.dart
```dart
import "lib.dart" ;

class D {
  const D();
  static const D WARNING = D();
}

void test(C x, D y) {
  const a = C.WARNING;
  const b = C.WARNING;
  const d = D.WARNING;
  switch (x) {
      case C.WARNING:
        break;
      case C.ERROR:
        break;
      default:
        break;
  }
  switch (y) {
      case D.WARNING:
        break;
      default:
        break;
  }
}
void main() {
  test(C.WARNING, D.WARNING);
}
```

**Comment by a14n** [comment]
It reminds me #31835 (issue with const and several files)

**Comment by leafpetersen** [comment]
I'm going to take a look at this for a bit, but if anyone more competent comes along feel free to steal it from me... :)

**Comment by leafpetersen** [comment]
Brian and I looked at this today.  The summary synthesis code is serializing the initialize for code like `  static const C WARNING = C();` as if the call to `C` was a method invocation.  In lib/src/summary/summarize_const_expr.dart, the code goes down this path:

```dart
    } else if (expr is MethodInvocation) {
      _serializeMethodInvocation(expr);
```

Not sure what the right architectural solution is for this code: perhaps just allow these as potentially valid constant expressions?  Not sure what depends on these being marked as non valid constant expressions.  Hopefully @scheglov can address this quickly tomorrow.

**Comment by leafpetersen** [comment]
To partially answer my own question, disabling the code that marks method invocations as not valid consts inside of _serializeMethodInvocation in summarize_const_expr.dart does eliminate all of the incorrect NON_CONSTANT_CASE_EXPRESSION errors, but causes the following two new errors to show up:

```
  error • Evaluation of this constant expression throws an exception at lib/src/js_model/js_strategy.dart:356:25 • const_eval_throws_exception
 error • Evaluation of this constant expression throws an exception at lib/src/kernel/element_map_impl.dart:1765:40 • const_eval_throws_exception
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/50160
