### ISSUE TITLE
Test Analyzer optional new/const on large code bases

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32821]
dartfmt with Leaf’s extra hacks here: https://github.com/dart-lang/dart_style/tree/no-new-const-context
Result of running that on DDC, sdk libraries, and dart2js here: https://dart-review.googlesource.com/c/sdk/+/50100
Result of running that on flutter/examples here: https://github.com/leafpetersen/flutter/tree/optional_new_const

(this is part of the work for finishing optional new/const)

**Comment by leafpetersen** [comment]
Brian and I between us ran his CL on all of the flutter examples, as well as dart2js, DDC, and the analyzer itself, all with new/const removed using dartfmt.  There are no issues with the flutter examples, but the others turned up this bug:  https://github.com/dart-lang/sdk/issues/32823 .

This also seems to be present in dev.43 .

**Comment by leafpetersen** [comment]
As of https://dart.googlesource.com/sdk/+/2471888d4a3ce101ae7a642dc027c338a0114667 I have verified that:
  - Flutter examples all analyze correctly with and without new and const
  - pkg/compiler/lib analyzes correctly without new and const
  - pkg/dev_compiler/lib analyzes correctly without new and const
  - pkg/analyzer/lib analyzes correctly without new and const

**Comment by bwilkerson** [comment]
@leafpetersen Thanks! Both for running all of the tests and for all your recent help getting analyzer updated to the new optional new and const feature. I suspect that we can close this issue now; what do you think?

**Comment by leafpetersen** [comment]
I think so.  Thanks for getting this done quickly.  @dgrove feel free to reopen if you have additional tests in mind.
