### ISSUE TITLE
Remove vmservice from Flutter apps in release mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32834]
As @rmacnak-google noticed, snapshots of Flutter applications compiled in release mode still contain vmservice code. This happens due to entry points
1) {"dart:_vmservice", "::", "boot"} in precompiler.cc
2) "dart:vmservice_io,::,main" in dart_vm_entry_points.txt

We should be able to remove those entry points and exclude vmservice code and its dependencies in Flutter release mode.

/cc @rmacnak-google @mraleph

**Comment by alexmarkov** [comment]
As per our discussion, we should be able to exclude vmservice entry points once we support specifying mode-specific (`!product`) entry points with `@pragma` annotations.

**Comment by mraleph** [comment]
@sjindel-google is taking over this

My prototype CL that added support for `@pragma('vm.extern', ...)` is here: https://dart-review.googlesource.com/c/sdk/+/55400

**Comment by mraleph** [comment]
@sjindel-google's work has reached Flutter framework: 

<img width="269" alt="flutter_benchmarks" src="https://user-images.githubusercontent.com/131846/42366440-79acfdce-8101-11e8-8430-bc68adb9c9a4.png">
