### ISSUE TITLE
Make Endian.host a compile-time constant on VM

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32836]
Currently, Endian.host (in typed_data) is not a compile-time constant. It could be a constant in Dart VM / Flutter. This causes Flutter to invent its own constants:

[painting.dart#L840](https://github.com/flutter/engine/blob/132ebdda892381c8c4bd03f55fc2d7f597bb5910/lib/ui/painting.dart#L840)
```dart
// If we actually run on big endian machines, we'll need to do something smarter
// here. We don't use [Endian.Host] because it's not a compile-time
// constant and can't propagate into the set/get calls.
const Endian _kFakeHostEndian = Endian.little;
```

As Endian.host is not a compile-time constants, method [hooks.dart#L176](https://github.com/flutter/engine/blob/132ebdda892381c8c4bd03f55fc2d7f597bb5910/lib/ui/hooks.dart#L176)
```dart
PointerDataPacket _unpackPointerDataPacket(ByteData packet) {
  const int kStride = Int64List.bytesPerElement;
  const int kBytesPerPointerData = _kPointerDataFieldCount * kStride;
  final int length = packet.lengthInBytes ~/ kBytesPerPointerData;
  assert(length * kBytesPerPointerData == packet.lengthInBytes);
  final List<PointerData> data = new List<PointerData>(length);
  for (int i = 0; i < length; ++i) {
    int offset = i * _kPointerDataFieldCount;
    data[i] = new PointerData(
      timeStamp: new Duration(microseconds: packet.getInt64(kStride * offset++, _kFakeHostEndian)),
      change: PointerChange.values[packet.getInt64(kStride * offset++, _kFakeHostEndian)],
      kind: PointerDeviceKind.values[packet.getInt64(kStride * offset++, _kFakeHostEndian)],
      device: packet.getInt64(kStride * offset++, _kFakeHostEndian),
      physicalX: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      physicalY: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      buttons: packet.getInt64(kStride * offset++, _kFakeHostEndian),
      obscured: packet.getInt64(kStride * offset++, _kFakeHostEndian) != 0,
      pressure: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      pressureMin: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      pressureMax: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      distance: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      distanceMax: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      radiusMajor: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      radiusMinor: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      radiusMin: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      radiusMax: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      orientation: packet.getFloat64(kStride * offset++, _kFakeHostEndian),
      tilt: packet.getFloat64(kStride * offset++, _kFakeHostEndian)
    );
    assert(offset == (i + 1) * _kPointerDataFieldCount);
  }
  return new PointerDataPacket(data: data);
}
```
is AOT-compiled into a very large code chunk (25.67K). In this method, each inlined copy of getInt64 and getFloat64 checks if passed endianness matches Endian.host and includes both code paths for matching endianness and non-matching.

/cc @mraleph @a-siva

**Comment by lrhn** [comment]
This has been requested before.
It would require to make the declaration:
```dart
external static const Endian host;
```
and handle that somehow on each platform. I don't believe we have any other `external const` declaration, and our patch files are only specified to allow patching method bodies, not field initializers.

I'm not opposed to making the change, but it isn't just a library change.

(An alternative would be to just make it constant and let the `_littleEndian` getter be computed dynamically. That would make `Endian.host` not identical to either of `Endian.big` and `Endian.little`, but only `==` to them. I think that would be even less efficient than what we have now since all endianness comparisons would then become dynamic).

**Comment by rakudrama** [comment]
`Endian.host` is browser-dependent.

dart2js does not currently handle constants that are not known at compile time so this would be a big change for dart2js as there is no runtime instance canonicalization and no startup budget to initialize one.

**Comment by mraleph** [comment]
The work-around for this has landed in the VM AOT pipeline. Closing for now.
