### ISSUE TITLE
Make int.parse throw on overflow

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32840]
From @lrhn 

"More importantly, we should fix `int.parse` to throw on overflow instead of (probably?) truncating to 64 bits."

**Comment by lrhn** [comment]
The VM is correctly parsing integers in the -2^63..2^63-1 range, throwing on overlarge values, and accepting "0x..." literals in the -2^63 .. 2^64-1 range.

Dart2js just uses the underlying JS double parser  which does not throw on values that cannot be correctly represented. I would prefer if we could treat `int.parse` the same way as integer literals and make it an error if the exact numeric value of the numeral cannot be represented by the `int` class.

**Comment by rakudrama** [comment]
I think detecting 64-bit overflow on JavaScript is the wrong choice. It breaks the invariant ...

```dart
int.parse(n.toString()) == n
```

... by introducing an unnecessary exception on large but exact numbers.

I have more sympathy for detecting rounding during parsing, but that also has problems.
int.toString() may be rounded to reduce the number of non-zero digits, e.g.
36028797018963968 prints as 36028797018963970. Demanding xxx68 from parsing would also break the invariant.

We can't change the formatting of `int` without changing the formatting of `double` - in a dynamic context there is no way to tell if the value is `int` or `double`.

We have feedback that `int.parse` is too slow, so I don't see being able to add much in the way of additional checking.

**Comment by lrhn** [comment]
I agree that dart2js shouldn't necessarily throw for values above 2^63.

I do think it should catch inexact values, but I can see the problem arising from the `toString` not being exact for integer values, even when not using exponential notation. Another example like:
```dart
print(9223372036854774784); // 9223372036854775000
```
It's useless if `int.parse(9223372036854774784.toString())` throws.
I guess there is no good solution (short of a very inefficient `int.toString` implementation).

Doubles! Can't live with them ... 'nuff said.
