### ISSUE TITLE
flutter_tester.exe exits when main is async

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#32848]
When I run `windows-x64\flutter_tester.exe --non-interactive test2.dart` it prints `Started!` and then exists. It does not exit and prints `Tick!` when I run `darwin-x64/flutter_tester --non-interactive test2.dart`. It also does not exist on Windows if I remove `async` from `main`.

```
C:\Users\scheglov\AppData\Local\Temp\flutterDesigner>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
```

```dart
import 'dart:async';

main() async {
  print('Started!');
  new Timer.periodic(new Duration(seconds: 1), (_) { print('Tick!'); });
}
```

**Comment by bkonyi** [comment]
I was able to reproduce a few weeks ago but it looks like this has been resolved since. Feel free to reopen if you run into the issue again.
