### ISSUE TITLE
Non exported top-level property appears in auto-complete, but it's not exposed anywhere

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32849]
`sandboxExists` exists in https://github.com/dart-lang/test_descriptor/blob/master/lib/src/sandbox.dart

But it is not exported: https://github.com/dart-lang/test_descriptor/blob/master/lib/test_descriptor.dart

And it doesn't show up in the docs: See https://pub.dartlang.org/documentation/test_descriptor/1.0.3/test_descriptor/test_descriptor-library.html

Yet, it shows up in the autocomplete list in this code.

```dart
import 'package:test_descriptor/test_descriptor.dart' as d;

main() {
  d.sand[AUTOCOMPLETE HERE]
}
```

This is on 2.0.0-dev.47.0

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/53863
