### ISSUE TITLE
Turn on sync async for Flutter

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32850]

**Comment by a-siva** [comment]
Unable to land this tonight as some flutter tests are failing. These tests are expecting exceptions to be thrown and are comparing the stack traces from the exception, these stack traces are not matching now. Looks like a case of updating the expected stack traces in the tests.
Will update the tests tomorrow and land the pull request (https://github.com/flutter/flutter/pull/16543)

**Comment by dgrove** [comment]
@a-siva do you believe that we can close this now?

**Comment by dgrove** [comment]
Moving this to Beta4.

**Comment by dgrove** [comment]
@a-siva are you driving this?

**Comment by dgrove** [comment]
@floitschG will make this happen.

**Comment by dgrove** [comment]
There's no more work for Dart. @a-siva is planning to open a Flutter issue.
