### ISSUE TITLE
Mirrors crash when reading library dependency metadata

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32879]
The test `lib_2/mirrors/library_imports_bad_metadata_test/none` crashes due to Dart 2-invalid code in the mirrors implementation.

**Comment by mkustermann** [comment]
One of the issues here is that native function [LibraryMirror_libraryDependencies](https://github.com/dart-lang/sdk/blob/master/runtime/lib/mirrors.cc#L440) does not set the type argument for the array.

@rmacnak-google
