### ISSUE TITLE
Default to "sync async" for Dart VM

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32870]

**Comment by a-siva** [comment]
The engine roll is happening and will turn this on once that is done.

**Comment by a-siva** [comment]
Unable to land this tonight as some flutter tests are failing. These tests are expecting exceptions to be thrown and are comparing the stack traces from the exception, these stack traces are not matching now. Looks like a case of updating the expected stack traces in the tests.
Will update the tests tomorrow and land the pull request (https://github.com/flutter/flutter/pull/16543)

**Comment by dgrove** [comment]
@floitschG Can you help out now that you're back?

**Comment by a-siva** [comment]
This is on by default now.
