### ISSUE TITLE
Show clauses are combined using intersection, not union.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32878]
Consider the following program:

```dart
import 'dart:async' show Future show Stream;

main() {
  Future f = null;
  Stream s = null;
  print("$f $s");
}
```

The [language specification](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex) requires this program to have two compile-time warnings (in Dart 2 that means errors) because `Future` is not defined and `Stream` is not defined. The reason is that if we have multiple `show` clauses on the same import then the resulting set of names that we get access to is obtained as the _intersection_ of the sets of names listed in each `show` clause, not the union.

The current implementations behave as specified (we get `Undefined class` from the analyzer and `isn't a type` from the vm and dart2js).

However, it seems unlikely that this is intended: We should either prohibit multiple `show` clauses or take the union, otherwise there is no way it could ever be anything else than a useless set of redundant listings of the same identifiers.

Here is the core of the relevant wording in the specification (modulo a typo that I fixed, and which does not matter for this issue):
```
\item If $C_i$ is of the form

\code{\SHOW{} $id_1, \ldots,\ id_k$}

then let $NS_i = show([id_1, \ldots,\ id_k], NS_{i-1}$)

where $show(l,n)$ takes a list of identifiers $l$ and a namespace $n$, and produces a namespace that maps each name in $l$ to the same element that $n$ does.
Furthermore, for each name $x$ in $l$, if $n$ defines the name $x=$ then the new namespace maps $x=$ to the same element that $n$ does.
```

**Comment by lrhn** [comment]
I believe the idea was to have more modifiers than just `hide` and `show`. With those two alone, you only ever need to have one modifier.
If you also had renames, you could. potentially, have a need for first hiding something, then renaming something to the old name, then showing that (and more).

In other words, the current import scope modifiers are probably overly general for the job they do.

**Comment by eernstg** [comment]
Even if we introduce renaming it sounds like it would make sense to say "two `show` clauses is a compile-time error" rather than a construct that (surprisingly, I think) takes the intersection of the names which are shown.

**Comment by eernstg** [comment]
Closing: The current rules are somewhat silly, but I'll focus on more important things.
