### ISSUE TITLE
Missing nsm forwarder on widening abstract override

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32877]
When a concrete method is overridden by (via a subclass or implemented interface) an abstract method with a more general signature (i.e. adding optional parameters), and the class contains a noSuchMethod implementation different from that in Object, a noSuchMethod forwarder should be generated for the method, but this particular case is not handled.

This is similar to the missing error described in https://github.com/dart-lang/sdk/issues/32014 but for the case where there is a noSuchMethod implementation (and the program is thus valid).

**Comment by eernstg** [comment]
> noSuchMethod forwarder should be generated

That's actually not true. We discussed this case and agreed that it is too error prone to let a generated forwarder override a developer-written implementation, so it should instead be an error when such a situation arises. Search for `This can only happen` in [nosuchmethod-forwarding.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/nosuchmethod-forwarding.md) where the commentary explaining this decision is given, and the previous paragraph `It is a compile-time error` where the rule itself is specified.

**Comment by askeksa-google** [comment]
Issue invalid.
