### ISSUE TITLE
improve the performance of analyzing the flutter repo

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32882]
Follow up from https://github.com/dart-lang/sdk/issues/32769; we should investigation improving the performance of analyzing the flutter repo (`flutter analyze --flutter-repo`).

Some changes are in-flight, and will be visible w/ the next roll of the dart sdk.

**Comment by devoncarew** [comment]
See the benchmarks here: https://flutter-dashboard.appspot.com/benchmarks.html

**Comment by devoncarew** [comment]
(also note a potential performance improvement @jmesserly found - https://github.com/dart-lang/sdk/issues/32814 - though, it wouldn't be necessary after the move to the CFE)

**Comment by dgrove** [comment]
Is this a Beta 4 issue?

**Comment by devoncarew** [comment]
I'll add it; the next dart sdk that rolls into flutter will already improve performance enough to close this issue.

**Comment by dgrove** [comment]
After https://github.com/flutter/engine/commit/76cb311d9c33720dcd19274228b39ecdbad8d9af , this looks much closer. Is there more work that will happen for Beta 4?

**Comment by scheglov** [comment]
There are two more optimizations which are not part of this roll, which make Flutter analysis in watch mode 12% and 10% respectively.
https://dart-review.googlesource.com/c/sdk/+/51061
https://dart-review.googlesource.com/c/sdk/+/51160

**Comment by dgrove** [comment]
Very cool. It sounds like we'll be able to close this quite soon.

**Comment by dgrove** [comment]
We're all green https://flutter-dashboard.appspot.com/benchmarks.html with https://github.com/flutter/flutter/pull/16707 .
