### ISSUE TITLE
JS Interop with customized MouseEvent fails with dart2js, works with DDC

### ISSUE THREAD

**Issue by avilladsen** [dart-lang/sdk#32883]
The `@JS()`-style interop fails at runtime in dart2js but **not** DDC (or Dartium) when used to declare a class to try to access non-standard properties of what is really a MouseEvent:
```
TypeError: Instance of 'MouseEvent': type 'MouseEvent' is not a subtype of type 'MyMouseEvent'
```
Or depending on how exactly you write the Dart code:
```
TypeError: J.getInterceptor$x(...).get$myProp is not a function
```
To give some context, in [some cases](https://api.highcharts.com/highcharts/plotOptions.series.events.click) Highcharts will add its own custom properties to a MouseEvent before passing it to your handlers. I'm only really interested in those custom properties, so I made a facade class:
```dart
@JS()
abstract class SeriesEvent {
  external Point get point;
}
```
which appeared to work during development, but failed when compiling with dart2js.

It's easy enough to get around this issue with the `getProperty` helper function. It would be great if `@JS()` actually worked in this case, but at the least dart2js and DDC should be consistent with each other.

I suspect this may be related to #15216.

Below is the simplified example I made to play around with this issue. I'm using Chrome on Mac OSX, and I've tried this with essentially the same result (differently worded error messages) on both Dart 1.2.4 and Dart 2.0.0-dev.48.0.

JS script/HTML body:
```html
  <button id="btn">Click me!</button>
  <script>
      function onButtonClick(handler) {
          document.querySelector('#btn').onclick = function(event) {
              event.myProp = "value";
              handler(event);
          }
      }
  </script>
```
button_click.dart:
```dart
@JS()
library mouse_event_interop.button_click;
import 'package:js/js.dart';

@JS()
external onButtonClick(Function handler);

// having MyMouseEvent implements MouseEvent does not change the error
@JS()
abstract class MyMouseEvent {
  external String get myProp;
}
```
main.dart:
```dart
import 'package:js/js.dart';
import 'button_click.dart';

void main() {
  // TypeError: Instance of 'MouseEvent': type 'MouseEvent' is not a subtype of type 'MyMouseEvent'
//  onButtonClick(allowInterop((MyMouseEvent event) {
//    print(event.myProp);
//  }));

  // TypeError: J.getInterceptor$x(...).get$myProp is not a function
  typedOnButtonClick((event) {
    print(event.myProp);
  });
}

void typedOnButtonClick(void handler(MyMouseEvent event)) {
  onButtonClick(allowInterop(handler));
}
```

I'd bet this also happens with native JS types other than MouseEvent, but I haven't experimented with that.

**Comment by vsmenon** [comment]
Merging this one with:  #33134
