### ISSUE TITLE
Change command-line VM default to Dart 2

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32886]

**Comment by dgrove** [comment]
@a-siva I believe this should be pushed to Dart2Stable (we should be able to do it end of May, but not in time for the Beta4 milestone).

**Comment by natebosch** [comment]
The current VM does not support `dart --no-preview-dart-2`. It would be nice if it did for a backwards compatible transition period.

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/58240 has landed.
