### ISSUE TITLE
Build error after upgrade flutter to beta 2 with dart 2

### ISSUE THREAD

**Issue by xinoxapps** [dart-lang/sdk#32891]
```
Syncing files to device Android SDK built for x86...
compiler message: file:///Users/wendel/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.31.2-alpha.1/lib/src/summary/link.dart:409:3: Error: Duplicated name: enclosingElement
compiler message:   final CompilationUnitElementForLink enclosingElement;
compiler message:   ^
```

**Comment by a-siva** [comment]
Can you post reproduction instructions, what app was being built etc.

**Comment by xinoxapps** [comment]
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale nl-NL)
    • Flutter version 0.2.8 at /Users/wendel/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/wendel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

------ pubspec.yaml

name: zaira
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  path_provider: 0.4.0
  firebase_auth: 0.5.4                                      # new
  google_sign_in: 3.0.1
  flutter_facebook_connect: "0.0.4+1"

  discoveryapis_generator: "0.9.4"
  _discoveryapis_commons: '>=0.1.0 <0.2.0'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  http: '>=0.11.3+16'

  zaapi:
    path: "./api_dev/"

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this issue.
