### ISSUE TITLE
`catch` does not catch in unchecked mode

### ISSUE THREAD

**Issue by ohir** [dart-lang/sdk#32897]
`Dart VM version: 2.0.0-dev.43.0.flutter-52afcba357 (Fri Mar 30 20:33:12 2018 +0000) on "linux_x64"`

Simple try-catch block does not work due to engine spawning closure in an Isolate.
Given `repro.dart` of
```dart
void main(List<String> args) {
  List<int> nl;
	try { 
	  nl = args.map((String s)=>int.parse(s)); 
	} catch (e) { 
	  print('Bad parameter given!');
		return; 
  }
  print('All: $nl');
	return;
}
```

**catch** catches in dart1 (checked) mode:
```
% dart -c repro.dart 1 2 3 bad
Bad parameter given!
```

But it fails to catch in unchecked mode:
```
% dart repro.dart 1 2 3 bad
Unhandled exception:
FormatException: Invalid radix-10 number
bad
#0      int._throwFormatException (dart:core-patch/dart:core/integers_patch.dart:115)
#1      int._parse (dart:core-patch/dart:core/integers_patch.dart:105)
#2      int.parse (dart:core-patch/dart:core/integers_patch.dart:62)
#3      main.<anonymous closure> (file:///tmp/repro.dart:4:34)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#6      _iterablePartsToStrings (dart:collection/iterable.dart:338)
#7      IterableBase.iterableToShortString (dart:collection/iterable.dart:254)
#8      Iterable.toString (dart:core/iterable.dart:683)
#9      _StringBase._interpolate (dart:core-patch/dart:core/string_patch.dart:817)
#10     main (file:///tmp/repro.dart:9:19)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
I use (as seen at opening) flutter version of Dart engine. The official flutter wiki announced `--preview-dart-2` mode to be new default with **beta2**. But apparently it is not dart2. If I put `--preview-dart-2` explicitly, the catch catches again:
```
% dart --preview-dart-2 repro.dart 1 2 3 bad
Bad parameter given!
```

**Comment by mraleph** [comment]
`map` returns a lazy `Iterable` rather than a `List`, quoting [the documentation](https://api.dartlang.org/dev/2.0.0-dev.48.0/dart-core/Iterable/map.html): 

> Returns a new lazy Iterable with elements that are created by calling f on each element of this Iterable in iteration order.
>
> This method returns a view of the mapped elements. As long as the returned Iterable is not iterated over, the supplied function f will not be invoked. The transformed elements will not be cached. Iterating multiple times over the returned Iterable will invoke the supplied function f multiple times on the same element.

So `catch` does not catch anything because nothing is thrown. 

In Dart 2 or checked mode you instead get a type cast error - because you are assigning value of type `Iterable` to a variable of type `List`.

**Comment by fmatosqg** [comment]
On my OS X I get a slightly different behavior

[✓] Flutter (Channel dev, v0.2.6, on Mac OS X 10.11.6 15G1510, locale en)
Dart VM version: 2.0.0-dev.43.0.flutter-e305117519 (Tue Mar 27 19:15:22 2018 +0000) on "macos_x64"

```
dart   repro.dart --preview-dart-2   1 2 3 bad
Unhandled exception:
FormatException: Invalid radix-10 number
--preview-dart-2
#0      int._throwFormatException (dart:core-patch/dart:core/integers_patch.dart:115)
#1      int._parse (dart:core-patch/dart:core/integers_patch.dart:105)
#2      int.parse (dart:core-patch/dart:core/integers_patch.dart:62)
#3      main.<anonymous closure> (file:///private/tmp/daer/repro.dart:4:34)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#6      _iterablePartsToStrings (dart:collection/iterable.dart:338)
#7      IterableBase.iterableToShortString (dart:collection/iterable.dart:254)
#8      Iterable.toString (dart:core/iterable.dart:683)
#9      _StringBase._interpolate (dart:core-patch/dart:core/string_patch.dart:817)
#10     main (file:///private/tmp/daer/repro.dart:9:19)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
