### ISSUE TITLE
Exception with bleeding edge SDK

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#32908]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4674.33`
- `<NO SDK>`
- `IC-173.4674.33, JRE 1.8.0_151-b12x64 Oracle Corporation, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version , FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:690:14)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:677:26)
#3      Driver.start (package:analysis_server/src/server/driver.dart:389:12)
#4      main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)

**Comment by bwilkerson** [comment]
We can test for `null`, but that would only move the failure to somewhere else. I'd like to understand when we are unable to find the path to the script being run and how to reliably find the location of the SDK.

**Comment by bwilkerson** [comment]
@scheglov Should we close this as being stale, or do we still want to try to look into it?
