### ISSUE TITLE
Move from `pub build` to `dart2js` for Observatory

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#32900]
~~If there are any Transformers they will need to be rewritten as Builders, then build_runner and related packages will need to be pulled in to the SDK.~~

There are no Transformers so we should be able to call Dart2Js directly.

**Comment by dgrove** [comment]
@devoncarew @a-siva can you assign someone?

**Comment by natebosch** [comment]
I've made some progress on this but I'm getting stuck.

I have been making changes to [observatory_tool.py](https://github.com/dart-lang/sdk/blob/8e812ddaa52110e919bea938735caaff9eb3e33e/tools/observatory_tool.py) to find the dart2js snapshot in the same way as it does for pub and then invoke that for the "build" action.

I'm able to get to the point where I run dart2js but I'm hitting an error that makes me think maybe the dart2js snapshot was somehow build incorrectly.

```
Command failed: /usr/local/google/home/nbosch/projects/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart /usr/local/google/home/nbosch/projects/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/snapshots/dart2js.dart.snapshot -DOBS_VER=2.0.0-edge -o /usr/local/google/home/nbosch/projects/dart-sdk/sdk/out/ReleaseX64/observatory/build/web/main.dart.js /usr/local/google/home/nbosch/projects/dart-sdk/sdk/out/ReleaseX64/gen/observatory_copy/web/main.dart
output: The compiler crashed: Error reading '../../../../../../tools/sdks/sdk/lib/dart_client.platform'  (No such file or directory)
```

**Comment by rmacnak-google** [comment]
Don't invoke dart2js' snapshot directly. Use the wrapper script at tools/sdks/<os>/dart-sdk/bin/dart2js, which sets extra arguments to tell dart2js where to find the core libraries etc.

**Comment by natebosch** [comment]
Latest update is it's harder than I thought because I need to generated a `packages/` directory in addition to building with dart2js, and I'm still working on the change - it's slow going since gn/ninja/build.py (not to mention depot_tools) are all new to me and all slowing me down.

Also giving more consideration to pulling `build_runner` in to the SDK instead of trying to do the work in python, but that would also be blocked on a few polish issues with build_runner and would add more delay.

**Comment by natebosch** [comment]
I think I have something working. https://dart-review.googlesource.com/c/sdk/+/51740 is ready for another review.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/6d5e8e8f8790881ed0009383ec34489304a4f9d8
