### ISSUE TITLE
Isolate.resolvePackageUri has inconsistent behavior when called from a script launched via relative path

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32901]
When running in the VM with preview-dart-2, resolvePackageUri sometimes doesn't resolve to a file URI correctly unless the script was launched with an absolute path.

demo:

```
/tmp/resolve
$ cat pubspec.yaml
name: resolvedemo
version: 0.1.0
/tmp/resolve
$ pub get
Resolving dependencies... 
Got dependencies!
/tmp/resolve
$ cat bin/resolve.dart 
import "dart:isolate" show Isolate;

main() {
  Uri theUri = Uri.parse('package:resolvedemo/test.dart');
  print('theUri: $theUri');
  Isolate.resolvePackageUri(theUri).then((u) => print ('resolved Uri: $u'));
}

/tmp/resolve
$ dart `pwd`/bin/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///tmp/resolve/lib/test.dart
/tmp/resolve
$ dart bin/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///tmp/resolve/lib/test.dart
/tmp/resolve
$ dart --preview-dart-2 `pwd`/bin/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///tmp/resolve/lib/test.dart
/tmp/resolve
$ dart --preview-dart-2 bin/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: lib/test.dart
/tmp/resolve
$
```

I believe all four runs of the program should have the same output.
(edit: refined example for clarity)

**Comment by jcollins-g** [comment]
This seems to be substantially worse on windows, with the resolution failing completely in all cases:

![screenshot from 2018-04-16 13-55-01](https://user-images.githubusercontent.com/14116827/38834626-db519864-417d-11e8-9a6e-c8c39044e839.png)

**Comment by jcollins-g** [comment]
This blocks dart-lang/dartdoc#1668.

**Comment by lrhn** [comment]
The behavior is correct, but it might not be useful.

The location of the `.packages` file is found relative to the entry point. There is no specification of what the result of that is, just that it finds the file, so choosing a relative path for the location of the `.packages` file is not wrong.
The `.packages` file contains a relative location that is interpreted as relative to the `.packages` file.
So, when the entry-point is relative, everything after that stays relative.

I think we should just decide that the path of the `.packages` file must be resolved into an absolute URI before resolving a relative path against it. That would likely be done by resolving the relative URI against the current working directory (aka, `Uri.base`). That would avoid resolving a relative URI against another relative URI, which is generally a code smell.

**Comment by jcollins-g** [comment]
@lrhn  Resolving to an absolute file URI would work for me.   Also I'll mention that I don't think returning null here is correct on Windows -- no matter what we decide, that should be fixed.

**Comment by jcollins-g** [comment]
The returning null on Windows is still a blocking bug for Dartdoc under Dart 2.0.

**Comment by srawlins** [comment]
I get null on Macos if I am in a directory _below_ the `.packages` file. With the same layout as @jcollins-g 's above:

```shell
$ cd bin/

$ pwd
/tmp/resolve/bin

$ dart `pwd`/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///tmp/resolve/lib/test.dart

$ dart resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///private/tmp/resolve/lib/test.dart

$ dart --preview-dart-2 `pwd`/resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: file:///tmp/resolve/lib/test.dart

$ dart --preview-dart-2 resolve.dart
theUri: package:resolvedemo/test.dart
resolved Uri: null
```

The second example returns `file:///private/tmp/resolve/lib/test.dart`, a bit of a head scratcher..., and the fourth example returns `null`. ☹️

**Comment by a-siva** [comment]
I am able to reproduce the behavior that @srawlins reports on linux too.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/56622 should fix this.
