### ISSUE TITLE
CFE does not reject non-const partial instantiations for default parameter values

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32912]
This is the CFE specific issue for the default parameter issue from https://github.com/dart-lang/sdk/issues/32415 .

Partial instantiations of generic methods are only `const` objects if their type arguments are `const` types.  The CFE should statically reject the following program, but currently doesn't.

```dart
dynamic _defaultCallback<T>(T t) => t;
class C<T> {
  final dynamic Function(T) callback;
  // Should be statically rejected
  void foo([dynamic Function(T) f = _defaultCallback]) {}
  // Should be statically rejected
  const C({this.callback = _defaultCallback});
}

// Should be statically rejected
void bar<T>([dynamic Function(T) f = _defaultCallback]) {}

void main() {
  print(new C<int>().callback);
}
```

**Comment by dgrove** [comment]
With -dev.59, the Dart Analyzer doesn't report any errors for this. /cc @bwilkerson

**Comment by mit-mit** [comment]
@peter-ahe-google to check if this fails in the VM

**Comment by peter-ahe-google** [comment]
Dart2js is rejecting this program, and so is the VM.

**Comment by mit-mit** [comment]
Per triage discussion, and above comment, punting to 2.1

**Comment by natebosch** [comment]
> and so is the VM.

I see a runtime error. How can I repro the VM statically rejecting this code? Tried at `Dart VM version: 2.0.0-dev.67.0` and `Dart VM version: 2.0.0-edge.bab152a0a903aeb7d4afc974d5368ce220dd9501`

cc @dgrove - per our discussion regarding breaking changes I think either this or https://github.com/dart-lang/sdk/issues/32913 should be in Dart2Stable.

**Comment by dgrove** [comment]
FWIW, I see dart2js (which uses the CFE) rejecting this with -dev.67, but I'm not able to see the VM rejecting it statically.

**Comment by peter-ahe-google** [comment]
I could have sworn that I saw the VM report this as a compile-time error, but I must have accidentally looked at the output from dart2js.

**Comment by leafpetersen** [comment]
Note that dart2js only gives an error on this if the default value is actually used.  So the code below is not statically rejected, and gives no errors when run (neither by DDC, nor by dart2js, nor by the VM).

```dart
dynamic _defaultCallback<T>(T t) => t;
class C<T> {
  final dynamic Function(T) callback;
  // Should be statically rejected
  void foo([dynamic Function(T) f = _defaultCallback]) {}
  // Should be statically rejected
  const C({this.callback = _defaultCallback});
}

// Should be statically rejected
void bar<T>([dynamic Function(T) f = _defaultCallback]) {}

void main() {
  print(new C<int>(callback: _defaultCallback));
}
```

This means that fixing this will be a breaking change.

**Comment by a-siva** [comment]
Leaf has already reported the behavior on the different implementations in his comment above.

**Comment by kmillikin** [comment]
The Dart analyzer does not catch this.  The JIT VM fails if the value is used:

```
Unhandled exception:
type '(T) => dynamic' is not a subtype of type '(int) => dynamic'
#0      main (const.dart:14:22)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

The AOT VM compiler crashes when deserializing a .dill whether or not the value is used:
```
error: Unbound type parameter found in Library:'const.dart' Class: ::.  Please report this at dartbug.com.
```

So we're not really catching this but we're not running it either.  I don't know how much it would take to fix the VM's JIT and AOT constant evaluators to catch this.

**Comment by mkustermann** [comment]
I've made a [CL](https://dart-review.googlesource.com/c/sdk/+/81278) which would fix it and give better (though still not very good) error messages.

**Comment by kmillikin** [comment]
This is now caught by the VM in both its JIT and AOT compilers.  The remaning work on the front end will be done post-Dart 2.1.

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
