### ISSUE TITLE
Analyzer - missing static error for assigning the stack trace argument within a catch clause

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#32910]
According to the spec this variable should be final. When running with the dart vm `--preview-dart-2` it is caught at parse time, however the analyzer does not report it.

```dart
void main() {
  try {} catch (_, stackTrace) {
    stackTrace = StackTrace.current;
    print(stackTrace);
  }
}
```

No warning with `dartanalyzer --strong` or `dartanalyzer --preview-dart-2`. Running with `dart --preview-dart-2` gives:

```
file:///tmp/catch_final.dart:3:5: Error: Setter not found: 'stackTrace'.
    stackTrace = StackTrace.current;
    ^^^^^^^^^^
file:///tmp/catch_final.dart:3:5: Error: Setter not found: 'stackTrace'.
    stackTrace = StackTrace.current;
    ^^^^^^^^^^
```

**Comment by natebosch** [comment]
Same thing happens for the error argument as well

**Comment by srawlins** [comment]
Recent dartanalyzer now reports that each parameter is final and cannot be re-assigned:

> error • The final variable 'err' can only be set once. • 32910.dart:3:5 • assignment_to_final_local

> error • The final variable 'stackTrace' can only be set once. • 32910.dart:4:5 • assignment_to_final_local
