### ISSUE TITLE
Analyzer does not eliminate type variables from `const` values

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32918]
This is the analyzer specific issue for the least closure part of https://github.com/dart-lang/sdk/issues/32415 .

The following program prints `B<Null>` and passes the assertion when run with DDC + kernel, but prints `B<String>` and fails the assertion under DDC + analyzer.  The analyzer should be taking the least closure of the inferred type argument to `B` to eliminate the type variable (which is not otherwise a valid `const` type.)

```dart
class A<T> {
  const A();
}

class B<T> implements A<T> {
  const B();
}

class C<T> {
  final _a;

  const C([A<T> a = const B()]) : _a = a;
}

void main() {
  var c = new C<String>();
  print(c._a.runtimeType);
  assert(c._a is A<Null>);
}
```

**Comment by leafpetersen** [comment]
@nshahan just ran into an inconsistency between dart2js and ddc from this.

**Comment by keertip** [comment]
Ran into this with package [shelf](https://github.com/dart-lang/shelf/blob/master/lib/src/shelf_unmodifiable_map.dart#L57)
```
  const _EmptyShelfUnmodifiableMap() : super(const {});
```
does not evaluate, throws an exception. The workaround 

```
const _EmptyShelfUnmodifiableMap() : super(const <String, Null>{});
 ```

**Comment by devoncarew** [comment]
@vsmenon, @MichaelRFairhurst is working through the dart 2 stable issues in priority order. Anything not a P1 for dart 2 stable (https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3ADart2Stable+label%3A%22area-analyzer%22) is a target of opportunity for us, given the other work going on.

**Comment by MichaelRFairhurst** [comment]
This also has a workaround, by specifying Null as a parameter, so its not a P1

**Comment by leafpetersen** [comment]
Not sure what to do with this one.  It's inconsistent runtime behavior, which is bad, must be fixed.  Could be punted to 2.1, but not an optional one.

**Comment by devoncarew** [comment]
From talking to @MichaelRFairhurst, we believe this ok to address in the 2.1 timeframe.

**Comment by jmesserly** [comment]
testing https://dart-review.googlesource.com/c/sdk/+/98707

**Comment by dgrove** [comment]
Speculatively moving this to 2.3

**Comment by jmesserly** [comment]
sounds good to me! I just set out the CL for review
