### ISSUE TITLE
Hot data reload in AngilarDart (build_runner)

### ISSUE THREAD

**Issue by krypton-code** [dart-lang/sdk#32920]
I'm going through the tutorial in this place:
https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt1#show-all-hero-properties
as soon as I make changes to the template and try to update the page, I don't get changes. I have to run the command `pub run build_runner serve` again, that to see the changes. I also noticed in other cases that I need to manually reboot the build_runner.

I dare to suggest that this does not work properly. Thank you.

* dependencies:
  * angular: ^5.0.0-alpha
* dev_dependencies:
  * angular_test: ^2.0.0-alpha
  * build_runner: ^0.8.2
  * build_test: ^0.10.0
  * build_web_compilers: ^0.3.6
  * test: ^0.12.30

* Dart VM version: 2.0.0-dev.48.0 (Unknown timestamp) on "linux_x64"
* Ubuntu 16.04
* Chrome 65.0.3325.181

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/angular#1259
