### ISSUE TITLE
Working with self signed certs

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#32921]
_From @MderM on April 18, 2018 15:9_

Any chance that this package will work with self signed certificates? HttpClient has a configurable callback for this. Would help a lot in prototyping stage...

_Copied from original issue: dart-lang/web_socket_channel#15_

**Comment by nex3** [comment]
`web_socket_channel` just forwards to `dart:io`'s `WebSocket` implementation, so I'm going to move this to the SDK repo.

**Comment by natebosch** [comment]
You should be able to use the `--root-certs-file` to point to the trusted root certificates.

**Comment by ben-xD** [comment]
Does anyone know how would this interplay with Flutter? I guess I need to pass `DART_VM_OPTIONS=--root-certs-file=directory` somewhere, but not sure where. I'm using the web_socket_channel plugin in a flutter application
