### ISSUE TITLE
getMembersInheritedFromClasses provides incomplete data for reexported classes

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32923]
Per offline discussion with @bwilkerson 

Dart 2.0.0-dev.48.0, analyzer 0.31.2-alpha.1.  (Unable to validate at head right now because something in head seems broken.)

If I build a inheritance manager from the reexporting library and pass in the reexported element, private inherited members are dropped from the result.  However, if I build the inheritance manager from the defining library (element.library), the inheritance manager provides the full list of inherited members.

**Comment by bwilkerson** [comment]
@jcollins-g Is this issue still relevant?

**Comment by jcollins-g** [comment]
@bwilkerson This issue does not cause any problem in dartdoc due to the availability of a workaround.  But it seems like we shouldn't have to find the defining library for this to work.  I think it's a real bug, but just not one we might care about fixing?

**Comment by bwilkerson** [comment]
I don't know; I have forgotten the original discussion so I'm missing context.

I think a concrete example would help. Reading over the description above, it isn't clear to me that this is even a bug.

**Comment by jcollins-g** [comment]
This is not actually a bug.  As discussed offline, Dartdoc currently needs to know about private members even when from locations where they're not actually accessible (it is conceivable that they might be referred to in comment references).

The workaround is actually then just a bugfix in Dartdoc and we can close this out.
