### ISSUE TITLE
Https hijacking  with HttpClient .

### ISSUE THREAD

**Issue by wendux** [dart-lang/sdk#32936]
When I use ` HttpClient` to request  "https://www.google.com" in china ， I  was surprised to find that the response  is not the  google home page and without any error tip !  some of response content is : 
```
  <script src="https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/nocache/imgdata/seErrorRec.js"></script>
    <title>页面不存在_百度搜索</title>
    <style data-for="result">
....
```
It seems to be Http hijacking! 

Because the certificate of baidu.com is  trusted root certificate, so  the `badCertificateCallback` of `HttpClient` is not invoked。

I guess that the `HttpClient` may not verify the hostname listed in  server certificate (should assure  the request hostname is in the server certificate ) .  If this is really the fact , means all  trusted root certificate  can be used to hijacking the https request.  It will lead serious security  issue.

**My environment**
Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64"

**Comment by matanlurey** [comment]
This is a version of the VM (`1.24.3`) that is no longer being actively worked on.

I'd try the latest Dart 2.0-dev SDK, and refile if you are still having an issue.

**Comment by wendux** [comment]
Yes, I  have set the proxy as fellows:
``` dart
   httpClient.findProxy = (uri) {
    //proxy all request to localhost:8888
    return "PROXY localhost:8888";
  };
```
Is this a problem with the proxy?
