### ISSUE TITLE
Native external libraries do not load

### ISSUE THREAD

**Issue by LousyLynx** [dart-lang/sdk#32930]
I am attempting to make a binding for an external C library in Dart. For the most part, it is going fairly well with the setup, although I am running into a slight problem with the library. I am using mostly the same configuration as on the wiki page for natives(with the exception of the [build file](https://gist.github.com/LousyLynx/8c598e26a4c34cb9236b59ff55acb211), which I got off of another repository I found). When I try to run my Dart code, I am greeted with the error:

    /usr/lib/dart/bin/dart: symbol lookup error: ///path/to/libnatives.so: undefined symbol: LibraryMethod

Where `LibraryMethod` is the method in the other library. This library has its header includes in `/usr/include` and its library files in `/usr/lib/x86_64-linux-gnu`.

I am running Dart `2.0.0-dev.47.0`, and Ubuntu 16.04 LTS.

**Comment by rmacnak-google** [comment]
The VM only looks up the symbol <extension_name>_Init. This error means you did not link a definition of  'LibraryMethod' into your shared library.

**Comment by LousyLynx** [comment]
To anyone who has this issue in the future: I fixed this by adding the `-L` and `-l` parameters to the **END** of my `gcc` command. For some reason the `gcc` command will only allow for this type of thing to work if those parameters are at the end of the command.

Hope this helped someone!
