### ISSUE TITLE
Named constructors do not appear in completion list when not using new/const keyword

### ISSUE THREAD

**Issue by bramvbilsen** [dart-lang/sdk#32947]
When using the Dart 2 preview in VS Code / Intellij / Android Studio, there are no auto fill options named constructors.
For example trying to auto fill
```
new ListView.
```
presents me with all the named constructors for this class.
Using 
```
ListView.
```
does not present any auto fill options.

Dart version: Dart 2.0.0-dev.48.0.flutter-fe606f890b

**Comment by vsmenon** [comment]
fyi - @devoncarew

**Comment by scheglov** [comment]
We oscillated between enabling and disabling this feature and ended up with disabling it, because we are not sure what the state of runtime is/will-be.

https://dart-review.googlesource.com/c/sdk/+/49280

**Comment by xster** [comment]
@scheglov can you elaborate a bit on what you meant? It's a big inconvenient that moving forward, all factories will not be auto-completable.

**Comment by scheglov** [comment]
I got a confirmation that optional new/const is ready in VM, and people actually want to stop writing them. So, I landed https://dart-review.googlesource.com/c/sdk/+/55506 that restores completion for constructors without `new`.

**Comment by xster** [comment]
\o/!!! 

It looks like the revert^3 was from today. I assume it means when the next dart version rolls, this will be on in all IDEs?

**Comment by scheglov** [comment]
Yes, all IDEs get completion from Analysis Server, so all of them will get constructors.

![image](https://user-images.githubusercontent.com/384794/40144192-9be088a0-5912-11e8-9180-8f9a600ee813.png)
