### ISSUE TITLE
Is there a "BinarySink"  like "StreamSink" in dart?

### ISSUE THREAD

**Issue by wendux** [dart-lang/sdk#32945]
When I want to write a text file with a `Stream` , I can do as follows:
```dart
...
 Stream<List<int>> stream=httpClientResponse;
 IOSink sink=file.openWrite();
 sink.addStream(stream)
```
It works only if the file is an text file, because the` IOSink` extends `StringSink`, it will encode the stream to a string, but I want to save the `List<int>` as binary bytes when the file is a binary file (e.g. an image).

**Comment by jngbng** [comment]
https://www.crossdart.info/p/sdk/1.23.0/lib/io/io_sink.dart.html#line-10
I found that IOSink work well with both String and and List<int>.
`stream.pipe(sink)` works well with me.

**Comment by natebosch** [comment]
You can use `IOSink.add`, `IOSink.addStream` etc to write bytes directly. It extends `StringSink` because of the convenience methods that do String to byte encoding like `writeln` but doesn't force you to write only strings to it.
