### ISSUE TITLE
Isolate.spawnUri() ignores packageConfig argument in Dart 2 mode

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#32950]
`Isolate.spawnUri()` seems to completely ignore the `packageConfig` argument in Dart 2 mode, instead always using the automatic package resolution behavior of looking for a `.packages` file in the same directory as the entrypoint or in any of its parent directories. To reproduce:

```yaml
# pubspec.yaml
name: test
dependencies:
  path: any
```

```dart
import 'dart:isolate';
import 'dart:io';

import 'package:path/path.dart' as p;

main() async {
  var path = '/tmp/other.dart';
  new File(path).writeAsStringSync("""
    import 'package:path/path.dart' as p;

    void main() => print(p.current);
  """);

  var exitPort = new ReceivePort();
  await Isolate.spawnUri(p.toUri(p.absolute(path)), [], null,
      packageConfig: p.toUri(p.absolute(".packages")),
      onExit: exitPort.sendPort);
  await exitPort.first;
}
```

In Dart 1 mode, this prints the current working directory as expected. In Dart 2 mode, it produces this error:

```
Error: Could not resolve the package 'path' in 'package:path/path.dart'.
package:path/path.dart: Error: Not found: package:path/path.dart.
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Error: Could not resolve the package 'path' in 'pack
age:path/path.dart'.                                                                               
package:path/path.dart: Error: Not found: package:path/path.dart.
```

This is blocking `pub run`'s ability to run in Dart 2 mode.

**Comment by dgrove** [comment]
@a-siva can you find someone to look at this?

**Comment by a-siva** [comment]
The packagesConfig option passed to spawnUri is not being passed to the front end, the CompilerOptions set up for the front end always uses Platform.packagesConfig and hence ends up using that. Will have to add an option in kernel_services.dart to accept a packagesConfig option and pass that in when creating the Compiler object.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/52986 should fix this once it is reviewed.

**Comment by dgrove** [comment]
This change has landed, but the bot didn't seem to close this - @a-siva can this be closed?

**Comment by a-siva** [comment]
Yes, closing it.
