### ISSUE TITLE
DDC should do const evaluation with double arithmetic

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#32964]
For the following:

```dart
const val = 9223372036854775807;
const val2 = val + val;

void main() {
  print(val + val);
  print(val2);
}
```

DDC prints:
```
18446744073709552000
-2
```

It should do double arithmetic in both cases.

**Comment by vsmenon** [comment]
@jmesserly (fyi @mraleph ) I thought we had a bug filed for this, but cannot seem to find it.

**Comment by jmesserly** [comment]
On DDK they both print 18446744073709552000 (which is the result I get in a JS console).

Easy fix here, back out of the const evaluation optimization in DDC's Analyzer backend

**Comment by jmesserly** [comment]
This implements constant evaluation for `dartdevk` with the correct numeric rules: https://dart-review.googlesource.com/c/sdk/+/53121

**Comment by jmesserly** [comment]
Tagging this so we remember it's fixed once we complete kernel migration.

(could be fixed in dartdevc+Analyzer with https://dart-review.googlesource.com/c/sdk/+/52528, but as discussed there, it doesn't seem worth a possible performance hit, so I'm going to abandon that issue.)

**Comment by jmesserly** [comment]
the example now prints an error that the number isn't represented exactly in JS.
