### ISSUE TITLE
Switch default case is ignored in mixin with Dart 2

### ISSUE THREAD

**Issue by deckerst** [dart-lang/sdk#32971]
The following highlights an issue with the default case in a switch statement, depending on whether it is inside a mixin.

```
void main() {
  new TestSwitchClass()
    ..base()
    ..mixin();
}

class TestSwitchClass extends TestSwitchBase with TestSwitchMixin {}

class TestSwitchBase {
  void base() {
    print('base BEFORE');
    switch (42) {
      default:
        print('base WORKS');
        break;
    }
    print('base AFTER');
  }
}

class TestSwitchMixin {
  void mixin() {
    print('mixin BEFORE');
    switch (42) {
      default:
        print('mixin WORKS');
        break;
    }
    print('mixin AFTER');
  }
}
```

Logs from with Dart 1 & 2:
```
td-2:bin thibaultdeckers$ dart main.dart 
base BEFORE
base WORKS
base AFTER
mixin BEFORE
mixin WORKS
mixin AFTER
td-2:bin thibaultdeckers$ dart --preview-dart-2 main.dart 
base BEFORE
base WORKS
base AFTER
mixin BEFORE
mixin AFTER
```

When running this with Dart 2, the default case in the mixin is skipped, so the expected log 'mixin WORKS' is missing.

* Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.48.0.flutter-fe606f890b (Mon Apr 16 21:21:13 2018 +0000) on "macos_x64"

**Comment by vsmenon** [comment]
FYI - @kmillikin @a-siva .  The above repros for me with a VM built yesterday.  The example works fine in DDK, so I'm guessing it's a backend issue, not CFE. 

Not positive though as DDK doesn't opt into kernel mixin lowering.

**Comment by mraleph** [comment]
I'd guess that it's clone visitor again. From a brief look it does not clone `isDefault` flag: 

https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/clone.dart#L343-L358

**Comment by vsmenon** [comment]
Thanks - refiled on kernel.

**Comment by mraleph** [comment]
I'll fix it.
