### ISSUE TITLE
Missing error when directly calling field

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32975]
If a field or getter is called directly, and the field or getter is not of a callable type, the expression is silently accepted.

From `language_2/call_non_method_field_test`:
```dart
class Fisk {
  int i;
}

main() {
  Fisk x1 = new Fisk();
  x1.i(); //# 01: compile-time error
}
```

**Comment by dgrove** [comment]
With -dev.59, the Dart Analyzer produces the error:

Analyzing /usr/local/google/home/dgrove/tmp/dart2stable/32975.dart...
  error • 'i' isn't a function at tmp/dart2stable/32975.dart:7:6 • invocation_of_non_function
1 error found.
