### ISSUE TITLE
Missing error on static vs. non-static setter/member

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32984]
It is a compile-time error if a class contains a static getter and a non-static member with matching name, or vice versa.

Caught by `language_2/bad_override_test`.

**Comment by jensjoha** [comment]
I think this issue can be closed. We've implemented the stuff from https://github.com/dart-lang/sdk/issues/33235#issue-326617285. Those should be the new rules.
Re-open if I'm wrong.
