### ISSUE TITLE
Missing return type check on async and generator functions

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32985]
A function marked `async`, `async*` or `sync*` must have a return type which is a `Future`, `Stream` or `Iterator`, respectively. This check seems to be missing in Fasta.

Exposed by `language_2/async_or_generator_return_type_stacktrace_test` and `language_2/async_return_types_test`.

**Comment by lrhn** [comment]
To be exact, such  a function must have a type which is a supertype of some generic instantiation of `Future`, `Stream` or `Iterable` (not `Iterator`). That is, a type that the *actual* returned object is assignable to. Return types like `Object`, `dynamic` or `FutureOr<int>` (for `async) are *valid*, even if they are much less useful.

**Comment by peter-ahe-google** [comment]
@lrhn isn't there some special case for inferring these types as well?

**Comment by askeksa-google** [comment]
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33068
