### ISSUE TITLE
extra ILLEGAL_ASYNC_RETURN_TYPE warnings  when preview-dart-2 and strong mode are forced off

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32991]
At head, overriding the default --preview-dart-2 with --no-preview-dart-2 and --no-strong creates extra ILLEGAL_ASYNC_RETURN_TYPE warnings, though apparently not on my own personal Linux machine:

https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8948164777367127456%2F%2B%2Fsteps%2Fanalyze_pkg_tests%2F0%2Fstdout

Impacted tests:
```
analyzer/test/src/dart/ast/ast_test: StaticWarning
analyzer/test/src/summary/expr_builder_test: StaticWarning
analyzer/test/src/summary/resynthesize_ast_test: StaticWarning
analyzer/test/src/summary/resynthesize_kernel_test: StaticWarning
front_end/test/incremental_dart2js_load_from_dill_test: StaticWarning
front_end/test/incremental_load_from_dill_test: StaticWarning
```

**Comment by bwilkerson** [comment]
We are no longer supporting these flags, so I believe that this issue is now stale.
