### ISSUE TITLE
dart2js strong: issue with deferred loading instantiations in constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32997]
repro:
**a.dart**:
```dart
import 'b.dart' deferred as b;

main() async {
  await b.loadLibrary();
  print(b.m<int>(3));
}
```

**b.dart**:
```dart
T getFoo<T>(T v) => v;

typedef dynamic G<T>(T v);

m<T>(T x, {G<T> f: getFoo}) {
  print(f(x));
}
```

produces this error:
```
/tmp/out.js:5914: TypeError: O.b__getFoo$closure is not a function
  C.CONSTANT = O.b__getFoo$closure();
```

(`__getFoo$closure` is defined in a deferred unit, but it is being accessed incorrectly from the main chunk)

**Comment by sigmundch** [comment]
FYI @johnniwinther - this started failing as a result of adding InstantiateConstantValue.

I started to investigate, but feel free to take over if I haven't send a fix yet.

**Comment by johnniwinther** [comment]
The example contains a compile-time error since `getFoo` is inferred to be instantiated with `<m.T>` which isn't a constant. The problem still exists if `m` is not generic:

```
T getFoo<T>(T v) => v;

typedef dynamic G<T>(T v);

m(int x, {G<int> f: getFoo}) { // `getFoo` is instantiated with `<int>`.
  print(f(x));
}
```
