### ISSUE TITLE
invalid error from front-end: complaining about not implementing private members

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33009]
I'm seeing compile-time errors produced by the FE in code that I believe is valid.

Seems to come up when using generic types in private members of an interface, and implementing such interface from a different library. Here is an example repro:

**a.dart**:
```dart
import 'b.dart';

class A implements I<dynamic> {
  dynamic get foo => 1;
}
```

**b.dart**:
```dart
class I<T> {
  T get foo => _foo;
  T _foo = null;
}
```

When  running:
```
pkg/front_end/tool/fasta compile --strong a.dart
```

This error is reported:
```
`abstract_wat.dart:3:7: Error: The non-abstract class 'A' is missing implementations for these members:
  '_foo='.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class A implements I<dynamic> {
      ^
abstract_wat.dart:3:7: Context: '_foo=' is defined here.
class A implements I<dynamic> {
```

Marked as P1 as this blocks rolling out dart2js in strong mode (this came up trying to run dart2js in strong-mode using -dev.50 on internal customer applications.)

**Comment by sigmundch** [comment]
Upon closer review, I believe this is a P0, I'll send more details offline.

**Comment by mraleph** [comment]
Moving to P0 because this also blocking the Flutter roll. 

This is likely caused by 9c2fcedaf4abafa1404aafc726323c04fc4d05cd (/cc @askeksa-google) which I suggest reverting unless the fix is easy.

**Comment by sigmundch** [comment]
@mraleph - thanks for the link to the possible cause, I'll try reverting locally to see if it can unblock our work.

The context I wanted to mention earlier is that this shows up on most targets of internal apps, so unless the revert works, it would also block us from making progress on our investigation of dart2js strong-mode issues.

**Comment by aam** [comment]
I tried reverting 9c2fced on https://dart-review.googlesource.com/c/sdk/+/53169 and Siggi's test seem to pass.

**Comment by kmillikin** [comment]
This is because of the forwarding stubs, this is another place where we need logic to treat them as if they weren't there.

**Comment by askeksa-google** [comment]
The check for missing implementations got confused by a forwarding stub. Fix coming up.

**Comment by athomas** [comment]
Sure, I'll create a release as soon as this lands!

**Comment by askeksa** [comment]
The fix has landed.

**Comment by yjbanov** [comment]
Thanks! I'll give it a try asap.

**Comment by athomas** [comment]
I'll create the release.
