### ISSUE TITLE
Type parameters do not shadow library prefixes in instance creation expressions

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#33005]
Given:

```dart
// foo.dart
class Foo {}
```

And:

```dart
import "foo.dart" as T;

class Bar<T> {
  test() {
    new T.Foo(); // <--
  }
}

void main() {
  new Bar().test();
}
```

I expect an error on the marked line because T should refer to Bar's type parameter, not the import prefix T. Instead, all I get from analyzer is:

```
hint • Unused import: 'foo.dart' at temp.dart:1:8 • unused_import
```

If I use T inside `test()` in some other kind of expression, I get the expected error. I think it's only when used in a `new ...` expression that it doesn't get the scope right.

I stumbled onto this while converting the language_2/prefix negative tests to be multitests, so this is probably an ancient bug that was never caught because negative tests make it too easy to mistake the true cause of a failure.

**Comment by lrhn** [comment]
This is a bug. There has been some confusion about whether prefixes were statically scoped in places where they needed to be prefixes (which this isn't, but something like `new p.C.n()` *requires* `p` to be a prefix), but the paragraphs saying that "Dart is lexically scoped" are unambiguous.

**Comment by srawlins** [comment]
Analyzer now reports:

> error • The prefix 'T' can't be used here because it is shadowed by a local declaration. • a.dart:5:9 • prefix_shadowed_by_local_declaration
