### ISSUE TITLE
html.NodeValidatorBuilder is not white listing `href` attribute

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/sdk#33004]
Console reports following error 
```
html_dart2js.dart:50678 Removing disallowed attribute <A href="https://www.example.com/">
f8 @ html_dart2js.dart:50678
```
Even after using a node validator that whitelists `href` attribute
```dart
var modalDivElement = new html.DivElement();
final html.NodeValidatorBuilder _htmlValidator =
        new html.NodeValidatorBuilder.common()
          ..allowElement('a', attributes: ['href']);
modalDivElement.setInnerHtml('<a href="https://www.example.com/">test</a>', validator: _htmlValidator);
html.querySelector("body").append(modalDivElement);
```

This is happening with other users as well , see this issue for example
https://github.com/dart-lang/dart-pad/issues/676

In the pull request that was made to fix this issue, you can see that `href` attribute was previously white listed for `a` elements using `.allowElement('a', attributes: ['href'])`, and still it reports `Removing disallowed attribute <A href=".....`.
https://github.com/dart-lang/dart-pad/pull/689/files

As a result of this , some users(including me), as shown in above pull request have implemented a node validator that allows all attributes to be set without any errors.

See this implementation for example : 
https://github.com/dart-lang/dart-pad/blob/7fa4ad8600c89a689bdc6f52fcfe8628cafd263b/lib/src/util.dart#L23

This is encouraging users to use insecure implementations of `html.NodeValidatorBuilder` for avoiding errors.
When `href` attribute is white listed, it should be allowed to be set without any errors.

Dart version:
Dart VM version: 2.0.0-dev.49.0 (Wed Apr 18 20:41:36 2018 +0200) on "linux_x64"

Browser:
Chromium Version 65.0.3325.181 (Developer Build) (64-bit)

**Comment by alan-knight** [comment]
The problem is not with the href attribute, it's that the default Uri policy is SameOriginUriPolicy and it disallows example.com. I think that's the only implementation provided, so you would need to implement a permissive UriPolicy.
