### ISSUE TITLE
VM compilers error messages should only include source of classes when there's ambiguity

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33006]
From discussion in https://github.com/flutter/flutter/issues/16260#issuecomment-385451443:

Error messages of the form:

```
The following assertion was thrown building MyHomePage(dirty):
type 'List<dynamic>' is not a subtype of type 'List<Widget>' where
  List is from dart:core
  List is from dart:core
  Widget is from package:flutter/src/widgets/framework.dart
```

are confusing; it seems like it's trying to point out an issue w/ `List`, when - after re-reading it - it's clearer that there's no issue. I'm guessing that this is trying to point out classes with the same name but loaded from different libraries. I think to improve this we could remove all lines about which libraries the classes are from, only including them if there are classes with the same names form different libraries. In this case the message would look like:

```
The following assertion was thrown building MyHomePage(dirty):
type 'List<dynamic>' is not a subtype of type 'List<Widget>'
```

and - if there were two `List`s loaded from different libraries, that might look more like:

```
The following assertion was thrown building MyHomePage(dirty):
type 'List<Widget>' is not a subtype of type 'List<Widget>' where
  List is from dart:core
  List is from package:foo_bar
```

/cc @peter-ahe-google @kmillikin for triage

**Comment by peter-ahe-google** [comment]
I can't find the code that produces this error, but I suspect that this is from the Dart VM's runtime.

**Comment by peter-ahe-google** [comment]
It may be `Exceptions::CreateAndThrowTypeError` in `runtime/vm/exceptions.cc` that generates this error.

/cc @crelier

**Comment by devoncarew** [comment]
> I can't find the code that produces this error, but I suspect that this is from the Dart VM's runtime.

Thanks for triaging! I'd assumed this was CFE generated.

**Comment by devoncarew** [comment]
@creisman, are you the right person to take a look at this? We would like to improve the clarity of the error messages here. /cc @a-siva @ mraleph

**Comment by crelier** [comment]
Yes, I can have a look, probably not today, though.
