### ISSUE TITLE
`new List.filled(rows, new List.filled(column, -1))` does not create matrices properly

### ISSUE THREAD

**Issue by HofmannZ** [dart-lang/sdk#33007]
## The code

Initialising a 2d matrix:

```dart
int rows, columns;
<List<List<int>>> matrix;

rows = 4;
columns = 7;
matrix = new List.filled(rows, new List.filled(column, -1))

print(matrix);
``` 

Prints the following list:

```
[[-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1]]
```

Consider the following snippet:

```dart
...

matrix[1][2] = 0;

print(matrix);
```

## Expected output

You would expect the cell at in the 2nd row and 3rd column to has a value of 0:

```
[[-1, -1, -1, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1]]
```

## Actual output 

It actually changes all the rows to have the same value in their 3rd column:

```
[[-1, -1, 0, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1, -1]]
```

## Background

I found this bug while competing in the Google # Hashcode finals. During the competition we decided to switch to C++ because we found it a bit more reliable at this moment in time. We do love the Dart lang and hope we'll be able to submit a solution with it at Google # Hashcode in 2019.

## Environment

Dart: v1.24.3
MacOS: v10.13.4

**Comment by mraleph** [comment]
From documentation for `List.filled`:

> All entries in the returned list point to the same provided `fill` value. That all items in the list are the same object is observable when the given value is a mutable object.
> 
> ```dart
> var shared = new List.filled(3, []);
> shared[0].add(499);
> print(shared);  // => [[499], [499], [499]]
> ```
> 
> You may use `List.generate` to create a new object for each position in in the list.
> 
> ```dart
> var unique = new List.generate(3, (_) => []);
> unique[0].add(499);
> print(unique); // => [[499], [], []]
> ```

https://api.dartlang.org/stable/1.24.3/dart-core/List/List.filled.html
