### ISSUE TITLE
Allow passing DDC module names on the CLI

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33016]
Today we calculate module names based on the [modulePath](https://github.com/dart-lang/sdk/blob/ce7329849d8bb730c80e91252cd60487509e815e/pkg/dev_compiler/lib/src/analyzer/module_compiler.dart#L394) but we need to be able to specify a module name that doesn't match the path.

**Comment by jmesserly** [comment]
yeah, we definitely need to support this.

I believe it's covered by https://github.com/dart-lang/sdk/issues/32272 ... I'll add info to the description to make sure we cover this
