### ISSUE TITLE
Missing check for F-bounded quantization

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#33018]
The following code, in `language_2/f_bounded_quantification_test`, does not give the required errors in Fasta:
```dart
class FBound<F extends FBound<F>> {}

class Bar extends FBound<Bar> {}

class SubBar extends Bar {}

class Baz<T> extends FBound<Baz<T>> {}

class SubBaz<T> extends Baz<T> {}

main() {
  FBound<Bar> fb = new FBound<Bar>();
  FBound<SubBar> fsb = new FBound<SubBar>(); // //# 01: compile-time error

  FBound<Baz<Bar>> fbb = new FBound<Baz<Bar>>();
  FBound<SubBaz<Bar>> fsbb = new FBound<SubBaz<Bar>>(); // //# 02: compile-time error
}
```

**Comment by stefantsov** [comment]
I think this one is an instance of https://github.com/dart-lang/sdk/issues/33308.  Basically, all invocations lack the check that the type arguments don't violate the bounds.  I'm working on it.

**Comment by askeksa-google** [comment]
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33308
