### ISSUE TITLE
dart2js: not a compile-time constant errors reported more than once.

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33013]
We report this error when evaluating constants, and if we find an error we don't fail early, but end up evaluating the same constant multiple times.

**Comment by srawlins** [comment]
@sigmundch fixed with const-update-2018?

**Comment by sigmundch** [comment]
Possibly?

We used to do constant evaluation multiple times and we might still be doing so for some parts of the compilation (even if we use the CFE's constant evaluator). I believe doing things in the CFE will let us stop compilation early if there are errors, so I believe this is now less likely (we still do constant evaluation again later, but I believe the duplicate error scenarios are less likely)

Unfortunately I didn't add any repro cases on this bug, so now it's hard to validate. I'm tentatively closing this and if we find it again we can reopen.
