### ISSUE TITLE
pkg/dev_compiler/tool/kernel_sdk.dart generates files into the source tree during the build.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#33012]
The invocation of `patch_sdk.main()` points its output directory into the source tree: https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/tool/kernel_sdk.dart#L31

Generating files into the source tree during the build is not allowed.

It probably also needs investigation why the patched sdk is generated twice, once by //utils/dartdevc:dartdevc_patch_sdk into the build output (correct) , and once by //utils/dartdevc:dartdevc_sdk_kernel_summary into the source tree (incorrect). Maybe //utils/dartdevc:dartdevc_sdk_kernel_summary should depend on and use the output of //utils/dartdevc:dartdevc_patch_sdk ?

Marking P1 because this will cause mysterious build problems eventually.

/cc @vsmenon @peter-ahe-google

**Comment by jmesserly** [comment]
(cleared assignment because I'm not sure who will pick this up. Vijay and Bob are more familiar with the build rules in utils/dartdevc/BUILD.gn, having worked on the original code there. But I might be working in that area soon, if so then I'll take a look at this. Building into the source tree is not good.)

**Comment by vsmenon** [comment]
Looking at the snapshotting code for Dart 2 DDC.  I'll see if I can fix this as well.

**Comment by peter-ahe-google** [comment]
Perhaps we can remove the use of patch_sdk? Fasta should be able to read patch files directly now. This generally improves the source locations we embed in the platform dill file. Please reach out to me on GVC if you need more info.

**Comment by jmesserly** [comment]
> Perhaps we can remove the use of patch_sdk? Fasta should be able to read patch files directly now. This generally improves the source locations we embed in the platform dill file. Please reach out to me on GVC if you need more info.

oh that's an great idea! I tried it at first in the DDC to Kernel port but it wasn't implemented at that time. Filed: https://github.com/dart-lang/sdk/issues/33036

**Comment by zanderso** [comment]
@jmesserly can you verify that https://github.com/dart-lang/sdk/commit/d87642df9cd3b74815105e0579d89e1cb877e434 fixes this as well?

**Comment by jmesserly** [comment]
yes this is fixed

**Comment by zanderso** [comment]
Thanks!
