### ISSUE TITLE
Add a dartk-sim* to the CQ to catch issues early-on

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33021]
Recently a commit caused all dartk-sim* builders to stop working. The CQ should catch such issues early on.

Can we have, e.g. a release-simdbc64 on the CQ?

/cc @mraleph

**Comment by athomas** [comment]
https://ci.chromium.org/p/dart/builders/luci.dart.try/vm-kernel-linux-release-simdbc64-try is running on the CQ as an experiment. If it is stable (it should be given that it does the same as the CI builder), I will enable it properly.

**Comment by mkustermann** [comment]
Thanks a lot!
