### ISSUE TITLE
Isolate.spawnUri() with a data: URL doesn't work in Dart 2

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#33028]
When running the following code with `--preview-dart-2`:

```dart
import 'dart:isolate';

main() async {
  var data = new UriData.fromString("""
    import 'dart:convert';
    import 'dart:isolate';

    main() async {
      print("in isolate!");
    }
  """,
      mimeType: "application/dart");

  await Isolate.spawnUri(data.uri, [], null);
}
```

it fails with

```
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: data:application/.packages: Error: Unable to read '.packages' file:
  FormatException: Expecting '='
application/.packages.
#0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:454:14)
<asynchronous suspension>
#1      main (file:///home/nweiz/test.dart:14:17)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Tested on Dart 2.0.0-dev.52.0.

**Comment by dgrove** [comment]
This will block some needed packages from moving to Dart 2.

**Comment by a-siva** [comment]
The front end seems to come back with this error when we call it to compile the script before spawning the isolate.

**Comment by lrhn** [comment]
The error message suggests that the front-end doesn't recognize a `data` URI as non-hierarchical, then tries to resolve `".packages"` against it and load that file. The loader recognizes the protocol and decodes the bungled data URI. The result is as random as can be expected.

We should probably just recognize `data` URIs in the `Uri` class and block you from resolving against them, at least it will err earlier and with a better message.

The solution would be for the front-end to skip `.package` file loading on `data` URIs. That means that the `data` backed library cannot resolve package URIs unless the call gets an explicit `packageConfig` parameter, but that should already be the case anyway.

**Comment by askeksa-google** [comment]
The given test case does not fail after https://github.com/dart-lang/sdk/issues/32950 was fixed. Can this be closed as a duplicate?

**Comment by dgrove** [comment]
@natebosch @grouma can you take a look to see if this can be closed?

**Comment by grouma** [comment]
This still is an issue with: Dart VM version: 2.0.0-dev.54.0 (Unknown timestamp) on "linux_x64"

Getting the following:

```
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: data:application/.packages: Error: Unable to read '.packages' file:
  FormatException: Expecting '='
application/.packages.
#0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:454:14)
<asynchronous suspension>
#1      main (file:///usr/local/google/home/grouma/Projects/scripts/test.dart:17:31)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by grouma** [comment]
I had to reimage my machine today for unrelated reasons. I ran the test again and now it is passing. I still have the same SDK version:
Dart VM version: 2.0.0-dev.54.0 (Unknown timestamp) on "linux_x64"

@natebosch can you update your SDK and run the tests as well. I want to verify that it is truly fixed before closing the issue.

**Comment by dgrove** [comment]
Strange - I just tried this at tip of bleeding edge (Dart VM version: 2.0.0-edge.779dc6eb85c1f2249803d017ffa785c85681ad1b (Wed May 9 21:33:09 2018 +0000) on "linux_x64"
), and it's failing for me.

**Comment by dgrove** [comment]
This is working fine at tip for me. Closing.

I'm using Dart VM version: 2.0.0-edge.57dee60d4d1ef66de7494636d9c93418eb7201f0 (Fri May 11 00:03:35 2018 +0000) on "linux_x64"
