### ISSUE TITLE
Dart 2 runtime failures in analyzer tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#33026]
Running the tests in dart2 causes runtime failrues

type '_BroadcastStream<dynamic>' is not a subtype of type 'Stream<FileSystemEvent>' where...
type '_BroadcastStream<dynamic>' is not a subtype of type 'Stream<FileSystemEvent>' where
  _BroadcastStream is from dart:async
  Stream is from dart:async
  FileSystemEvent is from dart:io
dart:io                                                                                                    FileSystemEntity.watch
package:watcher/src/file_watcher/native.dart 46:10                                                         _NativeFileWatcher._listen
package:watcher/src/file_watcher/native.dart 36:5                                                          new _NativeFileWatcher
package:watcher/src/file_watcher/native.dart 19:31                                                         new NativeFileWatcher.<fn>
package:watcher/src/resubscribable.dart 47:21                                                              new ResubscribableWatcher.<fn>
dart:async                                                                                                 _StreamImpl.listen
../../analyzer/test/file_system/physical_resource_provider_test.dart 683:39  PhysicalResourceProviderTest._watchingFile.<fn>

and a few more.

to repro, 

dart --preview-dart-2 my_test.dart

**Comment by dgrove** [comment]
This is likely a dup of #33027

**Comment by bwilkerson** [comment]
I believe that's the case, yes.
