### ISSUE TITLE
VM should have option to produce a full kernel file

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#33035]
We have clients that want to run their program in dart 2 mode on a stripped down VM. Need a kernel file that contains both program + libraries to support this use case.

**Comment by mkustermann** [comment]
You can get a binary Kernel IR file (.dill file) containing the entire application, dart:* libraries, vmservice_io, etc using:

```
# Compile the app
$ pkg/front_end/tool/fasta compile --platform=out/ReleaseX64/vm_platform_strong.dill -o app.dill app.dart

# Bootstraps & runs the app entirely from the app.dill file (doesn't use built-in core libraries)
$ out/ReleaseX64/dart app.dill
```

You can look at the contents of the dill file via:
```
$ pkg/kernel/bin/dump.dart app.dill app.txt
$ vim app.txt
```

That being said, I'm not sure if there's a `dart` binary without the core library snapshot /  platform file inside you can use this way.

**Comment by a-siva** [comment]
These pkgs that you mention are not part of the Dart sdk that we build and I believe the bug has been filed to raise this point.

Currently the dart executable is used for everything (building snapshots, app jit snapshots ...) and maybe for consistency it might make sense to have the same executable produce this whole app also. The requirement comes from the Yeti project who want to install the 'product dart executable' on their device (size constraints has to be < 5MB) and would like to then ship their app and have it be run.

**Comment by a-siva** [comment]
I think the priority on this can be dropped as the project Yeti which originally requested for this feature has changed their product strategy a bit. Not sure if there is still a need for this feature.

**Comment by a-siva** [comment]
Closing issue as requirement for this feature does not exist anymore.
