### ISSUE TITLE
Roll latest pub w/ 500 retry, fix for flutter version, better errors, etc

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33030]
Soon would be great!

**Comment by nex3** [comment]
Do we want to do this before Dart 2 support for pub run lands?

**Comment by kevmoo** [comment]
I think there are enough fixes here to warrant a roll. Unless we think Dart2 support will land in the next day or two

**Comment by nex3** [comment]
There's a PR out for it now: https://github.com/dart-lang/pub/pull/1893

**Comment by kevmoo** [comment]
Cool! Worth waiting for...
