### ISSUE TITLE
Ability to pass closures through isolates in server

### ISSUE THREAD

**Issue by BSFishy** [dart-lang/sdk#33047]
I am working on a CLI program and could really use the ability to pass closures through isolates. I can see it is implemented in JS, and was wondering if there are any plans to implement it in CLI as well.

**Comment by BSFishy** [comment]
I'll get a little more in depth with what I am trying to do(my apologies). I am trying to make a library ontop of the existing `HttpServer`(or whatever it's called) which allows the developer to register their routes and pages to the server, but also allows the server to refresh the files which are being used to register the routes and pages. That way the server allows for easy development as well as a quick response solution. At this point in time, I am trying to implement `onLoad`, `onStart`, and `onStop` functions which would be called in those points in time of initializing the server/sites. What I am trying to do is pass those over to the main thread, or server(the other files which register the routes and pages are created in other isolates using `spawnUri`). I could create a cache of those functions on the client side(side with routes), but I feel like I would have more control if it were on the server side.

**Comment by mkustermann** [comment]
Sending arbitrary closures to other isolates is currently tracked at https://github.com/dart-lang/sdk/issues/40370.
Hope it's ok if I close this in favor of https://github.com/dart-lang/sdk/issues/40370 - since most of the discussion is on that issue.
