### ISSUE TITLE
Trying to spawn an isolate w/ seemingly okay Data URIs fails

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33056]
Dart VM version: 2.0.0-dev.53.0 (Thu May 3 12:35:47 2018 +0200) on "macos_x64"

```dart
import 'dart:isolate';

void main(List<String> args, [SendPort sendPort]) async {
  sendPort.send('../../../../../../../../../../../etc/passwd%00');
}
```

`data:;charset=utf-8,import%20'dart:isolate';%0A%0Avoid%20main(List%3CString%3E%20args,%20%5BSendPort%20sendPort%5D)%20async%20%7B%0A%20%20sendPort.send('../../../../../../../../../../../etc/passwd%2500');%20%20%0A%7D%0A`

yields

```
  IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
  FormatException: Invalid MIME type (at character 10)
  data:/etc/passwd%2500');%20%20%0A%7D%0A
           ^

  #0      UriData._parse (dart:core/uri.dart:3616)
  #1      Uri.parse (dart:core/uri.dart:796)
  #2      _resolveScriptUri (dart:_builtin:223)
  dart:isolate                              Isolate.spawnUri
```

Also

```dart
import 'dart:isolate';

void main(List<String> args, [SendPort sendPort]) async {
  sendPort.send('../../../../../../../../../../../etc/hosts');
}
```

`data:;charset=utf-8,import%20'dart:isolate';%0A%0Avoid%20main(List%3CString%3E%20args,%20%5BSendPort%20sendPort%5D)%20async%20%7B%0A%20%20sendPort.send('../../../../../../../../../../../etc/hosts');%20%20%0A%7D%0A`

```
  IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
  FormatException: Invalid MIME type (at character 10)
  data:/etc/hosts');%20%20%0A%7D%0A
           ^

  #0      UriData._parse (dart:core/uri.dart:3616)
  #1      Uri.parse (dart:core/uri.dart:796)
  #2      _resolveScriptUri (dart:_builtin:223)
  dart:isolate                              Isolate.spawnUri
```

**Comment by kevmoo** [comment]
@lrhn – something you can ponder?

**Comment by kevmoo** [comment]
...in both cases, using `new Uri.dataFromString(script, encoding: utf8);`

**Comment by lrhn** [comment]
Krutz! Seems like URI path normalization is applied to a data URI, so the `..`'s remove preceding content up to the `data:` . That's just wrong.

**Comment by lrhn** [comment]
Data URIs are no longer path-normalized.
