### ISSUE TITLE
codegen/string_escapes_test doesn't work with CFE

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#33060]
The dart2js unittest codegen/string_escapes_test doesn't work with CFE.

**Comment by anders-sandholm** [comment]
Not sure if dart2js or front-end issue. Why not both?

**Comment by johnniwinther** [comment]
Good call - we need to coordinate the solution.

**Comment by rakudrama** [comment]
One of the errors is a source string containing `\u2080\u2029`. This shows up in the generated code as `()`, which is U+0028 U+0029.
So it seems that the code units are being truncated to the low byte somewhere, perhaps by storing code units into a `Uint8List`.

If the input is changed to `\u2028\u2029\u20c1` then the output becomes `()\ufffd`. This indicates that the low 8 bits are being interpreted as UTF-8, with `0xc1` being mapped to the error replacement character U+FFFD.

**Comment by lrhn** [comment]
If you look in `source_file_helper`, requesting a binary file for something supplied as a string to the memory source files does:
```dart
case InputKind.binary:
        if (source is String) {
          utf8SourceFiles[resourceUri] =
              new StringSourceFile.fromUri(resourceUri, source);
          source = source.codeUnits;
        }
        input =
            binarySourceFiles[resourceUri] = new Binary(resourceUri, source);
        break;
```
If the string is not Latin-1, this puts 16-bit integers into the `Binary` input. I'm guessing it's being truncated when read from that.
