### ISSUE TITLE
CFE: Missing compile time errors for async, async*, and sync* methods with incompatible return type

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#33068]
For example:
`int badReturnTypeAsync() async {} // //# 01: compile-time error`

Tests:
`language_2/async_or_generator_return_type_stacktrace_test_0{1,2,3}`
`language_2/async_return_types_test/{wrongReturnType,nestedFuture}`

**Comment by dgrove** [comment]
with -dev.59:

cat ~/tmp/dart2stable/33068.dart
int badReturnTypeAsync() async {} // //# 01: compile-time error


dgrove@dgrove:~$ /usr/lib/google-dartlang/bin/dartanalyzer --preview-dart-2 ~/tmp/dart2stable/33068.dart 
Analyzing /usr/local/google/home/dgrove/tmp/dart2stable/33068.dart...
  error • Functions marked 'async' must have a return type assignable to 'Future' at tmp/dart2stable/33068.dart:1:1 • illegal_async_return_type
  hint • This function declares a return type of 'int', but doesn't end with a return statement at tmp/dart2stable/33068.dart:1:1 • missing_return
1 error and 1 hint found.

**Comment by dhil** [comment]
[A recent commit](https://github.com/dart-lang/sdk/commit/b244c0805d9741510526566d69b5cf0f9eacf303) includes a fix such that the fasta now (correctly) produces an error whenever the declared return type of an `async` function is not a super type of `Future`.

I think this fix can be generalised to handle `async*` and `sync*` cases. I'll look it into.
