### ISSUE TITLE
covariance checks too late for `sync*` `async*`

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#33066]
Right now, covariance checks won't happen until we get inside the generator body. So you have to start iterating over the iterator, or listening to the stream.

@leafpetersen does it sound right that we should do these checks synchronously? See tests in https://dart-review.googlesource.com/c/sdk/+/53862

In DDC we can fix this in _emitGeneratorFunction. Right now covariance checks are emitted (along with argument initializers) inside the JS generator body. We can probably move the checks outside the generator pretty easily (and possibly the argument initializers too? I think that's semantic preserving, since they must be constants.)

**Comment by jmesserly** [comment]
I'm not totally sure how precise we want to specify these. It may be nice to leave implementations free to do checks later--as long as the checks happen before use, it prevents unsound access. That said, DDC is a development compiler, so it may make sense for us to check as eagerly as possible.

**Comment by lrhn** [comment]
We want to specify it exactly. It's part of the language semantics, and there shouldn't be any slack.

I agree that parameter type checks should happen synchronously, and that includes covariant type checks. Type checks are part of function *invocation*, when actual arguments are bound to formal parameters. There cannot be a time where the formal is bound to an invalid value. Effectively it's invisible whether the type is checked at the call point or inside the function, either implementation is allowed.

**Comment by jmesserly** [comment]
Sounds good to me :)

**Comment by leafpetersen** [comment]
Agreed, do the checks eagerly.

**Comment by jmesserly** [comment]
fyi -- @Markzipan is working on the fix in CL https://dart-review.googlesource.com/c/sdk/+/97945 (under review)
