### ISSUE TITLE
CFE missing compile time errors on invalid bounds in mixins

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#33071]
Tests:
`language_2/mixin_invalid_bound_test` and `language_2/mixin_invalid_bound2_test`

**Comment by stefantsov** [comment]
I think this issue is an instance of https://github.com/dart-lang/sdk/issues/33308.  It affects not only mixins, but all other class kinds as well.

**Comment by askeksa-google** [comment]
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33308
