### ISSUE TITLE
Rename `retype` to `cast`, overriding old `cast`. Deprecate and remove `retype` functions. 

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#33075]
The `cast` and `retype` methods on numerous types are confusing and removing `cast` will make the API better for users. We will reuse the `cast` name for the current `retype` behavior.

Steps:
* [x] Change `cast`  to work as `retype` (fails no tests in the SDK, five tests in google3) and deprecate `retype`. ([CL](https://dart-review.googlesource.com/c/sdk/+/53802))
* [x] Roll into google3.
* [x] Change all calls to `retype` to call `cast` instead after rolling in the change.
* [ ] Update packages to use `cast` instead of `retype`.
* [x] Remove `retype` from SDK.
* [ ] Remove `retype` from packages that manually implement `retype` on the interfaces.

**Comment by leafpetersen** [comment]
This is in process.  The initial change has landed, waiting on a roll.

**Comment by dgrove** [comment]
The roll has now occurred.

**Comment by leafpetersen** [comment]
@lrhn How is this going?

**Comment by lrhn** [comment]
I have two remaining CL's out that I need land in google code, and one in Flutter, then neither should be using `retype` any more (or at least be resistant to it being removed).
I have made a PR for `package:observable`, so it too should be good. I still have to check if there are any other packages affected.

**Comment by dgrove** [comment]
Any further updates, @lrhn ?

**Comment by lrhn** [comment]
Since retype has been removed from the SDK, packages are now forced to be updated, and it seems we are on-track for that within this week.

Going back and removing the, now unnecessary, retype declarations from packages can be handled on a per-package basis.

**Comment by mit-mit** [comment]
The work here is believed to be complete; just need to double-check that this was rolled to google3

**Comment by mit-mit** [comment]
@whesse can you help confirm that this is in google3?

**Comment by natebosch** [comment]
> Remove retype from packages that manually implement retype on the interfaces.

I haven't seen this effort - are we planning on pushing it to package owners? I wouldn't consider it blocking for Dart2Stable if that is all that is remaining.

**Comment by whesse** [comment]
I don't know anything about this, or how to find out which SDK and third_party package versions are in Google3.

**Comment by mit-mit** [comment]
@srawlins any chance you know?

**Comment by srawlins** [comment]
No, but I suspect the following packages: collection, observable, and quiver. I don't know of any internal manual implementations.

**Comment by dgrove** [comment]
The SDK which removes retype hasn't yet landed in google3.

**Comment by dgrove** [comment]
Internal work here is done.

**Comment by dgrove** [comment]
@mit-mit lowering priority, and removing from Dart2Stable (if you disagree, please add back).
