### ISSUE TITLE
stackTrace property not visible for some error types in chrome dev console

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33088]
You can repro this with a basic web project, throwing an `UnsupportedError` will give you the stack trace property in the chrome dev console, but throwing an `ArgumentError` will not.

```dart
main() {
  // Works as expected, shows `stackTrace` property
  throw new UnsupportedError('');
  // Doesn't show the `stackTrace` property
  throw new ArgumentError();
}
```

You can use build_runner to build/serve the app above, put it in `web/main.dart`, make a pubspec.yaml like this:

```yaml
name: example
dev_dependencies:
  build_runner: any
  build_web_compilers: any
```

And a `web/index.html` like this:

```html
<script src="main.dart.js"></script>
```

And then run `pub run build_runner serve` and load up `localhost:8080` in your browser.

I tracked this down to [getGetters](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/tool/input_sdk/private/ddc_runtime/classes.dart#L176) not returning the stackTrace property but didn't go further than that.

**Comment by vsmenon** [comment]
I think this may be fixed now.

**Comment by nshahan** [comment]
I see the stack traces for both now.
