### ISSUE TITLE
Common front end: Support metadata on enum values

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33083]
This is the common front end specific issue for #33082, which has the details.

**Comment by kmillikin** [comment]
I don't think we'll hit this for the Beta 4 milestone so I'm adding it to Dart 2 stable.

**Comment by leafpetersen** [comment]
I went ahead and took the Dart2Stable milestone off, since I don't think this is a release blocker.

**Comment by kevmoo** [comment]
We now have `dartfmt` and analyzer support – t'would be sad to not get this in for v2.

It's a common request for json_serializable

**Comment by stefantsov** [comment]
I think we have a chance.  I'm working on it in [CL 56496](https://dart-review.googlesource.com/c/sdk/+/56496).
