### ISSUE TITLE
dart2js: investigate possibly dead code in emitter

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33081]
`existingIsolateProperties` seems to not be defined anywhere. delete?

https://github.com/dart-lang/sdk/blob/74d03e7a75b3d0a8947a1b71a2ebe73f1b34f97a/pkg/compiler/lib/src/js_emitter/full_emitter/setup_program_builder.dart#L416

**Comment by joshualitt** [comment]
Closing because this seems to be deleted.
