### ISSUE TITLE
Override completions appear inconsistently within a class

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33084]
While working on the Folding visitor in the analysis server I noticed something weird. Depending on where I start typing `visit` I may or may not get completion items for the visit methods.

The class currently has a bunch of visitor methods implemented (directives). If I type `visit` after the last one (but before the last method in the class) I do not get the completions; yet if I type it between any of the existing visit overrides, I do get them.

Before I typed `visit` the code is all syntactically valid.

<img width="841" alt="screen shot 2018-05-09 at 10 59 30 am" src="https://user-images.githubusercontent.com/1078012/39808951-60777534-5378-11e8-8f54-e68e71983929.png">

<img width="865" alt="screen shot 2018-05-09 at 10 59 18 am" src="https://user-images.githubusercontent.com/1078012/39808957-6587e8ce-5378-11e8-8858-afbdc6fdc235.png">

Maybe related: In the cases where it works, the next characters are `@override` and the `@` gets a red squiggle. I have raised cases about not getting override completions before, but I'm not sure this is the same thing; this feels more like a bug whereas that felt more like a feature request.

(cc @bwilkerson)

**Comment by bwilkerson** [comment]
My first guess is that analyzer's parser is producing different AST structures in those two cases. The completion support uses the AST structure to decide which suggestions to offer. It would return different suggestions if the structures are different. If that's true, then it should be easy to support the other structure as well.

**Comment by bwilkerson** [comment]
This appears to have been fixed, so I'm going to close it.
