### ISSUE TITLE
We should not run _2 test suites in Dart 1.0 mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33085]
For those test suites where we have explicit _2 variants (e.g. lib_2) we should not run Dart 1.0 mode VM on them.

For example we do that on `target-arm64-vm-linux-release-be`:

```
tools/test.py '--mode=release' '--arch=arm64' '--progress=line' --report --time --write-debug-log --write-result-log --write-test-outcome-log --checked --append_logs

...
FAILED: none-vm-checked release_arm64 lib_2/mirrors/immutable_collections_test
Expected: Pass
Actual: Timeout
```

@whesse Maybe you could take a look at this?

**Comment by whesse** [comment]
Should this be a skip in the status file, for the non-dart-2 modes?  What characterizes those modes?

**Comment by mkustermann** [comment]
I thought this is already configured somewhere (e.g. where 2.0 is not running the v1 test suites). Maybe @athomas knows.

`test.dart` shouldn't enqueue those suites, then there is no need for marking the status files with skips.

**Comment by mkustermann** [comment]
For the `language_2` test suite, I've done this now in 0cd9497f96c98d7772f32f4b1be5f9abbced1546 (it has removed many status file lines)

**Comment by athomas** [comment]
The dart 1 tests will be removed soon anyway, so I'm closing this.
