### ISSUE TITLE
dart2js crash:  omit bound checks when omitting implicit checks

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33093]
```dart
class A<T> implements Comparable<A> {
  int compareTo(A other) => 0;
}

int _f<T extends Comparable>(T a, T b) => a.compareTo(b);

typedef int Comparator<R>(R a, R b);

class B<Q extends Comparable> {
  Comparator<Q> c;
  B(c): c = c ?? _f;
}

main() {
  new B<A>(null).c(new A<int>(), new A<int>());
}
```

**Comment by sigmundch** [comment]
Oops - forgot to write text: the random piece of code above reproduces the problem.

@johnniwinther - can you take a look?

**Comment by sigmundch** [comment]
The crash happens only with --strong and --omit-implicit-checks

**Comment by sigmundch** [comment]
OK - seems that what's wrong here is that we are generating a check even with omit-implicit-checks.

Should we actually skip the check in that case?

In particular, if you tweak the code to force us to believe that the runtime type is needed, you can see that the generated code includes the assertion:
```js
_f: [function(a, b, $T) {                                                    
       H.assertIsSubtype($T, P.Comparable, "The type argument '", "' is not a subtype of the type variable bound '", "' of type variable 'T' in '_f'.");
       return 0;
}
```

I've updated the title to match what I expect.

**Comment by sigmundch** [comment]
I took a stab at omitting the check when we pass `--omit-implict-checks` here: https://dart-review.googlesource.com/c/sdk/+/54627

However, that is not enough to prevent the crash.

**Comment by vsmenon** [comment]
@sigmundch will be out for a while - @johnniwinther - will you be able to take a look?

**Comment by johnniwinther** [comment]
The problem is that we don't register need for rti through instantiations.

I'm working on a fix.
