### ISSUE TITLE
Dart spec forbids escapes in triple-quoted ("multiline") strings

### ISSUE THREAD

**Issue by cpovirk** [dart-lang/sdk#33090]
I'm looking [in the first edition ECMA spec](https://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-408%201st%20edition%20June%202014.pdf#page=56) and [in the Dart 2 `.tex` spec](https://github.com/dart-lang/sdk/blob/779dc6eb85c1f2249803d017ffa785c85681ad1b/docs/language/dartLangSpec.tex#L3563).

Both define `stringContentTDQ` as:

```
stringContentTDQ:
˜( ‘\’ | ‘"""’ | ‘$’) |
stringInterpolation
;
```

That's in contrast to `stringContentDQ`, which is defined as:

```
stringContentDQ:
˜( ‘\’ | ‘"’ | ‘$’ | NEWLINE ) |
‘\’ ˜( NEWLINE ) |
stringInterpolation
;
```

The effect, if I understand correctly, is that `stringContentTDQ` doesn't permit the escapes that `stringContentDQ` does. Similarly for `stringContentTSQ`.

But Dart appears to permit escapes in practice. (I also found this [random Dart grammar](http://casadev.cs.au.dk/DART_BENCHMARKS/dart-petitparser/blob/4f5480087f886c8d02e98d50b82f2c00021b60b1/lib/src/dart/grammar.dart#L500) that follows suit.) I'd guess(?) that's the desired behavior and that the spec is wrong, but obviously you'd know better :)

* Dart SDK Version (`dart --version`)
I tested with 1.25.0 (Dartpad). I wouldn't be surprised if this applied to Dart 2, as well, but I haven't checked.

* Whether you are using Windows, MacOSX, or Linux (if applicable)
presumably N/A for Dartpad, but Linux if it matters

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
presumably N/A here, but Chrome if it matters

**Comment by lrhn** [comment]
Definitely a spec issue, not an implementation issue.
A non-raw multiline string should accept escapes (otherwise you wouldn't need raw multiline strings).

**Comment by eernstg** [comment]
[Here](https://dart-review.googlesource.com/c/sdk/+/61923)'s a CL for that.

**Comment by eernstg** [comment]
Closing: As of 5d4dbdac5c096b5614982c50498c0efd651f26a6, the spec was adjusted to allow these escape sequences.
