### ISSUE TITLE
Missing CFE error: super calls must be last

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33101]
In Dart 2, super calls must appear last in the initializer list.  The CFE is missing this error (see repro below).

@lrhn @eernstg Do we need to update the spec for this?

cc @munificent 

```dart
class A {
}

class B extends A {
  int x;
  B() : super(), x = 0 {} 
}

void main() {
  new B();
}
```

**Comment by eernstg** [comment]
Regarding the spec update: It was needed, but was done in be0969b249ddab83ef148351a5c4c716100393e0 (that is, on Aug 20).
