### ISSUE TITLE
By default, dartanalyzer should ignore files under .dart_tool

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33112]
AFAIR, I used to be able to run the dartanalyzer over all of a project's folder by running:

    dartanalyzer .

and the analyzer would ignore the files under `.pub`.

Ever since we've moved to `.dart_tool`, I can't use `.` as a directory specifier anymore since the analyzer seems to go through the files in `.dart_tool` too.

cc @kevmoo @kwalrath

**Comment by chalin** [comment]
Maybe ignoring the content of `build` would be a good idea too.

**Comment by chalin** [comment]
Hmm, I'm unsure if it is `.dart_tool` or `build` that is the problem. My point is that I can't seem to run `dartanalyzer .` from project roots anymore. I'd like to be able to run this command again, since I'm using the same command over all Angular example apps, and not all of the them have the same `lib`, `web` and `test` folders present.

**Comment by vsmenon** [comment]
@bwilkerson - fyi.  Does analyzer have a list of directories that it ignores?

**Comment by bwilkerson** [comment]
Yes, it should. I thought we had made it ignore hidden files and directories, though, so I'm not sure what's going on here. It's quite likely, at this point, that the behavior is inconsistent depending on which too is being used and how it's being used.

**Comment by chalin** [comment]
> > Does analyzer have a list of directories that it ignores?
>
> Yes, it should.

Does it include `build`? (Where is this list?)

**Comment by matanlurey** [comment]
The folder `build` means nothing in PBR, you can call it whatever you want with `-o chalin`.

**Comment by chalin** [comment]
Right, I understand that; as I mentioned earlier, my point was that we previously didn't have to do anything special to have hidden directories or `build` ignored. If there is a break in behavior, maybe it should at least be mentioned in the SDK changelog -- along with a suggestion on how to get equivalent behavior.

In the meantime, I've added the following line to all example app `analysis_options.yaml` files:

```yaml
analyzer:
  exclude: [.*/**, build/**]
```

(Which is probably what we'll end up having to do.)

**Comment by bwilkerson** [comment]
> Where is this list?

Unfortunately, it's procedurally encoded and not all in one place. One of the places is sdk/pkg/analyzer_cli/lib/src/driver.dart:590.

**Comment by chalin** [comment]
FYI, as of 2-dev.59 I can't seem to reproduce the issue I saw with `.dart_tool`. Closing. /cc @kevmoo
