### ISSUE TITLE
Error in compiler

### ISSUE THREAD

**Issue by vettukal** [dart-lang/sdk#33125]
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk --dart-sdk-summary=C:\tools\dart-sdk/lib/_internal/ddc_sdk.sum --modules=amd -o mapping=file:///test/app_test.dart.browser_test.dart,test/app_test.dart.browser_test.dart file:///test/app_test.dart.browser_test.dart
    dart --version: 2.0.0-dev.55.0 (Mon May 14 09:23:07 2018 +0200) on "windows_x64"
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4268)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54)
#3      TableReader.read (package:front_end/src/base/flat_buffers.dart:694)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:4174)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:939)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:502)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:405)
#8      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:405)
#10     new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:93)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:131)
#12     compile (package:dev_compiler/src/analyzer/command.dart:57)
#13     _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43)
<asynchronous suspension>
#14     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33)
<asynchronous suspension>
#19     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23)
<asynchronous suspension>
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```
}

**Comment by vsmenon** [comment]
@jakemac53 @jmesserly - this looks like an invalid summary file?

**Comment by jmesserly** [comment]
> @jakemac53 @jmesserly - this looks like an invalid summary file?

yes, it's blowing up reading the summary file. How was the build invoked?

We could catch the exception from `new SummaryDataStore` in DDC but I'm not sure we'd have any useful information to print. We need at least the Analyzer exception to tell us what file it was reading at the time.

**Comment by jmesserly** [comment]
Hmmm, even more strange: I don't see a `-s` option passed in on the command line, so there shouldn't even be any summary paths? (the SDK doesn't count; that's processed at an earlier point). The stack trace implies there's a `-s` or `--summary` option, but the command line arguments don't show that.

**Comment by natebosch** [comment]
this doesn't look quite like I would expect for how `build_web_compilers` invokes DDC - how are you running a build here?

**Comment by vettukal** [comment]
Just used the standard sdk.

**Comment by natebosch** [comment]
> Just used the standard sdk.

dartdevc isn't a compiler that is easy to use without being integrated specifically with a build system. If you're invoking this manually it's likely that the command line args are incorrect.
