### ISSUE TITLE
Enable hot-reload bot testing on mac in Dart 2.0 mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33126]
Currently the [tools/bots/test_matrix.json](https://github.com/dart-lang/sdk/blob/master/tools/bots/test_matrix.json#L396) contains only one entry for app_jit, which seems to be running it in `tools/test.py --mode=debug,release,product --compiler=app_jit` mode.

We should start testing app_jit training in Dart 2.0 mode, i.e. `--compiler=app_jitk --strong`.

@athomas Could you take a look at this?

/cc @a-siva @rmacnak-google @mraleph

**Comment by mkustermann** [comment]
Similarly to `app_jit` we also should have reload builders running in 2.0 mode (it seems the current 6 builders we have run only in legacy mode).

Given I've read some emails about switching things now to 2.0 mode by default we might want to give this issue a **higher priority** now. @a-siva @mraleph wdyt?

**Comment by athomas** [comment]
- [ ] Add -capp_jitk option to test.py (CL sent for review)
- [ ] Add test matrix config for app_jitk (CL sent for review)
- [ ] Add test matrix config for reload/rollback (CL sent for review)
- [ ] Update status files (app_jitk)?
- [ ] Update status files (reload/rollback)?
- [ ] Add luci config for app_jitk (CL sent for review)
- [ ] Add luci config for reload/rollback

app_jitk release trial run (maybe just needs status updates):
https://luci-milo.appspot.com/swarming/task/3da702739035a710

app_jitk product trial run (completely broken, @mkustermann):
https://luci-milo.appspot.com/swarming/task/3da6f324a8d11310

**Comment by mkustermann** [comment]
> app_jitk product trial run (completely broken, @mkustermann):

@athomas Actually this particular issues seems to have been fixed just yesterday in e35ed9c74951424b98f1c3e82c83b2a0f809b6f8 :)

**Comment by athomas** [comment]
Status update:
app_jitk builders are in production now.
reload/rollback builders should follow later this week.

**Comment by mkustermann** [comment]
The hot reload builders are blocked on https://github.com/dart-lang/sdk/issues/33277 (currently it seems to crash a lot). So we'll first have to look into this before we add hot-reload builders.

**Comment by dgrove** [comment]
#33277 has been fixed, so removing blocked state.

**Comment by athomas** [comment]
This is still totally broken on mac:
https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2Fb5abdd97a2554229ecd583fb570c5c4615c3b1508ea60c794593946861fb4bb3%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout

https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2Fcb93f06bb1deca86f955f2d5491dc4ea60e41074f321bdb948829adc8d7ed3d8%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout

**Comment by dgrove** [comment]
Any updates here? Are we unblocked enough for PreRelease1, @athomas ?

**Comment by athomas** [comment]
Everything I can do until #33291 is addressed has been done. Reload can't be tested on Mac until then but the linux builders are running.

**Comment by dgrove** [comment]
#33291 isn't targeted for PreRelease 1. Perhaps both should be targeted for
Dart2Stable ?

**Comment by athomas** [comment]
Makes sense, I updated the milestones.

**Comment by a-siva** [comment]
I changed the description to match the current state
- app-jit is being tested in dart2 mode
- hot reload bots on mac have not been enabled yet

**Comment by JekCharlsonYu** [comment]
will close this and leave the other bug open to track #33291.
