### ISSUE TITLE
VM does not accept any `Invocation` as argument to `NoSuchMethodError.withInvocation`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#33124]
To reproduce, evaluate `new NoSuchMethodError.withInvocation(null, new Invocation.getter(#foo))`.
This fails a dynamic cast of `as _InvocationMirror`. It should work for all objects implementing `Invocation`.

**Comment by natebosch** [comment]
Given that the default constructor is deprecated this makes it impossible to construct a `NoSuchMethodError` without a deprecation warning as far as I can tell.
