### ISSUE TITLE
`new Path2D()` from dart:html doesn't work in dev_compiler

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33138]
With the latest sdk on chrome, the following will break:

```dart
import 'dart:html';

main() {
  var path = new Path2D();
}
```

The relevant parts of the stack trace are:

```
Uncaught Error: use `new Path2D.new(...)` to create a Dart object
    at new Object (dart_sdk.js:5008)
    at new Interceptor (dart_sdk.js:7187)
    at new Path2D (dart_sdk.js:85374)
    at Function._create_1 (dart_sdk.js:85389)
    at Function.new (dart_sdk.js:85378)
    at main (entry.dart:4)
    ...
```

This looks to be caused by the `_create_1`, `_create_2`, and `_create_3` static methods in the [html_dart2js.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dart2js/html_dart2js.dart) file starting on line 31236:

```dart
  static Path2D _create_1() => JS('Path2D', 'new Path2D()');
  static Path2D _create_2(path_OR_text) =>
      JS('Path2D', 'new Path2D(#)', path_OR_text);
  static Path2D _create_3(path_OR_text) =>
      JS('Path2D', 'new Path2D(#)', path_OR_text);
```

If you pause on a breakpoint in the compiled js here and log `Path2D` you get the custom class from dart:html, not the Path2D from window. It seems that the scoping here is broken in some way, not sure if it has to do with static methods in es6 classes or what.

If you replace these calls with `window.Path2D` it fixes things, but I don't know if that is really the correct fix. Note that there are likely other rarely used classes from dart:html that are broken in the same way.

Another note here, is that if I put a breakpoint within the static `new` method (the compiled dart factory constructor) - the scope is actually correct (Path2D there is the window.Path2D). As soon as that calls through to `html$.Path2D._create_1();` though it changes to reference class.

Original issue https://github.com/dart-lang/build/issues/1451.

cc @vsmenon

**Comment by jmesserly** [comment]
yeah, Path2D should be qualified by `window`. Normally we (well, the folks that work on area-html) fix this in the JS code.

That said I do wonder if we could do something in the compiler. The class name should really be a JS.TemporaryId so it can't conflict with anything. It will still have correct name when stored on the library object, so this shouldn't change anything semantically, nor should it get renamed unless needed. I'll have to double check to make sure it doesn't break anything (like other JS builtins that make assumptions about the local class name).

**Comment by vsmenon** [comment]
@terrylucas 

I feel like we've hit this before.

**Comment by jmesserly** [comment]
fyi -- testing a fix now

**Comment by robertmuth** [comment]
Since I brought this up originally: 
I did not realize that window.Path2D was the proper way to qualify this
and do not mind the breakage at all.
It would be nice, though, if the error message would point me in the right direction rather than
at something that does not work.

**Comment by jakemac53** [comment]
> I did not realize that window.Path2D was the proper way to qualify this

To be clear you should not need to do `window.Path2D` in  your code, this is a bug on the dart:html/dev_compiler side of things.

**Comment by jmesserly** [comment]
so... I fixed this by changing how DDC does class naming. Then I found this code in the compiler and realized it's just the regexp doesn't detect numbers:
```dart
    // TODO(vsm): Constructors in dart:html and friends are trying to
    // allocate a type defined on window/self, but this often conflicts a
    // with the generated extension class in scope.  We really should
    // qualify explicitly in dart:html itself.
    var constructorPattern = new RegExp("new [A-Z][A-Za-z]+\\(");
    if (constructorPattern.matchAsPrefix(source) != null) { ... }
```
Not really sure which approach is cleaner.

**Comment by jakemac53** [comment]
hah! I don't have a strong opinion here (or enough information to know really) but the regex seems more brittle (as evidenced by this bug haha). I think a good general rule of thumb is if you can fix it without a regex you probably should do so :D.

**Comment by vsmenon** [comment]
doh!

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/55504
