### ISSUE TITLE
async library: check return type of onerror handlers lazily

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33139]
[simply filing a bug for reference and coordination purposes]

The async library has several APIs taking error callbacks which could be a binary or unary function. When we test for the arity, we are currently checking for an exact type, it so happens that some users register a callback with a dynamic return type, which doesn't match any of the expectations.

Because return-types cannot be declared on closures, users would have to awkward updates to their code to be able to meet the callback signature (e.g. moving the callback to a method, or adding an explicit cast to help type-inference). To improve the user experience, we'd like to change the internal API to not check for the return type of the function type, instead to check the return value after the callback is executed instead. This will allow users to continue to provide a callback with a dynamic return type, as long as the callback returns the correct value.

Marking as P1 as we are starting to enable strong-mode in dart2js on internal apps, and we've seen this scenario come up in our early testing.

Note: implementation is almost done in https://dart-review.googlesource.com/c/sdk/+/53208.

**Comment by sigmundch** [comment]
Funny coincidence, @efortuna just hit this while converting dart2js to run on the Dart2 vm

**Comment by dgrove** [comment]
@lrhn can you please provide an update?

**Comment by vsmenon** [comment]
Related issue #31939 - but I don't there is time to do all that for 2.0.

I'm reading @sigmundch 's suggestions as something like:

```
if (f is Object Function(Null, Null)) {
  return f(arg1, arg2 as StackTrace) as FutureOr<T>;
} else if (f is Object Function(Null)) {
  return f(arg1) as FutureOr<T>;
}
```

**Comment by vsmenon** [comment]
Got it - missed that `registerBinaryCallback` would cast the function in the old code.  The new code is looser on the return type - which matches @sigmundch 's request.

We could loosen the param types, but that would require a dynamic call (e.g., fix my example above to `return (f as Function)(arg1, arg2 as StackTrace) as FutureOr<T>`).  Not great.

**Comment by vsmenon** [comment]
@lrhn - is this ready to close?

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/53208 has landed. Can this be closed now?

**Comment by sigmundch** [comment]
Yes.
