### ISSUE TITLE
Analyzer: `mixin` and `interface` should be builtin identifiers in Dart 2

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33131]
Meta bug here: https://github.com/dart-lang/sdk/issues/33113 .

@bwilkerson @devoncarew

**Comment by bwilkerson** [comment]
The definition of what is and is not a built-in identifier is now in the front_end package, so I believe that there is no work to do on the analyzer side. Let me know if that turns out to not be true.
