### ISSUE TITLE
some probl

### ISSUE THREAD

**Issue by LingfengSun** [dart-lang/sdk#33136]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.4892.42`
- `1.24.3`
- `IU-181.4892.42, JRE 1.8.0_152-release-1136-b38x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/pp/69w8gh8d3d1fvj0nt2n809k80000gn/T/report1.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Failed to handle completion domain request: {id: 237, method: completion.getSuggestions, params: {file: /Users/sunlingfeng/IdeaProjects/quiz/lib/ui/QuestionText.dart, offset: 593}, clientRequestTime: 1526458331136}
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OpTypeAstVisitor.visitNamedExpression.<anonymous closure> (package:analysis_server/src/services/completion/dart/optype.dart:741)
#3      Object

**Comment by zoechi** [comment]
That doesn't look related to Flutter, or you have the wrong SDK path configured in the Flutter plugin

**Comment by matanlurey** [comment]
Also this is a *very* old version of the SDK @vsmenon (`1.24.3`). Nobody will be fixing this :-/
