### ISSUE TITLE
Remove analyzer sources from the shipped SDK

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#33141]
https://github.com/flutter/flutter/pull/17479 removes Flutter's dependency on shipped analyzer sources.  Assuming there are no others, we should stop shipping sources for:

* analysis_server
* analyzer
* front_end
* kernel

@DanTup: are you currently running server from a snapshot for vscode?

@devoncarew : any idea about Atom?

What about vim support, etc?

**Comment by DanTup** [comment]
> are you currently running server from a snapshot for vscode?

Yeah, we run `bin/snapshots/analysis_server.dart.snapshot` from the Dart SDK, which in the case of a flutter project is the one inside the `cache/dart-sdk` folder. Is it just the `.dart` sources being removed; the snapshot will still be there?

**Comment by DanTup** [comment]
And FWIW, Atom seems to be doing the same:

https://github.com/dart-atom/dart/search?utf8=%E2%9C%93&q=snapshot&type=

**Comment by bwilkerson** [comment]
@pq Is this still an open task?

**Comment by devoncarew** [comment]
Landed here: https://dart-review.googlesource.com/c/sdk/+/72060
