### ISSUE TITLE
html gamepad bindings are not working properly

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/sdk#33148]
Dart VM version: 2.0.0-dev.55.0 (Unknown timestamp) on "linux_x64"

When one creates a gamepad object, joystick positions and button state appear to be frozen. 

The workaround is to re-instantiate the gamepad object every frame.

Below is some code demonstrating this:

https://github.com/ChronosTeam/ChronosGL/blob/aa00d2049e294b770cca025e925f380913f4b72d/example/game/game.dart#L209

**Comment by vsmenon** [comment]
@terrylucas

**Comment by robertmuth** [comment]
5 years later this seems to be still broken.

Could not get it to work with  https://pub.dev/packages/js_bindings either.

**Comment by robertmuth** [comment]
Apparently, the workaround described in the initial post is how the API is supposed to be used:

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API
