### ISSUE TITLE
dart2js: inlining difference in dart2

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33145]
This example shows `_checkLength` gets inlined in Dart1 but not in Dart2. The `_checkLength` function simply returns the parameter and has no checks, even in compliance mode.

```dart
import 'dart:typed_data';

const C = 304;

main() {
  print(new Uint8List(0));
  print(new Uint8List(C));
}
```

**Comment by vsmenon** [comment]
@rakudrama - is this something that should be fixed before dart2stable?

**Comment by rakudrama** [comment]
https://dart-review.googlesource.com/c/sdk/+/58542 fixes this instance.
