### ISSUE TITLE
missing dart bindings for html canvas functions in dev

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/sdk#33147]
Dart VM version: 2.0.0-dev.55.0 (Unknown timestamp) on "linux_x64"

it looks like the new SDK is cracking down on functions whose JS
equivalent use crazy overloading, e.g.:
https://api.dartlang.org/stable/1.24.3/dart-html/CanvasRenderingContext2D/fill.html

But what are the equivalent new functions?
The dev documentation does not seem to offer a full replacement:

https://api.dartlang.org/dev/2.0.0-dev.54.0/dart-html/CanvasRenderingContext2D-class.html

**Comment by vsmenon** [comment]
@terrylucas

**Comment by vsmenon** [comment]
Some special handling for fill here:

https://github.com/dart-lang/sdk/blob/master/tools/dom/scripts/htmlrenamer.py#L576

**Comment by terrylucas** [comment]
I'll take a look.

**Comment by terrylucas** [comment]
CL to fix this is https://dart-review.googlesource.com/c/sdk/+/59240
