### ISSUE TITLE
Unable to find modules for some sources

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#33151]
* SDK version: 2.0.0-dev.54
* Windows 10

I'm trying to build a large Angular app, with many dependencies.
While building, no errors are reported, but near the end, it complains that certain modules cannot be found.
I'm out of ideas on how to proceed next (also not sure if this an Angular or DDC issue)

Below is the full build log:

C:\dev\dart-sdk\bin\pub.bat global run webdev serve web:59522
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 34ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 4.2s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 2.2s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
[INFO] 2.0s elapsed, 51/108 actions completed.
[INFO] 8.5s elapsed, 115/134 actions completed.
[INFO] 10.7s elapsed, 246/284 actions completed.
[INFO] 11.8s elapsed, 299/442 actions completed.
[INFO] 12.9s elapsed, 425/452 actions completed.
[INFO] 14.0s elapsed, 522/580 actions completed.
[INFO] 15.1s elapsed, 539/581 actions completed.
[INFO] 16.2s elapsed, 556/588 actions completed.
[INFO] 17.2s elapsed, 564/622 actions completed.
[INFO] 18.2s elapsed, 616/640 actions completed.
[INFO] 25.7s elapsed, 624/678 actions completed.
[INFO] 26.7s elapsed, 794/802 actions completed.
[INFO] 29.3s elapsed, 798/829 actions completed.
[INFO] 30.4s elapsed, 1020/1067 actions completed.
[INFO] 32.0s elapsed, 1063/1188 actions completed.
[INFO] 33.2s elapsed, 1168/1397 actions completed.
[INFO] 34.3s elapsed, 1416/1465 actions completed.
[INFO] 35.4s elapsed, 1638/1663 actions completed.
[INFO] 37.1s elapsed, 1665/1854 actions completed.
[INFO] 38.1s elapsed, 1807/1855 actions completed.
[INFO] 39.3s elapsed, 1956/1976 actions completed.
[INFO] 43.4s elapsed, 2006/2011 actions completed.
[INFO] 44.4s elapsed, 2033/2038 actions completed.
[INFO] 46.3s elapsed, 2052/2057 actions completed.
[INFO] 47.3s elapsed, 2091/2094 actions completed.
[INFO] 48.4s elapsed, 2181/2185 actions completed.
[INFO] 49.5s elapsed, 2242/2247 actions completed.
[INFO] 50.6s elapsed, 2293/2296 actions completed.
[INFO] 51.7s elapsed, 2385/2387 actions completed.
[INFO] 52.7s elapsed, 2474/2475 actions completed.
[INFO] 53.8s elapsed, 2552/2554 actions completed.
[INFO] 54.8s elapsed, 2605/2606 actions completed.
[INFO] 55.9s elapsed, 2666/2668 actions completed.
[INFO] 57.0s elapsed, 2743/2745 actions completed.
[INFO] 58.0s elapsed, 2827/2829 actions completed.
[INFO] 59.1s elapsed, 2922/2924 actions completed.
[INFO] 1m 0s elapsed, 2973/2975 actions completed.
[INFO] 1m 1s elapsed, 3048/3050 actions completed.
[INFO] 1m 2s elapsed, 3143/3145 actions completed.
[INFO] 1m 3s elapsed, 3210/3212 actions completed.
[INFO] 1m 4s elapsed, 3315/3316 actions completed.
[INFO] 1m 5s elapsed, 3406/3408 actions completed.
[INFO] 1m 6s elapsed, 3504/3506 actions completed.
[INFO] 1m 7s elapsed, 3523/3529 actions completed.
[INFO] 1m 8s elapsed, 3559/3564 actions completed.
[INFO] 1m 9s elapsed, 3592/3598 actions completed.
[WARNING] angular on lib/src/view/edit_structure/document_editor/document_editor.css:
Errors parsing CSS:
error on line 47, column 65: expected ), but found /
  :host /deep/ .content-renderer__meta-tags-container:not(:host /deep/ .content-renderer__meta-tags-container:empty) {
                                                                ^
error on line 47, column 72: expected deep, but found .
  :host /deep/ .content-renderer__meta-tags-container:not(:host /deep/ .content-renderer__meta-tags-container:empty) {
                                                                       ^
error on line 47, column 72: expected /, but found .
  :host /deep/ .content-renderer__meta-tags-container:not(:host /deep/ .content-renderer__meta-tags-container:empty) {
                                                                       ^
error on line 47, column 116: expected {, but found )
  :host /deep/ .content-renderer__meta-tags-container:not(:host /deep/ .content-renderer__meta-tags-container:empty) {
                                                                                                                   ^
error on line 47, column 118: expected }, but found {
  :host /deep/ .content-renderer__meta-tags-container:not(:host /deep/ .content-renderer__meta-tags-container:empty) {
                                                                                                                     ^
error on line 48, column 14: parsing error expected {
    padding: 10px 20px 0 20px; }
             ^^
error on line 48, column 16: parsing error expected }
    padding: 10px 20px 0 20px; }
               ^^
error on line 48, column 19: premature end of file unknown CSS
    padding: 10px 20px 0 20px; }
                  ^^
[INFO] 1m 10s elapsed, 3630/3635 actions completed.
[INFO] 1m 11s elapsed, 3691/3692 actions completed.
[INFO] 1m 12s elapsed, 3745/3746 actions completed.
[INFO] 1m 13s elapsed, 3829/3830 actions completed.
[INFO] 1m 15s elapsed, 3843/3845 actions completed.
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
 Unable to find modules for some sources, check the following imports:

`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/paperback.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book.template.dart at 15:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/request_data_bloc.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/visible_content_bloc.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/search_bloc.template.dart at 11:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/history_bloc.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/save_bloc.template.dart at 13:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_organizer.template.dart at 11:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/editor_worker_bloc.template.dart at 13:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/create_bloc.template.dart at 15:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/key_bind_bloc.template.dart at 13:1
`import 'package:taurus_shared/taurus_shared.dart' hide User;` from libra_components|lib/src/gutter_components/comment_annotation.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/content_tag_annotation.template.dart at 12:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/footnote_annotation.template.dart at 12:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/header_annotation.template.dart at 13:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/metadata_annotation.template.dart at 14:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/infrastructure/facade_service.template.dart at 12:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref9;` from libra_components|lib/src/paperback.template.dart at 32:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref37;` from libra_components|lib/src/book.template.dart at 89:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref6;` from libra_components|lib/src/book_blocs/content/request_data_bloc.template.dart at 25:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref10;` from libra_components|lib/src/book_blocs/content/visible_content_bloc.template.dart at 34:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref6;` from libra_components|lib/src/book_blocs/content/search_bloc.template.dart at 24:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref3;` from libra_components|lib/src/book_blocs/editor/history_bloc.template.dart at 20:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref7;` from libra_components|lib/src/book_blocs/editor/save_bloc.template.dart at 27:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref2;` from libra_components|lib/src/book_organizer.template.dart at 15:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref5;` from libra_components|lib/src/book_blocs/editor/editor_worker_bloc.template.dart at 23:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref5;` from libra_components|lib/src/book_blocs/editor/create_bloc.template.dart at 25:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref5;` from libra_components|lib/src/book_blocs/editor/key_bind_bloc.template.dart at 23:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref2;` from libra_components|lib/src/gutter_components/comment_annotation.template.dart at 22:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref4;` from libra_components|lib/src/gutter_components/content_tag_annotation.template.dart at 21:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref1;` from libra_components|lib/src/gutter_components/footnote_annotation.template.dart at 15:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref4;` from libra_components|lib/src/gutter_components/header_annotation.template.dart at 21:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref2;` from libra_components|lib/src/gutter_components/metadata_annotation.template.dart at 19:1
`import 'package:taurus_shared/taurus_shared.template.dart' as _ref5;` from libra_components|lib/src/infrastructure/facade_service.template.dart at 23:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book.dart at 9:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/paperback.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/request_data_bloc.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart' hide User;` from libra_components|lib/src/gutter_components/comment_annotation.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/content_tag_annotation.dart at 6:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/header_annotation.dart at 7:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/metadata_annotation.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/gutter_components/footnote_annotation.dart at 6:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/visible_content_bloc.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/content/search_bloc.dart at 5:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_organizer.dart at 5:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/history_bloc.dart at 8:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/save_bloc.dart at 7:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/editor_worker_bloc.dart at 7:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/create_bloc.dart at 9:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/book_blocs/editor/key_bind_bloc.dart at 7:1
`import 'package:taurus_shared/taurus_shared.dart';` from libra_components|lib/src/infrastructure/facade_service.dart at 6:1

[INFO] Running build completed, took 1m 16s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 487ms

[INFO] Succeeded after 1m 16s with 3924 outputs (9818 actions)

Serving `web` on http://localhost:59522

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/build#1458
