### ISSUE TITLE
Iterable.singleWhere throws on duplicate element, even if orElse is provided.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#33163]
The documentation and implementation does not agree.

From `lib/core/iterable.dart`
``` 
  /**
   * Returns the single element that satisfies [test].
   *
   * Checks elements to see if `test(element)` returns true.
   * If exactly one element satisfies [test], that element is returned.
   * Otherwise, if there are no matching elements, or if there is more than
   * one matching element, the result of invoking the [orElse]
   * function is returned.
   * If [orElse] is omitted, it defaults to throwing a [StateError].
   */
E singleWhere(bool test(E element), {E orElse()}) {
    E result = null;
    bool foundMatching = false;
    for (E element in this) {
      if (test(element)) {
        if (foundMatching) {
          throw IterableElementError.tooMany(); /// Problem seems to be here
        }
        result = element;
        foundMatching = true;
      }
    }
    if (foundMatching) return result;
    if (orElse != null) return orElse();
    throw IterableElementError.noElement();
  }
```

* Dart SDK Version (`dart --version`)
```
../../bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.0.0-dev.54.0.flutter-46ab040e58 (Fri May 11 17:50:46 2018 +0000) on "macos_x64"
```

**Comment by davidmorgan** [comment]
@lrhn Bump--this is definitely a bug--I would expect 'orElse' to apply in all cases, as per the doc comment, and not just when there is nothing found.

**Comment by lrhn** [comment]
Good catch.
It should probably just return the `orElse()` result in that case too. It's feels a little weird to return a third value because we found two already, but returning `null` is reasonable.

**Comment by TedSander** [comment]
Just adding my 2 cents. I would find it a bit weird to call orElse for both the multiple find case, and the none found case without orElse having a way to tell me which case happened. There a definitely cases I would want a different action based on if none were found, or if more than one was found.

As it stands I probably agree with the implementation and would only use singleWhere when I expect 0 or 1 value and would want an error otherwise.

I would also expect changing the implementation would be a breaking change at this point.

**Comment by natebosch** [comment]
> I would also expect changing the implementation would be a breaking change at this point.

+1. I would not be surprised if there is code relying on this behavior.

**Comment by ride4sun** [comment]
```
void main() {
  
  try{
  var list = ['1','2','3'];
  list.singleWhere((el) => el == '4',orElse:null);
  }
  catch(e){print('oh shit that throws!');}
}
```

**Comment by lrhn** [comment]
Not planning on changing this, it's potentially breaking and not a high impact fix.

**Comment by ride4sun** [comment]
> Not planning on changing this, it's potentially breaking and not a high impact fix.

I am wondering how many people will be highly impacted by misleading behavior. 
you could always obsolete the method and introduce a new. I would like to understand that reasoning better.

**Comment by natebosch** [comment]
> you could always obsolete the method and introduce a new.

Adding a new method like this in the SDK has a high cost. Adding it on `Iterable` would be very breaking, and adding it as an extension doesn't need to be in the SDK.

We have added a `singleWhereOrNull` extension method in `package:collection`. Once that is published you should be able to use that extension combined with `??` to get what you are hoping for in the vast majority of cases. We don't have a fixed schedule for when that will be published.

**Comment by ride4sun** [comment]
any news on the eta of that collection pack. - thx

**Comment by natebosch** [comment]
> any news on the eta of that collection pack. - thx

The package won't be published for a stable SDK until null safety is out. For dev SDKs it will likely be published in the next couple weeks.
