### ISSUE TITLE
Support application snapshots in Dart 2 mode

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#33176]
It looks like the VM currently doesn't support application snapshots in Dart 2 mode. Given a file `test.dart`, when I run

```sh
$ dart --preview-dart-2 --snapshot=test.dart.snapshot --snapshot-kind=app-jit test.dart
$ dart --preview-dart-2 test.dart.snapshot
```

it prints "Missing root library" and exits with code 255. I've tested this with Dart 2.0.0-dev.55.

**Comment by a-siva** [comment]
Is this still a problem, I tried the following and it works

```
sivalinuxmach[repro]> out/ReleaseX64/dart --preview-dart-2 --snapshot=/tmp/hello --snapshot-kind=app-jit /tmp/hello.dart
Hello World

sivalinuxmach[repro]>out/ReleaseX64/dart --preview-dart-2 /tmp/hello
Hello World
```
