### ISSUE TITLE
loading binary data with HttpRequest is harder than it should be

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/sdk#33174]
Dart VM version: 2.0.0-dev.55.0 (Unknown timestamp) on "linux_x64"

Not sure if this merely a documentation issue, a NYI or a bug.

Loading binary data with HttpRequest is harder than it should be.
The binary data should end up as  a List<int> where each integer is in [0, 255]

Options tried:

* HttpRequest.request with responseType "blob"
   For the resulting Blob it is unclear how to get to a List<int> 

* HttpRequest.request with responseType  "arraybuffer" 
   The resulting object is not a documented type

* HttpRequest.request with mimeType   'text\/plain; charset=x-user-defined
  This results in a String but what is the best way to get this into a  List<int> 
  Note: data.codeUnits does not seem to satisfy the [0, 255] condition

I feel the best solution would be if the second approach resulted in a  uint8array

**Comment by a-siva** [comment]
Not sure I understand the issue, can you post some sample code here to make it more clear.

**Comment by robertmuth** [comment]
Below is what I currently do to load a url with arbitrary binary data.
I am looking for something more robust.

```
 List<int> Unpack(String inp) {
   List<int> data = inp.runes.toList();
   for (int i = 0; i < data.length; i++) {
     if (data[i] > 255) {
       data[i] = data[i] & 0xff;     // <<<<< fragile hack
     }
   }
   return data;
 }

String mt = 'text/plain; charset=x-user-defined';

 Future<List<int>> LoadBinaryData(String url) async {
   Completer<List<int>> c = new Completer();
   HttpRequest.request(url, mimeType: mt).then((HttpRequest contents) {
     c.complete(Unpack(contents.response));
   });
   return c.future;
 }

````

**Comment by vsmenon** [comment]
@robertmuth is this client code or server code?  If "arraybuffer", what is the type of `contents.response`?

**Comment by robertmuth** [comment]
This is client code (running in the browser).
I just retried this and now  "arraybuffer" now returns a ByteBuffer which is much more useful.
I'll do some more experiments and will close the bug if everything works as expected.
