### ISSUE TITLE
native js object wrapping issue in html speech synthesis API

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/sdk#33178]
Dart VM version: 2.0.0-dev.55.0 (Unknown timestamp) on "linux_x64"

The code below fails at runtime with 
_js_helper.TypeErrorImpl.new {message: "Type 'NativeJavaScriptObject' is not a subtype of expected type 'SpeechSynthesisVoice'." ...
=====================================================
Note that the event handler prints this for the voice in question

Google US English en-US [object SpeechSynthesisVoice] NativeJavaScriptObject
=====================================================

Future<Map<String, dynamic>> GetVoices() async {
  Completer<Map<String, dynamic>> c = new Completer();

  window.speechSynthesis.on["voiceschanged"].take (1).listen((ev) {
    Map<String, dynamic> voices = {};
    for (dynamic v in window.speechSynthesis.getVoices()) {
      print("${v.name} ${v.lang} ${v} ${v.runtimeType}");   // print output see above
      voices[v.lang] = v;
    }
    c.complete(voices);
  });
  return c.future;
}

var promiseVoices = GetVoices();
Map<String, dynamic> voices = await promiseVoices;

var u = new SpeechSynthesisUtterance();
u.text = "hello workd";
u.voice = voices["en-US"];    // This causes the problem
window.speechSynthesis.speak(u);

**Comment by terrylucas** [comment]
https://dart-review.googlesource.com/c/sdk/+/59240 to fix DDC.

**Comment by robertmuth** [comment]
Sadly, this is broken as of  2.3.2 ddc. 
dart2js appears to be working.
