### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#33186]
[report2.txt](https://github.com/dart-lang/sdk/files/2022797/report2.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-181.4892.44`
- `2.0.0-dev.55.0`
- `WS-181.4892.44, JRE 1.8.0_152-release-1136-b38x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440, 2560x1440`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 2.0.0-dev.55.0, server version 1.20.2, error: Captured exception
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:448)
#2      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:820)
#3      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:242)
#4      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#5      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218)
#6      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:883)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1883)
#10     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
```
Dart analysis server, SDK version 2.0.0-dev.55.0, server version 1.20.2, error: Captured exception
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:448)
#2      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:820)
#3      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:242)
#4      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#5      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218)
#6      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:883)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1883)
#10     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#13     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:435)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:475)
#18     Driver.start (package:analysis_server/src/server/driver.dart:434)
#19     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
1526911076077 <= {"event":"server.connected","params":{"version":"1.20.2","pid":14604,"sessionId":""}}
1526911076102 <= {"id":"0","result":{"version":"1.20.2"}}
1526911076102 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1526911075544}
1526911076102 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1526911076102 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["C:\\acr\\odw\\sdk\\core"],"excluded":["C:\\acr\\odw\\sdk\\core\\.idea","C:\\acr\\odw\\sdk\\core\\.dart_tool","C:\
1526911076102 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\ba
1526911076102 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","C:\\acr\\odw\\sdk\\core\\
1526911076102 => {"id":"6","method":"analysis.updateContent","params":{"files":{"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart":{"type":"add","content":"//  Copyright (c) 2016, 2
1526911076102 => {"id":"7","method":"edit.getAssists","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","offset":1480,"length":0},"clientRequestTime":1526911075554
1526911076102 => {"id":"8","method":"analysis.updateContent","params":{"files":{"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart":{"type":"add","content":"//  Copyright (c) 2016, 2
1526911076102 => {"id":"9","method":"edit.getAssists","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","offset":1479,"length":0},"clientRequestTime":1526911075832
1526911076107 <= {"id":"1"}
1526911076112 <= {"id":"2"}
1526911076142 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1526911076147 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1526911076357 <= {"event":"analysis.errors","params":{"file":"C:\\acr\\odw\\sdk\\core\\analysis_options.yaml","errors":[]}}
1526911076367 <= {"event":"analysis.errors","params":{"file":"C:\\acr\\odw\\sdk\\core\\pubspec.yaml","errors":[]}}
1526911076628 <= {"id":"3"}
1526911076633 <= {"id":"4"}
1526911076638 <= {"id":"5"}
1526911076648 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1526911078134 <= {"event":"analysis.errors","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":
1526911078169 <= {"event":"analysis.highlights","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","regions":[{"type":"DIRECTIVE","offset":355,"length":25},{"type":
1526911078209 <= {"event":"analysis.navigation","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","regions":[{"offset":362,"length":17,"targets":[0]},{"offset":391
1526911078214 <= {"event":"analysis.closingLabels","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","labels":[]}}
1526911078229 <= {"event":"analysis.outline","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","na
1526911078239 <= {"event":"analysis.overrides","params":{"file":"C:\\acr\\odw\\sdk\\core\\lib\\src\\element\\bytes\\bytes_mixin.dart","overrides":[{"offset":1250,"length":2,"superclassMember":{"elemen
1526911078249 <= {"id":"6","result":{}}
1526911078259 <= {"id":"8","result":{}}
1526911078389 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'lineStarts' was called on null.\nReceiver: null\nTried ca
```

[report2.txt](https://github.com/dart-lang/sdk/files/2022801/report2.txt)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Looks the same as https://github.com/dart-lang/sdk/issues/33193
