### ISSUE TITLE
Analysis server shouldn't create edits for source files outside analysis roots during renames/refactors

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33181]
Moving from https://github.com/Dart-Code/Dart-Code/issues/915

If a user invokes rename on something that's in an external package (for example, a named argument to a flutter Widget constructor), the server generates edits for package files.

I think any files outside the analysis roots (or something similar) should be treated as read-only.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by DanTup** [comment]
I seem to have inconsistent behaviour here - sometimes I get "x is in a pub package and cannot be renamed" and sometimes it seems (like Flutter packages) seem to be allowed through.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/56039
