### ISSUE TITLE
Make CFE/Kernel run on Dart 2

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#33180]
A tracking issue for this task.

**Comment by kmillikin** [comment]
Work has started on this.  Estimated 100% done at this point but triggers some bugs in testing that need to be fixed before it's usable.

**Comment by dgrove** [comment]
https://github.com/dart-lang/sdk/issues/31623 is a dup of this.

**Comment by kmillikin** [comment]
Fixed in 2d46ebd6a5c5d826ccaa6a34b00ce8564bedeaa5.
