### ISSUE TITLE
MutationObserver constructor fails

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#33188]
* SDK 2.0.0-dev.55
* Windows 10

I'm trying to use a ```MutationObserver``` from ```dart:html```.

The ctr takes a handler with typedef ```MutationCallback```, this is:
```
typedef void MutationCallback(
    List<MutationRecord> mutations, MutationObserver observer);
```

Now when I declare my handler as following:
```
void onMutation(
              List<MutationRecord> mutations, MutationObserver observer) {
            final MutationRecord match =
                mutations.firstWhere(matcher, orElse: () => null);

            if (match != null) controller.add(true);
          }
```

When I run my app, I get a RTE as following:
```
EXCEPTION: Type 'List<dynamic>' should be 'List<MutationRecord>' to implement expected type 'List<MutationRecord>'
```

The stack trace points to the ```MutationObserver``` constructor.

**Comment by denkuy** [comment]
same in 2.0.0-dev.68.0

**Comment by natebosch** [comment]
`MutationCallback` is currently typed to take a `List<dynamic>`.
https://api.dartlang.org/stable/2.2.0/dart-html/MutationCallback.html
