### ISSUE TITLE
Migrate pub to fully Dart 2

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33187]
- [x] Add support for `DART_VM_OPTIONS=--no-preview-dart-2` and flip the default to Dart 2
- [ ] (Eventually) Drop the Dart 1 snapshot and the special handling in the shell and batch scripts

**Comment by natebosch** [comment]
We want to flip the default in our shell script wrappers in the same release as the VM defaults to Dart 2 by default.

https://github.com/dart-lang/sdk/issues/32886

We also need VM support for `--no-preview-dart-2` to give an escape hatch. If we aren't getting support for `--no-preview-dart-2` we may as well skip straight to  dropping the Dart 1 snapshot - again in the same release as the VM changes to Dart 2 mode.

**Comment by natebosch** [comment]
https://dart-review.googlesource.com/c/sdk/+/56641

Should be good to go assuming we can get support for `--no-preview-dart-2` and this can go out in the same release as when the VM flips to Dart 2 by default.

**Comment by mraleph** [comment]
https://dart-review.googlesource.com/c/sdk/+/53381/3/runtime/bin/main_options.cc has all the necessary code for `--no-preview-dart-2`. 

I thought that got landed as a part of some other CL, but apparently not.

**Comment by natebosch** [comment]
@mraleph - were you able to land a change with support for that flag?

**Comment by a-siva** [comment]
Will add the --no-preview-dart-2 flag from the CL above when we flip the VM to Dart 2 by default.

**Comment by dgrove** [comment]
It looks like this is no longer a blocker for Dart2Stable - would you agree, @natebosch ?

**Comment by dgrove** [comment]
Moving the remainder of this (removing the Dart 1 snapshot) to Dart 2.1

**Comment by natebosch** [comment]
https://github.com/dart-lang/pub/pull/1933 drops support for `pub run` in Dart 1 mode. We'll also need to update the pub scripts in the SDK when we roll that in.
