### ISSUE TITLE
Analysis server completions differ in comments depending on whether there's any non-comment content

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33183]
If you create two two files, one that has only comments and one that also has content, like this:

test1:
```dart
// this is a test.
```

test2:
```dart
// this is a test.
class A{}
```

If you invoke completion where the fullstop is in the comment, the first one gives you a list of items, whereas the second one returns no items. I think the second one is correct (there shouldn't be completion for comments unless inside brackets?) but I think they should at least be consistent.

**Comment by bwilkerson** [comment]
It's also possible that it's because we're performing completion at the end of the file.

**Comment by timsneath** [comment]
Nice theory, @bwilkerson :) but I don't actually think it's that. My repro:

1. Open an existing Dart project in VS Code with DartCode extension
2. Add a new file
3. Name it `test.dart`
4. Type `// test.dart` in the file
5. Get "bad" auto-complete during step 4
6. Move the cursor above the comment and hit Return a few times
7. Type `// test.dart` again
8. See the same bad auto-complete during step 7
6. add `class T {}` to the file
7. Now add a comment above the class, and no bad auto-complete
8. Delete `class T {}`
9. Bad auto-complete reoccurs

"Bad" autocomplete looks like this:
![image](https://user-images.githubusercontent.com/2319867/40320059-2cb1f696-5cdf-11e8-941a-6637fac6b559.png)

**Comment by bwilkerson** [comment]
@timsneath Thanks! I am able to reproduce the behavior you saw (in IntelliJ, which confirms that it's in server). But I have another test case.

1. Create a file containing
```
// test.dart
class T {}
```
2. Place the cursor after the class body, press return once or twice.
3. Type `// test.d`.

I see the same bad completion. So, it's not quite being at the end of the file, but it does appear to be related to typing after the last non-comment token in the file.

**Comment by timsneath** [comment]
Great, thanks @bwilkerson! And for the record, I see the same also in VSCode. Fingers crossed there's an easy fix!
