### ISSUE TITLE
Add DDK entry to libraries.json

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33198]
Will be needed for full support of config specific imports. https://github.com/dart-lang/sdk/issues/32960

We have tools that need to understand what the import graph looks like, and we'll need to be able to crawl imports which are platform specific. We need a stable description of what the `dart.library.*` queries will be for all the platforms we might need to build. It might be easiest to publish this as a json file or similar in the SDK itself.

@leafpetersen @sigmundch @vsmenon @jakemac53

**Comment by sigmundch** [comment]
I got some good news for you, this already exists :)

As part of adding support for patch-files and config imports in the CFE, we designed a format to specify this information. 

The CFE reads it from a json file, but to make it easier to edit, we write it in yaml and autogenerate the .json from it. 

You can find the files under [sdk/lib/libraries.yaml][1] and [sdk/lib/libraries.json][2].

[1]: https://github.com/dart-lang/sdk/blob/master/sdk/lib/libraries.yaml
[2]: https://github.com/dart-lang/sdk/blob/master/sdk/lib/libraries.json

**Comment by sigmundch** [comment]
I forgot to mention: we also have a library that parses these files here:

https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/base/libraries_specification.dart

The top comment on this file has the full details of what can be specified in the .json files.

**Comment by natebosch** [comment]
Looks like it's missing DDC, flutter (aot?), and fuschia

**Comment by sigmundch** [comment]
Flutter/fuschia need a .json file on their own repo because that's where the source of their special sdk libaries are (e.g. `dart:ui`). I'm not familiar about fushias sources, but for flutter the .json file is here: 
https://github.com/flutter/engine/blob/9e4c5d0e1f9daf0c46fdc7e5d1e81ce9c36b65c4/lib/snapshot/libraries.json

DDK should have had one entry here. I believe they don't because they haven't migrated their script to build the SDK to use the same mechanism we use for dart2js, vm, and flutter.

**Comment by natebosch** [comment]
Ok, let's leave this issue open specifically for adding the DDK entry.

**Comment by sigmundch** [comment]
sounds good - thanks

**Comment by sigmundch** [comment]
So DDK has a custom way to build the SDK, but they do use a libraries.json file. The file is currently under:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/tool/input_sdk/lib/libraries.json

We should however switch DDK to use the same compile_platform script that all other platforms use, and merge their libraries.json with the one used by all other tools.

**Comment by sigmundch** [comment]
And here is a CL to make ddc use the same libraries.json file and build its platform.dill file in the same way as dart2js and the vm: https://dart-review.googlesource.com/c/sdk/+/56297

**Comment by leafpetersen** [comment]
What's the status with this?

**Comment by vsmenon** [comment]
@leafpetersen Do we need this for Dart2Stable?  If so, do we just need the json changes in Siggi's CL?  If not, can this wait till Siggi is back?

**Comment by natebosch** [comment]
This is a blocker for config specific import support in build systems. I don't think we're necessarily considering Dart 2 stable blocked on support in the build systems.
