### ISSUE TITLE
FutureOr declarations improperly reify types with --preview-dart-2

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#33196]
When running the following code on the VM with `--preview-dart-2`:

```dart
import 'dart:async';

main() {
  var result = returnsString();
  print(result.runtimeType);
}

FutureOr<String> returnsString() async {
  throw "oh no";
}
```

it prints `Future<dynamic>`, even though `Future<dynamic>` is not a subtype of `FutureOr<String>`. This violates soundness, and can lead to very confusing type errors as the invalid runtime value is propagated through the program. If I change the type of `returnsString()` to `Future<String>`, this prints `Future<String>` as expected.

Tested against Dart 2.0.0-dev.55.

**Comment by crelier** [comment]
This is not a VM issue, but a kernel one:

With Future<String> as result type, you get this kernel file:

```
  [...]
  static method main() → dynamic {
    asy::Future<core::String> result = bug::returnsString();
    core::print(result.{core::Object::runtimeType});
  }
  static method returnsString() → asy::Future<core::String> /* originally async */ {
    final asy::Completer<core::String> :async_completer = asy::Completer::sync<core::String>();
    asy::FutureOr<core::String> :return_value;
    [...]
```
However, with FutureOr<String>, you get this:

```
  [...]
  static method main() → dynamic {
    asy::FutureOr<core::String> result = bug::returnsString();
    core::print(result.{core::Object::runtimeType});
  }
  static method returnsString() → asy::FutureOr<core::String> /* originally async */ {
    final asy::Completer<dynamic> :async_completer = asy::Completer::sync<dynamic>();
    asy::FutureOr<dynamic> :return_value;
    [...]
```
I am changing the area to kernel and reassigning to @kmillikin

**Comment by eernstg** [comment]
The following would be relevant for this issue: The dynamic type of Future/Stream/Iterable from an invocation of a function marked async/async*/sync* was previously unspecified, but [this CL](https://dart-review.googlesource.com/c/sdk/+/56487) proposes a specific choice. If that CL is landed as is then [`returnsString`](https://github.com/dart-lang/sdk/issues/33196#issue-325327876) should return an instance of type `Future<String>`.

**Comment by kmillikin** [comment]
Well pedantically, `returnsString` doesn't return and with synchronous `async` functions the call to `print` will never be reached.

**Comment by kmillikin** [comment]
OK, I'm wrong about that, the thrown value is put into a Future.
