### ISSUE TITLE
Using the wrong preposition in "let" template command crashes compiler

### ISSUE THREAD

**Issue by danielmcquillen** [dart-lang/sdk#33201]
Dart version: 2.0.0-dev.55.0 
MacOSX
Chrome

Noticed that if I mistakenly type invalid syntax like `let blah in blahs` in a template (rather then the correct `let blah of blahs`) it will crash the compiler rather than just report a syntax error.

**Comment by matanlurey** [comment]
It appears you meant to file this in `dart-lang/angular`. If that is correct, consider filing here:
https://github.com/dart-lang/angular
