### ISSUE TITLE
Performance issues with TypedData._getX/_setX operations

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33205]
These functions only have a full native implementation in runtime and inliner only supports inlining them if receiver type is known. 

The main reason for only inlining them if receiver type is known is because they are polymorphic with respect to receiver type: 

* Their implementations do bounds checking even though bounds should already be checked by callers.  The bounds checking depends on `lengthInBytes`, which makes these operations statically polymorphic - as `lengthInBytes` is not stores in `TypedData` and instead needs to be computed based on the receiver class.  
* Implementation is also polymorphic with respect to external vs non-external `TypedData`.

Inability to inline these methods is most visible in AOT code that works with typed data views:
where we end up always calling runtime:

```dart
import 'dart:typed_data';

const K = 100;
const N = 1000000;

void doIt(Uint8List list) {
  for (int i = 0; i < list.length; i++) {
    list[i] = 0;
  }
}

void main(List<String> args) {
  if (args.contains('--use-view')) {
    for (var i = 0; i < K; i++)
      doIt(new Uint8List.view(new Uint8List(N).buffer));
  } else {
    for (var i = 0; i < K; i++)
      doIt(new Uint8List(N));
  }
}
```

```shell
$ pkg/vm/tool/precompiler2 /tmp/b.dart /tmp/b.aot 
$ time pkg/vm/tool/dart_precompiled_runtime2 /tmp/b.aot --use-view
pkg/vm/tool/dart_precompiled_runtime2 /tmp/b.aot --use-view  10.63s user 0.04s system 100% cpu 10.606 total
$ time pkg/vm/tool/dart_precompiled_runtime2 /tmp/b.aot           
pkg/vm/tool/dart_precompiled_runtime2 /tmp/b.aot  0.94s user 0.06s system 105% cpu 0.955 total
```

The list of things we could improve:

- [x] These methods should not check bounds. 
- [x] We should provide graph intrinsic and an inline graph fro these methods that can handle both internal and external typed_data similar to how runtime method handles it. 

Longer term we should investigate if we could normalize representation of views in such a way that view into external typed data is not different from the view into non-external typed_data.

**Comment by aartbik** [comment]
Timings of view cases on AOT 64-bit have substantially improved. On my desktop:

user	0m0.980s
user	0m1.596s   --use-view

Still a few i's to dot before we can close this.

**Comment by mraleph** [comment]
We should check if ARM32 saw any improvement at all and if not - see what is missing to get better code (e.g. be better with choosing non-speculative path on 32-bit platforms?).

**Comment by aartbik** [comment]
The i's to dot:
  (1) intrinsify/inline set indexed for 64-bit
  (2) avoid retry-compilation for "view" on 64-bit int and f32/f64
  (3) finalize story on other platforms, 32-bit

**Comment by aartbik** [comment]
Internal benchmark shows "flat" behavior now for all typed data setters and getters on 64-bit AOT. Last item to look at is doing a bit more on 32-bit as well (also AOT vs JIT differences are tracked elsewhere).
