### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by chenyi2013** [dart-lang/sdk#33210]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1280x800  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/3f/pfqvl5hs3qs1m76vfdhm5ks40000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Exception while using a Visitor to visit a ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: Class 'DynamicTypeImpl' has no instance getter 'superclass'.
Receiver: Instance of 'DynamicTypeImpl'
Tried calling: superclass
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Visitor._getSelfAndInheritedTypes (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:132)
#2      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:153)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:477)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#6      Iterable.any (dart:core/iterable.dart:402)
#7      Visitor._hasImmutableAnnotation (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:125)
#8      Visitor._visitTypedLiteral (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:93)

**Comment by a14n** [comment]
I can't figure out how that happens.

If you look at [the code](https://github.com/dart-lang/linter/blob/8a5b8e6e0796ec2fe5fd709e45b73f0dc180e1f0/lib/src/rules/prefer_const_literals_to_create_immutables.dart#L80-L86) how could a `DynamicTypeImpl` object can be processed here as all types are `InterfaceType`. The only guess I have is that `current.superclass` lies about its return type.

WDYT?

**Comment by bwilkerson** [comment]
I suppose it's possible that we have a class whose explicit superclass could not be resolved, and that as a result analyzer is returning `dynamic` in spite of the declaration of `superclass`.

**Comment by a14n** [comment]
I can not reproduce the error with an undefined super class. I will tentatively add a `is` check.
