### ISSUE TITLE
Inconsistencies on when universal function is torn off

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#33211]
The following code is behaving differently on different platforms:

```
typedef T Foo<T>(T x);

T _foo<T>(T x) => x;

class Bar{
  final Foo f;
  const Bar._([this.f = _foo]);
  const Bar() : this._();
}

void main() {
  var b = new Bar();
  print(b.f.runtimeType);
}
```

On DDC and DDK, I see:
```
(dynamic) => dynamic
```

On Dart VM (--preview-dart-2):
```
<T>(T) => T
```

Older versions of the VM (2.0.0-dev.44.0) print `(dynamic) => dynamic`.

Dart2JS, otoh, gives a compile time error:
```
Error: Not a compile-time constant.
  const Bar._([this.f = _foo]);
```

**Comment by leafpetersen** [comment]
The DDC behavior is correct.  Inference should instantiate the generic function with dynamic, and the result is a valid `const` value.

**Comment by vsmenon** [comment]
@a-siva @crelier - this looks like a recent regression in the VM.  Dev 44 VM was printing the right type.

**Comment by vsmenon** [comment]
@sigmundch @leafpetersen - dart2js should support this as well - is there already a bug for that?

**Comment by crelier** [comment]
@sjindel-google - type inference is done on the kernel side and this also involves partially instantiated functions. Could it be that runtimeType does not properly handles partially instantiated functions?

**Comment by sjindel-google** [comment]
@crelier: It's possible -- it may also be related to the fact that the field initializer is being evaluated by the constant evaluator version of partial instantiation, not the regular (runtime) version.

**Comment by sjindel-google** [comment]
I can handle the VM part of this.

**Comment by rakudrama** [comment]
dart2js now prints `(dynamic) => dynamic`
