### ISSUE TITLE
Disallow including the same part in multiple libraries in the same program

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#33225]
Motivated by the discussion in https://github.com/dart-lang/sdk/issues/32999 we want to make it a compile-time error if a file is used as a part in more than one library in the same program.

The implementation of the check for this in Fasta is covered by https://github.com/dart-lang/sdk/issues/32999 - this issue covers the specification change.

**Comment by dgrove** [comment]
Tentatively assigning to @eernstg

**Comment by eernstg** [comment]
[Here](https://dart-review.googlesource.com/c/sdk/+/60660)'s a CL for that.

**Comment by eernstg** [comment]
The language team accepted [said CL](https://dart-review.googlesource.com/c/sdk/+/60660) and it has now been landed (as of d7e5332057f012adcd1d57956249582516a07337)
