### ISSUE TITLE
Function.toString on partially instantiated generic functions is a bit confusing

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33230]
On the VM, the program below prints out:

```
Closure: <T>(T) => void from Function 'f': static.
(int) => void
```

It's somewhat confusing that printing the function shows the type of the original un-instantiated function, instead of the type of the instantiated function.  

```dart
void f<T>(T x) {}
void main() {
  void Function(int) g = f;
  print(g);
  print(g.runtimeType);
}
```

**Comment by leafpetersen** [comment]
cc @terrylucas

**Comment by ZichangG** [comment]
Just double checked VM can now print right info:
`Closure: (int) => void from Function 'f': static.`
will close this bug.
