### ISSUE TITLE
typedef function and generic methods print same output

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#33234]
getEntriesToBeTrimmed prints:

Closure: <K, V>(List<CacheEntry<K, V>>, int) => Iterable<CacheEntry<K, V>> from Function 'lruBasedTrimFn': static.

lruBasedTrimFn prints:

Closure: <K, V>(List<CacheEntry<K, V>>, int) => Iterable<CacheEntry<K, V>> from Function 'lruBasedTrimFn': static.

However, getEntriesToBeTrimmed is declared as (function typedef):

typedef Iterable<CacheEntry<K, V>> CacheEvictionFunction<K, V>(
    List<CacheEntry<K, V>> entries, int entriesToBeTrimmed);
final CacheEvictionFunction getEntriesToBeTrimmed;

and lruBasedTrimFn is declared as (generic method):

Iterable<CacheEntry<K, V>> lruBasedTrimFn<K, V>(
    List<CacheEntry<K, V>> entries, int entriesToBeTrimmed) {
  entries.sort((x, y) =>
      x.metaInfo._lastAccessTime.compareTo(y.metaInfo._lastAccessTime));
  return entries.take(entriesToBeTrimmed);
}

Identity comparison always failed because of the type difference.  Leaf noticed the difference so changing the typedef to a generic method fixed the problem e.g.,

typedef CacheEvictionFunction = Iterable<CacheEntry<K, V>> Function<K, V>(
    List<CacheEntry<K, V>> entries, int entriesToBeTrimmed);

Question should the output of a typedef function appear different from a generic method?

**Comment by eernstg** [comment]
> Question should the output of a typedef function appear different from a generic method?

It sounds like you are talking about the result returned from `o.toString()` where `o` is a function object? (.. also known as a closure or a first class function, which could be obtained as a tear-off or from evaluation of a function literal, etc.).

If that is correct, the language specification does not specify anything, the behavior of `toString` is implementation dependent on any instance of a built-in type, including function objects. (Of course, if we declare a concrete `toString()` method then it should behave as implemented, but built-in types are not guaranteed to have any source code, and even if they do have source code it's not specified by the language as such).

**Comment by leafpetersen** [comment]
@terrylucas Sorry, I should have mentioned you on this bug that I filed yesterday: https://github.com/dart-lang/sdk/issues/33230 .  I think that's the issue you are referring to here.  Feel free to re-open if there's an additional problem not capture in the above.

**Comment by terrylucas** [comment]
No problem just glad its being tracked plus your bug description is much
more succinct.

Thanks.
