### ISSUE TITLE
mixin on a ClassMirror of a class which is the result of a mixin application of the form S with M doesn't work

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33240]
The ClassMirror of a class which is the result of mixing application of the form S with M returns a class mirror of the reflectee and not the mixin.

The code below - 
```
import 'dart:mirrors';
class Super {}
class Mixin {}
class Mixin2 {}
class Mixin3 {}
class MixinApplication = Super with Mixin;
class Class extends Super with Mixin {}
class MultipleMixins extends Super with Mixin, Mixin2, Mixin3 {}
main() {
  print(reflectClass(MixinApplication).mixin);
}
```

prints
"ClassMirror on 'Mixin'" when run with Dart 1 and
"ClassMirror on 'MixinApplication'" with Dart 2.

Cause - The mixin_ field in the RawClass object in the VM is not being correctly populated,
The kernel file does not have this information to be able to populate this field correctly when loading the kernel file in the VM.

**Comment by kmillikin** [comment]
Just a quick comment because it's late.

That was exactly the intent of isSyntheticMixinApplication (https://codereview.chromium.org/2982373002) but it turns out that the implementation was incomplete.  The flag was not documented in binary.md and was not set in all cases.

For classes marked as synthetic mixins, you should be able to rely on the superclass being the superclass and the mixed-in class being the only implemented interface.

Is there any reason that the VM needs to distinguish between "synthetic mixins" and "transformed mixins"?  If not, I think a change like this should be sufficient on the Kernel side:
```
diff --git a/pkg/kernel/binary.md b/pkg/kernel/binary.md
index 13b28bf961..b3b35e54e4 100644
--- a/pkg/kernel/binary.md
+++ b/pkg/kernel/binary.md
@@ -286,7 +286,8 @@ type Class extends Node {
   UriReference fileUri;
   FileOffset fileOffset;
   FileOffset fileEndOffset;
-  Byte flags (isAbstract, isEnum, xx); // Where xx is index into ClassLevel
+  Byte flags (isAbstract, isEnum, isSyntheticMixinApplication,
+              xx); // Where xx is index into ClassLevel
   StringReference name;
   List<Expression> annotations;
   List<TypeParameter> typeParameters;
diff --git a/pkg/kernel/lib/transformations/mixin_full_resolution.dart b/pkg/kernel/lib/transformations/mixin_full_resolution.dart
index a2f3926209..1b01660a1e 100644
--- a/pkg/kernel/lib/transformations/mixin_full_resolution.dart
+++ b/pkg/kernel/lib/transformations/mixin_full_resolution.dart
@@ -237,6 +237,7 @@ class MixinFullResolution {
 
     // This class is now a normal class.
     class_.mixedInType = null;
+    class_.isSyntheticMixinImplementation = true;
   }
 
   Constructor buildForwardingConstructor(
```
(We should probably consider updating the text format but that requires rebasing tests.)

**Comment by alexmarkov** [comment]
Thank you for quick feedback!

We need a flag which covers mixin applications which were transformed to normal classes, including anonymous mixin applications and named mixin applications.

Synthetic mixin flag was not set for named mixin applications (mixin aliases):

https://github.com/dart-lang/sdk/blob/57d256377c7ec99ada943cd2c8e5855557ea2405/pkg/front_end/lib/src/fasta/kernel/kernel_library_builder.dart#L452-L453

I was afraid to change the semantics of the isSyntheticMixinImplementation flag as other backends might not expect that:

https://github.com/dart-lang/sdk/blob/57d256377c7ec99ada943cd2c8e5855557ea2405/pkg/compiler/lib/src/kernel/env.dart#L300

Do you think it's a good idea to set 'isSyntheticMixinImplementation' for named mixin applications even though they are present in sources and not really _synthetic_?

AFAICT, currently VM doesn't use synthetic mixin application flag, but it could be need in future. For example, dart:mirrors implementation distinguishes between named and anonymous mixin applications for Dart 1 mixins, and eventually we might need this for desugared Dart 2 mixins as well.

Also, named mixin applications may have implemented interfaces, so mixed-in type is not the only type in their lists of interfaces.

Please advise how to proceed.

**Comment by kmillikin** [comment]
The VM is the only backend that uses the mixin elimination transformation. So the question is: does the VM need to distinguish between classes that were originally named or anonymous mixin applications.  If not, we don't need a separate flag.

Dart2js only sees named (never anonymous) mixin applications.  If it sees the flag on a named mixin application it knows that it was originally anonymous.

The VM only sees normal classes (never mixin applications).  If it sees the flag on a normal class it knows it was originally a mixin application.

Is that sufficient?  (The name is not great, but I can't think of anything that's much better so I'm inclined to just leave it for now.)

You're right about named mixing being able to implement interfaces.  That means you can rely on there being at least one implementedType and implementedTypes.last is the original mixed-in type.

**Comment by lrhn** [comment]
There should be no semantic difference between an unnamed mixin application and an abstract "named" mixin application (class declaration) with a fresh private name and no annotations. The only difference is in the *source*, not the semantics. If mirrors intend to reflect source (whether there is a declaration in the source code or not), then it needs to be able to distinguish the two cases, but I wouldn't require that of a *run-time* reflection system.

That is:
```dart
class C extends S with M implements I { ... }
```
should be equivalent *in every way* to:
```dart
abstract class _$SwithM = S with M;
class C extends _$SwithM implements I { }  // Only use of _$SwithM
```

So, I'm arguing that the mirror system should not propose to be a source reflection system, and just do run-time reflection. At runtime, you cannot tell whether a mixin application was abstract or it just had a curious private name. Making that distinction would make the transformation invalid (or more cumbersome), which we do not want. Performing the transformation, so all classes have exactly one superclass and one mixin, is intended to be a valid implementation approach.
