### ISSUE TITLE
SDK 1.24.3, Windows/Linux: analysis server reports false errors

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#33254]
Originally filed as https://youtrack.jetbrains.com/issue/WEB-32864. Reproducible with Dart SDK 1.24.3, on Windows and Linux. 
- Open attached project in WebStorm or IntelliJ IDEA
- `pub get`
- Restart Dart Analysis Server (or close/open the project)

Analysis Server reports unresolved imports although they are correct. 
Also attaching Analysis Server instrumentation log. Note that first it reports correct (empty) error set and correct navigation info. But soon after doing it server reports false errors and limited (incorrect) navigation info.
[sletmig.zip](https://github.com/dart-lang/sdk/files/2044683/sletmig.zip)
[das_log_.txt](https://github.com/dart-lang/sdk/files/2044685/das_log_.txt)

**Comment by srawlins** [comment]
Closing as stale
