### ISSUE TITLE
[VM] _JsonUtf8Parser fails on UTF-8 with BOM

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#33251]
Dart SDK 2.0.0-dev.58.0

```dart
import 'dart:convert';

void main() {
  final data = [0xEF, 0xBB, 0xBF, 0x7B, 0x7D]; // BOM { }

  print(json.decode(utf8.decode(data))); // prints "{ }"

  print(utf8.decoder.fuse(json.decoder).convert(data)); // fails in VM
}
```
The code above runs fine when compiled to JS but fails in Dart VM:
```
Unhandled exception:
FormatException: Unexpected character (at offset 0)
#0      _ChunkedJsonParser.fail (dart:convert-patch/dart:convert/convert_patch.dart:1362)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/dart:convert/convert_patch.dart:1258)
#2      _ChunkedJsonParser.parse (dart:convert-patch/dart:convert/convert_patch.dart:926)
#3      _JsonUtf8Decoder.convert (dart:convert-patch/dart:convert/convert_patch.dart:65)
#4      main
```

**Comment by lrhn** [comment]
That should probably be accepted. 
While a BOM is not recommended for UTF-8 encoding, it does happen.

**Comment by lexaknyazev** [comment]
I'm more concerned that there's a difference between Dart VM and compiled JS behavior. It complicates writing portable code.

Normative docs on this matter are kinda mixed.

From [RFC-7159 (JSON), section 8.1](https://tools.ietf.org/html/rfc7159#section-8.1)
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.  In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

But the ES 5.1/6.0 (ECMA-262) definitions of JSON white-space don't include BOM, so `JSON.parse` shouldn't accept it. But since the code above works, I suspect that JS runtime removes BOM from the string beforehand.

**Comment by lexaknyazev** [comment]
@lrhn Is there any chance that someone from Dart team will be able to fix this soon? 
If not, I could prepare a CL myself because it's apparently a blocking issue for me (so instead of putting the workaround into my app it could be implemented in the SDK).

**Comment by lrhn** [comment]
I'll look into it today. If it turns out to be easy, I'll fix it, otherwise it'll have to wait until we fine some idle resource to handle it.
