### ISSUE TITLE
Path variable

### ISSUE THREAD

**Issue by BaileyJM02** [dart-lang/sdk#33256]
* Dart VM version: 2.0.0-dev.58.0 (Unknown timestamp) on "linux_x64"
* Linux Ubuntu 18, but probably all OS
----
When using commands such as `pub global activate [package]` I was given the following error:
```
Warning: Pub installs executables into ~/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"~/.pub-cache/bin"
```
However, with hours of dispear and annoyance that the *fix* provided didn't work, I have finally found a solution and feel, to save other peoples time, I will ask you to fix it. 

Instead of this:
```
export PATH="$PATH":"~/.pub-cache/bin"
```
It should be 
```
export PATH="$PATH:$HOME/.pub-cache/bin"
```

**Comment by natebosch** [comment]
The details of the expansion do depend on your shell and where you are adding the export (could differ between `.profile` and `.bash_profile` for instance).

I do think that `"$HOME"` is likely to work with more consistency than `"~"`.
