### ISSUE TITLE
Add support for "naked" instructions: global object pool, pc-relative static calls, faster indirect calls, potential code sharing

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33274]
After we no longer execute any code during AOT compilation (see https://github.com/dart-lang/sdk/issues/33185), we can start making "naked" instructions, i.e.:

  * use global object pool
  * use pc-relative static calls
  * faster instance calls
  * share more common code

**Comment by a-siva** [comment]
Can you elaborate on what is "naked" instructions ?

**Comment by rmacnak-google** [comment]
Without an object header, not in heap page, etc.

Both the within snapshot duplication and and cross snapshot sharing are likely to make pc-relative calls tricky.

**Comment by mkustermann** [comment]
Landed 8c30475728338cc28e1429c11a035efd76b1aca7 for this issue.

**Comment by mkustermann** [comment]
Landed 33632ade58748cffd788c3110c3cc8aa9286f0c1 for this issue.

**Comment by mraleph** [comment]
This work has been completed. \o/
