### ISSUE TITLE
Analyzer Error with empty feedback

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33278]
In the IntelliJ event log:

```
10:45 AM Dart Analyzer Error
	 Encountered a Dart Analysis Server error.
	 Open issue submission form?
```

Clicking the _Open issue submission form?_ link brought me here, but the populated feedback is empty except for the following line:

> Analyzer Feedback from IntelliJ

**Comment by zoechi** [comment]
Can you reproduce the problem? 
I run into an issue several times where the content of the error report was not added to the issue body, but to the URL in the browser URL bar. #32496

**Comment by leonsenft** [comment]
I haven't been using IntelliJ consistently recently, but if I see it happen again I'll check to see if this is a duplicate of https://github.com/dart-lang/sdk/issues/32496. I suspect it is.

**Comment by natebosch** [comment]
Closing in favor of #32496
