### ISSUE TITLE
when creating a snapshot file, also generate a snapshot_name.d dependencies file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33276]
When we create a snapshot file (say `foo.dart.snapshot`), we should also create a dependencies file listing all the Dart files that were used to create that snapshot (`foo.dart.snapshot.d`). This format would be the same as a .d make dependency file, one source file per line. Having this file would make it possible to write simple tools to re-snapshot an application if any of the input source files change.

@a-siva @rmacnak-google @vsmenon

**Comment by rmacnak-google** [comment]
This already exists.
 
```
dart --snapshot=hello.dart.snapshot --snapshot-depfile=hello.dart.snapshot.d ~/hello.dart
```
