### ISSUE TITLE
dart2js should issue an error if an integer literal cannot be represented exactly as a double

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33286]
See https://github.com/dart-lang/sdk/issues/33282 for context.

cc @efortuna @rakudrama

**Comment by efortuna** [comment]
I believe previously Stephen and I had talked about making this just a warning. Do we indeed want to make this an error?

**Comment by leafpetersen** [comment]
Does seem reasonable.  @lrhn any objection to keeping this a warning?

**Comment by efortuna** [comment]
I talked with Stephen about this again, and he's recommending staying with error. So we'll do that.

**Comment by lrhn** [comment]
I think the back-end should be allowed to do whatever it thinks best, but my personal preference is to make it an error. An integer literal is a sign of intent to use that exact value, so if the program doesn't actually use that value, it's very likely to be an error.

(I'm also interesting in whether it agrees with `int.parse` or not, but our JS `int.parse` is so amazingly slow that it probably doesn't matter what we decide there).

**Comment by sigmundch** [comment]
all work is now being done in the CFE, @rakudrama will be adding additional dart2js tests

**Comment by vsmenon** [comment]
@rakudrama - is this covered by #33351 or is there any additional work here?

**Comment by rakudrama** [comment]
Yes.
