### ISSUE TITLE
ddc should issue an error if an integer literal cannot be exactly represented as a double

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33287]
See https://github.com/dart-lang/sdk/issues/33282 for context.

**Comment by vsmenon** [comment]
This is now covered / fixed in #33351 - @jmesserly can you verify?

**Comment by jmesserly** [comment]
I'm going to reopen this one to track DDC status.

**Comment by jmesserly** [comment]
blocked until I can figure out how to fix Analyzer:
```dart
  int z2 = -0x8000000000000000;
```
is rejected by Analyzer with:
```
[error] The integer literal -0x8000000000000000 can't be represented in 64 bits. (../../../scratch/test.dart, line 5, col 13)

Please fix all errors before compiling (warnings are okay).
```
But not by CFE (DDK/VM work).

**Comment by jmesserly** [comment]
WIP CL should fix Analyzer and DDC, need to verify tests behave as expected, and updated many status entries: https://dart-review.googlesource.com/c/sdk/+/63023

This brings Analyzer/DDC into alignment with CFE, using similar logic whenever possible to keep them in sync.

**Comment by dgrove** [comment]
@jmesserly is this likely to land soon?

**Comment by jmesserly** [comment]
yes I am putting finishing touches on status files now :)  I was out of office last week

**Comment by jmesserly** [comment]
the CL is out for review
