### ISSUE TITLE
Callable class tear-offs do not infer correctly

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33298]
(Potential duplicate of https://github.com/dart-lang/sdk/issues/32864, but I don't know for sure)

This seems to fail, at least in `dart --preview-dart-2`. I _think_ DDC too:

```dart
class A {
  String call(String s) => '$s$s';
}

void main() {
  A a = new A();

  // OK
  List<String> list1 = ['a', 'b', 'c'].map(a.call).toList();

  // Error, List<Object> is not a List<String>
  List<String> list2 = ['a', 'b', 'c'].map(a).toList();
}
```

/cc @leafpetersen

**Comment by lrhn** [comment]
Doesn't seem like a language issue (apart from making sure that this is specified correctly).

The expression `a` is used in a position where a function is needed, and its static type is a callable class, so it should be effectively equivalent to `a.call`.

There might be a sequencing issue, if we need to do type inference before knowing that we have to change  `a` to `a.call`, and then it's too late for the type of `a.call` to affect type inference. I think this kind of type-based rewrite should happen *during* type inference, so it happens exactly when we know the expected type for the argument expression `a`, and before we decide the static type of the expression.

**Comment by vsmenon** [comment]
@jmesserly @bwilkerson I see the same behavior with the analyzer / ddc.

**Comment by jmesserly** [comment]
Yeah, I believe there is a bug filed about this on the Analyzer side:
https://github.com/dart-lang/sdk/issues/32864#issuecomment-380911980
(call tearoffs happen after inference, similar to CFE)

**Comment by dgrove** [comment]
tentatively moved to Dart2Stable

**Comment by kmillikin** [comment]
This is partially fixed by https://github.com/dart-lang/sdk/commit/e22706793d6c97da2a892f5d621506e762728880

The case that doesn't work yet is generic methods.  So if you had:

```dart
class A {
  T call<T>(T t) => t;
}

main() {
  A a = new A();
  List<String> list = ['a', 'b', 'c'].map(a).toList();
}
```
You will get a static error and the workaround is to use `a.call` instead.
