### ISSUE TITLE
Type literals should support generics

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#33297]
Suppose you want a `Type` variable to contain the type of a `List<int>`.

It should be possible to do it as:

```dart
Type type = List<int>;
```

Instead you have to do things like:
```dart
Type type = (<T>() => T)<List<int>>();
```
or:
```dart
class GetType<T> { const GetType(); Type get type => T; }

Type type = const GetType<List<int>>().type;
```

**Comment by lrhn** [comment]
I agree that it would be nice. Allowing `expression '<' types '>'` as a stand-alone  expression (which this requires) would also allow us to explicitly instantiate function tear-offs (`var x = list.map<String>;`) and would be part of constructor tear-offs (`var c = List<int>.generate;`). If we have that syntax anyway, using it for type literals should also "just work".

There is a reason we don't have it already, and that is (as usual) that it's ambiguous. An expression like:
```dart
 var x = foo(a < b, c > - 2);
```
can be parsed in two ways, one where foo takes two arguments, and one where it takes one with the `a<b, c>` being a single expression.
We are already handling such ambiguity with generic method invocation, and we allow un-prefixed constructor invocation (`List<int>.generate(...)`), but in both case we have the parenthesis of the function arguments to help us decide, and we won't always have that in this more general case.

The ambiguity comes from a situation where a sequence of tokens ending in `>` can be seen both as an expression with type arguments, and as an incomplete expression ending in a "greater than", and where there is a continuation that is both a continuation of the full expression, and is a valid expression after a greater than. We want to be able to *parse* the program without having to resolve identifiers to declarations, so we can't rely on the meaning of the identifiers to pick the right disambiguation, we want to do it entirely at the grammar level.

We already had parentheses as an ambiguous continuation, but we will probably have to account for expressions like `[2]` and `-2` as well, which duplicate as index-operator and list literal, respectively subtraction and negative literal (and maybe with an intermediate `--` or `++` as well). There might be more, but those are the ones I can think of (and if we add new syntax, that's another place where we can get new ambiguities).

The current rule is to pick the type-argument interpretation only, and always, when the `>` is followed by `(`.
I don't see a good *use* for index operators or subtraction on the expressions that we'd initially allow type arguments on (they evaluate to functions or `Type` objects), but we'll have to investigate if there is any existing code that would be affected, and we should consider whether the syntax may get more uses in the future.

(So, a not-completely-trivial feature request).

**Comment by mkustermann** [comment]
The original example of
```dart
Type type = List<int>;
```
seems to actually work now.

For more complex examples, e.g. a nullable type parameter, i.e. "T?" one can use the generic class/function workaround as pointed out earlier.
Though it's probably better to use a `typedef` - as pointed out by @eernstg - which the CFE will fold away:
```dart
main() {
  print(MakeNullable<int>);
}
typedef MakeNullable<T> = T?;
```

**Comment by lrhn** [comment]
Indeed, with the "constructor tear-offs" feature bundle, we can now write `List<int>` as a type literal, and use something like
```dart
typedef TypeOf<T> = T;
```
for the remaining unexpressible types, since `TypeOf<int Function(int)?>` is also a valid expression now.

I'd say this issue has been fixed!
