### ISSUE TITLE
FunctionType.instantiate doesn't handle generic typedefs properly.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33294]
Consider the following typedef:

```dart
typedef F<T> = T Function<U>(U p);
```

If an analyzer `FunctionType` is created for `F` using the `FunctionTypeImpl.forTypedef` constructor, and then that type is instantiated using `.instantiate([objectType])`, the resulting type is `(U) -> Object`.  This is a nonsense type since it refers to the free type variable `U`.

One might argue that it doesn't really make sense to try to create `FunctionType` objects for typedefs like `F`, because `F` doesn't represent a type at all; it represents a thing that can be *instantiated* to form a type (languages like Haskell call this a "type constructor").  But the analyzer *does* create such a type when building the element model, so it seems like it should behave sensibly.  And IMHO the only sensible way for it to behave is for the result of `.instantiate([objectType])` to be `<U>(U) -> Object`.

Note: this is a bug in the analyzer API, not a bug in the analyzer's analysis of source code.  If the user actually writes `F<Object>` in their source code, the analyzer manages to instantiate it properly to `<U>(U) -> Object`.

**Comment by scheglov** [comment]
I believe this is fixed now, with strict FunctionType(s).
