### ISSUE TITLE
JS interop: allowInterop type check failure

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#33296]
See https://github.com/dart-lang/angular/issues/1359

```dart
F allowInterop<F extends Function>(F f) {
  if (JS('bool', 'typeof(#) == "function"', f)) {
    // Already supports interop, just use the existing function.
    return f;
  } else {
    return _convertDartFunctionFast(f);
  }
}
```

F is `List Function()`.
It is the returned type where the check fails (by line number).
F needs to be at the return type for type inference, so we can't widen it to `Function`.

We can make the return check go away, but the JavaScriptFunction could flow to another equivalent type check.

```dart
F allowInterop<F extends Function>(F f)
-->
Function allowInterop<F extends Function>(F f)
```

If we want to make the type check pass, we need to answer the question "What is the Dart type of a JavaScript function?". It is not clear what the answer should be. A 'safe' type for the check would be
```dart
Null Function([dynamic, dynamic, ... , dynamic])
```
for some large number of arguments, but that type mischaracterizes the return type.

Perhaps we need a special type rule for JavaScriptFunction - it 'is' any Function type with only positional arguments.

**Comment by matanlurey** [comment]
This is blocking the AngularDart beta 5 release.

**Comment by rakudrama** [comment]
Fixed via https://dart-review.googlesource.com/c/sdk/+/57720
