### ISSUE TITLE
Add quick fix for making local variable non-final

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#33290]
This currently exists for final fields (related: https://github.com/dart-lang/sdk/issues/25316), and would be nice to have for local variables as well.

This would make it a little less painful to have the [`prefer_final_locals`](http://dart-lang.github.io/linter/lints/prefer_final_locals.html) lint turned on.

Current behavior in Dart 2.0.0-dev.59.0:

<img width="323" alt="screen shot 2018-05-30 at 10 16 16 pm" src="https://user-images.githubusercontent.com/1713967/40762848-3330a27c-6457-11e8-856d-d77068c357d3.png">
<img width="370" alt="screen shot 2018-05-30 at 10 17 43 pm" src="https://user-images.githubusercontent.com/1713967/40762863-4edecf6c-6457-11e8-8b4f-7867c8c54fb6.png">

**Comment by pq** [comment]
@greglittlefield-wf: sorry for the slow reply on this.

@scheglov, @bwilkerson: I'm assuming there's no good reason not to do this one?  Seems reasonable and straight-forward?

**Comment by bwilkerson** [comment]
I see no reason not to support this, and yes, it should be fairly easy to extend the current quick fix to handle this case as well.

**Comment by scheglov** [comment]
I don't see any reason not to implement this, and it should be easy.

**Comment by greglittlefield-wf** [comment]
Awesome! Would you accept a patch for this?

**Comment by bwilkerson** [comment]
Yes, we're always happy to take contributions.

**Comment by greglittlefield-wf** [comment]
❤️
