### ISSUE TITLE
int is no longer "An arbitrarily large integer".

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/sdk#33309]
https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/int.dart
says 

"An arbitrarily large integer."

at https://github.com/dart-lang/sdk/blob/4be50d6fa1737dcb8402041ecb7334e5a34ba3a1/sdk/lib/core/int.dart#L8

That is no longer true.

**Comment by lrhn** [comment]
It's still true ... for small values of "arbitrarily".
I'll update the documentation.

**Comment by natebosch** [comment]
Documentation has been corrected
https://github.com/dart-lang/sdk/blob/c6d786a3e7be55f1468dff1d5f3b5ad6c31b8b95/sdk/lib/core/int.dart#L8-L11
