### ISSUE TITLE
Substitution of f-bounded types leads to confusing displayName

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33300]
Consider the following code:
```dart
abstract class C<T> {
  Map<S, V> f<S extends T, T extends U, V extends T>();
}
```

The type of `C.f` is `<S extends T, T extends U, V extends T>() -> Map<S, V>`, as expected.

If we now use `FunctionType.substitute2` to substitute `Object` for `T`, we obtain a type whose `displayName` property is `<S extends T extends Object,T extends Object,V extends T>() → Map<S, V>`.

This is confusing.  The displayName should just be `<S extends T,T extends Object,V extends T>() → Map<S, V>`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/118374
