### ISSUE TITLE
Substitution of function types fails to substitute return type in some conditions.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33301]
Consider the following code:
```dart
abstract class C<T> {
  Map<S, V> f<S extends T, T extends U, V extends T>();
}
```

The type of `C.f` is `<S extends T, T extends U, V extends T>() -> Map<S, V>`, as expected.

If we now use `FunctionType.substitute2` to substitute `Object` for `T`, we obtain a type whose type formals (`S`, `T`, and `V`) are not the same as the initial type.  (This is necessary because `T` has a different bound in the substituted type, and because `S` and `V` point to `T`).

However, if we look at the return type of the substituted type (`Map<S, V>`), we would expect its `S` and `V` to point to the versions of `S` and `V` in the substituted type.  But they don't--they point to the versions of `S` and `V` in the original type.

**Comment by stereotype441** [comment]
Similar behaviors apply to the parameter types, e.g. if we have:

```dart
abstract class C<T> {
  void f<S extends T, T extends U, V extends T>(S s, V v);
}
```

and we use `FunctionType.substitute2` to substitute `Object` for `T`, the parameter types `S` and `V` point to the versions of `S` and `V` in the original type.

**Comment by scheglov** [comment]
I believe this is fixed now, with strict FunctionType(s).
