### ISSUE TITLE
Dart 2 pub doesn't install

### ISSUE THREAD

**Issue by hgabe** [dart-lang/sdk#33315]
I've installed dart from the dev channel, but it doesn't install pub package manager
method used to install:
     -- apt-get 
     -- deb package

**Comment by hgabe** [comment]
never mind it does install, didn't install before

**Comment by natebosch** [comment]
What error do you get?

**Comment by zoechi** [comment]
It probably just doesn't create symlinks for any executables except `dart`.
You might need to add `dart_install_dir/bin` to `PATH`
It would also be interesting what Dart version you installed.

**Comment by hgabe** [comment]
the latest update for dart fixed the problem

**Comment by zoechi** [comment]
@hgabe could you please close the issue then?
