### ISSUE TITLE
Dart IJ plugin should be changed to support 4.x version of dart vm service api

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#33310]
We seem to unable to increment major version of vm service api (as requested on https://dart-review.googlesource.com/c/sdk/+/57520/6/runtime/observatory/tests/service/external_service_disappear_test.dart#b35) because it will break IJ Dart plugin: https://github.com/JetBrains/intellij-plugins/blob/master/Dart/thirdPartySrc/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java#L149. 

We need to fix IJ Dart plugin so it can accommodate such major version increment.

cc @rmacnak-google

**Comment by devoncarew** [comment]
@aam, thinking about this a bit more, it's difficult for clients to know if they're going to be forward compatible with a major rev of the service protocol.

Perhaps the resolution here could be that we don't plan to rev the major version now, and when we do rev., we'll coordinate with clients to:

- call out how v. n+1 is breaking from v. n
- say when the next version will be released
- clients can then update to accept either n+1 or n, release new versions
- we wait for uptake of those versions, then rev the protcol

**Comment by devoncarew** [comment]
As of https://github.com/dart-lang/sdk/commit/70eb6996419 we no longer have a hard version check in the Java clients.
