### ISSUE TITLE
Generic functions issue in VM with --preview-dart-2 option

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#33322]
Consider the following code:

```dart
typedef void T<X>();
void t<X>() {}

T f = t;

main() {
  print (t is T);
  print (f is T);
}
```
When run in VM with --preview-dart-2 option this code produces 
```
false
true
```
No issues in VM without --preview-dart-2 option it produces
```
true
true
```
Why results on  VM with --preview-dart-2 are different?

Dart VM version: 2.0.0-dev.59.0 (Unknown timestamp) on "linux_x64"

**Comment by floitschG** [comment]
`typedef void T<X>()` is equivalent to `typedef T<X> = void Function<X>()`.
As such, `T f = t` is equivalent to `T<dynamic> f = t`, which is equivalent to `void Function() f = t`. During the assignment step of `t` to `f` the generic function `t` is specialized to be a function of type `void Function<dynamic>()` and the generic type is dropped.

This explains why `t is T` and `f is T` have different results.
