### ISSUE TITLE
feature: Provide a way to define version constraints globally

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#33323]
I have ~25 Dart packages in my repo, some private some public.
Almost all of these packages are using "logging" as a dependency.
If the version for logging changes I have to touch every single project to update the version numer

This is more than annoying...

Gradle for example let me define global vars in `~/.gradel/init.gradle`. With these global vars (version numbers in this case) it's very easy to update version constraints for all my internal projects at once.

**Comment by lrhn** [comment]
Can you explain why you have to update version numbers so often that this becomes a problem?

You should be able to stay at the old major version number and your packages will still work.
If the package was updated with a new major version number, then it has probably changed in a non-backwards compatible way, and automatically updating a lot of packages to use the new version seems dangerous. You will have to run the tests of each package to ensure that they still work, and then actually updating the version number is not as big an overhead.

I can see that `logger` is at version `0.11.something`, which is effectively 11 major beta-versions. That's a lot of versions, and most packages don't do major updates that often. (Also, it's a <1.0 version, so depending on the package is known to come with a risk of instability, as you are experiencing).

In any case, this sounds like a request for the [`pub` tool](https://github.com/dart-lang/pub). Would it suffice to have a way to automatically update-and-test a dependency, say `pub try-version logger:^0.12.0` which updates the version of logger in the .packages and run the tests, and if successful, updates the `pubspec.yaml` constraint? Then you can do that for each package in your repo, and if they are all successful, you are done.

**Comment by munificent** [comment]
This issue was moved to dart-lang/pub#1946
