### ISSUE TITLE
No response from search.getElementDeclerations in dev SDKs

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33336]
@scheglov Not sure if this is a result of the recent change, but my symbol search tests are timing out against dev SDKs. Seems like I'm not getting a response to search.getElementDeclerations.

Here's a log file - the test timed out after 60 seconds. The last thing in the log is the request, with no response written. The sample application is a tiny Dart app at https://github.com/Dart-Code/Dart-Code/tree/master/test/test_projects/hello_world.

[analyzer.instrum.txt](https://github.com/dart-lang/sdk/files/2073034/analyzer.instrum.txt)

**Comment by scheglov** [comment]
I can reproduce the problem.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/58500

**Comment by DanTup** [comment]
Confirmed this fix looks good in master btw 👍
