### ISSUE TITLE
Pub get socket error trying to find package angular at https://pub.dartlang.org

### ISSUE THREAD

**Issue by Chibueze-20** [dart-lang/sdk#33356]
I'm using dart 1.24.3 and I'm trying to resolve dependencies for the first time (angular package) I was trying out the example code (tour of hero) but I can't seem to get past this error message "got socket error trying to find package angular at https://pub.dartlang.org" I'm new to dart so I don't know what really is the problem... my internet connection does not have proxy settings
Operating system : windows 10
Dart SDK: 1.24.3

**Comment by natebosch** [comment]
I think this was a transient error with the pub server. We now have more retries in the pub client as well.
