### ISSUE TITLE
Pub get socket err

### ISSUE THREAD

**Issue by Chibueze-20** [dart-lang/sdk#33354]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by matanlurey** [comment]
Hi @Chibueze-20 

Please consider re-filing the issue, with the description you skipped filled out. Otherwise this is not actionable.
