### ISSUE TITLE
CFE not properly reporting compile time error?

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#33367]
@awdavies reports having seen the following error while compiling a Fuchsia module:

```
../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc: 4147: error: unreachable code
Dumping native stack trace for thread 1431d                                                                                       
  [0x0000000000833fcf] Unknown symbol
  [0x0000000000833fcf] Unknown symbol                                                         
  [...] more stacktrace stuff
```

Resolution was:

> Alright, looks like the issue was some missing import.  Ended up having to just do things w/ a pubspec.yaml and such on the local machine

/cc @mraleph

**Comment by alexmarkov** [comment]
We're going to fix error reporting in dart_runner's compiler.dart.
/cc @rmacnak-google

**Comment by mraleph** [comment]
We have tracked it down to how Fuschia's Kernel compiler wrapper is using Compiler APIs. 

It made a reasonable expectation that `CompilerOptions.setExitCodeOnProblem = true` would make CFE set non-zero exit code if there were any compilation errors, however that option does not actually have any effect if `onProblem` handler is installed and `compileToKernel` actually installs `onProblem` handler.

**Comment by rmacnak-google** [comment]
https://fuchsia-review.googlesource.com/c/topaz/+/160870
