### ISSUE TITLE
Dart Analyzer can't seem to figure out whether a List child is const or new

### ISSUE THREAD

**Issue by maryx** [dart-lang/sdk#33369]
* Dart SDK Version: `dart --version` didn't work but `flutter --version` gives `Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b`
* Linux
----
It seems like the Dart Analyzer can't determine whether the child of a `<Widget>[]` is `new` or `const`, so we have to manually specify `new`. E.g. for this code:
```
  final rating = getRatingFromAPI();
  final numReviews = getReviewsFromAPI();
  ...
  Widget _buildRating() {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Text( // this one doesn't need a `new` for some reason
          rating.toStringAsFixed(1),
          style: _secondaryTextStyle,
        ),
        Container( // this one doesn't need a `new` either
          margin: EdgeInsets.symmetric(horizontal: 8.0),
          child: Text('hello'),
        ),
        new Text( // this one needs a new. If omitted, see error below
          '(${numReviews})',
          style: _secondaryTextStyle,
        ),
      ],
    );
  }
```
If I omit the `new` for the third child, I get `error • Prefer const literals as parameters of constructors on @immutable classes at package:... • prefer_const_literals_to_create_immutables` and a green squiggle under the word `<Widget>` in VS Code.

Is this expected?

**Comment by matanlurey** [comment]
> It seems like the Dart Analyzer can't determine whether the child of a `<Widget>[]` is `new` or `const`, so we have to manually specify `new`. E.g. for this code:

This feature was reverted. There is no such thing as "automatic const" anymore, only "optional new". Once you specify the context as `const` once, then the remaining constructor calls are implicitly const. Consider:

```dart
class Animal {
  const Animal();
}

void main() {
  // Same as "final animals = [new Animal()]"
  final animals = [Animal()];

  // Same as "const animals = const [const Animal()]"
  const animals = [Animal()]
}
```

In your case `children: ` is not a _const_ context.

-----

re: `prefer_const_literals_to_create_immutables`

You might want to also file this as `dart-lang/linter`, as it isn't part of the SDK proper:
https://github.com/dart-lang/linter/issues

**Comment by maryx** [comment]
Ah thanks, I hadn't been sure where to file this - redirecting and closing this.
