### ISSUE TITLE
DDC should warn in the console if running in an unsupported envrionment

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33366]
A lot of (primarily newer) clients try DDC for the first time, and hit obscure errors when running in non-Chrome, specifically I've seen crashes for both IE 11 and Edge (I heard that Firefox and Safari ~mostly work?).

I realize this is WAI for now, so I hope we can clarify, with something like:

```js
if (isUnsupportedEnv()) {
  console.warn(
    'Detected DartDevCompiler running in an unsupported browser or JS environment. '
    'Officially, DartDevCompiler works in the latest X versions of Chrome, and has partial '
    'support for X and Y. If you see unexpected errors after this message, you are likely '
    'using an unsupported browser. You can always use Dart2JS (some link) to test, as well.');
}
```

**Comment by jmesserly** [comment]
CC @vsmenon 

I'm not sure how to define or test for "unsupported" browsers. Old IEs from before Edge are definitely not supported, so we may be able to add a check for that. All of the standards compliant modern browsers should work, though (such as: Chrome, Firefox, Safari, Edge). If DDC is doing something non-standard that relies on Chrome, I'd like to hear about it. I think we'd consider that a bug. We're certainly limited in our testing/dev budget, so we'll need good repros to track down cross browser issues.

So yeah we can add an old-IE check, but beyond that, I'm not sure. I haven't heard about crashes on Edge. I'd like to see those bugs. It's possible they're browser bugs, but without seeing them, it's hard to say.

**Comment by matanlurey** [comment]
I think one problem we've run into already is Safari seems to consume much more memory in DDC (either due to DDC itself, or ES6, it's not totally clear). It would be good to warn users, in development mode, that we don't have full support (i.e. we aren't profiling and fixing memory issues for Safari).

/cc @natebosch

**Comment by jmesserly** [comment]
> (i.e. we aren't profiling and fixing memory issues for Safari)

Yes I recall that Safari issue, it seemed like a Safari bug. Like in general we can't warn about every bug browsers may have in their JS engines, right? That doesn't seem feasible. As ES6 gets more usage these issues will get reported & fixed. If Safari has a bug, it can be fixed. Any message we add may become obsolete and just add to confusion, or lead folks to not report bugs, which seems like a suboptimal result?

**Comment by matanlurey** [comment]
I totally get it. I just want users to know they aren't on a "golden path".

All the console.warn needs to do is link to `webdev.dartlang.org/toosl/ddc#supported-browsers`

**Comment by jmesserly** [comment]
Also I thought more about old-IE (pre-Edge): I don't think we can add a warning there, because our SDK code will fail to load with a SyntaxError. Hopefully that error will make it obvious enough that the browser is unsupported.

> I totally get it. I just want users to know they aren't on a "golden path".
> All the console.warn needs to do is link to webdev.dartlang.org/toosl/ddc#supported-browsers

I think you meant https://webdev.dartlang.org/tools/dartdevc ... quoting that page:

> The Dart development compiler (dartdevc, also known as DDC) lets you run and debug your Dart web app in any modern web browser.
