### ISSUE TITLE
Run all tests on vm-kernel-* bots

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#33374]
For some reason, certain vm-kernel-* bots (e.g. vm-kernel-linux-release-x64-be, vm-kernel-precomp-linux-debug-x64-1-8-be etc.) run only a subset of tests (language_2 corelib_2 lib_2 standalone_2):

```
python -u /b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/tools/test.py -mrelease '--arch=x64' '--progress=line' --report --time --write-debug-log --write-result-log --write-test-outcome-log --copy-coredumps -cdartk -rvm --strong language_2 corelib_2 lib_2 standalone_2
```

Other bots, such as vm-kernel-linux-release-simarm run all tests.
Due to this discrepancy in configuration of build bots, some tests are only run in simarm/simarm64 modes but not on x64.

Status files for legacy Dart 1 tests are already updated and old tests are excluded in Dart 2 configurations, so we should be able to run all tests on all bots.

/cc @athomas

**Comment by athomas** [comment]
Already tracked in #32499.

This is because they haven't been ported to Luci, yet. Note that the vm-kernel-linux-release-x64-try builder runs on the new infrastructure and doesn't have any test selectors.

**Comment by alexmarkov** [comment]
@athomas, is it hard to modify configuration of old bots? While we're waiting for migration to finish, we're missing test coverage and not detecting bugs like https://github.com/dart-lang/sdk/issues/33453.
