### ISSUE TITLE
int64 shifts should throw on out of range shifts 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33377]
@lrhn specified that for `int i` shifts `i << j` and `i >> j` should throw if `j` is outside of `[0, 63]` range.

This was not covered by the informal specification and VM does not implement this correctly.

We need to ensure that we have tests for this semantics and fix VM implementation.

/cc @leafpetersen

**Comment by lrhn** [comment]
And similarly for `>>>` when we add it to `int`.

As usual, JS compilation is not implementing `int` the same way, and they can only shift by at most 31.

**Comment by leafpetersen** [comment]
I think this actually contradicts the informal spec implicitly (see the section on shifts).  Do we really want this semantics?  It will make it non-constant width shifts quite a bit slower.

**Comment by alexmarkov** [comment]
Could you point to a particular place in the specification? Can't find this in the language spec or int.dart.

What is the reason behind this change? It looks like it limits what users could do - it might be convenient to be able to shift by 64 bits.

When would you like this change to happen? Dart2Stable, Dart2.1 or later?

This looks like a breaking change. Do we need to introduce an option to be able to switch to the old behavior while code is being migrated? Do you expect any breakages in Flutter code?

**Comment by leafpetersen** [comment]
It's not really explicit but I don't know how to read this section in a way that doesn't imply that bits are just shifted out silently:

- The `<<` operator is specified to shift "out" bits that leave the 64-bit range. Shifting might change the sign of an integer value. All bits of the operand are used as input to shifting operations. Some CPU architectures, like ia32 and x64, only use the least-significant 6 bits for the right-hand-side operand, so this requires more work from the compiler: `int x = 0x10000; printf("%d\n" 1 << x);` prints "1".

In particular, what's the point of calling out that all bits are used as input to shifting operations if the intention is not that you can shift by more than 63 bits?

**Comment by leafpetersen** [comment]
Thinking about this a bit more - none of the arithmetic operations throw on overflow.  It's quite odd then that the bitwise operations would throw.  Usually I think of bitwise operations as more low level and less checked.

**Comment by mraleph** [comment]
I am fine with shift not throwing as long as there is precise specification of how shifts behave: e.g. do we specify that `i << j` is just `(i << (j & 63))`? That probably would be the best from the performance point of view.   

Moving this to `area-language`. Marking as needing resolution before Dart 2 stable.

**Comment by vsmenon** [comment]
Is there a conclusion here?  We need to close this soon.  :-)

**Comment by vsmenon** [comment]
Do we need to change FE behavior (during constants)?

Do we need to change BE behavior?

**Comment by leafpetersen** [comment]
I believe there are no changes required.  The implementations match the specification, and there are no plans to change the specification.
