### ISSUE TITLE
Uri.queryParametersAll: JSArray is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33371]
_From @jtmcdole on June 6, 2018 19:25_

I expect this to run:

```dart
main() {
  var uri = Uri.parse('https://foo.bar.com/this/is/a/path?foo=foo1&foo=foo2&bar=baz');
  print(uri.queryParametersAll);
  print(uri.queryParameters);
}
```

Instead I get:
```shell
Uncaught exception:
TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'
```

_Copied from original issue: dart-lang/site-www#909_

---

You can try it here: https://dartpad.dartlang.org/e0fe1365f6094701c7632562a17e13b7

**Comment by chalin** [comment]
Thanks for reporting this issue @jtmcdole.

The error is only reported when `uri.queryParametersAll` is printed. It seems that there might be a Dart 2 type error in this code:
https://github.com/dart-lang/sdk/blob/8c20f26234f6a40066f7e2e802de913bc45ee7a3/sdk/lib/core/uri.dart#L1918-L1929

The call to `_splitQueryStringAll(query)` returns a `Map<dynamic, dynamic>` rather than the expected `Map<String, List<String>>`. That might causing the problem.

cc @kevmoo @kwalrath

**Comment by chalin** [comment]
Btw, DartPad is currently using Dart SDK 2.0.0-dev.59.0.

**Comment by chalin** [comment]
You can try it here: https://dartpad.dartlang.org/e0fe1365f6094701c7632562a17e13b7

**Comment by lrhn** [comment]
The bug is in `ConstantMap.from` in the dart2js runtime system. It assumes that the input map has the correct key type, which isn't guaranteed by the uses.
We already have (untriaged) status-file entries marking dart2js as crashing on `uri_test` and `uri_parameters_all_test`.

**Comment by rakudrama** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/b9381d337829ba872666f2233d27e5ce6315aa21
