### ISSUE TITLE
Add endLine/endColumn to analysis server structures (like Location/ElementDeclaration)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33378]
Some of the APIs in VS Code request line/column for both start and end positions, for example the symbol providers. When we have access to an open document, we can translate the offset/length into a line/column, however when there's no open document (for example in the workspace symbol list) we cannot. For now we've just been returning the startLine/startColumn as both the start/end positions, but that's started to show now that they're using ranges for other things, like arrange our symbols into an outline tree:

<img width="478" alt="screen shot 2018-06-07 at 10 23 08 am" src="https://user-images.githubusercontent.com/1078012/41091604-d5f0c702-6a3e-11e8-948d-2af862739b90.png">

For now, I'm going to use the open document when we have it (document symbols) but continue the old behaviour when we don't (workspace symbols), but it'd be good if we could supply accurate data in all cases (it turns out we have a lot of places returning the same start/end because of this).

**Comment by bwilkerson** [comment]
If it wouldn't take too long, could you put together a list of the structures that would need to be updated? It would be good to have a definitive list so that we don't miss any place and so that we know the scope of the work required.

**Comment by DanTup** [comment]
Don't need this anymore, as in LSP we can easily compute this on the server.
