### ISSUE TITLE
pkg:analyzer: hitting an assert when annotating Enum values

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33373]
When running my build script with `--enable-asserts`, I hit this assertion. When not running in debug mode, all is fine.

https://github.com/dart-lang/sdk/blob/b74d27d1b2ede186a3c795d7947b5a6123fe3ec0/pkg/analyzer/lib/src/generated/resolver.dart#L5433

**Comment by kevmoo** [comment]
CC @bwilkerson @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/59440
