### ISSUE TITLE
CFE does not support import from http URLs or invocation from a script URL that is a http URL

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33388]
```dart
import "http://127.0.0.1:8181/http_launch_main.dart";

main() {
}
```
executing this produces:
`http://127.0.0.1:8181/http_launch_main.dart: Error: File http://127.0.0.1:8181/http_launch_main.dart does not exist.`

Similarly using a http URL on the command line produces an error
out/ReleaseX64/dart --preview-dart-2 http://127.0.0.1:8181/http_launch_main.dart
http://127.0.0.1:8181/http_launch_main.dart: Error: File http://127.0.0.1:8181/http_launch_main.dart does not exist.

Both of these cases used to work in Dart 1

**Comment by natebosch** [comment]
Do we have plans to fix this? `package:test` relies on on running the VM this way.

**Comment by lrhn** [comment]
I believe this needs to be fixed on the VM side. In `gen_kernel.dart` and `frontend_server.dart`, the VM creates a compiler options object. It needs to overwrite the `fileSystem` option with a `FileSystem` implementation which supports HTTP.

**Comment by dgrove** [comment]
@natebosch is this required for Dart2Stable for package:test ?

**Comment by mit-mit** [comment]
Per comments above, sounds like the VM would be expected to resolve these, cc @a-siva

**Comment by natebosch** [comment]
This is also blocking for an important tool internally.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/64960 is out for review with the fix

**Comment by dgrove** [comment]
@aam ready to close?

**Comment by aam** [comment]
@dgrove wrote:
> @aam ready to close?

Yes!
