### ISSUE TITLE
The docs for either Object.HashCod or HashMap (or both?) should indicate that hashCode should not change while an object is used as a key

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33384]
Today the docs for HashMap only mention a requirement for consistency between `==` and `hashCode` and the docs for `hashCode` explicitly allow for it to change over the lifetime of an object if equality changes.

We had a user confused when `map.containsKey(map.keys.first)` could return false - we could call out the risks of mutable hashCode in the docs so we have something to point to when this comes up.

**Comment by vsmenon** [comment]
fyi - @lrhn
