### ISSUE TITLE
Analyzer crashes and cannot find files with .. in path

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#33381]
* Dart SDK Version (`dart --version`): 2.0.0-dev.60.0 and earlier.  On Linux.

The dartanalyzer command fails when given a relative path that navigates above the working directory.
Example:
~/ssd/sdk/tools/gardening/bin$ dartanalyzer bot.dart
Analyzing bot.dart...
No issues found!
~/ssd/sdk/tools/gardening/bin$ dartanalyzer ../bin/bot.dart
Analyzing ../bin/bot.dart...
No dart files found at: ../bin/bot.dart

A .. inside a relative or absolute path works in an installed -dev.36, as long as it doesn't go above the current directory:

~/ssd/sdk/tools/gardening/bin$ dartanalyzer foo/../bot.dart
Analyzing bot.dart...
No issues found!

But the same command crashes the analyzer in version -dev.60

~/ssd/sdk/tools/gardening/bin$ ../../../out/ReleaseX64/dart-sdk/bin/dartanalyzer foo/../bot.dart
Analyzing bot.dart...
Unhandled exception:
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:236:28)
<asynchronous suspension>
#2      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:162:43)
<asynchronous suspension>
#3      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:104:18)
<asynchronous suspension>
#4      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:752:21)
#5      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:375:40)
#6      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#7      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:242:40)
#8      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:230:20)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:227:36)
#11     Driver.start (package:analyzer_cli/src/driver.dart:199:38)
#12     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#13     Driver.start (package:analyzer_cli/src/driver.dart:163:21)
#14     main (file:///usr/local/google/home/whesse/ssd/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
#15     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#16     main (file:///usr/local/google/home/whesse/ssd/sdk/pkg/analyzer_cli/bin/analyzer.dart:9:5)
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

The same crash happens when a valid absolute path to a file including a .. is passed to -dev.60, but any valid absolute path works in -dev.36.

@bwilkerson @scheglov @stereotype441

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/59101
