### ISSUE TITLE
Incorrect type casting between int, double, and string using num

### ISSUE THREAD

**Issue by Hell4Ge** [dart-lang/sdk#33393]
Using dartpad "Based on Dart SDK 2.0.0-dev.59.0" under Chrome

The code

```
void main() {
		// 9223372036854775807 its max value for 64bit integer
    num a = 9223372036854775808.0;	// This should enter the double range, so I suppose a would be double
  
  	print(a);	// prints 9223372036854776000, not 9223372036854775808
  
    print(a is double); // true
    print(a is int);		// true
}
```

The output

```
9223372036854776000
true
true
```

Ok so far the 9223372036854776000 is a JavaScript fault ([StackOverflow](https://stackoverflow.com/questions/8104391/why-do-javascript-converts-some-number-values-automatically))

**Comment by zoechi** [comment]
Integers in Javascript are 53 bit, not 64 https://webdev.dartlang.org/faq#q-how-are-integers-handled-when-compiled-to-javascript
You might want to BigInt (see also https://www.dartlang.org/articles/dart-vm/numeric-computation, https://docs.flutter.io/flutter/dart-core/BigInt-class.html)

**Comment by matanlurey** [comment]
DartPad uses JS number semantics, like @zoechi mentioned.
