### ISSUE TITLE
Analyzer allows function type parameters in new Function syntax

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33398]
The grammar for the new for Dart 2 Function type syntax does not allow old-style function typed parameters to be mixed in with the new Function syntax.  The following should be rejected:

```
typedef F = int Function(int f());
```

The analyzer currently allows this.

See https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-function-type-alias.md for the relevant grammar.

cc @eernstg

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/74043
