### ISSUE TITLE
Release pkg:analyzer 0.32.2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33396]
With commits including https://github.com/dart-lang/sdk/commit/bdbf872079efc28af49e16bb1549ff5fa4d21f9e

Assuming we have some confidence that there are no breaking API changes since 0.32.1

**Comment by kevmoo** [comment]
FYI: I just tagged 0.32.1 - https://github.com/dart-lang/sdk/releases/tag/analyzer-0.32.1

**Comment by bwilkerson** [comment]
Done.
