### ISSUE TITLE
Observatory wont run

### ISSUE THREAD

**Issue by acidblue** [dart-lang/sdk#33406]
Dart version 1.24.3 on Win 7 x64
I get a "Firefox cant connect to localhost:8181" error.
Not sure if Observatory is even installed, how do i check?
All the IDE's iv'e tried cant connect to observatory, also they cant run Dart, even though the dart plugins are installed.
I've tried:
Visual Studio.
Atom
Dont know where to begin, so far Dart is a major PIA!
Need help.

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by matanlurey** [comment]
@acidblue You are using a pretty old version of Dart, considering Dart 2.0 is close.

Please refrain from profanity in our issue tracker, and review our [code of conduct](https://www.dartlang.org/code-of-conduct) going forward. Closing thread as non-actionable.

**Comment by acidblue** [comment]
I updated to Dart 2.0, but I get the same error.
The only difference is the port # has changed.

**Comment by zoechi** [comment]
Does
```
dart --observe bin/main.dart
```
what you want?
