### ISSUE TITLE
CFE: Missing error when awaiting a void expression

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33416]
The snippet below should be an error per the static analysis section of https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md .

```dart
import 'dart:async';

void returnsVoid() {}

main() async {
  await returnsVoid();
}
```

**Comment by dgrove** [comment]
per #33415, this is not caught by the analyzer.

**Comment by natebosch** [comment]
Closing as unplanned since it's a breaking change to fix it and we've decided it's not worth the effort to clean up. As per https://github.com/dart-lang/sdk/issues/33823 we will hopefully be able to make this show up in the analyzer but can't add it to CFE.
