### ISSUE TITLE
Implement general-purpose dead code elimination in Dart VM compiler

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#33414]
Currently, we have specialized DCE for phis and instruction-specific cleanup during instruction canonicalization. However, it could be useful to have general-purpose DCE pass which would be able to remove unused instructions (even if they are in a cycle through phis).

/cc @mraleph

**Comment by mraleph** [comment]
@alexmarkov should we keep this open to track implementation of DCE capable of removing control flow?

**Comment by alexmarkov** [comment]
DCE pass which I implemented removes code which is reachable but doesn't have any effect. It doesn't remove branches which don't have any effect, but another pass (`OptimizeBranches`) handles that already. It's not aimed at removing unreachable basic blocks.

Created a separate issue https://github.com/dart-lang/sdk/issues/39765 to investigate feasibility of implementing unreachable code elimination.
