### ISSUE TITLE
dartanalyzer can't find dart files any more?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33411]
Dart VM version: 2.0.0-dev.61.0 (Mon Jun 11 15:46:09 2018 +0200) on "linux_x64"

In the `build` repo, I can't seem to get `dartanalyzer` to find any dart files at all any more, example commands below:

```
~/build/build$ dartanalyzer .
Analyzing build...
No dart files found at: <redacted>/build/build
~/build/build$ dartanalyzer lib/build.dart 
Analyzing lib/build.dart...
No dart files found at: <redacted>/build/build/lib/build.dart
```

**Comment by jakemac53** [comment]
@MichaelRFairhurst do you think this could be related to the recent changes for finding generated files?

**Comment by jakemac53** [comment]
This actually seems to be related to how the `excludes` are treated in `analysis_options.yaml`, ours looks like this:

```yaml
  exclude:
    - "test/goldens/generated_build_script.dart"
    # Note that these paths are actually package relative, this does not exclude
    # the `build` package from analysis.
    - "build/**"
    # Prevents extra work during e2e test runs.
    - "dart2js_test/**"
    - ".dart_tool/**"
```

Removing the `build/**` from that gets things working again.

My guess is now these paths are considered relative to the analysis_options.yaml and not the individual package (this is a mono_repo setup with multiple packages in subdirectories with a single analysis_options.yaml at the root of the repo).

**Comment by jakemac53** [comment]
Feel free to close if this is the new intended behavior

**Comment by MichaelRFairhurst** [comment]
Thanks for filing -- and for figuring it out!

I *will* close it as intented behavior, but I'm also curious to hear if you have any suggestions on what we should do in this case.

Workarounds include making a new analysis_options.yaml in build/, or making an analysis_options_alternate.yaml and then doing `dartanalyzer --options analysis_options_alternate.yaml build/`. I don't think there are any others.

With the former solution, your nested analysis_options.yaml file cannot `include:` the outer one. In that case, the `exclude` path gets inherited literally: `build/build/**` would be excluded if you are analyzing within `build/`.

With the latter solution, you can't `include: analysis_options.yaml` without still excluding `build/**`, but you could make a `base.yaml` which has everything _except_ the exclude. Then `analysis_options.yaml` can `include: base.yaml` and `analysis_options_alternate.yaml` can too.

Would these work for you, or do we need to brainstorm more ideas on how to make the excludes work better?

**Comment by jakemac53** [comment]
Honestly - think the new logic is better than the old logic anyways - if you look at the [update](https://github.com/dart-lang/build/pull/1555/files#diff-d62227308ce5fdb544ee6b0a8b157a69) in the build repo things are a lot more clear now. I don't think we need anything on our end.

This should really only affect mono_repo structured packages - its a bit annoying for those but ultimately they end up in a better place so :man_shrugging: .

**Comment by MichaelRFairhurst** [comment]
Awesome. OK, closed WAI!
