### ISSUE TITLE
Spawning isolates causes a memory leak in Dart 2

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33428]
Original issue https://github.com/dart-lang/test/issues/863

Dart VM version: 2.0.0-dev.61.0 (Mon Jun 11 15:46:09 2018 +0200) on "linux_x64"

If you run the following code with --preview-dart-2 then the memory steadily climbs even though the isolates are being killed.  If you run it without --preview-dart-2 then the memory remains quite stable (it does climb a little but not on every iteration of the loop - probably a result of jit optimizations).

Reproduction code:

```dart
import 'dart:async';
import 'dart:io';
import 'dart:isolate';

void main() async {
  final completer = new Completer();
  final p = new ReceivePort();
  final isolate = await Isolate.spawn(func, p.sendPort, paused: true);
  var d = new ReceivePort();
  isolate.addOnExitListener(d.sendPort);
  d.listen((_) => completer.complete());
  p.listen((_) => isolate.kill());
  isolate.resume(isolate.pauseCapability);
  await completer.future;
  p.close();
  d.close();

  final current = await Process
      .run("ps", ["-p", "$pid", "-o", "command,vsize,rss,%mem,size"]);
  print("${current.stdout}");
}

void func(SendPort p) async {
  p.send('ok');
}
```

cc @a-siva @dgrove

**Comment by joeconwaystk** [comment]
I'll add that in larger test suites, memory consumption goes well over 10Gb (before my machine starts choking, at least). This reproduction case just identifies that something is being retained by the VM for each isolate spawned (both by the test runner, or the test code itself).

**Comment by rmacnak-google** [comment]
@aam The kernel service never removes entries from the map that associates compiler state with an isolate.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/61113 with the fix
