### ISSUE TITLE
Common front end: Return type in async function not checked

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33425]
The language specification says that it is a static warning (so in Dart 2 it is an error) for an `async` function to have return type `R` unless `R` is a supertype of `Future<T>` for some `T`. In other words, the return type can be `Future<T>` for any `T`, and it can be any top type (like `dynamic`, `FutureOr<void>`, etc.). But it is not enough to be a subtype of `Future<...>` and in particular it cannot be `Null`.

Consider the following program:

```dart
Null f() async {}

main() async {
  await f();
}
```

No error message is emitted when this program is executed using `dart --preview-dart-2` (version 2.0.0-dev.60.0), but it should be a compile-time error.

**Comment by natebosch** [comment]
This is a big hole that users are likely to run in to. Can we give this a high priority?

cc @dgrove

**Comment by dhil** [comment]
@natebosch I submitted a fix for this yesterday, it'll probably go in on Monday.
