### ISSUE TITLE
[analyzer] Misleading error message for async return type `Never`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33424]
[Edit: The example program has been updated, see [this comment](https://github.com/dart-lang/sdk/issues/33424#issuecomment-1527171444).]

The language specification says that it is a static warning (so in Dart 2 it is an error) for an `async` function to have return type `R` unless `R` is a supertype of `Future<T>` for some `T`. In other words, the return type can be `Future<T>` for any `T`, and it can be any top type (like `dynamic`, `FutureOr<void>`, etc.). But it is not enough to be a subtype of `Future<...>` and in particular it cannot be `Null`.

Consider the following program:

```dart
Null f() async {}

main() async {
  await f();
}
```

Here is the error message from the analyzer for that program (version 2.0.0-dev.60.0):

```
> dartanalyzer --preview-dart-2 --no-hints n005.dart
Analyzing n005.dart...
  error • Functions marked 'async' must have a return type assignable to 'Future' at n005.dart:3:1 • illegal_async_return_type
1 error found.
```

This message is misleading given that `Null` is actually assignable to `Future` (which would presumably mean `Future<dynamic>`), and it should be adjusted to follow the rule in the specification more precisely. I have no reason to believe that there is a problem with the error detection, it is just the error message which is misleading.

**Comment by keertip** [comment]
Closing as we are at Dart 3 now, and this is stale.

**Comment by eernstg** [comment]
I actually think we still need the fix, for the same reason (except that the example program is a bit different now, because of language changes). So here is the updated example program:

```dart
Never f() async {}
main() async => await f();
```

This program is still rejected (as it should be) with an error message which is misleading (which, presumably, it shouldn't be ;-). Here is the message from DartPad (based on Flutter 3.10.0-14.0.pre Dart SDK 3.1.0-42.0.dev):

```
Functions marked 'async' must have a return type assignable to 'Future'.
```

This error message is misleading because (1) `Never` _is_ assignable to `Future<T>` for any `T`, so the error message contradicts itself. (2) The actual requirement is that there must be a `T` such that `Future<T>` is assignable to the return type (we could also say: `Future<Never>` must be a subtype of the return type).

So the requirement has the opposite direction, and that requirement 

I believe the error message could simply be adjusted to say 'Functions marked 'async' must have a return type which is a supertype of 'Future<Never>'.'

**Comment by eernstg** [comment]
@johnniwinther, the CFE emits the same error message. Do you think there is a need for a separate CFE issue?

**Comment by eernstg** [comment]
Very good, cf. https://github.com/dart-lang/sdk/issues/52211.
