### ISSUE TITLE
CFE doesn't reject generic function types in bounds of type variables

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#33423]
The following script should result in a compile-time error; however, it crashes the compiler currently.

```dart
class Hest<X extends Y Function<Y>(Y)> {}

main() {}
```

**Comment by dgrove** [comment]
With -dev.59, the analyzer produces no errors and no warnings for this. /cc @bwilkerson

**Comment by mit-mit** [comment]
Moving to P1, this is causing a crash and should not be allowed to compile

**Comment by dgrove** [comment]
Is there a link to the pending fix, @stefantsov ?

**Comment by stefantsov** [comment]
Sorry for the delay @dgrove.  I'm working on it right now.  I plan to upload it in about an hour.

**Comment by stefantsov** [comment]
I've uploaded the pending fix as [CL 64544](https://dart-review.googlesource.com/c/sdk/+/64544).
