### ISSUE TITLE
No error reported when a const makes explicit use of a type parameter

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33439]
Consider the following code:
```dart
class C<T> {
  const C();
}

class D<T> {
  final x = const C<T>(); // (1)
}

main() {
  print(new D<int>().x.runtimeType);
}
```

The VM, dart2js, and the common front end agree that this code has an error at the line marked `(1)`, because a constant expression cannot refer to type variables in enclosing scopes.

The analyzer reports no error.

**Comment by sigmundch** [comment]
DBC

I should note that we have run into this a few times with internal customers when defining default values. The most subtle case has been when using a generic function, which gets instantiated with a class type variable implicitly. You can find examples in https://github.com/dart-lang/sdk/issues/33438

**Comment by MichaelRFairhurst** [comment]
Saw this while investigating #32913 and thought it'd be a good place to start.....however, this is already fixed, it seems.
