### ISSUE TITLE
improve error messages on invalid constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33438]
We need to provide better error message when constants are invalid. 

One scenario that especially needs more data is generic instantiation that are substituted by a type variable (since type variables can be used in a constant context).

Compare the error message you get from these 2 examples:
```dart
class A<T> {
  final List<T> f;
  A([this.f = const <T>[]]);
}

main() => print(new A<String>().f);
```

```
Error: Type variable 'T' can't be used as a constant expression #lib1::A::T.
```

```dart
Q generic<Q>() => null;

class A<T> {
  final T Function() f;
  A([this.f = generic]);
}

main() => print(new A<String>().f);
```

```
Error: Not a compile-time constant.
```

**Comment by zoechi** [comment]
Similar to #33216 ?

**Comment by sigmundch** [comment]
Very similar, but still a separate issue because #33216 tracks error reporting for constants in the vm. (most errors are reported by the front-end, but constants are not evaluated in the front-end, instead each backend (dart2js, vm) has it's own evaluation logic and error reporting)

**Comment by vsmenon** [comment]
Bump past 2.1?

**Comment by sigmundch** [comment]
Since we flipped the constant-update-2018 flag, the CFE now does all constant evaluation and a reasonable error is given for the second case.
