### ISSUE TITLE
Dev61 Heavy memory usage with simple QuickStart examples

### ISSUE THREAD

**Issue by werner-j** [dart-lang/sdk#33437]
Hello,

I'm testing Dart 2.0 dev build 61 and experience heavy memory consumption even with the simple QuickStart examples from the web page or Web Storm (todo list example) on a Mac with Safari. When looking at memory stats, opening the page increases the RAM consumption of Safari for about 4-5 GB.

Safari basically tells me that I'm running a web site with heavy memory consumption and that I should close it to improve the performance of my Mac. I can reproduce this on my iMac and a MacBook Air.

In order to route, prioritize, and act on this, please include:

* Dart VM version: 2.0.0-dev.61.0 (Mon Jun 11 15:46:09 2018 +0200) on "macos_x64"
* macOS High Sierra (with all updates)
* Safari

**Comment by matanlurey** [comment]
@werner-j: Unfortunately this isn't enough information to really act on. Can you include:

* A link to or source code of the example you are running
* How you are running/serving your application
* If you are using DDC (DartDevCompiler) or Dart2JS

I have never seen any sample application use 4-5Gb of RAM. It's possible that DartDevCompiler has a bug in Safari, officially it only supports Chrome right now.

**Comment by werner-j** [comment]
Hello @matanlurey 

thanks for your reply. The source code is the standard QuickStart example from WebStorm that you get, when using the wizard. If necessary, I can create an archive and upload, but you can get it directly from the WebStorm wizard.

I am running the application as follows:

```
iMac:dartlang werner$ /Users/werner/.pub-cache/bin/webdev serve
[INFO] Setting up file watchers completed, took 29ms
[INFO] Waiting for all file watchers to be ready completed, took 201ms
[INFO] Reading cached asset graph completed, took 996ms
[INFO] Checking for updates since last build completed, took 869ms
[INFO] Running build completed, took 644ms
[INFO] Caching finalized dependency graph completed, took 422ms
[INFO] Succeeded after 1.1s with 0 outputs (0 actions)
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081
```

I figured that on Firefox there is no such weird behavior.

Herer is two images from iStat Menus memory graph. The first shows Safari's memory consumption right before and the second right after opening http://localhost:8080 in the browser:

![bildschirmfoto 2018-06-13 um 19 36 38](https://user-images.githubusercontent.com/4938857/41368127-48396952-6f41-11e8-8ff7-28b103da1ba3.png)
![bildschirmfoto 2018-06-13 um 19 36 59](https://user-images.githubusercontent.com/4938857/41368131-4a67b49a-6f41-11e8-9cd8-02ace3b75115.png)

As you can see its memory usage increases from 2.14GB to 5.27GB (so this time 3.13GB). In Firefox I can only spot about 100MB increase of the browser's memory usage. For Chrome I have to try.

**Comment by matanlurey** [comment]
@werner-j Is it one of these? https://github.com/dart-lang/stagehand/tree/master/templates

As I mentioned, Safari is likely not supported here. It shouldn't use GBs of RAM though, I think.

**Comment by werner-j** [comment]
@matanlurey looks like it's https://github.com/dart-lang/stagehand/tree/master/templates/web-angular

**Comment by matanlurey** [comment]
DartDevCompiler, as you can tell by the name, is for development. It is the only incremental build compiler. You can always use the production compiler, Dart2JS, but re-builds will be slow. You can use that with the "release" option for build_runner:

```bash
$ pub run build_runner serve --release
```

/cc @natebosch

**Comment by natebosch** [comment]
@vsmenon @jmesserly - are we aware of issues with high memory usage with small sample apps with DDC?

**Comment by jmesserly** [comment]
I'm not aware of any Safari specific memory issues. It is possible DDC is using some feature or pattern that is not well optimized in Safari, but without a detailed profile it's hard to say. Given that memory usage is fine in the other two browsers, it suggests a browser issues.

**Comment by matanlurey** [comment]
@werner-j Can you supply profile information?

**Comment by werner-j** [comment]
@matanlurey - could you please be a bit more specific, which kind of information you're looking for and whether there's an automated way of creating that? If you're looking for information about the machine, that is as follows:

* iMac 27"
* Intel Core i7 2,93GHz
* 24GB RAM
* 2.25TB Fusion Drive (>2TB free)
* macOS High Sierra 10.13.5
* Safari Version 11.1.1 (13605.2.8)

I will try the production compiler to compare what happens there. Thanks for that suggestion.

**Comment by werner-j** [comment]
Okay - when serving via `pub run build_runner serve --release` there is no issue with Safari and memory consumption is fine. So it seems a DDC related problem. Thanks for the help.

**Comment by matanlurey** [comment]
I think we can safely close this. I don't think there is any intention to optimize Safari+DDC right now.
