### ISSUE TITLE
Dart 2-dev.61: Analysis server reports "Target of URI doesn't exist" when CLI analyzer is happy

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33457]
## Environment

Dart VM version: **2.0.0-dev.61.0** (Mon Jun 11 15:46:09 2018 +0200) on "macos_x64"

## Steps to reproduce

1. `git clone https://github.com/dart-lang/site-www.git`
2. `cd site-www/examples/util`
3. `pub upgrade`
4. `dartanalyzer --preview-dart-2 .` # will report: No issues found!
5. Open the same project in VS Code or WebStorm.

## Expected result

The IDE should report the same analysis errors (i.e., none) as the CLI analyzer, but instead it reports `Target of URI doesn't exist: 'package:test/test.dart`:

```
{
	"resource": "/Users/chalin/git/dart/site-www/examples/util/lib/print_matcher.dart",
	"owner": "dart",
	"code": "uri_does_not_exist",
	"severity": 8,
	"message": "Target of URI doesn't exist: 'package:test/test.dart'.",
	"source": "dart",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 32
}
```

This happens for all projects under `site-www/examples`.

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
In another project I'm noticing that `ignore_for_file` and `ignore` directives are being ignored by the analysis server.

**Comment by kwalrath** [comment]
For at least a week, I've seen this in my working copy of site-www. I tried deleting .idea files and ~/.dartServer/.analysis-driver/, as well as repairing the cache, but no joy.

When I download a fresh copy of site-www, it's fine. I can even open both copies of site-www in WebStorm at the same time, and the old|fresh copies are still broken|OK.

So there's something left over somewhere that's messing with both Patrice and my site-www repos, but I can't figure out what it is.

**Comment by bwilkerson** [comment]
I'm going to close this under the assumption that it's been fixed now that `dartanalyzer` has been replaced by `dart analyze`.
