### ISSUE TITLE
dart2js: enable dart2 by default

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33454]
* [x] add a `--no-preview-dart-2` flag to temporarily opt-out
* [x] switch the default behavior of dart2js in the sdk.
* [x] increase test coverage of Dart 2.0 in the bots
  * [x] d8 bots running Dart2
  * [x] chrome bots running Dart2
  * [x] ff bots running Dart2
  * [x] safari bots running Dart2
  * [ ] ie bots running Dart2
* [x] update .status files:
  * [x] d8
  * [x] chrome
  * [x] ff
  * [x] safari
  * [ ] ie

[1]: https://dart-review.googlesource.com/c/sdk/+/64320

**Comment by sigmundch** [comment]
update: CL ready, but waiting for bot stability after the vm switched dart2 by default.

**Comment by sigmundch** [comment]
update: technically we landed a CL that enables it by default, however, I don't want to close this bug until our test bots are covering the new mode in all browsers.

**Comment by sigmundch** [comment]
update: test-matrix changes with extra coverage in linux landed, infrastructure team will be adding the coverage shortly. Status files up to date for linux tests.

Next steps: bot changes (from infrastructure team), bring mac/win bots to parity as well.

**Comment by sigmundch** [comment]
update: status files up to date for d8, chrome, ff, safari. Infrastructure team will swap all bots to test the strong counterparts. Bots for ie11 need more infrastructure work, so they will come a bit later.

I'm keeping this as P1 because bots are testing dart2js for dart2 only in d8, as soon as we have one browser tested in dart2, we'll lower this item priority to P2.

@athomas @whesse - would you be able to help us do the flip this week? Our goal was to have them before shipping Dart2Stable-prerelease so that we are more confident that we don't have hidden regressions. Thanks!

**Comment by sigmundch** [comment]
update: Bill started the migration process, there is already a CL out to enable the chrome bots in strong mode.

**Comment by sigmundch** [comment]
update: Bill landed several changes and we are now run all except the IE browser tests in dart2, woohoo!

We still need to get the IE bots up and running with the new test-matrix infrastructure, but I don't consider this blocking Dart2Stable anymore. I realize it's still important to get this done, so rather than lowering the priority, I'm updating the milestone instead.

**Comment by vsmenon** [comment]
@athomas - are we still blocked on IE bots or are those on Dart2 now?

**Comment by athomas** [comment]
None of the dart2js bots runs with --no-preview-dart-2. As far as I know
the dart2js team has already started to remove the Dart 1 support from
dart2js itself.

**Comment by vsmenon** [comment]
Thanks - can we close this bug then?

**Comment by vsmenon** [comment]
closed after chatting with @johnniwinther @rakudrama
