### ISSUE TITLE
autocompletion doesn't work on map literals

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#33464]
Thank you for taking the time to file an issue!

Works for `List`

![image](https://user-images.githubusercontent.com/405837/41457742-dd696d58-7084-11e8-8844-80f9a4d21276.png)

but does not for `Map`

![image](https://user-images.githubusercontent.com/405837/41457757-eab29c3c-7084-11e8-94fa-fe6ebea1e6ee.png)

Dart VM version: 2.0.0-dev.62.0 (Wed Jun 13 16:50:22 2018 +0200) on "macos_x64"

**Comment by bwilkerson** [comment]
My guess is that the map literal is being interpreted to be a block. There is an issue open for that behavior, but I can't locate it at the moment.

**Comment by bwilkerson** [comment]
Ah, it was a CL I was thinking of: https://dart-review.googlesource.com/c/sdk/+/71247.

This is now working as intended.
