### ISSUE TITLE
pub global activate packages don't work with --preview-dart-2

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/sdk#33460]
Related to https://github.com/dart-lang/sdk/issues/32188
If I run
`DART_VM_OPTIONS=--preview-dart-2 pub global run webdev build`, then the dart2 flag is passed properly, and I can use dart2 features like optional new/const.

However, if I run
```
pub global activate webdev
DART_VM_OPTIONS=--preview-dart-2 webdev build
```
then the flag is not passed properly to the dart vm, so we get failures with optional new/const.

**Comment by dgrove** [comment]
After talking with @natebosch , closing this, as it will be fixed automatically when Dart2Stable ships.
