### ISSUE TITLE
Uncaught Error: TypeError: Can't create an instance of malbounded type 'Future<void>'

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33467]
This is a simplified reproduction of this issue https://github.com/dart-lang/angular/issues/1401. I'm not sure when this began happening, but it can be reproduced on version 2.0.0-dev.61.0 and upwards.

The following program

```dart
void main() {
  new Future<void>.value();
}
```

compiled with `dart2js --checked`, produces the following error

```
main.dart.js:591 Uncaught Error: TypeError: Can't create an instance of malbounded type 'Future<void>': 'void' is not a subtype of bound 'Object' type variable 'Future.T' of type 'Future<Future.T>'.
    at Object.wrapException (main.dart.js:591)
    at Object.throwTypeError (main.dart.js:1127)
    at Object.main (main.dart.js:1713)
    at main.dart.js:1935
    at main.dart.js:1919
    at main.dart.js:1930
    at main.dart.js:1938
```

However, the same error isn't produced with `dart2js --enable-assserts`. I'm not sure what the distinction between these flags are.

Furthermore, this error isn't generated if you compile with `dart2js --checked --preview-dart-2`.

- Is this a bug?
- Is `--checked` still relevant?
- Why does it produce different asserts?
- Are `void` semantics invalid without `--preview-dart-2`?

**Comment by matanlurey** [comment]
There is no such thing as `--checked` with `--preview-dart-2`.

If this works with `--preview-dart-2` without `--checked` we can also close this issue.

**Comment by srawlins** [comment]
Works on the VM, dev.59, with no flags, with `--checked`, and with `--preview-dart-2`.

**Comment by leonsenft** [comment]
> There is no such thing as --checked with --preview-dart-2.

Out of my own curiosity how do you know this? I can't find any clarifying documentation. Maybe dart2js should be emitting a warning if you pass in `--checked` that it will be removed in the near future (when `--preview-dart-2` is the default).
 
> If this works with --preview-dart-2 without --checked we can also close this issue.

It does.

**Comment by leonsenft** [comment]
@matanlurey But it doesn't say that anywhere on the page you linked, so I'm still not sure how anyone would be expected to know this.

**Comment by matanlurey** [comment]
Yeah, that problem I can't solve. I'm just saying at a technical level, it isn't supported.

@kwalrath @chalin  Can we make sure to update this tools page for Dart2?

/cc @jakemac53 @natebosch

**Comment by sigmundch** [comment]
FWIW - we initially added a hint in the compiler to warn about it:

https://github.com/dart-lang/sdk/blob/541dd195bb536e69d992a7ee47d1c1884fb43456/pkg/compiler/lib/src/dart2js.dart#L443

I realize now that this hint is not being printed, because of a separate issue with the FE (we were omitting all hints because they were hundreds of them).

We will remove the option when we remove Dart 1.0, but not before. Meanwhile,  here are some action items we can do:
* [ ] reenable the hint
* [ ] update the dart2js usage to indicate which flags are Dart 1 only.
* [ ] update online docs as well

**Comment by kwalrath** [comment]
The [v5 tools page](https://webdev-dartlang-org-dev.firebaseapp.com/tools/dart2js) already doesn't have `--checked`. We'll update the v4 one to mention that `--checked` and `--preview-dart-2` don't work together, and that `--checked` won't be present in Dart 2.

**Comment by chalin** [comment]
I'll handle updating the docs in the manner that Kathy suggested.

This is what the `dart` help prints:

```console
> dart -h
Usage: dart [<vm-flags>] <dart-script-file> [<dart-options>]

Executes the Dart script passed as <dart-script-file>.

Common options:
--checked or -c
  Insert runtime type checks and enable assertions (checked mode, not
  compatible with --preview-dart-2).
...
```

So updating the dart2js usage text in a similar fashion is an excellent idea.

@sigmundch - if you open a separate issue to track "update the dart2js usage to indicate which flags are Dart 1 only.", can you please cc @kwalrath and @chalin?

**Comment by sigmundch** [comment]
Thanks @chalin 

Turns out that the dart2js usage no longer shows --checked, we are basically only showing flags available in Dart 2.0.

**Comment by chalin** [comment]
Using the latest external SDK, the `-c` flag is still mentioned:

```console
> dart --version
Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"
> dart2js -h
Usage: dart2js [options] dartfile

Compiles Dart to JavaScript.

Common options:
  -o <file> Generate the output into <file>.
  -c        Insert runtime type checks and enable assertions (checked mode).
  -m        Generate minified output.
  -h        Display this message (add -v for information about all options).
```

Also:

```console
> dart2js -h -v
Usage: dart2js [options] dartfile

Compiles Dart to JavaScript.

Supported options:
  ...
  --preview-dart-2
    Preview of all Dart 2.0 semantics, this includes generic methods and strong
    mode type checks.

    This flag is mainly for early dogfooding and will be removed when all
    features are shipped.
```

The `--preview-dart-2` flag should probably be mentioned when under the (terse) usage text. The "early dogfooding" reference should probably be removed now :)

**Comment by chalin** [comment]
> Turns out that the dart2js usage no longer shows --checked, we are basically only showing flags available in Dart 2.0.

@kwalrath, in that case I'd suggest holding back on making changes to the v4 webdev site. WDYT?

**Comment by sigmundch** [comment]
Thanks @chalin!

Ha, we had removed the longer `--checked` expanded documentation but totally missed the `-c` shortened version.... I'll remove it too.

I plan to make --preview-dart-2 on by default in the next few days, so I'll likely just get rid of the flag entirely at that moment.

**Comment by supermuka** [comment]
@leonsenft, just answer your question in [dart-lang/angular#1401]( dart-lang/angular#1401) about why I need to use _dart2js_ instead _ddc_.

After upgrading Dart to 2.0.0-dev.57.0, the following exception was thrown on the browser console:

> `EXCEPTION: Type 'List<dynamic>' should be 'List<UserProfileOrganization>' to implement expected type 'FutureOr<List<UserProfileOrganization>>'`

I am using **_rpc package_** (0.5.8) to implement REST APIs and this exception occurs into client side stub file generated by _rpc tool_.

To solve this problem, the use of dart2js was suggested, as discussed in Gitter on [mai 23 15:28](https://gitter.im/dart-lang/server?at=5b05b2d5aaafa25932ae3fbd).

Since then, I'm using **dart2js** including `-r` parameter on build command line as `pub run build_runner serve -r`. This way the above exception is no longer thrown.

**Comment by matanlurey** [comment]
That was not great advice, both Dart2JS and DDC will care about these errors in Dart2.

**Comment by joshualitt** [comment]
I believe this is now working on TOT. Please reopen this issue with a new repro if that is not the case.
