### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by charlenopires** [dart-lang/sdk#33474]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 182.3208.16`
- `2.0.0-dev.63.0`
- `IC-182.3208.16, JRE 1.8.0_152-release-1226-b7x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\CHARLE~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-dev.63.0, server version 1.20.3, error: Could not initialize the library map from [D:\Dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, D:\Dart\sdk\lib\_internal\libraries.dart]

FileSystemException(path=D:\Dart\sdk\lib\_internal\libraries.dart

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/dart-lang/sdk/issues/33720
