### ISSUE TITLE
Analyzer should warn on always-throwing calls

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#33486]
Sometimes, it's needed to disallow certain inherited methods. The most obvious example is `UnmodifiableListMixin`. Classes that mix it in have modification methods defined but throw on them at runtime.

Consider this example:
```dart
import 'dart:collection';

void main() {
  final foo = new UnmodifiableListView(new List<int>(1));

  foo; // Static type: UnmodifiableListView
  foo[0] = 42; // Unsupported operation: Cannot modify an unmodifiable list
}
```
It would be nice for the analyzer to warn on operations that are guaranteed to throw. 

If proving that is too difficult, maybe it's reasonable to add a new `@unsupported` annotation which would combine UX effects of `@alwaysThrows` (dead code highlighting) and `@deprecated` (strike-throw).

**Comment by matanlurey** [comment]
I wonder how generally useful this is, considering:

* It's totally valid to have something throw (and not be caught). This isn't Java ;)
* In your case, it's detectable, but imagine the more realistic scenario:

```dart
import 'dart:collection';

void main() {
  final foo = new UnmodifiableListView(new List<int>(1));
  useAList(foo);
}

void useAList(List<int> list) {
  list[0] = 42;
}
```

... in this case, there is no static way (without program analysis) to detect you are making an invalid operation. I'm afraid that the pattern of _ disallow certain inherited methods_ is just not a strong one (and more of a smell). I hope we can get proper immutable collections at some point to mitigate the need for this pattern.

**Comment by lexaknyazev** [comment]
In my real code, I'd like a class (which is not a `List`) to implement:
1. all read-only `ListBase` members;
2. `operator []=`;
3. ability to grow (increase `.length` value) but not shrink.

`ListBase` brings various `remove*` methods that won't work anyway, so I wanted to somehow "hide" them. What would be a less smelly way of doing that?

**Comment by matanlurey** [comment]
There is no way to do this, unfortunately. 

You could create your own sub-type of `Iterable`:

```dart
abstract class ImmutableList<T> implements Iterable<T> {
  T operator [](int index);
}
```

... though that gets pretty close to [`BuiltList`][1].

[1]: https://pub.dartlang.org/documentation/built_collection/latest/built_collection/BuiltList-class.html

/cc @leafpetersen @lrhn for thoughts. This comes up quite a bit (lack of immutable lists).

**Comment by lrhn** [comment]
I have no plan to add variant `List` types. This is an old discussion, and so far we are sticking to the design of having `List` for everything and throwing on operations that are not allowed.

There are simply too many variants to pick from to make for a useable class hierarchy.

The analyzer can still warn if it discovers that something will inevitably throw, but that's only possible when it *understands* the code and knows exactly what method will be called. The language specification will not go into that detail.

**Comment by srawlins** [comment]
Since subtypes can always be in play, the analyzer cannot know if an `@unsupported` call will be made or not.

And as @lrhn says, there are no plans to make related changes to List.
