### ISSUE TITLE
Suggestion: _typeInferrer.inferFieldInitializer should get the factory from InferenceHelper

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33488]
Feedback from @kmillikin on https://dart-review.googlesource.com/c/sdk/+/60620, commenting on the code in body_builder.dart that passes the factory to _typeInferrer.inferFieldInitializer:

> It seems like we should just get the factory from the InferenceHelper this, rather than passing it.  Since that requires changing the InferenceHelper API, feel free to consider it for a separate change.

**Comment by stereotype441** [comment]
I think this needs to wait until after #33503, since in order to add the factory to the InferenceHelper, we'll have to add type parameters to the InferenceHelper, and we don't want those type parameters to collide with the type parameters that are already present.

**Comment by kmillikin** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/33503.

**Comment by stereotype441** [comment]
Unassigning myself because I’m not actively working on this issue right now.

**Comment by kmillikin** [comment]
This is probably too stale to be relevant any more. @johnniwinther
