### ISSUE TITLE
We need to run `co19_2` test suite on Dart 2.0 configurations

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33484]
We really should test co19 on Dart 2.0 configurations. It appears like we don't run co19 on e.g. the `--compiler=dartkp --strong` configuration - probably we also don't run it on many other configurations.

Just today I've been fixing an issue, which does have a test in co19 but we don't run seem to run it, so the issue was not uncovered.

The necessary changes are: 
  * Update [tools/testing/dart/options.dart:_defaultTestSelector](https://github.com/dart-lang/sdk/blob/master/tools/testing/dart/options.dart#L13) to include `co19_2`
  * Update status files

@athomas Could you take a look at this?

/cc @mraleph @a-siva

**Comment by athomas** [comment]
Current status:
dart2js/analyzer/frontend are using co19_2 on all builders
VM CQ builders (vm-kernel-linux-product-x64, vm-kernel-linux-release-simdbc64, vm-kernel-linux-release-x64) are enabled.

Next step is to add some vm-precomp builders.

**Comment by athomas** [comment]
There are quite a few AOT builders running co19 tests now.
