### ISSUE TITLE
Please roll dart_style to 1.1.0

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#33490]
I've published a new version of dart_style. It fixes a minor runtime error when run on the Dart 2 VM. More importantly, it adds the `--fix` option to automatically remove `new` and unneeded `const` from user code.

It also has some formatting changes caused by the above support for optional `new`/`const`, so this needs to be coordinated with the pre-built version in `sdk/tools/sdks/*/dart-sdk/bin/dartfmt`. Would you mind rolling this in?

Thanks!

**Comment by athomas** [comment]
This might take some more days:
* We need to create a dev release with the flag flip.
* Then we need to check if its possible to update checked in SDKs (this is the first time test.py will run on a Dart 2 by default checked in SDK).
* Then we can roll dart_style (possible with another dev SDK).

**Comment by whesse** [comment]
I have just fixed test.py to run with a Dart 2 default SDK, and will check the rest of the build process by making a test CL that updates the SDK, and running on many trybots.

**Comment by athomas** [comment]
Blocked on #33590.

**Comment by munificent** [comment]
Thanks!
