### ISSUE TITLE
Analyzer error

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#33491]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-181.5281.31`
- `1.24.3`
- `WS-181.5281.31, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 3200x1800  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/pp/c9ntz_rn3b76h5_zxkvsl5sh0000gp/T/report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: /path/to/file.dart context: exception_20180618_205821_139
NoSuchMethodError: Class 'DynamicTypeImpl' has no instance method 'instantiate'.
Receiver: Instance of 'DynamicTypeImpl'
Tried calling: instantiate(Instance(length:1) of '_GrowableList')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ExprTypeComputer._doMakeUntypedList (package:analyzer/src/summary/link.dart:2450)
#3      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2091)
#4      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#5      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#6      DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#7      DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#8      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#9      FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#10     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)

**Comment by matanlurey** [comment]
This is an error from the Dart SDK from almost a year ago.

I'd recommend trying the latest `-dev` builds and see if the error persists. AFAIK there is no plans to continue any work or releases for the `1.x` (currently "stable") SDK.

**Comment by mnordine** [comment]
Forgive me, but I'm not sure I understand, I'm using stable Dart, stable WebStorm for a production application. Also, I have been using both for quite a while now (although perhaps something changed in my source code to trigger this).

**Comment by mnordine** [comment]
Curiously, everything is fine on Windows

**Comment by zoechi** [comment]
deleting `~/.dartServer/.analysis-driver/` might help

**Comment by mnordine** [comment]
Thanks for the suggestion @zoechi, but that didn't work.
