### ISSUE TITLE
Find a replacement for AstRewriteVisitor in LibraryAnalyzer._resolveFile2

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33506]
The purpose of the AstRewriteVisitor is to rewrite things that look like method calls into things that look like constructor calls (to support implicit constructor calls).  This visitor relies on resolution results, but we're calling it at a time that we haven't received resolution results yet.  I'm hoping that the visitor can eventually go away completely, because in the final design, the front end will know whether we're looking at a constructor call when it calls the factory, and it will call the appropriate factory method.

**Comment by scheglov** [comment]
Mostly done in https://dart-review.googlesource.com/c/sdk/+/68004
There is still a failing test because of using raw element instead of Member.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/68161 will fix the `ConstructorMember` problem.
