### ISSUE TITLE
Remove testedType arguments from Factory.isExpression and Factory.isNotExpression

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33507]
Currently the way the ResolutionStorer/ResolutionApplier works is to receive a DartType from the front end and then apply it's resolution information recursively to the type literal AST.  Eventually what we'll do instead is just construct a fully resolved type literal directly in the factory API, so the `testedType` argument won't be needed anymore.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
