### ISSUE TITLE
dart2js not injecting proper covariance checks

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#33500]
The following example doesn't throw when compiled with dart2js `--preview-dart-2`.  It should throw.

```dart
void main() {
  var list = [1, 2];
  List<Object> l2 = list;
  l2.add("hello"); // Runtime exception expected here.
  print(l2);
  print(l2.runtimeType);
}
```

**Comment by vsmenon** [comment]
@sigmundch - fyi - I didn't see a bug filed for this.

**Comment by sigmundch** [comment]
Johnni - can you take a look?

**Comment by rakudrama** [comment]
I'll look at it. We should be more selective about lowering to Array.push.

**Comment by rakudrama** [comment]
Fix available https://dart-review.googlesource.com/c/sdk/+/61104
