### ISSUE TITLE
Measure progress by counting all @failingTest annotations in analyzer/analysis_server CFE tests

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33512]
As soon as https://dart-review.googlesource.com/c/sdk/+/61101 lands, it would be nice to create a dart program that examines all of the reflective tests that exercise the common front end and counts:
- The number of tests marked as `@failingTest` in the CFE test that are marked as passing in the corresponding base class (non-CFE) test.
- The total number of tests that exercise the CFE.

This would give us a way of tracking progress once we have the old front_end/analyzer integration support re-enabled.

To see which tests exercise the common front end, see the tests that are enabled by https://dart-review.googlesource.com/c/sdk/+/61101.

**Comment by devoncarew** [comment]
Started here: https://dart-review.googlesource.com/c/sdk/+/62081
