### ISSUE TITLE
DDC throws `CastError` instead of `TypeError` on certain integer conversions.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33523]
The following program:

```dart
void main() {
  Object any = 3.4;
  String s = any;
  num anum = 3.4;
  int aint = anum;
}
```
compiled with DDC, generates the following js:

```js
   ddctest.main = function() {
    let any = 3.4;
    let s = core.String._check(any);
    let anum = 3.4;
    let aint = dart.asInt(anum);
  };
```

The `dart.asInt` intrinsic throws `CastError`, instead of `TypeError`.  The `_check` functions correctly throw `TypeError`.

**Comment by Markzipan** [comment]
Closing since DDC throws correct errors here now.
