### ISSUE TITLE
Stop inserting duplicate statements when there is an error in a loop.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33528]
This happens for example in this code:
```dart
main() {
  break:
  do {
    break break;
  } while (false);
}
```

The zero-th statement is duplicated after the loop, and when we `infer`, its expression is unwrapped from `ShadowSyntheticExpression(InvalidExpression)` into just `InvalidExpression` and this causes [crashes](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8943186141050098720%2F%2B%2Fsteps%2Ffasta_sdk_tests%2F0%2Fstdout).

**Comment by anders-sandholm** [comment]
Looks like this is an area-analyzer-cfe issue as well. 
Please make sure to add an area-* label when filing new issues if known at the time of filing.

**Comment by kmillikin** [comment]
It's not just the error in the loop that is causing this.  It seems to be an egregious case of cascading errors:
```
duplicate.dart:2:3: Error: A break statement can't be used outside of a loop or switch statement.
Try removing the break statement.
  break:
  ^^^^^
duplicate.dart:2:8: Error: Expected ';' before this.
  break:
       ^
duplicate.dart:2:3: Error: No target of break.
  break:
  ^
duplicate.dart:2:8: Error: Expected an identifier, but got ':'.
  break:
       ^
duplicate.dart:2:8: Error: Getter not found: ''.
  break:
       ^
duplicate.dart:2:8: Error: Unexpected token ';'.
  break:
       ^
duplicate.dart:4:11: Error: Expected ';' before this.
    break break;
          ^^^^^
```

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
