### ISSUE TITLE
Replace type inference listeners with factory objects

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33536]
Sub-tasks:
- [ ] Replace KernelTypeInferenceListener with ToplevelInferenceFactory
- [ ] Rename ResolutionStorer to AnalyzerFactory (or something like that)
- [ ] Remove TypeInferenceListener API

**Comment by kmillikin** [comment]
While this would be very nice to have, I think we should postpone it for now.  If it becomes a performance issue we'll raise the priority.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
