### ISSUE TITLE
Decide how Factory interface should handle forward references

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33530]
Consider the following code:
```dart
int twoToTheX(int x) { // (1)
  if (x == 0) return 1;
  return 2 * twoToTheX(x - 1); // (2)
}
```

The factory interface is designed to build the AST in bottom-up order, which means that we'll build the AST node for the reference to `twoToTheX` (at `(2)`) prior to building the AST node for the declaration of `twoToTheX` (at `(1)`).  But we want the AST to be fully resolved at the time that we build it, and that seems to require building the declaration node first.  We have a chicken-and-egg problem.

A similar problem arises for break and continue statements, which can point to labeled statements that enclose the break and continue statements.  Also, a similar problem arises for variable declarations, because even though referring to a variable prior to its declaration is illegal in Dart, it's important for the analyzer to be able to connect the illegal reference to the declaration site in order to aid the user in diagnosing and fixing the problem.

The chicken-and-egg problem is currently resolved in the ResolutionStorer by using the fileOffset of the declaration site as a proxy for the declaration itself.  So, the reference (`(2)`) is built first, and instead of immediately populating it with a reference to the declaration, it is populated with the file offset of the declaration.  Later, after the declaration (`(1)`) is built, the analyzer does a second walk of the AST, finding the declaration sites and hooking up all the references to them.

But doing a second walk of the AST is inefficient, so we would like to come up with a better way.

**Comment by kmillikin** [comment]
I can take this one:

We shouldn't focus on the order that the AST is built.  We will infer types and compile to syntax for the body of `twoToTheX` as a part of inferring types and compiling to syntax for the enclosing function.  This is not "bottom up", it is "top-down-bottom-up" with respect to the type inference derivation and we have very wide leeway about which order we satisfy the sub-derivations of a type inference derivation.  Information can flow from a judgment to the judgments it depends on and vice versa.

The standard solution is that you pass around an environment and that's what we should do here as well.

In this case, we can't even perform type inference for an expression unless we have an environment giving inferred types (either declared types, inferred at the declaration, or else promoted types) for free variable references.  This environment is essentially a map from names in scope to their inferred types.  It can also contain the syntactic declaration.

There is a similar solution for labels.  Fasta already has technology to do this which we will repurpose.

**Comment by stereotype441** [comment]
Addressed by the following CLs:
- 1b681a75c387630a5a567af57e0c85ed6b615aa8
- d0655066a51ec8f8d538f80f5fb21dde1bb1147b
- 7c0d31092df1ddc71638117e6be39887f470ffae
- 9b814bdf3464f63eff0c423368d4ccf3194271b1
- 63399765674bd3e3080b6ad2fbf716a8d8012319
- 8c1591af9ea8fa525e5be6ed75b3b053d1f9f0d1

We agreed that this approach is good enough for now, so I'm closing this bug.
