### ISSUE TITLE
Make ResolutionStorer implement the Factory API

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33534]

**Comment by stereotype441** [comment]
I've done some preliminary work on this in https://dart-review.googlesource.com/c/sdk/+/61420, but I'm going to put the rest of the work on hold until #33502 is finished, to avoid creating needless merge conflicts.

**Comment by bwilkerson** [comment]
I don't have any outstanding changes, and likely won't until tomorrow at the earliest. If you want to go ahead you can.

**Comment by stereotype441** [comment]
Fair enough.  I've sent the CL to you for review.

**Comment by stereotype441** [comment]
Completed in ee19f2804a54e526ff318d4c07fa4b580b7b7ce2
