### ISSUE TITLE
ensure important clients migrated to the new analyzer API

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33546]
todo: identify and list clients

- [ ] kythe (https://github.com/dart-lang/sdk/issues/31645)

/cc @scheglov @bwilkerson

**Comment by natebosch** [comment]
@devoncarew - can you update the issue or point to some documentation that explains what "Task model" means and what it's replacement is? I'd like to have somewhere to link to when I see code using AnalysisContext.
