### ISSUE TITLE
remove analyzer task model

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33544]

**Comment by devoncarew** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/33546.

**Comment by stereotype441** [comment]
This is currently blocked on #32454.

**Comment by stereotype441** [comment]
I've audited all the code remaining in `pkg/analyzer/lib/src/task` and `pkg/analyzer/lib/task`, and everything that remains is code that we need to keep.  The task model has been entirely removed.
