### ISSUE TITLE
remove analyzer support for non-strong mode / Dart 1.0

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33545]
In roughly this order:

- [x] deprecate the use of `strong-mode: true` in analysis_options.yaml files
- [x] ignore `strong-mode: false` in analysis_options.yaml files
- ~determine which (if any) of the options that can be nested under strong-mode will continue to be supported and how, and issue a deprecation warning for the old use (indicating the new use)~ (https://github.com/dart-lang/sdk/issues/32661)
- [x] have `analyzer-linux-release`, `analyzer-mac-release`, and `analyzer-windows-release` bots test in dart 2 mode
- [x] delete the `analyzer-strong-linux-release` / `analyzer-strong-window-release` / `analyzer-strong-mac-release` bots
- [x] in test.py, remove the `--strong` flag
- [x] have the `dartanalyzer --strong` flag complain if the user passes it in, and ignore the flag
- [x] update status files to remove the deprecated non-strong test exclusions
- [x] deprecate the `AnalysisOptions.strongMode` field; replace it with a deprecated constant getter and a no-op setter
- [x] delete analyzer non-strong specific tests
- [x] delete the `TypeSystemImpl` class and related code
- [x] code paths for `if (!strongMode)` can be deleted
- [x] remove the `dartanalyzer --strong` flag

**Comment by devoncarew** [comment]
@bwilkerson @scheglov @stereotype441 @MichaelRFairhurst @jmesserly Are there any missing tasks from the above / more specific details / anything that needs re-ordering? If so, feel free to note anything missing here or edit the first comment as necessary.

**Comment by bwilkerson** [comment]
> ignore strong-mode: false in analysis_options.yaml files

We should probably issue a warning if any options file uses `strong-mode` with a non-map value.

We should figure out which (if any) of the options that can be nested under `strong-mode` will continue to be supported and how, and issue a deprecation warning for the old use (indicating the new use).

> delete the TypeSystemImpl class and related code

I don't think we should do that until we see how things shake out after we've moved everything over to CFE. I don't think it's a huge benefit, and might introduce bugs.

**Comment by bwilkerson** [comment]
> just curious why not? Dart 1 type system will be dead code, right?

Yes, the Dart 1 type system will be dead. I didn't think about it until I saw your question, but we have two implementation classes, and this is only suggesting that we remove the one that should no longer be removed. So, yes, that should be fine.

> delete the AnalysisOptions.strongMode field

We should not remove the field, we should instead replace it with a constant getter and a no-op setter and mark them as deprecated. Otherwise it's a breaking change for clients.

**Comment by devoncarew** [comment]
I updated the lists above based on the discussion (deleting `TypeSystemImpl` and !strongMode code paths, and removing or deprecating `AnalysisOptions.strongMode` depending on the level of breaking change we decide we want).

**Comment by srawlins** [comment]
@scheglov I believe you deleted the `--strong` flag with analyzer 0.40.0. I suspect the other two unchecked items are complete, and we can close this issue.

**Comment by scheglov** [comment]
SGTM
