### ISSUE TITLE
Error on Future without type arguments

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33559]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)

`Dart VM version: 2.0.0-edge.f2eaf6aae78548a43946ba71e6581daada6a7b5b (Thu Jun 21 14:53:43 2018 +0000) on "macos_x64"`

```
/Users/scheglov/Applications/dart-sdk/bin/dart --enable-vm-service:53724 /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/test/fasta/strong_test.dart
Observatory listening on http://127.0.0.1:53724/

pkg/front_end/lib/src/fasta/testing/kernel_chain.dart:292:1: Error: No type arguments provided, 1 possible.
Future openWrite(Uri uri, f(IOSink sink)) async {
^^^^^^

Process finished with exit code 254
```

If I replace `Future` with `Future<void>`, then it works.
That's really strange.
There are hundreds of other places where `Future` is used without type arguments.

**Comment by srawlins** [comment]
Er, has this been seen any more? I suspect this was transient.

**Comment by scheglov** [comment]
I have not seen this since then.
