### ISSUE TITLE
Native extensions not loading under Windows with Dart 2

### ISSUE THREAD

**Issue by rytone** [dart-lang/sdk#33551]
Windows environment: Windows 10 x64 with Dart `2.0.0-dev.64.0`, `2.0.0-dev.63.0` with `--preview-dart-2`, and `1.24.3`
Linux environment: Arch Linux x64 with Dart `2.0.0-dev.63.0` with `--preview-dart-2`

Under Windows, using the sample extension included in the SDK (built with Visual Studio 2017 15.6.4), running `sample_synchronous_extension.dart` fails with the message `Native extension path must be absolute.error: library handler failed`. The extension works properly using Dart 1, and this issue also occurs with an extension I have written myself. Testing under Linux, everything works properly, even with Dart 2.

**Comment by anders-sandholm** [comment]
labelled area-vm for lack of a better label for native extensions

**Comment by tejainece** [comment]
Any updates on this one?

**Comment by DanTup** [comment]
Are there any workarounds for this? I just hit the same thing, and I also can't find any way to put an absolute path in there (`dart-ext:file:///` seems wonky, and also doesn't seem to work).

**Comment by mraleph** [comment]
@sjindel-google you mentioned that you are going to rework the implementation so I am moving this to you.

**Comment by DanTup** [comment]
@sjindel-google Just tested the sample extension on Windows with 2.1.0-dev.1.0 and it works fine now (on v2.0 it gives the error in the OP here). Thanks 👍
