### ISSUE TITLE
Dart Analyzer Error 					Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by sudipta213** [dart-lang/sdk#33554]
Analyzer Feedback from IntelliJ

**Comment by anders-sandholm** [comment]
@sudipta213 please provide more info/background on the error

**Comment by zoechi** [comment]
@anders-sandholm looks like #32496

**Comment by devoncarew** [comment]
Unfortunately I don't think this is actionable; we will need to address #32496.
