### ISSUE TITLE
Document that the VM temporarily doesn't support deferred loading checks

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33561]
The VM doesn't check when a deferred library is loaded, so access to deferred code works as if it was imported directly.

https://github.com/dart-lang/sdk/issues/33118 is tracking fixing the underling vm issue, but meanwhile we need to document where we are (likely Dart2Prerelease will be out without this implemented).

**Comment by kwalrath** [comment]
It looks like this is the only place that needs to be updated:

https://www.dartlang.org/guides/language/language-tour#deferred-loading
