### ISSUE TITLE
Analyzer requirements for outlines, annotations, and overall driving of the front end

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33567]
The analyzer needs to be able to do the following.  We are open to negotiation about exactly how much work is done on the analyzer side vs. in the front end itself:

- Incrementally compute library dependencies prior to analysis: given a file URI, and a filesystem abstraction that can be used to read the contents of the file, the analyzer needs to be able to find out either (a) that the file represents a part, or (b) the absolute URIs of all the libraries and parts that file refers to via import/export/part declarations.

- Compute the API signature of a file: given a file URI and a filesystem abstraction, the analyzer needs to be able to compute a cryptographic hash which encompasses all the ways in which the file contents might affect outline building.  (E.g. one could strip out comments, method bodies, and the initializer expressions of fields that are non-const and have explicit types, and then hash the remaining tokens with MD5).

- Drive outline building: given a library URI, a filesystem abstraction, and a way of retrieving previously built outlines that the library transitively depends on, the analyzer needs to be able to compute an outline of the library and its transitive dependencies, suitable for building into an element model.  Libraries whose outlines are supplied should not be re-parsed; files whose outlines are not supplied should be parsed from source.
  - Note that the analyzer simply supplies whatever outlines haven't been evicted from its cache, so it can't make any guarantee about the relationship between the outlines that are supplied; for example if the dependency chain is A <- B <- C <- D, it's possible that just the outline for B will be missing.
  - The outline information needs to be expressed in a form that can be serialized and deserialized so that the analyzer can cache it to disk.
  - Note that the analyzer may supply outline information that came from older versions of the files, provided that those files' API signatures have not changed.
  - The outline information needs to either contain the constant values of annotations, default parameters, const fields, and const top level variables, or it needs to contain enough information that these constant values can later be computed without needing to consult the original source file.
  - Note that we currently use the Component class to represent the outlines that are input and output to this process.  This mostly works, but it carries two disadvantages:
    - It doesn't support constant evaluation since it doesn't store the expressions for constants.
    - It requires us to fully deserialize and supply all known outlines prior to asking for a file to be analyzed, because we don't yet have a way to compute library dependencies prior to analysis (see above).

- Drive local file analysis of a library: given a library URI, a filesystem abstraction, and a way of retrieving previously built outlines of the library and its transitive dependencies, the analyzer needs to be able to compute an AST of the entire library contents (including nodes both inside and outside of method bodies).  It should not be necessary to parse any file from source other than the file being analyzed; everything else should come from the supplied outlines.
  - Note that we currently use the Component class to supply the outlines, and we remove the outline for the library being analyzed.  This is slightly wasteful--it would be better if the front end could take advantage of the supplied outline of the library being analyzed.

Optional future improvement:

- Drive local file analysis of a part: as above, but only analyze a single file of a multi-part library.  It should not be necessary to analyze all parts of a library at once.

- Drive local analysis of a method or initializer: as when driving local file analysis of a library, except that the analyzer only needs an AST for the body of a single method or the initializer of a single field.
  - As before, the analyzer may supply outline information that came from older versions of the files, provided those files' API signatures haven't changed.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
