### ISSUE TITLE
ExecutableElement has isAsynchronous, isGenerator, etc.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33566]
But this is body, and this information is not available from Kernel outlines.

@bwilkerson Maybe we should stop exposing this data from element model.

**Comment by bwilkerson** [comment]
I'd need to see whether / where the information is being used to answer that question.

**Comment by scheglov** [comment]
For now we use full kernels, but when we switch to outlines, we will have this problem again.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
