### ISSUE TITLE
Delete pub package "threejs_facade_test"

### ISSUE THREAD

**Issue by patlillis** [dart-lang/sdk#33562]
https://pub.dartlang.org/packages/threejs_facade_test

This was a temporary project that I was using to test some things. I didn't realize that there wouldn't be a way for me to delete it from pub.dartlang.org. There are no users, it's less than a week old, and clearly has the word "_test" in the name, so this shouldn't cause any problems.

I just found out about "publish_to: none" (https://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package), but alas it's too late :(

Thanks a lot for the help, much appreciated.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/pub#1935
