### ISSUE TITLE
VM/DDC and Dart2Js disagree about an `is` check for a torn off function

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33575]
I've narrowed this down as much as I can.

```dart
main() {
  // throws in Dart2JS because (List<String>) -> void is not a (List<dynamic>) -> void
  // does not throw in the VM or DDC
  new Bar<List>(new Specific()).foo(null);
}

class Foo<E> {
  void foo(E a) {}
}

class Bar<E> implements Foo<E> {
  final Foo<E> inner;

  Bar(this.inner);

  @override
  void foo(E a) {
    if (inner.foo is! Function(E)) throw 'sad';
  }
}

class Specific implements Foo<List<String>> {
  @override
  void foo(List<String> a) {}
}
```

The real world scenario is tearing off a function and passing it to a constructor.
https://travis-ci.org/dart-lang/collection/jobs/394385077#L589

**Comment by natebosch** [comment]
@sigmundch helped me narrow down the issue:

```dart
main() {
  print(new A().foo.runtimeType);
  print(new B().foo.runtimeType);
}

class Foo<E> {
  void foo(E a) {}
}

class A implements Foo<List<String>> {
  void foo(List<String> a) {}
}

class B {
  void foo(List<String> a) {}
}
```

VM prints:

```
(Object) => void
(List<String>) => void
```

dart2js print:

```
(List<String>) => void
(List<String>) => void
```

dart2js matches my intuition. Fixing this in VM and DDC will be breaking for code which works today, though its not clear how widespread it would be.

**Comment by dgrove** [comment]
@leafpetersen @lrhn @eernstg what should we do here?

**Comment by eernstg** [comment]
The first example shows that `dart2js` forgets to adjust the reified type of the tear-off `inner.foo` even though its parameter is covariant: A `print(inner.foo.runtimeType)` just before 'sad' yields `(List<String>) => void` with dart2js and `(Object) => void` with the vm, and the latter is correct.

The second example addresses the same problem more directly (the tear-off of `A.foo` doesn't get the right run-time type).

So this is a dart2js bug, and it just needs to be more thorough when it decides on which parameters are covariant.

**Comment by leafpetersen** [comment]
What @eernstg said.  When you tear off a method which (even indirectly) has  covariant parameters, the runtime type of those covariant parameters is `Object`, reflecting the fact that the implementation type of the method is necessarily more general than the interface type at which it is being read.

**Comment by sigmundch** [comment]
Mmm - may I ask, why is the covariant argument turned into `Object` and not some other type bound (for example a type derived from the super types?)

For example, in this code:
```dart
main() {
  var m = new A().foo;
  print(m.runtimeType);
}

abstract class F {
  foo(covariant int x);
}

class A implements F {
  void foo(int x) {}
}
```

The VM prints `(Object) => void`. Couldn't this be more precise and marked as `(int) => void`?

Similarly, when using type parameters, I was expecting the type to match at least the type provided by the type parameter interface. So if I did:
```dart
main() {
  var m = new A().foo;
  print(m.runtimeType);
}

abstract class F<E> {
  foo(E x);
}

class A implements F<num> {
  void foo(int x) {}
}
```

I could get `(num) => void`

**Comment by leafpetersen** [comment]
To your latter question, I consider this undesirable because it allows `x is T` to fail even when `x` has static type `T`. 

```
F<Object> a = new A();
void Function(Object) f = a.foo;
assert(f is! void Function(Object));
```

This isn't strictly a soundness issue, but is, I think, a bad outcome.

There is some broader discussion here about alternatives we considered for reification:

https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-from-class.md#alternatives

**Comment by johnniwinther** [comment]
A fix is in the pipeline: https://dart-review.googlesource.com/c/sdk/+/61924

**Comment by kevmoo** [comment]
66 test fixes – wow! https://dart-review.googlesource.com/c/sdk/+/61924/1/tests/language_2/language_2_dart2js.status
