### ISSUE TITLE
Determine how to support analyzer's need to create nodes for which there is no corresponding kernel representation

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#33571]
The Factory API currently provides the methods needed to create the kernel representations of code. The API has been made generic so that analyzer can return its own AST representations. But there are AST nodes to represent pieces of code that kernel only represents implicitly. For example, there is no kernel representation of the syntactic form of a type annotation, only the semantic representation of a `DartType`.

We need to figure out how we're going to support the creation of these additional AST nodes.

**Comment by devoncarew** [comment]
Related, a (currently internal only) [doc](https://docs.google.com/document/d/1zEMZQBdD9Az9bDrxFSyMWQ_C2k3SlorcKlM9xYHCvx4/edit#heading=h.wh65jxb58e2z
) about transmitting type information from the front end to the analyzer.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
