### ISSUE TITLE
Please improve error messages around const values

### ISSUE THREAD

**Issue by rkj** [dart-lang/sdk#33579]
For this incorrect code:
```
class A{}

final foo = new A();
const bar = foo;
```
While running in DartPad I get this error messages:

> Error compiling to JavaScript:
> main.dart:4:13:
> Error: Not a constant expression.
> 
> Error: Compilation failed.

While it's correct It's pretty hard to tell which part exactly is wrong, especially in more complex cases, for example when one of 5 arguments to a constructor is not const.

If the error said something like:
> Error: `foo` is not a constant expression

it would be much nicer.

**Comment by zoechi** [comment]
Might be a dup of #33438 ?

**Comment by sigmundch** [comment]
Thanks @zoechi , yes, I'll mark this as a duplicate.

Most errors are reported by the front-end, but constants are not evaluated in the FE, so each backend (dart2js, vm) has it's own evaluation logic and error reporting. This short error was produced by dart2js, we can use #33438 to track this.
