### ISSUE TITLE
Dart does not throw error when analyzer fails with "type_argument_not_matching_bounds" error for interface

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33585]
Dart SDK Version: 2.0.0-dev.64.1
OS: Windows 10 (64 bit)

The following test example produces type_argument_not_matching_bound in analyzer and passes with dart:

``` dart
abstract class B<X extends int> extends Object{}
class A implements B<List>{}

main() {
  A a = new A();
  print("Hello");
}
```
Sample output is:
```
D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound\inst_to_bounds>dartanalyzer test.dart
Analyzing test.dart...
  error - 'List' doesn't extend 'int' at test.dart:3:22 - type_argument_not_matching_bounds
  hint - The value of the local variable 'a' isn't used at test.dart:6:5 - unused_local_variable
1 error and 1 hint found.

D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound\inst_to_bounds>dart test.dart
Hello

D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound\inst_to_bounds>dart --version
Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"
```
I believe dart should throw error here.

This is similar with #33184, however analyzer error messages are different.

**Comment by iarkh** [comment]
I observe exactly the same with mixins - should I file a separate bug about this or this is the same issue?
Sample code is:
``` dart
class A {}
class B{}

class M<X extends A> {}
class O extends Object with M<B> {}

main() {}
```

**Comment by anders-sandholm** [comment]
@eernstg

**Comment by eernstg** [comment]
I've adjusted the area because the analyzer correctly reports the bound violation as a compile-time error, but the VM (presumably the common front end) fails to report it.

It may or may not be the same piece of code that detects these bound violations in the front end, so I'll leave it to the front end team to decide on how many issues they want for it.

**Comment by eernstg** [comment]
Searching for existing issues on this topic, I found this one: #33308. Closing this one as a duplicate thereof, adding a comment there about the examples given here.
