### ISSUE TITLE
Dartium archive zip file contain wrong version

### ISSUE THREAD

**Issue by apetracco** [dart-lang/sdk#33582]
In this archive
https://www.dartlang.org/tools/sdk/archive

we can find link for download Dartium new version (1.24.3) but zip file contain 1.24.2 version.

1.24.2 is expired so it's not possible to use  Dartium.

**Comment by anders-sandholm** [comment]
You can override the expiration using, e.g.,
export DARTIUM_EXPIRATION_TIME=1577836800; ./chrome-wrapper
(similar to what is explained in #33580)

Also, 1.24.3 and 1.24.2 Dartium are identical, so we're keeping the binary as is.
