### ISSUE TITLE
onError callback in runZoned should allow optional arguments

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33589]
runZoned with an onError callback matching `void Function(Object, [StackTrace])` used to get the stack trace, after https://github.com/dart-lang/sdk/commit/315a186dc4128a4f15cfb4a0c4f1ef6b42ccb866#diff-12fb606dfa5b73b9715d30ae9fa63c32R1471 it no longer does.

We used to check for the binary callback first which would match with an optional second argument.

This is causing a failure in `package:async` tests.

cc @lrhn

**Comment by lrhn** [comment]
That sounds like a bug.
Which platform are you running on?
