### ISSUE TITLE
Dartanalyzer does not throw compiler error when function variable with incorrect return type parameter is declared

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33597]
* Dart SDK Version: 2.0.0_dev.64.1
* OS: Windows 10

Here is a test example which demonstrates the failure:
``` dart
typedef F<X extends int> = X Function();
F<List>  myvariable;
main() {}
```
Function of `F` type can take only `int` parameters.
However, analyzer does not throw compiler error if I try to declare `F<List>` variable.
Dart also passes without any errors and warnings.
I believe compiler error should be thrown here.

Sample output is:
```
$>dart --version
Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"

$>dartanalyzer --preview-dart-2 test.dart
Analyzing test.dart...
No issues found!

$>dartanalyzer test.dart
Analyzing static_analysis_A01_t01.dart...
No issues found!

$>dart test.dart

$>
```

**Comment by eernstg** [comment]
We ought to create a separate issue for the VM (such that each team has their own issue to close when the implementation has been fixed).

**Comment by iarkh** [comment]
This is not reproducible in the build 2.0.0-dev.65.0

**Comment by eernstg** [comment]
Right, closing: All current tools implement these checks.
