### ISSUE TITLE
dfe.cc uses wrong path to find the front end snapshot.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#33590]
The `Platform::GetExecutableName` here: https://github.com/dart-lang/sdk/blob/master/runtime/bin/dfe.cc#L62

gives an incomplete path, causing GetDirectoryPrefixFromExeName() to return the empty string.

**Comment by zanderso** [comment]
One possibility is to create a version of `Platform::GetResolvedExecutableName()` that doesn't do scoped allocation. Another is to compute the snapshot path before `DFE::Init()` somewhere that has a scope available.

@a-siva @mkustermann @alexmarkov

**Comment by athomas** [comment]
This blocks rolling the checked in SDK to a Dart 2 version.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/62201 unblocks the rolling of checked in SDK (prebuilt version) to a Dart2 version.

**Comment by a-siva** [comment]
The remaining work on this issue is to fix the code which searches for snapshot to account for windows path separators.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/62260 to address https://github.com/dart-lang/sdk/issues/33590#issuecomment-400121475 is out for review
