### ISSUE TITLE
Dart Alice in Wonderland in the magical world of perfect language not used by the world. ?

### ISSUE THREAD

**Issue by DevJoseWeb** [dart-lang/sdk#33603]
https://www.linkedin.com/pulse/dart-alice-wonderland-magical-world-perfect-language-used-r-f-junior/

"The whole world went to Java or .Net.You still find C ++ coders in financial companies because their systems are built on it, but they're disappearing."

Dart initially had a mixed reception and the Dart initiative was criticized by some to fragment the web due to the original plans to include a Dart VM in Chrome. These plans were discarded to focus instead of compiling Dart to JavaScript. "Dart is the Java Script Woman" ????

**Comment by mraleph** [comment]
Issue tracker is place to report bugs, not a place to promote your blog posts.
