### ISSUE TITLE
Analyzer doesn't warn on invalid constant expression with a generic

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33612]
I don't know if there's another issue that covers this, but I couldn't see anything obvious. I'm working on some tests in `flutter_tools` but since it's a non-Flutter project it's using the VM directly (latest dev build - v2.0.0-64.1). I'm passing `--preview-dart-2` as an analyzer arg and a VM arg (since I don't think it's on my default when invoked directly):

```
Spawning /Users/dantup/Dev/dart-sdk/v2/bin/dart
    with args [
        "/Users/dantup/Dev/dart-sdk/v2/bin/snapshots/analysis_server.dart.snapshot",
        "--client-id=Dart-Code.dart-code",
        "--client-version=2.15.0-beta.1",
        "--preview-dart-2"
    ]
```

I wrote some code like this:

```dart
const isInstanceOf<T>()
```

Originally it had a type name in it, then I made it generic. I get no warnings on it, but when I run the code I get:

```
test/integration/flutter_tester_hot_reload_test.dart:91:34: Error: Not a constant expression.
  expect(ref, const isInstanceOf<T>());
                                 ^
```

Seems like the analyzer should pick this up?

<img width="1210" alt="screen shot 2018-06-25 at 3 15 17 pm" src="https://user-images.githubusercontent.com/1078012/41855615-ffd20144-788a-11e8-87f3-9e5476503125.png">

**Comment by lrhn** [comment]
It's a bug, you're doing the right thing.

The expression is not constant if it contains a type variable, so you can't use `const`.
If the analyzer tells you to use `const`, then it's misguided.
