### ISSUE TITLE
google_maps Error: 'IdentityCodec' is not a subtype of expected type 'Codec<String, dynamic>'

### ISSUE THREAD

**Issue by jbhsoftware** [dart-lang/sdk#33618]
Hello, 

I don't intend to create duplicate posts, but I fear my initial post may not get any attention where it is!

With that said, I'll keep it brief, I am having some kind of type issue that I cannot figure out how to fix.

Any guidance is appreciated, thank you!

[Link to my Question](https://github.com/a14n/dart-google-maps/issues/59)

[Link to Repro of Issue](https://github.com/jbhsoftware/google_address_autocomplete.git)

* Dart SDK Version (`dart --version`) 2.0.0-dev63.0
* OS- Windows 7 
* IDE-Webstorm
* Browser-Chrome

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by matanlurey** [comment]
It seems the repo is not compatible with the requirements of Dart2.

I'd keep your question at https://github.com/a14n/dart-google-maps/issues/59
