### ISSUE TITLE
support for git-worktree broken

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33619]
Several on the team use [git-worktree][1] for our day-to-day workflow.

This [recent change][2] on how to calculate the dart-vm version broke support for git-worktree.

Here are some additional details:

**why git-worktrees?**
Worktrees allow to have many local folders working on a single git repo. It makes it very easy to switch context between branches and share them across working spaces without having to push and pull them from multiple git repos. They also support having separate gclient files, so they can all get build and tested separately. This is especially useful to do some parallel work: one can run test suites on one branch, while developing on another.

**what broke?**

It's no longer possible to build the sdk inside a worktree.

**why things broke?**
The way worktrees are implemented, is that the main git repo has all the information for each worktree under the `.git` folder. Each linked worktree just has a directory under the main git repo's `.git/worktrees` folder. However, the worktree itself doesn't have a `.git` folder, instead it as a  `.git` file that says where the worktree folder is. For example:

```sh
git-repo/.git/ # a folder, the .git folder for the main git repo
git-repo/.git/worktrees/w1/  # a folder, a .git-like folder for the worktree w1
w1/.git  # a file, the contents point to git-repo/.git/worktrees/w1/
```

The breaking change assumes we can read a file under `.git/logs/HEAD`, this works in the default worktree, but fails in any other worktree where `.git` is a file and not a folder. Note there is a `logs/HEAD` file in the workspace's folder:

```sh
git-repo/.git/logs/HEAD # HEAD for the main git repo
git-repo/.git/worktrees/w1/logs/HEAD # HEAD for the w1 worktree.
```

@stereotype441 @zanderso 

[1]: https://git-scm.com/docs/git-worktree
[2]: https://dart-review.googlesource.com/c/sdk/+/48091

**Comment by jensjoha** [comment]
*ping* on this one --- is this something that's being fixed?

/cc @rmacnak-google
/cc @whesse

**Comment by sigmundch** [comment]
I kept using a patch on my local branch and every now and then keep getting bugged by this.

I created this patch https://dart-review.googlesource.com/c/sdk/+/127485 that uses the suggestion from @jensjoha, thoughts?

**Comment by sigmundch** [comment]
During the code-review with Zach, we came up with another idea, which is to keep the references to the .git logs, but make the location of the git folder configurable.

I have updated the CL, and once it lands you will be able to build under a git-worktree by doing:
```bash
echo "default_git_folder = \"../../sdk/.git/worktrees/wk1\"" >> out/ReleaseX64/args.gn
```

**Comment by jensjoha** [comment]
This command seems to work for me:
```
[ ! -d ".git" ] && cat .git | awk -F ":" '{print $NF}' | awk '{$1=$1};{print "default_git_folder = \"" $0 "\""}' >> out/ReleaseX64/args.gn
```
