### ISSUE TITLE
Dart2JS: `<Null>` allows heap unsoundness?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33613]
Reproduce in `-dev.63` in Dart2JS with `--preview-dart-2`:

```dart
void main() {
  var listOfNull = <Null>[];
  List<Object> listOfObject = listOfNull.toList();
  listOfObject.add(1);
  List<String> listOfString = listOfObject;
  listOfString.add('Hello World');
  // True
  print(listOfString is List<String>);
  // [1, 'Hello World']
  print(listOfString);
}
```

There are no static or runtime errors in this code snippet, but I end up having a statically typed `List<String>` that can be passed (and treated) as a `List<String>` but (a) has a reified type of `<Null>` not `<String>`, (b) passes the `is List<String>` test, and (c) contains an `int`.

Notably, if I add this line at the end:

```dart
  listOfString.map((v) => print(v)).toList();
```

I start getting runtime errors:

```
Uncaught exception:
TypeError: 1: type 'JSInt' is not a subtype of type 'String'
```

A few questions:

1. Why?
2. Why does `.map` with `print()` cause a `TypeError` but nothing else?

**Comment by matanlurey** [comment]
Here is the VM (running with Dart2):

```
dart /tmp/a.dart
Unhandled exception:
type 'int' is not a subtype of type 'Null' of 'value'
#0      List.add (dart:core/runtime/libgrowable_array.dart)
#1      main (file:///tmp/a.dart:4:16)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

... the VM catches `listOfObject.add(1)`, in this case.

**Comment by rakudrama** [comment]
This is the same issue as https://github.com/dart-lang/sdk/issues/33500 which is fixed.

```
TypeError: 1: type 'JSInt' is not a subtype of type 'Null'
    at Object.wrapException (o1.js:606:17)
    at Object.assertSubtypeOfRuntimeType (o1.js:1271:17)
    at Interceptor.add$1 (o1.js:420:11)
    at Object.main (o1.js:1866:27)
```

**Comment by matanlurey** [comment]
Oh wow thanks!
