### ISSUE TITLE
Enable `--omit-implicit-checks` (by default) in Dart2JS

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33615]
Internally, all applications and tests are run with `--omit-implicit-checks`.

In fact, AngularDart, for example _requires_ `--omit-implicit-checks`:
https://github.com/dart-lang/angular/blob/09ed555b1a75141406cb96e54f9807e704bed875/angular/lib/src/runtime/optimizations.dart#L25-L39

There are too many inconsistencies on how DDC treats implicit casts and JS interop (https://github.com/matanlurey/dart_js_interop#generic-type-arguments) to _not_ have this flag enabled. Optionally, we can make it just the default for `build_runner` and bypass having to make the SDK agree that this flag should be enabled.

/cc @jakemac53 @natebosch @kevmoo @rakudrama

**Comment by matanlurey** [comment]
Otherwise, AngularDart, externally, will need to ship with something like:

```dart
// angular.dar
runApp(...) {
  try {
    Object x = 5;
    String y = x;
  } catch (_) {
    throw '--omit-implicit-checks is required to use AngularDart';
  }
}
```

**Comment by matanlurey** [comment]
(Of course the other option is supporting an `unsafeCast` function in the SDK)

**Comment by natebosch** [comment]
By default we [turn on minify](https://github.com/dart-lang/build/blob/49d9d6e0cd03471fd249689936e4db23ff95e049/build_web_compilers/build.yaml#L47-L48)

We could add this argument by default. One thing to note is that we _don't_ merge argument defaults. If the user adds any of their own arguments we drop our defaults, so any user which does specify args would also need to specify `--omit-implicit-checks`.

@matanlurey - is there a link to some discussion about why Angular needs this flag?

**Comment by matanlurey** [comment]
It's _mainly_ for performance reasons (we cast from `dynamic` to `T` in hot-code).

It's also because of places like the infamous `eventHandler1`:

```dart
  void Function(E) eventHandler1<E, F extends E>(void Function(F) handler) {
    return (E event) {
      markPathToRootAsCheckOnce();
      appViewUtils.eventManager
          .getZone()
          .runGuarded(() => handler(unsafeCast<F>(event)));
    };
  }
```

... it's actually _not_ safe to check the type argument `F`. We changed it from `as F` to `unsafeCast<F>` (i.e. an implicit cast) specifically to avoid type checking event types, which can vary in browsers, be scripted, monkey-patched, etc.

You can also view my report at https://github.com/matanlurey/dart_js_interop#generic-type-arguments - there are too many inconsistencies between DDC and Dart2JS _without_ `--omit-implicit-checks`. We've only ever tested our code in either DDC or Dart2JS _with_ `--omit-implicit-checks` - I have no idea what else could fail at runtime.

**Comment by anders-sandholm** [comment]
not sure if this is a dart2js, ddc, or "build_runner" issue. Feel free to re-assign as you see fit.

**Comment by sigmundch** [comment]
My preference is that we don't enable `--omit-implicit-checks` by default in dart2js. It seems dangerous for projects that don't have good test coverage, and I'm afraid of people going off-rails because the compiler trusted an incorrect type.

I am more comfortable providing some kind of scoped version of this feature, though. This may be similar to `unsafeCast`, but more likely it will be a mechanism that lets you annotate a method with `@omitImplicitChecks`.

Until we implement that, enabling the omit flag on angular projects might be a possible intermediate step, but that feels like a build_runner issue. Is there a label for it here? Or do we need to move the bug to some other repo?

**Comment by natebosch** [comment]
> enabling the omit flag on angular projects might be a possible intermediate step

We don't have any way to enable it by default only for angular projects. What we'd end up with is enabling it by default for _everyone_ who doesn't have their own dart2js args specified. I'm not sure if that is much better than enabling it be default in dart2js

**Comment by sigmundch** [comment]
> We don't have any way to enable it by default only for angular projects.

Oh, bummer :( - I was initially thinking that the presence of certain source-generators in the build configuration could be used to decide whether to enable the flag, or the fact that you first compute dependencies and crawl the program to find all imports may give you a way to detect an angular dependency.

**Comment by matanlurey** [comment]
We could do that theoretically but I'm not sure it will be a good experience for our users. Similar to the issue filed by Patrice today it also means the spec compliant mode is virtually unused/tested.

**Comment by matanlurey** [comment]
edit: Untested outside of the SDK repo of course

**Comment by sigmundch** [comment]
+ @vsmenon - let's try to find some time to get together and decide how we want to proceed

**Comment by vsmenon** [comment]
If we move `unsafeCast` to `dart:js` / `dart:js_util` as an initial step, would that unblock you, @matanlurey ?  

We need to clean up the semantic inconsistencies around JS interop regardless.  Relying on `--omit-implicit-checks` is at best a bandaid for that.

**Comment by matanlurey** [comment]
We discussed this offline with @kevmoo and @ferhatb and team.

We could use `unsafeCast` for AngularDart specifically, but that won't help the ACX/AngularDart components, or other code paths. Let's sync offline?

**Comment by vsmenon** [comment]
@matanlurey and I chatted offline.  @matanlurey 's primary concern is that we're not testing sufficiently with our standard compiler options.  Our SDK tests are, but our internal tests all have extra flags.

I will close this and open a different thread on how we can improve our internal test signal.
