### ISSUE TITLE
Dart 2 boolean conversion must throw on non-boolean value.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#33611]
In Dart 1, "boolean conversion" allowed any object to be converted to `bool` in unchecked mode.
Dart 2 only has checked mode, and the required type of all the places that introduced boolean conversion is now `bool`, so it's alread a type error if the value isn't a subtype of `bool`.
That doesn't handle `null`, though. It's still not a boolean value, and it must be a runtime error if the value in a condition is `null`.

Dart 1 specified this as an assert, because in Dart 1 asserts were enabled in checked mode.
The Dart 2 specification of this has not been written yet, but it will say that it's a run-time error if the value is `null`.

Currently dart2js does not throw in that case. Run:
```dart
main() {
  bool x = null;
  if (x) print("yes");
  else print("no");
}
```
one dart2js with `--preview-dart-2`, and it prints "no".

**Comment by eernstg** [comment]
Note that as of 5fab3242f4716c6f14036019acbb55a3fefe282b there is no notion of boolean conversion any more, and it is a run-time error when `null` is encountered in those situations where boolean conversion used to be applied. This means that the above program should throw at `if (x) ..`, and it shouldn't print anything.

**Comment by zoechi** [comment]
Does this make #dart-lang/linter#1047 obsolete?

**Comment by zoechi** [comment]
@eernstg right, thanks for the explanation.

**Comment by fishythefish** [comment]
Closing in favor of #34147.
