### ISSUE TITLE
No error when run dart class with incorrect instantiation to bound for functions

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33625]
* Dart SDK Version: 2.0.0-dev.64.1
* OS: Windows10

The following simple code example demonstrates the problem:
``` dart
typedef F<X> = X Function();
typedef G<X extends F> = X Function();
main() {}
```
Sample output is:
```
$>dart --version
Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"

$>dartanalyzer test.dart
Analyzing test.dart...
  error - Type parameter bound types must be instantiated at test.dart:2:21 - strong_mode_not_instantiated_bound
1 error found.

$>dart test.dart

$>
```
Please see also comment from the bug 33184:
> However, the typedef example shows the opposite problem: dartanalyzer rejects the raw type F just because it is raw, and it should actually detect that F has simple bounds and hence it can be raw. It is likely that the VM does not yet implement the checks at all, so it's lucky to get the correct behavior in this case. ;-)

**Comment by anders-sandholm** [comment]
@eernstg

**Comment by eernstg** [comment]
@anders-sandholm, I'll just add a 'bug' label here: The analyzer should accept `X extends F` with the raw `F` because `F` has simple bounds, and since the type parameter of `F` is covariant, instantiate to bound should make that `F<dynamic>`. So it all fits together, and the analyzer just needs to accept it.

**Comment by stereotype441** [comment]
As of b3af151325d9aa17bf23d2151bcb1582861ac641, the analyzer accepts the repro case above without complaint.  If I'm understanding @eernstg's comment above, that's correct behavior, so this bug is fixed.
