### ISSUE TITLE
IntelliJ Debugging completely broken in dev-64

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/sdk#33620]
Attempting to debug even a new command-line project in IntelliJ didn't work on dev-64. 
After the first run, all subsequent runs never connected to the debugger.

But when I downgrade to dev-63, everything works just fine.

IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

**Comment by devoncarew** [comment]
@alorenzen, I can't repro (in `2.0.0-dev.65.0`). Can you re-confirm, or add repro steps?

I tried w/ a hello-world dart cli app, with and without async/await.

<img width="301" alt="screen shot 2018-06-26 at 12 57 12 pm" src="https://user-images.githubusercontent.com/1269969/41936090-ddec510e-7940-11e8-94a6-469411e577ef.png">

**Comment by srawlins** [comment]
Closing as not reproducible; please re-open if you encounter this again.
