### ISSUE TITLE
Negation of a void value produces no error

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33629]
This code produces no error with the analyzer:

```dart
void voidValue = false;

void main() {
  if (!voidValue) {};
}
```

cc @MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment]
Good catch, Leaf!

Should we put this in dart2stable so we can try to report this by then?

**Comment by leafpetersen** [comment]
Lower priority than other fixes, probably not a blocker.

**Comment by leafpetersen** [comment]
Yes, this should be an analyzer and CFE error.  I have no expectations one way or the other about what the VM does with invalid code.

**Comment by natebosch** [comment]
cc @dgrove - I think this needs to be in Dart2Stable since it will break otherwise working code.
