### ISSUE TITLE
Experimentally make DartType.element start returning `null` in situations where FE doesn't report a type; fix clients

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33634]
The existing analyzer design associates all `DartType` objects with an element.  Once the analyzer is integrated with the front end, we won't be able to do that, because the front end doesn't track an element associated with each type.  The only types we will be able to associate with elements are:
- Interface types will still be possble to associate with their class elements.
- Function types built from typedefs will still be possible to associate with their function elements.
- Type parameter types will still be possible to associate with their type parameter element.
- Dynamic will still be possible to associate with its singleton "element" (no front end support is needed for this, since the association between the single dynamic type and the single dynamic element can just remain hardcoded into the analyzer).

To prepare for switching over to the common front end, we want to make an experimental breaking change to the analyzer to cause `DartType.element` to return `null` in all sitations except the ones above.  Then we can start fixing clients to handle `DartType.element` being `null`.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
