### ISSUE TITLE
dartfmt --fix doesn't remove `new` from string interpolation expression

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33635]
`dartfmt --fix` is a wonderful feature!

Note that it currently fails to remove `new` from the following string interpolation expression:

```dart
    sink.write('FILE ACCESSED ${new DateTime.now()}\n');
```

cc @munificent @kwalrath

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/dart_style#707
