### ISSUE TITLE
Crash in DeclarationResolver._matchOffset

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#33632]
This function tries to set an offset on an Analyzer Element and fails if the Element already has an offset which is different.

After patching https://github.com/dart-lang/sdk/issues/33630 and https://github.com/dart-lang/sdk/issues/33631 and running `dartanalyzer --use-cfe` over `pkg/front_end/tool/_fasta/compile.dart` I observed this failure due to a ConstructorElement that had two different name offsets.  This just seems like a bug.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
