### ISSUE TITLE
Avoid the need to build function bodies twice

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33633]
In anticipation of being able to build resolved ASTs from judgments using the `Factory` API, @scheglov committed 4ebdb31646c15b896449b039dd3d517547ac9b1a last week, which changes things so that the analyzer first asks the kernel to build an outline of the program, then for each file to be analyzed in detail, requests full compilation of that file in order to obtain resolution data.  This had the negative consequence of breaking tests of annotations, default values, and toplevel variable initializers (since the kernel doesn't store information about these things in the outline).

Since we've decided to defer the work of building resolved ASTs from judgments, we need to get these tests passing again; we're planning to do that by having the analyzer do a full compilation step initially (instead of building just the outline); then for each file to be analyzed it will request a full compilation again.  This means that function bodies will be built twice.

This issue is a reminder that we need to get rid of this redundancy.

**Comment by scheglov** [comment]
I had to revert separation of `getOutline()` and `getResolution()` in `FrontEndCompiler`.
https://dart-review.googlesource.com/c/sdk/+/62666

So, now we do less work overall, but with responsiveness is less.
We need to remember to keep this in mind while later evaluating performance and responsiveness.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
