### ISSUE TITLE
Make the resolution applier resilient to missing keys

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#33631]
When running dartanalyzer --use-cfe (over the front end, dart2js, and the analyzer itself) after working around https://github.com/dart-lang/sdk/issues/33630, the resolution applier will fail when it tries to look up a key in the resolution store and does not find it.

I worked around this by returning `null` for these by turning the `throw` in `ResolutionApplier._get` into `return null`.  That will require hardening a lot of code in the resolution applier to be resilient to `null` which we don't expect to deal with in the long term.  It would be better to produce a `ResolutionData` that is a safe default for missing data, but I don't know if that's even possible.

This blocks running dartanalyzer --use-cfe.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
