### ISSUE TITLE
Make the resolution storer resilient to duplicate keys

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#33630]
Running the command-line analyzer with --use-cfe (over the front end, dart2js, and the analyzer itself), it can fail when it attempts to record resolution information for Kernel nodes that do not have a file offset.  The failure is due to the code which verifies that we do not overwrite resolution information, when it sees a second Kernel node without a file offset.

It can be fixed by changing `throw` to `return` in `_ResolutionStorer._store` which has the effect of ignoring subsequent stores with the same key.

This prevents running dartanalyzer --use-cfe.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
