### ISSUE TITLE
Inconsistent declarations of method with tightened types

### ISSUE THREAD

**Issue by aemino** [dart-lang/sdk#33640]
Version/Platform: Dart 2.0.0-dev.65.0 / Windows x64

Given the following code...
```dart
abstract class MixinA {
  num method(num n) => null;
}

abstract class MixinB<T, S> {
  T method(covariant S n) => null;
}

abstract class ClassA extends Object with MixinA, MixinB<num, num> {} // works
abstract class ClassB extends Object with MixinA, MixinB<int, num> {} // works
abstract class ClassC extends Object with MixinA, MixinB<num, int> {} // works
abstract class ClassD extends Object with MixinA, MixinB<int, int> {} // doesn't work
// Inconsistent declarations of 'method' are inherited from (int) → int, (num) → num.
```

Only the last class declaration throws an error.  Is this the intended behavior?  I also wonder if the WIP proposal for interface conflict resolution is related to this.

**Comment by lrhn** [comment]
I don't think there should be any error here. 
The error comes from the analyzer, and not from the common front-end, so it's the analyzer being too restrictive.

The fourth case is overriding
```dart
  num method(num n) => null;
```
with
```dart
  int method(covariant int n) => null;
```
and that is a perfectly valid override - the return type is more specific, which is fine, and the parameter type is marked covariant, so it's also fine that it's more specific.

**Comment by srawlins** [comment]
If I change the methods to throw, instead of return null, to get around null-safety, analyzer now reports no errors.
