### ISSUE TITLE
Redirecting factory cycle is a compile-time error

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#33649]
The spec currently says (in section 10.6.2): "It is a run-time error if a redirecting factory constructor redirects to itself, either directly or indirectly via a sequence of redirections."

This should be a compile-time error.

**Comment by eernstg** [comment]
It sounds uncontroversial to make it a compile-time error, but it was apparently adjusted to be a run-time error because of deferred libraries. Can we be certain that no such difficulties exist today?

I'll add area-language. @lrhn, @leafpetersen, do you have any worries about this change?

**Comment by eernstg** [comment]
Closing: As of 9282a34aea73e20faf1674f797ef44dd88ad8181, this is specified as a compile-time error.

**Comment by eernstg** [comment]
Re-opening, 9282a34aea73e20faf1674f797ef44dd88ad8181 fixes a number of things, but not exactly the topic of this issue.

**Comment by eernstg** [comment]
This is being addressed by [an upcoming CL](https://dart-review.googlesource.com/c/sdk/+/51323).

**Comment by eernstg** [comment]
[Said CL](https://dart-review.googlesource.com/c/sdk/+/51323) has landed, and the language specification now says this:

```
A redirecting factory constructor $q'$ is {\em redirection-reachable}
from a redirecting factory constructor $q$ if{}f
$q'$ is the redirectee constructor of $q$,
or $q''$ is the redirectee constructor of $q$
and $q'$ is redirection-reachable from $q''$.
It is a compile-time error if a redirecting factory constructor
is redirection-reachable from itself.
```
