### ISSUE TITLE
Analyzer issue with optional new and generic types on methods.

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#33647]
In the following code:

```dart
import 'dart:async';

var a = new Future<int>.sync(() => 3).then<int>((e) => e);
var b = Future<int>.sync(() => 3).then((e) => e);
var c = Future<int>.sync(() => 3).then<int>((e) => e);
```
`dartanalyzer` displays errors on `c` variable because of the type argument on `.then`.

```
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.65.0
$ cat bin/test.dart
import 'dart:async';

var a = new Future<int>.sync(() => 3).then<int>((e) => e);
var b = Future<int>.sync(() => 3).then((e) => e);
var c = Future<int>.sync(() => 3).then<int>((e) => e);
$ dartanalyzer bin/test.dart
Analyzing bin/test.dart...
  error • The operator '<' isn't defined for the class 'Function' at bin/test.dart:5:39 • undefined_operator
  error • Expected to find ';' at bin/test.dart:5:40 • expected_token
  error • Expected a method, getter, setter or operator declaration at bin/test.dart:5:43 • expected_executable
  error • Unexpected text '>' at bin/test.dart:5:43 • unexpected_token
  error • Undefined class 'e' at bin/test.dart:5:46 • undefined_class
  error • Unexpected text ')' at bin/test.dart:5:47 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at bin/test.dart:5:47 • expected_executable
  error • Undefined class 'e' at bin/test.dart:5:52 • undefined_class
  error • Unexpected text ')' at bin/test.dart:5:53 • unexpected_token
  error • The name '' is already defined at bin/test.dart:5:53 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at bin/test.dart:5:53 • expected_executable
11 errors found.
```

**Comment by bwilkerson** [comment]
@danrubel Could you check this on the fasta parser?

**Comment by mit-mit** [comment]
tagging P1, this is blocking https://github.com/flutter/flutter/issues/18604

**Comment by devoncarew** [comment]
@a14n, thanks for the reduced case! I'm curious, where did this occur in the Flutter codebase?

**Comment by a14n** [comment]
https://github.com/flutter/flutter/blob/34238f54ebb5a8c398df2335745db1640a42e061/packages/flutter_tools/lib/src/commands/daemon.dart#L182-L196

**Comment by danrubel** [comment]
The fasta parser correctly handles this case where as the old parser does not.
I added some [new parser tests](https://dart-review.googlesource.com/c/sdk/+/64200) to assert this.
I don't know if we want to fix the old parser.

**Comment by bwilkerson** [comment]
If we're going to move to the fasta parser as quickly as I think we will, then it probably isn't worth fixing the old parser.

**Comment by dgrove** [comment]
I agree, @bwilkerson . Moving to Dart 2.1 milestone.

**Comment by mit-mit** [comment]
cc @dgrove this one is blocking https://github.com/flutter/flutter/issues/18604 which in turn is blocking https://github.com/dart-lang/sdk/issues/32596m which is 2.0 stable. 

If we were to punt this, when would we get the needed support via fasta?

**Comment by devoncarew** [comment]
This would likely happen soon after the dart 2 branch, in the neighborhood of days after.

**Comment by mit-mit** [comment]
Do we know if Flutter would track the master or stable branch?

**Comment by devoncarew** [comment]
I assume Flutter will continue to track Dart SDK dev releases; pinging @tvolkert and @Hixie.

**Comment by Hixie** [comment]
@cbracken and @a-siva are probably the appropriate people to make that call.

**Comment by a-siva** [comment]
Yes we will continue to actively roll Dart from top of tree into Flutter on a regular basis.

**Comment by devoncarew** [comment]
To update, this is blocked on https://github.com/dart-lang/sdk/issues/33543.

**Comment by dgrove** [comment]
#33543 has been closed. Can this be?
