### ISSUE TITLE
CFE prints strange error if top-level var is called `library`

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#33654]
Consider this code (SDK 2.0.0-dev.65.0)
```
var library;
main(){}
```
- Analyzer sees no problems
- VM prints `Error: A class member can't have the same name as the enclosing class.`

Expected:
- VM and Analyzer agree regarding validity of this code
- If this code is errorneous indeed then I guess the VM error message should be more clear

Related issue: https://github.com/dart-lang/sdk/issues/24375

**Comment by lrhn** [comment]
The word `library` is a built-in identifier. That means that it can't be the name of a type or prefix, but nothing prevents the declaration above. The program is correct and should be accepted.

**Comment by alexander-doroshko** [comment]
@lrhn Thanks for the clarification!
Can you please also have a look at https://github.com/dart-lang/sdk/issues/24375? I guess VM is right there but analyzer needs to be fixed.

**Comment by srawlins** [comment]
The program is now accepted by the VM, dart2js, and analyzer. Is there another way to reproduce the error message that needs improving?

**Comment by askeksa-google** [comment]
Closing as fixed.
