### ISSUE TITLE
Address Meteor benchmark regression

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33656]
12c461b15ae3ad4c503db256cd08f0fe1d66ee34 regressed Meteor in AOT v2 mode by 30% - and this regression is not recovered yet.

**Comment by aartbik** [comment]
With the latest 32-bit generalization of improving typed data setter/getter performance, expect the 32-bit performance of Meteor to drop too. Things have to become worse before they get better.... :-)

**Comment by aartbik** [comment]
Although the original plan was to recover the drop using a new number analysis phase, only one or two operations are really responsible for the huge performance drop. So in the meanwhile, perhaps a very simple heuristic can recover the performance without regressing elsewhere.

**Comment by aartbik** [comment]
Performance back to where it was (or better).
Sample result:
```
JsonParseCustomReviver (Intel Xeon)   +7.040%
Meteor (Intel Core i5)               +41.07%
```
