### ISSUE TITLE
RegExp strange results

### ISSUE THREAD

**Issue by alescdb** [dart-lang/sdk#33669]
* Dart SDK Version (`dart --version`)
**Dart** VM version: 2.0.0-dev.65.0 (Unknown timestamp) on "linux_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
**Linux**

I'm trying to parse a javascript array with Dart VM and RegExp, but it does not match :

The JS I'm trying to parse :
```
var xxx = new Array("AAAA","BBB")
```

With grep, results looks good to me :
```
bash> grep -Eo "\(([^\)]*)\)"  test.js 
("AAAA","BBB")
```

Same in PHP :
```
<?php
$js = 'var xxx = new Array("AAAA","BBB")';
preg_match("/\(([^\)]*)\)/", $js, $m);
print_r($m);
```

will give :
```
Array
(
    [0] => ("AAAA","BBB")
    [1] => "AAAA","BBB"
)
```

But in dart I got strange results  :
```
main() {
  String js = 'var xxx = new Array("AAAA","BBB")';
  RegExp regexp = new RegExp('\(([^\)]*)\)');

  var match = regexp.firstMatch(js);
  if (match != null) {
    for (int i = 0; i < match.groupCount; i++) {
      print("[$i] => ${match.group(i)}");
    }
  }
}
```

results :
```
[0] => var xxx = new Array("AAAA","BBB"
[1] => var xxx = new Array("AAAA","BBB"
```

**Comment by lrhn** [comment]
Your argument to the `RegExp` constructor is just a string literal, and the backslashes are recognized by the string as an escape, so the actual string you pass is `"(([^)]*)))"'.

To avoid backslashes being interpreted as string escapes, you can use a raw string;
```dart
RegExp regexp = new RegExp(r'\(([^)]*)\)');
```
or (to fiddle with the regexp) even shorter:
```dart
RegExp regexp = new RegExp(r'\((.*?)\)');
```

So, the behavior is correct, you are just no using the RegExp you expected.

**Comment by alescdb** [comment]
My bad, Thanks !
Maybe the lint rule `valid_regexps` should warn about this ?
