### ISSUE TITLE
VM: Long CheckClass chains

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#33664]
dart2js (running from snapshot) has the following code for [`instruction.next`](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/ssa/optimize.dart#L213).

```
              ;; CheckClass:24(v8 T{Type: class 'HInstruction'} Cids[17: HTypeInfoExpression etc.  cid 1389-1404 | HLocalValue etc.  cid 1406-1410 | HBitNot etc.  cid 1412-1414 | HLessEqual etc.  cid 1417-1421 | HBitXor etc.  cid 1423-1427 | HRemainder etc.  cid 1429-1434    
0x7fe6f7508676            testb rcx,1    
0x7fe6f7508679            jz 0x00007fe6f7508ce5    
0x7fe6f750867f            movzxwq rdx,[rcx+0x1]    
0x7fe6f7508684            addl rdx,0xfffffa93    
0x7fe6f750868a            cmpl rdx,0xf    
0x7fe6f750868d            jna 0x00007fe6f750874a    
0x7fe6f7508693            addl rdx,-0x11    
0x7fe6f7508696            cmpl rdx,4    
0x7fe6f7508699            jna 0x00007fe6f750874a    
0x7fe6f750869f            addl rdx,-6    
0x7fe6f75086a2            cmpl rdx,2    
0x7fe6f75086a5            jna 0x00007fe6f750874a    
0x7fe6f75086ab            addl rdx,-5    
0x7fe6f75086ae            cmpl rdx,4    
0x7fe6f75086b1            jna 0x00007fe6f750874a    
0x7fe6f75086b7            addl rdx,-6    
0x7fe6f75086ba            cmpl rdx,4    
0x7fe6f75086bd            jna 0x00007fe6f750874a    
0x7fe6f75086c3            addl rdx,-6    
0x7fe6f75086c6            cmpl rdx,5    
0x7fe6f75086c9            jna 0x00007fe6f750874a    
0x7fe6f75086cf            cmpl rdx,7    
0x7fe6f75086d2            jz 0x00007fe6f750874a    
0x7fe6f75086d8            addl rdx,-9    
0x7fe6f75086db            cmpl rdx,2    
0x7fe6f75086de            jna 0x00007fe6f750874a    
0x7fe6f75086e4            addl rdx,-4    
0x7fe6f75086e7            cmpl rdx,1    
0x7fe6f75086ea            jna 0x00007fe6f750874a    
0x7fe6f75086f0            addl rdx,-3    
0x7fe6f75086f3            cmpl rdx,3    
0x7fe6f75086f6            jna 0x00007fe6f750874a    
0x7fe6f75086fc            cmpl rdx,5    
0x7fe6f75086ff            jz 0x00007fe6f750874a    
0x7fe6f7508705            addl rdx,-7    
0x7fe6f7508708            cmpl rdx,5    
0x7fe6f750870b            jna 0x00007fe6f750874a    
0x7fe6f7508711            addl rdx,-7    
0x7fe6f7508714            cmpl rdx,3    
0x7fe6f7508717            jna 0x00007fe6f750874a    
0x7fe6f750871d            addl rdx,-5    
0x7fe6f7508720            cmpl rdx,4    
0x7fe6f7508723            jna 0x00007fe6f750874a    
0x7fe6f7508729            addl rdx,-6    
0x7fe6f750872c            cmpl rdx,1    
0x7fe6f750872f            jna 0x00007fe6f750874a    
0x7fe6f7508735            addl rdx,-4    
0x7fe6f7508738            cmpl rdx,2    
0x7fe6f750873b            jna 0x00007fe6f750874a    
0x7fe6f7508741            cmpl rdx,7    
0x7fe6f7508744            jnz 0x00007fe6f7508ce5    
  ;; v19 <- LoadField(v8 T{Type: class 'HInstruction'}, 64 {next} [nullable dynamic], immutable=0) T{Type: class 'HInstruction'?}    
0x7fe6f750874a            movq rdx,[rcx+0x3f]
```

The code seems to exclude a lot of little holes in a ~90 class hierarchy.

1. Can the VM do something to tell that the holes are actually in the hierarchy? One possible reason for holes is abstract classes. Another is that some elements of the hierarchy are rare. We don't care about a false positive for the abstract class since there cannot be an instance.

2. If the set of Cids must be checked as-is, a table of ~90 bytes would be fewer instructions, fewer branch mispredictions, and about the same bytes, e.g. something like:

```
movzxwq rdx,[rcx+0x1]	
addl rdx,0xfffffa93
cmpl rdx,90
ja deopt
lea r11,[rip+xxx]
test [r11+rdx],1
jz deopt
```

/cc @mraleph

**Comment by mraleph** [comment]
There are three problems here (potentially in reverse order of importance to solve them):

1. There are code paths in the call specializer that emit polymorphic `CheckClass` instructions without applying any sort of cids range expansion that we apply to polymorphic calls. The holes you see are simply never observed classes. However even this expansion would not fully help here because CID expansion algorithms that we have require classes to be finalized and classes are not finalized in app-jit training unless they are actually allocated - meaning that some holes will nevertheless remain. 
2. Backend code pattern for `CheckClass` is inefficient and should indeed balance between using code driven and data driven approaches. 
3. These `CheckClass` instructions are redundant to begin with given the strong mode: `HInstruction` is non-interface type and no subclass overrides `get:next` - meaning that `CheckClass` should be replaced with `CheckNull` instead.

**Comment by mraleph** [comment]
@aartbik Aart, could you look into using static type information better in the JIT pipeline (e.g. eliminating check classes like the one above)?

**Comment by aartbik** [comment]
Small stand-alone reproducer:

abstract class A {
  A next;
}
class B extends A {
  B(A n) {
    this.next = n;
  }
}
abstract class C extends A {
}
class D extends C {
  D(A n) {
    this.next = n;
  }
}

yields for:

  while (i != null) {
    A next = i.next;
    ....
    i = next;
  }

this code:

        ;; CheckClass:24(v6 T{!null} Cids[2: B etc.  cid 1025 | D etc.  cid 1027])
0x7fbe4683bab4    f6c101                 testb rcx,1
0x7fbe4683bab7    0f8472000000           jz 0x00007fbe4683bb2f
0x7fbe4683babd    480fb75101             movzxwq rdx,[rcx+0x1]
0x7fbe4683bac2    81fa01040000           cmpl rdx,0x401
0x7fbe4683bac8    740c                   jz 0x00007fbe4683bad6
0x7fbe4683baca    81fa03040000           cmpl rdx,0x403
0x7fbe4683bad0    0f8559000000           jnz 0x00007fbe4683bb2f
        ;; v13 <- LoadField(v6 T{!null}, 8 {next} [nullable dynamic]) T{Type: class 'A'?}
0x7fbe4683bad6    488b5107               movq rdx,[rcx+0x7]

**Comment by aartbik** [comment]
With AOT, right after ComputeSSA:

B3[target]:20
    PushArgument(v4)
    CheckNull:24(v4)
    v11 <- StaticCall:26( get:next<0> v4)

In contrast, JIT, right after ComputeSSA:

B3[target]:20
    PushArgument(v6)
    v13 <- InstanceCall:24( get:next<0>, v6 IC[2: D cnt:1 trgt:'A.get_next' | B cnt:1 trgt:'A.get_next'])

**Comment by mraleph** [comment]
@aartbik the difference between AOT and JIT is due to AOT running global closed world analysis passes on Kernel before invoking VM compilation pipeline.

**Comment by aartbik** [comment]
For sure, I just including the AOT and JIT code for the smaller example to contrast the differences that exist right now. The goal is to make JIT behave as good as the closed world case while staying safe wrt subtleties of dynamic class loading.

**Comment by aartbik** [comment]
A quick prototype yields the same code for JIT (by adding a CHA deopt clause on class A):

<no checks>
;; v11 <- LoadField(v4 T{Type: class 'A'}, 8 {next} [nullable dynamic]) T{Type: class 'A'?}
0x7fdb19d712ea    488b5107               movq rdx,[rcx+0x7]

and yields about 10% improvement on the standalone reproducer (which has just two holes in the sparse type hierarchy).

Codesize and runtime improvements for just the core loop in dart2js  should be even better (do you have a particular command line invocation you want me to check specifically?).

**Comment by sigmundch** [comment]
@aartbik - Stephen is out on vacation, but I'd be happy to help try it out in dart2js.

He probably came across this by profiling dart2js during our SSA-optimizations. We have a couple compile-time benchmarks you can try in golem, but I can also try it out on a large application and let you know if I see some measurable difference there. Do you have a CL I can patch in?

**Comment by mraleph** [comment]
We can just start by uploading to Golem and looking if anything improves on dart2js-compile target.

**Comment by aartbik** [comment]
I started a golem run. In the meanwhile, you can try out the patch:

https://dart-review.googlesource.com/c/sdk/+/64440

Still, I would be interested in the exact way of invoking dart2js so that optimize.dart is exercised. In my runs of dart2js (on other dart code or on patch), this code is never run.

**Comment by sigmundch** [comment]
Will do, thanks!

It is always enabled :) - could it be matter of getting a complex enough input program?

**Comment by aartbik** [comment]
Thanks for the hints. I was able to exercise some of the methods through JIT. Strangely enough not the visitBasicBlock shown above, but at least the very similar method below.

`optimize.dart_SsaCheckInserter_visitBasicBlock`

which looks like

```
 while (instruction != null) {
      HInstruction next = instruction.next;
      instruction = instruction.accept(this);
      instruction = next;
    }
```

When JITted, the intermediate on input for the next getter looks like:

```
     v11 <- InstanceCall:24( get:next<0>, v6 IC[
        55: HParameterValue cnt:1326 trgt:'HInstruction.get_next' |
              HConstant cnt:2700 trgt:'HInstruction.get_next' |  **very long list** )
```

Before this would expand to a very long chain. But with the new improvement, the while loop (which enables removing the CheckNull) goes directly into the LoadField:

```
        ;; Branch if StrictCompare:12(!==, v6, v0) T{bool} goto (3, 4)
0x7fae196a97c1    493b4668               cmpq rax,[thr+0x68]   null
0x7fae196a97c5    0f848f020000           jz 0x00007fae196a9a5a
        ;; B3
        ;;   Loop 0
        ;; v11 <- LoadField(v6 T{Type: class 'HInstruction'}, 64 {next} [nullable dynamic]) T{Type: class 'HInstruction'?}
0x7fae196a97cb    488b483f               movq rcx,[rax+0x3f]

```

**Comment by aartbik** [comment]
Golem runs are mainly in the noise, even for dart2js-compile (but unsure at this point if that exercises the ssa code above). As expected, however, the microbenchmark that targets this specific case improves quite a bit (and this one "only" has two "holes" in the class hierarchy):

```
x86:
NextLoop (Intel Core i5)   2.861%
NextLoop (Intel Xeon)      5.721%

ia32:
NextLoop (Intel Core i5)   7.131%
NextLoop (Intel Xeon)     17.91%

armv7:
NextLoop (Odroid-C2)      58.15%

armv8:
NextLoop (Odroid-C2)      55.71%

```

**Comment by aartbik** [comment]
Investigating the "deopt storm". Without background threads I see, for example the following method compiled twice in unopt mode (once per test run):

Compiling  unopt : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling  unopt : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.

With background threads, the same method goes into some sort of compilation loop, clearly in some nasty interaction with CHA.

Compiling  unopt : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
....
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling opt  : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.

**Comment by aartbik** [comment]
The cycle actually involves two methods, and it is not so much a "deopt storm" as a "recompilation storm" (but of course due to CHA). Both are compiled in the background, and on the same isolate, but both compilations fail, and, even though both are marked with

`function.set_is_background_optimizable(false);`

failure of one seems to trigger the other right away, round and round we go.
```
Compiling JIT opt : dart:io__File@14069316_open_<anonymous closure> on isolate vm-service 0x55d1cc76a900
  do not compile again background: dart:io__File@14069316_open_<anonymous closure>
Compiling JIT opt : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316. on isolate vm-service 0x55d1cc76a900
  do not compile again background: dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316.
Compiling JIT opt : dart:io__File@14069316_open_<anonymous closure> on isolate vm-service 0x55d1cc76a900
  do not compile again background: dart:io__File@14069316_open_<anonymous closure>
Compiling JIT opt : dart:io__RandomAccessFile@14069316__RandomAccessFile@14069316. on isolate vm-service 0x55d1cc76a900
```

**Comment by aartbik** [comment]
I have a fix for the cycle. Two functions remained in the queue of a background thread, but even though set_is_background_optimizable was reset, it kept on looping in this thread rather than releasing it and let the foreground thread take it from there.

This fixes the timeout consistently. Even with this, however, the test sometimes fails as follows, which must be addresses too.
```
'Uint8List' is not a subtype of type 'String' of 'string'
>testee>err> #0      Utf8Encoder.convert (dart:convert/utf.dart) 
```

**Comment by aartbik** [comment]
With the looping out of the way, this was easy to debug. Both AOT and JIT rely on ICData in subsequent codegen, which can be a mismatch with the static class determined by the new code. For now, I added a bail in such (rare but possible) cases. In the long run we may want to rely on statically determined information instead!
