### ISSUE TITLE
Please roll dart_style to 1.1.1 in the SDK

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#33663]
Sorry the churn! I know you just rolled 1.1.0. After that happened, @chalin discovered that `--fix` doesn't work inside string interpolation (https://github.com/dart-lang/dart_style/issues/707). I wanted to address that before I announced `--fix`.

This doesn't change the behavior of dartfmt very much, but it may affect a few things in the SDK, so it would be good to roll it with the prebuilt SDK. If you don't mind adding this to the CHANGELOG, I would appreciate that too:

```
  * Format expressions inside string interpolation.
```

Thank you!

**Comment by munificent** [comment]
Ping?

**Comment by munificent** [comment]
It is valid and it is harder to read. That's why I avoided formatting inside interpolations for so long.

But my current thinking is that it's OK that it's harder to read — that's a signal to you to reorganize your string so that it fits within the line length limit.

**Comment by munificent** [comment]
Yeah, so what's going on here is the expected behavior.

I avoided formatting inside interpolation for a long time specifically because this. When it does wrap, it tends to look bad.

But the only time it should wrap, as it's doing here, is when it can't wrap anywhere else. In that case, if it looks bad, it's a signal to you to reorganize the code or split up the string literal so that it doesn't *have* to wrap in the first place. dartfmt will do everything it can to fit code inside the line limit.

**Comment by a14n** [comment]
IMHO a wrap should never happen in String interpolations. This makes the code really hard to read (especially for uri-like String or in multiline Strings)

```dart
var a = [];
f(o) => null;

var s01 =
    '         $a                                                               ';
var s02 =
    '         ${a}                                                             ';
var s03 =
    '         ${a.length}                                                      ';
var s04 =
    '         ${f(a)}                                                          ';
var s05 =
    '         ${a.map(f).toList()}                                             ';
var s06 =
    '         ${a.map((e)=>'').toList()}                                       ';

var s07 = '''
         ${a.length}                                                            end
''';
```

is formatted to

```dart
var a = [];
f(o) => null;

var s01 =
    '         $a                                                               ';
var s02 =
    '         ${a}                                                             ';
var s03 = '         ${a
    .length}                                                      ';
var s04 = '         ${f(
    a)}                                                          ';
var s05 = '         ${a
    .map(f)
    .toList()}                                             ';
var s06 = '         ${a
    .map((e) => '')
    .toList()}                                       ';

var s07 = '''
         ${a
        .length}                                                            end
''';
```

`s07` is my main concern.

I really like to see dart code inside interpolation been formatted but I really think it should be formatted without wrapping. (The bad code signal can be provided by the lint `lines_longer_than_80_chars`)

**Comment by munificent** [comment]
Yeah, in retrospect, I think you're right. I'm working on seeing if I can format interpolations but avoid wrapping them now. If it's possible, I'll kick out a 1.1.2 release of dart_style soon.

**Comment by chalin** [comment]
FYI, for the use cases that I faced, I liked the interpolation reformatting. In cases where it wrapped, it was because my lines were too long, so I broke them at more meaningful points my self (but at least the formatter was letting me know the strings were too long).

E.g.,

```dart
foo(
  'some ... ${very.long} string');

// rewritten as

foo(
  'some ... '
  '${very.long} string');
```

**Comment by munificent** [comment]
Yes, you generally should fix the string so that it fits in the line length. But when it doesn't, I think it's better for dartfmt to leave the line long than to jam some heinous line break inside the interpolation.

In particular, in multi-line strings, you may *want* the long lines.

**Comment by chalin** [comment]
Makes sense.
