### ISSUE TITLE
Analyzer/CFE inconsistency on super calls to abstract methods.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33662]
Consider this code:

```dart
abstract class Foo {
  String get attribute;
}

abstract class Bar implements Foo {
}

class Baz extends Bar {
  String get attribute => super.attribute;
}

void main() {
  new Baz();
}
```

When run with the CFE, this produces the following:

```
tmp/ddctest.dart:14:33: Error: Superclass has no getter named 'attribute'.
  String get attribute => super.attribute;
                                ^^^^^^^^^
```

When run through the analyzer, it produces the following:

```
  hint • The getter 'attribute' is always abstract in the supertype at tmp/ddctest.dart:14:33 • abstract_super_member_reference
1 hint found.
```

I believe that this should be an error on all platforms.

cc @lrhn do you agree that this is an error or am I missing something?

cc @kmillikin, @bwilkerson

**Comment by leafpetersen** [comment]
cc @keertip

**Comment by rich-j** [comment]
Is this issue related to https://github.com/dart-lang/sdk/issues/33420?

**Comment by leafpetersen** [comment]
Ok, moving this over to an analyzer bug.

**Comment by leafpetersen** [comment]
File a spec issue to ensure the text reflects this: https://github.com/dart-lang/sdk/issues/33963 .
