### ISSUE TITLE
Stop using templateUnspecified in CFE.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33676]
Analyzer needs to associate every error with `ErrorCode`, which comes from `analyzerCode` in `messages.yaml`. Using `templateUnspecified` does not allow this.

**Comment by bwilkerson** [comment]
@stefantsov I've been working on this for a couple of days (without realizing it was assigned to you). Do you mind if I take over?

**Comment by stefantsov** [comment]
@bwilkerson Yes, sure.

**Comment by bwilkerson** [comment]
I think I've done as much as I know how to do. Many of the remaining usages appear to be for internal problems. While these probably ought not to be reported as errors, I don't know what the code should do instead.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
