### ISSUE TITLE
When deprecated_InputError occurs during outline generation, a nearly empty kernel component is produced

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33686]
The method `KernelTarget.buildOutlines` (which is used by the command-line analyzer when run with `--use-cfe`) contains a catch clause for the type `deprecated_InputError` which calls `handleInputError`.  `handleInputError` calls `erroneousComponent` to create a component with a single `main` method that throws an exception, ensuring that the resulting program won't run.

This creates a problem when using the command-line analyzer, because it means that if the program contains any error that's reported via `deprecated_InputError`, then the analyzer will receive a component that lacks `dart:core`, causing it to crash.

Identified causes for deprecated_InputError:
* [ ] Not existing files in `import` directives (see also https://github.com/dart-lang/sdk/issues/33719).
* [ ] Unresolved package URIs in `import` directives (see also https://github.com/dart-lang/sdk/issues/33718).
* [ ] Using a builtin identifier as a class name, e.g. `class typedef {}`.
* [ ] Duplicate name `var x; var x;`, top-level or class members.

**Comment by stefantsov** [comment]
I've updated the top-level comment with a list of identified causes for the described behavior.  Please, expand it as needed.

**Comment by stereotype441** [comment]
This issue is now responsible for about 1/7 of the crash failures we're seeing when running language_2 tests with the analyzer/FE integration.

**Comment by scheglov** [comment]
Here are `language_2` tests that crash because of `deprecated_InputError `.

```
language_2/black_listed_test/02
language_2/black_listed_test/04
language_2/black_listed_test/06
language_2/black_listed_test/08
language_2/black_listed_test/10
language_2/black_listed_test/12
language_2/black_listed_test/14
language_2/built_in_identifier_illegal_test_typedef
language_2/constructor_redirect2_test/02
language_2/constructor_redirect2_test/03
language_2/constructor_redirect2_test/04
language_2/duplicate_constructor_test/01
language_2/enum_syntax_test/09
language_2/enum_syntax_test/10
language_2/enum_syntax_test/11
language_2/factory_with_type_parameters_test/03
language_2/factory_with_type_parameters_test/04
language_2/field1_test
language_2/field2_test
language_2/field4_test
language_2/field5_test
language_2/field6_test/00
language_2/field6_test/01
language_2/interface_injection1_negative_test
language_2/interface_injection2_negative_test
language_2/main_not_a_function_test
language_2/mixin_illegal_syntax_test/01
language_2/mixin_illegal_syntax_test/02
language_2/mixin_illegal_syntax_test/03
language_2/mixin_illegal_syntax_test/04
language_2/mixin_illegal_syntax_test/05
language_2/mixin_illegal_syntax_test/07
language_2/mixin_illegal_syntax_test/08
language_2/mixin_illegal_syntax_test/09
language_2/nonexistent_library
language_2/prefix_variable_collision_test_01
language_2/regress_33235_04_test/01
language_2/regress_33235_05_test/01
language_2/regress_33235_06_test/01
language_2/regress_33235_08_test/01
language_2/regress_33235_09_test/01
language_2/regress_33235_14_test/01
language_2/regress_33235_15_test/01
language_2/static_setter_conflicts_test/09
language_2/static_setter_conflicts_test/10
language_2/toplevel_collision1_test/00
language_2/toplevel_collision1_test/02
language_2/toplevel_collision2_test/00
language_2/toplevel_collision2_test/01
language_2/vm/regress_27201_bad_lib_path
```

**Comment by stefantsov** [comment]
We expect those issues to be addressed soon, as more people return from vacation.

**Comment by bwilkerson** [comment]
Any progress on this? This appears (based on the error message, not extensive code analysis) to also be causing several of the analysis server tests to be flaky.

**Comment by bwilkerson** [comment]
And why was the priority lowered? Can we bump the priority back up?

**Comment by stefantsov** [comment]
I think some progress and discussion has been done by @kmillikin on those instances of deprecated_InputError that originate from ambiguous naming.

**Comment by stereotype441** [comment]
There are currently 53 tests failing due to this bug:
```
black_listed_test/02
black_listed_test/04
black_listed_test/06
black_listed_test/08
black_listed_test/10
black_listed_test/12
black_listed_test/14
built_in_identifier_illegal_test/typedef
constructor_redirect2_test/02
constructor_redirect2_test/03
constructor_redirect2_test/04
duplicate_constructor_test/01
duplicate_field_with_initializer_test/01
enum_syntax_test/09
enum_syntax_test/10
enum_syntax_test/11
factory_with_type_parameters_test/03
factory_with_type_parameters_test/04
field1_test
field2_test
field4_test
field5_test
field6_test/00
field6_test/01
import_nonexisting_dart_uri_test/01
interface_injection1_test/1
interface_injection2_test/1
library_test/01
main_not_a_function_test
mixin_illegal_syntax_test/01
mixin_illegal_syntax_test/02
mixin_illegal_syntax_test/03
mixin_illegal_syntax_test/04
mixin_illegal_syntax_test/05
mixin_illegal_syntax_test/07
mixin_illegal_syntax_test/08
mixin_illegal_syntax_test/09
part_refers_to_core_library_test/01
prefix_variable_collision_test/01
regress_33235_04_test/01
regress_33235_05_test/01
regress_33235_06_test/01
regress_33235_08_test/01
regress_33235_09_test/01
regress_33235_14_test/01
regress_33235_15_test/01
static_setter_conflicts_test/09
static_setter_conflicts_test/10
toplevel_collision1_test/00
toplevel_collision1_test/02
toplevel_collision2_test/00
toplevel_collision2_test/01
vm/regress_27201_test
```

**Comment by stereotype441** [comment]
A CL is out for review that fixes this bug: https://dart-review.googlesource.com/c/sdk/+/71161

Once it lands I'll reclassify the failures in tests/language_2/language_2_analyzer.status.

**Comment by scheglov** [comment]
The closing CL was reverted as https://dart-review.googlesource.com/c/sdk/+/71401

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
