### ISSUE TITLE
Decide whether we want using MissingImplementationCause in Analyzer.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33680]

**Comment by bwilkerson** [comment]
Sorry, what is `MissingImplementationCause`?

**Comment by scheglov** [comment]
This is a problems code reported from CFE, when there is a non-abstract class with not implemented inherited members. It specifies from where these members came.

**Comment by scheglov** [comment]
CFE reports `StaticWarningCode.NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_*`, *and* also additional problems with `MissingImplementationCause` as a way to give more details to the user. Separately, not embedded into the `Abstract Class` problem.

**Comment by bwilkerson** [comment]
Is there any (reasonable) way for us to merge the information from these two sources? If not, then we need to change the CFE to report all of the data we need.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
