### ISSUE TITLE
DDC: Doesn't issue NSM/NullError on closure failure (?)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33684]
I'm having a hard time reproducing this externally (either it is fixed, or I am missing nuances).

I hit the following exception internally while treating to help a team:

```
TypeError: TToString(...)._check(...) is not a function
```

_Somewhere_ here, there is code like:

```dart
typedef ItemRenderer<T> = String Function(T);

class Context<T> {
  final ItemRenderer<T> itemRenderer;
  Context({this.itemRenderer});
}

void main() {
  someFunction(null, null);
}

void someFunction(Context<String> context, ItemRenderer itemRenderer) {
  itemRenderer = (item) => context.itemRenderer(item);
  itemRenderer('Hello');
}
```

(Not precise)

I'd imagine to get a `NoSuchMethodError` or `NullError` instead of this internal-y error.

**Comment by matanlurey** [comment]
Wait, great, I can reproduce it exactly (externally):

```dart
import 'package:test/test.dart';

typedef ItemRenderer<T> = String Function(T);

class Context<T> {
  final ItemRenderer<T> itemRenderer;
  Context({this.itemRenderer});
}

void main() {
  test('should ...', () {
    void doThing(Context<String> context) {
      ItemRenderer<dynamic> itemRenderer;
      itemRenderer = (item) => context.itemRenderer(item);
      itemRenderer('Hello');
    }
    
    doThing(new Context());
  });
}
```

... produces

```
test/ddc_bug_test.dart: should ... [E]
  TypeError: StringToString(...)._check(...) is not a function
  ddc_bug_test.dart 14:52  item
  ddc_bug_test.dart 15:7   doThing
  ddc_bug_test.dart 18:5   test$.test.dart.fn
```

It looks like `TypeError` implements `NoSuchMethodError` FWIW.

**Comment by jmesserly** [comment]
That's just the null error from JavaScript. Same thing happens:
```dart
void main() {
  Function(Object) f;
  f('Hello');
}
```
Same thing from a method call like `c.m()`. It is a NoSuchMethodError in Dart. You can catch it:
```dart
class C {
  m() {}
}

void main() {
  try {
    C c;
    c.m();
  } on NoSuchMethodError catch (e) {
    print('caught $e');
  }
  try {
    Function(Object) f;
    f('Hello');
  } on NoSuchMethodError catch (e) {
    print('caught $e');
  }
}
```
We can't change the JS error type. We do have a regexp to match the method case. The above program prints:
```
caught NullError: invalid member on null: 'm'
caught TypeError: f is not a function
```
We could add a regexp `is not a function`. The problem is, if you're using JS interop that error could mean anything, so we would be misleading users to say it's a null error.

I'll see if I can find something that helps here.

**Comment by jmesserly** [comment]
I'm testing a fix now (https://dart-review.googlesource.com/c/sdk/+/66228), with the fix the program in my comment now prints:
```
caught NoSuchMethodError: invalid member on null: 'm'
caught NoSuchMethodError: tried to call a non-function, such as null: 'f'
```
The error message now suggests that null could be the cause. I also prefixed the messages with the string "NoSuchMethodError: " to make it more clear what the Dart type of the Error is. Does that help?

**Comment by matanlurey** [comment]
Very, thanks!
