### ISSUE TITLE
JSArray vs JsArray TypeErrors

### ISSUE THREAD

**Issue by tonyclickspace** [dart-lang/sdk#33688]
Dart SDK 2.0.0-dev.63.0
To reproduce: https://dartpad.dartlang.org/6809e880ad4b1ce421d964aa6a5fde66

dart:js uses the class "`JsArray`". Using `new List.from({JsArray})` creates not a `List<dynamic>`, but an instance of "`JSArray`", separate from the dart:js implementation.

Can easily cause unexpected TypeErrors, like:
`TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'JsArray'`

**Comment by matanlurey** [comment]
Unfortunately `dart:js` is soft deprecated: https://github.com/dart-lang/sdk/issues/33350

I would discontinue use of it, it's unlikely to get any updates to make it more adaptable to Dart2.

I have some documentation of avoiding use of `dart:js` here:
https://github.com/matanlurey/dart_js_interop
