### ISSUE TITLE
Decide what staticInvokeType should be for invalid method invocation.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33682]
```dart
int foo = 0;
main() {
  foo(1);
}
```

The `staticInvokeType` of `foo(1)` in Analyzer is `int`, in CFE it is `() → dynamic`, which is IMHO closer to what we would expect, but why not `(int) → dynamic`?

**Comment by bwilkerson** [comment]
I believe that Dart 2 dismantles the magic of the `call` method, but `dynamic` might still be a valid result.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
