### ISSUE TITLE
Analyzer/FE error recovery for wrong number of setter parameters

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33691]
Consider the following erroneous code:
```
// ERROR: setters must have exactly one parameter
void set badSetter(int a, double b) {
  var x = a + b;
}
void main() {
  badSetter = 1;
}
```
The current analyzer handles `badSetter` by reporting an error and creating an "impossible" element model in which the setter has two parameters.  This allows for fairly graceful recovery; for instance, the reference to `double` in the declaration of the bogus parameter `b` correctly points to the declaration of `double` in the SDK.  And the reference to `b` inside the method is correctly resolved to the extra parameter, and it even has the expected type of `double`.  However, this graceful recovery comes at a cost: when analyzing any code that makes reference to a setter (such as the code in `main`), the analyzer must be prepared for the possibility that the setter in question has any number of parameters (possibly even zero).

The front end handles this differently: it creates a kernel representation of the setter in which the two parameters are replaced with a single synthetic parameter having type `dynamic` and name `#synthetic`.  The upside to this is that it doesn't need any special case logic to analyze the reference to the setter in `main`.

But the downside is that it's not clear how to integrate this with the analyzer without losing the graceful error recovery.  Currently the way analyzer/FE integration works is that the analyzer element model is built from the kernel representation, which means that an element gets created for `badSetter` that has only one parameter.  Later, when the file is examined in more detail, an unresolved AST is created in which `badSetter` has two parameters, and a visitor (`DeclarationResolver`) tries to bind the declarations in the AST to their corresponding elements.  That visitor throws an exception because of the mismatch in parameter counts.

We *could* get past the exception by making the visitor tolerate a mismatch in parameter counts by, say, ignoring extra parameters found in the AST.  But there would be two follow-on problems:
- Since the kernel representation of `badSetter` has just a single parameter whose type is `dynamic`, there's no way for the analyzer to resolve `int` and `double` to their corresponding declarations; that information has been lost.
- When we then tried to analyze the body of the setter, there would be no element for the reference to `b` to refer to.  (Possible workaround: maybe we could pretend that `b` is a local variable declaration).

**Comment by kmillikin** [comment]
I'm probably missing something super obvious, but I have to ask.

The DeclarationResolver has the Kernel AST and the Analyzer AST in its hand and it walks the Kernel AST to create elements and then walks the Analyzer AST to read resolution information out of the resolution store and into the elements.

Why doesn't it walk the Analyzer AST to create elements?

In this example, we'd have the setter element with both parameter elements.  Then the problem is simply to ensure that we record resolution information for both parameters on the front end.

**Comment by stereotype441** [comment]
Two reasons that won't work:

1. The analyzer AST is heavyweight, so we only create it when we need to analyze a given file.  The elements are lighter weight, and we need them whenever a thing is referred to.  So if `badSetter` and `main` are in different files, and we analyze `main` first, we have to create the element for `badSetter`, and we don't have the AST to refer to.

2. There are some scenarios involving bazel where we don't have access to the AST at all, since analysis is running inside a bazel sandbox, and we have declared to bazel that the analysis for a given file only depends on that file and a summary of its dependencies.  We can't depend on the source files for the dependencies, because that would cause nuisance rebuilds; and if we declare that we don't depend on the sources for the dependencies, then bazel won't allow us to access them.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
