### ISSUE TITLE
Dart does not throw error if function argument parameter extends Null

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33701]
Dart SDK Version: 2.0.0-dev.55.0
OS: Windows 10

Sample code below declares a [typedef] with parameter which extends [Null]. It causes a lot of compiler errors with dartanalyzer and passes without errors with dart.
``` dart
typedef F<X extends Null> = Function(X);
main() {}
```
This is similar to the issue #33699, however analyzer produces different errors in these two cases, so we would be better to have separate issues.

I believe both tools should behave in the same way.
Dartanalyzer sample output is:
```
Analyzing typedef_ret_extends_neg_l1_t05.dart...
  error - 'X' can't be a supertype of its upper bound at typedef_ret_extends_neg_l1_t05.dart:50:11 - type_parameter_supertype_of_its_bound
1 error found.
```
Dart stdout and stderr are empty, no exceptions or warnings there.

**Comment by lrhn** [comment]
The error seems spurious.

There is nothing inherently problematic with allowing `Null` as a type parameter bound (apart from the class being useless, so it's also not a big loss if we don't).

If we have a rule preventing a type parameter from being a supertype of its bound, the phrasing needs to be fixed so it doesn't allow this any more than it disallows `<X extends Object>`.

**Comment by iarkh** [comment]
OK, but if Null is allowed, analyzer should not throw error too.
Should I update synopsys accordingly?

**Comment by eernstg** [comment]
Removing blocked status: As of 4fd04044fb43ffc7a018470caf3e9df097613991, the subtype circularity prevention rule in the language specification has be adjusted such that Null is now an acceptable upper bound for a type variable. The front end should now be updated accordingly.

**Comment by srawlins** [comment]
Analyzer no longer reports an error for this code (both with and without null-safety).
