### ISSUE TITLE
Dart2Js batch mode leaks memory

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33708]
Compiled at HEAD of the master branch yesterday:

Dart VM version: 2.0.0-edge.c5213877d149872f918f8f9816f8f3a3ff255df8 (Thu Jun 28 09:32:37 2018 -0700) on "linux_x64"

Related report https://github.com/dart-lang/build/issues/1620.

In build_runner we use `dart2js` in batch mode to speed up compilation, but it appears that it is leaking memory (slowly) over time, eventually leading it to consume all the memory on the machine and/or crash.

You can reproduce this by cloning the [angular repo](https://github.com/dart-lang/angular) and running `pub run build_runner build -r test` under the `_test` directory.

cc @rakudrama @natebosch @matanlurey @sigmundch

**Comment by rakudrama** [comment]
To profile:
- add  <yourDartEnlistment>/sdk/bin to the path
- add  `--observe=8123` to the last line of sdk/bin/dart2js_sdk
- `pub run build_runner build -r test` for about a minute and a half
- connect to `http:127.0.0.1`

The attached allocation profile was taken about 15 minutes into the build, shortly before the dart2js VM crashed, leaving `pub` waiting on the dead process. At this point dozens of targets have been compiled.

It seems that ~40% of all tokens allocated are retained. Ditto Kernel classes like FunctionNode.
The data points to the leak being in fasta / kernel.

![screenshot from 2018-06-29 12-30-56](https://user-images.githubusercontent.com/2108821/42111209-76d4d888-7b98-11e8-8235-fe06eac4e480.png)

**Comment by rakudrama** [comment]
We have a fix. https://dart-review.googlesource.com/c/sdk/+/63321

**Comment by rakudrama** [comment]
Fixed via 714dbc3e815539ccb13eaef6483e1f3b2b5eb7c7
