### ISSUE TITLE
Should we have a separate error code for argument type is not assignable to the parameter type?

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33712]
```dart
main() {
  foo('zzz');
}
foo(int p) {}
```

```
bin/test.dart:2:7: Error: A value of type 'dart.core::String' can't be assigned to a variable of type 'dart.core::int'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::int'.
  foo('zzz');
      ^
```

In Analyzer we currently have separate `StaticWarningCode.ARGUMENT_TYPE_NOT_ASSIGNABLE`.

**Comment by bwilkerson** [comment]
Note that this is not the only error for which analyzer has more specific contextual information and which will therefore need to be split into multiple error messages.

@stefantsov Do we want separate issues for each message, or should we have a single issue covering the general case with an explicit list?

**Comment by stefantsov** [comment]
I would prefer the single issue with the list, like those that we had for converting shadow expression and shadow statements to judgments.

**Comment by bwilkerson** [comment]
Sounds good. I don't have a complete list at this point, but I'll start working on it.

**Comment by bwilkerson** [comment]
This particular case is addressed by https://dart-review.googlesource.com/c/sdk/+/63960.
