### ISSUE TITLE
noSuchMethod forwarders should also be generated for certain private methods

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33725]
Cf. the discussion in #33665: The feature specification [nosuchmethod-forwarding.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/nosuchmethod-forwarding.md) specifies that when there is a non-trivial `noSuchMethod` implementation, `noSuchMethod` forwarders must be generated in concrete classes for method signatures in the class interface with no implementation.

However, that feature specification does not consider the case where the class has only the `noSuchMethod` implementation declared in `Object`, but the developer cannot declare an implementation of a method signature because the name is inaccessible (that is, private and from a different library _L1_).

In that situation, we may encounter statically checked invocations (in code in _L1_) where there is no method implementation, unless it has been generated.

In order to maintain the property that every statically checked method invocation will have a corresponding method implementation, we must generate `noSuchMethod` forwarders also in that case.

Alternatively, we could make a class where this situation arises a compile-time error (which means that developers will have to declare a concrete `noSuchMethod` in order to be able to claim `implements C` where `C` has some inaccessible methods (which may be "nice", but presumably seriously breaking).

This issue is concerned with reaching a decision on whether to generate forwarders even when there is no non-trivial `noSuchMethod` for such inaccessible methods.

**Comment by stefantsov** [comment]
Related issue for the common front end: https://github.com/dart-lang/sdk/issues/33727.

**Comment by eernstg** [comment]
An update to [nosuchmethod-forwarding.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/nosuchmethod-forwarding.md) is available in [this CL](https://dart-review.googlesource.com/c/sdk/+/64380), awaiting reviews.

**Comment by eernstg** [comment]
Done in 6920d6b11ef9247b503a7ac215f6db6071c164a3.
