### ISSUE TITLE
Avoid duplication between representations of invalid assignment judgments

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33729]
https://dart-review.googlesource.com/c/sdk/+/63360 introduces a new class to represent assignments to variables that don't exist.  Long term, I think we should try to represent all invalid assignments by a single judgment class (e.g. IllegalAssignmentJudgment) rather than making separate judgment classes for each of the cases.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
