### ISSUE TITLE
dartdoc comments not recognized for classes that are marked as abstract when using the analyzer with --use-fasta-parser

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33738]
Specifically, if it's within a dartdoc comment for a class that's marked as abstract:

```
/** [String] */
class Foo {}
```

For the above, `String` will resolve.

```
/** [String] */
abstract class Bar {}
```

For the above, `String` will not resolve.

@danrubel

**Comment by devoncarew** [comment]
I hit this when dogfooding --use-fasta-parser - you can see it if you open the `pkg/analyzer_plugin` package from the sdk repo. You can see the issue in the `lib/plugin/assist_mixin.dart` file (and a few others) - they come up with unused imports warnings, as the imports have symbols that are only referenced from dartdoc comments.

**Comment by devoncarew** [comment]
And similarly, when dogfooding on the flutter codebase, the `Document all public members` lint fires. This only happens for `abstract` classes, even through they do have dartdoc comments. So I suspect that there's some issue recognizing a dartdoc comment before a class that has a leading `abstract` keyword.

**Comment by devoncarew** [comment]
@danrubel, honestly, from dogfooding this locally for a few hours, this may be the only blocking issue from enabling `--use-fasta-parser` by default.

**Comment by danrubel** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/64140
