### ISSUE TITLE
Analyzer doesn't support Severity.context when converting error messages from CFE

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#33730]
Any such message results in a crash because of an exception thrown from Analyzer when Severity.context is encountered.

**Comment by bwilkerson** [comment]
What does `Severity.context` mean?

**Comment by stefantsov** [comment]
It means some extra information about the error that may point to some part of the program related to the error message.

Let me demonstrate it on the following program:

```dart
class Foo<X extends Bar> {}

class Bar<Y extends Foo> {}

main() {}
```

When compiled, it produces an error message because of the cyclic definitions of type variables.  The message is reported only on one of such variables, and the rest of them are included in the context:

```kernel
$ pkg/front_end/tool/fasta compile --strong --dump-ir /tmp/asdf.dart 
file:///tmp/asdf.dart:3:7: Error: Generic type 'Bar' can't be used without type arguments in the bounds of its own type variables. It is referenced indirectly through 'Foo'.
Try providing type arguments to 'Foo' here or to some other raw types in the bounds along the reference chain.
class Bar<Y extends Foo> {}
      ^^^
file:///tmp/asdf.dart:3:11: Context: Bound of this variable references raw type 'Foo'.
class Bar<Y extends Foo> {}
          ^
file:///tmp/asdf.dart:1:11: Context: Bound of this variable references raw type 'Bar'.
class Foo<X extends Bar> {}
          ^
library;
import self as self;
import "dart:core" as core;

class Foo<X extends self::Bar<dynamic> = self::Bar<dynamic>> extends core::Object {
  synthetic constructor •() → void
    : super core::Object::•()
    ;
}
class Bar<Y extends self::Foo<self::Bar<dynamic>> = dynamic> extends core::Object {
  synthetic constructor •() → void
    : super core::Object::•()
    ;
}
static const field dynamic #errors = const <dynamic>["file:///tmp/asdf.dart:3:7: Error: Generic type 'Bar' can't be used without type arguments in the bounds of its own type variables. It is referenced indirectly through 'Foo'.\nTry providing type arguments to 'Foo' here or to some other raw types in the bounds along the reference chain.\nclass Bar<Y extends Foo> {}\n      ^^^"]/* from null */;
static method main() → dynamic {}
```

As far as I understand, ignoring the context should not reduce the amount of compile-time errors produced by the compiler, but reduces the amount of useful information provided by the compiler.

**Comment by bwilkerson** [comment]
> ... ignoring the context should not reduce the amount of compile-time errors produced by the compiler ...

Agreed. But I do find it odd that this "has context" flag is being encoded in the severity of the error.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
