### ISSUE TITLE
dart2js: fix how we treat private names in nsm forwarders

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33732]
We have a bug that private names from different libraries are conflicting with each other. Because nsm forwarders may include library-private names, we added a workaround in 64553b68e96f04c6514be68bd417795757b2a091  to ignore those private names in other libraries.

The workaround is incorrect, as it wouldn't correctly handle this example:

**a.dart**:
```dart
import 'b.dart';

class A implements I {
  int _m() => 1;
  noSuchMethod(Invocation m) => 2;
}

class B implements I {
  noSuchMethod(Invocation m) => 3;
}

main() {
  print((new A()._m)()); // should print "1"
  foo(new B()); // should print "3"
}
```

**b.dart**:
```dart
abstract class I {
  int _m();
}

void foo(I i) {
  print("${(i._m)()}");
}
```

If we incorrectly ignore the forwarder, the call to foo(new B()) will cause a runtime error

Before our workaround, we used to print "3" twice. After the workaround, we print "1", and then have a runtime error on `foo(new B())`,  because the tearoff hits nSM and returns "3", which can't invoked.

Once we correctly handle private names in nsm-forwarder, the tearoff will be created correctly, and the call to `foo` should print "3".

More details can be found in the discussion here: https://github.com/dart-lang/sdk/issues/33665

**Comment by vsmenon** [comment]
Bump this post 2.1?
