### ISSUE TITLE
valueOf(key) for Maps like elementAt(index) for Iterables

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#33734]
Based on [a problem I encountered](https://stackoverflow.com/questions/51141109/null-aware-operator-with-maps/51141153?noredirect=1#comment89267419_51141153), I think that it would be a nice addition to the language.

```dart
map.valueOf(key)
// which is equal to
map[key]
```

This enables the null-safe operator:

```dart
map?.valueOf(key)
```

This already exists for iterables, where:

```dart
list.elementAt(index)
// is equal to
list[index]
```

**Comment by lrhn** [comment]
We are not planning on adding a duplicate method. That's bad API design just to make up for a lacking language feature.

We should consider extending null-aware behavior to operators, or at least the index operators. We already allow them for cascades, and we want null-aware operators to extend to the end of the same section like cascades do.
So, maybe at least allow `x?.[42]` and `x?.[42] = 10` like we allow `x..[42].toString()` and `x..[42] = 10`.
