### ISSUE TITLE
How can i install download older version of Dart SDK in linux apt-get?

### ISSUE THREAD

**Issue by ccj9707** [dart-lang/sdk#33742]
I originally used this command well in Docker :
```apt-get -y --allow-unauthenticated install dart=2.0.0-dev.63.0-1```
It had worked well at 2.0.0-dev-64.1, but now, I can see this error message : 
```E: Version '2.0.0-dev-63.0-1' for 'dart' was not found```

Can you help me?

**Comment by thosakwe** [comment]
Inquired about this the other day with @sgjesse and @athomas, here was Alexander's response:

```
Hi!

We are making some changes to how publish packages that caused this. With the latest dev release, we've published all dev channel releases again. However, we might have only the latest at a later date. We should make the old debs more easily accessible on the webpage, but you can download them already now by putting the version number into the URL instead of "latest":

https://storage.googleapis.com/dart-archive/channels/dev/release/2.0.0-dev.64.1/linux_packages/dart_2.0.0-dev.64.1-1_amd64.deb 

Sorry for the inconvenience,
- Alex
```

So, for `2.0.0-dev.63.0`:

https://storage.googleapis.com/dart-archive/channels/dev/release/2.0.0-dev.63.0/linux_packages/dart_2.0.0-dev.63.0-1_amd64.deb

**Comment by thosakwe** [comment]
After downloading the `.deb`, you can run:

```bash
sudo dpkg -i /path/to/dart_2.0.0-dev.63.0-1_amd64.deb
sudo apt-get install -f
```

You can then run `dart --version`, and should see the expected output.

**Comment by ccj9707** [comment]
@thosakwe Thank you, I solved the problem.
