### ISSUE TITLE
FutureOr in a class header can be an error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33743]
It was previously not explicit in the language specification that the type `FutureOr<T>` (where `T` can be any type, written by a developer or obtained during compilation from a mechanism like instantiate-to-bound) cannot be used in certain positions. With commit b803d74c9b0ac14b66555b7735d58b0ccc0e300a it has been made explicit in the language specification that it is a compile-time error to have `FutureOr<T>` for any `T` as a superclass, superinterface, or as a mixin.

This issue is concerned with the implementation of that behavior. Currently (2.0.0-dev.66.0) the fact that the actual source code for `FutureOr` in async.dart  contains a constructor named `FutureOr._` ensures that `extends` and `with` is already a compile-time error, but it may be useful to report the error differently (as "FutureOr cannot be used as a superclass" or something like that, rather than as an error caused by a missing constructor). However, `implements` is accepted, and that should be made a compile-time error.

```dart
import 'dart:async';

class C1
    extends FutureOr<int>  //# 01: compile-time error
{}

class C2
    implements FutureOr<int>  //# 02: compile-time error
{}

class C3 extends Object
    with FutureOr<int> //# 03: compile-time error
{}

main() async {
  // Ensure that all classes get compiled.
  new C1();
  new C2();
  new C3();
}
```

---

### Subtasks

- [x] Fasta (#33744).
- [x] Analyzer (#33745).

**Comment by srawlins** [comment]
Both subtasks have been completed.
