### ISSUE TITLE
Incomplete sentence in `DartObject.toSymbolValue()` documentation

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33757]
This sentence in the doc string for `toSymbolValue()` ends abruptly.

https://github.com/dart-lang/sdk/blob/d5ccb53f0133061bc9f85fea6c391c627ddb5801/pkg/analyzer/lib/dart/constant/value.dart#L148

**Comment by keertip** [comment]
The documentation has been fixed.
