### ISSUE TITLE
dart2js 2.0.0-dev.64.1 features new undocumented error: "Error: The integer literal DDD can't be represented exactly in JavaScript."

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#33752]
There is no changelog entry for this breaking change.

**Comment by srawlins** [comment]
Assigning to @sigmundch for triage and priority

**Comment by srawlins** [comment]
Feature tracked in https://github.com/dart-lang/sdk/issues/33282

**Comment by sigmundch** [comment]
Adding changelog entry in https://dart-review.googlesource.com/c/sdk/+/63664

**Comment by srawlins** [comment]
@sigmundch indeed fixed this.
