### ISSUE TITLE
Callback exists but tested as null when using dart2js in some scenario (dart2)

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#33761]
I'm testing on Ubuntu 16.04 sdk 2.0.0-dev.67.

The following test (weird but extracted from an existing source), in pure dart:

```dart
import 'dart:async';
import 'package:test/test.dart';

bool callbackIsNull;

class Test2 {
  Future test(void callback()) async {
    callbackIsNull = callback == null;
    return new Future.value();
  }
}

class Test {
  Future test(
    int param,
    void callback(),
  ) async {
    // check params
    if ((param == null) != (callback == null)) {
      throw new ArgumentError('param and callback must be specified together');
    }

    await new Test2().test(callback);
  }
}

void main() {
  test('bug', () async {
    callbackIsNull = true;
    void callback() {
      print("callback");
    }

    await new Test().test(1, callback);
    expect(callbackIsNull, isFalse);
  });
}
```

works when run using

    pub run test -p vm
    pub run build_runner test -- -p chrome
    pub run build_runner test -- -p firefox
    
Running it this way fails
    
    pub run test -p chrome
    pub run test -p firefox
    pub run build_runner test -r -- -p chrome
    pub run build_runner test -r -- -p firefox

Test is available here: https://github.com/alextekartik/dart-test/tree/master/bug_33761_test for convenience. Tested on dart 2.0.0-dev.67 and ubuntu 16.04

**Comment by alextekartik** [comment]
After more investigation, I found a weird workaround:

https://github.com/tekartik/idb_shim.dart/blob/1fc6bb689e4f6f0b62e42820707d399ca71ac22e/lib/src/sembast/sembast_factory.dart#L45-L64

The following test - copied from indexed_db_dart2js.dart implementation - testing that 2 parameters are either null or non null, seems to lead to weird optimization with dart2js

    (version == null) != (onUpgradeNeeded == null)

If I run `pub run test -p chrome test/test_runner_bug_test.dart` with:

    if ((version == null) != (onUpgradeNeeded == null)) {

the output is the following (only with dart2js not with dartdevc)

     init Closure 'main_closure__initializeDatabase' NOT NULL
    open1 Closure 'main_closure__initializeDatabase' NOT NULL
    open2 Closure 'main_closure__initializeDatabase' NOT NULL


If I run the same test with the replaced test:

    if (((version != null) || (onUpgradeNeeded != null)) &&
        ((version == null) || (onUpgradeNeeded == null))) {

the output is the following:

     init Closure 'main_closure__initializeDatabase' NOT NULL
    open1 Closure 'main_closure__initializeDatabase' NOT NULL
    open2 Closure 'main_closure__initializeDatabase' NULL

**Comment by alextekartik** [comment]
I was able to isolate the issue a little more, in pure dart. The following test:

```dart
import 'dart:async';
import 'package:test/test.dart';

bool callbackIsNull;

class Test2 {
  Future test(void callback()) async {
    callbackIsNull = callback == null;
    return new Future.value();
  }
}

class Test {
  Future test(
    int param,
    void callback(),
  ) async {
    // check params
    if ((param == null) != (callback == null)) {
      throw new ArgumentError('param and callback must be specified together');
    }

    await new Test2().test(callback);
  }
}

void main() {
  test('bug', () async {
    callbackIsNull = true;
    void callback() {
      print("callback");
    }

    await new Test().test(1, callback);
    expect(callbackIsNull, isFalse);
  });
}
```

works when run using

    pub run test -p vm
    pub run build_runner test -- -p chrome
    
Running it this way fails
    
    pub run test -p chrome
    pub run build_runner test -r -- -p chrome

Test is available here: https://github.com/alextekartik/dart-test/tree/master/bug_33761_test for convenience. Tested on dart 2.0.0-dev.67 and ubuntu 16.04

**Comment by sigmundch** [comment]
@alextekartik - thank you for filing this bug and for finding a small repro for us. This was super super helpful!

After pruning a bit here and there, it appears this is an issue with our global whole-program analysis. We are interpreting incorrectly the condition you have in check-params, and as a result we believe callback is null before the call to `Test2.test`. 

We'll work soon on a fix, but meanwhile, if this is blocking you, I believe that moving the condition to a local variable will make dart2js ignore it:
```dart
var condition = (param == null) != (callback == null);
if (condition) throw ...;
```

Turns out, the problem also reproduces on normal values and not just on callbacks. Here is a reduced repro that highlights the problem:
```dart
import 'package:expect/expect.dart';

@NoInline() // if dart2js inlines the code during optimizations, it hides the problem
foo(x) => print('x is null: ${x == null}');

void main() {
  var x = 1;
  if ((x == null) != false) return;
  foo(x); // the whole-program analysis misinterprets the condition above and incorrectly thinks `x == null` here.
}
```

**Comment by sigmundch** [comment]
Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/63981

**Comment by alextekartik** [comment]
Confirmed the issue is fixed (and the one I was encountering in my lib) using 2.0.0-dev.68. Congrats and thanks
