### ISSUE TITLE
Reporting a problem compiler message This might be a bug

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#33760]
I am posting regarding the info shown below:
`_compiler message: Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new._`

**Flutter Version:**
Flutter 0.5.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 472bbccf75 (7 days ago) • 2018-06-26 17:01:46 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
Niyazis-MacBook-Pro:capitalbank niyazitoros$ 

**Dart Version:**
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64"
Niyazis-MacBook-Pro:capitalbank niyazitoros$ 

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.6, on Mac OS X 10.13.5 17F77, locale en-CY)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
Niyazis-MacBook-Pro:capitalbank niyazitoros$ 

**Warning:**
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
compiler message: Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/EGL_emulation(11732): eglMakeCurrent: 0xa75042a0: ver 3 0 (tinfo 0xa7503300)
[{"event":"app.progress","params":{"appId":"67aebb65-5f93-44c8-ba18-8f65ad6fa763","id":"4","progressId":null,"message":"Syncing files to device Android SDK built for x86..."}}]Syncing files to device Android SDK built for x86...

D/        (11732): HostConnection::get() New Host Connection established 0xa7522440, tid 11787
D/EGL_emulation(11732): eglMakeCurrent: 0xa4b7de00: ver 3 0 (tinfo 0xa7503290)

**Comment by a-siva** [comment]
This appears to be another instance of #36032

**Comment by a-siva** [comment]
Closing as duplicate.
