### ISSUE TITLE
Please roll dart_style to 1.1.2 in the SDK

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#33773]
I know I said [the last one](https://github.com/dart-lang/sdk/issues/33663) was it, but I'm sorry. I again need a new version of dart_style rolled. :(

The last change to format inside string interpolations looks really bad when the string doesn't fit inside a single line. This fixes that.

**Comment by whesse** [comment]
Yes I am.

**Comment by whesse** [comment]
The checked-in SKD is updated to this version of dartfmt in CL https://dart-review.googlesource.com/c/sdk/+/64541
