### ISSUE TITLE
Token for '=' is needed for Analyzer to convert invalid field initializers produced by the CFE in some cases of error recovery

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#33771]
It manifests in the following test case: `tests/language_2/illegal_initializer_test.dart`.  Here is a simplified version of the code from that file:

```dart
class A {
  A() : this;
}

main() {}
```

Error `MissingAssignmentInInitializer` is produced, and the recovery is to issue an invalid field initializer.  As far as I understand, Analyzer wants the location of `=` in the case of an initializer, even invalid one, even when there's no `=` written by the programmer.

Judging by the following output, the location of the missing `=` may be determined as the end of `this`:

```
$ out/ReleaseX64/dart-sdk/bin/dartanalyzer --format=machine /tmp/asdf.dart 
ERROR|SYNTACTIC_ERROR|EXPECTED_TOKEN|/tmp/asdf.dart|2|13|1|Expected to find '.'.
ERROR|SYNTACTIC_ERROR|MISSING_ASSIGNMENT_IN_INITIALIZER|/tmp/asdf.dart|2|13|1|Expected an assignment after the field name.
ERROR|COMPILE_TIME_ERROR|INITIALIZER_FOR_NON_EXISTENT_FIELD|/tmp/asdf.dart|2|9|4|'' isn't a field in the enclosing class.
ERROR|SYNTACTIC_ERROR|MISSING_IDENTIFIER|/tmp/asdf.dart|2|13|1|Expected an identifier.
```

**Comment by danrubel** [comment]
The parser should be inserting a synthetic `=` after `this` in the example above.
Please let me know if this is not the case.

**Comment by bwilkerson** [comment]
Wouldn't the parser need to insert "._s_ = _s_" (where "_s_" is a synthetic identifier) in order to have valid code?

**Comment by danrubel** [comment]
Sorry. You are correct and the parser does that. I've updated my comment above.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
