### ISSUE TITLE
[!] VS Code, 64-bit edition (version 1.25.0)

### ISSUE THREAD

**Issue by botaniQQQ** [dart-lang/sdk#33788]
`[!] VS Code, 64-bit edition (version 1.25.0)`

![te88gmo](https://user-images.githubusercontent.com/3118010/42454967-a14f93b0-8399-11e8-94d1-8de056dcfae5.jpg)

**Comment by matanlurey** [comment]
Closed. This should be filed at https://github.com/flutter/flutter/issues, as mentioned.

**Comment by botaniQQQ** [comment]
@a-siva, oh, really, mixed up, thanks.
