### ISSUE TITLE
Angular + Dart 2 SDK version problem

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/sdk#33785]
* Dart SDK Version (2.0.0-dev.67.0)
* Linux

Installed latest dart 2 sdk.
Trouble running **pub**, but got partly round that [https://github.com/dart-lang/pub/issues/1944]
When I do a pub --trace get I get the following output, which starts off by contradicting the just installed sdk version number.

Resolving dependencies... 
The current Dart SDK version is 2.0.0-dev.44.0.

Because ng_dart_quickstart requires SDK version >=1.24.0 <2.0.0, version solving failed.
---- Log transcript ----
FINE: Pub 2.0.0-dev.44.0
SLVR: fact: pub itself depends on barback >=0.15.0 <0.15.3
SLVR: fact: when barback is in use pub itself depends on source_span ^1.0.0
SLVR: fact: when barback is in use pub itself depends on stack_trace >=0.9.1 <2.0.0
SLVR: fact: when barback is in use pub itself depends on async >=1.8.0 <3.0.0
SLVR: fact: ng_dart_quickstart is 0.0.1
SLVR: derived: ng_dart_quickstart
SLVR: fact: ng_dart_quickstart requires SDK version >=1.24.0 <2.0.0
SLVR: conflict: ng_dart_quickstart requires SDK version >=1.24.0 <2.0.0
SLVR: Version solving took 0:00:00.017390 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.0s).
ERR : The current Dart SDK version is 2.0.0-dev.44.0.
    | 
    | Because ng_dart_quickstart requires SDK version >=1.24.0 <2.0.0, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 331  VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 154  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 119  VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                      _Completer.completeError
    | package:pub/src/solver/version_solver.dart      VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                      _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart 109  VersionSolver.solve
    | package:pub/src/solver.dart 35                  resolveVersions.<fn>
    | package:pub/src/log.dart 409                    progress
    | package:pub/src/solver.dart 32                  resolveVersions
    | package:pub/src/entrypoint.dart 207             Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                      new Future.microtask
    | package:pub/src/entrypoint.dart 206             Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38             GetCommand.run
    | package:args/command_runner.dart 194            CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                      new Future.microtask
    | package:args/command_runner.dart 142            CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168         PubCommandRunner.runCommand.<fn>
    | dart:async                                      new Future.sync
    | package:pub/src/utils.dart 116                  captureErrors.<fn>
    | package:stack_trace                             Chain.capture
    | package:pub/src/utils.dart 131                  captureErrors
    | package:pub/src/command_runner.dart 168         PubCommandRunner.runCommand
---- End log transcript ----

**Comment by zoechi** [comment]
What output do you get for `dart --version`?

**Comment by biancashouse** [comment]
Dart VM version: 2.0.0-dev.67.0 (Unknown timestamp) on "linux_x64"

BTW - pub does not seem to be installed with Dart 2 SDK !

**Comment by zoechi** [comment]
`pub` is always installed, you might need to add `dart-sdk/bin` to your `PATH`

**Comment by biancashouse** [comment]
Doh, dart sdk was hiding in /usr/lib/dart.

Many thanks.

**Comment by zoechi** [comment]
Is there still an issue or can this be closed?

**Comment by biancashouse** [comment]
Sure can. I'll update and close the issue, thanks...

**Comment by biancashouse** [comment]
Found that the dart-sdk is installed in /usr/lib/dart.
I was looking under /usr/local !

So in my profile I do:

export DATK_SDK_HOME=/usr/lib/dart
export PATH=$PATH......:$DART_SDK_HOME/bin

Now pub workds as documented. Phew.
