### ISSUE TITLE
deprecated symbols should have lower priority in code completion

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33789]
When calculating code completion rankings, being deprecated should lower your score. That way `Foo.newLowerCase` will score higher than `Foo.NEW_LOWER_CASE`.

/cc @scheglov

**Comment by greglittlefield-wf** [comment]
I'd like to request the same for deprecated libraries; should I create a new issue for that, or should it be included in this one?

**Comment by bwilkerson** [comment]
> When calculating code completion rankings, being deprecated should lower your score.

That ought to be the case today. I don't know what specific case you were originally seeing, but given the following input:
```
class C {
  @deprecated
  static const int NEW_LOWER_CASE = 0;
  static const int newLowerCase = 0;
}

int f() => C.^;
```
if you remove the `^` and complete after the period the non-deprecated field will be ranked higher than the deprecated field.

> I'd like to request the same for deprecated libraries when completing imports/exports ...

Yes, that makes perfect sense. I think it's just an oversight that we aren't currently doing that.

> ... should I create a new issue for that ...

It would be good to have it as a separate issue. The code that computes available libraries isn't the same as the code that computes member access, so the two issues aren't likely to be addressed by the same CL, and it's generally best to have separate issues for separable arcs of work.

**Comment by greglittlefield-wf** [comment]
Sounds good; I've created a separate issue for that: https://github.com/dart-lang/sdk/issues/42878

Thanks!

**Comment by bwilkerson** [comment]
This appears to be working correctly, so I'm going to close it.
