### ISSUE TITLE
how to generate the SDK API doc?

### ISSUE THREAD

**Issue by wangtun** [dart-lang/sdk#33784]
* Dart SDK Version (`dart --version`)
2.0.0-0.59
* Whether you are using Windows, MacOSX, or Linux (if applicable)
macOSX 1

I want to generate a API DOC and publish it on my own server so I can open the API doc more quickly than the official website. thanks

**Comment by bkonyi** [comment]
@jcollins-g, would you happen to know if this is something that's easily doable from what's present in the SDK, or do we do something special to generate our docs?

**Comment by jcollins-g** [comment]
`dartdoc --sdk-docs` should generate those in virtually the same manner as what is uploaded.  Any differences would be specific to our serving setup I think.

**Comment by bkonyi** [comment]
Ah, thanks! I figured I was missing something simple.

@wangtun, if you clone this repository, running `dartdoc --sdk-docs` in the root of the project should generate the docs, assuming you have `dartdoc` somewhere on your path already. If not, you can always build the SDK locally using `tools/build.py`.

**Comment by jcollins-g** [comment]
@bkonyi / @wangtun Actually, you don't even need to clone the repository.  If you have the SDK installed, that's enough.
