### ISSUE TITLE
package:analyzer throws NPE on older source

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#33783]
Dart VM version: 2.0.0-dev.66.0 (Fri Jun 29 11:19:05 2018 +0200) on "macos_x64"

Run `dartanalyzer` on the package `protractor_dar` version: `0.0.1`:

           NoSuchMethodError: The getter 'length' was called on null.
           Receiver: null
           Tried calling: length
           #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
           #1      InterfaceTypeImpl.superclass (package:analyzer/src/dart/element/type.dart:1384:23)
           #2      InterfaceTypeImpl.lookUpGetterInSuperclass (package:analyzer/src/dart/element/type.dart:1702:31)
           #3      InterfaceTypeImpl.lookUpGetter (package:analyzer/src/dart/element/type.dart:1689:12)
           #4      InterfaceTypeImpl.lookUpInheritedGetter (package:analyzer/src/dart/element/type.dart:1727:16)
           #5      ElementResolver._lookUpGetter (package:analyzer/src/generated/element_resolver.dart:1783:19)
           #6      ElementResolver._resolveProperty (package:analyzer/src/generated/element_resolver.dart:2362:23)
           #7      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:2392:23)
           #8      ElementResolver.visitPrefixedIdentifier (package:analyzer/src/generated/element_resolver.dart:996:5)
           #9      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8952:49)
           #10     ResolverVisitor.visitPrefixedIdentifier (package:analyzer/src/generated/resolver.dart:6382:10)
           #11     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8952:49)

**Comment by devoncarew** [comment]
This looks like a dup of https://github.com/dart-lang/sdk/issues/33740.
