### ISSUE TITLE
dartanalyzer on old package throws '_Link' is not a subtype of type 'File'

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#33782]
Dart VM version: 2.0.0-dev.66.0 (Fri Jun 29 11:19:05 2018 +0200) on "macos_x64"

I was running `pana` on package: `shuffler` version: `0.0.1`, downloading it and running `dartanalyzer` reproduces the issue.

    SEVERE     Unhandled exception:
           type '_Link' is not a subtype of type 'File'
           #0      Driver._collectFiles (package:analyzer_cli/src/driver.dart:547:23)
           #1      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:326:11)
           #2      _RootZone.runUnary (dart:async/zone.dart:1381:54)
           #3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
           #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
           #5      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
           #6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:347:9)
           #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
           #10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

`analyzer_cli` hasn't been updated in ages, and it seems it has strong-mode errors that need to be fixed: https://pub.dartlang.org/packages/analyzer_cli#-analysis-tab-

**Comment by devoncarew** [comment]
fixed in https://dart.googlesource.com/sdk/+/3ad109038ea8d636babac2f30d34d2c5522a18f4
