### ISSUE TITLE
Unable to build the AngularDart code after Dart upgrade to 2.0

### ISSUE THREAD

**Issue by vijaychendrayan** [dart-lang/sdk#33780]
I have just upgraded to Dart version , Now I am unable to do the build, getting below error msg.
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64".
I am using Chrome browser for running my applications.

/usr/local/opt/dart/libexec/bin/pub global run webdev serve web:54909
webdev failed with an unexpected exception.
Unable to spawn isolate: file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/multimap.dart:413:5: Error: The method '_WrappedIterable::singleWhere' has fewer named arguments than those of overridden method 'Iterable::singleWhere'.
  V singleWhere(bool test(V element)) {
    ^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/delegates/iterable.dart:71:5: Error: The method 'DelegatingIterable::singleWhere' has fewer named arguments than those of overridden method 'Iterable::singleWhere'.
  E singleWhere(bool test(E element)) => delegate.singleWhere(test);
    ^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+6/lib/src/utils.dart:81:7: Error: The non-abstract class 'BatchedStreamTransformer' is missing implementations for these members:
  'cast'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BatchedStreamTransformer<T> implements StreamTransformer<T, List<T>> {
      ^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/bimap.dart:46:7: Error: The non-abstract class 'HashBiMap' is missing implementations for these members:
  'map', 'cast', 'updateAll', 'removeWhere', 'addEntries', 'update', 'entries'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class HashBiMap<K, V> implements BiMap<K, V> {
      ^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/lru_map.dart:49:7: Error: The non-abstract class 'LinkedLruHashMap' is missing implementations for these members:
  'map', 'cast', 'updateAll', 'removeWhere', 'addEntries', 'update', 'entries'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class LinkedLruHashMap<K, V> implements LruMap<K, V> {
      ^^^^^^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/multimap.dart:262:7: Error: The non-abstract class '_WrappedMap' is missing implementations for these members:
  'map', 'cast', 'updateAll', 'removeWhere', 'addEntries', 'update', 'entries'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _WrappedMap<K, V, C extends Iterable<V>> implements Map<K, C> {
      ^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/multimap.dart:294:7: Error: The non-abstract class '_WrappedIterable' is missing implementations for these members:
  'cast', 'whereType', 'followedBy'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _WrappedIterable<K, V, C extends Iterable<V>> implements Iterable<V> {
      ^^^^^^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/multimap.dart:459:7: Error: The non-abstract class '_WrappedList' is missing implementations for these members:
  '+', 'whereType', 'lastIndexWhere', 'indexWhere', 'followedBy', 'first=', 'last='.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _WrappedList<K, V> extends _WrappedIterable<K, V, List<V>>
      ^^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/quiver-0.25.0/lib/src/collection/multimap.dart:612:7: Error: The non-abstract class '_WrappedSet' is missing implementations for these members:
  'whereType', 'followedBy'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _WrappedSet<K, V> extends _WrappedIterable<K, V, Set<V>>
      ^^^^^^^^^^^
file:///Users/vijayc/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+3/lib/src/utf_stream.dart:121:7: Error: The non-abstract class 'Utf8DecoderTransformer' is missing implementations for these members:
  'cast'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class Utf8DecoderTransformer extends _StringDecoder {
      ^^^^^^^^^^^^^^^^^^^^^^
Dart Dev Server terminated

**Comment by matanlurey** [comment]
The version of packages you are using are quite old (`quiver` is now on `0.29.0+1`).

Please utilize the latest Dart2-compatible packages and use a `pub upgrade`. Feel free to open another issue if the problem persists, but I'm nearly certain you are just using outdated packages.
