### ISSUE TITLE
create three new analyze cfe bots

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33792]
We'd like three new bots:

- `analyzer-use-cfe-linux`
- `analyzer-use-cfe-mac`
- `analyzer-use-cfe-win`

We don't expect that these would be on the main waterfall immediately, but we'd like them available to start setting them up (with a target for the main waterfall of 3-4 weeks away). Thanks!

@athomas @whesse 

/cc @bwilkerson @kmillikin

**Comment by athomas** [comment]
The last comment referred to https://github.com/dart-lang/sdk/issues/33791 so I'm re-opening this issue and closing the other one.

**Comment by devoncarew** [comment]
Oops, thanks - closed the wrong one.

**Comment by athomas** [comment]
I've created the builders, and they are in "choose tryjobs" now. They obviously don't work until they have an entry in test-matrix.json. Once they do, I can add them to the consoles and setup the commit triggers.

**Comment by devoncarew** [comment]
The CL to provide initial content for the bots has landed: https://dart-review.googlesource.com/c/sdk/+/67580

@athomas, if the bots look good, I think we can move them to the main waterfall at your convenience.
