### ISSUE TITLE
set up three new analyzer bots

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33791]
We'd like to split our tests across two sets of bots in order to speed up their cycle time. Specifically, we'd like three new bots:

- `analyzer-testing-linux`
- `analyzer-testing-mac`
- `analyzer-testing-win`

Once these are set up we'll refactor `analyzer-linux-release`, `analyzer-mac-release`, `analyzer-win-release` to split testing across them.

@athomas @whesse

**Comment by athomas** [comment]
This has been superseded (the bots got faster just via some sharding).
