### ISSUE TITLE
gracefully detect and report errors when snapshots were built with a different vm

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33797]
This issue came up in the context of pub-run/pub-global activate. The latter creates a snapshot and latter runs it. If the snapshot and the vm have different versions, we simply get a vm-crash.

Example repro:
* install some sdk (e.g. version 2.0.0-dev.55.0)
* install a tool via pub-global-activate, e.g. `pub global activate webdev`
* upgrade to a different sdk (e.g. version 2.0.0-dev.67.0)
* run the tool

You can get errors like:
```
./../runtime/vm/kernel_binary.cc: 39: error: Invalid kernel binary format version (found 8, expected 5)

===== CRASH =====
version=2.0.0-dev.55.0 (Mon May 14 09:23:07 2018 +0200) on "linux_x64"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
Aborting re-entrant request for stack trace.
/path/to/.pub-cache/bin/webdev: line 7: 121316 Aborted                 dart "/path/to/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot.dart2" "$@"

```

/cc @a-siva @munificent

**Comment by a-siva** [comment]
The CL https://github.com/dart-lang/sdk/commit/f67308a983a2a7d8f4645702d34fba36e41b0c56
fixed this by returning error codes instead of a fatal error.
Do you still see issues after this change?

**Comment by sigmundch** [comment]
Thanks! I believe so, yes.

We haven't had a new breaking format released in the -dev channel since this fix was in, but it seems to be working in bleeding-edge.

**Comment by munificent** [comment]
Yes, this is working as expected in pub now. Thanks for the fix!
