### ISSUE TITLE
Fasta loses annotations for parameters of redirecting factory constructors

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33800]
The following code produces kernel that does not have annotations on `p`.

```dart
class C {
  factory C(@a p) = C.named;
  C.named(p);
}

const a = 1;
```

Gives:
```kernel
class C extends core::Object {
  static factory •(@self::a dynamic p) → self::C
    return null;
}
static const field core::int a = 1;
```

But this code has annotations on formal parameters.
```dart
class C {
  factory C(@a p) => null;
}

const a = 1;
```
Gives:
```kernel
class C extends core::Object {
  static factory •(@self::a dynamic p) → self::C
    return null;
}
static const field core::int a = 1;
```

**Comment by stefantsov** [comment]
Thanks for filing the issue.  It's indeed a bug in the front end.  I've worked on both the annotations on parameters and redirecting factories, so it's not hard for me to fix this one.  I plan to start work on it tomorrow.

Also, I believe there's a wrong compile output for the first program.  I think it should be something like the following:

```kernel
library;
import self as self;
import "dart:core" as core;

class C extends core::Object {
  static field dynamic _redirecting# = <dynamic>[self::C::•];
  constructor named(dynamic p) → void
    : super core::Object::•()
    ;
  static factory •(dynamic p) → self::C
    let dynamic #redirecting_factory = self::C::named in invalid-expression;
}
static const field core::int a = 1;
```

**Comment by scheglov** [comment]
Right, I copied the wrong output for the first example.

**Comment by stefantsov** [comment]
I believe I have a fix for that in [CL 65540](https://dart-review.googlesource.com/c/sdk/+/65540).
