### ISSUE TITLE
disabled two failing analyzer summary tests

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33804]
We disabled two failing analyzer summary tests - these starting failing when we switched the analyzer to strong mode only, but pass when the analyzer is run with --use-fasta-parser. Additionally, they _may_ be using previous state from disk, as I've seen the tests pass sometimes when I thought they should have failed.

CL to disable: https://dart-review.googlesource.com/c/sdk/+/64360

@scheglov @bwilkerson

**Comment by bwilkerson** [comment]
@devoncarew With the fasta parser enabled by default, can we re-enable these tests now?

**Comment by devoncarew** [comment]
I can convert them back to normal `@failingTest`s. It looks like they depend on !previewDart2. I don't know the value of the tests - if they should be updated to work in previewDart2 or deleted.
