### ISSUE TITLE
android_error

### ISSUE THREAD

**Issue by BlueSky-YJS** [dart-lang/sdk#33801]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1200, 1366x768`

**Comment by matanlurey** [comment]
Can you please re-open a new ticket with the error information, i.e. stack trace or what not?

If this is Android/Flutter specific, please re-open it at github.com/flutter/flutter instead.
