### ISSUE TITLE
Analyzer needs a way to merge and flush metadata during incremental compilation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33803]
Analyzer uses its own Kernel metadata, and needs to carry this metadata with newly compiled libraries into the existing Component. We solved this issue in [Analyzer for now](https://github.com/dart-lang/sdk/commit/5403f654aea2764cf41381caa1a98ee6951d6df4), but it CFE thinks that this is something that should be implemented by CFE itself, this issue can be used for tracking.

We also need a way to flush portions of metadata that are associated with nodes in libraries that are invalidated, so to avoid memory leak.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
