### ISSUE TITLE
Test analyzer_cli/build_mode_test not compatible with protobuf 0.9.0

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#33814]
The test `pkg/analyzer_cli/build_mode_test.dart` uses the `writeRawBytes` method which was removed from the protobuf packagin in version 0.9.0.

To fix this, maybe look at how the package bazel_worker was fixed to be compatible.

**Comment by devoncarew** [comment]
@lrhn, this should have been fixed before you committed. Build mode in the analyzer isn't optional, and drives a lot of the google3 workflow.

**Comment by devoncarew** [comment]
OK, this is just breaking the test, not build mode itself.
