### ISSUE TITLE
A way to know that a Procedure is a synthetic loadLibrary() invoker

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33825]
```dart
import 'dart:math' deferred as math;

main() {
  var f = math.loadLibrary;
}
```

Generates:

```Kernel
import self as self;
import "dart:async" as asy;

static method main() → dynamic {
  dynamic f = self::__loadLibrary_math;
}
static method __loadLibrary_math() → asy::Future<dynamic>
  return LoadLibrary(math);
```

For now Analyzer filters it out [using `name.startsWith('__loadLibrary_')`](https://dart-review.googlesource.com/c/sdk/+/64640/3/pkg/analyzer/lib/src/dart/element/element.dart#1719), but this is not fully correct - it is possible to have real, not synthetic functions named like this.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
