### ISSUE TITLE
Null reference exception in ThreadLocalData::RunDestructors on Windows

### ISSUE THREAD

**Issue by clarkezone** [dart-lang/sdk#33826]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.58.0.flutter-f981f09760 (Sat May 26 03:16:14 2018 +0000) on "windows_x64"
[note it's the version that is bundled with any particular version of flutter]

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A  This is in conjunction with Dart Embedding (tracked by this issue: https://github.com/google/flutter-desktop-embedding/issues/101)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

I've encountered this issue while developing a Windows version of Flutter Desktop Embedding.  Because loading flutter_engine.dll hooks thread termination, it is possible that a thread can be created and exit before Dart has been initialized.  This causes a null reference exception in ThreadLocalData::RunDestructors.  A reduced repro that shows it is as follows:

```
#include "stdafx.h"
#include "flutter_embedder.h"


DWORD WINAPI ThreadProc(CONST LPVOID lpParam) {
	return 0;
}

int __stdcall wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int)
{
	CreateThread(NULL, 0, &ThreadProc, 0, 0, NULL);

	Sleep(250);
	
	return 0;

	// FlutterEngineRun below will never get called but will cause flutter_engine.dll to be loaded on process start which will, in turn, 
	// hook DLL_THREAD_DETACH via the PIMAGE_TLS_CALLBACK mechanism which in turn calls ThreadLocalData::RunDestructors when ThreadProc returns.
	// If you look in dart-lang\sdk\runtime\vm\os_thread_win.cc you will see that, in this case, ThreadLocalData::InitOnce hasn't been called yet
	// which will trigger a nullref exception in ThreadLocalData::RunDestructors.
	FlutterProjectArgs args{};
	FlutterRendererConfig render{ FlutterRendererType::kOpenGL };
	FlutterEngine mEngine{ nullptr };
	
	auto result = FlutterEngineRun(FLUTTER_ENGINE_VERSION, &render, &args, nullptr, &mEngine);
}
```
I've developed a fix here:

https://github.com/clarkezone/sdk/commit/42f67a7628ef98915989b7f46cf5a8722aa04bf1

Please let me know how to proceed from here,

thx

James

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by bkonyi** [comment]
Should be fixed in [this CL](https://dart-review.googlesource.com/c/sdk/+/65171). Thanks @clarkezone!
