### ISSUE TITLE
CFE does not report error when a setter's parameter type is not assignable to the corresponding getter's return type.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#33836]
Example:
```dart
class C {
  String get foo => "42";
  void set foo(int x) {}
}
main() {
  new C().foo;
  new C().foo = 42;
}
```
This should cause an error.
The spec says:
>It is a compile-time error if a class has a setter named *v*= with argument type *T* and a getter named *v* with return type *S*, and *S* may not be assigned to *T*.

The analyzer shows a warning.

**Comment by natebosch** [comment]
cc @dgrove @leafpetersen 

If we plan on fixing this post Dart 2.0 it will be breaking.

**Comment by leafpetersen** [comment]
Will the analyzer switch warnings to errors before Dart 2?  @devoncarew 

If not, we need to treat doing so later as a non-breaking change.  As long as the analyzer gives an error about this though, the missing CFE error isn't blocking.

**Comment by devoncarew** [comment]
> Will the analyzer switch warnings to errors before Dart 2?

Right now we're showing the severity levels from strong mode:

> It is a compile-time error

I don't know if this is an isolated bug or we need to promote a group of warnings to errors. Either way, it's an easy fix.

> If not, we need to treat doing so later as a non-breaking change.

A warning is already a failing severity from the POV of dartanalyzer, so promoting it to an error won't be hugely breaking for users.

**Comment by devoncarew** [comment]
For posterity, this is the `mismatched_getter_and_setter_types` error code.

**Comment by natebosch** [comment]
> A warning is already a failing severity from the POV of dartanalyzer, so promoting it to an error won't be hugely breaking for users.

I can't repro. When I run `dartanalyzer` and it prints a warning I get a zero exit code. Internally we probably default to `--fatal-warnings` but that is not the default externally.

**Comment by devoncarew** [comment]
No, you're right, I see that `--fatal-warnings` defaults to false.

**Comment by dgrove** [comment]
Bringing back into Dart2Stable

**Comment by devoncarew** [comment]
It looks like the warning ==> error spec changed happened recently: https://github.com/dart-lang/sdk/commit/a07b2a10c6da58e0f3c461d778e51b128e2772a5. I'll open an issue for this.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/sdk/issues/33837

**Comment by devoncarew** [comment]
But I'm not sure the CFE portion of this needs to be in dart2 stable.

**Comment by dgrove** [comment]
Since the analyzer issue #33837 is in Dart2Stable, this doesn't need to be.

**Comment by natebosch** [comment]
I'm guessing this is unplanned since the decision was made to keep this a warning.
