### ISSUE TITLE
Need to get target-arm64 builder to Luci + strong mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33832]
Our current [target-arm64-vm-linux-release](https://ci.chromium.org/buildbot/client.dart/target-arm64-vm-linux-release-be/) builder is still running on buildbot and is using `--checked` mode. We should get it to luci and use Dart 2.0 testing on it.

It causes various issues, also in blown up status files, due to the usage of `--checked`.

/cc @mraleph

**Comment by athomas** [comment]
It's already using Dart 2.0 testing (I switched it to -cdartk a while a go as requested by @mraleph).

I removed the --checked step in the recipe. I didn't move the bot to Luci because we don't have the required hardware on Luci, yet.

**Comment by athomas** [comment]
Luci migration of the bot will happen as part of https://crbug.com/893675.

Then this task is ready to be completed.

**Comment by athomas** [comment]
Luci migration is completed. The target-arm64 bot has been merged into the cross-arm64 bot.
