### ISSUE TITLE
dart2 analyser does not report an error

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#33847]
Dart analyzer does not report an error when a function with one parameter is invoked and the type of an actual argument is not a subtype of a formal argument type. Generated code reports a run-time exception **_type 'S0' is not a subtype of type 'Future<S0>'_**.

```dart
import "dart:async";

class S0 {}
FutureOr<S0> t0Instance = new S0();
// S0 is not a subtype of Future<S0>
Future<S0> t1Instance = new Future<S0>.value(new S0());
f1(Future<S0> t1) {}

main() {
  f1(t0Instance);     // <- exception
}
```

> dart test.dart
Unhandled exception:
type 'S0' is not a subtype of type 'Future<S0>'
#0      main (file:///home/ngl/dart_wd/dtests/co19/LanguageFeatures/Subtyping/static/generated/ztest1.dart:10:6)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Tested with Dart VM version: 2.0.0-dev.68.0 (Tue Jul 10 14:47:26 2018 +0200) on "linux_x64"

**Comment by matanlurey** [comment]
This is an [implicit downcast](https://github.com/dart-lang/sdk/issues/31410), a feature of Dart2.

Because `FutureOr<S0>` _could_ be a `Future<S0>`, it is allowed and checked at runtime.

Issue #31410 is tracking removing and augmenting this in future versions of Dart/the analyzer.
