### ISSUE TITLE
The 'exists' implementation in '_IoFileSystemEntity' returns false for 'file:///dev/fd/0'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33842]
The code in 'exists' of '_IoFileSystemEntity' returns false for '/dev/fd/0'

see code below on how we get false

> import 'dart:io';
> 
> main() async {
>   String devFd0Path = '/dev/fd/0';
>   bool result = await FileSystemEntity.isFile(devFd0Path);
>   print("$devFd0Path is file? $result");
>   File devFd0 = new File(devFd0Path);
>   bool devFd0Exists = devFd0.existsSync();
>   print("$devFd0Path exists? $devFd0Exists");
> }
> /dev/fd/0 is file? false
> /dev/fd/0 exists? true

The test standalone_2/io/named_pipe_script_test.dart fails with the error
Expect.fail('Error: Input file not found: file:///dev/fd/0.');

I also noticed that the incremental compiler does not call validateOptions as a result of which
this test works when the incremental compiler is used.

**Comment by peter-ahe-google** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/65082
