### ISSUE TITLE
Update all dartlang packages to declare an `<3.0.0` SDK constraint

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#33843]
We need to update all packages we maintain from using an `<2.0.0` SDK upper bound to using an `<3.0.0` upper bound, to ensure packages will resolve with Dart 2 stable.

**Comment by mit-mit** [comment]
cc @kevmoo can you drive this? I'm out the next three weeks...

**Comment by kevmoo** [comment]
I'm on it! CC @dgrove

**Comment by dgrove** [comment]
Removing p1-high label, as this won't block the Dart 2 Stable branch. We will need this before shipping Dart 2.0.0 .

**Comment by vsmenon** [comment]
Any update on this?
