### ISSUE TITLE
Dart Analyzer - FlutterAnalyze-Repository possible regression

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33854]
We need to look into whether the Dart Analyzer - FlutterAnalyze-Repository performance CI benchmark has regressed; the results seem suspicious.

**Comment by devoncarew** [comment]
@sortie, I'm unable to locate the source for this benchmark right now, but I suspect that we're not clearing the analysis driver cache before a benchmark run. This would give the approx performance we're seeing on the graph. We do want to measure a cold start for the analysis server - with no previous analysis summaries on disk.

I'm assigning to you to ping me when you're back. I'd like to verify that this is what's occurring, and then clear the driver cache (`rm -rf ~/.dartServer/.analysis-driver/`) before each benchmark run. This will give us results that match what we want to track for Flutter.

**Comment by sortie** [comment]
Benchmarks shouldn't have hidden persistent state, great that you discovered this!

The current directory when benchmarks are run is temporary and is deleted automatically. We should redirect all state to that directory and not rely on the home directory and other places, so we know avoid hidden persistent state.

Is there an environment variable or command line parameter that controls the location of ~/.dartServer/.analysis-driver? Setting that to the benchmarking directory would be the best option in my opinion. If there isn't, possibly we can do it by setting `$HOME` to the benchmark directory.

**Comment by sortie** [comment]
cc @mraleph

**Comment by devoncarew** [comment]
> Is there an environment variable or command line parameter that controls the location of ~/.dartServer/.analysis-driver?

There isn't, but that's something that we could add.

When we benchmark this in other situations, we do clear the driver cache as part of the benchmark, so that would also be a good way of solving this.

**Comment by devoncarew** [comment]
@sortie, the change to add an env. variable override for the analysis driver's cache landed here: https://dart-review.googlesource.com/c/sdk/+/70540

**Comment by sortie** [comment]
I've rebased the flutter-analyze changelist and added support for the environment variable. I ran out of time today and need to do the final touches.

**Comment by sortie** [comment]
The flutter-analyze CL now takes full advantage of this environment variable.

**Comment by devoncarew** [comment]
👍, looking forward to seeing that land
