### ISSUE TITLE
Possible to run dart scripts standalone?

### ISSUE THREAD

**Issue by jordyvandomselaar** [dart-lang/sdk#33853]
I'd like to distribute a CLI tool written in dart to systems that do not have the Dart SDK installed. Is it possible to ship a prepackaged Dart SDK or something with it so it can run as intended?

**Comment by matanlurey** [comment]
No, it is not (directly) possible. I can close as a duplicate of #27596.

(The other option is copying what dart-sass does: https://github.com/sass/dart-sass#standalone)
