### ISSUE TITLE
CHANGELOG should call out that `pub run` executes programs with Dart 2.0 semantics

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#33850]
The [CHANGELOG](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#200-dev641) for 2.0.0-dev.64.1 calls out that the VM now runs "Dart 2" by default:

> The Dart VM now runs programs by default with Dart 2.0 semantics.

And the 2.0.0-dev.65 entry calls out:

> Pub no longer supports running with DART_VM_OPTIONS=--no-preview-dart2.

But I don't think either entry makes it clear to users (especially those not on the Dart team), that a command such as `pub run test` will now execute code (both the test program and the tests themselves) with Dart 2.0 semantics.

**Comment by srawlins** [comment]
Assigning to @a-siva, who wrote the changelog entry in dev.64.1 for the VM.

**Comment by natebosch** [comment]
`pub run` has always had the same default as `dart` - I never have personally felt the need to call them out separately when documenting the difference.

Do we expect this will have much impact since Dart 2 will soon be the only mode?

**Comment by srawlins** [comment]
If I was the only person confused about this, we don't need to document it.

I doubt that `--no-preview-dart-2` will be removed in Dart 2.0.

**Comment by natebosch** [comment]
> I doubt that `--no-preview-dart-2` will be removed in Dart 2.0.

I think we are counting on the fact that it will be or we're going to be stuck with a lot of legacy code until Dart 3.0

**Comment by srawlins** [comment]
It definitely wasn't.

**Comment by a-siva** [comment]
Where should we document this to clarify further that 'pub run' now runs only in Dart 2 mode.
We expect to get rid of the --no-preview-dart-2 option in the next upgrade release (2.1 is what I think it will be called).

**Comment by natebosch** [comment]
I think we missed our window on this. At this point we've communicated that Dart 2 is the only mode and `--no-preview-dart-2` is at least not advertised even if it works.

I don't think there is action for us to take.
