### ISSUE TITLE
math.pow has poor performance with ints compared to doubles

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#33861]
math.pow takes twice the time on ints than on doubles.

```
import 'dart:math';

main() {
  Stopwatch stopwatch = new Stopwatch()..start();
  for (int i = 0; i < 1000000000; ++i) {
    // double x = i * 1.0;
    int x = i;
    pow(x, 3);
  }
  print('executed in ${stopwatch.elapsed}');
}
```
With x as an int, it takes around 6.8 seconds on my machine.

```
import 'dart:math';

main() {
  Stopwatch stopwatch = new Stopwatch()..start();
  for (int i = 0; i < 1000000000; ++i) {
    double x = i * 1.0;
    // int x = i;
    pow(x, 3);
  }
  print('executed in ${stopwatch.elapsed}');
}
```
With x as a double, it takes 2.8 seconds.

I would expect ints and doubles to have comparable performance.

* Dart SDK Version (`dart --version`)

Dart VM version: 2.0.0-dev.63.0.flutter-4c9689c1d2 (Mon Jun 18 15:50:02 2018 +0000) on "macos_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)

MacOSX

**Comment by lrhn** [comment]
This is just the double version hitting an optimization.
if I change the power from 3 to 4, then the integer version time goes from 6.7 seconds to 10.9 seconds, and the double version goes from 2.6 seconds to 39.1 second.

You're just hitting this line in `_doublePow` which doens't have a corresponding line in `_intPow`:
```dart
if (exponent == 3.0) return base * base * base;
```
(I'd be surprised if that rewrite is actually correct for all doubles).

So, honestly, the double version is the horrendously the slow one here. 
We can add the 1/2/3 power optimization to integers as well. If we do that ... nothing changes. It might actually be a tiny bit slower.

**Comment by SteveAlexander** [comment]
Fascinating. Thanks for the explanation!

**Comment by aartbik** [comment]
Indeed, _doublePow() starts with a few special cases, some of which are there to enforce IEEE, others are there to get better performance.
```dart
  if (exponent == 0.0) {
    return 1.0; // ECMA-262 15.8.2.13
  }
  // Speed up simple cases.
  if (exponent == 1.0) return base;
  if (exponent == 2.0) return base * base;
  if (exponent == 3.0) return base * base * base;

```
The integer version _intPow() has no such paths.

My proposal is to
(1) mostly rely on inlining/constant folding of parameters for performance while adhering to the standard
(2) make the compiler more aware of  _intPow() semantics to allow specialization of very obvious fast paths.

This avoids falling into IEEE pitfalls for floating-points while helping the integer case somewhat. Moreover, usually this only helps benchmarks, although occasionally it may trigger in user code when several stacked methods with a power operation in a leaf are inlined.

**Comment by aartbik** [comment]
Some _current_ timings for the records. Also exposes an AOT issue.

**JIT:**
```
$ dart power.dart --int
INT executed in 0:00:07.268897
$ dart power.dart 
FP executed in 0:00:02.914776
```
**AOT:**
```
$ precompiler2 power.dart ./snap
$ dart_precompiled_runtime2 ./snap --int
INT executed in 0:01:26.812500                   OUCH!
$ dart_precompiled_runtime2 ./snap 
FP executed in 0:00:08.337010
```

**Comment by aartbik** [comment]
@a-siva @alexmarkov @mraleph

**Comment by aartbik** [comment]
One last bit of information before I start the work, the double case is also optimized inside the compiler (not just the library), as recognized "MathDoublePow" intrinsic. So it makes extra sense to do the same for the int case.

**Comment by aartbik** [comment]
I also fixed the AOT issue, which was due to speculation, which forced a recompilation in which pow() was no longer optimized. After the fix, this brings the runtimes down to:

**JIT:**
```
$ dart power.dart --int
INT executed in 0:00:01.007383
$ dart power.dart 
FP executed in 0:00:02.941543
```
**AOT:**
```
$ precompiler2 power.dart ./snap
$ dart_precompiled_runtime2 ./snap --int
INT executed in 0:00:01.374013
$ dart_precompiled_runtime2 ./snap 
FP executed in 0:00:08.788383
```

**Comment by aartbik** [comment]
Even though we can obviously continue to improve pow() performance as we go, all surprising performance differences of this bug have been addresses.

**Comment by aartbik** [comment]
I had to revert since simarm does not like the test.
