### ISSUE TITLE
Dart does not throw error if parameter of incorrect type is passed to the function.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33863]
Dart SDK Version: 2.0.0_dev.68.0
OS: Windows 10

The following sample code example declares a function with `<X extends int>` parameter and than calls it with the `String` argument:
``` dart
testme<X extends int>(X x) {}
main() { testme("incorrect param"); }
```
It expectidly fails with dartanalyzer - indeed, `String` does not extend `int`:
```
Analyzing test.dart...
  error - Couldn't infer type parameter 'X'.

Tried to infer 'String' for 'X' which doesn't work:
  Type parameter 'X' declared to extend 'int'.
The type 'String' was inferred from:
  Parameter 'x' declared as     'X'
                but argument is 'String'.

Consider passing explicit type argument(s) to the generic.

 at test.dart:2:10 - strong_mode_could_not_infer
1 error found.
```
However, this incorrectly passes with dart - any errors and warning. I believe dart should throw a error here too.

Please note that this is similar with the issue #33597 which is about function return parameter. There dartanalyzer does **not** throw a compiler error (and dart throws it as expected) and the situation is a mirror with one described here.

**Comment by lrhn** [comment]
Seems to be a missing error from the front-end. Likely know already, but they'll know which bug is the canonical one.

**Comment by askeksa-google** [comment]
The missing check against bounds is covered by https://github.com/dart-lang/sdk/issues/33308
