### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#33867]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.0.0-dev.68.0`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1920x1200, 3840x2160  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report.txt
[report.txt](https://github.com/dart-lang/sdk/files/2197960/report.txt)

```
Dart analysis server, SDK version 2.0.0-edge.84ca27a09ebd6a65cd23ee52d835d89cbe06c574, server version 1.20.3, error: Could not initialize the library map from [/Users/zoechi/flutter/flutter/bin/cache/dart-sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart, /Users/zoechi/flutter/flutter/bin/cache/dart-sdk/lib/_internal/libraries.dart]

FileSystemException(path=/Users/zoechi/flutter/flutter/bin/cache/dart-sdk/lib/_internal/libraries.dart

**Comment by bwilkerson** [comment]
I assume that this is stale. Please let me know if that's not the case.
