### ISSUE TITLE
Analyzer unexpectedly fails when calls row Callable function.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33865]
Dart SDK Version: 2.0.0_dev.68.0
OS: Windows 10

The following sample code example declares callable class with parametrized `call` method:
``` dart
class F1 {
  X call<X>() { return null; }
}

X fff<X>() { return null; }

main() {
  F1 func = new F1();
  int i = fff();
  int ii = func();
  int iii = func.call();
}
```
Dart passes with this and it seems like it's a correct result.

Dartanalyzer throws unexpected error on the   `int ii = func();`, sample output is:
```
Analyzing test.dart...
  error - A value of type 'X' can't be assigned to a variable of type 'int' at test.dart:10:12 - invalid_assignment
  hint - The value of the local variable 'i' isn't used at test.dart:9:7 - unused_local_variable
  hint - The value of the local variable 'ii' isn't used at test.dart:10:7 - unused_local_variable
  hint - The value of the local variable 'iii' isn't used at test.dart:11:7 - unused_local_variable
1 error and 3 hints found.
```
I believe this is incorrect behavior, `int i = fff();`, `int ii = func();` and `int iii = func.call();` should work in the same way.

**Comment by iarkh** [comment]
I am not able to reproduce this issue with the recent dev build (2.0.0-dev.69.1). So should I close this?

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let me know if that's not the case.
