### ISSUE TITLE
Don't desugar function-typed formal parameters in the parser.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#33873]
Consider a function typed formal parameter such as this:

```dart
void f([returnType name(formalParameters) = defaultValue])
```

Currently the set of events fired by the front end parser for a function-typed formal parameter is as follows:

- `beginMetadataStar`
- `endMetadataStar`
- `beginFormalParameter`
- `beginFunctionTypedFormalParameter`
- Event(s) for `returnType`
- Event(s) for `formalParameters`
- endFunctionTypedFormalParameter
- Event for `name`
- beginFormalParameterDefaultValueExpression
- Event(s) for `defaultValue`
- endFormalParameterDefaultValueExpression
- handleValuedFormalParameter
- endFormalParameter

The order of these events doesn't reflect the syntax of the language, since the event for `name` occurs after the events for `formalParameters` and after the call to `endFunctionTypedFormalParameter`.  Essentially what is happening is that the parser is desugaring the declaration so that it looks more like

```dart
void f([returnType Function(formalParameters) name = defaultValue])
```

This forces the AstBuilder to jump through some hoops in order to create an analyzer AST reflecting the syntax the user actually used (see discussion at https://dart-review.googlesource.com/c/sdk/+/65162/1/pkg/analyzer/lib/src/fasta/ast_builder.dart#1233).  Similar hoops will be required in the BodyBuilder once we transition to the factory technique of building fully resolved analyzer ASTs directly from the BodyBuilder's judgment tree.

I think we should change the order of parser events to match the syntax, e.g.:

- `beginMetadataStar`
- `endMetadataStar`
- `beginFormalParameter`
- `beginFunctionTypedFormalParameter`
- Event(s) for `returnType`
- Event for `name`
- Event(s) for `formalParameters`
- endFunctionTypedFormalParameter
- beginFormalParameterDefaultValueExpression
- Event(s) for `defaultValue`
- endFormalParameterDefaultValueExpression
- handleValuedFormalParameter
- endFormalParameter

Then it will be the responsibility of the listener to do the desugaring (if desired), just like we do for all other desugaring.

**Comment by bwilkerson** [comment]
@danrubel (in case you're interested and missed it)

**Comment by peter-ahe-google** [comment]
I disagree that the BodyBuilder will need to be updated to generate analyzer ASTs.

Regardless, it is certainly premature to consider changing this:

* You have a working implementation, and thus no business case for making any changes.
* Resolution in the BodyBuilder relies heavily on the order of these events, and we've deliberately reordered the events to enable fast one-pass resolution.

**Comment by devoncarew** [comment]
Thanks for the thoughts here Peter. However, I am going to re-opn this issue to foster further discussion.

> thus no business case for making any changes

I don't agree with this.

**Comment by peter-ahe-google** [comment]
If you don't agree, please explain the business case.

**Comment by peter-ahe-google** [comment]
It is my opinion that this change isn't necessary. Furthermore, no business case has been provided to motivate this change. Code "jumping through hoops" or speculation about how this will evolve in the future isn't a business case. That's simply a subjective statement about code feel (which shouldn't be confused with code health).

The suggestion will complicate the current implementation, and it's unlikely that it will change in the future as the current behavior unifies handling of formal parameters, including generalized function types.

However, since it is clearly more important that this issue remains open, than responding to arguments or action is taken, I've updated the priority and labels to reflect the fact that no further action is likely to occur on this issue.

One can wonder why an issue is kept open "foster further discussion" when no discussion is actually happening.

**Comment by devoncarew** [comment]
Thanks for not closing the issue again.

Our bar here for opening issues and considering API changes isn't meeting some type of business case criteria, it's if we can see a way that the APIs can better support analyzer integration. If the APIs doesn't support what we'll need for integration, or don't support things as well as they could, then we'll consider API changes as part of the solution.

**Comment by devoncarew** [comment]
re: 

> Resolution in the BodyBuilder relies heavily on the order of these events

and

> as the current behavior unifies handling of formal parameters, including generalized function types

we're happy to have this feedback - this does help estimate the cost of changes vs issues we're currently seeing, and to know reasons for the current behavior
