### ISSUE TITLE
improve the training of the analysis server's appjit snapshot

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33871]
Currently we train it on `--help` (https://github.com/dart-lang/sdk/blob/master/utils/analysis_server/BUILD.gn#L10); we should improve the training so that it covers code paths that will get hot when analyzing large apps.

@bwilkerson @mkustermann

**Comment by devoncarew** [comment]
@bwilkerson, do you have thoughts about how to approach this? Currently I would likely either take the tack of reviving the `--one-shot` CL, which would exercise the right code paths, or do something similar to the CL but have a much more targeted flag - something like a `--training` flag w/ no params.

**Comment by bwilkerson** [comment]
Despite my reluctance to have a `--one-shot` mode :-), I like the idea of a `--training` feature.

It might want to take a parameter, though, which would allow us to specify one or more targets to analyze. I don't know how much of a difference there is in terms of code style between a web app and a flutter app, but it might produce better all-around results if we had multiple different apps to train against.

The other question is what `--training` would actually do. It's certainly useful to fully analyze the targets and get back diagnostics, but it might also be useful to automate making a few code completion requests, etc. We don't have to do everything (anything we do will be an improvement over what we currently do), but exercising some of the more critical paths should help performance.

**Comment by devoncarew** [comment]
OK, perhaps something like a `--train-with <path>` arg. I don't think we'd need to train it on much more than we'd need for a quick startup, but we can also adjust the training algorithm over time.

**Comment by devoncarew** [comment]
landed
