### ISSUE TITLE
DDC/Pageloader: Cannot create reified `List<T>`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33872]
This is blocking removing the DDC runtime type cast warning whitelist internally.

For legacy clients, DDC supports a subset of the `dart:mirrors` API if `package:pageloader` is used. We are working on removing usage, as folks are aware, but as @dgrove and @vsmenon have mentioned, we are unlikely to "pull the plug" anytime soon.

`dart:mirrors::reflectType`'s API is defined as:

```dart
external TypeMirror reflectType(Type key, [List<Type> typeArguments]);
```

But [DDC patches it as][2]:

```dart
@patch
TypeMirror reflectType(Type key) { /* ... */ }
```

[1]: https://api.dartlang.org/dev/2.0.0-dev.68.0/dart-mirrors/reflectType.html
[2]: https://github.com/dart-lang/sdk/blob/875abcea3924e94b60bfbb003467542af9d983d8/pkg/dev_compiler/tool/input_sdk/patch/mirrors_patch.dart#L45-L51

This causes a build failure when attempting to use the `typeArguments` parameter:

```
[error] Too many positional arguments: 1 expected, but 2 found. (package:pageloader/src/core.dart, line 337, col 29)
```

Unfortunately it looks like this is blocking fixing PL2, so I'd need this fixed.

(There is probably another issue here - why does patching not verify the signatures match?)

/cc @jmesserly

**Comment by matanlurey** [comment]
Another option is I could try and use [`dart:_internal's` `extractIterableTypeArguments`][1]:

... and use a `<List>.cast` instead of mirrors to create this type.

[1]: https://pub.dartlang.org/documentation/dart_internal/latest/extract_type_arguments/extractIterableTypeArgument.html

**Comment by jmesserly** [comment]
> There is probably another issue here - why does patching not verify the signatures match

DDC+Analyzer patching is based on the AST. For Analyzer it would be infeasible to do validation (would need to patch first, then load two SDKs and compare them, but there isn't a well spec'd version of what comparison would mean, and loading two resolved Dart SDKs simultaneously is not well supported.) I guess CFE doesn't validate patches either, possibly for similar reasons.

Whoever added this should've added it to the DDC patch or at least filed a bug. Thanks for reporting. It's probably not a difficult fix.

**Comment by matanlurey** [comment]
Thanks! To be clear I'm also open to any other workarounds/ideas you have :)

Here is the code in question:
https://github.com/google/pageloader/blob/1897c5190e8d50945e6b84f081bb2d18263a7044/dart/async/lib/src/core.dart#L320-L329

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/65201
