### ISSUE TITLE
Class parameter does not affect methods of the given class in some cases.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33880]
Dart SDK Version: 2.0.0_dev.68.0
OS: Windows 10

The following code sample declares class `C<X>`, create `C<int>` instance and assigns parametrized `call` function to the `String` variable:
```dart
class C<X> {
  X call() { return null; }
}

main() {
  C c = new C<String>();
  int i1 = c.call();
  int i2 = c();
}
```
This test  should fail both on `int i1 = c.call();` and `int i2 = c();` calls because `X` type is set to `String` during the `c` object creation, so `c.call()` should return `String` object and so it should be impossible to assign it to `int` variable.

However, it does not happen: both dart and dartanalyzer pass here.

Please note that the following example passes with analyzer (is it a bug?) and fails with dart:
```dart
class C<X> {
  call(X x) { return null; }
}

main() {
  C c = new C<String>();
  c.call(12345);
  c(12345);
}
```
Dart sample output is:
```
Unhandled exception:
type 'int' is not a subtype of type 'String' of 'x'
#0      C.call (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/Callable/test.dart)
#1      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/Callable/test.dart:7:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by lrhn** [comment]
The type of `c` is `C<dynamic>` because there is no inference on raw types.
The code says `C c = `, and that first `C` is expanded to `C<dynamic>`.
You are allowed tor assign a `C<String>` to `C<dynamic>` and you are allowed to assign `dynamic` (the return type of `C<dynamic>.call`) to `int`, and the actual value is `null`, so everything works.

See also #33119.
33119
