### ISSUE TITLE
The getter 'isBoolNumStringOrNull' was called on null

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33885]
_From @lejard-h on July 17, 2018 13:23_

After upgrading to angular beta from angular alpha and dart-2.0.0-dev68

I have the following error at compile time.

```
NoSuchMethodError: The getter 'isBoolNumStringOrNull' was called on null.
Receiver: null
Tried calling: isBoolNumStringOrNull
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      CodeGenerator._emitSimpleIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:3008:24)
#2      CodeGenerator.visitSimpleIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:2972:20)
#3      CodeGenerator.visitPrefixedIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:5157:14)
#4      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8952:49)
#5      CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5796:18)
#6      CodeGenerator.visitNamedExpression (package:dev_compiler/src/analyzer/code_generator.dart:4061:46)
#7      CodeGenerator._emitArgumentList (package:dev_compiler/src/analyzer/code_generator.dart:4044:19)
#8      CodeGenerator.visitInstanceCreationExpression.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:4538:15)
#9      CodeGenerator._emitInstanceCreationExpression.emitNew (package:dev_compiler/src/analyzer/code_generator.dart:4356:31)
#10     CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4395:51)
#11     CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4535:12)
#12     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6579:15)
#13     CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5796:18)
#14     CodeGenerator._visitInitializer (package:dev_compiler/src/analyzer/code_generator.dart:4283:11)
#15     CodeGenerator._emitLazyFields (package:dev_compiler/src/analyzer/code_generator.dart:4299:19)
#16     CodeGenerator._emitTopLevelFields (package:dev_compiler/src/analyzer/code_generator.dart:4243:21)
#17     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:638:9)
#18     List.forEach (dart:core/runtime/libarray.dart:79:8)
#19     CodeGenerator._emitModule (package:dev_compiler/src/analyzer/code_generator.dart:384:22)
#20     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:263:18)
#21     ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:233:28)
#22     _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#23     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#24     _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#25     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1465:12)
#30     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#31     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

_Copied from original issue: dart-lang/angular#1498_

**Comment by matanlurey** [comment]
_From @lejard-h on July 17, 2018 13:31_

I also have warnings but don't know if it is linked

```
Selector argument FocusableItem for "@ContentChildren" is a Type, but it is not annotated with @Component or @Directive. During runtime this query will never find any elements. This may become an error in future versions of AngularDart
```

**Comment by jmesserly** [comment]
Hard to know without code to reproduce the problem. Are you running with `unsafe-force-compile` by any chance (or is it set by the build tool)? DDC errors like this should print the full arguments to `dartdevc` in the error message, if you could include those that would be helpful.

We can add a defensive null check, but without knowing why, it could be hiding a more serious problem. What happened is Analyzer's `element.computeConstantValue()` returned null, and that should never happen unless the code has errors (in which case: we should have aborted the compile before reaching the JS code generator).

**Comment by lejard-h** [comment]
Any news about this ?

We still have the error on the last sdk and nothing on the analyzer

**Comment by jmesserly** [comment]
Would it be possible to get access to Dart code that reproduces this problem?

**Comment by jmesserly** [comment]
In the meantime I will put in a workaround that may help: https://dart-review.googlesource.com/c/sdk/+/66225

**Comment by lejard-h** [comment]
Sorry we won't be able to share our project, if we success to isolate the bug we will try to reproduce and share.

In your workaround, is it possible to log the element when the value is null ? Or do you have any solution to help us debug it ?

**Comment by Kleak** [comment]
@jmesserly i try to find the root cause, could you tell me what is `VariableElement` in `element is VariableElement` ?

**Comment by jmesserly** [comment]
> i try to find the root cause, could you tell me what is VariableElement in element is VariableElement ?

it's a constant of some sort, most likely a top-level constant like:
```
const foo = ...;
```
I might be able to add some logging, that would print out which variable is causing the problem, that might help us track it down.

Also: Dev Compiler is going to migrate to the new common front-end soon (instead of using Dart Analyzer) so the problem may go away at that point.

**Comment by jmesserly** [comment]
I put in a workaround, so I think we can close this. Since DDC is going to migrate away from Analyzer, whatever is causing this bug should go away at that time.

**Comment by Kleak** [comment]
with the update to dart 2 stable we have the problem again.

**Comment by Kleak** [comment]
It could be cool to have an hint of where the problem is.
