### ISSUE TITLE
Observatory breaks build if old package directories not deleted

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#33884]
The directory runtime/observatory and its subdirectories contain obsolete package directories, that aren't deleted by any cleanup code.
These are now causing problems during gclient sync, when the hooks try to run gn to prepare ninja files to build dart, they hit a failure with error message:
```
[1/1] Regenerating ninja files
FAILED: build.ninja 
../../buildtools/linux-x64/gn --root=../.. -q gen .
ERROR at //build/dart/copy_tree.gni:20:3: Duplicate output file.
  action(target_name) {
  ^--------------------
Two or more targets generate the same output:
  obj/runtime/observatory/observatory/deployed/web/packages/charted/charts/themes/quantum_theme.css
This is can often be fixed by changing one of the target names, or by 
setting an output_name on one of them.
Collisions:
  //runtime/observatory:copy_charted_package
  //runtime/observatory:copy_web_package
See //build/dart/copy_tree.gni:20:3: Collision.
  action(target_name) {
  ^--------------------
ninja: error: rebuilding 'build.ninja': subcommand failed
BUILD FAILED
step returned non-zero exit code: 1
```

We should add code to the hooks in gclient sync that deletes the package directories from runtime/observatory.  I'll work on this.

**Comment by whesse** [comment]
@rmacnak-google @zanderso

**Comment by zanderso** [comment]
We should also remove "packages" entries from the `.gitignore` files in the tree. Then we could find/remove them with `git clean`.

**Comment by rmacnak-google** [comment]
There's no pub or package:charted involved in Observatory's build anymore.
