### ISSUE TITLE
Are we addressing relative vs. package import issues?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33888]
There are an increasing number of issues being filed, all tracked separately:

* https://github.com/dart-lang/sdk/issues/33887
* https://github.com/dart-lang/sdk/issues/33149
* https://github.com/dart-lang/sdk/issues/32922
* https://github.com/dart-lang/sdk/issues/32601
* https://github.com/dart-lang/sdk/issues/31230
* https://github.com/dart-lang/sdk/issues/33076

If the answer is no, and this is a tools issue (?), can we make that official?

/cc @lrhn @leafpetersen

**Comment by matanlurey** [comment]
Assigning to Dan to triage, because it looks like all individual issues are different teams?

**Comment by zoechi** [comment]
also #33076

**Comment by lrhn** [comment]
I believe #33076 is what we are doing to address it.

**Comment by matanlurey** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/33076.
