### ISSUE TITLE
Does dart 2 have native support for implementing key exchange protocols (e.g. Diffie–Hellman)?

### ISSUE THREAD

**Issue by egemenvardar** [dart-lang/sdk#33899]
I am looking for a dart package to implement key exchange protocol (Diffie–Hellman) in a Flutter application. As far as I've seen there is no support for that in the dart sdk.

I've found two packages that might be helpful: [ed25519_dart](https://pub.dartlang.org/packages/ed25519_dart) and [dh](https://pub.dartlang.org/packages/dh). Unfortunately, neither worked for me - I suspect that they are incompatible with dart 2 and they aren't maintained properly.

Is there a plan to add support to dart sdk for key exchange protocols? Or is there some dart library I could use to generate elliptic curve based public & private keys? I saw [this GitHub issue](https://github.com/dart-lang/sdk/issues/22611) about adding native support for forward secrecy, but it was closed and I assume no support has been added since then.

**Comment by soulman-is-good** [comment]
@matanlurey hard to find information on why cryptography is not part of dart sdk? Why is it not planned?
