### ISSUE TITLE
Problem with StreamBuilder and Firebase

### ISSUE THREAD

**Issue by Shamzic** [dart-lang/sdk#33895]
The StreamBuilder widget with Firebase can't be displayed when it is inside a children bracket. 
Furthermore it works when it is a simple child.

I have found this post wich resume the same problem : https://stackoverflow.com/questions/50792605/streambuilder-widget-is-not-rendered-if-nested-in-children-widget

Hope someone will find a solution !
Thanks !

**Comment by matanlurey** [comment]
This issue was moved to flutter/flutter#19487
