### ISSUE TITLE
Request for better generic method type param support for noSuchMethod

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33911]
An internal customer just hit this when moving tests from Dart1 to Dart2.
(They were on the DDC runtime whitelist, hence why it only came up now)

Here is a minimal reproducible sample of the user's code:

```dart
import 'dart:async';

void main() {
  MiRpc rpc = new FakeMiRpc();
  var request = new Request<String>();
 
  // 'Future<dynamic>' is not a subtype of type 'Future<String>'
  print(rpc.handle(request).runtimeType);
}

class Request<T> {}

// Real RPC class they use in production.
abstract class MiRpc {
  Future<T> handle<T>(Request<T> r);  
}

// Fake implementation (uses Mockito) in tests.
class FakeMiRpc implements MiRpc {
  @override
  noSuchMethod(_) => new Future.value();
}
```

I had the following 3 ideas for them:

1. Stop using `noSuchMethod`. This would be a giant change for them.
2. Add another method, like `handleUntyped`:
```dart
class MiRpc {
  Future<T> handle<T>(Request<T> request);
  Future<dynamic> handleUntyped(Request<T> request);
}

class FakeMiRpc implements MiRpc {
  @override
  Future<T> handle<T>(Request<T> request) {
    return handleUntyped(request).then((r) => r as T);
  }

  @override
  noSuchMethod(_) => new Future.value();
}
```
... and then change the 100+ usages from

`when(mockRpc.handle)`

to

`when(mockRpc.handleUntyped)`

3. The hackiest, but another option. Encode an "escape hatch" into "class Request":

```dart
class Request<T> {
  Future<T> reifyAsT(Future<dynamic> future) => future.then((r) => r as T);
}

Then FakeMiRpc could use it:

noSuchMethod(Invocation i) {
  var request = ...
  var future = ...
  return request.reifyAsT(future);
}
```

-----

I hope this example shows that we should clearly document and state that using `noSuchMethod` to proxy for methods with generic type arguments will likely not work in many cases (unlike Dart 1).

/cc @srawlins

**Comment by lrhn** [comment]
How about `noSuchMethod(_) => Future<Null>.value();`?

This does not seem to be a `noSuchMethod` problem as much as it's a general strong-mode issue. The code is not type-safe, it is returning a `Future<dynamic>` where a `Future<T>` (with `T` being `String`) is required. That's a predictable strong mode type error, since `dynamic` is no longer a wild-card type. You need to return a `Future` which is actually assignable to `Future<T>`, but you would need that whether you use `noSuchMethod` or not.

It is true that `noSuchMethod` has a hard time with type parameters because it gets them as `Type` objects, and there is no way to reify those as real types again (deliberately). For traditional *mocking*, I don't see that as a big issue. You typically record a request-response sequence, and you can return a response that matches the actual request.

**Comment by kwalrath** [comment]
I believe the new behavior is documented in https://www.dartlang.org/guides/language/language-tour#nosuchmethod, but there's no mention of the difference in https://www.dartlang.org/dart-2. I don't think that /dart-2 is the best place to list every single difference, but it should point to a page that is much more thorough. That could be the [SDK changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md), if the changelog were much more thorough than it is right now.

**Comment by matanlurey** [comment]
@lrhn:

> How about `noSuchMethod(_) => Future<Null>.value();`?

Sure, that works until you need a valid value.

> This does not seem to be a `noSuchMethod` problem as much as it's a general strong-mode issue.

It's a `noSuchMethod` problem in-that strong mode makes it less useful but users don't know that.

**Comment by vsmenon** [comment]
@matanlurey In this case, something like this should work:

```dart
class FakeMiRpc implements MiRpc {
  @override
  noSuchMethod(invocation) {
    var types = invocation.typeArguments;
    if (types.length == 1 && types.first == String) return Future<String>.value();
    return Future.value();
  }
}
```

I don't think there is anyway to thread the type param generally though (@leafpetersen @lrhn ?).

**Comment by vsmenon** [comment]
@matanlurey @lrhn - retitled the bug to (I think) match Matan's request better.

**Comment by matanlurey** [comment]
My original request was just around documenting that `noSuchMethod` _doesn't_ support generic type arguments, not to augment it @vsmenon.

**Comment by vsmenon** [comment]
In a sense, it does (`Invocation.typeArguments`).

**Comment by matanlurey** [comment]
Oh sure. I just don't need there feature (or want the backend teams to have to implement it). I just wanted it documented so we had something to point to that NSM in Dart 2 isn't exhaustive
