### ISSUE TITLE
Please merge revision 651994ba70fbf916316af8dd37571a4549bb66a1 into dev channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33919]
@whesse @mit-mit 
These changes address issue 32503 (make observatory strong mode clean)

The revisions that need merging are:
651994ba70fbf916316af8dd37571a4549bb66a1
296319d2f00e3f51942f884f8f340f725c598ac8

This should merge cleanly

**Comment by whesse** [comment]
Merged in 2.0.0-dev.69.1
