### ISSUE TITLE
Remove the unsafe mode flag

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33915]
Remove the unsafe mode flag added in the VM as an interim measure to bridge the performance gap until we have robust optimizations in place to account for the hit from runtime type checks.

**Comment by dgrove** [comment]
Any updates? still planned for 2.1?

**Comment by a-siva** [comment]
This is now an internal flag which is not documented and is not used by any tool. We just use it sometimes for measuring the cost of type checks when doing performance analysis. I am not sure if this should even be an issue.

marking issue as will not fix and closing it.
