### ISSUE TITLE
Dart 2: Dart Analysis Server consume too many resources

### ISSUE THREAD

**Issue by sestegra** [dart-lang/sdk#33925]
Dart VM version: 2.0.0-dev.68.0 (Tue Jul 10 14:47:26 2018 +0200) on "macos_x64"

I've just migrated from Dart 1.24.3 to Dart 2.0.0-dev.68.0.
Before the migration, I was running Webstorm with debug like a charm, CPU and RAM consumption were good.

Now, my CPU is continuously burning and RAM consumption is extremely high 3 times about 2G.
- dartanalyzer.dart.snapshot
- analysis_server.dart.snapshot
- webdev serve

Why the performance changed so dramatically ?

**Comment by sestegra** [comment]
During the migration, Dart Analyzer got around 3000 errors (due to strong mode issues that I had to fix) and around 1000 warnings (false positive coming from Angular plugin).

After fixing the errors and deactivating the Angular plugin, I noticed better performance, but lower than Dart 1. I guess it's related to #33257

**Comment by bwilkerson** [comment]
I'm assuming this is stale. If you're still seeing this kind of performance, please let us know.
