### ISSUE TITLE
Element 'Gradient' from SDK library 'ui.dart' is implicitly hidden by 'gradient.dart'

### ISSUE THREAD

**Issue by littlen101** [dart-lang/sdk#33921]
Trying to use Gradient.sweep() and but the analyzer error appears no matter how I import it

Dart VM version: 2.0.0-dev.58.0.flutter-f981f09760 (Sat May 26 03:16:14 2018 +0000) on "windows_x64"

similar to #28023 and #28226

**Comment by littlen101** [comment]
Seems that it is being hidden because of 
`package:flutter/painting.dart`

Is there a way for me to show 
'dart:ui' 
gradient instead

**Comment by lrhn** [comment]
Zoechi's answer is correct. If one imported name is shadowing or conflicting with another, you need to either hide one of the names using a `hide` modifier on the import, or import one of the libraries with a prefix:
```dart
 import 'package:flutter/painting.dart' as painting;
 ...
      painting.Gradient(...)
```
