### ISSUE TITLE
Dart 2.0.0.69-dev-0 is not on Chocolatey

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#33922]
The [latest version](https://chocolatey.org/packages/dart-sdk) at time of writing is 2.0.0.68-dev-0. This is breaking Dart Sass's release process, which relies on distributing snapshots to the same version of the Dart SDK it built on. See https://github.com/sass/dart-sass/issues/413. This is high priority for us, as it's breaking all of our users who are on Windows.

**Comment by bkonyi** [comment]
Looks like it's [updated now](https://chocolatey.org/packages/dart-sdk).

**Comment by nex3** [comment]
2.0.0.69-dev-0 isn't there, only 2.0.0.69-dev-4. It's important that *all* dev versions be available on Chocoatey, because Dart Sass depends on exactly the same version it was built with (because the snapshot format differs from version to version).

![dart-version-history](https://user-images.githubusercontent.com/188/43349305-ba317114-91b3-11e8-90bd-a39bf92b1927.png)

**Comment by nex3** [comment]
This is [actively breaking](https://github.com/sass/dart-sass/issues/413#issuecomment-409296253) Sass users on Windows. Can we please upload the missing versions? @whesse

**Comment by athomas** [comment]
@nex3 It's a mistake that the other .69 versions weren't uploaded. Normally we release all versions to chocolatey. I'll look into what happened there. But, publishing the old versions would make them the latest dev release on chocolatey and we would downgrade SDK pre-release users. With .69.5 looks like it might become stable, so it would be really bad timing to replace it with an older release on chocolatey now.

Please release a new version of the dart-sass chocolatey package with a dependency on one of the existing SDK chocolatey packages.
