### ISSUE TITLE
Analyzer doesn't understand "final/sealed" types

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33933]
We don't have _user-defined_ sealed types yet, but they _do_ exist. Consider:

```dart
void main() {
  int x = 5;
  if (x is String) {
    print('...');
  }
}
```

I'd expect `x is String` to be a hint similar to a dead code warning.

**Comment by srawlins** [comment]
Dup of https://github.com/dart-lang/sdk/issues/29548 ?

**Comment by matanlurey** [comment]
Yup!
