### ISSUE TITLE
Please merge 128ecff0c573d7886f8a42595527fd6cc8e12001

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33939]
Commit: https://github.com/dart-lang/sdk/commit/128ecff0c573d7886f8a42595527fd6cc8e12001
Reason: https://github.com/dart-lang/sdk/issues/33872

This is blocking disabling the DDC whitelist of runtime exceptions internally.

**Comment by whesse** [comment]
Merged in 2.0.0-dev.69.2
