### ISSUE TITLE
Please merge revisions listed below (CONSTANT REMOVAL) to dev

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33935]
@whesse @mit-mit @dgrove @athomas 

Merge removal of deprecated SCREAMING CAPS CONSTANTS and follow up CLs to fix test status files.  https://github.com/dart-lang/sdk/issues/31813.

Please merge the following hashes:
f2402b3c08b849062707ec06e6f43abb182e2196
d283ad8291b03ba9fdab64d08282bd1f44dd4d4c
d715c5e052de7ee28978ed01534a500fab0f4f05
e9fa236d6be2672e85d2cfe7817db4b244b3fd92

Did not merge cleanly (conflict only in CHANGELOG).  Merge CL is here:

https://dart-review.googlesource.com/c/sdk/+/66021

**Comment by leafpetersen** [comment]
cc @lrhn

**Comment by whesse** [comment]
Merged in 2.0.0-dev.69.2
