### ISSUE TITLE
Please merge 5c9c90f7e1d3377d48955d3f540c4d2bf23616fb into dev channel

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#33937]
**commit(s) to merge**: 5c9c90f7e1d3377d48955d3f540c4d2bf23616fb

**merge instructions**: this should patch cleanly? https://dart-review.googlesource.com/c/sdk/+/66121

**reason**: https://github.com/dart-lang/sdk/issues/33934

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
Merged in 2.0.0-dev.69.2
