### ISSUE TITLE
Figure out which hints are no longer needed because of the semantics of Dart 2

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#33936]
With Dart 2, it is possible that some of the hints that analyzer was creating are no longer needed (because they've been replaced by actual errors). We need to examine each one of them to determine which ones to stop producing so that we don't produce duplicate diagnostics.

See `HintCodeTest.test_abstractSuperMemberReference_getter()` as an example.

**Comment by srawlins** [comment]
Closing as very stale. If there are more Hints which are unnecessary due to Dart 2, we'll find them when we find them.
