### ISSUE TITLE
No error/warning for missing return

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33940]
A friend sent me some code that was failing at runtime because he'd missing a return (he expected this should've resulted in warnings/errors). I tried with the `2.0-dev69.0` with simplified code and also got no warnings (I tried setting `implicit_casts: false` too in case that had anything to do with it, but it didn't help).

```dart
void thing(String Function() f) {
  f();
}

void main() {
  thing(() {
    // Oops, forgot to return String.
  });
}
```

I found a couple of issues on GH complaining of unexpected `missing_return` warnings, so it seems like there is some functionality for it, so I can't figure out whether the above is intended or a bug?

(cc @bwilkerson)

**Comment by DanTup** [comment]
In case it matters, the original code wasn't quite as weird as this, it was like:

```
x.fold(y, (A a, B b) {
  // code with missing return
});
```

**Comment by leafpetersen** [comment]
I think a dup of https://github.com/dart-lang/sdk/issues/28233 .
