### ISSUE TITLE
Observatory does not have link to #timeline-dashboard

### ISSUE THREAD

**Issue by alanrussian** [dart-lang/sdk#33948]
Flutter recommends viewing the #timeline-dashboard page. It's accessible through the widget inspector via a button. If you don't use the widget inspector, there's no link to this page when you go to the Observatory homepage.

**Comment by a-siva** [comment]
There is a link to the timeline in the main observatory page "view timeline"

![image](https://user-images.githubusercontent.com/8633293/43106707-b0f2db38-8e8e-11e8-8e8c-a31dd5b4a63e.png)

**Comment by alanrussian** [comment]
That's not the same as the timeline dashboard page. The link you mentioned links to "#timeline". The timeline dashboard is at "#timeline-dashboard".

**Comment by a-siva** [comment]
The timeline-dashboard page was an internal experimental page not sure why the widget inspector exposes it.

**Comment by alanrussian** [comment]
I filed https://github.com/flutter/flutter/issues/23746
