### ISSUE TITLE
The Dart vm should accept a list of kernel modules instead of a single monolithic file

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#33952]
Currently the pipeline for generating and running modular kernel files for the vm requires a concat step at the very end, to merge all the files into a single output. This is presenting problems when trying to compile large numbers of tests on CI environments such as Travis ([example failure](https://travis-ci.org/dart-lang/pub/jobs/407277655#L567)).

The problem is that each test in this example ends  up producing a 22MB output file, even though its individual kernel module is quite small (low KBs generally). This results in a build cache that is almost 6GB in size for pub.

If the vm could take a list of dill files instead, and read them all in sequentially as if they were a single file (that's all that is needed), then we could skip this entire build step and get caching working for CI environments (as well as using up a lot less disk space on users machines).

In theory these could also be read in parallel which may speed up the startup time.

**Comment by a-siva** [comment]
Not sure I understand the problem, if an individual test only produces a kernel file of low KBs size what gets concatenated to it to make it grow to 22 MB ?

**Comment by jakemac53** [comment]
The small file for the test is the kernel module for the test file itself, but none of its dependencies.

**Comment by a-siva** [comment]
So what you are stating is that if you do not have to concatenate then all the dependent modules are shared across the different tests and so the cache is smaller.

**Comment by jakemac53** [comment]
Yes, exactly.

**Comment by zanderso** [comment]
We do something somewhat similar for Fuchsia. `Dart_LoadLibraryFromKernel()` (https://github.com/dart-lang/sdk/blob/master/runtime/include/dart_api.h#L3143) can be called multiple times to load partial programs. See: https://fuchsia.googlesource.com/topaz/+/master/runtime/dart_runner/dart_component_controller.cc#161

**Comment by jakemac53** [comment]
Note that we could run into issues with to many command line args, so it might make more sense to pass a file that lists all the required dill files, or something along those lines.

**Comment by grouma** [comment]
Raising the priority on this one. This is significantly impacting the resource usage for users of the new kernel builder. I think an appropriate stop gap solution is to allow multiple kernel files to be passed on the command line with a the long term solution being a manifest which contains the list of required kernel files.

**Comment by aam** [comment]
@jakemac53 @grouma , what is the process you use to produce separate kernel files for the test and its dependencies?

**Comment by jakemac53** [comment]
> @jakemac53 @grouma , what is the process you use to produce separate kernel files for the test and its dependencies?

We are using the build_runner + build_vm_compilers  + build_test (needed for tests only) packages. These use the kernel worker snapshot shipped with the vm, combined with a custom module strategy, to do compile packages to kernel.

It is essentially the same as the web stack, but with `build_vm_compilers` instead of `build_web_compilers` (which uses ddc).

**Comment by aam** [comment]
@jakemac53 wrote:
> We are using the build_runner + build_vm_compilers + build_test

Can you folks somehow share instructions to run this stack so we can test vm implementation of multiple kernels loading?

**Comment by jakemac53** [comment]
You would need to add these packages to your `pubspec.yaml`:

```yaml
dev_dependencies:
  build_runner: ^0.10.0
  build_vm_compilers: 0.1.0
```

Then you can run `pub run build_runner build -o <output-dir>` and it will create a merged output directory for you. By default this will only compile scripts under the `benchmark`, `bin`, `test`, `tool`, and `example` directories, so you will want to put your app entrypoints in one of those.

In the output directory you will see a bunch of `.vm.app.dill` files which are the merged kernel files - you will also see `.vm.dill` files which are the individual modules.

Since we can't do it today we don't have a utility to grab all the modules required for a given entrypoint and pass them to the vm, but if you make a relatively small example it shouldn't be difficult to find the required `.vm.dill` files (they live right next to the dart files generally, although for package imports it depends on the module structure). Let me know if you need help there.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/67460 is one way of solving this.

**Comment by jakemac53** [comment]
That looks simple/effective enough for our purposes

**Comment by aam** [comment]
cc @rmacnak-google

**Comment by rmacnak-google** [comment]
The standalone embedder should not accept any new kinds of input. It's already very brittle and damaged from the CFE architecture, and the cost of supporting a new kind of input should not be borne by existing users. If you require special loading, create your own embedder as Fuchsia has done.

**Comment by jakemac53** [comment]
> If you require special loading, create your own embedder as Fuchsia has done.

This really isn't anything special relating to the build package, we just happen to be one of the first use cases which compiles large numbers of applications. The current implementation doesn't allow any way to share code across those applications, even though kernel supports it.

Given that precompiled kernel is the only way to get reasonable startup performance, I think we should support this out of the box.

**Comment by natebosch** [comment]
> we just happen to be one of the first use cases which compiles large numbers of applications (tests specifically)

Our users have been doing this for years, it's not the build system introducing the use case. In Dart 1 everyone used `dart` to compile and run a large number of applications and performance was fine. Dart 2 tanked the performance of using `dart` for this use case (compiling and running from source), so we're trying to mitigate that and we're open to discussion about what that mitigation should look like.

**Comment by matanlurey** [comment]
It might also be worth looping in engineers that work _within_ the SDK - how do they run 100s or 1000s of Dart-VM-based tests now? Does `test.py` have something like the logic above itself?

**Comment by aam** [comment]
Support for feeding multi-kernel lists to dart landed in https://dart.googlesource.com/sdk/+/41e720b486daab41257ea512e9df19e6dcc73f45.

**Comment by jakemac53** [comment]
Awesome thanks!

**Comment by grouma** [comment]
Thank you!

**Comment by natebosch** [comment]
Revisiting this, trying to see if we can use it.

Turns out I don't think this solves our problem. We can't use absolute paths because it isn't a hermetic output, and relative paths against `cwd` drop the usability. Can we consider using relative paths against the manifest file?

**Comment by a-siva** [comment]
I believe this has been fixed, can we close the issue?

**Comment by natebosch** [comment]
Support was added but not in a way we can use in any hermetic build system. See my previous comment. I reopened the issue to see if we can get support for relative file paths.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/103901 with relative paths fix.
