### ISSUE TITLE
What is the difference between TypeError and CastError?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33950]
... in Dart2:

* https://api.dartlang.org/dev/2.0.0-dev.69.2/dart-core/CastError-class.html
* https://api.dartlang.org/dev/2.0.0-dev.69.2/dart-core/TypeError-class.html

My opinion is we should have just one of these, not both. I've seen users write:

```dart
try {
  doThing();
} on TypeError catch (e) {

} on CastError catch (e) { 

}
```

It also looks like the type of error you get is runtime dependent (VM, Dart2JS, DDC).

**Comment by vsmenon** [comment]
A `CastError` should be an explicit cast failure.  A `TypeError` should be an implicit cast failure.

At the moment, it's a useful distinction - as long as we have omit-implicit-checks.  In the long run, that doesn't seem ideal though - we'd like folks to avoid implicit casts if they prefer.

Do you have an example where impls are inconsistent?

**Comment by matanlurey** [comment]
Ah I had no idea it was explicit or implicit.

It seems unfortunate though. Could `CastError` extend `TypeError` so both don't need to be caught?

**Comment by lrhn** [comment]
I wold love for `TypeError` to not extend `AssertionError` any more. Didn't make it in Dart 2, it was a breaking change and a low priority.

I would also personally prefer to just have one error for this. In Dart 2, there are no type errors that are not cast errors because all unsafe assignments automatically gets an implicit cast inserted.

**Comment by hugocbpassos** [comment]
> I would also personally prefer to just have one error for this. In Dart 2, there are no type errors that are not cast errors because all unsafe assignments automatically gets an implicit cast inserted.

What is considered an "unsafe" assignment? Perhaps something like the following?

```dart
void main() {
  int fooInt = foo();
}

dynamic foo() => 'foo';
```

This throws a `TypeError`, thought.

**Comment by lrhn** [comment]
CastError is now deprecated, and everything throws `TypeError`.
