### ISSUE TITLE
Add a 'wrap with (Flutter) Builder refactor'

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#33957]
The 2 patterns of taking a Widget instance or taking a WidgetBuilder instance are common in Flutter. 

Currently if one makes a mistake and wrote one when the other is needed, it's inconvenient to make the switch since one has to make the manual act of balancing brackets etc. 

Would be good to have a quick-refactor function to flip between the two.

**Comment by MrBirb** [comment]
@xster #45656 was recently merged. It claims to fix this issue.

**Comment by xster** [comment]
Very cool
