### ISSUE TITLE
Wrong (weird) paths returned from debugger for pub

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33959]
Not sure if this is a bug or expected, but feels weird.

I'm investigating an issue with paths in the call stack when I'm debugging tests and noticed when an exception occurs during the "loading" of a test package (which includes execution of all code outside of the `test`/setUp`/etc. methods) the call stack has some pub with weird paths (from a build server?):

<img width="760" alt="screen shot 2018-07-24 at 2 05 34 pm" src="https://user-images.githubusercontent.com/1078012/43139832-aceed106-8f4a-11e8-8366-cf63c44a1deb.png">

When you click on them, we try to navigate the editor there (and fail). We can add exists checks on the path, but it seems weird that we can handle the Dart ones (they come through as `dart:` and then we download the source from the VM).

I don't know if it only happens when we break in specific places; here's how I ended up here:

** pubspec.yaml **
```yaml
name: simple_test
version: 0.0.1

environment:
  sdk:         '>=2.0.0-dev <3.0.0'

dependencies:
  test: '>=1.0.0'
```

** test.dart **
```dart
import 'package:test/test.dart';

main() {
  assert(1 == 2);
  test('test', () {
    assert(1 == 2);
  });
}
```

Running it with "Break on all exceptions".

**Comment by vsmenon** [comment]
This looks like an issue with source maps.  @kmillikin - is this front end?

**Comment by bkonyi** [comment]
If I'm not mistaken, those paths are from the build infrastructure that creates the binaries for Flutter SDK releases. According to @rmacnak-google, this is due to the paths being captured when the snapshots are being generated on the bots. Basically, it looks weird, but that's currently WAI based on how we do snapshots / generation of kernel files.

**Comment by DanTup** [comment]
Normally for non-user code (like the `dart:` libraries) we can download the source code from the VM, but that doesn't seem to work here (the source seems to come back as `undefined`). Is there anything we can to show the user source code here? I think I can make it show "source unavailable" or something in VS Code, but if the source is available I'd rather make it display.

**Comment by DanTup** [comment]
There's actually something weird here anyway - even the `dart:` libraries don't return source code when I'm stopped at this error (I don't know if it's related to the snapshot). If I remove the first assert and let it break inside the test method, then fetching source for `dart:` libs works fine.

So, I'm going to make the following changes:

1. If the path given to us by the VM does not exist on disk, return no source reference to VS Code (this will result in "Unknown Source" being shown in the call stack)
2. If the user clicks on a stack frame that we thought we had source for (`dart:` libs in this case) but the VM returns `undefined`, then we will reject the request with `<source not available>`. This causes VS Code to show that string as if it was the source code for the file (!) but at least it's clear to the user what's happened.

I'm not sure if many people will hit this; I don't expect many use Break on All Exceptions and then break end up in code that works this way.

**Comment by DanTup** [comment]
That doesn't seem to be an issue anymore (perhaps after moving to `dart run test:test`?). The stack looks like this:

<img width="458" alt="Screenshot 2022-09-20 at 15 25 05" src="https://user-images.githubusercontent.com/1078012/191284343-71030c02-2bb2-48f9-b44d-e36e56b51d0f.png">

And (at least using the new SDK DAPs) every frame can be navigated to.
