### ISSUE TITLE
Please update language_2 tests to reflect the current state wrt to void

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#33958]
I'm unable to make progress on #30470 as I can't get a definitive answer as to what the specification is, and the tests are out of sync in regards some of the statements made by the language team.

**Comment by leafpetersen** [comment]
I am working on this.

**Comment by leafpetersen** [comment]
In progress CL here:  https://dart-review.googlesource.com/c/sdk/+/66521

All of the tests that I have triaged have been moved under language_2/void, and are, to the best of my scrutiny, now correct (in that CL).

Tomorrow I will sort out status files in some fashion and land this.

**Comment by leafpetersen** [comment]
Note: I have no way of finding tests that might relate to void unless they have void in their name, and so those are what I will triage (this is a very unfortunate property of our language tests).  If there are other tests that anyone is aware of that I should include in this triage, please let me know.

**Comment by leafpetersen** [comment]
Yes, this is not blocking for Dart 2.

**Comment by leafpetersen** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/66521

**Comment by leafpetersen** [comment]
Done.  https://dart-review.googlesource.com/c/sdk/+/66521
