### ISSUE TITLE
Strange issue with two separate functions not calling if one is not called

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/sdk#33968]
```dart
  void _handleTap(String linkUrl, Function _callback){
    if(_callback != null)  _callback();
    if(linkUrl != null)  _launchURL(linkUrl);
  }
```

if callback is a function and linkUrl is null, neither will fire.

If I then change linkUrl to any value, they both fire.

**Comment by matanlurey** [comment]
I can't reproduce this in any of the latest SDKs.

It looks like you are writing something potentially specific to an app framework (Flutter?) You might want to file something with more details on StackOverflow.

**Comment by lukepighetti** [comment]
I found a mistake in my code that was not pictured above. This can *definitely* be closed.
