### ISSUE TITLE
Organize imports should separate current package import from other

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#33961]
_Organize imports_ with `2.0.0-dev.69.2` (in VSCode) doesn't respect [PREFER placing “third-party” “package:” imports before other imports](https://www.dartlang.org/guides/language/effective-dart/style#prefer-placing-third-party-package-imports-before-other-imports).

In `google_maps` package I get:

```dart
import 'dart:html' show Node;

import 'package:google_maps/google_maps.dart';
import 'package:js_wrapping/js_wrapping.dart';

part 'google_maps_src_adsense.g.dart';
part 'library/adsense/ad_format.dart';
part 'library/adsense/ad_unit.dart';
part 'library/adsense/ad_unit_options.dart';
```

instead of:

```dart
import 'dart:html' show Node;

import 'package:js_wrapping/js_wrapping.dart';

import 'package:google_maps/google_maps.dart';

part 'google_maps_src_adsense.g.dart';
part 'library/adsense/ad_format.dart';
part 'library/adsense/ad_unit.dart';
part 'library/adsense/ad_unit_options.dart';
```

**Comment by srawlins** [comment]
That rule was removed (here's the Ordering section: https://dart.dev/effective-dart/style#ordering), and I believe the current quick fix aligns with Effective Dart.
