### ISSUE TITLE
AOT: implement non-speculative int64 versions of MOD and TRUNCDIV

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33967]
Our compiler does not inline / specialize `int.%` or `int.~/` even on platforms where there are short enough instruction sequences. 

On ARM64 we should probably always emit `sdiv` for `TRUNCDIV` and `sdiv+msub` for `MOD`. 
 
On ARM32 we probably emit whatever we emit for `IntegerDivision` or maybe a call to `__aeabi_ldivmod` - if that is better.

**Comment by aartbik** [comment]
This is a blocking AOT optimization of any integer operation chain with % or ~/. We should start supporting this at the very least on 64-bit architectures.

**Comment by aartbik** [comment]
While working on this I noticed the current VM is not completely accurate for

```dart
0x8000000000000000 % -1 
0x8000000000000000 ~/ -1 
```

**Comment by aartbik** [comment]
Still getting used to the buttons :-) I obviously hit the "close and comment" rather than just the "comment".

**Comment by aartbik** [comment]
I kept this open for an ARM32 implementation (probably a lib call).

**Comment by aartbik** [comment]
Closing this issue after all. The 64-bit cases are now fully optimized, as requested. Handling the arm32 case with a lib call (compared to a call into the runtime) does not seem worth the engineering effort.
