### ISSUE TITLE
Fix memory leak of kernel blobs during isolate reload

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33973]
The kernel blobs we use during isolate reloads are leaked and reported by a LSAN. Currently many objects (e.g. `Library`, `Function`) use an `ExternalTypedData` reference into the middle of a C-heap allocated buffer and don't have finalizers installed. The entire buffer is never freed.

There are multiple solutions to this problem:

  * Option a) Make `Library`, `Class`, ... objects point to a typed data view, which has as a backing store `ExternalTypedData`
  * Option b) Make the kernel offsets into the kernel blob absolute and use the same `ExternalTypedData` on all objects and **install a finalizer** to free the memory.
  * ???

/cc @rmacnak-google @jensjoha

**Comment by wz4tc** [comment]
Another similar issue. FYI
https://github.com/dart-lang/sdk/blob/master/runtime/vm/kernel_binary.cc#L150
