### ISSUE TITLE
Type promotion doesn't work

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#33972]
Please see Subtyping informal spec https://github.com/dart-lang/sdk/blob/master/docs/language/informal/subtyping.md

> Left Promoted Variable: T0 is a promoted type variable X0 & S0
> 
> and S0 <: T1

This rule doesn't work. See the code below

```dart
class T1 {}
class X0 {}
class S0 extends T1 {}

class T0 implements X0, S0 {}

foo(T1 t1) {}

main() {
  X0 t0Instance = new T0();
  T1 t1Instance = new T1();

  if (t0Instance is S0) {
    foo(t0Instance); // Error: The argument type '#lib1::X0' can't be assigned to the parameter type '#lib1::T1'
  }
}
```
This code produce an error in VM and analyzer. Type promotion should be performed here and no error should be thrown
Dart VM version: 2.0.0-dev.69.0 (Unknown timestamp) on "linux_x64"

**Comment by vsmenon** [comment]
I believe type promotion shouldn't kick in here as `X0` and `S0` are unrelated. 

@leafpetersen @munificent

**Comment by munificent** [comment]
I think @vsmenon is correct.

In the example here, there is no promotion because you can only promote to a subtype. So `t0Instance` never has type `T0 & S0`. At least that's my understanding. I'm going to close this assuming I'm right but @leafpetersen can reopen if I got this wrong. :)

**Comment by leafpetersen** [comment]
@vsmenon and @munificent are correct: `X0` and `X0` are unrelated, so no promotion should happen.  But more to the point, there are no type variables in this example at all: just class types.   I think what you're looking for is something more like:

```dart
class T1 {}
class S0 extends T1 {}

foo(T1 t1) {}

bar<T>(T o) {
  if (o is S0) {
    foo(o);
  }
}

main() {
  bar<S0>(S0());
}
```

**Comment by sgrekhov** [comment]
@leafpetersen thank you for clarification. But... Isn't type promotion is too sophisticated in its current form? It'd be much simpler and, I believe, more expected by developers (especially newbies) if
```dart
A x = ...
if (x is C) {
  // Type promotion. x is treated as instance of C as well as instance of A
}
```
But now it works only if x is a local variable and C is subtype of A. May be there are additional limitations as well? This is not intuitive
