### ISSUE TITLE
Hint that local values, known methods are always something

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33988]
I've seen teams that have migrated from a pattern of:

```dart
class A1 {
  void Function() aMethod;
}
```

... to ...

```dart
class A2 {
  void aMethod() {}
}
```

However, they retain a `!= null` check for legacy reasons:

```dart
void example(A2 a) {
  if (a.aMethod != null) {

  }
}
```

I would like a _hint_ produced:

```dart
void example(A2 a) {
  // HINT: Unnecessary null check, a.aMethod is a method and can never be null.
  if (a.aMethod != null) {

  }
}
```

Similarly, and I can open another issue, we should catch local variables:

```dart
void example() {
  var a = 'Example';
  // HINT: Unnecessary null check, a has a known assigned value that is not null.
  if (a != null) {

  }
}
```

Ideally it would also work for `is` checks. No hints are produced below:

```dart
void example(A a) {
  var x = 'Hello';
  if (x is String) {
    
  }
  if (a.aMethod is void Function()) {
    
  }
}
```

**Comment by natebosch** [comment]
> Similarly, and I can open another issue, we should catch local variables:

This one would require flow analysis and AFAIK our analyzer code does not have any strategy for that so it would be a large undertaking. Flow analysis for hints like this and type promotion would be _awesome_ though.

**Comment by matanlurey** [comment]
It looks the linter does limited flow analysis, right?

**Comment by srawlins** [comment]
It looks like null safety has solved all our problems. Analyzer reports the following for your first example:

> hint • The operand can't be null, so the condition is always true. • a.dart:6:17 • unnecessary_null_comparison
