### ISSUE TITLE
update packages affected by dart:html breaking change

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33987]
The fix for #33891 introduced new compile-time errors on some libraries that we need to update before releasing 2.0

We are already working on it, this is just a bug to track status.

**Comment by terrylucas** [comment]
Change to Angular Dart has been made in scroll_host_base.dart. Awaiting public roll out.

**Comment by terrylucas** [comment]
Nick when you roll out

**Comment by nshahan** [comment]
The PR is out. https://github.com/dart-lang/angular_components/pull/304

I'll close this issue once it lands and I publish.

**Comment by vsmenon** [comment]
Looks like that's been merged now.  Can we close this?

**Comment by nshahan** [comment]
Yes it got merged and a version with the fix was published.
https://pub.dartlang.org/packages/angular_components/versions/0.9.0-beta+2
