### ISSUE TITLE
Offer auto-fix for @mustCallSuper

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33985]
Raised by @xster at https://github.com/Dart-Code/Dart-Code/issues/746

Don't know how generalizable it is to expand to all linter warnings, but would be nice for the analyzer server to return easy fixes. 

For instance, @mustCallSuper tagged methods can just have its sub class implementations auto add a line for `super.x()`

**Comment by bwilkerson** [comment]
The question would be where to add the call? Typically either at the beginning or the end, but even that's no guaranteed.

**Comment by DanTup** [comment]
I'd say whichever seems most likely (which is probably the top?). It's much quicker to shift a line up/down than type the line if there are lots of params, so I think it's still a good saving even if it ends up in the wrong place sometimes.

That said; since it's not going to show up all that often, maybe having two fixes (eg. "Insert super call at top of method") isn't completely ridiculous if the method is not empty.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/240846
