### ISSUE TITLE
Compiler error when using a class with a generic inside of generic method override

### ISSUE THREAD

**Issue by chaselatta** [dart-lang/sdk#33980]
Dart Version: 2.0.0-dev.63.0
Platforms: All

I have an abstract class with a generic method. If I override the method with a class that requires a generic type to be specified, like `Stream<T>` I get a parser error. The following code snippet illustrates the issue:

```
abstract class Base {
  void save<T>(T data);
}

// This class compiles without any error
class Foo extends Base {
  @override
  void save<String>(String data) {}
}

// This class fails to compile with the error "Error: Unexpected token '<'."
class Bar implements Base {
  @override
  void save<Stream<int>>(Stream<int> data) {} 
}
```

**Comment by matanlurey** [comment]
I don't think your code is valid. In the above case, you are creating a type parameter named `String`.

What you want to do is something like this:

```dart
abstract class Base<T> {
  void save(T data);
}

class Foo extends Base<String> {
  @override
  void save(String data) {}
}

class Bar implements Base<Stream<int>> {
  @override
  void save(Stream<int> data) {}
}
```

**Comment by chaselatta** [comment]
If it is not valid code then why would this compile without error? Should we be seeing an error saying that the definition of `save` in `Base` is not valid?

```dart
abstract class Base {
  void save<T>(T data);
}

class Foo extends Base {
  @override
  void save<String>(String data) {}
}
```

**Comment by nkoroste** [comment]
+1 to what chaselatta said - not only there is no compile time error but it also works for some cases which is even more misleading. For example, it works for all other primitives that are not String.

**Comment by ameiyil** [comment]
+1

Not sure if things have changed recently, but it looks like legal code according to this feature announcement about Generics in methods and functions: https://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html

Is it something to do with the abstract classes that makes this illegal somehow? If so, why?

**Comment by ameiyil** [comment]
Thanks for the explanation, that helps a lot.

I particularly found the the following line helpful to understanding why `save<String>()` causes String to be interpreted as a type variable.

> The next thing you need to know is that it is not possible to override a generic instance method by a non-generic one.

Since it's not immediately obvious (at least the 3 of us who responded to this issue didn't realize it) I fear others will make the same mistake, could this be added to the technical documentation somewhere?

Perhaps the language tour doc? 
https://www.dartlang.org/guides/language/language-tour

**Comment by eernstg** [comment]
I think the real tripwire here is C++ knowledge: Anyone who approaches Dart from a Java or C# background would presumably understand `void save<X>(X x) {}` to declare a generic function (e.g., a generic instance method, but it could also be a local function etc.), so `X` is understood to be the declaration of its type parameter, and it makes no difference that `X` may be the name of something else in an enclosing scope, e.g., `void save<String>(String x) {}`. Same thing!

So in that sense it has nothing to do with the situation where a non-generic method attempts to override a generic method (`Base.save` and `Foo.save` in the original example are both generic).

But the C++ template specialization [example that I mentioned](https://www.geeksforgeeks.org/template-specialization-c/) allows for declarations where we have something that resembles actual type arguments (here: `<char>`) being passed to the function that we are declaring:
```C++
// A generic sort function 
template <class T>
void sort(T arr[], int size)
{
    // code to implement Quick Sort
}
 
// Template Specialization: A function 
// specialized for char data type
template <>
void sort<char>(char arr[], int size)              // <----- Here!
{
    // code to implement counting sort
}
```
Template specialization is purely a compile-time mechanism. You can see some examples in C# [here](https://stackoverflow.com/questions/600978/how-to-do-template-specialization-in-c-sharp) illustrating how static overloading can be used to do something similar in some cases, and how this breaks down at runtime (search for `TSomething`).

I've mentioned the idea of adding a remark about C++ template specialization to the language tour to a person who is working with it.
