### ISSUE TITLE
Request usable version of Dart until 2.0 is ready

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#33986]
I need a free version of a Dart development system that works decently.   Currently I am trying to use Intellij community edition.

1.  version 2.0  doesn't work yet,  because the software uses pub instead of webdev.   
     (The new analyzer works fine on my project.  )

2.  The newest 1.0 version will no longer run dartium.   I did download and install the latest version
 of dartium,   dartium-mac-x64-stable-1.24.2.0 3,
   but it says that it has expired.
    The problem is that,  debugging in the chrome editor is crippled by comparison.   The worst problem is that caught exceptions do not show up properly in the call stack.   Usually it is at some lower level dart-sdk code with no indication of the higher level call in my code.  It does appear in the call stack of dartium.    (In my latest case,  i simply passed a null object to a constructor that tried to compute its length -- a fast, development patch that is clearly wrong.  I simply wanted to know the location of the constructor call.)
 This is very old problem,  but up to now I simply switched to dartium to track down these problems.    Of course,  I can insert breakpoints and step through the code,  but this is time consuming.

  I am hoping that Dart 2.0 will work better.   I would like to have a working version of dartium until this can occur.

**Comment by zoechi** [comment]
> the software uses pub instead of webdev.

What is "the software"?

>  it has expired

Easy to work around #33580

**Comment by drpond1** [comment]
"the software"  ...   corrected to:
    the current version of IntelliJ community edition uses pub not webdev.
When that gets updated,  I will switch to 2.0.

Dartium workaround.
    Thanks for pointing out the discussion on the issue.  You might want
to  revise the page webdev.dartlang.org/tools/sdk/archive with a pointer to
this issue.

 Thank you for your very fast response,

**Comment by matanlurey** [comment]
As mentioned, Dartium is not a requirement and there is an easy workaround in #33580.

**Comment by drpond1** [comment]
I have been using Dart 2.0 for a while.

1.  The combination of Dart 2.0 and the chrome debugger is *now* very good.   breakpoints work.  you can go to function definitions.   watches work, call stack works,....and more.
    Not quite as convenient as an
integrated debugger,  but really very nice.     The issue can be closed,  because users wanting a free development system (Intellij) can use the chrome debugger.     (Yes, I know the issue was closed for other reasons.)    Thanks to:  either the Dart team or the Chrome team or both.  

2,  The original issue was opened because I  made the mistake of not setting up webdev,  because the documentation for manually installing the sdk did not mention it.  So I thought the system
was not yet ready. 

In webdev.dartlang.org/tools/sdk#install
"As the following instructions show, you can use a package manager to easily install and update the Dart SDK. Alternatively, you can build the SDK from source or   *** download the SDK as a zip file. ***  "

But "the SDK as a zip file" page says nothing about webdev.
Perhaps webdev startup has already been simplified.  If not...

Describe the need for manually starting webdev.
For those IntelliJ users not wanting to  change path variables,  there is a very simple solution.
Look at the error message when webdev fails to run.  That tells you the path for pub.
Open a terminal in IntelliJ (view/toolwindows/terminal) and type pub with the specified path,  but with the command: pub global activate webdev .
