### ISSUE TITLE
Using void with a prefix causes unprefixed "void" to suddenly report "not a type"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#33990]
Given a program that imports dart:core with and without a prefix:

```
import 'dart:core';
import 'dart:core' as core;
```

Then by attempting to use `core.void`, suddenly `void` stops working:

```
void x; // error: not a type
core.void y; // also an error
```

Note: originally was not sure if void should be usable with a prefix. Per @lrhn's comment, it should not be. So that part is working at least!

**Comment by lrhn** [comment]
Working as intended. The word `void` is a reserved word, not an identifier. As such, the name is not looked up anywhere, and cannot be exported by any library, including `dart:core`.

**Comment by MichaelRFairhurst** [comment]
OK that clarifies things!

However, I think you missed this part:

```
void x; // error: void is not a type
core.void y;
```

That should never happen based on what you're saying!

**Comment by MichaelRFairhurst** [comment]
Edited the title and description to account for the fact that `core.void` should not in this case work.

**Comment by srawlins** [comment]
There is no longer the 'void is not a type' issue.
