### ISSUE TITLE
Please merge 6bddb6c112d7f8c220397652f92f4263daf5ca12 and 57e11e3d55a12805324d17cc72555307eed032ee into dev channel

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#33996]
**commit(s) to merge**: 6bddb6c112d7f8c220397652f92f4263daf5ca12 and 57e11e3d55a12805324d17cc72555307eed032ee (original fix + status file patch)

**merge instructions**: clean merge

**reason**: Fixes issues with async debugging described in flutter/flutter#18877 which are also present in standalone Dart.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by kevmoo** [comment]
Is this critical for GA? Could this land in our first patch release? CC @vsmenon

**Comment by vsmenon** [comment]
@a-siva - what do you think?  do we need this in 2.0?

**Comment by bkonyi** [comment]
If anyone is debugging and steps over an awaited Future with a closure
defined within the same asynchronous method, the debugger falls right
through all other breakpoints in the program. This is extremely confusing
and frustrating to run into, so I'd argue that from a dev-exp perspective
this is a big enough issue to warrant a fix being patched in for the 2.0
release.

**Comment by kevmoo** [comment]
Is this a recent regression for Flutter? I think we're at the point now where we REALLY want to be picky about bugs we merge in.

We can get a dev release out with this the same week as stable – but we'd really like to keep the bar high for 2.00 GA

**Comment by bkonyi** [comment]
No, I believe this has been an issue since we moved to Dart 2 in general,
but it was only reported when Dan Tup ran into it during VsCode work. I
personally think this is a pretty major debugger regression, but if there's
going to be another release in the near future I guess it can wait.

**Comment by athomas** [comment]
Merged in 2.0.0-dev.69.4
