### ISSUE TITLE
analyzer co19_2 test failures when switching the parser to fasta

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33995]
@danrubel

**Comment by bwilkerson** [comment]
Are there test failures that need to be tracked here, or can we close this?

**Comment by devoncarew** [comment]
I see 60 references from `co19_2/co19_2-analyzer.status`.

**Comment by danrubel** [comment]
I have fixed what I can in the parser (see above) and many (all?) of the rest are pre-existing issues. If you do find another parser or AstBuilder related issue, please let me know

**Comment by devoncarew** [comment]
Great! I'll close this now given that the remaining issues are pre-existing.
