### ISSUE TITLE
Need an invoke method to call closures more quickly than possible with eval

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#34006]
With Dart 2, vm service eval is now a little too slow to efficiently use for cases where all you really need to do is invoke a closure passing in a list of arguments.

We would like to provide  enhanced debugger views of Map, List, Iterable, and Set objects even if they aren't the dart:core Map or List classes which puts some pressure on the VM service as calls are needed to detect that InstanceRef objects match one of these types and to collect chunks of children similar to what the VM Service does for Map and List.

I'm aware I'll need to handle when the references to closures go out of scope at which point I'll make a slower call to get another reference to the closure.

As discussed in
https://github.com/dart-lang/sdk/issues/34004
the best way to implement this is outside of the VM Service so we need an efficient way to implement this functionality which is where

**Comment by rmacnak-google** [comment]
`apply` and `eval` go together, it's odd we haven't already added this yet.

**Comment by rmacnak-google** [comment]
Do you need named arguments too?
