### ISSUE TITLE
Having `.dart_tool/` in a Flutter project breaks detection of Flutter's `analysis_options.yaml`

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#34007]
I noticed that `dartanalyze` / `flutter analyze` complains about super mixins:

`The class 'TickerProviderStateMixin' can't be used as a mixin because it extends a class other than Object`

I don't have `analysis_options.yaml` file in my project, so analyzer should default to flutter's `analysis_options_user.yaml` file. That one has super mixins enabled (among other things).

I noticed that dartanalyzer doesn't use the Flutter options file:

```
$ dartanalyzer -v .
Analyzing hn_app...
Using default analysis options
  error • The class 'TickerProviderStateMixin' can't be used as a mixin because it extends a class other than Object at lib/main.dart:127:10 • mixin_inherits_from_not_object
  [...]
```

This is weird because in any other Flutter project, dartanalyzer correctly uses the flutter options file:

```
$ dartanalyzer -v .
Analyzing hn_app_new_clone...
Loaded analysis options from /Users/filiph/dev/flutter/packages/flutter/lib/analysis_options_user.yaml
```

So _something_ confuses the analyzer about this project being Flutter or not.

I noticed that when I clone the project, I don't see the issue. So I diffed the new clone and the original project, and saw that the only meaningful difference was the existence of `.dart_tool/` directory (created by `build_runner`).

If I delete that directory, analyzer correctly identifies the project as Flutter. When I run `build_runner` again, the problem reappears.

cc @devoncarew 

* Dart SDK Version (`dart --version`)
  * Dart VM version: 2.0.0-dev.69.3 (Wed Jul 25 17:21:20 2018 +0200) on "macos_x64"
  * (Issue detected on Flutter's version as well, i.e. Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2.)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
  * N/A

**Comment by devoncarew** [comment]
I think what's happening here is that we're seeing some conflict between a `.dart_tool` specific resolution, to handle generated code, and flutter project detection.

**Comment by devoncarew** [comment]
The fix for this is landing now; it'll likely take a week or two to make it to flutter master.
