### ISSUE TITLE
Analyzer doesn't like `void Function(void)`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34008]
"error • Variables must be declared using the keywords 'const', 'final', 'var' or a type name"

CFE seems fine with it. `void Function(void x)` is a workaround.

**Comment by leafpetersen** [comment]
There's a comment to this effect here: https://github.com/dart-lang/sdk/issues/30177#issuecomment-407572900 .

**Comment by devoncarew** [comment]
I'm going to close this as a duplicate of https://github.com/dart-lang/sdk/issues/30177.
