### ISSUE TITLE
CFE: Triage void and invalid_return tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34014]
https://dart-review.googlesource.com/c/sdk/+/66521 adds un-triaged tests related to void and invalid returns with a status set to Skip. 

```
void/*: Skip 
invalid_returns/*: Skip  
```

 This issue is to track the work to triage these tests.  Please remove the appropriate Skip section from language_2.status (labelled with this bug), adjust any status files appropriately, and file any required additional issues to address failing tests.

**Comment by leafpetersen** [comment]
ping on this?  We're seeing issues around incorrect `void` warnings, it might be worth getting these triaged.

**Comment by kmillikin** [comment]
Thanks, it slipped through the cracks.  I'm on the case.

**Comment by kmillikin** [comment]
This is done.

**Comment by leafpetersen** [comment]
Re-opening - I misnamed the test for valid returns and there are still some failures.

**Comment by kmillikin** [comment]
It's been triaged and the underlying issue is fixed in 3224afe9fe9f6795046561ccc67e954e6b21c02f.
