### ISSUE TITLE
dart2js: Triage void and invalid_return tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34011]
https://dart-review.googlesource.com/c/sdk/+/66521 adds un-triaged tests related to void and invalid returns with a status set to Skip. 

```
void/*: Skip 
invalid_returns/*: Skip  
```

 This issue is to track the work to triage these tests.  Please remove the appropriate Skip section from language_2.status (labelled with this bug), adjust any status files appropriately, and file any required additional issues to address failing tests.

**Comment by leafpetersen** [comment]
Is this done?

**Comment by sigmundch** [comment]
yes - seems it was done indirectly in an unrelated change (4e4e9ec74a11a3e7bb62a19b0cad221cafc7ce75). 

Just checked and we seem to be matching expectations on all tests under void/ and invalid_returns/ at this time.
