### ISSUE TITLE
VM crashes trying to run Flutter unless a strange workaround is included in the BodyBuilder

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34016]
The following two versions of `BodyBuilder.handleUnaryPostfixAssignmentExpression` ought to have the same behavior:
(a)
```dart
  void handleUnaryPostfixAssignmentExpression(Token token) {
    debugEvent("UnaryPostfixAssignmentExpression");
    var generator = popForLvalue(token);
    var operator = incrementOperator(token);
    if (operator == null) {
      push(new DelayedPostfixIncrement(
          this, token, generator, operator, null));
    } else {
      push(new DelayedPostfixIncrement(
          this, token, generator, operator, null));
    }
  }
```
(b)
```dart
  void handleUnaryPostfixAssignmentExpression(Token token) {
    debugEvent("UnaryPostfixAssignmentExpression");
    var generator = popForLvalue(token);
    var operator = incrementOperator(token);
    push(new DelayedPostfixIncrement(
        this, token, generator, operator, null));
  }
```

However, I find that if I try to run Flutter using version (b) (and with 31af5ce13c45af007b521d4ea1e83698dcd21137 reverted), I see the crash described in #33993.  If I try to run it using version (a), I see no crash.

At the moment I suspect this is a VM bug, because it seems plausible that the presence of the `if` test in version (a) might be inhibiting a buggy optimization from occurring.

Detailed repro steps:
- Patch CL https://dart-review.googlesource.com/c/sdk/+/67280 to the Dart SDK codebase, replace the implementation of `BodyBuilder.handleUnaryPostfixAssignmentExpression` with the code in (b) above, and do a release build (in my tests I used version cb70de8afaf72ffccc2cb296960d3ed755979167 of the SDK as a starting point).
- Check out the Flutter repository (I used version https://github.com/flutter/flutter/commit/78a00cb13aa660545a6a886a43f266141c024adf).
- Go into the `packages/flutter_tools` subdirectory and run `pub get`.
- If you haven't built Flutter before, go out to the root directory of the Flutter repo and run `./bin/flutter`.
- Back in the `packages/flutter_tools` subdirectory, run `$path_to_dart_sdk/bin/dart --packages=.packages bin/flutter_tools.dart --help`, where `$path_to_dart_sdk` is the path to the patched SDK built above.

When I follow these steps I see the stacktrace from #33993.  I've verified these steps on Linux.  Based on working with @devoncarew this morning, I believe they should reproduce the problem on Mac as well.

**Comment by stereotype441** [comment]
Note: https://dart-review.googlesource.com/c/sdk/+/67280 had a merge conflict so I had to upload a new version of it.  I've confirmed that my steps above still reproduce the problem when patchset 2 is applied to 6e322f794c68510a52c100e0d2dfe9e0f60373a0.

**Comment by mraleph** [comment]
From a brief look it seems like this reveals an ancient bug - we hoist static final field loads above their lazy initialization.

I will make a fix tomorrow.

**Comment by mraleph** [comment]
Thanks for the detailed report Paul! This should now be fixed
