### ISSUE TITLE
VM: Triage void and invalid_return tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34013]
https://dart-review.googlesource.com/c/sdk/+/66521 adds un-triaged tests related to void and invalid returns with a status set to Skip. 

```
void/*: Skip 
invalid_returns/*: Skip  
```

 This issue is to track the work to triage these tests.  Please remove the appropriate Skip section from language_2.status (labelled with this bug), adjust any status files appropriately, and file any required additional issues to address failing tests.

**Comment by leafpetersen** [comment]
Is this done?

**Comment by athomas** [comment]
Yes: https://dart-ci.firebaseapp.com/current_results/#/filter=language/invalid_returns,language/void
