### ISSUE TITLE
Analyzer: Triage void and invalid_return tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34010]
https://dart-review.googlesource.com/c/sdk/+/66521 adds un-triaged tests related to void and invalid returns with a status set to Skip. 

```
void/*: Skip 
invalid_returns/*: Skip  
```

 This issue is to track the work to triage these tests.  Please remove the appropriate Skip section from language_2.status (labelled with this bug), adjust any status files appropriately, and file any required additional issues to address failing tests.

**Comment by leafpetersen** [comment]
I have a CL for this.

**Comment by leafpetersen** [comment]
I fixed the non CFE side of this here:  https://dart-review.googlesource.com/c/sdk/+/67282

The CFE path still needs triaging.

**Comment by bwilkerson** [comment]
Given that the integration with CFE has been suspended, I'm assuming that the required work has been done.
