### ISSUE TITLE
several unit test failures in pkg_tested/dart_style/test/formatter_test when the analyzer is switched to --use-fasta-parser

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34040]
./tools/test.py -m release -c none -r vm --checked --no-preview-dart-2 --use-sdk pkg_tested/dart_style/test/formatter_test

I see 4 unit test failures here, many with the message "Could not format because the source could not be parsed:".

**Comment by bwilkerson** [comment]
@danrubel in case the parser failures are interesting

**Comment by danrubel** [comment]
As of today, all but 3 are fixed. Working on them...

**Comment by danrubel** [comment]
dart formatter changes:
* [ignore non-semantic errors from the parser](https://github.com/dart-lang/dart_style/pull/724)
* update [map literal](https://github.com/dart-lang/dart_style/pull/725) test
* update [covariant modifier](https://github.com/dart-lang/dart_style/pull/726) test

**Comment by devoncarew** [comment]
fixed I believe
