### ISSUE TITLE
Analyzer/FE integration of outline data fails when there are compile errors

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34043]
This is a catch-all bug for test failures in which the test case has a compile error, and the analyzer is crashing while trying to decode the outline resolution information it receives from the front end.

Situations where this occurs:
- Duplicate enum name
  - language_2/enum_syntax_test/02
- Illegal operator names
  - language_2/operator_negative_test
  - language_2/syntax_test/{04-11,13-21,23-26}
- Extraneous comma before formal parameter
  - language_2/arg_param_trailing_comma_test/{24-26,72-74,98-100}
- Cycle in the class hierarchy - see also #33756
  - language_2/class_cycle2_test/{01,02}
  - language_2/class_cycle_test/{00,01}
  - language_2/conflicting_generic_interfaces_hierarchy_loop_infinite_test
  - language_2/conflicting_generic_interfaces_hierarchy_loop_test
  - language_2/cyclic_class_member_test/01
  - language_2/interface_cycle_test/{01,02}
  - language_2/mixin_cyclic_test/{01,02}
  - language_2/mixin_illegal_cycles_test/{01-06}
- Setter with wrong number of parameters - see also #33691
  - language_2/get_set_syntax_test/{02,03,06,07,10,11,14,15}
  - language_2/setter_declaration2_negative_test
  - language_2/setter_declaration_negative_test
- Default value in required parameter
  - language_2/parameter_default_test/{01-06}
- Attempt to use class type parameter in static signature
  - language_2/type_parameter_test/{04-06,08-09}
- Syntax error in class declaration
  - language_2/mixin_illegal_syntax_test/{06,10-12,14}
- Enum name collision
  - language_2/enum_syntax_test/{03-06}
- Illegal constructor name
  - language_2/constructor_name_test/02
  - language_2/factory2_test/01
  - language_2/factory_test/00
- Unknown problem
  - language_2/built_in_identifier_type_annotation_test/set
  - language_2/built_in_identifier_type_annotation_test/set-funret
- Attempt to apply type arguments to a non-generic type
  - language_2/generic_function_typedef2_test/04
- Illegal part file
  - language_2/internal_library_test/02
- Native const factory
  - language_2/const_native_factory_test
- Part file missing "part of" declaration - See also #33587
  - language_2/missing_part_of_tag_test/01
- Synthetic token used where type expected
  - language_2/built_in_identifier_illegal_test/implements
- Imported library has incorrect declaration order
  - language_2/script1_negative_test
- Part file contains a "library" declaration
  - language_2/script2_negative_test

This seems like the sort of issue where high level design work is needed, so for now I'm not going to file individual bugs for the subcategories listed above.

**Comment by stereotype441** [comment]
Note that @scheglov has done some work in this area related to the handling of types; perhaps his work can be extended.

**Comment by kmillikin** [comment]
Related to https://github.com/dart-lang/sdk/issues/33686

**Comment by stereotype441** [comment]
I've finished triaging the remaining test.py failures with analyzer/FE integration and updated the above list.  I believe the list of failing tests is now reasonably complete.  I've decided to remove failures due to #33686 from the list above (the distinction being that #33686 addresses situations where the front end fails to recover from errors at all; this bug addresses situations where the front end recovers from the error but in a way that the analyzer doesn't know how to map to its model)

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
