### ISSUE TITLE
Add ability to name isolates for debugging

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34059]
In https://github.com/flutter/flutter/issues/19490 @rmacnak-google said "the framework's use of wrapper functions makes it impossible to tell just from the isolate's name". It would be great if we could provide information to `Isolate.spawn` to make future debugging easier, since we actually have name information at hand when we make that call (we use it in Timeline calls). (I'm not sure where the Isolate's name appears, but presumably in debugging dumps or some such?)

**Comment by bkonyi** [comment]
Would we consider adding an optional `debugName` parameter to `Isolate.spawn` and `Isolate.spawnUri` a breaking change? I highly doubt anyone has used `Isolate` as an interface, so I can't see that being an issue, but maybe someone else can think of a situation where this might be breaking?

**Comment by natebosch** [comment]
>  I highly doubt anyone has used `Isolate` as an interface, so I can't see that being an issue, but maybe someone else can think of a situation where this might be breaking?

If we only add it to the static methods `Isolate.spawn` they aren't part of the interface so I think we should be fine. If we need to add an instance field on `Isolate` then it might be breaking, but I would be very surprised to see a class `implements Isolate`.

**Comment by natebosch** [comment]
Another suggestion from a while ago is to be able to set it from the `Service` class: https://github.com/dart-lang/sdk/issues/28207
