### ISSUE TITLE
Add a contributions-welcome GitHub issue label

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#34067]
It would be useful and welcoming to include a "contributions-welcome" label in our [battery of labels](https://github.com/dart-lang/sdk/wiki/How-the-issue-tracker-works#labels). Seeing this label on an issue conveys the following information:

* **The issue has been vetted as "legitimate."** For bugs, it's a legitimate bug. For feature requests, it's been accepted by the Dart team as "yeah we should have this." The label conveys **"We would accept a PR from an external contributor."**
* **Fixing the issue should not be overly difficult for an external contributor**, or require multiple areas of expertise. For example, adding a method to StringBuffer would probably not ever be labeled as "contributions-welcome", because StringBuffer's methods are mostly `external`, so an implementation would be required in dart2js, DDC, and the VM.
* **Fixing the issue should not require a great amount of code.** The Dart team might be hesitant to accept a giant pull request, e.g. consisting of > 100 LOCs, as we would then _own it_, in terms of bugs, support, updates.
* Maybe not intentionally or directly, but this kind of label will often convey "This is a legitimate bug / feature request, but the Dart team is not going to get to it any time soon."

This is similar to golang's ["help wanted"](https://github.com/golang/go/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. I've seen many projects with a similar label.

This label would mostly apply to bug fixes and documentation requests, but could certainly apply to feature requests as well. For example, [these >800 enhancements under "area-analyzer".](https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-analyzer+sort%3Aupdated-asc+-label%3Atype-bug) I would bet that > 80% of these could be labeled "contributions-welcome."

This label can also serve the community as a signal of "beginners start here." Users might sort through golang's "help wanted" issues to find an easy or interesting contribution. The same applies here: "contributions-welcome" signals "dive on in," "probably not hard."

**Comment by athomas** [comment]
https://github.com/dart-lang/sdk/labels/contributions-welcome

I added the label, would you mind updating the wiki, @srawlins?

**Comment by srawlins** [comment]
Thanks @athomas !! Done!
