### ISSUE TITLE
Expose runtime API for VM

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/sdk#34079]
Expose public API limited to VM platform (because of it's nature) to control VM stats, as well as maybe controlling GC etc. Under the VM stats I mean mostly memory usage, allocations metrics, etc.
More generally native package that similar to Go's runtime (https://golang.org/pkg/runtime/).

**Comment by mraleph** [comment]
VM exposes such API's via vmservice protocol. 

Please take a look at the [protocol specification](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service_dev.md) and let us know if something is missing.

**Comment by mraleph** [comment]
I am tentatively closing this. Let me know if vmservice protocol does not fit your intended use case.

**Comment by vanesyan** [comment]
Thanks, I'll look a bit more into it and give you feedback. Once again, thanks.
