### ISSUE TITLE
The method 'delete' isn't defined for the class

### ISSUE THREAD

**Issue by thanizebra** [dart-lang/sdk#34073]
dartdevc arguments: --dart-sdk=/usr/lib/dart --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd -o packages/da0/app_component.template.ddc.js --module-root=. --library-root=/lib --summary-extension=linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/collection/src/utils.linked.sum -s packages/collection/src/algorithms.linked.sum -s packages/collection/src/canonicalized_map.linked.sum -s packages/collection/src/comparators.linked.sum -s packages/collection/src/iterable_zip.linked.sum -s packages/collection/src/priority_queue.linked.sum -s packages/collection/collection.linked.sum -s packages/async/async.linked.sum -s packages/charcode/ascii.linked.sum -s packages/charcode/html_entity.linked.sum -s packages/charcode/charcode.linked.sum -s packages/path/path.linked.sum -s packages/source_span/source_span.linked.sum -s packages/string_scanner/string_scanner.linked.sum -s packages/typed_data/typed_buffers.linked.sum -s packages/typed_data/typed_data.linked.sum -s packages/http_parser/http_parser.linked.sum -s packages/http/src/base_client.linked.sum -s packages/angular/src/core/linker/view_type.linked.sum -s packages/meta/meta.linked.sum -s packages/angular/src/core/change_detection/change_detection.linked.sum -s packages/stack_trace/stack_trace.linked.sum -s packages/logging/logging.linked.sum -s packages/angular/src/core/zone/ng_zone.linked.sum -s packages/angular/src/core/application_tokens.linked.sum -s packages/angular/core.linked.sum -s packages/angular/di.linked.sum -s packages/meta/dart2js.linked.sum -s packages/js/js.linked.sum -s packages/js/js_util.linked.sum -s packages/angular/src/core/change_detection/change_detection.template.linked.sum -s packages/angular/di.template.linked.sum -s packages/angular/src/core/application_tokens.template.linked.sum -s packages/angular/core.template.linked.sum -s packages/intl/date_symbols.linked.sum -s packages/intl/number_symbols.linked.sum -s packages/intl/number_symbols_data.linked.sum -s packages/intl/src/plural_rules.linked.sum -s packages/intl/intl.linked.sum -s packages/angular/src/bootstrap/modules.linked.sum -s packages/angular/angular.linked.sum -s packages/angular_router/src/directives/router_outlet_directive.linked.sum -s packages/angular_router/src/constants.linked.sum -s packages/da0/app_component.css.shim.linked.sum -s packages/angular_router/angular_router.linked.sum -s packages/angular/src/bootstrap/run.template.linked.sum -s packages/angular/angular.template.linked.sum -s packages/angular_router/src/directives/router_outlet_directive.template.linked.sum -s packages/angular/src/core/change_detection/directive_change_detector.linked.sum -s packages/angular_router/angular_router.template.linked.sum -s packages/da0/src/post.linked.sum -s packages/http/http.linked.sum -s packages/da0/src/post.template.linked.sum -s packages/angular_forms/src/directives.linked.sum -s packages/angular_forms/angular_forms.linked.sum -s packages/angular_forms/angular_forms.template.linked.sum -s packages/da0/src/dashboard_component.css.shim.linked.sum -s packages/da0/app_component.linked.sum --url-mapping=package:da0/app_component.template.dart,packages/da0/app_component.template.dart --url-mapping=package:da0/src/routes.template.dart,packages/da0/src/routes.template.dart package:da0/app_component.template.dart package:da0/src/routes.template.dart
    dart --version: 2.0.0-dev.69.5 (Unknown timestamp) on "linux_x64"
```
AnalysisException: Cannot compute LIBRARY_ELEMENT for packages/da0/app_component.template.dart
Caused by Infinite loop while performing task InferInstanceMembersInUnitTask for packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
  Dependency Cycle:
    Run InferInstanceMembersInUnitTask on packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
    Run ResolveInstanceFieldsInUnitTask on packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
    Run InferStaticVariableTypesInUnitTask on packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
    Run PartiallyResolveUnitReferencesTask on packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
    Run InferInstanceMembersInUnitTask on packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    Run ResolveInstanceFieldsInUnitTask on packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    Run InferStaticVariableTypesInUnitTask on packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    Run PartiallyResolveUnitReferencesTask on packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT10 for packages/da0/src/routes.template.dart in packages/da0/src/routes.template.dart
    INFERABLE_STATIC_VARIABLES_IN_UNIT for packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    RESOLVED_UNIT8 for packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    RESOLVED_UNIT9 for packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart
    CREATED_RESOLVED_UNIT10 for packages/da0/src/post_list_component.template.dart in packages/da0/src/post_list_component.template.dart

#0      AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:320:11)
#1      AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#6      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#7      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#8      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#9      _CompilerWorker.performRequest (file:///tmp/tmpfbghuQ/dart-2.0.0-dev.69.5/dart/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///tmp/tmpfbghuQ/dart-2.0.0-dev.69.5/dart/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:726:7)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#2      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#3      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#4      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#5      _CompilerWorker.performRequest (file:///tmp/tmpfbghuQ/dart-2.0.0-dev.69.5/dart/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#6      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#12     main (file:///tmp/tmpfbghuQ/dart-2.0.0-dev.69.5/dart/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```
}

[SEVERE] build_web_compilers|ddc on lib/src/dashboard_component.css.shim.module (cached):
Error compiling dartdevc module:da0|lib/src/dashboard_component.css.shim.ddc.js

[error] The method 'delete' isn't defined for the class 'PostListComponent'. (package:da0/src/post_list_component.template.dart, line 213, col 9)
[error] The getter 'hero' isn't defined for the class 'PostListComponent'. (package:da0/src/post_list_component.template.dart, line 213, col 20)

Please fix all errors before compiling (warnings are okay).
}

[SEVERE] Failed after 1.5s

**Comment by jmesserly** [comment]
this might be fixed when we move DDC off task model, see https://github.com/dart-lang/sdk/issues/35013

**Comment by natebosch** [comment]
Should no longer be a problem with the latest `build_web_compilers` on very recent SDKs.
