### ISSUE TITLE
Cannot try SDK on Fedora or RHEL

### ISSUE THREAD

**Issue by ukulanne** [dart-lang/sdk#34089]
Cannot try SDK on Fedora or RHEL. You use to have tarballs with the binaries but now they are gone. Not everybody has Ubuntu.

**Comment by julemand101** [comment]
You can still download a binary version of Dart SDK for Linux on this page (it is not tarballs but zip files but I hope thats ok):
https://www.dartlang.org/tools/sdk/archive

**Comment by ukulanne** [comment]
While far from ideal, I can work with this for sure. Thanks

**Comment by athomas** [comment]
We currently don't have plans to create additional Linux packages in the future. Another alternative would be use Dart in a docker container.
