### ISSUE TITLE
json.decode() FormatException when decoding String

### ISSUE THREAD

**Issue by alexd1971** [dart-lang/sdk#34084]
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "macos_x64"
MacOS X

When decoding a string json.decode throws a FormatException:
```dart
json.decode('qwerty'); // throws FormatException: SyntaxError: Unexpected token q in JSON at position 0
```
But
```dart
print(json.encode('qwerty')); // prints qwerty
```
And
```
print(json.encode('qwerty').runtimeType);// prints String
```
And
```
print(json.decode(json.encode('qwerty')); // prints 'qwerty'
```
Is this a bug?

**Comment by rakudrama** [comment]
You say:
```dart
print(json.encode('qwerty')); // prints qwerty
```
It prints a string of 8 characters, including the quotes, i.e. `"qwerty"`.
The quotes are part of the string. `print` does not add quotes to indicate the value is a String.

The string needs quotes to be passed to `json.decode`:
```dart
json.decode('"qwerty"');
```
This is working as specified.

**Comment by alexd1971** [comment]
Thank you
