### ISSUE TITLE
generated kernel file is not deterministic

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#34086]
From the same set of sources compiler produces kernel files that are slightly different where "no such method forwarders" for the same private name are transposed.

To repro

```
out/ReleaseX64/dart-sdk/bin/dart --dfe=out/ReleaseX64/kernel-service.dart.snapshot --snapshot-kind=script --kernel_multiroot_filepaths=`pwd`/p/d/dart-sdk/sdk --kernel_multiroot_scheme=dartlang --snapshot=tmfs.dill --sync-async  --strong  pkg/analysis_server/bin/server.dart && $DH/out/ReleaseX64/dart-sdk/bin/dart $DH/pkg/kernel/bin/dump.dart tmfs.dill > dump-mfs.txt 
```

Compare dump-mfs.txt from several runs and observe the difference along the lines:
```
215137a215136,215137
>     no-such-method-forwarder get _returnType() → type::DartType
>       return this.{link::GenericTypeAliasElementForLink::noSuchMethod}(new core::_InvocationMirror::_withoutType("get:_returnType", const <core::Type>[], const <dynamic>[], core::Map::unmodifiable<core::Symbol, dynamic>(const <core::Symbol, dynamic>{}), false)) as{TypeError} type::DartType;
215170,215171d215169
<     no-such-method-forwarder set _returnType(type::DartType value) → void
<       return this.{link::GenericTypeAliasElementForLink::noSuchMethod}(new core::_InvocationMirror::_withoutType("set:_returnType", const <core::Type>[], core::List::unmodifiable<dynamic>(<dynamic>[value]), core::Map::unmodifiable<core::Symbol, dynamic>(const <core::Symbol, dynamic>{}), false));
```

The culprit seems to be `_PrivateName._computeHashCode` function which is built on top of `Reference` `hashCode`, which is simply inherited from `Object`: https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/ast.dart#L4451.

One solution might be to remove reference.hashCode from `_PrivateName._computeHashCode`:
```
diff --git a/pkg/kernel/lib/ast.dart b/pkg/kernel/lib/ast.dart
index 959a84b1d0..b424ab1e37 100644
--- a/pkg/kernel/lib/ast.dart
+++ b/pkg/kernel/lib/ast.dart
@@ -4614,7 +4614,7 @@ class _PrivateName extends Name {
   Library get library => libraryName.asLibrary;
 
   static int _computeHashCode(String name, Reference libraryName) {
-    return 131 * name.hashCode + 17 * libraryName.hashCode;
+    return name.hashCode;
   }
 }
```

Another solution might be to define Reference hashCode similarly how it is defined for TreeNode: https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/ast.dart#L107 that guarantees unique hashCode for every instance of Reference.

cc @alexmarkov @keertip @davidmorgan

**Comment by kmillikin** [comment]
cc @stefantsov

**Comment by keertip** [comment]
This should be treated as a P1, it blocks landing performance improvements in google3.

**Comment by kmillikin** [comment]
Thanks for the context.  I agree with the priority.

**Comment by stefantsov** [comment]
I'm actively working on it.  I hope to upload a fix within a few hours.

**Comment by stefantsov** [comment]
I have a workaround in [CL 68940](https://dart-review.googlesource.com/c/sdk/+/68940).  It removes the described non-determinism and seems slightly more preferable than the two described approaches.  Compared to using just `name.hashCode` it doesn't make `_compareNames` slower when a private and non-private names with the same `.name` are passed in (probably the same reasoning can be applied to using `Name`s in `Set`s and `Map`s).  Compared to using enumeration on `Reference`s as `hashCode` it should not result in accidental member reordering in our `*.expect` files when a CL changes the order in which `Reference`s are created.  The downside of the CL is that member reordering in `*.expect` files may happen if the `Library` objects are created in different order, but I think it's something that we can fix later, when this P1 is addressed.

**Comment by stefantsov** [comment]
Ok, I didn't think about `Reference` objects created for not yet loaded libraries.  They don't have access to `_libraryId`.  Had to go with fix 1 from the above.

Also, it would be great to have a test for non-determinism.  I'll try to ask around about having it.

**Comment by keertip** [comment]
@stefantsov, with your fix patched in I no longer see a difference in the names. But, the order of the "no such method forwarders" is not the same when generating the kernel, and so that has to be fixed to make them deterministic.

**Comment by stefantsov** [comment]
@keertip Is there a repro?  With my CL landed I try to do what @aam has described, and the output from two different runs is the same.

**Comment by aam** [comment]
@keertip do you see differences in the order of nsm-forwarders from multiple runs of patched version or you see difference between patched and unpatched version?

Later is probably expected.

I did few runs of patched versions, kernel dump files all look identical.

**Comment by keertip** [comment]
@stefantsov, was testing with a version where the kernel service was not updated with the changes. After updating the kernel service snapshot with the fix, can now generate deterministic kernel.

**Comment by stefantsov** [comment]
Thanks @keertip!  I'm happy that it worked.

I'm lowering the priority, because the workaround has landed.  I'll keep the issue open until we have a test that check for non-determinism or until we decide that it's not needed.

**Comment by jensjoha** [comment]
What's the status on this?

**Comment by jensjoha** [comment]
Considering we haven't heard anything for 3+ years I'll assume this one is fine and close.
