### ISSUE TITLE
Malformed code completion in IntelliJ for Setters & Getters

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/sdk#34082]
Consider the following simple class:

```Dart
class MyType {
  String _someString = "";
  /// Returns "Hello " + the value of someString.
  get someString => "Hello " + _someString;
  set someString(String value) => _someString = value;
}
```
If the getter someString is placed before the setter someString, the code completion in IntelliJ marks the property as someString(String value), with no documentation.

Consider the following modified class:

```Dart
class MyType {
  String _someString = "";
  set someString(String value) => _someString = value;
  /// Returns "Hello " + the value of someString.
  get someString => "Hello " + _someString;
}
```
If the getter with documentation comes after the setter, the code completion correctly displays it as property of type String.

Code completion should be able to present the member as a property no matter if the getter or setter is declared first in the class body.

Code completion should also be able to present documentation for both get and set scenarios, even if documentation is only declared on the setter or getter.

**Comment by weenzeel** [comment]
Issue is also tracked by IntelliJ issue tracker as WEB-34113.

**Comment by alexander-doroshko** [comment]
@a-siva, @bwilkerson, I'm not sure `area-intellij` is the right label here. I guess it's Analysis Server responsibility.

**Comment by bwilkerson** [comment]
We are now correctly displaying the comment in both cases, but the presentation is still different and shouldn't be.

**Comment by keertip** [comment]
Will not be worked on in the near future.
