### ISSUE TITLE
Failing dart2js unit tests

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#34095]
Some dart2js unit tests are failing. This was not caught in the CQ/CI at the time of introduction because of a bug in the infrastructure (the first failing build is when @whesse fixed the bug).

I'm marking this as P1 because I don't know how important these tests are.

https://ci.chromium.org/p/dart/builders/luci.dart.try/dart2js-unit-linux-x64-release-try/1418

**Comment by rakudrama** [comment]
dart2js/codegen/string_interpolation_test fixed by 8195fd8c64

**Comment by rakudrama** [comment]
Johnni, this is my partial attempt at fixing the type_mask one: https://dart-review.googlesource.com/c/sdk/+/69245

**Comment by vsmenon** [comment]
Is this obsolete?  We should track bot failures elsewhere.

**Comment by rakudrama** [comment]
dart2js/codegen/string_interpolation_test -- passes
dart2js/rti/rti_emission_test -- passes

dart2js/inference/type_mask2_test -- moved to https://dart-review.googlesource.com/c/sdk/+/109981
