### ISSUE TITLE
[SEVERE] build_web_compilers|ddc on package:angular_components/material_tab/material_tab.template.module (cached): Error compiling dartdevc module:angular_components|lib/material_tab/material_tab.template.ddc.js

### ISSUE THREAD

**Issue by Florence2016** [dart-lang/sdk#34094]
* Dart SDK Version (`--version: 2.0.0`)
* Windows 10
* Chrome

AnalysisException: Cannot compute LIBRARY_ELEMENT for C:\Users\....\AppData\Local\Temp\scratch_spaceed25b7ba-9ad6-11e8-a5ac-18dbf251ebdc\packages\angular_components\material_tab\material_tab.template.dart
Caused by Unexpected exception while performing BuildDirectiveElementsTask for source C:\Users\.....\AppData\Local\Temp\scratch_spaceed25b7ba-9ad6-11e8-a5ac-18dbf251ebdc\packages\angular_components\material_tab\material_tab.template.dart
#0      AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:335:7)
#1      AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#6      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#7      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#8      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#9      _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Caused by RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
#0      List.[] (dart:core/runtime/libarray.dart:10:52)
#1      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:820:20)
#2      _LibraryResynthesizerContext.buildImportedLibrary (package:analyzer/src/summary/resynthesize.dart:828:61)
#3      ImportElementImpl.importedLibrary (package:analyzer/src/dart/element/element.dart:5915:16)
#4      LibraryElementImpl.importedLibraries (package:analyzer/src/dart/element/element.dart:6631:40)
#5      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:17)
#6      List.forEach (dart:core/runtime/libarray.dart:79:8)
#7      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7011:35)
#8      List.forEach (dart:core/runtime/libarray.dart:79:8)
#9      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#10     List.forEach (dart:core/runtime/libarray.dart:79:8)
#11     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#12     List.forEach (dart:core/runtime/libarray.dart:79:8)
#13     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#14     List.forEach (dart:core/runtime/libarray.dart:79:8)
#15     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7011:35)
#16     List.forEach (dart:core/runtime/libarray.dart:79:8)
#17     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#18     List.forEach (dart:core/runtime/libarray.dart:79:8)
#19     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#20     List.forEach (dart:core/runtime/libarray.dart:79:8)
#21     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7012:35)
#22     List.forEach (dart:core/runtime/libarray.dart:79:8)
#23     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:7011:35)
#24     LibraryElementImpl.invalidateLibraryCycles (package:analyzer/src/dart/element/element.dart:7016:15)
#25     BuildDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:1220:22)
#26     AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:323:9)
#27     AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#28     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#29     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#30     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721:14)
#31     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#32     ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#33     _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#34     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#35     _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#36     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#42     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#43     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:726:7)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#2      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#3      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#4      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#5      _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#6      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#12     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by natebosch** [comment]
Not sure if the underlying bug is in the way build_web_compilers is invoking DDC... but we probably want to start with finding why we're getting a stack trace.

**Comment by Florence2016** [comment]
What I did to solve this issue
I deleted the scratch_space...on the Temp folder.

It created multiple folders then, when I clear it then tried webdev serve
it builds

**Comment by Florence2016** [comment]
then I add dependency scratch space package...I dont know if its part of
the solution..

**Comment by vsmenon** [comment]
We think this is obsolete.
