### ISSUE TITLE
dart2js: remove Dart1 support

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#34109]
This is gated on migrating IE bots (tracked in #33454)

**Comment by vsmenon** [comment]
@rakudrama @johnniwinther - are one of you working on this?  Or should we bump from 2.1?

**Comment by rakudrama** [comment]
Johnni has been removing Dart1 support, e.g.

75943282e5	Delete Flags.strongMode and references to it
244c9bebec	Remove STRONG_MODE flag
814738b273	Remove CompilerOptions.strongMode/enableTypeAssertions/trustTypeAnnotations
3af2f793ac	Remove --no-preview-dart-2 from dart2js

I feel this is going well and it is worth pushing to to the point we can close out the issue.
It is really paying down the technical debt, e.g. the above changes remove about ~1500 LOC.
