### ISSUE TITLE
Linter offers contradictory advice about const

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/sdk#34100]
Given a analysis_options.yaml file that contains:
```
linter:
  rules:
    - prefer_const_constructors
```
Applying `flutter analyze` to the following file generates an error:

```
import 'package:collection/collection.dart' show UnmodifiableSetView;
class Foo<T> {
  void bar() {
    print(const UnmodifiableSetView<T>.empty());
  }
}
```

```
  error • A constant creation can't use a type parameter as a type argument • lib/main.dart:5:37
```

Replacing `const` with `new` generates:
```
   info • Prefer const with constant constructors • lib/main.dart:5:11
```

**Comment by HansMuller** [comment]
This issue came up here: https://github.com/flutter/flutter/pull/19739

**Comment by bwilkerson** [comment]
It should be easy to not emit the lint when there are type parameters in the type arguments list.

@a14n (in case you're interested)

**Comment by a14n** [comment]
Dup of #33289 migrated to dart-lang/linter#1022
