### ISSUE TITLE
AOT snapshots built with --enable_asserts should retain the token stream for assert().

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#34110]
Otherwise we get assertion failure error messages like:

```
'foo.dart': Failed assertion: line -1: '<optimized out>': is not true.
```

/cc @rmacnak-google @mraleph

**Comment by a-siva** [comment]
How is this going to work in the Dart 2 world, we do not have token streams. Are you suggesting they include the source code? That would explode the size of AOT snapshots.

**Comment by a-siva** [comment]
No we do not have any token streams in the 2.0 world, we would have to figure out an alternative scheme.

**Comment by a-siva** [comment]
Marking this as a duplicate of https://github.com/dart-lang/sdk/issues/53343

**Comment by a-siva** [comment]
Reopening issue as we will use this to track the functionality of ensuring messages from asserts are handled correctly in AOT.
