### ISSUE TITLE
Async articles are out of date / wrong

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34123]
This gives a lot of no longer accurate advice:

https://www.dartlang.org/tutorials/language/futures

See a confused user here: https://www.reddit.com/r/dartlang/comments/965b8u/async_in_dart/?utm_content=full_comments&utm_medium=message&utm_source=reddit&utm_name=frontpage

Not sure who to ping: @kwalrath @chalin @munificent or if ithis is the right repo for this issue

**Comment by kwalrath** [comment]
This is the right repo. Thanks for the report.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-www#1070

**Comment by MichaelRFairhurst** [comment]
Ah I will remember that!

Thanks Patrice & Kathy!
