### ISSUE TITLE
Source span for assignment errors should be the whole RHS

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#34126]
```dart
f(List<A> a) {
  List<B> b;
  b = a.where((e) => e is B).toList();
}
class A {}
class B {}
```

Analyzer highlights the whole expression that cannot be assigned to `b`.
![image](https://user-images.githubusercontent.com/384794/43981019-1a4f597a-9ca5-11e8-8795-7d78222021e6.png)

CFE should just the last invocation - `toList`.
![image](https://user-images.githubusercontent.com/384794/43981062-3a8a0280-9ca5-11e8-93a3-bce097c0336b.png)

This is not user friendly.
We need to highlight the whole RHS.
In order to do this in CFE we need to know the start and the end offset of the expression given into `BodyBuilder.wrapInCompileTimeError`:
```dart
  Expression wrapInCompileTimeError(Expression expression, Message message,
      {List<LocatedMessage> context}) {
    return wrapInLocatedCompileTimeError(expression,
        message.withLocation(uri, forest.readOffset(expression), noLength),
        context: context);
  }
```

We discusses this locally in PDX and while we could do something Analyzer specific, e.g. put begin/end tokens into `XyzTokens` classes, all other backends also should report errors in the same way for consistency. So, we need a general solution.

Does CFE team has ideas about this?

One direct approach is to add `fileStartOffset` and `fileEndOffset` to every `ExpressionJudgment` implementation. Does this sound OK?

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
