### ISSUE TITLE
js-interop: Error while passing Map<String,Dynmaic> from dart code to js function

### ISSUE THREAD

**Issue by drbcode** [dart-lang/sdk#34130]
repository that reproduces this issue:
https://github.com/drbcode/dart_interop_map_issue

pubspec.yaml
```yaml
name: dart_interop_map_issue
version: 0.0.1
description:
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  js: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
```

web/index.html
```yaml
<!DOCTYPE html>

<html>
<head>
    <title>test</title>
    <script src="test.js"></script>
    <script src="test.dart.js" defer></script>
</head>

<body>
</body>
</html>

```

web/test.js
```js
function mapTester(a) {
    console.log("logging value of a.b");
    console.log(a.b);
}
```

web/test_interop.dart
```dart
@JS()
library some_test;

import 'package:js/js.dart';

@JS('mapTester')
external mapTester(Map<String,dynamic> a);

@JS('mapTester')
external mapTester2(a);
```

web/test.dart
```dart
import 'test_interop.dart' as interop_test;
import 'dart:js';

void main() {
  Map<String,dynamic> a={
    "b":1,
  };
  // doesn't work
  interop_test.mapTester(a);
  interop_test.mapTester2(jsify(a));
}

dynamic jsify(dynamic obj) {
  if (obj == null || obj is num || obj is String) {
    return obj;
  } else if (obj is Map) {
    // Do a deep convert.
    Map m = {};
    for (var key in obj.keys) {
      m[key] = jsify(obj[key]);
    }
    return new JsObject.jsify(m);
  } else if (obj is Iterable) {
    // Do a deep convert.
    return new JsArray.from(obj).map(jsify);
  } else {
    return obj;
  }
}
```

### how to run

```bash
webdev serve
```

### console output

```
logging value of a.b
undefined
logging value of a.b
undefined
```

### expected output

```
logging value of a.b
1
logging value of a.b
1
```

### what works
Old interop done using `dart:js` works fine.

```dart
test(Map<String, dynamic> items) {
    context.callMethod('mapTester', [jsify(items)]);
    return;
}
```

There are APIs like `chrome.storage.local.set` that require you to pass a `Map<String, dynamic> items`, this can't be done using new interop (`'package:js/js.dart';`) but it's possible to do with old interop (`dart:js`).

  js:
    version: "0.6.1+1"
  json_annotation:
    version: "1.1.0"
  Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "linux_x64"

**Comment by matanlurey** [comment]
A `Map` in Dart is not the same thing as an object in JavaScript.

You might want to look at some examples:
* https://github.com/matanlurey/dart_js_interop#creating-a-structured-object
* https://github.com/matanlurey/dart_js_interop#creating-an-unstructured-object

**Comment by drbcode** [comment]
It says `error: The function 'createObject' isn't defined. (undefined_function at [dart_interop_map_issue] web/test.dart:10)`

```dart
// lib.dart

import 'package:js/js_util.dart' as js;

void main() {
  var object = js.createObject();
  js.setProperty(object, 'anyName', 'anyValue');
}
```

**Comment by drbcode** [comment]
The problem is I'm writing a public facing API and making developers write abstract classes for creating js object doesn't seem like the right thing to do.

In older versions of dart I was able to use jsify function that I have posted above for `dart:js` package that worked fine.

Is there any way to dynamically convert dart map to js objects that is supported by new `js` package?

**Comment by drbcode** [comment]
I made a post on stackoverflow.
Dynamically convert a Dart 2 Map to a Javascript object:
https://stackoverflow.com/questions/51804476/dynamically-convert-a-dart-2-map-to-a-javascript-object

**Comment by drbcode** [comment]
In above example I'm passing both a normal map and jsified map, in both cases it fails, I believe this is a bug, if not then `context.callMethod('mapTester', [jsify(items)]);` should fail as well.

**Comment by drbcode** [comment]
Code
```dart
void main() {
  Map<String,dynamic> a={
    "b":1,
  };
  interop_test.mapTester(a);
  interop_test.mapTester2(a);
  interop_test.mapTester2(jsify(a));
  interop_test.mapTester2(JsObject.jsify(a));
  context.callMethod('mapTester', [jsify(a)]);
}
```
Output:

![interop_issue](https://user-images.githubusercontent.com/41248528/43997048-d396fdbc-9dee-11e8-83d0-2490f6faeb36.png)

Why it doesn't fail for `context.callMethod('mapTester', [jsify(a)]);` ?

**Comment by drbcode** [comment]
This one solved the issue for me, also the documentation that you have linked to doesn't include examples for latest SDKs, need some correction there , will send PRs soon.

```dart
import 'test_interop.dart' as interop_test;
import 'package:js/js_util.dart' as js;
void main() {
  Map<String,dynamic> a={"b":1,};
  interop_test.mapTester(mapToJSObj(a));
}
Object mapToJSObj(Map<dynamic,dynamic> a){
  var object = js.newObject();
  a.forEach((k, v) {
    var key = k;
    var value = v;
    js.setProperty(object, key, value);
  });
  return object;
}
```
