### ISSUE TITLE
switch for enum incorrectly warns about return type (regressed from dev-69.4.flutter-08f59e5de3 )

### ISSUE THREAD

**Issue by kdy1** [dart-lang/sdk#34132]
Current version of dart reports `warning: This function has a return type of 'Widget', but doesn't end with a return statement. (missing_return at [my_proj] lib\common\progress_button.dart:51)` even if all variants of an enum are handled.

### `flutter doctor -v`
```
[√] Flutter (Channel @u, v0.5.9-pre.22, on Microsoft Windows [Version 10.0.17134.165], locale ko-KR)
    • Flutter version 0.5.9-pre.22 at C:\Users\kdy\flutter
    • Framework revision ef71d9d956 (7 hours ago), 2018-08-12 00:16:43 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

```
----

I'm not sure if this was intended.

**Comment by mraleph** [comment]
Please post your switch statement. 

Most likely you don't handle `null` value.

**Comment by srawlins** [comment]
Did you handle the null case? 😄

**Comment by a-siva** [comment]
Closing this under 'works as intended'
