### ISSUE TITLE
BigInt parsing anomaly

### ISSUE THREAD

**Issue by shamblett** [dart-lang/sdk#34140]
* Dart SDK Version  - Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64
* Using Windows, Linux 
 
When trying BigInt.parse("0x0000000000000000000000000000000000000000000000000000000000000000");

I'm getting 'FormatException: Could not parse BigInt 0x'

Shouldn't this just return BigInt.zero?

**Comment by lrhn** [comment]
It should. It does for me on tip-of-tree. The exception printed should come from 
```dart
throw new FormatException("Could not parse BigInt", source);
```
so it should include the entire source, not just the first two characters. 
Can you check if there is any way that string could be cut short to only two characters in your code?

**Comment by shamblett** [comment]
Yes your right, its being truncated to '0x', I guess this should fail parsing so no problem here now.

**Comment by a-siva** [comment]
closing based on comment above, if it is still a problem please reopen
