### ISSUE TITLE
Add "--use-cfe" flag to smith:configuration, and create configs for steps on --use-cfe builders.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#34151]
the builders:    {
      "builders": [
        "analyzer-use-cfe-linux",
        "analyzer-use-cfe-mac"
        "analyzer-use-cfe-win"
 
Have two test.py steps that pass --use-cfe to test.py.  We need to add this fkag to the configuration code in pkg/smith, and add a named configuration for these steps.

**Comment by whesse** [comment]
Also add --analyzer-use-fasta-parser flag to the test configuration.

**Comment by athomas** [comment]
Presumed done.
