### ISSUE TITLE
Analyzer says `unnecessary_cast`, but removing cast is a compile-time error.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34150]
Example:
```dart
const int minValue = (1 << 63);
T abs<T extends num>(T value) {
  if (value is int && value == minValue) return minValue as num;
  return -value;
}
main() {
  print(abs(42));
}
```
Here the analyzer (according to dartpad) complains that `as num` is unnecessary.
However, without the cast, `minValue` is not assignable to `T`.

**Comment by srawlins** [comment]
The unnecessary_cast warning now only reports when the cast type is the exact same as the expression's static type.

**Comment by lrhn** [comment]
(And eerily the following should therefore still be reported:
```dart
  List<num> nums = []; 
  if (nums is! List<int>) nums = [1] as List<int>;
  print([nums].runtimeType);
```
but removing the cast will change the static type of `nums` after the `if`. 
You just can't be sure without knowing what the type inference would do *without* the cast, and the cast changes the context type of the expression it casts. This is probably good enough, the cases where an `as` is used for its ability to block a context type are likley few far between in any code that has to get through code review.)
