### ISSUE TITLE
Add a "message" property to @Deprecated annotation

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/sdk#34155]
`@Deprecated` allows for an "expires" string, but not a generic "message."  A message should be added so that developers can provide migration instructions for deprecated members.

Ex:
```dart
@Deprecated(
  message: 'Use XXXX instead.',
  expires: 'v1.0.3',
)
```

**Comment by matanlurey** [comment]
I think the honest answer based on usage already is just rename `expires` to `message`, sine that is how it is actually being used in real code today. I'm also sympathetic to adding other properties that allow tools to auto-suggest fixes, i.e.:

```dart
@Deprecated.movedTo('newMethod')
void oldMethod() {}

void newMethod() {}
```
