### ISSUE TITLE
pub get already having problems

### ISSUE THREAD

**Issue by hzmnet** [dart-lang/sdk#34157]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)   
**Newest**
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
VS code

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----
when we create a simple web-angular and run “pub get".
we already got below issues

```
Resolving dependencies...
It looks like xxxx  (package) is having some trouble.
Pub will wait for a while before trying to connect again.
```

**Comment by matanlurey** [comment]
The right place for this bug report is https://github.com/dart-lang/pub/issues.

You'll need to include more information - are you behind a proxy, for example?
