### ISSUE TITLE
Implementation Issue for SuperMixins: Intellij

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#34169]
**What:** Issue for implementation for intellij

**ETA:** 10/15 in Dart Repo. 

**For:** [SuperMixins Implementation]( https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md) and [strawman documentation](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) 

**Meta Issue:** This is subsumed under the [Super Mixins Meta Issue in the Language Repo](https://github.com/dart-lang/language/issues/12)

**Comments:** Feel free to break this further into further tasks and issues, or use as a meta issue for all the tasks in the implementation plan

**Comment by devoncarew** [comment]
also, cc @alexander-doroshko

**Comment by devoncarew** [comment]
Note that this will be a syntax change, and updating IntelliJ's parser may block rolling the new mixins into Flutter.

**Comment by leafpetersen** [comment]
Per @jwren this is at least close to implemented, but we need to make sure it gets rolled into the appropriate versions and released.

**Comment by jwren** [comment]
@alexander-doroshko implemented in IntelliJ, version IntelliJ IDEA 2018.2.3.  @leafpetersen, @bwilkerson and myself just verified.

Dart Plugin version 182.4323.44
