### ISSUE TITLE
Implementation Issue for SuperMixins: Analyzer

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#34164]
**What:** Issue for implementation for Analyzer

**ETA:** 10/15 in Dart Repo.

**For:** [SuperMixins Implementation]( https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md) and [strawman documentation](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) 

**Meta Issue:** This is subsumed under the [Super Mixins Meta Issue in the Language Repo](https://github.com/dart-lang/language/issues/12)

**Analyzer Tasks**

- [x] Add the AST nodes required to represent the new mixin syntax
- [x] Add support to AstBuilder to build the AST (dependent on the fasta parser work) - @danrubel
    - [x] Add parser recovery for mixin header similar to class header - @danrubel
- [x] Add support to the element model to represent the semantics of mixins - @bwilkerson
- [x] Add support for the new mixins to summary files - @scheglov
- [x] Add support for resolving the new mixin syntax - @scheglov
- [x] Add support for building the new mixin element model - @scheglov
- [x] Add error checking related to the new mixin semantics (mostly done)

**Analysis Server Tasks**

- [x] Add indexing/search support - @scheglov
- [x] Add code completion support
  - [x] keyword completion - @bwilkerson
  - [x] completion in on clause - @bwilkerson
  - [x] new mixins should not be suggested in extends clauses - @bwilkerson
  - [x] new mixins should not be suggested in instance creations
- [x] Add folding support - @bwilkerson
- [x] Add outline support - @bwilkerson
- [x] Add syntax highlighting support - @bwilkerson
- [x] Add hover support - @bwilkerson
- [ ] Add quick fixes for new errors - @scheglov
- [ ] Add a quick assist to convert existing classes to the new syntax (when appropriate)
  - [x] Initially available at declaration sites - @bwilkerson
  - [ ] Eventually available at use sites as well - @danrubel

**Comment by danrubel** [comment]
Parsing, events, parse errors, recovery, and AstBuilder mods are now complete.

**Comment by leafpetersen** [comment]
Do we have an estimate on when error checking will land?

**Comment by bwilkerson** [comment]
Error checking has started to land, but is not yet complete.

**Comment by leafpetersen** [comment]
CL out here with mixin inference tests: https://dart-review.googlesource.com/c/sdk/+/74017

**Comment by leafpetersen** [comment]
Inference tests have landed.  cc @scheglov 

mixin_declaration/mixin_declaration_inference_valid_classes_test: CompileTimeError # https://github.com/dart-lang/sdk/issues/34164

**Comment by bwilkerson** [comment]
I created #34661 to capture the rest of the rest of the work on the quick assist. There are many errors that need quick fixes besides the new ones added for this feature, so I didn't create an issue for those.

Those are both nice to haves, so I'm marking this as done.

**Comment by DanTup** [comment]
@bwilkerson There's a tick above next to "keyword completion" - is this expected to be in `master`? I don't see it using yesterdays nightly build (`2.2.0-edge.f6c41ac3bc4ca689de745588c282425c9adf8262`):

<img width="348" alt="screen shot 2018-11-21 at 10 55 42 am" src="https://user-images.githubusercontent.com/1078012/48836975-0d51ea80-ed7c-11e8-84bc-1865ea763836.png">

I do get it for other keywords (for ex `abstract`).

**Comment by bwilkerson** [comment]
Yes, I would have expected that to have been on master. I'm seeing the same behavior from the latest analyzer branch, so it appears to be a regression.
