### ISSUE TITLE
Implementation Issue for SuperMixins: CFE / Kernel

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#34165]
**What:** Issue for implementation for CFE/Kernel

**ETA:** 10/15 in Dart Repo. 

**For:** [SuperMixins Implementation]( https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md) and [strawman documentation](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) 

**Meta Issue:** This is subsumed under the [Super Mixins Meta Issue in the Language Repo](https://github.com/dart-lang/language/issues/12)

**Comments:** Feel free to break this further into further tasks and issues, or use as a meta issue for all the tasks in the implementation plan

**Comment by danrubel** [comment]
Parsing, events, parse errors, recovery, and AstBuilder mods are now complete.

**Comment by leafpetersen** [comment]
CL out with tests for mixin inference here: https://dart-review.googlesource.com/c/sdk/+/74017

**Comment by leafpetersen** [comment]
Inference tests have landed.

https://dart-review.googlesource.com/c/sdk/+/74017

mixin_declaration/mixin_declaration_inference_valid_classes_test is failing and in some cases crashing.

**Comment by kmillikin** [comment]
Support for compiling mixins has landed.  The static checks required at mixin applications are not yet implemented.

There are two kinds of checks on the class that the mixin is applied to: (1) that it implements the superclass constraint interfaces and (2) that it provides concrete implementations of the methods that are used in super calls in the mixin.

The first of these is straightforward to implement and can be done soon.  The second of them is of moderate difficulty.

**Comment by leafpetersen** [comment]
Presumably code that doesn't satisfy 2) is already broken, and can only "work" if the code is not exercised?  Based on that, I'd prioritize 1) and consider letting 2) slip if necessary.

**Comment by kmillikin** [comment]
Code that doesn't satisfy (2) that it provides implementations of the required superclass methods is broken.

Checks for (1) that the supertype implements all the constraint interfaces, is implemented in https://dart-review.googlesource.com/c/sdk/+/79206, landing as soon as I verify that it doesn't break dart2js.

**Comment by kmillikin** [comment]
To elaborate on mixins that contain super calls which are applied to classes that don't have implementations of those methods:  either the mixin and the subclasses of the mixin application do not implement the method, in which case it is a compile-time error to instantiate it because the classes are abstract; or else the method is implemented in the mixin or a subclass of the application but it would be a runtime error to evaluate the super call in the mixin.

I also just discovered that the VM allows one to extend a mixin (and `class C extends M` means `class C extends Object with M`).  I will work on statically disallowing that right now.

**Comment by kmillikin** [comment]
CFE now signals an error when a class extends a mixin (implemented [here](https://dart-review.googlesource.com/c/sdk/+/79524)).

**Comment by kmillikin** [comment]
As far as the feature goes: we are missing static checks at mixin applications that the superclass has implementations of the methods that are used in super calls in the mixin declaration.  Unfortunately, I think these have to get on the next release.

We also want to do some internal cleanup soon (e.g., represent mixins directly in Kernel), but that isn't tied to any particular release.

**Comment by dgrove** [comment]
Can this be closed?

**Comment by kmillikin** [comment]
Yes.
