### ISSUE TITLE
Implementation Issue for Super Mixins: DDC

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#34167]
**What:** Issue for implementation for DDC

**ETA:** 10/15 in Dart Repo. 

**For:** [SuperMixins Implementation]( https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md) and [strawman documentation](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) 

**Meta Issue:** This is subsumed under the [Super Mixins Meta Issue in the Language Repo](https://github.com/dart-lang/language/issues/12)

**Comments:** Feel free to break this further into further tasks and issues, or use as a meta issue for all the tasks in the implementation plan

**Note:** This is a P1 for Super Mixins

**Comment by jmesserly** [comment]
testing CL now: https://dart-review.googlesource.com/c/sdk/+/74965 

Kernel support is not implemented yet because we can't tell which classes are these new mixins.

**Comment by leafpetersen** [comment]
I landed inference tests, and I'm seeing some tests that are expected to produce a compile time error and which are passing on the analyzer, failing on ddc.  This seems unexpected so re-opening this for investigation.

```
mixin_declaration/mixin_declaration_inference_invalid_03_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_04_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_05_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_06_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_07_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_08_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_09_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_10_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
```

**Comment by jmesserly** [comment]
I'm going to open a new issue, since this one is about implementing the feature in DDC, which has been landed.

I don't see how inference/MissingCompileTimeError can be a DDC problem (we don't do inference, or produce compile errors, except in rare circumstances), but I'll take a look. It could be something related to Analyzer task model or summaries, both of which DDC uses, and Analyzer tests don't.

**Comment by jmesserly** [comment]
new bug is https://github.com/dart-lang/sdk/issues/34516
