### ISSUE TITLE
invariant_booleans false positive

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34173]
This may be a dupe of #28262, #29431 or #28967 but it looks different to me so I thought it worth raising.

```dart
var hasAnError = false;
void danny() {
  if (hasAnError) {
    return;
  }
  setError();
  if (hasAnError) { // Conditions should not unconditionally evaluate to `true` or to `false`.
    return;
  }
  print('Running');
}

void setError() {
  hasAnError = true;
}
```

I wouldn't expect it to look through all called code to see if the variable is set, but possibly it's a bit too keen to report here.

**Comment by DanTup** [comment]
This one is even simpler:

```dart
void test(int a, int b) {
  if (a < b) {
    print('a < b');
  } else if (b < a) {
    print('b < a');
  }
}
```

The lint fires for the `else if` condition, but it's not unconditionally true or false? Strangely, if I make it `b <= a` (which I think would make it always true, since it's effectively an `else`) the lint disappears.

**Comment by zoechi** [comment]
Also similar https://github.com/dart-lang/linter/issues/592, https://github.com/dart-lang/linter/issues/720

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1384
