### ISSUE TITLE
Analysis Server InterfaceTypeImpl.typeArguments exception

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#34178]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.4203.550`
- `2.0.0-edge.42f295ece52db767c22c902761bbae9d0fcd3dab`
- `IC-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1920x1200`

# Exception

Appended the contents of:
file:///private/var/folders/dg/b5sjdc0150nfdybn23gn8svw003j4w/T/
[report246.txt](https://github.com/dart-lang/sdk/files/2298844/report246.txt)

```
Dart analysis server, SDK version 2.0.0-edge.42f295ece52db767c22c902761bbae9d0fcd3dab, server version 1.20.5, error: Captured exception
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1399:26)
#2      InterfaceTypeImpl.appendTo (package:analyzer/src/dart/element/type.dart:1435:27)
#3      TypeImpl.toString (package:analyzer/src/dart/element/type.dart:2507:5)
#4      _StringBase._interpolateSingle (dart:core/runtime/libstring_patch.dart:801:17)
#5      StringBuffer.write (dart:core/runtime/libstring_buffer_patch.dart:64:24)
#6      _ParameterElementImpl

**Comment by scheglov** [comment]
Same as https://github.com/dart-lang/sdk/issues/33477, which has an example, and can be reproduced.
