### ISSUE TITLE
CFE should not allow type literals which are not compile-time constants in default values of optional parameters

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34175]
The following example compiles just fine with CFE:

```dart
bar<T>([var param = T]) {
  print(T);
  print(param);
}

main() {
  bar<int>();
}
```

It prints
```
int
T
```

The problem is that 'T' is not a compile-time constant and should not be allowed in the default value of optional parameter.

/cc @kmillikin @askeksa-google

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
