### ISSUE TITLE
How to use git to reference a dart library that is not a root directory.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/sdk#34188]
I encountered problems in the process of using pubspec.

I'm using the `json_serializable` library because for some reason I need to customize some of the code to make it self-serving.

Because I'm a direct fork library and `json_serializable` is not the root directory of the github repository, how do I refer to this library in pubspec.

Or do I have to open a single git repository to save json_serializable. 
If this is done, I will be very troublesome when I want to change the PR official branch in the future.

**Comment by zoechi** [comment]
`path: ...` was added to `pub` for Git dependencies a while ago https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by vsmenon** [comment]
Closing as I think you can use `path` as @zoechi suggests.

**Comment by CaiJingLong** [comment]
thanks
