### ISSUE TITLE
dart html build crashing

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#34186]
repro: https://bitbucket.org/unicomp21/radtextures/commits/2e5f62009116afa9349023c8e967d0230e6ba35b

Dart 2.0.0
Linux
Chrome

/usr/lib/dart/bin/pub global run webdev serve web:41039
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 60ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 370ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 857ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.8s

[INFO] Running build...
[INFO] Running build completed, took 829ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 484ms

[INFO] Succeeded after 1.3s with 0 outputs (0 actions)

Serving `web` on http://localhost:41039

require.js:143 Uncaught core.UnsupportedError.new
defaultOnError @ require.js:143
requirejs.onError @ WorkerProc.dart.bootstrap.js:80
onError @ require.js:549
check @ require.js:903
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
enable @ require.js:1176
init @ require.js:788
callGetModule @ require.js:1203
completeLoad @ require.js:1590
onScriptLoad @ require.js:1717
load (async)
req.load @ require.js:1942
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
(anonymous) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
localRequire @ require.js:1449
requirejs @ require.js:1797
(anonymous) @ WorkerProc.dart.bootstrap.js:112
(anonymous) @ WorkerProc.dart.bootstrap.js:156

**Comment by vsmenon** [comment]
You may get a cleaner error by enabling custom formatters (see https://webdev.dartlang.org/guides/debugging).

The `dart:isolate` library is no longer supported on the web.  Right now, that triggers a runtime error (to allow old code that imports it but doesn't use it at runtime):

```
Unsupported operation: dart:isolate is not supported on dart4web
```

**Comment by vsmenon** [comment]
Closing as `dart:isolate` isn't supported.  Should make sure the error around this is clearer though.
