### ISSUE TITLE
literal_only_boolean_expressions has false positives

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34181]
I tried turning on `literal_only_boolean_expressions` in flutter but the only things it flagged were false positives, mostly `while (true)` loops (Dart doesn't have an "infinite loop" construct) and `for` loops where the middle condition is `true` (similar).

**Comment by kevmoo** [comment]
@pq – should this be in the linter package?

**Comment by lrhn** [comment]
(For the `for` loop, omitting the condition is the traditional way to make an infinite loop, not writing `true`).

**Comment by zoechi** [comment]
https://github.com/dart-lang/linter/issues/453

**Comment by pq** [comment]
Absolutely, this is a linter issue with `literal_only_boolean_expressions`.  Closing in favor of tracking in dart-lang/linter#453.
