### ISSUE TITLE
Kernel loader does not set reflectability in the same way parser did

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34194]
For example parser used to hide all private methods of all libraries - which does not happen anymore.

TODO

- [ ] Mark all members of `dart:_internal` non-reflectable. 
- [ ] Mark all private members of `dart:*` non reflectable.

**Comment by rmacnak-google** [comment]
This is probably why mirrors/invocation_fuzz_test is marked RuntimeError, Crash.
