### ISSUE TITLE
It is a compile-time error if actual parameters to const constructor result in invalid constant expressions

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34192]
From `co19_2/Language/Classes/Constructors/Constant_Constructors/invalid_constant_initializer_t02`:
```dart
class A {
  final x;
  const A(var p) : x = p + 42;
}

class IntPair {
  const IntPair(this.x, this.y);
  final int x;
  final int y;
  operator +(v) => new IntPair(x+v, y+v);
}


main() {
  try {
    var a = const A(const IntPair(1,2)); // parameter does not evaluate to int/bool/String, despite implementing the plus operator
  } catch (x) {}
}
```
The spec says (in 10.6.3):
"When invoked from a constant object expression, a constant constructor must throw an exception if any of its actual parameters is a value that would prevent one of the potentially constant expressions within it from being a valid compile-time constant."

Here, *must throw an exception* should be interpreted as *should be treated as if it would have thrown an exception*, i.e. it is a compile-time error.

**Comment by eernstg** [comment]
If [this CL](https://dart-review.googlesource.com/c/sdk/+/70621) is landed, the situation should be less ambiguous.

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.

**Comment by sigmundch** [comment]
(reopened because we temporarily disabled the constant-update-2018 experiment)

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
