### ISSUE TITLE
When class has const constructor, field initializers must be const

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34191]
From ``co19_2/Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t01``:
```dart
class A {}

class C {
  final x = new A();
  const C();
}
```
The spec says (in 10.6.3): "It is a compile-time error if a constant constructor is declared by a class C if any instance variable declared in C is initialized with an expression that is not a constant expression."

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.
