### ISSUE TITLE
Multiple entrypoints not working in hot reload

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34199]

**Comment by mraleph** [comment]
For now we should disable entry points based optimization when hot reload is enabled. 

I am marking this as P0 because it would cause us some issues when trying to roll into Flutter.

**Comment by mraleph** [comment]
See also https://github.com/dart-lang/sdk/issues/34201 which is related.

**Comment by a-siva** [comment]
I agree is this optimization needed when flutter runs in debug mode, I assumed this was an AOT only optimization.

**Comment by mraleph** [comment]
@a-siva it's a different entry point based optimization, this one is for skipping Dart 2 strong mode type checks - the question is do we want Flutter debug to be faster, or do we want to have all type checks enabled there?

**Comment by sjindel-google** [comment]
I think there are no issues with the optimizations landed so far, so I'm bumping it down to P1 since the Flutter roll is not blocked.

**Comment by mraleph** [comment]
I think there is no issue between multiple entry points and hot reload.

**Comment by mraleph** [comment]
Note: there are tests in the status files marked with this issue, e.g.  runtime/tests/vm/dart/entrypoints/tearoff_inline_test.dart

**Comment by mraleph** [comment]
I checked the tests - they are just making strong assumptions about how things would be optimized, which sometimes does not hold in the hot reload testing mode. I don't think there is any reason to do anything here. 

I have marked the tests as SkipByDesign.
