### ISSUE TITLE
Dartdevk doesn't emit full paths for module dependencies

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#34197]
Given a module with a single file with a package import:

```dart
import 'package:path/path.dart';
```

I end up with this module definition:

```js
define(['dart_sdk', 'path.ddc'], function(dart_sdk, path) {
```
(the .ddc part is because we output to `.ddc.js` files, you can pretty much ignore that, this is actually better than what dartdevc does today)

In dartdevc I would have gotten something like this:

```js
define(['dart_sdk', 'packages/path/path'], function(dart_sdk, path) {
```

It appears that dartdevk is only using the basename for the module?

@jmesserly @vsmenon

**Comment by jmesserly** [comment]
The new way to specify import path will be as part of the `--summary` (`-s`) option, like `-s path.sum=js/import/path`, I believe this is now supported. We got a fair bit of feedback that `--module-root` was not ideal (as the location of the summary file does not necessarily correspond with how the modules will be served by the application). That said, I'm in the process of merging `dartdevk` into DDC so I'll likely need to support legacy options (such as module-root) in DDK.

**Comment by jakemac53** [comment]
Ah, ok! I can try updating out ddk logic to provide that. Does that also allow multiple summaries that refer to the same JS module do you know? We have some work internally that might be able to take advantage of that (creating multiple summaries that correspond to a single js module).

**Comment by jmesserly** [comment]
yeah, you should be able to put anything in there, and it will be used as the module import URI. So having a bunch of summaries point at the same JS module file would work.

**Comment by jmesserly** [comment]
this was fixed. yay :)
