### ISSUE TITLE
Stability of mirror system for Dart VM

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/sdk#34198]
Stability consideration for mirror system since Dart 1 mirror system is considered as unstable. There was been another major bump of Dart as Dart 2 was released, were in mirror system is also considered as unstable, before stable release it's been a bit unclear will mirroring be introduced also in Dart 2 or not, now we have it. But can you, please, clarify the state of the mirror system for Dart 2 and what future for it is planning? Mainly I speak here about Dart VM.

**Comment by a-siva** [comment]
You mention that the mirror system was considered unstable in Dart 1, can you elaborate on that with specifics of what is unstable.

In Dart 2 we intended to maintain the same support that we had for dart:mirrors, there could be some issues that we overlooked. Could you elaborate on what you have found.

**Comment by zoechi** [comment]
Mirrors support was marked experimental for dart2js as far as I remember and 
removed entirely in Dart 2 dart2js and Flutter.
Only the server VM supports mirrors in Dart 2.

**Comment by eernstg** [comment]
It might be relevant to know the following: In a setting where 'dart:mirrors' is not supported you can do most of what 'dart:mirrors' will do using code generation with [package reflectable](https://github.com/dart-lang/reflectable).

**Comment by vanesyan** [comment]
@a-siva that was right in the documention of `'dart:mirrors'` package, here is fragment from that comment:
```

**Comment by a-siva** [comment]
At this point we have no plans for enhancing `dart:mirrors `library.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for `dart:mirrors`
