### ISSUE TITLE
strong mode and hot reload

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34201]
Some currently accepted reloads might violate strong mode heap safety guarantees, e.g. 

```dart
class A {
  String a;
  A(this.a);
}

final a = new A("10");

String bar(String b) => a + b;
```

can be reloaded as 

```dart
class A {
  int a;
  A(this.a);
}

final a = new A(10);

int bar(int b) => a + b;
```

after which we have an instance of `A` in the heap which contains `String` in field `a` but should contain an `int`. 

We need to 

- [ ] Classify potential violations of heap safety
- [ ] Cover these violations with tests to illustrate an issue
- [ ] Decide which ones are accepted (because they are common) and which ones should be rejected.
- [ ] Devise strategy for reconciling these violations with strong mode based optimizations (either by disabling optimizations or augmenting them to cope)

/cc @a-siva @rmacnak-google @alexmarkov

**Comment by aam** [comment]
So I understand better - why does having stack frames which refer to old-structured objects violate strong mode?

> after which we have an instance of A in the heap which contains String in field a but should contain an int.

Isn't the premise of hot-reload not to update live objects, but only update class definitions so that only objects created from that point on will have updated structure?

**Comment by mraleph** [comment]
> So I understand better - why does having stack frames which refer to old-structured objects violate strong mode?

Actually just having old stack frames violates strong mode - imagine we do: 

```dart
void foo() {
  bar("10");
  bar("10");
}

void bar(String x) {
  print(x.length);
  debugger();  // *
}
```

and then we reload it while it is paused on `*` at the first invocation with 

```dart
void foo() {
  bar(10);
  bar(10);
}

void bar(int x) {
  print(x + 1);
  debugger();  // *
}
```

and resume then we will end up invoking `bar(...)` with a string - which should never happen in the correctly typed strong mode program. 

>  but only update class definitions so that only objects created from that point on will have updated structure?

Yep, but that means that live objects might become inconsistent with their definitions (e.g. field types don't match actual field values).

The more I think about it the more convinced I am that we are just forced to disable all static strong mode based optimizations when hot reload is possible.

**Comment by aam** [comment]
> Actually just having old stack frames violates strong mode - imagine we do...then we will end up invoking `bar(...)` with a string

Nice example. Somehow I don't see this as a violation of a strong mode. Yes, making such change would result in runtime exception, but that is as expected considering live frame and change in method signature that user requested.

> The more I think about it the more convinced I am that we are just forced to disable all static strong mode based optimizations when hot reload is possible.

Yes, it seems rather hard to identify and rollback (all transitive) optimizations that would be invalidated by given hot reload.
Arguably, though, without those optimization, isn't performance of the "debug"(jit) app is similar to dart 1 checked mode performance(what Flutter used to run in, for example).

**Comment by mraleph** [comment]
> Yes, making such change would result in runtime exception, but that is as expected considering live frame and change in method signature that user requested.

Yes, but well typed static invocations are not expected to cause runtime exceptions in strong mode under normal conditions. (/cc @leafpetersen )

But of course hot reload is not a normal condition. 

> Arguably, though, without those optimization, isn't performance of the "debug"(jit) app is similar to dart 1 checked mode performance(what Flutter used to run in, for example).

Close, but probably worse - because Dart 1 did not reify generic methods meaning that type tests were missing in those places. Also there were no implicit down casts which exist to guarantee static type safety. 

I guess we need to start by adding a flag that turns on to `true` when hot reload is possible and otherwise turned off. 

Then we can go around and disable optimizations that require global well typedness.

We might also need to start benchmarking this mode on golem - like we did with checked mode.

My concern here is that this significantly increases complexity of our optimizations because we know need to account for this very carefully in our mental models of the code.

**Comment by aam** [comment]
>  guess we need to start by adding a flag that turns on to true when hot reload is possible and otherwise turned off.

There is `Isolate::CanReload()` https://github.com/dart-lang/sdk/blob/master/runtime/vm/isolate.cc#L1236

**Comment by aam** [comment]
> Isolate::CanReload() does not actually give us anything useful - it will usually be true even when you are running a batch mode dart2js.

Not sure I follow - you can connect to dart2js running in batch mode via observatory and request hot reload.

**Comment by matanlurey** [comment]
As a developer who _writes_ Dart-VM based tools I am always very surprised to find out my code is running slower/less optimally in order to support either Observatory, Hot Reload, or other debug-only features. I don't know if we need an explicit `dart --debug`, but maybe we do?

**Comment by a-siva** [comment]
This issue has been a P1 since 2018, I feel it should be a P2 as we evaluate further and fix the issues.

**Comment by aam** [comment]
I believe this was largely addressed by @rmacnak-google 
- https://github.com/dart-lang/sdk/commit/a8b3773054c283ac9057522c491a1f9f7a4fe68e#diff-1d5b5a2785a3bb4ca902e997a42a3d93 by adding runtime type checks when needed.
