### ISSUE TITLE
Cannot use "ServiceWorker" from dart:html

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#34202]
I am going to have to continue to rely on a `@JS`-interop based solution for the time being.

-----

I tried to just implement the basic example as seen in [_Service Workers: an Introduction_][1], with Dart 2.0.0 (stable) and DDC (DartDevCompiler) and Dart2JS, and was unsuccessful, though I did use some workarounds where feasible.

* [ ] The [`ServiceWorkerRegistration`][2] object is omitted in [`<ServiceWorkerContainer>.register`][3]:

  ```dart
  import 'dart:html';

  void main() async {
    await window.onLoad.first;
    final result = await window.navigator.serviceWorker.register('sw.dart.js');
    // result is dynamic

    // Workaround:
    final registration = await window.navigator.serviceWorker.getRegistration();
  }
  ```

[1]: https://developers.google.com/web/fundamentals/primers/service-workers/
[2]: https://api.dartlang.org/stable/2.0.0/dart-html/ServiceWorkerRegistration-class.html
[3]: https://api.dartlang.org/stable/2.0.0/dart-html/ServiceWorkerContainer-class.html

* [ ] There is no access to the global `self` object for use within `sw.dart.js`:

  ```js
  self.addEventListener('install', function(event) {
    // Perform install steps
  });
  ```

  ... so I can't do anything without falling back to `@JS()`-based interop (using `window` will fail).

* [ ] `ServiceWorkerGlobalScope` doesn't have useful types on the `.onEventX` events:

  For example, `self.onInstall.listen((e) { ... }`, `e` = `Event`. I expected `InstallEvent`.

* [ ] It's not possible to add an event listener to the `activate` or `install` event (from Dart):

  Here is my current "worker.dart" file (a small shim):
  https://gist.github.com/matanlurey/a4fe2d7a91f7323d6744f256f690a67e

  See https://github.com/dart-lang/sdk/issues/34228.

* [ ] The object returned from `serviceWorker.register` leaks through as a `Promise`, not a `Future`.

  This leads to weird interactions with `package:test` matchers, for example:
  ```dart
  // Throws: Expected Future, got Promise
  expect(serviceWorker.register('a.dart.js'), returnsNormally);
  ```

* [ ] There is no way to check for support of a service worker before using methods

----

[Attached is a minimal example][4] of this not working:

```bash
$ pub upgrade
$ pub run build_runner serve
```

[4]: https://github.com/dart-lang/sdk/files/2304235/try_service_worker.zip

**Comment by kevmoo** [comment]
CC @vsmenon  @terrylucas @dgrove

**Comment by matanlurey** [comment]
I am trying this as a workaround for now:

```dart
/// Adds the `self` field, used for accessing browser APIs from within a worker.
///
/// TODO: Remove once an equivalent API is available directly from `dart:html`.
/// (https://github.com/dart-lang/sdk/issues/34202)
@JS()
library tinypwa.src.js_interop.in_service_worker;

import 'dart:html';

import 'package:js/js.dart';

/// Refers to the `self` property on the global scope within service workers.
@JS()
external ServiceWorkerGlobalScope get self;
```

**Comment by matanlurey** [comment]
Clarification for @vsmenon @terrylucas @kevmoo @dgrove - the `p1-high` label is specifically right now for the `worker.onActivate` event - the inability to use this API is going to become a blocker for any team that tries to use service workers written in Dart (you can still write them in JS, of course).

**Comment by matanlurey** [comment]
I'm going to fork the P1 issue into https://github.com/dart-lang/sdk/issues/34202, since that looks like is more of a low-level platform issue, and it's not directly related to the `ServiceWorker` API as-exposed from `dart:html`.

**Comment by terrylucas** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/74482
