### ISSUE TITLE
Static field access erroneously considered constant

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34205]
From `co19_2/Language/Metadata/compilation_t01.dart`:
```dart
class A {
  static var a = 10;
}

@A.a
class B {}
```
This gives no error in CFE. It should produce an error because A.a is not a constant expression.

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.

**Comment by sigmundch** [comment]
(reopened because we temporarily disabled the constant-update-2018 experiment)

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
