### ISSUE TITLE
we'd like to roll dart_style forward

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34212]
See https://github.com/dart-lang/dart_style/issues/729 for context - the roll will unblock switching the analyzer to using the fasta parser, which itself will unblock Analyzer CFE integration and the new super mixins support.

A CL with the roll is here: https://dart-review.googlesource.com/c/sdk/+/70940. Thanks!

cc @athomas

**Comment by athomas** [comment]
Done.
