### ISSUE TITLE
Remove deprecated profiler library

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34234]
https://github.com/dart-lang/sdk/blob/e434142df0338f9705624e02776e97483ec2b305/sdk/lib/profiler/profiler.dart#L6

This might be safer to remove than the deprecated stuff called out in #34233 since an import to `dart:profiler` is called out as an error by the analyzer with `uri_does_no_exist`. Since we decided only code that passed the analyzer without errors is valid any code using this is already invalid for Dart 2 (even though it does run today in the VM with no errors from the CFE).

**Comment by a-siva** [comment]
The above file appears to have been removed. Closing this issue.
