### ISSUE TITLE
Request to delete package Naviagtor

### ISSUE THREAD

**Issue by ravipatel147** [dart-lang/sdk#34239]
Link : https://pub.dartlang.org/packages/navigate

Package have current version 0.0.5 and before it all version are useless i need to re-publish package can you please remove package from pub

**Comment by mit-mit** [comment]
Confirmed that author of this bug is author of the package's linked github repo.

**Comment by mit-mit** [comment]
Jonas, can you do this, please?

**Comment by sortie** [comment]
I began running the package removal script.

**Comment by ravipatel147** [comment]
Okay please done

**Comment by sortie** [comment]
Done. The package should now be fully removed.
