### ISSUE TITLE
Process.run/runSync attempts to execute paths in the working directory

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34246]
I expect to need to run `./file_name`, or `path/file_name` instead of `file_name` in order to execute a binary with a relative path. This is the behavior that occurs with `runInShell: true` since it's the behavior of `/bin/sh`. However with `runInShell: false` it attempts to execute any file or directory with that name even if it isn't executable. Try creating a directory named `tar` and then use `Process.runSync('tar', ['--version'])`.

**Comment by natebosch** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/3972f738ca4e91104e2d6dad9bb1f36147879e98

**Comment by sortie** [comment]
Also reported as https://github.com/dart-lang/sdk/issues/34246

**Comment by sortie** [comment]
Thanks Nate for pointing out this old issue. Please be sure to let me know if there's any other old issues I should take a look at. So far I've only triaged issues labeled library-io from 2019 or updated in 2019.
