### ISSUE TITLE
Analyzer vs CFE, missing warning in analyzer

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#34248]
Ran across an example where analyzer failed to warn about "This expression has type 'void' and can't be used." where the code was 

```
return await call_to_void_function();
```
The same code when passed through the CFE during kernel generation failed.

Looks like the analyzer is missing a warning in this case.

**Comment by scheglov** [comment]
@MichaelRFairhurst

**Comment by devoncarew** [comment]
@MichaelRFairhurst, can you verify that this is not an issue?

**Comment by MichaelRFairhurst** [comment]
confirmed
