### ISSUE TITLE
[dartdevc] site-webdev examples/ng/doc/quickstart NoSuchMethodError on Edge when using DDC

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#34243]
_From @NecroSean38 on August 22, 2018 12:19_

I tried the quickstart of angular-dart, and got an error on Edge (similar things happened on IE):

> SCRIPT5022: NoSuchMethodError: method not found: 'Unexpected Null Value>' Receiver: null Arguments: []

This error only appears when using DDC, and I am not sure whether it is a bug about DDC or this example.

_Copied from original issue: dart-lang/site-webdev#1798_

**Comment by chalin** [comment]
_From @kwalrath on August 22, 2018 18:14_

My understanding is that DDC is not guaranteed to work with any browser except Chrome, but @vsmenon might be able to tell us more.

**Comment by chalin** [comment]
_From @vsmenon on August 22, 2018 18:20_

For DDC (development): we're not officially supporting any browser except Chrome, but we plan to expand this down the line.

For Dart2JS (production): we do support Edge (https://webdev.dartlang.org/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets)

**Comment by chalin** [comment]
_From @NecroSean38 on August 23, 2018 12:44_

@kwalrath I just clone the code in [https://github.com/angular-examples/quickstart](url), and run it by using `pub global run webdev serve` at local. Here is what I saw in Edge (version: 42.17134.10)

![ddc](https://user-images.githubusercontent.com/16998796/44525851-dafd0680-a714-11e8-9418-27f26f32130d.png)

Things worked well when I changed the builder from DDC to Dart2JS.

**Comment by chalin** [comment]
Quickstart works fine under Chrome. This is likely a ddc issue. I'll move this to the SDK repo.

**Comment by matanlurey** [comment]
FYI: DDC does not _likely_ support Edge yet
(https://webdev.dartlang.org/tools/dartdevc/faq#what-browsers-does-dartdevc-work-with)

**Comment by chalin** [comment]
Ok, then closing this issue. Kathy has updated the docs to make it clear that dartdevc supports Chrome only atm.
