### ISSUE TITLE
Native extensions not build under Windows

### ISSUE THREAD

**Issue by StekolschikovV** [dart-lang/sdk#34242]
Windows environment: Windows 7 x64 with Dart 2.1.0-dev.2.0 , Visual Studio 2008.

When I try to compile a dll file from the [example](https://github.com/dart-lang/sdk/tree/master/samples), errors occur.  I use the [instruction ](https://www.dartlang.org/articles/dart-vm/native-extensions)and try to fulfill all the conditions.

How to fix it?

Video: https://drive.google.com/file/d/1FjSIo-2U4F1JlYjvFQGxCu-jIcvGS4Xw/view

Git: https://github.com/StekolschikovV/sample_extension/tree/master/sample_extension

Errors:
Warning	1	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	795	sample_extension
Error	2	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	795	sample_extension
Warning	3	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	803	sample_extension
Error	4	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	803	sample_extension
Warning	5	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	814	sample_extension
Error	6	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	814	sample_extension
Warning	7	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1021	sample_extension
Error	8	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1021	sample_extension
Warning	9	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1043	sample_extension
Error	10	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1043	sample_extension
Warning	11	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1092	sample_extension
Error	12	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1092	sample_extension
Warning	13	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1253	sample_extension
Error	14	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1253	sample_extension
Warning	15	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1263	sample_extension
Error	16	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1263	sample_extension
Warning	17	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	1304	sample_extension
Error	18	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	1304	sample_extension
Warning	19	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2296	sample_extension
Error	20	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2296	sample_extension
Warning	21	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2310	sample_extension
Error	22	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2310	sample_extension
Warning	23	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2351	sample_extension
Error	24	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2351	sample_extension
Warning	25	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2367	sample_extension
Error	26	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2367	sample_extension
Warning	27	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2392	sample_extension
Error	28	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2392	sample_extension
Warning	29	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2418	sample_extension
Error	30	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2418	sample_extension
Warning	31	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2441	sample_extension
Error	32	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2441	sample_extension
Warning	33	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	2967	sample_extension
Error	34	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	2967	sample_extension
Warning	35	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3001	sample_extension
Error	36	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3001	sample_extension
Warning	37	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3112	sample_extension
Error	38	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3112	sample_extension
Warning	39	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3129	sample_extension
Error	40	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3129	sample_extension
Warning	41	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3144	sample_extension
Error	42	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3144	sample_extension
Warning	43	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3185	sample_extension
Error	44	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3185	sample_extension
Warning	45	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3200	sample_extension
Error	46	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3200	sample_extension
Warning	47	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3218	sample_extension
Error	48	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3218	sample_extension
Warning	49	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3351	sample_extension
Error	50	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3351	sample_extension
Warning	51	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3362	sample_extension
Error	52	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3362	sample_extension
Warning	53	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3410	sample_extension
Error	54	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3410	sample_extension
Warning	55	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3418	sample_extension
Error	56	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3418	sample_extension
Warning	57	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3428	sample_extension
Error	58	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3428	sample_extension
Warning	59	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3447	sample_extension
Error	60	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3447	sample_extension
Warning	61	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3471	sample_extension
Error	62	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3471	sample_extension
Warning	63	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3480	sample_extension
Error	64	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3480	sample_extension
Warning	65	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_api.h	3500	sample_extension
Error	66	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_api.h	3500	sample_extension
Warning	67	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_native_api.h	170	sample_extension
Error	68	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_native_api.h	170	sample_extension
Warning	69	warning C4091: '__declspec(dllexport)' : ignored on left of 'int' when no variable is declared	c:\program files\dart\dart-sdk\include\dart_native_api.h	176	sample_extension
Error	70	error C2143: syntax error : missing ';' before '['	c:\program files\dart\dart-sdk\include\dart_native_api.h	176	sample_extension

**Comment by dgrove** [comment]
I'm not sure if we support a development stack that this is this old - @a-siva will know.

**Comment by ykmnkmi** [comment]
Any updates? Article in site outdated?

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
