### ISSUE TITLE
Dart 2 says getter not found in abstract class, static analysis

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#34247]
It looks like static analysis in Dart 2 doesn't allow getters defined in other classes to be used in the abstract class that's included into the class.

For example, I have a class `Component` which extends from `ComponentDom`. Class `Component` has variable `template`. Saying `this.template` inside `ComponentDom` results in an error:

```
lib/modules/component_dom.dart:7:13:
Error: Getter not found: 'template'.
```
Is this the case now that it's impossible to do in Dart 2?

**Comment by matanlurey** [comment]
Yes, if you have:

```dart
class Base {
  void printTemplate() {
    print(template); // Compile-time error.
  }
}

class Super extends Base {
  String template;
}
```

... `Base` does not know that `template` exists, and cannot access it in Dart 2.

If you want this, you should create an abstract getter in `Base`:

```dart
abstract class Base {
  String get template;
 
  void printTemplate() {
    print(template);
  }
}

class Super extends Base {
  String template;
}
```
