### ISSUE TITLE
analyzer getSignature should provide enough information to support automatic triggering

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34241]
Currently the analysis server's `getSignature` will walk up the AST to the nearest invocation and return the signature information. This means it works even if your arguments are complex expressions. However, if we want to automatically trigger signature help in the editor we need more context. Consider this code:

```dart
return ListTile( // [ position 1 ]
  title: Text("Enable notifications"),
  trailing: Switch(
    value: notificationsEnabled,
    onChanged: (bool enabling){
      if (enabling) { // [ position 2 ]
      }
    },
  ),
);
```

When the user types the `(` at `[ position 1 ]` we would like to display the signature help automatically. However when the user types the `(` on the line marked `[ position 2 ]` we do not want to automatically display signature help. However, if the user *manually* invokes signature help we should still provide (in this case for the `Switch` call).

I think there are a few possible options, for ex.:

1. The editor tells the server whether the request for getSignature is auto-triggered or allowed to climb the tree to find the nearest invocation - (otherwise it would only look at the invocation immediately in front of (behind?) the cursor)

2. The server returns some flag indicating whether automatic display is appropriate for this location (or the distance the invocation is from the supplied offset)

I also think we may wish to never walk up the tree when we're in a comment node?

@bwilkerson Any thoughts on this? I had to disable auto-display of this after I release it because it was kinda annoying in Flutter build methods, but I'd love to get it back.

**Comment by bwilkerson** [comment]
Interesting. The second position is inside a closure. One possibility is that server stops looking as soon as it hits a closure. That would stop the manually displayed help at this location, but it isn't clear to me that that wouldn't be the right thing to do here. How does VS Code deal with similar situations in other languages (such as Java, for example)?

If we really do want to allow manually requested help at position 2, then I'm not sure how best to support it. I have concerns with your first suggestion because it seems to encode behavior that is specific to a single client (that is, I'm not sure it's general enough to support multiple clients). On the other hand, I don't know of any other clients asking for this, so maybe it's not an issue. :-) For the second suggestion, I'm not sure what you mean by "distance". At this point I like the first suggestion best.

**Comment by DanTup** [comment]
> The second position is inside a closure. One possibility is that server stops looking as soon as it hits a closure.

That makes sense - I think we already have some other things we already stop at (though it doesn't help that we want to auto trigger on some `(`'s but not others).

> How does VS Code deal with similar situations in other languages (such as Java, for example)?

I just did some testing in TypeScript and it seems to work "as I would like". In the code:

```ts
dc.stop(() => {
			if (
```

If triggered on the first `(` but not for the `(` of `if`. Looking at the code, I found that they pass along a "trigger reason" (eg. did was it invoked explicitly, or because of a typed character):

https://github.com/Microsoft/TypeScript/blob/937afab4b026c9ed527c8369275c749fc8f2af99/src/services/signatureHelp.ts#L34

If it wasn't triggered explicitly and they're in a comment or string, they bail:

https://github.com/Microsoft/TypeScript/blob/937afab4b026c9ed527c8369275c749fc8f2af99/src/services/signatureHelp.ts#L37

However that doesn't seem to cover the case above, I think that's being handled by `getImmediatelyContainingArgumentOrContextualParameterInfo` and `tryGetParameterInfo` which ultimately ends up here:

https://github.com/Microsoft/TypeScript/blob/937afab4b026c9ed527c8369275c749fc8f2af99/src/services/signatureHelp.ts#L279

Which, looks a bit like ours - looks like it's just some specific AST nodes that walk up to parents/don't.


> For the second suggestion, I'm not sure what you mean by "distance". At this point I like the first suggestion best.

I was thinking by giving the distance (for ex. in AST nodes, from the offset to where the invocation is) the client could make this decision (eg. if the distance is 0, we can display for a triggered character but otherwise only show if manually triggered. Of course, exposing information about the AST would be weird, but I wondered if there was some way of representing it.

In any case, I also think the first option is best, and it seems to be what TypeScript (though strangely I can't find an equivilent in the [LSP spec](https://microsoft.github.io/language-server-protocol/specification) - it supports passing trigger chars from the server to client, but the request for signature help doesn't seem to pass it back to the server to let it make this decision).

At simplest, it could be a boolean for whether it was a manual or automatic trigger, though if we pass the trigger character (which is likely to be one of `(`, `,` or `[`?) it lets the server have a little more control (though we'll need to be sure we've processed the incoming character before this request if we're going to be strict in ensuring it's a `(`, for ex.).

**Comment by bwilkerson** [comment]
The best path forward might be to
1. stop looking up when we hit a closure,
2. re-enable the feature, then
3. add the field to the request to allow us to decide whether to look higher in some cases.

**Comment by DanTup** [comment]
This change stops looking when we hit a closure:

https://dart-review.googlesource.com/c/sdk/+/71481

I don't know if this is enough for us to enable this by-default though. For example, imagine inside a string:

```dart
myFunc("this is a test (probably)");
```

Here, we don't want to automatically pop open the signature help when the user types the second `(`. However, we do want to support them manually invoking signature help here because they might have started typing and then wondered (oh, what was this parameter again?).

If we stop looking when we're inside strings/comments/whatever, it affects the users ability to manually invoke the help explicitly.

**Comment by bwilkerson** [comment]
True. And I wouldn't claim that we're in a good place if users can't explicitly invoke the functionality, but I do think users might be better off if they got the implicit form of the functionality even when they couldn't get the explicit form everywhere they liked. Hence my suggestion that we make the implicit version work well and then, later, figure out how to expand it to support the manual case better.

**Comment by DanTup** [comment]
> I do think users might be better off if they got the implicit form of the functionality even when they couldn't get the explicit form everywhere they liked

I actually thing the opposite. Supporting manual triggering means the user can see it wherever they want, even if they have to press a key to get it. If we do the opposite, we're preventing the user from seeing the help unless they put their cursor in very specific positions and that feels awkward.

One of the reasons I really want to support signature help is to remove the placeholders we previously inserted when you complete function calls (we insert the names for requires args and make them tab stops). There are all sorts of weird quirks with it (such as when you want to pass a function as a callback, it assumes you're calling it and adds parens to the end). This was a workaround for the user not easily being able to get help on the signature. I've tried using it with this turned off (and not having signature help) and it was awful - I had to keep using the mouse to hover the calls to see the info on every call.

This feature has been a (really) long time coming. I'd really like to deliver the full feature if I can and I'm happy to handle future breaking changes with version number checks if we do think it needs changing (I don't think anyone else is likely to use it in the immediate future?). I'm sure we could do something reasonable future-proof though. If we used an enum (not a bool) - eg. with `Manual` and `TriggerCharacter` - we should be able to extend it later (eg. by allowing the actual trigger character to be supplied when the type=TriggerCharacter, or by adding additional types of triggering). For now, the only important thing is knowing when it was automatically-triggered and suppressing walking up the AST.

**Comment by bwilkerson** [comment]
> Supporting manual triggering means the user can see it wherever they want ...

Ok, that's fair.

> If we used an enum (not a bool) - eg. with `Manual` and `TriggerCharacter` ...

Yes, enums are definitely more future proof. My preference, though, would be to use names that describe what server should do, rather than how the user initiated the operation. The distinction, as I understand it, is the scope of the look-up: whether it should look outside closures, comments, etc.

> ... by allowing the actual trigger character to be supplied ...

And that's why :-) Server should never need to know which characters each of the clients use and how to interpret them. That needs to be done on the client side.

**Comment by DanTup** [comment]
> My preference, though, would be to use names that describe what server should do, rather than how the user initiated the operation.

Hmm, I don't know if the editor has enough information to make the decisions though, it seems like this logic is better contained in the server. For ex:

```dart
func((5 + 3 * 2), a);
```

Here, typing the first `(` should show the signature help because the user is invoking a function. The second should not. The editor doesn't have the information to know this (not without having some representation of the code, but we probably don't want that and even if we did it'd probably lag behind and complicate this).

The server has the offset, and knowledge about whether an invocation starts there (or it's an argument separator) and whether showing signature help automatically would be appropriate.

> Server should never need to know which characters each of the clients use and how to interpret them. That needs to be done on the client side.

To avoid this, I think the server would need to return extra information to allow the editor to know whether it's a `(` that invokes or a `,` that separate args (and then the client would need to have some logic that ties those concepts to specific keys)?

**Comment by bwilkerson** [comment]
> Here, typing the first `(` should show the signature help because the user is invoking a function. The second should not.

Then the request is for signature information, and the enum value's name should imply "if at the beginning of an argument". I think the client can make this kind of request anytime the user types a left parenthesis or comma (and maybe a left square bracket) without needing any other context. Server could still figure out that the second `(` doesn't meet that criteria and return a "no information at this location" response.

For the manual invocation, the enum value's name should imply "if anywhere inside any argument list no matter how deeply nested".

What I don't want is for server to need to interpret a client-specific character code to decide what information to return. UI belongs to the client.

**Comment by DanTup** [comment]
> Then the request is for signature information, and the enum value's name should imply "if at the beginning of an argument". 

Ah sorry, I see what you mean. I thought you meant the client should tell the server whether to walk up, but providing it as a condition like that makes sense. "if at the beginning of an argument" I guess also covers the commas a well as the parens :-)

> What I don't want is for server to need to interpret a client-specific character code to decide what information to return. UI belongs to the client.

I guess I was thinking that the specific character may be important, because we would ideally only want to trigger on `(` when it's at the the start of the invocation and only `,` when it's between args (and maybe on `[` when it's an indexer). This might be overkill though, it might work fine just based on the logic above.

Do you think this is a sound enough plan to implement (specific naming aside)?

**Comment by bwilkerson** [comment]
Yes.

**Comment by DanTup** [comment]
@bwilkerson unless this might benefit other editors, I think we can close this - with VS Code moving to LSP, things like triggering will be handled based on its protocol and getSignature won't be used.

**Comment by bwilkerson** [comment]
@jwren Does IntelliJ use, or want to use, this request?

**Comment by jwren** [comment]
IntelliJ does not currently use it.  If I am reading the purpose of the protocol correctly, then the current IJ bracket features, folding and breadcrumb features are sufficient.

Just because IJ isn't a user doesn't mean that we should remove it, some future client could use the protocol.

**Comment by bwilkerson** [comment]
If we didn't have any clients using it I'd probably vote to remove it. But removing it would break any existing VS Code users that haven't updated to the (yet future) version that uses LSP, and that's not something I'm willing to do. (Not to mention any clients that I'm not aware of that might be using it.)

**Comment by bwilkerson** [comment]
Given that the original issue will be resolved when VS Code is switched to LSP, I'm going to close this.
