### ISSUE TITLE
_UnmodifiableMapMixin missing many overrides for mutable operations

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#34256]
I'd expect this to throw, but it doesn't!

```dart
void main() async {
  var map = <dynamic, dynamic>{'1': true, 2: false};
  var wrapper = Map.unmodifiable(map);
  
  print(wrapper.runtimeType);
  print(wrapper);
  wrapper.removeWhere((k, v) => true);
  print(wrapper);
}
```

Only some of the mutable methods are correctly implemented...
- [x] addAll
- [ ] addEntries
- [x] clear
- [x] putIfAbsent
- [x] remove
- [ ] removeWhere
- [ ] update
- [ ] updateAll

https://github.com/dart-lang/sdk/blob/5e4e6037a91538cb369353525d89d391421b2a51/sdk/lib/collection/maps.dart#L271-L299

**Comment by lrhn** [comment]
Good catch. New modifying methods should be handled too.

**Comment by lrhn** [comment]
Fixed.
