### ISSUE TITLE
The front end should treat const/final declarations as not introducing a setter

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34250]
This is the front-end / vm specific subissue for #28267, which has the details.

I have chosen `area-vm` for this issue because that was the area that #28267 had (before I noted that this issue exists with multiple tools, created subissues for each of them, and changed #28267 to `area-meta`), but it is possible that it should be adjusted to `area-front-end`.

**Comment by jensjoha** [comment]
Fixed with 7ea75ab0e002312357bbdcf2c98f3f345ded0fc0.
