### ISSUE TITLE
Extension Methods

### ISSUE THREAD

**Issue by agrapine** [dart-lang/sdk#34257]
I've been programming in Dart for the last 6 months, coming from C#, and loving it... 
But one thing I can't really let go. And it is such a handy tool to keep the code cleaner.

**Extension Methods**

so we can have some of the stuff we want without changing the underlying code

now
`int index=0;
[].map((value)=> {...; index++})`

after
`[].map((value, index)=> ...)`

or immutable sort with iterator, using a comparable
`[].orderBy(x=> x.field)`

...

NB: I know this has been opened before, and there are quite some serious ramifications but I think the end result is worth while

**Comment by zoechi** [comment]
Dup of #9991 (#32280)

**Comment by agrapine** [comment]
worth it 👍
