### ISSUE TITLE
Unexpected output produced by the formatter

### ISSUE THREAD

**Issue by bluemix** [dart-lang/sdk#34265]
### What I was doing

I wanted to format (re-order) my code

### Request

While responding to request: `edit.format`

### Versions

- Flutter SDK 0.5.9-pre.68
- Visual Studio Code 1.26.1
- Dart Code 2.17.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/bluemix/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.17.1
```

### Exception

The formatter produced unexpected output. Input was:
import 'package:altameer_hr/i18n/translations.dart';
import 'package:altameer_hr/redux/app/app_state.dart';
import 'package:altameer_hr/ui/common/info_message_view.dart';
import 'package:altameer_hr/ui/common/loading_view.dart';
import 'package:altameer_hr/ui/new_leave/new_leave_view.dart';
import 'package:altameer_hr/ui/new_leave/new_leave_view_model.dart';
import 'package:altameer_hr/utils/clippers.dart';
import 'package:altameer_hr/utils/gradients.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';

class NewLeavePage extends StatelessWidget {
  const NewLeavePage();

  @override
  Widget build(BuildContext context) {
    return StoreConnector<AppState, NewLeaveViewModel>(
      distinct: true,
      converter: (store) => NewLeaveViewModel.fromStore(store),
      builder: (_, viewModel) => NewLeavePageContent(viewModel),
    );
  }
}

class NewLeavePageContent extends StatelessWidget {
  NewLeavePageContent(this.viewModel);
  final NewLeaveViewModel viewModel;
  BoxDecoration _gradientBack() {
    return  BoxDecoration(
      gradient: hazeGradient,
    );
  }

  _buildBackground() {
    return Stack(
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          decoration: _gradientBack(),
        ),
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Expanded(
              flex: 4,
              child: Center(),
            ),
            Expanded(
                flex: 1,
                child: Stack(
                  fit: StackFit.loose,
                  children: <Widget>[
                    ClipPath(
                      clipper: BottomWaveClipper(),
                      child: new Container(
                        padding: const EdgeInsets.all(20.0),
                        decoration: new BoxDecoration(
                            shape: BoxShape.rectangle,
                            gradient: tameerGradient),
                      ),
                    ),
                  ],
                )),
          ],
        )
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
      @override
    return Stack(
      fit: StackFit.expand,
      children: <Widget>[
        _buildBackground(),
        Scaffold(
      appBar: AppBar(),
      body: new Center(
          child: NewLeaveView(),
        ),
    )
        
      ],
    );
  }
}

Which formatted to:
import 'package:altameer_hr/i18n/translations.dart';
import 'package:altameer_hr/redux/app/app_state.dart';
import 'package:altameer_hr/ui/common/info_message_view.dart';
import 'package:altameer_hr/ui/common/loading_view.dart';
import 'package:altameer_hr/ui/new_leave/new_leave_view.dart';
import 'package:altameer_hr/ui/new_leave/new_leave_view_model.dart';
import 'package:altameer_hr/utils/clippers.dart';
import 'package:altameer_hr/utils/gradients.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';

class NewLeavePage extends StatelessWidget {
  const NewLeavePage();

  @override
  Widget build(BuildContext context) {
    return StoreConnector<AppState, NewLeaveViewModel>(
      distinct: true,
      converter: (store) => NewLeaveViewModel.fromStore(store),
      builder: (_, viewModel) => NewLeavePageContent(viewModel),
    );
  }
}

class NewLeavePageContent extends StatelessWidget {
  NewLeavePageContent(this.viewModel);
  final NewLeaveViewModel viewModel;
  BoxDecoration _gradientBack() {
    return BoxDecoration(
      gradient: hazeGradient,
    );
  }

  _buildBackground() {
    return Stack(
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          decoration: _gradientBack(),
        ),
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Expanded(
              flex: 4,
              child: Center(),
            ),
            Expanded(
                flex: 1,
                child: Stack(
                  fit: StackFit.loose,
                  children: <Widget>[
                    ClipPath(
                      clipper: BottomWaveClipper(),
                      child: new Container(
                        padding: const EdgeInsets.all(20.0),
                        decoration: new BoxDecoration(
                            shape: BoxShape.rectangle,
                            gradient: tameerGradient),
                      ),
                    ),
                  ],
                )),
          ],
        )
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: <Widget>[
        _buildBackground(),
        Scaffold(
          appBar: AppBar(),
          body: new Center(
            child: NewLeaveView(),
          ),
        )
      ],
    );
  }
}

```text
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:146:7)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:119:35)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:340:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:744:45)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:740:50)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:739:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#46     _StreamController._add (dart:async/stream_controller.dart:639:7)
#47     _StreamController.add (dart:async/stream_controller.dart:585:5)
#48     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#49     _rootRunUnary (dart:async/zone.dart:1136:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#55     _StreamController._add (dart:async/stream_controller.dart:639:7)
#56     _StreamController.add (dart:async/stream_controller.dart:585:5)
#57     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/bluemix/flutter-projects/altameer_hr",
        "explicitFileCount": 84,
        "implicitFileCount": 866,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
Apologies that we didn't get a chance to look at this crash before it got stale. Please re-open if you see on a recent version of Flutter or Dart.
