### ISSUE TITLE
FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#34278]
What would cause this I/O exception on attempt to call `Uri.base`?

       {
          "isFatal": false,
          "message": "Analysis failed: /google/src/cloud/yuewa/intellij_client/google3/ads/awapps2/shared/image_picker/common_component/test/media_constraint_tooltip_test.dart",
          "stackTrace": "FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)\n#0      _uriBaseClosure (dart:io/runtime/bindirectory_patch.dart:64:5)\n#1      Uri.base (dart:core/runtime/liburi_patch.dart:21:41)\n#2      current (package:path/path.dart:84:17)\n#3      Context.current (package:path/src/context.dart:62:57)\n#4      Context.toUri (package:path/src/context.dart:1008:43)\n#5      ResourceUriResolver.restoreAbsolute (package:analyzer/src/file_system/file_system.dart:38:29)\n#6      SourceFactoryImpl.restoreUri (package:analyzer/src/context/source.dart:176:26)\n#7      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:810:32)\n#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1206:31)\n\u003casynchronous suspension\u003e\n#9      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:39)\n\u003casynchronous suspension\u003e\n#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)\n\u003casynchronous suspension\u003e\n#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)\n#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:396:29)\n#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)\n#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)\n#15     Driver.start.\u003canonymous closure\u003e (package:analysis_server/src/server/driver.dart:494:21)\n#16     _rootRun (dart:async/zone.dart:1124:13)\n#17     _CustomZone.run (dart:async/zone.dart:1021:19)\n#18     _runZoned (dart:async/zone.dart:1516:10)\n#19     runZoned (dart:async/zone.dart:1463:12)\n#20     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:538:12)\n#21     Driver.start (package:analysis_server/src/server/driver.dart:492:7)\n#22     main (file:///build/work/a4f9bcf0eae1106deda00ff0bddf67d1/google3/third_party/dart_lang/v2_1_0_dev_0_0/pkg/analysis_server/bin/server.dart:62:11)\n#23     _RootZone.runUnary (dart:async/zone.dart:1379:54)\n#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)\n#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)\n#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)\n#27     Future._complete (dart:async/future_impl.dart:476:7)\n#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)\n#29     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)\n#30     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)\n#31     Dropbox.writeRow (package:dart.tools.silo/dropbox.dart)\n#32     _RootZone.runUnary (dart:async/zone.dart:1379:54)\n#33     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)\n#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)\n#35     Future._propagateToListeners (dart:async/future_impl.dart:671:32)\n#36     Future._complete (dart:async/future_impl.dart:476:7)\n#37     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)\n#38     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)\n#39     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)\n#40     _SiloFile.save (package:dart.tools.silo/dropbox.dart)\n#41     _RootZone.runUnary (dart:async/zone.dart:1379:54)\n#42     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)\n#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)\n#44     Future._propagateToListeners (dart:async/future_impl.dart:671:32)\n#45     Future._completeWithValue (dart:async/future_impl.dart:486:5)\n#46     Future._asyncComplete.\u003canonymous closure\u003e (dart:async/future_impl.dart:516:7)\n#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#49     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)\n#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)\n\n",
          "time": "2018-08-27T16:41:02.160Z"
        },

**Comment by bkonyi** [comment]
It looks like either the `Namespace` used internally either has the CWD set incorrectly or a call to `getcwd` is failing and returning NULL. `OS Error: No such file or directory, errno = 2` leads me to believe that something has set the current directory to one which was eventually deleted, which would cause this failure. Do you know which directory you expect to be in at this point? If so, is there any way it could have been deleted?

**Comment by scheglov** [comment]
This is an internal exception, so it is possible that directory disappeared because of repo permissions timed out. It is kind of sad that this happens, and `Uri.base` throws exception, and its clients unknowingly throw exceptions as well. But it is useful to know that it might happen, thank you.
