### ISSUE TITLE
No error on type argument after constructor name with implicit new

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34270]
This program gives no error in the analyzer:
```dart
class Foo<X> {
  Foo.bar();
}

main() {
  Foo.bar<int>();
}
```
See also https://github.com/dart-lang/sdk/issues/34159

**Comment by bwilkerson** [comment]
This also does not produce any errors on the VM, so I believe that it's working as intended. Why did you expect to see an error?

**Comment by askeksa-google** [comment]
`Foo.bar` is a named constructor. Named constructors do not take type arguments, but one is supplied here. The correct syntax for supplying a type argument to the class during instantiation would be `Foo<int>.bar()`.

The VM does not report an error because it generally is missing an error for supplying type arguments where they are not expected: https://github.com/dart-lang/sdk/issues/32972

**Comment by bwilkerson** [comment]
Ah, of course! Too subtle for me after a day of triaging issues. Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/73600
