### ISSUE TITLE
Analysis-server doesn't build on Windows

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34275]
I'm trying to build the SDK on Windows and gets the following error (with out/ReleaseX64 removed first):
```
-- create_sdk
tools\build.py -mrelease -ax64 -j8 create_sdk
gn gen --check in out\ReleaseX64
GN Time: 2.399 seconds
ninja -C out\ReleaseX64 create_sdk
ninja: Entering directory `out\ReleaseX64'
[1703/1733] ACTION //utils/analysis_server:analysis_server(//build/toolchain/win:x64)
FAILED: gen/analysis_server.dart.snapshot
c:/src/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../build/gn_run_binary.py compiled_action dart.exe --deterministic --packages=c:/src/dart/sdk/.packages --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=c:/src/dart/sdk/out/ReleaseX64/gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit c:/src/dart/sdk/pkg/analysis_server/bin/server.dart --train-using=c:/src/dart/sdk/pkg/analyzer_cli --sdk=c:/src/dart/sdk/sdk/
Command failed: ./dart.exe --deterministic --packages=c:/src/dart/sdk/.packages --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=c:/src/dart/sdk/out/ReleaseX64/gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit c:/src/dart/sdk/pkg/analysis_server/bin/server.dart --train-using=c:/src/dart/sdk/pkg/analyzer_cli --sdk=c:/src/dart/sdk/sdk/
output: Analyzing with an empty driver cache:
Analyzing c:/src/dart/sdk/pkg/analyzer_cli...
  error • The return type 'Driver' of the redirected constructor isn't assignable to 'CommandLineStarter' at ..\..\pkg\analyzer_cli\lib\starter.dart:22:34 • (redirect_to_invalid_return_type)
Completed in 25.3s.
```

**Comment by bwilkerson** [comment]
@athomas It appears to be building on the windows bots. In any case, I think this is an infrastructure issue. Could you confirm and change the area if I'm right?

**Comment by athomas** [comment]
@lrhn Did you do a gclient sync before this? Are there any local changes?

**Comment by lrhn** [comment]
No changes in repo, `gclient sync` and `run-hooks` successful, cleaned output directory.

Talked to @johnniwinther and he told me he had experienced the same problem, and he added an "ignore" for the analyzer warning to the `driver.dart` file to get it compiling.

Sequence to reproduce (on Win 10):
> git co master
> del /s /q out
> git pull
> gclient sync
> gclient runhooks
> python tools\build.py -mrelease create_sdk

Only error from runhooks is that it won't download Android tools, as usual.

Then wait ... wait more ... it's a laptop ... yep, problem is still there.
