### ISSUE TITLE
Observatory show blank screen on safari

### ISSUE THREAD

**Issue by xster** [dart-lang/sdk#34293]
Dart VM version: 2.1.0-dev.1.0.flutter-ccb16f7282 (Tue Aug 21 22:21:20 2018 +0000) on "macos_x64"

```
[Error] 
	$0 (main.dart.js:4778)
	a12 (main.dart.js:3262)
	(anonymous function) (main.dart.js:3264)
	$1 (main.dart.js:3488)
	a30 (main.dart.js:1690)
	(anonymous function) (main.dart.js:1699)
```

**Comment by kangwang1988** [comment]
I found some other informations:
![image](https://user-images.githubusercontent.com/817851/50912399-09ce0c00-146d-11e9-908d-e9cf4032b93e.png)

https://stackoverflow.com/questions/27751373/i-have-error-document-registerelement-underfined
```
5

Currently only Chrome and other blink-based browsers support Custom Elements. Firefox supports but not enabled by defualt.

See Can I Use for a full supporting chart.

If you are using it on other browsers, you need to include a Web Components polyfill (usually a file named webcomponents.js).
```

**Comment by kevmoo** [comment]
Observatory has migrated away from custom components.
