### ISSUE TITLE
[DDC/Dart 2.0] Fix behavior of type errors on partial instantiation in DDK.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34296]
It was decided in #31953 that the partial instantiation operator needs to check the bounds of type arguments at the point of partial instantiation, rather than waiting until the resulting closure is called. The VM is currently being updated with the correct behavior, but DDK also has the incorrect behavior. For example, the following test should pass:

```dart
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
//
// This test checks that necessary type argument bounds checks are performed
// eagerly during partial instantiation, rather than being delayed until the
// partially instantiated closure is invoked.

import "package:expect/expect.dart";

class C<T> {
  void foo<S extends T>(S x) {}
}

void main() {
  C<Object> c = C<int>();
  void Function(String) fn;
  Expect.throwsTypeError(() {
    fn = c.foo;
  });
}
```

I've suggested P1 priority for this issue because fixing the semantics here is a breaking change.

**Comment by jmesserly** [comment]
DDC probably has the same behavior with either Analyzer or Kernel backend. If that's true we'd have to fix both.

(regarding priority: I don't think this would be P1 per the guidelines? https://github.com/dart-lang/sdk/wiki/How-the-issue-tracker-works ... as this is not "A single project is unusable or has many test failures". Implicit instantiation is fairly obscure, and the only problem with the current behavior is throwing an exception later than we should. But it seems like something we should fix by the 2.1 milestone for consistency.)

**Comment by sjindel-google** [comment]
Thanks for linking me to that page, I wasn't aware that we had general priority guidelines across teams.

Note that implicit instantiation is not as obscure as it may seem. For example, this external customer hit a performance issue with it in the VM in Dart 2.0: https://github.com/dart-lang/sdk/issues/34090.

**Comment by jmesserly** [comment]
> Note that implicit instantiation is not as obscure as it may seem. For example, this external customer hit a performance issue with it in the VM in Dart 2.0: #34090.

oh, good to know. thank you! :)

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/72545
