### ISSUE TITLE
RegExp matching taking almost forever

### ISSUE THREAD

**Issue by jkleiser** [dart-lang/sdk#34306]
I have come across cases where a call to RegExp.hasMatch(...) takes what seems forever to return. Here is the code:
```
main() async {
  final txt = "maiaktivitetbunadbygdekvinnerdaglig123";
  RegExp rex = new RegExp(r"^([a-zA-Z]+\.?)+$");
  print(rex.hasMatch(txt));
  print("done");
}
```
On my Mac, it actually terminated after 7 minutes 33 seconds with correct 'false'.

If I replace the txt value above with ` "trouble.trouble.trouble.trouble.trouble.123"`, then it terminates after only 37 seconds.

I don't know how this could be improved so that Dart programmers don't run into disturbing experiences like this. It may be a general RegExp problem that is hard to fix.

I'm using
```
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
```
My macOS is version 10.13.6.

**Comment by matanlurey** [comment]
This looks like a limitation in regular expressions, not Dart.

For example try this in JavaScript (in the Chrome console or NodeJs):
```js
var t = "maiaktivitetbunadbygdekvinnerdaglig123";
var r = new RegExp("^([a-zA-Z]+\.?)+$");
t.test(r);
```

This completely locks up my computer. I'm guessing that particular regular expression is going into some sort of bad state and/or loop - I don't know enough about regular expressions to give more feedback though, maybe someone else does.

**Comment by matanlurey** [comment]
Closing since it looks like Lasse helped you out but there isn't anything for us to do on our end.
