### ISSUE TITLE
Builds with --obfuscate should be tested continuously on CI

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#34312]
According to @mraleph builds with the --obfuscate option are not tested continuously on Dart's Waterfall. They should be in order to ensure that they don't break in the future.

Case in point: The currently seem to be broke, see https://github.com/dart-lang/sdk/issues/34311.

/cc @mraleph @mit-mit

**Comment by goderbauer** [comment]
This option is interesting for flutter because it reduces binary/snapshot sizes.

**Comment by mit-mit** [comment]
cc @athomas

**Comment by athomas** [comment]
There's already an issue for this: #32229

I'll close this issue and get to work on the other one.
