### ISSUE TITLE
No error reported when a mixin application implies an invalid override

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34317]
This is the analyzer version of #34235.

Consider the following code:
```dart
class Base {
  void foo() {
    print('Base.foo called');
  }
}
class M1 {
  void foo({x}) {
    print('M1.foo called, with x=$x');
  }
}
class BaseWithM1 = Base with M1;
class M2 {
  void foo() {
    print('M2.foo called');
  }
}
class Derived extends BaseWithM1 with M2 {}
main() {
  new Derived().foo();
}
```

This should result in a compile error, since the mixin application `BaseWithM1 with M2` attempts to override `foo({x})` with `foo()`, and overrides may not drop optional parameters.

The analyzer reports no errors, warnings, nor hints for the above code.

Note that this is not an academic example; it's a reduction of a situation that arose in practice during front_end development.

**Comment by scheglov** [comment]
This was fixed in https://dart-review.googlesource.com/c/sdk/+/76061
