### ISSUE TITLE
test.py can deflake tests by running a list of tests multiple times

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#34310]
When a run of test.py on a builder reveals tests whose results have changed, we want to rerun those tests multiple times each.

We want to pass a list of test names to test.py, and a repeat count, and get the results of those tests in the same format that we get other test results (the new result log).

We want to implement a new test.py flag that will take the filename of a file containing fully specified test names (no wildcard matching) and a flag with a repeat count.
If needed, the multitest tags can be separated from the test file name by a different symbol than /, but we shouldn't have to do that to run them. 

The output results of this will be compared with the existing and previous results of the test, to decide iif this is new flakiness to be reported, or if a stable change in the result of the test has occurred.  I'm not to focused on what the stdout of this run would be, it just needs to produce the result file to be processed by the next stage.

**Comment by whesse** [comment]
This new feature will be needed within a week or two, and is key to our having an initial workflow that goes all the way through by EOQ.  If someone besides me could start implementing it, it would be great - I am working on the result log.

**Comment by whesse** [comment]
I will take care of implementing this, starting tomorrow.

**Comment by sortie** [comment]
This works now.
