### ISSUE TITLE
CFE does not typecheck redirecting factory ctors

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34336]
I looked but did not see an issue for this:

```
abstract class A {                                                           
  factory A(dynamic x) = B;                              
}                                                                                
                                                                                 
class B implements A {                                     
  B(int x);                                        
}
```

This is allowed by the spec, however, if `A(x)` is changed to `double`, there is no error, and at runtime, if you give `A(x)` a non-int, you get no error, and a value of the wrong type makes it through ungated.

```
B(int x) {
  print(x);
}

A(1.0); // prints 1.0
```

This was revealed by default_implementation2_test, but, it actually passes that test because that test needs triage (will file a ticket on that next).

**Comment by MichaelRFairhurst** [comment]
Regarding how that test needs triage: #34337

**Comment by MichaelRFairhurst** [comment]
Luckily, the analyzer is too strict here, which protects users (some) from this unsound runtime behavior: #34338

**Comment by kmillikin** [comment]
I think it's https://github.com/dart-lang/sdk/issues/32988.  Reopen if you don't agree.

**Comment by eernstg** [comment]
Hmmmm .. the spec actually makes it an error for a redirecting factory constructor to have parameter types that aren't subtypes of the corresponding types in the redirectee (cf. https://github.com/dart-lang/sdk/issues/34338#issuecomment-418039211), so the [example](https://github.com/dart-lang/sdk/issues/34336#issue-356114733) should be flagged as an error.

This is also the behavior that I can see with dartanalyzer version 2.1.0-dev.3.0, but there is no error with `dart` (same version), that is, the CFE does not flag it.

The topic of #32988 is the type of the returned instance, not the type annotations of the parameters, so I don't think we can off-load this on that issue.

Hence, I believe it is correct to keep this issue open and labeled `area-front-end`, `type-bug`, so I'll re-open this one.

> .. if `A(x)` is changed to `double`, there is no error

That (assuming that it means 'change `A(dynamic x)` to `A(double x)`) would then also be flagged as a compile-time error, so there should not be a need to revisit its behavior at run time.

**Comment by kmillikin** [comment]
The topic of #32988 is "Missing type check for redirecting factory constructors".  The comment https://github.com/dart-lang/sdk/issues/32988#issuecomment-414950889 is exactly this case.

**Comment by eernstg** [comment]
Ah, right, I trusted the [initial text](https://github.com/dart-lang/sdk/issues/32988#issue-318019473) of the issue to say what it's about, and that's only the type of the returned object.
