### ISSUE TITLE
Dart2js must implement Dart 2.1 integer literal changes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34356]
Dart2js specific issue for #34355.

Dart2js implements `int` instances as values that implement both `int` and `double`. 
It should now be able to accept all integer literals where the value is an exact double

For dart2js this change may actually be a simplification, since it can treat integer literals the same independently of whether they are in an integer or double context, and an integer literal has the same value no matter where it occurs.

**Comment by sigmundch** [comment]
@lrhn - we are trying to identify whether there is anything for us to do in dart2js. It appears that, once the CFE accepts the int value during type-checking, our current semantics already handle this as the new spec indicates. 

Please let us know if we are missing anything or if there are specific language tests that we should ensure are working. If all appears to look good, we can probably mark this issue as closed.

Thanks!

**Comment by sigmundch** [comment]
I just discovered tests under `language_2/double_literals/*`, it appears we depend mainly on the CFE for those. We are passing on the 280 compile-time error tests, but fail on the 2 large positive tests.

I still believe there is no action needed in dart2js, but we are blocked on #34357 to close this issue.

**Comment by vsmenon** [comment]
@kmillikin @sigmundch the blocker is closed.  Can we close this issue?

**Comment by kmillikin** [comment]
I believe so, the co19_2 and feature tests are passing on dart2js.
