### ISSUE TITLE
The dev-compiler must implement the Dart 2.1 integer literal changes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34358]
Dev-compiler specific issue for #34355.

The dev-compiler, like [dart2js](#34356) implements int instances as values that implement both int and double.
It should now be able to accept all integer literals where the value is an exact double

For the dec-compiler this change may actually be a simplification, since it can treat integer literals the same independently of whether they are in an integer or double context, and an integer literal has the same value no matter where it occurs.

**Comment by jmesserly** [comment]
I'll check the specs but I don't think we'll need to do much. In the Kernel tree, it should be like any other DoubleLiteral. DDC still supports the Analyzer AST, so we may need to do something for that, depending on how they've chosen to represent these literals in Analyzer.

**Comment by jmesserly** [comment]
Analyzer backend is blocked on #34360, Kernel backend is blocked on #34357 (DDC may not need any changes for Kernel, though).

**Comment by jmesserly** [comment]
testing CL for DDC+Analyzer: https://dart-review.googlesource.com/c/sdk/+/76343
