### ISSUE TITLE
The VM must implement the Dart 2.1 integer literal changes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34359]
VM specific issue for #34355.

The VM only needs to be prepared for integer literals being used in double contexts, since all tools already supports its 64-bit integer implementation.

Likely the integer literal in a double context can be converted to a double literal by the front-end, and the VM will never notice the change.

**Comment by a-siva** [comment]
Can we use a new scheme for filing issues related to new language features.
If a new language feature is a front-end only change and does not require any implementation specific changes then we file an issue only against the front-end, if it requires an implementation specific change then we create an issue specific to the implementation (vm, dart2js etc.)

In this case for instance it appears that a front end only change would suffice to cover the new feature.

**Comment by lrhn** [comment]
If I was *certain* there wouldn't be any need for the VM to do anything, I wouldn't have filed this issue.
We could decide to wait until we are certain to file an issue.
Since the only ones who can figure out whether a change is needed is the front-end and VM teams in cooperation, I wanted to make sure the issue was visible to the the VM team. If we wait until the front-end work is complete before figuring out what the VM has to do, it can delay completion of the feature.

If you have a different process already in place, I'm fine with following that instead.

**Comment by dgrove** [comment]
@a-siva are you going to close this one or leave it open?

**Comment by a-siva** [comment]
@kmillikin can you confirm that the front-end converts integer literals used in a double context to a double literal. If that is the case I can close this issue.

**Comment by a-siva** [comment]
Closing this as fixed, no work was needed in the VM side.
