### ISSUE TITLE
Allow integer literals in double contexts, and allow all integer constants supported by platform.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34355]
Meta-issue for implementation of the 2.1 language change around integer constants.

In Dart 2.0, integer constants are limited by the values supported by 64-bit integers, even when compiling to platforms (like the web) which supports larger integers. Also, an integer literal in a double context is a compile-time error because integers are not doubles in the type system (`int` is not a sub-type of `double`).

In Dart 2.1, the following changes are made to integer literals:
* An integer literal in a double context is allowed if its numerical value can be represented *exactly* by a double. It is then treated like a double literal with that value.
* An integer literal that is not in a double context is allowed if its numerical value can be represented *exactly* by the target platform's `int` implementation.

The details of these changes have already been incorporated in the language specification in the Dart SDK repository (although "double context" is kept vague since it's the same as the concept used by the Dart 2 type system and type inference, which has not yet been added to the specification).
The language issues https://github.com/dart-lang/language/issues/3 and https://github.com/dart-lang/language/issues/4 can be used as background material.

These changes need to be implemented by the compilers and tools.
- [x] Front-end (#34357)
- [x] dart2js (#34356)
- [x] DDC (#34358)
- [x] VM (#34359)
- [x] analyzer (#34360)

The formatter should be unaffected since this introduces no new expressions, it just allows some type combinations that would previously be rejected by the type checker, and some literals that would previously be rejected by the compilers.

Some tests have landed with 864622a76f9f045c3ee45e7492786b2519d132b9, and more will likely follow. Each platform needs to un-skip the tests when they have an implementation.

**Comment by athomas** [comment]
As of the latest co19 roll today, tests for int-to-double are available as part of the co19_2 suite:
co19_2/LanguageFeatures/int-to-double

**Comment by MichaelRFairhurst** [comment]
Quick comment, the tests shoud probab/y cover the maxValue << 1 case. They do test maxValue + 1, which is likely to fail on platforms because it requires an extraordinarily high number of bits to represent, not necessarily because it would create an extraordinary mantissa.

**Comment by dgrove** [comment]
What else is needed here? all 5 implementation issues are closed. @leafpetersen - thoughts?

**Comment by leafpetersen** [comment]
@kwalrath do we want any documentation work on this?

We should also be sure to advertise the feature (either as part of the 2.1 release or independently).  

Can't think of anything else.

**Comment by natebosch** [comment]
At a minimum it should be in the changelog - I don't think I see an entry.

**Comment by dgrove** [comment]
@lrhn assigning to you for the changelog, and then please close.

**Comment by dgrove** [comment]
https://dart-review.googlesource.com/c/sdk/+/79213 is committed - closing.
