### ISSUE TITLE
Analyzer: does not apply parameters to metadata or instantiate it to bounds

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34367]
```
class C<T> {
  T x;
  const C(this.x);
}

@C(42) // 1
@C<int>(42) // 2
var x;
```

Both cases 1 and 2 fail with "int cannot be assigned to T"

Revealed by text_constructor_generic_named_test

**Comment by srawlins** [comment]
When the `x` field is made final, this is now successful.
