### ISSUE TITLE
DDC gets confused when `Object` has static members.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34387]
This [CL](https://dart-review.googlesource.com/c/sdk/+/73360) adds static members to `Object`.
When building the SDK (`tools/build.py -mrelease -ax64 create_sdk`) I get the following error:
```
Command failed: tools/sdks/dart-sdk/bin/dart --dfe=tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot pkg/dev_compiler/tool/build_pkgs.dart --analyzer-sdk out/ReleaseX64/gen/utils/dartdevc/ddc_sdk.sum --kernel-sdk out/ReleaseX64/gen/utils/dartdevc/kernel/ddc_sdk.dill --output out/ReleaseX64/gen/utils/dartdevc
output: [error] Static members from supertypes must be qualified by the name of the defining type. (package:path/src/path_map.dart, line 9, col 62)
[error] Static members from supertypes must be qualified by the name of the defining type. (package:path/src/path_set.dart, line 9, col 58)

Please fix all errors before compiling (warnings are okay).
```

The `path` package library lines in question are:
```dart
/// A map whose keys are paths, compared using [equals] and [hash].
```
and 
```dart
/// A set containing paths, compared using [equals] and [hash].
```
So, the error is in the unmatched reference in the DartDoc. Those should be [Context.equals] and [Context.hash]. However, that doesn't mean that finding the static `hash` in `Object` is in any way correct, because it is not visible at that point. The reference here is still just undeclared, it is not magically referencing the static `Object.hash`, and it is not OK to make it an error.
(Make it an error to have an undeclared reference, but don't invent references that are not there).

Blocking #11617

**Comment by lrhn** [comment]
Blocking the CL https://dart-review.googlesource.com/c/sdk/+/73360

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/83223
