### ISSUE TITLE
Analyzer does not report cases of 'Can't return a value from a void function'

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#34400]
Testing #f2e6e72, seeing cases where dart2js is failing on 'Can't return a value from a void function', whereas the analyzer does not report the same. These are valid failures, where users have `Future<void>` methods which have a `return` statement.

**Comment by bwilkerson** [comment]
@MichaelRFairhurst I unassigned you because the new norm is to self-assign issues at the point at which you start working on them. You're more than welcome to tackle this :-)

**Comment by leafpetersen** [comment]
There are valid cases for having a return in a `Future<void>` function, and there was a bug (very recently fixed) in the CFE where they were over-reporting.  I suspect that's what you're seeing.  cc @kmillikin

**Comment by keertip** [comment]
Leaf, so are you saying this might be an issue with the cfe?

**Comment by leafpetersen** [comment]
This is an issue with the CFE, should be fixed in bleeding edge as of last night.

**Comment by leafpetersen** [comment]
Closing since I think this is all resolved in bleeding edge.

**Comment by kmillikin** [comment]
This was a front end bug which should have been fixed by 3224afe9fe9f6795046561ccc67e954e6b21c02f.
