### ISSUE TITLE
Allow type parameters on constructors

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34414]
I have a class of type `Foo<T>` which I want to construct using a source of `R` values and a callback that can convert `R`s to `T`s.

```dart
   typedef T Converter<R, T>(R value);
   class Foo<T> {
     factory Foo.convert<R>(Bar<R> source, Converter<R, T> converter) {
       // ...
     }
   }
```

This fails with `Error: Constructors can't have type parameters`.

**Comment by Hixie** [comment]
(Using a static method instead fails with https://github.com/dart-lang/sdk/issues/34415.)

**Comment by eernstg** [comment]
This has been in the pipeline for a while, it just didn't make it into Dart 2. We have https://github.com/dart-lang/sdk/issues/26391 which is used to discuss (and push for) that feature, so I'll close this one as a duplicate thereof.
