### ISSUE TITLE
StreamController.close docs don't describe the significance of the returned Future

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#34425]
the docs [here](https://api.dartlang.org/stable/2.0.0/dart-async/StreamController/close.html) say that `close` returns a `Future` (tangent: not sure why it's a `Future` instead of `Future<void>`), but don't say when it's supposed to complete.  that makes it hard to determine how to write tests that involve `close`.  should you `await` it?  what do you expect to happen after `await`ing it?  what *doesn't* happen before you `await` it?

**Comment by natebosch** [comment]
Docs where expanded in https://dart-review.googlesource.com/c/sdk/+/302101
