### ISSUE TITLE
Make gen_snapshot use CFE and let it run in Dart 2.0 mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#34423]
The change in  cd3dded had the side-effect of flipping the --strong/--sync-async/--reify-generic-functions on for `gen_snapshot`. Though `gen_snapshot` doesn't seem to support running in Dart 2.0 mode and doesn't seem to use CFE.

This broke our head-head-head flutter integration buildbot.

@aam @mraleph

**Comment by a-siva** [comment]
This has been fixed, gen_snapshot now runs in Dart 2.0 mode, it inputs a '.dill' file and generates the snapshot.
