### ISSUE TITLE
Add a quick fix for unawaited futures in an async context

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#34431]
... i.e. a fix for [`unawaited_futures`](https://dart-lang.github.io/linter/lints/unawaited_futures.html).

I'd suggest the following 2 quick fixes to be available:

1. (Preferred) Insert `await`
2. (Optional) Import `package:pendatic` (if required), and wrap in `unawaited(<expression>)`.

/cc @davidmorgan @bwilkerson @srawlins

**Comment by asashour** [comment]
This can be closed, both fixes are now available.
