### ISSUE TITLE
An overriding method can't specify a different default value

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#34437]
The failing co19_2 tests appear to be due to missing constant evaluation or error checking after constant evaluation should be performed. I don't think that this should occur in the fasta parser or in AstBuilder, but if so, feel free to assign it to me and I'll fix.

tests/co19_2/co19_2-analyzer.status:
- [ ] Language/Classes/Abstract_Instance_Members/override_default_value_t01
- [ ] Language/Classes/Abstract_Instance_Members/override_default_value_t02
- [ ] Language/Classes/Abstract_Instance_Members/override_default_value_t03
- [ ] Language/Classes/Abstract_Instance_Members/override_default_value_t04
- [ ] Language/Classes/Abstract_Instance_Members/override_default_value_t05
- [ ] /Language/Classes/Instance_Methods/override_different_default_values_t01
- [ ] /Language/Classes/Instance_Methods/override_different_default_values_t02

**Comment by bwilkerson** [comment]
@leafpetersen Are the tests above valid? (I'm guessing the answer is "yes", but would appreciate the confirmation anyway.)

**Comment by danrubel** [comment]
Apparently, this error checking was part of ErrorVerifier and removed in [Remove spec mode support from ErrorVerifier](https://dart-review.googlesource.com/c/sdk/+/65643/2/pkg/analyzer/lib/src/generated/error_verifier.dart#b2146). Thanks to @bwilkerson for tracking this down.

**Comment by leafpetersen** [comment]
Yes, they look right to me.

cc @lrhn

**Comment by lrhn** [comment]
I agree that the test should give compile-time errors with the current specification.
> It is a compile-time error if an instance method $m_1$ overrides an instance member $m_2$, the signature of $m_2$ explicitly specifies a default value for a formal parameter $p$, and the signature of $m_1$ implies a different default value for $p$.

**Comment by bwilkerson** [comment]
Thanks!

Just to clarify, the error reporting wasn't removed in that CL. The code that referenced the error code was removed, but the removed wasn't being run when strong mode was enabled. The removed code indicates that this error was being generated elsewhere, but I have not been able to find where that was suppose to be happening (it wasn't using this error code).

What I can tell you is that these tests were marked as failing when the co19_2 tests were created on Feb 1, 2018 (https://dart-review.googlesource.com/37743). I suspect that this error was accidentally disabled at some point during the development of strong mode. In any case, it's been broken for at least 7 months.

**Comment by natebosch** [comment]
CFE also does not report these as errors, it will be breaking to change this to an error.

**Comment by lrhn** [comment]
If no compiler implements the restriction, and it'll be a compile-time error to re-introduce it, we may want to consider just dropping the restriction.

It's not required for soundness, and it means that a subclass can't just drop the default value and use `param ??= defaultValue;` in code instead, even if that actually handles explicit `null` arguments better.
Or a sub-class can't use a more specialized default value (say `const ColorPoint(0, 0, Color.black)` instead of `cons Point(0, 0)`).

**Comment by leafpetersen** [comment]
We discussed this today in the language meeting.  We will demote this to a warning for the time being, and consider changing it to an error (breaking change) in the future.  So the resolution of this bug is to add this back in as a warning.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/91170

**Comment by stereotype441** [comment]
I'm reverting 6699384dddfac8da9e4a2edfca2f6445d412358a because of failures in Flutter (https://dart-review.googlesource.com/c/sdk/+/91360).  Let's discuss with @leafpetersen today.

**Comment by leafpetersen** [comment]
cc @tvolkert @Hixie 

This is currently a warning, and so users are free to ignore it.  I'd suggest that we send a PR to flutter globally suppressing this warning, they are then free to re-enable it and fix up their code if they want the warning, and continue to ignore it if not.

**Comment by Hixie** [comment]
It would be much easier to determine whether the new warnings are valid or false positives if the error message told you what the superclass' and subclass' defaults are.

**Comment by scheglov** [comment]
Sometimes. Sometimes it will not, because the value is an `int`, and what you really want is to reference a constant by name.

**Comment by scheglov** [comment]
@tvolkert @Hixie If these problems are warnings, will they still break Flutter?

I have a [PR](https://github.com/flutter/flutter/pull/27197) for Flutter, but it changes default values to make them the same as inherited, but different than they were. This might be a reason that build fails.

**Comment by tvolkert** [comment]
Yes, Flutter will still break if they're warnings.
