### ISSUE TITLE
The method 'isSubtypeOf' was called on null.

### ISSUE THREAD

**Issue by boostmerlin** [dart-lang/sdk#34445]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\lenov0\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 4831, method: edit.isPostfixCompletionApplicable, params: {file: E:\workspace\flutter\takebackmytime\lib\models\app_state.dart, offset: 85, key: .assert}, clientRequestTime: 1536723377446}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by bwilkerson** [comment]
It's a little hard to tell because the stack traces don't match the current code base, but I believe this was fixed in https://dart-review.googlesource.com/71620. Please let us know if you continue to see this after moving to a more recent build.
