### ISSUE TITLE
Incorrect decimal value represented as 0x43F0000000000000.

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#34449]
The document "Feature: Evaluating integer literals as double values" that describes a feature of the support in Dart 2 for evaluating integer literals occurring in a context where the expected type is double to a value of type double contains:

> Consequently, double d = 18446744073709551614; has no error and it will initialize d to have the double value represented as 0x43F0000000000000. But int i = 18446744073709551614; is a compile-time error because 18446744073709551614 is too large to be represented as a 64 bit 2's complement number, and double d = 18446744073709551615; is a compile-time error because it cannot be represented exactly using the IEEE 754 double-precision format.Thank you for taking the time to file an issue!

However, the exact value witch is represented as 0x43F0000000000000 is 18446744073709551616 (not a value 18446744073709551614 mentioned in the document).

**Comment by lrhn** [comment]
Thanks, good catch.
