### ISSUE TITLE
Dev-compiler assumes `&` , `|` and `^` only exists on `int`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34450]
I am adding non-short-circuit boolean operators to the `bool` class.
In doing so, I find DDC generating incorrect code, where the `a & b` is compiled into something similar in JavaScript, followed by `>>0`. This looks like an assumption that if the operations was allowed on a native object, then it must be an integer operation, without actually checking that it was an integer operation.

See: https://dart-review.googlesource.com/c/sdk/+/25240 and the error in:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8937943941959450128/+/steps/ddc_tests/0/stdout

If compiling the code:
```dart
main(List<String> args) {                                                           
 bool b = args.isEmpty;
 print(b | b);
}
```
the resulting JS code contains:
```javascript
   core.print((dart.notNull(b) | dart.notNull(b)) >>> 0);
```
where it should instead call the interceptor for `bool.operator|`.

**Comment by jmesserly** [comment]
thanks! Not sure if you got my message when you were working on your CL, but I already made a CL to fix this (https://dart-review.googlesource.com/c/sdk/+/71228). Anyways I'm happy to verify it works and land it :)

**Comment by jmesserly** [comment]
Verified that my fix works with your patch. I will see if I can submit it on its own to unblock you. Otherwise you could mark DDC failing and I'll fix it in my CL.

**Comment by lrhn** [comment]
Your change looks good, so I'll hold for it (less status file juggling is always better). Thanks!
