### ISSUE TITLE
View not refreshing (No change detection)

### ISSUE THREAD

**Issue by chstrong** [dart-lang/sdk#34454]
* Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
* MacOS X 10.13.6
* Chrome

I want to notify a parent component from a child component to update a view in the parent component, after saving an entry. I'm using the @Output annotation to parse back an event.

In the parent component the function "loadPosts()" is actually invoked, but the view is not updated. Not even with ChangeDetectorRef.

What happens:

place_component contains a "list-post" directive, which displays all posts.
place_component contains a modal, to add a new post with a directive "new-post"
When a new post is saved, a message is parsed back over @output to the "new-post" directive in the modal: (doneIt)="loadPosts()"
The loadPosts() function is executed, but the "list-post" directive does not reload.

See following Stackoverflow for details:
https://stackoverflow.com/questions/52295624/how-to-notify-parent-component-of-change-and-refresh-view

**Comment by matanlurey** [comment]
This should be reported to AngularDart not the SDK.

**Comment by chstrong** [comment]
Apologies
