### ISSUE TITLE
exception from the analysis server when typing in code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34465]
From @rtolar and https://github.com/flutter/flutter-intellij/issues/2611#issuecomment-421446264:

The problem is reproducible.
I created a skeleton app to reproduce:
https://github.com/rtolar/flutter_intellij_2611

Basically:

add dependency to http in pubspec.yaml: http: ^0.11.3+17
add import in main.dart import 'package:http/http.dart' as http;
start typing var client = http.C
I only get the error the first time I type that.
Restart Android Studio to get it to happen again.

**Comment by devoncarew** [comment]
cc @scheglov as we have a clear repro for this

**Comment by scheglov** [comment]
I was no able to reproduce this.

**Comment by rtolar** [comment]
Apparently so.
I upgraded from the 'beta' channel to the 'dev' channel, and was not able to reproduce the problem.

e.g. using:

C:\Users\rtola\dev\flutter>flutter --version
Flutter 0.8.4 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 7f7a731da0 (12 hours ago) • 2018-09-14 13:11:32 -0400
Engine • revision 7a9b430d74
Tools • Dart 2.1.0-dev.4.0.flutter-c28db2d6e1

**Comment by bwilkerson** [comment]
Thanks for confirming!
