### ISSUE TITLE
HttpClient drops requests silently

### ISSUE THREAD

**Issue by microdog** [dart-lang/sdk#34477]
While using `http` package in our Flutter app, we find that HTTP requests may be dropped silently when `[HttpClient.maxConnectionsPerHost]` is set and network connections are disabled. After enabling network connections, requests are still being dropped.

After tracing into the library, we find that this might be a bug in the Dart SDK. The number of connecting connections are counted incorrectly in `_ConnectionTarget`:

https://github.com/dart-lang/sdk/blob/bb56d4592f/sdk/lib/_http/http_impl.dart#L1940

`_connecting` is increased before `connectionTask.then()`, and the error of `connectionTask` is not handled. I think `_connecting` should be decreased when `connectionTask` completed with error.

The related issue in `http` package(including reproducing steps and demo): https://github.com/dart-lang/http/issues/176#issuecomment-421542357

Flutter Version:

```
Flutter 0.8.5-pre.5 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1ad538e454 (30 hours ago) • 2018-09-14 16:47:28 -0700
Engine • revision 24d94601b9
Tools • Dart 2.1.0-dev.4.0.flutter-bb56d4592f
```

**Comment by cskau-g** [comment]
Thanks for filing this here. I think the SDK is the right place for this issue.
Since I'm on https://github.com/dart-lang/http/issues/176, let me take this one here.

**Comment by mkustermann** [comment]
Is this still an issue? If so, @sortie Can you take a look at this?

**Comment by microdog** [comment]
@mkustermann Yes, it can be reproduced by the following program.

```dart
import 'dart:io';

void request(client, id, url) async {
  try {
    HttpClientResponse resp =
        await client.getUrl(Uri.parse(url)).then((request) => request.close());
    print('#${id}\t${url} -> StatusCode: ${resp.statusCode}');
  } catch (e) {
    print('#${id}\t${url} -> Error: ${e}');
  }
}

void main() async {
  HttpClient client = new HttpClient();

  client.maxConnectionsPerHost = 1;
  //client.maxConnectionsPerHost = null;

  int id = 0;
  request(client, id++, 'http://mydomainismissing');
  request(client, id++, 'http://mydomainismissing');
  request(client, id++, 'http://mydomainismissing');
}
```

3 results are expected, but only 1 will be returned.

```shellsession
$ dart main.dart
#0      http://mydomainismissing -> Error: SocketException: Failed host lookup: 'mydomainismissing' (OS Error: nodename nor servname provided, or not known, errno = 8)
$ dart --version
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "macos_x64"
```

**Comment by sortie** [comment]
@ZichangG, looks like @microdog diagnosed the issue in the original post, can you take a look?
