### ISSUE TITLE
Support for Arm Platforms

### ISSUE THREAD

**Issue by lamarrr** [dart-lang/sdk#34478]
No support for Raspberry PI and other ARM platforms, I feel this is crucial

**Comment by julemand101** [comment]
Can you please elaborate what you mean by "No support"? If you go to the following page:
https://www.dartlang.org/tools/sdk/archive

You can select Linux and download Dart for both "ARMv7" and "ARMv8 (ARM64)". In fact, I am already running Dart on a Beaglebone Black board and it runs (not that fast with Dart 2.0 but it runs (see #34172 which is even about running Dart on Raspberry Pi)).
