### ISSUE TITLE
Type promotion could be even better if it analyzed more of the control flow

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34483]
This code runs fine (and is provably correct), but the analyzer complains `error • The argument type 'dynamic' can't be assigned to the parameter type 'String' • test.dart:8:7 • argument_type_not_assignable`:

```dart
void bar(String value) {
  print(value.runtimeType);
}

void foo(dynamic value) {
  if (value is! String)
    value = value.toString();
  bar(value);
}

void main() {
  foo(0);
}
```

**Comment by eernstg** [comment]
Type promotion has been discussed in many issues; I tried to summarize the discussion by adding a list of relevant issues (including this one) to #25565.

**Comment by srawlins** [comment]
I think this is being followed up on at https://github.com/dart-lang/language/issues/80 and https://github.com/dart-lang/language/issues/81

**Comment by leafpetersen** [comment]
This works now.
