### ISSUE TITLE
CFE fails to infer method types from interfaces implemented via mixin

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34488]
Consider the following program:
```dart
abstract class Base {
  void f(int i);
}

abstract class Mixin implements Base {}

class Derived extends Object with Mixin {
  f(i) {}
}
```

According to my understanding of type inference (and the behavior of the analyzer), `Derived.f` should have type `(int) -> void` (inherited from `Base` via `Mixin`).  But the common front end treats it as though it has type `(dynamic) -> dynamic`.

**Comment by stereotype441** [comment]
Test cases here: https://dart-review.googlesource.com/c/sdk/+/75131

**Comment by kmillikin** [comment]
Thanks for the report.  Proposed fix is here: https://dart-review.googlesource.com/c/sdk/+/75441 but it will need a fix to an issue in JS interop that was hidden by the CFE bug.

**Comment by peter-ahe-google** [comment]
I think I may have a fix for this in the Fasta class hierarchy builder.

**Comment by stefantsov** [comment]
I believe this issue is fixed now after [CL 100580](https://dart-review.googlesource.com/c/sdk/+/100580) was landed.
