### ISSUE TITLE
Kernel needs to have test coverage for getStaticType 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34496]
We have been trying to use `getStaticType` and we discover cases where it breaks severely because either some transformation violated the strong mode or because `getStaticType` does not take care of some language corner case (e.g. the most recent discovery was that it does not support callable classes).

We would like to have an access to `getStaticType` that is tested.

Additionally we would like to have a way of running a verification pass after the Kernel generation that verifies that AST is strongly typed.

**Comment by kmillikin** [comment]
I agree.  We can do better here.

**Comment by mraleph** [comment]
I think Johnni is actually landing some tests for this so I will tentatively assign this issue to him.

**Comment by johnniwinther** [comment]
Verification of .getStaticType (that it doesn't crash) added in https://github.com/dart-lang/sdk/commit/970c164826d67fc2cd29ff596e5a103e9ee05ff2

**Comment by johnniwinther** [comment]
With https://dart-review.googlesource.com/c/sdk/+/110724 testing of the .getStaticType value is in place.

I'm closing this issue as the further work needed is only in improving the coverage of the tests when necessary.
