### ISSUE TITLE
CFE fails to report error for import prefix hidden by class member (when used to name a type)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34498]
Consider the following code:
```dart
import 'dart:core';
import 'dart:core' as core;

class A {
  core.List get core => null; // (1)
}
```

Based on my reading of the spec, there should be a compile-time error at (1), because the declaration of the getter `core` inside of class A hides the import prefix declared at top level.  So the type `core.List` should be invalid.

But the front end accepts this code without complaint, and considers the return type of the getter to be the type `List` from `dart:core`.

Note that the analyzer's handling of this case isn't correct either; it also accepts the code without complaint, but it consideres the return type of the getter to be `dynamic`.

**Comment by lrhn** [comment]
This should be a compile-time error. The lexical scope for the declarations of `A` is the class scope of `A`.

**Comment by stereotype441** [comment]
Test case here: https://dart-review.googlesource.com/c/sdk/+/75280

**Comment by peter-ahe-google** [comment]
Work in progress: https://dart-review.googlesource.com/c/sdk/+/79047
