### ISSUE TITLE
Analyzer fails to report error for import prefix hidden by class member (when used to name a type)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34500]
Consider the following code:
```dart
import 'dart:core';
import 'dart:core' as core;

class A {
  core.List get core => null; // (1)
}
```
Based on my reading of the spec, there should be a compile-time error at (1), because the declaration of the getter `core` inside of class A hides the import prefix declared at top level. So the type `core.List` should be invalid.

Oddly, the analyzer accepts this code without complaint, but it considers the return type of the getter to be the type `dynamic`.

Note that the front end's handling of this case isn't correct either--see #34498.

**Comment by lrhn** [comment]
This should indeed be a compile-time error.

**Comment by stereotype441** [comment]
Test case here: https://dart-review.googlesource.com/c/sdk/+/75280

**Comment by stereotype441** [comment]
Note: a similar issue is #33005 (in that case, a type parameter fails to shadow the library prefix; in this one, a getter fails to shadow the library prefix).

**Comment by srawlins** [comment]
Analyzer now reports:

> error • The prefix 'core' can't be used here because it is shadowed by a local declaration. • a.dart:5:3 • prefix_shadowed_by_local_declaration
