### ISSUE TITLE
dartanalyzer: error reporting for anonymous sync generator in class

### ISSUE THREAD

**Issue by riczhao** [dart-lang/sdk#34504]
```
$ cat t.dart 
class c {
  var s = {
    'f': () sync*{
      yield 1;
    }
  };
}
main() {
  for (var v in c().s['f']())
    print(v);
}

$ dartanalyzer t.dart 
Analyzing t.dart...
  error • The function expression type '() → Iterable<FutureOr<Null>>' isn't of type '() → Null'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s) at t.dart:3:10 • strong_mode_invalid_cast_function_expr
  error • The literal '1' with type 'int' isn't of expected type 'FutureOr<Null>' at t.dart:4:13 • strong_mode_invalid_cast_literal
  error • The type 'Iterable<int>' implied by the 'yield' expression must be assignable to 'Iterable<FutureOr<Null>>' at t.dart:4:13 • yield_of_invalid_type
  error • The type 'Null' used in the 'for' loop must implement Iterable at t.dart:9:17 • for_in_of_invalid_type
  hint • The type of the function literal can't be inferred because the literal has a block as its body at t.dart:3:10 • strong_mode_top_level_function_literal_block
4 errors and 1 hint found.

$ dart t.dart 
1

```
It can run correctly, but dart analyzer reported errors.

Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
Dart VM version: 2.1.0-dev.4.0 (Fri Sep 7 16:44:38 2018 +0200) on "macos_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
macOS 
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by lrhn** [comment]
I have no idea where the `FutureOr<Null>` comes from, it looks completely spurious.
If I change `sync*` to `async*`, the error starts mentioning `Stream<FutureOr<Null>>` instead, so it's a general issue.

The static type of `() sync* { yield 1; }` should be `Iterable<dynamic> Function()`, so `c.s` should have type `Map<String, Iterable<dynamic> Function()>` (statically if we infer it, or static type `dynamic` and that type at run-time).

**Comment by riczhao** [comment]
I wonder why I can’t specify the return type explicitly rather not let analyzer guess.

**Comment by srawlins** [comment]
The analyzer still reports one hint:

> hint • The type of the function literal can't be inferred because the literal has a block as its body. • a.dart:3:10 • top_level_function_literal_block

**Comment by srawlins** [comment]
Which I think is covered by https://github.com/dart-lang/sdk/issues/34503.
