### ISSUE TITLE
Analyzer top level type inference doesn't support block closures

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34503]
(We have known we needed to fix this for a long time, but I can't find a specific issue for it, so I'm filing one now)
The analyzer does not correctly infer the types of fields and variables outside of method bodies when their initializers contain block-bodied closures.

For example:
```dart
var x = [1, 2, 3].map((x) { return x.toString(); }).toList();
```
Type inference should infer a type of `List<String>` for `x`.  But the analyzer infers a type of `List<Null>`.

**Comment by eernstg** [comment]
Another case is described in #37422.

**Comment by srawlins** [comment]
The example code no longer errors, and if I change the type of `x` be `List<int>` I get an error:

```dart
List<int> x = [1, 2, 3].map((x) { return x.toString(); }).toList();
```

> A value of type 'List&lt;String>' can't be assigned to a variable of type 'List&lt;int>'.
