### ISSUE TITLE
Analyzer: no error when constant constructor redirects to non-constant

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34509]
Consider the following program:
```dart
class A {
  final int i;
  const A(): this._(1);
  A._(this.i);
}
```
With `dartanalyzer` version 0.2.1-dev.4.0 this yields 'No issues', but it is a compile-time error for a constant constructor to redirect to a non-constant constructor (section 'Redirecting Generative Constructors'):
```
When $\ConstMetavar$ is \CONST{},
it is a compile-time error if the redirectee is not a constant constructor.
```
As an aside, the vm says 'A constant constructor can't call a non-constant constructor', so I believe that there is no need to create an area-meta issue for several tools.

**Comment by srawlins** [comment]
An error is now reported:

> error • Constant redirecting constructor can't redirect to a non-constant constructor. • 34509.dart:3:19 • redirect_to_non_const_constructor
