### ISSUE TITLE
Unexpected type error during the Future<List<int>> variable assigning.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34505]
Dart SDK Version: 2.1.0-dev.4.0
OS: Windows 10 (64 bit)

Probably this is a duplicate of #34482, however I prefer to create a separate bug here: it's casting to `Future<FutureOr>` there and to raw `Future` here. Please let me know if I should treat such similar cases as duplicates of each others

Here is a sample code:
```
import "dart:async";
main() {
  Future<List<int>> f1 = new Future(() => [0, 1]);
  Future ff = new Future(() => [0, 1]);
  Future<List<int>> f2 = ff;
}
```
Analyzer does not produce compile errors here.

Dart passes on the line 3 and throws type exception on the line 5:

> Unhandled exception:
> type 'Future<dynamic>' is not a subtype of type 'Future<List<int>>'
> #0      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/Future/test.dart:5:21)
> #1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
> #2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Seems like in both cases above `Future` object gets assigned to [Future<List<int>>] variable, so it's expected that the result should be the same (it should not be errors here).

**Comment by lrhn** [comment]
This error seems correct. After type inference, your program is:
```dart
import "dart:async";
main() {
  Future<List<int>> f1 = new Future<List<int>>(() =><int> [0, 1]);
  Future<dynamic> ff = new Future<dynamic>(() => <int>[0, 1]);
  Future<List<int>> f2 = ff;
}
```
and the assignment of a `Future<dynamic>` (value of `ff`) to a variable with type `Future<List<int>>` (`f2`) is a correct run-time error.

When we have a situation like `dynamic x = [1, 2];` where the context type doesn't constrain the type parameter of the expression, we use upwards inference to find the list type, so we infer `dynamic x = <int>[1, 2];` here.

**Comment by iarkh** [comment]
You are correct, I believe bugs should be closed.
