### ISSUE TITLE
Some mixin tests are missing compile errors when run in DDC

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#34516]
from @leafpetersen:

> I landed inference tests, and I'm seeing some tests that are expected to produce a compile time error and which are passing on the analyzer, failing on ddc.  This seems unexpected so re-opening this for investigation.

```
mixin_declaration/mixin_declaration_inference_invalid_03_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_04_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_05_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_06_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_07_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_08_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_09_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
mixin_declaration/mixin_declaration_inference_invalid_10_test: MissingCompileTimeError   # https://github.com/dart-lang/sdk/issues/34167
```

**Comment by jmesserly** [comment]
This is almost certainly Analyzer side (DDC does not produce errors) but I'll take a look. Could be task model or summary related.

**Comment by jmesserly** [comment]
conflicting interfaces are not reported because DDC is on the task model.

Error verifier has this:
```

  /// Setting this flag to `true` disables the check for conflicting generics.
  /// This is used when running with the old task model to work around
  /// dartbug.com/32421.
  ///
  /// TODO(paulberry): remove this flag once dartbug.com/32421 is properly
  /// fixed.
  final bool disableConflictingGenericsCheck;
```
Which references this issue:
https://github.com/dart-lang/sdk/issues/32421

Which @stereotype441 and @leafpetersen talked about in these comments:
https://github.com/dart-lang/sdk/issues/32421#issuecomment-370886163

It sounds like we are OK with DDC missing the conflicting interface errors until DDC switches to Kernel.

I believe the right resolution is to close this, as it is not related to mixins per se, but to the existing decision around conflicting interface errors in Analyzer. Let me know if that has changed, or if I misunderstood anything about that discussion.

(FYI -- I am rapidly making progress on removing the DDC's Analyzer backend, and also in parallel, I have a local change that switches DDC over to Analysis Driver. But my current focus is on DDC's Kernel backend.)

**Comment by leafpetersen** [comment]
SGTM, thanks for taking a look.
