### ISSUE TITLE
js-interop: Cannot read property 'Name' of undefined / ES6 / webpack / babel

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#34510]
**Describe the issue you're seeing**
Repo with all files: https://github.com/MikeMitterer/template-js-web
`npm install && npm run dev` to build everything. 

I have a very simple JS6-Class transpiled with webpack and bable
https://github.com/MikeMitterer/template-js-web/blob/master/src/main/webapp/assets/js/log/logger.js

WebPack generates something like this:
```js
...
__webpack_require__.d(__webpack_exports__, "Name", function() { return Name; });
...
var _log_logger__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./log/logger */ "./src/main/webapp/assets/js/log/logger.js");
var n1 = new _log_logger__WEBPACK_IMPORTED_MODULE_2__["Name"]("Gerda", "Riedmann");
...
```
I can't figure out what's the right setting the `@JS(...)` annotation???

**Does it happen in Dartium??? or when compiled to JavaScript?**
Chrome

* Dart SDK version: *use `dart --version`*
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"

* pkg/js version: *look at `pubspec.lock`*
js 0.6.1+1

Failing code:
```dart
@JS('_log_logger__WEBPACK_IMPORTED_MODULE_2__')
library main.js;

import 'dart:html';
import 'package:js/js.dart';

@JS()
class Name {
    external Name(final String firstname, final String lastname);

    external String get lastname;
}

void main() {
    final name = new Name("Mike","Mitterer");

    querySelector('#output').text = 'Your Dart app is running. ${name.lastname}';
}
}
```
Simple "Name" class
[logger.js.zip](https://github.com/dart-lang/sdk/files/2392399/logger.js.zip)
Bundled main.js
[main.js.zip](https://github.com/dart-lang/sdk/files/2392401/main.js.zip)

**Comment by matanlurey** [comment]
ES6 modules are currently not supported (I don't believe `_log_logger__WEBPACK_IMPORTED_MODULE_2__` is in the global namespace). You'll need to add it to the global namespace (i.e. `window.name = Name` or similar).

**Comment by MikeMitterer** [comment]
The import is not ES6. The original code is ES6 but transpiled with Bable.
