### ISSUE TITLE
CFE issues incorrect error with redirecting generic factory constructor

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34528]
The code below passes the analyzer with no errors (I believe correctly).  The CFE (somewhere between #4134b95 and #2e3f17f) has started issuing an error (I believe incorrectly).

```dart
class Foo<T> {}

class Bar<T extends Foo<T>> {
  Bar._();
  factory Bar()= _Bar<T>._;
}

class _Bar<T extends Foo<T>> extends Bar<T> {
  _Bar._() : super._();
}

void main() {

}
```

```
file:///Users/leafp/tmp/ddctest.dart:10:18: Error: The type variable 'T' has bound '#lib1::Foo<#lib1::Bar::•::T>' but the context expects a type variable with bound '#lib1::Foo<#lib1::_Bar::T>'.
Try redirecting to a different constructor.
  factory Bar()= _Bar<T>._;
```

This is breaking the bleeding edge google roll.  cc @keertip @kmillikin @stefantsov

**Comment by kmillikin** [comment]
It was introduced here: https://github.com/dart-lang/sdk/commit/de984e58cbe29a13c078e20ee992f006ad33c891

/cc @dhil

**Comment by dhil** [comment]
By substituting on the bounds, Fasta now accepts your program. I will give my proposed fix a spin in the CQ. Moreover, I'll add your example to the test suite.
