### ISSUE TITLE
Wrong type of generic

### ISSUE THREAD

**Issue by Devtronic** [dart-lang/sdk#34526]
Hello, 

I don't know if this behaviour is expected, but if I using generic types, the method is not recognizing which type was passed.

I need to reflect the passed type using the `reflectClass(T)` function to read out the properties of the passed type. (`name` and `age` in this example)

```dart
import 'dart:mirrors';

class TestObj {

  String name;

  int age;

  TestObj() {

  }
}

void main() {
  testType<TestObj>(TestObj, TestObj);
}

void testType<T>(Type T2, Type T3){
  print(T == T2);       // False
  print(T2 == T3);      // True

  print(T == TestObj);  // False
  print(T2 == TestObj); // True
  print(T3 == TestObj); // True

  // (VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
  print(reflectClass(T2).newInstance(const Symbol(''), []).type.declarations.values);

  // (VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
  print(reflectClass(T3).newInstance(const Symbol(''), []).type.declarations.values);

  // Exception
  print(reflectClass(T).newInstance(const Symbol(''), []).type.declarations.values);
}
```

**Output**
```
false
true
false
true
true
(VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
(VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
Unhandled exception:
Invalid argument(s): dynamic
#0      _Mirrors.makeLocalClassMirror (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:1447)
#1      _Mirrors.reflectClass (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:1460)
#2      reflectClass (dart:mirrors-patch/dart:mirrors/mirrors_patch.dart:49)
#3      testType (file:///D:/GitHub/mapper/test.dart:33:9)
#4      main (file:///D:/GitHub/mapper/test.dart:16:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Is this a bug? And if not how can I do it correctly? :-) 

* Dart VM version: 2.1.0-dev.0.0.flutter-be6309690f
* Windows

**Comment by lrhn** [comment]
That `print(T == T2);` prints false proves there is a problem. 
Both `T` and `T2` should evaluate to `Type` objects representing the type `TestObj`, and type objects representing the same type should be equal.

My guess is that you are somehow not getting the correct type bound to `T`, and it is, for some reason, bound to `dynamic` instead of `TestObj`. That's what to expect if the program was run on Dart 1, since generic methods were only included in Dart 2.

So yes, a bug somewhere.

**Comment by mraleph** [comment]
Note that this is not reproducible for me on Linux. I am getting:

```
╭─vegorov@volhv ~/src/dart/sdk ‹experimental-for-aart›
╰─$ ~/src/flutter/flutter/bin/cache/dart-sdk/bin/dart /tmp/test.dart
TestObj
true
true
true
true
true
(VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
(VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
(VariableMirror on 'name', VariableMirror on 'age', MethodMirror on 'TestObj')
```

@Devtronic how do you run this code?

**Comment by Devtronic** [comment]
Ok, shame on me... I see, that there is a second dart executable installed on my computer. IntelliJ was running the test file with `Dart VM version: 2.0.0-dev.58.0.flutter-f981f09760`. `dart --version` in cmd outputs `Dart VM version: 2.1.0-dev.0.0.flutter-be6309690f`. I can't reproduce this problem with version 2.1.0 .

Thanks @mraleph 👍
