### ISSUE TITLE
what is equivalent of java socket.setSoLinger(true,0) in Dart Socket

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#34520]
In web app I use javacasi to create a socket as;

socket = new Socket(host,portNo);
socket.setSoLinger(true,0);
Now I am trying to do same in my flutter mobile app. My question is, what is equivalent of java socket.setSoLinger(true,0) in Flutter Dart Socket?

Using Dart socket I create an example in https://stackoverflow.com/questions/52425195/how-to-use-rawsocket-in-dart?noredirect=1#comment91801891_52425195

The error is server related because I cannot be able to set some socket option like so_linger.

What is the actual implementation of SO_LINGER in the Dart platform?

**Comment by sortie** [comment]
Dart does not implement SO_LINGER at this time. Socket options are set with the class Socket setOption method. However, it only receives a bool, which doesn't handle options like SO_LINGER that has two integer parameters (l_onoff and l_linger). The Windows socket code does set SO_LINGER by default to l_onoff = 1 and l_linger = 10 and there's no way to override that, while the other operating systems do not set it at all.

**Comment by NTMS2017** [comment]
thanks for the info.
