### ISSUE TITLE
Analyzer does not check that implicit bounds are correct in "extends" clauses

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34532]
In the following example, `extends Bar` is interpreted via instantiate to bounds as `extends Bar<Foo>`.  It is illegal for a super bounded type to appear in that position:

```dart
class Foo<T> {}

class Bar<T extends Foo<T>> {}

class Baz extends Bar {} // Should be error here, because Bar completes to Bar<Foo>

void main() {
}
```

This applies to types used in the "implements", "with", and "on" clauses as well (the last is missing from the spec text, I will file an issue).

```
\LMHash{}
It is a compile-time error if a parameterized type $T$ is super-bounded
when it is used in any of the following ways:
\begin{itemize}
\item $T$ is an immediate subterm of a new expression
  (\ref{new})
  or a constant object expression
  (\ref{const}).
\item $T$ is an immediate subterm of a redirecting factory constructor
  signature
 (\ref{redirectingFactoryConstructors}).
\item $T$ is an immediate subterm of an \EXTENDS{} clause
  (\ref{superclasses}),
  or it occurs as an element in the type list of an \IMPLEMENTS{} clause
  (\ref{superinterfaces}),
  or a \WITH{} clause
  (\ref{classes}).
\end{itemize}
```

cc @stereotype441 @devoncarew @scheglov @eernstg 

I think this is an important one to fix for Dart 2.1 - this violates very basic soundness properties of the type system.

**Comment by stereotype441** [comment]
I'm looking at this now.

**Comment by stereotype441** [comment]
Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/76280

**Comment by stereotype441** [comment]
The above CL is no good.  It causes the analyzer to require all mentions of a type to be regular-bounded; we need the analyzer to permit super-bounded types in many circumstances.  I'll work on a better fix.

**Comment by stereotype441** [comment]
Better fix is out for review: https://dart-review.googlesource.com/c/sdk/+/76280
