### ISSUE TITLE
assert not working on mac os x

### ISSUE THREAD

**Issue by bhrugumehta** [dart-lang/sdk#34535]
I have created simple program in mac os x. Just set variable without any assignment and then check assert ( exist != null) but this statement fails, no any assertion.

Dart version:

Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"

Thanks

**Comment by dhil** [comment]
Have you tried enabling the option `--enable-asserts`, i.e. `dart --enable-asserts <dart-script-file.dart>`?

**Comment by bhrugumehta** [comment]
@dhil 
Thanks.
I did not try with that option by enabling. Thanks.
After I enable it's work, getting assertion.
I think I will have to more dig in to the dart configuration option.
