### ISSUE TITLE
Submitting an error that happened here 

### ISSUE THREAD

**Issue by samueldeschamps** [dart-lang/sdk#34549]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/dn/03v200394t988xgfn82gxxzh0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 10457, method: edit.isPostfixCompletionApplicable, params: {file: /Users/samuel/StudioProjects/barber_app/lib/telaEfetivarReserva.dart, offset: 5884, key: !}, clientRequestTime: 1537540362193}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by bwilkerson** [comment]
I believe that this has been fixed in the bleeding edge. Please let us know if you see it again after updating to the next dev or stable release.

**Comment by samueldeschamps** [comment]
OK, thanks!
I only reported because Android Studio plugin suggested me to do so, but
this wasn't a real problem to me.

Best regards,
Samuel Deschamps.


Em sáb, 22 de set de 2018 às 01:27, Brian Wilkerson <
notifications@github.com> escreveu:
