### ISSUE TITLE
when reporting for host for flutter_tools, we should report for 'CLI' host

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34543]
We report the host for flutter_tools runs - this is used to know which IDE is driving flutter_tools; we key off the value of the `FLUTTER_HOST` environment variable. It would be nice to also report a 'host' for pure CLI usage. We could infer this by there being no value set for `FLUTTER_HOST`, and for the entrypoint command into the tool not being the `daemon` command (or, `flutter run --machine`).

We should also update the docs for building tools on flutter_tools to specify that IDEs - and people driving flutter_tools - should specify an `FLUTTER_HOST` env variable.

cc @mit-mit

**Comment by vsmenon** [comment]
@devoncarew - is this an ask on the VM?

**Comment by devoncarew** [comment]
No, just a change to flutter_tools.

**Comment by vsmenon** [comment]
Shouldn't that be filed on the flutter repo then?

**Comment by devoncarew** [comment]
oops! I'd meant to.
