### ISSUE TITLE
Export functionality used in Flutter Engine to public headers

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#34547]
Currently, Flutter engine is using the following private Dart headers:

```c
#include "third_party/dart/runtime/bin/crypto.h"
#include "third_party/dart/runtime/bin/io_natives.h"
#include "third_party/dart/runtime/bin/embedded_dart_io.h"
```

Please migrate the functionality used by https://github.com/flutter/engine/blob/master/lib/io/dart_io.cc and by https://github.com/flutter/engine/blob/master/lib/ui/dart_runtime_hooks.cc to common Dart headers so these can be converted to third_party/dart/runtime/include/ paths.

This prevents Flutter engine from being compiled in Google.

**Comment by mehmetf** [comment]
@zanderso @mraleph FYI

**Comment by zanderso** [comment]
@a-siva This is the header file issue we discussed.

@mehmetf @keertip would it work for you if we captured the needed API in a public header under `runtime/bin/include` ?

**Comment by mehmetf** [comment]
Hm, I will leave the final answer up to @keertip however the way we recommend these headers be used now is:

```c
#include <dartapi.h>
```

which implies there's a collision possibility if we start including files from different dirs.

**Comment by a-siva** [comment]
You mean 'include <dart_api.h> ?

This include file should probably be called something else, maybe 'dart_embedder_api.h'

**Comment by chinmaygarde** [comment]
What is the utility of `dart_embedder_api.h` over `dart_api.h`? Are they same?

**Comment by mehmetf** [comment]
I just wanted to highlight that this is blocking an active project. It would be great to get a timeline on this fix. Is it something doable in the next week or so?

**Comment by a-siva** [comment]
Ben is slated to start work on this, we are in the process of scoping the work and will update with a timeline here.

**Comment by bkonyi** [comment]
This change landed last week in [this CL](https://dart-review.googlesource.com/c/sdk/+/77014).
