### ISSUE TITLE
Analyzer: Inferred type of variable should be taken from initializing expression

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34558]
Consider the following program:

```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;
class A<X extends num> {}

A sourceTop;
var fsourceTop = toF(sourceTop);

main() => print(sourceTop);
```
Storing the above in `n030.dart`, dartanalyzer version 2.1.0-dev.5.0 gives the following response:
```
  error • A value of type '<Y extends A<num>>() → void' can't be assigned to a variable of type '<Y extends dynamic>() → void' at n030.dart:6:18 • invalid_assignment
```

The message reveals that we are attempting to assign a value whose static type is a function type (so it can't be the actual argument being assigned to the formal parameter of `toF`, it can only be the value of `toF(sourceTop)` being assigned to `fsourceTop`), and that fails.

But this means that `toF` receives the inferred actual type argument `A<num>` (as it should), and hence the static type of `toF(sourceTop)` is `void Function<Y extends A<num>>()`, but, somehow, the variable `fsourceTop` has been given the inferred type annotation `void Function<Y extends dynamic>()`.

For an instance variable we could infer the type annotation from declarations in superinterfaces, but this is a library variable and hence there is no such information available.

So I would expect the inferred type of such a `var` variable to be the same as the static type of the initializing expression. If that is the case then we would never get an error because of a type mismatch.

I've labeled this as a bug because I assume that we would never want to infer the type annotation for a library variable as any other type than the static type of the initializing expression.

**Comment by stereotype441** [comment]
I'm looking into this now.

**Comment by stereotype441** [comment]
Whoops, it looks like github erroneously auto-closed this issue.  Still working on it.

**Comment by stereotype441** [comment]
Unassigning myself because I’m not actively working on this issue right now.

**Comment by srawlins** [comment]
When I make the above program null-safe (and hopefully do not change the nature of the program...), neither the CFE nor the analyzer find any problems:

```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => <Y extends X>() {};
class A<X extends num> {}

A sourceTop = A();
var fsourceTop = toF(sourceTop);

main() => print(sourceTop);
```
