### ISSUE TITLE
Front end: Assignability check should reject unrelated types

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34559]
Consider the following program:

```dart
typedef F<X> = void Function<Y extends X>();

F<num> x;
F<int> y = x; //# 01: compile-time error
F<dynamic> z = x; //# 02: compile-time error

main() { 
  y; //# 01: continued
  z; //# 02: continued
}
```

With `dart` and `dart2js` version 2.1.0-dev.5.0 I get no compile-time errors from the above program, but there is no assignability relation between `F<S>` and `F<T>` for distinct `S` and `T`, also not in the case where `S <: T` or `T <: S`: the types `F<S>` and `F<T>` are simply unrelated when `S` and `T` differ.

I assume that this should be handled by the common front end, hence the label.

**Comment by dhil** [comment]
I would expect this issue to have been resolved by @stefantsov's [recent patch to a similar issue](https://github.com/dart-lang/sdk/issues/34623). Indeed with Dart `version: 2.1.0-edge.4c67897123b3b8b574d8f62ab2df2823e1af45d7 (Tue Oct 16 11:46:39 2018 +0200) on "linux_x64"` I now get the following errors
```
bug.dart:4:12: Error: A value of type '<Y extends dart.core::num = dynamic>() → void' can't be assigned to a variable of type '<Y extends dart.core::int = dynamic>() → void'.
Try changing the type of the left hand side, or casting the right hand side to '<Y extends dart.core::int = dynamic>() → void'.
F<int> y = x; //# 01: compile-time error
           ^
bug.dart:5:16: Error: A value of type '<Y extends dart.core::num = dynamic>() → void' can't be assigned to a variable of type '<Y extends dynamic = dynamic>() → void'.
Try changing the type of the left hand side, or casting the right hand side to '<Y extends dynamic = dynamic>() → void'.
F<dynamic> z = x; //# 02: compile-time error
```
I suppose these are the errors you expected. Thus, I suppose we can close this issue.
