### ISSUE TITLE
Dart 2.0.0 lets you get dependencies for a package with an invalid Dart 2.0 environment setting

### ISSUE THREAD

**Issue by C-Alexander** [dart-lang/sdk#34557]
SDK Version:
2.0 stable,  2.1 Dev

Tested using Windows

Depending in Dart 2 on a package without an sdk environment upper constraint will get you the error 
```
The current Dart SDK version is 2.1.0-dev.0.0.

Because test1 depends on library1 from path which requires SDK version <2.0.0, version solving failed.
```
This is intended as documented here: https://www.dartlang.org/dart-2

However, in library1 itself, which lacks any specification as to sdk version, you can get dependencies, upgrade dependencies, run, without so much as a warning.

Due this behavior, pub.dartlang.org only reports a warning (as it doesn't fail to solve versions). 

Proposed solutions: 

Either A:
- Warn on pub commands that an upper constraint must be given for the sdk version, for it to be a valid dart2 package. 
- Mark it as incompatible with dart2, potentially by taking https://github.com/dart-lang/pana/blob/master/lib/src/pubspec.dart and making "shouldWarnDart2Constraint" return a true if there is no constraint. (or better yet, creating a new warning just for that)

or B: 
- Error it out on upgrade dependencies, with the standard version solving failed, forcing packages to adhere, with clear documentation on what to add *in* the error to make the situation clear to newbs, including a link to the https://www.dartlang.org/dart-2 page and perhaps also to the https://www.dartlang.org/tools/pub/versioning page

or C: 
- Make getting versions accept lax constraints again 

~ The current situation is IMO unclear when looking for packages, resulting in packages like https://pub.dartlang.org/packages/flutter_color_picker#-analysis-tab- having 100 healthscore yet not actually working with any dart 2 project. Additionally it can lead to vague situations where people expect a package they made for themselves to just work since there's no warnings, and then it doesn't, despite it not being immediately clear why it would require a version beneath dart 2.0. 

Sorry for the long issue.

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/pub#1986
