### ISSUE TITLE
Provide analyzer lint to prevent old-style mixins

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34568]
As part of migrating to the new `mixin` syntax we should make sure that old-style mixins do not creep back in. Having a lint that checks for old-style mixins would be very useful.

An additional benefit is that it could assist with the migration by surfacing old usages. Currently, one has to locate all the `with` keywords and manually check that the provided mixin list does not contain anything declared with the `class` keyword.

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by bwilkerson** [comment]
The lint is named `prefer_mixin`. If you're using an IDE, there is also a quick-assist available at the name of the class in the class declaration to convert classes to mixins (assuming there are no constructors). Happy to extend the quick-assist if you run into other cases where it could help but doesn't currently.

**Comment by yjbanov** [comment]
Great! Thank you! I'll give it a shot and report back if I see any issues.
