### ISSUE TITLE
`mixin` with `on` clause does not resolve grand-ancestor methods

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34565]
### What I was doing

```dart
class A {
  String bar() => 'baz';
}

class B extends A {
}

mixin UnhappyMixin on B {
  String baz() => bar();
//                ^
//                "The method 'bar' isn't defined for the class 'UnhappyMixin'."
}
```

### Versions

- Flutter SDK 0.4.3-pre.1162
- Visual Studio Code 1.27.1
- Dart Code 2.18.0

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by scheglov** [comment]
This is another instance of https://github.com/dart-lang/sdk/issues/34564.
This works now.
![image](https://user-images.githubusercontent.com/384794/45988878-f4ec7a80-c02d-11e8-8eb4-f1ebea520c0f.png)

**Comment by yjbanov** [comment]
Nice! I had a suspicion but wasn't sure.
