### ISSUE TITLE
`mixin` should be able to `extend` another `mixin`

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34567]
This issue affects both the **analyzer** _and_ the **VM**.

### What I was doing

Attempted to have one `mixin` extend another. I get the following bouquet of analysis errors.

```dart
mixin A {}
mixin B extends A {}
//      ^
//      "Variables must be declared using the keywords 'const', 'final', 'var' or a type name."
//      "Document all public members."
//      "Expected an identifier."
//      "A class or mixin definition must have a body, even if it is empty."
//      "Prefer typing uninitialized variables and fields."
//      "Expected to find ';'."
//      "Missing variable type for 'extends'."
```

Flutter uses this capability to allow one mixin automatically bring another mixin into the mix ([example](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/animation/listener_helpers.dart#L21)).

One possible workaround is to have the user mix in all the mixins necessary. However, this is not possible when some of the mixins are private, like in the aforementioned example.

### Versions

- Flutter SDK 0.4.3-pre.1162
- Visual Studio Code 1.27.1
- Dart Code 2.18.0

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by bwilkerson** [comment]
I'm fairly certain that extending mixins is _not_ supported in the proposal (which I think is here: https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md).

**Comment by yjbanov** [comment]
I don't think we want to extend mixins. We only use the `extends` keyword because there is no alternative. What we're looking for is that one mixin can automatically bring other mixins with it, some of which may be private. Let's pretend `includes` keyword exists just for that:

```dart
// mixins.dart
mixin M2 { }
mixin M1 includes M2 { }

// a.dart
class A extends Object with M1 { }
```

We could desugar the above into the following:

```dart
// mixins.dart
mixin M2 { }
mixin M1 on M2 { }

// a.dart
class A extends Object with M1, M2 { }
```

The only extra capability the former syntax has is that `M2` can be _private_. This is because the application of `M1` does not mention `M2` by name. There would not be any other semantic difference between the former and the latter examples.

Having said that, in the `listener_helpers.dart` case `_ListenerMixin` can easily become an interface (thanks @vsmenon for the idea!). If I do not find any other instances of mixins extending other mixins I'll close the issue.

**Comment by yjbanov** [comment]
Ok, [here's another similar case](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L57). Here, a mixin is using `extends/with` but seem to be looking for the same effect:

```dart
abstract class RenderProxyBoxMixin<T extends RenderBox> extends RenderBox with RenderObjectWithChildMixin<T>
```

I was able to use the following workaround:

```dart
mixin RenderProxyBoxMixin<T extends RenderBox> on RenderBox, RenderObjectWithChildMixin<T>
```

This is because all usages of `RenderProxyBoxMixin` already apply `RenderObjectWithChildMixin`, so they work with this different declaration. But it is technically a breaking change.

Perhaps we could allow the `with` keyword in the mixin declaration to mean what I described in https://github.com/dart-lang/sdk/issues/34567#issuecomment-424141408?

**Comment by lrhn** [comment]
Using `on` is not a work-around, it's how mixin declarations are intended to be used.

We are reserving the `extends` and `with` keywords for mixin declarations in case we want to declare composite mixins later, what you are describing with "includes". 

That feature doesn't currently exist - even with the current supermixins flag.
The reason existing super-classes that `RenderProxyBoxMixin<T>` is applied to all implement `RenderObjectWithChildMixin` is that they *must*.
Mixing in `RenderProxyBoxMixin` only mixes in the members of that declaration, not the ones from its super-class. Such behavior was never intended in the Dart 1 specification, and to the best of my knowledge, it wasn't implemented that way either.

This *is* working as intended.

**Comment by yjbanov** [comment]
Sounds good. I'll keep an eye on it, but I think `on` will be sufficient.

**Comment by feinstein** [comment]
If I understand this correctly, there's no way to extend a mixin like:

```dart
mixin A with B {
  void methodFromA() {
    methodFromB();
  }
}
```

`on` will not do the trick as what I want is:

```dart
class C with A {
...
}
```

and using `on B` instead of `with B` will force me to do:

```dart
class C extends B with A {
...
}
```

Which is a lot more complicated to declare.

Could this be reopened so `mixins` could extend other `mixin` using `with`?

**Comment by leafpetersen** [comment]
I believe that this feature request is already tracked [here](https://github.com/dart-lang/language/issues/540).

**Comment by feinstein** [comment]
Thanks!

**Comment by SergeyShustikov** [comment]
If you need to extend the mixin, which contains only abstract methods, you can use `implements` instead of `extends`

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class TestProvider extends ChangeNotifier {}

mixin AnotherMixin<T extends ChangeNotifier> on StatelessWidget {
  T activateController();
}
mixin Controller implements AnotherMixin {
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) {
        return activateController();
      },
      child: buildWidget(context),
    );
  }

  Widget buildWidget(BuildContext context);
}

class Test extends StatelessWidget with Controller {
  @override
  Widget buildWidget(BuildContext context) {
    return Scaffold(body: Center(child: Text("Tap")));
  }

  @override
  ChangeNotifier activateController() {
    return TestProvider();
  }
}
```

**Comment by bambinoua** [comment]
@SergeyShustikov thank you for your example. I helps me to understand some thing related to mixins. But using your example I still can't achive my needs. It is possible that I want to much. :) In any case maybe you can help me.

I need to implement 2 mixins on `State`. 1st one is a base functionality, 2nd one is extended funtionality which must includes the functionality of 1st mixin. So I expected something like this:
```dart
mixin MyMixin<T extends StatefullWidget> on State<T> {
  Widget creteButton();
}

mixin MyExtendedMixin<T extends StatefullWidget> on MyMixin<T> {
  Widget creteWidget();
}

```
but it is naturally I could not to mix the `MyExtendedMixin` for my `State` until I mixed the `MyMixin`, i.e. I can do this:
```dart
class _MyState extends State<Widget> with MyMixin, MyExtendedMixin {}
```

but I would like to have this:
```dart
class _MyState extends State<Widget> with MyExtendedMixin {}
```

I spent time to try to implement this but without success. What do you think, do I want more than possible? ;)

**Comment by ChaserVasya** [comment]
same problem

**Comment by stan-at-work** [comment]
Same issue here. 

Why is this issue closed when there is no decision on whether it will be available, and no information on whether there is a fix for it yet?

**Comment by mraleph** [comment]
> Same issue here.
> 
> Why is this issue closed when there is no decision on whether it will be available, and no information on whether there is a fix for it yet?

Mixin composition is tracked in https://github.com/dart-lang/language/issues/540
