### ISSUE TITLE
Precompiler doesn't create `kInvokeFieldDispatcher` functions for callback fields with optional parameters

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#34572]
A recent [PR](https://github.com/flutter/flutter/pull/22249) failed on Flutter, but only when code is called in AOT release mode (JIT/debug works fine). Here's the relevant part of the [crash log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci82MWNmOTQ2YmE4YzU1YzczYzkxMTlhMjAzZDA3YjhjMDI1YjZhYTkyDAsSBFRhc2sYgICAgICAwAoM):

```
2018-09-24T21:32:27.882616: stdout: [  +19 ms] I/flutter ( 4203): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2018-09-24T21:32:27.882735: stdout: [   +1 ms] E/DartVM  ( 4203): ../../third_party/dart/runtime/vm/object.h: 6258: error: Handle check failed: saw Closure: (RouteSettings, (BuildContext) => Widget) => MaterialPageRoute expected TypeArguments
stdout: [        ] E/DartVM  ( 4203): Dumping native stack trace for thread 1082
stdout: [        ] E/DartVM  ( 4203):   [0x8f563ba1] Unknown symbol
2018-09-24T21:32:27.889829: stdout: [   +7 ms] E/DartVM  ( 4203):   [0x8f563ba1] Unknown symbol
2018-09-24T21:32:27.934663: stdout: [  +44 ms] E/DartVM  ( 4203):   [0x8f625491] Unknown symbol
stdout: [        ] E/DartVM  ( 4203): -- End of DumpStackTrace
2018-09-24T21:32:28.003378: stdout: [  +68 ms] Successfully connected to service protocol: http://127.0.0.1:62057/
2018-09-24T21:32:28.006533: stdout: [   +3 ms] getVM: {}
2018-09-24T21:32:28.019089: stdout: [  +12 ms] getIsolate: {isolateId: isolates/738645851}
```

And the relevant source bits:

```dart
typedef PageRouteFactory = PageRoute<T> Function<T>(RouteSettings settings, WidgetBuilder builder);

...
      // widget.pageRouteBuilder is a final PageRouteFactory
      final Route<dynamic> route = widget.pageRouteBuilder<dynamic>(
        settings,
        builder,
      );
```

which gets passed in as:

```dart
   WidgetsApp(
        pageRouteBuilder: <T>(RouteSettings settings, WidgetBuilder builder) =>
            MaterialPageRoute<T>(settings: settings, builder: builder),
...
```

If I rework the typedef to be like:

```dart
typedef PageRouteFactory = PageRoute<dynamic> Function(RouteSettings settings, WidgetBuilder builder);
...
   WidgetsApp(
        pageRouteBuilder: (RouteSettings settings, WidgetBuilder builder) =>
            MaterialPageRoute<dynamic>(settings: settings, builder: builder),
```

It's fine in AOT.

I've tried to create a simplified repro a few different ways, but whatever I do doesn't seem to reproduce the crash.  However, using the PR branch to run any material/cupertino app does reliably reproduce the crash.

**Comment by mraleph** [comment]
Could you investigate @sjindel-google?

**Comment by dnfield** [comment]
FWIW, I would have expected this code to reproduce it, but it runs fine:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

typedef PageRouteFactory = PageRoute<T> Function<T>(RouteSettings settings, WidgetBuilder builder);

class Repro {
  Repro(this.pageRouteBuilder);
  PageRouteFactory pageRouteBuilder;

  Route<dynamic> build() {
    final Route<dynamic> route = pageRouteBuilder<dynamic>(
      RouteSettings(name: '/', isInitialRoute: true), 
      (BuildContext context) => Placeholder(),
    );
    return route;
  }
}

void main() {
  var repro = new Repro(<T>(RouteSettings settings, WidgetBuilder builder) => 
    MaterialPageRoute<T>(settings: settings, builder: builder));
  print(repro.pageRouteBuilder);
  print(repro.build());
}
```

But it seems to run without error.  I've tried a few other modifications of it to no avail.

**Comment by sjindel-google** [comment]
The problem appears to be that we aren't building the invoke-field-dispatcher function for `pageRouteBuilder` when the call-site is generic, only when the call-site is non-generic. This is AOT-specific, because the precompiler is responsible for making sure all the necessary

**Comment by dnfield** [comment]
Why doesn't my smaller snippet [above](https://github.com/dart-lang/sdk/issues/34572#issuecomment-424421058) reproduce it?

**Comment by sjindel-google** [comment]
I'm not sure. When the `kInvokeFieldDispatcher` is missing, the compiler uses a slower path to invoke the closure. I'm investigating where it goes wrong in this process.

**Comment by sjindel-google** [comment]
I've uploaded https://dart-review.googlesource.com/c/sdk/+/76661 to fix the issue. I've verified that the fix works on Flutter Gallery when using your refactoring patch.
