### ISSUE TITLE
Can I get root isolate stack from other isolate?

### ISSUE THREAD

**Issue by workhardupc** [dart-lang/sdk#34575]
In class StackTrace, can only get current stack trace.

When root isolate stalled, I want to get the root isolate stack.

Can I get root isolate stack from other isolate?

**Comment by lrhn** [comment]
No.

Isolates are isolated, the only way they can communicate with each other is to pass messages through ports.
If one isolate stalls (likely an infinite loop) then it stops receiving port messages and it stops receiving most isolate commands - those are not fully handled until the isolate is back at the event loop.

The only one who can get a "current stack trace" of an isolate is the isolate itself.

I don't know if the `dart:developer` library can allow something through the debugger, but it's not something to rely on in production.
