### ISSUE TITLE
Make 'as' cheaper in AOT

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34582]
In https://github.com/flutter/flutter/issues/21813, @mraleph wrote:
> `x as String` is compiled down to some big code. if you do an implicit cast:
> 
> ```dart
>     String name1 = json["name1"] /* as String */;
> ```
> 
> that should yield smaller AOT code.

Is there any chance we could make `as` generate the same cheap code as an implicit cast in an assignment? My understanding is that with Dart2 there's now no reason why they should be different.

Flutter would like to disable all implicit casts and replace them all with `as`. We currently can't do that because we have the `avoid_as` lint enabled specifically because of this performance concern.

**Comment by matanlurey** [comment]
That is indeed confusing considering the VM has to do checks either way.

**Comment by mraleph** [comment]
> Is there any chance we could make as generate the same cheap code as an implicit cast in an assignment? 

Yes, we are going to look at this soon. @mkustermann has a CL which we will land when he is back from vacation. This is legacy stuff (implicit and explicit `as` checks throw different errors).

**Comment by mkustermann** [comment]
Now that I'm back from vacation I'll start working on this.

In https://github.com/dart-lang/sdk/issues/34097 we got the green light from the language team to treat implicit and explicit casts the same way.

**Comment by mkustermann** [comment]
Closing this, as implicit/explicit `as` should have same performance characteristics since the change above landed.
