### ISSUE TITLE
material-input and material_dropdown_select generated from LinkedHashMap.entries are not editable

### ISSUE THREAD

**Issue by pawsa** [dart-lang/sdk#34581]
* Dart SDK Version (`dart --version`)
 Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Reproduced with Firefox, Chrome and Chromium

**Issue statement**
A sequence of material-dropdown-select compoents fails to show the dropdown list when generated by ngFor over LinkedHashMap.entries. I.e. drop down selects generated as follow are not editable:

```
 <material-list-item *ngFor="let item of map.entries">
    <material-dropdown-select...>

```
The issue is even more evident for  a simpler

```
 <material-list-item *ngFor="let item of map.entries">
    <material-input></material-input>

```
FWIW, The component material-dropdown-select works as expected when generated by ngFor over LinkedHashMap.values.

```
 <material-list-item *ngFor="let item of map.values">
    <material-dropdown-select>...

```
See https://github.com/pawsa/editablelist/blob/master/lib/test_component.html for a simple yet complete demo.

I would expect some diagnostics to be generated at the very least.

**Comment by zoechi** [comment]
My suspicion is that subsequent calls to `map.entries` return new MapEntry instances every time which fail identity check. I'm not entirely sure Angular uses `identical()` instead of `==` but I believe so.

```dart
print(identical(map.entries.first, map.entries.first));
```
This would cause Angular change detection to detect changes every time it checks and re-render `*ngFor` which renders the dropdown closed again immediately after you open it.

As a workaround you could store `map.entries` in a field in the component and use that in `*ngFor` instead
```html
 <material-list-item *ngFor="let item of myMapEntries">
```

**Comment by lrhn** [comment]
Even subsequent iterations of the same `map.entries` may return a new `MapEntry` for the same key/value pair. You'd have to convert it to a list to be sure the values don't change - that's also a good recommendation any time you plan to use the same lazily computed iterable more than once.

Also, even if Angular uses `==`, `MapEntry` doesn't override `operator==`.
There is no *natural* equality on entries ... or rather, that equality would be the map's key-equality for the key and `==` for the value. We do not want each entry to carry a reference to the map class and a way to access its key equality.

**Comment by pawsa** [comment]
Failing identity checks sound like the explanation to me. This sounds like a broken^Wunintuitive design to me, though. map.entries promise property-like semantics. If the intention was not to behave like a property, map.entries() should have been used.

zoehi@: copying to a field is not an option: I do want to detect *real* changes and update the view accordingly.

**Comment by pawsa** [comment]
In my case, I can use map.values - where I can also store the key. map.values  provide the expected semantics, at least in the current implementation.
