### ISSUE TITLE
Why not use `...` to agree on multi-line strings?

### ISSUE THREAD

**Issue by 6643** [dart-lang/sdk#34587]
Why not use &#96;...&#96; to agree on multi-line strings?
'''...''' or """...""" is too cumbersome.

**Comment by natebosch** [comment]
Dart also has concatenation of adjacent strings - when you don't care about indentation I like to use that. FWIW I'd write this example as:

```dart
  var query = 'SELECT * FROM Task '
      "WHERE category = 'Personal' "
      'AND priority < 3 '
      'ORDER BY priority DESC';
```

Not the prettiest, but also probably good enough that we don't need yet another quote option.

**Comment by 6643** [comment]
@natebosch @lrhn 
thank's
