### ISSUE TITLE
language_2 tests f_bounded_quantification2_test and f_bounded_quantification4_test fail to satisfy bounds

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34583]
I believe both of these tests are erroneous:
- tests/language_2/f_bounded_quantification2_test.dart
- tests/language_2/f_bounded_quantification4_test.dart

In both cases a type appears in an "extends" clause that is inferred (via instantiate-to-bounds) as a super-bounded type, but super-bounded types aren't allowed in extends clauses.

f_bounded_quantification4_test is simpler so I'll consider it in detail:
```dart
import "package:expect/expect.dart";

class A<T extends B<T>> {}

class B<T> extends A {} // (1)

main() {
  Expect.equals("B<B<dynamic>>", new B<B>().runtimeType.toString());
}
```
According to my reading of https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md, the type `A` at `(1)` should be instantiated to `A<B<dynamic>>`.  This is a super-bounded type (because it does not satisfy the constraints of `A`, whereas `A<B<Null>>` does).  Therefore there should be a compile-time error, since super-bounded types aren't allowed in extends clauses.

f_bounded_quantification2_test is more complex but I believe it has the same problem.

I will soon be making a change to the analyzer to correctly detect this error condition.

@lrhn can you double-check my reasoning here?

**Comment by eernstg** [comment]
True, we cannot have instances whose dynamic type is a superbounded type, because that would compromise the soundness of code which has been compiled under the assumption that the bound is satisfied. So I agree with you that there should be a compile-time error for `extends A` in the example. I'll take a look at f_bounded_quantification2_test now, and return with a comment on that.

**Comment by eernstg** [comment]
2013! ;-)

Error here, too, maybe in other places as well, but certainly here: `implements EntityApi` and `implements EntitiesApi`.

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/115779
https://dart-review.googlesource.com/c/sdk/+/115900
