### ISSUE TITLE
Dart Analysis Server Error with latest dev-release sdk and IntelliJ

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#34590]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4505.22`
- `2.1.0-dev.5.0`
- `IC-182.4505.22, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1200, 1920x1200`

# Exception

```
Dart analysis server, SDK version 2.1.0-dev.5.0, server version , FATAL error: FormatException: Could not find an option named "enable-new-analysis-driver".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:307:45)
#4      CommandLineParser.parse (package:analysis_server/src/server/driver.dart:95:15)
#5      Driver.start (package:analysis_server/src/server/driver.dart:299:33)
#6      main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)```

```
1537951220518 started analysis server:
  C:\Users\johnniwinther\dart-sdk\bin\dart.exe C:\Users\johnniwinther\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IC-182.4505.22 --useAnalysisHighli
```

**Comment by bwilkerson** [comment]
Sorry about that! The flag `--enable-new-analysis-driver` has been removed because the new driver is now always enabled when running server. Unfortunately, we also (at a different time) changed server so that it no longer ignores unrecognized flags.

Please remove the obsolete flag from the `dart.server.additional.arguments` registry entry. That should solve the problem.

**Comment by johnniwinther** [comment]
And where is said registry? I've never seen or heard about it. (Given that, does it mean that this is failing for every user trying to update past version 2.0.0?)

**Comment by bwilkerson** [comment]
> And where is said registry?

Select the menu item "Help > Find Action...". In the dialog, type "Registry" and select "Registry..." from the list.

> I've never seen or heard about it.

As far as I know, the command-line parameter is only included if a user edits the list, but Jaime or Devon might know better. Let us know if it isn't explicitly included via the registry entry.

@jwren @devoncarew

**Comment by devoncarew** [comment]
> As far as I know, the command-line parameter is only included if a user edits the list, but Jaime or Devon might know better.

Yes, the user would have had to add that param in the registry explicitly - likely not a frequent event. You perhaps added it when doing some performance testing for us in the past?

**Comment by johnniwinther** [comment]
Thanks for the pointers. It works now.

... and yes, it must have been from some performance testing...
