### ISSUE TITLE
Dart Analysis error

### ISSUE THREAD

**Issue by rtolar** [dart-lang/sdk#34608]
While editing code, I received the following error:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.c688d0c0c3ad3dece3a79ce0e115d787a94707ea`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/kr/_0rvhwj9417dsnf42d8s43lc0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.c688d0c0c3ad3dece3a79ce0e115d787a94707ea, server version 1.20.5, error: Analysis failed: /Users/richardtolar/dev/emporosflutter/lib/default_route.dart
RangeError (index): Invalid value: Not in range 0..17, inclusive: 18
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7718:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7610:5)
#6      _ParameterElementImpl


------------------
```
Dart analysis server, SDK version 2.1.0-edge.c688d0c0c3ad3dece3a79ce0e115d787a94707ea, server version 1.20.5, error: Analysis failed: /Users/richardtolar/dev/emporosflutter/lib/default_route.dart
RangeError (index): Invalid value: Not in range 0..17, inclusive: 18
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7718:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7610:5)
#6      _ParameterElementImpl&VariableElementImpl&ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:7830:18)
#7      ExecutableElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:4100:19)
#8      MethodElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:6515:11)
#9      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3307:5)
#10     _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:827:19)
#11     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:1064:65)
#12     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:62:17)
#13     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#14     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#16     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#18     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#21     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:389:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:479:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:523:12)
#35     Driver.start (package:analysis_server/src/server/driver.dart:477:7)
#36     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1538080000356 => {"id":"16635","method":"analysis.updateContent","params":{"files":{"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart":{"type":"add","content":"import 'package:flutter/mat
1538080000384 <= {"id":"16632","result":{"fixes":[]}}
1538080000385 <= {"id":"16633","result":{}}
1538080000385 <= {"id":"16635","result":{}}
1538080000458 => {"id":"16636","method":"edit.getAssists","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1949,"length":0},"clientRequestTime":1538080000458}
1538080000664 <= {"id":"16634","result":{"fixes":[]}}
1538080000879 <= {"id":"16636","result":{"assists":[]}}
1538080000883 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538080001073 => {"id":"16637","method":"edit.getFixes","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1940},"clientRequestTime":1538080001073}
1538080001074 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538080001074 => {"id":"16638","method":"analysis.updateContent","params":{"files":{"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart":{"type":"add","content":"import 'package:flutter/mat
1538080001076 => {"id":"16639","method":"edit.getFixes","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1939},"clientRequestTime":1538080001076}
1538080001178 => {"id":"16640","method":"edit.getAssists","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1939,"length":0},"clientRequestTime":1538080001178}
1538080001414 <= {"id":"16637","result":{"fixes":[]}}
1538080001414 <= {"id":"16638","result":{}}
1538080001437 <= {"id":"16640","result":{"assists":[]}}
1538080001437 <= {"id":"16639","result":{"fixes":[]}}
1538080001441 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538080001991 => {"id":"16641","method":"edit.getFixes","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1939},"clientRequestTime":1538080001991}
1538080001991 => {"id":"16642","method":"analysis.updateContent","params":{"files":{"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart":{"type":"add","content":"import 'package:flutter/mat
1538080001992 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538080001994 => {"id":"16643","method":"edit.getFixes","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1944},"clientRequestTime":1538080001994}
1538080002000 <= {"id":"16641","result":{"fixes":[]}}
1538080002001 <= {"id":"16642","result":{}}
1538080002002 => {"id":"16644","method":"edit.getAssists","params":{"file":"/Users/richardtolar/dev/emporosflutter/lib/default_route.dart","offset":1944,"length":0},"clientRequestTime":1538080002002}
1538080002011 <= {"id":"16643","result":{"fixes":[]}}
1538080002011 <= {"id":"16644","result":{"assists":[]}}
1538080002016 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538080003476 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538080003491 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/richardtolar/dev/emporosflutter/lib/default_route.dart","stackTrace":"RangeError (index): Invalid 
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I think this was fixed in https://github.com/dart-lang/sdk/commit/765a78d44e7a9e5fd09b10a3b0c60c6e2e4bba96.
