### ISSUE TITLE
CFE: Change errors to warnings

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34612]
Once the list in https://github.com/dart-lang/sdk/issues/34349 is finalized, we should make sure that the severity of all of these diagnostic messages is set to be warnings in the CFE.

**Comment by askeksa-google** [comment]
I took a round on current CFE status of the errors in the list:

- **conflicting_dart_import**, **mixin_return_types**: Could not find matching analyzer error codes. Language team had the same experience.
- **return_without_value**: CFE already reports a warning.
- **mismatched_getter_and_setter_types**, **mismatched_getter_and_setter_types_from_supertype**, **missing_enum_constant_in_switch**, **non_void_return_for_operator**, **non_void_return_for_setter**: CFE does not detect the situation. We can leave them as they are and optionally implement warnings later.
- **import_duplicated_library_named**: Currently an error in the CFE. https://dart-review.googlesource.com/c/sdk/+/78242 makes it a warning.
- **final_not_initialized**, **final_not_initialized_constructor**: Not clear whether this applies to all final variables or just to instance variables. They have all produced an error in the CFE since August 17 (fixed by https://dart-review.googlesource.com/c/sdk/+/63781 and https://dart-review.googlesource.com/c/sdk/+/66563), so it would seem it is not breaking anything. The language team would like to think about this before we make it a warning.

**Comment by kmillikin** [comment]
We need a decision on final_not_initialized and final_not_initialized_constructor.  The rest are either already warnings in the CFE or not signaled.

**Comment by leafpetersen** [comment]
@lrhn Thoughts on the final variables question?  I'm fine either way, and am inclined to go with the path of minimum implementation effort (presumably leaving as error, since that's what it is now).

**Comment by dgrove** [comment]
Adding @lrhn

**Comment by lrhn** [comment]
I'd want to make as many of these warnings errors as possible (well, except for duplicate library name, which is useless). 
If they are already errors in the analyzer, then let's keep it that way.

**Comment by askeksa-google** [comment]
With missing initialization of final variables categorized as an error, the CFE now reports either a warning or nothing for all remaining items on the list.

The analyzer currently reports most of the items (all in the second and third bullets here) as errors, so we have the option of upgrading these to warnings or errors in the CFE later, though that will not be done for 2.1.
