### ISSUE TITLE
NPE in _SummarizeAstVisitor.visitConstructorDeclaration

### ISSUE THREAD

**Issue by blackmenthor** [dart-lang/sdk#34610]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1366x768, 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/l6/w6xjmy255mbdjvkpznnlqbw40000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1088:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2945:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:469:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1045:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1764:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8251:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:522:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:21:37)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:428:46)
#10     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:427:26)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I was not able to reproduce it.

It happens when `ConstructorDeclaration.parameters` is `null`, which is not correct, and should not be produced by the parser. Is this something fixed between the version that the user has and now? @danrubel

**Comment by danrubel** [comment]
I don't remember fixing anything like that recently.
I can certainly put some asserts in AstBuilder if you think that would help narrow down the problem.

**Comment by bwilkerson** [comment]
_If_ the bug is in `AstBuilder`, it looks like it would be in `endFactoryMethod`. The other place a constructor declaration is create is in `endMethod`, but it looks like `endMethod` guards against the popped list of parameters being `null`, while `endFactoryMethod` does not have any guard.

**Comment by danrubel** [comment]
I refactored some of the recovery code and added some guard code in AstBuilder.
https://dart-review.googlesource.com/c/sdk/+/78000
Hopefully this will help narrow down the problem.

**Comment by scheglov** [comment]
OK, I can reproduce it.
```dart
class C {
  get C.named => null;
}
```

**Comment by scheglov** [comment]
This is definitely a parser issue.
@danrubel can you fix it please? :-)
