### ISSUE TITLE
Analyzer training runs are broken on Fuchsia

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#34616]
```
output: Unhandled exception:
NoSuchMethodError: The method 'getChild' was called on null.
Receiver: null
Tried calling: getChild("uuid.txt")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Driver._readUuid (package:analysis_server/src/server/driver.dart:669:10)
#2      Driver.start (package:analysis_server/src/server/driver.dart:434:9)
#3      main (file:///usr/local/google/home/rmacnak/ssd/topaz1/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by bwilkerson** [comment]
Server stores a session id on disk for the purposes of logging information (internal users only). It puts the file in the user's home directory:
```dart
final home = io.Platform.isWindows ? env['LOCALAPPDATA'] : env['HOME'];
```
I'm guessing that on Fuchsia either there is no home directory or this isn't the right way to get the path. Can you tell me which case I'm looking at?

**Comment by rmacnak-google** [comment]
`fx set x64 out/debug-x64 --args use_prebuilt_dart_sdk=false && fx full-build`

**Comment by zanderso** [comment]
There won't be a home directory during the Fuchsia build, and it would be best not to touch the environment at all, really even in the non-Fuchsia case. It could potentially be a source of non-hermetic-ness.

**Comment by bwilkerson** [comment]
We can fix the code so that it doesn't break when there's no home directory, but the training program we use writes to disk, so that might be a bigger issue. We do that because during normal use the analysis server uses the disk as a cache. The training analyzes the same set of source files twice: once when the disk cache is empty (which fills the cache) and once when it is full. This causes us to exercise two code paths that are important for optimal performance.

I'm not sure how we want to deal with that. Ideas?

**Comment by zanderso** [comment]
Can you accept the cache directory as a command line argument?

**Comment by bwilkerson** [comment]
Yes, using `--cache`.

**Comment by zanderso** [comment]
So, to clarify: That flag already exists, and if it is set, it will bypass touching $HOME?

**Comment by bwilkerson** [comment]
No. There are two different sets of data being cached. There is a UUID used to represent a user to a reporting mechanism used only for internal users (which is what's looking for $HOME), and there is a set of data per library representing the results of analyzing the library. The flag controls the location of the latter, but not the former.

**Comment by zanderso** [comment]
> There is a UUID used to represent a user to a reporting mechanism used only for internal users (which is what's looking for $HOME)

This should almost certainly be turned off during a training run during the build.

**Comment by bwilkerson** [comment]
I think that https://dart-review.googlesource.com/c/sdk/+/77422 should fix the issue, but I don't have any way to test it. Please let me know if the problem persists or if you need any other changes.
