### ISSUE TITLE
[window.fetch] Unable to return result

### ISSUE THREAD

**Issue by 6643** [dart-lang/sdk#34617]
```
$ cat main.dart 
import 'dart:html';

main() {
  window.fetch('https://httpbin.org/get').then((response) {
    print(response);
  });
}
$ dart2js main.dart
Compiled 7,352,967 characters Dart to 87,873 characters JavaScript in 1.19 seconds

```

main.dart:4 Uncaught TypeError: C.Window_methods.fetch$1(...).then$1 is not a function
    at Object.main (main.dart:4)
    at out.js:2325
    at out.js:2309
    at out.js:2320
    at out.js:2328
main @ main.dart:4
(anonymous) @ out.js:2325
(anonymous) @ out.js:2309
(anonymous) @ out.js:2320
(anonymous) @ out.js:2328

**Comment by sigmundch** [comment]
@terrylucas - it appears that `fetch` is declared to return a Future, and the original JS fetch returns a `Promise`. Seems like there is a conversion missing between the two?

**Comment by 6643** [comment]
This problem no longer exists today

**Comment by 6643** [comment]
This problem no longer exists today
