### ISSUE TITLE
Breaking bug-fixes in CFE for Dart 2.1

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34611]
A number of situations that are defined to be compile-time errors by the spec were not adequately checked in Dart 2.0. Most known cases have been, or will be, implemented for Dart 2.1. Any such newly implemented compile-time error that was detected by neither the analyzer nor the CFE in 2.0 is a *breaking bug-fix*.

This issue aims to track our overall process of integrating and rolling out the known breaking bug-fixes.

Some breaking bug-fixes (e.g. https://github.com/dart-lang/sdk/issues/33022) have already been re-classified as warnings, as specified in https://github.com/dart-lang/sdk/issues/34349. Our known breaking bug-fixes which have not been re-classified are:

- Interface checks and mixin overrides (https://github.com/dart-lang/sdk/issues/32014 and https://github.com/dart-lang/sdk/issues/34235).  *These checks are necessary for soundness, so they can probably not be re-classified. At the same time, the risk of existing code breaking because of these checks is high, as these override relationships can sometimes be quite subtle. A violation has already been found (and [fixed](https://github.com/dart-lang/dartdoc/pull/1755)) in `dartdoc`.*
- Relaxed generic interface conflict check (https://github.com/dart-lang/sdk/issues/34574). *This was a work-around for existing super mixin code in Flutter. The flutter code has been fixed. This change is probably safe.*
- Type arguments after named constructor with implicit new (https://github.com/dart-lang/sdk/issues/34403). *Making this a warning would be sound (as it is just unsupported syntax), but doing so will hinder future implementation of the feature, as discussed in the issue.*
- Redirection from `const` to non-`const` constructor (https://github.com/dart-lang/sdk/issues/34161). *Unlikely to occur in existing code, as such a situation would probably fail either in the back-end or at runtime.*
- `FutureOr` in an `implements` clause (https://github.com/dart-lang/sdk/issues/33744). *Very unlikely to occur in existing code.*
- Setter with the same name as the enclosing class (https://github.com/dart-lang/sdk/issues/34225). *Unlikely, but also harmless to re-classify.*
- Import prefix hidden by class member (https://github.com/dart-lang/sdk/issues/34498).

Action items:

- [x] Decide which (if any) of these errors should be re-classified as warnings, and add them to the list in https://github.com/dart-lang/sdk/issues/34349.
- [x] Decide how to go about rolling these changes (in particular the first in the list) into internal code. Maybe we want to test it before landing the change (compiling all the code should suffice). Maybe we want to land the checks as warnings first, then up them to errors after fixing existing code.
- [x] Fix all existing internal code.
- [x] Assess impact on external code.
- [x] Land the remaining fixes.
- [ ] Describe all of these changes in the release notes for 2.1.
- [x] Mail flutter-dev, dart-misc, and dart-announce with breaking fix announcement.

**Comment by dgrove** [comment]
@kmillikin given our timeline, is this still viable?

**Comment by kmillikin** [comment]
I'm sorry, I didn't understand the status of #34498.  It's not caught by the CFE or the Analyzer, for different reasons.

It looks like we'll ship Dart 2.1 without fixing the issue in the front end unless the language team wants to elevate the priority for it.

**Comment by askeksa-google** [comment]
Correction: https://github.com/dart-lang/sdk/issues/33022 will not be breaking whatever we do, since it was detected by the analyzer (as a warning) in 2.0.

**Comment by dgrove** [comment]
Any further updates here?

**Comment by askeksa-google** [comment]
Fixes have landed for all 8 issues mentioned in the list. Only communication remains.

I can write a description of each change with examples. That could then go in the release notes and on the mailing lists with an appropriate introduction.

As mentioned, there is a corner case of https://github.com/dart-lang/sdk/issues/33308 (related to generic typedefs) which is also breaking. I will include that on the list of descriptions.

**Comment by askeksa-google** [comment]
"It is a compile-time error if a class named `C` declares a member with
basename `C`." (10)

Dart 2.0 lacked this check for setters, allowing this code:
```dart
class A {
  set A(int x) {}
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34225

---

"When **const**? is **const**, it is a compile-time error if the redirectee
is not a constant constructor." (10.6.1)

Dart 2.0 allowed a constant constructor to redirect to a non-constant
constructor, like this:
```dart
class A {
  const A.foo() : this(); // Redirecting to A()
  A() {}
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34161

---

"Let *C* be a concrete class whose interface has an accessible member *m* named
`id`. It is a compile-time error if *C* does not have a concrete member *m0*
named `id` which is a correct override of *m*, unless *C* has a concrete method
named `noSuchMethod` which is different from the one in the built-in class
`Object`, and *C* does not have a concrete member named `id`." (10.8.1)

Dart 2.0 missed this check in some cases. So for instance, this code would be
allowed:
```dart
class A {
  num get thing => 2.0;
}

abstract class B implements A {
  int get thing;
}

class C extends A with B {} // 'thing' from 'A' is not a valid override of 'thing' from 'B'.

main() {
  print(new C().thing.isEven); // Expects an int but gets a double.
}
```
Issue link: https://github.com/dart-lang/sdk/issues/32014

---

"It is a compile-time error if an element in the type list of the `implements`
clause of a class *C* is type `FutureOr<T>` for any `T`." (10.9)

Dart 2.0 did not perform this check, allowing code like:
```dart
class A implements FutureOr<Object> {}
```
Issue link: https://github.com/dart-lang/sdk/issues/33744

---

"It is a compile-time error if a class *C* has two superinterfaces that are
different instantiations of the same generic class." (10.9)

Dart 2.0 contained a temporary relaxation of this rule that would allow two
instantiations of the same generic class if one was a subtype of the other.
For instance, this code would be accepted:
```dart
class I<T> {}

class A {}

class B extends A {}

class X implements I<B> {}

class Y extends X implements I<A> {} // Y implements both I<A> and I<B>
```
Issue link: https://github.com/dart-lang/sdk/issues/34574

---

"Let *K* be a class declaration with the same constructors, superclass and
interfaces as *C*, and the instance members declared by *M*
(respectively *M1*, . . . , *Mk*). It is a compile-time error if the
declaration of *K* would cause a compile-time error." (12.1)

Dart 2.0 did not check whether members of a mixin were correct overrides
of the corresponding member of the superclass in a mixin application. This
would allow code such as:
```dart
class A {
  int get thing => 2;
}

class B {
  num get thing => 2.0;
}

class C extends A with B {} // 'thing' from 'B' is not a valid override of 'thing' from 'A'.

main() {
  A a = new C();
  print(a.thing.isEven); // Expects an int but gets a double.
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34235

---

"Consider a generic type alias declaration *G* named `F` with formal type
parameter declarations `X1 extends B1`, . . . , `Xm extends Bm`, and right hand
side *T*, and the parameterized type *S* of the form `F<T1, . . . , Tl>`.
It is a compile-time error if *S* is not well-bounded." (14)

Dart 2.0 was missing this well-bounded check, allowing this code:
```dart
class A<X extends int> {}

typedef F<Y extends int> = A<Y> Function();

F<num> f = null;
```
Issue link: https://github.com/dart-lang/sdk/issues/33308

---

Dart 2.0 allowed the type arguments for an instance creation of a generic class
using a named constructor to be placed after the constructor name when the
optional `new` keyword was omitted.
```dart
class A<T> {
  A.foo() {}
}

main() {
  A.foo<String>(); // Incorrect syntax, was accepted in 2.0
  A<String>.foo(); // Correct syntax
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34403

---

Dart 2.0 allowed a type to use a prefix even if that prefix was shadowed by
a declaration.
```dart
import 'dart:core';
import 'dart:core' as core;

class A {
  core.List get core => null; // core refers to the field, not the prefix
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34498

**Comment by askeksa-google** [comment]
Indeed it seems the 2.0 analyzer caught https://github.com/dart-lang/sdk/issues/34574. It also catches the specific example I wrote for https://github.com/dart-lang/sdk/issues/34235, but it did miss some mixin overrides, as described in https://github.com/dart-lang/sdk/issues/34317. I will write a better example for https://github.com/dart-lang/sdk/issues/34235 which is also missed by the 2.0 analyzer.

**Comment by askeksa-google** [comment]
"Let *K* be a class declaration with the same constructors, superclass and interfaces as *C*, and the instance members declared by *M* (respectively *M1*, . . . , *Mk*). It is a compile-time error if the
declaration of *K* would cause a compile-time error." (12.1)

Dart 2.0 did not always check whether members of a mixin were correct overrides of the corresponding member of the superclass in a mixin application. This would allow code such as:
```dart
class A {
  num get thing => 2.0;
}

class M1 {
  int get thing => 2;
}

class B = A with M1;

class M2 {
  num get thing => 2.0;
}

class C extends B with M2 {} // 'thing' from 'M2' not a valid override.

main() {
  M1 a = new C();
  print(a.thing.isEven); // Expects an int but gets a double.
}
```
Issue link: https://github.com/dart-lang/sdk/issues/34235

**Comment by askeksa-google** [comment]
Replaces the corresponding section for https://github.com/dart-lang/sdk/issues/34235. Only https://github.com/dart-lang/sdk/issues/34574 goes away.

**Comment by munificent** [comment]
> @munificent Are you handling the CHANGELOG for these?

Yup, I made a note to include the stuff in this issue. @askeksa-google, if you want, you can put this directly in the CHANGELOG file too.

In general, any time *anyone* lands a change in the SDK that is breaking or significantly impacts users, *that CL* should also add a description to the CHANGELOG. We can go back and condense stuff in the CHANGELOG later, but it's important that it gets written down at least once so that we know to include it at all.

**Comment by leafpetersen** [comment]
@askeksa-google Thanks very much for the writeup.

I've posted a summary to [dart-misc](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/krN8cAKfr_U) and [flutter-dev](https://groups.google.com/forum/#!topic/flutter-dev/dW5vuDhbU1Q).

**Comment by leafpetersen** [comment]
@munificent Once the CHANGELOG entry lands can you close this out?

**Comment by munificent** [comment]
You got it!

**Comment by dgrove** [comment]
Any ETA on the CHANGELOG, @munificent ?

**Comment by askeksa-google** [comment]
https://github.com/dart-lang/sdk/issues/32014 and https://github.com/dart-lang/sdk/issues/34235 (with the old example) were mentioned in the CHANGELOG when they were committed. The change is here: https://dart-review.googlesource.com/c/sdk/+/77741

**Comment by munificent** [comment]
I've been out sick, but I'll try to get to it today.

**Comment by munificent** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/82361

**Comment by mit-mit** [comment]
Looks like @munificent changelog changes landed. @askeksa-google anything else we need here?

**Comment by munificent** [comment]
Closing it since I think this was just waiting on the CHANGELOG. @askeksa-google, feel free to re-open if you think there's more to do.
