### ISSUE TITLE
Provide a service protocol extension to control GC

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34618]
We've had a number of cases recently where benchmarks have changed in distressing ways but upon investigation the most likely cause is determined to be a difference in GC timing (e.g. happening later causing memory usage to be greater, or happening earlier causing wall-clock time to be longer).

It would be extremely helpful if, during benchmarks, we could force a GC at a particular time. We would not want this feature to be available in release builds (because we don't want applications controlling their own GC, that typically results in worse performance), and we don't need it to be available in debug builds (since benchmarks aren't run in debug builds), we would only need this in profile builds.

**Comment by goderbauer** [comment]
See https://github.com/flutter/flutter/pull/22238 as an example where GC is causing trouble for benchmark runs.

**Comment by goderbauer** [comment]
I can't seem to call the provided `_collectAllGarbage` from flutter driver and it's not giving me any helpful errors, see https://github.com/goderbauer/flutter/commit/ee2afb2c5a343384b9eb12d3f32701a7842f6f5a for how I am trying to call it an the exception I am getting. 

@rmacnak-google Is there anything obvious I am doing wrong in calling this? I was just copying how the other service methods are called.

**Comment by goderbauer** [comment]
Nevermind, I found the issue (see comment on commit linked above).
