### ISSUE TITLE
Flaky failure in product/release mode of vm/dart/appjit_cha_deopt_test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#34627]
This test has failed sporadically on both Linux and windows.  Log of a failure is at https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8934105289149893248/+/steps/vm_tests_shard_1/0/stdout
on builder 
https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-linux-product-x64

Marking as flaky in the status file runtime/tests/vm/vm.status.

The log says:
FAILED: dartk-vm product_x64 vm/dart/appjit_cha_deopt_test
  Expected: Pass
  Actual: RuntimeError
  --- Command "vm" (took 01.000757s):
  DART_CONFIGURATION=ProductX64 out/ProductX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart/appjit_cha_deopt_test.dart
  exit code:
  255
  stdout:
  + out/ProductX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --snapshot=/b/s/w/iteNixBh/GREMKH/app.jit --snapshot-kind=app-jit /b/s/w/ir/runtime/tests/vm/dart/appjit_cha_deopt_test_body.dart --train
  + out/ProductX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/iteNixBh/GREMKH/app.jit
  running [RUN FROM SNAPSHOT] out/ProductX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/iteNixBh/GREMKH/app.jit:
  Command stderr:
  Unhandled exception:
  NoSuchMethodError: Class 'IOOverrides' has no instance getter 'scheme'.
  Receiver: Instance of 'IOOverrides'
  Tried calling: scheme
  #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
  #1      _setPackagesMap (dart:_builtin:207:19)
  stderr:
  Unhandled exception:
  Expect.fail('[RUN FROM SNAPSHOT] Process finished with non-zero exit code 255')
  #0      Expect._fail (package:expect/expect.dart:651:5)
  #1      Expect.fail (package:expect/expect.dart:269:5)
  #2      reportError (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart:34:10)
  #3      runDartBinary (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart:53:5)
  #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
  #5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
  #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
  #8      Future._completeWithValue (dart:async/future_impl.dart:486:5)
  #9      Future.wait.<anonymous closure> (dart:async/future.dart:399:22)
  #10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
  #11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
  #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
  #13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
  #14     Future._completeWithValue (dart:async/future_impl.dart:486:5)
  #15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
  #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
  #19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
  --- Re-run this test:
  python tools/test.py -m product -n dartk-linux-product-x64 --output-directory /b/s/w/ioUgDoXd --write-results vm/dart/appjit_cha_deopt_test

**Comment by sjindel-google** [comment]
I saw this again today in https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924811950970976960/+/steps/vm_tests/0/stdout:
```
FAILED: app_jitk-vm product_x64 language_2/deferred_load_inval_code_test
Expected: Pass
Actual: RuntimeError

--- Command "app_jit" (took 702ms):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --snapshot=/b/s/w/ir/cache/builder/sdk/out/ProductX64/generated_compilations/app_jitk/tests_language_2_deferred_load_inval_code_test/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language_2/deferred_load_inval_code_test.dart

exit code:
0

--- Command "vm" (took 129ms):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ProductX64/generated_compilations/app_jitk/tests_language_2_deferred_load_inval_code_test/out.jitsnapshot

exit code:
255

stderr:
Unhandled exception:
NoSuchMethodError: Class '_IOSinkImpl' has no instance getter 'scheme'.
Receiver: Instance of '_IOSinkImpl'
Tried calling: scheme
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _setPackagesMap (dart:_builtin:207:19)
```

**Comment by dcharkes** [comment]
More of these failures happening: [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924681631360574544/+/steps/vm_tests/0/stdout), [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924723694484524624/+/steps/vm_tests/0/stdout), [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924708636798629888/+/steps/vm_tests/0/stdout), and [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924685556346974592/+/steps/vm_tests/0/stdout).

**Comment by dcharkes** [comment]
@sjindel-google why is this the same issue as what @whesse posted? Because of the NoSuchMethodError? Other than that these failures seem to be unrelated.

**Comment by sjindel-google** [comment]
Yes, because of the "NoSuchMethodError". It seems likely that the receiver for ".scheme" is being pulled from the weeds.

**Comment by sstrickl** [comment]
Another instance ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924352546485836000/+/steps/vm_tests/0/stdout)) of the failure in language_2/deferred_load_invalid_code_test on app-kernel-linux-release-x64:

```
FAILED: app_jitk-vm release_x64 language_2/deferred_load_inval_code_test
Expected: Pass
Actual: RuntimeError

--- Command "app_jit" (took 810ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/tests_language_2_deferred_load_inval_code_test/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language_2/deferred_load_inval_code_test.dart

exit code:
0

--- Command "vm" (took 195ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/tests_language_2_deferred_load_inval_code_test/out.jitsnapshot

exit code:
255

stderr:
Unhandled exception:
NoSuchMethodError: Class '_IOSinkImpl' has no instance getter 'scheme'.
Receiver: Instance of '_IOSinkImpl'
Tried calling: scheme
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _setPackagesMap (dart:_builtin:207:19)

--- Re-run this test:
python tools/test.py -n app_jitk-linux-release-x64 language_2/deferred_load_inval_code_test
```

**Comment by aam** [comment]
Five failures in last 24 hours: - three on product bot, two on release bot: [failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924250807931517360/+/steps/vm_tests/0/stdout), [failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924266744255352032/+/steps/vm_tests/0/stdout), [failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924277323873379120/+/steps/vm_tests/0/stdout), [failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924301581918408944/+/steps/vm_tests/0/stdout), [failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924322151375680080/+/steps/vm_tests/0/stdout)

**Comment by crelier** [comment]
How is this class finalizer assert fault related to this NoSuchMethodError?
The assert fault seems to indicate a collision while rehashing type argument vectors. Was anything changed recently in the way we hash types?

**Comment by aam** [comment]
NoSuchMethodError seems to be caused by broken class structure as that seems to be an impossible situation.
They are related because the failure are in exact same test. Until this debug failure on a assertion, all previous failure as far as I know were NoSuchMethodErrors in release/product mode.

**Comment by crelier** [comment]
I think this is what's happening:
The function ClassFinalizer::RehashTypes() is racing with the background compiler. As the types are being rehashed, the background compiler inserts new canonical type arguments in the table, using the new hashes (new cids), but the table is still hashed according to the old cids, which results in collisions and assert faults once the type arguments are being rehashed.

The background compiler should be blocked from running during the rehashing.

**Comment by mraleph** [comment]
@crelier Regis, given that you analyzed the issue and established the root case do you think this is something you could also fix?

**Comment by crelier** [comment]
@mraleph Slava, sure, I'll kick the tires of this theory today.

**Comment by crelier** [comment]
Stopping the background compiler before sorting classes should fix this issue.
