### ISSUE TITLE
Implement a tool to inspect AOT snapshot sizes 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34632]
We have a tool that allows to view RX part of the snapshot broken down by package/library/method. 

We don't have a comparable way of visualizing the other parts of the snapshot - but having such a tool is essential for large applications to understand where size is coming from.

**Comment by Hixie** [comment]
@sjindel-google Is there a roadmap or timescale on which we might see a resolution to this issue? (I am asking because it's blocking a similar issue on Flutter's side and I'm just trying to figure out what expectations I should be setting.)

**Comment by sjindel-google** [comment]
It's a an OKR for me in Q4, but I will likely have something usable before then.

**Comment by Hixie** [comment]
@sjindel-google Is the tool available publicly yet?

**Comment by sjindel-google** [comment]
Yes, it's been complete since early December.
Docs are in `runtime/docs/snapshot_profiling.md` in the Dart repo.
