### ISSUE TITLE
Unable to run `dart data:application/dart;xxx` from CLI in Dart v2

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34639]
Sometime shortly after v2 dev 40 the ability to run dart with `data:` URIs seems to have become broken.

// v2.0.0:

```text
$ dart "data:application/dart;charset=utf-8,main%28%29%7Bprint%28%22test%22%29%3B%7D"
data:application/.packages:1: Error: Unable to read '.packages' file:
  FormatException: Expecting '='
application/.packages.
```

In v1 (and early dev builds) this would work:

```text
$ ~/Dev/dart-sdk/v1/bin/dart "data:application/dart;charset=utf-8,main%28%29%7Bprint%28%22test%22%29%3B%7D"
test
```

I noticed this when trying to contribute to vm_service_client - the test suite is broken because it passes scripts this way (https://github.com/dart-lang/vm_service_client/issues/32).

**Comment by mraleph** [comment]
@a-siva what is your opinion abou t this? Should we just close this as "Won't Fix"? I think the original support for `dart:` here was complete accident.

**Comment by DanTup** [comment]
Doing some tidying up of issues I've opened. Closing this one as it sounds like this wasn't intended to work, and the original issue that led me here is in a now-archived repo.
