### ISSUE TITLE
Analyzer checks "class C<X extends C>" class declaration in a very strange way.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34635]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10

Here is a sample code which declares a class `C<X extends C>`:
``` dart
//class A<X extends C> {}
class C<X extends C> {}
main() {}
```
It fails with compile time error both in analyzer and dart:
> Analyzing test1.dart...
>   error - Type parameter bound types must be instantiated at test1.dart:2:19 - strong_mode_not_instantiated_bound
> 1 error found.

See also bugs #33152, #31810.

This is very strange, but if I uncomment a first line in the code, i.e. have:
``` dart
class A<X extends C> {}
class C<X extends C> {}
main() {}
```
this test still fails with the same compile error with dart, however with dartanalyzer it starts to pass unexpectedly, analyzer sample output is:
> Analyzing test1.dart...
> No issues found!

So I believe analyzer should behave in the same way with both sample code examples above.

**Comment by stereotype441** [comment]
I'm looking into this now.

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/78867
