### ISSUE TITLE
analyzer/linter unrelated_type_equality_checks fails to recognize mixin constraints

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34641]
With `package:analyzer` version `0.33.0-alpha.0` and `package:linter` version `0.1.66` the `unrelated_type_equality_checks` is unable to recognize type compatibility correctly when the types bounds are specified using the `on` clause:

```dart
abstract class A {
  A parent;
}

class B extends A {

}

mixin M<T extends B> on B {
  void foo(T t) {
    assert(t.parent == this);
//                  ^
//                  Equality operator `==` invocation with references of unrelated types.
  }
}
```

@pq @JekCharlsonYu @stereotype441 @bwilkerson

**Comment by stereotype441** [comment]
I'm looking into this now.

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/77676

**Comment by yjbanov** [comment]
I'm still seeing this on `analyzer` version `0.33.0` and `linter` version `0.1.68`

**Comment by yjbanov** [comment]
nvm, was hitting a wrong version of the Dart SDK.
