### ISSUE TITLE
Analyzer generates nonsensical function types based on generic typedefs

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34657]
Consider the following typedefs:
```dart
typedef F<T> = void Function(T); // Equivalent to: typedef void F<T>(T t);
typedef G = void Function<T>(T);
typedef H<T> = void Function<U>(T, U);
```

Each of these typedefs is represented in the element model by a `FunctionTypeAliasElement`.  When that element's `.type` is queried, or a function type is produced by calling the `FunctionTypeImpl.forTypedef` constructor (and not supplying the named parameter `typeArguments`), the following types are returned:
- For F: `<T>(T) -> void`
- For G: `(T) -> void`
- For H: `<T>(T, U) -> void`

These types don't make sense.  In the case of F, we are producing a generic function type, but what we actually have is a generic *typedef* that should expand to a *non-generic* function type.  In the case of G, the function type's type formal is just dropped.  In the case of H, the function type's type formal is replaced with the typedef's type parameter.

It would be far better to return the "raw types" for the typedefs (the types represented by the right hand side, with no substitutions performed).  That is:
- For F: `(T) -> void`
- For G: `<T>(T) -> void`
- For H: `<U>(T, U) -> void`

There are similar problems when using `FunctionTypeImpl.forTypedef` and supplying `typeArguments`:
- `FunctionTypeImpl.forTypedef(fElement, [objectType])` produces `(Object) -> void`
- `FunctionTypeImpl.forTypedef(gElement, [])` produces `(T) -> void`
- `FunctionTypeImpl.forTypedef(hElement, [objectType]) produces `(Object, U) -> void`

It would be far better to return the right hand side with the type arguments substituded, i.e.:
- `FunctionTypeImpl.forTypedef(fElement, [objectType])` should produce `(Object) -> void` (note: this works correctly)
- `FunctionTypeImpl.forTypedef(gElement, [])` should produce `<T>(T) -> void`
- `FunctionTypeImpl.forTypedef(hElement, [objectType])` should produce `<U>(Object, U) -> void`

Note: this is a bug in the analyzer API, not a bug in the analyzer's analysis of source code. For the most part, if the user actually uses the above typedefs in their source code, the analyzer behaves correctly, due to workarounds elsewhere in the analyzer code base.  However, I believe that in some complex cases the workarounds aren't sufficient.

Related issue: #33294

**Comment by srawlins** [comment]
I strongly suspect this is fixed; generic typedefs are used so commonly now, we'd see user reports. In any case, please re-open if this still needs fixing.
