### ISSUE TITLE
minor rephrasing request: Replace "another library" by " current library"

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/sdk#34652]
The  Dart Language Specification, Chapter 18 "Libraries and Script",
   in section 18.1 "Imports" states
  "An import specifies a library to be used in the scope of another library."

I would prefer

     "An import specifies a library to be used in the scope of current library, 
      which holds the library import declaration."

By the way
 
   replace "the the " occurrences  by  "the"

**Comment by eernstg** [comment]
Hello @pet-ro, thanks for the input, sorry about not getting around to it!

At this time the text you mention has been rewritten totally, and there are no occurrences of 'the the', so I'll close the issue.
