### ISSUE TITLE
Backreferences to typedefs are sometimes lost in the functoin types built from them

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#34655]
Kernel's `FunctionType` has a backreference to the `Typedef` it was built from (`FunctionType.typedefReference`).  Sometimes this reference is lost, that is, `(typedef.type as FunctionType).typedefReference` is sometimes `null`.

It's hard to reproduce this error.  One way to do that is the following.  After [CL 57621](https://dart-review.googlesource.com/57621) lands, try removing the line commented with a TODO that has the id of this GitHub issue, then build `dartdevc_test` target and run test `language_2/checked_null_test/01`.

```bash
$ ./tools/build.py -m release -a x64 runtime_kernel create_sdk dartdevc_test
$ python tools/test.py -m release -r chrome -n dartdevk-checked-linux-release-chrome language_2/checked_null_test/01
```

It should crash because of the `null` in the reference.

**Comment by peter-ahe-google** [comment]
I've removed the work around and added some checks that helps us diagnose the root cause in this CL https://dart-review.googlesource.com/c/sdk/+/81408
