### ISSUE TITLE
int.parse()'s FormatException when number is too large is really not helpful

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#34667]
Take the following program, executed with dart 2.0.0:

```dart
void main() {
  int.parse(
      '101110100110101101011010000100001111101110000001111011111111111111101011010101000',
      radix: 2);
}
```

```none
$ dart c.dart
Unhandled exception:
FormatException: Invalid radix-2 number
101110100110101101011010000100001111101110000001111011111111111111101011010...
#0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:130:5)
#1      int._parse (dart:core/runtime/libintegers_patch.dart:104:14)
#2      int.parse (dart:core/runtime/libintegers_patch.dart:61:12)
...
```

The words "FormatException" and "Invalid radix-2 number" lead me to believe that the string that I passed does not contain a valid binary number, like it contains a 7 or something. And seeing the ellipsis at the end doesn't alleviate this worry. What else is in the string that I passed? It takes a while to realize it is not exactly the contents of the string, but the size of the number that is the problem.

It would be helpful if the error message said _something_ about the number being too large, for myself, and for users unfamiliar with the integer restrictions of Dart 2.

Clang's C++ compiler includes messages like ["integer literal is too large to be represented ..."](http://clang.llvm.org/docs/DiagnosticsReference.html#wc-11-compat).

If the class thrown needs to remain FormatException, that's fine.

**Comment by srawlins** [comment]
Ouch.

**Comment by ZichangG** [comment]
lol. I submitted the CL(my first cl) without closing it properly. Accidentally ran into this issue, so close it!

**Comment by srawlins** [comment]
Ah yes, thanks much! I see it was fixed in https://github.com/dart-lang/sdk/commit/ec86471ccc47a62df8b4009e1fb37c66ff9dc91b.
