### ISSUE TITLE
Remove --checked flag from VM

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#34660]
The VM still has a `--checked` flag. That should we removed in Dart 2.2, as we no longer have a checked mode, as announced in the Dart 2 migration docs:

https://www.dartlang.org/dart-2#migration
> Dart no longer has checked mode.
> Assert statements are still supported, but you enable them differently.

**Comment by mit-mit** [comment]
Assigning to self as this will be the test-case of our revised breaking change process.

**Comment by mit-mit** [comment]
cc @a-siva can you assign this to someone in your team to announce per the [new process](https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md) ?

**Comment by a-siva** [comment]
@mit we are removing this option correct?

**Comment by mit-mit** [comment]
Yes, I suggest so.

**Comment by mit-mit** [comment]
Did someone send the breaking change notification?

**Comment by a-siva** [comment]
No, it is documented in the changelog
