### ISSUE TITLE
Code completion: the list of names for named parameters is suggested where it is not applicable

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#34672]
Dart SDK 2.0, 2.1-dev
Code completion powered by the Analysis Server: the list of names for named parameters is suggested where it is not applicable. I believe no code completion items should be here. Example from Flutter project:
```
import 'package:flutter/material.dart';

main() {
  return AppBar (
    elevation: 0<caret>,
  );
}
```
![image](https://user-images.githubusercontent.com/4499789/46477203-cec79700-c7f2-11e8-9c82-7a3b2a289c64.png)

**Comment by bwilkerson** [comment]
I can no longer reproduce this, so I suspect that it was fixed.

**Comment by alexander-doroshko** [comment]
@bwilkerson @scheglov I'm afraid it hasn't been fixed.
It's been workarounded on the Dart plugin end with [this commit](https://github.com/JetBrains/intellij-plugins/commit/f724029e53a689bb797838dfb90998104f93e65d#diff-4d42c546ef5bfd3c644d5fff4e823b4b99b60d15448ea3c72734e2c8ced813b6R73):
```
if (isRightAfterBadIdentifier()) {
  return; // don't run completion at all
}
```

This workaround works but it potentially may prevent from adding new code completion features like, for example, numbers completion.
