### ISSUE TITLE
Async Causal Stack traces issue

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#34673]
During my gardening shift today I was looking at some flakiness on the buildbot. More specifically, the following test `service/pause_on_unhandled_async_exceptions_test` fails on optimiztation counter threshold builder. It is flaky.

It turns out the logic from [runtime/vm/debugger.cc](https://github.com/dart-lang/sdk/blob/master/runtime/vm/debugger.cc#L2230) seems to be not quite correct.

If `_AsyncAwaitCompleter.start()` gets optimized, it will inline `_Closure.call()`. This means there is one frame less on the stack. The logic in debugger.cc seems then to no longer do the right thing by skipping 2 frames.

It can be easily reproduced by:
```
out/ReleaseX64/dart --no-background-compilation --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart
```

@aam  Since you touched the code last in e71bd048e57d68c563a9ac20d9fd2e5dec8d943c, could you take a look?

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/78580 fixed this.
