### ISSUE TITLE
Report type argument after named constructor invocation as an error

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34671]
https://github.com/dart-lang/sdk/issues/34403 discusses a missing error in the CFE and analyzer for type arguments after a named constructor. The issue was fixed in the analyzer in https://dart-review.googlesource.com/c/sdk/+/73600 but downgraded to a warning in https://dart-review.googlesource.com/c/sdk/+/74560 to give people some time to fix their code. That issue now tracks the implementation of the error in the CFE.

The analyzer needs to flip the check back to being an error for Dart 2.1. Hence this issue.

**Comment by askeksa-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/78080 changes test failures for the analyzer and DDC marked with https://github.com/dart-lang/sdk/issues/34403 to this issue.

**Comment by leafpetersen** [comment]
We're working at clarifying the timing of landing this in the #34403 .

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/79382
