### ISSUE TITLE
Add analyzer info when using uninitialized variables

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#34670]
When you are coding, suppose, this:
```Dart
function() {
  String str;
  List list;
  print(str.substring(2) + list.first);
}
```
There's no warning nor anything after you execute the code (at least in VM) and you get the error of calling substring on null (being that list.first will also raise an exception, making you waste more time fixing the program)
I think there should be at least an info that you are working with null variables when the analyzer doesn't detect  some assignment that removes the null state from variables.

**Comment by bwilkerson** [comment]
It isn't clear whether users would want that enabled by default, but we could certainly add a lint for that.

**Comment by Rodsevich** [comment]
I think this is a common error that hits the majority of users (specially in Dart, where we all come from another languajes where some of them doesn't have this problem), so shouldn't it be activated by default and disable by advanced users in case they want (However I don't know for what use case)
