### ISSUE TITLE
Output divergence AOT-DebugX64 due to LICM

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#34684]
DIVERGENCE 1.1:2819010248 : KBC-INT-DebugX64 vs. AOT-DebugX64

(comparing output reveals that most agree with KBC-INT, and AOT-DebugX64 is off).

**Comment by aartbik** [comment]
Most modes agree on the following output prior to the first exception:

{0: T#0}
Infinity
true
throws RangeError (start): Invalid value: Not in range 0..2, inclusive: 73 #0      RangeError.checkValidRange (dart:core/errors.dart:320:7)
#1      List.sublist (dart:core/runtime/libgrowable_array.dart:81:22)
#2      X2.run (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:1000:54)
#3      main (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:1028:14)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

But AOT sees the exception first, in X1 already

throws RangeError (length): Invalid value: Not in range 0..3, inclusive: 36 #0      X1.run (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:0)
#1      X2.run (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:984)
#2      main (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:1028)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)

**Comment by aartbik** [comment]
Several other divergences in our nightly run found the same issue.
It looks like LICM moved something before the loop in an incorrect manner.

**Comment by aartbik** [comment]
Problem occurred due to hoisting:

v16 <- Constant(#3) T{_Smi!}
v440 <- Constant(#36) [36, 36] T{_Smi!}

B630[join]:
 ....
CheckArrayBound:4902(v16, v440)

out of the loop to

B11[join]:
 ....
 CheckArrayBound:10700(v16, v440)

**Comment by mraleph** [comment]
Reduction is below. We should prohibit LICM for `CheckArrayBound`. Note that we already prohibit bounds check generalization - which can similarly optimistically hoist `CheckArrayBound` from the loop and thus change an observable behavior of the program.

```dart
void foo(int n, int k) {
  var l = new List<int>(1);
  var j = n - 1;
  for (var i = 0; i < k; i++) {
    // CheckArrayBound would be hoisted by LICM and converted to
    // GenericCheckArrayBound.
    l[j] = 10;
  }
}

void main() {
  try {
    foo(2, 0);
  } catch (e) {
    print('Threw, but should not throw!');
  }
}
```

**Comment by aartbik** [comment]
I have a WIP fix that avoids CheckArrayBound altogether in AOT and instead only introduces GenericCheckBound where needed. This actually exposes another issue, where we hoist the load but no longer the check bound which can introduce other issues (before we hoisted the load and the check bound together). We miss the "redefinition" mechanism that should protect against such cases.

**Comment by aartbik** [comment]
Assuming the relanding sticks, the LICM bug has been resolved. Nightly [dartfuzz](https://github.com/dart-lang/sdk/tree/master/runtime/tools/dartfuzz) runs are now hopefully useful again.
