### ISSUE TITLE
[new configuration failure] standalone_2/io/dart_std_io_pipe_test

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34697]
This test is failing in a recently introduced test configuration:

```
python tools/test.py -m debug -a ia32 -n dartk-linux-debug-ia32 standalone_2/io/dart_std_io_pipe_test
```

**Comment by a-siva** [comment]
@sjindel-google this issue does not document what the failure mode was, do we have any context on this. I believe @bkonyi changed the test recently to ensure it did not timeout and I haven't seen failures after that change.
If we do not have any context about the failure I would suggest closing the issue.
