### ISSUE TITLE
Analyzer: Mixin superinvocation checking ignores `covariant` and may skip check at mixin application

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34693]
Consider the following program:

```dart
class A {
  bar(num n) {}
}

mixin M on A {
  test() {
    super.bar(3.14);
  }
}

class B {
  bar(covariant int i) { print(i.runtimeType); }
}

class C extends B with M {}

main() {
  C().test();
}
```

With `dartanalyzer` from 1a38084774030249aeff13f183134a401ebe997d, we get the following response:

```
ERROR|COMPILE_TIME_ERROR|MIXIN_APPLICATION_NOT_IMPLEMENTED_INTERFACE|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|19|24|1|The class doesn't implement the required class 'A'.
ERROR|COMPILE_TIME_ERROR|MIXIN_APPLICATION_CONCRETE_SUPER_INVOKED_MEMBER_TYPE|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|19|24|1|The super-invoked member 'bar' has the type '(num) → dynamic', but the concrete member in the class has type '(int) → dynamic'.
```

However, it is _not_ an error when the superinterfaces have a member `bar(num)` and a concrete implementation with signature `bar(covariant int)` is given, so we should not have the first error.

We _should_ have an error at the mixin application `B with M`, because that is equivalent to a class that contains (among other things) an implementation of `test` doing `super.bar(3.14)`, and for `B with M` that superinvocation will statically resolve to an invocation of `bar(covariant int)`.

That might be exactly what the second error (`MIXIN_APPLICATION_CONCRETE_SUPER_INVOKED_MEMBER_TYPE`) means, but it confuses me a bit because it should have said something like '3.14 is a `double`, which is not assignable to the declared argument type `int`', and it says something which sounds more like "you can't have a `bar(covariant int)` when the mixin thinks it'll be a `bar(num)`". That is, it sounds like the second error is actually a more detailed error about the same thing as the first error, rather than an error about not having an assignable type for an actual argument.

**Comment by scheglov** [comment]
I think that the first error (`MIXIN_APPLICATION_NOT_IMPLEMENTED_INTERFACE `) is valid, because 
`B` does not implement `A`.

**Comment by eernstg** [comment]
But `B` _does_ in fact implement `A`: The only requirement is that `B` (being concrete) must have a concrete declaration of `bar` which is a correct override of `A.bar`, and `bar(covariant int i)` will override `bar(num n)` just fine.

**Comment by scheglov** [comment]
`MIXIN_APPLICATION_CONCRETE_SUPER_INVOKED_MEMBER_TYPE` is reported on `B with M`, not on `B.bar` overriding `A.bar`.

The reason why this happens is that in Analyzer we have different rules for `FunctionType` subtyping in `isSubtypeOf()`, and for overrides in `isOverrideSubtypeOf()`. I have no idea why. Should these rules be the same? Does "is a valid override" mean the same as "is a subtype" for function types? I tried to search "valid override" in the specification PDF, but it does not use it.

**Comment by scheglov** [comment]
OK, I was enlightened that subtyping for `FunctionType`s has nothing to do with `covariant`, and this is only used for overrides (?).

https://dart-review.googlesource.com/c/sdk/+/78680 changes the check that the superclass must "have a concrete implementation of the super-invoked members compatible with the super-constraint interface" from `isSubtypeOf ()` to `isOverrideSubtypeOf ()`.

**Comment by eernstg** [comment]
> `MIXIN_APPLICATION_CONCRETE_SUPER_INVOKED_MEMBER_TYPE` is reported on `B with M`, not on `B.bar` overriding `A.bar`.

Right, but it is still not correct. In particular, the program [here](https://github.com/dart-lang/sdk/issues/34693#issuecomment-427733456) gets no error messages from `dartanalyzer` in commit 89d753588cb3f8f4557c9b2ed663039890460fb2 (2018-10-09 03:18:15 CEST), but it should have an error because `super.bar(3.14)` is a compile-time error in `B with M`.

So it looks like the override relation check in the analyzer is now taking covariance into account, which fixes one of the issues. But there is still no check of the superinvocations at each mixin application.

> Does "is a valid override" mean the same as "is a subtype" for function types?

The language specification has the following (section 'Instance Methods' resp. 'Superinterfaces'):
```
It is a compile-time error if an instance method $m_1$ overrides
an instance member $m_2$ and the type of $m_1$ is not a subtype
of the type of $m_2$.
...
It is a compile-time error if the implicit interface of a class $C$ has
an instance member $m$ of type $F$ and $C$ declares or inherits
a corresponding instance member $m$ of type $F'$ if $F'$ is not a
subtype of $F$.
```
The wording `method .. overrides .. member` goes back to 2013 and I plan to revise it, but we already specify elsewhere that we get an error if that `member` is not a method, so let's just concentrate on methods.

As you can see, the current language specification uses subtyping to make the decision. However, you already mentioned that covariant parameters do not occur in function types, so we couldn't possibly take them into account if we rely 100% on this text. So we must consult some feature specs as well.

We have [a CL](https://dart-review.googlesource.com/c/sdk/+/40080) introducing a feature specification about how to compute the interface of a class, and in particular how to disambiguate signatures which are mutual subtypes of each other. We also have the feature specs about covariant parameters ([by-keyword](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md), [from-class](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-from-class.md)), and they must also be taken into account before we have a complete picture.

So here is my view of this situation:

- Subtyping is going to give the correct answer when there are no covariant parameters and no top types.
- The override check on a covariant parameter only differs from subtyping based checks when the parameter is covariant-by-keyword, and that is specified [here](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md).
- When we have clashes like `implements I, J` where `I` has `dynamic foo()` and `J` has `Object foo()`, subtyping will not help us (they are equivalent according to the subtype relation); I have tried to get [this CL](https://dart-review.googlesource.com/c/sdk/+/40080) landed, but haven't yet gotten buy-in, so I do not think we can give a definite answer about how to disambiguate in those situations. It's basically about top types, because we have so many (`dynamic`, `void`, `Object`, `FutureOr<FutureOr<Object>>` etc.etc.), and it _does_ make a difference whether `e.foo().someNonExistingMethod(42)` is checked according to a typing of `e.foo()` as `Object` (so we get an error) or `dynamic` (where there is no error).

In short, it's not specified in one place as we would have liked, but we should have clear answers for all topics except disambiguation of top types.

I'll push on [disambiguation](https://dart-review.googlesource.com/c/sdk/+/40080) again.

> Analyzer checks when applying a mixin by checking that, for each member that
> mixin invokes from its superclass constraints,

Sounds like this is concerned with superinvocations only, as opposed to 'all invocations of instance methods on `this`'?

But it actually applies in both cases: If a mixin `M` contains code that invokes an instance member on `this` (superinvocation or not) then that invocation needs to be checked for compile-time errors. Assuming that we check each of these invocations in the body of `M` we only need to check for situations where the check in the body of `M` may not yield a valid result for a given mixin application.

One example where we need to check again at each mixin application is superinvocations, as shown in the example (the covariant parameter makes `super.bar(3.14)` a compile-time error). Another example would be a plain `bar(3.14)` or `this.bar(3.14)` in a similar situation:

```dart
class A {
  bar(num n) {}
}

mixin M on A {
  test() {
    bar(3.14); // Error location for error below.
  }
}

class B implements A {
  bar(covariant int i) { print(i.runtimeType); }
}

class C extends B with M {} //# 01: compile-time error

main() {
  C().test(); //# 01: continued
}
```

I think parameters that are covariant-by-keyword is the only mechanism which is capable of turning instance method invocations (superinvocations and invocations on `this`, implicitly or explicitly) into errors.

Of course, all kinds of other changes will turn an override (in the mixin) into an error (relative to the superclass that it is applied to), but I think that's already being checked correctly.

> there is the corresponding member
> in the superclass, and the function type of this member is a subtype of the function
> type of the member in the superclass constraint.

What we must require is that the given superinvocation or `this`-invocation does not have an error in the new setting, and it is actually not sufficient to check the subtype relation you mention (and it is also not sufficient to check that there exists any particular override relation, because `bar(covariant int i)` _does_ override `bar(num n)` correctly, and it still makes `super.bar(3.14)` a compile-time error).

So we need an additional round of checks on all these invocations at each mixin application.

> Analyzer does not actually copies
> members of M into C.

I suppose this would be an implementation concern, as long as it doesn't actually make the correct checks completely impossible.

> The fact that there was double in invocation arguments is
> not visible anywhere outside M method bodies.

True, but it still makes `B with M` and error.

> So, from Analyzer point of view
> `B.bar` has type `(covariant int) → dynamic`, which is not a subtype of `A.bar`
> with type `(num) → dynamic`. So, the error.

(I guess we agree that it should be checked according to override rules and not just subtype rules, and it  was changed to do so in https://dart-review.googlesource.com/c/sdk/+/78680).
