### ISSUE TITLE
Spec for instantiate-to-bounds defines a somewhat redundant variable that is never used

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34705]
This is a bit confusing:

> Let _T_ be a `qualified` term which denotes a generic class or                   
> parameterized type alias _G_ (*so _T_ is a raw type*), let                       
> _F<sub>1</sub> .. F<sub>k</sub>_ be the formal type                              
> parameter declarations in the declaration of _G_, with type parameters           
> _X<sub>1</sub> .. X<sub>k</sub>_ and ...

The distinction between _F<sub>n</sub>_ and _X<sub>n</sub>_ is not entirely clear to me, and it doesn't appear that _F_ is later used anywhere in the document.

Perhaps it should be removed to leave only _T_, _X<sub>n</sub>_, _G_, and _B<sub>n</sub>_.

**Comment by eernstg** [comment]
You're right, the formal parameter declarations (_F_) contain the type variable and the bound, but they are not used in the text that follows so they might as well have remained unnamed. I'll take that into account when integrating the text into the language specification dartLangSpec.tex (which is going to happen soon, anyway).

**Comment by eernstg** [comment]
Fixed in ade528c4e6f91aaeef94c1ebb5ffa06fa2d06f4e.
