### ISSUE TITLE
Some strange issue just popped up while working.

### ISSUE THREAD

**Issue by vns-aditya** [dart-lang/sdk#34706]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.3911.36`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.3911.36, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/x8/swxlnn3x45b1hz1y2m2rj2pm0000gp/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/ashwithateam/Ballebaaz/Ballebaaz/ballebaaz/lib/Profile/profileBloc.dart
Exception: Element not found in summary: dart:core

**Comment by bwilkerson** [comment]
We believe that this has been fixed on bleeding edge. Please let us know if you continue to see this after updating to a newer version of Dart.
