### ISSUE TITLE
Analyzer does not reject typedef which has a reference to itself.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34700]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10

The following test example declares a typedef which reference to itself:
```
typedef F<X extends F> = F Function();
main() {}
```
It fails in runtime with `The typedef 'F' has a reference to itself.` error message, but does not throw any error in analyzer.

I believe analyzer also should throw a compile error here.

Please see #33599 evaluation for more details.

**Comment by MichaelRFairhurst** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/76040
