### ISSUE TITLE
Super mixin. Error to call super in a mixin body

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#34711]
The following program produces an error

```dart
abstract class B {
  foo();
}

class C implements B {
  foo() {}
}

mixin M on B {
  test() {
    super.foo(); // Error: Superclass has no method named 'foo'.
  }
}

class MA extends C with M {
}

main() {}
```
According to the [super mixin spec](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) there should be no error. `super.foo()` call is allowed here

Dart VM version: 2.1.0-dev.6.0

**Comment by lrhn** [comment]
Ack, yes. The text should probably say a "statically valid invocation" because it really is only an interface check, not an actual invocation.

**Comment by kmillikin** [comment]
Mixin declarations have not "shipped" yet.  Some features will work, many will not.  Testing against 2.1.0-dev.6.0 definitely won't work.

This issue was fixed in https://github.com/dart-lang/sdk/commit/c9b05d3f1ff0ba22cc8cc2e66e2654d99609e087.
