### ISSUE TITLE
Fasta: Missing inference of type arguments on redirecting factories

### ISSUE THREAD

**Issue by dhil** [dart-lang/sdk#34714]
In redirecting factories, type arguments are not inferred on redirectees. For example, the current implementation does not infer `T` on `B` below
```dart
class A<T> {
  factory A() = B; // Should infer B<T>.
}

class B<T> implements A<T> {
  B();
}
```
Instead it "infers" `B<dynamic>` (it doesn't really infer, hence the quotes, c.f. [the responsible code](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/kernel_class_builder.dart#L298-L301)).

**Comment by eernstg** [comment]
Cf. https://stackoverflow.com/questions/52674849/using-is-to-check-runtime-type-of-dart-generic for an example where this came up.

Considering that example, it's very confusing that the analyzer includes this kind of inference (so static analysis looks like we get the right type argument), but the common front end omits the inference (so `B` above means `B<dynamic>`), and at the same time the common front end does not report an error for returning an object whose type is not a subtype of the enclosing class. So this should probably be given a high priority.

**Comment by leafpetersen** [comment]
This still seems to be an issue, I just ran into this.

**Comment by eernstg** [comment]
Awaiting conclusion in dart-lang/language#366. I just noted that everybody seems to support the approach where the omitted type arguments are inferred.

**Comment by stefantsov** [comment]
The CL in progress is here: https://dart-review.googlesource.com/c/sdk/+/147181

With the CL patched I see the following results:

```dart
// $ cat /tmp/asdf.dart
class A<X> {
  A();
  factory A.foo() = B;
}

class B<Y> extends A<Y> {
  B();
}

main() {
  print(new A<String>.foo().runtimeType);
}


// $ dart /tmp/asdf.dart
// B<String>
```

**Comment by eernstg** [comment]
A conclusion was already emerging in dart-lang/language#366, and has been confirmed: The CFE should be updated to use inference rather than instantiation to bound.
