### ISSUE TITLE
Super mixin. No error in VM if mixin application does not implement required interface

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#34712]
```dart
class A {
  String get aGetter => "A getter";
}

abstract class B {
  String get bGetter;
}

class C {
  String get aGetter => "C A getter";
  String get bGetter => "C B getter";
}

mixin M on A, B {}

class MA extends C with M {
}

main() {
  MA ma = new MA();
}
```
This code produces an error in analyzer `error - The class doesn't implement the required class 'A'` but no issue in VM. There should be an error inn VM as well because class C doesn't implement interfaces A and B and therefore `C with M` is a compile error

Dart VM version: 2.1.0-dev.6.0

**Comment by kmillikin** [comment]
Absolutely.  This feature has not shipped and is still under development.  Testing against 2.1.0-dev.6.0 will definitely not work.

**Comment by sgrekhov** [comment]
No issue on Dart VM version: 2.1.0-dev.8.0. Error now produced in analyzer and in VM. Closed
