### ISSUE TITLE
yaml file for dartfmt

### ISSUE THREAD

**Issue by StokeMasterJack** [dart-lang/sdk#34719]
It would be cool to have something like analysis_options.yaml for dartfmt.

**Comment by bwilkerson** [comment]
@munificent

**Comment by natebosch** [comment]
There aren't any options the user is intended to use for `dartfmt` other than, I think, the `--fix` options.

https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it

What do you expect should be configured?

**Comment by StokeMasterJack** [comment]
I like my closing parens on the next line:

      ButtonsView(
          isGameOver: g.isGameOver,
          onDeal: model.onDeal,
          onHit: model.onHit,
          onStay: model.onStay
      **),**

But I suppose if this is supposed to be like prettier, enforcing a style, then we should all use the same thing.

**Comment by natebosch** [comment]
FWIW you can get that behavior by using a trailing comma on the argument list.
