### ISSUE TITLE
Analyzer rejects B<X extends A<A<X>>> whereas Dart passes with this.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34726]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10

The following example declares four classes and print their types:
``` dart
class A<X extends A<X>> {}
class A1<X extends A1<A1<X>>> {}
class B<X extends A<X>> {}
class B1<X extends A<A<X>>> {}

main() {
  print(A);
  print(A1);
  print(B);
  print(B1);
}
```
Dart passes with this and prints actual types of `A`, `A1`, `B`, `B1`:
> A<A<dynamic>>
> A1<A1<A1<dynamic>>>
> B<A<dynamic>>
> B1<A<A<dynamic>>>
Seems like this is a correct result which corresponds instantiate-to-bound Spec.

However, dartanalyzer throws compile error for class `B1<X extends A<A<X>>>` here:
>   error - 'A<X>' doesn't extend 'A<A<X>>' at test.dart:4:22 - type_argument_not_matching_bounds
>   error - 'X' doesn't extend 'A<X>' at test.dart:4:24 - type_argument_not_matching_bounds
> 2 errors found.
It should pass here kike dart does.

**Comment by eernstg** [comment]
Note that there may be some overlap with #34264 (which is focusing on `FutureOr`, but otherwise similar to this one).

**Comment by iarkh** [comment]
This bug is still reproducible with the recent dart version:
Dart SDK version: 2.11.0-176.0.dev (dev) (Mon Sep 28 19:05:52 2020 -0700) on "windows_x64"

**Comment by eernstg** [comment]
Closing: Cf. https://github.com/dart-lang/sdk/issues/43687, we must get a compile-time error for the declaration of `B`, so the analyzer is behaving correctly. The common front end reports that error as well.
