### ISSUE TITLE
Fix expression evaluation when standalone vm was launched from .dill-file

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#34736]
This is carry-over from https://github.com/dart-lang/sdk/issues/33087 that was re-purposed to track work in frontend so it can be initialized from the kernel file.

Remaining work here is to enable standalone vm and its kernel-service so it can bootstrap compiler from kernel file as well. This is needed primarily to support simarm64/simdbc64 tests that are run on standalone dart vm from kernel file.

**Comment by aam** [comment]
@a-siva suggested that there are new parts of the system being built that now rely on bootstrapping kernel service from dill, therefore bumping priority of this issue.

**Comment by aam** [comment]
Priority lowered as this is _not_ on the critical path for anything new.

**Comment by alan-knight** [comment]
I note that this also means you can't evaluate expressions when debugging VM programs.

**Comment by aam** [comment]
> I note that this also means you can't evaluate expressions when debugging VM programs.

Yes, when debugging VM programs launched by standalone embedder from dill file. That scenario is still considered to be rather rare currently.

**Comment by keertip** [comment]
@aam , internally all tests are run using dill, so debugging is also done with dill files. It would be good to get this fixed soon.

**Comment by aam** [comment]
cc @rmacnak-google @ZichangG

**Comment by mraleph** [comment]
According to @jensjoha all the necessary machinery is already in place, it's just not enabled - and enabling it should be rather easy.

**Comment by jensjoha** [comment]
So it seems that I remembered wrong --- the machinery wasn't quite in place.
I have a CL ready though; it will go out for review soon.
