### ISSUE TITLE
type 'MappedListIterable<String, Project>' is not a subtype of type 'List<Project>'

### ISSUE THREAD

**Issue by akeating** [dart-lang/sdk#34733]
Moved over from https://github.com/flutter/flutter/issues/22841. Although observed in a flutter project, @zoechi is able to reproduce as a pure dart issue. 

```
$ flutter --version
Flutter 0.9.7-pre.76 • channel master • git@github.com:flutter/flutter.git
Framework • revision 6eac2d126c (15 hours ago) • 2018-10-08 19:22:20 -0400
Engine • revision 88facf4054
Tools • Dart 2.1.0-dev.6.0.flutter-c6254163dc
```

The original issue follows:

The following code appears to type-check but fails with `flutter run`:
```
final List<Project> projects = ['a', 'b', 'c'].map((name) {
    return Project(name);
});
```
and `Project`:
```
class Project {
  final String name;
  Project(this.name);
}
```

The resulting exception is:
```
I/flutter (13088): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY I/flutter (13088): The 
following assertion was thrown building Builder:
I/flutter (13088): type 'MappedListIterable<String, Project>' is not a 
subtype of type 'List<Project>'
```

```
$ flutter analyze
Analyzing flutter_app...                                         
No issues found! (ran in 1.9s)
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.7-pre.76, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.27.2)
[✓] Connected device (1 available)

• No issues found!
```

I have attached the default flutter project, modified to illustrate the problem
[main.dart.zip](https://github.com/flutter/flutter/files/2458648/main.dart.zip)

Expected: Since the code appears to type-check, the code should not fail at run-time.
Actual: The code fails at run-time.

I know that adding `.toList()` gets around this. The problem is that code that the ecosystem thinks is valid fails unexpectedly at run-time. 

I'm thinking the code should fail to type-check in this case, but interested to hear of another perspective.

**Comment by zoechi** [comment]
Moved from https://github.com/flutter/flutter/issues/22841

I expected
```yml
analyzer:

  strong-mode:
    implicit-casts: false
```
to recognize that statically, but it seems not to.

**Comment by MichaelRFairhurst** [comment]
Thanks for reporting!

Not sure what's going on, I haven't been able to get any implicit downcast warnings out of a list literal. Must be a regression.

I don't think we have good test coverage here unfortunately.

**Comment by brianegan** [comment]
Gave a thumbs up as this is a bug I run into quite often, and it would be great to get static type checking working here!

**Comment by scheglov** [comment]
There are two separate options: `implicit-casts` and `declaration-casts`. In this case actually `declaration-casts: false` is required. But... it was deprecated.

@leafpetersen and @devoncarew You added and [deprecated](https://dart-review.googlesource.com/c/sdk/+/63361/) [it](https://dart-review.googlesource.com/c/sdk/+/63641/) correspondingly. So, we don't check it anymore, and this code (I hope that it has the same problem as the original issue) should not report any static analysis errors?

```dart
main() {
  List<String> items = [1, 2, 3].map((v) => v.toString());
  print(items);
}
```

**Comment by leafpetersen** [comment]
The `implicit-casts` option should cover all casts.  If I recall correctly, the `declaration-casts` option could be added to enable declaration casts separately.  So:

```
--no-implicit-casts # no implicit casts
--no-implicit-casts --declaration-casts # declaration casts allowed, all others not
--no-declaration-casts # declaration casts forbidden, all others allowed
```

If specifying --no-implicit-casts alone no longer covers all implicit casts, I think that's a regression.
