### ISSUE TITLE
asan failure calling process_sync_test and signals_test

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#34734]
Tests reliably failing on the build farm, but not reproducible locally:

```
python tools/test.py -m release -n dartk-asan-linux-release-x64 standalone_2/io/process_sync_test
python tools/test.py -m release -n dartk-asan-linux-release-x64 standalone_2/io/signals_test
```

Both tests expect a process exit code `<0>` but got exit code `<1>`.

https://github.com/dart-lang/sdk/blob/master/tests/standalone_2/io/process_sync_test.dart#L38
https://github.com/dart-lang/sdk/blob/master/tests/standalone_2/io/signals_test.dart#L65

Builder `vm-kernel-asan-linux-release-x64`

Tests succeed without asan.

**Comment by mkustermann** [comment]
Marking as duplicate of https://github.com/dart-lang/sdk/issues/34724. These tests spawn subprocesses and the subprocesses report asan leaks, which makes the exit code probably 1 (the asan default)
