### ISSUE TITLE
Help Needed:  How to configure nginx for dart.aqueduct?

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#34731]
Hi, my aqueduct server is working on ubuntu 18.04. I install nginx from nginx.org and itself my nginx also working. Currently I don't use any block my nginx. I modified default config. My problem is that how to configure my nginx so I can use reverse proxy option so I don't connect to my aqueduct server directly. Any help please?

```

my nginx config is:
# Default server configuration
# My domain (mobile.niyazitoros.com) ip: 5.5.5.5 // TEST IP
# ------ http://mobile.niyazitoros.com  and http://5.5.5.5  is working.

server {
    listen 80 default_server;
    listen [::]:80 default_server;

       server_name mobile.niyazitoros.com;

#    root /var/www/example.com;
#    index index.html;

    location / {
# My aqueduct server works on 127.0.0.1:8888
               proxy_pass http://127.0.0.1:8888/;
    }
}
```

**Comment by zoechi** [comment]
x-link https://stackoverflow.com/questions/52717650/how-to-configure-nginx-org-as-proxy-server-for-aqueduct-server

**Comment by NTMS2017** [comment]
Ok. I found it. to I use default.conf in sites-available and sites-enabled. this was wrong place to modify default.conf. Correct path is modify default.conf in conf.d dir.

1) install nginx
2) run: 
	nginx -v  
	(nginx version: nginx/1.15.5)
3) sudo nano /etc/nginx/conf.d/default.conf

	server {
		listen 80;
        	listen [::]:80;

        	error_log    /var/log/nginx/your_domain_name.error.log debug;
        	rewrite_log on;

        	server_name your_domain_name;

        	location / {
                	proxy_pass http://127.0.0.1:8888/;
		}
	}


4) sudo systemctl reload nginx
5) sudo systemctl restart nginx
6) sudo nginx -t
7) curl http://your_domain_name/
