### ISSUE TITLE
first app

### ISSUE THREAD

**Issue by mcanikhilprajapati** [dart-lang/sdk#34743]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by bwilkerson** [comment]
What was the problem you experienced or feedback you wanted to provide?

**Comment by stereotype441** [comment]
I'm closing this issue since we haven't heard a response. @mcanikhilprajapati, please feel free to reopen if you see this issue again and can capture additional info.
