### ISSUE TITLE
[snapshot] Failed to generate snapshot

### ISSUE THREAD

**Issue by 6643** [dart-lang/sdk#34756]
```
$ dart --version
Dart VM version: 2.1.0-dev.7.0 (Unknown timestamp) on "linux_x64"
```

```
$ cat main.dart 
import 'dart:io';

main(List<String> args) {
  print(args);
  HttpServer.bind(InternetAddress.anyIPv4, 2018).then((server) {}).catchError(print);
}
```

```
$ dart --snapshot=main.dart.snapshot --snapshot-kind=app-jit main.dart
[]
^C
```

Execute first and then produce a snapshot?
Why do I need to run the program? The previous version did not need to run and the snapshot was successful.

**Comment by natebosch** [comment]
The program will run when using `--snapshot-kind=app-jit`, this has been the case since that snapshot kind was introduced. The VM executes the program in order to get some JIT optimizations. You can use `--snapshot-kind=script` to get a snapshot built without running the program.

**Comment by 6643** [comment]
@natebosch 

```
$ dart --snapshot=main.dart.snapshot --snapshot-kind=script main.dart 
Unrecognized value for snapshot_kind: 'script'
Valid values are: none, kernel, app-jit
```
Are you sure you have this parameter?
I have a snapshot generated by the previous version, 3.5M file, which is generated by app-jit method.

**Comment by natebosch** [comment]
Ah I had the name wrong. It should be `--snapshot-kind=kernel`.

If you have a file generated with `app-jit` then it was generated while running the program, which is a great way to do it when possible.
