### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by nahuelcabrera** [dart-lang/sdk#34754]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1440x900`

# Exception

Please append the contents of:
file://C:\Users\Nahuel\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Nahuel\code\wupper\lib\app\page\planner\planner_page.dart
Exception: Element not found in summary: package:wupper/app/page/planner/planner_page.dart

**Comment by bwilkerson** [comment]
We believe that this has been fixed in the bleeding edge builds. Please let us know if you see the issue again after updating to the next dev or stable build.
