### ISSUE TITLE
Remove support for enableSuperMixins from analyzer and server

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#34764]
There should not be any way to enable the old mixin support.

**Comment by bwilkerson** [comment]
@leafpetersen @dgrove To confirm that this is a P1.

**Comment by leafpetersen** [comment]
Yes.  As soon as the PR moving flutter to the new syntax lands, we should remove this, unless @keertip  has any concerns about internal code.

**Comment by keertip** [comment]
That should be fine, no issues.

**Comment by bwilkerson** [comment]
@leafpetersen I have a CL to remove support for enableSuperMixins, but it's failing on the bots. Turns out that we have a number of tests, like sdk/tests/language_2/mixin_super_test.dart, that have "SharedOptions=--supermixin" embedded in them. Should we delete all such tests?

**Comment by leafpetersen** [comment]
It's probably worth trying to convert them to the new syntax.  If it's not too much work, mark them globally skip, and assign me a bug to triage them for conversion?

**Comment by bwilkerson** [comment]
Marked as skipped by https://dart-review.googlesource.com/c/sdk/+/79475

Issue for conversion: https://github.com/dart-lang/sdk/issues/34781

**Comment by dgrove** [comment]
Any updates on this? @bwilkerson @stereotype441

**Comment by bwilkerson** [comment]
Keerti asked me to hold off until Flutter had rolled internally in order to ensure that we didn't block internal rolls of critical fixes. The CL is still green and can be landed fairly quickly.

**Comment by vsmenon** [comment]
Can we close this yet?  Did it all land?

**Comment by bwilkerson** [comment]
Yes, it landed, but it caused some breakages. There was discussion yesterday, continuing into this morning, about whether we could fix those breaks quickly enough or whether we'd need to roll it back.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/79469

We can re-open if it needs to be reverted.
