### ISSUE TITLE
make it illegal to register service extensions in release builds

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#34761]
ServiceExtensions are only exposed if the Observatory is included in the build. Observatory is not included in release builds, so registering ServiceExtensions in release builds never makes sense.

Please see document [https://docs.google.com/document/d/13JlgvliCn5sWwT2K2SfDwD1NhEfxpJH9DCf22gZZru8/edit?ts=5bbf76c3](url)

**Comment by rmacnak-google** [comment]
-1. Product mode does and should make use of dart:developer no-ops, not errors.
