### ISSUE TITLE
[snapshot-kind=app-jit] Doesn't support asynchronous?

### ISSUE THREAD

**Issue by 6643** [dart-lang/sdk#34771]
```
$ dart --version
Dart VM version: 2.1.0-dev.7.0 (Unknown timestamp) on "linux_x64"

```
```
$ cat main.dart 
import 'dart:async';

main(List<String> args) {
  print(args);
  Future.delayed(Duration(days: 1), () {
    print('snapshot?');
  });
}
```

```
$ dart --snapshot=main.dart.snapshot --snapshot-kind=app-jit main.dart
[]
^C
```

I have a file with a previous snapshot.
I am pretty sure that this app is in a previous version, the app-jit snapshot was successful.
Now it has failed. At that time, the snapshot does not need to run the script.

**Comment by rmacnak-google** [comment]
Did you mean use such a long time as `days: 1`? This works for me when I change it to a few seconds.
