### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#34782]
Flutter currently relies on log messages to discover the Dart observatory port, which isn't always reliable (particularly on iOS devices where you can't reliably retrieve older log messages).  We're looking at implementing an mDNS based solution to advertise the port and host name of the server, but it would be nice if this was available through the SDK, and could be used in other use cases on more platforms.

It looks like Dartino had done some of this work here: https://github.com/dartino/sdk/tree/master/pkg/mdns

**Comment by a-siva** [comment]
Can this be done as a package instead of being integrated into dart:io

**Comment by dnfield** [comment]
Started porting Dartino package here: flutter/packages/pulls/7
