### ISSUE TITLE
Unexpected mixin desugaring when there are more than 2 superclass constraints

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34783]
The commit message for c9b05d3f1ff0ba22cc8cc2e66e2654d99609e087 explains that a mixin declaration like this:
```dart
mixin M on S0, S1 {...}
```
now gets desugared by the front end to:
```dart
abstract class _M&S0&S1 implements S0, S1 {}
abstract class M extends _M&S0&S1 {...}
```
based on the motivation that the superclass constraints `S0` and `S1` should be treated symmetrically.

I would have expected this to generalize to three superclass constraints in a way that was manifestly symmetrical, e.g. I would have expected this mixin declaration:
```dart
mixin M on S0, S1, S2 {...}
```
to get desugared to:
```dart
abstract class _M&S0&S1&S2 implements S0, S1, S2 {}
abstract class M extends _M&S0&S1&S2 {...}
```
but instead it seems to get desugared to:
```dart
abstract class _M&S0&S1 implements S0, S1 {}
abstract class _M&S0&S1&S2 implements _M&S0&S1, S2 {}
abstract class M extends _M&S0&S1&S2 {...}
```

Is this intended behavior?  I'm not sure if this will have any user-visible effect (e.g. unintended compile-time errors), but it seems like it risks making back-end development more complex.

@kmillikin @jmesserly @stefantsov

**Comment by kmillikin** [comment]
This behavior is intentional.  This is (obviously?) a transitional encoding.  Will we ever change it?  Probably soon.
