### ISSUE TITLE
Create "analyzer" branch and set up build bots

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34780]
The analyzer team would like to begin doing development work in a branch called "analyzer" so that high risk changes can have time to be thoroughly vetted before being released to master.  The following infrastructure work is needed:

- [x] Create the branch "analyzer" in the repo https://github.com/dart-lang/sdk
- [x] Ensure that the analyzer team has push access to the branch
- [x] Set up new bots to run on the branch
  - [x] analyzer-analysis-server-linux
  - [x] analyzer-linux-release
  - [x] analyzer-mac-release
  - [x] analyzer-win-release

Note that the existing bots should not be removed--we still need analyzer coverage on the master branch.

Thank you!

**Comment by athomas** [comment]
Branch is created, you should also have push access. @stereotype441, can you verify and check the box if it works?

**Comment by stereotype441** [comment]
Verified that I have push access, thanks!

**Comment by athomas** [comment]
https://ci.chromium.org/p/dart/g/analyzer/console

**Comment by athomas** [comment]
We also need to update the test matrix to make the new builders work, I'll do that now.

**Comment by athomas** [comment]
The builders are green now.
