### ISSUE TITLE
Encountered Dart error while switching Flutter channel from `master` to `beta`.

### ISSUE THREAD

**Issue by relativityboy** [dart-lang/sdk#34788]
*Reporting because the code asked me to.*

* Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
* MacOSX
* Android Studio (rebuilding flutter)

```
Downloading Dart SDK from Flutter engine 74625aed323d04f2add0410e84038d250f51b616...

...
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
D/        (17320): HostConnection::get() New Host Connection established 0xaad8f980, tid 17359
D/EGL_emulation(17320): eglMakeCurrent: 0xafef43c0: ver 3 0 (tinfo 0xaad92b10)
```

**Comment by zoechi** [comment]
Have you tried `flutter clean`?

**Comment by relativityboy** [comment]
I hadn't. As this is exploratory work, I've been keeping most of my work in git. I resolved my issue by doing a `reset --hard`.  Wish I were in a position to provide more educated debugging info.

**Comment by zoechi** [comment]
`reset --hard` in your project or in the Flutter install dir?

Can this issue be closed then?

**Comment by relativityboy** [comment]
In my project dir.

I have no attachment to this issue. Close if you like. As per above, I only reported it because the software told me to. :)

**Comment by a-siva** [comment]
Closing issue per comment above.
