### ISSUE TITLE
Find a way to do less copying when sending large typed data

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34796]
When sending a large typed data through a message port, there is an optimization to convert it to an external typed data (https://github.com/dart-lang/sdk/blob/f3c51a4be043e91c61e7662ecb4a24e00d2f87f6/runtime/vm/raw_object_snapshot.cc#L1945-L1961) to avoid copying on the receiver side. This morphs object from one type to another, which causes problems https://github.com/flutter/flutter/issues/22796, https://github.com/dart-lang/sdk/issues/34752.

As a workaround to these problems, the optimization of converting typed data to external will be put under a flag and disabled by default. However, we still need to find a way to do less copying when sending large amount of data through message ports, preferably without morphing object types.

**Comment by hooluupog** [comment]
If Dart isolate support transferable Data. [#4149](https://github.com/dart-lang/sdk/issues/4149)

**Comment by mraleph** [comment]
Note that transferrables on the Web are implemented by externalizing typed arrays behind the scenes. This is the kind of implementation we want to avoid, because it introduces the problem that type of the object changes dynamically: you take a normal typed array and send it to another worker - it suddenly becomes an empty typed array on the sender side.

**Comment by alexmarkov** [comment]
Maybe we can introduce transferable typed data as separate classes (they could be private in dart:typed_data), created with separate public factory constructors (e.g. Int8List.transferable(int length)). Unlike other typed data classes, transferable could have a mutable length (if needed), or an extra flag indicating that contents was moved to another isolate and should not be accessed anymore. This way it will be possible to avoid both extra copying and dynamic changes of object types.

The only culprit is that users will need to change their code and use the new API to create transferable typed data.

/cc @aam

**Comment by yjbanov** [comment]
> you take a normal typed array and send it to another worker - it suddenly becomes an empty typed array on the sender side

Why is this a problem?

**Comment by matanlurey** [comment]
You could just "0-out" the array, instead of clearing all elements, right?

**Comment by yjbanov** [comment]
> we can treat type array length as a constant value

Ah, nice! Didn't know you did that.

> You could just "0-out" the array, instead of clearing all elements, right?

That's is as bad as copying :)

**Comment by matanlurey** [comment]
FWIW, in AOT mode, it might be reasonable to segfault if you attempt to access a typed array that has been transferred. In JIT mode you could throw an exception? I don't know if that makes sense, but I imagine the number of folks that will be using transferable arrays is rather small, and it is probably OK to give them undefined behavior if you transfer the array and then try to use it.

**Comment by yjbanov** [comment]
> it might be reasonable to segfault if you attempt to access a typed array that has been transferred

That means inserting a check before every access to a typed array. Since typed arrays tend to be used in performance-critical parts of the code, I'd try to avoid adding checks.

**Comment by matanlurey** [comment]
Oh, I mean don't insert a check, and let the program just crash :)

**Comment by yjbanov** [comment]
> Oh, I mean don't insert a check, and let the program just crash :)

The thing is, it won't crash. Because the memory is not copied/moved anywhere, it's still there. So the crash is not guaranteed to happen predictably.

**Comment by matanlurey** [comment]
Hmm. Could the pointer to the array be pointed to a null location, or something? 💥

**Comment by rmacnak-google** [comment]
TransferableTypedData was introduced.
