### ISSUE TITLE
Ship dartfix via pub global activate

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34792]
We should plan to ship `dartfix` via `pub global activate`. That likely means:
- [x] moving the tool to its own project directory https://github.com/dart-lang/sdk/issues/34765
- [x] making sure that its deps only include published packages https://github.com/dart-lang/sdk/issues/34793

cc @danrubel

**Comment by devoncarew** [comment]
Done (or, close to done)?

**Comment by danrubel** [comment]
`dartfix` is now published
