### ISSUE TITLE
have dartfix only depend on published packages

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34793]
Dartfix currently depends on a few non-published packages (it looks like specifically just `pkg/analysis_server/`).

We should refactor it so that it doesn't depend on non-published packages, so that dartfix itself can be published.

It looks like the use of `pkg/analysis_server/` is just for the JSON communications; if that's the case, we can move to using a package like `package:analysis_server_lib` (https://pub.dartlang.org/packages/analysis_server_lib).

**Comment by bwilkerson** [comment]
I had originally expected / intended analysis_server_client (in sdk/pkg) to fulfill that roll. It has the advantage that it can easily be kept consistent with changes to server. In either case, we should consolidate and have a single package to support Dart-based clients that use server's APIs.

**Comment by danrubel** [comment]
Both `analysis_server_client` and `dartfix` are now published.
