### ISSUE TITLE
Devcompiler's Object.toString doesn't match other platforms.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34807]
If you do 
```dart
class C {}
main() {
 print(C());
}
```
other platforms print `[Instance of 'C']`, but dartdevc prints `Instance of 'C'` without the braces. I'm guessing this is the JS `Object.prototype.toString` behavior, but it is inconsistent.
If anyone depends on the format (which they obviously shouldn't since it isn't specified, but when has that ever stopped anyone) then they get different results in the dev-compiler.

(This was tested with `dartdevk`, the same test file failed for a different reason (#34806) with dartdevc).

**Comment by jmesserly** [comment]
FYI, it's not calling JavaScript toString. DDC just has an older copy of the SDK impl code (originally from dart2js), so it's defined in our core_patch.dart file as:

```dart
  @patch
  String toString() =>
      "Instance of '${dart.typeName(dart.getReifiedType(this))}'";
```
Easy fix. :)

**Comment by jmesserly** [comment]
errr, I'm confused... other impls like Dart VM/dart2js seem to also print it without the brackets. I get the same output. Was there a different repro for this?

**Comment by lrhn** [comment]
I'm confused too. I can't see any change to the other platforms' behavior, and yet they now all print without square brackets. Maybe I was seeing things?

So, everything is fine. Keep up what you are doing! :)
