### ISSUE TITLE
Dart Analyzer Error - Android Studio . probably because of $ sign in String

### ISSUE THREAD

**Issue by levyitay** [dart-lang/sdk#34801]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/yn/xq1_21cs5f35w4gbp5c94sf00000gn/T/report.txt
[report.txt](https://github.com/dart-lang/sdk/files/2480693/report.txt)

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/itayl/workspace/flutter_login/lib/DBHelper.dart
Element mismatch in /Users/itayl/workspace/flutter_login/lib/DBHelper.dart at class DBHelper
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by devoncarew** [comment]
Thanks for the report! This looks like a dup of https://github.com/dart-lang/sdk/issues/34721.
