### ISSUE TITLE
Super mixin. Factory constructor issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#34804]
Now, if mixin declares factory constructor then it is an error in analyzer but no error in VM. Example

```dart
class S {}
class T {}

class I {}
class J {}

class B {}
class C {}

mixin M<X extends S, Y extends T> on B, C implements I, J {
   factory M() {} // In analyzer error • Mixins can't declare constructors
}

class A implements B, C, I, J {}

class MA extends A with M {}

main() {
   new MA();
}
```
According to the discussion in a https://github.com/dart-lang/sdk/issues/24767 factory constructors should be allowed. From other hand, the feature specification reads: 
`The mixinMember production allows the same instance or static members that a class would allow, but no constructors (for now).`

So it's unclear now are factory constructors allowed or not, but anyway analyzer and VM should produce the same result

Dart VM version: 2.1.0-dev.7.1

**Comment by lrhn** [comment]
Factory constructors are not allowed in `mixin` declarations. It is not a class declaration, and the feature specification is unambiuous.

It's not technically impossible to allow factory constructors, we have just chosen not to do so.

So,, this is a missing front-end error.
