### ISSUE TITLE
URLs: Uri.parse & Uri.https

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#34810]
I'm trying to parse a URL generated by pacakge:oauth2 an example of the URL is:
```
http://localhost:9000/#/facebook?code=foobar#_=_#_=_
```

if I use Uri.parse I get a `FormatException` as it doesn't like the `#` in the query parameter. I've been informed that I need to use `Uri.http` or `Uri.https` but this requires me to parse the URL myself in to the authority, path & parameter components, esentially implemented my own Uri.parse function.

Am I misunderstanding or is this correct? 

I really think that `Uri.parse` should support all http & https or perhaps there could be `Uri.parseUrl`?

**Comment by lrhn** [comment]
The currently released Dart is following the URI grammar from RFC 3986 and requires the URI to not have URI "general delimiters" in wrong places. The grammar for URIs does not allow `#` to occur more than once ([https://tools.ietf.org/html/rfc3986#section-3.5] does not allow `#` as a character in the fragment), so all but one of them would need to be escaped as `%23`.

The newest dev-release of Dart is more lenient wrt. general delimiters, and will parse the above URI the same way as
```
http://localhost:9000/#/facebook?code=foobar%23_=_%23_=_
```

So, this is fixed, but has not been released in a stable version yet.
