### ISSUE TITLE
invalid_use_of_protected_member breaks flutter

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#34819]
info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/cupertino/segmented_control.dart:125:52 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/cupertino/slider.dart:82:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/cupertino/switch.dart:69:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/checkbox.dart:86:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/checkbox_list_tile.dart:112:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/chip.dart:244:48 • invalid_use_of_protected_member
   info • The member 'build' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/feedback.dart:28:22 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/radio.dart:80:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/radio_list_tile.dart:129:41 • invalid_use_of_protected_member
   info • The member 'didChangeDependencies' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/scaffold.dart:972:24 • invalid_use_of_protected_member
   info • The member 'didChangeDependencies' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/scaffold.dart:975:44 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/slider.dart:145:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/switch.dart:110:41 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/material/switch_list_tile.dart:108:41 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/rendering/binding.dart:252:30 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/rendering/sliver.dart:631:47 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/rendering/sliver.dart:637:65 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:55:48 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:296:70 • invalid_use_of_protected_member
   info • The member 'initState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:416:70 • invalid_use_of_protected_member
   info • The member 'didChangeDependencies' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:417:40 • invalid_use_of_protected_member
   info • The member 'build' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:418:31 • invalid_use_of_protected_member
   info • The member 'build' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:418:58 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/async.dart:429:12 • invalid_use_of_protected_member
   info • The member 'deactivate' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/automatic_keep_alive.dart:265:25 • invalid_use_of_protected_member
   info • The member 'deactivate' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/automatic_keep_alive.dart:300:40 • invalid_use_of_protected_member
   info • The member 'build' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/binding.dart:615:27 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/binding.dart:615:47 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/widgets/binding.dart:620:30 • invalid_use_of_protected_member
   info • The member 'dispose' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/binding.dart:644:37 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/binding.dart:723:35 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/debug.dart:36:19 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/debug.dart:50:56 • invalid_use_of_protected_member
   info • The member 'performLayout' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/widgets/framework.dart:4327:44 • invalid_use_of_protected_member
   info • The member 'invokeLayoutCallback' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/widgets/framework.dart:4332:19 • invalid_use_of_protected_member
   info • The member 'didChangeDependencies' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/image.dart:39:12 • invalid_use_of_protected_member
   info • The member 'lerpTo' can only be used within instance members of subclasses of 'package:flutter/src/painting/decoration.dart' • packages/flutter/lib/src/widgets/implicit_animations.dart:58:29 • invalid_use_of_protected_member
   info • The member 'lerpFrom' can only be used within instance members of subclasses of 'package:flutter/src/painting/decoration.dart' • packages/flutter/lib/src/widgets/implicit_animations.dart:59:24 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/notification_listener.dart:117:71 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/overlay.dart:47:17 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/overlay.dart:102:19 • invalid_use_of_protected_member
   info • The member 'didChangeDependencies' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/routes.dart:1072:14 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/scroll_notification.dart:74:45 • invalid_use_of_protected_member
   info • The member 'dispose' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' • packages/flutter/lib/src/widgets/scroll_position.dart:517:14 • invalid_use_of_protected_member
   info • The member 'describeSemanticsConfiguration' can only be used within instance members of subclasses of 'package:flutter/src/rendering/object.dart' • packages/flutter/lib/src/widgets/scrollable.dart:552:19 • invalid_use_of_protected_member
   info • The member 'initServiceExtensions' can only be used within instance members of subclasses of 'package:flutter/src/foundation/binding.dart' • packages/flutter/lib/src/widgets/widget_inspector.dart:927:23 • invalid_use_of_protected_member

**Comment by rmacnak-google** [comment]
Suppressing this requires an "error" exclusion rather than a "lint" exclusion, which is also a bug. "protected" is not part of the language.

**Comment by matanlurey** [comment]
@rmacnak-google: These are "info", not "error". Flutter is failing the build on _all_ analysis hints, so you might want to talk to @Hixie or folks who manage Flutter, not the SDK/analyzer folks here.

**Comment by bwilkerson** [comment]
This was fixed in https://github.com/dart-lang/sdk/commit/20f43499516994018f6ce290f8054b4cd2da44ce
