### ISSUE TITLE
dart:collection add fromEntries ctor to HashMap

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#34818]
Dart version: 2.x

It'd be nice if we had an entries ctor here just like Map – not a breaking change

CC @lrhn

**Comment by lrhn** [comment]
Definitely possible, and simple. It will literally be 
```dart
factory HashMap.fromEntries(Iterable<MapEntry<K, V>> entries) => HashMap()..addEntries(entries);
```
