### ISSUE TITLE
INVALID_USE_OF_PROTECTED_MEMBER is reported in documentation comments

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#34816]
This causes build failures.

https://github.com/flutter/flutter/pull/23130/checks?check_run_id=23921607

**Comment by scheglov** [comment]
CL for review https://dart-review.googlesource.com/c/sdk/+/80267

**Comment by scheglov** [comment]
Fixed.

**Comment by devoncarew** [comment]
Note that we'll need to revert part of https://github.com/flutter/flutter/pull/23130/files when the fix for this lands in Flutter.
