### ISSUE TITLE
JSC_DUPLICATE_OBJECT_KEY exception when running dart2js output through Google Closure Compiler

### ISSUE THREAD

**Issue by graphicbeacon** [dart-lang/sdk#34820]
Hello Dart team :)

This is happening with **Dart SDK Version `2.0.0`** on **MacOSX**.

I am experiencing the exception below when attempting to run the compiled output through Closure Compiler at https://closure-compiler.appspot.com/home:

```
JSC_DUPLICATE_OBJECT_KEY: Object literal contains illegal duplicate key "gam", disallowed in strict mode at line 1014 character 0
gam:function(){return this}},
^
```

Doing a search in the compiled output shows the duplicate `gam` keys:

```js
gam:function(){return this},
$isag:1,
gam:function(){return this}},
```

**Any ideas on how to proceed with this?** 

_I'm testing this out as I remember @sethladd stating in a past video suggesting you could improve the output by running through the closure compiler. Is this still the case?_ Thank you so much

_Im blogging on Dart at [DEV.to](https://dev.to/graphicbeacon)_

**Comment by matanlurey** [comment]
I think any recommendation to use Closure Compiler _with_ Dart2JS is very outdated. Dart2JS already has implementation details similar to JSC (tree-shaking, optimizations) with specifics to Dart. As such, I can't imagine anyone will work on making JSC compatible with Dart2JS outputs.
