### ISSUE TITLE
IntelliJ auto complete suggestions for non imported classes not working as expected "as you type"

### ISSUE THREAD

**Issue by thefuzzyorange** [dart-lang/sdk#34829]
IntelliJ with Dart plugin does not show suggested imports for packages "as you type" when you declare a class that has not yet been imported in the file.

![image](https://user-images.githubusercontent.com/632669/47062865-d0249680-d1d8-11e8-87a4-25d5c043e0d8.png)

If however you fully type the class, cancel the auto suggest, then ALT+ENTER you get suggested import
![image](https://user-images.githubusercontent.com/632669/47062889-f4807300-d1d8-11e8-98bc-c59f27efdd07.png)

The auto complete suggestion works if you declare a new instance of the class though
![image](https://user-images.githubusercontent.com/632669/47062837-a5d2d900-d1d8-11e8-9553-71daa3234bd6.png)

This behavior applies to any packages be they from dart sdk, external packages referenced in pubspec.yaml, even classes in different files in the same project.

Coming from using IntelliJ for Java dev, I am so used to just typing the first few letters and having access to all glorious possible suggestions that the way this works in Dart makes coding feel cumbersome as now you have to know the exact entire name of the class you want to import and when you don't you have to go look at the name of the class inside the package you want and then paste it in at which point you might as well copy the package path and declare an import for that.

![image](https://user-images.githubusercontent.com/632669/47062967-6c4e9d80-d1d9-11e8-88eb-f58295955537.png)

It would be a huge improvement to the coding experience if it could work like Java... possible?

----
Dart VM version: 2.1.0-dev.6.0.flutter-2aac05fe10 (Fri Sep 28 16:29:23 2018 +0000) on "linux_x64"

**Comment by zoechi** [comment]
Is this a dup of #25820?

**Comment by thefuzzyorange** [comment]
Yes looks like the same thing, Perhaps we should repost the contents in #25820 as maybe the visuals paint a better picture of how the behaviour works for Java vs Dart>?

**Comment by alexander-doroshko** [comment]
Server-side of this feature is tracked as #25820.
IntelliJ's part is tracked as https://youtrack.jetbrains.com/issue/WEB-23646. 
Both are fixed now. @a-siva could you close this issue? (I don't have permissions)
