### ISSUE TITLE
Dart Analyzer: Simple Repro -> Freeze

### ISSUE THREAD

**Issue by mwalkerwells** [dart-lang/sdk#34822]
The following code causes the analyzer to freeze...

MacOS / Dart 2.1.0-dev.7.1.flutter-ac6d4f7e65

Also repro'd with the Dart SDK packaged with Flutter v0.9.4.

```dart
class Foo<T> {}

class Bar {
  Foo<NotDeclared<>>;
}
```

**Comment by bwilkerson** [comment]
@danrubel @scheglov I'm guessing that this is related to #34850

**Comment by scheglov** [comment]
Yes, I agree that this is duplicate of #34850
