### ISSUE TITLE
Completion improvement: "final FooBar |" should yield "_fooBar"

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#34821]
Let's say I start typing in the following field:

"final FooBar "

90% of the time, I want to name this "_fooBar".

If I type in "f", IntelliJ will offer to autocomplete it as "fooBar". However, these types of fields are usually private. If I type in "_f", IntelliJ doesn't offer any autocomplete suggestions. I would expect that "_fooBar" be offered as soon as I type in "_".

**Comment by bwilkerson** [comment]
I thought we determined that this was _not_ being done by server, but is actually added by the clients. Is this actually being done in server?

**Comment by jwren** [comment]
I believe I added it myself, it is part of the completion service.  `final AaaBbbCcc |`, includes the completion `aaaBbbCcc`, but not `_aaaBbbCcc`.

**Comment by jwren** [comment]
Found the file: .../dart-sdk/sdk/pkg/analysis_server/lib/src/services/completion/dart/variable_name_contributor.dart

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/80362

**Comment by stereotype441** [comment]
@jwren I see that the CL landed.  Can this issue be closed?

**Comment by jwren** [comment]
Yes, it should be fixed in master, closing.

**Comment by jwren** [comment]
Yes, it should be fixed in master, closing.

**Comment by jwren** [comment]
Yes, it is fixed in the master branch, closing.
