### ISSUE TITLE
default toString on generic class is inconsistent with instance.runtimeType (and wrong)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#34827]
See repro below.

`runtimeType` is correct - `Pair<int>`.

The default `toString` is very wrong - `Instance of 'Pair<Duration'`.

A caching issue?

Reproduces on the SDK at 2.1.0-dev.7.0 and ~recent commit fade5f33f05f2fe82bee8c04b895ab80a5f35ff9

Does not reproduce on DartPad.

```dart
class SomeClass<N, E> {
  Pair<N> get value => Pair<N>();
}

class Pair<T> {}

void main() {
  final graph = SomeClass<int, Duration>();

  var item = graph.value;

  print(item.runtimeType);
  // prints `Pair<int>` - expected
  print(item);
  // prints `Instance of 'Pair<Duration>'` – NOT expected
}
```

**Comment by kevmoo** [comment]
CC @a-siva

**Comment by kevmoo** [comment]
@mraleph ?

**Comment by mraleph** [comment]
Should be fixed by this: https://dart-review.googlesource.com/c/sdk/+/81561. Sorry for the delay.
