### ISSUE TITLE
Sources stripped in vm_platform_strong.dill

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#34832]
In e70a7aab8a60 the source was stripped from "vm_platform_strong.dill", but no other mechanism was created for getting the source.

The means that if I for instance has "break on uncaught exception" enabled, and get an "Index out of range" exception in, say, a List, I'm greeted with the message `<source not available>`.

Equivalently if I have code like this where I mix something in from the sdk:
```
import 'dart:collection';

main() {
  Foo foo = new Foo();
  foo.add(42);
  Iterator<int> i = foo.iterator;
  while(i.moveNext()) {
    print(i.current);
  }
}

class Foo extends Object with ListMixin<int> {
  @override
  int length = 4;

  @override
  int operator [](int index) {
    return 42;
  }

  @override
  void operator []=(int index, int value) {}
}
```
and I step into for instance `add` and keep stepping, I get several pauses at
```
_Foo&Object&ListMixin.add ( list.dart:260:3 )
No source
```

To me - at least - this seems like a bad trade-off. Saving 2.5 MB is nice, but regressing the debugging experience and the "debuggability" is going in the wrong direction.

/cc @a-siva @rmacnak

**Comment by jensjoha** [comment]
Update: Actually the functionality went away with 76470aca476c40e1e7a7ee50037e85f0a20945d2.

**Comment by jensjoha** [comment]
Oh, and because fasta loads the thing when compiling, it also gives worse error messages on compile time errors, e.g. 
```
myfile.dart:2077:14: Error: Can't declare a member that conflicts with an inherited one.
  static int hashCode(String key) {
             ^
org-dartlang-sdk:///runtime/lib/object_patch.dart:1: Context: This is the inherited member.
```
notice how the "This is the inherited member." is empty...

**Comment by john-reid-1000** [comment]
> @john-reid-1000, thanks for the comprehensive report! The vm currently does not return sources for dart: libraries. We do think we should restore that ability; the best place to track that work is likely #34832.
> 
> cc @bkonyi

That's great, thanks @devoncarew, is source stripping for dart: something I can disable if I build from source?

This should should definitely be disabled by default in my opinion. Is there any reason that this cannot be enabled/disabled for each debug session? or are the dart: libraries bundled into the vm binary or something?

**Comment by devoncarew** [comment]
We re-worked our toolchain over the last few years. The dart sdk source files are pre-compiled into what we call kernel files that ship as part of the sdk. The dart: sources are just not available to the VM in the way that they were before. We'll have to either add the source to the kernel files at compile time, or make a source archive file available to the VM, in order for it to return sources to debugger clients.

This isn't something you can re-enable with a flag unfortunately...

**Comment by a-siva** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/93375
