### ISSUE TITLE
Calls from native code to Dart code through the API do not perform type-checks

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34834]
Consider:

```dart
class C {
@pragma("vm:entry-point")
int foo(int x) => x;
}
```

Native code can call `foo` since it is marked as an entry-point. However, we are responsible for checking that the argument types are respected by native code. Currently, the TFA optimization will mark `foo` as `hasDynamicUses=false`, and we will not check any parameters to `foo`.

We need to fix three things:
1. TFA needs to mark entry-points with the Kernel metadata flag `hasDynamicUses`.
2. The native API needs to treat native calls as dynamic calls, by using the DIF (`dyn:foo` in this example).
3. We need to add support for creating DIFs for static methods, which cannot by invoked dynamically from normal Dart code.

**Comment by sjindel-google** [comment]
@mraleph @alexmarkov
 
@bkonyi I heard you were fixing related bugs in this area?

**Comment by alexmarkov** [comment]
Do we really need to treat calls through native Dart API as dynamic? Native Dart API is inherently unsafe, so we could require from users of Dart API to guarantee type safety, omitting all checks in these cases. As a safety precaution, we could do type checks as assertions in debug mode in Dart API implementation. This is potentially more efficient (but less safe) than treating these calls as dynamic.

Also, this issue looks duplicate to https://github.com/dart-lang/sdk/issues/32231.

**Comment by sjindel-google** [comment]
> Do we really need to treat calls through native Dart API as dynamic? Native Dart API is inherently unsafe, so we could require from users of Dart API to guarantee type safety, omitting all checks in these cases. As a safety precaution, we could do type checks as assertions in debug mode in Dart API implementation. This is potentially more efficient (but less safe) than treating these calls as dynamic.
> 
> Also, this issue looks duplicate to #32231.

 Yeah, I agree there's a tradeoff. It's a question of whether users of our native API need more or less guardrails. @mraleph , what are your thoughts?

For the record, we've already added this type-check to `Dart_SetField`, so we're currently in an inconsistent state.

**Comment by a-siva** [comment]
I believe [dart-lang/9f00eec55b](https://github.com/dart-lang/sdk/commit/9f00eec55b) added type checking to Dart_Invoke calls too.

**Comment by bkonyi** [comment]
@sjindel-google, @a-siva is right. I added type checks to both `Dart_Invoke` and `Dart_SetField`, so there shouldn't be any more work needed there.

**Comment by a-siva** [comment]
@bkonyi and @sjindel-google,  can this issue be closed
