### ISSUE TITLE
provide support for migrating double literals to int literals

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34835]
This would change double literals to int where legal. Possibly only for Flutter UI code?

So, `8.0` would change to `8` (and, the analyzer and CFE would then convert back to `8.0` at the call sites).

cc @danrubel 

Related language feature: https://github.com/dart-lang/sdk/issues/34355

**Comment by devoncarew** [comment]
This would be useful for things like auto-converting Flutter samples and examples.

**Comment by danrubel** [comment]
- [ ] Prefer int literals over double literals lint
- [ ] Convert double literal to int literal assist
- [ ] Hook up lint + fix in edit.dartfix
