### ISSUE TITLE
Analyzer Feedback from android studio

### ISSUE THREAD

**Issue by ahmad5521** [dart-lang/sdk#34830]
Analyzer Feedback from android studio

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 2560x1440`

# Exception

Please append the contents of:
file:///private/var/folders/wc/pdr7lmhx18z2zvx5sh4tf2fh0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/AhmadAsiri/Documents/development/flutter_app/lib/pages/product_edit.dart
Exception: Element not found in summary: package:flutter/src/widgets/form.dart

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/34823
