### ISSUE TITLE
Dev-compiler fails to infer type of mixin.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34846]
This is triggered by the code in `language_2/issue32353_test.dart` (currently in CL 
https://dart-review.googlesource.com/c/sdk/+/79700)

The code works when compiled by `dartdevk` and when analyzed by the analyzer, so it seems to be a dartdevc *only* issue.

**Comment by jmesserly** [comment]
will close this and track the task model issue in: https://github.com/dart-lang/sdk/issues/35013
