### ISSUE TITLE
Typo in Super mixin feature specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#34842]
Pleease see https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md

>In a mixin declaration like mixin A<X extends S, Y extends T> on B, C implements D, E { body } the on clause declares the interfaces B and C as super-class constraints of the mixin.
...
 A mixin declaration defines an interface. The interface for this mixin declaration is equivalent to the interface of the class declared as:
> 
> `abstract class A<X extends S, Y extends S> extends A$super<X, Y> implements D, E { body' }`
> where body' contains abstract declarations corresponding to the instance members of body of the mixin A.
> 

There should be `Y extends T`, not S

`abstract class A<X extends S, Y extends T> extends A$super<X, Y> implements D, E { body' }`

**Comment by lrhn** [comment]
Good catch. Fixed.
(You can also file issues like this in the https://github.com/dart-lang/language repository, it's closer to the actual file. Either will work.)
