### ISSUE TITLE
Red squiggly line appearing under wrong thing and freezing

### ISSUE THREAD

**Issue by shabikar** [dart-lang/sdk#34858]
Sometimes when I put a custom data type inside the angular brackets of Future, like (Future<CustomDataType>), without first importing it, the red squiggly line appears under Future instead of the custom data type and the IDE freezes.

I am on Ubuntu 16.04

Analyzer Feedback from IntelliJ

**Comment by alexander-doroshko** [comment]
@shabikar, IntelliJ-specific issues (like freezes) are tracked in JetBrains issue tracker: https://youtrack.jetbrains.com/issues/WEB (Subsystem: Dart). Is the problem is still actual, please file an issue there and attach the whole folder with logs and thread dumps zipped (Help | Compress Logs...)

**Comment by srawlins** [comment]
Closing with @alexander-doroshko 's comment.
