### ISSUE TITLE
No syntax highlighting and errors in IDE anymore

### ISSUE THREAD

**Issue by Butzlabben** [dart-lang/sdk#34855]
It stops highlighting stuff in code.

[report2.txt](https://github.com/dart-lang/sdk/files/2493081/report2.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Daniel\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Daniel\IdeaProjects\wishlist2\lib\ui\choose_filter.dart
Element mismatch in C:\Users\Daniel\IdeaProjects\wishlist2\lib\ui\choose_filter.dart at class ChooseFilter extends StatelessWidget
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by devoncarew** [comment]
Thanks for the report! This looks like a dup of https://github.com/dart-lang/sdk/issues/34721.
