### ISSUE TITLE
Instantiate-to-bounds produces different result in dart and analyzer in some cases

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34861]
Dart SDK Version: 2.1.0-dev.7.1
OS: Windows 10

The following source code example declares class `G`, prints its actual type and assigns `G` object to a variable of its actual type:
```
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class A<X> {}
class B<X> extends A<X> {}
class G<X1 extends A<X1>, X2 extends A<X1>, X3 extends B, X4 extends X2> {}

main() {
  G source;
  print(G);
  var fsource = toF(source);
  F<G<A<dynamic>, A<A<dynamic>>, B<dynamic>, A<A<dynamic>>>> target = fsource;
}
```
Dart passes with this, the output is: `G<A<dynamic>, A<A<dynamic>>, B<dynamic>, A<A<dynamic>>>`, and so it's actual type of `G`.

However, analyzer fails with compile error here, error message reads that analyzer treats `G` actual type as `G<A<dynamic>, A<dynamic>, B<dynamic>,dynamic>`: 
`error - A value of type '<Y extends G< A <dynamic>, A<dynamic>, B<dynamic>, dynamic>>() -> void' can't be assigned to a variable of type '<Y extends G<A<dynamic>, A<A<dynamic>>, B<dynamic>, A<A<dynamic>>>>() -> void' at test1.dart:12:71 - invalid_assignment
`

**Comment by iarkh** [comment]
I've simplified a testcase above:
```
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class B<X> {}
class A<X1 extends B<X1>, X2 extends X1> {}

main() {
  A source;
  print(A);
  var fsource = toF(source);
  F<A<B<dynamic>, B<dynamic>>> target = fsource;
}
```
It also passes with dart and produces compile time error with analyzer.

**Comment by eernstg** [comment]
Right, the simplified example is also a bug in the analyzer.

**Comment by srawlins** [comment]
If you put `@dart=2.9` above the example, the analyzer now produces no errors.
