### ISSUE TITLE
Analyzer consuming all memory

### ISSUE THREAD

**Issue by dcov** [dart-lang/sdk#34876]
This has been happening over the past couple of days where the analyzer will start doing its analysis, but will never end and eventually consume all available memory including the swap space. 
I assumed it might be the Dart Code plugin for VS Code, so I tried using Android Studio instead, but it still happens.
I also cleared the analyzer cache directly at: ~/.dartServer/.analysis-driver, and it seemed to work for a little while, but it's started back up again, and clearing it again didn't do anything this time.
As of now, starting up VS Code/Android Studio will immediately trigger this 'infinite' analysis, and always ends up freezing my system unless I manually stop it.

Dart VM version: 2.1.0-dev.7.1.flutter-b99bcfd309 (Wed Oct 10 20:19:14 2018 +0000) on "linux_x64"

Update:
It also happens when using the [dart-vim-plugin](https://github.com/dart-lang/dart-vim-plugin) on neovim.

**Comment by iarkh** [comment]
Hello, I observe the same behavior when debug and run co19 test in IDEA.
I work on Windows 10 desktop.

**Comment by zoechi** [comment]
Probably a dup of #34802

**Comment by dcov** [comment]
Yup! specifically this one #34850. Thanks @zoechi.
