### ISSUE TITLE
Revive ARMv6 support

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#34874]
This has several components.
- [ ] Triage and fix simarmv6 test failures
- [ ] Find Linux and Android ARMv6 cross toolchains. Teach `gclient sync` or `gclient runhooks` to download them.
- [ ] Add GN toolchain definitions for the ARMv6 toolchains
- [ ] Make sure we're passing all the right flags to the ARMv6 toolchains
- [ ] Obtain ARMv6 hardware (Linux and/or Android), attach to bots, run tests on hardware. This can mirror the ARMv7 setup.

**Comment by zanderso** [comment]
See: https://github.com/flutter/flutter/issues/22380

**Comment by robertmuth** [comment]
I would be great if, as a side effect of this, we would end up with an SDK for "Raspian", 
the Linux distribution for Raspberry Pi's.
Modern Raspis (2/3 models) are ARMv7 but the Pi Zeros are ARMv6. 

To see where things are WRT  ARMv6 compatibility, one could  build and SDK 
on Raspi 3 and then try it out on an Zero

**Comment by zanderso** [comment]
> To see where things are WRT ARMv6 compatibility, one could build and SDK
on Raspi 3 and then try it out on an Zero

By default when targeting 32-bit ARM, the Dart VM compiler definitely generates instructions that require ARMv7, so the SDK that we build that works on ARMv7 is not designed to work on ARMv6.

[This process](https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Raspberry-Pi-1) for Raspberry Pi 1 worked at one point in time, and would be a good starting point for future ARMv6 support.

**Comment by mit-mit** [comment]
I would like to reconsider this. Currently Flutter formally only supports ARMv7 and ARM64:
https://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on
