### ISSUE TITLE
Analyzer processes typed parameter which extends simple bounded typedef in incorrect way

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34881]
Dart SDK Version: 2.1.0-dev.7.1
OS: Windows 10

The following test example declares `G1<X> = X Function()` typedef and than uses it as a typed parameter of other typedefs and classes:
```
typedef G<X extends num> = X Function();

typedef G1 = G Function();

typedef G2 = G<dynamic> Function();
typedef G3 = G<Object> Function();  // Compile-error here
typedef G4 = G<String> Function();  // Compile-error here


class A1<X extends G<dynamic>> {}
class A2<X extends G<String>> {}  // Compile-error here
class A3<X extends G<Object>> {}  // Compile-error here

main() {}
```
`G` is simple-bounded, and so its bound cannot be extended to `dynamic`.

However, analyzer throws compile-time error for lines where `A2`, `A3`, `G3` and `G4` are declared, and there is no errors with `G2` and `A1` declarations.

Seems like it's incorrect behavior and declaring of A1 and G2 should causes compile-time error too.

Analyzer sample output for the given example is:
```
Analyzing test.dart...
  error - 'Object' doesn't extend 'num' at test.dart:6:16 - type_argument_not_matching_bounds
  error - 'String' doesn't extend 'num' at test.dart:7:16 - type_argument_not_matching_bounds
  error - 'String' doesn't extend 'num' at test.dart:11:22 - type_argument_not_matching_bounds
  error - 'Object' doesn't extend 'num' at test.dart:12:22 - type_argument_not_matching_bounds
4 errors found.
```

Please note that dart silently passes with the same example for all the class and typedef declarations, I am going to file a separate bug against runtime about this.

**Comment by srawlins** [comment]
The errors today are the same as reported above.

**Comment by eernstg** [comment]
We can actually close this one. No behavior needs to change:

`G<Object>` and `G<String>` are reported as errors, both when they occur in `A2`, `A3`, `G3`, and `G4`. This is correct, because those types are not well-bounded.

`G<dynamic>` is a correctly super-bounded type, and no error is reported. Again OK.
