### ISSUE TITLE
IOOverrides.fseGetType gets a path ending with \0

### ISSUE THREAD

**Issue by iinozemtsev** [dart-lang/sdk#34885]
I'm trying to use IOOverrides in a test to fake filesystem operations and found an issue that the handler I pass to [fseGetType](https://github.com/dart-lang/sdk/blob/a1d61371d36b289cbd19144a07b66db177d108d3/sdk/lib/io/overrides.dart#L72) gets paths with `\0`. Looks like this happens because `FileSystemEntity.type` [encodes](https://github.com/dart-lang/sdk/blob/a1d61371d36b289cbd19144a07b66db177d108d3/sdk/lib/io/file_system_entity.dart#L685) path to zero-terminated utf8 array, and later, when there's an `IOOverrides`, [decodes](https://github.com/dart-lang/sdk/blob/a1d61371d36b289cbd19144a07b66db177d108d3/sdk/lib/io/file_system_entity.dart#L835) it back without trimming a zero. 

Is this an intended behavior or an issue? I can work this around, but still it would be nice to have it working out of the box.

Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
  
   Dart VM version: 2.1.0-dev.6.0+google3-v2.1.0.dev.6.0 (google3) on "linux_x64"`

* Whether you are using Windows, MacOSX, or Linux (if applicable)

   Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

   N/A

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by liamappelbe** [comment]
Confirmed this is still a bug. I'll investigate.
