### ISSUE TITLE
Add an API to `CompilationUnitElement` : List<Element> get declarations;

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34892]
Today in order to iterate across everything in a library you need to know all the different types of elements and access them all separately : `accessors`, `functions`, `functionTypeAliases`, etc.

It would be more convenient, and more future-compatible as new types are added, if there was a single API that combined all of these for us.

**Comment by bwilkerson** [comment]
Would it be sufficient to be able to get all of the elements from each compilation unit, or do you really want all of the top level elements in a library (or both)?

**Comment by natebosch** [comment]
Our ultimate goal is everything in a library (in this case). If there is a use case for iterating over the elements in a compilation unit it would be better to have the API there since it's easier to generalize from compilation unit to library by iterating over units than to filter from all elements in a library to the ones in a particular compilation unit.

I'm pretty sure we _don't_ want all elements in the namespace in this case.

**Comment by natebosch** [comment]
For context, here's how we are implementing this today:

https://github.com/dart-lang/source_gen/blob/c080f35bd3d55d305df7825ba34978583f8583b3/source_gen/lib/src/library.dart#L37-L47

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/81185

**Comment by bwilkerson** [comment]
Note that this landed on the 'analyzer' branch, not on bleeding edge. Probably won't effect anything because you can't use it until a new version of the analyzer package has been published, but I thought I'd be thorough.

**Comment by kevmoo** [comment]
What's the story w/ that branch? I'm a bit confused...

**Comment by bwilkerson** [comment]
We have started cleaning up the analyzer code bases. We're being careful, of course, but there's always the possibility of accidentally introducing a bug. We don't want to risk introducing a bug into the next release, so we're doing this work on a branch until we're confident that it's safe to move the changes to master.
