### ISSUE TITLE
Cut out all of vm-service and developer in release mode for Flutter

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#34895]
The treemap [1] reports that there are still ~3KB of vmservice.cc and ~2KB of developer.cc included in Flutter's release mode engine. Can we cut those out completely since they are disabled in release mode anyways?

/cc @a-siva 

[1] https://storage.googleapis.com/flutter_infra/flutter/2cd89200c24c8c1d51e875e87e0f899339865cd3/android-arm-release/sizes/index.html

**Comment by a-siva** [comment]
Sure.

**Comment by liamappelbe** [comment]
I think developer.cc is already minimal. For example, Developer_inspect needs to return the inspectee to remain consistent with https://api.dartlang.org/stable/2.1.0/dart-developer/inspect.html, even though in product mode it doesn't actually do anything. I've checked every method from developer.cc that appears in the binary and it seems like they're all as small as they can be, while still adhering to those docs.

vmservice.cc can be stripped out though. Mailing a CL for this now.
