### ISSUE TITLE
how to call class method with string function name?

### ISSUE THREAD

**Issue by linguitang** [dart-lang/sdk#34909]
example:
class A {
  B(){
    return true;
  }
 C(){
    return false;
 }
}

var str = "B";
how to call function B with str;

**Comment by lrhn** [comment]
The general problem requires reflection, so you can only do it using the `dart:mirrors` library. That library is not available on all platforms (it's not on the web and not in Flutter).

Short of that, you need to know the possible methods ahead of time, and then you can either write a function like:
```dart
Function getMember(A object, String name) {
   if (name == "B") return object.B;
   if (name == "C") return object.C;
   throw ArgumentError.value(name, "name");
}
```
or use something like [`package:reflectable`](https://pub.dartlang.org/packages/reflectable) to generate the function for you.

**Comment by vsmenon** [comment]
Closing.  To add to @lrhn 's explanation, mirrors is not likely to be provided for client code as it interferes with the compiler's ability to optimize code.

**Comment by eernstg** [comment]
@linguitang, on the reflectable version issue, please see https://github.com/dart-lang/reflectable/issues/153.

**Comment by dvijai** [comment]
> The general problem requires reflection, so you can only do it using the `dart:mirrors` library. That library is not available on all platforms (it's not on the web and not in Flutter).
> 
> Short of that, you need to know the possible methods ahead of time, and then you can either write a function like:
> 
> ```dart
> Function getMember(A object, String name) {
>    if (name == "B") return object.B;
>    if (name == "C") return object.C;
>    throw ArgumentError.value(name, "name");
> }
> ```
> 
> or use something like [`package:reflectable`](https://pub.dartlang.org/packages/reflectable) to generate the function for you.

it is usable if line are limited, but if there are thousands or variable, then the questions remains on its place unsolved.
