### ISSUE TITLE
Analysis server hangs in InterfaceTypeImpl.==

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34925]
Here is my invocation:

```
$HOME/src/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart $HOME/src/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --sdk $HOME/src/dart-sdk/sdk/tools/sdks/dart-sdk
```

It is using 100% cpu on one core and responds very slowly. Here is the profile:

![observator](https://user-images.githubusercontent.com/29863079/47506211-e8974f80-d86f-11e8-9060-0e21c1a70688.png)

**Comment by sjindel-google** [comment]
This bug reproduces reliably on my system after I am editing Dart files for no more than an hour.

**Comment by vsmenon** [comment]
fyi - @stereotype441 @bwilkerson - infinite recursion on the trace perhaps?

**Comment by sjindel-google** [comment]
If this helps, I'm running the analysis server here within the Dart SDK, and it's possible that it's trying to analyze all the dart files under `tests/`.

**Comment by stereotype441** [comment]
Note that https://github.com/dart-lang/sdk/issues/34981#issuecomment-434330984 contains a command-line repro

**Comment by stereotype441** [comment]
@scheglov took a look and it sounds like this is yet another issue with the analyzer's representation of function types.  We plan to rework the analyzer's function type representation once all clients have been migrated off the task model; once that happens we should be able to fix this bug.

**Comment by stereotype441** [comment]
Substantial work has been done on the analyzer's representation of function types since this issue was reported, and the repro from https://github.com/dart-lang/sdk/issues/34981#issuecomment-434330984 no longer crashes.  So I'm marking this as fixed.  Please feel free to re-open if you're still seeing a problem.
