### ISSUE TITLE
Function type parameters with explicit Object bound are instantiated to dynamic

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34920]
The default type for a type parameter with no specified bound is `dynamic`. The default type for a type parameter with bound `Object` is `Object`.

For function types, CFE instantiates `dynamic` in both cases and thus does not report the error in this program:
```dart
Q hest<Q>(dynamic x) {
  if (x is Q) return x;
  return null;
}

Q Function<Q>(dynamic) pony = hest;
Q Function<Q extends Object>(dynamic) zebra = hest;

main() {
  hest(42).fisk(); //# 01: ok
  pony(42).fisk(); //# 02: ok
  zebra(42).fisk(); //# 03: compile-time error
}
```

**Comment by stefantsov** [comment]
I think there's a fix for it that's going to be landed soon: https://dart-review.googlesource.com/c/sdk/+/81405.
