### ISSUE TITLE
Stable Angular 5.1.0 needs unstable dev SDK 2.1.0

### ISSUE THREAD

**Issue by quizzmaster** [dart-lang/sdk#34945]
I'm new to Dart and AngularDart. I want to use the stable branch of the dart SDK with version 2.0.0. The homepage mentions angular version 5.1.0 to be the latest stable version for dark 2.0.0, but pub says it needs SDK >=2.1.0-dev.5.0. It's really confusing for me, because the package manager should serve the packages for the stable sdk. If I switch to the dev branch of the SDK an other package I use in a different project `rpc_mongo_mapper` won't work anymore, because it relies on the stable SDK.

Such a behaviour is predestined to scare new developers of dart.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/angular#1648
