### ISSUE TITLE
Support generic operator

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#34940]
Like generic methods, generic operators are helpful.

```
class Foo {
  T operator[]<T>(int index) => null;
}
```

**Comment by lrhn** [comment]
Dart overridable operators are currently required to have specific signatures, matching exactly how the operators can be written. For example, `*` must take one argument, and `[]=` must take two.

Having a type parameter that you *cannot* provide explicitly is problematic. It would only be possible to introduce the type argument via inference, and there is no way to override the inferred type.

It also means that different classes have different signatures for `+`, invocations of `+` become much more dynamic.

The example here isn't that useful, you could just return `Null`, but something like:
```dart
abstract class MyNum {
  MyNum operator+(MyNum other);
}
class MyDouble implements MyNum {
  MyDouble operator+(MyNum  other) => ...
}
class MyInt implements MyNum {
  T operator+<T extends MyNum>(T value) => ...
}
```
could let you have a function with return type depending on the provided argument type.
