### ISSUE TITLE
Cannot bind to IPv6 link-local addresses

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#34944]
If you attempt to bind to a Link-Local IPv6 address, it will fail.

```dart
import 'dart:io';

Future<void> main() async {
  final List<NetworkInterface> interfaces = await NetworkInterface.list(
    includeLoopback: true,
    includeLinkLocal: true,
    type: InternetAddressType.IPv6,
  );

  // find a link local address
  InternetAddress linkLocalAddress;
  for (var interface in interfaces) {
    for (var address in interface.addresses) {
      if (address.address.contains('%')) {
        linkLocalAddress = address;
        break;
      }
    }
    if (linkLocalAddress != null && !linkLocalAddress.address.endsWith('%lo0')) {
      break;
    }
  }
  print(linkLocalAddress);

  await RawDatagramSocket.bind(
    linkLocalAddress,
    5353,
    reuseAddress: true,
    reusePort: true,
    ttl: 255,
  );
}
```

output:

```
InternetAddress('fe80::1c4d:8ae2:3efa:476c%en0', IPv6)
Unhandled exception:
SocketException: Failed to create datagram socket (OS Error: Can't assign requested address, errno = 49), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io/runtime/binsocket_patch.dart:597:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind (dart:io/runtime/binsocket_patch.dart:1828:26)
#2      RawDatagramSocket.bind (dart:io/runtime/binsocket_patch.dart:1786:31)
#3      main (package:multicast_dns/interfaces.dart:25:27)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

This appears to be a bug in address parsing to the RawAddr union.  For reasons I don't fully grasp right now, I get a different error if I try to bind to the loopback local link address; either it fails if I try to bind to an in-use port, or it succeeds otherwise.  I'm not sure why that works but other link-local addresses do not.

**Comment by dnfield** [comment]
This appears to not be an issue on Windows, but it is reproducing on macOS.  Haven't tested Linux.

**Comment by sortie** [comment]
On Linux, binding to fe80::/10 (link-local unicast addressing) doesn't work for me and fails with EINVAL. This doesn't seem to be be a problem with Dart, as nc -l fe80::x -p 5353 also fails with EINVAL and makes the exact same system call.

Can you test if you can bind to that address and port in another program / programming language? It might be that it isn't supposed to work.

**Comment by sortie** [comment]
Ping?

**Comment by dnfield** [comment]
I think this was a problem in my application logic - I'm going to close for now, as I'm pretty sure I was just doing things wrong for IPv6 and ended up working around it anyway.
