### ISSUE TITLE
dartfmt doesn't support machine and dry run at the same time

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#34961]
```
dartfmt -n --machine .
Cannot use --dry-run and --machine at the same time.
```
I think we should be able to use both.

**Comment by munificent** [comment]
> I think we should be able to use both.

`--dry-run` is only meaningful to avoid overwriting files. `--machine` never overwrites, so combining the two wouldn't make a difference.

There options are kind of a mess because they accreted over time without much of a coherent design. :(

> @munificent - should we move these to https://github.com/dart-lang/dart_style ?

In general, yes please.
