### ISSUE TITLE
Release mode is way more slower than debug mode for benchmark

### ISSUE THREAD

**Issue by zzjjob** [dart-lang/sdk#34960]
I was trying to benchmark the performance of flutter and compare it with that of Java and C. 

The problem with FluidMotion may be that I didn't open vfp, but what about other benchmarks?

<img width="841" alt="wx20181029-125443 2x" src="https://user-images.githubusercontent.com/3352030/47630070-c2c4c000-db79-11e8-9055-47aa742f3530.png">

dart source code in [ton80](https://github.com/dart-archive/ton80)

Flutter 0.10.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d954ae6850 (3 weeks ago) • 2018-10-09 16:21:06 -0400
Engine • revision bf377896ff
Tools • Dart 2.1.0-dev.6.0.flutter-a50dfd6698

**Comment by mraleph** [comment]
In general JIT has more type information available (based on the runtime profile) and is more aggressive in its optimizations than the AOT. 

We are working to reduce this performance difference. In fact these numbers were _much_ worse in the Dart 1 world - we saw improvements of 2x or more across the board over the past year.

If you have a concrete application that you think is running to slow - please file a separate bug and we will investigate.

**Comment by zzjjob** [comment]
> In general JIT has more type information available (based on the runtime profile) and is more aggressive in its optimizations than the AOT. AOT has to balance optimizations and download size.
> 
> We are working to reduce this performance difference. In fact these numbers were _much_ worse in the Dart 1 world - we saw improvements of 2x or more across the board over the past year.
> 
> If you have a concrete application that you think is running to slow - please file a separate bug and we will investigate.

AOT code can be continuously optimized at runtime， like JIT ?

**Comment by mraleph** [comment]
@zzjjob not really AOT code is optimized once during compilation - that is why it is called AOT = ahead of time. (we do some optimizations to methods calls - by linking them directly to the call targets - but that's as much as we do).
