### ISSUE TITLE
Merge dartfix protocol changes into dev channel

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#34968]
**commit to merge**: https://dart-review.googlesource.com/c/sdk/+/81861

**merge instructions**: merge the above CL which is comprised of 4 cherry-picks. I did it this way so that I could ensure all the tests passed.

**reason**: analysis server protocol changes for the edit.dartfix request/response used by dartfix.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
This commit will be merged in a full push to dev, that will happen before Dart 2.1.
I will close the issue when that happens.

**Comment by whesse** [comment]
Three of the four cherry-picks were included in the base revision pushed to dev, but commit 0fe448a99643e149acb2e7e32d7a30eba7dd646d was not.  This needs to be cherry-picked to dev, and will be in the next patch release.

**Comment by whesse** [comment]
Merged in 2.1.0-dev.9.1
