### ISSUE TITLE
what is "no valid OpenPGP data found."

### ISSUE THREAD

**Issue by navidshad** [dart-lang/sdk#34967]
I have a problem with installing dart-sdk on Ubuntu. 
I got error when I performed this command
```
sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1449  100  1449    0     0   1643      0 --:--:-- --:--:-- --:--:--  1642
gpg: no valid OpenPGP data found.
```

**Comment by natebosch** [comment]
This has to do with `curl`. You can manually download that file `https://dl-ssl.google.com/linux/linux_signing_key.pub` and then do `cat linux_singing_key.pub | apt-key add -`

Or to get help making this work with `curl` - https://stackoverflow.com/a/38039880
