### ISSUE TITLE
update linter in dev for dartfix

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#34974]
**commit(s) to merge**: https://dart-review.googlesource.com/c/sdk/+/81881

**merge instructions**: merge this CL into dev

**reason**: pull the latest linter changes into analysis server to support dartfix

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
This commit will be included in the next full push to dev, which will happen before 2.1.
I will close the issue when this happens.

**Comment by whesse** [comment]
This was not included in the full push to dev, which was of a version from Oct 25.  All outstanding merge requests, including this, will be merged into -dev.9.1 without delay.

**Comment by whesse** [comment]
Merged in 2.1.0-dev.9.1
