### ISSUE TITLE
Uri parsing does not throw on invalid URIs

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#34988]
This appears to be an issue only with: Dart VM version: 2.1.0-dev.8.0

Example code:
```
main () {
  Uri.parse('[][][]');
}
```

Should throw with:
```
Uncaught exception:
FormatException: Invalid character (at character 1)
[][][]
^
```

However it executes without exception.

**Comment by vsmenon** [comment]
@grouma - is this a regression?

FYI @lrhn

**Comment by grouma** [comment]
Yes this is a regression. package:test was relying on the fact that invalid URIs will throw. Documentation also states the same.

**Comment by lrhn** [comment]
We changed the rules for parsing to be more permissive. People were actually expecting URIs with `[]` in the query or fragment to parse, because they do so on other platforms.
