### ISSUE TITLE
dart:mirrors, MethodMirror.isSynthetic should be true for nSM forwarders

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34982]
Consider the following program:
```dart
import 'dart:mirrors';

abstract class A {
  int sum(int a, int b);
}

class B implements A {
  dynamic noSuchMethod(Invocation invocation) {}
}

void main() {
  ClassMirror classMirror = reflectClass(B);
  MethodMirror methodMirror = classMirror.declarations[#sum];
  assert(methodMirror.isSynthetic);
}
```
This programs throws when executed by `dart --enable-asserts` version 2.1.0-edge.973c9519b768b3c13d3e135f05cdf945c64b7754 (and also 2.1.0-dev.7.1), but it seems reasonable to expect that implicitly induced noSuchMethod forwarders are considered synthetic.

So this issue is a request for changing the semantics of `MethodMirror.isSynthetic` such that nSM forwarders are considered synthetic, such that the above program will run without throwing.

**Comment by rootext** [comment]
Hello.
Is there any plans to fix it?

**Comment by mraleph** [comment]
@liamappelbe you recently added code to recognize the forwarders for coverage. Could you also update isSynthetic to respect the bit? Would probably be one line change.

**Comment by liamappelbe** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/223eaa6fbb74eda869cf526ceed81493f45d7c05
