### ISSUE TITLE
Generic metadata, please

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#34984]
The spec doesn't allow generic metadata in the grammar for metadata.  (The CFE actually does allow it, analyzer doesn't.)  This seems like an unnecessary restriction.

```
class Resolvable<T, U> {
  final U Function(T) resolve;
  const Resolvable(this.resolve);
}

void resolveInt(int n) { print(n); }

@Resolvable(resolveInt)
class D { ...
```

**Comment by lrhn** [comment]
Agree that it's probably unnecessary.
Prom a parsing perspective, if we can recognize `@foo` and `@foo(...)`, then we should also be able to recognize `@foo<...>(...)`. I don't think there is any annotatable element that can start with `<`.

**Comment by kmillikin** [comment]
I also want type inference to work here, based on the constructor arguments.

**Comment by eernstg** [comment]
I had a CL a while ago about this, but it got no traction and it was abandoned. However, I believe there would not be any problems doing it, and I agree that the current lack of support is surprising.

**Comment by kmillikin** [comment]
I just tested this for real (without relying on type inference) and the CFE and Analyzer do agree that it's not allowed to write the type arguments there.

**Comment by TimWhiting** [comment]
This can be closed right?

**Comment by lrhn** [comment]
Absolutely! *Fixed!*
