### ISSUE TITLE
Get unexpected [NoSuchMethodError] when [connectionTimeout] is set on [HttpClient]

### ISSUE THREAD

**Issue by microdog** [dart-lang/sdk#34980]
I've found that if `connectionTimeout` is set on `HttpClient` and is shorter than the system level timeout, an unexpected `NoSuchMethodError` will be thrown instead of a `SocketException` described in the document when a connection exceeds this timeout.

After investigating, I find that this might be a bug in Dart SDK.

https://github.com/dart-lang/sdk/blob/f4ce2c5749f3f27cc84140c8fd330079ad90ccdd/sdk/lib/_http/http_impl.dart#L1943-L1949

The connection timeout is implemented using `Future.timeout`, but no error is thrown in the `onTimeout` function. This will cause the returned future(`socketFuture`) to be finished with `null`. Then the `called on null` exception will be thrown in the future's callback.

https://github.com/dart-lang/sdk/blob/f4ce2c5749f3f27cc84140c8fd330079ad90ccdd/sdk/lib/_http/http_impl.dart#L1952

### Demo

```
import 'dart:io';

main(List<String> args) async {
  final client = new HttpClient();

  // CRITICAL
  // Comment this line and the request will be finished with a
  // [SocketException] caused by system level timeout.
  // If a custom connectionTimeout is set and is shorter than
  // the system timeout, an unexpected [NoSuchMethodError] will
  // be thrown.
  client.connectionTimeout = new Duration(microseconds: 1);

  // expected [SocketException] instead of [NoSuchMethodError]
  await client.getUrl(Uri.parse("http://10.255.255.1"));
}

```

Result:

```
Unhandled exception:
NoSuchMethodError: The method 'setOption' was called on null.
Receiver: null
Tried calling: setOption(Instance of 'SocketOption', true)
#0      main (file:///Users/microdog/Workspace/git/dart_http_timeout_demo/main.dart:15:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Result without connectionTimeout set:

```
Unhandled exception:
SocketException: OS Error: Operation timed out, errno = 60, address = 10.255.255.1, port = 53232
#0      main (file:///Users/microdog/Workspace/git/dart_http_timeout_demo/main.dart:15:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

### Dart SDK Version:

```
Dart VM version: 2.1.0-dev.7.1.flutter-b99bcfd309 (Wed Oct 10 20:19:14 2018 +0000) on "macos_x64"
```

**Comment by jeroentrappers** [comment]
I'm running into the same issue.

**Comment by vvinogradsky** [comment]
I am seeing the same thing. Fix please?

**Comment by MasterEthan** [comment]
I'm seeing the same issue.

**Comment by wendux** [comment]
I'm running into the same issue.

**Comment by jbdeboer** [comment]
Calling ```task.cancel()``` will cause task.socket to complete with a SocketException.

I believe the best fix is to return task.socket from the onTimeout function. This change will cause socketFuture to also complete with a SocketException and prevent the next then function from executing.

**Comment by ccornici** [comment]
Same issue here

**Comment by jbdeboer** [comment]
@ccornici I have a patch waiting for review which fixes this issue #36242 . 

While the team is working on the review, you can either patch your SDK locally or catch NoSuchMethod exceptions where you were catching socket exceptions.

**Comment by bpilot** [comment]
Also having this issue with a mission-critical service (liveness testing monitor). Please help.

**Comment by jbdeboer** [comment]
If you look back at the history, there is a patch I proposed. But the
easiest work around is to catch NoSuchMethodError and retry the connection.

**Comment by brianquinlan** [comment]
I can no longer reproduce this and the `onTimeout` approach is no longer used.
