### ISSUE TITLE
Document the mixin keyword in the Language Tour

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34992]
This is probably planned already, but filing this issue just so we do not forget.

Let's document the `mixin` keyword in (at least) the [Language Tour](https://www.dartlang.org/guides/language/language-tour) in time for 2.1. Some Dart users started discovering this feature and are asking questions.

/cc @leafpetersen @sfshaza2

**Comment by sfshaza2** [comment]
Yes, this is in the plans, Yegor. @kwalrath has it on her todo list. But a bug is a great idea.  :)

**Comment by kwalrath** [comment]
I'm going to close this in favor of dart-lang/site-www#1164.
