### ISSUE TITLE
Strange type-error from the analyzer (2.1.0-dev.8.0)

### ISSUE THREAD

**Issue by Keksinautin** [dart-lang/sdk#35003]
Hi, with such code:
```dart
import 'dart:html';
import 'package:mockito/mockito.dart';

class WindowMock extends Mock implements Window {}
```
The analyzer shows the error in the 4th string:  
`The return type of getter 'Window.opener' is 'WindowBase' which isn't assignable to the type 'Window' of its setter 'Window.opener'`.

For the stable Dart version, there are no errors.

`dart --version`: `Dart VM version: 2.1.0-dev.8.0 (Wed Oct 24 21:47:12 2018 +0200) on "linux_x64"`

I do not understand what should I do to fix the code, or it is just an issue of the new analyzer. 
Can somebody help, please?

**Comment by dgrove** [comment]
Giving an area so it shows as triaged.

**Comment by Keksinautin** [comment]
I have removed all files related to Dart and IDE and then reinstalled them. After it, I have not seen this issue anymore. I guess we can close this issue. I'm sorry to trouble you.
