### ISSUE TITLE
move dartdevc off analyzer task model

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#35013]
See https://github.com/dart-lang/sdk/issues/33546

Also, Analyzer task model has incorrect results for some things (e.g. mixin type arguments, top-level inference) and users are hitting these.

**Comment by vsmenon** [comment]
@JekCharlsonYu - we're hoping to cherry-pick this fix for 2.1.  It fixes some issues @yjbanov hit on new mixins.

**Comment by jmesserly** [comment]
I'm testing this CL: https://dart-review.googlesource.com/c/sdk/+/82469. I may need to update a more status entries, but otherwise I think it's in good shape.

**Comment by vsmenon** [comment]
@jmesserly - how is this looking?
