### ISSUE TITLE
Please merge "increment analysis server protocol version" into dev channel

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#35018]
**commit(s) to merge**: https://dart-review.googlesource.com/c/sdk/+/82480

**merge instructions**: clean merge

**reason**: dartfix added a new edit.dartfix analysis server protocol and the dartfix client checks the protocol version before continuing.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
This commit 8c20adffe66ff672111aa5ab4dbbd557df097e30 is cherry-picked into 2.1.0-dev.9.0.
Other cherry-picks are missing, and arm building is broken, so 2.1.0-dev.9.1 should be used instead.
