### ISSUE TITLE
Race between Monitor::~Monitor and Monitor::Exit on Windows

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35029]
The code does this:

```cpp
void GCMarker::StartConcurrentMark(PageSpace* page_space, bool collect_code) {
  // ... 

  Monitor roots_monitor;
  intptr_t root_tasks_remaining = num_tasks;
  for (intptr_t i = 0; i < num_tasks; i++) {
    ASSERT(visitors_[i] == NULL);
    SkippedCodeFunctions* skipped_code_functions =
        collect_code ? new SkippedCodeFunctions() : NULL;
    visitors_[i] = new SyncMarkingVisitor(isolate_, page_space, &marking_stack_,
                                          skipped_code_functions);

    // Begin marking on a helper thread.
    bool result = Dart::thread_pool()->Run(new ConcurrentMarkTask(
        this, isolate_, page_space, visitors_[i], i, num_tasks, &roots_monitor,
        &root_tasks_remaining));
    ASSERT(result);
  }

  // Wait for roots to be marked before exiting safepoint.
  MonitorLocker ml(&roots_monitor);
  while (root_tasks_remaining > 0) {  // (*)
    ml.Wait();
  }
}
```

and in the task it does this

```cpp
  virtual void Run() {
    {
      // ...
      {
        MonitorLocker ml(roots_monitor_);
        (*root_tasks_remaining_)--;  // (*)
        ml.Notify();
      }
      // ...
    }
    // ...
  }
```

Notice the following issue:

At `(*)` we decrement `root_tasks_remaining` and sent notification to the thread that started concurrent marking. When we send notification we release the `roots_monitor_` lock. 

Initiating thread then can acquire the lock and if `roots_task_remaining == 0` then it would proceed to exit `StartConcurrentMarking` - at which point `roots_monitor` would be released and then deleted. 

Meanwhile marking tasks will wake up from `Notify` and try to grab `roots_monitor_` again. 

However `roots_monitor_` is deleted - leading to a crash. 

I found this issued by looking at crash dump that @a-siva has observed during gardening. 

Crashdump is here: https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=49cb64ad2b7a4593bc1dd373f1203b8c2230956a

Here is extracted stack trace of the crashed thread:

```
 # Child-SP          RetAddr           Call Site
00 00000089`adbfea08 00007ff8`1b4b7287 ntdll!NtDelayExecution+0x14
01 00000089`adbfea10 00007ff7`84253949 KERNELBASE!SleepEx+0xa7
02 00000089`adbfeab0 00007ff8`1b466913 dart!crashpad::`anonymous namespace'::UnhandledExceptionHandler+0xc9 [c:\b\s\w\ir\cache\builder\sdk\third_party\crashpad\crashpad\client\crashpad_client_win.cc @ 174] 
03 00000089`adbfecf0 00007ff8`1e6bda9d KERNELBASE!UnhandledExceptionFilter+0x153
04 00000089`adbfee00 00007ff8`1e6a6466 ntdll!RtlUserThreadStart$filt$0+0x38
05 00000089`adbfee30 00007ff8`1e6ba07d ntdll!_C_specific_handler+0x96
06 00000089`adbfeea0 00007ff8`1e629c58 ntdll!RtlpExecuteHandlerForException+0xd
07 00000089`adbfeed0 00007ff8`1e614bcf ntdll!RtlDispatchException+0x368
08 00000089`adbff5e0 00007ff8`1e64cc96 ntdll!RtlRaiseStatus+0x5f
09 00000089`adbffb80 00007ff8`1e63ffb7 ntdll!RtlpUnWaitCriticalSection+0x46
0a 00000089`adbffbb0 00007ff7`8421838b ntdll!RtlLeaveCriticalSection+0x67
0b (Inline Function) --------`-------- dart!dart::MonitorLocker::{dtor}+0x8 [c:\b\s\w\ir\cache\builder\sdk\runtime\vm\lockers.h @ 143] 
0c 00000089`adbffbe0 00007ff7`84108905 dart!dart::ConcurrentMarkTask::Run+0x9b [c:\b\s\w\ir\cache\builder\sdk\runtime\vm\heap\marker.cc @ 704] 
0d 00000089`adbffc70 00007ff7`84108ade dart!dart::ThreadPool::Worker::Loop+0x45 [c:\b\s\w\ir\cache\builder\sdk\runtime\vm\thread_pool.cc @ 383] 
0e 00000089`adbffcb0 00007ff7`8408f6e4 dart!dart::ThreadPool::Worker::Main+0x8e [c:\b\s\w\ir\cache\builder\sdk\runtime\vm\thread_pool.cc @ 442] 
0f 00000089`adbffce0 00007ff7`84271fb0 dart!dart::ThreadEntry+0x54 [c:\b\s\w\ir\cache\builder\sdk\runtime\vm\os_thread_win.cc @ 67] 
10 (Inline Function) --------`-------- dart!invoke_thread_procedure+0xd [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 91] 
11 00000089`adbffd10 00007ff8`1c812774 dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 115] 
12 00000089`adbffd40 00007ff8`1e680d51 KERNEL32!BaseThreadInitThunk+0x14
13 00000089`adbffd70 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by mraleph** [comment]
If possible I request an easy way to switch concurrent marking on and off (e.g. controlled by a GN argument). @rmacnak-google

**Comment by rmacnak-google** [comment]
It is possible to disable concurrent marking with --marker-tasks=0. This also disables parallel marking, so I'll add a more specific --concurrent-mark flag.

**Comment by a-siva** [comment]
Ryan and I looked at this stack trace a bit more. It is unclear why you think that the notifying threads would release the roots_monitor_lock_, our implementation of monitors release the lock only when a 'Wait()' is called not for 'Notify()' or 'NotifyAll()'.

We had Ben get us the stack trace for other threads in the system at the time of the crash and the other thread was sitting in the 'Wait' of GCMarker::StartConcurrentMark, it hadn't yet exited the scope which would have triggered deletion of roots_monitor.

**Comment by mraleph** [comment]
We got a new crash today on Windows in a different place, but with a similar pattern that I observed in a concurrent marking crash: `Monitor` originally on the stack, a thread is hitting crash in `Monitor::Exit` -> `LeaveCriticalSection` because it is trying to access the state of an already destroyed monitor.

Notice that there was a piece I had wrong in my initial analysis of the crash - we are crashing while leaving CriticalSection, not when entering it. 

I started looking through the disassembly and discovered that `LeaveCriticalSection` is actually _non-atomic_. It does approximately the following: 

```
LeaveCriticalSection(cs):
  unlock(cs);  // (*)
  notify-waiters-if-any(cs)
```

Already after `(*)` another thread can go and lock `cs`. Meaning that in the following code:

```
// Main thread
{
  Monitor m;
  MonitorLocker ml(&m);
  
  bool done = false;
  RunThread(new Task(&done, &m));
  while (!done) {
    ml.Wait();
  }
}

// Task thread
// ...
{
  MonitorLocker ml(this->pm);
  *this->pdone = true;
}  // Here we call this->pm->Exit(), which calls LeaveCriticalSection(...)
```

race arises: 

- task thread executes `LeaveCriticalSection(cs)` but is suspended after `(*)` within `LeaveCriticalSection`.
- another thread (main thread) meanwhile grabs `cs`, checks if we are done and exits the block, leading to `~Monitor` which destroys the critical section;
- task thread progresses past `(*)` and touches destroyed critical section - and then explodes.

It seems we are hitting a fundamental problem in runtime - and this needs to be addressed.

**Comment by rmacnak-google** [comment]
I had a CL a while ago to update our Mutex/Monitor implementation to SRWLock. This didn't end up landing because the event handler on Windows requires recursive locking (though I forget whether it was for the mutex or the monitor). Perhaps we should land the half that updates dart::Mutex/Monitor but not dart::bin::Mutex/Monitor?

**Comment by mraleph** [comment]
Yeah, I remember debugging this. We might be able to rewrite event handler to avoid recursive locking.

That might work but we need to look into implementation of `ReleaseSRWLockExclusive` - I can't figure out from MSDN documentation if it provides similar destruction guarantees as mutexes on Linux. 

I can try to look into disassembly tomorrow.

**Comment by rmacnak-google** [comment]
Looks like we can get recursion from CRITICAL_SECTION + CONDITION_VARIABLE. Updated https://dart-review.googlesource.com/c/sdk/+/20901

**Comment by mraleph** [comment]
I briefly looked through machine code in SRW lock implementation - it does look like it should not exhibit the same race as we see with CriticalSection, so moving away from CRITICAL_SECTION to SRW locks should fix the race.
