### ISSUE TITLE
Typo in "int.dart" Documentation Commenting

### ISSUE THREAD

**Issue by nprisbrey** [dart-lang/sdk#35021]
* Dart SDK Version (`dart --version`):
**Most recent (2.0.0)**
* Whether you are using Windows, MacOSX, or Linux (if applicable):
**N/A**
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable):
**N/A**

**Issue:**
There is a typo in the file [sdk/sdk/lib/core/int.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/int.dart) on line 13. The word "valus" should be "values".

**Comment by natebosch** [comment]
https://dart-review.googlesource.com/c/sdk/+/82542

**Comment by lrhn** [comment]
Fixed by @natebosch. Thanks!
