### ISSUE TITLE
"new ScriptElement()..async = false" incorrectly rejected in async method

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#35020]
* Dart SDK Version (`dart --version`)
v2_1_0_dev_7_1
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

```
import 'dart:html';
import 'package:test/test.dart';

main() {
  setUp(() async {
    new ScriptElement()..type='text/javascript'..async=false..src='foo.js';
  });
}
```
gives the error
[error] The keywords 'async', 'await', and 'yield' can't be used as identifiers in an asynchronous or generator function. (.../async_test.dart, line 6, col 50)

**Comment by lrhn** [comment]
Only `await` and `yield` are reserved in Dart 2 async functions, not `async` itself.

**Comment by srawlins** [comment]
This is now accepted.
