### ISSUE TITLE
Analyzer fails to report error when a static toString method is defined

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#35036]
```dart
class ConvertValue {
    static String toString(final value) {
        if(value == null) {
            return "";
        }
        return value.toString();
    }
}
```
toString works fine in dev-mode but dart2js complains with:
```bash
packages/m4d_core/utils/ConvertValue.dart:72:19:
Error: Can't declare a member that conflicts with an inherited one.
    static String toString(final value) {
                  ^
Error: Compilation failed.
```
-----
Dart-Version: Dart VM version: 2.1.0-dev.8.0 (Wed Oct 24 21:47:12 2018 +0200) on "macos_x64"
MAC: 10.11.6

**Comment by eernstg** [comment]
Right, as Lasse already indicated it is a compile-time error, so it's an analyzer bug to not emit that error. 

But it may be worth mentioning that the member signatures do not matter: For the [given example](https://github.com/dart-lang/sdk/issues/35036#issue-376883019), the relevant rules are in section 'Class Member Conflicts'. These rules are concerned with the kinds and names of members (e.g., a static member declaration vs. an inherited instance member) and they never mention the signatures of said members. So both examples in this issue might just as well have been expressed with declarations with the same signature (in both cases: with an empty formal parameter list in the subclass).

**Comment by psyanite** [comment]
I am also encountering this issue

`class EnumUtil {
  static T fromString<T>(Iterable<T> values, String string) {
    return values.firstWhere(
        (f)=> "${f.toString().substring(f.toString().indexOf('.')+1)}".toString()
        == string, orElse: () => null);
  }

  @override
  static String toString(String string) {
    return string.split('.')[1];
  }
}
`
`lib/utils/enum_util.dart:9:17: Error: Can't declare a member that conflicts with an inherited one.`
