### ISSUE TITLE
FileSystemEvent.isDirectory returns wrong value when directory itself is deleted

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35032]
Create a durectory, watch it, then delete and see fired FileSystemEvent. Example
```dart
import "dart:io";
main() {
  Directory sandbox = new Directory(Directory.systemTemp.path + Platform.pathSeparator + "test-dir");
  sandbox.createSync();
  Directory dir = sandbox.createTempSync();

  dir.watch().listen((FileSystemEvent event) {
      print(event);
      print(event.isDirectory);
  });
  dir.deleteSync();

  new Future.delayed(new Duration(seconds: 1)).then((_) {
    sandbox.delete(recursive: true);
  });
}
```
Output is
```
FileSystemDeleteEvent('/tmp/test-dir/FXJVOX')
false
```
Here we delete a directory. Why FileSystemDeleteEvent.isDirectory is false?

Dart VM version: 2.1.0-dev.8.0 (Unknown timestamp) on "linux_x64"

**Comment by ZichangG** [comment]
This is because underlying [inotify](http://man7.org/linux/man-pages/man7/inotify.7.html) doesn't set the isDir bit. FileSystemDeleteEvent.isDirectory comes directly from IN_ISDIR bit.
Besides, from dart api page, [isDirectory](https://api.dartlang.org/stable/2.5.2/dart-io/FileSystemEvent/isDirectory.html) says, 
> In particular, it will always be false for delete events.

**Comment by ZichangG** [comment]
But Mac OS does report isDirectory as true if running the sample program. I think this description is not accurate enough.

**Comment by sgrekhov** [comment]
Just retested on Linux (Ubuntu 18).
Dart VM version: 2.6.0-dev.7.0 (Unknown timestamp) on "linux_x64". idDirectory is false

```
FileSystemDeleteEvent('/tmp/test-dir/FVEEZH')
false
```

**Comment by ZichangG** [comment]
Hi @sgrekhov 

I tried to make [changes](https://dart-review.googlesource.com/c/sdk/+/136405) to be consistent with our api doc.

But 2 co19_2 tests complained (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8888003642068032448/+/steps/test_results/0/logs/new_test_failures__logs_/0).

I think they should be changed to be synced with [api page](https://api.dart.dev/stable/2.5.2/dart-io/FileSystemEvent/isDirectory.html).

**Comment by sgrekhov** [comment]
@ZichangG created https://github.com/dart-lang/co19/issues/532 to change co19 tests

**Comment by ZichangG** [comment]
@sgrekhov 
The change has been landed and I approved the test failures. Can you update the tests accordingly?

There are 2 tests to be updated:
io/FileSystemDeleteEvent/isDirectory_A01_t03.dart
io/FileSystemDeleteEvent/isDirectory_A01_t01.dart
