### ISSUE TITLE
Please merge 460451be99d90119c4557d28d28994687a38eeab into stable channel

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#35042]
**commit(s) to merge**: 460451be99d90119c4557d28d28994687a38eeab

**merge instructions**: Merges clean. Review: https://dart-review.googlesource.com/c/sdk/+/82361

**reason**: Finalize the CHANGELOG entry for 2.1.0.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by kevmoo** [comment]
@munificent – do you want this merged to stable or dev?

**Comment by munificent** [comment]
Stable, I think? Maybe both? This is the CHANGELOG for 2.1.0 stable.

**Comment by athomas** [comment]
This is special. We will merge this commit in when we roll dev to stable (that's how it was done for 2.0).

**Comment by athomas** [comment]
This was merged manually in e1e89a6.
