### ISSUE TITLE
'RangeError (index): Index out of range: no indices are valid: 0'.

### ISSUE THREAD

**Issue by CheoWalker** [dart-lang/sdk#35046]
Dart VM version: 1.24.3 (Mon Dec 18 16:57:48 2017) on "linux_x64"
Ubuntu 18.04
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.3-pre.89, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (1 available)

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill), but couldn't. Error message was 'RangeError (index): Index out of range: no indices are valid: 0'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

**Comment by dgrove** [comment]
@a-siva @kmillikin  I've seen two issues reporting this same thing - where do you think the right place for this is?

**Comment by a-siva** [comment]
The Dart VM version here shows "1.24.3" which is a pretty old version, could you please upgrade to a newer installation of Flutter and see if the problem still reproduces.

**Comment by kmillikin** [comment]
It's not always obvious if problems like this are in the VM or the front end.  I'd make sure that both teams (including @aam and @jensjoha) know about problems like this and we'll triage it further from there.

**Comment by vsmenon** [comment]
I'll close this particular bug as the Dart VM version is so old.
