### ISSUE TITLE
frontend server filesystem and fuchsia kernel compiler filesystem are incompatible

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#35058]
The kernel compiler in fuchsia source tree sets up a single root file system. This is used to produce uris such as `fuchsia-source:///topaz/app/foo.dart`:

https://fuchsia.googlesource.com/topaz/+/master/runtime/dart/compiler.dart#110

The frontend server sets up a multiroot filesystem:

https://github.com/dart-lang/sdk/blob/master/pkg/vm/lib/frontend_server.dart#L291

Attempting to configure the multiroot filesystem with a filesystem root and scheme matching the kernel compiler results in an error that it cannot resolve a uri `org-dartlang-sdk:///somthing`. Replacing this filesystem with the version used by the fuchsia kernel compiler works locally.

If switching the filesystem setup used by the frontend_server to be the same as the kernel compiler is not breaking, that would be one solution. Another would be a fuchsia specific frontend server implementation. I'm not familiar enough with the filesystem implementations to say.

**Comment by keertip** [comment]
@aam

**Comment by aam** [comment]
kernel compiler and frontend server should be using same filesystem uri, yes. frontend server gets filesystem uri as a parameter, when invoked. Is it possible for fuchsia flow to use appropriate uri((`fuchsia-source`) when it invokes frontend server?

**Comment by jonahwilliams** [comment]
Passing `--filesystem-root=...` and `--filesystem-scheme=fuchsia-source` to the frontend server results in the exception below. However, it is possible that this is just the result of the `target` being incorrect as well. I'll go ahead and patch my local fork to use the same file system to confirm that the same error happens.

```
Unhandled exception:
[   +1 ms] FileSystemException(uri=org-dartlang-sdk:///third_party/flutter/lib/ui/painting.dart; message=StandardFileSystem
only supports
           file:* and data:* URIs)
[        ] #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
[        ] #1      MultiRootFileSystemEntity._resolveEntity (package:build_integration/file_system/multi_root.dart:64:41)
[        ] <asynchronous suspension>
[        ] #2      MultiRootFileSystemEntity.delegate (package:build_integration/file_system/multi_root.dart:52:27)
[        ] <asynchronous suspension>
[        ] #3      MultiRootFileSystemEntity.exists (package:build_integration/file_system/multi_root.dart:70:41)
[        ] <asynchronous suspension>
[        ] #4      FrontendCompiler.invalidateIfInitializingFromDill (package:vm/frontend_server.dart:429:25)
...
```

**Comment by jonahwilliams** [comment]
Still getting the same exception with the same filesystem patched in

**Comment by aam** [comment]
an update: @jonahwilliams is trying a patch that aligns platform.dill generation scheme with scheme used when compiling actual apps.

**Comment by jonahwilliams** [comment]
Based on our internal discussions we've found a working solution, tentatively closing
