### ISSUE TITLE
domain_edit_dartfix_test fails on analyzer branch

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35055]
In b1cbfab2740075cf1d6df157512bb80147b30f06, I merged the latest code from the master branch to the analyzer branch, including commit 68e2cdc3e63b89b3a283e8395b0ab751adf3eda2 from master, which added `pkg/analysis_server/test/domain_edit_dartfix_test.dart`.  Although this test passes on the master branch where it was introduced, it fails on the analyzer branch with the following stack trace (see for instance [buildbot results](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8930697805494825680/+/steps/analysis_server_unit_tests_shard_2/0/stdout)):

```
  InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
  
  package:analyzer/src/dart/analysis/session.dart 201:7                                AnalysisSessionImpl._checkConsistency
  package:analyzer/src/dart/analysis/session.dart 166:5                                AnalysisSessionImpl.getResolvedUnit
  package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart 57:47  DartChangeBuilderImpl.createFileEditBuilder
  ...
```

I'm able to reproduce the problem locally.  @danrubel, would you mind taking a look?

**Comment by danrubel** [comment]
Fix https://dart-review.googlesource.com/c/sdk/+/82882
