### ISSUE TITLE
Please merge #c7e6cdf into dev channel

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#35056]
**commit(s) to merge**: https://dart.googlesource.com/sdk/+/c7e6cdf81ca2f6113cc132d85d5f73a9441d3643

**merge instructions**: clean merge

**reason**: Updates edit.dartfix to choose move type parameters rather than remove type parameters

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
Merged in version 2.1.0-dev.9.2
