### ISSUE TITLE
Please merge "Fix misc printf format bugs" into dev channel

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#35059]
git checkout 2.1.0-dev.9.1
git cherry-pick a6518386520af63764ad40dde3b53e5e160b9bff  # Merges cleanly
./tools/build.py runtime
./tools/test.py service

Fixes crashes during VM service RPCs responses that include "%", for example from % encoded URIs. See issue #35009.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
Merged in version 2.1.0-dev.9.2
