### ISSUE TITLE
Flutter Dart bug

### ISSUE THREAD

**Issue by komazecDj** [dart-lang/sdk#35053]
1) Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
2) Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"
3) ubuntu 16

Flutter project fired successfully, even tho this error appeared...

**Comment by dgrove** [comment]
There's not enough info here to act on this. Can you please open a new issue with reproduction instructions?
