### ISSUE TITLE
Please merge 0fd4a51e2c805aec79d4d0e42f446f5395c6113a into dev channel

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#35067]
**commit(s) to merge**: 0fd4a51e2c805aec79d4d0e42f446f5395c6113a

**merge instructions**: clean merge

**reason**: Fixes regression since 2.0 that leads to a crash without any useful error messages on the Dart VM.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
Merged in version 2.1.0-dev.9.2
