### ISSUE TITLE
[Constants] Dart2Js Issue for Experimental Flags Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35073]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), all tools will need to add support for experimental flags, if not yet supported. 

Phase 0 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60) 

Reference:
[Dart SDK Process for changes behind experimental flags](https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md)

**Comment by sigmundch** [comment]
Experimental flags are implemented in dart2js.
