### ISSUE TITLE
[Constants-Phase1] CFE Issue for Constants Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35079]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), 

***Analyzer and CFE
**The analyzer and CFE implements support for the new constant and potentially constant expressions behind the experimental flag.
The CFE plans to implement constant evaluation itself, rather than deferring it to the backends. The new constant features will be included in this implementation, so back-ends should not need to implement the new behavior.
If the implementation requires changes to the Kernel format, then backends may need to adapt to that, just as with any other Kernel format change.

Phase 1 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60)

**Comment by danrubel** [comment]
The CFE scanner / parser has been updated to [support the >>> operator](https://dart-review.googlesource.com/c/sdk/+/85421).

**Comment by a-siva** [comment]
@mit should the milestone for this issue be 2.3, I believe we are using 2.3 to denote all issues that need to be fixed for the next release.

**Comment by aartbik** [comment]
@ajcbik

**Comment by mit-mit** [comment]
Moving to 2.3 (I missed the comment above as it was to @mit, not @mit-mit

**Comment by kmillikin** [comment]
Constant evaluation has landed in the CFE behind the experimental feature flag `constant-update-2018`.
