### ISSUE TITLE
[Constants] Intellij Issue for Experimental Flags Implementation #35073

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35076]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), all tools will need to add support for experimental flags, if not yet supported. 

Phase 0 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60) 

Reference:
[Dart SDK Process for changes behind experimental flags](https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md)

**Comment by devoncarew** [comment]
For context for https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md#flag-format-for-ui-based-tools-ideseditorsetc, my understanding is that the analysis options will be controlled by the analysis_options.yaml file, and the runtime options will be controlled by ensuring that launch configs can pass flags through to the VM / flutter_tools.

We'll just need to verify that launch configs support the passthrough (which I believe that they all do).

**Comment by vsmenon** [comment]
Is there anything to do here?

**Comment by devoncarew** [comment]
I don't believe there's any work here.
