### ISSUE TITLE
[Constants] Analyzer Issue for Experimental Flags Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35072]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), all tools will need to add support for experimental flags, if not yet supported. 

Phase 0 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60) 

Reference:
[Dart SDK Process for changes behind experimental flags](https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md)

**Comment by vsmenon** [comment]
Is this still open?  I think this is just experiments, nothing constant specific, right?

**Comment by stereotype441** [comment]
I believe the work that remains is to code generate the experimental flags from a common file in the front end.

**Comment by vsmenon** [comment]
Do you plan to do that for / before 2.3?  If not, we should drop the milestone.

**Comment by stereotype441** [comment]
> Do you plan to do that for / before 2.3? If not, we should drop the milestone.

That's a question for @kmillikin.

**Comment by mit-mit** [comment]
This is expected out in 2.3. If the work is already complete, please just close this

**Comment by vsmenon** [comment]
As I understand it, all plumbing is done, except we still have two sources of truth (analyzer + cfe - see https://dart-review.googlesource.com/c/sdk/+/98485) instead of one.

We won't block on that, so unless someone says otherwise, let's bump this to 2.4.

**Comment by vsmenon** [comment]
@stereotype441 , actually, if that's all that's left, can you close this and open a new issue for the common file?

**Comment by stereotype441** [comment]
Closed in favor of #36523.
