### ISSUE TITLE
[Constants-Phase1]  Intellij Issue for Constants Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35078]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), 

Intellij/Grok/Dartfmt
Support for the new constant expressions is added to the relevant tooling.

It is very likely that no changes are needed here, as long as the analyzer supports the new expressions. All the affected expressions are already valid non-constant expressions. We may need support more for testing that this is OK

Phase 1 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60)

**Comment by mit-mit** [comment]
cc @devoncarew this was stuck in 2.2.1, is anyone working on this for 2.3?

**Comment by vsmenon** [comment]
Assigning to @devoncarew to triage (@jwren ).

**Comment by jwren** [comment]
Nothing needed in IntelliJ right now for this.

I can't speak for kythe.io or dartfmt
