### ISSUE TITLE
Please merge #cde479301a81f9fbaec3fb007457a4ec8e5a65a7 to dev channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35085]
**commit(s) to merge**: cde479301a81f9fbaec3fb007457a4ec8e5a65a7

**merge instructions**: https://dart-review.googlesource.com/c/sdk/+/83229

**reason**: revert a change that introduced regression in Flutter (please see https://github.com/flutter/flutter/issues/23879)

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment]
Merged in version 2.1.0-dev.9.2

**Comment by whesse** [comment]
Merged in version 2.1.0-dev.9.2
