### ISSUE TITLE
Flaky vm/dart/appjit_determinism_test failure

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35092]
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8930559535403422544/+/steps/vm_tests_shard_2/0/stdout):
```
FAILED: dartk-vm product_x64 vm/dart/appjit_determinism_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 02.000488s):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart/appjit_determinism_test.dart

exit code:
255

stdout:
+ xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --deterministic --snapshot=/b/s/w/it1i5tr1/3f4ZRq/snapshot1 --snapshot-kind=app-jit /b/s/w/ir/runtime/tests/vm/dart/appjit_determinism_test.dart --child
+ xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --deterministic --snapshot=/b/s/w/it1i5tr1/3f4ZRq/snapshot2 --snapshot-kind=app-jit /b/s/w/ir/runtime/tests/vm/dart/appjit_determinism_test.dart --child

stderr:
Unhandled exception:
Expect.fail('Snapshots are not bitwise equal!')
#0      checkDeterministicSnapshot (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m product -n dartk-mac-product-x64 vm/dart/appjit_determinism_test
```

(There were two issues with this test before, in https://github.com/dart-lang/sdk/issues/34638 and https://github.com/dart-lang/sdk/issues/34973, both of which got addressed)

@mraleph 
@rmacnak-google Do you know any recent changes which could've caused this?

**Comment by rmacnak-google** [comment]
No, the most recent changes to raw_object.h look fine.

I'm not having much luck trying to reproduce. I'll update the test to report the position of the difference so next time we can at least say what type of object is different.

**Comment by sjindel-google** [comment]
This reproduced again today, and your debugging statement appears to have triggered: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8930438607350824704/+/steps/vm_tests_shard_2/0/stdout

**Comment by sjindel-google** [comment]
Failed again on https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929890694507142016/+/steps/vm_tests_shard_2/0/stdout.

**Comment by rmacnak-google** [comment]
This one differed in the symbol table:
```
Data + 5f990: array len 2050
Data + 5f994: element 1175
Data + 5f997: element 0
Data + 5f999: element _queryParameters@0150898
Data + 5f99c: element _stateIncomplete@7048458
Data + 5f99f: element sentinel
Data + 5f9a0: element 71
Data + 5f9a3: element sentinel
Data + 5f9a4: element sentinel
Data + 5f9a5: element sentinel
Data + 5f9a6: element _AsyncAwaitCompleter@7048458.
Data + 5f9a9: element escapeDelimiters
Data + 5f9ac: element timerMillisecondClock
Data + 5f9af: element @Timer@Timer._createPeriodicTimer
Data + 5f9b2: element TrustTypeAnnotations
Data + 5f9b5: element isValidKey
Data + 5f9b8: element otherZone
Data + 5f9bb: element sentinel
Data + 5f9bc: element sentinel
Data + 5f9bd: element _currentUriBase@21232984
Data + 5f9c0: element sentinel
Data + 5f9c1: element what
Data + 5f9c4: element sentinel
Data + 5f9c5: element sentinel
Data + 5f9c6: element packageConfigString
Data + 5f9c9: element sentinel
Data + 5f9ca: element sentinel
Data + 5f9cb: element sentinel    ******************first difference is here
Data + 5f9cc: element _closeInternal@1026248
Data + 5f9cf: element sentinel
Data + 5f9d0: element sentinel
```

**Comment by dcharkes** [comment]
Today again:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929427141012865088/+/steps/vm_tests_shard_2/0/stdout

And links for last Friday:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929691224870693440/+/steps/vm_tests_shard_2/0/stdout
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929704572002017296/+/steps/vm_tests_shard_2/0/stdout

**Comment by mraleph** [comment]
Failed again: 

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929056180756921376/+/steps/vm_tests_shard_2/0/stdout

**Comment by mkustermann** [comment]
Flutter has been changed to use `--deterministic` for generating the snapshot (in https://github.com/flutter/flutter/commit/d92d175bcb720eb2a54dae89ff923b7fe829e714 ) and the appjit_determinism test uses `--deterministic` for a long time.

@mraleph / @rmacnak-google Were there any changes which could've fixed this issue?

**Comment by rmacnak-google** [comment]
There haven't been any changes that intentionally addressed this issue, so the flakiness is still a mystery.
