### ISSUE TITLE
Breaking Change Request: Enforce covariance of type variables in super-interfaces

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#35097]
It is currently possible to subvert the Dart type system in the class hierarchy because of a missing check on the use of covariant generic type parameters.  Discussion of the consequences of this can be found [here](https://github.com/dart-lang/language/issues/38), but in short it can cause soundness violations.  We propose to make the problematic uses errors as [described here](https://github.com/dart-lang/language/issues/39).  

**Change Summary**  After this change, using the type parameter of a generic class non-covariantly in a direct super-interface of a class would be an error.  Example:
```dart
class A<X> {};
class B<X> extends A<void Function(X)> {};
```
The definition of `B` would cause a static error after this change.

**Justification** Missing this check allows Dart programs to subvert the type system, resulting in undefined (unsafe) behavior.  For an example, see [this issue](https://github.com/dart-lang/language/issues/38).

**Impact** We expect the impact of this to be minimal.  I have analyzed all internal google code and all of the flutter framework code and found no examples of code which would be impacted by this.

**Mitigation**  We do not expect to be able to provide tooling to migrate any code impacted by this change.  We might consider releasing this as a warning for some number of dev releases (or possibly even a stable release cycle) before promoting it to an error to ensure that users have time to migrate any affected code.

**Comment by matanlurey** [comment]
:+1:, thanks!

**Comment by mit-mit** [comment]
@Hixie LGTM'ed via email

**Comment by leafpetersen** [comment]
@mit-mit LGTM'ed via email

**Comment by mit-mit** [comment]
@leafpetersen what is the timeline for landing this breaking change?

**Comment by leafpetersen** [comment]
Implementation issue is here: https://github.com/dart-lang/language/issues/113 .  It's on the books for Q1, I tentatively marked it with the 2.2 milestone.

**Comment by vsmenon** [comment]
Is this still Q1?

**Comment by kmillikin** [comment]
What is the relative priority of this vs. UI as code?  This is a small amount of work for CFE but we have only a few weeks left in Q1.

**Comment by mit-mit** [comment]
UI as code is more urgent

**Comment by mit-mit** [comment]
cc @leafpetersen remind me, did we send a breaking change notification for this to announce?

**Comment by leafpetersen** [comment]
Yes, I sent out announcements to the usual places.

**Comment by vsmenon** [comment]
@kmillikin @stereotype441 - Leaf added the impl items to 2.3 as P2.  They are soundness issues, but probably rare.  Nice to get done, but lower priority than ui-as-code.

**Comment by leafpetersen** [comment]
It looks like this is going to slip forward another release.

**Comment by dgrove** [comment]
LGTM

**Comment by aadilmaan** [comment]
Leaf - We have all the approvals. You may proceed with this in Dart2.4

**Comment by leafpetersen** [comment]
There should be no bad builds to be marked for flutter from the period in which this had landed in the CFE and not the analyzer.  The last roll of the engine that I see is https://github.com/flutter/flutter/commit/2f6a986675981c2d124f4bf0df4de4d422f7fc3a, which includes commits  `0308a1c4a Roll src/third_party/dart fde6a5917e..e3edfd36b2 (14 commits)` .  That commit range does not include either implementation commit.

**Comment by dgrove** [comment]
What's remaining here?

**Comment by aadilmaan** [comment]
Leaf will do the necessary announce via emails groups once we have a release candidate for D24 but will close this issue for now as no engineering work remains.
