### ISSUE TITLE
Analyzer. For mixin application It is allowed to invoke a noSuchMethod forwarder in a superinvocation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35090]
This is offshoot #34691.

The program below produces an error in analyzer (Dart VM version: 2.1.0-dev.8.0 (Unknown timestamp) on "linux_x64")
`error • The class doesn't have a concrete implementation of the super-invoked member 'g' `

```dart
class A {
  String get g => "g";
}

class C implements A {
  noSuchMethod(Invocation i) {
    print("C.noSuchMethod invoked");
  }
}

mixin M on A {
  test() {
    super.g;
  }

  noSuchMethod(Invocation i) {
    print("M.noSuchMethod invoked");
  }
}

class MA extends C with M {
}

main() {
  print(new MA().g);
  print(new MA().test());
}
```
According to the @eernstg 

> This is a bug in the analyzer: It is allowed to invoke a noSuchMethod forwarder in a superinvocation; for the mixin application C with M, the superclass is C; C implements A, and C has a non-trivial noSuchMethod, so C has a noSuchMethod forwarder for String get g.
> 
> At run time the invocation of super.g in M, when occurring in the mixin application C with M, must invoke that noSuchMethod forwarder which will in turn invoke noSuchMethod; but that method is overridden in C with M by M.noSuchMethod, so the returned value must be "M.noSuchMethod", which is also what we get from dart.

**Comment by lrhn** [comment]
Also, if `C` has been *abstract*, it would not get a nSM-forwarder (only concrete classes need them, so only concrete classes get them), and then the mixin application would be invalid because the super-class `C` does not have a concrete valid implementation of `A.g`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/83881/

**Comment by sgrekhov** [comment]
There is still an error in analyzer
error - The class doesn't have a concrete implementation of the super-invoked member 'g'

dartanalyzer version 2.2.0-dev.0.0 on Windows x64

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/88542
