### ISSUE TITLE
Where is the definition for _Dart_Handle ?

### ISSUE THREAD

**Issue by flybrotherlixiang** [dart-lang/sdk#35101]
`Dart_Handle` is widely used across Dart SDK. According to `dart_api.h`, it's simply an alias for `_Dart_Handle *`. But I can't find the definition for it in source code.
![image](https://user-images.githubusercontent.com/10112726/48188043-ab56b580-e377-11e8-8032-4cabb85685d8.png)

**Comment by mraleph** [comment]
It does not have a definition - it's an opaque pointer. In reality it points to `dart::LocalHandle`. See `Api::UnwrapHandle` in `dart_api_impl.cc`.

Also please don't use issue tracker to ask questions. Instead use [mailing list](https://groups.google.com/a/dartlang.org/forum/#!forum/misc) for that.

**Comment by flybrotherlixiang** [comment]
Thanks a lot! @mraleph
