### ISSUE TITLE
hashCode for double: difference dart/js

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#35116]
If I run the following code in dart2js or in dartdevc
print((10.4).hashCode);
print((10.8).hashCode);

I get 10 in both cases, seems related to https://github.com/dart-lang/sdk/issues/2884

**Comment by matanlurey** [comment]
This might be due to performance considerations for Dart2JS/DDC, since JavaScript doesn't have differentiation between `int` and `double` (all JavaScript numbers are floating point values).

/cc @rakudrama @jmesserly

**Comment by jmesserly** [comment]
Good fine on #2884! This seems to have been fixed for the VM but not other implementations: https://github.com/dart-lang/sdk/commit/1db8615e29cf1e62854d041b805c6d3c43c2225c

We could mix some of the non-integral parts of the JS Number into the hashCode.

**Comment by rakudrama** [comment]
Fixed via ea6d343bae03d8de3662e1467a94f0d13897a8ba

There is one 'num' method for both int and double.

The method is now bigger so no longer gets inlined, so is a little slower for integers.
get:hashCode usually didn't get inlined anyway (e.g. in HashMap implementations it is an interface call).
It is quite a bit slower for non-integers, but presumably this is (1) not very common and (2) there is a benefit from avoiding hash table collisions.
