### ISSUE TITLE
Remove need for recursive monitors from Windows event handler

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#35118]
The event handler implementation is the one place in the VM that requires recursive monitors. We should refactor handle clean up not to require this, allowing us to use cheaper SRWLOCKs for dart::bin::Monitor, and to make Windows consistent with our other platforms, whose monitor implementations are not recursive.

**Comment by mraleph** [comment]
@sortie no the underlying issue is not fixed because even handler was not refactored to avoid use of recursive locking.

**Comment by a-siva** [comment]
Changing priority to P3, not sure there is an immediate need to address this.

**Comment by mraleph** [comment]
Accidentally I have a patch in the works for this because I hit this when trying to share `Mutex` implementation between `bin` and `vm`.
