### ISSUE TITLE
No warning for unreachable break

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#3511]
while(true) {
...
}

gives no warning if the break statement is missing or unreachable.
////////////////////////////////////////////////////////////////////////////////////
Editor Version: 8124

**Comment by srawlins** [comment]
"or unreachable" seems strange to pair with this request. Aren't _any_ unreachable _statements_ just dead code (a warning that already exists).

Or, for the following code, would you like _two_ warnings (DEAD_CODE, INFINITE_LOOP):

```dart
while (true) {
  // no break statements.
  functionThatCouldThrowOrExit();
  // no break statements.
}
```

**Comment by bwilkerson** [comment]
I think he meant "or if the break is unreachable" as in:

    while (true) {
      if (3 < 2) break;
    }

Basically, don't be fooled just because there is a break statement if it can never get you out of the loop.

**Comment by srawlins** [comment]
This is a duplicate of a newer bug which has more information, https://github.com/dart-lang/sdk/issues/29196.
