### ISSUE TITLE
Analyzer does not allow declare a class with typed function parameter if it's parametrized contravariant or invariant.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#35114]
Dart SDK Version: 2.1.0-dev.9.3
OS: Windows 10

This bug is similar with the issues #34689, #34699, but it seems like it's a slightly different case.

Here is a source code example:
``` dart
typedef G<X> = void Function(X);
class A<X extends G> {}

main() {
  G<dynamic> b;
  G<Null> a;
  G<int> c;

  A<G<dynamic>> b1;
  A<G<Null>> a1;
  A<G<int>> c1;
}
```

Seems like all the source lines are valid and should pass.
However, analyzer throws a errors for the lines 10 (`A<G<Null>> a1;`) and 11 (A<G<int>> c1;).

Analyzer sample output is:
```
Analyzing test.dart...
  error - '(Null) -> ’ Null' doesn't extend '(dynamic) -> ’ dynamic' at test.dart:10:5 - type_argument_not_matching_bounds
  error - '(int) -> ’ int' doesn't extend '(dynamic) -> ’ dynamic' at test.dart:11:5 - type_argument_not_matching_bounds
  hint - The value of the local variable 'b' isn't used at test.dart:5:14 - unused_local_variable
  hint - The value of the local variable 'a' isn't used at test.dart:6:11 - unused_local_variable
  hint - The value of the local variable 'c' isn't used at test.dart:7:10 - unused_local_variable
  hint - The value of the local variable 'b1' isn't used at test.dart:9:17 - unused_local_variable
  hint - The value of the local variable 'a1' isn't used at test.dart:10:14 - unused_local_variable
  hint - The value of the local variable 'c1' isn't used at test.dart:11:13 - unused_local_variable
2 errors and 6 hints found.
```
This happens for both contravariant (`typedef G<X> = void Function(X);`) and invariant (`typedef G<X> = void Function(X);`) cases.

The test passes for covariant (`typedef G<X> = X Function();`) and unused parameter (`typedef G<X> = void Function();`).

Dart passes with the line 10 and throw a compile time error for the line 11 here. I am going to file a separate issue about this against runtime.

**Comment by eernstg** [comment]
The treatment of these situations depends critically on the outcome of [CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140).

If it is landed then all lines in `main` are OK (and a raw `G` means `G<Null>`).

If it is _not_ landed then we're hit by the inconsistency that caused me to create that CL: Variance at top-level is ignored, so a raw `G` means `G<dynamic>`. Then `A<G<Null>>` and `A<G<int>>` are not regular-bounded (`<: G<dynamic>` fails for both `G<Null>` and `G<int>`). For the super-boundedness check, we need to check whether `A<G<Object>>` is regular-bounded (which it is) and whether `A<G<int>>` is regular-bounded (which it's not). So if we don't have 80140 then the type annotation of `c1` is a compile-time error, and the rest is OK.

**Comment by eernstg** [comment]
[CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140) landed Dec 2018. The rules have changed a couple of times since then, so it's time to revisit this issue.

In particular, the raw `G` used as a bound means `G<dynamic>`.

Today, I get the following errors from the analyzer (of 8f9113d9f1cb11400c384a4ac68fc050636cf573):

```
ERROR|COMPILE_TIME_ERROR|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/202108/n035.dart|11|5|6|'void Function(int)' doesn't conform to the bound 'void Function(dynamic)' of the type parameter 'X'.
ERROR|COMPILE_TIME_ERROR|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/202108/n035.dart|10|5|7|'void Function(Null)' doesn't conform to the bound 'void Function(dynamic)' of the type parameter 'X'.
```

and the following from `dart` (same commit):

```
n035.dart:10:14: Error: Type argument 'void Function(Null)' doesn't conform to the bound 'void Function(dynamic)' of the type variable 'X' on 'A'.
Try changing type arguments so that they conform to the bounds.
  A<G<Null>> a1;
             ^
n035.dart:2:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends G> {}
        ^
n035.dart:11:13: Error: Type argument 'void Function(int)' doesn't conform to the bound 'void Function(dynamic)' of the type variable 'X' on 'A'.
Try changing type arguments so that they conform to the bounds.
  A<G<int>> c1;
            ^
n035.dart:2:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends G> {}
        ^
```

These error messages are correct for a test where null safety is enabled. In a test without null safety the type `A<G<Null>>` is superbounded, so in that case there should not be an error, and that is also the behavior I see from both tools.

So at this point we can close this issue, because there are no known issues with tools connected to the topic of this issue.

However, there may be a need to change some co19 tests (to expect an error on line 10 and 11) and co19_2 tests (to expect an error on line 11). I created https://github.com/dart-lang/co19/issues/1178 to handle this.
