### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by shinyford** [dart-lang/sdk#35129]
Just got the following error:

Launching lib/main.dart on iPhone XR in debug mode...
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

I'm not sure what the actual problem was, however: it went on to compile perfectly.

Doctor:

[✓] Flutter (Channel dev, v0.11.0, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.11.0 at /Users/nicford/development/flutter
    • Framework revision c319b890b3 (11 days ago), 2018-10-29 19:44:36 -0700
    • Engine revision 162b2e98c0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/nicford/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/nicford/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone XR • 3BD28F85-9698-4D2E-B7EE-D9F60127725C • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by a-siva** [comment]
This appears to be another instance of #36032

**Comment by a-siva** [comment]
Closing as duplicate.
