### ISSUE TITLE
(Set Literals) Intellij Support

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35126]
***** Request: 
As per implementation Plan:

Task7 : Task0 (Intellij support)
IntelliJ parser supports set literals

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by devoncarew** [comment]
@alexander-doroshko, is there any work here for the IntelliJ parser? The proposal here (https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md) has the deltas to the language grammar. I believe the syntax is final, and implementation has started in the analyzer.

**Comment by alexander-doroshko** [comment]
@devoncarew Thanks for the heads up, I've updated the parser on our end (https://youtrack.jetbrains.com/issue/WEB-36102)

**Comment by mit-mit** [comment]
Is this done?

**Comment by alexander-doroshko** [comment]
@mit-mit yes
