### ISSUE TITLE
(Set Literals) CFE Issue - Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35122]
***** Request: 
As per implementation Plan:

Task2 : Task1 (CFE implementation)
The CFE implements support for set literals (errors and warnings, constant evaluation, and any required changes to support the backends).

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by kmillikin** [comment]
Set literal support has been added to Kernel and the Fasta compiler.

We do not yet signal all the static errors related to constant set literals because we do not yet perform constant evaluation.  This behavior is on consistent with the behavior of constant map literals.
