### ISSUE TITLE
(Set Literals) DDC Support

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35123]
***** Request: 
As per implementation Plan:
Task4 : Task3 (DDC implementation)
DDC implements backend support.

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by kmillikin** [comment]
Is this fully implemented?

**Comment by jmesserly** [comment]
yeah, this is fully implemented.
