### ISSUE TITLE
(Set Literals) Dart2JS Support

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35125]
***** Request: 
As per implementation Plan:

Task6 : Task2 (dart2js support)
- [ ] [dart2js implements backend support]()
****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by kmillikin** [comment]
Is this fully implemented? 

/cc @sigmundch

**Comment by sigmundch** [comment]
Yes! (modulo error messages that would be in common with anything that the CFE has to do)

We are adding a lowering of set literals within dart2js, but I consider that an optimization to track separately.
