### ISSUE TITLE
overridden members of a mixin do not get 'overrides method' decorations

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35127]
In IntelliJ, overridden members of a mixin do not get 'overrides method' decorations. I assume that we're not traversing into `mixin` types when reporting overridden method events to IDEs?

@yjbanov, does that capture the issue you hit correctly?

cc @scheglov 

<img width="428" alt="screen shot 2018-11-09 at 7 25 56 pm" src="https://user-images.githubusercontent.com/1269969/48297091-5c7f4d80-e455-11e8-9018-b3fb1af06b86.png">

**Comment by bwilkerson** [comment]
Do we get these decorations if a class is used as a mixin?

**Comment by yjbanov** [comment]
That's a correct description AFAICT.

> Do we get these decorations if a class is used as a mixin?

Yes, a `class` with a `with` clause will get the decoration and following it does take me to the correct place.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/91690

![image](https://user-images.githubusercontent.com/384794/52029284-6c905180-24c7-11e9-85f1-2971dfc14daa.png)
