### ISSUE TITLE
(Set Literals) CFE Issue (Parsing Support)

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35121]
***** Request: 
As per implementation Plan:

Task1 : Task0 (Parsing support)
The CFE implements parsing support for the new literal syntax.

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by stereotype441** [comment]
I believe @danrubel is planning to work on this

**Comment by danrubel** [comment]
Parsing support for set literals has landed as of https://dart-review.googlesource.com/c/sdk/+/84561.
To enable this support in your tests, set the [parser.parseSetLiterals](https://dart-review.googlesource.com/c/sdk/+/84561/3/pkg/front_end/lib/src/fasta/parser/parser.dart#264) flag to `true`.
