### ISSUE TITLE
Unable to determine final token position for script with no source

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#35130]
When trying to fix parts of #34070, I noticed that we can't calculate the last token position or any token position in the final line of a script when we have no source. This is due to the fact that the [SourceInfo](https://github.com/dart-lang/sdk/blame/master/pkg/kernel/binary.md#L93) doesn't contain a field which can be used to determine the number of tokens in a script. 

To get around this issue, either the `lineStarts` list should be modified to include information about the last line or a `tokenCount` field should be added. This is blocking #34070.

**Comment by jensjoha** [comment]
I find it unclear what you're asking.

Are we talking about `Script::TokenRangeAtLine`? That's at least the only place I can find where the source is used without directly wanting the actual source string too.

That function, though, is only used in the debugger which is only interested in actual TokenOffset.
For all intends and purpose this function could be modeled on `Script::GenerateLineNumberArray()` which works without source (i.e. for the special case of the last line call `debug_positions()` and use the last entry there).

**Comment by bkonyi** [comment]
Yes, you're right. I didn't realize I could grab that from `debug_positions()`. Thanks!
