### ISSUE TITLE
'--package-root' doesn't work on 2.1.0-dev.6.0

### ISSUE THREAD

**Issue by iklyaus** [dart-lang/sdk#35138]
My case is to deploy VM application, including all its dependencies, to the server. To run it I've set '--package-root' and point to the packages directory that is placed in the same folder as my app.
The result is:
Error: Could not resolve the package 'di' in 'package:di/di.dart'.
(and more lines below)......

File .packages is removed.

The workaround is to generate .packages and specify **FULL** paths (relative paths don't work too).

**Comment by kevmoo** [comment]
We removed support for package directories entirely. The workaround is the solution – although it sounds like full paths are an issue when you deploy?

**Comment by iklyaus** [comment]
Hmm... Relative paths work locally and don't work on the server. So, the problem on our side! We'll continue investigation...

Thank you guys!
