### ISSUE TITLE
await for doesn't run if I just add stream output to buffer

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#35135]
I am using `flutter_bluetooth_serial` library, and trying to gather all data into a buffer:
```
await for (String msg in _bluetooth.onRead()) {
      //print(msg);
      _buffer.add(msg);
    }
```

Some times its doesn't work at all, or works weirdly, until I uncomment the print line.

```
[√] Flutter (Channel dev, v0.11.3, on Microsoft Windows [Version 10.0.17134.376], locale en-US)
    • Flutter version 0.11.3 at C:\Flutter
    • Framework revision 72bf075e8d (2 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

```

**Comment by matanlurey** [comment]
Based on [how `flutter_bluetooth_serial` is implemented][1], I can't see any clear reason why the code above will work. Unfortunately, I don't know what `_buffer` is, so we're going to need a more full code sample to help you debug this.

[1]: https://github.com/edufolly/flutter_bluetooth_serial/blob/master/lib/flutter_bluetooth_serial.dart#L49-L50
