### ISSUE TITLE
unecessary_cast false-positive

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35140]
_From @zoechi on November 11, 2018 16:11_

```dart
  @override
  BuiltList<Node> get childNodes =>
      (ListBuilder<Node>(directives as Iterable ?? <Node>[])
            ..addAll(selections))
          .build();

  @nullable
  BuiltList<Directive> get directives;

  BuiltList<Selection> get selections;
```
`Directive` and `Selection` implement `Node`

![image](https://user-images.githubusercontent.com/405837/48315303-b8bcab80-e5d4-11e8-9c87-8e693a4f3d0a.png)

![image](https://user-images.githubusercontent.com/405837/48315306-c8d48b00-e5d4-11e8-9e07-647fd1b4729f.png)

_Copied from original issue: dart-lang/linter#1260_

**Comment by pq** [comment]
This is actually an analyzer hint and should be tracked in the SDK...

**Comment by srawlins** [comment]
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/34150
