### ISSUE TITLE
Lack in RawDatagramSocket.bind() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35147]
Please see https://api.dartlang.org/stable/2.0.0/dart-io/RawDatagramSocket/bind.html
Please, add something like this

`If port has the value 0 an ephemeral port will be chosen by the system. The actual port used can be retrieved using the port getter.`

Also add description ot other parameters. 
`bool reuseAddress: true, bool reusePort: false, int ttl: 1`

**Comment by EPNW** [comment]
Please also document what the dynamic `host` may be, and how `InternetAddress.anyIPv4 ` and `InternetAddress.anyIPv6` influence the behaviour.

**Comment by sortie** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/33721
