### ISSUE TITLE
Dart2JS: How to avoid interceptors for JS interop?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#35142]
I have code that ~mostly looks like this:

```dart
@JS()
library js_interop;

import 'package:js/js.dart';

@JS('self')
external MyGlobals get myGlobals;

@JS()
@anonymous
abstract class MyGlobals {
  external List<String> get names;
  set names(List<String> names);
}

void main() {
  var names = myGlobals.names;
  if (names == null) {
    names = myGlobals.names = [];
  }
}
```

This fails, mostly mysteriously, with a `NoSuchMethodError`. While debugging the Dart2JS, I realized that this is going through an Interceptor. The code that is emitted looks something like this:

```js
J.get$names$x = function(receiver) {
  return J.getInterceptor$x(receiver).get$names(receiver);
}

...

JavaScriptObject: {
  get$names: function(obj) {
    return obj.names;
  }
}

...

main: function() {
  var names;
  names = J.get$names$x(self.self);
}
```

-----

Questions:

1. In my head, this would work perfectly fine if instead Dart2JS just emitted:

```js
main: function() {
  var names;
  names = self.names;
}
```

... but I can't tell why it doesn't try to do that. Any pointers? I can point to my internal work.

2. [Low] Is there a way to avoid reading `self.self` in this case?

**Comment by matanlurey** [comment]
@rakudrama:

> Can you avoid trying to define the top level scope, and use a getter/setter for each top-level variable?

Yeah. I could create a set of top-level setters and getters. I'll try that!

> For example defining `MyGlobals g = myGlobals`

Do I need to write specifically that? Does `final g = myGlobals` do the same thing w/ inference?

> A third problem you will have is that ... `List<String>` is not the right type

Ah. I was trying to avoid returning `List<dynamic>`, from your other request that we try and type the returns. If it is `List<dynamic>`, won't Dart2JS consider all native types live again?

**Comment by matanlurey** [comment]
Ping @rakudrama 🏓

**Comment by rakudrama** [comment]
The current native analysis ignores type parameters, so `<dynamic>` should not pull in any new types.

**Comment by matanlurey** [comment]
Thanks! That's enough information for me! Closing.
