### ISSUE TITLE
DDC/Dart2JS: Guidance on JS-interop Arrays, please!

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#35159]
## Problem

We have a e2e testing code path in AngularDart that reads and writes to a global `Array`, i.e. `window.ngTestabilityRegistries`, as an example. If this variable does not exist, the framework creates it (via a _Dart_ `List` literal - `[]`), and if it already exists, the framework just uses it.

It turns out that DDC and Dart2JS do not agree on what a `JSArray` is (via @rakudrama):

> In ES6 it is possible to subclass Array.
>
> I believe DDC uses this feature.
>
> The Dart2JS interceptor code does not recognize these as Arrays.
>
> I am going to investigate using` Array.isArray(x)` in our interceptor code instead of the `x.constructor===Array` check. Last time I checked, `Array.isArray` was slower.

## Resolution

I need either:

1. For Dart2JS to understand sub-classed `Array`s (ES6+ feature)
2. A more temporary path forward to _always_ creating an `Array` directly. Will this work?

```dart
@JS()
library js_Interop;

import 'package:js/js.dart';

@JS('Array')
abstract class _JsArray {
  external factory _JsArray();
}

/// Always creates a normal `window.Array` (in both Dart2JS and DDC).
List<dynamic> createJsArray() => _JsArray() as List;
```

/cc @rakudrama @jmesserly

**Comment by matanlurey** [comment]
Another option is I could monkey patch the `.constructor` property in DDC to make Dart2JS understand it.

**Comment by jmesserly** [comment]
DDC's `List<dynamic>` will be a normal JS array, would that work for you? (subclassing Array is only used for generics)

I agree that dart2js should understand subclassed arrays though.

I'm curious how dart2js is getting a DDC array? Are there like 2 Dart apps on the page, using JS interop to talk to each other or something like that?

**Comment by matanlurey** [comment]
@jmesserly:

> Are there 2 Dart apps on the page, using JS interop to talk to each other...

Yup!

**Comment by jmesserly** [comment]
Here's an example, FWIW:
```dart
@JS()
library foo;

import 'package:js/js.dart';

@JS()
external set ngTestabilityRegistries(List<dynamic> value);

main() {
  ngTestabilityRegistries = [];
}
```
`dartdevc` compiles that to this:
```js
test.main = function() {
  dart.global.ngTestabilityRegistries = [];
};
```
If I add these prints:
```js
  console.log(Array.isArray(dart.global.ngTestabilityRegistries));
  console.log(dart.global.ngTestabilityRegistries.constructor === Array);
```
I get True True

**Comment by matanlurey** [comment]
Thanks!
