### ISSUE TITLE
Error:Cannot access private library

### ISSUE THREAD

**Issue by abhishekchaubey** [dart-lang/sdk#35150]
Trying to access a web-service but added dependecies 

`  http: ^0.12.0
`
But getting below error message from compiler 

```
Compiler message:
lib/login_web_service.dart:1:8: Error: Can't access platform private library.
import 'dart:_http';
       ^
Compiler failed on D:\GitApps\vattendance\flutter_app\lib/main.dart
Gradle task 'assembleDebug'... Done                         22.3s
Gradle task assembleDebug failed with exit code 1
```

**Comment by kevmoo** [comment]
Which version of Flutter are you using?

**Comment by zoechi** [comment]
Might be related to #35009, #32300

**Comment by vsmenon** [comment]
That's an intentional error.  That file can't be imported.  Where is the import?  I don't see a `lib/login_web_service.dart` in `package:http`.  

Closing as this hasn't been updated for a couple weeks.  Please re-open if further info.

**Comment by NoraMansour** [comment]
you can use `import 'dart:convert';`

**Comment by 7uthaifah** [comment]
you can use `import 'dart:convert';`

**Comment by adelbenhamadi** [comment]
fixed  with import 'dart:io' to use HttpHeaders

**Comment by malibayram91** [comment]
fixed with flutter clean
