### ISSUE TITLE
code completion inserts duplicated aliases

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35153]
When importing with an alias, sometimes the aliases show up in the completion list, and selecting the one with the alias does not replace the existing alias, so you end up with two (`a.a.FutureOr`).

![screen shot 2018-11-13 at 11 09 00 am](https://user-images.githubusercontent.com/1078012/48409766-aeb1be80-e734-11e8-8413-d5b56019aead.png)

```
import 'dart:async' as a;

a.Fut
```

```js
{
	"event": "completion.results",
	"params": {
		"id": "12",
		"replacementOffset": 29,
		"replacementLength": 3, // This is only replacing 'Fut'
		"results": [
			// SNIP
			{
				"kind": "INVOCATION",
				"relevance": 1000,
				"completion": "a.FutureOr", // But it's replacing it with 'a.FutureOr'
				"selectionOffset": 10,
				"selectionLength": 0,
				"isDeprecated": false,
				"isPotential": false,
				"docSummary": "A type representing values that are either `Future<T>` or `T`.",
				"docComplete": /*...*/,
				"element": {/* ... */}
			},
			// ...
```

**Comment by bwilkerson** [comment]
@scheglov I expect that code completion is not checking the identity of the elements being added. `Future` is going to be one of the most common occurrences of this behavior because of the fact that it's now re-exported from `dart:core`.

What I don't know is what the performance implications would be to fix this and whether the value of solving this case would justify the cost across all completions.

**Comment by DanTup** [comment]
FWIW, it wasn't Future that I found it on - I just used that to try and make a small test case. It was working on LSP that I kept hitting it (the mappings file imports things with prefixes because there are lots of collisions between the LSP and server type names).

<img width="778" alt="screen shot 2018-11-08 at 10 21 37 am" src="https://user-images.githubusercontent.com/1078012/48192838-ceb23e00-e340-11e8-9c13-a1d0ec4561c8.png">

**Comment by scheglov** [comment]
Seems like something specific to completion in top-level variables after an import prefix.

For example:
![image](https://user-images.githubusercontent.com/384794/48441696-0bb37180-e741-11e8-8f9e-733a2dc1beb9.png)

OTOH, in a function body completion after an import prefix is fine.
![image](https://user-images.githubusercontent.com/384794/48441732-21289b80-e741-11e8-8b70-2851033fe3f9.png)

**Comment by bwilkerson** [comment]
This appears to have been fixed, so I'm going to close it.
