### ISSUE TITLE
Analysis should not mark a member decorated with `@pragma('vm:entry-point')` as unused

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#35164]
The following code:

```dart
@pragma('vm:entry-point')
void _updateUserSettingsData(String jsonData) {
  final Map<String, dynamic> data = json.decode(jsonData);
  _updateTextScaleFactor(data['textScaleFactor'].toDouble());
  _updateAlwaysUse24HourFormat(data['alwaysUse24HourFormat']);
}
```

Results in an analysis error on the method declaration:

> The function '_updateUserSettingsdata' isn't used. [unused_element]

It seems like the analyzer should treat this method as being used, as we're declaring that it's a VM entrypoint and will be called externally from the script.

**Comment by lrhn** [comment]
For the record: Pragmas are for internal use by specific tools. The analyzer is not *expected* to know anything about VM pragmas. If it were, we would need to have some central record of which pragmas exist and what they mean, instead of just letting each tool team pick their own.

Obviously, the analyzer can *choose* to recognize some pragmas, to give a better user experience.
Most normal users should not be using pragmas.

**Comment by lrhn** [comment]
Only the VM team can say what the meaning of `@pragma('vm:entry-point')` is and whether they promise to keep supporting it. It is deliberately not something that the language itself, or any other tool, needs to even know about.

That is why I'm worried if the analyzer does need to understand a foreign pragma.

@a-siva @mraleph

**Comment by mraleph** [comment]
This discussion is much deeper really - presence of pragma just makes explicit something that was always true - VM allows you to call private methods externally so strictly speaking analyzer can never issue a warning about an unused method. 

Pragma makes something that was always possible explicit. 

We are going to continue supporting this particular pragma and we are going to support external users using it to specify entry points in their programs.

**Comment by lrhn** [comment]
The VM also has mirrors, so "unused" is really hard to nail down :smile:.

**Comment by mraleph** [comment]
By the way this specific pragma is described here: https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/aot/entry_points_pragma.md

**Comment by dnfield** [comment]
On a relatively recent version of Dart, these appear to work now, e.g. 

```dart
void main() {}

@pragma('vm:entry-point')
void _privateFoo() {
  print('I can be used');
}
```

passes analysis now with the pragma but not without.
