### ISSUE TITLE
sometimes unable to compute hashCode for ExportElements (analyzer 0.33.3+2)

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#35174]
Discovered while working on dart-lang/dartdoc#1832.  ExportElementImpl's 'identifier' depends on something that is allowed to be null, and so sometimes we can not compute hashCodes for those elements (throws when reading identifier)

```dart
  @override
  LibraryElement get exportedLibrary {
    if (_exportedLibrary == null) {
      if (_unlinkedExportNonPublic != null) {
        LibraryElementImpl library = enclosingElement as LibraryElementImpl;
        _exportedLibrary =
            library.resynthesizerContext.buildExportedLibrary(uri);
      }
    }
    return _exportedLibrary;
  }

  void set exportedLibrary(LibraryElement exportedLibrary) {
    _assertNotResynthesized(_unlinkedExportNonPublic);
    _exportedLibrary = exportedLibrary;
  }

  @override
  String get identifier => exportedLibrary.name;
```

**Comment by jcollins-g** [comment]
I've worked around requiring this so it is not blocking dart-lang/dartdoc#1832.

**Comment by glesica** [comment]
Not sure if this is related, but I noticed that if the export uses a `package:` URI rather than a relative file path (so `package:foo/src/foo.dart` instead of `src/foo.dart`) the `exportedLibrary` getter on the `ExportElement` instance is null.

**Comment by srawlins** [comment]
`LibraryExportElementImpl` now has:


```dart
String get identifier => 'export@$nameOffset';
```

so I believe this is fixed. Re-open if not.
