### ISSUE TITLE
Please stick to C++11 in Dart VM for now

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#35173]
Google-internal host (linux) toolchain is not on C++14 or C++17 yet. They explicitly told us we can build Dart VM that way but it is not supported. 

We currently do build Flutter engine using these unsupported flags but the risk is mitigated by the fact that Android and iOS toolchain _is_ on C++14. For Flutter, only flutter_tester needs to be built on the host toolchain which makes the risk somewhat manageable.

I am opening this issue so we can discuss whether going to C++14 or 17 is a must for Dart VM and whether it is worth the risk of the VM being broken in Google with no real help from toolchain owners.

**Comment by keertip** [comment]
cc/ @a-siva , @mraleph

**Comment by mraleph** [comment]
@sjindel-google updated our build configuration to use C++11 instead of C++14 (see https://dart-review.googlesource.com/c/sdk/+/85202)

We can't use C++14 anyway because Flutter builds 32-bit host binaries with C++11 due to buildroot limitations.

**Comment by mdempsky** [comment]
> We can't use C++14 anyway because Flutter builds 32-bit host binaries with C++11 due to buildroot limitations.

This has been resolved and Flutter now builds with C++14 everywhere: https://github.com/flutter/buildroot/commit/50e07b839afd81dab05e7d77168dbd1a553fc13b

@mehmetf Do you know if Google supports C++14 internally yet? In https://dart-review.googlesource.com/c/sdk/+/101740 we're discussing utilizing std::unique_ptr (C++11) within the Dart VM, and using std::make_unique (C++14) came up. Seems like this is worth revisiting.

**Comment by mdempsky** [comment]
Looks like C++11 compatibility is still required by Google for the foreseeable future. :( Googlers can find details at go/cxx17.

**Comment by mdempsky** [comment]
Update: Google now supports C++17 (Googlers, see go/towt/167).

Also, Flutter uses C++17 on all supported platforms (at least as far as I can tell).

**Comment by mehmetf** [comment]
Not entirely :-/

Unfortunately the Cast toolchain which customer: dream uses is still on C++11 as far as I can tell. Will investigate more.

**Comment by mdempsky** [comment]
[sad react]

**Comment by mdempsky** [comment]
It seems like the Cast toolchain issue is resolved now, and C++17 is available everywhere we're building Flutter.

Are there any other Dart customers still keeping Dart on C++11?
