### ISSUE TITLE
Consistent #include's in public VM APIs

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#35172]
Currently, the #include's in runtime/include/*.h follow two formats:

```c
#include "dart_api.h"
#include "dart_tools_api.h"
```

and

```c
#include "include/dart_tools_api.h"
```

This creates problems when we try to define the includes root. Currently, we have to put in both /runtime/ and /runtime/include as part of -I which seems unnecessary. Can we please standardize? I would much rather we always do #1 (w/o the "include" prefix).

**Comment by keertip** [comment]
@a-siva , this will make it easier to build internally.

**Comment by a-siva** [comment]
Can you elaborate on why you prefer the first option.
In the runtime/vm directory we always use #include "include/dart_api.h" this has been our stated policy and i see that some of the newer files that got added in the 'include' directory do not follow this.

**Comment by mehmetf** [comment]
We currently recommend users of this API to write #include "dart_api.h" in their code as opposed to "include/dart_api.h". The latter makes less sense to me since the prefix __include/__ is not specific to Dart VM.

These users, internally, depend on a single build target which defines the -I flag so they can't modify it. So we either need to tell them to use the include prefix OR have both runtime/ and runtime/include/ as part of -I.
