### ISSUE TITLE
The code in CheckEntryPoint provides a very cryptic message when it encounters a class that needs the entry point pragma

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35170]
The code in CheckEntryPoint in dart_api_impl.cc which checks that a class accessed using the C++ API has the vm entry point pragma produces a very cryptic crash message.

It would be nice if the message indicated which class was being accessed from which library so that the class could be easily fixed.

The code RELEASE_ASSERT(klass.has_pragma())
could be converted to an explicit check with an error message and a call to FATAL

**Comment by mraleph** [comment]
I already have a fix for this yesterday in https://dart-review.googlesource.com/c/sdk/+/84435

**Comment by a-siva** [comment]
Didn't realize you were working on this, this was going to be Liam's starter bug to make sure he had the correct git setup for the Dart and Flutter projects. I will find him another one.
