### ISSUE TITLE
Type test operator `is` works unintended for class `final` members

### ISSUE THREAD

**Issue by kikuchy** [dart-lang/sdk#35181]
# Problem

According to [Language Tour](https://www.dartlang.org/guides/language/language-tour#type-test-operators), the combination of `if` statement and `is` operator can omit omit type cast by `as` operator in `if` statement.

But `final` ized class members cannot cast automatically.

```dart
class A {
  final Object a;
  A(this.a);
  void foo() {
    if (a is String) {
      print(a.codeUnits);    // Error: The getter 'codeUnits' isn't defined for the class 'dart.core::Object'.
    }
  }
}
```

`final` ized class members will not be exchanged for another instance, so its type will not change.

I think it should be compiled successfully.

# Environment

* Dart SDK Version (`dart --version`)
    * Dart 2.1.0-dev.5.0.flutter-a2eb050044
* Whether you are using Windows, MacOSX, or Linux (if applicable)
    * MacOSX

**Comment by eernstg** [comment]
This is working as intended. It would be sound to extend the ability to promote a variable to the case where it is a final variable of any kind, but it is actually only supported for local variables (which includes formal parameters of an enclosing function). So it's definitely a useful enhancement (and we have proposals for enhancing promotion in various ways, but it will take a while before it's part of the language), but with the current rules there is no promotion of `a` in your example.

**Comment by eernstg** [comment]
[Here's](https://github.com/dart-lang/sdk/blob/a2dfa75371d9f1924bfd467dbf6ca37f78b88c63/docs/language/dartLangSpec.tex#L11164) the place where you can see that promotion only occurs for local variables.

**Comment by eernstg** [comment]
> I'm looking forward to that proposals becomes part of the language.

Me too. ;-)
