### ISSUE TITLE
Analyzer: Instantiate-to-bound should use computed type arguments in non-cycles.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35191]
Consider the following program:
```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class A<X> {}
class B<X extends A<X>> {}
class C<X extends B<Y>, Y extends A<Y>> {}

main() {
  C source7;
  var fsource7 = toF(source7);
  F<C<B<A<dynamic>>, A<dynamic>>> target7 = fsource7;
}
```
With `dartanalyzer` from 79b85ae94409225d57e9bc78f54a566c896e1aa6 (2018-11-16) we get the following response:
```
  error • A value of type '<Y extends C<B<dynamic>, A<dynamic>>>() → void' can't be assigned to a variable of type '<Y extends C<B<A<dynamic>>, A<dynamic>>>() → void' at n023.dart:13:45 • invalid_assignment
```
But the program should be accepted without errors.

Basically, the use of `F` and `toF` makes it possible to compare static types for equality, and the error message shows that the raw `C` is expanded to `C<B<dynamic>, A<dynamic>>` by instantiate-to-bound.

This implies that the instantiate-to-bound algorithm uses the value `dynamic` for the occurrence of `Y` in the bound `B<Y>` of `X` in `C`. However, it should have been `A<dynamic>`, because step 2 of instantiate-to-bound (search 'if no dependency cycle exists' [here](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md)) says that `Y` should be replaced by the actual value computed for `Y` (because this is a covariant occurrence of `Y`), and that is `A<dynamic>`, as it should be and as we can see in the second type argument to `C`.

PS: The treatment of type aliases during instantiate-to-bound is under discussion in CL 80140, but that topic is unrelated to this issue (that's only about non-covariant variance, and we only have covariance here, and the rule which should be used by the analyzer, but isn't, has been in place since January 2018, af430f37a82).

**Comment by eernstg** [comment]
A further reduction of the situation above was possible:
```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class A<X> {}
class B<X extends Y, Y extends A<Y>> {}

main() {
  B source7;
  var fsource7 = toF(source7);
  F<B<A<dynamic>, A<dynamic>> > target7 = fsource7;
}
```
which causes the following error message:
```
  error • A value of type '<Y extends B<dynamic, A<dynamic>>>() → void' can't be assigned to a variable of type '<Y extends B<A<dynamic>, A<dynamic>>>() → void' at n024.dart:12:43 • invalid_assignment
```
which shows that the raw `B` is taken to mean `B<dynamic, A<dynamic>>`; but it should have been `B<A<dynamic>, A<dynamic>>`, because the i2b value of `Y` in the bound for `X` should be the value obtained by breaking the cycle for `Y`, rather than a plain `dynamic`.

**Comment by srawlins** [comment]
In a null-safe version of the repro above:

```dart
typedef F<X> = void Function<Y extends X>();
external F<X> toF<X>(X x);

class A<X> {}
class B<X extends Y, Y extends A<Y>> {}

f(B source7) {
  var fsource7 = toF(source7);
  F<B<A<dynamic>, A<dynamic>> > target7 = fsource7;
}
```

the analyzer gives zero errors.
