### ISSUE TITLE
DartDoc build failure on Dart 2.1

### ISSUE THREAD

**Issue by shamblett** [dart-lang/sdk#35190]
* Dart SDK Version Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

Switched to Dart 2.1 sdk, upgrading packages gives me 

Working dir: C:\dev\dart\projects\mqtt_client
C:\dev\dart\dart-sdk\bin\pub.bat get
Resolving dependencies...
Got dependencies!
Precompiling executables...
Failed to precompile dartdoc:dartdoc:
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:3193:19: Error: The return type of the method 'ModelElement::modelType' is dartdoc.element_type::ElementType, which does not match the return type of the overridden method (dartdoc.element_type::DefinedElementType).
Change to a subtype of dartdoc.element_type::DefinedElementType.
  ElementType get modelType {
                  ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:5352:26: Context: This is the overridden method ('modelType').
  DefinedElementType get modelType;
                         ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:419:7: Context: Both members are inherited by the non-abstract class 'Class'.
class Class extends ModelElement
      ^^^^^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:3193:19: Error: The return type of the method 'ModelElement::modelType' is dartdoc.element_type::ElementType, which does not match the return type of the overridden method (dartdoc.element_type::DefinedElementType).
Change to a subtype of dartdoc.element_type::DefinedElementType.
  ElementType get modelType {
                  ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:5352:26: Context: This is the overridden method ('modelType').
  DefinedElementType get modelType;
                         ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:1071:7: Context: Both members are inherited by the non-abstract class 'Constructor'.
class Constructor extends ModelElement
      ^^^^^^^^^^^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:3193:19: Error: The return type of the method 'ModelElement::modelType' is dartdoc.element_type::ElementType, which does not match the return type of the overridden method (dartdoc.element_type::DefinedElementType).
Change to a subtype of dartdoc.element_type::DefinedElementType.
  ElementType get modelType {
                  ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:5352:26: Context: This is the overridden method ('modelType').
  DefinedElementType get modelType;
                         ^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:1287:7: Context: Both members are inherited by the non-abstract class 'Enum'.
class Enum extends Class {
      ^^^^
file:///C:/Users/shamblett/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.20.4/lib/src/model.dart:3193:19: Error: The return type of the method 'ModelElement::modelType' is dartdoc.element_type::ElementType, which does not match the return type of the overridden method (dartdoc.element_type::DefinedElementType).
Change to a subtype of dartdoc.element_type::DefinedElementType.
  ElementType get modelType {
                  ^
Process finished with exit code 0

**Comment by jcollins-g** [comment]
That is a very old version of dartdoc.  Dartdoc >=0.24.0 is recommended for Dart 2.1.
