### ISSUE TITLE
New test results workflow broken if a test step fails and returns empty results.log

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35200]
An example of the flakiness analysis of test results failing is in the two builds after https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/dart2js-strong-linux-x64-firefox/1774

This build fails with a test.py timeout in the dart2js-extra tests step.  This step produces no results, and no results are uploaded to the cloud storage for build 1774 and this test suite.

On the next build, all the tests in this suite are seen as new (because they are compared with latest), and 50 of them are sent for deflaking.  All of the new tests are reported as passing or failing.  It also seems like all the dart2js_extra tests are missing from approved_results.json.   This is the result of my running the approved_results script at exactly this point when the latest results had no entries for this suite.  There was no warning that we were removing a whole suite's worth of approved results, that had no matches in the current results.

After this point, all the results from the suite show up as passing and failing new tests, and the failing ones turn the build red.

There should be better treatment of the case when a test suite fails to run, and produces no results. The approve_results script should detect if a lot of test's results get deleted, and show a warning.

**Comment by sortie** [comment]
I believe this is a problem in the recipe. The recipe should not upload results if the builder did not run correctly (infra failures / test.py timing out). The tools are able to handle gaps in the build numbers thanks to the latest mechanism. If test.py times out, the builder should fail with an infra problem, stop running any more steps (especially the upload step), and turn the builder purple. Then the address can be resolved and the scripts will continue to work normally (except no new results come in on the builders, but they don't do anything bad). Why didn't the timing out test.py step turn red? It says 0 tests ran, why didn't it time out that test way before the 20 min timeout for everything?

Or perhaps there's a legitimate case where test.py timing out should upload degraded test results? But I would argue we shouldn't smooth over these problems and turn the bot purple and deal with it. We should monitor the time taken for these steps and ensure they're not anywhere near the timeout, which should just be an overall safety. We could potentially drop the test.py timeout in favor of a bot wide timeout. Normally we should just be dealing with single tests timing out, not the whole thing timing out overall.

Handling these tools in the scripts using the data just makes things more complicated, and detecting this case would be a bit error prone, as it would also happen if a suite/many tests are just deleted (which is fine). I don't think that's the right place to handle this.

**Comment by sortie** [comment]
Would I be right to say <https://chromium-review.googlesource.com/c/chromium/tools/build/+/1370052> would fix this problem? Unless that doesn't cause the whole builder to abort if there's a problem.

**Comment by sortie** [comment]
I don't believe this is a problem anymore and any remnants is the intended behavior.
