### ISSUE TITLE
nativeSetOption can return an OSError but specifies bool

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#35207]
https://github.com/dart-lang/sdk/blob/a9abc6461395e3327c7d3c22095ea3bf3de3d075/runtime/bin/socket_patch.dart#L1148-L1149

Some of the other `native` methods omit a return type and get an implicit `dynamic` for this reason - the return value is checked to see if it's an `OSError` before trying to use it.

The caller here even tries that:
https://github.com/dart-lang/sdk/blob/a9abc6461395e3327c7d3c22095ea3bf3de3d075/runtime/bin/socket_patch.dart#L1082-L1083

However we get a type error before we can because the signature only allows `bool`.

See https://github.com/dart-lang/http/issues/214

**Comment by ZichangG** [comment]
This should be fixed with https://dart-review.googlesource.com/c/sdk/+/137140
