### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by danasugu** [dart-lang/sdk#35204]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900, 1366x768`

**Comment by stereotype441** [comment]
Was there an error message reported?  Usually we can't act on a bug unless we can see the error message, and ideally a stack trace.  See for example https://github.com/dart-lang/sdk/issues/35206 for the type of information we're looing for.

**Comment by stereotype441** [comment]
I'm closing this issue since we haven't heard a response.  @danasugu, please feel free to reopen if you see this issue again and can capture additional info.
