### ISSUE TITLE
Missing comma in parameter list not found as error

### ISSUE THREAD

**Issue by firsthour** [dart-lang/sdk#35213]
Dart version: 2.1.0-dev.9.2
Windows 10
Found in:
Android Studio version 3.2.1
Dart plugin version 181.5656

Part of the issue reported to the Dart plugin team at https://youtrack.jetbrains.com/issue/WEB-35833

Very simple class with an error:

`class Test { static void test(String a String b) {} }`

Notice the lack of comma between "String a" and String b".

Dart Analysis does not report a compiler error here. It seems fine with the missing comma.

**Comment by alexander-doroshko** [comment]
I'd also add that `dartfmt foo.dart` throws an error in this case:
```
Hit a bug in the formatter when formatting foo.dart.
The formatter produced unexpected output. Input was:
class Test { static void test(String a String b) {} }
Which formatted to:
class Test {
  static void test(String a, String b) {}
}

Please report at github.com/dart-lang/dart_style/issues.
```
I can report it at https://github.com/dart-lang/dart_style/issues if needed but I guess that the fix for this issue may fix the dartfmt issue automatically.

**Comment by lrhn** [comment]
I think the dartfmt issue comes from the analyzer front-end parsing the input as `String a, String b`. Then dartfmt formats that and writes it, and then fails its sanity check that the output only differs from the input on whitespace. If the analyzer front-end had rejected the input (as it should), then dartfmt would never get to that point.
