### ISSUE TITLE
Issue with Directory.rename() and Directory.renameSync()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35217]
According to the [Directory.rename()](https://api.dartlang.org/stable/2.1.0/dart-io/Directory/rename.html) and [Directory.renameSync()](https://api.dartlang.org/stable/2.1.0/dart-io/Directory/renameSync.html) documentation

> If newPath identifies an existing directory, that directory is replaced.

An existing directory is replaced only when it's empty. If if is not empty an error occurs. I believe, it's expected, but documentation should be updated to reflect it

Dart VM version: 2.1.0-dev.9.4 (Unknown timestamp) on "linux_x64"

**Comment by brianquinlan** [comment]
As @sortie hinted, the behavior on Windows is very dangerous:
https://github.com/dart-lang/sdk/issues/47633
https://github.com/dart-lang/sdk/issues/47634

I'd like to fix those two bugs and then bring the documentation in line with the actual semantics.

**Comment by brianquinlan** [comment]
I fixed the documentation in 0e5f3f49c3917c838b13b79afdaf262d4b1b5d3d
