### ISSUE TITLE
close_sinks rule false positive ? 

### ISSUE THREAD

**Issue by jaumard** [dart-lang/sdk#35221]
With the following code: 

```
TransactionReceiptBloc() {
    final loadTransactionController = StreamController<int>(sync: true);
    transactionId = loadTransactionController.sink;
  }

  void close() {
    transactionId.close();
  }
```

dart analyzer still warn about sink not closed, but it is. Or do I miss something ? 

ENV: 
Dart VM version: 2.1.0-dev.9.4.flutter-f9ebf21297 (Thu Nov 8 23:00:07 2018 +0100) on "macos_x64"

**Comment by lukepighetti** [comment]
It looks like your close function is outside of your Bloc class. Can you confirm?

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1381
