### ISSUE TITLE
VM ignores return value from Utf8::DecodeTo*

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#35222]
If `String::FromUTF8` is given invalid UTF-8 I think we get a String back with garbage data in it (or whatever data was at that memory before). Or does the garbage collector null out data?

Example:
E.g. byte sequence C0 00 00 00 00 (0b11000000 0b00000000 0b00000000 0b00000000 0b00000000)
 * CodeUnitCount will say length 5, type kLatin1
 * It'll allocate a OneByteString of length 5
 * Run Utf8::Decode to decode
 * num_trail_bytes = 2; look at 0x01 and set is_malformed to true because IsTrailByte says false. Puts -1 into "ch".
 * Utf8::DecodeToLatin1 sees the -1 and returns false
 * String::FromUTF8 ignores the false and simply returns strobj.raw();

**Comment by zguo93** [comment]
Hi Jensjoha,
Could you address where you get invalid input byte sequence? It helps me understand what need to be done with invalid byte sequence, instead of simply returning null.

**Comment by jensjoha** [comment]
Ideally you wouldn't --- I think one would have to tamper with a dill file to get into such a situation.

**Comment by zguo93** [comment]
Great! if that's the case, a null return will not create other issues. Currently, FromUTF8() will return null if it found invalid input. Thanks for addressing the issue.
