### ISSUE TITLE
RangeError in _ClassVerifier._checkForMismatchedAccessorTypes

### ISSUE THREAD

**Issue by ZubairKh** [dart-lang/sdk#35223]
Analyzer Feedback from IntelliJ (Android Studio)

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1280x800, 1920x1080  Retina`

I am working on Flutter app in Android Studio after latest upgrade I am now getting the following below exception.

# Exception

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/...projectDirs.../lib/firebase/firestore_manager.dart context: exception_20181120_142532_983
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap

```

# Flutter Doctor Result

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.7, on Mac OS X 10.13.6 17G65, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

• No issues found!

Any type of help is much appreciated 👍

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/86080
