### ISSUE TITLE
Please merge cb883470871af88a4ffba54f5d2cadf6eb7fa315 and e4a5ab06e4c128d3440caad00e4d4196a80a1c72 into stable channel

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35232]
@whesse @mit-mit @kasperl

This provides a minimal implementation of #35162 for Dart 2.1.1.  Namely, it causes a hint to be shown if the user attempts to use `Future` or `Stream` without importing `dart:async`, and their pubspec indicates that they support a version of the SDK prior to those symbols being exported from `dart:core`.

The implementation addresses just the first two checkboxes from #35162.  That is, it does not include logic to trigger re-analysis of the hint if the pubspec changes, and it does not include quick fixes to allow the user to correct the hint with a few clicks.

Revisions to be merged:
- cb883470871af88a4ffba54f5d2cadf6eb7fa315
- e4a5ab06e4c128d3440caad00e4d4196a80a1c72

Note: these CLs cherry-pick cleanly to stable, but they result in an SDK that is unbuildable due to an extraneous import.  See https://dart-review.googlesource.com/c/sdk/+/84980 for the proper fix to the conflict.

**Comment by whesse** [comment]
@athomas @JekCharlsonYu

**Comment by stereotype441** [comment]
Note that we may not want to cherry-pick this until #35290 is fixed.

**Comment by bwilkerson** [comment]
#35290 has been fixed by https://dart-review.googlesource.com/c/sdk/+/85620, so as long as we also cherry pick that fix, we should be good to go.

**Comment by stereotype441** [comment]
Ok, I've updated https://dart-review.googlesource.com/c/sdk/+/84980 to include a cherry-pick of https://dart-review.googlesource.com/c/sdk/+/85620, so landing that CL should now be a sufficient fix.

**Comment by athomas** [comment]
Even though we haven't cherry-picked this, it was included in the full pushes we did for 2.1.1.
