### ISSUE TITLE
Error before my code is run

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#35250]
I encountered the following problem when trying to run my code using IntelliJ IDEA.  The following is from the chrome console window.
...........

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
require.js:143 Uncaught Error: Script error for "web/drpond", needed by: drpond.dart.bootstrap
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
drpond.ddc.js.errors:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
drpond.dart.bootstrap.js:135 Unknown error loading http://localhost:53584/drpond.ddc.js

.......

 I tried commenting out the new code changes and got the same problem.   I tried updating dependencies and rebuilding and got the same problem.
 I then put the changes back (uncommented) and the problem disappeared.    
 I can no longer duplicate the problem.

**Comment by natebosch** [comment]
Next time you encounter this, check on the console where the development server is running and see if there are build errors - those could lead to 500 errors when trying to load the compiled result.

**Comment by drpond1** [comment]
I am reasonably certain there were no build errors due to the web app code.

  I just tried upgrading dependencies,  rebuilding, and running.   I
started to have a problem,  At first it could not find the server,
but I was eventually able to get it to work.  This is not quite the same
behavior as reported
in November.

I did see the following in the current log
[SEVERE] Terminating builds due to package graph update, please restart the
build.
[INFO] Terminating. No further builds will be scheduled.

[INFO] Builds finished. Safe to exit


With Dart 2.0 I started using

build_runner: ^0.10.0
build_web_compilers: ^0.4.0

So, a change in Dart might cause the dependencies to be

 unexpectedly updated.  This would then lead to package updates

  possibly interfering with a build that I was not expecting.


But I really don't know.

**Comment by natebosch** [comment]
We do expect a running server to terminate on a package or SDK update.

You'll also want to update to the newer versions of `build_runner` and `build_web_compilers`.

If you're still running in to issues after that please file an issue over at https://github.com/dart-lang/build/issues
