### ISSUE TITLE
Failed to create dart projects in IntelliJ IDEA version 18.3

### ISSUE THREAD

**Issue by micrcx** [dart-lang/sdk#35256]
In IntelliJ IDEA version 18.3, after updating the plug-in of dart, the problem of creating projects on dart from scratch arose: the operation "Loading Dart project templates ..." begins and continues indefinitely. Apparently there are simply no templates. But also error messages are absent.

**_NB! Current dart version: 2.1.0-dev.3.0._**

**Comment by alexander-doroshko** [comment]
I guess this has been fixed quite a while ago (tracked as https://youtrack.jetbrains.com/issue/WEB-35995). Feel free to close the issue, I don't have permissions here.

**Comment by micrcx** [comment]
List of project's templates is appeared. Tnx.
