### ISSUE TITLE
 The for loop scope of the dart language is very strange

### ISSUE THREAD

**Issue by Vadaski** [dart-lang/sdk#35257]
![3471543235068_ pic](https://user-images.githubusercontent.com/23734225/49014094-e2bbc380-f1b9-11e8-8d84-a6a2c1fd8cb1.jpg)

I think that variable i should not be allowed to be defined again in the body of the loop.
Its strange.

**Comment by lrhn** [comment]
Dart allows you to shadow outer variable declarations inside nested code blocks.
You can write:
```dart
foo(int x) { 
  if (something) {
    String x = "foo";
    ... x ...
  }
  ... x ...
}
```
The inner block creates a new scope, and you can declare any variable in there.

It can be argued that it's unnecessary to allow shadowing of a local variable, but it is occasionally useful.

There are no plans to change this part of the language at the current point.
