### ISSUE TITLE
Dart2JS crashes with 255 error, if several builds are running simultaneously

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/sdk#35255]
dart: Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "linux_x64"

After migration to Dart2.0.0 we've faced new issue with dart2js compilation:
When our continuous integration system tries to run several dart2js processes simultaneously (in different docker-containers on the same physical machine), most of them will fail with 255 error code.
But serial (non-simultaneous) compilation is mostly successful.

Beside same CPU and memory, that docker-containers also share pub-cache folder.
I suggest, that the reason is lack of some resources (for example, file descriptors). The problem is, dart2js process tells no specific details, even with --verbose flag:
```
Info: Using platform configuration at file:///ci-syst/5/dart-sdk/2.0.0/lib/dart_client.platform
Info: Compiling file:///root/branch_builder/.dart_tool/build/dart2js/dart2js_MNISOY/wrike_ws.index.dart (2.0.0)
Inputs: [file:///root/branch_builder/.dart_tool/build/dart2js/dart2js_MNISOY/wrike_ws.index.dart]
Output: null
Was error handler provided: yes
FileSystem: CompilerFileSystem (provided: CompilerFileSystem)
Input Summaries: <empty>
Linked Dependencies:
  - file:///ci-syst/5/dart-sdk/2.0.0/lib/_internal/dart2js_platform_strong.dill
Packages uri: file:///root/branch_builder/.dart_tool/build/dart2js/dart2js_MNISOY/.packages
Packages: null
Compile SDK: false
SDK root: null (provided: null)
SDK specification: null (provided: file:///ci-syst/5/dart-sdk/2.0.0/lib/libraries.json)
SDK summary: null (provided: null)
Strong: true
Target: null (provided: dart2js)
throwOnErrorsForDebugging: false
throwOnWarningsForDebugging: false
exit on problem: false
Embed sources: true
debugDump: false
verbose: true
verify: false

Info: Resolving...
Info: Resolved 429 elements.
Info: Resolved 1349 elements.
Info: Resolved 1863 elements.
Info: Resolved 2362 elements.

....

Info: All native types marked as used due to _ResolutionWorldImpact(reason)
 type uses:
  TypeUse(Object,TypeUseKind.PARAMETER_CHECK)
 const-literals:
  null
 native-data:
  NativeBehavior(returns: [Object, Null], creates: [Object], sideEffects: SideEffects(reads nothing; writes nothing), throws: may)
  NativeBehavior(returns: [], creates: [], sideEffects: SideEffects(reads nothing; writes nothing), throws: may).
Info: Resolved 1068 native elements used, 0 native elements dead.
Info: Inferring types...

...

Info: Compiled 58494 methods.
Info: Compiled 58749 methods.
Info: Compiled 59000 methods.

(CI log) Process exited with code 255
```

We haven't migrated to Dart2.1 yet.
How do you think, can this help?

Or may be you have some suppositions, what can result in such behaviour?

**Comment by DisDis** [comment]
@jmesserly fyi.

**Comment by mraleph** [comment]
If this is a VM crash there should be some output - does it really terminate like that without anything on stderr? 

/cc @sigmundch

**Comment by yury-yufimov** [comment]
All my attempts to get anything from stderr have failed. But here's something new:
that dart2js processes are run in docker-container, in thread, started by GNU parallel ( https://www.gnu.org/software/parallel/ )
And now I can't reproduce the issue, if I start dart2js without parallel, just from bash-script!
So, let's close the issue for a moment. If it'll return, when dart2js is started directly, I'll reopen it.
