### ISSUE TITLE
Request deletion of package from pub

### ISSUE THREAD

**Issue by aegis123** [dart-lang/sdk#35261]
Is it possible to delete [google_maps_flutter](https://pub.dartlang.org/packages/google_maps_flutter) from pub? It seems it has been uploaded by 5lineofcode@gmail.com but it says the Author is the Flutter Team. Its is also referencing the flutter packages in the original [flutter repository](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter).

Changing the information is also a possibility to make it clear that this is not the flutter team that uploaded it as the readme describes.

But I think the person that uploads it should either fork/extra that plugin and put it in his own repo vs just linking to the original

**Comment by jonasfj** [comment]
I've moved this issue: https://github.com/dart-lang/pub-dartlang-dart/issues/1820

For future reference please prevent people from publishing work-in-progress packages by adding `publish_to: none` to your pubspec.yaml, typically as follows:

```yaml
publish_to: none  # do not publish this package while under active development.
```
