### ISSUE TITLE
'getReference' was called on null

### ISSUE THREAD

**Issue by jwinarske** [dart-lang/sdk#35264]
Flutter 0.11.9 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d48e6e433c (6 days ago) • 2018-11-20 22:05:23 -0500
Engine • revision 5c8147450d
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Android Studio 3.3 RC 1
Build #AI-182.5107.16.33.5138683, built on November 18, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-39-generic

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null.
Receiver: null
Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
Built build/app/outputs/apk/debug/app-debug.apk.

Missing some or all of the above might make the issue take longer or be
impossible to act on.

**Comment by vsmenon** [comment]
@a-siva - not sure how to triage this.

**Comment by jensjoha** [comment]
Thank you for filing the issue. Unfortunately we didn't include enough debug information to actually find and fix this issue. Hopefully it won't happen again, and if it does, the error message now should include more information.
