### ISSUE TITLE
On MacOS abort() can hang the process so it times out.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#35275]
See this CL temporarily adding the timeout status to satisfy flaky MacOS bots:
https://dart-review.googlesource.com/c/sdk/+/85414

**Comment by crelier** [comment]
This is probably the same issue as https://github.com/dart-lang/sdk/issues/35268

**Comment by mraleph** [comment]
I have a hypothesis based on an experiment. I have wrote a binary that does nothing but calls `abort()`. If I run this binary in a shell with `ulimit -c unlimited` then it takes around 10s to finish. If I spin 10 of those binaries in parallel then they each take around a minute to finish. 

It seems that core writing is super slow on Mac. 

So what we think is a hang might actually be just slow core dump production. 

I think the right way to fix this is to change out testing scripts to set `core` ulimit back to `0` when running tests that are expected to crash. 

There is another consideration - those bots only have 100gb free space and each core is actually >1gb.
