### ISSUE TITLE
Function arguments autocompletion

### ISSUE THREAD

**Issue by GreenTigerEye** [dart-lang/sdk#35272]
For IDE's (such as Intellij) there should be a way to autocomplete function arguments.

That's what we want to have completed automatically.
`itemBuilder: (BuildContext context, int index) {}`

![](https://i.stack.imgur.com/n7okg.png)

See [Stackoverflow](https://stackoverflow.com/questions/53483904/flutter-autocomplete-function-arguments-in-intellij?noredirect=1#comment93837582_53483904)

**Comment by xBioDreadx** [comment]
Miss function arguments autocomplete so much!
![image](https://user-images.githubusercontent.com/8358357/69461861-371f6200-0d80-11ea-86c0-800e1f9b1563.png)
Just show me some colors, it will be so much easier!

**Comment by dexcell** [comment]
+1

**Comment by srawlins** [comment]
+1

**Comment by scheglov** [comment]
@pq implemented this initially in e0c178b38e632b6af1b18c63285034a7a5eab600
