### ISSUE TITLE
Analyzer: Interface ambiguity not detected

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35280]
Cf. issue #35278, `dartanalyzer` fails to report an error for a declaration of a class whose interface contains an ambiguous member signature (that is, none of the superinterfaces provide a member signature whose function type is a subtype of that of them all). Here is an example:

```dart
abstract class O {}
abstract class P { O f(O o); }
class OI implements O {}
class PI implements P { OI f(covariant OI o) => null; }
class P2I extends PI implements P {}
```

In this situation, `P2I` has superinterfaces `PI` and `P`, and they provide member signatures with function types `O Function(O)` respectively `OI Function(OI)` for `f`, and none of those is a subtype of the other.

So the computation of the interface of `P2I` fails because none of the signatures for `f` can be used, and this should be reported as a compile-time error.

Presumably, the reason why this case has not been covered before is that we have covariance for a parameter in `PI`, which makes that signature an unlikely candidate for being a subtype of the others (because it will have a more special argument type), but at the same time that signature offers a covariantly specialized return type (which makes it likely that other signatures will not be subtypes of this one). So in that sense it's a worst case scenario, and this combination of a covariant return type and a covariant parameter type is likely to create a similar conflict whenever it is used.

From a practical point of view, the developer can disambiguate the code by adding an explicit (possibly abstract) declaration of `f` in the body of `P2I`: `OI f(OI o);`. But it is an error when there is no such declaration, following the general principle that we do not invent signatures that do not occur in the program.

We actually discussed (in #31596) how to select the signature for a method when there is an inherited declaration with a more special argument type and some source of covariance, and I argued in https://github.com/dart-lang/sdk/issues/31596#issuecomment-355571973 that we could get a better typing in some situations by allowing such signatures to become the signature of that member in the interface of the class (even though they correspond to function types that are not subtypes of them all: `OI Function(OI)` is not a subtype of `O Function(O)`), but we ended up concluding that it is only the function type of the signature that matters.

**Comment by srawlins** [comment]
Analyzer now reports an error for `P2I`:

> Superinterfaces don't have a valid override for 'f': PI.f (OI Function(OI)), P.f (O Function(O)).
