### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by alam1251** [dart-lang/sdk#35285]
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'RangeError (index): Index out of range: no indices are valid: 0'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

**Comment by vsmenon** [comment]
This may be related to #35264 - "previous compilation" error.

**Comment by jensjoha** [comment]
Thank you for filing the issue. Unfortunately we didn't include enough debug information to actually find and fix this issue. Hopefully it won't happen again, and if it does, the error message now should include more information.
