### ISSUE TITLE
run co19 debug tests with release compiler

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35296]
Some co19 tests in debug mode are _really_ slow because the compiler itself also runs in debug mode:

```
$ tools/test.py -m debug co19_2/LibTest/collection/ListMixin/ListMixin_class_A01_t02
tools/testing/dart/main.dart:1: Warning: Interpreting this as package URI, 'package:test_dart/main.dart'.
Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: mac, vm-options: [], timeout: null, preview-dart-2)
Suites tested: co19_2
[03:38 | 100% | +    1 | -    0]
```

@mraleph suggested that we should change the configuration such that the compiler itself runs in release mode.

@mkustermann would this be possible?

**Comment by mkustermann** [comment]
I think changing the way we run tests **depending on test suite** (like co19) is not a good idea. There's nothing which makes co19 more special than language_2 or other test suites we have.

For sim* architectures we compile tests to .dill files separately and run them then on the debug VM. We do this to avoid running the kernel isolate in simulated mode, which can be very slow.

For x64 we have an app-jit trained kernel-isolate, which should run fast (it's generated code) so there's no need to do the same as for sim* architectures.

What is this particular test doing? Maybe some of the co19 tests should be re-written do **do less work**.

**Comment by dcharkes** [comment]
It is calling 

* `/tests/co19_2/src/LibTest/core/List/sort_A01_t04.test.dart`
* `/tests/co19_2/src/LibTest/core/List/sort_A01_t05.test.dart`
* `/tests/co19_2/src/LibTest/core/List/sort_A01_t06.test.dart`

which sort huge lists of numbers.

**Comment by dcharkes** [comment]
I will look into making these tests smaller or splitting them. (Let's track progress in the other issue.)
