### ISSUE TITLE
d3 is not compitable with Dart2

### ISSUE THREAD

**Issue by it-avenger** [dart-lang/sdk#35293]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by it-avenger** [comment]
I am using Dart 2.1.0 and d3 0.2.0.
It says d3 dart package is not compitable.

**Comment by mraleph** [comment]
This package is not part of the Dart SDK. 

You should file this issue at https://github.com/rwl/d3.dart/issues

However it does not look actively maintained - so your best bet is to fork the package and fix those issues yourself.
