### ISSUE TITLE
Detection of SDK constraint violation has a false positive with references in combinators

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#35290]
References to `Future` and `Stream` that occur in combinators should not be flagged. Even if the classes are inappropriately in the namespace via `dart:core`, the issue will be flagged at the use site.

To reproduce, create a file containing
```dart
export 'dart:async' show Future;
```

**Comment by stereotype441** [comment]
Note: this issue is in the Dart2.1.1 milestone because it is a bug in #35162, which we are currently trying to cherry-pick to 2.1.1 (see cherry-pick request #35232).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/85620
