### ISSUE TITLE
DAS refactorings should not include Dart SDK files and gen files

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#35301]
See context in https://github.com/JetBrains/intellij-plugins/pull/627 and https://github.com/JetBrains/intellij-plugins/commit/f4baabc8bed2ead69b799c86df5b17cd34c68d97

The Dart Analysis Server/ Analyzer should make decisions on behalf of clients not return SDK/ generated files/ pub cache files as part of refactoring and quick fixes.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/86040
