### ISSUE TITLE
Analyzer: Odd treatment of promoted type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35306]
Consider the following program:
```dart
class A {}
class B extends A {}

void f<X extends A, Y extends B>(X x) {
  if (x is Y) {
    A a = x;
    B b = x;
    X x2 = x;
    Y y = x;
  }
}
```
`dartanalyzer` version 2.2.0-dev.0.0 reports errors for this program as follows:
```
  error • A value of type 'X' can't be assigned to a variable of type 'A' at n006.dart:10:11 • invalid_assignment
  error • A value of type 'X' can't be assigned to a variable of type 'B' at n006.dart:11:11 • invalid_assignment
  error • A value of type 'X (/usr/local/google/home/eernst/lang/dart/scratch/201812/n006.dart)' can't be assigned to a variable of type 'X (/usr/local/google/home/eernst/lang/dart/scratch/201812/n006.dart)' at n006.dart:12:12 • invalid_assignment
```
First, promotion of `x` does not take place, even though `Y` is guaranteed to be a type which is a subtype of the bound of `X` (so `x` should have been promoted to have type `X & Y`).

The most surprising error is that a value of type `X` can't be assigned to a value of type `X`. Presumably there is some additional structure to those types that make them spuriously different.

Next, if we really trust `x` to have type `X`, the fact that `X` has bound `A` should justify assignment to a variable of type `A`: It's a plain upcast.

If we had promoted `x` to have type `X & Y` then we would also have allowed the assignment to a variable of type `B`, because `X & Y <: Y <: B`, again a plain upcast.

Finally, the assignment to `Y` should be allowed with a promotion (to `Y`!), but given that promotion did not take place we have a variable of type `X` and a target type `Y`, and they are unrelated. So we have at least an inconsistency here.

**Comment by leafpetersen** [comment]
@stereotype441 I believe that strong mode promotion should promote `x` to have type `X extends Y` (which @eernstg is writing `X & Y`) because `Y extends B` and `B extends A` and hence while we cannot promote `x` from `X` to `Y`, we allow promotion of the bound of `X` to `Y`.  See line 1296 of type_system.dart.  

I believe that given such a promotion, all of the assignments in that example should be valid (no errors).

**Comment by eernstg** [comment]
> given [..] promotion [..] all of the assignments in that example should be valid

That was also the way I saw it.

PS: About the terminology, I'd be a little bit worried about saying 'we allow promotion of the bound of `X` to `Y`' because the type test does not establish any additional guarantees about `X`, it's only about the type of the value of `x`. But I guess that's also the intention behind those words.

**Comment by MichaelRFairhurst** [comment]
It looks like we don't use TypeSystem in this, but call `type.isMoreSpecificThan`. That is dart 1 semantics. This is probably the cause.

**Comment by leafpetersen** [comment]
> About the terminology, I'd be a little bit worried about saying...

The analyzer associates bounds not with the declaration of a type variable (alone) but with each reference to a type variable.  Not the way I'm used to thinking about it, but it's reasonable.  So in the terminology above, when I say "the bound of `X`", I don't mean the bound on the declaration of `X`, I mean the bound on the specific instance of `X` which classifies `x`.

**Comment by eernstg** [comment]
> "the bound of `X` [means] the bound on the specific instance of `X` which classifies `x`.

As far as I can see, this means that the declared bound of `X` will be inaccessible if a variable `v` of type `X` is promoted to a type of the form `X extends S` (which is a notation for `X & S` that emphasizes that `S` is simply considered to be the bound of `X`).

In that case it's _essential_ that promotion to a type `X & S` is only allowed when `S` is a subtype of the declared bound of `X`. This is also a constraint that I have had in mind, and it is indeed what we have specified in the upcoming [CL 85921](https://dart-review.googlesource.com/c/sdk/+/85921).

This is one of the properties that makes types of the form `X & S` different from intersection types in a general form.

But it's not reflected in the current behavior of the analyzer, which _will_ allow promotion from `X` to `X & S` in some cases where `S` is _not_ a subtype of the bound of `X` (cf. #35305). But I expect that we will just get that fixed.

Another matter is that  we may make other mistakes if we just use a promoted type variable type `X extends S` as evidence that `X` has bound `S`. Consider this example, which is accepted by `dartanalyzer` (versions 2.2.0-dev.0.0 as well as a fresh one from commit 5451ac62e26caeacd8a8c4a660ac320bdf9c84f3) without errors:

```dart
class A<X extends int> {
  A() { print(X); }
}

A<X> g<X extends int>(X x) => A<X>();

void f<X extends num, Y extends X>(Y y) {
  if (y is int) {
    g(y); // This is the interesting statement!
  }
}

main() {
  f<num, num>(42);
}
```

In this example, an invocation of `g` is accepted, which means that some type parameter `U` was inferred. The type `U` must satisfy `U <: int` in order to satisfy the declared bound on the type parameter of `g`, and it must also be a type which is assignable to the type of `y` (otherwise it would be an error to pass `y` as an actual argument). Given that `y` is actually promoted to `Y extends int`, it looks like the inferred type argument `U` was `Y extends int`, which could hardly mean anything else than `Y`, except that we have the extra assumption that `Y <: int`.

Of course, if this program were allowed to run, the actual value of `Y` would be `num`, and we would then, presumably, create an instance of type `A<num>`, which is a soundness violation (because the body of `A` can contain code that relies on `X <: int`). In particular, there is no evidence at the point of creation (that is, the body of `g`) that there is a need to check that the value of `X` is a subtype of `int`.

So it looks like it is not just the promoted variable which is treated as if it had type `Y extends int`, it is actually also the type variable `Y` itself which is, in some contexts, considered to have that bound.

This brings us back to something which is closely related to #35100, albeit from a different angle (in that issue, the focus was on having one value of a type argument for static analysis, and another one at run time; in this context the issue is that we make unsound assumptions about the bound of a type variable).

This makes me conclude that it is, at least, necessary to be rather careful if one wants to think that promotion to a type of the form `X & S` actually yields a type variable with a modified bound.

**Comment by eernstg** [comment]
Cf. the example [here](https://github.com/dart-lang/sdk/issues/35306#issuecomment-444821466),
the conclusion `int <: X` is reached, even though we only know `X <: num` (and, in particular, we could have `X == double`).

It could be caused by a spurious recursive step ("to check that `int` is a subtype of the bound of `Y`, we need to check that `int <: X`; but the bound of `X` is `num`, so we just check `int <: num`, yep!" ;-).

But it is never correct to assume, for a type variable `X` with bound `U` that `T <: X` just because `T <: U`, so the check which is being performed at that step cannot be a subtype check (because it cannot possibly be the case that the general subtype check is implemented such that it makes that mistake), and it is probably the "check that `int` is a subtype of the bound of `Y`" that, mistakenly, checks against the bound of the bound (maybe continuing with the bound of that, etc., until it finds a bound which is not a type variable).
