### ISSUE TITLE
Specification: Specify how a promoted type variable type (X & S) is handled in a type test

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35314]
Promotion of the type of a local variable `v` can give rise to a type of the form `X & S` when the static type of `v` is `X`, `S` is a subtype of the bound of `X`, and a test of the form `v is S` is known to have evaluated to `true`:

```dart
void f<X>(X x) {
  if (x is int) {
    // In this block, `x` is known to have type `X & int`.
  }
}
```
The language specification currently does not specify this case at all, and this issue is concerned with adding language to specify it. A likely spot to edit is [here](https://github.com/dart-lang/sdk/blob/e7a048d12e64e7ab4ccb08d82f9ce9f0246698eb/docs/language/dartLangSpec.tex#L9739).

**Comment by eernstg** [comment]
Created a CL with a proposed update: https://dart-review.googlesource.com/85921.

**Comment by chingjun** [comment]
I just hit a similar case, but without variable type involved: 

```dart
class A {}
class B {
  int b;
}
class C extends A implements B {
  int b;
}

void main() {
  A x = C();
  if (x is B) {
    // In this block, the type of `x` is known to be `A & B`
    x.b = 3;
  }
}
```

**Comment by eernstg** [comment]
I'm closing this issue. It is very old, and the mechanism has been specified in detail in newer documents. In particular:

- [The null-safety specification](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md).
- [The null-safety subtype rules](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md).
- [Flow analysis specification](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md).
- [Inference specification](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md).

@chingjun wrote:

> I just hit a similar case, but without variable type involved:

```dart
void main() {
  A x = C();
  if (x is B) { // No promotion, `B` is not a subtype of `A`.
    x.b = 3; // Error, `A` does not have a `b`.
  }
}
```

This case is actually different: Dart supports only a very special case when it comes to intersection types: They can be of the form `X & S` where `X` is a type variable, and `S` must be a subtype of the bound of `X`. So there is no type like `A & B` in Dart, and hence we can't promote `x` to have any such type.

You'd use a fresh local variable to get the promotion:

```dart
class A {}

class B {
  int b;
  B(this.b); // Needed with null safety, `b` can't be uninitialized.
}

class C extends A implements B {
  int b;
  C(this.b); // Needed with null safety.
}

void main() {
  A x = C(0);
  Object y = x; // To be promoted, hence a supertype of `A` and of the target `B`.
  if (y is B) y.b = 3; // `y` promoted to `B`.
}
```
