### ISSUE TITLE
AOT treeshaker should remove unused fields

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#35310]
A few classes in the Flutter framework have `_debug*` fields, that are only accessed from within asserts. It would be cool if the treeshaker could remove these fields in release builds where they are not used and never accessed.

This should help with reducing Flutter's memory footprint when running an app and it will also slightly reduce the AOT snapshot size on disk.

/cc @rmacnak-google 

Related: https://github.com/dart-lang/sdk/issues/35303, if that's implemented even more fields are going to be unused in release mode.

**Comment by mraleph** [comment]
Currently TFA does not seem to distinguish whether some field is only written to or both written to and read from. 

It seems if we add the distinction then tree shaking would become trivial. 

/cc @alexmarkov @sjindel-google
