### ISSUE TITLE
Dart Socket listener skipping the response data

### ISSUE THREAD

**Issue by dileep4g** [dart-lang/sdk#35313]
using dart-sdk version :-2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822

connected with server from following program,while receiving response listener skips some data (ex:-check following Server response deta1 and data2 received properly data3 is skipped, if we put sleep 1 sec before data3 from server code then it is working)

following client code

```dart
import 'dart:io';
import 'dart:core';
import 'dart:typed_data';

void main() async {
  try {
    const Duration ReceiveTimeout = const Duration(milliseconds: 5000);
    await Socket.connect("localhost", 8081).then((socket) {
      socket.setOption(SocketOption.tcpNoDelay, true);
      socket.timeout(ReceiveTimeout);
      socket.listen((data) {
        List packetData = (new Uint8List.fromList(data).buffer.asUint8List());
        print(packetData); //printing response
      });
      socket
          .add([255, 10, 81, 0, 1, 2, 5, 53, 50, 51, 51, 54]); //sending Request
    }).catchError((e) {});
  } catch (e) {
    print("error:");
  }
}
```

following Server Response data1, data2 and data3 server sends in header.

```
byte[] data1=new byte[]{127, 77, 0, 101, 0, 1, 2, 39, 75, 5, 53, 50, 51, 51, 54, 48, 126, 40, 0, 122, 66, 41, 0, 125, 30, 0, 0, 76, 53, 41, 0, 124, 123, 40, 0, 122, 44, 41, 0, 124, 18, 41, 0, 38, 122, 40, 0, 80, 0, 0, 0, 46, 122, 40, 0, 20, 0, 0, 0, 60, 30, 0, 0, 122, 27, 0, 0, 122, 122, 55, 73, 0, 0, 0, 0, 20, 0, 0, 0, 0};

byte[] data2=new byte[]{127, 28, 0, 101, 0, 1, 2, 42, 26, 5, 53, 50, 51, 51, 54, 73, 34, 37, 0, 122, 98, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0};

byte[] data3=new byte[]{127, 26, 0, 101, 0, 1, 2, 12, 24, 5, 53, 50, 51, 51, 54, 32, 122, 0, 0, 35, 122, 40, 0, 20, 0, 0, 0, 1, 48};
```

**Comment by mraleph** [comment]
@dileep4g could you also provide the server code to make the reproduction completely runnable, so that we could test it locally? 

Also please provide information about your OS and its version (e.g. is it Linux, Windows, Mac, which version etc)

**Comment by dileep4g** [comment]
@mraleph can You please check my previous comment in the above i shared what You needed Server Code and OS version.

**Comment by mraleph** [comment]
I can reproduce. I see that all the bytes that are send from Java side arrive to Dart side - however they arrive merged together. Which is expected.

You should expecting that messages that you send arrive as separate.

Please change your Dart test to verify that your data is received fully (but merged) and reopen this issue if you find that data is lost.

**Comment by raygun101** [comment]
I see this issue as well.
If the server sends data immediately when receiving a client connect request.

var socket = await SecureSocket.connect(this.host, this.port, timeout: timeout);
socket.listen(...

It's like the stream adds the data before you can attach a listener. (so it's lost)
