### ISSUE TITLE
KBC mode crashes DebugIA32 mode

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#35319]
DartFuzz crashed on KBC-INT-DebugIA32
To repro (fill in own path):

> gen_kernel --gen-bytecode --platform=$TOP/out/DebugIA32/vm_platform_strong.dill -o out.dill fuzz.dart 
> $TOP/out/DebugIA32/dart --enable-interpreter --compilation-counter-threshold=-1 out.dill

Result:

> ===== CRASH =====
> version=2.2.0-edge.aae0f7997de4d06df22766a089bc2eb18cb24e2d (Mon Dec 3 18:07:39 2018 +0000) on "linux_ia32"
> si_signo=Trace/breakpoint trap(5), si_code=128, si_addr=(nil)
> thread=255482, isolate=out.dill:main()(0x29b0c00)
>   [0xf7940821] Unknown symbol
>   [0xf7940821] Unknown symbol
>   [0xf6c633d2] Unknown symbol
>   [0xf6c62988] Unknown symbol
>   [0xf6c481f5] Unknown symbol
>   [0xf6c626d5] Unknown symbol
>   [0xf7940b70] Unknown symbol
>   [0x01545331] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
>   [0x01544ef8] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
>   [0x015483fa] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
>   [0x01580b2a] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>   [0x015bb801] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>   [0x015bc474] dart::MessageHandler::TaskCallback()
>   [0x015bd96c] Unknown symbol
>   [0x017392df] dart::ThreadPool::Worker::Loop()
>   [0x01738e77] dart::ThreadPool::Worker::Main(unsigned int)
>   [0x01684aed] Unknown symbol
>   [0xf7ec827a] Unknown symbol
> -- End of DumpStackTrace

**Comment by aartbik** [comment]
[fuzz.dart.txt](https://github.com/dart-lang/sdk/files/2645619/fuzz.dart.txt)

**Comment by aartbik** [comment]
The difference seems to be the --enable-interpreter flag and specific to IA32

Crashes:
> $ ${DART_TOP}/out/DebugIA32/dart  --enable-interpreter out.dill 
> $ ${DART_TOP}/out/DebugIA32/dart   --enable-interpreter --compilation-counter-threshold=-1 out.dill

Runs fine:
> $ ${DART_TOP}/out/DebugIA32/dart  out.dill 
> $ ${DART_TOP}/out/DebugIA32/dart  --use-bytecode-compiler out.dill 
> ${DART_TOP}/out/DebugX64/dart  --enable-interpreter --compilation-counter-threshold=-1 out.dill

With output:

> throws
> true
> I😀Q♥😀+
> [-4294967296, 14]
> true
> -2147483649
> 5e-324
> aVi)
> [-4294967296, 14]
> {0: }
>

**Comment by alexmarkov** [comment]
Interpreter is not supported on 32-bit architectures, so please remove any configurations involving --enable-interpreter from IA32 and 32-bit ARM fuzzing.

**Comment by aartbik** [comment]
Ah, that explains a lot. Strange that it started just now. I will modify the execution modes.

**Comment by aartbik** [comment]
OK, I will make sure fuzzer never tests these combinations. Don't we want to report a bit friendlier message though, like we do for AOT IA32?

**Comment by aartbik** [comment]
The massive failures were caused by, the issue above was just due to using the wrong scripts while reproducing. Fix for build issue is out for review.

fail1:
pkg/vm/lib/kernel_front_end.dart:13:8: Error: Error when reading 'pkg/build_integration/lib/file_system/multi_root.dart': No such file or directory
import 'package:build_integration/file_system/multi_root.dart'
       ^
pkg/vm/lib/kernel_front_end.dart:481:22: Error: Method not found: 'MultiRootFileSystem'.
    fileSystem = new MultiRootFileSystem(
                     ^^^^^^^^^^^^^^^^^^^
