### ISSUE TITLE
Compiler ignores invalid escape sequences

### ISSUE THREAD

**Issue by joe776** [dart-lang/sdk#35312]
For example `'z' == '\z'` is true, and `print('\z')` outputs `z`. It looks like the parser/compiler simply ignores the backslash if it does not recognize the escape sequence. I would have expected this to be a compile time error (like in Java strings, for example).

* Dart SDK Version (`dart --version`): 2.1.0 stable
* Whether you are using Windows, MacOSX, or Linux (if applicable): n/a
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): n/a

**Comment by joe776** [comment]
Thank you! I didn't read far enough.
Some typos were exactly our problem. As this is a minor issue and likely a breaking change, I also don't think it's happening. I'll close this issue then.

**Comment by eernstg** [comment]
Thanks! Note that there is a loophole for supporting checks on code that have no semantics without venturing into actual language updates: Lints. So you could consider moving this request to https://github.com/dart-lang/linter.

**Comment by joe776** [comment]
I created a WIP pull request there: https://github.com/dart-lang/linter/pull/1295
Thank you!
