### ISSUE TITLE
feature: Please add monorepo support for pubspec 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#35327]
monorepo is a term (I think) from the node-section.
It describes a way having a base project with some subprojects. These subprojects share infos and configs (mainly version constraints and settings) with their parent.
Sharing version constraints in pubspec with a parent folder would be very helpful.

**Comment by MikeMitterer** [comment]
Update: The TypeScript way: https://blog.bitsrc.io/so-whats-new-in-typescript-3-2-1ab82e83db94#85b3

**Comment by matanlurey** [comment]
Something like this is managed outside of the SDK here: https://github.com/dart-lang/mono_repo.
