### ISSUE TITLE
Mixin lost generic type

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#35322]
When I ran dartfix over [this example file](https://github.com/dart-lang/site-www/blob/e341ab20b3b7e5127df6618dab0635c4416e0ccc/examples/misc/lib/language_tour/operators.dart#L48), the class that was converted to use `mixin` lost its generic type:

```diff
-abstract class Builder<T> {
+mixin Builder {
   T build();
 }
```

Analysis fails for the resulting class and the classes that use it as a mixin (PhoneNumberBuilder, AddressBookBuilder).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/86223
