### ISSUE TITLE
Specification: Specify static analysis of function body execution that "falls through" at the end

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35330]
The language specification is currently silent on the treatment of the situation where a function body completes normally (that is, we reach the end rather than reaching an explicit return statement), but it should say that this situation is treated like encountering an explicit `return;` which is added at the end of the function body.

This means that, for instance, we will make it an error to fall through in a function with return type `int`:

```dart
int f() {
} // Error, as if `return;` had been added at the end of the body.
```

However, in the case where the location just after the body cannot be reached, we do not wish to emit an error:

```dart
int f() {
  return 42;
} // No error: Body will return a value, cannot complete normally.
```

The property of being unreachable is obviously undecidable in general, so we will approximate it conservatively (as in "this location can definitely not be reached", as opposed to "this location cannot be proven to be reachable"). So we may still raise an error in a situation where the end of the body cannot actually be reached, but that's a fact that we cannot prove. Consequently, some function bodies will need to contain code which is semantically unreachable, but in return we get the guarantee that no function execution will fall through at the end, except for the ones where `return;` would be OK.

We will probably want to specify a notion of having an explicit return or throw statement on every path in the control flow graph, possibly including known-infinite loops, evaluation of expressions of type bottom (if we add such a type, evaluation of such an expression will not complete normally), and whatever else is considered worthwhile.

Currently, the specification says that the notion of being statically unreachable will be specified in the future, and this issue is concerned with doing that.

**Comment by eernstg** [comment]
> The subject and lead-in sounds like this is about the dynamic behavior.

No, this is intended to be about the static analysis, and about compile-time errors, which is also the reason why I wrote

> The property of being unreachable is obviously undecidable in general, so we will approximate it 

Adjusted the title to make this explicit.

**Comment by lrhn** [comment]
> and pragmatically non-stupid. ;-)

You just *had* to add that, didn't you?!

**Comment by eernstg** [comment]
> You just had to add that, didn't you?!

Of course! ;-)

But, seriously, we _want_ that property, as opposed to the situation where developers are thinking "why can't the compiler understand that we will always return something?" because the static approximation that we've chosen is unable to see that the body could indeed never fall through at the end.

> There goes our normal strategy.

We can still be strategically stupid. ;-)

**Comment by eernstg** [comment]
Transferred to repo language: https://github.com/dart-lang/language/issues/139, please continue the discussion there.
