### ISSUE TITLE
AOT-ReleaseX64 crash divergence

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#35335]
Isolate (/b/s/w/ir/tmp/t/dart_fuzzYMYQOP) AOT-ReleaseX64 - JIT-ReleaseIA32: !DIVERGENCE! 1.2:2915825161 (output=false)

fail1:
../../runtime/vm/compiler/aot/precompiler.cc: 2312: error: unreachable code
thread=27829, isolate=isolate(0x56499373c900)
  [0x000056499136478c] Unknown symbol
  [0x000056499136478c] Unknown symbol
  [0x0000564991565872] Unknown symbol
  [0x000056499141a1e8] Unknown symbol
  [0x000056499141b8fa] Unknown symbol
  [0x0000564991416c25] Unknown symbol
  [0x0000564991415647] Unknown symbol
  [0x00005649914107b4] Unknown symbol
  [0x000056499140e273] Unknown symbol
  [0x000056499140e135] Unknown symbol
  [0x0000564991562f9a] Unknown symbol
  [0x00005649911a016e] Unknown symbol
-- End of DumpStackTrace

**Comment by aartbik** [comment]
Debug AOT crashes as:

> flow_graph_compiler.cc: 951: error: expected: speculative_policy_->AllowsSpeculativeInlining()
```

Label* FlowGraphCompiler::AddDeoptStub(intptr_t deopt_id,
                                       ICData::DeoptReasonId reason,
                                       uint32_t flags) {
....
    ASSERT(speculative_policy_->AllowsSpeculativeInlining());
....
}
```

while release AOT hits the error above:

> runtime/vm/compiler/aot/precompiler.cc: 2333: error: unreachable code
```

bool PrecompileParsedFunctionHelper::Compile(CompilationPipeline* pipeline) {
....
       if (!speculative_policy.AllowsSpeculativeInlining()) {
          // Assert that we don't repeatedly retry speculation.
          UNREACHABLE();
        }
....
}
```

**Comment by aartbik** [comment]
Bit more details:

> Retrying compilation file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart_::_foo3, suppressing inlining of deopt_id:2394
> ../../runtime/vm/compiler/backend/flow_graph_compiler.cc: 947: error: expected: speculative_policy_->AllowsSpeculativeInlining()
> 

which refers to this code:
```
B267[target]:2014
    v9302 <- UnboxInt64(v2198 T{int})
    v2304 <- BinaryInt64Op(% [tr], v9302 T{int}, v2188 T{int}) T{int}
    v9594 <- UnboxedConstant:2394(#10)
    v9596 <- UnboxedConstant:2394(#20)
    v9598 <- UnboxedConstant:2394(#4)
    v9320 <- Unbox:2394(v0 T{Null})
    v9600 <- UnboxedConstant:2394(#5e-324)
    goto:2394 B321
```

**Comment by aartbik** [comment]
The unbox is made speculative during hoisting in LICM, where the following code
```
  GotoInstr* last = pre_header->last_instruction()->AsGoto();
  // Using kind kEffect will not assign a fresh ssa temporary index.
  flow_graph()->InsertBefore(last, current, last->env(), FlowGraph::kEffect);
  current->CopyDeoptIdFrom(*last);
```
puts the deopt of the Goto on the Unbox. Doing this in AOT without proper checks seems wrong.

**Comment by aartbik** [comment]
The problem is that the CanDeoptimize() property changes due to hoisting. The unwritten contract, of course, is that this does not change.
```
about to hoist:
 v9346 <- Unbox(v8916)         can_deopt=F
after hoist:
 v9346 <- Unbox:2394(v8916)    can_deopt=T
```

**Comment by aartbik** [comment]
New nightly run has several failures that are probably very related (since the CanDeoptimize() assert is violated for an UnboxInstr, just like above). So adding one failure here to make sure we verify this once fixed.

JIT-DebugSIMARM - AOT-DebugX64: !DIVERGENCE! 1.2:3494344839 (output=false)

fail2:
../../runtime/vm/compiler/backend/il.cc: 4617: error: expected: CanDeoptimize()

**Comment by aartbik** [comment]
Note, continuing nightly failures with similar error messages. This bug really needs fixing!

**Comment by mraleph** [comment]
I have looked at the graph. 

This happens in the unreachable dead code: we have 

```
B266[join]:64 pred(B1505, B1506)
    CheckNull:2004(v0)
    v8928 <- Redefinition(v0) T{Null}
```

The type of this redefinition is non-Nullable Null - empty set - this should be impossible.

Then this flows into 

```
B320[join]:2386 pred(B318, B319) {
      v2332 <- phi(v729, v8928) alive T{_Double}
}
```

note that `phi` was inferred to have `T{_Double}` because `v729` is `_Double` and `v8928` is essentially impossible type. 

I think we need to be aggressively deleting impossible code like this.

Alternative fix is to make sure that type propagation does not produce impossible types like this:

```dart
diff --git a/runtime/vm/compiler/backend/type_propagator.cc b/runtime/vm/compiler/backend/type_propagator.cc
index c587626f12..791cba021f 100644
--- a/runtime/vm/compiler/backend/type_propagator.cc
+++ b/runtime/vm/compiler/backend/type_propagator.cc
@@ -283,7 +283,7 @@ void FlowGraphTypePropagator::VisitCheckClassId(CheckClassIdInstr* check) {
 void FlowGraphTypePropagator::VisitCheckNull(CheckNullInstr* check) {
   Definition* receiver = check->value()->definition();
   CompileType* type = TypeOf(receiver);
-  if (type->is_nullable()) {
+  if (type->is_nullable() && !type->IsNull()) {
     // Insert redefinition for the receiver to guard against invalid
     // code motion.
     EnsureMoreAccurateRedefinition(check, receiver, type->CopyNonNullable());
@@ -305,7 +305,7 @@ void FlowGraphTypePropagator::CheckNonNullSelector(
   if (target.IsNull()) {
     // If the selector is not defined on Null, we can propagate non-nullness.
     CompileType* type = TypeOf(receiver);
-    if (type->is_nullable()) {
+    if (type->is_nullable() && !type->IsNull()) {
       // Insert redefinition for the receiver to guard against invalid
       // code motion.
       EnsureMoreAccurateRedefinition(call, receiver, type->CopyNonNullable());
```

**Comment by aartbik** [comment]
Seeds to check after fix (it is always the AOT one that crashes):

 AOT-ReleaseX64 - KBC-CMP-ReleaseX64: !DIVERGENCE! 1.2:3060628533 (output=false)
 JIT-MARKSWEEPEVERY-DebugSIMDBC - AOT-ReleaseX64: !DIVERGENCE! 1.2:3495203332 (output=false)
JIT-NOFIELDGUARDS-ReleaseSIMDBC64 - AOT-ReleaseX64: !DIVERGENCE! 1.2:1470560046 (output=false)
AOT-ReleaseX64 - JIT-ReleaseSIMARM: !DIVERGENCE! 1.2:1253864548 (output=false)

**Comment by aartbik** [comment]
Slava's type prop change fixes all known seeds so far!

**Comment by aartbik** [comment]
Note that simply ignoring null may not have been the right solution. We should remove the following dead code, just to make sure it is never hoisted before the check.

**Comment by mraleph** [comment]
As a temporary solution we could still create a redefinition after the `CheckNull` just not set it's type to impossible type.
