### ISSUE TITLE
Analyzer issue with super-bounded type and invariance

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35332]
Just noted that #34906 was closed and the example program is accepted as it should be. :+1:

However, the commit https://github.com/dart-lang/sdk/commit/a88b10ad5a7cfaf4e06e75e4477f656e8bddb5a2 where this was achieved does not quite handle all variances. Here's a slightly different example:

```dart
typedef G<X, Y extends Function(X)> = X Function(Y Function(Y));
class C<Z extends G<num, Function(Object)>> {}

main() {
  C<G<dynamic, Function(Null)>> target; // Should be reported as an error.
}
```

A fresh analyzer (commit 1ca3f3d2cbf9af5602084dd55dc0268a87bae525, which correctly accepts the example in #34906) fails to report an error for this example, even though it should. (Similarly, no error is reported by a fresh vm, same commit, but the error _is_ reported by dartk in a non-landed CL where 80140 is being implemented, so that's being handled, and hence I'll just use area-analyzer in this issue.)

The point is that `C<G<dynamic, Function(Null)>>` is not well-bounded, and this is a compile-time error ([as specified here](https://github.com/dart-lang/sdk/blob/4264f3c619944e4007f22f7838344c31db57eac8/docs/language/dartLangSpec.tex#L4855)): `C<G<dynamic, Function(Null)>>` is only well-bounded if it is regular-bounded or super-bounded. It's easy to see that it is not regular-bounded (`G<dynamic, Function(Null)>` is not a subtype of `G<num, Function(Object)>`, e.g., `dynamic` is not a subtype of `num`).

In order to be super-bounded, we need to perform some "extreme substitutions" (replacing certain occurrences of a top type by `Null` and vice versa, according to the variance), which yields `C<G<Null, Function(Null)>>` (note that `Null` is not replaced by `Object` because it occurs in an invariant position in `G<..., Function(Null)>`, because `Y` of `G` is invariant). The result of these substitutions must then be regular-bounded. But `C<G<Null, Function(Null)>>` is not regular-bounded, because `G<Null, Function(Null)>` is not a subtype of `G<num, Function(Object)>`.

So we have a compile-time error, and it is not reported.

PS: The spec update [CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140) is in the pipeline, and it is concerned with super-bounded types, but the issue reported here exists independently of CL 80140, so this issue is not blocked on the outcome for that CL.

**Comment by stereotype441** [comment]
@MichaelRFairhurst FYI

**Comment by srawlins** [comment]
I think we cover this now... but the error we now report includes the type, `Never`, so I'm not sure... in any case, we report:

> 'Never Function(Never Function(Null) Function(Never Function(Null)))' doesn't conform to the bound 'num Function(dynamic Function(Object) Function(dynamic Function(Object)))' of the type parameter 'Z'.
> Try using a type that is or is a subclass of 'num Function(dynamic Function(Object) Function(dynamic Function(Object)))'.
> The inverted type 'C<Never Function(Never Function(Null) Function(Never Function(Null)))>' is also not regular-bounded, so the type is not well-bounded.

**Comment by eernstg** [comment]
Here is an updated version of the example program:

```dart
typedef G<X, Y extends Function(X)> = X Function(Y Function(Y));
class C<Z extends G<num, Function(Object?)>> {}

main() {
  late C<G<dynamic, Function(Never)>> target;
}
```

The type `C<G<dynamic, Function(Never)>>` is not well-bounded, and we do get a compile-time error from the analyzer (as well as from the CFE), so I think we can close the issue.
