### ISSUE TITLE
Add Atomics to dart:html

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35348]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics

Required to allow no-copy sharing of data with Workers and WASM

See also https://github.com/dart-lang/sdk/issues/35344

**Comment by unicomp21** [comment]
I guess there are no plans for adding atomics?  Or it's low priority?  With the return of SharedArraybuffer, post spectre, these would be really nice to have.

**Comment by unicomp21** [comment]
The babylon_dart repo is progressing nicely, having workers w/ atomics would open up additional opportunities wrt to procgen, etc.

**Comment by unicomp21** [comment]
Think the webkit stuff is progressing too, would be nice if everything came together at the same time ie safari on ios.
