### ISSUE TITLE
Create a public API replacement for TypeSystem

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35346]
(Capturing some in-person discussion between me and @bwilkerson)

Currently the analyzer public API exposes the `TypeSystem` class to clients in three ways:
- `AnalysisSession.typeSystem` returns it
- `ResolveResult.typeSystem` returns it
- `DartType.flattenFutures` requires it as an argument

Several of the methods on `TypeSystem` seem very unlikely to be needed by clients.  We would like to change the public API so that it exposes some other object (with a narrower interface), and relegate `TypeSystem` to be an implementation detail of the analyzer.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/87602
