### ISSUE TITLE
Why List.getRange() is much slower than List.subList() (performance)

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#35352]
From the document it said the `sublist` will return a new list, and  the `getRange` won't.
But from the test result, the creating new list seems the performance is better.

For example,
```
void main() {
  List<int> s = new Uint8List(100000000);
  final sw = new Stopwatch()..start();
  for (int i = 0, j = s.length; i < j; i+= 5) {
    new String.fromCharCodes(s.getRange(i, i+5));
  }
  print('Using getRange(): ${sw.elapsedMilliseconds}ms');
  sw.reset();
  for (int i = 0, j = s.length; i < j; i+= 5) {
    new String.fromCharCodes(s.sublist(i, i+5));
  }
  print('Using subList(): ${sw.elapsedMilliseconds}ms');
}
```
The result in Dart 2.1.0
```
Using getRange(): 4687ms
Using subList(): 2067ms
```
In Dart 1.24.3
```
Using getRange(): 7953ms
Using subList(): 3350ms
```

And Dart is 3 times slower than Java
```
public static void main(String[] args) {
	char[] s = new char[100000000];
	long t1 = System.nanoTime();

	String text;
	for (int i = 0, j = s.length; i < j; i += 5) {
		char[] newString = new char[5];
		System.arraycopy(s, i, newString, 0, 5);
		text = new String(newString);
	}

	System.out.println("time: " + TimeUnit.MILLISECONDS
			.convert(System.nanoTime() - t1, TimeUnit.NANOSECONDS) + "ms");
}
```
Java only takes 708ms.

**Comment by lrhn** [comment]
You are likely hitting an optimization in `String.fromCharCodes`. A `sublist` of an `Uint8List` is again a `Uint8List`, and `String.fromCharCodes` is optimized for `Uint8List` inputs.

If the input is just an `Iterable<int>`, the `String.fromCharCodes` constructor must assume that it can be anything, so it first converts it to a `List<int>` to find the length and then checks that each integer is non-negative and less than 0x10ffff. It then further recognizes that the values are actually less that 256 and creates a one-byte internal string representation. The `Uint8List` input gives all that information, and the total length, directly.

So, creating a new iterable using `getRange` is faster than creating a new list using `sublist`, but *consuming* the iterable is much less efficient.

**Comment by jumperchen** [comment]
@Irhn,

Thanks for the explanation, another issue is that, why the Dart constructing a string from Uint8List takes so much times, comparing with Java, the result is unacceptable, because we use Dart to parse a large XML file in our system, the parsing time is terrible and it seems no way for us to optimize it. (we already get rid of parsing String to speed up, but we still need to construct the String object as result once it required.)
Do you have any suggestion about how to solve it? (The option of changing language is not possible for us at the meantime.)

**Comment by mraleph** [comment]
@jumperchen your benchmark makes `String.fromCharCodes` polymorphic - which makes it slower then it actually should be. 

If you take care of not making it polymorphic then it is at least 2x faster: 

```dart
import 'dart:typed_data';
void main() {
  List<int> s = new Uint8List(100000000);
  final sw = new Stopwatch()..start();
//  for (int i = 0, j = s.length; i < j; i+= 5) {
//    new String.fromCharCodes(s.getRange(i, i+5));
//  }
//  print('Using getRange(): ${sw.elapsedMilliseconds}ms');
//  sw.reset();
  for (int i = 0, j = s.length; i < j; i+= 5) {
    new String.fromCharCodes(s.sublist(i, i+5));
  }
  print('Using subList(): ${sw.elapsedMilliseconds}ms');
}
```

**Comment by jumperchen** [comment]
@mraleph,
Yes, by reversing the executed code, it will be faster.
But the total parsing time is still slower than Java implementation. (from xml to JSON-like map)
The XML file size is about 340MB:
```
1. Java takes: 16 sec.
2. Dart 2 takes: 47 sec. 2.2GB Memory Usage (the implementation as your suggestion.)
```
I will find what's the root cause.

**Comment by jumperchen** [comment]
After a more thorough investigation, here are the causes for the poor performance:
1.	We use Dart Archive library to unzip a zip file, which contains a Deflate compression, the [Archive’s Inflate](https://github.com/brendan-duncan/archive/blob/2827d795ad55b44b9bc1ee9b957e483b2a25ed3b/lib/src/zlib/inflate.dart) uses Dart to implement the decode code that performance run worse than the native implementation from dart:io ZLibDecoder.
2.	We use utf8.decode() to decode the xml content, which may contain utf8 characters.
This is also a performance issue, which is already mentioned in https://github.com/dart-lang/sdk/issues/31954.
3.	We should use command line to run dart code to see the result instead of running in IntelliJ (which opens Dart Observatory causing it to run slower)

After getting rid of the mentioned causes, the Dart 2 performance is as fast as Java, even better. :)

**Comment by mraleph** [comment]
Thank you for the update @jumperchen! Great to hear that performance now is matching your needs :) 

1. I have filed an issue against package `archive` - so that author considers using builtin zlib implementation when that is available.
2. #31954 considers `UTF8.decode` in AOT mode. If you could send us some examples for UTF8.decode slowness in JIT mode (vs Java) then we can also file a separate bug for this in JIT mode.

**Comment by jumperchen** [comment]
@mraleph,

Comparing `utf8.decode` between Dart2 and Java from reading a zip file, there is no more different, so I guess the difference is about the original question `List.getRange() is much slower than List.subList()`, because the result of `utf8.decode` is a string object with its codeUnits `List<int>` (not a Uint8List), and we parse the `List<int>` to construct a string, which won't run into the optimized code like @lrhn said.

Anyway, we'll be upgrading our project from Dart 1 to Dart 2 to gain performance boost. Feel free to close the issue if there is no more concerns.

**Comment by mraleph** [comment]
Okay. I am going to go ahead and close this issue because we don't have any immediate plans to fix `getRange(...)` vs `sublist(...)` as they are inherently different. 

Though if a lot of people would hit the same issue we should consider adding optimizations that detect iterables that are produced from lists and handling them more efficiently inside core libraries.

Let us know if you hit any other performance problems!
