### ISSUE TITLE
Questions about breakpoint resolution / breakpointNumbers

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35368]
In the past I've seen the VM return the same breakpointNumber for multiple requests to set breakpoints when they resolved to the same location (I had to make changes in Dart Code to handle this). However while trying to support breakpoint resolution (something Dart Code has never handled correctly) I discovered this *not* happening (which is causing other problems!) so I was hoping to get clarification on the expected behaviour.

The reason this is causing me issues is that I end up sending giving two breakpoints back to VS Code and it seems to assume it's only valid for one breakpoint per location (I guess it'd be confusing if removing a breakpoint appeared to not work because there was another in the same place).

I may be able to handle this by just tracking the breakpoint locations myself and mapping them onto an ID I control, however I want to be sure I understand the expected behaviour before changing things (and adding more things to go wrong) as it's not entirely clear how this should work from the docs.

Here's an example of different IDs for the same location:

```js
==> {
	"id": "87",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "isolates/426090760",
		"scriptUri": "file:///Users/dantup/Desktop/Dart%20Sample/bin/donotformat/test.dart",
		"line": 10
	}
}
==> {
	"id": "88",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "isolates/426090760",
		"scriptUri": "file:///Users/dantup/Desktop/Dart%20Sample/bin/donotformat/test.dart",
		"line": 11,
		"column": 5
	}
}
<== {
	"jsonrpc": "2.0",
	"method": "streamNotify",
	"params": {
		"streamId": "Debug",
		"event": {
			"type": "Event",
			"kind": "BreakpointAdded",
			"isolate": {
				"type": "@Isolate",
				"fixedId": true,
				"id": "isolates\/426090760",
				"name": "test.dart:main()",
				"number": "426090760"
			},
			"timestamp": 1544451126435,
			"breakpoint": {
				"type": "Breakpoint",
				"fixedId": true,
				"id": "breakpoints\/31",
				"breakpointNumber": 31,
				"resolved": true,
				"location": {
					"type": "SourceLocation",
					"script": {
						"type": "@Script",
						"fixedId": true,
						"id": "libraries\/@18247938\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2FDart%2520Sample%2Fbin%2Fdonotformat%2Ftest.dart\/16798757b3b",
						"uri": "file:\/\/\/Users\/dantup\/Desktop\/Dart%20Sample\/bin\/donotformat\/test.dart",
						"_kind": "kernel"
					},
					"tokenPos": 170
				}
			}
		}
	}
}
<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "Breakpoint",
		"fixedId": true,
		"id": "breakpoints\/31",
		"breakpointNumber": 31,
		"resolved": true,
		"location": {
			"type": "SourceLocation",
			"script": {
				"type": "@Script",
				"fixedId": true,
				"id": "libraries\/@18247938\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2FDart%2520Sample%2Fbin%2Fdonotformat%2Ftest.dart\/16798757b3b",
				"uri": "file:\/\/\/Users\/dantup\/Desktop\/Dart%20Sample\/bin\/donotformat\/test.dart",
				"_kind": "kernel"
			},
			"tokenPos": 170
		}
	},
	"id": "87"
}
<== {
	"jsonrpc": "2.0",
	"method": "streamNotify",
	"params": {
		"streamId": "Debug",
		"event": {
			"type": "Event",
			"kind": "BreakpointAdded",
			"isolate": {
				"type": "@Isolate",
				"fixedId": true,
				"id": "isolates\/426090760",
				"name": "test.dart:main()",
				"number": "426090760"
			},
			"timestamp": 1544451126435,
			"breakpoint": {
				"type": "Breakpoint",
				"fixedId": true,
				"id": "breakpoints\/32",
				"breakpointNumber": 32,
				"resolved": true,
				"location": {
					"type": "SourceLocation",
					"script": {
						"type": "@Script",
						"fixedId": true,
						"id": "libraries\/@18247938\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2FDart%2520Sample%2Fbin%2Fdonotformat%2Ftest.dart\/16798757b3b",
						"uri": "file:\/\/\/Users\/dantup\/Desktop\/Dart%20Sample\/bin\/donotformat\/test.dart",
						"_kind": "kernel"
					},
					"tokenPos": 170
				}
			}
		}
	}
}
<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "Breakpoint",
		"fixedId": true,
		"id": "breakpoints\/32",
		"breakpointNumber": 32,
		"resolved": true,
		"location": {
			"type": "SourceLocation",
			"script": {
				"type": "@Script",
				"fixedId": true,
				"id": "libraries\/@18247938\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2FDart%2520Sample%2Fbin%2Fdonotformat%2Ftest.dart\/16798757b3b",
				"uri": "file:\/\/\/Users\/dantup\/Desktop\/Dart%20Sample\/bin\/donotformat\/test.dart",
				"_kind": "kernel"
			},
			"tokenPos": 170
		}
	},
	"id": "88"
}
```

(cc @a-siva - do you know who is best to answer this?)

**Comment by a-siva** [comment]
I looked at the breakpoint addition code in the VM and it does check first if a breakpoint already exists at a location, if one exists it returns it.
```
        BreakpointLocation* bpt =
            GetBreakpointLocation(script, breakpoint_pos, requested_column);
        if (bpt != NULL) {
          // A source breakpoint for this location already exists.
          return bpt;
        }
```
We also have code that given a line and column number tries to find the best fit token position for a breakpoint. In your case the line number/column number are different for the two requests but if the best fit resolved it to the same token position I would have expected to see the same breakpoint ID returned.
Maybe in your case the two positions did not resolve to the same token position when a best fit resolution was done.

**Comment by DanTup** [comment]
> Maybe in your case the two positions did not resolve to the same token position when a best fit resolution was done.

In both of the responses above, the tokenPos is the same (170). I wondered whether it was because they were both sent at (approximately) the same time; maybe there's a race?

**Comment by a-siva** [comment]
Do you have reproduction instructions for somebody in the VM team to take a look

**Comment by DanTup** [comment]
I don't seem to be able to repro this exactly anymore. I can get some similar weird issues for code like this:

```
if (true) {
  print('test');
}
```

If I put breakpoints on the first two lines, they get their own IDs before they resolve (presumably because from the AST they look like different locations) but then when they resolve, they get same tokenPos - I presume the `if (true)` was optimised out or something?

If that sounds normal, I think we can close this for now and I'll come back with a solid repro if I see the original issue (which was giving different IDs for the same tokenPos even when the breakpoints were resolvable immediately).

**Comment by ZichangG** [comment]
It looks like column number should be matched besides script and token_pos. That's why 2 breakpoints are saved separately inside debugger. Column breakpoint has column number 5 and the regular line breakpoint has -1.

`if ((bpt->script_ == script.raw()) && (bpt->token_pos_ == token_pos) &&`
`        (bpt->requested_column_number_ == requested_column)) {`
`      return bpt;`
`    }`

**Comment by DanTup** [comment]
If a user sets two breakpoints on different columns, but that are essentially the  same, for ex:

```dart
someFunction();
   ^     ^    // breakpoints here
```

will they be treated as two separate breakpoints (but only one of them will ever be hit)?

**Comment by ZichangG** [comment]
Yes. Inside debugger, there will be 2 BreakpointLocations having different column numbers. But since they shared the same token position(if they were resolved into the same position), it will create only 1 instance of Codebreakpoint and hit only once.

`CodeBreakpoint* code_bpt = GetCodeBreakpoint(lowest_pc);`
`  if (code_bpt == NULL) {`
`    // No code breakpoint for this code exists; create one.`
`    code_bpt =`
`        new CodeBreakpoint(code, loc->token_pos_, lowest_pc, lowest_kind);`
`    RegisterCodeBreakpoint(code_bpt);`
`  }`

**Comment by ZichangG** [comment]
With this CL, setting breakpoints on compiled function, if a resolved breakpoint already exists with same token position, there won't be breakpoint created with new id. Everything else remain the same.
From my point of view, breakpoints on uncompiled functions should remain separate since we have no idea whether they can be resolved into the same token position. But for compiled function, duplicates can be avoided. Any comments or suggestion?

**Comment by DanTup** [comment]
That sounds reasonable, though the reason I think this originally came up is that the IDE will squash breakpoints at the same location (eg. the second breakpoint "overwrites" the first). This then means when the user removes the breakpoint, we might remove only one, and they have to click remove (in the same place) again.

I think probably I need to handle some of this better in debug adapter (rather than just trying to proxy breakpoints between VS Code + VM unchanged). We already need to consider supporting multiple connected debuggers (this is now more likely with things like Dart DevTools) so I don't think the current way (which assumes VS Code was the originator of all breakpoints) will hold up anyway.

**Comment by ZichangG** [comment]
Agree with your point. Debug adapter would be a better way to provide an uniform solution. Please let me know if you need any help from our side. :)

**Comment by a-siva** [comment]
Can this issue be closed?

**Comment by DanTup** [comment]
Yeah, I think I this needs to be handled in the debug adapter, and it might make sense to roll this up with changes being discussed to better support multiple debuggers attached to the VM.
