### ISSUE TITLE
bug in deferred loading of full emitter + csp + intercepted type

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35361]
This example reveals a bug that only occurs in the full emitter under CSP:

**repro.dart**
```dart
import  "b.dart" deferred as d;
void main() => d.loadLibrary().then((_) { new d.MyClass();});
```

**b.dart**
```dart
import 'package:js/js.dart';

@JS()
class MyClass {}
```

We noticed this on some tests in the CSP  bots when we landed a change to improve the deferred loading algorithm (2a39f63c2a). The failing language tests also hit on other areas affected by the CL, but the example above shows the failure even before our changes to the deferred loading algorithm.

The issue appears to be that the full emitter correctly splits the precompiled classes in the deferred unit, but it incorrectly keeps the class metadata in the main unit. I was only able to reproduce this with subclasses of intercepted types, it is unclear whether this would fail in other cases.

Because we are in the process of deprecating the full emitter, we don't intent to fix it at this time.

**Comment by srawlins** [comment]
Hi @sigmundch , you tagged this as closed-not-planned, but left it open; close this issue?

**Comment by sigmundch** [comment]
thanks - yes the full emitter is now gone,s o I think we can safely close this.
