### ISSUE TITLE
Performance regression Dart 1 to Dart 2?

### ISSUE THREAD

**Issue by Indribell** [dart-lang/sdk#35365]
Hello,

A benchmark from a 3th party author ( https://github.com/costajob/app-servers ) showed when switching over from Dart 1 to Dart 2, that the author lost a massive amount of performance.

Making Dart performance go from bad to even worse. With a massive memory spike, what seems to be a JIT issue ( please include AOT by default into the SDK ).

The author ran Dart on:

Dart version 2.0.0 installed via homebrew.
macOS High Sierra
2.2 GHz Intel Core i7 (4 cores)
16 GB 1600 MHz DDR3

```
| Language                  | App Server                                        | Req./sec (local)  | RAM (MB)  | CPU (%)  |
| :------------------------ | :------------------------------------------------ | ----------------: |---------: |--------: 
2> | [Dart](#dart)          | [Dart HttpServer](#dart-httpserver)               |         36833.66  |    422.1  |   527.1  |
1> | [Dart](#dart)          | [Dart HttpServer](#dart-httpserver)               |         54573.24  |    158.1  |   573.1  |
```

https://github.com/costajob/app-servers/commit/becadd1270632f71cccadd7b0cd1a4acdd3933ec

It might be interesting to give the code ( https://github.com/costajob/app-servers/blob/master/servers/dart_server.dart ) a try, as to see why it showed such a large regression.

**Comment by zsxawerdu** [comment]
Side note, commenting out the req.response.write jumps the performance up a lot, like 2x.

It could be just noise though, I tried detaching the socket both writing the headers and not writing the headers, it didn't effect performance.  Thus, it may be the response.write which is IOSink.  I find this weird that performance is cut to 50% just writing "Hello".

**Comment by zsxawerdu** [comment]
Created a gist to demostrate the issue.   Just comment out the single line in the source.  The HTTP is being written other than the "hello" 5 character difference in the response, yet a 40-50% reduction in performance.

https://gist.github.com/zsxawerdu/d34bd5d68dea708f61799a0967d42dcd

**Comment by zsxawerdu** [comment]
I did benchmarks on 2.8.0-dev and this problem went away.  @dgrove, you may want to close the ticket.
