### ISSUE TITLE
Creating a new map from a const nested map results in a partially unmodifiable map

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/sdk#35366]
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

```
void main() {
  const Map<String, dynamic> constNestedMap = {
    "root": {
      "child": "Bert",
    }
  };
  
  Map<String, dynamic> modNestedMap = Map.from(constNestedMap);
  modNestedMap["root"]["child"] = "Ernie";
}
```

The last line throws `Unsupported operation: Cannot modify unmodifiable Map`. This is true for both VM and dart2js. See it in [Dartpad](https://dartpad.dartlang.org/beea855f54d081d92864a6b30818a4c6).

On the other hand, root elements can be modified, so this will execute properly: 
`modNestedMap["root"] = {"child": "Ernie"};`

**Comment by mraleph** [comment]
This is working as intended. `Map.from` is not a deep copy, it's a shallow copy.
