### ISSUE TITLE
Constant propagator replaces unboxed operations with boxed constants.

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#35371]
AOT-DebugX64 - KBC-CMP-DebugX64: !DIVERGENCE! 1.2:1418832748 (output=false)

fail1:
../../runtime/vm/compiler/backend/il.h: 7344: error: expected: (from == kUnboxedInt64) || (from == kUnboxedUint32) || (from == kUnboxedInt32)
thread=11605, isolate=isolate(0x55a7cec0a900)

**Comment by aartbik** [comment]
Without the assert we get this strange unboxed int converter with a tagged from type:

    v2510 <- UnboxedIntConverter(tagged->int64, v6)

**Comment by aartbik** [comment]
The following rewriting in UnboxIntegerInstr::Canonicalize() would introduce the offending conversion above. This rule clearly expects to find a truly unboxed int as input of the Box operand, not a tagged smi.

```
   v6 <- Constant(#1) [1, 1] T{_Smi}
....
   v2382 <- BoxInt64:1402(v6) [-9223372036854775808, 9223372036854775807] T{_Smi}
....
B378[target]:824
   ....
   v2384 <- UnboxInt64(v2382) [-9223372036854775808, 9223372036854775807] T{int}

```

**Comment by aartbik** [comment]
For now, I fixed this by avoiding the rewrite into UnboxedIntConverter() for a tagged operand. However, arguably we should fix the input to this rewriting rule and make sure v6 is an UnboxedConstant, not a smi constant. Since we allow type imprecise IR which is fixed later by selecting the right representations at certain points, it is unclear if this IR was by design or an actual bug.

**Comment by aartbik** [comment]
Over to Slava to determine we are not sweeping any dirt under the carpet with this fix.

**Comment by mraleph** [comment]
I did not have a chance to look at this yet. Lets keep it open.

**Comment by aartbik** [comment]
Friendly ping @mraleph  (I don't think this is an issue anymore after your related fixed, but just make sure).

**Comment by mraleph** [comment]
Looked at this today - the reason for the bug is that constant propagator is replacing unboxed operations (e.g. `BinaryInt64Op(1, 2)` with boxed constants). It should instead follow what canonicalizer does - it creates `Unbox` of a constant when replacing unboxed operation with a constant value.
