### ISSUE TITLE
no code completion values after entering in a keyword

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35384]
When trying to complete a symbol that starts with a keyword, I get completion until I type the keyword, I get no completion once I've entered enough text to match the keyword, and I resume getting completions once I've entered more text than the keyword.

So, when trying to complete `isFooBar`, I see completion suggestions on `i`; I lose them when I type `is`, and I start seeing them again on `isF`.

**Comment by bwilkerson** [comment]
A simple reproduction case:
```
void f() {
  i
}
bool get isFoo => true;
```

**Comment by scheglov** [comment]
Oh, I hit this quite often - all flag variables like `isEnabled`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356305
