### ISSUE TITLE
Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't.

### ISSUE THREAD

**Issue by theshivamlko** [dart-lang/sdk#35398]
Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'RangeError (index): Index out of range: no indices are valid: 0'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

* Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"

*  Windows 10

**Comment by ignoracenfly** [comment]
always this problem. every time you modify some file  in imac, just execute "build run --release" or 
"build apk" and then immediately  there will be an exception "FormatException: Bad UTF-8 encoding 0xe4".
