### ISSUE TITLE
Add a way to track all the libraries and part files used by the current isolate/vm

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#35396]
`currentMirrorSystem().libraries.keys` can give use the URI for every library, which is generally a `package:` URI.

We have a use case for checking whether any Dart code has changed from a previous state, and today we're able to track a content hash based on these URIs. This doesn't work in the case of `part` files, because it only includes the main file for each library.

I attempted to iterate over all declarations in from each library and check `declaration.location.sourceUri`, but we seem to get relative paths for some part files instead of a `package:` URI.

Can we either normalize the `sourceUri` to a `package:` URI (assuming the library it's a part of was already normalized to a `package:` URI which is typically the case), or add some other way of tracking down all the part files in use?

**Comment by lrhn** [comment]
I'd say that the ` sourceUri` *should not* be relative. It obviously depends on what it represents: The part *file* or the `part` declaration source. Run-time mirrors are not source mirrors, so I'd expect the former, and so it should be the actual URI.

Until that changes (if it does), I guess it is safe to assume that it is relative to the library URI and resolve it as `libraryUri.resolveUri(sourceUri)`.
