### ISSUE TITLE
Analysis server generates quickfixes that modify the Flutter SDK

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35402]
Found by @bradmuzza at https://github.com/Dart-Code/Dart-Code/issues/1341. If you call some Flutter framework code incorrectly, you may get quick-fixes that make modifications to the Flutter SDK source files:

<img width="652" alt="screen shot 2018-12-13 at 1 07 36 pm" src="https://user-images.githubusercontent.com/1078012/49940775-6e329580-fed8-11e8-9232-c917b6ec7c82.png">

If you click `Add required parameter`, it'll insert this as a new param in the definition of `IconButton`.

Note: In VS Code, this results in the file being opened, made dirty, and a "You're modifying a file outside your workspace" message, however it's still pretty easy for a user to just hit `Save All` or something and end up with a broken SDK.

This is similar to https://github.com/dart-lang/sdk/issues/33181 where it was deemed that generated edits outside of the analysis roots probably didn't make sense, so I think the same logic could work here (rather than being specific to the Flutter SDK).

cc @bwilkerson @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/87382
