### ISSUE TITLE
Invalid example in num.toStringAsFixed() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35400]
Please see https://api.dartlang.org/stable/2.1.0/dart-core/num/toStringAsFixed.html
There is an example
```dart
...
123456789012345678901.toStringAsFixed(3);  // 123456789012345683968.000
1000000000000000000000.toStringAsFixed(3); // 1e+21
...
```
Integers in Dart 2.1 are 64-bits, so these examples are invalid. The int literals above are too big for 64-bits integers

**Comment by Kaushl2208** [comment]
Hey @kevmoo , I would like to work on it!! Can I get the whereabouts of the documentation file?

**Comment by kevmoo** [comment]
@Kaushl2208 - 
https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/num.dart

**Comment by Kaushl2208** [comment]
Hey @kevmoo, I have updated the example into the correct range now but the "git cl" is giving me a hard time. I have setup depot_tools and configured the path but after giving the cl command the system gets stuck. Any ideas?

Here is the screenshot for your reference 
![Screenshot from 2020-02-23 16-51-33](https://user-images.githubusercontent.com/41343571/75111222-8023d280-565d-11ea-8182-2a03fa1b2699.png)

**Comment by kevmoo** [comment]
Is this opening your default editor? Do you have your editor configured to
be `vi` or similar? That's likely it!

**Comment by Kaushl2208** [comment]
Nope, it's not opening any editor. Neither the configured one.

**Comment by kevmoo** [comment]
Where are you seeing to use `git cl config`?

**Comment by Kaushl2208** [comment]
After bit of hustle, Figured it out finally! 🤘

**Comment by Kaushl2208** [comment]
> Where are you seeing to use `git cl config`?

https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up

I was not setting up the path correctly and the command takes a little while to execute.

**Comment by Kaushl2208** [comment]
Hey, While uploading the commit for review It showed a warning
`** Presubmit Warnings **
Changes were made to sdk/ that were not made to sdk_nnbd/
Please update these files as well:

sdk_nnbd/lib/core/num.dart
`
Should I change this file too?

**Comment by kevmoo** [comment]
Yes please!

**Comment by Kaushl2208** [comment]
Hey @kevmoo, Can you please tell me what is `github-review.com` . I am getting this log after doing `git cl upload -s`

`Credentials for the following hosts are required:
 github-review.com. These are read from /home/kaushl2208/.gitcookies (or legacy /home/kaushl2208/.netrc)                                                                                                                                                     You can (re)generate your credentials by visiting https://github-review.com/new-password`

After updating the .netrc with same credentials as of my GitHub. It works until updating the description in vim. It again throws this error :

`ServerNotFoundError: Unable to find the server at github-review.com`
