### ISSUE TITLE
Error reading dependency file E:\Final\Flutter\mutawasillinv1\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1 Compiler message: Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null. Receiver: null Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

### ISSUE THREAD

**Issue by HaroonAbbas** [dart-lang/sdk#35413]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by HaroonAbbas** [comment]
v0.11.13, on Microsoft Windows [Version 10.0.15063], locale ar-YE)
    • Flutter version 0.11.13 at C:\flutter
    • Framework revision 58c8489fcd (2 weeks ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)


I use Chrome

**Comment by a-siva** [comment]
Can you also add some instructions on how the problem can be reproduced.

**Comment by a-siva** [comment]
This appears to be another instance of #36032

**Comment by jensjoha** [comment]
Well, the "Error reading dependency file E:\Final\Flutter\mutawasillinv1\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException" does not sound like the same thing...

**Comment by a-siva** [comment]
No reproduction instruction for the "java.lang.ArrayIndexOutOfBoundsException" error. Closing issue as obsolete.
