### ISSUE TITLE
How to save a file?

### ISSUE THREAD

**Issue by StekolschikovV** [dart-lang/sdk#35424]
I need to save the file that is on my hard drive.

File address: /home/mk/proj1/1.txt

Program address: /home/mk/proj2/

I try to save:

```
new dom.AnchorElement(href: '/home/mk/proj1/1.txt')
 ..setAttribute("download", '1.txt')
 ..click();
```

Displays information about saving, but writes: Failed! No file.

How to save a file?

**Comment by parlough** [comment]
This was asked a long time ago, but for reference the [download attribute docs on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download) cover this well. The docs however do indicate the behavior differs by browser and user settings.

I was able to get this to work. The targeted file has to be served from the [same origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) to be accessible. Both automatically clicking with `.click()` and having the user do it seemed to work. I'm assuming only documents in your `proj2` directory were being served so the items in `proj1`, such as `1.txt` weren't accessible.
