### ISSUE TITLE
analyzer: int2double doesn't work in const contexts

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#35441]
This was thought to be #33441, but it turns out its its own issue:

```
const double x = 1; // inferred as 1.0
class C {
  const C() : assert(x is double); // false
}
```

The cause for this is actually very simple. The visitor that evaluates an AST node for const evaluation, does not look at the node's `staticType` at all, and simply creates an integer. This made sense when integer expressions were always integers.

It's not a bigger issue, like inference not having been run, as we thought behind #33441. It's really easy.

We have `@failingTest`s for this in analyzer already.

**Comment by MichaelRFairhurst** [comment]
I just ran into something really weird

This now passes:

```
const C(double x) : assert(x is double);
```

where it didn't before.

But this still fails:

```
const double x = 0;
const C() : assert(x is double);
```

**Comment by bwilkerson** [comment]
The information needed by the first example is completely local. The information for the second isn't, and hence depends (IIRC) on having built a dependency graph so that `x` is evaluated before the initializer. I wonder whether the graph might not be getting built correctly for asserts in initializer lists.

**Comment by lrhn** [comment]
In either case `is` checks are not allowed in const contexts (yet).

**Comment by MichaelRFairhurst** [comment]
@lrhn there are other ways to reproduce the problem:

```
const double x = 0;
const C() : assert("$x" == "0.0");
```

However, these are just symptoms of the real problem, which is that x was given the wrong type.

Not only does it make it easier and more reliable to test this by turning on the const updates, it also makes it more important to have fixed before the new const behavior is released. So its all related.

**Comment by stereotype441** [comment]
@MichaelRFairhurst can we mark this as fixed now?

**Comment by MichaelRFairhurst** [comment]
Yes, thanks for the reminder!
