### ISSUE TITLE
confused function's return type: can also be 'void' or 'Future' in a async function

### ISSUE THREAD

**Issue by Buerkut** [dart-lang/sdk#35447]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version :Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"
* OS: MacOSX

In  a async function, its return type is Future, and there is no error when compiling and running. example:
--------
import 'dart:async';
import 'dart:convert';

Future main() async {
  var lineStream = Stream.fromIterable(['fo', 'o\nb', 'ar']);
  var lines = await lineStream.transform(LineSplitter()).toList();
  print(lines);
}
--------

but if replace 'Future' with 'void', it's also ok!

--------
import 'dart:async';
import 'dart:convert';

void main() async {
  var lineStream = Stream.fromIterable(['fo', 'o\nb', 'ar']);
  var lines = await lineStream.transform(LineSplitter()).toList();
  print(lines);
}
--------

I'm confused.Is it intentional to design as that?

**Comment by eernstg** [comment]
A async function with return type `void` is a "fire and forget" function. That is, you should use this to communicate to the caller that it is a bad idea to wait for the completion of this asynchronous task (say, because it's logging via a socket and it won't help you to wait until that's done).
