### ISSUE TITLE
Omit code completions for methods that are marked @protected

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#35449]
The meta package contains an [`@protected` annotation](https://github.com/dart-lang/sdk/blob/master/pkg/meta/lib/meta.dart#L158) for members that should only be invoked from within a class itself. https://github.com/dart-lang/sdk/issues/25841 added analyzer support to warn on all calls to @protected methods from elsewhere. The present bug request going one step further: omit all @protected methods from the code completion dialog. This seems like the desired UX given using such a code completion would result in an immediate warning, and this doesn't seem useful.

**Comment by leisim** [comment]
I feel like this should be a higher priority. Currently it is impossible to expose internal non-private methods to generated code but hide them from the user's auto complete 😔

**Comment by srawlins** [comment]
Agree

**Comment by scheglov** [comment]
For @protected https://dart-review.googlesource.com/c/sdk/+/358120

**Comment by scheglov** [comment]
For @visibleForTesting https://dart-review.googlesource.com/c/sdk/+/358328

**Comment by westito** [comment]
It is also applicable to `@visibleForOverriding`. But this is special a little bit, placing between `@protected` and `@visibleForTesting`. Code complete should list this method right inside the sub-class body, but not inside an inner function.
