### ISSUE TITLE
tan() does not return infinity pi/2 and -pi/2

### ISSUE THREAD

**Issue by NebulaFox** [dart-lang/sdk#35457]
```
tan(pi * 0.5) = tan(-pi * 0.5) = 16331239353195370
```

DartPad example
https://dartpad.dartlang.org/1e331c1d672f4525db95c888b7a516f3

Dart SDK Version: 2.1.0

**Comment by rakudrama** [comment]
`pi` is not exactly π, but the closest IEEE 754 double to the value of π.
The double type is really just a subset of the rational numbers with a few oddities like NaN, -0.0 and infinities, so cannot precisely represent an irrational numbers like π and √2.

There are two adjacent double numbers on either side of π/2. One of those is the best approximation possible with the IEEE 754 double format.
For more information on the approximation and its consequences, you can read [What every computer scientist should know about floating-point arithmetic](https://dl.acm.org/citation.cfm?id=103163).

I fixed up your example and added the closest 5 doubles to π/2:
https://dartpad.dartlang.org/9f3ea9bd193e2e489a4b607c9dc5b642
You can see that while 16331239353195370 is not ∞, it is the closest result to ∞.
The previous result is smaller and the next result is negative.
This demonstrates that the Dart math library `pi` and `tan` are doing as good a job as is possible for IEEE 754 double precision floating point numbers.

**Comment by NebulaFox** [comment]
@rakudrama Thanks for taking the time to explain the situation.

I was just under the impression that libraries just handled the case π/2 and return infinity or an exception.
