### ISSUE TITLE
The immutable annotation is not allowed on mixins.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35459]
I think it should be... right?

```dart
import 'package:meta/meta.dart';

@immutable
mixin Mix {
  int a;
}
```

The analyzer prints a warning for this code: "Only classes can be annotated as being immutable"

**Comment by srawlins** [comment]
@bwilkerson can you confirm this is a bug? I can land a fix if so.

**Comment by bwilkerson** [comment]
I believe that it's consistent with the intended semantics of `@immutable` that it could be applied to mixins.
