### ISSUE TITLE
AssetImage  Image extending outside BoxDecoration container 

### ISSUE THREAD

**Issue by bradmuzza** [dart-lang/sdk#35461]
I have Image inside a BoxDecoration that works when I get the image from CachedNetworkImageProvider but when I get the image from Assetimage the image is not clipped to the box size. Both image sources are displayed in ListTile. Also worth mention that The Images from assets will render when I move them out side the BoxDecoration. 

 Code from AssetImage:
`return Container(
      width: widget.width, 
      height: widget.heigth,
      decoration: BoxDecoration(
      shape: BoxShape.circle,
      border: Border.all(color:widget.colour, width:3),
      image: DecorationImage(
      fit: BoxFit.cover,
      image: AssetImage(url)
       )....`

Code from CachedNetworkImageProvider:
`return Container(
width: widget.width, 
height: widget.heigth,
decoration: BoxDecoration(
  shape: BoxShape.circle,
  border: Border.all(color:widget.colour, width:3),
  image: DecorationImage(
    fit: BoxFit.cover,
    image: CachedNetworkImageProvider(widget.location.imageURLs[widget.index])..`

![screenshot_1545216515](https://user-images.githubusercontent.com/38493907/50251357-bea97600-0437-11e9-91ac-76f9fe5c5318.png)

**Comment by zoechi** [comment]
This is a Flutter issue that was answered on StackOverflow https://stackoverflow.com/questions/53849631/flutter-imageasset-image-extending-outside-boxdecoration-container

**Comment by kevmoo** [comment]
Not a Dart SDK issue
