### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by latos** [dart-lang/sdk#35465]
Cannot find value Instance of 'TypeVariableLocal' in (Instance of 'ThisLocal', function(#and), function(#or)).
  ExprRuntime() {
  ^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,
Mac OS 10.12.6 

* the Dart SDK build number (build number could not be determined), and
Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64"

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on PolesClient|web/staticapp/main.dart threw error: Assertion failure: Cannot find value Instance of 'TypeVariableLocal' in (Instance of 'ThisLocal', function(#and), function(#or)).
package:compiler_unsupported/src/ssa/locals_handler.dart 330           LocalsHandler.readLocal
package:compiler_unsupported/src/ssa/builder.dart 1880                 SsaBuilder.visitFunctionExpression.<fn>
dart:core                                                              List.forEach
package:compiler_unsupported/src/ssa/builder.dart 1876                 SsaBuilder.visitFunctionExpression
package:compiler_unsupported/src/tree/nodes.dart 1132                  FunctionExpression.accept
package:compiler_unsupported/src/ssa/builder.dart 1587                 SsaBuilder.visit
package:compiler_unsupported/src/ssa/builder.dart 1891                 SsaBuilder.visitFunctionDeclaration
package:compiler_unsupported/src/tree/nodes.dart 1050                  FunctionDeclaration.accept
package:compiler_unsupported/src/ssa/builder.dart 1587                 SsaBuilder.visit
package:compiler_unsupported/src/ssa/builder.dart 1633                 SsaBuilder.visitBlock
package:compiler_unsupported/src/tree/nodes.dart 903                   Block.accept
package:compiler_unsupported/src/ssa/builder.dart 787                  SsaBuilder.buildMethod
package:compiler_unsupported/src/ssa/builder.dart 340                  SsaBuilder.build
package:compiler_unsupported/src/ssa/builder.dart 139                  SsaAstBuilderTask.build.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1098                    CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/ssa/builder.dart 130                  SsaAstBuilderTask.build.<fn>
package:compiler_unsupported/src/common/tasks.dart 63                  CompilerTask.measure
package:compiler_unsupported/src/ssa/builder.dart 124                  SsaAstBuilderTask.build
package:compiler_unsupported/src/ssa/ssa.dart 37                       SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 932           JavaScriptBackend.codegen
package:compiler_unsupported/src/js_backend/element_strategy.dart 125  ElementCodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 737                     Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 737                     Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 735                     Compiler.emptyQueue.<fn>.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1098                    CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 733                     Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/enqueue.dart 507                      EnqueuerStrategy.processWorkItem
package:compiler_unsupported/src/js_backend/enqueuer.dart 227          CodegenEnqueuer.forEach
package:compiler_unsupported/src/compiler.dart 729                     Compiler.emptyQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 728                     Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 752                     Compiler.processQueue.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 747                     Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 621                     Compiler.compileLoadedLibraries.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 518                     Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 473                     Compiler.runInternal
===== asynchronous gap ===========================
package:compiler_unsupported/src/compiler.dart 308                     Compiler.run.<fn>.<fn>
dart:async                                                             new Future.sync
package:compiler_unsupported/src/compiler.dart 308                     Compiler.run.<fn>
package:compiler_unsupported/src/common/tasks.dart 176                 CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 305                     Compiler.run
package:compiler_unsupported/src/apiimpl.dart 263                      CompilerImpl.run.<fn>.<fn>

**Comment by sigmundch** [comment]
We used to have this error long time ago, but I believe this is no longer an issue in the latest version of the compiler (/cc @johnniwinther to confirm).

@latos - I noticed that you are using an old version of the SDK (1.24.3). Let us know if you still see the issue in the latest stable release of Dart (2.1.0).

**Comment by johnniwinther** [comment]
The missing registration of type variables needed only in local functions has been fixed.
