### ISSUE TITLE
Cleanup all sync async conditional code in dart2js and kernel code (this flag is now the default)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35466]
Please remove all the conditional code in dart2js and kernel pkgs around sync async.
This is the default now and there is no runtime option to turn this off.

**Comment by kmillikin** [comment]
I've removed it from Kernel in this CL: https://dart-review.googlesource.com/c/sdk/+/87960 so this is really just a dart2js issue now.
