### ISSUE TITLE
Why it (<E extends V>) comes with runtime error but works with analyzer

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#35470]
Dart version: 2.1.0

Why the following example fails in runtime with `Error: Inferred type argument....`
For example,

```
void main() {
  Bar().sayHi();
}

class Foo<V> {
  log<E extends V>(E e) => print('v: $e');
}

class Bar extends Foo {
  sayHi() {
    log(3); // runtime error
  }
}
```

It seems no way to avoid this runtime error, unless we remove this `<E extends V>`

**Comment by eernstg** [comment]
This is a bug which was apparently introduced into the common front end (of `dart` and `dart2js`) as of version 2.1.0-dev.8.0.

**Comment by stefantsov** [comment]
Thanks for reporting the bug!  I'm working on a fix in [CL 87965](https://dart-review.googlesource.com/c/sdk/+/87965).

**Comment by jumperchen** [comment]
@eernstg, Thanks for the suggestion, we will refactor our code to avoid this situation.
@stefantsov, Thanks for your attention and high efficiency on fixing this issue!
