### ISSUE TITLE
DateTime.now.toUtc seems inconsistent and possibly broken.  

### ISSUE THREAD

**Issue by tensor-programming** [dart-lang/sdk#35489]
* Dart 2.1.0 windows x64

I am building a flutter application that uses the current time in conjuncture with a timestamp from an external API.  The idea is that the API gives me a past timestamp and then I want to be able to find the duration between the two.  In the past, (a few months ago; prior to the dart 2 release) I could use `DateTime.now().toUtc()` and this would give me a current timestamp in UTC time.  Right now, it seems that this same call gives me the current local time with a UTC format.   I.E: `2018-12-23 06:02:15.000Z` vs `2018-12-23 06:02:15.000`

I am able to achieve what I want using `DateTime.now().subtract(DateTime.now().timeZoneOffset)` but this is fairly verbose and it seems pretty round-about/contradictory compared to other language implementations.  Java's Instant class gives you the time in UTC by default as does Python's `datetime.utcnow` function.  

Is this an intended feature or is this some kind of bug that was introduced during the dart 2 release?

**Comment by natebosch** [comment]
I can't repro - is this with the Dart VM? What does `DateTime.now().timeZoneName` return for you?
