### ISSUE TITLE
weird reply from rxdart

### ISSUE THREAD

**Issue by usrdjan** [dart-lang/sdk#35482]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by usrdjan** [comment]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null.
Receiver: null
Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
lib/main.dart:4:8: Error: Error when reading 'file:///home/su/flutter/.pub-cache/hosted/pub.dartlang.org/rxdart-0.20.0/lib/rxdart.dart/': Not a directory
import 'package:rxdart/rxdart.dart/';
       ^
Compiler failed on /home/su/AndroidStudioProjects/flt_rxdart/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by zoechi** [comment]
Perhaps you missed running `flutter packages get`
If this doesn't help delete `/home/su/flutter/.pub-cache/hosted/pub.dartlang.org/rxdart-0.20.0/` and try again.

**Comment by usrdjan** [comment]
my bad, it was message regarding the folder, so it's not the
import 'package:rxdart/rxdart.dart/';
but:
import 'package:rxdart/rxdart.dart';
no slash...

Rookie here...

Cheers.
