### ISSUE TITLE
What's the difference between dartdevc and dartdevk?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#35483]
I presume one takes kernel files and one takes sources?

It's not clear from their help messages:

```
%./dartdevc                                                                                               [~/Downloads/dart-sdk/bin]
The Dart Development Compiler compiles Dart sources into a JavaScript module.

Usage: dartdevc [options...] <sources...>

-h, --help                   Display this message. Add -v to show hidden options.
-o, --out                    Output file (required).
    --modules                module pattern to emit

          [amd] (default)    AMD/RequireJS modules
          [common]           CommonJS/Node.js modules
          [es6]              ECMAScript 6 modules

-s, --summary                summary file(s) of imported libraries, optionally
                             with module import path: -s path.sum=js/import/path

    --module-name            The output module name, used in some JS module formats.
                             Defaults to the output file name (without .js).

    --library-root           (deprecated) used to name libraries inside the module.
```

```
./dartdevk                                                                                               [~/Downloads/dart-sdk/bin]
The Dart Development Compiler compiles Dart sources into a JavaScript module.

Usage: dartdevc -k [options...] <sources...>

-h, --help                   Display this message.
-o, --out                    Output file (required).
    --packages               The package spec file to use.
    --[no-]summarize-text    emit API summary in a .js.txt file
                             (defaults to on)

    --multi-root-scheme      The custom scheme to indicate a multi-root uri.
                             (defaults to "org-dartlang-app")

    --multi-root             The directories to search when encountering uris with the specified multi-root scheme.
                             (defaults to "/Users/eseidel/Downloads/dart-sdk/bin/")

    --modules                module pattern to emit

          [amd] (default)    AMD/RequireJS modules
          [common]           CommonJS/Node.js modules
          [es6]              ECMAScript 6 modules

-s, --summary                summary file(s) of imported libraries, optionally
                             with module import path: -s path.sum=js/import/path

    --module-name            The output module name, used in some JS module formats.
                             Defaults to the output file name (without .js).
```

The internet only talks about dartdevc.

Dart VM version: 2.1.1-dev.0.1 (Thu Dec 20 08:43:10 2018 +0100) on "macos_x64"

**Comment by kwalrath** [comment]
I haven't documented dartdevk because I was told it was going to be provided as dartdevc. But I suppose the tools page should mention it, since it is (for whatever reason) provided as a separate file in the SDK.

**Comment by natebosch** [comment]
You're correct that dartdevk is the one that consumes kernel files. We expect that both of these should be opaque to most users, you should be using them through `build_runner` and `build_web_compilers`. We have not yet published the version that uses dartdevk.

Are you trying to use these compilers outside of the build system? If so, can you explain the reasoning?

**Comment by vsmenon** [comment]
They're roughly equivalent.  Under the hood, `dartdevc` is the original analyzer-based version we're deprecating.  `dartdevk` is the kernel/CFE-based version we're planning to replace it with.  We're moving to the latter to unify with other Dart compilation tools, but we need to fix some perf issues first.  

Most users are unlikely to invoke either directly.  These tools are somewhat analogous to gcc without the link step (i.e., the .c to .o part).   Our builders invoke them for you at the right granularity and do the link step to produce a complete app.

@jmesserly - are you planning on unifying to one binary?  If not, perhaps change the help to clarify?  :-)

**Comment by jmesserly** [comment]
dartdevk is deprecated. It can be removed now, since it was never officially released. It was only used by build_runner (and even that was experimental support).

> are you planning on unifying to one binary?

it's already done! :) `dartdevk` is simply an alias for `dartdevc -k`/`dartdevc --kernel`

**Comment by jmesserly** [comment]
Update: I've got a CL ([88281](https://dart-review.googlesource.com/c/sdk/+/88281)) that removes dartdevk, and Nate has a [pull request](https://github.com/dart-lang/build/pull/1945) for build_runner that switches over to `dartdevc --kernel`
