### ISSUE TITLE
Allow testing for type enum

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/sdk#35496]
As far as I know, all enums have the same properties / methods. In other words, they all act the same. I see no reason why we shouldn't be able to test if a value is an enum and then perform enum-y tasks on it.

For example, I have a BehaviorSubject that persists values on add to `shared_preferences` in Flutter. I support numbers, strings, and lists of strings. I'd like to also support enums but I can't because I cannot test if an incoming value is an enum.

**Comment by jacob314** [comment]
This would also enable extension methods on enums.

**Comment by lukepighetti** [comment]
We can already do extension methods on enums. Use them all the time.

**Comment by srawlins** [comment]
@eernstg did I see you write on another issue that this is implemented in Dart 2.14?

**Comment by eernstg** [comment]
Yes, class `Enum` is a supertype of every `enum` type, and it was added in 43cff263654c0511c058d9a19ece1c87a906ea6d, Jun 25 2021. It wasn't associated with a language version, but it is present in dart-pad as of today (SDK 2.14.0).
