### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by maiducanh1989** [dart-lang/sdk#35490]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4886.37`
- `2.1.0-dev.9.4`
- `IU-183.4886.37, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900, 1920x1080`

**Comment by vsmenon** [comment]
This appears to be incomplete - was there a bug or trace?
