### ISSUE TITLE
developer's TimelineSyncFunction and Timeline.timeSync should be generic

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35509]
[TimelineSyncFunction](https://api.dartlang.org/dev/2.1.1-dev.0.1/dart-developer/TimelineSyncFunction.html) should be generic, as:

```dart
typedef TimelineSyncFunction<T> = T Function();
```

This allows [Timeline.timeSync](https://api.dartlang.org/dev/2.1.1-dev.0.1/dart-developer/Timeline/timeSync.html) to be generic as well:

```dart
class Timeline {
  T timeSync<T>(
      String name,
      TimelineSyncFunction<T> function, {
      Map<dynamic, dynamic> arguments,
      Flow flow
  });
}
```

This allows developers to avoid a dynamic return type, improves type safety, and inference. (I am specifically opening this after trying to use --no-implicit-dynamic with this API.)

**Comment by srawlins** [comment]
@rmacnak-google you seem to own this code 😁 would you accept a change as described above if I mailed it?

**Comment by rmacnak-google** [comment]
Yes, I'm okay with that change.
