### ISSUE TITLE
Analyzer: no error assigning to a final local via for in loop

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#35508]
Discovered seemingly on accident by `language_2/void/void_type_usage_test/final_local_for_in2`

```
  final Object x = null;                                                         
  for(x in [1, 2]) {}
```

This doesn't show any errors but of course should. `x` is final so it cannot be set to `1` and `2`.

**Comment by srawlins** [comment]
I think I fixed this at some point.

> error • The final variable 'x' can only be set once. • 35508.dart:3:7 • assignment_to_final_local
