### ISSUE TITLE
Linting fails in the second condition of a ternary

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35517]
_From @ThinkDigitalRepair on December 29, 2018 4:28_

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

Using a ternary and needing to change the Variable type but only getting errors on the first operand.
<img width="853" alt="screen shot 2018-12-28 at 8 23 26 pm" src="https://user-images.githubusercontent.com/23037821/50533463-f622bd00-0ade-11e9-8289-01d2ade20faf.png">
After changing only one operand. This, I'm sure, should throw an error if it's ever false.
<img width="707" alt="screen shot 2018-12-28 at 8 23 42 pm" src="https://user-images.githubusercontent.com/23037821/50533464-f622bd00-0ade-11e9-99ba-2e03634f5193.png">

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/thinkdigital/development/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5124
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 67D4E3CB-0E25-487C-A979-722757E1B383 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.

_Copied from original issue: flutter/flutter-intellij#3002_

**Comment by pq** [comment]
Thanks for the report @ThinkDigitalRepair.

This is definitely not right and I can reproduce it.  Really **_neither_** of your examples should analyze cleanly (since `ImageAsset` is not a widget) but it looks like there's a hiccup in the way types are inferred in the ternary.  I'm going to move this issue over to the SDK for the analyzer folks to look at.

Thanks for the catch!

**Comment by pq** [comment]
/cc @stereotype441 @bwilkerson 

Here's a simplified repro:


```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ClipOval(
              child:
                  _counter == 1 ? Image.asset("foo.png") : AssetImage("bar.png"),
            ),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

It appears that `_counter == 1 ? Image.asset("foo.png") : AssetImage("bar.png")` is being treated as type `Widget` (and it shouldn't).

**Comment by ThinkDigitalRepair** [comment]
Thanks!

**Comment by srawlins** [comment]
The current behavior ('The argument type 'Object' can't be assigned to the parameter type 'Widget?'.') is just fallout from the Least Upper Bound of the two types in the conditional operator.
