### ISSUE TITLE
Analyzer: "Document all public members" on Enum values having an annotation

### ISSUE THREAD

**Issue by cedx** [dart-lang/sdk#35527]
* Dart SDK: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
* OS: Windows 10

I'm using the rule `public_member_api_docs` from the Dart linter.

If I use an annotation on a documented member of a class, everything is OK. But if I do the same thing with a enumerated value, the analyzer triggers an error: `Document all public members`.

```dart
// This class does not trigger the analyser warning.
class Foo {
  /// A comment.
  @JsonKey(defaultValue: '')
  String bar;
}

// This enum triggers the analyzer warning.
enum Baz {
   /// A comment.
  @JsonValue('contact')
  qux
}
```

Removing the annotation on the enumerated value also removes the analyzer warning.

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1396
