### ISSUE TITLE
Why don't provide official sql interface and driver?

### ISSUE THREAD

**Issue by kingkazuma** [dart-lang/sdk#35526]
I wonder why don't provide related official SQL interface and mainstream database connection driver, such as mysql and oracle.This has caused great inconvenience in product.

Is there any special significance?

**Comment by mit-mit** [comment]
We are working on lower-level platform support for calling C/C++ more efficiently and easily (https://github.com/dart-lang/sdk/issues/34452); hopefully that will provide a good starting point for db drivers.

**Comment by kevmoo** [comment]
Closing this out as it's not related to our core SDK work.
