### ISSUE TITLE
Andoid Studio Reported Warning

### ISSUE THREAD

**Issue by jindalAnuj** [dart-lang/sdk#35531]
In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version 2.1.0-dev.9.4`)
* Windows
* Flutter

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'RangeError (index): Index out of range: no indices are valid: 0'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

**Comment by jensjoha** [comment]
Thank you for reporting this issue.
Unfortunately this is an old version of dart, where I didn't include enough debugging information in the message to actually fix the issue.
Rest assured though, that everything should still be fine: It tried a speed-up trick but failed --- it then reverted back to a slower compile.
