### ISSUE TITLE
Add --suggested option for style related fixes

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#35539]
Currently, `dartfix` has two conflated rolls:

* Language upgrade fixes (required):
    * Converting classes used as mixins to use the new mixin syntax
    * Moving named constructor type arguments from the name to the type
* Stylistic code changes (suggested):
    * Converting double literals to int literals where applicable

While the latter is good, the primary roll of `dartfix` is the former, and currently there is no way to apply the required changes without applying the suggested changes. As I see it, there are two ways we can address this:

1) Only apply suggested code changes if a new `--suggested` option is supplied. This is similar to `dartfmt --fix`

2) Apply suggested code changes unless a new `--required-only` option is supplied.

**Comment by mit-mit** [comment]
Maybe generalize this a bit further and differentiate between *required* updates and *suggested* updates?

**Comment by danrubel** [comment]
I like that generalization and have updated the description above. Thank you!
