### ISSUE TITLE
Generate number check when comparing FutureOr

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#35542]
```dart
import 'dart:async';

FutureOr<dynamic> x = 'abc';
dynamic y = 'abc';

void foo() {
  x = 0x7fffffffffffffff;
  y = 0x7fffffffffffffff;
}

void main() {
  foo();

  if (identical(x, y)) {
    print('ok');
  } else {
    print('fail');
  }
}
```

```

pkg/vm/tool/precompiler2 foo.dart foo.snapshot
pkg/vm/tool/dart_precompiled_runtime2 foo.snapshot
fail
```

If the type of `x` is changed to `dynamic`, the test passes.

It looks like the following code should be adjusted to account for FutureOr, which could hold a boxed number:
https://github.com/dart-lang/sdk/blob/0797d6ef695739aafd3759096f4143c7440f0213/runtime/vm/compiler/backend/il.cc#L3061-L3068

/cc @mraleph @crelier

**Comment by crelier** [comment]
I'll take a look. Thanks.
Note that I'd like to commit this [CL](https://dart-review.googlesource.com/c/sdk/+/88221), before fixing this issue.

**Comment by crelier** [comment]
Fixed by above referenced commit.
