### ISSUE TITLE
Completion/Hovers/Signature Information for super() constructor calls don't match direct calls

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35546]
(Moved from https://github.com/Dart-Code/Dart-Code/issues/1369 @marcoms)

Given the following code:

```dart
class A {
  String a;
  A({this.a});
}

class B extends A {
  B() : super(/* 2 */);
}

main() {
  var a = new A(/* 1 */);
}
```

Invoking completion at `/* 1 */` will provide arguments from the constructor:

<img width="597" alt="screenshot 2019-01-03 at 10 44 29 am" src="https://user-images.githubusercontent.com/1078012/50633811-909e5880-0f44-11e9-934a-76b8f7f3d830.png">

However invoking completion at `/* 2 */` in the `super` call does not:

<img width="618" alt="screenshot 2019-01-03 at 10 45 12 am" src="https://user-images.githubusercontent.com/1078012/50633852-aad83680-0f44-11e9-9096-b23405d16517.png">

I think the behaviour for a `super()` call should be the same as if calling the constructor directly.

**Comment by DanTup** [comment]
Looks like this is more than just the completion, the hovers are missing and the signature help too. I can split this into multiple issues if these aren't just the same problem.

**Comment by rithviknishad** [comment]
any updates on this issue? it's been quite a while

**Comment by bwilkerson** [comment]
I'm now seeing the same behavior for both locations, so I assume this was fixed.
