### ISSUE TITLE
completion.getSuggestions should implicitly analysis.setPriorityFiles on the param file

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#35543]
Analysis server is vastly (~5 minutes on my workstation) slower to return completions after startup if analysis.setPriorityFiles was not called on the target file. But I can't really imagine a case where a completion request should not be prioritized. Is there any reason to not implicitly prioritize a file that completion suggestions are being requested for?

**Comment by bwilkerson** [comment]
> Is there any reason to not implicitly prioritize a file that completion suggestions are being requested for?

I don't know whether there would be a negative impact from implicitly prioritizing files for which explicit requests have been made, but it might be worth looking into.

Note that this wouldn't help the majority of server's clients. Most clients already make the files in which completion will be (or could be) requested priority files for other reasons.

I'm guessing that it isn't that difficult for your code to set the priority files appropriately.

**Comment by lambdabaa** [comment]
> Note that this wouldn't help the majority of server's clients. Most clients already make the files in which completion will be (or could be) requested priority files for other reasons.

Makes sense to me! And it wasn't difficult to add the call to `analysis.setPriorityFiles`. It was just surprising that it would make a 5 minute difference in the time it took for analysis server to issue a response to my request. I think it would make analysis server a more intuitive product for integrators if

1. Requests were acked quickly, even if the results notification takes a while to come through. The API design suggests that a `completion.getSuggestions` response should come back immediately and that the analysis server will answer it without doing any work. I thought that I was seeing a bug when my request didn't get a response for so long.

2. The server tried to behave in ways that matched integrators intentions and expectations. I can't imagine a case where a client would ask for suggestions and not want the request's parameter files to be prioritized. I only knew to try `analysis.setPriorityFiles` because I was sitting next to @jwren.

That being said, I agree that this wouldn't make a difference for existing clients and might not be worth prioritizing for that reason.

**Comment by scheglov** [comment]
We now use special `resolveForCompletion()`, so the priority of the file does not matter.
