### ISSUE TITLE
Analyzer: Enforce covariance of type variables in super-interfaces

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35553]
Note that this should be implemented behind an experimental flag.

See the language tracking issue: https://github.com/dart-lang/language/issues/113
And the feature specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/contravariant-superinterface-2018/feature-specification.md
And the implementation plan: https://github.com/dart-lang/language/blob/master/accepted/future-releases/contravariant-superinterface-2018/implementation-plan.md

**Comment by stereotype441** [comment]
Sadly, this isn't likely to make the cut for Dart 2.3.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/103960
