### ISSUE TITLE
Change Deprecated semantics to allow same-package deprecated member use

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35556]
In https://github.com/dart-lang/sdk/issues/30084 it has been proposed that more noise than signal is added when the analyzer reports on `@deprecated` member use within the same package as the `@deprecated` member declaration.

As of late December, the analyzer has some notions of two elements being declared in the "same-package" or not, for Pub packages, package:build-based Pub packages, and packages found inside GN and Bazel workspaces. We can publish this notion of "package" and "workspace," and then update the semantics of Deprecated to include something like:

> If the deprecated use is found in the same package as the deprecated member's declaration, then the tool need not bother the user about it.

(or, "then the tool may optionally report it.")

As @bwilkerson points out at https://github.com/dart-lang/sdk/issues/30084#issuecomment-392070260, the semantics of Deprecated were determined by the language team, and so the analyzer team should not decide whether this change is appropriate.

**Comment by lrhn** [comment]
The doc already says: "A tool that processes Dart source code *may* report when:" (my emphasis).
The analyzer is free to not report anything. It should not report *more* than what the documentation says (unless the documentation forgot a case, then we should fix the documentation as well), and it shouldn't warn where the documentation says not to (use of something deprecated inside something that is itself deprecated).

If you decide to not report deprecation of declarations from the same "package"/compilation-unit, then we can, and probably should, update the documentation, but doing so is not a blocker for omitting warnings. I'd prefer to see the final design before changing the documentation.

**Comment by srawlins** [comment]
Woohoo! WDYT, @bwilkerson, good enough to move forward on #30084, perhaps split DEPRECATED_MEMBER_USE into two Hints? Or perhaps one Hint and one Lint, TBD? I'm happy to update the documentation as well; can do in the same change, I suppose.

**Comment by bwilkerson** [comment]
Hints are enabled by default, and if the majority opinion is that we should not warn about using deprecated elements in the same package then we shouldn't make same-package checks a hint.

**Comment by srawlins** [comment]
That sounds fair. Perhaps:

* DEPRECATED_MEMBER_USE stays an analyzer Hint, but does not report on same-package use,
* We introduce a new linter Lint, like DEPRECATED_MEMBER_USE_SAME_PACKAGE, which only reports on same-package deprecated member use.

**Comment by bwilkerson** [comment]
Yes, I think that's what we'd need to do.

**Comment by srawlins** [comment]
Introduced forever ago.
