### ISSUE TITLE
Auto complete don't work for Mixins

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#35552]
Hey everyone! I don't know if this issue should be posted here, if not please give me some light.

The problem is the auto completion code for mixins: it does not work when calling super class methods. Check this image:

![image](https://user-images.githubusercontent.com/1146982/50654892-8183ce80-0f75-11e9-809b-602134e787f0.png)

Also, when I am inside the mixin code and try to override methods, it gives me no options.
The IDE I am using is Intellij Community with the latest version of the plugin (**v183.4886.3**)

Best regards.

**Comment by vitaliy-bobrov** [comment]
Same issue using VS Code

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/97020 should fix the completion case.
