### ISSUE TITLE
Specification: Make it an error to 'have' a method and setter with the same basename

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35561]
We currently specify in section 'Class Member Conflicts' of the language specification that it is an error to declare a getter/setter and have a method with the same name, and vice versa, but this does not cover the case where two superinterfaces declare such a pair (so we don't have "a has and a declares" we just have "two has"):

```dart
abstract class A { set foo(v); }
abstract class B { void foo(); }
abstract class C implements A, B {} // No error.
```

It is not possible for any concrete class `D` to implement `C`, because it (or some superclass) would need to implement both the setter and the method, so there would be some class in the superclass chain from `D` which 'has' the setter and 'declares' the method or 'declares' the setter and 'has' the method, so we wouldn't ever have this clash in a concrete class (and hence we wouldn't have it at run time) already with the current spec, but it is better to catch this situation early such that developers don't paint anybody else into that corner.

So we should extend the specification to make this kind of clash an error already when we only have 'has' and 'has' (which will of course include all errors according to the current spec because 'declares' is a special case of 'has').

This is a non-breaking spec change, because the analyzer already rejects this kind of clash.

**Comment by eernstg** [comment]
@lrhn, @leafpetersen, do you agree that we want this update?

**Comment by lrhn** [comment]
I do!

**Comment by leafpetersen** [comment]
SGTM, thanks.

**Comment by eernstg** [comment]
Done in [this CL](https://dart-review.googlesource.com/88455).

**Comment by eernstg** [comment]
Closing: Said CL was committed in cba23af8ceb39b30d02d381d5a59199fd63e6c38.
