### ISSUE TITLE
Analyzer: control flow collections phase 2

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35567]
Phase 2 covers tool support.  For the analyzer this means high quality error messages, parser recovery, and quick fixes.

Note that this should be behind an experimental flag.

See the language tracking issue: https://github.com/dart-lang/language/issues/165
And the feature specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md
And the implementation plan: https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/implementation-plan.md

Subtasks include:
- [x] IDE quick fixes using spread and if #35867

**Comment by bwilkerson** [comment]
I don't know whether there is more work here that we wanted to get done or whether we should close this.

**Comment by stereotype441** [comment]
I'm happy to consider it done at this point.
