### ISSUE TITLE
dartanalyzer unnecessary_parenthesis disagrees with Dart with a lambda in constructor

### ISSUE THREAD

**Issue by dotdoom** [dart-lang/sdk#35577]
* Dart SDK Version: `Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"`

In the following example, parenthesis seem to be necessary around `..f` assignment:

```dart
class ClassWithFunction {
  Function f;
}

class UnnecessaryParenthesis {
  final value;
  UnnecessaryParenthesis() : value = (ClassWithFunction()..f = () => 42);
  //                                 ^                                 ^
}
```

Removing them makes Dart complain either with "Expected an identifier", or, if a parameter `x` is supplied in lambda (`..f = (x) => 42`), "Constructors can't return values".

Not removing them makes `dartanalyzer` complain about unnecessary parenthesis:

```
$ dartanalyzer --options <(echo 'linter: {"rules":["unnecessary_parenthesis"]}') \
    unnecessary_parenthesis.dart 
Analyzing unnecessary_parenthesis.dart...
  lint • Unnecessary parenthesis can be removed at unnecessary_parenthesis.dart:7:38 • unnecessary_parenthesis
1 lint found.
```

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1395
