### ISSUE TITLE
Debugger evaluates type arguments incorrectly (in reverse order)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35581]
Moving this from https://github.com/Dart-Code/Dart-Code/issues/1382 since it seems to be a Dart debugger issue.

Given this code:

```dart
void main() {
  genericMethod<bool, double, int, String>();
}

void genericMethod<TBool, TDouble, TInt, TString>() {
  print('TBool: ' + TBool.toString()); // BREAKPOINT
  print('TDouble: ' + TDouble.toString());
  print('TInt: ' + TInt.toString());
  print('TString: ' + TString.toString());
}
```

If you break on the marked line in `genericMethod` and then evaluate `TBool` and `TString` as expressions, they return the wrong `Type`. `TBool` returns `String`, `TString` returns `bool`, etc. (the order has been interpreted in reverse).

This can repro'd with Observatory:

![screenshot 2019-01-07 at 6 14 49 pm](https://user-images.githubusercontent.com/1078012/50785315-25d48080-12a8-11e9-8923-8d5ed11e715f.png)

Tested with most recent nightly build:

```
dantup-macbookpro:bin dantup$ ~/Dev/dart-sdk/nightly-2019-01-07/bin/dart --version
Dart VM version: 2.2.0-edge.5f25d1546ce35596f9023f784a023dfe6eb8b2aa (Mon Jan 7 17:31:06 2019 +0000) on "macos_x64"
```

**Comment by rmacnak-google** [comment]
@sjindel-google

**Comment by DanTup** [comment]
Fix looks good, thanks!
