### ISSUE TITLE
Make changes to error verifier to catch new null-related error conditions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35583]
Notes from our discussion on Jan 4:
- E.g. catch the user trying to invoke through nullable
- Maybe start with some simple checks?
- Maybe port over some of the void-related errors?

**Comment by bwilkerson** [comment]
* Maybe start implementing a new subclass of `TypeSystem`, in which case these should mostly fall out from existing assignability checks?

**Comment by MichaelRFairhurst** [comment]
I think that's https://github.com/dart-lang/sdk/issues/35582

**Comment by scheglov** [comment]
Lots of work was done, I'm going to close this catch-them-all issue.
