### ISSUE TITLE
Make type system changes to support non-nullability

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35582]
Notes from our discussion on Jan 4:
- We decided to use a non-wrapper approach, i.e. we keep the present `DartType`-derived classes and add field(s) to them to track nullability.
- We decided not to make any changes that are visible through the analyzer public API yet, because we aren't sure whether analyzer clients should be exposed to the existence of "star" types (with indeterminate nullability) yet.
- Leaf's proposed subtyping rules: https://github.com/dart-lang/language/pull/151

**Comment by bwilkerson** [comment]
A proposed implementation of the flags is in https://dart-review.googlesource.com/c/sdk/+/88433 waiting for more review.

**Comment by bwilkerson** [comment]
I'm going to close this issue because I don't believe that there's anything actionable here (and we're using a different tool for tracking tasks).
