### ISSUE TITLE
Analyzer: Setter/method conflict not detected

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35591]
As of cba23af8ceb39b30d02d381d5a59199fd63e6c38, the specification of 'Class Member Conflicts' has been adjusted slightly. The only change which is not a clarification is that there is now a conflict between a method and a getter/setter _also_ in the case where the two members come from distinct superinterfaces. (Previously we only specified an error for the case when the class 'has' a method and 'declares' a getter/setter, and when it 'has' a getter/setter and 'declares' a method.)

This means that those two members are brought together in the same class interface, but there is no location where it is true that the class interface has one of them and declares the other. So we previously did not have a rule to catch this, but with cba23af8ceb39b30d02d381d5a59199fd63e6c38 we do.

The analyzer seems to flag the method &amp; getter conflict as an error already, so there may not be a need to change anything for that. But the method &amp; setter conflict is not detected:

```dart
abstract class A {
  void foo();
  void bar();
}

abstract class B {
  int get foo;
  void set bar(value);
}

abstract class C implements A, B {}
```

A fresh analyzer (from cba23af8ceb39b30d02d381d5a59199fd63e6c38) detects the following problem:

```
ERROR|COMPILE_TIME_ERROR|INCONSISTENT_INHERITANCE_GETTER_AND_METHOD|/usr/local/google/home/eernst/lang/dart/scratch/201901/n001.dart|13|16|1|'foo' is inherited as a getter (from 'B') and also a method (from 'A').
```

which shows that it does not detect the conflict between the method and the setter.

**Comment by srawlins** [comment]
Analyzer now additionally reports:

> The class 'C' can't inherit both a method and a setter named 'bar'.
