### ISSUE TITLE
CFE missing some constant set literal static errors

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35608]
Blocking issue #35122

The following new tests, checking for compile-time-errors in constant_set_literals, are failing
because the fasta compiler is not detecting them.  These tests pass the --enable-experiment=set-literals
flag to fasta.

All in the co19_2 suite: failing with MissingCompileTimeError:
LanguageFeatures/Set-literals/constant_set_literals_A02_t02/01: 
LanguageFeatures/Set-literals/constant_set_literals_A02_t02/02:
LanguageFeatures/Set-literals/constant_set_literals_A02_t02/03:
LanguageFeatures/Set-literals/constant_set_literals_A02_t02/04:
LanguageFeatures/Set-literals/constant_set_literals_A02_t03/01:
LanguageFeatures/Set-literals/constant_set_literals_A02_t03/02:
LanguageFeatures/Set-literals/constant_set_literals_A02_t03/03:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/01:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/02:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/03:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/04:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/05:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/06:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/07:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/08:
LanguageFeatures/Set-literals/constant_set_literals_A05_t01/09:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t01/01:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t01/02:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t01/04:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/01:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/02:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/05:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/06:
LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/08:
LanguageFeatures/Set-literals/semantics_A01_t01/01:
LanguageFeatures/Set-literals/semantics_A01_t01/02:
LanguageFeatures/Set-literals/semantics_A01_t01/09:
LanguageFeatures/Set-literals/semantics_A01_t01/10:
LanguageFeatures/Set-literals/semantics_A05_t05/03:
LanguageFeatures/Set-literals/set_literals_A04_t02/01:
LanguageFeatures/Set-literals/set_literals_A04_t02/02:
LanguageFeatures/Set-literals/set_literals_A04_t02/03:
LanguageFeatures/Set-literals/set_literals_A04_t02/04:
LanguageFeatures/Set-literals/set_literals_A04_t02/05:
LanguageFeatures/Set-literals/set_literals_A04_t02/11:
LanguageFeatures/Set-literals/set_literals_A04_t02/12:
LanguageFeatures/Set-literals/set_literals_A04_t02/13:

**Comment by kmillikin** [comment]
These tests are no longer failing.
