### ISSUE TITLE
Issue for implementing experimental flags in the Dart VM

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35602]
Reference:

[Dart SDK Process for changes behind experimental flags](https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md)

[Dart Experimental Flags Implementation](https://docs.google.com/document/d/1pnaKiqxQqO0-tXhmkFh0lLhvhGTjaVlduDcGOdN1saY/edit?usp=sharing)

This issue is opened to track the following

- implementing the experimental flags option in the command line VM
- hooking up the experimental flags options passed in to the CFE invoked in the kernel isolate
- reading the options embedded in the kernel file and appropriately setting the VM flags

**Comment by liamappelbe** [comment]
Note to self: We also need to plumb this through in gen_kernel

**Comment by liamappelbe** [comment]
This issue is done, except for the last step of deserializing the flags from the kernel. The CFE currently doesn't serialize the flags because there's no experimental feature that needs a VM implementation yet. So deserialization will have to wait until there's a use case.
