### ISSUE TITLE
Some co19_2 tests of experimental features failing on dart2js

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35614]
The // SharedOptions=
annotation is now processed (obeyed) in co19_2 tests as well, and some
tests of experimental features have started failing now, on dart2js.
See CL https://dart-review.googlesource.com/c/sdk/+/88704

These are using the --enable-experiment=constant-update-2018 flag and the 
--enable-experiment=set-literals flag.

They are preapproved, in order to land the change enabling all test annotations on co19 tests,
but should be investigated and fixed. 

co19_2/LanguageFeatures/Constant_update2018/EqualityOperator_A01_t01 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Constant_update2018/EqualityOperator_A01_t02 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Constant_update2018/ShortCircuitOperators_A03_t02 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Constant_update2018/ShortCircuitOperators_A03_t04 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/constant_set_literals_A01_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/constant_set_literals_A02_t02/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/constant_set_literals_A02_t03/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/constant_set_literals_A05_t01/none broke (Pass -> CompileTimeError, expected Pass)
 

 co19_2/LanguageFeatures/Set-literals/exact_types_of_literals_A01_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/exact_types_of_literals_A01_t02/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A01_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A02_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A03_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A05_t02 failed again (RuntimeError -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A05_t03 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A05_t04 broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/semantics_A05_t05/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/set_literals_A01_t02/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/set_literals_A03_t01/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/set_literals_A03_t02/none broke (Pass -> CompileTimeError, expected Pass)
  co19_2/LanguageFeatures/Set-literals/set_literals_A04_t02/none broke (Pass -> CompileTimeError, expected Pass)

**Comment by sigmundch** [comment]
Thanks - We are now accepting the flag. Set-literals are working, constants have not been integrated, but that's tracked elsewhere. I just landed a change updating some of the expectations and we will be looking more closely to what remains.
