### ISSUE TITLE
Report suspicious use of '=='

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#35617]
This program has no warning, hint or lint:
```dart
foo(int id, String name) {
  print(name == id);
  print(id == name);
}

main() {
  foo(1, 'hello');
  foo(null, null);
}
```
It is suspicious because the static type of the receiver and argument are disjoint. The only way `name == id` can be `true ` is if both are `null`. If that is the intention it is clearer to write `name == null && id == null`. It is more likely to be a bug.

I recently spent an hour debugging a bug of this form, where I had `value == 0` but `value` was a `BigInt`, so the test was always false.
There are some cases where this is not an error, for example package fixnum's `Int64.==` that converts `int` values, so `value == 0` is fine when `value` can be an `Int64` (but `0 == value` is still silently wrong).

Given the presence of definitions of `==` that do conversions, a blanket warning would not be appropriate.  But we want to detect as many errors as possible, so a lint is too weak. I suggest:

 - A warning for corelib types where we know the behaviour of `==`. This would have caught my `BigInt` case, and is worthwhile even if the rest of this idea is too hard.

 - An annotation for describing the accepted types that could be used for `Int64.==` to warn on excluded types. An accepted type of `Object` disable the diagnostic.
```dart
  @pragma('analyzer:accepts', int) @pragma('analyzer:accepts', fixnum.Int32)
  operator == (Object other) ...
```

We can usually tell from the body of the `==` method when `==` tests within-domain. Bodies that do _not_ contain code like `other is Foo && ...` could have a hint/lint to annotate with the above annotation.

As a bonus, it would be useful to extend this as far as possible into parametric types, e.g.
```dart
   <T extends num>(T x, String y) => x == y
```
should warn.

**Comment by matanlurey** [comment]
This is, at least partially covered, by `unrelated_type_equality_checks` in the Linter:
https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html.

That being said, I'd be very supportive of the language or tools tightening the definition of `==`.

**Comment by stereotype441** [comment]
@pq FYI

**Comment by pq** [comment]
@rakudrama: is turning on the `unrelated_type_equality_checks` lint an option for you?  That should at least help moving forward (though I agree w/ @matanlurey, it'd be interesting to explore how we could be more proactive in the language and default analysis wrt to `==` checks).

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1394
