### ISSUE TITLE
A value of type 'int' can't be assigned to a parameter of type 'FutureOr<int>'.

### ISSUE THREAD

**Issue by Keksinautin** [dart-lang/sdk#35612]
In this code 
```dart
import 'dart:async';

class A {
  final FutureOr<int> a;
  
  const A({this.a: 2});
}

void main() async {
  final b = const A(); // Here we have an error;
  ///But in this case it works well
  //final b = new A();
  
  print(b.a);
}
```
I have a error: `A value of type 'int' can't be assigned to a parameter of type 'FutureOr<int>'.`
I think this is a very strange result.

[https://gist.github.com/Keksinautin/5366adf409b6762440cdf3c60ab5404b](https://gist.github.com/Keksinautin/5366adf409b6762440cdf3c60ab5404b)

* Dart SDK Version (`dart --version`): **2.1.0**

**Comment by vsmenon** [comment]
I can repro this with the dartanalyzer.  If I run the above directly on the dart VM, it works fine.

**Comment by stereotype441** [comment]
Marking as P1 since this seems like a pretty fundamental type system problem (possibly affecting soundness).  If we investigate and find that it only fails in rare corner cases, we may downgrade to P2.

**Comment by bwilkerson** [comment]
Makes me wonder whether the code I added to unwrap FutureOr in https://dart-review.googlesource.com/c/sdk/+/88741 needed to be added to the assignability testing methods.

**Comment by bwilkerson** [comment]
After looking more closely at the original case, it seems more likely to me that the bug is in the constant evaluation engine, which would somewhat limit the impact of the bug.

**Comment by scheglov** [comment]
I tried to [fix this](https://dart-review.googlesource.com/c/sdk/+/92408), but hit once more type inference limitation.

```dart
test.dart
--------------
import 'test2.dart';

main() {
  const C();
}

test2.dart
--------------
class C {
  final List<int> values;

  const C({this.values: const []});
}
```

  Produces:
`error: A value of type 'List<dynamic>' can't be assigned to a parameter of type 'List<int>'. (const_constructor_param_type_mismatch at [test] bin/test.dart:4)`

**Comment by srawlins** [comment]
This was fixed somewhere along the way. In dart 2.5.2, there are no warnings in the original example, nor in @scheglov's recent example with `List<int>`. dart2js and the VM successfully execute as well.
