### ISSUE TITLE
breaking change: dart:mirrors check types of arguments passed to reflectively invoked methods 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35611]
# Background 

In Dart 2 and Dart 2.1 releases due to a bug in `dart:mirrors` implementation it was possible to violate strong mode type safety via `dart:mirrors`. 

For example the following code:

```dart
import 'dart:mirrors';

class A {
  void method(int v) {
    if (v != null && v is! int) {
      print("This should be impossible: expected null or int got ${v}");
    }
  }
}

void main() {
  final obj = A();
  reflect(obj).invoke(#method, ['not-an-number']);
}
```

In Dart 2.1 release would print 

```
This should be impossible: expected null or int got not-an-number
```

In Dart 2.1.1 we are addressing this issue meaning that this code would start throwing `TypeError`

```
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'v'
#0      _TypeError._throwNew (dart:core/runtime/liberrors_patch.dart:89:51)
#1      _LocalInstanceMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:327:37)
#2      _LocalInstanceMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:323:25)
#3      main (file:///tmp/test.dart:13:16)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

# Expected impact

We expect that only programs that are incorrect with respect to strong mode would break. 

However this might also reveal issues where programs relying on mirrors were not taking care of creating instances of generic classes with correct type arguments - and instead relied on Dart 1 "dynamic-is-bottom" semantics.

For example the following code would stop working:

```dart
import 'dart:mirrors';

class B<T> {
}

class A {
  void method(B<int> v) {
  }
}

void main() {
  final obj = A();
  reflect(obj).invoke(#method, [B()]);
}
```

This would fail with 

```
type 'B<dynamic>' is not a subtype of type 'B<int>' of 'v'
```

# Addressing the breakage

You would need to change your reflective code to pass arguments of correct types, which also means creating instances with correct type arguments. 

Note that if you need to construct object reflectively with the given type arguments you can use  `reflectType` to create type mirror with the given type arguments and then cast this mirror to `ClassMirror` and use `ClassMirror.newInstance`:

```dart
print((reflectType(B, [int]) as ClassMirror).newInstance(const Symbol(""), []).reflectee);  // Instance of B<int>
```

# Known Affected Packages

`package:rpc` see #35009

/cc @mit-mit

**Comment by mit-mit** [comment]
cc @dgrove @Hixie @matanlurey @devoncarew any concerns with this breaking change?

**Comment by devoncarew** [comment]
Mirrors and strong mode have mostly impacted us in the backend of dartpad, which uses package:rpc (which relies in mirrors). @jcollins-g would know more about our exposure here.

**Comment by jcollins-g** [comment]
Isn't this the same bug that I requested a revert for the fix for in 2.1?  It looks like it from the description.

If so, I have a workaround in my back pocket now (https://github.com/dart-lang/dart-services/pull/354) that will bypass this temporarily for dart-services, and the longer-term plan (hopefully this quarter pending grpc-web being done) is to port to grpc.

**Comment by mit-mit** [comment]
Yes, it is the same bug which we reverted for 2.1.0. With that, I assume that you have no objections over this breaking change landing in 2.1.1?

**Comment by jcollins-g** [comment]
Yep, no objections.

**Comment by dgrove** [comment]
LGTM.

**Comment by mit-mit** [comment]
There have been no objections neither here, nor on the Dart Misc/Announce groups, hence this change is approved.

**Comment by joeconwaystk** [comment]
@Hixie Wanted to follow up here on the comment about dropping mirrors entirely. We've heard otherwise - is there a change in direction here?

**Comment by Hixie** [comment]
My understanding is that the current status is that both the Dart VM environment and the Dart DDC environment only support a subset of `dart:mirrors`, that `dart:mirrors` doesn't support everything from Dart 2, and that there is no plan to make any improvements to this. In the Flutter environment, `dart:mirrors` is disabled and we have found alternative solutions each time a request to enable mirrors has been raised. General support for mirrors has numerous disadvantages, such as preventing dead code elimination (tree shaking). There are arguments to be made for having more limited forms of reflection (e.g. metaclasses for classes to which you can actually get a reference, maybe even introspection for classes which are annotated as "published" or some such), but those wouldn't be done using an API like `dart:mirrors`.
