### ISSUE TITLE
Enum + Set is broken when used via an Isolate

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#35626]
```
$ dart --version
Dart VM version: 2.1.1-dev.0.1.flutter-2cb346bd0c (Tue Jan 8 15:52:54 2019 +0000) on "macos_x64"
```

```dart
import 'dart:isolate';

class Content {
  Content(partOfDay) : this.partOfDay = Set()..add(partOfDay);
  final Set<PartOfDay> partOfDay;
}

enum PartOfDay {
  morning,
  afternoon,
  evening
}

foo() async {
  final r = ReceivePort();
  await Isolate.spawn(bar, r.sendPort);
  final Content content = await r.first;

  Set<PartOfDay> pod = Set()..add(PartOfDay.afternoon);
  print('A: ${content.partOfDay}');
  print('B: $pod');
  print('C: ${pod.intersection(content.partOfDay)}');
  print('D: ${content.partOfDay.intersection(pod)}');
}

bar(SendPort sendport) {
  sendport.send(Content(PartOfDay.afternoon));
}

main() async {
  foo();
}
```

Output:

```
A: {PartOfDay.afternoon}
B: {PartOfDay.afternoon}
C: {}
D: {PartOfDay.afternoon}
```

Expected output:

```
A: {PartOfDay.afternoon}
B: {PartOfDay.afternoon}
C: {PartOfDay.afternoon}
D: {PartOfDay.afternoon}
```

This looks similar in scope to https://github.com/dart-lang/sdk/issues/23244

I originally encountered this problem in a Flutter project, and reported it as a Flutter bug: https://github.com/flutter/flutter/issues/26013

**Comment by liamappelbe** [comment]
Interesting bug. Seems to be specific to Set<Enum> (Set<int> works fine).

As a workaround, duplicating the set immediately after you receive it seems to fix the issue:
```
  final r = ReceivePort();
  await Isolate.spawn(bar, r.sendPort);
  final Content content = await r.first;
  content.partOfDay = Set()..addAll(content.partOfDay);
```

**Comment by rmacnak-google** [comment]
Only instances of _InternalLinkedHashMap are rehashed when received through an isolate message. The hash code of enums is probably not stable across isolates.

**Comment by lrhn** [comment]
Yes, our isolate communication is too low-level to understand the logical structure of objects, it just copies them bit-by-bit, and it also doesn't preserve the hash-code of objects. That means that hash-based structures cannot be safely sent over a send-port. We have a hack for the platform hash maps to rehash when copying. We should probably extend it to hash sets.

**Comment by liamappelbe** [comment]
This is going to be non-trivial to fix. Looks like maps are special cased in the VM as with a native RawLinkedHashMap, and RawLinkedHashMap::WriteTo copies the key and values one by one (which takes care of the rehashing).

Sets look like they're entirely implemented in Dart, so they get the default bitwise copy. So I think fixing this will require a native RawLinkedHashSet class (plus a ton of plumbing).

**Comment by SteveAlexander** [comment]
As an alternative, perhaps a warning or error could be given when sending an Enum across isolates?

The problem I had was not that I needed enums to work, but that it took significant effort to find out that they weren't working in the case of Sets.
