### ISSUE TITLE
A test in co19_2 needs to be corrected

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#35623]
I think in test tests/co19_2/src/LanguageFeatures/Instantiate-to-bound/class/dynamic/class_typedef_l1_t02.dart 'dynamic' should be replaced with Null in the type argument inside of 'main'.

**Comment by bkonyi** [comment]
@stefantsov, I think you'll need to file an issue against dart-lang/co19 to get it fixed.

**Comment by dgrove** [comment]
Correct, @bkonyi

**Comment by stefantsov** [comment]
Thanks @bkonyi and @dgrove for the suggestion!  I've reposted it there as https://github.com/dart-lang/co19/issues/221.  I'm closing this issue in dart-lang/sdk.
