### ISSUE TITLE
TFA does not correctly handle case when static field is only written and never read

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/sdk#35632]
@mraleph 
This issue comes up from https://github.com/flutter/flutter/issues/26417
I've dug more and find it's because of callstack below:

![image](https://user-images.githubusercontent.com/817851/51040894-94d90e80-15f3-11e9-90ac-003f76aaaeb0.png)

flutter doctor -v as below:
```
KWLM:doctor -v
[✓] Flutter (Channel master, v1.1.10-pre.37, on Mac OS X 10.14.3 18D32a, locale en-CN)
    • Flutter version 1.1.10-pre.37 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 5a434c61a (11 hours ago), 2019-01-11 10:05:35 +0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)
```

**Comment by alexmarkov** [comment]
Thank you for triaging and short reduction.
The fix is sent out for review: https://dart-review.googlesource.com/c/sdk/+/89161

**Comment by Tabarek** [comment]
I have the same error on how to fix it?

**Comment by mraleph** [comment]
@Tabarek It is unlikely that you have the same error (unless you are using very old installation of Flutter) - because this error has been fixed.

I suggest filing a separate issue for the error you are seeing and I recommend to do it over at Flutter issue tracker.
