### ISSUE TITLE
clean up unnecessary work in dart2js bots

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35638]
dart2js switched it's emitter to be "faststartup" by default. The old emitter is now gone.

We need to:

- [x] stop running tests in both configurations (now they are running all test twice on the same config)
- [x] rename bots to remove the "faststartup" word (there is only one emitter, no need to call out it's historic name)
- [x] remove builders and configurations that are no longer necessary
- [x] remove plumbing of fast-startup in test.py

To save on bot resources, I've sent out right away a fix for the first two.
* https://dart-review.googlesource.com/c/sdk/+/89181: removes redundant work on builders that run both emitters, it also removes the faststartup flag on the remaning faststartup builders
* https://dart-review.googlesource.com/c/sdk/+/89180: moves all bots to use the non-faststartup builders, together with the previous change will allow us to delete the actual builders at some point. 

@athomas @whesse

**Comment by athomas** [comment]
The infra/config part of this was landed in https://dart-review.googlesource.com/c/sdk/+/89220

**Comment by athomas** [comment]
test.py plumbing was removed by @whesse in https://dart-review.googlesource.com/c/sdk/+/89582
