### ISSUE TITLE
Invalid path should cause a proper analyzer error

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#35645]
```
import './pages//product_details_page.dart'; 
```
caused hot-reload to not work but analyzer didn't warn/error.

https://github.com/flutter/flutter/issues/26491

After removing the redundant `/` hot reload worked.

**Comment by srawlins** [comment]
Closing as stale. We have a few issues surrounding the `//`, but AFAIK it is legal syntax. I think we have a lint rule request to warn about double slashes.
