### ISSUE TITLE
Dart VM hangs if native extension returns a invalid UTF-8 string

### ISSUE THREAD

**Issue by MoacirSchmidt** [dart-lang/sdk#35647]
I have just written a dart native extension and realize that when extension returns an invalid UTF-8 string Dart VM hangs without any error message.

I know this is a programmer mistake but Dart VM should return some message instead of simply hangs.

Code to reproduce this issue is here:
https://github.com/MoacirSchmidt/dart_vm_hangs_if_not_valid_utf8

This native extension returns a string "Mês" (this is an ANSI string, not UTF-8 valid) and hangs Dart VM. See line 52 of sample_extension.cpp on link above.

If I change string to "Mas" (a valid UTF-8 string) everything works ok!

I have noticed that this problem occurs always when 
bool ApiMessageWriter::WriteCObjectInlined(Dart_CObject* object,
                                           Dart_CObject_Type type) 
returns false due to check "if (!Utf8::IsValid(utf8_str, utf8_len))" (line 1075 of dart_api_message.cc)

* Reproduced on following versions:
- Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
- Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_ia32"
- Dart VM version: 2.2.0 (built on my PC) on "windows_ia32"

* Running Windows 7-SP1

**Comment by mdempsky** [comment]
Isn't the problem that the response message is invalid so Dart_PostCObject failed, which is effectively the same as not sending a response (and thus causes the Dart code to hang waiting for one)?

It looks like Dart does return an error in the form of having Dart_PostCObject return false on failure, but samples/sample_extension/sample_extension.cc doesn't check this.

**Comment by MoacirSchmidt** [comment]
It is not the same problem but behavior is the same! I  have also experimented that another problem you mentioned!

**Comment by ZichangG** [comment]
Sorry for delayed reply. @MoacirSchmidt 
From your description, some error messages will be helpful instead of returning Null. So one possible solution is to return String with error messages if sending failed. What do you think?
