### ISSUE TITLE
Add a 'tryElementAt' or 'orElse' to elementAt in Iterable

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#35646]
~~The only way to get a single value from a list is to call the bracket operator []. This makes null aware access impossible.~~

~~`var a = list?[5]; // error`~~

~~Is there a reason why lists don't have a `get` method like java?~~

I think lists should have a way to access values in a "safe" manner (similar to double.tryParse).

I propose either a`tryElementAt` method which would return null on a `RangeError` or an optional `orElse` inside `elementAt` which would make elementAt return something instead of throwing.

Would this make sense or am I missing something?

Thanks.

**Comment by julemand101** [comment]
I am sorry if I misunderstand your issue but did you see the elementAt method on Iterable (which List are implementing)?
https://api.dartlang.org/stable/2.1.0/dart-core/Iterable/elementAt.html

You can still get a range error but with this method it is possible to make null aware access to the list object itself.

**Comment by modulovalue** [comment]
Thank you! It's a (somewhat embarrassing) mistake on my part for not being able to find that on my own.

**Comment by lrhn** [comment]
I don't think it's embarrassing. I think it's more embarrassing that we don't have null-aware operator access of any kind yet :)

**Comment by lrhn** [comment]
In any case, we have no plan to change the `Iterable` API at the current time, so I'll close this request.

**Comment by mateusfccp** [comment]
This is still valuable, did we change our plans about changing the `Iterable` API?

**Comment by lrhn** [comment]
No change in our opinion on change. 

Fiddling with `Iterable` will be extremely breaking unless we find some exceedingly clever way to version APIs.
