### ISSUE TITLE
The VM doesn't provide an API to tweak the profiler sampling rate once an application has flutter

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#35654]
For Flutter, a much higher sample rate than the default rate is needed to get useful output when profiling rendering a frame.
For example, with the default rate you only get ~ 8 samples in a typical frame which makes it hard to see what happened.

The VM looks like it could actually support increasing the sample rate on the fly without much difficulty. That would allow us to crank up the rate when recording a profile and then lower it as soon as the stop button is pressed.

**Comment by bkonyi** [comment]
`profile_period` can now be changed via the `setFlag` service API as of [this change](https://dart-review.googlesource.com/c/sdk/+/89445).
