### ISSUE TITLE
dart2js: track the need of affinity tags explicitly

### ISSUE THREAD

**Issue by Keksinautin** [dart-lang/sdk#35652]
This code:
```dart 
// same with import 'package:js/js.dart';
import 'dart:js'; 

void main() {
  allowInteropCaptureThis(() {
	  print('a');
  });
}
```
Have this result
```
Uncaught exception:
TypeError: Instance of 'Function': type 'Function' is not a subtype of type 'Function'
```
But only after the `dart2js` compilation, with `DDC` it works just well.

I guess it is not expected behavior.

* Dart SDK Version (`dart --version`) 2.1.0

**Comment by sigmundch** [comment]
Sorry - I need to clarify. I was testing this in the latest version of dart2js, where I got a different error:
```
TypeError: init.getIsolateTag is not a function                                                                              
    at /tmp/out.js:2280:19                                                                                                         
    at Object.holder.(anonymous function) (/tmp/out.js:105:35)                                                                                             
    at Object._convertDartFunctionFastCaptureThis (/tmp/out.js:1521:13)                                        
    at Object.allowInteropCaptureThis (/tmp/out.js:1537:41)                                                            
    at main (/tmp/out.js:1542:9)                                                                                         
```

Turns out that the new error is related to the issue I explained above. My error and yours are different because dart2js switched to use the `--fast-startup` emitter by default, so the error was triggered earlier.

Adding the use of the DivElement above circumvented not only this new error, but also the error you saw,f or some reason.

**Comment by sigmundch** [comment]
and to wrap up my monologue :) - The two issues are one and the same.

the `allowInteropCaptureThis` function returns a special kind of function object (a JavaScriptFunction), this type is not preserved properly due to the same bug that made us miss `getIsolateTag` in the `fast-startup` emitter. The compiler needs to see some native type allocated somewhere in order for this to work.

Most programs contain such allocation, which is why this error is so hard to find and see.

**Comment by sigmundch** [comment]
Just renamed the bug to help us track this in the future.

**Comment by Keksinautin** [comment]
Hi @sigmundch,

Thank you for the response, and sorry for my long silence - I was on vacation. 

Do you want to say that this bug is not important, because my usage is unusual and unpopular?
In this case, could you please propose a code snippet in which the functions `allowInteropCaptureThis` works?

My guess was that if the function is exists it should work, at least in the easiest variant, am I wrong?

Because of this bug I have to write a code like this:
```dart
    final that = this;
    // ignore: unnecessary_lambdas
    globalJsPropertyToCall = allowInterop(() {
      that.someClassMethod();
    });
```

In my opinion it doesn't look like a good piece of code, what do you think?

**Comment by sigmundch** [comment]
> Do you want to say that this bug is not important, because my usage is unusual and unpopular?

Sorry for the confusion, no. I meant that with a small workaround, your code could be made to work without you having to wait until we find how to properly fix the problem and ship it.

Change your main to add:
```dart
import 'dart:js';
main() {
  context['document']; // line added to workaround issue #35652
  ...
```

or:
```dart
import 'dart:html';
main() {
  new DivElement(); // line added to workaround issue #35652
  ...
```

and I expect you will no longer hit the issue.

Also if it still doesn't work, let us know if using the `--fast-startup` flag in dart2js fixes it or using the latest SDK (where `--fast-startup` is the default).

> Because of this bug I have to write a code like this [...]

Thanks for sharing this snippet, could you try and see if this works instead:
```dart
  globalJsPropertyToCall = allowInterop(someClassMethod);
```

I have a feeling that your use case is fine with just `allowInterop` and without `allowInteropCaptureThis`.

I believe there is confusion on what `allowInteropCaptureThis` is supposed to do. In particular, "CaptureThis" is referring to the JavaScript `this`, and not to the Dart `this`. Dart always captures the enclosing `this`, so you don't need to do anything special to have access to it in your callback. In JavaScript, it is possible to create functions that are not bound and some APIs require that you give them a callback that has a `this` instance bound to it. The interop library provided `allowInteropCaptureThis` to make it easy to create those JavaScript functions for those special JS APIs, but I think for most use cases `allowInterop` is all you need.

**Comment by Keksinautin** [comment]
Yes, thank you, you are right, just `allowInterop` works fine in my case. I had to try it.

**Comment by sigmundch** [comment]
@fishythefish - I believe the changes you landed in
72ba7461d057eee14de35a924bcbecdd9d361712 and
5148afa2fa6e6873b812a27ea830b87c4c194b18

will fix this issue too, correct?

**Comment by fishythefish** [comment]
Yes, I believe that should be the case.
