### ISSUE TITLE
report all compilation errors when performing incremental recompilation

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35666]
If you recompiling code with errors incrementally front-end server will only report errors in the code that gets recompiled, but will swallow the errors in the code (libraries) which did not change.

This might be misleading to users. See flutter/flutter#23121

**Comment by kmillikin** [comment]
I agree, this is misleading.  We'll fix it to report all errors on recompilation.

**Comment by jensjoha** [comment]
Should be fixed with d9072d52725774f1f422327a731fa616806fe927.
