### ISSUE TITLE
Error compiling dartdevc module: (The exported library ''foo_impl.dart'' can't have a part-of directive.)

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#35672]
Dart version: 2.1.0

We try to use conditional exports in our code base to solve the old Dart1 transformers feature, but it seems to work well on Dart VM and Dart Dart2JS compiler only, and fails on DDC compiler. (Dart Analysis has no error at all)

The following example can reproduce this error.
* `main.dart`
```
import 'foo.dart';

void main() {
  print(Foo().sayHi());
}
```
* `foo.dart`
```
// ignore: uri_does_not_exist
export 'foo_impl.dart'
// ignore: uri_does_not_exist
if (dart.library.html) 'html_foo_impl.dart'
// ignore: uri_does_not_exist
if (dart.library.io) 'io_foo_impl.dart';
```

* `foo_impl.dart`
```
class Foo {
  String sayHi() => 'foo';
}
```

* `html_foo_impl.dart`
```
class Foo {
  String sayHi() => 'html_foo';
}
```

* `io_foo_impl.dart`
```
class Foo {
  String sayHi() => 'io_foo';
}
```

And then run with the command 

```$ pub run build_runner build test```

The error messages:
```
[INFO] Generating build script completed, took 371ms
[INFO] Reading cached asset graph completed, took 333ms
[INFO] Checking for updates since last build completed, took 769ms
[INFO] Running build completed, took 189ms
[INFO] Caching finalized dependency graph completed, took 161ms
[SEVERE] build_web_compilers|ddc on test/main.dartdevc.module (cached):
Error compiling dartdevc module:foo|test/main.ddc.js

[error] The exported library ''foo_impl.dart'' can't have a part-of directive. (/test/foo.dart, line 2, col 8)

Please fix all errors before compiling (warnings are okay).
}

```

**Note:** If we run with `$ pub run build_runner build test -r` or `$  pub run test test/main.dart` no error at all.

**Comment by jumperchen** [comment]
I found a workaround by adding the `ignore: export_of_non_library` for foo.dart.

For example,
```
// ignore: uri_does_not_exist, export_of_non_library
export 'foo_impl.dart'
 // omitted
```

**Comment by natebosch** [comment]
Let's track this together with #34179 since I think it's another symptom of the same root cause.
