### ISSUE TITLE
unused_element is confused by a function with the same name in two classes

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35677]
SDK: 2.1.1-dev.1.0

`hint: The method '_private2' isn't used. (unused_element at [json])` - on class A

Did **not** get one for `A._private` though. Seems it's confused by the use of `_private` in `B` – even though it's an unrelated class.

```dart
class A {
  _private() => null; // don't get `unused_element` here, though – BUG!
  _private2() => null; // get `unused_element` here – as expected
}

class B {
  public() => _private();
  _private() => null; // No issue here, as expected
}
```

**Comment by kevmoo** [comment]
Thanks! Can't wait for the next few release to see how many of these we
have in the wild!

**Comment by rakudrama** [comment]
After checking in the fix, I am getting new cases:

```
$ tools/test.py -nunittest-asserts-no-sdk-linux dart2js/analyses/analyze_test
...
pkg/compiler/lib/src/js_backend/field_naming_mixin.dart:193:11: warning: hint:
[UNUSED_ELEMENT] The declaration '_localFieldNameCounter' isn't referenced.
pkg/compiler/lib/src/js_backend/field_naming_mixin.dart:109:11: warning: hint:
[UNUSED_ELEMENT] The declaration '_localFieldNameCounter' isn't referenced.
...
```
The getter at 193 overrides the getter at 109.
The getter at 109 (and setter) is called from 165, in the same class:
```
  jsAst.Name _nextName() => registry.getName(_localFieldNameCounter++);
```

**Comment by srawlins** [comment]
Eek, sorry @rakudrama I'll look at this.
