### ISSUE TITLE
Is it a bug? why can't use 'on' to catch an exception defined by myself ?

### ISSUE THREAD

**Issue by Buerkut** [dart-lang/sdk#35686]
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) ;
OS: macos_x64;

As the title, I met a problem,  and I don't know whether it is my bug or a bug of sdk.
the sample code is below：

```
class AException implements Exception {
  const AException();
  String toString() => 'AException';
}

class A {
  void at() => throw AException;
}

void main() {
  try {
    var a = A();
    a.at();
  } on AException catch (e) { // the catch line
    print(e);
  }
}

```

But when run it, I got a uncatched exception:
```
Unhandled exception:
AException
#0      A.at (file:///Users/Buerkut/Documents/Compute/Develop/Workspace/Dart/data_struct/bin/ebug.dart:7:16)
#1      main (file:///Users/Buerkut/Documents/Compute/Develop/Workspace/Dart/data_struct/bin/ebug.dart:13:7)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
in the catch line as comments, the "on AException catch (e)'' seems useless. If changed
```
on AException catch (e)
```
to 
```
catch (e)
```
it will be ok.and print the exception:
```
AException
```
Is it a bug or my error? Thanks a lot!

-------------

plus, why does dart cancel the semicolon ';' at the line end? it is very inconvenient.

**Comment by dhil** [comment]
The exception clause `on AException catch (e)` matches an *instance* of `AException`, but at the throw site `throw AException` a *class name* is thrown rather than an instance. Try throwing an instance of `AException` instead, for example `throw AException()` (note the parentheses).

**Comment by Buerkut** [comment]
Ok, I got it! thank you very much! It's right! @dhil

**Comment by Buerkut** [comment]
sorry, I have another question: why doesn't the compiler report an error when throwing a classname instead of an instance? @dhil

**Comment by zoechi** [comment]
A type name is a valid expression that returns a Type instance.
In Dart you can throw any value, not only Exceptions.

**Comment by Buerkut** [comment]
OK，throwing anything is powerful, but I think at least in handling exception flows the design should be more strict. Otherwise it is maybe ambiguous.

**Comment by zoechi** [comment]
@Buerkut 

> handling exception flows the design should be more strict

I don't understand what you mean here.

Perhaps you want to enable https://dart-lang.github.io/linter/lints/only_throw_errors.html
https://www.dartlang.org/guides/language/analysis-options#enabling-linter-rules

**Comment by Buerkut** [comment]
OK，I see. thank you all ! @zoechi @dhil
