### ISSUE TITLE
Rename klass getter on InstanceConstant to classNode

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#35696]
Getters in the kernel AST API which return the class of something are generally called `classNode`. However, the getter in `InstanceConstant` deviates from this convention by being named `klass`. We want to change this getter name to `classNode` for API consistency.

The `InstanceConstant` class is part of the constants API, which is currently only used internally in the AOT compiler and not yet produced by the front-end.

According to searches for uses of the `InstanceConstant` class, no internal code, nor any public code on GitHub, use the `klass` getter, except in forks of the Dart SDK.

For these reasons, the impact of the change is expected to be minimal.

To adapt code to be compatible with the change, simply use the new getter name, `classNode`, in place of the old one, `klass`.

**Comment by mit-mit** [comment]
cc @Hixie @matanlurey for feedback

**Comment by mit-mit** [comment]
Background information on Dart kernel available here: https://github.com/dart-lang/sdk/tree/master/pkg/kernel

**Comment by Hixie** [comment]
I support the cause.
