### ISSUE TITLE
offer a quick fix for nullable operators

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35691]
When we see the following code:

```
return subtreeRoot != null ? subtreeRoot.valueRef : null;
```

we should offer a quick fix to convert to:

```
return subtreeRoot?.valueRef;
```

cc @jacob314 @kenzieschmoll

**Comment by bwilkerson** [comment]
Yes, we should. We either have a lint or have a request for a lint to find this case. Is that the lint that you're thinking of having a quick fix for?

**Comment by devoncarew** [comment]
I think so, but I guess I didn't really consider whether this should be a quick fix (associated with a lint) or a quick assist - just offered if the user asked what was available at that location.

**Comment by bwilkerson** [comment]
We have a small number of quick assists that would have worked as fixes for a lint but are useful even for developers that don't enable the lint. That approach seems to make sense in this case.

**Comment by bwilkerson** [comment]
I didn't find that particular lint rule, but in case they're useful I did find two rules related to null-aware operators:

- https://dart-lang.github.io/linter/lints/prefer_conditional_assignment.html
- https://dart-lang.github.io/linter/lints/unnecessary_null_in_if_null_operators.html

We should also support the inverse order: `subtreeRoot == null ? null : subtreeRoot.valueRef`.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/94124
