### ISSUE TITLE
dart2js crash 

### ISSUE THREAD

**Issue by cgiess** [dart-lang/sdk#35697]
* Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64"
* Ubuntu 18.10 (Linux hostname 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

The compiler crashed: NoSuchMethodError: The getter 'inferrer' was called on null.
Receiver: null
Tried calling: inferrer
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ElementInfoCollector._hasBeenResolved (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:164:59)
#2      ElementInfoCollector.visitField (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:121:36)
#3      ElementInfoCollector.visitLibrary.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:88:31)
#4      JsToElementMapBase._forEachLibraryMember.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:182:8)
#5      Iterable.forEach (dart:core/iterable.dart:277:30)
#6      JLibraryEnv.forEachMember (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_model/env.dart:114:23)
#7      JsToElementMapBase._forEachLibraryMember (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:181:16)
#8      JsElementEnvironment.forEachLibraryMember (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:1304:16)
#9      ElementInfoCollector.visitLibrary (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:80:17)
#10     Iterable.forEach (dart:core/iterable.dart:277:30)
#11     ElementInfoCollector.run (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:58:27)
#12     DumpInfoTask.dumpInfo.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:552:11)
#13     CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#14     DumpInfoTask.dumpInfo (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:549:5)
#15     Compiler.generateJavaScriptCode (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:379:20)
#16     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:395:9)
#17     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#18     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:389:14)
#19     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:276:5)
<asynchronous suspension>
#20     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#23     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#24     Compiler.run (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#25     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#26     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by sigmundch** [comment]
@cgiess thanks for reporting the issue.

I believe we have fixed this issue in version 2.1.1-dev.0.0 (from commit 0fded45)

I'm closing this assuming this is the case, but please feel free to reopen if that's not the case. If you are still hitting this issue, it would help us to have some steps on how you can reproduce the issue(for example, a simple input program you are compiling and flags you passed to the compiler).

Thanks!
