### ISSUE TITLE
Stocks microbenchmark regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35694]
https://github.com/dart-lang/sdk/commit/7e1aa678551e33cb9d5de485b1f2fcd79f74e59e regressed the stocks microbenchmark.

**Comment by Hixie** [comment]
cc @jason-simmons who did the work of bisecting to find the cause. Thanks Jason.

**Comment by Hixie** [comment]
cc @a-siva @aam

**Comment by jason-simmons** [comment]
The affected benchmark is microbenchmarks/stock_layout_iteration

```
cd flutter/dev/devicelab
dart bin/run.dart -t bin/tasks/microbenchmarks.dart
```
