### ISSUE TITLE
Type analysis is incorrect when an SDK type is shadowed by a non-SDK type

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35709]
When a class declares a member that uses a type T, and the class's library imports two libraries which declare T, then the T is lost in locations where it should be inferred.

Take this library:

```dart
class File {
  final String s;

  File(this.s);
}
```

and import it from a file which also imports 'dart:html':

```dart
import 'dart:html'; // ignore: unused_import
import 'package:ddc_repro/lib.dart';
import 'package:test/test.dart';

class Foo {
  File _a = File('a');
  File _b = File('b');
  List<File> list;

  Foo() {
    list = [_a, _b];
  }
}

void main() {
  test('yay', () {
    List<File> list = Foo().list;
  });
}
```

DDC errors on this test:

```
00:04 +0 -1: yay [E]                                                                                                                                                                                   
  Type 'List<dynamic>' should be 'List<File>' to implement expected type 'List<File>'.
  dart:js               check_C
  html_test.dart 17:16  test_core$.test.dart.fn
```

Here are a few ways to avoid the error:

1. Remove the import of 'dart:html'.
2. Prefix the import of 'dart:html'.
3. Put an explicit `<File>` type argument on the list literal.
4. Make everything local, rather than using the class members:

   ```dart
   import 'dart:html'; // ignore: unused_import
   import 'package:ddc_repro/lib.dart';
   import 'package:test/test.dart';

   File _a = File('a');
   File _b = File('b');

   void main() {
     test('yay', () {
       List<File> list;
       list = [_a, _b];
       List<File> list2 = list;
     });
   }
   ```

**Comment by srawlins** [comment]
CC @jmesserly; this was hit internally during DDC runtime cast cleanup.

**Comment by jmesserly** [comment]
DDC doesn't do any type inference or implicit cast placement, so this is probably coming from Analyzer.

**Comment by srawlins** [comment]
Ah ok, @stereotype441, can you triage please?

**Comment by renatoathaydes** [comment]
Here's a simple example which I think shows the exact same behaviour from the Analyser:

**other.dart**
```
class EventSink {}
```

**example.dart**
```
import 'dart:async';

import 'other.dart';

abstract class Factory {
  EventSink create();
}

tryit(Factory f) async {
  // doesn't compile
  EventSink sink = f.create();
}
```

Error:
```
error: A value of type 'dynamic' can't be assigned to a variable of type 'EventSink'. (invalid_assignment at [eventory] example.dart:11)
```

I was bitten by this in a real project and it took a while to figure out what was happening...

Here's what it looks like from IntelliJ:

![Dart Analyser confused](https://files.gitter.im/dart-lang/sdk/ownv/Screenshot-from-2019-08-03-20-40-55.png)

`dynamic` seems to be inferred as the type of a method when there's a clash in the imports.

**Comment by renatoathaydes** [comment]
I think the correct behaviour from the Analyser would be to consider the type that clashed as an unknown type until the conflict was resolved, and also emit a clear type conflict error like `the EventSink type is being imported from both dart:async and other.dart. Either hide it from one of the imports, or use namespaced imports to prevent conflicts.`

**Comment by srawlins** [comment]
The analyzer no longer confuses shadowed elements like this.
