### ISSUE TITLE
approve_results.dart: send email to team

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35702]
Would it be possible to send an email to a team when someone runs the approve script?

I think this could help demystify the approval process and let each team decide how to file issues without imposing the workflow on others. For example, if someone adds a test that fails on dart2js, rather than filing a bug and approving the change, they could instead approve it and we would get an email notifying us so we can act on it. We may file a bug or may decide to add a comment on an existing bug, or something else.

**Who to notify?** maybe we need a table associating bot names to email addresses, similar to what we do to get CC'd on gerrit CLs

**How to notify?** say who approved it (I believe you already track that) and maybe add a link to the approved tests? Since the list can sometimes be very large, adding a link might make the email easier to digest, we could also then reuse the link on a bug entry.

**Comment by sortie** [comment]
Yeah I would love to do something like this. I'm not sure we're ready to do this yet, we've still exploring how to best make the approval data more accessible.
