### ISSUE TITLE
Dead code lint should detect "return null" after otherwise complete enum-based switch

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35716]
_From @Hixie on August 20, 2018 23:12_

Once #1139 is fixed, a `return null` after a (complete) switch over an enum where every branch terminates (throws, returns, or exits) and where the switch variable is previously asserted to be non-null should be flagged as dead code:

```dart
enum Foo { a, b, c }

String hello(Foo value) {
  assert(value != null);
  switch (value) {
    case Foo.a: return 'A';
    case Foo.b: return 'B';
    case Foo.c: return 'C';
  }
  return null; // This should be considered dead code.                                                                         
}
```

_Copied from original issue: dart-lang/linter#1140_

**Comment by pq** [comment]
@bwilkerson : should this be moved over to the SDK repo?

**Comment by pq** [comment]
_From @bwilkerson on January 20, 2019 15:52_

Yes. The dead code detection is done in analyzer.

**Comment by srawlins** [comment]
This will be completed as part of the NNBD type system; not likely before.
