### ISSUE TITLE
ForEachStatement offset doesn't take await keyword into account

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#35723]
With analyzer-0.33.6+1 the offset of `await for (...)` points on the first letter of `for` but should be on the first letter of `await`.

/cc @bwilkerson

**Comment by bwilkerson** [comment]
That doesn't make any sense. The line of code responsible for this hasn't changed since 2016.

Nevertheless, it's definitely wrong and the fix should be easy.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/90442
