### ISSUE TITLE
Highlighting and error checking in Dartdoc code

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#3572]
We often have code examples in DartDoc. They get out of sync with the actual code very easily, and are harder to read because they aren't syntax highlighted. It would be really nice if the editor could recognize code fragments in DartDoc comments and do syntax highlighting and error checking on them. There are already mechanisms that DartDoc uses to indicate code fragments, so this ought to be recognizable. There might be an issue with needing to recognize that this code isn't actually part of the file, as it might break, or two different code fragments might define a function with the same name, so each needs to be treated somewhat separately, and not compiled as part of the file. But it would be really really nice.

**Comment by srawlins** [comment]
This seems like it would be impossible to do without false positive warnings. The following code blocks, that might be found in Dartdoc comments, would produce false analyzer warnings:

1. Dart code with pseudocode:
    ```
    callAFunction();
    callSomethingElse();
    ...
    var a = foo();
    ```

2. Code blocks that don't contain Dart:
    ```
    <p>This is html. Not dart. The analyzer probably wouldn't take kindly to that.</p>
    ```

3. Code with undeclared identifiers. Would the analyzer know that only a subset of warnings are valid in example code?
    ```
    someFunction(myVariable);
    ```

This would also pull in package:markdown as a dependency to the analyzer.

**Comment by srawlins** [comment]
Close as infeasible for the reasons above?

**Comment by bwilkerson** [comment]
There are ways to make things better than they are, but I don't care that much whether we leave this as a reminder or close it.
