### ISSUE TITLE
provide a way to specify that method can be torn-off reflectively

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35720]
An annotation `@pragma('vm:entry-point', 'get')` on a method should be interpreted as a signal that method is torn-off reflectively.

**Comment by mkustermann** [comment]
> Should it mean that the method is only torn off or also called?

When we create the implicit closure function, we inevitably will also generate the real function, do we not?

**Comment by sjindel-google** [comment]
If it's only torn off, we can inline the real function into the method without duplicating the code.

**Comment by mkustermann** [comment]
This has been implemented by ae7bf9e999b09efc45d87a4f6f01f11832b2d442
