### ISSUE TITLE
analyzer should not support ignore: for error level issues

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35738]
The analyzer shouldn't support using the `// ignore:` syntax for error level issues (just warnings, hints, and lints).

```
    // ignore: invalid_assignment
    int foo = '';
```

**Comment by devoncarew** [comment]
Specifically, the above shouldn't suppress the reported issue, and it may cause an issue to be reported for the `ignore: invalid_assignment` line itself.

**Comment by srawlins** [comment]
Dupe of https://github.com/dart-lang/sdk/issues/27218
