### ISSUE TITLE
Please merge 3cb16d20 into dev channel

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#35739]
**commit(s) to merge**: 3cb16d20

**merge instructions**: merges cleanly in `origin/dev`

**reason**: https://github.com/dart-lang/sdk/issues/35551 fixes race condition during re-building parts after their libraries have already been analyzed. Affects Analysis Server users.

Commit: https://github.com/dart-lang/sdk/commit/3cb16d20e7810a2a378bb897d939f67c0b380d88

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Released in 2.1.1-dev.3.2.
