### ISSUE TITLE
Running dartanalyzer in the Dart sdk build checkout fails to find .packages

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35736]
Running dartanalyzer version 2.1.1-dev.0.1 in the root of the SDK checkout (the gclient checkout of the SDK repo for building dart), on tools/testing/dart/main.dart, fails if the --packages .packages option is left off.

The command
dartanalyzer tools/testing/dart/main.dart

does not find the package at pkg/smith, and reports 600 errors.

The comand
dartanalyzer --packages .packages tools/testing/dart/main.dart
succeeds and finds no errors.

It it intended that dartanalyzer does not find and use a .packages file in the current directory?

**Comment by bwilkerson** [comment]
> It it intended that dartanalyzer does not find and use a .packages file in the current directory?

Yes, though in this case the distinction is moot.

It's intended that it looks for the '.packages' file most closely associated with the file being analyzed. I would have expected it to look in 'sdk/tools/testing/dart', 'sdk/tools/testing', etc. until it found the one in 'sdk', irrespective of the current working directory.

So, this sounds like a bug to me.

**Comment by srawlins** [comment]
Closing as stale since we don't look at `.packages` files any longer.
