### ISSUE TITLE
Remove internal uses of task model from analyzer tests

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35734]
https://dart-review.googlesource.com/c/sdk/+/84687 removes support for the analyzer task model.  Clients have already been migrated to use newer analyzer APIs such as `AnalysisSession`.  However, there are some internal uses of the task model in analyzer tests.  These tests need to be modified so that they still test the analyzer effectively, without using the task model:
- [x] ElementLocatorTest
- [x] ErrorReporterTest2
- [x] ExitDetectorTest2
- [x] ConstantEvaluatorTest
- [x] DeclarationResolverMetadataTest
- [x] DeclarationResolverTest
- [x] StrongModeDeclarationResolverTest
- [x] ElementResolverCodeTest
- [x] ErrorResolverTest
- [x] SimpleResolverTest
- [x] AnalysisDriverTest
- [x] ConstantVisitorTest
- [x] ClassElementImplTest
- [x] ElementAnnotationImplTest
- [x] FieldElementImplTest
- [x] MethodElementImplTest
- [x] MethodMemberTest
- [x] ParameterElementImplTest
- [x] TopLevelVariableElementImplTest
- [x] ExprBuilderTest
- [x] ResynthesizeAstStrongTest
- [x] ParseYamlTaskTest

**Comment by scheglov** [comment]
Tests migration was done.

**Comment by bwilkerson** [comment]
There is still a class `TestAnalysisContext` that subclasses the task-based analysis context. Doesn't that also need to be removed?

**Comment by scheglov** [comment]
Good point.
https://dart-review.googlesource.com/c/sdk/+/97270
