### ISSUE TITLE
Go verify behavior in EditDomainHandler.getAssists

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#35741]
Context: https://github.com/dart-lang/sdk/issues/34152

After @scheglov's change lands (https://dart-review.googlesource.com/c/sdk/+/90840), go test IntelliJ DAS protocol back and forth to ensure that there are no follow up issues with the Dart Analysis Server and IntelliJ with `EditDomainHandler.getAssists`.

**Comment by alexander-doroshko** [comment]
I was not aware of the discussion in #34152 and this issue. But I also noticed the problem while was testing dart web debugger, and fixed it: https://github.com/JetBrains/intellij-plugins/commit/71603ae6ae08fca16463a988883e8488d8b5e699

@jwren Feel free to close, I don't have permissions here.
