### ISSUE TITLE
Analyzer doesn't detect compile-time error for mismatched types in constant containers

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35748]
Consider the following code (assuming `--enable-experiment=set-literals`):
```dart
const Object o = const Object();
main() {
  const a = <int>[o];
  const b = <int>{o};
  const c = <int, int>{o: 1};
  const d = <int, int>{1: o};
}
```

From a static error perspective, the constant declarations of `a`, `b`, `c`, and `d` are all valid, because Object is assignable to int.  However, constant evaluation should report an error, because the type of the *value* of `o` is Object, and it is unsound to store a value of type Object in a list, set, or map where an int is expected.

The VM and dart2js report the correct error.  The analyzer and DDC don't report any error at all.

**Comment by srawlins** [comment]
The analyzer now reports four errors:

> error • The element type 'Object' can't be assigned to the list type 'int'. • a.dart:3:19 • list_element_type_not_assignable
> error • The element type 'Object' can't be assigned to the set type 'int'. • a.dart:4:19 • set_element_type_not_assignable
> error • The element type 'Object' can't be assigned to the map key type 'int'. • a.dart:5:24 • map_key_type_not_assignable
> error • The element type 'Object' can't be assigned to the map value type 'int'. • a.dart:6:27 • map_value_type_not_assignable
