### ISSUE TITLE
DiscoverBlocks doesn't take into account PhiInstr

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#35740]
[DiscoverBlocks](https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/backend/flow_graph.cc#L219 ) doesn't take into account ordering of variables in Phi instructions that basic blocks might have.
This becomes a problem where flow graph is changed(as part of 
[PrepareInlineByteArrayBaseOp](https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/backend/inliner.cc#L2848) for example), new PhiInstr are added with variables coming from new basic blocks in certain order, but DiscoverBlocks traverses basic blocks in such a order that resulting predecessor list doesn't match order of variables in PhiInstr.

**Comment by aam** [comment]
cc @mraleph @aartbik

**Comment by mraleph** [comment]
That is why predecessors are always sorted by `block_id()` to give stable ordering. See `JoinEntryInstr::AddPredecessor`. 

When you are doing graph mutations that add/replace predecessors you need to take that into account. See for example code in `ReplaceAsPredecessorWith` or `FlowGraph::MergeBlocks`

**Comment by aartbik** [comment]
Thanks! This is one of those assumptions we should translate to code in a "graph checker" that runs after every pass.
