### ISSUE TITLE
How to implements getter and setter property proxy

### ISSUE THREAD

**Issue by 100cm** [dart-lang/sdk#35743]
I want  to  auto setState()  in flutter when i set my property

for example

```
set someState(value){
setState(){
value ++
}
}
```

and i want to auto setState for all my properties  in my class ,could i do this?

**Comment by zoechi** [comment]
`setState()` is only available in `StatefulWidget`s and not in model classes.
I don't think this is a good idea.

**Comment by kevmoo** [comment]
This seems like a language request, but it could use more information @100cm 

CC @leafpetersen @munificent
