### ISSUE TITLE
No tip on Android Studio

### ISSUE THREAD

**Issue by rhymelph** [dart-lang/sdk#35752]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1440x900`

# Exception

Please append the contents of:
file://C:\Users\lwl\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: F:\Flutter\project\rhy_base\lib\page\PersonPage.dart
Exception: Element not found in summary: dart:core

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
