### ISSUE TITLE
inconsistent deprecated_member_use_from_same_package between two machines on same SDK version?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35750]
pubspec_parse at a specific commit: https://github.com/dart-lang/pubspec_parse/commit/5557745c2acbe757d7a6fd8740b0502e4cf83e50

Dart VM version: 2.1.1-dev.3.2

On my mac, `dartanalyzer --fatal-infos --fatal-warnings .` runs fine – zero errors/warnings/hints

On travis, with the same SDK version (but on linux)

https://travis-ci.org/dart-lang/pubspec_parse/jobs/484095285#L506-L515

```console
$ dartanalyzer --fatal-infos --fatal-warnings .
Analyzing pubspec_parse...
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:19:18 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:52:18 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:128:20 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:138:20 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:148:20 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:159:20 • deprecated_member_use_from_same_package
  hint • 'author' is deprecated and shouldn't be used at test/parse_test.dart:170:20 • deprecated_member_use_from_same_package
7 hints found.
```

🤷‍♂️

**Comment by kevmoo** [comment]
Related commit? https://github.com/dart-lang/sdk/commit/c54bc11770fd35ee739c7abac247029a99536553 @srawlins

**Comment by kevmoo** [comment]
@scheglov @stereotype441 – ides?

**Comment by srawlins** [comment]
I suspect this is an issue with the Workspace concept; on travis, `.dart_tool` is never generated, so it thinks it is in a PubWorkspace; but on your Mac, I'll bet you _do_ have a `.dart_tool` in this repo checkout, so it thinks its a PackageBuildWorkspace.

**Comment by kevmoo** [comment]
> I suspect this is an issue with the Workspace concept; 

Yup! Deleting `.dart_tool` on my mac gives me the same output! Feel free to rename this issue to track the "real" problem...
