### ISSUE TITLE
dart:ffi Strings

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35762]
Add library functions to convert Dart strings to C strings and vice versa.

**Comment by dcharkes** [comment]
In our tests (and a simplistic SQLite wrapper) we use https://github.com/dart-lang/sdk/blob/master/tests/standalone_2/ffi/cstring.dart

It's so simple it should probably not be part of the sdk.

**Comment by mit-mit** [comment]
There's an initial version of this now in https://github.com/dart-lang/ffi

We should see if we can make memory management easier. It would be very beneficial if you could pass string constants to C functions and now have to worry about free'ing them.

**Comment by dcharkes** [comment]
Great! Thanks @sjindel-google and @mit-mit!

Should we migrate our examples and tests to depend on `package:ffi` instead of having duplicated code? (Though how do we prevent our tests/samples from breaking? Should we pin the version we use?)

**Comment by mit-mit** [comment]
Yes, I think we should.

Examples that are apps generally protect themselves using dependency pinning (i.e. checking in the .lock file): https://dart.dev/guides/libraries/private-files#pubspeclock

**Comment by dcharkes** [comment]
We've got support for strings in `package:ffi`. I've opened a new issue for copy-free strings. Closing this issue.
