### ISSUE TITLE
dart:ffi IA32

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35774]
Support `dart:ffi` on 32 bit Linux, Windows, and Macos.

**Comment by dcharkes** [comment]
Landed in https://github.com/dart-lang/sdk/commit/b032f1b284f6f8f6b38b5097fa40840f1ccf1eed.

**Comment by sjindel-google** [comment]
Structs aren't supported yet though...

**Comment by sjindel-google** [comment]
https://github.com/dart-lang/sdk/issues/36334
