### ISSUE TITLE
[vm/ffi] Allow subclassing Pointer?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35782]
`dart:ffi` provides two ways to instantiate `Pointer` objects: `allocate` and `fromAddress`.

Structs in `dart:ffi` are modeled as subtypes of `Pointer<Void>`. For this reason the signature of `fromAddress` is:
```dart
T fromAddress<T extends Pointer>(int ptr);
```

`allocate` does not support allocating structs with malloc, as we do not have a way (yet) to know what the size of a struct is. Because of this `allocate` always returns a `Pointer`, not a subtype:
```dart
Pointer<T> allocate<T extends NativeType>({int count: 1});
```

With these signatures, `allocate` can be a factory, static method or top level function, while `fromAddress` can only be a static method or top level function (as the static return type can be a sub type of Pointer).

We might be able to support `allocate` of structs in the future, if we have a predefined way to calculate/define the size of structs.

For reference, the current boilerplate of structs:

```dart
@ffi.struct
class Coordinate extends ffi.Pointer<ffi.Void> {
  @ffi.Double()
  double x;

  @ffi.Double()
  double y;

  @ffi.Pointer()
  Coordinate next;

  // generated by @ffi.struct annotation
  external static int sizeOf();

  Coordinate offsetBy(int offsetInBytes) =>
      super.offsetBy(offsetInBytes).cast();

  Coordinate elementAt(int index) => offsetBy(sizeOf() * index);

  static Coordinate allocate({int count: 1}) =>
      ffi.allocate<ffi.Uint8>(count: count * sizeOf()).cast();

  /// Allocate a new [Coordinate] in C memory and populate its fields.
  factory Coordinate(double x, double y, Coordinate next) {
    Coordinate result = Coordinate.allocate()
      ..x = x
      ..y = y
      ..next = next;
    return result;
  }
}
```

Do we prefer a factory constructor for `allocate`?
Or do we want to keep `allocate` and `fromAddress` as similar as possible and change the signature of `allocate` to support allocating structs as well?
And if so, a top level function or a static method for both?

**Comment by sjindel-google** [comment]
* Subclassing pointer requires us to invent values (boxing) of a type without calling a constructor -- places strange restrictions on subclasses, which might be hard to apply completely
* Subclassing pointer is not as necessary if generalized typedefs are introduced
* If Pointers cannot be subclassed, we don't need to use a boxed representation for the pointer address
* However, it allows more ergonomic native signatures to be written, e.g.:

```dart
class Statement extends Pointer<Void> {
  // ...
}

Statement prepare(String query);
```

**Comment by dcharkes** [comment]
Quite often the Dart api does not coincide with Pointer-wrapper-classes

```dart
class Result extends IterableBase<Row> implements ClosableIterable<Row> {
  final StatementPointer _statement;
  // ...
```

https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/lib/src/database.dart#L122-L125

This would then have to be:

```dart
class StatementPointer {
  Pointer<Void> pointer;
}
```

**Comment by dcharkes** [comment]
No we will not allow subtyping, the API will be:

```dart
class Statement extends NativeType { }

Pointer<Statement> p;
```

**Comment by ds84182** [comment]
Will `class Foo extends Void {}` be allowed? Or is it limited to only non-zero-sized native types?

**Comment by sjindel-google** [comment]
I think we're planning to only allow extending `Struct` for now. However, structs can have size 0 if there are no fields.

**Comment by sjindel-google** [comment]
When this is implemented, we should ensure that the following code doesn't crash:

```dart
import 'dart:ffi';
import 'dart:async';

class DbOptionsPtr extends Pointer<Void> {}

main(args) async {
  DbOptionsPtr opts = fromAddress(0);
  await Isolate.spawn(print, opts);
}
```

**Comment by dcharkes** [comment]
@sjindel-google Any thoughts on what we do with `CString = Pointer<Uint8>`?

See our use of CString in the SQLite sample: [samples/ffi/sqlite/lib/src/bindings/signatures.dart](https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/lib/src/bindings/signatures.dart) and [samples/ffi/sqlite/lib/src/bindings/bindings.dart](https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/lib/src/bindings/bindings.dart).

Conceptually I would say:

```dart
CString = char* = Pointer<Uint8>.
```

With generalized typedefs and extension methods we could write these things as extension methods:

```dart
typedef CString = Pointer<Uint8>
extension CStringMethods on CString {
  // ..
}
```

You've proposed the following in [the CL disallowing subclassing Pointer](https://dart-review.googlesource.com/c/sdk/+/101291/8/tests/ffi/cstring.dart):

```dart
class CString extends Struct {}
Pointer<CString> = Pointer<Uint8>
```

This seems to equate `CString` to `char` instead of `char*`.

Alternatively we could require manual wrapping, but that does not enable us to write CString in function signatures.

```dart 
class CString {
  final Pointer<Uint8> chars;
}
```

**Comment by sjindel-google** [comment]
My feeling is that typedef/extension method is "obviously" the right solution.

What I proposed (intended to be a temporary workaround) is actually:

```
class CString extends Struct<CString> {
  Uint8 char;
}
Pointer<CString> = Pointer<Uint8>
```

**Comment by dcharkes** [comment]
I'm not an expert on the commonalities between inline C arrays and char pointers, but the sqlite3 api just mentions `char*`

If we want to keep the mental load of writing signatures and bindings low, we should maybe opt for `Pointer<Char>`, where we use a `class Char extends Struct`. The use sites would need to interact primarily through the Pointer instead of the ref:

```dart
Pointer<Char> myString;
myString.load<Char>().someMethod();
```

**Comment by sjindel-google** [comment]
If we add `.ref`, this would instead look like:

```Dart
Pointer<Utf8> myString;
myString.ref.toString();
```
