### ISSUE TITLE
Error on String.fromCharCode rune

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#35781]
Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Example:**
```
main(List<String> arguments) {
  String _xCustomerName = "ÐÝÞðýþ";
  String _xCustomerNameTurkish;

  _xCustomerName.runes.forEach((int rune) {
    var character = new String.fromCharCode(rune);
    switch (character) {
      case 'Ð':
        character = 'Ğ';
        break;
      case 'Ý':
        character = 'İ';
        break;
      case 'Þ':
        character = 'Ş';
        break;
      case 'ð':
        character = 'ğ';
        break;
      case 'ý':
        character = 'ı';
        break;
      case 'þ':
        character = 'ş';
        break;
    }
    _xCustomerNameTurkish = _xCustomerNameTurkish + character;
  });
  print(_xCustomerNameTurkish);

}
```

**Error:**

Unhandled exception:
NoSuchMethodError: The method '+' was called on null.
Receiver: null
Tried calling: +("Ğ")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      main.<anonymous closure> (file:///Users/niyazitoros/IdeaProjects/dart_string_example/bin/main.dart:31:51)
#2      Iterable.forEach (dart:core/iterable.dart:277:30)
#3      main (file:///Users/niyazitoros/IdeaProjects/dart_string_example/bin/main.dart:9:24)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by lrhn** [comment]
The `_xCustomerNameTurkish` variable is never initializer, so it starts out being `null`.
You then do `_xCustomerNameTurkish + character`, which calls the `+` method on `null`, giving you the error message you see.

Try initializing _xCUstmerNameTurksih` to an empty string.

**Comment by NTMS2017** [comment]
Thank you very much
