### ISSUE TITLE
Dart analyzer misses variable redeclaration within switch block

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/sdk#35786]
Running `Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"` and `dartanalyzer version 2.1.0`, analyzing the following block:

```
void main() {
  int value = 42;
  String choice = "any";
  switch (choice) {
    case "any":
      print(value);
      int value = 55;
      print(value);
      break;
    default:
      break;
  }
}
```
results in `No issues found!` even though the int `value` variable has been redeclared in the block.
When running the above code, it will rightfully terminate with a runtime exception:
```
> dart switch.dart
switch.dart:8:11: Error: Can't declare 'value' because it was already used in this scope.
      int value = 55;
          ^^^^^
switch.dart:7:13: Context: Previous use of 'value'.
      print(value);
            ^^^^^
```
Static analysis should be able to discover and mark this error appropriately.

**Comment by srawlins** [comment]
Analyzer now properly reports the errors.
