### ISSUE TITLE
Need to map absolute path of a library to package URI

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#35788]
See [issue in Flutter](https://github.com/flutter/flutter/issues/26615) we need to map the absolute library path returned from the kernel (widget transformer) to a library URI e.g.,
```
  package:flutter_gallery
  package:flutter
```
Currently, we can retrieve libraries on an isolate (VM Service) to fetch the list of libraries (no absolute paths but has the library URI) but we have no way of mapping absolute library names to the library URI.

This mapping of course exists inside the VM but I don't know if its exposed to us via an existing VM Service API or can it be exposed to us through a new VM Service call or added to the Library structure returned from libraries?

**Comment by terrylucas** [comment]
+jacob314

Looking at the transformer code - libraryUri is being used.  But I don't believe that is the usage that is causing the problem.

I think it might be this where location is from a NamedExpression
          'file', new StringLiteral(location.file.toString())));

Its being done on the location value of an InvocationExpression node

node.location

Does either location or node have libraryUri?

**Comment by jacob314** [comment]
Using the libraryUri from the library will work fine for us as long as the library does not have part files.
If there are part files, we want to generate the corresponding package: style uri to the specific part file instead.
I expect we'll be able to update our visitor to get this information without requiring any changes to kernel.

**Comment by jensjoha** [comment]
In e9e0daee5c9eb89b58ded0b8e087612f23b9a6fd the import uris are available for all sources in the kernel file. In 58882ffdd49afdfb53c7be15361340bb64760fe4 it is also read by the VM.

**Comment by jensjoha** [comment]
I suspect this issue can be closed?
