### ISSUE TITLE
Create analyzer-stable branch

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35806]
Retire the "analyzer-0.33" branch, and instead create a branch called "analyzer-stable" with the permissions the analyzer-0.33 branch used to have (push and code review access for the analyzer team IIRC).  And then point the analyzer branch builders (and the console page) to it. @stereotype441

**Comment by whesse** [comment]
This sounds OK to me, if you need stabilization on a different schedule and release policy than the SDK as a whole (which you do).
If it were a separate repo, then it would be just a master and stable branch on that repo, but the setup is not really more complicated with it in the SDK.
We just make the analyzer-stable branch, and the builders on it, and you stabilize on that branch and publish to pub.

**Comment by whesse** [comment]
If you don't use the "analyzer" branch anymore (it is now locked, with no new commits allowed), we could use that one.  That one already has mirroring set up so it appears on github as well.  If you don't want it to appear on github, it is just as easy to create the analyzer-stable branch on Gerrit, and give you (dart-team) the right permissions, and switch the builders to it.  Let me know which you prefer.

**Comment by stereotype441** [comment]
> If you don't use the "analyzer" branch anymore (it is now locked, with no new commits allowed), we could use that one. That one already has mirroring set up so it appears on github as well. If you don't want it to appear on github, it is just as easy to create the analyzer-stable branch on Gerrit, and give you (dart-team) the right permissions, and switch the builders to it. Let me know which you prefer.

I thought about that, but I was concerned that it would lead to confusion, since previously the "analyzer" branch was *ahead* of master, and the branch I want now is meant to be *behind* master.  So I'd rather we go ahead create the new analyzer-stable branch as discussed earlier.

I don't think there's any need to mirror the new branch to github.

**Comment by stereotype441** [comment]
Please base the branch on commit 3cb16d20e7810a2a378bb897d939f67c0b380d88, thanks!

**Comment by psycry** [comment]
Not sure if this is related to what I'm seeing but this does seem to coincide with me starting to have this issue this morning:

#35810 

beta branch but I've tried it on others, it may be something causing a plugin incompatibility with IntelliJ

**Comment by athomas** [comment]
The branch exists now:
https://dart.googlesource.com/sdk/+/refs/heads/analyzer-stable

@stereotype441 re-open if anything doesn't work.

@psycry This issue is unrelated to your issue.

**Comment by athomas** [comment]
Oh, missed the part about moving the builders over.

**Comment by whesse** [comment]
co19 fix worked.  I also approved the test results of this commit (accidentally), but this sounds like what you wanted, based on our discussion of auto-approval.  All the test failures are visible in the test results for commit 4626ec65cc787d77862fc4066a1f0dc26934569a

**Comment by stereotype441** [comment]
Are try bots expected to work on the branch?  I just tried running a CL through the try bots and got "Patch Failure" from most of the bots: https://dart-review.googlesource.com/c/sdk/+/91761

It's not a huge deal if this isn't expected to work; we can always just use the post-submit bots to verify that everything is ok.  But I wanted to make sure you were aware of it if it's expected to work :)

**Comment by stereotype441** [comment]
@whesse ping!  It would be nice to know if try bots are expected to work on this branch.

**Comment by athomas** [comment]
It obviously doesn't work right now but we don't know yet if it's just a configuration issue or something that just isn't supported, yet.

**Comment by stereotype441** [comment]
> It obviously doesn't work right now but we don't know yet if it's just a configuration issue or something that just isn't supported, yet.

Ok, thanks!

**Comment by athomas** [comment]
Closing, unlikely we will work on this in the near future.
