### ISSUE TITLE
pkg:analyzer - remove support for Dart scripts within an HTML page?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35813]
https://github.com/dart-lang/sdk/blob/118bdcc1f6ea228301b9e36fdaf976beb9600dc0/pkg/analyzer/lib/src/task/html.dart#L89-L93

I could see this making sense when Dartium was around, but now?

Will check w/ AngularDart folks.

Related to https://github.com/dart-lang/sdk/issues/35802

**Comment by bwilkerson** [comment]
Removing it is technically a breaking change, but I don't believe it will break anyone using the latest published version of analyzer because the task model is now disabled (except in a few of our internal tests, which we're working on cleaning up).

**Comment by kevmoo** [comment]
I checked with the angular source and throughout our docs – this is a VERY deprecated use case. We should stop wasting the cycles to support this.

The notion of having `<script type="application/dart">` in HTML is not supported anywhere on our platform.

**Comment by scheglov** [comment]
I believe I removing all this while removing the task model last year.
