### ISSUE TITLE
Unable to step into core libraries after calling setLibraryDebuggable()

### ISSUE THREAD

**Issue by john-reid-1000** [dart-lang/sdk#35820]
_Dart SDK Version (`dart --version`)_
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

I was attempting to step into the some of the dart provided libraries source code. Specifically `dart:collection`. Having found that these libraries needed to be set debuggable first, I have used vm_service_lib to set `dart:collections` as debuggable. 

However, with the following code,

```
import 'dart:collection';
import 'dart:developer';

main(List<String> arguments)
{
  debugger();
  var q = Queue<int>();
  q.add(22);
}
```

I attempted to step into the Queue constructor and add() member function. It does step into Queue, where as it would previously step over, but the source is apparently unavailable. 

![image](https://user-images.githubusercontent.com/43964867/52023744-a761ac00-24fe-11e9-8b64-fa89153141a2.png)

I see no way to path to the source code for `dart:collection` using `vm_service_lib`. I have tried `reloadSources()` but this doesn't help.

Is more required to enable source level debugging on core packages? or is this a bug?

This is the code I am using the enable debugging on that module.

```
import 'package:vm_service_lib/vm_service_lib.dart';
import 'package:vm_service_lib/vm_service_lib_io.dart';

void main() async
{
 VmService service = await vmServiceConnect("127.0.0.1",49341);
 VM vm = await service.getVM();
 Isolate isolate = await service.getIsolate(vm.isolates.first.id);
 
 for (var library in isolate.libraries)
 {
  if (library.name == "dart.collection")
  {
   service.setLibraryDebuggable(vm.isolates.first.id,library.id,true);
   break;
  }
 }
 await service.reloadSources(vm.isolates.first.id,force:true,pause:true);
 service.dispose();
}
```

**Comment by devoncarew** [comment]
@john-reid-1000, thanks for the comprehensive report! The vm currently does not return sources for `dart:` libraries. We do think we should restore that ability; the best place to track that work is likely https://github.com/dart-lang/sdk/issues/34832.

cc @bkonyi

**Comment by john-reid-1000** [comment]
That's great, thanks @devoncarew, is source stripping for dart: something I can disable if I build from source? 

This should should definitely be disabled by default in my opinion. Is there any reason that this cannot be enabled/disabled for each debug session? or are the dart:  libraries bundled into the vm binary or something?
