### ISSUE TITLE
False negative with dynamic types

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#35822]
With all strong mode flags enabled, some explicit `dynamic` usages are considered implicit and trigger errors.

A typical example is assigning to `List<dynamic>`:

```dart
List<dynamic> foo = [];
```

This code triggers a `strong_mode_implicit_dynamic_list_literal`, while we are explicitly using `dynamic` here.

This causes further issues when using functions:

```dart
void foo(List<dynamic> list) {}


foo([]); // strong_mode_implicit_dynamic_list_literal
foo(<dynamic>[]); // fine
```

**Comment by rrousselGit** [comment]
Another example where it causes conflict with linter rules:

```dart
dynamic loadYaml(String content) {}

final yaml = loadYaml(); // strong_mode_implicit_dynamic_variable
final dynamic yaml = loadYaml(); // omit_local_variable_types
```

**Comment by srawlins** [comment]
Can you explain the problem? It looks like you have enabled `implicit-dynamic: false` (or --no-implicit-dynamic` at the command line), which is intended to give you exactly these warnings.

**Comment by rrousselGit** [comment]
The issue is that there's no cast involved at all.
These examples are totally safe, as we're assigning `dynamic` to `dynamic`.

**Comment by rrousselGit** [comment]
I think the biggest issue lies in `List<dynamic>` vs `List`

```dart
List<dynamic> foo = [];
```

^ This should be fine because we're explicitly saying `dynamic` here. But it still triggers an error.

```dart
List foo = [];
```

^ This is not fine should stay unchanged.

**Comment by srawlins** [comment]
Certainly. The flag, `implicit-dynamic: false` is a flag which reports instances of implicit dynamic types, such as `List<dynamic> foo = /* implicit <dynamic> here */[];`.

I don't think you want to use this flag, but it is working as intended.

**Comment by jamesderlin** [comment]
This came up during a code review.  I wrote code:

    Map<String, dynamic> foo() => <String, dynamic>{ ... }

During readability review, @munificent told me to remove the explicit type on the RHS since it should be inferred.  However, the type is necessary to appease `implicit-dynamic: false`.  Bob explained:

> Ah, right. This is a limitation of the current no-implicit-dynamic behavior.
> 
> Inference *does* infer the type correctly, but because that inferred type contains dynamic no-implicit-dynamic yells at you. That's because it doesn't distinguish between "I didn't have a type to infer at all so I used dynamic" and "I did have a type to infer and that type was dynamic".
> 
> If you're using no-implicit-dynamic, then the current code is fine. In the future, we're hoping to have a smarter implicit dynamic flag that would not yell at inference like this.

**Comment by rrousselGit** [comment]
One temporary solution is to use `Object` instead.

The intent is different though

**Comment by jamesderlin** [comment]
Another example: Using [Flutter's `ImageStream.addListener`](https://docs.flutter.io/flutter/painting/ImageStream/addListener.html):

`imageStream.addListener(someCallback, onError: (e, st) {});`

triggers a `strong_mode_implicit_dynamic_parameter` error, presumably for the same reason mentioned in https://github.com/dart-lang/sdk/issues/35822#issuecomment-476409322. (`onError` is an [`ImageErrorListener`](https://docs.flutter.io/flutter/painting/ImageErrorListener.html) whose first argument is explicitly `dynamic`.)

**Comment by srawlins** [comment]
`implicit-dynamic: false` is now removed.
