### ISSUE TITLE
missing-type errors show up after less useful errors

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35828]
Take this code:

```dart
import 'dart:html' as html;

List<html.Element> l = <Element>[];
```

The analyzer reports two errors, consistently in this order:

* The list literal type 'List\<dynamic>' isn't of expected type 'List\<Element>'. The list's type can be changed with an explicit generic type argument or by changing the element types.
* The name 'Element' isn't a type so it can't be used as a type argument.

One can spend several minutes staring at the first error, trying to figure out why List\<dynamic> is involved at all, before seeing the second error.

Related to https://github.com/dart-lang/sdk/issues/23037, which highlights that "The name 'Element' isn't a type" is not as helpful as something like "The name 'Element' is undefined" or "unknown".

**Comment by srawlins** [comment]
Oof another bad case of this. Take this code, which is missing an import of the fixnum package:

```dart
int compareThings<T extends Comparable>(T a, T b) => a.compareTo(b);

void f(Int64 x, Int64 y) {
  compareThings(x, y);
}
```

The analyzer reports:

```
[error] Couldn't infer type parameter 'T'.

Tried to infer 'dynamic' for 'T' which doesn't work:
  Type parameter 'T' declared to extend 'Comparable<dynamic>'.
The type 'dynamic' was inferred from:
  Parameter 'left'  declared as     'T'
                    but argument is 'dynamic'.
  Parameter 'right' declared as     'T'
                    but argument is 'dynamic'.

Consider passing explicit type argument(s) to the generic.

[error] Undefined name 'Int64'.
[error] Undefined name 'Int64'.
```

I'm all for longer error messages with careful explanation, but `Undefined name 'Int64'` should appear first!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/302680
