### ISSUE TITLE
analysis_options "include" directive does not parse package: URIs when in parent of pubspec

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35831]
The easiest way to see this is probably just to

1. clone the protobuf repo:

   ```
   $ git clone git@github.com:dart-lang/protobuf.git
   $ cd protobuf
   ```

2. There is an analysis_options.yaml here. If you add the following line:

   ```yaml
   include: package:pedantic/analysis_options.yaml
   ```

   and then `cd protoc_compiler`, and add the following to pubspec.yaml's `dev_dependencies`:

   ```yaml
     pedantic: '1.4.0'
   ```

   and then `pub get`, you are setup.

3. Then if you run `dartanalyzer lib`, you'd expect to see a `prefer_is_empty` lint report in `lib/message_generator.dart`, for the line `fullName.substring(package.length == 0 ? 0 : package.length + 1);`. But not so!

4. To see that, indeed, there is a `prefer_is_empty` lint report, just `cp ../analysis_options.yaml .`, then again `dartanalyzer lib`. A ha!

   ```none
   Analyzing lib...
     lint • Use isEmpty instead of length at lib/message_generator.dart:67:26 • prefer_is_empty                                                  
     lint • Use isNotEmpty instead of length at lib/message_generator.dart:303:13 • prefer_is_empty                                              
     lint • Use isNotEmpty instead of length at lib/message_generator.dart:378:9 • prefer_is_empty                                               
     lint • Use isEmpty instead of length at lib/options.dart:41:7 • prefer_is_empty
   ```

**Comment by bwilkerson** [comment]
@danrubel Is this a bug, or was this by design?

**Comment by danrubel** [comment]
I must have assumed that the pubspec and the analysis options are in the same directory because it is not by design.

**Comment by srawlins** [comment]
Phew, glad it's a bug! I was trying to add the functionality to the protobuf repo; other multi-package repos like this include [built_value](https://github.com/google/built_value.dart), [angular](https://github.com/dart-lang/angular), and [build](https://github.com/dart-lang/build), all of which have top-level (above package) `analysis_options.yaml` files; so they cannot use the `include` feature.

**Comment by srawlins** [comment]
I think https://github.com/dart-lang/sdk/issues/42910 is a duplicate of this, but more discussion over there.
