### ISSUE TITLE
analyzer InterfaceManager.getMembersInheritedFrom* is deprecated but has no replacement

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#35833]
Checked with analyzer v0.35.0 and verified with @scheglov -- filing bug per his request.

Dartdoc uses this here:
https://github.com/dart-lang/dartdoc/blob/85b3166e1b88a6266e8935495373e07941eefeda/lib/src/model.dart#L1046

and here:
https://github.com/dart-lang/dartdoc/blob/85b3166e1b88a6266e8935495373e07941eefeda/lib/src/model.dart#L1048

**Comment by kevmoo** [comment]
Also in `json_serializable`!!!

https://github.com/dart-lang/json_serializable/blob/7e368ebd5909be193ca985c0bd4b81069a5436b8/json_serializable/lib/src/field_helpers.dart#L83-L85

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/91847 helps in migrating `json_serializable`.

For DartDoc, `InheritanceManager2.getInheritedMap()` is a close, but not full, replacement. It returns `FunctionType`s, not `ExecutableMember`s. And the corresponding `FunctionType.element` is the base element, not a member.

@bwilkerson FYI

**Comment by kevmoo** [comment]
Not a huge fan of the `InheritanceManager2` name. Could we just call it `InheritanceManager` and use aliased imports or something?

**Comment by scheglov** [comment]
We re-introduced using `ExecutableElement`(s) in `InheritanceManager3`, and migrated DartDoc to it.
