### ISSUE TITLE
Analyzer should define runtime environment variables when evaluating constants.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#35847]
With the code snippet:

```dart
class A {
  // Make sure that debug strings are set to null in release builds.
  const A(this.debugString) : assert(!releaseMode || debugString == null);

  final String debugString;

  static const bool releaseMode = bool.fromEnvironment('dart.vm.product');
  
  static const A anA = A(releaseMode ? null : "Debug String");
}
```

The definition of "anA" is flagged with an analyzer error:

```
  error • Evaluation of this constant expression throws an exception • const_eval_throws_exception
```

Probably because `bool.fromEnvironment('dart.vm.product')` returns `null` when the analyzer evaluates it (I haven't verified this).

The analyzer should probably define runtime variables in the same way as the compiler/VM would, probably pretending to be in a predictable mode. When running in the analyzer, `bool.fromEnvironment('dart.vm.product')` should probably return `false`, or at least it should return something other than `null`.

There are probably also other environment variables that should be set to provide a "normal" environment for the analyzer to run in.

In this case, I'm prevented from writing a useful assert because the analyzer flags it as a result of its abnormal environment.

**Comment by gspencergoog** [comment]
Actually supplying `bool.fromEnvironment('dart.vm.product', defaultValue: false)` seems to fix the issue, so maybe that's a fine workaround.  I'm now wondering why that fixes it, since `defaultValue` is defined to have a default value of `false` to begin with.

**Comment by srawlins** [comment]
The analyzer no longer reports an error with this code.
