### ISSUE TITLE
getting short data is work perfect, but I got error when I get a long data...

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#35858]
getting shot data is work perfect, but I got error when I get a long data...

Future Starts Here
**Request:** Q110:_:111111:_:222222:_:20180801:_:20190130
Request has data
Socket sends data to database
Socket start to listen to database
**(1) 152:_:12**:_:10:_:10:_:02.08.2018:_:I….. **_continue but data is not complete. The header 152:_:12 means data has 152 rows with 12 columns_**
Socket start to listen to database
(1) 950:_:B:_:396.86:_:20180811870:_…… **_data comes complete, but no header its continue from above_**
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      _handle.<anonymous closure> (file:///Users/niyazitoros/IdeaProjects/capital_console/bin/main.dart:30:18)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#6      _StreamController._add (dart:async/stream_controller.dart:639:7)

_Originally posted by @NTMS2017 in https://github.com/dart-lang/sdk/issues/35832#issuecomment-460521465_

**Comment by vsmenon** [comment]
Let's keep this on the old issue (#35832).

This one is confusing without any context.
