### ISSUE TITLE
Ensure library URIs are also obfuscated in AOT

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35852]
It appears like we keep library URIs alive in --obfuscate mode. The kernel loader just creates the Library objects from the normal URI (see [kernel_loader.cc](https://github.com/dart-lang/sdk/blob/master/runtime/vm/kernel_loader.cc#L2036)).

We can consider also obfuscating the library URIs.

**Comment by mkustermann** [comment]
@sjindel-google Could you look into this? It will help reduce AOT size as well as allows g3 apps to ship in fully obfuscated mode.

**Comment by mraleph** [comment]
There is actually a separate pass in the `Precompiler::Obfuscate` that should collect all scripts and libraries and obfuscate their names and urls. 

If I do this:

```
$ pkg/vm/tool/precompiler2 --strip /tmp/hello.dart /tmp/snap.aot
$ strings /tmp/snap.aot | grep hello.dart
file:///tmp/hello.dart
$ pkg/vm/tool/precompiler2 --obfuscate --strip /tmp/hello.dart /tmp/snap.aot
$ strings /tmp/snap.aot | grep hello.dart
```

I don't see `/tmp/hello.dart` in the output.
