### ISSUE TITLE
dart:ffi Void size one byte or unknown

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35879]
Should `Void` have a size of 1 byte, or an unknown size.

Defining a size would allow the following

```dart
Pointer<Void> p = allocate(count: 20);
Pointer<Void> p2 = p.elementAt(10);
sizeOf<Void>(); // returns 1
```

Keeping `Void` opaque, not knowing its size would disallow allocate and sizeOf:

```dart
Pointer<Void> p = allocate<Int8>(count: 20).cast();
Pointer<Void> p2 = p.offsetBy(10);
sizeOf<Void>(); // throws exception
```

cc @sjindel-google

**Comment by sjindel-google** [comment]
We can allow pointer arithmetic on a `Pointer<Void>` without necessarily allowing `allocate` and `sizeOf`.

**Comment by dcharkes** [comment]
We already allow `offsetBy` on `Pointer<Void>`.

**Comment by sjindel-google** [comment]
Right, I'm just saying that we could allow `elementAt` as well.

**Comment by sjindel-google** [comment]
We will need this if we remove `offsetBy`.

**Comment by dcharkes** [comment]
It is not C or C++ semantics, it's a non standard extension in GNU C.

> ### 6.24 Arithmetic on void- and Function-Pointers
> In GNU C, addition and subtraction operations are supported on pointers to void and on pointers to functions. This is done by treating the size of a void or of a function as 1.
> 
> A consequence of this is that sizeof is also allowed on void and on function types, and returns 1.
>
> The option -Wpointer-arith requests a warning if these extensions are used.

https://gcc.gnu.org/onlinedocs/gcc/Pointer-Arith.html

I prefer keeping things consistent with regard to being sized or not.

Sized:

* Int8, ..., Double, Float
* Pointer
* subtypes of Struct

Not sized:

* NativeType
* NativeInt
* NativeDouble
* NativeFunction
* Void
* Struct

Everything that is sized can be used in `allocate`, `sizeOf`, `elementAt`, `load`, and `store`.

Note that in our implementation before https://github.com/dart-lang/sdk/issues/37254 we require `load` and `store` to be statically typed as a sized thing, while we fail `sizeOf`, `elementAt`, and `allocate` dynamically. We do the latter so that you can write generic code. After landing https://github.com/dart-lang/sdk/issues/37254 all of these will be dynamic.

If we use extension methods we could even try using `NativeSized` in the hierarchy, and only define these 5 operations on those. This would almost work: you could still try to call them on `Struct` and `NativeSized` even though these are not sized themselves.

**Comment by sjindel-google** [comment]
:+1:
