### ISSUE TITLE
fast iteration on status-free workflow

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35873]
When iterating locally on a feature, it is very useful to run a single test repeatedly (e.g. when debugging or making changes to a compiler).

Could we have a way to iterate on a single test and have accurate results that reflect the current results in the status-free system?

-----
Context:

In the old workflow, we normally would use a selector to run a few tests or a single test. For example:
```
./tools/test.py -m release -c dart2js -r d8 language_2/set_literals/invalid_set_literal_test/29
```

This has the unfortunate effect that the test fails whenever `.status` files inaccurately apply to dart2js. For example, the test above produces a compile-time error, but it is incorrectly labeled as "MissingCompileTimeError" under `$fasta` section in `language_2_kernel.status`.

This issue may go away when everyone moves to the new workflow, but it can be very confusing to work with at this time, and because we don't maintain status files anymore, this seems unavoidable.

The new workflow suggest that we run tests like:
```
./tools/test.dart -b name-of-our-bot
```

This however runs all tests run by that bot. 

Could we make `test.dart` accept a selector? For example:
```
./tools/test.dart -b name-of-our-bot language_2/set_literals/invalid_set_literal_test/...
```

/cc @fishythefish

**Comment by sortie** [comment]
Thanks for the feedback. We heard this from a few sources and I have a CL in review that fixes the problem (<https://dart-review.googlesource.com/c/sdk/+/92780>) -- I believe that should meet your needs.

**Comment by sortie** [comment]
Hi. I've implemented what you need now. See --help of test.dart for how it works. Any additional parameters following -- are forwarded to test.py.

**Comment by sortie** [comment]
@askeksa-google You also asked about this feature, it's now done.

**Comment by sigmundch** [comment]
thank you!
