### ISSUE TITLE
A process with mode `detachedWithStdio` has a null getter for `exitCode`.

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#35874]
This applications throws when it shouldn't:

```dart
import 'dart:io';

void main() async {
  var process =
      await Process.start('ls', [], mode: ProcessStartMode.detachedWithStdio);
  process.exitCode.then((_) {});
}

```

**Comment by bkonyi** [comment]
Started looking into this and it appears that this is working as intended based on [the documentation](https://api.dartlang.org/stable/2.2.0/dart-io/Process/start.html).

In particular:

> If mode is ProcessStartMode.detachedWithStdio a detached process will be created where the stdin, stdout and stderr are connected. The creator can communicate with the child through these. The detached process will keep running even if these communication channels are closed. The process' exit code will not become available when it terminated.

`ProcessStartMode.detached` behaves similarly. Exit codes are only available when using `ProcessStartMode.normal`.

**Comment by grouma** [comment]
Interesting that this behavior is documented. Is this due to a technical limitation? I can't fathom why this would be the preferred behavior.

**Comment by iinozemtsev** [comment]
Just learned this in a hard (~2 hours searing for an error in my code then reading through process_patch.dart) way.

While this is nice to have a doc in Process.start, it would be also helpful to mention this fact in `exitCode` getter

**Comment by vanlooverenkoen** [comment]
Is there any way to know if the command failed or succeeded?
