### ISSUE TITLE
Another dart2js compiler crash

### ISSUE THREAD

**Issue by generic13** [dart-lang/sdk#35875]
The following code crashes dart2js:

class A {
  int a;
  A( int a ){ (this).a = a; }
}

I understand that "(this)" might be an illegal dart syntax (I am compiling generated code that produced it) and reporting it to help fix compiler crashes.
Here is the output of the dart2js:
================
test.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.2.0-dev.0.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///usr2/jdev/devel.3.8.dart/test_comp/test.dart,
at character offset 21:
test.dart:2:22: Internal problem: Unsupported operation: 'ThisExpression'.
  A( int a ){ (this).a = a; }
                     ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:43:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:70:10)
#2      PropertyAccessGenerator.make (package:front_end/src/fasta/kernel/expression_generator.dart:303:14)
#3      Generator.buildPropertyAccess (package:front_end/src/fasta/kernel/expression_generator.dart:213:38)
#4      IncompletePropertyAccessGenerator.withReceiver (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/front_end/lib/src/fasta/kernel/kernel_expression_generator_impl.dart:361:23)
#5      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:1336:17)
#6      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:1254:14)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3756:22)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3685:13)
#9      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3650:13)
#10     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5012:16)
#11     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:4972:12)
#12     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3554:14)
#13     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3473:20)
#14     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3378:15)
#15     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:826:14)
#16     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:578:5)
#17     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3036:14)
#18     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2899:15)
#19     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2704:15)
#20     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1714:13)
#21     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1674:14)
#22     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:569:14)
#23     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:461:14)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:340:15)
#25     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#26     Loader.buildBodies (package:front_end/src/fasta/loader.dart:182:15)
<asynchronous suspension>
#27     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#28     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#29     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#30     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:145:38)
<asynchronous suspension>
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#32     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#33     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:140:32)
<asynchronous suspension>
#34     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#35     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#36     new Future.sync (dart:async/future.dart:224:31)
#37     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#43     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#44     compile (package:front_end/src/api_unstable/dart2js.dart:138:46)
<asynchronous suspension>
#45     LibraryLoaderTask.loadLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:74:27)
<asynchronous suspension>
#46     CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#47     LibraryLoaderTask.loadLibraries (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:56:12)
#48     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:277:61)
<asynchronous suspension>
#49     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:38)
#50     new Future.sync (dart:async/future.dart:224:31)
#51     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:20)
#52     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#53     Compiler.run (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:217:41)
#54     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:89:22)
#55     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#60     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:834:7)
#1      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:578:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3036:14)
#3      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2899:15)
#4      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2704:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1714:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1674:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:569:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:461:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:340:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:182:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#15     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:145:38)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#17     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#18     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:140:32)
<asynchronous suspension>
#19     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#20     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#29     compile (package:front_end/src/api_unstable/dart2js.dart:138:46)
<asynchronous suspension>
#30     LibraryLoaderTask.loadLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:74:27)
<asynchronous suspension>
#31     CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#32     LibraryLoaderTask.loadLibraries (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:56:12)
#33     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:277:61)
<asynchronous suspension>
#34     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:38)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:20)
#37     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#38     Compiler.run (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:217:41)
#39     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:89:22)
#40     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#45     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by peter-ahe-google** [comment]
Thanks for the bug report, @generic13 . I think this is legal syntax. Regardless, the compiler shouldn't crash.

**Comment by generic13** [comment]
If it's a legal syntax, it would be great (would make it easier to use code generation). Thank you!

**Comment by generic13** [comment]
Just checking if it was fixed. I downloaded the latest dev build (dart_2.1.1-dev.3.2-1_amd64.deb) and it still crashes after the following message:

Message.dart:306:14: Internal problem: Unsupported operation: 'ThisExpression'.
      (this).op = op;

It would be great if the fix is made available in the dev download.
Thank you!

**Comment by peter-ahe-google** [comment]
As far as I know, dart_2.1.1-dev.3.2 was cut before my fix landed. But it looks like my fix will be included in the next dev release.

**Comment by generic13** [comment]
Great, thank you!
