### ISSUE TITLE
implicit_this_reference_in_initializer false positive ? 

### ISSUE THREAD

**Issue by jaumard** [dart-lang/sdk#35878]
I have the following case: 

```
class Whatever  {
  final _analytics = KiWiAnalytics();
  final _observer = Lazy<FirebaseAnalyticsObserver>(() {
    return _analytics.observer;
  });
}
```
And I'm getting this error: `error: Only static members can be accessed in initializers. (implicit_this_reference_in_initializer)` 
For me it should be an error as I'm not in an initializer anymore, but under a callback.

Env:
`Dart VM version: 2.1.1-dev.0.1.flutter-ec86471ccc (Thu Jan 3 22:43:43 2019 +0000) on "macos_x64"`

**Comment by vsmenon** [comment]
This is working as intended.  The right hand side of an initializer cannot refer implicitly to `this`.  E.g., in your example, there is no guarantee that the callback is not executed before `_analytics` is initialized.  

Something like this (moving the initialization to a constructor with order explicit) should work:

```
class Whatever  {
  final _analytics; 
  final _observer; 

  Whatever() : this._(KiWiAnalytics());
  Whatever._(this._analytics) : _observer = _analytics.observer;
}
```
