### ISSUE TITLE
[vm/ffi] DynamicLibrary extends Struct

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35881]
`DynamicLibarary` is currently completely separate from `Pointer`. This prevents us to pass a handle to a dynamic library to C++ from Dart, and it introduces some code duplication in the VM.

We can make `DynamicLibrary extends Pointer<Void>`.

It would be best if this would be a non-indexable and non-storeable pointer: https://github.com/dart-lang/sdk/issues/35841

**Comment by dcharkes** [comment]
If there is a good reason for not merging the two, then we should expose `DynamicLibrary.handle` to enable users passing library handles to C functions.

**Comment by dcharkes** [comment]
If we don't allow subclassing Pointer, we cannot make DynamicLibrary a subclass (https://github.com/dart-lang/sdk/issues/35782).

Converting issue to providing `.handle`.

**Comment by dcharkes** [comment]
@sjindel-google we should then maybe also support the reverse, a `fromHandle(Pointer<Void> handle)` constructor?

**Comment by sjindel-google** [comment]
I think so. Perhaps we should make `DynamicLibrary` a struct and go with `Pointer<DynamicLibrary>` in the new structs API?

**Comment by dcharkes** [comment]
We should do that. Then we do not have to implement `DynamicLibrary.handle` and `DynamicLibrary.fromHandle(h)` as special cases.

Moreover, if someone would ever be passing dynamic library handles through ffi function calls or callbacks, the arguments would be typed as `Pointer<DynamicLibrary>` rather than `Pointer<Void>`.

**Comment by sjindel-google** [comment]
We are incorrectly using `dlopen`/`dlsym` directly instead of the embedder callbacks, which violates the embedder abstraction. Once we switch to using embedder callbacks, the underlying pointer behind a dynamic library will be embedder-defined and not useful to Dart code.
