### ISSUE TITLE
"Abort trap: 6" instead of NoSuchMethodError (null access)

### ISSUE THREAD

**Issue by gothamgasworks** [dart-lang/sdk#35887]
* Dart SDK Version: `Dart VM version: 2.1.1-dev.3.2 (Thu Jan 24 11:50:07 2019 +0100) on "macos_x64"`

When I run the following code:

```dart
class Value {
  const Value(this.val);

  final int val;
}

const int limit = 50000;

Value maybeWrap(int i) => i < limit ? new Value(i) : null;

void main() async {
  for (int i = 0; i < 65536; ++i) {
    if (maybeWrap(i).val == -1) {
      // never mind we just do something with it
      print(i);
    }
  }
}
```

Expected output:
```
Unhandled exception:
NoSuchMethodError: The getter 'val' was called on null.
... etc ...
```

Actual output:
```
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

I get the expected output if I decrease the value of `limit` to 5000, so I'm guessing this is a JIT bug.

**Comment by mraleph** [comment]
@mkustermann @sjindel-google  Martin or Samir could you take a look at this? My suspicion would be that something is wrong with lazy deoptimization which occurs on the slow-path that uses shared stubs.

**Comment by sjindel-google** [comment]
The issue is that `CheckNull` (which was originally created for AOT) doesn't work in JIT because it doesn't create an deoptimization info. This example is easy to fix in the call specializer, but unfortunately we have other uses of `CheckNull` in JIT-mode which require more work to fix.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/92783
