### ISSUE TITLE
dart:ffi remove Pointer.offsetBy

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35883]
C++ uses the size of the type when doing pointer arithmetic, we support this with `Pointer.elementAt()`. It only works for `Pointer<T>` where `T` has a size. This is the preferred way of using an array of elements. 

`Pointer.offsetBy()` enables taking arbitrary offsets (in bytes) on any Pointer. This is not the preferred way, possibly we can leave it out completely.

**Comment by sjindel-google** [comment]
We will remove it.

**Comment by dcharkes** [comment]
We'll change `offsetBy` to `_offsetBy` after the Structs API revamp has landed (it's references in the frontend, so it will conflict when changed).

**Comment by sjindel-google** [comment]
What was the reasoning to remove it?

**Comment by dcharkes** [comment]
I think the reasoning was that using `offsetBy` is error-prone (creating unaligned pointers). If people wanted to do that, they should explicitly convert to `Pointer<Uint8>` with casting, do the pointer arithmetic, and cast back to the original pointer.

We could even provide that in `package:ffi` as an add on (which users would import manually):

```dart
extension PointerArithmetic<T extends NativeType> on Pointer<T> {
  Pointer<T> offsetBy(int numBytes) => cast<Uint8>().elementAt(numBytes).cast();
}
```

**Comment by dcharkes** [comment]
We'll remove it for now.
