### ISSUE TITLE
publish a new `package:analyzer` (w/ set literals enabled)

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35905]
As discussed on Friday, the `linter` would benefit from a new package that enables set-literals.

Thanks!

/cc @stereotype441 

/fyi @jcollins-g

**Comment by pq** [comment]
_gentle nudge_

@stereotype441: any time-line on this?

**Comment by stereotype441** [comment]
> _gentle nudge_
> 
> @stereotype441: any time-line on this?

Sorry for the delay!  I've just published analyzer 0.35.1, with set literals support enabled.

**Comment by pq** [comment]
Thanks a million!
