### ISSUE TITLE
Proposal: allow passing constructors as functions

### ISSUE THREAD

**Issue by rhcarvalho** [dart-lang/sdk#35901]
This feature request intends to allow using constructors where functions with the same type/signature are expected.

Example code: https://dartpad.dartlang.org/9745b0f73157959a1c82a66ddf8fdba4

---

## Background

As of Dart 2, [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-new) suggests not using the `new` keyword and removing it from existing code. 
Doing that makes named constructors and static methods look the same at call sites.

The [Language Tour](https://www.dartlang.org/guides/language/language-tour#constructors) says (emphasis mine):
> ### Constructors
> Declare a constructor by **creating a function** with the same name as its class [...]

Thus suggesting that a constructor is a function. But it turns out it is not really a function, as it cannot be used in all contexts where a function can.

## Why it would be useful

Dart built in types, in particular collection types, have several methods that take functions as arguments, for instance `.forEach` and `.map`, two concise and expressive ways to perform computations.

In an program I'm working on, I got a bit surprised by not being able to create new instances using `Iterable.map` + a named constructor. And then I realized that [others have arrived at the same conclusion at least 4 years back on StackOverflow](https://stackoverflow.com/questions/25980799/is-there-a-reason-to-use-constructors-over-static-methods-future-delayed-date/25980875#25980875), but I could not find a matching issue.

### Example Flutter code

What I would like to write:

```dart
  return Column(
    // This won't compile:
    children: ['Alice', 'Bob', 'Charlie'].map(Text).toList(),
  );
```

What I have to write instead with Dart 2.1.0:

```dart
  return Column(
    // Need a dummy wrapper around the constructor:
    children: ['Alice', 'Bob', 'Charlie'].map((name) => Text(name)).toList(),
  );
```

Note that the feature request is not specific to Flutter code, but applies to any Dart code as per the more generic example in https://dartpad.dartlang.org/9745b0f73157959a1c82a66ddf8fdba4.

---

* Dart SDK Version (`dart --version`)

```
Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/language#216
