### ISSUE TITLE
dart:ffi interaction with dynamic

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35902]
While not efficient, `dart:ffi` should be available with `dynamic` (except for trampolines).

```dart
Pointer<Int8> p = allocate();
dynamic q = p;
q.store(123);
q.free();
```

TODO: test whether it works and write tests for this functionality.

**Comment by sjindel-google** [comment]
We will lock out these methods on `dynamic` for now so that switching to extension methods will be a non-breaking change (against the runtime behaviour).

**Comment by sjindel-google** [comment]
This task is mentioned in code which checks that type arguments to `load` and `store` are statically known, which is a separate additional issue.

**Comment by sjindel-google** [comment]
Another thing to check is that the trampolines and other ops that work on Pointers but aren't instance methods still work when the Pointer class is implemented (instead of extended).

**Comment by sjindel-google** [comment]
@mraleph @dcharkes 
This could be another substantial task to work on next: it requires re-writing the dynamic invocation forwarders in the VM.

**Comment by sjindel-google** [comment]
Not sure what the exact scope of this issue is, but we need to also disallow dynamic invocations of `asFunction` and `lookupFunction`.

**Comment by dcharkes** [comment]
> Not sure what the exact scope of this issue is, but we need to also disallow dynamic invocations of `asFunction` and `lookupFunction`.

That would be trivial with extension methods.

If we ship before extension methods land, we need to prohibit this. However, this is work that we would be obsolete once we switch to extension methods, so I'd give this low priority.

**Comment by sjindel-google** [comment]
We can give it low priority as long as the dynamic invocations don't make the VM crash.

**Comment by sjindel-google** [comment]
@dcharkes Assigning myself since you asked me to remove dynamic invocations of `Pointer.load` and `Pointer.store` altogether in https://dart-review.googlesource.com/c/sdk/+/107513

**Comment by dcharkes** [comment]
This is part of [the CL](https://dart-review.googlesource.com/c/sdk/+/117547) that addresses Pointer optimizations (https://github.com/dart-lang/sdk/issues/38172), and is currently in review.

**Comment by mkustermann** [comment]
We already track extension methods in https://github.com/dart-lang/sdk/issues/37773 and do not plan support for dynamic load/store atm, right? So can we close this issue?

**Comment by sjindel-google** [comment]
Yes, this issue is obsolete.

**Comment by dcharkes** [comment]
The CL that rules out invocations on dynamic hasn't landed yet. It should land today.
