### ISSUE TITLE
False positives for INVALID_OVERRIDE_DIFFERENT_DEFAULT_VALUES_NAMED with generics and different files

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35908]
Given two source files:

`/test/lib/other.dart`:
```dart
class C {
  f({x: const ['x']}) {}
}
```
`/test/lib/test.dart`:
```dart
import 'other.dart';
class D extends C {
  f({x: const ['x']}) {}
}
```

The analyzer erroneously reports the error `INVALID_OVERRIDE_DIFFERENT_DEFAULT_VALUES_NAMED`.

I believe what's happening is that the summary for `/test/lib/other.dart` fails to record the inferred type of the list, so when we compute errors for `/test/lib/test.dart`, we are comparing the constant `<dynamic>['x']` with the constant `<String>['x']`.

**Comment by stereotype441** [comment]
P1 because this created problems in the internal SDK roll that forced `INVALID_OVERRIDE_DIFFERENT_DEFAULT_VALUES_NAMED` to be disabled.

**Comment by stereotype441** [comment]
The workaround should tide us over until we can re-vamp the way constants are represented in summaries.  Dropping priority to P2.

**Comment by stereotype441** [comment]
Note: the workaround in 7ebd02cdaa98747fa17e56170b2a6e7ed766f109 had a problem: it could result in a null reference exception in the event that the default value couldn't be evaluated.  Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/94021

**Comment by srawlins** [comment]
I think this was fixed around when @scheglov implemented summary2.
