### ISSUE TITLE
tune "convert to set literal" assist to avoid producing code w/ type errors

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35907]
In the world of set-literals, an assist is presented on this snippet.

```dart
Set<String> s = new HashSet<String>();
```

If you perform it, and get:

```dart
Set<String> s = <String>{};
```

which provokes the following error:

```
error: The set literal type 'Set<String>' isn't of expected type 'HashSet<String>'. The set's type can be changed with an explicit generic type argument or by changing the element types. (strong_mode_invalid_cast_literal_set at ...)
```

As discussed in https://github.com/dart-lang/linter/issues/1425#issuecomment-462214416, we should consider not providing the assist if it would produce errored results.

/cc @bwilkerson

**Comment by leafpetersen** [comment]
I don't think that's the example you mean - that fix should not cause an error. Perhaps you mean that the original code was:

```dart
 HashSet<String> s = new HashSet<String>();
 ```

?

**Comment by bwilkerson** [comment]
I just confirmed that `Set<String> s = <String>{};` does not produce any error, while `HashSet<String> s = <String>{};` does produce an error.

However, as far as I can tell, the assist is _only_ offered if the explicitly created type is `Set`, not when it is either `HashSet` or `LinkedHashSet`.

**Comment by pq** [comment]
@leafpetersen: you're spot on.  Sorry for the confusion.  I've been juggling a lot of cases and got this one mixed up.

> However, as far as I can tell, the assist is _only_ offered if the explicitly created type is `Set`, not when it is either `HashSet` or `LinkedHashSet`.

And it looks doubly so.  You're right @bwilkerson.  The assist does the right thing.

Closing this out.  Feel free to re-open if there's anything of value here.

Thanks!
