### ISSUE TITLE
dart:ffi asFunction / lookupFunction static function vs instance method

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35903]
Currently `Pointer.asFunction` and `DynamicLibrary.lookup` are instance methods.
However, this enables users to call these dynamically.

```dart
Pointer<Int8 Function(Int8)> p = fromAddress(memoryAddress);
dynamic q = p;
int Function(int) f = q.asFunction();
f(123);
```

Unfortunately we cannot at compile-time discover this, which means that we cannot generate trampolines in AOT mode.

We have two possible solutions:

1. throw a runtime exception on a dynamic invocation
2. make these functions static: `f = asFunction(q)`

The second option is a bit less ergonomic, but safer.

**Comment by dcharkes** [comment]
@lrhn @mraleph

**Comment by lrhn** [comment]
Let it crash? Or throw in `asFunction` if the function is not available?

If this was done using [static extension types](https://github.com/dart-lang/language/issues/42) instead then dynamic invocation would not work. Much of the ffi functionality is compiler magic that works similar to this, so I'd not be worried if it just doesn't work when used through dynamic. It's already so very magical.

The trampoline you create, is it for a particular function, or can it be reused for multiple functions with the same type, just with different native addresses? If it was the latter, you could create it when you see `Pointer<Int8 Function(Int8)>`.

**Comment by sjindel-google** [comment]
We will keep using instance methods for now and use extension methods once available, to ease migration. (Throwing an exception on a dynamic call).

**Comment by dcharkes** [comment]
This should be addressed now that we have extension methods.
