### ISSUE TITLE
package:build workspaces don't pick up inner contexts

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#35911]
This issue is somewhat complicated and affects the maintainers of the flutter website repo, reported by @filiph 

Their code generator relies on this package

https://github.com/chalin/code_excerpt_updater

which generates an `example.g` directory with its own `.packages` file within the project

and also runs package:build

which causes it to fill the `.dart_tool/build` directory with what appears to be (and is) valid build output

which causes analyzer to treat the `flutter_packages` repo as a `package:build` workspace

which seems to break context nesting

so that code within `example.g` is analyzer against `./.packages` instead of `examples.g/.packages`

The easiest solution here is to update the script for the flutter documentation command to clear `.dart_tool/build` but that may hurt their build times and doesn't solve the immediate problem. Estimation: easy

The correct solution (probably?) is to fix inner context discovery. I did some investigation and didn't see a clear link between the package:build worksppace and `context_locator`. Still, likely isn't a tremendous amount of work. Maybe a day or two.

**Comment by MichaelRFairhurst** [comment]
Quick question for @jakemac53 @natebosch 

We're categorizing this as a package:build directory because it gets a build output directory (`.dart_tool/build/`). Is there a better way to check if a project relies on package:build generated file resolution that wouldn't confuse `pub run` kicking off a build with the project itself relying on generated file resolution?

**Comment by jakemac53** [comment]
Knowing nothing about the analyzer - it sounds like the analyzer is looking in parent directories for a `.dart_tool/build` directory (similar to what it would do for a `.packages` file?). If that is the case, and it does that check before it checks for _any_ `.packages` files, then it would see the parent `.dart_tool/build` directory before it saw the `.packages` file in the current directory and then that might win? I am not sure the best resolution to that, but essentially it should choose the "closest" context it can find, in this case that means local `.packages` file (under `example.g`) should win over the parents `.dart_tool/build` directory.

> We're categorizing this as a package:build directory because it gets a build output directory (`.dart_tool/build/`)

That is pretty sane, you could also check for `build_runner` in dev dependencies which would work even before a build has been ran and would be better.

> Is there a better way to check if a project relies on package:build generated file resolution that wouldn't confuse `pub run` kicking off a build with the project itself relying on generated file resolution?

I don't quite understand what you are asking here, `pub run` doesn't kick off builds (unless the executable being ran does a build).

**Comment by natebosch** [comment]
> you could also check for `build_runner` in dev dependencies which would work even before a build has been ran and would be better.

This will stop being true once the flutter tool can perform builds.

> but essentially it should choose the "closest" context it can find

+1

I think we need to look for package-root indicators a level at a time instead of an indicator at a time.

**Comment by MichaelRFairhurst** [comment]
> I don't quite understand what you are asking here, `pub run` doesn't kick off builds (unless the executable being ran does a build).

Yeah that's the case. I think the `build_runner` dep is the answer I was looking for, so it's unfortunate we can't use that long term.

> If ... it does that check before it checks for _any_ `.packages` files ... but essentially it should choose the "closest" context it can find

Yes, the concept of a `Workspace` (which is what we use here) is a bigger concept than `.packages` files which introduce a `Context`. We search for `Workspace`s first and `Context`s second, but somehow finding a `Workspace` seems to be stopping the code that searches for nested `Context`s.

In theory, though, you could even have nested package:build `Workspace`s. So the design here may need some larger changes.

**Comment by srawlins** [comment]
This could still be a problem, but I imagine it would have been re-reported elsewhere. Closing for now; re-open if it is still a problem.
