### ISSUE TITLE
Confusing message associated with DEPRECATED_MEMBER_USE when doing a prefixed import

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35922]
The following code:
```dart
import 'package:analyzer/analyzer.dart' as analyzer;
```
Produces the hint `info • 'analyzer' is deprecated and shouldn't be used`.  This is really misleading because it makes it sound like the whole analyzer package has been deprecated.  In point of fact all that's been deprecated is the library `package:analyzer/analyzer.dart`.

We should adjust the message text to something like `'package:analyzer/analyzer.dart' is deprecated and shouldn't be used`.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/93066
