### ISSUE TITLE
Remove `dartdevk.dart.snapshot` from the SDK

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#35926]
The corresponding `.bat` and executable files were removed in https://github.com/dart-lang/sdk/commit/3d6acab3e78e99e8b2613e0e99df5b283fd670f9. We should also remove the snapshot if it isn't used.

**Comment by jmesserly** [comment]
hmm, do you know how you were seeing this? "git grep dartdevk" doesn't find anything except the test configuration name (which we're keeping). In my (recently cleaned) xcodebuild directory I'm not seeing anything. Could it be a stale file from an old build?

**Comment by jmesserly** [comment]
I downloaded the latest dev SDK zip file and I'm not seeing this file under bin/snapshots

**Comment by grouma** [comment]
I noticed this on Windows with a chocolaty install. I deleted the SDK folder and installed it yesterday. Could this be a Windows only issue?

**Comment by jmesserly** [comment]
I am not seeing this file in our official zip files at: https://webdev.dartlang.org/tools/sdk/archive, at least with the latest dev release (I did not check the stable build).

Perhaps Chocolatey does not clear old files? Or the build is old, from before we removed `dartdevk`?

**Comment by grouma** [comment]
Let me delete the SDK folder and try to do another install with chocolaty later today. If it doesn't show up I'll close this.

**Comment by jmesserly** [comment]
I figured it out, https://chocolatey.org/packages/dart-sdk has an older build from 2018-12-13. You can see in their zip file "virus scan" results that dartdevk was still present at that point in time, which makes sense, since my CL is from Jan 4th. I think we can close this?

**Comment by grouma** [comment]
Nice. Yeah we can close.
