### ISSUE TITLE
please update the verbosity of class inheritance.

### ISSUE THREAD

**Issue by faststare08** [dart-lang/sdk#35939]
example I want to inherit the Map class and please dont require the developer to implement each of the method of the parent class.

**Comment by zoechi** [comment]
https://api.dartlang.org/stable/2.1.0/dart-collection/MapMixin-class.html might help

**Comment by lrhn** [comment]
The `Map` class is an abstract interface, so inheriting gives you no implementations of the members.

You can't declare a non-abstract class which implements `Map` and does not have an implementation of the `Map` interface. The language considers such a class a bug. If we allowed it, it would be far too easy to forget implementing some method of the interface, or, if the interface gets a new method, it is too easy to not realize that an implementation is no longer complete. In Dart 1 it was only a warning to not implement an interface completely, but in Dart 2 it is an error.

So, if you want to implement `Map`, then you need to get an implementation from *somewhere*.

There is only one concrete, extensible class implementing `Map` in the platform libraries: `SplayTreeMap`. You could extend that, but it's likely not the type of map that you want.

Alternatively, you can extend `MapBase` from `dart:collection`, which provides a default implement of most of the methods of `Map`. You still have to implement a small group of fundamental methods (`keys`, `[]`, `[]=`, `remove` and `clear`). The remaining functions are defined in terms of those

For your case, I think the best solution is to extend `DelegatingMap` from `package:collection`.
It implements the entire `Map` interface, and by default it forwards all calls to a map that is provided in the constructor. You can then override some of the methods, or add new methods. The delegating collection classes are provided precisely for uses like that

Example:
```dart
import "package:collection";

class MyFancyMap<K, V> extends DelegatingMap<K, V> {
  MyFancyMap() : super(<K, V>{}); 
  /// Fancy new method.
  void addWhere(Map<K, V> map, {bool whereKey(K key), bool whereValue(K value)}) {
    map.forEach((key, value) {
      if ((whereKey == null || whereKey(key)) && (whereValue == null || whereValue(value)) {
        this[key] = value;
      }
    });
  }

  /// New implementation of existing method.
  void addAll(Map<K, V> map) {
    // Use my method instead of the default:
   addWhere(map);
  }
  
  /// Specialied behavior of existing method, using old method.
  /// Here: don't store keys with `null` values, remove the keys instead.
  void opearator[]=(K key, V value) {
    if (value == null) {
      super.remove(key);
    } else {
      super[key] = value;
    }
  }
}
```

So, the `DelegatingMap` class is the easiest way to implement the entire `Map` interface, delegating to a map implementation of your choice. You can override the individual methods, add methods, and use `super.something` to use the original method. The `DelegatingMap` class exists precisely for this reason.
