### ISSUE TITLE
Misleading error message when symbol doesn't exist in prefixed library

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#35936]
When referring to a symbol that doesn't exist via a library prefix, the analyzer refers to the library prefix as a class. For example, if in the following code, `foo.dart` doesn't export the symbol `bar`

```dart
import 'foo.dart' as foo;

void main() {
  print(foo.bar);
}
```

the analyzer produces the following message:

> The getter 'bar' isn't defined for the class 'foo'. #undefined_getter

This is misleading because `foo` isn't a class, it's a library prefix. I imagine the analyzer has enough information to discern this fact, but is perhaps reusing the same message that is normally used for undefined properties on classes?

See https://github.com/dart-lang/angular/issues/1716 for an example of where users have run into this misleading message.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/93121
