### ISSUE TITLE
frontend_server_test is failing on windows w/asserts

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#35946]
The test pkg/vm/test/frontend_server_test.dart is failing on Windows in one of its subtests (full compiler tests compile and recompile with MultiRootFileSystem). 

The test runs on 
https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/pkg-win-release

The results dashboard query for it is
https://datastudio.google.com/c/reporting/1Frv1da3qnxI5r0Fhinx0D0xbXNAyBlvv/page/8zzd?config=%7B%22df15%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580vm%252Ftest%252Ffrontend_server_test%22%7D

and the failing log is at
https://dart-ci.appspot.com/log/pkg-win-release/latest/pkg/vm/test/frontend_server_test
https://dart-ci.appspot.com/log/pkg-win-release/4139/pkg/vm/test/frontend_server_test

/=============================================================================\
| pkg/vm/test/frontend_server_test failed again (RuntimeError, expected Pass) |
\=============================================================================/

--- Command "vm" (took 58.000000s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.packages C:\b\s\w\ir\cache\builder\sdk\pkg\vm\test\frontend_server_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: basic train with mocked compiler completes[0m
00:00 [32m+1[0m: batch compile with mocked compiler compile from command line[0m
00:00 [32m+2[0m: batch compile with mocked compiler compile from command line with link platform[0m
00:00 [32m+3[0m: interactive compile with mocked compiler compile one file[0m
00:00 [32m+4[0m: interactive compile with mocked compiler compile one file[0m
00:00 [32m+5[0m: interactive compile with mocked compiler compile few files[0m
00:00 [32m+6[0m: interactive incremental compile with mocked compiler recompile few files[0m
00:00 [32m+7[0m: interactive incremental compile with mocked compiler recompile few files with new entrypoint[0m
00:00 [32m+8[0m: interactive incremental compile with mocked compiler accept[0m
00:00 [32m+9[0m: interactive incremental compile with mocked compiler reset[0m
00:00 [32m+10[0m: interactive incremental compile with mocked compiler compile then recompile[0m
00:00 [32m+11[0m: interactive incremental compile with mocked IKG compile then accept[0m
00:00 [32m+12[0m: interactive incremental compile with mocked IKG compile with output path compile from command line[0m
00:00 [32m+13[0m: full compiler tests compile expression[0m
00:02 [32m+14[0m: full compiler tests compile expression when delta is rejected[0m
result e5a9a864-bc2c-4aa3-ad2c-87c86e867d57
e5a9a864-bc2c-4aa3-ad2c-87c86e867d57 C:\b\s\w\ir\tmp\t\foo bareab21ad0-305d-11e9-87d3-a60be3196b8b/app.dill 0
result cfefa575-15dc-4eb5-ad9d-ef2cf527fc6a
cfefa575-15dc-4eb5-ad9d-ef2cf527fc6a C:\b\s\w\ir\tmp\t\foo bareab21ad0-305d-11e9-87d3-a60be3196b8b/app.dill.incremental.dill 0
C:\b\s\w\ir\tmp\t\foo bareab21ad0-305d-11e9-87d3-a60be3196b8b/app.dill.incremental.dill 0
result df30165d-7973-4c62-b773-119194ad98ba
df30165d-7973-4c62-b773-119194ad98ba C:\b\s\w\ir\tmp\t\foo bareab21ad0-305d-11e9-87d3-a60be3196b8b/app.dill.incremental.dill 0
result e0baefe0-7ed3-4f03-999a-866f973a1bb3
e0baefe0-7ed3-4f03-999a-866f973a1bb3
result 3976a0b3-76e9-48d0-8a71-e9a161968048
3976a0b3-76e9-48d0-8a71-e9a161968048 C:\b\s\w\ir\tmp\t\foo bareab21ad0-305d-11e9-87d3-a60be3196b8b/app.dill.incremental.dill 0
00:03 [32m+15[0m: full compiler tests recompile request keeps incremental output dill filename[0m
00:04 [32m+16[0m: full compiler tests unsafe-package-serialization[0m
00:05 [32m+17[0m: full compiler tests compile and recompile report non-zero error count[0m
00:05 [32m+17[0m[31m -1[0m: full compiler tests compile and recompile report non-zero error count [1m[31m[E][0m[0m
  Expected: <0>
    Actual: <1>

  third_party\pkg\test\lib\src\frontend\expect.dart 160:30                  fail
  third_party\pkg\test\lib\src\frontend\expect.dart 154:3                   _expect
  third_party\pkg\test\lib\src\frontend\expect.dart 60:3                    expect
  pkg\vm\test\frontend_server_test.dart 913:13                              main.<fn>.<fn>.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                              _rootRunUnary
  dart:async/zone.dart 1029:19                                              _CustomZone.runUnary
  dart:async/zone.dart 931:7                                                _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                                        _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 591:14                                        _DelayedData.perform
  dart:async/stream_impl.dart 707:11                                        _StreamImplEvents.handleNext
  dart:async/stream_impl.dart 667:7                                         _PendingEvents.schedule.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                              _rootRun
  dart:async/zone.dart 1021:19                                              _CustomZone.run
  dart:async/zone.dart 923:7                                                _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                               _CustomZone.bindCallbackGuarded.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                              _rootRun
  dart:async/zone.dart 1021:19                                              _CustomZone.run
  dart:async/zone.dart 923:7                                                _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                               _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                                  _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                                   _startMicrotaskLoop
  dart:isolate/runtime/lib/isolate_patch.dart 115:13                        _runPendingImmediateCallback
  dart:isolate/runtime/lib/isolate_patch.dart 172:5                         _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                              _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                                        _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                                        new _BufferingStreamSubscription
  dart:async/stream_controller.dart 838:9                                   new _ControllerSubscription
  dart:async/stream_controller.dart 670:51                                  _StreamController._subscribe
  dart:async/stream_controller.dart 818:19                                  _ControllerStream._createSubscription
  dart:async/stream_impl.dart 472:9                                         _StreamImpl.listen
  pkg\vm\test\frontend_server_test.dart 880:30                              main.<fn>.<fn>
  dart:async/runtime/lib/async_patch.dart 49:6                              _AsyncAwaitCompleter.start
  pkg\vm\test\frontend_server_test.dart 840:63                              main.<fn>.<fn>
  third_party\pkg\test\lib\src\backend\declarer.dart 168:27                 Declarer.test.<fn>.<fn>.<fn>
  dart:async/runtime/lib/async_patch.dart 77:64                             _asyncThenWrapperHelper.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                              _rootRunUnary
  dart:async/zone.dart 1029:19                                              _CustomZone.runUnary
  dart:async/future_impl.dart 126:18                                        _FutureListener.handleValue
  dart:async/future_impl.dart 639:45                                        Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 668:32                                        Future._propagateToListeners
  dart:async/future_impl.dart 473:7                                         Future._complete
  dart:async/future_impl.dart 51:12                                         _SyncCompleter.complete
  dart:async/runtime/lib/async_patch.dart 28:18                             _AsyncAwaitCompleter.complete
  dart:async/runtime/lib/async_patch.dart 294:13                            _completeOnAsyncReturn
  third_party\pkg\test\lib\src\backend\declarer.dart                        Declarer._runSetUps
  dart:async/runtime/lib/async_patch.dart 77:64                             _asyncThenWrapperHelper.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                              _rootRunUnary
  dart:async/zone.dart 1029:19                                              _CustomZone.runUnary
  dart:async/future_impl.dart 126:18                                        _FutureListener.handleValue
  dart:async/future_impl.dart 639:45                                        Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 668:32                                        Future._propagateToListeners
  dart:async/future_impl.dart 348:9                                         Future._addListener.<fn>
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 209:15  StackZoneSpecification._run
  third_party\pkg\stack_trace\lib\src\stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                              _rootRun
  dart:async/zone.dart 1021:19                                              _CustomZone.run
  dart:async/zone.dart 923:7                                                _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                               _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                                  _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                                   _startMicrotaskLoop
  dart:isolate/runtime/lib/timer_impl.dart 391:30                           _Timer._runTimers
  dart:isolate/runtime/lib/timer_impl.dart 416:5                            _Timer._handleMessage
  dart:isolate/runtime/lib/isolate_patch.dart 171:12                        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                              _CustomZone.registerUnaryCallback
  dart:async/runtime/lib/async_patch.dart 77:23                             _asyncThenWrapperHelper
  third_party\pkg\test\lib\src\backend\declarer.dart                        Declarer.test.<fn>.<fn>.<fn>
  third_party\pkg\test\lib\src\backend\invoker.dart 250:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                              _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                               _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                               new Timer
  dart:async/timer.dart 87:9                                                Timer.run
  dart:async/future.dart 174:11                                             new Future
  third_party\pkg\test\lib\src\backend\invoker.dart 402:11                  Invoker._onRun.<fn>.<fn>.<fn>

00:06 [32m+17[0m[31m -1[0m: full compiler tests compile and recompile with MultiRootFileSystem[0m
result 0e959c13-53ed-4a91-8d71-0f586bdb5aa9
0e959c13-53ed-4a91-8d71-0f586bdb5aa9 C:\b\s\w\ir\tmp\t\foo bareab21ad4-305d-11e9-87d3-a60be3196b8b/app.dill 0
00:06 [32m+18[0m[31m -1[0m: full compiler tests compile "package:"-file[0m
result dc6913a6-95b2-4c60-8160-a4bf3c9b7da7
dc6913a6-95b2-4c60-8160-a4bf3c9b7da7 C:\b\s\w\ir\tmp\t\foo bareab21ad5-305d-11e9-87d3-a60be3196b8b/app.dill 0
00:06 [32m+19[0m[31m -1[0m: full compiler tests compile and produce deps file[0m
result 8a56df24-9a8d-4fbc-929c-609ac8961826
8a56df24-9a8d-4fbc-929c-609ac8961826 C:\b\s\w\ir\tmp\t\foo bareab21ad6-305d-11e9-87d3-a60be3196b8b/app.dill 0
00:07 [32m+20[0m[31m -1[0m: full compiler tests mimic flutter benchmark[0m
Restart #0
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/full.dill -- count 0
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/full.dill -- count 1
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/incremental.dill -- count 2
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/incremental.dill -- count 3
Restart #1
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/full.dill -- count 0
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/full.dill -- count 1
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/incremental.dill -- count 2
C:\b\s\w\ir\tmp\t\foo bareab21ad7-305d-11e9-87d3-a60be3196b8b/incremental.dill -- count 3
00:44 [32m+21[0m[31m -1[0m: [31mSome tests failed.[0m

stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n unittest-asserts-release-win pkg/vm/test/frontend_server_test

**Comment by whesse** [comment]
I misread the log, I think the failing subtest is 
"full compiler tests compile and recompile report non-zero error count".

test source: https://dart.googlesource.com/sdk/+/master/pkg/vm/test/frontend_server_test.dart#840

**Comment by dcharkes** [comment]
link from @athomas: https://dart-ci.appspot.com/log/pkg-linux-debug/547/pkg/vm/test/kernel_front_end_test

**Comment by dcharkes** [comment]
The test swallows the actual error:

```dart
file:///C:/Users/DACOHA~1/AppData/Local/Temp/foo%20bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/foo.dart:1:10: Error: Method not found: 'foo'.
main() { foo(); bar(); }
         ^^^
file:///C:/Users/DACOHA~1/AppData/Local/Temp/foo%20bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/foo.dart:1:17: Error: Method not found: 'bar'.
main() { foo(); bar(); }
                ^^^
f90c324c-a95b-4834-9b6e-603a70c16ced C:\Users\DACOHA~1\AppData\Local\Temp\foo bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/app.dill
2
result b793ab90-47fc-4493-bd18-596e07ea83bc
file:///C:/Users/DACOHA~1/AppData/Local/Temp/foo%20bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/bar.dart:1:10: Error: Method not found: 'baz'.
main() { baz(); }
         ^^^
b793ab90-47fc-4493-bd18-596e07ea83bc C:\Users\DACOHA~1\AppData\Local\Temp\foo bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/app.dill.incremental.dill 1
result b1aaefea-bba3-4327-b7b2-e0f9ff3143df
file:///C:/Users/DACOHA~1/AppData/Local/Temp/foo%20bar64a72c2d-3c1f-11e9-b7dd-8cdcd44b8c86/bar.dart:1:10: Error: Method not found: 'baz'.
main() { baz(); }
         ^^^
```

**Comment by dcharkes** [comment]
Something is wrong with the path encoding on Windows, the `invalidatedUris` in fasta contains a path where the backslashes are encoded as `%5C`. On Linux/MacOS these would be forward slashes and the paths are the same.

`IncrementalCompiler.computeDelta`: `print(entryPoint); print(invalidatedUris);`


```
file:///C:/Users/DACOHA~1/AppData/Local/Temp/foo_barf3699276-3c29-11e9-b7dd-8cdcd44b8c86/bar.dart 
{c:%5CUsers%5CDACOHA~1%5CAppData%5CLocal%5CTemp%5Cfoo_barf3699276-3c29-11e9-b7dd-8cdcd44b8c86%5Cbar.dart}
```

**Comment by aam** [comment]
How do I find when the test started failing?

**Comment by aam** [comment]
This seems to have been broken since https://dart-review.googlesource.com/c/91747.

cc @jensjoha
