### ISSUE TITLE
flutter analyze does not tell the line number of the syntax error

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#35949]
Put the code of 
https://github.com/flutter/flutter/issues/22302
into `lib/main.dart` and run
`flutter analyze`

The output does not properly report lines.

I get
```
 error • Expected to find '}' • lib/main.dart:1:374 • expected_token
```
even though it should report
```
 error • Expected to find '}' • lib/main.dart:15:40 • expected_token
```

![image](https://user-images.githubusercontent.com/405837/52805441-da6f7800-3086-11e9-8f45-9964a0a8f9b1.png)

**Comment by zoechi** [comment]
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
    • Flutter version 1.2.1-pre.142 at /Users/zoechi/flutter/flutter
    • Framework revision fec01201b1 (5 days ago), 2019-02-09 11:23:28 -0500
    • Engine revision 067045757f
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 174d6fec3d)
```

**Comment by srawlins** [comment]
That is super weird. I haven't seen other reports like this, so I'm closing as stale. Please report if you see this again.
