### ISSUE TITLE
" Simultaneous usage of DBC simulator and interpreter not yet supported."

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35943]
On our buildbot we seem to be getting flakiness with (from [this build](https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-mac-release-simdbc64/1725) and [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8921589204952650928/+/steps/vm_tests_shard_1/0/stdout)):
```
FAILED: dartk-vm release_simdbc64 vm/cc/GenKernelKernelMaxRSS
Expected: Pass
Actual: Crash

--- Command "run_vm_unittest" (took 05.000793s):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/run_vm_tests --dfe=/b/s/w/ir/xcodebuild/ReleaseSIMDBC64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags GenKernelKernelMaxRSS

exit code:
-6

stderr:
../../runtime/vm/stub_code.cc: 137: error: Simultaneous usage of DBC simulator and interpreter not yet supported.
thread=4355, isolate=kernel-service(0x7ff45e014000)
  [0x000000010a42c884] dart::Profiler::DumpStackTrace(void*)
  [0x000000010a42c884] dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-mac-release-simdbc64 vm/cc/GenKernelKernelMaxRSS

```

The  commit on which this failed seems unrelated.

/cc @crelier @alexmarkov Since you guys are working on the interpreter. Any idea why this would be flaky?

**Comment by crelier** [comment]
It looks like this GenKernelKernelMaxRSS test is temporarily enabling the interpreter, regardless of whether it runs on a simulator or not. See runtime/vm/benchmark_test.cc:162:
  FLAG_enable_interpreter = true;

I am not familiar with this benchmark. Does it make sense to run it without the interpreter when running on a simulator? Or should we skip it altogether?

**Comment by alexmarkov** [comment]
That benchmark measures max RSS after reading bytecode. It make sense to run this benchmark only if interpreter is supported, so we should skip it on all simulated architectures/32-bit arm/ia32.
/cc @zanderso 

Also, as interpreter is not compatible with simulator, maybe interpreter should issue a FATAL error on simulated architectures immediately when entering interpreter? @crelier what do you think?
Currently the error is issued while iterating/inspecting interpreted stack frames, which could be the source of flakiness.

**Comment by crelier** [comment]
See https://dart-review.googlesource.com/c/sdk/+/93343
