### ISSUE TITLE
[VM] Remove TEMP_FAILURE_RETRY from close()

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#35954]
There are a bunch of places where we wrap close(fd) calls in some flavor of TEMP_FAILURE_RETRY. This is a bad pattern that causes some subtle bugs in the case of the call being interrupted.

Context:
https://lwn.net/Articles/576478/
http://linux.derkeiler.com/Mailing-Lists/Kernel/2005-09/3000.html

**Comment by a-siva** [comment]
The TEMP_FAILURE_RETRY makes the code robust to signal interruption. As an aside, not using TEMP_FAILURE_RETRY causes bugs and may be worthy of its own check. The difficult to spot bug in the code above is that close will release the file descriptor even if its interrupted. The retry loops subsequent calls to close will fail with EBADF or close a file descriptor opened on a different thread. A good discussion of the issue and Linux's divergence from POSIX behavior are here:

http://lwn.net/Articles/576478/
http://linux.derkeiler.com/Mailing-Lists/Kernel/2005-09/3000.html

Here is what the spec says (and from which Linux differs):
http://austingroupbugs.net/view.php?id=529

If close() is interrupted by a signal that is to be caught, it shall
return -1 with errno set to [EINTR] and fildes shall remain open;
however, it is unspecified whether fildes can subsequently be passed
to any function except close() without error
