### ISSUE TITLE
Cannot send regular Dart Instance to Isolate spawned with spawnUri

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#35962]
* Dart SDK Version (`dart --version`)

Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"

* Sample code:

_main.dart_

```dart
import 'dart:isolate';

class Message {
  final int number;
  SendPort sender;

  Message(this.number, this.sender);
}

void main(List<String> args) {
  final port = ReceivePort();
  port.listen((data) => print("Got back $data"));
  Isolate.spawnUri(Uri.file('isolate.dart'), [], Message(12, port.sendPort));
}
```

_isolate.dart_

```dart
import 'dart:isolate';

class Message {
  final int number;
  SendPort sender;

  Message(this.number, this.sender);
}

void main(List<String> args, Message msg) {
  receive(msg);
}

void receive(Message msg) {
  print("Received ${msg.number}");
  msg.sender.send(msg.number * 2);
}
```

Running `dart main.dart`, I get the following error:

----

```
Unhandled exception:
Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
#0      Isolate._spawnUri (dart:isolate/runtime/libisolate_patch.dart:530:54)
#1      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:446:7)
<asynchronous suspension>
#2      main (file:///home/renato/programming/projects/webdart-example/run.dart:14:11)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
dart run.dart  0,80s user 0,05s system 139% cpu 0,603 total
```

Expected result:

```
Received 12
Got back 24
```

The result above is what gets printed out if the Isolates are both in the same process, as with this:

```
import 'dart:isolate';

class Message {
  final int number;
  SendPort sender;

  Message(this.number, this.sender);
}

void main(List<String> args) {
  final port = ReceivePort();
  port.listen((data) => print("Got back $data"));
  Isolate.spawn(receive, Message(12, port.sendPort));
}

void receive(Message msg) {
  print("Received ${msg.number}");
  msg.sender.send(msg.number * 2);
}

```

If sending objects between Isolates running on different processes is not possible, at least that should be made a bit clearer in the documentation, I think, as I couldn't find anything related to this limitation.

I hope I am not doing something wrong... sorry if that's the case but information about `spawnUri` seems to be very limited.

**Comment by mraleph** [comment]
This limitation is described in [the documentation for `SendPort.send`](https://api.dartlang.org/dev/2.2.0-dev.2.0/dart-isolate/SendPort/send.html)

> The content of message can be: primitive values (null, num, bool, double, String), instances of SendPort, and lists and maps whose elements are any of these. List and maps are also allowed to be cyclic.
> 
> In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via Isolate.spawn), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the dartvm. For now, the dart2js compiler only supports the restricted messages described above.
