### ISSUE TITLE
Error: Error when reading 'bin/main.dart': The system cannot find the path specified.

### ISSUE THREAD

**Issue by narayanapillaikumar** [dart-lang/sdk#35971]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by dgrove** [comment]
There is not enough information to act on here - if you are still seeing this, can you please file a new issue?

**Comment by davidakinfenwa** [comment]
I am also having the same issue 

Error: Error when reading 'bin/main.dart': The system cannot find the path specified.

my .vscode is like this:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            
        }
    ]
}
