### ISSUE TITLE
Add HashCodeBuilder to help developers build hash codes

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#3597]
Dart objects don't implement Hashable by default. It is left up to the developer to implement Hashable and provide a sensible hashcode. This can be error-prone if not understood. However, there are well known hash code generation strategies.

Suggest the Dart library ship with a hashcode builder to facilitate the correct strategy for generating a hashcode.

**Comment by floitschG** [comment]
Marking as dupe of #11617
