### ISSUE TITLE
http package not working

### ISSUE THREAD

**Issue by Mallikarjun-0369** [dart-lang/sdk#35972]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by Mallikarjun-0369** [comment]
Getting error with http package.
Error: Not found 'dart:html' import 'dart:html';
Error: Type 'HttpRequest' not fount.

file:///C:/flutter_stable/flutter_windows_v1.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:95:25: Error: Type 'HttpRequest' not found.
  void _openHttpRequest(HttpRequest request, String method, String url,

**Comment by zoechi** [comment]
Ensure your Flutter install is clean https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by Mallikarjun-0369** [comment]
Hi Gunter Zochabauer,

Thank a lot, Issue resolved with your suggestion.



*Regards,*
*Mallikarjuna Reddy,*
*Android Developer.*
