### ISSUE TITLE
Please merge 765e6338a803ee17472b1fa715ffcfbd4ea46bfb into dev channel

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#35987]
**commit(s) to merge**: https://dart.googlesource.com/sdk/+/765e6338a803ee17472b1fa715ffcfbd4ea46bfb

**merge instructions**: TBD clean merge or patch CL

**reason**: dart:ffi is not ready for public consumption yet. This commit marks it for exclusion in API docs

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Landed in f2255563431b5ec71194d959c3ff74d0f824b36e.
