### ISSUE TITLE
The sdk ships with 8 different versions of the ddc compiled sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#35988]
dartdevc supports 4 different module loaders, and two different frontends, which results in 8 copies of the untreeshaken sdk. This totals 47.8MB out of a total 291.7MB for the entire sdk.

A lot of this is for historical/transitional reasons, but we should try and get down to just 1 if we can, or at least reduce this as much as possible : ).

As far as I know, the only truly supported module system externally is `amd` (via build_web_compilers), but we should probably keep both the analyzer and kernel versions around for a while.

Note that this also has the effect today of copying all of these files into the output directory from webdev/build_runner, so even a hello world app with no deps produces an ~50MB output directory today.

cc @jmesserly I don't know if we have any plans to reduce the number of module formats that are supported?

**Comment by jmesserly** [comment]
> Note that this also has the effect today of copying all of these files into the output directory from webdev/build_runner, so even a hello world app with no deps produces an ~50MB output directory today.

It seems like this should be fixable without changes to the SDK.

> As far as I know, the only truly supported module system externally is `amd` (via build_web_compilers), but we should probably keep both the analyzer and kernel versions around for a while.

Some folks are using the Common JS format with Node JS. We could probably remove legacy and ES6 though. I would like us to transition to ES6 at some point, but there doesn't seem to be any urgent reason to do it.

We don't technically need to keep both Analyzer and Kernel compiled JS files, as they should be functionally equivalent. But I do worry if the backends are not self-sufficient. If we're going to keep one, I'd suggest we keep the Kernel one, that way we're testing the thing we're moving towards (and not relying on the deprecated backend).

**Comment by jakemac53** [comment]
> It seems like this should be fixable without changes to the SDK.

This is unfortunately a lot harder than you would think because of how the `Builder`s are encapsulated, and the fact that we model deletions as a `Builder` also. It is also just generally difficult to prove beyond a reasonable doubt that some file is never used in release mode. For instance you can change your compiler for release mode to be dartdevc... and then it would crash if we always delete these.

**Comment by jakemac53** [comment]
> We don't technically need to keep both Analyzer and Kernel compiled JS files, as they should be functionally equivalent. But I do worry if the backends are not self-sufficient. If we're going to keep one, I'd suggest we keep the Kernel one, that way we're testing the thing we're moving towards (and not relying on the deprecated backend).

This would help significantly, and is probably the quickest way forward for now. We should ideally just drop the `kernel` directory and replace the existing files with the kernel produced ones?

**Comment by jmesserly** [comment]
> This is unfortunately a lot harder than you would think because of how the `Builder`s are encapsulated, and the fact that we model deletions as a `Builder` also. It is also just generally difficult to prove beyond a reasonable doubt that some file is never used in release mode. For instance you can change your compiler for release mode to be dartdevc... and then it would crash if we always delete these.

Err, I'm not following, can't we just copy the one relevant dart_sdk.js file for the build configuration? That's what most build systems would do. (It seems like a big hammer to delete useful configurations from the SDK, because the build system can't figure out which one to copy...)

> We should ideally just drop the `kernel` directory and replace the existing files with the kernel produced ones?

That sounds right, but we'll need to be careful it doesn't affect our build bots, which still need to test Analyzer SDK and "legacy" format for use by internal builds. Basically the intermediate path (under "gen") won't change, only the files under the "dart-sdk" folder.

**Comment by jakemac53** [comment]
> Err, I'm not following, can't we just copy the one relevant dart_sdk.js file for the build configuration? That's what most build systems would do.

This sort of all stems from the fact that `package:build_runner` is designed to work with zero configuration. You don't explicitly declare all the inputs to actions/binaries/etc, so we just make everything available all the time.

We treat the sdk just like any other package, just with the special name `$sdk`. All packages have to pre-declare their sources, in the case of the SDK today we use [this glob](https://github.com/dart-lang/build/blob/0e3808b73b56e0485206f55c39b37fcd2c64ab44/build_runner_core/lib/src/package_graph/target_graph.dart#L43).

We could certainly make that glob more specific, but that means if we switch module formats later then old versions of build_runner won't work with newer versions of build_web_compilers. No direct dependency exists between these packages, so we can't make pub do the version solve for us.

**Comment by jmesserly** [comment]
Ah gotcha. It seems like the build system knows it only wants AMD and it only wants Analyzer (or Kernel, if in DDK mode), so would a glob like this work: `'lib/dev_compiler/amd/*.js'` Or does the AMD knowledge only exist in build_web_compilers? If so, could that package be responsible for copying the SDK, since it's the one that has knowledge of which files DDC apps actually need to run?

(Conceptually DDC itself could copy dart_sdk.js, similar to how dart2js statically links the SDK so the JS file can be run standalone. The reason I didn't, is that most compiles aren't the entrypoint so it seemed like it would be a lot of redundant copying. But if DDC had an option to copy the SDK, would it help? DDC knows which backend and module format were selected, so it could copy the right file)

**Comment by jakemac53** [comment]
> Or does the AMD knowledge only exist in build_web_compilers? If so, could that package be responsible for copying the SDK, since it's the one that has knowledge of which files DDC apps actually need to run?

Right, only build_web_compilers really knows. We were actually just discussing essentially doing this copy you describe to resolve the issue. We can abuse the build system a bit and use dart:io to read directly from the sdk and copy the files we know we need into the build_web_compilers package itself and serve them from there instead of the `$sdk` package. Then we can even potentially remove the `$sdk` package hack entirely.

**Comment by jmesserly** [comment]
Oh nice, that sounds awesome! If you want to add any copy logic to DDC (since it already knows some of the info), feel free. But build_web_compilers sounds good too.

**Comment by jakemac53** [comment]
Fwiw, I do also still think it would be worth trying to reduce the amount of precompiled JS we ship with the sdk. It sounded like deleting the kernel dir would be enough to close this issue?

**Comment by jmesserly** [comment]
> Fwiw, I do also still think it would be worth trying to reduce the amount of precompiled JS we ship with the sdk. It sounded like deleting the kernel dir would be enough to close this issue

yeah, I think we should do this:
- remove: lib/dev_compiler/{amd,common,es6,legacy}/*
- remove: lib/dev_compiler/kernel/{es6,legacy}/*
- move: lib/dev_compiler/kernel/{amd,common}/* --> lib/dev_compiler/{amd,common}/*

**Comment by kevmoo** [comment]
This is 46 MB of code (uncompressed). It likely a non-trivial addition to the flutter SDK. We should move on this.

CC @vsmenon @jonahwilliams

**Comment by jmesserly** [comment]
CC @nshahan or @Markzipan who may be looking for tasks to grab. This one would have a lot of benefit. I'm not sure who in our office can offer advice on how to edit GN files, maybe y'all can ask around (IIRC, Bob and Vijay have contributed to that file in the past, and Siggi may have done some work on the dart2js GN file).

**Comment by nshahan** [comment]
@jmesserly I've been experimenting with removing es6 and legacy versions of the precompiled sdk. Removing them from the GN files is pretty simple so they don't get generated but that breaks some tools/tests that rely on them. For example `pkg/dev_compiler/test/sourcemap/sourcemaps_ddc_suite.dart` uses es6 modules. 

Going through and cleaning that up leads me to a new questions: In the removal process do we want to cleanup all forms of support or modify all the tools to work in these modes without the precompiled sdk and compile it as needed? Should we be scrubbing all the es6 and legacy options from all our tools?

**Comment by jmesserly** [comment]
@nshahan -- we don't need to remove them completely from the build, just from the part that copies them into the dart-sdk folder. Sorry I wasn't clear about that.

> Going through and cleaning that up leads me to a new questions: In the removal process do we want to cleanup all forms of support or modify all the tools to work in these modes without the precompiled sdk and compile it as needed? Should we be scrubbing all the es6 and legacy options from all our tools?

Definitely not. This is a temporary decision to not ship JS files we're not using yet. "legacy" is still required internally, and ES6 is still something we'll probably want to move to, once there's better browser support for it. (In fact, we can probably move node.js support over to ES6 soon.)

**Comment by jmesserly** [comment]
In particular, it looks like (root) BUILD.gn, copy_dev_compiler_js is the target to change. Should only be a few lines, I'd imagine, plus removing the corresponding targets that aren't used anymore (e.g. copy_dev_compiler_js_legacy)

**Comment by jmesserly** [comment]
I was thinking something like this (disclaimer: completely untested): https://dart-review.googlesource.com/c/sdk/+/99905 ... does that seem reasonable?

**Comment by nshahan** [comment]
Yeah, that all sounds reasonable. I have a similar WIP to remove the copy and output in the SDK but there are a few breaks that need cleanup to make it land-able. I'll iterate on that. Thanks!

**Comment by nshahan** [comment]
I have finally removed all precompiled copies of the SDK module that shipped in the packaged SDK.
https://dart-review.googlesource.com/c/sdk/+/275482
