### ISSUE TITLE
Missing detection of compile-time error concerned with field and constant constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35983]
Consider the following program:

```dart
class C {
  final xs = []; // Error!
  const C();
}

main() => const C();
```

With `dart` version 2.1.1-dev.3.2 and a fresh 072088823638f05b8f698db1d616cab10e0c1af0, the following dynamic error is reported:

```
error: Invalid const object field: Instance(length:0) of '_GrowableList', owner: Instance of 'C'
```

However, this should be reported as a _compile-time_ error (dartLangSpec, section 'Constant Constructors'):

```
It is a compile-time error if a constant constructor is declared
by a class $C$ if any instance variable declared in $C$ is initialized
with an expression that is not a constant expression.
```

This may be an `area-front-end` issue, or it might at least become an `area-front-end` issue when &amp; if all constant related tasks are handled by the front end.

But, for now, I've chosen `area-vm`, which fits with the behavior of `dart2js` (where the same issue is handled differently, cf. #35984).

**Comment by mkustermann** [comment]
@askeksa-google This might be a case where the kernel const evaluator assumes front-end would've issued a compile-time error already, so it blindly evaluates initializers.

**Comment by askeksa-google** [comment]
Actually, the new constant evaluator already handles this case on its own. Run with `--enable-experiment=constant-update-2018` and see that a compile-time error is correctly reported.

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
