### ISSUE TITLE
Indentation is messed up after running 'Wrap with new widget' quick fix

### ISSUE THREAD

**Issue by marcoms** [dart-lang/sdk#35999]
```Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"```

The following is the result when running running 'Wrap with new widget' in VSCode. Seems to happen every time.

![bug](https://user-images.githubusercontent.com/4211302/53124302-ea89ca80-3552-11e9-8f5a-a4cafcc7be67.png)

**Comment by DanTup** [comment]
This has been recently fixed for LSP (I think it was fixed for non-LSP previously) by the combination of https://github.com/dart-lang/sdk/commit/44275c6001837550d4a6b7339237ae1c27bdbc19 and https://github.com/Dart-Code/Dart-Code/pull/3215 (you'll need both an SDK that contains that first change and v3.21 or later of the Dart VS Code extension to see it).
