### ISSUE TITLE
False const_eval_throws_exception in Dart 2.1.2-dev.0.0.flutter-0a7dcf17eb

### ISSUE THREAD

**Issue by werediver** [dart-lang/sdk#35993]
```sh
$ dart --version
Dart VM version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "macos_x64"
```

Two source files are required to reproduce the issue (all the sources in one file will qualify okay).

**main.dart**
```dart
import 'package:const_exc/src/aux.dart';

void main() {
  const foo = Foo(1);
  const bar = Bar.some(); // False const_eval_throws_exception here
  print("$foo, $bar");
}
```

**src/aux.dart**
```dart
class Foo {
  final double value;

  const Foo(this.value);
}

class Bar {
  final Foo value;

  const Bar(this.value);

  const Bar.some() : this(const Foo(1)); // Using a floating point literal `1.0` eliminates the issue
}
```

The error message produced:
```
error: Evaluation of this constant expression throws an exception. (const_eval_throws_exception at [const_exc] lib/src/main.dart:5)
```

The highlights:
- putting sources in multiple files is required to reproduce the issue
- using an integer literal in `Bar.some()` is required (using a floating point literal eliminates the issue)
- the error message seems entirely unrelated

**Comment by mit-mit** [comment]
Is this in the CFE?

**Comment by werediver** [comment]
@mit-mit I'm not familiar with the compiler's codebase, but it looks like the subject error is generated only in [pkg/analyzer/lib/src/dart/constant/evaluation.dart](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/constant/evaluation.dart), so it looks like analyser (but I don't know what the common front-end includes).

**Comment by kmillikin** [comment]
This is coming from the Analyzer.  /cc @stereotype441

**Comment by stereotype441** [comment]
This is a manifestation of a larger issue that we're currently working on (#33441).  That issue will probably take some time to resolve, so in the meantime I've got a band-aid fix: https://dart-review.googlesource.com/c/sdk/+/94123

**Comment by stereotype441** [comment]
Band-aid fix has landed, so I'm reducing the priority of this bug to P2.

**Comment by srawlins** [comment]
What are the conditions for closing this now, @stereotype441 ? I'm guessing it's fixed with const-update-2018? Perhaps summary2? 😀
