### ISSUE TITLE
Breaking change request: non const expressions bug fix

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#35998]
In Dart 2.1.1 and earlier, some Dart tools including analyzer had a bug that caused them to accept some invalid default parameter values and const constructor initializers. This bug can be fixed then may appear as a breaking change on code bases.

Bug dartbug.com/32913
CL https://dart-review.googlesource.com/c/sdk/+/91105

# Expected Impact

We expect this to be unlikely to affect all but a very very small minority of users. I saw two cases in internal code so it does happen but seems very very rare.

# intended change

Previously this example analyzed and built cleanly with all tools

```dart
callback<T>(T t) => ...; // a generic function

f<T>( // a function with a type parameter
  [
    Function(T) x // with an optional function argument referencing the type parameter
      = callback // with the default value referencing the generic function
  ]
) { ... }

// or

class C<T> { // a generic class
  final Function(T) x; // with a function-typed field that references a type parameter
  const C() // with a const constructor
    : x // with an initialzer referencing that field
      = callback; // with an expression that references the generic function
}
```

The exact conditions are complicated to describe, but spelled out in the later "Justification" section.

At first the fix will only affect the analyzer and DDC. The later fixes to the other tools (vm & dart2js through cfe) will not be considered breaking changes. However, this distinction may give users some "wiggle room" if they really really need it.

# Mitigation

If you are affected by this breaking change, the fix is typically to use `dynamic` and `Null` to explicitly create a callback which is assignable for all values of `T`.  (The reason this works is described here).

```dart
callbackWithParameter<P>(P p) => ...;
R callbackWithReturn<R>() => ...;

const Null Function() callbackNull = callbackWithReturn;
const Function(dynamic) callbackDynamic = callbackWithParameter;

f<T>([
  Function(T) x = callbackDynamic,
  T Function() y = callbackNull,
]) { ... }
```

This works for const constructor initializers as well as default parameter values.

Specifically for default parameter values, you also have the option of not specifying a default value and rather using `??=` in your method body to set the default. That way there is no requirement that your default value be a valid const expression.

Because the breakage is expected to be rare, I expect an announcement to be sufficient in helping the community respond.

# Justification

The problem is subtle but important for consistency with how constant values are handled. In Dart, every syntactic occurrence of a compile time expression yields one identical constant value. Dart also enforces that default parameter values and constant initializer values are const.

Here are some examples of behavior that will be unaffected:

```dart
void f() {
  const []; // Only one list is ever created, regardless of how many times f() is called
}

void f2([Map x = const {}]) { // the default value of x must be const
  ...
}

class C {
  final Map x;
  C() : x = const {}; / the initializer of x must be const
  ...
}
```

And type variables are not const (this behavior is also not changed):

```dart
class C<T> {
  const List<T> list = <T>[]; // error: T is not a constant
}
```

This is because, in accordance with the spec and implementation of const, the expression must produce one value, and `T` is a placeholder for what can be any number of values at compile time.

We missed a case, however, where type variables are inferred and results in a non-const default parameter value, or const constructor initializer:

```dart
callback<R>(R r) => ...;

f<T>([Function(T) x = callback]) { ... }

// or

class C<T> {
  final Function(T) x;
  const C() : x = callback;
}
```

Here, the type parameter `T` is implicitly applied to `callback<R>` so that the assignment can succeed. This results in a non-const value of non-const type `Function(T)`. 

This violates the design that one constant expression yields one constant value, and therefore caused different runtime failures of different kinds in different tools.

**Comment by sigmundch** [comment]
FWIW - dart2js already rejects code like this today (i.e. we consider non-constant a generic-function instantiatiated with a type-variable), so both examples above are considered compile-time errors by us.

**Comment by MichaelRFairhurst** [comment]
@sigmundch that doesn't nseem to be the case for me.

I compiled this code successfully:

```
dynamic _defaultCallback<T>(T t) => t;                                           
class C<T> {                                                                     
  final dynamic Function(T) callback;                                            
  // Should be statically rejected                                               
  void foo([dynamic Function(T) f = _defaultCallback]) {}                        
  // Should be statically rejected                                               
  const C({this.callback = _defaultCallback});                                   
}                                                                                
                                                                                 
// Should be statically rejected                                                 
void bar<T>([dynamic Function(T) f = _defaultCallback]) {}                       
                                                                                 
void main() {                                                                    
  print(new C<int>(callback: _defaultCallback));                                 
}    
```

```
$ dart2js test.dart
Compiled 7,364,799 characters Dart to 64,602 characters JavaScript in 0.63 seconds
```

**Comment by sigmundch** [comment]
We only complain if the code is reachable after tree-shaking. The program above effectively doesn't reach any of the elements with static errors.  If you change your main to:
```
main() {
  const C<int>();
  new C<int>(callback: _defaultCallback).foo();
  bar<int>();
}
```

you'll see all 3 errors reported.

**Comment by mit-mit** [comment]
cc @matanlurey @Hixie @dgrove for comments & approval

**Comment by matanlurey** [comment]
Do we have an idea of many breakages internally this causes?

**Comment by MichaelRFairhurst** [comment]
It caused two breakages that I fixed.

cl/232591842 and cl/231476064

**Comment by mit-mit** [comment]
cc @matanlurey @Hixie @dgrove we'd love to get closure on this

**Comment by matanlurey** [comment]
LGTM from me.

**Comment by leafpetersen** [comment]
cc @aadilmaan

**Comment by Hixie** [comment]
I have no opinion on this.

**Comment by eernstg** [comment]
This case was not specified appropriately.

[This PR](https://github.com/dart-lang/language/pull/277) introduces expressions like `f` and `C.f` denoting a library function or static method as a constant expression also in the case where that expression is subject to generic function instantiation, and each actual type argument thus provided is a constant type expression.

Before this change, the spec was silent on how to deal with the fact that some of these expressions would be subject to generic function instantiation. This actually means that the spec said they were _all_ constant (including the case [above](https://github.com/dart-lang/sdk/issues/35998#issuecomment-466164103) where `T` is passed to `_defaultCallback`), and that's definitely not something we want to introduce by accident).

**Comment by leafpetersen** [comment]
> I have no opinion on this.

@Hixie is this a pocket veto, a pocket approval, or a request for more information?  

cc @aadilmaan

**Comment by eernstg** [comment]
Said PR was merged as https://github.com/dart-lang/language/commit/e49bcc31cbfa7fa0569060ba45844a5146a64c94.

**Comment by dgrove** [comment]
LGTM.

**Comment by aadilmaan** [comment]
@Hixie - To echo Leaf's previous comment, do we assume your No Opinion to be an OK2Proceed?

**Comment by MichaelRFairhurst** [comment]
I didn't realize I was supposed to mail the users sooner...doing this now while we wait for @Hixie to respond.

**Comment by Hixie** [comment]
> is this a pocket veto, a pocket approval, or a request for more information?

It's an abstention, I guess. I have no opinion and trust your judgement.

**Comment by eernstg** [comment]
OK, then I'll the commit https://github.com/dart-lang/language/commit/e49bcc31cbfa7fa0569060ba45844a5146a64c94 where the rules were clarified as it is.

In short, this means that a generic function `f` or `p.f` is a constant expression when it is subject to generic function instantiation, provided that the actual type arguments are constant type expressions (plus, of course, the usual requirements for a function to be a constant).

**Comment by eernstg** [comment]
@MichaelRFairhurst, I believe this is no longer area-language. Did you originally intend it to be area-analyzer? I'll remove area-language, please make further changes as needed.

**Comment by kevmoo** [comment]
Can this issue be closed now? Is there work in the SDK – or is it up to a language discussion?
