### ISSUE TITLE
[Proposal] - Please bring the date&time lib to 2019

### ISSUE THREAD

**Issue by cosinus84** [dart-lang/sdk#35994]
There is an issue(proposal) that was very useful. I know is hard but a lot of mobile apps need some date&time magic, is mandatory for flutter to grow. We can not promise in making apps fast but struggling with date&time. Can't move from my RN app using momentjs.

https://github.com/dart-lang/sdk/issues/27245

**Comment by mit-mit** [comment]
Closing, this seems to just be a copy of #27245. @cosinus84 you can thumbs-up the original bug instead of creating a copy.
