### ISSUE TITLE
dartdevc: Implement "Control Flow Collections"

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36005]
Initially these features are behind the experimental flag `control-flow-collections`.

- Support in List Literals.
  - [x] DDC
  - [ ] DDK
- Support in Map Literals.
  - [x] DDC
  - [ ] DDK
- Support in Set Literals.
  - [x] DDC
  - [ ] DDK

Tested in `language_2/control_flow_collections` and `co_19_2/LanguageFeatures/Control-flow-collections`.

See: 
- Language tracking issue: [dart-lang/language#165](https://github.com/dart-lang/language/issues/165)
- [Feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md)
- [Implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/implementation-plan.md)
- [Unified collections specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md)

**Comment by vsmenon** [comment]
@nshahan - done on DDC side?

**Comment by nshahan** [comment]
@vsmenon Yes I believe the implementation is done, I'm just waiting for confirmation from the testing infra to before I check these off.

**Comment by nshahan** [comment]
Progress is looking good. There are a few tests failing for DDK but there are changes out for review to fix them.

**Comment by Markzipan** [comment]
Some tests are failing due to a couple of CFE bugs. See: https://github.com/dart-lang/sdk/issues/36396 and https://github.com/dart-lang/sdk/issues/36395

**Comment by dgrove** [comment]
@nshahan what is remaining here?

**Comment by Markzipan** [comment]
@dgrove, A couple of bugs remain in the CFE. They were originally closed but weren't actually resolved. Reposted here: https://github.com/dart-lang/sdk/issues/36443

**Comment by nshahan** [comment]
Passing the remaining tests are blocked on fixing some missing compile time errors. #36444

**Comment by nshahan** [comment]
We are not expecting any more work on the DDK side.
