### ISSUE TITLE
dartdevc: Implement "Spread Collections"

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36006]
Initially these features are behind the experimental flag `--enable-experiment=spread-collections`.

- Support in List Literals.
  - [x] DDC
  - [x] DDK
- Support in Map Literals.
  - [x] DDC
  - [x] DDK
- Support in Set Literals.
  - [x] DDC
  - [x] DDK

Tested in `language_2/spread_collections` and `co_19_2/LanguageFeatures/Spread-collections`.

See: 
- Language tracking issue: [dart-lang/language#164](https://github.com/dart-lang/language/issues/164)
- [Feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md)
- [Implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/implementation-plan.md)
- [Unified collections specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md)

**Comment by vsmenon** [comment]
@nshahan - are we done on the DDC side now?

**Comment by nshahan** [comment]
@vsmenon DDC looks good and all language_2 spread tests are reporting passing. Waiting on DDK constant update fixes before closing issue as done.

**Comment by dgrove** [comment]
@nshahan what is remaining here?

**Comment by nshahan** [comment]
Progress is looking good. There are a few tests failing for DDK but there are changes out for review to fix them.

**Comment by munificent** [comment]
Everything looks checked. Can we close this out?

**Comment by nshahan** [comment]
I'm reluctant to close this issue until we are passing all tests we expect to pass. At this time DDK is failing the language_2/spread_collections/const_test. To prevent confusion I'll uncheck DDK for now. 

@Markzipan Once all tests are passing could you come back, check it off and close the issue?

**Comment by Markzipan** [comment]
The fix to the last failing spread test is in this cl: https://dart-review.googlesource.com/c/sdk/+/98300

Forgot to submit it!
