### ISSUE TITLE
[Analyzer] Not catching possible consts depending on machine

### ISSUE THREAD

**Issue by willlarche** [dart-lang/sdk#36017]
Flutter PR https://github.com/flutter/flutter/pull/28125 passed local and [cirrus](https://cirrus-ci.com/task/5190784199426048) analysis but [failed](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci81N2E4YjAzYzVlN2I1YTE0YmE0NjQ4ZTIwOWJlY2UzYzQxNzNhODNjDAsSBFRhc2sYgICAgICA_AgM) in devicelab on the analyzer_benchmark. 

* Dart SDK Version (`dart --version`)
Local: Dart VM version: 2.1.2-dev.0.0.flutter-c92d5ca288 (Wed Feb 13 19:14:26 2019 +0000) on "macos_x64"
Cirrus: Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
Devicelab: not sure. You should ask someone on flutter-team
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Local: macOS
Cirrus: linux
Deveicelab: linux

**Comment by stereotype441** [comment]
@pq this looks like a linter issue.  Can you take a look?

**Comment by pq** [comment]
Hey @willlarche, I can't access those logs at the moment (seeing auth issues).  Could you paste the failure trace here so I can take a look?

Thanks!

**Comment by willlarche** [comment]
Sure thing: 
Cirrus: 
[5190784199426048-test.log](https://github.com/dart-lang/sdk/files/2907570/5190784199426048-test.log)

Devicelab:
[devicelabAnalyzerLog.txt](https://github.com/dart-lang/sdk/files/2907583/devicelabAnalyzerLog.txt)

**Comment by pq** [comment]
Thanks @willlarche!

I'm not that familiar with how these test environments are setup and run but what I'd like to figure out is where they differ.  In particular, I'd like to confirm:

1. are they running the same version of the Dart SDK?
2. are they running the same command...
3. to analyze the same code?

A simple hypothesis is that the cyrus run is not properly analyzing `lib/demo/fortnightly/fortnightly.dart` (as your changes to address the analysis issues in https://github.com/flutter/flutter/pull/28431/files look reasonable).

I'm guessing totally, but maybe @goderbauer or @tvolkert have some insight into how things are setup and run? 

Some log excerpts below...

cyrus:

```
⏩ RUNNING: cd .; bin/flutter analyze --dartdocs --flutter-repo --watch --benchmark
Analyzing Flutter repository...                                     4.8s


0 issues found • analyzed 1761 files in 4.83 seconds
Analysis benchmark written to analysis_benchmark.json ({time: 4.827, issues: 0, missingDartDocs: 0}).
```

devicelab:

```
Executing: /home/linux1/.cocoon/flutter/dev/devicelab/../../bin/flutter analyze --benchmark --flutter-repo
2019-02-24T03:14:47.118115: stdout: Analyzing 3 directories...                                      
2019-02-24T03:14:47.126266: stdout: Analysis benchmark written to analysis_benchmark.json ({time: 77.517, issues: 3, missingDartDocs: 0}).
```

**Comment by pq** [comment]
OK, I tried an experiment to test the hypothesis that maybe `lib/demo/fortnightly/` is skipped on cyrus by running it's command (`bin/flutter analyze --dartdocs --flutter-repo`) with errors introduced to 
`fortnightly.dart` locally.  That works as expected.

My current thinking is SDK skew.

Can we confirm that the same SDK is running in both environments?

**Comment by willlarche** [comment]
I would need @tvolkert to helpe me on that info.

My local machine was on master, BTW.

**Comment by pq** [comment]
@tvolkert: any thoughts on this?

**Comment by tvolkert** [comment]
I'm currently swamped with mgr tasks...  /cc @dnfield

**Comment by dnfield** [comment]
SDK skew is possible - one test runs on presubmit and the other on post submit.  

I can't seem to find a Cirrus post submit for this, which could help verify that.

**Comment by dnfield** [comment]
Hmm the Cirrus post commit run had the same issue - cirrus version passed using same Dart SDK as the devicelab afterwards.  This really shouldn't be due to SDK version skew

**Comment by pq** [comment]
Thanks for taking a look @dnfield.  I'll loop back in a bit and see if I can dig a little deeper. 🍻

**Comment by srawlins** [comment]
Closing as stale. If this happens again, please re-open.
