### ISSUE TITLE
Unminified dart2js produces invalid names when mixins used

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#36010]
* Dart SDK Version (`dart --version`)

2.2.0-dev.2.1

* Whether you are using Windows, MacOSX, or Linux (if applicable)

Linux

`dart2js` produces invalid property names in prototypes corresponding to classes with mixins. For example, `WidgetsFlutterBinding` declared as this:

```dart
class WidgetsFlutterBinding extends BindingBase
    with
        GestureBinding,
        ServicesBinding,
        SchedulerBinding,
        PaintingBinding,
        SemanticsBinding,
        RendererBinding,
        WidgetsBinding {}
```

Results in the following output:

```javascript
  N._WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_initServiceExtensions_closure0.prototype = {
    // ... other things ...
    $call$body$_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding_initServiceExtensions_closure: function(value) {
      // ... body omitted ...
    }
    // ... other things ...
  }
```

Note the `&` symbols in the property name.

**Comment by rakudrama** [comment]
I noticed this and fixed it earlier this week: https://github.com/dart-lang/sdk/commit/db71576ef39462a99ab2459c5266f65a431443c5
