### ISSUE TITLE
Tired calling: getReference

### ISSUE THREAD

**Issue by sdresche17** [dart-lang/sdk#36016]
App builds just fine and no notes in flutter doctor, but I got the below output when trying to run:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Error reading dependency file C:\Users\SamuelD\Documents\GitHub\RideToWork\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file C:\Users\SamuelD\Documents\GitHub\RideToWork\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null.
Receiver: null
Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

**Comment by jensjoha** [comment]
Thank you for reporting this issue.
Unfortunately this is an old version of dart, where I didn't include enough debugging information in the message to actually fix the issue.
Rest assured though, that everything should still be fine: It tried a speed-up trick but failed --- it then reverted back to a slower compile.
