### ISSUE TITLE
analyzer should warn when using Set literals with SDK < 2.2.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36024]
Just like we did for `Future` without `dart:async` imports, we should warn package authors if they are using a feature outside of their defined SDK constraint.

VERY helpful to avoid publishing packages that silently break folks.

CC @mit-mit @devoncarew @stereotype441

**Comment by devoncarew** [comment]
Are checks like these things we should roll into `pub publish` itself?

**Comment by kevmoo** [comment]
> Are checks like these things we should roll into `pub publish` itself?

Likely, although it should be done server-side. The problem: it'll make publish slow. CC @mit-mit 

Either way, having it analyzer itself is a good first step.

**Comment by kevmoo** [comment]
FYI: marked this P1 because I think it's critical to help our users "do the right thing"

**Comment by bwilkerson** [comment]
Is this something we're going to want for every experiment that gets enabled? (I think the answer it "yes", but wanted to confirm.)

If so, we should make sure that it's part of the analyzer's implementation plan from now on.

Is this going to hold up shipping 2.2.0? (I think that's the implication of the P1 and milestone, but again wanted to confirm.)

**Comment by kevmoo** [comment]
> Is this something we're going to want for every experiment that gets enabled? (I think the answer it "yes", but wanted to confirm.)
>
> If so, we should make sure that it's part of the analyzer's implementation plan from now on.

I think so! As language features are introduced, it'd be amazing if we could warn people about this.

(I'd love to do it for APIs, too.)

https://github.com/dart-lang/sdk/blob/edca6169c1c040702acde237e605be0bfe037326/sdk/lib/internal/internal.dart#L200-L204

> Is this going to hold up shipping 2.2.0? (I think that's the implication of the P1 and milestone, but again wanted to confirm.)

I'd *like* it to block `2.2.0` – later and the ship has sailed. We should talk to @dgrove and @mit-mit about that

**Comment by devoncarew** [comment]
Given the amount of moving parts between landing a change in the sdk repo, and it making it's way into even a dev sdk, I suspect we've already missed 2.2.0. We should likely plan for a landing in a .x patch release, and design the feature we'd ultimately like to see land.

**Comment by kevmoo** [comment]
okay...would be good to track.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/96837

**Comment by kevmoo** [comment]
Closed in 5fdb3c505785457ab0f0c92155e296c570bbea7b

**Comment by kevmoo** [comment]
Reverted in https://github.com/dart-lang/sdk/commit/0f4a208c3ea2ba8ac5c91a227177a8eab53d9f05

**Comment by stereotype441** [comment]
Fix was re-landed in 495c319574843fa83e9c474961cf51498a0d874a
