### ISSUE TITLE
Bring in latest `pub`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36026]
The last sync of `pub` was on Aug 8 - https://github.com/dart-lang/pub/commit/9f00679ef47bc79cadc18e143720ade6c06c0100

We've had a number of commits since – https://github.com/dart-lang/pub/compare/SDK-2.1.0-dev.1.0...master – and we've added a changelog validaor, logout command, support for global activation via a custom pub URL, etc.

It'd be nice to roll this in, no?

CC @mit-mit @sigurdm

**Comment by mit-mit** [comment]
Too late for 2.2; that is going out today. But, yes we should bring this over.

**Comment by sigurdm** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/94380

**Comment by kevmoo** [comment]
Before we close out this issue, can we do another sync? ...to grab https://github.com/dart-lang/pub/pull/2014

**Comment by sigurdm** [comment]
https://dart-review.googlesource.com/c/sdk/+/94744

**Comment by vsmenon** [comment]
Is this still open?

**Comment by kevmoo** [comment]
Fixed in 895bc90509993987d4f7106ffec9484691a6b7a8
