### ISSUE TITLE
Cannot publish to pub.dartlang

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#36039]
* Dart SDK Version (`dart --version`)

Dart VM version: 2.1.1 (Unknown timestamp) on "linux_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)

#165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Chrome and Firefox tried.

## Description:

Running `pub publish` I get this message:

```
Looks great! Are you ready to upload your package (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A45216&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
```

When I follow the link in the browser, I see a 400 error message.

```
400. That’s an error.

Error: invalid_request

Missing required parameter: redirect_uri

Learn more
Request Details

    access_type=offline
    approval_prompt=force
    response_type=code
    client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent

That’s all we know.
```

**Comment by renatoathaydes** [comment]
I've tried adding a few OAuth parameters that were missing... still no luck:

```
401. That’s an error.

Error: invalid_client

The OAuth client was not found.
Request Details

    access_type=offline
    approval_prompt=force
    response_type=code
    client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent
    redirect_uri=https://pub.dartlang.com
    scope=profile

That’s all we know.
```

**Comment by renatoathaydes** [comment]
I've upgraded to Dart 2.2.0, `pub --version` shows 2.2.0 as well... still same problem. The OAuth client used by pub seems to be misconfigured.

**Comment by natebosch** [comment]
cc @jonasfj

**Comment by jonasfj** [comment]
@renatoathaydes, can you please double check that you copied the entire URL from your terminal to the browser...

If I open `https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A45216&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email`
in my browser (I probably shouldn't let myself get phished that easily :see_no_evil:)..

I can sign-in without problems... but upon gettting redirect to `http://localhost:45216/?code=....` the browser will obviously get an error as the `pub` client on my machine is not listening to port `45216` and waiting for a call back...

Note. it's easy to only copy part of the URL out of the terminal. It's a little unfortunate that the URL is so long..

**Comment by renatoathaydes** [comment]
@jonasfj you're right... my terminal in IntelliJ highlights the link so I just clicked on it, didn't copy... but unfortunately the terminal didn't highlight the full URL.
Sorry for the trouble.
