### ISSUE TITLE
Unnecessary Flutter / Dart code inteli-sense or suggestions when adding documentation or TODOs.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36037]
_From @zoechi on February 26, 2019 13:50_

@SV27 commented on [Tue Feb 26 2019](https://github.com/flutter/flutter/issues/28483)

Hi Team,

   Whenever I put a fullstop/period (.) in my code documentation or todo comments, android studio unnecessarily showing Dart code suggestions. It is very frustrating. I need to press escape key immediately after typing Period sign (.) every time.

Attached the screenshot for your reference. I was coding for a flutter application on Mac when taking this screen shot.

<img width="639" alt="android_studio_unnecessary_suggestion" src="https://user-images.githubusercontent.com/34560264/53381587-3c5d9680-393f-11e9-8838-71520045c530.png">

_Additional Notes:_ I reported this issue in Google Issues tracker for Android Studio. But, they asked me to report this in Flutter. Here is the Google issues tracker Link : https://issuetracker.google.com/125088418

---

@jonahwilliams commented on [Tue Feb 26 2019](https://github.com/flutter/flutter/issues/28483#issuecomment-467263196)

cc @devoncarew 

_Copied from original issue: flutter/flutter-intellij#3231_

**Comment by pq** [comment]
_From @zoechi on February 26, 2019 13:51_

It's an analyzer issue that probably should go to dart-lang/sdk but I can only move within flutter/xxx.
I got the impression that such issues find the right people here as well.

**Comment by bwilkerson** [comment]
Server controls what shows up in the list, but not whether to show the completion list.

@jwren Can we control when completion is invoked?

**Comment by devoncarew** [comment]
I believe the completions that show here are all suggested from IntelliJ and the Dart plugin itself, and not analysis server suggestions.

@alexander-doroshko

**Comment by alexander-doroshko** [comment]
These completion items come from the Analysis Server. Since 'Show suggestions as you type' option is enabled by default (Settings/Preferences | Editor | General | Code Completion), you see completion list as you type, both in the source code and in comments.

It's possible to disable 'on-the-fly' completion inside comments on the Dart plugin end. If you believe the server is right I can do it. Completion inside a comment will appear on explicit shortcut only. But is the server right here?

**Comment by bwilkerson** [comment]
I'd be fine with changing server to disable suggestions inside comments (except inside references like "[Foo.]"?). It _is_ strange to have it triggered when typing non-code. That said, we'd also loose it when typing code snippets unless we special case for that as well. Doing the work in server gives us more control over how it behaves.

**Comment by scheglov** [comment]
I don't think that these completion suggestions are from DAS.

![image](https://user-images.githubusercontent.com/384794/53442299-da904180-39bd-11e9-89b0-c799826ab2fb.png)

And DAS (patched out to return no completions ever anywhere):
```
1551211112516 <= {"id":"44","result":{"id":"12"}}
1551211112517 <= {"event":"completion.results","params":{"id":"12","replacementOffset":941,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[],"includedElementKinds":[],"includedSuggestionRelevanceTags":[]}}
```

**Comment by alexander-doroshko** [comment]
@scheglov Completions in this example come from the server, and they appear on-the-fly as you type:
![image](https://user-images.githubusercontent.com/4499789/53470995-5a78e300-3a74-11e9-8909-4f416eb0a099.png)

Completion in your example comes from IntelliJ platform, but it doesn't appear as you type. It shows up only when explicitly invoked using a completion shortcut. I think that's fine.

So I see 2 solutions for this issue: disable completions in comments on the server end (except in special code blocks) or disable auto-popup in comments on the IDE end (show on shortcut only). Or both :).

**Comment by bwilkerson** [comment]
My preference would be to fix it in server so that we can provide completions in references (and maybe code blocks).

**Comment by scheglov** [comment]
@alexander-doroshko True, in a comment at the very end of a file DAS gives completion suggestions. I think I have already seen this fact before, but have not fixed it.

**Comment by SV27** [comment]
any update on when the fix is available for us ?

**Comment by alexander-doroshko** [comment]
@scheglov Friendly ping. We keep getting [user complaints](https://youtrack.jetbrains.com/issue/WEB-40705).

**Comment by scheglov** [comment]
I still don't have time to work on this :-(

**Comment by pq** [comment]
Chiming in here, there is a bug in server that provides completions at the end of a file but I think what people are being tripped up by is the more common case where they are seeing completions in API doc comments.  For example:

![image](https://user-images.githubusercontent.com/67586/65623163-0be4e600-df7c-11e9-8877-1644c13e3db7.png)

I just looked again w/ @scheglov and confirmed that these results are **_not_** coming from server.

/cc @alexander-doroshko

**Comment by pq** [comment]
Looking a little closer, I wonder if these completions aren't coming from the `BASIC` completion type that `DartServerCompletionContributor` is extending?  Is there maybe a way to short-circuit those proposals in the comment body case?

**Comment by alexander-doroshko** [comment]
@pq Completions on your screenshot indeed come from IntelliJ Platform, not from Analysis Server and Dart plugin. And that's totally fine as this completion list doesn't show up automatically as you type. Only on *explicit* Ctrl+Space.

The problem described in this issue (server-based completion in the last comment in a file) **is** a problem because completion popup appears without Ctrl+Space, just on typing.

**Comment by pq** [comment]
Got it.  Thanks for the clarification @alexander-doroshko. 👍

**Comment by bwilkerson** [comment]
I believe that this has been fixed other than for the special case where the comment is at the end of the file, which is being tracked in a different issue, so I'm closing this.
