### ISSUE TITLE
Kernel need way to specify what other kernel files it requires to load

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#36032]
E.g. https://github.com/dart-lang/sdk/issues/35866 is likely caused by a mis-match between the expected and actual platform loaded.
If the dill file knew - for instance - a checksum of the platform it assumed, we could check that the expected and actual platform was the same and discard if it isn't.

**Comment by a-siva** [comment]
issue #37043 and all the issues marked as duplicate in that issue seem to be related. Considering the number of times we seem to have run into this issue I am marking this as p1-high

**Comment by dgrove** [comment]
@kmillikin - can you please take a look, as this is happening frequently on version upgrades?

**Comment by dgrove** [comment]
The plan is to suppress this warning for D24 - CL is out here: https://dart-review.googlesource.com/c/sdk/+/104825

**Comment by jensjoha** [comment]
Temporary fix landed as 5eff2a0374cb89e335c138889c5125b48d12894d.

**Comment by kmillikin** [comment]
The warning should be disabled for compiling against an app that includes an outdated platform.  Somehow fixing the underlying issue is getting moved to the next Dart release.

**Comment by johnniwinther** [comment]
@jensjoha Is there more work left here?

**Comment by jensjoha** [comment]
Well, it haven't exactly been fixed with a list of checksums for other required dills, but for the platform specifically it should have been fixed with https://github.com/dart-lang/sdk/issues/41802 --- let's say that's good enough.
