### ISSUE TITLE
Unit test variants for UI as code should be deleted

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36045]
The following classes should be deleted once spread and control flow collection tests are enabled by default:

- [x] NonErrorResolverTest_WithSpread (https://dart-review.googlesource.com/c/sdk/+/94348)
- [x] ReachableFlowTest_SpreadCollections (e94e797d7b65bae5e036161c6ad62a7894a07a82)

**Comment by stereotype441** [comment]
@MichaelRFairhurst please add additional classes to this bug if you wind up creating additional similar unit tests.

**Comment by srawlins** [comment]
These tests do not exist any more.
