### ISSUE TITLE
prefer_contains false positive

### ISSUE THREAD

**Issue by sma** [dart-lang/sdk#36042]
This code snippet triggers a false _"Use contains instead of indexOf"_ analyzer hint as I'm using `next` inside the while loop and therefore `contains` is no option.

```dart
while ((next = text.indexOf('{', last)) != -1) {
  ...
}
```

Dart version: `Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"`

**Comment by srawlins** [comment]
CC @pq

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1456
