### ISSUE TITLE
Analyzer should warn when using UI as code features with an SDK constraint that does not guarantee support

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36046]
Similar to #36024 but for the "UI as code" feature

**Comment by stereotype441** [comment]
The latest information I have from the Dart scrum team is that the first version of Dart with "UI as code" features enabled will be 2.2.2, so we should implement the warning so that it fires if the user's SDK constraint includes versions prior to 2.2.2.

If we change our minds and decide to ship 2.2.2 without "UI as code" features enabled by default, we can update the warning accordingly before doing so.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/96837

**Comment by stereotype441** [comment]
Fix was reverted in 0f4a208c3ea2ba8ac5c91a227177a8eab53d9f05

**Comment by stereotype441** [comment]
Fix was re-landed in 495c319574843fa83e9c474961cf51498a0d874a

**Comment by lrhn** [comment]
I would prefer if we do not release significant new features in point-releases of the SDK.
The UI-as-code features are scheduled for Dart 2.3. Can we keep them behind a flag until then?
Or at least until a 2.3.0-rc1?

**Comment by bwilkerson** [comment]
This issue being closed only means that when the experiment is enabled that analyzer will tell users if their SDK constraints are not high enough. The experiment is not enabled by default in analyzer; that will happen when it happens everywhere else.

**Comment by lrhn** [comment]
Ah, makes sense. Carry on! :)
