### ISSUE TITLE
Analyzer gets precedence wrong with bitwise negation (~) on a list element

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36055]
Given the following code:

```
void main() {
  final x = <int>[123];
  x[0] = ~x[0];
}
```
dartanalyzer (with `strong-mode: implicit-casts: false` in `analysis_options.yaml`) complains:

> error • A value of type 'dynamic' can't be assigned to a variable of type 'int' at test.dart:3:10 • invalid_assignment

If I modify the assignment to `x[0] = ~(x[0]);` then the analyzer complaint disappears.  According to the [operator table](https://www.dartlang.org/guides/language/language-tour#operators), `[]` should have higher precedence than `~`.

I'm presuming that this is a bug with the analyzer and not with the VM since running the code and printing `x[0]` produces the expected result.

----

* Dart SDK Version: Dart VM version: 2.2.0-dev.2.1.flutter-0f9a5198bd (Tue Feb 26 09:30:32 2019 +0000) on "linux_x64".  I've also tested with 2.1.0 and get the same result.

* Whether you are using Windows, MacOSX, or Linux (if applicable): Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): N/A

**Comment by eernstg** [comment]
This is a bug. We have the following derivation from `<expression>` to `~x[0]`, so `~x[0]` _is_ an expression and that's what is required as the right hand side of an assignment:

```
expression -*->
unaryExpression -->
prefixOperator unaryExpression -->
'~' unaryExpression -->
'~' postfixExpression -->
'~' primary selector -->
'~' identifier assignableSelector -*->
'~' identifier unconditionalAssignableSelector -*->
'~' 'x' '[' expression ']' -*->
'~' 'x' '[' '0' ']'
```

One thing to note, however, is that the precedence tables ([here](https://www.dartlang.org/guides/language/language-tour#operators) and [in the language specification](https://github.com/dart-lang/language/blob/097c90a3302dc66aaf7c96d7200f35e12a4173be/specification/dartLangSpec.tex#L16045)) are not normative, so the precise answer must be determined from the grammar rules.

**Comment by eernstg** [comment]
Checking on a fresh (7829012e6176f1290fd0f3311a80da69889c9f2a) set of tools and several older ones (even a very old 1.10.1 `dartanalyzer`), I can't get the errors you mention for the example program. This seems to imply that it only occurs under Flutter.

**Comment by DanTup** [comment]
I guess this isn't specific to `~` since it seems to have come up at https://github.com/flutter/devtools/issues/529 with a minus:

```dart
  MyList a = new MyList();
  double b = -a[0];
```

**Comment by bwilkerson** [comment]
@danrubel This sounds like it might be a parser issue.

**Comment by efortuna** [comment]
This will show up on our I/O demo and is therefore fairly high priority to fix

**Comment by danrubel** [comment]
@bwilkerson I added [several more parser tests](https://dart-review.googlesource.com/c/sdk/+/99362) and it does not look like a parser issue. 

I've confirmed what was mentioned at the top of the issue...
the analyzer does not report any errors with this code 
```
void main() {
  final x = <int>[123];
  x[0] = ~x[0];
}
```
until the following is added to the `analysis_options.yaml` file
```
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by bwilkerson** [comment]
@efortuna Would you be able to work around the issue by removing the `implicit-casts: false` setting from your analysis options file?

**Comment by efortuna** [comment]
yeah, we actually worked around it by parenthesizing the expression, but it looks a little dumb :-) we can do the implicit-casts change insetad

**Comment by DanTup** [comment]
The parens may be a better temporary fix, to avoid disabling the implicit-cast check for the whole project. When I tested it, I got lints about unnecessary parens though!

**Comment by munificent** [comment]
I spent a little time looking into this because I couldn't believe our parser would get the precedence wrong. It's not a precedence thing.

In checker.dart:

```dart
  void visitPrefixExpression(PrefixExpression node) {
    if (node.operator.type == TokenType.BANG) {
      checkBoolean(node.operand);
    } else {
      _checkUnary(node.operand, node.operator, node.staticElement);
    }
    node.visitChildren(this);
  }
```

When it calls `_checkUnary()`, the static element for the `~` node is null. I think that's because in element_resolver.dart:

```dart
  void visitPrefixExpression(PrefixExpression node) {
    Token operator = node.operator;
    TokenType operatorType = operator.type;
    if (operatorType.isUserDefinableOperator ||
        operatorType == TokenType.PLUS_PLUS ||
        operatorType == TokenType.MINUS_MINUS) {
      Expression operand = node.operand;
      String methodName = _getPrefixOperator(node);
      DartType staticType = _getStaticType(operand, read: true);
      MethodElement staticMethod =
          _lookUpMethod(operand, staticType, methodName);
      node.staticElement = staticMethod;
      ...
```

The call to `_getStaticType()` on the index operand eventually calls:

```dart
DartType getReadType(Expression expression) {
  if (expression is IndexExpression) {
    return expression.auxiliaryElements?.staticElement?.returnType;
  }

  ...
```

The `auxiliaryElements` property is null. That in turn causes the `staticMethod` to evaluate to null, which causes the `staticElement` of the `~` node to be null.

Then back in the error checker, it treats that as meaning the `~` has type dynamic and then reports an implicit cast from dynamic error.

I don't know what `auxiliaryElements` is or why it's null here. Wrapping in parentheses avoids this issue because then it doesn't go into that `expression is IndexExpression` branch in `getReadType()`. Instead it uses `expression.staticType`, which is correctly filled in for the parentheses node.

**Comment by srawlins** [comment]
This has been fixed.
