### ISSUE TITLE
Stop closing issues simply.

### ISSUE THREAD

**Issue by User0-0** [dart-lang/sdk#36051]
There are many issues which are just simply closed without resolving issues.
Here are a couple of them,
#1410
#4019 
I don't think I wanted to list all of them.

**Comment by srawlins** [comment]
Looks like those were both closed on June 3, 2015. I agree that they should have been closed with a documented reason, but I suspect this was a one-off bug-closing event. Perhaps we _have_ stopped closing issues simply?

**Comment by srawlins** [comment]
Actually, I think this is the day we migrated from Google Code to GitHub. There are ~20k bugs closed on that day, including the oldest bugs: https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3C2015-06-04+sort%3Acreated-asc

I'm guessing bugs which used to have the label "closed-not-planned" were auto-closed. I would definitely open a new bug for the ones which you still want, which were closed without explanation, and link to the old one. (But search existing issues first, I know I've seen that "_" issue lying around...)

**Comment by kevmoo** [comment]
In general we try to provide reasons. As @srawlins has done above.

**Comment by User0-0** [comment]
@srawlins So, where do i need to open these issues?
In [Language](https://github.com/dart-lang/language/issues/) or [SDK](https://github.com/dart-lang/sdk/issues/)?

**Comment by srawlins** [comment]
Hmm, I think the capitalization issue would be opened on sdk/, and your other issue is already opened on language/ as https://github.com/dart-lang/language/issues/204.
