### ISSUE TITLE
Add (temporary) support for flutter_web in analysis server assists

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36056]
Imagine everything is the same except `package:flutter` -> `package:flutter_web`.

The source is not public yet, but I can provide more context via email

CC @devoncarew @scheglov

**Comment by bwilkerson** [comment]
More details would be good. Like what kind of assists you want and whether there's anything different about the package. It might be as simple as adding an "or" when looking to see which package various classes are defined in.

**Comment by kevmoo** [comment]
> More details would be good.

I had a discussion with @devoncarew about this already. Put this here mostly for tracking.

**Comment by devoncarew** [comment]
I believe the package APIs would be identical. The package implementations would have differences, and the APIs might diverge at the dart:ui level?

I think we'd want the same assists, refactorings,  and outline supports available for `package:flutter_web` as we have today for `package:flutter`.

**Comment by kevmoo** [comment]
> I believe the package APIs would be identical. The package implementations would have differences, and the APIs might diverge at the dart:ui level?

That's the goal. There may be some issues with the exact same types coming from the exact analogous path – we'd need to validate that

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/95283

**Comment by kevmoo** [comment]
Saw that this landed at 3124125008f1e3e68f269fd529b8ae4bfbc79eeb – what's
the next step?

**Comment by scheglov** [comment]
I need to actual implement choosing one or another package.
It would be useful if I could access `flutter_web` for testing.

**Comment by kevmoo** [comment]
> I need to actual implement choosing one or another package.
> It would be useful if I could access `flutter_web` for testing.

Done!

**Comment by scheglov** [comment]
Seems to work with https://dart-review.googlesource.com/c/sdk/+/95484

![image](https://user-images.githubusercontent.com/384794/53830030-66621a80-3f36-11e9-9012-703c1b7fb950.png)
