### ISSUE TITLE
pkg:meta: add @internal (or @packageInternal?) annotation and associated warning

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36058]
Used to annotate a declaration in a `lib/src` directory of a package that should not be exported by that package or any other and that should not be exposed (via return type, parameter type, field/property type, etc) of any other public (non-internal) member of the library.

Tools, such as the analyzer, can provide feedback if

* the annotation is associated with a declaration outside the `lib` directory or in the `lib` directory, but not under `lib/src` of a package
* the annotation is associated with a declaration that is exported by a library under `lib`, but not under `lib/src`
* the annotation is associated with a declaration that is exposed (via return type, parameter type, field/property type, etc) of any other public (non-internal) member of the library
* the annotation is associated with a non-public library member 
* the annotation is associated with a declaration that is not used

**Comment by kevmoo** [comment]
CC @srawlins – seems the type of thing you'd like

**Comment by srawlins** [comment]
Matan has requested this as https://github.com/dart-lang/sdk/issues/28066.

I would like to implement this now that analyzer can determine if two libraries are in the same package.

**Comment by bwilkerson** [comment]
Closing as a duplicate.
