### ISSUE TITLE
dartanalyzer --format machine produces a lot of duplicate rows

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#36062]
To reproduce the issue: download `analyzer` `0.35.2` sources and update it to use [pedantic](https://www.dartlang.org/guides/language/analysis-options#default-google-rules-pedantic). Run `dartanalyzer --format machine lib/` with `Dart SDK 2.2.0` on it.

This generates `1443845` lines, with a lot of duplicates, after deduplication it is only `7094` lines.

Related `pana` issue: https://github.com/dart-lang/pana/issues/517

**Comment by stereotype441** [comment]
@pq this sounds like it's related to analyzer_cli, which I believe you have some familiarity with.  Would you mind having a look?

**Comment by pq** [comment]
Sure thing.  Happy to take a look 👍

**Comment by pq** [comment]
This reproduces on HEAD.  It looks like the non-machine error formatter uses a Set to collect errors which does the de-duping.  I'm not clear on why the dups are getting there in the first place though? Investigating...  Maybe @bwilkerson has insights in the meantime?

**Comment by pq** [comment]
Interesting datapoint, I don't see dups if I'm analyzing a single file.  If the file is imported by another, I see duplicates.

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/95360.
