### ISSUE TITLE
int, double, and String have inconsistent capitalization

### ISSUE THREAD

**Issue by User0-0** [dart-lang/sdk#36068]
Just opening a new issue for an old closed issue #1410.
I think int, double, bool and other data type names should be Capitalized since they are just classes, or at least the `String` class should be `string` to match with other basic data types.

**Comment by kevmoo** [comment]
I'm also a BIG fan of consistency, but the ship for these types has sailed. It's not worth the breaking . change to the ecosystem.

**Comment by User0-0** [comment]
@kevmoo So, you waited until I opened that issue again, can't you just said it in #36051. Do you get any rewards for closing issues? Thinking of adding this issue too in #36051.

**Comment by User0-0** [comment]
Still not satisfied.

**Comment by User0-0** [comment]
Can this issue be let open?
So we can hope that all classes will be Capitalized one day.
