### ISSUE TITLE
InstanceMirror.setField fails to set List to List<int> in Dart 2.2.0

### ISSUE THREAD

**Issue by rootext** [dart-lang/sdk#36073]
The following code fails in Dart 2.2.0 with error "type 'List\<dynamic>' is not a subtype of type 'List\<int>' of 'value'":
```dart
import 'dart:mirrors';

class A {
  List<int> list;
}

main() {
  List value = [0,1];
  final obj = reflect(new A());

  final setField = (obj, value) { obj.setField(#list, value); };
  setField(obj, value);
}
```
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "windows_x64"

It works in Dart 2.0.0 and in 2.1.0.

Is it fixed issue or regression?

**Comment by matanlurey** [comment]
This is an intentional (fix) of Dart 2: https://github.com/dart-lang/sdk/issues/35611

**Comment by rootext** [comment]
@matanlurey, thank you for extremly fast response. sorry for disturbing. will fix my code.
