### ISSUE TITLE
dart2js: Design new reified type representation for dart2js

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#36085]
The current type representation, based around JavaScript constructors and lists of type arguments, has many problems. It is hard to extend, much too slow, allocates too many objects, and represents type relationships as functions which is code-size inefficient. We need a new representation that addresses the following needs:

- Represents nullable and non-nullable types.
- Has an efficient `is` and `as` operations, especially for the implicit `as T` of method parameters that are covariant due to a generic type parameter.
- Has an efficient subtype test.
- Allows deferred loading analysis to separate the type representation from the constructor function (and methods) so that the code of classes can be placed in a deferred loading part even when the type is used in the main part.

The new representation will likely involve canonicalized reified type objects, caching of decisions, and specialization to primitive and common types.

#13843

**Comment by jodinathan** [comment]
why was this closed?

**Comment by jodinathan** [comment]
why was this closed?
maybe new stuff incoming? :D :D

**Comment by rakudrama** [comment]
@jodinathan The new reified type representation has been designed and implemented. Perhaps I should have said that :-)
