### ISSUE TITLE
New protocol to inspect analysis server state at code completion time

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#36083]
I would like the ability to ask analysis server

1. What is the current code completion context (eg declaration)?
2. What types (if any) do we expect next?
3. Which types have been resolved for variable _n_ tokens coming before the cursor?

This will give other completion ranking mechanisms (such as ML) a better ability to model analysis server state.

**Comment by bwilkerson** [comment]
An alternative that we should consider is to add a more general protocol to generate the training data itself rather than data that would be used to build the training data. I think this would give us more flexibility in terms of the data we produce without adding instability to the protocol.

**Comment by lambdabaa** [comment]
> An alternative that we should consider is to add a more general protocol to generate the training data itself rather than data that would be used to build the training data. I think this would give us more flexibility in terms of the data we produce without adding instability to the protocol.

I like this idea a lot! If we went for this alternative, another parameter I would ideally like in addition to the ability to specify the number of lookback tokens is a filter for which tokens should be included. That would, for instance, allow the caller to optionally ask server to throw away everything except for keywords, identifiers, and literals.

**Comment by bwilkerson** [comment]
I think the decision about how much control to give the client and how much to hard code in server is an interesting one. It makes sense to me to have options for things that we want to be able to vary for testing purposes, and both number of lookback tokens and which tokens to include seem reasonable.

If we're thinking about experimenting, though, we should structure the protocol to ask for all the interesting variants in a single call. It will be much more efficient to produce all of the variants after analyzing a file one time than to have to analyze a file once per variant.

**Comment by lambdabaa** [comment]
> If we're thinking about experimenting, though, we should structure the protocol to ask for all the interesting variants in a single call. It will be much more efficient to produce all of the variants after analyzing a file one time than to have to analyze a file once per variant.

That's a good point and there's also no reason that a filter or limit couldn't be applied client-side.

**Comment by bwilkerson** [comment]
> ... no reason that a filter or limit couldn't be applied client-side.

No, but doing so requires that we pass enough information back to allow the client to decide how to filter or limit. Seems to me that filtering and limiting might be easier to do on the server side. It would also require the client to understand the data format, which would mean one more piece of code to keep coordinated if we want to change it.

**Comment by lambdabaa** [comment]
WIP server protocol patch: https://dart-review.googlesource.com/c/sdk/+/95100

**Comment by lambdabaa** [comment]
This is fixed, thanks!
