### ISSUE TITLE
org-dartlang-debug:synthetic_debug_expression:1:1: Error

### ISSUE THREAD

**Issue by kevin-ma** [dart-lang/sdk#36091]
I got an error on my mac, what i did is just hot reload project after coding a sub widget, i tried to find out what is wrong, just like run AS instead of vc code, clean cache, and restart mac...please get my some idea, thank you~

dart : 2.2.0
flutter: 1.2.1

here is the log:
```
Launching lib/main.dart on iPhone XR in debug mode...

Compiler message:
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_debugCanPerformMutations'.
_debugCanPerformMutations
^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_debugCanPerformMutations' isn't defined for the class 'RenderViewport'.
 - 'RenderViewport' is from 'package:flutter/src/rendering/viewport.dart' ('file:///Users/makw/flutter/packages/flutter/lib/src/rendering/viewport.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_debugCanPerformMutations'.
_debugCanPerformMutations
^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_semanticsConfiguration'.
_semanticsConfiguration
^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_semanticsConfiguration' isn't defined for the class 'RenderViewport'.
 - 'RenderViewport' is from 'package:flutter/src/rendering/viewport.dart' ('file:///Users/makw/flutter/packages/flutter/lib/src/rendering/viewport.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_semanticsConfiguration'.
_semanticsConfiguration
^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by shrugs** [comment]
seems related to #35980 

I fixed by

1. delete all watched variables, breakpoints
2. flutter clean
3. VSCode's "Reload Window"

**Comment by DanTup** [comment]
@shrugs I added a comment to the other issue https://github.com/dart-lang/sdk/issues/35980#issuecomment-470436036 about logging. If you can reproduce this and provide the Flutter Run and Observatory logs, that might help understand what happened.

**Comment by DanTup** [comment]
Actually, I saw these errors while looking into https://github.com/Dart-Code/Dart-Code/issues/1507

It seems like we get this error when trying to `evaluateInFrame` for some frames. It's reproducible with Observatory:

![screenshot 2019-03-07 at 2 39 13 pm](https://user-images.githubusercontent.com/1078012/53964283-efb84f00-40e6-11e9-8040-bfb122d92944.png)

The IDE doesn't know which expressions in the Watch window are valid for any given frame, we just have to send them to the VM. However it seems to write these message sometimes when they're not valid.

**Comment by a-siva** [comment]
@DanTup are you reloading when you get this error? If it is a valid error as 'func' probably was removed do you want it to silently ignore the error?

**Comment by DanTup** [comment]
> are you reloading when you get this error?

No, no reloading. I was just trying to evaluate the expression at every level of the stack. I expected it to fail on some (where there is no `func` in scope), however based on the original message at the top here, this is being written to Flutter Run's stdout/stderr rather than only being responded to over the VM Service.

It seems like a similar issue to https://github.com/flutter/flutter/issues/18574 which was fixed by @aam in https://github.com/flutter/flutter/pull/18703. When the debugger is sending expressions to evaluateInFrame, we don't want errors showing up anywhere except in the VM Service call response, since otherwise the console just fills up with errors if they have anything in the watch window (since most expressions are only valid for certain locations of frames).

**Comment by DanTup** [comment]
(Observatory was probably a bad example, since I guess you'd expect to see the error spat out there.... lemme repro in VS Code and post back some more notes...)

**Comment by DanTup** [comment]
Ok, I did some more digging. My comment above is slightly incorrect - it's not the same as the previous issue, it does not occur during normal stepping. However, there's definitely something weird going on.

- Launch flutter_gallery
- Hit a breakpoint
- Add an expression `foo` to the Watch window... it will show an error (only in the Watch window)
- Remove the expression from the Watch window
- Full Restart
- error appears in Flutter's stdout

So it seems like during a Hot Restart, it's compiling expressions that were previously evaluated by the Watch window (evaluateInFrame), and writing all of their errors to stdout. I'm not sure why it's kept hold of those expressions.

Even stranger, is after completely terminating my debug session and starting again, I see errors from expressions evaluated in previous debugging sessions (!).

Might these be being kept around somewhere?

**Comment by a-siva** [comment]
Could these watch expressions be saved on the IDE side? I presume when you say you are terminating your debug session and starting again you don't mean detaching and attaching back to the same engine process but actually starting a brand new session which would be a new engine process.

**Comment by DanTup** [comment]
> Could these watch expressions be saved on the IDE side? 

I don't believe so - I added and removed the watch expression, and I didn't see anything in the logs to suggest we'd re-sent them to the VM. I'm as confused as you though, I can do some more testing next week.

>  I presume when you say you are terminating your debug session and starting again you don't mean detaching and attaching back to the same engine process but actually starting a brand new session which would be a new engine process.

That is correct, the app was completely terminated. That's why I wondered if they might be somehow stored somewhere. I'll do more testing, and also see if I can repro using the command line + Observatory too.

**Comment by aam** [comment]
@DanTup are you able to repro this with VSCode?

**Comment by DanTup** [comment]
Yep, I can repro in VS Code doing this:

- Run the flutter_gallery app and hit a breakpoint somewhere
- Add `foo` to the watch window
- Delete `foo` from the watch window
- Click the Stop button on the debug toolbar
- Start a new debug session

I can even restart VS Code, and continue to see them when launching.

**Comment by aam** [comment]
@DanTup but what do you observe after `Start a new debug session` ? I am not seeing anything wrong after I delete `foo` from watch window, stop, start. What should I be looking for?

**Comment by DanTup** [comment]
I see a load of red text like in the top-most comment here showing that `foo` is invalid in the Debug Console. It builds up, so after testing a few times, when I next run I see lots and lots of them. When you added `foo` to your watch window, was it invalid (eg. caused an error in the watch window?), and were you at a breakpoint? I was testing on my MacBook using the iOS simulator.

Note: VS Code 1.32 that was released yesterday has a serious bug that breaks a lot of the Flutter debugger; I don't know whether it effects this (I tested it before the upgrade), but I hope they'll have a fix out for that early next week.

**Comment by aam** [comment]
Thanks @DanTup . I got the repro by stopping at a breakpoint, adding a `foo` watch, removing it, continuing execution, hot reloading. When I hot reload I see `foo`-related compiler errors showing up in debug console.
I think it's related to https://dart-review.googlesource.com/c/sdk/+/91747 that landed few weeks ago.

cc @jensjoha

**Comment by ride4sun** [comment]
```
16:18:08.544 1601 info flutter.tools [        ] org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'requestList' isn't defined for the class 'FirestoreProvider'.
16:18:08.544 1602 info flutter.tools [        ]  - 'FirestoreProvider' is from 'package:elm_bluetooth_bloc/resources/firestore_provider.dart' ('elm_bluetooth_bloc/lib/resources/firestore_provider.dart').
16:18:08.544 1603 info flutter.tools [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'requestList'.
16:18:08.546 1604 info flutter.tools [        ] requestList
16:18:08.546 1605 info flutter.tools [        ] ^^^^^^^^^^^
```

I got the same problem. Deleting Breakpoints and variables and restart did not help 
After than a flutter clean worked. I get the problem quite often....

**Comment by robertonic** [comment]
Is there a fix for this? It makes hot reloading unreliable.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/96406 with the fix. It should land into dart sdk first, which then should be rolled into the engine/flutter.

**Comment by Mp5A5** [comment]
> seems related to #35980
> 
> I fixed by
> 
> 1. delete all watched variables, breakpoints
> 2. flutter clean
> 3. VSCode's "Reload Window"

good job

**Comment by robertonic** [comment]
Mp5A5, that doesn't help me much. 

Using IntelliJ the error **re-appears after a small and apparently random number of hot reloads.** It's a very slow cycle to keep running "flutter clean" and then rebuild and rerun the code.

**Comment by a-siva** [comment]
The CL has been rolled into Flutter, can this issue be closed

**Comment by robertonic** [comment]
>> https://dart-review.googlesource.com/c/sdk/+/96406 with the fix. It should land into dart sdk first, 
>> which then should be rolled into the engine/flutter.

How do I update flutter to use this fix?

**Comment by ride4sun** [comment]
> The CL has been rolled into Flutter, can this issue be closed

What is the ETA to get an update on Flutter with this?

**Comment by aam** [comment]
The fix landed on flutter master channel: https://github.com/flutter/flutter/commit/a29906d5f552f2984daf9bef569b7fe1295e1c70
