### ISSUE TITLE
TouchEvent.supported fails on Chromebooks, Surface, etc. after Chrome v70+

### ISSUE THREAD

**Issue by MurrayLS** [dart-lang/sdk#36092]
* Dart SDK Version: 2.0.0
* Windows/ChromeOS, possibly MacOS
* Chrome, possibly Edge

Chrome [released an update](https://www.chromestatus.com/feature/4764225348042752) that disables the touch API by default on devices classified as Desktop devices.

This prevents devices (particularly modern Chromebooks, Surface Pros) that would typically allow TouchEvent interactions from using them despite having support. Web applications check for TouchEvent availability through TouchEvent.supported, however this method:

```
static bool isEventTypeSupported(String eventType) {
    // Browsers throw for unsupported event names.
    try {
      var e = new Event.eventType(eventType, '');
      return e is Event;
    } catch (_) {}
    return false;
}
```

currently returns false on Chrome. Would it be possible to add other additional logic for checking whether touch devices are supported, possibly using the suggestions in the link above?

Additionally, it's possible that a similar problem occurs on Edge, based on the note in above  link that Edge has implemented a similar change. I do not have access to a suitable device to test this on, however.

**Comment by sigmundch** [comment]
@terrylucas - can you take a look?

**Comment by peterjosling** [comment]
Any updates on this? This is causing us issues.

**Comment by terrylucas** [comment]
I'll take a look.

**Comment by terrylucas** [comment]
Changing TouchEvent.supported and PointerEvent.supported should fix the problem. Is this what you're looking for?

```
  static bool get supported {
    if (window.navigator.maxTouchPoints > 0) {
      bool hasTouchEvent = JS('bool', '!!window.TouchEvent');
      if (hasTouchEvent) {
        try {
          var e = new TouchEvent('touches');
          return e is TouchEvent;
        } catch (_) {}
      }
    }
    return false;
  }
```

 ```
 static bool get supported {
    if (window.navigator.maxTouchPoints > 0) {
      bool hasTouchEvent = JS('bool', '!!window.PointerEvent');
      if (hasTouchEvent) {
        try {
          var e = new PointerEvent('pointerover');
          return e is PointerEvent;
        } catch (_) {}
      }
    }
    return false;
  }

```

**Comment by peterjosling** [comment]
Yup, that looks great to me!

**Comment by peterjosling** [comment]
Actually, strike that, PointerEvent.supported shouldn't check for maxTouchPoints, PointerEvent can be supported without a touchscreen.

The maxTouchPoints check in TouchEvent.supported is also potentially slightly confusing - a browser (e.g. Chrome on my workstation) can support TouchEvents but not have a touchscreen (so maxTouchPoints is zero). I'd suggest removing the maxTouchPoints check from both and leaving it to any clients if they want to check navigator.maxTouchPoints to detect the presence of a touchscreen.

**Comment by peterjosling** [comment]
I've also just realised navigator.maxTouchPoints isn't supported in Safari.

**Comment by terrylucas** [comment]
Peter,

I don't believe I sent you my pending CL
<https://dart-review.googlesource.com/c/sdk/+/108521/1/sdk/lib/html/dart2js/html_dart2js.dart>,
from a week ago - been on vacation.  PointerEvent I did not check
maxTouchPoints.  However, you are suggesting that TouchEvents.supported not
test for MaxTouchPoints?  That means we'll only check if TouchEvent can
created/used?
<https://dart-review.googlesource.com/c/sdk/+/108521/1/sdk/lib/html/dart2js/html_dart2js.dart>

  static bool get supported {
    if (window.navigator.maxTouchPoints > 0) {
      try {
        return TouchEvent('touches') is TouchEvent;
      } catch (_) {}
    }
    return false;
  }

**Comment by peterjosling** [comment]
Yes, that would match the current behaviour which doesn't check maxTouchPoints, it just checks if the TouchEvent interface exists.

For most cases I'd imagine this is the intention - just checking if `TouchEvent` can be created before you try and bind any event listeners.

**Comment by terrylucas** [comment]
CL submitted https://dart-review.googlesource.com/c/sdk/+/108521

**Comment by peterjosling** [comment]
Thanks!

**Comment by AndrewLugg** [comment]
This fix has worked on Chromebooks and Surface for us, but it has now broken iOS 9.3.5 with Safari which report it doesn't support touch.
