### ISSUE TITLE
Cascade notation does not work in short hand if

### ISSUE THREAD

**Issue by orbli** [dart-lang/sdk#36107]
* Dart SDK Version (`dart --version`)
**dart 2.1.0**
* Whether you are using Windows, MacOSX, or Linux (if applicable)
**Windows**
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A (flutter)

I faced the problem in flutter but it is too large to display;
instead I built a minimal code snippet at codingground.

```
var x = new List<String>()..insert(0,"a");
x = x[0] == "a" ? x..clear() : x..insert(0,"b");
print(x);
```
![image](https://user-images.githubusercontent.com/6440599/53785790-a637fa80-3f54-11e9-9145-efeb7a4e31e2.png)

**Comment by tatumizer** [comment]
That's how the precedence of cascade operator is defined vs ?:
The fix: extra parentheses
```x = x[0] == "a" ? (x..clear()) : (x..insert(0,"b"));```

To verify that it's a problem of precedence, try this:
```
var x = ["a"], y = ["b", "c"];
x[0] == "a" ? x: y..clear(); // clear acts on x, not on y!
print(x.length); // 0
print(y.length); // 2
```
