### ISSUE TITLE
BigInt.toDouble() produces Infinity instead of -Infinity on large negative values.

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#36105]
`BigInt.toDouble()` fails to convert large negative values to `-Infinity`. Instead, it produces `Infinity` for both positive and negative values. A small repro:

```dart
void main() {
  BigInt positive = BigInt.from(10).pow(309);
  BigInt negative = -positive;
  print(positive.toDouble()); // Correctly produces `Infinity`.
  print(negative.toDouble()); // Incorrectly produces `Infinity` instead of `-Infinity`.
}
```

This breaks constant folding in `dart2js` and may cause issues elsewhere. (Confirmed this behavior for the VM and `dart2js` backends; unsure about others.)

`Dart VM version: 2.2.0-dev.2.1+google3-v2.2.0.dev.2.1 (google3) on "linux_x64"`

**Comment by lrhn** [comment]
Well spotted. The `bigint_patch.dart` file contains an overflow check:
```dart
if (length - 53 > maxDoubleExponent) return double.infinity;
```
which forgets to account for sign.
