### ISSUE TITLE
compilation error: RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/sdk#36102]
This occurred when I started about 15 copies of the same Flutter test in the background and on Linux. Not something I ordinarily do; trying to track down an unrelated intermittent failure.

00:02 +0: loading /usr/local/google/home/hansmuller/github/flutter/packages/flutter/test/rendering/editable_test.dart                                                               
Compiler message:
Warning: Tried to initialize from a previous compilation (file:///usr/local/google/home/hansmuller/github/flutter/packages/flutter/build/testfile.dill), but couldn't.
Error message was 'RangeError (index): Index out of range: no indices are valid: 0'.
Stacktrace included '#0      Uint8List.[] (dart:typed_data/runtime/lib/typed_data_patch.dart:2177:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:426:17)
#4      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:489:14)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:138:36)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:115:20)
<asynchronous suspension>
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:46:44)
<asynchronous suspension>
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:340:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#18     _rootRun (dart:async/zone.dart:1120:38)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async/runtime/lib/timer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
'.
This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///tmp/initialize_from.dillLUQWCS/initialize_from.dill.gz in your error
report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

**Comment by HansMuller** [comment]
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/2928027/initialize_from.dill.gz)

**Comment by aam** [comment]
thank you @HansMuller .  Attached initialize_from.dill being empty, more than likely what happened was that the dill file that was getting ready to be read by one flutter test instance was overridden by another test instance.

 cc @jensjoha

**Comment by midastouch365** [comment]
how do I solve this issue?

**Comment by jensjoha** [comment]
@midastouch365 this shouldn't be a problem that you have per say: It's a warning and everything should still be fine, although the startup time (i.e. compilation time) will be a little slower.

If everything is not fine you're having a different problem.
If the warning appears every time you run, that's somewhat of a different problem as well.

**Comment by midastouch365** [comment]
@jensjoha You're right. I think my problem is a little different from the one above. I refreshed my computer, and creating a new flutter app. When I tried running it, this error message shows up:

Launching lib/main.dart on iPhone Xʀ in debug mode...
Finished with error: FileSystemException: Cannot open file, path = '/Users/busayoadebayo/Desktop/flutter/bin/cache/artifacts/engine/darwin-x64/isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)

**Comment by jensjoha** [comment]
That seems like a flutter-specific problem to me. You should probably file a bug at https://github.com/flutter/flutter/issues.

**Comment by midastouch365** [comment]
@jensjoha ok thanks. I've filed a report

**Comment by a-siva** [comment]
This appears to be another case of #36032

**Comment by a-siva** [comment]
Closing as a corresponding Flutter issue has been filed.
