### ISSUE TITLE
Implicit downcasts off leads to unintuitive dynamic downcast errors

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36115]
Take this error:

```
The return type 'dynamic' isn't a 'AbstractDirective', as defined by the method '_matchDirectiveByElement'
```

This type of error makes more sense for named classes than for `Object`/`dynamic`/`void`. A `Person` is not a `Car`, or even a `NamedPerson`, but, it seems weird to say a `dynamic` isn't an `AbstractDirective`. It also seems weird that my dynamic code isn't assignable to my typed code because that's what makes dynamic...dynamic.

As an experienced dartisan I know why this occurs but new users would probably be better served by an error along the lines of:

```
Error: dynamic values cannot be returned in functions with declared non-dynamic return types.
```

or

```
Error: dynamically typed code is being passed into a statically typed location without a cast.
```

We may also want to consider if disabling implicit downcasts for the purposes of NNBD should allow downcasting dynamic. We could add something like `--strict-dynamic-casts` for power users, and in that case, while I'd probably still prefer a better error message, we could probably rely on those power users being able to figure it out.

I don't think this error is an issue for wrapped types, ie,

```
the return type 'List<dynamic>' isn't a 'List<AbstractDirective>' as defined by...
```

but I'm curious if anyone sees a wider problem than I do here, or a good generalized solution.

**Comment by srawlins** [comment]
As this mode is deprecated, I'm going to close this for now; anyone can re-open if they think there is still a problem to address here.
