### ISSUE TITLE
Improve Lambda autocomplete 

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36112]
_From @feinstein on March 5, 2019 8:11_

having something like:

```
myStream.stream.listen()
```

won't autocomplete into a lambda, which does work for Java and is very handy.

_Copied from original issue: flutter/flutter-intellij#3254_

**Comment by pq** [comment]
_From @feinstein on March 5, 2019 8:25_

/cc @alexander-doroshko

**Comment by pq** [comment]
_From @alexander-doroshko on March 5, 2019 8:34_

@feinstein I'm not the right person.
Code completion is powered by the Dart Analysis Server from the Dart SDK. So usually code completion issues are tracked in https://github.com/dart-lang/sdk/issues/, label: `area-analyzer`. No actions needed, I think Flutter plugin developers will move the issue there if they want to.

BTW I think the issue description could be improved so that developers understand what you do, what you expect and what you get instead.

**Comment by pq** [comment]
Thanks for the triage @alexander-doroshko!

@feinstein: I'll move this one over.  Cheers for the report!

**Comment by scheglov** [comment]
Yes, I'd like to see this feature as well.
It was also [requested for Flutter](https://github.com/dart-lang/sdk/issues/35884).

I have some work in progress, but it is not complete and should be generalized to not only named arguments, and not in a separate completer (probably).
https://dart-review.googlesource.com/c/sdk/+/95481

**Comment by pq** [comment]
@scheglov: is this PR abandoned?

**Comment by scheglov** [comment]
Yeah, I started doing additional refactorings to argument completions, and tests. It was taking too much time, and I had more urgent work, so I put this on hold.

**Comment by pq** [comment]
@scheglov: do you mind if I pickup where you left off or do you want me to hold off for you to pick this up again?

**Comment by scheglov** [comment]
Sure, you own it now :-)

**Comment by pq** [comment]
Implemented w/ e0c178b.
