### ISSUE TITLE
RTE on function with typed argument in signature called from JS

### ISSUE THREAD

**Issue by aaronstgeorge-wf** [dart-lang/sdk#36114]
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"

We have a case where a one argument function transitively called from JS throws a run time exception if the function signature includes a non-`dynamic` type, but works with a `dynamic` type. A cast to the expected type doesn't fail, so the type appears to be correct.

The following code is dart 1 and 2 compatible and reproduces the bug: [gist of issue](https://gist.github.com/aaronstgeorge-wf/f8d2c3e69044156a65f42b3bae860331). Sorry that it's not all that minimal, boiling the problem down and still getting the bug to reproduce proved very difficult. It works fine in Dart 1 in DDC and dart2js, in Dart 2 it fails with a RTE in DDC and doesn't work but doesn't throw an RTE in dart2js (i.e. nothing is printed).

looking into the compiled JS it seems like if the the DDC (dart 2) compiled code looks like this:

```js
        _.ref = dart.fn(ref => {
          core.print(dart.runtimeType(ref));           // printing run time type 
          ref = foo$.FooComponent.as(ref);             // cast
          core.print(dart.dsend(ref, 'method', []));   // calling method
        }, dynamicToNull());
```
everything works.

If it looks like this:
```js
        _.ref = dart.fn(ref => {
          core.print(dart.runtimeType(ref));       // printing run time type 
          ref = ref;                               // cast
          core.print(ref.method());                // calling method
        }, FooComponentToNull());
```
it fails. Not sure if that's helpful.

May also be related: when the function signature is explicitly typed the `runtimeType` printed inside the function is `NativeJavaScriptObject` rather than what we expect; when the function signature is dynamically typed it appears correct.

**Comment by aaronstgeorge-wf** [comment]
FYI: @greglittlefield-wf

**Comment by vsmenon** [comment]
If you still have the repro handy, could you include the code for `foo.over_react.g.dart`?

**Comment by jakemac53** [comment]
@vsmenon I moved this to D24 as it looks like it is blocking for some users, and would likely block internal users as we migrate to ddk as well

**Comment by vsmenon** [comment]
The date of the bug suggests pre-DDK DDC.  Do we know for sure?

**Comment by jakemac53** [comment]
Oh, true. I based that on this comment https://github.com/dart-lang/sdk/issues/36912#issuecomment-491889737, but maybe I misunderstood and it was a newer Dart SDK that broke them?

In any case it does sound like thiss is still a problem in DDK.

**Comment by seanburke-wf** [comment]
`foo.over_react.g.dart` should be generated by the builders from `over_react`. That said, we recently had some insight on this issue: we have some interop wrapping that conditionally happens in `react`, but due to the change in the type system where `dynamic` is no longer bottom, that condition (which checks the arity of the `ref` callback) is failing and the interop wrapping doesn't occur, causing this issue. We believe this particular issue is no longer valid.

**Comment by vsmenon** [comment]
Thanks - I'll close this one.  (Showing the generated files often makes it faster for us to triage by inspection.)
