### ISSUE TITLE
MapEntry needs to have a public constructor

### ISSUE THREAD

**Issue by aryzhov** [dart-lang/sdk#36130]
I am making my own implementation of Map which will expose the index of the map entry. In fact, I am storing map entry objects and I'd like to return these objects in the `entries()` iterator. It would be optimal for my map entry object to extend `MapEntry` but I found that it's impossible due to its private constructor:

```dart
class MapEntry<K, V> {
  final K key;
  final V value;
  const factory MapEntry(K key, V value) = MapEntry<K, V>._;
  const MapEntry._(this.key, this.value);
  ...
}
```
I can't see the reason behind the private constructor here, considering that all fields of this class are final. My proposal is to make a public constructor and eliminate the factory constructor as it's redundant.

* Dart 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

**Comment by lrhn** [comment]
The class was made to not have a public generative constructor to prevent anyone from using it as a superclass. That allows us to later change the class, perhaps move the implementation to a separate class and keep the interface public. We could have done that from the start (public interface class, private implementation), but it wasn't necessary. We still want to reserve the option.

It's an exceedingly simple class, so it should be easy to implement (two final fields is all). Having a class with state that you can both extend and implement may cause some users to extend it, even if they will be overriding the state.

**Comment by aryzhov** [comment]
An interface/implementation solution would be the right way to go. I was not suggesting that because it would be a breaking change. I still don't understand the rationale behind this design. If you do decide to break it up into interface/implementation, it would be a breaking change, and you don't want to open up the constructor in order to not introduce a breaking change in the future. Essentially, you are saying that only the Dart team can extend this class, limiting other efficient 3rd party Map implementations.

Your  statement regarding the ability to extend and implement is also puzzling. Yes, Dart does not have pure interfaces and there's no way to describe that this class should be immutable. That's the limitation of the language. Perhaps, that capability needs to be added to the language. Workarounds like this set a really bad example for developers to follow.

**Comment by aryzhov** [comment]
I want to add some code to help us get on the same page:

### Option A: Public constructor
This is what I am proposing.
```dart
class MapEntry<K, V> {
  final K key;
  final V value;
  MapEntry(this.key, this.value);
}
```
### Option B: Interface / implementation
This is the right thing to do, but it would be a breaking change.
```dart
abstract class MapEntry<K, V> {
  K get key;
  V get value;
}
class _SimpleMapEntry<K, V> extends MapEntry<K, V> {
  final K key;
  final V value;
  _SimpleMapEntry(this.key, this.value);
}```

### Option C: Extensibility without a breaking change 
I think this is the option you were referring to in your last comment.
```dart
class MapEntry<K, V> {
  K key;
  V value;
  MapEntry(this.key, this.value);
}
```
I don't see any other ways to change the implementation to achieve extensibility. We can rule out B as a breaking change. If you ever want to go with C, you can do it after doing A. Therefore, there's no harm in doing A.

**Comment by aryzhov** [comment]
I found another option, which would achieve extensibility without a breaking change and compromises.

### Option D: Interface with default implementation
```dart
abstract class MapEntry<K, V> {
  K get key;
  V get value;
  factory MapEntry(K key, V value) => SimpleMapEntry<K, V>(key, value);
  MapEntry.create();
}
class SimpleMapEntry<K, V> extends MapEntry<K, V> {
  final K key;
  final V value;
  SimpleMapEntry(this.key, this.value): super.create();
}
```
This is more complex than A, but would be a breaking change is A is implemented. The `create()` constructor is a bit cumbersome, but I could live with it if it's properly documented.

**Comment by mraleph** [comment]
@aryzhov you can just do

```dart
class MyMapEntry<K, V> implements MapEntry<K, V> {
  final K key;
  final V value;
  final int index;
  MyMapEntry(this.key, this.value, this.index);
}
```

Any reason you don't want to go this way? In Dart you can *implement any class* because each class acts as an interface.

**Comment by aryzhov** [comment]
Oh, that clarifies it. Thank you! Closing this issue.

**Comment by aryzhov** [comment]
Thank you, Slava. I don't know how I didn't think of that.
