### ISSUE TITLE
Spread collection test failures.

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#36142]
I approved some test failures related to spread collections:
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-release-simdbc64/5216
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-release-x64/4433
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-product-x64/2584

I'm not totally sure what the culprit CL is or who to assign this bug to. Grid suggests [this](https://dart-review.googlesource.com/c/sdk/+/95708), but that seems unrelated. I know this stuff is in active development, so this is mostly just an FYI. Feel free to close if you're aware of the failures.

**Comment by munificent** [comment]
Thanks for approving. These tests are expected to fail since the feature is still being implemented.
