### ISSUE TITLE
DDC missing correct type check

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36158]
This looks like a nasty regression - the following isn't throwing in DDC (but is in DDK) and is printing false:

```dart
void main() {
  List<int> l = [1, 2, 3].where((x) => x.isEven).map((x) => x + 1);
  print(l);
  print(l is List<int>);
}
```

It was working correctly as recently as `2.2.0-dev.1.1`.

**Comment by vsmenon** [comment]
@nshahan - can you take a look?  It's possible it's a recent analyzer change giving us the wrong type.  The generated code for that example is checking against `Iterable<int>` not `List<int>` on the assignment to `l`.  

fyi @jmesserly @stereotype441

**Comment by nshahan** [comment]
@vsmenon Yes, I'll dig in now.

**Comment by vsmenon** [comment]
Thanks!  In `reify_coercions.dart`, there is a call to `ast_properties.getImplicitCast(node)` - may want to sanity check what type we're getting there on this example.

**Comment by vsmenon** [comment]
@stereotype441 - as discussed offline, we tracked to a CL by @scheglov .  Will you folks be able to fix soon?  This is a pretty nasty regression (soundness bug).

fyi - @jmesserly

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/97143 should fix it.

There may be a related (but distinct) issue in _findCovariantChecksForMember, for finding covariant parameter type checks. I haven't tried to reproduce it yet.

It's not entirely obvious to me how to fix that one. I think it needs to be modified to use InheritanceManager2 (which has the nice side effect that it should run faster), but I'm not sure if there's a simple way to do that.
