### ISSUE TITLE
DDC: Dynamic function calls are too hard to debug

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#36165]
Here is a very simple example (I wish we had DDC-Pad ready):

```dart
void main() {
  // NoSuchMethodError: method not found: 'call'
  // Receiver: Instance of '(String) => void'
  // Arguments: []
  Function.apply(arity1, []); 
}

void arity1(String name) {}
```

Notice, it does not:

* Have the _name_ of the method. Here is it straight forward, but the actual code I'm debugging it is a nested function passed down to me, and there are a lot of functions in the app that match the definition I'm trying to debug.

* Actually say what is wrong.

## Test Suite

Here is a test suite I put together and tried on DDC and Dart2JS and the standalone Dart VM. DDC unfortunately was the worst of the 3 (even though I assume it has more information than Dart2JS?):

```dart
import 'package:test/test.dart';

void main() {
  test('should call fine statically', () {
    expect(() => funcWith1StringArg('Matan'), returnsNormally);
  });

  test('should call fine dynamically (Dynamic call)', () {
    expect(() => (funcWith1StringArg as dynamic)('Matan'), returnsNormally);
  });

  test('should call fine dynamically (Function.apply)', () {
    expect(
      () => Function.apply(funcWith1StringArg, ['Matan']),
      returnsNormally,
    );
  });

  // Expected to fail.
  test('should fail gracefully (Dynamic Call)', () {
    expect(() => (funcWith1StringArg as dynamic)(), returnsNormally);
  });

  // Expected to fail.
  test('should fail gracefully (Function.apply)', () {
    expect(
      () => Function.apply(funcWith1StringArg, []),
      returnsNormally,
    ););
  });
}

void funcWith1StringArg(String name) {}
```

## Results

> `test('should fail gracefully (Dynamic Call)', () {`

DDC: 

* No name
* No description of the failure

```
NoSuchMethodError: method not found: 'call'
Receiver: Instance of '(String) => void'
Arguments: []
```

Dart2JS: 

* Name is partially there (`__funcWith1StringArg$closure(...).call$0`)
* Description of the failure is misleading (`is not a function`)

```
JsNoSuchMethodError:<NoSuchMethodError: method not found: 'call$0'
(F.function_call_error_test__funcWith1StringArg$closure(...).call$0 is not a function)
```

DartVM:

* Name is there!
* Description of the failure is correct! Woohoo!

```
NoSuchMethodError: Closure call with mismatched arguments: function 'funcWith1StringArg'
Receiver: Closure: (String) => void from Function 'funcWith1StringArg': static.
Tried calling: funcWith1StringArg()
Found: funcWith1StringArg(String) => void
```

> `test('should fail gracefully (Function.apply)', () {`

DDC: 

* No name
* No description of the actual failure

```
NoSuchMethodError: method not found: 'call'
Receiver: Instance of '(String) => void'
Arguments: []
```

Dart2JS:

* Name is there!
* No description of the actual failure

```
NoSuchMethodError: method not found: 'call'
Receiver: Closure 'funcWith1StringArg'
Arguments: []
```

DartVM:

* Name is there!
* Description of the failure is correct! Woohoo!

```
NoSuchMethodError: Closure call with mismatched arguments: function 'call'
Receiver: Closure: (String) => void from Function 'funcWith1StringArg': static.
Tried calling: call()
Found: call(String) => void
```

/cc @vsmenon @jmesserly 
/cc @sigmundch as well. The Dart2JS errors are better, but not great, even in `-o0`.

**Comment by vsmenon** [comment]
@matanlurey - this is awesome bug report (even if the bug isn't awesome) - thanks!

We may also want to gently hint typing the function call.

**Comment by vsmenon** [comment]
@nshahan - what's the status on this?  We may want to file a separate bug to better record function names.  Is there anything more here that's reasonable for D24?

**Comment by nshahan** [comment]
I'm looking at what it would require to tag a name for all dynamic calls right now. I'll close this issue and open one for getting the names in the failure messages. If I make progress on it then it might make it in before D24 but it's not blocking.
