### ISSUE TITLE
Breaking change request: Add ECMAScript 2018 regular expression features to the RegExp interface

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#36171]
# Intended Change

We will make the following modifications to the `RegExp` interface:

* Add two named argument, `unicode` and `dotAll`, to the `RegExp` constructor. The first signals that the given pattern is a Unicode pattern. The second changes the behavior of '.' to match line terminators as well.
* Add the `isUnicode` property that tells whether a given `RegExp` pattern will be treated as a Unicode one.
* Add the `isDotAll` property that describes whether '.' in the given RegExp will match line terminators.
* Convert uses of `Match` in the `RegExp` interface to `RegExpMatch`, a subinterface that contains methods for working with named groups.

`RegExpMatch` extends the `Match` interface with the following method and property:

* `String namedGroup(String name)` - Retrieves the matched String (if any) for the given named capture group. (This is the named capture group analogue to `String group(int index)`.)
* `Iterable<String> groupNames` - Contains a sequence of names corresponding to the  named capture groups in the originally matched pattern. (This is the named capture group analogue to `int groupCount`.)

# Justification

This change is part of work to address #34935. Currently, `dart2js` allows the following RegExp features due to compiling down to JavaScript, while the Dart VM does not:

* [Lookbehind](https://github.com/tc39/proposal-regexp-lookbehind)
* [Named capture groups](https://github.com/tc39/proposal-regexp-named-groups) and named back references
  * Note: `dart2js` does *not* currently support retrieval by name from Match objects, only by their implicit index.

Supporting these features in the Dart VM to bring it to parity with `dart2js` do not require changes to the `RegExp` interface. However, it is a reasonable expectation by users that matches for named capture groups could be retrieved by name, and to allow that for both the Dart VM and `dart2js`, we must either change the interface or require downcasting the returned `Match` objects to `RegExpMatch` manually.

The third feature, [Unicode property group escapes](https://github.com/tc39/proposal-regexp-unicode-property-escapes), is not currently supported by either `dart2js` or the Dart VM since it is only supported by JavaScript for Unicode patterns (regular expressions with the `/u` flag). However, we have seen multiple requests for allowing Unicode property group escapes, and to fulfill those requests, we must also add support for Unicode patterns. Otherwise we might change the semantics of existing RegExp patterns, due to the permissive nature of BMP patterns with features like identity escapes. (This is why Unicode property group escapes are only allowed in Unicode pattern mode in JavaScript.)

While we are making modifications to the interface, we should go ahead and support the other regular expression feature added in ECMAScript 2018, [the dotAll flag](https://github.com/tc39/proposal-regexp-dotall-flag) (`/s`).

# Expected Impact

The expected impact is minimal, since only implementers of the RegExp interface would be affected, such as the `JSSyntaxRegExp` classes in `dart2js` and `dartdevc`. Since we are only adding properties, named arguments, and changing return values to subtypes of the currently expected type, current code using `RegExp` objects would not be affected.

**Comment by mit-mit** [comment]
cc @matanlurey @Hixie @dgrove for approval

**Comment by sstrickl** [comment]
Also @lrhn given prior discussion with him about these changes.

**Comment by matanlurey** [comment]
Assuming this has no additional cost for Dart2JS LGTM for me.

**Comment by sstrickl** [comment]
One reasonable question, while we're adding the Unicode pattern flag, is whether we also want to add the [dotAll](https://github.com/tc39/proposal-regexp-dotall-flag) flag as well, which was introduced into ECMAScript at the same time as lookbehind, named groups and unicode property escapes. @lrhn, I think you've mentioned this flag before in our conversations, any thoughts here? If we ever want to support it, now would definitely be the time while we're already changing the interface anyway.

(This would not change the expected impact, since again it's only additions to the API.)

**Comment by lrhn** [comment]
I agree, we should prepare the `dotAll` flag as well, both as constructor argument and as boolean getter. 

While Dart web developers can't use it yet because it requires a flag (and inline flags are not enabled yet), there is no reason to not port that particular feature of JS RegExps when we port the rest.

(We should also check if there are any other JavaScript RegExp features that are at the [Draft or Candidate stages](https://tc39.github.io/process-document/), and prepare for those).

**Comment by sstrickl** [comment]
Well, it can be used as a global flag on the pattern as well, not just an inline flag, so Dart users will be able to use it.

I've altered the issue description to add the new constructor named parameter and property, and also adjusted the title of this issue to better reflect what we're doing now.

**Comment by lrhn** [comment]
Dart users cannot *currently* use the `dotAll` flag because there is no way to specify it for a Dart RegExp 
That means that we don't have a discrepancy between the capability of Dart-on-VM and Dart-on-JS, neither can use the flag. 

The pattern syntax-only features can be used in Dart-on-JS as soon as they are enabled in the browser.

(I don't think inline flags are enabled in browsers yet, at least they aren't in Chrome, but when they are, we should probably be ready to enable them in Dart as well to avoid platform discrepancies).

**Comment by sstrickl** [comment]
Ohhhh, yes. Sorry, I totally misunderstood your comment, but now that I have read it correctly, unfortunately that mean that Dart-on-JS (when running on v8) _can_ currently use dotAll, because unlike the Unicode pattern flag, it can be turned on via inline flag manipulation. (The 's', 'i', and 'm' flags can be turned on inline in v8.)

Which means we should definitely add it, so that we don't have Dart-on-JS people using that workaround because they can't get the functionality on a global level.

Actually, given this, would it make sense for patterns passed to RegExp on Dart-on-JS to at least be required to pass the same parser as the VM, even if that pass is thrown away, to ensure that the Dart-on-JS versions aren't using features unsupported by the VM? This would definitely add overhead and I doubt we'd want to do it, but it's unfortunate that we have this mismatch.

(I don't see any proposals in the tc39 repo involving PCRE-style inline flags, so it doesn't look like that's being suggested yet as a standardized thing.)

**Comment by lrhn** [comment]
Agree, I have also not found anything suggesting that inline-mode-flags is on track to become an ECMAScript feature. It's a feature that you can enable with a command-line flag, so potentially it could be used in some node.js scripts, but it's not on the web and not something dart2js code can accidentally use.
I don't think inline modes is something we need to worry about at the current time.

**Comment by lrhn** [comment]
I have only been able to fine one case of a class implementing `RegExp` outside of the Dart platform libraries, the [package `multi_reg_exp`](https://pub.dartlang.org/packages/multi_reg_exp), which has not been updated to Dart 2.0. This change is unlikely to break existing Dart 2.0 code.

**Comment by Hixie** [comment]
I have no opinion here. I think long term we probably want to create a new type of `Pattern` that is more similar to Perl6's patterns than regexps, but that's neither here nor there really.

**Comment by dgrove** [comment]
This change LGTM - getting web and VM as close as possible is critical.

**Comment by sstrickl** [comment]
Landed in 5ebb640.

**Comment by sstrickl** [comment]
Reopening due to revert in 9238e253055b0028, checking into issue that caused revert now.

**Comment by sstrickl** [comment]
Relanded in 4028fec3b56703752
