### ISSUE TITLE
integrate kernel constants with inference and ssa

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36178]

**Comment by sigmundch** [comment]
update: Johnni started working on the integration with global inference (see https://dart-review.googlesource.com/c/sdk/+/97240)

**Comment by johnniwinther** [comment]
update: CFE constants are integrated in inference and ssa but work is still needed to fully support platform code with the new constants. This work (see https://dart-review.googlesource.com/c/sdk/+/97634) has already shown some bugs but more may come.

**Comment by sigmundch** [comment]
current status: Johnni tested enabling CFE constants on on the bots and believes most backend work is done.Only one issue with native typed arrays showed up, which he'll investigate tomorrow.

**Comment by sigmundch** [comment]
@johnniwinther - do you believe there is anything else to do on the dart2js side? Can we close this issue?

**Comment by johnniwinther** [comment]
We're done.
