### ISSUE TITLE
CFE is mis-lowering Map to Iterable in BlockExpression

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36173]
For example, a statement like `print(<int, int>{...map});` results in kernel output like:

```
    core::print( block {
      final core::Map<core::int, core::int> #t1 = <core::int, core::int>{};
      for (final core::MapEntry<core::int, core::int> #t2 in map)
        #t1.{core::Map::[]=}(#t2.{core::MapEntry::key}, #t2.{core::MapEntry::value});
    } =>#t1);
```

This explodes since map (ForIn.iterable) isn't iterable. Should this be map.entries instead?

**Comment by vsmenon** [comment]
fyi - @kmillikin.  Not sure if this is a known issue.

**Comment by kmillikin** [comment]
There's a missing call to the getter Map.entries.  Proposed fix [here](https://dart-review.googlesource.com/c/sdk/+/96780).
