### ISSUE TITLE
add js number semantics to kernel constants

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36179]
* [x] add tests for number semantics (in progress)
* [x] add evaluation logic to CFE constant evaluator

**Comment by sigmundch** [comment]
current status: @fishythefish  has been working on the first item (tests for js-number semantics). Most tests are out for review at this time (more than 20 CLs!)

**Comment by sigmundch** [comment]
current status: @fishythefish has an implementation of the semantics in the CFE evaluator and will be sending out a CL shortly

**Comment by sigmundch** [comment]
CL: https://dart-review.googlesource.com/c/sdk/+/98240

**Comment by dgrove** [comment]
Can this be closed now, @sigmundch and @fishythefish ?
