### ISSUE TITLE
support kernel transformers in ddc

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36174]
DDC needs to support kernel transforms for the Flutter Widget inspector.

For the DDC itself, I think we need to be able to invoke `dartdevc` with a list of kernel transforms to apply.

@jmesserly @jakemac53 @jacob314

**Comment by vsmenon** [comment]
@jacob314 - do you have a pointer to the flutter xform for the Inspector?

**Comment by jacob314** [comment]
https://github.com/flutter/engine/tree/master/flutter_kernel_transformers/lib
One file, 600 lines.
You may want to also glance at 
https://github.com/flutter/engine/blob/master/frontend_server/lib/server.dart
which shows how the kernel transformer is integrated into the flutter engine frontend server.

**Comment by vsmenon** [comment]
Thanks!

General q for this bug: do we need to expose ddc as a package a la

https://github.com/flutter/engine/blob/master/frontend_server/lib/server.dart#L14

?

**Comment by jmesserly** [comment]
Yeah, the Flutter SDK will need a new entry point for `dartdevc`, that passes in their additional transforms.

The hardest part is going to be this line:
```dart
import 'package:vm/frontend_server.dart' show ProgramTransformer;
```

In other words, it depends on an interface that is specific the the Dart VM. That interface is just:
```dart
abstract class ProgramTransformer {
  void transform(Component component);
}
```

We could certainly reference "package:vm" from DDC, but I'm not sure if that's a good idea. Other ideas:
- move that interface into a shared location (e.g. CFE?)
- have DDC accept a function, like `void Function(Component) transform`, and then Flutter can pass a tear-off of the transform method.
- have DDC declare a similar interface, and Flutter SDK can implement a simple adaptor.

Proposal:

1. Move most contents of `pkg/dev_compiler/bin/dartdevc.dart` into `lib/` so it's easier to call `main()`.
2. `bin/dartdevc.dart` should simply forward to the new entry point under lib.
3. Add an optional parameter for passing in Kernel transforms.
4. in `pkg/dev_compiler/lib/src/kernel/target.dart`, change `performModularTransformationsOnLibraries` to call these new transforms as needed.

I should note that steps 1-2 are not strictly necessary, as we already have `package:dev_compiler/src/compiler/shared_command.dart` and the bin script is less than 100 lines. However it might be nice so they don't need to copy the bazel worker code.

**Comment by natebosch** [comment]
+1 for accepting `void Function(Component)`.

-1 for including a `main` under `lib/`. Would prefer an interface that looks more like a library so that the `main` under `bin/` can be very simple.

**Comment by vsmenon** [comment]
Just so I'm clear, does this mean we need to publish dev_compiler separately as a package?  If so, we need to figure out how to version it / keep it coherent with the SDK (and particularly DDC SDK internals).

**Comment by jmesserly** [comment]
> -1 for including a main under lib/. Would prefer an interface that looks more like a library so that the main under bin/ can be very simple.

Ah, that's not what I meant. It should have a normal library interface. Indeed, that's exactly how DDC is already set up (the method is called `compile`). The only real issue is that bazel worker logic was added to the bin/ script, and it's collected a bit of other code since then.

> Just so I'm clear, does this mean we need to publish dev_compiler separately as a package? If so, we need to figure out how to version it / keep it coherent with the SDK (and particularly DDC SDK internals).

We absolutely *should not* publish a package. Flutter SDK builds these directly, and gets our code the same way as they get the VM (I believe they use DEPS). Think static linking at Flutter SDK build time, not pub downloading compilers onto the user's machine. :)

**Comment by vsmenon** [comment]
@jacob314 - how hard would it be to factor out the widget kernel transform into its own package?

**Comment by jacob314** [comment]
btw the widget kernel transform is the only transform in that package :)
could be easy to factor out further if we wanted.

**Comment by jmesserly** [comment]
> btw the widget kernel transform is the only transform in that package :)
could be easy to factor out further if we wanted.

We would need the following changes:
- flutter_kernel_transformers moved to its own git repository (note: it should *not* be published to pub; it is a build-time-only package)
- Flutter Engine repository pulls that package in via its [DEPS file](https://github.com/flutter/engine/blob/master/DEPS)
- Dart SDK repository pulls that package in via its [DEPS file](https://github.com/dart-lang/sdk/blob/master/DEPS)
- The code in flutter_kernel_transformers is refactored into two Dart files under lib, one which uses "package:vm" and one which does not. Flutter's frontend_server will continue to use the "package:vm" variant, DDC will use the other one.
- note: any future changes to your code in that package will require commits in 3 separate repositories (flutter_kernel_transformers, dart-lang/sdk, and flutter/engine).
- at some point in the future, revert all of this technical debt and go back to the current architecture.

Does that sound feasible to you, @jacob314 and @vsmenon ?

**Comment by jmesserly** [comment]
addendum: @jacob314 if this does sound feasible, can you sign up for this work?

**Comment by jacob314** [comment]
I may be missing something but I think it would make more sense for you to just fork flutter_kernel_transformers.dart file for now and use it directly in the DDC package. That sounds simpler than creating a bunch of technical debt to try to reuse the code when the code,

**Comment by jmesserly** [comment]
> I may be missing something but I think it would make more sense for you to just fork flutter_kernel_transformers.dart file for now and use it directly in the DDC package. That sounds simpler than creating a bunch of technical debt to try to reuse the code when the code,

Ah, interesting idea, that would be *much* easier. Are you concerned at all about potential drift between the two codebases? Or is it pretty stable?

**Comment by jmesserly** [comment]
testing https://dart-review.googlesource.com/c/sdk/+/97022 now
