### ISSUE TITLE
Analyzer considers distinct constant objects to be identical

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#36188]
Example (from #36159):
```dart
class C {
  final double x;
  const C(this.x);
}

const cp0 = C(0.0);
const cm0 = C(-0.0);

main(){
  print(identical(0.0, -0.0)); // falee
  print(0.0 == -0.0); // true
  print(identical(cp0.x, cm0.x)); // false
  print(cp0.x == cm0.x); // true
  print(identical(cp0, cm0)); // false
  print(cp0 == cm0); // false
  print(const{cp0, cm0});
}
```
The analyzer prints
```
Analyzing seteq.dart...   
  error • Two values in a constant set can't be equal at seteq.dart:16:20 • equal_values_in_const_set                                        
1 error found.         
```
for this code, which is incorrect. The `cp0` and `cm0` have distinct state, so they are not canonicalized. They also do not override `operator==`, so they are not `==`, contrary to what the analyzer says here.

**Comment by bwilkerson** [comment]
I have a CL that fixes this in analyzer (https://dart-review.googlesource.com/c/sdk/+/96840) but it breaks DDC. I don't have time right now to add the support required to keep DDC working, so I'm going to un-assign myself. If someone else wants to pick this work up before I have time to get back to it, you can use my CL as you see fit.

**Comment by srawlins** [comment]
Our behavior is unchanged.

**Comment by kallentu** [comment]
Relanded with https://github.com/dart-lang/sdk/commit/74794c81b2c63ec970781bf7865ed59d81dc8f5f. Behaviour should be changed.
