### ISSUE TITLE
Confusing analyzer error when tightening return type with abstract override

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#36191]
The following Dart code results in an analysis error:
```dart
class A {
  num getValue() => 1;
}

// error: 'A.getValue' ('() → num') isn't a valid override of 
//        'B.getValue' ('() → int').
class B extends A {
  @override
  int getValue();
}
```
This message is confusing because B is a subtype of A, and the wording implies that `A.getValue` is overriding `B.getValue`, which is backwards.

The presence of the error makes sense, since there's no concrete implementation of `getValue` that satisfies the typing declared in `B`'s override. 

However, the wording doesn't convey that well (and at first, my team and I thought that this error was some sort of analyzer bug).

---

This issue is reproducible on Dart SDK version 2.2.0

**Comment by srawlins** [comment]
Reversed methods in the message is tracked here. https://github.com/dart-lang/sdk/issues/37993

**Comment by eernstg** [comment]
@greglittlefield-wf wrote:
> ... which is backwards

Note [this comment](https://github.com/dart-lang/sdk/issues/37993#issuecomment-757976910), addressing this backwardness issue.
