### ISSUE TITLE
Collection literal error regression when using experiments

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36201]
When running with the experiment `spread-collections` or `control-flow-collections` defining a map literal but only one type does not produce an error.

```
var foo = <int>{1:2, 3:4};
```

You will get a set containing `{1, 2, 3, 4}`.

There is a test for this but I don't think the code path is being exercised without the experiment flags.
https://github.com/dart-lang/sdk/blob/master/tests/language_2/set_literals/invalid_set_literal_test.dart#L15

**Comment by nshahan** [comment]
cc @leafpetersen

**Comment by vsmenon** [comment]
@stereotype441

**Comment by bwilkerson** [comment]
I believe that this should be fixed by https://dart-review.googlesource.com/c/sdk/+/96985. It will likely produce a different error message than before, but I don't think that matters.

If that does not solve the problem you're seeing, please re-open the issue.
