### ISSUE TITLE
vmservice should not ignore exceptions when writing to the devfs

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#36202]
We've recently spent some time diagnosing a hot reload error on fuchsia. The underlying problem was: `OS: ERROR 28 no space left on device.` However, the devfs does not return a status code or error message indicating the failure. To verify this, we had to rebuild the vm_service with logging and print statements to confirm the issue.

For example, regardless of exceptions we respond with 200 OK.

https://github.com/dart-lang/sdk/blob/master/runtime/bin/vmservice/server.dart#L285

The actual failing call was in addStream from the devfs, but it wasn't caught or handled in anyway, leading to an unresponsive app.

https://github.com/dart-lang/sdk/blob/master/runtime/bin/vmservice/vmservice_io.dart#L153

https://github.com/dart-lang/sdk/blob/5721d8af6d8755fa6f70f3951de2c451c57bf12f/sdk/lib/vmservice/devfs.dart#L128

**Comment by jonahwilliams** [comment]
cc @chingjun

**Comment by rmacnak-google** [comment]
devfs should be removed. It has nothing to do with introspecting the VM, and it does not belong in the VM service.

**Comment by bkonyi** [comment]
> devfs should be removed. It has nothing to do with introspecting the VM, and it does not belong in the VM service.

@rmacnak-google should we consider removal of DevFS from the VM service rather than spend time on a fix here? What exactly relies on DevFS currently?

**Comment by bkonyi** [comment]
Friendly bump, @rmacnak-google

**Comment by bkonyi** [comment]
Do we just want to response with a generic error code and the exception message or do we want to actually return specific error codes (e.g., 507 for insufficient storage)?

**Comment by jonahwilliams** [comment]
I strongly suspect we would treat all non-200 error codes the same (toolExit), but would probably display the response text (if provided) in an error message.
