### ISSUE TITLE
SSE: dart:io's HttpResponse buffers response even when buffering is disabled

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#36207]
- Dart SDK Version: `Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"`

Server sent events (SSE) are great alternative to Websockets. They are unidirectional and work everywhere unlike Websockets which do not work dehind corporate firewalls/proxies.

It is impossible to implement SSE on the server side in Dart because messages are always buffered even when [`bufferOutput`](https://docs.flutter.io/flutter/dart-io/HttpResponse/bufferOutput.html) is set to false and `flush` is called.

Feature request: The actual flush method or some new flushXXX method that actually flushed data down the HttpResponse's wire.

Related issues:
https://github.com/dart-lang/sdk/issues/26283
https://github.com/dart-lang/sdk/issues/14953
https://stackoverflow.com/questions/19612857/eventsource-and-buffered-httpresponse

**Comment by tejainece** [comment]
This could be a false alarm. I will reopen it if i encounter it in the future.

**Comment by sortie** [comment]
Alright, be sure to reopen if there's a problem.
