### ISSUE TITLE
Missing static native methods from dart:html

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36205]
Some (maybe all) static native methods in dart:html are not available when you build with DDC but they are when you build with dart2js. 

Examples: 

Calling `Css.supports(...)` generates a runtime error:
```
NoSuchMethodError: tried to call a non-function, such as null: 'html.Css.supports'
```

Or calling `MediaRecorder.isTypeSupported(...)`
```
NoSuchMethodError: tried to call a non-function, such as null: 'html.MediaRecorder.isTypeSupported'
```

**Comment by jmesserly** [comment]
From the error message, the compiler appears to be generating a call to `html.Css.supports` rather than directly to the DOM's `CSS.supports`. Should be an easy fix.

**Comment by jmesserly** [comment]
It looks like I spotted this bug (I wasn't the original code author) from reading it and left a helpful TODO:
```dart
    // A static native element should just forward directly to the
    // JS type's member.
    //
    // TODO(jmesserly): this code path seems broken. It doesn't exist
    // elsewhere, such as [_emitAccess], so it will only take affect for
    // unqualified static access inside of the the same class.
    //
    // If we want this feature to work, we'll need to implement it in the
    // standard [_emitStaticClassName] code path, which will need to know the
    // member we're calling so it can determine whether to use the Dart class
    // name or the native JS class name.
```
It looks like I fixed it in the DDC+Kernel backend, so it only affects DDC+Analyzer.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/97262
