### ISSUE TITLE
VM: Implement "Spread Collections"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36218]
Initially these features are behind the experimental flag --enable-experiment=spread-collections.

- [x]   Support in List Literals.
- [x]   Support in Map Literals.
- [x]   Support in Set Literals. 

See:

Language tracking issue: [dart-lang/language#164](https://github.com/dart-lang/language/issues/164)
[Feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md)
https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/implementation-plan.md
PENDING Unified Collections: https://github.com/dart-lang/language/pull/200

**Comment by aartbik** [comment]
Current status of spread collections test
```
           spread            
JIT   +  175 | -   51     
AOT   +  180 | -   46  
```

**Comment by aartbik** [comment]
Looked at a few that fail seemingly after parsing.
One is due to missing type arguments, I filed:
https://github.com/dart-lang/sdk/issues/36284

**Comment by aartbik** [comment]
New status:
```
           spread
JIT   +  216 | -   42
AOT   +  213 | -   45
```

**Comment by a-siva** [comment]
The latest test results shows 7 tests crashing in the VM with the following stack trace

```
stderr:
../../runtime/vm/compiler/frontend/constant_evaluator.cc: 129: error: unimplemented code
version=2.2.1-edge.69079303cf82fd1d4f985a963164c1de793490a2 (Tue Mar 26 13:47:39 2019 +0000) on "linux_x64"
thread=7996, isolate=const_error_test_05.dart:main()(0x5624fd63c900)
  [0x00005624fbacae3c] dart::Profiler::DumpStackTrace(void*)
  [0x00005624fbacae3c] dart::Profiler::DumpStackTrace(void*)
  [0x00005624fbd9c8a2] dart::Assert::Fail(char const*, ...)
  [0x00005624fbcbe1f1] dart::kernel::ConstantEvaluator::EvaluateExpression(long, bool)
  [0x00005624fbcd8656] dart::kernel::StreamingFlowGraphBuilder::BuildVariableDeclaration()
```

**Comment by a-siva** [comment]
We also seem to have 13 RuntimeErrors (could be all related to CFE issues but each one of them needs to be evaluated)

**Comment by aartbik** [comment]
It is unclear if the constant evaluator in the VM will need to be extended to deal with block expressions or not. Right now we see something like this in the kernel file, with an unimplemented map entry in the statement block.
```
    const core::Map<dynamic, dynamic> res1 = block {
      final core::Map<dynamic, dynamic> #t1 = <dynamic, dynamic>{};
      [@vm.call-site-attributes.metadata=receiverType:dart.core::Map<dynamic, dynamic>] #t1.{core::Map::[]=}(invalid-expression "unimplemented map entry", null);
    } =>#t1;

```

**Comment by aartbik** [comment]
Checked with Kevin: VM does not need to deal with "constant" block expressions, all constants are evaluated to list constants, set constants, or map constants.

**Comment by aartbik** [comment]
This morning's status

 ```
          spread
JIT   +  295  | -   24
AOT   +  290  | -   29
```

**Comment by a-siva** [comment]
go/dart-test-results shows 4 failures (all CFE related)

- await_test [https://github.com/dart-lang/sdk/issues/36277](url)
- const_error_test[12,13,14]

If there is no more work to be done in the compilers we can close this issue, A separate issue can be opened to track the OSR optimization issue.

**Comment by aartbik** [comment]
Tracking OSR follow up in https://github.com/dart-lang/sdk/issues/36421
(this is probably more important for control flow collections than spread operators, but even those could in theory be long running)
