### ISSUE TITLE
DDC: Mixed in setter overrides of private fields are called unexpectedly during instantiation

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#36217]
In the DDC, when a mixin introduces a setter that overrides a private field, that setter is called unexpectedly during object initialization.

This seems to happen because the class is attempting to initialize the property backing that field to `null`, but ends up going through the setter instead unexpectedly.

This affects over_react, and we currently have a [less-than-ideal workaround in place](https://github.com/Workiva/over_react/blob/2.1.0+dart2/lib/src/builder/generation/impl_generation.dart#L167-L172
) for this bug. 

Reduced test case:
```dart
main() {
  // Prints "_privateVar setter called" unexpectedly.
  new C();
}

class A {
  var _privateVar;
}

mixin B on A {
  @override
  get _privateVar {
    print('_privateVar getter called');
  }
  @override
  set _privateVar(value) {
    print('_privateVar setter called');
  }
}

class C extends A with B {}
```

This happens with both the new and old mixin syntax.

This does not happen:
- in dart2js
- when the field is public
- when the setter overrides occurs via a subclass

-----

Reproducible in Dart SDK 2.2.0/2.2.1-dev.1.0

**Comment by greglittlefield-wf** [comment]
If one were to contribute a fix for this, would using `Object.defineProperty` within field initializers be an acceptable path forward?

This part of the compiler would be updated:
https://github.com/dart-lang/sdk/blob/master@%7B2019-06-18%7D/pkg/dev_compiler/lib/src/kernel/compiler.dart#L1523-L1526
which would result in the following changes to the emitted code for the above example, fixing the issue:
```diff
 main.A = class A extends core.Object {};
 (main.A.new = function() {
-   this[_privateVar] = null;
+   dart.defineValue(this, _privateVar, null);
 }).prototype = main.A.prototype;
```

I can also put up a CL if that's a better place to discuss this approach.

Coincidentally, this problem looks to be the same as the example given in the ES6 class fields proposal that led to using using `Object.defineProperty` semantics over `this.# =`.
https://github.com/tc39/proposal-class-fields#public-fields-created-with-objectdefineproperty

I think it would be nice to eventually use ES6 class fields, but converting the dev compiler over to use them seems non-trivial...

**Comment by greglittlefield-wf** [comment]
I can no longer reproduce this issue in! Closing.

The regression test case added for #44636 seems pretty similar to the one for this issue. @sigmundch Do you think it's safe to say that regression test also covers this case?

**Comment by sigmundch** [comment]
Thanks @greglittlefield-wf for following up! Indeed, yes, it does seem like that regression test would also serve for this issue after all.

**Comment by greglittlefield-wf** [comment]
Awesome, thank you!
