### ISSUE TITLE
VM: Implement "Control Flow Collections"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36214]
Initially these features are behind the experimental flag control-flow-collections.

- [x] Support new block expression AST node

See:

Language tracking issue: [dart-lang/language#165](https://github.com/dart-lang/language/issues/165)
[Feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md)
[Implementation plan
](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/implementation-plan.md)

PENDING Unified Collections: dart-lang/language#200

**Comment by aartbik** [comment]
Just for proper book-keeping, the following CL provides an initial implementation of block expressions in the Dart VM:

https://dart-review.googlesource.com/c/sdk/+/94441

This should provide a fully functional implementation to continue testing, even though it still has some issues that could be improved (e.g. for now we just disable OSR completely while running control flow collections code for simplicity; this may be unacceptable in the long run).

**Comment by aartbik** [comment]
Current status of control flow collections tests
```
             control-flow
JIT        +  190 | -   76
AOT        +  190 | -   76
```

**Comment by aartbik** [comment]
Some CFE CLs for if statements were submitted:

https://dart-review.googlesource.com/c/sdk/+/97200
https://dart-review.googlesource.com/c/sdk/+/97628

for-loops still pending:

https://dart-review.googlesource.com/c/sdk/+/97628

**Comment by aartbik** [comment]
New status
```
             control-flow
JIT         +  203 | -   63
AOT         +  186 | -   80
```

**Comment by aartbik** [comment]
Found https://github.com/dart-lang/sdk/issues/36377

**Comment by aartbik** [comment]
Also https://github.com/dart-lang/sdk/issues/36357 and https://github.com/dart-lang/sdk/issues/36356 are blocking fuzz test runs

**Comment by aartbik** [comment]
This morning's status:
```
             control-flow
JIT       +  251 | -   15
AOT       +  251 | -   15
```

**Comment by aartbik** [comment]
Probably biggest VM item left to be explored is enabling OSR points inside control flow collection for loops. Alex notes we should ensure that temporaries on the expression stack are preserved when OSR happens.

Consider a more complex expression like

 ` var x = x.bar(42, bazz(), 'abc', [more_bazz(), for (int i = 0; i < n; i++) 2*i ]);
`

In this case x, 42, bazz() and 'abc' should be on the expression stack unless CFE introduces temporary variables for them. Let's:
(1) test if the above example works;
(2) dump kernel to see how CFE generates this;
(3) print flowgraph of a function compiled for OSR and check that it loads captured values correctly.

**Comment by a-siva** [comment]
If there is no more compiler backend work left to be done on this we can close the issue, a new issue can be opened to track the OSR optimization and it will not be a blocker for the 2.3 release.

**Comment by aartbik** [comment]
Sounds good. I will do that.

**Comment by aartbik** [comment]
Tracking OSR follow up in https://github.com/dart-lang/sdk/issues/36421
Closing this, since there is no known VM work left.
