### ISSUE TITLE
Analyzer accepts potentially-const expressions in const contructor invocations

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36215]
Analyzer accepts this:

```
class C {
  Object inner;
  const C(int x) : inner = const C(x);
}
```

This should not be accepted: x is _not_ a constant expression. It is merely a _potentially_ constant expression.

Proof by contradiction:

```
var x;
print(new C(x));
```

By using `new`, `inner` cannot be initialized to a const `C` of `x`, because `x` is not const.

**Comment by srawlins** [comment]
Analyzer 2.6.0-dev.0.0 now complains about the `inner`, but still not the `x`, still a bug?

```none
$ dartanalyzer 36215.dart 
Analyzing 36215.dart...
  error • Can't define a const constructor for a class with non-final fields. • 36215.dart:3:3 • const_constructor_with_non_final_field
1 error found.
```

**Comment by eernstg** [comment]
Yes, this is still a bug (just tried with `final Object inner`, and the analyzer then reports `No issues`). 

[Here's](https://github.com/dart-lang/language/blob/51c5fd4af78ec6b6edae3862a1bdbf43f160871d/specification/dartLangSpec.tex#L8136) the requirement in the spec:

> It is a compile-time error if _a<sub>i</sub>_ is not a constant expression for some 
> _i ∈ 1..n + k_.

where _a<sub>i</sub>_ is each actual argument. So, as @MichaelRFairhurst  says, `x` in the example is a formal parameter, so it is not a constant expression, so `const C(x)` is an error.

**Comment by srawlins** [comment]
Still no static analysis.

**Comment by kallentu** [comment]
The original example (with `final` added to the field) has a cycle which is not exactly the issue here, but has been fixed by https://github.com/dart-lang/sdk/commit/1c6742689134a8d509918057bf0698f23b46b86f.

For the formal parameters, I think the following example is similar and without a cycle:
```
class D {
  final int d;
  const D(this.d);
}

class C {
  final Object inner;
  const C(int x) : inner = const D(x);
}
```

The analyzer reports `Arguments of a constant creation must be constant expressions.` for the `x` in `D(x)`.
Closing.
