### ISSUE TITLE
Analyzer: Short-circuited const code has false negatives AND positives

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36219]
```dart
void main() {                                                                    
  dynamic nonConst;                                                              
  const dynamic nil = null;                                                      
  const Object constValue = const Object();                                      
                                                                                 
  const falsePositive1 = true ? constValue : nil + 1;                            
  const falsePositive2 = false ? nil + 1 : constValue;                           
  const falsePositive3 = constValue ?? nil + 1;                                  
                                                                                 
  const falseNegative1 = true || nonConst;                                       
  const falseNegative2 = false && nonConst;                                      
                                                                                 
  print(falsePositive1);                                                         
  print(falsePositive2);                                                         
  print(falsePositive3);                                                         
  print(falseNegative1);                                                         
  print(falseNegative2);                                                         
}               
```

dartanalyzer reports:

```dart
  error • Evaluation of this constant expression throws an exception at lib/test.dart:6:46 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception at lib/test.dart:7:34 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception at lib/test.dart:8:40 • const_eval_throws_exception
```

These are false negatives. The spec regarding short-circuiting operations specifies that these expressions only require the unexecuted code to be potentially-const expressions, which does not require them to be evaluated.

There are also two false negatives, because `falseNegative` and `falseNegative2` depend on non-const expressions, but no error is reported.

CFE reports:

```
lib/test.dart:10:34: Error: Not a constant expression.
  const falseNegative1 = true || nonConst;
                                 ^^^^^^^^
lib/test.dart:11:35: Error: Not a constant expression.
  const falseNegative2 = false && nonConst;
                                  ^^^^^^^^
```

The issue is that we rely on constant evaluator to report references to non-const concepts like local variables etc. However, if we run the constant evaluator we get the runtime errors that should not be reported. Constant verifier is probably where the potentially-const expression validation should occur, however, it does not do that type of validation (and if it did, it would be duplicating work).

**Comment by bwilkerson** [comment]
Related to https://github.com/dart-lang/sdk/issues/36192.

**Comment by leafpetersen** [comment]
Just to be clear, I think the false positives here are only false positives with the *new* constant semantics that have not yet shipped.  dart2js reports errors there as well.

**Comment by lrhn** [comment]
Agree, the false-positives should still be erors until we release the update constants. Since some of these constant changes were implemented already during the Dart 2.0 phase, we are in a slightly shaky position until every platform catches up.

The false negatives are bugs. They are, always have been, and always will be (being optimisitic here) compile-time errors.

**Comment by MichaelRFairhurst** [comment]
> It's likely a regression from partially implementing the new short-circuiting const specification, and not getting all the details right.

No, these are current bugs and not related to constant_update_2018

**Comment by MichaelRFairhurst** [comment]
For post constant_update_2018 I expect the situation to be:

```
void main() {                                                                    
  dynamic nonConst;                                                              
  const dynamic nil = null;                                                      
  const Object constValue = const Object();                                   
                                                                                 
  const falseNegative1 = true || nonConst;                                       
  const falseNegative2 = false && nonConst;  
  const falseNegative3 = true ? constValue : nonConst;
  const falseNegative4 = false ? nonConst : constValue;                                      

  print(falseNegative1);
  print(falseNegative2);
  print(falseNegative3);
  print(falseNegative4); 
} 
```

I'm not sure about

```
  const maybeFalsePositive = constValue ?? nil + 1;      
  const maybeFalseNegative = constValue ?? nonConst;      
```

@leafpetersen @eernstg @lrhn can you confirm what the desired behavior here is?

**Comment by lrhn** [comment]
Desired (aka. specified and required) behavior:
```dart
void main() {                                                                    
  dynamic nonConst;                                                              
  const dynamic nil = null;                                                      
  const Object constValue = const Object();                                   
                                                                                 
  const falseNegative1 = true || nonConst;  // compile-time error
  const falseNegative2 = false && nonConst;  // compile-time error
  const falseNegative3 = true ? constValue : nonConst;  // compile-time error
  const falseNegative4 = false ? nonConst : constValue; // compile-time error                                     

  const maybeFalsePositive = constValue ?? nil + 1;  // OK, evaluates to constValue   
  const maybeFalseNegative = constValue ?? nonConst;   // compile-time error.   
} 
```
The rule here is that the non-taken branch of a short-circuit operator in a const expression must be *potentially constant*. The `nonConst` variable is not a constant variable, so referencing it is not a potentially constant expression. 
The `nil + ` expression is potentially constant because both `nil` and `1` are, and it type checks because the type of `nil` is `dynamic`. It's never evaluated, so there is no run-time error (at compile-time).

**Comment by srawlins** [comment]
In Dartanalyzer 2.5.0, there is exactly one error with the above code, on `falseNegative4`: 

> Const variables must be initialized with a constant value.

There are also many dead_code hints, e.g. in `true || nonConst`, `nonConst` is marked as dead code. dart2js correctly reports "Error: Not a constant expression" where @lrhn indicated, on lines 6, 7, 8, 9, and 12.

**Comment by srawlins** [comment]
I'm going to close this as complete. Now the analyzer reports errors at the declarations of `falseNegative1` and `falseNegative2` (so they are no longer false negatives).
