### ISSUE TITLE
Summaries do not distinguish between types inferred from initializers and types inferred from class hierarchy

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36210]
Consider this code (adapted from `AmbiguousSetOrMapLiteralBothTest.test_setAndMap`):

```dart
Map<int, int> map;
Set<int> set;
abstract class A {
  Map<int, int> get m1;
}
class B extends A {
  var m1 = {...set, ...map};
  var m2 = {...set, ...map};
}
```

Note that the initializers for both `m1` and `m2` both try to mix sets and maps, so this is erroneous code.  But we still want to be able to give the user helpful error messages about it.  In particular, for `m1`, we want to assume the literal is a map (due to the downward context from class `A`), so we want to issue an error just at the site of the spread of `set`.  Whereas for `m2`, we want to issue an error for the entire literal, since there is no contextual information available to resolve the ambiguity.

That currently doesn't work, because during summary generation, both `m1` and `m2` are assigned the type `Map<int, int>` (the former because it overrides `A.m1`, the latter because we arbitrarily resolve ambiguous set/map literals to be maps if no other information is available).  Then, during analysis of the file, the type `Map<int, int>` is used as the downward inference context, so both `m1` and `m2` are analyzed identically.

This is currently getting in the way of my implementing summary support for spread collections.  In the long term, it would be nice it summaries could contain enough information to distinguish between types inferred from initializers (as in `m2`) and types inferred from overrides (as in `m1`) so that we could avoid this problem altogether.

Cc @scheglov, who is working on a replacement implementation for summaries.

**Comment by leafpetersen** [comment]
> the type `Map<int, int>` is used as the downward inference context, so both `m1` and `m2` are analyzed identically.

Just a quick comment based on little context, but this seems a priori dangerous.  Are you sure you're not potentially changing results by having a possible incorrect downwards type?  I'm thinking something like this:

```dart
T foo<T>(T x) {
  print(T);
  return <int, int>{} as T;
}

void main() {
  var x = {...foo("hello" as dynamic)};
}
```

where having a downwards type changes the inferred type argument to `foo`, and causes a downcast which wasn't there originally.

**Comment by stereotype441** [comment]
@leafpetersen Agreed that it's a priori dangerous, which is why I filed this bug.  For the short term we've altered the behavior so that ambiguous set/map literals get `dynamic` as their inferred type; so far in all the cases I've found this is sufficent to avoid a user-visible problem.  We intend to come back and do a more thorough fix as part of @scheglov's rework of summaries.

**Comment by srawlins** [comment]
I'm closing this as stale since there is a new implementation of summaries. If we re-discover the bug in the new format, that can be a new issue.
