### ISSUE TITLE
VM: Implement support for constants being evaluated by front end

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36220]
This is the tracker issue for implementing support in the VM for constants being evaluated by the front end

- [x] Implement support in JIT mode
- [ ] The bytecode compiler currently implements constant expression evaluation, with CFE doing it that becomes redundant
- [ ] The AOT pipeline implements constant expression evaluation as a kernel to kernel transformation, with CFE doing it that becomes redundant

Language tracking issue: https://github.com/dart-lang/language/issues/60
Frontend implementation tracking issue: https://github.com/dart-lang/sdk/issues/35079

**Comment by aartbik** [comment]
I marked us both as owner for now. Alex probably wants to do the bytecode side. I can help with the other stuff after consulting with Alex.

**Comment by dgrove** [comment]
Any updates on this issue?

**Comment by aartbik** [comment]
I am not aware of blocking VM work. For JIT, we could eagerly evaluate the constants in the constant table (which becomes larger) to reduce compile-time. For AOT, I don't think anything is not working, and removing code would be just a cleanup. I let Alex comment on bytecode status.

**Comment by a-siva** [comment]
I think this issue can be taken off from the 2.3 milestone list, it is more for clean up work to remove the redundant constant expressions evaluation code from the AOT and bytecode paths once CFE has solid support for constant expressions evaluation.

**Comment by aartbik** [comment]
Lazy constant reading has been submitted. Items and ideas to follow up on:

(1) by setting the raw-bytes array and hash map from the start, we may be able to completely avoid the "pending" and "delayed" data structures; we should be evaluate every constant when needed first
(2) by peeking into pragma's we may avoid the cyclic detector altogether
(3) removed unused code and data structures when this stabilizes

**Comment by aartbik** [comment]
Approved fails to follow-up on:

```
| vm-kernel-precomp-obfuscate-linux-release-x64 | language_2/const_inference_test | RuntimeError | 
```

**Comment by aartbik** [comment]
A fix for the cyclic test crash is pending (see https://dart-review.googlesource.com/c/sdk/+/107000). As for the constant inference, the difference is right after canonicalize:

```dart
v16 <- Constant(#Closure: (Null) => Null from Function 'constFunction': static.) T{_Closure}
vs.
v16 <- Constant(#Closure: (dynamic) => dynamic from Function 'constFunction': static.) T{_Closure}

```

**Comment by aartbik** [comment]
The canonicalize difference happens in LoadFieldInstr::Canonicalize() with the following code
```dart
   if (Evaluate(instance()->BoundConstant(), &result)) {
      if (result.IsSmi() || result.IsOld()) {
          return flow_graph->GetConstant(result);
      }
  }
```
with Evaluate() returning the different values

```dart
v15 <- Constant(#Instance of 'C<Null>') T{C}
Instance of 'C<Null>'
Closure: (Null) => Null from Function 'constFunction': static.

v15 <- Constant(#Instance of 'C<Null>') T{C}
Instance of 'C<Null>'
Closure: (dynamic) => dynamic from Function 'constFunction': static.

```

**Comment by aartbik** [comment]
Fix for crash confirmed:

selected bot: vm-kernel-precomp-linux-debug-x64

The following tests are now succeeding:

| BOT/CONFIG                        | TEST                               |
| --------------------------------- | ---------------------------------- |
| vm-kernel-precomp-linux-debug-x64 | language_2/cyclic_metadata_test/02 |

Fix for the failure is pending at https://dart-review.googlesource.com/c/sdk/+/107064

**Comment by aartbik** [comment]
Confirmed fixes for all vm bots. Sample. below.

The following tests are now succeeding:

| BOT/CONFIG                          | TEST                            |
| ----------------------------------- | ------------------------------- |
| vm-kernel-precomp-linux-product-x64 | language_2/const_inference_test |

**Comment by aartbik** [comment]
@a-siva any actionable items left for this?

**Comment by a-siva** [comment]
I think there are no more known items, let me close it. If we find bugs we can open new issues for the failures.
