### ISSUE TITLE
Validate ddk with the devtools/webdev2/vm service proxy workflow

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36238]
We need to make sure all the assumptions we are making around DDC hold true for DDK, there is one known issue regarding library tracking but once that is fixed we might discover other differences.

**Comment by jakemac53** [comment]
cc @jmesserly

**Comment by jmesserly** [comment]
yes, DDK is not generating the correct `trackLibraries` call and I believe the inline source maps (for package:stack_trace) are missing too.

Hmm, that probably explains the code size difference between them.

**Comment by jmesserly** [comment]
I filed https://github.com/dart-lang/sdk/issues/36253 for the trackLibraries issue

**Comment by jakemac53** [comment]
This is all confirmed working now (with the kernel transform as well)
