### ISSUE TITLE
Fasta crash: error in program crashes the compiler

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36230]
This silly little program

```dart
main() {
  int x = 17;
  print((--x)--);
}
```

crashes Fasta in the VM's modular transformations, when they encounter an `SyntheticExpressionJudgment`.

**Comment by peter-ahe-google** [comment]
FYI, the crash is by design.

It also crashes the BinaryPrinter if you use `-t none`.

**Comment by srawlins** [comment]
This no longer crashes. Now this is printed:

```none
36230.dart:3:13: Error: Can't assign to a parenthesized expression.
  print((--x)--);
            ^
```
