### ISSUE TITLE
Would like dartfmt to leave a blank line after shebang lines

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36246]
Currently (as of dartfmt version 1.2.2) if I make a `.dart` script that's meant to be executable:

    #!/usr/bin/env dart

    import 'dart:io';
    // More code...    

Then `dartfmt` will remove the blank line after the shebang line.  I dislike this because it puts Dart code up against a line that isn't legal Dart.  I also suspect that putting a blank line between the shebang and code (or between the shebang with copyright notice and code) is a more common practice than not, but I haven't collected data to back that up.

(I suppose I should be encouraged to add a dartdoc comment near the top of the script since `dartfmt` will insert a blank line above it.)

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/dart_style#782
