### ISSUE TITLE
DDC+Kernel needs to emit trackLibraries call

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#36253]
DDC+Kernel is not emitting the `trackLibraries` call necessary for debug tools. We should refactor this code into shared_compiler.dart and use it from both of DDC's backends (Analyzer and Kernel).

**Comment by vsmenon** [comment]
@jmesserly - have you started on this?  might be an easy one to someone else to take.

**Comment by jmesserly** [comment]
yes, I've started. It's tricky because it involves refactoring to move shared code into shared_compiler.dart and I'm trying to not cause too many conflicts with my hot reload branch. My current work-in-progress CL takes my hot reload branch, but removes the unfinished bits, keeping the fixes for trackLibraries and exporting private symbols.

**Comment by jmesserly** [comment]
testing a fix now: https://dart-review.googlesource.com/c/sdk/+/97553.
(note: this does not address the private symbols issue, that'll be a separate CL)
