### ISSUE TITLE
callable class don't implement call interface

### ISSUE THREAD

**Issue by tarno0se** [dart-lang/sdk#36251]
```
abstract class Base {
  void f();
}

class Callable {
  void call() {}
}

class A implements Base {
  var f = Callable();//error: Class 'A' can't define field 'f' and have method 'Base.f' with the same name.
}
```

**Comment by lrhn** [comment]
This is expected behavior.

Dart distinguishes methods from getters with a function type. The `Base` class requires `f` to be a method, and class `A` tries to make it a getter, so class `A` is invalid.

What you can do instead is:
```dart
class A implements Base {
  void Function() _f;
  A(this._f);
  void f() { 
    _f();
  }
}
```

**Comment by tarno0se** [comment]
> Dart distinguishes methods from getters with a function type. The Base class requires f to be a method, and class A tries to make it a getter, so class A is invalid.

Yes, and this is a design error. The implementation should not require a method. The implementation should require ANY callable object.
