### ISSUE TITLE
No analyzer error for [expression][unary_operator][expression]

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#36255]
While editing some code, I accidentally removed an `&&`, and the code ended up something like this:
```dart
if (a !b && c && d) {}
```

I got a runtime error for `a !b`, but didn't receive an analyzer error as I'd expect to.

This also reproduces with the `~` operator:
```dart
main() {
  var a, b;
  // No analyzer error
  // Runtime error: "Error: The string '!' isn't a user-definable operator."
  var result1 = a !b;
  // No analyzer error
  // Runtime error: "Error: The string '~' isn't a user-definable operator."
  var result2 = a ~b;
}
```
---

Reproducible in Dart 2.2.0

**Comment by lrhn** [comment]
@askeksa-google @peter-ahe-google 
The front end could perhaps also do with a more precise error message.

**Comment by peter-ahe-google** [comment]
The example program above leads to a spurious error about non-nullable types and causes an infinite loop in the parser.

@danrubel
