### ISSUE TITLE
flutter analyzer performance regressions due to a recent dart sdk roll

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#36250]
From https://github.com/flutter/flutter/pull/29389:

It looks like a recent Dart sdk roll into flutter caused a ~5% performance regression in flutter analyze --flutter-repo. From some investigation, this is likely due to upstream linter changes, esp. around `LibraryAnalyzer._computeHints` and `BestPracticesVerifier.BestPracticesVerifier`.

cc @scheglov @stereotype441

**Comment by srawlins** [comment]
I am having trouble understanding what https://github.com/flutter/flutter/pull/29389/files actually changed in the actual running "analyzer performance" in CI ([dashboard](https://flutter-dashboard.appspot.com/benchmarks.html)). Filtering the dashboard for "analyzer", I see 4x "analyzer_benchmark" charts, 2x for "flutter_repo".

https://github.com/flutter/flutter/pull/29389 was merged the morning of March 15, but the benchmark chart now only goes back to March 16. :frowning_face: 

How can we see logs for these benchmark runs? What SDK was being used before the regression, and after?

**Comment by srawlins** [comment]
@keertip points out an idea of what flutter/flutter#29389 may have effectively done in the bots: in increasing the minimum SDK constraint, it may have changed what versions of various packages were downloaded.

I'm not super duper sure how though, since the _latest_ versions of packages fitting the constraints should be fetched each time, and it would be odd for the a _later_ version of package A to have a _lower_ SDK constaint than an _earlier_ version of package A.  Hmm...

**Comment by bwilkerson** [comment]
I thought flutter hard-coded the versions they vended, which would mean that the SDK constraints can't change anything for them, only for clients that depend on the flutter packages.

**Comment by srawlins** [comment]
You're right @bwilkerson. I suspect this is not due to your PR at all. The commit just before your PR is an [engine roll](https://github.com/flutter/flutter/commit/f6e9afa7d33f79aaf743bb44d58e0ad8f0710815), which I think @scheglov already identified and I am just realizing.

The engine roll includes a dart roll: `Roll src/third_party/dart 7d560f8385..7418238239` which is https://github.com/dart-lang/sdk/commit/7d560f8385 to https://github.com/dart-lang/sdk/commit/7418238239 so I'm bisecting those now.

**Comment by srawlins** [comment]
I bisected those commits to no avail, and then ran `flutter analyze` at the commit before Brian's commit, and then _at_ Brian's commit, and sure enough, I can see the performance regression. 😦 

Then when I bump the pubspecs one-by-one (and re-run `./bin/flutter update-packages`), it appears that performance slowly gets worse:

* f6e9afa7d33f79aaf743bb44d58e0ad8f0710815 (the commit before Brian's): 44.8s
* bump packages/flutter/pubspec.yaml: 45.6s
* and bump packages/flutter_test/pubspec.yaml: 45.8s
* and bump examples/flutter_gallery/pubspec.yaml: 47.0s

But whyyyyy... whyyyyy... curious.

**Comment by bwilkerson** [comment]
Did you re-run `./bin/flutter update-packages` after each bump?

Does `./bin/flutter update-packages` actually change the set of packages? If so, which ones?

Does the same thing happen if you don't run `./bin/flutter update-packages`?

**Comment by srawlins** [comment]
> Did you re-run ./bin/flutter update-packages after each bump?

Yes
> Does ./bin/flutter update-packages actually change the set of packages? If so, which ones?

No, I'm pretty sure it doesn't; I've been diffing the pubspec.lock files, and the only thing that changes is the SDK constraints at the bottom.

> Does the same thing happen if you don't run ./bin/flutter update-packages?

Hrm, good question. My next test I'm going to do is  smaller SDK bumps (like 2.1.0, 2.1.1)

**Comment by bwilkerson** [comment]
Analyzer doesn't look at the `pubspec.lock` file, only the `.packages` file, which doesn't contain any SDK version information. If it doesn't change the set of packages, then I _really_ don't see how it could impact performance.

**Comment by srawlins** [comment]
Ok, interesting. Unfortunately, there is no difference in the `.packages` files before and after the change :(

```none
srawlins-macbookpro:flutter srawlins$ diff packages/flutter_tools/.packages{,BKUP}
1c1
< # Generated by pub on 2019-03-21 18:17:22.621362.
---
> # Generated by pub on 2019-03-21 18:13:38.622492.
srawlins-macbookpro:flutter srawlins$ diff packages/flutter_test/.packages{,BKUP}
1c1
< # Generated by pub on 2019-03-21 18:17:24.087211.
---
> # Generated by pub on 2019-03-21 18:13:40.887155.
srawlins-macbookpro:flutter srawlins$ diff packages/flutter/.packages{,BKUP}
1c1
< # Generated by pub on 2019-03-21 18:17:21.501142.
---
> # Generated by pub on 2019-03-21 18:13:37.724932.
srawlins-macbookpro:flutter srawlins$ diff examples/flutter_gallery/.packages{,BKUP}
1c1
< # Generated by pub on 2019-03-21 18:17:20.558909.
---
> # Generated by pub on 2019-03-21 18:13:36.769917.
```

Incrementally bumping the minimum SDK version also decreases performance no matter what (newer) version I chose:

* Leaving minimum SDK at 2.0.0-dev.68.0: 44.8s
* Bumping flutter_gallery, flutter, flutter_test, flutter_tools' minimum SDK to 2.1.0: 46.9s
* Bumping them to 2.1.0-dev.0.0: 46.9s
* Bumping them to 2.0.0: 46.7s

Even if I don't run `update-packages` after bumping the pubspecs! Bumping the pubpsecs  to use 2.2.0 as a lower bound, then _not_ running `update-packages`, then analyzing, results in a time of 46.5s.

All of this is quite mysterious and prevents me from bisecting 😠 . I think the next step is to profile with @scheglov 's script, which  emulates `flutter analyze`, with and without the pubspec changes (no custom SDK, just whatever `flutter analyze` does).

**Comment by srawlins** [comment]
For future archaeologists, I looked at this again today; the `flutter_tools.dart` command has a `--verbose` which gets real noisy, and prints millisecond timestamps. I played with this data a bit, and found a couple strange data points. There are 3 files that take _way_ longer to analyze (I think) when the pubspecs are changed:

* `/Users/srawlins/code/flutter/examples/flutter_gallery/test_driver/scroll_perf.dart` goes from 388 ms to 1154 ms (+766 ms; +197%)
* `/Users/srawlins/code/flutter/packages/flutter_localizations/test/widgets_test.dart` goes from 105 ms to 898 ms (+793 ms; +755%)
* `/Users/srawlins/code/flutter/packages/flutter_tools/analysis_options.yaml` goes from 95 ms to 185 ms (+90 ms; +95%)

Of all the files which originally took longer than 50 ms to analyze, these are the only three now take at least 1.2x as long to analyze. These files accounting for 1.6 seconds accounts for most of the slowdown from 45 to 47 seconds. These numbers are the averages of 2 runs before changing pubspecs, and 2 runs after.

If someone on the analyzer team can profile analyzing any of these three files, maybe we'll learn something juicy...

**Comment by devoncarew** [comment]
An update here: our perf CI system was incorrectly ascribing blame to some commits - commits to flutter/flutter were not causing the benchmarks to re-run (but commits to dart-lang/sdk were). This issue is now fixed - as of a week or two ago.

In any case, the CI system incorrectly assigning blame to various commits might explain why we had trouble diagnosing this issue.

**Comment by devoncarew** [comment]
Closing as assumed fixed - Konstantin's change from https://dart-review.googlesource.com/c/sdk/+/152725 made the benchmark about 35% faster.
