### ISSUE TITLE
Analyzer reports wrong error for non-constant map with equal keys

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#36258]
The code below works well in VM, but analyzer reports errors

```dart
class C {
  int a;
  int b;

  C(this.a, this.b);

  int get hashCode => a;
  bool operator== (Object other) => other is C && this.a == other.a;
}

main() {
  var m1 = <int, String>{1: "val1", 1: "val2"}; // Analyzer error - Two keys in a map literal can't be equal
  var m2 = <String, int>{"key1": 1, "key1": 2}; // Analyzer error - Two keys in a map literal can't be equal
  var m3 = <C, int>{new C(1, 2): 1, new C(1, 3): 2};
  var m4 = <C, int>{new C(1, 2): 1, new C(1, 3): 2};
}
```
According to the Dart Language specification Expressions/Maps

> It is a compile-time error if two keys of a constant map literal are equal
> according to their ‘==’ operator

But this is for constant literals only. For non-constant map literals equal keys are allowed. So there should be no error

Dart VM version: 2.2.1-dev.1.1 (Fri Mar 15 10:54:11 2019 +0100) on "windows_x64"

**Comment by bwilkerson** [comment]
@scheglov I think https://dart-review.googlesource.com/c/sdk/+/97177 will address this.

**Comment by scheglov** [comment]
The CL was landed, the issue fixed.
