### ISSUE TITLE
Analysis server should process `@macro` in documentation comments

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36266]
During the indexing phase of analysis (when gathering defined types for use in searches), the analyzer should also build an index of any documentation templates it finds in the source code.  The analysis server should use these templates to expand `@macro` declarations when serving documentation comments to IDE users.

(This is a task we're already planning to work on; just capturing it in a github issue so I can add it to the appropriate milestone)

If you need more background information about this task, reach out to @bwilkerson, @devoncarew, or me.

**Comment by bwilkerson** [comment]
I believe that this has been implemented. I saw it working on a local build on my machine, but it would be great to get confirmation from at least one other person just to be sure.

**Comment by DanTup** [comment]
@bwilkerson I just tested with Flutter master (which claims to be SDK 2.2.1-edge https://github.com/dart-lang/sdk/commit/f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb) but don't see the fix:

```js

// Dart SDK:
//    Loc: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk
//    Ver: 2.2.1-edge.f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb

{
    "id": "92",
    "result": {
        "hovers": [
            {
                "offset": 452,
                "length": 5,
                "dartdoc": "{@macro flutter.widgets.widgetsApp.color}",
                "elementDescription": "{Color color}",
                "elementKind": "parameter",
                "isDeprecated": false,
                "staticType": "Color"
            }
        ]
    }
}
```

I can't see any commits since that one that look related to this - do you know when it landed?

**Comment by DanTup** [comment]
I guess https://github.com/dart-lang/sdk/commit/dd7a6320e3b694f12ce3aea06ce98ab5e3f7ea36 is the work, which was merged much before the hash above. Is there anything special about the Flutter SDK that might affect it?

**Comment by bwilkerson** [comment]
Yes, that's the commit.

The SDK that ships with Flutter is usually a couple of days behind bleeding edge. I don't know whether or not that's the issue.

**Comment by DanTup** [comment]
The hash I gave above is the one from the Dart SDK inside Flutter that was being used:

```
//    Loc: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk
//    Ver: 2.2.1-edge.f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb
```

Is there a simple way I can test if it's working, like should it work within a single file like this?:

```dart
/// {@template template_name}
/// Some shared docs
/// {@endtemplate}
const Color foo = null;

  /// {@macro template_name}
const Color foo2 = null;
```

**Comment by bwilkerson** [comment]
Yes, that works for me in IntelliJ running a build of the SDK from this morning (2.2.1-edge.28acc7ff6ae6d4acdf0a559f2c6ab5979908169a).

**Comment by bwilkerson** [comment]
Devon suggested that you could try building the SDK and symlink-ing it into Flutter.

**Comment by DanTup** [comment]
That small sample wasn't working either, so maybe there's something up. It seems weird for the SDK to have a version hash that should include it, but it not, so maybe I messed something up. I'll do some more digging shortly (I can test with this mornings nightly I already have, but I'd like to understand what went wrong above - I rely on the hash showing in my logs/`dart --version` to be accurate quite a lot :-))

**Comment by bwilkerson** [comment]
We were debugging an issue here yesterday and noticed that there are multiple inconsistent version numbers reported in the Flutter build, which made it quite difficult for us to know whether we were reproducing the user's configuration. (I don't remember the details by I can try to track them down if it's important.)

**Comment by DanTup** [comment]
Ah, now you mention it - I opened an issue this morning because I was seeing `None` where a hash used to be:

https://github.com/flutter/flutter/issues/30433

So now I wonder if the hash I had above (which actually was likely fished out of the `version` file by my extension, and not gotten from `dart --version`) was also bogus. That could explain things - in which case I'll try linking in the nightly from this morning or something to test it with Flutter. Thanks!

**Comment by DanTup** [comment]
@bwilkerson Ok, testing with this mornings nightly build Dart, with no Flutter involved, I still don't see it. I just get back the raw dartdoc contents. I'm opening a single file like this:

```
/// {@template template_name}
/// Some shared docs
/// {@endtemplate}
const String foo = null;

/// {@macro template_name}
const String foo2 = null;
```

[Here's a complete log](https://github.com/dart-lang/sdk/files/3039594/complete.txt), but here's the interesting parts:

```
Dart SDK:
    Loc: /Users/dantup/Dev/dart-sdk/nightly-2019-04-03
    Ver: 2.2.1-edge.cc0997f1bce093eb71fb56ee7da6e6e43139fd02

Spawning /Users/dantup/Dev/dart-sdk/nightly-2019-04-03/bin/dart with args ["/Users/dantup/Dev/dart-sdk/nightly-2019-04-03/bin/snapshots/analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=2.25.0"]

==> {
	"id": "2",
	"method": "analysis.updateContent",
	"params": {
		"files": {
			"/Users/dantup/Desktop/ddd test/test.dart": {
				"content": "/// {@template template_name}\n/// Some shared docs\n/// {@endtemplate}\nconst String foo = null;\n\n/// {@macro template_name}\nconst String foo2 = null;\n",
				"type": "add"
			}
		}
	},
	"clientRequestTime": 1554307108642
}
==> {
	"id": "7",
	"method": "analysis.getHover",
	"params": {
		"file": "/Users/dantup/Desktop/ddd test/test.dart",
		"offset": 85
	},
	"clientRequestTime": 1554307111646
}
<== {
	"id": "7",
	"result": {
		"hovers": [
			{
				"offset": 83,
				"length": 3,
				"containingLibraryPath": "/Users/dantup/Desktop/ddd test/test.dart",
				"containingLibraryName": "",
				"dartdoc": "{@template template_name}\nSome shared docs\n{@endtemplate}",
				"elementDescription": "String foo",
				"elementKind": "top level variable",
				"isDeprecated": false,
				"staticType": "String"
			}
		]
	}
}
==> {
	"id": "8",
	"method": "analysis.getHover",
	"params": {
		"file": "/Users/dantup/Desktop/ddd test/test.dart",
		"offset": 137
	},
	"clientRequestTime": 1554307113015
}
<== {
	"id": "8",
	"result": {
		"hovers": [
			{
				"offset": 136,
				"length": 4,
				"containingLibraryPath": "/Users/dantup/Desktop/ddd test/test.dart",
				"containingLibraryName": "",
				"dartdoc": "{@macro template_name}",
				"elementDescription": "String foo2",
				"elementKind": "top level variable",
				"isDeprecated": false,
				"staticType": "String"
			}
		]
	}
}
```

**Comment by bwilkerson** [comment]
Devon did a local build on his machine and confirmed that it appears to be working for him. I'm not sure what the difference is. In any case, thanks for spending time on this!

**Comment by DanTup** [comment]
Hmm, is there any difference in how you're testing to the above? I'll test again tomorrow with the new nightly and also running from source to see if I can figure out what's up.

**Comment by devoncarew** [comment]
I did a `flutter upgrade` on master, and tested via doing an `F1` in IntelliJ when the cursor was an `app.navigatorKey` reference.

**Comment by DanTup** [comment]
I tried in Android Studio but see the same behaviour there:

<img width="416" alt="Screenshot 2019-04-03 at 9 15 32 pm" src="https://user-images.githubusercontent.com/1078012/55510256-c3481200-5655-11e9-9bec-e447d3cfa771.png">

<img width="656" alt="Screenshot 2019-04-03 at 9 16 24 pm" src="https://user-images.githubusercontent.com/1078012/55510258-c3481200-5655-11e9-84fa-ba029ea32d2b.png">

**Comment by DanTup** [comment]
To resolve the above - it turned out that the difference was whether the SuggestionSets work was enabled. Turning it on resolves the issues I saw (in VS Code - I'm not sure how to do the equiv in Android Studio).

Suggestion Set work is planned to be on-by-default in the next major Dart Code release.

**Comment by devoncarew** [comment]
We'll get support in Android Studio once it starts selecting a new enough version of the Dart plugin.

Short term it looks like SuggestionSets and `@macro` support will be coupled. This is not a blocker for us. Longer term we'll look to uncoupling the impl of `@macro` processing from SuggestionSets.
