### ISSUE TITLE
language/const_syntax_test/[1,2,3] should not be compile-time errors

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#3626]
For example &quot;/1&quot; looks as valid code for me.
I don't see why it should cause compile-time error.

-----
main() {
&nbsp;&nbsp;Expect.equals(42, FOO);   /// 01: compile-time error
}

const FOO = 42;     /// 01: continued

class C {
}

-----

**Comment by mhausner** [comment]
Obsolete.
