### ISSUE TITLE
Analyzer support needed for flutter manifest lints

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36268]
Analyzer XML parsing support is needed to support the following Flutter feature requests:
- https://github.com/flutter/flutter/issues/29242
- https://github.com/flutter/flutter/issues/29241
- https://github.com/flutter/flutter/issues/29240
- https://github.com/flutter/flutter/issues/29239
- https://github.com/flutter/flutter/issues/29238

**Comment by stereotype441** [comment]
@keertip is there any more work required, or can we close this issue?

**Comment by keertip** [comment]
It's done, can close.
