### ISSUE TITLE
type_feedback_test is failing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#36265]
type_feedback_test is failing on vm-kernel-optcounter-threshold-linux-release-ia32 bot:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8918532969289762960/+/steps/test_results/0/stdout

Looks like the culprit is: https://dart-review.googlesource.com/c/sdk/+/97174

**Comment by rmacnak-google** [comment]
This may be broken for reasons related to https://github.com/dart-lang/sdk/issues/35196 due to the initial usage counter value.

**Comment by sjindel-google** [comment]
This is failing again, apparently due to fully-intrinsified methods not being accounted for:

https://dart-review.googlesource.com/c/sdk/+/99162

**Comment by sjindel-google** [comment]
This is failing again, apparently due to fully-intrinsified methods not being accounted for:

https://dart-review.googlesource.com/c/sdk/+/99162

**Comment by rmacnak-google** [comment]
Removed in fb5465c6247eecf279cd889df6aab2c29a04336b
