### ISSUE TITLE
Platform class is not fakeable in tests

### ISSUE THREAD

**Issue by DaveShuckerow** [dart-lang/sdk#36263]
Not having this leads to needing workarounds such as [package:platform](https://pub.dartlang.org/packages/platform#-readme-tab-).

The request here is to make Platform's fields non-static so that it is possible to construct a different Platform.

**Comment by kevmoo** [comment]
We are having discussions about this

CC @yjbanov @lrhn

**Comment by yjbanov** [comment]
One of the properties we'd want from `Platform` (or whatever replacement we come up with) is that it is effective at tree-shaking. This is so I can write code like this:

```dart
if (Platform.isIOS) {
  ... iOS-specific code ...
} else if (Platform.isWeb) {
  ... Web-specific code ...
}
```

And not get the iOS-specific code compiled into the Web app.

However, this request seems to ask that `Platform` is even more dynamic than it is today. Perhaps you don't want `Platform` but something else. Or perhaps what I want is not `Platform` but something else. Or both. I think `Platform` is quite broken for the kind of cross-platform story we're aiming at.

One of the related discussions is happening in https://github.com/dart-lang/sdk/issues/35969.

**Comment by sortie** [comment]
Hi, being able to fake the Platform class is a reasonable request. As you point out package:platform is a workaround that works right now. I'm currently planning a new design that meets @yjbanov's needs and I'll add this to the design considerations as well. Unfortunately I won't be able to execute on this until early May.
