### ISSUE TITLE
CFE: Implement type inference for control-flow collections

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36276]
Type inference and run-time check insertion for control-flow collections needs to be implemented.  These are normally blocked on being able to compile the corresponding construct (#36274).

- [x] `if` in lists and sets (49a7fa1c116e1d4117d621458af)
- [x] `if` in maps (864b22d3ce3b2f7d90dd3ab28ab986b37bd3380d)
- [x] `for` in lists and sets (fbc70da0d3718b8073207ed76752053dbfdc1da4)
- [x] `for` in maps (584affcffa3d893a99938cceebc312a76fb82934 + follow-ups)
- [x] `for in` in lists and sets (fbc70da0d3718b8073207ed76752053dbfdc1da4)
- [x] `for in` in maps (584affcffa3d893a99938cceebc312a76fb82934 + follow-ups)

**Comment by kmillikin** [comment]
This is on target for landing by March 29.

**Comment by stefantsov** [comment]
The proposed implementation is in https://dart-review.googlesource.com/c/sdk/+/98015 and https://dart-review.googlesource.com/c/sdk/+/98180.  I think we may close this issue when the two CLs are landed.
