### ISSUE TITLE
[bug] new WannabeFunction() is BinaryFunction return false!!!

### ISSUE THREAD

**Issue by Guang1234567** [dart-lang/sdk#36288]
Hello dev:

As we known in http://dart.goodev.org/articles/language/emulating-functions

```dart

typedef BinaryFunction(a,b);

class WannabeFunction {
  call(int a, int b) => a + b;
}

new WannabeFunction() is BinaryFunction; // true
```

But `new WannabeFunction() is BinaryFunction return false` actually !

**Comment by Guang1234567** [comment]
In addition:

```dart
        print(“stupid bug: ${new WannabeFunction() is BinaryFunction}"); //  false
        BinaryFunction v = new WannabeFunction(); // is  BinaryFunction  return false, but cant assign to BinaryFunction v !!!!!
        print("stupid bug: ${v(11, 22)}"); // 33
```

**Comment by mraleph** [comment]
Documentation you are referring to is outdated. You should read through an up to date version of this page: https://www.dartlang.org/articles/language/emulating-functions

Semantics has changed in Dart 2: now only real functions are considered to be subtypes of function types. However to avoid breaking too much code semantics of assignment `BinaryFunction v = new WannabeFunction()` has changed. It's essentially a syntactic sugar for tearing off `call` method: `BinaryFunction v = new WannabeFunction().call`.

See https://groups.google.com/a/dartlang.org/forum/#!topic/misc/hvt6jpiYxsE for more information.
