### ISSUE TITLE
Add switch autocomplete on enum

### ISSUE THREAD

**Issue by tolotrasamuel** [dart-lang/sdk#36290]
In Android Studio, Dart does not compile if a `switch` is used on an enum and some clause are missing. 
Though I do not see why should that trigger a fatal compiler error, (Why not just skip missing clause) one would intuitively place the cursor on the error and press the keys: ALT+ENTER but nothing happens. 

I suggest a feature that auto-generate all missing clause with an empty: `break` statement or just not consider this a fatal compiler error at all.

![image](https://user-images.githubusercontent.com/29230303/54734842-f3a2a180-4bbb-11e9-81d9-82b58dcfd299.png)

**Comment by lrhn** [comment]
It makes sense to have a fix to remove the error. Just adding `default: break;` is likely not sufficient :)

(See https://github.com/dart-lang/sdk/issues/36127 for the ongoing discussion about whether this should be a warning or error. The fix makes sense in either case).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/97780
