### ISSUE TITLE
Analyzer should warn when using constant-update-2018 features with an SDK constraint that does not guarantee support

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36296]
The first version of Dart with constant-update-2018 enabled is planned to be 2.2.2, so we should implement a hint based on checking the user's SDK constraint against this version number.

Since the constant-update-2018 feature affects both syntax and semantics, it will be more challenging to detect when the user is inadvertently taking advantage of the feature.  We will definitely detect the easy cases.  We'll detect the harder cases if time allows.

The easy cases are as follows:
- [x] Making use of `is` or `as` in a constant context.
- [x] Using or overriding the new `>>>` operator.
- [x] Applying one of the operators `&`, `|`, or `^` to operands of type `bool`.

The harder cases are as follows (they require some rework of the analyzer's constant evaluator):
- [x] When using `==` in a constant, a non-primitive type is compared to `null`.
- [ ] When using `&&`, `||`, `??`, or `?:` in a constant, an operand fails to be a valid constant, but it's permitted by constant-update-2018 because that operand is skipped due to short-circuiting.

Note that constant-update-2018 also makes subtle changes to what is considered a valid "potentially constant" expression.  We're not going to try to account for this, because we believe such differences will be extremely rare corner cases.

**Comment by bwilkerson** [comment]
Initial work done in https://dart-review.googlesource.com/c/sdk/+/97567.

**Comment by bwilkerson** [comment]
I believe that we have the functionality required for 2.3, and a little more, so I'm removing the milestone.

**Comment by stereotype441** [comment]
We need to update this warning to refer to version 2.3.2.

**Comment by bwilkerson** [comment]
Should this include the `>>>` operator?

**Comment by stereotype441** [comment]
> Should this include the `>>>` operator?

No, `>>>` is slated for a future release.

Thanks for taking this on, Brian!

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/104260

**Comment by stereotype441** [comment]
As of 556c9134acb3c9328efe075738030e4f63b55f69, the warning now refers to version 2.3.2.  The remaining bullet item is a small enough corner case that it's not worth putting effort into.
