### ISSUE TITLE
Overriding `==` from `Function` leads to potentially unexpected dart2js behavior

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/sdk#36298]
Hi there!

We have a class which implements `Function` but overrides the `==` operator. This code failed to compile via dart2js because the signature for `==` in the overriding class omits a type on the parameter to `==`, where `Function` specifies the type of the parameter as `Object` (despite the fact that the signature of `==` from the `Object` class omits a type on the parameter in it's signature for `==`). Here's a dartpad instance which replicates this behavior: https://dartpad.dartlang.org/e2f5a7e339b47401bf985526f19419ce

I'm honestly not sure if this should be a build error or not, considering that non-operator method overrides don't exhibit the same build failure. That said, if it is an intended build error, I would think that it should at least also appear as an analyzer error. 

So my question is: Should this be a build error, and, if so, why is it not an analyzer error also?

This is all on Dart `2.2.0`. Thanks for looking!

**Comment by sigmundch** [comment]
There seems to be an inconsistency between dart-analyzer and the CFE (which parses code for both dart2js and the vm).

Tweaking your example, here is a similar issue without dealing with our code libraries:
```dart
main() {}

// this compiles
abstract class C {
  bool someFunc(thing);
}

abstract class B {
  bool someFunc(Object thing);
}

class A extends C implements B {
  @override
  bool someFunc(thing) => true;
}
```

C's `thing` is inferred as dynamic, then we don't know what the type of A's `thing` should be. You hit a simlar issue if you add a type in C like String or something else.

@leafpetersen @lrhn - which implementation is correct here?

@lrhn  - aside - it seems that we probably want to fix the type of either Object.== or Function.== in the libraries to be consistent

**Comment by corwinsheahan-wf** [comment]
@sigmundch Good call, I forgot that the base class will inherit method signatures from both `Object` and `Function`! Thanks for taking the time to look into this.

**Comment by leafpetersen** [comment]
As an aside, note that implementing `Function` is a no-op, and somewhat discouraged.

My [draft spec](https://github.com/dart-lang/language/blob/3b46550bd069bb62c2f30300039711f886741edb/resources/type-system/inference.md) for top level inference specifies that

```
 If there are multiple overridden/implemented methods, and any two of them have non-equal types (declared or inferred) for a parameter position which is being inferred for the overriding method, it is an error.
```

However, the question is what is meant by "non-equal".  This can either be syntactic equality, or mutual subtype.  In the former case, the example here should be rejected, in the latter not.  If we accept it, we need to specify which of the equal but not syntactically the same types we choose.  I think we could do that.

For the case where one of the types is more specific (e.g. the `String` case that @sigmundch proposes), that is currently definitely an error as specified, but @eernstg has advocated using the most specific type, as we do when computing signatures.  This seems broadly reasonable to me, but is a change we'd have to coordinate between the implementation teams.

**Comment by srawlins** [comment]
Implementing Function is now deprecated.

**Comment by evanweible-wf** [comment]
@srawlins do you happen to have a link to more information on that? We have quite a few things internally that implement Function, so I'm hoping to learn more.

**Comment by eernstg** [comment]
`implements Function` gets special treatment: It has no effect, for example:

```dart
class C implements Function {}

void main() {
  print(C() is Function); // 'false'.
}
```

Same treatment is given to `extends` and `with` clauses. So if you have some classes whose superinterfaces include `Function` you can simply delete it and nothing should change.

**Comment by evanweible-wf** [comment]
Oh okay, I see. So we can still override `call()` to make classes behave like Functions, this just means the `implements Function` part is unnecessary. Is that right?

**Comment by srawlins** [comment]
@evanweible-wf Oh I see. Definitely, adding a `call` method is still a supported feature to make a class instance callable.

**Comment by evanweible-wf** [comment]
Perfect, thanks for the clarification!
