### ISSUE TITLE
Remove `>>>=` from 2.3

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36308]
This isn't currently parsed and we have no tests yet, so we suggest removing it from the constant work for the current milestone and revisiting later.

Per @bwilkerson on eng task:

There is one reference to `>>>=` in the specification -- in the grammar production 'compoundAssignmentOperator' -- that would need to be removed if we don't do the other work.

fyi - @aadilmaan @stereotype441 @kmillikin @lrhn @danrubel

**Comment by danrubel** [comment]
Scanner and parser work for `>>>=` is now complete, but I won't land it until we decide we are supporting it... https://dart-review.googlesource.com/c/sdk/+/97602

**Comment by vsmenon** [comment]
@danrubel - if we want to push this past 2.3, is there anything we need to do now?  I.e., remove the production @bwilkerson mentioned above - is that a simple change?

**Comment by danrubel** [comment]
Scanner/parser support for `>>>=` has landed in [97602](https://dart-review.googlesource.com/c/sdk/+/97602) but is disabled for now.
I recommend we follow Brian's suggestion and remove `>>>=` from the spec for 2.3.
After 2.3 we can revisit this and finish the work.

**Comment by kmillikin** [comment]
The decision was to *not* ship this assignment operator as part of 2.3.  @jensjoha can you verify that it's a syntax error in Fasta and close this issue if so?

**Comment by jensjoha** [comment]
Without the flag flipped in the parser it produces an error, yes.
