### ISSUE TITLE
Bad state: Too many elements

### ISSUE THREAD

**Issue by superpeace** [dart-lang/sdk#36301]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

dart 2.2
mac
 

  dartdevc arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.2.0/libexec/lib/_internal/ddc_sdk.sum --modules=amd -o packages/ThisApp/page/member/daummap/page.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/js/js.dartdevc.linked.sum -s packages/func2/func.dartdevc.linked.sum -s packages/ThisApp/common/javascript/daummap.dartdevc.linked.sum -s packages/logging/logging.dartdevc.linked.sum -s packages/collection/src/utils.dartdevc.linked.sum -s packages/collection/src/algorithms.dartdevc.linked.sum -s packages/collection/src/canonicalized_map.dartdevc.linked.sum -s packages/collection/src/comparators.dartdevc.linked.sum -s packages/collection/src/iterable_zip.dartdevc.linked.sum -s packages/collection/src/priority_queue.dartdevc.linked.sum -s packages/collection/collection.dartdevc.linked.sum -s packages/meta/meta.dartdevc.linked.sum -s packages/angular/src/core/change_detection/change_detection.dartdevc.linked.sum -s packages/path/path.dartdevc.linked.sum -s packages/stack_trace/stack_trace.dartdevc.linked.sum -s packages/angular/src/core/zone/ng_zone.dartdevc.linked.sum -s packages/angular/src/core/application_tokens.dartdevc.linked.sum -s packages/angular/core.dartdevc.linked.sum -s packages/angular/di.dartdevc.linked.sum -s packages/angular/src/core/linker/view_type.dartdevc.linked.sum -s packages/meta/dart2js.dartdevc.linked.sum -s packages/js/js_util.dartdevc.linked.sum -s packages/angular/src/core/change_detection/change_detection.template.dartdevc.linked.sum -s packages/angular/di.template.dartdevc.linked.sum -s packages/angular/src/core/application_tokens.template.dartdevc.linked.sum -s packages/angular/core.template.dartdevc.linked.sum -s packages/intl/date_symbols.dartdevc.linked.sum -s packages/intl/number_symbols.dartdevc.linked.sum -s packages/intl/number_symbols_data.dartdevc.linked.sum -s packages/intl/src/plural_rules.dartdevc.linked.sum -s packages/intl/intl.dartdevc.linked.sum -s packages/angular/src/bootstrap/modules.dartdevc.linked.sum -s packages/angular/angular.dartdevc.linked.sum -s packages/angular_router/src/directives/router_outlet_directive.dartdevc.linked.sum -s packages/angular_router/src/constants.dartdevc.linked.sum -s packages/angular_router/angular_router.dartdevc.linked.sum -s packages/angular_forms/src/directives.dartdevc.linked.sum -s packages/angular_forms/angular_forms.dartdevc.linked.sum -s packages/angular_components/content/deferred_content_aware.dartdevc.linked.sum -s packages/angular_components/app_layout/material_drawer_base.dartdevc.linked.sum -s packages/angular_components/app_layout/material_persistent_drawer.dartdevc.linked.sum -s packages/angular_components/app_layout/material_temporary_drawer.dartdevc.linked.sum -s packages/angular_components/app_layout/material_stackable_drawer.dartdevc.linked.sum -s packages/angular_components/utils/browser/feature_detector/feature_detector.dartdevc.linked.sum -s packages/angular_components/utils/browser/events/events.dartdevc.linked.sum -s packages/angular_components/auto_dismiss/auto_dismiss.dartdevc.linked.sum -s packages/quiver/core.dartdevc.linked.sum -s packages/angular_components/src/laminate/enums/base.dartdevc.linked.sum -s packages/angular_components/laminate/enums/position.dartdevc.linked.sum -s packages/angular_components/laminate/enums/visibility.dartdevc.linked.sum -s packages/angular_components/utils/rate_limit_utils/rate_limit_utils.dartdevc.linked.sum -s packages/angular_components/utils/disposer/disposer.dartdevc.linked.sum -s packages/angular_components/src/utils/async/async_update_scheduler.dartdevc.linked.sum -s packages/angular_components/utils/async/async.dartdevc.linked.sum -s packages/angular_components/utils/disposer/disposable_callback.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/dom_service.dartdevc.linked.sum -s packages/angular_components/utils/angular/imperative_view/imperative_view.dartdevc.linked.sum -s packages/angular_components/laminate/portal/portal.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/zindexer.dartdevc.linked.sum -s packages/angular_components/src/laminate/ruler/ruler_interface.dartdevc.linked.sum -s packages/angular_components/laminate/ruler/dom_ruler.dartdevc.linked.sum -s packages/angular_components/src/laminate/overlay/overlay_ref.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/overlay.dartdevc.linked.sum -s packages/angular_components/src/laminate/components/modal/modal_controller_directive.dartdevc.linked.sum -s packages/angular_components/src/model/action/async_action.dartdevc.linked.sum -s packages/angular_components/model/action/async_action.dartdevc.linked.sum -s packages/angular_components/laminate/components/modal/modal.dartdevc.linked.sum -s packages/angular_components/focus/focus_interface.dartdevc.linked.sum -s packages/angular_components/laminate/enums/alignment.dartdevc.linked.sum -s packages/angular_components/annotations/rtl_annotation.dartdevc.linked.sum -s packages/angular_components/src/laminate/popup/dom_popup_source.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/constants.dartdevc.linked.sum -s packages/dart_internal/extract_type_arguments.dartdevc.linked.sum -s packages/observable/observable.dartdevc.linked.sum -s packages/angular_components/utils/angular/properties/properties.dartdevc.linked.sum -s packages/angular_components/utils/angular/reference/reference.dartdevc.linked.sum -s packages/angular_components/src/laminate/popup/popup_hierarchy.dartdevc.linked.sum -s packages/angular_components/laminate/popup/popup.dartdevc.linked.sum -s packages/angular_components/focus/focus.dartdevc.linked.sum -s packages/angular_components/interfaces/has_disabled.dartdevc.linked.sum -s packages/quiver/strings.dartdevc.linked.sum -s packages/angular_components/mixins/has_tab_index.dartdevc.linked.sum -s packages/angular_components/button_decorator/button_decorator.dartdevc.linked.sum -s packages/angular_components/content/deferred_content.dartdevc.linked.sum -s packages/angular_components/model/ui/has_renderer.dartdevc.linked.sum -s packages/angular_components/dynamic_component/dynamic_component.dartdevc.linked.sum -s packages/angular_components/focus/focus_activable_item.dartdevc.linked.sum -s packages/angular_components/focus/focus_item.dartdevc.linked.sum -s packages/angular_components/focus/focus_list.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_iterator/dom_iterator.dartdevc.linked.sum -s packages/angular_components/focus/focus_trap.dartdevc.linked.sum -s packages/angular_components/focus/keyboard_only_focus_indicator.dartdevc.linked.sum -s packages/angular_components/model/ui/icon.dartdevc.linked.sum -s packages/angular_components/glyph/glyph.dartdevc.linked.sum -s packages/angular_components/model/ui/highlighted_text_model.dartdevc.linked.sum -s packages/angular_components/highlighted_text/highlighted_text.dartdevc.linked.sum -s packages/angular_components/model/ui/highlight_provider.dartdevc.linked.sum -s packages/angular_components/highlighted_text/highlighted_value.dartdevc.linked.sum -s packages/angular_components/utils/color/color.dartdevc.linked.sum -s packages/angular_components/utils/color/material.dartdevc.linked.sum -s packages/angular_components/material_ripple/material_ripple.dartdevc.linked.sum -s packages/angular_components/theme/module.dartdevc.linked.sum -s packages/angular_components/theme/dark_theme.dartdevc.linked.sum -s packages/angular_components/material_button/material_button_base.dartdevc.linked.sum -s packages/angular_components/material_button/material_button.dartdevc.linked.sum -s packages/angular_components/material_button/material_fab.dartdevc.linked.sum -s packages/angular_components/material_icon/material_icon.dartdevc.linked.sum -s packages/angular_components/material_checkbox/material_checkbox.dartdevc.linked.sum -s packages/angular_components/model/selection/selection_model.dartdevc.linked.sum -s packages/angular_components/utils/id_generator/id_generator.dartdevc.linked.sum -s packages/angular_components/material_chips/material_chip.dartdevc.linked.sum -s packages/angular_components/material_chips/material_chips.dartdevc.linked.sum -s packages/dart2_constant/core.dartdevc.linked.sum -s packages/quiver/time.dartdevc.linked.sum -s packages/angular_components/forms/error_renderer.dartdevc.linked.sum -s packages/angular_components/mixins/focusable_mixin.dartdevc.linked.sum -s packages/angular_components/material_input/deferred_validator.dartdevc.linked.sum -s packages/angular_components/material_input/base_material_input.dartdevc.linked.sum -s packages/angular_components/material_input/material_input_default_value_accessor.dartdevc.linked.sum -s packages/angular/experimental.dartdevc.linked.sum -s packages/angular_components/framework_stabilizers/framework_stabilizers.dartdevc.linked.sum -s packages/angular_components/framework_stabilizers/testability.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/dom_service_webdriver_testability.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/angular_2.dartdevc.linked.sum -s packages/angular_components/material_input/material_input_multiline.dartdevc.linked.sum -s packages/angular_components/material_input/material_input.dartdevc.linked.sum -s packages/angular_components/model/observable/observable.dartdevc.linked.sum -s packages/angular_components/utils/comparators/comparators.dartdevc.linked.sum -s packages/angular_components/model/date/date.dartdevc.linked.sum -s packages/angular_components/material_datepicker/calendar.dartdevc.linked.sum -s packages/angular_components/src/utils/angular/managed_zone/managed_zone.dartdevc.linked.sum -s packages/angular_components/utils/angular/managed_zone/angular_2.dartdevc.linked.sum -s packages/angular_components/utils/browser/window/module.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/module.dartdevc.linked.sum -s packages/angular_components/laminate/popup/module.dartdevc.linked.sum -s packages/angular_components/model/date/time_zone_aware_clock.dartdevc.linked.sum -s packages/fixnum/fixnum.dartdevc.linked.sum -s packages/protobuf/protobuf.dartdevc.linked.sum -s packages/angular_components/material_datepicker/proto/date.pb.dartdevc.linked.sum -s packages/angular_components/material_datepicker/proto/date_range.pb.dartdevc.linked.sum -s packages/angular_components/material_datepicker/range.dartdevc.linked.sum -s packages/angular_components/material_datepicker/comparison_option.dartdevc.linked.sum -s packages/angular_components/material_datepicker/comparison.dartdevc.linked.sum -s packages/angular_components/material_datepicker/model.dartdevc.linked.sum -s packages/angular_components/material_datepicker/module.dartdevc.linked.sum -s packages/angular_components/material_datepicker/date_input.dartdevc.linked.sum -s packages/angular_components/material_datepicker/date_range_input.dartdevc.linked.sum -s packages/angular_components/src/material_datepicker/calendar_listener.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_calendar_picker.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_month_picker.dartdevc.linked.sum -s packages/angular_components/src/material_datepicker/sequential.dartdevc.linked.sum -s packages/angular_components/material_datepicker/next_prev_buttons.dartdevc.linked.sum -s packages/angular_components/material_datepicker/preset.dartdevc.linked.sum -s packages/angular_components/model/ui/accepts_width.dartdevc.linked.sum -s packages/angular_components/material_list/material_list_size.dartdevc.linked.sum -s packages/angular_components/material_list/material_list.dartdevc.linked.sum -s packages/angular_components/mixins/material_dropdown_base.dartdevc.linked.sum -s packages/angular_components/material_list/material_list_item.dartdevc.linked.sum -s packages/angular_components/model/ui/toggle.dartdevc.linked.sum -s packages/angular_components/material_popup/material_popup.dartdevc.linked.sum -s packages/angular_components/material_select/activation_handler.dartdevc.linked.sum -s packages/angular_components/mixins/button_wrapper.dartdevc.linked.sum -s packages/angular_components/material_select/dropdown_button.dartdevc.linked.sum -s packages/angular_components/model/formatters/formatter.dartdevc.linked.sum -s packages/angular_components/model/ui/display_name.dartdevc.linked.sum -s packages/angular_components/model/collection/labeled_list.dartdevc.linked.sum -s packages/angular_components/model/selection/selection_options.dartdevc.linked.sum -s packages/angular_components/model/ui/has_factory.dartdevc.linked.sum -s packages/angular_components/model/selection/selection_container.dartdevc.linked.sum -s packages/angular_components/material_select/material_select_base.dartdevc.linked.sum -s packages/angular_components/material_select/material_select_item.dartdevc.linked.sum -s packages/angular_components/material_select/material_select_dropdown_item.dartdevc.linked.sum -s packages/angular_components/material_select/shift_click_selection.dartdevc.linked.sum -s packages/angular_components/mixins/track_layout_changes.dartdevc.linked.sum -s packages/angular_components/model/a11y/active_item.dartdevc.linked.sum -s packages/angular_components/model/a11y/active_item_directive.dartdevc.linked.sum -s packages/angular_components/model/a11y/keyboard_handler_mixin.dartdevc.linked.sum -s packages/angular_components/src/model/selection/interfaces/selectable.dartdevc.linked.sum -s packages/angular_components/model/selection/select.dartdevc.linked.sum -s packages/angular_components/model/ui/template_support.dartdevc.linked.sum -s packages/angular_components/utils/angular/css/css.dartdevc.linked.sum -s packages/angular_components/material_select/material_dropdown_select.dartdevc.linked.sum -s packages/angular_components/material_toggle/material_toggle.dartdevc.linked.sum -s packages/angular_components/src/material_datepicker/comparison_range_editor.dartdevc.linked.sum -s packages/angular_components/material_select/material_select.dartdevc.linked.sum -s packages/angular_components/model/action/delayed_action.dartdevc.linked.sum -s packages/angular_components/src/material_tooltip/tooltip_controller.dartdevc.linked.sum -s packages/angular_components/material_tooltip/module.dartdevc.linked.sum -s packages/angular/src/bootstrap/run.template.dartdevc.linked.sum -s packages/angular/angular.template.dartdevc.linked.sum -s packages/angular_components/focus/focus_interface.template.dartdevc.linked.sum -s packages/angular_components/src/laminate/enums/base.template.dartdevc.linked.sum -s packages/angular_components/laminate/enums/alignment.template.dartdevc.linked.sum -s packages/angular_components/annotations/rtl_annotation.template.dartdevc.linked.sum -s packages/angular_components/laminate/enums/position.template.dartdevc.linked.sum -s packages/angular_components/laminate/enums/visibility.template.dartdevc.linked.sum -s packages/angular_components/src/laminate/ruler/ruler_interface.template.dartdevc.linked.sum -s packages/angular_components/utils/rate_limit_utils/rate_limit_utils.template.dartdevc.linked.sum -s packages/angular_components/utils/disposer/disposer.template.dartdevc.linked.sum -s packages/angular_components/src/utils/async/async_update_scheduler.template.dartdevc.linked.sum -s packages/angular_components/utils/async/async.template.dartdevc.linked.sum -s packages/angular_components/utils/disposer/disposable_callback.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/dom_service.template.dartdevc.linked.sum -s packages/angular_components/laminate/ruler/dom_ruler.template.dartdevc.linked.sum -s packages/angular_components/src/laminate/popup/dom_popup_source.template.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/constants.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/feature_detector/feature_detector.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/events/events.template.dartdevc.linked.sum -s packages/angular_components/utils/angular/properties/properties.template.dartdevc.linked.sum -s packages/angular_components/utils/angular/reference/reference.template.dartdevc.linked.sum -s packages/angular_components/src/laminate/popup/popup_hierarchy.template.dartdevc.linked.sum -s packages/angular_components/laminate/popup/popup.template.dartdevc.linked.sum -s packages/angular_components/model/action/delayed_action.template.dartdevc.linked.sum -s packages/angular_components/model/ui/toggle.template.dartdevc.linked.sum -s packages/angular/src/core/change_detection/directive_change_detector.dartdevc.linked.sum -s packages/angular_components/src/material_tooltip/tooltip_controller.template.dartdevc.linked.sum -s packages/angular_components/content/deferred_content_aware.template.dartdevc.linked.sum -s packages/angular_components/content/deferred_content.template.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/zindexer.template.dartdevc.linked.sum -s packages/angular_components/utils/angular/imperative_view/imperative_view.template.dartdevc.linked.sum -s packages/angular_components/laminate/portal/portal.template.dartdevc.linked.sum -s packages/angular_components/src/laminate/overlay/overlay_ref.template.dartdevc.linked.sum -s packages/angular_components/src/utils/angular/managed_zone/managed_zone.template.dartdevc.linked.sum -s packages/angular_components/utils/angular/managed_zone/angular_2.template.dartdevc.linked.sum -s packages/angular/experimental.template.dartdevc.linked.sum -s packages/angular_components/framework_stabilizers/framework_stabilizers.template.dartdevc.linked.sum -s packages/angular_components/framework_stabilizers/testability.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/dom_service_webdriver_testability.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/dom_service/angular_2.template.dartdevc.linked.sum -s packages/angular_components/utils/browser/window/module.template.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/module.template.dartdevc.linked.sum -s packages/angular_components/laminate/overlay/overlay.template.dartdevc.linked.sum -s packages/angular_components/laminate/popup/module.template.dartdevc.linked.sum -s packages/angular_components/mixins/material_dropdown_base.template.dartdevc.linked.sum -s packages/angular_components/utils/id_generator/id_generator.template.dartdevc.linked.sum -s packages/angular_components/material_popup/material_popup.scss.css.shim.dartdevc.linked.sum -s packages/angular_components/material_popup/material_popup.template.dartdevc.linked.sum -s packages/angular_components/material_tooltip/module.template.dartdevc.linked.sum -s packages/angular_components/src/material_tooltip/icon_tooltip.dartdevc.linked.sum -s packages/angular_components/material_tooltip/material_tooltip.dartdevc.linked.sum -s packages/angular_components/model/date/date_formatter.dartdevc.linked.sum -s packages/angular_components/utils/angular/managed_zone/interface.dartdevc.linked.sum -s packages/async/async.dartdevc.linked.sum -s packages/angular_components/utils/showhide/showhide.dartdevc.linked.sum -s packages/angular_components/material_datepicker/date_range_editor.dartdevc.linked.sum -s packages/angular_components/material_datepicker/config.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_date_range_picker.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_datepicker.dartdevc.linked.sum -s packages/angular_components/model/selection/string_selection_options.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_time_picker.dartdevc.linked.sum -s packages/angular_components/material_datepicker/material_date_time_picker.dartdevc.linked.sum -s packages/angular_components/material_dialog/material_dialog.dartdevc.linked.sum -s packages/angular_components/material_spinner/material_spinner.dartdevc.linked.sum -s packages/angular_components/material_yes_no_buttons/material_yes_no_buttons.dartdevc.linked.sum -s packages/angular_components/material_expansionpanel/material_expansionpanel.dartdevc.linked.sum -s packages/angular_components/material_expansionpanel/material_expansionpanel_auto_dismiss.dartdevc.linked.sum -s packages/angular_components/material_expansionpanel/material_expansionpanel_set.dartdevc.linked.sum -s packages/angular_components/material_input/input_wrapper.dartdevc.linked.sum -s packages/angular_components/model/ui/highlighted_text_model.template.dartdevc.linked.sum -s packages/angular_components/highlighted_text/highlighted_text.scss.css.shim.dartdevc.linked.sum -s packages/angular_components/highlighted_text/highlighted_text.template.dartdevc.linked.sum -s packages/angular_components/model/ui/has_renderer.template.dartdevc.linked.sum -s packages/angular_components/model/ui/highlight_provider.template.dartdevc.linked.sum -s packages/angular_components/highlighted_text/highlighted_value.template.dartdevc.linked.sum -s packages/angular_components/model/ui/highlight_assistant.dartdevc.linked.sum -s packages/angular_components/mixins/highlight_assistant_mixin.dartdevc.linked.sum -s packages/angular_components/stop_propagation/stop_propagation.dartdevc.linked.sum -s packages/angular_components/material_input/material_auto_suggest_input.dartdevc.linked.sum -s packages/angular_components/material_input/material_input_error_keys.dartdevc.linked.sum -s packages/angular_components/material_input/material_number_validators.dartdevc.linked.sum -s packages/angular_components/material_input/material_number_accessor.dartdevc.linked.sum -s packages/angular_components/material_input/material_percent_directive.dartdevc.linked.sum -s packages/quiver/iterables.dartdevc.linked.sum -s packages/quiver/collection.dartdevc.linked.sum -s packages/built_collection/built_collection.dartdevc.linked.sum -s packages/angular_components/model/collection/combined_list.dartdevc.linked.sum -s packages/angular_components/model/menu/menu_item_affix.dartdevc.linked.sum -s packages/angular_components/model/menu/menu.dartdevc.linked.sum -s packages/angular_components/material_menu/menu_popup_wrapper.dartdevc.linked.sum -s packages/angular_components/material_menu/menu_root.dartdevc.linked.sum -s packages/angular_components/material_menu/menu_item_affix_list.dartdevc.linked.sum -s packages/angular_components/model/menu/selectable_menu.dartdevc.linked.sum -s packages/angular_components/material_menu/material_menu.dartdevc.linked.sum -s packages/angular_components/material_menu/dropdown_menu.dartdevc.linked.sum -s packages/angular_components/material_menu/material_fab_menu.dartdevc.linked.sum -s packages/angular_components/material_progress/material_progress.dartdevc.linked.sum -s packages/angular_components/material_radio/material_radio.dartdevc.linked.sum -s packages/angular_components/material_select/display_name.dartdevc.linked.sum -s packages/angular_components/material_select/material_dropdown_select_accessor.dartdevc.linked.sum -s packages/angular_components/material_select/material_select_searchbox.dartdevc.linked.sum -s packages/quiver/check.dartdevc.linked.sum -s packages/angular_components/material_slider/material_slider.dartdevc.linked.sum -s packages/angular_components/material_stepper/material_step.dartdevc.linked.sum -s packages/angular_components/material_stepper/common.dartdevc.linked.sum -s packages/angular_components/src/utils/angular/scroll_host/scroll_host_interface.dartdevc.linked.sum -s packages/angular_components/utils/angular/scroll_host/interface.dartdevc.linked.sum -s packages/angular_components/src/utils/angular/scroll_host/pan_controller_impl.dartdevc.linked.sum -s packages/angular_components/utils/angular/scroll_host/angular_2.dartdevc.linked.sum -s packages/angular_components/material_stepper/material_stepper.dartdevc.linked.sum -s packages/angular_components/material_tab/tab_mixin.dartdevc.linked.sum -s packages/angular_components/material_tab/tab_button.dartdevc.linked.sum -s packages/angular_components/material_tab/tab_change_event.dartdevc.linked.sum -s packages/angular_components/material_tab/fixed_material_tab_strip.dartdevc.linked.sum -s packages/angular_components/material_tab/material_tab.dartdevc.linked.sum -s packages/angular_components/material_tab/material_tab_panel.dartdevc.linked.sum -s packages/angular_components/src/material_tree/group/material_tree_group.dartdevc.linked.sum -s packages/angular_components/material_tree/material_tree.dartdevc.linked.sum -s packages/angular_components/reorder_list/reorder_events.dartdevc.linked.sum -s packages/angular_components/utils/keyboard/keyboard.dartdevc.linked.sum -s packages/angular_components/reorder_list/reorder_list.dartdevc.linked.sum -s packages/angular_components/utils/color/palette.dartdevc.linked.sum -s packages/angular_components/scorecard/scorecard.dartdevc.linked.sum -s packages/angular_components/scorecard/scorecard_bar.dartdevc.linked.sum -s packages/angular_components/scorecard/scoreboard.dartdevc.linked.sum -s packages/angular_components/angular_components.dartdevc.linked.sum -s packages/charcode/ascii.dartdevc.linked.sum -s packages/charcode/html_entity.dartdevc.linked.sum -s packages/charcode/charcode.dartdevc.linked.sum -s packages/term_glyph/term_glyph.dartdevc.linked.sum -s packages/source_span/source_span.dartdevc.linked.sum -s packages/string_scanner/string_scanner.dartdevc.linked.sum -s packages/typed_data/typed_buffers.dartdevc.linked.sum -s packages/typed_data/typed_data.dartdevc.linked.sum -s packages/http_parser/http_parser.dartdevc.linked.sum -s packages/http/src/base_client.dartdevc.linked.sum -s packages/http/http.dartdevc.linked.sum -s packages/ThisApp/common/http/IHttpClient.dartdevc.linked.sum -s packages/ThisApp/common/constants.dartdevc.linked.sum -s packages/ThisApp/common/http/JwtHttpClient.dartdevc.linked.sum -s packages/ThisApp/common/core/base_core.dartdevc.linked.sum -s packages/ThisApp/common/core/base_component.dartdevc.linked.sum -s packages/ThisApp/common/core/page_component.dartdevc.linked.sum --url-mapping=package:ThisApp/page/member/daummap/page.dart,packages/ThisApp/page/member/daummap/page.dart package:ThisApp/page/member/daummap/page.dart
    dart --version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4361:50)
#2      CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4545:12)
#3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7064:15)
#4      CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5853:18)
#5      CodeGenerator.visitNamedExpression (package:dev_compiler/src/analyzer/code_generator.dart:4092:46)
#6      CodeGenerator._emitArgumentList (package:dev_compiler/src/analyzer/code_generator.dart:4075:19)
#7      CodeGenerator.visitInstanceCreationExpression.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:4548:15)
#8      CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4360:31)
#9      CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4545:12)
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7064:15)
#11     CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5853:18)
#12     CodeGenerator.visitNamedExpression (package:dev_compiler/src/analyzer/code_generator.dart:4092:46)
#13     CodeGenerator._emitArgumentList (package:dev_compiler/src/analyzer/code_generator.dart:4075:19)
#14     CodeGenerator.visitInstanceCreationExpression.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:4548:15)
#15     CodeGenerator._emitInstanceCreationExpression.emitNew (package:dev_compiler/src/analyzer/code_generator.dart:4366:31)
#16     CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4405:51)
#17     CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4545:12)
#18     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7064:15)
#19     CodeGenerator.visitExpressionStatement (package:dev_compiler/src/analyzer/code_generator.dart:4125:23)
#20     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4259:49)
#21     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#22     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#23     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#24     CodeGenerator._visitStatementList (package:dev_compiler/src/analyzer/code_generator.dart:5869:41)
#25     CodeGenerator.visitBlockFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:3612:21)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195:49)
#27     CodeGenerator._emitFunctionScopedBody (package:dev_compiler/src/analyzer/code_generator.dart:2829:22)
#28     CodeGenerator._emitFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:2812:17)
#29     CodeGenerator._emitFunction (package:dev_compiler/src/analyzer/code_generator.dart:2796:11)
#30     CodeGenerator._emitMethodDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:2592:12)
#31     CodeGenerator._emitClassMethods (package:dev_compiler/src/analyzer/code_generator.dart:1497:23)
#32     CodeGenerator._emitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:852:21)
#33     CodeGenerator.visitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:811:12)
#34     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#35     CodeGenerator._emitTypeDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:544:26)
#36     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:598:9)
#37     List.forEach (dart:core/runtime/libarray.dart:106:8)
#38     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:336:22)
#39     compileWithAnalyzer (package:dev_compiler/src/analyzer/module_compiler.dart:107:33)
#40     _compile (package:dev_compiler/src/analyzer/command.dart:152:16)
#41     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#42     compile (package:dev_compiler/src/compiler/shared_command.dart:385:18)
#43     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:39)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:24)
<asynchronous suspension>
#49     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#55     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#56     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
#57     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
}

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by natebosch** [comment]
I suspect this is most likely related to misusing js interop - we are missing some static checking around things like using only named arguments in an `@anonymous` factory constructor.

Do you get any errors when compiling with dart2js ("--release" mode in build_runner)?
Do you get any errors if you upgrade to `build_web_compilers` version 2.0.0?
