### ISSUE TITLE
VM: Handle late evaluation of environment constants

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36306]
When we integrate the new constant evaluator into the front end (enabled by the `constant-update-2018` flag), the front end has the option to compile without an environment, leaving all `fromEnvironment` constants unevaluated. The resulting dlll file contains `UnevaluatedConstant` nodes in the constant pool for all `fromEnvironment` constants in the program. The expression inside that `UnevaluatedConstant` is the root of the constant expression that contains the environment constant.

The VM needs to evaluate such constants when given a dill file. As a first (somewhat inefficient) implementation, we can do it like this:
1. As the first thing after loading the file into memory, search the constant pool for the occurrence of any `UnevaluatedConstant`.
2. If any constants are unevaluated, send the binary blob to a Dart isolate, which will deserialize it, run the constant evaluator, serialize it and send it back.
3. Replace the original binary blob by the fully evaluated one, then continue loading.

There are of course several ways in which this procedure can be optimized going forward, for instance:
- Add a global flag in the dill file to indicate the presence of unevaluated constants. I am not quite sure where that would go, as the format doesn't seem to have a global flags field, so we would need to add one.
- Only send over as much information as necessary to perform the constant evaluation. Merge the result back into the loaded data.
- Integrate with the ongoing work on on-demand instantiation of constants, so constants are only evaluated when needed.

We will want to avoid doing this for the platform dill. See https://github.com/dart-lang/sdk/issues/36307

**Comment by kmillikin** [comment]
The VM team would prefer that for the 2.3 release we would not write unevaluated constants to .dill files intended for the VM.  We can move this to a post 2.3 milestone.  Do you agree @askeksa-google ?

**Comment by askeksa-google** [comment]
This is fine as long as we are not breaking anyone's workflow by removing the possibility to do late evaluation of environment constants in the VM.

Anyone depending on this feature will have to change their process to either supply the environment early or use runtime environment lookup (using `new String.fromEnvironment` and friends), or some combination.

This will also make it all the more essential to fix https://github.com/dart-lang/sdk/issues/36307.

**Comment by a-siva** [comment]
We don't plan on supporting this in 2.3 and would like to evaluate if this is really needed considering that the front end isolate runs with the same environment as the VM when we execute Dart programs from source.

**Comment by a-siva** [comment]
There are no plans to implement late evaluation of environment constants, with the constant-update-2018 flag all evaluations will happen in the CFE. Please see https://github.com/dart-lang/sdk/issues/36579 for more details.
