### ISSUE TITLE
VM: Build separate platform dills for different VM configurations

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36307]
Due to https://github.com/dart-lang/sdk/issues/36306 we want to avoid late evaluation of environment constants in the VM for the platform dill.

Environment constants are used in the platform dill to distinguish between product and release mode in the VM.

One way to achieve this is to build separate, fully evaluated, versions of the platform dill for the different VM configurations, plus an unevaluated one for the AOT compiler.

**Comment by askeksa-google** [comment]
A bit more detail (under the assumption that we are not doing https://github.com/dart-lang/sdk/issues/36306):

As far as I know, when we generate kernel for the platform, we don't supply an environment to the front end (via the `environmentDefines` field in `CompilerOptions`), which means that when we enable the constant evaluator in the front end (by flipping the flag), all environment constants will be left unevaluated. The VM does not understand these unevaluated constants.

Thus, for dill files targeted for direct consumption by the VM, an environment needs to be supplied when building the kernel, so that environment constants are fully evaluated. The environment doesn't have to encompass all names referenced. The ones not present in the provided environment will get default values.

The AOT compiler needs these environment constants unevaluated, so the platform dill supplied to the AOT compiler must be compiled without supplying an environment.

Apparently, the uses of environment constants in the VM platform are these:
```
sdk/lib/developer/profiler.dart:137:  @pragma("vm:entry-point", !const bool.fromEnvironment("dart.vm.product"))
sdk/lib/developer/timeline.dart:8:    const bool.fromEnvironment("dart.developer.timeline", defaultValue: true);
sdk/lib/vmservice/vmservice.dart:45:final bool useAuthToken = const bool.fromEnvironment('DART_SERVICE_USE_AUTH');
sdk/lib/vmservice/vmservice.dart:711:@pragma("vm:entry-point", !const bool.fromEnvironment("dart.vm.product"))
```

Possibly, some of these are only relevant for AOT. Those can just be given whatever values for the VM platform. If any of these should be given different values for different VM configurations, then the corresponding environment given to the compiler when generating the platform dills must be different accordingly.

**Comment by dgrove** [comment]
@aam @a-siva is this required for 2.3? If it is, can you please mark as P1?

**Comment by aam** [comment]
It seems that (per https://github.com/dart-lang/sdk/blob/master/pkg/vm/bin/kernel_service.dart#L166), all environment variable values specified on the command line vm will be passed to the compiler that it can use for constant evaluation. So the only work here is to make sure that we do set correct environment variables("dart.vm.product") when building "release"(or "product" for flutter) platform dill.

**Comment by aam** [comment]
@askeksa-google can you please confirm that `!const bool.fromEnvironment("dart.vm.product")` is being evaluated by frontend (when running with `--enable-experiment=constant-update-2018`). I'm still seeing ```@core::pragma::_("vm:entry-point", !const core::bool::fromEnvironment("dart.vm.product"))
   static method _printMetrics() → core::String {``` in the generated kernel file.

**Comment by askeksa-google** [comment]
Yes, when the front end is given the constant update flag, it evaluates all constants. It has two modes of operations for this:
- If the `environmentDefines` field in the compiler options contains a map, it uses this map to look up environment constants. Environment variables not found in the map will get default values.
- If the `environmentDefines` field in the compiler options is `null`, it leaves environment constants (and constants that depend on them) unevaluated, but still moves them to the constant pool.

In both cases, you should not see the `const bool.fromEnvironment("dart.vm.product")` expression inside the annotation.

It looks like the flag was not properly enabled for the front-end run. How did you enable it?

The `EnvironmentMap` class in `kernel_service.dart` that you point to is used in JIT mode to provide the VM runtime environment as the compile-time environment for the front end. I would expect that this code is not involved when building the platform.

**Comment by aam** [comment]
> It looks like the flag was not properly enabled for the front-end run. How did you enable it?

I added `--enable-experiment=constant-update-2018` to dart command line that invoked comple_platform.dart that builds platform.dill:

```
$FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart -Ddart.vm.product=true --enable-experiment=constant-update-2018 --packages=$FH/engine/src/third_party/dart/.packages --dfe=$FH/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot $FH/engine/src/third_party/dart/pkg/front_end/tool/_fasta/compile_platform.dart dart:core --single-root-scheme=org-dartlang-sdk --single-root-base=$FH/engine/src/third_party/dart/ org-dartlang-sdk:///sdk/lib/libraries.json vm_outline_strong.dill vm_platform_strong.dill vm_outline_strong.dill
```
