### ISSUE TITLE
Command line needs error messaging

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#36312]
Command I was running:
`dart test_app.dart --observe=8888`
Command I should have been running:
`dart --observe=8888 test_app.dart`

It would be really helpful if there was some error messaging to help correct this mistake, as this cost me a few hours of productivity trying to figure out why I couldn't connect to the Observatory. I went down a rabbit hole of networking issues, downloading different dart sdks, etc., when all I needed to do is reformat my command.

Thanks!

**Comment by mraleph** [comment]
It's a bit unclear how VM is supposed to detect the error, because `--observe=8888` can easily be command line flag passed to your `test_app.dart`, e.g.

```dart
void main(args) {
  final shouldObserve = args.contains('--observe=8888');
}
```

I do notice that `dart --help` is a bit confusing:

```
Usage: dart [<vm-flags>] <dart-script-file> [<dart-options>]

Executes the Dart script passed as <dart-script-file>.

Common options:
....
--observe[=<port>[/<bind-address>]]
```

I think we should update it to 

```
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
....
--observe[=<port>[/<bind-address>]]
```

**Comment by a-siva** [comment]
I believe the VM is working as intended, will use this issue to make changes to the help message as 
 suggested by @mraleph
