### ISSUE TITLE
Why is the string encoding of darts utf-16, not utf-8?

### ISSUE THREAD

**Issue by jiankafei** [dart-lang/sdk#36316]
Why is the string encoding of darts utf-16, not utf-8?

**Comment by lrhn** [comment]
Historical reasons and JavaScript compatibility.

Dart was designed to be usable in a browser, and still is using the dart2js compiler. 
If the Dart string was signficiantly different from the JavaScript string, this compilation would have been horribly inefficient at string operations. For that reason, the Dart string matches the JavaScript string (and the Java and C# strings for that matter).

**Comment by elansys-kc** [comment]
Isn't compilation less important than enforcing run-time conversions from system languages, or are you suggesting utf-16 should be used everywhere. This explanation seems inadequate, though perhaps it alludes to a pain point with Android?. Perhaps a link would be better? I am trying to consider how best to limit conversions between System services, Golang and Dart. In this case Dart/C#/Java, seem to be the odd balls.

This stackoverflow suggests utf-8 should be used for security reasons and it's link suggests utf-8 is expected for the web moving forwards?

https://stackoverflow.com/questions/4655250/difference-between-utf-8-and-utf-16
https://encoding.spec.whatwg.org/

**Comment by sh4wn** [comment]
UTF16 sucks.
