### ISSUE TITLE
Make "Convert to block/expression body" assist higher priority than "Convert to async function body"

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#36327]
In my personal experience, when both assists are available, I almost always want to convert between block/expression bodies, and not convert to an async function.

I mostly use this assist to edit expression functions. For example, editing a function passed into `Iterable.map`:

<img width="336" alt="Screen Shot 2019-03-24 at 1 58 44 PM" src="https://user-images.githubusercontent.com/1713967/54885754-04157f00-4e3d-11e9-812d-65d8034e8343.png">

Making these async functions is almost never something I want to do, so it's frustrating that it comes up as the first option (whereas in Dart 1, before the "convert to async" assist was added, the assist to convert between block/expression was first in the list).

Semi-related: https://github.com/dart-lang/sdk/issues/35636

**Comment by bwilkerson** [comment]
I agree. In fact, I probably wouldn't have noticed #35636 if I hadn't kept accidentally selecting "convert to async" when I didn't want it.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/97840

**Comment by greglittlefield-wf** [comment]
@bwilkerson I'm not seeing any change in behavior ("convert to async" is still first) in Dart 2.3.0, which has these changes 😢

**Comment by bwilkerson** [comment]
@jwren Does IntelliJ use the priority information returned with the assists? If not, can it?

**Comment by greglittlefield-wf** [comment]
For more info, I'm also seeing this in VS Code on Dart 2.3.0
<img width="341" alt="Screen Shot 2019-05-13 at 7 04 46 AM" src="https://user-images.githubusercontent.com/1713967/57627765-73f6da80-754d-11e9-995c-644fdb1b629a.png">
