### ISSUE TITLE
 Auto class loader, similar to php. for lazy instantiation of objects

### ISSUE THREAD

**Issue by JhulFramework** [dart-lang/sdk#36331]
In My Application I just want to register classes and instantiate them only when needed. it will improve performance of app.
Please implement this if it is possible.

https://www.php.net/manual/en/language.oop5.autoload.php

Thank you

**Comment by eernstg** [comment]
Take a look at the section 'Lazily loading a library' in the [language tour](https://www.dartlang.org/guides/language/language-tour).
