### ISSUE TITLE
Flutter / Flutter Web rolls blocked by CFE: '@method::... is already bound'

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36338]
As of last Friday we are getting errors from kernel on our bleeding edge bots in package:build that look like the following:

```
Unable to spawn isolate: root::package:code_builder/src/specs/code.dart::Block::@methods::accept is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:161:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:913:48)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:423:14)
#3      LimitedBinaryPrinter.computeCanonicalNames (package:kernel/binary/limited_ast_to_binary.dart:36:17)
#4      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:518:5)
#5      serializeComponent (package:front_end/src/fasta/kernel/utils.dart:69:11)
#6      _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:593:11)
```

I also saw a separate report for flutter:

```
root::package:flutter/src/rendering/proxy_box.dart::_RenderProxyBox&RenderBox&RenderObjectWithChildMixin::@methods::handleEvent is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:161:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:913:48)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:423:14)
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:5724:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:5718:7)
#5      FrontendCompiler.writeDillFile (package:vm/frontend_server.dart:410:15)
```

I wasn't able to get an isolated repro, but you can repro the `code_builder` failure by simply importing `package:code_builder/code_builder.dart` and trying to run that script with the bleeding edge Dart VM.

**Comment by vsmenon** [comment]
@a-siva - is this blocking flutter rolls as well now?  See flutter trace against bleeding edge above.

**Comment by vsmenon** [comment]
Tentatively marking as 2.3.

**Comment by bkonyi** [comment]
@vsmenon this is blocking the Dart SDK roll into the Flutter engine. This is a high priority (critical?) issue.

**Comment by vsmenon** [comment]
thanks - @kmillikin @a-siva @aadilmaan - is someone on this?

**Comment by mraleph** [comment]
@stefantsov was working on this and landed a fix (which turned out to be partial) 

I am reverting offending CL because the underlying problem was not resolved during today.

**Comment by mraleph** [comment]
The revert is in CQ https://dart-review.googlesource.com/c/sdk/+/97802

**Comment by mraleph** [comment]
The change has been reverted.
