### ISSUE TITLE
[ffi] Define safepoint semantics of FFI calls.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36339]
Native calls (e.g. through native extensions) are treated as safepoints; while the thread in running C, any other thread is free to initiate a GC. However, transitioning into and out of a safepoint on the boundary to native calls is expensive and technically difficult to implement for FFI calls. Therefore we currently do *not* enter a safepoint when running FFI code. This means that a long-running FFI will prevent other threads from initiating a GC (unless it calls back into the Dart API).

We need to decide what the default safepoint semantics should be, and implement an ability to choose (no safepoint for fast calls, safepoint for slow/long-running calls).

**Comment by sjindel-google** [comment]
@mraleph @dcharkes

**Comment by dcharkes** [comment]
This could be a flag communicated by a type argument, in the same spirit as whether a function is leaf or not (from the dart:ffi vision doc).
