### ISSUE TITLE
language_2/spread_collections/runtime_error_test fails in AOT and app-jit modes

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36348]
The new test language_2/spread_collections/runtime_error_test fails in AOT and app-jit modes.
This test was added in 419243fc4e66d2804131cd1db717b2da6433d01f and it tests type checks in spread collections.

It looks like kernel AST is not entirely correct here:

```
    dynamic wrongIterableType = <core::String>["s"];
    exp::Expect::throwsTypeError(() → core::List<core::int> => block {
      final core::List<core::int> #t12 = <core::int>[];
      for (final core::int #t13 in wrongIterableType as{TypeError} core::Iterable<dynamic>)
        [@vm.call-site-attributes.metadata=receiverType:dart.core::List<dart.core::int>] #t12.{core::List::add}(#t13);
    } =>#t12);
```

Variable `final core::int #t13` has static type `int`, but types of values from iterable are not checked.

/cc @kmillikin @stefantsov @aartbik

**Comment by kmillikin** [comment]
@stefantsov it looks like we're missing the downcast we need on the elements of the iterable for for-in.  I suppose the bug is in the translation to block expressions.  You can take a look at the code we generate for the corresponding for-in statement to see what it should be.

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/98003.

**Comment by stefantsov** [comment]
The CL is currently in review.
