### ISSUE TITLE
fail to open Dart SDK repo with IntelliJ

### ISSUE THREAD

**Issue by wxCUHK** [dart-lang/sdk#36344]
hi, I am working on Mac OS. I found a problem with opening the Dart SDK repo by following this instruction :
**_To open the sdk repo using IntelliJ, choose File > Open... and select the <sdk>/client/idea directory._**
This results in an empty project.
![image](https://user-images.githubusercontent.com/16485217/54996442-476e1a00-5004-11e9-88c7-fe0446280359.png)

**Comment by kevmoo** [comment]
Where did you get these instructions?
