### ISSUE TITLE
DateTime.difference() documentation could be clearer; why not have operator-?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36347]
The documentation to [DateTime.difference](https://api.dartlang.org/stable/2.2.0/dart-core/DateTime/difference.html) could be clearer about how the difference is computed.  That is, instead of :

> Returns a [Duration] with the difference between [this] and [other].

I think it'd be better as:

> Returns a [Duration] with the difference subtracting [other] from [this].

Or instead of relying on readers to deduce it from the example code, explicitly state:

> The returned [Duration] will be negative if [other] occurs after [this].

Even better would be to provide an `operator -` that allows one `DateTime` to be subtracted from the other without ambiguity.

(Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64")

**Comment by lrhn** [comment]
The `operator-` on `DateTime` is taken by `operator-(Duration difference)`, so we can't also use it to subtract a `DateTime`.
Apart from that, we should update the documentation.

**Comment by jamesderlin** [comment]
`Duration` has as `operator-(Duration other)`, but I don't see any `operator-(Duration difference)` listed for [DateTime](https://api.dartlang.org/stable/2.2.0/dart-core/DateTime-class.html).  Am I looking in the wrong place?

**Comment by lrhn** [comment]
No, my bad. I was probably thinking of `Duration`.
