### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Skyost** [dart-lang/sdk#36353]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\Hugo\Projets\Flutter\bacomathiques\lib\main.dart context: exception_20190327_130809_416
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:109:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#11     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#14     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2605:22)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:920:20)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1643:20)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#23     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#25     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#26     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#27     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#28     _relink (package:analyzer/src/summary/link.dart:305:57)
#29     link (package:analyzer/src/summary/link.dart:123:3)
#30     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#32     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#33     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#44     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#50     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#51     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#52     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#54     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#55     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## Additional information

Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\Hugo\Projets\Flutter\bacomathiques\lib\main.dart context: exception_20190327_130809_416
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:109:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#11     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#14     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2605:22)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:920:20)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1643:20)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#23     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#25     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#26     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#27     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#28     _relink (package:analyzer/src/summary/link.dart:305:57)
#29     link (package:analyzer/src/summary/link.dart:123:3)
#30     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#32     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#33     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#44     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#50     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#51     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#52     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#54     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#55     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
1553688462975 started analysis server:
  D:\Hugo\Programmes\Flutter\bin\cache\dart-sdk\bin\dart.exe D:\Hugo\Programmes\Flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-18
1553688465760 <= {"event":"server.connected","params":{"version":"1.23.0","pid":12756,"sessionId":""}}
1553688465804 <= {"id":"0","result":{"version":"1.23.0"}}
1553688465806 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1553688463106}
1553688465806 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1553688465806 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["D:\\Hugo\\Projets\\Flutter\\bacomathiques","D:\\Hugo\\Projets\\Flutter\\bacomathiques\\android"],"excluded":["D:\
1553688465806 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\lesson.dart"]},"clientRequestTime":1553688463218}
1553688465806 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\lesson.dart"],"CLOSING_LABELS":["D:\\Hugo\\Proj
1553688465810 <= {"id":"1"}
1553688465815 <= {"id":"2"}
1553688466454 <= {"event":"analysis.errors","params":{"file":"D:\\Hugo\\Projets\\Flutter\\bacomathiques\\pubspec.yaml","errors":[]}}
1553688467187 <= {"id":"3"}
1553688467189 <= {"id":"4"}
1553688467202 <= {"id":"5"}
1553688467228 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1553688467453 => {"id":"6","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1553688467453}
1553688478399 <= {"id":"6","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1553688478486 <= {"event":"analysis.errors","params":{"file":"D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\app.dart","errors":[]}}
1553688486871 => {"id":"7","method":"analysis.setPriorityFiles","params":{"files":["D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\util.dart"]},"clientRequestTime":1553688486871}
1553688486872 => {"id":"8","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\util.dart"],"CLOSING_LABELS":["D:\\Hugo\\Projet
1553688489740 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\Hugo\\Projets\\Flutter\\bacomathiques\\lib\\main.dart context: exception_20190327_130809_416","stackT
```

**Comment by parlough** [comment]
Seems to be the same issue as https://github.com/dart-lang/sdk/issues/36872

Likely fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f
