### ISSUE TITLE
await for of a stream that is null does not produce an error

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36359]
According to the spec an _await for_ statement like the following should produce a run time error. 

I haven't seen any implementation that actually does so. The vm, dart2js and ddc all continue silently without executing the body and produce the same output.

```dart
import 'dart:async';

// Prints:
// before await for
// after await for
main() async {
  Stream nullStream = null;

  print('before await for');
  await for (var i in nullStream) {
    print(i);
  }
  print('after await for');
}
```

**Comment by kevmoo** [comment]
CC @lrhn – didn't you just fix something like this?

**Comment by lrhn** [comment]
It's a breaking change, and it hasn't landed yet, but otherwise yes.

**Comment by lrhn** [comment]
This has been fixed, you can no longer use a `null` value in the stream position.
