### ISSUE TITLE
Dart_StringToCString expects argument 'object' to be non-null.

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36362]
Perhaps this is expected behavior, but a program like

```dart
main() {
  FileSystemEntity.identicalSync(null, '');
}

```
gives the somewhat cryptic error message from a native CC implementation.

`Dart_StringToCString expects argument 'object' to be non-null.`

I am not sure if this is worth fixing, but I assume a typical Dart programmer would expect a somewhat more "Darty" exception message when this happens.

@a-siva

**Comment by mraleph** [comment]
This seems to be a `dart:io` dev-experience issue.

**Comment by sortie** [comment]
dart:io is full of these issues. I took a first pass and fixed many of them (and wrote tests). I'll continue work at some other time and make sure I got all of them.

I'm considering it a bug that any user input to dart:io can cause aborts like this in the VM code. Does errors like this shut down the whole process or just the isolate?

**Comment by liamappelbe** [comment]
I think this bug is obsolete, now that dart:io is null safe: https://api.dart.dev/stable/2.13.4/dart-io/FileSystemEntity/identicalSync.html
