### ISSUE TITLE
Encountered a Dart Analysis Server error?

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#36367]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6183.87`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Captured exception
NoSuchMethodError: The method 'refresh' was called on null.
Receiver: null
Tried calling: refresh(Instance of 'DeclarationsContext')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:611:15)
#2      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:473:7)
#3      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:177:13)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#9      Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#15     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#16     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#17     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/pp/w8543ckd5_xf_s2917gmwb0m0000gn/T/report.txt.

**Comment by DanTup** [comment]
Are you using a Dart nightly build? I think upgrading to a more recent one will fix it - it looks like #36212.

**Comment by NTMS2017** [comment]
I am using stable version, and I just made a clean install IDEA IC-191.6183.87  (2019.01 Community Edition) I will post my flutter doctor -v here in 10 min

**Comment by NTMS2017** [comment]
I get same error twice today. I couldn't catch first one why its happened. But second one once I use reload to my Samsung device I enter some wrong text to text field and when I use my mobile backspace to delete the test it happened again.

Here is my Flutter Doctor -v

flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale tr-CY)
    • Flutter version 1.2.1 at /users/niyazitoros/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

**Comment by DanTup** [comment]
Oh, I see - I was confused by the Dart SDK version in the first report - it shows `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`, though I see this was actually the version that shipped in Flutter, it's just recorded different in the error report.

Looking at the fix, using `part of library` instead of `part of 'file.dart'` might stop the issue (though generally it's encouraged to use file paths instead of library names!). You could also switch to another Flutter branch (like dev) - however that may be less stable than the stable version.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/36212

**Comment by NTMS2017** [comment]
Thanks for the info

**Comment by Harbdollar** [comment]
Restart your Android studio or visual code. 
If not fix, Shut down your System and pull it on back.
