### ISSUE TITLE
isAnalyzing quirks: startup delay, yaml order, plugins excluded

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36378]
On an example codebase in google3, this is the timing of restarting the analyzer:

- 6 seconds go by with no feedback (perhaps VM startup time?)
- analysis_options.yaml warnings appear with no other feedback
- 15 more seconds go by **before** the "analyzing" bar appears
- dart analysis finishes much later
- "analyzing" disappears
- plugins start analyzing with no feedback

Ideally it would look more like:

- <1 seconds go by
- "analyzing" bar appears
- we probably only want analysis_options.yaml warnings to appear first if the user has that file open
- dart finishes, probably with some feedback
- plugins begin, with some feedback (perhaps just "analyzing" sticks around, but better yet, "running plugins" or something)

**Comment by keertip** [comment]
This will need to be evaluated at current version as this issue was opened quite a while back. Closing as obsolete.
