### ISSUE TITLE
Support --inline-source-map in ddc kernel backend

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36385]
Sorry for such a late addition to the 2.3 milestone but it looks like to get source maps working fully (in package:test primarily), we will need the `--inline-source-map` option enabled in the kernel backend for ddc.

cc @jmesserly @vsmenon 

We could decide to punt on this and accept js stack traces for tests, but it would be good to get in. There may also be other scenarios outside of testing where the inline source maps are required though.

**Comment by jakemac53** [comment]
fwiw the command line option doesn't seem to throw (like it used to I believe), but it doesn't seem to be outputting the source map either

**Comment by jakemac53** [comment]
Actually nevermind these are being included - we just need to map the uris to something that make sense (we already do this for normal source maps but need to do the same mapping in the dart stack trace mapper code, which we have control of outside of the sdk).

**Comment by jmesserly** [comment]
Nice! Yeah, I implemented that flag in the same CL as trackLibraries.
