### ISSUE TITLE
CFE sometimes doesn't perform loop variable inference inside for/if expressions in collections.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36395]
For the snippet:
```
import 'expect.dart';

void main() {
  Expect.type<List<int>>([for (var i = 1; i < 2; i++) i]);
}
```
The CFE generates something like:
```
  static method main() → void {
    exp::Expect::type<core::List<core::int>>( block {
      final core::List<dynamic> #t1 = <dynamic>[];
      for (dynamic i = 1; i.<(2) as{TypeError} core::bool; i = i.+(1))
        #t1.{core::List::add}(i);
    } =>#t1);
  }
```

This fails with "List\<dynamic\> is not a List\<int\>". We'd expect `i` to be an int in this context instead of dynamic. 

A related issue is that casts aren't emitted for the loop variable:
```
import 'expect.dart';

void main() {
  dynamic nonInt = "string";
  for (int i = nonInt; false; ) {}
  var x = <int>[for (int i = nonInt; false;) 1];
}
```
generates
```
  static method main() → void {
    dynamic nonInt = "string";
    for (core::int i = nonInt as{TypeError} core::int; false; ) {
    }
    core::List<core::int> x = block {
      final core::List<core::int> #t1 = <core::int>[];
      for (core::int i = nonInt; false; )
        #t1.{core::List::add}(1);
    } =>#t1;
  }
```

Which is missing the type check.

Similarly for if expressions:
```
import 'expect.dart';

void main() {
  dynamic nonBool = 3;
  if (nonBool) {}
  Expect.throwsTypeError(() => <int>[if (nonBool) 1]);
}
```
which generates:
```
  static method main() → void {
    dynamic nonBool = 3;
    if(nonBool as{TypeError} core::bool) {
    }
    exp::Expect::throwsTypeError(() → core::List<core::int> => block {
      final core::List<core::int> #t1 = <core::int>[];
      if(nonBool)
        #t1.{core::List::add}(1);
    } =>#t1);
  }
```

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/98333.

**Comment by kmillikin** [comment]
It looks like we fixed the first part of this but not yet the issue with if elements (fixed by [CL 98484](https://dart-review.googlesource.com/c/sdk/+/98484)).

@Markzipan you might avoid editing the original issue to add substantial new information (save edits for fixing typos) and instead add new information as a follow up comment --- the email notification just gives the original and we don't necessarily see or get notified of your edits.

**Comment by Markzipan** [comment]
@kmillikin That's my bad! I had mistakenly thought both issues were the same underlying problem (why insert casts for dynamic types?).
