### ISSUE TITLE
Test results changes after CFE changes

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#36394]
To get our CI builders green I have approved the following test changes:

| BOT                               | TEST                                                                           | RESULT           | EXPECTED         | 
| --------------------------------- | ------------------------------------------------------------------------------ | ---------------- | ---------------- | 
| front-end-linux-release-x64/fasta | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/01  | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/03  | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/04  | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | co19_2/LanguageFeatures/Set-literals/disambiguating_A06_t01/03                 | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/control_flow_collections/if_const_error_test/23                     | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/control_flow_collections/if_const_error_test/24                     | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/control_flow_collections/if_const_error_test/35                     | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/control_flow_collections/if_const_error_test/36                     | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/control_flow_collections/if_const_error_test/37                     | Pass             | CompileTimeError |
| front-end-linux-release-x64/fasta | language_2/spread_collections/const_error_test/13                              | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/01  | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/03  | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/04  | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | co19_2/LanguageFeatures/Set-literals/disambiguating_A06_t01/03                 | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/23                     | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/24                     | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/35                     | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/36                     | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/37                     | Pass             | CompileTimeError |
| front-end-mac-release-x64/fasta   | language_2/spread_collections/const_error_test/13                              | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/01  | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/03  | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/04  | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | co19_2/LanguageFeatures/Set-literals/disambiguating_A06_t01/03                 | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/23                     | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/24                     | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/35                     | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/36                     | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/control_flow_collections/if_const_error_test/37                     | Pass             | CompileTimeError |
| front-end-win-release-x64/fasta   | language_2/spread_collections/const_error_test/13                              | Pass             | CompileTimeError |

@stefantsov These started after your changes rolled in and seem to be missing compile-time errors. Would you mind forwarding it to the right person?

**Comment by stefantsov** [comment]
Thanks for approving the changes, Martin!

The most of the listed test cases, namely `language_2/spread_collections/const_error_test/13`, `co19_2/LanguageFeatures/Control-flow-collections/const_collections_A02_t02/{01,03,04}` and `language_2/control_flow_collections/if_const_error_test/{23,24,35,36,37}`, are covered by the existing GitHub issue: https://github.com/dart-lang/sdk/issues/32557.  I've created a new issue for the rest: https://github.com/dart-lang/sdk/issues/36413, and assigned myself.
