### ISSUE TITLE
Uri.tryParse(null) throws a NoSuchMethodError

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36415]
I don't think this is the correct type of error:

```dart
Uri.tryParse(null)
```

```
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Uri.parse (dart:core/uri.dart:788:17)
#2      Uri.tryParse (dart:core/uri.dart:1033:14)
#3      main 
bin/uri.dart:2
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

The docs aren't really clear about what should happen for `null`, they say:

```
Returns null if the string is not valid as a URI or URI reference.
```

However `int.tryParse(null)` throws `Invalid argument(s): The source must not be null` so it seems like this should probably be consistent.

(testing with current nightly build)

**Comment by lrhn** [comment]
It should be consistent and always throw an `ArgumentError`.

I so can't wait for non-nullable types :)

**Comment by DanTup** [comment]
> I so can't wait for non-nullable types :)

You and me both (and no doubt countless others)! 😀

**Comment by DanTup** [comment]
It's not possible to pass `null` to `Uri.tryParse` now :-)
