### ISSUE TITLE
CFE doesn't report set/map disambiguation errors in all cases

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#36413]
Some errors related to ambiguous literal set/map contents are handled by converting erroneous elements to `invalidCollectionElement` and are silenced.  They should be reported instead.

To reproduce, run the following command:

```
python tools/test.py -n fasta-linux --verbose co19_2/LanguageFeatures/Set-literals/disambiguating_A06_t01/03
```

It should result in a compile-time error, but the current status is `Pass`.

**Comment by kmillikin** [comment]
We should fix this for Dart 2.3.  @stefantsov do you consider it blocking the release?

**Comment by stefantsov** [comment]
I think it may give a strange feeling about compiling a line like `print({if (true) 1 else 2: 3});` and seeing `{}` in the output without any error messages.  It's also not very hard to fix.  I'll start working on it now.

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/98466.
