### ISSUE TITLE
Optimize interpreter execution

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36410]
optimize transitions from interpreter ==> compiled code and compiled code ==> interpreter 
optimize interpreter execution

**Comment by rmacnak-google** [comment]
"Optimize interpreter execution" is too vague.

**Comment by a-siva** [comment]
There are two aspects to it
- optimize the transitions from interpreted mode to compiled code and back (this make require unifying the execution stack)
- figure out if the C++ implementation of the interpreter is not efficient enough and if so consider generating a more optimal version

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
