### ISSUE TITLE
new const tests language_2/constants_2018 tests are failing

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36424]
The following tests are now failing:

| BOT                          | TEST                                                        | RESULT           | EXPECTED         | 
| ---------------------------- | ----------------------------------------------------------- | ---------------- | ---------------- | 
| cross-vm-linux-release-arm64 | language_2/constants_2018/equals_test/01                    | Pass             | CompileTimeError |
| cross-vm-linux-release-arm64 | language_2/constants_2018/equals_test/02                    | Pass             | CompileTimeError |
| cross-vm-linux-release-arm64 | language_2/constants_2018/equals_test/03                    | Pass             | CompileTimeError |
| cross-vm-linux-release-arm64 | language_2/constants_2018/equals_test/04                    | Pass             | CompileTimeError |
| cross-vm-linux-release-arm64 | language_2/constants_2018/potential_const_dynamic_test/sh3  | CompileTimeError | Pass             |
| cross-vm-linux-release-arm64 | language_2/constants_2018/potential_const_type_test/sh3     | CompileTimeError | Pass             |

**Comment by a-siva** [comment]
I have attached milestone 2.3 to these but if they are considered not important you could remove the tag

**Comment by kmillikin** [comment]
@askeksa-google Can you take a look at these?

**Comment by sstrickl** [comment]
As mentioned on #36418, I saw these had been preapproved on CQ bots when it landed and I went ahead and approved on all other bots (I thought I'd caught all the bots, but apparently I missed that one, sorry). There's a separate crash on the -reload- bots mentioned in the other issue.

**Comment by askeksa-google** [comment]
The first 4 should be fixed by https://dart-review.googlesource.com/c/sdk/+/98349.

The remaining ones involve unsigned right shift and are not expected to pass, as we don't support that operator yet (the constant evaluator does, but the parser rejects it for the time being).

**Comment by kmillikin** [comment]
The first four tests are fixed, and the remaining ones are not relevant for Dart 2.3.
