### ISSUE TITLE
we'd like a feature in DDC to create AMD modules with module names

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#36423]
In DartPad, we're using DDC to create AMD modules. We load these in the front end using require.js. We get errors when trying to load in anonymous modules, so we're currently post-processing the DDC output in insert names for the compiled modules.

It would be great if there was a command-line flag in DDC to do this in a first class way; the regex replace is likely pretty fragile.

The output we get from DDC:

```javascript
define(['dart_sdk'] ...
```

and we convert that to:

```javascript
define("dartpad_main", ['dart_sdk'] ...
```

We're using the `--module-name` flag to DDC, which does add the name to a dart.trackLibraries() section in the compiled module, but doesn't seem to actually name the module.

cc @jmesserly @vsmenon @jakemac53

**Comment by jmesserly** [comment]
`--single-out-file` will do this for you. Perhaps it should be renamed. IIRC @jacob314 added it so we could concat the files. LMK if that works, and we can close this?

**Comment by devoncarew** [comment]
Awesome! I'll give that a try, and update (or close) this bug.

**Comment by devoncarew** [comment]
Ah, interesting, it converts the whole thing into an eval:

```
eval("define('dartpad_main', ['dart_sdk'], function(dart_sdk) {\n  'use strict';\n  const core = dart_sdk.core;\n  const dart = dart_sdk.dart;\n  const dartx = dart_sdk.dartx;\n  const _root = Object.create(null);\n  const main = Object.create(_root);\n  main.main = function() {\n    for (let i = 0; i < 5; i++) {\n      core.print(\"hello \" + dart.str(i + 1));\n    }\n  };\n  dart.trackLibraries(\"dartpad_main\", {\n    \"main.dart\": main\n  }, null);\n  // Exports:\n  return {\n    main: main\n  };\n});\n\n//# sourceMappingURL=main.dart.js.map\n\n//# sourceURL=dartpad_main.js\n");
```

Seems to work for what we're doing however...

**Comment by jmesserly** [comment]
Strange. According to a comment:
```dart
      // In single-out-file mode we wrap each module in an eval statement to
      // leverage sourceURL to improve the debugging experience when source maps
      // are not enabled.
      //
      // Note: We replace all `/` with `.` so that we don't break relative urls
      // to sources in the original sourcemap. The name of this file is bogus
      // anyways, so it has very little effect on things.
```
I don't entirely follow that, but it sounds like it helped something related to debugging?

**Comment by jmesserly** [comment]
LMK if it becomes an issue, we could split those two features.

**Comment by devoncarew** [comment]
The `eval` is slightly concerning, but things are working as is. If you do separate out the behavior, we'd definitely opt-into the one w/o eval.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/dart-services/pull/383 for context

**Comment by jacob314** [comment]
The eval is only there because it gives a better JS debugging experience as
each of the eval calls will look like a separate JS script as far as Chrome
devtools is concerned. This let's each JS file have its own sourcemap, etc.
For this use case I expect none of that matters and you could strip out the
evals with no user visible impact.

**Comment by vsmenon** [comment]
The eval is also there is to enable further concatenation.  DartPad shouldn't need that - there is only the one output file.

**Comment by vsmenon** [comment]
I.e., if you concat two files without the eval, the source maps are screwed up.  With the eval, the source maps are still valid within the eval.

**Comment by jmesserly** [comment]
it sounds like maybe we should add a separate option to control the AMD named-module behavior without the concat (i.e. `eval`) behavior? Or: we could add the module name unconditionally. It's not going to hurt anything.

BTW Devon, I don't think the module name is supposed to matter according to require.js docs: 
https://requirejs.org/docs/whyamd.html#namedmodules

> Notice that the above module does not declare a name for itself. This is what makes the module very portable. It allows a developer to place the module in a different path to give it a different ID/name. The AMD loader will give the module an ID based on how it is referenced by other scripts.
> [...]
> You should avoid naming modules yourself, and only place one module in a file while developing. However, for tooling and performance, a module solution needs a way to identify modules in built resources.

In other words, naming modules is supposed to only be for concatenation purposes, otherwise the file name is used. But the DartPad use case might be an advanced one, compared to what the requirejs docs are talking about?

**Comment by devoncarew** [comment]
> But the DartPad use case might be an advanced one, compared to what the requirejs docs are talking about?

I suspect we're pretty specialized - we can load the pre-determined modules by name, from compiled JS modules we've put in google storage (things like the dart sdk js file). The actual compiled JS for the input dart source we're loading by adding it as a script tag directly into the page - I don't think the module-name-is-a-file-path will work for us.

Obviously, we're pretty happy to explore alternatives; right now, a single named AMD module seems to be working for us.

**Comment by jmesserly** [comment]
That makes sense! LMK if the `eval` ever causes problems, we can add a flag pretty easily for you. (Or even change the default way we generate AMD code, so the name is always included.)
