### ISSUE TITLE
Investigate possibilty of having a more optimal method dispatch mechanism

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36426]
The current method dispatch mechanism degrades performance when the degree of polymorphism increases. Investigate the possibility of a new mechanism that alleviates this performance degradation.

**Comment by rmacnak-google** [comment]
Instance calls unoptimized machine code and dynamic calls in the interpreter will add cases to their ICData without bound. We should consider porting the switch calls to JIT mode, which switch to using a MegamorphicCache when the polymorphism reaches a certain threshold.

**Comment by rmacnak-google** [comment]
1e24fe7d699a1c36be142afa21859c6a9c82d035
