### ISSUE TITLE
Analyzer checks overriding between superclass and superinterface incorrectly.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#36432]
DART version: 2.2.1-dev-1.1
OS: Windows 10 64 bit

This bug is similar with #34392 which was fixed some time ago.

Here is a source code example:
```dart
abstract class I { foo(a) {} }

abstract class A { foo() {} }
abstract class B { another() {} }

abstract class C extends A implements I {}    // compile error here
abstract class D extends B implements I {}    // no error here

main() {}
```
Analyzer throws a compile error for the line #6 and passes with the line #7:

> Analyzing test.dart...
>   error - Superinterfaces don't have a valid override for 'foo': I.foo ((dynamic) → dynamic), A.foo (() → dynamic) at test.dart:6:16 - inconsistent_inheritance
> 1 error found.
> 

Seems like it should pass in both cases.

Please note that #34392 source example passes with the recent dart versions. 

If I run my test with dart, it passes as well.

**Comment by eernstg** [comment]
This is working as intended.

You need to say `foo([a])` in `I` in order to make that signature more specific than `A.foo`. Otherwise you just have two incomparable signatures for `foo` in the superinterfaces of `C`, and that's an error of the declaration of `C` when `C` doesn't declare a `foo`.

Alternatively, if you add the declaration `foo([a]);` to the body of `C` then that declaration is a correct override of both `A.foo` and `I.foo`, and there is no error.

**Comment by iarkh** [comment]
I tested this with 2.2.1-dev-1.1 and dart passed for me.
So, seems like it's fixed in the next release.

**Comment by eernstg** [comment]
I get the same response (error on line 6) from `dart` version 2.2.1-dev.1.1 as I did for the other versions (older and newer than that), which is also the response we should get, and also the response that we get from `dartanalyzer`.

But I'm not quite sure what you mean by 'it passed for me'. Do you mean that you have a version of `dart` that does not report an error for line 6? That would be a bug, but I can't recreate that behavior.

**Comment by iarkh** [comment]
Sorry for inaccuracy! Dart report compile error on the line 6 too, so if it's expected this bug can be closed.

**Comment by eernstg** [comment]
Yep, that error is expected. Thanks!

**Comment by kevmoo** [comment]
@eernstg – is there a bug here? For whom? Otherwise, please close! 😄
