### ISSUE TITLE
Odd comment parsing behavior with /*/*/

### ISSUE THREAD

**Issue by kankaristo** [dart-lang/sdk#36435]
I use the following little trick to easily comment/uncomment a block of code:
```c
/*/
RunSomeCode();
// */
```

Adding a single `*` to the top line uncomments the code:
```c
/**/
RunSomeCode();
// */
```

You can also toggle between 2 alternative blocks of code, by adding or removing the same `*` on the first line (this doesn't work in Dart, see below):
```c
// Runs the first block of code (2 asterisks on the first line)
/**/
RunSomeCode("A");
/*/
RunSomeCode("B");
// */

// Runs the second block of code (1 asterisk on the first line)
/*/
RunSomeCode("A");
/*/
RunSomeCode("B");
// */
```

This "trick" works in all languages I've tried it in, which use `/* */` for multiline comments (a similar trick also works in Lua, which uses `--[[ ]]`).

-----

Dart is sort of the odd one out though, because Dart **requires** the space in `// */`. If you try the above with `//*/` on the last line, it will fail to compile as Dart (but works fine in C, C++, C#, Java, JavaScript, and many others (can't remember all of the languages I've tried it with). The "toggle" doesn't work, because Dart can't handle a multi-line comment ending with `/*/`.

The very simplest form that I can reduce this to is `/*/*/`, which fails to compile as Dart, but is valid in JavaScript, etc.

If you add the space, like in the examples above, it compiles fine: `/*/ */`

-----

I miss using the toggle trick (which doesn't work in Dart at all).

I can't think of a reason why this would be by design (since the same is valid JavaScript), so is this a bug in the Dart parser?

I'm using Dart 2.2.1-dev.0.0 and dart2js 2.2.1-dev.0.0, if that makes a difference, but I doubt it does, because this has been the same since before Dart 2.0.

(I'm not sure if this is the right place for this issue, please tell me if there's some other place to file language/parser issues.)

**Comment by bwilkerson** [comment]
I suspect the issue you're running into is the fact that Dart allows block comments to nest:
```
/*
This in the outer comment.
/*
This is in the inner comment.
*/
This in the outer comment.
*/
```
So when the parser sees `/*` it assumes that it's the beginning of a nested block comment.

**Comment by kankaristo** [comment]
I see... Is there a reason why nested comments are supported, can they be _used_ for something?

Is it so that documentation in comments can include code examples with comments (although using block comments is only recommended for commenting out code, [not for documentation](https://www.dartlang.org/guides/language/effective-dart/documentation#dont-use-block-comments-for-documentation))?

Or is it more of an implementation detail of the parser?

Seems like an odd difference to all other languages I've come across, that also use `/* */` for block comments. Some C compilers give a warning about `/*` inside a block comment, but they don't warn about ending a block comment with `/*/`, so none of the examples I gave have given me any warnings/errors (apart from `dartdevc` and `dart2js`).

Lua also allows nested block comments, but only because it also allows [nested strings](http://lua-users.org/wiki/StringsTutorial), and uses the same syntax for both multi-line strings and multi-line comments (comments just add `--` in front of the string).

**Comment by bwilkerson** [comment]
It was an intentional decision early in the design of Dart. I don't remember the motivation for it.

**Comment by eernstg** [comment]
SML uses nested comments (see, e.g., [here](https://riptutorial.com/sml/example/23540/nested-comments)), so it's not a completely new idea. The motivation was probably that you can comment out a block of code by putting `/*` and `*/` around it. That won't work if the syntax does not support nested comments, and that block of code already contains multi-line comments.

I don't know whether it's more important to be able to perform the toggle trick, or it's more important to be able to comment out a lot of code with just 4 chars, though. ;-)

**Comment by kankaristo** [comment]
> SML uses nested comments (see, e.g., [here](https://riptutorial.com/sml/example/23540/nested-comments)), so it's not a completely new idea. The motivation was probably that you can comment out a block of code by putting `/*` and `*/` around it. That won't work if the syntax does not support nested comments, and that block of code already contains multi-line comments.
> 
> I don't know whether it's more important to be able to perform the toggle trick, or it's more important to be able to comment out a lot of code with just 4 chars, though. ;-)

Granted, the toggle trick is a pretty obscure thing, but Dart's use of `/* */` for nested comments is different to all other "`/* */` languages" I've ever seen... And probably breaks most syntax highlighters, like the one in VSCode, and the one here on GitHub (the below code begins with ```dart, so it's explicitly marked as Dart):
```dart
/*
outer
/*
inner
*/
outer
*/
```
