### ISSUE TITLE
Enabling JS web semantics for numerics results in decimal points for constant strings with interpolated integers

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36441]
For the following snippet:
```
main() {
  const a = 100;
  const b = "$a";
  print(a);
  print(b);
}
```
The CFE generates something like:
```
main = reg::main;
library from "org-dartlang-app:/regress4.dart" as reg {

  static method main() → dynamic {
    core::print(#C1);
    core::print(#C2);
  }
}
constants  {
  #C1 = 100.0
  #C2 = "100.0"
}
```
With JS semantics selected, this results in `100 100.0`. 
The expected output is `100 100`.

Because numerics without a fractional part are stringified without the decimal, we'd expect #C2 to have been generated as "100".

**Comment by Markzipan** [comment]
Might be fixed by: https://dart-review.googlesource.com/c/sdk/+/98240

**Comment by fishythefish** [comment]
@Markzipan: Did the CL fix the issue for you?

**Comment by Markzipan** [comment]
@fishythefish Sure did, thanks!
