### ISSUE TITLE
CFE missing compile time errors when const collections contain spread or map keys that override operator==

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36444]
There are missing compile time errors on the following tests across all CFE backends.

https://github.com/dart-lang/sdk/blob/d77a6064a9fbc4da0110bd65ee76a4d574f1428f/tests/language_2/spread_collections/const_error_test.dart#L61-L63

**Comment by kmillikin** [comment]
@askeksa-google can you take a look at this?

**Comment by kmillikin** [comment]
There is a related issue with map keys, which is shown by the following tests:

```
control_flow_collections/if_const_error_test/23: MissingCompileTimeError
control_flow_collections/if_const_error_test/24: MissingCompileTimeError
control_flow_collections/if_const_error_test/35: MissingCompileTimeError
control_flow_collections/if_const_error_test/36: MissingCompileTimeError
control_flow_collections/if_const_error_test/37: MissingCompileTimeError
```

**Comment by kmillikin** [comment]
Because these are missing compile-time errors I don't think they should block the Dart 2.3 release.  Still, we'd like to fix them in time for the release.

**Comment by askeksa-google** [comment]
Working on a fix for this one. Expect to have it ready tomorrow.

**Comment by nshahan** [comment]
It looks like the test cases that use doubles were fixed but the tests that use a class (`Duration` in these tests) that overrides operator== are still failing to produce a compile time error: 

https://github.com/dart-lang/sdk/blob/a112b11e2e51cd22cacd044f530a178da1409d58/tests/language_2/control_flow_collections/if_const_error_test.dart#L86

https://github.com/dart-lang/sdk/blob/a112b11e2e51cd22cacd044f530a178da1409d58/tests/language_2/control_flow_collections/if_const_error_test.dart#L118

https://github.com/dart-lang/sdk/blob/a112b11e2e51cd22cacd044f530a178da1409d58/tests/language_2/spread_collections/const_error_test.dart#L62

**Comment by vsmenon** [comment]
Closing in favor of #36480
