### ISSUE TITLE
Implement CheckNull on DBC

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36457]
Two potential optimizations are currently disabled in DBC due to absence of `CheckNull`:

https://github.com/dart-lang/sdk/blob/28734c5f23a6ce3172c0cc6977702970d4d9a49a/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L2132 Using unchecked entry-point for statically-typed closure calls in DBC.

https://github.com/dart-lang/sdk/blob/28734c5f23a6ce3172c0cc6977702970d4d9a49a/runtime/vm/compiler/backend/flow_graph.cc#L501 Reduce `CheckClass` to `CheckNull` when the concrete receiver type of an inlined method is statically known.

@mraleph

**Comment by dcharkes** [comment]
Thanks for reporting this @sjindel-google!

CheckNull on DBC is also blocking for #35773, with these two optimizations I can directly test my implementation of CheckNull on DBC. :)
