### ISSUE TITLE
Delayed constant evaluation breaks when a field initializer is unevaluated

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36454]
```dart
class A {
  final int x = int.fromEnvironment("x");
  const A();
}

main() {
  const a = const A();
  print(a.x);
}
```
When this program is compiled without an environment, the constant evaluator will produce an `InstanceConstant` with an unevaluated child, which violates the invariant that all subconstants of constants must be evaluated. Subsequent evaluation fails to evaluate the child, breaking the backend.

The proper solution is to introduce an `InstanceExpression` Kernel node, representing a direct instance creation with specific field values. This expression can have the unevaluated field initializer as a subexpression.

**Comment by askeksa-google** [comment]
A fix is ready in https://dart-review.googlesource.com/c/sdk/+/98570, but it breaks a dart2js unit test. I will investigate tomorrow.

**Comment by lrhn** [comment]
For the record, you need a `const` in front of the `int.fromEnvironment("x")` for the class `A` to be valid.

A field initializer of a class with a constant constructor must be constant, but it is not automatically a constant context, so you need to write the `const` in front.

**Comment by askeksa-google** [comment]
Thanks, Lasse. I thought I fixed that in https://dart-review.googlesource.com/c/sdk/+/93520, but that fix apparently doesn't quite work with implicit `new`/`const`.
