### ISSUE TITLE
Please improve the usability of gen_bytecode_test

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36468]
This test is not ideal because it's testing the bytecode generator and expecting it to produce the *same* output for possibly *different* inputs.  When something changes in Fasta we often have to either regenerate the expectations or mark this test as failing.

The test output is nearly unusable.  When it fails it gives a useless stack trace.  Catch this and give a useful message.  It dumps out a whole bunch of expected and actual output that is not formatted like the expectation file.  It's got leading whitespace, quotes, and escaped newlines.  Format this like the expectation file.

There are no instructions to tell me how to rebase the expectations.  Please add simple instructions ("run this command" or "create a file named this with these contents").

Nobody on the CFE team really has the expertise to know if the expectations are correct or not, so I've just gone with option B and approved that the test is currently failing.

**Comment by kmillikin** [comment]
OK, I didn't commit the CL with the test failure yet.  It's https://dart-review.googlesource.com/c/sdk/+/98664 which fails because we are currently (and temporarily) allocating more context variables in the async translation.

How do I regenerate the expectations, and can it be made more discoverable?

**Comment by alexmarkov** [comment]
In order to re-generate expectations please run the following script:

```
tools/test.py -m release -r vm --vm-options -Ddump.actual.result=true pkg/vm/test/bytecode/gen_bytecode_test

for i in `find -name *.actual`
do
  mv $i `echo $i | sed -e s/.actual/.expect/`
done
```

Thank you for the suggestions! In addition, does it make sense to unify re-generation of expectations with front-end tests?

Also, I'm not sure that these test are very useful now, as we have functional testing of bytecode pipeline on dartkb bots, so we can consider removing them.

**Comment by kmillikin** [comment]
Thanks for the instructions.  I'm sorry to have sounded so frustrated in the initial report.

**Comment by alexmarkov** [comment]
Sample test output with https://dart-review.googlesource.com/c/sdk/+/98946:

```
00:00 +0: gen-bytecode /usr/local/google/home/alexmarkov/work/dart/sdk/pkg/vm//testcases/bytecode/literals.dart
00:00 +0 -1: gen-bytecode /usr/local/google/home/alexmarkov/work/dart/sdk/pkg/vm//testcases/bytecode/literals.dart [E]
  
  Result is different for the test case file:///usr/local/google/home/alexmarkov/work/dart/sdk/pkg/vm//testcases/bytecode/literals.dart
  
  The first difference is at line 672.
  Actual:     Entry                2
  Expected:   EntryOptional        2, 1, 0
  
  This failure can be caused by changes in the front-end if it starts generating
  different kernel AST for the same Dart programs.
  
  In order to re-generate expectations run tests with -DupdateExpectations=true VM option:
  
    tools/test.py -m release --vm-options -DupdateExpectations=true pkg/vm
  
  In order to dump actual results into .actual files run tests with -Ddump.actual.result=true VM option:
  
    tools/test.py -m release --vm-options -Ddump.actual.result=true pkg/vm
  
  
  package:test/src/frontend/expect.dart 160:30       fail
  pkg/vm/test/common_test_utils.dart 124:7           compareResultWithExpectationsFile
  pkg/vm/test/bytecode/gen_bytecode_test.dart 46:3   runTestCase
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                  _Completer.completeError
  dart:async-patch/async_patch.dart 40:18            _AsyncAwaitCompleter.completeError
  pkg/vm/test/bytecode/gen_bytecode_test.dart        runTestCase
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23            _asyncThenWrapperHelper
  pkg/vm/test/bytecode/gen_bytecode_test.dart        runTestCase
  pkg/vm/test/bytecode/gen_bytecode_test.dart 56:32  main.<fn>.<fn>
  package:test/src/backend/declarer.dart 168:27      Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23            _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart             Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15       Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test/src/backend/invoker.dart 402:11       Invoker._onRun.<fn>.<fn>.<fn>
  
```

@kmillikin please comment here or on the CL if not all concerns are addressed or you have further suggestions. Thanks!

**Comment by kmillikin** [comment]
Thanks!  This looks good.
