### ISSUE TITLE
computeNode is deprecated in analyzer 35.4, what can we use instead?

### ISSUE THREAD

**Issue by twistedinferno** [dart-lang/sdk#36462]
Hi, `computeNode` in analyzer 35.4 has been deprecated (dart version 2.1.1-dev.1.0), the following is the commit that made the change.  

https://github.com/dart-lang/sdk/commit/67b9f2ec8d143392c9b1f118243271237a40139a#diff-f1c690259cb67309c745fb8632449c23

What should we use instead?

I'm looking at the following line of code in flutter package `functional_widget` that uses the method (trying to update the analyzer version).
```
  String _getFallbackElementDiagnostic(ParameterElement element) =>
      'DiagnosticsProperty<${element.type.isUndefined ? element.computeNode().beginToken : element.type.displayName}>';
```

https://github.com/rrousselGit/functional_widget/issues/30

**Comment by bwilkerson** [comment]
I'm not familiar with 'functional_widget', but it looks like it's using the package 'build', which is what I assume you'll use to get the analyzer information. Perhaps @natebosch can help you transition.

**Comment by natebosch** [comment]
I think it would be something like:

```dart
Token _findBeginToken(ParameterElement element) {
  final parsedLibrary = element.session.getParsedLibraryByElement(element.library);
  final declaration = parsedLibrary.getElementDeclaration(element);
  final parameter = declaration.node as FormalParameter;
  return parameter.beginToken;
}
```

**Comment by twistedinferno** [comment]
Marvelous, it all works now :-)
