### ISSUE TITLE
Regression on positions of constants

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36471]
With the new constant evaluator, we don't serialize the source positions of constants. This causes some missing positions in stack traces when a constant is involved in a runtime error. For instance, the test `language_2/vm/bool_check_stack_traces_test/01` fails because a `null` condition in an `if` statement comes from a `const` variable.

A full fix will require a change to the Kernel binary format to include the position into `ConstantExpression` nodes, plus support for reading this position from the node in all backends.

A simpler solution that will handle common cases (including the mentioned test) would be to convert primitive constants back into literals in places that do not require a constant (such as referencing a `const` variable).

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/98677.
