### ISSUE TITLE
DDK does not have access to initializers in external constructors

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36480]
The following snippet doesn't throw an error in DDK (but does in Dart2JS):
```
main() {
  var v1 = const {const Duration(seconds : 1)}; // Expected compile-time error
}
```

When running that snippet with DDK, Fasta evaluates `shouldBeUnevaluated` (constant_evaluator.dart, lline ~836) to true, so the `hasPrimitiveEqual` check is never performed. 

The same applies to map constants. 

Related issue: https://github.com/dart-lang/sdk/issues/36444

**Comment by jmesserly** [comment]
FYI -- This bug may also affect the Dart VM when using modular builds (e.g. in the internal repository?)

**Comment by kmillikin** [comment]
P2 means this isn't blocking the 2.3 release, but it would be awfully nice to fix it now.

**Comment by askeksa-google** [comment]
Based on the description, I think this is what is happening:
- In the first (separate) compilation pass, the `Duration` constructor is unavailable, which causes the front-end constant evaluator to leave the constant (and thereby the whole constant set literal) unevaluated.
- In the second compilation pass, when all of the code is (presumably) available, DDC should create a constant evaluator and invoke it on all unevaluated constants it encounters in order to complete their evaluation. Any errors in the constant that could not be detected by the evaluator in the first pass (because of unevaluated sub-constants) will be reported by the constant evaluator at this time.

It looks like this second-pass constant evaluation is not performed in DDC.

**Comment by jmesserly** [comment]
> In the second compilation pass, when all of the code is (presumably) available, DDK should create a constant evaluator and invoke it on all unevaluated constants it encounters in order to complete their evaluation. Any errors in the constant that could not be detected by the evaluator in the first pass (because of unevaluated sub-constants) will be reported by the constant evaluator at this time.

When we compile the user's code, we supply CFE with the SDK summary, so all of the info is available. CFE has the same exact info that DDK does. So I'm not sure why we get "unevaluated constants" in the Kernel Tree?

Generally with Analyzer and CFE, they report all of the compiler errors before we attempt to generate JavaScript.

That said, it's certainly possible for us to call into a constant evaluator or something like that. Is there a code sample illustrating what we should do? Is there some way we can report errors that will make them formatted in the same way that CFE normally would?

**Comment by jmesserly** [comment]
I guess what I'm trying to understand here: what are the two passes you're referring to? DDC never has all Dart sources available. We only have the user's code, and the .dill outlines for all transitive dependencies.

**Comment by vsmenon** [comment]
Reassigning based on my understanding.  Note, we're not supporting runtime `const X.fromEnvironment` for arbitrary defines, so there should not be unevaluated constants.

As Jenny, DDC never has the whole program source.  We're assuming all info for a constant is the combo of the source and .dill outlines for dependencies.

**Comment by askeksa-google** [comment]
To evaluate a `const` constructor call, the constant evaluator will need access to the initializers for the constructor, plus the initializing expressions of all fields of the enclosing class. So if these are not part of the outlines provided to DDK currently, we would probably need to add them.

Alternatively, we can skip front-end constant evaluation in DDK entirely, but this would also skip associated static checks, such as for duplicate keys in constant map literals.

**Comment by vsmenon** [comment]
@Markzipan - can you check to see if DDK has the full constants (i.e., const initializers in the outline) with the const experiment on?  If it does, you should see consts evaluated across summary boundaries (as with DDC).

**Comment by Markzipan** [comment]
From what I can tell, the kernel SDK's outline doesn't contain any information about initializing the Duration object. 

It's probably not necessary to skip front-end evaluation for this narrow case though.

**Comment by jmesserly** [comment]
Hmm, this seems like an issue with outline Kernel files then, if I'm understanding correctly?

AFAIK, Analyzer summaries contain sufficient information for constant checking. They serialize some bits of the AST; pkg/analyzer/lib/src/summary/expr_builder.dart has the deserialization code. @stereotype441 might have some info on how it works?

**Comment by jmesserly** [comment]
FWIW: we could build a non-outline Kernel file for DDC's SDK, but that wouldn't help other packages. (I don't think we want the entire build to use non-outline, because that would adversely affect DDC+Kernel build performance, especially with incremental edits.)

**Comment by stereotype441** [comment]
> Hmm, this seems like an issue with outline Kernel files then, if I'm understanding correctly?
> 
> AFAIK, Analyzer summaries contain sufficient information for constant checking. They serialize some bits of the AST; pkg/analyzer/lib/src/summary/expr_builder.dart has the deserialization code. @stereotype441 might have some info on how it works?

Yup, the principle followed by the analyzer is: any information gleaned from a given file that could possibly affect the errors/warnings reported for other files gets encoded in the summary.  Since a small number of compile time errors depend on constant values (e.g. duplicate keys in constant map), this means that all constant values have to be stored in the summary.  The analyzer happens to encode them as ASTs and then evaluate them at the time they are referenced, but that's an implementation detail.

**Comment by kmillikin** [comment]
Outlines do not currently contain everything they need for constant evaluation (or type inference, for that matter).

**Comment by jmesserly** [comment]
We realized today: since const control-flow-collections depend on the constant evaluator, will they work across modules (w/ outline summaries)? In other words, something like this:
```dart
// in module1, e.g. the module for the flutter web package
const module1List = [ /* some items */];
// in module2, e.g. user code
const module2List = [ /* some items */, ...module1List, for (x in module1List) x, /* more items */ ];
```
Since `module1List` is unavailable in the outline summary, it could be a problem? But I think the "ListConcatenation" type is designed to solve it. So perhaps we just need a test for it.

**Comment by askeksa-google** [comment]
`ListConcatenation` and the similar nodes for sets and maps are used internally by the constant evaluator to represent partially evaluated collections containing spread and control flow. These will show up when some subconstant inside such a collection could not be evaluated.

The constant still can't be evaluated unless all `const` variables and constructors that it depends on are available (and an environment is supplied for any `const X.fromEnvironment`). The concatenation nodes are just there to ensure that no additional complications arise from the spread and control flow, so to speak.

(By the way, `for` is not allowed in constants, but the spread illustrates the situation well enough.)

I noticed that `pkg/dev_compiler/lib/src/kernel/compiler.dart` contains implementations for the visit methods for these concatenation nodes. Superficially, these look like they do the right thing, but there are cases where they will give the wrong result (e.g. for `if` elements with unevaluated conditions, where the expression is neither a constant nor a literal) or fail to report an error in the program (e.g. wrong type of element or duplicate key in a map).

In general, it is not the intent that backends dive into unevaluated constants. Rather, these should be handed to a constant evaluator for final evaluation. This leads us back to the problem at hand - that the Kernel outline is insufficient.

**Comment by vsmenon** [comment]
Closing in favor of #36635.
