### ISSUE TITLE
"main" on the service isolate should be  by posting a message on that isolate's message handler.

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/sdk#36504]
It is currently [run inline](https://github.com/dart-lang/sdk/blob/a47b4ad2b8683cc8a82aa0ff89da2db7a3be27a3/runtime/vm/service_isolate.cc#L345).

**Comment by chinmaygarde** [comment]
cc @a-siva @rmacnak-google

**Comment by liamappelbe** [comment]
The service isolate's port is set up by the vmservice_io::main, so I don't think we can send a message to the service isolate until after this main function is called.
