### ISSUE TITLE
Inconsistent behavior when downcasting bounded generic functions

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36501]
The following snippet executes in DDC but emits an error in CFE:
```
typedef G = T Function<T extends int>(T x);

main() {
  f<T extends num>(T x) => x + 2;
  print((f as G)(40)); // 42
}
```

The error:
```
Unhandled exception:
type '<T extends num>(T) => num' is not a subtype of type '<T extends int>(T) => T' in type cast
```

**Comment by eernstg** [comment]
It is true that there is no subtype relation between those two generic function types: Generic function types are invariant in their bounds. The reason for this is that it has serious implications for the tractability of type inference if any kind of variance is supported. So CFE is right.

**Comment by leafpetersen** [comment]
Corrected test for this landed [here](https://dart.googlesource.com/sdk/+/b74ae33406f079e0814a5757e3eb2f8b3022582f)

**Comment by nshahan** [comment]
I have a fix to make DDK show the proper behavior in progress.
