### ISSUE TITLE
how can i build dart native extensions for android

### ISSUE THREAD

**Issue by garygogo** [dart-lang/sdk#36520]
hi, i see the article which url is https://www.dartlang.org/articles/server/native-extensions, how can i build such native extensions for android; how to use ndk-build to build?  tks!

**Comment by rmacnak-google** [comment]
It is the same as building for Linux. Just replace `g++` with the `g++` or `clang++` from the NDK for the architecture you're targeting.

Beware that native extensions are a feature of the command-line embedder of the Dart VM. Other embedders such as the Flutter engine do not support native extensions. If you want to use C or C++ with your Dart code on Flutter, see [Flutter plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages).

**Comment by garygogo** [comment]
Thanks for your reply. how can I use dart native method in flutter?

**Comment by a-siva** [comment]
see [Flutter plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages) for more information.

**Comment by ping996** [comment]
How to put my extension library on android devices,  I have an error about dart can't load the library.
`2019-10-21 16:38:59.849 24632-24651/com.example.flutter_app333333333 E/flutter: [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unknown library tag.error: library handler failed
2019-10-21 16:38:59.849 24632-24651/com.example.flutter_app333333333 E/flutter: [ERROR:flutter/shell/common/engine.cc(193)] Could not prepare to run the isolate.
2019-10-21 16:38:59.849 24632-24651/com.example.flutter_app333333333 E/flutter: [ERROR:flutter/shell/common/engine.cc(132)] Engine not prepare and launch isolate.
2019-10-21 16:38:59.849 24632-24651/com.example.flutter_app333333333 E/flutter: [ERROR:flutter/shell/common/shell.cc(428)] Could not launch engine with configuration.`

**Comment by ping996** [comment]
does the flutter support the dart native extension now? 
dart native extension: https://dart.dev/server/c-interop-native-extensions
