### ISSUE TITLE
Analyzer should provide execution details if evaluation of a constant throws an exception

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36526]
Consider the following code, adapted from the repro for #36511:
```dart
class A {
  const A(int i)
  : assert(i == 1); // (2)
}
class B extends A {
  const B(int i) : super(i);
}
main() {
  print(const B(2)); // (1)
}
```
Analyzing this code produces the following error message at line (1):
```
error • Evaluation of this constant expression throws an exception at /usr/local/google/home/paulberry/tmp/test.dart:9:9 • const_eval_throws_exception
```
Although this is technically correct, it's far too little information to allow the user to figure out where the problem is.  In particular, there's absolutely no information to lead the user to the site of the assertion failure at (2), or to aid in understanding how (2) was reached from (1).  This would be even more of a problem if the definitions of classes A and B were more distant, or if the constant evaluation were more complex.

By contrast, the VM's error message contains a full stack trace, and it points both to locations (1) and (2):
```
Unhandled exception:
'file:///.../test.dart': Failed assertion: line 3 pos 12: 'i == 1': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      new A (file:///usr/local/google/home/paulberry/tmp/test.dart:3:12)
#3      new B (file:///usr/local/google/home/paulberry/tmp/test.dart:6:20)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
'file:///usr/local/google/home/paulberry/tmp/test.dart': error: line 9 pos 15: error evaluating constant constructor
  print(const B(2)); // (1)
              ^
```

We really should improve the analyzer's error reporting here.

**Comment by lukehutch** [comment]
This is also an issue in VS Code.

Example:

![image](https://github.com/dart-lang/sdk/assets/811305/c6c6ff6d-215a-4cae-9d4f-9aacb68d35f4)

The actual exceptions are given in the `PROBLEMS` pane of VS code, but not in the popup:

![image](https://github.com/dart-lang/sdk/assets/811305/cf276d19-38cc-42a4-af29-da9205d44b93)

The `Evaluation of this constant expression throws an exception` error doesn't give enough info. The actual errors are found by the compiler, but they are apparently suppressed by this error.

**Comment by bwilkerson** [comment]
VS Code gets its information from the analysis server (the LSP language server for Dart).

The good news is that work is currently underway to allow the analysis server to produce similar information.

@kallentu
