### ISSUE TITLE
Analyzer fails to detect error when a non-null-aware spread expression has static type null

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36529]
Example code:
```dart
main() {
  var x = [...null];
  Map y = {...null};
  Set z = {...null};
}
```

This is currently causing failures in the following co19 tests:
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/01
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/02
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/03
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/04
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/05
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t01/06
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/01
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/02
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/03
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/04
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/05
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A09_t03/06
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A10_t01/04
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A10_t05/04
- co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A11_t01/06

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/98923
