### ISSUE TITLE
DDC does not build a working SDK with CFE constants flag enabled

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#36532]
Use the instructions and patches here to enable the constants flag: https://github.com/dart-lang/sdk/issues/36479

DDC's Kernel-backend compiled SDK will not load. I've found a few issues so far:
- the SDK's internal annotations are not found. For example `@nullCheck`, `@notNull`, `@JSExportName`, `@NoReifyGenerics`, and probably other critical ones such as `@JsPeerIterface`.
- static calls seem to be tagging the target with RTTI, as if it were a tearoff. As a result, we attempt to create a `dart.FunctionType` before it has been defined. This might partly be an issue with `@ReifyFunctionTypes`, but even so, we should not be reifying in these cases as it is unnecessary. We'll need to double check that this works properly for user code.

Also a few minor/trivial issues (not P1) such as:
- integer constants are generated as if they were doubles: `1.0` instead of `1`. This is valid, but has a very slight code size/readability cost.

**Comment by jmesserly** [comment]
I found a serious perf issue: #36535. My hope is that it isn't bad enough to require a fix in 2.3

**Comment by jmesserly** [comment]
I'm testing https://dart-review.googlesource.com/c/sdk/+/98875.

Once it passes, we can pull out the "pkg/dev_compiler" fixes into a CL and submit that separately. But for now I've merged it with the patches in #36479 so I can test how DDC is doing.

**Comment by sigmundch** [comment]
@jmesserly - I just added the 2.3 milestone, I assume this is necessary before we ship, correct?

**Comment by jmesserly** [comment]
ah, thank you. I meant to put it in 2.3, yup.

**Comment by jmesserly** [comment]
I'm now testing a fix here: https://dart-review.googlesource.com/c/sdk/+/98927

Once DDC is green, I can pull out the DDC changes. It also includes a 1-liner CFE fix for https://github.com/dart-lang/sdk/issues/36545

**Comment by jmesserly** [comment]
I uploaded a few more workarounds:
- there's some unusual CFE behavior where annotations end up as ConstantExpressions wrapping an UnevaluatedConstant.
- external factories appear to be eliminated normally, but preserved with the constants flag.

I'm dry-running that now. I think it will fix most/all of the remaining test failures.

**Comment by jmesserly** [comment]
Last night's test run found a few more issues. Based on local testing, I believe those are now fixes, so I made a CL that is DDC-only. https://dart-review.googlesource.com/c/sdk/+/99240. I'm also doing another test run on the above CL that contains the code to flip the flag.

**Comment by jmesserly** [comment]
The CL passed on both with and without the constants flag globally enabled (other than 2 co19 tests that are failing on other platforms too w/ constants flag, so not a DDC issue). I've sent it out for review.

**Comment by sigmundch** [comment]
@jmesserly - just saw that your CL landed, woohoo! 

Is it safe to close this issue at this time?
