### ISSUE TITLE
Analyzer with --no-implicit-dynamic complains about anonymous function passed to Function

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36534]
Consider the following code, where I have some function that takes a `Function` parameter and try to pass an anonymous function to it:

```dart
void foo(Function f) {}

Future<void> main() async {
  foo((e) {});
}
```

Running `dartanalyzer --no-implicit-dynamic` gives me an error:

>  error • Missing parameter type for 'e' at foo.dart:4:8 • strong_mode_implicit_dynamic_parameter

Okay, if I try to add a type with `foo((Object e) {});` then I trigger the lint:

>   lint • Avoid annotating types for function expression parameters at foo.dart:4:8 • avoid_types_on_closure_parameters

so I can't win.

This is admittedly a nonsensical example, and `foo` should specify return and parameter types for its `Function` argument.  However, I encountered this when trying to pass an anonymous closure to `Future<T>.catchError()` which necessarily takes a `Function`. (Incidentally, I don't see explicit documentation in [`Future<T>`](https://api.dartlang.org/stable/2.2.0/dart-async/Future-class.html) nor in [`Future<T>.catchError`](https://api.dartlang.org/stable/2.2.0/dart-async/Future/catchError.html) that explains what signatures are allowed for `onError`.  The best I can find is "If `test` returns true, `onError` is called with the error and possibly stack trace".)

A workaround seems to be to use `foo((dynamic e) {});` or to use a named function.

* Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64"

**Comment by zoechi** [comment]
Adding this before the line with the error
```dart
// ignore: implicit_dynamic_parameter
```
or this somewhere in the file
```dart
// ignore_for_file: implicit_dynamic_parameter
```
is the workaround I use.

**Comment by hpoul** [comment]
@zoechi is it just me, or did this stop working on the dev channel (dart 2.9.0-7.0.dev)?

<img width="645" alt="Screenshot 2020-05-14 at 12 40 32" src="https://user-images.githubusercontent.com/313066/81925097-546f1380-95e0-11ea-8580-5a47a6137548.png">

**Comment by shinriyo** [comment]
<img width="944" alt="スクリーンショット 2020-06-17 16 44 12" src="https://user-images.githubusercontent.com/396927/84870168-e7a4d880-b0b9-11ea-8fe0-2b094efef365.png">
What is this?

```
            errorWidget: (context, url, error) => SizedBox(
              width: double.infinity,
              height: double.infinity,
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: backgroundGreyDark,
                ),
              ),
            ),
```

**Comment by srawlins** [comment]
I don't think there is anything for `--no-implicit-dynamic` to do differently here. In each example, there is an implicit `dynamic` type:

> ```dart
> void foo(Function f) {}
>
> Future<void> main() async {
>   foo((e) {});
> }
> ```

Using `--no-implicit-dynamic` implies that you want to be warned about your implicit dynamic here.

> `(foo as List).map((e) ...`

since `as List` means `as List<dynamic>`, the parameter type for `e` is an implicit dynamic.

@shinriyo we'd have to see a complete example to see why `error` is missing a (more appropriate) type.
