### ISSUE TITLE
improve convert_to_spreads assist when applied in sequence

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36548]
Noted by @a14n in https://github.com/flutter/flutter/pull/30784#pullrequestreview-224436527

```dart
<A>[a, b]..addAll(f())..addAll(<A>[c, d]);
```
migrates to:

```dart
<A>[a, b, ...f(), ...<A>[c, d]];
```

but a better transformation could be:

```dart
<A>[a, b, ...f(), c, d];
```

@bwilkerson : sorry about the title -- please update if you have a better one!

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/99040
