### ISSUE TITLE
Email announce@ with breaking change warning for vm-service auth change

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36549]
Commit: https://github.com/dart-lang/sdk/commit/15b11b018364ce032eae50d78fc8a52b541e2bce

Breaking change notes: 
https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md

**Comment by kevmoo** [comment]
CC @mit-mit – right?

**Comment by mit-mit** [comment]
Yes, please use the breaking change process Kevin links to above!

**Comment by bkonyi** [comment]
[dart-announce](https://groups.google.com/a/dartlang.org/forum/#!topic/announce/DkKC9tARf6g). Still waiting for this to appear on dart-misc.

**Comment by kevmoo** [comment]
@bkonyi – all good now!
