### ISSUE TITLE
Extend convert_to_spreads assist to handle list adds

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36547]
@stereotype441 noticed in https://github.com/flutter/flutter/pull/30784#discussion_r273508002 a migration to:

```dart
return Section(<Line>[Line(prefix), ...codeLines]..add(Line(postfix)));
```

and expected:

```dart
return Section(<Line>[Line(prefix), ...codeLines, Line(postfix)]);
```

It would be great if the assist handled adds.

**Comment by bwilkerson** [comment]
I don't think we want convert_to_spread to produce changes that don't introduce a spread element (the messaging just seems wrong), so I propose adding an inline_invocation assist to handle those cases. (CL out for review.)

**Comment by pq** [comment]
Closing in favor of work in: https://dart-review.googlesource.com/c/sdk/+/99040

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/99040
