### ISSUE TITLE
VM/Interpreter: remove assumptions about alignment of bytecode instructions

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36542]
Currently interpreter assumes that bytecode instructions are 4-byte aligned.
For example, interpreter distinguishes entry frames by a misaligned marker:

```
  static bool IsEntryFrameMarker(uword pc) { return (pc & 2) != 0; }
```

This prevents us from using a more compact encoding of bytecode instructions.

@crelier @rmacnak-google could you help with this?

**Comment by rmacnak-google** [comment]
Yeah, let's move the argument count to a separate slot.

**Comment by crelier** [comment]
We can probably set the pc to a marker value (0 or -1) and as you suggest, use a slot in the entry frame for argc. Let me have a look.
