### ISSUE TITLE
Map does not have a null-aware-chainable "get" method

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#36541]
Take the following example:

```dart
void fn(List<Map> listOfMaps) {
  var x = listOfMaps?.elementAt(0)["key"];
}
```

I am accessing the first element of `listOfMaps`, guarding against null, with `listOfMaps?.elementAt`. However, if `listOfMaps` is null, then so is `listOfMaps?.anything`, so an exception will be raised when ultimately `[]` is called on null.

The solution to this for property access is to chain null-aware all the way down, i.e. `foo?.bar.baz.quux` should be `foo?.bar?.baz?.quux` to be safe. But this cannot be done for operators like `[]`.

In the case of a List, you can replace `list[i]` with `list?.elementAt(i)`, but there is no equivalent method for Map. I propose `V get(K key)` or `V get(Object key)`.

**Comment by ThinkDigitalRepair** [comment]
I agree. I've been having to work around this too by explicitly checking if the map is null first.
I like the optional get method, like Java has, or a `myMap?[key]`, which looks funny, but technically would fall in line with putting a `?` after the object in question.

**Comment by ThinkDigitalRepair** [comment]
In fact, I'd like to propose a few changes that touch on this point.
Since we have null operators to execute or assign if n object *is* null, why not include operators to run or execute if an object isn’t? say, `myInt !? myInt++` or `myObject !?= newValue;`
also, if Dart allows for the null aware operators to be used in conjunction with operators, it would solve this problem and also allow for 
```
myInt?++ //  does this get in the way of the syntax for the proposed non-nullable types?
```

**Comment by jamesderlin** [comment]
Also see https://github.com/dart-lang/sdk/issues/28389.

BTW, I would be very much in favor of `V get(K key)` not only for null-aware-chainability but also to have a version of `operator[]` that type-checks the key.

**Comment by leafpetersen** [comment]
We are adding a null aware subscript operator as part of the [upcoming NNBD release](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md).  See additional discussion [here](https://github.com/dart-lang/language/issues/376).
