### ISSUE TITLE
Isolate stuck as "loading" in Observatory web UI

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36558]
A VS Code uesr (@Ibtesam-Mahmood) has an issue with the analysis server not working correctly that we're trying to track down here:

https://github.com/Dart-Code/Dart-Code/issues/1565

I gave some steps for opening Observatory for the analysis server so we could pause the isolate and see where it is (based on the log files, it has started running code, but then seems to not respond). However when he tries to look at the isolate, it's stuck saying "loading":

<img width="1407" alt="Screen Shot 2019-04-08 at 7 24 36 PM" src="https://user-images.githubusercontent.com/29645101/55763196-f878a980-5a33-11e9-8775-ca706ccd4739.png">

@a-siva do you know what this means? Is it a bug? How can we understand what the isolate is doing?

**Comment by a-siva** [comment]
The fact that you are able to connect to VM and get this output means the VM is still up and running, can you switch to the debug window and see if it is responsive and what stack trace it shows.

**Comment by rmacnak-google** [comment]
It's likely the isolate is in a native function, which the VM cannot interrupt. Does this application use synchronous file/stdio/socket/process operations?

**Comment by DanTup** [comment]
Aha, yes - I think it does sync file access (reading each file that it's analyzing). Is there any way to monitor that (besides instrumenting the code more?).

@Ibtesam-Mahmood I think it may also be worth taking a copy of your project and seeing if you can strip it down to see there's something specific in their triggering the issue.

**Comment by DanTup** [comment]
Closing this as it seems like this may be working as expected if the isolate is in native code. We'll continue to debug in the Dart Code issue - if I can get to repro it on my machine I can easily instrument the server more to figure out what's going on.
