### ISSUE TITLE
CFE still produces kernel files with kUnevaluatedConstant tags in them

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36565]
For debugging purposes it would be better if CFE did not generate kernel files with the kUnevaluatedConstant tags in them and instead produced errors for the constants which could not be evaluated by the front end.

**Comment by askeksa-google** [comment]
In which context are you seeing these unevaluated constants? When running the front end in the Kernel service as part of a JIT compilation, or stand-alone to produce a dill file?

If the front end is given an environment, and it does not encounter any unavailable constructors or variable initializers (as is currently the case sometimes for DDK), it should not produce any unevaluated constants.

We can certainly add an option to the front end to report an error if any constants could not be evaluated.

**Comment by askeksa-google** [comment]
I have added an option in https://dart-review.googlesource.com/c/sdk/+/99121. Is this what you need?

**Comment by kmillikin** [comment]
I'm marking this as P2 (non-blocking).
