### ISSUE TITLE
implement vm:always-inline and vm:never-inline pragmas

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#36571]
We have an old way to give inlining hints to the optimizing compiler via `--enable-inlining-anotations`. This mechanism should be replaced with `@pragma`-s instead. 

We should remove `FLAG_enable_inlining_annotations` and fix all tests in our suites to use `@pragma('vm:always-inline')` or `@pragma('vm:never-inline')` respectively.

We should also remove inlining white and black lists.

**Comment by sstrickl** [comment]
Reopening due to the reverts mentioned above.
