### ISSUE TITLE
returnType is missing from element on SuggestionSets constructors

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36576]
With standard completion items, Constructors have the `returnType` populated on the `element`:

```js
{
	"kind": "INVOCATION",
	"relevance": 1000,
	"completion": "ProcessInfo",
	"selectionOffset": 11,
	"selectionLength": 0,
	"isDeprecated": false,
	"isPotential": false,
	"declaringType": "ProcessInfo",
	"element": {
		"kind": "CONSTRUCTOR",
		"name": "",
		"location": {
			"file": "/Users/dantup/Dev/dart-sdk/nightly-2019-04-11/lib/io/process.dart",
			"offset": -1,
			"length": 0,
			"startLine": 1,
			"startColumn": 0
		},
		"flags": 0,
		"parameters": "()",
		"returnType": "ProcessInfo" // <--------------
	},
	"returnType": "ProcessInfo",
	"parameterNames": [],
	"parameterTypes": [],
	"requiredParameterCount": 0,
	"hasNamedParameters": false
}
```

However this is missing from the SuggestionSets:

```js
{
	"label": "ProcessInfo",
	"element": {
		"kind": "CONSTRUCTOR",
		"name": "",
		"location": {
			"file": "/Users/dantup/Dev/dart-sdk/nightly-2019-04-11/lib/io/process.dart",
			"offset": 4294967295,
			"length": 0,
			"startLine": 0,
			"startColumn": 0
		},
		"flags": 0,
		"parameters": "()"
	},
	"parameterNames": [],
	"parameterTypes": [],
	"requiredParameterCount": 0
}
```

In VS Code we show this in the extra detail. Since `name` is blank here, I don't want to assume that `label` is the class name (because of prefixes, etc.) so I think it's best included in the object.

(cc @scheglov)

**Comment by scheglov** [comment]
The `label` is the class name, because `AvailableSuggestion` cannot include prefixes - they are for declarations in libraries, no matter how they are used. Prefixes are added later on `getSuggestionDetails`, for a specific suggestion selected.

But I don't have any objects against adding return types to constructors, this seems consistent. Will update this issue when done.

**Comment by DanTup** [comment]
>  Prefixes are added later on `getSuggestionDetails`, for a specific suggestion selected.

Ah, of course! Ok, let me know if you have any issue adding it, I can use this as a fallback. Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/99200

**Comment by DanTup** [comment]
@scheglov for some reason I'm still not seeing this:

```

	"label": "ProcessInfo",
	"element": {
		"kind": "CONSTRUCTOR",
		"name": "",
		"location": {
			"file": "/Users/dantup/Dev/dart-sdk/nightly-2019-04-15/lib/io/process.dart",
			"offset": 4294967295,
			"length": 0,
			"startLine": 0,
			"startColumn": 0
		},
		"flags": 0,
		"parameters": "()"
	},
	"parameterNames": [],
	"parameterTypes": [],
	"requiredParameterCount": 0
},
```

I'm using this mornings nightly build, the version number is from the same log file as above:

```
Dart SDK:
    Loc: /Users/dantup/Dev/dart-sdk/nightly-2019-04-15
    Ver: 2.2.1-edge.ec0447db5d27049f5bb87d639e043993a76593cd
```

And I'm spawning the analyzer snapshot from that same version:

> [9:27:48 AM]: Spawning /Users/dantup/Dev/dart-sdk/nightly-2019-04-15/bin/dart with args ["/Users/dantup/Dev/dart-sdk/nightly-2019-04-15/bin/snapshots/analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=2.26.0-dev"]

The file I'm testing with is just this:

```dart
main() {
  ProcessInf
}
```

I see it still missing both in my tests run and if I try it manually. Any ideas?

**Comment by DanTup** [comment]
I deleted `~/.dartServer` and it seems to be working now - maybe something is cached in there?

**Comment by scheglov** [comment]
Yes, I think I did not increment the data version.
