### ISSUE TITLE
[Breaking Change Request] VM service requires authentication code by default

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#36575]
# Change in behavior and rationale
Currently, the VM service will only accept connections coming from localhost unless origin checks are explicitly disabled. This is to prevent attackers from connecting to the VM service over the network and executing arbitrary Dart code. While an origin check is sufficient to prevent execution of malicious code over the network via the VM service, it does not prevent malicious programs from connecting via localhost through the browser or other program running on the same machine. To mitigate the risk of a malicious connection via localhost, the VM service will now requires an authentication code to be provided upon connection.

Previously, a valid web socket connection to the VM service would use the following URI:

`ws://127.0.0.1:8181/ws`

Now, by default, the VM service requires a connection to be made with a URI similar to the following:

`ws://127.0.0.1:8181/Ug_U0QVsqFs=/ws`

where `Ug_U0QVsqFs` is an authentication code generated and shared by the VM service via stdout.

This behavior can be disabled with the --disable-service-auth-codes flag, although it is highly recommended to leave authentication codes enabled unless running on a trusted device behind a firewall.

# Impact and mitigation

For command line users, this change should have no effect other than requiring a new Observatory or DevTools page to be opened with the unique URL on each run. For users of officially supported IDEs and tools (namely Intellij, VSCode, DevTools, and Observatory), this change should be transparent as these tools already support urls with authentication codes (this has been confirmed by @DanTup, @devoncarew, and myself).

For Flutter, this behavior will be disabled by default **for the time being** until the correct changes can be made to `flutter_tools`, particularly for the `flutter attach` workflow.

For Fuchsia, this behavior **is disabled by default** as a non-trivial amount of work is required to add support at the moment.

cc/ @kevmoo

**Comment by aadilmaan** [comment]
Please review and approve - @Hixie @matanlurey @dgrove (@sigmundch and @mit-mit to cover while Dan is out)

**Comment by bkonyi** [comment]
FYI, there's more context to the request based on internal bugs, so feel free to ping me directly for links.

**Comment by aadilmaan** [comment]
Ben - Can you please link those bugs in the comments? Thank you so much.

**Comment by bkonyi** [comment]
> Ben - Can you please link those bugs in the comments? Thank you so much.

These are internal bugs, but b/29808785 is the original. Also, this is a request from the DevTools team for IO, so @jacob314 would have more context as well.

**Comment by sigmundch** [comment]
LGTM

**Comment by mit-mit** [comment]
LGTM

**Comment by mit-mit** [comment]
But please remember to post on dart-announce for external feedback

**Comment by aadilmaan** [comment]
Waiting on @Hixie and @matanlurey approvals.

**Comment by Hixie** [comment]
I thought this was in Flutter already.

I recommend that we not support `--disable-service-auth-codes`. It introduces a second codepath that is by design less secure and is bound to be less tested and is therefore likely to break in places we don't think about. Our life would be easier if it didn't exist.

**Comment by jacob314** [comment]
This is in Flutter already. I agree that we should remove `--disable-service-auth-codes` from Flutter now that  we have migrated to use the auth codes by default. If there are pain points for command line users we should fix those (for example, add a flutter tools command to launch DevTools directly).

**Comment by bkonyi** [comment]
I don't think that there was any plan to remove `--disable-service-auth-codes` as the authentication codes can be tedious to deal with when querying the service protocol directly over HTTP (@rmacnak-google, this is something you do semi-frequently, right?).

**Comment by Hixie** [comment]
If they're tedious to deal with then we should fix it so they're not tedious. Our security is only as strong as the weakest link. It's like having a bank vault with a side door because going through the vault door is too inconvenient.

**Comment by rmacnak-google** [comment]
`--disable-service-auth-codes` and `--disable-service-origin-check` should both be removed.

**Comment by bkonyi** [comment]
Are we more concerned about the ability to disable authentication codes in general or the fact that there's a flag exposed to do this? Fuchsia doesn't currently support authentication codes, so there needs to be a way to disable them within Flutter and the VM at launch. 

cc @zanderso

**Comment by zanderso** [comment]
Right. The existence of the command line flags is not important to Fuchsia, but since auth codes are not dealt with there yet, there should exist a way to disable them until resources can be allocated to support them.

**Comment by jacob314** [comment]
I agree that `--disable-service-origin-check` should be removed. However, value should be that the check is disabled not enabled as `service-auth-codes` provide orders of magnitude better security than the spoof-able `service-origin-check`. 
The security token is a vault door. The origin check is just a sign saying "please do not enter". The origin check makes it harder for us to support remote debugging cases such as https://github.com/flutter/devtools/issues/637 so the security benefit is minimal but gets in the way of use cases we would like to support.

**Comment by mmcc007** [comment]
Removing `disable-service-auth-codes` for flutter would be an inconvenience to those using hot reload for integration tests. Though there may be a workaround to get the auth code from the syslog.

For more on using hot reload for integration tests see https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54

**Comment by jacob314** [comment]
We should find a way to make that hot reload for integration tests workflow work smoothly without disabling auth codes. Plumbing the autho codes through either via the syslog or a mechanism like the flutter tools daemon protocol seems like the way to go.

**Comment by mit-mit** [comment]
What's the status of this request?

**Comment by bkonyi** [comment]
The original issue covered by this request has been resolved (authentication codes have been enabled by default for the VM service since May). However, `--disable-service-auth-codes` is still used throughout the Flutter and Dart test infrastructure which we should deal with at some point, but that's now tracked by https://github.com/dart-lang/sdk/issues/38527.
