### ISSUE TITLE
Confusing incompatibility between "the same type" twice

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#36577]
Consider the following program (cf. https://github.com/dart-lang/sdk/issues/36569 where this came up):

```dart
void main() {
  var bar = Bar()..setList();
}

void addItem(List list, Object item) => list.add(item);

abstract class Foo<T> {
  List<T> get list; 
  void setList<T>({List<T> value = const <Null>[]});
}

class Bar implements Foo<int> {
  List<int> list;
  void setList<int>({List<int> value = const <Null>[]}) {
    list = value;
  }
}
```

We get the following response from the `dart` vm (at the indicated versions):

```
lang/dart/scratch/201904(master %)$ ~/bin/dart-sdk-2.0.0-dev.63.0/bin/dart n015.dart
lang/dart/scratch/201904(master %)$ ~/bin/dart-sdk-2.0.0-dev.64.0/bin/dart n015.dart
n015.dart:16:12: Error: A value of type 'dart.core::List<#lib1::Bar::setList::int>' can't be assigned to a variable of type 'dart.core::List<dart.core::int>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::List<dart.core::int>'.
    list = value;
           ^
```

The error seems to be spurious, the types should be the same `List<int>` in both cases, no matter how that's spelled.

I would assume that this is a front-end issue, so I'll use that label.

**Comment by eernstg** [comment]
Sorry, I misread the code, `int` is actually the name of a type variable declared by `Bar.setList`.

This means that 2.0.0-dev.63.0 had a bug (because it did not detect the type error), but that's a long time ago. ;-)

Double-checking, I think everything is working as intended. Hence, I'll close the issue.

**Comment by jensjoha** [comment]
As a side note I'll try to make the message be less bad.

**Comment by eernstg** [comment]
Sounds like that would essentially be concerned with the readability of constructs like `#lib1::Bar::setList::int`? If you know how to read that then the message isn't that bad, I think.

**Comment by jensjoha** [comment]
In the above, true, but today the error message is
```
Error: A value of type 'List<int>' can't be assigned to a variable of type 'List<int>'.
 - 'List' is from 'dart:core'.
```

**Comment by eernstg** [comment]
OK, that's in need of improvements!
