### ISSUE TITLE
Update path to latest pkg:test location

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36581]
https://github.com/dart-lang/sdk/blob/561dc79a7b6d09b0af09a82cdeaf30c425ad6422/pkg/kernel/pubspec.yaml#L17-L18

RE https://github.com/dart-lang/sdk/commit/561dc79a7b6d09b0af09a82cdeaf30c425ad6422

**Comment by natebosch** [comment]
Why does this file even have `dev_dependencies` like this? They're incomplete and can't be used... What are they accomplishing?

**Comment by kevmoo** [comment]
🤷‍♂️

**Comment by natebosch** [comment]
I'm going to change them to `any`.

https://dart-review.googlesource.com/c/sdk/+/99204

**Comment by natebosch** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/f6573719721e28ffeb5f020d3bfb05d473891d1b
