### ISSUE TITLE
Implement lazy evaluations of constants instead of eagerly reading the constant table and evaluating all constants while loading the kernel file

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36584]
With CFE now evaluating constant expressions when constant_update_2018 is used the kernel file has a constant table and the VM eagerly reads the constant table and evaluates all the constants in it while loading the kernel file. This eager reading will not work when we load multiple kernel files with some kernel files having forward references. 

Instead constants should be read and evaluated lazily when they are needed.

**Comment by aartbik** [comment]
A WIP CL can be found at:

https://dart-review.googlesource.com/c/sdk/+/99088

**Comment by dgrove** [comment]
Not required for D24

**Comment by aartbik** [comment]
The lazy constant reader has been submitted, so I am closing this bug. All follow-up items are tracked in the related bug https://github.com/dart-lang/sdk/issues/36220
