### ISSUE TITLE
error: expected: obj.IsSmi()

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36589]
Isolate (/b/s/w/itOOGpNh/dart_fuzzNUSODX) KBC-CMP-DebugX64 - JIT-DebugIA32: !DIVERGENCE! 1.9:1190873720 (output=false)

fail2:
../../runtime/vm/object.h: 7005: error: expected: obj.IsSmi()
version=2.2.1-edge.bed1bab2cd4b79694db9ace0e5497b8bb9eb1ab8 (Thu Apr 11 02:01:03 2019 +0000) on "linux_ia32"
thread=9528, isolate=main(0x4270b00)
  pc 0x01a135dc fp 0xf70fbef8 dart::Profiler::DumpStackTrace(void*)
  pc 0x01cb6ba4 fp 0xf70fbf18 Dart_DumpNativeStackTrace
  pc 0x01cb8b5b fp 0xf70fbf48 dart::Assert::Fail(char const*, ...)
  pc 0x01b4ca0a fp 0xf70fbf88 /b/s/w/ir/out/DebugIA32/dart+0x174ca0a
  pc 0x01b4c62b fp 0xf70fbfe8 dart::LoadIndexedInstr::MakeLocationSummary(dart::Zone*, bool) const
  pc 0x01b8051d fp 0xf70fc068 dart::SSALivenessAnalysis::ComputeInitialSets()
  pc 0x01b0bbde fp 0xf70fc0b8 dart::LivenessAnalysis::Analyze()
  pc 0x01b8b607 fp 0xf70fc0f8 dart::FlowGraphAllocator::AllocateRegisters()
  pc 0x01bca65a fp 0xf70fc2f8 /b/s/w/ir/out/DebugIA32/dart+0x17ca65a
  pc 0x01bc92e0 fp 0xf70fc388 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x01bc9712 fp 0xf70fc3b8 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x01c3b5b0 fp 0xf70fc738 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x01c3c7d9 fp 0xf70fcee8 /b/s/w/ir/out/DebugIA32/dart+0x183c7d9
  pc 0x01c3d8af fp 0xf70fcf68 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, int)
  pc 0x01a7b206 fp 0xf70fd628 dart::DRT_OptimizeInvokedFunction(dart::NativeArguments)
  pc 0xf7180779 fp 0xf70fd648 Unknown symbol
  pc 0xf7180afc fp 0xf70fd660 Unknown symbol
  pc 0xf68299f3 fp 0xf70fd6d8 Unknown symbol
  pc 0xf68248ba fp 0xf70fd700 Unknown symbol
  pc 0xf68246ff fp 0xf70fd718 Unknown symbol
  pc 0xf68245f2 fp 0xf70fd72c Unknown symbol
  pc 0xf6823b68 fp 0xf70fd748 Unknown symbol
  pc 0xf6808415 fp 0xf70fd760 Unknown symbol
  pc 0xf68238b5 fp 0xf70fd778 Unknown symbol
  pc 0xf7180bad fp 0xf70fd7a4 Unknown symbol
  pc 0x018c3284 fp 0xf70fd818 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  pc 0x018c2eb5 fp 0xf70fd858 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  pc 0x018c6437 fp 0xf70fd8a8 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x01903dca fp 0xf70fdff8 dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  pc 0x01940981 fp 0xf70fe068 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x019415f4 fp 0xf70fe0c8 dart::MessageHandler::TaskCallback()
  pc 0x01942aec fp 0xf70fe0f8 /b/s/w/ir/out/DebugIA32/dart+0x1542aec
  pc 0x01abed5f fp 0xf70fe148 dart::ThreadPool::Worker::Loop()
  pc 0x01abe8fa fp 0xf70fe198 dart::ThreadPool::Worker::Main(unsigned int)
  pc 0x01a0d76f fp 0xf70fe2e8 /b/s/w/ir/out/DebugIA32/dart+0x160d76f
  pc 0xf76cf295 fp 0xf70fe3a8 /lib/i386-linux-gnu/libpthread.so.0+0x6295
-- End of DumpStackTrace

**Comment by aartbik** [comment]
Using DebugIA32/dart, we get

```
dart fuzz.dart

../../runtime/vm/object.h: 7008: error: expected: obj.IsSmi()
version=2.2.1-edge.74f3dd3a3adbbd121a26851e6443a2410251edd1 (Mon Apr 15 10:06:40 2019 -0700) on "linux_ia32"
thread=123909, isolate=main(0x4513b80)
  pc 0x01aa7c8c fp 0xf5e7c9b8 dart::Profiler::DumpStackTrace(void*)
  pc 0x01d4e9f4 fp 0xf5e7c9d8 Dart_DumpNativeStackTrace
  pc 0x01d509cb fp 0xf5e7ca08 dart::Assert::Fail(char const*, ...)
  pc 0x01be21aa fp 0xf5e7ca48 /usr/local/google/home/ajcbik/drive2/dart/sdk/out/DebugIA32/dart+0x17e21aa
  pc 0x01be1dcb fp 0xf5e7caa8 dart::LoadIndexedInstr::MakeLocationSummary(dart::Zone*, bool) const
  pc 0x01c15ccd fp 0xf5e7cb28 dart::SSALivenessAnalysis::ComputeInitialSets()
  pc 0x01ba13ee fp 0xf5e7cb78 dart::LivenessAnalysis::Analyze()
  pc 0x01c20de7 fp 0xf5e7cbb8 dart::FlowGraphAllocator::AllocateRegisters()
  pc 0x01c60baa fp 0xf5e7cdb8 /usr/local/google/home/ajcbik/drive2/dart/sdk/out/DebugIA32/dart+0x1860baa
  pc 0x01c5f830 fp 0xf5e7ce48 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x01c5fc62 fp 0xf5e7ce78 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x01cd2ff0 fp 0xf5e7d1f8 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x01cd4219 fp 0xf5e7d9a8 /usr/local/google/home/ajcbik/drive2/dart/sdk/out/DebugIA32/dart+0x18d4219
  pc 0x01cd52ef fp 0xf5e7da28 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, int)
  pc 0x01cd69da fp 0xf5e7e0d8 dart::BackgroundCompiler::Run()
```

**Comment by aartbik** [comment]
Attached the fuzz.dart as txt.
[fuzz.dart.txt](https://github.com/dart-lang/sdk/files/3081494/fuzz.dart.txt)

**Comment by aartbik** [comment]
This crashes in LoadIndexedInstr::MakeLocationSummary() of il_ia32.cc on the instruction
` v16917 <- LoadIndexed(v16915, v9742 T{_Mint})`
when calling CanBeImmediateIndex().

**Comment by aartbik** [comment]
Traced this further to Assembler::IsSafeSmi() for ia32, where we have the following code, which returns true for the power of two tests when value == 8589934591

```
static bool IsSafeSmi(const Object& object) {
    int64_t value;
    if (HasIntegerValue(object, &value)) {
      return Utils::IsInt(16, value) || Utils::IsPowerOfTwo(value) ||
             Utils::IsPowerOfTwo(value + 1);
    }
    return false;
  }

```

**Comment by aartbik** [comment]
I think using

`const int64_t index = Integer::Cast(constant->value()).AsInt64Value();`

is the right way of fixing this. The test guarantees this cast will succeed, and the rest of the computations will still correctly test if this is a proper immediate index. I saw a similar case for arm32.

**Comment by aartbik** [comment]
We could fix this by using Integer::Cast at several places, but I am starting to wonder if the problem happened earlier. Did we violate a smi assumption somewhere?

@mraleph @mkustermann

**Comment by mkustermann** [comment]
@aartbik 

In all places where we insert `LoadIndexedInstr` into the graph we insert explicit bounds checks of the index before the load (the instruction itself doesn't check bounds).

This load instruction works on array/growable-arrays as well as our typed data classes. All of these arrays have, by construction, a Smi length (the length is encoded as `RawSmi*` in all of those classes).

This implies that the `LoadIndexedInstr` the compiler is barfing on is actually dead code (the `CheckArrayBound` would throw at runtime). The integer used here is `0x1ffffffff` which is not a valid Smi.

So we can either

  * prune the dead code reliably (see also https://github.com/dart-lang/sdk/issues/33414) or
  * make the `LoadIndexedInstr` (and `StoreIndexedInstr`) handle constant non-Smi index (and emit code to deopt / int3).

There's already some handling of dead code in the `CheckArrayBoundInstr`, though not for non-Smi:

```c++
  if (length_loc.IsConstant() && index_loc.IsConstant()) {
    ASSERT((Smi::Cast(length_loc.constant()).Value() <=
            Smi::Cast(index_loc.constant()).Value()) ||
           (Smi::Cast(index_loc.constant()).Value() < 0)); 
    // Unconditionally deoptimize for constant bounds checks because they
    // only occur only when index is out-of-bounds.
    __ jmp(deopt);
    return;
  }
```

**Comment by aartbik** [comment]
Small reproducer for ia32:

```dart
List<int> x;

@NeverInline
int foo() {
  return x[8589934591];
}

main() {
  x = new List(1);
  x[0] = -1;
  int i = 1;
  for (int j = 0; j < 20; j++) {
    try {
      i = foo();
    } catch (e, s) {
      i++;
    }
  }
  Expect.equals(21, i);
  Expect.equals(-1, x[0]);
}

```

**Comment by aartbik** [comment]
@mkustermann 

Note that the code you referred to is also easy to break once you know what to look for :-) For now I am sending out a CL that does some local repairs of this IA32 omission, just to keep DartFuzz going again. But in the long run I like the idea of treating this as a combination of (1) DCE, removing the load/store if the check always fails (2) replacing the check with a direct throw.

```dart
 if (length_loc.IsConstant() && index_loc.IsConstant()) {
    ASSERT((Smi::Cast(length_loc.constant()).Value() <=
            Smi::Cast(index_loc.constant()).Value()) ||
           (Smi::Cast(index_loc.constant()).Value() < 0)); 
```
breaks for
```dart
int foo() {
  List<int> x = new List(1);
  return x[8589934591];
}
```
