### ISSUE TITLE
_getCpuProfileTimeline response inconsistent for debug/profile mode

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#36583]
In DevTools, we are pulling CPU samples for a timeline event as follows:
```
      callMethod(
          '_getCpuProfileTimeline',
          isolateId: isolateId,
          args: {
            'tags': 'None',
            'timeOriginMicros': origin,
            'timeExtentMicros': extent,
          },
        ));
```
There seems to be an issue where the query doesn't match the response in a profile build. Here are a couple responses illustrating the differences. Both examples are from an event with duration 0.3ms, which is what was passed as 'extent' in the above method call, so I would think that the number of samples and the timeExtentMicros would be similar, but they are not.

The **timeExtentMicros** for the profile build example seems suspicious. The query passed in was ~300 micros.

Sample response from profile build:
```
{  
   type:_CpuProfileTimeline,
   samplePeriod:50,
   stackDepth:128,
   sampleCount:1062,
   timeSpan:4.878267,
   timeOriginMicros:530809635141,
   timeExtentMicros:4878267,
```
Sample response from debug build:
```
{  
   type:_CpuProfileTimeline,
   samplePeriod:50,
   stackDepth:128,
   sampleCount:4,
   timeSpan:0.000286,
   timeOriginMicros:7626172541,
   timeExtentMicros:286,
```

Perhaps in profile mode, a different query format is expected? It seems odd that **timeExtentMicros** is so different from the query that was passed in. 

 cc/ @bkonyi @a-siva

**Comment by kenzieschmoll** [comment]
It also seems impossible to have over 1000 samples in 0.3ms at a samplePeriod of 50? Something strange must be going on somewhere.

**Comment by bkonyi** [comment]
Appears to have been fixed by [this CL](https://dart-review.googlesource.com/c/sdk/+/99365), so I'll close this for now.
