### ISSUE TITLE
error: expected: (d & kDMask) == d

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36588]
Isolate (/b/s/w/iterwHF5/dart_fuzzVLIYWD) JIT-NOFIELDGUARDS-ReleaseX64 - JIT-DebugSIMDBC64: !DIVERGENCE! 1.9:3654411966 (output=false)

fail2:
../../runtime/vm/constants_dbc.h: 1004: error: expected: (d & kDMask) == d
version=2.2.1-edge.bed1bab2cd4b79694db9ace0e5497b8bb9eb1ab8 (Thu Apr 11 02:01:03 2019 +0000) on "linux_dbc"
thread=23970, isolate=main(0x56316a7db200)
  pc 0x00005631686f23cc fp 0x00007f44a62bbd00 dart::Profiler::DumpStackTrace(void*)
  pc 0x00007f44a62bc278 fp 0x00007f44a62bc4f0 Unknown symbol
-- End of DumpStackTrace

**Comment by aartbik** [comment]
Using DebugSIMDBC64/dart, we get

```
$ dart fuzz.dart
../../runtime/vm/constants_dbc.h: 1004: error: expected: (d & kDMask) == d
```

Attaching fuzz.dart (as txt) for your convenience.
[fuzz.dart.txt](https://github.com/dart-lang/sdk/files/3081437/fuzz.dart.txt)

**Comment by dcharkes** [comment]
The instruction emitted is `__ InstanceCall2(ArgumentCount(), call_ic_data_kidx)`.

`call_ic_data_kidx` = 65536, which does not fit into 16 bits (`d` is 16 bits).

This program has more than 65535 constants in the pool, which we do not support at the moment.

Documentation of `InstanceCall2`:

```
//  - InstanceCall<N> ArgC, D; InstanceCall<N>Opt ArgC, D
//
//    Lookup and invoke method with N checked arguments using ICData in PP[D]
//    with arguments SP[-(1+ArgC)], ..., SP[-1].
//    The ICData indicates whether the first argument is a type argument vector.
```

@aartbik, is this a case we should support. Or is this unlikely to happen in user programs?

**Comment by dcharkes** [comment]
Judging from [constants_dbc.h](https://github.com/dart-lang/sdk/blob/master/runtime/vm/constants_dbc.h), the whole DBC bytecode is designed to work with 64k constants:

```
//  - Nop D
//
//    This instruction does nothing. It may refer to an object in the constant
//    pool that may be decoded by other instructions.

//   +--------+--------+--------+--------+
//   | opcode |~~~~~~~~|        D        |   D: unsigned 16-bit operand
//   +--------+--------+--------+--------+
```

and 

```
//  - LoadConstant rA, D; PushConstant D
//
//    Load value at index D from constant pool into FP[rA] or push it onto the
//    stack.

//   +--------+--------+--------+--------+
//   | opcode |    A   |        D        | A_D: unsigned 8-bit operand and
//   +--------+--------+--------+--------+      unsigned 16-bit operand
```

And it looks like the native functions are the first entries in the constant pool. Every native function uses 3 constant pool entries, and the native call instruction can only access the first 256 constants in the pool. (Which means we can only have 85 native calls in DBC?)

```
//  - NativeCall ArgA, ArgB, ArgC
//
//    Invoke native function at pool[ArgB] with argc_tag at pool[ArgC] using
//    wrapper at pool[ArgA].
```

**Comment by dcharkes** [comment]
Oh, the DBC bytecode is designed to work with 64k constants __per executing function__. 
`//   PP - object pool for the currently execution function`

The function `run` in `fuzz.dart` is 2000+ lines.

This is the same issue as: https://github.com/dart-lang/sdk/issues/35242

**Comment by aartbik** [comment]
As also noted in https://github.com/dart-lang/sdk/issues/36646, I think we should support this case. The fuzzer may be a bit extreme, but I can see real-world programs have 64K (think: program generators). What do you think?

**Comment by aartbik** [comment]
Closing this one, as we have a general tracking bug.
