### ISSUE TITLE
HttpRequest error UnknownJavascriptObject

### ISSUE THREAD

**Issue by pinnisi** [dart-lang/sdk#36594]
* Dart SDK 2.1.0 and 2.2.0
* tested on Safari 9 on iOS 9.3

running a simple http get request, as

`HttpRequest.getString('test.txt').then(print);`

causes this error:

TypeError: Instance of 'UnknownJavascriptObject': type 'UnknownJavascriptObject' is not subtype of type 'Event'.

<img width="1680" alt="error" src="https://user-images.githubusercontent.com/9946496/56029256-53ebb580-5d1a-11e9-8a5a-52d5658e4499.png">

and the request fails. Works in newer iOS/Safari versions

**Comment by kevmoo** [comment]
Safari 9 is outside our official supported version range.

Can you replicate this on a newer version of Safari? (11 or 12?)

https://webdev.dartlang.org/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets

**Comment by ericmartineau** [comment]
I'm having this issue in Version 14.0.2 (16610.3.7.1.9)

```
_failedAsCheck
_generalNullableAsCheckImplementation
_installSpecializedAsCheck 
call$1 
invokeClosure
(anonymous function)
--- addEventListener ---
_addEventListener$3 
addEventListener$3
addEventListener$3$x
_tryResume$0 
onData$1 
```

```
 W._EventStreamSubscription_onData_closure.prototype = {
    call$1: function(e) {
      /// This line is where the error occurs
      return this.handleData.call$1(type$.Event._as(e));
    },
    $signature: 30
  };
```

I'm using the `dio` library, which delegates calls to `dart:html` HttpRequest.  The main flutter application is not having the same issue; this issue is happening within a separate web entrypoint that's used as a webworker.  Works fine in Chrome, but not Safari
