### ISSUE TITLE
assertion_initializer_const_error2_test fails because asserts are not enabled

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36599]
The `language_2/assertion_initializer_const_error2_test` test fails on several configurations because asserts are not enabled for the front-end run. After https://dart-review.googlesource.com/c/sdk/+/99169 the bytecode configurations are added to the mix.

Fixing this might be as simple as replacing `dart2jsOptions=--enable-asserts` by `SharedOptions=--enable-asserts`.

**Comment by vsmenon** [comment]
Does this need to be 2.3?  Are we concerned there is a real bug here, or is this just a test framework fix?

**Comment by stefantsov** [comment]
Yes, it's a test framework fix.

**Comment by askeksa-google** [comment]
Assert initializers in `const` constructors are now always evaluated during constant evaluation, so the test passes.
