### ISSUE TITLE
service/get_source_report_test fails because of fixed expectations

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36600]
The test `service/get_source_report_test` fails after the `constant-update-2018` flag is enabled in this line:
```dart
expect(((numRanges == 9) || (numRanges == 10)), isTrue);
```
It seems some code changed because of the constant evaluation and this caused the number of ranges to be different. The test should be updated.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/99268 should fix this.
