### ISSUE TITLE
Please merge # 394f88d into dev channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36604]
**commit(s) to merge**: #394f88d

**merge instructions**: clean merge

**reason**: prevents regression on source-maps when enabling constant-update-2018.

Note: this cherry-pick is only needed if we are doing a cherry-pick of the contsnat-update-2018 flag change. If we are doing a full merge to dev instead, then we just need to make sure this hash is included.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
The commit in question was pushed to the dev channel with 2.3.0-dev.0.0.
