### ISSUE TITLE
bug in unevaluated constants within string interpolation

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36609]
It appears that when using unevaluated constants, string interpolation incorrectly stringifies an unevaluated subexpression. 

To repro: uncomment these lines:
https://github.com/dart-lang/sdk/blob/master/tests/compiler/dart2js/model/cfe_constant_evaluation_test.dart#L320
and rerun the unit test.

This shows up under `tests/compiler/dart2js/model/cfe_constant_evaluation_test.dart`, where we purposely force delaying evaluation of constants in the test:
```
  const f1 = const bool.fromEnvironment("x") ? null : "${proxy}";
```

This only started failing after enabling constant-update-2018 by default.

Note that `proxy` is defined in `dart:core` and that enabling the feature by default has an indirect effect on serialization because how dart2js uses its platform file. When we pass a non-default flag by hand the platform.dill is not used by dart2js, so the entire constant was evaluated in memory.

When we flipped the flag by default, this test started reading serialized constants from the .dill file.

This patch solves the issue for me, but I'm not 100% sure this is correct (I'm swapping the condition, because all evaluated values are added to a string buffer):

```diff
--- a/pkg/front_end/lib/src/fasta/kernel/constant_evaluator.dart
+++ b/pkg/front_end/lib/src/fasta/kernel/constant_evaluator.dart
@@ -1963,11 +1963,11 @@ class ConstantEvaluator extends RecursiveVisitor<Constant> {
       final expressions = new List<Expression>(concatenated.length);
       for (int i = 0; i < concatenated.length; i++) {
         Object value = concatenated[i];
-        if (value is UnevaluatedConstant) {
-          expressions[i] = extract(value);
-        } else {
+        if (value is StringBuffer) {
           expressions[i] = new ConstantExpression(
               canonicalize(new StringConstant(value.toString())));
+        } else {
+          expressions[i] = extract(value);
         }
       }
  ```

**Comment by vsmenon** [comment]
@sigmundch - any update?  is someone looking at this?

**Comment by sigmundch** [comment]
I don't believe anyone is looking into it yet. It however is a case where we are more permissive than we should, so it could be relaxed to a P2 if needed.

@stefantsov - are you familiar with this area of the compiler?  I would ask @askeksa-google to take a look, but I believe he is out on holiday.

In general - I think my patch above would fix string-interpolation, but I worry that there is a more general problem with unevaluated constants that needs to be looked at.

**Comment by vsmenon** [comment]
@stefantsov - can you take a look and assign back to @sigmundch if needed?

**Comment by sigmundch** [comment]
@johnniwinther - also may be able to help

**Comment by vsmenon** [comment]
@johnniwinther has fix out for this:

https://dart-review.googlesource.com/c/sdk/+/99461
