### ISSUE TITLE
Some test crash on DBC with constant update

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36603]
With https://dart-review.googlesource.com/c/sdk/+/99169 on the DBC builders, these three tests crash: `language_2/const_inference_test`, `language_2/partial_tearoff_instantiation_test/none`, `language_2/vm/regress_33095_test`. See for instance https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-debug-simdbc64/5493.

**Comment by a-siva** [comment]
There are two sets of failures
- one set is similar to the errors seen in https://github.com/dart-lang/sdk/issues/36500
- the other set is https://github.com/dart-lang/sdk/issues/36500
Closing this issue as a duplicate of these two issues.
