### ISSUE TITLE
VM: `main` receives an argument which is not a `List<String>`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#36626]
Cf. https://github.com/dart-lang/dart-pad/issues/1009, the vm invokes the `main` function of a script with an argument which is not of type `List<String>`.

```dart
main(args) {
  print(args.runtimeType is List<String>); // Prints 'false'.
}
```

The specification requires that it is a `List<String>`, [here](https://github.com/dart-lang/language/blob/59c1810f871116bec4d3e7629e0b6c81712d7bd6/specification/dartLangSpec.tex#L13951), and this would also be a reasonable choice in practice.

**Comment by jamesderlin** [comment]
If I add `print('${args.runtimeType}');`, it prints `List<String>`.  Huh?

**Comment by rmacnak-google** [comment]
You mean

```
main(args) {
  print(args is List<String>); // Prints 'true'.
}
```

**Comment by jamesderlin** [comment]
Sorry, my last comment might not have been clear.  When I run:
```
main(args) {
  print(args.runtimeType is List<String>);
  print('${args.runtimeType}');
}
```
I get:
```
false
List<String>
```
which makes no sense.

**Comment by eernstg** [comment]
@jamesderlin wrote:
> makes no sense

I mixed up two versions of the test program, the vm works correctly. You should test 'args is List<String>` as @rmacnak-google said, and it does return true. Testing `args.runtimeType is T` is true if and only if `T` is a supertype of `Type`, so it's false as tested.
