### ISSUE TITLE
Platform.operatingSystemVersion returns uname output on Android

### ISSUE THREAD

**Issue by Laogeodritt** [dart-lang/sdk#36625]
Hi all,

_(Unsure of the structure of dart+flutter and whether this is a dart SDK issue or an issue of the implementation in flutter; I did a quick search flutter-side for `operatingSystemVersion` and `_operatingSystemVersion` and didn't find anything, so I'm assuming the Dart SDK implements this. Please redirect me if needed.)_

On Android using Flutter, `Platform.operatingSystemVersion` outputs the `uname` info containing Linux kernel information. It would be more intuitive to Android users/developers for this value to be the Android OS version, and the documentation doesn't make it fully clear what to expect from this property to me.

For example, on an Android 6.0.1 device:

* Expected value: `"6.0.1"`
* Actual output: `"Linux 3.18.20-perf+ #1 SMP PREEMPT Tue Jul 5 20:55:09 CST 2016"`.

(Alternatively, if this is the desired behaviour, then I would suggest that the documentation needs to be clearer on what to expect from `operatingSystemVersion`, and that some way of obtaining the OS version rather than kernel version should be available.)

## Version information

* Target OS: Android 6.0.1
* Flutter 1.2.1
* Dart VM 2.1.0
* Development/build on Linux x64

## Related information

* `Platform` class file: https://github.com/dart-lang/sdk/blob/dev/sdk/lib/io/platform.dart
* `Platform.operatingSystemVersion` was added in issue #30018

**Comment by datasun** [comment]
Platform.operatingSystemVersion = "QP1A.190711.020.A105FNXXS6BUB1" when running on Android Q. From this ticket's request rather "10.01" is expected. A parsable version number would be more developer-friendly.
