### ISSUE TITLE
analysis server error

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36638]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.2.1-dev.4.2`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.2.1-dev.4.2, server version 1.26.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1555345352326}
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:470:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/report.txt.

**Comment by a-siva** [comment]
This issue has been seem many times and hence raising priority.

**Comment by Sejdra-ing** [comment]
Same problem with the coverage of test flutter 
`flutter test --coverage`

**Comment by Thetyne** [comment]
Same here with 4 test of widget :(

**Comment by devoncarew** [comment]
I see that this is also occuring in Dart SDKs `2.4.0` - I believe the last stable flutter release.

**Comment by devoncarew** [comment]
This was fixed in https://dart-review.googlesource.com/c/sdk/+/100461.

cc @scheglov @stereotype441

**Comment by halvorsen** [comment]
This same for-loop iterator error occurs when I do integration tests as described here (https://flutter.dev/docs/testing), the for-loops work fine when running the app without the tests. (I've tested on all the different build release channels described here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels, including the master branch which I believe should have the above fix posted by devoncarew). Should I report a new error?

**Comment by stereotype441** [comment]
@halvorsen can you post the full stack trace, and the version information (including, if possible, the SHA of the Dart SDK) here?  That should be enough information for us to tell whether it's the same bug resurfacing or a new bug; if it's a new bug we can always move it to a new bug report.

**Comment by halvorsen** [comment]
VERSION

Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"

STACK TRACE

00:00 +8 -1: Local Storage Tests get project ids by modification date [E]
  NoSuchMethodError: The getter 'iterator' was called on null.
  Receiver: null
  Tried calling: iterator
  dart:core-patch/object_patch.dart 50:5                     Object.noSuchMethod
  dart:core-patch/array_patch.dart 52:19                     new List.from
  package:root_storage_api/src/project_info.dart 46:12       ProjectInfo.fromString
  package:root_storage_api/src/common_info.dart 27:44        new CommonInfo.fromJson
  package:root_storage_api/src/project_info.dart 29:51       new ProjectInfo.fromJson
  package:root_local_storage/src/project_storage.dart 35:39  _LocalStorage&Object&BaseStorage&UserStorage&ProjectStorage.loadProjectInfo
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                          _Completer.completeError
  dart:async-patch/async_patch.dart 40:18                    _AsyncAwaitCompleter.completeError
  package:root_local_storage/src/project_storage.dart        _LocalStorage&Object&BaseStorage&UserStorage&ProjectStorage.loadProjectInfo
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                               _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                    _asyncThenWrapperHelper
  package:root_local_storage/src/project_storage.dart        _LocalStorage&Object&BaseStorage&UserStorage&ProjectStorage.loadProjectInfo
  package:root_local_storage/src/project_storage.dart 65:35  _LocalStorage&Object&BaseStorage&UserStorage&ProjectStorage.projectInfosByDate
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                               _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                    _asyncThenWrapperHelper
  package:root_local_storage/src/project_storage.dart        _LocalStorage&Object&BaseStorage&UserStorage&ProjectStorage.projectInfosByDate
  test_driver/file_storage_test.dart 185:38                  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                               _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                    _asyncThenWrapperHelper
  test_driver/file_storage_test.dart                         main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 168:27          Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                               _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                    _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart                 Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15           Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                               _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                new Timer
  dart:async/timer.dart 87:9                                 Timer.run
  dart:async/future.dart 174:11                              new Future
  package:test_api/src/backend/invoker.dart 399:21           Invoker._onRun.<fn>.<fn>.<fn>

**Comment by stereotype441** [comment]
@halvorsen thanks!  Although your exception message is the same as the one in this bug, the rest of your stack trace is very different, so the bug you're experiencing isn't the same bug.  It looks from your stacktrace like your bug is likely in the package `root_storage_api`, so I would recommend reporting the problem to the authors of that package.  I couldn't find that package on pub.dev; do you know where it came from?

**Comment by halvorsen** [comment]
that's my own package. I'll look into it more, if it seems like it's my own error. Thanks for looking into it.
