### ISSUE TITLE
New AndroidManifest.xml errors and warnings not working yet

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#36637]
The new AndroidManifest.xml errors and warnings aren't working completely yet.

PR: https://dart-review.googlesource.com/c/sdk/+/98040.

Bug:  In context_manager.dart, the `getChildAssumingFile` in:

`File manifestFile = folder.getChildAssumingFile(MANIFEST_NAME);`

does not appear to search the `folder` recursively,  `getChildAssumingFile` assumes a relative path is being passed (but `AndroidManiest.xml` is being passed).  This means that if the `AndroidManiest.xml` is not at the root of the project, this will note return the File object here.

This was confirmed by copying the `AndroidManiest.xml` to the root of the project and seeing correct behavior from the dart analysis server in IntelliJ.

**Comment by stereotype441** [comment]
Believed to be fixed by 32f522311963b34393b2ebdf1aefd4df4df3f2d4.  @jwren can you test and confirm?

**Comment by bwilkerson** [comment]
Keerti confirmed. Fixed by https://dart-review.googlesource.com/c/sdk/+/99401.

**Comment by jwren** [comment]
I just synced, built the SDK locally, and confirmed manually in IntelliJ that the issue is resolved.
