### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by luisfilipels** [dart-lang/sdk#36633]
- Dart SDK Version: 2.2.0
- Windows 10, 64-bit

[report1.txt](https://github.com/dart-lang/sdk/files/3079841/report1.txt)

This happens whenever I open an existing dart/flutter project using the IntelliJ IDE. If I create a new project, everything seems to work correctly. Deleting the .analysis-driver folder did not solve the issue. Also, the "Restart Dart Analysis Server" button in IntelliJ seems to have no effect whatsoever.

**Comment by srawlins** [comment]
Thanks for reporting this crash; unfortunately we did not get to investigate before this report became stale. Please re-open this if you see it again in a recent version of Dart.
