### ISSUE TITLE
AndroidManifest.xml - warning doesn't get updated as analysis_options.yaml is updated

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#36650]
Context: https://github.com/dart-lang/sdk/issues/36637 is fixed

Given some warning that is generated in an AndroidManifest.xml, if I modify the contents of analysis_options.yaml, the warning is not removed, or added back after modification and saves to the analysis_options.yaml file.

**Comment by srawlins** [comment]
This is fixed now.
