### ISSUE TITLE
Update changelog WRT --disable-service-auth-codes

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36659]
The current changelog says we added `--disable-service-auth-codes`

Isn't it `--enable-service-auth-codes` now?
Is this "the plan" for 2.3?

**Comment by bkonyi** [comment]
That flag is temporary and will be removed shortly.

**Comment by kevmoo** [comment]
Meaning it'll go back to `--disable-service-auth-codes`?

We should be clear about this. There is a pending `2.3.0-dev.0.0` which will have `--enable-service-auth-codes`

**Comment by bkonyi** [comment]
--disable-service-auth-codes is still present, but it temporarily a no-op
as authentication codes are currently disabled by default. That
--enable-service-auth-codes flag is simply for the DevExp folks to test
their tools while I finish making the required changes throughout the repos.

**Comment by kevmoo** [comment]
Okay.

Also: I didn't see it in `dart --help --verbose` – which seems...bad.

**Comment by kevmoo** [comment]
Dropping the priority. This flag should show up in `--help --verbose` though!

**Comment by bkonyi** [comment]
Hm, it looks like we have a bunch of flags missing actually. None of the
flags from runtime/bin/main_options.h seem to be part of the options list...

**Comment by bkonyi** [comment]
Added in [this CL](https://dart-review.googlesource.com/c/sdk/+/100264). I'll have to chat with others on the VM team to figure out if this behavior is expected for flags defined in main_options.h. Most other flags are picked up automatically, which is why I was under the assumption this option was already listed.
