### ISSUE TITLE
Please merge #43eebea5a3715d7c3904cd85a35db5cffaae687e into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36663]
**commit(s) to merge**: 43eebea5a3715d7c3904cd85a35db5cffaae687e

**merge instructions**: merges cleanly in `origin/dev`

**reason**: Workaround for https://github.com/dart-lang/sdk/issues/36644 - prevents crash in Flutter Web development.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @a-siva 

---

**Comment by athomas** [comment]
Merged to dev for 2.3.0-dev.0.1.
