### ISSUE TITLE
fuchsia: transition zx::channel::read() arguments

### ISSUE THREAD

**Issue by mfaltesek** [dart-lang/sdk#36661]
Transitions callers of zx::channel::read and zx::channel::read_etc to a
corrected argument order and temporarily changes the method names during the transition to zx::channel::rea2 and zx::channel::rea2_etc.

specifically, the new argument order can be found here:

https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/zircon/system/ulib/zx/include/lib/zx/channel.h#34

This will be a multi-step operation. I'll find another bug when *rea2* can be rename back to *read*.

**Comment by kulakowski** [comment]
cc @zanderso

**Comment by zanderso** [comment]
Why is this issue filed in this repo? There are no uses of zx::channel in this repo.

**Comment by mfaltesek** [comment]
OK sorry about that. Please close.
