### ISSUE TITLE
Breaking-Change-Request: intent to remove ARMv5 support in Dart VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#36666]
We intend to remove ARMv5 support in the VM, changing lowest supported version to ARMv6.

# Rationale 

ARMv5 does not seem to have any users, is not tested on bots and is not well maintained (most likely broken by this point).

# The expected impact of this change.

Dart VM no longer work on ARMv5 devices.

# Mitigation

None available.

**Comment by aadilmaan** [comment]
Announce email sent. Approvals pending.

@Hixie @matanlurey @dgrove - Please review and approve.

**Comment by dgrove** [comment]
Approved.

**Comment by aadilmaan** [comment]
Waiting on @Hixie and @matanlurey approvals.

**Comment by Hixie** [comment]
cc @eseidelGoogle @cbracken Do we claim to support ARMv5?

**Comment by timsneath** [comment]
As best I can tell, ARMv5 is very dead: as in, unsupported by modern
Android. It dates back to Android 2.3, and if I've read right, is
unsupported in Jelly Bean and onward (which are the platforms we support
<https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on>).
I only see mention in our own docs of ARMv7.

From random internet links:

   - NDK r17 includes the Neural Network API, JNI Shared Memory API,
   Rootless ASAN, and support for UBSAN. It removes support for ARMv5, MIPS,
   and MIPS64. NDK r18 will remove gcc support, instead you must use clang.
   -
      -

      armeabi — ARMv5/6 are old architectures that haven’t been used in
      years, since Android 2.3, and due to limitations of
architecture, PSPDFKit
      rendering was just too slow to be usable. This is why we don’t ship this
      architecture at all. All new devices (Android 4.0 or newer) support at
      least ARMv7 architecture with NEON. Support for armeabi was removed
      within the NDK 17.

**Comment by cbracken** [comment]
This is correct. We don’t claim to support ARMv5; no issues removing this from my side.

**Comment by aadilmaan** [comment]
@Hixie @matanlurey Any additional concerns or questions for this request?

**Comment by Hixie** [comment]
sgtm

**Comment by aadilmaan** [comment]
Waiting on @matanlurey for final approval.

**Comment by dgrove** [comment]
This won't impact @matanlurey. This request is fully approved as of now.

**Comment by matanlurey** [comment]
Feel free to skip me for anything that won't impact the web or google3. LGTM tho.

**Comment by aadilmaan** [comment]
Roger that. Assign back to Vyacheslav.

**Comment by mit-mit** [comment]
@mkustermann was this removed?

**Comment by mkustermann** [comment]
> @mkustermann was this removed?

Here's a CL that removes the remaining code: [cl/122540](https://dart-review.googlesource.com/c/sdk/+/122540)
