### ISSUE TITLE
Figure out whether we need to support simdbc32

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#36665]
Flutter builds ios_debug_arm with simdbc in 32-bit mode (see e.g. this [ios_debug_arm failure](https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/323)).

SIMDBC in 32-bit mode is an unsupported configuration and is not tested on our CI builders.

We should figure out if Flutter actually needs it and start repairing and testing it on our CI builders or we should remove it.

/cc @a-siva @mraleph

**Comment by mraleph** [comment]
I am not sure that SIMDBC32 even works. We should just prohibit building it.

**Comment by rmacnak-google** [comment]
As far as I know, Flutter still supports 32-bit iOS devices.

**Comment by chinmaygarde** [comment]
Correct. That is used for Flutter’s debug mode on old iOS devices that still support iOS 8 (our minimum supported OS version).

**Comment by mkustermann** [comment]
Given that Flutter seems to still support it:

@athomas Should we add simdbc32 to our supported configurations and add a builder for it?

**Comment by dcharkes** [comment]
Also the fuzzer is running SimDBC32.

/cc @aartbik

**Comment by a-siva** [comment]
Consider the recent proposal by @sjindel-google to use the JIT in iOS debug mode, I am closing this issue.
