### ISSUE TITLE
[feature-request] Extract Constants

### ISSUE THREAD

**Issue by Stargator** [dart-lang/sdk#36671]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version: 2.2.0

----

I would like the Analysis Server to improve the extraction of a [constant](https://youtrack.jetbrains.com/issue/WEB-24470).

Extraction for class-level constant, local final variable with/without type annotation.

The analysis server needs to support it first in order to help improve the tooling for Dart developers such as the Dart plugin for IntelliJ.

Some background information as it relates to the JetBrains tools:

> Extract Constant refactoring is the only one that is done by the IDE itself, without using the Analysis Server. It happened this way for historical reasons. I think we should simply remove this refactoring because it is not consistent with its 'Extract variable' server-driven peer.

So while it may seem like support is there, the IDE did it without the aid of the analysis server and would need the analysis-server to be updated to continue to support this feature.

**Comment by keertip** [comment]
Closing as stale.

**Comment by Stargator** [comment]
@keertip I've seen other Extract tickets still active. Is it possible this will be looked at in the future?

**Comment by keertip** [comment]
Maybe. If we do plan to work on it, the issue will be updated.
