### ISSUE TITLE
Memory Leak in JSLinkedHashMap when objects are used as keys

### ISSUE THREAD

**Issue by audioMirror** [dart-lang/sdk#36670]
**Dart SDK Version:**  2.2.0
Although bug looks to be at least 4 years old.

**OS:** Windows (but shouldn't matter)

**dart2js** compilation, running on any browser.

**Behavior:** When using anything other than a String or int as the Key for a default Map<Key,Value> in a javascript build, an internal leak of _Array_ objects occurs in the JSLinkedHashMap if elements are continually being added (and removed) with different actual Key objects.

**Severety:** **Extreme**.  If you use a Map this way, it causes the code to slow and then die from the millions of _Array_ object leaks.

-----------

Here is a snippet of dart-lang 
sdk/sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart

```
class JsLinkedHashMap<K, V> extends MapBase<K, V>
    implements LinkedHashMap<K, V>, InternalMap {
  ...
  var _rest;
  ...
  int internalComputeHashCode(var key) {
    // We force the hash codes to be unsigned 30-bit integers to avoid
    // issues with problematic keys like '__proto__'. Another option
    // would be to throw an exception if the hash code isn't a number.
    return JS('int', '# & 0x3ffffff', key.hashCode);
  }
  ...
  V internalRemove(Object key) {
    var rest = _rest;
    if (rest == null) return null;
    var bucket = _getBucket(rest, key);
    int index = internalFindBucketIndex(bucket, key);
    if (index < 0) return null;
    // Use splice to remove the [cell] element at the index and
    // unlink the cell before returning its value.
    LinkedHashMapCell cell = JS('var', '#.splice(#, 1)[0]', bucket, index);
    _unlinkCell(cell);
    // TODO(kasperl): Consider getting rid of the bucket list when
    // the length reaches zero.
    return JS('', '#', cell.hashMapCellValue);
  }
  ...
}
```

Notice the _**TODO(kasperl)**_ comment.  Not implementing the comment is the cause of the memory leak.

This class has different code paths for String, int, and "everything else" keys.  For object keys, the hashcode becomes a 30-bit integer.  This becomes the key to a bucket that is put into a bare JS Object named __rest_ in the code.

There are therefore up to 2^30 buckets that could be created by this class, if new objects are added as keys.  And, they are never removed!  If a JSLinkedHashMap is used with continually new objects as keys, the application will quickly slow down in garbage-collection panic, and eventually die of out-of-memory.

The buckets themselves leak (not the user data).  The buckets are an Array().  This is easily seen in the Chrome debug Memory console as a huge number of Array leaks.

In a Java implementation, the number of buckets would be dynamic, based on load factor.  This adds complication, and leads to a big-bang of work during rebalancing the bucket entries.  However, it leads to a fast implementation if the number of objects in the Map stabilize.

***********

The Dart implementation can be fixed 

- if the internalComputeHashCode() can use a configurable number of bits, based on expected load.  This changes the API, and may not be suitable (though, if dynamic rebalancing is done, a dynamic number of bits could be used)

OR

- if the delete is called on the bucket 30-bit hashcode, from the __rest_ variable, when the bucket is empty, as per the **_TODO_** comment.  This would require no API changes.  While this takes extra time, removing something from a var JS object is already done for the String and int keys.  This would likely be the preferred fix.  (It probably isn't worth it, but an "empties" list of buckets could be held for re-use.)

**Comment by rakudrama** [comment]
Thanks for the detailed bug report.
I will look into a fix.

In the meantime, one work-around might be to periodically copy the map  (`myMap = Map.from(myMap)`), say every 10000 operations.

**Comment by audioMirror** [comment]
Thanks for the workaround.  I can do that in the critical spots in my application, though hacking everywhere that uses a Map<> without a String key isn't reasonable.  I'll have to settle for a small leak, as opposed to the current app-killing leak.

Any quick fix would be appreciated!  I expect it will only take a few lines to delete the bucket if it is empty.

**Comment by rakudrama** [comment]
Fix being tested: https://dart-review.googlesource.com/c/sdk/+/99885

**Comment by jmesserly** [comment]
FYI, I looked at DDC's implementation and it doesn't appear to have the same bug.

**Comment by dgrove** [comment]
close this?

**Comment by jmesserly** [comment]
ah, yes, dart2js CL landed.
