### ISSUE TITLE
Regression in parsing of variables named `required`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36678]
@keertip found this testing the bleeding edge analyzer on some internal code.  The analyzer currently (as of 9e87c1667783666c6ba14a43ceda1a451b2a7597) rejects code like the following:

```dart
main() {
  var x = [];
  for (final required in x) {}
}
```

We have been discussing the possibility of making `required` a reserved word when NNBD is enabled, however even if we do so, we need it to keep working now, and we will need it to continue to work for opted-out libraries even after NNBD is released. 

This bisects to @danrubel's commit ebdefa3f5fc2d66cdc969f61a1f409f5fdb2c28f.

Dan is on vacation today so I'm looking into doing a short-term fix by reverting ebdefa3f5fc2d66cdc969f61a1f409f5fdb2c28f (as well as the follow-up commits that depend on it).

**Comment by danrubel** [comment]
Looks like this problem has been here all along, but we only just bumped into it when I added "required" as a modifier. It also fails if I use "external" in place of "required".
