### ISSUE TITLE
Please merge d8a0d68bd66b388e4c5f6dc38f4fd940a4cb88bc into dev channel

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36698]
**commit(s) to merge**: d8a0d68bd66b388e4c5f6dc38f4fd940a4cb88bc

**merge instructions**: clean merge

**reason**: We'd like to switch `build_modules` to pass the `--target` flag to clear since it's the only way we'll actually be able to control whether summaries are used separately from the target.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by aadilmaan** [comment]
Merged to Version 2.3.0-dev.0.2
