### ISSUE TITLE
Please merge 1ecedb23416943b13fd3f48a5d398f2cfa6dbee4 into dev channel

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#36699]
**commit(s) to merge**: 1ecedb23416943b13fd3f48a5d398f2cfa6dbee4
**merge instructions**: clean merge

**reason**:
Fixes memory leak in default Map implementation.
This is a longstanding bug. Although longstanding bugs do not fit the cherry-pick rubric, I would like to see this go in because it was recently reported as a severe impact by a customer and is in a core data type (i.e. no simple work-arounds and likely has moderate undiagnosed impact on many apps).

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by aadilmaan** [comment]
Merged to Version 2.3.0-dev.0.2
