### ISSUE TITLE
Where is the dart html XmlSerializer-class now?

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/sdk#36693]
In https://api.dartlang.org/stable/2.2.0/dart-html/XmlSerializer-class.html there was a XmlSerializer and seems its remove from dart:html. Where is the XmlSerializer-class now?

**Comment by vsmenon** [comment]
I still see it in docs (though, note it's deprecated):

https://api.dartlang.org/dev/2.3.0-dev.0.1/dart-html/XmlSerializer-class.html

What makes you think it's gone?
