### ISSUE TITLE
We hope to add python slice-like functionality in the next release

### ISSUE THREAD

**Issue by 2534290808** [dart-lang/sdk#36703]
We hope to add python slice-like functionality in the next release

**Comment by vsmenon** [comment]
It's not clear if this is a request?  :-)

If it is, can you please add an explicit example of what you have in mind?

**Comment by 2534290808** [comment]
Add a Python-like slice operator

**Comment by vsmenon** [comment]
https://github.com/dart-lang/sdk/issues/983
