### ISSUE TITLE
Instantiate a generic

### ISSUE THREAD

**Issue by leonardoprc** [dart-lang/sdk#36708]
I'm implementing a abstraction that consists of the following proposed:

```
class Clients<Model, Param, Serial is new()> {
  ...
  /// setup environment
  configureServer(String url) async {
    this.serial = new Serial();
    ...
  }
...
```

my problem is how can I instantiate a generic . (no bad compare ...) in java made it easy. In Dart, is it possible? How to make ?

**Comment by lrhn** [comment]
In Dart, there is no way to instantiate a type which is not known at compile-time. A type variable cannot be instantiated.

What you may want to do here is to provide a factory function to the object, not a constraint on the type variable:
```dart
class Clients<Model, Param, Serial> {
  final Serial Function() _serialFactory;
  Clients(..., Serial serialFactory(), ...) : _serialFactory = serialFactory;
  ...
  configureServer(String url) async {
    this.serial = _serialFactory();
    ...
  }
  ....
}
```
That way you tell the class how to create objects, you do not rely in there being a specific constructor on the type, which you cannot access anyway.

**Comment by leonardoprc** [comment]
And how is the new Clients() ?

**Comment by leonardoprc** [comment]
What is the syntax ?

**Comment by lrhn** [comment]
To instantiate a `Clients`, you will have to provide the factory function:
```dart
new Clients<MyModel, MyParam, MySerial>(() => new MySerial())
```
There is no way to piggy-back the functionality that allows you to create an instance of a specific type through the type variables, so you have to pass it explicitly.
