### ISSUE TITLE
Dart 2.3 CHANGELOG described the wrong syntax

### ISSUE THREAD

**Issue by Vadaski** [dart-lang/sdk#36705]
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md
I am using dart 2.3 .And I think this CHANGELOG post describes how to handle empty collections but use wrong syntax.
If you know the expression might evaluate to null and you want to treat that as equivalent to zero elements, you can use the null-aware spread `?...`.
Actully is `...?` rather than `?...`

**Comment by vsmenon** [comment]
fyi - @munificent @athomas - do we need to fix anything in the changelog?

**Comment by munificent** [comment]
/me facepalms.

Yes, we do.

https://dart-review.googlesource.com/c/sdk/+/100265

Thanks for noticing this, @Vadaski.

**Comment by Vadaski** [comment]
Glad I could help，also I am very happy to see that dart is getting better to use. BTW I love the Spread! 😍
