### ISSUE TITLE
Deprecated parsing functions in package:analyzer/analyzer.dart don't enable UI-as-code

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36724]
The deprecated parsing functions in `package:analyzer/analyzer.dart` (`parseCompilationUnit`, `parseDartFile`, and `parseDirectives`) don't properly enable parser support for UI-as-code features (`spread-collections` and `control-flow-collections`).  This means that analyzer clients that use these functions may encounter unexpected errors when attempting to analyze code that uses those features.

Note that not all analyzer clients are affected; only clients that use the deprecated APIs.  ~~Also, a few clients pass `suppressErrors: true` to the deprecated APIs; these clients should be unaffected.~~

So far I've found the following affected open source clients:
- `package:intl_translation`
- `package:source_transformer`
- `package:test`
- `package:wing`
- Some code in the ACX gallery
- The angular compiler

When these clients are used in open source, the version of the analyzer they use is obtained from pub (not from the SDK), therefore to get a fix in the hands of users, we will need to publish a new 0.36.x version of `package:analyzer` (likely 0.36.2), and ensure that any clients have pubspec constraints that allow that version of the analyzer to be used.  It will not be necessary to cherry-pick a fix to the `dev` branch of the SDK.

The version of angular on pub is currently on analyzer version 0.35.x, so if we want angular to work with UI-as-code features it will need to be upgraded to 0.36.x.  (That would have been the case even in the absence of this bug, since the last 0.35.x version of the analyzer pre-dates the completion of UI-as-code functionality.)

**Comment by stereotype441** [comment]
FYI @aadilmaan @alorenzen @jakemac53 @natebosch @nshahan @alan-knight @kevmoo

**Comment by kevmoo** [comment]
ALSO @matanlurey

**Comment by stereotype441** [comment]
Correction: clients that pass `suppressErrors: true` to the deprecated APIs are not necessarily safe; it appears that the parser error recovery discards constructs in this case.  For example, parsing `[...x]` yields `[]`.  However, the only open source client I've found that passes `suppressErrors: true` is `package:build_resolvers`, and it only looks at directives for the purpose of finding import dependencies.  So in practice it should still be safe.

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/100278

**Comment by nshahan** [comment]
@stereotype441 What is the status of the analyzer API for getting an `AstNode` from a `ClassElement` in an async context? 

I am relying on `parseCompilationUnit()` to extract documentation comments because `ClassElement.documenationComment` is always null during our build.

**Comment by stereotype441** [comment]
Re-opening as a reminder that we need to release another version of the analyzer.

**Comment by stereotype441** [comment]
Analyzer 0.36.2 has now been published, so the only remaining work to get the fix into users' hands is to update the client packages to allow analyzer versions 0.36.2.  AFAICT the packages that need to be upgraded are:
- `package:intl_translation`
- The angular compiler

Reassigning to @alan-knight for `package:intl_translation` and @alorenzen for the angular compiler.

**Comment by stereotype441** [comment]
@alan-knight just updated `package:intl_translation` to allow 0.36.x.  So the only package that needs to be upgraded now is the angular compiler.

**Comment by stereotype441** [comment]
@alorenzen Is this likely to be addressed by D24?  If not we should change the milestone.

**Comment by alorenzen** [comment]
We already published 6.0.0-alpha, which includes the analyzer ^0.36.2 constraint: https://pub.dev/packages/angular/versions/6.0.0-alpha#-analysis-tab-

Was there more that needed to be done here?

**Comment by stereotype441** [comment]
That sounds sufficient, thanks!
