### ISSUE TITLE
Please merge 34f0bed1893a53eda6ba7c4c1e57c572ec963627 into dev channel

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#36722]
**commit(s) to merge**: 34f0bed1893a53eda6ba7c4c1e57c572ec963627

**reason**: I got the null-aware spread syntax — a syntax I designed — wrong in the CHANGELOG. [Review](https://dart-review.googlesource.com/c/sdk/+/100265)

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by kevmoo** [comment]
![ralph](https://user-images.githubusercontent.com/17034/56610723-faf70980-65c4-11e9-82e1-610f34fbfd78.gif)

**Comment by aadilmaan** [comment]
athom will make this change manually when push our release candidate to stable. Closing this merge request.

**Comment by munificent** [comment]
Thanks!
