### ISSUE TITLE
Improve error message when overriding a getter/field with a normal method

### ISSUE THREAD

**Issue by jimyi** [dart-lang/sdk#36732]
In DartPad:

```
void main() {
}

abstract class Foo {
  String get name;
}

class Bar implements Foo {
  String name() {
    return 'hey';
  }
}
```

The error message says: "Class 'Bar' can't define method 'Foo' and have field 'name.Foo' with the same name."

It took me way more time than I'd like to decipher this because Bar doesn't have a method Foo.

Seems like the error message should have been:
"Class 'Bar' can't define method 'name' and have field 'Foo.name' with the same name."

Looks like this is because the order of two variables are mixed up here:
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/error_verifier.dart#L2535

```
_errorReporter.reportErrorForElement(
            CompileTimeErrorCode.CONFLICTING_METHOD_AND_FIELD, method, [
          _enclosingClass.displayName,
          inherited.enclosingElement.displayName,
          name
        ]);
```

should actually be:

```
_errorReporter.reportErrorForElement(
            CompileTimeErrorCode.CONFLICTING_METHOD_AND_FIELD, method, [
          _enclosingClass.displayName,
          name,
          inherited.enclosingElement.displayName
        ]);
```

**Comment by devoncarew** [comment]
cc @bwilkerson for fyi in terms of error messages we could look to improve

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/100406
