### ISSUE TITLE
Code completion not working after `...` (spread)

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#36733]
No completions from the Analysis Server at the |:

```dart
void main() async {
  final list1 = [1, 2, 3];

  final list2 = [0, ...li|];

  print(list2);
}
```

Issue originally filed at https://youtrack.jetbrains.com/issue/WEB-38571

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/100523

**Comment by scheglov** [comment]
There is a couple of other cases when completion does not work perfectly, even with this CL.
1. No completion for the loop variable in `IfElement`, e.g. no `name` in `[for (var name in names) ^]`.
2. No `else` completion in `IfElement`.

**Comment by stereotype441** [comment]
We decided it's not necessary to try to cherry-pick a fix into Dart 2.3.

**Comment by aadilmaan** [comment]
Did this change land already?

**Comment by scheglov** [comment]
Yes, see the `dart-bot` message just above.

But https://github.com/dart-lang/sdk/issues/36733#issuecomment-486747230 is not addresses yet.

**Comment by stereotype441** [comment]
@scheglov are the remaining issues likely to be addressed in D24?  If not let's change the milestone.

**Comment by scheglov** [comment]
I moved it from D24 to Future.

**Comment by bwilkerson** [comment]
Completion now works after the for loop parts, but still doesn't complete `else` in the following example

```
void f(List<String> names) {
  var x = [if (names.isNotEmpty) names[0] el ];
}
```

**Comment by srawlins** [comment]
As spread completions work now, this issue is closed. I've opened a new issue for the unrelated completion that @bwilkerson brings up in https://github.com/dart-lang/sdk/issues/36733#issuecomment-765808493: https://github.com/dart-lang/sdk/issues/48837
