### ISSUE TITLE
Improve instance calls in JIT optimized code

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#36731]
Related to issue #36428 

@alexmarkov identified that the OneArgCheckInlineCacheStub is hot in JIT optimized code coming from bytecode in a representative Flutter app running on Fuchsia. Improving the stub, or reorganizing instance calls in optimized code would presumably improve fps there.

@rmacnak-google @a-siva

**Comment by alexmarkov** [comment]
It looks like OneArgCheckInlineCache is only used in unoptimized code, and observatory profiler incorrectly  shows that it is called from optimized code. Anyway, we have almost 15% ticks in OneArgCheckInlineCache, so it is worth looking at that stub.

**Comment by rmacnak-google** [comment]
Related: https://dart-review.googlesource.com/c/sdk/+/99705

**Comment by a-siva** [comment]
Can this issue be closed, rmacnak@ has landed some related CLs.

**Comment by a-siva** [comment]
I am going to close this as the original issue of ephemeral apps is not being worked on.
