### ISSUE TITLE
Cache results of DRT_GetFieldForDispatch in the interpreter

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#36735]
Related to issue #36428

@alexmarkov noted that calls to DRT_GetFieldForDispatch from the interpreter are hot in a representative Flutter workload running on Fuchsia. Results of this runtime call could be cached.

@rmacnak-google @a-siva

**Comment by alexmarkov** [comment]
DRT_GetFieldForDispatch appears in the profile as we keep interpreting invoke-field dispatchers even if they are hot. https://dart-review.googlesource.com/c/sdk/+/100633 addresses this problem.

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
