### ISSUE TITLE
Tried to initialize from a previous compilation but the file was not self-contained

### ISSUE THREAD

**Issue by dkwingsmt** [dart-lang/sdk#36740]
```
Compiler message:
Warning: Tried to initialize from a previous compilation, but the file was not self-contained. This might be a bug.
The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///tmp/initialize_from.dillDVMGGY/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
```

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3114685/initialize_from.dill.gz)

Working on Linux,

```
$ dart --version
Dart VM version: 2.2.0 (Unknown timestamp) on "linux_x64"
```

**Comment by devoncarew** [comment]
@kmillikin, I assume this is something reported from the CFE / kernel?

**Comment by jensjoha** [comment]
Thank you for taking the time to report this issue.

The exact same thing happens here as in #36759.
To summarize, everything is fine - the compile that reported this will be slower, but the output will be perfectly fine. It is caused by an updated flutter sdk.

**Comment by devoncarew** [comment]
@jensjoha - should the error message be changed or removed?

**Comment by jensjoha** [comment]
I don't think so. See #36770.
