### ISSUE TITLE
DDC: Implement left-to-right evaluation order for instance method invocations

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#36747]
This is the DDC specific subissue for #36744, which has the details.

Running the test again, it looks like DDC already implements the specified left-to-right evaluation order, in which case this issue could just be closed. I'll leave it open, however, just so we get at least two pairs of eyes on this. ;)

**Comment by leafpetersen** [comment]
Please don't start work on this until we have resolved any breaking change issues.

**Comment by eernstg** [comment]
Closing: The language specification is being changed to specify the current behavior, so no implementation work is needed.
