### ISSUE TITLE
Dart 2.3 CHANGELOG doesn't mention dart2aot or dartaotruntime

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#36758]

**Comment by munificent** [comment]
@kevmoo I know nothing of these things. Do you want to add something or tell me what to add?

**Comment by kevmoo** [comment]
CC @mit-mit this is intentional. We want to release this "silently" for 2.3. Do a bigger announcement w/ D24

**Comment by mit-mit** [comment]
Yup

**Comment by munificent** [comment]
"Look under your seat. There is already an AOT compiler there waiting for you. You get an AOT compiler! You get an AOT compiler! Everyone gets a compiler!"

**Comment by mit-mit** [comment]
This was added to changelog as 'initial support' yesterday. Hope I don't ruin the "under your seat" moment.
