### ISSUE TITLE
why _sendDone in StreamController is private?

### ISSUE THREAD

**Issue by zhengbomo** [dart-lang/sdk#36750]
`Stream.empty()` can send done event for listener
```
Stream.empty().listen((v) {
  print(v);
}, onDone: () {
  print("done");
});

// print done
```

but my custom Stream cannot send done event, there is not any public method for it

```dart
var streamController = StreamController(sync: true);
var obs = Observable(streamController.stream);
var sub1 = obs.listen((v) {
  print("value $v");
}, onDone: () {
  print("done");
}, onError: (error) {
  print("error");
});
streamController.add("1111");
streamController.add("2222");
streamController.addError(null);
sub1.cancel();
streamController.close();
```

why???

**Comment by kevmoo** [comment]
@lrhn ?

**Comment by lrhn** [comment]
The `close` method is the way to send a "done" event.

You can only ever send one "done" event, and you are not allowed to send any other event after a "done" event. When you close the controller, it sends (or enqueues, if the stream is paused or behind on receiving events) the "done" event and prevents you from adding more events using `add` and `addError`.

**Comment by zhengbomo** [comment]
> The `close` method is the way to send a "done" event.
> 
> You can only ever send one "done" event, and you are not allowed to send any other event after a "done" event. When you close the controller, it sends (or enqueues, if the stream is paused or behind on receiving events) the "done" event and prevents you from adding more events using `add` and `addError`.

when I close the controller(`streamController.close()`), but I cannot get the 'done' event on listener
