### ISSUE TITLE
"missing or invalid authentication code"; Observatory SDK 2.3.0-dev.0.3

### ISSUE THREAD

**Issue by rootext** [dart-lang/sdk#36763]
Steps:
Run any script with observatory enabled
Open observatory link from terminal
See error: missing or invalid authentication code

dart --version 
Dart VM version: 2.3.0-dev.0.3 (Tue Apr 23 12:02:59 2019 -0700) on "windows_x64"
Windows 10 64-bit

**Comment by devoncarew** [comment]
@bkonyi - I think this is something you'd addressed recently?

**Comment by bkonyi** [comment]
@rootext do you mind sharing the link you're navigating to? Observatory might just be picky depending on whether or not the URI has a trailing /.

**Comment by rootext** [comment]
@bkonyi,
You are right. It seems it is VSCode issue. It doesn't recognizse last / as part of URI on Ctrl+click in terminal.
Sorry for disturbing

**Comment by bkonyi** [comment]
> @bkonyi,
> You are right. It seems it is VSCode issue. It doesn't recognizse last / as part of URI on Ctrl+click in terminal.
> Sorry for disturbing

No problem! This should worth with or without the trailing /, so I'll add a fix for that.

**Comment by thosakwe** [comment]
Is this fix in the latest version of the Dart SDK? I just installed from homebrew a few hours ago, and am running into the same issue.

**Comment by bkonyi** [comment]
> Is this fix in the latest version of the Dart SDK? I just installed from homebrew a few hours ago, and am running into the same issue.
> 
> To be more specific - I get this error regardless of whether the trailing slash is present.
> 
> EDIT: Never mind, figured it out. The `=` at the end of the URL wasn't getting picked up by my terminal, so I was actually going to the wrong URL.

Glad to hear your figured out your issue! Anyway, this fix probably isn't present in the latest published SDK, but will probably appear in one of the next dev builds.

**Comment by j0m3** [comment]
was the fix to use another dart version or

**Comment by bkonyi** [comment]
> was the fix to use another dart version or

At this point, most definitely. There haven't been any more reports of issues related to authentication codes recently.

**Comment by sgehrman** [comment]
vscode terminal was stripping off the last = character and failing for me.
