### ISSUE TITLE
please cherry pick 14d09498b7830fba62816ec8db3ed9b58601b841

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#36768]
Please cherry pick 14d09498b7830fba62816ec8db3ed9b58601b841 into Dart 2.3. This addresses an issue with the CrOS linting support for Flutter apps.

**Comment by vsmenon** [comment]
@devoncarew - is this primarily for Flutter's version of the Dart SDK?

**Comment by devoncarew** [comment]
yes

**Comment by Hixie** [comment]
what bug is this fixing?

**Comment by devoncarew** [comment]
hey, to update:

- this addresses as issue where the Flutter CrOS linting would traverse into the ios/.symlinks/ directory, and unintentionally create lint warnings for the manifest files for user plugins; see the unit test for more details (https://github.com/dart-lang/sdk/commit/14d09498b7830fba62816ec8db3ed9b58601b841#diff-4923bdcee3ab1dcd724972e95b93bdbeR101)
- this should be cherry-picked into dart 2.3
- it no longer needs to be cherry-picked into flutter 1.5 (as the https://github.com/dart-lang/sdk/commit/1f1592edce7122ff657d9538d58d9cce0cae46e6 from @keertip is not being cherry-picked)

**Comment by aadilmaan** [comment]
This will be picked up in Dart2.3-dev0.4 on dev-branch. We withdrew the request to merge this to flutter.
