### ISSUE TITLE
CFE should preserve label names

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36761]
As of right now, there's no way to retrieve the original label names. Labels are very uncommon in the wild, but this would probably be nice to have for debugging purposes. 

Trivial example:
```
main() {
  A:
  while (true) while (true) break A;
}
```

A is renamed to L0.

**Comment by kmillikin** [comment]
Isn't it better to use the position of the label or labeled statement, plus the source code, to give us the name?

That shouldn't require extra space per label for a cosmetic name and complicated logic for avoiding name clashes or ambiguity in the printed representation.

**Comment by Markzipan** [comment]
That's a good point. I noticed a couple of comments in DDC's source alluding to this feature for kernel - I suppose those are outdated.
