### ISSUE TITLE
Add a way to look up the library object for an instance in DDC apps

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36771]
We currently have the `getType(instance)` utility which gives the class for an instance, but we don't have a way (that I can find) to get back at the library for that instance.

For the vm service protocol we need to provide a `ClassRef` for each `InstanceRef`, which requires an `id` and a `name`. The name we can get, but we don't have a way of constructing a unique id today if we can't get back to the library.

It is probably worth chatting in person before doing anything here, there are some other ways we could potentially solve it as well (add a unique ID for each class etc).

**Comment by natebosch** [comment]
Are the requirements that `id` is globally unique per type? Is it a `String`?

**Comment by jakemac53** [comment]
The `id`s do need to be globally unique, and are just simple `String`s. We do already get ids from chrome though which we might be able to use.

**Comment by Markzipan** [comment]
I believe kernel provides something like this (thing URIs) - we just don't save it in DDC. I haven't checked if they are consistent with Analyzer though.

**Comment by vsmenon** [comment]
@natebosch - do you have an update on this one?

**Comment by natebosch** [comment]
No updates yet - will take a look today.

**Comment by natebosch** [comment]
If we add the extra metadata to track this internally it's about a 2% size penalty within the SDK.

**Comment by vsmenon** [comment]
That's not bad.  Add under `--emit-metadata`?

**Comment by vsmenon** [comment]
Nate - did you decide if we want anything in D24 for this?

**Comment by natebosch** [comment]
~1.2% impact on flutter web gallery. I think we should move forward with the change and release in D24.

I think we should keep this on by default instead of behind `--emit-metadata` for now. It's not clear that all the other stuff that comes along with emit-metadata is going to be as useful as this...

**Comment by vsmenon** [comment]
sgtm
