### ISSUE TITLE
Please merge d03323783a5a5a571916457fcf084d103fce86b3 into dev channel

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36776]
**commit(s) to merge**: d03323783a5a5a571916457fcf084d103fce86b3

**merge instructions**: clean merge

**reason**: This fixes a bug in the analysis server's logic for computing Flutter outlines (#36772).  Without it, if a user has a build method that makes use of UI-as-code, the analysis server will crash trying to build the outline view, causing the outline view to be stale; to recover, the user has to stop using UI-as-code in that build method and restart the analysis server. 

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by aadilmaan** [comment]
@Hixie for approval to land this on Flutter 1.5. Explanation is provided in description.

**Comment by aadilmaan** [comment]
This will be picked up in flutter-1.5 branch (Dart SDK branch for Flutter 1.5) as well as Dart2.3-dev0.4 on dev-branch.
