### ISSUE TITLE
Flaky analyzer behavior around updating files

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36773]
In `build_resolvers` we keep a long lived `AnalysisDriver` and we update it's view of the code by giving it a `MemoryResourceProvider` and [calling `resouceProvider.updateFile`](https://github.com/dart-lang/build/blob/4bfe34db661aa450129aaac07e7128dd6018acc7/build_resolvers/lib/src/build_asset_uri_resolver.dart#L44)

Sometimes this update seems to not take. When we resolve the code afterwards we sometimes see, for instance, that a class where we added a super type does not get reflected.

You can reproduce the failure by running the tests in `build_test` repeatedly. Clone https://github.com/dart-lang/build then use something like:

```
cd build_test
pub upgrade
count=0; while pub run build_runner test; do let count++; echo "$count"; done
```

For me it usually fails in under 10 tries. The [test](https://github.com/dart-lang/build/blob/4bfe34db661aa450129aaac07e7128dd6018acc7/build_test/test/resolve_source_test.dart) changes a file content in each test case and then attempts to resolve it.

**Comment by natebosch** [comment]
cc @stereotype441 @scheglov - we had seen this a while ago and @jakemac53  mentioned that you were unable to find a consistent repro. I attempted to repro this without going through `build_resolvers` and I wasn't able to, so right now running these tests is the best setup we have to see it happen.

**Comment by scheglov** [comment]
I can reproduce it with the provided instructions, although it needs much more iterations - hundreds sometimes. However it looks that the test file itself is updated and picked up. But `package:collection/collection.dart` is not resolved. I added some debug exception.

```
00:01 +40 -1: test/resolve_source_test.dart: should resolveSource of a simple dart file package: dependencies [E]                                                                                                 
  [/_resolve_source/lib/_resolve_source.dart][library example; import 'package:collection/collection.dart'; abstract class Foo implements Equality {}]
  firsImport: unresolved: package:collection/collection.dart
  org-dartlang-app:///test/resolve_source_test.dart 58:13  main.<fn>.<fn>.<fn>
```

I don't know how this package URI is expected to be resolved, I don't see where setup for this test happens.

**Comment by natebosch** [comment]
> I don't know how this package URI is expected to be resolved,

Here's a rough outline:

The asset `asset:collection/lib/collection.dart` should be readable through the [`PackageAssetReader`](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_test/lib/src/package_reader.dart#L23) that we are creating and passing to `runBuilder` [here](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_test/lib/src/resolve_source.dart#L200).

At the point where we [fetch the resolver in the test](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_test/lib/src/resolve_source.dart#L223) it should end up going through [performResolve](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_resolvers/lib/src/build_asset_uri_resolver.dart#L30) which crawls through transitive imports and reads assets through the `BuildStep`.

**Comment by scheglov** [comment]
Hm... I added `print` to `BuildAssetUriResolver.performResolve`, but don't see anything printed while running `resolve_source_test.dart`.

**Comment by natebosch** [comment]
I was able to see print statements from `performResolve` with the following steps:

- Patch in https://github.com/dart-lang/build/pull/2243 to get logger output for this test.
- Add a `dependency_override` in `build_test` pubspec pointing to `path: ../build_resolvers`.
- Add a print statement in `performResolve`
- `pub get`
- `pub run build_runner test`

**Comment by scheglov** [comment]
Thank you, I will do this.

**Comment by scheglov** [comment]
`processAsset` in `performResolve` is asynchronous, but we don't wait it. I think that `resolveAbsolute` is called before the chain of `processAsset` invocations finishes executing.

**Comment by natebosch** [comment]
> `processAsset` in `performResolve` is asynchronous, but we don't wait it. 

The async work is [captured in the `visiting` variable](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_resolvers/lib/src/build_asset_uri_resolver.dart#L40) which we then [return from `performResolve`](https://github.com/dart-lang/build/blob/6baa72a47a81c98e012fd960ca804516ae8f14c1/build_resolvers/lib/src/build_asset_uri_resolver.dart#L77)

It's possible there is a bug in that singular use implementation of `FutureGroup` but I don't _think_ that's what is happening here...

**Comment by scheglov** [comment]
Ah, OK, `_FutureGroup`.

But it still looks like something is wrong with the order of operations.
I added some logging, and "!!!!!!!!!!!!!!!! NoContents" happens after "[processAsset][assetId: collection|lib/collection.dart][0]", but before "[processAsset][assetId: collection|lib/collection.dart][1]". So, the contents has not been read and put into `_cachedAssetContents`.


```
00:01 +40: test/resolve_source_test.dart: (setUpAll)                                                                                                                                                              
[WARNING] runBuilder: [performResolve]
[WARNING] runBuilder: [processAsset][assetId: _resolve_source|lib/_resolve_source.dart][0]
[WARNING] runBuilder: [processAsset][assetId: _resolve_source|lib/_resolve_source.dart][1][contents: 136 bytes.]
[WARNING] runBuilder: [processAsset][assetId: _resolve_source|lib/_resolve_source.dart][2]
[WARNING] runBuilder: [performResolve][unit: library example; import 'package:collection/collection.dart';]
[WARNING] runBuilder: [performResolve][dependencies: {collection|lib/collection.dart}]
[WARNING] runBuilder: [processAsset][assetId: collection|lib/collection.dart][0]
00:01 +40: test/resolve_source_test.dart: should resolveSource of a simple dart file                                                                                                                              
!!!!!!!!!!!!!!!! NoContents: [uri: package:collection/collection.dart][assetId: collection|lib/collection.dart]
[resolveAbsolute][uri: package:collection/collection.dart][cachedId: null]
00:01 +40: test/resolve_source_test.dart: (setUpAll)                                                                                                                                                              
[WARNING] runBuilder: [processAsset][assetId: collection|lib/collection.dart][1][contents: 826 bytes.]
[WARNING] runBuilder: [processAsset][assetId: collection|lib/collection.dart][2]
```

```dart
  Future<void> performResolve(
      BuildStep buildStep, List<AssetId> entryPoints, AnalysisDriver driver) {
    print('[performResolve]');
    // Basic approach is to start at the first file, update it's contents
    // and see if it changed, then walk all files accessed by it.
    var visited = Set<AssetId>();
    var visiting = _FutureGroup();

    void processAsset(AssetId assetId) {
      print('[processAsset][assetId: $assetId][0]');
      visited.add(assetId);

      visiting.add(buildStep.readAsString(assetId).then((contents) {
        print('[processAsset][assetId: $assetId][1][contents: ${contents.length} bytes.]');
        if (_cachedAssetContents[assetId] != contents) {
          print('[processAsset][assetId: $assetId][2]');
          if (_cachedAssetContents.containsKey(assetId)) {
            var path = assetPath(assetId);
            resourceProvider.updateFile(path, contents);
            driver.changeFile(path);
          } else {
            resourceProvider.newFile(assetPath(assetId), contents);
          }
          _cachedAssetContents[assetId] = contents;
          var unit = parseDirectives(contents, suppressErrors: true);
          print('[performResolve][unit: $unit]');
          var dependencies = unit.directives
              .whereType<UriBasedDirective>()
              .where((directive) {
                var uri = Uri.parse(directive.uri.stringValue);
                return !_ignoredSchemes.any(uri.isScheme);
              })
              .map((d) => AssetId.resolve(d.uri.stringValue, from: assetId))
              .where((id) => id != null)
              .toSet();
          print('[performResolve][dependencies: $dependencies]');
          _cachedAssetDependencies[assetId] = dependencies;
        } else {
          print('[processAsset][assetId: $assetId][2-]');
        }
        _cachedAssetDependencies[assetId]
            .where((id) => !visited.contains(id))
            .forEach(processAsset);
      }, onError: (e, st) {
        print(e);
        print(st);
        if (seenAssets.contains(assetId)) return;
        _cachedAssetDependencies.remove(assetId);
        _cachedAssetContents.remove(assetId);
        final path = assetPath(assetId);
        if (resourceProvider.getFile(path).exists) {
          resourceProvider.deleteFile(path);
        }
      }));
    }

    entryPoints.forEach(processAsset);
    return visiting.future;
  }

  /// Attempts to parse [uri] into an [AssetId] and returns it if it is cached.
  ///
  /// Handles 'package:' or 'asset:' URIs, as well as 'file:' URIs that have the
  /// same pattern used by [assetPath].
  ///
  /// Returns null if the Uri cannot be parsed or is not cached.
  AssetId lookupAsset(Uri uri) {
    if (_ignoredSchemes.any(uri.isScheme)) return null;
    if (uri.isScheme('package') || uri.isScheme('asset')) {
      final assetId = AssetId.resolve('$uri');
      if (!_cachedAssetContents.containsKey(assetId)) {
        print('!!!!!!!!!!!!!!!! NoContents: [uri: $uri][assetId: $assetId]');
      }
      return _cachedAssetContents.containsKey(assetId) ? assetId : null;
    }
    if (uri.isScheme('file')) {
      final parts = p.split(uri.path);
      final assetId = AssetId(parts[1], p.posix.joinAll(parts.skip(2)));
      return _cachedAssetContents.containsKey(assetId) ? assetId : null;
    }
    return null;
  }
```

**Comment by natebosch** [comment]
Will the analyzer try to `lookupAsset` as a result of `driver.changeFile(path);`?

**Comment by natebosch** [comment]
I think you might be on to something, if I refactor this I'm no longer able to reproduce the problem. It's either because I fixed a bug in how we handle the async work capturing, or because I'm batching up all the updates to files in the `ResourceProvider` for when they can all be done synchronously.

I'll do a little more validation here, but it's looking plausible that the bug was on our side.

**Comment by scheglov** [comment]
`AnalysisDriver.changeFile()` does very little - remember that the file was changed and flush some cached data. Later analysis is done asynchronously. So, per se `changeFile` will not call `lookupAsset`, but some time later it might be called, if you ask for an analysis result, or has `addFile()` (so subscribed to receiving analysis results for this file continuously).

**Comment by natebosch** [comment]
See https://github.com/dart-lang/build/pull/2244#discussion_r280662920

With `await for` I can still reproduce the bug. If I move the `driver.changeFile` outside of the `await for` then the problem doesn't happen. So I think the problem may indeed be related to doing `chagneFile` as we go before we can synchronously perform all the changes to the resource provider...

**Comment by scheglov** [comment]
`driver.changeFile` itself does not do work, but it schedules work to do asynchronously, by `AnalysisDriverScheduler` that calls `AnalysisDriver.performWork`. The first thing `performWork()` does is to refresh the next changed file. So, if you call `changeFile` before making sure that files that referenced by the changed file are available, this will cause a problem. Once a file reported via `changeFile` has been refreshed, it will not be refreshed until the next time `changeFile` is called for it. If some URI were not resolved because `UriResolver` was not ready, they will stay unresolved.
