### ISSUE TITLE
Putting two class into two files causes error

### ISSUE THREAD

**Issue by WakasaKina** [dart-lang/sdk#36784]
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "windows_x64"

It seems strange that I can't put two class into two files.

I am not quite sure how to describe this, but I can provide a simple example.

I put the example here:

https://github.com/WakasaKina/strange

The first commit is right and two class are in one files.

After I split two class into two files (in the second commit) , it become wrong.

I have no idea why this happens.

**Comment by mraleph** [comment]
Each file is its own library in Dart (unless you are using `part` directives, which are in general discouraged). And `_foo` identifiers are _library private_. Try the following code:

```
// a.dart
class Base {
  _foo() {
    print("Base._foo()");
  }
} 

invokePrivateMethod(o) => o._foo();

// b.dart
import 'a.dart';

class Child extends Base {
  _foo() {
    print("Child._foo()");
  }
}

invokePrivateMethod(o) => o._foo();

// main.dart
import 'a.dart' as a;
import 'b.dart' as b;

void main() {
  a.invokePrivateMethod(Child()); // Would invoke _foo defined in a.dart
  b.invokePrivateMethod(Child()); // Would invoke _foo defined in b.dart
  Child()._foo(); // This would throw noSuchMethod.
}
```

In short this means that you can't override library private methods by subclassing unless you are within the same library.
