### ISSUE TITLE
dbc test build failure:  comparison of integers of different signs

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36796]
fuzzer has not been running for a few days due to build failure

dbc_test.cc -o obj/runtime/vm/compiler/assembler/run_vm_tests.assembler_dbc_test.o
In file included from ../../runtime/vm/compiler/assembler/assembler_dbc_test.cc:8:
In file included from ../../runtime/vm/compiler/assembler/assembler.h:8:
../../runtime/platform/assert.h:110:14: error: comparison of integers of different signs: 'const unsigned int' and 'const signed char' [-Werror,-Wsign-compare]
  if (actual == expected) return;
      ~~~~~~ ^  ~~~~~~~~

**Comment by aartbik** [comment]
Sending out a fix, but @mraleph @dcharkes why is not showing up anywhere else?

**Comment by mraleph** [comment]
Is this 32-bit DBC build? I think we are not building it on any bot.

**Comment by aartbik** [comment]
Yes, the fuzzer build bot does the following (among others):

             "--mode=debug,release",
             "--arch=ia32,simarm,simdbc,simdbc64",

**Comment by dcharkes** [comment]
Tracking 32 bit DBC builds in https://github.com/dart-lang/sdk/issues/36665.
