### ISSUE TITLE
add a fix for `sort_child_properties_last`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36797]
Corresponding to: https://github.com/dart-lang/linter/issues/1542.

**Comment by stereotype441** [comment]
@pq is this likely to be completed for D24?  If not, let's change the milestone.

**Comment by pq** [comment]
Landed yesterday . w/ https://github.com/dart-lang/sdk/commit/fc17a90bedb88dca7f1ce2a2d6c64aee6bf3fd7d . 🎉 

Just forgot to close out.  Thanks for the nudge!
