### ISSUE TITLE
test.py -n outcome does not match bot outcome

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#36806]
SInce the move from status files to status databases, `test.py --mode=x --arch=y` has been useless because we've lost information about expected test outcomes unless there is a bot. For the minority of configurations that have bots, supposedly `test.py -n z` will consult the status database, but I have yet to see it produce the same result as the bots.

For example, at f6f59c997fb0deeb41545c3b9315013ba0fc469f, `test.py -n dartk-linux-debug-x64 language_2` says that 9 tests are failing, but the bot is green.

Because of this, it is necessary to create a large number of try jobs instead of using local testing.

**Comment by athomas** [comment]
`test.py` never looks at the status file database. `test.dart` (a wrapper around `test.py`) does.

Dart Eng Tip #24 has more details (http://go/dartt).

`test.py -n z` just sets the options specified in the named configuration and will still use status files.
