### ISSUE TITLE
Nightly fuzz failure: generic check bounds needs "may throw" flag

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36803]
Only three shards failed last nightly! Green is on the horizon again!

(1) JIT-O3-DebugIA32 - AOT-O3-ReleaseX64: !DIVERGENCE! 1.12:2782870810 (output=true)

(2) JIT-noVFP-ReleaseSIMARM - AOT-ReleaseX64: !DIVERGENCE! 1.12:1687411526 (output=true)

(3) JIT-COMPACTEVERY-O3-DebugIA32 - KBC-MIX-DebugX64: !DIVERGENCE! 1.12:3542603487 (output=false, but empty fail2 string)

**Comment by aartbik** [comment]
(1) Reproduces:

```
< [-83, -45, 4294967296, -46, -9223372036854775807, 27, -9, -30, 2147483648, 4294967295, -27, -62, 1, 58]
---
> [-83, -45, 4294967296, -46, -9223372036854775807, 27, -9]

```

**Comment by aartbik** [comment]
The AOT execution throws a RangeError exception while in X0's run through super. All other modes don't and append the extra elements (before throwing another Invalid argument exception at uriDecode).

**Comment by aartbik** [comment]
This was introduced by https://dart-review.googlesource.com/c/sdk/+/98460

(before GenericCheckBoundInstr could throw, after it couldn't which completely nullifies the new LICM mechanism I introduced; I could have been added as reviewer to this CL :-(

@mkustermann @mraleph

**Comment by mraleph** [comment]
@aartbik oh, that's a spooky bug... I somehow completely missed that `NoThrow` hiding in the class declaration - we need to put some assertions around that. (Because instruction itself still throws - it is just marked as non-throwing by mistake).

**Comment by aartbik** [comment]
It was disappointing though that none of the earlier test (for LICM) triggered this, though. I am working hard getting a very small reproducer so that this is less likely to happen again :-)

**Comment by aartbik** [comment]
(2) and (3) no longer reproduce. Changing the title of this CL to reflect (1).
