### ISSUE TITLE
Dart 2.2.1 release?

### ISSUE THREAD

**Issue by rich-j** [dart-lang/sdk#36804]
It's been almost 3 weeks since the Dart 2.2.1 milestone was closed and 2.2.1-dev.4.2 was released. However, there isn't a final Dart 2.2.1 release yet. When will this happen?

There is an Angular bug fixed in Angular 5.3.0 - which requires Dart 2.2.1-dev.3.0 or greater. Yes, we know that we can use Dart dev channel but would like to stay with final releases.

**Comment by devoncarew** [comment]
I don't believe a `2.2.1` release is planned. You can follow our progress on `2.3.0` (https://github.com/dart-lang/sdk/milestone/72) - that's likely to be the next stable release.

cc @aadilmaan (and @athomas) for the feedback into the process and timing of patches into the stable release.
