### ISSUE TITLE
VM service appears to drop query parameters from HTTP requests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#36819]
Consider a request to the VM service using HTTP instead of WebSockets, such as

```
http://127.0.0.1:8181/m5F0iBiimG4=/getIsolate?isolateId=isolates847450331
```

The VM currently answers
```
{"jsonrpc":"2.0", "error":{"code":-32602,"message":"Invalid params","data":{"request":{"method":"getIsolate","params":{}},"details":"getIsolate expects the 'isolateId' parameter"}},"id":""}
```
Requests that don't need parameters, such as getVM, still work.

Because of this, Observatory fails to load the profiling samples into the timeline view.

@alexmarkov @zanderso

**Comment by bkonyi** [comment]
CL up for review [here](https://dart-review.googlesource.com/c/sdk/+/101021/).
