### ISSUE TITLE
Constant evaluator silently rejects type errors in numeric operations

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36823]
The constant evaluator assumes that its input is statically type correct. If some operation has a type error, it assumes that an error has been reported earlier and silently replaces the constant by a runtime error.

This assumption does not hold in the case of `dynamic` receivers. For instance, when compiling for the VM, this program is silently translated into an explicit runtime error:
```dart
main() {
  const dynamic i = 7;
  const dynamic d = 7.0;

  const ii = i << i;
  const id = i << d;
  const di = d << i;
  const dd = d << d;

  print(const [ii, id, di, dd]);
}
```
When compiling to JavaScript, the program is dynamically type correct and works as expected.

**Comment by kmillikin** [comment]
This affects the new CFE constant evaluator, but it shouldn't be a blocker for enabling it.
