### ISSUE TITLE
Decompiling .dart.snapshot into Dart sourcecode

### ISSUE THREAD

**Issue by Reza-saeedi** [dart-lang/sdk#36826]
According to dart-lang/sdk:

Starting in 1.21, the Dart VM also supports application snapshots, which include all the parsed classes and compiled code generated during a training run of a program.
> $ dart --snapshot=hello.dart.snapshot --snapshot-kind=app-jit hello.dart 
Hello, world!
$ dart hello.dart.snapshot arguments-for-use
Hello, world!

Now,how can i decompile this hello.dart.snapshot file to hello.dart?

**Comment by dgrove** [comment]
Sorry, this isn't something that we're planning to support.
