### ISSUE TITLE
Add "Safe URL" setters for Element classes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#36833]
Various dart:html Element classes have "URL" setters, e.g. `ScriptElement.src=` and `AnchorElement.src=`. These do not perform sanitization, so it is desirable to have alternative "safe" methods, e.g. `ScriptElement.safeSetSrc()`.

This could be accomplished directly in `dart:html`, or in a separate library, as extension methods to the various classes.

**Comment by srawlins** [comment]
CC @sigmundch @vsmenon @matanlurey

**Comment by matanlurey** [comment]
I think a pkg/safehtml with some top-level methods is likely the way to go, for now. Let's chat tho!

**Comment by srawlins** [comment]
Yeah this could be accomplished w/o extension methods with a package that has top-level methods which call `ScriptElement.src=` and simply doesn't include the [linter rule](https://github.com/dart-lang/linter/pull/1528) in its analysis options. The path would be to enable the linter rule in _your_ code, then use pkg/safehtml to set such attributes.

**Comment by matanlurey** [comment]
This lines up well with how https://pub.dartlang.org/packages/pedantic was developed, too.

**Comment by sigmundch** [comment]
One thought is that in a future world where dart:html types are exposed from a package, could we use extension methods to ensure that the default classes don't have the vulnerable methods? Or to hide them?

In other words, I'd love for the future to be a state where the default is the safe API and that you have to go out of your way to use the unsafe one.

**Comment by matanlurey** [comment]
That's a good point. I think it would be worth brainstorming and making public:

* Different options we have to implement this in the _current_ language
* Different options we have to implement in Dart future versions
* Exactly what API surfaces need protection, and to what degree (i.e. dynamic access or not)

**Comment by srawlins** [comment]
Canceling this request for the SDK; working on a separate pub package.
