### ISSUE TITLE
Dart compilers reify `Null` and `bottom` inconsistently

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36832]
Here are a couple examples:

```dart
class A {
  var x = () => throw 'Hi';
  var y = () => null;
}

Null f() => null;
main() {
  A a = new A();
  print(a.x.runtimeType);
  print(a.y.runtimeType);
  a.y = a.x;
  // a.x = f;  Static error in CFE, ok in analyzer
  a.x = (f as dynamic);
  print(a.x.runtimeType);
  print(a.y.runtimeType);
}
```

On VM and Dart2JS, this prints:
```
() => Null
() => Null
() => Null
() => Null
```

On DDC and DDK, this prints:
```
() => bottom
() => Null
() => Null
() => bottom
```

For this example:
```dart
void Function(E) eventHandler<E, F extends E>(void Function(F) handler) {
  return (E e) {
    print(E);
    print(F);
  };
}

void main() {
  void Function(int) f = eventHandler((String s) {});
  f(42);
}
```

On VM, Dart2JS, and DDC:
```
int
Null
``` 

On DDK:
```
int
bottom
```

The simplest answer is to always reify as `Null` regardless of what the CFE or Analyzer passes in.  If so, we can change DDC / DDK accordingly.

**Comment by vsmenon** [comment]
@sigmundch @alexmarkov - do Dart2JS and/or the VM ever reify `bottom`?  Or do they just map it to `Null`?

fyi - @leafpetersen

**Comment by leonsenft** [comment]
> The simplest answer is to always reify as Null regardless of what the CFE or Analyzer passes in. If so, we can change DDC / DDK accordingly.

I think this is necessary as `bottom` [isn't a user visible type](https://github.com/dart-lang/sdk/issues/36777#issuecomment-488810412) (at least not yet), so there's no way to test for it like you can for `Null`.

**Comment by alexmarkov** [comment]
VM maps kernel Bottom type to Null when reading dill files. There is no runtime representation for bottom type in VM.

**Comment by sigmundch** [comment]
dart2js as well, we map bottom to null and there is no reified notion of bottom.

I agree that DDC/DDK should do the same.

**Comment by vsmenon** [comment]
Thanks!  Let's go forward with the DDC/K change to be consistent.
