### ISSUE TITLE
Enable gen_snapshot to be compiled for X64 host and ARM target (SIMARM_X64 build)

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#36839]
This is needed to resolve https://github.com/flutter/flutter/issues/22598 - some operating systems are moving away from 32-bit applications altogether.

**Comment by rishab2113** [comment]
@mraleph can confirm, macOS 10.15 Beta (19A471t) completely breaks AOT build capability

**Comment by a-siva** [comment]
Would like for https://github.com/dart-lang/sdk/issues/37435 to be setup before we close this as done.

**Comment by dgrove** [comment]
#37435 is closed now. What is left here?
