### ISSUE TITLE
Observatory crashes on application with FFI 

### ISSUE THREAD

**Issue by rootext** [dart-lang/sdk#36845]
Steps to reproduce:
1. Load any library `var lib = DynamicLibrary.open('...');`
2. Lookup any function  `lib .lookupFunction<..., ...>('...');`
3. Run application with observatory 
`dart --observe=22222  --pause-isolates-on-exit --pause-isolates-on-unhandled-exceptions app.dart`
4. Open observatory and click cpu profile
5. Application crashes:
```
Observatory listening on http://127.0.0.1:22222/3Wyn9c4cC1o=/
c:\b\s\w\ir\cache\builder\sdk\runtime\vm\object.cc: 6184: error: unreachable code
version=2.3.0-dev.0.3 (Tue Apr 23 12:02:59 2019 -0700) on "windows_x64"
thread=12396, isolate=main(000002688E8261A0)
  pc 0x00007ff6bc1a7a8c fp 0x000000c861cfc080 Dart_IsPrecompiledRuntime
-- End of DumpStackTrace
```

**Comment by adjentz** [comment]
I imagine I ran into a similar problem.

 When debugging via VS Code plugin, 
`dart_hello_def = mylib.lookup<NativeFunction<rust_hello_def>>("goodbye_dart").asFunction();`  throws the exact same error 
> c:\b\s\w\ir\cache\builder\sdk\runtime\vm\object.cc: 6184: error: unreachable code

However, running from the command-line `dart bin/main.dart` yields the expected result.

Running Windows 10, dart-sdk 2.3.1

**Comment by mraleph** [comment]
Could you take a look @dcharkes ?
