### ISSUE TITLE
[ffi] Explore more concise dynamic library binding

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#36854]
Explore if we could use type annotations on dynamic library function signatures (similar to struct fields) to avoid writing two signatures.

Moreover, the `asLibrary` would dynamically link all functions in one go.

```dart
abstract class FooBar extends Library {
  @Int32
  int Truncate64(@Int64 int x);
}

// Part of dart:ffi
class DynamicLibrary {
  // ...
  T asLibrary<T extends Library>();
}
```

Suggested in https://github.com/dart-lang/sdk/issues/34452#issuecomment-489462255

/cc @mraleph @sjindel-google

**Comment by dcharkes** [comment]
> Annotations on typedefs? It's more likely than you think!
> @eernst Erik, where are we with filling in the annotation holes in the grammar?

_Originally posted by @lrhn in https://github.com/dart-lang/sdk/issues/34452#issuecomment-489707783_

@eernstg and @lrhn: Are typedefs inlined in the dart compiler? And if so, are annotations preserved?

```dart
typedef FunctionPointer = @Int32 int TruncationFunction(@Int64 int x);

Pointer<FunctionPointer> myPointer = //...
```

**Comment by lrhn** [comment]
Ah, I meant something like:
```dart
@Something
typedef MyType = int Function(int);
```
Putting annotations into the *value* is probably not going to work. Annoatations in Dart goes on *declarations*, in general, things that have a name or identity. Structural types are not such a thing.

**Comment by dcharkes** [comment]
Now that we have https://pub.dev/packages/ffigen, we might not need this as much as before.

**Comment by dcharkes** [comment]
We will address this by introducing assets:

* https://github.com/dart-lang/sdk/issues/50565
