### ISSUE TITLE
[ffi] Bool type

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#36855]
Should we add a `Bool` type that corresponds to the Dart `bool`?

How should it behave when passed to C?

/cc @sjindel-google @mraleph

**Comment by dcharkes** [comment]
> Since C99, the C language has a bool type which we might want to support in `dart:ffi`.

/cc @mkustermann

**Comment by theochampion** [comment]
Any updates in this?

**Comment by oltrenuovefrontiere** [comment]
There is any update on this? Have you any side-way to support c99 bool return types while we wait for this feature to be implemented?

**Comment by dcharkes** [comment]
Not yet. You can work around it with `Int8` for now. Does that work for you?

**Comment by oltrenuovefrontiere** [comment]
Asking to google, I've found that it could be implemented as a uint8_t in some cases, but for me (gcc on linux) Int8 works like a charm! Thank you for your suggestion and the immediate response!
I hope you're all keeping well and safe

**Comment by alexlapa** [comment]
> How should it behave when passed to C?

Maybe use [Itanium C++ ABI spec](https://itanium-cxx-abi.github.io/cxx-abi/abi.html#pod)? This should be correct for most targets.

> If the base ABI specifies rules for the C99 type _Bool, then bool follows those rules. Otherwise, it has size and alignment 1.
