### ISSUE TITLE
Add a fix/assist for curly_braces_in_flow_control_structures

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36862]
The latest version of [pedantic](https://pub.dev/packages/pedantic#-changelog-tab-) enabled the lint `curly_braces_in_flow_control_structures` which broke DevTools builds because apparently it's violated it in many places.

It'd be nice if there was a quick-fix for this, since it's pretty tedious to fix if you enable later 😄

**Comment by bwilkerson** [comment]
We already have a "Surround with block" assist, but it appears that it only triggers if the statements to be included in the block have been completely selected. (For example, given `if (cond) print('x');` the user has to select `print('x');`.)

@scheglov Do you remember why we decided not to allow partial selections to trigger the assist?

**Comment by DanTup** [comment]
The "Surround with block" assist could help, but being specifically marked as a fix would allow it to show places like the context menu in the Problems list:

<img width="460" alt="Screenshot 2019-05-06 at 7 17 47 pm" src="https://user-images.githubusercontent.com/1078012/57245868-c5760580-7033-11e9-8db2-d66c8465f568.png">

**Comment by bwilkerson** [comment]
Interesting problem. Many of our lints have assists that correspond to them rather than fixes (so that they can be used even when the lint isn't enabled. Looks like we need to think about a way for server to communicate that information with clients so that they can be surfaced in the appropriate places.

@pq Such a mechanism might replace the way we currently associate lints with assists for reporting purposes.

**Comment by DanTup** [comment]
Ah, interesting - I hadn't noticed some didn't appear in the problems view. In VS Code we're actually already fetching all code actions from the server, and it's VS Code that's filtering them to fixes here. If we can identify those that are really "fixes" we could potentially just change the `CodeActionKind` we supply with them to VS Code.

**Comment by pq** [comment]
See also: https://github.com/dart-lang/sdk/issues/37508

**Comment by pq** [comment]
This one is implemented (see: `UseCurlyBraces`).
