### ISSUE TITLE
Dart Aspect-Oriented Programming (AOP)

### ISSUE THREAD

**Issue by furkanvatandas** [dart-lang/sdk#36861]
Is there any development about AOP or still not planned?

**Comment by mraleph** [comment]
No development.

**Comment by matthewadams** [comment]
Dart has so many good things going for it.  Built-in AOP (a la AspectJ) would complete the offering, IMHO.

**Comment by matthewadams** [comment]
There's https://github.com/alibaba-flutter/aspectd, but I feel an official AspectD from google with all features of AspectJ would DEFINITELY give me all of the fundamental tools that I need to put Dart in my toolbelt.
