### ISSUE TITLE
Hint text in pkg/analyzer/lib/src/dart/error/hint_codes.dart reference SDK v2.2.2

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#36879]
I noticed this when I tried to use the ui-as-code features and got the hint in my editor. 

```
The for, if and spread elements were not supported until version 2.2.2, but this code is required to be able to run on earlier versions.
Try updating the SDK constraints.
```

https://github.com/dart-lang/sdk/blob/78e50a5f9b62a3fbf884f7f51a8f655df4a291e5/pkg/analyzer/lib/src/dart/error/hint_codes.dart#L636

Some of these should be updated to v2.3.0. Others like the >>> operator, I'm not sure about.

**Comment by x4080** [comment]
I even doing flutter upgrade again and again to see why this message still appears, but the code still works even with this warning

**Comment by apaatsio** [comment]
This is confusing because according to https://github.com/dart-lang/sdk/releases *version 2.2.2 does not exist*.

I guess those features were planned to be released in 2.2.2 but that release never happened and was replaced by 2.3.0. They just forgot to update the error message to reflect that.

**Comment by apaatsio** [comment]
Actually, [this commit](https://github.com/dart-lang/sdk/commit/495c319574843fa83e9c474961cf51498a0d874a) contains many references to version 2.2.2. I think they should all be fixed.

**Comment by srawlins** [comment]
It now references 2.3.0.
