### ISSUE TITLE
Analyzer complains when static constant check depends on environment

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36873]
When a constant expression contains `fromEnvironment` calls, and some static check in the constant depends on the value of the environment constant, the analyzer seem to always give an error, even when appropriate `-D` options are given on the commandline.

For instance, the program
```dart
class A {
  const A(int x) : assert(x > 5);
}

main() {
  var c = const A(int.fromEnvironment("x"));
  print(c);
}
```
gives the error
```
  error • Evaluation of this constant expression throws an exception at junk/const_assert.dart:7:11 • const_eval_throws_exception
```

The same problem shows for the test case in https://dart-review.googlesource.com/c/sdk/+/101262
```dart
const b = bool.fromEnvironment("foo");

main() {
  const l1 = [1, 2, 3];
  const l2 = [if (b) ...l1];
  print(l2);
}
```
where `b` with its default value of `false` should give no errors.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/102001
