### ISSUE TITLE
VM: Enhance inlining heuristics and avoid relying on statistics of OSR-ed functions

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36880]
When compiling a method for on-stack replacement (OSR), its instruction size and call site count are remembered in a function, and can be later used to make inlining decisions. Flow graph is much smaller when compiling for OSR, as it enters function in the middle, so inliner relies on the incorrect statistics.

However, if this is fixed by adding code

```C++
  if (flow_graph->IsCompiledForOsr()) {
    return;
  }
```

to https://github.com/dart-lang/sdk/blob/cbff5cff2fe4fd252b1a3575d04f161803d4ed7e/runtime/vm/compiler/backend/inliner.cc#L2239

then FluidMotion benchmark slows down:

Before the fix: FluidMotion(RunTime): 32619.731258064512 us.
After the fix: FluidMotion(RunTime): 39410.117823529414 us.

This happens as FluidField.lin_solve is no longer inlined into FluidField.project, resulting in a slower code in the inner loop of lin_solve.

Inlining trace before the fix:
```
Inlining calls in FluidField.project
[... skipped ...]
  => FluidField.lin_solve (deopt count 0)
     Success
       with reason --inlining-callee-call-sites-threshold, code size 63, call sites: 1
```

After the fix:
```
Inlining calls in FluidField.project
[... skipped ...]
  => FluidField.lin_solve (deopt count 0)
     Bailout: heuristics (default) with code size:  124, call sites: 4, inlining depth of callee: 1, const args: 3

```

Disabling OSR with --no-use-osr has the similar effect on this benchmark, although it has a proper warm-up before taking measurements and OSR functions are not used while running banchmark code for measurements.

We need to figure out how to improve inlining heuristics so that inlining would happen even without incorrect statistics from OSR function.

This issue is related to https://github.com/dart-lang/sdk/issues/36429 as with interpreter OSR does not happen before function is compiled in background and inliner doesn't see skewed statistics of OSR-ed function, resulting in a slower execution with interpreter compared to running in default or bytecode JIT modes.

/cc @mraleph @aartbik

**Comment by aartbik** [comment]
With the dust of lazy constant reading settling down, I have started to look into this in more details. I have a few ideas on how to improve this.

**Comment by aartbik** [comment]
Here are numbers on my desktop, just for future comparison.  
```c
         FluidMotion      FluidMotion+no-osr
JIT       36416.98          43414.20
AOT       53631.97             --
```

**Comment by aartbik** [comment]
I have a new heuristics that improves the bookkeeping of inlining statistics for specialized vs. non-specialized cases (based on constant arguments), together with extra constant folding to make the specialization more effective. With this, we get:

```c
         FluidMotion      FluidMotion+no-osr
JIT       36524.01          36088.44
AOT       52267.64             --
```

Golem results and flutter gallery code size measurements to follow!

**Comment by aartbik** [comment]
My pending CL sees a few failures.

```dart
dartk-linux-debug-x64:vm/dart/entrypoints/tearoff_prologue_test/0 broke (Pass -> Crash, expected Pass)
dartk-linux-debug-x64:vm/dart/entrypoints/tearoff_prologue_test/1 broke (Pass -> Crash, expected Pass)
dartk-linux-debug-x64:vm/dart/entrypoints/tearoff_test/0 broke (Pass -> Crash, expected Pass)
dartk-linux-debug-x64:vm/dart/entrypoints/tearoff_test/1 broke (Pass -> Crash, expected Pass)
```

which is due to the following assert:

`     ASSERT(!first_stack_overflow_instr->in_loop());`

I actually don't think the CL is at fault in itself, but it at least exposes something to due the change in inline heuristics. Regardless, this needs to be fixed before proceeding.

@alexmarkov @mkustermann @mraleph

**Comment by aartbik** [comment]
Alex pointed out this issue. The test-specific closure call appears before the check. We probably never inlined that one before, but now we do, causing all the misery.

```dart
B1[function entry]:2 {
      v16 <- Parameter(0)
      v17 <- Parameter(1)
      v18 <- Parameter(2)
} specu repr=tagged
    PushArgument(v6) specu repr=tagged #uses=0 #env-uses=1
    PushArgument(v20) specu repr=tagged #uses=0 #env-uses=1
    PushArgument(v19) specu repr=tagged #uses=0 #env-uses=1
    ClosureCall:32( function=v8<0>, v6, v20, v19) specu can-deopt repr=tagged #uses=0 #env-uses=0
    CheckStackOverflow:8(stack=0, loop=0) specu can-deopt repr=tagged
    DebugStepCheck:10() specu repr=tagged

```

**Comment by aartbik** [comment]
@sjindel-google

**Comment by sjindel-google** [comment]
Could we just move the `ClosureCall` to after the `CheckStackOverflow` and `DebugStepCheck`?

**Comment by sjindel-google** [comment]
gg

**Comment by aartbik** [comment]
@sjindel-google  

Yes, I am okay with that. That seems cleaner. But I did not want to initiate major surgery in this part of the code just for my change in inline heuristics.

**Comment by aartbik** [comment]
On to the next issue exposed by this inlinining heuristic change. The test refactoring_test.dart in pkg/analysis_server/test/edit/ crashes as:

`object.h: 6143: error: Handle check failed: saw Code([Optimized] new Name) expected Instance`


In debug mode, the flow graph checker may actually give a clue on potential trouble (or perhaps something else):

`flow_graph_checker.cc: 314: error: expected: def->next() != nullptr`

This happens right after the newly introduced constant propagation, so definitely related to the pending CL!

**Comment by aartbik** [comment]
The flow graph checker was actually really helpful! This was another omission of failing to clean up the environment after removing a push argument. Fixing this removes the checker failure and the crash reported in the test!
