### ISSUE TITLE
flutter analyze perf regression

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#36881]
https://github.com/dart-lang/sdk/commit/8d1ed856d258beb0aa3aa164044f235a131c7994 caused a 12.002% perf regression on the flutter-analyze benchmark on our perf CI system. This is due to work refactoring the summary file format in order to allow us to address corner cases in analyzer dart language support.

We think we can re-coup this perf regression by adding a cli flag to the analysis server which disables some work not required by a tool just doing analysis (disabling things like indexing and other items). We'll then update the implementation of `flutter analyze` to pass that flag into the analysis server.

cc @stereotype441 @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/103182
