### ISSUE TITLE
dartanalyzer --help uses confusing double negatives

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36884]
`dartanalyzer --help` prints:

```
    --[no-]declaration-casts    Disable declaration casts in strong mode (https://goo.gl/cTLz40)
                                This option is now ignored and will be removed in a future release.

    --[no-]implicit-casts       Disable implicit casts in strong mode (https://goo.gl/cTLz40).
    --no-implicit-dynamic       Disable implicit dynamic (https://goo.gl/m0UgXD)
```

I don't know how to interpret that: to disable implicit casts, do I use `--implicit-casts` or `--no-implicit-casts`? (Or is it like "flammable" and "inflammable" where they both mean the same thing?) It's even more confusing that `--no-implicit-dynamic` does *not* use `[no-]` but words its description the same as the others.

I recommend making `--no-declaration-casts` and `--no-implicit-casts` use the same style as `--no-implicit-dynamic` and remove the square brackets around `no`.

(dartanalyzer version 2.3.0-dev.0.5 on Linux x64.)

**Comment by srawlins** [comment]
`dartanalyzer` is now deprecated, in favor of `dart analyze`, so this help text will be removed instead of tidied up. Please refer to https://dart.dev/guides/language/analysis-options for better documentation on those options.
