### ISSUE TITLE
Analyzer cache retained between buildbot runs, leading to confusing bot results

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36888]
On May 4, the trybot flutter-analyze-try reported a mysterious set of warnings for @bwilkerson's [CL 101380](https://dart-review.googlesource.com/c/sdk/+/101380):

```
warning • This function has a return type of 'String', but doesn't end with a return statement • dev/tools/gen_keycodes/lib/key_data.dart:152:47 • missing_return
warning • This function has a return type of 'String', but doesn't end with a return statement • dev/tools/gen_keycodes/lib/key_data.dart:181:44 • missing_return
warning • This function has a return type of 'String', but doesn't end with a return statement • dev/tools/gen_keycodes/lib/key_data.dart:196:44 • missing_return
warning • This function has a return type of 'Future<bool>', but doesn't end with a return statement • examples/flutter_gallery/lib/demo/material/leave_behind_demo.dart:230:50 • missing_return
warning • This function has a return type of '_NavigationBarTransition', but doesn't end with a return statement • packages/flutter/lib/src/cupertino/nav_bar.dart:2181:66 • missing_return
warning • This function has a return type of 'FutureOr<T>', but doesn't end with a return statement • packages/flutter_driver/lib/src/driver/driver.dart:103:46 • missing_return
warning • This function has a return type of 'Future<ByteData>', but doesn't end with a return statement • packages/flutter_test/lib/src/binding.dart:756:62 • missing_return
warning • This function has a return type of 'FutureOr<List<void>>', but doesn't end with a return statement • packages/flutter_tools/lib/src/resident_runner.dart:185:79 • missing_return
warning • This function has a return type of 'Future<Map<String, dynamic>>', but doesn't end with a return statement • packages/flutter_tools/lib/src/run_hot.dart:443:13 • missing_return
```

What was mysterious about these warnings is that they were new; they did not appear on the main flutter-analyze buildbot.  Yet nothing in CL 101380 should have affected the analyzer's generation of missing_return warnings.

The cause was as follows: the analyzer currently has a bug (#28233) preventing it from detecting missing_return errors in certain circumstances, and the Flutter codebase has code that would fail analysis if that bug were fixed.  @srawlins is working on a CL to fix that bug: [CL 100301](https://dart-review.googlesource.com/c/sdk/+/100301/4).  The trybot happened to run CL 100301 just before CL 101380, and when it did so, it correctly detected the bad flutter code.  The analyzer cache persists between bot runs, so when the trybot went on to run CL 101380, it delivered the analysis results from the cache rather than doing a fresh analysis; this caused the warnings to incorrectly show up in CL 101380.

In principle this situation could apply to any CL, and it could apply to either trybot runs or post-commit bot runs.  It could cause unexplained errors/warnings (as it did in this case), or it could cause errors/warnings to fail to show up when they should.  I'm classifying as P1 because it could potentially cause the bots to miss a serious analyzer regression, and because we regularly see odd behavior from analyzer bots that we suspect is due to stale data in the analyzer cache.

**Comment by stereotype441** [comment]
Possible solutions we've discussed in the past:
1. Modify the analyzer so that it uses a hash of its own source code as a salt when creating analysis cache keys; this would ensure that any change to the analyzer would fully invalidate the cache.  Note that the analyzer currently has a salt it uses for this purpose, but it must be incremented manually, and we generally only think to increment it when modifying the summary format.  Unfortunately it's a nontrivial task to include a hash of the full source code in the salt, due to the chicken-and-egg problem that we can't include a hash of the analyzer source code in the analyzer source code itself.
2. Modify the bots so that they erase the analysis cache directory between runs.  This would be relatively simple to do, but would be slightly riskier, since it would allow for the remote possibility that if we forget to increment the salt between major releases, a user might see stale analysis data after upgrading their SDK.  The risk is mostly theoretical--in practice the code for the SDK itself tends to change from one release to the next, which should be sufficent to invalidate any entries in the analysis cache.

**Comment by stereotype441** [comment]
@athomas how much effort would it be to have the trybots erase the analyzer cache between runs?

**Comment by bwilkerson** [comment]
> 2. ...  it would allow for the remote possibility that if we forget to increment the salt between major releases, a user might see stale analysis data after upgrading their SDK.

We could remove (or at least lessen) the risk by always manually incrementing the salt as part of shipping a release, whether we think we need to or not.

That would have the unfortunate disadvantage that cached data could never be used across releases, even if there is no other reason for discarding it.

And as you said, it isn't clear that this is a big enough risk to worry about it.

**Comment by athomas** [comment]
I'm assuming that we're referring to the ~/.dartServer directory.

That directory can be moved to a location that is always deleted between runs using this environment variable:
ANALYZER_STATE_LOCATION_OVERRIDE

So I will ensure that on CI this variable is always set to a tmp directory that is cleaned out between runs. That shouldn't be too hard.

**Comment by athomas** [comment]
So I will fix this: https://github.com/dart-lang/sdk/issues/35161
