### ISSUE TITLE
dart.exe may be getting flagged as malware

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36897]
From a user report - I don't know how to repro this:

https://gitter.im/dart-lang/sdk?at=5cd33a035a887e1cd9b42289

> I just upgraded my flutter and dart sdk and my antivirus sees dart.exe as a threat, infected with Win64:Malware-gen. Is that a common issue? How can I ensure the file's integrity?

cc @whesse @athomas

**Comment by athomas** [comment]
For Dart SDK zips we also publish hashes that could be used to verify the integrity (chocolatey does that automatically, AFAIK) of the zip, and then the file in the zip could be compared to the file on disk (or simply replaced).

It sounds like the user may have gotten their Dart SDK via the Flutter SDK, in that case I'm not sure how to answer the file integrity question.

It also seems that Win64:Malware-gen could also just be a false positive and needs to be reported to the antivirus vendor as such.

**Comment by whesse** [comment]
This may be a false positive from your antivirus scanner's heuristics.  Most antivirus programs include instructions for submitting a possible false positive to them, so they can check it out and make their programs stop triggering on it.  The downloads from the official dart and flutter websites should be guaranteed to be safe, since they are transferred with https:

**Comment by natebosch** [comment]
We may need to loop some flutter folks in - sounds like this is happening with `dart.exe` in the flutter SDK

**Comment by timbaert** [comment]
I just downloaded flutter version v1.5.4-hotfix.2-stable and I encounter the same problem. In my case, AVG AntiVirus Free has put the file in quarantine due to Win64:Malware-gen.

**Comment by Eptagone** [comment]
I have the same problem with Kaspersky. it says dart-sdk is a Trojan.

**Comment by ElieSol** [comment]
Hello, having the same problem here after trying to update dart, any updates on this ?

**Comment by mraleph** [comment]
@ElieSol report these bugs to your antivirus vendor.

**Comment by ElieSol** [comment]
@mraleph  will do that thanks, in the meantime I have uninstalled then reinstalled flutter and managed to got rid of the problem

**Comment by cedvdb** [comment]
I had some issue lately where dart.exe has reached quarantaine. To be fair its behavior was not right: it created a fork bomb inside git and I had to reinstall both git and flutter twice. That happened when running `flutter pub get --offline` when in airplane mode. After that command, running any git command in any dir would output `BUG: FORK BOMB`. Flutter / dart should not be able to totally screw other programs.

![image](https://user-images.githubusercontent.com/22280985/184111393-6f2bad44-afb4-41ff-adfb-5def2eb210f0.png)

**Comment by ahmvdshafiq** [comment]
> I had some issue lately where dart.exe has reached quarantaine. Its behavior was not right: it created a fork bomb inside git and I had to reinstall both git and flutter twice after restarting my system. That happened when running `flutter pub get --offline` when in airplane mode. After that command, running any git command in any dir would output `BUG: FORK BOMB` (even after restart). Flutter / dart should not be able to totally screw other programs, git in this instance.
> 
> ![image](https://user-images.githubusercontent.com/22280985/184111393-6f2bad44-afb4-41ff-adfb-5def2eb210f0.png)
> 
> Today dart.exe has just disappeared out of nowhere, I assume it's the antivirus deleting it somehow. Given the above it's a bit though to whitelist flutter / dart.
> 
> It seems like I'm the only person that has experienced this as I found nothing related.

do you fou
nd the solution?

**Comment by cedvdb** [comment]
@ahmvdshafiq as I said I had to reinstall git and flutter
