### ISSUE TITLE
Set.unmodifiable()

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#36901]
Both `List` and `Map` have `unmodifiable()` constructors, which are very handy for copying collections that are provided as arguments and making them unmodifiable in a single step. But `Set`, despite being a `dart:core` collection type like `List` and `Map`, has no such constructor. It would be very cool if it did.

**Comment by gagoman** [comment]
I have written a patch (https://dart-review.googlesource.com/c/sdk/+/164103/2) but I am not sure what is a best way to proceed with tests: there are located in different folders and repositories. I'd be glad to update the patch if you'll guide me through process (e.g. how I submit changes to both sdk and c019 at the same time). Thank you.

**Comment by lrhn** [comment]
You won't need to add tests to co19, there is a different, independent team doing those tests.

Test for the SDK repository would go into tests/corelib and tests/corelib_2 (for non-null-safety tests).

The approach seems sound, with only some style nitpicks :)

**Comment by gagoman** [comment]
Ok, got it. What will you suggest? I can port rest of unmodifiable set view tests from https://github.com/dart-lang/collection. Could you also post nitpicks (in CL?) so that I can fix them? Thanks.
