### ISSUE TITLE
Compile UI as code features away before constant evaluation

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36910]
Currently during constant evaluation we eliminate UI as code features (spreads and control-flow in collections) by compiling them into simpler constructs.  The original syntax is a Fasta-internal implementation detail that is not part of the Kernel language.  That is, the AST nodes are not in package:kernel and the Kernel transformation APIs (e.g., the Visitor and Transformer classes) do not know about them.  Furthermore, this syntax is impossible to serialize and deserialize.

For the Flutter Widget inspector, we would like to perform a transformation before constant evaluation and that requires compiling these features away first so the Kernel transformation APIs work.  (See #36640.)

For separate compilation, we would like to serialize constant initializer expressions in outlines, without performing constant evaluation and that requires compiling these features away first so that serialization works.  (See #36635.)

**Comment by askeksa-google** [comment]
CL for fix is here: https://dart-review.googlesource.com/c/sdk/+/103123
