### ISSUE TITLE
VM pauses on handled exceptions with --observe

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36911]
In VS Code it's possible to enable the VM service for the analysis server to help debug things. We currently use `--observe=x` for this (though I've changed it to just `--enable-vm-service=x` now since that's more appropriate).

[A user noticed that the server stopped responding](https://github.com/Dart-Code/Dart-Code/issues/1692) and we found in the logs:

> vm-service: isolate (1009032850) 'main' has no debugger attached and is paused due to exception.  Connect to Observatory at http://127.0.0.1:8123/yW5fS7-lu7Y=/ to debug.

I'm able to reproduce this by forcing the server to throw an error in the same location. However, the exception is in code that has a catch block around it (actually, it uses `on`, but I changed it to just catch everything while debugging to make it clearer).

Here's the top frame where the exception is thrown, and you can see in the console when I ran `set` that only *uhandled* exceptions should pause.

![Screenshot 2019-05-09 at 3 15 06 pm](https://user-images.githubusercontent.com/1078012/57460962-06f1f500-726e-11e9-9e59-eff0e5c9d73f.png)

Further up the stack is this frame, which is calling the function inside a `try/catch`:

![Screenshot 2019-05-09 at 3 18 01 pm](https://user-images.githubusercontent.com/1078012/57461011-212bd300-726e-11e9-8134-6821127b3fb9.png)

I've reviewed each frame between them, and although there are more async boundaries/awaits, the code is not "run in the background", the responses to the code throwing are all being awaited within the try/catch.

I've tried, but been unable to reproduce this in a smaller sample (I can reliably reproduce it using the server though). Is there a way I can get more information that will help understand what's happening?

@a-siva

**Comment by a-siva** [comment]
--observe turns on --pause-isolates-on-unhandled-exceptions and the behavior you are describing above matches what should happen when --pause-isolates-on-unhandled-exceptions is turned on.

**Comment by DanTup** [comment]
@a-siva but these exceptions are not unhandled, they are handled in a try/catch. If you don't use `--observe` then the exceptions do not crash anything, they run the code in the `catch` block (which is empty) and continue in the `while` loop.

**Comment by DanTup** [comment]
I see this in the Analysis Server tests too. If I run them with breaking only on uncaught exceptions (for example `analysis_server/test/lsp/test_all.dart`) it breaks on all tests that throw exceptions, even though they're caught. For example:

<img width="1553" alt="Screenshot 2019-05-13 at 1 03 32 pm" src="https://user-images.githubusercontent.com/1078012/57620033-8853cb00-757f-11e9-9f9d-5b72d8de0b3f.png">

If I walk up the stack, I eventually get to this:

<img width="682" alt="Screenshot 2019-05-13 at 1 04 59 pm" src="https://user-images.githubusercontent.com/1078012/57620118-bdf8b400-757f-11e9-80ee-40b81eda2336.png">

The highlighted line is misleading, the error is actually occurring on line 386 where we await this the future created on line 373, but we expect that it throws. The test framework handles the exception (and then passes the test), so I wouldn't expect to break here unless I was breaking on handled exceptions.

FWIW, I can't reproduce this outside of the server code. Even if I make a simple analysis server test that just throws directly in the `expectLater` callback it doesn't repro. I haven't figured out why that is yet though!

**Comment by DanTup** [comment]
Actually, I can repro. Here's a small sample that just uses `package:test`:

```dart
import 'package:test/test.dart';

main() {
  test('foo', () async {
    final foo = () async {
      await Future.delayed(const Duration(seconds: 1));
      throw 'ERR';
    }();
    await expectLater(foo, throwsA(TypeMatcher<String>()));
  });
}
```

My understanding is that there is no *unhandled* exception here. The test framework handles the expected exception and passes the test. But if you run this with break-on-*unhandled*-exceptions it still pauses on the `throw`.

**Comment by a-siva** [comment]
Ok, I guess what you are stating is that --pause-on-unhandled-exceptions is behaving like --pause-on-exceptions.

**Comment by DanTup** [comment]
Yep, correct - though possibly only in some circumstances (maybe when async?).

**Comment by DanTup** [comment]
This may be unrelated to the `--observe` flag and just a more general issue, as a Flutter user is seeing it without any special flags (we've set exeptionPauseMode to Unhandled and it's breaking on an exception right inside a try/catch - also async):

https://github.com/flutter/flutter/issues/33427

**Comment by ZichangG** [comment]
VM will checks try catch block to determine an exception is handled or unhandled. The expectLater() is basically using Future.then() machinery instead of try catch block. So the exception thrown was considered as unhandled exception. The workaround is to use try catch block.

From our perspective, it is hard to trace Future objects and registered callbacks. We are still going to use trycatch block as criteria.

**Comment by emakar** [comment]
This is still happening with try-catch as well - https://github.com/flutter/flutter/issues/33427 (closed with no action)

**Comment by DanTup** [comment]
@emakar can you provide a code sample that triggers the issue you're seeing? (and include which version of the SDK you're seeing it on)
