### ISSUE TITLE
runtime/tests/vm/dart/spawn_shutdown_test.dart is broken

### ISSUE THREAD

**Issue by mdempsky** [dart-lang/sdk#36917]
If I edit spawn_shutdown_test.dart with

     trySpawn(Function f, Object o) async {
       try {
         await Isolate.spawn(f, o);
       } catch (e) {
    +    print(e);
         // Isolate spawning may fail if the program is ending.
         assert(e is IsolateSpawnException);
       }
     }

then I see that it prints

    type '(SendPort) => void' is not a subtype of type '(Object) => void'

50 times and then exits. Instrumenting the Dart VM itself, I see that Isolate_spawnFunction in runtime/lib/isolate.cc is never actually called.

It seems like this test isn't actually currently testing what it means to test.

/cc @zanderso

**Comment by zanderso** [comment]
Looks like the test was not properly updated in the Dart 1 to Dart 2 migration. @a-siva

**Comment by mdempsky** [comment]
I thought to try making the test less brittle by checking that workers are actually spawning by creating a RawReceivePort in the main function, but this doesn't seem to work:

    diff --git a/runtime/tests/vm/dart/spawn_shutdown_test.dart b/runtime/tests/vm/dart/spawn_shutdown_test.dart
    index 235a0d8615..5f5825677a 100644
    --- a/runtime/tests/vm/dart/spawn_shutdown_test.dart
    +++ b/runtime/tests/vm/dart/spawn_shutdown_test.dart
    @@ -14,9 +14,9 @@ import 'dart:isolate';
     // workers in a staggered fashion in an attempt to see a variety of
     // isolate states at the time that this program terminates.
     
    -trySpawn(Function f, Object o) async {
    +trySpawn(SendPort parentObject) async {
       try {
    -    await Isolate.spawn(f, o);
    +    await Isolate.spawn(worker, parentObject);
       } catch (e) {
         // Isolate spawning may fail if the program is ending.
         assert(e is IsolateSpawnException);
    @@ -37,7 +37,7 @@ void worker(SendPort parentPort) {
       }
     
       // Spawn a child worker.
    -  trySpawn(worker, port.sendPort);
    +  trySpawn(port.sendPort);
     }
     
     void main() {
    @@ -45,16 +45,25 @@ void main() {
       const delay = const Duration(milliseconds: (1000 ~/ numWorkers));
       const exitDelay = const Duration(seconds: 2);
     
    +  var spawned = 0;
    +  var port = new RawReceivePort();
    +  port.handler = (_) {
    +    print('Spawned another worker');
    +    spawned++;
    +  };
    +
       // Take about a second to spin up our workers in a staggered
       // fashion. We want to maximize the chance that they will be in a
       // variety of states when the vm shuts down.
       print('Starting ${numWorkers} workers...');
       for (int i = 0; i < numWorkers; i++) {
    -    trySpawn(worker, null);
    +    trySpawn(port.sendPort);
         sleep(delay);
       }
     
       // Let them spin for a bit before terminating the program.
       print('Waiting for ${exitDelay} before exit...');
       sleep(exitDelay);
    +  port.close();
    +  print('Spawned ${spawned} workers');
     }

As output I get:

    Starting 50 workers...
    Waiting for 0:00:02.000000 before exit...
    Spawned 0 workers

Is there some subtlety to how port communication works that I'm overlooking?

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/102101
