### ISSUE TITLE
Showing bug in flutter app

### ISSUE THREAD

**Issue by fazil-augr** [dart-lang/sdk#36921]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer
* Common Front End (CFE) and kernel
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.10.1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.10.1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+1/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+3/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+4/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/faziltm/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.0.4/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Downloading ios tools...                                           43.3s
Downloading ios-profile tools...                                   41.5s
Running Gradle task 'assembleDebug'...                                  
Downloading ios-release tools...                                   34.2s
                                                                                Compiler message:                                                               Warning: Tried to initialize from a previous compilation (build/app.dill), but the file was not self-contained. This might be a bug.
                                                                                The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///var/folders/tq/frr_czc97x3454bnnk6x2gv00000gn/T/initialize_from.dill7uPMdL/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.                          
Note: Some input files use or override a deprecated API.                        Note: Recompile with -Xlint:deprecation for details.     `

**Comment by mit-mit** [comment]
This looks like a Flutter bug? Can you kindly file this in the Flutter tracker?
