### ISSUE TITLE
Not getting lints from the analysis server with --lsp

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36931]
I think this started after I upgrade to 2.3.0

I'm not getting any lints from the analysis server. I run with `--lsp`. After fixing a bug to let `/contexts` load on the diagnostics server, I can see that it is reading the correct `analysis_options.yaml` file, but there are no lints listed. If I go back to `dart_language_server` which wraps the analysis server without `--lsp` I get lints and I can see them listed on `/contexts`.

cc @bwilkerson @DanTup

**Comment by DanTup** [comment]
Good catch - it didn't occur to me that lints weren't just the same as errors/warnings (but the rules need registering).

Fix is in https://dart-review.googlesource.com/c/sdk/+/102340
