### ISSUE TITLE
 build_web_compilers:ddc on xxx.dartdevc.module (cached): Error compiling dartdevc module:xxx.ddc.js

### ISSUE THREAD

**Issue by Unfreeze-kk** [dart-lang/sdk#36947]
run ```flutter packages pub global run webdev serve ```

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/Users/dengkangkang/dev/flutter/bin/cache/dart-sdk --dart-sdk-summary=/Users/dengkangkang/dev/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.sum --modules=amd -o packages/flutter_app/page/base/CommonPageState.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/meta/meta.dartdevc.linked.sum -s packages/flutter_web_ui/ui.dartdevc.linked.sum -s packages/flutter_web/io.dartdevc.linked.sum -s packages/typed_data/typed_buffers.dartdevc.linked.sum -s packages/flutter_web/src/foundation/assertions.dartdevc.linked.sum -s packages/flutter_web/foundation.dartdevc.linked.sum -s packages/collection/src/utils.dartdevc.linked.sum -s packages/collection/src/algorithms.dartdevc.linked.sum -s packages/collection/src/canonicalized_map.dartdevc.linked.sum -s packages/collection/src/comparators.dartdevc.linked.sum -s packages/collection/src/iterable_zip.dartdevc.linked.sum -s packages/collection/src/priority_queue.dartdevc.linked.sum -s packages/collection/collection.dartdevc.linked.sum -s packages/flutter_web/src/services/clipboard.dartdevc.linked.sum -s packages/flutter_web/services.dartdevc.linked.sum -s packages/flutter_web/src/scheduler/binding.dartdevc.linked.sum -s packages/flutter_web/scheduler.dartdevc.linked.sum -s packages/flutter_web/src/gestures/arena.dartdevc.linked.sum -s packages/flutter_web/gestures.dartdevc.linked.sum -s packages/flutter_web/src/physics/clamped_simulation.dartdevc.linked.sum -s packages/flutter_web/physics.dartdevc.linked.sum -s packages/flutter_web/src/animation/animation.dartdevc.linked.sum -s packages/vector_math/hash.dartdevc.linked.sum -s packages/vector_math/vector_math_64.dartdevc.linked.sum -s packages/flutter_web/animation.dartdevc.linked.sum -s packages/flutter_web/src/cupertino/activity_indicator.dartdevc.linked.sum -s packages/flutter_web/cupertino.dartdevc.linked.sum -s packages/flutter_web/material.dartdevc.linked.sum -s packages/flutter_app/weight/Tool.dartdevc.linked.sum -s packages/rxdart/src/samplers/buffer_strategy.dartdevc.linked.sum -s packages/rxdart/samplers.dartdevc.linked.sum -s packages/rxdart/src/streams/amb.dartdevc.linked.sum -s packages/rxdart/streams.dartdevc.linked.sum -s packages/rxdart/src/transformers/buffer.dartdevc.linked.sum -s packages/rxdart/transformers.dartdevc.linked.sum -s packages/rxdart/futures.dartdevc.linked.sum -s packages/flutter_app/bloc/Bloc.dartdevc.linked.sum -s packages/flutter_app/CommonRoute.dartdevc.linked.sum --url-mapping=package:flutter_app/page/base/CommonPageState.dart,packages/flutter_app/page/base/CommonPageState.dart package:flutter_app/page/base/CommonPageState.dart
    dart --version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64"
```

**Comment by vsmenon** [comment]
Was there a stack trace?  What version of build_web_compilers?  Thanks!

**Comment by Unfreeze-kk** [comment]
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:4247:7)
#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:707:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:20898:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:2754:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:316:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:219:43)
#8      List.forEach (dart:core-patch/growable_array.dart:278:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:219:18)
#10     new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:92:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:135:22)
#12     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#13     compile (package:dev_compiler/src/compiler/shared_command.dart:405:18)
#14     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#20     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#26     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

**Comment by Unfreeze-kk** [comment]
```
dev_dependencies:
#  flutter_web_test: any

  build_runner: ^1.2.2
  build_web_compilers: ^1.1.0

  test: ^1.3.4
```

**Comment by vsmenon** [comment]
Thanks!  Have you tried the latest build_web_compilers?  It looks like you're on an older stack.

**Comment by Unfreeze-kk** [comment]
It work when I change  to the latest version.Thanks~
