### ISSUE TITLE
Failed to connect to the VM observatory service: java.io.IOException: Failed to connect: ws://localhost:5858/ws Caused by: de.roderick.weberknecht.WebSocketException: connection failed: unknown status code 403

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#36945]
After upgrading to Dart 2.3, attaching to a running isolate from IntelliJ stopped working.

When connecting to a running isolate from IntelliJ (using the "Dart Remote Debug" run configuration), I get the following error in the IntelliJ console:

```
Failed to connect to the VM observatory service: java.io.IOException: Failed to connect: ws://localhost:5858/ws
Caused by: de.roderick.weberknecht.WebSocketException: connection failed: unknown status code 403
```

Here's the setup. This worked okay before:

<img width="1183" alt="Screen Shot 2019-05-12 at 4 33 27 PM" src="https://user-images.githubusercontent.com/919717/57589108-ed51e700-74d3-11e9-9d0d-6e1e672387c9.png">

The command I'm using is `dart --enable-asserts --enable-vm-service:5858 --pause_isolates_on_start bin/my_command.dart`.

I think this is related to https://github.com/dart-lang/sdk/issues/36575.

dart version: `Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "macos_x64"`

There is a workaround: run the Dart command with `--disable-service-auth-codes`. 

Possible remedies:

* Improve the error code. If the connection fails with 403, the tooling should say something like "Have you provided the full blah blah blah?"
* IntelliJ plugin asks for the token.
* IntelliJ plugin offers the `--disable-service-auth-codes` flag in its "Use these command line arguments..." section.

**Comment by mit-mit** [comment]
Not clear if this is VM or IntelliJ

**Comment by ZichangG** [comment]
Looks like this is not a VM issue.

**Comment by alexander-doroshko** [comment]
@filiph I've filed an issue in the JetBrains issue tracker: https://youtrack.jetbrains.com/issue/WEB-43245. This is where we track requests related to the Dart plugin. It will be fixed ASAP.

**Comment by alexander-doroshko** [comment]
Fixed in the Dart plugin. I don't have permissions to close the issue here.
