### ISSUE TITLE
JIT vs AOT true divergence

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36953]
Found by nightly as  

JIT-OPTCOUNTER-ReleaseIA32 - JIT-DebugSIMDBC64: !DIVERGENCE! 1.13:2674942396 (output=true)

but shows ups as regular JIT vs AOT divergence too on X64.

```
1,2c1,2
< 0.0
< 40
---
> throws
> -19
6c6
< 12163347382224
---
> 206158430160

```

**Comment by aartbik** [comment]
AOT throws the following exception, but JIT does not:

throws NoSuchMethodError: The method '+' was called on null.
Receiver: null
Tried calling: +() #0      X0.foo0_1 (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz2674942396.dart:178)
#1      X0.run (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz2674942396.dart:292)
#2      main (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz2674942396.dart:298)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171)
[fuzz2674942396.dart.txt](https://github.com/dart-lang/sdk/files/3179861/fuzz2674942396.dart.txt)

**Comment by aartbik** [comment]
In AOT, the do-while loop in foo0_1()
     
```dart
{ int loc0 = 0;
   do {
         ....
   } while (++loc0 < 59);
}
```

yields the following baffling IR for the addition:

```dart
B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      ....

```

**Comment by aartbik** [comment]
Before SSA, AOT sees the following IR:
```dart
B41[join]:364 pred(B39, B43) specu repr=tagged
    t0 <- LoadLocal(loc0 @-8) specu repr=tagged #uses=0 #env-uses=0
    t1 <- LoadLocal(:t0 @-19) specu repr=tagged #uses=0 #env-uses=0
    PushArgument(t1) specu repr=tagged #uses=0 #env-uses=0
    t2 <- Constant(#1) specu repr=tagged #uses=0 #env-uses=0
    PushArgument(t2) specu repr=tagged #uses=0 #env-uses=0
    t3 <- LoadLocal(:t0 @-19) specu repr=tagged #uses=0 #env-uses=0
    CheckNull:434(t3) specu non-deopt (but could) repr=tagged #uses=0 #env-uses=0
    t3 <- Constant(#null) specu repr=tagged #uses=0 #env-uses=0
    StoreLocal(:t0 @-19, t3) specu repr=tagged #uses=0 #env-uses=0
    t1 <- StaticCall:436( +<0> t1, t2, using unchecked entrypoint, recognized_kind = Integer_add) specu non-deopt (but could) repr=tagged #uses=0 #env-uses=0
```
in contrast, the JIT unoptimized IR looks like:
```dart
B41[join]:350 pred(B39, B43) specu repr=tagged
    t0 <- LoadLocal(loc0 @-8) specu repr=tagged #uses=0 #env-uses=0
    PushArgument(t0) specu repr=tagged #uses=0 #env-uses=0
    t1 <- Constant(#1) specu repr=tagged #uses=0 #env-uses=0
    PushArgument(t1) specu repr=tagged #uses=0 #env-uses=0
    t0 <- InstanceCall:416( +<0>, t0, t1) specu non-deopt (but could) repr=tagged #uses=0 #env-uses=0
```

**Comment by aartbik** [comment]
During SSA building, some of the push arguments are not relinked properly:
```
RELINK INPUT OF PushArgument(t1) from t1 <- LoadLocal(:t0 @-19) to v0 <- Constant(#null)
RELINK INPUT OF PushArgument(t2) from t2 <- Constant(#1) to v35 <- Constant(#1)
```

**Comment by aartbik** [comment]
@mraleph can you have a quick look if something jumps out. Wrong index? Missing phi?

**Comment by mraleph** [comment]
On brief examination this looks like a missing phi. I think the root cause is incorrect computation of assigned variables - i think the core mistake is that variable liveness analysis is using `InsideTryBlock` but that returns true only for try block itself. However catch-block should also get special treatment. Things work okay as long as exits from try and catch block are merged - however in this particular case we disconnect try from catch. 

```
          // note that try block has no normal successors because it ends with throw.
          try {                                                                                                                                                      
             throw ((!(var3)) ? var5 : foo0_0(((0.574808452613698 / 0.4272697248194094)).toDouble(), (-57 | (++var0))));                                              
           } catch (exception, stackTrace) {                                                                                                                          
             var4 *= -9223372032559808513;                                                                                                                            
           }                                                                                                                                                          
         } while (++loc0 < 59);
```

I am looking at how to fix this.
