### ISSUE TITLE
Give a different warning if @required is used on a positional parameter

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#36966]
In this class:
```dart
class Action {
  const Action(@required this.name);
  final String name;
}
```
The analyzer gives the warning: `info: The type parameter 'name' is annotated with @required but only named parameters without default value can be annotated with it.`

This is because `name` is a positional parameter and not a named parameter, but the error message makes it sound like a named parameter. The analyzer should print a different message along the lines of `Redundant use of the annotation @required on a positional parameter. Positional parameters are always required.`

Version: Dart VM version: 2.3.1-dev.0.0.flutter-a0290f823c (Thu May 9 07:43:56 2019 +0000) on "linux_x64"

**Comment by jacob314** [comment]
Fyi @pq.

**Comment by pq** [comment]
cc @bwilkerson (fyi)

**Comment by parlough** [comment]
I'm not sure this is the best message as not all positional parameters are required if my understanding is correct, with the ones defined within [] actually not required? For non optional positional parameters I think something like your suggested message would work, but for optional positional parameters, should a different warning and suggestion to be made to make the parameter non optional as well as remove the `@required` annotation?

**Comment by gspencergoog** [comment]
Yes, I get your point though.  Perhaps three different cases then:

1) On required positional parameter:
   `Redundant use of the annotation @required on a positional parameter. Positional parameters are always required.`
2) On optional positional parameter:
   `Incorrect use of the annotation @required on an optional positional parameter. Optional positional parameters cannot be required.`
3) On a named parameter with a default:
  `The type parameter 'name' is annotated with @required but only named parameters without default value can be annotated with it.`

**Comment by parlough** [comment]
I gave this a shot as a first try at contributing if it is desired at https://dart-review.googlesource.com/c/sdk/+/102900

**Comment by srawlins** [comment]
Thanks, @parlough !
