### ISSUE TITLE
Stream transform not respecting isBroadcast parameter

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#36965]
(dart 2.2.0)

Below is a test which transforms a broadcast Stream using 2 different methods, one using StreamTransformer.fromHandlers, the other using an extended StreamTransformer class:

```
      // dummy transformer, using custom class
      final transformer = TestStreamTransformer<int>();
      // dummy transformers, using fromHandlers
      final fromHandlers = StreamTransformer<int, int>.fromHandlers();
      // base broadcast Stream
      final broadcastStream =
          Stream.fromIterable(const [1]).asBroadcastStream();

      final transformedStreamA = broadcastStream.transform(fromHandlers);
      final transformedStreamB = broadcastStream.transform(transformer);

      expect(broadcastStream.isBroadcast, isTrue); // passes
      expect(transformedStreamA.isBroadcast, isTrue); // passes
      expect(transformedStreamB.isBroadcast, isTrue); // fails



class TestStreamTransformer<T> extends StreamTransformerBase<T, T> {
  final StreamTransformer<T, T> transformer;

  TestStreamTransformer() : transformer = _buildTransformer();

  @override
  Stream<T> bind(Stream<T> stream) => transformer.bind(stream);

  static StreamTransformer<T, T> _buildTransformer<T>() {
    return StreamTransformer<T, T>((Stream<T> input, bool cancelOnError) {
      StreamController<T> controller;

      if (input.isBroadcast) {
        controller = StreamController<T>.broadcast(sync: true, onListen: () {});
      } else {
        controller = StreamController<T>(sync: true, onListen: () {});
      }

      return controller.stream.listen(null);
    });
  }
}
```

I would expect transform to always return a new Stream which is the same as the original Stream regarding broadcast, or not.

**Comment by frankpepermans** [comment]
The problem is with the bind Function call, when using fromHandlers, bind returns a _BoundSinkStream
https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream_transformers.dart#L177
where isBroadcast is properly handled,
however when extending StreamTransformer, bind will return a _BoundSubscriptionStream where this is not the case:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream_transformers.dart#L323

**Comment by lrhn** [comment]
Correct, the `_BoundSubscriptionStream` should probably emit the same `isBroadcast` result as the wrapped stream. I'll fix that.

This doesn't chang whether you can listen more than once or not. In practice, the `onListen` callback is called for each listen attempt. If that function starts out by calling `stream.listen` on the original stream, then you can listen multiple times when the original stream allows it.
The boolean `isBroadcast` doesn't actually do anything, it's just there as a hint that the stream has a particular behavior.

**Comment by frankpepermans** [comment]
Correct at it being just a hint, except at our rxdart lib, we sometimes treat incoming Streams differently based off this parameter, causing unexpected behavior.

**Comment by frankpepermans** [comment]
Any updates regarding this issue?

This is causing some annoying side effects with RxDart currently

**Comment by lrhn** [comment]
The `_BoundSubscriptionStream` class has been updated (https://github.com/dart-lang/sdk/commit/82c8c78739f3fd40f91836bf0dd71d6e073a6627) so it returns the `isBroadcast` of the wrapped stream.

There are no other changes planned.

**Comment by shinayser** [comment]
> The `_BoundSubscriptionStream` class has been updated ([82c8c78](https://github.com/dart-lang/sdk/commit/82c8c78739f3fd40f91836bf0dd71d6e073a6627)) so it returns the `isBroadcast` of the wrapped stream.
> 
> There are no other changes planned.

Sorry if this is a dumb question, buf if it has been fixed 3 months ago (may/19) why it still causing problems on current stream transformers?

**Comment by shinayser** [comment]
> The `_BoundSubscriptionStream` class has been updated ([82c8c78](https://github.com/dart-lang/sdk/commit/82c8c78739f3fd40f91836bf0dd71d6e073a6627)) so it returns the `isBroadcast` of the wrapped stream.
> 
> There are no other changes planned.

@lrhn do you know when this fix is being released?

**Comment by rullyalves** [comment]
I'm also having problems with this, I performed a transformation and then an external API request in a stream, and the request was redone for each stream listener.

**Comment by lrhn** [comment]
It should definitely have been released by now.
