### ISSUE TITLE
Give a different warning when overriding hashCode without operator==

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#36967]
In the following code:
```dart
class Foo {
  String name;
  @override
  int get hashCode => name.hashCode;
}
```

The analyzer warns `info: Always override hashCode if overriding ==.` when it should say  `info: Always override == if overriding hashCode.`

Version: Dart VM version: 2.3.1-dev.0.0.flutter-a0290f823c (Thu May 9 07:43:56 2019 +0000) on "linux_x64"

**Comment by gspencergoog** [comment]
cc @pq

**Comment by pq** [comment]
Great catch.  Thanks @gspencergoog.
