### ISSUE TITLE
Modified Flutter Widget transform needs to be performant

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36976]
As part of landing the new const refactoring, we need to redo the flutter widget transform to do it correctly: https://github.com/dart-lang/sdk/issues/36640

This is a separate issue to validate that it is performant.

**Comment by vsmenon** [comment]
@jacob314 @devoncarew - can someone on your team own this?

fyi - @askeksa-google

**Comment by jacob314** [comment]
I'm owning the performance validation.

**Comment by aadilmaan** [comment]
@jacob314 Any progress update?

**Comment by devoncarew** [comment]
A CL is out for review here: https://dart-review.googlesource.com/c/sdk/+/102920.

@jacob314 may be OOO now; if so, I believe that @terrylucas will take over that CL. I'll confirm.

**Comment by devoncarew** [comment]
@jacob314 may be OOO now. We'll need to de-prioritize this to a P2, or find a new owner (@askeksa-google, could that be you?).

**Comment by askeksa-google** [comment]
It should be someone familiar with testing the performance of Flutter builds.

Though based on @jacob314's comments on https://github.com/flutter/engine/pull/8994 I'd say we can just close this.

**Comment by devoncarew** [comment]
👍

**Comment by jacob314** [comment]
I tested the performance a couple days ago and it is a significant
performance improvement not regression. The previous version in Flutter was
running on more libraries than it needed to. When this change lands we
should next make track-widget-creation default to true in all Flutter run
debug builds from the command line as well as the ide case where it is
already enabled.
