### ISSUE TITLE
Feature request : Java conversion

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/sdk#36970]
I spend quite some time converting Java to dart. Copy/pasting chunks of code into the editor and then doing a bunch of common things like removing protected/private, putting _ in instead. Altering enums to remove the advanced features. Rename try/catch block. Renaming types, etc.

It would be nice if this could be done automatically during cut/paste ? I'm not suggesting it would produce working code, but just save some typing effort.
Not sure if editors support that functionality.

**Comment by mit-mit** [comment]
Offering this functionality is not considered part of the core Dart SDK. If someone in the Dart community wanted to offer a community tool for this, that would be welcome.
