### ISSUE TITLE
is! operator with ||

### ISSUE THREAD

**Issue by tlserver** [dart-lang/sdk#36982]
```
class A {
}

class B extends A {
  int f;

  B(this.f);
}

main() {
  A b = B(1);
  print(b is B && b.f == 1); // true
  // apply De Morgan's laws
  print(b is! B || b.f != 1); // expecting false but actually Error: The getter 'f' isn't defined for the class 'A'.
}
```

Is it possible that making Dart compiler think that `b` is `B` instead of `A` in the second case? `b` is always `B` when `b is! B === false`.

Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "windows_x64"

**Comment by lrhn** [comment]
Dart's type promotion is still very simple.
It only prmoteos on the positive branch of `x is T` tests, not on anything else (including not on the negative branches of `x is! T`).

We pla ton improve this in the future, no later than when introducing non-nullable types (becuse `if (x != null) ....` definitely should promote x` to non-nullable).
