### ISSUE TITLE
Wrong {} in optional function parameters

### ISSUE THREAD

**Issue by nicolasvac** [dart-lang/sdk#36980]
• Flutter version 1.5.4-hotfix.2 at /Users/nicolas/dev/flutter_sdk/flutter
• Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
• Engine revision 52c7a1e849
• Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
• MacOS Mojave 10.14.5 with Android Studio

Hi everyone. I was trying to make a function with default values on maps, but this is the error that i get.

<img width="560" alt="Schermata 2019-05-16 alle 03 20 18" src="https://user-images.githubusercontent.com/45635090/57819624-9ecd7280-7789-11e9-9f3a-7e53600263a4.png">

Dart thinks that i'm actually putting optional parameters in it, but i'm just trying to put a default value on a map.

**Comment by lrhn** [comment]
You are adding optional parameters. The `body` parameter is a named parameter, and currently all named parameters are optional parameters. Also, only optional parameters can have default values.

Your problem here is that default values must be constants, and your `{}` map literal is not a constant.
You need to write it as:
```dart
tatic dynamic post(String url,
    {Map<String, dynamic> body = const {}, Map<String, dynamic> headers}) async {
 ...
```
That is: Put a `const` in front of the `{}` to make it a constant map.

**Comment by nicolasvac** [comment]
But why do i need const only with maps ? This makes kinda of nonsense, right ?
<img width="333" alt="Schermata 2019-05-16 alle 13 08 21" src="https://user-images.githubusercontent.com/45635090/57849496-ba616900-77db-11e9-9f44-5dd5250570c4.png">

With a String, or any other type it doesn't need to, even by putting ''. It only happens with maps

**Comment by lrhn** [comment]
The string also needs to be constant, but a string literal *is* constant by default.

Map literals are, by default, mutable maps. You need to write the `const` before a collection literal (list/set/map) or an object construction (like `const Duration(seconds: 1)`). For constant number, bool and strings expressions, you don't need to write the `const`, but the expression still needs to be constant, so it cannot refer to non-constant variables or call any non-allowed-in-constants methods.

**Comment by nicolasvac** [comment]
Ok, that's clear enough now!
Thanks.
