### ISSUE TITLE
Kernel outlines should only invalidate on API changes

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36986]
This is a tracking bug for Jens' ongoing work to track:

https://dart-review.googlesource.com/c/sdk/+/101280

https://dart-review.googlesource.com/c/sdk/+/101282

We'd like this in D24 to improve incremental build times.

**Comment by vsmenon** [comment]
FYI - @kmillikin @aadilmaan @jakemac53 - per our discussion yesterday.

We'll also need follow up work in package:build and blaze to land.

**Comment by vsmenon** [comment]
The CLs in the original comment are merged.

@jensjoha @jakemac53 - can we close this yet?

**Comment by kmillikin** [comment]
Those specific CLs are landed.  @jensjoha please reopen if there's more work to be done.
