### ISSUE TITLE
How do I execute Dynamically (like Eval) in Dart?

### ISSUE THREAD

**Issue by smile2014** [dart-lang/sdk#36989]
var doAdd = new Function("iNum", "alert(iNum + 10)");
doAdd(10);---->  20

**Comment by lrhn** [comment]
Dart does not allow you to create code at run-time.

What problem are you trying to solve?

There are workarounds when you are running on the VM and has access to isolates. You can create a new library with a `main` function, encode the source code as a `data:` URI and spawn it as a new isolate, but that will not allow you to create a new functions in the current isolate. You'll have to communicate with the new code using isolate port communication.

In general, I'd recommend trying something else. It is often possible to get the effect of generating code by just combining first-class function values, but that obviously depends on the problem at hand.

**Comment by smile2014** [comment]
I dynamically render the form through the json data given by the backend. The disabled corresponds to a piece of javascript, similar to angular ngx-formly expression

**Comment by Sunbreak** [comment]
Though not planned, but it is possible actually.

Dart could take advantage of JavaScript prototype chain as Kotlin/JS in https://rosettacode.org/wiki/Reflection/Get_source#Kotlin

It is possible even in Dart/VM in JIT mode: https://rosettacode.org/wiki/Reflection/Get_source#Kotlin
