### ISSUE TITLE
StreamSubscription.cancel should return Future<void>

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#36994]
[StreamSubscription.cancel](https://api.dartlang.org/stable/2.3.0/dart-async/StreamSubscription/cancel.html) currently returns a "raw" Future (a `Future<dynamic>`). The documentation reads:

> For historical reasons, may also return null if no cleanup was necessary. Returning null is deprecated and should be avoided.

> A returned future completes with a null value. If the cleanup throws, which it really shouldn't, the returned future completes with that error.

I imagine the null value that the returned future completes with is a "pre Dart 2-ism", before `Future<void>` was a valid type. Perhaps as part of `dart:async`'s opt-in to NNBD, the return type could be changed to non-nullable `Future<void>`.

Correct me if I'm wrong, but I think it is a non-breaking change to change a return type from `Future<dynamic>` to `Future<void>`. `Future<void>` is assignable to `Future<dynamic>`.

**Comment by lrhn** [comment]
No interface API change is non-breaking. I wish it wasn't so, but it is.

Changing a return type to a super-type (`Future<void>` is a super-type of `Future<Null>`) will allow subclasses to continue working, but it may break clients which do: `Future<Null> result = subscription.cancel();`. That will then introduce an implicit downcast which may fail.

It might be possible to make the change completely non-breaking by changing the interface to `Future<void>` and still only return `Future<Null>` instances. I can't find a simple way to break that, but it *requires* implicit downcasts, so people warning about those might get bitten.

**Comment by lrhn** [comment]
We managed to make the change as part of Null Safety migration. The return type is (non-nullable) `Future<void>` now.
