### ISSUE TITLE
Please merge #9ac7bd78 into stable channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36998]
**commit to merge**: 9ac7bd78550ac5c73b2131a71751a30e6ae967e7

**merge instructions**: clean merge

**reason**: this fixes a dart2js crash when developers use spreads `...` in top-level fields. Both internal and external users have come across this bug (#36864, #36963).

The fix is already in 2.3.1-dev.0.0, this request is to release it also in the stable channel.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @aadilmaan

**Comment by aadilmaan** [comment]
Sigi - Can it wait until we get D24 out on stable or this is urgent enough for a patch release?

**Comment by sigmundch** [comment]
I just saw another issue filed about this over the weekend (#37010)

My inclination is to do a patch release. It's not _urgent_ because it doesn't affect code that already exists, only new code with UI-as-code features. However, it makes the product feel unpolished for users exploring the new UI-as-code features. Given that this affects top-level fields, my hunch is that people hit this more often when first exploring around with the feature in Dart Pad.

**Comment by aadilmaan** [comment]
Alright. Looking to Alex to merge this.

**Comment by athomas** [comment]
I can do it on Tuesday.

@aadilmaan I'm assuming that you'll coordinate announcements/other release activities if necessary?

@sigmundch Can you suggest a paragraph that I can add to the changelog?

**Comment by aadilmaan** [comment]
@athomas Do you mean the release activities referenced here: https://github.com/dart-lang/sdk/wiki/Release-checklist

**Comment by sigmundch** [comment]
>... Can you suggest a paragraph that I can add to the changelog?

Here is an attempt:

# 2.3.1 - 2019-05-21

This is a patch version release with bug fixes.

### Dart for the web
#### dart2js

* fixed a bug that caused the compiler to crash when it compiled UI-as-code features within fields.

**Comment by athomas** [comment]
@aadilmaan https://github.com/dart-lang/sdk/wiki/Release-checklist#stable-release-patch

Seems like we don't have much more than an announcement to do for a stable release patch. That wiki page seems a bit out-of-date though.

**Comment by aadilmaan** [comment]
@mit-mit What do you think we should do for any release checklist items? I think a simple email to the announce group should suffice here.

**Comment by mit-mit** [comment]
Agree, I think we should email dart-announce. Here is a similar post I did back when we did Dart 1.x builds:
https://groups.google.com/a/dartlang.org/forum/#!topic/announce/nFzxF6mzCyM

**Comment by aadilmaan** [comment]
Awesome. I will send this out once Alex has landed the change on stable.

**Comment by sigmundch** [comment]
Thanks Alex and Aadil!

Closing this bug as I see 2.3.1 is out and this has been announced now.
