### ISSUE TITLE
The compiler crashed: Crash when compiling package:react/react_dom.dart

### ISSUE THREAD

**Issue by mwattsun** [dart-lang/sdk#36990]
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "windows_x64"
Windows 10 pro version 1809 (OS Build 17763.53)
Chrome Version 74.0.3729.157 (Official Build) (64-bit)
While building fresh clone of project https://github.com/leerob/dart-react-todo.git
Dart-to-JavaScript compiler (dart2js) version: 2.3.0

The compiler crashed: Crash when compiling package:react/react_dom.dart,
at character offset null:
RangeError (offset): Invalid value: Not in range 0..828, inclusive: 2019
#0      RangeError.checkValueInInterval (dart:core/errors.dart:281:7)
#1      Source.getLocation (package:kernel/ast.dart:6050:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:16:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:203:47)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:226:29)
#5      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:68:13)
#6      Loader.addMessage (package:front_end/src/fasta/loader.dart:279:20)
#7      Loader.addProblem (package:front_end/src/fasta/loader.dart:230:12)
#8      LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:109:19)
#9      KernelLibraryBuilder.addProblem (package:front_end/src/fasta/kernel/kernel_library_builder.dart:251:47)
#10     KernelLibraryBuilder.reportTypeArgumentIssue (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1545:5)
#11     KernelClassBuilder.checkBoundsInSupertype (package:front_end/src/fasta/kernel/kernel_class_builder.dart:329:17)
#12     KernelClassBuilder.checkBoundsInOutline (package:front_end/src/fasta/kernel/kernel_class_builder.dart:375:7)
#13     KernelLibraryBuilder.checkBoundsInOutline (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1786:21)
#14     SourceLoader.checkBounds.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:875:16)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#16     SourceLoader.checkBounds (package:front_end/src/fasta/source/source_loader.dart:871:14)
#17     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:276:14)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#20     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:107:28)
<asynchronous suspension>
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#23     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:180:32)
<asynchronous suspension>
#24     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#34     compile (package:front_end/src/api_unstable/dart2js.dart:178:46)
<asynchronous suspension>
#35     KernelLoaderTask.load.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/loader.dart:110:27)
<asynchronous suspension>
#36     CompilerTask.measure (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#37     KernelLoaderTask.load (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/loader.dart:59:12)
#38     Compiler.runInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:248:48)
<asynchronous suspension>
#39     Compiler.run.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:38)
#40     new Future.sync (dart:async/future.dart:224:31)
#41     Compiler.run.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:20)
#42     CompilerTask.measureSubtask (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#43     Compiler.run (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:220:41)
#44     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#45     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#50     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

#0      RangeError.checkValueInInterval (dart:core/errors.dart:281:7)
#1      Source.getLocation (package:kernel/ast.dart:6050:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:16:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:203:47)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:226:29)
#5      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:68:13)
#6      Loader.addMessage (package:front_end/src/fasta/loader.dart:279:20)
#7      Loader.addProblem (package:front_end/src/fasta/loader.dart:230:12)
#8      LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:109:19)
#9      KernelLibraryBuilder.addProblem (package:front_end/src/fasta/kernel/kernel_library_builder.dart:251:47)
#10     KernelLibraryBuilder.reportTypeArgumentIssue (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1545:5)
#11     KernelClassBuilder.checkBoundsInSupertype (package:front_end/src/fasta/kernel/kernel_class_builder.dart:329:17)
#12     KernelClassBuilder.checkBoundsInOutline (package:front_end/src/fasta/kernel/kernel_class_builder.dart:375:7)
#13     KernelLibraryBuilder.checkBoundsInOutline (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1786:21)
#14     SourceLoader.checkBounds.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:875:16)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#16     SourceLoader.checkBounds (package:front_end/src/fasta/source/source_loader.dart:871:14)
#17     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:276:14)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#20     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:107:28)
<asynchronous suspension>
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#23     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:180:32)
<asynchronous suspension>
#24     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#34     compile (package:front_end/src/api_unstable/dart2js.dart:178:46)
<asynchronous suspension>
#35     KernelLoaderTask.load.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/loader.dart:110:27)
<asynchronous suspension>
#36     CompilerTask.measure (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#37     KernelLoaderTask.load (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/loader.dart:59:12)
#38     Compiler.runInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:248:48)
<asynchronous suspension>
#39     Compiler.run.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:38)
#40     new Future.sync (dart:async/future.dart:224:31)
#41     Compiler.run.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:20)
#42     CompilerTask.measureSubtask (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#43     Compiler.run (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:220:41)
#44     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#45     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#50     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by jensjoha** [comment]
This will be fixed with https://dart-review.googlesource.com/106083.
