### ISSUE TITLE
webdev reports compiler errror

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#37007]
Version before dart-sdk 2.30:
This is basically the same problem,  I have previously posted about and it has been closed.
However, this time the error is different so I thought I would pass it along. 

Note that after getting and updating dependencies the problem was solved.
 

......

Here is the information that was generated.

Thank you for taking the time to file an issue!

Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk-summary=/Users/cia73872827277/Documents/dartProjects/dart/dart-sdk/lib/_internal/ddc_sdk.sum --modules=amd -o web/drpond.ddc.js --module-root=. --library-root=/web --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/petitparser/src/core/actions/action.dartdevc.linked.sum -s packages/petitparser/petitparser.dartdevc.linked.sum -s packages/collection/src/utils.dartdevc.linked.sum -s packages/collection/src/algorithms.dartdevc.linked.sum -s packages/collection/src/canonicalized_map.dartdevc.linked.sum -s packages/collection/src/comparators.dartdevc.linked.sum -s packages/collection/src/iterable_zip.dartdevc.linked.sum -s packages/collection/src/priority_queue.dartdevc.linked.sum -s packages/collection/collection.dartdevc.linked.sum -s packages/xml/src/xml/builder.dartdevc.linked.sum -s packages/xml/xml.dartdevc.linked.sum -s packages/codemirror/src/js_utils.dartdevc.linked.sum -s packages/codemirror/codemirror.dartdevc.linked.sum --url-mapping=file:///web/drpond.dart,web/drpond.dart --url-mapping=file:///web/pictureconstruction.dart,web/pictureconstruction.dart --url-mapping=file:///web/piano_input.dart,web/piano_input.dart --url-mapping=file:///web/show_examples.dart,web/show_examples.dart --url-mapping=file:///web/lib/xml/xmlImport.dart,web/lib/xml/xmlImport.dart --url-mapping=file:///web/lib/apg/pict.dart,web/lib/apg/pict.dart --url-mapping=file:///web/lib/apg/apg.dart,web/lib/apg/apg.dart --url-mapping=file:///web/lib/apg/src/anchor.dart,web/lib/apg/src/anchor.dart --url-mapping=file:///web/lib/apg/src/transform.dart,web/lib/apg/src/transform.dart --url-mapping=file:///web/lib/apg/src/apgFunctions.dart,web/lib/apg/src/apgFunctions.dart --url-mapping=file:///web/lib/apg/src/iterator.dart,web/lib/apg/src/iterator.dart --url-mapping=file:///web/lib/apg/src/iteratorsforPaths.dart,web/lib/apg/src/iteratorsforPaths.dart --url-mapping=file:///web/lib/apg/src/paths.dart,web/lib/apg/src/paths.dart --url-mapping=file:///web/lib/drPondPicture.dart,web/lib/drPondPicture.dart --url-mapping=file:///web/lib/lexer.dart,web/lib/lexer.dart --url-mapping=file:///web/lib/errorHandling.dart,web/lib/errorHandling.dart --url-mapping=file:///web/lib/drawing/drawSemantics.dart,web/lib/drawing/drawSemantics.dart --url-mapping=file:///web/lib/drawing/drawStatements.dart,web/lib/drawing/drawStatements.dart --url-mapping=file:///web/lib/drawing/drawExprs.dart,web/lib/drawing/drawExprs.dart --url-mapping=file:///web/lib/drawing/colors.dart,web/lib/drawing/colors.dart --url-mapping=file:///web/lib/drawing/drawLexerConst.dart,web/lib/drawing/drawLexerConst.dart --url-mapping=file:///web/lib/drawing/drawParser.dart,web/lib/drawing/drawParser.dart --url-mapping=file:///web/lib/musicAnimatedPict.dart,web/lib/musicAnimatedPict.dart --url-mapping=file:///web/lib/music/musicParser.dart,web/lib/music/musicParser.dart --url-mapping=file:///web/lib/music/musicSemantics.dart,web/lib/music/musicSemantics.dart --url-mapping=file:///web/lib/music/musicExprs.dart,web/lib/music/musicExprs.dart --url-mapping=file:///web/lib/music/musicLexerConst.dart,web/lib/music/musicLexerConst.dart --url-mapping=file:///web/lib/music/musicStatements.dart,web/lib/music/musicStatements.dart --url-mapping=file:///web/lib/music/waveTable/piano.dart,web/lib/music/waveTable/piano.dart file:///web/drpond.dart file:///web/pictureconstruction.dart file:///web/piano_input.dart file:///web/show_examples.dart file:///web/lib/xml/xmlImport.dart file:///web/lib/apg/pict.dart file:///web/lib/apg/apg.dart file:///web/lib/apg/src/anchor.dart file:///web/lib/apg/src/transform.dart file:///web/lib/apg/src/apgFunctions.dart file:///web/lib/apg/src/iterator.dart file:///web/lib/apg/src/iteratorsforPaths.dart file:///web/lib/apg/src/paths.dart file:///web/lib/drPondPicture.dart file:///web/lib/lexer.dart file:///web/lib/errorHandling.dart file:///web/lib/drawing/drawSemantics.dart file:///web/lib/drawing/drawStatements.dart file:///web/lib/drawing/drawExprs.dart file:///web/lib/drawing/colors.dart file:///web/lib/drawing/drawLexerConst.dart file:///web/lib/drawing/drawParser.dart file:///web/lib/musicAnimatedPict.dart file:///web/lib/music/musicParser.dart file:///web/lib/music/musicSemantics.dart file:///web/lib/music/musicExprs.dart file:///web/lib/music/musicLexerConst.dart file:///web/lib/music/musicStatements.dart file:///web/lib/music/waveTable/piano.dart
    dart --version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```
FileSystemException(path=packages/petitparser/src/core/actions/action.dartdevc.linked.sum; message=Cannot open file)
#0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:201:7)
#1      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:503:21)
#2      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:411:43)
#3      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#4      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:411:18)
#5      new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:94:21)
#6      _compile (package:dev_compiler/src/analyzer/command.dart:135:22)
#7      compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:385:18)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
}

[SEVERE] Failed after 1.4s
Serving `web` on http://localhost:53322

**Comment by srawlins** [comment]
We have changed summary format since this error; I suspect this has been resolved.
