### ISSUE TITLE
hot reload button is grayed out in Android Studio 

### ISSUE THREAD

**Issue by KingxXxCode** [dart-lang/sdk#37001]
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50397/v1bGluENHfQ=/ws

**Comment by a-siva** [comment]
@KingxXxCode can you provide a more detailed scenario of the steps that lead to this error.

**Comment by alexander-doroshko** [comment]
@a-siva @devoncarew maybe close this issue as there's not enough information to proceed? In any case, I'm not sure `area-intellij` is the right label here.
