### ISSUE TITLE
Remove the localhost security restriction for VMService connections

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#37000]
If someone runs the VM disabling the security token we should continue to enforce the localhost restriction.

When the security token is in place, the localhost check serves no purpose and just blocks users from convenient use cases.

**Comment by bkonyi** [comment]
Authentication codes aren't an alternative solution to the existing origin check as they provide different protections against malicious connections. AFAIK, we don't have any plan to remove the origin check as there's a way for users to disable it for convenience.
