### ISSUE TITLE
Analyzer does not throw a compile error when declares a class with super-bounded type parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#37028]
Dart SDK Version: 2.3.1-dev.0.0
OS: Windows 10 64 bit

The following test example creates several classes:
``` dart
class A<T extends A<T>> {}

class B1<X extends A<Object>> {}
class B2<X extends A<dynamic>> {}
class B3<X extends A<void>> {}

class B4<X extends A<A<Object>>> {}
class B5<X extends A<A<dynamic>>> {}
class B6<X extends A<A<void>>> {}

main() {}
```

Dart throws a compile time errors for all the `B1`-`B6` class declarations.
Analyzer throws a compile error for `B1` and `B4` variables only and passes for `B2`, `B3`, `B5`, `B6`,

Seems like all these cases shiuld work in the similar way.

Dart sample output is:

> $> dart test.dart
> test.dart:3:10: Error: Type argument 'Object' doesn't conform to the bound 'A<T>' of the type variable 'T' on 'A'.
>  - 'Object' is from 'dart:core'.
>  - 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B1<X extends A<Object>> {}
>          ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<T extends A<T>> {}
>         ^
> test.dart:4:10: Error: Type argument 'dynamic' doesn't conform to the bound 'A<T>' of the type variable 'T' on 'A'.
>  - 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B2<X extends A<dynamic>> {}
>          ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<T extends A<T>> {}
>         ^
> test.dart:5:10: Error: Type argument 'void' doesn't conform to the bound 'A<T>' of the type variable 'T' on 'A'.
>  - 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B3<X extends A<void>> {}
>          ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<T extends A<T>> {}
>         ^
> test.dart:7:10: Error: Type argument 'A<Object>' doesn't conform to the bound 'A<T>' of the type variable 'T' on 'A'.
>  - 'A' is from 'test.dart'.
>  - 'Object' is from 'dart:core'.
> Try changing type arguments so that they conform to the bounds.
> class B4<X extends A<A<Object>>> {}
>          ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<T extends A<T>> {}
>         ^
> test.dart:8:10: Error: Type argument 'A<dynamic>' doesn't conform to the bound 'A<T>' of the type variable 'T' on 'A'.
>  - 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B5<X extends A<A<dynamic>>> {}
>          ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<T extends A<T>> {}
>         ^

Analyzer sample output is:
> Analyzing test.dart...
>   error - 'Object' doesn't extend 'A<Object>' at test.dart:3:22 - type_argument_not_matching_bounds
>   error - 'A<Object>' doesn't extend 'A<A<Object>>' at test.dart:7:22 - type_argument_not_matching_bounds
>   error - 'Object' doesn't extend 'A<Object>' at test.dart:7:24 - type_argument_not_matching_bounds
> 3 errors found.

Please note that both dart and analyzer expectedly passes for 
``` dart
class A<T extends A<T>> {}

class B1<X extends A<Null>> {}
class B2<X extends A<A<Null>>> {}

main() {}
```

**Comment by eernstg** [comment]
None of `B1` .. `B6` is an error: The bound of a type variable _can_ be a super-bounded type.

In practice that's probably a bad idea because the type variable is available (so we can use `T extends A<T>` rather than `T extends A<Object>`, which is more informative), but it is allowed.

**Comment by stefantsov** [comment]
I agree with Erik.  I think the given program should compile without errors.  [According to the spec](https://github.com/dart-lang/sdk/blob/2bbb6aae9bb7a14a8177463bcb5a857e635978df/docs/language/dartLangSpec.tex#L5245) super-bounded types should be allowed in bounds of type variables.  The proposed fix is going to land soon: https://dart-review.googlesource.com/c/sdk/+/79701.

**Comment by stefantsov** [comment]
Note that the fix only covers the CFE behavior.

**Comment by eernstg** [comment]
I just created #37034 for the analyzer.

**Comment by stefantsov** [comment]
https://dart-review.googlesource.com/c/sdk/+/79701 is landed, so I'm closing this issue.
