### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by Jhingun1** [dart-lang/sdk#37020]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

**Comment by a-siva** [comment]
Can you provide the full stack trace that the analyzer feedback provided, it is hard to figure out the problem from your description.

**Comment by vsmenon** [comment]
Hi, if you do have a stack trace, please open a new issue.  We don't have enough info here.
