### ISSUE TITLE
Can't try/catch around a final variable declaration

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#37023]
Consider:
```dart
   final Foo foo = obtainFoo();
   doSomethingWith(foo);
```
However, `obtainFoo()` is defined as potentially throwing a `FormatException`, so we want to wrap it in a try/catch. We do not want to wrap the `doSomethingWith` call in a try/catch, as it is defined as never throwing and so catching exceptions from it is wrong.

Currently we are forced to do this:

```dart
  Foo foo;
  try {
    foo = obtainFoo();
  } on FormatException catch (error) {
    reportError(error);
    return;
  }
  doSomethingWith(foo);
```

...however doing this means that `foo` is no longer final.

Making things up, one imagines:

```dart
  final Foo foo = try {
    obtainFoo()
  } on FormatException catch (error) {
    reportError(error);
    return;
  };
  doSomethingWith(foo);
```

**Comment by kevmoo** [comment]
A language feature request? CC @munificent @leafpetersen @mit-mit @lrhn @eernstg

**Comment by matanlurey** [comment]
I "feels" bad but you can do this:

```dart
void main() {
  final foo = () {
    try {
      return obtainFoo();
    } on FormatException catch (error) {
      reportError(error);
      return null;
    }
  }();
}
```

I imagine this might be somewhere where `late final` becomes useful, though.

**Comment by leafpetersen** [comment]
Try catch expressions could be useful here.  

We could consider allowing definite assignment for final variables as well when we ship definite assignment as part of NNBD.

**Comment by Hixie** [comment]
it'd be interesting to define `final` such that when it is used on a declaration without an assignment, it requires that the compiler be able to prove that before any use, it has gone through exactly one assignment (I assume this is what "late final" means, but I don't think we need new syntax to do it in Dart).

**Comment by munificent** [comment]
> (I assume this is what "late final" means, but I don't think we need new syntax to do it in Dart)

Late final means "check *at runtime* that a variable was assigned before use". Definite assignment analysis means to do that check statically. My understanding is that we're planning to do definite assignment analysis of locals as part of NNBD. I think that might extend to final ones, but I'm not sure.

**Comment by leafpetersen** [comment]
Right.  `late final` is for cases where the compiler can't prove that it's definitely assigned (so runtime check on any read not dominated by another read/write).  Extending definite assignment analysis to `final` variables as well seems very reasonable, I think I'll include it in the proposal for evaluation.

**Comment by srawlins** [comment]
I think this is covered by `final` with definite assignment, yes?

```dart
final Foo foo;
try {
  foo = obtainFoo();
} on FormatException catch (error) {
  reportError(error);
  return;
}
doSomethingWith(foo);
```

**Comment by munificent** [comment]
Yes, I think null safety will make code like this work as intended.
