### ISSUE TITLE
Access to Pub Serve output

### ISSUE THREAD

**Issue by wtoalabi** [dart-lang/sdk#37036]
I am planning on writing the frontend for my next project with Dart.
The backend will be PHP (using the Laraval framework).

Right now, using dart2js is the only way to convert the dart code to JS.
And it is slow for my process.
After each iteration, I have to save and generate, then refresh the browser to view changes.

The only alternative I know of is to use pub serve.
That works, but I dont have access to the generated file.

Which I need to give to Laravel.

The way it is done with JS/Webpack is that the you write your React/Vue and it saves (when you --watch) the generated JS into a specified folder...which is then picked up by the server.

So, my question is, is this possible in a way I have not found out yet?

Is there a way to watch dart files for changes and output the result into an output folder of choice?

Thanks!!!

**Comment by a-siva** [comment]
@wtoalabi should you be filing this issue at https://github.com/dart-lang/pub/issues and not against the sdk?

**Comment by vsmenon** [comment]
@wtoalabi - have you looked at webdev: https://github.com/dart-lang/webdev ?

E.g.,:
```
> webdev serve --auto restart
```

This uses DDC - the fast development compiler - instead of dart2js for debugging.

**Comment by vsmenon** [comment]
Closing here.  If you have further questions, please take a look at gitter or other channels for faster responses:

https://dart.dev/community
