### ISSUE TITLE
Analyzer reports error for some super-bounded types used as a bound

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#37034]
Cf. #37028, which contains the following:

> Dart SDK Version: 2.3.1-dev.0.0
> OS: Windows 10 64 bit
> 
> The following test example creates several classes:

```dart
class A<T extends A<T>> {}

class B1<X extends A<Object>> {}
class B2<X extends A<dynamic>> {}
class B3<X extends A<void>> {}

class B4<X extends A<A<Object>>> {}
class B5<X extends A<A<dynamic>>> {}
class B6<X extends A<A<void>>> {}

main() {}
```

> Dart throws a compile time errors for all the B1-B6 class declarations.
> Analyzer throws a compile error for B1 and B4 variables only and passes for B2, B3, B5, B6,

It is allowed for a type variable bound to be a super-bounded type, so all of these are correct. Checking the example with a `dartanalyzer` from 2.3.1-dev.0.0 and a fresh one from c4e8cf469a0ff7c19fab0578b496b3593b17a1d5, I also get errors for `B1` and `B4`, and that should not happen:

```
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/201905/n011.dart|7|22|9|'A<Object>' doesn't extend 'A<A<Object>>'.
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/201905/n011.dart|7|24|6|'Object' doesn't extend 'A<Object>'.
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/201905/n011.dart|3|22|6|'Object' doesn't extend 'A<Object>'.
```

**Comment by srawlins** [comment]
Still the case.

**Comment by eernstg** [comment]
We can actually close this issue. Here is an updated version of the example program (the original example assumed a language version before null safety):

```dart
class A<T extends A<T>> {}

class B1<X extends A<Object?>> {}
class B2<X extends A<dynamic>> {}
class B3<X extends A<void>> {}

class B4<X extends A<A<Object?>>> {}
class B5<X extends A<A<dynamic>>> {}
class B6<X extends A<A<void>>> {}

main() {}
```

This program is accepted with no diagnostic messages, which is as expected.
