### ISSUE TITLE
PrepareInlineStringIndexOp builds incorrect graph on SIMDBC64

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37046]
We have the following code in this function: 

```cpp
  LoadIndexedInstr* load_indexed = new (Z) LoadIndexedInstr(
      new (Z) Value(str), new (Z) Value(index), Instance::ElementSizeFor(cid),
      cid, kAlignedAccess, DeoptId::kNone, call->token_pos());
  cursor = flow_graph->AppendTo(cursor, load_indexed, NULL, FlowGraph::kValue);

  auto box = BoxInstr::Create(kUnboxedIntPtr, new Value(load_indexed));
  cursor = flow_graph->AppendTo(cursor, box, nullptr, FlowGraph::kValue);
```

it assumes that  `LoadIndexedInstr` would returned unboxed value. However this is not true on SIMDBC where it returns tagged value

```cpp
Representation LoadIndexedInstr::representation() const {
  switch (class_id_) {
    // ...
    case kOneByteStringCid:
    case kTwoByteStringCid:
    case kExternalOneByteStringCid:
    case kExternalTwoByteStringCid:
      return kTagged;
```

**Comment by mkustermann** [comment]
By looking at this it seems to me that the `LoadIndexedInstr::representation()` is in agreement with `LoadIndexedInstr::EmitNativeCode()` in DBC (same for `StoreIndexedInstr` and `RequiredInputRepresentation()`). The `SelectRepresentations` pass will add extra boxing/unboxing instructions to make representations match up. So I'm not quite sure if this is an actual bug.

Though I agree the extra boxing/unboxing is unnecessary and we should change the DBC instructions to also load/store unboxed values like on the other architectures.

[cl/103301](https://dart-review.googlesource.com/c/sdk/+/103301) should address this.

**Comment by mraleph** [comment]
It is in the agreement but it generates graph which does not make sense by itself - I would like us to move towards consistent representations in the graph and not emitting box of tagged values (even though this would be later repaired by the SelectRepresentations pass) would be a good first step.
