### ISSUE TITLE
'late' word

### ISSUE THREAD

**Issue by Davarg** [dart-lang/sdk#37067]
Dart 2.3.0
Flutter 1.5.4-hotfix.2
I can't use 'late' word as variable name or method name.
For example

```dart
class A {
    int get late => 0;
}
```

**Comment by lrhn** [comment]
We want to use `late` as a built-in identifier in a future language feature, so most likely the parsers are already now starting to special-case it. 

That should not break here, though, since a built-in identifier should be useable as a method or variable name (just not as a type or prefix name).

**Comment by danrubel** [comment]
@Davarg  Just downloaded and tried this with Dart 2.3.0 and there does not seem to be a problem using `late` as an identifier name (see below). What am I missing?
```
$ cat stuff.dart
class A {
    int get late => 0;
}

main() {
  print('result = ${A().late}');
}

$ dart stuff.dart 
result = 0

$ dart --version
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "macos_x64"
```

**Comment by DanTup** [comment]
FWIW, I'd also tried to repro this on v2.3.0 and the current nightly and couldn't. I'm not sure what was different here. FWIW, here's the errors @Davarg provided (he posted it in Gitter after raising here):

- first for `get` - Expected to find ';'.dart(`expected_token`)
- second for `late` - Can't have modifier 'late' here. Try removing 'late'.dart(`extraneous_modifier`)
- third for `=>` - Methods must have an explicit list of parameters. Try adding a parameter list.dart(missing_method_parameters). Expected an identifier.dart(`missing_identifier`)

**Comment by leafpetersen** [comment]
I can reproduce this in the version of dart shipped in flutter stable labelled as 2.3.0-dev.0.5 , but not in the version shipped as the dart sdk labelled as 2.3.0-dev.0.5 (see below).  This was a regression that was reported here and fixed: https://github.com/dart-lang/sdk/issues/36691 .  It looks like flutter stable shipped from the bad state.

```
leafp-macbookpro:flutter leafp$ cat ~/tmp/test1.dart
class A {
    int get late => 0;
}

void main() {
  new A();
}leafp-macbookpro:flutter leafp$ ./bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64"
leafp-macbookpro:flutter leafp$ ./bin/cache/dart-sdk/bin/dart ~/tmp/test1.dart
file:///Users/leafp/tmp/test1.dart:2:9: Error: Expected ';' after this.
    int get late => 0;
        ^^^
file:///Users/leafp/tmp/test1.dart:2:13: Error: Can't have modifier 'late' here.
Try removing 'late'.
    int get late => 0;
            ^^^^
file:///Users/leafp/tmp/test1.dart:2:18: Error: Expected an identifier, but got '=>'.
    int get late => 0;
                 ^^
file:///Users/leafp/tmp/test1.dart:2:18: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
    int get late => 0;
                 ^^
leafp-macbookpro:flutter leafp$ ~/dart/dart-sdk/bin/dart --version
Dart VM version: 2.3.0-dev.0.5 (Tue Apr 30 12:57:36 2019 -0700) on "macos_x64"
leafp-macbookpro:flutter leafp$ ~/dart/dart-sdk/bin/dart ~/tmp/test1.dart
leafp-macbookpro:flutter leafp$ 
```

**Comment by DanTup** [comment]
- the version of dart shipped in flutter stable labelled as 2.3.0-dev.0.5
- the version shipped as the dart sdk labelled as 2.3.0-dev.0.5

Ouch, that explains why I couldn't repro with what seemed like the same version. I guess this issue is already resolved then (though it's a shame this didn't somehow end up on the [Flutter bad builds page](https://github.com/flutter/flutter/wiki/Bad-Builds) to prevent it getting to stable).

**Comment by Davarg** [comment]
Hello everyone and thanks for help. As I understand this issue is now exist only in Flutter so I created another ticket, you can see.

**Comment by lrhn** [comment]
Agree, this is now a Flutter-only issue.
