### ISSUE TITLE
LUB of void and, e.g., int, is void, generating use_of_void issues.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#37070]
Take the following code:

```dart
void main() async {
  var x = await Future.wait([
    Future<int>.value(7),
    Future<void>.value(),
  ]);
  var y =  x[0];
  print(y);
}
```

The analyzer reports on the last line, "The expression here has a type of 'void', and therefore cannot be used.". dart2js also errors out, saying, "Error: This expression has type 'void' and can't be used."

[Future.wait](https://api.dartlang.org/stable/2.3.1/dart-async/Future/wait.html) takes a `Iterable<Future<T>>`, and returns a `Future<List<T>>`. Inference is resolving T to (correct me if I'm wrote) the LUB of int and void, getting void. :(

The workaround here is to use `List<Object>` or `List<dynamic>` on the left, but I think it would make more sense if the  LUB here resolved to dynamic.

Related void issues:

* https://github.com/dart-lang/sdk/issues/34455 The unsoundness of `void` checking matters
* https://github.com/dart-lang/sdk/issues/32558 void is inconsistent about whether non-void values can be assigned to it
* https://github.com/dart-lang/sdk/issues/33340 Front end: move void above (below) dynamic in LUB(GLB)

**Comment by lrhn** [comment]
I think picking `void` as the type here is *perfect*.

If you change `x[0]` to `x[1]`, then your code will invalidly use a `void` typed result.

The type system around `void` is there to protect you against that. If you choose to sidestep that by casting `void` to `Object` or `dymamic`, then that's on you, and you having to do it explicitly seems like the right choice.
