### ISSUE TITLE
Request: Official ORM

### ISSUE THREAD

**Issue by weitzhandler** [dart-lang/sdk#37076]
Hi,

I'm a .NET developer, and I'm checking out Flutter and Dart, because I'm fascinated by its support for mobile, desktop, and web.

One of the major things that scare me most, is that Dart doesn't provide an official ORM alternative to [Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/).

My request is that the Dart team officially recognize one and ensure its equipped with support for:
- Easy code-first relational model design once
- Database generation and migration
- Data querying and manipulation
- All done by Dart, without having to write SQL queries (unless refined stuff are required)

Posted as of Dart SDK Version: 2.3.1

Thanks!

**Comment by srawlins** [comment]
This work is much better suited towards individual packages. Packages can use the FFI interface or native extensions. Users can write and share their own database APIs, including ORMs.

As Dart is oriented as a client language (on mobile devices or in the browser), authoring and supporting our own interfaces to databases, or writing an ORM, is not something we're prioritizing.

**Comment by Wdestroier** [comment]
@srawlins Can this issue be reopened? It's impossible to create an ORM equivalent to Entity Framework without support from the sdk team.

The best attempt I have seen so far is from [typed_sql](https://pub.dev/packages/typed_sql):

```dart
await db.books
    .where((b) => b.authorId.equals(toExpr(authorId)))
    .delete()
    .execute();
```

However, the code above should be ideally written as:

```dart
await db.books
    .where((b) => b.authorId == authorId)
    .delete();
```

Anybody can write an ORM in a week-end.
For example, the following code from Eloquent ORM (Laravel) can be easily rewritten in Dart:
```php
$model = User::where('votes', '>', 100)->firstOrFail();
```

Entity Framework had support from the compiler team. That's how it's so much superior to any ORM created by other programming language users.

True, multiple databases providers can be written by the community ([PostgreSQL example](https://github.com/npgsql/efcore.pg)). The core of the framework can't be written by the community.
