### ISSUE TITLE
Add back support for getStaticMethods and getStaticFields in DDC output

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#37071]
Forked from #36802

**Comment by natebosch** [comment]
cc @jakemac53

https://dart-review.googlesource.com/c/sdk/+/103549 adds this in the kernel path.

This makes the `lib/dev_compiler/kernel/amd/dart_sdk.js` file about 9% bigger so this could be a significant code size regression. We'll need to see what it does with some representative client code.

With the change as is  we would be outputting type signature information for static functions, which does not seem necessary to meet the needs of the [function interface](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#function) which needs only the name, owners, and whether it's const... For fields it does currently also want type information.

We need to decide whether all we need is the name, or whether we really need this support at all and that it's worth the code size.

**Comment by jakemac53** [comment]
> This makes the `lib/dev_compiler/kernel/amd/dart_sdk.js` file about 9% bigger so this could be a significant code size regression. We'll need to see what it does with some representative client code.

wow, ya that is a lot worse than I would have expected

**Comment by natebosch** [comment]
Looks like the SDK and proto modules are hit the worst. A large proto module internally went up by 22%. Overall, though, I think the impact on a large app was about 3%. For some modules the impact is <1%, I suppose because some code uses relatively little static fields and methods...

**Comment by natebosch** [comment]
@jakemac53 - do we need this enabled for the SDK or can we get by without that?

**Comment by jakemac53** [comment]
I think we probably need it, otherwise nobody will be able to see any static methods or fields on SDK objects in the debugger.

**Comment by jakemac53** [comment]
Nevermind, we talking offline and I am now convinced it is just not worth the code size hit to provide this info.

**Comment by natebosch** [comment]
`--emit-metadata` makes the SDK ~24% bigger so it's probably not something we'd want to turn on there...

**Comment by natebosch** [comment]
We'll avoid this for now and wait for a motivating use case to come up.
