### ISSUE TITLE
Analyzer auto-completes args with non-idiomatic code

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#37073]
```
$ flutter --version

Flutter 1.6.0 • channel dev • git@github.com:flutter/flutter.git
Framework • revision ed90d05596 (9 days ago) • 2019-05-14 17:09:29 -0700
Engine • revision 832cdacc6f
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
```

From what I can tell, there is some special-cased code for Flutter's `Widget`?

For example, if I write:

```dart
import 'package:flutter/material.dart';

class HasNamedArgs {
  final List<String> args;
  HasNamedArgs({this.args});
}

void main() {
  HasNamedArgs(^)
}
```

... it is auto-completed as:

```dart
void main() {
  HasNamedArgs(args: )
}
```

But if I write:

```dart
import 'package:flutter/material.dart';

class HasNamedArgs extends StatelessWidget {
  final List<Widget> children;
  const HasNamedArgs({this.children});
}

void main() {
  HasNamedArgs(^)
}
```

... it is auto-completed as:

```dart
void main() {
  HasNamedArgs(children: <Widget>[],)
}
```

This is a really strange style for Dart 2.x, at least by default, because reified types and type inference says that the `List<Widget> children` _must_ be a `List<Widget>`. I would have expected to see it auto-complete as:

```dart
void main() {
  HasNamedArgs(children: [],)
}
```

... instead. (I realize this is not the style the [Flutter SDK](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-using-var) wants to use, but that isn't 99.9% of users, and this goes against the style guide otherwise).

**Comment by DanTup** [comment]
This appears to be fixed by #41303 / 1e4a56ee720218ae82af13a9cf71e038b0884cfc. In VS Code on current master, it completes as suggested (`children: []`) without the type.
