### ISSUE TITLE
IDE does not Identify folders generated under .dart_tool/generated/project/test

### ISSUE THREAD

**Issue by humblerookie** [dart-lang/sdk#37087]
IDE Intellij isn't able to identify files generated  via `flutter generate` (`build runner`)under the test folder. Seems to be an issue with dart so raising the same here as requested.

The generated classes under test aren't recognized, however classes under lib folder are.

Dart version: 2.3.0
OS: Mac 10.13.6 
Intellij : 2018.2.7

Relevant issue on flutter with all details [Issue](https://github.com/flutter/flutter/issues/33266)

Kindly let me know if you need more info.

cc: @jonahwilliams

**Comment by humblerookie** [comment]
Does this need more input? @irhn

**Comment by humblerookie** [comment]
@Irhn any updates on this issue?

**Comment by lrhn** [comment]
I'm not working on the analyzer, so I am not the one to answer that.
Let's see if we can attract some analyzer developers.

**Comment by bwilkerson** [comment]
@stereotype441 @scheglov

**Comment by srawlins** [comment]
Sorry for the 5-year delay; we've changed how generated files work and package configs, a far bit in the meantime. If you are still having this issue in a recent Dart and Flutter version, please re-open.
