### ISSUE TITLE
Dart VM C API should include equivalent of Isolate.kill

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37081]
In Dart code users are both capable of starting and killing isolates. However in there is no equivalent for that in native code. 

This is needed for embedders which want to safe guard against long running (infinite) loops in Dart code.

**Comment by mraleph** [comment]
@a-siva @rmacnak-google Ryan, Siva - any concerns about adding such API?

**Comment by rmacnak-google** [comment]
SGTM

Compare Dart_NotifyLowMemory, which uses isolate control messages to trigger compaction.
