### ISSUE TITLE
Fasta should support >>> with --enable-experiment=triple-shift

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#37082]
Fasta seems to have support for `>>>` conditioned on the experimental flag `constant-update-2018` but it is an independent experiment.

It appears that tests enabling `triple-shift` but not `constant-update-2018` have compile time errors due to the `>>>` operator.

/cc @askeksa-google @danrubel

**Comment by askeksa-google** [comment]
Fix is here: https://dart-review.googlesource.com/c/sdk/+/104004
