### ISSUE TITLE
Add support for aarch64/armhf architectures

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/sdk#37094]
Currently dart support x86 x64 arm and maybe more architectures types.
Can you add support for aarch64 and armhf(aarch32)?
Example device that use aarch64 is NanoPi NEO2.
Example device that use armhf is NanoPi NEO.

**Comment by mraleph** [comment]
Dart supports aarch64 and armhf, so it should run on both of these devices just fine. 

Though you need to crosscompile it, rather than build it on the device.
