### ISSUE TITLE
Dart Analysis error

### ISSUE THREAD

**Issue by msc4266** [dart-lang/sdk#37096]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7141.44`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IC-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, FATAL error: NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'SimpleToken'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:579:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://T:\temp\report1.txt.

**Comment by msc4266** [comment]
I got this when a file (edited with IntelliJ) had an invisible NUL at the end. I don't know how this happened. Anyways, I opened the file with VS Code, where I could see and remove the [NUL] character at the end.

**Comment by a-siva** [comment]
Dumping priority to P1 as it has been seen multiple times.

**Comment by srawlins** [comment]
This has been seen as recently as Dart 2.4.1.

**Comment by srawlins** [comment]
Dart 2.3 and 2.4 were released over 6 months ago; please upgrade Dart (or Flutter) to a recent version. Feel free to re-open this issue if it occurs again.
