### ISSUE TITLE
Isolate and IsolateRef VM impls return object with 'fixedId' fields, but those fields are not defined in the spec

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37107]
Isolate and IsolateRef VM impls return object with 'fixedId' fields, but those fields are not defined in the spec. See this PR: https://github.com/dart-lang/vm_service_drivers/pull/220/commits/ab1fa1677f7f91727642a7b067bf3eb15cf92410#diff-68936077052390239c77a3732f47e9ccR2058, which adds temporary field definitions to the copy of the spec we generate code from.

We'd either want to add `fixedId` to the two classes in the spec, or possibly change the parent classes to ones that already include `fixedId` (`ObjRef`?).

**Comment by rmacnak-google** [comment]
The service protocol specification is not an IDL, and we do not support using to generate a client library.

The service implementation is free to include extra fields in responses that are not required by the spec. Such fields may be removed without notice.

**Comment by devoncarew** [comment]
Ryan, Ben had asked me to open this issue in order to track extra `fixedId` fields I'd seen.

> The service protocol specification is not an IDL, and we do not support using to generate a client library.

Our important, customer facing tools (the Dart IntelliJ plugin, the Flutter IntelliJ plugin, and DevTools) are built on libraries that use the service protocol doc this way - as a parsable doc. We need those tools to continue to work, and to be able to consume an evolving service protocol API. If for some reason it's a non-goal that the spec be parsable, that likely needs to change. It's minimal work - since the spec is already parsable - and an important use case for our tools.

> The service implementation is free to include extra fields in responses that are not required by the spec. Such fields may be removed without notice.

I have no issue with that. We can work around these extra fields easily in the generator. In this case, I wanted to call them out, to ensure that it was intentional that they weren't documented, or weren't a sign of a modeling issue in the spec.
