### ISSUE TITLE
Remove RawInstructions::stats_

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#37103]
The CodeStatistics in RawInstructions needs to be removed. It used to hide in an alignment gap, but another field has been added to RawInstructions so that's no longer true.

**Comment by mraleph** [comment]
Could you clarify:

```cpp
class RawInstructions : public RawObject {
  RAW_HEAP_OBJECT_IMPLEMENTATION(Instructions);
  VISIT_NOTHING();

  // Instructions size in bytes and flags.
  // Currently, only flag indicates 1 or 2 entry points.
  uint32_t size_and_flags_;
  uint32_t unchecked_entrypoint_pc_offset_;

#if defined(DART_PRECOMPILER)
  // There is a gap between size_and_flags_ and the entry point
  // because we align entry point by 4 words on all platforms.
  // This allows us to have a free field here without affecting
  // the aligned size of the Instructions object header.
  // This also means that entry point offset is the same
  // whether this field is included or excluded.
  CodeStatistics* stats_;
#endif
```

I count max 3 words here on 32-bit platform: header, size_and_flags_, unchecked_entrypoint_pc_offset_. On 64-bit I count two words: header and size_and_flags_ + unchecked_entrypoint_pc_offset_. Which leaves space for stats_. 

Maybe I am counting wrong.

**Comment by liamappelbe** [comment]
That makes sense. Maybe the comment isn't wrong. But the fact that it's conditional on the precompiler is preventing me from extracting of the sizeof to a constant. Maybe it's sufficient to just make this field unconditional.

@rmacnak-google WDYT?

**Comment by rmacnak-google** [comment]
@liamappelbe SGTM

Long term I'd like to move stats_ to a side table so the code alignment can be reduced.

**Comment by mraleph** [comment]
removed by @rmacnak-google
