### ISSUE TITLE
Parser does not allow `!` before `.` (NNBD)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#37111]
With `--enable-experiment=non-nullable`, the following code has a parse error:
```dart
class A {
  int? b = 1;
}
main() {
  var a = A();
  print(a!.b); // ERROR: Expected to find ')'
}
```

Note: I discovered this while trying to confirm whether we support `!` in cascade expressions, e.g. `a..foo()!.bar=3;` (see discussion at https://github.com/dart-lang/language/pull/293#discussion_r288360213).  So we should double check this case too when fixing the bug.

**Comment by stereotype441** [comment]
@danrubel

**Comment by eernstg** [comment]
Also note that [this CL](https://dart-review.googlesource.com/c/sdk/+/101500) contains a Dart.g grammar file that builds on one of Lasse's proposals to include support for `!` as a selector.

This means that there is a complete grammar for the NNBD syntax (so any conflicts with the rest of the language would come up), and also that it's possible to experiment with it.

**Comment by danrubel** [comment]
The current implementation treats `?.` as a single token meaning that 
```
  var foo = bar?.name;  // <--- valid - no space between ? and .
  var foo = bar? .name; // <--- invalid - space between ? and .
```
Should we do the same for `!.` so that it's consistent?

**Comment by bwilkerson** [comment]
No. The '!' operator is a postfix operator, and doesn't need to be followed by a period:
```
int x = y!;
```
The expression `x!.y` is equivalent to `x! . y` or even `(x!).y`.
