### ISSUE TITLE
Add predicate-parameterized search functions to List: indexOfMatch/lastIndexOfMatch

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#3711]
When we call indexOf/lastIndexOf on our list implementations, we let the elements in the list dictate if they are equals to the &quot;thing&quot; we're searching for. I find that a bit counterintuitive. I'd prefer if we always asked the thing we're searching for if it feels like it's equal to the elements like this:

``` dart
class Yes { operator==(other) => true; }
var list = [ 1, 2, 3 ];
Expect.equals(0, list.indexOf(new Yes()));
Expect.equals(2, list.lastIndexOf(new Yes()));
```

**Comment by floitschG** [comment]
Closing as dupe of #30275.
