### ISSUE TITLE
Converting a class to a mixin caused a 1-3% increase in read only snapshot size.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#37126]
Why did [this change] cause a 1%-3% regression several of Flutter's regression tests? The tests are all readonly data size tests. It's simply moving the implementation of a class into a mixin.

Essentially, the change was:

Before:
```dart
class Diagnosticable {
  const Diagnosticable();
  // ... functions
}
```
And now it's:
```dart
class Diagnosticable with DiagnosticableMixin {
  const Diagnosticable();
}

mixin DiagnosticableMixin {
  // ... funtions
}
```

Attached are two snapshot heap dumps: one before the change, and one after.  I wasn't able to get them to load in Chrome's dev tools but the data is there, at least.

[heap_snapshots.zip](https://github.com/dart-lang/sdk/files/3239004/heap_snapshots.zip)

Snapshot size of Flutter Gallery app before (f38ee1528):
app.dill: 21014104
isolate_snapshot_data: 4152976
isolate_snapshot_instr: 7263408

Snapshot size of Flutter Gallery app after (c7c0965cc):
app.dill: 21021520 (0.03% increase)
isolate_snapshot_data: 4232280 (1.9% increase)
isolate_snapshot_instr: 7279664 (0.2% increase)

Version: Dart VM version: 2.3.2-dev.0.0.flutter-fee615c5a5 (Tue May 28 17:01:16 2019 +0000) on "linux_x64"

[this change]:https://github.com/flutter/flutter/commit/c7c0965cc593578e036a504f4de4617380902b2c

**Comment by gspencergoog** [comment]
cc @mraleph

**Comment by mraleph** [comment]
@sjindel-google could you help @gspencergoog here? It would be great to make our tooling work for such use cases so that Flutter devs could easily explain the size difference from their changes.

**Comment by sjindel-google** [comment]
It looks like the tests for this feature, `vm/dart/v8_snapshot_profile_writer`, was disabled in https://dart-review.googlesource.com/c/sdk/+/95040, along with all `vm/dart` tests in precompiled mode.

**Comment by sjindel-google** [comment]
Besides our test being broken now, Chrome's snapshot format appears to have changed.

**Comment by rmacnak-google** [comment]
The snapshots can also be visualized with https://github.com/dart-lang/sdk/blob/master/runtime/tools/graphexplorer/graphexplorer.html

**Comment by sjindel-google** [comment]
Here are updated snapshots:

[Archive.zip](https://github.com/dart-lang/sdk/files/3263687/Archive.zip)

The comparison view in Chrome DevTools shows that, among other things, there are a lot of `Function`s being retained now -- although there is only one more `Instructions` than before. I'll keep digging.

**Comment by sjindel-google** [comment]
I have identified the root cause of the problem -- the V8 snapshots were super helpful!

The "Summary" view from Chrome DevTools shows that 153 new `Function` objects were introduced. Unfortunately the "Comparison" view doesn't produce reliable results, because the object IDs are not stable across precompilation of different sources, but a simple script (
[main.dart.txt](https://github.com/dart-lang/sdk/files/3276193/main.dart.txt)
) shows that all the new `Function`s are constructors, for example:

```
> [Class] _TabStyle@378014024::[Function] _TabStyle@378014024. [Constructor]
14227a14376
> [Class] Texture::[Function] Texture. [Constructor]
14304a14454
> [Class] TickerMode::[Function] TickerMode. [Constructor]
14524a14675
> [Class] Transform::[Function] Transform. [Constructor]
14702a14854
> [Class] UnconstrainedBox::[Function] UnconstrainedBox. [Constructor]
15071a15224
> [Class] Viewport::[Function] Viewport. [Constructor]
```

The "Retainers" view shows why the `Viewport` constructor was kept in the "after" snapshot:

![devtools](https://user-images.githubusercontent.com/29863079/59267579-e6d99b00-8c4a-11e9-8828-a995ccde6e59.png)

This suggests that some inlining decisions changed, and the disassembly for the `Viewport` constructor confirms this.

Before:
```
*** BEGIN CFG
After AllocateRegisters
==== package:flutter/src/widgets/nested_scroll_view.dart__NestedScrollViewCustomScrollView@514016527_buildViewport
  0: B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>) T{_OneByteString}
}
  2: B1[function entry]:2 {
      v2 <- Parameter(0) T{_NestedScrollViewCustomScrollView}
      v3 <- Parameter(1) T{BuildContext?}
      v4 <- Parameter(2) T{ViewportOffset?}
      v5 <- Parameter(3) T{AxisDirection?}
      v6 <- Parameter(4) T{_GrowableList}
}
  4:     CheckStackOverflow:8(stack=0, loop=0)
  6:     v7 <- AllocateObject(NestedScrollViewViewport) T{NestedScrollViewViewport}
  7:     ParallelMove r0 <- r0
  8:     ParallelMove S-1 <- r0
  8:     PushArgument(v7)
 10:     PushArgument(v5)
 12:     PushArgument(v4)
 14:     PushArgument(v6)
 15:     ParallelMove r1 <- S+6
 16:     v9 <- LoadField(v2 . handle {final}) T{SliverOverlapAbsorberHandle}
 18:     PushArgument(v9)
 20:     StaticCall:14( NestedScrollViewViewport.<0> v7, v5, v4, v6, v9)
 21:     ParallelMove r0 <- S-1
 22:     Return:18(v7)
*** END CFG
```

After:
```
*** BEGIN CFG
After AllocateRegisters
==== package:flutter/src/widgets/scroll_view.dart_ScrollView_buildViewport
  0: B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>) T{_OneByteString}
      v9 <- Constant(#true) T{bool}
      v42 <- Constant(#_ImmutableList len:16) T{_ImmutableList}
      v59 <- Constant(#_ImmutableList len:10) T{_ImmutableList}
      v70 <- Constant(#_ImmutableList len:8) T{_ImmutableList}
      v89 <- Constant(#_ImmutableList len:6) T{_ImmutableList}
}
  2: B1[function entry]:2 {
      v2 <- Parameter(0) T{ScrollView}
      v3 <- Parameter(1) T{BuildContext?}
      v4 <- Parameter(2) T{ViewportOffset?}
      v5 <- Parameter(3) T{AxisDirection?}
      v6 <- Parameter(4) T{_GrowableList}
}
  4:     CheckStackOverflow:8(stack=0, loop=0)
  5:     ParallelMove r0 <- S+6
  6:     v7 <- LoadField(v2 . shrinkWrap {final}) T{bool}
  8:     Branch if StrictCompare:16(===, v7, v9) goto (3, 4)
 10: B3[target]:20 ParallelMove r2 <- S+4, r1 <- S+3, r0 <- S+2
 12:     v18 <- AllocateObject(ShrinkWrappingViewport) T{ShrinkWrappingViewport}
 13:     ParallelMove r1 <- r0, r0 <- S+3
 14:     ParallelMove S-1 <- r1
 14:     StoreInstanceField(v18 . axisDirection = v5 T{AxisDirection?}, barrier removed)
 16:     StoreInstanceField(v18 . crossAxisDirection = v0, barrier removed)
 17:     ParallelMove r2 <- S+4
 18:     StoreInstanceField(v18 . offset = v4 T{ViewportOffset?}, barrier removed)
 19:     ParallelMove r3 <- S+2
 20:     StoreInstanceField(v18 . children = v6, barrier removed)
 22:     StoreInstanceField(v18 . key = v0, barrier removed)
 24:     PushArgument(v18)
 26:     StaticCall:12( _Diagnosticable&Object&DiagnosticableMixin@260198569.<0> v18)
 27:     ParallelMove r0 <- S-1
 28:     Return:26(v18)
 30: B4[target]:28 ParallelMove r2 <- S+4, r1 <- S+3, r3 <- S+2
 32:     v10 <- AllocateObject(Viewport) T{Viewport}
 33:     ParallelMove r1 <- r0, r0 <- S+6
 34:     ParallelMove S-4 <- r1
 34:     v12 <- LoadField(v2 . cacheExtent {final}) T{Null?}
 35:     ParallelMove S-3 <- r2
 36:     v14 <- LoadField(v2 . center {final}) T{Null?}
 37:     ParallelMove S-2 <- r3
 38:     v16 <- LoadField(v2 . anchor {final}) T{_Double}
 39:     ParallelMove r0 <- S+3, S-1 <- r4
 40:     StoreInstanceField(v10 . axisDirection = v5 T{AxisDirection?}, barrier removed)
 42:     StoreInstanceField(v10 . crossAxisDirection = v0, barrier removed)
 44:     StoreInstanceField(v10 . anchor = v16, barrier removed)
 45:     ParallelMove r6 <- S+4
 46:     StoreInstanceField(v10 . offset = v4 T{ViewportOffset?}, barrier removed)
 48:     StoreInstanceField(v10 . center = v14, barrier removed)
 50:     StoreInstanceField(v10 . cacheExtent = v12, barrier removed)
 51:     ParallelMove r7 <- S+2
 52:     StoreInstanceField(v10 . children = v6, barrier removed)
 54:     StoreInstanceField(v10 . key = v0, barrier removed)
 56:     PushArgument(v10)
 58:     StaticCall:12( _Diagnosticable&Object&DiagnosticableMixin@260198569.<0> v10)
 59:     ParallelMove r0 <- S-4
 60:     Return:40(v10)
*** END CFG
```

The `StaticCall` introduced into `buildViewport` is significant, because functions with no calls in them (or other instructions which can cause an exception to be thrown) don't need code source maps -- hence the increase in RO data size.

This is likely an artifact of our implementation of mixins, which adds an additional class to the class hierarchy above the class incorporating the mixin. The extra constructor added to the chain appears to have adversely affected the inliner's decisions.

@aartbik : How might we resolve this?

**Comment by aartbik** [comment]
I will have a look, also in combination with a few i's to dot in the heuristics after my last CL.

**Comment by aartbik** [comment]
@sjindel-google can you elaborate a bit more on your previous note, which seems to compare

`NestedScrollViewCustomScrollView@514016527_buildViewport`
with
`scroll_view.dart_ScrollView_buildViewport`

Is that intentional? I am not sure how you get to the inline heuristics conclusions by comparing  buildViewport from two different classes?

**Comment by sjindel-google** [comment]
Sorry, I copy-pasted the disassembly for the wrong function into my comment. I've updated it.

The change to this one function is significant because it's called from many other subclass constructors, all of which now have this extra `StaticCall` inside them when they didn't have any calls before, forcing the creation of a code source maps for many constructors.

**Comment by aartbik** [comment]
@sjindel-google thanks for updating the comment, now it is much more clear!

**Comment by aartbik** [comment]
I made a small reproducer that illustrates it all. In the following, the static method foo() is fully optimized (returning 1). However, the static method bar() suffers from the extra indirection of the mixin construction. Onwards to a fix!

```dart
class X {
  const X();
  int foo() { return 1; }
}

mixin YMixin {
  int bar() { return 2; }
}

class Y with YMixin {
  const Y();
}

@pragma("vm:never-inline")
int foo() {
  var x = new X();
  return x.foo();
}

@pragma("vm:never-inline")
int bar() {
  var y = new Y();
  return y.bar();
}

```

**Comment by aartbik** [comment]
I have an improved heuristic that includes the mixin construction in the inliner. This brings back the relative sizes closely to where they were before, with no other regressions.

```
head:

VMIsolate(CodeSize): 4737
Isolate(CodeSize): 2005123                     101%
ReadOnlyData(CodeSize): 2212408                103%  
Instructions(CodeSize): 7006928                100%
Total(CodeSize): 11229196                      101%

improved heuristic:

VMIsolate(CodeSize): 4737
Isolate(CodeSize): 1985691
ReadOnlyData(CodeSize): 2152880
Instructions(CodeSize): 6987616
Total(CodeSize): 11130924

head:

Inlining into: 'package:flutter/src/widgets/scroll_view.dart_ScrollView_buildViewport'
     growth: 2.041667 (24 -> 49)
   32 Viewport.Viewport.
     240 MultiChildRenderObjectWidget.MultiChildRenderObjectWidget.
       96 RenderObjectWidget.RenderObjectWidget.
         72 Widget.Widget.
           72 DiagnosticableTree.DiagnosticableTree.
             10 Diagnosticable.Diagnosticable.
   20 ShrinkWrappingViewport.ShrinkWrappingViewport.
     168 MultiChildRenderObjectWidget.MultiChildRenderObjectWidget.
       96 RenderObjectWidget.RenderObjectWidget.
         72 Widget.Widget.
           72 DiagnosticableTree.DiagnosticableTree.
             10 Diagnosticable.Diagnosticable.

improved heuristic:

Inlining into: 'package:flutter/src/widgets/scroll_view.dart_ScrollView_buildViewport'
     growth: 2.125000 (24 -> 51)
   32 Viewport.Viewport.
     240 MultiChildRenderObjectWidget.MultiChildRenderObjectWidget.
       96 RenderObjectWidget.RenderObjectWidget.
         72 Widget.Widget.
           72 DiagnosticableTree.DiagnosticableTree.
             10 Diagnosticable.Diagnosticable.
               10 _Diagnosticable&Object&DiagnosticableMixin@262198569._Diagnosticable&Object&DiagnosticableMixin@262198569.
   20 ShrinkWrappingViewport.ShrinkWrappingViewport.
     168 MultiChildRenderObjectWidget.MultiChildRenderObjectWidget.
       96 RenderObjectWidget.RenderObjectWidget.
         72 Widget.Widget.
           72 DiagnosticableTree.DiagnosticableTree.
             10 Diagnosticable.Diagnosticable.
               10 _Diagnosticable&Object&DiagnosticableMixin@262198569._Diagnosticable&Object&DiagnosticableMixin@262198569.


```
