### ISSUE TITLE
AnalysisServer's 'Move File' refactoring doesn't update URIs in part-files

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#37121]
Create `foo.dart` file
```
part 'foo_part.dart';
```
and `foo_part.dart` file next to it:
```
part of 'foo.dart';
```
Move `foo.dart` file to a subfolder, update files content using Analysis Server `"MOVE_FILE"` refactoring (supported in IntelliJ IDEA 2019.2 but not yet in publicly available releases).
- URI in the `foo.dart` file is correctly updated -- that's ok.
- Problem: URI in the `foo_part.dart` file is NOT updated.

**Comment by bwilkerson** [comment]
@jwren

**Comment by jwren** [comment]
Fail test added in this PR: https://dart-review.googlesource.com/c/sdk/+/106981

**Comment by jwren** [comment]
I expected to have the addition of in `index.dart` have the additional search reference from the index, but it still does not.

```
@override
  visitPartOfDirective(PartOfDirective node) {
    Element element = node.element;
    if(element is LibraryElement) {
      CompilationUnitElement compilationUnitElement = element.definingCompilationUnit;
      if(compilationUnitElement.source != null) {
        if(node.uri != null) {
          recordUriReference(compilationUnitElement, node.uri);
        }
      }
    }
    super.visitPartOfDirective(node);
  }
```

**Comment by jwren** [comment]
Resolved in master Dart SDK branch with https://dart-review.googlesource.com/c/sdk/+/107200
