### ISSUE TITLE
No static error when iterating over a generic type, T.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#37125]
```dart
void main() {
  example1(5);
  example2(3);
}

void example1<T>(T item) {
  // No static error.
  // Runtime error (in Dart2JS):
  // TypeError: 5: type 'JSInt' is not a subtype of type 'Iterable'
  for (final x in item) {
    print(x);
  }
}

void example2<T>(T item) {
  // Static error: The method 'iterator' isn't defined for the class 'Object'.
  final iterator = item.iterator();
  while (iterator.moveNext()) {
    print(iterator.current);
  }
}
```

I'd expect the same or similar error in both cases.

/cc @leafpetersen

**Comment by vsmenon** [comment]
@leafpetersen @lrhn - is this a language issue or an implementation one?  Right now, it looks like none of the implementations report a static error for the `for`.

**Comment by vsmenon** [comment]
Issue moved to [dart-lang/language #383](https://github.com/dart-lang/language/issues/383) via [**ZenHub**](https://www.zenhub.com/)

**Comment by leafpetersen** [comment]
I commented on the language issue - this seems pretty clearly an implementation bug to me.  The spec is unusually clear here, and I can't see any way it allows this.

Probably this should just be fixed as part of the NNBD implicit cast elimination though.

**Comment by natebosch** [comment]
@leafpetersen - We expect a static error for argument type `T`. What do we expect for argument type `Object`?

**Comment by leafpetersen** [comment]
Unfortunately, `Object` is explicitly carved out as permitted by the spec.  :(

The no implicit cast/NNBD release should fix this.

**Comment by vsmenon** [comment]
Assigning to both front ends.  It probably does make sense to fix as part of NNBD.  That said, it doesn't appear to be marked as an implicit cast by the analyzer right now - i.e., no static error with `--no-implicit-cast`.

**Comment by srawlins** [comment]
`dartanalyzer --enable-experiment=non-nullalbe` reports correctly:

```
  error • An expression whose value can be 'null' must be null-checked before it can be dereferenced. • 37125.dart:10:19 • unchecked_use_of_nullable_value
  error • The type 'Object' used in the 'for' loop must implement Iterable. • 37125.dart:10:19 • for_in_of_invalid_type
  error • The method 'iterator' isn't defined for the type 'Object'. • 37125.dart:17:25 • undefined_method
3 errors found.
```
