### ISSUE TITLE
Article on convertors and codecs missing

### ISSUE THREAD

**Issue by duncanmak** [dart-lang/sdk#37124]
https://dart.dev/articles/libraries/converters-and-codecs is current a dead page.

Maybe it should be resurrected.

Currently, there's a cache of the page (with the old page layout) here: http://web.archive.org/web/20190402212224/https://www.dartlang.org/articles/libraries/converters-and-codecs#how-to-write-efficient-conversions.

cc @sortie, he asked me to file an issue on IRC.

**Comment by vsmenon** [comment]
@kwalrath

**Comment by kwalrath** [comment]
Issue moved to [dart-lang/site-www #1649](https://github.com/dart-lang/site-www/issues/1649) via [**ZenHub**](https://www.zenhub.com/)
