### ISSUE TITLE
Document HttpClientResponseCompressionState in changelog

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37128]
We should document all changed APIs. Should mention HttpClientResponseCompressionState was added!

**Comment by tvolkert** [comment]
It's already done - https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#dartio

I may be missing something...

**Comment by aadilmaan** [comment]
Can we consider this closed based on Todd's comment above?

**Comment by kevmoo** [comment]
Document the fact there is a new enum – that's not clear from the changelog.

**Comment by tvolkert** [comment]
https://dart-review.googlesource.com/c/sdk/+/104282

**Comment by tvolkert** [comment]
Fixed.
