### ISSUE TITLE
Should we be using the internal `Since` annotation for new features?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37127]
https://github.com/dart-lang/sdk/blob/a25f927ba9b758b9648d4b375a8fcee84b28f78d/sdk/lib/internal/internal.dart#L200-L204

aa2ce7cfbf just landed `HttpClientResponse. compressionState` and `HttpClientResponseCompressionState`

Should these be annotated w/ `Since`? @lrhn @turnidge @zanderso 

Should we look to get Analyzer to support `Since` so it's useful for end users? @stereotype441 @devoncarew @bwilkerson

**Comment by kevmoo** [comment]
Ditto for

* `dart:developer` in I33b8324e9c16fb12e80dd91beb275320b64f7316 
* new RegExp features in 4028fec3b56703752dbab6b5d5647fb9ac204774

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by kevmoo** [comment]
Ditto for `dart:isolate` debug name - ac2c934563fb10a0033612821e595894bcf9ded9

**Comment by zanderso** [comment]
@turnidge's input would surely be invaluable, but @tvolkert is probably the more correct Todd in this case.

**Comment by lrhn** [comment]
True, we should use it. If for nothing else, then for documentation.

**Comment by tvolkert** [comment]
`HttpClientResponse.compressionState` and `HttpClientResponseCompressionState` are done as of https://github.com/dart-lang/sdk/commit/ebbfc7d8ca5366888b832cf83ee0df49e8f1b745

**Comment by lrhn** [comment]
For the record, new features should be releases in minor version increments, so the next release where new features are released will be `2.4.0`. 

If we release a `2.3.2`, it will be a patch/bug-fix release cherry-picked from head, and it will most likely not contain any of the new features.
So, for not-yet-released features, the annotations should be `@Since("2.4.0")`.

**Comment by devoncarew** [comment]
I think the sdk version doesn't follow strict semver, and won't always rev the minor version even when there are api additions (reving the sdk version is more of a product decision than a semver one).

**Comment by lrhn** [comment]
We should generally use `Since` on new features.
