### ISSUE TITLE
Donate dart lang to apache foundation or eclipse foundation or linux cncf foundation?

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#37139]
learn dart lang for a year. like dart lang very much. 
But still worry about the future of dart lang.
why not donate dart lang to an opensource foundation, like (apache, eclipse , linux cncf)

The kubernetes was born in google, then became a linux cncf foundation project.

dart lang should be more popular and more open , if it was an open source foundation project.

Currently, it was only a google project, we can not know where it will goes. the future not very clear and stable.

Google close many project/product year by year. will dart lang be cut off?
Have no idea.

**Comment by devoncarew** [comment]
Hmm, I'm not sure what the best forum for this question is. Perhaps as an email to the discuss group (https://groups.google.com/a/dartlang.org/forum/#!forum/misc)?

cc @timsneath

**Comment by devoncarew** [comment]
> learn dart lang for a year. like dart lang very much.

@netroby, thanks for the feedback!

I'm going to close this issue, but feel free to ask your question on above discussion group.

**Comment by netroby** [comment]
@devoncarew ， Did you affected by Google fire it's employee of Python,Flutter and Dart team?

Any reconsider donate dart lang to a third standalone foundation, like apache, eclipse.

Or google just will shutdown Dart, Flutter, and other useless team.
