### ISSUE TITLE
dart2aot: fails to run from spaces in path name

### ISSUE THREAD

**Issue by idraper** [dart-lang/sdk#37130]
Dart SDK Version: Dart VM version: 2.3.1
OS: Windows 10

I did a raw install (completely uninstalled v2.2) to get version 2.3 to try and use the dart2aot tool as shown [here](https://dart.dev/tools/dart2aot).

```
// bin/main.dart
void main() => print('Hello World');
```

Running `dart bin/main.dart` output:
```
Hello World
```
as expected

Running `dart2aot bin/main.dart bin/main.dart.aot` gave the following error:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
As you'd expect, Dart is installed in the path `C:\Program Files\...` and the space was giving it a problem.

I was able to solve the problem by editing `dart2aot.bat` file directly by including quotes around the file paths.

Specifically, I changed:
```
REM Step 1: Generate Kernel binary from the input Dart source.
%DART% %GEN_KERNEL% --platform %VM_PLATFORM_STRONG% --aot -Ddart.vm.product=true -o %SNAPSHOT_FILE%.dill %SOURCE_FILE%

REM Step 2: Generate snapshot from the Kernel binary.
%GEN_SNAPSHOT% %GEN_SNAPSHOT_OPTION% %GEN_SNAPSHOT_FILENAME% %SNAPSHOT_FILE%.dill
```
to be:
```
REM Step 1: Generate Kernel binary from the input Dart source.
"%DART%" "%GEN_KERNEL%" --platform "%VM_PLATFORM_STRONG%" --aot -Ddart.vm.product=true -o "%SNAPSHOT_FILE%.dill" "%SOURCE_FILE%"

REM Step 2: Generate snapshot from the Kernel binary.
"%GEN_SNAPSHOT%" %GEN_SNAPSHOT_OPTION% "%GEN_SNAPSHOT_FILENAME%" "%SNAPSHOT_FILE%.dill"
```
After editing, both `main.dart.aot` and `main.dart.aot.dill` are generated.

---
Then, after running `dartaotruntime bin/main.dart.aot` it works as expected, printing out the same as when running from the `dart` command.

**Comment by vsmenon** [comment]
@mit-mit @mraleph - should dart2aot issues be labeled as vm?

**Comment by mraleph** [comment]
I guess we have no better label for these right now.

**Comment by mraleph** [comment]
Assigning to @cskau-g

**Comment by nex3** [comment]
This is important for Sass as well; we'd like to transition our Chocolatey installation to AOT-compile the application at install time as a workaround for #28617, but if `dart2aot` can't reliably be run from a common Windows installation directory then that won't work.

**Comment by cskau-g** [comment]
This issue should be resolved with dart2native having replaced dart2aot.
