### ISSUE TITLE
dart/entrypoints/jit tests are overly sensitive to usage counters

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#37144]
These tests are disabled in https://dart-review.googlesource.com/c/sdk/+/102820 because of changes in the way the usage counter is incremented.

**Comment by mkustermann** [comment]
The CL which is up for review wants to `dart/entrypoints/jit: Skip`. This would make our checked/unchecked entrypoint functionality untested. It was introduced to bypass Dart 2.0 type checks on function entry if it's safe, which gave - as far as I've been told - significant performance improvements.

Can you elaborate why exactly they will be skipped and if there's a plan to enable them again?

**Comment by sjindel-google** [comment]
I think we should just emit the unchecked calls in optimized and unoptimized code. I can't see a reason to not do it in unoptimized code.

This would make the tests completely insensitive to usage counters.

**Comment by sjindel-google** [comment]
It turns out this requires updating all the IC stubs
