### ISSUE TITLE
VM generated ELF binaries and Android's strip don't work together

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#37146]
Android build scripts will run `strip --strip-unneeded` by default, and this breaks ELF binaries generated by the VM.

@jason-simmons reports that nm on these binaries gives errors like

```
    arm-linux-androideabi-nm: foo.so: attempt to load strings from a
non-string section (number 0)
```

and all the symbols had null names:
```
    00000000 T (null)
```

It sounds like `strip` is assuming that debug sections do not share a string table with runtime sections, but VM generated ELF binaries use a single string table for everything. We should try generating separate string tables.

**Comment by sjindel-google** [comment]
A similar issue was the root cause of https://github.com/flutter/flutter/issues/41010
