### ISSUE TITLE
VSCode doesn't pick up 'dart:ffi' imports

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37141]
I'm reproduced this with the head of Flutter and the latest rolled SDK.

The VSCode config contains this:

```
    "dart.sdkPath": "<home path>/src/flt/engine/flutter/bin/cache/dart-sdk",
    "dart.flutterSdkPath": "<home path>/src/flt/engine/flutter"
```

An import of 'dart:ffi' in any Dart file will cause an analyzer error.

**Comment by dcharkes** [comment]
In my VSCode, with the Dart sdk on my path, the imports resolve fine in the Dart editor. Is the dart-sdk which is shipped with Flutter pruned of hidden libraries? dart:ffi is excluded from docs by https://github.com/dart-lang/sdk/commit/61eae93462919fada27cfe68ce7378acacf2574b.

**Comment by luca992** [comment]
Also can't get the import to resolve in android studio
