### ISSUE TITLE
 Option for setting minimum TLS version (TLS1.2)

### ISSUE THREAD

**Issue by sedem7** [dart-lang/sdk#37157]
Some online REST services, that uses private keys for authentication (*.p12 for same State and Government services) are using TLS1.2 as minimum protocol version. Dart always make initial “Client Hello” with TLS 1.0 header with set of 15 chipers. As a result, not strong enough chipper is used by “Server Hello” and “SSLV3_ALERT_HANDSHAKE_FAILURE(tls_record.cc:586)” is thrown.

If same test is done with Java where minimum protocol is set to TLS 1.2, a set of 45 chipers is allowed for connection and chipper TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f) is selected. Connection is successful. 

Dart version: 2.3.0
OS: Windows 10

**Comment by sortie** [comment]
What's the difference between this issue and <https://github.com/dart-lang/sdk/issues/37173>?

**Comment by sedem7** [comment]
Same as #37173
