### ISSUE TITLE
[Analyzer] Incorrect ElementVisitor documentation

### ISSUE THREAD

**Issue by kuanfajardo** [dart-lang/sdk#37151]
Dart Version: 2.3.0-dev.0.5
Machine: N/A
Browser: N/A

The `ElementVisitor` [documentation](https://pub.dev/documentation/analyzer/latest/dart_element_element/ElementVisitor-class.html) gives examples of concrete implementations of `ElementVisitor`. However, it incorrectly states that these classes are located in `package:analyzer/dart/ast/visitor.dart`:

![image](https://user-images.githubusercontent.com/19846915/58838987-811f5a80-861d-11e9-9237-b5b67834a7a4.png)
 
The actual location of these classes is in `package:analyzer/dart/element/visitor.dart`. Updating this shouldn't be a problem.

This error is likely due to there being two `visitor` libraries within the `analyzer` package; one of these is the concrete implementation of AST visitors, the other of Element visitors (which at first glance looks like a duplicate, not a completely different library!)

![image](https://user-images.githubusercontent.com/19846915/58839121-01de5680-861e-11e9-83f0-2b30fb0196bb.png)

I propose for some differentiation between the two libraries, i.e. renaming to `ast_visitor` and `element_visitor`.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/105100
