### ISSUE TITLE
Possible Error in ConstructorElementImpl.appendTo method in Analyzer

### ISSUE THREAD

**Issue by lukas-h** [dart-lang/sdk#37165]
This tracker is for issues related to:
* Analyzer

https://github.com/dart-lang/sdk/blob/1b643e5c1f80d4b3f462a2497b776621e3620bf1/pkg/analyzer/lib/src/dart/element/element.dart#L2638

```
  @override
  void appendTo(StringBuffer buffer) {
    String name;
    if (enclosingElement == null) {
      String message;
      String name = displayName;
      if (name != null && !name.isEmpty) {
        message =
            'Found constructor element named $name with no enclosing element';
      } else {
        message = 'Found unnamed constructor element with no enclosing element';
      }
      AnalysisEngine.instance.logger.logError(message);
      name = '<unknown class>';
    } else {
      name = enclosingElement.displayName;
    }
    String constructorName = displayName;
    if (constructorName != null && !constructorName.isEmpty) {
      name = '$name.$constructorName';
    }
    appendToWithName(buffer, name);
  }
```

I assume with `name` in the line `name = '<unknown class>';` should be meant the `name` declared at the beginning of the function (outside the `if`-block), but instead the `name` inside the `if`-Body is taken. In this case the `name` outside the `if` remains `null`.

Maybe renaming the `name`-Variable inside the `if`-block into something else could fix this problem.

**Comment by devoncarew** [comment]
cc @stereotype441 for triage

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/105349
