### ISSUE TITLE
add a hint for self assignments

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#37162]
Add a hint that flags self-assignments.  For example:

```dart
  void _showIfHidden(Rect globalBounds) {
    if (!show) {
      setState(() {
          globalBounds = globalBounds;
          show = true;
        });
    }
  }

```

Follow-up from: https://github.com/dart-lang/linter/issues/1597.

/cc @kentcb

**Comment by srawlins** [comment]
Closing in favor of https://github.com/dart-lang/linter/issues/1597.
