### ISSUE TITLE
Tried to initialize from a previous compilation

### ISSUE THREAD

**Issue by TJ-C** [dart-lang/sdk#37168]
I Received the following message right after I updated flutter and then ran the debugger in VS Code.:

Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

This message did not reappear after stopping and rerunning the debugger.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        

[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

My iPhone wasn't paired at the time flutter doctor was run.

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3257874/initialize_from.dill.gz)

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/dart-lang/sdk/issues/36032
