### ISSUE TITLE
AOT compiled Dart code fails running

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#37164]
* Repro steps:

1. `git clone https://github.com/dart-lang/dart_style.git`
1. `cd dart_style`
1. `pub get`
1. `dart2aot benchmark/benchmark.dart benchmark/benchmark.dart.aot`
1. `dartaotruntime benchmark/benchmark.dart benchmark/benchmark.dart.aot`

=>

```
VM initialization failed: Invalid vm isolate snapshot seen
```

Environment:
```
$ dart --version
Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "macos_x64"
```

**Comment by mit-mit** [comment]
cc @cskau-g @mraleph

**Comment by mraleph** [comment]
```
dartaotruntime benchmark/benchmark.dart benchmark/benchmark.dart.aot
```

I think you meant

```console
$ dartaotruntime benchmark/benchmark.dart.aot
```

or maybe 

```console
$ dartaotruntime benchmark/benchmark.dart.aot benchmark/benchmark.dart
```

?

**Comment by mit-mit** [comment]
Doh.

**Comment by mit-mit** [comment]
Tracking error message improvement in https://github.com/dart-lang/sdk/issues/37223
