### ISSUE TITLE
When run in build mode, analyzer examines pubspec.yaml file even if not supplied

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#37177]
With the following directory structure:
```
pubspec.yaml:
  name: test
  version: 1.0.0
  environment:
    sdk: ^2.0.0

lib/foo.dart:
  Object foo() => {1, 2, 3};
```
Run the analyzer like so:
```
$PATH_TO_DART_SDK/bin/dartanalyzer --build-mode 'package:foo/foo.dart|lib/foo.dart'
```
Observed result:
```
Analyzing package:foo/foo.dart|lib/foo.dart...
  hint • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions at lib/foo.dart:1:17 • sdk_version_set_literal
1 hint found.
```
Expected result:
- No errors.

The reason there should be no errors has to do with the contract of build mode: when run in build mode, the analyzer must not examine any input file unless it was explicitly supplied on the command line.  So even though there is a pubspec.yaml file present, it should be ignored.

Why does build mode have this contractual requirement?  It has to do with how the analyzer is run by the Bazel build tool.  Normally, Bazel runs build rules in a sandbox where the only files present are the ones explicitly specified as inputs in the user's `BUILD` file.  So if the analyzer goes looking for an input that wasn't expected, it won't find it.  This sandboxing is how Bazel keeps builds reproducible--it ensures that if an input is needed to do a build, the user won't forget to explicitly add it to their `BUILD` file.

But when Bazel runs the analyzer in "worker" mode, it skips creating the sandbox and relies on the analyzer to only examine input files that it's explicitly granted access to.  (Worker mode is a performance optimization that leaves the analyzer process alive after a build step, and then re-uses it for subsequent build steps; that way VM startup and JIT compilation penalties are amortized.)  If the analyzer accesses other input files, then that causes two problems: (1) it means that the analyzer will get different results between worker and non-worker builds (which is terribly confusing, because performance optimizations aren't expected to change analysis results), and (2) it means that if the user changes one of these other input files, Bazel won't know that it's necessary to re-run the build step (because it didn't know that file was a dependency), so the user will see stale build results.

The way this manifests is that if there's a package in a Bazel build environment with a `pubspec.yaml` file, and the package uses a feature (such as set literals) that wasn't available in the Dart version in its minimum SDK constraint, then no hint will be reported when Bazel is run normally, but an error will be reported if Bazel is run with the analyzer in "worker" mode.  If the user tries to correct the hint they see in build mode by updating `pubspec.yaml`, the hint won't go away.

In the long term what we should probably do is:
- Add the ability for a `pubspec.yaml` to be explicitly specified on the command line when running in build mode
- Update the Bazel starlark rules for Dart so that when building a package that contains `pubspec.yaml`, it will be explicitly specified on the command line when running the analyzer.
- Change the analyzer behavior so that in build mode, if `pubspec.yaml` isn't specified on the command line, it acts as if the file isn't present in the filesystem.

However, in the short term I think we should change the analyzer behavior so that in build mode, `pubspec.yaml` files are ignored.  That will restore parity between worker and non-worker mode and ensure that builds are reproducible.

**Comment by pq** [comment]
Consider a filtering resource provider that drops `pubspec`s when in build mode.

**Comment by srawlins** [comment]
I think there is no longer `--build-mode`.
