### ISSUE TITLE
Invoking the analyzer (indirectly through DDC) uses analysis_options.yaml from the current directory

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#37172]
I ran into some confusing behavior when running DDC (analyzer based). The analyzer that gets run will look for an analysis_options.yaml file starting in the current working directory instead of the directory where the file your are compiling is located.

This is not the case when you invoke `dartanalyzer` directly. It doesn't matter where your current working directory is in the hierarchy, it looks for the analysis_options.yaml file walking up the ancestor directories from the location of the file you are analyzing.

Now that I know the issue I can work around it, but it seems strange that this is the case.

@stereotype441

**Comment by dcharkes** [comment]
I ran into the same problem https://github.com/Dart-Code/Dart-Code/issues/2019

**Comment by keertip** [comment]
DDC is no longer based on the analyzer, this issue is obsolete.
