### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by boblaprade** [dart-lang/sdk#37184]
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3262793/initialize_from.dill.gz)

**Comment by devoncarew** [comment]
Thanks for the report! Closing as a dupe (we've received several reports of this).
