### ISSUE TITLE
vm/dart/trigger_gc_in_native_test/* failing on Android in AOT

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37185]
This test was disabled in https://dart-review.googlesource.com/c/sdk/+/95040, but now it's failing after being re-enabled.

See https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8911384542933560432/+/steps/test_results/0/logs/tests_that_began_failing/0

**Comment by aam** [comment]
What was the resolution for this issue?
There are more crashes in dart/trigger_gc_in_native_test/3 on dartkp-android-release-arm starting at https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-android-release-arm/1859.

**Comment by bkonyi** [comment]
I honestly can't remember and couldn't find anything in my closed CLs...
