### ISSUE TITLE
Analyzer: Spurious `dynamic` claimed as type argument which is actually a function type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#37186]
Consider the following example:

```dart
class A {}
class B implements A {}

class C<T> {
  void foo(D<void Function(C<T>)> d) {}
}

abstract class D<F extends void Function(C<Null>)> {
  F get f;
}

class D1 implements D<void Function(C<A>)> {
  void Function(C<A>) get f => null;
}

main() async {
  var x = C<B>();
  await x.foo(D1());
}
```

With `dartanalyzer` from commit 3894b0896e02a0dc7c8437f556e74ef7cb509251 (as well as 2.3.2-dev.0.0) we get the following response:

```
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/201905/n037.dart|12|23|19|'dynamic' doesn't extend 'void Function(C<Null>)'.
```

This would make sense if line 12 had applied `D` to the actual type argument `dynamic`, but it actually applies it as `D<void Function(C<A>)>`, and that's a regular-bounded parameterized type (`void Function(C<A>) <: void Function(C<Null>)`) so there should not be any errors.

**Comment by srawlins** [comment]
Still not accepted by analyzer
