### ISSUE TITLE
Create public service protocol RPCs for functionality used by tooling

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#37199]
The following private service protocol RPCs are being used by tooling other than Observatory. We need to either make these RPCs public or create public implementations which do not expose information about the VM implementation.

- [x] `_clearVMTimeline` ([CL here](https://dart-review.googlesource.com/c/sdk/+/106061))
- [x] `_clearCpuProfile`
- [x] `_getInstances` ([CL here](https://dart-review.googlesource.com/c/sdk/+/106561))
- [x] `_getCpuProfile`
- [x] `_getCpuProfileTimeline`
- [x] `_setVMTimelineFlags` ([CL here](https://dart-review.googlesource.com/c/sdk/+/106061))
- [x] `_getAllocationProfile` ([CL here](https://dart-review.googlesource.com/c/sdk/+/105730))
- [x] `_getVMTimeline` ([CL here](https://dart-review.googlesource.com/c/sdk/+/106061))

See flutter/devtools#709 for DevTools related RPCs.

**Comment by bkonyi** [comment]
@DanTup, you don't happen to be using any private RPCs in the VSCode extension, do you?

**Comment by DanTup** [comment]
We subscribe to the _Service stream to get ServiceRegistered events (to see if things like hot reload are supported). I don't think there's anything else though.
