### ISSUE TITLE
window.navigator.getGamepads() fails on Firefox and Edge when using ddc and breaks every Iterable used afterwards

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#37190]
_EDIT_: See https://github.com/dart-lang/sdk/issues/37190#issuecomment-499892026, getGamepads() ruins every iterable.

I have this code:

```dart
  final connectedGamepads = window.navigator.getGamepads();
  print(connectedGamepads.length);
  print(connectedGamepads.runtimeType);
  print(connectedGamepads);
```

which I compile using `pub serve build_runner serve` and using `dartdevc` as the compiler. When I open the page in Firefox, the following is logged (It does not matter if a gamepad is connected or not):

```
0 dart_sdk.js:18740:15
_GamepadList dart_sdk.js:18740:15
Error: dart_sdk.js:5844:7
    DartError dart_sdk.js:5844
    throw dart_sdk.js:4556
    castError dart_sdk.js:4516
    as dart_sdk.js:4856
    check_C dart_sdk.js:4036
    add dart_sdk.js:73426
    _isSubtypeOrLegacySubtype dart_sdk.js:4306
    _isSubtypeOrIgnorableCastFailure dart_sdk.js:4818
    as dart_sdk.js:4853
    check_C dart_sdk.js:4036
    add dart_sdk.js:73426
    _isSubtypeOrLegacySubtype dart_sdk.js:4306
    _isSubtypeOrIgnorableCastFailure dart_sdk.js:4818
    as dart_sdk.js:4853
    check_C dart_sdk.js:4036
    add dart_sdk.js:73426
    iterableToFullString dart_sdk.js:15270
    toString dart_sdk.js:9719
    str dart_sdk.js:4981
    print dart_sdk.js:41132
    main main.dart:9
    <anonymous> main.dart.bootstrap.js:237
    execCb require.js:1696
    check require.js:878
    enable require.js:1139
    bind require.js:134
    emit require.js:1189
    each require.js:59
    emit require.js:1188
    check require.js:938
    enable require.js:1139
    bind require.js:134
    emit require.js:1189
    each require.js:59
    emit require.js:1188
    check require.js:938
    enable require.js:1176
    init require.js:788
    callGetModule require.js:1203
    completeLoad require.js:1590
    onScriptLoad require.js:1717
```

When I set the breakpoint @`DartError dart_sdk.js:5844` the following error message is passed to `DartError`: `Expected a value of type 'Gamepad', but got one of type 'NativeJavaScriptObject`

If I open the page with Chrome or use dart2js everything works fine and it prints an empty list for Firefox .

What I would expect:
* code compiled with `dartdevc` should also work on Firefox (same for Edge)

Also, I am sure it did work at some point, because I've run this code successfully before (before May 21, so Dart 2.3.0 and Firefox 67). Going back to an older `pubspeck.lock` where it did work doesn't change anything, so it's probably `dartdevc` (maybe Firefox 68 returns something different than Firefox 67 that can't be mapped like before? It works in Chrome after all.).

OS: Windows 10
Browser: Firefox 68.0b7 (64-bit)
Dart: Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "windows_x64"

**Comment by denniskaselow** [comment]
Okay, this one is driving me nuts. I've downgraded to Dart 2.3.0 and Firefox 67 and it still didn't run, but when I switched some lines of code, it suddenly run (even on current Dart 2.3.1 and Firefox 68 and Edge).

So, this code does not run on Firefox and Edge:
```dart
  print('getGamepads');
  final connectedGamepads = window.navigator.getGamepads();
  print('listen');
  window.on['gamepadconnected'].cast<GamepadEvent>().listen((event) {
    print(event.gamepad);
  });
  print('iterate');
  for (var i = 0; i < connectedGamepads.length; i++) {
    if (connectedGamepads[i] != null) {
      print(i);
    }
  }
  print('done');
```

and outputs:
```
getGamepads dart_sdk.js:18740:15
listen dart_sdk.js:18740:15
Error: dart_sdk.js:5844:7
```

but this code runs just fine on Chrome, Firefox and Edge (the only change is that I moved the `getGamepads()` line):
```dart
  print('listen');
  window.on['gamepadconnected'].cast<GamepadEvent>().listen((event) {
    print(event.gamepad);
  });
  print('getGamepads');
  final connectedGamepads = window.navigator.getGamepads();
  print('iterate');
  for (var i = 0; i < connectedGamepads.length; i++) {
    if (connectedGamepads[i] != null) {
      print(i);
    }
  }
  print('done');
```

and outputs:
```
listen dart_sdk.js:18740:15
getGamepads dart_sdk.js:18740:15
iterate dart_sdk.js:18740:15
done dart_sdk.js:18740:15
```

and even `[object Gamepad]` in all 3 browsers once I press a button. No `NativeJavaScriptObject` anywhere.

It's a simple fix in this example, but this "fix" doesn't work in my actual code (not yet at least), so I have no idea what's going on here. I haven't touched that part of my code since November 2018.

**Comment by denniskaselow** [comment]
Okay, it's not me who is going nuts, it's `window.navigator.getGamepads()` that's gone totally bonkers in ddc on Firefox and Edge.

This simple program which doesn't even interact with the gamepads just fails spectacularly:

```dart
import 'dart:html';

void main() {
  window.navigator.getGamepads();
  print('add item');
  [].add(1);
  print('done');
}
```

It's the same exception as above with a similar stacktrace. Somehow `getGamepads()` turns all lists into lists of gamepads.

In the `dart_sdk.js` of the `add` method is this code:
```js
add(value) {
  E._check(value);
  dart.throw(new core.UnsupportedError.new("Cannot add to immutable List."));
}
```

E is a type parameter and in this case it is `Gamepad`. As far as I can tell, everything that is `Iterable` is affected.

**Comment by devoncarew** [comment]
I believe that DDC (the development compiler) is only tested against Chrome. dart2js (the release mode compiler) is tested against the major evergreen browsers.

cc @vsmenon

**Comment by vsmenon** [comment]
Thanks for the simplified repro!

As @devoncarew said, we're only officially supporting (i.e., testing against) Chrome for ddc/debugging.  We plan to expand that eventually. 

@terrylucas 

I suspect the problem is here:

https://github.com/dart-lang/sdk/blob/master/tools/dom/templates/html/impl/impl_Navigator.darttemplate#L18

We're tagging the object/prototype as a `GamepadList`, but that type is probably Chrome only.  I bet it's just a regular JS Array in FF / Edge.

**Comment by treeplate** [comment]
Using getGamepads() on chrome, I get a `RangeError: Maximum call stack size exceeded` with a large stack trace including:
```
    at dart.NullableType.new.as (http://localhost:54953/dart_sdk.js:6935:39)
    at FixedSizeListIterator.new.get current [as current] (http://localhost:54953/dart_sdk.js:111922:18)
    at JsIterator.next (http://localhost:54953/dart_sdk.js:6898:52)
    at Object._isInterfaceSubtype (http://localhost:54953/dart_sdk.js:6418:16)
    at Object._isSubtype (http://localhost:54953/dart_sdk.js:6309:16)
    at Object.isSubtypeOf (http://localhost:54953/dart_sdk.js:6214:29)
    at Object.instanceOf [as is] (http://localhost:54953/dart_sdk.js:5343:17)
    at Function.is_C [as is] (http://localhost:54953/dart_sdk.js:4970:51)
    at dart.NullableType.new.as (http://localhost:54953/dart_sdk.js:6935:39)
    at FixedSizeListIterator.new.get current [as current] (http://localhost:54953/dart_sdk.js:111922:18)
    at JsIterator.next (http://localhost:54953/dart_sdk.js:6898:52)
    at Object._isInterfaceSubtype (http://localhost:54953/dart_sdk.js:6418:16)
    at Object._isSubtype (http://localhost:54953/dart_sdk.js:6309:16)
    at Object.isSubtypeOf (http://localhost:54953/dart_sdk.js:6214:29)
    at Object.instanceOf [as is] (http://localhost:54953/dart_sdk.js:5343:17)
```

**Comment by liyuqian** [comment]
I got `Expected a value of type 'Gamepad?', but got one of type 'Type'` error in Chrome Version 116.0.5845.179 (Official Build) (64-bit) too...

**Comment by denniskaselow** [comment]
As this works with `package:web` which is already beyond 1.0 and a replacement for `dart:html` I don't think this issue matters anymore, so I'm closing it.
