### ISSUE TITLE
Analysis Server: worspace/symbol raises an error if the query field is not present

### ISSUE THREAD

**Issue by jonas-jonas** [dart-lang/sdk#37206]
Hi,

while integrating the dart analysis server into our eclipse plugin I noticed an error being raised by the analysis server. [Particularly the error is raised by the `workspace/symbol` handler](https://github.com/dart-lang/sdk/blob/fca2c82be074a2355ac58271a2f4cb2c772299da/pkg/analysis_server/lib/src/lsp/handlers/handler_workspace_symbols.dart#L31).

```
[t=1559985255637] LSP4E to org.eclipse.dartboard.server1:
{"jsonrpc":"2.0","id":"9","method":"workspace/symbol","params":{}}

[t=1559985255696] org.eclipse.dartboard.server1 to LSP4E:
{"id":"9","jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params for workspace/symbol"}}
```

The problem seems to be that the eclipse client is omitting the `query` parameter altogether (instead of sending it with an empty string). 
This is something that could be changed in either the eclipse client (by sending the parameter with an empty string) or the analysis server. 
But since omitting the parameter seems to be handled correctly in the typescript language server, it seems better suited to let the parameter be empty _or omitted_.

I would also be able to submit a patch if you decide to fix it in the analysis server.

The error happened on Linux (Fedora 30) with the latest nightly:
```
Dart VM version: 2.3.2-edge.7f146e431e160e51d030a633d09bc692574ce15f 
(Sat Jun 8 01:21:59 2019 +0000) on "linux_x64"
```

The server was launched with the following arguments:
`dart /home/jonas/Library/nightlies/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp`

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@jonas-jonas I think the request here is incorrect. Looking at the spec, the `query` field is not optional:

https://microsoft.github.io/language-server-protocol/specification#workspace_symbol

To be optional it must have a `?` on the end of the name, or `| undefined` or `| null` in the definition. I believe the fix is for your LSP client to send an empty string for `query` for this request. I know that sounds strange because the spec says "non-empty string", however I believe that's a spec bug based on our discussion here (and that the VS Code language client will sent empty strings to get full lists):

https://github.com/microsoft/vscode-languageserver-node/issues/458

It's been a while and the spec wasn't updated to reflect this, so I'll send a PR tomorrow to try and have it updated to avoid confusion.

I'll also take a look if we can improve the errors for things like this. It's come up a few times where we've got invalid params and we just give this generic response which doesn't help track it down. If the error said that `query` was a required value, I think it'd be easier for clients to debug.

Let me know if you think this all makes sense and I'll close this. Thanks!

**Comment by jonas-jonas** [comment]
Hi @DanTup,

thanks for the quick reply. I was aware of the discussion about the optionality of the `query` fields contents. The developers of LSP4E also raised an issue with microsoft about this: https://github.com/Microsoft/language-server-protocol/issues/740

Though as I said, LSP4E uses the same abstraction for all language servers and seems to always send the request without the `query` field (same for TS/JS, Json, etc.).

My thought was, that it shouldn't make much of a difference to treat omitting the field altogether like it was empty. I guess as the analysis server should be as near to the spec as possible, this isn't something you're willing to do?

Anyways, I will raise the issue with the client's developers and try to have it resolved there. 

Again thanks for your answer. :)

> I'll also take a look if we can improve the errors for things like this. It's come up a few times where we've got invalid params and we just give this generic response which doesn't help track it down. If the error said that query was a required value, I think it'd be easier for clients to debug.

That sounds great, I was indeed a little confused when I first saw the error.

**Comment by DanTup** [comment]
On the surface it does seem like a reasonable request for us to just support this field not being present...

However! The code that does all of the deserialisation and validation is code-gen'd from the spec. This means making one-off tweaks isn't just a case of modifying a bit of code, we'd have to override the generated types. We do this in some places (mainly to make them fit better with Dart - for ex. the spec uses unions and Dart doesn't have them) but I'd prefer not to do it if it's to workaround a client doing the wrong thing according to the spec. If we did this, it encourages the client not to fix it, which could lead to them failing against other servers, and then those other servers workaround around it, and then the documented spec and the spec that everyone has to implement will diverge.

So I really think the best thing here is to get the spec fixed, and then the client follow it. I'm fairly certain that the spec fix is to allow empty strings (VS Code seems to be the reference implementation - when it disagrees with the spec, it's generally the spec determined to be wrong), but we'll see what the response is to [my PR](https://github.com/microsoft/language-server-protocol/pull/770).

**Comment by jonas-jonas** [comment]
Alright, I raised the issue with the maintainers of the client and opened a PR to fix the issue. Closing.

**Comment by DanTup** [comment]
Great - do let me know if you have any issues getting a solution. I'll let you know if I get a response on my PR that's anything other than confirming what we suspect. Thanks!

**Comment by DanTup** [comment]
I have a PR open for improving the errors (that I hope to land soon), for ex:

```dart
   // Create a request that doesn't supply the query param.
    final request = new RequestMessage(
      Either2<num, String>.t1(1),
      Method.workspace_symbol,
      <String, dynamic>{},
      jsonRpcVersion,
    );

    final response = await sendRequestToServer(request);
    expect(response.error.code, equals(ErrorCodes.InvalidParams));
    // Ensure the error message is useful to the client.
    expect(
      response.error.message,
      equals('Invalid params for workspace/symbol:\n'
          'params.query must not be undefined'),
    );
```

The message should tell you exactly which fields are bad and why ("must not be undefined", "must not be null", "must be bool", etc).
