### ISSUE TITLE
Use alignment flags to zx_vmar_map() on Fuchsia

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#37210]
On Fuchsia, `zx_vmar_allocate` and `zx_vmar_map` have been updated to accept flags indicating the desired alignment:

https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/zircon/docs/syscalls/vmar_allocate.md
https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/zircon/docs/syscalls/vmar_map.md

The alignment flags should be used by VirtualMemory::AllocateAligned() in virtual_memory_fuchsia.cc here:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/virtual_memory_fuchsia.cc#L115

**Comment by crelier** [comment]
I am afraid the new alignment flags do not help us, since they offer an alignment up to 8K only. The Dart heap requires an alignment of 256K (heap page size).

**Comment by dgstevens** [comment]
The flags support all powers of 2 up to 4GB. For dart, seems like you'd want ZX_VM_ALIGN_256KB.

**Comment by crelier** [comment]
I see. The string "and continues up to" was actually not a typo :-)
I'll take care of it. Thanks.

**Comment by crelier** [comment]
This was addressed by https://dart-review.googlesource.com/c/sdk/+/105545
