### ISSUE TITLE
Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

### ISSUE THREAD

**Issue by hoornet** [dart-lang/sdk#37226]
Error:
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3276857/initialize_from.dill.gz)

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///C:/Users/Hoornet/AppData/Local/Temp/initialize_from.dill4d6cba12-8c52-11e9-8f4f-b42e99307704/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...
E/eglCodecCommon( 5347): glUtilsParamSize: unknow param 0x000082da
I/Choreographer( 5347): Skipped 78 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 5347): eglMakeCurrent: 0xe6105f00: ver 3 1 (tinfo 0xcfe3be00)
I/OpenGLRenderer( 5347): Davey! duration=1350ms; Flags=1, IntendedVsync=558726268564, Vsync=560026268512, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=560031295900, AnimationStart=560031354100, PerformTraversalsStart=560031387400, DrawStart=560039524900, SyncQueued=560040651300, SyncStart=560042929800, IssueDrawCommandsStart=560043132200, SwapBuffers=560060515600, FrameCompleted=560078903000, DequeueBufferDuration=8774000, QueueBufferDuration=200000, 
D/EGL_emulation( 5347): eglMakeCurrent: 0xebe5ce80: ver 3 1 (tinfo 0xe4693c60)

--------------

C:\DEV\flutter\bin\flutter.bat **doctor** --verbose
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.529], locale en-US)
    • **Flutter version 1.6.3** at C:\DEV\flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • **Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)**

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Hoornet\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7479.14

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\Hoornet\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by devoncarew** [comment]
Thanks! We see a lot of these reports. Closing as a dup of https://github.com/dart-lang/sdk/issues/36032.
