### ISSUE TITLE
[vm/ffi] Support resolving static symbols

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37225]

**Comment by dcharkes** [comment]
I also encountered the need for this last week.

We either want to make DynamicLibrary extend Pointer, or support an `RTLD_DEFAULT` which is a DynamicLibrary with address=0.

```dart
final DynamicLibrary RTLD_DEFAULT = fromAddress<Pointer<Void>>(0).cast();

final Pointer<Void> Function(int) malloc = RTLD_DEFAULT.lookupFunction<
   Pointer<Void> Function(IntPtr), Pointer<Void> Function(int)>("malloc");

Pointer<T> allocate<T extends NativeType>({int count: 1}) =>
   malloc(sizeOf<T>() * count).cast();
```

**Comment by dcharkes** [comment]
## API

We can either implement this in two ways.

### Use dlsym pseudo handles

> There are two special pseudo-handles, RTLD_DEFAULT and RTLD_NEXT. The former will find the first occurrence of the desired symbol using the default library search order. The latter will find the next occurrence of a function in the search order after the current library. This allows one to provide a wrapper around a function in another shared library.

```dart
final Pointer<Void> RTLD_DEFAULT = Pointer.fromAddress<Void>(0);
final Pointer<Void> RTLD_NEXT = Pointer.fromAddress<Void>(-1);
final DynamicLibrary staticLibrary = DynamicLibrary.fromHandle(RTLD_DEFAULT);
staticLibrary.lookup(...);
```

* pro: requires no special machinery - we could even let users write this themselves, instead of providing something
* possible con: bleeds out dlsym internals

### Separate top level functions

```dart
/// Looks up a symbol and returns its address in memory.
///
/// Throws an [ArgumentError] if it fails to lookup the symbol.
external Pointer<T> lookupStatic<T extends NativeType>(String symbolName);

/// Helper that combines lookupStatic and cast to a Dart function.
F lookupFunctionStatic<T extends Function, F extends Function>(String symbolName) {
  return lookupStatic<NativeFunction<T>>(symbolName)?.asFunction<F>();
}
```

* pro: hides away dlsym logic
* con: hides away dlsym logic
* con: copies two functions from the DynamicLibrary
* con: requires extra machinery

## Other issues

Symbols could possibly be stripped by the linker. This would be specific to how the Dart embedder is build.

**Comment by sjindel-google** [comment]
`dlsym` isn't the only API we need to support -- Windows has its own for example (and maybe Fuchsia later?)

Either solution seems OK as long as `LoadLibraryW` (for Windows) can be used to get the current library. I don't think any of the pros/cons are significant. I imagine that the "wrapper" code in the first example would ultimately be tucked away in a helper library, if not in `dart:ffi` itself.

**Comment by dcharkes** [comment]
Ah yes, we have two in the VM currently: `dlopen`+`dlsym` and `LoadLibraryW`+`GetProcAddress`.

On Windows you get a handle that you pass to `GetProcAddress` the following way:

> GetModuleHandle(NULL)

https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-getmodulehandlea

The common denominator is using a specific handle for the current process. On Unix this is `0` and on Windows you obtain it with `GetModuleHandle(NULL)`.

Using that, this would probably be the API:

```dart
// Implemented in VM: returns 0 on Unix, and executes `GetModuleHandle(NULL)` on Windows.
external Pointer<Void> _staticLibraryHandle();

final DynamicLibrary staticLibrary = DynamicLibrary.fromHandle(_staticLibraryHandle());
```

**Comment by sjindel-google** [comment]
That solution is OK, but I think I would prefer the to expose `lookupStatic` directly for "future-proofing". We can of course use #2 as the implementation in the patch file.

**Comment by sjindel-google** [comment]
On iOS, all embedded libraries are loaded when the App starts, so we don't need the normal `DynamicLibrary.open` at all.

**Comment by dcharkes** [comment]
Which commit(s) added this?

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/113687
