### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by NicolasDionB** [dart-lang/sdk#37222]
dartdevc -k arguments: --dart-sdk-summary=D:\_Utils\Flutter\SDK\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\web/main.ddc.js --source-map -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/meta/meta.ddc.dill=packages/meta/meta -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/collection/collection.ddc.dill=packages/collection/collection -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/icons.ddc.dill=packages/live_app/widgets/icons -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/src/cupertino/activity_indicator.ddc.dill=packages/flutter_web/src/cupertino/activity_indicator -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/src/badge_animation_type.ddc.dill=packages/live_app/widgets/badge/src/badge_animation_type -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/color/tiny_color/hsl_color.ddc.dill=packages/live_app/util/color/tiny_color/hsl_color -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/color/pigment/pigment.ddc.dill=packages/live_app/util/color/pigment/pigment -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/color/tiny_color/conversion.ddc.dill=packages/live_app/util/color/tiny_color/conversion -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/color/tiny_color/tiny_color.ddc.dill=packages/live_app/util/color/tiny_color/tiny_color -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/src/badge_position.ddc.dill=packages/live_app/widgets/badge/src/badge_position -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/src/badge_positioned.ddc.dill=packages/live_app/widgets/badge/src/badge_positioned -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/src/badge_shape.ddc.dill=packages/live_app/widgets/badge/src/badge_shape -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/src/badge.ddc.dill=packages/live_app/widgets/badge/src/badge -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/badges.ddc.dill=packages/live_app/widgets/badge/badges -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/color/material_color.ddc.dill=packages/live_app/util/color/material_color -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/themes/app_theme.ddc.dill=packages/live_app/widgets/themes/app_theme -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/buttons/floating_bar_button.ddc.dill=packages/live_app/screens/vroom/buttons/floating_bar_button -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/top_bar.ddc.dill=packages/live_app/screens/vroom/top_bar -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/badge/badge_themed.ddc.dill=packages/live_app/widgets/badge/badge_themed -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/panels/panel_content.ddc.dill=packages/live_app/screens/vroom/panels/panel_content -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/js/js.ddc.dill=packages/js/js -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/logger/logger.ddc.dill=packages/live_app/util/logger/logger -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/json_annotation/json_annotation.ddc.dill=packages/json_annotation/json_annotation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/network/dto/hub_packet.ddc.dill=packages/live_app/managers/network/dto/hub_packet -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/core/broadcast_event.ddc.dill=packages/live_app/core/broadcast_event -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/user/dto/user.ddc.dill=packages/live_app/managers/user/dto/user -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/charcode/ascii.ddc.dill=packages/charcode/ascii -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/charcode/charcode.ddc.dill=packages/charcode/charcode -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/path/path.ddc.dill=packages/path/path -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/source_span/source_span.ddc.dill=packages/source_span/source_span -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/http/src/base_client.ddc.dill=packages/http/src/base_client -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/http/http.ddc.dill=packages/http/http -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/network/network.ddc.dill=packages/live_app/util/network/network -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/localization/localization_manager.ddc.dill=packages/live_app/managers/localization/localization_manager -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/login/dto/server_info.ddc.dill=packages/live_app/managers/login/dto/server_info -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/client/debug.ddc.dill=packages/live_app/util/client/debug -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/client/platform.ddc.dill=packages/live_app/util/client/platform -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/login/server_info_step.ddc.dill=packages/live_app/managers/login/server_info_step -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/random/random.ddc.dill=packages/live_app/util/random/random -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/user/user.ddc.dill=packages/live_app/util/user/user -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/network/hub_error.ddc.dill=packages/live_app/managers/network/hub_error -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/core/base_core.ddc.dill=packages/live_app/core/base_core -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/stream/dto/kurento.ddc.dill=packages/live_app/managers/stream/dto/kurento -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/math/math.ddc.dill=packages/live_app/util/math/math -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/panels/panel_base.ddc.dill=packages/live_app/screens/vroom/panels/panel_base -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/network/dto/negotiate.ddc.dill=packages/live_app/managers/network/dto/negotiate -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/network/hub_connection.ddc.dill=packages/live_app/managers/network/hub_connection -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/vroom/dto/vroom_init.ddc.dill=packages/live_app/managers/vroom/dto/vroom_init -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/vroom/dto/vroom_info.ddc.dill=packages/live_app/managers/vroom/dto/vroom_info -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/_debug.ddc.dill=packages/live_app/_debug -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/asn1lib/asn1lib.ddc.dill=packages/asn1lib/asn1lib -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/pointycastle/src/ufixnum.ddc.dill=packages/pointycastle/src/ufixnum -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/pointycastle/adapters/stream_cipher_as_block_cipher.ddc.dill=packages/pointycastle/adapters/stream_cipher_as_block_cipher -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/encrypt/encrypt.ddc.dill=packages/encrypt/encrypt -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/encrypt/encrypt.ddc.dill=packages/live_app/util/encrypt/encrypt -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/vroom/dto/subroom_info.ddc.dill=packages/live_app/managers/vroom/dto/subroom_info -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/managers/vroom/subroom_manager.ddc.dill=packages/live_app/managers/vroom/subroom_manager -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/core/vroom_core.ddc.dill=packages/live_app/core/vroom_core -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/video_widget.ddc.dill=packages/live_app/widgets/video_widget -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/panels/panel_chat.ddc.dill=packages/live_app/screens/vroom/panels/panel_chat -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/widgets/user_avatar.ddc.dill=packages/live_app/widgets/user_avatar -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/intl.ddc.dill=packages/intl/intl -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/message_lookup_by_library.ddc.dill=packages/intl/message_lookup_by_library -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/texts/messages_all.ddc.dill=packages/live_app/texts/messages_all -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/texts/i18n.ddc.dill=packages/live_app/texts/i18n -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/easy_localization/easy_localization_provider.ddc.dill=packages/live_app/util/localization/easy_localization/easy_localization_provider -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/easy_localization/easy_localization_delegate.ddc.dill=packages/live_app/util/localization/easy_localization/easy_localization_delegate -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/easy_localization/easy_localization.ddc.dill=packages/live_app/util/localization/easy_localization/easy_localization -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/panels/panel_users.ddc.dill=packages/live_app/screens/vroom/panels/panel_users -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/screens/vroom/vroom.ddc.dill=packages/live_app/screens/vroom/vroom -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/src/widgets_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/src/widgets_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/src/l10n/generated_date_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/src/l10n/generated_date_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/intl/date_symbol_data_custom.ddc.dill=packages/intl/date_symbol_data_custom -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/src/utils/date_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/src/utils/date_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/src/cupertino_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/src/cupertino_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/src/l10n/generated_material_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/src/l10n/generated_material_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/util/localization/flutter_localizations/flutter_localizations.ddc.dill=packages/live_app/util/localization/flutter_localizations/flutter_localizations -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_spacefaccc908-8bc2-11e9-8343-d8fc93281c47\packages/live_app/main.ddc.dill=packages/live_app/main --packages file:///C:/Users/NICOLA~1.DIO/AppData/Local/Temp/kernel_builder_a8a20ee3-8c42-11e9-8343-d8fc93281c47/.packages --module-name web/main --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map web/main.dart
    dart --version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "windows_x64"

```
RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:435:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:388:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:235:49)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:232:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:65:41)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:65:26)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by devoncarew** [comment]
Looks like a crash in DDC, when reading a kernel file, when compiling a flutter_web app. Tentatively assigning to the DDC team to do additional triage.

**Comment by Jufebrown** [comment]
Had a similar problem (same message about bug in compiler) with a regular dart project. Happened right after I upgraded the sdk today. Had to delete my .dart_tool directory and then rebuild the project. There is some incompatibility with reading cached files between 2.3.2 and 2.3.1

**Comment by vsmenon** [comment]
Merging to:

https://github.com/dart-lang/sdk/issues/38102
