### ISSUE TITLE
ClassTable::StateOffsetFor performance regression

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#37221]
https://dart-review.googlesource.com/c/sdk/+/104286 caused a bunch of benchmark regressions. This was entirely due to the new implementation of dart::compiler::target::ClassTable::StateOffsetFor(intptr_t cid). Don't know why this caused such a huge performance regression, but I rolled back the culprit function in: https://dart-review.googlesource.com/c/sdk/+/105550

Need to investigate this more and then roll forward.

**Comment by devoncarew** [comment]
@liamappelbe, when opening an issue, if you know the best area for the issue, can you assign an area label to it? This will reduce the work for issue triagers. Thanks!

**Comment by liamappelbe** [comment]
Forgot to close this. It was fixed by https://dart-review.googlesource.com/c/sdk/+/105701
