### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by zhengyanhu** [dart-lang/sdk#37235]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.7479.14`
- `2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e`
- `WS-191.7479.14, JRE 1.8.0_202-release-1483-b53x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

Dart Analyzer Error
Encountered a Dart Analysis Server error.

**Comment by devoncarew** [comment]
Thanks for the feedback! Without more info (generally provided as part of the crash report), we can't take action here.
