### ISSUE TITLE
[DDC] Function source map location does not align with Chrome

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#37240]
Consider this Dart:
```Dart
void doSomething() {
    ...
}
```
DDC compiled output would look something like this:
```Javascript
foo$.doSomething = function() {
   ...
};
```
(assume zero based line and column below)

The provided DDC source map will have a location entry at line 0 and column 0. That is starting at `foo$`. This does not align with what Chrome uses in call frames. If we were to break on line 1 (at ...) the Chrome paused event will have a call frame at line 0 column 5 that is starting at `doSomething`.

We should shift the source map entry point to be at the start of the actual function name.

**Comment by vsmenon** [comment]
@grouma - i can't replicate this in chrome dev tools.  E.g., if I have:

```dart
void doSomething() {
  throw 'something';
}
```

the `throw` is on the stack / call frame in Dart.

**Comment by grouma** [comment]
Given our new approach to debugging we can close this out. We can handle this in `package:dwds`.
