### ISSUE TITLE
[vm/ffi] Test FFI with high heap

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37251]
Currently native heap addresses are freely cast between `void*`, `intptr_t` and `size_t`. We need to make sure there are no surprises when the heap lives in the upper half of the address space.

**Comment by mkustermann** [comment]
There's also some interesting questions on 64-bit runtimes:

```
final p = Pointer<Int8>.fromAddress(0);
p[-1]; // Should be disallowed.
p[0x8000000000000000]; // Same here, since index is -9223372036854775808

final p2 = Pointer<Int8>.fromAddress(0x8000000000000000); // Should be allowed.
```

**Comment by sjindel-google** [comment]
I don't see why `p[-1]` should be disallowed. I think the C interpretation should be `(p.address + -1 * elementSize).load()`.

And the same for the rest. But, I intended this issue to be specifically about our handing of `malloc` returning large pointers. So it's obsolete after https://github.com/dart-lang/sdk/issues/38520
