### ISSUE TITLE
[vm/ffi] Inconsistent overflow checks in allocate vs. elementAt

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37250]
Allocate checks that the element count * element size doesn't overflow -- elementAt doesn't check.

**Comment by dcharkes** [comment]
We have two types of overflow, a one that is just based element size and pointer size. And a second one which is based on offset towards a previous pointer and pointer size.

Second type:

```dart
Pointer<Int8> p = fromAddress(0x7FFF FFFF FFFF FFF0).
p2 = p.offsetBy(0x7FFF FFFF FFFF FFF0).offsetBy(0x7FFF FFFF FFFF FFF0);
```

I guess both these different types off overflows deserve their own error message.

`elementAt` can throw both errors. (And will also be able to throw both errors once it is implemented as `Pointer.fromAddress(p.address + sizeOf<T> * count)`).

**Comment by dcharkes** [comment]
On second thought, @sjindel-google and I think we should just the same behavior with overflow as in the rest of the FFI: ignore so that it truncates.
