### ISSUE TITLE
IDE `uncaught exception` breakpoint stopped unexpectedly when using a combination of Future and Completer

### ISSUE THREAD

**Issue by cyanglaz** [dart-lang/sdk#37268]
* Dart SDK Version (`dart --version`)
`Dart VM version: 2.3.1-dev.0.0.flutter-a0290f823c (Thu May 9 07:43:56 2019 +0000) on "macos_x64"`

Consider this code: 
```dart
class _MethodCompleter {

  final Completer<String> completer =
      Completer<String>();

  Future<String> callMethod() async {
    throwException().then(completer.complete, onError: completer.completeError);
    return completer.future;
  }

  Future<String> throwException() async {
    throw PlatformException(code: "exceptions");
  }
}
```

When we call `callMethod` like 
```dart
  try {
    await callMethod();
  } catch (e) {
    print(e);
  }
```

Even we wrap the code in a try-catch block, the `uncaught exception` break point in VSCode and Android will stop, saying the exception is uncaught. And the `e` is actually caught and I can see the printed exception `e`.

This issue came up in a specific implementation in the `google_sign_in` plugin  https://github.com/flutter/flutter/issues/26705 and I thought it might be helpful to put it here.

**Comment by komapeb** [comment]
This is also true for Android Studio, see https://github.com/flutter/flutter/issues/26705#issuecomment-500502338

**Comment by dgrove** [comment]
Assigning to @bkonyi since this is happening in multiple IDE's.

**Comment by ZichangG** [comment]
The problem is probably because try catch block is outside Future.then(). Because Future.then() will wipe out stack where the frame containing try catch block will disappear. Currently vm only checks try catch block to determine whether an exception is handled or not. You can check the stacktrack whether caller of callMethod() is there or not.

**Comment by ZichangG** [comment]
#36911 Similar issues

**Comment by ZichangG** [comment]
Just test with your sample code. It actually worked well(Debugger doesn't pause on the exception) with latest dart sdk version in both observatory and VScode.

**Comment by cyanglaz** [comment]
Dup with https://github.com/flutter/flutter/issues/33427
Offline discussion with @ZichangG: Dart is not able to support an exception thrown in a future because the event loop that handles the future is not able to see the caller's stack trace.

I am closing this issue now since the update of this issue can be tracked on https://github.com/flutter/flutter/issues/33427

If you are still interested in the issue, please follow https://github.com/flutter/flutter/issues/33427
