### ISSUE TITLE
[vm/ffi] Write test for behavior of allocation of size-0 structs.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37265]
Currently, it might succeed or throw an exception, depending on the behavior of `malloc`.

**Comment by dcharkes** [comment]
https://github.com/dart-lang/sdk/issues/37250 changes the `Pointer.allocate()` semantics to be consistent with `malloc` as well.

Semantics are `malloc(sizeOf<T>() * count)` where `count` and `T` are the argument and type argument passed to `Pointer.allocate`.

So I think the current semantics are fine.

We should probably add a test which is similar to https://dart-review.googlesource.com/c/sdk/+/107503/3/tests/ffi/data_test.dart

**Comment by sjindel-google** [comment]
I'm fine with the current semantics.

**Comment by sjindel-google** [comment]
Obsolete after https://github.com/dart-lang/sdk/issues/37265
