### ISSUE TITLE
Inconsistent error reporting between dart2js and DDC with generic types

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37267]
See https://github.com/kevmoo/dart_sdk_issue_37267

`webdev serve` – no problem

`webdev serve --release`

![Screen Shot 2019-06-14 at 12 11 58 PM](https://user-images.githubusercontent.com/17034/59532482-bccbe700-8e9d-11e9-9097-0d4bada48f9c.png)

Packages: see pubspec.lock
SDK: 2.4.0-dev.0.0

**Comment by vsmenon** [comment]
Do we know if that's a correct error?

Are you running with `-O3` or higher?

**Comment by kevmoo** [comment]
Running w/ defaults.

I couldn't find an error. It works fine on DDC. Wondering if this is a bug in Dart2js

**Comment by vsmenon** [comment]
@kevmoo - @rakudrama is investigating.  He already found that the app works if you disable dart2js inlining (--disable-inlining in build.yaml).

**Comment by rakudrama** [comment]
@johnniwinther could you take a look? I didn't make much progress before the weekend.

**Comment by johnniwinther** [comment]
I've narrowed it down to a problem in `SsaInstructionSimplifier.visitTypeInfoExpression`. The logic doesn't properly avoid the non-trivial substitutions. I'm still working on a getting a small repro and a precise fix.

**Comment by kevmoo** [comment]
Confirmed fixed w/ the original code. Thanks @johnniwinther !
