### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by vespasyan** [dart-lang/sdk#37277]
compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3294005/initialize_from.dill.gz)

**Comment by dgrove** [comment]
This is addressed in Dart 2.4 by https://dart-review.googlesource.com/c/sdk/+/105240/ .
