### ISSUE TITLE
Singleton instance does't get created until the first time constructor is called.

### ISSUE THREAD

**Issue by yang-f** [dart-lang/sdk#37281]
See question below.

**Comment by yang-f** [comment]
```
class Singleton {
  Singleton._internal() : super();
  static Singleton _instance = new Singleton._internal();
  factory Singleton() {
    return _instance;
  }
}
```
I want the instance get created at once, but it is not.

**Comment by lrhn** [comment]
The only Dart code that gets evaluated before `main` is called, and not as a direct or indirect call from the `main` code, is constants (and even those are indistinguishable from being created the first time they are referenced). That is why static fields are initialized on first access, because that is the first time control flow from `main` reaches the code which initializes the field.

There is no way to create an instance of `Singleton` before someone asks for it without making it constant:
```dart
class Singleton {
  const Singleton._internal();
  factory Singleton() => const Singleton._internal();
}
```
That obviously only works if the class *can* be constant (no mutable state).

Otherwise, you have to wait for someone to ask for an instance, otherwise the code to create it will not be called at all.

Why do you want the instance created "at once", and when is that?

**Comment by yang-f** [comment]
because this:
```
class Singleton {
  const Singleton._internal(){
    // some async operation;
  }
  factory Singleton() => const Singleton._internal();
}
```
and when some on call it:
```
Singelton().doSomething();
```
the async operation does't completed at all.

**Comment by yang-f** [comment]
'at once' means the beginning of the runtime.

**Comment by lrhn** [comment]
There is no way to run code at the beginning of runtime. Dart is deliberately designed to make that not possible. Even if there was a way to do that, you would still have to wait for the asynchronous operation to complete before giving access to the created singleton, so you would have to block `main` until the async operation was done.

Having to do an operation, async or not, does prevent you from using a constant constructor.
If the operation is asynchronous, you will have to wait for it to complete before you can use the result. The way to wait for an asynchronously computed result is to provide a future.
I recommend doing it something like:
```dart
class Singleton {
  static final Future<Singleton> instance = _initialize();

  final SomeType _state;
  Singleton._internal(this._state);
  Future<Singleton> _initialize() async {
     async operation with await;
     return Singleton._internal(computedState);
  }
}
```
  
Then, to use the singleton, you just have to `await Singleon.instance`. You can do that every time you access the singleton, or you can cache the result `var singleton = await Singleton.instancel`, and then use `singleton` in the code after that.

**Comment by yang-f** [comment]
It seems a good solution, and i have another problem. I have to access the singleton in a sync function,  such as widget of flutter's build:
```
@override
Widget build(BuildContext context){
  // can not support await;
  // and the next code does't work
  var _instance = await Singleton.instance;
  return AnyWidget(param:_instance);
```
any idea?

**Comment by yang-f** [comment]
> It seems a good solution, and i have another problem. I have to access the singleton in a sync function, such as widget's build of flutter:
> 
> ```
> @override
> Widget build(BuildContext context){
>   // can not support await;
>   // and the next code does't work
>   var _instance = await Singleton.instance;
>   return AnyWidget(param:_instance);
> }
> ```
> 
> any idea?

sorry, i think it's a `bad` question. And my meaning is: `it seems an impossible task.`

**Comment by julemand101** [comment]
I know nothing about Flutter but perhaps this guides is useful for you:
https://flutter.dev/docs/development/ui/widgets/async

I think you need to use the FutureBuilder.

**Comment by yang-f** [comment]
> I know nothing about Flutter but perhaps this guides is useful for you:
> https://flutter.dev/docs/development/ui/widgets/async
> 
> I think you need to use the FutureBuilder.

thx for you suggestion. the physical truth is more complicated, and i have an idea:
```
class Resourse{
  Future<Something> init async{
    return ...
  }
}
void main async {
  var resourse = new Resource();
  await resource.init();
  runApp();
}
```
