### ISSUE TITLE
cascade operator not work on the sort method of a List

### ISSUE THREAD

**Issue by dingbo8128** [dart-lang/sdk#37280]
Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "macos_x64"

```dart
void main() {
  var numbers = [2, 10, 5, 1];
  var maxNumber = numbers..sort().last();
  print(maxNumber);
}
```
Unable to spawn isolate: test/sorttest.dart:3:28: Error: This expression has type 'void' and can't be used.
  var maxNumber = numbers..sort().last();

**Comment by lrhn** [comment]
You need to write it as `(numbers..sort()).last`.

As written, it sorts the list, which returns `void`, and then tries to call `last` on that return value.

You can also use: `numbers.reduce((a, b) => a > b ? a : b)` to find the maximal element without sorting first.

**Comment by dingbo8128** [comment]
The following code works well without put cascade into ()
```dart
void main() {
  var sb = StringBuffer();
  sb..write('foo')
    ..write('bar');
  print(sb.toString());
}
```
I feel confused: when should I  use () and when not ?

**Comment by dingbo8128** [comment]
@lrhn Thanks for your kindly reply.  I have understood the usage.  expression  in form a..b.c..d.e.f will be parsed as  (a..(b.c)..(d.e.f)). So `numbers..sort().last` is wrong, `sb..write('foo')..write('bar')` is right.  It's disappointing that so delicate skill was not well documented.
