### ISSUE TITLE
[vm/ffi] struct inheritance

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37298]
Should we allow subtyping of structs?

```dart
import dart:ffi show Struct, Int8;

A extends Struct {
  @Int8()
  int x;
}

B extends A {
  @Int8()
  int y;
}
```

Where `B` has all the fields of `A`.

/cc @sjindel-google

**Comment by sjindel-google** [comment]
I don't see a reason to allow it -- it's not widely defined in native ABIs.

**Comment by sjindel-google** [comment]
We won't support it since you can't extend structs in C. Also, it's semantically the same as composition.
