### ISSUE TITLE
Bytecode problems with large number of parameters

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#37305]
Consider the attached synthetic test case, aart.dart, which stresses the number of parameters passed to a method. For JIT and AOT we get the right output

```dart
JIT
k=1632000

AOT
k=1632000

```
With bytecode, however, we see various issues.

```dart
BYTECODE + INTERPRETER
k=32945

BYTECODE + MIX
runtime/vm/compiler/frontend/base_flow_graph_builder.cc: 192: error: expected: stack_ == nullptr

BYTECODE + COMPILER
../../runtime/vm/compiler/frontend/bytecode_flow_graph_builder.cc: 345: error: expected: target_pc > pc_
```

**Comment by aartbik** [comment]
[aart.dart.txt](https://github.com/dart-lang/sdk/files/3303408/aart.dart.txt)

**Comment by aartbik** [comment]
@alexmarkov please have a look. Are we hitting limits somewhere?

**Comment by alexmarkov** [comment]
This test hits a limitation of maximum 255 arguments passed into a call. Both SIMDBC and new kernel bytecode have this limitation. The following CL adds a compile-time error to bytecode generator: https://dart-review.googlesource.com/c/sdk/+/106984 to avoid cryptic crashes.
