### ISSUE TITLE
Please merge #9ac3a733d2f611c405a799e871c541bd8ce33e7b and #f925cd442204efddc8aa3341562b3452178b30bb  into dev channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#37307]
**commit(s) to merge**: 9ac3a733d2f611c405a799e871c541bd8ce33e7b, f925cd442204efddc8aa3341562b3452178b30bb

*merge instructions**: merges cleanly (has to be merged after the other merge request)
**reason**: Fixes Flutter issue https://github.com/flutter/flutter/issues/34308

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Merged to dev & and stable: 7340a569caac6431d8698dc3788579b57ffcf0c6
