### ISSUE TITLE
dartanalyzer fails when user's home directory does not exist.

### ISSUE THREAD

**Issue by zeroomega** [dart-lang/sdk#37308]
This tracker is for issues related to:
* Analyzer

* Dart SDK Version (`dart --version`)
version 2.3.2-edge.b37aa3b03650c60ab47b78b2163382d889ecb5df

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

I am working on adding dartanalyzer support in goma (remote build system) so our team can speed up the build. But when I tried my dartanalyzer support prototype, it always fails with following messages:

```
Unhandled exception:
FileSystemException: Creation failed, path = '/nonexistent/.dart' (OS Error: No such file or directory, errno = 2)
#0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
#1      createAnalyticsInstance (package:telemetry/telemetry.dart:62:9)
#2      analytics (package:analyzer_cli/src/driver.dart:74:5)
#3      Driver.start (package:analyzer_cli/src/driver.dart:177:5)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/k/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart:18:17)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

After digging into the source code of dartanalyzer, I figure out dartanalyzer will try to write its analytics data into user's home directory, which is fine. But it shouldn't fail if the home directory is not writable or not exist. Some build bots may not have a home directory or may not have a writable file-system.

I also tried '--use-analysis-driver-memory-byte-store' flag but the exception persists.

c.c. @petrhosek

**Comment by devoncarew** [comment]
fixed in 983447f95aac00a307c16b8b872585eebb93db1d
