### ISSUE TITLE
Soundness violation

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#37316]
Commit https://github.com/dart-lang/sdk/commit/e9acd9033e3ec3aafef525c354095d7d5605d3f4 adds a test case to test/languages_2/ that checks for a type soundness violation.  It demonstrates that it's possible to put a `String` into a variable of type `num`.  The violation is possible because of a missing forwarding stub.

Compiling the test code to Kernel shows that neither D, nor E receive the forwarding stubs for foo that would mark the parameter of foo with generic-covariant-impl bit.  The demonstration shows that the violation happens on the VM, but not on dart2js.  Most likely, dart2js runs its own analysis and adds the necessary checks.

The issue is expected to be fixed after the chain of CLs starting at https://dart-review.googlesource.com/c/sdk/+/100580 and (currently) ending at https://dart-review.googlesource.com/c/sdk/+/106084 is landed.  With changes form that chain patched in the code from the example compiles to Kernel code that contain the missing forwarding stubs, and the soundness violation doesn't happen at run-time.  Instead, a TypeError is thrown, as it is expected to be.

**Comment by stefantsov** [comment]
Ironically enough, after the chain of the CLs mentioned above landed, the test started failing for dart2js.  /cc @johnniwinther

**Comment by mraleph** [comment]
@chloestefantsova could you check if this can be closed or is there something else left to do (e.g. for `dart2js` or some other bakend)?

**Comment by chloestefantsova** [comment]
Yes, it seems to be fixed now. Thanks for finding this lost relic!
