### ISSUE TITLE
VM generates unpredictable STR instructions

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37319]
The behavior of `LDR`/`LDP`/`STR`/`STP` is unpredicable when the register being stored is also written back to. We have some asserts that try to prevent this:

https://github.com/dart-lang/sdk/blob/3707cf0c1b30ece22a5cfec4f8486bff2c8be6e1/runtime/vm/compiler/assembler/assembler_arm64.h#L877

https://github.com/dart-lang/sdk/blob/3707cf0c1b30ece22a5cfec4f8486bff2c8be6e1/runtime/vm/compiler/assembler/assembler_arm.cc#L134

However, we still generate such instructions, at least on ARM64:

https://github.com/dart-lang/sdk/blob/3707cf0c1b30ece22a5cfec4f8486bff2c8be6e1/runtime/vm/compiler/stub_code_compiler_arm64.cc#L786

**Comment by rmacnak-google** [comment]
Another unpredictable condition we don't have asserts for is load-pair with the two registers being the same.

**Comment by sjindel-google** [comment]
@rmacnak-google That's only for load-pair right? Store-pair seems fine to me to have two of the same register.

**Comment by rmacnak-google** [comment]
Right.

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/106904
