### ISSUE TITLE
source map missing file name 

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#37325]
@jakemac53 @grouma 

Using SDK 089a4353443f17caaca1173d3423fffbf609a2fd I'm seeing an issue with source paths.

Steps
Check out https://github.com/dart-lang/webdev
Go to webdev/example
run
webdev serve --debug   
(you may need to pub global activate webdev)
navigate to http://127.0.0.1:8080/main.ddc.js.map
in the "sources" section I'm only seeing ["/"], whereas in older versions it includes "main.dart".

**Comment by jakemac53** [comment]
When I have seen these in the past it was due to our source map rewriting in `build_web_compilers`. Are you sure you are on the latest version of that?

**Comment by alan-knight** [comment]
Fixed. Needed to upgrade (again) the example.
