### ISSUE TITLE
Part files can't reside a directory level above the main file

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#37336]
I have a part file located at `example/part.dart` which contains:
```Dart
`part of `hello_world/main.dart`
```

I have the main file located at `example/hello_world/main.dart` which contains:
```Dart
part `../part.dart`
```

This returns the invalid error:
```
Expected this library to be part of 'file:///usr/local/google/home/grouma/Projects/webdev/dwds/example/hello_world/main.dart', not 'file:///usr/local/google/home/grouma/Projects/webdev/dwds/example/hello_word/main.dart'.
```

**Comment by lrhn** [comment]
I see `/hello_word/` in the error message. Is there an `l` missing in `world` in the `part of` declaration?
(The `part of ` declaration included here is not syntactically valid, so it's probably not the actual one).

**Comment by grouma** [comment]
Well I feel silly. Looks like this was just a typo. Fixing the typo resolves the issue with part files.
