### ISSUE TITLE
Flutter build web compilers fail

### ISSUE THREAD

**Issue by OlfatMostafa** [dart-lang/sdk#37333]
I got this message

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=E:\flutter\bin\cache\dart-sdk --dart-sdk-summary=E:\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.sum --modules=amd -o C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/animation.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/meta/meta.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/typed_data/typed_buffers.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web_ui/ui.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/io.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/foundation/assertions.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/foundation.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/utils.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/algorithms.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/canonicalized_map.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/comparators.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/iterable_zip.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/src/priority_queue.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/collection/collection.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/services/clipboard.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/services.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/scheduler/binding.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/scheduler.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/gestures/arena.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/gestures.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/physics/clamped_simulation.dartdevc.linked.sum -s C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/physics.dartdevc.linked.sum --url-mapping=package:flutter_web/src/animation/curves.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/curves.dart --url-mapping=package:flutter_web/src/animation/listener_helpers.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/listener_helpers.dart --url-mapping=package:flutter_web/src/animation/animations.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/animations.dart --url-mapping=package:flutter_web/src/animation/tween.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/tween.dart --url-mapping=package:flutter_web/src/animation/animation.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/animation.dart --url-mapping=package:flutter_web/src/semantics/debug.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/semantics/debug.dart --url-mapping=package:flutter_web/src/semantics/binding.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/semantics/binding.dart --url-mapping=package:flutter_web/src/painting/alignment.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/alignment.dart --url-mapping=package:flutter_web/src/painting/basic_types.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/basic_types.dart --url-mapping=package:flutter_web/src/painting/border_radius.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/border_radius.dart --url-mapping=package:flutter_web/src/rendering/platform_view.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/rendering/platform_view.dart --url-mapping=package:flutter_web/src/widgets/icon_data.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/widgets/icon_data.dart --url-mapping=package:flutter_web/src/widgets/scroll_simulation.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/widgets/scroll_simulation.dart --url-mapping=package:flutter_web/src/widgets/icon_theme_data.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/widgets/icon_theme_data.dart --url-mapping=package:flutter_web/src/painting/image_stream.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/image_stream.dart --url-mapping=package:flutter_web/src/painting/image_cache.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/image_cache.dart --url-mapping=package:flutter_web/src/painting/binding.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/binding.dart --url-mapping=package:flutter_web/src/painting/debug.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/debug.dart --url-mapping=package:flutter_web/src/painting/box_shadow.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/box_shadow.dart --url-mapping=package:flutter_web/src/painting/image_provider.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/image_provider.dart --url-mapping=package:flutter_web/src/painting/box_fit.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/box_fit.dart --url-mapping=package:flutter_web/src/painting/gradient.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/gradient.dart --url-mapping=package:flutter_web/src/painting/clip.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/clip.dart --url-mapping=package:flutter_web/src/painting/colors.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/colors.dart --url-mapping=package:flutter_web/src/painting/text_style.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/text_style.dart --url-mapping=package:flutter_web/src/painting/strut_style.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/strut_style.dart --url-mapping=package:flutter_web/src/painting/text_span.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/text_span.dart --url-mapping=package:flutter_web/src/painting/text_painter.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/text_painter.dart --url-mapping=package:flutter_web/src/painting/fractional_offset.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/fractional_offset.dart --url-mapping=package:flutter_web/src/painting/geometry.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/geometry.dart --url-mapping=package:flutter_web/src/painting/image_decoder.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/image_decoder.dart --url-mapping=package:flutter_web/src/painting/image_resolution.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/image_resolution.dart --url-mapping=package:flutter_web/src/painting/notched_shapes.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/notched_shapes.dart --url-mapping=package:flutter_web/src/painting/paint_utilities.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/painting/paint_utilities.dart --url-mapping=package:flutter_web/src/animation/tween_sequence.dart,C:\Users\dell\AppData\Local\Temp\scratch_spacedffa0b0c-9441-11e9-96c3-e0db55e4d0f1\packages/flutter_web/src/animation/tween_sequence.dart package:flutter_web/src/animation/curves.dart package:flutter_web/src/animation/listener_helpers.dart package:flutter_web/src/animation/animations.dart package:flutter_web/src/animation/tween.dart package:flutter_web/src/animation/animation.dart package:flutter_web/src/semantics/debug.dart package:flutter_web/src/semantics/binding.dart package:flutter_web/src/painting/alignment.dart package:flutter_web/src/painting/basic_types.dart package:flutter_web/src/painting/border_radius.dart package:flutter_web/src/rendering/platform_view.dart package:flutter_web/src/widgets/icon_data.dart package:flutter_web/src/widgets/scroll_simulation.dart package:flutter_web/src/widgets/icon_theme_data.dart package:flutter_web/src/painting/image_stream.dart package:flutter_web/src/painting/image_cache.dart
package:flutter_web/src/painting/binding.dart package:flutter_web/src/painting/debug.dart package:flutter_web/src/painting/box_shadow.dart package:flutter_web/src/painting/image_provider.dart package:flutter_web/src/painting/box_fit.dart package:flutter_web/src/painting/gradient.dart package:flutter_web/src/painting/clip.dart package:flutter_web/src/painting/colors.dart package:flutter_web/src/painting/text_style.dart package:flutter_web/src/painting/strut_style.dart package:flutter_web/src/painting/text_span.dart package:flutter_web/src/painting/text_painter.dart package:flutter_web/src/painting/fractional_offset.dart package:flutter_web/src/painting/geometry.dart package:flutter_web/src/painting/image_decoder.dart package:flutter_web/src/painting/image_resolution.dart package:flutter_web/src/painting/notched_shapes.dart package:flutter_web/src/painting/paint_utilities.dart package:flutter_web/src/animation/tween_sequence.dart
    dart --version: 2.3.2-dev.0.0.flutter-e3edfd36b2 (Wed May 22 16:01:07 2019 +0000) on "windows_x64"
```
NoSuchMethodError: The getter 'renames' was called on null.
Receiver: null
Tried calling: renames
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      TemporaryNamer.getName (package:dev_compiler/src/compiler/js_names.dart:93:24)
#2      Printer.visitIdentifier (package:dev_compiler/src/js_ast/printer.dart:932:20)
#3      Identifier.accept (package:dev_compiler/src/js_ast/nodes.dart:1392:50)
#4      Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#5      Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#6      Printer.visitVariableInitialization (package:dev_compiler/src/js_ast/printer.dart:720:5)
#7      VariableInitialization.accept (package:dev_compiler/src/js_ast/nodes.dart:1007:15)
#8      Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#9      Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#10     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#11     Printer.visitVariableDeclarationList (package:dev_compiler/src/js_ast/printer.dart:649:5)
#12     VariableDeclarationList.accept (package:dev_compiler/src/js_ast/nodes.dart:955:15)
#13     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#14     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#15     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#16     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#17     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#18     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#19     List.forEach (dart:core-patch/growable_array.dart:278:8)
#20     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#21     Printer.blockBody (package:dev_compiler/src/js_ast/printer.dart:248:7)
#22     Printer.visitArrowFun (package:dev_compiler/src/js_ast/printer.dart:1028:7)
#23     ArrowFun.accept (package:dev_compiler/src/js_ast/nodes.dart:1524:50)
#24     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#25     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:633:7)
#26     Printer.visitCall (package:dev_compiler/src/js_ast/printer.dart:763:5)
#27     Call.accept (package:dev_compiler/src/js_ast/nodes.dart:1176:50)
#28     MetaLet.accept (package:dev_compiler/src/compiler/js_metalet.dart:157:29)
#29     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#30     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#31     Printer.visitConditional (package:dev_compiler/src/js_ast/printer.dart:744:5)
#32     Conditional.accept (package:dev_compiler/src/js_ast/nodes.dart:1153:50)
#33     MetaLet.accept (package:dev_compiler/src/compiler/js_metalet.dart:157:29)
#34     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#35     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#36     Printer.visitConditional (package:dev_compiler/src/js_ast/printer.dart:739:5)
#37     Conditional.accept (package:dev_compiler/src/js_ast/nodes.dart:1153:50)
#38     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#39     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#40     Printer.visitConditional (package:dev_compiler/src/js_ast/printer.dart:739:5)
#41     Conditional.accept (package:dev_compiler/src/js_ast/nodes.dart:1153:50)
#42     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#43     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#44     Printer.visitProperty (package:dev_compiler/src/js_ast/printer.dart:1128:5)
#45     Property.accept (package:dev_compiler/src/js_ast/nodes.dart:1752:50)
#46     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#47     Printer.visitObjectInitializer (package:dev_compiler/src/js_ast/printer.dart:1113:7)
#48     ObjectInitializer.accept (package:dev_compiler/src/js_ast/nodes.dart:1721:50)
#49     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#50     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#51     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#52     Printer.visitNew (package:dev_compiler/src/js_ast/printer.dart:756:5)
#53     New.accept (package:dev_compiler/src/js_ast/nodes.dart:1197:50)
#54     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#55     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#56     Printer.visitReturn (package:dev_compiler/src/js_ast/printer.dart:476:7)
#57     Return.accept (package:dev_compiler/src/js_ast/nodes.dart:662:50)
#58     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#59     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#60     List.forEach (dart:core-patch/growable_array.dart:278:8)
#61     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#62     Printer.visitMethod (package:dev_compiler/src/js_ast/printer.dart:1220:7)
#63     Method.accept (package:dev_compiler/src/js_ast/nodes.dart:1918:50)
#64     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#65     Printer.visitClassExpression (package:dev_compiler/src/js_ast/printer.dart:1180:9)
#66     ClassExpression.accept (package:dev_compiler/src/js_ast/nodes.dart:1878:50)
#67     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#68     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#69     Printer.visitAssignment (package:dev_compiler/src/js_ast/printer.dart:713:7)
#70     Assignment.accept (package:dev_compiler/src/js_ast/nodes.dart:986:50)
#71     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#72     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#73     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#74     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#75     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#76     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#77     List.forEach (dart:core-patch/growable_array.dart:278:8)
#78     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#79     Printer.blockBody (package:dev_compiler/src/js_ast/printer.dart:248:7)
#80     Printer.functionOut (package:dev_compiler/src/js_ast/printer.dart:599:5)
#81     Printer.visitFun (package:dev_compiler/src/js_ast/printer.dart:999:5)
#82     Fun.accept (package:dev_compiler/src/js_ast/nodes.dart:1497:50)
#83     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#84     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#85     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#86     Printer.visitCall (package:dev_compiler/src/js_ast/printer.dart:766:5)
#87     Call.accept (package:dev_compiler/src/js_ast/nodes.dart:1176:50)
#88     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#89     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#90     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#91     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#92     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#93     List.forEach (dart:core-patch/growable_array.dart:278:8)
#94     Printer.visitAll (package:dev_compiler/src/js_ast/printer.dart:234:11)
#95     Printer.visitProgram (package:dev_compiler/src/js_ast/printer.dart:242:5)
#96     Program.accept (package:dev_compiler/src/js_ast/nodes.dart:361:50)
#97     JSModuleFile.getCode (package:dev_compiler/src/analyzer/module_compiler.dart:272:10)
#98     JSModuleFile.writeCodeSync (package:dev_compiler/src/analyzer/module_compiler.dart:304:16)
#99     _compile (package:dev_compiler/src/analyzer/command.dart:168:12)
#100    compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#101    compile (package:dev_compiler/src/compiler/shared_command.dart:405:18)
#102    _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#103    _rootRun (dart:async/zone.dart:1124:13)
#104    _CustomZone.run (dart:async/zone.dart:1021:19)
#105    _runZoned (dart:async/zone.dart:1516:10)
#106    runZoned (dart:async/zone.dart:1463:12)
#107    _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#108    AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#109    _rootRun (dart:async/zone.dart:1124:13)
#110    _CustomZone.run (dart:async/zone.dart:1021:19)
#111    _runZoned (dart:async/zone.dart:1516:10)
#112    runZoned (dart:async/zone.dart:1463:12)
#113    AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#114    main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#115    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#116    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```
}

**Comment by vsmenon** [comment]
This trace was going through the deprecated path (`package:dev_compiler/src/analyzer/command.dart`), so should be obsolete now.
