### ISSUE TITLE
True divergence: FP precision differences

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#37335]
JIT-ReleaseIA32 - JIT-DebugX64: !DIVERGENCE! 1.13:3190886612 (output=true)

Gives many subtle differences, like the one below. Given this is 32-bit vs 64-bit, this may be something that needs to be fixed at grammar-level. But perhaps it is real.

```
< 7.963426227304606e-12
---
> 7.963426227304605e-12
```

**Comment by aartbik** [comment]
Another one

KBC-INT-ReleaseX64 - AOT-O3-ReleaseX64: !DIVERGENCE! 1.13:458957384 (output=true)

although this seems due to throw/non-throw difference:

< throws
8c7
< 0.33994272961723915
---
> 0.5339807910033899

**Comment by aartbik** [comment]
The first issue is indeed due to 32-bit vs. 64-bit implementation.

2.9065489552295786e-304 ^ 0.61017368125593 is 6.165122919860247e-186
2.9065489552295786e-304 ^ 0.61017368125593 is 6.165122919860246e-186

**Comment by aartbik** [comment]
Lasse gives some background.

> The language specification just says that Dart `double` values are IEEE-754 64-bit floating point values, but nothing more  The operations are then defined by the platform libraries, which do not promise any specific implementation.
> 
> So, the libraries do not promise anything, and the VM is free to implement them as inconsistently as JavaScript implementations. Consistency is great, but we prefer to not overpromise :)

Given this, I think we should deal with this in DartFuzz by either

- no longer compare 32-bit vs 64-bit execution modes, but only pair same bit size archs
- no longer generate FP operations when 32-bit vs 64-bit modes are run

**Comment by aartbik** [comment]
@feli-citas

**Comment by feli-citas** [comment]
JIT-DEPOPTEVERY-ReleaseX64 - JIT-DebugIA32: !DIVERGENCE! 1.13:483434976 (output=true)
```
< 0.00021296142396241748
---
> 0.00021296142396241743
```

JIT-DebugSIMARM - JIT-ReleaseX64: !DIVERGENCE! 1.13:1962568294 (output=true)
```
< 0.509659585465119_
---
> 0.5096595854651191
```
