### ISSUE TITLE
FileSystemCreateEvent is fired with delay on Mac

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#37342]
Please see https://github.com/dart-lang/co19/issues/186#issuecomment-443188150 and  below. 
Shortly.
1. Create directory `dir`. 
2. Then create directory 'target'. 
3. Start watching `dir`. 
4. In directory `dir` create link pointing to `target`

Result: On Mac, sometimes, FileSystemCreateEvent t for creation of directory `dir` itself is caught. The reason is that `FileSystemCreateEvent` for creation of directory on Mac is fired with 0.1s delay. By that time we may already watch `dir`.

**Comment by brianquinlan** [comment]
This behavior is expected and documented:
https://api.dart.dev/stable/3.1.3/dart-io/FileSystemEntity/watch.html
