### ISSUE TITLE
[Phase 1 - Foundation] Implement static extension methods in VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37359]
This feature is a mostly FE feature so there might not be any work required in the backend. 

However this depends on resolution of two specification issues:

- [x] -Semantics of tear-off equality needs to be finalized. If tear-offs of the same extension method with the same receiver are specified as equal - then changes to VM would be needed to implement that.- Tear offs are not equal per language team decision. 
- [x] Changes to `dart:mirrors` might be required to surface extension methods a good way. 

Depending on how extension methods are desugared in Kernel changes might be required to provide good developer experience (e.g. proper function names in the stack traces, proper variables names in the debugger).

/cc @a-siva

**Comment by leafpetersen** [comment]
Some language tests landed [here](https://dart-review.googlesource.com/c/sdk/+/106908).

**Comment by a-siva** [comment]
Minimal support for extension methods in dart:mirrors has been added.
