### ISSUE TITLE
[Phase 1 - Foundation] Implement static extension methods in CFE/Kernel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37358]
This is tracking issue for implementing static extension methods in CFE/Kernel 

As currently specified this feature might not require any changes to Kernel format.

**Comment by leafpetersen** [comment]
Some language tests landed [here](https://dart-review.googlesource.com/c/sdk/+/106908).

**Comment by johnniwinther** [comment]
On by default in https://dart-review.googlesource.com/c/sdk/+/119327
