### ISSUE TITLE
Implementation of "Static Extension Methods"

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37350]
Language Feature Request - https://github.com/dart-lang/language/issues/41
Implementation Plan - https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/implementation-plan.md

**Comment by leafpetersen** [comment]
Issue for dartfmt support filed [here](https://github.com/dart-lang/dart_style/issues/830).

**Comment by leafpetersen** [comment]
Some language tests landed [here](https://dart-review.googlesource.com/c/sdk/+/106908).

**Comment by aadilmaan** [comment]
Phase 2 issues added to the Epic umbrella bug.

**Comment by vsmenon** [comment]
Closing in favor of remaining open issues.
