### ISSUE TITLE
Analyzer incorrectly rejects type variable bound of `Null`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37366]
The analyzer currently rejects a use of `Null` as an upper bound on a type parameter:

```dart
void bar<T extends Null>() {
}
```

This is a valid upper bound.  See discussion here: https://github.com/dart-lang/sdk/issues/33709 .

The CFE seems to accept this.

**Comment by srawlins** [comment]
Near duplicate of https://github.com/dart-lang/sdk/issues/33701

**Comment by srawlins** [comment]
Analyzer no longer reports an error for this code (both with and without null-safety).
