### ISSUE TITLE
[vm/ffi] Pointer<Null>

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37362]
What do we do with `Pointer<Null>` in the FFI? (This is allowed by the Dart language.)

**Comment by sjindel-google** [comment]
This type could be useful for the `nullptr` constant, so that we don't need to cast it to use it in other contexts:

```Dart
Pointer<Null> nullptr = Pointer<Null>.fromAddress(0);

// ...
void takesPtr(Pointer<Int8> ptr);
// ...

takesPtr(nullptr);  // Actually works!
```

**Comment by dcharkes** [comment]
linking https://github.com/dart-lang/sdk/issues/35756

**Comment by sjindel-google** [comment]
What needs to happen? AFAICT, everything is working as intended.

**Comment by dcharkes** [comment]
We don't actually use `Pointer<Null>` as `nullptr`:

```dart
/// Represents a pointer into the native C memory.
final Pointer<Void> nullptr = Pointer.fromAddress(0);
```

If we can, we should change it to that maybe.

We don't have any tests containing `Pointer<Null>`, we should probably add one.
