### ISSUE TITLE
[vm/ffi] Constructing struct classes from load()/ref in new structs API

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37363]
Struct classes are allowed to define constructors, so long as they don't contain field initializers.

However, when loading a struct reference from a pointer, we need to manufacture an instance of the struct without a reference to any constructor. The proposed design is to skip any user-defined constructors and initialize the object via a synthetic one-argument constructor (which takes the target address).

Other options include allowing or requiring the user to define a constructor (with the correct signature) which would be called instead.

Of course, the user can always invoke their own constructors directly, which would be responsible for calling the super constructor (of `Struct`) with a `Pointer` for the backing memory.

**Comment by dcharkes** [comment]
We have converged on a design taking finalizers and structs by value into account.
