### ISSUE TITLE
Crash in lib_2/mirrors/mirrors_reader_test after unrelated change

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37360]
The `lib_2/mirrors/mirrors_reader_test` started crashing with:
```
/========================================================================\
| lib_2/mirrors/mirrors_reader_test broke (Pass -> Crash, expected Pass) |
\========================================================================/

--- Command "vm" (took 01.000594s):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/lib_2/mirrors/mirrors_reader_test.dart

exit code:
-6

stderr:
../../runtime/vm/object.cc: 16904: error: unreachable code

--- Re-run this test:
python tools/test.py -n dartk-linux-product-x64 lib_2/mirrors/mirrors_reader_test
```
after 1a97ed32b4595b5adecf1f8d390c16e2bf26f658 landed (which is changing only dart code). 

Most likely the change resulted in type finalization order differences which surfaced an existing bug.

/cc @crelier

**Comment by mkustermann** [comment]
The place where it fails is in `runtime/lib/mirrors.cc`:
```c++
static RawAbstractType* InstantiateType(const AbstractType& type,
                                        const AbstractType& instantiator) {
  // Generic function type parameters are not reified, but mapped to dynamic,
  // i.e. all function type parameters are free with a null vector.
  ASSERT(type.IsFinalized());
  ASSERT(type.IsCanonical() || type.IsTypeParameter());

  if (type.IsInstantiated()) {
    return type.Canonicalize();
  }
  TypeArguments& instantiator_type_args = TypeArguments::Handle();
  if (!instantiator.IsNull()) {
    ASSERT(instantiator.IsFinalized());
    instantiator_type_args = instantiator.arguments();
  }
  AbstractType& result = AbstractType::Handle(type.InstantiateFrom(
      instantiator_type_args, Object::null_type_arguments(), kAllFree, NULL,
      Heap::kOld));
  ASSERT(result.IsFinalized());
  return result.Canonicalize();
}
```

The `type.InstantiateFrom(instantiator_type_args, ...)` will be invoked on a `type` which is a `TypeParameter(index: 1)` though the `instantiator_type_args` has only a length of 1:
```
(gdb) p type.ToCString()
$9 = "TypeParameter: name L; index: 1; class: _UnmodifiableListMixin@6027147; bound: List<N>"

(gdb) p instantiator.ToCString ()
$8 = "Type: class 'UnmodifiableInt8ListView', args:[TypeArguments: (H36be58ac) [Type: class 'int']]"

(gdb) p func.ToFullyQualifiedCString ()
$10 = "dart:typed_data__UnmodifiableListMixin@6027147_sublist"

```
This will eventually cause `TypeParameter::Instantiate()` to simply return `null`:
```c++
RawAbstractType* TypeParameter::InstantiateFrom(
    const TypeArguments& instantiator_type_arguments,
    const TypeArguments& function_type_arguments,
    intptr_t num_free_fun_type_params,
    TrailPtr instantiation_trail,
    Heap::Space space) const {
  ...
  if (instantiator_type_arguments.Length() <= index()) {
    // InstantiateFrom can be invoked from a compilation pipeline with
    // mismatching type arguments vector. This can only happen for
    // a dynamically unreachable code - which compiler can't remove
    // statically for some reason.
    // To prevent crashes we return AbstractType::null(), understood by caller
    // (see AssertAssignableInstr::Canonicalize).
    return AbstractType::null();
  }
  ...
}
```

The `dart:typed_data__UnmodifiableListMixin@6027147_sublist` belongs to an abstract class (which is used as a mixin):
```dart
abstract class _UnmodifiableListMixin<N, L extends List<N>, TD extends TypedData> {
  L sublist(int start, [int end]) { ... }
}
```

It's not clear to me why we get a non-expanded instantiator type argument vector here (for an abstract class).

@crelier @rmacnak-google Maybe you guys know?

**Comment by rmacnak-google** [comment]
This might be related to the ClassMirror._trueSuperclass. ClassMirrors can represent the declaration of a class (List<E>) or a particular instantiation (List<int>). I haven't followed all the changed to how mixins are implemented, but I suspect there's something related to mirrors having to skip links in the inheritance chain and instanitators getting out of sync.

**Comment by crelier** [comment]
I observe the same thing as Martin.
The instantiator, which is properly marked as finalized, contains only a single type argument, which is surprising. In the earlier VM implementation, a mixin application class would extend a synthetic class parameterized with both the type parameters of the application and of the mixin class. In this case, I would have expected class UnmodifiableInt8ListView to be parameterized with at least 3 type parameters, but it only has one.

To verify that the issue was limited to mirrors, I modified a type data test to throw list.runtimeType where list is of type UnmodifiableInt8ListView. Surprisingly, this type has only only type argument 'int'.

So it seems like the new mixin implementation is behaving very differently than the previous one. Is it documented anywhere?

**Comment by mkustermann** [comment]
> So it seems like the new mixin implementation is behaving very differently than the previous one. Is it documented anywhere?

I don't know if this is documented anywhere. But it is easy to see what the CFE feeds to the VM by dumping the kernel IR:

```
sdk % dart pkg/vm/bin/gen_kernel.dart --platform=out/ReleaseX64/vm_platform_strong.dill -o tests/lib_2/mirrors/mirrors_reader_test.dart{.dill,} 
sdk % dart pkg/vm/bin/dump_kernel.dart tests/lib_2/mirrors/mirrors_reader_test.dart.dill{,.txt}   
sdk % vim tests/lib_2/mirrors/mirrors_reader_test.dart.dill.txt
<...>
```

There we can see:
```
abstract class UnmodifiableListBase<E extends core::Object = dynamic>
    extends col::ListBase<_in::UnmodifiableListBase::E>
    implements _in::UnmodifiableListMixin<_in::UnmodifiableListBase::E> {
  ...
}

abstract class _UnmodifiableInt8ListView&UnmodifiableListBase&_UnmodifiableListMixin
    extends _in::UnmodifiableListBase<core::int>
    implements typ::_UnmodifiableListMixin<core::int, typ::Int8List, typ::Int8List> {
  ...
}
class UnmodifiableInt8ListView
    extends typ::_UnmodifiableInt8ListView&UnmodifiableListBase&_UnmodifiableListMixin
    implements typ::Int8List {
  ...
}
```

So the mixin application class is not generic: The `UnmodifiableInt8ListView` supplies instantiated type arguments to the mixin, so the mixin application class (containing the copied bodies) will have all it's type parameters replaced with the instantiated types. This leaves instances of  `UnmodifiableInt8ListView` to have a type argument vector of length 1 (which is the type parameter of the `UnmodifiableListBase` base class). So it's clear why the instantiator has only length 1.

But also notice that the test is trying to instantiate `"TypeParameter: name L; index: 1; class: _UnmodifiableListMixin@6027147; bound: List<N>"`. This is not the mixin application class, it is rather the abstract mixin class itself (which is abstract: i.e. we can have no instances of it, and therefore can also not have instantiator type argument vector for it).

To me this looks like we use an instantiator from some instance (`UnmodifiableInt8ListView`) to instantiate a type from an "unrelated" class  (`_UnmodifiableListMixin`). 


For reference, the Dart code is this:
```dart
class UnmodifiableInt8ListView extends UnmodifiableListBase<int>
    with _UnmodifiableListMixin<int, Int8List, Int8List>
    implements Int8List { ... }

abstract class _UnmodifiableListMixin<N, L extends List<N>,
    TD extends TypedData> { ... }

abstract class UnmodifiableListBase<E> = ListBase<E> with UnmodifiableListMixin<E>;
abstract class UnmodifiableListMixin<E> implements List<E> { ... }
abstract class ListBase<E> extends Object with ListMixin<E> { ... }
abstract class ListMixin<E> implements List<E> { ... }
```

**Comment by a-siva** [comment]
saw this failure again on [vm-kernel-mac-release-simdbc64/3322](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-release-simdbc64/3322)

**Comment by rmacnak-google** [comment]
Class::DeclarationType for UnmodifiableInt8ListView yields ```Type: class 'UnmodifiableInt8ListView', args:[TypeArguments: (H2bd6c745) [Type: class 'int']]```, which I would expect to have 4 type arguments not 1.
