### ISSUE TITLE
vm/dart/disassemble_determinism_test failed on vm-kernel-win-release-x64

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#37379]
The following tests failed (needs approval):
vm/dart/disassemble_determinism_test failed again (Timeout, expected Pass)
There were test failures.

Created this issue for investigation and added an approval for the timeout.

**Comment by ZichangG** [comment]
Worked well on my local machine with latest sdk.

**Comment by a-siva** [comment]
Can you remove the approval and see if it works on the buildbot

**Comment by ZichangG** [comment]
It starts passing now. I will close this issue.

**Comment by liamappelbe** [comment]
It's timing out again consistently as of [this CL](https://dart-review.googlesource.com/c/sdk/+/108320). /cc @bwilkerson 

Logs:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8908400765563754368/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

I'm approving the timeout for now.

**Comment by ZichangG** [comment]
This test consistently worked on my windows station with around 18s to finish. Timeout is not surprising to me if running on a slower bot. It has already been marked as "slow" test on windows. I will close it for now.
