### ISSUE TITLE
Error from text file saved in Windows 10 notepad.exe

### ISSUE THREAD

**Issue by gitboss** [dart-lang/sdk#37378]
Error from text file saved in Windows 10 notepad.exe, however same file saved in Notepad++ with EOL conversion set to unix works.

Dart SDK Version : 
Dart VM version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "windows_x64"

OS : Windows 10.

Steps to reproduce : 

1) Copy some string content from MS Excel to Windows Notepad
2) Save the contents in notepad as check.txt. 
3) Copy the same string content from  MS Excel to Notepad++ 
4) In Notepad++ change the EOL conversion to Unix LF 
5) Save the contents in Notepad++ as works.txt. 

Run the following code : 

```
import 'dart:io';

Future main(List<String> args) async {
  testFile('works.txt');
  testFile('check.txt');
}

void testFile(String filename) {
  String contents = new File(filename).readAsStringSync();
  List<String> puzzles = contents.split("\n");

  for (int i = 0; i < puzzles.length; i++) {
    List<int> puzzle = puzzles[i].split("").map(int.parse).toList();
    print('You should see 1 here >>>> ${puzzle[i]}');
  }
}
```

The code works as expected on works,txt file, however generates an error for check,txt. The output from the code above is as follows : 

```
D:\numbers\numbers\lib>dart check.dart
check.dart:1: Warning: Interpreting this as package URI, 'package:numbers/check.dart'.
You should see 1 here >>>> 1
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 1
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
#1      testFile (package:numbers/check.dart:14:47)
#2      main (package:numbers/check.dart:4:3)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

I have attached the 3 files.
[lib.zip](https://github.com/dart-lang/sdk/files/3332053/lib.zip)

**Comment by lrhn** [comment]
The two files differ. The `works.txt` file contains the string `"1234567890\n"` and the file `check.txt` contains the string `"1234567890\r\n". The `"\r\n"` sequence is the DOS/Windows line break character.

Both files fail with the code provided here, so you might want to check whether this is the actual code that you are having problems with. The error message printed here comes from the `works.txt` file.
When you split `"1234567890\n"` on `"\n"`, you get two results: `"1234567890"` and `""` (the empty string), so `puzzles.length` is 2, and when `i` is 1, the `puzzle` becomes the empty list and the print lines does `puzzle[1]` and throws the error reported here.

If you use `check.txt`, the split by `\n` gives two strings: `"1234567890\r"` and `""`. This is then split on `""` and put through `int.parse`. When that reaches `int.parse` of `"\r"`, it fails with a format exception.

To split into lines in a platform independent way, you can use the `LineSplitter` converter from `dart:convert`:
```dart
List<String> puzzles = LineSplitter().convert(content);
...
```
The `LineSplitter` converter recognizes carriage return, newline, and carriage return followed by newline as line terminators.

So, all in all, this seems to be working as intended. The `"\n"` string only represents the single newline character (U+000A), not the platform dependent line terminator sequence.

**Comment by gitboss** [comment]
Thanks for checking. Your answer clears my confusion.
