### ISSUE TITLE
Error compiling dartdevc module:flutter_html|lib/rich_text_parser.ddc.js

### ISSUE THREAD

**Issue by martinory** [dart-lang/sdk#37389]
I'm trying to display a string of html code and tried to use this library "flutter_html" where I would change the pubspec as seen under (as well as package:flutter_web/...). Btw how can I display raw html as a string?

```

name: flutter_html
description: A Flutter widget for rendering static html tags as Flutter widgets. (Will render over 70 different html tags!)
version: 0.10.4
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"
  
dependencies:
  html: ^0.14.0
  flutter_web: any
  flutter_web_ui:
    any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


```

[INFO] Reading cached asset graph completed, took 265ms
[INFO] Checking for updates since last build completed, took 808ms
[INFO] Serving `web` on http://localhost:8080
[INFO] Running build completed, took 226ms
[INFO] Caching finalized dependency graph completed, took 158ms
[SEVERE]build_web_compilers:entrypoint on web/main.dart (cached): AssetNotFoundException: flutter_html|lib/rich_text_parser.ddc.js

[SEVERE]build_web_compilers:ddc on package:flutter_html/rich_text_parser.ddc.module (cached): Error compiling dartdevc module:flutter_html|lib/rich_text_parser.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\tools\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_html/rich_text_parser.ddc.js --source-map -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/meta/meta.ddc.dill=packages/meta/meta -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/collection/collection.ddc.dill=packages/collection/collection -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/flutter_html/image_properties.ddc.dill=packages/flutter_html/image_properties -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/path/path.ddc.dill=packages/path/path -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/charcode/ascii.ddc.dill=packages/charcode/ascii -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/charcode/charcode.ddc.dill=packages/charcode/charcode -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/source_span/source_span.ddc.dill=packages/source_span/source_span -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/csslib/parser.ddc.dill=packages/csslib/parser -s C:\Users\User\AppData\Local\Temp\scratch_spaceb160edbc-9914-11e9-9bb2-aa3992dd563c\packages/html/dom.ddc.dill=packages/html/dom --packages file:///C:/Users/User/AppData/Local/Temp/kernel_builder_b160edc0-9914-11e9-9bb2-aa3992dd563c/.packages --module-name packages/flutter_html/rich_text_parser --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map package:flutter_html/rich_text_parser.dart
    dart --version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "windows_x64"

Crash when compiling packages/flutter_html/rich_text_parser.dart,
at character offset 9686:
Bad state: No element
#0      List.last (dart:core-patch/array.dart:121:5)
#1      Source.getLocation (package:kernel/ast.dart:6050:59)
#2      Component.getLocation (package:kernel/ast.dart:5812:31)
#3      _getLocationInComponent (package:kernel/ast.dart:6165:22)
#4      Constructor._getLocationInEnclosingFile (package:kernel/ast.dart:1430:12)
#5      TreeNode.location (package:kernel/ast.dart:165:12)
#6      BodyBuilder.throwNoSuchMethodError (package:front_end/src/fasta/kernel/body_builder.dart:1488:27)
#7      BodyBuilder.buildStaticInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3333:13)
#8      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3652:24)
#9      KernelTypeUseGenerator.buildPropertyAccess (package:front_end/src/fasta/kernel/kernel_expression_generator.dart:1332:25)
#10     SendAccessGenerator.withReceiver (package:front_end/src/fasta/kernel/kernel_expression_generator_impl.dart:290:23)
#11     BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:1457:17)
#12     BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:1368:14)
#13     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3909:22)
#14     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3835:13)
#15     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4904:15)
#16     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4876:12)
#17     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4857:14)
#18     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4836:13)
#19     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4572:12)
#20     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4128:14)
#21     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4067:12)
#22     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3863:13)
#23     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3835:13)
#24     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4904:15)
#25     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4876:12)
#26     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4857:14)
#27     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4836:13)
#28     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4572:12)
#29     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4128:14)
#30     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3907:21)
#31     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3835:13)
#32     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3800:13)
#33     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5183:16)
#34     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3625:14)
#35     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#36     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5571:15)
#37     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3629:14)
#38     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#39     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5273:13)
#40     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#41     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#42     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5571:15)
#43     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3629:14)
#44     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#45     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5273:13)
#46     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#47     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#48     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5571:15)
#49     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3629:14)
#50     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#51     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5273:13)
#52     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#53     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#54     Parser.parseStatementsInSwitchCase (package:front_end/src/fasta/parser/parser.dart:5951:17)
#55     Parser.parseSwitchBlock (package:front_end/src/fasta/parser/parser.dart:5910:15)
#56     Parser.parseSwitchStatement (package:front_end/src/fasta/parser/parser.dart:5841:13)
#57     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3655:14)
#58     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#59     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5571:15)
#60     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3629:14)
#61     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#62     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5273:13)
#63     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#64     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#65     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5279:15)
#66     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#67     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#68     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5279:15)
#69     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#70     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#71     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5571:15)
#72     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3629:14)
#73     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#74     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5273:13)
#75     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#76     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#77     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5279:15)
#78     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3641:14)
#79     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3615:20)
#80     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3520:15)
#81     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:834:14)
#82     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:587:5)
#83     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3176:14)
#84     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#85     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2844:15)
#86     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1828:13)
#87     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1788:14)
#88     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#89     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#90     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#91     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:278:14)
<asynchronous suspension>
#92     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#93     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#94     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#95     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#96     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:308:28)
<asynchronous suspension>
#97     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#98     new Future.sync (dart:async/future.dart:224:31)
#99     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#100    _rootRun (dart:async/zone.dart:1124:13)
#101    _CustomZone.run (dart:async/zone.dart:1021:19)
#102    _runZoned (dart:async/zone.dart:1516:10)
#103    runZoned (dart:async/zone.dart:1463:12)
#104    CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#105    IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#106    _compile (package:dev_compiler/src/kernel/command.dart:268:64)
<asynchronous suspension>
#107    compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#108    compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#109    _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#110    _rootRun (dart:async/zone.dart:1124:13)
#111    _CustomZone.run (dart:async/zone.dart:1021:19)
#112    _runZoned (dart:async/zone.dart:1516:10)
#113    runZoned (dart:async/zone.dart:1463:12)
#114    _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#115    AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#116    _rootRun (dart:async/zone.dart:1124:13)
#117    _CustomZone.run (dart:async/zone.dart:1021:19)
#118    _runZoned (dart:async/zone.dart:1516:10)
#119    runZoned (dart:async/zone.dart:1463:12)
#120    AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#121    main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#122    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#123    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:842:7)
#1      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:587:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3176:14)
#3      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#4      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2844:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1828:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1788:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:278:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:308:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#25     _compile (package:dev_compiler/src/kernel/command.dart:268:64)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#28     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale sv-SE)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\User\flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by megadrazz** [comment]
quer um conselho desista não perca seu tempo mano!

**Comment by sigmundch** [comment]
Thanks for filing a bug. We actually need some additional data to be able to help. It looks like the compiler run into some issues while parsing your code and didn't recover gracefully. 

In particular this section "Crash when compiling packages/flutter_html/rich_text_parser.dart,
at character offset 9686:" of the error message seems to indicate where in the code the problem was.

I haven't tested this, but I wonder if for example typing an html block outside a string could potentially trigger an unhandled case in the parser?

We are happy to look at fixing the problem, but we'd need some example text that triggers this isue before we can help.
