### ISSUE TITLE
Analyzer: Spurious and obsolete error message

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#37383]
Consider the following program:

```dart
import 'dart:async';

FutureOr<void> f(int val) async {
  if (val != 1) return;
  return () => print('void void void!');
}
```

With the `dartanalyzer` from c4af35cdf3cbd2b2ec11f0a91f721aea014d3fd0 we get the following response:

```
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201906/n012.dart|4|17|6|Functions can't include return statements both with and without values.
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201906/n012.dart|5|3|6|Functions can't include return statements both with and without values.
```

However, there is no rule which makes it an error (or warning) to have two statements of the form `return;` and `return e;` in the same function body (that was true a while back, but that's all gone with 5d8501a07ea506ed6c88c20502fd224886d51881).

The error that we _should_ have is that

- `f` is asynchronous and returns `FutureOr<void>` (so the flattened return type is `void`).
- `return () => print('void void void!')` returns a function type (so the flattened _returned_ type is again that function type).
- which matches [this error case](https://github.com/dart-lang/language/blob/24cfec5c63f6f17d4dabfe4af9c8c127adad19a3/specification/dartLangSpec.tex#L12966).

However, the following program shows that the analyzer uses the obsolete _meaning_ as well as the obsolete text associated with this situation:

```dart
import 'dart:async';

FutureOr<void> f(int val) async {
  dynamic d = null;
  if (val != 1) return;
  return d;
}
```

The response is as follows:

```
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201906/n014.dart|5|17|6|Functions can't include return statements both with and without values.
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201906/n014.dart|6|3|6|Functions can't include return statements both with and without values.
```

But this is not an error, because the flattened returned type is now `dynamic`.

So these two test programs may exhibit the same underlying issue, but it still makes sense to take both tests into account because the first one should report a different error, and the second one should not report any errors at all.

Note that issue #37384 is somewhat similar, but for the front end.

**Comment by srawlins** [comment]
The analyzer now reports the desired error:

> error • A value of type 'void Function()' can't be returned from the function 'f' because it has a return type of 'FutureOr<void>'. • a.dart:5:10 • return_of_invalid_type
