### ISSUE TITLE
Analyzer, what replaces parameterKind

### ISSUE THREAD

**Issue by tonosama-atlacatl** [dart-lang/sdk#37397]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer 0.35.3

* Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "macos_x64"
* macOS Mojave 10.14.5

**issue:**
**ParameterElement's** **parameterKind** is marked as "Deprecated", no mention of what replaces it. A quick look at Analyzer yields extensive use of **ParameterKind** still.

**Questions:**

- What replaces parameterKind?
- How can I redo this:
```arg.parameterKind == ParameterKind.REQUIRED ```

**Comment by tonosama-atlacatl** [comment]
**SO** to the rescue: https://stackoverflow.com/questions/56811925/analyzer-what-replaces-parameterkind?noredirect=1#comment100181391_56811925

Still, this deprecation business could use some notes.

**Comment by bwilkerson** [comment]
Sorry about the lack of information! We are trying to be more careful about providing deprecation information than we used to be, but we have not had time to go back and fix the lack of information for all of the existing deprecated APIs. I now have a CL out to add the answer to this question (https://dart-review.googlesource.com/c/sdk/+/107721).
