### ISSUE TITLE
NoSuchMethod on null divergence

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#37408]
KBC-INT-ReleaseX64 - AOT-O3-ReleaseX64: !DIVERGENCE! 1.13:458957384 (output=true)

due to throw/non-throw difference:

```dart
< throws
8c7
< 0.33994272961723915
---
> 0.5339807910033899
```

This can be reproduced as a simple JIT vs AOT difference:
```dart
throws NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble() #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      atan2 (dart:math-patch/math_patch.dart:130:54)
#2      foo2 (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:49:55)
#3      X0.run (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:193:13)
#4      main (file:///usr/local/google/home/ajcbik/Repo/DART/fuzz.dart:199:14)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


```

**Comment by aartbik** [comment]
The AOT run does not throw on b == null in the following

```dart
@pragma("vm:exact-result-type", "dart:core#_Double")
double atan2(num a, num b) => _atan2(a.toDouble(), b.toDouble());
```

**Comment by aartbik** [comment]
@feli-citas

**Comment by aartbik** [comment]
The exact conditions must be just right, but here is a small reproducer we can use as regression test.
```dart
import "package:expect/expect.dart";

import 'dart:math';

String var0 = '5Zso';

double foo2(String par1) {
  return atan2(0.16964141699241508, num.tryParse('\u2665vDil'));
}

class X0  {
  void run() {
    foo2(var0);
  }
}

main() {
  bool x = false;
  try {
    new X0().run();
  } catch (exception, stackTrace) {
    x = true;
  }
  Expect.isTrue(x);
}
```

**Comment by aartbik** [comment]
The expected flow of speculative inlining tan2 is that

```dart
  8:     v21 <- Unbox:12(v12) T{_Double} 
 10:     v18 <- InvokeMathCFunction:12(MathAtan2, v21, v21) T{_Double} 
```
will trigger a re-compilation, suppressing inlining of deopt_id:12. However, in the failing case we get the following **intrinsic graph** the following, where v3 is incorrectly assumed non-null.

```dart
B1 pre#=1 post#=0
doms(#0)=
succ=
preds=B0,
B1[function entry]:24 {
      v0 <- Parameter(1) T{num?}
      v3 <- Parameter(0) T{_Double}
} specu repr=tagged
    v1 <- Unbox(v0) env specu can-deopt repr=double #uses=1 #env-uses=0
    v4 <- Unbox(v3) specu repr=double #uses=1 #env-uses=0
    v6 <- InvokeMathCFunction(MathAtan2, v1, v4) specu repr=double #uses=1 #env-uses=0
    v8 <- Box(v6) specu repr=tagged #uses=1 #env-uses=0
    Return:26(v8) specu repr=tagged
```

**Comment by aartbik** [comment]
@mraleph or @alexmarkov, can you give a few pointers on where GraphIntrinsify() gets the types for the incoming parameters?

**Comment by aartbik** [comment]
@alexmarkov pointed out, correctly, that the parameters are shown in reverse order. So the type of the *second* is correctly nullable. My mistake. Back to debugging.

**Comment by aartbik** [comment]
It looks like the reversal happens in
```C
static bool BuildInvokeMathCFunction(BlockBuilder* builder,
                                     MethodRecognizer::Kind kind,
                                     intptr_t num_parameters = 1) {
....
 for (intptr_t i = 0; i < num_parameters; i++) {
    const intptr_t parameter_index = (num_parameters - i - 1);
    Definition* value =
        builder->AddParameter(parameter_index, /*with_frame=*/false);
   ....
}
```
The only two intrinsics that pass more than one parameter are MathAtan2 and DoubleMod. So it seems the parameter_index calculation is just wrong and we never noticed (which is likely, since most of the time we inline the recognized method much earlier for non-null parameters).

**Comment by aartbik** [comment]
I prototyped storing index() and nindex() (not-adjusted index ;-)) for "frameless" parameters. When nindex() is queried during type propagation to get to the local name, and everything else is left "as is", everything works fine!!

```dart
B1[function entry]:24 {
      v0 <- Parameter(1) T{_Double} // now correctly identified as "a", with double type
      v3 <- Parameter(0) T{num?}    // now correctly identified as "b", with nullable type
} specu repr=tagged
    v1 <- Unbox(v0) specu repr=double #uses=1 #env-uses=0
    v4 <- Unbox(v3) env specu can-deopt repr=double #uses=1 #env-uses=0
    v6 <- InvokeMathCFunction(MathAtan2, v1, v4) specu repr=double #uses=1 #env-uses=0
    v8 <- Box(v6) specu repr=tagged #uses=1 #env-uses=0
    Return:26(v8) specu repr=tagged
```
@mraleph or @alexmarkov or @mkustermann, any better way of fixing this?

**Comment by alexmarkov** [comment]
Almost all uses of `ParameterInstr::index()` do not account for reverse indices in ParameterInstr with `base_reg() == SPREG`:

https://github.com/dart-lang/sdk/blob/75f6822c704045aaaa47a84d0711324a05a44ce3/runtime/vm/compiler/backend/flow_graph.cc#L310

https://github.com/dart-lang/sdk/blob/75f6822c704045aaaa47a84d0711324a05a44ce3/runtime/vm/compiler/backend/flow_graph.cc#L346

https://github.com/dart-lang/sdk/blob/75f6822c704045aaaa47a84d0711324a05a44ce3/runtime/vm/compiler/backend/type_propagator.cc#L1018-L1020

https://github.com/dart-lang/sdk/blob/75f6822c704045aaaa47a84d0711324a05a44ce3/runtime/vm/compiler/backend/type_propagator.cc#L1074-L1075

It looks like only register allocator accounts for that:

https://github.com/dart-lang/sdk/blob/75f6822c704045aaaa47a84d0711324a05a44ce3/runtime/vm/compiler/backend/linearscan.cc#L737-L741

I think ParameterInstr::index() should always return non-adjusted index of a parameter in order to avoid confusion. We can reverse index in register allocator, or introduce a new method in ParameterInstr such as `offset_in_words()` to return offset relative to `base_reg()`.

**Comment by aartbik** [comment]
Thanks for your input @alexmarkov. I will make that so.

**Comment by aartbik** [comment]
Note that the pending fix (https://dart-review.googlesource.com/c/sdk/+/109550) has the advantage that parameters appear in the intuitive order again and with the intuitive index (with the sp_index just a mere code generation issue, although we could display this in il_printer.cc too if needed).

```dart
B0[graph]:22
B1[function entry]:24 {
      v0 <- Parameter(0) T{_Double}   // a
      v3 <- Parameter(1) T{num?}        // b
}
    v1 <- Unbox(v0)
    v4 <- Unbox(v3)
    v6 <- InvokeMathCFunction(MathAtan2, v1, v4)
    v8 <- Box(v6)
    Return:26(v8)
```
