### ISSUE TITLE
On my android studio

### ISSUE THREAD

**Issue by LeonelAugusto** [dart-lang/sdk#37411]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.5.0-dev.0.0`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by hpoit** [comment]
What's the issue here? The issue header doesn't help either.

**Comment by a-siva** [comment]
Not sure we have enough information in this issue to figure out problem, if you are able to post more information about it reopen it.
