### ISSUE TITLE
DDK does not initialize named arguments with their default values for cross-module noSuchMethod invocations

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37416]
Modular repro here: https://dart-review.googlesource.com/c/sdk/+/107821
Ran with: 
`dart pkg/dev_compiler/test/modular_suite.dart --configuration-name dartdevk-linux-release --verbose --filter mock`

The expected output is `Symbol(not_null) true`, but the actual output is `Symbol(not_null) null`. We also see the expected output if everything is collected into a single file.

This is also causing some tests that use Mockito to fail.

DDK accesses VariableDeclaration.initializer for default parameters. For cross-module parameters with default values, this is null. Is there some other logic we should be performing?

**Comment by Markzipan** [comment]
@askeksa-google Thoughts and feelings?

**Comment by mraleph** [comment]
@Markzipan your test now prints `Symbol(not_null) true` let us know if something still does not work.

**Comment by Markzipan** [comment]
Thanks, Slava!
