### ISSUE TITLE
Make front-end-linux-release-x64-try faster

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37428]
front-end-linux-release-x64-try takes 10 mins longer (46 minutes) than the next slowest bot (ddc-linux-release-chrome-try, 36 minutes).
I find I'm waiting for front-end-linux-release-x64-try a lot.
I think they both take way too long, but it would be less painful if we could trim some time off the slowest.

The big steps are:
( 8 mins 25 secs )unit tests
( 8 mins 8 secs )fasta sdk tests
( 22 mins 51 secs )fasta co19_2 tests

It looks like sharding "fasta co19_2 tests" might do the trick.

**Comment by athomas** [comment]
Fixed by b64ab73.
