### ISSUE TITLE
Analyzer with implicit-dynamic turned off fails to flag typedef

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/sdk#37437]
I have a Flutter project with this in its analysis_options.yaml file:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

In a code file, I've got this:

```dart
typedef MyFunc = Function(int x);
anotherFunc(int x) { }
```

The first line is not flagged as an issue by the analyzer, but the second one is. Is that by design, or should the analyzer have declared both to be errors?

### Currently running:

Dart VM version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64"

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

**Comment by srawlins** [comment]
`implicit-dynamic` is now deprecated.
