### ISSUE TITLE
Specify recommended dart:mirrors behaviour for extension methods

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#37433]
@mraleph commented on [Tue Jun 25 2019](https://github.com/dart-lang/language/issues/421)

This is a request to specify how (and if) extensions and their methods are visible through `dart:mirrors`. 

This does not have to be a normative specification, but can simply be a recommendation for implementations. 

---

@lrhn commented on [Tue Jun 25 2019](https://github.com/dart-lang/language/issues/421#issuecomment-505405718)

*This will be a suggestion, but people actually using `dart:mirrors` are invited to chip in!*

Dart mirrors straddle the gap between run-time object mirrors and declaration mirrors.
Since extensions have no run-time presence, they are neither objects nor types, I guess they should only be available as declaration mirrors.

Also, since the name does not have any value or type associated, it's not possible to `reflect(extension)` or `reflectClass(extension)`. So, there can be no direct access to the extension, you have to find the declaring library and look through the declarations, or tear off an extension method, reflect on that, and traverse the mirrors to the declaring `ExtensionMirror`.

Reflecting on such a torn off closure would give a `ClosureMirror` and the `function` of that would give a `FunctionMirror`. (Maybe `FunctionMirror` should get an `isExtension` flag to distinguish instance methods from extension methods). The `owner` of that will then have to be an `ExtensionMirror` instead of a `ClassMirror`.

Extension declarations look like a class declarations. They have static and instance members (no constructors, no fields, but that's a proper subset). As such, the API for an `ExtensionMirror` should likely mimic a subset of the `ClassMirror` API. It is not a `TypeMirror`, though. It *is* an `ObjectMirror` because you can invoke static members on it.

So, perhaps an API for `ExtensionMirror` could look like:
```dart
abstract class ExtensionMirror implements DeclarationMirror, ObjectMirror {
  Map<Symbol, DeclarationMirror> get declarations;                         
  Map<Symbol, MethodMirror>      get instanceMembers;                 
  TypeMirror                     get onType;           
  Map<Symbol, MethodMirror>      get staticMembers;                   
  List<TypeVariableMirror>       get typeVariables;                  

  // From DeclarationMirror:
  bool                           get isPrivate;  
  bool                           get isTopLevel; 
  SourceLocation                 get location;             
  List<InstanceMirror>           get metadata;                   
  DeclarationMirror              get owner;                   
  Symbol                         get qualifiedName;
  Symbol                         get simpleName;   

  // From ObjectMirror:
  dynamic                        delegate(Invocation invocation);
  InstanceMirror                 getField(Symbol fieldName);
  InstanceMirror                 invoke(Symbol memberName, List positionalArguments, 
                                       [Map<Symbol, dynamic> namedArguments]);
  InstanceMirror                 setField(Symbol fieldName, Object value);
}
```
An extension can be unnamed, and then it might not have a `simpleName` or `qualifiedName`. The system is free to introduce a fresh private name for unnamed extensions if that makes things easier.

That's a completely naïve design, simply based on making every part of the declaration available.

**Comment by mit-mit** [comment]
Moving to the SDK repo; this is not considered a language issue.

**Comment by leafpetersen** [comment]
Is there any work planned for this before we ship?

**Comment by mraleph** [comment]
@a-siva Siva, do we want to support extension in the mirrors in any special way? (e.g. in the way that Lasse suggests?).

**Comment by a-siva** [comment]
I think there are two aspects here

- minimal support : we should have the ability of identifying these methods as static extension methods in the VM internal _Function_ object. This ensures that at the minimum we will support _isExtension_ in _FunctionMirror_ . In addition we will be able to produce proper display names for these functions in stack traces.

- full support : complete mirror support with a version of the API which might be similar to the comment above by Lasse.

At the minimum we should do the minimal support for the D26 release and maybe plan on full support depending on whether there is a strong user requirement for it.

**Comment by mit-mit** [comment]
Minimal support SGTM

**Comment by a-siva** [comment]
Minimal support of adding an IsExtension function in MethodMirror and VariableMirror is done.
Will keep this issue open in case we want to implement the full spec described above.

**Comment by a-siva** [comment]
Closing this as we don't plan on implementing the full spec.
