### ISSUE TITLE
corelib_2: DateTime 'testFarAwayDates' test fail on web platforms

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37442]
`testFarAwayDates` fails because it relies on non-web integer literals.
Are there web integer values that are just as interesting?

`testExtremes` fails in one of the `-_MAX_MILLISECONDS` cases and needs further analysis.

These tests are being split out to increase coverage of the remaining tests (https://dart-review.googlesource.com/c/sdk/+/108220)

**Comment by sigmundch** [comment]
testExtremes was fixed in https://github.com/dart-lang/sdk/commit/751a47f942268c3c61561f4ee77466f1e5066930

only testFarAwayDates needs to be fixed now.
