### ISSUE TITLE
Array map from Object

### ISSUE THREAD

**Issue by eagle-design** [dart-lang/sdk#37458]
The soloution that i found is to creating new Array and push into that , but map must do this job !
---
The argument type '(TabItem) → TabItemTile' can't be assigned to the parameter type '(dynamic) → dynamic'.

````
List tabs = [
      TabItem(
        icon: Icons.home,
      ),
    ];

tabs = tabs.map((TabItem item) => TabItemTile(
          item: item,
        ));

````

**Comment by mraleph** [comment]
Try either 

```
List<TabItem> tabs = [TabItem(icon: Icons.home,),];
```

or 

```dart
var tabs = [TabItem(icon: Icons.home,),];
```

Currently you have essentially written 

```dart
List<dynamic> tabs = ...;
```

which leads to the error above.

Also note that `map` does not return a `List`, but rather an `Iterable`. So you need to write

```dart
var tabs = [TabItem(icon: Icons.home,),];
tabs = tabs.map((TabItem item) => TabItemTile(
          item: item,
        )).toList();
```
