### ISSUE TITLE
flutter web cannot run after update new version

### ISSUE THREAD

**Issue by kimweichew** [dart-lang/sdk#37459]
RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[]  (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte 
package:kernel/binary/ast_from_binary.dart:104
#2      BinaryBuilder.readUint32 
package:kernel/binary/ast_from_binary.dart:124
#3      BinaryBuilder.readComponent 
package:kernel/binary/ast_from_binary.dart:444
#4      ProcessedOptions.loadComponent 
package:front_end/…/base/processed_options.dart:391
#5      initializeIncrementalCompiler 
package:front_end/…/api_unstable/ddc.dart:233
<asynchronous suspension>
#6      _compile  (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile  (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile  (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#23     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by kimweichew** [comment]
#16     _rootRun  (dart:async/zone.dart:1124:13)
#17     _CustomZone.run  (dart:async/zone.dart:1021:19)
#18     _runZoned  (dart:async/zone.dart:1516:10)
#19     runZoned  (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run 
package:bazel_worker/…/worker/async_worker_loop.dart:33
<asynchronous suspension>
#21     main  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

[SEVERE] Failed after 385ms
[INFO] ------------------------------------------------------------------------

**Comment by vsmenon** [comment]
Merging to:

https://github.com/dart-lang/sdk/issues/38102
