### ISSUE TITLE
Statements inside if conditions

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#37462]
Statements inside control statement conditions to store it, check it and also scope it inside the control statement block would be very useful.

```dart
if((Point point = parseCursorPosition(chars)) != null) {
  // Do something with point
}
```

or

```dart
if(Point point = parseCursorPosition(chars); point != null) {
  // Do something with point
}
```

This feature is very popular in golang world.

**Comment by tejainece** [comment]
Right now, this is possible:

```dart
Point point;
if((point = parseCursorPosition(chars)) != null) {
  // Do something with point
}
```

**Comment by a-siva** [comment]
Moved this issue over to dart-lang/language under https://github.com/dart-lang/language/issues/443.

Closing it over here.
