### ISSUE TITLE
[vm/ffi] fromFunction and asFunction drop type argument and return dynamic

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37464]

**Comment by sjindel-google** [comment]
Can you please clarify the title/description of the task?

I'm not sure if you're identifying a bug or feature.

**Comment by dcharkes** [comment]
If I remember correctly, we created this task during a discussion about the API. I think the goal was to remove locations in the source code which are invariant/covariant/contravariant. By removing the type argument from `asFunction()` it becomes invariant by construction (but dynamically typed).

For `fromFunction` I don't remember what we discussed.

If there is a bug in variance checking for `fromFunction` and `asFunction` then this should be classified as bug. Though a bug could also be fixed without changing the API.

**Comment by sjindel-google** [comment]
Ah yes, #37853 is the bug and this is the API cleanup.

**Comment by dcharkes** [comment]
This is a trade-off between verbosity and static checking. Removing the type argument to `asFunction` and `lookupFunction` makes it less verbose. However, it also makes it so that type errors are only caught when assigning the returned closure to a variable with some function signature.

/cc @mkustermann what do you think?

**Comment by sjindel-google** [comment]
We agreed offline to leave it as is.
