### ISSUE TITLE
Type safety is not preserved for closure calls

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#37476]
VM treats closure calls with known function type as unchecked and bypasses parameter type checks, including bounds checks. The following example illustrates that it is not correct and may violate soundness of types:

```dart
class A<T extends num> {
  void Function<S extends T>(S x) foo() {
    print('foo: T = $T');
    return <S extends T>(S a) {
      T b = a;
      print('closure: S = $S');
      print('closure: T = $T');
      print('closure: a = $a');
      print('closure: b = $b');
      print('closure: a is S = ${a is S}');
      print('closure: b is T = ${b is T}');
      bar(b);
    };
  }

  void bar(T x) {
    print('bar: x = $x');
    print('bar: x + 1 = ${x + 1}');
  }
}

A<num> a = new A<int>();

main() {
  a.foo().call(3.14);
}
```

```
dart foo.dart

foo: T = int
closure: S = double
closure: T = int
closure: a = 3.14
closure: b = 3.14
closure: a is S = true
closure: b is T = false
Unhandled exception:
type 'double' is not a subtype of type 'int' of 'x'
#0      A.bar (file:///.../foo.dart)
#1      A.foo.<anonymous closure> (file:///.../foo.dart:13:7)
#2      main (file:///.../foo.dart:26:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Note that TypeError is not thrown when entering closure and double (`a`) is assigned to int (`b`). Only when `bar` is called its type check catches violation of type safety.

With precompiler the result is different but still incorrect:

```
pkg/vm/tool/precompiler2 foo.dart foo.snapshot
pkg/vm/tool/dart_precompiled_runtime2 foo.snapshot

foo: T = int
closure: S = double
closure: T = int
closure: a = 3.14
closure: b = 3.14
closure: a is S = true
closure: b is T = false
bar: x = 3.14
bar: x + 1 = 4614253070214989088

```

/cc @mraleph @mkustermann

**Comment by mraleph** [comment]
I think this a front-end bug, rather than a VM bug. If you have `void Function(T)` instead of `void Function<S extends T>(S)` then front-end inserts implicit check on the result of `a.foo()` for soundness. 

I don't see why `void Function<S extends T>(S)` would not be treated the same - I think it should be and most likely it is an oversight on CFE part.

@leafpetersen could you confirm that my understanding is correct?

**Comment by mraleph** [comment]
I had discussions with @eernstg and @lrhn and they confirmed that my understanding is correct - given an invocation class `C<T>` and a method `U foo()` on that class, such that `T` occurs in `U` non-covariantly - if we have invocation `C<X> o; use(o.foo());` we are supposed to emit an implicit check `use(o.foo() as U/T=X)` where `U/T=X` is an instantiation of `U` with `T=X`. 

I am recategorising this as a front-end bug.

**Comment by mraleph** [comment]
@johnniwinther Johnni could you take a stub at fixing this?

**Comment by johnniwinther** [comment]
Will do.

**Comment by leafpetersen** [comment]
I agree with the diagnosis of the issue.
