### ISSUE TITLE
ddc minimal null safety support to unfork

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37478]

**Comment by mit-mit** [comment]
@vsmenon @franklinyow this doesn't appear to have any active issues; can it be closed?

**Comment by vsmenon** [comment]
@sigmundch @nshahan - can we close this now?

**Comment by sigmundch** [comment]
There is still one issue being worked on.

The list above is a bit confusing because long ago we used "ZenHub dependencies" (which are all closed), but then switched to use Epics. We still have #40266 under this epic, but not listed as a dependency.

**Comment by franklinyow** [comment]
closing as all sub-issues are completed
