### ISSUE TITLE
apt-get update on dart docker images recently started failing with expired GPG key

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/sdk#37475]
About ~40 mins ago, we started seeing that our builds that are based on `google/dart` images started failing on our second docker step, which is to run an `apt-get update`, with this error:

```
E: GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian unstable Release: Signed file isn't valid, got 'NODATA' (does the network require authentication?)
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

I tried a few tags (2.4, 2.3, 2.2) and all hit the same error.

---

You can reproduce this issue with the following Dockerfile:

```Dockerfile
FROM google/dart:2.4.0
RUN apt-get update
```

Running `docker build .` in a directory with that `Dockerfile` will output:

```
Sending build context to Docker daemon  296.7MB
Step 1/80 : FROM google/dart:2.4.0
 ---> b250f9411f14
Step 2/80 : RUN apt-get update
 ---> Running in 66e89e3deb22
Get:1 http://security.debian.org stretch/updates InRelease [94.3 kB]
Get:2 http://security.debian.org stretch/updates/main amd64 Packages [623 kB]
Ign:3 https://storage.googleapis.com/download.dartlang.org/linux/debian stable InRelease
Ign:4 https://storage.googleapis.com/download.dartlang.org/linux/debian unstable InRelease
Get:6 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release [941 B]
Get:7 https://storage.googleapis.com/download.dartlang.org/linux/debian unstable Release [951 B]
Get:9 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release.gpg [819 B]
Ign:5 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:13 https://storage.googleapis.com/download.dartlang.org/linux/debian stable/main amd64 Packages [1151 B]
Err:10 https://storage.googleapis.com/download.dartlang.org/linux/debian unstable Release.gpg
  Signed file isn't valid, got 'NODATA' (does the network require authentication?)
Get:14 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [33.3 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9475 kB]
Reading package lists...
E: GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian unstable Release: Signed file isn't valid, got 'NODATA' (does the network require authentication?)
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

---

This looks like it may be similar to or the same as https://github.com/dart-lang/site-www/issues/1457

**Comment by evanweible-wf** [comment]
@athomas @kevmoo

**Comment by evanweible-wf** [comment]
A lot of our dart repos are still on 2.3 and we're trying to upgrade them to 2.4 right now, but are unable to do so because of this (changing the base image invalidates the cached layers). Any confirmation on if this is something that can be either worked around by us or fixed by someone on the dart team re-signing the file in question would be greatly appreciated.

**Comment by athomas** [comment]
Thanks for the report!

The release script copied an empty Release.gpg file to the cloud storage bucket (because it only checks for the presence of the file, not for it having content) from the signing server. It also didn't check the result of the docker build which failed for the same reason.

I re-triggered the sync and the Release.gpg is now correct. I also triggered docker build for 2.5.0-dev.1.0 again and that works now, so this should be resolved.

**Comment by evanweible-wf** [comment]
Thanks @athomas!

**Comment by patkujawa-wf** [comment]
This is happening again, started maybe an hour or so ago. Same issue?
