### ISSUE TITLE
dart2aot: Error When Executing

### ISSUE THREAD

**Issue by michaelknowles** [dart-lang/sdk#37482]
`Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"`

Attempting to run dart2aot results in an error.  Seems like it cannot handle spaces in the path.
```
C:\Users\Michael\Projects\adventofcode\bin>dart2aot
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Michael\Projects\adventofcode\bin>dart2aot -h
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Michael\Projects\adventofcode\bin>dart2aot main.dart main.dart.aot
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by cskau-g** [comment]
Thank you for reporting this.
The tool is in the process of being refactored, so I'll add it to the list of things we need to check there.

For good measure, can you confirm whether your `C:\Users\Michael\Projects\adventofcode\bin` folder or the binaries in it are symlinks ("shortcuts")?

**Comment by michaelknowles** [comment]
There are no symlinks in that path or where Dart is installed.

Michael Knowles

________________________________

**Comment by cskau-g** [comment]
Thank you for clarifying. I think I see it now. I misread the pasted bit but I see your `dart2aot` binary isn't actually under `...\adventofcode\bin` but rather somewhere under `C:\Program ...`, which makes sense.

**Comment by xgqfrms** [comment]
@michaelknowles what's your solution of the question?

**Comment by michaelknowles** [comment]
According to @cskau-g there is a refactoring in progress already where this will be fixed.  A temporary workaround is to not use paths that contain spaces in them.

**Comment by cskau-g** [comment]
I believe this is dup. of https://github.com/dart-lang/sdk/issues/37130 which has been resolved. Closing.
