### ISSUE TITLE
type_tostring_test and nested_generic_closure_test failing after ac41a200

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37486]
See https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-dartkb-linux-product-x64/982 for example.

The failures have been seen on `vm-dartkb-linux-product-simarm64` and `vm-dartkb-linux-product-x64` so far.

**Comment by sjindel-google** [comment]
It's also appeared on the obfuscation bot, although with a different error.

**Comment by alexmarkov** [comment]
Dartkb failures indicate the real bugs, revealed by newly added tests. I'll take a look at them.

Regarding obfuscation bot: we can either skip corelib_2/type_tostring_test on the obfuscation bot, or add `@pragma("vm:entry-point")` annotations to prevent obfuscation of names used in the test.

**Comment by crelier** [comment]
I also approved these failures showing on vm-dartkb-linux-debug-x64 and vm-dartkb-linux-debug-simarm64.
