### ISSUE TITLE
DEPENDENCY HELL

### ISSUE THREAD

**Issue by hpoit** [dart-lang/sdk#37481]
Hi. Will there be a version resolver soon? I constantly get version solving failure from trying to run different projects available on Github, such as https://github.com/budo385/todo_bloc_app/tree/master/todoapp_dart_angular

**Comment by hpoit** [comment]
https://docs.julialang.org/en/v1.0/stdlib/Pkg/ is a stellar example of a package manager

**Comment by hpoit** [comment]
Example number 2 where I have to guess what do to about version solving failure: https://github.com/montyr75/dart_chat_ng_fb_start

This is very frustrating.

**Comment by hpoit** [comment]
Package management should completely be behind the scenes.

**Comment by hpoit** [comment]
"Since environments are managed and updated independently from each other, “dependency hell” is significantly alleviated in Pkg." Source: https://docs.julialang.org/en/v1.0/stdlib/Pkg/

I am in DartLang's **dependency hell**.

**Comment by hpoit** [comment]
PLEASE WATCH https://www.youtube.com/watch?v=-yUiLCGegJs

**Comment by hpoit** [comment]
If Julia wrote Pkg3 on scientific funding, I am absolutely sure Google can too.

**Comment by hpoit** [comment]
Which SDK version range do I need????

![image](https://user-images.githubusercontent.com/3711100/60974831-2b675d80-a301-11e9-8dc9-a11b2975aa76.png)

**Comment by hpoit** [comment]
Maybe a negative version? Are there negative versions? Like -5.0.0, the dark side?

**Comment by hpoit** [comment]
I am sorry for the attitude, it's just so frustrating to start the morning like this.

**Comment by mraleph** [comment]
@hpoit the error message seems to state that it is `dart_to_js_script_rewriter` package and not your package requires SDK <2.0.0. So no amount of editing sdk constraint on your package is going to solve the problem - instead you need to make sure that `dart_to_js_script_rewriter` is updated.

**Comment by hpoit** [comment]
You mean if `dart_to_js_script_rewriter` 1.0.3 is the latest version? Apparently it is: https://github.com/Workiva/dart_to_js_script_rewriter

**Comment by mraleph** [comment]
Yes if you look at its pubspec you will see that it declares that it does not work on Dart 2 SDK.

Now that I actually also looked at what it does I realize that this package can't be ported to Dart 2 SDK because it is a pub transformer and this infrastructure was deprecated and removed in Dart 2.

**Comment by hpoit** [comment]
Thanks! I'll see what to do about it!

**Comment by natebosch** [comment]
You don't need `dart_to_js_script_rewriter` in Dart 2. You should be putting in a script tag for the JS from the start - never a script tag for Dart. dartium does not exist in Dart 2.
