### ISSUE TITLE
New hint for possibly ill-formatted Dart Language Version Override

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#37504]
@jakemac53 pointed out that users could easily typo when writing a Dart Language Version override comment in their libraries and part files. From [the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md#individual-library-language-version-override):

> The syntax for defaulting to a lower language level is line consisting only of a single-line comment of the form `// @dart = 2.0` (exactly two slashes, the string `@dart`, a `=`, and a numeral which is two decimal numbers separated by `.`) in the initial part of the file, prior to any language declarations. It can be preceded by a `#!` line or by other comments, but not by a `library` declaration or any other declaration. Whitespace (space and tabs) are allowed everywhere except between the slashes, inside the `@dart` string and inside the version numeral. The comment must be an actual single-line comment, and not a string of that form embedded in a block comment. Block comments traditionally start lines with a `*` character, but that is purely convention, so it would be possible to have a line containing just `//@dart=2.3` inside a block comment. That will not count as a language version override marker.

The analyzer should warn when a comment _almost_ looks like a DLV override, but is not being successfully parsed as one. Something that catches:

* `/// @dart = 2.0` (three slashes)
* `// @Dart = 2.0` (incorrect case)
* `// @dart = 2.0.0` (too many numbers and periods)
* `// @dart < 3.0` (incorrect `=`)
* `// @dart = 3` (too few numbers and periods)
* `// @dart = v2.0` (extra non-whitespace between `@dart`, `=`, or `2.0`)
* `// @dart 2.0` (missing equals)

I prefer this be a Hint, not a Lint, to make it very very visible, that users need not opt-in to.

**Comment by lrhn** [comment]
Consider also reporting something looking like a language version marker inside a block comment, unless that is too much trouble.
If you only look at EOL-comments, then it might not be worth the extra effort to look into the rest.
