### ISSUE TITLE
consider converting assists to fixes where there is a corresponding lint

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#37508]
Follow-up from conversation w/ @kevmoo, @devoncarew , @bwilkerson and @jwren.

As things currently stand there are a number of lints that have corresponding quick assists.  The rub is that these assists do not show up in the problems view yet fixes do (and to the user they are indistinguishable).

One remedy would be to convert all assists with corresponding lints to fixes.  The down-side of this is that not all users will enable the producing lint, meaning the assist will become only available to some users.  

Another alternative would be to add explicit fixes duplicating the assists in these cases.  (Without some care this could lead to doubled completion results.)

Another option might be to take advantage of the error code correspondences encoded in assists somehow.

https://github.com/dart-lang/sdk/blob/7cadd70696f85699fbe0fdb07b01ea9c4c8b4a5e/pkg/analysis_server/lib/src/services/correction/assist.dart#L34-L39

Possibly these could be scanned and returned in the DAS getFixes call?

**Comment by bwilkerson** [comment]
> One remedy would be to convert all assists with corresponding lints to fixes.

The one thing that needs to be added to avoid the downside is to only convert assists when the lint _is_ enabled. That shouldn't be too hard.

It might be more efficient, though, to directly create it as a fix when the lint is enabled and only check for an assist if the corresponding lint is not enabled. We check for assists far more often, so reducing the number of assists we check for would be a good thing.

**Comment by pq** [comment]
Done! 👍
