### ISSUE TITLE
dart:ffi how to describe in dart GoString and GoSlice structures generated by go

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#37509]
[Here (gist)](https://gist.github.com/ykmnkmi/bafb91c9231cc591f610748ef347ff13) dart and go code with generated header file.
i tried with Utf8 class from sqlite example, it's _seems_ work.
calling add 1, 2: 3
calling cosine 2pi: 1.0
callin log��U��o��U�����U@�o��UP�o��U��o��UP`�o��Uf��o��U��o��U��o��U��o��U��o��U��o��U�o��U�o��U �o��U0�o��U@�o��UP�o��U`�o��Up�o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U�o��U�o��U �o��U0�o��U@�o��UP�o��U`�o��Up�o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U�o��U�o��U �o��U0�o��U@�o��UP�o��U`�o��Up�o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U�o��U�o��U �o��U0�o��U@�o��UP�o��U`�o��Up�o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U��o��U
1

**Comment by sjindel-google** [comment]
Here's a working Gist which uses your "Log" function:

https://gist.github.com/sjindel-google/b88c964eb260e09280e588c41c6af3e5

Note that because `GoString` is represented as a struct in C, you have to pass it to the Go function by pointer (`*string` in Go) because we don't supporting passing structs directly to native functions.

**Comment by crossle** [comment]
@sjindel-google   how to return a GoString when dart call golang return string, like go code
 ```
func hello() (string, error) {
	return "", nil
}
```

**Comment by dcharkes** [comment]
We need support for passing structs by values in the calling convention for that. See https://github.com/dart-lang/sdk/issues/36730.

**Comment by sjindel-google** [comment]
In the meantime you can use a string* in Go (GoString* in C).

**Comment by crossle** [comment]
Thanks @dcharkes @sjindel-google, hope support soon.
How about the return multiple values like go return error and another value?
