### ISSUE TITLE
tests/language/override_field_test.dart incorrectly asserts that fields cannot be overridden

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#3751]
I believe this test is incorrect:

class A {
&nbsp;&nbsp;int instanceFieldInA;
}

class B extends A {
&nbsp;&nbsp;int instanceFieldInA;
}

main() {
&nbsp;&nbsp;var x  = new B();
}

Gilad, could you please advice and assign to me when you have an answer?

**Comment by srawlins** [comment]
This was fixed in 99c505e9b3c33274abd910c99e9a392f69b17f22.
