### ISSUE TITLE
[Analyzer] sort self packages to bottom

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/sdk#37519]
Hi there, it appears that the language server has removed support for local imports, so I suggest grouping them below other imports automatically.

eg

```dart
import 'dart:math';

import 'package:flutter/material.dart';

import 'package:myapp/models/score.dart';
import 'package:myapp/theme/colors.dart';
import 'package:myapp/theme/fonts.dart';
import 'package:myapp/theme/localization.dart';
```

xpost https://github.com/Dart-Code/Dart-Code/issues/1854

**Comment by lrhn** [comment]
What is "support for local imports", and when was it removed?

(Also, for the record: the space after `package:` is not allowed in package URIs.)

**Comment by lukepighetti** [comment]
I noticed a few days ago that analyzer wasn't importing local paths unless they were one directory below. Another developer I was talking to also noticed this. So if this was unintentional, there may be a regression?

**Comment by srawlins** [comment]
Local imports should still be supported.

We are now supporting the sorting rules laid out in [Effective Dart](https://dart.dev/guides/language/effective-dart/style#ordering) and enforced by the [directives_ordering](https://dart-lang.github.io/linter/lints/directives_ordering.html) lint rule.
