### ISSUE TITLE
Dart Flutter Web build Error Compiler Bug

### ISSUE THREAD

**Issue by samuelsarix** [dart-lang/sdk#37515]
This is the Output, I didnt change anything at all, and it worked before this build with the exact same code. Using webdev serve

dartdevc -k arguments: --dart-sdk-summary=C:\src\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/frx_web/page_state.ddc.js --source-map --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/services.ddc.dill=packages/flutter_web/services --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\SamuelSchwienbacherS\AppData\Local\Temp\scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --packages=file:///C:/Users/SAMUEL~1/AppData/Local/Temp/kernel_builder_7a12dc27-a4ad-11e9-9816-a434d99df8d6/.packages --module-name=packages/frx_web/page_state --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:frx_web/pages/product_page.dart package:frx_web/page_state.dart package:frx_web/pages/login_page.dart package:frx_web/pages/order_page.dart package:frx_web/pages/main_page.dart
    dart --version: 2.3.2-dev.0.0.flutter-e3edfd36b2 (Wed May 22 16:01:07 2019 +0000) on "windows_x64"

FileSystemException(uri=file:///C:/Users/SamuelSchwienbacherS/AppData/Local/Temp/scratch_space7a12dc20-a4ad-11e9-9816-a434d99df8d6/packages/collection/collection.ddc.dill; message=Das System kann den angegebenen Pfad nicht finden.
)
#0      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:68:7)
<asynchronous suspension>
#1      MultiRootFileSystemEntity.readAsBytes (package:build_integration/file_system/multi_root.dart:78:61)
<asynchronous suspension>
#2      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:61)
<asynchronous suspension>
#3      _compile (package:dev_compiler/src/kernel/command.dart:237:27)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#6      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#12     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#18     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

[SEVERE]build_web_compilers:ddc on lib/main.ddc.module (cached): Bad state: Tried to use a deleted ScratchSpace!

[SEVERE]build_web_compilers:entrypoint on web/main.dart (cached): AssetNotFoundException: frx_web|web/main.ddc.js

[SEVERE]build_web_compilers:ddc on web/main.ddc.module (cached): Bad state: Tried to use a deleted ScratchSpace!

[SEVERE] Failed after 416ms

**Comment by vsmenon** [comment]
Issue moved to [dart-lang/build #2357](https://github.com/dart-lang/build/issues/2357) via [**ZenHub**](https://www.zenhub.com/)
