### ISSUE TITLE
corelib_2/bigint_from_test/3 started failing on Mac reload bots after constant update re-enabled

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#37529]
After 9bbd3192 landed, in addition to new failures for `lib_2/mirrors/dynamic_load_test` (see #37517) and `language_2/enum_duplicate_test/none` (see #35885), there were also failure on the Mac reload bots for `corelib_2/bigint_from_test/3`:

```
  /===================================================================\
  | corelib_2/bigint_from_test/3 broke (Pass -> Crash, expected Pass) |
  \===================================================================/
  --- Command "vm_compile_to_kernel []" (took 509ms):
  DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_corelib_2_bigint_from_test.dart_3/out.dill /b/s/w/ir/cache/builder/sdk/tests/corelib_2/bigint_from_test.dart --packages=/b/s/w/ir/cache/builder/sdk/.packages -Ddart.developer.causal_async_stacks=true
  exit code:
  0
  --- Command "vm" (took 20.000554s):
  DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --optimization-counter-threshold=5 --no-background-compilation --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_corelib_2_bigint_from_test.dart_3/out.dill
  exit code:
  -6
  stderr:
  ../../runtime/vm/raw_object.h: 213: error: expected: IsWellFormed()
  version=2.5.0-edge.e7fab5eacc4319ea449749ec5225ae1b2b520c6c (Fri Jul 12 12:57:14 2019 +0000) on "macos_dbc"
  thread=3075, isolate=main(0x7f99a7048400)
  Stack dump aborted because GetAndValidateThreadStackBounds failed.
  --- Re-run this test:
  python tools/test.py -n dartk-reload-mac-debug-simdbc64 corelib_2/bigint_from_test/3

```

Example logs:
* [`vm-kernel-reload-mac-debug-simdbc64`](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8908135924606670320/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)
* [`vm-kernel-reload-mac-release-simdbc64`](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8908137778577823776/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)

Approving these (and the others mentioned) for now to turn the bots green instead of reverting, since it's only three tests and only on the reload bots, and then investigating.

**Comment by sstrickl** [comment]
I consistently see the same crash for `language_2/enum_duplicate_test/none` even for commits a couple months back (tried a handful of prior points back to c5e03e5c). Further digging revealed issue #35885, so that part of this issue is a duplicate.

Interestingly enough, I get a RTE for `lib_2/mirrors/dynamic_load_test` post-constant update when testing on my own workstation (unsure if it's the expected one) but if I go one commit back, I get a crash. (That is, I see Crash -> RTE, not RTE -> Crash.) Just found #37517, which I missed, so that part's a duplicate of that issue.

**Comment by a-siva** [comment]
simdbc and simdbc64 architectures are being deprecated for Flutter in the Catalina release, so removing the D25 milestone.

**Comment by sjindel-google** [comment]
DBC is obsolete.
