### ISSUE TITLE
State management without boilerplate by introducing new language features

### ISSUE THREAD

**Issue by jascodes** [dart-lang/sdk#37525]
Setting state should be easy and without boiler plate. Check out awesome Svelte 3 feature so fundamental should be built in at compiler level.

Check out https://svelte.dev/examples#reactive-assignments

Svelte 3 is awesome at using simple variables as state which can be used in UI. They do it by using reactive assignments. In order to be complaint with javascript they use `$:` label to mark assignment as reactive(i.e setstate). In dart we can use `<= ` or something else you fancy.

Thx

**Comment by vsmenon** [comment]
Issue moved to [dart-lang/language #450](https://github.com/dart-lang/language/issues/450) via [**ZenHub**](https://www.zenhub.com/)

**Comment by miyoyo** [comment]
Copy/Pasting the message to be sure the author sees it:
This isn't really relevant to Dart at all, as svelte is just a compiler.
This is achievable with a code analyzer and builder already, dart has no issues with labels (beyond linting that they're unused) or even labels declared multiple times.

**Comment by jascodes** [comment]
@vsmenon thanks for moving to right place, you can close this thread.
