### ISSUE TITLE
flutter hhh builder should be enabled as a tryjob

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#37542]
The Flutter HHH bot seems to be our best indicator on whether a CL will break Flutter rolls.  It's caught const-update issues the last two times we enabled, but only after a flip.  Can we add it to the presubmit?

@athomas @a-siva

**Comment by a-siva** [comment]
I believe there are some resource constrains which might make this a challenge to run it as a CQ dry run, maybe it can be made an optional job that folks can run if needed.

**Comment by athomas** [comment]
I'm open to explore making this an optional tryjob for high impact CLs like
flag flips, but it's easy to exhaust our capacity with this. So I'm not
sure I want it to show up in "Choose tryjobs".

The build recipe would need to be tested first, and might need changes. I
did migrate it to Luci with the possibility of enabling it as a tryjob so
it might just work.

We also need to setup a special bucket so we can have custom permissions as
well as not have this show up in Choose tryjobs (a handful lines of
starlark code) in case people start to accidentally DoS the CI system with
this job.

**Comment by athomas** [comment]
Test to see if the flutter-engine-linux would work as a tryjob as is: https://ci.chromium.org/swarming/task/4685a3530953d710?server=chromium-swarm.appspot.com

**Comment by athomas** [comment]
With https://chromium-review.googlesource.com/c/chromium/tools/build/+/1741820 patched in, I got a run that passes:
https://luci-milo.appspot.com/swarming/task/468968b982fffe10

I won't make this part of the default CQ, though. The builder is way to heavy-weight.
