### ISSUE TITLE
build_web_compilers:ddc on package:flutter_web/src/physics/clamped_simulation.ddc.module (cached): Error compiling dartdevc module:flutter_web|lib/src/physics/clamped_simulation.ddc.js  We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by GayathrideviGA** [dart-lang/sdk#37549]
dartdevc -k arguments: --dart-sdk-summary=C:\src\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\Admin\AppData\Local\Temp\scratch_space9676f356-a856-11e9-89d2-0e15e81adcaa\packages/flutter_web/src/physics/clamped_simulation.ddc.js --source-map --packages=file:///C:/Users/Admin/AppData/Local/Temp/kernel_builder_9c72f6a1-a856-11e9-89d2-0e15e81adcaa/.packages --module-name=packages/flutter_web/src/physics/clamped_simulation --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:flutter_web/src/physics/simulation.dart package:flutter_web/src/physics/friction_simulation.dart package:flutter_web/src/physics/spring_simulation.dart package:flutter_web/src/physics/clamped_simulation.dart package:flutter_web/src/physics/gravity_simulation.dart package:flutter_web/src/physics/utils.dart package:flutter_web/src/physics/tolerance.dart
    dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

[SEVERE] Failed after 15.4s

**Comment by GayathrideviGA** [comment]
dartdevc -k arguments: --dart-sdk-summary=C:\src\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\Admin\AppData\Local\Temp\scratch_space9676f356-a856-11e9-89d2-0e15e81adcaa\packages/flutter_web/src/physics/clamped_simulation.ddc.js --source-map --packages=file:///C:/Users/Admin/AppData/Local/Temp/kernel_builder_9c72f6a1-a856-11e9-89d2-0e15e81adcaa/.packages --module-name=packages/flutter_web/src/physics/clamped_simulation --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:flutter_web/src/physics/simulation.dart package:flutter_web/src/physics/friction_simulation.dart package:flutter_web/src/physics/spring_simulation.dart package:flutter_web/src/physics/clamped_simulation.dart package:flutter_web/src/physics/gravity_simulation.dart package:flutter_web/src/physics/utils.dart package:flutter_web/src/physics/tolerance.dart
    dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE] Failed after 15.4s

**Comment by vsmenon** [comment]
@jakemac53 - slightly different one.  Failing on this line:

https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/api_unstable/ddc.dart#L153
 
Do you think this is potentially the same issue as #37540?

**Comment by jakemac53** [comment]
No - this is a known issue with the current dev SDK on windows - the paths aren't matching up (and the error message is a bit broken as well).

It should be fixed at head and the next dev release should resolve it.

**Comment by vsmenon** [comment]
Thanks!  Is there a dup bug I can point this one to?

**Comment by jakemac53** [comment]
I don't see one linked to the fix https://dart-review.googlesource.com/c/sdk/+/108503

**Comment by vsmenon** [comment]
Thanks, marking as fixed.
