### ISSUE TITLE
dartdoc for parseIPv6Address ends up with an emoji

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#37547]
As seen on https://api.flutter.dev/flutter/dart-core/Uri/parseIPv6Address.html

```
::1
FEDC:BA98:7654:3210:FEDC:BA98:7654:3210
3ffe:2a00💯7031::1
::FFFF:129.144.52.38
2010:836B:4179::836B:4179
```

I think it'd be sane to just add backtics around the addresses to code-format them.

**Comment by dnfield** [comment]
Opened  https://dart-review.googlesource.com/c/sdk/+/109317

**Comment by lrhn** [comment]
Good catch. I'll accept the CL for now, and take it up with the DartDoc people.
I was not aware that DartDoc supported Github emoji syntax like `:100:` (:100:), and I'm not sure it should.

**Comment by dnfield** [comment]
I'm afraid it might be part of the Markdown parsing stuff.  @jcollins-g or @kwalrath might know more.

**Comment by lrhn** [comment]
It is part of the Dart Markdown package, but it is an optional extension that we don't *have* to have enabled.
