### ISSUE TITLE
Front end does not recognize `const Symbol(">>>")`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#37550]
When running the front end with the flags `--enable-experiment=constant-update-2018,triple-shift`, the code `const Symbol(">>>")` is rejected with the error message:
```
symb.dart:3:20: Error: The symbol name must be a valid public Dart member name, public constructor name, or library name, optionally qualified, but was '">>>"'.
print(const Symbol(">>>"));
```
With those two flags enabled, the symbol should be allowed.

With only the `triple-shift` experiment, without the `constant-update-2018` flag, both the VM and dart2js backends accept `const Symbol(">>>")`. That's just because they fail to check the input entirely, they accept `const Symbol(">>>>")` too.

See also #34919. If we remove the restriction on the const  `Symbol` constructor parameters entirely, then it's just up to the backends to *recognize* inputs that should create symbols equal to source names. All other symbols would only be equal to other symbols with the same string.

**Comment by a-siva** [comment]
The following tests fail due to this when const_update_2018 flag is turned on by default in the front end
`language_2/unsigned_right_shift_test/none broke (Pass -> CompileTimeError, expected Pass)`
