### ISSUE TITLE
getCpuSamples response does not include resolvedUrls in profile mode

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#37553]
When the app is run in debug mode, the response from `getCpuProfileTimeline` includes stack frames with resolved urls. In profile mode, all the resolved urls are the empty string.

This is the case for both iOS and Android.

**Comment by bkonyi** [comment]
@a-siva, @rmacnak-google do either of you see any way around this for profile builds?

**Comment by bkonyi** [comment]
So I'm fairly certain the CFE is doing the stripping... @mraleph you wouldn't happen to know why the resolved uris are stripped in profile mode, would you?

**Comment by mraleph** [comment]
CFE does not really know anything about AOT vs JIT build modes. 

AFAIK VM strips it during Precompilation to reduce snapshot size. See `Precompiler::DropLibraryEntries` it contains the following line:

```
        script.set_resolved_url(String::null_string());
```

I would suspect that if you remove this line then resolved url would be preserved in the snapshot.

**Comment by bkonyi** [comment]
@kenzieschmoll is there any reason that a resolved URL needs to be displayed rather than the import URI? The links in DevTools' timeline don't appear to be clickable, so I'm not sure what value is gained by using resolved URLs.

The reason I ask is because adding the `resolved_url` field to the snapshotted script object will introduce non-determinism to the build across different machines, and @rmacnak-google has made a point of avoiding the introduction of non-deterministic builds.

**Comment by kenzieschmoll** [comment]
@jacob314 will we be able to jump to source with the import URI or do we need the resolved_urls to do this?

**Comment by bkonyi** [comment]
> @jacob314 will we be able to jump to source with the import URI or do we need the resolved_urls to do this?

Is it possible to jump to source in DevTools currently? I haven't seen a way to unless I'm missing something.

**Comment by kenzieschmoll** [comment]
It isn't possible yet but we want to be able to from the inspector and the CPU profiler.

**Comment by jacob314** [comment]
Can you provide an example of what the "import URIs" look like. Without seeing what the VM would return to us I have no idea if they would be sufficient or not.
In general it should be fine for profile builds to be a bit larger than release builds so my preference would be just to change the default we are using in profile builds.

**Comment by kenzieschmoll** [comment]
Here is an example of a stackFrame's json in the response:
```
{
  "category": "Dart", 
  "name": "updateChild", 
  "resolvedUrl": "file:///Users/kenzieschmoll/develop/flutter/packages/flutter/lib/src/widgets/framework.dart",
  "parent": "isolates/1925773073691959-2775"
}
```

**Comment by kenzieschmoll** [comment]
Pinging this issue. We had a user file an [issue](https://github.com/flutter/devtools/issues/2391) against DevTools because the file URIs are missing in profile mode. This is a key component for a user to be able to map method names to source locations.

**Comment by bkonyi** [comment]
SDK change [up for review](https://dart-review.googlesource.com/c/sdk/+/193520). We'll need to add `--include_script_urls` to the `gen_snapshot` invocation in `flutter_tools` for the profile mode build for this to be considered closed.

**Comment by bkonyi** [comment]
After going through review, it turns out putting this behind `--include_script_urls` isn't necessary. The resolved script URLs will now be included in all AOT configurations except `PRODUCT` mode (aka, Flutter's `release` mode) as of 2a62fc49a338feb7c49a4c03c84d85a9103f9904.
