### ISSUE TITLE
Add stream that notifies clients when a flag is changed

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#37557]
It would be nice to have a FlagChange stream that we could subscribe to that would send change events with the flag name and new value.

In DevTools, we need this to monitor changes to the `profile_period` flag. 

cc: @jacob314

**Comment by a-siva** [comment]
I presume changes to profile_period are made by the clients in that case why is it necessary to have FlagChange stream. Are you considering a scenario where multiple clients are connected to the same VM and changes made in one client should now be propagated to all the other clients?

**Comment by kenzieschmoll** [comment]
@a-siva exactly. If a user has two instances of DevTools open and connected to the same VM, we want to be able to maintain state between the two DevTools clients.
