### ISSUE TITLE
Invalid alignment assumptions in ffi.cc

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#37559]
With g++ (Debian 7.3.0-25) 7.3.0

```
g++ -MMD -MF obj/runtime/vm/compiler/libdart_vm_jit.ffi.o.d -D_FORTIFY_SOURCE=2 -DDEBUG -DTARGET_ARCH_IA32 -DDEBUG -DDART_USE_TCMALLOC -DTARGET_OS_LINUX -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -I../../runtime -I../.. -Igen -I../../runtime/include -I../../third_party/tcmalloc/gperftools/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -m32 -msse2 -mfpmath=sse -fno-exceptions -pthread -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -fdebug-prefix-map=/usr/local/google/home/rmacnak/dart3/sdk=../.. -no-canonical-prefixes --sysroot=/ -O2 -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O2 -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++11 -fno-rtti -fno-exceptions -c ../../runtime/vm/compiler/ffi.cc -o obj/runtime/vm/compiler/libdart_vm_jit.ffi.o
../../runtime/vm/compiler/ffi.cc:63:1: error: static assertion failed: FFI transformation alignment
 static_assert(alignof(double) == 4, "FFI transformation alignment");
 ^~~~~~~~~~~~~
../../runtime/vm/compiler/ffi.cc:64:1: error: static assertion failed: FFI transformation alignment
 static_assert(alignof(uint64_t) == 4, "FFI transformation alignment");
 ^~~~~~~~~~~~~
cc1plus: error: unrecognized command line option ‘-Wno-unused-private-field’ [-Werror]
cc1plus: all warnings being treated as errors
```
@sjindel-google @dcharkes

**Comment by rmacnak-google** [comment]
To run the build with the host g++ instead the downloaded version of clang,

```
./tools/gn.py --mode all --arch all --no-clang --no-goma --target-sysroot x64=/,ia32=/,simarm=/,simarm64=/,simdbc64=/
./tools/build.py --mode all --arch all runtime
```

**Comment by sjindel-google** [comment]
This is problematic even when we compile the VM with clang, because we might have to load (and thus  interoperate with) code which was compiled with GCC.

**Comment by dcharkes** [comment]
@mkustermann [mentioned on the CL](https://dart-review.googlesource.com/c/sdk/+/108103/12/pkg/vm/lib/transformations/ffi.dart#125) that older versions of GCC return the preferred alignment instead of the required alignment.

I'll find a better way to test alignment assumptions on older GCCs.

**Comment by dcharkes** [comment]
> The behavior of the "alignof" operator was changed in GCC 8 and Clang 8. Note that this didn't change the actual alignment of "double", only the reported alignment from that operator.
> 
> Some links:
> https://gcc.gnu.org/gcc-8/changes.html
> https://releases.llvm.org/8.0.0/tools/clang/docs/ReleaseNotes.html
> https://llvm.org/PR26547

I did not find a different alignment function/macro that returns the ABI rather than the preferred alignment on all old compilers. (`_Alignof` returns ABI alignment on GCC7 but preferred alignment on Clang 7. and `__alignof__ ` always returns preferred alignment.)

We could add a dummy struct to detect the ABI alignment.

```c++
struct Dummy {
  int8_t a;
  double b;
}

offsetof(Dummy, b);
```

Alternatively, we could skip the check on clang <= 7 and gcc <= 7 ([detect compiler version](http://nadeausoftware.com/articles/2012/10/c_c_tip_how_detect_compiler_name_and_version_using_compiler_predefined_macros)) and keep the check on all other compilers. 

(I'd prefer the first solution.)

**Comment by sjindel-google** [comment]
Either solution is fine with me.
