### ISSUE TITLE
`visitComment` from `RecursiveAstVisitor` class does not visit non-documentation comments

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/sdk#37566]
Dart 2.4.0 and analyzer 0.37.0

[The documentation](https://pub.dev/documentation/analyzer/latest/dart_ast_ast/Comment-class.html) leads me to believe that all kinds of comments are visited by the Dart AST visitor, including documentation comments, non-documentation comments, and end-of-line comments.

I have a class that extends `RecursiveAstVisitor` and overrides `visitComment` like so: 

```dart
class TestVisitor extends RecursiveAstVisitor {
   @override
   void visitComment(Comment node) {
       print('only the documentation comment will be visited $node');
   }
}
```

When I visit code that looks like this, only the documentation comment is visited:

```dart
class Test {
   /// Documentation comment visited by `visitComment`
   void testFunc() {
      // Non-documentation comment NOT visited by `visitComment`
      print('hello'); // end-of-line comment NOT visited by `visitComment`
    }
}
```

Is this intentional? Someone on my team mentioned that there were optimizations made to the AST in Dart 2 for more performant analysis, is this a result of that? Are those changes documented anywhere?

If intentional, it'd be great if the documentation was updated to reflect this. Also if intentional, is there an alternative way to visit non-documentation comments (or anything else that was removed)?

Thanks!

**Comment by bwilkerson** [comment]
Sorry for the confusion! We've never created `Comment` nodes for anything other than documentation comments, despite what the documentation would lead you to believe.

> Is this intentional?

Yes. The AST structure is already very large, and adding nodes for all the comments would only make that worse.

> Someone on my team mentioned that there were optimizations made to the AST in Dart 2 for more performant analysis, is this a result of that?

Nope. It's been this way since day 1, long before we published the analyzer as a package.

> Are those changes documented anywhere?

The only change I can think of that they might be thinking about is the deprecation of `computeNode`. There isn't any documentation that really explains what to do if you were using that method because the right change really depends on too many factors to make it reasonable to document (though arguably we ought to add documentation for some of the more common cases).

> ... is there an alternative way to visit non-documentation comments ...

Yes. All of the comments are preserved in the token stream. You can ask any AST node (including a compilation unit) for the `beginToken` and `endToken`. All of the tokens are stored in a linked list, so you can ask any token for the `next` token in the list. For performance, the comment tokens are not kept directly in the linked list, but you can ask any token for the `precedingComments` to get tokens for all of the comments between the previous token and the current token.

For example, assume the following snippet: `a /*1*/ /*2*/ b`. If you have the token for `a` and ask for the `next` token you'll get the token for `b`. If you have the token for `b` you can ask for the `precedingComments` and you'll get a token for `/*1*/`. Asking the token for `/*1*/` for the `next` token will get you the token for `/*2*/`. Asking the token for `/*2*/` for the `next` token will get you `null`.

**Comment by passsy** [comment]
> > ... is there an alternative way to visit non-documentation comments ...
> 
> Yes. All of the comments are preserved in the token stream. You can ask any AST node (including a compilation unit) for the `beginToken` and `endToken`. All of the tokens are stored in a linked list, so you can ask any token for the `next` token in the list. For performance, the comment tokens are not kept directly in the linked list, but you can ask any token for the `precedingComments` to get tokens for all of the comments between the previous token and the current token.
> 
> For example, assume the following snippet: `a /*1*/ /*2*/ b`. If you have the token for `a` and ask for the `next` token you'll get the token for `b`. If you have the token for `b` you can ask for the `precedingComments` and you'll get a token for `/*1*/`. Asking the token for `/*1*/` for the `next` token will get you the token for `/*2*/`. Asking the token for `/*2*/` for the `next` token will get you `null`.

For those wondering, here is the quite complex workaround in code. Not sure if I'll ever publish it, therefore I leave it here.

```dart
// ignore_for_file: depend_on_referenced_packages

import 'dart:isolate';

import 'package:_fe_analyzer_shared/src/scanner/token.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:characters/characters.dart';
import 'package:custom_lint_builder/custom_lint_builder.dart';

// This is the entrypoint of our custom linter
void main(List<String> args, SendPort sendPort) {
  startPlugin(sendPort, _ExampleLinter());
}

extension on Token {
  Iterable<Token> selfAndAllNextTokens() sync* {
    Token? token = this;
    while (token != null) {
      yield token;
      token = token.next;
    }
  }
}

// This class is the one that will analyze Dart files and return lints
class _ExampleLinter extends PluginBase {
  @override
  Stream<Lint> getLints(ResolvedUnitResult resolvedUnitResult) async* {
    final library = resolvedUnitResult.libraryElement;

    // Comments are not directly available as AstNodes
    // https://github.com/dart-lang/sdk/issues/37566

    final List<AstNode> allNodes = [];
    final visitor = AnyAstNodeVisitor(onVisitNode: (node) {
      allNodes.add(node);
    });
    resolvedUnitResult.unit.visitChildren(visitor);

    print('Found ${allNodes.length} nodes');

    final Set<Token> allTokensInFile = allNodes.expand((AstNode element) sync* {
      var begin = element.beginToken;
      var end = element.endToken;
      yield* begin.selfAndAllNextTokens().takeWhile((value) => value != end);
      yield end;
    }).toSet();

    print('All tokens in file: ${allTokensInFile.length}');

    final Set<Token> allTokensIncludingComments = allTokensInFile.expand((element) sync* {
      yield element;
      var comment = element.precedingComments;
      if (comment != null) {
        yield* comment.selfAndAllNextTokens();
      }
    }).toSet();

    print('All tokens including comments: ${allTokensIncludingComments.length}');

    final Set<CommentToken> comments = allTokensIncludingComments.whereType<CommentToken>().toSet();

    print('Found ${comments.length} comments in ${library.source.shortName}');

    for (final comment in comments) {
      final thirdChar = comment.lexeme.characters.skip(2).take(1);
      final fourthChar = comment.lexeme.characters.skip(3).take(1);
      if ((thirdChar.string == '/' && fourthChar.string == ' ') || thirdChar.string == ' ') {
        // Correct comment
      } else {
        yield Lint(
          code: 'comment_without_space',
          message: 'Comments should have a leading space',
          location: resolvedUnitResult.lintLocationFromOffset(comment.offset, length: 3),
        );
      }
    }
  }
}

class AnyAstNodeVisitor extends GeneralizingAstVisitor<void> {
  AnyAstNodeVisitor({
    required this.onVisitNode,
  });

  void Function(AstNode node) onVisitNode;

  @override
  void visitNode(AstNode node) {
    onVisitNode(node);
    super.visitNode(node);
  }

  @override
  void visitComment(Comment node) {
    onVisitNode(node);
    super.visitComment(node);
  }
}

```

**Comment by incendial** [comment]
Why not to visit it like this https://github.com/dart-code-checker/dart-code-metrics/blob/master/lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart#L22?

And then just https://github.com/dart-code-checker/dart-code-metrics/blob/master/lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule.dart#L39

Btw, consider checking out our https://dartcodemetrics.dev/docs/rules/common/format-comment, it covers your case and much more
