### ISSUE TITLE
Stream "timeout" happens even after execution has finished

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#37565]
The "timeout" method is being called even after the execution has already finished. Check this code:

```dart
main() async {
  var theFirstValue = await justAnIntegerStream().map((it) {
    print("Value received=$it");
    return it;
  }).timeout(Duration(milliseconds: 2000), onTimeout: (_) {
    print("TIMEOUT HAPPENED!");
  }).first;

  print("Execution ended with value=$theFirstValue.");
}

Stream<int> justAnIntegerStream() async* {
  for (int i = 0; i < 10; i++) {
    await Future.delayed(Duration(milliseconds: 1000));
    yield i;
  }
}
```

The console prints:

```
Value received=0
Execution ended with value=0.
TIMEOUT HAPPENED!

Process finished with exit code 0
```

That makes no sense since the stream has already been closed due to the `first` call on the stream.

My Dart version:
```
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
```

**Comment by devoncarew** [comment]
The stream continues to run - `first` just extracts the first element out of it as a future. I believe this is working as intended.

**Comment by shinayser** [comment]
The documentation for the "first" says that it cancels the subscription:

`Internally the method cancels its subscription after the first element. This means that single-subscription (non-broadcast) streams are closed and cannot be reused after a call to this getter.`

Since there is noone listening after the `first` executes, should'nt the stream streaming data?
