### ISSUE TITLE
Analysis  server has terminated 

### ISSUE THREAD

**Issue by OOMROO** [dart-lang/sdk#37562]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

**Comment by devoncarew** [comment]
Was there any associated stack trace or other information?

**Comment by OOMROO** [comment]
我用的Android Studio 开发的Flutter 项目 底部有 dart Analysis 标签栏 提示我 Analysis  server has terminated 。我删除项目 重新clone  打开 后 这个错误消失了，我不知道为什么。我关掉这个issuse。 非常感谢你的回复

**Comment by OOMROO** [comment]
The dart Analysis TAB at the bottom of the Flutter project developed by Android Studio that I used reminds me that Analysis server has terminated. I deleted the project and re-opened clone after this error disappeared, I do not know why. I'll close this issuse. Thank you very much for your reply
