### ISSUE TITLE
Option for gen_snapshot to generate assembly without a DWARF section

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#37560]
See https://github.com/flutter/flutter/issues/15288#issuecomment-504211391

This section confuses the Xcode toolchain when trying to build with bitcode.  I can strip it out as a step in the tool, but it seems like it would be better if I could just tell gen_snapshot to not include it to begin with.

**Comment by rmacnak-google** [comment]
6d608fb52bc1926a73d986d73ab228b77cfb7ca2

**Comment by mehmetf** [comment]
I don't think this is fixed. The comment in flutter tooling indicates the stripping was requested for assembly snapshots whereas the fix linked above is just for elf snapshots.

The workaround in tooling is still there: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L181-L196
