### ISSUE TITLE
DDC refuses to compile unsupported but unreachable code

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#37571]
## Main issue: DDC should accept unsupported but correct Dart code that's unreachable

I'm trying to make Flutter tests pass on the Web. However, some tests use numeric value ranges that are available in the VM and AOT, but not available on the Web. For example, [this test](https://github.com/flutter/flutter/blob/919dcf53f368c0aa5c559728d9d89d241617913c/packages/flutter/test/services/message_codecs_test.dart#L52) results in this error:

```
test/services/message_codecs_test.dart:52:43: Error: The integer literal
9223372036854775807 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript
9223372036854775808 is the nearest value that can be represented exactly.
        _checkEncodeDecode<dynamic>(json, 9223372036854775807);
```

To make this test pass, I'd like to guard the unsupported parts with a constant check, such as:

```dart
if (!kIsWeb) {
  _checkEncodeDecode<dynamic>(json, 9223372036854775807);
  _checkEncodeDecode<dynamic>(json, -9223372036854775807);
}
```

However, DDC still refuses to compile it. I also trid `if (false)` out of curiosity, but got the same error.

## Secondary issue: the suggested value is wrong

Note that the error message suggests that I use 9223372036854775808 instead. However, that value cannot be represented exactly. It will be truncated to 9223372036854776000.

* Dart SDK Version: this is in Flutter as of https://github.com/flutter/flutter/commit/5a34e7981

/cc @vsmenon

**Comment by vsmenon** [comment]
Do you see different in dart2js?

We don't do any reachability analysis in DDC.

**Comment by ferhatb** [comment]
Can we use warn/hint or a throw when in DDC mode ?

**Comment by vsmenon** [comment]
Hmm, so instead of a static error, provide a mode that throws at runtime if/when the line is executed?

**Comment by yjbanov** [comment]
dart2js does both, tell me it's dead code _and_ refuses to compile it :smile: 

```
ERROR: web/main.dart:8
  Dead code. #dead_code

Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
    print(9223372036854775807);
          ^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

If reachability analysis is not possible, can it be replaced with a runtime error in DDC and reachability analysis in dart2js?

@ferhatb I think warn/hint won't work in DDC without reachability analysis.

**Comment by jonahwilliams** [comment]
I looked into this a while back. The check for int size is implemented in fasta, which happens way before dead code elimination in dart2js

**Comment by vsmenon** [comment]
Yes, the error is enforced in the CFE when running in web mode (i.e., with a web backend).

We could change the CFE (either by default or under an option) to inject a runtime error instead of reporting a static error.  In the general case, I think users would prefer a static error to a runtime one though.

Not sure it's worth it though.  Could replace all occurrences of problematic values with `int.parse` of the string rep.

**Comment by vsmenon** [comment]
Closing, as I don't think this is worth another mode in the CFE.

**Comment by yjbanov** [comment]
`int.parse` does not provide a solution for constants. What should we recommend to Flutter users targeting mobile and web with a single codebase?

**Comment by vsmenon** [comment]
In terms of what works today, it'd have to be a config specific import & separating constants accordingly.
