### ISSUE TITLE
Dart2JS interop breaks if there are no classes annotated with @JS

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#37576]
Was trying to reproduce a different issue and was unable to use js iterop at all until I had _some_ class annotated with `@JS()` regardless of wether that class was used.

```
VM362 main.dart.js:1001 Uncaught TypeError: v.getIsolateTag is not a function
    at VM362 main.dart.js:1001
    at Object.a.<computed> (VM362 main.dart.js:27)
    at Object.bh (VM362 main.dart.js:617)
    at Object.bk (VM362 main.dart.js:626)
    at Object.aX (VM362 main.dart.js:628)
    at VM362 main.dart.js:1013
    at VM362 main.dart.js:1008
    at dartProgram (VM362 main.dart.js:1011)
    at VM362 main.dart.js:1013
```

So, for instance, if I only have top level methods annotated then `getIsolateTag` function is not written and the interop does not work.

**Comment by natebosch** [comment]
There are many other conditions which can also make it work - this is most likely to show up in very small samples. Here is one:

```dart
@JS()
library main;

import 'package:js/js.dart';

@JS('doStuff')
external set doStuff(Function anything);

void main() {
  print('Started');
  doStuff = allowInterop(dartStuff);
}

void dartStuff(String arg) {
  print('Dart has: $arg');
}
```

We don't emit the `getIsolateTag` in that case. We do emit it for

```dart
@JS()
library main;

import 'package:js/js.dart';

@JS('doStuff')
external set doStuff(Function anything);

@JS()
class Foo {}

void main() {
  print('Started');
  doStuff = allowInterop(dartStuff);
}

void dartStuff(String arg) {
  print('Dart has: $arg');
}
```

After syncing with @rakudrama this isn't trivial to solve.

The short story is that we track "impacts" of different pieces of code. A call to "allowInterop" should have the impact of emitting `getIsolateTag`, but it doesn't and noticing where that happens isn't easy. Things work when some other bit of code is known to have that impact.

This might get easier to solve if we have the constant update turned on.

**Comment by rakudrama** [comment]
Compiling the program with asserts enabled (dart2js_developer) shows there are some other problems:

```
org-dartlang-sdk:///sdk/lib/js/dart2js/js_dart2js.dart@21484+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

...

Unhandled exception:
'package:compiler/src/ssa/types.dart': Failed assertion: line 67 pos 12: 'abstractValueDomain.isEmpty(result).isPotentiallyFalse': Unexpected empty return value for NativeBehavior(returns: [JavaScriptFunction], creates: [JavaScriptFunction], sideEffects: SideEffects(reads anything; writes anything), throws: may).
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AbstractValueFactory.fromNativeBehavior (package:compiler/src/ssa/types.dart:67:12)
#3      KernelToTypeInferenceMapImpl.typeFromNativeBehavior (package:compiler/src/js_model/js_strategy.dart:616:33)
#4      KernelSsaGraphBuilder._handleForeignJs (package:compiler/src/ssa/builder_kernel.dart:4688:27)
#5      KernelSsaGraphBuilder._handleInvokeStaticForeign (package:compiler/src/ssa/builder_kernel.dart:4043:7)
#6      KernelSsaGraphBuilder.visitStaticInvocation (package:compiler/src/ssa/builder_kernel.dart:3766:7)
#7      StaticInvocation.accept (package:kernel/ast.dart:2976:36)
#8      KernelSsaGraphBuilder.visitVariableDeclaration (package:compiler/src/ssa/builder_kernel.dart:3526:24)
#9      VariableDeclaration.accept (package:kernel/ast.dart:4661:35)
#10     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder_kernel.dart:1715:17)
#11     Block.accept (package:kernel/ast.dart:3955:35)
#12     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1297:23)
#13     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:451:15)
#14     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:751:15)
#15     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:436:21)
#16     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:514:22)
```

The call  `JS('JavaScriptFunction', ...)` in js_dart2js.dart should have registered `JavaScriptFunction` as having been created.

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/114302/ tracks calls to `allowInterop` and produces impacts which emit `getIsolateTag`.

Even with this fix, the sample program still breaks the compiler, as Stephen mentioned above. The `NativeBehavior` from `allowInterop` does correctly mark `JavaScriptFunction` as being returned, but we don't mark `JavaScriptFunction` as being *instantiated*, so we produce an empty type mask for it.

@rakudrama, @johnniwinther: Should we mark `JavaScriptFunction` as abstractly instantiated in this case?

**Comment by fishythefish** [comment]
Digging deeper, although the `NativeBehavior` marks `JavaScriptFunction` as being instantiated, the `NativeResolutionEnqueuer` fails to process the `NativeBehavior` correctly because the `NativeClassFinder` does not mark `JavaScriptFunction` as a native class.

We should add all classes instantiated by a `NativeBehavior` to the set of native classes during resolution, or at least treat them like it.

Basic fix here: https://dart-review.googlesource.com/c/sdk/+/114466/
