### ISSUE TITLE
io.HttpClient doesn't support RFC6874

### ISSUE THREAD

**Issue by tamird** [dart-lang/sdk#37570]
Following up from https://github.com/dart-lang/sdk/issues/29456, it is now possible to parse IPv6 link-local addresses, but using them to make HTTP requests still does not work.

cc @raggi @ZichangG @zanderso @a-siva

**Comment by ZichangG** [comment]
I think it is probably because zoneID is part of host and not get handled properly. 
Do you have a more specific test case showing how HTTP requests fail? so I can run it locally and try to fix it.

**Comment by tamird** [comment]
Sure, the test case is roughly:

```
try {
  await http.get(Uri.http('[fe80::4607:bff:fee2:315f%25enx44070be2315e]', '/'));
} on SocketException catch (e) {
  print('SocketException: $e');
}
```
which prints
```
SocketException: SocketException: Failed host lookup: 'fe80::4607:bff:fee2:315f%25enx44070be2315e' (OS Error: Name or service not known, errno = -2)
```

**Comment by ZichangG** [comment]
@lrhn A quick question regarding escape character in URI. 
For this issue, host is "ipv6" + "%25" + "zoneID", which has been passed downstream. When native C api call getaddrinfo() looks up host, it accepted the format to be "ipv6" + "%" + "zoneID", which causes "25" be a part of scope id.
So "25" should be dropped at class URI or somewhere downstream? What do you think?

**Comment by ZichangG** [comment]
The other issue I found, 
When getaddrinfo() gets host with numeric scope id, it worked well. An example I run on my local machine, `[fe80::5ae0:189a:ff49:a15b%32]`
Once alphabet characters there, it failed to look up the address. `[fe80::5ae0:189a:ff49:a15b%32a]`

**Comment by tamird** [comment]
I think that's just because `32a` is not a scope that exists on your machine. `getaddrinfo` returns a `sockaddr_in6` which has an integeral `scope_id` field - if you provide a non numeric scope, it has to figure out the interface index of the scope. Can you try it with one of your machine's interface names?

**Comment by ZichangG** [comment]
Forget to mention,  `inet6 fe80::5ae0:189a:ff49:a15b  prefixlen 64  scopeid 0x20<link>` is one of interface on my machine. getaddrinfo() worked well. 

Why does your example contains non numeric scope id? Where does it come from?

**Comment by tamird** [comment]
That's the interface name on my machine.

**Comment by tamird** [comment]
After applying https://dart-review.googlesource.com/c/sdk/+/110184 and https://dart-review.googlesource.com/c/sdk/+/110121, I get:
```
SocketException: Connection failed (OS Error: Invalid argument, errno = 22), address = fe80::4607:bff:fee2:315f%enx44070be2315e, port = 80
```
Which is certainly more encouraging!

I then added some logging in the native `connect` call:
```diff
diff --git a/runtime/bin/socket_linux.cc b/runtime/bin/socket_linux.cc
index f2bb4aaee8..8c2f88a436 100644
--- a/runtime/bin/socket_linux.cc
+++ b/runtime/bin/socket_linux.cc
@@ -44,6 +44,11 @@ static intptr_t Connect(intptr_t fd, const RawAddr& addr) {
   if ((result == 0) || (errno == EINPROGRESS)) {
     return fd;
   }
+  if (addr.ss.ss_family == AF_INET6) {
+      char astring[INET6_ADDRSTRLEN];
+      inet_ntop(addr.ss.ss_family, &addr.in6.sin6_addr, astring, sizeof(astring));
+      Syslog::PrintErr("ERROR addr=%s scope_id=%d\n", astring, addr.in6.sin6_scope_id);
+  }
   FDUtils::FDUtils::SaveErrorAndClose(fd);
   return -1;
 }
```
and I now see the following:
```
ERROR addr=fe80::4607:bff:fee2:315f scope_id=0
SocketException: SocketException: Connection failed (OS Error: Invalid argument, errno = 22), address = fe80::4607:bff:fee2:315f%enx44070be2315e, port = 80
```
So the scope id is not being set correctly.

I wrote a simple C program to test my assumptions:
```c
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <errno.h>
#include <arpa/inet.h>
#include <string.h>
#include <stdio.h>

int main() {
  int ret;

  struct addrinfo hints, *result, *rp;
  memset(&hints, 0, sizeof(hints));
  ret = getaddrinfo("fe80::4607:bff:fee2:315f%enx44070be2315e", NULL, &hints, &result);
  if (ret != 0) {
    fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, strerror(errno));
    return ret;
  }
  int i = 0;
  for (rp = result; rp != NULL; rp = rp->ai_next) {
    fprintf(stdout, "%d: ai_flags=%d\n", i, rp->ai_flags);
    fprintf(stdout, "%d: ai_family=%d\n", i, rp->ai_family);
    fprintf(stdout, "%d: ai_socktype=%d\n", i, rp->ai_socktype);
    fprintf(stdout, "%d: ai_protocol=%d\n", i, rp->ai_protocol);

    struct sockaddr_in* in;
    struct sockaddr_in6* in6;
    const void* src;

    char addrstr[INET6_ADDRSTRLEN];
    switch (rp->ai_family) {
      case AF_INET:
        in = (struct sockaddr_in*)rp->ai_addr;
        src = &in->sin_addr;
        break;
      case AF_INET6:
        in6 = (struct sockaddr_in6*)rp->ai_addr;
        src = &in6->sin6_addr;
        fprintf(stdout, "%d: ai_addr->sin6_scope_id=%d\n", i, in6->sin6_scope_id);
        break;
    }
    const char* str = inet_ntop(rp->ai_family, src, addrstr, sizeof(addrstr));
    if (str == NULL) {
      fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, strerror(errno));
      return -1;
    }

    fprintf(stdout, "%d: ai_addr->sin{,6}_addr=%s\n", i, str);
    i++;
  }
  return 0;
}
```
This program prints:
```
0: ai_flags=0
0: ai_family=10
0: ai_socktype=1
0: ai_protocol=6
0: ai_addr->sin6_scope_id=15
0: ai_addr->sin{,6}_addr=fe80::4607:bff:fee2:315f
1: ai_flags=0
1: ai_family=10
1: ai_socktype=2
1: ai_protocol=17
1: ai_addr->sin6_scope_id=15
1: ai_addr->sin{,6}_addr=fe80::4607:bff:fee2:315f
2: ai_flags=0
2: ai_family=10
2: ai_socktype=3
2: ai_protocol=0
2: ai_addr->sin6_scope_id=15
2: ai_addr->sin{,6}_addr=fe80::4607:bff:fee2:315f
```
so the sin6_scope_id is being set correctly there.

So something in the dart VM is not constructing the InternetAddress correctly.

**Comment by ZichangG** [comment]
The same problem I get from gdb. The addr coming from getaddrinfo() has been malformed. The addr has different content when socket connect() is called.

I tried to use socket connect with addr coming from getaddrinfo(). Connection cannot be established. It says network is unreachable. I am not sure whether connect to a link local address is allowed or not.

**Comment by ZichangG** [comment]
The field `sin6_scope_id` has not been ignored and not being passed into dart side. Therefore, when it comes back, it also ignore `sin6_scope_id`.

```c++
CObjectUint8Array* SocketAddress::ToCObject(const RawAddr& addr) {
  int in_addr_len = SocketAddress::GetInAddrLength(addr);
  const void* in_addr;
  CObjectUint8Array* data =
      new CObjectUint8Array(CObject::NewUint8Array(in_addr_len));
  if (addr.addr.sa_family == AF_INET6) {
    in_addr = reinterpret_cast<const void*>(&addr.in6.sin6_addr);
  } else {
    in_addr = reinterpret_cast<const void*>(&addr.in.sin_addr);
  }
  memmove(data->Buffer(), in_addr, in_addr_len);
  return data;
}
```

**Comment by tamird** [comment]
Yeah, this is pretty bad. I don't understand why `ToCObject` tries to create a `Uint8Array`, rather than just dealing in `RawAddr`.

**Comment by tamird** [comment]
With these two changes:
- https://dart-review.googlesource.com/c/sdk/+/110121
- https://dart-review.googlesource.com/c/sdk/+/110364

my test case works! unfortunately, the latter change definitely breaks the `InternetAddress` class.

**Comment by lrhn** [comment]
The URI format *must* contain the `%25` according to rfc6874.

> For this issue, host is "ipv6" + "%25" + "zoneID", which has been passed downstream.

That is the problem. You (or someone) use the URI host substring as an IPv6 address. It is not. It is *encoding* an IPv6 address, so you need to decode the `Uri.host` getter result before passing it to something expecting an IPv6 address.

That was not previously necessary for IPv6 addresses because IPv6 addresses could not contain escapes. Now they can. That makes some existing code act incorrectly when it meets a new IPv6 address with a zone ID. That code needs to change, it is not compatible with zone ID URIs (Changing the URI class was a forward-breaking change, not because any existing program would break, but because existing library code might not be ready to encounter the new feature. This is part of the breaking change clean-up.)

The `host` getter currently returns the host part of the URI string. It does not return the interpretation.

The problem is exacerbated by the `host` getter *not* returning the `[` and `]` surrounding an IPv6 address. We can't choose to unescape IPv6 addresses and not unescape host names because the user cannot tell the difference from the `host` getter value itself, and they might unescape it again, which would make a zone ID of  `%2525` be wrong.

Maybe we could add an extra getter (`hostName`? That'll be confusing!) which returns the unescaped version of `host`. Then code should be migrated to that.

Or we could make `host` unescape automatically, under the assumption that currently used host names never contain escapes anyway. That's a hypothesis that needs testing. It would break with the overall design of the `Uri` class, where `host`, `path`, `query` and `fragment` return the actual URI text, and you have to use `pathSegments` or `queryParameters` to get the interpreted version.
