### ISSUE TITLE
Missing bounds check on dynamic calls

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37572]
language_2/generic_function_bounds_test is currently failing on VM configurations, e.g.

https://dart-ci.appspot.com/log/vm-kernel-linux-debug-x64/dartk-linux-debug-x64/5841/language_2/generic_function_bounds_test

The failure seems to be because of a missing check that the type arguments produced by "instantiate to bounds" correctly satisfy the type parameter bounds.

Interestingly, this failure only happens for local functions and not for top level functions: see below for a small reproduction.  Currently, running this program with bleeding edge dart produces:

```
Global: passed
Local: failed
```

```dart
void i<T extends Iterable<T>>() => null;
main() {
  void j<T extends Iterable<T>>() => null;
  try {
    (i as dynamic)();
    print("Global: failed");
  } catch (e) {
    print("Global: passed");
  }
  try {
    (j as dynamic)();
    print("Local: failed");
  } catch (e) {
    print("Local: passed");
  }
}
```

**Comment by leafpetersen** [comment]
I split the relevant test into a multi-test [here](https://dart.googlesource.com/sdk/+/b74ae33406f079e0814a5757e3eb2f8b3022582f).  The relevant (failing) tests are now:
  - language_2/generic_function_bounds_test/01 
  - language_2/generic_function_bounds_test/03

**Comment by ZichangG** [comment]
Thanks for creating the tests! I will come back to this later. There are several more important issues waiting.

**Comment by crelier** [comment]
These tests only fail in dart_precompiled configurations. However, the problem does not seem related to the precompiler, but to the fact that a dill file is generated in an intermediary step.

I have reduced this issue to this small repro that does not involve the precompiler:

```
cat ~/bug1.dart
main() {
  g<T extends U, U extends num>(T x, U y) => x;
  print(g<double, int>(42.0, 100));
}

```
An exception is thrown as expected when executed this way:
```
out/DebugX64/dart ~/bug1.dart
Unhandled exception:
type 'double' is not a subtype of type 'int' of 'T'
#0      main.g (file:///usr/local/google/home/regis/bug1.dart:2:40)
#1      main (file:///usr/local/google/home/regis/bug1.dart:3:10)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
However, the bounds check is ignored when generating a dill file as an intermediate step:
```
pkg/vm/tool/gen_kernel --platform=out/DebugX64/vm_platform_strong.dill -o ~/out.dill ~/bug1.dart
out/DebugX64/dart ~/out.dill
42.0
```

The dumped dill file starts with:
```
main = bug1::main;
library from "file:///usr/local/google/home/regis/bug1.dart" as bug1 {

  static method main() → dynamic {
    function g<T extends U* = core::num*, U extends core::num* = core::num*>(T* x, U* y) → T*
      return x;
    core::print([@vm.call-site-attributes.metadata=receiverType:<T extends U* = dart.core::num*, U extends dart.core::num* = dart.core::num*>(T*, U*) →* T*] g.call<core::double*, core::int*>(42.0, 100));
  }
}
```

Actually, I would expect the CFE to give a static error in this case. We should not even be able to generate a dill file or run. So I am reassigning to the CFE team.

**Comment by crelier** [comment]
As @alexmarkov points out, the small repro may be a different problem.
The original issue may be in the aot pipeline and be related to https://github.com/dart-lang/sdk/issues/38254

**Comment by alexmarkov** [comment]
The problem might be in AST-specific flow graph builder as these test cases (`language_2/generic_function_bounds_test/01`, `language_2/generic_function_bounds_test/03`) pass in bytecode mode (after https://dart-review.googlesource.com/c/sdk/+/117931 landed).

**Comment by crelier** [comment]
The reason it worked when not using an intermediate dill file is that the bytecode pipeline was used in this case and it does not have this issue.
The problem was that bound checking should never be skipped when invoking a closure.
