### ISSUE TITLE
DartType.operator== needs to account for nullability suffixes

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#37587]
Currently, `DartType.operator==` does not account for nullability suffixes, so types like `int` and `int?` are treated as equal.

Possibly related issue: #35331

**Comment by scheglov** [comment]
Work in progress:
https://dart-review.googlesource.com/c/sdk/+/107444

I will need to re-run tests and over internal code, there might be some issues that are not yet solved.
