### ISSUE TITLE
Add https://github.com/dart-lang/tflite_native to chromium mirror

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37583]
Please add https://github.com/dart-lang/tflite_native to the https://chromium.googlesource.com/external/github.com/dart-lang/ mirror.

**Comment by whesse** [comment]
We don't use the chromium mirror anymore, we use dart.googlesource.com for everything.  Was there documentation that was not updated yet, using that old name?
Created the mirror in dart.googlesource.com/tflite_native.

**Comment by lambdabaa** [comment]
> We don't use the chromium mirror anymore, we use dart.googlesource.com for everything. Was there documentation that was not updated yet, using that old name?

Thank you! I think I just copied this from another mirror request.
