### ISSUE TITLE
Support code-folding of 'if/else' blocks in VS Code

### ISSUE THREAD

**Issue by TheTrainor** [dart-lang/sdk#37582]
I'd like to request the ability to fold 'if/else' blocks of code within VS Code. Just as it works for function or class blocks.

@DanTup, following up from the quick request on gitter ;-)

Cheers!

**Comment by he0119** [comment]
is there any update on this?

**Comment by DanTup** [comment]
Sorry for the delay - this has been implemented (f0e1f32c87c805bea8b8b2e50694338b0c494845) and will be available in an upcoming SDK release.

(@bwilkerson this can be closed - I don't have permissions to do it)

**Comment by TheTrainor** [comment]
Thanks DanTup, looking forward to that SDK release!
