### ISSUE TITLE
Dart Embedding API never calls Platform::Initialize()

### ISSUE THREAD

**Issue by kpozin** [dart-lang/sdk#37586]
`Platform::Initialize()` (defined in [platform.h](https://github.com/dart-lang/sdk/blob/9cd47ac2e6ac024e5a0fd1d5667d94a8c2fd2d5e/runtime/bin/platform.h#L17)) is only called [in the CLI](https://github.com/dart-lang/sdk/blob/9cd47ac2e6ac024e5a0fd1d5667d94a8c2fd2d5e/runtime/bin/main.cc#L1068) and [in `gen_snapshot`](https://github.com/dart-lang/sdk/blob/9cd47ac2e6ac024e5a0fd1d5667d94a8c2fd2d5e/runtime/bin/gen_snapshot.cc#L856).

It is not called in any code path reachable from the Dart Embedding API. This is problematic for Fuchsia because we would like to perform some initialization in `Platform` on the main runner thread (as opposed to component threads).

**Comment by zanderso** [comment]
`Platform::Initialize()` is currently conflating VM initialization with the (as yet unwritten) process-wide initialization needed for the `dart:io` `Platform` APIs. I think it would be okay to add a new method to `Platform` like `Platform::InitOnce`, do the API initialization from there, and call it from `dart::bin::BootstrapDartIo()` and `dart::embedder::InitOnce`. Maybe also rename `Platform::Initialize()` to `Platform::InitializeVM()` or something like that. @sortie @a-siva.

**Comment by a-siva** [comment]
@zanderso is there another issue tracking process-wide initialization for dart:io Platform APIs ?

**Comment by zanderso** [comment]
@kpozin if there is an internal issue tracking the work for which the Platform API initialization is needed, could you share the issue number here?

**Comment by kpozin** [comment]
@zanderso I18N-30

**Comment by bkonyi** [comment]
Fixed in [this CL](https://dart.googlesource.com/sdk/+/729099cc5bee54ea86839fe5303cab1f5259941f).

**Comment by a-siva** [comment]
We had a discussion regarding this and the question was why should the Dart embedding API provide a means for calling Platform::InitOnce().
This function is present in runtime/bin and it should be possible for the embedder to call it directly when appropriate. We should also make sure every embedder has an appropriate version of Platform::InitOnce() (some of them may not want to do the signal initialization stuff that is currently being done for the standalone embedder)

**Comment by bkonyi** [comment]
@a-siva should we just close this issue?
