### ISSUE TITLE
[benchmarks/ffi] Generate repetitive benchmark code

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37581]
The `dart:ffi` [benchmarks](https://dart-review.googlesource.com/c/sdk/+/108724) have repetitive patterns in the benchmark code. This is hard to maintain and easy to get wrong. We should use code generation to address this.

Follow up of https://github.com/dart-lang/sdk/issues/36247.

**Comment by sjindel-google** [comment]
@dcharkes Can you please assign an estimate?

**Comment by dcharkes** [comment]
The estimate includes the part of figuring out how to generate Dart code in the SDK.

Generated benchmarks are under review, still some tweaking to be done there:
https://dart-review.googlesource.com/c/sdk/+/114201
https://dart-review.googlesource.com/c/sdk/+/114068
