### ISSUE TITLE
shift-command-return does not add ; for imports

### ISSUE THREAD

**Issue by lookfirst** [dart-lang/sdk#37609]
Originally [filed the issue with IDEA](https://youtrack.jetbrains.com/issue/WEB-39931
), but apparently it is upstream, so refiling here.

When typing out an import, shift-command-return does not add the trailing ; for imports.

**Comment by alexander-doroshko** [comment]
@devoncarew, Statement Completion functionality comes from the Analysis Server, so I think `area-analyzer` would be a correct label here. 
//cc @stevemessick

**Comment by alexander-doroshko** [comment]
@devoncarew

**Comment by scheglov** [comment]
It looks that much changed since then, and now we suggest `import` together with `;`.
<img width="571" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/d205943e-74c4-4f1e-83bd-a58688a97470">
Whether I use Enter or Cmd+Shift+Enter, it inserts `;`.

**Comment by lookfirst** [comment]
5 years isn't too bad! Thanks for resolving this.
