### ISSUE TITLE
Constant evaluation doesn't record instantiation information for generic functions.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#37608]
Consider the following code (adapted from https://github.com/dart-lang/sdk/blob/master/pkg/front_end/test/constants/data/function.dart):
```dart
T method1<T>(T t) => t;
const function0 = method1;
const int Function(int) instantiation0 = method1;
```
The analyzer computes the same constant value for both `function0` and `instantiation0`.  But in fact they are not the same constant.  Type inference should determine that in order for `method1` to match the declared type of `int Function(int)`, the generic function `method1` needs to be instantiated with the type parameter `int`, so the constant value of `instantiation0` should reflect this.

Discovered while adapting the analyzer to use the CFE/dart2js "ID test" framework.
I'm currently working on a CL that demonstrates the bug.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/118379
