### ISSUE TITLE
Testing infra compiles with .dill files from mismatched versions of the SDK

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#37619]
Sometimes there are strange failures when running tests with the testing infrastructure that don't appear if you simple invoke DDK on the test directly. 

I believe this is because there are some .dill files that are created using the prebuilt version of the SDK. 
https://github.com/dart-lang/sdk/blob/master/utils/dartdevc/BUILD.gn#L262-L306

Usually this is fine but in some instances they are not compatible. For example, when we landed the constants-update-2018 experiment any .dill files created with the prebuilt version of the SDK are lacking the information needed by DDK to support the new constant evaluation and causes strange failures during testing. See the ongoing dry runs for this change.
https://dart-review.googlesource.com/c/sdk/+/109640

I think a temporary workaround would be submit a new version of the prebuilt SDK.

This will probably be a problem again in the future with more experiments so we will need a more permanent fix. We need to move the building of the libraries used for dartdevc_test into the test.py and use the current SDK to generate the .dill files.

@Markzipan @munificent @whesse @athomas @sortie

**Comment by Markzipan** [comment]
Further supporting this, passing `--enable-experiment constant-update-2018` to `pkg/dev_compiler/tool/build_pkgs.dart` resolves the problem (.dill files look correct).

**Comment by Markzipan** [comment]
I may have been testing under the false assumption that the constant update had been reenabled. So while it's not clear if this issue doesn't exist, this issue isn't a blocker on the constant update.

**Comment by nshahan** [comment]
Closing for now but can reopen if we can repro and confirm that this is an issue.
