### ISSUE TITLE
Dart is printing wrong newlines on console outputs in AOT snapshots

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#37616]
_Follow the request of @DanTup on https://github.com/dart-lang/sdk/issues/32172#issuecomment-514519159._

Dart is printing newlines wrongly on console log outpus when compiled to AOT snapshots:

```
Starting server
Starting server
Starting serverStarting server
Starting server
Starting server
Starting server

Starting server

```
My dart code spawns some isolates (one for each processor's core):

```dart
void main([List<String> args]) {
  _buildServers();
}

void _buildServers() {
  for (int i = 0; i < Platform.numberOfProcessors - 1; i++) {
    Isolate.spawn(_startServer, null);
  }

  _startServer(null);
}

const String _GREET = 'Hello World';

_startServer(arg) async {
  var server = await HttpServer.bind(
    InternetAddress.loopbackIPv4,
    666,
    shared: true,
  );

  print("Starting server");

  await for (HttpRequest request in server) {
    print("New request");
    request.response
      ..write(_GREET)
      // ignore: unawaited_futures
      ..close();
  }
}
```

Put that code in a dart file then do a `dart2aot mydart.dart mydart.aot`
After that open a console window (I am testing on windows with Powershell but also happens on CMD).

```dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"```

**Comment by rmacnak-google** [comment]
This looks like the prints from multiple isolates got interleaved, rather than any issue with newline encoding. Note that `print` has no atomicity guarantee, so interleaving is valid behavior.

**Comment by shinayser** [comment]
Your hipetesis sounds correct! There is a way to prevent that?

**Comment by dgrove** [comment]
As @rmacnak-google says, this is intended behavior. Some sort of serialization point is going to be needed in the application.

**Comment by shinayser** [comment]
But it doesn't make much sense...
Can you give a guidance of how should it be done, since dart's isolantes doesn't share memory? There is some library that helps with it? 
Any help is appreciated.
