### ISSUE TITLE
VM uses incorrect path for dill manifest when run from the same directory

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#37610]
If I create a dill manifest file with relative file paths and I run it with a working directory at least 1 level up from the manifest file it works - if my working directory is the same as the directory of the manifest file it does not work.

We're still unable to use the new feature from #33952 

The `kernel_list_dirname` for input `script_uri` of `try.vm.app.dart` is `try.vm.app.dart` which can't be concatenated with a relative path. The `kernel_list_dirname` for input `script_uri` of `bin/try.vm.app.dart` is `bin/` which _can_ be concatenated with a relative path.

https://github.com/dart-lang/sdk/blob/2ada1edb59003ed02236efcb06ac671c7c30fdb8/runtime/bin/dfe.cc#L442

I think we want to check whether we go the same result back and in that case use an empty prefix.

Some other things that made this difficult to track down:
- If anything goes wrong we bail out and attempt to parse as a Dart file. `#@dill` will never be the leading content of a valid Dart file as far as I know - so it's not very useful to have this behavior once we see the magic number for a dill manifest.
- The end of the file _must_ be `\n`. A missing trailing newline, or an extra blank line (`\n\n`) cause it to consider it an invalid kernel manifest and fall back to parsing as Dart.

**Comment by natebosch** [comment]
Since we're using OS specific file separators I strongly suspect we'll also have an issue with hermetic builds across OSes...

**Comment by aam** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/3999da08921e7fdc4370ac077802c51a87d26da4
