### ISSUE TITLE
dart2js: constant-update-2018: timeout for language_2/canonicalization_hashing_shallow_collision_array_test

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37611]
This test times out (if left to run it takes ~15 minutes.)
```
tools/test.py -m release -c dart2js -r d8\
   --dart2js-options --enable-experiment=constant-update-2018 \
  language_2/canonicalization_hashing_shallow_collision_array_test
```
Deserializing the type inference results takes too long.
```dart
abstract class AbstractDataSource extends DataSourceMixin
    implements DataSource {
  ...
  ir.TreeNode _readTreeNode(_MemberData memberData) {
    _TreeNodeKind kind = _readEnumInternal(_TreeNodeKind.values);
    switch (kind) {
      ...
      case _TreeNodeKind.constant:
        // TODO(johnniwinther): Support serialization within a member context
        // and use this to temporarily cache constant node indices.
        ir.ConstantExpression expression = _readTreeNode(memberData);
        _ConstantNodeIndexerVisitor indexer = new _ConstantNodeIndexerVisitor();
        expression.constant.accept(indexer);
        ir.Constant constant = indexer.getConstant(_readIntInternal());
        return new ConstantReference(expression, constant);
```

 - [ ] One problem with this test is that there are type inference results for each of the sub-constants `[1]`, `[2]` etc in the big constant:
```dart
const [[1], [2], [3], ...]
```
The huge top-level constant is re-indexed to call `indexer.getConstant` for each sub-constant.

- [x] Another problem is that _ConstantNodeIndexerVisitor is not DAG-aware. This causes language_2/canonicalization_hashing_memoize_array_test to run out of memory.

/cc @johnniwinther - where is the right place to put a shared _ConstantNodeIndexerVisitor?

**Comment by rakudrama** [comment]
Second issue fixed by https://dart-review.googlesource.com/c/sdk/+/110186

**Comment by a-siva** [comment]
The dart2js bots show errors on this test after const_update_2018 flag was turned on by default and the results have been approved to turn the bots green
- dart2js-rti-linux-x64-d8
- dart2js-strong-hostasserts-linux-ia32-d8 
- dart2js-minified-strong-linux-x64-d8
- dart2js-strong-linux-x64-chrome
- dart2js-csp-minified-linux-x64-chrome
- dart2js-strong-linux-x64-firefox
