### ISSUE TITLE
Null coverage on returned range

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#37612]
I recently had to provide a work around on a null coverage value for a range returned by the VM, see: https://github.com/dart-lang/coverage/pull/260

I believe the root cause was due to a script that used the `native` keyword. Is this expected?

**Comment by bkonyi** [comment]
It's hard to say without a reproduction case. Do you happen to have one?

**Comment by bkonyi** [comment]
Friendly ping @grouma. Do you have a reproduction case by any chance?

**Comment by grouma** [comment]
Followed up internally for the repo.

**Comment by bkonyi** [comment]
> Followed up internally for the repo.

Sorry for the delay, I'll take a look. Thanks!

**Comment by bkonyi** [comment]
cc/ @ZichangG do you have some cycles to investigate this? I can forward you the relevant information for the repro if you're willing to take a look.

**Comment by ZichangG** [comment]
Sure. Not a problem, I'm looking at another coverage issue.

**Comment by bkonyi** [comment]
> Sure. Not a problem, I'm looking at another coverage issue.

Thanks! I'll forward you the information shortly.

**Comment by ZichangG** [comment]
According to the comments of coverage: 
> Provided only when the Coverage report has been requested and the range has been compiled.

So I think null check/ compiled check is required.

Checkout the commemts of coverage:
https://github.com/dart-lang/sdk/blob/f22f62c85dd4957c594d23b547e72d72aa66e0e3/pkg/vm_service/lib/vm_service.dart#L5678
