### ISSUE TITLE
Dart2js output isn't hermetic if deferred loading is used

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#37623]
I noticed today that if you use deferred loading it adds lines like this to the output JS which includes absolute file uris:

```
H.checkDeferredIsLoaded("message", "file:///tmp/scratch_spaceJVGEKY/web/sub/message.dart");
```

This is given command line args with a relative path like `-oweb/main.dart.js web/main.dart`.

I think we might not be hitting this internally if we are using the `google3://` style uris, so we could potentially work around it with a similar thing in build_web_compilers as well.

**Comment by rakudrama** [comment]
Yes, having two compilations produce different bits as a result of using different tmp directories is a problem.

The URI argument to `checkDeferredIsLoaded` is used only in error messages. It could be changed without much impact. Imports of packages seem to have `package:` style URIs, so it is only libraries in the main package that have this problem.

See also https://github.com/dart-lang/sdk/issues/29637.
