### ISSUE TITLE
empty fails in nightly fuzz runs

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#37632]
We sometimes see failures with an empty fail report, as in:

```
Isolate (/b/s/w/itTbo578/dart_fuzzYMJHUK) FP : JIT-O3-ReleaseIA32 - JIT-noVFP-ReleaseSIMARM: !DIVERGENCE! 1.15:2617449246 (ResultCode.error vs ResultCode.success)

fail1:
```

Most of the time these don't reproduce locally. We should find out what those are, probably with some more elaborate logging.

**Comment by feli-citas** [comment]
Another example:
```

Isolate (/b/s/w/itxHXNaV/dart_fuzzFFMSIM) FP : KBC-INT-ReleaseX64 - KBC-INT-DebugX64: !DIVERGENCE! 1.15:2418783284 (ResultCode.error vs ResultCode.success)

fail1:
910343936

```

**Comment by aartbik** [comment]
Doc on exit codes in Dart:

https://api.dartlang.org/stable/1.10.1/dart-io/Process/exitCode.html

**Comment by aartbik** [comment]
Still happening:

```
NO-FP : JIT-DebugX64 - JIT-O3-DebugIA32: !DIVERGENCE! 1.16:669171839 (ResultCode.success vs ResultCode.error)

fail2:
1550122496
throws
....

FP : JIT-ReleaseX64 - KBC-CMP-ReleaseX64: !DIVERGENCE! 1.16:3479128508 (ResultCode.success vs ResultCode.error)

fail2:
451638528

NO-FP : JIT-DebugSIMARM - KBC-MIX-ReleaseX64: !DIVERGENCE! 1.16:571594142 (ResultCode.success vs ResultCode.error)

fail2:
956745984
false
throws
....
```

**Comment by aartbik** [comment]
The re-run mechanism works!

> Isolate (/b/s/w/it5ye5SS/dart_fuzzZQJAVP) FP : JIT-ReleaseSIMARM64 - KBC-CMP-O3-DebugX64: !DIVERGENCE! 1.16:2550338632 (ResultCode.success vs ResultCode.error)
> 
> fail2:
> 64528128
> 
> Commencing re-run .... 
> No error on re-run

**Comment by aartbik** [comment]
The good thing is that we now have less false divergences to look at. However, I am still a bit uncomfortable about ignoring all fails that succeed the second time around, since we may miss non-deterministic bugs in the VM/compiler. So let's restrict the rerun to exits codes outside the [-255..255] range.
