### ISSUE TITLE
new Element.html("<tr></tr>") throws an error

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#37639]
* Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

```
 Element.html('<tr></tr>', treeSanitizer: NodeTreeSanitizer.trusted);
```

```
Uncaught Bad state: No element
```

**Comment by rileyporter** [comment]
Thanks for filing this bug, sorry it took us so long to get to it! 

In `Element.html`, the HTML fragment is parsed as if it occurred within the context of a `<body>` tag, so some special elements like `<tr>` that must be parsed within the scope of a `<table>` will be dropped if they aren't in the right context. That is what is happening here. You can use [createFragment](https://api.dart.dev/stable/2.15.1/dart-html/Element/createFragment.html) to parse contextual HTML fragments, or try using [the Element `tr` factory](https://api.dart.dev/stable/2.14.4/dart-html/Element/Element.tr.html) if you just want to make a `<tr>` element.
