### ISSUE TITLE
dart:ffi fails to expose libtensorflowlite_c.dll on windows

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37648]
I built two versions of libtensorflowlite_c.dll. One was using clang-on-windows and the other was using Microsoft's VS toolchain. I used [depends.exe](http://www.dependencywalker.com/) to inspect both and they each look to have the correct symbols defined

![DIIASl0](https://user-images.githubusercontent.com/535859/61984135-ec4f3280-afb7-11e9-8ae0-8d2360597303.png)

The clang-on-windows build:

`DynamicLibrary.open('libtensorflowlite_c.dll')` seems to work but then calling lookup on any symbol fails with `Invalid argument(s): Failed to lookup symbol (127)`.

The Microsoft toolchain build:

`DynamicLibrary.open('libtensorflowlite_c.dll')` fails with `Invalid argument(s): Failed to load dynamic library (126)`

To reproduce you can do

```
git clone git@github.com:dart-lang/tflite_native.git
cd tflite_native
git checkout 712b8a93fbb4caf83ffed37f154da88c2a517a91  # clang-on-windows
pub get && pub run test
git checkout 7c9c2ca00f279c33e8d234c041d96eccd2590b76 # ms toolchain
pub run test
```

**Comment by YowFung** [comment]
@lambdabaa I met the same problem, how did you solve it?
I want to use the `libssh2.dll`. 

Initially, I copied the DLL from somewhere into my flutter project folder and used `DynamicLibrary.open("libssh2.dll")` to load it, but it failed. Later, I downloaded the source code from [libssh2.org](https://www.libssh2.org/) and generated a new DLL file in Visual Studio. This time, it could load but said `Failed to lookup symbol (127)`.
