### ISSUE TITLE
unused_import considers [ClassName], but not [new ClassName]

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37649]
See the example below.

For line one, everything is fine.
For line two, (if it's the only reference to HahsMap in the code), then you get an `unused import` hint.

If you remove the import, the `comment_references` lint lights up.

```dart
import 'dart:collection' show HashMap;

/// [HashMap] references the class
/// [new HashMap] references the constructor
final something = null;
```

**Comment by kevmoo** [comment]
CC @pq RE linter overlap.

**Comment by pq** [comment]
Thanks @kevmoo!

@bwilkerson: regarding overlap (and the need to track separately for the linter), my guess is that if we fix this in `analyzer` it will "just work" for the lint (as `identifier.staticElement` will be non-null?):

https://github.com/dart-lang/linter/blob/c4657c3c1fe0ea5d60b79bd6d2875f5390308e44/lib/src/rules/comment_references.dart#L98

**Comment by bwilkerson** [comment]
That's my expectation as well.

**Comment by kevmoo** [comment]
That would be wonderful!

**Comment by pq** [comment]
This one looks fixed.  Please re-open if any issues persist!
