### ISSUE TITLE
How to ignore the rule of lines_longer_than_80_chars when run "flutter format -n --set-exit-if-changed ."

### ISSUE THREAD

**Issue by qiuyu-y** [dart-lang/sdk#37657]
when i run 'flutter format -n --set-exit-if-changed ." , it return 'Formatting failed: 1' , how can i ignore the rule of lines_longer_than_80_chars to let it return success

i try to use the "lines_longer_than_80_chars: false" to ignore it , but it doesn't work

<img width="510" alt="WeChatca8e36d41af585847ad9bde81a8f12d3" src="https://user-images.githubusercontent.com/53244695/62018213-4df7e280-b1ec-11e9-99ad-0bf1054b4235.png">

**Comment by mit-mit** [comment]
I don't believe `flutter format` let's you set a line length. But maybe you can use `dartfmt`?

```
Usage:   dartfmt [options...] [files or directories...]

Example: dartfmt -w .
         Reformats every Dart file in the current directory tree.

Common options:
-h, --help                           Shows usage information.
    --version                        Shows version information.
-l, --line-length                    Wrap lines longer than this.
                                     (defaults to "80")
```

**Comment by qiuyu-y** [comment]
Setting line length is workable through IntelliJ Preference，so after setting like this, the flutter format return 'Formatting failed: 1' 

<img width="2024" alt="WeChat08c5d56a40d35168fd670eb669a0c0e7" src="https://user-images.githubusercontent.com/53244695/62264510-c9f36400-b452-11e9-940f-d62a4193d716.png">

**Comment by mit-mit** [comment]
Try `flutter format -n --set-exit-if-changed -- --line-length 140 .`

**Comment by mohak852** [comment]
> flutter format -n --set-exit-if-changed -- --line-length 14

This command is not running it got stuck and I am unable to solve this issue please help me in this
@mit-mit
