### ISSUE TITLE
Adding very small doubles results in double.infinity

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#37650]
On the VM (JIT), `1.7976931348623157e+308 - -1.7976931348623157e+308` evaluates to `double.infinity`.

This seems like a bug, but I might just not be understanding IEEE 754 correctly.

See https://github.com/flutter/flutter/pull/37049 for context

**Comment by dnfield** [comment]
Well, based on the fact that JavaScript, Java, and C++ also evaluate this to infinity, I'm going to close this - it looks like it's just IEEE 754.

**Comment by flar** [comment]
1.8e308 is approximately the maximum positive finite double value.
X - -X == X + X, so we are trying to compute twice the approximate maximum double value and that results in a double too large to represent with a finite value so it becomes infinite.
