### ISSUE TITLE
Create a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#37663]
We have https://dart.dev/code-of-conduct, but maybe dart-lang/sdk should have a CODE_OF_CONDUCT.md file.

Details:
* dart.dev/code-of-conduct is aimed at all community members, not just contributors.
* dart.dev/code-of-conduct is similar to the beginning of [Flutter's code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), which is aimed at contributors.
* dart-lang/sdk's CODE_OF_CONDUCT.md could point to dart.dev/code-of-conduct and (if necessary) add info specific to working on the sdk repo or code repos. Or it could be more like Flutter's code of conduct.

More info: https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project

Related: #30051

/cc @timsneath

**Comment by kevmoo** [comment]
We should use/update https://github.com/dart-lang/.github/blob/master/CODE_OF_CONDUCT.md

This is inherited by ALL repos under dart-lang. 😄

**Comment by kwalrath** [comment]
I don't know how the GitHub integration works... I don't see anything magical happening because flutter/flutter has a CODE_OF_CONDUCT.md file. But we could advertise the code of conduct better, wherever conduct issues are likely to come up.

**Comment by kwalrath** [comment]
I did see a link to the dart-lang CODE_OF_CONDUCT.md file when I was creating a PR here; I don't recall seeing that link anywhere else in the GitHub UI. So we should continue to link to the code of conduct, as necessary.

#40024 modifies CONTRIBUTING.md to add a link to the code of conduct. If you can think of other places that need to link to it, please add them to https://github.com/dart-lang/site-www/issues/1792.
