### ISSUE TITLE
don't know why

### ISSUE THREAD

**Issue by abdullahbasaran** [dart-lang/sdk#37661]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1280x800  Retina`

**Comment by kevmoo** [comment]
Please include full details of the crash. This isn't enough information to debug!
