### ISSUE TITLE
Improve performance of async functions when causal async stacks are turned on 

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37668]
When the VM runs with --causal-async-stacks (default is on), async code can be quite slow due to the eager stack trace collection in async functions.

We should look into how we can implement this faster in our current system. In particular in AOT mode this is heavy because it needs to map return addresses from the stack to code objects.

Looking a bit forward we can also consider investigating if it makes sense to implement coroutines in the VM.

**Comment by mkustermann** [comment]
See also [V8 Zero-cost async stack traces](https://bit.ly/v8-zero-cost-async-stack-traces), where the stack trace is constructed at exception-throwing time using the registered callbacks in the Promises/Futures data structures.

**Comment by mkustermann** [comment]
See also https://github.com/dart-lang/sdk/issues/29189

**Comment by cskau-g** [comment]
The --lazy-async-stacks CL has now landed.

**Comment by mkustermann** [comment]
@cskau-g has landed lazy async stack now and the old causal async stack support got removed. So there's nothing left to do. Closing.
