### ISSUE TITLE
Consider updating allocation stats only if observatory needs the information

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37678]
The allocation stubs we generate are currently always updating the allocation statistics tables even if no observatory is connected (we only avoid this in product mode). 

See e.g. [StubCodeCompiler::GenerateAllocationStubForClass](https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/stub_code_compiler_x64.cc):
```
void StubCodeCompiler::GenerateAllocationStubForClass(Assembler* assembler,
                                                                                              const Class& cls) {
     ...
  if (FLAG_inline_alloc &&
      target::Heap::IsAllocatableInNewSpace(instance_size) &&
      !target::Class::TraceAllocation(cls)) {
    ...
    NOT_IN_PRODUCT(__ UpdateAllocationStats(target::Class::GetId(cls)));
```

Our normal sdk we distribute is a release sdk and our tools like dart2js also run in release mode. So we might want to consider to only collect statistics **if we actually need** them, i.e. for observatory, instead of eagerly on every single allocation.

-> We should make our allocations as fast as we can possibly make them.

@rmacnak-google @a-siva @mraleph

**Comment by mraleph** [comment]
We should disable this accounting and do a run to collect performance data. If we see significant performance improvement then we should discuss potential ways to reduce the overhead.

**Comment by rmacnak-google** [comment]
Regenerating the allocation stubs after a service client connects would work for the "current" values in the allocation statistics, but it would not work for the "accumulated" or "promoted" values, or at least it would require a breaking change that the accumulators can be off and start off.

@bkonyi
