### ISSUE TITLE
"finally" block runs even if a return happens on "try" block

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#37672]
I might be getting crazy but as far as I know the `return` keyword should stop the code execution, right?

Check this code:

```dart
void main() {
  var returnedValue = getAnInteger();
  print("Value: $returnedValue");
}

getAnInteger() {
  try {
    return 10;
  } finally {
    return 666;
  }
}
```
It prints:
```
Value: 666
```

Is this a bug?

_My dart version_: 
```
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
```

**Comment by kevmoo** [comment]
CC @munificent @lrhn who may have quick wisdom here...

**Comment by eernstg** [comment]
The finally block is executed after the execution of the try block completes (cf. [this text](https://github.com/dart-lang/language/blob/54c7e33580df7d43b98ad30022c630a7c5b2acf8/specification/dartLangSpec.tex#L12928)).

The wording `even if execution of $b$ did not complete normally` in that line confirms that there are other cases, e.g., when the execution returns or throws.

Note that Java does the same thing: https://programming.guide/java/try-finally.html.

**Comment by shinayser** [comment]
Thanks for the clarification!
