### ISSUE TITLE
HttpClient throws exception form some (invalid?) www-authenticate header values

### ISSUE THREAD

**Issue by karoitay** [dart-lang/sdk#37696]
I'm experiencing this issue where HttpClient fails to parse some (invalid?) www-authenticate response header.

For example:
The result of `curl -i -X POST https://api.thetvdb.com/login` is:

```
HTTP/2 401 
date: Mon, 29 Jul 2019 09:15:50 GMT
content-type: application/json; charset=utf-8
content-length: 26
set-cookie: __cfduid=d0a0c5ee3934fe0f08c3ddd136ab53e471564391749; expires=Tue, 28-Jul-20 09:15:49 GMT; path=/; domain=.thetvdb.com; HttpOnly
vary: Accept-Language
www-authenticate: JWT realm=jwt auth
x-powered-by: Thundar!
x-thetvdb-api-version: 2.2.0
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4fddfd9498b5c2c2-FRA

{"Error":"Not authorized"}
```

When I try to post to the same url using HttpClient, I get an exception
```dart
import 'dart:io';

Future main() async {
  var httpClient = HttpClient();
  var request = await httpClient.postUrl(Uri.parse('https://api.thetvdb.com/login'));
  await request.close();
  httpClient.close();
}
```
```
HttpException: Failed to parse header value
#0      _HeaderValue._parse.expect (dart:_http/http_headers.dart:684:9)
#1      _HeaderValue._parse.parseParameters (dart:_http/http_headers.dart:764:15)
#2      _HeaderValue._parse (dart:_http/http_headers.dart:773:20)
#3      _HeaderValue.parse (dart:_http/http_headers.dart:626:12)
#4      _HttpClientResponse._authenticate (dart:_http/http_impl.dart:476:22)
#5      _HttpClientRequest._onIncoming (dart:_http/http_impl.dart:1093:25)
#6      _HttpClientConnection.send.<anonymous closure>.<anonymous closure> (dart:_http/http_impl.dart:1741:17)
#7      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

The `www-authenticate` header returned from the server may not be valid but it feels like HttpClient should fail gracefully so that callers still be able to get the response object and just skip authentication (just like the 'no credentials available' [here](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/http_impl.dart#L550)).

Thanks,
Itay

**Comment by zichangg** [comment]
I believe this works as intended.

The parser failed to understand the syntax because the response of `www-authenticate` is not valid. There is no way we can continue the parsing. It shouldn't have `"auth"` after the `"real=jwt"`.

Here is an example (Section 3): 
http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html and https://tools.ietf.org/html/rfc2617#section-2

**Comment by abhaysood** [comment]
I'm facing the same issue. For 401s a server I need to interact with responds with the header:
WWW-Authenticate: Bearer realm=<custom_realm_value>, error=invalid-token, error_description=Invalid bearer token.

Note that the value in _realm_ can be any string and the header value contains spaces after _commas_. Which is completely valid based on my understanding.

Quoting from the [RFC](https://tools.ietf.org/html/rfc2617#section-2):

> Upon receipt of an unauthorized request for a URI within the protection space, the origin server MAY respond with a challenge like the following: WWW-Authenticate: Basic realm="WallyWorld"

I don't think the _HTTPClient_ should assume what a server will respond with. We are facing this issue which is blocking us from handling refresh tokens when a 401 response is received.

**Comment by Nei1eveN** [comment]
We are facing the same issue as well. Do we have an alternative for this aside from using platform channels?

> I'm facing the same issue. For 401s a server I need to interact with responds with the header: WWW-Authenticate: Bearer realm=<custom_realm_value>, error=invalid-token, error_description=Invalid bearer token.
> 
> Note that the value in _realm_ can be any string and the header value contains spaces after _commas_. Which is completely valid based on my understanding.
> 
> Quoting from the [RFC](https://tools.ietf.org/html/rfc2617#section-2):
> 
> > Upon receipt of an unauthorized request for a URI within the protection space, the origin server MAY respond with a challenge like the following: WWW-Authenticate: Basic realm="WallyWorld"
> 
> I don't think the _HTTPClient_ should assume what a server will respond with. We are facing this issue which is blocking us from handling refresh tokens when a 401 response is received.
