### ISSUE TITLE
Implement static support for the null check operator.

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#37692]
See [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#null-check-operator) of the feature spec.

**Comment by johnniwinther** [comment]
Landed in https://dart-review.googlesource.com/c/sdk/+/118380

**Comment by johnniwinther** [comment]
Inference handled in https://dart-review.googlesource.com/c/sdk/+/130705

**Comment by johnniwinther** [comment]
We still need to figure out whether the type context should be nullable (like for lhs of ??).

**Comment by stefantsov** [comment]
@johnniwinther I think we may take the following comment for the answer: https://github.com/dart-lang/sdk/issues/39694#issuecomment-562673214.

**Comment by stefantsov** [comment]
Following https://github.com/dart-lang/sdk/issues/39694#issuecomment-562673214 the proposed fix is to make the context nullable: https://dart-review.googlesource.com/c/sdk/+/134330
