### ISSUE TITLE
Rebuilding SDK fails because of file permission errors

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#37698]
Building the SDK in a clean directory works the first time. Trying to rebuild the SDK will produce errors when trying to copy files related to the language_model.

Repro:
In an SDK checkout at master (bd049f5b53ef0730fa6cbd7b88656f1bec308283 as I write this):

1) Build the SDK the first time. I'm running on a mac and I use the commands:
`./tools/build.py -m release -a x64 create_sdk`
It should complete normally.

2) Make an edit to any file in the sdk. For example, simply add a new comment to the file
`sdk/lib/collection/collection.dart`.

3) Run the same command to build the SDK again.
`./tools/build.py -m release -a x64 create_sdk`

Errors should appear:
```
FAILED: dart-sdk/model/CIPD_VERSION.json dart-sdk/model/lexeme/idx2word.json dart-sdk/model/lexeme/word2idx.json dart-sdk/model/lexeme/model.tflite
```

There is currently a bug in the copy_tree.py file that prevents the permissions errors from appearing but I have a fix out for that.
https://dart-review.googlesource.com/c/sdk/+/111483

With that fix I see the following errors:

```
FAILED: dart-sdk/model/CIPD_VERSION.json dart-sdk/model/lexeme/idx2word.json dart-sdk/model/lexeme/word2idx.json dart-sdk/model/lexeme/model.tflite
python ../../tools/copy_tree.py --from /Users/nshahan/code/dart-sdk/sdk/pkg/analysis_server/language_model --to /Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model
Traceback (most recent call last):
  File "../../tools/copy_tree.py", line 156, in <module>
    sys.exit(Main(sys.argv))
  File "../../tools/copy_tree.py", line 148, in Main
    CopyTree(args.copy_from, args.to)
  File "../../tools/copy_tree.py", line 95, in CopyTree
    raise RuntimeError(errors)
RuntimeError: [('/Users/nshahan/code/dart-sdk/sdk/pkg/analysis_server/language_model/CIPD_VERSION.json', '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/CIPD_VERSION.json', "[Errno 13] Permission denied: '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/CIPD_VERSION.json'"), ('/Users/nshahan/code/dart-sdk/sdk/pkg/analysis_server/language_model/lexeme/idx2word.json', '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/idx2word.json', "[Errno 13] Permission denied: '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/idx2word.json'"), ('/Users/nshahan/code/dart-sdk/sdk/pkg/analysis_server/language_model/lexeme/word2idx.json', '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/word2idx.json', "[Errno 13] Permission denied: '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/word2idx.json'"), ('/Users/nshahan/code/dart-sdk/sdk/pkg/analysis_server/language_model/lexeme/model.tflite', '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/model.tflite', "[Errno 13] Permission denied: '/Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/model/lexeme/model.tflite'")]
[9/133] ACTION //utils/dartanalyzer:generate_summary_strong(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED
```

**Comment by lambdabaa** [comment]
I think this should be fixed by https://github.com/dart-lang/sdk/commit/1e16b74b5b0338603ce479efffc59e01ecd05630 but I will confirm.

**Comment by lambdabaa** [comment]
> I think this should be fixed by [1e16b74](https://github.com/dart-lang/sdk/commit/1e16b74b5b0338603ce479efffc59e01ecd05630) but I will confirm.

That patch fixed another issue but not this one. In this case CIPD is making files read-only that we're copying into `dart-sdk/`. When we try to copy a second time it complains. We probably need in `copy_tree.py` to set all of the files we're writing to `dart-sdk/` as writable when we copy over permissions.

```
ariaye@ariaye1:~/sdk/sdk$ ls -la pkg/analysis_server/language_model/
total 16
drwxr-xr-x  3 ariaye primarygroup 4096 Jul 31 12:39 .
drwxr-xr-x 10 ariaye primarygroup 4096 Jul 25 12:20 ..
-r--r--r--  1 ariaye primarygroup  108 Jul 31 12:39 CIPD_VERSION.json
drwxr-xr-x  2 ariaye primarygroup 4096 Jul 31 12:39 lexeme
```

**Comment by lambdabaa** [comment]
Reassigning to Alexander since he will know much better what the best remediation is for this.

**Comment by lambdabaa** [comment]
As a temporary workaround, you can delete your build output and do a full rebuild rather than incremental. Or probably just the `model/` directory.

**Comment by rakudrama** [comment]
I have to delete my out/ directory several times a day so I'm spending a lot of time waiting for builds.

**Comment by athomas** [comment]
@lambdabaa Please re-recreate the package but add this to the pkg-def:
preserve_writable: true

And then bump the deps.

**Comment by lambdabaa** [comment]
https://dart-review.googlesource.com/c/sdk/+/111983

**Comment by lambdabaa** [comment]
Fixed in 98ffe8a7c620c1bcab5ed4ce2f039b2be031c254

**Comment by athomas** [comment]
FYI: The fix has landed, but if the out or xcodebuild directories still contains a read-only language model those files will have to be deleted manually before the fix becomes effective.

**Comment by rakudrama** [comment]
Thanks!
