### ISSUE TITLE
Parsing calls following null-assertion operator

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#37708]
I'm starting to add dartfmt support for the new NNBD syntax. I tried out:

```dart
{
  obj!.method;
  obj!(arg);
  obj![arg];
}
```

As far as I know, the grammar permits all three of these. The `!` is just another kind of selector, which can be arbitrarily chained. As of analyzer 0.37.0, the parser accepts the first statement but reports errors on the other two:

```
line 3, column 4: Expected to find ';'.
  ╷
3 │ obj!(arg);
  │    ^
  ╵
line 4, column 4: Expected to find ';'.
  ╷
4 │ obj![arg];
  │    ^
```

Is this a parser bug? @leafpetersen @bwilkerson

**Comment by bwilkerson** [comment]
@danrubel

**Comment by leafpetersen** [comment]
Yes, I think this is a bug.

**Comment by munificent** [comment]
Yeah, 0.38.2 is the version that came out today and is the one I tried.

**Comment by munificent** [comment]
@danrubel, any idea when a new version of analyzer with this fix will be published?

**Comment by danrubel** [comment]
I leave that to @bwilkerson and @stereotype441

**Comment by munificent** [comment]
I'm trying 0.38.3, which handles more of these cases correctly, which is great. However, if I give it:

```dart
foo.bar![0];
```

I get:

```
line 1, column 5: Expected an identifier.
  ╷
1 │ foo.bar![0];
  │     ^^^
  ╵
```

**Comment by stereotype441** [comment]
@munificent I'm looking into whether a member of the CFE team can take this on.
