### ISSUE TITLE
"asynchronous function" -> "async function"

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#37701]
When you use `await` in a function that isn't marked `async`, you get the error "The await expression can only be used in an asynchronous function". Here's an example from DartPad2:

![image](https://user-images.githubusercontent.com/2164483/62249858-53962980-b3a0-11e9-9f03-ff42fe1a47cb.png)

Could you change "asynchronous function" to "async function"?

In the docs we've been distinguishing between **asynchronous functions** (any function that returns a future) and **async functions** (the subset of asynchronous functions that have `async` before the body). I'm not sure readers will necessarily get the difference (and I'm open to other options), but we should try to be consistent.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/111603
