### ISSUE TITLE
Merge-to-Stable request: Fix for performance regression in JIT

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37718]
To address https://github.com/dart-lang/sdk/issues/37551 we've landed a fix in 5f627b7a54e32b5157cbcbfa760209cab5851252 . We'd like to be included in the next patch release for the stable channel.

The regression triggers when working with `Int32List` from `dart:typed_data`, it can cause major slowdown of code.

**Comment by athomas** [comment]
Since this will be the sole issue in 2.4.1, shouldn't we put something in the CHANGELOG.md? Otherwise this release will look a bit weird.

I can cherry-pick a CHANGELOG.md entry in addition to this change.

**Comment by athomas** [comment]
Merged to stable in 04b7b090eb5dd714654faa80843c1feadc1ccede.
