### ISSUE TITLE
Dart Analizer error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by Bielteknik** [dart-lang/sdk#37711]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2`
- `IU-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2, server version , FATAL error: type '(dynamic) => void' is not a subtype of type '(String) => void' of '_printClosure@10040228'
#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:89:51)
```

For additional log information, please append the contents of
file://C:\Users\Bielteknik\AppData\Local\Temp\report.txt.

Dart analysis server, SDK version 2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2, server version , FATAL error: type '(dynamic) => void' is not a subtype of type '(String) => void' of '_printClosure@10040228'
#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:89:51)

```
1564669290457 started analysis server:
  C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IU-192.5728.98 --useAnalysisHighlight2
```

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5; please re-open if you see this in a recent version of Dart/Flutter.
