### ISSUE TITLE
Analyzer does not recognize extension methods referred to as bare words in classes

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37726]
My read of the spec is that the following should be legal:

```dart
extension Ext1 on A {
  void foo() {}
  void get b => 3;
}

class A {
  void test() {
    foo();
    b;
  }
}
```

The analyzer on current bleeding edge gives an error on the mention of `foo` in `A`, but not of `b`.  My read is that both should resolve to the extension members from `Ext1`, since they are both rewritten to be prefixed by `this.`, and then subject to extension method resolution.  

cc @lrhn @eernstg @munificent @bwilkerson @stereotype441 @johnniwinther

**Comment by leafpetersen** [comment]
This is tested in tests out for review here:  https://dart-review.googlesource.com/c/sdk/+/111882 .

**Comment by leafpetersen** [comment]
This also happens more comprehensively when both are referenced from inside another extension:

```dart
class A {
}
extension Ext1 on A {
  void foo() {}
  void get b => 3;
}

extension Ext2 on A {
  void test() {
    foo();
    b;
  }
}
```

Here both references are errors.  Also tested in the above referenced CL.

**Comment by bwilkerson** [comment]
That matches my understanding as well. It looks like a bug in analyzer to me (or a place where the implementation is incomplete, if there's a difference :-).

**Comment by eernstg** [comment]
I agree, given that no declaration with basename `b` or `foo` is in scope:
> both rewritten to be prefixed by `this.`, and then subject to extension method resolution.

**Comment by bwilkerson** [comment]
I believe that this should be fixed by https://dart-review.googlesource.com/c/sdk/+/112021
