### ISSUE TITLE
Uri.encodeUrl() doesn't fully encode url

### ISSUE THREAD

**Issue by bmcilw1** [dart-lang/sdk#37723]
Dart core library: Uri

Uri.encodeFull() doesn't seem to be properly encoding urls.

```js
  var url = Uri.encodeFull('https://www.test.com?test=one/two&anotherParam=123');
  print('encoded: '  + url);
```

Output:
```
encoded: https://www.test.com?test=one/two&anotherParam=123
```

For reference, see issue reported on Flutter project: https://github.com/flutter/flutter/issues/31530

Using dart through flutter on MacOS.

flutter --version
```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (2 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

**Comment by bmcilw1** [comment]
And another test:

```js
var url = Uri.encodeFull('https://www.test.com?test=one/two&anotherParam=12://3');
print('encoded: '  + url);
```

Output:
```
encoded: https://www.test.com?test=one/two&anotherParam=12://3
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by xx-li** [comment]
You can use Uri.encodeComponent  @bmcilw1

**Comment by lrhn** [comment]
`Uri.encode` is working correctly. The resulting URL is a valid URL, which is all the function promises:

> Encode the string `uri` using percent-encoding to make it safe for literal use as a full URI.

The documentation specifically states that it doesn't encode letters, digits or the characters `!#$&'()*+,-./:;=?@_~`.

As mentioned above, you might want to use `Uri.encodeComponent` which also encodes URI separators, depending on what result you actually want.

**Comment by xx-li** [comment]
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
There is no function `Uri.encode`,  `Uri.encodeFull` not work for me, `Uri.encodeComponent`  is working,  It encoded whole url。

@lrhn

**Comment by lrhn** [comment]
Right, it was `Uri.encodeFull` which was working correctly. Updated original.
