### ISSUE TITLE
Any common interface for collections length?

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#37731]
```dart
int doLength(dynamic value) {
  // try {
  //   return value.length; 
  // } catch (_) {
  //   return null;
  // }
  if (value is Iterable) return value.length;
  if (value is Map) return value.length;
  if (value is String) return value.length;  
  throw Exception();
}
```
Any interface like Comparable but for length?

**Comment by ykmnkmi** [comment]
and for this case:
```dart
bool contains(dynamic value, dynamic values) {
  if (values is Iterable) return values.contains(value);
  if (values is Map) return values.containsKey(value);
  if (values is String) return values.contains(value as Pattern);
  return false;
}
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
No plans to introduce a general `Lenghtable` interface, no.
The `length` means different things to different interfaces. A count of elements is not the same as a count of map entries or count of code units. The only thing that they have in common is that they are non-negative integers counting *something*, but that doesn't mean that it's generally useful to have a shared supertype.

I think the code here is very specialized (I've needed to know the length of something without knowing what the thing is), and not something we want to add support for in the platform libraries. It's unlikely to carry its own weight.
