### ISSUE TITLE
SuperConstructorInvocation with null arguments

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37735]
@MichaelRFairhurst used fuzz tester and found the following code that crashes Analyzer (in both summary1 and summary2).

```dart
class{const():super.{n
```

This causes the parser to produce `SuperConstructorInvocation` with null `argumentList`.
![image](https://user-images.githubusercontent.com/384794/62430358-b8b78b00-b6d0-11e9-9f94-460907097987.png)

**Comment by bwilkerson** [comment]
For this one it seems like we should ensure that the argument list isn't null, but otherwise leave things as they are.
