### ISSUE TITLE
Breakpoints not always hit on the second pass in execution

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#37747]
Directions provided by Paul (@stereotype441 )-- Found a repro, at least on my machine.  I've uploaded the state of my code to https://dart-review.googlesource.com/c/sdk/+/111671 and included repro instructions in the CL description.  You should be able to download the exact state of the code that I was using by clicking "download" and using the command line listed under "checkout".  Let me know if you have any trouble reproducing it.

See the directions in https://dart-review.googlesource.com/c/sdk/+/111671

I was able to reproduce the issue on the bleeding edge of the master branch of the dart-sdk (a locally built `2.5.0`), but not on `2.4.0`, downloaded from https://dart.dev/tools/sdk/archive

**Comment by stereotype441** [comment]
To provide some context on why we decided to mark this as P1: @bwilkerson, @scheglov, and I have all seen this problem consistently over the last few weeks over a variety of breakpoints, so we suspect it is likely to affect a nontrivial percentage of users.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/112147 is under review to fix this issue

**Comment by jwren** [comment]
@stereotype441 @bwilkerson @scheglov This has landed, please let us know if you hit the issue again.
