### ISSUE TITLE
Analyser wrongly reports local variable as unused

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/sdk#37746]
In Dart 2.4.0
MacOSX
Visual Studio Code and Jetbrains IDE's

Consider the code:

void doStuff() {
  var myValue = 1;
  myValue = 2;
} 

The dart wrongly reports:

The value of the local variable 'myValue' isn't used.
Try removing the variable, or using it.

**Comment by bwilkerson** [comment]
That's actually working as intended. The value of the variable isn't used. You could remove the content of `doStuff` without changing the semantics of the code.

What makes you think that the report is wrong?

**Comment by weenzeel** [comment]
Ah, ok … just expected the second assignment to be enough, but i suppose the variable needs to be used in some "useful" way.

Closing!
