### ISSUE TITLE
improve performance of sync* code on VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37753]
- [x] Do not use `Closure.clone` to create clones of the `:sync_body` closure - instead change kernel transformation to put `:sync_body` into another closure and call that closure to produce a copy of `:sync_body`. Prototype change improves performance in JIT mode by 3x. 
- [x] Disable argument type checks for `sync-yielding` functions because their arguments are guaranteed to match.
- [x] In `_SyncIterator` recognize `yield*` of a `_SyncIterable` and track the top of the iterator stack explicitly rather than delegating downwards which makes deep recursive `yield*` ineffecient. (Apparently dart2js does that which makes it more efficient than VM /cc @rakudrama ).

Related issue(PR) on Flutter side (https://github.com/flutter/flutter/pull/36303). /cc @jonahwilliams  

/fyi @mkustermann

**Comment by cskau-g** [comment]
@mraleph do you have a benchmark tracking what we're hoping to improve for the third point?

**Comment by cskau-g** [comment]
Thanks, @mraleph. I was able to find the benchmarks in the Golem repo.

Now, for the second point on the list, can you provide a bit more context? I take it you have a specific change in mind for that one?

**Comment by mraleph** [comment]
>  I take it you have a specific change in mind for that one?

The original issue gives the brief description of the suggested change: "  In _SyncIterator recognize yield* of a _SyncIterable and track the top of the iterator stack explicitly". 

Let me expain this with an example. Imagine you write the code like this:

```dart
foo() sync* {
  yield* bar();
}

bar() sync* {
  yield* baz();
}

baz() sync* {
  yield* someIterable;
}

for (var item in foo()) { ... }
```

While we are iterating `foo()` asking for each next element requires asking iterator of `bar()` for next element which would ask iterator of `baz()` for next element, which would finally delegate to iterator of `someIterable`. 

However if the outer iterator (one that is used to iterate `foo()`) has special handling for `yield* x` where `x is _SyncIterable` then it can maintain a stack of iterators inside and advance the top of the stack instead of delegating. 

This makes nested `yield*` much faster - in pathological case you might go from quadratic to linear algorithmic complexity.

**Comment by cskau-g** [comment]
My apologies - it gets a bit confusing to refer to the three point list. By 'the second point' I was referring to 'Disable argument type checks for sync-yielding functions'. The _SyncIterable change I think I've got a handle on, but thank you all the same for the detailed explanation.

For a bit more context on my part, I've been poking around the code and I see some potential candidate approaches, including: `LocalVariable::type_check_mode()`, `BytecodeGenerator::_parameterNeedsTypeCheck()`, and perhaps a couple of others.
But none of them stand out to me as the obvious right way to do it.
Is this what you had in mind?

**Comment by mraleph** [comment]
@cskau-g oops, I confused myself what the question was referring too, apologies. 

Yeah, those are the right place to look into. The disabling these type-checks should lead to slightly smaller binary size and potentially faster execution.

**Comment by kevmoo** [comment]
@cskau-g @mraleph – do we get a final report of the perf delta from this work?

CC @mit-mit – great to have a record of these things!

**Comment by kevmoo** [comment]
> @cskau-g @mraleph – do we get a final report of the perf delta from this work?
> 
> CC @mit-mit – great to have a record of these things!

I guess I see the notes in the associated commits.

So great to see this!

**Comment by cskau-g** [comment]
@kevmoo, sure. Just beware that benchmark numbers, at least from Golem, are a bit finicky.

Going by the 'detected performance changes' report:
- 85484 [VM] Optimise nested _SyncIterator to avoid deep recursion:
  - Iteration.concat.syncstar (dart): +27-33%
  - Iteration.concat.syncstar (dart-aot): +40%
  - Iteration.deeptree.syncstar (dart): +3100-3400%
  - Iteration.deeptree.syncstar (dart-aot): +3800%
- 85141 [VM] Reworked: Remove unnecessary Closure.clone() from sync*:
  - Iteration.concat.syncstar (dart): +150-230%
  - Iteration.concat.syncstar (dart-aot): +130%
  - Iteration.deeptree.syncstar (dart): +10%
  - Iteration.tree.syncstar (dart): +150-230%
  - Iteration.tree.syncstar (dart-aot): +120%

The last CL hasn't gotten a performance change report (yet?) but preliminary results were also much more moderate:
- [VM] Removes parameter type check for sync-yielding function:
  - Iteration.concat.syncstar: +5-10%
  - Iteration.tree.syncstar: +4-8%

Lastly, the affected benchmarks are hyper-specific to this change, so the numbers here are not indicative of real world performance changes.
I'd say 99% of users will see no noticeable difference - though it should make sync* patterns much more attractive going forwards. 🧲

**Comment by kevmoo** [comment]
Awesome to see! Well done!
