### ISSUE TITLE
Dart2js build to es6

### ISSUE THREAD

**Issue by sinegovsky-ivan** [dart-lang/sdk#37759]
Does dart2js support build to ES6?

Something like TypeScript's --target option

**Comment by natebosch** [comment]
cc @vsmenon

**Comment by vsmenon** [comment]
No, but ES5 is valid ES6.  Is there something specific you're looking for?

**Comment by sinegovsky-ivan** [comment]
> Is there something specific you're looking for?
smaller and faster bundle size, without any polyfills, etc.

Do you have plans to support specify build target to dart2js?

I had found this article - https://www.reddit.com/r/dartlang/comments/ae0nhx/google_groups_dart2js_will_support_es6_in_2019/. But not sure it is an official information.

Thank you!

**Comment by natebosch** [comment]
> Do you have plans to support specify build target to dart2js?

No, I don't think we plan on making this configurable. If and when we are able to drop support for IE and target only the more modern browser we will use ES6 features where it's sensible to reduce code size etc. When we do that it will be the new baseline, not a configuration.

Supporting multiple output targets from the same compiler is not a goal.

**Comment by vsmenon** [comment]
Right, we have no plan to make it configurable.  Once we drop IE support, we'll evaluate ES6 features supported on all our target browsers that improve performance / code size etc, and we'll drop IE specific polyfills.

(fyi @rakudrama )

**Comment by sinegovsky-ivan** [comment]
ok, thank you.

**Comment by 10686142** [comment]
> Right, we have no plan to make it configurable. Once we drop IE support, we'll evaluate ES6 features supported on all our target browsers that improve performance / code size etc, and we'll drop IE specific polyfills.
> 
> (fyi @rakudrama )

Any chances support for ES6 will be implemented in the near future? Since [Microsoft will no longer support IE](https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge), so I guess  this means you will also stop supporting IE, right?
