### ISSUE TITLE
Implement KBC + AOT hybrid mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37755]
I propose to cleanup and land [original prototype](https://dart-review.googlesource.com/c/sdk/+/56672) to have it in the tree. For now we would ignore "closed-world" violations introduced by dynamically loading interpreted code into the AOT runtime.

/cc @a-siva @alexmarkov @mkustermann

**Comment by zzjjob** [comment]
How is the progress ？

**Comment by chgibb** [comment]
Is the intent to allow for the dynamic loading of interpreted code into a running AOT app?

**Comment by a-siva** [comment]
@zzjjob could you elaborate a bit more about your requirements and how this hybrid mode proposal helps address the requirements.

**Comment by zzjjob** [comment]
For example, hot fix, I hope that if a function has a bug when AOT, it can be interpreted KBC, so that it can be quickly repaired when a serious bug or crash occurs.

**Comment by zzjjob** [comment]
@a-siva   MacOS  Allow Execution of JIT-compiled Code Entitlement, Perhaps it is possible to generate optimized code through  KBC when AOT runtime. just like AppJIT, i'am not sure.

**Comment by mraleph** [comment]
Currently we have no work planned on this, because so far we have not encountered a motivating use case ever since hot patch feature was explicitly abandoned by the Flutter team.

**Comment by chgibb** [comment]
@mraleph that's unfortunate to hear but makes sense given the discussion around the feature in the Flutter repo. @zzjjob this project was started with allowing for over the air updates/patches as a goal https://github.com/chgibb/hydro-sdk and might be of interest for the use case you defined above.

**Comment by zzjjob** [comment]
@chgibb  Thanks, I know this project and it's an interesting project.

@mraleph We know that the performance of AOT is not the best. AOT + KBC can reduce JIT compilation time and achieve better performance.

**Comment by alexmarkov** [comment]
Bytecode mode (KBC) is removed from Dart VM.

**Comment by taxueliuyun** [comment]
> @chgibb Thanks, I know this project and it's an interesting project.
> 
> @mraleph We know that the performance of AOT is not the best. AOT + KBC can reduce JIT compilation time and achieve better performance.

@zzjjob are you have new progress？
