### ISSUE TITLE
[vm/ffi] API: Pointer load and store as extension methods

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37773]
These methods would be better exposed as extension methods:

* `Pointer.load` (this issue)
* `Pointer.store` (this issue)
* `Pointer.asExternalTypedData` (but keep original) https://github.com/dart-lang/sdk/issues/38610
* `Struct.addressOf` https://github.com/dart-lang/sdk/issues/38611

update from @dcharkes: I split this issue into three to keep the CL sizes manageable.

**Comment by sjindel-google** [comment]
Putting this in Q3 stable since extension methods should be usable by then.

**Comment by dcharkes** [comment]
> * Pointer.asExternalTypedData (but keep original)

@sjindel-google, how did you envision this? Instance methods shadow extension methods.

**Comment by dcharkes** [comment]
I've made CLs for the [API change](https://dart-review.googlesource.com/c/sdk/+/118992) and updating the [tests, samples, and benchmarks](https://dart-review.googlesource.com/c/sdk/+/118993). Feel free to leave comments on those.

Note, we cannot land these CLs as long as the extension methods are behind a flag as experiment.

**Comment by dcharkes** [comment]
Do we want to keep `load` and `store` as `@deprecated` for a while? Or would we like to remove them right away? If we deprecate them, how long should we keep them? Till Dart 2.7?

Pro for deleting them: We do not have deprecated stuff in the ffi 1.0 release.
Pro for making them deprecated for a while: We don't break existing customers right away.

Maybe we should delete them right away. We have been upfront about API changes, and it will clean up the API and our internal implementation.

What is your opinion @sjindel-google @mkustermann?

**Comment by sjindel-google** [comment]
I vote for breaking them, but we should land all our breaking changes for 1.0 at once.

**Comment by dcharkes** [comment]
> we should land all our breaking changes for 1.0 at once.

:+1: Yeah, or we would break people on master and g3 multiple times.

**Comment by dcharkes** [comment]
> Note, we cannot land these CLs as long as the extension methods are behind a flag as experiment.

@johnniwinther has just turned on the flag by default. We are unblocked. :+1:
