### ISSUE TITLE
Land CFE modularity work to support pruned dependencies

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#37788]
This is a tracking issue to land the work @jensjoha prototyped internally here:

 cl/256943326, cl/256954541, cl/256964167 

properly into master.  Marking as D25 as we'll need this to switch internal to DDK, and we need to switch before extension methods ship.

fyi @jakemac53 @davidmorgan @mraleph

**Comment by dgrove** [comment]
any updates on this?

**Comment by jensjoha** [comment]
It's currently in the CQ and will land soon.

**Comment by jensjoha** [comment]
Landed in aeb864a43fad14b27d6ae78c530e9f048e3b038e (bazel) and e47f3549199ecd355017a2c60582c5755c1ebaf2 (ddc).
