### ISSUE TITLE
Max int literal const overflows when used from global scope using DDC, but not dart2js

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/sdk#37790]
Hi there! Going off this DDC build output:

```
[error] The integer literal '0x7FFFFFFFFFFFFFFF' can't be represented exactly in JavaScript. The nearest value that can be represented exactly is '0x8000000000000000'
```

This max int literal overflows in DDC, but not dart2js, when used as a globally scoped const:

```dart
const int globallyScopedBigInt = 0x8000000000000000;

void printBigInts() {
  const int locallyScopedBigInt = 0x8000000000000000;
  print('global scope: $globallyScopedBigInt');
  print('local scope: $locallyScopedBigInt');
}

void main() {
  printBigInts();
}
```

dart2js output:
```
global scope: 9223372036854776000
local scope: 9223372036854776000
```

DDC output:
```
global scope: -9223372036854776000
local scope: 9223372036854776000
```

**Comment by vsmenon** [comment]
Hi - if you're on the latest build_web_compilers, this should be fixed.  We recently migrated DDC to the same frontend as dart2js (but it's controlled by a switch in build_web_compilers).  You should see the dart2js output above on both now.

Closing as I think it's fixed.  Please reopen if you're seeing issues on the latest.
