### ISSUE TITLE
CFE does not initialize cross-module optional positional parameters with default values when subclassed.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37794]
Modular repro: https://dart-review.googlesource.com/c/sdk/+/112460

Ran with:
```dart pkg/dev_compiler/test/modular_suite.dart --configuration-name dartdevk-linux-release --verbose --filter test```

The expected output is `A('foo') A('foo')`, but we're observing `A('null') A('foo')`.

**Comment by mraleph** [comment]
I will take a look.
