### ISSUE TITLE
ML completion ranking needs a way to check for AvailableSuggestion existence

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37797]
ML ranking currently produces likely next lexemes and compares them to names of suggestions coming out of static analysis via the `List<CompletionSuggestion>`. However, nearly all of the suggestions are now held client-side in `AvailableSuggestionSet`. Model doesn't know whether to create a `CompletionSuggestion` or `IncludedSuggestionRelevanceTag` when something is missing from the classic completion list since it has no way of checking for the existence of an `IncludedSuggestionRelevanceTag`. Currently it is creating both `CompletionSuggestion` and `IncludedSuggestionRelevanceTag` but it should ideally choose one based on whether a corresponding `AvailableSuggestion` actually exists.

**Comment by lambdabaa** [comment]
@scheglov: The code path that needs this new ability to check whether a client-cached token with a given name will be included for this code completion is

[DartCompletionManager#computeSuggestions](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/completion_manager.dart#L79) which calls [CompletionRanking#rerank](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/completion_ranking.dart#L109) passing in the two lists of `CompletionSuggestion` and `IncludedSuggestionRelevanceTag`. Model looks in these two lists for a match on each name it wants to suggest and will currently create a new `CompletionSuggestion` object and `IncludedSuggestionRelevanceTag` if it doesn't find a match.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/122962
