### ISSUE TITLE
DDC doesn't work on MS Edge

### ISSUE THREAD

**Issue by dewsy** [dart-lang/sdk#37809]
Hy! I'm opening this issue based on this one: [dart-lang/site-webdev#1940](https://github.com/dart-lang/site-webdev/issues/1940)

* Dart SDK Version: 2.5.0-dev.0.0
* I'm using Windows, the issue is tested on two PC-s.
* I'm using Edge.

The issue is:
webdev serve fails on Microsoft Edge. It's stuck on the "Loading..." which sits between the <my-app> tags.

longer explanation:
I tried to run the official quickstart repository, and it ran flawlessly on Chrome and Firefox, however, it produced the above mentioned error on Edge. I tried it with multiple repos on multiple computers with freshly cleaned Edge browsers, the issue stayed consistently.  I even tried to change the versions on various dependencies, no luck there.

Adding the "--release" tag to the webdev serve command solved the issue, so in the previous issue we came to the conclusion, that it must be something DDC releated, since switching the compiler to dart2js instantly solved the issue, on the same codebase where DDC failed.

**Comment by vsmenon** [comment]
Note, we don't official support Edge in debug mode (we do in release).  Informally, Edge / debug appears to work in dev Edge releases (which are Chromium based).

**Comment by kwalrath** [comment]
@vsmenon I thought we wanted to support Edge in debug mode, so that DartPad with Flutter would run in more browsers. (I can't find a bug about that, though.)

**Comment by parlough** [comment]
Since the older Chakra-based Edge is no longer distributed or supported, I'm going to close this as stale.

If anyone has issues with the newer Chromium-based Edge, please open a new issue. Thanks!

Thanks again for the report :)
