### ISSUE TITLE
Compiling issue on Windows using Visual Studio for dbc mode

### ISSUE THREAD

**Issue by littlesome** [dart-lang/sdk#37807]
Got 2 errors when trying dbc mode on Windows:

* in runtime/vm/simulator_dbc.h 
  ```
  uword get_pc() const { return reinterpret_cast<uword>(pc_); }
  ```

  ```
  uword pc_;
  ```
  should remove `reinterpret_cast`
  `error C2440: 'reinterpret_cast' : cannot convert from 'uword' to 'uword' `

* in runtime/vm/simulator_dbc.cc
  `SignedAddWithOverflow` and `SignedSubWithOverflow` has no msvc  implementation

**Comment by a-siva** [comment]
We are in the process of deprecating dbc mode.

**Comment by mraleph** [comment]
@littlesome It will just use a normal ARM64 JIT mode (this is only possible in development).In fact this change has already happened on flutter master channel.

**Comment by littlesome** [comment]
@mraleph I think iOS does not allow JIT even in development mode,  or maybe I just missunderstand something?

**Comment by mraleph** [comment]
@littlesome that was our impression as well, but some additional research has recently revealed that you can actually make JIT work during development. as I mentioned the change has been already rolled into Flutter and so far we have not heard of any issues.

**Comment by littlesome** [comment]
@mraleph That's great! and thanks a lot ! 👍
