### ISSUE TITLE
Enable dart:html access on vm

### ISSUE THREAD

**Issue by jld3103** [dart-lang/sdk#37805]
I'm on Linux with dart 2.4.1 and with Flutter 1.8.5-pre.117 using dart 2.5.0-dev.1.0.

For flutter on web to work correctly (works but analyzer says it doesn't) access to ```dart:html``` has to be enable for vm. I also opened that issue in the flutter issue track, but nobody responded flutter/flutter#35588.
It also relates to #6424 but that issue has another context.

From the original issue:
To get it to work these lines should also be included in the vm section:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/libraries.yaml#L181
Is that possible or would that break anything?

**Comment by a-siva** [comment]
Not sure I understand the comment 'dart:html has to be enabled for vm' as you are using flutter on web which does not involve the VM. I presume you want to the analyzer to accept this without errors.

//cc @devoncarew for comments about analyzer accepting import of dart:html in flutter for web

**Comment by jld3103** [comment]
Yeay exactly.

**Comment by devoncarew** [comment]
Currently I think you'll need to have a separate main.dart for web work; the Dart VM will not understand the dart:html import.

You'd want something like this: https://github.com/csells/flutter_mplat_ttt#the-trick, but with two separate entry-point files, one for flutter for web, which could use the dart:html library, and one for flutter for mobile.

**Comment by devoncarew** [comment]
@jld3103, looking into this a bit more, I think the work for this would happen in the flutter/engine repo. I'm going to close this issue and add a comment to your original flutter/flutter issue.

**Comment by jld3103** [comment]
Currently flutter web gets unforked into the original repo and it's easily possible to import and work with dart:html.
