### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by freshcodestechnology** [dart-lang/sdk#37812]
#Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.5.0-edge.f29f41f1a54dfe50e4bff42533b72e6958e2d32e`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.f29f41f1a54dfe50e4bff42533b72e6958e2d32e, server version 1.27.2, FATAL error:
```

For additional log information, please append the contents of
file://C:\Users\Android\AppData\Local\Temp\report1.txt.

**Comment by a-siva** [comment]
@freshcodestechnology the crash report that you have appended to the issue appears to be truncated, we do not see the error message in full, could you provide a more detailed report which includes the error and the accompanying stack trace.
