### ISSUE TITLE
Allow const constructor with mixins that have getter-only fields

### ISSUE THREAD

**Issue by cpboyd** [dart-lang/sdk#37810]
Originally posted at https://github.com/google/built_value.dart/issues/694

I'm getting `const_constructor_with_mixin_with_field` when using this mixin:
```dart
mixin RouteEnum on EnumClass {
  String get title;

  String get subtitle;

  IconData get icon;

  Color get color;
}
```

I have other code in the mixin that depends on those fields, which are defined in the subclass.

Since I'm not actually defining any fields in the mixin itself, it seems like this error shouldn't necessarily happen.

Shouldn't getter-only fields be treated similarly to functions?

Edit: Forgot to add my use case for this...
I'm using Flutter with a `BottomNavigationBar` and separate navigation within each tab.

As a result, I'd like to keep all of this related information with the `EnumClass` because it makes more sense structurally to me than to have functions within the various Widgets.

**Comment by Skyost** [comment]
Any news on this one ?

**Comment by pqsky7** [comment]
any update for this issue?

**Comment by nyarian** [comment]
Any news?

**Comment by mhmdanas** [comment]
@nyarian this issue was fixed in https://github.com/dart-lang/sdk/commit/56dbe294f234d0b755f58899623f78839f5d0ff1.

**Comment by Peng-Qian** [comment]
Hi all,
when it available in Flutter?

**Comment by zs-dima** [comment]
Any news about?
