### ISSUE TITLE
Stack traces not showing up for the test package with ddk in 2.5.0-dev.2.0

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#37822]
To repro you need to run a failing test with build_runer and ddk, you will get no output in the console other than telling you what test failed.

It is hitting some sort of internal error in the stack_trace package when trying to fold the traces.

Reproduction instructions:

1. Clone the [build](git@github.com:dart-lang/build.git) repo.
2. Checkout the [fix-failing-tests](https://github.com/dart-lang/build/tree/fix-failing-tests) branch of the build repo (this will enable local debugging of the test which makes it easier).
3. Run `pub run build_runner serve test` and load  `http://localhost:8080/hello_world_test.debug.html` in your browser.
4. Click the button on the page to run the tests.

I would recommend setting it to pause on all exceptions, and then hitting continue until you get inside this function:
```
dart.gbind = function gbind(f, ...typeArgs) {
    let type = f[dart._runtimeType];
    type.checkBounds(typeArgs);
    let result = (...args) => f.apply(null, typeArgs.concat(args));
    return dart.fn(result, type.instantiate(typeArgs));
  };
```

In here `type` ends up being undefined and `f` is a raw function with no dart information attached which seems to be the problem.

**Comment by vsmenon** [comment]
@jakemac53 - is this a regression within ddk or from ddc?  Do you know if this affects internal as well?  (I.e., thinking of whether to mark as D25)

**Comment by jakemac53** [comment]
I haven't tests in DDC or internal. I can try internal since that covers both but I don't know if we have updated to the version that would have these issues.

**Comment by Markzipan** [comment]
I have a repro of the issue locally - it's a DDK problem for sure. Looking into it.

**Comment by jakemac53** [comment]
I also confirmed that it is still working with ddc/internal

**Comment by jakemac53** [comment]
Confirmed this is fixed now
