### ISSUE TITLE
Output divergence: KBC-MIX-SRC-noVFP-ReleaseSIMARM

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#37821]
Isolate (/b/s/w/itm3ksy5/dart_fuzzITXQTF) FP : KBC-MIX-SRC-noVFP-ReleaseSIMARM - KBC-CMP-DebugIA32: !DIVERGENCE! 1.16:3582329983 (output)

I can reproduce this locally. Most configurations see the output:

> {25: xH0IE#}
> false
> tA
> true
> 31
> 0.44794902547497595
> Y
> [34]
> {16, -97}
> {46: Hg♥♥n5W}

However,  KBC-MIX-SRC-noVFP-ReleaseSIMARM has a 0.0 instead:

> {25: xH0IE#}
> false
> tA
> true
> 31
> 0.0                       <---- here
> Y
> [34]
> {16, -97}
> {46: Hg♥♥n5W}
>

**Comment by aartbik** [comment]
@bkonyi do you feel like boosting your compiler triaging skills with this one?

**Comment by bkonyi** [comment]
@aartbik what was the seed that generated the program with this result?

**Comment by aartbik** [comment]
Ah, that was 3582329983, version 1.16. I have a write up on go/dartfuzz on how to read the output and how to reproduce, but in a nutshell, use

`dart dartfuzz.dart --seed=3582329983 --fp fuzz.dart `

to reproduce this case (make sure to get version 1.16 though, we are at 1.18 now if you have git pulled recently).

**Comment by bkonyi** [comment]
I'm not sure I have the resources to dig into this deeper at the moment so I think I'm going to pass this on with a simple reproduction case. It seems that playing with the compilation and optimization counter thresholds makes this behavior reproduce more consistently.

```dart
import 'dart:async';
import 'dart:cli';
import 'dart:collection';
import 'dart:convert';
import 'dart:core';
import 'dart:io';
import 'dart:isolate';
import 'dart:math';
import 'dart:typed_data';

double var5 = 0.5521203015696288;

class X0  {
  double fld0_1 = 0.44794902547497595;
  void run() {
    // Seems to work for loc1 < 10
    for (int loc1 = 0; loc1 < 11; loc1++) {
        var5 = fld0_1;
    }
    // this operation is modifying the value stored in var5
    fld0_1 -= 20;
  }
}

class X1 extends X0 {
  void run() {
    super.run();
  }
}

main() {
  new X0().run();
  print(var5);
}
```
cc/ @aartbik @alexmarkov

**Comment by aartbik** [comment]
To reproduce:

`dart --deterministic --no-use-vfp --enable-interpreter fuzz.dart`

**Comment by alexmarkov** [comment]
Interpreter only looks at `UnboxingCandidateBit` in `kind_bits_`, `is_nullable_` and `guarded_cid_` to decide if a field is unboxed:
https://github.com/dart-lang/sdk/blob/524f78e6cb1d317c3f97064324a29fdf730fa73b/runtime/vm/interpreter.cc#L3078-L3082

However, compiler also takes VFP into account:

https://github.com/dart-lang/sdk/blob/524f78e6cb1d317c3f97064324a29fdf730fa73b/runtime/vm/compiler/backend/flow_graph_compiler.cc#L175-L181

https://github.com/dart-lang/sdk/blob/524f78e6cb1d317c3f97064324a29fdf730fa73b/runtime/vm/compiler/backend/flow_graph_compiler_arm.cc#L67-L69

In this particular case interpreter was loading and storing `X0.fld0_1` as an unboxed field (so there is a Double box dedicated for the field), but when getter executed 10 times it was compiled and compiled code returned a field's value without allocating a new box. That effectively copied private box of `X0.fld0_1` into `var5`. The subsequent modification of `X0.fld0_1` had a side-effect of modifying value in `var5`.

We should align how compiler and interpreter decide on unboxing fields. For example, we could avoid setting `UnboxingCandidateBit` if VFP is disabled.
