### ISSUE TITLE
[Phase 2 - Tools] DDC support for Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37845]
If this feature can be implemented entirely in the front end with no Kernel changes, and DDC is entirely onto the CFE, then no DDC changes may be needed. Otherwise, DDC may need to handle any Kernel changes or otherwise add support for this.

Otherwise, if DDC still relies on the Analyzer, it depends on the Analyzer changes.

**Comment by vsmenon** [comment]
@sigmundch @Markzipan - can we close this now?  I don't think there is anything left.
