### ISSUE TITLE
[Phase 2 - Tools] Analysis Server support for Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37849]
Update to use the latest analyzer with support for the feature. There are a handful of usability features that would be nice.
- Completion should suggest applicable extension methods.
- Conflicting extension methods should be reported in a useful way.

It would be excellent to have quick-fixes for:
- Completing with and importing a known extension which is not imported in the current library
- Insert an explicit extension type override in case of conflicting extensions, or for available extensions which were not as specific as the one chosen by the language.

**Comment by stereotype441** [comment]
As of d8c5daf17ac336c843b2c4226028dc3fa26d4295 the feature is enabled and we're not aware of any remaining analyzer work that needs to be done, so I'm closing this.
