### ISSUE TITLE
[Phase 2 - Tools] dartfmt support for Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37844]
Define and implement formatting rules for the new syntax. Add formatting tests. The new syntax is very similar to class syntax, so the formatting rules will likely be similar too.

**Comment by leafpetersen** [comment]
This is also tracked in the dart_style repo [here](https://github.com/dart-lang/sdk/issues/37844)

**Comment by aadilmaan** [comment]
@leafpetersen - I think you copied the wrong link. It keeps bringing me back to this same bug.

**Comment by leafpetersen** [comment]
Right, how about [here](https://github.com/dart-lang/dart_style/issues/830)!

**Comment by aadilmaan** [comment]
Ah got it. Then I will mark this a dupe of https://github.com/dart-lang/dart_style/issues/830.
