### ISSUE TITLE
[Phase 2 - Tools] Update VS Code to support Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37851]
Update the syntax highlighting grammar to support the new syntax (and, likely apply a very similar diff to the Atom grammar above).

**Comment by DanTup** [comment]
@aadilmaan I don't see a link to the Atom grammar change - do you have it? Or do you have some info on what the changes are (for ex. sample code and what needs tweaking). Thanks!

**Comment by DanTup** [comment]
Oh, I see the text was copied from [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/implementation-plan.md#vs-code) so probably Atom is not done yet.

I guess the change is just to handle `extension` and `on`?

**Comment by bwilkerson** [comment]
The proposal, including the grammar changes, is here: https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md.

**Comment by DanTup** [comment]
Thanks - looks like it only needed `extension` adding (we already have `on`).
