### ISSUE TITLE
[dartdevc] DDK doesn't properly generate private constructor field initializers.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37855]
```
class _A implements B {
  @override
  final List<String> field1;

  @override
  final List field2;

  _A(this.field1, this.field2);

  @override
  void noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

abstract class B<E> extends C<E> {
  B();
}

abstract class C<E> {
  List<E> _field1;
  List _field2;
  List get field2 => _field2;
  set field2(List value) => _field2 = value;
}

main() {
  var x = _A(["a"], ["b"]);
}
```

DDK errors with:
```
Error: NoSuchMethodError: 'field2='
method not found
Receiver: Instance of '_A'
Arguments: [Instance of 'List<dynamic>']
... at _A.new.set field2 [as field2]
```
DDK generates A's constructor as:
```
(test._A.new = function(field1, field2) {
  this.field1 = field1;
  this.field2 = field2;
  ;
}).prototype = test._A.prototype;
```
But DDC correctly generates:
```
(test._A.new = function(field1, field2) {
  this.field1 = field1;
  this[field2$] = field2;
  ;
}).prototype = test._A.prototype;
```

**Comment by Markzipan** [comment]
It seems that DDK's virtualFields aren't being set properly. Setting line 245 of kernel/property_model.dart to true trivially fixes the issue. Maybe mock members aren't being tracked properly, but mock members were purposefully removed in https://github.com/dart-lang/sdk/commit/21fbf7d7677291e1e9b7120de4b2a714cd77b09d#diff-12a190bd8331cb2743a596a8881481ee.

**Comment by nshahan** [comment]
Just to clarify, but I might be reading this wrong. Is the `field1` of class _A intended to override the private `_field1` in class C? Should it actually be private in this example?

**Comment by Markzipan** [comment]
Hmm, I think field1 might just be a red herring here. The error's on field2 due to the superclass's getter. Not entirely sure why I added field1 (maybe lazy copying?).

**Comment by Markzipan** [comment]
@vsmenon Based on what Aske's saying, this might actually be the same issue as https://github.com/dart-lang/sdk/issues/37839. If that field isn't present in `_classProperties.virtualFields`, we wouldn't wrap it in that symbol object.

**Comment by vsmenon** [comment]
https://dart-review.googlesource.com/c/sdk/+/113124
