### ISSUE TITLE
[Phase 2 - Tools] Update Atom plug-in to support Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37850]
The Dart Atom plug-in has a grammar for syntax highlighting Dart code in Atom. This same grammar is also used for syntax highlighting on GitHub. Update this to handle the new syntax.

**Comment by alexander-doroshko** [comment]
@a-siva @devoncarew Probably `area-intellij` is not relevant here?

**Comment by a-siva** [comment]
Agree, we don't seem to have any Atom specific label or a generic plugin label. Removed the area-intellij label, please feel free to assign it to some other area label.
