### ISSUE TITLE
Wrong errors for null-aware cascade in class_member_declarations_test

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#37859]
In the test `language_2/nnbd/syntax/class_member_declarations_test.dart`, case none, errors are raised for the null-aware cascade token `?..` as used in `a?..foo().length..x27`:

```
ERROR|SYNTACTIC_ERROR|MISSING_IDENTIFIER|/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_tests/language_2/nnbd/syntax/class_member_declarations_test_none.dart|79|6|1|Expected an identifier.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_tests/language_2/nnbd/syntax/class_member_declarations_test_none.dart|79|6|0|The getter '' isn't defined for the class 'A?'.
```

With NNBD, this should be allowed (cf. [this grammar rule](https://github.com/dart-lang/language/blob/e163637d1537ccc9ccde1d25ca87b82286aa634d/specification/dartLangSpec.tex#L9591)).

**Comment by scheglov** [comment]
@danrubel Is this a known issue?

**Comment by danrubel** [comment]
@bwilkerson How should this be represented in the AST?

**Comment by bwilkerson** [comment]
I would assume that it should be represented exactly like the expression `a..foo().length..x27`, except that the first cascade operator is `?..` rather than `..`. So, I entered the following text into a file and opened the status page to look at the structure.
```
class A {}
f(A a) {
  print(a..foo().length..x27);
}
```
It's a little hard to read because most of the field names seem to have been removed, but it looks like this:
```
CascadeExpressionImpl [1457..1476]
┊        static type = A
┊   SimpleIdentifierImpl [1457..1457]
┊        name = a
┊        static element = A a
┊        static type = A
┊   PropertyAccessImpl [1458..1471]
┊  ┊        static type = dynamic
┊  ┊   MethodInvocationImpl [1458..1464]
┊  ┊   ┊        static invoke type = dynamic
┊  ┊   ┊        static type = dynamic
┊  ┊   ┊   SimpleIdentifierImpl [1460..1462]
┊  ┊   ┊   ┊        name = foo
┊  ┊   ┊   ┊        static type = dynamic
┊  ┊   ┊   ArgumentListImpl [1463..1464]
┊  ┊   SimpleIdentifierImpl [1466..1471]
┊  ┊   ┊        name = length
┊  ┊   ┊        static type = dynamic
┊   PropertyAccessImpl [1472..1476]
┊  ┊        static type = dynamic
┊  ┊   SimpleIdentifierImpl [1474..1476]
┊  ┊   ┊        name = x27
┊  ┊   ┊        static type = dynamic
```
(ignore the offsets, I had commented out code before it in the file).

**Comment by danrubel** [comment]
That's what I was thinking as well. I can take care of adding a new ?.. cascade token. Would you handle the change to the AST cascade node?
