### ISSUE TITLE
Wrong error for `late var` in this_reference_in_late_field_test, class_member_declarations_test

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#37857]
In the test `language_2/nnbd/static_errors/this_reference_in_late_field_test.dart`, case 01 has a variable declared `late var x = this;`. With NNBD this is not an error (cf. [this grammar rule](https://github.com/dart-lang/language/blob/e163637d1537ccc9ccde1d25ca87b82286aa634d/specification/dartLangSpec.tex#L1878) and [this issue comment](https://github.com/dart-lang/language/issues/321#issuecomment-497070013)), but the analyzer reports the following error:

```
ERROR|SYNTACTIC_ERROR|CONFLICTING_MODIFIERS|/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_tests/language_2/nnbd/static_errors/this_reference_in_late_field_test_01.dart|14|8|3|Members can't be declared to be both 'var' and 'late'.
```

The same issue exists for declarations starting with `late var` in `language_2/nnbd/syntax/class_member_declarations_test.dart`.

**Comment by scheglov** [comment]
@danrubel Is this a known issue?
