### ISSUE TITLE
[Phase 2 - Tools] Update co19 tests to support Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37852]
The co19 team can start implementing tests early using the experimental flag. Those tests should not be run by default until the feature has been released.

**Comment by leafpetersen** [comment]
These have landed, so this is close to done.  cc @eernstg @athomas

**Comment by eernstg** [comment]
There may be more tests coming. I asked for comments from the co19 folks.

**Comment by eernstg** [comment]
Closing: The set of static extension method tests in co19 has been completed as planned.
