### ISSUE TITLE
Please merge 28e857bbf5ba54a10fdab3aeec1917d153495e3d into dev channel

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37869]
**commit(s) to merge**: 28e857bbf5ba54a10fdab3aeec1917d153495e3d

**merge instructions**: clean merge or patch CL

**reason**: Typing quickly causes the single ML completion worker to fall behind leading to ranking timeouts. A couple of beta testers of Dart ML code completion were confused by completion results intermittently not reranking by probability. This patch fixes the issue and makes it so that we leverage a small pool of isolates to load balance over. Uplifting this change will allow users to beta test ML code completion effectively on this week's dev release.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Done: 533f94951d90274e6f0fbe76183782cef37b1181
