### ISSUE TITLE
Analyzer: no error for using assertions in redirecting generative constructors

### ISSUE THREAD

**Issue by LongCatIsLooong** [dart-lang/sdk#37867]
On dartPad or with my local SDK, the following code snippet does not trigger an analyzer warning/error, but fails to compile:
```dart
void main() {
  print(A.half(4));
}

class A {
  final int x;
  A(this.x);
  A.half(int x):
    assert(x % 2 == 0),
    this(x ~/ 2);
}
```
`dart --version`:
> Dart VM version: 2.5.0-dev.1.0.flutter-0ca1582afd (Thu Jul 25 23:50:46 2019 +0000) on "linux_x64"

**Comment by srawlins** [comment]
For reference, dart2js produces the following error while compiling the code above:

> Error: Can't have other initializers together with 'this'.
> main.dart:8:3:
> Error: Final field 'x' is not initialized by this constructor.
>   A.half(int x):
>   ^^^^
