### ISSUE TITLE
type 'Utf8Decoder' is not a subtype of type 'StreamTransformer<Uint8List, String>'

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#37866]
Dart Sass's [tests running against Dart dev](https://travis-ci.org/sass/dart-sass/jobs/571990418) are currently breaking because of this issue. The proximate cause seems to be something in the `test` package, but it looks like the underlying issue is with the core library or the type checker.

This is high severity for us; it's blocking all Dart Sass pull requests and releases. Accordingly, I'm marking it as P1.

**Comment by lrhn** [comment]
@tvolkert Is this related to the breaking change?

**Comment by tvolkert** [comment]
Is this a dup of https://github.com/dart-lang/test/issues/1059 (closed by https://github.com/dart-lang/test/pull/1060)?

**Comment by nex3** [comment]
What changed? There wasn't any kind of breaking change announcement on any mailing list I follow.

**Comment by tvolkert** [comment]
Do you follow announce@dartlang.org?

https://groups.google.com/a/dartlang.org/forum/#!topic/announce/wcy9wW8Lk9A

**Comment by nex3** [comment]
Ah, my mistake, I must have missed that.

**Comment by a-siva** [comment]
Closing 'working as intended' per comments above.
