### ISSUE TITLE
Output divergence: KBC-CMP-SRC-noVFP-ReleaseSIMARM - KBC-MIX-ReleaseX64

### ISSUE THREAD

**Issue by feli-citas** [dart-lang/sdk#37868]
Clamping produces inconsistent results between 64 and 32bit versions, e.g.:
```
import 'dart:core';
import 'dart:io';
import 'dart:typed_data';

Uint8ClampedList var0 = Uint8ClampedList.fromList([ 9223372032559808513, -71, 20 ]);
main() {
   print(' $var0');                                                                                                                 
}
```
produces
```
< [255, 0, 20]
```
on KBC-MIX-ReleaseX64 and
```
> [1, 0, 20]
```
on KBC-CMP-SRC-noVFP-ReleaseSIMARM.

**Comment by aartbik** [comment]
Note that 9223372032559808513 in hex is 

`0x7fffffff00000001`

so it looks like we are simply dropping the upper 32-bits somewhere. Clamping 9223372032559808513 in Dart2 should yield 255 as far as I know.

**Comment by aartbik** [comment]
I traced this through our library.
```dart
  factory Uint8ClampedList.fromList(List<int> elements)
```
calls (see https://dart-review.googlesource.com/c/sdk/+/106909)
```dart
mixin _TypedIntListMixin<SpawnedType extends List<int>> on _IntListMixin
    implements List<int> {

  void setRange(int start, int end, Iterable<int> from, [int skipCount = 0]) {
      ....
      Lists.copy(otherList, otherStart, this, start, count);
  }
```
which is
```dart
static void copy(List src, int srcStart, List dst, int dstStart, int count) {
     ....
     for (int i = srcStart, j = dstStart; i < srcStart + count; i++, j++) {
        dst[j] = src[i];
      }
}
```
which should call the clamped []= operator

```
    t2 <- InstanceCall:106( []<0>, t2, t3)
    PushArgument(t2)
    InstanceCall:108( []=<0>, t0, t1, t2)

```
except it doesn't.

**Comment by aartbik** [comment]
The graph intrinsifier seems to be the culprit. No clamping occurs, but it should!

```dart
==== dart:typed_data__Uint8ClampedList@6027147_[]=
B0[graph]:64 {
      v9 <- Constant(#null)
}
B1[function entry]:66 {
      v0 <- Parameter(0)
      v1 <- Parameter(1)
      v2 <- Parameter(2)
}
    v3 <- LoadField(v0 . TypedDataBase.length {final})
    v5 <- CheckArrayBound(v3, v1)
    v7 <- UnboxInt32([tr], v2)
    StoreIndexed(v0, v5, v7)
    Return:68(v9)

```

**Comment by aartbik** [comment]
@mkustermann @mraleph 

https://dart-review.googlesource.com/c/sdk/+/92740

**Comment by mraleph** [comment]
The clamping is supposed to happen inside `StoreIndexed` so you would not be able to see it from the IR. 

It seems that on both IA32 and X64 `StoreIndexed` is broken for clamped arrays - while ARM and ARM64 are correct and does clamping. I am puzzled how such situation did arise.

**Comment by mkustermann** [comment]
To me it seems like this works on x64/arm64 but not on ia32/arm.

The code we generate on 32-bit seems to have, since it's beginning in [cl/14812005](https://codereview.chromium.org/14812005/diff/12001/runtime/vm/intermediate_language_arm.cc#skiplinks-1113) only supported Smis as values (which are 31-bit).

The actual graph we generate on 32-bit platforms is the following, which does have a `CheckSmi` instruction on the value:
```
*** BEGIN CFG
After FinalizeGraph
==== file:///usr/local/google/home/kustermann/repositories/sdk-gclient4/sdk/clamp.dart_::_foo
B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>) T{_OneByteString}
      v4 <- Constant(#0) [0, 0] T{_Smi}
      v5 <- Constant(#9223372032559808513) [9223372032559808513, 9223372032559808513] T{_Mint}
      v17 <- Constant(#Field <::.var0>: static) T{Field}
}
B1[function entry]:2
  0:     v15 <- LoadStaticField(v17) T{Uint8ClampedList?}
    CheckClass:14(v15 T{Uint8ClampedList?} Cids[1: _Uint8ClampedList@6027147 etc.  cid 103])
  1:     v6 <- LoadField(v15 T{_Uint8ClampedList} . TypedDataBase.length {final}) [0, 1073741823] T{_Smi}
    CheckArrayBound:14(v6, v4) [-1073741824, 1073741823] T{_Smi}
    CheckSmi:14(v5)
    v10 <- UnboxInt32:14([tr], v5 T{_Smi}) [9223372032559808513, 9223372032559808513] T{int}
  2:     StoreIndexed:14(v15 T{_Uint8ClampedList}, v4, v10)
    Return:18(v0)
*** END CFG
```

After 119f9374185 we insert the truncating `UnboxInt32` (which was done before inside the `StoreInstanceField::EmitNativeCode` via  SmiUntag).

The bug seems to be in the [graph intensifier](https://dart-review.googlesource.com/c/sdk/+/99149/10/runtime/vm/compiler/graph_intrinsifier.cc#b256) where we no longer insert the `CheckSmi` instruction.

**Comment by mkustermann** [comment]
```diff
diff --git a/runtime/vm/compiler/graph_intrinsifier.cc b/runtime/vm/compiler/graph_intrinsifier.cc
index db4e7dc727..73a5d27b79 100644
--- a/runtime/vm/compiler/graph_intrinsifier.cc
+++ b/runtime/vm/compiler/graph_intrinsifier.cc
@@ -285,6 +285,8 @@ static bool IntrinsifyArraySetIndexed(FlowGraph* flow_graph,
     case kTypedDataUint16ArrayCid:
     case kExternalTypedDataUint8ArrayCid:
     case kExternalTypedDataUint8ClampedArrayCid:
+      builder.AddInstruction(new CheckSmiInstr(
+                                       new Value(value), DeoptId::kNone, builder.TokenPos()));
       value = builder.AddUnboxInstr(kUnboxedIntPtr, new Value(value),
                                     /* is_checked = */ false);
       value->AsUnboxInteger()->mark_truncating();
```

**Comment by mraleph** [comment]
@mkustermann note that we are talking about clamping here (that is turning out of range values into 0 or FF depending whether they are negative or positive). `CheckSmi` would not really fix the underlying logic which is simply missing on intel and present on ARM.

**Comment by mraleph** [comment]
I was looking at the wrong code - of course clamping is there on all architectures. It's just (as @mkustermann points out) uses truncated value which is incorrect.

**Comment by aartbik** [comment]
Yes, perhaps I was a bit unclear, but 64-bit works (all archs) but 32-bit does not (all archs), due to the 32-bit truncation prior to any clamping in the intrinsifier. It works on all archs without intrinsifier.

I will apply Martin's patch and send out a CL with regression test.

**Comment by aartbik** [comment]
And, feel the power of value-guided fuzzing!!!! The table of "interesting" integers made exposing this bug on the new types possible :-)
