### ISSUE TITLE
Object with noSuchMethod method should be allowed to be used as a Callable.

### ISSUE THREAD

**Issue by pinyin** [dart-lang/sdk#37884]
Possible related to #6130.

**Example**

https://dartpad.dartlang.org/8494d39be3c472351640c1fbb2fa618b

```
void main() {
  final func = Callable((obj)=> print(obj));
  func('a');
}

class Callable implements Function {
  Function func;
  
  @override
  noSuchMethod(invocation) {
    Function.apply(func, invocation.positionalArguments, invocation.namedArguments);
  }
  
  Callable(this.func);
}
```

**Expected Behavior**

Prints a.

**Current Behavior**

Compilation terminates with an exception:
```
main.dart:3:7:
Error: The method 'call' isn't defined for the class 'Callable'.
 - 'Callable' is from 'main.dart'.
  func('a');
      ^
Error: Compilation failed.
```

**Comment by lrhn** [comment]
Addin a `noSuchMethod` implementation does not allow you to call members on the type which are not declared.
If you do:
```dart
class Foo {
  noSuchMethod(invocation) { print(invocation.memberName); }
}
main() {
  Foo().bar();
}
```
it is also a compile-time error. The only place you can call a method which isn't part of the interface of the class is thorough dynamic invocation:
```dart
main() {
  (Foo() as dynamic).bar();  // prints the #bar symbol.
}
```

Also, adding `implements Function` does nothing. You cannot implement the `Function` type in Dart 2 (we allow the syntax for backwards compatibility, but it does nothing).

In this case, it will work if you do:
```dart
final dynamic func = Callabel((obj) => print(obj));
func('a'); // prints 'a'
```

If you want `Callable` to be callable in a *typed* setting, you need to give it an actual, typed `call` method.
