### ISSUE TITLE
Some small dartdoc issues in the SDK

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#37880]
**Dart SDK Version:** 7551b9cee30f4cd7c198977f0019292ff7543ddb

I created a CL with my best take on the fixes here - https://dart-review.googlesource.com/c/sdk/+/103741

- [Stream#drain doc](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream.dart#L1099) missing new paragraph line and references a function it doesn't call.
- Unresolved doc references in [base64.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/convert/base64.dart#L38) due to not being able to link to methods from variables.
- Similar unresolved references in [json.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/convert/json.dart#L77) due to not being able to link to methods from variables.
- The doc references [value] instead of [object] inside [jsonEncode](https://github.com/dart-lang/sdk/blob/master/sdk/lib/convert/json.dart#L79)
- Map identity factory doc [links to == operator](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/map.dart#L86) wrong.
- [RegExp#isDotAll](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/regexp.dart#L155) doc uses wrong capitalization on [isMultiLine] breaking link.
- Various improper linking in [RawSocketOption](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/socket.dart#L428)
- In `Stdin` [terminal is spelt wrong](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/stdio.dart#L42), breaking the linking
- `js_dart2js.dart` [attempts to link to an apply method](https://github.com/dart-lang/sdk/blob/master/sdk/lib/js/dart2js/js_dart2js.dart#L57) without the class type where it resides.
- `Random`'s class dartdoc [improperly links](https://github.com/dart-lang/sdk/blob/master/sdk/lib/math/random.dart#L12) to the `Random.secure` constructor

**Comment by srawlins** [comment]
Thanks much!

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/bb879969dd17f65c1694ff722f6b5c67275ed11e
