### ISSUE TITLE
[Phase 2 - Tools] Validate that the angular compiler works with extensions methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37890]
This issue tracks making any required changes in the angular compiler to support extension methods.  @matanlurey are you the point person this?

**Comment by srawlins** [comment]
CC @leonsenft

**Comment by vsmenon** [comment]
@matanlurey - anything to do here?  Is there any blocker for D26 (next week)?

**Comment by vsmenon** [comment]
@matanlurey - I don't there is anything blocking here any more.

I heard there are some limits to using extension methods in templates (.html files), but it appears to work for me.

**Comment by matanlurey** [comment]
Sorry. I only check Dart GitHub about once every 2 weeks or so, so if have anything you need my opinion on an email or ping is probably better suited. I think we can close this.

@vsmenon: You're able to use extension methods in template files?
