### ISSUE TITLE
[Phase 2 - Tools] Support extension methods in web debugging tools.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37892]
This tracks any required work in web debuggers for supporting extension methods.

**Comment by leafpetersen** [comment]
Is there package:test work that needs to happen here as well?

**Comment by leafpetersen** [comment]
Filed [an issue](https://github.com/dart-lang/test/issues/1063) on package:test.

**Comment by jakemac53** [comment]
package:build_web_compilers also does stack trace mapping so it might need to do something as well?

**Comment by leafpetersen** [comment]
Filed [an issue](https://github.com/dart-lang/build/issues/2417) for build_web_compilers.

**Comment by vsmenon** [comment]
@Markzipan @sigmundch - can we close this as well?
