### ISSUE TITLE
[Phase 3 - Release] Support extension methods in dartpad/codemirror.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37893]
This tracks any required work to validate support for extension methods in the dartpad editor, and to update the dartpad backend to support extension methods.

@filiph do you know who owns this?

**Comment by filiph** [comment]
I'm guessing @RedBrogdon and/or @domesticmouse.

**Comment by RedBrogdon** [comment]
Happy to help.

@leafpetersen: What's the scope of work here beyond updating DartPad's backend to use the appropriate SDK release for compilation and analysis? Is there anything unique to extension methods in comparison to other new language features, for example?

**Comment by leafpetersen** [comment]
I don't know all of the pieces involved in dartpad, so hard for me to say for sure what requires changes.  Things that I see that should be validated to work:
  - Syntax highlighting in the editor (I think @devoncarew said this is done with codemirror)
  - Hookup to the backend (backend is on a version which supports extension methods)
  - There's some kind of documentation window on the lower right: if this is just sending back info from the analysis server, my guess is that this will just work out of the box, but otherwise some work to be done.

**Comment by RedBrogdon** [comment]
SGTM.

1) Syntax highlighting will hopefully just work, though we've had some issues with it in the past, so that'll be something to check on.
2) Updating the backend to the new SDK version is something @domesticmouse does frequently, so there's a process in place for that.
3) DartPad's doc content does come from the analysis server (as do formatting, completions, and the other static analysis-based features). As long as we've got the right version of the SDK in the image for the backend, that should work without any changes to DartPad's codebase.

**Comment by domesticmouse** [comment]
What is required to start testing extension methods? I can easily run up a Dart 2.5.dev `dart-services` cluster. We need to point a version of the front end at said cluster, however. 

Related requests:
 * https://github.com/dart-lang/dart-pad/issues/1155
 * https://github.com/dart-lang/dart-pad/issues/774

**Comment by bwilkerson** [comment]
Extension method support can be enabled by enabling the experiment via the analysis options file:
```yaml
analyzer:
  enable-experiment:
    - extension-methods
```

**Comment by leafpetersen** [comment]
You can find a lots of examples of the syntax [in the test files here](https://github.com/dart-lang/sdk/tree/master/tests/language_2/extension_methods) to test out the syntax highlighting support.

**Comment by filiph** [comment]
Silly question: does the `extension-methods` experiment only work on tip of tree or is it in one of the more stable releases as well?

**Comment by leafpetersen** [comment]
> Silly question: does the `extension-methods` experiment only work on tip of tree or is it in one of the more stable releases as well?

The flag may or may not exist, but actual support only landed quite recently.

**Comment by domesticmouse** [comment]
Given this requires analysis options file content, running this on DartPad.dev is going to require two things:
 * A [Dart Docker](https://hub.docker.com/r/google/dart) release that includes the required support
 * A refactoring of how `dart-services` compiles and analyses code such that it creates full projects before spinning up the compiler. Currently, we only create projects for Flutter Web samples.

**Comment by bwilkerson** [comment]
It won't, of course, require an analysis options file after it's been enabled by default. Which means that another possibility might be to enable the feature locally, build an analysis server that has it enabled, and then use that server for testing. The changes to enable the feature are in https://dart-review.googlesource.com/c/sdk/+/113747.

**Comment by RedBrogdon** [comment]
Is there a separate command line flag to enable extension methods for dart2js/DDC when calling them directly?

**Comment by leafpetersen** [comment]
All tools should support the `--enable-experiment=extension-methods` flag on the command line.

Note that the CFE (and hence dart2js) implementation is not very complete right now, and that DDC does not support the runtime semantics yet.

**Comment by vsmenon** [comment]
@RedBrogdon - we're not sure there is anything else here.  It should just work when you're on D26.  Can you sanity check?  Do we need anything for syntax highlighting?

**Comment by RedBrogdon** [comment]
@domesticmouse is in the home stretch of moving compilation to DDK/unforked flutter web (https://github.com/dart-lang/dart-services/pull/452). Once that's done, I can try firing up a local copy with 2.6 to check things out.

**Comment by vsmenon** [comment]
Any update on this?

**Comment by domesticmouse** [comment]
We are working on unforking flutter web, but that is now turning into an orthogonal approach. 

On what timeframe do the extension methods become available? I can build a version of `dart-services` that runs the `dev` build of Dart, and the DartPad front end team can add a version selector to the front end UI.

**Comment by leafpetersen** [comment]
Extensions methods are now available in dev, and should be in 2.6.0 stable around the end of the month.  I wouldn't bother do any extra work to get a dev version in, but when stable lands it would be good to roll to that to pick up support.  Also rolling in a version of the syntax highlighter that recognizes extensions would probably be good.

**Comment by domesticmouse** [comment]
I'll be rolling up `dart-services` to 2.6.0 as part of the Dart 2.6.0 launch. I believe @johnpryan is in the process of getting a version of [codemirror with extension method keywords](https://github.com/google/codemirror.dart/pull/105) integrated into the DartPad front end app.

**Comment by vsmenon** [comment]
Just to clarify:
- Extension methods are enabled by default in 2.6 dev branches and the upcoming 2.6 stable.  No flag needed to enable.
- Extension methods work in dart2js and ddk but not the old analyzer-based ddc.  We expect to delete the latter soon.

**Comment by domesticmouse** [comment]
I've just raised https://github.com/dart-lang/dart-pad/issues/1341 to track removing our dependence on the old analyzer based DDC. 

My understanding is that we can stay on the old DDC for the Dart 2.6 release, but have to be off it for Dart 2.7 release. Am I in the right ballpark?

**Comment by vsmenon** [comment]
The old DDC will not support static extension methods for 2.6, but will otherwise work.

@mit-mit - are you ok with DartPad not supporting static extension methods until 2.7?

**Comment by mit-mit** [comment]
Yes.

**Comment by vsmenon** [comment]
Great.

>My understanding is that we can stay on the old DDC for the Dart 2.6 release, but have to be off it for Dart 2.7 release. Am I in the right ballpark?

Right.  FYI - @sigmundch @nshahan

**Comment by vsmenon** [comment]
BTW, are dartpad and codemirror things we need to track separately?  Is there any work for codemirror?

**Comment by RedBrogdon** [comment]
John updated CodeMirror a couple weeks ago to recognize "on" and "extension" as keywords:

https://github.com/codemirror/CodeMirror/pull/6033

So I believe we're good there. DartPad Eng will always have "update CodeMirror" on our todo list for new language feature that require it. Adding the update as a separate item on the release checklist isn't a bad idea, though.

**Comment by vsmenon** [comment]
As I understand it, we're good on DartPad (which uses Dart2JS).

We're in progress on FlutterPad (which uses DDC and expects to switch to DDK).

**Comment by vsmenon** [comment]
Can we close this now?

**Comment by johnpryan** [comment]
I think this can be closed. Extensions are working on dartpad.dev for Flutter (DDC) and Dart (Dart2JS) programs.
