### ISSUE TITLE
Dart Analysis has terminated (android studio)

### ISSUE THREAD

**Issue by TarekAlabd** [dart-lang/sdk#37900]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
UnimplementedError: Encoding "null"
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:172:7)
#1      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:171:9)
#2      _File._parse (package:analyzer/src/services/available_declarations.dart:1652:25)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#4      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#5      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#6      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#12     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#18     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#19     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#20     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#21     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#22     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#30     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#31     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#32     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#33     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#34     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

D:\Prog\flutter\bin\cache\dart-sdk\bin\dart.exe D:\Prog\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-183.6156.11 --useAnalysi
1566125052869 <= {"event":"server.connected","params":{"version":"1.27.1","pid":5016,"sessionId":""}}
1566125052900 <= {"id":"0","result":{"version":"1.27.1"}}
1566125052900 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1566125051036}
1566125052900 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1566125052900 => {"id":"3","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart"]}}}
1566125052900 <= {"id":"1"}
1566125052916 <= {"id":"2"}
1566125052916 <= {"id":"3"}
1566125053996 => {"id":"4","method":"analysis.setAnalysisRoots","params":{"included":["D:\\Tarek\\Programming\\flutter\\intro_animation"],"excluded":["D:\\Tarek\\Programming\\flutter\\intro_animation\
1566125053997 => {"id":"5","method":"analysis.setPriorityFiles","params":{"files":["D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart"]},"clientRequestTime":1566125053997}
1566125053998 => {"id":"6","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart"],"CLOSING_LABELS":["D:\\Tarek
1566125055509 <= {"event":"analysis.errors","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\pubspec.yaml","errors":[]}}
1566125055532 <= {"event":"analysis.errors","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\android\\app\\src\\debug\\AndroidManifest.xml","errors":[]}}
1566125055620 <= {"event":"analysis.errors","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\android\\app\\src\\main\\AndroidManifest.xml","errors":[]}}
1566125055635 <= {"event":"analysis.errors","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\android\\app\\src\\profile\\AndroidManifest.xml","errors":[]}}
1566125058151 => {"id":"7","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1566125058151}
1566125058688 <= {"id":"4"}
1566125061152 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1566125061167 <= {"id":"5"}
1566125061183 <= {"id":"6"}
1566125061183 <= {"id":"7","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1566125084089 <= {"event":"analysis.errors","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file
1566125084105 <= {"event":"analysis.highlights","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","regions":[]}}
1566125084105 <= {"event":"analysis.navigation","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","regions":[],"targets":[],"files":[]}}
1566125084120 <= {"event":"analysis.closingLabels","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","labels":[]}}
1566125084136 <= {"event":"analysis.outline","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name"
1566125084136 <= {"event":"analysis.overrides","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","overrides":[]}}
1566125084151 <= {"event":"flutter.outline","params":{"file":"D:\\Tarek\\Programming\\flutter\\intro_animation\\lib\\main.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"codeOffset":0,"c
1566125091277 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"UnimplementedError: Encoding \"null\"\n#0      translateErrorToken (package:front_end/sr
```

**Comment by srawlins** [comment]
Thanks for filing an issue. This has been previously reported in https://github.com/dart-lang/sdk/issues/37641; please follow along there if interested.
