### ISSUE TITLE
standalone_2/io/file_system_watcher_test is flaky on Windows

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#37909]
Timeouts:

[log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8904689634760463520/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)
[log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8904685545374473392/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)
[log3](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8904686202099164480/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)

Runtime errors:

[log4](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8904962870934627568/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)
[log5](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8904946517620382992/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)

```
/================================================================================================\
  | standalone_2/io/file_system_watcher_test failed again (Timeout -> RuntimeError, expected Pass) |
  \================================================================================================/
  --- Command "vm" (took 17.000558s):
  set DART_CONFIGURATION=DebugIA32 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\cache\builder\sdk\out\DebugIA32\crashpad_handler.exe & out\DebugIA32\dart.exe --no-background-compilation --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.packages C:\b\s\w\ir\cache\builder\sdk\tests\standalone_2\io\file_system_watcher_test.dart
  exit code:
  255
  stdout:
  unittest-suite-wait-for-done
  stderr:
  Unhandled exception:
  SocketException: OS Error: Access is denied.
  , errno = 5, port = 0
  #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
  #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
  #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
  --- Re-run this test:
  python tools/test.py -n dartk-win-debug-ia32 standalone_2/io/file_system_watcher_test
```

/cc @ZichangG

**Comment by ZichangG** [comment]
For the runtime errors, it is probably relative to file permission. Since this test is creating and modifying the file. But I'm not sure how to verify.

**Comment by aam** [comment]
Closed via https://github.com/dart-lang/sdk/commit/95db62d6a2ecd1b8bb6eeec36fd58950855c1ab9
