### ISSUE TITLE
Analyzers "Add type annotation" not always given as an option

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#37918]
At least on current master (d153e9844758160e70c93438c605ee52672ae4e3) I get the following behavior:

- The assist "Add type annotation" is not always given as an option.
- Sometimes I am given the option to "split variable declaration" - but not to add type annotation (despite splitting it actually adding the type annotation as well).

Example: On above sha1, open `pkg/front_end` and go to the file `lib/src/fasta/flow_analysis/flow_analysis.dart` and to line 295:
https://github.com/dart-lang/sdk/blob/d153e9844758160e70c93438c605ee52672ae4e3/pkg/front_end/lib/src/fasta/flow_analysis/flow_analysis.dart#L293-L297
Standing on variable I'm given the option to split. Doing so gives 
```
Variable variable;
variable = entry.key;
```
so it clearly knows.

Commenting this check out in the analyzer fixes this issue, but is probably not an ideal solution
https://github.com/dart-lang/sdk/blob/d153e9844758160e70c93438c605ee52672ae4e3/pkg/analysis_server/lib/src/services/correction/assist_internal.dart#L369-L373
(though, it seems that the split assist has no such check).

And then on line 1112
https://github.com/dart-lang/sdk/blob/d153e9844758160e70c93438c605ee52672ae4e3/pkg/front_end/lib/src/fasta/flow_analysis/flow_analysis.dart#L1110-L1114
I'm not given any option(s) at all --- but hovering the variable it still tells me that it's a "Variable", so again it knows.

Commenting this check out in the analyzer fixes this issue, but (again) probably not an ideal solution
https://github.com/dart-lang/sdk/blob/d153e9844758160e70c93438c605ee52672ae4e3/pkg/analysis_server/lib/src/services/correction/assist_internal.dart#L264-L267

Update: The "Variable" thing confused me, this reproduces it:
```
class Foo<E> {
  List<E> bar(List<E> baz) {
    var result = <E>[];
    for (var e in baz) {
      var x = e;
      print(x);
    }
    return result;
  }
}
```

and updating the analyzer to also allow TypeParameterType by adding `&& type is! TypeParameterType` seems to fix it.

**Comment by FMorschel** [comment]
@jensjoha, is this behaviuour still happening for you? I took your repro:

```dart
class Foo<E> {
  List<E> bar(List<E> baz) {
    var result = <E>[];
    for (var e in baz) {
      var x = e;
      print(x);
    }
    return result;
  }
}
```

And in `result` I do get both lints. In `x` I get none, I'm not completely sure what you meant by: 

> Sometimes I am given the option to "split variable declaration" - but not to add type annotation (despite splitting it actually adding the type annotation as well).

I could take a look at the declaration for `x` and see if I can figure out why neither assist trigger there and get back to you.

**Comment by jensjoha** [comment]
For the standalone example

```dart
class Foo<E> {
  List<E> bar(List<E> baz) {
    var result = <E>[];
    for (var e in baz) {
      var x = e;
      print(x);
    }
    return result;
  }
}
```

- I'm given options about both adding type and splitting on `var result = <E>[];`
- I'm not given such options on `for (var e in baz) {`.
- I'm not given such options on `var x = e;`

This seems to fit with what you are experiencing. I have - as of testing now - not experience being given only one option. I'm given either both or neither.

As for the fix I've hinted that "allow TypeParameterType" fixes it --- I was just unsure if that would have unforseen consequences. With record types being supported in a similar fashion (https://dart-review.googlesource.com/c/sdk/+/262260) it's probably ok though.

**Comment by FMorschel** [comment]
Did as you said, I do think your suggestion to allow type parameters is the right one: https://dart-review.googlesource.com/c/sdk/+/388281.
