### ISSUE TITLE
"We're sorry, you've found a bug in our compiler."

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [dart-lang/sdk#37911]
[SEVERE]build_web_compilers:ddc on lib/login_screen.ddc.module (cached): Error compiling dartdevc module:hoops_admin|lib/login_screen.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\Tools\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/hoops_admin/login_screen.ddc.js --source-map --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/services.ddc.dill=packages/flutter_web/services --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/hoops_admin/scroller.ddc.dill=packages/hoops_admin/scroller --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/websocket/src/websocket_browser.ddc.dill=packages/websocket/src/websocket_browser --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/powerflutter_base/powerflutter.ddc.dill=packages/powerflutter_base/powerflutter --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/hoops_shared/hoops_shared.ddc.dill=packages/hoops_shared/hoops_shared --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/hoops_admin/quiz_screen.ddc.dill=packages/hoops_admin/quiz_screen --summary=C:\Users\FortniteLaptop\AppData\Local\Temp\scratch_spacefe56d975-c290-11e9-92f9-54bf64511a94\packages/hoops_admin/widgets.ddc.dill=packages/hoops_admin/widgets --packages=file:///C:/Users/FORTNI~1/AppData/Local/Temp/kernel_builder_404a5d02-c291-11e9-92f9-54bf64511a94/.packages --module-name=packages/hoops_admin/login_screen --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:hoops_admin/login_screen.dart package:hoops_admin/main.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:391:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by TheDOme6** [comment]
same on my machine

**Comment by TheDOme6** [comment]
Found a fix: run flutter clean or delete the .dart_tool folder. If it still doesn't work run pub cache repair and pub get afterward.

**Comment by vsmenon** [comment]
Merging to:

https://github.com/dart-lang/sdk/issues/38102
