### ISSUE TITLE
Support increasing size of VM cpu sample buffer

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#37924]
For doing CPU profiling against a Flutter application, we need to be able to record very deep call stacks (made possible by increasing the stack depth - e.g. passing `--dart-flags=--max_profile_depth=256` to the flutter run command).

This means that the VM sample buffer will now fill and overflow even quicker than normal (where max_profile_depth = 128).

Can we also pass a flag to increase the VM sample buffer size? Perhaps we could even combine these actions into a common flag (e.g. `--deep-profile`) that is a combination of `--profile`, `--dart-flags=--max_profile_depth=256`, and a flag to increase the buffer size `--max-buffer-size` or something like that.

This `--deep-profile` mode could be executed with a warning that this will increase the size of their application, so that the user is aware of the tradeoffs. However, I would think this trade off would be one a user would be willing to make since it only applies to development and not release.
@bkonyi @jacob314

**Comment by rakudrama** [comment]
See also https://github.com/dart-lang/sdk/issues/29651

**Comment by kenzieschmoll** [comment]
An [issue](https://github.com/flutter/devtools/issues/1032) was filed against the DevTools timeline regarding this issue.  Any updates on this @bkonyi?

**Comment by bkonyi** [comment]
Sorry for the delay. I've got a [CL up for review](https://dart-review.googlesource.com/c/sdk/+/117208) that exposes a `--sample-profile-duration` flag. This flag takes in an integer for the number of seconds of profiling that the profiler's sample buffer should be able to handle in the worst case scenario given the profiler's sampling rate and the maximum profiler stack depth.

Note that providing this flag will print a warning to the console similar to the following:

```
$ dart --observe --sample-buffer-duration=120 --profile-period=50 --max_profile_depth=255 tmp.dart 

** WARNING ** Custom sample buffer size provided via --sample-buffer-duration
The sample buffer can hold at least 120s worth of samples with stacks depths of up to 255, collected at a sample rate of 20000Hz.
The resulting sample buffer size is 6624002048 bytes.
```

This example above mirrors the profiler settings that some of our customers require for fine grained profiling. If the sample buffer is to hold a minimum of 120s worth of samples with this configuration **it will consume 6317MiB of memory**, so you'll need to keep that in mind when choosing a value for this flag.
