### ISSUE TITLE
NNBD platform library migration

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37926]
This tracks required work for shipping NNBD migrated versions of the SDK platform libraries.

**Comment by a-siva** [comment]
I guess the only thing remaining for this issue is the actual unfork of the SDK?

**Comment by leafpetersen** [comment]
Is [this](https://github.com/dart-lang/sdk/issues/40042) complete now?  It's still marked as an open dependency.

**Comment by a-siva** [comment]
No that is not done yet, I guess that needs to finish.

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/issues/40042 is done now, so closing this issue.
