### ISSUE TITLE
Migrate core libraries to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37928]
This tracks the migration of the core SDK libraries to be NNBD clean (tests passing, statically analyzing).

Specifically, this issue covers the following libraries:
  - core, async, convert, collection, math, typed_data and internal

**Comment by leafpetersen** [comment]
Is there anything left to do here?  @munificent are all of these tests ported?

**Comment by munificent** [comment]
Almost. @eernstg is handling typed_data and I have a CL out for convert: https://dart-review.googlesource.com/c/sdk/+/130965.

**Comment by a-siva** [comment]
All the libraries used by the VM have been ported and are being used in the NNBD SDK.
