### ISSUE TITLE
Uncaught TypeError: Cannot read property 'main' of undefined

### ISSUE THREAD

**Issue by andesappal** [dart-lang/sdk#37938]
* Dart SDK 2.5.0-dev.2.1
* macos_x64
* Chrome

Hello. I get no issues on Webstorm, but on Chrome I get:
![image](https://user-images.githubusercontent.com/54340176/63443530-574f2600-c40b-11e9-8112-0814aee70eae.png)

I'd like to give you a test case and show how to reproduce the issue, but I'm afraid this is the first time an issue like this occurs for me, and it is happening with my customer's software, which at the moment is in its initial stage. I don't know how to act on this. Thank you in advance, Andres

**Comment by andesappal** [comment]
I think these files could be helpful:
https://gist.github.com/andesappal/be25ed8b10a45e4f818dd5ebec53df28
https://gist.github.com/andesappal/ea43109df83dd0198de9e78458bf4e1d
https://gist.github.com/andesappal/4a9ecc1e15b1d1b10a83c84a47ae58ab

**Comment by vsmenon** [comment]
Closing, as I believe this is fixed in the latest.
