### ISSUE TITLE
Migrate dart:html and related web libraries to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37931]
This tracks the migration of the dart:html libraries for the NNBD release.  Specifically, this covers the following libraries:
  - html, js, indexed_db, web_gl, svg, web_sql, web_audio

**Comment by lrhn** [comment]
The `dart:html` migration needs to also migrate the templates, so the dom generator tool need to have two different locations for those templates.

**Comment by leafpetersen** [comment]
The current open list is:

```
lib/svg
lib/web_audio
lib/web_gl
lib/web_sql
lib/indexed_db
lib/html
lib/js
lib/js_util.
```

@srujzs will own migrating all but the last two, @vsmenon will handle the last two.

**Comment by leafpetersen** [comment]
Migration how-to is [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by franklinyow** [comment]
@srujzs Can this be closed?

**Comment by srujzs** [comment]
The libraries have been migrated to NNBD, but two outstanding dart:html issues remain:

1) Converting getters and setters to natives to handle inevitable performance issues in the new NNBD-migrated libraries.
2) Converting html tests to NNBD for strong mode.

Maybe it makes more sense to spawn off issues for those to granularize work, but I've avoided closing this issue for the above reasons. Would you prefer I do that?

**Comment by franklinyow** [comment]
If these issues does not block the un-forking, we should close this, and open new issue under either #40106 or #40107.  Otherwise, I would leave this open.

**Comment by srujzs** [comment]
The first will impact weak mode performance, and will block the unforking. I filed #40772 to track that and put it under the unforking epic. I also filed #40769 to handle the second bullet, which will impact a separate epic. I will close this however, since it is functionally complete.
