### ISSUE TITLE
`Process.start` with a process that segfaults seems to bring down the VM

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#37932]
Problem:

If I use `Process.start` to call a process that segfaults, I don't get any output and all execution seems to go away, whereas if I invoke the process in my shell, I get `Segmentation fault: 11` and an exit code of 139.

Reproduction steps:

main.c:

```c
#include <signal.h>
#include <stdio.h>

int main(int argc, char** argv) {
  printf("GOODBYE, CRUEL WORLD\n");
  if (argc > 1) {
    raise(SIGSEGV);
  }
}
```

run `cc main.c -o segv`

main.dart:

```dart
import 'dart:io';

Future<void> main(List<String> args) async {
  print('[DART] Process.start:');
  final Process process = await Process.start('./segv', args);
  process.stderr.pipe(stderr);
  process.stdout.pipe(stdout);
  print(await process.exitCode);

  print('[DART] done');
}
```

run `dart main.dart` - output:

```
dnfield@mbp:dart_segv$ dart ./main.dart 
[DART] Process.start:
0
[DART] done
GOODBYE, CRUEL WORLD
```

run `dart main.dart die` - output:

```
dnfield@mbp:dart_segv$ dart ./main.dart die
[DART] Process.start:
dnfield@mbp:dart_segv$ echo $?
0
```

**Comment by mkustermann** [comment]
The `Segmentation fault: 11` is printed by the shell itself - you won't see this output when launching a subprocess yourself. What you can notice is the exit code of the subprocess.

Your example has a slight issue, which is non-trivial to see:
```
  process.stdout.pipe(stdout);
```
What this will do is, it will listen to the output of `process.stdout`, add any data that comes from there to `stdout` and once the `process.stdout` stream is done, it **will close** `stdout`. Any `print()` call afterwards will go to /dev/null.

So your example needs to be modified a bit to see if we actually have a bug. Could you try running:
```dart
import 'dart:io';
import 'dart:async';
import 'dart:convert';

Future<void> main(List<String> args) async {
  Future.delayed(const Duration(seconds: 1)).then((_) {
    print("One second timer expired");
  });

  print('[DART] Process.start:');
  final Process process = await Process.start('./segv', args);
  process.stderr
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen((line) => stderr.writeln(line));
  process.stdout
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen((line) => stdout.writeln(line));
  print(await process.exitCode);

  print('[DART] done');
}
```
This should print
```
% dart test.dart die
[DART] Process.start:
-11
[DART] done
One second timer expired
```

If you don't see the exit code, then we might have a bug in our process implementation. Though you should always see `One second timer expired`.

**Comment by dnfield** [comment]
You are entirely right - in fact, sticking with just print seems to be the way to go:

```dart
import 'dart:convert';
import 'dart:io';

Future<void> main(List<String> args) async {
  print('[DART] Process.start:');
  final Process process = await Process.start('./segv', args);
  process.stderr
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen(print);
  process.stdout
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen(print);
  print(await process.exitCode);

  print('[DART] done');
}
```

Thanks!
