### ISSUE TITLE
Generate dart:ffi API reference

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#37946]
I expected dart:ffi to be in https://api.dart.dev/dev or https://api.dart.dev/be, but it isn't yet.

**Comment by sjindel-google** [comment]
We have already wrote the documentation in the source, it's just marked as hidden until the FFI is stable.

I think this should be tracked by https://github.com/dart-lang/sdk/issues/37230

**Comment by sjindel-google** [comment]
Rather I mean https://github.com/dart-lang/sdk/issues/35775
