### ISSUE TITLE
Opt-in/Opt-out mechanism for NNBD

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37957]

**Comment by a-siva** [comment]
A similar mechanism would also be needed in CFE.

**Comment by johnniwinther** [comment]
CFE issue tracked through https://github.com/dart-lang/sdk/issues/39827

**Comment by stereotype441** [comment]
This epic has been rolled up into #40192 (Analyzer support for Unforked Null Safe SDK)
