### ISSUE TITLE
Parser support for NNBD

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37958]
Completion criteria:
- A parser feature shouldn’t be considered complete until there are passing analyzer unit tests for it, as well as language_2 tests.
- The goal for language_2 tests is to have adequate test coverage to verify that the feature works and that we agree with the language team about how it should behave.
- We’ll write explicit language_2 tests to handle ambiguities explicitly mentioned in the spec.  We’ll leave it to the language team to write tests for other ambiguities.

**Comment by bwilkerson** [comment]
@danrubel Is this work complete?

**Comment by danrubel** [comment]
I have finished Parser and AstBuilder changes along with a collection of analyzer NNBD tests.

**Comment by johnniwinther** [comment]
Closing this epic since all known issue are handled.

**Comment by johnniwinther** [comment]
Reopening the epic due to a new incoming issue.

**Comment by franklinyow** [comment]
Are we ready to close this?

**Comment by johnniwinther** [comment]
Let's try again!
