### ISSUE TITLE
[NNBD Migration Tool] Simplify treatment of inferred types

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37968]
Be sure to address corner cases of exact nullability logic, such as:
- Exact type gets propagated into a substituted type
- Exact type gets propagated into a type inferred via ?? or ?:
- Exact type gets propagated into a type inferred for a “var” declaration
- Exact type gets propagated into a type inferred from instantiate-to-bounds
- Exact type gets propagated into a type inferred for a mixin

Also part of this task:
- Get rid of `EdgeOriginKind.initializerInference`

**Comment by stereotype441** [comment]
This is now addressed.
