### ISSUE TITLE
NNBD Migration Tool - Exceptions Handling

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37974]
This is a moving target. As more and more of the tool is developed and ran against the sdk code base, we will find exceptions to handle. We will address the Top 10 new exceptions from each successive run. 

Last updated 20190821.

- DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:40:12) (x3268)
- Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:229:7) (x1051)
- new DecoratedType.<anonymous closure> (package:nnbd_migration/src/decorated_type.dart:65:16) (x541)
- EdgeBuilder.visitListLiteral (package:nnbd_migration/src/edge_builder.dart:807:7) (x354)
- EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:852:7) (x189)
- DecoratedType._substitute (package:nnbd_migration/src/decorated_type.dart:405:5) (x159)
- EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:1653:7) (x146)
- new DecoratedType.<anonymous closure> (package:nnbd_migration/src/decorated_type.dart:84:52) (x126)
- EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:1595:9) (x125)
- EdgeBuilder.visitSimpleIdentifier (package:nnbd_migration/src/edge_builder.dart:1062:7) (x123)

**Comment by stereotype441** [comment]
Here's the current top ten list:
- AlreadyMigratedCodeDecorator.decorate (package:nnbd_migration/src/already_migrated_code_decorator.dart:40:9) (x265)
- DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:59:10) (x245)
- EdgeBuilder.visitSetOrMapLiteral (package:nnbd_migration/src/edge_builder.dart:1018:7) (x122)
- EdgeBuilder._checkNonObjectMember (package:nnbd_migration/src/edge_builder.dart:1296:12) (x84)
- EdgeBuilder.visitAsExpression (package:nnbd_migration/src/edge_builder.dart:236:5) (x80)
- Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:228:7) (x62)
- _AssignmentChecker._checkAssignment (package:nnbd_migration/src/edge_builder.dart:1971:7) (x52)
- Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:239:7) (x51)
- Variables.decoratedDirectSupertypes (package:nnbd_migration/src/variables.dart:41:12) (x48)
- EdgeBuilder.visitSimpleIdentifier (package:nnbd_migration/src/edge_builder.dart:1080:7) (x42)

**Comment by stereotype441** [comment]
Here's the current top ten list:
- EdgeBuilder.visitAsExpression (package:nnbd_migration/src/edge_builder.dart:252:5) (x84)
- EdgeBuilder.visitIndexExpression (package:nnbd_migration/src/edge_builder.dart:758:7) (x30)
- _AssignmentChecker._checkAssignment_recursion (package:nnbd_migration/src/edge_builder.dart:2087:7) (x25)
- AnnotationTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/annotation_tracker.dart:39:16) (x24)
- new DecoratedType.<anonymous closure> (package:nnbd_migration/src/decorated_type.dart:64:16) (x24)
- EdgeBuilder.visitBooleanLiteral (package:nnbd_migration/src/edge_builder.dart:386:19) (x23)
- EdgeBuilder.visitAssignmentExpression (package:nnbd_migration/src/edge_builder.dart:274:7) (x22)
- EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:1746:21) (x19)
- EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:368:14) (x16)
- EdgeBuilder.visitIsExpression (package:nnbd_migration/src/edge_builder.dart:817:7) (x12)

**Comment by stereotype441** [comment]
Here's the current top ten list:
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1476:13) (x13)
- AnnotationTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/annotation_tracker.dart:39:16) (x12)
- DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:33:30) (x11)
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1460:9) (x10)
- EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:789:33) (x9)
- DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:59:10) (x9)
- EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1073:22) (x8)
- new DecoratedType._forTypeParameterSubstitution (package:nnbd_migration/src/decorated_type.dart:198:12) (x7)
- EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:1869:21) (x6)
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1536:7) (x4)

**Comment by stereotype441** [comment]
Here's the current top ten list:
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1501:13) (x13)
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1485:9) (x11)
- EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:804:33) (x9)
- AnnotationTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/annotation_tracker.dart:39:16) (x8)
- EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1098:22) (x8)
- EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:1916:21) (x6)
- EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1561:7) (x5)
- new DecoratedType.<anonymous closure> (package:nnbd_migration/src/decorated_type.dart:68:16) (x4)
- EdgeBuilder.visitSimpleIdentifier (package:nnbd_migration/src/edge_builder.dart:1197:7) (x3)
- Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:234:7) (x3)

**Comment by stereotype441** [comment]
We now have exceptions down to an acceptable level and we have transitioned to working on correctness issues.
