### ISSUE TITLE
InstanceRef returned for a closure is not valid

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#37989]
The `InstanceRef` returned for a bound closure contains fields `closureFunction` and `closureContext`. However, these fields are only valid for an actual `Instance`.

Example returned `BoundVariable`:

`{"type":"BoundVariable","name":"b","value":{"type":"@Instance","_vmType":"Closure","class":{"type":"@Class","fixedId":true,"id":"classes\/46","name":"_Closure","_vmName":"_Closure@0150898"},"kind":"Closure","id":"objects\/10","closureFunction":{"type":"@Function","fixedId":true,"id":"classes\/1099\/implicit_closures\/1","name":"staticOnClass","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/staticOnClass","name":"staticOnClass","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"Foo"},"_kind":"RegularFunction","static":true,"const":false,"_intrinsic":false,"_native":false},"_kind":"ImplicitClosureFunction","static":true,"const":false,"_intrinsic":false,"_native":false},"closureContext":{"type":"@Instance","_vmType":"Context","class":{"type":"@Class","fixedId":true,"id":"classes\/141","name":"Null"},"kind":"Null","fixedId":true,"id":"objects\/null","valueAsString":"null"}},"declarationTokenPos":714,"scopeStartTokenPos":723,"scopeEndTokenPos":891},{"type":"BoundVariable","name":"c","value":{"type":"@Instance","_vmType":"Closure","class":{"type":"@Class","fixedId":true,"id":"classes\/46","name":"_Closure","_vmName":"_Closure@0150898"},"kind":"Closure","id":"objects\/11","closureFunction":{"type":"@Function","fixedId":true,"id":"classes\/1099\/implicit_closures\/2","name":"instanceMethod","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/instanceMethod","name":"instanceMethod","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"Foo"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ImplicitClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"closureContext":{"type":"@Context","id":"objects\/12","length":1}},"declarationTokenPos":745,"scopeStartTokenPos":756,"scopeEndTokenPos":891}`

**Comment by bkonyi** [comment]
I think this is WAI (Observatory seems to allow for these fields in `@Instance` objects), but the documentation is wrong. I'll go ahead and update it to match.

**Comment by grouma** [comment]
I think you'll need to update package:vm_service as well.

**Comment by bkonyi** [comment]
> I think you'll need to update package:vm_service as well.

Yup, that was done as part of [this CL](https://dart-review.googlesource.com/c/sdk/+/115610). Published as 1.1.2.
