### ISSUE TITLE
[Proposal] Analyzer metadata annotation for argument type

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#37982]
```
class IdField {
  num value;
  bool operator ==(x) => x.value == value;
}

IdField field;
// silently accepted even though it's logically undesired
print(field=='string');
```
Ideally I'd want strict type for operator == argument `x` but if it's not possible then can we at least have an analysis metadata annotation to warn at compile time that an undesired type is passed to a function?
E.g.
```
  @restrict x IdField 
  bool operator ==(x) => x.value == value;
```
=>
`Warning: Parameter x is String which is not a subclass of IdField`

The use case: change type of a class member that is e.g. compared with a member of another class that used to be the same type but is not any more.

**Comment by duzenko** [comment]
Someone might suggest simply checking type of `x` inside the operator function body but in my case it's not a solution. I need to filter list elements by their member value and it would just return empty result in runtime rather than fixing the underlying issue at compile time.

**Comment by eernstg** [comment]
```dart
class IdField {
  num value;
  bool operator ==(covariant IdField x) => x.value == value;
}

main() {
  IdField field;
  print(field == 'string');
}
```

There are special rules in the language specification (section 'Equality') about the evaluation of expressions of the form `e1 == e2`, but no special rules about the type checking. The tools treat the expression as if it had been an invocation of `operator.==`, so you do get the compile-time error you mention, as long as `e1` has type `IdField` or a subtype thereof.

**Comment by duzenko** [comment]
That works. I should have asked on StackOverflow. Sorry.
