### ISSUE TITLE
CFE cross-module mixins sometimes do not inherit getters/setters.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38004]
Modular repro: https://dart-review.googlesource.com/c/sdk/+/114560
Ran with 
```dart pkg/dev_compiler/test/modular_suite.dart --configuration-name dartdevk-linux-release --verbose --filter mixin```
Outputs:  
```
dev-dart-app:/a.dart:3:7: Error: The non-abstract class 'A' is missing implementations for these members:
 - _Mix.Test
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
```

As a single module:
```
class A extends Object with Mix {}

abstract class Mix = Object with _Mix;

abstract class _Mix {
  List get Test => const ["Hello"];
}

main() {
  print(A().Test);
}
```
CFE (DDK) outputs `[Hello]`.

**Comment by askeksa-google** [comment]
This is a problem for dart2js modular compilation as well and is present with both the old and new class hierarchy analysis code. The `_Mix` class in the example doesn't have to be private to trigger the problem. I am investigating further...

**Comment by askeksa-google** [comment]
When loading a named mixin application class from dill, the cfe did not properly set the internal flag marking it as a named mixin application. This confused the class hierarchy builder, causing it to miss the inherited members.

Proposed fix: https://dart-review.googlesource.com/c/sdk/+/115218
