### ISSUE TITLE
Angular Dart compilation failed

### ISSUE THREAD

**Issue by widmoser** [dart-lang/sdk#38001]
Dart Angular compilation fails with the message: 

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!

-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.4.1/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/durooma_web/app_component.template.ddc.js --source-map --summary=packages/durooma_web/firebase.config.ddc.dill=packages/durooma_web/firebase.config --summary=packages/durooma_web/firebase.config.template.ddc.dill=packages/durooma_web/firebase.config.template --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js --summary=packages/firebase/src/app.ddc.dill=packages/firebase/src/app --summary=packages/firebase/firebase.ddc.dill=packages/firebase/firebase --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/logging/logging.ddc.dill=packages/logging/logging --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/stack_trace/src/chain.ddc.dill=packages/stack_trace/src/chain --summary=packages/meta/dart2js.ddc.dill=packages/meta/dart2js --summary=packages/angular/src/core/change_detection/change_detection.ddc.dill=packages/angular/src/core/change_detection/change_detection --summary=packages/angular/src/core/application_tokens.ddc.dill=packages/angular/src/core/application_tokens --summary=packages/angular/core.ddc.dill=packages/angular/core --summary=packages/angular/di.ddc.dill=packages/angular/di --summary=packages/angular/src/core/change_detection/change_detection.template.ddc.dill=packages/angular/src/core/change_detection/change_detection.template --summary=packages/angular/di.template.ddc.dill=packages/angular/di.template --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/angular/src/core/application_tokens.template.ddc.dill=packages/angular/src/core/application_tokens.template --summary=packages/angular/core.template.ddc.dill=packages/angular/core.template --summary=packages/angular/src/bootstrap/modules.ddc.dill=packages/angular/src/bootstrap/modules --summary=packages/angular/angular.ddc.dill=packages/angular/angular --summary=packages/money/money.ddc.dill=packages/money/money --summary=packages/firebase/firestore.ddc.dill=packages/firebase/firestore --summary=packages/durooma_web/src/account.ddc.dill=packages/durooma_web/src/account --summary=packages/durooma_web/app_component.ddc.dill=packages/durooma_web/app_component --summary=packages/angular/src/bootstrap/run.template.ddc.dill=packages/angular/src/bootstrap/run.template --summary=packages/angular/angular.template.ddc.dill=packages/angular/angular.template --summary=packages/angular/src/runtime/text_binding.ddc.dill=packages/angular/src/runtime/text_binding --summary=packages/angular/src/runtime/interpolate.ddc.dill=packages/angular/src/runtime/interpolate --packages=file:///var/folders/tl/4zfr9m4s0s57z2z_c20f4ddr0000gn/T/kernel_builder_gmL1K0/.packages --module-name=packages/durooma_web/app_component.template --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:durooma_web/src/transaction.template.dart package:durooma_web/src/transactions_component.template.dart package:durooma_web/src/category.template.dart package:durooma_web/app_component.template.dart package:durooma_web/src/account.template.dart
    dart --version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:391:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by vsmenon** [comment]
Merging to:

https://github.com/dart-lang/sdk/issues/38102
