### ISSUE TITLE
CFE gives wrong line number for some errors in extensions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38036]
In the example below, the CFE reports the following error:

```
../../../tmp/test2.dart:7:3: Error: The method 'call' isn't defined for the class 'int'.
Try correcting the name to the name of an existing method, or defining a method named 'call'.
  }
```

Note that the line number reported (line 7), is off by one from the actual line number of the incorrect call (line 6).

If the extension is changed to a class by replacing `extension E1 on A1` with `class E1`, the line number is reported correctly.

```dart
int topLevelMethod(int x) => -4;

extension E1 on A1 {
  int get topLevelMethod => 3;
  void test() {
    topLevelMethod(4);
  }
}
class A1 {}
void main() {}
```

cc @munificent

**Comment by srawlins** [comment]
The CFE now correctly reports the error on line 6.
