### ISSUE TITLE
Analyzer missing error when using a built-in identifier as an extension name.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38095]
The extension method feature spec says:

```
The name of an extension must not be a built-in identifier.
```

But I currently see no errors when running the analyzer on this program:

```dart
extension mixin on int {}
extension extension on int {}
extension as on int {}
void main() {
}
```

cc @lrhn @eernstg @munificent

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/114755/3
