### ISSUE TITLE
CFE Missing error when using a built-in identifier as an extension name

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38094]
The extension method feature spec says:

```
The name of an extension must not be a built-in identifier.
```

But I currently see no errors when running the CFE on this program:

```dart
extension mixin on int {}
extension extension on int {}
extension as on int {}
void main() {
}
```

cc @lrhn @eernstg @munificent

**Comment by vsmenon** [comment]
@johnniwinther @leafpetersen 

Should this block dart-lang/sdk#37350 ?  If so, we should add to D27.

**Comment by eernstg** [comment]
The name of an extension cannot be used as a type annotation (that would be a compile-time error even if it did parse), so we might actually be able to micro-optimize the language such that an extension name can be a built-in identifier.

However, I think it's extremely unlikely to be an improvement in terms of source code readability or general utility. Also, it is breaking in principle, but extension methods haven't "really" been released yet, so the breakage should be tiny.

So I'd recommend keeping the specification as it is, and getting the implementations adjusted to outlaw the built-in identifiers.

**Comment by leafpetersen** [comment]
Yes, we should fix this for D27 if possible.  The analyzer already reports this as an error so I'm not too worried about breakage at this point.
