### ISSUE TITLE
Parser incorrectly errors on "late var"

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38093]
I'm adding support to dartfmt for the new NNBD `late` modifier. When I try to parse:

```dart
late var i;
```

I get:

```
  line 1, column 10: Members can't be declared to be both 'var' and 'late'.
    ╷
  4 │   late   var i;
    │          ^^^
    ╵
```

I think this error is incorrect. My understanding from the discussion on https://github.com/dart-lang/language/issues/321 is that we [decided](https://github.com/dart-lang/language/issues/321#issuecomment-497070013) to make `late` a modifier that can be applied to any declarator, including `var`.

@danrubel @bwilkerson @stereotype441 @leafpetersen

**Comment by eernstg** [comment]
Yes, `late var i;` should be accepted. Here's the corresponding CFE issue: #38022.
