### ISSUE TITLE
Type parameter bounds not working in some cases when parent interface reimplements ancestor class

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#38098]
Dart SDK version: 2.4.1

For the following example:
```dart
class Component {
  Object get state => null;
}

class StatefulComponent<TState> extends Component {
  @override
  TState get state => null;
}

abstract class StatefulComponentImpl<TState> 
    extends StatefulComponent<TState> 
    with ComponentImplMixin {}

mixin ComponentImplMixin on Component {
  // some stuff that references Component members, requiring the `on` clause
}

class FooState {
  String get fooState => 'foo';
}

mixin FooComponentMixin<TState extends FooState> on StatefulComponentImpl<TState> {
  test() {
    // Analysis error: "The getter 'fooState' isn't defined for the class 'Object'."
    state.fooState;
  }
}
```
Within `FooComponentMixin`, `state` has a static type of `Object` when I would expect it to be the lower bound of TState, `FooState`.

The test case can also be reduced a bit further by eliminating ComponentInternalsMixin and just adding the redundant `implements`:
```diff
 abstract class StatefulComponentImpl<TState> 
     extends StatefulComponent<TState> 
+    implements Component {}
-    with ComponentImplMixin {}
-
-mixin ComponentImplMixin on Component {
-  // some stuff that references Component members, requiring the `on` clause
-}
```
but I wanted to show why I was "re-implementing" that class.

This issue also does not reproduce if `FooComponentMixin` is made a class that extends `StatefulComponent2<TState>` instead of just implementing it.

**Comment by vsmenon** [comment]
The CFE doesn't report an error on the above.

**Comment by greglittlefield-wf** [comment]
I just checked and can't reproduce this issue in Dart 2.8.4. Perhaps we can close this as fixed?

**Comment by eernstg** [comment]
Yes, the error isn't occur any more, so let's close it. @greglittlefield-wf, please create a new issue if you encounter similar behavior again.
