### ISSUE TITLE
How will analyzer view extensions on @immutable classes?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38104]
According to [immutable](https://pub.dev/documentation/meta/latest/meta/immutable-constant.html),

> Used to annotate a class C. Indicates that C and all subtypes of C must be immutable.
>
> A class is immutable if all of the instance fields of the class, whether defined directly or inherited, are final.
>
> Tools, such as the analyzer, can provide feedback if [...] a class that has this annotation or extends, implements or mixes in a class that has this annotation is not immutable.

Does this definition need to be amended for static extensions? I think maybe not because it looks like an extensions [cannot define fields](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#syntax):

> The member declarations can be any non-abstract static or instance member declaration except for instance variables and constructors

Am I reading that right? Is an "instance variable" a field? If that is the case, then no extension _could_ break the immutable contract, and we're fine.

CC @bwilkerson @lrhn @pq

**Comment by bwilkerson** [comment]
Yes, you're reading that correctly and extensions can't impact the mutability of a class.

We might want to think about the implications of `@sealed`, though.
