### ISSUE TITLE
Error only with dart2js without -O4 flag

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#38111]
I am getting an exception that only happens when using Dart2JS without the -O4 flag.
It doesn't happen with DDC.

Reading the stack trace, the last time it touches my code is a flag that enable some ngIf in my template file. So I am guessing the problem is within the template.
I tried commenting chunks of html in the template to try to find the problem but was in vain. It looks like it may be happening in a deeper component. 
There is just no enough info to track it.

As I have no idea what is going on, I can't make a repro case.

What can I do to debug this?

<img width="478" alt="Guaraci - Webinários e congressos 2019-08-29 15-43-40" src="https://user-images.githubusercontent.com/6199518/63967543-0b882680-ca74-11e9-8921-9812a5e6f0a4.png">

**Comment by vsmenon** [comment]
Can you compile with `--no-minify`?

**Comment by jodinathan** [comment]
The exception just is not happening anymore.
I tried several times to clear stuff and I haven't touched the code that was supposed to be the origin of the exception.
I have no idea what happened.

Should I close this and reopen if it happens again?

**Comment by vsmenon** [comment]
Yes, let's close and reopen if needed.  Thanks!
