### ISSUE TITLE
Parser fuzz assertion failure: `next.isIdentifier`

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38113]
`t{{r?this}}`

I did not put type-bug because it's unclear to me if this assertion failure indicates an actual bug.

```
'package:front_end/src/fasta/parser/parser.dart': Failed assertion: line 5274 pos 14: 'next.isIdentifier': is not true.,
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)    
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)       
#2      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5274:14)
#3      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#4      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#5      Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5695:15)
#6      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3732:14)
#7      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
```

@danrubel

**Comment by lrhn** [comment]
A failing assertions should not be reachable by any user input. In general, no user-facing Dart tool should fail with a thrown exception because it means the user won't get a good error message. 
Syntax errors should be recongized and reported by the parser in a usable format.

**Comment by MichaelRFairhurst** [comment]
@lrhn The failing assertion should not be reachable, yes, but this assertion error does not reach users because `--enable-asserts` is not on for any user facing tools by default.

Without `--enable-asserts`, this program does not crash.

It is however possible that without `--enable-asserts` the error messages get screwed up or something. I haven't looked deeply.

**Comment by danrubel** [comment]
If an assert fails, then an assumption in the parser is incorrect. Either the assert is incorrect and should be changed/removed, or there is a more subtle bug that needs to be addressed.
