### ISSUE TITLE
Update `is` type test logic for NNBD

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38129]
Need to preserve existing behavior in Legacy libraries 

Example `null is T` is `false` but `Null <: T`.

In libraries that have opted in, `null is T` should always agree with the subtype relation.

**Comment by franklinyow** [comment]
Is this still P2 and blocker?  Shouldn't be both.

**Comment by nshahan** [comment]
The spec and our implementation has converged. I believe we are handling these correctly now and we can open new issues for any case where our type test are not correct.
