### ISSUE TITLE
Create legacy and nullable types at runtime in DDC

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38127]
Use the new representation to track Legacy (aka star or *) and Nullable (aka question or ?) types at runtime.

**Comment by sigmundch** [comment]
@nshahan - would it be fair to say that this is now complete? Or are there additional items we need to workout here?

**Comment by nshahan** [comment]
Yes thanks, the implementation to emit the types has landed. c13ab9dce2e564915b522e8a2e92f33033ad8022
