### ISSUE TITLE
Analyzer allows extension setter even if receiver has getter with same basename.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#38136]
The analyzer does not report an error for the program:
```dart
class C {
  final int x = 42;
}
extension D on C {
  void set x(int o) { print(o); }
}
main() {
  C c = C();
  c.x = 42;
  c.x += 0;
}
```
It should be an error. Since the `C` interface has a member with base name `x`, the assignment `c.x = 42` should not trigger an extension member invocation, and it should just be an error that `C` does not have any `x=` setter.

**Comment by bwilkerson** [comment]
@leafpetersen

**Comment by leafpetersen** [comment]
I spent some time this morning looking into this.  The feature specification does say that extension resolution is done by base name, which has fairly broad implications, broader than just this example.  We don't seem to have any tests for this.  The CFE also doesn't seem to implement this correctly.

**Comment by leafpetersen** [comment]
Tests for this under review here: https://dart-review.googlesource.com/c/sdk/+/115211 .

**Comment by srawlins** [comment]
The analyzer now produces an error for both lines 9 and 10:

```none
  error • 'x' can't be used as a setter because it's final. • 38136.dart:9:5 • assignment_to_final
  error • 'x' can't be used as a setter because it's final. • 38136.dart:10:5 • assignment_to_final
```
