### ISSUE TITLE
As expression in const Constructor initializer List.

### ISSUE THREAD

**Issue by G5Becks** [dart-lang/sdk#38140]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK Version (2.4.1)
* MacOSX mojave

I have a situation where I am trying to figure out a way to pass a default argument to a const constructor, but the argument is a set that I cannot create because of the fact that the arguments to the set override the == operator.

One of the workarounds that I tried was to create a const List with the values and then in the initializer list I wrote,

`: _daysOfWeek = daysOfWeek as SplayTreeSet<DayOfWeek> ?? everyDay as SplayTreeSet<DayOfWeek>;`

This results in a compiler error when testing 

`**Error: As expression is not a constant expression.**`

The analyzer did not report anything during the implementation of this code.

Not sure if this is by design, but it would probably be helpful to report this as an error before hand.

**Comment by eernstg** [comment]
Sounds like a version issue. An `as` expression is constant (with suitable operands). Both the `dartanalyzer` and `dart` from commit 8a670d773bccdea29b8f76249317a6e054d7c50a are happy about the following program:

```dart
class A {
  final int x;
  const A(Object o) : x = o as int;
}

main() {
  const A(42);
}
```

**Comment by eernstg** [comment]
It looks like there is no bug as reported in the current versions of our tools, so I'll close the issue. @G5Becks, please re-open and provide more information if you disagree!
