### ISSUE TITLE
error: expected: IsRepresentable(result, representation())

### ISSUE THREAD

**Issue by feli-citas** [dart-lang/sdk#38147]
```

Isolate (/b/s/w/itgaEXbo/dart_fuzzCRGXML) NO-FFI FP : JIT-SLOWPATH-DebugSIMARM64 - KBC-INT-SRC-DET-ReleaseX64: !DIVERGENCE! 1.31:213432904 (-6 vs 0)
                                                                                                                              
fail1:
-6
212
212
x0.foo0_2 throws
x1.foo1_0 throws
x1.foo1_1 throws
0.8671544052470181
...
../../runtime/vm/compiler/backend/il.cc: 2391: error: expected: IsRepresentable(result, representation())
version=2.6.0-edge.35df96a2e28703efa67d0f555823f188cc031fb2 (Fri Aug 30 02:50:10 2019 +0000) on "linux_simarm64"
thread=31210, isolate=main(0x55636b36f800)
  pc 0x000055636848a5cc fp 0x00007fa66acfcf20 dart::Profiler::DumpStackTrace(void*)
  pc 0x000055636809fb42 fp 0x00007fa66acfd000 dart::Assert::Fail(char const*, ...)
  pc 0x00005563685d3db1 fp 0x00007fa66acfd060 dart::BinaryIntegerOpInstr::Evaluate(dart::Integer const&, dart::Integer const&) const
  pc 0x00005563685a3230 fp 0x00007fa66acfd0b0 dart::ConstantPropagator::VisitBinaryIntegerOp(dart::BinaryIntegerOpInstr*)
  pc 0x000055636859ee4c fp 0x00007fa66acfd0e0 dart::ConstantPropagator::VisitTargetEntry(dart::TargetEntryInstr*)
  pc 0x000055636859cecc fp 0x00007fa66acfd120 dart::ConstantPropagator::Analyze()
  pc 0x000055636859cda9 fp 0x00007fa66acfd1f0 dart::ConstantPropagator::Optimize(dart::FlowGraph*)
  pc 0x000055636868a55d fp 0x00007fa66acfd200 /b/s/w/ir/out/DebugSIMARM64/dart+0x1cff55d
  pc 0x0000556368689c24 fp 0x00007fa66acfd2c0 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x000055636868a0be fp 0x00007fa66acfd2e0 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x000055636870af96 fp 0x00007fa66acfd960 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x000055636870c016 fp 0x00007fa66acfdb80 /b/s/w/ir/out/DebugSIMARM64/dart+0x1d81016
  pc 0x000055636870ccb2 fp 0x00007fa66acfdc30 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  pc 0x000055636870df80 fp 0x00007fa66acfdcf0 dart::BackgroundCompiler::Run()
  pc 0x000055636855330c fp 0x00007fa66acfdd40 dart::ThreadPool::Worker::Loop()
  pc 0x0000556368552df4 fp 0x00007fa66acfdd90 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x0000556368484555 fp 0x00007fa66acfded0 /b/s/w/ir/out/DebugSIMARM64/dart+0x1af9555
-- End of DumpStackTrace


                 
```

**Comment by aartbik** [comment]
Reproduces, even for vanilla DebugX64:

dart fuzz.dart
[fuzz.dart.txt](https://github.com/dart-lang/sdk/files/3561336/fuzz.dart.txt)

../../runtime/vm/compiler/backend/il.cc: 2391: error: expected: IsRepresentable(result, representation())
version=2.6.0-edge.a94a3c60d7e7f9f395a9d3cd9949a1e47d228e49 (Fri Aug 30 16:38:14 2019 +0000) on "linux_x64"
thread=186461, isolate=main(0x557a52f82c00)
  pc 0x0000557a51d8b8ec fp 0x00007f66f67bdec0 dart::Profiler::DumpStackTrace(void*)
  pc 0x0000557a519a1b42 fp 0x00007f66f67bdfa0 dart::Assert::Fail(char const*, ...)
  pc 0x0000557a51ecc931 fp 0x00007f66f67be000 dart::BinaryIntegerOpInstr::Evaluate(dart::Integer const&, dart::Integer const&) const
  pc 0x0000557a51e9be10 fp 0x00007f66f67be050 dart::ConstantPropagator::VisitBinaryIntegerOp(dart::BinaryIntegerOpInstr*)
  pc 0x0000557a51e97a2c fp 0x00007f66f67be080 dart::ConstantPropagator::VisitTargetEntry(dart::TargetEntryInstr*)
  pc 0x0000557a51e95aac fp 0x00007f66f67be0c0 dart::ConstantPropagator::Analyze()
  pc 0x0000557a51e95989 fp 0x00007f66f67be190 dart::ConstantPropagator::Optimize(dart::FlowGraph*)

**Comment by aartbik** [comment]
For v41 in

```dart
    v37 <- Constant(#61) T{_Smi}
    v40 <- Constant(#12) T{_Smi}
....
    v38 <- UnarySmiOp:68(unary-, v37) T{_Smi}
    v41 <- BinarySmiOp:70(<< [tr], v38, v40) T{_Smi}
```
we evaluate to integer 9223372036854525952

**Comment by aartbik** [comment]
Calling Integer::ShiftOp() correctly yields  -249856 (-61 << 12) but then
```C++
    if (is_truncating()) {
      int64_t truncated = result.AsTruncatedInt64Value();
      truncated &= RepresentationMask(representation());
      result = Integer::New(truncated, Heap::kOld);
```
in BinaryIntegerOpInstr::Evaluate() changes the -249856 to 9223372036854525952.

**Comment by aartbik** [comment]
The real question, perhaps, is why this truncating shift appears as a result of FlowGraph::OptimizeLeftShiftBitAndSmiOp().

**Comment by aartbik** [comment]
Simple reproducer (with low threshold JIT compilation):

```dart
int bar(int x, int y) {
  return (x << y) & 0xffff;
}

@pragma("vm:never-inline")
int foo() {
  return bar(-61, 12);
}

main() {
  for (int i = 0; i < 20; i++) {
    int k = foo();
    print("k = $k");
  }
}

```

**Comment by aartbik** [comment]
I suspect this is the issue, since this ultimately is used to create the mask

```dart
static intptr_t RepresentationBits(Representation r) {
  switch (r) {
    case kTagged:
        return compiler::target::kBitsPerWord - 1;   // should be kSmiBits?

```

**Comment by mraleph** [comment]
I am starting to think that 

```
 truncated &= RepresentationMask(representation());
```

should be something like this

```
int64_t TruncateTo(int64_t v, Representation r) {
  switch (r) {
    case kTagged:
      return (v << 1) >> 1;
    case kUnboxedInt32:
      return (v << 32) >> 32;
    case kUnboxedUint32:
      return v & 0xFFFFFFFF;
    case kUnboxedInt64:
      return v;
    default:
      UNREACHABLE();
      return 0;
  }
}
```

to produce consistent results for all representations.

**Comment by mkustermann** [comment]
Agree with Slava.

The expression our compiler evaluates at compile-time is `(-61 << 12) & 0xFFFF`. Due to the mask we know that we don't care about the overflow bits of the shift and mark the instruction as truncating, meaning that we want the result to stay in Smi range.

Staying in Smi range on DebugX64 means that the upper two bits of the 64-bit integer have to be the same. So that's what the compile-time evaluator should do (and Slava's example shows how to do it).

**Comment by aartbik** [comment]
Thanks @mkustermann and @mraleph. I will change all mask uses to the TruncateTo() code.
