### ISSUE TITLE
Unable to Access window Object From dart:html

### ISSUE THREAD

**Issue by azwalzaman** [dart-lang/sdk#38154]
When I try to use the the window object from dart:html in an angulardart component like this:

```
Storage loc = window.localStorage;

loc['name'] = 'myname';
```
I get an error  like "**Expected a getter, setter or operator declaration**" at the second line on VS Code.

Then when I try doing it like:

`
window.localStorage['name'] = 'myname';`

I get "**Expected to find semicolon**" near the dot operator after the window object. I tried it with things other than localStorage as well.

Dart version:
Dart VM version: 2.4.1

OS:
Windows 10

**Comment by vsmenon** [comment]
This sounds like a parse error of some sort.   Can you provide a more complete repo?  E.g., the file you get an error on?

**Comment by azwalzaman** [comment]
Okay, I'll send it shortly

**Comment by azwalzaman** [comment]
@vsmenon Okay, I'll send it shorty

**Comment by vsmenon** [comment]
Also, you may try running `dartanalyzer` directly on the file.  Is the error on `window` the first one you hit?  If there are earlier (or other) ones, it may be getting confused.

**Comment by azwalzaman** [comment]
@vsmenon I don't get any errors when I comment that part out so I think it's the first error.

**Comment by vsmenon** [comment]
Okay, I'm going to close this one then.  The analyzer appears to believe you're in the middle of a class declaration (or similar) and is not expecting a statement.  It doesn't really have anything to do with `window`.

**Comment by azwalzaman** [comment]
@vsmenon Okay. But how could I work around this? I was trying a modified version of the Tour Of Heroes guide from Angular Dart. There's a file that returns mock data(a list of objects). I intended to change that to read from localStorage and return the data from it.

**Comment by vsmenon** [comment]
Fix the static errors in order.  Your code for `window` may be fine.
