### ISSUE TITLE
Cannot return `this` in async method when `this` could be coerced to a typedef.

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#38162]
* Dart SDK Version (`dart --version`)

Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"

## Description

The following code works fine:

```dart
typedef Go = void Function(String name);

class CanGo {

  void call(String name) => print("Hello $name");

  Future<Go> next() {
    return Future.value(this);
  }
}

main() {
  Go go = CanGo();
  print("Going alright!");
  go("joe");
}
```

But if I change the next method to this:

```dart
  Future<Go> next() async {
    return this;
  }
```

which should be equivalent?... I get an error:

```
The return type 'CanGo' isn't a 'Future<void Function(String)>', as defined by the method 'next'.
```

## Expected result

The two different implementations of `next` seem equivalent, however only the first one "compiles" (according to the Dart Analyser).

Ok:

```dart
  Future<Go> next() {
    return Future.value(this);
  }
```

Not ok:

```dart
  Future<Go> next() async {
    return this;
  }
```

I am currently working around the issue by adding an "alias" to `this`:

```dart
  Go get self => this;

  Future<Go> next() async {
    return self;
  }
```

But would be nice to not have such an inconsistency in the language.

**Comment by lrhn** [comment]
Seems like the analyzer forgets to do implicit `call` method tear-off when the value is `this`. It works correctly on the common front-end.

**Comment by srawlins** [comment]
Analyzer is now ok with this code.
