### ISSUE TITLE
Incremental compiler re-issuing of errors from constant evaluator

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#38167]
Say we have the following:
* We have a class with a constant constructor with an assert initializer
* We compile and everything is fine because it's not initialized.
* We add a leaf-node which initializes it, compiles and we get an error as expected.
* We remove the leaf-node (or replace the instantiation or whatnot) and recompiles. We would expect to not see the error anymore as we are basically in the same world as before where we didn't get an error --- but we still get the error.

Reason: We re-issue all errors from libraries we didn't recompile. The error is attached to the wrong place (the library of the const constructor with the assert initializer) ---- it should have been attached to the library that cased the problem (the leaf-node that initialized it).

If this happens in flutter one would have to both fix the instantiation (e.g. remove the new code that triggered it) AND clean the old build data.

/cc @mraleph

**Comment by mraleph** [comment]
From my understanding this has a rather negative affect on the ease of use of the hot-reload, as you get stuck in a place from which only `flutter clean` can get you out. 

@askeksa-google could you take a look at this and asses how hard would it be to fix it?
