### ISSUE TITLE
[vm/ffi] Handle unaligned reads and writes

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#38170]
Most likely `Pointer.load`/`Pointer.store` cannot handle unaligned reads or writes.

**Comment by dcharkes** [comment]
We discussed adding documentation to `load` and `store` that they do not support unaligned reads and writes, and adding `loadUnaligned` and `storeUnaligned`.

**Comment by dcharkes** [comment]
Do we want to support this for MVP, or just add documentation that it's not support for MVP?

**Comment by dcharkes** [comment]
That would mean that hot loops with `offsetBy` would need to check every iteration. (For `elementAt` we could skip the check as it stays aligned.)

I think adding `loadUnaligned` and `storeUnaligned` to avoid any runtime overhead for the aligned ones is the cleaner solution.

**Comment by sjindel-google** [comment]
If the offset for `offsetBy` is a constant, then we don't need to check.
If it's variable, then yes, but is that a common situation?

**Comment by sjindel-google** [comment]
Martin and I agreed that the current state is acceptable:

1. We don't check or enforce alignment anywhere.
2. We assume Pointers are aligned to their pointed-to type's size when performing optimizations, for example in the choice of memory access instructions.
