### ISSUE TITLE
DartVM async*/await for are slow

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#38176]
I wrote several versions of the same code:

```dart
// the initial version
Stream<int> f1(Stream<int> stream) async* {
  await for (final e in stream) {
    if (e.isEven) {
      continue;
    }
    yield e;
  }
}

// only with method on stream
Stream<int> f2(Stream<int> stream) => stream.where((e) => !e.isEven);

// with a stream controller
Stream<int> f3(Stream<int> stream) {
  final sc = StreamController<int>();
  stream.where((e) => !e.isEven).listen(sc.add, onDone: sc.close);
  return sc.stream;
}

// without await for
Stream<int> f4(Stream<int> stream) async* {
  yield* stream.where((e) => !e.isEven);
}
```

I tested those methods on a stream of 1_000_000 integers. The results are almost the same on every runs (DartVM 2.4.1 and 2.5.0-dev.2.1):

- f1: 0:00:00.767951
- f2: 0:00:00.246713
- f3: 0:00:00.346697
- f4: 0:00:00.405180

It looks like some improvment could be done here to have better performance with `await for` and `async*`

**Comment by mraleph** [comment]
Duplicate of #29189

**Comment by mraleph** [comment]
Thank you for the report.

We are aware that there is a performance gap between `async` functions and hand written equivalents on microbenchmarks and we plan to eventually address some of it. 

If you have an example of a real world code that is significantly impacted by this gap please let us know - it would help us to prioritise fixing this.

**Comment by a14n** [comment]
Thank for pointing me to #29189 I didn't manage to find it before reporting the issue.

>If you have an example of a real world code that is significantly impacted by this gap please let us know - it would help us to prioritise fixing this.

Acutally I submitted this issue because I was performing a performance test on a real application and was triing to improve it. In a nutshell the application consume a gRPC streams of events, applies some filter/map on them and writes the result to other gRPC output streams. After some changes to avoid `async*/await for` the application now handles more events per second.

**Comment by mraleph** [comment]
@a14n Do you have some more complete example which includes some gRPC / server code etc? That would be very helpful.

**Comment by a14n** [comment]
It's really hard to extract a simple repro :-/
Even worse a simple repro with gRPC I started shows better performance with `async*` compared to `stream.where` :'(
I guess the perfs really depends on environment here.
