### ISSUE TITLE
 Unhandled exception

### ISSUE THREAD

**Issue by donald99** [dart-lang/sdk#38180]
The Flutter environment：
[✓] Flutter (Channel master, v1.9.8-pre.45, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
• Flutter version 1.9.8-pre.45 at /Users/***/Flutter
• Framework revision 2b7e59b9c0 (3 hours ago), 2019-09-02 04:20:42 -0400
• Engine revision 2baba33c82
• Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)
In flutter_tools ，git apply --3way 0001-aspectd.patch
My project add aspectd(https://github.com/alibaba-flutter/aspectd/blob/master/0001-aspectd.patch)，build it，get app.dill
then
dart /Dart/sdk/pkg/vm/bin/dump_kernel.dart app.dill app.dill.txt
Exception：

Unhandled exception:
RangeError (index): Index out of range: no indices are valid: 0
#0 Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1 BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2 BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3 BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4 main (file:///Dart/sdk/pkg/vm/bin/dump_kernel.dart:47:40)

#5 _startIsolate. (dart:isolate-patch/isolate_patch.dart:303:32)
#6 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by mraleph** [comment]
I don't think this really contains enough information for us to reproduce the issue. Just based on the exception you are trying to dump an empty `app.dill` file.
