### ISSUE TITLE
RegExp accepts invalid pattern '[^]'

### ISSUE THREAD

**Issue by peter-fingo** [dart-lang/sdk#38183]
This results in a single character match for every token, but it should probably raise an exception in the constructor.

```
void main() async {
  final r = RegExp('[^]');
  for (final x in r.allMatches('this is a string')) {
    print('${x.start} : ${x.end}');
  }
}
```

-->

```

0 : 1
1 : 2
2 : 3
3 : 4
4 : 5
5 : 6
6 : 7
7 : 8
8 : 9
9 : 10
10 : 11
11 : 12
12 : 13
13 : 14
14 : 15
15 : 16
```

**Comment by mraleph** [comment]
Why do you consider this to be an invalid pattern? It's an inversion of the empty character range - which means it includes all characters. 

Dart follows ECMAScript grammar for regular expressions, which indeed permits such expression, [see here](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-CharacterClass)

```
CharacterClass ::
   [[lookahead ∉ { ^ }] ClassRanges ]
   [ ^ ClassRanges ]
ClassRanges ::
    [empty]
    NonemptyClassRanges
```

**Comment by peter-fingo** [comment]
Apologies, thanks for the clarification.
