### ISSUE TITLE
Analyzer incorrectly resolves extensions with incomparable types.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38198]
The analyzer currently accepts the program below, which should be an error per the extension method spec, for the reasons explained in comments.  

Note that there is a bug in `static_extension_resolution_test.dart` from which this example is derived: the expectations in that test are currently incorrect for some of the cases.  I am working on a fix for the test.

```dart
class Target<T> {}

class SubTarget<T> extends Target<T> {}

extension E2 on SubTarget<Object> {
  static String name = "SubTarget<Object>";
  String e2() => "$name.e2";
}

extension E3<T> on Target<T> {
  static String name = "Target<T>";
  String e2() => "$name.e2";
}

void main() {
  SubTarget<num> s1 = SubTarget<int>();

  // The instantiated on type of `E2(s1)` is `SubTarget<Object>`
  // The instantiated on type of `E3(s1)` is `Target<num>`
  // Neither is a subtype of the other, so the resolution is
  // ambiguous, and should be an error (we do not proceed to the
  // instantiate to bounds tie breaker when they are unrelated)
  print(s1.e2()); 
}
```

cc @lrhn @stereotype441 @aadilmaan @bwilkerson

**Comment by leafpetersen** [comment]
Test for this out for review here: https://dart-review.googlesource.com/c/sdk/+/115620

**Comment by scheglov** [comment]
I cannot find in the spec the statement that `we do not proceed to the instantiate to bounds tie breaker when they are unrelated`. What I see is `5. the instantiate-to-bounds type of T1 is a subtype of the instantiate-to-bounds type of T2 and not vice versa.`

In this example `extension E2 on SubTarget<Object>` and `extension E3<T> on Target<T>`.
`extendedType1 = SubTarget<Object>` and `extendedType2 = Target<num>`.
`extendedTypeBound1 = SubTarget<Object>` and `extendedTypeBound2 = Target<dynamic>`.
And `extendedTypeBound1 is a subtype of extendedTypeBound2`.

Could you please point my at the pertinent spec location, or clarify the spec?

**Comment by leafpetersen** [comment]
> Could you please point my at the pertinent spec location, or clarify the spec?

Sure.  There are two places this is spelled out, in slightly different words.  In [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#extension-conflict-resolution) we have this:

> An extension with `on` type clause *T*<sub>1</sub> is more specific than another extension with `on` type clause *T*<sub>2</sub> iff 
>
> 1. The latter extension is declared in a platform library, and the former extension is not, or
> 2. they are both declared in platform libraries or both declared in non-platform libraries, and
> 3. the instantiated type (the type after applying type inference from the receiver) of *T*<sub>1</sub> is a subtype of the instantiated type of *T*<sub>2</sub> and either
> 4. not vice versa, or
> 5. the instantiate-to-bounds type of *T*<sub>1</sub> is a subtype of the instantiate-to-bounds type of *T*<sub>2</sub> and not vice versa.

Note that 4) and 5) are dependent on 3) being true (I agree this is not especially clear as written). 
 So in order for `E2` to be more specific than `E3` here, we need firstly that 3) is true, and secondly that either 4) or 5) are true.

But here `SubTarget<Object> <: Target<num>` is not true, so `E2` is not more specific than `E3`.  

And since `Target<num> <: SubTarget<Object>` is also not true, we also have that `E3` is not more specific than `E2`.

I think the language used in the [Summary](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#summary), while less precise, is a little clearer:

> One extension is more specific than another if the former is a non-platform extension and the latter is a platform extension, or if the instantiated on type of the former is a proper subtype of the instantiated on type of the latter, or if the two instantiated types are equivalent and the instantiate-to-bounds on type of the former is a proper subtype of the one on the latter.

**Comment by scheglov** [comment]
Thank you.

By a some reason the quote from the spec in the implementation was not precise, with (3) and (4) put together. Not sure if a copying mistake, or a change to the spec. When (3), (4) and (5) are separated, then the instantiate-to-bound makes sense.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/116142
