### ISSUE TITLE
Add constructors for VM Service Protocol objects so that required parameters are clearly specified

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#38194]
See this PR for details:
https://github.com/dart-lang/webdev/pull/628

**Comment by bkonyi** [comment]
[CL up for review](https://dart-review.googlesource.com/c/sdk/+/117211).

**Comment by devoncarew** [comment]
(FYI, having an `area-` label lets us know that an issue's been triaged)

**Comment by bkonyi** [comment]
> (FYI, having an `area-` label lets us know that an issue's been triaged)

Ah, makes sense. Thanks for letting me know!
