### ISSUE TITLE
RangeError while launching app on iOS Simulator

### ISSUE THREAD

**Issue by govindsh** [dart-lang/sdk#38206]
Android Studio 3.4
MAC OS - Mojave 10.14.6

**Error Snippet:**
Launching lib/main.dart on iPhone 5s in debug mode...
Running Xcode build...
Xcode build done.                                           11.3s
Syncing files to device iPhone 5s...

```
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't.
Error message was 'RangeError (index): Index out of range: no indices are valid: 0'.
Stacktrace included '#0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart:2177:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:426:17)
#4      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:499:14)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:133:34)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:116:20)
<asynchronous suspension>
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:339:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#18     _rootRun (dart:async/zone.dart:1120:38)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
'.
This might be a bug.
```
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3577491/initialize_from.dill.gz)

**Comment by mraleph** [comment]
Thanks for reporting the issue!

**Comment by mraleph** [comment]
@jensjoha Jens, could you add some checking into `initializeFromDill` to reject empty dill files? 

It would also be helpful to add some checking to the `readComponent` and to throw a more meaningful error.

**Comment by jensjoha** [comment]
> @jensjoha Jens, could you add some checking into `initializeFromDill` to reject empty dill files?

It has silently ignored it since April (d8739b582b5e).

> It would also be helpful to add some checking to the `readComponent` and to throw a more meaningful error.

I did that yesterday (4bd13a74d9096eca6a5b67cdd0025c8023237e2a).

**Comment by jensjoha** [comment]
This is an attempt to initialize from an empty file.
It is probably a bug --- somewhere --- (improper locking or whatnot) that the file becomes empty, but this error message was suppressed in this case back in April on the dart-side (in d8739b5).

@govindsh Thank you for your report. First, rest assured that everything is fine - the compile that reported this will be slower, but the output will be perfectly fine. My guess would be that you are on an old flutter version. In a newer flutter-version (with a newer dart version included) this error message should have been suppressed in this particular case to avoid unnecessarily scaring anyone. Again: Nothing bad happened to your output and everything is fine.

**Comment by govindsh** [comment]
Thank you @jensjoha & @mraleph.
