### ISSUE TITLE
Please merge FFI changes into dev channel

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38207]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/08132661a6b11e65a36d6b89098679268f4d4c7b, https://github.com/dart-lang/sdk/commit/d6af8654e58b837cd27d3b7ceea9e0678c0f1bf8 https://github.com/dart-lang/sdk/commit/f989605cc96bef6e34a3833dbbea522b86d313b2

**merge instructions**: n/a

**reason**: FFI is launching in preview win 2.5

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by mit-mit** [comment]
cc @dcharkes @sjindel-google

**Comment by athomas** [comment]
We decided not to include these changes in 2.5.0. They are all included in 2.6.0-dev.0.0.

**Comment by sjindel-google** [comment]
Not even the documentation changes?

**Comment by athomas** [comment]
Not even the documentation changes were accepted.

**Comment by mit-mit** [comment]
The rationale was that FFI API docs are available at https://api.dart.dev/dev, where they will update everytime we release a dev build
