### ISSUE TITLE
Error when field from mixin overrides covariant setter (CFE)

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#38211]
It should be permissible to override a setter having a covariant parameter with a field whose type is a subtype of the setter parameter type. Nevertheless, both the analyzer and CFE report an error when the field comes from a mixin:
```dart
abstract class A {
  void set x(covariant Object y);
}

class M {
  int x;
}

class B extends Object with M implements A {}
```
This is the CFE issue. The corresponding analyzer issue is [here](https://github.com/dart-lang/sdk/issues/38210).

**Comment by eernstg** [comment]
Note some extra cases with a similar issue described [here](https://github.com/dart-lang/sdk/issues/38210#issuecomment-528388220).
