### ISSUE TITLE
Don't print nullability attribute after supertype in hierarchy expectation files

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#38226]
CFE can produce .expect files with the result of the class hierarchy building phase (see, for example, the embedded .expect file with that  in https://github.com/dart-lang/sdk/blob/master/pkg/front_end/test/fasta/types/dill_hierachy_test.dart).  The printer outputs the nullability attributes after the supertypes (superclass, interfaces, the mixed-in type); although, that attribute doesn't make sense for supertypes and isn't in the Kernel AST at all.

That's an artifact of the .expect file printing routine and should be fixed.  However, it's probably not a high-priority task and doesn't affect the implementation of the NNBD features in CFE.

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/118568
