### ISSUE TITLE
`AnalysisServer.edit_isPostfixCompletionApplicable()` returns `true` for `try` and `tryon` when typing a comment

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#38235]
Dart SDK 2.4.1. Paste this code and invoke code completion in IntelliJ IDEA:
```
main(){
  () {
    // comment.<caret>
  };
}
```
`try` and `tryon` postfix templates are not expected here. But `AnalysisServer.edit_isPostfixCompletionApplicable()` returns `true`.

![image](https://user-images.githubusercontent.com/4499789/64429480-cb055a00-d0be-11e9-9712-88c49e86df79.png)

@stevemessick

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357985
