### ISSUE TITLE
Type-inference ... is it a bug?

### ISSUE THREAD

**Issue by buergerling** [dart-lang/sdk#38232]
This issue is related to Analyzer, Dart SDK Version 2.4.1. 

The following program worked fine some time ago. Now typeinference seems to have a bug. Before reporting a bug I wanted to make sure that the problem with type-inference is not my fault, so I asked a [question on stackoverflow. ](https://stackoverflow.com/questions/57807328/type-inference-in-dart-is-there-a-bug). But I think it is a bug ... 
 
The program is a transscript of the standard trampolining library (TailCalls.scala) of Scala version 13.0. Hence, I assume the correctness of the dart program.

```
abstract class TailRec<A> {
  A value;

  A result() {
    TailRec<A> tr = this;
    while (!(tr is _Done<A>)) {
      if (tr is _Bounce<A>) {
        tr = (tr as _Bounce<A>).continuation();
      } else if (tr is Cont) {
        var a = (tr as Cont).a;
        var f = (tr as Cont).f;
        if (a is _Done) {
          tr = f(a.value);
        } else if (a is _Bounce) {
          tr = a.continuation().flatMap<A>(f);
        } else if (a is Cont) {
          var b = a.a;
          var g = a.f;
          tr = b.flatMap<A>((x) => g(x).flatMap<A>(f));
        } else {
          throw new Exception("#1");
        }
      } else {
        throw new Exception("#2");
      }
    }
    return tr.value;
  }

  A compute() {
    TailRec<A> res = this;

    while (!res._isDone) {
      final _Bounce<A> bounce = res;
      res = bounce.continuation();
    }
    _Done<A> done = res;
    return done.value;
  }

  bool get _isDone;

  TailRec<B> map<B>(B Function(A) f) {
    return flatMap((a) => new _Bounce(() => new _Done<B>(f(a))));
  }

  TailRec<B> flatMap<B>(TailRec<B> Function(A) f) {
    if (this is _Done) {
      return new _Bounce(() => f(this.value));
    } else if (this is _Bounce) {
      return new Cont(this, f);
    } else if (this is Cont) {
      Cont<A, B> c = (this as Cont<A, B>);
      return new Cont<A, B>(c.a, (A x) => c.f(x).flatMap(f));  
      /*
      in the application of flatMap the falsely required type is:
        TailRec<B> TailRec.flatMap<B>(TailRec<B> Function(B) f)
      this is at odds with the definition of flatMap
      the correct type given is:
        TailRec<B> Function(A) f
      */
    } else {
      throw new Exception("#3");
    }
  }
}

class Cont<A, B> extends TailRec<B> {
  Cont(this.a, this.f);
  TailRec<A> a;
   TailRec<B> Function(A x) f;
  @override
  bool get _isDone => false;
}

class _Done<A> extends TailRec<A> {
  _Done(this.value);
  @override
  final A value;
  @override
  final bool _isDone = true;
}


class _Bounce<A> extends TailRec<A> {
  _Bounce(TailRec<A> Function()f) {
    this.continuation = f;
  }
  TailRec<A> Function()continuation; 
  @override
  final bool _isDone = false;
}

TailRec<A> done<A>(A x) => new _Done<A>(x);

TailRec<A> tailcall<A>(TailRec<A> continuation()) => new _Bounce(continuation);
```

In the application of flatMap the falsely required type is:

`flatMap<B>(TailRec<B> Function(B) f)
`

The definition of flatMap shows the correctly required type:

`flatMap<B>(TailRec<B> Function(A) f) 
`

Type-inference falsely concludes a type variable 'B' instead of an 'A'.

The correctly given type is:

`TailRec<B> Function(A) f`

I am using dart version 2.4.1

**Comment by mraleph** [comment]
Maybe I am missing something but `c` is `Cont<A, B>` which means `c.f` is `TailRec<B> Function(A x)` which means `c.f(x)` is `TailRec<B>` which means that `c.f(x).flatMap` is `TailRec<B'> flatMap<B'>(TailRec<B'> Function(B) f)`. 

Which indicates that things are working as expected in the inference. 

I would like to highlight two things. First of all, there seems to be some confusion in your code with `A` and `B`. Note that `Cont<A, B> extends TailRec<B>`. Which means that if you have `TailRec<A>` then line `Cont<A, B> c = this as Cont<A, B>` looks a bit suspicious - the second type argument to `Cont` should be the same as the first type argument to `TailRec` which is `A` and not `B`. So you should have something like `Cont<?, A> c = this` - which would make more sense. We just need to figure out what to use instead of `?`.

When I look at the Scala code I see that they use a feature that Dart currently does not have (though there are some discussions about adding such feature /cc @leafpetersen @lrhn). In Scala they write:

```scala
    final def flatMap[B](f: A => TailRec[B]): TailRec[B] =
      this match {
        case Done(a) => Call(() => f(a))
        case c@Call(_) => Cont(c, f)
        // Take advantage of the monad associative law to optimize the size of the required stack
        case c: Cont[a1, b1] => Cont(c.a, (x: a1) => c.f(x) flatMap f)
      }
```

Note that they use `match` to also "extract" type arguments of the `Cont` because there is not enough information in the context for that (remember `?` which we need to fill in in the Dart code). 

Ultimately I think a more Dart-y way to port this code would be something like this:

```
abstract class TailRec<A> {
  A value;

  A result() {
    TailRec<A> tr = this;
    while (!(tr is _Done<A>)) {
      if (tr is _Bounce<A>) {
        tr = (tr as _Bounce<A>).continuation();
      } else if (tr is Cont) {
        var a = (tr as Cont).a;
        var f = (tr as Cont).f;
        if (a is _Done) {
          tr = f(a.value);
        } else if (a is _Bounce) {
          tr = a.continuation().flatMap<A>(f);
        } else if (a is Cont) {
          var b = a.a;
          var g = a.f;
          tr = b.flatMap<A>((x) => g(x).flatMap<A>(f));
        } else {
          throw new Exception("#1");
        }
      } else {
        throw new Exception("#2");
      }
    }
    return tr.value;
  }

  A compute() {
    TailRec<A> res = this;

    while (!res._isDone) {
      final _Bounce<A> bounce = res;
      res = bounce.continuation();
    }
    _Done<A> done = res;
    return done.value;
  }

  bool get _isDone;

  TailRec<B> map<B>(B Function(A) f) {
    return flatMap((a) => new _Bounce(() => new _Done<B>(f(a))));
  }

  TailRec<B> flatMap<B>(TailRec<B> Function(A) f);
}

class Cont<A, B> extends TailRec<B> {
  Cont(this.a, this.f);

  final TailRec<A> a;
  final TailRec<B> Function(A x) f;

  @override
  TailRec<C> flatMap<C>(TailRec<C> Function(B) f) =>
    Cont<A, C>(this.a, (A x) => this.f(x).flatMap(f));  

  @override
  bool get _isDone => false;
}

class _Done<A> extends TailRec<A> {
  _Done(this.value);

  @override
  TailRec<B> flatMap<B>(TailRec<B> Function(A) f) =>
    _Bounce(() => f(this.value));

  @override
  final A value;

  @override
  final bool _isDone = true;
}


class _Bounce<A> extends TailRec<A> {
  _Bounce(this.continuation);

  TailRec<A> Function() continuation; 

  @override
  TailRec<B> flatMap<B>(TailRec<B> Function(A) f) =>
    Cont(this, f);

  @override
  final bool _isDone = false;
}
```

**Comment by buergerling** [comment]
Looks good as far as the type-checking is concerned. But even with the improved version there will be a runtime error. I think it would be desirable to have type-checking to avoid such surprises. 

Unhandled exception:
type '(int) => TailRec<int>' is not a subtype of type '(dynamic) => TailRec<dynamic>'
#0      TailRec.result (package:tailcalls/aleph.dart:11:46)
#1      main (package:tailcalls/aleph.dart:121:17)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
