### ISSUE TITLE
Flow analysis not accepting uninitialized final variables that are definitely assigned exactly once

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38237]
From an IM conversation with @Hixie 

The following code should be accepted with NNBD enabled (@leafpetersen confirmed):
```dart
final int foo;
switch (bar) {
  case 'a': foo = 1; break;
  case 'b': foo = 2; break;
  default: foo = 3;
}
```
It is currently rejected by the analyzer.  We need to get this working and make sure there is a language_2 test case for it (so that we won't forget to ensure that it works on CFE as well).

**Comment by scheglov** [comment]
@leafpetersen I cannot find where this is specified. The closest statement that I was able to find requires that the variable is also `late`: "It is not a compile time error to write to a `final` variable if that variable is declared `late` and does not have an initializer.".

**Comment by leafpetersen** [comment]
@scheglov We're discussing some of the corners of this feature [here](https://github.com/dart-lang/language/issues/946), but will have spec to you shortly.

**Comment by leafpetersen** [comment]
The spec for this landed, and the implementation work is tracked here: https://github.com/dart-lang/sdk/issues/43100
