### ISSUE TITLE
NNBD migration fails to remove dead "if != null" test

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38241]
The following code snippet:
```dart
void _foo(int arg) {
  if (arg == null) {
    print('null');
    return;
  }
  print(arg + 1);
}

void main() {
  _foo(1);
}
```
Is unchanged by the migration tool.  I would have expected this instead:
```dart
void _foo(int arg) {
  /* if (arg == null) {
    print('null');
    return;
  } */
  print(arg + 1);
}

void main() {
  _foo(1);
}
```

**Comment by srawlins** [comment]
This is obsolete due to #41231. The preview will currently indicate that the if condition is always false, but the output to disk will be unchanged, to support weak mode.
