### ISSUE TITLE
language_2/generic_no_such_method_dispatcher_test fails on dartkp bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#38254]
After https://dart-review.googlesource.com/c/sdk/+/115901 the test started to fail:

```
─➤  python tools/test.py -n dartkp-linux-release-x64 language_2/generic_no_such_method_dispatcher_test  
Test configuration:
    dartkp-linux-release-x64(architecture: x64, compiler: dartkp, mode: release, runtime: dart_precompiled, system: linux)
Suites tested: language_2

FAILED: dartkp-dart_precompiled release_x64 language_2/generic_no_such_method_dispatcher_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel []" (took 05.000106s):
DART_CONFIGURATION=ReleaseX64 $DH/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.dill $DH/tests/language_2/generic_no_such_method_dispatcher_test.dart --packages=$DH/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 02.000564s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=$DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.S --reify-generic-functions --no-use-osr --no-background-compilation --ignore-unrecognized-flags --packages=$DH/.packages $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 5ms):
DART_CONFIGURATION=ReleaseX64 rm $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.dill

exit code:
0

--- Command "assemble" (took 01.000392s):
DART_CONFIGURATION=ReleaseX64 gcc -m64 -shared -nostdlib -o $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.aotsnapshot $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.S

exit code:
0

--- Command "remove_assembly" (took 15ms):
DART_CONFIGURATION=ReleaseX64 rm $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.S

exit code:
0

--- Command "vm" (took 420ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --reify-generic-functions --optimization-counter-threshold=10 --no-use-osr --no-background-compilation --ignore-unrecognized-flags --packages=$DH/.packages $DH/out/ReleaseX64/generated_compilations/dartkp/tests_language_2_generic_no_such_method_dispatcher_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <123>, actual: <2>) fails.
#0      Expect._fail (package:expect/expect.dart:664)
#1      Expect.equals (package:expect/expect.dart:126)
#2      main (file://$DH/tests/language_2/generic_no_such_method_dispatcher_test.dart:56)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

--- Re-run this test:
python tools/test.py -n dartkp-linux-release-x64 language_2/generic_no_such_method_dispatcher_test
```

cc @fishythefish

**Comment by fishythefish** [comment]
This looks like an implementation bug?

```dart
class A {
  noSuchMethod(m) {
    return 123;
  }

  bar<U, V>(x) => x + 1;
}

class B extends A {}
```

The failing expectation is
```dart
Expect.equals(123, b.bar<int>(1));
```

`b.bar<int>` should result in NSM since only one type argument is provided, but we're producing `1 + 1` instead of `123`.

**Comment by fishythefish** [comment]
FWIW, I'm cleaning up tests that are failing on huge numbers of bots, and AFAICT this test wasn't passing on anything before. Bots might be red because this changed from a compile-time error to a runtime error.

**Comment by aam** [comment]
cc @crelier

**Comment by crelier** [comment]
I'll have a look, but we definitely check the number of passed type arguments when resolving a call target at runtime. See runtime/vm/object.cc:6665

bool Function::AreValidArgumentCounts(intptr_t num_type_arguments,
                                      intptr_t num_arguments,
                                      intptr_t num_named_arguments,
                                      String* error_message) const {
  if ((num_type_arguments != 0) &&
      (num_type_arguments != NumTypeParameters())) {
...

I suspect that the call was wrongly resolved earlier and we never get a chance to resolve it at runtime.

**Comment by sstrickl** [comment]
Also failing on vm-kernel-precomp-android-release-arm [in the same way](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8902815038328169968/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0), so approving there.

**Comment by fishythefish** [comment]
Thanks for helping out with the approvals. :)
I approved what I could before heading home for the weekend, but the builders were lagging quite a bit.

**Comment by crelier** [comment]
cc @rmacnak-google 

It looks like an issue in gen_kernel --aot

If I dump the generated kernel file (from a slightly simplified repro), I see this line:

`exp::Expect::equals(123, [@vm.direct-call.metadata=#lib1::A::bar] [@vm.inferred-type.metadata=int] b.bar<core::int*>(1));`

I think that the annotation `[@vm.direct-call.metadata=#lib1::A::bar]` is wrong, but I am not familiar enough with the precompiler to see where it is coming from.

Without the --aot flag, this line becomes:
`exp::Expect::equals(123, b.bar<core::int*>(1));
`

and the code properly invokes the noSuchMethod.

**Comment by crelier** [comment]
Here is the simpler repro and the commands used:

```
import "package:expect/expect.dart";

class A {
  noSuchMethod(m) {
    return 123;
  }

  bar<U, V>(x) => x + 1;
}

class FooBar extends A {}

main() {
  dynamic b = new FooBar();
  Expect.equals(123, b.bar<int>(1));
}

```
Then run
`pkg/vm/tool/gen_kernel --aot --platform=out/DebugX64/vm_platform_strong.dill -o ~/out.dill ~/repro.dart --packages=.packages`

`out/DebugX64/dart pkg/vm/bin/dump_kernel.dart ~/out.dill  ~/out.dill.txt
`

**Comment by crelier** [comment]
Also cc'ing someone from the CFE team: @stefantsov

**Comment by crelier** [comment]
cc @alexmarkov 
This issue may be related to https://github.com/dart-lang/sdk/issues/37572
