### ISSUE TITLE
Docs missing on `allowInterop`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38280]
https://api.dart.dev/stable/2.5.0/dart-js/allowInterop.html

The docs are missing. Maybe they are taken from https://github.com/dart-lang/sdk/blob/36648acfcc5062ad6d5e7bcd18e35e27714487ca/sdk/lib/js/dart2js/js_dart2js.dart#L700-L701

We do have a doc comment at https://github.com/dart-lang/sdk/blob/36648acfcc5062ad6d5e7bcd18e35e27714487ca/sdk/lib/_internal/js_dev_runtime/lib/js/dart2js/js_dart2js.dart#L546-L557

**Comment by natebosch** [comment]
See also https://github.com/dart-lang/sdk/issues/24576

**Comment by natebosch** [comment]
cc @kwalrath @jcollins-g 

How do we generate the docs for `api.dart.dev` - I want to ensure that they show up if I move these doc comments.

**Comment by kwalrath** [comment]
I haven't built the docs in a long time, but it looks like this is the code:

https://github.com/dart-lang/sdk/blob/master/tools/bots/dart_sdk.py#L37

@keertip might know the most about how this works.

**Comment by natebosch** [comment]
👍 

Was able to run `dart third_party/pkg/dartdoc/bin/dartdoc.dart --sdk-docs --output docs`

I confirmed that the version of the file it's reading is `sdk/lib/js/dart2js/js_dart2js.dart`

I'll move the comments to that file.
