### ISSUE TITLE
Make serialized IR for entire AOT compilation include more information

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38297]
In addition to all the serialized functions (in the form of IR), we would like to have the following information

  * [ ] Information for each class (e.g. size, class-id, type arguments vector offset, ...): This could be added to the serialized text `(class-desc <canonical-name> (cid 1) (...) ...)`
  * [ ] Information for fields (e.g. offset of the field in an instance): Similar to above, this could be `(field-desc <canonical-field-name> ...)`
  * [x] Constant array a) During AOT compilation accumulate all objects the serializer writes into an array and stick it into the object store to ensure it gets serialized and deserialized by AOT runtime. b) Add an "index" for each constant we serialize in the IR (so the generated code for LLVM can use those indices to index into the array provided by the deserialized snapshot
  * [x] A Function array, similar to the constant array, but containing the Function objects compiled by the AOT compiler. When populated, serialized flow graphs contain an index into this pool as well.

The code for the last two items, i.e. constant and function table, should be guarded by either a runtime flag or a preprocessor define.

/cc @mraleph @jakehehrlich

**Comment by mkustermann** [comment]
@sstrickl Maybe you could look into those things?

**Comment by sstrickl** [comment]
Just to note, landing this caused a failure in the test that uses --populate-llvm-constant-pool ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901442713388232672/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)):

| BOT                                 | TEST                                 | RESULT | EXPECTED | 
| ----------------------------------- | ------------------------------------ | ------ | -------- | 
| vm-kernel-precomp-linux-product-x64 | vm/dart/base_il_serialization_test/1 | Crash  | Pass     |

Only that bot at the moment, though. Have approved to get the bot back green and will investigate now.

**Comment by sstrickl** [comment]
The failure was likely related to #38661. I have a fix for this in review.

@jakehehrlich also requested a function pool containing the functions that were compiled. I've implemented this, and it's also in review. Will update the bug description to include this request (and check it off once the change has landed).

**Comment by mkustermann** [comment]
I think this work was discontinued due to possible user going away. Closing this issue.
