### ISSUE TITLE
[Phase 2 - Tools] Validate that built value works with const update 2018

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38294]
This tracks any investigation into whether built_value is ready to support [const-update-2018](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#language-1). Namely that means that the following are allowed in const expressions:

* Casts (`e as T`) and type tests (`e is T`).
* Comparisons to `null`, even for types which override the `==` operator.
* The `&`, `|`, and `^` binary operators on booleans.
* The spread operators (`...` and `...?`).
* An `if` element in a collection literal.

If built_value could interact with any expressions like this (for example... in an annotation?), we should verify that the two interact nicely.

**Comment by srawlins** [comment]
CC @aadilmaan

**Comment by mraleph** [comment]
@srawlins tentatively marking as `area-pkg` please change to a different area if this is wrong.

**Comment by davidmorgan** [comment]
`built_value` does almost nothing with const--only annotations and 'enum' constants. The enum constants are required to be of a specific form, so nothing can break there. The annotations just take bools and strings.

**Comment by srawlins** [comment]
Sweet.
