### ISSUE TITLE
[Phase 2 - Tools] Validate that angular works with const update 2018

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38295]
This tracks any investigation into whether angular is ready to support [const-update-2018](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#language-1). Namely that means that the following are allowed in const expressions:

* Casts (`e as T`) and type tests (`e is T`).
* Comparisons to `null`, even for types which override the `==` operator.
* The `&`, `|`, and `^` binary operators on booleans.
* The spread operators (`...` and `...?`).
* An `if` element in a collection literal.

If angular could interact with any expressions like this (for example... in an annotation, in a template), we should verify that the two interact nicely.

**Comment by srawlins** [comment]
Hi @leonsenft, @matanlurey . Sorry, this issue was filed very late (the feature has shipped). That's on me.

However, better late than never; before users really get excited about using these expressions in const expressions, we should validate that Angular handles them, e.g. in grabbing constants from analyzer's API.

Assigning to @leonsenft for triage.

CC @aadilmaan

**Comment by leonsenft** [comment]
Most of these aren't supported in the template (yet) because we don't use an actual Dart expression parser. This is nothing new, and for a long time we haven't supported parts of the Dart language in templates. He're's a recent example: https://github.com/dart-lang/angular/issues/1858

We'll have to look into the new const expressions for annotations.

**Comment by mraleph** [comment]
@srawlins tentatively marking as `area-web` please change to a different area if this is wrong.

**Comment by vsmenon** [comment]
Any objections to moving this issue to AngularDart tracker?

**Comment by leonsenft** [comment]
None! @srawlins it seems like you'd been experimenting with this recently. Did you encounter any issues?

**Comment by srawlins** [comment]
I've successfully landed some spreads in Angular providers lists and directives lists. Works fine. I played around with collection-if, as @leonsenft had some concerns there, but I couldn't seem to break it. :) I'll just mark this as complete.
