### ISSUE TITLE
Analyzer doesn't forward const constructors

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38305]
See #32223. 

```dart
class Mixin {}

class Base {
  const Base();
}

class Sub = Base with Mixin;

void main() {
  const Sub();
}
```

Analyzer incorrectly produces an error: `The constructor being called isn't a const constructor.`

**Comment by scheglov** [comment]
I have issues with understanding the spec wording, asked for clarification.

**Comment by srawlins** [comment]
Erik responded in that issue.

**Comment by eernstg** [comment]
I think we can close this issue, based on the title. In particular, the analyzer (and the CFE) do create/assume the required forwarding constant constructors, such that the following updated example has no errors:

```dart
mixin Mixin {}

class Base {
  const Base();
}

class Sub = Base with Mixin;

void main() {
  const Sub();
}
```

@srawlins, @scheglov, please reopen the issue or create a new one if you disagree.
