### ISSUE TITLE
DDC doesn't instantiate tearoff of .call

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38302]
See #32654 and `language_2/instantiate_tearoff_of_call_test`.

```dart
T f<T>(T x) => x;

void test(T Function<T>(T) f) {
  int Function(int) intFunc = f.call;
}

void main() {
  test(f);
}
```

DDC reports a runtime error at the assignment of `f.call` to `intFunc` because a value of type `<T>(T) => T` appeared where a value of type `(int) => int` was expected. Per the discussion in #32654, `f.call` should be implicitly instantiated with `int` and the assignment should succeed.

**Comment by vsmenon** [comment]
Do you know if this is both DDK and DDC?  FYI - @Markzipan

**Comment by Markzipan** [comment]
DDK emits a compile-time error:
```
Error: A value of type 'T Function<T>(T)' can't be assigned to a variable of type 'int Function(int)'.
Try changing the type of the left hand side, or casting the right hand side to 'int Function(int)'.
  int Function(int) intFunc = f.call;
```

**Comment by fishythefish** [comment]
It's failing across both backends, but not consistently. #38301 is the tracking error for CFE, which of course causes DDK to fail (with a compile-time error). The issue here is that analyzer is passing this test, but DDC produces a runtime error anyway.

**Comment by nshahan** [comment]
Closing this issue because there is no longer a version of DDC with an analyzer frontend and behavior in the CFE version of DDC should be covered by #38301.
