### ISSUE TITLE
Godot Engine API for Dart and Flutter using "dart:ffi" 

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#38303]
[As proposed to Godot](https://github.com/godotengine/godot-proposals/issues/58),
an API that allows to use Godot engine on Dart and Flutter
would give a chance to Dart and Flutter developers to an easier experience
in game development with Flutter or Flutter Web.

**Comment by LikeLakers2** [comment]
Hi, I came from the Godot proposal, referenced just above this comment.

It is possible to integrate Dart into Godot using bindings. This should serve whatever purpose you may need -- though I advise you to learn how Godot works first, as GDScript may already be enough for what you need!

While I myself have no experience creating bindings, I can lead you to some resources that may help you create your own (mostly copy-pasted from [here](https://github.com/godotengine/godot/issues/23064#issuecomment-491622903) so this may not be quite up-to-date):

https://github.com/GodotNativeTools/godot_headers (**important** - this is what you'll use to make the bindings)
https://github.com/GodotNativeTools (everything from there except `GDNative-demos` and `godot_headers` is a binding -- you could study how those are done so you could figure out how to bind Dart)
https://github.com/ShadowApex/godot-go (existing binding)
https://github.com/SimulaVR/godot-haskell (existing binding)

There's also https://github.com/GodotNativeTools/godot_headers/issues/36#issuecomment-440971346 which I think(?) should give you a basic understanding of how to make a binding; you might also consider making a new issue there if you're stuck on how to use the bindings.

You might also benefit from asking for help on some of the [community channels](https://godotengine.org/community), if you're still having trouble.

I hope these resources help you!

**Comment by iapicca** [comment]
> bindings

I imagine it more like a plugin that allows Godot to render inside a flutter widget tree:
Flutter App => Plugin (Godot Engine + Dart:ffi interface) => Flutter Widget Tree => Godot Inside a Widget

**Comment by iapicca** [comment]
> Hi, I came here from the Godot proposal, referenced just above this comment.
> 
> It is possible to integrate Dart into Godot using bindings... though I advise you to learn how Godot works first, as the GDScript (and C#) language integrated into the engine may already be enough for what you need!
> 
> While I myself have no experience creating bindings, I can lead you to some resources that may help you create your own (mostly copy-pasted from [here](https://github.com/godotengine/godot/issues/23064#issuecomment-491622903) so this may not be quite up-to-date):
> 
> https://github.com/GodotNativeTools/godot_headers (**important** - this is what you'll use to make the bindings)
> https://github.com/GodotNativeTools (everything from there except `GDNative-demos` and `godot_headers` is a binding -- you could study how those are done so you could figure out how to bind Dart)
> https://github.com/ShadowApex/godot-go (existing binding)
> https://github.com/SimulaVR/godot-haskell (existing binding)
> 
> There's also [GodotNativeTools/godot_headers#36 (comment)](https://github.com/GodotNativeTools/godot_headers/issues/36#issuecomment-440971346), which I think should give you a basic understanding of how to make a binding; you might also consider making a new issue there if you're still confused on how to create new bindings.
> 
> You might also benefit from asking for help on some of the [community channels](https://godotengine.org/community), if you're still having trouble.
> 
> I hope these resources help you!

I imagine it more like a plugin that allows Godot to render inside a flutter widget tree:
Flutter App => Plugin (Godot Engine + Dart:ffi interface) => Flutter Widget Tree => Godot Inside a Widget

**Comment by mraleph** [comment]
@iapicca Thanks for taking a time to file an issue and your interest in `dart:ffi`. 

I am not entirely sure I understand correctly what is expected from the Dart team here: if it is a request for the Dart team to provide bindings to Godot, then unfortunately this is unlikely to happen because we don't really have enough resources for that. Which means you have to take on this task yourself or rally the community. 

On the other hand if you start using `dart:ffi` and discover some ergonomic issues which makes it harder to use it, then please do file issues about those problems that you encounter.

**Comment by JOELwindows7** [comment]
Sorry for talking in a closed issue but, everyone, please wake up!

**Somebody did implement Unity in Flutter!!!**

https://github.com/snowballdigital/flutter-unity-view-widget

Don't let us defeat!

**Comment by kyadalu1** [comment]
Check [this](https://www.youtube.com/watch?v=gSd2U8LAkyw&list=PLQhQEGkwKZUobJyaYz2pQz8KWm-Pkv3rp&index=7) & [this](https://www.youtube.com/watch?v=Bt8JaPTUrNA&list=PLQhQEGkwKZUobJyaYz2pQz8KWm-Pkv3rp&index=9)

**Comment by JOELwindows7** [comment]
> Check [this](https://www.youtube.com/watch?v=gSd2U8LAkyw&list=PLQhQEGkwKZUobJyaYz2pQz8KWm-Pkv3rp&index=7) & [this](https://www.youtube.com/watch?v=Bt8JaPTUrNA&list=PLQhQEGkwKZUobJyaYz2pQz8KWm-Pkv3rp&index=9)

found new issue to mention in desc: https://github.com/m4gr3d/Godot-Android-Samples/issues/11
