### ISSUE TITLE
allowInterop is no longer idempotent in DDC in dev build

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#38311]
Calling `allowInterop` on the return value of `allowInterop` used to return the same function but it doesn't in DDC in the dev build of the SDK.

Reproduced with 
- Dart SDK 2.6.0-dev.0.0
- build_web_compilers 2.3.0

Reduced test case:
```dart
function() {}
final once = allowInterop(function);
final twice = allowInterop(once);
print(identical(once, twice)); // prints false
```

This issue does not reproduce in dart2js, or in 2.5.0 DDC/dart2js.

<details>
<summary> <em><code>allowInterop</code> implementation and compiled result, for reference</em></summary>

DDC source code for allowInterop: https://github.com/dart-lang/sdk/blob/cff9c587f4317175d48ac683aadcac05713b2e16/sdk/lib/_internal/js_dev_runtime/lib/js/dart2js/js_dart2js.dart#L557-L570
DDC-compiled code for `allowInterop`:
```js
  js.allowInterop = function allowInterop(F, f) {
    let ret = js._interopExpando._get(f);
    if (ret == null) {
      ret = function(...args) {
        return dart.dcall(f, args);
      };
      js._interopExpando._set(f, ret);
    }
    return F._check(ret);
  };
```

</details>

~~Could the issue be that the `F._check` check on the return value is creating a new instance that the expando doesn't know about?~~ Edit: never mind, I was thinking about the Expando wrong. It stores the converted function on `f`, not `ret`.

**Comment by vsmenon** [comment]
@natebosch - I don't think we handle this case.
