### ISSUE TITLE
web: flutter run failed after adding web support to existing project 

### ISSUE THREAD

**Issue by JamesKarl** [dart-lang/sdk#38310]
Error compiling dartdevc module:syncfusion_flutter_charts|lib/charts.ddc.js

packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:24:9: Error: Expected 0 type arguments.
  final Point<double> innerRadiusStartPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:24:47: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> innerRadiusStartPoint = Point<double>(
                                              ^^^^^
packages/syncfusion_flutter_charts/charts.dart:8:1: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
import 'dart:ui';
^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:27:9: Error: Expected 0 type arguments.
  final Point<double> innerRadiusEndPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:27:45: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> innerRadiusEndPoint = Point<double>(
                                            ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:31:9: Error: Expected 0 type arguments.
  final Point<double> radiusStartPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:31:42: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> radiusStartPoint = Point<double>(
                                         ^^^^^

Error compiling dartdevc module:jpush_flutter|lib/jpush_flutter.ddc.js  

### -------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/jameskarl/devenv/dart/flutter-stable/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/jpush_flutter/jpush_flutter.ddc.js --source-map
    --summary=packages/platform/platform.ddc.dill=packages/platform/platform --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --packages=file:///var/folders/nc/gy1m09vs0hg1_m22b1cmlt600000gn/T/kernel_builder_ATa9Fx/.packages
    --module-name=packages/jpush_flutter/jpush_flutter --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=file:///Users/jameskarl/devenv/dart/flutter-stable/bin/cache/flutter_web_sdk/libraries.json
    package:jpush_flutter/jpush_flutter.dart
    dart --version: 2.5.0-dev.4.0.flutter-be66176534 (Thu Sep 5 15:05:53 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xa6 (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3293:32)
#4      ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1593:20)
#5      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1466:14)
#6      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1430:19)
#7      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:2989:24)
#8      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1429:15)
#9      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2156:25)
#10     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2979:18)
#11     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1427:16)
#12     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:895:38)
#13     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:535:19)
#14     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:477:21)
#15     List.forEach (dart:core-patch/growable_array.dart:283:8)
#16     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:423:23)
#17     Iterable.forEach (dart:core/iterable.dart:277:30)
#18     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:316:15)
#19     _compile (package:dev_compiler/src/kernel/command.dart:387:27)
<asynchronous suspension>
#20     compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#21     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#22     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#28     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

                                                                        
AssetNotFoundException: syncfusion_flutter_charts|lib/charts.ddc.js     
Failed after 39.0s

**Comment by vsmenon** [comment]
Consolidating to https://github.com/dart-lang/sdk/issues/39271
