### ISSUE TITLE
Crash when compiling package:flutter_ui/sliver/sliver_list.dart,

### ISSUE THREAD

**Issue by Chainson** [dart-lang/sdk#38312]
------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\WorkSoft\Flutter1.9\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter_ui/sliver/sliver_box.ddc.js --source-map --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter/material.ddc.dill=packages/flutter/material --summary=C:\Users\Administrator\AppData\Local\Temp\scratch_spacee125fdf2-d443-11e9-8e2e-32b49ed6c559\packages/flutter_ui/sharedelement/product_detail.ddc.dill=packages/flutter_ui/sharedelement/product_detail --packages=file:///C:/Users/ADMINI~1/AppData/Local/Temp/kernel_builder_edbbffd0-d443-11e9-8e2e-32b49ed6c559/.packages --module-name=packages/flutter_ui/sliver/sliver_box --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/WorkSoft/Flutter1.9/flutter/bin/cache/flutter_web_sdk/libraries.json package:flutter_ui/sliver/sliver_box.dart
    dart --version: 2.5.0-dev.4.0.flutter-be66176534 (Thu Sep 5 15:05:53 2019 +0000) on "windows_x64"

**Comment by vsmenon** [comment]
I think this is a dup of https://github.com/dart-lang/sdk/issues/38102
