### ISSUE TITLE
type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer' after upgrading from Dart SDK 2.4.1 to 2.5.0

### ISSUE THREAD

**Issue by halverneus** [dart-lang/sdk#38328]
What I'm seeing when running "webdev build" with webdev version 2.3.0:

[SEVERE] ERROR - 2019-09-11 11:27:31.606401
[SEVERE] Asynchronous error
[SEVERE] type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer'
[SEVERE] dart:async                                                       Stream.transform
[SEVERE] package:web_socket_channel/src/copy/web_socket_impl.dart 728:28  new WebSocketImpl.fromSocket
[SEVERE] package:web_socket_channel/src/channel.dart 94:26                new WebSocketChannel
[SEVERE] package:shelf_web_socket/src/web_socket_handler.dart 77:25       WebSocketHandler.handle.<fn>
[SEVERE] 

I get the same error if I update all my dependencies to the latest:
  build_runner: ^1.6.9
  build_web_compilers: ^2.3.0
  sass_builder: ^2.1.3

The problem goes away when I downgrade back to 2.4.1.

**Comment by keertip** [comment]
Issue moved to [dart-lang/webdev #660](https://github.com/dart-lang/webdev/issues/660) via [**ZenHub**](https://www.zenhub.com/)
