### ISSUE TITLE
Enum constructor support

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/sdk#38329]
I'm coming from Android development with Kotlin where we have support for constructors and properties while in Dart we don't.

In my current Flutter project I have the following code to handle my `EventStatus` Enum:

```dart
class EnumValues<T> {
  Map<String, T> map;
  Map<T, String> reverseMap;

  EnumValues(this.map);

  Map<T, String> get reverse {
    if (reverseMap == null) {
      reverseMap = map.map((k, v) => new MapEntry(v, k));
    }
    return reverseMap;
  }
}

class EventStatusConverter {
  static final _statusValues = new EnumValues<EventStatus>({
    'UPCOMING': EventStatus.UPCOMING,
    'CURRENT': EventStatus.PUBLISHED,
  });

  static EventStatus decode(String status) => _statusValues.map[status];

  static String encode(EventStatus status) => _statusValues.reverse[status];
}
```

You can see that it is very dificult and we have to write alot of boilerplate code to handle Enums in Dart. We can add support for constructors and params in Enum to prevent boilerplate code. For example we can have something like this:

```java
enum EventStatus {
  const MyEnum(this.value);

  final String value;

  UPCOMING("UPCOMING"), CURRENT("CURRENT");
}
```
The code above compile in Java. And the code bellow compile in Kotlin:

```kotlin
enum class Color(val rgb: Int) {
        RED(0xFF0000),
        GREEN(0x00FF00),
        BLUE(0x0000FF)
}
```

What I am proposing is to have a more concise and easy way to deal with Enum in Dart.

**Comment by keertip** [comment]
Issue moved to [dart-lang/language #570](https://github.com/dart-lang/language/issues/570) via [**ZenHub**](https://www.zenhub.com/)
