### ISSUE TITLE
Implement override inference special casing for operator == in legacy libraries

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38336]
See https://github.com/dart-lang/language/issues/569.  Note that we should be sure to test this carefully in language_2 tests to make sure the analyzer and the front end implement this behavior the same way.

A particular corner case that is worth testing is:
- Class A (opted in) overrides `Object.operator==` without specifying a parameter type.
- Class B (opted out) overrides `A.operator==` without specifying a parameter type.

In this corner case, `B.operator==` should have inferred type `bool Function(dynamic)`, because the overriden `A.operator==` does not specify a type.

**Comment by scheglov** [comment]
This was done in cb0e5c5a3ee0e88270da525e3d87f6b44f06ffc9.
