### ISSUE TITLE
Dart 2.5.0 seems to break filesystem watching on Windows

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#38334]
Dart Sass's filesystem watcher tests have started failing more consistently on Windows only with the release of Dart 2.5.0. Watcher tests have always been kind of flaky, but we're seeing *much* more consistent failures now. See [this Travis job](https://travis-ci.org/sass/dart-sass/jobs/583772459) and [this one](https://travis-ci.org/sass/dart-sass/jobs/583803353) as examples; both of these jobs were manually restarted about four times, with similar timeouts each time. Note that the latter also increases the timeout and adds `test`-package-level retries, but the tests are still failing.

However, the most recent `master` branch build with Dart 2.4 [produced no Windows failures](https://travis-ci.org/sass/dart-sass/jobs/581905229), nor did [the same pull request with the Windows builder pinned to Dart 2.4.1](https://travis-ci.org/sass/dart-sass/jobs/581905229). This strongly suggests that something changed in Dart 2.5.0 that dramatically increased the flakiness of filesystem watchers on Windows.

This is high-severity for Dart Sass; until this is fixed, we'll need to pin our Windows releases to 2.4.1 so we don't break filesystem watching for downstream users.

**Comment by nex3** [comment]
As another data point, these same builds were *not* failing on Node.js on Windows, which ultimately bottoms out on the same OS-level APIs that Dart uses. This further suggests something's up in `dart:io`.

**Comment by ZichangG** [comment]
@nex3 Hi, looks like watcher doesn't response and trigger a timeout. It is similar to the other issue that I worked on [watcher issue](https://github.com/dart-lang/sdk/issues/37233) and I landed the change about a week ago(https://dart-review.googlesource.com/c/sdk/+/119524). 
Can you try it again to see whether my cl solves the problem? If not, I can take a look again.

**Comment by nex3** [comment]
Is that change in a released dev version of Dart 2.5?

**Comment by ZichangG** [comment]
I'm not quite sure.
Looks like this is added into 2.6.0-dev.7.0, according to https://github.com/dart-lang/sdk/compare/2.6.0-dev.7.0...master.

**Comment by nex3** [comment]
I'm unable to test this on Dart 2.6.0-dev.7.0 because it appears that [it has no x64 Windows release available](https://storage.googleapis.com/dart-archive/channels/latest/release/2.6.0-dev.7.0/sdk/dartsdk-windows-x64-release.zip).

**Comment by nex3** [comment]
Okay, I managed to figure it out, and it looks like the issue is fixed. :+1:

**Comment by ZichangG** [comment]
Thanks for testing. Appreciate! ^_^
