### ISSUE TITLE
Check that when test framework runs NNBD tests, it points analyzer at NNBD SDK

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38337]
Note: this is not needed for the long term, since when we ship NNBD there will only be a single SDK, and it will be null-aware.  It is needed for the short term, so that we can prototype NNBD features and analyze them against the NNBD-enabled SDK before it is merged into the main SDK.

**Comment by stereotype441** [comment]
Essentially all we need to do here is verify that our tests that exercise NNBD functionality are running with an NNBD SDK.  @scheglov will verify.

**Comment by scheglov** [comment]
I looked into https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8890622611336331664/+/steps/test_results/0/logs/results.json/0 and see that tests `nnbd/static_errors/use_nnbd_sdk_test/` are all `"matches":true`, and we created these tests to pass only when NNBD SDK is used, which means that we use NNBD SDK.
