### ISSUE TITLE
Add support for building SDK from sdk_nnbd

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38330]
@lrhn has proposed that we make any required changes/updates to the gn files to enable building a dart_sdk from the new sdk_nnbd fork before we start landing changes there.  This issue is to organize and track this work.  

The proposal is to have each implementation team handle their own build rules, unless it makes more sense to centralize this.  @a-siva @mraleph @johnniwinther @sigmundch @vsmenon @nshahan @munificent can you comment on who should own this for each team?

**Comment by a-siva** [comment]
@a-siva will own it for the Dart VM parts of the build.

**Comment by nshahan** [comment]
@nshahan will own for DDC.

**Comment by munificent** [comment]
I'll start hacking on this now. I'm just going to start at the top by adding a new "create_sdk_nnbd" to the main BUILD.gn file, go from there, and see what issues I run into.

**Comment by munificent** [comment]
First stab at it: https://dart-review.googlesource.com/c/sdk/+/117681

It doesn't do much, but it adds a bunch of new build targets for all of the stuff in sdk_nnbd/BUILD.gn, and has a lot of TODO comments for places in there where VM, dart2js, etc. changes will end up needing to go.

**Comment by munificent** [comment]
OK, I've landed that CL. It doesn't do anything very useful yet, but it should be a starting point for implementation teams to start forking the actual interesting logic in the various tool-specific BUILD.gn files.

**Comment by leafpetersen** [comment]
I think this is complete, can we close?

**Comment by munificent** [comment]
Yup! There's probably more bits of work to do for dart2js and the VM, but they will handle that as needed as part of their NNBD implementations.
