### ISSUE TITLE
Analyzer doesn't generate an error for missing getter

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#38342]
In `language_2/setter_no_getter_test.dart`, the analyzer does not produce any error for when a composite operator is called without a getter being defined.

```
set topLevel(var value) {}

class Example {
  set foo(var value) {}
}

main() {
  print(topLevel++);
  //    ^
  // [cfe] Getter not found: 'topLevel'.

  Example ex = new Example();
  print(ex.foo++);
  //       ^
  // [cfe] The getter 'foo' isn't defined for the class 'Example'.
}

```

In the review below, analyzer lines were added manually.
https://dart-review.googlesource.com/c/sdk/+/116825 for reference.

cc @leafpetersen

**Comment by srawlins** [comment]
I cannot find the test mentioned (I'm sure it's just been renamed), but we now produce the same two errors as CFE.
