### ISSUE TITLE
Analyzer allows initializers on external constructors

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38348]
Analyzer permits the following:

```dart
class Foo {
  int x;
  external Foo.c() : x = 1;
}
```

It should be a syntax error to provide initializers on an external declaration.

**Comment by srawlins** [comment]
The analyzer now reports

> error • An external constructor can't have any initializers. • a.dart:3:20 • external_constructor_with_initializer

If this changes with dart-lang/language#571, we can of course change analyzer.
