### ISSUE TITLE
Only include a single tflite dynamic library per SDK bundle

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#38366]
Currently we include tflite builds for osx, linux, and windows in all 64-bit builds. A small set of changes to https://github.com/dart-lang/tflite_native/blob/master/lib/src/bindings/dlib.dart and https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn should fix this.

**Comment by lambdabaa** [comment]
https://dart-review.googlesource.com/c/sdk/+/123552

**Comment by srawlins** [comment]
Is this obsolete, @bwilkerson ?

**Comment by bwilkerson** [comment]
Yes, I believe it is.
