### ISSUE TITLE
IntelliJ / VSCode refactorings - Refactor -> Move Class / Function to new file

### ISSUE THREAD

**Issue by atreeon** [dart-lang/sdk#38374]
Hi, would it be possible to add a few refactoring options to move classes and methods to new files.  It is something that I am used to doing in c# and I found it beneficial (there are similar refactor options in IntelliJ for Java and a bunch of other languages)

https://stackoverflow.com/questions/57910810/is-there-an-intellij-action-or-shortcut-that-allows-creating-a-new-separate-file/57912758?noredirect=1#comment102256421_57912758

IntelliJ - refactor option must belong in Dart
https://youtrack.jetbrains.com/issue/WEB-23272

**Comment by devoncarew** [comment]
`area-analyzer` - they'd be implemented in the analysis server, and exposed through the IDE clients.

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by escamoteur** [comment]
this is a duplicate of https://github.com/dart-lang/sdk/issues/30310

**Comment by devoncarew** [comment]
Closing as a dup of #30310.
