### ISSUE TITLE
the building sdk wiki maybe out  of date

### ISSUE THREAD

**Issue by xiaohongjun0509** [dart-lang/sdk#38397]
https://github.com/dart-lang/sdk/wiki/Building
  this wiki may out of date,  i build following the steps descride aboved, but tells missing various of files. can please update them?  thanks.

**Comment by LinXiaoTao** [comment]
+1

**Comment by srawlins** [comment]
@xiaohongjun0509 The Building page is fairly long. Can you tell us what steps are out of date, and what files were missing when you tried to follow the steps?
