### ISSUE TITLE
[dartdevc] DDK renames standard JS members accessed explicitly with JS interop.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38398]
Snippet:
```
import 'package:js/js.dart';

@JS()
class EditorClass {
  external String get prototype;
}

class MockEditorClass extends Mock implements EditorClass {}

class Mock {
  noSuchMethod (Invocation i) {
    print("CALLED");
  }
}

main() {
  var e = MockEditorClass();
  print(e.prototype);
}
```

Fails to print "CALLED" in DDK (but does in DDC). 

DDC is generating the prototype getter as:
```
MockEditorClass extends src__mock.Mock {
    get prototype() {
      return dart.lazyJSType(() => dart.global.EditorPrototype, "EditorPrototype")._check(this.noSuchMethod(new dart.InvocationImpl.new('prototype', [], {isGetter: true})));
    }
  };
```

But DDK adds an underscore to 'prototype':
```
  formula_select_test.MockEditorClass = class MockEditorClass extends mock.Mock {
    get _prototype() {
      return dart.lazyJSType(() => dart.global.EditorPrototype, "EditorPrototype")._check(this.noSuchMethod(new core._Invocation.getter(C15 || CT.C15)));
    }
  };
```

**Comment by vsmenon** [comment]
@Markzipan - is this something you need help from @natebosch on?

**Comment by Markzipan** [comment]
@vsmenon If we plan on working around this behavior for now, I'd appreciate the extra hands. 

But if the CFE can add some sort of annotation (or tell us about an existing one we're missing), the fix becomes easy: https://github.com/dart-lang/sdk/issues/38400

**Comment by natebosch** [comment]
In the long term we probably want to make this a static error - https://github.com/dart-lang/sdk/issues/37896

I'm a little surprised that this works in DDC today, how does it work there?

**Comment by Markzipan** [comment]
DDC checks that the getter is externally defined and is annotated with JS(). If that matches and it's in a hard-coded list of javascript built-in members, it doesn't append the underscore. It relies on the analyzer producing `PropertyInducingElement`s for getters/setters.

**Comment by Markzipan** [comment]
@vsmenon What are your thoughts in the case when `String` is another JS() class? Such as in:

```
import 'package:js/js.dart';

@JS()
class SomeJS {
}

@JS()
class EditorClass {
  external SomeJS get prototype;
}

class MockEditorClass extends Mock implements EditorClass {}

class Mock {
  noSuchMethod (Invocation i) {
    print("CALLED");
  }
}

main() {
  var e = MockEditorClass();
  print(e.prototype);
}
```

**Comment by natebosch** [comment]
>  I think you can workaround this (for now) by adding an abstract getter in the Mock:

When we are rewriting the forwarders for `noSuchMethod` we do the rewriting anyway, regardless of whether we have a local property with the same name.
