### ISSUE TITLE
Pass test_runner's NNBD flags to dartdevc

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38392]
The test_runner now allows configurations and command-line options to specify which NNBD mode a test should be compiled and run in. This needs to get plumbed through to the implementations. This issue is for doing that to DDC and DDK.

**Comment by munificent** [comment]
@nshahan is there any more work needed here? I think all the flags are going through now, right?

**Comment by nshahan** [comment]
Yes, we have been relying on the ability to set the mode since 8ad8abfb7463e33e6ac4363437ce843b3ebc7115.
