### ISSUE TITLE
ML Complete suggesting attributes that don't exist

### ISSUE THREAD

**Issue by henriquearthur** [dart-lang/sdk#38404]
I am using the new ML Complete feature to develop Flutter apps on VS Code. When I use CTRL+Space to view possible completions some attributes that don't exist in a particular widget shows up on the list, like in `Column` for example:

![image](https://user-images.githubusercontent.com/5016325/64928750-e248f380-d7f2-11e9-9c99-092a357f3266.png)

Attributes with `:` in the end do exist, but the others don't.

This is worse when I don't use CTRL+Space but I start typing instead. If I start typing `width` into a `BoxDecoration` widget, it will show as possible completion even though there is no `width` attribute on `BoxDecoration`. _(this is an example, happens with any widget)_

![image](https://user-images.githubusercontent.com/5016325/64928831-bc701e80-d7f3-11e9-9507-77cb85da0d76.png)

Those attributes don't end with `:` so by that I can know they don't exist but I think they shouldn't even appear on the list.

Before ML Complete update (or disabling it) this doesn't happen. Only attributes that **do exist** shows up on the list. This is very confusing because it changes previous behaviour.

Dart auto-complete is the best I've ever seen because it only shows to the developer what really can be completed. I hope that doesn't change with ML completions.

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale pt_BR.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

```

dart --version:
```
Dart VM version: 2.6.0-dev.0.0 (Unknown timestamp) on "linux_x64"
```

**Comment by lambdabaa** [comment]
Thanks for the thorough bug report @henriquearthur.
