### ISSUE TITLE
Parser fuzz timeout: unterminated list type args in unterminated parameterized call

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38415]
repro: `f() { m(T<R(<Z`

Never finishes parsing.

Adding a close delimiter of any kind (`}`, `)`, `>`, `;`, or `[`) fixes the infinite loop, as does adding `>` to `T<R`, or adding a function name to `<Z` ie `f<Z`.

**Comment by MichaelRFairhurst** [comment]
This doesn't infinite loop for dartmt so I wasn't sure if this wasn't analyzer+fasta integration specific. However, I just confirmed that it loops forever when run via the `dart` command, so it seems not analyzer specific (but likely recovery specific)

**Comment by stereotype441** [comment]
For now I'm classifying this under analyzer-ast-builder.  We need to investigate this on the analyzer side to see what code is executing under the infinite loop.  If it doesn't wind up being an infinite loop in analyzer code we can re-classify.

**Comment by jensjoha** [comment]
It goes into an infinite loop when compiling via the CFE as well.
In fact, it happens in package:front_end/src/fasta/parser/util.dart in findPreviousNonZeroLengthToken where token.beforeSynthetic == token...

**Comment by jensjoha** [comment]
Fixed with 165196dbc0da793dca85a06ac78bed8a4f58a12b.
