### ISSUE TITLE
utils/kernel-service:frontend_server build is broken

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38427]
46f2603 breaks the `utils/kernel-service:frontend_server` build target. It looks like something is trying to read `gen/utils/kernel-service/frontend_server.dart.dill` as UTF-8, sees a huge number of bytes it can't decode, and then vomits an error for each such occurrence.

cc @aam @rmacnak-google

**Comment by aam** [comment]
thanks for the report. 

How do you use this target?

**Comment by fishythefish** [comment]
I don't use the target specifically. Last week, I finally got fed up that the default (`all`) build target never works, so I fixed it. When I ran `tools/build.py -mrelease` today, I ran into this issue.

**Comment by fishythefish** [comment]
Fixed by b0fa0aebb7064b3af60a7504df832fe3bf4c9a44.
