### ISSUE TITLE
Analyzer warns about duplicate definition of empty identifier.

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#38448]
Running the analyzer on `f(,[]) {}` gives the following errors:
```
  error • Expected an identifier. • /...f.dart:1:3 • missing_identifier
  error • Expected an identifier. • /.../f.dart:1:5 • missing_identifier
  error • The name '' is already defined. • /.../f.dart:1:5 • duplicate_definition
```
The last one should not be reported.

**Comment by karlklose** [comment]
Also note that the last error in machine readable format reports a length of 0, which should probably illegal.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/117761
