### ISSUE TITLE
Dart lang improvements

### ISSUE THREAD

**Issue by pouloghost** [dart-lang/sdk#38446]
I'm new to flutter/dart from android. Dart seems to be more java than kotlin, which makes dart quite outdated. Some great kotlin language features are missing, and will you consider adding them into new versions of dart?

- immutable at language level ( data class in kotlin)
- property delegation ( by KProperty in kotlin)
- inheritance limitation ( default not inheritable)
- more declarative generic (where clause in C#)

**Comment by dgrove** [comment]
Issue moved to [dart-lang/language #583](https://github.com/dart-lang/language/issues/583) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dgrove** [comment]
Issue moved to [dart-lang/language #582](https://github.com/dart-lang/language/issues/582) via [**ZenHub**](https://www.zenhub.com/)
