### ISSUE TITLE
Dart2js emits invalid code for JS interop operator []=

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38441]
```dart
@JS()
library main;

import 'package:js/js.dart';

@JS('console.log')
external void consoleLog(Object o);

@JS('Object')
class RawObject {
  external void operator []=(Object key, Object val);
  external Object operator [](Object key);
}

void main() {
  var o = RawObject();
  o['foo'] = 'bar';
  consoleLog(o);
}
```

The emitted JS can't be parsed because it has a line like:

```js
u.[]=("foo","bar")
```

Which causes:

```
main.dart.js:64 Uncaught SyntaxError: Unexpected token '['
```

**Comment by natebosch** [comment]
Note that I only see this because I'm missing the `external factory RawObject()` constructor, and so at the use site dart2js is treating this as a Dart object, not a JS object.

When I include the external factory constructor dart2js will crash instead.

**Comment by sigmundch** [comment]
There are two issues with this code:
* `new RawObject` is compiled incorrectly (tracked separately here https://github.com/dart-lang/sdk/issues/38442)
* we don't have the logic to emit indexing operators properly for js-interop.

We need to evaluate whether this should be valid going forward.

A workaround for now is to use `js_util.setProperty` on the interop instance.

**Comment by natebosch** [comment]
I think we want to make this a static error (again?)

See https://github.com/dart-lang/sdk/blob/4b6ab33cfa60897242cba384c969d77dd52f9b8e/pkg/compiler/lib/src/diagnostics/messages.dart#L205-L235

**Comment by sigmundch** [comment]
+1 My inclination for now is also to do so.

**Comment by natebosch** [comment]
Statically disallowed with https://github.com/dart-lang/sdk/commit/833c70be61f8f34d4b809224caf3e4350e365735
