### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library (193)

### ISSUE THREAD

**Issue by AweiLoveAndroid** [dart-lang/sdk#38450]
I use Dart 2.6. When running sample codes,the problem happening as follow.

I just download the newest Dart dev SDK form `http://www.gekorm.com/dart-windows/` and install in my computer.(not in Flutter projects.)

Version: Dart dev 2.6
Tools:     VSCode
Computer:  Windows 7 x86_64

```
[Running] dart "c:\Users\Administrator\Desktop\hello_dart_ffi\samples\ffi\hello_world\hello.dart"
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (193)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:19:12)
#2      main (file:///c:/Users/Administrator/Desktop/hello_dart_ffi/samples/ffi/hello_world/hello.dart:17:36)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

[Done] exited with code=255 in 10.025 seconds
```

**Comment by dgrove** [comment]
Which precise version of Dart are you using? (dev/stable/master, and did you get it from the Dart or Flutter SDK?)

**Comment by sjindel-google** [comment]
Which sample code are you trying to run?

**Comment by AweiLoveAndroid** [comment]
@sjindel-google I‘m trying to use dart:ffi, and according to the `dart:ffi` documents,but the problem happends.

**Comment by AweiLoveAndroid** [comment]
@dgrove  Dart VM version: 2.6.0-dev.1.0

**Comment by sjindel-google** [comment]
@AweiLoveAndroid It would be really helpful if you could link us to the specific sample (we have a handful of samples on GitHub), so we can see which library it's failing to load.

**Comment by a136498491** [comment]
I encountered the same 192 error. 
My CPU and Windows are all x64,so my solution was to configure the project to 64-bit.

**Comment by fedorovmichael** [comment]
Hi, I have the some problem, I try to run on windows vm very simple code :

import 'dart:ffi' as ffi;
import 'dart:io' show Platform;

typedef hello_world_func = ffi.Void Function();
typedef HelloWorld = void Function();

void main() {
final dylib = 
  fi.DynamicLibrary.open(Platform.script.resolve("build/windows/x64/Debug/Runner/hello.dll").path);
final HelloWorld hello = dylib.lookup<ffi.NativeFunction<hello_world_func>>('hello_world')
      .asFunction();
  // Call the function
  hello(); 
}

code of dll:
**file: hello.cpp**
#include <stdio.h>
#include "hello.h"

int main()
{
    hello_world();
    return 0;
}
void hello_world()
{
    printf("Hello World\n");
}

**file: hello.h**:
void hello_world();

the code of c++ compiled in visual studio community 2019 to hello.dll
in the flutter I put it to:
build/windows/x64/Debug/Runner/hello.dll

when I run it in vs code get error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)
#0       _open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      main package:hello1/main.dart:19
#3      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:247:25)
#4      _rootRun  (dart:async/zone.dart:1190:13)
#5      _CustomZone.run  (dart:async/zone.dart:1093:19)
#6      _runZoned  (dart:async/zone.dart:1630:10)
#7      runZonedGuarded  (dart:async/zone.dart:1618:12)
#8      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:239:5)
#9      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
#10     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by dcharkes** [comment]
Note that error code 193 is not equal to 126.

Error code 193 is due to using a 64 bit sdk and loading a 32 bit dll, or vice versa.
Error code 126 could be due to a wrong path, try using backslashes in the path.

See both errors mentioned in: https://github.com/flutter/flutter/issues/58079.

Issue is already solved in linked issue.
