### ISSUE TITLE
breaking-change-request: ParameterMirror for abstract functions will not provide the default values for optional parameters

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#38464]
FunctionTypeMirror objects allow reflecting on a function. This object has a method 'parameters' which returns a list of the parameter types of the reflectee. The ParameterMirror object in turn allows reflecting on the formal parameter declaration.

Currently it is possible to reflect on abstract methods and it's formal parameter declaration.

### Planned Change
We will not support reflecting on the default parameter values of optional parameters specified on the formal parameter declaration of an abstract method.
`defaultValue` will always return a Null object
`hasDefaultValue` will return false

### Expected Impact
We expect the impact to be low because of this change as _dart2js_ and _flutter_ do not support _dart:mirrors_. In addition we always state that the _dart:mirrors_ library is unstable and its API might change.

**Comment by mit-mit** [comment]
Can you please post to dart-announce?

**Comment by a-siva** [comment]
Posted.

**Comment by mit-mit** [comment]
I don't see it? https://groups.google.com/a/dartlang.org/forum/?pli=1#!forum/announce

**Comment by mit-mit** [comment]
This has now been posted. If anyone has feedback on this breaking change, kindly post comments here.

**Comment by mit-mit** [comment]
@Hixie @matanlurey @dgrove, please review

**Comment by mit-mit** [comment]
There appear to be no objections, I think we can land this (after the current stable branch has happened)

**Comment by mit-mit** [comment]
@a-siva what is the status of this?

**Comment by a-siva** [comment]
This has landed already.
