### ISSUE TITLE
Migration engine should remove dead code, not comment it out.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38466]
Currently, if the migration engine discovers dead code, it comments it out by inserting `/*` and `*/` strings.  This is problematic because:
- It leads to an ugly migration result that the user must clean up
- It doesn't do the right thing if the dead code previously contained `/*` style comments.

What we should do instead is simply delete the dead code; the user can use their source control tool (or some other migration tool UX that we provide) to see what is being deleted, and un-do the deletion if desired.

**Comment by srawlins** [comment]
We received pretty strong feedback in the UX studies that we should implement this.

**Comment by stereotype441** [comment]
This is mostly obselete due to #41231, which avoids trying to delete unreachable code altogether.  However, we are still trying to change `@required` to `required` by commenting out the `@` symbol, so there's still some work to do.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
