### ISSUE TITLE
build sdk error on mac

### ISSUE THREAD

**Issue by LinXiaoTao** [dart-lang/sdk#38473]
Hi, I built sdk according to the wiki, but failed.

run command:
``` shell
./tools/build.py --verbose --mode release --arch x64 create_sdk
```

error info:
```
ninja -C xcodebuild/ReleaseX64 -v create_sdk
ninja: Entering directory `xcodebuild/ReleaseX64'
ninja: error: loading 'build.ninja': No such file or directory
BUILD FAILED
```

os version: macOS Mojave 10.14.2(18C54)

Xcode version: Version 10.1 (10B61)

Dart SDK sources version: git commit 6a27310b87

**Comment by LinXiaoTao** [comment]
solved

**Comment by thandy1212** [comment]
I'm getting the same issue. How did you solve it?

**Comment by AsteriskZuo** [comment]
I'm getting the same issue too. How did you solve it?

**Comment by AsteriskZuo** [comment]
> solved

I'm getting the same issue too. How did you solve it?
