### ISSUE TITLE
dart2js error

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/sdk#38475]
![image](https://user-images.githubusercontent.com/27394631/65212842-57a81300-dad6-11e9-8906-553b94af5da5.png)

``` java
➜  hello_key_client git:(feature-no-pwd-verify) ✗ dart2js -O1 -o password_generator.dart.js password_generator.dart
Warning: Interpreting this as package URI, 'package:flutter_hellokey_configuration/hello_key_client/password_generator.dart'.
Error: No 'main' method found.
Error: Compilation failed.
```

**Comment by sigmundch** [comment]
Thanks for reaching out. 

The error you show seems like a legitimate error from the compiler. It appears that the input file you provided is a library with no main? dart2js is a compiler designed to compile an entire Dart application by giving it the .dart file containing `main`. It doesn't have support for compiling libraries separately if that's what you are trying to do.

Can you clarify what is your question or issue?

**Comment by GanZhiXiong** [comment]
For details, you can see another issue I proposed:
https://github.com/dart-lang/sdk/issues/38477#issue-495609751

Thanks！

**Comment by GanZhiXiong** [comment]
Dart2js can't Dart a single Dart file as a js file?

**Comment by sigmundch** [comment]
Ah, I see, thanks for the pointer and clarification. 

Short answer, dart2js cannot compile individual files, but the dartdevc compiler is modular and may be what you are looking for. I replied on the other bug with a lot more details. I'm closing this issue as a duplicate so we can keep the conversation on the other bug (#38477)

Cheers!
