### ISSUE TITLE
front_end package is missing dependency on `meta` package.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#38483]
https://pub.dev/packages/front_end/versions/0.1.24#-analysis-tab-

This is causing build failures for the build package tests https://github.com/dart-lang/build/issues/2450.

This is also likely causing other real world failures - anything using `build_vm_compilers` that has a transitive import to front_end will not work.

see also https://github.com/dart-lang/sdk/issues/38482

**Comment by jakemac53** [comment]
cc @stereotype441 @bwilkerson who I understand are familiar with the release process here.

Fwiw pub should be giving a warning when attempting to publish these packages already as well. We should probably turn that into an error cc @jonasfj .

**Comment by jakemac53** [comment]
Sent out https://dart-review.googlesource.com/c/sdk/+/118320 but that change also needs to be published.

**Comment by stereotype441** [comment]
https://dart-review.googlesource.com/c/sdk/+/118320 has landed and is now published in front_end version 0.1.26.
