### ISSUE TITLE
Analyzer does not issue an error when operators [] and []= come from different extensions.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38484]
The example below should have an error for both the invocation `a.x++` and `a[0]++`, since both are equally ambiguous (we resolve invocations by basename).  The analyzer currently only issues an error for the setter/getter pair, but not the operator[] example.

cc @stereotype441 @lrhn @aadilmaan 

```dart
class A {}

extension E1 on A {
  int operator[](int index) => 0;
  int get x => 0;
}

extension E2 on A {
  void operator[]=(int index, int value) {}
  void set x(int _) {}
}


void main() {
  var a = A();
  a.x++;
  a[0]++;
}
```

**Comment by stereotype441** [comment]
@scheglov would you mind taking a look?

**Comment by scheglov** [comment]
I don't see in the extension methods spec if `[]` and `[]=` are paired like getters and setters.
I see the test, and it implies that they are, but a reference to the spec would be nice :-)

**Comment by lrhn** [comment]
The specification probably doesn't say that yet, but we are trying to nail down all the places where it treats setters and getters as completely unrelated, and that should be made to include the `[]` and `[]=` operators.

The currently (pending) version of [static extension methods](https://github.com/dart-lang/language/pull/537/files#diff-f481d2d4d1fb2735b0998524e4871fc1R146) took a shortcut to this and specified it directly. The "basename" of the instance member invocation `o[i]=e` is defined as `[]`, and everything with extension lookup is based on basenames.

**Comment by leafpetersen** [comment]
> Also, should this pairing be done for non-extension operators `[]` and `[]=`?
> I.e. is this an error because `B.[]` prevents us from using `A.[]=`?

To your second question, as best I know, we don't intend to prevent setter/getter pairs (including operator[]) to be defined in different parts of the inheritance/mixin chain.  So the example [here](https://github.com/dart-lang/sdk/issues/38484#issuecomment-533353659) should continue to work.

**Comment by leafpetersen** [comment]
Tests updated to test `[]` and `[]=` pairings [here](https://dart-review.googlesource.com/c/sdk/+/118366).

**Comment by eernstg** [comment]
@lrhn wrote:
> The specification probably doesn't say that yet,

Actually, we do have [this](https://github.com/dart-lang/language/blob/88eda0082df640babe75bc02842dd8b390dc18e4/specification/dartLangSpec.tex#L2133):

> Operators are instance methods with special names,
> except for operator `[]` which is an instance getter
> and operator `[]=` which is an instance setter.

and

> The basename of an operator named `n` is `n`,
> except for operator `[]=` whose basename is `[]`.

**Comment by lrhn** [comment]
@eernstg Excellent! :raised_hands:.

**Comment by scheglov** [comment]
Some more changes, to support extension overrides and index expressions.
https://dart-review.googlesource.com/c/sdk/+/118462
