### ISSUE TITLE
Handle downcasts in nnbd migration

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38480]

**Comment by srawlins** [comment]
Is this an epic we should consider for Q4, @stereotype441 @MichaelRFairhurst ? Are users running into these issues today?

**Comment by stereotype441** [comment]
I would be comfortable closing this.  I have seen one or two issues arise with downcasts, but they're rare enough that I think it is better to fix them as they arise rather than try to cover all the cases.
