### ISSUE TITLE
CFE does not issue an error on ambiguous uses of operators [] and []=

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38485]
I realize that support is still in progress, but just to make sure that this is on the radar, since this case doesn't seem to be tested (I will fix that).

The example below should have an error for both the invocation `a.x++` and `a[0]++`, since both are equally ambiguous (we resolve invocations by basename).  The CFE currently issues no errors.

cc @johnniwinther  @lrhn @aadilmaan 

```dart
class A {}

extension E1 on A {
  int operator[](int index) => 0;
  int get x => 0;
}

extension E2 on A {
  void operator[]=(int index, int value) {}
  void set x(int _) {}
}


void main() {
  var a = A();
  a.x++;
  a[0]++;
}
```

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/118940
