### ISSUE TITLE
Analyzer does not recognize nullable function-syntax parameters.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#38495]
Example:
```dart
main() {
 funcup();
}
void funcup([int foo(int)?]) {
}
```
gives the error
```
Analyzing funcup.dart...
  error • The parameter 'foo' can't have a value of 'null' because of its type, so it must either be a required parameter or have a default value. • funcup.dart:4:18 • missing_default_value_for_parameter
1 error found.
```
It should not say that because the parameter *is* nullable.

**Comment by scheglov** [comment]
This has been fixed as https://github.com/dart-lang/sdk/issues/38811 in e221f83febb696841d43d5668f9c799c70210981.

![image](https://user-images.githubusercontent.com/384794/67592556-e3840f00-f714-11e9-9659-a70e70ea8ba5.png)
