### ISSUE TITLE
[ask] how to use log(x) with base number 

### ISSUE THREAD

**Issue by cacing69** [dart-lang/sdk#38519]
i have a new on dart programming, so i need to use this function on my program to find log() with base number 

so for example on php, i used like this
![image](https://user-images.githubusercontent.com/36250619/65407490-e84f5d80-de0c-11e9-9597-2597cf118e59.png)
[PHP log() function](https://www.javatpoint.com/php-math-log-function)
how can i solve this on dart ?

**Comment by lrhn** [comment]
Dart does not currently have an arbitrary base logarithm function, only base *e* (`log`). This is most likely inherited from JavaScript, which also only provides these two.

In general, the logarithm at one base, *b*<sub>1</sub>, can be found using the logarithm at any other base, *b*<sub>2</sub> as *log*<sub>*b*<sub>1</sub></sub>(*x*) = *log*<sub>*b*<sub>2</sub></sub>(*x*) / *log*<sub>*b*<sub>2</sub></sub>(*b*<sub>1</sub>).

So, to find the base-10 logarithm of 5 using only the natural logarithm (base *e*), you can write `log(5)/log(10)`. The constant `log(10)` is available as `ln10`, so it can also be written `log(5)/ln10`.

If it happens often, you can define your own functions:
```dart
double logBase(num x, num base) => log(x) / log(base);
double log10(num x) => log(x) / ln10;
```

**Comment by cacing69** [comment]
Thanks you very much for explanation @lrhn

**Comment by cacing69** [comment]
@lrhn So if i want to chane base to 1000 just make
```
double log1000 =  log(9000) / log(1000)
```

**Comment by lrhn** [comment]
That should compute `log_1000(9000)`. You can see that the result changes by 1 when you change the `9000` value by a factor of 1000:
```dart
print(log(9000) / log(1000)); // 1.3180808364797751
print(log(9000000) / log(1000)); // 2.318080836479775
print(log(9) / log(1000)); // 0.318080836479775
print(pow(1000, log(9000) / log(1000)); // 9000.000000000011
```
That is the correct behavior for a base-1000 logarithm (with a little rounding).

**Comment by cacing69** [comment]
Ahh thank you , now i can understand
