### ISSUE TITLE
dart2native has unneeded output

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38524]
We currently produce a fair amount of status output:

```
$ dart2native hello.dart
Generating AOT kernel dill.
Generating AOT snapshot.
Generating executable.
Marking binary executable.
Generated: /Users/mit/tmp/hello.dart.exe
$
```

I suggest that we remove anything but the last line from the standard output. If there is a reason to keep it, I suggest we put it behind a `-v, --verbose` flag like other Dart commands.

**Comment by cskau-g** [comment]
This is now fixed in [0b7a78d](https://dart.googlesource.com/sdk/+/0b7a78d0a611c3b5e2f9e1dc2e85579d4f6f2562#).
