### ISSUE TITLE
Remove --disable-service-auth-codes and --disable-service-origin-check

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#38527]
Now that authentication codes have been enabled for the VM service by default for a few months now, we should remove `--disable-service-auth-codes` and `--disable-service-origin-check` and require that all connections to the VM service use an authentication code. We'll need to go through the Flutter and Dart test infrastructure to remove the usage of these flags and handle authentication codes properly. This should be easier to do now that https://github.com/dart-lang/sdk/issues/38418 has been resolved, making it possible to avoid scraping stderr for the VM service URI.

**Comment by leonsenft** [comment]
Just ran into this issue trying to remote debug from IntelliJ. It still doesn't support adding the authentication code (or any kind of path for that matter). We probably want to make sure all of the tools have support for this before removing the flags.

https://www.jetbrains.com/help/idea/run-debug-configuration-dart-remote-debug.html

**Comment by bkonyi** [comment]
@devoncarew do you happen to know if there's any plan to get IntelliJ up to speed with respect to authentication codes? We should do that sooner than later since we do plan to remove this flag in the near future.

**Comment by alexander-doroshko** [comment]
@leonsenft @bkonyi I've filed an issue in the JetBrains issue tracker: https://youtrack.jetbrains.com/issue/WEB-43245. This is where we track requests related to the Dart plugin. It will be fixed ASAP.

**Comment by dnfield** [comment]
FWIW, this flag is extremely helpful when doing local debugging that requires frequently restarting the application, particularly when you need to start it from Xcode .

**Comment by bkonyi** [comment]
At this point, I highly doubt these flags will be removed as they have proven to be useful. I'll close this issue for now and re-open if we decide to revisit this decision later.
