### ISSUE TITLE
Allow building Android x86 JIT artifacts using x64 gen_snapshot.

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/sdk#38537]
Toolchain support for building and running `i386` host executables is rapidly vanishing. 

Historically, an `i386` variant of `gen_snapshot` on the host has been required in order generate artifacts that are consumed by (or embedded in) `armv7` or `i386` targets.

On the Mac, due to addition of restrictions to running `i386` binaries on Catalina, [an effort was undertaken](https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%E2%80%8E%E2%80%8D%F0%9F%92%BBplatform-catalina+) to enable the use of `x64` host binaries to generate artifacts `armv7` targets.

However, the Android `x86` configuration was also affected by this issue. Since Flutter never supported Android `x86` AOT builds, those variants were not affected. However, x86 JIT builds still needed support. We achieved this by dropping support for locally building the x86 Flutter engine on a Mac. An end user testing on an x86 emulator would download Android artifacts on the cloud built with Linux builder.

It is now apparent that Linux toolchain support for i386 builds is also becoming poorer and on its way out. Already, internally in Google, no variant of x86 Android can be built because of host binary restrictions (instead, those target depend on artifact drops from the OSS side). On the OSS side, maintaining an entire toolchain for the sole purpose of building a binary that generates intermediate artifacts (that never ends up in any artifact bucket) is getting burdensome.

We would like to support all targets (Android/iOS with x86,x64,armv7,aarch64) without needing i386 toolchains if possible.

**Comment by chinmaygarde** [comment]
@a-siva suggested that a possible solution could be not to provide core snapshots on x86. However this would adversely affect (startup performance) https://github.com/flutter/flutter/issues/9253 which is a "JIT-as-Release" effort.

**Comment by aam** [comment]
cc @mehmetf regarding recent investigation into using x86 emulator for testing.

**Comment by chinmaygarde** [comment]
Based on further discussions with @a-siva, the guidance is to switch to using x64 host `gen_snapshot` binaries to generate core snapshots for Android `x86`. This support was apparently still in place pending a patch from @rmacnak-google. Ryan is now holding off on landing said patch so that support for the requested configuration can remain.

Work items:
[ ] @jason-simmons is going to switch to using x64 host binaries on Linux.
[ ] @chinmaygarde  is going to re-enable the previously disabled local engine development workflow on Catalina Macs with Andriod `x86` targets.
[ ] @chinmaygarde is going to remove all support for building with i386 toolchains on either Linux or Mac.

This should unblock further upgrades to the compiler and toolchain that have been stalled due to poor i386 toolchain support. Thanks for the quick resolution everyone!

**Comment by mehmetf** [comment]
This is great news, Chinmay. @rmacnak-google had told me that it would take months to support x86 from x64 `gen_snapshot` binaries. If we can support a "simx86_x64" mode, that would solve all internal problems as well.

**Comment by rmacnak-google** [comment]
To clarify, AppJIT or AppAOT support for IA32 would take months. The plan here is to keep the plain core snapshots portable (sigh) so that a "simia32_x64" is not needed, and to run the JIT from kernel files.

**Comment by jason-simmons** [comment]
I tried building `gen_snapshot` as an x64 binary in a Flutter `android_debug_unopt_x86` build.

This can be done by patching the `flutter/tools/gn` script to not override the `host_cpu` when the target CPU is x86 (see https://github.com/flutter/engine/blob/master/tools/gn#L197)

However, Dart will not build if the host architecture is 64-bit but the target architecture is 32-bit:
    https://github.com/dart-lang/sdk/blob/master/runtime/platform/globals.h#L344
(with the exception of simarm_x64 mode)

Disabling this check reveals various places in `il_ia32.cc`/`assembler_ia32.cc`/`disassembler_x86.cc`/etc. that assume a 32-bit host.

**Comment by mehmetf** [comment]
FWIW, we were working around this internally by *not* setting a TARGET_ARCH copt at all. It is terrible (and it broke when Ryan originally rolled his patch that broke word compatibility) but yes, as you point out, if you set ia32 arch on a x64 binary, it barfs.

**Comment by a-siva** [comment]
Assigning issue to self, At this point no work is needed from our side other than holding off on landing @rmacnak-google CL https://dart-review.googlesource.com/c/sdk/+/117291.

@chinmaygarde @jason-simmons please let us know if you run into issues with the current strategy.

**Comment by jason-simmons** [comment]
I was able to build the Flutter engine for an android_x86 target with an x64 gen_snapshot binary by:
  * setting `dart_host_sdk_toolchain = "//build/toolchain/linux:clang_x64"`
  * changing the `//flutter/lib/snapshot:generate_snapshot_bin` target to depend on the `//third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/linux:clang_x64)` executable

The resulting build of gen_snapshot does not set a `TARGET_ARCH` macro, but that does seem to cause any problems.

**Comment by a-siva** [comment]
I believe with https://dart-review.googlesource.com/c/sdk/+/119205 we now have support for building a core snapshot was use with android_x86 target
