### ISSUE TITLE
Allow Map.remove() for missing keys

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#38540]
It would be useful to add a special case to `UnmodifiableMapMixin` *et al* to allow the `remove()` method to be called in a way that wouldn't modify the underlying map in the first place. This wouldn't violate unmodifiability, and it would allow const empty maps to be used in situations where `remove()` is the only modifying operation in use.

This is coming up in Dart Sass. We have a map of overridden variable names to values, and we want to remove an override when it's used. We want to use a constant empty map for the common case of no overrides being declared, but that currently requires awkward extra logic when removing a key to work around the fact that `Map.remove()` won't work (even though the const map is empty and so `remove()` could never modify it).

**Comment by lrhn** [comment]
We chose to make unmodifiable objects throw on any *potentially* modifying operation, even if some operations may not change anything at all, for a number of reasons:
* It's *easier*. We don't have to simulate the operation to figure out whether it changes anything. Users of `UnmodifiableMapMixin` won't need to change `remove` depending on the contents of their map.
* It's *simple*. Users don't have to consider whether some operation is safe or not, and we don't have to draw a semi-arbitrary line somewhere. Is calling `clear` OK for empty collections? Is setting length to the current length safe for lists? Is adding an existing element OK for sets. Is setting a list element or map value to *the same* value OK?

I don't want to carve out an exception for just `Map.remove`. If there is no simple and consistent rule that can delineate the allowed operations in general, I prefer to stay with the current simple and consistent rule: You can't call potentially modifying members on unmodifiable objects - they simply do not have a useful implementation for that method at all.

In this case, you can perhaps use a single shared empty non-constant map. If you are sure that removal is the only operation used, it should be safe. Or create your own empty const set from one of the classes in `package:collection`, like:

```dart
class SassEmptySet<T> extends EmptyUnmodifiableSet<T> {
  const SassEmptySet();
  void remove(Object key0) {};
}
```
or
```dart
class SassEmptySet<T> extends DelegatingSet<T> {
  const SassEmptySet() : super(const <Null>{});
  void remove(Object key) {}
}
```

**Comment by lrhn** [comment]
No plans to change current behavior.
