### ISSUE TITLE
memory leaks in 2.6.0-dev.2.0

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#38553]
The latest dev SDK started causing [timeouts](https://travis-ci.org/dart-lang/build/jobs/589078538) for the package:build travis build bots.

When diagnosing locally I noticed that the memory usage of the test runner has gone up by approximately 6x (for the same version of the package) so I believe something has happened in the SDK.

Repro instructions:

```
git clone git@github.com:dart-lang/build.git
cd build/build_runner
pub upgrade
pub run test -t integration --total-shards 4 --shard-index 1
```
In the latest stable sdk (2.5.0) I see the main test process using <1GB of ram, in the latest SDK (2.6.0-dev.2.0) I see it using >6GB of ram.

**Comment by jakemac53** [comment]
Note that I haven't yet been able to create an isolated repro for this - it doesn't appear to be a general issue with isolates as far as I can tell which was my first intuition.

We do also create a lot of sub-processes so that could be related.

**Comment by vsmenon** [comment]
@a-siva @mraleph - it appears something between dev.1.0 and dev.2.0 is breaking testing on travis, at least for big tests.  Adding to D26.

**Comment by jakemac53** [comment]
I did figure out how to hook observatory in fwiw - if you check out the [test](git@github.com:dart-lang/test.git) repo you can run it directly, but you need to pass the `.packages` file explicitly as well. Updated instructions:

```
git clone git@github.com:dart-lang/build.git
git clone git@github.com:dart-lang/test.git
cd build/build_runner
pub upgrade
dart --packages=.packages --observe ../test/pkgs/test/bin/test.dart -t integration --total-shards 4 --shard-index 1
```

**Comment by a-siva** [comment]
I was trying to reproduce the problem, i tried using the instructions above on
Dart 2.5.0-edge.4b207266a7001f4f1e98ff1010f0df55a890d061 

While the tests are running I see 'top' reporting the following numbers for the process


PID       COMMAND      %CPU  TIME       #TH   #WQ  #PORT MEM      PURG   CMPRS  PGRP
46219  dart                   0.0       02:12.28 23      0        50         6281M  0B        399M     46219

The memory usage reported is about 6GB. When looking through observatory also I find similar
numbers
pid	46219
peak memory	6.0GB
current memory	5.8GB

Not sure if memory usage has increased between 2.5.0 and 2.6.0.

**Comment by a-siva** [comment]
Can you run an individual test and compare the times it takes to finish between
2.6.0-dev.1.0 and 2.6.0-dev.2.0
I am wondering if the timeouts might be a result of
[https://github.com/dart-lang/sdk/commit/31996aa24fc4cba80582f3f858bf8fb90b47d726](https://github.com/dart-lang/sdk/commit/31996aa24fc4cba80582f3f858bf8fb90b47d726) enabling bytecodes be default.

**Comment by jakemac53** [comment]
Is there a way I can try enabling/disabling the bytecodes by default to see if that is the problem?

**Comment by alexmarkov** [comment]
@jakemac53 you need to rebuild Dart SDK in order to disable bytecode by default. Either revert 31996aa24fc4cba80582f3f858bf8fb90b47d726 or use the following commands to build Dart SDK in `out/ReleaseX64`:

```
rm -rf out
tools/gn.py -m release -a x64 --no-bytecode
tools/build.py -m release -a x64 create_sdk
```

**Comment by rmacnak-google** [comment]
According to --print-metrics, the kernel service has a 6.7GB heap with bytecode on, and a 923MB heap with bytecode off.

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/118902 brings `heap.old.capacity.max` of `kernel-service` down to `3.478 GB`.

**Comment by a-siva** [comment]
@jakemac53 any updates on whether you were able to try out your test with byte codes disabled and can you also try by patching the CL that Alex has provided.

**Comment by alexmarkov** [comment]
There is actually a memory leak when bytecode is used.

In CFE, there is a global variable `globalDebuggingNames` (in `pkg/kernel/lib/text/ast_to_text.dart`) which accumulates AST nodes when toString() is called from a node. AST nodes are strongly connected (due to parent pointers), so holding one AST node means the whole AST for a `Component` is leaked.

Bytecode generator uses `Expression.getStaticType` a lot, which calls `Expression.getStaticTypeAsInstanceOf`, which sometimes calls `toString()` from AST node when it throws an error (these crashes are tracked in https://github.com/dart-lang/sdk/issues/34496 and bytecode generator has a workaround to catch them). A side-effect of calling `Expression.getStaticType` is that the whole AST is leaked.

https://dart-review.googlesource.com/c/sdk/+/118914 saves/restores `globalDebuggingNames` around bytecode generation and brings down `heap.old.capacity.max` of `kernel-service` to 1.043 GB in this case.

**Comment by jakemac53** [comment]
It sounded like @rmacnak-google was able to repro it so I didn't try it myself.

I don't know of any way to run a custom sdk build on travis - it only supports pointing at some released channel.

**Comment by jakemac53** [comment]
Thanks @alexmarkov for the investigation/fix!

**Comment by a-siva** [comment]
Can you try your test again to see if you still see timeouts after this fix?

**Comment by jakemac53** [comment]
https://travis-ci.org/dart-lang/build/jobs/590056649
https://travis-ci.org/dart-lang/build/jobs/590056650
https://travis-ci.org/dart-lang/build/jobs/590056651
https://travis-ci.org/dart-lang/build/jobs/590056652

**Comment by jakemac53** [comment]
Gah, looks like dartfmt is broken in the latest build, cc @munificent https://travis-ci.org/dart-lang/build/jobs/590056627.

I can restart with only the integration tests running on the absolute latest.

**Comment by jakemac53** [comment]
It looks like we are no longer timing out. The tests were still consistently slower overall, compare:

https://travis-ci.org/dart-lang/build/jobs/590054327
https://travis-ci.org/dart-lang/build/jobs/590054328
https://travis-ci.org/dart-lang/build/jobs/590054329
https://travis-ci.org/dart-lang/build/jobs/590054330

to:

https://travis-ci.org/dart-lang/build/jobs/590061915
https://travis-ci.org/dart-lang/build/jobs/590061916
https://travis-ci.org/dart-lang/build/jobs/590061917
https://travis-ci.org/dart-lang/build/jobs/590061918

I would definitely consider us unblocked though.
