### ISSUE TITLE
 Why is my ML Complete not working?

### ISSUE THREAD

**Issue by Rabbit95** [dart-lang/sdk#38555]
## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1080x1920`

![image](https://user-images.githubusercontent.com/34308208/65565105-85cb9e00-df81-11e9-9e99-0e2f9278c246.png)

**Comment by mit-mit** [comment]
cc @lambdabaa

**Comment by lambdabaa** [comment]
@Rabbit95 Close! It's actually `--enable-completion-model`, the dashes are required.

**Comment by Rabbit95** [comment]
> @Rabbit95 Close! It's actually `--enable-completion-model`, the dashes are required.

Please don't close. `--enable-completion-model` It will cause another error. I am in China, it is now at 12 o'clock in the morning, I will upload a screenshot of the error after 8 hours.
