### ISSUE TITLE
Please merge 12c1b4336589eb31fe919b78c5b3999ab1eb3bae into stable channel

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38567]
**commit(s) to merge**: 12c1b4336589eb31fe919b78c5b3999ab1eb3bae

**merge instructions**: patch CL: https://dart-review.googlesource.com/c/sdk/+/118660

**reason**: Prevents type inference failures in the analyzer.  See https://github.com/dart-lang/sdk/issues/38365.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by stereotype441** [comment]
Note: I examined the trybot failures and I believe it is safe to land this.

**Comment by mit-mit** [comment]
Thanks Paul! Alex, lets do it.

**Comment by athomas** [comment]
Yes, this release will go out today or tomorrow.

**Comment by athomas** [comment]
Released with 2.5.1.
