### ISSUE TITLE
Analyzer: remove uses of Element.type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38566]
Filing this issue to track work that @scheglov currently has in progress.

Notes:
- Need to stop using LazyFunctionType but it’s needed by InheritanceManager2.  We migrated all users from InheritanceManager2, but it’s still a breaking change to get rid of it.
- We can't safely remove Summary1 yet due to some outstanding issues being discussed in https://github.com/dart-lang/build/issues/2451
- A lot of changes have been added to breaking changes CL.  We can still make more changes, e.g.:
  - Remove isMoreSpecificThan
  - Workarounds with using old subtype checks for constant types.

**Comment by srawlins** [comment]
Should this be closed? summary1 was deleted.

**Comment by scheglov** [comment]
No, this is not done yet.

There are [pending breaking changes](https://dart-review.googlesource.com/c/sdk/+/123622) that I'd like to land eventually. But there are still internal users, specifically Angular analyzer plugin, which I don't know how to fix.

**Comment by scheglov** [comment]
The CL with breaking changes was landed.
So, we are done.
