### ISSUE TITLE
NNBD Migration: Consider adding a "preview" mode to the migration tool

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38573]
It's beginning to seem like the workflow for running the migration tool might look something like:
1. Try running a migration.
2. Examine the results.  If no problems are discovered, commit the result; migration is finished.
3. (Problems were discovered) Revert the migration.
4. Make a preliminary change to try to give the migration tool more information (e.g. add an `assert(x!=null)` or a `/*?*/` or `/*!*/` to the source code).
5. Commit the preliminary change.
6. Go back to step 1.

A naive user might skip step 5, in which case when they iterate and get to step 3, there is a big risk that they will accidentally revert their preliminary change, and then need to waste a lot of time trying to recreate it.

It might be better if the migration tool had a "preview" mode where the user could see what changes it plans to make, but those changes are not yet written to disk.  Then the workflow would be more like this:
1. Run a migration preview.
2. Examine the results.  If no problems are discovered, tell the migraton tool to go through with the migration; commit the result; migration is finished.
3. (Problems were discovered) Make a preliminary change to try to give the migration tool more information.
4. Go back to step 1.

Since there is no longer any need for a revert step, there would be no danger of the revert accidentally destroying any diffs the user wanted to keep.

As a follow-up, we might consider automating some of the preliminary changes, so that the user could use a single click to e.g. add `/*!*/`, re-run migration, and see the new result.  We might even consider offering a "delta preview" mode that shows the user how the migration would change *if* they make the single-click change.

**Comment by stereotype441** [comment]
@srawlins FYI (since we discussed this idea in our meeting yesterday)

**Comment by lrhn** [comment]
This could be handled by providing the tool with the option of not overwriting the existing file, but perhaps saving it as `originalFileName.dart.nnbd` or `originalFileName_nnbd.dart` (or let the user choose the name mangling somehow).
Then the user can check the delta by running diff, and a wrapper script or editor can show the difference in whatever way they want, and perhaps ask "make change (Y/N)?" at the end and copy the file on yes.

Adding user interaction to the migration tool itself would be less flexible than just providing the data and let someone else build whatever interaction they like around it. (I'll probably have a script which parses the output of the migration script, then feeds the file names of the original and modified files into [meld](https://meldmerge.org/))

**Comment by srawlins** [comment]
This mode has been written and UX studied. We will continue to improve it.
