### ISSUE TITLE
New flaky crash of 'language_2/covariant_test/37'

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#38571]
This test is expected to produce a compile-time error, but has (flakily) crashed on `dartk-optcounter-linux-release-ia32`:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901399150148309184/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0

I didn't paste the logs here because the stacktrace is useless.

**Comment by sjindel-google** [comment]
Since the code produces a compile-time error, it seems that the crash must involve execution of the CFE.

**Comment by sjindel-google** [comment]
I could not reproduce after 800 runs.

**Comment by alexmarkov** [comment]
Both `language_2/covariant/covariant_test` and `language/covariant/covariant_test` are currently passing on all configurations and not flaky.
