### ISSUE TITLE
Analyzer: Make a common interface for promotable elements, and use it in flow analysis integration

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38572]
Two kinds of elements that are subject to type promotion: `LocalVariableElement` and `ParameterElement`.  These two element classes share the common interface `VariableElement`, so accordingly the code that integrates flow analysis with the analyzer uses `VariableElement` to represent promotable elements.  This is dangerous, though, because `FieldElement` and `TopLevelVariableElement` also implement `VariableElement`, so there is a danger that we will accidentally try to apply type promotion to them.

It would be safer if we had a common interface implemented only by `LocalVariableElement` and `ParameterElement`.  `LocalElement` comes close, but it is also implemented by `FunctionElement`, and we don't want that to be promotable.

Once we make a new interface to represent promotable things, we should update the flow analysis integration both in the analyzer and in the NNBD migration tool to use the new interface instead of `VariableElement`.

**Comment by bwilkerson** [comment]
Are you envisioning a public or private interface?

Also, an alternative would be to introduce an `isPromotable` getter on `VariableElement`. Such a getter would be consistent with `FunctionBody.isPotentiallyMutatedInClosure`.

**Comment by stereotype441** [comment]
> Are you envisioning a public or private interface?

I would prefer for it to be public.  What I was envisioning was that the new interface would be empty and would implement LocalElement; we would change ParameterElement and LocalVariableElement so that they implemented the new interface rather than implementing LocalElement directly.  So I believe there would be no visible change to clients.

(We *could* make it a private interface but IMHO there's a nice benefit to making it part of the public API because there's a natural affinity between ParameterElement and LocalVariableElement that a customer might want to take advantage of via a shared interface)

> 
> Also, an alternative would be to introduce an `isPromotable` getter on `VariableElement`. Such a getter would be consistent with `FunctionBody.isPotentiallyMutatedInClosure`.

That wouldn't carry the same safety benefits, though, since we would have to remember to call `isPromotable` at all the right times, whereas with a common interface the type system would help us ensure that we aren't trying to promote non-promotable things.
