### ISSUE TITLE
Adding support for RISC-V architecture

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/sdk#38587]
Do you have plans to add support for [RISC-V](https://en.wikipedia.org/wiki/RISC-V)/RISC 5 architecture on Linux.
RISC-V is currently gaining momentum and dart can be one of the first programing languages to add support for it.

**Comment by fw-brice** [comment]
If anyone is working on supporting RISC-V, I'd like to invite you to join the [RISC-V Managed Runtimes SIG](https://lists.riscv.org/g/sig-managed-runtimes). Our goal is to bring together all of the various groups working on managed runtimes on RISC-V to help with coordination and knowledge sharing. You can find the full charter of the group [here](https://github.com/riscv/groups/blob/main/Managed-Runtimes/CHARTER.md).

**Comment by Areopagitics** [comment]
It would be really nice to get Dart working so that we can get Flutter on the RISC-V architecture, now that [Ubuntu 21.04](https://wiki.ubuntu.com/RISC-V) is out for the riscv64 HiFive Unmatched. It would streamline building apps for the RISC-V architecture.

**Comment by rmacnak-google** [comment]
There's some edge cases in FFI that still fail, but this is basically working now.
