### ISSUE TITLE
Analyzer gives incorrect type for extensions with NNBD.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#38584]
Example:
```dart
extension<T extends Object?> on T {
  R on<R>(R convert(T value)) => convert(this);
  void log() {
    print("LOG: Object ${this}: ${this.runtimeType}, static type: $T");
  }
}

main() {
  [1]..on((it) {
   if (it[0] == 0) return null;
   if (it[0].isEven) it.add(it[0]);
   return it;
  })?.log();
} 
```
give the following error with `--enable-experiment=extension-methods,non-nullable`:
```
Analyzing errcast.dart...
  error • The argument type 'Object?' can't be assigned to the parameter type 'T'. • errcast.dart:2:42 • argument_type_not_assignable
  error • The return type 'Null' isn't a 'List<int>', as defined by anonymous closure. • errcast.dart:10:27 • return_of_invalid_type_from_closure
  error • The target expression can't be null, and so '?.' isn't necessary. • errcast.dart:13:5 • unnecessary_null_aware_call
3 errors found.
```
The first error is reported elsewhere, but the analyzer apparently infers `List<int>` as the return type of the `on` call, and not `List<int>?` as it should (or `Object?` if it can't infer anything).
This shows as the other two errors - cannot return `null` from the function body, and can't use `?.` on the result.

There is no good reason to infer `List<int>` as the return type. There are two returns, one of type `List<int>` and another of type `Null`. If you look at both, you can't infer `List<int>`, and if you look at neither, you will just have to instantiate `R` to bounds. Looking at only *one* of them is probably not happening, so the error is likely in the LUB computation between `Null` and `List<int>`.

**Comment by scheglov** [comment]
Please update https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#upper-and-lower-bounds.

**Comment by leafpetersen** [comment]
I believe this is now fixed.
