### ISSUE TITLE
[vm/ffi] Fix --enable-ffi=false

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38591]
Our [test](https://github.com/dart-lang/sdk/blob/master/tests/ffi/enable_ffi_test.dart) testing whether the flag works has a bug, it triggers a compile error but not because of the flag.

Fixing the compile error makes the test succeed, even with `--enable-ffi=false`.

/cc @sjindel-google

**Comment by sjindel-google** [comment]
This is probably because the check for imports of "dart:ffi" which enforces the flag is performed in the Kernel FE, not the KBC FE.

**Comment by dcharkes** [comment]
<details>
 <summary>It indeed looks like that the frontend does not pass that the FFI library is used.</summary>

```c++
  if (((flags & kUsesDartFfiFlag) != 0) && !Api::IsFfiEnabled()) {
    H.ReportError(
        "import of dart:ffi is not supported in the current Dart runtime");
  }
```
runtime/vm/compiler/frontend/bytecode_reader.cc

`flags` is 0.

It should be set here:

```dart
    for (var dependency in library.dependencies) {
      final targetLibrary = dependency.targetLibrary;
      assert(targetLibrary != null);
      if (targetLibrary == coreTypes.mirrorsLibrary) {
        flags |= LibraryDeclaration.usesDartMirrorsFlag;
      } else if (targetLibrary == dartFfiLibrary) {
        flags |= LibraryDeclaration.usesDartFfiFlag;
      }
    }
```

pkg/vm/lib/bytecode/gen_bytecode.dart

</details>

@alexmarkov what Dart script do I invoke to run `gen_bytecode.dart` to verify if it sets the `usesDartFfiFlag`?

**Comment by alexmarkov** [comment]
Currently bytecode generator is used in kernel service of standalone VM by default. You can add debug prints into gen_bytecode.dart, rebuild Dart SDK and see what's printed when you run the test using `dart` command.

Also, you can build a dill file with bytecode, run it and dump it:
```
pkg/vm/tool/gen_kernel --no-aot --no-link-platform --platform=out/ReleaseX64/vm_platform_strong.dill -o out.dill foo.dart --packages=.packages -Ddart.developer.causal_async_stacks=true --gen-bytecode  --drop-ast --bytecode-options=source-positions,local-var-info,debugger-stops,annotations
out/ReleaseX64/dart out.dill
pkg/vm/tool/dump_kernel out.dill out.dill.dump
```

Could you check if `dart:ffi` is indexed in `CoreTypes.index` ? Maybe

https://github.com/dart-lang/sdk/blob/a46bb7cb5ade4a0b9ebbec84d4006554cd5618a2/pkg/vm/lib/bytecode/gen_bytecode.dart#L996-L997

returns `null`. `libraryIndex` is taken from CoreTypes instance:

https://github.com/dart-lang/sdk/blob/a46bb7cb5ade4a0b9ebbec84d4006554cd5618a2/pkg/vm/lib/bytecode/gen_bytecode.dart#L890

**Comment by alexmarkov** [comment]
If `dart:ffi` is used without being included into `CoreTypes.index`, then we can fix detection of `dart:fii` import in bytecode generator in the following way: https://dart-review.googlesource.com/c/sdk/+/119180. @dcharkes could you try this?

**Comment by dcharkes** [comment]
@alexmarkov thanks! Yes, `dart:ffi` was not indexed in `CoreTypes.index`.


Offtopic: For the next time I need to work with gen_bytecode.dart

> You can add debug prints into gen_bytecode.dart, rebuild Dart SDK and see what's printed when you run the test using `dart` command.

Building `create_sdk` takes like 2 minutes. Isn't there a way to run just run `dart x/y/z/gen_bytecode.dart my/dart/source_program.dart` without any compilation?

(I use `dart pkg/vm/bin/gen_kernel.dart my/dart/source_program.dart` to iterate fast and run the debugger without recompiling, when I'm working on the pkg/vm ffi transformations for example.)

**Comment by alexmarkov** [comment]
> Isn't there a way to run just run dart x/y/z/gen_bytecode.dart my/dart/source_program.dart without any compilation?

@dcharkes as I mentioned above, you can also generate a dill file with bytecode using `gen_kernel` tool if you prefer (note that `pkg/vm/tool/gen_kernel` runs `pkg/vm/bin/gen_kernel.dart` from source). Just add `--gen-bytecode` flag to generate bytecode, optionally with ` --drop-ast --bytecode-options=source-positions,local-var-info,debugger-stops,annotations` depending on your needs.
