### ISSUE TITLE
[vm/ffi] API: Struct.addressOf as extension method

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38611]
Split off https://github.com/dart-lang/sdk/issues/37773 to keep the CL sizes manageable.

> These methods would be better exposed as extension methods:
> 
> * `Struct.addressOf`

This allows us to drop the type argument from `Struct`, and the custom check that classes extending `Struct` always have themselves as a type argument.

Current API:

```dart
/// This class is extended to define structs.
///
/// Fields in a struct, annotated with a subtype of [NativeType], are
/// automatically transformed into wrappers to access the fields of the struct
/// in native memory.
///
/// All fields in a struct must either have a type which extends [NativeType] or
/// else have an annotation indicating the corresponding native type (e.g.
/// "@Int32()" for "int").
///
/// Instances of a subclass of [Struct] have reference semantics and are backed
/// by native memory. The may allocated via [Pointer.allocate] or loaded from a
/// [Pointer], but not by a generative constructor.
abstract class Struct<S extends NativeType> extends NativeType {
  /// Returns the address backing the reference.
  final Pointer<S> addressOf;

  Struct() : addressOf = null;
  Struct.fromPointer(this.addressOf);
}
```

New API:

```dart
abstract class Struct {
  final Pointer<Struct> _addressOf;
  Struct._fromPointer(this._addressOf);
}

extension StructAddressOf<T extends Struct> on <T> {
  /// Returns the address backing the reference.
  Pointer<T> get addressOf => _addressOf as Pointer<T>;
}
```

**Comment by sjindel-google** [comment]
I'm fine with disallowing generative constructors.

**Comment by mkustermann** [comment]
So the proposed changes are as follows:

* remove `Struct::T` type parameter
* remove default `Struct` constructor and only have one private `Struct._(Pointer<Struct>)` constructor
* add `extension on Struct<T> { Pointer<T> get addressOf => ...; }`
* enforce subclasses of `Struct` do not have generative constructors

Sounds good to me. If everyone is in agreement we can implement that!

**Comment by sjindel-google** [comment]
If we remove the default `Struct` constructor and have only a private constructor, then any subclasses of `Struct` will be deemed illegal by the CFE and Analyzer according to the regular Dart rules.

**Comment by mkustermann** [comment]
Then we can allow the default one but use `nullptr` instead of a `null` - which would make it a bottom and any cast would work.

**Comment by sjindel-google** [comment]
That sounds good to me.

**Comment by dcharkes** [comment]
https://dart-review.googlesource.com/c/sdk/+/121422 CL is almost ready, however new analyzer failures.

Need to triage if these failures are introduced by this CL, or whether they are already covered by @mkustermann in https://github.com/dart-lang/sdk/issues/35777.
