### ISSUE TITLE
[vm/ffi] API: Pointer.asExternalTypedData as extension method

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38610]
Split off https://github.com/dart-lang/sdk/issues/37773 to keep the CL sizes manageable.

> These methods would be better exposed as extension methods:
> 
> * `Pointer.asExternalTypedData` (but keep original)

```dart
  /// Creates an *external* typed data array backed by this pointer.
  ///
  /// The typed data array returned is only valid for as long as the backing
  /// [Pointer]. Accessing any element of the type data array after this
  /// [Pointer] has been [Pointer.free()]d will cause undefined behavior.
  ///
  /// Since [Pointer]s do not know their length, the size of the typed data is
  /// controlled by `count`, in units of the size of the native type for this
  /// [Pointer] (similarly to [Pointer.allocate]).
  ///
  /// The kind of TypedData produced depends on the native type:
  ///
  ///   Pointer<Int8> -> Int8List
  ///   Pointer<Uint8> -> Uint8List
  ///   etc. up to Int64/Uint64
  ///   Pointer<IntPtr> -> Int32List/Int64List depending on platform word size
  ///   Pointer<Float> -> Float32List
  ///   Pointer<Double> -> Float64List
  ///
  /// Creation of a [Uint8ClampedList] is not supported. Creation of a typed
  /// data from a [Pointer] to any other native type is not supported.
  ///
  /// The pointer must be aligned to a multiple of the native type's size.
  //
  // TODO(37773): Use extension methods to articulate more precise return types.
  // We should still keep this member though as a generic way to access a
  // Pointer of unknown type.
  external TypedData asExternalTypedData({int count: 1});
```

@sjindel-google how did you envision this? Instance methods shadow extension methods.

**Comment by sjindel-google** [comment]
We would change the name of the instance method to `asExternalTypedDataDynamic` or such.

**Comment by dcharkes** [comment]
(1) Using extension methods _and_ a generic method:

* pro: precise return type.
* con: API pollution with both the precise and the dynamic method.
* con: dynamic method has imprecise receiver type, throws on non-integer type arguments.

(2) Using _only_ extension methods:

* pro: precise return type.
* pro: precise receiver type.
* pro: only one (extension) method (per Pointer type argument) in the API.
* con: users (or `package:ffi`) have to write the generic one by hand if they want it.

(3) Using _only_ generic method (current situation):

* pro: only one method in API.
* con: imprecise return type.
* con: imprecise receiver type, throws on non-integer type arguments.

@sjindel-google I don't like the API pollution of option 1.

I think option 2 is a better option.

**Comment by sjindel-google** [comment]
I'm in favor or #1 or #3. The ability to manipulate a pointer generically is one of the advantages of `asExternalTypedData`.

**Comment by dcharkes** [comment]
I'm fine with option 3 as well, keeping the return type generic.

We should still move it to an extension method on `Pointer<_NativeInteger>` so that the receiver type is precise.

**Comment by sjindel-google** [comment]
Could you elaborate on your concern with two versions of `asExternalTypedData` from solution #1?

**Comment by dcharkes** [comment]
Option 1:

```dart
final Pointer<Int8> p = fromSomewhere();
final td = p.// x
```

`x`: Here we would have two methods with exactly the same functionality with slightly different names, but one with a more precise return type. I think that is confusing from a public API point of view.

Option 3b:

If a user wants the more precise return type, (s)he can always write:

```dart
final Pointer<Int8> p = fromSomewhere();
final Int8List td = p.asExternalTypedData();
```

Or option 2:

If the user wants to have a generic one, (s)he can always write a wrapper.

Both option 3b and 2 do not confuse/penalize the user that wants no generic version or no precise return type.

**Comment by sjindel-google** [comment]
> x: Here we would have two methods with exactly the same functionality with slightly different names, but one with a more precise return type. I think that is confusing from a public API point of view.

But, they don't have the exact same functionality. One is slower but can be called on a generic pointer. If the function is named like `asExternalTypedDataDynamic`, I don't see how that's confusing.

**Comment by lrhn** [comment]
I'd make the `count` argument positional instead of named.

Providing an `Int8List` (or any typed-data view) means that you can extract its `ByteBuffer` buffer and then view it as, e.g., a `Uint32List` (maybe subject to alignment?). 
Consider whether you actually want to support this. If so, this is fine. If not, maybe don't make it return an `Int8List`, just a `List<int>` which happens to truncate on store. (Do not make it an `Int8List` which throws if you extract the buffer, or give a buffer which throws on any of the `asUintXList()` methods).

Going through the buffer seems like the only way to get, say, a `Uint8ClampedList`, unless you add an extra method to `Pointer<Uint8>`.

Alternatively, you can provide a function to go directly to the buffer:
```dart
Pointer<Int8> p = fromSomewhere();
ByteBuffer buffer = p.asExternalTypedDataBuffer(count); // count * Int8.size bytes of buffer.
Int8List list = buffer.asInt8List();
// perhaps with shorthand:
Int8List alsoList = p.asExternalTypedDataList(count); // count elements.
````

**Comment by sjindel-google** [comment]
The ability to access the byte buffer and cast it (provided alignment is correct, which is checked) is part of the feature.

I think the question is about how to make the return type more specific by turning `asExternalTypedData` into an extension method.

**Comment by sjindel-google** [comment]
As discussed offline, we will add extension methods only to the types which support external type data, and we can add a generic version later.

**Comment by dcharkes** [comment]
Yes, option 2. And we change the name to `asTypedList`, instead of `asExternalTypedData`.

```dart
extension on Pointer<Int8> {
  Int8List asTypedList(int elements);
}

extension on Pointer<Int16> {
  Int16List asTypedList(int elements);
}

// etc
```

**Comment by dcharkes** [comment]
This has landed.

The old method still needs to be removed, but that is part of https://github.com/dart-lang/sdk/issues/38860.
