### ISSUE TITLE
Discussion: New file and format for `.packages`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#38612]
This issue is intended for *discussion* about the format of a new file to replace `.packages`

For language versioning we need to extend the information currently available in the `.packages` file. Since existing tools rely on the current file format, we will instead introduce a *new* file which will coexist with `.packages` until the latter can be phased out.

A few things have been decided:

* The file will be generated by the Pub tool along with `.packages` from information found during dependency resolution, the extra information needed for language versioning included.
* The file will contain JSON text.
* The file will be placed in the `.dart_tool` subdirectory.
* The file will have a name ending in `.json`.

The file name is not decided yet. It should signal that this is not intended for human editing, and that it is related to resolving package related information (but maybe leave room to be used for more things in the future).

The contents of the file are generally dictated by the requirements, but there are a few things left to nail down. A current proposal is posted as https://github.com/dart-lang/language/pull/591

One idea proposed there is to define "belonging to a package" wider than being resolvable through a `package:` URI, so, e.g., the `test` directory of a Pub package directory would also "belong to the package" in cases where that matters. You'd still need a way to point to the particular files that are reachable through a `package:` URI, which must all belong to the package. The alternative is to keep the current distinction between Pub package (what Pub works with) and Dart package (what Dart can reach through a `package:` URI).

Another question is what the intended scope of the file. Should other tools be able to store information in the file?

Paths in the file will likely have to be *URI* paths (or full URI references). This avoids having to consider platform specific path syntax. It does mean that tools reading the file cannot use those paths as OS paths directly, but must go through URI resolution.

**Comment by jonahwilliams** [comment]
> The file will be placed in the .dart_tool subdirectory

To clarify - does this mean that pub will by convention place the new file in the .dart_tool subdirectory, or the file must be placed there to function properly?

**Comment by lrhn** [comment]
Both, at least for automatically found files.

The code looking for the configuration file will check for `.dart_tool/filename.json` in the directory where it currently looks for `.packages`. So, an entry point in `myPkg/bin/` will look for myPkg/bin/.dart_tool/filename.json`, not find it, then check the parent dir for `myPkg/.dart_tool/filename.json` and find it, just as it does for `.packages` now.

You *can* place the file anywhere, but then you have to point to it manually with `--packages whereItis/myfile.json`. (That code will use the file contents to detect which version it is, not the extension! The JSON file must have `{` as its first non-whitespace character, the current format cannot have that).

It does mean that the SDK repo will need a `.dart_tool` directory to contain its default package configuration, which is currently just a `.packages` file in the root of the SDK directory tree.

**Comment by jonahwilliams** [comment]
Thanks for the clarification - that makes sense and should be straightforward to use.

**Comment by lrhn** [comment]
This has been implemented.
