### ISSUE TITLE
Migration tool should track type parameters lost in downcasts

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38624]
Migration tool should not make non-nullable parameters nullable in is checks

```dart
class C<A, B> extends List<A/*1*/> {}

f(List<int> a) {
  a is C<int/*2*/, bool/*3*/>;
}
```

The relationship between 1 and 2 is currently tracked, but we should also draw always -> 3.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
