### ISSUE TITLE
Migration tool should handle unbound downcast types recursively

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38626]
```
f(dynamic a) {
  a as List<List<int/*1*/>/*2*/>;
}
```

We currently only draw always -> 2, but we should also be drawing always -> 1.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
