### ISSUE TITLE
Migration tool should treat downcasts and as casts more similarly

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38622]
Migration tool should not make non-nullable parameters nullable in is checks

```dart
class C<T> {}

f(dynamic a) {
  a is C<int>;
  a as C<int>>;
  C<int> c = a;
}
```

These three lines of code share functionality and should be handled in a unified way.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
