### ISSUE TITLE
Migration tool should not make non-nullable parameters nullable in is checks

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38621]
```dart
class C<T extends int/*1*/> {}

f(dynamic a) {
  a is C<int/*2*/>;
}
```

We currently draw an edge from always to 2. That edge should be 1 to 2.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
