### ISSUE TITLE
Should Null have nullability suffix question?

### ISSUE THREAD

**Issue by derolf** [dart-lang/sdk#38623]
While fixing some bugs in https://github.com/dart-lang/sdk/pull/38614, I came across the question whether the `Null`-type should have a `nullabilitySuffix` of type `NullabilitySuffix.question`?

Proof by contradiction (LUB is least upper bound function):

- Assume that Null is not nullable. 
- That means Null and Null? are different types.
- LUB(T, Null) = T?, i.e. combining T with Null widens T to T?
- Hence, LUB(Null, Null) = Null?
- That violates LUB being reflexive which would mean that LUN(Null, Null) = Null
- Hence the assumption is wrong.

One way to solve this is defining Null = Never?.

**Comment by lrhn** [comment]
The trouble with defining `Null` as an alias for `Never?` is that `Null` is a class type with an instance. It's not an insurmountable problem, and we might even want to make `null` not be a class type (it's un-implementable already), but we'd need a new category of objects that the `null` value would belong to. Currently we only have function values and class instance values.

It's quite possible that `Never?` and `Null` are distinct types which normalize to the same type (`Null`). We just have to specify type normalization.

**Comment by derolf** [comment]
Okay, I understand that null should not be suffixed with question. Then my fix that computes LUB(T, Null) => T? in commit https://github.com/dart-lang/sdk/commit/e383e33126cc891e42d52994d64d4c03e286a5f4 is correct so far and I need to fix the inference of lambda return types which is now broken.

**Comment by derolf** [comment]
Btw it’s a bit weird that function expressions return ‘null’ implicitly when they have no return statement. ‘void’ would have been more logical.
