### ISSUE TITLE
Migration engine fails to delete unnecessary null check inside a binary logical operator

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38639]
Running the migration engine over the logging package produces the following code:
```
set level(Level? value) {
  if (hierarchicalLoggingEnabled && parent != null) {
    _level = value;
  } else {
    /* if (parent != null) {
      */ throw new UnsupportedError(
        'Please set "hierarchicalLoggingEnabled" to true if you want to '
            'change the level on a non-root logger.'); /*
    } */
    _rootLevel = value;
  }
}
```
The field `parent` is marked as being non-nullable, but the null check in the first line of the body is not removed as it ought to be.

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by stereotype441** [comment]
I think I have enough information to know what needs to be done here:
- Add logic to the `EdgeBuilder` to record whether the code following an `if` statement is dead (by consulting flow analysis).
- Add logic to the `FixBuilder` to check whether the code following an `if` statement will be dead after migration (by consulting flow analysis).
- Add logic to the `FixBuilder` to recognize that if the code following an `if` statement was not dead prior to migration, and is dead now, then the code following the `if` should be deleted.

This all depends on getting the `FixBuilder` to work, which is the subject of #38472.

**Comment by srawlins** [comment]
This has been obsoleted by the need to keep such code around for weak checking.
