### ISSUE TITLE
[NNBD] analyzer type promotion issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#38643]
```dart
test<T>(T t) {
   if (t is Object) {
     Object foo() => t;
   }
}
```
Analyzer with '`--enable-experiment non-nullable`' option produces the following output
```
dartanalyzer --enable-experiment non-nullable test.dart

Analyzing test.dart...
  error - The return type 'T' isn't a 'Object', as defined by the method 'foo'. - test.dart:3:22 - return_of_invalid_type
  hint - Unnecessary type check, the result is always true. - test.dart:2:8 - unnecessary_type_check_true
  hint - The declaration 'foo' isn't referenced. - test.dart:3:13 - unused_element
1 error and 2 hints found.
```

There are two issues here.
First, there must be no error. `T` must be promoted to `T&Object` which is subtype of `Object`, so we can return `t` here
Second,  "hint - Unnecessary type check, the result is always true. - test.dart:2:8 - unnecessary_type_check_true". According to the @eernstg "Looks like a missing update in the analyzer: It thinks that `Object` is a top type. It should only consider `Object?`, `void`, `dynamic`, and `FutureOr<T>` where `T` is a top type as top types."

dartanalyzer version 2.6.0-dev.3.0

**Comment by scheglov** [comment]
Paul fixed type parameters promotion in 8e23f76ac731e8626782f423cbcecd523a1627d4.
I will patch around the existing hint for `is Object`.
https://dart-review.googlesource.com/c/sdk/+/122700
