### ISSUE TITLE
Flutter Project gets corrupted

### ISSUE THREAD

**Issue by toastguyz** [dart-lang/sdk#38640]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

Issue:

Flutter Project files gets corrupted.

some dart files in my project gets corrupted.  i have attached screenshots here. Half of the files get corrupted. i have already deleted .idea folder, .iml files, invalidated caches and restarted android studio.

But, Not found any solution.

Can anyone please suggest me a way to solve the issue.

**Comment by parlough** [comment]
Do you by chance have any further or more recent information or perhaps live links to the screenshots you mentioned?

**Comment by mobinshaik999** [comment]
Hai 
i may be late but hope  it helps someother
1. Close android studio 
2. delete caches folder in ::  C:\Users\<USER NAME>\.AndroidStudio3.5\system 
3.open androidStudio. That's it solved my problem

**Comment by srawlins** [comment]
Closing as stale. Please open a new issue if you encounter this again.
