### ISSUE TITLE
Analyzer intermittently fails with const_eval_throws_exception on seemingly valid code.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#38659]
When I submitted https://github.com/flutter/flutter/pull/41417 to the Flutter repo, an integration test failed with an analyzer error (for that, and the following commit to the repo). The error is:
```
error • Evaluation of this constant expression throws an exception • packages/flutter/lib/src/widgets/actions.dart:35:35 • const_eval_throws_exception
```

It passes when I run it locally with `flutter analyze --flutter-repo` (the same command in the test), but it fails in this [log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvZWIzZTJmNTU5ZjI1NjNhMDg3OGQxOWJkOTk3NjI5Y2UwN2JlY2QzYwwLEgRUYXNrGICA4PrK8_4LDA) (will need to log in to [dashboard](https://flutter-dashboard.appspot.com/) to view). Here's an excerpt:
```
2019-09-26T20:45:53.728633: 
Executing: /home/linux2/.cocoon/flutter/dev/devicelab/../../bin/flutter analyze --benchmark --flutter-repo
2019-09-26T20:47:52.740588: stdout: Analyzing 3 directories...                                      
2019-09-26T20:47:52.744525: stdout: Analysis benchmark written to analysis_benchmark.json ({time: 118.138, issues: 1, missingDartDocs: 0}).
2019-09-26T20:47:52.744714: stdout: 
2019-09-26T20:47:52.749852: stdout:   error • Evaluation of this constant expression throws an exception • packages/flutter/lib/src/widgets/actions.dart:35:35 • const_eval_throws_exception
2019-09-26T20:47:52.749985: stdout: 
2019-09-26T20:47:52.760458: stderr: 1 issue found. (ran in 118.1s)
```

The code in question is similar to this:
```dart
class DoNothingAction {
  static const LocalKey key = ValueKey<Type>(DoNothingAction);
}

class DoNothingIntent extends Intent {
  const DoNothingIntent() : super(DoNothingAction.key);
}

class Intent {
  const Intent(this.key) : assert(key != null);
  static const Intent doNothing = DoNothingIntent();  // <<<< Fails here (only in test)
  final LocalKey key;
}

abstract class Key {
  const factory Key(String value) = ValueKey<String>;
  const Key.empty();
}

abstract class LocalKey extends Key {
  const LocalKey() : super.empty();
}

class ValueKey<T> extends LocalKey {
  final T value;
  const ValueKey(this.value);
}
```

Note that running the analyzer locally **passed** and so did the analyzer run on the Cirrus bots.  The one that failed (twice) was the `analyzer_benchmark` devicelab test, as well as a brief failure in my IDE that didn't come back. This points to an intermittent failure of some sort (race condition?), rather than a problem in the actual analysis.  The compiler has no problem compiling and running the affected code.

* Dart SDK Version (`dart --version`)
Dart VM version: 2.6.0-dev.3.0.flutter-327bc451f8 (Thu Sep 26 18:11:10 2019 +0000) on "linux_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux (devicelab) and macOS (IDE).

**Comment by srawlins** [comment]
The analyzer no longer reports any const_eval_throws_exception errors for the example code.
