### ISSUE TITLE
pedantic package: analysis options not recognized

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#38651]
When I open the folder for [a package I'm working on](http://github.com/timsneath/dart_console), I always get a warning on the pedantic package:
![image](https://user-images.githubusercontent.com/2319867/65894427-a1a6b980-e35e-11e9-8774-a7117febb370.png)

I have it declared in pubspec.yaml per [the instructions on the pedantic package](https://pub.dev/packages/pedantic):
![image](https://user-images.githubusercontent.com/2319867/65894535-cd29a400-e35e-11e9-8a32-5c9d2685060a.png)

And this file shows up in the Dependencies list in VSCode:
![image](https://user-images.githubusercontent.com/2319867/65894572-dfa3dd80-e35e-11e9-962b-4ccfb657016b.png)

If I delete and re-add it, the error message sometimes disappears, but it always comes back again on a subsequent folder open.

@DanTup also seems to be able to reproduce this. His comments:

> It seems like a server bug to me - I don't know why it's generating that warning (I also witnessed it vanish when I was making changes in that file, but I reloaded the project and it came back.
>
> Strangely, the file even shows up on the completion list in a .dart file confirming it's on disk (whether we should list non-Dart files here, I'm not sure!)..
![image](https://user-images.githubusercontent.com/2319867/65894750-21348880-e35f-11e9-9adb-cfeacd7488b5.png)

**Comment by srawlins** [comment]
I believe @scheglov fixed this and similar bugs recently by re-analyzing on a larger set of files (like the YAML files) etc.

**Comment by DanTup** [comment]
Not sure why I hadn't previously replied here, but in case others come across this there was some additional discussion in https://github.com/Dart-Code/Dart-Code/issues/3259 about another instance of this (or perhaps the same) which seemed to be triggered by a nested project that didn't reference the `pedantic` package.

If the same thing happens now, [the error message was improved](https://github.com/dart-lang/sdk/commit/6d763b4565765524dda8a00db92a96aea5972cbe) to include the root of the package so it's clear which pubspec/`.packages` file was being used to resolve the package URI that failed.
