### ISSUE TITLE
dartanalyzer doesn't show message from @Deprecated

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#38667]
It would be *much* more helpful if `dartanalyzer` printed the message from the `@Deprecated` annotation.

For example, running `dartanalyzer` on the following program:
```dart
@Deprecated('Use bar() instead')
void foo() {}

void main() {
  foo();
}
```
prints only:

> Analyzing deprecated.dart...
> dart --v  hint • 'foo' is deprecated and shouldn't be used at deprecated.dart:7:3 • deprecated_member_use_from_same_package
> 1 hint found.

without showing "Use bar() instead", and people must find the definition of the deprecated symbol themselves to find the recommended fix.

I am using Dart SDK Version: 2.5.1 on Linux x64.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/119780

**Comment by ThinkDigitalSoftware** [comment]
Thanks, @bwilkerson. Does this include messages showing up in tooltips and other places in the IDE or only the command-line tool?
