### ISSUE TITLE
Code completion adds "prefix0" prefix on import with hide

### ISSUE THREAD

**Issue by nbros** [dart-lang/sdk#38669]
This is probably a tricky corner case of issue #37916.

I already have the following import in my code:
```dart
import 'package:flutter/material.dart' hide Step;
```
(I hide Step from material because I already have a class named Step in my code)

When I use completion on a class from the material library, for example GestureDetector, Dart Code completes with ```prefix0.GestureDetector``` and adds the following import:
```dart
import 'package:flutter/material.dart' as prefix0;
```

**Comment by pq** [comment]
Thanks for this report @nbros.  I haven't been able to reproduce this just yet...   Are you on the latest Flutter?  Are you still seeing the issue?

**Comment by nbros** [comment]
Hello,
I tried again with the latest version from master and it works now (no superfluous prefix0).

With:
```
Flutter 1.10.15-pre.93 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3fea2838df (8 hours ago) • 2019-10-11 16:18:00 -0700
Engine • revision eed171ff35
Tools • Dart 2.6.0 (build 2.6.0-dev.7.0 965b8cb1d8)
```

Thanks

**Comment by pq** [comment]
Thanks for following up!
