### ISSUE TITLE
Build the VM using the forked NNBD SDK

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38663]
The SDK (i.e. core libraries) have been forked in the repo into sdk_nnbd. Once #38662 is done and there is a flag available in the build files to detect whether that should be used, the next step is to get the various build targets for each implementation using that flag to determine which SDK to pull from.

This issue is to do that for the VM.

**Comment by a-siva** [comment]
This issue will also track updates to the test scripts to run the VM against tests in NNBD mode and setup bots to run the NNBD sdk builds and run tests.

**Comment by munificent** [comment]
Is there still work to be done here?

**Comment by a-siva** [comment]
The build setup is done.

Migration of libraries is being tracked in separate issues and so this can be closed.
