### ISSUE TITLE
Decide what to do with CompletionDomainHandlerListTokenDetailsTest

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#38677]
It is not clear to me what this code is intended to do, or if we need it at all.
For now I will disable the test.

@lambdabaa

**Comment by bwilkerson** [comment]
The test exists to ensure that the training data used for the ML completion model is being generated the way we expect. I'm not sure we want to disable the test.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/180762
