### ISSUE TITLE
No code completion after typedef reference

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#38687]
Analysis Server doesn't provide code completion for `hashCode` after `handler` (see `SomeClass` constructor).
```
typedef Object HandlerFunc();

class SuperClass {
    SuperClass({props});
}

class SomeClass extends SuperClass {
    final HandlerFunc handler;
    
    SomeClass({this.handler}) : super(props: [handler.hashCode]);
}
```

**Comment by parlough** [comment]
I went ahead and attempted to address this issue here: https://dart-review.googlesource.com/c/sdk/+/148700/
