### ISSUE TITLE
new_with_abstract_class error message is confusing in Dart 2

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#38695]
Running `dartanalyzer` on the following code:

```dart
abstract class Foo {}

final f = Foo();
```
generates:

>   error • Abstract classes can't be created with a 'new' expression at foo.dart:3:11 • new_with_abstract_class
> 1 error found.

This is a bit confusing since I didn't use `new`.  It would be better if that were removed from the error message.

(I'm using Dart 2.5.1 on Linux x64.)

**Comment by mit-mit** [comment]
Re-opening to track some refactoring @bwilkerson suggested is still needed

**Comment by srawlins** [comment]
The analyzer now produces the following:

```
  error • Abstract classes can't be instantiated. • 38695.dart:3:11 • instantiate_abstract_class
```

when analyzing the example, at Dart 2.8.0-dev.0.0. Any refactoring still required, @bwilkerson ?

**Comment by bwilkerson** [comment]
Sorry, but I don't remember what refactoring @mit-mit was referring to.

**Comment by bwilkerson** [comment]
Now I remember. Yes, the refactoring I was talking about was done in https://dart-review.googlesource.com/c/sdk/+/126780.
