### ISSUE TITLE
NNBD migration tool incorrectly considers parameters as postdominated

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38698]
This is a pathological attempt (and its successful) to break our goal of preservation of behavior in the current design of the migration tool.

```dart
class A {
  f(int x) {
    x + 1;
  }
}

class B {
  f(int x) {
    print(x);
  }
}

void g(A a) {
  a.f(null);
}

void main() {
  g(B());
}
```

**Which nullabilities get changed**: `A.f` is made non-null, because its parameter is postdominated by a non-null assertion through calling the `+` parameter on it. This causes the call `a.f(null)` in `g` to get a `!` on the `null` literal.

**The old behavior**: This program prints "null".

**The new behavior**: The migrated program will crash.

The error here is that hard edges are added when we have a post-dominating non-null intent on a type/element. In this case, we have mistakenly drawn the conclusion that the code `x + 1` postdominates the parameter `x`. However, as shown by `main` and `g`, this is not actually the case.

`x + 1` only postdominates _the local binding of the parameter_ `x`, and does not postdominate references to the _parameter type in the signature of `A.f`_.

**Some options going forward**:

- don't draw hard edges to parameters (probably *not* what we want?)
- make null literals have something harder than a hard edge, so that the `null` literal wins over the "postdominating" use of x. This does not fully solve the problem, though, as the same problem holds for any nullable var which may hold the value null.
- make hard edge propagation stop when it sees a hard null propagation. This is like the prior option but could handle postdominated usages of nullable parameters.
- make hard edges for parameters when no overrides of that method exists (would require an additional analysis pass and miss downstream overrides)
- add some kind of edge to the graph solver where it waits to see that *all* usages of *all* methods (ie, base and overrides) for a given parameter are postdominated by a non-null usage before propagating the hard edge backwards to callers

Surely there are others that I haven't thought of.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
