### ISSUE TITLE
Change `vm-kernel-precomp-android-release-arm` to use x64 gen_snapshot to produce 32-bit arm

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38709]
As mentioned by @sjindel-google , this is what flutter does atm:
```
examples/flutter_gallery % flutter build aot --release --target-platform=android-arm -v
...
../../bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-elf

examples/flutter_gallery % file ../../bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot 
../../bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[xxHash]=c58929559abff580, stripped
```

**Comment by mkustermann** [comment]
@whesse / @athomas Could you look into this?

**Comment by whesse** [comment]
Looked at the build files with sjindel.  Didn't find any obvious solutions, don't know what determines architecture. Neither of us are familiar with them, or how they work.  Suggest asking zra or other MTV people who have written them.

**Comment by mkustermann** [comment]
It should be just figuring out what changes to `build.py` and `gn.py` and maybe the GN files to make to make it work for android.

Samir will do it :)

**Comment by mkustermann** [comment]
@sjindel-google  Can this be closed now?
