### ISSUE TITLE
NNBD migration needs to sometimes insert downcasts rather than null assertions

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38707]
Attempting to migrate:

```dart
main() {
  List<int/*?*/> x = [];
  List<int/*!*/> y = x;
}
```

Yields the result:

```dart
main() {
  List<int?> x = [];
  List<int> y = x!;
}
```

Notice that it adds a ! on x when assigned to y. This is not correct.

It should be migrated to:

```dart
main() {
  List<int?> x = [];
  List<int> y = x as List<int>;
}
```

**Comment by MichaelRFairhurst** [comment]
Potentially related to #38708...

We may actually need to insert `.cast<int>` instead of `as List<int>` for the same reasons discussed there.

**Comment by srawlins** [comment]
The migration tool now performs the cast:

```dart
main() {
  List<int?> x = [];
  List<int> y = x as List<int>;
}
```
