### ISSUE TITLE
Analyzer issue with '?..' operator

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#38715]
```dart
class A {
  void test() {}
}

main() {
  A? a = null;
  a ?.. test();
}
```
Now run analyzer with 'non-nullable' experiment flag

dartanalyzer --enable-experiment=non-nullable static_errors_A11_t01.dart
Analyzing static_errors_A11_t01.dart...
  error - The expression is nullable and must be null-checked before it can be used. - static_errors_A11_t01.dart:23:3 - unchecked_use_of_nullable_value
1 error found.

Null-aware operator '?..' shouldn't report this error

Dart VM version: 2.6.0-dev.5.0 (Thu Oct 3 15:21:01 2019 +0200)

**Comment by scheglov** [comment]
I believe this was fixed some time ago, not errors here anymore.
