### ISSUE TITLE
[vm/ffi] Most FFI tests broken in ARM_X64

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#38718]
Testing via:
```bash
python tools/test.py -n dartkp-android-debug-arm_x64 ffi```

Uncovers at least a dozen crashes.

/cc @mraleph @mkustermann @dcharkes

**Comment by sjindel-google** [comment]
This makes the FFI basically unusable on 32-bit devices in Flutter.

**Comment by dcharkes** [comment]
We haven't implemented simarm at all (https://github.com/dart-lang/sdk/issues/37299).

**Comment by mkustermann** [comment]
@sjindel-google Are you sure the changes you made for https://github.com/dart-lang/sdk/issues/38709 are correct?

As mentioned offline some days ago, we should add integration tests to https://github.com/flutter/flutter that can serve as examples as well as actual tests - they would run on all devices go/flutter-dashboard runs on.

**Comment by sjindel-google** [comment]
> We haven't implemented simarm at all (#37299).

This isn't actually about SIMARM at all, it's about cross-compiling from X64 to ARM. The "SIM" part comes from the SIMARM_X64 config, but it's misleading.

> As mentioned offline some days ago, we should add integration tests to https://github.com/flutter/flutter that can serve as examples as well as actual tests - they would run on all devices go/flutter-dashboard runs on.

Does Flutter dashboard run on any 32-bit devices? I can't tell from the dashboard itself.

**Comment by sjindel-google** [comment]
> @sjindel-google Are you sure the changes you made for #38709 are correct?

I'm pretty sure: most of the tests do pass.

**Comment by mkustermann** [comment]
Seems like this was just a  `kWordSize` vs `compiler::target::kWordSize` issue.

> Does Flutter dashboard run on any 32-bit devices? I can't tell from the dashboard itself.

I would assume so, because the flutter/engine as well as flutter/flutter contain 32-bit vs 64-bit code. It can produce fat apks with 32-bit and 64-bit flutter, so I would assume it's tested. Will follow up on it.

Though my point stands: We should have ffi tests in flutter/flutter to ensure it runs on all devices that normal flutter tests run. Any new configurations / devices flutter adds to their test matrix would immediately test the ffi as well.

**Comment by sjindel-google** [comment]
> Seems like this was just a kWordSize vs compiler::target::kWordSize issue.

Most likely, although some tests are still broken after https://dart-review.googlesource.com/c/sdk/+/120260

**Comment by sjindel-google** [comment]
Actually that was the last of the errors. `enable_ffi_test` seems broken in both ARM and ARM_X64 configs (it's producing an error from gen_snapshot, but this isn't recognized as a compile-time error).

**Comment by dcharkes** [comment]
> Actually that was the last of the errors. `enable_ffi_test` seems broken in both ARM and ARM_X64 configs (it's producing an error from gen_snapshot, but this isn't recognized as a compile-time error).

So it's both not showing up as a compile-time error and not as a runtime error? The test is setup as `//# 01: compile-time error, runtime error`.

**Comment by sjindel-google** [comment]
It says:

```
FAILED: dartkp-dart_precompiled release_arm ffi/enable_ffi_test/01
Expected: Pass Slow
Actual: MissingCompileTimeError
Missing expected compile error.
Missing expected runtime error.
```
