### ISSUE TITLE
Migration: explicit null assignment should be a very strong hint of nullability

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38719]
Consider the following code:
```dart
void f({String s = null}) {
  print(s.length);
}
```
Currently, the migration decides that `s` should be non-nullable, since `s` is unconditionally dereferenced within the body of the `f`.  But because of the explicit assignment to `null`, we know that the user intends for `s` to be nullable.

We may want to consider an assignment (or default value) of a null literal to be a special indicator that the user intends the value to be nullable, and thus create a "union" edge so that it is considered stronger than the unconditional usage of `s` in `s.length`.

Note, however that we should be careful, because some indications should be even stronger still, for example the `/*!*/` comment in this code:
```dart
void f(String/*!*/ s) {
  s = null;
}
```
I'm placing this issue under the epic "NNBD migration tool - detailed edge cases and polish" because I haven't been able to think of any examples of non-buggy code where this kind of case would arise.

**Comment by srawlins** [comment]
Hehe the current behavior is to put a `!` on `null`, which is perhaps worse?

```dart
void f({String s = null!}) {
  print(s.length);
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
