### ISSUE TITLE
pub analyzes package with old incompatible dart version

### ISSUE THREAD

**Issue by passsy** [dart-lang/sdk#38716]
I'm the author of [`lint`](https://pub.dev/packages/lint) and I get analyze errors when publishing to pub with sdk constraint `>=2.5.0 <3.0.0`.

Analyze runs with `Dart 2.4.0` which is outdated. It would be better when analyzer would run with the latest stable version.

The implication is a big score hit (Health: 0).

I'm required to publish for Dart 2.5+ to ship the latest lint rule additions. Publishing for Dart 2.4 is not possible as it would result in analyze error due to unknown lint rules.

[Errors](https://pub.dev/packages/lint#-analysis-tab-):

#### Analysis issues and suggestions

```
Fix dependencies in pubspec.yaml.

Running pub upgrade failed with the following output:

ERR: The current Dart SDK version is 2.4.0.
 
 Because lint requires SDK version >=2.5.0 <3.0.0, version solving failed.
```

#### Maintenance issues and suggestions

```
Fix platform conflicts. (-20 points)

Error(s) prevent platform classification:

Fix dependencies in pubspec.yaml.
```
```
Make sure dartdoc successfully runs on your package's source files. (-10 points)

Dependencies were not resolved.
```

**Comment by vsmenon** [comment]
@jonasfj - should this be filed on `pub`?

**Comment by passsy** [comment]
Fixed in the meantime
