### ISSUE TITLE
Analyzer with nnbd null check issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#38733]
```dart
class A {
  foo() {}
}

dynamic init(x) => x;

main() {
  A? a = init(A());
  if (a is Null) { // analyzer error, see below
  } else {
    a.foo(); 
  }
}
```
Analyzer output (with --enable-experiment=non-nulable option) is
```
  error - The expression is nullable and must be null-checked before it can be used. - null_promotion_A01_t07.dart:27:5 - unchecked_use_of_nullable_value
  hint - Tests for null should be done with '== null'. - null_promotion_A01_t07.dart:25:7 - type_check_is_null
```
Seems that we have an error because of "It is an error to call an expression whose type is potentially nullable and not dynamic." [rule](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors). But (according to @eernstg ) this should happen only  if there is no promotion of `a` in the `else` branch. Here we have a type promotion so there must be no error

Dart VM version: 2.6.0-dev.5.0

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/123221

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144804
