### ISSUE TITLE
Analyzer with nnbd: late variable initialization issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#38734]
```dart
class C {
  late String v2 = initV2("Show must go on"); // analyzer   error - Only static members can be accessed in initializers. - late_A04_t05.dart:53:20 - implicit_this_reference_in_initializer
  initV2(String val1) {
    v2 = val1;
  }
}
```
According to the [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) "It is not an error for the body of a late field to reference this." there must be no error.

Dart VM version: 2.6.0-dev.5.0

**Comment by leafpetersen** [comment]
cc @stereotype441 @scheglov this came up in migrating dart:core as well.  It looks like the analyzer correctly does not issue an error for explicit "this" references in late fields, but not implicit "this" references in late fields.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/123688
