### ISSUE TITLE
dart2native: strip option

### ISSUE THREAD

**Issue by cup** [dart-lang/sdk#38731]
Now that dart2native can create a single file, it would be nice if a way was
available for Dart to strip the created files. Currently I am using something
like this:

~~~
dart2native one.dart
strip one
~~~

I noticed that `dartaotruntime` itself has already been stripped, as its the
same size as a "hello world" example after you strip it yourself.

**Comment by cup** [comment]
https://github.com/dart-lang/sdk/issues/36915

**Comment by cup** [comment]
Hm, actually, it looks like stripping destroys the program:

~~~
$ cat one.dart
main() {
   var bye = 'Hello world!';
   print("$bye");
}

$ ./dart2native.bat one.dart
Generated: d:\desktop\dartsdk-windows-x64-release\dart-sdk\bin\one.exe

$ ./one
Hello world!

$ strip one
$ ./one
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]
~~~

**Comment by cachapa** [comment]
I had a similar issue even without stripping, maybe it's related:

``` bash
$ dart2native main.dart -o fireutil
Generated: /home/cachapa/fireutil/bin/fireutil

$ ./fireutil 
Utility to manage Firestore databases.
[...]

$ sudo mv fireutil /usr/local/bin
$ fireutil 
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]
[...]
```

**Comment by cup** [comment]
To be fair, it fails with Go too:

~~~
$ cat one.go
package main
func main() {
   println("hello world")
}

$ go build one.go
$ ./one.exe
hello world

$ strip one.exe
$ ./one.exe
sh: ./one.exe: cannot execute binary file: Exec format error
~~~

but it doesnt matter as Go has a strip option:

~~~
$ go build -ldflags -s one.go
$ ./one.exe
hello world
~~~

and it does work with D:

~~~
$ cat one.d
import std.stdio;
void main() {
   writeln("hello world");
}

$ dmd one.d
$ ./one.exe
hello world

$ strip one.exe
$ ./one.exe
hello world
~~~

and works with Nim:

~~~
$ cat one.nim
echo "hello world"

$ nim c --gcc.exe:x86_64-w64-mingw32-gcc \
> --gcc.linkerexe:x86_64-w64-mingw32-gcc one.nim
$ ./one.exe
hello world

$ strip one.exe
$ ./one.exe
hello world
~~~

**Comment by 0xbkt** [comment]
@cup Can you confirm if UPX works with dart2native?

**Comment by cup** [comment]
@0xbkt this issue is about strip, not UPX

https://wikipedia.org/wiki/Strip_(Unix)

**Comment by mraleph** [comment]
`strip` is not going to do anything useful to the binary that `dart2native` produced so we have no plans to support it right now.

**Comment by jamesderlin** [comment]
> `strip` is not going to do anything useful to the binary that `dart2native` produced so we have no plans to support it right now.

Currently running `strip` not only is not useful, it's detrimental.

Is there anything we can do to at least make `strip` not break the generated binary?

**Comment by mraleph** [comment]
@jamesderlin not with the current approach - the generated binary is essentially AOT runtime and an AOT snapshot simply concatenated together. `strip` just throws AOT snapshot away because it is not a real section.

**Comment by cup** [comment]
https://github.com/dart-lang/sdk/issues/39261

**Comment by muv1** [comment]
https://github.com/dart-lang/sdk/issues/39319

**Comment by hendrik-brower** [comment]
I tried to get a compiled binary to run in a restricted environment (chroot).  I would guess this is either related or the error triggered in this case is caught by the generic error handler.  Ref: https://stackoverflow.com/questions/76050141/running-a-dart-exe-in-chroot
