### ISSUE TITLE
Ranking/sorting of code completion is worse with suggestion sets

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#38739]
This was [raised in Dart-Code](https://github.com/Dart-Code/Dart-Code/issues/1742), but I think needs to be fixed in the server. I thought there was already an open issue about this here but cannot locate it. I don't know if it's easily fixable, but seems like we should have an issue tracking it here.

This is what completion looked like before:

![Screenshot 2019-05-29 at 10 18 53 am](https://user-images.githubusercontent.com/1078012/58545465-3657aa00-81fb-11e9-942e-f08a66e76efe.png)

And this is what it looks like using the new auto-import completions:

![Screenshot 2019-05-29 at 10 24 04 am](https://user-images.githubusercontent.com/1078012/58545843-05c44000-81fc-11e9-8a3b-4f15579717d7.png)

Based on [comments from @scheglov](https://github.com/Dart-Code/Dart-Code/issues/1742#issuecomment-496975928) I think the issue here is that the declared type of the property does not match the one the user wants (because it just uses the parsed AST) and therefore doesn't get ranked at the top.

**Comment by maRci002** [comment]
To sum up there was a [community request to enable completion for non imported identifiers](https://github.com/dart-lang/sdk/issues/25820) and problems occur when the client uses the following event: `completion.existingImports`.

Thanks to @scheglov the [problem](https://github.com/JetBrains/intellij-plugins/pull/665#issuecomment-525002139) was helped a bit on the dev channel but [the relevance is still high in the local file for all the identifiers.](https://github.com/JetBrains/intellij-plugins/pull/665#issuecomment-533890087)

![local 1](https://user-images.githubusercontent.com/8436039/65389648-cac0bc00-dd58-11e9-893d-a9f7b946680d.gif)

**Comment by NikolnikovK** [comment]
Any follow up on this issue ?

**Comment by bwilkerson** [comment]
Yes, we are actively discussing how best to address this situation and I think we're getting close to having a plan. I don't know how long it will take to implement, but it should get better eventually.

**Comment by NikolnikovK** [comment]
It's been quite some time, and it's getting worse.
Now, even with auto-import on 'OFF' in VS Code, the code completion does not work.
Maybe I missed a news, would be great to at least have a work-around.

**Comment by DanTup** [comment]
Here's a specific example that came up without auto-imports (and without LSP):

Flutter 1.20.0:

<img width="697" alt="Screenshot 2021-01-07 at 12 00 46" src="https://user-images.githubusercontent.com/1078012/103891885-82aae180-50e2-11eb-8847-2982fddd9cbc.png">

Flutter 1.22.0:

<img width="659" alt="Screenshot 2021-01-07 at 12 15 44" src="https://user-images.githubusercontent.com/1078012/103891893-876f9580-50e2-11eb-894c-6d37e2ff7f5f.png">

I captured the `relevance` scores for each, and here's what they look like (TextStyle appears only with a relevance of 192, so is mixed in with the other classes):

<img width="1167" alt="Screenshot 2021-01-07 at 12 34 47" src="https://user-images.githubusercontent.com/1078012/103893207-cd2d5d80-50e4-11eb-940a-7acb8da123df.png">

**Comment by fisforfaheem** [comment]
Hope it gets fixed soon :(

**Comment by gaetschwartz** [comment]
Any updates @DanTup ?

**Comment by DanTup** [comment]
It's a bug that the `dart.autoImportCompletions` setting in VS Code is being ignored for LSP - I've filed https://github.com/Dart-Code/Dart-Code/issues/3177 to fix that.

**Comment by waleedf112** [comment]
> It's a bug that the `dart.autoImportCompletions` setting in VS Code is being ignored for LSP - I've filed [Dart-Code/Dart-Code#3177](https://github.com/Dart-Code/Dart-Code/issues/3177) to fix that.

I've tried to set LSP and "dart.autoImportCompletions" to false.
didn't work either.

**Comment by DanTup** [comment]
@waleedf112 sorry, you seem to be correct - disabling LSP and auto-import-completions does still result in worse ranking than the screenshot shown at the top here.

@bwilkerson I'm not sure if this is known or a new/different bug. My understanding was that the ranking with SuggestionSets wasn't as good because of less type information, though with suggestion sets disabled the `padding` example above is ranking `EdgeInsets` further down that it did:

<img width="429" alt="Screenshot 2021-03-04 at 17 48 30" src="https://user-images.githubusercontent.com/1078012/110006683-db2ce280-7d11-11eb-8aa0-c8f2f0a4b8c7.png">

```js
{
	"kind": "INVOCATION",
	"relevance": 517,
	"completion": "EdgeInsets.all",

{
	"kind": "INVOCATION",
	"relevance": 564,
	"completion": "hashCode",
```

**Comment by bwilkerson** [comment]
> I'm not sure if this is known or a new/different bug.

Me either.

> My understanding was that the ranking with SuggestionSets wasn't as good because of less type information ...

It's true that suggestion sets don't currently contain enough information to use type information, so that seems like a likely cause for the relevance results we were seeing.

This certainly suggests that there's also a problem when we aren't using suggestion sets. Unfortunately, because of having two code paths for suggesting `EdgeInsets.all` there could easily be multiple issues.

**Comment by fisforfaheem** [comment]
I am so much frustrated 😤  because of this behaviour of flutter :(

**Comment by bwilkerson** [comment]
I'm sorry the tools are causing frustration, and I completely understand why.

I've done some digging and I have found two issues that impact this behavior:
- It's giving too much weight to members defined on the implied target of `this`.
- It's not using the type of the parameter to give higher priority to static members.

I have a couple of ideas for how to solve the first issue, and I have just landed a CL to address the second issue (https://dart-review.googlesource.com/c/sdk/+/190281).

**Comment by fisforfaheem** [comment]
Thanks for the feedback. I hope this gets resolved soon as it is a very
pressing situation for beginners who know nothing of widget properties

**Comment by bwilkerson** [comment]
I have attempted to improved the first part of the issue with https://dart-review.googlesource.com/c/sdk/+/190581. Unfortunately I am not yet seeing any improvements in IntelliJ, which uses available declaration support.

**Comment by fisforfaheem** [comment]
Thanks for the feedback.

**Comment by waleedf112** [comment]
new progress in the master channel, code completion is better now, yet not perfect.

when viewing code suggestions, now I see the appropriate values:

![image](https://user-images.githubusercontent.com/44902066/113343527-c9286a80-92e4-11eb-8e5c-d61e6db59214.png)

a small and minor problem, if the suggested value was a function call, for example:

![image](https://user-images.githubusercontent.com/44902066/113343709-068cf800-92e5-11eb-8c9c-bdc49a44ca43.png)
![image](https://user-images.githubusercontent.com/44902066/113343743-11e02380-92e5-11eb-9f68-801b223f13f9.png)

it completes it as an Enum or a Type, not a function call like this:

![image](https://user-images.githubusercontent.com/44902066/113344518-050fff80-92e6-11eb-85ab-31bba6d01c59.png)
![image](https://user-images.githubusercontent.com/44902066/113344537-0b05e080-92e6-11eb-9af1-8a901fd90cf8.png)

```
Flutter version: 2.1.0-13.0.pre.390
Dart version: 2.13.0 (build 2.13.0-190.0.dev)
Flutter extension version: 3.21.0
```

dart settings:
```
  "dart.previewLsp": true,
  "dart.autoImportCompletions": false
```

finally, I can upgrade from Flutter 1.20.4 😂.
thank you guys, I hope it will get better and better.

**Comment by fisforfaheem** [comment]
Thanks For the Heads Up! i really hope they make it much better every week
now! also keep finding more goodies

**Comment by rajeshzmoke** [comment]
> new progress in the master channel, code completion is better now, yet not perfect.
> 
> when viewing code suggestions, now I see the appropriate values:
> 
> ![image](https://user-images.githubusercontent.com/44902066/113343527-c9286a80-92e4-11eb-8e5c-d61e6db59214.png)
> 
> a small and minor problem, if the suggested value was a function call, for example:
> 
> ![image](https://user-images.githubusercontent.com/44902066/113343709-068cf800-92e5-11eb-8c9c-bdc49a44ca43.png)
> ![image](https://user-images.githubusercontent.com/44902066/113343743-11e02380-92e5-11eb-9f68-801b223f13f9.png)
> 
> it completes it as an Enum or a Type, not a function call like this:
> 
> ![image](https://user-images.githubusercontent.com/44902066/113344518-050fff80-92e6-11eb-85ab-31bba6d01c59.png)
> ![image](https://user-images.githubusercontent.com/44902066/113344537-0b05e080-92e6-11eb-9af1-8a901fd90cf8.png)
> 
> ```
> Flutter version: 2.1.0-13.0.pre.390
> Dart version: 2.13.0 (build 2.13.0-190.0.dev)
> Flutter extension version: 3.21.0
> ```
> 
> dart settings:
> 
> ```
>   "dart.previewLsp": true,
>   "dart.autoImportCompletions": false
> ```
> 
> finally, I can upgrade from Flutter 1.20.4 😂.
> thank you guys, I hope it will get better and better.

can u post the full settings.json ?

**Comment by srawlins** [comment]
@bwilkerson did you do work on this recently?

**Comment by bwilkerson** [comment]
Yes. We're no longer using available suggestions data for libraries that are explicitly imported by the library in which completion is occurring. We _are_ still using it for libraries that could be imported but aren't yet. The recent work should improve the situation but doesn't necessarily solve the whole problem.

**Comment by fisforfaheem** [comment]
Thanks

**Comment by dipeshkd** [comment]
Updated the dart settings as per below and it improved the code competition suggestion
```
"dart.previewLsp": true,
"dart.autoImportCompletions": false
```

However it seems to have broken the package "Auto Import" suggestion 

After Applying the change
![image](https://user-images.githubusercontent.com/9581711/122531031-38576480-d073-11eb-9239-55677cf1f5ae.png)

Before applying the change
![image](https://user-images.githubusercontent.com/9581711/122531095-47d6ad80-d073-11eb-9023-ab8482add801.png)


```
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (7 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by fisforfaheem** [comment]
Thanks, I'll take a look.

**Comment by KlausJokisuo** [comment]
Any news on working fix for IntelliJ also?

**Comment by bwilkerson** [comment]
@scheglov Is experimenting with some changes that ought to improve code completion response time on IntelliJ, and this might have also have some benefits in terms of the ranking. Given the end-of-year holidays it isn't clear when we'll have those results, but we are continuing to work on improving code completion.

**Comment by DanTup** [comment]
The original example at the top is now much better (at least in Flutter `master`), although similar to a comment I just added in https://github.com/dart-lang/sdk/issues/43657, `Null` is oddly near the top, and the constructors might be a better choice than the types (especially since any named constructors are already in the list fully-qualified).

<img width="601" alt="Screenshot 2022-12-15 at 18 34 28" src="https://user-images.githubusercontent.com/1078012/207940381-39687dbd-7ec8-4740-b3be-e7a529ff2986.png">

**Comment by DanTup** [comment]
I believe this issue is redundant now, as we don't use suggestion sets at all. Not-yet-imported completions are included (and ranked) using the same mechanism as other completions now.
