### ISSUE TITLE
Migration: infer "late" when appropriate

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38747]

**Comment by bwilkerson** [comment]
Example: In the logging package, in `lib/logging.dart` lines 166-172 are migrated as
```
      String? msg;
      if (message is String) {
        msg = message;
      } else {
        msg = message.toString();
        object = message;
      }
```
I believe that it would be better to mark `msg` as non-nullable and late.

**Comment by stereotype441** [comment]
@MichaelRFairhurst and I discussed yesterday how to achieve this.  Once https://github.com/dart-lang/sdk/issues/40509 is implemented, the algorithm can be:
- If a node associated with the nullability of a variable that could be marked late, and all edges leaving that node point to nodes with non-null intent, consider the node to have "late non-null intent" (this is a weaker claim than the standard claim of "non-null intent"; non-null intent implies late non-null intent but not vice versa).
- Consider the edge produced by implicit initialization of null to be slightly weaker than ordinary edges.  That is, during propagation of nullability, it cannot override late non-null intent, whereas ordinary edges can.  (Note that in the original design document for the migration engine, such edges were called "uninit edges").
-  In the FixBuilder, when visiting the declaration of a variable, if it is non-nullable and lacks an initializer, mark it "late".

This should be equivalent to the algorithm in the original design document for the migration engine.

Open question: if a node has zero edges leaving it, should we consider it to vacuously have late non-null intent?
