### ISSUE TITLE
passing Iterable to isolate sometimes crashes

### ISSUE THREAD

**Issue by peter-meemo** [dart-lang/sdk#38746]
`Dart VM version: 2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "macos_x64"`

Passing Iterable over a sendPort sometimes fails, because lazy Iterables sometimes contain closures. It is often difficult for calling code to know whether the object it is sending is lazy or not, since this is not something that user code is expected to care about in common usage. 

Is there any way the isolate serialization code can handle realizing lazy Iterables before transmitting them?

**Comment by lrhn** [comment]
I don't think there is any chance we'll recognize an isolate contains a closure and then eagerly iterate it to find the element before sending. The only real solution would bet o allow sending closures, which is issue #33047.
