### ISSUE TITLE
Analyzer: MethodInvocation vs. FunctionExpressionInvocation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#38749]
https://dart-review.googlesource.com/c/sdk/+/120342 changes how Analyzer represents different kinds of invocations.

  We used to represent all invocations like `foo()` as MethodInvocation(s). But this is not ideal, because if `foo` is not an FunctionElement or a MethodElement, but a `PropertyAccessorElement`, then it is not `foo` that is invoked, but the result returned from `foo` is invoked instead. This is what FunctionExpressionInvocation should represent.

The changes is green in google3, but adds [several failures for DDC](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8900481111968585648/+/steps/test_results/0/logs/unapproved_new_test_failures/0), which I was not able to track and fix. We agreed that it is OK to land the
CL, and let the DDC team to decide what should not done on the DDC side.

**Comment by vsmenon** [comment]
I'll take a look and see if this is worth fixing.

**Comment by vsmenon** [comment]
obsolete
