### ISSUE TITLE
Instrumentation gives a Never NullabilityNodeInfo for `!` fixes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38748]
Every NNBD migration `!` fix, e.g.

```dart
parent._children[name] = this;

// to:

parent!._children[name] = this;
```

has a NullabilityNodeInfo on its reason that is `never`. Because of this, we cannot do equality checks, or distinguish between these nodes. In the instrumentation rendering, we end up pointing the user to a random never node.

**Comment by stereotype441** [comment]
This has been addressed.
