### ISSUE TITLE
Flow analysis needs to understand that assertion conditions don't necessarily execute.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38761]
Consider the following code:
```dart
void test(Object x) {
  assert((x is int ? x + 1 : throw 'foo') == 0); // (1)
  print(x + 1);                                  // (2)
}
```
The use of `x` in `x + 1` at (1) is valid, because `x` is promoted to `int` here.  But the use at (2) should be invalid, because if assertions are disabled, no promotion happens.

Once https://dart-review.googlesource.com/c/sdk/+/120503 lands, there will be a similar issue for assertions in constructor initializers, e.g.:
```dart
class C {
  C(Object x)
      : assert((x is int ? x + 1 : throw 'foo') == 0) { // ok
    print(x + 1);                                       // bad
  }
}

**Comment by lrhn** [comment]
I think `assert(test, message)` can always be treated like `if (assertionsEnabled && !test) throw AssertionError(message);` where `assertionsEnabled` is a magic value which cannot be known at compile/analyze-time
