### ISSUE TITLE
Update changelog for dart2native

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#38768]
@mit-mit dart2native is one of the main features for 2.6, but currently it isn't mentioned in the CHANGELOG.md at all.

Please add a description of the new dart2native feature to CHANGELOG.md.

**Comment by cskau-g** [comment]
Michael, were you on this?

**Comment by vsmenon** [comment]
ping

**Comment by vsmenon** [comment]
Assigning to @mit-mit - can you do or reassign?
