### ISSUE TITLE
Dart SDK 2.5.1 is not compatible work macOS Catalina

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38765]
The 2.5.1 SDK doesn't seem to run on the Catalina macOS update that went out yesterday: It fails with '"dart" cannot be opened because the developer cannot be verified'

<img width="617" alt="Screenshot 2019-10-08 at 08 00 02" src="https://user-images.githubusercontent.com/13644170/66398724-939c0d00-e9de-11e9-9471-c3c372f6cc39.png">

**Comment by mit-mit** [comment]
As a temporary work-around, we believe 2.5.0 might work. We're considering spinning 2.5.2 to resolve this.

**Comment by athomas** [comment]
2.6.0-dev.0.0 and 2.6.0-dev.6.0 also work. For 2.6.0-dev.(1|2|3|4|5).0 and 2.5.1 the unsigned/unnotarized binaries where mistakenly published.

**Comment by athomas** [comment]
Fixed in 2.5.2.

**Comment by Majdi-Alkhusha** [comment]
use this command 
sudo xattr -d com.apple.quarantine "Your_Flutter_path/bin/cache/dart-sdk/bin/dart"
