### ISSUE TITLE
Dart 2.6 docs & packages updates

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38770]
## Documentation

**Native:**

Update https://dart.dev/tools/dart2aot
  - [x] Remove dart2aot: https://github.com/dart-lang/site-www/pull/2048
  - [x] Add content to /tools/dart2native: https://github.com/dart-lang/site-www/pull/2048
  - [x] Clarify when to use .exe vs .aot: https://github.com/dart-lang/site-www/pull/2048
  - [x] Update landing page graphics: https://github.com/dart-lang/site-www/pull/1990

**Extension methods:**
  - [x] Nothing needed, we will add this for 2.7

**FFI:**
  - [x] Now in beta: https://github.com/dart-lang/site-www/pull/2052

## Packages

- [x] `dart:ffi` package that supports 2.6: https://github.com/dart-lang/ffi/pull/19
- [x] `dart_console` package that supports 2.6: https://github.com/timsneath/dart_console/pull/7
- [ ] [package:intl](http://pub.dartlang.org/packages/intl)
- [ ] [package:tflite_native](http://pub.dartlang.org/packages/tflite_native)

**Comment by kwalrath** [comment]
Should we move this to dart-lang/site-www?

**Comment by vsmenon** [comment]
@kwalrath - is there any update on this issue?  I think @mit-mit is out this week.

**Comment by kwalrath** [comment]
I plan to do this work next week.

**Comment by mit-mit** [comment]
There is no work here that needs to land in the SDK. But I'd prefer to track it here to make sure we don't forget before launch.

**Comment by dgrove** [comment]
@kwalrath what's the best way to track this for the release?

**Comment by kwalrath** [comment]
> @kwalrath what's the best way to track this for the release?

PRs, probably. I'm working on a PR for the dart2aot/dart2native doc updates.

I'll have a separate (smaller) PR for the FFI page.
