### ISSUE TITLE
Delete analyzer based DDC from the SDK - (In)direct Breaking Change?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38777]
We are getting close to the day when we will delete the analyzer based version of DDC from the SDK and stop distributing the SDK compiled by DDC. This is an important step to reduce our technical debt but it is a breaking change.

The only possible problem we have identified are projects with a dependency on package build_web_compilers: < 2.0.0. Those projects rely on the analyzer based DDC for development and would be broken if it disappeared from a new 2.x.x release of the SDK.

Many users have already switched to use the kernel based DDC implementation and will experience no issues. 
* Flutter Web builds (using the flutter CLI) have always used the kernel based version.
* AngularDart projects using the 6.0.0-alpha releases are forced to use a newer version of build_web_compilers.
* All web templates in Stagehand already use build_web_compilers: ^2.0.0

Projects with a dependency on angular ^5.0.0 (the latest stable releases) have the ability to version solve with build_web_compilers <2.0.0. These projects could be broken by upgrading their SDK. 

@mit-mit Do you have any guidance on how to proceed with the deletion. Should we go through the formal breaking change process? How would you like to message it?

@natebosch Mentioned we could possibly release a version of build_web_compilers on the 1.x.x branch that could at least provide a helpful error message but that would only help the users that upgraded to that release.

**Comment by natebosch** [comment]
@mit-mit - Do we have analytics on the pub downloads for `build_web_compilers` 1.x vs 2.x? Where could I find those?

**Comment by mit-mit** [comment]
> Do you have any guidance on how to proceed with the deletion.

Yes, please use the [breaking change process](https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md). I would simply explain what the change is, why we are making it, and what steps users can take to mitigate.

> Do we have analytics on the pub downloads for build_web_compilers 1.x vs 2.x?

Sorry, we don't have analytics per-version

**Comment by nshahan** [comment]
Breaking change request has been filed https://github.com/dart-lang/sdk/issues/38994.

**Comment by nshahan** [comment]
Waiting on https://github.com/dart-lang/build/issues/2564 before landing the first part of the deletion.

**Comment by nshahan** [comment]
From in person discussions we have agreed to add some detection in DDC and if it's passed an analyzer summary for the SDK (older versions of build_web_compilers do this) then we will print instructions to update the dependency. No longer waiting for a new version on the 1.x.x branch to be published.

**Comment by nshahan** [comment]
Deletion landed in c561a9eacc1b3d0a93980ef5119f77bf88511a15.

**Comment by natebosch** [comment]
Should we remove this TODO?

https://github.com/dart-lang/sdk/blob/8b777dd829e7466fd7dee207d45c60322ca93bc0/pkg/dev_compiler/lib/src/compiler/shared_command.dart#L404

Can we drop `isKernel` from the args object?

**Comment by nshahan** [comment]
I see what you mean now yeah we can probably delete it. I would also like to remove the kernel flag outright but we will need to work out how (versioning and publish order) to do that safely and avoid breaking build_web_compilers and flutter web.

**Comment by natebosch** [comment]
Looks like nothing else was referencing it so the last bit of cleanup is easy. https://dart-review.googlesource.com/c/sdk/+/130822
