### ISSUE TITLE
Fix nnbd migration tool for test test_dartfix_nonNullable -- how should this work?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38771]
Some progress here https://dart-review.googlesource.com/c/sdk/+/119601

However, we may not want to make this test pass, and we may want to take a different approach entirely, like ignore nullability during analysis and recalculate it from scratch.

**Comment by MichaelRFairhurst** [comment]
This test should be deleted

**Comment by srawlins** [comment]
I think the test has been deleted.
