### ISSUE TITLE
Using extension methods in dart:-libraries breaks dartdoc

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38786]
Creating an issue to mark as D26.

Full issue here: https://github.com/dart-lang/dartdoc/issues/2039 and https://github.com/dart-lang/dartdoc/issues/2033

From @athomas: We'll have to revert the extension method API CLs tomorrow if this is not fixed, or we cannot make a release.

/cc @mit-mit, @sjindel-google, @mkustermann

**Comment by athomas** [comment]
We should revert/fixup release blockers immediately. We're already unlikely to have a good dev build tomorrow because the release build is broken today (and we will have a Google3 hash that can't be released externally).

**Comment by athomas** [comment]
Marking this as P0 until the release build is fixed (if we wanted to release 2.6 today, we couldn't because of this issue).

**Comment by dcharkes** [comment]
I added a diff to https://github.com/dart-lang/dartdoc/issues/2039 that works around the problem, but I'm not sure whether that's the right fix.

I can try removing all the comments on the extension methods, to see if that works around it for now.

**Comment by mit-mit** [comment]
cc @jcollins-g

**Comment by dcharkes** [comment]
Original dartdoc issue: https://github.com/dart-lang/dartdoc/issues/2033

**Comment by dcharkes** [comment]
I landed a workaround, the release build works, but has no resolved identifiers in the dartdoc comments on extension methods.

**Comment by vsmenon** [comment]
This is worked around, so no longer P0.

**Comment by jcollins-g** [comment]
Closing issue.  While the crash is fixed, the implementation is still missing.  That will continue to be tracked in dart-lang/dartdoc#2033.
