### ISSUE TITLE
Investigate situation for Null/Never in inference, specifically in literals

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38799]
may be related to https://github.com/dart-lang/sdk/issues/38120

This code currently gives errors:

```dart
if ((() => true)()) {}
```

because the inferred return type is `Null`, which is not assignable to `bool`.

This is partly an open issue regarding literal inference. And partly should be changed so that in the meantime it returns Never.

**Comment by lrhn** [comment]
Why should it return `Never`? Did you mean `throw something` instead of `true`?

**Comment by scheglov** [comment]
The title of the issue is quite wide, but the example is narrow.
And it works for me.
Is there a more wide example you are thinking about, @MichaelRFairhurst ?

![image](https://user-images.githubusercontent.com/384794/67645018-72df1d00-f8e3-11e9-89b4-fc77a006ce29.png)

**Comment by MichaelRFairhurst** [comment]
@bwilkerson and @pq ran into something with this earlier...I probably summarized it into a repro that didn't actually capture it.

I thought we had not correctly implemented function return type inference, and that it always inferred a return type of `Null` for function literals.

Maybe the real case is this?

```
() { return true; }
```

We need to make sure that we're handling this correctly, and correctly may be that it should return dynamic, or Never, or bool.

**Comment by scheglov** [comment]
OK, we might have an issue here.

```dart
main(a) {
  var f1 = () {
    return true;
  };

  var f2 = () {
    return a;
  };

  var f3 = () {
    throw 42;
  };
}
```

The type of `f1` is `bool Function()`.
The type of `f2` is `dynamic Function()`.
The type of `f3` is `Null Function()`.

The type of `f3` looks wrong, it probably should be `Never Function()`, but I don't know where this would be written in the spec, so that I could confirm this. @leafpetersen, could you help?

**Comment by leafpetersen** [comment]
@scheglov I added this to my TODO list, but won't get to this today.

This relies on the reachability analysis that is part of definite assignment/promotion.

In case it's helpful here's my intention:

A path from the entry to a function **does not complete** if it terminates in a `throw statement` or an expression statement of type `Never`

A path from the entry to a function **returns normally** if it terminates in a `return` statement.

So we have:
  - A function body for which all paths do not complete has inferred return type `Never`
  - A function body for which all paths either do not complete, or return normally, has the inferred return type given by the upper bound of the types of all of the returned expressions
  - A function body for which at least one path neither fails to complete nor returns normally (in other words, it falls of the end of the function body) has the inferred return type given by the upper bound of `Null` and the types of all of the returned expressions.

**Comment by scheglov** [comment]
I believe the inference implementation was updated to do what the [spec requires](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference).
Specifically, we can infer `Never`.

https://dart-review.googlesource.com/c/sdk/+/149605
