### ISSUE TITLE
Analyzer: Missing return with enumerated types using switch-case

### ISSUE THREAD

**Issue by vargavince91** [dart-lang/sdk#38790]
This issue is related to the **Analyzer**.

I have a function that takes an enum enumerated type as a parameter and based on its value, returns a string. I used a `switch` and `case`. I cover every possible value that the enum can take. The dart analyzer complains that `function has a return type of 'String', but doesn't end with a return statement`. In my opinion, it's not correct, as every possible value (that compiles) will return a string.

```
$ dartanalyzer file.dart -v
Analyzing file.dart...
Loaded analysis options from /Users/vince/dartsidedev/plugins/analysis_options.yaml
  warning • This function has a return type of 'String', but doesn't end with a return statement at file.dart:3:1 • missing_return
         Try adding a return statement, or changing the return type to 'void'.
```

I'm using the analysis options from the flutter/flutter repo: https://github.com/flutter/flutter/blob/master/analysis_options.yaml

Here's my code:

```dart
enum Enum { A, B, C }

String convEnumToString(Enum e) {
  switch (e) {
    case Enum.A:
      return 'a';
    case Enum.B:
      return 'bb';
    case Enum.C:
      return 'ccc';
  }
}
```

* Dart SDK Version (`dart --version`)
```
dart --version
Dart VM version: 2.5.1 (Fri Sep 27 12:28:49 2019 +0200) on "macos_x64"
```

**Comment by srawlins** [comment]
In your example, the value of the enum may be `null`, which would fall off the end of the method, without a return statement.

**Comment by vargavince91** [comment]
Oh, of course!
