### ISSUE TITLE
Parser doesn't allow "late" as an identifier

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38803]
Take this:

```dart
main() {
  var foo;
  var bar = foo.late;
}
```

Run it with:

```sh
$ dart --enable-experiment=non-nullable temp.dart
```

Output:

```
temp.dart:3:17: Error: Expected an identifier, but got 'late'.
  var bar = foo.late;
                ^^^^
```

I believe that's incorrect. With NNBD, `late` is a built-in identifier. It can't be used as an identifier in some contexts (prefix?), but in most places it's a valid identifier, just like `get`, `set`, `hide`, etc.

**Comment by bwilkerson** [comment]
@jensjoha

**Comment by davidmorgan** [comment]
Thanks everyone. This is blocking use of extension methods in google3; please treat as high priority if possible :)

**Comment by jensjoha** [comment]
Should be fixed with https://dart-review.googlesource.com/c/sdk/+/121120/.
