### ISSUE TITLE
Feature Request: Provide an api for summarizing the flutter sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#38800]
See https://github.com/dart-lang/build/issues/733 for historical context.

Currently for the dart sdk we are using the `SummaryBuilder.forSdk` api to generate a summary of the sdk. However, when the user is using a flutter sdk we still end up only summarizing the dart sdk (under `bin/cache/dart_sdk` in the flutter sdk).

It would be really nice if we had a similar api which we could give the root of the flutter SDK and it could summarize it (including `dart:ui`). This would allow us to make codegen work much better in a flutter context.

There may be necessary work in the flutter repo for this to happen as well, I don't know if it ships all the necessary sources required to summarize it today.

Alternatively, some direction on how one might summarize the flutter sdk using existing apis would be very useful.

cc @bwilkerson @pq who I was told have some knowledge here.

**Comment by jonahwilliams** [comment]
The source code for the Flutter SDK libraries is available in `flutter/bin/cache/pkg/sky_engine/lib/**`.

**Comment by lesnitsky** [comment]
@jakemac53 is there some work required on dart-build side in order to be able to generate code aware of `dart:ui`, taking into account that Flutter SDK libraries are already available?

**Comment by jakemac53** [comment]
@lesnitsky correct, we need to create our own summary of the sdk (local analyzer versions aren't necessarily compatible with the summaries that ship with the sdk).

This issue was created exactly because of that need. It isn't clear how one would create a summary of the flutter sdk using existing apis. So we need either an api explicitly for that which encapsulates the logic (like `SummaryBuilder.forSdk`) or some guidance on how to do it.

@jonahwilliams thanks that should be a good starting point, I will see if I can get anywhere with that.

**Comment by jakemac53** [comment]
Ok, I was able to summarize the flutter sdk by editing the `flutter/bin/cache/pkg/sky_engine/lib/_embedder.yaml` file to include all the required web libraries:

```yaml
  # Public + internal apis required for summarizing the web stack
  "dart:_foreign_helper": "../../../dart-sdk/lib/_internal/js_runtime/lib/foreign_helper.dart"
  "dart:_js_embedded_names": "../../../dart-sdk/lib/_internal/js_runtime/lib/shared/embedded_names.dart"
  "dart:html_common": "../../../dart-sdk/lib/html/html_common/html_common.dart"
  "dart:_interceptors": "../../../dart-sdk/lib/_internal/js_runtime/lib/interceptors.dart"
  "dart:_js_helper": "../../../dart-sdk/lib/_internal/js_runtime/lib/js_helper.dart"
  "dart:_native_typed_data": "../../../dart-sdk/lib/_internal/js_dev_runtime/private/native_typed_data.dart"
  "dart:_js_names": "../../../dart-sdk/lib/_internal/js_runtime/lib/js_names.dart"
  "dart:_rti": "../../../dart-sdk/lib/_internal/js_runtime/lib/rti.dart"
  "dart:_recipe_syntax": "../../../dart-sdk/lib/_internal/js_runtime/lib/shared/recipe_syntax.dart"
  "dart:_js": "../../../dart-sdk/lib/js/_js.dart"
  "dart:mirrors": "../../../dart-sdk/lib/mirrors/mirrors.dart"
  "dart:web_gl": "../../../dart-sdk/lib/web_gl/dart2js/web_gl_dart2js.dart"
  "dart:_metadata": "../../../dart-sdk/lib/html/html_common/metadata.dart"
  "dart:indexed_db": "../../../dart-sdk/lib/indexed_db/dart2js/indexed_db_dart2js.dart"
  "dart:svg": "../../../dart-sdk/lib/svg/dart2js/svg_dart2js.dart"
  "dart:web_audio": "../../../dart-sdk/lib/web_audio/dart2js/web_audio_dart2js.dart"
  "dart:web_sql": "../../../dart-sdk/lib/web_sql/dart2js/web_sql_dart2js.dart"
```

Below is the corresponding dart code I used. I basically copied what `SummaryBuilder.forSdk` was doing but swapped the `FolderBasedSdk` for an `EmbedderSdk`.

```dart
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:collection';
import 'dart:io';

import 'package:analyzer/src/summary/summary_file_builder.dart';

import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:analyzer/src/dart/sdk/sdk.dart';
import 'package:analyzer/src/generated/engine.dart';
import 'package:analyzer/src/generated/sdk.dart';
import 'package:analyzer/src/generated/source.dart';

import 'package:path/path.dart' as p;

import 'package:yaml/yaml.dart' as yaml;

var sdkPath = p.normalize(
    p.absolute('../', 'flutter', 'bin', 'cache', 'pkg', 'sky_engine', 'lib'));

main() async {
  var summaryFile = File('flutter.sum');
  await summaryFile.writeAsBytes(sdkSummaryBytes());
}

List<int> sdkSummaryBytes() {
  // Prepare SDK.
  var resourceProvider = PhysicalResourceProvider.INSTANCE;
  var embedderYaml = yaml.loadYaml(resourceProvider
      .getFile(p.join(sdkPath, '_embedder.yaml'))
      .readAsStringSync());
  var sdk = new EmbedderSdk(
      resourceProvider, {resourceProvider.getFolder(sdkPath): embedderYaml});

  sdk.useSummary = false;
  sdk.analysisOptions = new AnalysisOptionsImpl();

  print(sdk.sdkLibraries.map((l) => l.shortName).toList());

  // Prepare 'dart:' URIs to serialize.
  Set<String> uriSet =
      sdk.sdkLibraries.map((SdkLibrary library) => library.shortName).toSet();

  Set<Source> librarySources = new HashSet<Source>();
  for (String uri in uriSet) {
    librarySources.add(sdk.mapDartUri(uri));
  }

  return new SummaryBuilder(librarySources, sdk.context).build();
}
```

@bwilkerson @pq Do I have to provide these libraries via the `_embedder.yaml`? There is a `libraries.json` file already at `flutter/bin/cache/libraries.json` which already specifies all these libraries but I don't know how to make the `EmbedderSdk` use it, or if its even possible to combine the `_embedder.yaml` and a `libraries.json`.

It feels weird/wrong to put these extra web only things under the engine `_embedder.yaml`.

**Comment by sigmundch** [comment]
drive-by comment

When we introduced libraries.json, our goal was to eventually move analyzer to use it too. We never got around to do it due to priorities, but it might be worth doing so to address this. In particular, I believe FolderBasedDartSdk still uses the `libraries.dart` file (the old format). I haven't looked, but I believe it should be feasible to switch to use the libraries.json directly without too much heavy lifting. Note that there is a generic parser for this file already here: https://github.com/dart-lang/sdk/tree/master/pkg/front_end/lib/src/base/libraries_specification.dart

**Comment by jakemac53** [comment]
I ran into a variety of issues here, but I think I have landed on something only mildly hacky. Basically, I can create a normal `FolderBasedSdk` - and then if I detect we are actually a flutter sdk I can create the `EmbedderSdk` and manually add all libraries from that to the FolderBasedSdk's libaryMap that didn't already exist.

This makes the `EmbedderSdk` effectively become just a layer on top of the normal sdk summary, and in practice it only adds `dart:ui` but should be general enough to add any more `dart:` libraries that are added in the future.

It is definitely not ideal - the two things don't fully agree on what files they are using for the different libraries - but we only care about the _api_ of these libraries so it shouldn't cause any problems.

cc @sigmundch

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/pull/2501, I haven't actually tested this out yet but it should work.

**Comment by jakemac53** [comment]
Ok, I have that now in a pretty reasonable place. I will go ahead and close this issue, although something more supported would be nice at some point (this is pretty fragile as I am relying on the layout of the sdk, and also that the flutter sdk is built enough that these libraries have been fetched).
