### ISSUE TITLE
Restore `promiseToFuture` in public API of `dart:html`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38805]
When I committed https://github.com/dart-lang/sdk/commit/0f1d5fa7e67e5e451a7d12eb8f2ccbde3eab183c it removed `promiseToFuture` from the public API. I'm not sure we ever intended for this to be public,  but since it is it would be breaking to remove it.

**Comment by natebosch** [comment]
cc @vsmenon - we should consider this a release blocker

Fix is https://dart-review.googlesource.com/c/sdk/+/120935

**Comment by muhleder** [comment]
This is currently breaking firebase for web. https://github.com/FirebaseExtended/firebase-dart/issues/251
