### ISSUE TITLE
Ddk source maps should not use platform specific separators

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#38802]
Today the `sources` key in source maps will use platform specific separators. It also ends up escaping those characters so you get a double backslash `\\`.

When we inline the sourcemap we escape that again, and get four backslashes `\\\\`.

Example from the inlined source map for `packages/test_core/test_core.ddc.js`:

```
"sources":["src\\\\runner\\\\engine.dart","src\\\\runner\\\\load_suite.dart","test_core.dart","src\\\\runner\\\\reporter\\\\expanded.dart"]
```
And from the actual source map on disk (`packages/test_core/test_core.ddc.js.map`):

```
"sources":["src\\runner\\engine.dart","src\\runner\\load_suite.dart","test_core.dart","src\\runner\\reporter\\expanded.dart"]
```

I would expect to get consistent separators on all platforms (url style with `/`).

**Comment by Markzipan** [comment]
Is there a simple repro for this? I'm not seeing this on my trivial Windows + internal tests.

**Comment by jakemac53** [comment]
I was reproducing it by building the `_test` directory under the [build_runner](https://github.com/dart-lang/build) repo, so:

```
git clone https://github.com/dart-lang/build
cd build/_test
pub run build_runner build test
```

And then you can look at `.dart_tool/build/generated/test_core/lib/test_core.ddc.js.map`.
