### ISSUE TITLE
Bug Adding Doubles: Fractions

### ISSUE THREAD

**Issue by natgross** [dart-lang/sdk#38815]
Simply adding 0.x or 0.xy to a double results in an inaccurate precision result. 
Following is a code snippet and result output:

```
void test1() {
  print('Test 1:');
  double d = 1.0;
  for (int i = 0; i < 30; i++) {
    d = d + 0.1;
    print('$i: $d ');
  }
}
void test2() {
  print('Test 2:');
  double d = 1.0;
  for (int i = 0; i < 30; i++) {
    d = d + 0.01;
    print('$i: $d ');
  }
}
```
===================================================

Test 1: (d = d + 0.1)
0: 1.1 
1: 1.2000000000000002 
2: 1.3000000000000003 
3: 1.4000000000000004 
4: 1.5000000000000004 
5: 1.6000000000000005 
6: 1.7000000000000006 
7: 1.8000000000000007 
8: 1.9000000000000008 
9: 2.000000000000001 
10: 2.100000000000001 
11: 2.200000000000001 
12: 2.300000000000001 
13: 2.4000000000000012 
14: 2.5000000000000013 
15: 2.6000000000000014 
16: 2.7000000000000015 
17: 2.8000000000000016 
18: 2.9000000000000017 
19: 3.0000000000000018 
20: 3.100000000000002 
21: 3.200000000000002 
22: 3.300000000000002 
23: 3.400000000000002 
24: 3.500000000000002 
25: 3.6000000000000023 
26: 3.7000000000000024 
27: 3.8000000000000025 
28: 3.9000000000000026 
29: 4.000000000000003 
------------------------------------------------
Test 2: (d = d + 0.01)
0: 1.01 
1: 1.02 
2: 1.03 
3: 1.04 
4: 1.05 
5: 1.06 
6: 1.07 
7: 1.08 
8: 1.09 
9: 1.1 
10: 1.11 
11: 1.12 
12: 1.1300000000000001 
13: 1.1400000000000001 
14: 1.1500000000000001 
15: 1.1600000000000001 
16: 1.1700000000000002 
17: 1.1800000000000002 
18: 1.1900000000000002 
19: 1.2000000000000002 
20: 1.2100000000000002 
21: 1.2200000000000002 
22: 1.2300000000000002 
23: 1.2400000000000002 
24: 1.2500000000000002 
25: 1.2600000000000002 
26: 1.2700000000000002 
27: 1.2800000000000002 
28: 1.2900000000000003 
29: 1.3000000000000003

**Comment by mraleph** [comment]
That's just how floating point arithmetic works. `0.1` is not representable precisely as a double value.

See https://floating-point-gui.de/ for more details.

**Comment by natgross** [comment]
In Excel (or any calculator) I do get the results I expected. Seems like those do some rounding internally first.
