### ISSUE TITLE
Analyzer seems to have no nullability info for functionFormalParameter

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#38811]
Consider the following program:

```dart
void f1(g1()) {}
void f2(g2()?) {}
void f3({g3()?}) {} // 1.

main() {
  int i = null; // 2.
  f1(null); // 3.
  f2(null); // 4.
}
```

With `dartanalyzer --enable-experiment=non-nullable` from commit 7b9a26ee6f2961a938f970d98dc127b894a3ba5e we get the following output:

```
ERROR|COMPILE_TIME_ERROR|MISSING_DEFAULT_VALUE_FOR_PARAMETER|/usr/local/google/home/eernst/lang/dart/scratch/201910/n016.dart|3|10|2|The parameter 'g3' can't have a value of 'null' because of its type, so it must either be a required parameter or have a default value.
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/201910/n016.dart|6|11|4|A value of type 'Null' can't be assigned to a variable of type 'int'.
```

However, this means the following:

- We get a compile-time error at (1), so analysis fails to detect that the type of the parameter `g3` is nullable (so it's OK for `g3` to be optional).
- We get an error at (2), which confirms that regular null checking is active.
- We get _no_ error at (3), so the parameter of `f1` is considered nullable, but it is declared non-nullable.
- We get _no_ error at (4), so the parameter of `f2` is considered nullable.

Looks like every function formal parameter is considered nullable at call sites, no matter what the declaration says, but for `required` checking it's always considered non-nullable?

**Comment by eernstg** [comment]
Ah, delicious, then we need to consider 'nullable' as a floating point number rather than a boolean. ;-)

**Comment by stereotype441** [comment]
@scheglov is going to have a look

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/121801

**Comment by scheglov** [comment]
The first example is fixed.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/121922 will fix [the example](https://github.com/dart-lang/sdk/issues/38811#issuecomment-540621921) with `FutureOr<int>? k`.
