### ISSUE TITLE
Unable to pass target aspectRatio to instantiateImageCodec 

### ISSUE THREAD

**Issue by BharathMG** [dart-lang/sdk#38827]
## Use case

When displaying images from network with unknown size, we have no way to calculate `targetWidth` and `targetHeight` to be able to pass as parameters to `instantiateImageCodec` in `painting.dart` to scale the images.

## Proposal

It will be really great if we could just pass the desired aspect ratio with image bytes just like we currently pass `targetWidth` and `targetHeight` in `instantiateImageCodec`. 

I opened this issue in Flutter repo here: https://github.com/flutter/flutter/issues/42432

**Comment by a-siva** [comment]
@BharathMG your initial issue report against Flutter was the correct place for filing this issue 'dart:ui' is a Flutter component and your request will be tracked there. I am closing this issue as there is nothing Dart specific here.
