### ISSUE TITLE
DDC stack traces with extension methods look odd

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38837]
Stack traces contain stuff like: ```Textify$124get$35text```

Both toString() and stack frames themselves (during debugging) show up like this, and we're seeing this across Flutter web, Flutter devtools, webdev, and internal.

State of our current stack trace post-processing:

* Running with webdev loads the mapper in build/build_web_compilers/web/stack_trace_mapper.dart.

* Flutter web depends on dev_compiler/web/stack_trace_mapper.dart (hard-coded here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/web_fs.dart#L389) to process the stringified stack trace. I suspect google3 does the same thing.

* Flutter devtools depends on webdev/dwds/debugging/debugger.dart to process the stack frame (but the stringified stack message is still processed by the mapper in build_web_compilers).

So whenever the scheme used for renaming JS identifiers/names changes (either in Kernel or DDC), we need to update build/build_web_compilers/web/stack_trace_mapper.dart (mapStackTrace) + copy it over to dev_compiler/web AND update webdev/dwds/debugging/debugger.dart (dartFramesFor).

cc: @sigmundch

**Comment by Markzipan** [comment]
Fixes out at: 
https://github.com/dart-lang/build/pull/2496
https://github.com/dart-lang/webdev/pull/723
https://dart-review.googlesource.com/c/sdk/+/121440

**Comment by vsmenon** [comment]
Can this be closed now?
