### ISSUE TITLE
Analyzer uses the setter type for resolution of postfix `++`, should use the getter type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38833]
Consider the following code:
```dart
class C {
  dynamic get x => 0;
  void set x(Object value) {}
  f() => x++;                 // (1)
}
```
The CFE accepts this without complaint.  The analyzer reports the error `The operator '+' isn't defined for the class 'Object'.` at (1).

I believe the CFE behavior is correct, because in effect, this code desugars to:
```dart
  f() {
    var v = x;
    x = v + 1;
    return v;
  }
```
So the type of `v` should be `dynamic`, and therefore `v + 1` should be allowed.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131220

**Comment by parlough** [comment]
I believe this was fixed by https://github.com/dart-lang/sdk/commit/489c0be8930c696bdcb27fc7a75dde4072db525b

Testing now results in no complaints by the analyzer.

**Comment by scheglov** [comment]
Oh, I probably forgot to close the issue.
Thank you!
