### ISSUE TITLE
Required Named Parameters in VM

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#38843]
CFE is populating an isRequired flag on function parameters. We need to support this flag in the VM.

Part of #37479

**Comment by franklinyow** [comment]
Any update?

**Comment by liamappelbe** [comment]
Working on it. Mailing the first CL today. This doesn't block unforking though.

**Comment by franklinyow** [comment]
If this does not block unforking, please take a look and decide if this could be moved under #40106 or #40107.
