### ISSUE TITLE
Implementation of NNBD strong checking mode in the VM

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#38845]
Support the strong nullability checking modes in the VM.

The strong checking mode is set globally via a command line flag (this flag doesn't exist yet). The checks also depend on whether a library is opted in or not. We also want to support a debugging mode that mixes weak and strong, aborting if the weak check passes but the strong check fails (to help users migrate their libraries).

Part of #37479

Dependent issues -

Migrate "dart:profiler" tests to NNBD #40142
Migrate "dart:developer" tests to NNBD #40140
Migrate "dart:typed_data" tests to NNBD #40139
Migrate "dart:convert" tests to NNBD #40138
Expect.type([null] is! List<int>) fails on Instance(length:1) of '_GrowableList' #39820

**Comment by a-siva** [comment]
Can nthis issue be closed as done?

**Comment by a-siva** [comment]
@crelier @liamappelbe can this issue be marked closed, all the sub issues listed in the description are closed.

**Comment by liamappelbe** [comment]
My parts are done. If @crelier is done too then we can close it.

**Comment by crelier** [comment]
I am not aware of any missing feature. It's only bug fixing from now on. Closing.
