### ISSUE TITLE
Drop To Frame

### ISSUE THREAD

**Issue by nbros** [dart-lang/sdk#38852]
Hello,

Eclipse has a feature in its Java debugger called "Drop To Frame" that allows selecting a frame in the call stack while paused in the debugger and resetting execution from the beginning of that frame.

I use it all the time in Java and I believe it could be useful in Dart too.

See for example https://www.vogella.com/tutorials/EclipseDebugging/article.html#drop-to-frame

Apparently the deprecated Eclipse-based Dart Editor used to have it too:
https://books.google.fr/books?id=F2AnCgAAQBAJ&pg=PA42&lpg=PA42&dq=dart+%22drop+to+frame%22&source=bl&ots=v1SpgCbuz_&sig=ACfU3U02y9m8dhQc2d8WwNhMbQUurcE8Zw&hl=en&sa=X&ved=2ahUKEwi65qP1uZblAhWMHhQKHTGzDw8Q6AEwCnoECAkQAQ

**Comment by rmacnak-google** [comment]
This already exists. Dart calls it "rewind".
