### ISSUE TITLE
How to reverse strings that contain surrogate pairs in Dart?

### ISSUE THREAD

**Issue by vargavince91** [dart-lang/sdk#38854]
I was playing with algorithms using Dart and as I actually followed TDD, I realized that my code has some limitations.

I was trying to reverse strings as part of an interview problem, but I couldn't get the surrogate pairs correctly reversed.

    const simple = 'abc';
    const emoji = '🍎🍏🐛';
    const surrogate = '👮🏽‍♂️👩🏿‍💻';

    String rev(String s) {
        return String.fromCharCodes(s.runes.toList().reversed);
    }

    void main() {
        print(simple);
        print(rev(simple));
        print(emoji);
        print(rev(emoji));
        print(surrogate);
        print(rev(surrogate));
    }

The output:

    abc
    cba
    🍎🍏🐛
    🐛🍏🍎
    👮🏽‍♂️👩🏿‍💻
    💻‍🏿👩️♂‍🏽👮

You can see that the simple emojis are correctly reversed as I'm using the `runes` instead of just simply executing `s.split('').toList().reversed.join('');` but the surrogate pairs are reversed incorrectly.

**How can I reverse a string that might contain surrogate pairs using the Dart programming language?**

**Comment by lrhn** [comment]
Using `runes` is correct for surrogate pairs, but not for your problem, which is grapheme clusters consisting of more than one code point.

A surrogate pair is just a single code point stored as two 16-bit integers. Reversing a the code points of a string can be done by 
```dart
String revCP(String s) => String.fromCharCodes(s.runes.toList().reversed());
```
That reversesthe code points without reversing the integers of a single surrogate pair.

Emojis like this consists of more than one codepoint grouped into a single *grapheme cluster* (many of the code points are also stored as surrogate pairs). 
To properly reverse such a string at the grapheme cluster level, you need to recognize the grapheme cluster boundaries. Dart does not currently expose that functionality.

**Comment by vargavince91** [comment]
Thank you @lrhn for your answer, I think it helped me understand the issue at hand much better.

For the record, I also asked on [StackOverflow](https://stackoverflow.com/questions/58360414/how-to-reverse-strings-that-contain-surrogate-pairs-in-dart), and someone recommended the [`grapheme_splitter`](https://pub.dev/packages/grapheme_splitter) package.

**Comment by lrhn** [comment]
That package probably works. I'm also working on a package with slightly higher-level, but otherwise similar, functionality. I hope to release a beta soon-ish.

**Comment by mit-mit** [comment]
Please see https://github.com/dart-lang/language/issues/685

**Comment by vargavince91** [comment]
It's great to see this issue addressed in the Flutter Survey.
