### ISSUE TITLE
[vm/ffi] Remove deprecated methods before D26

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38860]
Before we ship D26, we should remove deprecated methods from the `dart:ffi` API:

* https://github.com/dart-lang/sdk/issues/37773 `load` and `store` (replaced by `.val`, `.val=`, `.ref`, `[]`, and `[]=`)
* https://github.com/dart-lang/sdk/issues/38520 `allocate` and `free` (moved to `package:ffi`)
* https://github.com/dart-lang/sdk/issues/38610 `asExternalTypedData` (replaced by `asTypedList` extension method)

In order to be able to deprecate these at all in the sdk, we need to update the packages that are pulled in by DEPS (`package:ffi` and `package:tflite_native`).

We might also want to think about fixing g3.

cc @mkustermann @sjindel-google

**Comment by vsmenon** [comment]
If this is D26, can someone take ownership?

**Comment by sjindel-google** [comment]
I believe Daco is already working on this.

**Comment by mkustermann** [comment]
The [cl/121422](https://dart-review.googlesource.com/c/sdk/+/121422) is up and reviewed.

It's blocked on getting our github mirror working again

**Comment by dcharkes** [comment]
https://dart-review.googlesource.com/c/sdk/+/121708 CL ready, but blocked by CL addressing https://github.com/dart-lang/sdk/issues/38611.
