### ISSUE TITLE
dart2native "Precompilation not supported on IA32" on 64-bit Core i7

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#38877]
Running dart2native on macOS crashes saying "Precompilation not supported on IA32".

```
dart2native bin/main.dart --output=main

../../runtime/vm/compiler/jit/compiler.cc: 96: error: Precompilation not supported on IA32

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.

Failed to generate native files:
Generating AOT snapshot failed!
```

Is this targeting the right instruction set? I'm running on an Intel Core i7, which is 64-bit.

macOS 10.14.6 (Mojave)
Dart SDK 2.6.0-dev.7.0

**Comment by a-siva** [comment]
@johnpryan did you build your own version of the sdk from sources or did you download and install it ?

If you downloaded it, did you download the x64 version or the ia32 version? You need to download the x64 version as dart2native is supported only on the x64 version.

**Comment by johnpryan** [comment]
Ah, right... thanks for the help
