### ISSUE TITLE
RewindCommand does not properly check "count"

### ISSUE THREAD

**Issue by nbros** [dart-lang/sdk#38888]
Hello,

I think I found a bug in the implementation of the debugger's `RewindCommand` :

```dart
int count = 1;
if (args.length == 1) {
  count = int.parse(args[0]);
} else if (args.length > 1) {
  debugger.console.print('rewind expects 0 or 1 argument');
  return;
} else if (count < 1 || count > debugger.stackDepth) {
  debugger.console
      .print('frame must be in range [1..${debugger.stackDepth - 1}]');
  return;
}
```

This line:
https://github.com/dart-lang/sdk/blob/50f7ae9c5d3f8c4ec864d5e8739a42fd102c93f3/runtime/observatory/lib/src/elements/debugger.dart#L429

can only be executed if args.length is 0. In this case, count is always 1 and the test doesn't actually test anything. 

So I believe it should be:

```dart
int count = 1;
if (args.length == 1) {
  count = int.parse(args[0]);
  if (count < 1 || count > debugger.stackDepth) {
    debugger.console
        .print('frame must be in range [1..${debugger.stackDepth - 1}]');
    return;
  }
} else if (args.length > 1) {
  debugger.console.print('rewind expects 0 or 1 argument');
  return;
}
```

**Comment by parlough** [comment]
I went and submitted this fix with a few small changes in the following CL: https://dart-review.googlesource.com/c/sdk/+/148567

**Comment by parlough** [comment]
Sorry forgot to add closing message to commit. 

Fixed by https://github.com/dart-lang/sdk/commit/1fba93f7c72eefae3701a63381aab521ffd79729
