### ISSUE TITLE
Use SecTrustEvaluateWithError instead of SecTrustEvaluate in runtime/bin/security_context_macos.cc

### ISSUE THREAD

**Issue by frapontillo** [dart-lang/sdk#38887]
When trying to build Fuchsia following the step-by-step guide on the [official page](https://fuchsia.dev/fuchsia-src/getting_started.md#build_fuchsia), I am getting a Dart runtime-related failure:

```
[5622/49504] CXX host_x64/obj/third_party/dart/runtime/bin/dart_io_api.security_context_macos.cc.o
FAILED: host_x64/obj/third_party/dart/runtime/bin/dart_io_api.security_context_macos.cc.o 
../../prebuilt/third_party/clang/mac-x64/bin/clang++ -MD -MF host_x64/obj/third_party/dart/runtime/bin/dart_io_api.security_context_macos.cc.o.d -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DTARGET_ARCH_X64 -DNDEBUG -DDART_USE_BYTECODE -DTARGET_OS_FUCHSIA -I../../third_party/dart/runtime -I../../third_party -I../.. -Ihost_x64/gen -I../../third_party/dart/runtime/include -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../third_party/zlib -I../../third_party/boringssl/src/include -fcolor-diagnostics -fexperimental-new-pass-manager -fcrash-diagnostics-dir=clang-crashreports --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fdebug-prefix-map=/Users/francesco.pontillo/Workspace/fuchsia/out/default=. -fdebug-prefix-map=/Users/francesco.pontillo/Workspace/fuchsia/out=.. -fdebug-prefix-map=/Users/francesco.pontillo/Workspace/fuchsia=../.. -no-canonical-prefixes -fomit-frame-pointer -g3 -Wall -Wextra -Wnewline-eof -Wno-unused-parameter -Wno-unknown-warning-option -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wno-c99-designator -Wno-reorder-init-list -Wno-sizeof-array-div -Wno-int-in-bool-context -fvisibility=hidden -O0 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility-inlines-hidden -std=c++17 -stdlib=libc++ -faligned-allocation -fno-exceptions -fno-rtti -c ../../third_party/dart/runtime/bin/security_context_macos.cc -o host_x64/obj/third_party/dart/runtime/bin/dart_io_api.security_context_macos.cc.o
../../third_party/dart/runtime/bin/security_context_macos.cc:188:12: error: 'SecTrustEvaluate' is deprecated: first deprecated in macOS 10.15 [-Werror,-Wdeprecated-declarations]
  status = SecTrustEvaluate(trust.get(), &trust_result);
           ^~~~~~~~~~~~~~~~
           SecTrustEvaluateWithError
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:353:10: note: 'SecTrustEvaluate' has been explicitly marked deprecated here
OSStatus SecTrustEvaluate(SecTrustRef trust, SecTrustResultType *result)
         ^
1 error generated.
[5633/49504] ACTION //third_party/go:makefuchsia(//build/toolchain/fuchsia:x64)
ninja: build stopped: subcommand failed.
```

There is more information on the deprecation of `SecTrustEvaluate` on the [Apple developer documentation](https://developer.apple.com/documentation/security/1394363-sectrustevaluate?language=objc). It needs to be replaced with [`SecTrustEvaluateWithError`](https://developer.apple.com/documentation/security/2980705-sectrustevaluatewitherror?language=objc) instead.

**Comment by zanderso** [comment]
@a-siva @athomas Does this happen when building the standalone Dart SDK on Catalina?

Has this error been encountered when building the Dart SDK for the Flutter engine on Catalina? @christopherfujino @digiter

If the answer to both of those is 'no', then I would guess this is popping up in the Fuchsia build due to different toolchain versions @rmacnak-google.

Either way, the fix is to follow the advice, and switch to `SecTrustEvaluateWithError`. I think maybe @bkonyi was most recently in this code.

**Comment by athomas** [comment]
I don't have access to a Catalina device currently, we've only tried running, but not building on Catalina.

**Comment by a-siva** [comment]
Changed title of issue to use SecTrustEvaluateWithError instead of SecTrustEvaluate

**Comment by christopherfujino** [comment]
@digiter as far as I know we've never built the sdk on Catalina.

**Comment by digiter** [comment]
> @digiter as far as I know we've never built the sdk on Catalina, unless you've done it.

I thought using flutter implies building dart sdk. OK, we haven't tried building dart sdk on Catalina.

**Comment by bkonyi** [comment]
Given that `SecTrustEvaluateWithError` wasn't introduced until SDK 10.14 it might make more sense to just swallow this deprecation warning unless there's a way to determine the MacOS SDK version at compile time. Would there be any objection to that?

**Comment by zanderso** [comment]
You can use the macOS version macros in `AvailabilityMacros.h` as in platform/utils_macos.h: https://github.com/dart-lang/sdk/blob/master/runtime/platform/utils_macos.h#L12
