### ISSUE TITLE
Exception while using a UseFullHexValuesForFlutterColors

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#38884]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050, 2048x1152  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ExpressionFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6825:15)
#20     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#21     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:438:11)
#22     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6820:49)
#23     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#24     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#25     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#26     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#29     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#31     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#32     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#33     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#34     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#35     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3585:18)
#36     RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:827:10)
#37     LinterVisitor.visitExpressionFunctionBody (package:analyzer/src/lint/linter_visitor.dart:228:11)
#38     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3581:15)
#39     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5085:12)
#40     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:923:10)
#41     LinterVisitor.visitFunctionExpression (package:analyzer/src/lint/linter_visitor.dart:312:11)
#42     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5079:49)
#43     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#44     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#45     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#46     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#47     NodeListImpl.accept (pack...
```

For additional log information, please append the contents of
file:///private/var/folders/np/gmysjh1j2159hv7wssjzrw440028jd/T/report.txt.

---

Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ExpressionFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6825:15)
#20     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#21     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:438:11)
#22     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6820:49)
#23     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#24     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#25     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#26     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#29     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#31     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#32     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#33     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#34     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#35     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3585:18)
#36     RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:827:10)
#37     LinterVisitor.visitExpressionFunctionBody (package:analyzer/src/lint/linter_visitor.dart:228:11)
#38     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3581:15)
#39     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5085:12)
#40     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:923:10)
#41     LinterVisitor.visitFunctionExpression (package:analyzer/src/lint/linter_visitor.dart:312:11)
#42     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5079:49)
#43     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#44     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#45     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#46     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#48     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#49     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#50     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#51     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#52     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#53     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#54     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#55     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#56     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1164:10)
#57     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:541:11)
#58     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#59     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#60     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#61     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#62     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#63     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#64     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#65     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#66     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#67     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#68     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#69     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#70     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#71     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#72     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#73     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#74     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#75     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#76     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#77     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#78     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#79     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#80     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#81     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#82     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#83     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#84     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#85     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#86     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#87     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#88     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#89     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#90     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#91     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#92     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#93     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#94     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#95     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#96     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#97     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#98     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#99     _rootRun (dart:async/zone.dart:1124:13)
#100    _CustomZone.run (dart:async/zone.dart:1021:19)
#101    _runZoned (dart:async/zone.dart:1516:10)
#102    runZoned (dart:async/zone.dart:1463:12)
#103    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#104    Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#105    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#106    _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#107    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#108    CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#109    new Future.sync (dart:async/future.dart:224:31)
#110    CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#111    _rootRun (dart:async/zone.dart:1124:13)
#112    _CustomZone.run (dart:async/zone.dart:1021:19)
#113    _runZoned (dart:async/zone.dart:1516:10)
#114    runZoned (dart:async/zone.dart:1463:12)
#115    CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#116    CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#117    Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#118    main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#119    _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#120    main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#121    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#122    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1571112249283 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","overrides":[{"offset":1151,"length":11,"superclassMember":{"
1571112249286 <= {"event":"flutter.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":13082,"code
1571112249292 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1094,"uri":"package:flutter_egamebook/widgets/active_choice_block.dart","items":[{"label":"ActiveChoiceB
1571112249296 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1571112249296 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","classes":[],"members":[]}}
1571112249583 => {"id":"10453","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart":{"type":"add","content":"import 'dart:col
1571112249584 <= {"id":"10453","result":{}}
1571112249584 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1571112249588 => {"id":"10454","method":"edit.getFixes","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","offset":11497},"clientRequestTime":1571112249588}
1571112249592 => {"id":"10455","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","offset":11497,"length":0},"clientRequestTime":157
1571112249644 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/
1571112249644 <= {"id":"10454","result":{"fixes":[]}}
1571112249644 => {"id":"10456","method":"edit.getFixes","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","offset":11497},"clientRequestTime":1571112249644}
1571112249645 <= {"id":"10455","result":{"assists":[]}}
1571112249647 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":25},{"typ
1571112249651 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","regions":[{"offset":7,"length":17,"targets":[0]},{"offset":
1571112249653 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT
1571112249653 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","overrides":[{"offset":1151,"length":11,"superclassMember":{"
1571112249656 => {"id":"10457","method":"edit.getFixes","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","offset":11497},"clientRequestTime":1571112249656}
1571112249657 <= {"event":"flutter.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":13080,"code
1571112249657 <= {"id":"10456","result":{"fixes":[]}}
1571112249657 <= {"id":"10457","result":{"fixes":[]}}
1571112249663 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1094,"uri":"package:flutter_egamebook/widgets/active_choice_block.dart","items":[{"label":"ActiveChoiceB
1571112249663 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1571112249663 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","classes":[],"members":[]}}
1571112249947 => {"id":"10458","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart":{"type":"add","content":"import 'dart:col
1571112249948 <= {"id":"10458","result":{}}
1571112249948 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1571112249959 => {"id":"10459","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/widgets/active_choice_block.dart","offset":11498,"length":0},"clientRequestTime":157
1571112249999 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl 
```

**Comment by pq** [comment]
Thanks for the report @filiph!  This one is fixed w/ https://github.com/dart-lang/linter/commit/00c8317a3874cc0a1cb0e07597e379fea400306c.
