### ISSUE TITLE
Error "Explicit extension application cannot be used as an expression" when extending operators

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#38895]
A have a Person class:

```dart
class Person {
  String name;
  int age;

  @override
  String toString() => "$name [$age]";

}
```

I have two **OPERATOR** extensions:

```dart
extension PersonExtensions on Person {
  Person operator +(Person other) => Person(); //just doing nothing
}

extension OtherPersonExtensions on Person {
  Person operator +(Person other) => Person(); //just doing nothing
}
```

If I try to force using one of the extensions with its + operator like this:

```dart
void main(List<String> arguments) {
  var daniel = Person()
    ..name = "Daniel"
    ..age = 30;

  var robert = Person()
    ..name = "Robert"
    ..age = 28;

  var toPrint = OtherPersonExtensions(daniel) + robert; //forcing the usage

  print("$toPrint");
}
```

I get this error:

```
example/main.dart:13:17: Error: Explicit extension application cannot be used as an expression.
  var toPrint = OtherPersonExtensions(daniel) + robert;
                ^^^^^^^^^^^^^^^^^^^^^
```

So, is it a bug or it is impossible to resolve **operator overloading extensions** with conflicts?

**Comment by a-siva** [comment]
Your case works fine for
extension PersonExtensions on Person {
  Person plus(Person other) => Person(); //just doing nothing
}
extension OtherPersonExtensions on Person {
  Person plus(Person other) => Person(); //just doing nothing
}
var toPrint = OtherPersonExtensions(daniel).plus(robert)

**Comment by shinayser** [comment]
> Your case works fine for
> extension PersonExtensions on Person {
> Person plus(Person other) => Person(); //just doing nothing
> }
> extension OtherPersonExtensions on Person {
> Person plus(Person other) => Person(); //just doing nothing
> }
> var toPrint = OtherPersonExtensions(daniel).plus(robert)

Well.. of course it will work, you changed the operator extension for a standard function. The bug report is exactly for operator extensions.

**Comment by lrhn** [comment]
Looks like a bug in the front-end. The analyzer accepts the program.

To reproduce:
```dart
extension X on bool {                                                                                                                            
  bool operator+(bool other) => this | other;                                                                                                    
}                                                                                                                                                
main() {                                                                                                                                         
  print(false + true);                                                                                                                           
  print(X(false) + true);                                                                                                                        
}                                                                                                                                                
```
These two print statements should both print true. The latter is rejected by the front-end.
