### ISSUE TITLE
Analyzer incorrectly handles FutureOr<A> <: FutureOr<B>

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38904]
The analyzer performs the following incorrect shortcut:

https://github.com/dart-lang/sdk/blob/0881a4a691869bab507a73e9cd62068ed490bd68/pkg/analyzer/lib/src/generated/type_system.dart#L665-L666

It's true that `A <: B` implies `FutureOr<A> <: FutureOr<B>`, but the converse is false.

`tests/language_2/subtyping_static/future_or_subtype_test` exercises this behavior.

**Comment by srawlins** [comment]
I _believe_ this is fixed now. I reproduced the test without `package:expect` as follows:

```dart
import 'dart:async';

class A implements Future<Future<A>> {
  @override
  noSuchMethod(Invocation _) {}
}

void main() {
  //Expect.subtype<FutureOr<A>, FutureOr<Future<A>>>();
}

void f(FutureOr<A> foa, FutureOr<Future<A>> fofa) {
  fofa = foa;
}
```

This test examines assignability, not subtyping. Not sure what a better test would be. Anyways analyzer accepts this now, which I think asserts that `FutureOr<A>` is a subtype of `FutureOr<Future<A>>`.

**Comment by fishythefish** [comment]
If I want to check `Foo <: Bar`, I often use `<Foo>[] is List<Bar>`.

**Comment by srawlins** [comment]
Hmmm. Like the analyzer would flag that statically? With the `unrelated_type_equality_checks` lint rule or something?

**Comment by eernstg** [comment]
How about this?:
```dart
import 'dart:async';

class A implements Future<Future<A>> {
  @override
  noSuchMethod(Invocation _) {}
}

void f<X extends Y, Y>() {}

void main() {
  f<FutureOr<A>, FutureOr<Future<A>>>(); // OK iff subtyping holds.
}
```
Works, too! ;-)

**Comment by fishythefish** [comment]
Sorry, I should have clarified. If the analyzer happens to have a unit-testable version of `is` (or `as`), then it could be invoked with those arguments. Otherwise, for an end-to-end test, what Erik suggests works great. (Note that these two tricks put together are basically how `Expect.subtype` is defined.)

**Comment by srawlins** [comment]
Thanks @eernstg and @fishythefish!

I like these tricks. And I'll close this as fixed.
