### ISSUE TITLE
Incorrect "no effect" error with "!" on F-bounded type

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38901]
This may be because I don't fully understand F-bounded quantification, but if I take this program:

```dart
class LinkedList<E extends Entry<E>> {
  test(E entry) {
    entry.field!;
  }
}

class Entry<T> {
  T? field;
}
```

And analyze it with:

```
dartanalyzer --enable-experiment=non-nullable example.dart
```

I get:

```
  error • The '!' will have no effect because the target expression cannot be null at example.dart:4:16 • unnecessary_non_null_assertion
```

I'm pretty sure that error is wrong. In particular, consider:

```
class LinkedList<E extends Entry<E>> {
  test(E entry) {
    entry.field!;
  }
}

class Entry<T> {
  T? field;
}

main() {
  LinkedList<SomeEntry>().test(SomeEntry());
}

class SomeEntry extends Entry<SomeEntry> {}
```

It looks like `field` definitely *can* be `null` here, so the `!` is doing something useful.

cc @stereotype441 @scheglov @leafpetersen

**Comment by scheglov** [comment]
We had incorrect types because of missing combining of nullability suffixes.
https://dart-review.googlesource.com/c/sdk/+/121921 fixed this.

![image](https://user-images.githubusercontent.com/384794/67031207-e0aa6e00-f0c5-11e9-8e15-22e6d1f7718d.png)
