### ISSUE TITLE
CFE incorrectly handles FutureOr<A> <: FutureOr<B>

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38905]
The CFE performs the following incorrect shortcut:

https://github.com/dart-lang/sdk/blob/dd5edfe0c2458cc1c8b0e7f6f17c96f4508d49b0/pkg/kernel/lib/type_environment.dart#L264-L265

It's true that `A <: B` implies `FutureOr<A> <: FutureOr<B>`, but the converse is false.

`tests/language_2/subtyping_static/future_or_subtype_test` exercises this behavior.

**Comment by stefantsov** [comment]
Good find!  Proposed fix: https://dart-review.googlesource.com/c/sdk/+/135301
