### ISSUE TITLE
VM incorrectly handles FutureOr<A> <: FutureOr<B>

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38906]
Consider the following code:

```dart
import 'dart:async';

class A implements Future<Future<A>> {
  // Ignore missing implementation
  @override
  noSuchMethod(Invocation invocation) {}
}

void main() {
  List<A> as = [];
  List<FutureOr<A>> foas = [];
  print(as is List<Future<A>>);
  print(foas is List<FutureOr<Future<A>>>);
}
```

This should print
```
false
true
```

However, the VM prints
```
false
false
```

Across the board, our implementations seem to incorrectly assume that `FutureOr<A> <: FutureOr<B>` iff `A <: B`. In fact, `A <: B` does imply `FutureOr<A> <: FutureOr<B>`, but the converse is false. (In the above example, `B := Future<A>`. It's true that `FutureOr<A> <: FutureOr<Future<A>>`, but we incorrectly reduce this to `A <: Future<A>`, which is false.)

`tests/language_2/subtyping_static/future_or_subtype_test` also exercises this behavior, but it'll continue to fail on the VM until the CFE fixes the same issue - see #38905.

**Comment by crelier** [comment]
Type inference attributes runtime type `List<A>` to both variables `as` and `foas`.
Therefore, printing twice `false` is the correct outcome.

**Comment by fishythefish** [comment]
Reopening because I believe this is still an issue in a situation where no type inference occurs:

`tests/language_2/subtyping_static/future_or_subtype_test.dart`
```dart
import 'dart:async';
import 'package:expect/expect.dart';

class A implements Future<Future<A>> {
  @override
  noSuchMethod(Invocation _) {}
}

void main() {
  Expect.notSubtype<A, Future<A>>();
  Expect.subtype<FutureOr<A>, FutureOr<Future<A>>>();
}
```

**Comment by crelier** [comment]
The VM does not get a chance to run this test, as the front-end rejects it:
```
../../bug.dart:11:10: Error: Type argument 'FutureOr<A>' doesn't conform to the bound 'Super' of the type variable 'Sub' on 'Expect.subtype'.
 - 'FutureOr' is from 'dart:async'.
 - 'A' is from '../../bug.dart'.
 - 'Expect' is from 'package:expect/expect.dart' ('pkg/expect/lib/expect.dart').
Try changing type arguments so that they conform to the bounds.
  Expect.subtype<FutureOr<A>, FutureOr<Future<A>>>();
         ^
pkg/expect/lib/expect.dart:637:23: Context: This is the type variable whose bound isn't conformed to.
  static bool subtype<Sub extends Super, Super>() {
                      ^

```

**Comment by crelier** [comment]
I am reassigning this issue to CFE.

**Comment by stefantsov** [comment]
The CFE fix has just landed: https://github.com/dart-lang/sdk/commit/6a2c350a3e0002d9d525f336505c5e18f352a758

**Comment by fishythefish** [comment]
Reassigning to VM - #38905 is closed and the test passes on the CFE bots, but continues to fail on the VM.

**Comment by crelier** [comment]
Thanks! I'll fix it in the VM.

Note that the fixed CFE reports an error if I add this line:
Expect.subtype<FutureOr<A>, Future<A>>();

**Comment by fishythefish** [comment]
I think that error is expected - after instantiating to bounds, `FutureOr` is a top type, but `Future` isn't.

**Comment by crelier** [comment]
Sorry, I did not properly escape the code. I edited my comment above. I meant:
`Expect.subtype<FutureOr<A>, Future<A>>();
`

**Comment by fishythefish** [comment]
I believe the CFE is still correct. In order to have `FutureOr<A> <: Future<A>`, we must have both `A <: Future<A>` and `Future<A> <: Future<A>`. The latter is obviously true, but the former is false.

**Comment by crelier** [comment]
I see. The spec indeed states:
```
Left FutureOr:
  if T0 is FutureOr<S0> then:
    T0 <: T1 iff Future<S0> <: T1 and S0 <: T1
```
The "Or" in "FutureOr" translates to an "and" in the rules, Which is surprising.

In the Right FutureOr rule, it translates to an "or":
```
Right FutureOr: 
  if T1 is FutureOr<S1> then:
    T0 <: T1 iff any of the following hold:
      either T0 <: Future<S1>
      or T0 <: S1
      or T0 is X0 and X0 has bound S0 and S0 <: T1
      or T0 is X0 & S0 and S0 <: T1
```

**Comment by fishythefish** [comment]
Yes, there's a kind of duality at play here. The operations "and" and "or" are dual to each other (the same way "intersection" and "union" are dual), so when you go from the LHS of a subtype check to the RHS or vice versa, they switch.

This might be clearer in terms of sets. In order to have `A ∪ B ⊆ C`, we must have `A ⊆ C` *and* `B ⊆ C`. But if we instead want `A ⊆ B ∪ C`, then it's sufficient to have `A ⊆ B` *or* `A ⊆ C`.

**Comment by crelier** [comment]
That makes total sense! Thanks for taking the time to illustrate with sets.

**Comment by crelier** [comment]
Fix was reverted.
