### ISSUE TITLE
Static type of `!` does not remove nullability from a type parameter

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38900]
The static type of a `!` expression should be the type of its operand with any nullability removed. In analyzer with the non-nullable experiment enabled, this is working for normal types, but does not seem to work if the type is a nullable type parameter.

If I take:

```dart
class Foo<T> {
  void bad1(T? t) {
    T temp = t!;
  }

  T bad2(T? t) {
    return t!;
  }

  void ok1(int? i) {
    int temp = i!;
  }

  int ok2(int? i) {
    return i!;
  }
}
```

And analyze it using:

```
dartanalyzer --enable-experiment=non-nullable example.dart
```

I get:

```
  error • A value of type 'T' can't be assigned to a variable of type 'T' at example.dart:3:14 • invalid_assignment
  error • The return type 'T' isn't a 'T', as defined by the method 'bad2' at example.dart:7:12 • return_of_invalid_type
  hint • The value of the local variable 'temp' isn't used at example.dart:3:7 • unused_local_variable
  hint • The value of the local variable 'temp' isn't used at example.dart:11:9 • unused_local_variable
```

As I understand it, this program should have no errors. cc @stereotype441 @leafpetersen

**Comment by stereotype441** [comment]
@scheglov can you look at this?

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/38900#issue-507385686 will be addressed by https://dart-review.googlesource.com/c/sdk/+/121881.

https://github.com/dart-lang/sdk/issues/38900#issuecomment-542411318 might be related to type parameter substitution, and we need to land a fix for implicit cast first, possibly https://dart-review.googlesource.com/c/sdk/+/121764.

**Comment by munificent** [comment]
Thanks for the quick turnaround!

**Comment by scheglov** [comment]
The second example will be fixed with https://dart-review.googlesource.com/c/sdk/+/121921.
