### ISSUE TITLE
return duplicate completionItems for the same request

### ISSUE THREAD

**Issue by iamcco** [dart-lang/sdk#38911]
This tracker is for issues related to: **Analyzer**

Environment:

* Dart SDK Version (`dart --version`): `Dart VM version: 2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "macos_x64"`
*  MacOSX

When i edit a dart file outside my flutter project, the LSP service return duplicate completionItems.

dart.dart:
``` dart
void main() {
    prin$
}
```

`$` is cursor position, I check the log of the LSP and find that it return two `print(...)` items just with the difference of `sortText`, which are `999993` and `999994`

log: 

```
{
        "label": "print(…)",
        "kind": 3,
        "detail": "(Object object) → void",
        "sortText": "999993",
        "filterText": "print",
        "insertText": "print",
        "data": {
            "file": "/Users/aioi/development/dart.dart",
            "offset": 17,
            "libId": 91,
            "displayUri": "dart:core",
            "rOffset": 16,
            "rLength": 1
        }
    },
    ....
    {
        "label": "print(…)",
        "kind": 3,
        "detail": "(Object object) → void",
        "sortText": "999994",
        "filterText": "print",
        "insertText": "print",
        "data": {
            "file": "/Users/aioi/development/dart.dart",
            "offset": 17,
            "libId": 91,
            "displayUri": "dart:core",
            "rOffset": 16,
            "rLength": 1
        }
    }
```

This not happen when edit dart file in flutter project.

**Comment by lambdabaa** [comment]
I've reproduced this issue and also confirmed that ML does not create duplicate suggestions or tags. @scheglov knows most about this code.

**Comment by scheglov** [comment]
I can reproduce this for non-pub modules.
The issue is that we include libraries as both available in the context, and available in dependencies.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/121908
