### ISSUE TITLE
Static extension methods - compiler error with named parameters

### ISSUE THREAD

**Issue by filipproch** [dart-lang/sdk#38915]
Hi, I am trying the extension methods in Flutter and have an issue, with the following extension method >

```dart
extension ExtendedGeoAddress on GeoAddress {

  String prettyAddress({
    bool withCountry = false,
    String separator = ', ',
  }) {
    /// ...
  }

}
```

The analyzer doesn't have any problems with it but running the compiler, it fails with the following:
```
Compiler message:
lib/app/clients/clients_list.dart:145:54: Error: The argument type 'CrmClient' can't be assigned to the parameter type 'bool'.
 - 'CrmClient' is from 'package:my_app/domain/crm_client.dart' ('lib/domain/crm_client.dart').
              Text(client.prettyAddress(withCountry: false)
```

So, obviously, it doesn't like the place where I am using the extension method.

- `CrmClient` is a class that implements `GeoAddress`.

It seems like a bug to me.

**Output from `flutter doctor`**
[✓] Flutter (Channel master, v1.10.15-pre.94, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.10.15-pre.94 at /Users/filip/development/flutter
    • Framework revision 532a8fed41 (3 days ago), 2019-10-12 18:58:22 -0700
    • Engine revision eed171ff35
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 965b8cb1d8)

**Comment by mnordine** [comment]
Still not fixed in 2.6.0-dev.8.1

**Comment by johnniwinther** [comment]
I cannot reproduce the error on `2.6.0-dev.8.1`. Do you have a (small) repro?

**Comment by mnordine** [comment]
It is failing on a large project, I will try to reduce it. It should work with a package off https://pub.dev, right?

**Comment by johnniwinther** [comment]
It should. The availability of the feature should only be determined by the version of the sdk.

**Comment by mnordine** [comment]
Still getting the error with the large project, gradually trying to reduce it to reproduce the error in a new project...

**Comment by clicksrv** [comment]
Facing the same issue. Running Dart Version `2.6.0-dev.4.0.flutter-1103600280`.

How do I upgrade to dev 8.1 in Flutter SDK?

**Comment by mraleph** [comment]
@clicksrv you need to upgrade your Flutter installation. Make sure that you are on the `master` channel and run `flutter upgrade`.
