### ISSUE TITLE
Two bangs inserted in expression in package:path/src/context.dart

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38922]
### Steps to reproduce:

1. Check out path package at 1.6.2 (`git checkout 1.6.2`).
2. Migrate to NNBD (e.g. `dart ~/code/dart-sdk/sdk/pkg/dartfix/bin/dartfix.dart --fix=non-nullable --overwrite --outputDir nnbd-i13n .`).
3. Open the migration output for `lib/src/context.dart`. At line 474 we see:

`var fromParsed = _parse(from!!)..normalize();`

o_O

**Comment by srawlins** [comment]
CC @stereotype441 @MichaelRFairhurst seems like a bug in the migrator.

**Comment by stereotype441** [comment]
The code in question looks like this:
```dart
  var fromParsed = _parse(from)..normalize();
```
What's happening is that `EdgeBuilger` visits the subexpression `_parse(from)` twice: once when visiting the entire cascade expression `_parse(from)..normalize()`, and once when visiting the method call `..normalize()`.

I'm working on a fix.
