### ISSUE TITLE
migration via dartfix applies changes at incorrect offsets

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38924]
Steps to reproduce:
1. In a temporary directory (let's call it `$TMP1`), create a file `test.dart` with the following contents:
```dart
main() {
  f(null);
}
f(int i) => g(i);
g(int i) {}
```
2. From a clean checkout of the SDK, run `gclient sync` and build the SDK (I'm currently able to reproduce at f26aa6fff4deb53f8dddacdc1125fb685eea4a93).  Let `$SDK` represent the path to the SDK.
3. Create another temporary directory to hold the HTML output of dartfix (let's call it `$TMP2`)
4. Go into `$TMP1` and run `$SDK/out/ReleaseX64/dart-sdk/bin/dart `$OUT/pkg/dartfix/bin/dartfix.dart --fix=non-nullable -w . --outputDir $TMP2`
5. Examine the file `test.dart`.

Expected result:
```dart
main() {
  f(null);
}
f(int? i) => g(i);
g(int? i) {}
```

Observed result:
```dart
main() {
  f(null);
}
f(int? i) => g(i);
g(in?t i) {}
```

(Note that the second `?` is inserted in the wrong location).

Removing the `--outputDir $TMP2` parameter seems to work around the problem.

**Comment by srawlins** [comment]
I can reproduce this; tried a few times w/ `--outputDir $TMP2` and a few w/o.
