### ISSUE TITLE
verbose_gc_to_bmu_test is failing on various precomp bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#38932]
https://dart.googlesource.com/sdk/+/0b045aea2b0dc40f4770c63dec2ebb99fed06331 introduced failed test.
Failures were approved (on vm-kernel-precomp-linux-debug-x64 and others) to turn the bots green.

**Comment by bkonyi** [comment]
These failures are expected on precomp as the test attempts to launch `dart` by using `Platform.executable` which will actually point at `dart_precompiled_runtime` in the precompiled case.

**Comment by aam** [comment]
Did you want to mark them as skipped on those platforms in status files then so they won't be consuming test cycles?

**Comment by bkonyi** [comment]
Sure. See https://dart-review.googlesource.com/c/sdk/+/121943/.
