### ISSUE TITLE
Please merge dee702264b4ab6f6b634b2e346de5ac7ea08b042 into dev channel

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#38940]
**commit(s) to merge**: dee702264b4ab6f6b634b2e346de5ac7ea08b042

**merge instructions**: clean merge

**reason**: Fixes #38915 

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Merged into 2.6.0-dev.8.1 (61d12745a8a2fedfde8e5644a43baa45ae1a5d9a).
