### ISSUE TITLE
vm/cc/IRTest_InitializingStores test is marked failing on dartkb

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#38946]
I introduced a test which uses slot names which are different between dartkb and dartk modes. 

For now I have just marked it as failing in dartkb mode - but we need to find a way to make this test more robust.

**Comment by liamappelbe** [comment]
Looks like this is crashing, not just failing: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8899336893333737056/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0
