### ISSUE TITLE
Please merge 9f1b0fe102c0ad4599b695974621530f07684290 into dev channel

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#38941]
**commit(s) to merge**: 9f1b0fe102c0ad4599b695974621530f07684290

**merge instructions**: clean merge

**reason**: Fixes #38895 

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
Merged into 2.6.0-dev.8.1 (61d12745a8a2fedfde8e5644a43baa45ae1a5d9a).
