### ISSUE TITLE
Wrong "widget wrapping" when using ternary operators

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#38947]
_I don't know if this is the correct place to post it, some guidance will be welcome._ 

When developing in Flutter and you try to wrap a widget with another widget it works ONLY when not using a ternary operator.

Example, check this code:

![image](https://user-images.githubusercontent.com/1146982/67020577-c6c45780-f0d4-11e9-88a1-e56b8f558284.png)

Now imagine you want to wrap "Text 1" into another widget like this:

![image](https://user-images.githubusercontent.com/1146982/67020623-d9d72780-f0d4-11e9-9990-933f127c7dbb.png)

It is wapping the entire ternary condition: 

![image](https://user-images.githubusercontent.com/1146982/67020705-f4110580-f0d4-11e9-8992-4579f76229ff.png)

This is a pain when you are using thos ternary operators to develop because if you have to wrapp your widget in anything, you will have a lot of headache.

**Comment by srawlins** [comment]
@shinayser I think I see your issue, but to be clear: it looks like the bug is with the "Wrap with new widget" feature of the editor, correct?

**Comment by shinayser** [comment]
I think so, but everytime I think the problem is with the editor, people says to me to post the issue here hahaha.

**Comment by srawlins** [comment]
Fair enough! 😄 Yes it looks like this bug might be with the "analysis server" tool. Thanks for reporting!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/121925

**Comment by shinayser** [comment]
There is another issue, I don't know if its the same (if you want I can open another issue).

But when you press the alt + enter ("quickfix" shortcut on Intellij) it shows no options if the widget is inside **conditions** or **for loop** inside collections, like this:

![image](https://user-images.githubusercontent.com/1146982/67031711-7c4cd600-f0e8-11e9-882f-78bd4254b21e.png)

**Comment by scheglov** [comment]
Works for me with the Dart SDK bleeding edge.
It looks that it was fixed in https://github.com/dart-lang/sdk/issues/37951.

![image](https://user-images.githubusercontent.com/384794/67057566-e1fb8b00-f105-11e9-9008-8f6262d4880c.png)
![image](https://user-images.githubusercontent.com/384794/67057583-f17ad400-f105-11e9-9995-20c2d0fba8d6.png)

**Comment by shinayser** [comment]
> Works for me with the Dart SDK bleeding edge.
> It looks that it was fixed in #37951.
> 
> ![image](https://user-images.githubusercontent.com/384794/67057566-e1fb8b00-f105-11e9-9008-8f6262d4880c.png)
> ![image](https://user-images.githubusercontent.com/384794/67057583-f17ad400-f105-11e9-9995-20c2d0fba8d6.png)

Is this behavior already on stable? Because on my computer it is really not working =/
