### ISSUE TITLE
Dart 2.6.0-dev analyzer: issues format differs from stable 2.5 release format

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#38957]
The **Dart analyzer** from the **stable channel** (currently, 2.5.2) reports errors in this format:

```nocode
error • A value of type 'String' can't be assigned to a variable of type 'double' at lib/strong_analysis.dart:106:23 • invalid_assignment
```

The format used is "_kind_ • _message_ **at** _path_ • _issue_key_".

In the dev channel release (2.6.0-dev), the "at" in "at _path_" is replaced by by a bullet and the message is terminated with a period. For example:

```nocode
error • A value of type 'String' can't be assigned to a variable of type 'double'. • lib/strong_analysis.dart:106:23 • invalid_assignment
```

This seems like a significant (and **potentially breaking**) change for tools processing error messages (like the site-www CI testing tools), especially since this is only a **minor version increment**. Is this change deliberate?

cc @johnpryan @filiph @DanTup @kwalrath @legalcodes

**Comment by DanTup** [comment]
Looks like this came in with https://github.com/dart-lang/sdk/commit/19533094eb238ef0ec61f4378fea6d6932d9e3bd (FYI @bwilkerson).

There is a `--format machine` option you can pass that would be better if you need to parse the output. I don't know what guarantees are made for the human-readable output, but I would expect changes to the `machine` output to certainly be considered breaking.

Here's how it looks:

```
# Standard output (pre-change - I'm using a stable SDK)
  error • Expected to find ';' at main.dart:16:1 • expected_token

# Machine output
ERROR|SYNTACTIC_ERROR|EXPECTED_TOKEN|/Users/dantup/Dev/Google/flutter/examples/flutter_gallery/lib/main.dart|16|1|1|Expected to find ';'.
```

(I don't know how common it is for tools to scrape the standard output here - the editors use the server API, so wouldn't be affected by this).

**Comment by chalin** [comment]
Hi Dan, thanks for the info! I had forgotten about the machine format. You are probably right that most tools use that format. FYI, I'm using the human-readable format for doc generation on dart.dev (displaying actual analyzer error messages in the site pages.

**Comment by parlough** [comment]
I'm going to close this as we're fine handling this on dart.dev now and I don't think the exact format of the human readable output should be relied on outside of the analyzer's own testing.

For reference, the current format as of Dart 3.2 is `type • location:line:char • Issue. Fix suggestion • diagnostic_name`.

If anyone has any further concerns, please reopen or open a new issue. Thanks all!
