### ISSUE TITLE
Merge to 30719b3 and d2b39d1 to dev

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38952]
We would like 30719b37a9397cc38610e71a804236ec314535ec and d2b39d1a07a18572bdafedb79ce68ef5bf9e64bf cherry-picked to the new in-progress D26 stable branch.

/cc @athomas @dcharkes

**Comment by athomas** [comment]
Do you mean merge to dev? Stable would mean you intend to publish this as
2.5.3?

**Comment by mkustermann** [comment]
Well that depends: Did we branch for a D26 stable release or dev release?

**Comment by athomas** [comment]
That's not quite how Dart releases work.

We _merge_ to dev to start the cherry-pick season (2.6.0-dev.8.0). We cherry-pick to dev until we have something we want to release (2.6.0-dev.8.1). Then we _merge_ to stable and release (2.6.0). Then we cherry-pick to stable and release hotfixes (2.6.1).

Currently, 2.5.2 is at the tip of stable and 2.6.0-dev.8.0 is at the tip of dev.

More details are here:
https://github.com/dart-lang/sdk/wiki/Branches-and-releases

**Comment by mit-mit** [comment]
Pretty sure we mean merge-to-dev here...

**Comment by athomas** [comment]
Merged into 2.6.0-dev.8.1 (61d12745a8a2fedfde8e5644a43baa45ae1a5d9a).
