### ISSUE TITLE
Crash in language_model.dart

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#38951]
I received this crash in IntelliJ while working on the Flutter repo.

Analyzer Feedback from IntelliJ:

## Version information

- `IDEA IC-192.6817.14`
- `2.6.0-edge.ed1e0e199eceb4ce0b0530acdb231f0c3bc989bc`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.ed1e0e199eceb4ce0b0530acdb231f0c3bc989bc, server version 1.27.3, FATAL error: NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LanguageModel._transformInput.<anonymous closure> (package:analysis_server/src/services/completion/dart/language_model.dart:98:67)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      SubListIterable.toList (dart:_internal/iterable.dart:307:29)
#4      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:807:40)
#5      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#6      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:98:9)
#7      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:75:21)
#8      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:35:34)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## Additional Log Info
```
1571330295823 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/images_demo.dart","errors":[]}}
1571330295831 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/typography_demo.dart","errors":[]}}
1571330295871 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/animation/home.dart","errors":[]}}
1571330295881 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/animation/widgets.dart","errors":[]}}
1571330295888 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/animation/sections.dart","errors":[]}}
1571330295909 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/video_demo.dart","errors":[]}}
1571330295916 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/home.dart","errors":[]}}
1571330295924 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/category_menu_page.dart","errors":[]}}
1571330295945 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/shopping_cart.dart","errors":[]}}
1571330295950 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/colors.dart","errors":[]}}
1571330295961 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/login.dart","errors":[]}}
1571330295971 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/supplemental/cut_corners_border.dart","errors":[]}}
1571330295980 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/supplemental/asymmetric_view.dart","errors":[]}}
1571330295988 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/supplemental/product_columns.dart","errors":[]}}
1571330295996 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/supplemental/product_card.dart","errors":[]}}
1571330296005 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/model/app_state_model.dart","errors":[]}}
1571330296024 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/backdrop.dart","errors":[]}}
1571330296037 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/app.dart","errors":[]}}
1571330296077 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine/expanding_bottom_sheet.dart","errors":[]}}
1571330296092 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/fortnightly/fortnightly.dart","errors":[]}}
1571330296097 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/animation_demo.dart","errors":[]}}
1571330296100 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/shrine_demo.dart","errors":[]}}
1571330296105 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/calculator_demo.dart","errors":[]}}
1571330296117 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/colors_demo.dart","errors":[]}}
1571330296128 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/flutter_gallery/lib/demo/cupertino/cupertino_segmented_control_demo.dart","errors":[]}}
1571330296131 => {"id":"361","method":"analysis.updateContent","params":{"files":{"/Users/gspencer/code/flutter/packages/flutter/test/widgets/actions_test.dart":{"type":"add","content":"// Copyright 2
1571330296131 => {"id":"362","method":"completion.getSuggestions","params":{"file":"/Users/gspencer/code/flutter/packages/flutter/test/widgets/actions_test.dart","offset":778},"clientRequestTime":1571
1571330296132 <= {"id":"361","result":{}}
1571330296187 <= {"id":"362","result":{"id":"0"}}
1571330296189 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter/test/widgets/actions_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","l
```

**Comment by gladimdim** [comment]
I have the same issue when running dart 2.5.2 with flutter in IDEA Studio.

**Comment by srawlins** [comment]
CC @lambdabaa

**Comment by gspencergoog** [comment]
I'm still seeing this, here's another stack/log:

```
Dart analysis server, SDK version 2.6.0-edge.ed1e0e199eceb4ce0b0530acdb231f0c3bc989bc, server version 1.27.3, FATAL error: NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LanguageModel._transformInput.<anonymous closure> (package:analysis_server/src/services/completion/dart/language_model.dart:98:67)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      SubListIterable.toList (dart:_internal/iterable.dart:307:29)
#4      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:807:40)
#5      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#6      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:98:9)
#7      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:75:21)
#8      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:35:34)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
<details>
<pre>
1572470316742 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","kind":"LIBRARY","outline":{"element":{"kind"
1572470316742 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","overrides":[{"offset":1652,"length":19,"su
1572470316744 <= {"event":"flutter.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","outline":{"kind":"DART_ELEMENT","offset":0,"l
1572470316852 => {"id":"319","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart":{"type":"add","content":"
1572470316852 => {"id":"320","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4520},"clientRe
1572470316876 => {"id":"321","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4520},"clientRe
1572470316997 => {"id":"322","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart":{"type":"add","content":"
1572470316997 => {"id":"323","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4521},"clientRe
1572470317046 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","errors":[{"severity":"INFO","type":"LINT","lo
1572470317047 <= {"id":"319","result":{}}
1572470317049 <= {"id":"322","result":{}}
1572470317051 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","regions":[{"type":"DIRECTIVE","offset":16
1572470317053 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","regions":[{"offset":173,"length":33,"targ
1572470317053 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","labels":[]}}
1572470317053 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","kind":"LIBRARY","outline":{"element":{"kind"
1572470317054 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","overrides":[{"offset":1652,"length":19,"su
1572470317055 <= {"event":"flutter.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","outline":{"kind":"DART_ELEMENT","offset":0,"l
1572470317082 => {"id":"324","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart":{"type":"add","content":"
1572470317082 => {"id":"325","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4522},"clientRe
1572470317166 => {"id":"326","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart":{"type":"add","content":"
1572470317166 => {"id":"327","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4523},"clientRe
1572470317196 => {"id":"328","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","offset":4523},"clientRe
1572470317350 <= {"id":"320","result":{"id":"0"}}
1572470317351 <= {"id":"321","result":{"id":"1"}}
1572470317351 <= {"id":"323","result":{"id":"2"}}
1572470317352 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","errors":[{"severity":"ERROR","type":"COMPILE_
1572470317360 <= {"event":"completion.existingImports","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","imports":{"elements":{"strings":["
1572470317367 <= {"event":"completion.results","params":{"id":"0","replacementOffset":4520,"replacementLength":0,"results":[],"isLast":true,"libraryFile":"/usr/local/google/home/gspencer/code/flutter/
1572470317367 <= {"event":"completion.existingImports","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/actions.dart","imports":{"elements":{"strings":["
1572470317370 <= {"event":"completion.results","params":{"id":"1","replacementOffset":4520,"replacementLength":0,"results":[],"isLast":true,"libraryFile":"/usr/local/google/home/gspencer/code/flutter/
</pre>
</details>

**Comment by lambdabaa** [comment]
I believe this should have been fixed by https://github.com/flutter/engine/commit/c272b18409ea862b36178dca0b13dee3acbf9c9f for Flutter. @gspencergoog Would you be able to confirm the sha of your local `model.tflite` for me? For me I see:

```
ariaye@ariaye1:~$ cd $FLUTTER
ariaye@ariaye1:~/flutter$ md5sum bin/cache/dart-sdk/bin/model/lexeme/model.tflite 
e3a499a2af9832d7e20106c2d9e3591d  bin/cache/dart-sdk/bin/model/lexeme/model.tflite
```

**Comment by gspencergoog** [comment]
I see:
```
e3a499a2af9832d7e20106c2d9e3591d  bin/cache/dart-sdk/bin/model/lexeme/model.tflite
```
So it looks like the same one.

**Comment by gspencergoog** [comment]
FYI: It's possible that this latest one happened while I was switching back and forth between branches (I do that a lot), and so it could be that it happened when I was on a branch that wasn't synced to master/HEAD. I'll keep an eye out for that.

**Comment by lambdabaa** [comment]
> FYI: It's possible that this latest one happened while I was switching back and forth between branches (I do that a lot), and so it could be that it happened when I was on a branch that wasn't synced to master/HEAD. I'll keep an eye out for that.

SG, thanks!

**Comment by bwilkerson** [comment]
Given that the language model has been disabled, I'm going to assume that this is no longer an issue.
