### ISSUE TITLE
Pull the latest package:yaml into the SDK

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38958]
When I try to pull https://github.com/dart-lang/yaml/pull/57 internally I get test failures in the analyzer. I have not investigated whether these failures are an indication of a real problem or a fragile test. Hopefully it's a fragile test since we'll have more difficulty if the analyzer is relying on a particular non-file defined ordering for yaml keys...

cc @yjbanov @kevmoo

**Comment by natebosch** [comment]
https://dart-review.googlesource.com/c/sdk/+/122029 gets the tests passing, but I don't know if it is safe.

cc @scheglov @bwilkerson @stereotype441

**Comment by yjbanov** [comment]
I saw these test failures in a global presubmit when trying the `package:yaml` change internally (and noted them in an offline email thread). They looked like brittle tests to me.
