### ISSUE TITLE
Compiler Bug Error when running 'flutter -d chrome'

### ISSUE THREAD

**Issue by sumeet-toptal** [dart-lang/sdk#38959]
Error compiling dartdevc module:scrips_core|lib/ui_helpers/text_styles.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\_MiscProgs\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\scrips_core\ui_helpers\text_styles.ddc.js --source-map --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\meta\meta.ddc.dill=packages/meta/meta --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\foundation.ddc.dill=packages/flutter/foundation --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\vector_math\hash.ddc.dill=packages/vector_math/hash --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\physics.ddc.dill=packages/flutter/physics --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\utils.ddc.dill=packages/collection/src/utils --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\collection\collection.ddc.dill=packages/collection/collection --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\gestures.ddc.dill=packages/flutter/gestures --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\painting.ddc.dill=packages/flutter/painting --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\semantics.ddc.dill=packages/flutter/semantics --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\animation.ddc.dill=packages/flutter/animation --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\rendering.ddc.dill=packages/flutter/rendering --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\widgets\actions.ddc.dill=packages/flutter/src/widgets/actions --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\widgets.ddc.dill=packages/flutter/widgets --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\src\cupertino\action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\cupertino.ddc.dill=packages/flutter/cupertino --summary=C:\temp\scratch_space30280552-f15a-11e9-9bd7-aced5ccc25c6\packages\flutter\material.ddc.dill=packages/flutter/material --packages=file:///c:/temp/kernel_builder_425f72c6-f15a-11e9-9bd7-aced5ccc25c6/.packages --module-name=packages/scrips_core/ui_helpers/text_styles --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/_MiscProgs/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=c:\temp\ddk_builder_425f72c5-f15a-11e9-9bd7-aced5ccc25c6\used_inputs.txt package:scrips_core/ui_helpers/text_styles.dart
    dart --version: 2.6.0-dev.8.0.flutter-f020ce5d23 (Wed Oct 16 19:45:23 2019 +0000) on "windows_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:457:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:474:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:161:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:472:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:207:29)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:153:10)
<asynchronous suspension>
#7      _compile (package:dev_compiler/src/kernel/command.dart:277:27)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by vsmenon** [comment]
Merging to https://github.com/dart-lang/sdk/issues/38102
