### ISSUE TITLE
Merge to dev request

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38983]
We'd like to get 8d8faa7dea152cce83681bad4467dac87a30f7de and a9fc9f7fd4bbd9c211fbe2b1329dce82e0c1d0a2 merged to dev so it will be included in D26.

/cc @cskau-g

**Comment by athomas** [comment]
Merged into 2.6.0-dev.8.1 (61d12745a8a2fedfde8e5644a43baa45ae1a5d9a).
