### ISSUE TITLE
Clean up EmbedderSdk and tests in the analyzer

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38989]
See conversation at https://dart-review.googlesource.com/c/sdk/+/122029

> EmbedderSdk is deprecated and not used in analyzer.
The test looks not fully right to me, the reason it fails is probably because when "dart:core" is before, it treats other file paths as relative to the directory containing the file core.dart, which makes sense for bool.dart, int.dart, etc. But in general DartSdk classes and file structure are than every dart:xyz is in its own directory. This is not how the test is done. We should just remove all this.

If the code is unused we should remove it and clean up the tests. I'll submit a tweak to get the tests passing for now.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/122171

**Comment by scheglov** [comment]
The CL has been added to the staging CL for breaking changes.
https://dart-review.googlesource.com/c/sdk/+/122483
