### ISSUE TITLE
To reduce AOT runtime size we should exclude {service,kernel}_isolate.{cc,h} in product mode

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38982]
It appears like our AOT runtime has the code for `{service,kernel}_isolate.{cc,h}` in it.

We should probably remove it via `#if !(defined(PRODUCT) && defined(DART_PRECOMPILED_RUNTIME))`.

**Comment by a-siva** [comment]
The following CLs should account for this
https://dart-review.googlesource.com/c/sdk/+/129742
https://dart-review.googlesource.com/c/sdk/+/129807
https://dart-review.googlesource.com/c/sdk/+/129811
