### ISSUE TITLE
Problem with streams and recursion

### ISSUE THREAD

**Issue by ihsancemil** [dart-lang/sdk#38988]
I'm building flutter app. I'm using bloc pattern as design architecture. Bloc patterns uses Streams to share data between business logic to the ui components.

I want to build a simple sorting algorithm visualizer app*. Sorting algorithms generally uses recursion. For each list change I should notify the ui with yielding the current list. 

I'm using yield for ui update and yield* when I need to recursively call the method. I'm not sure but as far as I saw, after the first yield all yield*'s return their values.

I searched this however I think nobody tried yield* for recursive approach. Can you guys brighten me?

* You can find the all project at https://github.com/ihsancemil/sorting_visualizer and the recursive part is at lib/bloc/soting_bloc_algorithm.dart

**Comment by srawlins** [comment]
Thanks for your interest in Dart, @ihsancemil. Unfortunately, we cannot help with individual Flutter app questions. Can you give an example of using `yield` and `yield*` in a basic asynchronous setting, and explain what you want to happen, and what is actually happening? [DartPad](https://dartpad.dartlang.org/) is a great playground for trying out ideas in vanilla Dart.
