### ISSUE TITLE
"Quickfix" not showing inside collection expressions

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#38995]
When I am pressing the alt + enter ("quickfix" shortcut on Intellij) it shows no options if the widget is inside **conditions** or **for loop** inside collections, like this:

![image](https://user-images.githubusercontent.com/1146982/67031711-7c4cd600-f0e8-11e9-882f-78bd4254b21e.png)

![image](https://user-images.githubusercontent.com/1146982/67031826-ba49fa00-f0e8-11e9-99ee-921326c54454.png)

I am on Windows 10 with flutter 1.9-hotfix5. lso my dart and flutter plugins for Intellij are the latest version.

**Comment by srawlins** [comment]
I think someone else reported a very similar bug, or maybe it was re: completion.

@scheglov may have fixed this last week...

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/38947
