### ISSUE TITLE
FunctionTypedFormalParameterImpl.endToken does not take "?" into account

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38990]
dartfmt has an issue (https://github.com/dart-lang/dart_style/issues/862) where a comma after a nullable function-typed formal parameter gets discarded. To find the comma after each parameter, it uses `param.endToken.next` on each parameter. It looks like that wasn't updated when the optional trailing `?` was added to the AST:

```dart
  @override
  Token get endToken => _parameters.endToken;
```

That should probably be:

```dart
  @override
  Token get endToken => question ?? _parameters.endToken;
```

I should be able to put a little hack into dartfmt to work around this until it's fixed.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/137736
