### ISSUE TITLE
[Breaking Change Request] Remove support for Analyzer based DDC

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38994]
# Intended Change
Remove support for running the Analyzer based DDC from versions of the Dart SDK >= 2.7.0.
* Default all invocations of `dartdevc` to use Kernel based DDC and begin ignoring the `-k` and `--kernel` arguments.
* Delete the versions of dart_sdk.js compiled by Analyzer based DDC that are distributed with the SDK.

```
dart-sdk/lib/dev_compiler/amd/dart_sdk.js
dart-sdk/lib/dev_compiler/common/dart_sdk.js
dart-sdk/lib/dev_compiler/es6/dart_sdk.js
```

# Rationale
The Analyzer based DDC is pure technical debt now. None of our supported build systems rely on this implementation and it is unused. It slows down development of the Analyzer team as they must keep it updated when they make breaking API changes.

# Expected Impact
The exact number of users affected by this change is unknown but we expect it to be low based on the large groups that we know will not be.

## Projects known to break
* Projects with a dependency on build_web_compilers: < 2.0.0

## Projects that will _not_ be affected
* Flutter web projects (never used Analyzer based DDC)
* Web projects created by stagehand: ^3.3.2 (published for Dart v2.4 on Jul 3, 2019)
* Web projects that depend on AngularDart: ^6.0.0-alpha+1
* All Google internal web applications (already migrated to Kernel based DDC)

# Migration Steps
The migration path is simple, update your package to depend on build_web_compilers: ^2.0.0 (the latest as of this writing is v2.7.0). 

> The typical dependency on build_web_compilers does not include any API usage so there should be no breaking changes.

**Comment by mit-mit** [comment]
@Hixie @matanlurey @dgrove - Please review and approve.

**Comment by sigmundch** [comment]
@devoncarew - it came to my attention that this may affect flutter dartpad as well - I believe you were already aware, but let us know if there is any need to wait or if we can move forward.

**Comment by yjbanov** [comment]
Flutter does not use the analyzer based DDC and should not be affected by this chagne.

**Comment by domesticmouse** [comment]
At this point I am swamped with unforking flutter web. I think @RedBrogdon is going to have to take point on looking into getting us off of DDC for normal Dart compilation purposes.

**Comment by domesticmouse** [comment]
@devoncarew there is now =)

**Comment by Hixie** [comment]
LGTM in principle, modulo practical short term concerns.

**Comment by nshahan** [comment]
Closing the loop: Speaking with @RedBrogdon in person we have confirmed the change migrating flutter pad from "DDC" to "DDK" https://github.com/dart-lang/dart-services/pull/467 has been deployed and the tracking issue has been closed https://github.com/dart-lang/dart-pad/issues/1341.

I'll prepare a change that includes the deletion, thanks everyone! 😄

**Comment by mit-mit** [comment]
@nshahan what is the status of this?

**Comment by nshahan** [comment]
We pushed it back until D28 but It's underway. I have landed the first change that removes the ability to run the analyzer based DDC and stops running our test suite. https://dart-review.googlesource.com/c/sdk/+/127067/12

I have some other changes in progress that will actually delete the source files.

**Comment by nshahan** [comment]
Thanks for following up. The code for analyzer based DDC has been deleted.
https://github.com/dart-lang/sdk/commit/c561a9eacc1b3d0a93980ef5119f77bf88511a15
