### ISSUE TITLE
Building application for the web using redux

### ISSUE THREAD

**Issue by vaaniiaa** [dart-lang/sdk#39000]
Error compiling dartdevc module:samplewebapplication|lib/main_web_entrypoint.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\main_web_entrypoint.ddc.js --source-map --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\meta\meta.ddc.dill=packages/meta/meta --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\foundation.ddc.dill=packages/flutter/foundation --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\vector_math\hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\physics.ddc.dill=packages/flutter/physics --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\collection\collection.ddc.dill=packages/collection/collection --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\gestures.ddc.dill=packages/flutter/gestures --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\painting.ddc.dill=packages/flutter/painting --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\semantics.ddc.dill=packages/flutter/semantics --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\animation.ddc.dill=packages/flutter/animation --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\rendering.ddc.dill=packages/flutter/rendering --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\widgets\actions.ddc.dill=packages/flutter/src/widgets/actions --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\widgets.ddc.dill=packages/flutter/widgets --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\src\cupertino\action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\cupertino.ddc.dill=packages/flutter/cupertino --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter\material.ddc.dill=packages/flutter/material --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\navigation\navigation.ddc.dill=packages/samplewebapplication/model/navigation/navigation --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\login\login_response.ddc.dill=packages/samplewebapplication/model/login/login_response --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\services\login\login_service.ddc.dill=packages/samplewebapplication/services/login/login_service --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\redux\redux.ddc.dill=packages/redux/redux --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\redux_thunk\redux_thunk.ddc.dill=packages/redux_thunk/redux_thunk --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\redux\actions\login\login_actions.ddc.dill=packages/samplewebapplication/model/redux/actions/login/login_actions --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\redux\state\user\user_state.ddc.dill=packages/samplewebapplication/model/redux/state/user/user_state --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\redux\reducers\user\user_reducer.ddc.dill=packages/samplewebapplication/model/redux/reducers/user/user_reducer --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\redux\state\app_state.ddc.dill=packages/samplewebapplication/model/redux/state/app_state --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\redux\reducers\app_reducer.ddc.dill=packages/samplewebapplication/model/redux/reducers/app_reducer --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\screens\home\home_screen.ddc.dill=packages/samplewebapplication/screens/home/home_screen --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\flutter_redux\flutter_redux.ddc.dill=packages/flutter_redux/flutter_redux --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\views\error\error_dialog.ddc.dill=packages/samplewebapplication/views/error/error_dialog --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\views\login\input_field.ddc.dill=packages/samplewebapplication/views/login/input_field --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\views\login\login_input_form.ddc.dill=packages/samplewebapplication/views/login/login_input_form --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\model\login\login_viewmodel.ddc.dill=packages/samplewebapplication/model/login/login_viewmodel --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\screens\login\login_screen.ddc.dill=packages/samplewebapplication/screens/login/login_screen --summary=C:\Users\keshavarz\AppData\Local\Temp\scratch_space4612ead3-f312-11e9-b6d7-708bcd53d11f\packages\samplewebapplication\main.ddc.dill=packages/samplewebapplication/main --packages=file:///C:/Users/KESHAV~1/AppData/Local/Temp/kernel_builder_4c13af8c-f312-11e9-b6d7-708bcd53d11f/.packages --module-name=packages/samplewebapplication/main_web_entrypoint --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=C:\Users\KESHAV~1\AppData\Local\Temp\ddk_builder_4c13af88-f312-11e9-b6d7-708bcd53d11f\used_inputs.txt package:samplewebapplication/main_web_entrypoint.dart
    dart --version: 2.6.0-dev.7.0.flutter-70a7ef3f58 (Mon Oct 14 18:25:56 2019 +0000) on "windows_x64"

Crash when compiling null,
at character offset null:
Reference to root::package:samplewebapplication/screens/home//home_screen.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:249:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:611:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:815:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:836:29)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:274:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:359:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:151:20)
<asynchronous suspension>
#17     _compile (package:dev_compiler/src/kernel/command.dart:314:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

#0      Reference.asLibrary (package:kernel/ast.dart:249:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:611:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:815:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:836:29)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:274:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:359:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:151:20)
<asynchronous suspension>
#17     _compile (package:dev_compiler/src/kernel/command.dart:314:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

AssetNotFoundException: samplewebapplication|lib/main_web_entrypoint.ddc.js
Failed after 19.4s
Finished with error: Failed to build application for the Web.

**Comment by vsmenon** [comment]
@jakemac53 - can you take a quick look at the trace here?  Should this be merged into 

https://github.com/dart-lang/sdk/issues/38102

?

**Comment by jakemac53** [comment]
This looks like a different issue

**Comment by jakemac53** [comment]
Although its likely the same fix would work to resolve it?

**Comment by vsmenon** [comment]
Okay, I will merge then into #38102
