### ISSUE TITLE
RtcPeerConnection.createOffer throws on production build

### ISSUE THREAD

**Issue by wytrych** [dart-lang/sdk#39017]
Related to #38787 

The following code does not work on Chrome when running `webdev serve --release`, although it does during dev build: `webdev serve`.

Error thrown:
`Uncaught (in promise) TypeError: Instance of 'UnknownJavaScriptObject': type 'UnknownJavaScriptObject' is not a subtype of type 'FutureOr<RtcSessionDescription>'
`

```dart
import 'dart:html';

void main() async {
  final pc = RtcPeerConnection(const {
    'iceServers': [
      {'urls':'stun:stun2.l.google.com:19302'},
      {'urls':'stun:stun4.l.google.com:19302'},
    ]
  });
  final offer = await pc.createOffer();
  print('Here');
}
```

Edit: So this problem disappears when running `dart2js --omit-implicit-checks`

**Comment by vsmenon** [comment]
Merging to https://github.com/dart-lang/sdk/issues/38787
