### ISSUE TITLE
ast_from_binary incorrect ContinueSwitchStatement for nested function switch/case statement

### ISSUE THREAD

**Issue by marius-klimantavicius** [dart-lang/sdk#39040]
Related:
Common Front End (CFE) and kernel

* Dart SDK Version (`dart --version`)
Dart VM version: 2.5.2 (Tue Oct 8 16:17:11 2019 +0200) on "windows_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Not applicable

Ast from binary (https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/binary/ast_from_binary.dart) seems to incorrectly handle `continue` in switch cases (`ContinueSwitchStatement`) when switch is within function expression.

According to binary.md `A SwitchCase is in scope everywhere within its enclosing switch, except the scope is delimited by FunctionNodes.` however the builder reuses `switchCaseStack`. Possible fix - save `switchCaseStack` when reading function node restore before returning (maybe like label stack that uses `labelStackBase`).

Steps to reproduce:

```
void main() {
 var a = 0;
 var c = 0;
 var b;
 switch (a) {
   case 3:
     print ('c3');
	 continue next1;
   next1: case 1:
     b = () {
       switch (c) {
         case 0:
           print ('something ');
           continue next; // <-- error here
        next: case 1:
           print ('else');
           break;
       }
     };
   break;
 }
}
```

Compile to snapshot and dump (I was using `pub run kernel:dump issue.dill`) the generated .dill.

Expected result:
`continue` in nested function `switch` points to correct label (`continue #L6;` in this case)

Actual result:
`continue` in nested function `switch` points to (semi)random case (`continue #L3;` in this case).

**Comment by jensjoha** [comment]
Thank you for the report! I'll take a look.
