### ISSUE TITLE
pub.dev support for flutter and platform categorization

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#39047]
Client-side changes (needed before SDK branch off): https://github.com/dart-lang/pub/pull/2233

  * pub client rejects packages using both new and old platform scheme
  * pub client warns on packages using old platform scheme

Server-side changes (can happen after SDK branch off):
  * Overall change to the Flutter/Web/All categorization
  * Support for searching/browsing based on platform tags

**Comment by devoncarew** [comment]
@mit-mit, @jonasfj - what's the best `area-` label for pub work?

**Comment by srawlins** [comment]
Should this be filed under dart-lang/pub or dart-lang/pub.dev?

**Comment by mit-mit** [comment]
We wish to track these as meta-issues here so-as to have a full list of what has to get done for each release in the present repo.

**Comment by mit-mit** [comment]
@jonasfj are there any other changes we need on the client side for D27?

**Comment by jonasfj** [comment]
There are no other client side thing for D27, and both:
> * pub client rejects packages using both new and old platform scheme
> * pub client warns on packages using old platform scheme

have landed.

**Comment by mit-mit** [comment]
Great, closing
