### ISSUE TITLE
Parser fuzz crash: @dart= version must be non-negative

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39059]
```dart
//@dart=2.46803157260780285387
```

```
Unhandled exception:
Invalid argument(s): Minor version must be non-negative.
#0      new Version._ (package:pub_semver/src/version.dart:98:7)
#1      new Version (package:pub_semver/src/version.dart:109:16)
#2      Scanner._languageVersionChanged (package:analyzer/src/dart/scanner/scanner.dart:192:11)
#3      AbstractScanner.tokenizeLanguageVersionOrSingleLineComment (package:front_end/src/fasta/scanner/abstract_scanner.dart:1312:7)
#4      AbstractScanner.bigHeaderSwitch (package:front_end/src/fasta/scanner/abstract_scanner.dart:651:12)
#5      AbstractScanner.tokenize (package:front_end/src/fasta/scanner/abstract_scanner.dart:616:16)
#6      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:100:26)
#7      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#8      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#9      _File._parse (package:analyzer/src/services/available_declarations.dart:1859:25)
#10     _File.refresh (package:analyzer/src/services/available_declarations.dart:1184:30)

**Comment by jensjoha** [comment]
As I see it, this is an analyzer issue.

From https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md

> Program Library Level Configuration
> [...]
> If an entry contains an invalid dart version value, #dart=arglebargle or #dart= or any other value which is not a semantic versioning version, or multiple dart= entries, then tools which need the version should report an error.
> 
> [...]
> 
> Individual Library Language Version Override
> [...]
> The syntax for choosing a different language level than the default is line consisting only of a single-line comment of the form // @dart = 2.0 (exactly two slashes, the string @dart, a =, and a numeral which is two decimal numerals separated by .) in the initial part of the file, prior to any language declarations.

As I read it `2.46803157260780285387` would either be fine (`decimal numerals separated by . `) or should issue an error (`any other value which is not a semantic versioning version`).

It is clearly the analyzer calling the 'pub_samver' package that crashes:
```
Unhandled exception:
Invalid argument(s): Minor version must be non-negative.
#0      new Version._ (package:pub_semver/src/version.dart:98:7)
#1      new Version (package:pub_semver/src/version.dart:109:16)
#2      Scanner._languageVersionChanged (package:analyzer/src/dart/scanner/scanner.dart:192:11)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131705 will check this in analyzer, but I think the original issue is in CFE scanner, which silently overflows major / minor version.
