### ISSUE TITLE
Analyzer has no answer for `isAbstract` on constructor

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39051]
Reflectable encounters a dynamic error during code generation whenever it makes an attempt to evaluate `isAbstract` on a constructor.

It seems likely that this dynamic error could be avoided by adding two lines around line 750 of 'pkg/analyzer/lib/src/summary2/linked_unit_context.dart', like so:

```dart
  bool isAbstract(AstNode node) {
    if (node is ClassDeclaration) {
      return node.abstractKeyword != null;
    } else if (node is ClassTypeAlias) {
      return node.abstractKeyword != null;
    } else if (node is FunctionDeclaration) {
      return false;
    } else if (node is MethodDeclaration) {
      return LazyMethodDeclaration.isAbstract(node);
    } else if (node is ConstructorDeclaration) { /* Add this line and the next one */
      return false;
    }
    throw UnimplementedError('${node.runtimeType}');
  }
```

Alternatively, 'pkg/analyzer/src/dart/element/element.dart' could perform a check in line 4564, in order to avoid calling `linkedContext.isAbstract(_)` when `linkedNode` is a constructor:

```dart
  bool get isAbstract {
    if (linkedNode != null) {
      return !isExternal && enclosingUnit.linkedContext.isAbstract(linkedNode);
    }
    return hasModifier(Modifier.ABSTRACT);
  }
```

This issue did not exist with analyzer 0.37.* (at least some of those versions), but seems to exist with 0.38.3 and up (and I did not try 0.38.lower-than-3).

**Comment by srawlins** [comment]
CC @scheglov for summary2

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124084
