### ISSUE TITLE
Cherry-pick request for IA32 write protection bug

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39069]
Please cherry-pick https://dart-review.googlesource.com/c/sdk/+/122643 into Dart 2.6 since it fixes a bug with broad impact causing random crashes all 32-bit Intel configurations.

See https://github.com/dart-lang/sdk/issues/38528 for details on the bug.

/cc @mkustermann @athomas @whesse @mraleph

**Comment by athomas** [comment]
Assuming the ask here is to pick b359ac0a1e5b2fa16ec71d6e5788f53b82903057.

**Comment by athomas** [comment]
This was cherry-picked into 2.6.0-dev.8.2 (1a844e4).

**Comment by sjindel-google** [comment]
@athomas Yes, that's the commit I intended. Thanks!
