### ISSUE TITLE
Crash running the analyzer with ML completions enabled.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#39079]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.6.0-edge.cccb9ffb2ab3268389a08d20261861115864156c`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.cccb9ffb2ab3268389a08d20261861115864156c, server version 1.27.3, FATAL error: NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LanguageModel._transformInput.<anonymous closure> (package:analysis_server/src/services/completion/dart/language_model.dart:99:67)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      SubListIterable.toList (dart:_internal/iterable.dart:307:29)
#4      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:807:40)
#5      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#6      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:99:9)
#7      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:76:21)
#8      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/pl/5yqcvds916b39jxc_pb66y700025bq/T/report.txt.

**Comment by bwilkerson** [comment]
@lambdabaa Could you take a look at this?

**Comment by gspencergoog** [comment]
I had a similar crash.

## Version information

- `IDEA IC-192.6817.14`
- `2.6.0-edge.d43cd7e9096875bf0fb2d1f34b8f9857616a2f9a`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Linux(amd64) v4.19.37-5+deb10u2rodete2-amd64, screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d43cd7e9096875bf0fb2d1f34b8f9857616a2f9a, server version 1.27.3, FATAL error: NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LanguageModel._transformInput.<anonymous closure> (package:analysis_server/src/services/completion/dart/language_model.dart:99:67)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      SubListIterable.toList (dart:_internal/iterable.dart:307:29)
#4      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:807:40)
#5      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#6      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:99:9)
#7      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:76:21)
#8      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## Crash Report
<details>
<pre>
1571936305482 <= {"id":"163","result":{}}
1571936305505 => {"id":"164","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21049,"length":0},"client
1571936305627 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","errors":[]}}
1571936305628 <= {"id":"164","result":{"assists":[]}}
1571936305635 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","regions":[{"type":"DIRECTIVE","offset":16
1571936305640 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","regions":[{"offset":173,"length":33,"targ
1571936305640 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","labels":[{"offset":505,"length":300,"l
1571936305640 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","kind":"LIBRARY","outline":{"element":{"kind"
1571936305640 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","overrides":[]}}
1571936305645 <= {"event":"flutter.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","outline":{"kind":"DART_ELEMENT","offset":0,"l
1571936305648 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1280,"uri":"file:///usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test
1571936305667 <= {"event":"analysis.implemented","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","classes":[],"members":[]}}
1571936306012 => {"id":"165","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21049,"length":0},"client
1571936306016 <= {"id":"165","result":{"assists":[]}}
1571936306795 => {"id":"166","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21084,"length":14},"clien
1571936306799 <= {"id":"166","result":{"assists":[]}}
1571936307926 => {"id":"167","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21084,"length":20},"clien
1571936307929 <= {"id":"167","result":{"assists":[]}}
1571936308331 => {"id":"168","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21084,"length":18},"clien
1571936308335 <= {"id":"168","result":{"assists":[]}}
1571936308900 => {"id":"169","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart":{"type":"add","content":"
1571936308900 => {"id":"170","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","offset":21086},"clientR
1571936308903 <= {"id":"169","result":{}}
1571936309058 <= {"id":"170","result":{"id":"3"}}
1571936309059 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","errors":[{"severity":"ERROR","type":"STATIC_W
1571936309072 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","regions":[{"type":"DIRECTIVE","offset":16
1571936309088 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","regions":[{"offset":173,"length":33,"targ
1571936309090 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","labels":[{"offset":505,"length":300,"l
1571936309093 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","kind":"LIBRARY","outline":{"element":{"kind"
1571936309093 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/page_test.dart","overrides":[]}}
</pre>
</details>

**Comment by lambdabaa** [comment]
@jacob314 @gspencergoog Did you see this behavior on the latest flutter master channel? Or somewhere else?

**Comment by gspencergoog** [comment]
Yes, latest Flutter master:
```
Flutter 1.10.15-pre.253 • channel density • git@github.com:gspencergoog/flutter.git
Framework • revision 3cc69eacaf (3 minutes ago) • 2019-10-25 08:55:02 -0700
Engine • revision 8d6b74aee6
Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 1bd6e20d76)
```

**Comment by lambdabaa** [comment]
Thanks! This will be fixed once https://github.com/flutter/engine/commit/c272b18409ea862b36178dca0b13dee3acbf9c9f is picked up in the next roll.
