### ISSUE TITLE
Conditionally search for TODOs to report

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#39075]
See library_analyzer.dart:

https://github.com/dart-lang/sdk/blob/65813f5856254eae9861605edbf51d053a77dcda/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart#L261-L264

We conditionally run dart2js analysis. All other analysis is performed _unconditionally_, regardless of what codes are ignored in `analysis_options.yaml`. I think we should also conditionally run TODO analysis, since ToDoFinder walks every single token in a library and runs a regular expression over all lines of all comments. Seems expensive.

It shouldn't be hard to make a boolean, like `analysis_options.todo`, since there is exactly one code in the `Todo` category.

Internally, we have separete `analysis_options.yaml` files for building and for IDEs, so folk can still see TODO analysis in their IDE, but builds wouldn't look for TODO comments.

**Comment by srawlins** [comment]
Maybe the same with the ImportsVerifier, which produces Hints like UNUSED_IMPORT, DUPLICATE_IMPORT, ...

And UnusedLocalElementsVerifier, which produces Hints like UNUSED_ELEMENT.

**Comment by bwilkerson** [comment]
@scheglov who is better able to answer the performance question than I am.

**Comment by srawlins** [comment]
I'm going to close this. I did a bunch of A/B performance tests and could not budge the needle. Whether we search for TODOs or don't, analysis always takes the same amount of time. ☹️
