### ISSUE TITLE
Please merge 2be376385cf06b and 1a747c6546a171 to dev for D26 inclusion

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39072]
We would like 2be376385cf0 and 1a747c6546a1 be cherry-picked to dev, so it will be included in D26.

([cl/122646](https://dart-review.googlesource.com/c/sdk/+/122646) and [cl/122640](https://dart-review.googlesource.com/c/sdk/+/122640))

**Comment by athomas** [comment]
This was cherry-picked into 2.6.0-dev.8.2 (1a844e4).
