### ISSUE TITLE
Auto complete not working for extensions without 'this' keyword

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#39093]
Imagine i have a simple class like that:

![image](https://user-images.githubusercontent.com/1146982/67498289-92f9ac80-f655-11e9-987c-8df3c66b645f.png)

And an extension:

![image](https://user-images.githubusercontent.com/1146982/67498327-a0169b80-f655-11e9-81eb-4d804e57d88e.png)

Now, I want to call the extesion method "work" inside my "doSomethingMethod". If I press ctrl + space, it shows no options for that method:

![image](https://user-images.githubusercontent.com/1146982/67498395-be7c9700-f655-11e9-95ae-56e7119cdd90.png)

But if I add the **this** keyword, it shows up:

![image](https://user-images.githubusercontent.com/1146982/67498475-e5d36400-f655-11e9-8320-9df584c59594.png)

This problem also happens inside the extension body. It shows no methods from the base class when hitting ctrl + space:

![image](https://user-images.githubusercontent.com/1146982/67498557-03a0c900-f656-11e9-9023-3fc5ac64e860.png)

But works if I add the **this**:
![image](https://user-images.githubusercontent.com/1146982/67498599-174c2f80-f656-11e9-91de-cd49b5bb6999.png)

Obs: everything works like a charm for **mixins**. Only extensions has this problem.

**Comment by devoncarew** [comment]
cc @pq @bwilkerson

**Comment by VyMajoris** [comment]
Maybe related to this:

The auto complete also does not work unless you have already imported the extension on the file you are working:

Extension:
![ext1](https://user-images.githubusercontent.com/4342296/67887088-6815c980-fb29-11e9-9550-24fd3031ae4c.PNG)

Trying to get the Android Studio to show the `format` function without importing the extension manually:
![ext2](https://user-images.githubusercontent.com/4342296/67887284-c04ccb80-fb29-11e9-8801-d651d20c1acf.png)

Android Studio showing the method, after importing it manually:
![image](https://user-images.githubusercontent.com/4342296/67887439-03a73a00-fb2a-11e9-9ae4-b4a86e0e0421.png)

**Comment by kuhnroyal** [comment]
I can confirm these observations. I always have to manually import the extension before it can be used. Without the autocomplete, extension methods are hard to use.

**Comment by shinayser** [comment]
Just want to point out that in my current dart DEV version (`Dart VM version: 2.8.0-dev.8.0 (Thu Feb 6 15:47:55 2020 +0100) on "windows_x64"`) it still not working

**Comment by pq** [comment]
Hey, thanks!  I'm guessing your repro looks something like:

```
lib/
  person.dart => defines Person
  ext.dart => defines Ext and imports Person
```

?

(I can confirm that's still broken 😬)

**Comment by shinayser** [comment]
Actually them both are on the same file. And my extension doesn't have name at all.
This is my pessoa.dart:

```dart


class User implements Comparable<User> {
  String username;
  String password;
  int age;

  User(this.username, {this.age, this.password});

  void doSomething() {
    print('Doing something...');
  }

  @override
  String toString() => '$username [$password]';

  @override
  int compareTo(User other) => username.compareTo(other.username);
}

extension on User {
  void work() {}
}
```

**Comment by pq** [comment]
Ok, fantastic.  Thank you for the great repro!

**Comment by pq** [comment]
Progress:

![image](https://user-images.githubusercontent.com/67586/73982662-87bb4b80-48e9-11ea-9994-e75190ddaf2d.png)

https://dart-review.googlesource.com/c/sdk/+/134784

🚧
