### ISSUE TITLE
Allow `--enable-experiment=non-nullable` on command line to enable NNBD for analysis server

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39103]
Currently we enable NNBD for the analysis server using an option in the analysis_options.yaml file.  But for NNBD-enabled Dartpad, we want NNBD to be enabled without the user having to modify their files in any special way.  I think the best way to do this is probably for the analysis server to accept `--enabled-experiment=non-nullable` on the command line.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/123200
