### ISSUE TITLE
Analyzer considers "!" a mutating operator for prefer_final_fields

### ISSUE THREAD

**Issue by noinskit** [dart-lang/sdk#39114]
The prefer_final_fields analyzer rule treats negating a private bool ("!_foo") as a mutating operation which prevents the "Private field could be final." warning.

For example, this code:
`if (!_initialized) {
  widget.initialize(context);
}
`
does not trigger that warning, but this equivalent code:
`if (_initialized != true) {
  widget.initialize(context);
}
`
correctly triggers the warning.

I'm using flutter:
Flutter 1.9.1+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aedbb1835 (8 days ago) • 2019-10-17 08:37:27 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by cubuspl42** [comment]
+1, it's really irritating and can make a dangerous bug slip in

**Comment by bwilkerson** [comment]
@pq

**Comment by noinskit** [comment]
That was fast - thanks!
