### ISSUE TITLE
Spurious collection literal error with null-aware spread

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39117]
Consider the following program:

```dart
main() {
  Map? arguments;
  var map = <Object?, Object?>{...?arguments};
}
```

With `dartanalyzer --enable-experiment=non-nullable` from 0167f91012648a3c25a082a8ededf62934513764 we get the following error:

```
ERROR|COMPILE_TIME_ERROR|NOT_MAP_SPREAD|/usr/local/google/home/eernst/lang/dart/scratch/201910/n031.dart|3|36|9|Spread elements in map literals must implement 'Map'.
```

However, the requirement must be that `arguments` implements `Map<S, T>?` for some `S`, `T`, because `...?` is intended to allow for a spread whose type is nullable.

This has not yet been specified, but it is mentioned in dart-lang/language#602, line 7696, so it will be specified when that lands.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124207
