### ISSUE TITLE
Spurious collection literal ambiguity

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39115]
Consider the following program:

```dart
main() {
  Map? arguments;
  var _parent = null;
  var map = {
      ...?arguments,
      if (_parent != null) 'parentId': '16',
  };
}
```

The collection literal that is used to initialize `map` contains an `<ifElement>` whose contained `<element>` is of the form `e1 : e2`. This makes it 'unambiguously a map'. However, we still get the following error from `dartanalyzer --enable-experiment=non-nullable` as of 0167f91012648a3c25a082a8ededf62934513764:

```
ERROR|COMPILE_TIME_ERROR|AMBIGUOUS_SET_OR_MAP_LITERAL_EITHER|/usr/local/google/home/eernst/lang/dart/scratch/201910/n030.dart|4|13|71|This literal must be either a map or a set, but the elements don't have enough information for type inference to work.
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124207
