### ISSUE TITLE
KBC interpreter doesn't respect --unbox_numeric_fields

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39113]
The KBC interpreter doesn't respect this flag, which is true by default except in AOT, where it's false by default. For example https://github.com/dart-lang/sdk/blob/36cd2e22d407b5b71a0dbc4ddde01d2487fb034d/runtime/vm/interpreter.cc#L3193-L3195

This will break if the VM is run with this flag set to false, or if we try to run the interpreter in AOT.

/cc @alexmarkov @mkustermann @mraleph

**Comment by alexmarkov** [comment]
Maybe we should just change `Field::InitializeNew` to call `result.set_is_unboxing_candidate(false)` depending on the `unbox_numeric_fields` flag to disable unboxing early and for all, and remove uses of this flag from `il.cc`.

/cc @rmacnak-google who added support for unboxed fields in interpreter.
/cc @aartbik who last looked at unifying unboxing decisions between compiler and interpreter.

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
