### ISSUE TITLE
Failed to handle completion domain request: getter 'isSynthetic' was called on null

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#39125]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2048x1152, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 158, method: completion.getSuggestions, params: {file: _____, offset: 6334}, clientRequestTime: 1572036669951}
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      isTokenDot (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:139:17)
#2      testFollowingDot (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:144:31)
#3      CompletionRanking.rerank (package:analysis_server/src/services/completion/dart/completion_ranking.dart:131:33)
<asynchronous suspension>
#4      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:185:35)
<asynchronous suspension>
#5      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#6      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#7      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)
#12     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:as...
```

For additional log information, please append the contents of
file:///private/var/folders/np/gmysjh1j2159hv7wssjzrw440028jd/T/report1.txt.

Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 158, method: completion.getSuggestions, params: {file: /Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart, offset: 6334}, clientRequestTime: 1572036669951}
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      isTokenDot (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:139:17)
#2      testFollowingDot (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:144:31)
#3      CompletionRanking.rerank (package:analysis_server/src/services/completion/dart/completion_ranking.dart:131:33)
<asynchronous suspension>
#4      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:185:35)
<asynchronous suspension>
#5      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#6      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#7      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)
#12     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#56     _StreamController._add (dart:async/stream_controller.dart:640:7)
#57     _StreamController.add (dart:async/stream_controller.dart:586:5)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#59     _rootRunUnary (dart:async/zone.dart:1136:13)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
1572036670470 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/filiph/
1572036670473 <= {"id":"163","result":{}}
1572036670479 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN"
1572036670512 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":1
1572036670518 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<un
1572036670520 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","overrides":[{"offset":3101,"length":14,"superclassMember":{"element":{"ki
1572036670522 <= {"event":"flutter.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":9071,"codeOffset":0,"cod
1572036670591 <= {"id":"164","result":{"id":"11"}}
1572036670592 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/filiph/
1572036670595 => {"id":"165","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart":{"type":"add","content":"import 'dart:async';\nimport 'd
1572036670595 => {"id":"166","method":"completion.getSuggestions","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","offset":6339},"clientRequestTime":1572036670595}
1572036670596 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN"
1572036670599 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":1
1572036670601 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<un
1572036670606 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","overrides":[{"offset":3101,"length":14,"superclassMember":{"element":{"ki
1572036670616 <= {"event":"flutter.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":9072,"codeOffset":0,"cod
1572036670619 <= {"id":"165","result":{}}
1572036670679 <= {"id":"166","result":{"id":"12"}}
1572036670679 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/filiph/
1572036670682 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN"
1572036670697 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":1
1572036670698 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<un
1572036670701 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","overrides":[{"offset":3101,"length":14,"superclassMember":{"element":{"ki
1572036670703 <= {"event":"flutter.outline","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":9074,"codeOffset":0,"cod
1572036670707 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":706,"uri":"package:flutter_egamebook/flutter_runner.dart","items":[{"label":"EdgeheadFlutterRunner","dec
1572036670709 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":706,"uri":"package:flutter_egamebook/flutter_runner.dart","items":[{"label":"EdgeheadFlutterRunner","dec
1572036670709 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":706,"uri":"package:flutter_egamebook/flutter_runner.dart","items":[{"label":"EdgeheadFlutterRunner","dec
1572036670709 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":706,"uri":"package:flutter_egamebook/flutter_runner.dart","items":[{"label":"EdgeheadFlutterRunner","dec
1572036670710 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter_egamebook/lib/flutter_runner.dart","classes":[],"members":[]}}
1572036670772 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 158, method: completion.getSuggestions, params: {file: /Users/filiph/dev/
```

**Comment by devoncarew** [comment]
I believe this was addressed in 118831ec535f0c214ac025914d53961a0732d2a2.
