### ISSUE TITLE
Auto complete don't work after "yield" keyword

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#39124]
Check this simple code:

![image](https://user-images.githubusercontent.com/1146982/67601024-bdc52d00-f749-11e9-810e-6a7bba525039.png)

If you try to autocomplete anything that comes after the "yield" keyword, it shows no suggestions.

**Comment by pq** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8163dbea4f5d40efaa4c0f45050e3f2e4f665e67.
