### ISSUE TITLE
Spelling check presubmits should be removed

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39121]
I hit this pre-upload check today, and had the joy of wasting probably an hour of combined developer time with a combination of "wtf?" and figuring out how the heck to update the hardcoded list of allowed words.

A spelling check that doesn't even allow words like "retry" or "seeing" without explicitly adding them to a (hard to find) list is really not acceptable imo and this should be removed.

```
** Presubmit ERRORS **
Front-end smoke test failure(s):

***************
-----
Running: /usr/local/google/home/jakemac/dart-lang-sdk/sdk/tools/sdks/dart-sdk/bin/dart pkg/front_end/test/spelling_test_src_suite.dart: Failed with exit code 1 in 2324 ms.
--- stdout start ---
UNEXPECTED: spelling_test_src_test/front_end/lib/src/api_unstable/modular_incremental_compilation
The test had the outcome Fail, but the status file (/usr/local/google/home/jakemac/dart-lang-sdk/sdk/pkg/front_end/test/spelling_test.status) allows these outcomes: Pass
file:///usr/local/google/home/jakemac/dart-lang-sdk/sdk/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart:57:10: Misspelled word 'retry'.
  bool isRetry = false;
         ^^^^^

file:///usr/local/google/home/jakemac/dart-lang-sdk/sdk/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart:249:13: Misspelled word 'retry'.
      if (isRetry) rethrow;
            ^^^^^

file:///usr/local/google/home/jakemac/dart-lang-sdk/sdk/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart:254:22: Misspelled word 'seeing'.
you are consistently seeing this problem please see that issue.
                     ^^^^^^

file:///usr/local/google/home/jakemac/dart-lang-sdk/sdk/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart:260:9: Misspelled word 'retry'.
      isRetry = true;
        ^^^^^
```

**Comment by johnniwinther** [comment]
Sorry about that.

The spell check should have clearly stated where to put the unrecognized word - and not have blamed you for misspelling when that's clearly not the case.

The spell checking was meant as a CFE-internal requirement only since it _is_ a harsh requirement to put on the code. For that reason we should have excluded the `api_unstable` folder which _is_ a much more collaborative area and cannot be considered CFE-internal.

**Comment by jakemac53** [comment]
It seems like it should at least be initialized from a dictionary at least? These are extremely common/basic English words.

I think it would be very difficult to justify the cost/benefit of this check in any regard, but at least use an established spell checker or common list of words or something....?

I won't push further on it though.

**Comment by natebosch** [comment]
This does seem like the kind of problem that is better solved in your editor than in a presubmit. I'm not familiar with any other project at google that has a hardcoded hand edited spell check list for a codebase.

**Comment by sigmundch** [comment]
I accidentally stumbled upon this bug - a couple drive-by comments:
 * **smaller scope**: Are there parts of the CFE that get more value for the spell checker? For example, maybe it is most useful for user-visible error messages and public APIs and it could be scoped down to messages.yaml and files in package:kernel?
 * **automation**: In the past I also had friction with the whiltelist (e.g. understanding what is a word token for the whitelist took me some time). Maybe adding the ability to autoupdate the whitelist can make it easier for people to quickly see the failure, run a script, upload the CL and move on?

**Comment by jakemac53** [comment]
I am going to close this issue because I don't think its going anywhere.

I do appreciate that the error message is MUCH more informative and actionable now as well.
