### ISSUE TITLE
Spurious error for collection literal

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39120]
Consider the following program:

```dart
main() {
  Map arguments;
  var map = {...arguments};
}
```

With a `dartanalyzer --enable-experiment=non-nullable` from 0167f91012648a3c25a082a8ededf62934513764, this program produces the following error message:

```
ERROR|COMPILE_TIME_ERROR|AMBIGUOUS_SET_OR_MAP_LITERAL_EITHER|/usr/local/google/home/eernst/lang/dart/scratch/201910/n033.dart|3|13|14|This literal must be either a map or a set, but the elements don't have enough information for type inference to work.
```

The error is _not_ reported without `--enable-experiment=non-nullable`, so there is something related to nullability, even though all types in this program are non-nullable. It could be about `Object?` vs. `Object`, as mentioned below.

The error should not be reported, because: (1) `{...arguments}` has a spread element `...arguments` whose static type is `Map` (which means that it is a non-`Null` subtype of `Map<Object?, Object?>`, which is the nnbd replacement for the requirement `Map<Object, Object>` which is used in pre-nnbd code), so (2) that spread element yields a key and a value type for the map literal, but no set element type, so (3) the map literal 'must be a map'.

Here's a strong hint that it's concerned with `Object?`; we get no errors for this one:

```dart
main() {
  Map<Object, Object> arguments = {};
  var map = {...arguments};
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124207
