### ISSUE TITLE
Dart-io - http server fragment identifier parameter 

### ISSUE THREAD

**Issue by shellbear** [dart-lang/sdk#39138]
Informations:
* Dart core libraries (dart:io)
* Dart SDK Version (`dart --version`)
Dart VM version: 2.5.2 (Tue Oct 8 16:17:11 2019 +0200) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux

Hello, I'm trying to create a server to handle an OAuth2 response but, I don't understand how to get a fragment identifier parameter with the default dart io http server.

The url is of the following form:
`http://127.0.0.1:9000/?state=this_is_a_test#access_token=...&expires_in=...&token_type=...&refresh_token=...&account_username=...&account_id=...`

As you can see, all the parameters are passed after the fragment identifier and I can't get them.

The following code with the previous url as request:
```dart
final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 9000);

await for (HttpRequest request in server) {
    print('${request.uri}, ${request.requestedUri}');
    print(request.uri.queryParameters);
    ....
}
```

gives me:
```
/?state=this_is_a_test, http://127.0.0.1:9000/?state=this_is_a_test
{state: this_is_a_test}
```

But I can not get the other URL parameters after `#`. I have done other tests and it seems that the default HTTP server simply ignores all the parameters passed after the '#' sign.

```bash
curl 'http://127.0.0.1:9000/?state=hello_world#aaaaaaaaaaaaaaaaaaaaaaaaa'
curl 'http://127.0.0.1:9000/#this_is_a_parameter=yes&hello=world'
```
```
# http://127.0.0.1:9000/?state=hello_world#aaaaaaaaaaaaaaaaaaaaaaaaa
/?state=hello_world, http://127.0.0.1:9000/?state=hello_world
{state: hello_world}

# http://127.0.0.1:9000/#this_is_a_parameter=yes&hello=world
/, http://127.0.0.1:9000/
{}
```

Do you have an idea on how to solve the problem?

Thank you!

**Comment by devoncarew** [comment]
Do you know from the url spec whether this is correct - that the params shouldn't instead be passed before the fragment identifier?

**Comment by ShellBear** [comment]
Yes, I'm working with the Imgur OAuth 2.0 and all parameters are passed after the fragment identifier.

The doc says:
> An example User Agent flow response is shown below:
> `https://example.com/oauthcallback#access_token=ACCESS_TOKEN&token_type=Bearer&expires_in=3600`

https://apidocs.imgur.com/?version=latest#javascript-responses-for-the-response_type-token

**Comment by DanTup** [comment]
The fragment part of a URL is not passed to the server so Dart won't have any access to this. The imgur API doc linked above has some info about this:

> The access token is returned to your application in the fragment as part of the `access_token` parameter. Since a fragment (the part of the URL after the `#`) is not sent to the server, client side javascript must parse the fragment and extract the value of the `access_token` parameter.

It also includes some JS for decoding the "querystring" included in the fragment.
