### ISSUE TITLE
DateTime VM implementation DST transitioning temporary solution

### ISSUE THREAD

**Issue by Jonas-Sander** [dart-lang/sdk#39137]
https://github.com/dart-lang/sdk/blob/fccdd5fb429002c6ba6a4f421a48f8465c287aec/sdk/lib/_internal/vm/lib/date_patch.dart#L333-L336

What I read [online](https://www.timeanddate.com/time/dst/) is this:
> Not Always One Hour
> Today clocks are almost always set one hour back or ahead.
> 
> However, on Lord Howe Island, Australia, clocks are set only 30 minutes forward from LHST (UTC+10:30) to LHDT (UTC+11) during DST.
> 
> 30 and 45 minute time zones
> 
> Throughout history, there have been several variations, like half adjustments (30 minutes) or double adjustment (2 hours). Adjustments of 20 and 40 minutes have also been used.
> 

I just stumbled about these lines and wanted to give a heads up - I guess with the growing popularity of dart because of flutter this might be something that should get a look from you guys. Feel free to close if this is not important :).

**Comment by devoncarew** [comment]
@lrhn - any sense for the best place to triage this (the impl. of dart:core DateTime)?

**Comment by devoncarew** [comment]
Moved to `area-library` `library-core`.

**Comment by lrhn** [comment]
I believe that code has been updated to be more general. The only assumptions left are that time zone changes are at most two hours, and there is at most one time zone change in a single day.
