### ISSUE TITLE
[vm/ffi] Migrate to NNBD

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#39144]
Sub-issue of #38037. This tracks the migration of the `dart:ffi` libraries to NNBD.

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by dcharkes** [comment]
@leafpetersen see my questions on the doc and on [the CL](https://dart-review.googlesource.com/c/sdk/+/131380).
