### ISSUE TITLE
Frontend: Constant evaluation allows extension methods.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39146]
Example:
```dart
extension on Object {
  int operator~() => 42;
}

main() {
 const Object o = Object();
 const int x = ~o;
 print(x);
}
```
The front-end constant evaluator does not catch that we try to invoke an extension member here, but instead crashes. Backends report this crash, here the VM:
```
$ dart extbad.dart
Unhandled exception:
'file:///usr/local/google/home/lrn/dart/co/sdk/dev/extbad.dart': error: Invocation of _extension#0|~
#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

The constant evaluator should not allow `~` to be used in constant expression except when invoking the instance member `~` of `int`.

The specification is being updated to specify this clearly, but it has always been the intention that user code invocations cannot occur in constant expressions.

**Comment by johnniwinther** [comment]
@askeksa-google can you take a look at this?

**Comment by askeksa-google** [comment]
Fix in https://dart-review.googlesource.com/c/sdk/+/123247

Test case fails in the analyzer. Filed https://github.com/dart-lang/sdk/issues/39149 for the analyzer bug.
