### ISSUE TITLE
Cherry-pick 6354b0b97dc to dev channel, so it's included in D26 release

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39159]
Since we are distributing arm64 dart-sdks, I think it makes sense to include that fix.

Please cherry-pick 6354b0b97dc to dev channel, so it's included in D26 release.

**Comment by athomas** [comment]
This will not be picked into 2.6.0, but will be considered for a potential 2.6.1 release later.

**Comment by athomas** [comment]
Released in 2.6.1.
