### ISSUE TITLE
[VM] Crash in FlowGraph::RenameRecursive due to incorrect stack depth

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39152]
```dart
class A {
  int foo() => 42;
}

A a = new A();

class B {
  B(int x) {
    print(x);
  }
}

main() {
  B(a.foo());
}
```

```
pkg/vm/tool/precompiler2 foo.dart foo.snapshot
```

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=(nil)
version=2.7.0-edge.5a92c0e39585cdbd4fcc4a38e3e6c804537b85ab (Mon Oct 28 15:20:11 2019 +0000) on "linux_x64"
thread=255897, isolate=isolate(0x55bdd61ac100)
  pc 0x000055bdd405c63a fp 0x00007ffca484cca0 dart::FlowGraph::RenameRecursive(dart::BlockEntryInstr*, dart::GrowableArray<dart::Definition*>*, dart::GrowableArray<dart::PhiInstr*>*, dart::VariableLivenessAnalysis*, dart::ZoneGrowableArray<dart::Definition*>*)
  pc 0x000055bdd405cac2 fp 0x00007ffca484cda0 dart::FlowGraph::RenameRecursive(dart::BlockEntryInstr*, dart::GrowableArray<dart::Definition*>*, dart::GrowableArray<dart::PhiInstr*>*, dart::VariableLivenessAnalysis*, dart::ZoneGrowableArray<dart::Definition*>*)
  pc 0x000055bdd405bb3f fp 0x00007ffca484ce40 dart::FlowGraph::Rename(dart::GrowableArray<dart::PhiInstr*>*, dart::VariableLivenessAnalysis*, dart::ZoneGrowableArray<dart::Definition*>*)
  pc 0x000055bdd405ad8b fp 0x00007ffca484cf90 dart::FlowGraph::ComputeSSA(long, dart::ZoneGrowableArray<dart::Definition*>*)
```

For `main` the following flow graph is constructed from bytecode:
```
==== file:///usr/local/google/home/alexmarkov/work/dart/sdk/test_hello4.dart_::_main
B0[graph]:0
B14[function entry]:2
    t0 <- AllocateObject(B)
    StoreLocal(var0 @0, t0)
    t1 <- LoadLocal(var0 @0)
    PushArgument(t1)
    t2 <- StaticCall:6( get:a<0> , result_type = T{A?})
    t2 <- StoreLocal(var1 @-1, t2)
    PushArgument(t2)
    t3 <- LoadLocal(var1 @-1)
    t4 <- LoadLocal(:t3 @-5)
    CheckNull:8(t4)
    DropTemps(1)
    t2 <- StaticCall:10( foo<0> t2, using unchecked entrypoint, result_type = T{_Smi})
    PushArgument(t2)
    StaticCall:12( B.<0> t1, t2)
    t0 <- Constant(#null)
    Return:14(t0)
```

The problem is that `t0 <- AllocateObject(B)` stays on the stack, but it is only used in `StoreLocal(var0 @0, t0)` next to it. While `t0 <- AllocateObject(B)` value stays on the stack, flow graph builder uses `BaseFlowGraphBuilder::MakeTemporary()` to reference another value on the stack. That reference (`t4 <- LoadLocal(:t3 @-5)`) is done by index of value on the stack (which is calculated using current stack depth).

After generating flow graph for constructor invocation, original `t0 <- AllocateObject(B)` value is dropped using `BaseFlowGraphBuilder::Drop()`: https://github.com/dart-lang/sdk/blob/805989b7cd60f54d989b0d09a2bdcb0ead088943/runtime/vm/compiler/frontend/base_flow_graph_builder.cc#L673-L687

`t0 <- AllocateObject(B)` doesn't have SSA temp and it's not LoadLocal, so `BaseFlowGraphBuilder::Drop()` simply clears temp index of `t0 <- AllocateObject(B)`.
(AST-based pipeline uses `LoadLocal` after `AllocateObject` when generating constructor invocation, so `Drop()` doesn't clear its temp index.)

After that, during SSA construction there is code which skips instructions without temp index and doesn't append them to `env`: https://github.com/dart-lang/sdk/blob/805989b7cd60f54d989b0d09a2bdcb0ead088943/runtime/vm/compiler/backend/flow_graph.cc#L1410-L1414
This effectively removes value `t0 <- AllocateObject(B)` from the middle of the expression stack. Subsequent use of temporary variable `t4 <- LoadLocal(:t3 @-5)` would try to find value in `env` using the index which was calculated during flow graph construction, and it counts `t0 <- AllocateObject(B)`. So that use of temporary variable causes out-of-bounds access to `env` and crash.

My understanding is that `BaseFlowGraphBuilder::Drop()` is not working correctly - it shouldn't just clear temp index as clearing it changes stack depth for all instructions between definition of dropped instruction and `Drop()`.

/cc @mraleph @aartbik @mkustermann

**Comment by aartbik** [comment]
As another data point, I actually was working on adding ASSERTs to the SSA construction that verify the t<n> = .... assignment corresponds to exactly a stack depth of <n> at each statement, just to make sure we have graph consistency (this would have caught several OSR fails much earlier), but this still had several failures around various constructs as well.

**Comment by mraleph** [comment]
Clarification: 

> simply clears temp index of `t0 <- AllocateObject(B)`

I think we clear temp index of `StoreLocal(var0 @0, t0)`. 

Potential fix would be to change `BaseFlowGraphBuilder::MakeTemporary` to `set_ssa_temp_index(0)` on all definitions in the stack to prevent `Drop` from just clearing their temp index and thus invalidate the stack state.

**Comment by mraleph** [comment]
This seems to fix it:

```patch
diff --git a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
index 60c45cb2fa3..70f5d216f7c 100644
--- a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
+++ b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
@@ -633,7 +633,9 @@ LocalVariable* BaseFlowGraphBuilder::MakeTemporary() {
   // The value has uses as if it were a local variable.  Mark the definition
   // as used so that its temp index will not be cleared (causing it to never
   // be materialized in the expression stack).
-  stack_->definition()->set_ssa_temp_index(0);
+  for (Value* item = stack_; item != nullptr; item = item->next_use()) {
+    item->definition()->set_ssa_temp_index(0);
+  }

   return variable;
 }
```

**Comment by alexmarkov** [comment]
@mraleph this fix violates other assumptions and crashes in the following way when training kernel service:

```
output: ../../runtime/vm/compiler/frontend/base_flow_graph_builder.cc: 739: error: expected: !stack_->definition()->HasSSATemp()
version=2.7.0-edge.5a92c0e39585cdbd4fcc4a38e3e6c804537b85ab (Mon Oct 28 15:20:11 2019 +0000) on "linux_x64"
thread=119283, isolate=main(0x558c8dfcb800)
  pc 0x0000558c8b2a8c1c fp 0x00007ffcea753cd0 dart::Profiler::DumpStackTrace(void*)
  pc 0x0000558c8aea4d92 fp 0x00007ffcea753db0 dart::Assert::Fail(char const*, ...)
  pc 0x0000558c8b4b9fcc fp 0x00007ffcea753e10 dart::kernel::BaseFlowGraphBuilder::GetArguments(int)
  pc 0x0000558c8b502399 fp 0x00007ffcea753ec0 dart::kernel::FlowGraphBuilder::InstanceCall(dart::TokenPosition, dart::String const&, dart::Token::Kind, long, long, dart::Array const&, long, dart::Function const&, dart::kernel::InferredTypeMetadata const*, bool, dart::kernel::CallSiteAttributesMetadata const*)
  pc 0x0000558c8b4f2426 fp 0x00007ffcea753fc0 dart::kernel::StreamingFlowGraphBuilder::BuildMethodInvocation(dart::TokenPosition*)
  pc 0x0000558c8b4ea4bc fp 0x00007ffcea754010 dart::kernel::StreamingFlowGraphBuilder::BuildExpression(dart::TokenPosition*)
  pc 0x0000558c8b4ec5b0 fp 0x00007ffcea754050 dart::kernel::StreamingFlowGraphBuilder::BuildStatement()
```

Is it really needed to clear temp_index when dropping value from the stack? Maybe we can always generate `DropTempsInstr` and keep stack depth unmodified?

**Comment by mraleph** [comment]
This assertion seems just a sanity check. This should probably fix it

```patch
diff --git a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
index 60c45cb2fa3..ae5a07ce5da 100644
--- a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
+++ b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
@@ -633,7 +633,10 @@ LocalVariable* BaseFlowGraphBuilder::MakeTemporary() {
   // The value has uses as if it were a local variable.  Mark the definition
   // as used so that its temp index will not be cleared (causing it to never
   // be materialized in the expression stack).
-  stack_->definition()->set_ssa_temp_index(0);
+  for (Value* item = stack_; item != nullptr; item = item->next_use()) {
+    if (!item->definition()->IsPushArgument())
+      item->definition()->set_ssa_temp_index(0);
+  }

   return variable;
 }
```

**Comment by alexmarkov** [comment]
@mraleph Thank you for the quick fix.
