### ISSUE TITLE
No compile error in analyzer for void explicit extension argument

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39156]
According to the [Dart Static Extension Methods design document](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#explicit-extension-member-invocation)

> It is a compile-time error if the static type of the argument expression (expr) of an explicit extension invocation is void. (Expressions of type voidare only allowed in a few specific syntactic positions, and the new explicit extension invocation object position is not included in those.)

But in fact, there is no error in analyzer

```dart
class C {
  String name = "My name is C";
}

extension ExtendedC on C {
  String checkme() => this.name;
}

void getC() => new C();

main() {
  ExtendedC(getC()).checkme();
}
```
The code above produces no error in analyzer with --enable-experiment=extension-methods flag. " Error: This expression has type 'void' and can't be used." in VM.

dartanalyzer version 2.6.0-dev.8.2
Dart VM version: 2.6.0-dev.8.2 (Thu Oct 24 09:35:58 2019 +0200) on "windows_x64"

**Comment by devoncarew** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/123461
