### ISSUE TITLE
Analyzer shows no error for missint extension unary minus

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39158]
```dart
class C {
}

extension Extension1 on C {
}

main() {
  C c = new C();
  -Extension1(c);
}
```
There is no compile error in analyzer for missing unary minus operator

dartanalyzer version 2.6.0-dev.8.2

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/123462

**Comment by sgrekhov** [comment]
@bwilkerson the same issue exists for "~" operator as well. Does this fix fix it?

**Comment by sgrekhov** [comment]
Issue with the `~` operator fixed as well. Thank you
