### ISSUE TITLE
dart2native: reverse -o & -k in help

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#39154]
The help text for dart2native is almost but not quite in alpha order (2.6.0-dev.8.1). Move the `-o` line after `-k`, and we'll be good.

```
$ dart2native --help
Usage: dart2native <main-dart-file> [<options>]

Generates an executable or an AOT snapshot from <main-dart-file>.

-D, --define=<key=value>       Set values of environment variables. To specify
                               multiple variables, use multiple options or use
                               commas to separate key-value pairs.
                               E.g.: dart2native -Da=1,b=2 main.dart

    --enable-asserts           Enable assert statements.
-h, --help                     Display this help message.
-o, --output=<path>            Set the output filename. <path> can be relative
                               or absolute.
                               E.g.: dart2native main.dart -o ../bin/my_app.exe

-k, --output-kind=<aot|exe>    
          [aot]                Generate an AOT snapshot.
          [exe] (default)      Generate a standalone executable.

-p, --packages=<path>          Get package locations from the specified file
                               instead of .packages. <path> can be relative or
                               absolute.
                               E.g.: dart2native --packages=/tmp/pkgs main.dart

-v, --verbose                  Show verbose output.
```

**Comment by cskau-g** [comment]
This ordering is intentional since it is alpha ordered by the (full) flag name:
```
    ..addFlag('enable-asserts', ...
    ..addFlag('help', ...
    ..addOption('output', ...
    ..addOption('output-kind', ...
    ..addOption('packages', ...
```

The confusion I believe comes from some of the flags having an optional abbreviation ('o', 'k', ...), which doesn't follow the same order.
But since not all flags have an abbreviation that does not make a good sorting key.

I would suggest we leave the order as is.

**Comment by kwalrath** [comment]
Unfortunately the abbreviations come first, so it's easy to think it's a mistake. (I actually missed the `-k` flag when I first wrote the docs, possibly because of this.)

One more thing... Some flags have blank lines above them in the help, and some don't. Can we make them all have a blank line separator?

**Comment by cskau-g** [comment]
I personally prefer the current order, but I'll leave it up to you.

The blank lines, like some of the previous discussion about formatting choices and key=value pairs, is ultimately up to the args package.
In https://github.com/dart-lang/args/issues/48 it's stated that the forced newline after all multiline flags is WAI. It's been suggested to make it configurable, but I don't think it's been implemented yet.
