### ISSUE TITLE
Why 'Function.apply' don't have a parameter named 'typeArguments' ?

### ISSUE THREAD

**Issue by zjuwjf** [dart-lang/sdk#39177]
Why 'Function.apply' don't have a parameter named 'typeArguments' ?

So it looks like that the api of Function.apply is limited in some scenarios.

**Comment by lrhn** [comment]
It is deliberately limited.

Currently the type arguments to a generic function or interface must always be either literal types or other type parameters. That allows our ahead-of-time compilers to restrict the types that _might_ occur the value of a type parameter.

If `Function.apply` had a `typeArguments` parameter, what should its type be? The obvious solution would be `Iterable<Type>` or `List<Type>`, but for that to work, we would have to allow a `Type` object to be reified as a type argument. That breaks the separation described above, and could significantly bloat the output of, for example, dart2js.

So, we do not allow you to call generic functions with types supplied as run-time `Type` values.

**Comment by zjuwjf** [comment]
If `Function.apply` is used inside of `noSuchMethod(Invocation invocation)` , could these `Type`objects be reified ?

So maybe an object of `Invocation` could offer an api like `applyWithTypeArguments` ?

It is really needed in some scenarios.

Perhaps, there are more ways than difficulties 😄

**Comment by mraleph** [comment]
Based on the @lrhn I am closing this issue as not planned. 

Lasse, feel free to reopen and change the title / area if you think there is some work to be done.
