### ISSUE TITLE
Analyzer ignores (but does not reject) extension method applications during constant evaluation

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#39170]
The example program below tests that extension methods are not evaluated during constant evaluation.

Note that if `o.length` is not interpreted as an extension method application, then the program is ill-typed.

The analyzer correctly treats `o.length` as an extension method application for typing purposes, and correctly does not evaluate the extension method.  However, instead of issuing an error during constant evaluation, it instead evaluates `o.length` as an instance getter application, producing an incorrect value instead of an error.

```dart
extension ExtObject on Object {
  int get length => 4;
}

class B {
  final l;
  const B(Object o) : l = o.length;
  const B.fromInt(int x) : l = x;
}

class C {
  const C(dynamic b0, dynamic b1) : assert(identical(b0, b1));
}

void main() {
  // passes on analyzer because the constructor to B calls the string getter on o
  // fails on CFE because calling an extension method is not allowed
  const C(B("helloworld"), B.fromInt(10));
}
```

cc @eernstg @lrhn @stereotype441

**Comment by stereotype441** [comment]
@bwilkerson would you mind looking at this?

**Comment by bwilkerson** [comment]
It should be fixed by https://dart-review.googlesource.com/c/sdk/+/123542
