### ISSUE TITLE
FFI not supported message

### ISSUE THREAD

**Issue by shamblett** [dart-lang/sdk#39189]
I've been putting together a package using FFI developed on  linux X64 with the target machine being linux on arm architectures, all going very well until I upgraded the arm board to Dart 2.6.0-dev8.2,  I'm now getting :-

'import of ffi is not supported in the current dart runtime' 

when I run my Dart app. It works OK on my X64 dev machine, am I missing something?

**Comment by mraleph** [comment]
@dcharkes Daco could you investigate?

**Comment by dcharkes** [comment]
We do not support the hardfp (Linux on Arm32) calling convention yet (https://github.com/dart-lang/sdk/issues/36309).

@shamblett is your arm board 32 or 64 bit?

**Comment by shamblett** [comment]
I'm using the Dart ARM7 SDK, as I said above this was working fine, I can't remember exactly what dev release it was, maybe Dart 2.6.0-dev4, it was before FFI was upgraded to use extension methods where we didn't have the separate FFI package which now does allocate etc.

**Comment by dcharkes** [comment]
If your board is Arm32, then it was never supposed to be enabled. However, we had a bug in which it was not properly disabled on Arm32 Linux. I fixed that on [October 2nd](https://dart-review.googlesource.com/c/sdk/+/119323). 2.6.0-dev.4.0 (345c4b6bd833e431ab2d5f41e45dcd3b14ad3d39) was released on September 30, so in that version the FFI was erroneously enabled.

If you were not using floating points in FFI calls, using the FFI would have been fine. However, if you were using floating points in FFI calls, I would have expected to see errors (like passing random values to native functions). Did you use floating points in FFI calls?

As a solution now, we can try to bring forward work on supporting the FFI Linux Arm32 (#36309).

cc @mkustermann

**Comment by shamblett** [comment]
I have a few wrapper API calls that return floats, however my testing on my target board didn't use these so I wouldn't have noticed, everything else(mainly pointers, ints, strings) worked fine. OK thanks, I'll keep an eye on the work for this, I can move to arm64 in the meantime.

**Comment by mkustermann** [comment]
@dcharkes This is probably the only missing thing in our configuration matrix for the current feature set, right?

Since new features might take longer to implement (i.e. after D27), we could consider prioritizing this (hopefully small) task for D27. wdyt?

**Comment by dcharkes** [comment]
Yeah sure.

I'll close this issue, as it is a duplicate. Progress will be tracked in #36309.
