### ISSUE TITLE
codeOffset/codeLength are 0 for results from search.getElementDeclarations

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#39192]
@scheglov I don't know if this broke recently, but "Go to Workspace Symbol" in VS Code is jumping to the first line in files (https://github.com/Dart-Code/Dart-Code/issues/2083). It seems to be because `codeLength` and `codeOffset` are both `0` in the results to `search.getElementDeclarations` even though all the other info (offset, line, column) are there.

I could make this fall back, but there's no `length` to go with the normal offset, and since `codeOffset` is not optional according to the spec, this seems like it might be a bug.

```
[4:50:14 PM] [Analyzer] [Info] ==> {
	"id": "23",
	"method": "search.getElementDeclarations",
	"params": {
		"pattern": ".*[Zz].*[Zz].*[Zz].*",
		"maxResults": 500
	},
	"clientRequestTime": 1572540614761
}

[4:50:14 PM] [Analyzer] [Info] <== {
	"id": "23",
	"result": {
		"declarations": [
			{
				"name": "xzzz",
				"kind": "FIELD",
				"fileIndex": 0,
				"offset": 79047,
				"line": 2267,
				"column": 20,
				"codeOffset": 0,
				"codeLength": 0,
				"className": "Int32x4"
			},
			{
				"name": "yzzz",
				"kind": "FIELD",
				"fileIndex": 0,
				"offset": 81091,
				"line": 2331,
				"column": 20,
				"codeOffset": 0,
				"codeLength": 0,
				"className": "Int32x4"
			},
			{
				"name": "zxzz",
				"kind": "FIELD",
				"fileIndex": 0,
				"offset": 82113,
				"line": 2363,
				"column": 20,
				"codeOffset": 0,
				"codeLength": 0,
				"className": "Int32x4"
			},
```

**Comment by scheglov** [comment]
Yes, I broke it.
We don't properly serialize `codeOffset` and `codeLength` when we put data into the cache.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/123689

**Comment by DanTup** [comment]
Great, thanks!
