### ISSUE TITLE
Overridden generic methods in legacy library do not match NNBD ones

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39208]
Given:

**nnbd.dart:**

```dart
abstract class Nnbd {
  void method<T>();
}
```

**legacy.dart:**

```dart
// @dart = 2.5
import 'nnbd.dart';

abstract class Legacy extends Nnbd {
  void method<T>();
}
```

If I try to compile these using:

```
./pkg/dev_compiler/bin/dartdevc.dart --enable-experiment=non-nullable -k legacy.dart -o out.js
```

I get:

```
legacy.dart:5:8: Error: Declared type variables of 'Legacy.method' doesn't match those on overridden method 'Nnbd.method'.
  void method<T>();
       ^
nnbd.dart:2:8: Context: This is the overridden method ('method').
  void method<T>();
       ^
```

I think what's going on is that the implicit bound on `T` in `Nnbd.method<T>()` is `Object?` and in `Legacy.method<T>()` it's `Object*`. Since bounds must match exactly in overrides, it considers that an error. Like #39207, this means migrating a library can break downstream users.

I ran into this while testing out the migrated dart:async. The `_EventStreamSubscription.asFuture()` method in the unmigrated dart:html overrides that mean from StreamSubscription and then reports the above error. There are a number of other methods in dart:html that get broken this way.

I'm guessing the right fix is to treat legacy types as equivalent to the corresponding migrated type when checking bounds on generic method overrides.

cc @leafpetersen @scheglov

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/132846
