### ISSUE TITLE
Parent classes in memory profiler 

### ISSUE THREAD

**Issue by BharathMG** [dart-lang/sdk#39200]
Hey guys,

When I use memory profiler in dev tools, it is impossible to find which class is responsible for leaking dart and flutter objects. For ex, when I scroll the flutter list, I see a dart hidden class `_List` memory keeps growing. And I find no way to track down the parent class responsible for leaking those dart objects.

What is the recommended way to find memory leak issues using memory profiler?

**Comment by rmacnak-google** [comment]
Try looking at the tools in Observatory under the "heap snapshot" page.

**Comment by mraleph** [comment]
@jacob314 Does DevTools support retaining paths feature? 

Should this issue be filled at flutter/devtools as a Feature Request?

**Comment by jacob314** [comment]
I've moved this issue to https://github.com/flutter/devtools/issues/1292
This is absolutely the sort of feature we want to handle in DevTools and I believe the VM now supports the public API we need to provide it.
We're in the middle of porting DevTools to Flutter Web so it may be a couple months before you see us implement this feature in DevTools.
