### ISSUE TITLE
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: RangeError: Value not in range: 1

### ISSUE THREAD

**Issue by AmgadMahmoud** [dart-lang/sdk#39223]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: RangeError: Value not in range: 1
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:677:7)
```

For additional log information, please append the contents of
file://C:\Users\ITSpark\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.1.0; please re-open if you see this in a recent version of Dart/Flutter.
