### ISSUE TITLE
built_value and built_value generator have circular dependencies causing Flutter -> Fuchsia roll to fail

### ISSUE THREAD

**Issue by kf6gpe** [dart-lang/sdk#39238]
This might just be a simple fix, but looking at the build_value and built_value_generator projects its not clear to me how to correctly translate this circular dependency to gn would be.  

cc @davidmorgan @zanderso .

Possible dupe of https://github.com/flutter/flutter/issues/44188. Filed by Fuchsia team as https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=40784; comments should likely occur there.

**Comment by davidmorgan** [comment]
Sorry about that. Commented on fuchsia.dev.

**Comment by davidmorgan** [comment]
According to note on fuchsia.dev they have a workaround, nothing to do for Dart SDK. Will be properly resolved once `built_value` `7.0.0` has propogated through the various core packages.
