### ISSUE TITLE
Make it more obvious how to disable analytics

### ISSUE THREAD

**Issue by bvanrijn** [dart-lang/sdk#39233]
On https://dart.dev/get-dart, I read:

>  Dart tools may send usage metrics and crash reports to Google. By downloading the Dart SDK, you agree to the [Google Terms of Service](https://policies.google.com/terms). Note: The [Google Privacy Policy](https://policies.google.com/privacy) describes how data is handled in this service.

I would like to know how to stop the Dart tools from collecting usage metrics and crash reports altogether.

After searching through the code base, I found [pkg/telemetry/lib/telemetry.dart](https://github.com/dart-lang/sdk/blob/983447f95aac00a307c16b8b872585eebb93db1d/pkg/telemetry/lib/telemetry.dart), which mentions a file `~/.dart/analytics.json`, but it does not mention what to put there to disable collection of analytics (I have a hunch it's `{"enabled": false}`, but I'm not sure). A flag it mentions in passing, `--no-analytics`, doesn't seem to do anything (other than printing the help text).

A tool that gets this right, IMO, is the `dotnet` CLI. Out of the box, it collects metadata, but [what data it collects](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#data-points) is documented, and so is [the opt-out process](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#how-to-opt-out).

I guess my problem with how the Dart SDK handles this is twofold:

1. It is not obvious *what* is being collected, and I wished you went with a shorter, more focused privacy policy, such as https://developers.google.com/speed/public-dns/privacy
2. It is not obvious *how* to stop this data from being collected

Could you make it more obvious how to disable analytics? Thank you for your help.

**Comment by mraleph** [comment]
Assigning to @mit-mit to figure possible course of action here.

**Comment by Xylobol** [comment]
I'd like to also note here that it's a little foggy as to how much Google influence there is when it comes to Dart. I run a firm that's going to be launching open and private web apps, and the ambiguity around privacy and the Dart tooling pushed us to adopt TypeScript instead.

**Comment by Xylobol** [comment]
Taking a closer look, it would appear that setting the `enabled` key for analytics to `false` in the preferences file would do the trick. However, it's questionable that we had to pick apart the source to get to this conclusion. This is something that should default to disabled or have a yes/no prompt for on first run, and the documentation should be clear on how to turn analytics on and off.

**Comment by mit-mit** [comment]
Hi, thanks for the feedback. I'm doing some more digging, not ignoring this. My current indications are that we currently send no analytics from the Dart SDK, and that these code paths are only activated when the Dart SDK is embodied inside the Flutter SDK (which does have analytics prompts on first-run and settings). I'm working to confirm this.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> Hi, thanks for the feedback. I'm doing some more digging, not ignoring this. My current indications are that we currently send no analytics from the Dart SDK, and that these code paths are only activated when the Dart SDK is embodied inside the Flutter SDK (which does have analytics prompts on first-run and settings). I'm working to confirm this.

Any updates to this?

**Comment by mit-mit** [comment]
We've still not located any current Dart paths that send analytics outside of Flutter. We are discussing to rework the Dart tools pipeline to potentially include analytics, but when and if we do that, we will add explicit disclosure UI on first run, and provide an opt-out flag or setting.

**Comment by astriskit** [comment]
@mit-mit - last comment shows no data is sent; but is there a better way like flutter's `flutter config --no-analytics` command to switch it off; if not, is there a plan for the same.

**Comment by haikusw** [comment]
The documentation at https://dart.dev/get-dart needs to get updated then because it definitely says that Dart may send analytics and doesn't document any way to turn them off.

If you do add analytics sending outside of Flutter, I hope you'll make sure it's easy to turn off same as Flutter appears to be. Otherwise Game Over in terms of using Dart for me or my clients.

Cheers.

![Screen Shot 2020-05-07 at 12 51 47 PM](https://user-images.githubusercontent.com/222271/81338982-57a75400-9062-11ea-8c41-6d021ec20223.png)

**Comment by mit-mit** [comment]
We're working on a new `dart` developer tool (similar to the `flutter` tool), which will collect some usage and crash metrics. Once we complete that we plan on 1) updating the page in the screenshot to provide clarity on what is collected, and 2) providing an easy analytics opt-out (just like the flutter tool).

**Comment by geira** [comment]
> We're working on a new `dart` developer tool (similar to the `flutter` tool), which will collect some usage and crash metrics. Once we complete that we plan on 1) updating the page in the screenshot to provide clarity on what is collected, and 2) providing an easy analytics opt-out (just like the flutter tool).

That is not enough. According to the GDPR and a recent German court decision, analytics are defined as non-necessary services and require explicit, voluntary consent before you can send any data. Opt-out after the fact is illegal in the EU/EEC.

**Comment by 0uep** [comment]
Hi @bvanrijn @geira and all other followers of this issue
New issue https://github.com/flutter/flutter/issues/73657 to request application of EU/EEC law.
Happy new year :wink:

**Comment by omidraha** [comment]
```bash
    $ flutter config --no-analytics
    $ dart --disable-analytics
   
```

**Comment by martin-braun** [comment]
@omidraha WTF, you even have to disable it for `dart`? I almost consider this to be shady practices, please disable this already Google.
