### ISSUE TITLE
Uncaught exception: Invalid argument: null

### ISSUE THREAD

**Issue by AH-M** [dart-lang/sdk#39232]
into the https://dartpad.dartlang.org, when i'm using optional parameters method it shows error like Uncaught exception: Invalid argument: null. 

void main () {
         z(4);     
}
void asdf (int a, [int s, int d, int f]) {
  
  int z = a+s+d+f; 
     print("$a"); 
     print("$s"); 
     print("$d"); 
     print("$f"); 
     print("$z");  
}

**Comment by mraleph** [comment]
Your parameters `s`, `d`, `f` are `null` so you are trying to compute `4 + null` which throws this error.

Some of the exceptions in Dart Pad are not very user-friendly (because it uses production compiler `dart2js` /fyi @vsmenon @sigmundch ), but otherwise this is working as expected.
