### ISSUE TITLE
Prepare nnbd_migration and preview output for UX study

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#39247]
I've pared down the logging package (at commit `49669c490c2d0b57badf07f2df2cae61ce1b605c`):

* from 384 LOCs in `lib/` to 302,
* from 641 LOCs in `test/` to 445,
* from 1025 LOCs total to 747.

I think that 302 LOC in lib/ is sufficiently tight for a UX study. The nnbd-migration tool currently produces some "not great" results. I'd like to burn down this list before a UX study:

### Poor instrumentation

* [ ] ~~`lib/src/level.html`, line 14, `Comparable`:~~

   ~~The hover info on this non-nullable type argument has about 30 details reading "Something about initializer inheritance", all of which link to garbage destinations.~~

  (Brian) The information about sites that have not changes should probably be removed for the study.

* [ ] `lib/src/level.html`, line 44, `List`:

   ~~The hover info on this non-nullable type has 2 details reading "Something about initializer inheritance":~~

   * ~~The first links to `final levels = Level.LEVELS;`~~
   * ~~The second links to `final sorted = Level.LEVELS;`~~
   * ~~Both are cases where `LEVELS` has been assigned to a local variable with an inferred type.~~

  (Brian) The information about sites that have not changes should probably be removed for the study.

* [ ] `lib/src/level.html`, line 55, `bool`:

   ~~The hover info on this non-nullable type has two details reading "Something about inheritance." I think that this means that the return type's non-nullability was just inherited from `Object.==`. We should just say that and not have two reasons.~~

  (Brian) The information about sites that have not changes should probably be removed for the study.

* [x] `lib/src/level.html`, line 55, inserted `?`:

   ~~The hover info on this inserted `?` has two details reading "A nullable value is assigned" that link back to the same method.~~

  (Brian) I think this is because the definition of `==` in `Object` has a parameter of type dynamic. It would be nice to be able to migrate against the migrated SDK.

  (Brian) Confirmed that this is not a problem when migrating against the NNBD SDK.

* [x] `lib/src/logger.html`, line 101, inserted `!`:

   None of the `!` have good Detail destinations. In this case, there is one detail reading "A nullable value can't be used here", but it links to the const `Level()` constructor.

  (Brian) I tracked this one down and the issue is that we're running into a 'never' that needs to be replaced, and that's leading us to erroneously choose the constructor.

  (Paul) after further investigation, Brian and I decided that in this case, it's appropriate to use 'never', because there's no particular choice of nullability/non-nullability that needs to be pointed to.  So we should just remove the bogus link.  Passing back to Brian/Sam to make this fix.

* [ ] `lib/src/log_record.html`, line 8, inserted `?`:

  The message is fine, but the link is to the field formal parameter and there's no way for users to get to the argument sites. In this case we should either
  - create a separate detail for each of the places where a nullable value is passed as an argument and they should link to the arguments at the invocation sites, or
  - extend `RegionDetail` to allow nested children and display a list of arguments sites under this item.

  I prefer the second option.

  The problem is bigger than I initially realized. The problem is the inability for users to navigate because of implicit types. In this case it's implicit type arguments, but there are other places where this can occur. Another option is to insert the implicit types to make them visible and provide a place to hang further navigation. We'd need to make sure it's obvious that they are not part of the source code so that users don't think the migration changes include adding types everywhere.

* [x] (https://github.com/dart-lang/sdk/issues/39374) `lib/src/log_record.html`, line 11, inserted `?`:

  The single detail, "This field is initialized by an optional field formal parameter that has an implicit default value of 'null'" is great, but the link destination is just the text, `this.`, rather than `this.object`.

  (Brian) Actually, the HTML in question is `<a id="o627">this.<a href="log_record.html#o269">object</a></a>`, which seems to be correct. I suspect that this is a JS issue in that the outer anchor has the class `target` applied to it but the inner anchor does not.

* [ ] `lib/src/logger.html`, line 107, inserted `!`:

   In this case the single reason detail reads "node with no info (type(2171))" with no destination.

  (Brian) I believe that this is caused by a 'never' node.

  (Paul) Prototyped a solution in https://dart-review.googlesource.com/c/sdk/+/124902/, which has now landed.  Passing back to Brian/Sam to make further improvements.

* [x] `lib/src/logger.html`, line 121, inserted `?`:

   The 7th detail reads "upstream edge with no origin (always -> type(3870))" with no destination.

  (Brian) I believe that this is caused by an 'always' node.

  (Paul) Fixed by 8938a5ed2da9fca6f10903dd683c31713e9e8b10

* [x] `lib/src/logger.html`, line 128, inserted `?`:

   The single details reads "upstream edge with no origin (always -> type(4043))" with no destination.

  (Brian) I believe that this is caused by an 'always' node.

  (Paul) Fixed by 8938a5ed2da9fca6f10903dd683c31713e9e8b10

### Poor migration

* [x] `lib/src/logger.html`, line 37, inserted `?` on the Map _value_ type, Logger:

   The hover info has one detail reading "A nullable value is assigned" which sounds logical, but it links to some weird code:

   ```dart
   Logger._internal(this.name, this.parent, Map<String, Logger> children)
         : _children = children,
           children = UnmodifiableMapView(children) { // LINKS TO UnmodifiableMapView
       /* if (parent != null) */ parent._children[name] = this;
   }
   ```

   This is weird because (a) `children`'s value for `V` is `Logger`, non-nullable, (b), the re-assignment to children shouldn't decide `_children`'s nullability.

   (Sam): Paul said this is a case that Mike might know about. It hasn't been fixed, AFAIK, but I'm checking this box because I'm removing this public `children` field.

* [x] `lib/src/logger.html`, line 107, non-removed `@`:

  Shouldn't the migration engine remove `@`?

   (Sam): Not yet; removed usage of `@required`.

### Poor UI

* [ ] We should consider looking to see when a `!` is added to a field access in a place where promotion might be expected to promote the value and explicitly mention that promotion can't promote because it's a field.

* [x] Some regions get an underline when hovered over but aren't links like you might expect. See the file header in `lib/logging.html`.

**Comment by MichaelRFairhurst** [comment]
I found the cause of the first of the two poor migration issues:

```dart
// in logging_test.dart                                                                        
    expect(() {                                                                  
      loggerAB.children['test'] = null;                                          
    }, throwsUnsupportedError, reason: 'Children is read-only');
```

It's a case of where we create a node directly from `always`, so the UX output doesn't include it. I will figure out why it didn't create an in-between node.

+ @stereotype441 and @bwilkerson for thoughts on this issue. It's hard to believe the tool could/should handle this case. I'm assuming this is where we simply want to have the user see this and change the test and rerun?

**Comment by bwilkerson** [comment]
See https://github.com/dart-lang/sdk/issues/38775 for context on the plan to remove always and never. IIRC, Paul decided that we should do this incrementally until we had enough time to finish off the rest of the cases.

**Comment by srawlins** [comment]
I'm closing this for now as we're moving forward with the migrator as is. Future improvements need their own issues.
