### ISSUE TITLE
Wrong computation of class interface

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39259]
Consider the following program:

```dart
abstract class A1 {
  num g;
}

abstract class A2 {
  int g;
}

abstract class B implements A1, A2 {}

class C extends B {
  int get g => 42;
  set g(num value) {}
}

main() {
  B b = C();
  b.g.isEven; // Error.
  b.g = 1.0;
}
```

The interface of `B` should have a getter with return type `int` (because that's the most specific member signature among the ones named `g` in the superinterfaces of `B`), and it should have a setter with parameter type `num` (because `set g(num)` is the most specific member signature named `g=` from the superinterfaces).

However, when the above program is checked by the `dartanalyzer` from df678dbec0db5c3c4629301daf180236d99471b1 we get the following error at the `Error` comment:

```
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/usr/local/google/home/eernst/lang/dart/scratch/201911/n004.dart|18|7|6|The getter 'isEven' isn't defined for the class 'num'.
```

Tweaking the code a little, it seems to rely on the ordering of the superinterfaces, and not on the distinction between the implicitly induced getter/setter of a variable vs. explicitly declared getters or setters (if we swap the superinterfaces to `A2, A1` then error/OK swaps as well):

```dart
abstract class A1 {
  num get g1;
  int get g2;
  set s1(num _) {}
  set s2(int _) {}
}

abstract class A2 {
  int get g1;
  num get g2;
  set s1(int _) {}
  set s2(num _) {}
}

abstract class B implements A1, A2 {}

main() {
  B b = null;
  b.g1.isEven; // Error.
  b.g2.isEven; // OK.
  b.s1 = 1.0; // OK.
  b.s2 = 1.0; // Error.
}
```

Here's the response:

```
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/201911/n005.dart|22|10|3|A value of type 'double' can't be assigned to a variable of type 'int'.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/usr/local/google/home/eernst/lang/dart/scratch/201911/n005.dart|19|8|6|The getter 'isEven' isn't defined for the class 'num'.
```

**Comment by srawlins** [comment]
The analyzer now accepts both programs above with no errors or warnings (I'm using 2.8.0-dev.9.0)
