### ISSUE TITLE
dart2native static compile

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#39253]
how to compile native into static linked binary.

```
 # ldd ./bin/main.exe 
	linux-vdso.so.1 (0x00007ffd691f9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f65338b3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f65340c5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6533730000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f653370f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f653370a000)

```

If those requirement so not match the same, the native binary will coredump.

**Comment by mkustermann** [comment]
Merging this issue to https://github.com/dart-lang/sdk/issues/39296 

Is your use case to run the application inside a docker container? See also my response https://github.com/dart-lang/sdk/issues/39296#issuecomment-557204865

**Comment by netroby** [comment]
@mkustermann No that kind works, can we package all dependencies into single executable binary, 
Not copy them into target os.
