### ISSUE TITLE
Extensions aren't resolved when both available via part of and import

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#39262]
[Edit by eernstg] This is concerned with both the analyzer and the front end:

- [x] Analyzer #39263
- [x] Common front end #39264

---

When the same extension would be available either from an import or a `part of` directive, the analyzer seems to consider them as two different extensions and the frontend doesn't recognize the extension at all.

For instance, consider three Dart files: `extension.dart`, `library.dart` and `export.dart` with the following content:
```dart
// content of "extension.dart"
part of 'library.dart';

extension Bar on String {
 String get reversed => throw UnsupportedError('todo');
}
```
```dart
// content of "library.dart"
import 'export.dart';

part 'extension.dart';

void main() {
  print('Hello world'.reversed);
}
```
```dart
// content of "export.dart"
export 'library.dart';
```

Running dartanalyzer on these files yields
```
Analyzing extension-bug...
  error • A member named 'reversed' is defined in extensions 'Bar' and 'Bar' and neither is more specific. • library.dart:6:22 • ambiguous_extension_member_access
  hint • Unused import: 'export.dart'. • library.dart:1:8 • unused_import
1 error and 1 hint found.
```

In my understanding, that's valid dart code and there's only one `Bar` extension. It looks like the frontend doesn't find the extension at all in this case:
```
library.dart:6:22: Error: The getter 'reversed' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'reversed'.
        print('Hello world'.reversed);
                            ^^^^^^^^
```

My Dart version is `Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "linux_x64"`.

In this case the import/export doesn't make any sense of course, but it's a common practice for Dart packages to have one file that exports everything and then import that file from everywhere else.

**Comment by eernstg** [comment]
The following is actually sufficient:
```dart
// LIBRARY 'main.dart'.
import 'main.dart';

extension Bar on String {
 String get reversed => throw UnsupportedError('todo');
}

void main() {
  print('Hello world'.reversed);
}
```

**Comment by eernstg** [comment]
Cf. #39263 and #39264.

**Comment by srawlins** [comment]
Looks like analyzer and CFE are each clean.
