### ISSUE TITLE
dart.exe fails in Windows XP SP3 (x86)

### ISSUE THREAD

**Issue by DiWizard** [dart-lang/sdk#39276]
Is Windows XP/Windows Server 2003 are supported by Dart? 

On my Windows XP x86 SP3 and Windows Server 2003 x86 SP2 dart.exe generates error "The procedure entry point InetPtonW could not be located in the dynamic link library WS2_32.dll"

**Comment by mraleph** [comment]
We do not support Windows XP (See similar issue #19803)
