### ISSUE TITLE
Implement new prefix semantics for extension methods

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#39279]
See https://github.com/dart-lang/language/issues/671

- [ ] Tests / nail down spec change.
- [x] Implement in CFE.
- [ ] Implement in Analyzer.

FYI - @lrhn @leafpetersen @johnniwinther @stereotype441 - tentatively marking D27 for discussion.

**Comment by dgrove** [comment]
This is no longer a P0 for D27, correct?

**Comment by leafpetersen** [comment]
> This is no longer a P0 for D27, correct?

It may be.  There's some desire to do the breaking change version of this, in which case I would prefer we land this in D27.

**Comment by leafpetersen** [comment]
We're moving forward with this for D27.  @johnniwinther has a CL implementing the change in resolution for the CFE.  I'll work with @stereotype441 to get this done in the analyzer today.  I'll take over the CL from @lrhn with language tests.  For deferred libraries, we will temporarily disallow importing libraries with extensions as deferred unless all extensions are hidden, and we will relax this shortly (this just gives us breathing room to be sure we have the right affordances).

**Comment by vsmenon** [comment]
@a-siva - fyi if flutter rolls are starting today.

**Comment by leafpetersen** [comment]
@bwilkerson will handle the analyzer part.

**Comment by a-siva** [comment]
Has all of this landed already or is it slated to land today?

**Comment by johnniwinther** [comment]
CFE support is in the pipeline: https://dart-review.googlesource.com/c/sdk/+/124540

**Comment by leafpetersen** [comment]
This is done.
