### ISSUE TITLE
Provide a quickfix to add / remove method return type which LSP clients could use

### ISSUE THREAD

**Issue by vogella** [dart-lang/sdk#39277]
Would be nice to a have a quickfix which allows to add / remove the return type of a method, e.g.,:

```dart
List<Widget> _createChildren() {
  return [Text("Hello"), Text("Lars"), Text("Testing")];
```

```dart
_createChildren() {
  return [Text("Hello"), Text("Lars"), Text("Testing")];
```

Comsumers would be VS Code and the Eclipse Dartboard project.

**Comment by FMorschel** [comment]
Today the `add` version already exists.

**Comment by scheglov** [comment]
OK, I see now that there was this issue.
But my view on this is still the same.

We almost always want to have types in Dart code.
So, I don't understand why we need this assist.

If we had it, it would show on every method, adding lots of noise.
And I have hard time to imagine why we would want to remove the type.
Even if we had, removing manually it trivial.

**Comment by FMorschel** [comment]
I see two cases where this could be used. As the PR already does, for removing the return type of setters for example. It is an error to have anything other than `void` in these cases. Also, I see it as a helper for when developing new APIs when the return type changes you can simply run both `remove` + `add` (if available) to fix it. Other than that, I also agree this is probably not very useful.

About it adding more noise I'm not sure. I don't usually try to run assists on functions/methods (I don't expect other devs would but maybe I'm wrong), but here is an output:

![image](https://github.com/user-attachments/assets/ff803e9b-4b62-41c6-abdc-791e1001ee7e)

Maybe @vogella has some thoughts about the remove version of this assist?

**Comment by scheglov** [comment]
It looks that there is already a quick fix to remove a setter return type.
<img width="631" alt="image" src="https://github.com/user-attachments/assets/ce53adcc-17b8-4468-9c70-4fd470588dd5">

I still believe that adding not useful actions just adds noise.

**Comment by vogella** [comment]
I agree, having this quickfix seems not valuable. Not sure why I requested this 5 years ago.
