### ISSUE TITLE
dart2native does not support using dart:mirrors

### ISSUE THREAD

**Issue by KOGI** [dart-lang/sdk#39281]
The executables created with bin/dart2native do not support apps/codebases that use or depend on `dart:mirrors` for their normal operation.

**Comment by mraleph** [comment]
This is working as intended at this point (and should be a documented limitation). We disable `dart:mirrors` in AOT builds because it has bad interactions with tree-shaking.

**Comment by KOGI** [comment]
In [the Dart 2.6 announcement](https://medium.com/dartlang/dart2native-a76c815e6baf#7b66) under section "Known Limitations", we are encouraged to express our interest in various improvements by "by adding a “thumbs up” to the issue in our GitHub issue tracker". The first 2 bullets provide respective issues to vote on, but the third bullet (mirror support) does not. I created this ticket with the intention of it being used for this purpose.

**Comment by mraleph** [comment]
@KOGI the reason why there was no issue to vote on is because we have no intent to address this issue, i.e. we do not plan on enabling mirrors in AOT mode.

**Comment by KOGI** [comment]
@mraleph understood. In that case, maybe it shouldn't have been a suggestion/tease in the announcement article, then?
