### ISSUE TITLE
Provide .deb files for ARM64 for Raspberry Pi 4, Windows Subsystem for Linux running on ARM hardware

### ISSUE THREAD

**Issue by kf6gpe** [dart-lang/sdk#39280]
It would be great to see .deb packages for more ARM Linux platforms, specifically the Raspberry Pi 4 and other hosts like ARM64 WSL hosts. Although not a .deb file, languages like Rust provide a one-command-line option to download packages for ARM64.

**Comment by clarkezone** [comment]
+1

**Comment by hmartinez82** [comment]
+1

**Comment by parlough** [comment]
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/26953, as that issue contains more details about the current status of this.
