### ISSUE TITLE
Parser does not accept `!` in cascade sections

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39286]
The following code currently produces a parse error in the analyzer, with NNBD enabled:
```dart
class C {
  D? f() => new D();
  void h() {}
}

class D {
  void g() {}
}

void test(C x) {
  x..f()!.g()..h(); // (1)
}

main() {
  test(new C());
}
```

The errors are on the line marked `// (1)`, and are as follows:
```
  error • Expected to find ';'. • /usr/local/google/home/paulberry/tmp/test.dart:11:8 • expected_token
  error • Expected an identifier. • /usr/local/google/home/paulberry/tmp/test.dart:11:10 • missing_identifier
```
It appears that the parser is not accepting `!` as a possible selector in cascade sections.  I checked with @leafpetersen, and this is definitely intended to work.

**Comment by eernstg** [comment]
Yes, we should have this feature, but it is not covered by the currently specified grammar. Created https://dart-review.googlesource.com/c/sdk/+/124332 and https://github.com/dart-lang/language/pull/673 to fix that.
