### ISSUE TITLE
language_2/regress_29025_test is crashing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#39298]
language_2/regress_29025_test is crashing on some bots since https://dart-review.googlesource.com/c/sdk/+/124331

Bots:
vm-kernel-precomp-ast-linux-debug-x64
app-kernel-linux-debug-x64
vm-kernel-precomp-linux-debug-x64
vm-kernel-precomp-linux-debug-simarm_x64

Example log:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8897350045900213776/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

**Comment by crelier** [comment]
Canonical recursive types are not guaranteed to be unique. A CL is under review.
