### ISSUE TITLE
Catch a Thrown Exception Not Work

### ISSUE THREAD

**Issue by AndyDingDing** [dart-lang/sdk#39290]
Hello there,

It's easier to use async/await with try/catch than the catchError API where it is easier to use it wrongly, but it seems it doesn't work for me. My debugger is still dealing with the exception as if it was un-handled. 

This is the code I write:
```
 try {
      await device.connect(timeout: Duration(seconds: 6), autoConnect: false);
    } catch(e) {
      print("error caught when connectting : $e");
      disconnect(device);
    }
```
And function of connect is from another library, which is write as below:
```
 Future<void> connect({
    Duration timeout,
    bool autoConnect = true,
  }) async {
    var request = protos.ConnectRequest.create()
      ..remoteId = id.toString()
      ..androidAutoConnect = autoConnect;

    Timer timer;
    if (timeout != null) {
      timer = Timer(timeout, () {
        disconnect();
        throw TimeoutException('Failed to connect in time.', timeout);
      });
    }
    return;
  }

```
However, I can't catch TimeoutException that throw by connect. I got Unhandled Exception from the log:
```
E/flutter (19432): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: TimeoutException after 0:00:06.000000: Failed to connect in time.
E/flutter (19432): #0      BluetoothDevice.connect.<anonymous closure> (package:flutter_blue/src/bluetooth_device.dart:33:9)
E/flutter (19432): #1      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (19432): #2      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19432): #3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (19432): #4      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (19432): #5      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (19432): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19432): #7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (19432): #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (19432): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (19432): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (19432): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (19432): 

```
Hope someone can help with the issue.
Thanks in advance,
Andy

**Comment by lrhn** [comment]
The function throwing the `TimeoutException` is simply throwing in an unrelated `Timer` event. There is nothing linking that back to the future returned by the original `connect` call.
The `connect` function is marked `async`, but it doesn't await anything. It simply calls some functions, sets up a timer, then returns a future which completes almost immediately with `null`.  It doesn't wait for the operations it started, and it doesn't return anything depending on what happens later.

For things to work, the function should probably use a `Completer` to carry the error from the timer event to the `connect` return value.
