### ISSUE TITLE
Nested switch statements can produce bogus case_block_not_terminated

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#39304]
The following code:

```dart
int foo() {
  switch (1) {
    case 1:
      switch (1) {
        default: return 1;
      }

    default: return 1;
  }
}
```

Produces this analysis error:

```
  error • The last statement of the 'case' should be 'break', 'continue', 'rethrow', 'return' or 'throw'. • test.dart:3:5 • case_block_not_terminated 
```

This is bogus, because the nested `switch` statement will always terminate, and in fact if I add `return 1;` at the end of `case 1` I get a dead code hint:

```
Analyzing test.dart...
  hint • Dead code. • test.dart:7:7 • dead_code
1 hint found.
```

Note that this *only* reproduces when the outer switch statement has a `default` clause. This code:

```dart
int foo() {
  switch (1) {
    case 1:
      switch (1) {
        default: return 1;
      }
  }
  return 1;
}
```

produces no analysis complaints.

Tested with Dart 2.6.0.

**Comment by nex3** [comment]
It's also worth noting that I've seen this come up in practice in some instances where the outer switch *doesn't* have a `default` clause, but this was the best minimal reproduction I could find.

**Comment by srawlins** [comment]
The example code does not comply with the Dart language spec; each case statement must end in an individual statement like `return`, `break`, etc.

This is bug is another case of https://github.com/dart-lang/sdk/issues/28042; which may be fixed with https://github.com/dart-lang/sdk/issues/26704.

**Comment by srawlins** [comment]
The spec has changed under the null safety type system, to use flow analysis. The motivating example now passes without analysis errors using `dartanalyzer --enable-experiment=non-nullable`. 🎊
