### ISSUE TITLE
Runtime issues with sample "AngularDart Web App" project and SDK 2.6

### ISSUE THREAD

**Issue by tonosama-atlacatl** [dart-lang/sdk#39307]
To see these issues, go to **Intellij**, create a new project then choose **Dart** > **AngularDart Web App** pointing to a freshly download of **SDK 2.6**.

Issues from console after a fresh pub get/upgrade, then webdeb serve:
<img width="1001" alt="Screen Shot 2019-11-08 at 3 04 21 PM" src="https://user-images.githubusercontent.com/10780925/68516553-27106a00-0239-11ea-93bd-54231807447b.png">

- Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"
- Safari Version 13.0.1 (14608.2.11.1.11)
- IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 28, 2019
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
- pubspec.yaml:
```name: TEST_2
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
```

**Comment by joshualitt** [comment]
Closing because AngularDart is now in maintenance mode.
