### ISSUE TITLE
Can the dart file export to dll file?

### ISSUE THREAD

**Issue by biij5698** [dart-lang/sdk#39318]
Can the dart file export dll file like golang?

**Comment by keertip** [comment]
@biij5698 , what are you looking to do? Can you add more details?

**Comment by biij5698** [comment]
I want to export dart to dll and then it can be called by other language, for example Java、Python

**Comment by biij5698** [comment]
.dart file export to .dll file

**Comment by keertip** [comment]
Sorry, dart does not have support to do that. That said, have you looked at [dart-native](https://medium.com/dartlang/dart2native-a76c815e6baf) using which you can create stand alone executables?
