### ISSUE TITLE
can't build trivial angular app on arm

### ISSUE THREAD

**Issue by achatham** [dart-lang/sdk#39312]
I suspect this problem is in the dev compiler but am not totally sure. This is with SDK 2.6.0 on linux, tested via docker/ubuntut on an x86 machine and a raspberry pi 4.

I built the most trivial AngularDart app possible (zero lines of dart): https://github.com/achatham/dart_arm_example and built it via Docker, downloading the SDK as a zip file. The app builds fine on x86 but on arm it fails with:

[SEVERE]build_web_compilers:sdk_js_copy on package:build_web_compilers/$lib$: FileSystemException: Cannot open file, path = '/dart-sdk/lib/dev_compiler/kernel/amd/dart_sdk.js' (OS Error: No such file or directory, errno = 2)

**Comment by vsmenon** [comment]
I'm not sure we ship ARM SDKs with the web tools in them (including `dart_sdk.js` files).  We do not test it.

**Comment by achatham** [comment]
What is the arm sdk for, then? Building flutter or running servers *on* arm?

**Comment by vsmenon** [comment]
Mainly for folks who want to target ARM without cross-compilation.

BTW, the path looks suspicious: '/dart-sdk/lib/dev_compiler/kernel/amd/dart_sdk.js'

Is the Dart SDK really at root?  Is it on the path?

**Comment by achatham** [comment]
In the docker build I end up installing the SDK into /dart-sdk, but it's
just an arbitrary location.

When you say "target ARM", you mean for flutter or server apps? Not for web?

FWIW, my use case is I'm trying to build a web app that I've developed on
an x86 machine and want to deploy to a raspberry pi. But if this isn't
possible, I can cross-compile the webapp.

**Comment by vsmenon** [comment]
> In the docker build I end up installing the SDK into /dart-sdk, but it's
just an arbitrary location.

Ahh, got it.  Does that file (dart_sdk.js) actually exist?

> When you say "target ARM", you mean for flutter or server apps? Not for web?

Sorry, I meant tools that compile to native ARM machine code (i.e., not to JavaScript).

> FWIW, my use case is I'm trying to build a web app that I've developed on
an x86 machine and want to deploy to a raspberry pi. But if this isn't
possible, I can cross-compile the webapp.

Yeah, cross-compile / resulting JS should be fine here. 

I'm not sure whether our web tools themselves build on ARM, or whether we properly deploy everything in ARM versions of the Dart SDK.

**Comment by achatham** [comment]
No, dart_sdk.js is not in the bundle available at
https://storage.googleapis.com/dart-archive/channels/stable/release/2.6.1/sdk/dartsdk-linux-arm-release.zip

**Comment by achatham** [comment]
It's a hack, but I found that it works if I download and extract the x64 SDK, then the arm version on top of it. The missing files aren't architecture-specific.

**Comment by achatham** [comment]
FWIW, I cobbled together an arm webdev SDK and it took >4 hours to compile my webapp, mostly I/O bound from the raspberry pi's SD card. So if anyone finds this bug, I don't recommend this approach :)
