### ISSUE TITLE
Explicit extension invocation allows null-aware member access

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39325]
According to the Static Extension [specification](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#explicit-extension-member-invocation)

> It is a compile-time error if an extension application occurs in a place where it is not the target expression of a simple or composite member invocation. That is, the only valid use of an extension application is to invoke members on it. This is similar to how prefix names can also only be used as member invocation targets. The main difference is that extensions can also declare operators. This also includes null-aware member access like E(o)?.id or E(o)?.[v] because those need to evaluate the target to a value and extension applications cannot evaluate to a value.

In fact, there are no compile-time errors to use null-aware member access on explicit extensions
```dart
class C {
}

extension Ext on C {
  int id() => 42;
}

main() {
  C c = C();
  Ext(c)?.id();
}
```
The code above produces no issues in analyzer and no errors at runtime

dartanalyzer version 2.7.0-dev.0.0
Dart VM version: 2.7.0-dev.0.0 (Tue Nov 5 12:57:33 2019 +0100) on "windows_x64"

**Comment by sgrekhov** [comment]
See also #39326

**Comment by vsmenon** [comment]
@leafpetersen @stereotype441 @johnniwinther - is this a change we need for D27?  Spec / analyzer / CFE / all?

**Comment by vsmenon** [comment]
Also see https://github.com/dart-lang/sdk/issues/39326

**Comment by vsmenon** [comment]
We decided this should not block the D27 release.

**Comment by leafpetersen** [comment]
We've decided to change the spec to allow this, so there is no front end or analyzer work required.
