### ISSUE TITLE
flutter run -d chrome report errors 

### ISSUE THREAD

**Issue by wanjm** [dart-lang/sdk#39327]
flutter run -d chrome report errors 

Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                             
AssetNotFoundException: upime|lib/src/cmd/baseCmd.ddc.js
Error compiling dartdevc module:upime|lib/src/cmd/baseCmd.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/opt/google/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/upime/src/cmd/baseCmd.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/commfunc/http/parameter.ddc.dill=packages/commfunc/http/parameter --summary=packages/commfunc/http/multiPartParameter.ddc.dill=packages/commfunc/http/multiPartParameter --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/commfunc/log.ddc.dill=packages/commfunc/log --summary=packages/json_rpc_2/error_code.ddc.dill=packages/json_rpc_2/error_code --summary=packages/stack_trace/src/chain.ddc.dill=packages/stack_trace/src/chain --summary=packages/async/async.ddc.dill=packages/async/async --summary=packages/stream_channel/stream_channel.ddc.dill=packages/stream_channel/stream_channel --summary=packages/json_rpc_2/json_rpc_2.ddc.dill=packages/json_rpc_2/json_rpc_2 --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=packages/http/http.ddc.dill=packages/http/http --summary=packages/commfunc/http/httpBase.ddc.dill=packages/commfunc/http/httpBase --summary=packages/commfunc/http/http1Client.ddc.dill=packages/commfunc/http/http1Client --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/web_socket_channel/src/copy/bytes_builder.ddc.dill=packages/web_socket_channel/src/copy/bytes_builder --summary=packages/web_socket_channel/html.ddc.dill=packages/web_socket_channel/html --summary=packages/web_socket_channel/io.ddc.dill=packages/web_socket_channel/io --summary=packages/flutter_webrtc/rtc_session_description.ddc.dill=packages/flutter_webrtc/rtc_session_description --summary=packages/agora_rtc_engine/agora_rtc_engine.ddc.dill=packages/agora_rtc_engine/agora_rtc_engine --summary=packages/video_player/video_player.ddc.dill=packages/video_player/video_player --summary=packages/webview_flutter/platform_interface.ddc.dill=packages/webview_flutter/platform_interface --summary=packages/upimedata/drawMode.ddc.dill=packages/upimedata/drawMode --summary=packages/upimedata/meetConfig.ddc.dill=packages/upimedata/meetConfig --summary=packages/upime/typedef.ddc.dill=packages/upime/typedef --summary=packages/flutter_webrtc/rtc_ice_candidate.ddc.dill=packages/flutter_webrtc/rtc_ice_candidate --summary=packages/flutter_webrtc/rtc_stats_report.ddc.dill=packages/flutter_webrtc/rtc_stats_report --summary=packages/flutter_webrtc/media_stream.ddc.dill=packages/flutter_webrtc/media_stream --summary=packages/flutter_webrtc/media_recorder.ddc.dill=packages/flutter_webrtc/media_recorder --summary=packages/flutter_webrtc/rtc_video_view.ddc.dill=packages/flutter_webrtc/rtc_video_view --summary=packages/flutter_webrtc/get_user_media.ddc.dill=packages/flutter_webrtc/get_user_media --summary=packages/flutter_webrtc/rtc_peerconnection_factory.ddc.dill=packages/flutter_webrtc/rtc_peerconnection_factory --summary=packages/flutter_webrtc/webrtc.ddc.dill=packages/flutter_webrtc/webrtc --summary=packages/upimedata/UserInfo.ddc.dill=packages/upimedata/UserInfo --packages=file:///var/folders/tz/ypyk1jvn4sd83nrd5j0y2c4c0000gn/T/kernel_builder_hQ5Y4c/.packages --module-name=packages/upime/src/cmd/baseCmd --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///opt/google/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/tz/ypyk1jvn4sd83nrd5j0y2c4c0000gn/T/ddk_builder_CREuj7/used_inputs.txt package:upime/src/recorder/recorder.dart package:upime/src/recorder/localRecorderSection.dart package:upime/src/cmd/teachingTool.dart package:upime/src/layer/data/line.dart package:upime/src/recorder/drawer/rube.dart package:upime/src/liveMedia/agora/agoraVideoClient.dart package:upime/src/writer/writer.dart package:upime/src/ui/upimeState.dart package:upime/src/cmd/eleType.dart package:upime/src/ui/upimeContext.dart package:upime/src/line/baseLine.dart package:upime/src/layer/basicLayer.dart package:upime/src/liveMedia/agora/agoraView.dart package:upime/src/layer/layerInterface.dart package:upime/src/layer/ppt.dart package:upime/src/recorder/liveRecorderSection.dart package:upime/src/media/upimeTime.dart package:upime/src/layer/smallBoardPage.dart package:upime/src/ui/frameBoard.dart package:upime/src/line/bezier2.dart package:upime/src/layer/pptPage.dart package:upime/src/recorder/data/editAbleElement.dart package:upime/src/ui/container/litLayer/lineCanvas.dart package:upime/src/ui/container/containerBar.dart package:upime/src/ui/container/litLayer/imageLayer.dart package:upime/src/ui/container/litLayer/toolCanvas.dart package:upime/src/layer/data/dupPoint.dart package:upime/src/line/bezier.dart package:upime/src/ui/container/litLayer/contentCanvas.dart package:upime/src/liveMedia/freeswitch/webrtc.dart package:upime/src/cmd/smallBoard/showPage.dart package:upime/src/recorder/activeBorder/basicActiveBorder.dart package:upime/src/cmd/basic.dart package:upime/src/recorder/liveHttpClient.dart package:upime/src/layer/section.dart package:upime/src/writer/liveWriter.dart package:upime/src/recorder/data/line.dart package:upime/src/user/users.dart package:upime/src/layer/data/image.dart package:upime/src/ui/container/baseContainer.dart package:upime/src/layer/pptLayer.dart package:upime/src/layer/pageLayer.dart package:upime/src/recorder/drawer/focusDrawer.dart package:upime/src/ui/container/ppt/pptControlBar.dart package:upime/src/layer/mediaLayer.dart package:upime/src/recorder/recorderSection.dart package:upime/src/liveMedia/liveMedia.dart package:upime/src/layer/multiPageLayer.dart package:upime/src/ui/container/ppt/pptWebView.dart package:upime/src/cmd/cmdConverter.dart package:upime/src/recorder/drawer/line.dart package:upime/src/recorder/activeBorder/rotateActiveBorder.dart package:upime/src/recorder/fileType.dart package:upime/src/layer/LITLayer.dart package:upime/src/liveMedia/freeswitch/verto.dart package:upime/src/recorder/liveRecoder.dart package:upime/src/recorder/data/image.dart package:upime/src/recorder/drawer/toolTriangle.dart package:upime/src/recorder/mask.dart package:upime/src/ui/container/basicLitContainer.dart package:upime/src/cmd/baseCmd.dart package:upime/src/ui/frame.dart package:upime/src/cmd/pinfo.dart package:upime/src/writer/localWriter.dart package:upime/src/layer/cmdLayerType.dart package:upime/src/recorder/upimeLiveClient.dart package:upime/src/cmd/ctrlType.dart package:upime/src/ui/container/positionable.dart package:upime/src/liveMedia/baseLiveMedia.dart package:upime/src/recorder/drawer/toolLine.dart package:upime/src/recorder/activeBorder/pointActiveBorder.dart package:upime/src/liveMedia/agora/agoraClient.dart package:upime/src/liveMedia/agora/headView.dart package:upime/src/recorder/data/resizePoint.dart package:upime/src/ui/video.dart package:upime/src/cmd/smallBoard/syncPage.dart package:upime/src/liveMedia/agora/agora.dart package:upime/src/recorder/drawer/toolRect.dart package:upime/src/ui/upimeScrollController.dart package:upime/src/layer/page.dart package:upime/src/ui/container/smallBoard.dart package:upime/src/layer/data/element.dart package:upime/src/ui/update.dart package:upime/src/recorder/drawer/toolEllipse.dart package:upime/src/ui/container/basicContainer.dart package:upime/src/ui/container/pptContainer.dart package:upime/src/layer/PageTime.dart package:upime/src/layer/opptLayer.dart package:upime/src/user/baseUser.dart package:upime/src/liveMedia/freeswitch/freeswitch.dart package:upime/src/ui/container/LITContainer.dart package:upime/src/ui/container/legacyMediaContainer.dart package:upime/src/cmd/ppt.dart package:upime/src/line/rubeLine.dart package:upime/src/cmd/ctlCmd/cmd.dart package:upime/src/recorder/RecorderController.dart package:upime/src/recorder/drawer/basicDrawer.dart package:upime/src/layer/LITPage.dart package:upime/src/recorder/localRecorder.dart package:upime/src/cmd/dataType.dart package:upime/src/layer/smallBoardLayer.dart package:upime/src/ui/myRenderObjectWidget.dart
    dart --version: 2.7.0 (Fri Nov 8 21:32:48 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xa4 (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3274:32)
#4      AssertStatement.accept (package:kernel/ast.dart:4530:43)
#5      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3073:20)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#8      ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3238:62)
#9      Block.accept (package:kernel/ast.dart:4457:43)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3073:20)
#11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3084:18)
#12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2925:17)
#13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2071:25)
#14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2959:18)
#15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:2921:17)
#16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:2751:18)
#17     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1698:12)
#18     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1640:23)
#19     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:538:21)
#20     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:479:21)
#21     List.forEach (dart:core-patch/growable_array.dart:283:8)
#22     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:425:23)
#23     List.forEach (dart:core-patch/growable_array.dart:283:8)
#24     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:318:15)
#25     _compile (package:dev_compiler/src/kernel/command.dart:377:27)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:44:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#28     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Error compiling dartdevc module:upime|lib/player.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/opt/google/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/upime/player.ddc.js --source-map --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=packages/http/http.ddc.dill=packages/http/http --summary=packages/commfunc/log.ddc.dill=packages/commfunc/log --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/upimedata/meetConfig.ddc.dill=packages/upimedata/meetConfig --summary=packages/upime/typedef.ddc.dill=packages/upime/typedef --summary=packages/commfunc/global/global.ddc.dill=packages/commfunc/global/global --summary=packages/upimedata/UserInfo.ddc.dill=packages/upimedata/UserInfo --summary=packages/flutter_webrtc/rtc_ice_candidate.ddc.dill=packages/flutter_webrtc/rtc_ice_candidate --summary=packages/flutter_webrtc/rtc_stats_report.ddc.dill=packages/flutter_webrtc/rtc_stats_report --summary=packages/flutter_webrtc/rtc_session_description.ddc.dill=packages/flutter_webrtc/rtc_session_description --summary=packages/flutter_webrtc/media_stream.ddc.dill=packages/flutter_webrtc/media_stream --summary=packages/flutter_webrtc/media_recorder.ddc.dill=packages/flutter_webrtc/media_recorder --summary=packages/flutter_webrtc/rtc_video_view.ddc.dill=packages/flutter_webrtc/rtc_video_view --summary=packages/flutter_webrtc/get_user_media.ddc.dill=packages/flutter_webrtc/get_user_media --summary=packages/flutter_webrtc/rtc_peerconnection_factory.ddc.dill=packages/flutter_webrtc/rtc_peerconnection_factory --summary=packages/flutter_webrtc/webrtc.ddc.dill=packages/flutter_webrtc/webrtc --summary=packages/upimedata/drawMode.ddc.dill=packages/upimedata/drawMode --summary=packages/webview_flutter/platform_interface.ddc.dill=packages/webview_flutter/platform_interface --summary=packages/video_player/video_player.ddc.dill=packages/video_player/video_player --summary=packages/agora_rtc_engine/agora_rtc_engine.ddc.dill=packages/agora_rtc_engine/agora_rtc_engine --summary=packages/commfunc/http/parameter.ddc.dill=packages/commfunc/http/parameter --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/web_socket_channel/src/copy/bytes_builder.ddc.dill=packages/web_socket_channel/src/copy/bytes_builder --summary=packages/async/async.ddc.dill=packages/async/async --summary=packages/stream_channel/stream_channel.ddc.dill=packages/stream_channel/stream_channel --summary=packages/web_socket_channel/html.ddc.dill=packages/web_socket_channel/html --summary=packages/web_socket_channel/io.ddc.dill=packages/web_socket_channel/io --summary=packages/commfunc/http/httpBase.ddc.dill=packages/commfunc/http/httpBase --summary=packages/commfunc/http/http1Client.ddc.dill=packages/commfunc/http/http1Client --summary=packages/json_rpc_2/error_code.ddc.dill=packages/json_rpc_2/error_code --summary=packages/stack_trace/src/chain.ddc.dill=packages/stack_trace/src/chain --summary=packages/json_rpc_2/json_rpc_2.ddc.dill=packages/json_rpc_2/json_rpc_2 --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/commfunc/http/multiPartParameter.ddc.dill=packages/commfunc/http/multiPartParameter --summary=packages/upime/src/cmd/baseCmd.ddc.dill=packages/upime/src/cmd/baseCmd --packages=file:///var/folders/tz/ypyk1jvn4sd83nrd5j0y2c4c0000gn/T/kernel_builder_0yPOgw/.packages --module-name=packages/upime/player --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///opt/google/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/tz/ypyk1jvn4sd83nrd5j0y2c4c0000gn/T/ddk_builder_1daCHW/used_inputs.txt package:upime/player.dart package:upime/src/media/player.dart package:upime/src/media/media.dart package:upime/src/controller/controller.dart package:upime/src/fileReader/fileReader.dart package:upime/src/common.dart
    dart --version: 2.7.0 (Fri Nov 8 21:32:48 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xbb (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3274:32)
#4      ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1508:20)
#5      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1381:14)
#6      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1345:19)
#7      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:2969:24)
#8      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1344:15)
#9      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2071:25)
#10     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2959:18)
#11     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1342:16)
#12     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:924:38)
#13     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:537:19)
#14     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:479:21)
#15     List.forEach (dart:core-patch/growable_array.dart:283:8)
#16     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:425:23)
#17     List.forEach (dart:core-patch/growable_array.dart:283:8)
#18     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:318:15)
#19     _compile (package:dev_compiler/src/kernel/command.dart:377:27)
<asynchronous suspension>
#20     compile (package:dev_compiler/src/kernel/command.dart:44:18)
<asynchronous suspension>
#21     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#22     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#28     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Failed after 256ms
Building application for the web...                                 9.9s
Failed to build application for the Web.

**Comment by vsmenon** [comment]
A fix to this landed recently:

https://github.com/dart-lang/sdk/issues/39271
