### ISSUE TITLE
Wrong behaviour for explicit extension invocation in form E(o)?.[v]

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39326]
According to the Static Extension [specification](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#explicit-extension-member-invocation)

> It is a compile-time error if an extension application occurs in a place where it is not the target expression of a simple or composite member invocation. That is, the only valid use of an extension application is to invoke members on it. This is similar to how prefix names can also only be used as member invocation targets. The main difference is that extensions can also declare operators. This also includes null-aware member access like E(o)?.id or E(o)?.[v] because those need to evaluate the target to a value and extension applications cannot evaluate to a value.

In fact, 
```dart
class C {
}

extension Ext on C {
  int operator [](int index) => index;
}

main() {
  C c = C();
  Ext(c)?.[42];
}
```
No error at runtime. In analyzer
```
dartanalyzer --enable-experiment=extension-methods explicit_extension_member_invocation_A20_t04.dart
Analyzing explicit_extension_member_invocation_A20_t04.dart...
  error - The getter '[' isn't defined for the extension 'Ext'. - explicit_extension_member_invocation_A20_t04.dart:32:11 - undefined_extension_getter
  error - Expected an identifier. - explicit_extension_member_invocation_A20_t04.dart:32:11 - missing_identifier
2 errors found.
```
These error messages are wrong. See also #39325

dartanalyzer version 2.7.0-dev.0.0
Dart VM version: 2.7.0-dev.0.0 (Tue Nov 5 12:57:33 2019 +0100) on "windows_x64"

**Comment by lrhn** [comment]
The syntax `?.` is not available in current Dart. It's expected to be introduced with NNBD. 
It does look like a (conditional) member invocation, so it could be allowed, but it likely won't.

When NNBD happens, extension `on` types will be either nullable or not, so there won't be a need for a null-aware extension member invocation. The extension application itself won't be considered nullable, so it won't allow a `?.`.

**Comment by sgrekhov** [comment]
With non-nullable experimental flag there are no any errors in analyzer. But there must be according to the spec

**Comment by vsmenon** [comment]
We don't think this a blocker - this should only be an issue if nnbd is enabled, right?

**Comment by johnniwinther** [comment]
Right.

**Comment by johnniwinther** [comment]
Null aware access is now allowed. No work required for the CFE.
