### ISSUE TITLE
UnimplementedError: name is an instance of _OperatorName in endClassConstructor

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#39338]
I'm seeing the exception below:

```
UnimplementedError: name is an instance of _OperatorName in endClassConstructor
    Driver._captureExceptions(), package:analysis_server/src/server/driver.dart:717
    _CustomZone.handleUncaughtError(), dart:async/zone.dart:1003
    _CustomZone.runGuarded(), dart:async/zone.dart:925
    _CustomZone.bindCallbackGuarded(), dart:async/zone.dart:963
    _microtaskLoop(), dart:async/schedule_microtask.dart:41
    _startMicrotaskLoop(), dart:async/schedule_microtask.dart:50
    _Timer._runTimers(), dart:isolate-patch/timer_impl.dart:391
    _Timer._handleMessage(), dart:isolate-patch/timer_impl.dart:416
    _RawReceivePortImpl._handleMessage(), dart:isolate-patch/isolate_patch.dart:172
```

I don't have the source that's causing this issue, but I believe the source of the UnimplementedError is here: https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/fasta/ast_builder.dart#L885.

**Comment by devoncarew** [comment]
cc @bwilkerson who added this diagnostic in https://github.com/dart-lang/sdk/commit/4f309f04e771cf06184e4329d1073a7eaccb9b8e

**Comment by bwilkerson** [comment]
Actually, I believe that would be coming from https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/fasta/ast_builder.dart#L697.

Are you running from head, or from an earlier build? I ask because I thought this had already been fixed.

**Comment by devoncarew** [comment]
> Actually, I believe that would be coming from...

Ah, yup.

These are from user reported crashes in the last 7 days. I'm not sure what version it's from, but suspect that it's at least a recent dev build.

**Comment by devoncarew** [comment]
likely addressed in https://dart-review.googlesource.com/c/sdk/+/124121
