### ISSUE TITLE
compile bug

### ISSUE THREAD

**Issue by lyf571321556** [dart-lang/sdk#39341]
MacBook-Pro-2:~ admin$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.17-pre.59, on Mac OS X 10.13.6 17G8037,
    locale zh-Hans-CN)
    • Flutter version 1.10.17-pre.59 at /Users/admin/Library/flutter
    • Framework revision 9e0df259df (11 hours ago), 2019-11-11 15:56:43 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

MacBook-Pro:ones_ai_flutter admin$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
                                                                        
AssetNotFoundException: flutter_easyrefresh|lib/src/footer/load_indicator.ddc.js
Error compiling dartdevc module:flutter_easyrefresh|lib/bezier_bounce_footer.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/admin/Library/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd
    --no-summarize -o packages/flutter_easyrefresh/bezier_bounce_footer.ddc.js --source-map
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter_easyrefresh/src/footer/load_indicator.ddc.dill=packages/flutter_easyrefresh/src/footer/load_indicator
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --summary=packages/flutter_easyrefresh/easy_refresh.ddc.dill=packages/flutter_easyrefresh/easy_refresh
    --packages=file:///var/folders/pz/1x2346q96n77sb03s_3qvrlc0000gn/T/kernel_builder_mBC3Wm/.packages
    --module-name=packages/flutter_easyrefresh/bezier_bounce_footer --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=file:///Users/admin/Library/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/pz/1x2346q96n77sb03s_3qvrlc0000gn/T/ddk_builder_BgylIG/used_inputs.txt
    package:flutter_easyrefresh/bezier_bounce_footer.dart
    dart --version: 2.7.0 (Wed Nov 6 22:44:33 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xb4 (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3272:32)
#4      AssertStatement.accept (package:kernel/ast.dart:4524:43)
#5      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3072:20)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#8      ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3236:62)
#9      Block.accept (package:kernel/ast.dart:4451:43)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3072:20)
#11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3083:18)
#12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2924:17)
#13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2070:25)
#14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2958:18)
#15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:2920:17)
#16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:2750:18)
#17     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1697:12)
#18     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1639:23)
#19     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:538:21)
#20     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:479:21)
#21     List.forEach (dart:core-patch/growable_array.dart:283:8)
#22     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:425:23)
#23     List.forEach (dart:core-patch/growable_array.dart:283:8)
#24     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:318:15)
#25     _compile (package:dev_compiler/src/kernel/command.dart:377:27)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:44:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#28     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

                                                                        
Error compiling dartdevc module:flutter_easyrefresh|lib/src/footer/load_indicator.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/admin/Library/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd
    --no-summarize -o packages/flutter_easyrefresh/src/footer/load_indicator.ddc.js --source-map
    --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --packages=file:///var/folders/pz/1x2346q96n77sb03s_3qvrlc0000gn/T/kernel_builder_yHg4DG/.packages
    --module-name=packages/flutter_easyrefresh/src/footer/load_indicator --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=file:///Users/admin/Library/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/pz/1x2346q96n77sb03s_3qvrlc0000gn/T/ddk_builder_k2bNjt/used_inputs.txt
    package:flutter_easyrefresh/src/widget/empty_widget.dart package:flutter_easyrefresh/src/header/refresh_indicator.dart
    package:flutter_easyrefresh/src/physics/scroll_physics.dart package:flutter_easyrefresh/src/listener/scroll_notification_listener.dart
    package:flutter_easyrefresh/src/listener/scroll_notification_interceptor.dart package:flutter_easyrefresh/src/footer/load_indicator.dart
    dart --version: 2.7.0 (Wed Nov 6 22:44:33 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xaf (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3272:32)
#4      AssertStatement.accept (package:kernel/ast.dart:4524:43)
#5      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3072:20)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#8      ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3236:62)
#9      Block.accept (package:kernel/ast.dart:4451:43)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3072:20)
#11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3083:18)
#12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2924:17)
#13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2070:25)
#14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2958:18)
#15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:2920:17)
#16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:2750:18)
#17     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1697:12)
#18     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1639:23)
#19     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:538:21)
#20     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:479:21)
#21     List.forEach (dart:core-patch/growable_array.dart:283:8)
#22     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:425:23)
#23     List.forEach (dart:core-patch/growable_array.dart:283:8)
#24     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:318:15)
#25     _compile (package:dev_compiler/src/kernel/command.dart:377:27)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:44:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#28     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

                                                                        
Failed after 344ms

**Comment by vsmenon** [comment]
A fix to this landed recently:

https://github.com/dart-lang/sdk/issues/39271
