### ISSUE TITLE
Add @strictPrivate annotation

### ISSUE THREAD

**Issue by cubuspl42** [dart-lang/sdk#39348]
Proposed specification:

> Used to annotate an instance member (method, getter, setter, operator, or field) m in a class C. If the annotation is on a field it applies to the getter, and setter if appropriate, that are induced by the field. **Indicates that m should only be invoked from instance methods of C.**
> 
> Tools, such as the analyzer, can provide feedback if
> 
> - the annotation is associated with anything other than an instance member, or
> - an invocation of a member that has this annotation is used outside of an instance member **defined on a class in which the protected member is defined**.

Rationale: programming languages have had support for `private` visibility modifier since the early days of OOP. Dart decided not to include it in the language (for simplicity sake, I assume?). Such modifier is very useful, because most non-public methods are indeed only called class-internally. They can hold the most sensitive invariants.

I assume that such feature has very low chances of being integrated into the language itself, so I propose an annotation that would solve that problem outside of the compiler.

This annotation was previously described here: https://github.com/dart-lang/linter/issues/254

Name of the annotation is up for debate.

**Comment by munificent** [comment]
Dart already has private visibility. Identifiers that start with an underscore are visible only to the library where the identifier is declared. Dart doesn't have a private *keyword*, but it still has full support for privacy, just like Go which also lacks a private keyword.

**Comment by cubuspl42** [comment]
@munificent You misunderstood this annotation. This issue is about an annotation for class-private visiblity (what all other languages call _private_), not library-private (what Dart calls _private_).

**Comment by munificent** [comment]
I don't think there's that much benefit to adding another level of privacy for individual classes. If you want class privacy, it's trivial to move the class to its own library.

> Dart decided not to include it in the language (for simplicity sake, I assume?).

Dart has declarations that live outside of classes, so class privacy wouldn't be sufficient. Library privacy subsumes both top level declarations and classes.

**Comment by cubuspl42** [comment]
There is benefit.

Library-private visibility is a powerful tool, a lot like Java package-private, C#/Kotlin `internal`, or even (yes, really) C++ `friend`. When you're writing a library in any of these languages (library understood as a unit of code that has  a stable programming interface), these tools allow you to have an internal layer of communication, non-accessible by your clients, which is respected by a compiler and (depending on technology) a virtual machine. In other words, these tools can make your objects internally interconnected.

Coming back to Dart, specifically. The only way of having module-private interconnections is having all elements in a single library (which equals to a single file, unless you want to play with `part`, which is a fancy `#include`). Once the library has a dozen classes or more (the number is forced by the shape of your module's public API and the functionality expected, not something that depends on your mood), the classes start to become "naked" from each other's perspective. They need, let's say, 10% of their interface to be module-internal, but they see _everything_. Access to some of these very private symbols can require from you being aware of some non-obvious internal preconditions and invariants.

Example of a non-trivial library:
[flutter/lib/src/widgets/framework.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart)
5321 lines, 38 classes
