### ISSUE TITLE
Migration engine should stop hardcoding permissiveMode=true

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39353]
The migration engine currently has a "permissive mode" which makes it try to keep going if it encounters any exceptions during migration.  This is helpful in allowing us to test out early versions of the migration engine while it is still being implemented, but it has the danger of misleading users into thinking they have a high quality migration when they don't.

Before shipping the migration engine we should either turn off permissive mode or find a way to reassure ourselves that the migrations produced by the tool are very close to accurate even if an exception occurs.

**Comment by MichaelRFairhurst** [comment]
Per @stereotype441 , this no longer fits what we've seen in practice.
