### ISSUE TITLE
How to define a type like size_t??

### ISSUE THREAD

**Issue by X-Liang** [dart-lang/sdk#39372]
JavaScriptCore has a API is `JSStringGetLength` it need a JSStringRef and return a `size_t` type value.

**size_t** : if the compiler is 32 bit then it is simply a typedef(i.e., alias) for **unsigned int** but if the compiler is 64 bit then it would be a typedef for **unsigned long long**. The size_t data type is never negative.

dart.ffi has ffi.Uint32, ffi.Uint64, witch type should I use to map size_t?  If I use ffi.Uint64 it has a out of bound problem is 32bit machine. I think this problem because in 32bit matchine C API return a 32bit size value, but ffi.Pointer<UInt64> it will find UInt64 size value. If I use Uint32 in 64bit matchine when the return value is so large may be out of bound.
**How to define a type in 32bit matchine is Uint32 and 64bit is Uint64 like size_t??**

**Comment by ds84182** [comment]
You can use ffi.IntPtr for this. However, I think it gets sign extended on both 32-bit and 64-bit machines.

**Comment by X-Liang** [comment]
I find some package is use Int32 like this: [tflite_native](https://github.com/dart-lang/tflite_native/blob/9539cdd56d132614cd774fb8dbf6d8fe8c63cfb9/lib/src/bindings/tensor.dart), method: `TfLiteTensorByteSize`
and some package is use IntPtr like this: [malloc](https://github.com/dart-lang/ffi/blob/master/lib/src/allocation.dart), `malloc` : `void* malloc(size_t __byte_count)`
I want know what different of them??  Thanks😁

**Comment by ds84182** [comment]
@X-Liang The TFLite one seems like a bug. It should be IntPtr, otherwise if the size is greater than 2gb the return result will be incorrect.

**Comment by dcharkes** [comment]
It's not possible to define your own native type that way.

We keep track of a list of requested types here: https://github.com/dart-lang/sdk/issues/36140. Though, we can only add those types if they are well-defined across a range of compilers/platforms.

**Comment by dcharkes** [comment]
I've filed an issue for implementing a generic solution for this https://github.com/dart-lang/sdk/issues/42563.
