### ISSUE TITLE
Extension methods for prefix operators may not be correctly resolved

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39371]
Consider the following program:

```dart
extension E1 on Function {
  operator -() => this;
  operator ~() => this;
}

void main() {
  ~- (() => 1);
}
```

This program should compile without errors and is accepted by the analyzer, but `dart` from commit 082c10aab7ce80c7f11b007fb45357ade9776f84 (rather fresh, from today Nov 13th) incurs a dynamic error reported as follows:

```
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function '~'
Receiver: Closure: () => int
Tried calling: ~()
Found: ~() => int
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (file:///usr/local/google/home/eernst/lang/dart/scratch/201911/n026.dart:7:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

A similar problem occurs if the operators occur in the opposite order, or if we use `~~` (`--` has a different meaning so we can't use that).

It is not important that the extension is on a function type or `Function`, the same issue arises when it is on a regular class.

It occurs when more than one `<prefixOperator>` occurs together, and when they are resolved to extension method invocations. For instance, there is no problem with this:

```dart
class A {
  operator ~() => this;
  operator -() => this;
}

void main() {
  print(~-~A());
}
```

**Comment by ds84182** [comment]
Isn't this because the return type of the operators aren't defined, so it defaults to dynamic?

**Comment by eernstg** [comment]
You're right! So there is no problem. Closing.
And thanks for spotting that! ;-)
