### ISSUE TITLE
Migration should infer that a named parameter is required when there are no contradictory use sites

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39376]
Consider the following code:
```dart
void _f(bool b, {int x}) {
  if (b) {
    print(x + 1);
  }
}
main() {
  _f(true, x: 1);
}
```
This currently gets migrated to:
```dart
void _f(bool b, {int? x}) {
  if (b) {
    print(x! + 1);
  }
}
main() {
  _f(true, x: 1);
}
```
The rationale is that since `x` is a named parameter that lacks an `@required` annotation, there might be a call site that doesn't pass in a value for it, therefore we must allow for the possibility that it might be null.

But this is silly, since `_f` is a private function and we can see that all of its call sites pass in a non-null value for `x`.  A better migration would be:
```dart
void _f(bool b, {required int x}) {
  if (b) {
    print(x + 1);
  }
}
main() {
  _f(true, x: 1);
}
```

**Comment by stereotype441** [comment]
When we work on this, we should also think about the case where the argument is unconditionally used, but there is a call site that doesn't pass it in, e.g.:
```dart
void _f({int x}) {
  print(x + 1);
}
main() {
  _f();
}
```
Obviously such a program is broken; the question is, how should we migrate it?

Currently migration produces:
```dart
void _f({required int x}) {
  print(x + 1);
}
main() {
  _f();
}
```
Which will produce a compile-time error at the site of the call to _f.  IMHO that's pretty reasonable behavior.  When this issue is fixed we should make sure it doesn't regress.

**Comment by stereotype441** [comment]
@bwilkerson points out that this is a common case in Flutter, e.g.:

```dart
class MyWidget extends StatefulWidget {
  MyWidget({Key key, this.foo}): super(key: key);
  final Foo foo;
}
```
It might often occur that all calls to the constructor provide a value for `foo`.

**Comment by srawlins** [comment]
The migrator still migrates to `int? x`.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
