### ISSUE TITLE
Migration should not produce illegal overrides

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39378]
https://dart-review.googlesource.com/c/sdk/+/125084 allows the migration engine to understand that even though `dynamic` is nullable, some instances of `dynamic` in the user's source code may wind up never taking on null values.  This creates a problem when one of these "never null dynamic" types appears in an inheritance relation, e.g.:

```dart
class _A {
  void _m(p) {
    f(p);
  }
}
class _B extends _A {
  void _m(Object q) {
    g(q);
  }
}
void f(Object r) {}
void g(Object s) {}
```
Currently the migration tool reasons that since there are no call sites that pass in nullable values, the value of `p` is never going to be null.  Therefore there's no need to mark `f`'s parameter `r` as nullable.  This is a good thing, because it prevents unnecessary propagation of nulls.  But the migration engine is applying the same logic to the type of `q`, failing to mark it as non-nullable, and that's a compile-time error.

Note that it is tempting to fix this bug by having the nullability graph propagate nullability to `q`, but I believe that would be a bad solution, because it would then in turn get propagated unnecessarily to `s`.  I believe what we should do instead is to keep the existing nullability graph computations (so that nullability is *not* propagated to `s`), however before final output, we should determine if any additional `?`s need to be added in order to satisfy inheritance constraints, and if so we should add them without performing additional propagation.

**Comment by eernstg** [comment]
This sounds like we might want to help developers who are using the migration engine to avoid some of these trade-offs. If we establish some channels of communication (say, a comment in the migrated code, or a diagnostic message) then it could allow developers to modify their code to express their intent more clearly, and re-run the migration, with a more useful result.

For instance, if parameter `Object q` gets migrated into `Object? q`, and the reason for this is one of these known dilemma situations then it could instead be

```dart
class _B extends _A {
  /* NNBD migration of `q`: `?` forced by parameter type `dynamic` in _A */ 
  void _m(Object? q) {
    g(q);
  }
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
