### ISSUE TITLE
No parse error but invalid AST on constructor with type parameter

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39389]
If you throw this at dartfmt:

```dart
class MyFoo<F> {
  MyFoo<F>(this.foo);
}
```

It incorrectly tries to format it to:

```dart
class MyFoo<F> {
  MyFoo(this.foo);
}
```

The input code has a compile-time error. Constructors cannot have type parameters. If the parser had reported an error, then the formatter would not try to format it. Or, if the parser had allowed the wrong code but given the formatter an AST that let it reconstitute the original code, that would work too. But right now, it's just silently giving an incomplete AST.

Given that `ConstructorDeclaration` doesn't (and probably *shouldn't*) have a type parameters field, the easiest fix is probably to report this as an error.

**Comment by bwilkerson** [comment]
@jensjoha Interested in hearing your thoughts.

**Comment by jensjoha** [comment]
The parser parses it without error --- it (technically) hasn't made any decision about it being a constructor yet when it parses the type parameter. The listener is notified correctly though:

```
        beginMember()
          beginMethod(null, null, null, null, null, MyFoo)
            handleNoType({)
            handleIdentifier(MyFoo, methodDeclaration)
            beginTypeVariables(<)
              beginMetadataStar(F)
              endMetadataStar(0)
              handleIdentifier(F, typeVariableDeclaration)
              beginTypeVariable(F)
                handleTypeVariablesDefined(F, 1)
                handleNoType(F)
              endTypeVariable(>, 0, null, null)
            endTypeVariables(<, >)
            beginFormalParameters((, MemberKind.NonStaticMethod)
              beginMetadataStar(this)
              endMetadataStar(0)
              beginFormalParameter(this, MemberKind.NonStaticMethod, null, null, null)
                handleNoType(()
                handleIdentifier(foo, fieldInitializer)
                handleFormalParameterWithoutValue())
              endFormalParameter(this, ., foo, null, null, FormalParameterKind.mandatory, MemberKind.NonStaticMethod)
            endFormalParameters(1, (, ), MemberKind.NonStaticMethod)
            handleNoInitializers()
            handleAsyncModifier(null, null)
            handleEmptyFunctionBody(;)
          endClassConstructor(null, MyFoo, (, null, ;)
        endMember()
```

and analyzer also gives an error:
```
Constructors can't have type parameters.
Try removing the type parameters.
```

How this is handled on the analyzer side (and passed on) I don't know.

**Comment by bwilkerson** [comment]
Thanks for looking at this. Analyzer reports this as `CompileTimeErrorCode.TYPE_PARAMETER_ON_CONSTRUCTOR`, which is translated from the front end message code `messageConstructorWithTypeParameters`. It's reported by the `AstBuilder` in `endClassConstructor` on line 703 and in `endClassFactoryMethod` on line 782.

@munificent I'm guessing that the reason the formatter doesn't see it is because it's a `CompileTimeErrorCode` rather than a `ParserErrorCode`. The right fix is probably to make it a `ParserErrorCode`.

**Comment by munificent** [comment]
> @munificent I'm guessing that the reason the formatter doesn't see it is because it's a `CompileTimeErrorCode` rather than a `ParserErrorCode`. The right fix is probably to make it a `ParserErrorCode`.

That sounds right to me. Do you intend to do that, or should I find a different workaround?

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/125621

**Comment by munificent** [comment]
Thank you!
