### ISSUE TITLE
Migration engine does not support extensions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39387]
The migration engine needs to support extensions.  This entails several things:
- Support for extension declaration syntax
- Creating the proper graph edges to determine whether the type mentioned in an extension declaration's "on" clause should be made nullable
- Understanding that inside an extension declaration, if the type mentioned in an extension declaration's "on" clause is nullable, then `this` should be considered nullable
- Understanding that if the type mentioned in an extension declarations's "on" clause is nullable, then a use of the extension does not need to be null checked
- Support for explicit extension instantiation syntax

**Comment by srawlins** [comment]
Some support has been added, but there is now at least one crash:

```dart
class C<T> {}
void f(C<List> x) {}
extension E on C<List> {
  g() => f(this);
}
```

(In edge_builder's _thisOrSuper, `DecoratedType()` is called for type arguments which themselves have type arguments.)

Additionally the case of extending Function is not handled:

```dart
extension CurryFunction<R, S, T> on R Function(S, T) {
  /// Curry a binary function with its first argument.
  R Function(T) curry(S first) => (T second) => this(first, second);
}
```

I am checking in two failing tests.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
