### ISSUE TITLE
Extension methods inside factory methods behave inconsistently across analyzer and CFE

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#39394]
Consider `main.dart`:
```dart
main() {
  Foo.withBaz().baz();
}

class Foo {
  Foo();

  factory Foo.withBaz() {
    baz();
    return Foo();
  }
}

extension AddBaz on Foo {
  baz() {
    print('Baz');
  }
}
```

Analyze and run:
```console
$ dartanalyzer repro.dart
Analyzing repro.dart...
No issues found!
| ~/dev/playground/dart/json/jsonserilizable_ext @ mit-macbookpro3 (mit)
$ dart repro.dart
repro.dart:10:5: Error: Method not found: 'baz'.
    baz();
    ^^^
| ~/dev/playground/dart/json/jsonserilizable_ext @ mit-macbookpro3 (mit)
$
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
The front-end is correct and the analyzer is missing an error.

The `baz()` invocation in the `Foo.withBaz()` factory constructor is invalid.

There is no `baz` declaration in scope, and there is no `this` in scope, so it's simply an error.
It's the same behavior as if the `baz()` occurred in a static method.

If the `baz()` had occurred in a generative constructor or instance method, there would be a `this` and the `baz()` would be equivalent to `this.baz()` which would be a valid implicit extension application.

**Comment by srawlins** [comment]
Analyzer now reports an error:

> Instance members can't be accessed from a factory constructor.
