### ISSUE TITLE
Consider making the migration engine smarter about detecting and deleting unreachable code

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39399]
This came up during a trial migration fo the logger package.  The following code:
```dart
  Level get level {
    if (_level != null) return _level;
    if (parent != null) return parent.level;
    return _rootLevel;
  }
```
Is currently getting migrated to:
```dart
  Level? get level {
    if (_level != null) return _level;
    /* if (parent != null) */ return parent.level;
    return _rootLevel;
  }
```
Note that this is an incorrect migration, because `parent` should be nullable.  But if `parent` were meant to be non-nullable, there would be another issue: the migration engine is leaving behind the dead code `return _rootLevel;`.

It would be nice if the migration tool could detect cases where the elimination of a dead "if" causes the code below it to become unreachable, and either remove the unreachable code or otherwise alert the user that it's become unreachable.

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/38638

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
