### ISSUE TITLE
No clear distinction between num.toInt() and num.truncate()

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#39400]
The documentation for [`num.truncate`](https://api.dartlang.org/stable/2.6.1/dart-core/num/truncate.html) and for [`num.toInt`](https://api.dartlang.org/stable/2.6.1/dart-core/num/toInt.html) does not make it clear what (if any) distinction there is between them.

Even more confusingly, `num.truncate` explicitly states that it will throw `UnsupportedError` for unrepresentable values whereas `num.toInt` doesn't, implying that `num.toInt` somehow would not throw. (It does throw.)

Additionally, the `num.toInt` documentation uses the term "truncate", further conflating them.

* If there is no difference between the two, the documentation for, say, `num.toInt` should simply be something like "An alias to [truncate]."
* If there is a difference between the two, it should be described.

I see that `double` overrides `num.truncate` but inherits `num.toInt`, but the `double.truncate` documentation doesn't provide any clarification either.

(I also think that it would be clearer if `num.truncate` explicitly stated that it rounds-to-zero.)

**Comment by jamesderlin** [comment]
The [`num.operator ~/`](https://api.dartlang.org/stable/2.6.1/dart-core/num/operator_truncate_divide.html) documentation states:

> If either operand is a `double` then the result of the truncating division `a ~/ b` is equivalent to `(a / b).truncate().toInt()`.

So now I'm really confused, because why would both `.truncate()` and `.toInt()` be necessary in the equivalent expression?

(Again, I also feel like this would be clearer if it explicitly stated that it returned the quotient rounded-to-zero.)

**Comment by kevmoo** [comment]
@lrhn @munificent

**Comment by lrhn** [comment]
I agree that both operations do the same thing: Round towards zero and return the result as an `int`, throw for non-finite values. Both are defined on `num`, so there is no difference at all, except that they are named for different use cases: rounding vs type-conversion.

There is a corresponding rounding function, `truncateToDouble`, which rounds towards zero, but then converts to `double`. 
There is a corresponding type-conversion function, `toDouble`, which converts any integer to `double` and does nothing to `double`s.

**Comment by jamesderlin** [comment]
It looks like this got fixed at some point. The documentation for `num.toInt` now explicitly states that it is equivalent to `truncate`, the documentation for `truncate` explicitly states that it rounds fractional values toward zero, and the documentation for `floor` explicitly states that it rounds toward negative infinity.
