### ISSUE TITLE
Inference failure on nested list containing null

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39407]
I'm migrating some tests to NNBD and I ran into this simplified example:

```dart
main() {
  var stuff = [[1], null];
}
```

If I analyze that with:

```
dartanalyzer --enable-experiment=non-nullable temp.dart
```

I get:

```
Analyzing temp.dart...
  error • Couldn't infer type parameter 'E'.

Tried to infer 'List<int>' for 'E' which doesn't work:
  Parameter 'element' declared as     'E'
                      but argument is 'Null'.
The type 'List<int>' was inferred from:
  Parameter 'element' declared as     'E'
                      but argument is 'List<int>'.

Consider passing explicit type argument(s) to the generic.

 • temp.dart:2:15 • could_not_infer
  error • The element type 'Null' can't be assigned to the list type 'List<int>'. • temp.dart:2:21 • list_element_type_not_assignable
  hint • The value of the local variable 'stuff' isn't used. • temp.dart:2:7 • unused_local_variable
2 errors and 1 hint found.
```

@leafpetersen, is that the expected behavior? My intuition is that the outer list and thus `stuff` would be inferred to have type `List<List<int>?>`.

**Comment by leafpetersen** [comment]
Yes, that's what I would expect.  I think the updated NNBD least upper bound is just in the process of being implemented now though. @scheglov has a CL out that starts on this, I believe.

**Comment by scheglov** [comment]
Yes, the change to implement LUB using NNBD rules fixed this.
I will add a [few](https://dart-review.googlesource.com/c/sdk/+/125991) unit tests to cover it.

**Comment by munificent** [comment]
Can we close this now?

**Comment by scheglov** [comment]
Yes, the test landed, so we can close it.
