### ISSUE TITLE
Migration needs to add explicit types when the inferred type has the wrong nullability

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39404]
Consider the following code:
```dart
var x = 1;
x = null;
```
The type of `x` needs to be made nullable in order for `x = null` to succeed.  But since the type is inferred from the initializer, we need to replace `var` with `int?`.

**Comment by srawlins** [comment]
This is done as of 0ca9e85, correct?

**Comment by stereotype441** [comment]
> This is done as of [0ca9e85](https://github.com/dart-lang/sdk/commit/0ca9e8522e21ce730b0edade5021fd06c55e1697), correct?

You're right, thanks!  The CL says it only "partially addresses" the issue, but I can't find any notes to myself of any work remaining to do, so either I have already finished the follow-up work, or it hasn't been critical enough to notice.  Either way I think it's reasonable to close this issue.
