### ISSUE TITLE
dart:ffi call the C function which is statically linking framework

### ISSUE THREAD

**Issue by linyu92** [dart-lang/sdk#39415]
Env:
* Flutter Version （'Flutter 1.12.2'）
* Dart SDK Version (`Dart 2.7.0`)
* MacOSX
* iOS

As far as I know, dart:ffi uses dlsym to get function pointer with function name, but only adapt to methods in dynamic library. Can you provide a way to register or otherwise, so that statically linked methods can also be called by dart

**Comment by mit-mit** [comment]
cc @dcharkes

**Comment by dcharkes** [comment]
Use `DynamicLibrary.process()`.

https://api.dartlang.org/stable/2.6.1/dart-ffi/DynamicLibrary/DynamicLibrary.process.html

**Comment by linyu92** [comment]
I had try  DynamicLibrary.process() before.However, it seems  that dlsym can not find the symbol  which is statically linking.May be a register is needed. Or can show me the code how to
achieve it. 3Q!

**Comment by dcharkes** [comment]
The full documentation is [here on flutter.dev](https://flutter.dev/docs/development/platform-integration/c-interop). Please let me know if that works for you.
