### ISSUE TITLE
Add UBSAN (undefined behavior sanitizer) bot to our CI

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39427]
@alexmarkov pointed out some UB in a recent code review.

If we want to make our codebase clean of UB code, we should consider adding a UBSAN bot to our CI, similar to existing ASAN.

/cc @a-siva @mraleph

**Comment by rmacnak-google** [comment]
Related: 3678a3bd42b9254b47dd8abda41ef1d4ff1a1390

**Comment by rmacnak-google** [comment]
Related: 6fe15f6df93150b377c306d15b1173454fda48c2

**Comment by rmacnak-google** [comment]
Related: 60493d58fbc5648ef252110ebdf3798138440f92
