### ISSUE TITLE
Unused imports hint misses an unused import

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#39434]
Missing verification in unused imports hint:

if some file is imported using 2 different URIs, the second one should be flagged as unused.  Example:  in the analyzer `workspace.dart` file, include

```
import 'package:analyzer/src/workspace/bazel.dart';
import 'bazel.dart';
```

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/24073

**Comment by srawlins** [comment]
Oops, this is actually more a duplicate of https://github.com/dart-lang/sdk/issues/23788 or https://github.com/dart-lang/sdk/issues/32601; @lrhn 's explanation [here](https://github.com/dart-lang/sdk/issues/23788#issuecomment-118842122) is a good explanation:

> That is the expected behavior. A library is identified by the URI used to point to it (after resolution and nomalization). If you use two different URIs to import what ends up being the same file, it's still treated as two different libraries...
