### ISSUE TITLE
DateTime instance timezone is incorrectly modified when system changes timezone

### ISSUE THREAD

**Issue by BobEvans** [dart-lang/sdk#39436]
* Dart core libraries ("dart:async", "dart:io", etc.)
DateTime class

* Dart SDK Version (`dart --version`)
Any

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS

A DateTime instance does not maintain its timezone value and updates the timezone when the system timezone changes, thus it modifies the time originally recorded.

Reproduction:

```dart
import 'dart:convert';
import 'dart:io';


void main() {

    DateTime n = DateTime.now();
    var hour = n.hour;
    var tos = n.toString();
    print(tos);
    var timeZoneName = n.toLocal().timeZoneName;
    print("timezone name: $timeZoneName");
    var timeZoneOffset = n.toLocal().timeZoneOffset;
    print("Timezone offset: $timeZoneOffset");

    //user to go change system timezone
    print("hit return after changing timezone");
    stdin.readLineSync(encoding: Encoding.getByName('utf-8'));

    print("Time instance after change: ${n.toString()}");
    var timeZoneEquality = timeZoneOffset == n.timeZoneOffset;
    print("Timezone should have stayed the same on existing instance of DateTime. Same?: "
        ": $timeZoneEquality");
    print("Actual: ${n.timeZoneOffset}");


    var hourEquality = n.hour == hour;
    print("Hour should have stayed the same because timezone should not have changed. Equal? : $hourEquality");
    // at worst, the above line should have changed the hour since it is shifting the timezone
  // but really, an instance should not have its timezone adjusted when the system time changes.
    
}
```

**Comment by BobEvans** [comment]
This is particularly important for Flutter where it is running on mobile devices because many phones change timezones as a regular occurrence.

**Comment by lrhn** [comment]
Dart `DateTime` object do not contain a timezone.
They exist only as one of two kinds: UTC or *local*. 

What "local" means depends on the current run-time environment. If you change the time zone of the run-time, then the interpretation of all local `DateTime` objects also change. This is, effectively, behaving as expected.

You need a proper time-zone based time representation to avoid that, but Dart's `DateTime` is not that. It is, like JavaScript `Date` objects, a simple timestamp with a little calendar deconstruction on top.
