### ISSUE TITLE
[vm/aot] Remove unnecessary MonomorphicCheckedEntries

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39446]
Currently we emit a `MonomorphicCheckedEntry` for all "dynamic" functions:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/object.h#L2508-L2535

However, TFA can inform us that many "dynamic" functions will only be the target of static calls, and we don't need a monomorphic check for it.

`MonomorphicCheckedEntries` account for 4.5% of instruction code size on Flutter Gallery.

/cc @alexmarkov @mkustermann

**Comment by zhaoxuyang** [comment]
Why not put MonomorphicCheckedEntry to slow path？What is your solution?

**Comment by askeksa-google** [comment]
This was implemented as part of table dispatch in https://dart-review.googlesource.com/c/sdk/+/126648
