### ISSUE TITLE
Enum in analyzer serializer not sorted/refactor the format in Google3

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#39451]
For context: https://dart-review.googlesource.com/c/sdk/+/125554/1/pkg/analyzer/lib/src/summary/idl.dart#2022

The `UnlinkedTokenType` enums in `idl.dart` are no longer sorted.
Need to do a refactor to change the format.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/371260
