### ISSUE TITLE
pingInterval does not work

### ISSUE THREAD

**Issue by angel1st** [dart-lang/sdk#39469]
According to `io.dart` documentation, `pingInterval` in `IOWebSocketChannel.connect` is:
````
  /// [pingInterval] controls the interval for sending ping signals. If a ping
  /// message is not answered by a pong message from the peer, the WebSocket is
  /// assumed disconnected and the connection is closed with a `goingAway` code.
  /// When a ping signal is sent, the pong message must be received within
  /// [pingInterval]. It defaults to `null`, indicating that ping messages are
  /// disabled.
````
Well, my naive understanding was, if I configure `pingInterval` and in case the connection breaks, after `pingInterval` expires, the channel will close with `goingAway` code. However nothing like that happens.
Below is create channel code, please let me know if I miss some config options:

````
_channel = IOWebSocketChannel.connect(
        'ws://myserver.com:3121',
        pingInterval: Duration(seconds: 10),
      );
````

**Comment by natebosch** [comment]
Transferring to the SDK. `web_socket_channel` has no behavior associated with `pingInterval` - it is forwarded to the field on WebSocket.

This is a question about the documentation and behavior of assigning a duration to https://api.dart.dev/stable/2.6.1/dart-io/WebSocket/pingInterval.html

**Comment by ZichangG** [comment]
Hi,
I'm trying to fix this problem. From your description, I'm not sure what went wrong.

I looked at the implementation. Whenever `PONG` is not received on time, the connection is not closed. 

>  the connection is closed with a WebSocketStatus.GOING_AWAY close code

Is this the same as your observation?
