### ISSUE TITLE
Reduce size of monomorphic prologue by 2+ instructions by introducing Call-site guarantee of non-Smi

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39464]
With Dart 2.0 we have a strong type system. Most operations on integers are handled on the call site already (via `CheckNull`, `BinaryInt64Op`, `CheckedSmiOp`) 
=> We have very few dynamic calls to `_Smi``_Mint`.

So we can make our switchable instance calls **faster** and the **monomorphic callee checks** smaller by:

* Take advantage of `CompileType` at the call site and only issue switchable calls if we are **guaranteed** the receiver is not a `_Smi`.
* Simplify monomorphic entry prologue by removing 2+ machine instructions (in the class-id load)

@rmacnak-google  @mraleph @sjindel-google

**Comment by mkustermann** [comment]
@sjindel-google Maybe you want to look at this?

**Comment by sjindel-google** [comment]
Sure, it's related to https://github.com/dart-lang/sdk/issues/39446 as well

**Comment by mkustermann** [comment]
Doing this doesn't require any global knowledge and makes the calls faster, so I would start with this one :)

Please self-assign if you plan on working on it.

**Comment by sjindel-google** [comment]
Isn't it possible to regress some call-sites though if we don't know that the receiver is non-Smi?

**Comment by sjindel-google** [comment]
This approach is based on the assumption that we are devirtualizing all the hot Smi ops already.

However, the benchmarks reveal that there are many places where this does not happen, and consequently there are too many regressions to proceed.

It seems like we'll need significant improvements to TFA and our inlining heuristics before this idea is feasible.

**Comment by mraleph** [comment]
Samir, Could you post some benchmarking data here for the future reference?

**Comment by mkustermann** [comment]
Let's re-measure this now that one culprit was found :)

**Comment by mkustermann** [comment]
This change was made in d0909e068a35d42bd64caa01f49f0ff77de7ec8f and resulted in roughly -1.2% RX instruction reduction on flutter gallery (total gallery size reduction around -0.8).
