### ISSUE TITLE
Analyzer: Mixed returns is not an error any more

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39476]
Consider the following library:

```dart
import 'dart:async';

Future<void> foo(bool b) async {
  if (b) return;
  return null;
}
```

As of 54011e5622423d9bdbe4efaa5a37dff3b7771750, `dartanalyzer` reports errors for this library:

```
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201911/n045.dart|4|10|6|Functions can't include return statements both with and without values.
ERROR|STATIC_WARNING|MIXED_RETURN_TYPES|/usr/local/google/home/eernst/lang/dart/scratch/201911/n045.dart|5|3|6|Functions can't include return statements both with and without values.
```

The language specification used to have a rule saying that it is a compile-time error to have both `return;` and `return e;` in the same function, but this is no longer the case. The change occurred in SDK commit 9388cb3d0c3788ee37f84eddb6bff8e7a6bace62, and it was a consequence of integrating the feature specification invalid-returns.md into the specification. So the analyzer should stop checking and reporting `mixed_return_types`. The current spec text is [here](https://github.com/dart-lang/language/blob/58518773eab01ebcf8a57ec16e07a5d9588b7e71/specification/dartLangSpec.tex#L15323).

**Comment by bwilkerson** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/125927.

@eernstg The test `co19_2/Language/Statements/Return/many_return_statements_t01` appears to be based on the old spec. Could you please double check and follow up with the co19 team if necessary?

**Comment by eernstg** [comment]
I created an [issue](https://github.com/dart-lang/co19/issues/503) in the co19 repo for that, thanks!
