### ISSUE TITLE
Cherry-pick 635aaa8adfee0ae290a to dev channel

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39483]
We would prefer to cherry-pick 635aaa8adfee0ae2 for the next dev release (it reduces `dart2native` compiled application sizes)

**Comment by athomas** [comment]
Is this relevant for Flutter?

**Comment by mkustermann** [comment]
No. But it is my understanding we do a combined release, and for the dart release it would be very good to have

**Comment by athomas** [comment]
Good, the we should be able to cherry-pick this just into the Dart release, and we won't require Flutter to pick this up as well.

**Comment by athomas** [comment]
This is included in the 2.7.0-dev.2.0 build.
