### ISSUE TITLE
[vm] Improve types of closure captures

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39485]
We forget the types of variables when loading from contexts within closures.

/cc @mkustermann

**Comment by mkustermann** [comment]
At least for AST based front-end, the `LocalVariable`s should be annotated with their type, see [scopes.h    LocalVariable.type()](https://github.com/dart-lang/sdk/blob/master/runtime/vm/scopes.h#L109)

**Comment by sjindel-google** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/126100.
