### ISSUE TITLE
@Required does not give warning when class is generic - Example<T>

### ISSUE THREAD

**Issue by dmkerfont** [dart-lang/sdk#39481]
When a class is given a type parameter, the @Required tag does not give warnings when a parameter is missing.

![image](https://user-images.githubusercontent.com/15272811/69360713-a85ff780-0c50-11ea-84ea-8ce5e24f419d.png)

This works properly when the class has no type parameter

![image](https://user-images.githubusercontent.com/15272811/69360859-efe68380-0c50-11ea-9866-08c89e1de3d5.png)

This tracker is for issues related to:
* Analyzer - missing_required_param

Dartk SDK: 2.5.0
Windows
VSCode

**Comment by cubuspl42** [comment]
I confirm. This is deterministic and, in my opinion, very dangerous.

@dmkerfont Do you know if this a regression, or maybe it never worked?

**Comment by cubuspl42** [comment]
Please not, that generic free functions aren't affected.

**Comment by dmkerfont** [comment]
@cubuspl42 
> I confirm. This is deterministic and, in my opinion, very dangerous.
> 
> @dmkerfont Do you know if this a regression, or maybe it never worked?
I've only been working with flutter for a few weeks so I cannot say if this used to work.

**Comment by eernstg** [comment]
`@required` is not a part of the language Dart (but a `required` modifier on parameters will be added to Dart along with non-nullable types), and it is actually a 'hint' rather than a warning. But the following does produce a hint:

```dart
import 'package:meta/meta.dart';

class Example<T> {
  T value;
  Example({@required this.value});
}

void main() {
  Example();
}
```

as follows:

```
> dartanalyzer bin/main.dart
Analyzing bin/main.dart...
  hint • The parameter 'value' is required. . • bin/main.dart:9:3 • missing_required_param_with_details
1 hint found.
```

If you don't see this message then it could be caused by passing `--no-hints` to the analyzer?

**Comment by cubuspl42** [comment]
@eernstg 
The OP explicitly stated, that it works for non-generics, so I don't think it's possible that they pass `--no-hints`.
It appears to have been fixed in Dart 2.6.1, which is at the moment not available in Flutter.
https://travis-ci.org/cubuspl42/dart-lang-sdk-39481/builds/616763817

**Comment by eernstg** [comment]
The use of `@required` on a constructor/method/function parameter does not depend on whether the declaring entity is generic (cf. https://api.flutter.dev/flutter/meta/required-constant.html). But if the problem will disappear when Dart 2.6.1 or higher reaches Flutter, I think it would be a good idea to close this issue.

**Comment by dmkerfont** [comment]
Looks like this will just have to wait then. Thanks guys.
