### ISSUE TITLE
[vm/ffi] got 32-bit-inverted double value on some platforms

### ISSUE THREAD

**Issue by StimeKe** [dart-lang/sdk#39506]
We are developing phone app using flutter. The project is composed of a audio kernel written in C++ which is compiled into a shared library, and GUI part written in flutter. And they communicate each other in Dart FFI.

However, we found dart FFI always got 32-bit-binary-inverted double value (inverted in unit of 32-bits) for both function argument/return values. For example, if you returns -123.456 from C++ side function (binary `77 be 9f 1a 2f dd 5e c0`), the dart side would receive `2f dd 5e c0 77 be 9f 1a`, which is a twisted weird double value. And vice versa if you give it as argument to C++ side function.

This happens only in specific circumstances:

- OPPO android phone (a Chinese cell phone manufacturer).
     All OPPO phones we tested uses a 8-core A53 SoC. But other A53 SoC phones don't have this issue.

- **AND** release mode of flutter project. Debug mode is always OK.

This seems not a byte order issue, as it has a inverted unit of 32-bit, not 8-bit, so I have completely no idea about it. Is it a know issue to current development process? Or do you have any hints on it?

Thanks for a lot!

**Comment by dcharkes** [comment]
cc @mkustermann

> All OPPO phones we tested uses a 8-core A53 SoC. But other A53 SoC phones don't have this issue.

Interesting.

Just to double check: are you using `extern "C"` to ensure it is using the native ABI?

**Comment by StimeKe** [comment]
@dcharkes Yes we wrapped all API functions with `extern "C"`.

And please wait for a while for the minimal demo...

**Comment by StimeKe** [comment]
> cc @mkustermann
> 
> > 我们测试的所有OPPO手机均使用8核A53 SoC。但是其他A53 SoC手机没有这个问题。
> 
> 有趣。
> 
> 仔细检查一下：您`extern "C"`是否正在使用它来确保使用本机ABI？
> 
> 编辑：您是否有复制的最小示例？

**Comment by mkustermann** [comment]
@StimeKe Could you provide us with more information?

What does `flutter --version` say?

If the issue happens with `--profile` as well as `--release`, could you also provide us with the build command output, e.g.:
```
% flutter build aot --profile --target-platform=android-arm64 -v
...

.../clang_x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-elf
--elf=/.../app.so --strip /.../app.dill

...
```

Could you run `gen_snapshot` command printed above with an extra `--disassemble` command line argument:
```
% .../clang_x64/gen_snapshot --disassemble --causal_async_stacks --deterministic --snapshot_kind=app-aot-elf --elf=/.../app.so --strip /.../app.dill
                             ^^^^^^^^^^^^^
```

And give us the assembly blocks for the function which performs the C call as well as the machine code for the `FfiTrampoline` functions.


If a simple reproduction, e.g.
```dart
import 'dart:ffi';

final DynamicLibrary testLibrary = ...;
typedef CFunctionSignature = Double Function(Double, Double);
typedef DartFunctionSignature = double Function(double, double);

void main() {
  final DartFunctionSignature cFunction =
      testLibrary.lookupFunction<CFunctionSignature, DartFunctionSignature>('FooBarTest');
  print(cFunction(1.1, 1.2));
    ....
}
```
with calling a C function like
```
extern "C" double FooBarTest(double a, double b) { return a + b; }
```
reproduces the issue, you could send us the machine code for the Dart app as well as for the C function?

**Comment by simolus3** [comment]
This sounds very similar to https://github.com/flutter/flutter/issues/54948, which has been fixed.

**Comment by dcharkes** [comment]
It does, topic starter did not mention whether he was developing on Windows, but it is very likely.

I'll close this issue, please reopen if this is still an issue (on master).
