### ISSUE TITLE
num.tryParse and num.parse throws error when String contains comma

### ISSUE THREAD

**Issue by UlasKasim** [dart-lang/sdk#39508]
Unfortunately customers using comma instead of dots sometimes and I have to check if string contains comma then change them into dots, because of this i have this function
```
String replaceCommaWithPoint(String original){
  return original.replaceAll(",", ".");
}
```
There is a tryParse code
```
static num tryParse(String input) {
    String source = input.trim();
    // TODO(lrn): Optimize to detect format and result type in one check.
    return int.tryParse(source) ?? double.tryParse(source);
  }
```
What if we add to replace all method to change all ',' to '.' 
```
static num tryParse(String input) {
    String source = input.trim()..replaceAll(',','.');
    // TODO(lrn): Optimize to detect format and result type in one check.
    return int.tryParse(source) ?? double.tryParse(source);
  }
```

**Comment by lrhn** [comment]
Replacing `,` with `.` only works for inputs which use `,` as decimal point. An input like `100,000.00`, a traditional US notation, would not be saved by that, and an input like `100,000` would be off by a factor of 1000. It's probably better to have a hard failure than to "succeed" with a wrong answer.

We do not intend `double.parse` or `num.parse` to be general number parsing functions. They are ways to parse the result of `double.toString()` or `int.toString()` into the same number again, not any arbitrary input format. For more configurable number format parsing, you should use either `package:intl` or custom parsers for the formats that you choose to accept as input.

Adding an extra step to `tryParse` will affect performance of a function which is used in some performance sensitive settings. I would prefer to not add overhead there which every user has to pay for, even if only a minority gets any advantage from it.
