### ISSUE TITLE
List setRange/replaceRange doesn't re-hash the list.

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#39505]
Reproducible in [dartpad](https://dartpad.dartlang.org/):
```
void main() {
  final list = [1,2,3];
  print("hash1 ${list.hashCode} | $list");
  list.setRange(0,1,[5]); // also happens with replaceRange.
  print("hash1 ${list.hashCode} | $list");
}
```
**Expected**: hash result should be different after list is edited.
**Reality**: hash result is exactly the same as before. This makes really hard to edit lists without bugs, since hash is essential for a lot of usages. Example: my UI wasn't' refreshing because Flutter wasn't detecting any change even though the list was different.

I am using Dart 2.7.0 locally with Flutter, dartpad uses 2.6.0. This issue affects both.

**Comment by mraleph** [comment]
This is working as intended. List's `hashCode` is an identity hash code, not a hash code based on contents.

> Flutter wasn't detecting any change even though the list was different.

I don't think Flutter has any builtin change detection (unlike for example Angular). If you want widget to rebuild you need to tell Flutter that state is changing by calling [`setState`](https://api.flutter.dev/flutter/widgets/State/setState.html).

> Expected: hash result should be different after list is edited.

This expectation is in contradiction with how hashes work. Hashes have collisions (when two unequal objects have the same hash) so it is entirely possible that say `[1, 2, 3]` and `[5, 2, 3]` have the same hash even if List hash actually took contents into account.

**Comment by bernaferrari** [comment]
Thanks! (regarding Flutter, I was using the list's own hash to auto-calculate the diff in blocs. But as you just mentioned, I thought it was the hash of the elements. I'll change that, thanks!)
