### ISSUE TITLE
Support LSP completion snippet?

### ISSUE THREAD

**Issue by itome** [dart-lang/sdk#39500]
LSP server often send completion response like `child: ,`. Is there any option to make it some thing like `child: ${0},`?

Related issue -> https://github.com/emacs-lsp/lsp-mode/issues/1196

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
There isn't an option to control this, but it should be the standard behaviour. The client I was originally testing with didn't support snippet mode so the completion provider currently only supports plain-text.

https://github.com/dart-lang/sdk/blob/4f8f592b51990612335b66dccd5269aab09b96dd/pkg/analysis_server/lib/src/lsp/handlers/handler_completion_resolve.dart#L160-L165

I don't think it should be difficult to add though (and VS Code will be affected by this when running in LSP mode too) so I'll try and take a look at this soon.

**Comment by itome** [comment]
Thank you.

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/126165/

**Comment by itome** [comment]
Thanks! I'll try it when it merged.

**Comment by DanTup** [comment]
The change has been merged. If you don't want to run from source, it'll also be in tomorrow's nightly build (https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/).

Let me know if you have any issues. It does have tests and I've tested manually in VS Code, but we've seen differences between LSP clients before so it'd be good to know they're all interpreting this the same.

Thanks!

**Comment by itome** [comment]
I checked the nightly build and it works very fine in [lsp-mode](https://github.com/emacs-lsp/lsp-mode). Thank you!

**Comment by DanTup** [comment]
Great, thanks for confirming! 👍
