### ISSUE TITLE
Update pkg/analyzer/tool/diagnostics/diagnostics.md

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#39519]
@bwilkerson please update [diagnostics.md](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/diagnostics/diagnostics.md) to reflect what's in [diagnostic-messages.md](https://github.com/dart-lang/site-www/blob/3c3768a9b6a025140bbe5c1949f7c24cf1d5fb35/src/tools/diagnostic-messages.md):

* updated title in the YAML part
* added comment pointing to https://github.com/dart-lang/site-www/issues/1949
* (optional) updated filename

Thanks!

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/126241

(Updating the filename is a bit more involved than I'd like it to be, but I haven't forgotten that we want to do this.)
