### ISSUE TITLE
Thrown error is caught in a catch block but also printed as unhandled

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#39513]
I had this happen in a Flutter test (https://github.com/flutter/flutter/pull/45248#issuecomment-558092047) and I can't explain what's happening. It appears that an exception is thrown and caught, yet still printed to stderr as unhandled (and in the case of running inside a test, will fail the test).

I've managed to trim it down to this:

```dart
main() async {
  try {
    await resume();
    print('DID NOT THROW');
  } catch (e) {
    print('CAUGHT ERROR $e');
  }
}

Future<void> resume() async {
  await _printIfTakesLong(_throwError);
}

Future<String> _throwError() async {
  throw 'Error';
}

Future _printIfTakesLong(Future Function() callback) {
  final Future future = callback();

  future.timeout(const Duration(seconds: 1000), onTimeout: () {
    print('Task is taking long');
    return null;
  });

  return future;
}
```

The output of this is:

```
CAUGHT ERROR Error
Unhandled exception:
Error
#0      _throwError 
<asynchronous suspension>
#1      _printIfTakesLong
#2      resume 
<asynchronous suspension>
#3      main 
<asynchronous suspension>
#4      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
Exited (255)
```

Removing the `.timeout()` seems to stop it from happening, even though that timeout never fires.

I thought I must be missing an `await` or something in the original code, but then I wouldn't expect the `catch` block to be able to print that it caught `Error`.

**Comment by zanderso** [comment]
`Future.timeout` returns a new `Future` that completes with the same value as the `Future` it is called on. I suspect what's happening here is that the `Future` returned by `_printIfTakesLong` is `await`ed, and its error is handled by the `try-catch`, but the `Future` from the `Future.timeout` call is leaked, and its error gets thrown to the root zone.

**Comment by DanTup** [comment]
@zanderso but in the output, both errors are the same `Error` (neither are a timeout error) and the app terminates with those errors immediately (whereas the timeout error would not occur for 1000 seconds).

**Comment by DanTup** [comment]
Looks like your explanation is correct. The `timeout` future completes immediately because it's just passing the error through. If it's suppressed with a `catchError` then the problem goes away:

```
future.timeout(const Duration(seconds: 1000), onTimeout: () {
  print('Task is taking long');
  return null;
}).catchError((e) {});
```

I'll try to find a better way to log when these things are taking a long time without leaking these error-throwing futures.

Thanks!
