### ISSUE TITLE
corelib_2/cast_test.dart is broken

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39517]
I'm working on migrating some of the corelib_2 tests to NNBD and I ran into cast_test.dart. I was very confused by how what seemed like incorrect code in `testSet()` and `testMap()` could be passing, and then I realized:

```dart
void main() {
  testIterable();
  testList();
}
```

*Ohhhh.* Those functions aren't called at all. And, in fact, they are broken if you try to run them. I took a stab at fixing them myself, but I'm not sure what the intended behavior of the APIs is. In particular:

```dart
  dMap.remove(c); // Success, no type checks along the way.
```

The current implementation *does* cast the result to D, which fails. I'm not sure if the comment is wrong, the test is, or the implementation.

cc @leafpetersen

**Comment by lrhn** [comment]
See: https://dart-review.googlesource.com/c/sdk/+/126320

**Comment by lrhn** [comment]
Even better: See https://dart-review.googlesource.com/c/sdk/+/144469
