### ISSUE TITLE
TFA cannot devirtualize for-in loops

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39516]
For-in loops are elaborated to a set of calls to `.iterator`, `.moveNext` and `.current` by the Kernel Binary Frontend. These are not represented as calls in Kernel (but rather encapsulated in the `ForInStatement` node), so they cannot be analyzed or devirtualized by TFA.

/cc @mraleph @mkustermann @alexmarkov

**Comment by sjindel-google** [comment]
Unfortunately, fixing this results in a 0.5% code size increase due to more inlining opportunities :(

**Comment by mraleph** [comment]
@sjindel-google maybe we could devirtualize but inhibit inlining for now? alternatively we could finally start working on better inlining cost model.
