### ISSUE TITLE
Excessive analyzer error message for default parameter in function type aliases

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39524]
The code is
```dart
typedef void Foo({int i = 42});
```
Analyzer output is
```
  error - Default parameter values aren't allowed in typedefs. - syntax_A05_t02.dart:1:1 - default_value_in_function_type_alias
  error - Parameters in a function type cannot have default values - syntax_A05_t02.dart:1:25 - default_value_in_function_type
```
dartanalyzer version 2.7.0-dev.1.0

Why there are two very similar error messages here? What's the difference between these errors? I believe,  that there is only one error here and, therefore, there must be only one error message

**Comment by eernstg** [comment]
I suspect the best action is to remove the `typedef` error entirely: They are about to be generalized such that there is no guarantee that any particular type alias denotes a function type, and the function type is already addressed separately.

**Comment by bwilkerson** [comment]
We can't remove the diagnostic because we'll need to produce it in libraries that are opted out of the new functionality.

But I agree that there should only be one diagnostic produced in this case, and that it's a bug that there are two diagnostics.

**Comment by srawlins** [comment]
I don't see how `default_value_in_function_type_alias` provides value over `default_value_in_function_type`. If I had a line of code:

```dart
typedef void Foo({int i = 42});
```

and saw from the analyzer:

> error - Parameters in a function type cannot have default values - syntax_A05_t02.dart:1:25 - default_value_in_function_type

I don't think I'd be confused about the message, not with any confusion that would be cleared up by the text "Default parameter values aren't allowed in typedefs".

**Comment by bwilkerson** [comment]
@srawlins I'm not suggesting that analyzer needs to produce both diagnostics. I'm suggesting that
1. it _might_ still need to produce `default_value_in_function_type_alias` in some cases where it isn't producing the other (someone needs to look to determine whether that's the case), and
2. we can no longer remove errors when the spec changes to not require them because it's possible for users to opt out of those spec changes.

**Comment by leafpetersen** [comment]
> 2\. we can no longer remove errors when the spec changes to not require them because it's possible for users to opt out of those spec changes.

Unless I'm confused, I don't think there are any spec changes planned around this error that I know of.  I think the generalized type alias feature is basically irrelevant here.  As I understand it, there is a specified error that function types (no matter how they are introduced) may not have default values.  At least this is the intention - I think if any have been missed it is an errata in the spec.  If this is true (which I think it should be) then the error around default values in typedefs is entirely redundant.  In either case, I don't see how generalized type aliases changes anything about this?
