### ISSUE TITLE
LUB does not consider generic function types to be equivalent

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#39534]
I'm creating this issue to track so we know when it is safe to cleanup our workaround in the NNBD fork of the SDK. It came up from an email thread with @johnniwinther. The issues with LUB is compounded when nullability is added to the function types.

Repro:
```dart
typedef F1 = R Function<R>()?;

f() {
  R Function<R>()? a;
  R Function<R>()? b;
  F1 c = a ?? b;
}
```

Errors:
```
repro.dart:6:12: Error: A value of type 'Object Function()' can't be assigned to a variable of type 'R Function<R>()'.
 - 'Object' is from 'dart:core'.
  F1 c = a ?? b;
```

**Comment by nshahan** [comment]
We should be able to revert this change in the SDK when the issue is fixed:
https://dart-review.googlesource.com/c/sdk/+/126404

**Comment by stefantsov** [comment]
Proposed fix (work in progress): https://dart-review.googlesource.com/c/sdk/+/126725.

**Comment by stefantsov** [comment]
The CL has just landed.
