### ISSUE TITLE
io 实例报错什么原因？如下

### ISSUE THREAD

**Issue by anfenglei9527** [dart-lang/sdk#39530]
WebSocketChannelException: WebSocketException: Connection to 'https://openhw.work.weixin.qq.com/#' was not upgraded to websocket

代码如下：

```
getwxlink() {
  //连接微信服务器
 Map datax = {
    "cmd": "ping",
    "headers": {"req_id": "xxxxx"}
  };
  IOWebSocketChannel channel;
  try {
    channel = new IOWebSocketChannel.connect('wss://openhw.work.weixin.qq.com');

    channel.sink.add(datax);
  } catch (e) {
    print(e);
  }

  channel.stream.listen((message) {
    print(message);
    webSocket_callback(message, msname); //回调函数
  }, onError: onError1);
}
onError1(err) {
  debugPrint(err.runtimeType.toString());
  WebSocketChannelException ex = err;
  debugPrint(ex.message);
}


```

**Comment by natebosch** [comment]
I think this is a question about why the `dart:io` `WebSocket` is unable to connect to a particular endpoint. Potentially this is related to `wss://` instead of `ws://`? Or maybe there is something else going on?

**Comment by sortie** [comment]
Hi @anfenglei9527 

`openhw.work.weixin.qq.com` does not work for me. It returns HTTP 502 Bad Gateway. It is not a websocket for me. I'm closing the issue because I don't think I can help you. If you want more help, try run that curl command and see if it works.

I'm not sure if you read English, so I used Google Translate in case you don't:
> `openhw.work.weixin.qq.com` 对我不起作用。 它返回HTTP 502错误网关。 对我来说，这不是网络套接字。 我正在解决问题，因为我认为无法为您提供帮助。 如果您需要更多帮助，请尝试运行该`curl`命令，看看它是否有效。

```
$ curl -v -H "Connection: Upgrade" -H "Upgrade: websocket" https://openhw.work.weixin.qq.com
> GET / HTTP/1.1
> Host: openhw.work.weixin.qq.com
> User-Agent: curl/7.66.0
> Accept: */*
> Connection: Upgrade
> Upgrade: websocket
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.16.0
< Date: Tue, 10 Dec 2019 15:33:57 GMT
< Content-Type: text/html
< Content-Length: 15560
< Connection: keep-alive
< ETag: "58494d80-3cc8"
```
