### ISSUE TITLE
Make custom ELF loader support loading from in-memory RO data.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39543]
In addition to being file-based, we want the ELF loader to be able to load an AOT snapshot from an RO memory buffer (e.g. embedded as constant in the embedder).

I assume this should only take a day or so and it would significantly benefit a g3 customer.

@sjindel-google Can you take a look at this soon?

**Comment by sjindel-google** [comment]
How do you imagine he would load the segments? Coping them into anonymous memory?

**Comment by mkustermann** [comment]
Yes

**Comment by sjindel-google** [comment]
Closed in https://dart-review.googlesource.com/c/sdk/+/127644
