### ISSUE TITLE
Migration tool inserts unnecessary null check

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#39554]
Running the migration tool on the following program:

```dart
void test(bool z) {
  if (z == null) z = true;
  if (z) print("hello");
}
void main() {
  test(null);
}
```

Produces the following output, which has an analysis error because the `!` on `z` is unnecessary (it has been promoted via the assignment):

```dart
void test(bool? z) {
  if (z == null) z = true;
  if (z!) print("hello");
}

void main() {
  test(null);
}
```

The migration tool doesn't seem to be correctly accounting for the assignment promotion here.

cc @stereotype441

**Comment by MichaelRFairhurst** [comment]
Ran across this; can no longer reproduce.
