### ISSUE TITLE
Use two slashes when import the files will cause some errors

### ISSUE THREAD

**Issue by ping996** [dart-lang/sdk#39558]
When I use the two slashes when import the files cause my program executed failed, the imported file will call a singleton object, but the object created again when it called the second time. does the dart will pop an error when compile the code? not now yet.  is it an dart vm error?

**Comment by srawlins** [comment]
Please give an example of what you mean by "use the two slashes when import the files". What is your "program"? A web application? A command-line application?

What does the program execution do that is unexpected?

**Comment by a-siva** [comment]
Is this the error you are referring to?

```
Crash when compiling file://tmp/junk.dart,
at character offset null:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _Uri._toFilePath (dart:core/uri.dart:2743:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2738:49)
#2      new File.fromUri (dart:io/file.dart:267:49)
#3      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:66:18)
#4      HybridFileSystemEntity.readAsBytes (package:front_end/src/fasta/hybrid_file_system.dart:54:61)
<asynchronous suspension>
#5      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:212:55)
#6      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:299:26)
#7      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
```

**Comment by ping996** [comment]
no, just import other dart file in my project with two // caused my event bus can't send the message successfully, not a compile issue.

**Comment by a-siva** [comment]
Can you provide a sample piece of code showing your import statement.

**Comment by ping996** [comment]
such as:
```
import '../../util//xx.dart'
```
used two  '//' in that statement

**Comment by a-siva** [comment]
I tried a small program as follows
```
import '..//..//file.dart';

main() {
  func();
  print("Hello");
}
```

and file.dart has
```
func() {
  print("Hello");
}
```

When I run this I get the correct error message
```
': No such file or directory
import '..//..//file.dart';
       ^
/tmp/temp1/temp2/junk.dart:4:3: Error: Method not found: 'func'.
  func();
  ^^^^

```

**Comment by vsmenon** [comment]
For the given example, this is working as intended (`No such file or directory`).
