### ISSUE TITLE
non-nullable promotion on assignment not working

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#39562]
main.dart:
```
void main() {
  int? a;
  a = 42;
  int b = a;
  print(b);
}
```

```console
$ ./dart-sdk7/bin/dartanalyzer --enable-experiment=non-nullable main.dart
Analyzing main.dart...
  error • A value of type 'int?' can't be assigned to a variable of type 'int'. • main.dart:4:11 • invalid_assignment
1 error found.
| ~/tmp @ mit-macbookpro3 (mit)
$ ./dart-sdk7/bin/dartanalyzer --version
dartanalyzer version 2.7.0-dev.1.0
| ~/tmp @ mit-macbookpro3 (mit)
```

**Comment by mit-mit** [comment]
cc @lrhn this is expected to work, right?

**Comment by lrhn** [comment]
I expect it to work, and I'm hitting it now while migrating `dart:_http`.

**Comment by mit-mit** [comment]
cc @johnniwinther @stereotype441

**Comment by stereotype441** [comment]
Agreed.  The non-nullable analogue of the declared type needs to be a type of interest.  This is on my list to work on.

**Comment by sortie** [comment]
This pattern came up a bunch when migrating dart:io and the code could be made nicer once this feature is implemented.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144040
