### ISSUE TITLE
Analyzer NNBD wrong type inference.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39563]
Example:
```dart
Iterator<String> checkNoProxy(String? option) {
  if (option == null) throw "nope";
  return option.split(",").map((s) => s.trim()).iterator;
}
```
This gives the warning that a value of type `Iterator<String?>` cannot be returned because it expects an `Iterator<String>`.

The inference should not introduce any `?` for the iterator.

The signatures are:
```dart
String.split: List<String> split(String separator);
Iterable<E>/List<E>.map:  Iterable<T> map<T>(T Function(E));
String.trim: String trim();
Iterable<E>.iterator: Iterator<E> get iterator;
```
So, there is no reason to not infer `Iterable<String>` for the result of the return expression..

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/126702
