### ISSUE TITLE
Please merge 8023accf and f9cedb68 to dev

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#39579]
Please merge f9cedb68 and 8023accf into Flutter.

These fixes address https://github.com/flutter/flutter/issues/39916.

Impact of that bug is that nobody can release iOS Flutter apps on arm64 if they are using `dart:ffi`.

cc @athomas @tvolkert @mit-mit.

**Comment by tvolkert** [comment]
Those commits are both missing tests.

**Comment by athomas** [comment]
Cherry-picked into 2.7.0-dev.2.1.
