### ISSUE TITLE
Output divergence between DebugIA32 and ReleaseIA32

### ISSUE THREAD

**Issue by fizaaluthra** [dart-lang/sdk#39586]
```
Isolate (/b/s/w/itD1KudK/dart_fuzzGZOAVO) FP NO-FFI NO-FLAT : KBC-INT-DebugIA32 - JIT-NOINTRINSIFY-ReleaseIA32: !DIVERGENCE! 1.72:1467958387 (output)

-- BEGIN REPRODUCE  --

dartfuzz.dart --fp --no-ffi --no-flat --seed 1467958387 /b/s/w/itD1KudK/dart_fuzzGZOAVO/fuzz.dart

-- RUN 1 --

/b/s/w/ir/pkg/vm/tool/gen_kernel --gen-bytecode --platform=/b/s/w/ir/out/DebugIA32/vm_platform_strong.dill -o /b/s/w/itD1KudK/dart_fuzzGZOAVO/out.dill /b/s/w/itD1KudK/dart_fuzzGZOAVO/fuzz.dart
/b/s/w/ir/out/DebugIA32/dart --enable-interpreter --compilation-counter-threshold=-1 --old_gen_heap_size=128 /b/s/w/itD1KudK/dart_fuzzGZOAVO/out.dill

-- RUN 2 --

/b/s/w/ir/out/ReleaseIA32/dart --intrinsify=false --old_gen_heap_size=128 /b/s/w/itD1KudK/dart_fuzzGZOAVO/fuzz.dart

-- END REPRODUCE  --
```

cc @bkonyi 
Was unable to reproduce this locally.

**Comment by sstrickl** [comment]
For dartfuzz reproduction logs, could we get the commit on which the reproduction happened? When the failure is a Dart error (like an assert failure), the error message from Dart will include the commit hash, but in cases like this where it's an output divergence and not a Dart error, we don't have that info available. Given that dartfuzz generation changes over time (I noticed running dartfuzz on both commits mentioned in my comment on dart-lang/sdk#39734 had different outputs), knowing which commit the reproduction happened on is very important.

(If I'm just totally overlooking the commit information in the log pasted above somehow, please do point it out.)

**Comment by bkonyi** [comment]
> For dartfuzz reproduction logs, could we get the commit on which the reproduction happened? When the failure is a Dart error (like an assert failure), the error message from Dart will include the commit hash, but in cases like this where it's an output divergence and not a Dart error, we don't have that info available. Given that dartfuzz generation changes over time (I noticed running dartfuzz on both commits mentioned in my comment on #39734 had different outputs), knowing which commit the reproduction happened on is very important.
> 
> (If I'm just totally overlooking the commit information in the log pasted above somehow, please do point it out.)

I don't think we print the current commit anywhere. Let me see if I can add that for future runs. Thanks for the suggestion!

**Comment by bkonyi** [comment]
FYI @sstrickl, I've added the Dart SDK revision to the log output here: https://dart-review.googlesource.com/c/sdk/+/128374

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM. Please file another issue if this divergence could be reproduced without bytecode/interpreter.
