### ISSUE TITLE
when VM is requested to generate Kernel snapshot it compiles the same code twice

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#39580]
This is evident from the output: 

```
$ out/ReleaseX64/dart --snapshot=pkg/compiler/lib/src/dart2js.dart.kernel pkg/compiler/lib/src/dart2js.dart
pkg/compiler/lib/src/dart2js.dart: Warning: Interpreting this as package URI, 'package:compiler/src/dart2js.dart'.
pkg/compiler/lib/src/dart2js.dart: Warning: Interpreting this as package URI, 'package:compiler/src/dart2js.dart'.
``` 

Looking at the code I see that we first start the main isolate and then check if we need to generate Kernel snapshot after which we call `Snapshot::GenerateKernel(...);` which would compile all the same code again.
 
/cc @mkustermann @karlklose

**Comment by mraleph** [comment]
I think this actually affects Flutter tools build. `Building flutter tool...` takes twice as long as it should due to this issue - /cc @a-siva

**Comment by mraleph** [comment]
Bumping priority because it does affect people in the wild.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/225740 with proposed fix
