### ISSUE TITLE
Dart crashes on the incorrect class declaration instead throwing a compile error.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#39596]
Dart VM version: 2.7.0-dev.1.0 (Wed Nov 20 12:57:54 2019 +0100) on "windows_x64"

The dollowing source code declares a class with incorrect bounds:
``` dart
class A<X extends A<X, Y>, Y extends B<Null, A<X, Y>>> {}
main() {}
```
Class `B` is not declared anywhere, so declaration of `A` is also incorrect and compile error should be thrown here.

However, dart crashes on this example.

Sample output is:

> $> dartanalyzer test.dart
> Analyzing test.dart...
>   error - Undefined class 'B'. - test.dart:1:38 - undefined_class
> 1 error found.
>
> $> dart test.dart
> Crash when compiling null,
> at character offset null:
> InvalidType doesn't have nullability
> #0      InvalidType.nullability (package:kernel/ast.dart:5477:34)
> #1      DartType.isPotentiallyNonNullable (package:kernel/ast.dart:5456:12)
> #2      new IsSubtypeOf.basedSolelyOnNullabilities (package:kernel/type_environment.dart:238:52)
> #3      SubtypeTester.performNullabilityAwareSubtypeCheck (package:kernel/type_environment.dart:524:20)
> #4      SubtypeTester.isSubtypeOf (package:kernel/type_environment.dart:369:9)
> #5      TypeSchemaEnvironment.isSubtypeOf (package:front_end/src/fasta/type_inference/type_schema_environment.dart:306:18)
> #6      findTypeArgumentIssues (package:kernel/src/bounds_checks.dart:286:33)
> #7      ClassBuilderImpl.checkTypesInOutline (package:front_end/src/fasta/builder/class_builder.dart:857:40)
> #8      SourceLibraryBuilder.checkBoundsInOutline (package:front_end/src/fasta/source/source_library_builder.dart:2927:21)
> #9      SourceLoader.checkBounds.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:906:16)
> #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #11     SourceLoader.checkBounds (package:front_end/src/fasta/source/source_loader.dart:902:14)
> #12     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:276:14)
> <asynchronous suspension>
> #13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> <asynchronous suspension>
> #14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250:12)
> <asynchronous suspension>
> #15     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:125:28)
> <asynchronous suspension>
> #16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> <asynchronous suspension>
> #17     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
> <asynchronous suspension>
> #18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
> <asynchronous suspension>
> #19     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #20     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #21     new Future.sync (dart:async/future.dart:222:31)
> #22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #23     _rootRun (dart:async/zone.dart:1124:13)
> #24     _CustomZone.run (dart:async/zone.dart:1021:19)
> #25     _runZoned (dart:async/zone.dart:1516:10)
> #26     runZoned (dart:async/zone.dart:1463:12)
> #27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #29     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
> <asynchronous suspension>
> #30     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
> <asynchronous suspension>
> #31     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:338:17)
> <asynchronous suspension>
> #32     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:162:45)
> <asynchronous suspension>
> #33     new Future.<anonymous closure> (dart:async/future.dart:174:37)
> #34     _rootRun (dart:async/zone.dart:1120:38)
> #35     _CustomZone.run (dart:async/zone.dart:1021:19)
> #36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> #38     _rootRun (dart:async/zone.dart:1124:13)
> #39     _CustomZone.run (dart:async/zone.dart:1021:19)
> #40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #41     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
> #42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> #43     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> #44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> 
> 
> #0      InvalidType.nullability (package:kernel/ast.dart:5477:34)
> #1      DartType.isPotentiallyNonNullable (package:kernel/ast.dart:5456:12)
> #2      new IsSubtypeOf.basedSolelyOnNullabilities (package:kernel/type_environment.dart:238:52)
> #3      SubtypeTester.performNullabilityAwareSubtypeCheck (package:kernel/type_environment.dart:524:20)
> #4      SubtypeTester.isSubtypeOf (package:kernel/type_environment.dart:369:9)
> #5      TypeSchemaEnvironment.isSubtypeOf (package:front_end/src/fasta/type_inference/type_schema_environment.dart:306:18)
> #6      findTypeArgumentIssues (package:kernel/src/bounds_checks.dart:286:33)
> #7      ClassBuilderImpl.checkTypesInOutline (package:front_end/src/fasta/builder/class_builder.dart:857:40)
> #8      SourceLibraryBuilder.checkBoundsInOutline (package:front_end/src/fasta/source/source_library_builder.dart:2927:21)
> #9      SourceLoader.checkBounds.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:906:16)
> #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #11     SourceLoader.checkBounds (package:front_end/src/fasta/source/source_loader.dart:902:14)
> #12     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:276:14)
> <asynchronous suspension>
> #13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> <asynchronous suspension>
> #14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250:12)
> <asynchronous suspension>
> #15     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:125:28)
> <asynchronous suspension>
> #16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> <asynchronous suspension>
> #17     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
> <asynchronous suspension>
> #18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
> <asynchronous suspension>
> #19     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #20     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #21     new Future.sync (dart:async/future.dart:222:31)
> #22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #23     _rootRun (dart:async/zone.dart:1124:13)
> #24     _CustomZone.run (dart:async/zone.dart:1021:19)
> #25     _runZoned (dart:async/zone.dart:1516:10)
> #26     runZoned (dart:async/zone.dart:1463:12)
> #27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #29     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
> <asynchronous suspension>
> #30     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
> <asynchronous suspension>
> #31     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:338:17)
> <asynchronous suspension>
> #32     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:162:45)
> <asynchronous suspension>
> #33     new Future.<anonymous closure> (dart:async/future.dart:174:37)
> #34     _rootRun (dart:async/zone.dart:1120:38)
> #35     _CustomZone.run (dart:async/zone.dart:1021:19)
> #36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> #38     _rootRun (dart:async/zone.dart:1124:13)
> #39     _CustomZone.run (dart:async/zone.dart:1021:19)
> #40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #41     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
> #42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> #43     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> #44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
>

**Comment by stefantsov** [comment]
It seems that the bug was fixed some time ago.

```
$ dart --version
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "linux_x64"
$ cat /tmp/test.dart
class A<X extends A<X, Y>, Y extends B<Null, A<X, Y>>> {}
main() {}
$ dart /tmp/test.dart
/tmp/test.dart:1:38: Error: Type 'B' not found.
class A<X extends A<X, Y>, Y extends B<Null, A<X, Y>>> {}
                                     ^
/tmp/test.dart:1:38: Error: Expected 0 type arguments.
class A<X extends A<X, Y>, Y extends B<Null, A<X, Y>>> {}
                                     ^
```

I'm closing the issue.  Please re-open if it appears to be present.
