### ISSUE TITLE
The analyzer is too strict on null-aware constructs

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39598]
[Edit Dec 10: Corrected reference to issue at the end of this text.]

Thanks to @sgrekhov for noticing this. Consider the following program:

```dart
class A {
  void m() {}
}

main() {
  A a = new A();
  a?.m();
}
```

The analyzer with `--enable-experiment=non-nullable` as of commit 3557973a75bdee3d6c1329aa359c4317fe3c6a5e responds as follows:

```
> 
Analyzing n000.dart...
  error • The target expression can't be null, and so '?.' isn't necessary. • n000.dart:8:4 • unnecessary_null_aware_call
```

Apparently, this is a compile-time error. But the nnbd specification makes it a [warning](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors).

The option `--format=machine` does include `STATIC_WARNING` so maybe we could say that this is reported as a warning, but the exit code of this run was 3 (which is also reported for programs that have an error which is definitely not a warning), so it seems likely that it will give rise to build failures in the same way as an error.

A similar example with `a?..m()` does not give rise to any messages, but should be a warning as well. Similarly for `a?.[0]` when `A` has an `operator []`.

Note also that this warning is not applicable for receivers whose static type is of the form `S*`, cf. https://github.com/dart-lang/language/issues/715.

**Comment by srawlins** [comment]
This does not appear to be related to the migration.

**Comment by sgrekhov** [comment]
I believe that this is the same issue. Accodring to the NNBD [specification ](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors)

> It is a warning to use the null check operator (!) on a non-nullable expression.

In fact, analyzer produces an error

```dart
class A {}

main() {
  A a = new A();
  a!; // error - The '!' will have no effect because the target expression cannot be null. - static_errors_A27_t03.dart:21:4 - unnecessary_non_null_assertion
}
```
dartanalyzer version 2.7.0-dev.2.1

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/127742 will change severity of these errors to warnings.

> Note also that this warning might not be applicable for receivers whose static type is of the form S*, cf. #39598.

@eernstg Is the referenced issue correct here? It is this issue, so does not add new information :-( 

@leafpetersen It looks that the spec requires us to report the warning for `S*`, because they are non-nullable. The spec says: "It is a warning to use a null aware operator (?., ?.., ??, ??=, or ...?) on a non-nullable value.", and `int* <: Object`.

**Comment by eernstg** [comment]
> Is the referenced issue correct here?

Thanks for spotting this mistake&mdash;I've corrected the link now.

**Comment by leafpetersen** [comment]
See [this](https://github.com/dart-lang/language/pull/721) update to the spec which fixes the legacy type issue.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/128764 will use the new `strictly non-nullable` predicate where `non-nullable` was used.

**Comment by scheglov** [comment]
Also b6e051e2c87a711b0a3860523e1c3f050d33b4ae.
I believe this issue is fixed now.
