### ISSUE TITLE
analyzer sees any content like "// ignore:" as an ignore comment, even non-comments

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#39607]
Analyzer sees the content, `// ignore:` as an ignore comment, no matter where it occurs in a Dart library. For example, Flutter's `dev/bots/analyze.dart` contains the following line:

```dart
final RegExp _grandfatheredDeprecation = RegExp(r' // ignore: flutter_deprecation_syntax, https://github.com/flutter/flutter/issues/[0-9]+$');
```

which is seen to have an ignore comment, which would ignore two codes: `flutter_deprecation_syntax`, and `https://github.com/flutter/flutter/issues/[0-9]+$`.

https://github.com/flutter/flutter/blob/b9a56b9f48462d897101284f5f57b8568ef683c6/dev/bots/analyze.dart#L165

Files which generate code may also feature `// ignore:` or `// ignore_for_file:` will also encounter this issue, like Angular's compiler:

https://github.com/dart-lang/angular/blob/706c1b634443cfe2ba60b6ab37e2a536078ed00a/angular_compiler/lib/src/outliner.dart#L24

Fixing this issue would be a "breaking" change for some analyzer customers, in that more warnings may be reported in the _generating_ code, if it violates analyzer errors that it intends to ignore in _generated_ code.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/155847

**Comment by srawlins** [comment]
😀 🍾 Thanks! 🎉
