### ISSUE TITLE
Please merge #3f32196958970682b1acba6abb73bb891e23709e into dev channel

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39605]
**commit(s) to merge**: 3f32196958970682b1acba6abb73bb891e23709e 

**merge instructions**: clean merge

**reason**: The LateInitializationError class was introduced without library owner review. This CL adds better docs and makes the class abstract and non-instantiable, which is a safer default that we can loosen later if necessary. I'd prefer to no release it without this restriction because it would lock us in to the current affordances.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas 

--------
Thank you for filing a merge-to-dev request, please:
  * fill in the data above
  * set a milestone and area label (e.g. area-dart2js for a dart2js fix) 
  * attempt to do the merge (`git checkout origin/dev; git cherry-pick HASH`) to ensure the merge instructions are accurate.
  * delete this comment and examples :)

EXAMPLE 1:
> **commit to merge**: a7e511f (Should match the hash in the title. It's OK to have more than one commit, but please explain.)
>
> **merge instructions**: merges cleanly in `origin/dev`
>
> **reason**: fixes bug with nsm-forwarders with named arguments. Affects customers unit tests that use mockito.

EXAMPLE 2:
> **commit to merge**: a7e511f
>
> **merge instructions**: patch [CL/xyz](link) (merge had conflicts, CL resolves them).
>
> **reason**: fixes bug with nsm-forwarders with named arguments. Affects > customers unit tests that use mockito.

**Comment by athomas** [comment]
Cherry-picked into 2.7.0-dev.2.1.
