### ISSUE TITLE
Please merge 175ceca1fa6b53c9c831be4469b6b1e05663b096 into dev channel

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#39617]
**commit(s) to merge**: 175ceca1fa6b53c9c831be4469b6b1e05663b096

**merge instructions**: merges cleanly in `origin/dev`

**reason**: Fixes: https://github.com/dart-lang/pub/issues/2264

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
@tvolkert This is Flutter related change to pub, let me know if Flutter accepts this for 1.12 and I'll merge it to Dart's dev branch.

The only change in pub from is this commit:
https://github.com/dart-lang/pub/commit/ff5ad1eab1649a8eee6cc593302d3624d9853049

**Comment by athomas** [comment]
To actually land this change in Flutter we probably need more than just cherry-picking this into the SDK, because Flutter has its own pinned version:
https://github.com/flutter/engine/blob/master/DEPS#L81

**Comment by tvolkert** [comment]
At first glance, this doesn't look serious enough to warrant a hotfix.

**Comment by athomas** [comment]
I'll close this without merging it. If there is a strong need to get this into Flutter, a Flutter hotfix request should be filed (because this actually needs a change to Flutter engine rather than the Dart SDK to make it into Flutter).
