### ISSUE TITLE
Unexpected behavior from duration

### ISSUE THREAD

**Issue by friebetill** [dart-lang/sdk#39619]
The unexpected behaviour occurs in the dart:core library in the [Duration](https://api.dartlang.org/stable/2.6.1/dart-core/Duration-class.html) class. A negative duration is returned if the days are above the value 106751991 when creating a duration.

Here is an example code to demonstrate the problem:
```dart
void main(){
  print('Is Duration with 106751991 days negative? ${Duration(days: 106751991).isNegative}');
  // Output: Is Duration with 106751991 days negative? false
  print('Is Duration with 106751992 days negative? ${Duration(days: 106751992).isNegative}');
  // Output: Is Duration with 106751992 days negative? true
}
```

The problem does not occur in the [DartPad](https://dartpad.dartlang.org/), probably because the Javascript conversion removes the error or because the error was already solved in the Dart version 2.6.1.

I am using Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64".

**Comment by lrhn** [comment]
This is the VM 64-bit integer overflowing when used to represent microseconds.

We'll have to document that the `Duration` has a limit on the number of microseconds it can represent. 

We may want to ensure that it works correctly for the difference between any accepted `Date` objects (which also have a limit on the number of years they can represent). Maybe the limit needs to be low enough that the number can be represented by a double when compiling to JS

**Comment by lrhn** [comment]
We *can't* throw instead of overflowing because the constructor is `const`. This limits our ability to do any checking for overflow of the sum. I'll add asserts catching the cases where the individual values are too big. That might catch some inputs, but not overflows coming from adding different parts.

**Comment by lrhn** [comment]
Let's not do anything here, except document that the value can overflow.
