### ISSUE TITLE
Analyzer incorrectly says field is unused

### ISSUE THREAD

**Issue by parren-google** [dart-lang/sdk#39618]
Analyzer says field is unused, but it isn't:

```
extension Bar on Foo {
  int baz() => _baz;
  static final _baz = 1;
}
void main() {
  Foo.a.baz;
}
```

The field `_baz` is flagged as unused. Observed in VSCode.
Dart VM version: 2.7.0-edge+google3-v2 (google3) on "linux_x64"

**Comment by eernstg** [comment]
Right, here's a version of the code that fills in a couple of missing declarations and shows that we _do_ actually use `_baz` (and we still get the hint that it is unused, with a fresh analyzer from commit 2de9b45c8f1e7eeb8a1612282e26bcc0af7cfb6c):

```dart
class Foo {
  static Foo get a => Foo();
}

extension Bar on Foo {
  int baz() => _baz;
  static final _baz = 239487;
}

void main() {
  print(Foo.a.baz() == 239487); // Prints 'true'.
}
```

**Comment by parren-google** [comment]
Ah, sorry. Incomplete paste. My example should have `enum Foo {a, b}`.

**Comment by eernstg** [comment]
OK, that's just one more test case to consider. ;)

**Comment by leonardoayres** [comment]
It still happening with the latest Dart and Flutter 1.20.1 :-/

**Comment by mraleph** [comment]
@leonardoayres you would need to provide a reproduction (and file a separate bug) because reproduction from this issue does not show the hint anymore.
