### ISSUE TITLE
Exclamation mark added after literal null

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#39623]
-- snipped from an offline comment by @bwilkerson ---

...  I did see some other strange behavior when I was looking at `sdk/third_party/pkg/typed_data/lib/typed_buffers.dart` this morning.  Notice the `!` added after the literal `null` (on line 92):

```dart
void addAll(Iterable<E> values, [int start = 0, int? end]) {
  RangeError.checkNotNegative(start, "start");
  if (end != null && start > end) {
    throw new RangeError.range(end, start, null!, "end");
  }

  _addAll(values, start, end);
}
```
When I navigate to the constructor, the corresponding parameter is marked as nullable:

```dart
RangeError.range(num invalidValue, int? minValue, int? maxValue,
    [String? name, String? message])
    : start = minValue,
      end = maxValue,
      super.value(invalidValue, name, message ?? "Invalid value");
```

Is there a reason I'm not seeing that explains why the exclamation point was added? It looks like it might be a similar issue with the handling of the SDK classes, but I haven't dug to determine whether that's true.

--- snip ---

**Comment by srawlins** [comment]
This is expected. #38345 is a similar issue indicating we should call out such cases.
