### ISSUE TITLE
Analyzer code completion is suggesting names already in scope

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#39624]
Given some

```
final String foo;
final String bar;
final String name;
final String |
```

the tokens `foo`, `bar`, `name`, (and I'd argue `_foo`, `_bar`, and `_name` as well), should not be listed in code completion at the `|` above.

**Comment by bwilkerson** [comment]
I totally agree that names that are already in scope should not be suggested. That would also hold for names declared after the cursor such as:
```
String |
String foo;
```
or names of a different kind:
```
String get foo => '';
final String |
```
but that second example is why I'm less sure about derived names. I could easily imagine a user wanting to name the next field `_foo`. (I've even seen a real example of a class with both a public and a private field whose names differed only by the leading underscore, though I expect that's rare.)

**Comment by bwilkerson** [comment]
I believe that these suggestions were coming from the language model. Disabling the language model appears to have solved the issue.
