### ISSUE TITLE
Memory Leak in _LinkedHashSet when objects (not String or int) are used as the entries

### ISSUE THREAD

**Issue by audioMirror** [dart-lang/sdk#39638]
**Dart SDK Version: 2.5.0**
Although bug looks to be at least 4 years old.

**OS**: Windows (but shouldn't matter)

**dart2js** compilation, running on any browser.

Behavior: When using anything other than a String or int as the Key for a default Set<Value>, or a Set<Value>.identity() in a javascript build, an internal leak of Array objects occurs in the **_LinkedHashSet** or **_IdentityLinkedHashSet** if elements are continually being added (and removed) with different actual Value objects.

**Severety: Extreme**. If you use a Set this way, it causes the code to slow and then die from the millions of Array object leaks.

**Also Affected: _HashMap** in collection_patch.dart is also affected (from new HashMap() or HashMap.identity() ), but the default Map or LinkedHashMap from linked_hash_map.dart was fixed already in Case #36670 

----------------------------------------------
Here is a snippet of dart-lang
sdk/blob/master/sdk/lib/_internal/js_runtime/lib/collection_patch.dart

<pre>
class _LinkedHashSet<E> extends _SetBase<E> implements LinkedHashSet<E> {
  ...
  var _rest;
  ...
  bool remove(Object object) {
    if (_isStringElement(object)) {
      return _removeHashTableEntry(_strings, object);
    } else if (_isNumericElement(object)) {
      return _removeHashTableEntry(_nums, object);
    } else {
      return _remove(object);
    }
  }

  bool _remove(Object object) {
    var rest = _rest;
    if (rest == null) return false;
    var bucket = _getBucket(rest, object);
    int index = _findBucketIndex(bucket, object);
    if (index < 0) return false;
    // Use splice to remove the [cell] element at the index and
    // unlink it.
    _LinkedHashSetCell cell = JS('var', '#.splice(#, 1)[0]', bucket, index);
    _unlinkCell(cell);
    return true;
  }
  ...
  bool _removeHashTableEntry(var table, Object element) {
    if (table == null) return false;
    _LinkedHashSetCell cell = _getTableEntry(table, element);
    if (cell == null) return false;
    _unlinkCell(cell);
    _deleteTableEntry(table, element);
    return true;
  }
  ...
  void _deleteTableEntry(var table, var key) {
    JS('void', 'delete #[#]', table, key);
  }
  ...
}
</pre>

Notice that the _remove method does not call _deleteTableEntry() at any time.

This bug is a parallel bug to Case #36670, and fix should be identical. 

See [https://dart-review.googlesource.com/c/sdk/+/99885/2/sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart](https://dart-review.googlesource.com/c/sdk/+/99885/2/sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart) 

This class has different code paths for String, int, and "everything else" keys. For object keys, the hashcode becomes a 30-bit integer. This becomes the key to a bucket that is put into a bare JS Object named _rest in the code.

There are therefore up to 2^30 buckets that could be created by this class, if new objects are added as keys. And, they are never removed! If a _LinkedHashSet (or a sub-class like _LinkedIdentityHashSet) is used with continually new objects as keys, the application will quickly slow down in garbage-collection panic, and eventually die of out-of-memory.

The buckets themselves leak (not the user data). The buckets are an Array(). This is easily seen in the Chrome debug Memory console as a huge number of Array leaks.

**NOTE:** The **_HashMap** (invoked by creating a new HashMap or HashMap.identity() with dart2js ) in this same file **also has the bug** (which I verified in a test case),  However the separate JSLinkedHashMap in the linked_hash_map.dart file of Case #36670 was already fixed.

**Comment by audioMirror** [comment]
I have a fix for sdk/blob/master/sdk/lib/_internal/js_runtime/lib/collection_patch.dart , for both the _LinkedHashSet and _HashMap.

If I submit a patch according to the instructions on https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md , will a contributor be able to review and accept them?

**Comment by rakudrama** [comment]
Hi @audioMirror, please review https://dart-review.googlesource.com/c/sdk/+/129263
If this is what you had in mind, I'll make the equivalent changes in the various development branches we have active at the moment.

**Comment by audioMirror** [comment]
Yes, those changes look good!

**Comment by rakudrama** [comment]
Fixed via b1acde8d70efc62bfb056b0d723c0efacac6d6eb
