### ISSUE TITLE
Override error message does not show nullability annotation

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39647]
Consider:

```dart
class A {
  method(int? n) {}
}

class B extends A {
  method(int n) {}
}
```

`method()` in B is an invalid override because the parameter is not nullable and should be. If I run:

```
dartanalyzer --enable-experiment=non-nullable temp.dart
```

It dutifully detects that error:

```
Analyzing temp.dart...
  error • 'B.method' ('dynamic Function(int)') isn't a valid override of 'A.method' ('dynamic Function(int)'). • temp.dart:6:3 • invalid_override
1 error found.
```

Note however that the first function type shown says `int` and not `int?`. This makes it look like the override is fine and the error is bogus when really it's just not showing the type correctly.

**Comment by srawlins** [comment]
This was fixed recently; at head I see:

```
Analyzing 39647.dart...
  error • 'B.method' ('dynamic Function(int)') isn't a valid override of 'A.method' ('dynamic Function(int?)'). • 39647.dart:6:3 • invalid_override
1 error found.
```
