### ISSUE TITLE
Consider removing unused parameters in AOT

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39640]
If parameter is not used in a method, it might be possible to remove it in certain cases (for example, if method is static, so all call sites are known and can be adjusted accordingly). Whole-program constant propagation (https://dart-review.googlesource.com/c/sdk/+/125936) increases chances that parameter becomes unused even if it was originally used.

Also, we can remove passing of optional arguments from call sites if they are not used in any of the targets.

**Comment by sjindel-google** [comment]
Self assigning since it may overlap with https://github.com/dart-lang/sdk/issues/40488

**Comment by askeksa-google** [comment]
Subsumed by https://github.com/dart-lang/sdk/issues/40488
