### ISSUE TITLE
Migration engine should understand about ArgumentError.checkNotNull

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39644]
The core SDK provides this handy function for verifying that an argument is not null:

```dart
// in class ArgumentError
static void checkNotNull(Object? argument, [String? name]) {
  if (argument == null) throw ArgumentError.notNull(name);
}
```

The migration engine should treat a call to this method as signaling non-null intent in exactly the same way that `assert(x != null)` would.

**Comment by stereotype441** [comment]
Maybe we should double check to see how frequently this is used outside the SDK before we do this

**Comment by stereotype441** [comment]
Note that Quiver also has a checkNotNull function that is similar.  We should consider using it as a hint if it's commonly used

**Comment by srawlins** [comment]
https://github.com/dart-lang/sdk/issues/39315 is the sister issue for quiver. It is used _much_ more internally at Google.
