### ISSUE TITLE
There are several ways Flutter can check for memory leaks?

### ISSUE THREAD

**Issue by Aaron009** [dart-lang/sdk#39645]
I wrote a memory leak code.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TextMemoryLeak(),
    );
  }
}

class TextMemoryLeak extends StatefulWidget {
  @override
  _TextMemoryLeakState createState() => _TextMemoryLeakState();
}

class _TextMemoryLeakState extends State<TextMemoryLeak> {
  List memoryList = [];

  @override
  Widget build(BuildContext context) {
    Scaffold scaffold = Scaffold(
      appBar: AppBar(
        title: Text('test memory leaks'),
      ),
      body: Center(
        child: Text('${memoryList.length + 1}'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.map),
        onPressed: () {
          setState(() {

          });
        },
      ),
    );

    for (var i = 0; i < 100; ++i) {
      memoryList.add(scaffold); // A memory leak has occurred
      memoryList.add('A' * 1000);
    }
    return scaffold;
  }
}
```

This is a very simple code.

Every time you click on the `floatingButton`, it will be continuously added to the` memoryList` without being removed. This is an obvious memory leak.

I once read an article about Flutter checking for memory leaks.
The principle is that the larger the memory size requested by a function, the greater the possibility of a memory leak. (I forgot where I saw it. If anyone knows, please tell me the address of this article.)
I don't like this method because the memory requested by a function is very small, but it is a memory leak and it is difficult to check.

Another way is to use weakly referenced.

The principle is this.

```javascript
var memoryList = [];
memoryList.add('111111');

var weakMap = new WeakMap()
weakMap.set(memoryList, true);

forceGC();
// According to the principle, after executing gc, 
// if the memoryList key does not exist in the 
// `WeakMap`, 
// it means that the memoryList has recovered memory normally.
```

This troubleshooting method is very enjoyable. When I create an object, I make a weak reference to it to store it. When I destroy and force the use of GC, we can check the memory leaked objects through `WeakMap`.

####  In addition to the above two methods, is there a better way for Flutter to check for memory leaks?

I used to develop a game in which a colleague wrote a piece of code with a memory leak and then left. It was too painful when I investigated later.

**Comment by a-siva** [comment]
There are no immediate plans to support weak references in Dart.

I have transferred this issue under flutter/devtools as a request for better tooling to detect memory leaks in a flutter program, please follow https://github.com/flutter/devtools/issues/1437

**Comment by Aaron009** [comment]
I don't want to do tool checking because I haven't used very effective tools to check for memory leaks so far. I am a developer and have used many analysis tools, but it didn't help much.

I hope to have such a function.

In debug mode, an object is instantiated and then marked as recyclable by code. After GC was enforced, it was found that the object could not be recycled at this time, and an error or prompt was given.

**Comment by Aaron009** [comment]
@munificent 

Wow, I can see you here. I'm a game developer and I've seen the game design patterns you write and it's great.
