### ISSUE TITLE
Autocomplete error in VS Code working on flutter

### ISSUE THREAD

**Issue by 8155220** [dart-lang/sdk#39654]
**What I was doing**
Using autocomplete.

**Versions**
Dart Code extension: 3.6.0
Flutter extension: 3.6.0 (not activated)
VS Code: 1.40.0
Platform: win
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: C:\Users\Shep\AppData\Local\Android\flutter\bin\cache\dart-sdk
    Ver: 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db
Flutter SDK:
    Loc: C:\Users\Shep\AppData\Local\Android\flutter
    Ver: 1.9.1+hotfix.6
HTTP_PROXY: undefined
NO_PROXY: undefined

**Exception**

[9:39:23 PM] [Analyzer] [Error] Failed to handle completion domain request: {id: 133, method: completion.getSuggestions, params: {file: Z:\Flutter\flutterProject3\reserva_app\lib\blocs\test_bloc.dart, offset: 889}, clientRequestTime: 1575509963037}
[9:39:23 PM] [Analyzer] [Error] Exception: Element not found in summary: dart:core;dart:core;Never
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ElementHandle.librarySource (package:analyzer/src/dart/element/handle.dart:462:31)
#4      createExistingImportsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:101:19)
#5      CompletionDomainHandler.processRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:403:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart)
<asynchronous suspension>
#15     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#16     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#22     AnalysisServer.handleRequest.<…
[9:39:23 PM] [Analyzer] [Info] <== {"id":"134","result":{"contexts":[{"name":"Z:\\Flutter\\flutterProject3\\reserva_app","explicitFileCount":71,"implicitFileCount":978,"workItemQueueLength":0,"cacheEntryExceptions":[]}]}}
Wed Dec 04 2019 [21:39:29 GMT-0400 (Bolivia Time)] Log file ended

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
It looks that this happens in older Dat SDK, which uses summary1.
Consider updating to a newer Flutter / Dart SDK(s).
