### ISSUE TITLE
NNBD. Type not assignable to Object can be thrown

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39659]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) reads

> It is an error if the static type of e in the expression throw e is not assignable to Object.

Consider the following code
```dart
class A {
}

void test(A? x) {
  throw x;
}

main() {
  try {
    test(new A());
  } catch(e) {
    print(e);
  }
}
```
There must be an error here but Dart with --enable-experiment=non-nullable option simply execures this code without any issues. 
Tested on 
Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by stefantsov** [comment]
Thanks for reporting the bug!  Here's the proposed fix: https://dart-review.googlesource.com/c/sdk/+/128669.
