### ISSUE TITLE
NNBD. Local late variables with 'await' expression are allowed

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39661]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors)

> It is an error for the initializer expression of a late local variable to use a prefix await expression.

In fact, there is no error in this case nor in Analyzer nor in Dart
```dart
import "dart:async";
main() async {
  late int i = await 42;
}
```
The code above produces no errors in analyzer and runtime

Dart VM version: 2.7.0-dev.2.1
dartanalyzer version 2.7.0-dev.2.1

**Comment by scheglov** [comment]
This was fixed in 4fe27fd444f6ea3266050bf96dcd8a77f611afc2.
