### ISSUE TITLE
Spurious error on generic class with `FutureOr` in bound

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39666]
Consider the following program:

```dart
import 'dart:async';

class A<X extends FutureOr<List>> {}

void main() {}
```

With `dart` from commit c1565a7e6445becd7402b89611a3e471a15b12ed (of today) we get the following response:

```
n011.dart: Error: Type argument 'X' doesn't conform to the bound 'FutureOr<List<dynamic>>' of the type variable 'X' on 'A' in the return type.
 - 'FutureOr' is from 'dart:async'.
 - 'List' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
n011.dart:3:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends FutureOr<List>> {}
        ^
```

However, this doesn't actually make sense: There is no occurrence of `X` where it is passed as an actual argument to any parameterized types. Also, 'the return type' could hardly refer to the return type of `main`, and there are no other function declarations in this program.

The error only occurs when `FutureOr` is the special type from 'dart:async', it disappears if we add `class FutureOr<X> {}` and remove the import, so it must be part of the special treatment of `FutureOr`.

**Comment by johnniwinther** [comment]
Partially fixed by https://dart-review.googlesource.com/c/sdk/+/141541

Still needs handling for mixed inheritance.
