### ISSUE TITLE
NNBD. Dart ignores required named parameters

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39660]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors)

> It is an error if a required named parameter has a default value.
> 
> It is an error if a named parameter that is part of a required group is not bound to an argument at a call site.

```dart
void foo({required String s = ""}) {}

main() {
  foo();
}
```
The code above contains both of these errors and analyzer reports them but dart with  --enable-experiment=non-nullable doesn't

Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by stefantsov** [comment]
Here's the proposed fix for the first problem at the CFE side (that is, reporting errors on required named parameters having default values): https://dart-review.googlesource.com/c/sdk/+/130372.

**Comment by stefantsov** [comment]
Here's the proposed fix for the second problem at the CFE side (not passing a value for the required parameter at call site): https://dart-review.googlesource.com/c/sdk/+/131061.

**Comment by stefantsov** [comment]
I think the CFE part of this issue is resolved.  Of course, we can't statically detect cases like the following one, and we have to rely on the run time checking:

```dart
int foo({required String s}) => s.length;

main() {
  dynamic bar = foo;
  bar();
}
```

**Comment by johnniwinther** [comment]
Removing the front-end label as this should be considered a vm issue now.

**Comment by franklinyow** [comment]
Any update?

**Comment by franklinyow** [comment]
Any update?

**Comment by liamappelbe** [comment]
Working on it. Mailing the first CL today. This doesn't block unforking though.

**Comment by franklinyow** [comment]
If this does not block unforking, please take a look and decide if this could be moved under #40106 or #40107.
