### ISSUE TITLE
Some try-bots are failing with 'Invalid core_pattern configuration'

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#39662]
For example here: https://chromium-swarm.appspot.com/task?id=48ee1383d5a28c10

@sortie, @whesse, @athomas

**Comment by karlklose** [comment]
We have disabled the exception for now (https://dart-review.googlesource.com/c/sdk/+/127163)

**Comment by sortie** [comment]
We have a workaround in place and the commit queue works again. The root cause is <https://bugs.chromium.org/p/chromium/issues/detail?id=1030546>.

**Comment by whesse** [comment]
The change to puppet that changed the coredump pattern core_pattern has been reverted, and the workarounds are being reverted in https://dart-review.googlesource.com/c/sdk/+/127461

The change to puppet will be made more carefully, and will be tested to make sure it does not break the core pattern check on our linux swarming bots, when it relands.
