### ISSUE TITLE
Anzlyzer dead code detection is over-eager.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39668]
Example code:
```dart
  void _addValue(String name, Object value) {
    List<String> values = (_headers[name] ??= <String>[]);
    values.add(_valueToString(value));
  }
```
where `_headers` is declared as `final Map<String, List<String>> _headers;`.

Here I get a dead-code warning on the first line of the method. 
```
  hint • Dead code. • dart:_http/http_headers.dart:443:47 • dead_code
```
The code is correct and has a visible side effect, so some logic fails.

**Comment by MichaelRFairhurst** [comment]
This is probably not using the NNBD SDK.

If that is what's happening, it thinks `_headers[name]` has type `List<String>` and not `List<String>?`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/127681
