### ISSUE TITLE
package_config.json overlapping package roots.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39669]
The `package_config.json` file [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md) states that the package roots must not overlap.

It has been brought up that some packages have other packages nested inside, e.g., an example directory.

I propose to allow nested package roots, as long as they are properly nested (not the same directory) and the package URI roots are never inside another package as well.

All existing files will remain valid. Nobody uses the file yet.

@jonasfj @jakemac53

**Comment by jakemac53** [comment]
LGTM

> and the package URI roots are never inside another package as well.

In general I think this is a good restriction - there may be a few violations internally though that would have to be cleaned up (but not a lot I believe). CC @nshahan do you remember where you ran into this and if we cleaned it up already?

**Comment by jonasfj** [comment]
+1,

Good catch, many Flutter packages contain a full app as example.

**Comment by jakemac53** [comment]
This is implemented now right and can be closed? cc @lrhn

**Comment by lrhn** [comment]
I believe so.
