### ISSUE TITLE
No null-promotion in list literal.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39667]
Example code:
```dart
main(List<String>? args) {
  var list = [ if (args != null) ... args ];
}
```
Here I get a warning that `args` is nullable, which the test should have ensured that it isn't.

The actual code which that hit this was more like:
```dart
String? reason = ...;
var list = [ something, something, if (reason != null) ...utf8.encode(reason) ];
```
so I can't just use `...?`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/127482
