### ISSUE TITLE
Please update the pre-built SDK

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39672]
There is a bugfix in dart_style 1.3.2. It doesn't affect external users because it's related to the in-progress NNBD syntax so I didn't file a ticket roll the pre-build SDK. But now that Dart team people (like @cskau-g) are migrating code to NNBD, it's getting hit.

Could someone roll the SDK to the latest? Thanks!

See: https://github.com/dart-lang/dart_style/issues/877

**Comment by sortie** [comment]
@athomas will be updating the checked in SDK as part of the Dart 2.7 release.
