### ISSUE TITLE
NNBD. Strange error on VM for late final field

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39684]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) 

> It is not a compile time error to write to a final variable if that variable is declared late and does not have an initializer.

This works in analyzer, but in VM the code below produces a strange error

```dart
class C {
  late final v;
}

main() {
  new C().v = "here";
}
```
```
Unhandled exception:
Unimplemented handling of missing static target
#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
Tested on 
Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by liamappelbe** [comment]
It works for me. I'm running linux though, so it's possible it's a windows specific issue.

**Comment by sgrekhov** [comment]
Reproduced on Dart VM version: 2.7.0-dev.2.1 (Unknown timestamp) on "linux_x64"

**Comment by sgrekhov** [comment]
\]+m

mmmmm      b85/78/574555555  18//5//888878788888885 ,

**Comment by sgrekhov** [comment]
No issue in Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"
