### ISSUE TITLE
NNBD. No error for the class with the const constructor having late field

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39681]
According to the recent change in NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors)

> It is an error for a class with a const constructor to have a late final field.

But not there is no error in analyzer in this case.

```dart
class C {
  static late final int s = 42;
  late final int i = 42;
  const C();
}

main()  {
  C();
}
```
dartanalyzer version 2.7.0-dev.2.1 finds no issues in the code above

**Comment by scheglov** [comment]
This was fixed in 3de7487a2cfec15eeb262159cd0a789a50666b2c.
