### ISSUE TITLE
RawSynchronousSocket  Secure version

### ISSUE THREAD

**Issue by zfuke164345** [dart-lang/sdk#39683]
how can i pass certify and PrivateKey ?

**Comment by ZichangG** [comment]
Not quite sure about your use cases. Is [this](https://api.dartlang.org/stable/2.7.0/dart-io/SecurityContext/usePrivateKey.html) what you are looking for?

I'll close the issue. Looks like this question has been answered. https://github.com/dart-lang/sdk/issues/39703
