### ISSUE TITLE
Error compiling dartdevc module:webapp|lib/main.ddc.js

### ISSUE THREAD

**Issue by rajujin1** [dart-lang/sdk#39686]
dartdevc -k arguments: --dart-sdk-summary=C:\Users\1000254594\Desktop\fluttermy\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o
    C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\screens\login.ddc.js --source-map
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\meta\meta.ddc.dill=packages/meta/meta
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\foundation.ddc.dill=packages/flutter/foundation
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter_country_picker\country.ddc.dill=packages/flutter_country_picker/country
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\diacritic\diacritic.ddc.dill=packages/diacritic/diacritic
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\vector_math\hash.ddc.dill=packages/vector_math/hash
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\physics.ddc.dill=packages/flutter/physics
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\utils.ddc.dill=packages/collection/src/utils
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\collection\collection.ddc.dill=packages/collection/collection
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\gestures.ddc.dill=packages/flutter/gestures
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\painting.ddc.dill=packages/flutter/painting
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\semantics.ddc.dill=packages/flutter/semantics
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\animation.ddc.dill=packages/flutter/animation
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\rendering.ddc.dill=packages/flutter/rendering
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\widgets\actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\widgets.ddc.dill=packages/flutter/widgets
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\src\cupertino\action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\cupertino.ddc.dill=packages/flutter/cupertino
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter\material.ddc.dill=packages/flutter/material
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\flutter_country_picker\flutter_country_picker.ddc.dill=packages/flutter_country_picker/flutter_country_picker
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\util\KeyFinderIntf.ddc.dill=packages/webapp/util/KeyFinderIntf
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\beans\Question_Object.ddc.dill=packages/webapp/beans/Question_Object
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\beans\Qlist.ddc.dill=packages/webapp/beans/Qlist
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\beans\AnyInfo.ddc.dill=packages/webapp/beans/AnyInfo
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\util\responsive_widget.ddc.dill=packages/webapp/util/responsive_widget
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\device_id\device_id.ddc.dill=packages/device_id/device_id
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\util\ServerQuery.ddc.dill=packages/webapp/util/ServerQuery
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\util\MyStrings.ddc.dill=packages/webapp/util/MyStrings
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\pedantic\pedantic.ddc.dill=packages/pedantic/pedantic
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\charcode\ascii.ddc.dill=packages/charcode/ascii
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\charcode\html_entity.ddc.dill=packages/charcode/html_entity
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\charcode\charcode.ddc.dill=packages/charcode/charcode
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\path\path.ddc.dill=packages/path/path
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\term_glyph\src\generated\ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\source_span\source_span.ddc.dill=packages/source_span/source_span
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\string_scanner\src\eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\typed_data\typed_data.ddc.dill=packages/typed_data/typed_data
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\http_parser\http_parser.ddc.dill=packages/http_parser/http_parser
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\http\src\base_client.ddc.dill=packages/http/src/base_client
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\http\http.ddc.dill=packages/http/http
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\util\App_Db_Impl.ddc.dill=packages/webapp/util/App_Db_Impl
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\webapp\Base.ddc.dill=packages/webapp/Base
    --summary=C:\Users\1000254594\AppData\Local\Temp\scratch_spacebc8060bc-1815-11ea-a1ef-5c5f67283731\packages\provider\provider.ddc.dill=packages/provider/provider
    --packages=file:///C:/Users/1000254594/AppData/Local/Temp/kernel_builder_ca24e8e2-1815-11ea-a1ef-5c5f67283731/.packages --module-name=packages/webapp/screens/login --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map
    --libraries-file=file:///C:/Users/1000254594/Desktop/fluttermy/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=C:\Users\1000254594\AppData\Local\Temp\ddk_builder_ca24e8de-1815-11ea-a1ef-5c5f67283731\used_inputs.txt
    package:webapp/screens/login.dart
    dart --version: 2.6.0-dev.8.0.flutter-a61c775db8 (Thu Oct 17 14:39:30 2019 +0000) on "windows_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:457:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:474:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:161:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:472:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:207:29)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:153:10)
<asynchronous suspension>
#7      _compile (package:dev_compiler/src/kernel/command.dart:277:27)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by jakemac53** [comment]
@vsmenon do you know where the canonical issue is for this? We can merge it into that.

We expect this to be fixed in the `2.7.0` dart sdk.

**Comment by vsmenon** [comment]
Yes, merging to:

https://github.com/dart-lang/sdk/issues/38102
