### ISSUE TITLE
Dartfix non-nullable invalid `?` added (missing parens)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39697]
In the [build package](https://github.com/dart-lang/build/tree/master/build) we have the following function:

```dart
Logger get log => Zone.current[logKey] as Logger ?? _default;
```

The tool translates this into:

```dart
Logger get log => Zone.current[logKey] as Logger? ?? _default;
```

This isn't valid Dart code - the entire expression before the `??` needs to be wrapped in parens:

```dart
Logger get log => (Zone.current[logKey] as Logger?) ?? _default;
```

The syntax in general kind of sucks here as well - I don't know if we should consider allowing it without the parens in the grammar although I assume that would introduce some ambiguity in the grammar.

cc @leafpetersen @munificent

**Comment by leafpetersen** [comment]
As best I can tell the grammar allows the unparenthesized version.  @eernstg @lrhn am I missing something?

**Comment by jakemac53** [comment]
Ah, so probably a parser bug instead then?

**Comment by srawlins** [comment]
If this is just a bug in migrator, it's a duplicate of https://github.com/dart-lang/sdk/issues/38469

**Comment by jakemac53** [comment]
It sounds like this is more likely a parsing bug from what @leafpetersen said and an offline discussion I had with @munificent.

**Comment by leafpetersen** [comment]
Who handles parser bugs these days?

cc @johnniwinther @stereotype441

**Comment by johnniwinther** [comment]
@jensjoha
