### ISSUE TITLE
LHS of ?? should be inferred with a nullable context

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39694]
Consider the following code:
```dart
Object f() => g(null) ?? 0;
T g<T>(T t) => t;
main() {
  print(f());
}
```
With NNBD enabled, the analyzer produces the following output:
```
  error • The argument type 'Null' can't be assigned to the parameter type 'Object'. • .../test.dart:1:17 • argument_type_not_assignable
  hint • Dead code. • .../test.dart:1:26 • dead_code
```
I believe both of these are incorrect.  What's happening is that the downward inference context of `g(null) ?? 0` is `Object`, and that context is being passed down to `g(null)`, so the type argument `T` gets inferred as (non-nullable) `Object`.  Therefore, the `null` is not allowed, and the analyzer erroneously thinks that the `?? 0` is dead code.

I think what should happen instead is that when analyzing the LHS of a `??`, type inference should make the context nullable.  That would allow the code above to pass without error.

**Comment by leafpetersen** [comment]
Agreed.  Similarly for `!`, and I think `...?` as well.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131210

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131343 for `!`.
