### ISSUE TITLE
DDC excludes some SDK libraries when building the platform in the sdk_nnbd fork

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#39698]
We are temporarily building a smaller SDK platform to make progress building applications against the forked `sdk_nnbd` sources. This is because some of the libraries have not yet been ported and they don't compose well.

This is a tracking issue that we can close once all of these excluded libraries have been added back into the SDK that we build applications/tests against.
* dart:developer
* dart:io
* dart:isolate
* dart:indexed_db
* dart:html
* dart:html_common
* dart:svg
* dart:web_audio
* dart:web_gl
* dart:web_sql

**Comment by sigmundch** [comment]
Most are now included at this time, only missing `dart:io`
