### ISSUE TITLE
Dartfix non-nullable undesirable behavior with generics and function arguments

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39695]
In the [build package](https://github.com/dart-lang/build/tree/master/build) we have a private function like this:

```dart
Future<void> _futureOrWrite<T>(
        FutureOr<T> content, Future<void> write(T content)) =>
    (content is Future<T>) ? content.then(write) : write(content as T);
```
Result after the migrator:

```dart
Future<void> _futureOrWrite<T>(
        FutureOr<T> content, Future<void> write(T? content)) =>
    (content is Future<T?>) ? content.then(write) : write(content as T);
```

The migrator always wants to convert the function argument to a `T?` - but I can't fully understand why. This has a cascading effect of adding several more undesirable `?` throughout the codebase. I cannot figure out any way to make it not perform this change.

See the [preview dir](https://github.com/dart-lang/sdk/files/3933366/preview.tar.gz). If you look at the `lib/src/asset/writer.dart` all of the question marks there inevitably are a result of this. The good news is the tool did a good job of pointing me at the underlying cause though :).

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
