### ISSUE TITLE
Dartfix non-nullable preview UI bug (? in wrong place)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39693]
I tried running the migrator on the [build package](https://github.com/dart-lang/build/tree/master/build) - and I noticed a UI issue in the preview output.

See the attached preview dir - if you view the `lib/src/asset/writer.dart` file you will see some places where the highlighted `?` is in the wrong place:

![Screenshot from 2019-12-06 09-08-26](https://user-images.githubusercontent.com/984921/70341569-16d3b680-1808-11ea-9bc1-79443f7f3375.png)

If you look at the actual code after running the tool it did generate correctly:

```dart
  Future<void> writeAsBytes(AssetId id, List<int>? bytes);
```

[preview.tar.gz](https://github.com/dart-lang/sdk/files/3933220/preview.tar.gz)

**Comment by srawlins** [comment]
This looks to be fixed now. I suspect I fixed this when I escaped HTML in a few places.
