### ISSUE TITLE
Handle closure calls more precisely in type flow analysis

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39692]
Currently, all closures are treated conservatively in TFA: closure body is included into enclosing member, and parameters are approximated using static types. Closure calls are not analyzed.

TFA can be improved to track closure calls and handle closure bodies separately from enclosing member.

**Comment by modulovalue** [comment]
#53571 was closed because a solution to this issue is supposed to fix it. That issue contains a micro-benchmark that can then be used to verify this assumption. (_this is a reminder to myself to check this once this issue has been fixed_)

**Comment by a-siva** [comment]
@alexmarkov can this issue be closed as done ?

**Comment by alexmarkov** [comment]
@a-siva Yes, I think we can close this issue as done.

We end up analyzing only monomorphic closure calls, because analyzing all possible closure calls results in a huge combinatorial explosion and increases AOT compilation time too much.
