### ISSUE TITLE
Dartfix non-nullable should not add `?` to `FutureOr<Null>` or `FutureOr<void>`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39700]
Given this program:

```dart
import 'dart:async';

FutureOr<Null> doStuff(bool returnFuture) {
  if (returnFuture) return Future.value(null);
  return null;
}

FutureOr<void> doStuff2(bool returnFuture) {
  if (returnFuture) return Future.value(null);
  return null;
}
```

The dartfix tool will add a `?` to both return types - neither of which should be necessary.

**Comment by jakemac53** [comment]
Note that it will also add a `!` after the `null` literals :D.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
