### ISSUE TITLE
dartfix non-nullable errors on build_modules package

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39719]
I tried running the tool on the [build_modules](https://github.com/dart-lang/build/tree/master/build_modules) package a got several different types of errors - [here is the full output](https://github.com/dart-lang/sdk/files/3940810/out.txt). Some of these are explicitly unimplemented errors - others seem like more legit failures.

Note that the tool did still complete and apply meaningful changes to the code.

Here are some of the error messages (see linked file for stack traces):

* `Bad state: Unrelated types: class Null and abstract class Future<T>`
* `NoSuchMethodError: The method 'booleanLiteral' was called on null.
Receiver: null
Tried calling: booleanLiteral(Instance of 'BooleanLiteralImpl', false)`
* `Bad state: A decorated type for ModuleStrategy coarse should have been stored by the NodeBuilder via recordDecoratedElementType`
* `type 'TypeParameterTypeImpl' is not a subtype of type 'InterfaceType' in type cast`
* `UnimplementedError: TODO(paulberry)` (at `#0      new ConditionalModification (package:nnbd_migration/src/potential_modification.dart:41:7)`)
* `UnimplementedError: Simple identifier with a static element of type ConstFieldElementImpl_EnumValue in "fine" on line 34 of "~/build/build_modules/lib/src/common.dart"`
* `UnimplementedError: Simple identifier with a static element of type ConstFieldElementImpl_EnumValue in "coarse" on line 34 of "~/build/build_modules/lib/src/common.dart"`
* `UnimplementedError: LUB/GLB with substitution in "trackUnusedInputs ? [AssetId('b', 'lib/b$kernelOutputExtension')] : null" on line 97 of "~/build/build_modules/test/kernel_builder_test.dart"`

**Comment by srawlins** [comment]
The tool is definitely not ready to migrate packages yet. We can prioritize some early, upstream customers like code builders and Flutter, but don't expect anything soon.

**Comment by jakemac53** [comment]
Ya - I don't expect it to be working just seeing what does/doesn't work. If issues aren't helpful at this time I can stop filing them.

**Comment by srawlins** [comment]
This issue is particularly... broad :)

I like the issues that can be boiled down to minimal repros. Those are definitely helpful; I'm working on fixing one today.

**Comment by jakemac53** [comment]
Ok :). Feel free to close this one if you want. I didn't really want to spam with like 8 separate issues and didn't really know how to start efficiently creating minimal repros from these errors.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
