### ISSUE TITLE
NNBD. No static warning for using null-aware operators on non-nullable receiver

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39714]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors)

> It is a warning to use a null aware operator (?., ?.., ??, ??=, or ...?) on a non-nullable value.

```dart
class A {
}
class C extends A {}

main() {
  A? a = A();
  C c = C();
  if (a is Object) {
    a?.toString();
    a?..toString();
    a ?? c;           
    a ??= c;        
  }
}
```
The code above produces no any errors or warnings in dartanalyzer version 2.7.0-dev.2.1
See also #39598

**Comment by scheglov** [comment]
@leafpetersen Is this kind of promotion supported by [the flow analysis](https://github.com/dart-lang/language/blob/af07bfe46aa37275af19cf83fddeb161a1a4bada/resources/type-system/flow-analysis.md)? It does not look so to me. `instance check` uses `promote(E, T, M)`, which requires `T <: S`. In this case `Object` is not a subtype of `A?`, so no promotion.

**Comment by leafpetersen** [comment]
@scheglov I agree with your interpretation.  I would expect that any of the following would work:
  - `a is! Null`
  - `a is A`
  - `a != null`

But `a is Object` is not a promotable instance check.

**Comment by sgrekhov** [comment]
Yes, the test was not quite correct. For the following code

```dart
class A {
}
class C extends A {}

test(var a, C c) {
  if (a is Object) {
    a?.toString();              //# 01: static type warning
    a?..toString();             //# 02: static type warning
    a ?? c;                     //# 03: static type warning
    a ??= c;                    //# 04: static type warning
  }
}

main() {
  A? a = A();
  C c = C();
  test(a, c);
}
```
all warnings are reported as expected. So, I believe, this issue can be closed
