### ISSUE TITLE
NNBD. No error if factory constructor returns a nullable type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39712]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) 

> It is an error if the type of the value returned from a factory constructor is not a subtype of the class type associated with the class in which it is defined (specifically, it is an error to return a nullable type from a factory constructor for any class other than Null).

```dart
class A {
  A() {}

  factory A.factoryA() {
    C? c = new C();
    return c;
  }
}
class C extends A {
}

main() {
  A a = new A.factoryA();
}
```
The code above produces an error in analyzer (correct) and no issues in dart with --enable-experiment=non-nullable option (wrong)

Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by stefantsov** [comment]
I believe this was fixed by https://github.com/dart-lang/sdk/commit/c85979a28099c021b901772c2d7c715b2f9423ae.
