### ISSUE TITLE
Passing extended struct to c++ function

### ISSUE THREAD

**Issue by BissacM** [dart-lang/sdk#39718]
Hello.

I have this c++ Struct 
![image](https://user-images.githubusercontent.com/15155243/70454618-67bb0780-1ab3-11ea-81be-5ffd8c71db95.png)

And also a c++ function with the above struct paramter.
![image](https://user-images.githubusercontent.com/15155243/70454747-a224a480-1ab3-11ea-90a8-d209d011d2ad.png)

When trying to use the dart:ffi to call this function from a flutter plugin the VM raising an error
![image](https://user-images.githubusercontent.com/15155243/70454881-ed3eb780-1ab3-11ea-99e6-7ccbc8ceb70c.png)

I defined the function in this way
![image](https://user-images.githubusercontent.com/15155243/70454954-0a738600-1ab4-11ea-8c58-1c08a9b4ef22.png)

And the DummyStruct looks like this
![image](https://user-images.githubusercontent.com/15155243/70455001-25de9100-1ab4-11ea-9f44-fae80cf9c2e2.png)

The call to the function is
![image](https://user-images.githubusercontent.com/15155243/70455140-6d651d00-1ab4-11ea-8b22-1d3af4de15da.png)

Is there anything I'm doing wrong?

* Dart SDK Version
Flutter 1.12.16 • channel dev • git@github.com:flutter/flutter.git
Framework • revision 37f9c54116 (12 days ago) • 2019-11-27 11:33:38 -0800
Engine • revision fad1b23c42
Tools • Dart 2.7.0

* Using Windows

**Comment by dcharkes** [comment]
@BissacM Thanks for reporting.

Unfortunately, we do not support passing structs by value to functions yet. We are planning to add this in the future, exactly in the way that you tried to use it.

We're already tracking the feature in of https://github.com/dart-lang/sdk/issues/36730, I'm closing this duplicate issue.
