### ISSUE TITLE
dart2js: delete the old rti

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39733]
- [x] Remove force_old_rti argument.
- [x] Ignore `--use-old-rti` on dart2js command line.
- [x] Re-purpose 'rti' bots.
- [x] Re-purpose 'dart2js-x-*' golem targets.
- [x] Massive cleanup of dart2js and js_runtime codebase.

These can be started once D28 is final.

**Comment by natebosch** [comment]
We should consider https://github.com/dart-lang/sdk/issues/40535 blocking for this.

**Comment by vsmenon** [comment]
@sigmundch - consider bumping?

**Comment by franklinyow** [comment]
Can I move this to D29?

**Comment by sigmundch** [comment]
Yes, thanks - indeed, we want one stable release that allows `--use-old-rti`, but we should be deleting this in D29

**Comment by franklinyow** [comment]
@sigmundch  Can you move this to a proper milestone?  Need to close D29

**Comment by sigmundch** [comment]
I'm closing this instead :) - I believe this is now complete, @rakudrama did several cleanups already and I believe there is no more to be done.
