### ISSUE TITLE
Analysis server's "sort members" doesn't sort extension methods

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39739]
The following code is unchanged by "sort members":
```dart
extension E on int {
  int plus(int other) => this + other;
  
  int minus(int other) => this - other;
}
```
I would expect `minus` to be sorted before `plus`.

**Comment by FMorschel** [comment]
I tested this on Dart 3.5.3 and it seems to be functioning as expected now.

**Comment by srawlins** [comment]
Agree; works for me too.
