### ISSUE TITLE
required named arguments support in dart2js

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39730]
* [ ] Compiler model
    - [ ] FunctionType has new map for required named arguments.
    - [ ] Compile-time subtype test incorporates required named arguments.
    - [ ] FunctionType is properly serialized.
 * [ ] Runtime support
   - [ ] The call selector for required arguments is the same as optional arguments (a subclass can override with a required argument 'promoted' to optional, so it needs to be consistent).
   - [ ] Recipe parsing should interpret two 'bags' as specifying the required followed by optional named parameters.  Example: `"int(int,{req:int}{opt:int})"`, `"int({req:int}{})"`.
   - [ ] Subtype check modified.
   - [ ] `Function.apply` metadata needs to be emitted to specify which parameters are required. This can be similar to the default values.
   - [ ] `Function.apply` needs to be modified to use the required parameter metadata to reject missing required arguments.
 * [ ] Filter stubs so that stubs are generated only for selectors that 'expect' the required arguments (i.e. omit stubs that would 'default' a missing required argument).
   - [ ] On methods.
   - [ ] On closure `call` methods.
   - [ ] On tear-off `call`-to-selector mapping.

@Markzipan is currently looking into this.

**Comment by sigmundch** [comment]
FYI - @Markzipan  - I adjusted the list above with edits suggested by @rakudrama

I initially thought we needed to modify `CallStructure` under `universe`, but @rakudrama corrects me that this is likely not needed.

**Comment by Markzipan** [comment]
No problem - but shouldn't we do a check in `signatureApplies` to ensure that all required named parameters in the `ParameterStructure` actually appears at the call site? The current check only ensures that the arguments are a subset of of the parameters.

**Comment by rakudrama** [comment]
Yes, `signatureApplies` probably does need modifying. I misunderstood the original work item to be an extension to the 'language' of `CallStructure`.

**Comment by franklinyow** [comment]
Any update on this?  Do we need this for un-forking?

**Comment by sigmundch** [comment]
No progress here, however, this item is not needed to unfork. It is necessary for the full support of NNBD, but not for weak-mode (default when we unfork). Because of that we have prioritized other work first.

**Comment by franklinyow** [comment]
Should we move this under #40106 since this is not blocking the unfork?

**Comment by sigmundch** [comment]
Good point - I just moved it to a new epic, rather than #40106, I'm using a new sub-epic that is specific to dart2js in #40762
