### ISSUE TITLE
dart2js: emit nullable types

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39731]
(tracking bug for any tasks related to emitting nnbd from dart2js)

* [x] restructure subtyping rules to follow the spec algorithm.
  - [x] rewrite subtyping rules to implement legacy semantics following the spec algorithm structure.
  - [x] fork the subtyping rules into a legacy version and an nnbd version.
  - [x] call the correct version of the subtyping rules.
  - [x] special case `null` on the LHS of a type test: https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-checks-and-weak-checking
* [x] normalize types
  - [x] in the RTI
  - [x] in the backend
* [x] add nullable types in the dart2js internal representation
  - [x] ensure `T extends Never` is correctly normalized
* [x] emit nullable type information in the backend.
  - [x] ensure backend types are `*`-erased before they are surfaced to the user.

@fishythefish - please feel free to edit this list and add anything that is worth tracking.

**Comment by srawlins** [comment]
Siggi did you accidentally label this with `analyzer-nnbd-migration`?

**Comment by sigmundch** [comment]
Yes, sorry - it's unfortunately the first auto-complete option when you type "nnbd", even though there is an nnbd label.
