### ISSUE TITLE
Kernel binary file should specify NNBD mode

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#39749]
In order to avoid loading incompatible kernel files in the same VM instance and to provide meaningful errors if this happens, the kernel binary file should specify in which NNBD mode it was generated by CFE, namely in one of 3 possible modes:

1) non-nullable experiment disabled
2) non-nullable experiment enabled
3) non-nullable experiment enabled with strong type checks

**Comment by jensjoha** [comment]
Data available with a314cff6ee03c86811692a8a254d0642962be876.
