### ISSUE TITLE
GZipDecoder bug

### ISSUE THREAD

**Issue by buuth** [dart-lang/sdk#39741]
dear Dart team, I think there is a bug with GZipDecoder, it cannot decode very small file. I compressed few 28 bytes files, then use GZipDecoder to unzip, but GZipDecoder failed. It's easy to reproduce. Kind regards

**Comment by julemand101** [comment]
Please fill out the details in your report and not just make a title. Also, please provide a way to reproduce such gzip file which are failing together with a sample program showing the problem.

I have tried to make a gzip file containing one byte (and another with 20 bytes) and both files can be decoded with the following code:
```
import 'dart:convert';
import 'dart:io';

void main() {
  File('input.gz')
      .openRead()
      .transform(GZipCodec().decoder)
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .forEach(print);
}
```

Without more details than "It's easy to reproduce" it is difficult to say what your problem is and if there are a bug in the SDK.

**Comment by vsmenon** [comment]
@buuth - note, I moved your title to the body.  Please provide an example.

**Comment by buuth** [comment]
First I'm sorry that did not fill an issue properly, there was some problems with browser plugins that hide all forms, except for the title.
[WSS.gz](https://github.com/dart-lang/sdk/files/3954328/WSS.gz)
I attached file that I could not un-gzip by GZipDecoder().decodeBytes (Android Lollipop).
If archive is little bit bigger, GZipDecoder().decodeBytes works fine.
Thanks

**Comment by julemand101** [comment]
The GZipDecoder class is not part of the Dart SDK but are instead part of this package:
https://pub.dev/packages/archive

Which has its own issue tracker:
https://github.com/brendan-duncan/archive/issues

I have tried reproduce your problem with Dart 2.7.0 and using both the archive and archive_io library but both works as expected:
```
import 'dart:io';
import 'package:archive/archive.dart';

void main() {
  print(GZipDecoder().decodeBytes(File('WSS.gz').readAsBytesSync()).toList());
  // [235, 23, 52, 1, 105, 96, 1, 0, 205, 204, 12, 64, 205, 204, 12, 64, 205, 204, 12, 64, 205, 204, 12, 64, 232, 3, 0, 0]
}
```
```
import 'dart:io';
import 'package:archive/archive_io.dart';

void main() {
  print(GZipDecoder().decodeBytes(File('WSS.gz').readAsBytesSync()).toList());
  // [235, 23, 52, 1, 105, 96, 1, 0, 205, 204, 12, 64, 205, 204, 12, 64, 205, 204, 12, 64, 205, 204, 12, 64, 232, 3, 0, 0]
}
```

**Comment by buuth** [comment]
@julemand101 
Thank you very much for spending time on this issue. I will create an Android app for reproducing this issue and post it in correct board.
Buu
