### ISSUE TITLE
Analyzer doesn't show nullable types

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#39743]
A test program which assigns an `int?` to an `int` (see below) prints out the following error message:

```
 error • A value of type 'int' can't be assigned to a variable of type 'int'. • /Users/leafp/tmp/test4.dart:15:11 • invalid_assignment
 ```

The error message should show that the type of `x` is `int?`.

```
void test() {
  int? x;
  int y = x;
}
```

cc @scheglov @stereotype441

**Comment by scheglov** [comment]
This has been fixed recently, I think in 1cc5d6927ad4e1565dd9f9e771479b3f3771abe9.
