### ISSUE TITLE
Migrator should call out nullable-only-because-of-subclasses as questionable

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#39756]
Take this pre-NNBD code:

```dart
class A {
  final String s = "x";
}
class C implements A {
  String get s => (1+1==2) ? "x" : null;
}
```

The migrator will make the subclass return a `String?`, since it sees a literal null is possible returned. Then it must make the superclass's field be typed `String?` to avoid an illegal override.

We'd like to start categorizing some changes like this as "questionable".

@stereotype441 wrrote:

> The heuristic for deciding where to issue such a warning could be something like "if a getter, field, or method is being migrated to have a nullable return type, and the only graph edges causing that nullable return type are coming from derived classes, and there is a concrete implementation in the base class, then issue the warning."

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
