### ISSUE TITLE
Function literals with arrow notation break non-nullability

### ISSUE THREAD

**Issue by rbehrends** [dart-lang/sdk#39750]
With the newly released 2.7.0 version, running the following program through dartanalyzer will make think that the closure returns an `int?` rather than an `int`.

```
$ cat test1.dart 
List<int> test(List<int> l) =>
  l.map((x) => 0).toList();
$ dartanalyzer --enable-experiment=non-nullable test1.dart
Analyzing test1.dart...
  error • A value of type 'List<int?> can't be returned from function 'test' because it has a return type of 'List<int>'. • test1.dart:2:3 • return_of_invalid_type
1 error found.
```

This does not happen if we avoid the `=>` notation for function literals.

```
$ cat test2.dart                                          
List<int> test(List<int> l) =>
  l.map((x) { return 0; }).toList();
$ dartanalyzer --enable-experiment=non-nullable test2.dart
Analyzing test2.dart...
No issues found!
```

While I tried it on macOS, it also happens if you paste the code snippets in the null safety dartpad, so it does not appear to be platform-specific.

**Comment by scheglov** [comment]
This was fixed in 7707c2a84c85aadb08ff625d4c30486b5f078bd2.
