### ISSUE TITLE
heap growth control causes Dart2JSCompileAll to degrade significantly

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#3975]
When heap growth control is turned off the dart2js compile all benchmark runs as follows:

Dart2JSCompileAll(RunTime): 702174

with heap growth control turned on the numbers are:

Dart2JSCompileAll(RunTime): 1428801

We expect a slight degradation but this seems pretty significant and seems to indicate that the heap growth policy heuristics needs some tweaking.

**Comment by iposva-google** [comment]
Stale.
