### ISSUE TITLE
Implementation of NNBD runtime checks for weak mode support

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39755]
List of tasks

- [x] Annotated NNBD Types in VM https://github.com/dart-lang/sdk/issues/38842
- [x] Infrastructure work in VM type objects for NNBD
- [x] Implementation of runtime checks for weak mode support
- [x] type equality intrinsics
- [ ] Check required named parameters in type tests
- [ ] Check required named parameters during resolution
- [x] Update inlined type testing code
- [x] Update type testing stubs

**Comment by a-siva** [comment]
Some tests that are currently failing related to this issue

language/nnbd/static_errors/unchecked_use_of_nullable_test/114
language/nnbd/static_errors/unchecked_use_of_nullable_test/74

**Comment by liamappelbe** [comment]
Looks like the functions that those 2 lines sit in are never actually called from main, so we're only getting compile time errors for those functions. I'll update the test to call them.

**Comment by a-siva** [comment]
I don't think we are done with this issue (please see the original description that lists the set of tasks needed).

**Comment by alexmarkov** [comment]
Type testing stubs in NNBD weak mode are enabled in bffc9d101e419e36417e6dff1ec17519f17a3add.

**Comment by alexmarkov** [comment]
According to the specification checking required parameters is not needed in weak mode.
So I'm tentatively closing this issue as done.

@crelier @liamappelbe @a-siva Please reopen if there is anything left to do for weak mode checks.
