### ISSUE TITLE
NNBD. Null-check operator is not supported by generic function type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39758]
Run the following code in the dartanalyzer version 2.8.0-dev.0.0
```dart
main() {
  Function? f1 = null;
  f1!(42); // ok

  Function? f2 = null;
  f2<int>!(42); // Numerous errors
}
```
Output is 
```
  error - The expression is nullable and must be null-checked before it can be used. - null_check_operator_A02_t01.dart:46:3 - unchecked_use_of_nullable_value
  error - The operator '<' isn't defined for the class 'Function'. - null_check_operator_A02_t01.dart:46:5 - undefined_operator
  error - A comparison expression can't be an operand of another comparison expression. - null_check_operator_A02_t01.dart:46:9 - equality_cannot_be_equality_operand
  error - Negation argument must have a static type of 'bool'. - null_check_operator_A02_t01.dart:46:11 - non_bool_negation_expression
4 errors found.
```
Expected result - no error in analyzer for the code above

**Comment by vsmenon** [comment]
@leafpetersen @lrhn @eernstg - could one of you please confirm that the above should analyze without error?

**Comment by eernstg** [comment]
The syntax `f1!(42)` is of the form `<primary><selector><selector>` and should be accepted, and `f1!` is an expression with static type `Function` so it should be allowed to invoke it. Of course, no checks apply for the types of the actual arguments, so it's all OK. This means that it is a bug to report `unchecked_use_of_nullable_value`.

For `f2<int>!(42)`, there is no derivation (`<int>` is not a selector, but it would fit together with `(42)` and form the selector `<int>(42)`, derived via `<argumentPart>`). So it's OK to report a bunch of errors as parsing fails and is retried with some recovery steps (that we don't specify). However, `f2!<int>(42)` would be a relevant test.

**Comment by eernstg** [comment]
Tried this:

```dart
main() {
  Function? f1 = null;
  f1!(42); // ok

  Function? f2 = null;
  f2!<int>(42); // Numerous errors
}
```

With a fresh analyzer from commit 4b5d757beabe6c7f691be7076ac8ecd5f47cc1d7 we get the following response:

```
ERROR|SYNTACTIC_ERROR|EQUALITY_CANNOT_BE_EQUALITY_OPERAND|/usr/local/google/home/eernst/lang/dart/scratch/201912/n018.dart|6|10|1|A comparison expression can't be an operand of another comparison expression.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_OPERATOR|/usr/local/google/home/eernst/lang/dart/scratch/201912/n018.dart|6|6|1|The operator '<' isn't defined for the class 'Function'.

```

The common front end is unhappy as well:

```
n018.dart:6:10: Error: A comparison expression can't be an operand of another comparison expression.
Try putting parentheses around one of the comparisons.
  f2!<int>(42); // Numerous errors
         ^
n018.dart:6:6: Error: The method '<' isn't defined for the class 'Function?'.
 - 'Function' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named '<'.
  f2!<int>(42); // Numerous errors
     ^
```

**Comment by sgrekhov** [comment]
@eernstg thank you. #39776 for CFE

**Comment by scheglov** [comment]
Analyzer can analyze the following code, slightly different than the original.
A warning is reported:
```
warning: The '!' will have no effect because the target expression cannot be null. (unnecessary_non_null_assertion at [test] bin/test.dart:9)
```

```dart
Object? foo(int i) => "Lily was here";
Object? bar<T>(T t) => 42;

main() {
  Function? f1 = foo;
  f1!(42);  // Ok

  Function f2 = bar;
  f2!<int>(42); // Error, see below
}
```

**Comment by scheglov** [comment]
I opened https://github.com/dart-lang/co19/issues/513 to track fixing the co19 test.
