### ISSUE TITLE
TFA's Join static type isn't used

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39768]
The `Join` statement carries a static type which should constrain the result of the join. However, it doesn't appear to be used in `Join.apply`. Is this intentional?

/cc @alexmarkov

**Comment by alexmarkov** [comment]
> However, it doesn't appear to be used in Join.apply. Is this intentional?
@sjindel-google Yes, that's intentional.

There is a separate statement, `Narrow`, which narrows values using a type (intersects types). `Join` is supposed to calculate union.

`Join.staticType` is only used to break loops when building summary.

**Comment by sjindel-google** [comment]
Understood, thanks!

**Comment by Liujingguang** [comment]
class Person {
  XxxBean bean;
  List<XxxBean> listBean;
}

class XxxBean {
  String name;
  String email;
}


By modifying the dill file, I insert the fromjson() method for the Person class and the XxxBean class as follows:

class Person {
  XxxBean bean;
  List<XxxBean> listBean;

  dynamic fromJson(Map<String, dynamic> json) {
    bean = json['bean'] != null ? XxxBean().fromJson(json['bean']) : null;
    if (json['listBean'] != null) {
      listBean = List<XxxBean>();
      json['listBean'].forEach((v) {
        listBean.add(XxxBean().fromJson(v));
      });
    }
    return this;
  }
}

class XxxBean {
  String name;
  String email;

  dynamic fromJson(Map<String, dynamic> json) {
    name = json['aaa'];
    email = json['bbb'];
    return this;
  }
}

Problems I encountered in release mode：

Person().bean.name; // is ok
Person().listBean[0]; // is ok
Person().listBean[0].name; // is error: Attempt to execute code removed by Dart AOT compiler (TFA)。

why Person().listBean[0] is OK，but Person().listBean[0].name is error.
