### ISSUE TITLE
TFA doesn't analyze List constructor's type parameter

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39769]
Related to #39768

TFA will analyze the result of the code `new List<int>(10)` as `_T (dart.core::_List)`. Notably, the type argument is lost because the `_List` constructor is declared native and the return type annotation cannot specify type arguments.

This eventually causes poor analysis of values read out of the list.

/cc @alexmarkov @mkustermann @mraleph

**Comment by sjindel-google** [comment]
It seems that the underlying issue is the lack of type argument constraints on `ConeType`. Otherwise, we could narrow the concrete type declared in the `@pragma` by the static return type.

**Comment by alexmarkov** [comment]
We currently narrow native's return type using `TypeCheck` which should handle type arguments:

https://github.com/dart-lang/sdk/blob/80467ce51e3d49c01ab43b016d9f7f8d8bb1a3c2/pkg/vm/lib/transformations/type_flow/summary_collector.dart#L474-L485

We don't do this if return type is concrete (e.g. it comes from pragma). So, we can either
1. extend pragma syntax to specify type arguments,
2. remove pragma to rely on static type entirely, or
3. remove `if (type is! ConcreteType)` condition to do this narrowing even if concrete type is specified and see what would happen.

**Comment by sjindel-google** [comment]
I tried solution (3), but it still doesn't work because we perform the `TypeCheck` by taking the `fromStaticType` of the `RuntimeType` and intersecting that with the annotated type.

However, `fromStaticType` produces a `ConeType`, and they type arguments are then dropped.

I think solution (2) has the same issue.

I'm trying solution (1) now.

**Comment by sjindel-google** [comment]
(1) doesn't work either because `_List<E>` is not a constant and therefore cannot be passed as an argument to the pragma.

**Comment by Liujingguang** [comment]
class Person {
XxxBean bean;
List listBean;
}

class XxxBean {
String name;
String email;
}

By modifying the dill file, I insert the fromjson() method for the Person class and the XxxBean class as follows:

class Person {
XxxBean bean;
List listBean;

dynamic fromJson(Map<String, dynamic> json) {
bean = json['bean'] != null ? XxxBean().fromJson(json['bean']) : null;
if (json['listBean'] != null) {
listBean = List();
json['listBean'].forEach((v) {
listBean.add(XxxBean().fromJson(v));
});
}
return this;
}
}

class XxxBean {
String name;
String email;

dynamic fromJson(Map<String, dynamic> json) {
name = json['aaa'];
email = json['bbb'];
return this;
}
}

Problems I encountered in release mode：

Person().formJson({...}).bean.name; // is ok
Person().formJson({...}).listBean[0]; // is ok
Person().formJson({...}).listBean[0].name; // is error: Attempt to execute code removed by Dart AOT compiler (TFA)。

why Person().formJson({...}).listBean[0] is ok，but Person().formJson({...}).listBean[0].name is error?

**Comment by alexmarkov** [comment]
@Liujingguang could you dump a dill file before and after your modification (via `pkg/vm/tool/dump_kernel foo.dill foo.txt`), and post relevant snippets here?

It sounds like you're doing a transformation of a dill file after type flow analysis (TFA) and tree shaking. In such case, TFA is not aware of the new code you're injecting in the modified dill file, and it may optimize out code assuming that instances of XxxBean are never created (if they're created only in the injected fromJson()). Consider running your transformation before TFA, or annotating XxxBean with `@pragma("vm:entry-point")` and suppress tree shaking.

**Comment by Liujingguang** [comment]
class Person extends tex::_Person&Object&DataParseByAop {
    field tex::XxxBean bean = null;
    @#C51
    field core::List<tex::XxxBean> listBean = null;
    synthetic constructor •() → tex::Person
      : super tex::_Person&Object&DataParseByAop::•()
      ;
    method fromJson(core::Map<core::String, dynamic> json) → dynamic {
          this.{tex::Person::bean} = _in::unsafeCast<tex::XxxBean>(!saf::safeParse(json, <core::String>["bean"]).{core::Object::==}(null) ?{dynamic} new tex::XxxBean::•().{dat::DataParseByAop::fromJson}(saf::safeParse(json, <core::String>["bean"]) as{TypeError} core::Map<core::String, dynamic>) : this.{tex::Person::bean});
      if(!saf::safeParse(json, <core::String>["listBean"]).{core::Object::==}(null)) {
        this.{tex::Person::listBean} = core::_GrowableList::•<tex::XxxBean>(0);
        (saf::safeParse(json, <core::String>["listBean"]) as core::List<dynamic>).{core::Iterable::forEach}((dynamic v) → core::Null {
          this.{tex::Person::listBean}.{core::List::add}(_in::unsafeCast<tex::XxxBean>(new tex::XxxBean::•().{dat::DataParseByAop::fromJson}(v as{TypeError} core::Map<core::String, dynamic>)));
        });
      }
      return this;
    }


I annotate XxxBean with @pragma('vm:entry-point') is not ok, but i annotate List<XxxBean> listBean with @pragma('vm:entry-point') is ok. it likes this:
class Person with DataParseByAop {
  XxxBean bean;

  @pragma('vm:entry-point')
  List<XxxBean> listBean;
}

but I don't know why?

**Comment by alexmarkov** [comment]
TFA does global analysis and it needs to see the whole program. Your transformation introduces a new code which was not seen by TFA. Tree shaking transformation performed by TFA removes code which was not used by the analyzed program. However, the new code which was injected by your transformation uses `Person.listBean` and `XxxBean` in a new way (not seen by TFA). This might be a new call to the setter `Person.listBean` with `_GrowableList<XxxBean>` argument. Without seeing that call TFA may conclude that `Person.listBean[0]` is never an instance of XxxBean and it may remove `XxxBean.name` if there are no other uses.

As a workaround, you can annotate all classes created by injected code, as well as all methods, constructors and fields used by injected code with `@pragma('vm:entry-point')` to tell TFA that they could be used by the code not seen by TFA. Usually these pragmas are used to annotate Dart classes and members used from C/C++ code, but they should work for injected Dart code as well (unless your transformation adds new classes which extend/implement/mix-in existing classes - in such case `@pragma('vm:entry-point')` would not be enough).

A better solution would be to perform your transformation before TFA. In such case TFA will be able to analyze the transformed program and see injected code.

**Comment by Liujingguang** [comment]
> TFA does global analysis and it needs to see the whole program. Your transformation introduces a new code which was not seen by TFA. Tree shaking transformation performed by TFA removes code which was not used by the analyzed program. However, the new code which was injected by your transformation uses `Person.listBean` and `XxxBean` in a new way (not seen by TFA). This might be a new call to the setter `Person.listBean` with `_GrowableList<XxxBean>` argument. Without seeing that call TFA may conclude that `Person.listBean[0]` is never an instance of XxxBean and it may remove `XxxBean.name` if there are no other uses.
> 
> As a workaround, you can annotate all classes created by injected code, as well as all methods, constructors and fields used by injected code with `@pragma('vm:entry-point')` to tell TFA that they could be used by the code not seen by TFA. Usually these pragmas are used to annotate Dart classes and members used from C/C++ code, but they should work for injected Dart code as well (unless your transformation adds new classes which extend/implement/mix-in existing classes - in such case `@pragma('vm:entry-point')` would not be enough).
> 
> A better solution would be to perform your transformation before TFA. In such case TFA will be able to analyze the transformed program and see injected code.

Thank you very much. You have provided me with a new idea. I will analyze it before TFA. I will try it according to this idea. Thanks again.

**Comment by Liujingguang** [comment]
Thank you very much. You have provided me with a new idea. I will analyze it before TFA. I will try it according to this idea. Thanks again.
