### ISSUE TITLE
Analyzer support for language versions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39762]
This includes:
- support for the new JSON package format
- using language version info in the JSON package format to determine whether to analyze a library in NNBD opt-in or opt-out mode
- allowing a single library's opt-in / opt-out status to be overridden by an appropriately formatted comment at the top of the file (note: there are corner cases for part files under this scenario)
- appropriate fallback logic for analyzing projects that lack a JSON package file

**Comment by vsmenon** [comment]
@stereotype441 - any update on this?  Does it need an owner?

**Comment by stereotype441** [comment]
Still to do:
- Make sure package resolution is hooked up in all the right places
- fallback logic for analyzing projects that lack a JSON package file (@leafpetersen, @scheglov had some questions about what the correct behavior is in this case--which version should we assume if there is no JSON package file?)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131443
https://dart-review.googlesource.com/c/sdk/+/131444

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131948

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/132744
