### ISSUE TITLE
Unexpected NNBD error on function type

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39773]
In NNBD, it's illegal to have a *declaration* of a function with an optional parameter of a non-nullable type that doesn't have a default value. This is bad:

```dart
foo([int i]) {} // Bad!
```

However, "default-value-ness" is not part of a function's *type*, so it should be valid to have a function *type* with an optional non-nullable parameter. This must be allowed, otherwise there is no way to write the type of a function with an optional parameter, since function types can't have default values. So this should be OK:

```dart
main() {
  Function([int i]) f;
}
```

However, if I analyze this with NNBD enabled, I get:

```
Analyzing temp.dart...
  error • The parameter '?' can't have a value of 'null' because of its type, but no non-null default value is provided. • temp.dart:2:13 • invalid_optional_parameter_type
```

That error shouldn't be shown.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/129142
