### ISSUE TITLE
NNBD. No error when increasing List length

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39777]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#core-library-changes)

> Calling the .length setter on a List with element type E with an argument greater than the current length of the list is a runtime error unless Null <: E.

In fact, there is no such error
```dart
main() {
  List<int> list = [3, 14];
  list.length = 3;
  print(list); // prints [3, 14, null]
}
```
Tested on Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

**Comment by johnniwinther** [comment]
This probably requires special support in the backends.

**Comment by leafpetersen** [comment]
> This probably requires special support in the backends.

I don't think it requires backend support per se, just correct patch file code.

**Comment by alexmarkov** [comment]
In NNBD strong mode (with `--enable-experiment=non-nullable --null-safety`) example above produces a run-time error

```
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      List.length= (dart:core-patch/growable_array.dart:127:12)
```

In weak checking mode Null <: int, so no error is produced.
