### ISSUE TITLE
Prefer local identifiers in auto-complete

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39771]
I've noticed since (I think) the new ML-based auto-complete was added that IntelliJ will now suggest identifiers that are defined in libraries I have not even imported. That can be a delightful feature in some cases. But when I've typed the first couple of letters of a local variable declared on a previous line, it's *really* likely that *that's* the identifier I'm typing, and I didn't decide to turn my program into a web app:

<img width="658" alt="Screen Shot 2019-12-12 at 1 12 54 PM" src="https://user-images.githubusercontent.com/46275/70749625-95859380-1ce1-11ea-9dd3-0a24d9d77991.png">

In fact, I find myself so accustomed to auto-complete naturally suggesting my local variable that I often hit tab to accept the completion before realizing it picked the wrong thing. Then if I'm not careful to immediately undo it, I end up with a dangling import to an unused library that I need to remember to scroll up to and delete.

Is it possible for auto-complete to prefer in-scope identifiers over the ML results?

(In cases where I don't want to refer to a local identifier, or where there are multiple options, the ML has been a wonderful improvement.)

**Comment by bwilkerson** [comment]
Sorry for the long delay in responding. I believe the issue you're seeing is that IntelliJ re-orders the list that the server sends using several heuristics. One of those heuristics is that exact matches should appear first in the list.

@jwren Is there any way to disable IntelliJ's re-sorting behavior?
