### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by johnnyhawk02** [dart-lang/sdk#39799]
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\main_web_entrypoint.ddc.js --source-map --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\random_word_list.ddc.dill=packages/webmakaton/random_word_list --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\functions.ddc.dill=packages/webmakaton/functions --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\imagePaths.ddc.dill=packages/webmakaton/imagePaths --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\word_list.ddc.dill=packages/webmakaton/word_list --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\meta\meta.ddc.dill=packages/meta/meta --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\foundation.ddc.dill=packages/flutter/foundation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\vector_math\hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\physics.ddc.dill=packages/flutter/physics --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\collection.ddc.dill=packages/collection/collection --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\gestures.ddc.dill=packages/flutter/gestures --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\painting.ddc.dill=packages/flutter/painting --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\semantics.ddc.dill=packages/flutter/semantics --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\animation.ddc.dill=packages/flutter/animation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\rendering.ddc.dill=packages/flutter/rendering --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\widgets\actions.ddc.dill=packages/flutter/src/widgets/actions --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\widgets.ddc.dill=packages/flutter/widgets --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter_web_plugins\flutter_web_plugins.ddc.dill=packages/flutter_web_plugins/flutter_web_plugins --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter_web_image_picker\flutter_web_image_picker.ddc.dill=packages/flutter_web_image_picker/flutter_web_image_picker --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\cupertino\action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\cupertino.ddc.dill=packages/flutter/cupertino --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\material.ddc.dill=packages/flutter/material --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\widgets\image_and_text_02.ddc.dill=packages/webmakaton/widgets/image_and_text_02 --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\main.ddc.dill=packages/webmakaton/main --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\generated_plugin_registrant.ddc.dill=packages/webmakaton/generated_plugin_registrant --packages=file:///C:/Users/johnn/AppData/Local/Temp/kernel_builder_d51672f8-1f78-11ea-8edc-80913360a156/.packages --module-name=packages/webmakaton/main_web_entrypoint --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=C:\Users\johnn\AppData\Local\Temp\ddk_builder_d51672f7-1f78-11ea-8edc-80913360a156\used_inputs.txt package:webmakaton/main_web_entrypoint.dart
    dart --version: 2.7.0-dev.2.1.flutter-a4d799c402 (Mon Dec 2 23:13:10 2019 +0000) on "windows_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:280:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:45:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:404:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Error compiling dartdevc module:webmakaton|lib/main.ddc.js

Failed to initialize incremental compiler, throwing away old state.

This is likely a result of https://github.com/dart-lang/sdk/issues/38102, if
you are consistently seeing this problem please see that issue.

The specific exception that was encountered was:

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:280:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:45:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:404:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\main.ddc.js --source-map --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\imagePaths.ddc.dill=packages/webmakaton/imagePaths --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\meta\meta.ddc.dill=packages/meta/meta --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\foundation.ddc.dill=packages/flutter/foundation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\vector_math\hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\physics.ddc.dill=packages/flutter/physics --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\collection\collection.ddc.dill=packages/collection/collection --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\gestures.ddc.dill=packages/flutter/gestures --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\painting.ddc.dill=packages/flutter/painting --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\semantics.ddc.dill=packages/flutter/semantics --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\animation.ddc.dill=packages/flutter/animation --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\rendering.ddc.dill=packages/flutter/rendering --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\widgets\actions.ddc.dill=packages/flutter/src/widgets/actions --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\widgets.ddc.dill=packages/flutter/widgets --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\src\cupertino\action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\cupertino.ddc.dill=packages/flutter/cupertino --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter\material.ddc.dill=packages/flutter/material --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\widgets\image_and_text_02.ddc.dill=packages/webmakaton/widgets/image_and_text_02 --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter_web_plugins\flutter_web_plugins.ddc.dill=packages/flutter_web_plugins/flutter_web_plugins --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\flutter_web_image_picker\flutter_web_image_picker.ddc.dill=packages/flutter_web_image_picker/flutter_web_image_picker --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\random_word_list.ddc.dill=packages/webmakaton/random_word_list --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\functions.ddc.dill=packages/webmakaton/functions --summary=C:\Users\johnn\AppData\Local\Temp\scratch_spaced76cf232-1f77-11ea-8edc-80913360a156\packages\webmakaton\word_list.ddc.dill=packages/webmakaton/word_list --packages=file:///C:/Users/johnn/AppData/Local/Temp/kernel_builder_d51672f5-1f78-11ea-8edc-80913360a156/.packages --module-name=packages/webmakaton/main --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=C:\Users\johnn\AppData\Local\Temp\ddk_builder_d51672f4-1f78-11ea-8edc-80913360a156\used_inputs.txt package:webmakaton/main.dart
    dart --version: 2.7.0-dev.2.1.flutter-a4d799c402 (Mon Dec 2 23:13:10 2019 +0000) on "windows_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:280:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:45:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:404:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Failed after 989ms
Finished with error: Failed to build application for the Web.

**Comment by vsmenon** [comment]
Instance of https://github.com/dart-lang/sdk/issues/38102
