### ISSUE TITLE
Ambiguous List toString

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#39798]
If you `print` a List with Dart, I believe it calls:

https://api.dartlang.org/stable/dart-collection/ListMixin/toString.html

which is implemented by:

https://api.dartlang.org/stable/dart-collection/IterableBase/iterableToFullString.html

which:

> Converts each elements to a string, and separates the results by `", "`

However this can product ambiguous output:

~~~dart
main() {
   var a1 = ['sun', 'mon, tue'];
   print(a1); // [sun, mon, tue]
}
~~~

JavaScript has a similar problem:

~~~js
var a1 = ['sun', 'mon,tue'];
var s1 = a1.toString();
console.log(s1); // sun,mon,tue
~~~

but different runtimes have solved it, for example Node:

~~~js
var a1 = ['sun', 'mon,tue'];
console.log(a1); // [ 'sun', 'mon,tue' ]
~~~

and Firefox:

~~~js
var a1 = ['sun', 'mon,tue'];
var s1 = a1.toSource();
console.log(s1); // ["sun", "mon,tue"]
~~~

and also other languages like Python:

~~~py
a1 = ['sun', 'mon, tue']
print(a1) # ['sun', 'mon, tue']
~~~

Go:

~~~go
package main
import "fmt"
func main() {
   a1 := []string{"sun", "mon, tue"}
   fmt.Printf("%q\n", a1) // ["sun" "mon, tue"]
}
~~~

PHP:

~~~php
$a1 = ['sun', 'mon, tue'];
var_export($a1); # array(0 => 'sun', 1 => 'mon, tue')
~~~

Nim:

~~~nim
var a1 = ["sun", "mon, tue"]
echo a1 # ["sun", "mon, tue"]
~~~

**Comment by cup** [comment]
Workaround:

~~~dart
import 'dart:convert';
main() {
   var a1 = ['sun', 'mon,tue'];
   var s1 = jsonEncode(a1);
   print(s1); // ["sun","mon,tue"]
}
~~~

However fails in some cases:

~~~dart
import 'dart:convert';
main() {
   var a1 = ['sun', new DateTime.now()];
   var s1 = jsonEncode(a1);
   print(a1);
   /* Unhandled exception: Converting object to an encodable object failed:
   Instance of 'DateTime' */
}
~~~

**Comment by lrhn** [comment]
The main issue here is that there is only one intended purpose for `List.toString`, which is debugging. You should never use `toString` on a list for any other purpose than having a human look at it.
*However*, we can't actually prevent anyone from depending on the current behavior, and, e.g.,  parse the result of `toString`. Which means that it's a breaking change to change the current behavior. We are unlikely to be able to do so at this point.

So, not unsympathetic to the issue, but no current plans to change the current behavior.

**Comment by cup** [comment]
@lrhn I have thought about this some more, and it seems the root issue is with
Strings, not Lists. As if you have a List of numbers or other types, everything
prints out in an unambiguous way.

However Dart seems to have no method to "escape" or "quote" a string. Like
Python:

~~~py
s1 = 'sunday'
s2 = repr(s1)
print(s1, s2) # sunday 'sunday'
~~~

or PHP:

~~~php
$s1 = 'sunday';
$s2 = var_export($s1, true);
echo $s1, ' ', $s2; # sunday 'sunday'
~~~

or Ruby:

~~~rb
s1 = 'sunday'
s2 = s1.inspect
puts s1, s2 # sunday "sunday"
~~~

**Comment by lrhn** [comment]
Indeed, there is only `toString`, which does double duty of creating debug representations and actually converting something to a string. And because `print` converts things to strings before printing them, the `toString` of a string cannot return anything but itself. 

If there had been a `toDebugString`, then it would be easier to have two different behaviors of strings.

We could add a `repr`-like function which would recognize collections and provide the `repr` of the elements instead of the `toString`, and represent strings as quoted. Making it a virtual `toDebugString`, which defaults to calling `toString`, would be a potential approach, but it's not clear that it's worth the effort. It's more convenient when debug tools choose a representation that fit their output format. For example, the `console.log` of browser scripts makes the elements of a list *clickable*. That shows an understanding of the underlying object structure, it's not just printing a string.

**Comment by cup** [comment]
@lrhn I noticed another issue. `File` objects also make no attempt at
unambiguous output. They just wrap their contents in single quotes and hope for
the best:

~~~
$ ls
app.dart  "mon ' tue.txt"   sun.txt

$ cat app.dart
import 'dart:io';
main() {
   var o1 = new Directory('.');
   var a1 = o1.listSync();
   print(a1);
}

$ dart app.dart
[File: '.\app.dart', File: '.\mon ' tue.txt', File: '.\sun.txt']
~~~

**Comment by cup** [comment]
Another option for unambiguous output is URI encoding:

~~~dart
main() {	
   var s1 = 'sunday monday';
   var s2 = Uri.encodeFull(s1);
   print(s2); // sunday%20monday
}
~~~

**Comment by lrhn** [comment]
We have no plan to change `List.toString` at the current time. It returns, effectively, `"[${this.join(",")}]"`. It has to convert its elements to strings, and it does so by calling `toString`, but that also means that a string element itself is included without any quotes. It's not a `toSource()`.

For any other purpose, users will have to make a purpose specific function to create a representation of the list.
(To create a quoted version of a string, it's possible to use `jsonEncode`.)
