### ISSUE TITLE
The method 'FfiTrampoline' was called on null

### ISSUE THREAD

**Issue by umberto-sonnino** [dart-lang/sdk#39804]
I'm trying to run a C library with the new FFI interface, but I'm getting the following error:
```
Unhandled exception:
NoSuchMethodError: The method 'FfiTrampoline' was called on null.
Receiver: null
Tried calling: FfiTrampoline()
#0      FfiTrampoline (dart:ffi)
#1      main (file://~/Proj/triangle_ffi/triangle_ffi.dart:89:14)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

The code I'm trying to run is available here: [triangle_ffi](https://github.com/umberto-sonnino/triangle_ffi/tree/master). It includes a C test file `dlOpenTest.c` that runs the same library and runs the same function. 
A `makefile` that builds the `dylib` library and the C test is included in the `/c` folder.

Running on macOSX 10.14.6 with Dart VM version: 2.8.0-dev.0.0 on "macos_x64".

**Comment by vsmenon** [comment]
Do you believe there is a bug in the Dart FFI itself?  If so, can you let us know what/why?

If you are looking for help with your own code, you're probably better off asking on one of these channels:

https://dart.dev/community#join-the-conversation

**Comment by umberto-sonnino** [comment]
My bad, I was trying to use `null` instead of `nullptr`..!
