### ISSUE TITLE
[vm] SIMD binary ops are never inlined in AOT

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#39806]
SIMD ops `+`, `-`, `*` and `/` are always compiled as `StaticCalls` in the AOT pipeline.

This causes terrible performance.

/cc @mraleph @mkustermann @sstrickl

**Comment by mkustermann** [comment]
I believe 7a1c91bda93d18dae39c04b5ae7c03cc21760c88 implemented this support. Is there anything remaining or can we close the issue?
