### ISSUE TITLE
NNBD. No error if local late final wariable is written to twice

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39802]
The code below works without any errors
```dart
main() {
  late final String l;
  l = "Lily was here";
  print(l);
  l = "Show must go on";
  print(l);
}
```
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables)

> Let D be a late and final local variable declaration named v without an initializing expression. It is a run-time error, throwing an instance of LateInitializationError, to assign a value to v if a value has previously been assigned to v.

So, there must be a `LateInitializationError` at a runtime on  = "Show must go on";

**Comment by alexmarkov** [comment]
This example now results in a compile-time error:
```
foo.dart:5:3: Error: Late final variable 'l' definitely assigned.
  l = "Show must go on";
  ^
```
