### ISSUE TITLE
dart:ffi: Explain Struct wrapping or not

### ISSUE THREAD

**Issue by derolf** [dart-lang/sdk#39808]
From the documentation of Struct it is unclear whether loading a Struct from a Pointer actually creates a Dart Wrapper-Object or if it is an intrinsic “hack” without additionally allocation.

**Comment by dcharkes** [comment]
It's a Dart wrapper object.

It roughly looks like the following.

```dart
MyStruct extends Struct {  // View on C memory.
  Pointer<MyStruct> _hiddenPointer; // Pointer to C memory.

  // Accessors for C memory
  int get x => _hiddenPointer.cast<Int64>().value;
  set x(int newValue) => _hiddenPointer.cast<Int64>().value = newValue;

  int get y => _hiddenPointer.offsetInBytes(8).cast<Int64>().value;
  set y(int newValue) => _hiddenPointer.offsetInBytes(8).cast<Int64>().value = newValue;
}
```

However, note that when we will add support for structs by value (https://github.com/dart-lang/sdk/issues/36730), we actually need to store the data in Dart memory:

```dart
MyStruct extends Struct { // View on Dart or C memory.
  _SomePointer _data; // Pointer<MyStruct> extends _SomePointer and TypedData extends _SomePointer.

  // ...
}

**Comment by dcharkes** [comment]
Note that when we implement the struct operation optimizations (https://github.com/dart-lang/sdk/issues/38648) the Dart optimizer might decide to not materialize the `MyStruct` object at all in the following code:

```dart
Pointer<MyStruct> p;
p.ref.x = 1;
```

The optimizer can turn this conceptually* into the following:

```dart
Pointer<MyStruct> p;
p.cast<Int64>().value = 1;
```

*The optimizer doesn't work on source code, but an intermediate representation. So showing an optimization on source code isn't fully accurate.

**Comment by Sunbreak** [comment]
A example: https://github.com/dart-lang/ffigen/issues/68#issuecomment-784866350
