### ISSUE TITLE
NNBD. No runtime error when reading local late variable without initializer expression

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39801]
According to the NNBD [specificztion](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables)

> A read of a field or variable which is marked as late which has not yet been written to causes the initializer expression of the variable to be evaluated to a value, assigned to the variable or field, and returned as the value of the read.
> 
> If there is no initializer expression, the read causes a runtime error to be thrown which is an instance of LateInitializationError

This works for non-local fields and variables but doesn't work for local ones
```dart
main() {
  late final String l1;
  late String l2;

  print(l1); // prints null
  print(l2); // prints null
}
```

Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

**Comment by alexmarkov** [comment]
Now VM prints compile-time errors:
```
foo.dart:5:9: Error: Late variable 'l1' without initializer is definitely unassigned.
  print(l1); // prints null
        ^^
foo.dart:6:9: Error: Late variable 'l2' without initializer is definitely unassigned.
  print(l2); // prints null
        ^^
```
