### ISSUE TITLE
Following tests fail with MissingCompileTimeError when run with NNBD enabled

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39813]
language/nnbd/static_errors/not_initialized_non_nullable_instance_field_test/13
language/nnbd/static_errors/not_initialized_non_nullable_instance_field_test/10
language/nnbd/static_errors/not_initialized_non_nullable_instance_field_test/09
language/nnbd/static_errors/not_initialized_non_nullable_instance_field_test/11
language/nnbd/static_errors/missing_default_value_for_parameter_test/08
language/nnbd/static_errors/missing_default_value_for_parameter_test/07
language/nnbd/static_errors/missing_default_value_for_parameter_test/06
language/nnbd/static_errors/not_initialized_non_nullable_instance_field_test/12
language/nnbd/static_errors/missing_default_value_for_parameter_test/04
language/nnbd/static_errors/missing_default_value_for_parameter_test/05
language/nnbd/static_errors/missing_default_value_for_parameter_test/01
language/nnbd/static_errors/missing_default_value_for_parameter_test/10
language/nnbd/static_errors/missing_default_value_for_parameter_test/02
language/nnbd/static_errors/missing_default_value_for_parameter_test/11
language/nnbd/static_errors/missing_default_value_for_parameter_test/03
language/nnbd/static_errors/not_assigned_local_initializer_test/01
language/nnbd/static_errors/missing_default_value_for_parameter_test/13
language/nnbd/static_errors/missing_default_value_for_parameter_test/14
language/nnbd/static_errors/missing_default_value_for_parameter_test/12
language/nnbd/static_errors/missing_default_value_for_parameter_test/09
language/nnbd/static_errors/nullable_function_types_test/02
language/nnbd/static_errors/not_assigned_local_initializer_test/08
language/nnbd/static_errors/nullable_function_types_test/04
language/nnbd/static_errors/nullable_function_types_test/00
language/nnbd/static_errors/nullable_function_types_test/01
language/nnbd/static_errors/default_list_constructor_test/01
language/nnbd/static_errors/default_list_constructor_test/03
language/nnbd/static_errors/default_list_constructor_test/02
language/nnbd/static_errors/default_list_constructor_test/04
language/nnbd/static_errors/unchecked_use_of_nullable_test/01
language/nnbd/static_errors/unchecked_use_of_nullable_test/00
language/nnbd/static_errors/unchecked_use_of_nullable_test/06
language/nnbd/static_errors/unchecked_use_of_nullable_test/07
language/nnbd/static_errors/unchecked_use_of_nullable_test/08
language/nnbd/static_errors/unchecked_use_of_nullable_test/09
language/nnbd/static_errors/unchecked_use_of_nullable_test/10
language/nnbd/static_errors/unchecked_use_of_nullable_test/16
language/nnbd/static_errors/unchecked_use_of_nullable_test/11
language/nnbd/static_errors/unchecked_use_of_nullable_test/13
language/nnbd/static_errors/unchecked_use_of_nullable_test/21
language/nnbd/static_errors/unchecked_use_of_nullable_test/19
language/nnbd/static_errors/unchecked_use_of_nullable_test/20
language/nnbd/static_errors/unchecked_use_of_nullable_test/22
language/nnbd/static_errors/unchecked_use_of_nullable_test/23
language/nnbd/static_errors/unchecked_use_of_nullable_test/26
language/nnbd/static_errors/unchecked_use_of_nullable_test/25
language/nnbd/static_errors/unchecked_use_of_nullable_test/17
language/nnbd/static_errors/unchecked_use_of_nullable_test/18
language/nnbd/static_errors/unchecked_use_of_nullable_test/28
language/nnbd/static_errors/unchecked_use_of_nullable_test/29
language/nnbd/static_errors/unchecked_use_of_nullable_test/25
language/nnbd/static_errors/unchecked_use_of_nullable_test/38
language/nnbd/static_errors/unchecked_use_of_nullable_test/27
language/nnbd/static_errors/unchecked_use_of_nullable_test/37
language/nnbd/static_errors/unchecked_use_of_nullable_test/41
language/nnbd/static_errors/unchecked_use_of_nullable_test/36
language/nnbd/static_errors/unchecked_use_of_nullable_test/43
language/nnbd/static_errors/unchecked_use_of_nullable_test/39
language/nnbd/static_errors/unchecked_use_of_nullable_test/42
language/nnbd/static_errors/unchecked_use_of_nullable_test/54
language/nnbd/static_errors/unchecked_use_of_nullable_test/53
language/nnbd/static_errors/unchecked_use_of_nullable_test/52
language/nnbd/static_errors/unchecked_use_of_nullable_test/57
language/nnbd/static_errors/unchecked_use_of_nullable_test/49
language/nnbd/static_errors/unchecked_use_of_nullable_test/50
language/nnbd/static_errors/unchecked_use_of_nullable_test/51
language/nnbd/static_errors/unchecked_use_of_nullable_test/55
language/nnbd/static_errors/unchecked_use_of_nullable_test/48
language/nnbd/static_errors/unchecked_use_of_nullable_test/60
language/nnbd/static_errors/unchecked_use_of_nullable_test/63
language/nnbd/static_errors/unchecked_use_of_nullable_test/64
language/nnbd/static_errors/unchecked_use_of_nullable_test/61
language/nnbd/static_errors/unchecked_use_of_nullable_test/66
language/nnbd/static_errors/unchecked_use_of_nullable_test/65
language/nnbd/static_errors/unchecked_use_of_nullable_test/69
language/nnbd/static_errors/unchecked_use_of_nullable_test/68
language/nnbd/static_errors/unchecked_use_of_nullable_test/70
language/nnbd/static_errors/unchecked_use_of_nullable_test/72
language/nnbd/static_errors/unchecked_use_of_nullable_test/67
language/nnbd/static_errors/unchecked_use_of_nullable_test/73
language/nnbd/static_errors/unchecked_use_of_nullable_test/82
language/nnbd/static_errors/unchecked_use_of_nullable_test/71
language/nnbd/static_errors/unchecked_use_of_nullable_test/80
language/nnbd/static_errors/unchecked_use_of_nullable_test/81
language/nnbd/static_errors/unchecked_use_of_nullable_test/83
language/nnbd/static_errors/unchecked_use_of_nullable_test/89
language/nnbd/static_errors/unchecked_use_of_nullable_test/90
language/nnbd/static_errors/unchecked_use_of_nullable_test/88
language/nnbd/static_errors/unchecked_use_of_nullable_test/91
language/nnbd/static_errors/unchecked_use_of_nullable_test/97
language/nnbd/static_errors/unchecked_use_of_nullable_test/93
language/nnbd/static_errors/unchecked_use_of_nullable_test/92
language/nnbd/static_errors/unchecked_use_of_nullable_test/100
language/nnbd/static_errors/unchecked_use_of_nullable_test/95
language/nnbd/static_errors/unchecked_use_of_nullable_test/103
language/nnbd/static_errors/unchecked_use_of_nullable_test/94
language/nnbd/static_errors/unchecked_use_of_nullable_test/104
language/nnbd/static_errors/unchecked_use_of_nullable_test/105
language/nnbd/static_errors/unchecked_use_of_nullable_test/101
language/nnbd/static_errors/unchecked_use_of_nullable_test/106
language/nnbd/static_errors/unchecked_use_of_nullable_test/107
language/nnbd/static_errors/unchecked_use_of_nullable_test/109
language/nnbd/static_errors/unchecked_use_of_nullable_test/108
language/nnbd/static_errors/unchecked_use_of_nullable_test/113
language/nnbd/static_errors/unchecked_use_of_nullable_test/112
language/nnbd/static_errors/unchecked_use_of_nullable_test/110
language/nnbd/static_errors/unchecked_use_of_nullable_test/111
language/nnbd/static_errors/unchecked_use_of_nullable_test/121
language/nnbd/static_errors/unchecked_use_of_nullable_test/120
language/nnbd/static_errors/unchecked_use_of_nullable_test/184
language/nnbd/static_errors/unchecked_use_of_nullable_test/186
language/nnbd/static_errors/unchecked_use_of_nullable_test/188
language/nnbd/static_errors/unchecked_use_of_nullable_test/190
language/nnbd/static_errors/unchecked_use_of_nullable_test/183
language/nnbd/static_errors/unchecked_use_of_nullable_test/185
language/nnbd/static_errors/unchecked_use_of_nullable_test/191
language/nnbd/static_errors/unchecked_use_of_nullable_test/193
language/nnbd/static_errors/unchecked_use_of_nullable_test/192
language/nnbd/static_errors/unchecked_use_of_nullable_test/187
language/nnbd/static_errors/unchecked_use_of_nullable_test/189
language/nnbd/static_errors/unchecked_use_of_nullable_test/200
language/nnbd/static_errors/not_assigned_local_if_then_test/none
language/nnbd/static_errors/nullable_supertype_test/05
language/nnbd/static_errors/not_assigned_local_try_catch_body_test/none
language/nnbd/static_errors/nullable_supertype_test/04
language/nnbd/static_errors/nullable_supertype_test/03
language/nnbd/static_errors/missing_required_argument_test/01
language/nnbd/static_errors/nullable_supertype_test/01
language/nnbd/static_errors/nullable_supertype_test/02
language/nnbd/static_errors/missing_required_argument_test/03
language/nnbd/static_errors/missing_required_argument_test/06
language/nnbd/static_errors/missing_required_argument_test/04
language/nnbd/static_errors/missing_required_argument_test/02
language/nnbd/static_errors/missing_required_argument_test/05
language/nnbd/static_errors/missing_required_argument_test/08
language/nnbd/static_errors/missing_required_argument_test/07
language/nnbd/static_errors/not_initialized_non_nullable_static_field_test/08
language/nnbd/static_errors/not_initialized_non_nullable_static_field_test/01
language/nnbd/static_errors/non_null_assertion_test/01
language/nnbd/static_errors/not_assigned_local_while_true_break_before_test/none
language/nnbd/static_errors/await_in_late_local_variable_initializer_test/02
language/nnbd/static_errors/export_legacy_symbol_test/01
language/nnbd/static_errors/await_in_late_local_variable_initializer_test/05
language/nnbd/static_errors/default_value_on_required_parameter_test/01
language/nnbd/static_errors/use_nnbd_sdk_test/04
language/nnbd/static_errors/use_nnbd_sdk_test/01
language/nnbd/static_errors/not_assigned_local_if_then_else_else_test/none
language/nnbd/static_errors/not_initialized_non_nullable_top_test/01
language/nnbd/static_errors/use_nnbd_sdk_test/06
language/nnbd/static_errors/not_initialized_non_nullable_top_test/08
language/nnbd/static_errors/not_assigned_local_if_then_else_then_test/none
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/00
language/nnbd/static_errors/late_final_field_with_const_constructor_test/03
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/06
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/04
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/12
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/08
language/nnbd/static_errors/unchecked_use_of_nullable_cascaded_test/16
language/nnbd/static_errors/nullable_in_on_clause_test/01
language/nnbd/static_errors/nullable_in_on_clause_test/02
language/nnbd/resolution/question_question_lub_test/01
language/nnbd/resolution/question_question_lub_test/02
language/nnbd/resolution/question_dot_index_produces_nullable_type_test/06
language/nnbd/resolution/question_dot_index_produces_nullable_type_test/08
language/nnbd/resolution/question_dot_index_produces_nullable_type_test/11
language/nnbd/resolution/question_dot_produces_nullable_type_test/03
language/nnbd/resolution/question_dot_index_produces_nullable_type_test/10
language/nnbd/resolution/question_dot_index_produces_nullable_type_test/12
language/nnbd/resolution/question_dot_produces_nullable_type_test/01
language/nnbd/resolution/question_dot_produces_nullable_type_test/04
language/nnbd/resolution/question_dot_produces_nullable_type_test/05
language/nnbd/resolution/question_dot_produces_nullable_type_test/06
language/nnbd/resolution/question_dot_produces_nullable_type_test/10
language/nnbd/resolution/question_dot_produces_nullable_type_test/09
language/nnbd/resolution/question_dot_produces_nullable_type_test/07
language/nnbd/resolution/question_dot_produces_nullable_type_test/08

**Comment by a-siva** [comment]
Additional tests that are missing compilation errors after some of the nnbd tests were fixed:
language/nnbd/syntax/class_member_declarations_test/01
language/nnbd/syntax/class_member_declarations_test/02
language/nnbd/syntax/class_member_declarations_test/07
language/nnbd/syntax/class_member_declarations_test/08
language/nnbd/syntax/class_member_declarations_test/17
language/nnbd/syntax/class_member_declarations_test/18
language/nnbd/static_errors/not_assigned_local_initializer_test/04
language/nnbd/static_errors/not_assigned_local_initializer_test/11

**Comment by stefantsov** [comment]
Currently, of all the mentioned tests only `language/nnbd/static_errors/not_assigned_local_initializer_test/11` is completing with an error, and that error is tracked in https://github.com/dart-lang/sdk/issues/40601.  I think this issue can now be closed.
