### ISSUE TITLE
"late int v; v;" is expected to be fine but VM throws runtime error

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39814]
language/nnbd/static_errors/not_assigned_local_initializer_test.dart expects
`late int v; v; //# 04: ok` to be a valid construct but we get an error

```
Unhandled exception:
LateInitializationError: v
#0      _LateInitializationError._throwNew (dart:core-patch/errors_patch.dart:600:5)
#1      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64NNBD/generated_tests/language/nnbd/static_errors/not_assigned_local_initializer_test_04.dart:18:15)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by lrhn** [comment]
I do not believe this to be a valid construct.

I would expect reading a variable which is *definitely unassigned* to be an error, even if the variable is `late`. The `late` only affects reads which are potentially unassigned.

@leafpetersen Or did we not do that?

**Comment by leafpetersen** [comment]
If this were statically valid, it would be a runtime error.  It is intended to be a static error, but the spec was missing this error.  I have a PR adding the static error here: https://github.com/dart-lang/language/pull/750 .

**Comment by leafpetersen** [comment]
I'll fix the test.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/128777
