### ISSUE TITLE
[Breaking Change Request] Remove support for ia32 on macOS

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#39810]
# Intended Change
Remove support for ia32 on macOS from the dart-sdk completely, as well as the ia32 distributions for all future releases on dart.dev and other release channels (e.g. homebrew). 32-bit ARM on iOS will remain supported.

# Rationale
On macOS Catalina or later, these binaries cannot be run anymore. Snow Leopard (10.6, ~10 years ago) was the last release that could run on ia32 CPUs. Therefore, most users on macOS can run the x64 SDK instead.

# Expected Impact
The exact number of users affected by this change is unknown but we expect it to be low based on the large groups that we know will not be. Any projects that 

## Projects known to break
None

## Projects that will _not_ be affected
* Flutter
* All Google internal projects

# Migration Steps
Any project affected by this change needs to switch to the x64 macOS artifacts or stay on Dart SDK version 2.7.0.

**Comment by mit-mit** [comment]
cc @Hixie @matanlurey @dgrove any concerns?

**Comment by athomas** [comment]
The commit above was landed to unblock internal rolls and dev releases, but we will hold off dev releases until this request is approved. If it isn't approved, we'll have to either stop using xcode or pin to an older version (that will only work for some time).

**Comment by franklinyow** [comment]
Make sense to me.

**Comment by dgrove** [comment]
Approved

**Comment by athomas** [comment]
I accidentally posted this only to internal lists, I sent the external notification to announce@dartlang.org as well. I won't be able to act on this until after the holidays, anyway.

**Comment by Hixie** [comment]
this is probably fine.

**Comment by mit-mit** [comment]
@athomas this is approved, you may go ahead

**Comment by athomas** [comment]
This change has now fully landed. 2.7.0 is the last release that has ia32 binaries for macOS.
