### ISSUE TITLE
Error: A value of type 'String' can't be assigned to a variable of type 'int'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39823]
nnbd/syntax/class_member_declarations_test_none fails with the error

```
out/DebugX64NNBD/generated_tests/language/nnbd/syntax/class_member_declarations_test_none.dart:79:28: Error: A value of type 'String' can't be assigned to a variable of type 'int'.
  a?..foo().length..x27 = s!..toString().length;
                           ^

```

**Comment by stefantsov** [comment]
It seems that there's an error in the test case itself.

/cc @eernstg

**Comment by eernstg** [comment]
Yes, I think it should have been `a?..foo().length..x27 = s!.toString().length` such that the value assigned to `x27` of `a` is actually an `int`.

**Comment by leafpetersen** [comment]
I'll take this.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/128777
