### ISSUE TITLE
CFE support for language versions

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#39827]
This includes:

- support for the new JSON package format
- using language version info in the JSON package format to determine whether to analyze a library in NNBD opt-in or opt-out mode
- allowing a single library's opt-in / opt-out status to be overridden by an appropriately formatted comment at the top of the file (note: there are corner cases for part files under this scenario)
- appropriate fallback logic for analyzing projects that lack a JSON package file

**Comment by franklinyow** [comment]
@johnniwinther
Please edit the description as needed, the current description is clone from the Analyzer support issue
Please add Estimate to the issue

**Comment by jensjoha** [comment]
Generally I'd say this has been fixed.
CFE (with 81d4ac07d488fb48383586b29f6503b674a8b917) reads the json file and uses that as the default appropriately. It allows libraries to overwrite via the comment syntax (and has supported that for ~half a year).

> * allowing a single library's opt-in / opt-out status to be overridden by an appropriately formatted comment at the top of the file (note: there are corner cases for part files under this scenario)

What corner cases? As I recall there is no corner cases: The part and non-part should just match..?

> * appropriate fallback logic for analyzing projects that lack a JSON package file

Details? I've heard nothing else, than:
* Use .dart_tool/package_config.json; if it doesn't exist
* Use .packages; if it doesn't exist
* Use default version of the compiler;

Whichever way picks the "default" version it still allows to be overwritten by the first dart version comment in the code.

/cc @lrhn can you shed light on any of this?

**Comment by lrhn** [comment]
The part and library file must have the same version marker. That is the entirety of that corner case. It does mean that having the same version is not enough, if one has a marker and the other gets the version from a default, then it's still invalid.

For the compiler, you should just read the `package_config.json`/`.packages` files as specified, and if there are none, use the SDK version.

The analyzer might be able to figure something out from the `pubspec.yaml` itself, if it runs before anyone has called `pub get`, but that's not something the compiler should worry about.
I don't know if Fasta need to be prepared for someone else providing the resolution to use for a particular file. That's not a priority for now, we need to get language version working correctly, then we can add features later.

**Comment by franklinyow** [comment]
What's the status?  Are we ready to close this?

**Comment by lrhn** [comment]
I believe so. The CFE supports everything it's intended to support.
