### ISSUE TITLE
Migration needs to be able to add nullability to function typed parameter syntax

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39832]
Consider the following code:
```dart
int f(int callback()) { // (1)
  if (callback == null) {
    return 0;
  } else {
    return callback();
  }
}
void g() {
  f(null);
}
```
Clearly the parameter `callback` is meant to be nullable, ~~however there's no way to notate nullability using the old-style function-typed-parameter syntax, so we need to migrate line (1) to `int f(int Function()? callback) {`~~ so we need to migrate line (1) to `int f(int callback()?) {`.  The migration tool doesn't yet know how to do this.

**Comment by lrhn** [comment]
You can use `int f(int callback()?) { ...` to make the function parameter nullable.

You do not need to migrate, and probably *should not* migrate unless the user asks for it.
(I guess it would be perfectly fine to pass `fix` parameters through the migration tool to the formatter, if you use the formatter on the result of migration anyway).

**Comment by stereotype441** [comment]
@lrhn thanks!  I've modified the issue accordingly.
