### ISSUE TITLE
reintroduce the single-out-file flag

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39834]
When renaming the legacy module we deleted the `single-out-file` flag, which seems to be used by default by flutter's dartpad.

See: https://github.com/dart-lang/sdk/commit/ae34d6e233

We need to reintroduce it at this time, then reevaluate whether this is the right mechanism to address the needs from flutter's dartpad.

**Comment by RedBrogdon** [comment]
Thanks, @sigmundch! I'm going to do some experimenting to see whether we can or can't get along without it.

**Comment by sigmundch** [comment]
looking more closely I believe the "--single-out-file" flag had an effect when using the default format (amd) that made the output different, but if we used a different format (now called "ddc", pka "legacy") then the output looked the same, and the format automatically supported concatenating files together and serving them as a single file.

We however don't ship a `dart_sdk.js` for this `ddc` module format. We could either try to generate that and switch the format by passing `--module ddc` as a flag to the compiler, or add back the flag and switch things over more gradually at a later time.

@vsmenon - thoughts? I'm currently inclined to bring back the flag as it was before (even without the `eval` piece)

**Comment by sigmundch** [comment]
I believe @RedBrogdon worked around this issue back in January, so I'm closing this as obsolete. Feel free to reopen if I missed something.
