### ISSUE TITLE
instance method as function parameter

### ISSUE THREAD

**Issue by PandaGeek1024** [dart-lang/sdk#39839]
Hi, I don't know if this is the right place to ask about this question but will give it a try.

In some dart code, I see some thing similar
```
  var children = [1, 2, 3];
  List removeList = [];
  removeList.add(children[0]);
  removeList.forEach(children.remove);
```

I know that in dart you can pass function as parameter, but I don't know that you can also pass instance method in this case. And when instance method is executed it work on the variables with the instance. That is really amazing. Base on this, does it mean we can also pass class(static) function as well? I have checked the dart tour but never mention about this. Is there anywhere i can check this? Thanks.

**Comment by vsmenon** [comment]
You'll get better and faster answers here: https://dart.dev/community#join-the-conversation :-)

But, yes, you can pass static and top-level methods as well.  You can try yourself at https://dartpad.dev/.

**Comment by mraleph** [comment]
@PandaGeek1024 this is called _method tear-off_ and indeed language tour seems to omit it for unclear reasons (/cc @kwalrath). It does use it in one of the code examples where equality of functions is discussed - but only in passing (https://dart.dev/guides/language/language-tour#testing-functions-for-equality). 

It is only mentioned in Effective Dart (https://dart.dev/guides/language/effective-dart/usage#dont-create-a-lambda-when-a-tear-off-will-do)

**Comment by PandaGeek1024** [comment]
@mraleph thanks for your explanation, I read the part in Effective Dart about tear-off. Does it mean when use tear-off, dart will create a closure during compile time that contains the method and pass it all the paramters provided when executed?

**Comment by mraleph** [comment]
>  dart will create a closure during compile time that contains the method and pass it all the paramters provided when executed

Yep. The closure would not be created during compile time - but the rest is correct.
