### ISSUE TITLE
Analyzer accepts `?` after function-typed formal parameter

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39833]
The following code is accepted by the analyzer:
```dart
void f(int callback()?) {}
```
It should not be accepted unless the "non-nullable" experiment is enabled.

I'm investigating.

**Comment by stereotype441** [comment]
Looks like the bug is isolated to the analyzer, and the fix should be pretty straightforward.

**Comment by stereotype441** [comment]
@scheglov will verify that this got fixed

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/132741
