### ISSUE TITLE
How to translate Flutter dart code to ASTNode？

### ISSUE THREAD

**Issue by FKLam** [dart-lang/sdk#39841]
How to translate Flutter dart code to ASTNode？
We have Flutter project，and want to translate some files of dart to ASTNode，then to json.
But we not found idea to do it.

**Comment by bwilkerson** [comment]
The `analyzer` package, available on pub.dev, has support for creating an AST structure for Dart code and would probably meet your needs, though I don't know very much about your requirements.

**Comment by devoncarew** [comment]
@FKLam - perhaps follow up on this question at `analyzer-discuss@dartlang.org`?

**Comment by FKLam** [comment]
Thanks all.
