### ISSUE TITLE
Analyzer quick-fixes/auto-imports use relative paths for packages in pub-cache/flutter SDK

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#39848]
(Moving this from https://github.com/Dart-Code/Dart-Code/issues/2172 since it seems like an analyzer issue and has been seen in Android Studio too).

I've had a number of reports of analyzer import quick-fixes inserting long relative paths like `../../../../../flutter/.pub-cache/some-package-1.0/lib/file.dart` instead of the expected `package:` URIs. The same goes for auto-imports in completion:

![Screenshot from 2019-12-17 23-46-17](https://user-images.githubusercontent.com/42690541/71023653-31bbfa00-2129-11ea-9f7f-3eb128d3beff.png)

It's been seen in both VS Code and Android Studio. My thought was that it's either related to Flutter's custom pub-cache folder, or the change from `.packages` to `.dart_tool/packages_config.json` - though @devoncarew suggests the analyzer might not be using the new JSON file yet.

I'm unable to reproduce this myself, and one user reported deleting Flutter and re-downloading it resolved the issue, while another has reported that deleting `.packages`, `.dart_tool` and `pubspec.lock` fixed it (another reported it appears to have gone away with no input). I'm not familiar with how the server decides when a discovered library can be imported with a `package:` URI (I figured it would compare the file paths against the `.packages` entries) but I was going to try debugging if I could repro locally.

At least some of the users setting this downloaded Flutter as a zip file and then upgraded it with `flutter channel master` && `flutter upgrade`.

(fyi @bwilkerson @scheglov @pq)

**Comment by DanTup** [comment]
> @devoncarew suggests the analyzer might not be using the new JSON file yet

Looks like this work may have started (for ex. dfc268671f79491863365262e9ddcb6be0e93119), so it's possible it is related (the versions posted in the Dart-Code issue are all on recent `master` Flutter builds, which has a very recent SDK).

**Comment by devoncarew** [comment]
We have an update. This occurs after launching a flutter web app. Fluter is now generating additional files into the `dart_tool/` directory. The presence of `.dart_tool/build/` is causing the analysis server to switch to a different resolution strategy - one that can handle locating generated dart source file in the .dart_tool directory.

We're going to look at fixing resolution in these cases - ensuring that we continue to resolve packages as normal, and only use `.dart_tool/build/` for additional, generated files.

**Comment by devoncarew** [comment]
cc @MichaelRFairhurst, @stereotype441

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/129305

**Comment by devoncarew** [comment]
I've confirmed that this addresses the issue (when I patch a dart sdk built with this commit into the flutter master version). People on flutter master won't see this fix until this commit rolls into the flutter sdk.

**Comment by ReindertKorver** [comment]
Running `flutter clean` for now fixed it for me

**Comment by DanTup** [comment]
The fix has landed in Flutter `master` and is working fine for me now. Thanks!

```
danny@Dannys-MBP ~ % flutter --version
Flutter 1.13.6-pre.29 • channel master • git@github.com:DanTup/flutter.git
Framework • revision 2884758f50 (78 minutes ago) • 2019-12-26 11:59:45 -0800
Engine • revision 42bb7c9eea
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)
```
