### ISSUE TITLE
dartLangSpec.tex should be deleted

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39844]
I just discovered that the copy of `dartLangSpec.tex` I've been using for reference (in `docs/language/` of the `sdk` repo) is apparently no longer maintained (it was last modified on Feb 26).  It appears that the version that is now maintained is in the `language` repo, in `specification/`.

Can we delete `docs/language/dartLangSpec.tex` from the `sdk` repo, to avoid causing similar confusion for others?

**Comment by stereotype441** [comment]
@eernstg @leafpetersen @lrhn FYI

**Comment by eernstg** [comment]
That is confusing. Here's the reason why I haven't deleted it; create a branch and delete the spec from the SDK repo, commit, then try to search its history:

```
> git log -p dartLangSpec.tex
fatal: ambiguous argument 'dartLangSpec.tex': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I guess I could just remember the last commit where this file exists in the repo and switch to that commit before looking into the history, but it is awfully convenient to be able to do it from anywhere.

Would it suffice to change the file to have a large text "OBSOLETE -- look in language repo"?

**Comment by leafpetersen** [comment]
We should just delete this, it's too confusing. For referring to the history, I believe that:

```
git log -p --full-history -- docs/language/dartLangSpec.tex
```

will do what you want.

**Comment by eernstg** [comment]
https://dart-review.googlesource.com/c/sdk/+/128881 ;-)

**Comment by parlough** [comment]
The CL has been merged, so fixed by https://github.com/dart-lang/sdk/commit/642f8d052fd7fda51651b38bb77f59713de74ac3#diff-a2aadc8a44715f89c2c7c35ae6a8c4bc

**Comment by eernstg** [comment]
Right, closing. Thanks!
