### ISSUE TITLE
Problem with null safety and extensions

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#39849]
Hey guys!
I am playing with nullsafety.dartpad.dev and found something that is really annoying. I know the feature for NNBD isn't ready yet, but this is really intended?

``` dart
void main() {
  int? value = 0;   
  print(value?.doubleAsString() ?? "empty");  
}

extension on int {  
  String doubleAsString() => "${this + this}";  
}
```

Gives error:
![image](https://user-images.githubusercontent.com/1146982/71099308-d540f500-2191-11ea-967a-77a91c0d3112.png)

Is this really intended? Will this not break all the extensions feature? 
Thinking on a real world development this is definetly a problem, since we having a lot of libraries out there based on extensions already (like https://github.com/leisim/dartx) that will stop serving its purpose once we have the NNBD feature released and breaking it...

**Comment by leafpetersen** [comment]
cc @scheglov @stereotype441 @johnniwinther

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/129241
