### ISSUE TITLE
Feature request: "Change Signature" refactoring

### ISSUE THREAD

**Issue by saif97** [dart-lang/sdk#39842]
This is my very first time posting issue on GitHub, so excuse me if I did it wrong
IntelliJ idea has a really cool and time-saving refactoring method signatures feature. Unfortunately, for some reason, it doesn't work in IntelliJ Idea.

I've found [this](https://youtrack.jetbrains.com/issue/WEB-14977) issue in IntelliJ's YouTrack 4 years ago which redirected me here.  

Flutter 1.12.13+hotfix.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (7 days ago) •
2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

Using Windows, chrome.

**Comment by devoncarew** [comment]
@saif97 - thanks for the feedback. To clarify - is this a bug report or a feature request?

**Comment by devoncarew** [comment]
cc @jwren

**Comment by jwren** [comment]
Are all Dart refactorings (`Shift + F6` action) in IntelliJ broken?  Does a dialog appear after you invoke the refactoring?  Is an exception thrown?, or does the refactoring just not happen?

**Comment by saif97** [comment]
> @saif97 - thanks for the feedback. To clarify - is this a bug report or a feature request?

Feature request I guess. The feature is already available in IntelliJ Idea for Java development. However,  It doesn't work for Dart. 


> Are all Dart refactorings (`Shift + F6` action) in IntelliJ broken? Does a dialog appear after you invoke the refactoring? Is an exception thrown? or does the refactoring just not happen?

![image](https://user-images.githubusercontent.com/13847797/71309743-aee2ba00-241c-11ea-928c-ed658b427266.png)
These are all the available refactoring options for Dart. They all work (Thank you guys for the amazing work). 
However, the Change signature isn't available in Dart.  The picture below shows Java Code where pressing Ctrl + F6 (in my case) or simply searching it shows the command
![image](https://user-images.githubusercontent.com/13847797/71309848-ec941280-241d-11ea-8040-a9269b29f0ad.png)

In this picture, I tried to do the same in Dart code but as you can see the command isn't there & pressing Ctrl + F6 doesn't show the window either.
![image](https://user-images.githubusercontent.com/13847797/71309918-8f4c9100-241e-11ea-875a-39bef921e545.png)

No exceptions are thrown.

**Comment by jwren** [comment]
Changed to a feature request.  I am glad the refactorings are working as expected.  This is just not one of the refactorings that we happen to offer.

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#type_RefactoringKind

@scheglov @bwilkerson

**Comment by alexander-doroshko** [comment]
@devoncarew Probably `area-analyzer`?

**Comment by filipagh** [comment]
can you also include scope of `move` refactor to class, function ... (not only file) (idea shortcut F6)
expected result (python) 
![image](https://user-images.githubusercontent.com/22474494/150676707-b69283a2-0b6b-462f-96e8-1ed9ce1120d0.png)
actual options 
![image](https://user-images.githubusercontent.com/22474494/150676772-8287a891-5e4f-4a29-9362-d5e3587f1600.png)
thanks

**Comment by prinkeeras** [comment]
any updates on this?

**Comment by bwilkerson** [comment]
Nothing concrete.

We are hope to have some time this quarter to work on improving our refactoring support, but we haven't yet decided which refactorings we will be adding. This refactoring is definitely on our radar, though there are some limitations in LSP that might require us to implement a set of smaller refactorings that together could be used to achieve the same effect. That might not be ideal, but might be better than no support. We'll know more after we've had time to investigate what's possible and what isn't.

**Comment by bwilkerson** [comment]
There have been a couple of refactorings added since I last commented. They are, unfortunately, not available in IntelliJ at this point, but are available in VS Code.

There is now a 'Move to file' refactoring to help re-organize code in libraries.

There are also some experimental refactorings to convert some or all of the positional parameters to be named parameters and to move parameters left in the parameter list. Both implement a portion of the kinds of changes that a 'Change signature' refactoring would be expected to make, but can be done without implementing a per-client dialog.

It's unlikely that we'll be able to provide the full-functioned refactoring asked for here, as much as we'd like to. So, as much as I don't want to, I'm going to close this issue.

If there are other small-grained refactorings like these that you would like us to add, please open an issue for each of them.
