### ISSUE TITLE
flutter layout explorer

### ISSUE THREAD

**Issue by sulazo** [dart-lang/sdk#39855]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1440x900  Retina`

**Comment by devoncarew** [comment]
Hi, if this is feedback or a bug report, please re-open with details; thanks!
