### ISSUE TITLE
analysis_options "include" should throw an error if the file doesn't exist

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#39859]
If I write an `analysis_options.yaml` with an `include` directive pointing to a file that doesn't exist:

```yaml
include: asdfghjk
```

and run `dartanalyzer`, it doesn't provide any feedback that my `include` is invalid. It just acts as though it wasn't there. Failing early and providing clear feedback to users when something goes wrong is important for making a tool user-friendly and comprehensible.

**Comment by bwilkerson** [comment]
I completely agree.

The last time I checked, `dartanalyzer` would analysis options files, but only if you explicitly list it on the command line. It really ought to analyze it by default.

**Comment by srawlins** [comment]
Yeah this is still the current action. If you explicitly analyze the options file, you get something like:

```
Analyzing analysis_options.yaml...
  warning • The include file x in /Users/srawlins/code/dart-sdk/sdk/pkg/analyzer/analysis_options.yaml cannot be found. • analysis_options.yaml:1:11 • include_file_not_found
```

**Comment by srawlins** [comment]
To reiterate, the analyzer does now report issues on that include field, but only if analysis_options.yaml is explicitly analyzed. Follow https://github.com/dart-lang/sdk/issues/29570 for updates on that aspect.
