### ISSUE TITLE
Add tzdata loading configuration for Dart on Fuchsia

### ISSUE THREAD

**Issue by filmil** [dart-lang/sdk#39861]
Fuchsia OS needs to guarantee all runners use the same tzdata.

We need to add code that loads tzdata from a configuration provided by a Fuchsia product.

**Comment by devoncarew** [comment]
@mraleph, @a-siva - where is this best triaged to?

**Comment by mraleph** [comment]
area-vm is fine. There is a PR closing this issue from @filmil

**Comment by filmil** [comment]
Added for review: https://dart-review.googlesource.com/c/sdk/+/129301
