### ISSUE TITLE
NNBD. Allow all member access for class 'Never'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39866]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) was updated according to the https://github.com/dart-lang/language/issues/711. So, now 

> It is not an error to call or tear-off a method, setter, or getter, or to read or write a field, on a receiver of static type Never. Implementations that provide feedback about dead or unreachable code are encouraged to indicate that any arguments to the invocation are unreachable.

> It is not an error to apply an expression of type Never in the function position of a function call

But dartanalyzer version 2.8.0-dev.0.0 still produces an error
```dart
void test(var x) {
  if (x is Never) {
    x.toString(); // error - This expression is invalid because its target is of type Never and will never complete with a value - static_errors_A13_t01.dart:21:5 - invalid_use_of_never_value
  }
}

main() {
  test(null);
}
```

```dart
void test(var x) {
  if (x is Never) {
    x(); //error - This expression is invalid because its target is of type Never and will never complete with a value - static_errors_A14_t01.dart:19:5 - invalid_use_of_never_value
  }
}

main() {
  test(null);
}

```

**Comment by scheglov** [comment]
This error code [was downgraded](924f4e05495c1755a1a4f9ed3519ce68147067b9) to a hint.
```
info: The receiver expression is of type Never, and will never complete with a value. (receiver_of_type_never at [test] bin/test.dart:7)
```
