### ISSUE TITLE
NNBD. Analyzer issue for '?.' operator

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#39865]
The following code produces an error in analyzer with --enable-experiment=non-nullable
```dart
class A {
  void test() {}
  int operator[](int index) => 0;
}

main() {
  A? a = null;
  a?.test();
  a ?.. test();
  a?.[0];

  a = new A();
  a?.test();   // error - The target expression can't be null, and so '?.' isn't necessary. - static_errors_A11_t01.dart:33:4 - unnecessary_null_aware_call
  a ?.. test();
  a?.[0];
}
```
It's interesting, that if to remove the first part of the checkings then error disappears.
```dart
class A {
  void test() {}
  int operator[](int index) => 0;
}

main() {
  A? a = null;
  a = new A();
  a?.test(); 
  a ?.. test();
  a?.[0];
}
```
Analyzer finds no any issues in the code above. Why analyzer behaves so strange?
`dartanalyzer version 2.8.0-dev.0.0`

**Comment by sgrekhov** [comment]
Retested on dartanalyzer version 2.8.0-dev.12.0. There is static warning instead of error now

**Comment by scheglov** [comment]
See also https://github.com/dart-lang/sdk/issues/40088

**Comment by scheglov** [comment]
See https://github.com/dart-lang/sdk/issues/40088, the correct behavior for this code:
```dart
A? a = null;
a = new A();
```

...is to promote `a` from `A?` to `A` on assignment.

So, both test cases above should start reporting a warning that the target cannot be null.

https://dart-review.googlesource.com/c/sdk/+/144040 implements such promotion.
