### ISSUE TITLE
List<Dynamic> assignment to List<String> Fails Silently In Flutter

### ISSUE THREAD

**Issue by rhhub** [dart-lang/sdk#39862]
The following code hangs silently in Flutter but crashes on dartpad.

```
void main() {
  List<dynamic> listOfDynamic = ['hello'];

 // In flutter the following line indefinitely hangs silently without crashing.
  List<String> listOfString = listOfDynamic;

  print(listOfString);
}
```

Tried at https://dartpad.dartlang.org/ with crash and following error message:
Error: Error: TypeError: Instance of 'JSArray': type 'JSArray is not a subtype of type 'List<String>'

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (1 available)

**Comment by lrhn** [comment]
What you are seeing is the currently correct behavior.

Dart has *implicit downcasts* which allows you to use a value whose static type is a supertype of what is needed. The compiler inserts an implicit cast to the required subtype, and that cast fails at run-time.

An upcoming update to Dart, introducing non-nullable types, will also remove this implicit downcast, but for now they are still there. You can the Dart analyzer to warn you by enabling the [no-implicit-casts flag](https://dart.dev/guides/language/analysis-options#the-analysis-options-file).

I cannot explain why Flutter hangs at this point, but it would probably do so no matter which error you throw.

**Comment by rhhub** [comment]
> What you are seeing is the currently correct behavior.
> 
> Dart has _implicit downcasts_ which allows you to use a value whose static type is a supertype of what is needed. The compiler inserts an implicit cast to the required subtype, and that cast fails at run-time.
> 
> An upcoming update to Dart, introducing non-nullable types, will also remove this implicit downcast, but for now they are still there. You can the Dart analyzer to warn you by enabling the [no-implicit-casts flag](https://dart.dev/guides/language/analysis-options#the-analysis-options-file).
> 
> I cannot explain why Flutter hangs at this point, but it would probably do so no matter which error you throw.

Thanks for your response. I will give that a shot.
