### ISSUE TITLE
Dart LSIF indexer

### ISSUE THREAD

**Issue by chrismwendt** [dart-lang/sdk#39878]
[LSIF](https://github.com/microsoft/language-server-protocol/blob/master/indexFormat/specification.md) (Language Server Index Format) is a format for precomputing LSP data (definition, reference, and hover results, etc.) and saving it to a file for later use by code navigation tools. It's similar to Kythe, which is already supported in dartanalyzer.

@rvantonder and I are interested in adding LSIF support to the Dart SDK 😃 We're new to this ecosystem, so we have a few questions to start off:

- Where is the most appropriate place for a Dart LSIF indexer to live? (e.g. inside dartanalyzer, a sibling command to dartanalyzer, a separate repository, or someplace else)
- Is the Kythe support (specifically [kythe_visitors.dart](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/kythe/kythe_visitors.dart)) a good model to use for LSIF? I imagine the structure for both is similar: loop over files, visit each node in the AST, and accumulate data and emit results.
- For consistency with other LSIF indexers, it'd be great if it were a one-shot command-line tool, rather than a long-running process. Any recommendation for how to go about building a command-line tool like this? Perhaps dartfmt could be a good example here?

@scheglov Any thoughts? 💭

**Comment by bwilkerson** [comment]
> Where is the most appropriate place for a Dart LSIF indexer to live?

I'm guessing that you'll want to create your own GitHub repository in which to do this code. Adding it to the sdk repository would imply a responsibility for the Dart team to maintain it, and we'd need to have some discussions about whether that's something we could add to our plate. If you create a separate repository for it now it could potentially move it into the sdk later, assuming we both wanted to do so.

> Is the Kythe support (specifically kythe_visitors.dart) a good model to use for LSIF?

Yes, I believe that it is.

> Any recommendation for how to go about building a command-line tool like this? Perhaps dartfmt could be a good example here?

`dartfmt` only needs a parsed AST, while you need a resolved AST. I don't know of a really good example to point you to, so I would recommend starting with the tutorials for the `analyzer` package (https://github.com/dart-lang/sdk/tree/master/pkg/analyzer/doc/tutorial).

**Comment by chrismwendt** [comment]
Thanks, @bwilkerson 🙇 I started a new repository at https://github.com/sourcegraph/lsif-dart and the next step is to take a closer look at the Kythe support.

**Comment by devoncarew** [comment]
Closing this issue as it looks like it's resolved (and looking forward to tracking work on https://github.com/sourcegraph/lsif-dart!).
