### ISSUE TITLE
Two null checks added at the same offset

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39871]
In the `async` package, in `lib/src/delegate/future.dart`, on line 21, the tool added two null checks in the same location:
```
static Future<T> typed<T>(Future future) =>
    future is Future<T> ? future : future.then((v) => v as T!!);
```
Each has a reason that points to the `v` on the left of the `as` operator.

**Comment by srawlins** [comment]
async no longer has that change in the migration. We'll have to spot a new case and open a new issue.
