### ISSUE TITLE
NNBD: spurious error while calling extension method for nullable receiver

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39875]
Tested on https://nullsafety.dartpad.dev
(Based on Dart SDK 2.7.0-edge.134e0e28cda1f8110a69bad34ae70e8123475a80)

```
void main() {
  var yy = 5 > 3 ? 5 : null;
  yy.doubleAsString();  // error: the expression is nullable and must be null-checked before it can be used
}

extension on int? {
  String doubleAsString() => this.toString() + this.toString();
}
```

**Comment by scheglov** [comment]
@leafpetersen @lrhn What are rules for nullability and extensions? [The spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) does not mention `extension`.

**Comment by leafpetersen** [comment]
I don't think there are any modifications to the spec required for extensions, at least that I can think of off the top of my head.  The extension method specification allows extensions to be specified on any type.  NNBD adds nullable types, so now there can be extensions on nullable types.  The resolution rules remain the same.

I can call out explicitly that it is permitted to call an extension method on a nullable type if the receiver type is a subtype of the resolved `on` type.  

It might also be worth me calling out specifically the interaction between `?.` and extension methods.

Are there other questions that it would be helpful to make explicit?

**Comment by scheglov** [comment]
Yes, mostly it is clear.

One question is if the extended type in nullable, does this mean that `this` in extension can be nullable?

**Comment by leafpetersen** [comment]
> does this mean that `this` in extension can be nullable?

Yep.  Given `extension E on T`, `this` is treated as having type `T`.  So if `T` is nullable (or potentially nullable), the usual errors and warnings apply.

Your example is correct: `// 1` and `// 3` are errors, and the `// 2` is ok.

**Comment by scheglov** [comment]
@leafpetersen I have another question, about applying extensions to nullable types. Extensions are used when the target type does not have the matching member. But what does it mean "does not have"? What if the target type is nullable, and we have NOT null-aware invocation? Do we use the extension, or do we report that the target must be null-checked?

```dart
class A {
  int get foo => 0;
}

extension E on A? {
  int get foo => 0;
}

main(A? a) {
  a.foo;
}
```

**Comment by leafpetersen** [comment]
Great question.  Filed https://github.com/dart-lang/language/issues/761 for discussion.

**Comment by kuhnroyal** [comment]
Not sure where to ask this so I will try here.
Coming from Kotlin, I would expect extensions on nullable types also to be callable on a null receiver.

Is the explicitly not desired and if so, can someone explain why?

```dart
void main() {
  String? foo = null;
  
  String bar = foo.nullToEmpty(); // invalid but valid in Kotlin
  bool baz = foo.isNullOrEmpty(); // invalid but valid in Kotlin
}

extension Foo on String? {
  String nullToEmpty() {
    return this ?? "";  
  }

  bool isNullOrEmpty() {
    return this == null || this == "";   
  }
}
```

**Comment by tatumizer** [comment]
@kuhnroyal : please see the discussion here:
https://github.com/dart-lang/language/issues/761
It seems that the consensus right now is consistent with your wishes :)

**Comment by kuhnroyal** [comment]
@tatumizer Thanks, really hoping this makes it into the spec.

**Comment by leafpetersen** [comment]
> But what does it mean "does not have"? What if the target type is nullable, and we have NOT null-aware invocation? Do we use the extension, or do we report that the target must be null-checked?

@scheglov This is resolved in favor of using the extension.

**Comment by scheglov** [comment]
ACK, analyzer uses extension in such cases.
