### ISSUE TITLE
Flow analysis does not track "definitely unassigned variables"

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39876]
We should use it to give better errors for late variables (see https://github.com/dart-lang/language/pull/750).

We also need it to implement definite assignment for final variables.  That is, in NNBD, we want it to be possible to have a final local variable without an initializer, provided that the variable is definitely assigned before any use of it, e.g.:
```dart
void test(bool b) {
  final int x;
  if (b) {
    x = 3;
  } else {
    x = 4;
  }
  print(x); // ok; x is definitely assigned
  x = 5; // ERROR: already assigned
}
```
The reason "definitely unassigned" tracking is necessary for this is because we only want to allow assignment to a final variable if it is definitely unassigned.  For example, the following should be an error:
```dart
void test(bool b) {
  final int x;
  if (b) {
    x = 3;
  }
  x = 4; // ERROR: might already be assigned
}
```

**Comment by stereotype441** [comment]
@scheglov @leafpetersen FYI

**Comment by scheglov** [comment]
Tracking for definitely unassigned variables was done in flow analysis in https://dart-review.googlesource.com/c/sdk/+/138881.

**Comment by scheglov** [comment]
Reporting the error in analyzer in https://dart-review.googlesource.com/c/sdk/+/139034

**Comment by scheglov** [comment]
Presubmit for the analyzer CL uncovered an issue with function expressions in flow analysis.
I will fix it tomorrow.

**Comment by scheglov** [comment]
Flow analysis was fixed.
The CL for reporting the error in analyzer landed.
