### ISSUE TITLE
Discussion on Json serialization&deserialization, and Appeal for Kernel Transform Customization

### ISSUE THREAD

**Issue by xujim** [dart-lang/sdk#39879]
Hi, all
As you know, since Dart doesn't recommend mirror, we can handle Json serialization&deserialization with SourceGen. However, from my point of view, SourceGen has following weak points:

1. Doesn't support generic type. for example, you defined a Json class like:
```dart
class UserDataT <T, T1, T2, T3,T4>{
  T name;
  @JsonField(true,'city1')
  T city;
  T1 age;
  List<T3> children;
  T4 birthday;
  Map<String, T2> houses;
}
```
 2. Doesn't support customized serialization strategy, like serialization all fields of Json object to string, convert Json object to array, etc. And vice versa for deserialization.
     To be more detail, I want serialize the above class to Json composed with all string. That is to say, the age, birthday all will be of string type, instead of the original type like int and datetime.
 3. The SourceGen is not so fit with our traditional experience, we may like some way to do as following: 
```dart
 final UserDataT<String, int, String, Child, DateTime> userDataT = JsonParser.fromJson<UserDataT<String, int, String, Child, DateTime>>(jsonDecode(str));
 ```
or I can add a serialization strategy like:
```dart
 final UserDataT<String, int, String, Child, DateTime> userDataT = JsonParser.fromJson<UserDataT<String, int, String, Child, DateTime>>(jsonDecode(str), strategy: stringnify);
 ```

For the above issue, I have implemented a JsonParser based on Kernel transformer. Under the hood, I will transform the dill to generate the customized serialization&deserialization logics.

I am planning to open source this framework, but I am afraid it will be affect by the experience of Kernel transform of Dart. Therefore, with this issue, I urge Dart team to support customization of kernel transform pipeline. I am sure a lot of useful framework will be rising base on this feature.
Finally, I come up with this issue for this topic. Please give me support if you feel the same way.

Thanks,
Jim

**Comment by mraleph** [comment]
We are actively working on assessing potential ways to improve ergonomics of JSON serialization/deserialization as well as exploring ways to introduce metaprogramming into the Dart language. This work is still in the very early stage, but you can see some of the research @jakemac53 has been doing [here](https://github.com/jakemac53/json_investigations). 

Kernel transformations are powerful tool, however we starting to realise that there are some deeply rooted issues with it, which makes it unsuitable as a general purpose user level metaprogramming tool - so it is unlikely that we will expose it as such. 

@vsmenon do you think we should go ahead and file issues for better JSON support and for metaprogramming here or on the language repo to reflect that we are actively working on it?

/cc @vsmenon @johnniwinther @jakemac53

**Comment by mraleph** [comment]
I will for now close this issue - but we most likely will split two more specific issues out of it. Stay tuned.

**Comment by xujim** [comment]
well, anyway, thanks for your reply. @mraleph

**Comment by xujim** [comment]
I just have pity on my JsonParser framework, which could be one of my key performance index. :(
