### ISSUE TITLE
Analyzer stuck at 100% CPU on macOS (infinite loop)

### ISSUE THREAD

**Issue by xvrh** [dart-lang/sdk#39888]
When I run `flutter analyze` in my Flutter project, it runs indefinitely with the Dart process at 100% CPU.
I can workaround this behaviour with this section in the analysis_options.yaml

```
analyzer:
  exclude:
    - build/**
    - ios/**
    - macos/**
```

I see the behavior with flutter stable (Dart 2.7.0) and flutter dev (Dart 2.8.0-dev.0.0)

An other issue https://github.com/Dart-Code/Dart-Code/issues/1114 suggests that this may have something to do with a symlink cycle in one of this folders.

I see the same behaviour with the Dart Analysis Server in Intelli, Android studio and VisualStudio Code. (and this is even worth because it seems the `exclude` section of the analysis_options.yaml is not taken into account?).

I'm available to provide more information if needed.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by xvrh** [comment]
I opened https://github.com/flutter/flutter/issues/47673 with instructions to reproduce the issue.
