### ISSUE TITLE
NNBD: type literal for nullable type is not recognized as Type

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39881]
`var y = int?;` produces a bunch of errors. But there should be some way to write this type. How?

**Comment by lrhn** [comment]
There is no way to write that type, just as there is no way to write `List<int>` or `FutureOr<Object>`. Type literals can still only be plain or qualified identifiers.

As usual, you can use a helper function like `Type type<T>() => T;` and write `var y = type<int?>();`

**Comment by tatumizer** [comment]
I see. Thanks. Closing the issue.
