### ISSUE TITLE
NNBD: absurd error message while trying to call an extension method on null 

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39880]
Tested on https://nullsafety.dartpad.dev
(Based on Dart SDK 2.7.0-edge.134e0e28cda1f8110a69bad34ae70e8123475a80)
```
void main() {
  null.staticType(); // error: This expression is invalid as it will always be null
}
extension <T> on T {
  staticType()=>T;
}
```
The problem doesn't occur in the pre-NNBD version.

**Comment by lrhn** [comment]
Definitely a bug.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/129323 will fix reporting errors.

https://dart-review.googlesource.com/c/sdk/+/129340 will fix resolution, so that navigation, search, and refactoring work.

**Comment by tatumizer** [comment]
Not sure if this is related or not, was already reported or not, but in non-NNBD version (2.7.0, tested on dartpad) analyzer reports an error on `null.bar`, but not on `null.bar()` (no extension methods, just this:
```
main() {
   null.bar();
}
```
The error is printed later by dart2js

**Comment by scheglov** [comment]
Yes, I believe it is related.
By some reason we special-cased `null` literal in method invocation resolution.
It might have been specified so 8 years ago, but currently the spec says that the type of `null` is `Null`. So, invocation should be resolved as usually for any interface type.
![image](https://user-images.githubusercontent.com/384794/71302581-9497d600-2361-11ea-9aa8-1fd47ee46064.png)

I will update the implementation and run it through the tests on bots.

**Comment by lrhn** [comment]
(And, just for completeness: In NNBD, `Null` is not a subtype of `Object`. It still has the same members, though. @eernstg: We'll have to define those "default members" some other way).

**Comment by eernstg** [comment]
> "default members"

I think we need to talk about a top class, but we don't have to make a name for that top class available in source code (but we reserve the right to give it a suitable name later on). Let's call it `Any`. `Object?` is a subtype of `Any`, and the members of `Object` are all inherited from `Any`. No magic, just another class.
