### ISSUE TITLE
NNBD: passing optional non-nullable parameter

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39897]
Not sure where to post it, maybe it's the intended behavior or a bug or an open issue, but ... this doesn't work:
```
func({int x=0})=>0;
void main() {
  func(x:null); // The argument type Null cannot be assigned to the parameter type int
}
```
If this is by design, it's very problematic. E.g. we may have a map of 'key:value' pairs and want to create an instance of class Foo by calling the constructor `Foo(foo: map['foo'], ...20 parameters)`, but as soon as there's a single non-nullable parameter, we won't be able to do that - at least, it's not obvious how.
This would be equivalent to the invitation to declare all optional parameters nullable.

Pretty sure this problem was discussed somewhere, but I couldn't find any mention of it in the NNBD spec.

(Maybe it's just a bug, and passing `null` is allowed as a token for default value?).

EDIT: the proposal of null-elimination operator might help address the issue, but the status of the idea is unclear at the moment.

**Comment by devoncarew** [comment]
I think this is working as intended - if the function wants to accept null as a potential value, then the type of `x` would need to be declared as `int?`.

cc @leafpetersen to confirm

**Comment by tatumizer** [comment]
The function doesn't want to accept nulls. The parameter has a default value, so the function will never see the null in her life. Otherwise,  we have to introduce a much stronger rule: every optional parameter has to be declared with a nullable type, otherwise the caller will have a problem.
As a result, tons of nullable parameters will be introduced for no logical reason.

**Comment by lrhn** [comment]
In NNBD, all optional parameters must *either* have a default value (which is assignable to the parameter's type) *or* be nullable (which means that it has a default default-value of `null`). That way, the function can keep operating if you do not pass a value for the parameter.

You can only pass arguments which match the type of the parameter. That means that you *cannot* pass `null` as an argument to the `func` written here because it needs an `int`. You can *omit* passing an argument, in which case the function will get the default value instead.

Passing `null` will not trigger the default value, it didn't before NNBD, and it won't with NNBD. If the parameter is not nullable, passing `null` is no longer allowed, which is what NNBD is all about.

It does mean that you cannot easily call a function with computed arguments when some of them should be omitted. Not without knowing writing the default value at the call point:
```dart
Foo(foo: map["foo"] ?? 1, ... qux: map["qux"] ?? "defaultString");
```
That is *not new* though. If the function uses non-`null` default values now, it also doesn't work to pass `null` as argument. The function will have to *accept `null`* and then do a `?? defaultValue` internally. It can keep doing that, in which case the parameters will be nullable.

So, there really isn't any *change* here except that you have to write a `?` if a parameter accepts `null`. If the function currently throws when it gets `null` as argument, it should change to a non-nullable parameter type so the caller can get the *static* error.

**Comment by tatumizer** [comment]
I think the issue provides an argument in favor of null-elimination operator.
Closing.

**Comment by tatumizer** [comment]
OK, if you don't like null-elimination operator, here's the next best option :)
What if we allow passing a value of **static** type Null as a token to use default?
E.g.
```
foo(optionalNonNullableParameter: nullableExpr ?? null);
Null useDefault = null;
foo(optionalNonNullableParameter: nullableExpr ?? useDefault);
```

**Comment by lrhn** [comment]
@tatumizer It's a cute idea, but it doesn't really work the way you write it. First of all, a *value* cannot have a *static type*. Values have run-time types, expressions and variables have static types.
So, for `nullableExpr ?? useDefault`, the expression we are passing is the entire thing, which has the same static type as `nullableExpr`. The run-time value might be `null`, but we cannot track that back to the second part of the `??` operator to find its original static type.

**Comment by tatumizer** [comment]
Yeah, I felt something was wrong with this idea :-)
But it's still too soon to surrender! Forget Null. What if compiler instead allowed 2 special magical expressions `parameter: default` and `parameter: nullableExpr ?? default`. 
We can consider these "expressions" to be a kind of (micro-)DSL designed only for the purpose of passing parameters. After all, we have a whole DSL for collection literals, with "expressions" that are not really expressions and can't be used as such in any other context. 

I think this possibility was mentioned at some point in the discussion but without the DSL argument, the idea breaks apart quickly - indeed, we can't write `var x = default`. But we can refer to a precedent: 
`var x = if (cond) 5;` is not valid, but `var x = [if (cond) 5];` is, so we already opened Pandora box with contextual pseudo-expressions. WDYT?

**Comment by lrhn** [comment]
Taking it further! 

We could allow `default` in any *tail-position* expression of an argument expression.

An expression *e* is in a tail position of an expression *b* if 
 * it is the expression *b* itself,
 * *b* is `(c)` and *e* is in tail position in `c`.
 * *b* is `e1 ? e2 : e3` and *e* is in tail position in `e2` or `e3`.
 * *b* is `e1 ?? e2` and *e* is in tail position in `e2`.
 * *b* is `e1 || e2` or `e1 && e2` and *e* is in tail position in `e2` (and must have type `bool`)

That means that if `default` occurs, it occurs in a position where its value is *only* used as the argument value, and then we can treat it as an unpassed argument instead.

It's grammatically specifiable, we just have to have dual production hierarchies: &lt;expression&gt; and &lt;tail-expression&gt; where only the latter can produce `default`, and similarly all the way down. Annoying, but definitely doable (and if you have parameterized productions, like &lt;expression&gt;<sub>[tail=false]</sub> then it's even simpler.

**Comment by tatumizer** [comment]
We have a similar situation in collection literals where we can't easily write empty `else` clause:
```
var x=[
  if (cond) if (cond1) 0 else Nothing else 1
];
```
and have to resort to pretty awkward `...[]`:
```
var x=[
  if (cond) if (cond1) 0 else ...[] else 1 // or monstrous ...?null
];
```
We could allow the same type of "expression" instead, but the word "default" is no good in this setting. I was thinking of utilizing Never somehow, but couldn't figure out if this is acceptable. Actually, it's just a matter of finding a good word.

**Comment by lrhn** [comment]
Maybe we should allow `(if (cond1) 0)` as an element expression.

**Comment by tatumizer** [comment]
I'm still trying to figure out all PROs and CONs of using "default" token. I looked at some examples of optional parameters in existing APIs - and I see that in the absolute majority of cases, the default value is "null" anyway. The remaining cases include "int" and "bool" parameters where the  default values can be 0 or -1 (or true/false for booleans), but these cases are rare. Look at the following definition:
```
LinkedHashMap<K, V>({
  bool equals(
    K key1
    K key2
  ),
  int hashCode(
    K key
  ),
  bool isValidKey(
    dynamic potentialKey
  )
})
```

Though all parameters are optional, we can't write default values for those (the language doesn't support non-constant initializers), and the only choice is to make all these parameters nullable.
And this is the rule, not an exception. So the feature gets entangled with another feature (allowing non-constant initializers), but even in this case, nulls might be preferable for the reasons related to performance. E.g. `isValidKey` parameter, if initialized by default to function `(key)=>true`, will incur an overhead of calling this function where "if" could suffice otherwise.

If the majority of optional parameters are nullable, won't it be better to make all of them nullable, and with `null` being a formal default initializer everywhere uniformly? Then the real default value will be computed in - e.g. `if (param == null) param = expr;` or `if (param != null) doSomething`.

For usability, uniformity has a very high priority IMO.

**Comment by tatumizer** [comment]
In another thread, somebody suggested using `_` as a marker for a discardable value. There's a [prior art](https://csharp.today/c-7-0-discards/) in C#. Maybe it can be used also as a symbol for "default"?

**Comment by tatumizer** [comment]
Somebody opened yet another issue on the same topic: https://github.com/dart-lang/language/issues/820
New idea: to accommodate all variants of requests about "ignorable value", introduce a *verb* - e.g. "pass", like in python.
As soon as it becomes a verb, you don't need complicated rules involving tail-positions or anything b/c when "pass" operation gets executed, it stops the evaluation of the expression. And we really need a verb to make such interpretation possible!

**Comment by idkq** [comment]
You could use maps

class Dog{
  final String name;
  final int age;
  Dog({this.name, this.age});
  
  Dog.fromMap(Map<String, dynamic> map): 
    name = map['name'] as String, age = map['age'] as int;
  Map<String, dynamic> toMap() => {'name': name, 'age': age};
  
  Dog copyWith(Map<String, dynamic> fields){
    var newObj = this.toMap();
    for (final field in fields.entries)
      newObj[field.key] = field.value;
    return Dog.fromMap(newObj);
  }
}

void main() {
  Dog buddy = Dog(name: 'Buddy', age: 12);
  Dog puppy = buddy.copyWith({'age': null});
  
  // OUTPUT=> Name: Buddy Age: null
  print('Name: ${puppy.name} Age: ${puppy.age}');
}
