### ISSUE TITLE
.dart_tool problem

### ISSUE THREAD

**Issue by zamaniali28** [dart-lang/sdk#39906]
a few seconds ago
a few days when I want to create a flutter project, my android studio generated a folder that name is .dart_tool
![1577095164(1)](https://user-images.githubusercontent.com/56548683/71356136-40d4f900-25bc-11ea-93bd-a471e3ea8bbf.png)
. I don't know what is this folder? but sometime I can't run my project as well and take time more for running anyone know what is this and how to solve this problem?

**Comment by zamaniali28** [comment]
@jakemac53

**Comment by bwilkerson** [comment]
@scheglov

**Comment by devoncarew** [comment]
The `.dart_tool/` directory is a meta data directory created by Dart tooling. Flutter has recently started using tooling which generates info into this directory; iIts presence it normal and expected.
