### ISSUE TITLE
NNBD. Dart allows to declare Never variable in the legacy code.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#39917]
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

The following test example declares a variable of the type Never in the legacy code:
``` dart
// @dart=2.4
Never n;
main() {}
```
According to nnbd Spec:
> In a legacy library, none of the new syntax introduced by this proposal is available, and it is a static error if it is used.

So, there should be a compile error here, however this does not happens, the test just passes both with dart and analyzer.

Sample output is:
> $> dart --enable-experiment=non-nullable test.dart 
> 
> $> dartanalyzer --enable-experiment=non-nullable test.dart 
> Analyzing test.dart...
> No issues found!

**Comment by devoncarew** [comment]
@iarkh - is this a VM bug or an analyzer bug? Triaging to area-front end for now.

**Comment by lrhn** [comment]
The identifier `Never` is not new syntax, just a new type declaration exported by `dart:core`, so it is not covered by the quoted part of the specification.

The specification says that in a legacy library:
> The type `Never` is treated as the type `Null`.
and about legacy subtyping:
> This has the effect of treating `Never` as equivalent to `Null`, restoring `Null` to the bottom of the type hierarchy, ...

@leafpetersen 
I read this as the type `Never` being *replaced* with the type `Null` everywhere it occurs in legacy libraries. However, "is treated as" and "is equivalent to" are not strong enough to actually say that, they just say that there is some equivalence, so if it is what we intend, we should write it explicitly.
For example, is `identical(Never, Null)` true? Is `foo<X extends Never>()` assignable to `Function<X extends Null>`?

**Comment by johnniwinther** [comment]
@leafpetersen Any resolution on this issue? Should we parse `Never` as a regular interface type or as `Null` in legacy code?

**Comment by leafpetersen** [comment]
Let's just parse `Never` as `Never`, regardless of where it occurs.  I see no benefit to doing otherwise.

**Comment by lrhn** [comment]
So `Never` occurring in a non-NNBD library will mean `Never*` (because all types written in a non-NNBD library are legacy types), which is a different type than `Null`. (**NORM**(Never*) is Never*).
It's a mutual subtype of `Null`, so `Null` is still a bottom type, just not the only one.

We should consider whether it's still correct to say that `Never` is treated as `Null`. It is for subtyping (which *is* where the phrase occurs), but it is also a separate type wrt. type equality based on normalization.

**Comment by scheglov** [comment]
Test that analyzer  resolves `Never` in legacy.
https://dart-review.googlesource.com/c/sdk/+/133284
