### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Magadani** [dart-lang/sdk#39914]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `unknown`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version unknown, server version 1.27.4, error: Bad state: No dart:core, sdk: {
  "runtimeType": "FolderBasedDartSdk",
  "libraryMap": {},
  "directory": "C:\\Program Files\\Dart\\dart-sdk"
}
#0      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:111:9)
#1      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:56:49)
#2      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1846:22)
#3      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:297:16)
#4      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:167:33)
#5      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:775:48)
#6      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1189:19)
#7      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1251:16)
#8      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:791:9)
#9      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:496:22)
#10     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#11     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:319:16)
#12     AnalysisServer.handleR

**Comment by devoncarew** [comment]
Thanks for the report! Do you know if you are running any analysis server plugins (one you've written, or, if you're working on an AngularDart project)?

**Comment by devoncarew** [comment]
This text - `Bad state: No dart:core` - might mean that your sdk is corrupt; do regular dart commands work? You might try upgrading to a later dart sdk version.

**Comment by Archisio** [comment]
I had the same issue. The problem was that I had installed Flutter and Dart both individually, as Flutter already has Dart in the bin/cache/dart-sdk, I also had added both to environment variables path. My fix was to remove Dart (Standalone Installed One) and also remove it from environment variables path. Finally add the Flutter bin/cache/dart-sdk to my environment variable path.
