### ISSUE TITLE
RawDatagramSocket stops listening when an empty Datagram received

### ISSUE THREAD

**Issue by easeccy** [dart-lang/sdk#39910]
```
import 'dart:io';
 
void main() {
  RawDatagramSocket.bind(InternetAddress.anyIPv4, 8585)
      .then((RawDatagramSocket socket) {
    socket.listen((RawSocketEvent e) { 

      if (e == RawSocketEvent.read) {
        socket.receive();
        print('Some data received.'); 
      } 

    });
  });
}
``` 
In this simple code, server prints the message on every received datagram until it gets one empty datagram. Then it stops listening, no further datagrams will not trigger the received event callback.

Dart VM version: 2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by devoncarew** [comment]
Do you know if there any exceptions thrown?
