### ISSUE TITLE
Duplicated diagnostic for default values in function types

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39919]
Sometimes (maybe always) the diagnostics `CompileTimeErrorCode.DEFAULT_VALUE_IN_FUNCTION_TYPED_PARAMETER` and `ParserErrorCode.DEFAULT_VALUE_IN_FUNCTION_TYPE` are reported together. The non-parser code should not be reported when the parser code has already been reported.

**Comment by srawlins** [comment]
Looks like this has been fixed. There is not a single test in which these two codes (or similar) are reported together.
