### ISSUE TITLE
Analyzer: Accessing an element's type's named import prefix

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#39927]
Hi there,

I'm in a situation where I'm generating code to a part file that needs to produce type names using the named import prefixes found in main library file.

Here's a contrived example. Let's say I'm analyzing the following:
```dart
import 'dart:io' as io;
part 'file.g.dart';

io.File someFile;
```

and I'm looking to generate:
```dart
part of 'file.dart';

io.File getSomeFile() {
  return someFile;
}
```

If I have `someFile`'s element in hand, is there any way to see that its type is written using the named import prefix? Or tracking the use of the type back to its import statement?

For now I'm using the AST, which works in many situations, but feels wrong, and I'm losing a lot of the analyzer's smarts by doing it this way.

Thanks!

**Comment by bwilkerson** [comment]
It's possible, but not as easy as it potentially could be. You'll need to

1. Get the type of `someFile` and get the type's element (`importedElement`).
1. Get the library in which `someFile` is declared (`importingLibrary`).
1. Iterate over the imports associated with the `importingLibrary` to find the ones (plural) whose `namespace` maps the name of the `importedElement` to the `importedElement`.
1. If there are multiple, choose one of them, then use the prefix (if any) associated with the selected import.

There's nothing wrong with using the AST to access syntactic information (it's also part of the public API available to you), and that might well be the best way to access the prefix.

**Comment by shyndman** [comment]
I'm comfortable with that approach. Thanks Brian.

The AST is working great for the general case, but gets complicated when inference is involved. We originally moved to using the AST because the `build` library failed to resolve `dart:ui` types, but now that it does, I'd like to move back to letting the analyzer do more work on our behalf.

**Comment by shyndman** [comment]
I ended up using the internal `NamespaceBuilder` class because of its handling of combinators. Worth considering as part of the public API, imho.

**Comment by bwilkerson** [comment]
> The AST ... gets complicated when inference is involved.

Could you explain what complications you ran into?

> I ended up using the internal `NamespaceBuilder` class because of its handling of combinators.

I can't recommend doing that because we aren't making any guarantee to not change that class and hence might break your use case. Nor do I expect that we'll make it part of the public API.

But I do think we should consider how to support this use case better. Just brainstorming, but I think I'd rather see an API that would allow you to ask for the prefix (if any) that needs to be used when referencing an imported identifier within a compilation unit.

@stereotype441 @scheglov for additional thoughts.

**Comment by shyndman** [comment]
> > The AST ... gets complicated when inference is involved.
> 
> Could you explain what complications you ran into?

Our library looks at a user-defined class, and produces a mixin to decorate in additional functionality. The mixin roughly mirrors the shape of the class, and requires that we reference the same types.

My work with the AST was aiming to solve two problems — produce `dart:ui` types in generated code (previously the `build` library would present these types as `dynamic`), and to preserve prefixes as written. I did this by working with an unresolved AST, and pulling type nodes from member declarations.

Which means it was a strict requirement that all members be annotated. I couldn't see what was going on if someone wrote:

```dart
class Store {
  @observable
  var inferredString = '12345';

  @observable
  var inferredList = [WidgetA(), WidgetB(), WidgetC()];
}
```

But now that we have everything working with elements, I'm very happy to be rid of that code. It was only intended as a stop-gap until `build` caught up with our needs.

> > I ended up using the internal `NamespaceBuilder` class because of its handling of combinators.
> 
> I can't recommend doing that because we aren't making any guarantee to not change that class and hence might break your use case. Nor do I expect that we'll make it part of the public API.
> 
> But I do think we should consider how to support this use case better. Just brainstorming, but I think I'd rather see an API that would allow you to ask for the prefix (if any) that needs to be used when referencing an imported identifier within a compilation unit.
> 
> @stereotype441 @scheglov for additional thoughts.

Ack. We're tight on our dependencies' version ranges, so good for now. I'll pull builder logic into our codebase if you make changes.

And thank you. I'd be happy to move to a blessed solution when one becomes available.

**Comment by bwilkerson** [comment]
> ... working with an unresolved AST ...

Ah, now I understand. If you had a resolved AST then a lot of that information would also be available from the AST itself (such as the inferred types of variables).

I believe that the build package can provide a resolved AST, so that's another avenue you might want to explore at some point.

**Comment by shyndman** [comment]
> > ... working with an unresolved AST ...
> 
> Ah, now I understand. If you had a resolved AST then a lot of that information would also be available from the AST itself (such as the inferred types of variables).
> 
> I believe that the build package can provide a resolved AST, so that's another avenue you might want to explore at some point.

Right. I think that at the time `build` was using a `RestrictedAnalysisContext`, and I couldn't figure out how to get the resolved AST out. I very well could have missed something. :)

**Comment by scheglov** [comment]
> I ended up using the internal `NamespaceBuilder` class because of its handling of combinators. Worth considering as part of analyzer's public API, imho.

[`ImportElement.namespace`](https://pub.dev/documentation/analyzer/latest/dart_element_element/ImportElement/namespace.html) handles combinators.

**Comment by shyndman** [comment]
It most certainly is. Thanks @scheglov. I'll switch over ASAP.
