### ISSUE TITLE
vm/dart/causal_stacks/async_throws_stack_test fails on optcounter linux bots.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#39926]
https://dart.googlesource.com/sdk/+/72f4a831aabe2680e2cec1e7df4a01d111443ff7 broke vm/dart/causal_stacks/async_throws_stack_test on vm-kernel-optcounter-threshold-linux-release-x64, vm-kernel-optcounter-threshold-linux-release-ia32.

Offending CL was a revert of a change that actually fixed the test, but that change was reverted due to performance regression.

@cskau-g @mkustermann

**Comment by mkustermann** [comment]
This is most likely related to deoptimizations happening. Closing in favor of https://github.com/dart-lang/sdk/issues/48338 as there is more information there.
