### ISSUE TITLE
Comparison bool and int

### ISSUE THREAD

**Issue by Papirosnik** [dart-lang/sdk#39925]
Android Studio (version 3.5)
Dart 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)  on "macos_x64"

Hi there.
I've changed type of a variable from __*int*__ to __*bool*__ but have accidentally forgotten to change its usage in condition clause. And nothing wrong happened. Except, method logic became inverted and app behaviour has been changed. 
Without any warning.

An simplified example:

```
bool isCellDisabled() => true;

void main() {
  bool disabledCell = isCellDisabled();
  if (disabledCell == 42) {

...
```

And at least dartpad gives me a warning in this case:

> Equality operator '==' invocation with references of unrelated types - line 5

It would be nice to get smth like that on Android Studio on osx too.
Either some option already exists and I've just miss it?

Regards!

**Comment by devoncarew** [comment]
Hmm, I do see that warning when I try your example out in IntelliJ:

```
info: Equality operator `==` invocation with references of unrelated types. (unrelated_type_equality_checks)
```

Perhaps you have some analysis options which disable the `unrelated_type_equality_checks` hint?

**Comment by Papirosnik** [comment]
I didn't performe any special actions on ide (android studio), just used everything out of the box

Regards,
Slava K.

________________________________
