### ISSUE TITLE
Analyzer rejects iterating over value of type Never

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39939]
```dart
void main() {                                                                       
  Never x;                                                                       
                                                                                 
  for(var y in x) {}                                                             
}
```

Analyzer rejects this with:

```
error • The type 'Never' used in the 'for' loop must implement Iterable. • lib/test.dart:4:16 • for_in_of_invalid_type
```

The CFE produces no error

```
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      main (package:test/test.dart:4:16)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by lrhn** [comment]
For the record, the spec says:
> It is an error if the object being iterated over by a `for`-`in` loop has a static type which is not `dynamic`, and is not a subtype of `Iterable<dynamic>`.

There are no further changes to for-in iteration in the NNBD specification

`Never` *is* a subtype of `Iterable<dynamic>`.

So the semantics of `for (D id in e) ...` is equivalent to that of:
```dart
T id_1 = e;
var id_2 = id_$.iterator;
while (id_2.moveNext()) {
  D id = id_2.current;
  ...
}
```
where *T* is the static type of `e` when that is not a top-type (which here means `dynamic`).
In this case, *T* is  `Never`, this code is valid and it infers `Never` for the type of `id` (and `id_2`).

**Comment by MichaelRFairhurst** [comment]
The only weird thing here is to me is, what should the inferred type of y be?

**Comment by natebosch** [comment]
Is it feasible for us to make it an error to iterate over `Never`? If we can't, will we be adding a warning or hint?

**Comment by lrhn** [comment]
The analyzer can, and probably should, report any use of a `Never` typed expression as "dead code".

We do not consider unreachable code an *error*, but it is still unreachable.

**Comment by scheglov** [comment]
@lrhn I'm looking at `17.6.3 Asynchronous For-in`, but cannot find similar compile-time errors as for `17.6.2 For-in`. It only says about "dynamic type error": "The expression `e` is evaluated to an object `o`. It is a dynamic type error if `o` is not an instance of a class that implements `Stream`. It is a compile-time error if `D` is empty and `id` is a final variable." 

Also, no analogue of "If the static type of e is a top type (14.2) then `T` is `Iterable<dynamic>`" for async for-in.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/137681

**Comment by eernstg** [comment]
The static rules for asynchronous for-in statements were never specified (which is true for a number of other constructs as well). Fixing them whenever possible and in particular when it comes up, I created dart-lang/language#861. @lrhn, a review would be welcome! ;-)
