### ISSUE TITLE
How can i make a card clickable in this code ??

### ISSUE THREAD

**Issue by TheVegHunter** [dart-lang/sdk#39934]
`import "package:firebase_database/firebase_database.dart";
import 'package:flutter/material.dart';
import 'package:rotibankadminapp/volunteers/VolunteerList.dart';

class Home extends StatefulWidget {
  HomeState createState() => HomeState();
}

class HomeState extends State<Home> {
  List<VolunteerList> lists = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    DatabaseReference ref =
    FirebaseDatabase.instance.reference().child('VolunteerRegistration');
    ref.once().then((DataSnapshot snap) {
      var KEYS = snap.value.keys;
      var DATA = snap.value;
      lists.clear();
      for (var individualKey in KEYS) {
        VolunteerList volunteer = VolunteerList(
          DATA[individualKey]['aadharpan'],
          DATA[individualKey]['email'],
          DATA[individualKey]['name'],
          DATA[individualKey]['location'],
          DATA[individualKey]['age'],
          DATA[individualKey]['days'],
        );
        lists.add(volunteer);
      }
      setState(() {
        print("length :${lists.length}");
        print('${snap.value}');
        //print('${name}');
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build

    TextField(
      decoration: InputDecoration(
          prefixIcon: Icon(
            Icons.search,
            color: Colors.black.withOpacity(0.5),
          ),
          focusedBorder:
          OutlineInputBorder(borderSide: BorderSide(color: Colors.black)),
          border:
          OutlineInputBorder(borderSide: BorderSide(color: Colors.black)),
          hintText: 'Search Volunteers'),
    );
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Volunteer List',
        ),
      ),
      body: Container(
        child: lists.length == 0
            ? Text("No volunteers found")
            : ListView.builder(
          itemCount: lists.length,
          itemBuilder: (_, index) {
            return ListUI(
              lists[index].aadharpan,
              lists[index].email,
              lists[index].name,
              lists[index].location,
              lists[index].age,
              lists[index].days,
            );
          },
        ),
      ),
    );
  }

  Widget ListUI(String aadharpan, String email, String name, String location,
      String age, String days) {
    return Card(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(15.0),
      ),
      elevation: 15.0,
      margin: EdgeInsets.all(15),

      child: Column(

        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisSize: MainAxisSize.max,
        children: <Widget>[

          Text(
            name,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.start,
          ),
          Text(
            aadharpan,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.start,
          ),
          Text(
            email,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.left,
          ),
          Text(
            location,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.center,
          ),
          Text(
            age,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.start,
          ),
          Text(
            days,
            style: Theme
                .of(context)
                .textTheme
                .subtitle,
            textAlign: TextAlign.start,
          ),
        ]
        ,
      )
      ,
    );
  }
}
`

**Comment by devoncarew** [comment]
You might want to explore some of the docs or community resources available for flutter devs; https://flutter.dev/docs, and https://flutter.dev/community.
