### ISSUE TITLE
I'm not able to run flutter and i keep getting this Error " No pubspec.yaml file found. This command should be run from the root of your Flutter project. Do not run this command from the root of your git clone of Flutter."

### ISSUE THREAD

**Issue by shadizghe** [dart-lang/sdk#39940]

**Comment by devoncarew** [comment]
It sounds like you're trying to run a flutter command from your flutter sdk directory, when it instead wants to run from your project directory. You may want to walk through one of the dart or flutter getting started guides: https://flutter.dev/docs/get-started/codelab.
