### ISSUE TITLE
Analyzer ignores this-type-check in static extension method

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#39959]
Due to the lack of polymorphism with static extension methods, I am forced to extend the base class and do type checks to differentiate between subclass implementations. Not sure this is the intended way to solve my problem? It works as expected with the runtime.

However, the Dart Analyzer fails to resolve variables and methods within the type check:

```dart
class Base {}

class Sub extends Base {
  final int value;
  Sub(this.value);
  void printer() => print('SubPrinter');
}

extension BaseExtension on Base {
  void foo() {
    if (this is Sub) {
      print('Sub($value)'); // error: Undefined name 'value'.
      printer(); // error: The method 'printer' isn't defined for the class 'Base'.
    } else {
      print('Base()');
    }
 }
}

void main() {
  Base().foo();  // correctly prints 'Base()'
  Sub(42).foo();  // correctly prints 'Sub(42)' and 'SubPrinter'
}
```

Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64".

**Comment by scheglov** [comment]
@lrhn should analyser perform type promotion of `this` inside extensions?

**Comment by lrhn** [comment]
If it does type promotion anywhere else, then it should do so inside extension methods too. 

The goal is that there is no visible difference between an extension method and an instance method written the same way. Things should promote the same way everywhere.

**Comment by scheglov** [comment]
@lrhn Hm... No, analyzer does not do type promotion of `this` is classes. Should it?

**Comment by lrhn** [comment]
I don't think we do that prior to NNBD. With NNBD, I do believe we promote `this` the same way as local variables (or maybe we don't, and it's just wishful thinking on my part. @stereotype441?)

**Comment by srawlins** [comment]
There is currently no type promotion for `this`. It is being considered at https://github.com/dart-lang/language/issues/1397. If the idea is accepted, analyzer will implement the promotion.
