### ISSUE TITLE
Restart server when the source file changes

### ISSUE THREAD

**Issue by mymikemiller** [dart-lang/sdk#39951]
An http server can be run with the following command:

`dart server.dart`

That command needs to be rerun to pick up any source file changes. It would be nice to have a tool that watches for file changes and restarts the server when detected, similar to what `webdev serve` does for web servers.

I'm new to using dart on a server; maybe there's already a way to do this. If so, please excuse my ignorance but I wasn't able to find anything online.

**Comment by keertip** [comment]
@mymikemiller, you can reach out to the community through any of the forums listed at https://dart.dev/community to get an answer.
