### ISSUE TITLE
SocketException: OS Error: Connection reset by peer

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/sdk#39966]
This exception is being raised randomly on AWS ec2
After this exception is raised, the process exits with exit code 255, but tcp port is still in use

**Comment by keertip** [comment]
@lesnitsky , can you provide more details? How can we repro the issue?

**Comment by keertip** [comment]
Closing as there is not enough information to figure out the issue.

**Comment by 1996SEJR** [comment]
I have similar problems, I share this link:
[https://stackoverflow.com/questions/64009822/socketexception-in-flutter](url)

**Comment by fryette** [comment]
For me the solution is adding the next header `accept-encoding: gzip, deflate, br`
Had 100 percent same issue
