### ISSUE TITLE
NoSuchMethodError: The getter '_duration' was called on null.

### ISSUE THREAD

**Issue by MahdiPishguy** [dart-lang/sdk#39960]
```dart
E/flutter (16830): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter '_duration' was called on null.
E/flutter (16830): Receiver: null
E/flutter (16830): Tried calling: _duration
E/flutter (16830): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (16830): #1      Duration.> (dart:core/duration.dart:163:61)
```

that means i get this error on this file as `duration.dart` and this line of code:

```dart
  bool operator >(Duration other) => this._duration > other._duration; //line 163
```

**Comment by keertip** [comment]
@MahdiPishguy, can you add more details? How can we repro this error?

**Comment by MahdiPishguy** [comment]
@keertip since i can remember that, when i try to use `video_player` i get this error on playing video from url

**Comment by keertip** [comment]
@MahdiPishguy , this has to do with flutter. You will more likely get answers from the flutter community at https://flutter.dev/community or the docs https://flutter.dev/docs.
