### ISSUE TITLE
dart2js: NullCheck runtime library and optimization issues

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#39978]
The null check operator (postfix `!`) is defined to throw a `CastError` when the operand is `null`, otherwise it evaluates to the operand.

This will be implemented in SSA as a `HNullCheck` instruction that works like other checks, with the use of the check instruction ordering the dependency.

We want to compile `o!` to something short, like `o.toString;` or `o.a;` where the static and/or inferred type of `o` is a class with a field compiled to JavaScript property `a`.  We don't want it to compile to a call to a `notNull` method, since that will in most cases incur the cost of the call.

### Runtime support

- How do we diagnose a `CastError` for `o.a`, when it could also be a `NoSuchMethodError` a field getter in legacy code?
- Is it legal for the Error class to implement both CastError and NoSuchMethodError?

### Optimizations

dart2js has a similar concept of a null-receiver-guard that is inserted into the code when inlining a method when it is the single target of the receiver type ignoring nullability.
The null-receiver-guard is somewhat of a hack. It is a special case of the `HFieldGet` instruction with no use. The `canThrow` property of the instruction is used to limit code motion to preserve the order of exceptions. The optimizer _should_ be using `HTypeKnown`(witnessed form) after a potential null deference via `HFieldGet` to strengthen the operand type but this is not currently done.

It is desirable to remove the special case of `HFieldGet` and replace it with `HNullCheck`, and implement the optimizations that removes the null check when followed by an instruction that faults on `null` on the same operand. This optimization is very worthwhile on Dart 2 legacy code where many methods are inlined on potentially null receivers.

- [x] Use `HNullCheck` for null receiver guards
- [x] Fix dead code elimination to replace `HNullCheck`-followed-by-`HFieldGet` with `HFieldGet`-followed-by-`HTypeKnown`.
- [x] Perhaps keep `HNullCheck` until instruction selection and only eliminate it in favor of a following faulting instruction after all code motion.

See #35996 for problems with existing dummy field load implementation.

**Comment by mit-mit** [comment]
@rakudrama it appears this was merged; can the bug be closed?

**Comment by rakudrama** [comment]
Not yet. There is the remaining issue of the error thrown.

**Comment by sigmundch** [comment]
(last issue was fixed via 3d6c560ba173ae9cf2813748885d023fb98af630)
