### ISSUE TITLE
dart2js: add flag to select nnbd-mode in dart2js

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39979]
the flag will configure how code is generated (weak vs strong).

**Comment by natebosch** [comment]
Is this a temporary flag available during a transition, or will it be permanent?

Can you clarify the difference in the generated code?

**Comment by sigmundch** [comment]
It's a transition flag, but I expect it will be available until Dart 3 when weak-mode can be removed.

The change affects semantics of the generated code for  `is`, `as`, implicit checks (e.g. covariant parameter checks, type bound checks on instantiations) and any other subtype checks.

It's possible that the difference is implemented by calling different helper methods during codegen, or by using a constant-like value in our SDK libraries that is filled-in depending on the value of this flag. If we can, I like the idea of doing the latter so we can keep the change minimal.

Note that DDC today doesn't have the flag because it is a global setting. Like other global settings in ddc, we expose it via a top-level method in our runtime, which is invoked from JavaScript from the HTML file that links the app together (e.g. the file generated by test.py).

**Comment by sigmundch** [comment]
New specification is here: https://github.com/dart-lang/language/pull/779

**Comment by sigmundch** [comment]
The flag exists, but we need to plumb its value to the CFE still
