### ISSUE TITLE
Don't write Observatory banner to stdout when using --write-service-info

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#39975]
When passing [`--write-service-info`](https://github.com/dart-lang/sdk/issues/38418) to the VM, the Observatory info is still written to stdout:

```
danny@Dannys-MBP v2.8.0-dev.0.0 % bin/dart --observe --write-service-info=/tmp/service.json bin/snapshots/analysis_server.dart.snapshot --lsp
Observatory listening on http://127.0.0.1:8181/DAf9YiCNZWg=/
```

This prevents enabling the VM service for debugging the LSP server, as stdout has to conform explicitly to the LSP protocol and this line of text is not valid (which causes LSP clients to error).

Although technically breaking, I don't think anyone is using this flag yet (and if they are, it's unlikely they're also parsing the banner). Otherwise maybe we'd need another flag to suppress the output?

(cc @bkonyi)

**Comment by bkonyi** [comment]
I'm not sure we can suppress that output by default when the flag is provided since other tools could be expecting the Observatory to be written to stdout. I think the best bet is to add a flag to suppress output from the VM service.

**Comment by DanTup** [comment]
I thought the purpose of this new flag was specifically to move off scraping stdout (so a tool shouldn't pass it unless it's going to use the json?). It's not a big deal to me how it's handled though, as long as there's *some* way to enable the VM service for the LSP server without it writing to stdout (while still allowing us to get at a URL with the auth token).

**Comment by bkonyi** [comment]
Adding this flag was more for clients that _couldn't_ scrape stdout so they had some way to get the service authentication codes. I didn't really have any intention of removing the print to console, especially with major customers like flutter_tools still relying on this behavior.

**Comment by DanTup** [comment]
Sure - but my thinking was that flutter wouldn't pass `--write-servive-info` unless it was going t start using the JSON file instead. My assumption was that the tool spawning the VM is the tool scraping stdout/reading the JSON - though I don't know if that's correct.

Again though, an extra flag would be fine by me - there just needs to be some way to suppress it to allow debugging when `stdout` is being consumed directly by a tool not under our control. Thanks! :-)

**Comment by natebosch** [comment]
You should be able to use `dart -DSILENT_OBSERVATORY=true --observe`

**Comment by bkonyi** [comment]
> You should be able to use `dart -DSILENT_OBSERVATORY=true --observe`

Ah yes, I totally forgot about that. That should solve the problem.

**Comment by DanTup** [comment]
Me too - I think that'll work fine. Thanks!
