### ISSUE TITLE
Different behavior of tear-off in VM vs JS

### ISSUE THREAD

**Issue by rkj** [dart-lang/sdk#39972]
When doing tear-off methods in the JS it returns the same reference each time (identical == true), but in VM it does return different one each time.

Code: https://gist.github.com/rkj/a69f9b9b9cdc9349a6ca5f1570fe0b68

VM:
```sh
$ dart tearoff.dart 
true
false
```

Web: https://imgur.com/a/ElZC0Kz

**Comment by sigmundch** [comment]
I believe this is working as intended.

The specification (section "16.22.3 Ordinary Member Closurization") requires that `==` is true in your example:

> Assume that o1 and o2 are objects, m is an identifier, and c1 and c2 are function objects obtained by closurization of m on o1 respectively o2. Then c1 == c2 evaluates to true if and only if o1 and o2 is the same object. 

Later it also clarifies that `identical` is not guaranteed to be true, but it allows some implementations to return `true` if they want:

> In particular, two closurizations of a method m from the same object are equal, and two closurizations of a method m from non-identical objects are not equal. Assuming that `vi` is a fresh variable bound to an object, i ∈ 1..2, it also follows that `identical(v1.m, v2.m)` must be false when v1 and v2 are not bound to the same object. However, Dart implementations are not required to canonicalize function objects, which means that `identical(v1.m, v2.m)` is not guaranteed to be true, even when it is known that v1 and v2 are bound to the same object.

I've tagged this under area-specification in case some of the language team members disagree and would like to reopen.

**Comment by rkj** [comment]
FYI (and for my recollection): this is also different in Dart2js vs DDC, leads to tests & code behaving differently in those two envs. Would be awesome if at least they could be kept in sync.

**Comment by rakudrama** [comment]
Since the result of `identical(a, b)` is unspecified, dart2js will optimize two calls to a tear-off getter (i.e. `foo._foo`), reusing the first one.
If `tearOff` is annotated to not be inlined, then there are two tearoff closure objects (created at twice the cost):

```dart
class Foo {
  void _foo() => null;
  @pragma('dart2js:noInline')
  void Function() get tearFoo => _foo;
 }

void main() {
  var foo = Foo();
  var a = foo.tearFoo;
  var b = foo.tearFoo;
  print(a == b);
  print(identical(a, b));
}
```
This program prints
```
true
false
```
It is not going to be possible to make DDC have this optimization. It depends on exactly the same inlining to bring together the two calls to `foo._foo`.

The question is: should dart2js be changed to avoid making the program smaller and faster within the specification because it is detectable?

**Comment by eernstg** [comment]
I think we should keep the current specification and the current behavior as it is (and I agree that there is no conflict, and hence it's fine that this issue has been closed with 'working as intended').

We just need to keep saying that the correct equality test on function objects obtained by tearing off an instance method is `operator ==`. An optimization might make `identical` return the same answer, but it is not safe and not portable to rely on that optimization.

The performance difference may be significant: `identical` is resolved statically and could be inlined as  very few instructions when applied to expressions whose static type is, e.g., a function type, whereas `operator ==` is a regular instance method, subject to late binding. So it may be quite useful to be able to guarantee that `identical` will provide the correct comparison.

However, if we wish to invest in offering this kind of performance improvement I think we should aim for optimizations where `f1 == f2` is compiled as `identical(f1, f2)` when that's known to be correct. Developers should stick to the rule that the correct test is written using `operator ==`.

**Comment by rkj** [comment]
Thanks for explanations, it all makes sense. I agree not worth making changes to spec.

I guess it's just the case of Angular being Angular. I run into this issue while trying to figure out why `UnstableExpressionError` is being thrown for some benign looking code. Angular uses `identical` exactly for performance reasons. Given the dart2js behavior is performant I think this is not a serious issue, just annoyance in testing.
