### ISSUE TITLE
Consider converting return types to Never (at least internally) for methods that never return

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39983]
In `collection/lib/src/combined_wrappers/combined_list.dart`, on line 60:
```
bool remove(Object element) {
  _throw();
  return null!;
}
```
where `_throw` is defined on line 18 as:
```
static void _throw() {
  throw UnsupportedError('Cannot modify an unmodifiable List');
}
```
The return was likely added to work around an analyzer diagnostic about a missing return. It would be nice if we could update `_throw` to have a return type of `Never` and remove the return in `remove`. And if we did that we'd probably want to remove the dead code after the invocation.

Semi-independently, there is an annotation (`alwaysThrows`) that might make a good hint to the migrator. That annotation was added for use by the `test` package, IIRC, so supporting it might make it easier to migrate `test`.

**Comment by bwilkerson** [comment]
We might also want lint / fix / assist support for this kind of code. @pq

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
