### ISSUE TITLE
Null check operator after generative constructor invocation

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39982]
In `collection/lib/src/canonicalized_map.dart`, on line 145:

```
V? update(K key, V? Function(V?) update, {V? Function()? ifAbsent}) => _base
    .update(_canonicalize(key), (pair) => Pair(key, update(pair.last)),
        ifAbsent: ifAbsent == null ? null : () => Pair(key, ifAbsent())!)
    .last;
```

Note the null check after `Pair(key, ifAbsent())`, which I believe applies to the constructor invocation. (If I'm wrong and it binds to something else, let me know.)

The hover reads

> Added a non-null assertion to nullable expression.
> - node with no info (migrated_3)

which doesn't provide any useful information.

My guess at this point is that this is an attempt to insert a null check on a parent of the invocation and that it just isn't inserting the required parentheses (which is a known problem and might be captured elsewhere). But I might be wrong.

**Comment by srawlins** [comment]
This migration is quite different now, I suspect because of the FixBuilder. The `update` method is now migrated to:

```dart
  V update(K key, V Function(V) update, {V Function()? ifAbsent}) => _base
      .update(_canonicalize(key), (pair) => Pair(key, update(pair.last)),
          ifAbsent: ifAbsent == null ? null : () => Pair(key, ifAbsent()))
      .last;
```

Re-open if I'm wrong.
