### ISSUE TITLE
DateTime difference is off

### ISSUE THREAD

**Issue by EliasDeuss** [dart-lang/sdk#39989]
What I am getting from .difference()

Code:
```print("difference in days: " + DateTime.parse(date).difference(DateTime.now()).inDays.toInt().toString() + ' - ' + DateFormat.yMMMd().format(DateTime.parse(eventDateEnd.toString())).toString() + ' - ' + DateTime.now().toString()); ```

Output: ```difference in days: 1 - Jan 8, 2020 - 2020-01-05 21:41:26.365045```

**Comment by lrhn** [comment]
Can you say what the precise values of the `date` and `eventDateEnd` are?

The difference appears to be between the `date` and `DateTime.now()` and not the `eventDateEnd` and now, which you print afterwards. Should one of those two be a different variable?

**Comment by EliasDeuss** [comment]
@lrhn 

DateTime.now(): ```2020-01-05 21:41:26.365045```
date & eventDateEnd: ```2020-01-08 00:00:05.000Z```

**Comment by lrhn** [comment]
So `date` is a UTC time and `now()` is local time. Your Github profile lists you as "Bay Area", which I'll assume is UTC-8, so the corresponding UTC time for `now` would be `2020-01-0605:41:26.265045Z`.

That makes the difference between the two points in time 42:18:38.735, which is less than two days, so the difference in whole days should indeed be 1.
So, this is working as intended.
