### ISSUE TITLE
Dart:ffi, Failed to lookup my function symbol 

### ISSUE THREAD

**Issue by CLARKYJ** [dart-lang/sdk#39993]
This tracker is for issues related to:
* Dart core libraries ("dart:ffi")
* Dart vm

Env:
* Dart SDK Version 3.7.1
* MacOs
* Android

what I have done:
* create demo from flutter.dev/docs/development/platform-integration/c-interop,
   and it works.
* compile my own framework(libmarsstn.so). It contains a function which is 
`   extern  __attribute__((visibility("default"))) int32_t native_add2(int32_t x, int32_t y) __attribute__((used));`

* use nm libmarsstn.so | grep native_add2, and in the so, it can be found:
000000000003c2bc t native_add2

* put the framework in my demo's jni folder.

* run flutter to call native_add2 function. it failed. my code is
```
final DynamicLibrary nativeMarsLib = Platform.isAndroid ? DynamicLibrary.open("libmarsstn.so") : DynamicLibrary.process();
    Pointer<NativeFunction> nativeFuncPtr = nativeMarsLib.lookup<NativeFunction<nativeAdd2Sign>>("native_add2");
    final int Function(int x, int y) nativeAdd2 = nativeMarsLib.lookup<NativeFunction<nativeAdd2Sign>>("native_add2").asFunction();
```
* stact trace:
```
I/flutter (32248): The following ArgumentError was thrown building App(dirty, state: AppState#86316):
I/flutter (32248): Invalid argument(s): Failed to lookup symbol (undefined symbol: native_add2)
I/flutter (32248):
I/flutter (32248): The relevant error-causing widget was:
I/flutter (32248):   App 
package:multiplatform/main.dart:31
I/flutter (32248):
I/flutter (32248): When the exception was thrown, this was the stack:
I/flutter (32248): #0      DynamicLibrary.lookup  (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:29)
I/flutter (32248): #1      AppState.build 
package:multiplatform/main.dart:63

```

**Comment by CLARKYJ** [comment]
and i found that，when DynamicLibrary.open, normal so has positive hashcode, but my so has a negative hashcode value.

**Comment by CLARKYJ** [comment]
ok，I found out why， my function is localized， not global. After I made it global, it works fine.

**Comment by Dolaned** [comment]
@CLARKYJ what do you mean by global? im trying to compile code with xcode into a flutter app and having the same issue

**Comment by AnhPC03** [comment]
@CLARKYJ how did you make it global?

**Comment by aadarsh-patel** [comment]
@AnhPC03 @Dolaned To make any variable/function global you need to declare it outside the class.

For example,

**dog.dart**
```dart
// This function is global.
void bark(){
  print("Bark");
}

class Dog{
  // This function is not global.
  void bark(){
    print("Bark");
  }
}
```

**Comment by masonhorder** [comment]
@CLARKYJ how did you make your function global? i am having the same issues, thanks, mason

**Comment by weishirongzhen** [comment]
> and i found that，when DynamicLibrary.open, normal so has positive hashcode, but my so has a negative hashcode value.

my issue also same with that , got a  negative hashcode  when open so, any idea?

**Comment by walkerwg** [comment]
i having the save problem too. any idea?  need help!!! Thanks

**Comment by ovc-serega** [comment]
My use of inline functions caused this problem. When using ffi, do not use where inline functions are

**Comment by zhengbomo** [comment]
@CLARKYJ  how did you make it global?

**Comment by Skrell** [comment]
Man what a dick @CLARKYJ is

**Comment by Sunhill666** [comment]
Ok guys, i'm not a dick, here's my solution:
this is my `CMakeLists.txt`:

```text
# The Flutter tooling requires that developers have CMake 3.10 or later
# installed. You should not increase this version, as doing so will cause
# the plugin to fail to compile for some customers of the plugin.
cmake_minimum_required(VERSION 3.10)

project(dart_ncnn_yolov8_library VERSION 0.0.1 LANGUAGES CXX)

get_filename_component(PROJECT_FOLDER ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(ncnn_DIR ${PROJECT_FOLDER}/linux/ncnn/lib/cmake)
  set(OpenCV_DIR ${PROJECT_FOLDER}/linux/opencv-mobile/lib/cmake)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
  set(ncnn_DIR ${PROJECT_FOLDER}/android/src/main/cpp/ncnn/${ANDROID_ABI}/lib/cmake/ncnn)
  set(OpenCV_DIR ${PROJECT_FOLDER}/android/src/main/cpp/opencv-mobile/sdk/native/jni)
else()
  message(FATAL_ERROR "system not support: ${CMAKE_SYSTEM_NAME}")
endif()

find_package(OpenCV 4 REQUIRED)

find_package(ncnn REQUIRED)

include_directories(
  ${PROJECT_FOLDER}/src
  ${OpenCV_INCLUDE_DIRS}
)

add_library(dart_ncnn_yolov8 SHARED
  "dart_ncnn_yolov8.cpp"
)

set_target_properties(dart_ncnn_yolov8 PROPERTIES
  PUBLIC_HEADER dart_ncnn_yolov8.h
  OUTPUT_NAME "dart_ncnn_yolov8"
)

target_link_libraries(dart_ncnn_yolov8
    ncnn
    ${OpenCV_LIBS}
)

target_compile_definitions(dart_ncnn_yolov8 PUBLIC DART_SHARED_LIB)
```

And this is my headers file, plz notice that `extern "C"`:

```c
#if _WIN32
#include <windows.h>
#else
#include <pthread.h>
#include <unistd.h>
#endif

#if _WIN32
#define FFI_PLUGIN_EXPORT __declspec(dllexport)
#else
#define FFI_PLUGIN_EXPORT
#endif

#ifdef __cplusplus
extern "C" {
#endif

FFI_PLUGIN_EXPORT int add(int a, int b);

#ifdef __cplusplus
}
#endif

```
