### ISSUE TITLE
Flow analysis represents reachability as a single boolean, not a stack

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40009]
The flow analysis pull request (https://github.com/dart-lang/language/pull/763) defines `FlowModel.reachable` as a stack of booleans; this is necessary in order for promotions to work properly inside of unreachable code blocks, for example:
```dart
return;
if (x is! int) return;
x.isEven; // Should be OK
```
The current implementation defines `FlowModel.reachable` as a single boolean.  I'm not sure if the above case works by some other magic or not, but it seems like it would be best to just switch to the boolean stack defined by the spec proposal.

**Comment by stereotype441** [comment]
Note that this will also require implementing and wiring up the `split`, `drop`, `unsplit`, and `merge` functions documented in that same pull request.

**Comment by leafpetersen** [comment]
@stereotype441 is this fixed?

**Comment by stereotype441** [comment]
@leafpetersen the implementation doesn't currently use a stack, but so far I haven't found a concrete scenario where that leads to incorrect behavior.  I'm not sure where that leaves us.  I would still like to switch to a stack if time allows, so that we can have more confidence in the correctness of the implementation, but it seems like that is lower in priority unless we find a concrete bug.

**Comment by stereotype441** [comment]
After further investigation, it seems that promotion is currently broken inside dead code blocks, so I'm working on this now.
