### ISSUE TITLE
Real unboxed fields in the Dart VM

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#40004]
We would like to implement real unboxed fields for the Dart VM - at least in AOT mode.

We can rely on TFA to proof if fields are non-nullable and can therefore be unboxed. We start with unboxed `double` fields, but might extend this to `int` and maybe SIMD types.

The three approaches discussed are

  * Have two-sided objects, growing unboxed fields (with inheritance) on one side and GC fields on the other, the object pointer in the middle.
  * Have a separate typed-data array which we grow for unboxed fields and is introduced with first unboxed field (similar to how type-argument vectors)
  * Have the unboxed values directly in the object.

For now, @victoragnez will investigate the last approach.

Let's use this as a tracking bug.

/cc @sjindel-google

**Comment by mkustermann** [comment]
Is there anything remaining or can we close this issue?

**Comment by sjindel-google** [comment]
I believe this is complete, but we should make sure to take full advantage of null-safety when it's available.
