### ISSUE TITLE
Flow analysis does not implement the "factor" algorithm

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40014]
The flow analysis spec pull request (https://github.com/dart-lang/language/pull/763) defines a `factor` function that defines the "remainder" of a type `T` when another type `S` has been removed from consideration by an instance check.  If I'm understanding correctly, implementing it would mean that we could treat `if (x is Null)` as equivalent to `if (x == null)` as well as weird contrived cases like:
```dart
void f(int? x) {
  if (x is String?) return null;
  x.isEven; // Ok, because if x had been `null` then we would have returned.
}
```

**Comment by leafpetersen** [comment]
I believe the main motivating example for this is not nullable types but rather `FutureOr`.  This enables:

```
Future<int> test(FutureOr<int> x) {
  if (x is Future<int>) {
     return x.then((y) => y+1);
  }
  return Future.value(x + 1); // x has been promoted here.
}
```

This isn't critical functionality, so if it's a lot of work or doesn't work out cleanly we can drop it.  @lrhn has run into this a fair bit in real code, but he's probably not the median user.  It is something that if we ever do move forward with general union types we'd probably want to add later though, so there is some value to doing it now for forward compatibility.

**Comment by lrhn** [comment]
I don't think I'll be the only one. Any code working with `FutureOr<T>`, at a level other than simply always awaiting it, will have to do the test for `is Future<T>` and treat the `T` in the other branch.

**Comment by scheglov** [comment]
@leafpetersen I'm looking at `factor(T, S)` in [the spec](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md). And specifically, for in the context of this example:

```dart
void foo(int? a) {
  if (a is Null) {
    return;
  } else {
    a.isEven;
  }
}
```

Here I'd expect to get `a` promoted to `int` in `else`.
But it seems that there is a missing final `Else`, e.g. `Else T (or R maybe?)`.
What to do when none of the previous items match?

**Comment by scheglov** [comment]
@leafpetersen Also, does the rule for `instance check` correctly handles `tested` types? It uses `promote()` with `S` or `factor(T, S)` for `true` or `false` correspondingly. This results in `T1::tested` with the type that was given to `promote()`, not with the type that was tests, i.e. `S`. Is this the behavior that we want?

**Comment by leafpetersen** [comment]
> But it seems that there is a missing final `Else`, e.g. `Else T (or R maybe?)`.

Yes.  https://github.com/dart-lang/language/pull/864

> This results in `T1::tested` with the type that was given to `promote()`, not with the type that was tests, i.e. `S`. Is this the behavior that we want?

Ah, interesting.  I think it results in both being added eventually right?  That is, after the conditional below:

```dart
foo(FutureOr<int> f) {
  if (f is Future<int>) {
    // Future<int> is a type of interest here
  } else {
   // int is a type of interest here.
  }
  // Future<int> and int are both types of interest here
}
```

It does seem like we might want to have `Future<int>` be of interest in both branches:

```dart
foo(FutureOr<int> f) {
  if (f is Future<int>) {
     f.then(...);
  } else {
     // Demotes to FutureOr<int> then re-promotes to Future<int> if the latter is of interest?
     f = new Future.value(f); 
  }
}
```

@johnniwinther @stereotype441 @lrhn thoughts on this?

**Comment by stereotype441** [comment]
> > But it seems that there is a missing final `Else`, e.g. `Else T (or R maybe?)`.
> 
> Yes. [dart-lang/language#864](https://github.com/dart-lang/language/pull/864)
> 
> > This results in `T1::tested` with the type that was given to `promote()`, not with the type that was tests, i.e. `S`. Is this the behavior that we want?
> 
> Ah, interesting. I think it results in both being added eventually right? That is, after the conditional below:
> 
> ```dart
> foo(FutureOr<int> f) {
>   if (f is Future<int>) {
>     // Future<int> is a type of interest here
>   } else {
>    // int is a type of interest here.
>   }
>   // Future<int> and int are both types of interest here
> }
> ```
> 
> It does seem like we might want to have `Future<int>` be of interest in both branches:
> 
> ```dart
> foo(FutureOr<int> f) {
>   if (f is Future<int>) {
>      f.then(...);
>   } else {
>      // Demotes to FutureOr<int> then re-promotes to Future<int> if the latter is of interest?
>      f = new Future.value(f); 
>   }
> }
> ```
> 
> @johnniwinther @stereotype441 @lrhn thoughts on this?

Yeah, I agree.  Since "types of interest" informally means "types that we've tested against, regardless of whether the test passed", I think it would reduce user confusion if both branches to have the same set of types of interest.  So I would definitely say that `Future<int>` should be of interest in both branches.

**Comment by stereotype441** [comment]
@scheglov and I talked about this and we're going to move forward with what's discussed in the last comment, assuming from Leaf's silence that he agrees :)

**Comment by leafpetersen** [comment]
Sorry for the radio silence.  I agree that `Future<int>` should be of interest in both branches.  The question I had remaining in my head was whether `int` should also be of interest in both branches, only the second, or neither.  I think we at least want it to be of interest in the second branch, and I think that probably suggest doing it in both branches?  WDYT?

**Comment by stereotype441** [comment]
Agreed, making `int` a type of interest in both branches makes sense to me too.

**Comment by lrhn** [comment]
I think both parts of a union should be of interest in both branches of a union-type-part-test.
That will enable assignment promotion in cases like:
```dart
FutureOr<X> fox = ...;
if (fox is Future<X>) {
   fox = await fox;
}
// fox is X
```
or
```dart
FutureOr<X> fox = ...;
if (fox is X) {
  fox = Future.value(fox);
}
// fox is Future<X>
```
This matches the subtype promotion of 
```dart
num x = ...;
if (x is! int) {
  x = x.toInt();
}
```
only with positive tests instead of negative ones. (Although you should probably use negative tests in cases where the union is not disjoint).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144804
