### ISSUE TITLE
Flow analysis should intersect promotion lists when joining variable models

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40010]
The flow analysis pull request (https://github.com/dart-lang/language/pull/763) says that when joining two variable models, we should intersect the lists of promoted types.  What we're currently doing is to take the longest common initial sublist of the two lists of promoted types.  I think intersecting makes a lot more sense.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/40010
