### ISSUE TITLE
NNBD migration should support "fantasy land" functionality

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40017]
The idea is that if a user is migrating package X, and package X depends on package Y, which has not been migrated yet (but may have migration hints), the user wants to be able to put their filesystem into a state where they can execute the migrated version of packages X and Y together, in order run tests and see whether the migration looks correct.  We expect this will require writing out a fresh `packages.json` file as well as writing migrated source files to temporary directories.

**Comment by mit-mit** [comment]
@stereotype441 @kevmoo I believe we've decided against this?

**Comment by stereotype441** [comment]
> @stereotype441 @kevmoo I believe we've decided against this?

Correct.
