### ISSUE TITLE
Generic type parameter doesn't == to actual type

### ISSUE THREAD

**Issue by hongyiweiwu** [dart-lang/sdk#40018]
**Dart VM Version**: Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64"
**OS**: MacOS.

**Minimum Example**:
```
p<T>() {
    print(T == int);
}

main() {
    p<int>();
}
```

Currently the output is `true` if the non-nullable experiment is not enabled, and `false` if it's enabled. Not sure if this is intentional.

**Comment by lrhn** [comment]
It's not intended.
We haven't implemented the full intended `Type` object equality yet (it's based on type normalization which isn't implemented everywhere yet), but `int` being equal to `int` was never intended to not work.

**Comment by liamappelbe** [comment]
I'm not able to repro this.

How are you enabling and disabling the experiment? Currently you have to rebuild the sdk with the --nnbd flag: `tools/build.py --nnbd ...`

If you try to run a non-nnbd SDK with the experiment flag enabled, you should get an error. It looks like your SDK is just a bit too old to have this error message, so you'll instead get unexpected results like this.

**Comment by hongyiweiwu** [comment]
@liamappelbe I just updated to 2.8.0 dev 2 and this seems to have been fixed. I've closed the issue. Thanks for the feedback!
