### ISSUE TITLE
Poor readability of closures in generated JavaScript code

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#4003]
There are several factors that make code containing closures essentially incomprehensible:
1. The closures are all called ClosureN for various N.  They could have better names.  Instead of Closure123 the name could be e.g. containingFunction_Closure_2.  The names would still minify the same.
2. The closures are far from the functions.  If they can't be put in the function body at the point of closure creation, they should immediately follow the creating function (or class containing the creating function).
3. Closed names are obfuscated by long access paths (which causes further obfuscation by CSE).  See Issue #4001.
4. Closed names are obfuscated by suffixes.  Why this.box_0.first_3 when it could be this.vars.first?
5. Even when the ClosureN names are unavoidable, the essential superclass has a crazy name.  The superclass of all closures should be $$.Closure, not $$.Closure176 today and some other number tomorrow.

$$.Closure = {&quot;&quot;:
&nbsp;[&quot;this_0&quot;],
&nbsp;super: &quot;Closure176&quot;,
&nbsp;$call$0: function() {
&nbsp;&nbsp;return this.this_0.onLoad$0();
&nbsp;}
};
...
$$.Closure176 = {&quot;&quot;:
&nbsp;[],
&nbsp;super: &quot;Object&quot;,
&nbsp;toString$0: function() {
&nbsp;&nbsp;return 'Closure';
&nbsp;}
};

I am hoping that real JavaScript functions can be used as closures since then the code could compile to the obvious JavaScript program, using JavaScript's closures.  But if that is not possible, the above will still need to be addressed.

**Comment by karlklose** [comment]
@rakudrama Could you check what is still a problem in dart2js and update/close the bug?

**Comment by sigmundch** [comment]
I believe it still is an issue:
1. is resolved: we do use the name of the enclosing function + class
2. is not resolved: they are in the same library, but I've seen cases where they are a few hundred lines apart
3. I am not sure
4. is better: the variable name is `first`, but the box name still contains suffixes `_box_0`.
5. still appears to be an issue.
