### ISSUE TITLE
Questionable messaging because of type parameters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#40035]
In the collection package, in `lib/src/canonicalized_map.dart`, on line 89:

```
bool containsKey(Object? key) {
  if (!_isValidKey(key)) return false;
  return _base.containsKey(_canonicalize(key as K?));
}
```

This is a valid migration, but the explanation for the question mark on `key` is difficult to understand. The text reads "The corresponding parameter in the overridden method is nullable". The truth is that the corresponding parameter in the overridden method is `K`, which is potentially nullable. It might be better to be correct here, despite the fact that "potentially nullable" is a new concept for our users. (I think they're going to have to understand it anyway if they're using type parameters.)

**Comment by bwilkerson** [comment]
@MichaelRFairhurst @srawlins

**Comment by MichaelRFairhurst** [comment]
Isn't the overridden type `constainsKey(Object? key)`?

**Comment by bwilkerson** [comment]
Yes, sorry. I must have been looking at something else.

**Comment by MichaelRFairhurst** [comment]
it may be a good idea to link these up. If you accidentally looked at
something else and got thrown off, users definitely will do the same at
times too.

**Comment by bwilkerson** [comment]
We just have to decide how much of an IDE we're implementing here.
