### ISSUE TITLE
Migrate dart:vmservice to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40046]
Sub-issue of #38037 .

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by bkonyi** [comment]
Migration is up for review [here](https://dart-review.googlesource.com/c/sdk/+/131480).

**Comment by a-siva** [comment]
CL has landed.
