### ISSUE TITLE
Migrate dart:wasm and tests to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40043]
Sub issue of #38037 .

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by liamappelbe** [comment]
Done: https://dart-review.googlesource.com/c/sdk/+/131421

**Comment by munificent** [comment]
Hi, in that CL, I see the code was migrated, but not the tests. All of the tests at "tests/lib_2/wasm" need to by copied to "tests/lib/wasm" and also made NNBD clean.

Leaf sent out a doc with instructions on how to migrate tests. I'm working to improve that doc. In the meantime, let me know if you have any questions.

**Comment by liamappelbe** [comment]
I think the tests are already NNBD clean. I'll copy them to tests/lib/wasm

**Comment by munificent** [comment]
SGTM, thanks!
