### ISSUE TITLE
Migrate dart:cli and tests to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40044]
Sub-issue of #38037.

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/133866 should fix this.
