### ISSUE TITLE
Migrate dart:mirrors and tests to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40045]
Sub issue of #38037 .

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by eernstg** [comment]
Hi, @rmacnak-google, I considered migrating the tests. How would that fit into your plans?

**Comment by rmacnak-google** [comment]
Hi, @eernstg, I already have a CL with the tests migrated.

**Comment by eernstg** [comment]
OK, thanks!
