### ISSUE TITLE
Migrate dart:isolate and tests to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40042]
Sub issue of #38037 .

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by a-siva** [comment]
The library has been ported, port of the isolate specific tests are in progress.

**Comment by franklinyow** [comment]
Any update on this?  Thx!

**Comment by franklinyow** [comment]
Ping

**Comment by mit-mit** [comment]
cc @a-siva for status update

**Comment by a-siva** [comment]
The first part of this which is migrating the isolates tests away from the unittest package
landed yesterday https://dart-review.googlesource.com/c/sdk/+/139953.

The second part which migrated a large number of tests is being reviewed here
https://dart-review.googlesource.com/c/sdk/+/139980

After that lands we will have another CL today which moves the rest of the tests.

**Comment by a-siva** [comment]
With https://dart-review.googlesource.com/c/sdk/+/140162 the remaining isolate tests have been migrated.
tests/lib_2/isolate/isolate_stress_test.dart was not used by the VM and was probably an old dart2js
test. This file was not migrated.
