### ISSUE TITLE
Do not report missing members for `Never`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40057]
Member accesses on `Never` should be allowed (cf. https://github.com/dart-lang/language/issues/711#issuecomment-563965257) and issues arising because the resulting code is likely to be a bug should be handled by detecting and flagging unreachable code with a warning.

So a receiver of type Never is treated as if it had all member signatures, just like a receiver of type `dynamic`. For example, it is also assumed to have a setter named `s=` whose parameter type admits the argument `1`.

However, the analyzer reports in [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8891663887450837936/+/steps/test_results/0/logs/new_test_failures__logs_/0) concerning [static_errors_A13_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/static_errors_A13_t01.dart) that specific members do not exist for a receiver of type `Never`, and it is implied that there is a setter `s=`, but that it has argument type `Never` (cf. the error about line 24):

```
ERROR|STATIC_TYPE_WARNING|UNDEFINED_SETTER|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/static_errors_A13_t01.dart|30|9|1|The setter 's' isn't defined for the class 'Never'.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_SETTER|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/static_errors_A13_t01.dart|27|8|1|The setter 's' isn't defined for the class 'Never'.
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/static_errors_A13_t01.dart|24|11|1|A value of type 'int' can't be assigned to a variable of type 'Never'.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_SETTER|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/static_errors_A13_t01.dart|24|7|1|The setter 's' isn't defined for the class 'Never'.
```

**Comment by eernstg** [comment]
static_errors_A13_t02 shows the same issue.

**Comment by eernstg** [comment]
Note that #40126 reports the same issue, and includes detailed output from the analyzer.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
`static_errors_A13_t02` uses non-function `typedef`, so is not supported.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131706

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131721 will downgrade it from a warning to a hint.
