### ISSUE TITLE
DateTime difference calculation is wrong

### ISSUE THREAD

**Issue by Zazo032** [dart-lang/sdk#40059]
Run this code snippet on [DartPad](https://dartpad.dev/):

```dart
void main() {
  DateTime date1 = DateTime.parse('2020-03-31 00:00:00.000');
  DateTime date2 = DateTime.parse('2020-03-28 00:00:00.000');

  print(date1.timeZoneOffset);
  print(date2.timeZoneOffset);
  print(date1.difference(date2).inHours);
}
```

and you will get the this output:

```
2:00:00.000000
1:00:00.000000
71
```

There are 71 hours of difference, I think, because March 29th, we move 1 hour the clock (see time zone offsets). How can I get the correct difference (72 hours), as I wrote between 0:00 and 0:00?

**Comment by lrhn** [comment]
Use UTC dates instead of local time. In this case, it means putting a `Z` at the end of the date-time strings:
```dart
void main() {
  DateTime date1 = DateTime.parse('2020-03-31 00:00:00.000Z');
  DateTime date2 = DateTime.parse('2020-03-28 00:00:00.000Z');

  print(date1.timeZoneOffset); // 0:00:00.000000
  print(date2.timeZoneOffset); // 0:00:00.000000
  print(date1.difference(date2).inHours); // 72
}
```

The answer is correct for the times you put in: In local time there is exactly 71 hours between the two points in time.

**Comment by Zazo032** [comment]
That solved it, thanks @lrhn! Also, I just noticed there's a `DateTime.utc()` constructor.

**Comment by jhasty3** [comment]
This problem is still occurring. UTC is a good work around. But problem has persisited for 6 years?

[✓] Flutter (Channel stable, 3.46.0-1.0.pre-57, on macOS 26.5.2 25F84 darwin-arm64, locale en-US) [222ms]
    • Flutter version 3.46.0-1.0.pre-57 on channel stable at /opt/homebrew/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 37b9424fa8 (8 days ago), 2026-06-25 12:03:10 -0500
    • Engine revision a10d8ac38d
    • Dart version 3.12.2
    • DevTools version 2.57.0
