### ISSUE TITLE
AnalysisServer.analysis_getHover() returns not empty HoverInformation.containingClassDescription when null is expected

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#40056]
Starting from Dart SDK 2.8 (I tried with today's nightly build) `AnalysisServer.analysis_getHover()` returns not empty `HoverInformation.containingClassDescription` when asked for hover information for a class. Example:
![image](https://user-images.githubusercontent.com/4499789/72143971-bad0f480-33a8-11ea-8eac-181ded9d13bb.png)
`Containing class` line doesn't make sense here as the class doesn't contain itself. According to the documentation for [HoverInformation.containingClassDescription](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#type_HoverInformation) it should be omitted if the element is not a class member. Class itself is not a class member.

This is what Analysis Server returns:
![image](https://user-images.githubusercontent.com/4499789/72144191-2fa42e80-33a9-11ea-84ef-e97d3cd5a7ef.png)

**Comment by alexander-doroshko** [comment]
Seems to be fixed in today's Dart SDK nightly. Closing.

**Comment by bwilkerson** [comment]
This should now be fixed by https://dart-review.googlesource.com/c/sdk/+/155040. And there are regression tests to prevent it from coming back again.
