### ISSUE TITLE
Migrator should make typedef parameters nullable

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#40061]
Migrator should take:

```dart
typedef Fn = void Function(int x);
void main(void f(int x)) {
  Fn g = f;
  g(null);
}
```

and make `x` nullable:

```dart
typedef Fn = void Function(int? x);
void main(void f(int? x)) {
  Fn g = f;
  g(null);
}
```

This issue is spun from https://github.com/dart-lang/sdk/issues/40034, which is blocked by this.

**Comment by srawlins** [comment]
CC @stereotype441 @MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment]
Have a solution partway ready on this

**Comment by stereotype441** [comment]
Note that an example of this has cropped up in package:collection.

**Comment by MichaelRFairhurst** [comment]
likely postponing this in favor of lower hanging fruit. I sent an email out about possible solutions here, the original idea was union edges, but I think it could be better to make NodeBuilder lazy.

**Comment by MichaelRFairhurst** [comment]
refs #40353 

Also fixed
