### ISSUE TITLE
Code completion includes extension methods from other types

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40062]
Raised by @BendixMa at https://github.com/Dart-Code/Dart-Code/issues/2208. I can repro this on v2.8.0-dev, it seems like a server issue.

---

Hey,

when I declare a dart extension like so:

```dart
extension StringExtensions on String {
  bool get definitelyNotAnInt => false;

  void dontShowThisFunctionOnAnInt() {}
}
```

and use it subsequently in code like so:

```dart
main(List<String> args) {
  int integer = 0;
  integer. // and let vs-code show autocompletions here
}
```

then the suggestion list will include the extensions declared on the `String` class as shown below.

![dart-code-issue](https://user-images.githubusercontent.com/43601200/72103816-4fe0d880-332a-11ea-9318-fb39a58a94f6.png)

Especially when you have multiple extensions declared on multiple types than this will quickly make autocompletion almost useless as there are so many unrelated suggestions and you cannot find the functions/fields in the list that the class actually defines.

**Comment by DanTup** [comment]
@bwilkerson the unwanted methods come back in the completion results:

```js
{
	"event": "completion.results",
	"params": {
		"id": "2",
		"replacementOffset": 178,
		"replacementLength": 0,
		"results": [
			{
				"kind": "INVOCATION",
				"relevance": 1000,
				"completion": "dontShowThisFunctionOnAnInt",
				"selectionOffset": 27,
				"selectionLength": 0,
				"isDeprecated": false,
				"isPotential": false,
				// ...
				"returnType": "void",
				"parameterNames": [],
				"parameterTypes": [],
				"requiredParameterCount": 0,
				"hasNamedParameters": false
			},
			{
				"kind": "INVOCATION",
				"relevance": 1000,
				"completion": "definitelyNotAnInt",
				"selectionOffset": 18,
				"selectionLength": 0,
				"isDeprecated": false,
				"isPotential": false,
				// ...
				"returnType": "bool"
			},
			// ...
```

**Comment by bwilkerson** [comment]
@pq @jwren

**Comment by scheglov** [comment]
I broke it :-(
https://dart-review.googlesource.com/c/sdk/+/129334

https://dart-review.googlesource.com/c/sdk/+/131204 will add a new test, and restore the check.

**Comment by pq** [comment]
Thanks for the quick fix!
