### ISSUE TITLE
NNBD UX should explain implicit nullable types

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40064]
Not sure the best way to handle this.

Take the following code:

```dart
var x = List<int>(10);
```

This will get a nullable type because it's equivalent to

```dart
var x = <int>[null, null, null, ...];
```

This is fine to explain because there's nullabiliy node in the graph for this has a source location, and it gets an inserted ?.

However, there are countless ways to make this no longer the case. In thesecases the graph is built the same way, solved the same, but there's nowhere in the UI to show the explanation.

```dart
List<int> x = List(10); // becomes
List<int?> x = ... // with the only explanation "a nullable value is assigned."
```

This can be made worse to a potentially infinite depth:

```dart
T identity<T>(T t) => t;

List<int> x = identity(identity(identity(identity(identity( .... (List(10)) ....))));
```

In this case there are n inferred types:

```dart
List<int> x = idenity<List<int>>(identity<List<int>>( .... (List<int>(10) ...));
```

And the explanation for why a ? is inserted is lost in this chain of implicit nodes.

This occurs for other root causes, too:

```
T butNullable<T>() => null;
T identity<T>(T t) => t;

int x = identity(identity(identity( ... butNullable() ... ));
```

In this case, we get `int? x` with "a nullable value is assigned" which will point to `identity` and not `butNullable`.

It also occurs for

```
class C {
  final int? x; // null is passed into a field formal parameter
  C(this.x);
}
```

Perhaps this should be solved by making implicit types viewable in the interface, perhaps it can be solved by walking the graph.

Currently the explanation is lost.

**Comment by MichaelRFairhurst** [comment]
Another example of this came up.

```dart
var x = HashMap<T, int>();
x[t] = /* nullable value */ ...;
```

Expanding implicit types, this is

```dart
HashMap<T, int /* 1 */> x = HashMap<T, int /* 2 * />();
x[t] = ....;
```

_There are no null assignments to `int /* 2 */`._ There is, however, a nullable assignment to `int /* 1 */`. The `?` added on `int /* 2 */` is correctly migrated to be nullable because its assigned to `int /* 1 */`, where it says, "This is later required to accept null." That then navigates you to `int /* 1 */` assuming that that will direct you to the places it was assigned null. However, it's an implicit type, so it looks like the link directs you straight back to itself!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
