### ISSUE TITLE
Allow dart to set an environment variable in the parent process

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#40069]
I'm creating a package 'dshell' that is designed to make it easy to write cli scripts. Essentially the aim is that dshell should allow you to do everything that bash does, but using dart.

https://pub.dev/packages/dshell

As an example:
I'm currently trying to write the install script for dshell and need to reconfigure the current shell's 'PATH' so that after the install completes, the user can immediately run dshell commands without requiring a reboot or restart the terminal.

To do this, dshell needs to update the parent process's PATH environment variable.

Additionally, user of dshell are also likely to want to modify the parent process's environment variables for all sorts of reasons as bash users can currently do using 'export XXX=yyyy'.

Looking through the dart:io api I can't find any method that meets the above requirements.

I'm guessing the obvious path is to make Platform.environment writable?

**Comment by HotelCalifornia** [comment]
> as bash users can currently do using 'export XXX=yyyy'.

I'm pretty sure no shell (not even bash) allows you to modify the parent process's environment (nor should they!)

Plus, that's not even a shell limitation-- it's intentional on the part of the operating system. A program with this ability would, for instance, be able to overwrite the parent's `SHELL` variable and make it trivial to obtain root access

**Comment by bsutton** [comment]
It's been a long time, but I'm pretty sure you can do it from C.

**Comment by bsutton** [comment]
So looks like I'm wrong.

There is a way to do it on windows but lots like it's not completely
reliable.
https://www.perlmonks.org/?node_id=658253

As such I will close this issue.
