### ISSUE TITLE
Analyzer Feedback: Cannot open file

### ISSUE THREAD

**Issue by tbm98** [dart-lang/sdk#40063]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FileSystemException(path=/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStrea...
```

For additional log information, please append the contents of
file:///private/var/folders/p3/yks0s53s34s9pvmqcpy46pmc0000gn/T/report.txt.
file:
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FileSystemException(path=/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#56     _rootRunUnary (dart:async/zone.dart:1134:38)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#61     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#62     _StreamController._add (dart:async/stream_controller.dart:642:7)
#63     _StreamController.add (dart:async/stream_controller.dart:588:5)
#64     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#65     _rootRunUnary (dart:async/zone.dart:1138:13)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#70     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#71     _StreamController._add (dart:async/stream_controller.dart:642:7)
#72     _StreamController.add (dart:async/stream_controller.dart:588:5)
#73     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#74     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#75     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#76     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#77     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```
1578651099474 <= {"event":"analysis.navigation","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","regions":[{"offset":7,"length":31,"targets
1578651099475 <= {"event":"analysis.closingLabels","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","labels":[{"offset":301,"length":1372,"l
1578651099475 <= {"event":"analysis.outline","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","kind":"LIBRARY","outline":{"element":{"kind":
1578651099475 <= {"event":"analysis.overrides","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","overrides":[{"offset":260,"length":5,"super
1578651099479 <= {"event":"flutter.outline","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","outline":{"kind":"DART_ELEMENT","offset":0,"le
1578651099480 <= {"event":"analysis.implemented","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","classes":[],"members":[]}}
1578651099658 => {"id":"763","method":"edit.getAssists","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dart","offset":0,"length":0},"clientReque
1578651099661 <= {"id":"763","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/views/pages/login_page.dar
1578651163376 => {"id":"764","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":[]}}}
1578651163377 <= {"id":"764"}
1578651163377 => {"id":"765","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1578651163377}
1578651163377 => {"id":"766","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":[],"CLOSING_LABELS":[],"OUTLINE":[],"NAVIGATION":[],"HIGHLIGHTS":[],"IMPLEMENTED":[]}},"clientR
1578651163378 <= {"id":"765"}
1578651163378 <= {"id":"766"}
1578651256104 => {"id":"767","method":"analysis.getNavigation","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart","offset":196,"length":63},"clientRequest
1578651256140 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart","errors":[]}}
1578651256141 <= {"id":"767","result":{"files":["/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/register_page.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"length":0,"st
1578651256187 => {"id":"768","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart","offset":0,"length":0,"v
1578651256231 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart","errors":[]}}
1578651256233 <= {"id":"768","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1578651256245 => {"id":"769","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart","offset":0,"length":0,"v
1578651256339 <= {"id":"769","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"change":{"message":"","edits":[{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/main.dart
1578651256360 => {"id":"770","method":"analysis.updateContent","params":{"files":{"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/main.dart":{"type":"add","content":"import 'package:firebase_crashl
1578651256360 => {"id":"771","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/register_page.dart","offset":0,"length":0
1578651256361 <= {"id":"770","result":{}}
1578651256362 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1067,"uri":"package:xechung_mobile/main.dart","items":[{"label":"MainPage","declaringLibraryUri":"packag
1578651256418 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/register_page.dart","errors":[]}}
1578651256418 <= {"id":"771","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1578651256418 => {"id":"772","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/register_page.dart","offset":0,"length":0
1578651256441 <= {"id":"772","error":{"code":"SERVER_ERROR","message":"FileSystemException(path=/Users/tbm/dev/mobile_projects/xechung_mobile/lib/src/xechung/login_page.dart; message=Cannot open file)
```

**Comment by srawlins** [comment]
This has been reported as recently as dev builds of 2.9.0.

**Comment by sanekyy** [comment]
I have encountered this problem for at least the last six months

**Comment by srawlins** [comment]
This was reported recently using Dart 2.10.4 at https://github.com/dart-lang/sdk/issues/44706.

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this crash on a recent version of Dart.
