### ISSUE TITLE
Analyzer doesn't promote.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40088]
Concrete example:
```dart
  void addError(Object error, [StackTrace? stackTrace]) {
    if (!_mayAddEvent) throw _addEventError();
    AsyncError? replacement = Zone.current.errorCallback(error, stackTrace);
    if (replacement != null) {
      error = replacement.error;
      stackTrace = replacement.stackTrace;  // AsyncError.stackTrace type is StackTrace.
    } else {
      stackTrace ??= AsyncError.defaultStackTrace(error);
    }
    if (stackTrace == null) throw "unreachable"; // TODO(40088)
    _sendError(error, stackTrace);
  }
```

Here the analyzer warns that `stackTrace` passed to `_sendError` is nullable, even though all paths reach there assigns a non-nullable value to the variable.

Adding the `if ... throw ...` does promote.

**Comment by scheglov** [comment]
The set of `tested` types is empty for `stackTrace`, and according to the [flow analysis spec](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md#promotion), it is not promotable via assignment. @leafpetersen 

> - We say that a variable `x` is promotable via assignment of an expression of
>     type `T` given variable model `VM` if
>     - `VM = VariableModel(declared, promoted, tested, assigned, unassigned, captured)`
>     - and `captured` is false
>     - and `S` is the current type of `x` in `VM`
>     - and `T <: S` and not `S <: T`
>     - and `T` is a type of interest for `x` in `tested`

**Comment by lrhn** [comment]
Being non-null is always of interest:

> * We say that at type `T` is a type of interest for a variable `x` in a set of tested types `tested` if `tested` contains a type `S` such that `T` is `S`, or `T` is **NonNull(`S`)**.

I assume that the declared type of the variable is in the set of tested types/types of interest.

**Comment by scheglov** [comment]
It does not look to me that `tested` includes `declaredType`. The only place where I see `tested` updated is the `instance check` rule. There are places in the spec where `tested` is explicitly given the empty list `[]` value.

> ### Models
> 
> A *variable model*, denoted `VariableModel(declaredType, promotedTypes,
> tested, assigned, unassigned, writeCaptured)`, represents what is statically
> known to the flow analysis about the state of a variable at a given point in the
> source code.
> 
> - `declaredType` is the type assigned to the variable at its declaration site
>   (either explicitly or by type inference).
> 
> - `promotedTypes` is an ordered set of types that the variable has been promoted
>   to, with the final entry in the ordered set being the current promoted type of
>   the variable.  Note that each entry in the ordered set must be a subtype of
>   all previous entries, and of the declared type.
> 
> - `tested` is a set of types which are considered "of interest" for the purposes
>   of promotion, generally because the variable in question has been tested
>   against the type on some path in some way.
>

**Comment by leafpetersen** [comment]
I agree that this seems like something we would like to support.  @scheglov do you see any difficulties in supporting it?  I can update the specification to indicate that the declared type is always included in the set of types of interest - is that sufficient?

**Comment by scheglov** [comment]
@leafpetersen Yes, I think adding the declared type to the set of types of interest will work.

**Comment by scheglov** [comment]
Done.
