### ISSUE TITLE
Failed to generate executables by dart2native 

### ISSUE THREAD

**Issue by arctany** [dart-lang/sdk#40083]
Hi,

Dart SDK 2.7.0 stable version
MacOSX and Linux 

Run 
```
dart2native 
/home/admin/tools/dart-sdk/bin/dart2native bin/main.dart -o test
```
then got 
```
Unexpected object (Class with illegal cid, full-aot): 0x7fcda0b71ae1 Library:'dart:collection' Class: _CompactLinkedHashSet@3220832
Failed to generate native files:
Generating AOT snapshot failed!
```

I tested in MacOSX，the error remained the same.

My dependency tree:
```
Dart SDK 2.7.0
df_cli 0.0.1
|-- args 1.5.2
|-- logger 0.8.2
'-- sprintf 4.0.2
```
Can someone take a look on this?

**Comment by arctany** [comment]
A simple test to reproduce:

```
import 'package:logger/logger.dart';

main(){
  var logger = Logger();
  logger.v("Verbose log");
}
```
Run dart2native -o.
```
Unexpected object (Class with illegal cid, full-aot): 0x7fcda0b71ae1 Library:'dart:collection' Class: _CompactLinkedHashSet@3220832
Failed to generate native files:
Generating AOT snapshot failed!
```
It's confusing to get compile time error like this.

Another question is about the "-Denv= " defined in dart2native . How can I get the env vars in my program? 
I tried 
```
String.fromEnvironment("env") 
```
still return null.

**Comment by mit-mit** [comment]
cc @mkustermann  @cskau-g

**Comment by mkustermann** [comment]
@arctany Thank you for the bug report!

> Another question is about the "-Denv= " defined in dart2native.
> How can I get the env vars in my program?

Those have to be supplied at compile-time and used as compile-time constants:
```dart
main() => print(const String.fromEnvironment('foo'));
```

```
% dart2native -Dfoo=bar test.dart
...
% ./test.exe
bar
```

**Comment by mkustermann** [comment]
> It's confusing to get compile time error like this. I think dart2native should have a consistent 
> behavior when comes arbitrary code.

This is a bug in our AOT compiler. We'll take a look.

@sstrickl Could you take a look at this? It seems to only happen in Product mode not in Release mode.

```
% cat test.dart
import 'package:logger/logger.dart';

main() {
  var logger = Logger();
  logger.v("Verbose log");
}

%  DART_CONFIGURATION=ProductX64 pkg/vm/tool/precompiler2 test.dart test.aot
Unexpected object (Class with illegal cid, full-aot): 0x7fe048eb86b1 Library:'dart:collection' Class: _CompactLinkedHashSet@3220832
```
