### ISSUE TITLE
No code completion after yield keyword

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40099]
Originally raised at https://github.com/Dart-Code/Dart-Code/issues/2210 by @Tokenyet (looks like https://github.com/dart-lang/sdk/issues/24346, but that was marked fixed a long time ago).

---

![demo](https://user-images.githubusercontent.com/6420527/72199593-094dc400-3479-11ea-9849-24754fa7256b.gif)

The class that I wanted to use is in the same file (.dart), but the completion can't find any, even If It's own class methods.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

If there is something info not provided, I'll provide It asap.

**Comment by DanTup** [comment]
Small copy/pastable repro:

```dart
class Foo {
  bool myField;

  Stream<bool> foo() async* {
    // Completion after "myField" should include "myField"
    yield myFiel;
  }
}
```

**Comment by bwilkerson** [comment]
@jwren @pq

**Comment by pq** [comment]
Thanks!  I think this one is a dup of #39124.

In any event, looking now. 👍

**Comment by DanTup** [comment]
Sorry missed that one! Thanks!

**Comment by pq** [comment]
NP!

Always best to just report it.  Better too many reports than too few!
