### ISSUE TITLE
Converting from generic StatelessWidget to StatefulWidget omits type arguments

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40095]
Raised by @shyndman at https://github.com/Dart-Code/Dart-Code/issues/2213. I can repro this, and it seems like an issue in the quick-fix.

--

When converting a generic `StatelessWidget` subclass to a `StatefulWidget`, necessary type arguments are omitted from the generated `createState()`.

Example:
```dart
class Foo<T> extends StatelessWidget {
  Widget build(BuildContext) => ...
}

// when run through "Convert to StatefulWidget" becomes

class Foo<T> extends StatefulWidget {
  @override
  _FooState createState() => _FooState(); //! Missing type annotations
}

class _FooState<T> extends State<Foo<T>> {
  @override
  Widget build(BuildContext context) => ...;
}
```

As a result, the runtime type of the `State` subclass is `_FooState<dynamic>`, and its widget, `Foo<dynamic>`. When the state accesses fields whose types involve the type argument `T`, runtime type checks can fail.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/131420

**Comment by shyndman** [comment]
👍!

**Comment by ciceropablo** [comment]
@shyndman, @DanTup, @bwilkerson, it is possible to do the opposite?
