### ISSUE TITLE
No completion for aliased imports at class level

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40098]
Originally raised at https://github.com/Dart-Code/Dart-Code/issues/2211 by @Tokenyet.This looks a bit like https://github.com/dart-lang/sdk/issues/7898, but that was marked fixed a long time ago.

---

![ezgif-3-c37857e9f620](https://user-images.githubusercontent.com/6420527/72200095-e8d53800-347f-11ea-8def-632f8412d3bb.gif)

Use alias to prevent nameing conflict, but not working in this specified scenario.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

If there is something info not provided, I'll provide It asap.

**Comment by DanTup** [comment]
A simpler repro:

```dart
import 'dart:async' as alias;

class Foo {
  // no completion here
  // alias.

  foo() {
    // completion here
    // alias.
  }
}
```

**Comment by bwilkerson** [comment]
@jwren @pq

**Comment by bwilkerson** [comment]
The prefix is now being suggested in both places, so I believe that this has been fixed.
