### ISSUE TITLE
Rerunning tests does not reflect new code

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40108]
Dart VM version: 2.8.0-dev.0.0.flutter-32ce9c7872 (Sat Jan 11 20:39:02 2020 +0000) on "macos_x64"

When running tests, I have to run a flutter clean or at least an `rm -rf build` in order for new changes in my code to be reflected in a new test.

**Comment by mit-mit** [comment]
This sounds like a Flutter issue?

**Comment by ThinkDigitalSoftware** [comment]
Why so? Because it's in a Flutter project?

**Comment by mit-mit** [comment]
No, because you are using a flutter tool chain (flutter run/test/clean are flutter commands).

Or does this repro when using just a Dart SDK and the Dart tools (like pub run test)?

**Comment by ThinkDigitalSoftware** [comment]
Hmm. I can't test that on this particular project. It is a flutter project though. Can this be moved automatically?

**Comment by mit-mit** [comment]
Unfortunately not. Can you kindly open an issue here? https://github.com/flutter/flutter

**Comment by ThinkDigitalSoftware** [comment]
Sure can, thanks
