### ISSUE TITLE
Unforked Null Safe SDK

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#40105]
Tracks work associated with achieving feature and performance parity running unmigrated code against the Null Safe SDK.

Meta tracking issue for VM for this work is https://github.com/dart-lang/sdk/issues/40179

**Comment by vsmenon** [comment]
@franklinyow - is this still the primary issue?  We're still missing:

- dart2js test failure on unfork cl
- dart:_http breakage
- internal run
- flutter run
- dart2js performance
- dart2js code size
- aot code size (need flutter gallery size numbers)

**Comment by franklinyow** [comment]
> @franklinyow - is this still the primary issue? We're still missing:
> 
> * dart2js test failure on unfork cl
> * dart:_http breakage
> * internal run
> * flutter run
> * dart2js performance
> * dart2js code size
> * aot code size (need flutter gallery size numbers)

This Epic will close as soon as the ddc work landed.
The unforking work is in #40106

**Comment by vsmenon** [comment]
That does not seem right.  40106 is post-unfork completeness work.  We still need the above to actually unfork (i.e., land @a-siva 's cl): https://dart-review.googlesource.com/c/sdk/+/138902
