### ISSUE TITLE
migrate relevance checking out of completion contributor tests

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40104]
As discussed, validating completion suggestion relevance in isolation is not our preferred path forward and should be moved out of `assertSuggest` in the contributor test base class.

Current plan:

- [x] create a new `relevance` directory to hold relevance tests
- [ ] migrate valuable existing relevance checking logic from contributor tests to the new style
- [ ] remove relevance validation entirely from  `assertSuggest` in the contributor test base class

**Comment by bwilkerson** [comment]
I believe that this work was completed by https://dart-review.googlesource.com/c/sdk/+/157420.
