### ISSUE TITLE
Inconsistencies between DDK and DartVM stack traces

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#40103]
Flutter relies on parsing stack traces to filter and reformat stack traces to be more readable. Differences between stack traces in DDK and the DartVM make it slower and more fragile to write that logic.

It would be nice to add extra logic to DDK to normalize these differences so that stack traces so package:flutter stack trace filtering logic can be written once and work on both.

"The problem on web is we don't get class names in the stack traces - we only get method names. We also get method names in brackets if they're private. We also don't get frame line numbers, but that's not a huge deal."

Related flutter code review:
https://github.com/flutter/flutter/pull/48413#issuecomment-573831599

**Comment by jacob314** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/40103

**Comment by mraleph** [comment]
@jacob314 duplicate link is circular

**Comment by jacob314** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/40117
