### ISSUE TITLE
Add Future.never

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#40116]
Sometimes in tests I see a pattern of creating a Completer to return a future, but then to not hold on to the reference to the completer.

The pattern stands out as a bug until you realize that it is intentional. I think it's common enough that it might be worth giving it a name.

Potentially this can be something like

```dart
class Future {
  static Future<Never> never = Completer<Never>().future;
  ...
}
```

I'm not sure if `Future<Never>` makes the most sense as the type.

Any thoughts on this @lrhn ?

**Comment by lrhn** [comment]
I don't see any *good* uses of a future which never completes. It's almost invariably a mistake, or it's just being used in test to smoke out bugs, which is where you see it. 
I'm wary about introducing code for that in the general platform API. I'm not sure it carries its own weight there.

Maybe the test package could have a non-completing future available.

**Comment by natebosch** [comment]
> Maybe the test package could have a non-completing future available.

With the reduced discoverability I think we would skip it. If we add a language feature to add static members to another class I'd probably do it then.

**Comment by fabis94** [comment]
There most definitely are good uses for such a future and they're inside tests. If this isn't possible, what alternative is there for creating never finishing Futures inside tests? A super long Future.delayed() fails in Flutter tests due to "pending timers"

**Comment by st-pasha** [comment]
> I don't see any good uses of a future which never completes.

One valid use-case is when you have code like
```dart
final result = await Future.any([
  for (final component in components)
    component.process(input)
]);
```
where components compete on who can finish processing the `input` first; however, some components may not be able to process the input at all, so in that case they would want to return a never-completing Future.

**Comment by lrhn** [comment]
It's easy to create a never-completing future, just use `Completer<Foo>().future`.

I don't think *deliberately* choosing to not complete happens often enough that it deserves dedicated API in the platform libraries.
If anything, I want people to consider other options before introducing a non-completing future.
