### ISSUE TITLE
declaration of variable of type Never crashes the compiler

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#40114]
in dartpad (SDK 2.7.0) 
```
main() {
  Never x;
  print(x);
}
```
causes
```
Error compiling to JavaScript:
main.dart:1:1:
Internal Error: The compiler crashed when compiling this element.
main() {
^
The compiler is broken.
```

**Comment by mit-mit** [comment]
Doesn't crash in the VM, version 2.7.0

**Comment by sigmundch** [comment]
@johnniwinther - we crash in dart2js because we are getting an unexpected NeverType when the non-nullable experiment is off. Shouldn't the parser treat this as a regular type whose name happens to be "Never" if non-nullable types are disabled?

**Comment by johnniwinther** [comment]
You shouldn't get the `NeverType`. The verdict is still out on whether we should treat `Never` as a regular interface type or as `Null` in legacy mode. See #39917

**Comment by stefantsov** [comment]
I'm not sure it's a CFE bug.  Compiling the program in the original message with the CFE doesn't make it crash, both with and without Null Safety feature enabled.

<details>
<summary>With Null Safety feature enabled (Click to expand)</summary>
Note the absence of a space after `Never` in the textual output.  It's a minor bug and will probably be fixed soon.

```
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
library;
import self as self;
import "dart:core" as core;

static method main() → dynamic {
  Neverx;
  core::print(x);
}
```
</details>

<details>
<summary>With Null Safety feature disabled (Click to expand)</summary>

```
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/to
ol/_fasta/compile.dart --dump-ir -o /dev/null /tmp/asdf.dart
library;
import self as self;
import "dart:core" as core;

static method main() → dynamic {
  Never* x;
  core::print(x);
}
```
</details>

**Comment by johnniwinther** [comment]
Dart2js now supports Never.
