### ISSUE TITLE
Definite assignment doesn't track variables definitely assigned in switches.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40110]
In the code below, `x` is definitely assigned in all branches of the switch statement, but the analyzer reports an error indicating that it is used before being assigned.   Since the analyzer is tracking whether all of the cases are covered anyway, it seems like using this in definite assignment should be feasible.  cc @stereotype441 @johnniwinther @scheglov 

```dart
enum ME {
  Foo,
  Bar,
  Baz,
}

int test(ME me) {
  List<int> x;
  switch (me) {
    case ME.Foo:
    x = [];
    break;
    case ME.Bar:
    case ME.Baz:
    x = [];
    break;
  }
  return x.length;
}
```

**Comment by stereotype441** [comment]
Agreed that this should be feasible, though possibly not trivial--I'm not sure how readily available this information is to the front end at the time definite analysis is being performed.

@johnniwinther one way we could implement this would be to rename `FlowAnalysis.switchStatement`'s `hasDefault` to something like `isExhastive`, and the contract would be that the caller should pass `true` if *either* the switch statement has a default clause *or* if the type being switched on is an enum and all the enumerated values are covered by cases.  WDYT?

**Comment by leafpetersen** [comment]
Exhaustiveness also affects inference.  Here's a case from @bkonyi where the analyzer currently gives an error because it infers the return type of the closure to be `int?` even though all paths are actually handled.

```dart
enum ME {
  Foo,
  Bar,
  Baz,
}

int test(ME me) {
  return () {
    switch (me) {
    case ME.Foo:
    return 0;
    case ME.Bar:
    case ME.Baz:
    return 1;
}}();
}
```

**Comment by johnniwinther** [comment]
@stereotype441: using `isExhaustive` sounds like a good idea.

**Comment by stereotype441** [comment]
@leafpetersen do we need to cover the case where the enum values are constant expressions rather than direct references to the enum?  E.g.:
```
enum MyEnum { A, B, C };
const otherB = MyEnum.B;
const myConst = false;
int test(MyEnum e) {
  switch (e) {
    case MyEnum.A:
      return 0; 
    case otherB:
      return 1;
    case myConst ? MyEnum.B : MyEnum.C:
      return 2;
  }
  // No error because switch statement is exhaustive
}
```

**Comment by leafpetersen** [comment]
I'm guessing that would be substantially more complicated to support?

**Comment by scheglov** [comment]
Yes, it would be much more complicated.
Analyzer computes constant values only after resolution is finished.

**Comment by leafpetersen** [comment]
OK.  I don't see a lot of marginal value here.  Let's say that the notion of exhaustiveness that is only used for reachability and definite assignment only accounts for direct uses of enum constants.
