### ISSUE TITLE
Make "is" smarter with additional automatic casts for alternative execution paths

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#40118]
`is` can automatically cast an object to a scope such as in:

```dart
if (emp is Person) {
  emp.firstName = 'Bob';
}
```

But `is!` can't, it would be useful to be able to do something like this:

```dart
if (o is! String) {
    return;
}
return o.isEmpty; // only option is to be a String
```

This could also be infered for an `else`.

**Comment by lrhn** [comment]
This improvement is planned as part of the null-safety update. It's particularly useful along with `if (x == null) return;`-like tests which can promote `x` to non-nullable in the following code.

**Comment by feinstein** [comment]
Excellent, so should I close this or leave it open for tracking?

**Comment by mit-mit** [comment]
Closing, as mentioned this is already underway.
