### ISSUE TITLE
Analyzer missing return hint doesn't use reachability

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40119]
The code below triggers the analyzer's "missing return" hint with non-nullability on.  The analyzer must know that all paths hit a return statement, since the return type is non-nullable but there's no error, so the hint should be able to know this as well.

cc @stereotype441 @scheglov 

```dart
enum ME {
  Foo,
  Bar,
  Baz,
}

int test(ME me) {
  switch (me) {
    case ME.Foo:
    return 0;
    case ME.Bar:
    case ME.Baz:
    return 1;
  }
}
```

**Comment by scheglov** [comment]
This was fixed as https://github.com/dart-lang/sdk/issues/40110, the code is now diagnostics free.
