### ISSUE TITLE
NNBD Dart throws unexpected compile error for the dead code with Never variable

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40125]
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

NNBD Spec reads:
> It is not an error to call or tear-off a method, setter, or getter, or to read or write a field, on a receiver of static type Never. Implementations that provide feedback about dead or unreachable code are encouraged to indicate that any arguments to the invocation are unreachable.
> 
> It is not an error to apply an expression of type Never in the function position of a function call. Implementations that provide feedback about dead or unreachable code are encouraged to indicate that any arguments to the call are unreachable.

The following code sample check this assertion:
``` dart
void test(var x) {
  if (x is Never) {
    x.toString();
    x.runtimeType;
    x.s = 1;
    x?.toString();
    x?.runtimeType;
    x?.s = 1;
    x?..toString();
    x?..runtimeType;
    x?..s = 1;
    x();
  }
}

main() {
  test(null);
}
```
According to the Spec, this example should pass, however lines 5, 8, 11 and 12 throw errors.

Sample output is:

> $> dart --enable-experiment=non-nullable test.dart
> test.dart:5:7: Error: The setter 's' isn't defined for the class 'Never'.
> Try correcting the name to the name of an existing setter, or defining a setter or field named 's'.
>     x.s = 1;          // compile-error
>       ^
> test.dart:8:8: Error: The setter 's' isn't defined for the class 'Never'.
> Try correcting the name to the name of an existing setter, or defining a setter or field named 's'.
>     x?.s = 1;         // compile-error
>        ^
> test.dart:11:9: Error: The setter 's' isn't defined for the class 'Never'.
> Try correcting the name to the name of an existing setter, or defining a setter or field named 's'.
>     x?..s = 1;        // compile-error
>         ^
> test.dart:12:6: Error: The method 'call' isn't defined for the class 'Never'.
> Try correcting the name to the name of an existing method, or defining a method named 'call'.
>     x();              // compile-error
>      ^

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/134326
