### ISSUE TITLE
Analyzer `implicit-dynamic: false` has changed

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#40129]
I noticed different results between the dartanalyzer I have locally (prerelease) and the one on travis (2.8.0-dev.0.0). I get more results with the older version

>   error • Missing variable type for '_$dynamicOther'. • lib/generics.g.dart:1100:11 • implicit_dynamic_variable
> ...
>   error • Missing type argument for list literal. • test/imported_values_serializer_test.dart:26:7 • implicit_dynamic_list_literal

Looking at the analyzer changelogs it seems these error codes were removed. https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/CHANGELOG.md#0393

> Removed error codes: ASSIGNMENT_CAST, StrongModeCode.DOWN_CAST_COMPOSITE, DOWN_CAST_IMPLICIT, DOWN_CAST_IMPLICIT_ASSIGN, DYNAMIC_CAST, DYNAMIC_INVOKE, IMPLICIT_DYNAMIC_FIELD, IMPLICIT_DYNAMIC_FUNCTION, IMPLICIT_DYNAMIC_INVOKE, IMPLICIT_DYNAMIC_LIST_LITERAL, IMPLICIT_DYNAMIC_MAP_LITERAL, IMPLICIT_DYNAMIC_METHOD, IMPLICIT_DYNAMIC_PARAMETER, IMPLICIT_DYNAMIC_RETURN, IMPLICIT_DYNAMIC_TYPE, IMPLICIT_DYNAMIC_VARIABLE, INFERRED_TYPE, INFERRED_TYPE_ALLOCATION, INFERRED_TYPE_CLOSURE, INFERRED_TYPE_LITERAL, and NON_GROUND_TYPE_CHECK_INFO. These were used internally by the analyzer for testing and were not exposed to users.

The assertion that these were not exposed to users seems to be incorrect--they were exposed if you use `implicit-dynamic: false`.

Please advise--is `implicit-dynamic: false` supported? If so we probably need those codes back :D

Thanks :)

**Comment by bwilkerson** [comment]
@stereotype441 @scheglov

**Comment by scheglov** [comment]
I removed these error codes because the language specification does not require them, and my understanding was that they were necessary only for DDC, which does not use analyzer anymore.

**Comment by knaeckeKami** [comment]
implicit-dynamic is mentioned here:
https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks

and is incredibly useful IMO, as is prevents errors like this:

https://dartpad.dev/b42203ba5d7d8e5ff55f99bd003a81bf

(The user forgot to write the type parameter for in `extends State<GenericShizzle> ` (instead of extends State<GenericShizzle<T>>`, so he gets confusing errors at runtime).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/131723 will restore reporting `IMPLICIT_DYNAMIC_*`.

**Comment by davidmorgan** [comment]
Thanks :)
