### ISSUE TITLE
Browser tests timing out with 2.8.0-dev.1.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40133]
See
https://travis-ci.org/dart-lang/fake_async/jobs/636976975
https://travis-ci.org/dart-lang/clock/jobs/636977006
https://travis-ci.org/dart-lang/sample-pop_pop_win/jobs/637003551

CC @grouma @athomas 

Not sure the root cause here...

**Comment by jakemac53** [comment]
I think this was likely fixed by https://github.com/dart-lang/sdk/commit/12984eee89bbd668574124171ea7a66f03d77113 but that didn't make it into that dev release.

**Comment by jakemac53** [comment]
cc @fishythefish

**Comment by kevmoo** [comment]
An assert would cause a hang in production?

**Comment by grouma** [comment]
My understanding is that the assert would cause a failure in the root of the browser bootstrap logic which could cause a hang.

**Comment by jakemac53** [comment]
The assert is actually inside of dart2js library code. If asserts are enabled then this would cause the test to fail to load because it happens during the test communication setup between the runner and browser.

**Comment by kevmoo** [comment]
@athomas – this is worth doing a +1 dev roll!

**Comment by athomas** [comment]
I will start 2.8.0-dev.2.0 build based on https://github.com/dart-lang/sdk/commit/d1e11f088108b5ec90fcc2faef7ed1437b018f47 (includes the fix and is the latest that passed the internal roll).

**Comment by kevmoo** [comment]
Calling this fixed!
