### ISSUE TITLE
Migrate "dart:typed_data" tests to NNBD

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40139]
Migrate the tests in "tests/lib_2/typed_data" to NNBD at "tests/lib/typed_data".

**Comment by eernstg** [comment]
Cf. https://dart-review.googlesource.com/c/sdk/+/132341.

**Comment by eernstg** [comment]
Landed as e7d4c48a8014c9d785c8a3e2f7a90e2058a12626.
