### ISSUE TITLE
Null Safety migration of Flutter framework upstream dependencies

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40145]
This issue tracks the work to migrate the packages that the flutter framework itself depends on.

**Comment by leafpetersen** [comment]
@srawlins Do you have the list of packages involved?

cc @Hixie @a14n

**Comment by jonahwilliams** [comment]
The direct dependencies are fairly modest:

```
collection: 1.14.11
meta: 1.1.8
typed_data: 1.1.6
vector_math: 2.0.8
```

The dev_dependencies are slightly larger due to package:test_api, flutter_test, and others (see https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml)

**Comment by srawlins** [comment]
That should  be the correct list.

**Comment by a14n** [comment]
Starting from today there's also the `characters` package that has been added via https://github.com/flutter/flutter/commit/77859c682edbcc6a8af772dcf79d46b3786f10f9

**Comment by franklinyow** [comment]
@leafpetersen Is this done?

**Comment by jonahwilliams** [comment]
All of the framework direct dependencies are migrated https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L10

**Comment by franklinyow** [comment]
closing
