### ISSUE TITLE
Flutter core packages migration

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40147]
This tracks the migration of the core set of packages required to build a small Flutter app.

@srawlins @vsmenon Do you have the list of packages?

cc @Hixie @a14n

**Comment by a14n** [comment]
See the [hello_world pubspec.yaml](https://github.com/flutter/flutter/blob/master/examples/hello_world/pubspec.yaml). It's the same packages as https://github.com/dart-lang/sdk/issues/40145#issuecomment-574514830

**Comment by a14n** [comment]
If we want to migrate a larger example app we can look into [flutter_gallery pubspec.yaml](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/pubspec.yaml).

**Comment by leafpetersen** [comment]
I think flutter_gallery would be a good goal.

**Comment by mit-mit** [comment]
@franklinyow @leafpetersen I think we can mark this done?

**Comment by franklinyow** [comment]
Agree,closing
