### ISSUE TITLE
[ffi] DynamicLibrary.close() is missing

### ISSUE THREAD

**Issue by syoyo** [dart-lang/sdk#40159]
This tracker is for issues related to:

* Dart VM : ffi
* Dart SDK Version (`dart --version`) : `master`

Is there any (technical) reason not implementing `DynamicLibrary.close()`?

https://github.com/dart-lang/sdk/blob/ca565d946f502aaf9c6a4a42327473234b3a4cff/sdk/lib/ffi/dynamic_library.dart#L10

Extension supports Unload(dlclose) method.

https://github.com/dart-lang/sdk/blob/ca565d946f502aaf9c6a4a42327473234b3a4cff/runtime/bin/extensions_linux.cc#L25

I want to do .so hot reloading on Flutter(Dart), following this c-interop document: https://dart.dev/guides/libraries/c-interop

Without `DynamicLibrary.close` feature, it has no way to unload currently loaded .so file in Dart layer.

**Comment by dcharkes** [comment]
Good catch, we should add this.

**Comment by syoyo** [comment]
Thanks!

**Comment by dcharkes** [comment]
We should be able to _lookup_ `dlclose` (and `FreeLibrary` on Windows) and invoke it.

I presume we would be able to find the symbol in `DynamicLibrary.process()` on most architectures. 
 We'd have to figure out where on Windows `FreeLibrary` can be found.

Then we can add it as extension method to `DynamicLibrary` in `package:ffi` instead of adding it as a method to `dart:ffi`.

The implementation would be similar to `allocate` in https://github.com/dart-lang/ffi/blob/master/lib/src/allocation.dart

Feel free to make a PR to `package:ffi`.

cc @mkustermann

**Comment by syoyo** [comment]
> We should be able to lookup dlclose (and FreeLibrary on Windows) and invoke it.
>
> I presume we would be able to find the symbol in DynamicLibrary.process() on most architectures.
> We'd have to figure out where on Windows FreeLibrary can be found.

That is a good idea!

At least, I've confirmed invoking `dlclose` in such manner works well on Android through Flutter app, like this:
 
```
// Assume Platform.isAndroid

DynamicLibrary nativeAddLib =
        DynamicLibrary.open("/data/data/com.example.flutter_native_add/files/libnative_add.so");

int Function(int x, int y) addFun =
  nativeAddLib
    .lookup<NativeFunction<Int32 Function(Int32, Int32)>>("native_add")
    .asFunction();

// TODO: Windows support

// for `dlclose` symbol lookup
final DynamicLibrary dlLib = DynamicLibrary.process();

final int Function(Pointer<Void>) dlcloseFun =
  dlLib
    .lookup<NativeFunction<Int32 Function(Pointer<Void>)>>("dlclose")
    .asFunction();

int ret = dlcloseFun(nativeAddLib.handle);
print(ret); // 0 for success

// => calling `addFun()` will seg fault because .so has been unloaded

// reload .so
DynamicLibrary nativeAddLib =
        DynamicLibrary.open("/data/data/com.example.flutter_native_add/files/libnative_add.so");

// look-up symbol again.
int Function(int x, int y) addFun =
  nativeAddLib
    .lookup<NativeFunction<Int32 Function(Int32, Int32)>>("native_add")
    .asFunction();

print(addFun(1, 2)); // should work
```

As you can easily imagine, calling native method after

**Comment by mkustermann** [comment]
> We should be able to lookup dlclose (and FreeLibrary on Windows) and invoke it.

That would make the API unsymmetric: The VM decides which `dlopen()` to use but the user decides which `dlclose()` to use. I'm actually surprised we even expose the underlying `DynamicLibrary.handle` to the user - maybe we should remove it?

We should reserve the possibility for the VM embedder to intercept the dlopen/dlsym/dladdr/dlclose operations and thereby allow a custom implementation.

So I think it's not advisable for users to lookup `dlclose` and call it, we should provide it in our API

**Comment by dcharkes** [comment]
Those are good reasons, I'll add it to the VM then.

> I'm actually surprised we even expose the underlying `DynamicLibrary.handle` to the user -  maybe we should remove it?

We added it to enable users to lookup things.

> We should expose `DynamicLibrary.handle` to enable users passing library handles to C functions.
> 
> _Originally posted by @dcharkes in https://github.com/dart-lang/sdk/issues/35881#issuecomment-461500399_

Though, I guess users could do `dlopen` themselves on the same String, if they would want to lookup something in a same dynamic library.

**Comment by jci-cfoxr** [comment]
Just curious if there is still motivation to address this issue as there hasn't  been any activity.   We have a use case where this might be useful.  Thanks.

**Comment by dcharkes** [comment]
> Just curious if there is still motivation to address this issue as there hasn't been any activity. We have a use case where this would be useful. Thanks.

Yes, we should address this. We just haven't gotten around to it.

Feel free to submit a PR if you feel comfortable to do so.

**Comment by simolus3** [comment]
I've started working on this (https://dart-review.googlesource.com/c/sdk/+/307680)

**Comment by lrhn** [comment]
The "open" and "close" terminology about a loaded library feels a little off to me. I'd expect something like "load" and "unload", or "acquire" and "release" if treating like a resource.

The method name is fine, "close" is generally used to release resources in Dart, but the documentary saying that it "closes" a library doesn't tell me what it does. (But I also have near zero practical experience actually losing and unloading libraries, so if that's the correct terminology, it's just me not knowing that.)

The `ArgumentError`s should be `StateError`s.

**Comment by dcharkes** [comment]
> should be `StateError`s.

@lrhn any reason why on this API we chose for `StateError`s while on https://dart-review.googlesource.com/c/sdk/+/305900 we chose subsequent closes to be no-ops? Should we be consistent across `close()` methods in `dart:ffi`?

**Comment by lrhn** [comment]
I usually see no reason to throw on redundant closes. It's just not worth it.
So it's fine to not do that.

Was mainly pointing out that `ArgumentError` was not the correct choice, and if you do want to throw `StateError` would be better.
