### ISSUE TITLE
Migrate internal dart2js patch files and runtime libraries

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40153]
This issue tracks all sdk migration work for the dart2js platform.

This includes:
  * [x] updating all dart2js patch files (likely by coping changes from the ddc patches).
  * [x] completing the nnbd version of dart:html and related libraries
  * [x] completing the nnbd version of dart:js
  * [x] migrating all internal dart2js libraries (like _foreign_helper, _js_helper, _rti, etc)

**Comment by rakudrama** [comment]
We can start on the dart2js_server_platform since it leaves out dart:html

**Comment by franklinyow** [comment]
Are this done?  Can it be closed?

**Comment by sigmundch** [comment]
yes.
