### ISSUE TITLE
Add throwing setters for late final field override

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40161]
Late lowering should add a throwing setter for late final fields with initializers that override late fields that introduce a setter:

```Dart
class A {
  late final int field;
}
class B extends A {
  late final int field = 0; // A throwing setter is needed for B.field.
}
```

**Comment by johnniwinther** [comment]
See tests/language/nnbd/syntax/late_modifier_final_field_test.dart

**Comment by lrhn** [comment]
According to https://github.com/dart-lang/language/pull/720 the throwing setter should no longer be introduced. That means that the *test* is now wrong.

**Comment by johnniwinther** [comment]
The test is ok, the late lowering is wrong: When checking if the field is initialized we are checking the overriding and not the overridden field.

**Comment by johnniwinther** [comment]
This underlying issue for the test failure was fixed in https://dart-review.googlesource.com/c/sdk/+/131829
