### ISSUE TITLE
NNBD support in Dart API

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40176]
The Dart API needs to be updated to support nullability. For example, it should be possible to choose what kind of nullability you want when calling Dart_GetType.

**Comment by a-siva** [comment]
Here is some notes from the discussion that @rmacnak-google  and @a-siva had

Dart_NewListOf - Need to figure out if an equivalent of the fill call is needed here.
Dart_NewListOfType

Should look at removing the following calls
Dart_Allocate
Dart_AllocateWithNativeFields
Dart_InvokeConstructor
- calls to these are in //depot/google3/third_party/dart_lang/tonic/dart_wrappable.cc and @chinmaygarde  has removed them.


Dart_GetType -needs an additional argument.

Would we want to know if a library is opted in or opted out ?

Dart_CompileToKernel/Dart_CompiledSourcesToKernel does it need a way to pass parameters to CFE (--enable-experiment).

Does the C/Dart messaging API needs a change?

**Comment by bkonyi** [comment]
`Dart_Allocate`, `Dart_AllocateWithNativeFields`, and `Dart_InvokeConstructor` were removed in https://github.com/dart-lang/sdk/commit/3d1b8b26c2282b27559a42c564035f946492e7cd.

**Comment by bkonyi** [comment]
Added support for nullable/non-nullable/legacy types in https://github.com/dart-lang/sdk/commit/06f86bf58ae30e65c92d77c9a74ba2399f2d2956

**Comment by franklinyow** [comment]
Are we ready to close this?
Thx

**Comment by bkonyi** [comment]
Yes, we just need to remove the Dart_Allocate APIs described above. However, that's not directly related to NNBD so I'll close this issue.
