### ISSUE TITLE
Unhandled exception from VM writing a stdin that may be closed

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#40172]
The following code sometimes (quite often actually / almost every time) throws the following exception. The expected result is that no exception/error should be thrown.

```dart
import 'dart:io';

void main() async {
  final head = await Process.start('head', ['-1']);
  head.stdout.pipe(stdout); // only here to display the result
  head.stdin.writeln('a'); // this single element should stop head -1 process
  head.stdin.writeln('b'); 
}
```

```
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:789:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1442:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:1862:19)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:1617:22)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:1592:11)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#9      _StreamController._add (dart:async/stream_controller.dart:642:7)
#10     _StreamController.add (dart:async/stream_controller.dart:588:5)
#11     _StreamSinkImpl.add (dart:io/io_sink.dart:158:17)
#12     _IOSinkImpl.write (dart:io/io_sink.dart:291:5)
#13     _IOSinkImpl.writeln (dart:io/io_sink.dart:311:5)
#14     _Socket.writeln (dart:io-patch/socket_patch.dart:1708:44)
#15     _StdSink.writeln (dart:io/stdio.dart:343:11)
#16     main (file:///xxx/test.dart:7:14)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

I tested on the following VM:

```
$ dart --version
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "linux_x64"
```

This issue popped up via https://stackoverflow.com/questions/59746768/dart-how-to-pass-data-from-one-process-to-another-via-streams

**Comment by sortie** [comment]
Everything seems to be working as intended in your case. What's happening is that your code makes a new process whose standard input is a pipe from the dart process. You write a line and the "head -1" process outputs the line and then process exits. The other end of the pipe is now closed. Finally your code writes another line to the pipe, but the pipe is closed, and the write fails with EPIPE (Broken pipe). That is how pipes work. (By default the broken pipe condition would even kill the process with SIGPIPE, but Dart suppresses the signal and instead delivers it as the EPIPE (Broken pipe) error condition.)

 You can read more about how pipes work on Linux in the manual: http://man7.org/linux/man-pages/man7/pipe.7.html

**Comment by a14n** [comment]
Thanks for your explanation. The following-up question is : is there a way from my dart program to catch this error or to know that the pipe is closed? That way I could condition the `head.stdin.writeln('b')` to avoid this exception.

**Comment by sortie** [comment]
You'll have to catch the exception. You can't check if the pipe is closed in advance, and even if you could, the pipe could be closed by the other process between your check and a subsequent write. The Broken pipe (EPIPE) error is how the operating system tells you about this condition.

**Comment by a14n** [comment]
>You'll have to catch the exception

Could you provide an example? Simply add try-catch around `head.stdin.writeln('b')` doesn't work.

**Comment by sortie** [comment]
`Process.stdin` is an [IOSink](https://api.dart.dev/stable/dart-io/IOSink-class.html), which enqueues the writes and do them asynchronously in the background, but it has a `done` future that lets you catch error conditions:

```dart
import 'dart:io';

void main() async {
  final head = await Process.start('head', ['-1']);
  head.stdout.pipe(stdout); // only here to display the result
  head.stdin.done.catchError((e) {
    print("Caught: $e");
  });
  head.stdin.writeln('a'); // this single element should stop head -1 process
  head.stdin.writeln('b'); 
}
```

**Comment by a14n** [comment]
Awesome! Thanks for your help.
