### ISSUE TITLE
VM should support unforked Null Safe SDK

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40179]
This is the meta issue to track all issues that need to be addressed before we claim that the VM can support unforking of the Null Safe SDK.

Dependent issues -
 
NNBD support in Dart API #40176
NNBD Legacy mode test failures in co19_2/Language/Generics/typedef_A04 #40171 
NNBD Legacy mode test failure in dart_api_impl_test.cc #40170
NNBD Legacy mode test failures in snapshot_test.cc #40169
Migrate dart:vmservice to NNBD #40046 
Migrate dart:mirrors and tests to NNBD #40045 
Migrate dart:cli and tests to NNBD #40044 
Migrate dart:isolate and tests to NNBD #40042 
Migrate dart:io and its tests to NNBD #40040
Error accessing static field from nested function #39929 
type '_Invocation' is not a subtype of type '_InvocationMirror' in type cast #39815
Implementation of NNBD runtime checks for weak mode support #39755 
Migrate patch files in core libraries and dart:io library to be NNBD clean #39754
Dart ignores non-nullability of variables and function parameters. #39678
NNBD. Dart ignores required named parameters #39660 
Required Named Parameters in VM #38843 
Migrate VM libraries to NNBD Epic #38037 
Replace the SDK platform libraries with the NNBD migrated version #37929 
Migrate core libraries to NNBD #37928 
NNBD platform library migration Epic #37926

**Comment by franklinyow** [comment]
Looks like this is done.  Can I close this?

**Comment by franklinyow** [comment]
closing it as all issues completed
