### ISSUE TITLE
CFE support for Unforked Null Safe SDK

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40186]
This epic is used for Phase 1 (Unforked Null Safe SDK) support for CFE.

**Comment by vsmenon** [comment]
@franklinyow @johnniwinther - I think we decided most of these are not blocking unforking.  Can we adjust the epic accordingly?

**Comment by johnniwinther** [comment]
I recently moved a couple of subissues to the 'Complete null-safety' epic. Which of the current list of subissues do you think should not be part of this epic?
