### ISSUE TITLE
Analyzer support for Unforked Null Safe SDK

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40192]
Everything needed to be able to safely analyze legacy projects once the SDK is unforked.  Includes language versioning functionality.

**Comment by franklinyow** [comment]
Are we ready to close this Epic?

**Comment by stereotype441** [comment]
> Are we ready to close this Epic?

Yes, I think so.  It's possible that more issues will be disovered when we try to actually land the un-fork CL, but if they do we can address them as they arise.
