### ISSUE TITLE
DDC nnbd is equivalent for all legacy tests

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40199]
This is a tracking issue for getting to parity on the null-safe weak configuration.

Current status (ignoring compile-time errors):
* language_2: 12/6112 discrepancies (0.20%)
* corelib_2: 12/517 discrepancies (2.32%)
* lib_2 (no html): 13/527 discrepancies (2.47%)
* lib_2/html: N/A
* dartdevc_native: N/A
* co19_2: N/A

**Comment by franklinyow** [comment]
Can this be closed?

**Comment by sigmundch** [comment]
Yes, in particular there are no regressions anymore: any test that passed before, passes now, except for known breaking changes.

Note however that there are some discrepancies we haven't triaged, like new tests passing that used to fail before. We should still investigate those to make sure the change is not due to a hidden bug.
