### ISSUE TITLE
Add overlays to analysis server diagnostics

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40196]
This came up in an issue recently because a VS Code (or VS Code extension) bug caused the VS Code extension to get edits in the wrong order.

I thought this already existed (as did @devoncarew) but couldn't find it, but it turns out it was lost in a refactor (79eb965d8f9ecb90f71d3f100df10e13ef550a1e). I think the reason is that the full contents of overlays is not currently exposed.

I think this would be useful to add back because depending on the response to the LSP spec updates, there's the possibly of incorrectly applying edits in LSP (especially given there are lots of LSP clients - that means lots of potential for people to have subtle bugs that only show up based on ordering of edits).

@bwilkerson The things preventing this from working right now at that we don't expose `OverlayResourceProvider._overlayContent` to the diagnostic page. If I make this non-public (or add getters to get the list of keys, and make `_getOverlayContent` public) then page loads and functions fine.

Does it seem reasonable to add? Is there a preferred way to expose that overlay data?

**Comment by bwilkerson** [comment]
I don't understand why we'd need to do that, but I don't have the changes you're proposing as an example to look at.

My expectation would be that we'd add a link to the file list (where we have 'ast' and 'element model' links). We could either make the link conditional on `hasOverlay(path)` or maybe just annotate the link if there's an overlay, and then just use the normal `getFile(path).readAsStringSync` API to get the actual content when the user clicks that link.

**Comment by DanTup** [comment]
That seems like it'd work. I was starting from the original code which has a specific overlay page that lists only the overlays:

https://github.com/dart-lang/sdk/commit/79eb965d8f9ecb90f71d3f100df10e13ef550a1e#diff-8be5d8395588d478be85ba22d6943de0L1032

It has access both to a list of files with overlays, and also the content. I think adding it alongside the ast/element links would be pretty simple though and not require API changes. Do you have any preference for only showing overlays versus allowing accessing any file (and annotating whether it's an overlay)?

**Comment by bwilkerson** [comment]
Not a strong preference. It might be useful to look at the content of non-overlaid files at some point, but I don't have a use case in mind.

**Comment by DanTup** [comment]
Ok, sgtm. I added a `*` next to the link when there's an overlay:

![Screenshot 2020-01-21 at 13 37 41](https://user-images.githubusercontent.com/1078012/72809512-ab2c9800-3c53-11ea-9d59-081989a70a06.png)

Plus a note on the page saying whether it's an overlay or not:

![Screenshot 2020-01-21 at 13 37 48](https://user-images.githubusercontent.com/1078012/72809513-ab2c9800-3c53-11ea-89df-ec88e6aadc17.png)

https://dart-review.googlesource.com/c/sdk/+/132662/
