### ISSUE TITLE
Completion not working for function generics

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40190]
Completion is not working on function generic types. Check the code:

![image](https://user-images.githubusercontent.com/1146982/72536491-18f25180-3859-11ea-8569-b1f478302c50.png)

But it works for the 'int' class:

![image](https://user-images.githubusercontent.com/1146982/72536584-46d79600-3859-11ea-9e0c-3717825b35d7.png)

![image](https://user-images.githubusercontent.com/1146982/72536624-59ea6600-3859-11ea-8888-adebfd8b3072.png)

_EDIT: I tested other primite types and none of them are working, except `int`. `String` also doesn't work._

Code snippet:

```dart
void main(List<String> arguments) async {

  justAFunction<>(); 

}

void justAFunction<T>(T type) {
  print("The type is ${type}");
}
```

**Comment by shinayser** [comment]
@pq You seem to be the 'completion' guy 🤣. Can you add the 'analyzer' label?

**Comment by pq** [comment]
@bwilkerson and I were just moments ago talking about exactly this case!  I'll take a look.
