### ISSUE TITLE
Null Safety Stable release - analyzer support

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40193]
Everything needed to analyze NNBD-enabled projects.

**Comment by devoncarew** [comment]
@franklinyow - I'm removing this from the general dart nnbd epic (https://github.com/dart-lang/sdk/issues/41611) in favor of the analyzer beta specific epic (https://github.com/dart-lang/sdk/issues/42317).

**Comment by srawlins** [comment]
Null safety has shipped; can we close this issue even though we have 4 remaining sub-issues? Their completion is no longer tied to the release.

**Comment by franklinyow** [comment]
No objection from me
