### ISSUE TITLE
AOT compilation does not tree shake unused instance variable

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#40197]
Dart code:

main.dart:

```dart
// ignore_for_file: prefer_const_constructors
import 'dart:core';

import 'target.dart';

void main() {
  const Target target1 = Target('1', 1);
  final Target target2 = Target('2', 2);
  // ignore: unused_local_variable
  final Target target3 = Target('3', 3); // should be tree shaken out.
  target1.hit();
  target2.hit();
}
```

target.dart:

```dart
class Target {
  const Target(this.stringValue, this.intValue);

  final String stringValue;
  final int intValue;

  void hit() {
    print('$stringValue $intValue');
  }
}
```

.packages:
```
const_finder_fixtures:lib/
```

I ran this through the Flutter front end compiler:

```
out/host_release/dart-sdk/bin/dart out/host_release/gen/frontend_server.dart.snapshot --sdk-root out/host_release/flutter_patched_sdk --target=flutter --aot --tfa --packages test/.packages -Ddart.vm.product=true --output-dill test.dill test/lib/main.dart
```

I expect `target3` to get tree shaken (it is never referenced after construction and does nothing but initialize unreferenced variables in the ctor).  But it's not.

```
out/host_release/dart-sdk/bin/dart third_party/dart/pkg/kernel/bin/dump.dart test.dill > dump.txt
```

Shows that the instance is still present after AOT compilation.

/cc @aam @alexmarkov

**Comment by dnfield** [comment]
The relevant portion of dump.txt:

```
library from "package:const_finder_fixtures/main.dart" as con {

  import "dart:core";
  import "package:const_finder_fixtures/target.dart";

  static method main() → void {
    final tar::Target* target2 = new tar::Target::•("2", 2);
    final tar::Target* target3 = new tar::Target::•("3", 3);
    (#C1321).{tar::Target::hit}();
    target2.{tar::Target::hit}();
  }
}
library from "package:const_finder_fixtures/target.dart" as tar {

  class Target extends core::Object {
    final field core::String* stringValue;
    final field core::int* intValue;
    const constructor •(core::String* stringValue, core::int* intValue) → tar::Target*
      : tar::Target::stringValue = stringValue, tar::Target::intValue = intValue, super core::Object::•()
      ;
    method hit() → void {
      core::print("${this.{tar::Target::stringValue}} ${this.{tar::Target::intValue}}");
    }
  }
}
```

**Comment by aam** [comment]
> I expect target3 to get tree shaken (it is never referenced after construction and does nothing but initialize unreferenced variables in the ctor). But it's not.

Yeah, currently dart->kernel compiler isn't smart enough to figure out that constructor has no-side effects, so unused local variables like in the example above  stay in the kernel file.
Also, note that the fact that variable is not used doesn't always mean that constructor won't be executed(as it might have side effects).

**Comment by dnfield** [comment]
Talked some more with @alexmarkov about this - it sounds like gen_snapshot would take care of eliding this away anyway and he suspects it wouldn't have further impact on binary size.

I'm not concerned with fixing this case for my immediate need - I think I have a work around for it - but if it does in fact reduce AOT size it seems worthwhile.

**Comment by dnfield** [comment]
As an example here:

It seems like we could find that the VariableDeclaration has no associated sets or gets, and elide it with just the TargetInvocation.  But we could also find that the TargetInvocation only creates VaraiableDeclarations  that also have no gets or sets and elide the whole thing.

**Comment by alexmarkov** [comment]
Tree shaking detects if code is _reachable_ and removes classes and members which are not used in the reachable code. It doesn't remove unused variable, and it doesn't remove reachable code which doesn't have any effect (_dead code_).

In the example above `main` method is reachable, so tree shaking considers Target to be used and doesn't remove any of the calls to Target constructor.

However, VM does so much more beyond tree shaking to optimize this example:

1. When building SSA form, local variables are replaced with SSA values, so unused variables disappear (but their initializer code remains as it may have side-effects).

2. VM inlines all calls to `Target` constructor, so these calls are converted to field assignments. Flow graph after inlining:

```
    v2 <- AllocateObject(Target) T{Target}
    StoreInstanceField(v2 . stringValue = v4)
    StoreInstanceField(v2 . intValue = v5)
    v6 <- AllocateObject(Target) T{Target}
    StoreInstanceField(v6 . stringValue = v8)
    StoreInstanceField(v6 . intValue = v9)
    StaticCall:16( hit<0> v10, using unchecked entrypoint, result_type = T{??})
    StaticCall:18( hit<0> v2, using unchecked entrypoint, result_type = T{??})
```

3. Then, allocation sinking optimization detects that allocated `Target` instance `v6` is only used in field stores which initialize its fields, so it is eliminated:

```
    v2 <- AllocateObject(Target) T{Target}
  0:     StoreInstanceField(v2 . stringValue = v4)
  1:     StoreInstanceField(v2 . intValue = v5)
    StaticCall:16( hit<0> v10, using unchecked entrypoint, result_type = T{??})
    StaticCall:18( hit<0> v2, using unchecked entrypoint, result_type = T{??})
```

I can conclude that the code `final Target target3 = Target('3', 3);` which has no effect was in fact optimized out by the VM's AOT compiler.

**Comment by dnfield** [comment]
Thanks @alexmarkov  - it sounds like this would be an unneeded optimization then.  I'll close this - let me know if I'm misunderstanding.
