### ISSUE TITLE
add lambda completion for positional arguments

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40202]
Tracking issue for positional argument support for function body completion; follow-up from https://github.com/dart-lang/sdk/issues/25267.

**Comment by pq** [comment]
FWIW, some progress...

![where_lambda](https://user-images.githubusercontent.com/67586/72584352-90969f80-389e-11ea-8de8-500722ec4e34.gif)

**Comment by shinayser** [comment]
SOMEONE GIVE AN OSCAR TO THIS GUY

**Comment by shinayser** [comment]
One suggestion, if there is only one parameter, why not just call it it

**Comment by greglittlefield-wf** [comment]
Hey @shinayser, there's actually an existing language issue for that: https://github.com/dart-lang/language/issues/265

**Comment by pq** [comment]
@shinayser: I like the idea of (at least) abbreviating the param name (e.g., `element` => `e`).

fyi @devoncarew @InMatrix @bwilkerson (as this pertains to an ongoing discussion around "personalized completions").

**Comment by shinayser** [comment]
@pq Instead of trying to figure out what is the best case, isn't possible to leave that choice to the user?
I mean. There is a way to set the desired behavior on the `pubspec.yaml`? 

- Full parameter name
-  Abbreviated
- `it`

**Comment by pq** [comment]
> isn't possible to leave that choice to the user?

This is exactly one of the ideas up for discussion.  (See #40207 for a little more conversation.)

Thanks for chiming in!

**Comment by shinayser** [comment]
@pq I don't know if the problem is on my environment, but I am receiving no completion suggestions for optional positional arguments, like:

![image](https://user-images.githubusercontent.com/1146982/74059921-ac85f080-49c7-11ea-841f-b7c7be38b4ad.png)

It should suggest `() =>` or `() { } ` , shouldn't?

My sdk version is:
`Dart VM version: 2.8.0-dev.8.0 (Thu Feb 6 15:47:55 2020 +0100) on "windows_x64"`

**Comment by pq** [comment]
Ah, yes.  Confirmed.  This is a slightly different issue (with a different solution) than the cases above but for sure something we should support.

@shinayser: would you mind opening a fresh issue and cc'ing me?  Thanks!
