### ISSUE TITLE
ddc: emit is checks sensitive to the context library (opt-in vs opt-out)

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40200]
This might be a noop bug, just filing to make sure we discuss and resolve what needs to be done.

The current specification indicates that is checks may behave differently if they occur in an opt-in or opted-out library.

Do we need a parameter for it when emittting code? Because the checks are lowered differently by the CFE (`is Foo*` vs `is Foo`), it is possible that the semantics difference is already handled for us already.

**Comment by franklinyow** [comment]
Any update on this?

**Comment by sigmundch** [comment]
I recall we discussed this and there is nothing to do.
