### ISSUE TITLE
Add NullCheck nodes with an isNullUnsafe bit

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40203]
For mixed strong mode we need to insert NullCheck with an `isNullUnsafe` bit to show that, for runtime soundness, a null has to be performed. 

This for instance need for code like this:
```Dart
// opt-out library
int method() => null;
// opt-in library {
main() {
  int value = method(); // We need to wrap the call to method in a NullCheck
}
```

**Comment by lrhn** [comment]
It can be argued that what you have is an "implicit downcast" from `int*` to `int`, so you can perhaps subsume it into the implicit downcast functionality.

**Comment by johnniwinther** [comment]
I agree, but using a `NullCheck` if only the nullability is unsound, is more precise and can give a more performant static and/or runtime implementation.

**Comment by lrhn** [comment]
That won't help with:
```dart
// non-NNBD code:
List<int> x = [null];
// NNBD code:
List<int> y = x;
// Other NNBD code
main() {
  // No local type hints to suggest that `y[0]` can be `null`.
  int z = y[0];
  print(z.toRadixString(16));
}
```
Effectively, you will probably have to do null checks on *every* assignment to non-nullable types unless you have a global analysis to show you that `null` won't flow there.

**Comment by johnniwinther** [comment]
Good point!

**Comment by johnniwinther** [comment]
@sigmundch : We might want to insert these for fast errors - even though it doesn't provide soundness.

**Comment by johnniwinther** [comment]
Putting this on backlog until the new rules for strong mode as pure strong mode arrives. This change might not be necessary.

**Comment by johnniwinther** [comment]
We don't need this now that strong mode is pure.
