### ISSUE TITLE
sdk needs to update package_config version

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40208]
package_config has been [updated](https://github.com/dart-lang/package_config/pull/56) to support package_config.json, but the SDK is pinned to an old version that doesn't support it.  [edited: analyzer support of package_config.json is not blocked on this]

We might not be ready to do this immediately.  dart-lang/package_config#56 implies more work may be needed and the new package is not yet published.  @lrhn @stereotype441

**Comment by bwilkerson** [comment]
It's my understanding that analyzer already supports the new file. It just doesn't use `package_config` to do so.

**Comment by jcollins-g** [comment]
That's good? We still rely on package_config via imports, though so it needs updating.

**Comment by lrhn** [comment]
The package is *almost* ready. It doesn't support overlapping packages yet, but it should be usable otherwise.
I hope to get the overlapping packages support done this week.

**Comment by lrhn** [comment]
The package has been published as both `package_config` and `package_config_2`. This allows other packages to use `package_config_2` until they have weaned themselves of dependencies on `package_config` &lt; 2.0.0.

**Comment by mit-mit** [comment]
@lrhn @jcollins-g I think this has been resolved?

**Comment by lrhn** [comment]
I believe it has. The `package_config_2` package is dead, long live `package_config` v1.9 (with backwards compatibility).
