### ISSUE TITLE
core libraries: move resolve-input-uri to dart:core?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40214]
In various tools we often hit the issue of how to resolve an input string as a Uri.

We use helper methods to resolve tricky corner cases (e.g. `c:` in linux is not a file URI, but a URI with scheme 'c') and so on. Here is one example imlementation: `pkg/front_end/lib/src/fasta/resolve_input_uri.dart`

Could we share this code somewhere in our core libraries? E.g. a static method in `Uri`?

/cc @lrhn

**Comment by lrhn** [comment]
The operation here is to take an arbitrary input string and detect whether it's a URI or a file path, and in either case resolve it to a URI based on a base URI?

I think that's something that would make perfect sense for a package, but not something I'd put in the platform libraries. Maybe the `path` package?
