### ISSUE TITLE
dart2js: Revisit optimizations of List constructors for NNBD

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#40211]
With null-safety, the constructors `List<T>()` and `List<T>(length)` are being removed.
The replacements, other than list literals, are `List.empty()` and `List.filled(length, value)`, both with optional `growable:` arguments.

dart2js does optimizations with the legacy constructors, for example, it knows that `List(10)` is fixed-length, and knows the length, and generates `new Array(10)`, sometimes tagged with the complete type, e.g. `JSArray<int>`.

We need to do similar optimizations for `List.filled` (and `List.generate`).
It is important at global type analysis and later (SSA) to know:
- The length expression of a list
- Whether the list is fixed-length. This is somewhat complicated by the presence of the `growable:` parameter, which makes the answer value dependent.

One approach might be to re-write calls to `List.filled` with calls to specialized private constructors at the Kernel IR level. If the specialization bakes in the growable attribute (e.g. `List._filled` and `List._filledGrowable`, the fixed-length attribute might be inferred by the current machinery.

**Comment by sigmundch** [comment]
Related to these, we are also looking at how to improve dart2js tracing of nested arrays in the global analysis. Some benchmarks show that `List.generate` makes it harder to trace what's the type of the values in the list (especially whether those are arrays as well), as a result accesses to elements on the array are more imprecise than we would like.

**Comment by rakudrama** [comment]
## Tracing
We get a lot of precision from per-list element tracking. The Havlak benchmark creates a list of lists. The dart2 version allocates an list and assigns each element in a loop with a second list. The outer list is inferred as a collection with an element also being a collection with concrete implementation type.

The inferrer models each `[]`/`List()`/`List(n)` list constructor with a new ListTypeInformation. Since we lower `List(#)` to `new Array(#)` we can trace each list to see if it grows (for list literals which are growable) or if the flag property marking it as fixed-length is used (so we can omit the flag on fixed length lists that provably does not flow to length-modifying operations).

To get the same precision for the current constructors, `List.empty`, `List.filled`, `List.generate`, `List.of`, `List.from` and `List.unmodifiable` we need to trace each constructor.
The problem with tracing calls to, say, `List.filled` is that we still have the call. The implementation of `List.filled` itself contains a creation. When we trace that implementation creation, it does not flow anywhere, since we ignore the returned value and substituted the collection for the call site. Thus we might incorrectly conclude that a fixed-length allocation is never challenged, and omit the flag property. (This optimization is currently disabled with a mysterious comment.)

To fix tracing, we need to connect the inner, or _source_, collection with the outer, or _replacement_, collection.

We could have a 'linear-replacement' node in the inferrer graph that works a bit like a Φ-node that propagates types from only the replacement input but allows tracing through both inputs.

It would be useful if we could model some cases of `List.of`, `List.from` and `List.unmodifiable`. The basic idea is that the input to `List.of` flows to a node that links the collection element node of the input to the collection element node of the output, and links in a declared type node if the input LUBs to a non-collection node. 

## Length forwarding
One important optimization is detecting that lists have the same length.
```dart
var a = List(size);
var b = List(size);
for (int i = 0; i < size; i++) a[i] = b[i] = 100;
```
How we do this with `List(n)` is we keep a note of the HInstructions that represent fixed-length lists. The optimizer can then 'store-forward' the length. `a.length` and `b.length` in the bounds checks  (0 <= i < a.length) are replaced by `size`, making it possible to eliminate the checks (0 <= i < size).

We could also recognize `List.filled` and `List.generate` in a similar way.

## `List.generate` macro-expansion
To fully recover the precision in the dart2 version of Havlak, the `List.generate` in the new version would have to be traced with two levels of call-site context-sensitivity.

An alternative is to inline calls as a Kernel transform:
```
List<T>.generate(size, (i) => e, growable: g)

BlockExpression {
  // Evaluate arguments to new variables
  int _size = size;
  bool _growable = g;
  // Allocate an array of required size.
  // Inferrer recognizes this constructor and starts with an [empty] element type.
  // i.e. the elements are 'late'.
  var _result = List<T>._allocate(_size, growable: _growable);
  for (int _i = 0; _i < _size; _i++) {
    var i = _i; // Bind closure parameter
    _result[_i] = e;
  }
  return _result;
}
```

- if the function is not a function expression, it could be captured and called.
- if the function is a function expression with non-simple body, it could be captured and called. For dart2js it is probably best to not expand the call to `List.generate` in this case.
- `_allocate` could be further specialized depending on a known value for `growable`.

DDC could use this transform too. An optimizing compiler will erase trivial renames. DDC might be served better by generating tighter code, not introducing new variables where unnecessary.

**Comment by rakudrama** [comment]
I have implemented
- Tracing of all the `List` constructors.
- Length forwarding for fixed-length `List.filled` and `List.generate`.
- Expansion of `List.generate` for simple direct closures.
