### ISSUE TITLE
Late final field doesn't throw when written / rewritten by initializer

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40219]
This example from the spec:

```dart
int i = 0;
late final int x = i++ == 0 ? x + 1 : 0;
void main() {
  print(x);
}
```

doesn't throw as required by the spec: 
https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables

The kernel lowering doesn't appear to trigger a `LateInitializationError`:

```
library from "org-dartlang-app:/finalinit.dart" as fin {

  static field core::int i = 0;
  static field core::int? _#x = null;
  static get x() → core::int
    return let final core::int? #t1 = fin::_#x in #t1.==(null) ?{core::int} fin::_#x = (let final core::int #t2 = fin::i in let final core::int #t3 = fin::i = #t2.{core::num::+}(1) in #t2).{core::num::==}(0) ?{core::int} fin::x.{core::num::+}(1) : 0 : #t1{core::int};
  static method main() → void {
    core::print(fin::x);
  }
}
```

@johnniwinther @leafpetersen

**Comment by vsmenon** [comment]
Running with
```
ddb -k -d --nnbd strong finalinit.dart
```

**Comment by johnniwinther** [comment]
This feature spec has:

"If a variable or field is read from during the process of evaluating its own initializer expression, and no write to the variable has occurred, the read is treated as a first read and the initializer expression is evaluated again."

This means that the example should _not_ fail but evaluate to `1`.

@leafpetersen: Do you agree?

**Comment by leafpetersen** [comment]
@johnniwinther No, unfortunately you have to read a little further down (and the way I've written it is a bit confusing):

```
Let D be a late and final local variable declaration named v without an initializing expression. It is a run-time error, throwing an instance of LateInitializationError, to assign a value to v if a value has previously been assigned to v.

Note that this includes the implicit initializing writes induced by evaluating the initializer during a read. Hence, the following program terminates with a LateInitializationError exception.

int i = 0;
late final int x = i++ == 0 ? x + 1 : 0;
void main() {
  print(x);
}
```

I should delete the part about "without an initializing expression", since the following paragraph applies it to the case with an initializing expression as well.
