### ISSUE TITLE
Type inference for get methods

### ISSUE THREAD

**Issue by ogierm** [dart-lang/sdk#40227]
using Dart 2.7.0

It's kind of bugging me that there is no type inference for `get` methods?
Atleast
```dart
get bla => _bla;
Duration _bla;
```
infers `bla` to be of the type `dynamic`.

**Comment by bwilkerson** [comment]
The lint `recursive_getters` should catch such cases.

**Comment by ogierm** [comment]
@bwilkerson oh, I didn't know about the linters

**Comment by mit-mit** [comment]
Closing as by design
