### ISSUE TITLE
Analyzer emits spurious conflicting interfaces error for mixed mode interfaces

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40221]
Given the following code:

test6.dart:
```dart
class S<T> {}
```

test5.dart:
```dart
// @dart = 2.5
import "test6.dart";
abstract class B extends S<String> {}
```

test4.dart:
```dart
import "test5.dart";
import "test6.dart";

abstract class C extends B implements S<String> {}
```

The analyzer currently emits the following error:
```
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable  ~/tmp/test4.dart
Analyzing /Users/leafp/tmp/test4.dart...
  error • The class 'C' cannot implement both 'S<String*>*' and 'S<String>' because the type arguments are different. • /Users/leafp/tmp/test4.dart:4:1 • conflicting_generic_interfaces
1 error found.
```

My read of the spec is that this should not be an error.  The [relevant section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries) calls for an error only if **NNBD_TOP_MERGE** of the two super-interfaces does not exist, and I believe that here it exists and should be `S<String>`.

cc @stereotype441 @scheglov @johnniwinther 

cc @srujzs @vsmenon

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/133329
