### ISSUE TITLE
List<Map<String,dynamic>> should have a method to get a key via index

### ISSUE THREAD

**Issue by maheshmnj** [dart-lang/sdk#40222]
just like we access each element of the list using the index, similarly there should be a way to get a key based on the index of the list without iterating the list,I know we can get the key by iterating the map pair.
for instance I have a datastructure like this 
```
List<Map<String,List<String>>> map = [
{
'key1': [
         'foo',
         'bar',
          ],
  },
{
'key2': [
         'foo',
         'bar',
          ],
  },
...
...
]
```
I dont find any method to get the key at a particular index,I would like to get the keys in this case something like this 

```
map[x].keyAt(0) ; // should return key1
map[x].keyAt(1) ; // should return key2
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
I'm not sure I understand what is being asked for here. For example I don't know what `x` means in the example.

You can get `'key1`` as `map[0].keys.first` and `'key2'` as `map[1].keys.first`.

If you actually have a map with more than one key (and not a list of maps each with one key, as this example), then you can ask for the *n*th key as `theMap.keys.elementAt(n)`, but there is no promise that this will not take time proportional to *n* (or maybe even worse). Maps do not promise efficient index lookup for keys.

**Comment by maheshmnj** [comment]
> I'm not sure I understand what is being asked for here. For example I don't know what `x` means in the example.
> 
> You can get `` 'key1`` as ``map[0].keys.first`and`'key2'`as`map[1].keys.first`.
> 
> If you actually have a map with more than one key (and not a list of maps each with one key, as this example), then you can ask for the _n_th key as `theMap.keys.elementAt(n)`, but there is no promise that this will not take time proportional to _n_ (or maybe even worse). Maps do not promise efficient index lookup for keys.

sorry if the issue is not clear,but this answers the issue

**Comment by lrhn** [comment]
Glad I could help :smile:.
