### ISSUE TITLE
Please could you provide a way to determine CPU architecture e.g. 386, x64 or ARM

### ISSUE THREAD

**Issue by AlexBelchUK** [dart-lang/sdk#40231]
Hello,
    I'm working on FFI dart bindings to the PortAudio project. I'm using dart version 2.7
   on Windows 10 x64, Mac Catalina x64, Linux Ubuntu x84 LTE 18, Rasbian linux ARM

    I've been loading a dynamic library based on the platform operating system name
    e.g. Platform.isWindows() then load a x86 64 bit dll, 
           Platform.isMac() then load a x86 64 bit dynlib
    and Platform.isLinux() then load a x86 bit so library. 

   These are okay when there is only one type of dynamic library for the CPU to load, 
   however if the platform supports a different CPU architecture then there is no current way 
   to determine this in a uniform manner. e.g. is it x32, x64 or ARM type CPU architecture.

   For example under Linux I have Fedora Linux on x86 CPU architecture and also want to allow
   for loading a different dynamic ARM library when using Raspberry-PI ARM CPU architecture.

   Please could you add some functions to the Platform class such as:
   isArchitechtureX32(), isArchitechtureX64(), isArchitechtureARM32(), isArchitechureARM64()
   or equivalent to allow determining the type of dynamic library to load.

   Platform class is in Dart core libraries ("dart:io") used with VM

   Thanks for your help,
Alex.

**Comment by mit-mit** [comment]
cc @dcharkes do we have an FFI api for getting the bitness of the current OS?

**Comment by dcharkes** [comment]
`sizeOf<IntPtr>()` returns 4 or 8 for 32 bits and 64 bits respectively.

However, this is not enough on Linux 32 bit, as one does not know whether you're ARM or ia32. So we also want something for that.

**Comment by dcharkes** [comment]
This has been addressed:

* https://api.dart.dev/stable/2.18.6/dart-ffi/Abi-class.html
