### ISSUE TITLE
Incorrent result when Splitting variable declaration

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40239]
Dart VM version: 2.8.0-dev.3.0.flutter-f96c48307d (Fri Jan 17 18:18:09 2020 +0000) on "macos_x64"
Code:
```dart
var notifications = await _getDocuments<NotificationModel>(
        _firestore
            .collection(FirebaseCollections.notifications)
            .where('consumerId', isEqualTo: uid),
        converter: (doc) => NotificationModel.fromJson(doc.data),
```

Code for the function.
```dart
 _getDocuments<S>(
    CollectionReference collection, {
    @required S Function(DocumentSnapshot) converter,
  }) async {
    return (await collection.getDocuments()).documents.map(converter);
  }
}
```
![2020-01-20 10 46 57](https://user-images.githubusercontent.com/23037821/72750842-cbd0f100-3b72-11ea-9623-78d5fc0a0e41.gif)

**Comment by mit-mit** [comment]
Looks like the issue here in in the 'Split variable decleration' refactoring

**Comment by pq** [comment]
Thanks for the report! I've confirmed this locally and am looking at a fix. 👍

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/133960

**Comment by ThinkDigitalSoftware** [comment]
Thanks a bunch!

On Jan 30, 2020 9:56 AM, The Dart Team <notifications@github.com> wrote:

Closed #40239<https://github.com/dart-lang/sdk/issues/40239> via fccae66<https://github.com/dart-lang/sdk/commit/fccae66fa6511b60d515e2bc86a58a208ec831be>.

**Comment by pq** [comment]
Good deal. Repros are most appreciated!

**Comment by ThinkDigitalSoftware** [comment]
Done. https://github.com/dart-lang/sdk/issues/40406
