### ISSUE TITLE
[vm/ffi] Structs API in NNBD

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#40247]
With NNBD, non-nullable fields need initializers or need to be late field.

Our structs API uses nun-nullable fields, without initializers - because they are replaced by getters and setters:

https://github.com/dart-lang/sdk/blob/ef0c7f16e609e84cad7411394cec9fd8b1e1e04b/tests/ffi/coordinate.dart#L11-L26

We could work around it by replacing them with `late` fields, but it isn't elegant.

```dart
 class Coordinate extends Struct { 
   @Double() 
   late double x; 
  
   @Double() 
   late double y; 
  
   late Pointer<Coordinate> next; 
 } 
```

cc @mkustermann @lrhn

**Comment by ds84182** [comment]
What about making `Struct` subclasses `abstract`? Then you can avoid having to update all the fields to be lateinit.

**Comment by dcharkes** [comment]
We might optimizations that do not expect instances of abstract classes to ever occur.

One of the issues is that we have a default constructor. Having a constructor, rather than a factory, requires the fields to have initializers. Maybe we could get rid of that constructor and only have factories. I'll explore this option.

Another solution proposed by @lrhn is to make fields `external`.

**Comment by dcharkes** [comment]
cc @eernstg

**Comment by eernstg** [comment]
So we're two independent proposers of introducing support for `external` variables for that purpose. ;)

This is just a shortcut for declaring an external getter and an external setter, which is possible today. 

It is also very similar to https://github.com/dart-lang/language/issues/45, 'A variable declaration used only for interface purposes may be abstract', but even though we could use `abstract` and rely on having `Struct` as a superclass (directly or indirectly) to get the right semantics, `external` seems to indicate the actual semantics in a more readable manner.

**Comment by dcharkes** [comment]
Reference to migrating breaking changes for NNBD: https://github.com/dart-lang/sdk/issues/40444.

For this API change, we can probably allow struct fields to be non-`external` for opted out code to ease the migration.

**Comment by dcharkes** [comment]
Proposal language: https://github.com/dart-lang/language/blob/master/working/00044%20-%20Abstract-External%20Variables/proposal.md

**Comment by dcharkes** [comment]
This is not required for unforking the SDK.

For the time being, we can keep the FFI usages opted out of NNBD. (NNBD is an opt in feature.)

**Comment by dcharkes** [comment]
All `tests/ffi/*` now succeed on all configurations except for the analyzer.

```sql
SELECT configuration
FROM `dart-ci.results.latest_results`
WHERE suite = "ffi"
AND unexpected_result IS NOT NULL
GROUP BY configuration;
```

Row | configuration |  
-- | -- | --
1 | analyzer-asserts-strong-linux |  
2 | analyzer-asserts-weak-linux

Analyzer issue: https://github.com/dart-lang/sdk/issues/41940
