### ISSUE TITLE
Mismatched NNBD flags in function type params

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40258]
While fixing https://github.com/dart-lang/sdk/issues/40171, we noticed that the function type parameters have mismatching nullability flags. One was non-nullable and one was legacy, even though they're from the same library.

To repro, set `syntactically` to false in `Function::HasSameTypeParametersAndBounds`, and run co19_2/Language/Generics/typedef_A04_t06 in legacy mode.

**Comment by crelier** [comment]
I am not able to reproduce this issue, whether I force mutual subtyping of bounds or legacy equivalence in `Function::HasSameTypeParametersAndBounds`.
Feel free to reopen if you think the issue still exists.
