### ISSUE TITLE
CFE infers legacy types in opted-in libraries

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40255]
In the following example opted-in library references a class from opted-out library.
If explicit type annotation is used, then the type is non-nullable.
However, if type is inferred by the front-end, then it is legacy (in an opted-in library).

foo.dart:
```dart
import 'bar.dart';

reify<T>(T arg) => T;

main() {
  Foo x = new Foo();
  var y = new Foo();
  print(reify(x));
  print(reify(y));
}
```

bar.dart:
```dart
// @dart = 2.6
class Foo {}
```

Kernel file with non-nullable experiment enabled:
```
  static method main() → dynamic {
    bar::Foo x = new bar::Foo::•();
    bar::Foo* y = new bar::Foo::•();
    core::print(foo::reify<bar::Foo>(x));
    core::print(foo::reify<bar::Foo*>(y));
  }
```

/cc @leafpetersen @stefantsov @johnniwinther @crelier

**Comment by leafpetersen** [comment]
See [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#importing-legacy-libraries-from-opted-in-libraries) for the spec commentary on this.
