### ISSUE TITLE
Unmodified and modified regions can overlap each other

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#40253]
Preview a migration of the collection package, and open `lib/src/empty_unmodifiable_set.dart`. See line 30 which looks like:

```dart
// region explaining why `Iterable<Object>` was unmodified
//               |---------------|
//               v               v
bool containsAll(Iterable<Object?? other) => other.isEmpty;
//                              ^
//                              |
//     region explaining why `?` was inserted
```

We are attempting to mark `Iterable<Object?>` as an _unmodified_ region, then also mark `?` as a modified region. The result is garbled in the HTML.

**Comment by srawlins** [comment]
CC @bwilkerson @stereotype441 

One solution would be to only mark a raw type as an unmodified region (e.g. `Iterable` in `Iterable<Object>` or `Function` in `bool Function(E)`). Possible? Difficult?

**Comment by stereotype441** [comment]
I like that idea.  On the subject of difficulty, I believe that currently the logic for marking unmodified regions is outside the migration engine.  Would it make sense to move it into the FixBuilder?

**Comment by bwilkerson** [comment]
Yes, we should mark all type names as being unmodified (unless, of course, they were modified). Something like `List<String>` should mark both `List` and `String` as unmodified. Without doing so we won't be able to given the user control over all of the separate places where a hint could be added.

**Comment by srawlins** [comment]
This has been side-stepped for now; I've again disabled surfacing of unchanged type annotations.

**Comment by srawlins** [comment]
Closing as the source package has been migrated. I don't think we've hit this recently...
