### ISSUE TITLE
Iterable seems to be null while it's not

### ISSUE THREAD

**Issue by Funnyman420** [dart-lang/sdk#40254]
I call a static function from an imported library (https://pub.dev/packages/contacts_service#-readme-tab-) that used to work perfectly 3 weeks ago, but now seems to have an annoying bug.

Basically i call an async function that is supposed to return my phone contacts, which it does, but when i try to pass the result to other functions or try to convert the Iterable object to List it throws error that the object isn't supposed to be null. Which is clearly not the case as seen from my debugger.

Am i doing something wrong? How am i supposed to counter this?
![72803326-7d951e00-3c56-11ea-97b6-f7d1c6dcb7c0](https://user-images.githubusercontent.com/38563912/72823874-0aeb6900-3c7d-11ea-9bfb-7c778483d891.png)

**Comment by mit-mit** [comment]
It's hard to answer without actual repro steps.

Printing contacts leads to iterating the iterable, are you sure there are not some nulls in there?

**Comment by mit-mit** [comment]
I'm closing this from the SDK repo; this is better tracked in https://pub.dev/packages/contacts_service until we know that there is an SDK issue.

**Comment by lukasgit** [comment]
@mit-mit just now seeing this issue. We have the issue being tracked here: https://github.com/lukasgit/flutter_contacts/issues/71

**Comment by mit-mit** [comment]
This issue is closed. If you are seeing this on the current stable build, please file a new issue
