### ISSUE TITLE
Misleading documentation in dart:typed_data's ByteData (incorrect example) 

### ISSUE THREAD

**Issue by zathras** [dart-lang/sdk#40261]
`ByteData` has this example:
```
var buffer = new Uint8List(8).buffer;
var bdata = new ByteData.view(buffer);
bdata.setFloat32(0, 3.04);
int huh = bdata.getInt32(0);
```
This is misleading, and being slightly pedantic, it's actually wrong, because it's relying on unspecified behavior of the Uint8List constructor.  (The unspecified behavior is, of course, entirely reasonable, but it's still unspecified.)

A better example is:
```
var list = Uint8List(4);
var bdata =
    ByteData.view(list.buffer, list.offsetInBytes, list.lengthInBytes);
bdata.setFloat32(0, 3.04);
int huh = bdata.getInt32(0);
print(huh);
```
This helps reinforce the crucial point that for good reason, `Uint8List.buffer` makes no guarantees about the offset or length of its underlying buffer.  This fact isn't immediately obvious to folks with less experience with, e.g. Java's NIO.

**Comment by mit-mit** [comment]
This is from the API docs: https://api.dart.dev/stable/2.7.0/dart-typed_data/ByteData-class.html

**Comment by mit-mit** [comment]
cc @mkustermann

**Comment by lrhn** [comment]
I can absolutely promise that `new Uint8List(8).buffer` is a buffer with exactly 8 bytes, and the `Uint8List` will have `offsetInBytes` being zero. 
If we haven't documented that, we should.

As such, the example is correct. It may be based on undocumented behavior, but it's that's a flaw in the documentation.

That said, there is no need for the `Uint8List` at all, we could just create the `ByteData` directly:
```dart
var bdata = ByteData(8);
bdata.setFloat32(0, 3.04);
int bits = bdata.getInt32(0); // 0x40428f5c
```

**Comment by zathras** [comment]
The more important thing is to demonstrate in the example is that when you access a `Uint8List`'s buffer, **you should _always_ use that lists `offsetInBytes` and `lengthInBytes`**.

Using `Uint8List` in an example is actually a good thing; it would be a shame to lose that.  It's just bad practice to access a list's `buffer` and make assumptions about its offset, even an offset of zero comes to be guaranteed in the edge case of a newly-constructed list.  That's why I said "being slightly pedantic," and why I said the unspecified behavior is "entirely reasonable."  

Rather than fixing the less important pedantic part, I recommend fixing the part relating to good coding practices:  Use the Uint8List's `offsetInBytes` and `lengthInBytes` in the example.

**Comment by mit-mit** [comment]
Linking to in-progress change: https://dart-review.googlesource.com/c/sdk/+/132844
