### ISSUE TITLE
Refactor migration preview webapp into a build.py artifact

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40263]
Quoting @srawlins:
> Currently the Preview web app of the migration tool is written as multiline Dart strings. Most of the HTML is written into Dart strings. The Javascript is written in a Dart string. The style is written in a Dart string.
>
> The reason is that the Analysis Server, as a snapshot shipped via the SDK to users' computers, does not have access to resources on disk in the SDK (unless I've been in the dark!). So even if in pkg/analysis_server/lib/src/ there was a file called preview.html, package:analysis_server/src/foo.dart cannot attempt to read this file with a relative path, "./preview.html". The only way to load resources, that I've seen, is to bundle them up with the source code: importable Dart files with multiline strings.
>
> One way to improve this system, from a readability, maintainability, and even testability, standpoint, would be to add a build target for the preview web app. If we wrote it in Dart, Flutter, or even left it in its HTML/JavaScript/CSS state, we could write a build.py target that would generate a Dart source file, base64-encoded, with the entire app inside. The app would not contain any data about any specific migration; instead it would contain the web app, backed with data loaded dynamically from the Migration tool preview HTTP server, similar to today.

**Comment by srawlins** [comment]
@devoncarew and maybe others took care of the bulk of this task. It is now a generated project, with a hash check. When discussing with eng-prod, we decided it would be more trouble than value to actually integrate it into the build chain.
