### ISSUE TITLE
Re-run migration quickly after the addition of a hint

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40260]
Several things need to happen:
1. Source offsets stored in the `Variables` data structure need to be updated:
 a. Inner map keys in `Variables._conditionalDiscards` represent offsets of `IfElement` or `IfStatement` nodes.
  b. Inner map keys in `Variables._decoratedTypeAnnotations`, `Variables._expressionChecks`, and `Variables._unnecessaryCasts` represent offset/end pairs, encoded using `uniqueIdentifierForSpan`.  We'll have to do some math to figure out how to invert the encoding.
  c. Note that the outer map keys in all these cases are `Source` objects, so it should be easy to isolate the changes just to the source(s) that had hints added.
2. A new edge needs to be added to the nullability graph to reflect the addition of the hint.  We'll need to replicate the behavior of the last several lines of `NodeBuilder.visitTypeAnnotation` (the lines starting with `var commentToken = node.endToken.next.precedingComments;`).  You can access the decoratedType using `Variables.decoratedTypeAnnotation` (be careful about pre-hint vs post-hint offsets)
3. All nodes in the graph except for `always` and `never` need to have their `_state` reset to `NullabilityState.undetermined`
4. The intermediate data structures used by graph propagation need to be cleared: `NullabilityGraph._unionedWithAlways`, `NullabilityGraph._pendingEdges`, `NullabilityGraph._unsatisfiedEdges`, `NullabilityGraph._unsatisfiedSubstitutions`, and `NullabilityGraph._pendingSubstitutions`.  (Note: maybe it makes sense to pull these into their own object so that it can be thrown away and created afresh)
5. The graph needs to be re-propagated using `NullabilityGraph.propagate`
6. The fix-builder needs to be re-run by calling `NullabilityMigration.finalizeInput` with each source.  Note that currently `finalizeInput` is responsible for calling `NullabilityGraph.propagate`.  Note that this looks slightly different in the pre-fix-builder logic.

**Comment by stereotype441** [comment]
Here's the current state of this, based on a brain dump from @bwilkerson on Friday:
- The feature is currently disabled in the UI.  To turn it on, set the constant `supportsIncrementalWorkflow` (in `region_renderer.dart`) to `true`.
- Currently links we generate for adding hints share the same mechanism we use for other links (we generate a JSON object of type `{text: String, href: String}` - see `linkForEdit` in `migration_renderer.dart`).  However, we need to include some additional information to tell the front end that when the user adds a hint, this should be communicated back to the server using a POST request.
- And of course the front end needs to be modified to understand this information and generate the appropriate POST (see the line beginning with `postLinks.forEach` in `dart_page_script.dart`).
- Then, we'll have to modify the server to handle POST requests (see `HttpPreviewServer._handleServer`).
- Once that's done, we should be able to make the edits and update the migration graph, but then we won’t see any updates, we’ll have to hit refresh to get it to redraw.
- To get updates to work, we'll have to continue writing code in `preview_site.dart`'s `performEdit` method.  What's left to do there is (1) updating the graph by adding or removing an edge, and (2) updating the offsets in the existing structures to reflect the change in the source file.

Brian gave me a diff with the code he was in the middle of writing when he stopped on Friday; I've uploaded it to https://dart-review.googlesource.com/c/sdk/+/133765.  Note that there are merge conflicts with more recent commits; it's not clear whether it's worth trying to resolve these merge conflicts, or just start fresh with master.

**Comment by MichaelRFairhurst** [comment]
Not necessarily high priority, we want this feature to exist and optimizing it is a later concern.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
