### ISSUE TITLE
Unfork DDC runtime support for legacy types

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40266]
To make it easier to unfork nnbd, we plan to first unfork the subtyping logic and test using it with the non nnbd SDK.

This will make it possible to detect bugs and measure the impact of this implementation right away.

**Comment by franklinyow** [comment]
@nshahan Any update?

**Comment by nshahan** [comment]
Yes, we have been running presubmits with our internal repo and we have been fixing failures. We look good in that regard. Now we are focusing on cleaning up some regressions in performance before landing.

**Comment by sigmundch** [comment]
update: we are very close on this, but still working on the performance implications. Most performance work is done, but @nshahan is pushing one last bit here.

**Comment by nshahan** [comment]
Update: Still in progress. Planning on landing as soon as possible after the next stable release is cut.

**Comment by vsmenon** [comment]
What is the status of this?  Do you still plan to do this before the real unfork?  Does it need to be part of the unfork epic?

**Comment by nshahan** [comment]
Yes, changes are out for review and I expect to land them today.
