### ISSUE TITLE
analyzer errors on non-nullable optionals in abstract methods

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#40287]
```
abstract class Foo {
  void bar(int x, [int y]);
}
```

analyzer error:
`The parameter 'y' can't have a value of 'null' because of its type, so it must either be a required parameter or have a default value - line 2`

[Spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) states:
`It is an error if an optional parameter (named or otherwise) with no default value has a potentially non-nullable type except in the parameter list of an abstract method declaration.`

cc @leafpetersen @rakudrama

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/133201

**Comment by scheglov** [comment]
There are additional complications, spec questions.
https://github.com/dart-lang/co19/issues/516

**Comment by rakudrama** [comment]
Analyzer should also permit optional non-nullable parameters without a default for:

- `external` methods.
- `native` methods.

These methods are like abstract methods in that they declare a method without defining one, so should be permitted to omit the default value - it is up to the external code to provide the value.

These special cases usually occur in classes that are _not_ `abstract`.
Handling these is required for migrating `dart:html`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/133283 will also ignore `external` and `native` methods.
