### ISSUE TITLE
analyzer needs to substitute Never in const contexts for null-safe (not Null)

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40283]
```dart
abstract class C<T> {                                                            
  const C();                                                                     
}                                                                                
                                                                                 
class D<T> implements C<T> {                                                     
  const D();                                                                     
}                                                                                
                                                                                 
void f<T>([C<T> c = const D()]) {}
```

This produces

```
A value of type 'D<Null>' can't be assigned to a variable of type 'C<T>'.

Try changing the type of the variable, or casting the right-hand type to 'C<T>'. [invalid_assignment]
```

Interestingly, this doesn't fail for

```
void f([C<int> c = const D()]) {}
```

**Comment by scheglov** [comment]
@leafpetersen Where is logic for eliminating type parameters specified? Currently for legacy libraries we replace `T` with `Null` in covariant context, and with `Object` otherwise. But I was not able to find this in the specification. And similarly, I cannot find where the rule for using `Never` instead of `Null` is.

**Comment by stereotype441** [comment]
@leafpetersen can you help with Konstantin's question (https://github.com/dart-lang/sdk/issues/40283#issuecomment-577822298)?.  It would be nice if we could make some progress on this issue soon, since it's blocking our ability to get the migration tool to fully process `package:collection`.

**Comment by leafpetersen** [comment]
To the question of where this is specified, this may never have made it into the formal specification.

The current behavior was implemented as described here: https://github.com/dart-lang/sdk/issues/32918 .

The computation of least and greatest closure should be changed in NNBD to use Never for the bottom types and `Object?` for the top types.  In the analyzer this applies to _eliminateTypeVariables in type_system.dart as well as leastClosure and greatestClosure.

cc @stefantsov

**Comment by scheglov** [comment]
@leafpetersen Currently for legacy libraries we use `dynamic` in `leastClosure` and `greatestClosure`. And `Object` in legacy for `_eliminateTypeVariables`. But for NNBD we should use `Object?` instead everywhere. This makes me question whether using `dynamic` in legacy in analyzer is correct.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/133880 will make analyzer use `Never` instead of `Null`, and `Object?` instead of `Object` for `eliminateTypeVariables`. For `greatestClosure` and `leastClosure` I kept using `dynamic` for now, pending information.

**Comment by leafpetersen** [comment]
@scheglov Yes, let's make the change to `Object?` instead of `dynamic`, thank you.

**Comment by scheglov** [comment]
I updated [the CL](https://dart-review.googlesource.com/c/sdk/+/133880) to use `Object?` instead of `dynamic`.
