### ISSUE TITLE
dart:io and dart:html WebSocket classes have different behavior

### ISSUE THREAD

**Issue by ja2375** [dart-lang/sdk#40292]
`dart:io#WebSocket.connect()` throws an exception when it fails to connect to websocket, that's OK for me. But `dart:html#WebSocket.connect()` has a different behavior and I don'r seem to be able to find a cross-platform implementation to handle connection errors.

`dart:html#WebSocket.connect()` just prints to js console when it fails to connect, that makes no sense to me as that makes the program stop right there when it fails to connect.

I think it would be better to throw an exception just like `dart:io#WebSocket.connect()` does.

I'm using the lastest Flutter SDK in dev channel (that is Flutter SDK 1.14.3 with Dart version 2.8.0-dev.3.0 f910a7575f). AND i am also using [websocket](https://pub.dev/packages/websocket) package on pub.dev to make websocket cross-platform.

**Comment by sortie** [comment]
You should ask the [package:websocket](https://github.com/truongsinh/dart-websocket/) for help if you are having trouble with it. It appears it [awaits s.onOpen.first](https://github.com/truongsinh/dart-websocket/blob/master/lib/src/websocket_browser.dart#L49) before listening for errors. That's probably what causes an unhandled exception in your page.

You should listen on [onError](https://api.dart.dev/stable/2.7.1/dart-html/WebSocket/onError.html) and [onClose](https://api.dart.dev/stable/2.7.1/dart-html/WebSocket/onClose.html) on the websocket after connecting a plain dart:html [WebSocket](https://api.dart.dev/stable/2.7.1/dart-html/WebSocket-class.html). That should work - it works in my code. If it doesn't, let us know. I'm closing this issue as it seems to be a bug in the package you use rather in the Dart SDK. Please reopen if it is a bug in the Dart SDK. I'm removing the library-io tag as this issue appears to be about dart:html.
