### ISSUE TITLE
analyzer: Support FileContentOverlay or equivalent in public api

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#40294]
I would like to use a `FileContentOverlay` together with public analyzer apis. Ideally, I'd prefer the current class to be published and made available as an optional parameter
- in `ContextBuilder.createContext`
- in the `AnalysisContextCollection` factory constructor

I want to reduce the amount of internal analyzer apis I depend on, but I need to support temporarily overridden files. Having this api exposed would allow me to migrate away from creating a `DartAnalysisDriver` manually and instead use the public api.

I'm happy to work on this myself and submit a CL, but I'd appreciate some quick feedback on if exporting the class like that makes sense.

**Comment by bwilkerson** [comment]
Thanks for starting the discussion.

It might not be necessary to make that class public in order to get you what you need. Both of those classes takes a `ResourceProvider` in their constructors, and we have a public implementation of `ResourceProvider` named `OverlayResourceProvider` that is intended to allow you to overlay the analyzer's view of the file system.

I'd be interested to know whether that covers the cases you're trying to support.

**Comment by simolus3** [comment]
That sounds exactly like what I need, thanks for the quick reply!

If I run into any issues with that I'll re-open, but it looks like that solves my problem.

**Comment by simolus3** [comment]
I know it's not directly related, but now I'm wondering if it makes sense to change the `analyzer_plugin` package so that users won't have to use internal (or even deprecated) analyzer apis.

As a simple starting point, it could expose a `ResourceProvider` that respects current overlays.
Further, since none of the published plugins actually use an `AnalysisDriverScheduler` to coordinate work (they create one scheduler for each custom driver), maybe the api could be changed so that users wouldn't have to implement their own `AnalysisDriverGeneric` at all? Instead, the plugin could manage a context collection and only expose apis to obtain the current `AnalysisSession` for a path. It would be a breaking change, but not having to mess around with custom analysis drivers would make writing plugins much easier. The plugin api would also be closer to what people already know from the [analyzer tutorial](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/doc/tutorial/analysis.md) or from writing builders.

I would love to work on this, but I'm a little worried after my CL to bump the analyzer version took 3 months to get merged and still hasn't been released to pub. I fully respect that the analyzer team has other priorities and I don't want to blame anyone, but do you think this would have a chance of getting merged and published if I open a CL?
