### ISSUE TITLE
Migration tool doesn't handle overrides with function typed parameters well

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40306]
The migration tool doesn't seem to correctly add nested nullability annotations inside the parameters of function type parameters in overrides, resulting in invalid overrides.  

// opted_in.dart
```dart
class B {
  void bar(int? x) {}
  void foo(List<int?> Function(List<int?>) f) {}
}
```

// opted_out.dart
```dart
import "opted_in.dart";
class A extends B {
  void bar(int x) {}
  void foo(List<int> Function(List<int>) f) {}
}
```

Running the migration tool on opted_out.dart results in:
```dart
class A extends B {
  void bar(int? x) {}
  void foo(List<int?> Function(List<int>) f) {}
}
```

Note that the parameter type of `f` has been left as `List<int>` instead of `List<int?>`, resulting in an invalid override.

Function types in general seem problematic to handle, but for the specific case of overrides, it seems pretty straightforward to just merge in the required non-nullability annotations. 

cc @stereotype441 @MichaelRFairhurst

**Comment by stereotype441** [comment]
Actually I think this the migration tool is implementing the correct behavior in this case.  An override's parameters are allowed to be more accepting than the base method's parameters, so in other words the base method's parameter type should be a subtype of the override's parameter type.

Using the types produced by the migration engine, we need to satisfy:
```
List<int?> Function(List<int?>) <: List<int?> Function(List<int>))
```
Function types are contravariant in their parameter types, so this will be satisfied if:
```
List<int> <: List<int?>
```
Interface types are covariant in their type parameters, so this will be satisfied if:
```
int <: int?
```
Which is indeed the case.

Please feel to reopen if I've got my logic wrong here.

**Comment by leafpetersen** [comment]
Sorry, yes, I misdiagnosed this - I interpreted the analyzer errors I get post migration as giving me the argument type not the method type.  There is still something going wrong (I get override errors post migration), but I'll need to do a bit more digging for a repro.

I do wonder whether this specific choice here is the right choice of migration though.  One could argue that in the above case there is no evidence that the argument of `foo` needs to accept `List<int?>`, and hence it's better to tighten it to `List<int>`.  But I think superclass types are a pretty strong signal about intent here, and I worry that this sets up a trap for subsequent implementers.

At the least, I would suggest that the migration tool *not* do this for abstract methods (which it seems to do).  If I make the classes above abstract and remove the bodies of `foo`, it still chooses `List<int>` for the argument type of `f`, which doesn't seem likely to be what is desired.

**Comment by leafpetersen** [comment]
Filed https://github.com/dart-lang/sdk/issues/40320 with the concrete issue that I'm seeing.

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on the migration tool right now.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
