### ISSUE TITLE
Failures on Add an initial tests for dartdev that can execute and pass on the Dart build bots, as well as locally.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#40319]
I'm not sure what this test does but it used to mention 'dart2js' and now does not and fails as below:

There are new test failures on [Add an initial tests for dartdev that can execute and pass on the Dart build bots, as well as locally.](https://github.com/dart-lang/sdk/commit/e9bd2595f4d913bbaf7bd44365fc8bee0075cf15).

The tests
```
pkg/dartdev/test/command_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-minified-linux-d8
```

**Comment by rakudrama** [comment]
It should probably be `SkipByDesign` in the `.status` file.

**Comment by rakudrama** [comment]
https://dart-review.googlesource.com/c/sdk/+/133282

**Comment by sigmundch** [comment]
it appears there is a duplicate issue at https://github.com/dart-lang/sdk/issues/40318

@whesse - when creating an issue from the feed, could the feed show the issue also so that we prevent duplicate filings?
