### ISSUE TITLE
Migration preview doesen't distinguish adding and removing `?`s.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40314]
As of https://dart-review.googlesource.com/c/sdk/+/133241, here's what it looks like in the migration preview when migration adds a `?`:
![image](https://user-images.githubusercontent.com/306375/73082671-c2030280-3e7e-11ea-8a0e-1f8071c154f5.png)
And here's what it looks like when migration removes a `?`:
![image](https://user-images.githubusercontent.com/306375/73082749-df37d100-3e7e-11ea-8def-16252cde6ec6.png)
These need to be better distinguished.  Maybe we can color deletions red, or use a strikethrough?

**Comment by srawlins** [comment]
Do you have an example of a deletion, like a deleted `?`, that I can work with to design the UI?

**Comment by stereotype441** [comment]
Sure, you can use this (from `test_remove_question_from_question_dot` in `api_test.dart`):
```dart
_f(int/*!*/ i) => i?.isEven;
```
