### ISSUE TITLE
Add a hint if language-versioning comment not at top of file

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40316]
A couple of us have run into the mystery of finding out why a language-versioning comment was not working. Turns out we only process comments of the form `// @dart = 2.7` if they appear above all the code, it took us some time to realize that we had our comment below the imports and that was why it wasn't working.

Questions:
* Would it be possible to support it also if it appears after the imports? (e.g. maybe we don't want to support it below imports in case a language feature affects the import syntax itself)
* If not, could we add an analyzer hint indicating that it is not going to be used if it's not at the top of the file?

@stereotype441 @johnniwinther @leafpetersen - not sure under what area I should file this, I tentatively put both CFE (in case it is a scanner change) and analyzer (in case we decide to do the hint)

**Comment by johnniwinther** [comment]
The scanner only searches for language version tokens in the header (i.e. before any non-comment and non-whitespace characters have occurred).

To discover later occurrences we would need to scan every single-line comment which is likely to slow down tokenization.

**Comment by stereotype441** [comment]
I'd be ok with us doing it as an analyzer hint

**Comment by lrhn** [comment]
The idea with putting the language version marker before any Dart declaration is that it should be possible to detect the language version before *needing* it. It's possible for a library to have its first declaration be `late foo = 42;`, and at that point, we would like to know whether the `late` is a keyword or a type name.

Obviously it's possible to scan the file more than once, first to detect the language version, then to tokenize it, but as stated above, it comes with a cost.

Also, a the language version downgrade marker is important for understanding the file, so even for human readers, it's convenient if it occurs very early.

**Comment by stereotype441** [comment]
Ok, I'm removing area-front-end and categorizing this under one of the analyzer epics, under the assumption that we'll add a hint.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/138388
