### ISSUE TITLE
Weird Extensions precedence

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40315]
Please check this code:

```dart
extension Iterable1<R> on Iterable<Iterable<R>> {
  Iterable<R> flatten() sync* {
    for (var current in this) {
      yield* current;
    }
  }
}

extension Iterable2<R> on Iterable<R> {
  Iterable<dynamic> flatten() sync* {
    for (var current in this) {
      yield* (current as Iterable);
    }
  }
}

void main(List<String> arguments) async {
  var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ];

  var shouldBeAListOfInts = theList.flatten().toList();

  print(shouldBeAListOfInts.runtimeType); //prints List<dynamic>
}
```
In the code above, the extension `Iterable2` is always taking precedence over `Iterable1`, even `Iterable1` being more specific the `Iterable2 `.

Is some bug here or is it an intended behavior? There is a way to make this code work with both extensions?

**Comment by tatumizer** [comment]
Iterable2 is more specific than Iterable1.
R is a free variable in Iterable2. The list `theList` has a type `List<List<int>`, which is certainly an `Iterable<List<int>>`. So R becomes `List<int>`, which is more specific than `Iterable<int>`. 

Considering that you never use R in the extension Iterable2, you can simply rewrite it as
```
extension Iterable2  on Iterable {
  Iterable<dynamic> flatten() sync* {
    for (var current in this) {
      yield* (current as Iterable);
    }
  }
}
```
Now everything should work as you expect.

**Comment by shinayser** [comment]
The problem is `Iterable2` is condensed. In my real life case, it contains much more methods (and they use the R variable)

**Comment by tatumizer** [comment]
Let's verify that we are on the same page.
When you declare theList as
```
var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ];
```
you expect it to be dispatched to the first extension.
Could you provide the example of the declaration of `theList` to which the second extension is expected to apply?

**Comment by shinayser** [comment]
I want to apply this to Extension1:

```dart
var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ];
``` 

And this to Extension2:

```dart
var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    10,
  ];

OR

var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    "ten",
  ];

```

**Comment by tatumizer** [comment]
So, you want the first extension to apply to Iterable<Iterable<R>>, and the second - to Iterable<R> where 1) R is NOT Iterable 2) you really need a type variable R
I think it's a noble, but impossible goal. You have to sacrifice 2), then it would be easy.
I might be wrong though, but then, if anybody knows how to do it, it's not me. @lrhn - any thoughts?

**Comment by shinayser** [comment]
I am trying to improve the flatten method for the `dartx` library. It has the Interable2 extension with tons of methods inside it, but the `flatten` method always returns dynamic, losing the type.

Any thoughts would be welcome.

**Comment by tatumizer** [comment]
By any chance, aren't you trying to re-implement [expand](https://api.dart.dev/stable/1.10.1/dart-core/Iterable/expand.html)?

**Comment by lrhn** [comment]
> The problem is `Iterable2` is condensed. In my real life case, it contains much more methods (and they use the `R` variable)

Can you give an example of *how* it sues the type variable, because that may suggest what to do.
The code that and examples you have here do not look like something that can be safely typed using extensions. The choice of extension can only depend on the static type of the receiver, not the return type or the arguments, and the type of
```dart
var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    10,
  ];
```
is `List<Object>`, so it's limited which type variables you can extract from that.

The disambiguation rules in the extension resolution algorithm are tricky. 

They always pick the match that is on the *more specific* type, and in case of a tie, the one with the most specific type without the type parameters bound, because that is *most likely* to provide the most specific result. There will be exceptions to that, but hopefully they will be rare.

**Comment by shinayser** [comment]
> By any chance, aren't you trying to re-implement [expand](https://api.dart.dev/stable/1.10.1/dart-core/Iterable/expand.html)?

The problem with the expand is that it needs a lambda parameter to work. I wanted to make it work without the lambda.

> > The problem is `Iterable2` is condensed. In my real life case, it contains much more methods (and they use the `R` variable)
> 
> Can you give an example of _how_ it sues the type variable, because that may suggest what to do.
> The code that and examples you have here do not look like something that can be safely typed using extensions. The choice of extension can only depend on the static type of the receiver, not the return type or the arguments, and the type of
> 
> ```dart
> var theList = [
>     [1, 2, 3],
>     [4, 5, 6],
>     [7, 8, 9],
>     10,
>   ];
> ```
> 
> is `List<Object>`, so it's limited which type variables you can extract from that.
> There is the option of having more than one extension, so you can have
> 
> ```dart
> extension GenericItreableX<T> on Iterable<T> {
>   ...
> }
> extension IterableX on Iterable<dynamic> {
>   Iterable<dynamic> flatten() sync* {
>     for (var element in this) { 
>       if (element is Iterable) yield* element.flatten();
>     } else {
>       yield element;
>     }
>   }
> }
> ```
> 
> The disambiguation rules in the extension resolution algorithm are tricky.
> 
> They always pick the match that is on the _more specific_ type, and in case of a tie, the one with the most specific type without the type parameters bound, because that is _most likely_ to provide the most specific result. There will be exceptions to that, but hopefully they will be rare.

Thanks for your explanation. I think my idea has no resolution then :(
