### ISSUE TITLE
Update TypeError/CastError messages for null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#40326]
When a cast fails for generic classes DDC attempts to generate a helpful error message by inferring the type arguments that would allow the cast to succeed. This relies on an alternate implementation of the subtyping algorithm that needs to be updated for null safety. 

We have not yet made any changes to the algorithm because:

- It appears to be mostly untested.
- It is only triggered on a generic class cast failure.
- It's not clear how this should handle failures in mixed mode (opt-in/opt-out) settings.
- I wasn't aware this code existed when I updated the runtime subtype checks. ☹️

**Comment by sigmundch** [comment]
@nshahan - let's discuss this on today's sync up.

I'm currently wondering:
* should we consider it a blocker for unforking, or a bug we can fix afterwards?
* do we want to keep this feature? I wonder if the value provided justifies the extra complexity.

**Comment by sigmundch** [comment]
Nick landed the fix in a5704eaca39b2d28fec0e1f26d9b808743f74c68

**Comment by nshahan** [comment]
I'm going to reopen this issue because it is more about the text of the error messages we generate, not the type of the exception thrown. We still need to evaluate how the messages could be more helpful when a complicated generic function type check fails. The change that landed fixed https://github.com/dart-lang/sdk/issues/41008.

**Comment by sigmundch** [comment]
Oh - sorry, I misread the issue title and assumed this was #41008 

Do you feel OK changing this to a different epic (basically treating it as a non-blocker for unfork?)

**Comment by nshahan** [comment]
Yeah non-blocking, but I think a blocker should be to disable the feature since we have no idea how it will be recommending users to change the type on a failure. I'll send a CL to turn it off with a TODO pointed here to figure this out or delete if we no longer want this code.

**Comment by nshahan** [comment]
I haven't seen any sign that this feature has been missed and I don't intend to revive it. IIUC this was most useful during the migration from Dart 1 to Dart 2.
