### ISSUE TITLE
Expose Elf/Reader classes from package:native_stack_traces

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#40327]
It would be nice If I could instantiate a Dwarf object without relying on the physical file system. For example, to support taking the stack trace over stdin.

To that end, it would be nice if package:native_stack_traces either exposed the Elf/Reader classes via the public API, or supported a similar `Dwarf.fromBuffer` API that accept bytes directly.

cc @sstrickl

**Comment by jonahwilliams** [comment]
Actually, a better example would be in the flutter tool we use filesystem wrappers for testing purposes. Since the dwarf constructor requires a string path, it's not possible to integrate with these wrappers

**Comment by sstrickl** [comment]
Forgot to mention the bug in the CL that adds `Dwarf.fromBytes`, commit 2b27386. Released package version 0.2.2 on Friday, which includes this fix and another cleanup.

**Comment by jonahwilliams** [comment]
Awesome, thank you!
