### ISSUE TITLE
NNBD Wrong or no error for different type getter/setter with the same basename

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40333]
NNBD [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> It is an error if a class has a setter and a getter with the same basename where the return type of the getter is not a subtype of the argument type of the setter. Note that this error specifically requires subtyping and not assignability and hence makes no exception for dynamic.

In fact analyzer finds no issues in the code below

```dart
class C {
  void set test(int v) {}
  dynamic get test => 3.14;
}

main() {
  C c = new C();
  c.test = 1;
  c.test;
}
```
In the case when we do have an error, error message is wrong
```dart
class C {
  void set test(int v) {}
  num get test => 3.14;
}

main() {
  C c = new C();
  c.test = 1;
  c.test;
}
```
Here we have `error - The return type of getter 'test' is 'num' which isn't assignable to the type 'int' of its setter 'test'.`

But NNBD spec clearly says about 'subtyping', not about 'assignability'

Tested on `dartanalyzer version 2.8.0-dev.5.0`

**Comment by scheglov** [comment]
Thank you for the report.
Yes, checking for types of getters / setters is not right for NNBD.

https://dart-review.googlesource.com/c/sdk/+/133640 is a first step to fix it, using subtyping and a better error message.

For the first example analyzer was reporting an error in NNBD libraries, with the bleeding edge version. I don't remember fixing it, but maybe this happened accidentally.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/133665
