### ISSUE TITLE
CFE: Specify override inference special casing for operator == in legacy libraries

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40334]
This is the CFE issue for https://github.com/dart-lang/language/issues/569

**Comment by a-siva** [comment]
I am not sure if this is really fixed. I synched up to top of tree and tried this with the NNBD platform file that we are building on this test case and I still see the error
```
class Assumptions {
  @override
  String toString() {
    return "Assumptions";
  }
  bool operator ==(other) {
    return (kind == other.kind);
  }
  int kind;
}
main() {
  var a = Assumptions();
  print(a);
}

/usr/local/google/home/asiva/workspace/dart-nnbd/sdk/tools/sdks/dart-sdk/bin/dart --dfe=/usr/local/google/home/asiva/workspace/dart-nnbd/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /usr/local/google/home/asiva/workspace/dart-nnbd/sdk/pkg/vm/bin/gen_kernel.dart --platform=/usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64NNBD/vm_platform_strong.dill --no-link-platform /tmp/junk1.dart

/tmp/junk1.dart:7:27: Error: The getter 'kind' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kind'.
    return (kind == other.kind);
                          ^^^^
```

**Comment by johnniwinther** [comment]
Can you point me to a (WIP) CL that triggers this? (Since no implementation of sdk_nnbd currently uses the new parameter type in the patch, the fix is (only) tested in a mock sdk setting)

**Comment by johnniwinther** [comment]
I've got a local repro. Looking into it.

**Comment by johnniwinther** [comment]
Hmm. I can only trigger this when the user-code library is not opted out (in which case it is correct to complain). Maybe something is going wrong with the opt-in/out status in your case.

**Comment by johnniwinther** [comment]
I've found the bug. The problem is incorrect handling of the platform being opted in to nnbd even though the experimental flag is not set.

**Comment by a-siva** [comment]
Ok cool, thanks for taking the time to investigate.

**Comment by johnniwinther** [comment]
https://dart-review.googlesource.com/c/sdk/+/133780 is in the pipeline
