### ISSUE TITLE
request for a mirror for dart-lang/stagehand

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#40343]
Hi, I'd like a mirror for the https://github.com/dart-lang/stagehand repository (so that I can add it to the sdk DEPS file - CL in progress here: https://dart-review.googlesource.com/c/sdk/+/133460). Thanks!

**Comment by devoncarew** [comment]
cc @athomas, @whesse

**Comment by athomas** [comment]
Done: https://dart.googlesource.com/stagehand

**Comment by devoncarew** [comment]
Thanks!
