### ISSUE TITLE
String is ParameterizedType? (in analyzer-0.39.4)

### ISSUE THREAD

**Issue by nikeorever** [dart-lang/sdk#40345]

**Comment by a-siva** [comment]
Can you add some description about what the problem you have encountered. the title seems pretty cryptic.

**Comment by nikeorever** [comment]
> Can you add some description about what the problem you have encountered. the title seems pretty cryptic.

Sorry for this vague question，I want to determine if a DartType is a generic type，The code looks like this:`if (dartType is ParameterizedType) return true else return false`, But when dataType is String type, true will return, The same goes for int types，I use analyzer's api．

**Comment by nikeorever** [comment]
So i had to do this:
`static bool isParameterizedType(DartType dartType) {
    if (dartType is ParameterizedType) {
      final typeArgs = dartType.typeArguments;
      return typeArgs != null && typeArgs.isNotEmpty;
    }
    return false;
  }`

**Comment by nikeorever** [comment]
So i had to do this:
`
static bool isParameterizedType(DartType dartType) {
    if (dartType is ParameterizedType) {
      final typeArgs = dartType.typeArguments;
      return typeArgs != null && typeArgs.isNotEmpty;
    }
    return false;
  }

`

**Comment by nikeorever** [comment]
Looking forward to your answer，Thanks.

**Comment by srawlins** [comment]
The issue tracker is not the proper place for questions. Please use the analyzer's mailing list: analyzer-discuss@dartlang.org
