### ISSUE TITLE
'We're sorry, you've found a bug in our compiler.'

### ISSUE THREAD

**Issue by chrisunl** [dart-lang/sdk#40359]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dev_compiler

Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel
    --dart-sdk-summary=/Users/morrisc1/Dev/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc
    _sdk.dill --modules=amd --no-summarize -o
    packages/stock_app_flutter/main_web_entrypoint.ddc.js --source-map
    --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/found
    ation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/phy
    sics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zi
    p
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_
    queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canoni
    calized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/pa
    inting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/bi
    nding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/
    animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/render
    ing/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/action
    s --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cuperti
    no/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino
    --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --summary=packages/scoped_model/scoped_model.ddc.dill=packages/scoped_model/scoped_model
    --summary=packages/flutter_view_widgets/flutter_view_widgets.ddc.dill=packages/flutter_view
    _widgets/flutter_view_widgets
    --summary=packages/flutter_dotenv/flutter_dotenv.ddc.dill=packages/flutter_dotenv/flutter_d
    otenv
    --summary=packages/stock_app_flutter/model/stock-data.ddc.dill=packages/stock_app_flutter/m
    odel/stock-data
    --summary=packages/shared_preferences_platform_interface/method_channel_shared_preferences.
    ddc.dill=packages/shared_preferences_platform_interface/method_channel_shared_preferences
    --summary=packages/shared_preferences/shared_preferences.ddc.dill=packages/shared_preferenc
    es/shared_preferences
    --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic
    --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii
    --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity
    --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode
    --summary=packages/path/path.ddc.dill=packages/path/path
    --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/sr
    c/generated/ascii_glyph_set
    --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span
    --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/s
    rc/eager_span_scanner
    --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data
    --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser
    --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client
    --summary=packages/http/http.ddc.dill=packages/http/http
    --summary=packages/stock_app_flutter/main.ddc.dill=packages/stock_app_flutter/main
    --summary=packages/flutter_web_plugins/flutter_web_plugins.ddc.dill=packages/flutter_web_pl
    ugins/flutter_web_plugins
    --summary=packages/shared_preferences_web/shared_preferences_web.ddc.dill=packages/shared_p
    references_web/shared_preferences_web
    --summary=packages/stock_app_flutter/generated_plugin_registrant.ddc.dill=packages/stock_ap
    p_flutter/generated_plugin_registrant
    --packages=file:///var/folders/f_/6b15k4nx6871z6b27brdgj05s8sc4p/T/kernel_builder_DLWemM/.p
    ackages --module-name=packages/stock_app_flutter/main_web_entrypoint
    --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map
    --libraries-file=file:///Users/morrisc1/Dev/flutter/bin/cache/flutter_web_sdk/libraries.jso
    n
    --used-inputs-file=/var/folders/f_/6b15k4nx6871z6b27brdgj05s8sc4p/T/ddk_builder_K7x1U5/used
    _inputs.txt package:stock_app_flutter/main_web_entrypoint.dart
    dart --version: 2.8.0-dev.0.0.flutter-c547f5d933 (Fri Dec 27 00:43:14 2019 +0000) on
    "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure>
(package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent
(package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler
(package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure>
(package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by natebosch** [comment]
Can you check what version of `package:scratch_space` you have? `pub deps` should be able to tell you.

cc @jakemac53

**Comment by chrisunl** [comment]
Hi

flutter pub deps gives me:

flutter pub deps --verbose
[  +21 ms] executing: [/Users/morrisc1/Dev/flutter/]
git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +34 ms] Exit code 0 from: git -c
log.showSignature=false log -n 1 --pretty=format:%H
[        ] 659dc8129d4edb9166e9a0d600439d135740933f
[        ] executing: [/Users/morrisc1/Dev/flutter/]
git describe --match v*.*.* --first-parent --long
--tags
[  +10 ms] Exit code 0 from: git describe --match
v*.*.* --first-parent --long --tags
[        ] v1.13.6-0-g659dc8129
[   +9 ms] executing: [/Users/morrisc1/Dev/flutter/]
git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse
--abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [/Users/morrisc1/Dev/flutter/]
git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url
origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/Users/morrisc1/Dev/flutter/]
git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse
--abbrev-ref HEAD
[        ] beta
[   +6 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G3020
[  +28 ms] Artifact Instance of
'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts'
is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is
not required, skipping update.
[   +3 ms] Artifact Instance of
'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'MaterialFonts' is
not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is
not required, skipping update.
[        ] Artifact Instance of
'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts'
is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is
not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not
required, skipping update.
[        ] Artifact Instance of
'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is
not required, skipping update.
[  +37 ms] Using
/Users/morrisc1/Dev/flutter/.pub-cache for the pub
cache.
[        ] executing:
/Users/morrisc1/Dev/flutter/bin/cache/dart-sdk/bin/pu
b deps
Dart SDK 2.8.0-dev.0.0.flutter-c547f5d933
Flutter SDK 1.13.6
stock_app_flutter 1.0.0+1
|-- charts_flutter 0.8.1
|   |-- charts_common 0.8.1
|   |   |-- collection...
|   |   |-- intl...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- vector_math...
|   |-- collection...
|   |-- flutter...
|   |-- intl 0.16.1
|   |   '-- path...
|   |-- logging 0.11.4
|   '-- meta...
|-- cupertino_icons 0.1.3
|-- flutter 0.0.0
|   |-- collection 1.14.11
|   |-- meta 1.1.8
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.1.6
|   '-- vector_math 2.0.8
|-- flutter_dotenv 2.1.0
|   |-- flutter...
|   '-- meta...
|-- flutter_test 0.0.0
|   |-- archive 2.0.11
|   |   |-- args...
|   |   |-- crypto...
|   |   '-- path...
|   |-- args 1.5.2
|   |-- async...
|   |-- boolean_selector 1.0.5
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- charcode 1.1.2
|   |-- collection...
|   |-- convert 2.1.1
|   |   |-- charcode...
|   |   '-- typed_data...
|   |-- crypto 2.1.3
|   |   |-- collection...
|   |   |-- convert...
|   |   '-- typed_data...
|   |-- flutter...
|   |-- image 2.1.4
|   |   |-- archive...
|   |   '-- xml...
|   |-- matcher 0.12.6
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path...
|   |-- pedantic...
|   |-- petitparser 2.4.0
|   |   '-- meta...
|   |-- quiver 2.0.5
|   |   |-- matcher...
|   |   '-- meta...
|   |-- source_span 1.5.5
|   |   |-- charcode...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.9.3
|   |   '-- path...
|   |-- stream_channel 2.0.0
|   |   '-- async...
|   |-- string_scanner 1.0.5
|   |   |-- charcode...
|   |   |-- meta...
|   |   '-- source_span...
|   |-- term_glyph 1.1.0
|   |-- test_api 0.2.11
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   |-- vector_math...
|   '-- xml 3.5.0
|       |-- collection...
|       |-- convert...
|       '-- petitparser...
|-- flutter_view_widgets 1.0.6
|   |-- flutter...
|   '-- scoped_model 1.0.1
|       '-- flutter...
|-- http 0.12.0+2
|   |-- async 2.4.0
|   |   '-- collection...
|   |-- http_parser 3.1.3
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- source_span...
|   |   |-- string_scanner...
|   |   '-- typed_data...
|   |-- path 1.6.4
|   '-- pedantic 1.8.0+1
'-- shared_preferences 0.5.6+1
    |-- flutter...
    |-- meta...
    |-- shared_preferences_macos 0.0.1+4
    |   |-- flutter...
    |   '-- shared_preferences_platform_interface...
    |-- shared_preferences_platform_interface 1.0.1
    |   |-- flutter...
    |   '-- meta...
    '-- shared_preferences_web 0.1.2+3
        |-- flutter...
        |-- flutter_web_plugins 0.0.0
        |   |-- collection...
        |   |-- flutter...
        |   |-- meta...
        |   |-- typed_data...
        |   '-- vector_math...
        |-- meta...
        '-- shared_preferences_platform_interface...
[ +265 ms] "flutter deps" took 425ms.

although I don't see scratch_space there :-/

In any case I did flutter clean and no longer have the problem so I don't think I have the relevant state anymore

**Comment by jakemac53** [comment]
Oh right - in flutter this is a dependency of flutter_tool and not the main package.

I suppose the way to find the scratch_space version would be to look at the flutter version and what version of scratch_space that had pinned.

So in this case flutter was `1.13.6` - hopefully they tag releases on the repo :).

**Comment by jakemac53** [comment]
It looks like scratch_space 0.0.4+1 - which doesn't include the fix https://github.com/flutter/flutter/blob/41a911099b7d06f7b1c29f4420cfcfe41fd26e46/packages/flutter_tools/pubspec.yaml.

**Comment by jakemac53** [comment]
It looks like this was updated here https://github.com/flutter/flutter/commit/c3f590a8725ecbac5b018d43aae53210ddb0578b, which first made it into flutter `1.13.8`.

Can you update to that flutter version?

**Comment by vsmenon** [comment]
Merging to https://github.com/dart-lang/sdk/issues/38102
