### ISSUE TITLE
Migration tool should assign typedef params to their bounds

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40358]
```dart
typdef F<T extends num> // 1
  = Function(T/*!*/); // 2

F<int> f; // 3
f(null); // 4
```

With the assignment at `4`, the type parameter at `3` should be marked nullable since parameter at `2` is non-nullable. This should result in the bound at `1` being marked nullable.

This example works except for `1` being marked nullable, because we don't assign typedef params to their bounds yet.

**Comment by srawlins** [comment]
I think this example runs exactly the same. Everything looks good except `// 1`:

```dart
typedef F<T extends num> // 1
  = Function(T); // 2

late F<int?> f; // 3

g() {
  f(null); // 4
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
