### ISSUE TITLE
NNBD No type promotion for operators

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40369]
Consider the following code. There are two errors in the analyzer here
```dart
class C {
  List<int>? _list = [3, 1, 4];
  int operator [](int index) => _list != null ? _list[index] : -1; // error - The expression is nullable and must be null-checked before it can be used
  void operator []=(int index, dynamic value) {
    if (_list != null) {
      _list[index] = value; // error - The expression is nullable and must be null-checked before it can be used
    }
  }
}

main() {
}
```
In both cases _list is null-checked so there must be no error
Tested on `dartanalyzer version 2.8.0-dev.5.0 `

**Comment by eernstg** [comment]
We can't actually promote `_list`: It is an instance variable. The standard example why this wouldn't work safely is that a subclass of `C` could override the `_list` getter, and the overriding implementation could return a different list each time, so we wouldn't be able to trust the next occurrence of `_list` to have a specific type `T`, even if we just tested that `_list` was indeed a `T`. So this is working as intended.
