### ISSUE TITLE
DDC Error reading of static variable during its initialization

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40375]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables) reads

> A toplevel or static variable with an initializer is evaluated as if it was marked late. Note that this is a change from pre-NNBD semantics in that:
> 
> Throwing an exception during initializer evaluation no longer sets the variable to null
> Reading the variable during initializer evaluation is no longer checked for, and does not cause an error.

But for DDCcompiler it is still an error (see https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/1641/co19/LanguageFeatures/nnbd/late_A08_t06)
Test that fails
```dart
import "../../Utils/expect.dart";

const MAX = 10;
int counter = 0;

class C {
  static String? s = initS();
  static String? initS() {
    if (++counter > MAX) {
      return "result $counter";
    }
    return s;
  }
}

String? g = initG();
String? initG() {
  if (++counter > MAX) {
    return "result $counter";
  }
  return g;
}

main() {
  Expect.equals("result 11", C.s); // Runtime error: Error: Reading static variable 's' during its initialization
  counter = 0;
  Expect.equals("result 11", g);
}

```

Tested on SDK version 2.8.0-dev.6.0

**Comment by franklinyow** [comment]
Any update on the issue?  Thx!

**Comment by sigmundch** [comment]
@Markzipan - I recall you were looking at implementing this, but I can't remember where we ended up.

**Comment by sigmundch** [comment]
I just realized that this is not necessary for the unfork, so I moved it to a separate epic
