### ISSUE TITLE
Don't include unnecessary "<Widget>" in Flutter quick fix

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40378]
I believe this is coming from analysis server but, I'm not exactly sure. I only see the end result in Dart code. There are one or more quick fixes that help users generate Flutter code. Some of those create a list literal for lists of children widgets. When they do, they explicitly provide a type argument on the list:

```dart
<Widget>[ ... ]
```

This isn't needed since the list is in a context where type inference knows it should be a List<Widget>. Putting the redundant type argument there goes against [our guidance in "Effective Dart"](https://dart.dev/guides/language/effective-dart/design#avoid-redundant-type-arguments-on-generic-invocations).

Can we tweak the quick fixes to not insert this?

**Comment by bwilkerson** [comment]
Yes, I'm fairly sure it comes from server, and yes, we can fix it.

**Comment by pq** [comment]
I did a round-up and this should be fixed w/ ca3c83b65467e849f2d69dcba6ae7278025315c6.

If I missed any, please re-open! 👍
