### ISSUE TITLE
NNBD Migration should flag inserted casts that may newly fail

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40385]
Follow-up task of #38707.

Some inserted casts should be added because they make sense and they allow the tool to produce a (statically) valid migration result.

However, they should be flagged as places that need manual review, as they may look like simple implicit downcasts, rather than introduction of new places where a cast may fail.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
