### ISSUE TITLE
DDC generated code is slow to start up in Safari

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40380]
Initial startup of DDC apps is relatively slow in Safari, particularly for Flutter Web.

The root cause appears to be a perf bug / lack of optimization in Safari's JSC:

https://bugs.webkit.org/show_bug.cgi?id=199866

We may consider working around this in DDC by using `var` instead of `let` or `const` as suggested on the above.

**Comment by sigmundch** [comment]
How many of these declarations are top-level on the module?

I wonder if this will improve once we land the change to hoist variables, which @Markzipan is looking into in order to improve stepping in the debugger.

**Comment by vsmenon** [comment]
( @RedBrogdon )

I think we can close this one if you prefer.  Using `var` fixed / sidestepped the issue (see the webkit bug).  

We could restore `let` / `const` at some point, but I don't know if we still need this issue.

**Comment by sigmundch** [comment]
thanks
