### ISSUE TITLE
nnbd tool should create casts for function types

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40384]
In package:async, there are some compile errors from lazy test nulls combined with migrated async apis.

```dart
...
// in tests
onCancel = () => null;
...
CancelableOperation(..., Future<R> Function() onCancel: onCancel) ...
...
... Completer.complete(Future.sync(onCancel)) ...
```

the null causes the type of `onCancel` to be `Future<R>? Function()`. That is an illegal assignment to the parameter of `Future.sync` (`Future<T> Function()`).

Ultimately, the correct migration is probably to change the test to

```dart
onCancel = () async => null;
```

but in terms of an output we can expect the migration tool to produce, we can emit a cast when passed into `Future.sync`:

```dart
...
... Completer.complete(Future.sync(onCancel as Future<R> Function())) ...
```

In the long run, this ideally will be highlighted as a place users should manually review

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
