### ISSUE TITLE
Migration tool should consider supporting 'implicit-downcasts: false' users

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40383]
Some packages (such as package:async) have in their analysis_options.yaml

```yaml
analyzer:
  strong-mode:
    implicit-downcasts: false
```

It would seem like this is not relevant to the migration tool, because we will insert implicit downcasts for users. However, for two reasons this is not the case:

- implicit downcasts from dynamic are allowed in nnbd, but not with the flag
- with nullability, some relatives of dynamic may be migrated to subtypes

Ex:

```dart
dynamic d = 0;
Object o = d;
```

The migration for this introduces no changes. Which is a problem if you have `implicit-downcasts: false`, because

```
Object o = d;
```

is a downcast from dynamic in nnbd world. Which is accepted by default, but not accepted for projects with `implicit-downcasts: false`.

I think there are two solutions here:
- detect this and insert casts `as Object`
- (I suggest) removing the config from analysis_options

I suggest the latter because casts from dynamic were deliberately disabled because they are annoying and unlikely to be accidents. However, we may want to survey authors of these packages to check this :)

Its worth noting that there is a workaround: users can insert `as Object` into the code. It does not seem to get flagged as an unnecessary cast.

**Comment by stereotype441** [comment]
Note that @yjbanov brought this up in his meeting with the migration team on Aug 28.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
