### ISSUE TITLE
NNBD: Dart crashes when field of the type Null overrides Never field in legacy code.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40387]
Dart VM version: 2.8.0-edge.40f23c735f04433e4fc334fbd674474bd3de0f8b (Tue Jan 28 01:14:48 2020 +0000) on "linux_x64"

The following code declares a `Null` field of class `B` which field which overrides `Never` field of class `A` in the legacy code:
``` dart
// @dart=2.6

class A {
  Never n = throw "Should not reach here";
}

class B extends A {
  Null n = null;
}

main() {}
```
According to the NNBD Spec above it should pass because `Never` type should be should be treated as `Null`:
> Legacy libraries
> Static checking for a library which has not opted into this feature (a legacy library) is done using the semantics as of the last version of the language before this feature ships (or the last version to which it has opted in, if that is different). All opted-in libraries upstream from the legacy library are viewed by the legacy library with nullability related features erased from their APIs. In particular:
> 
> All types of the form T? in the opted-in API are treated as T.
> All required named parameters are treated as optional named parameters.
> The type Never is treated as the type Null
> In a legacy library, none of the new syntax introduced by this proposal is available, and it is a static error if it is used.

However it crashes, sample output is:

> $ dart --enable-experiment=non-nullable test.dart
> Crash when compiling null,
> at character offset null:
> Bad state: Unexpected nullability 'Never*.nullability' of type Never
> #0      IsNeverTypeSubtypeOf.isInterfaceRelated (package:front_end/src/fasta/kernel/types.dart:895:7)
> #1      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:214:25)
> #2      Types.isSubtypeOfKernel (package:front_end/src/fasta/kernel/types.dart:44:26)
> #3      ClassBuilderImpl._checkTypes (package:front_end/src/fasta/builder/class_builder.dart:1171:15)
> #4      ClassBuilderImpl.checkGetterOverride (package:front_end/src/fasta/builder/class_builder.dart:1407:5)
> #5      ClassBuilderImpl.checkOverride (package:front_end/src/fasta/builder/class_builder.dart:987:9)
> #6      DelayedOverrideCheck.check.callback (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2234:20)
> #7      DelayedOverrideCheck.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2336:13)
> #8      SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:979:25)
> #9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:304:14)
> <asynchronous suspension>
> #10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #11     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:277:12)
> #12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
> <asynchronous suspension>
> #13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
> #15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
> #16     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #18     new Future.sync (dart:async/future.dart:224:31)
> #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #20     _rootRun (dart:async/zone.dart:1126:13)
> #21     _CustomZone.run (dart:async/zone.dart:1023:19)
> #22     _runZoned (dart:async/zone.dart:1518:10)
> #23     runZoned (dart:async/zone.dart:1465:12)
> #24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #26     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
> #27     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
> #28     SingleShotCompilerWrapper.compileInternal (file:///home/iarkh/dart/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:359:17)
> #29     Compiler.compile.<anonymous closure> (file:///home/iarkh/dart/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:163:45)
> #30     new Future.<anonymous closure> (dart:async/future.dart:176:37)
> #31     _rootRun (dart:async/zone.dart:1122:38)
> #32     _CustomZone.run (dart:async/zone.dart:1023:19)
> #33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
> #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
> #35     _rootRun (dart:async/zone.dart:1126:13)
> #36     _CustomZone.run (dart:async/zone.dart:1023:19)
> #37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
> #38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> #39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
> #40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
> #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
> 
> 
> #0      IsNeverTypeSubtypeOf.isInterfaceRelated (package:front_end/src/fasta/kernel/types.dart:895:7)
> #1      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:214:25)
> #2      Types.isSubtypeOfKernel (package:front_end/src/fasta/kernel/types.dart:44:26)
> #3      ClassBuilderImpl._checkTypes (package:front_end/src/fasta/builder/class_builder.dart:1171:15)
> #4      ClassBuilderImpl.checkGetterOverride (package:front_end/src/fasta/builder/class_builder.dart:1407:5)
> #5      ClassBuilderImpl.checkOverride (package:front_end/src/fasta/builder/class_builder.dart:987:9)
> #6      DelayedOverrideCheck.check.callback (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2234:20)
> #7      DelayedOverrideCheck.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2336:13)
> #8      SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:979:25)
> #9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:304:14)
> <asynchronous suspension>
> #10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #11     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:277:12)
> #12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
> <asynchronous suspension>
> #13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
> #15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
> #16     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #18     new Future.sync (dart:async/future.dart:224:31)
> #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #20     _rootRun (dart:async/zone.dart:1126:13)
> #21     _CustomZone.run (dart:async/zone.dart:1023:19)
> #22     _runZoned (dart:async/zone.dart:1518:10)
> #23     runZoned (dart:async/zone.dart:1465:12)
> #24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #26     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
> #27     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
> #28     SingleShotCompilerWrapper.compileInternal (file:///home/iarkh/dart/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:359:17)
> #29     Compiler.compile.<anonymous closure> (file:///home/iarkh/dart/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:163:45)
> #30     new Future.<anonymous closure> (dart:async/future.dart:176:37)
> #31     _rootRun (dart:async/zone.dart:1122:38)
> #32     _CustomZone.run (dart:async/zone.dart:1023:19)
> #33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
> #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
> #35     _rootRun (dart:async/zone.dart:1126:13)
> #36     _CustomZone.run (dart:async/zone.dart:1023:19)
> #37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
> #38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> #39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
> #40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
> #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)

Please see also Issue #39917: its evaluation reads that `Never` is a separate type in the dart. 
So, should the source above pass or throw compile error?

**Comment by alexmarkov** [comment]
The crash comes from front-end.
/cc @johnniwinther
