### ISSUE TITLE
Is there a way to find all subtypes for a `ClassElement`?

### ISSUE THREAD

**Issue by atreeon** [dart-lang/sdk#40386]
The `ClassElement` has the property `allSupertypes`, is there a way to go the other way and find all subtypes for a `ClassElement`?

I would like this for code generation purposes.

_Using dart 2.6.1 and source_gen 0.9.4+7_

**Comment by bwilkerson** [comment]
We have support for that, but it isn't part of the public API. In part, because the information we have about subclasses is necessarily incomplete.

**Comment by atreeon** [comment]
ah, that is a shame!  no worries but if you think of something that might help that would be great.

**Comment by srawlins** [comment]
I'll close this as resolved. In the future, questions can be directed to analyzer-discuss@dartlang.org.
