### ISSUE TITLE
NNBD. No error if the body of a method, function, getter, or  function expression with a potentially non-nullable return type may complete normally

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40396]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> It is an error if the body of a method, function, getter, or function expression with a potentially non-nullable return type may completely normally.

In fact there are no any error. Example

```dart
class A {}

class C {
  static A sTest() {}

  A mTest() {}

  A get gTest {}
}

A test() {}

main() {
  C.sTest();
  C c = new C();
  c.mTest();
  c.gTest;
  test();
}
```
Tested on `dartanalyzer version 2.8.0-dev.6.0 `

**Comment by eernstg** [comment]
It might be helpful to note that the expected errors are on the declarations of `sTest`, `mTest`, `gTest`, and `test`, because each of them has the body `{}` which may (indeed will) complete normally, and each of them returns `A`, which is a potentially non-nullable type.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135582
