### ISSUE TITLE
NNBD. Error instead of warning for enum and switch with not all cases

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40395]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> If T is an enum type, it is a warning if the switch does not handle all enum cases, either explicitly or via a default.

In fact, it is an error instead of warning

```dart
enum E {
  one,
  two,
  three
}
main() {
  E e = E.three;
  switch (e) { // error - Missing case clause for 'three'
    case E.one:
      true;
      break;
    case E.two:
      false;
      break;
  }
}
```
Tested on `dartanalyzer version 2.8.0-dev.6.0 `

**Comment by scheglov** [comment]
This was fixed as https://github.com/dart-lang/sdk/issues/40547
