### ISSUE TITLE
NNBD. New rules for switch are not implemented

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40392]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> It is an error if any case of a switch statement except the last case (the default case if present) may complete normally. The previous syntactic restriction requiring the last statement of each case to be one of an enumerated list of statements (break, continue, return, throw, or rethrow) is removed.

This means that the following code must be allowed now (in fact - not in both anlyzer and VM)

```dart
Never willThrow() => throw "Lily was here";

main() {
  int i = 42;
  switch (i) {
    case 1: willThrow();
    case 2:
    case 42: willThrow();
    default: false;
  }
}
```
Tested on SDK version 2.8.0-dev.6.0

**Comment by alexmarkov** [comment]
In case of VM it fails due to a compile-time error which comes from front-end.
/cc @johnniwinther

**Comment by johnniwinther** [comment]
Filed https://github.com/dart-lang/sdk/issues/40425 for CFE

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/134245
