### ISSUE TITLE
NNBD: Analyzer does not ignore non-nullability of the type parameter in the legacy code.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40398]
Dart VM version: 2.8.0-edge.40f23c735f04433e4fc334fbd674474bd3de0f8b (Tue Jan 28 01:14:48 2020 +0000) on "linux_x64"

According to NNBD Spec:
> The legacy erasure of a type T denoted LEGACY_ERASURE(T) is T with all occurrences of ? removed, Never replaced with Null, required removed from all parameters, and all types marked as legacy types.

The following code passes with dart and throws a compile error with analyzer:
``` dart
// testlib.dart: nnbd
library testlib;
class A<X extends int> {}
```
``` dart
// test.dart: legacy code
// @dart=2.6
import "testlib.dart";
class A1<T extends Null> extends A<T> {}
void main() {}
```
According to the Spec, the fact that A type parameter is non-nullable should be ignored.
This is so in runtime, and this does not work with analyzer.
Sample output is:
> $ dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error • 'T' doesn't extend 'int'. • test.dart:4:36 • type_argument_not_matching_bounds
> 1 error found.
> $ dart --enable-experiment=non-nullable test.dart
> $

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135202
