### ISSUE TITLE
NNBD. Allow different types for 'switch'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40393]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> Given a switch statement which switches over an expression e of type T, where the cases are dispatched based on expressions _e<sub>0</sub>...e<sub>k</sub>_:
> 
> It is no longer required that the _e<sub>i</sub>_ evaluate to instances of the same class.

That means that the following code must work (doesn't work in fact)

```dart
void foo() {}

main() {
  num i = 42;
  switch (i) {
    case 1: true;
      break;
    case 3.14: foo();
      break;
    case 42: false;
  }
}
```
Tested on SDK version 2.8.0-dev.6.0

**Comment by a-siva** [comment]
I tried running this test using the bleeding edge dart and it works just fine.

**Comment by a-siva** [comment]
closing as fixed, please reopen if you disagree.
