### ISSUE TITLE
Please provide mmap related api

### ISSUE THREAD

**Issue by hackwaly** [dart-lang/sdk#40403]
I need mmap related api. Something hard to do without that.

Perhaps best place them in `dart:io` package.

**Comment by lrhn** [comment]
Sounds like something that would be related to dart:ffi.

**Comment by mkustermann** [comment]
Correct, with`dart:ffi` you can use `mmap`.

We have already some testing code which uses `mmap`, see [vmspecific_highmem_32bit_test.dart](https://github.com/dart-lang/sdk/blob/master/tests/ffi/vmspecific_highmem_32bit_test.dart#L93).

The only caveat atm is that if libc calls fail, there's no access to the failure reason via `errno` atm: There's an open issue for it https://github.com/dart-lang/sdk/issues/38832

**Comment by mkustermann** [comment]
@hackwaly As mentioned above, it's already possible now to lookup `mmap` in libc and call it. We do not plan on adding this to any of our `dart:*` at this point in time. The only issue is not being able to retrieve `errno` for possible retries - this is already tracked at https://github.com/dart-lang/sdk/issues/38832.

So I hope it's ok if I close this issue.
