### ISSUE TITLE
Failed to retrieve stack bounds error when running on Debian Linux

### ISSUE THREAD

**Issue by Ephenodrom** [dart-lang/sdk#40405]
Hello,

I am trying to run Dart on a managed hosting server which normally only works with PHP. Since it is possible to execute scripts on the command line i thought I should try out to execute a dart programm.

But I ended up facing this issue :
```
/httpdocs/tmp/bin/dart /httpdocs/testproject/bin/main.dart 
../../runtime/vm/os_thread.cc: 47: error: Failed to retrieve stack bounds
```

Any idea if this is a bug from the dart SDK or a problem with my hosting server which has limited access to certain things.

Regards

Hints : 
- The Debian version : Linux a2f9b 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1+deb9u2~deb8u1 (2019-05-14) x86_64 GNU/Linux
- The Dart Version : 2.7.1
- This is the code part from the mentioned file that throws the error : 
```cc
// Try to get accurate stack bounds from pthreads, etc.
  if (!GetCurrentStackBounds(&stack_limit_, &stack_base_)) {
    FATAL("Failed to retrieve stack bounds");
  }
```
- This looks like the implementation ( No idea what this lines of code do ), taken from the file os_thread_linux.cc  : 
```cc
bool OSThread::GetCurrentStackBounds(uword* lower, uword* upper) {
  pthread_attr_t attr;
  // May fail on the main thread.
  if (pthread_getattr_np(pthread_self(), &attr) != 0) {
    return false;
  }

  void* base;
  size_t size;
  int error = pthread_attr_getstack(&attr, &base, &size);
  pthread_attr_destroy(&attr);
  if (error != 0) {
    return false;
  }

  *lower = reinterpret_cast<uword>(base);
  *upper = *lower + size;
  return true;
}
```
- When i only run the dart sdk without giving a dart file as a parameter, the usage information appears : 
```
/httpdocs/tmp/bin/dart
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.
...
```

**Comment by rmacnak-google** [comment]
Can you try to run `cat /proc/self/maps`? This might be failing because pthreads is unable to access this file in your environment.

**Comment by Ephenodrom** [comment]
Hello @rmacnak-google 

Thanks for the quick reply. Unfortunately there is no file at **/proc/self/maps** neither does the folder **/proc** exist. Therefore the problem seems to come from the limited access my **user** has on the remote machine.

**Comment by pzillmann** [comment]
User tries to execute his code inside a webhosting environment (Plesk) - which isn't fully POSIX conform nor resembles a full Debian Linux.

See https://forum.netcup.de/netcup-intern/technik/12301-dart-auf-webhosting4000-ausf%C3%BChren/ (in German)

**Comment by Ephenodrom** [comment]
The problem appears due to the limitation of the hosting system. This is not a bug of the SDK.
