### ISSUE TITLE
[garden] unreachable nodes in aot snapshot

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/sdk#40404]
failures in bot:

https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-obfuscate-linux-release-x64/6039

https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-android-release-arm_x64/957

Heap snapshot contains 1123 unreachable nodes.
internal-garbage: 400624
external-garbage: 0
fragmentation: 2868544
** Killing script
Unexpected exception in service tests: Bad state: No element
#0      la.wv (nOa:628)
#1      zR.<anonymous closure>.AAa (iKa:130)
#2      zR.<anonymous closure> (iKa:133)
<asynchronous suspension>
#3      _ih.LG.<anonymous closure>.<anonymous closure> (kKa:373)
<asynchronous suspension>
#4      _mu (vLa:1134)
#5      _cc.MG (vLa:1031)
#6      _FutureListener.kH (pLa:140)
#7      Future._eJ.tya (pLa:682)
#8      Future._eJ (pLa:711)
#9      Future._aJ (pLa:526)
#10     Future._bJ.<anonymous closure> (pLa:556)
#11     _lu (vLa:1126)
#12     _cc.LG (vLa:1023)
#13     _cc.BG (vLa:925)
#14     _cc.GG.<anonymous closure> (vLa:965)
#15     _Tt (qLa:43)
#16     _Ut (qLa:52)
#17     _runPendingImmediateCallback (CMa:118)
#18     _RawReceivePortImpl._handleMessage (CMa:169)

**Comment by mkustermann** [comment]
Can this be closed?

**Comment by ZichangG** [comment]
I didn't track what happened after. You can close it if problems are solved. :)
