### ISSUE TITLE
Completion not showing top level functions

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40417]
The `http` library has a `put` method, but it doesn't show up on the completion window:

![image](https://user-images.githubusercontent.com/1146982/73552599-475e5800-4427-11ea-9ab1-7f918a71ffa3.png)

If I scroll down the entire completion window, the `put` method is not even there.
This is the same for other methods:

![image](https://user-images.githubusercontent.com/1146982/73552744-8db3b700-4427-11ea-8464-8816838649f3.png)
![image](https://user-images.githubusercontent.com/1146982/73552811-a9b75880-4427-11ea-823c-36514453e420.png)

**Comment by shinayser** [comment]
Another one for the Completion Overlord @pq !

**Comment by pq** [comment]
Is this one consistent for you?

In a quick attempt I wasn't able to repro:

![image](https://user-images.githubusercontent.com/67586/73943105-080b8d80-48a5-11ea-8448-203cdb36cb85.png)

Does it reproduce in a file in the same project w/ no other imports?

**Comment by shinayser** [comment]
I think that there are two differences in your test:
 - You are using Flutter, I was using a standalone CLI application
 - You are using VsCode (or am I wrong?)

I just tried with a new project and still not working. Please follow my steps:

- On Intellij, click **File -> New -> Project...**
- Select  **Dart -> Console Application**. Name it and press ok.
- Open the project, and go to the pubspec and add `http: any` on dependencies.
- Open the file `main.dart` located on the `bin`. It containes the **main** method.
- Add `import 'package:http/http.dart';` on the top of the file.
- Try to `put`, `post`, `get` inside the `main` method. 
- Doesn't work.

![image](https://user-images.githubusercontent.com/1146982/73962440-357c2980-48ed-11ea-9471-e5905027174e.png)

**Comment by pq** [comment]
Hmmm.  So I _am_ using IntelliJ.  Following your steps w/ a sample console app works for me too:

![image](https://user-images.githubusercontent.com/67586/73964680-85e09080-48c7-11ea-9f6d-09478137882f.png)

(`Dart VM version: 2.8.0-edge.e84bea25df23ea5f149fc808a6423c7500b9cace`)

🤔 

What Dart SDK are you using?

**Comment by shinayser** [comment]
`Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"`

**Comment by shinayser** [comment]
Ok, I just updated my sdk. Now I have:

`Dart VM version: 2.8.0-dev.8.0 (Thu Feb 6 15:47:55 2020 +0100) on "windows_x64"`

And still no completion =(

**Comment by shinayser** [comment]
I am a stupid person. Sorry for taking your time @pq I just found out what was going wrong...

This stupid guy here added `http` depency to the `environment` instead of `dependencies`:

![image](https://user-images.githubusercontent.com/1146982/73965614-42038080-48f3-11ea-980d-933b8a9a1688.png)

But that raised one question:

Why it wasn't being auto completed, but could be imported normally? 🤔

**Comment by pq** [comment]
Amazing!  (And a relief since I couldn't repro on windows either! ;))

> Why it wasn't being auto completed, but could be imported normally?

I believe `http` comes in as a transitive dependency of `test`.  You can confirm this by removing the dependency on test, upgrading and you'll see a squiggle on the import:

![image](https://user-images.githubusercontent.com/67586/73966833-a3175e00-48cb-11ea-81e2-8889b3491310.png)

As it happens we've got a lively thread going about how we can improve diagnostics (and support generally) for transitive dependencies here https://github.com/dart-lang/linter/issues/29.  Feel free to chime in!

All of that said, it's also weird that we are not flagging `http` as an invalid environment in your pubspec.  That just seems wrong?  (fyi @bwilkerson)

**Comment by bwilkerson** [comment]
We currently do a fairly limited job of validating the `pubspec.yaml` file. This would be a good thing to check if we ever enhance that.

**Comment by shinayser** [comment]
Great! Goo to see that my stupidness can be of value to enhance the tooling =)

**Comment by shinayser** [comment]
I created a new thread for trackign this issue. Thanks everytone and sorry for my mistake!

**Comment by pq** [comment]
No worries.  Thanks for the follow-up!
