### ISSUE TITLE
NNBD: Dart does not throw compile error when subtyping brings together incompatible member signatures for the method overriden in the opted in code.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40414]
Dart VM version: 2.8.0-edge.40f23c735f04433e4fc334fbd674474bd3de0f8b (Tue Jan 28 01:14:48 2020 +0000) on "linux_x64"

The following code source  brings together otherwise incompatible member signatures in the legacy code, then opted in method inherits them:

testlib_in.dart:
``` dart
class NULLABLE {
  int? i;
}

class NONNULLABLE {
  int i = 1;
}
```
testlib_out.dart:
``` dart
// @dart=2.6
import "testlib_in.dart";
class A extends NULLABLE implements NONNULLABLE {}
```
test.dart:
``` dart
import "testlib_out.dart";

class B extends A {}

class C extends A {   
  int? i;    // Unexpected compile error here
}

main() {
  print(A().i);
  print(B().i);
  print(C().i);
}
```
Seems like according to the Spec this example should throw compile error. At least, `Classes defined in opted-in libraries` section contains very similar example.

However, dart prints "null" three time (seems like this result is wrong) whereas analyzer throws compile time error (OK).
Sample output is:
> $ dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error • 'C.i' ('int? Function()') isn't a valid override of 'NONNULLABLE.i' ('int Function()'). • test.dart:6:8 • invalid_override
> 1 error found.
> $ dart --enable-experiment=non-nullable test.dart
> null
> null
> null
> $

**Comment by stereotype441** [comment]
Since the error occurs in opted-in code, I believe this does not block unforking the SDK.  Reassigning to the epic for full implementation of null safety in analyzer.

**Comment by scheglov** [comment]
It seems that this issue is triaged incorrectly, analyzer does report the diagnostics.
I will add [a unit test](https://dart-review.googlesource.com/c/sdk/+/135187), but it seems that this should be a CFE issue.

**Comment by eernstg** [comment]
We [switched](https://github.com/dart-lang/language/pull/789/files) to what we have called the 'consolidated' model, whereby each class has a complete interface (so you never need to traverse the whole superinterface graph in order to find the member signature for any given name), and a class declared in an opted-out library has a set of member signatures where every type is a `*` type.
