### ISSUE TITLE
NNBD: The argument type 'Future<T> Function()' can't be assigned to the parameter type 'FutureOr<T> Function()'

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#40416]
When using the analyzer in NNBD mode with the migrated SDK, the analyzer incorrectly detects an error when a function literal of type returning a Future is provided to `Future.then()`, complaining it cannot be assigned to a function returning FutureOf:

```dart
Future<int> foo() async => 0;

void a() {
  foo().then((_) => foo());
//|           ^^^^^^^^^^^^ STATIC_WARNING.ARGUMENT_TYPE_NOT_ASSIGNABLE
//| The argument type 'Future<int> Function(int)' can't be assigned to the parameter type 'FutureOr<int> Function(int)'.
}
```

Confirm with `dartanalyzer --dart-sdk=sdk_nnbd --enable-experiment=non-nullable test.dart`.

The error does not appear if the int is nullable or if a function with the right type is provided rather than the type being inferred.

This bug is blocking migrating the dart:io tests to NNBD, with 207 such compile errors across 41 files.

Additional test cases:

```dart
import 'dart:async';

Future<int> foo() async => 0;
Future<int?> bar() async => 0;

void a() {
  foo().then((_) => foo());
//|           ^^^^^^^^^^^^ STATIC_WARNING.ARGUMENT_TYPE_NOT_ASSIGNABLE
//| The argument type 'Future<int> Function(int)' can't be assigned to the parameter type 'FutureOr<int> Function(int)'.
}

void b() {
  // But it works with a nullable int.
  bar().then((_) => bar());
}

void c() {
  Future<int> x = foo();
  foo().then((int y) => x);
//|           ^^^^^^^^^^^^ STATIC_WARNING.ARGUMENT_TYPE_NOT_ASSIGNABLE
//| The argument type 'Future<int> Function(int)' can't be assigned to the parameter type 'FutureOr<int> Function(int)'.
}

void d() {
  // It works when returning an int.
  foo().then((int y) => y);
}

void e() {
  // It works when the function literal is assigned to a typed variable.
  Future<int> Function(int) func = (_) => foo();
  foo().then(func);
}

void f() {
  // But not when inferring the type.
  final func = (int whatever) => foo();
  foo().then(func);
//|           ^^^^ STATIC_WARNING.ARGUMENT_TYPE_NOT_ASSIGNABLE
//| The argument type 'Future<int> Function(int)' can't be assigned to the parameter type 'FutureOr<int> Function(int)'.
}

void g() {
  // It works when inferring the type when int is nullable.
  final func = (int? whatever) => bar();
  bar().then(func);
}

void h() {
  // It also works with an actual function.
  FutureOr<int> hello(int whatever) async {
    return whatever;
  }
  foo().then(hello);
}
```

**Comment by eernstg** [comment]
I tried to run this, but I don't get the indicated errors. Could it be the execution which doesn't run the right version of some tool? Here's the scenario, with current directory in the root of an SDK checkout at commit 3ab2112b06bee0ad28788b358d4a47e29d9be9d3:

```
> git co master
> tools/build.py -m release create_sdk; tools/build.py -m release --nnbd create_sdk
...
> cp ... # make sure that the example exists as tests/language/scratch_test.dart
> tools/test.py -n analyzer-asserts-strong-linux --enable-experiment=non-nullable language/scratch_test
...
```

This runs the analyzer on the source code from [here](https://github.com/dart-lang/sdk/issues/40416#issue-558207537) where I've deleted the `//|` comments (just in case some tool considers those comments to have some meaning), and no errors are reported.

**Comment by sortie** [comment]
I built master in the same way using b68d95ec9e13d11eaa12c71daed52f263c0fa4ac. Did you run the test with `out/ReleaseX64/dartanalyzer --dart-sdk=sdk_nnbd --enable-experiment=non-nullable test.dart`? The --dart-sdk option to provide the sdk_nnbd was essential.

**Comment by eernstg** [comment]
The command I mentioned

```
> tools/test.py -n analyzer-asserts-strong-linux --enable-experiment=non-nullable language/scratch_test
```

does include `--dart-sdk=sdk_nnbd`. Here's the full command that it runs:

```
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --dart-sdk=sdk_nnbd --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/usr/local/google/home/eernst/devel/dart/work/sdk/.packages --format=machine --no-hints /usr/local/google/home/eernst/devel/dart/work/sdk/tests/language/scratch_test.dart
```

Note that it uses `out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer`, not `out/ReleaseX64/dartanalyzer`.

**Comment by sortie** [comment]
(Err that was a typo, I meant `out/ReleaseX64/dart-sdk/bin/dartanalyzer`)

But it turns out `out/ReleaseX64/dart-sdk/bin/dartanalyzer` works for me! Apparently @munificent's `tools/migration/lib/src/analyze.dart` was using the `dartanalyzer` from the PATH which is 2.7.0 for me, rather than the analyzer I had just built. Seems like this issue has been solved in master since the 2.7.0 release. I'll close the issue now and confirm master indeed works as intended next week.

**Comment by munificent** [comment]
> Apparently @munificent's `tools/migration/lib/src/analyze.dart` was using the `dartanalyzer` from the PATH which is 2.7.0 for me

Oops, sorry. The migration script is pretty hacky since it's just a temporary tool. If you have improvements, I'm definitely happy to take them. :)

**Comment by exeptionerror** [comment]
All Possible Solution added here [[Solved] The argument type ‘Future’ can’t be assigned to the parameter type ‘void Function()’](https://fluttercorner.com/error-the-argument-type-future-cant-be-assigned-to-the-parameter-type-void/)

**Comment by behzodfaiziev** [comment]
> All Possible Solution added here [[Solved] The argument type ‘Future’ can’t be assigned to the parameter type ‘void Function()’](https://fluttercorner.com/error-the-argument-type-future-cant-be-assigned-to-the-parameter-type-void/)

Your link has virus!!!
