### ISSUE TITLE
Bad error recovery when declaring method named "with"

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#40419]
Parse this code:

```dart
class C {
  int with() => 7;
}
```

Apparently `with` is a reserved keyword across the board. In analyzer, for example, this produces the following errors:

>   error • Variables must be declared using the keywords 'const', 'final', 'var' or a type name. • a.dart:2:3 • missing_const_final_var_or_type
  error • Expected to find ';'. • a.dart:2:3 • expected_token
  error • Expected a class member. • a.dart:2:7 • expected_class_member
  error • Expected an identifier. • a.dart:2:11 • missing_identifier

**Comment by jensjoha** [comment]
Fixed with a840da4617565975fb773382fdf1a58376735d9b, 497bdc52269e8f8d83f4eed9770cb8c96b450fc4 and 5b76fc217295a4a62f2b89a96051d8b204c433ae.
