### ISSUE TITLE
Dart thinks my filename is capitalized and gives weird assignment compile error

### ISSUE THREAD

**Issue by remoteportal** [dart-lang/sdk#40437]
My filename is friendBase.dart, NOT FriendBase.dart!

Seems the compiler is internally confused and inconsistent about the capitalization of my filename.

Been fighting this erroneous error for several days now.

'''
Compiler message:
lib/json/FriendBase.dart:85:17: Error: A value of type 'FriendBase/*1*/' can't be assigned to a variable of type 'FriendBase/*2*/'.
 - 'FriendBase/*1*/' is from 'package:skateboard/json/friendBase.dart' ('lib/json/friendBase.dart').
 - 'FriendBase/*2*/' is from 'package:skateboard/json/FriendBase.dart' ('lib/json/FriendBase.dart').
    return Temp.friendFromJson(json);
                ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Src\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Src\Flutter\bin\flutter.bat'' finished with non-zero exit value 1
'''

'''
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at E:\Src\flutter
    • Framework revision 9f5ff2306b (6 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pete\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
'''

**Comment by lrhn** [comment]
Please check that no part of your code contains a reference to the file as `FriendBase.dart`.

Dart libraries are identified by their import URI. If one file imports `'package:skateboard/json/friendBase.dart'` and another imports `'package:skateboard/json/FriendBase.dart'`, then the language treats that as two different libraries declaring distinct and incompatible types. If you are running it on a platform where the file system is not case sensitive (like Windows), then the two URIs end up referencing the same *file*, but it's still  different *libraries*. (On an operating system with a case sensitive file system, one of the imports would just fail).

**Comment by mraleph** [comment]
@remoteportal seems like we have not gotten any response from you. I am going to close this issue as stale.

**Comment by remoteportal** [comment]
@mraleph can you please re-open.  I keep hitting this error.  It has nothing to do with importing capitalized paths... 

Now I'm getting it with another file:

error: Expected this library to be part of 'package:fa/json/AppBase.dart', not 'package:fa/json/appBase.dart'. (part_of_different_library at [fa] lib\json\appBase.dart:4)

**Comment by remoteportal** [comment]
> Please check that no part of your code contains a reference to the file as `FriendBase.dart`.
> 
> Dart libraries are identified by their import URI. If one file imports `'package:skateboard/json/friendBase.dart'` and another imports `'package:skateboard/json/FriendBase.dart'`, then the language treats that as two different libraries declaring distinct and incompatible types. If you are running it on a platform where the file system is not case sensitive (like Windows), then the two URIs end up referencing the same _file_, but it's still different _libraries_. (On an operating system with a case sensitive file system, one of the imports would just fail).

It's all on Windows and I checked all my imports; they are all lower case.  Somewhere inside your code, you are capitalizing something.

**Comment by remoteportal** [comment]
![image](https://user-images.githubusercontent.com/5971985/78538728-74304200-77bf-11ea-8d91-8681375fc6b3.png)

**Comment by mraleph** [comment]
@remoteportal you need to check that files on disk and your import paths have consistent capitalization. e.g. if you file on disk is called `AppBase.dart` then it should be referred to everywhere as `AppBase.dart`. If your file is called on disk `appBase.dart` then it should be referred to everywhere as `appBase.dart`. Please verify this. 

> Now I'm getting it with another file:
> error: Expected this library to be part of 'package:fa/json/AppBase.dart', not 'package:fa/json/appBase.dart'. (part_of_different_library at [fa] lib\json\appBase.dart:4)

Please search your code base for `AppBase.dart` and see if you have any matches.

**Comment by rasmusir** [comment]
Worth noting is that if you are on windows and you rename a file from `fooBar.dart` to `FooBar.dart` it might _look_ renamed in your explorer, even though it isn't. My solution to this has always been to rename it something completely different, then to what I actually want the file to be named.

**Comment by ali2236** [comment]
For me, the problem was with the project directory name. even after renaming it with lowercase letters, I kept getting a similar error. fixed by deleting the project from Android Studio's recent projects and opening the project again.
