### ISSUE TITLE
Analyzer complains about mixins with getters and setters, but CFE allows it

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#40435]
Seems like an implementation bug, as it runs fine (and I would expect it to work).

Example (reproduces in DartPad):

`Const constructor can't be declared for a class with a mixin that declares an instance field - line 12`

```dart
mixin A {
  int get foo;
}

class Bar implements A {
  const Bar();
  
  int get foo => 1;
}

class Qux with A {
  const Qux();
  
  int get foo => 2;
}

void main() {
  print(const Bar().foo);
  print(const Qux().foo);
}
```

**Comment by srawlins** [comment]
The analyzer no longer reports any issues with this code.
