### ISSUE TITLE
Analysis server crashes/stops responding after a few interactions in WSL 2

### ISSUE THREAD

**Issue by jonas-jonas** [dart-lang/sdk#40436]
I just installed the latest Flutter SDK (version below) inside my local WSL 2 instance to use with the "Remote" extension in VSCode. I noticed that after a few actions (quick fix, code suggestion, LSP stuff) the analysis server just stops responding. This results in an endless "Loading..." message in the code suggestion popup and no more code analysis in the editor. 

I captured the logs via `Dart: Capture Logs` right after a reload ([gist](https://gist.github.com/jonas-jonas/f4693898ecd9e31bfcbdead2596212ab)) and there is just no answer for the requests sent by the editor.

```
$ flutter --version
Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (6 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0
```

FWIW: With just Dart and a plain Dart project its the same situation and the whole thing feels very sluggish _when_ it works.
I also disabled Windows Defender scanning for all my WSL folders with no improvement.

I'm not sure if there is better way of capturing some logs related to this. If there is, let me know how and I will provide them.

**Comment by bwilkerson** [comment]
I'm going to close this under the assumption that it's been fixed by now. If you're still experiencing an issue, please re-open this issue or create a new one.
