### ISSUE TITLE
Request for a cherry-pick so that Flutter can hotfix it into stable

### ISSUE THREAD

**Issue by christopherfujino** [dart-lang/sdk#40443]
Because of [App startup crash on android arm device](https://github.com/flutter/flutter/issues/47819), flutter would like to cherry pick [5581307](https://github.com/dart-lang/sdk/commit/5581307ae6ade7a6a093a9643993b159f270ac56) onto [a4911c6](https://github.com/dart-lang/sdk/commit/a4911c63f4f72ba571d6db94de56007b09f4af99) (which is the revision stable is currently using). Is this possible?

Dart revision flutter stable is currently using: https://github.com/dart-lang/sdk/commit/a4911c63f4f72ba571d6db94de56007b09f4af99
Dart commit with fix: https://github.com/dart-lang/sdk/commit/5581307ae6ade7a6a093a9643993b159f270ac56

**Comment by christopherfujino** [comment]
@athomas

**Comment by athomas** [comment]
It is possible but I would advise against this. We have zero test coverage for special branches and the stable branch is already beyond a4911c6 (that is source equivalent to Dart stable 2.7.0). The stable branch is at 2.7.1 and the safe option would be cherry-pick 5581307 onto stable and call it 2.7.2 and then hotfix that into Flutter.

**Comment by christopherfujino** [comment]
Given the risk of picking up further upstream commits, I'm going to close this issue. Thanks!

**Comment by samardzija** [comment]
@christopherfujino @athomas when is planned to be a new stable release? 

IMO, this is a showstopper for 1.12 version, app crash on startup on real device and the version is useless with this bug and we as a developers can't do anything about it. It should be pushed to the stable as soon as possible.

**Comment by christopherfujino** [comment]
@samardzija you have a valid point. the decision not hotfix was from the flutter team. Could we move this conversation to [the flutter issue](https://github.com/flutter/flutter/issues/47819)?
