### ISSUE TITLE
Provide a `isConst` flag in Kernel AST for `Class`es

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#40440]
The VM would benefit if the front-end could provide a `isConst` flag on a `Class` if that class has a const constructor (and can therefore have const instances in the kernel).

(One could derive this information by looking at the class'es generative constructors and checking if any of those are const. Unfortunately this doesn't work after tree-shaking: Any tree shaker can shake the constructors away.)

@johnniwinther Do you think we can add such a flag?

/cc @rmacnak-google

**Comment by johnniwinther** [comment]
It shouldn't be a problem add a flag for this. Is this blocking something?

**Comment by mkustermann** [comment]
> It shouldn't be a problem add a flag for this. Is this blocking something?

Right now we have inconsistencies in the hot-reload implementation we would like to address. Having this flag would benefit that effort. It's not super urgend.
