### ISSUE TITLE
Build warnings with clang-cl on Windows.

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/sdk#40448]
Attempting to build with clang on Windows (via clang-cl) fails due to [this issue with POSIX names](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=vs-2019#posix-function-names). I believe the solution is either to try to disable the relevant warnings in as targeted a way as possible, or wrap the affected functions (e.g., `strdup` is where I'm hitting failures at the moment) in something with platform-specific implementations that call the `_`-prefixed versions on Windows.

This is related to https://github.com/flutter/flutter/issues/16256

**Comment by stuartmorgan** [comment]
I'll have one or more patches shortly to post for discussion. There were some other things caught by clang, at least one of which look like a real bug.

**Comment by stuartmorgan** [comment]
https://dart-review.googlesource.com/c/sdk/+/134502 has the first part, which is the fixes that aren't really specific to supporting clang, but rather general issues found when compiling with clang, so I expect to be uncontroversial.

The next part will require some small GN changes, but I'm still adjusting it to make those changes minimal.

**Comment by stuartmorgan** [comment]
https://dart-review.googlesource.com/c/sdk/+/134781 has the second part. With those two changes I'm able to build Flutter using clang on Windows.

There's a larger question of whether Dart's buildroot should support this directly, and whether it should be part of CI.

**Comment by stuartmorgan** [comment]
@a-siva Could you recommend a reviewer for the second patch above? It's the only remaining source-level blocker for building the Flutter engine with clang.

**Comment by ZichangG** [comment]
Siva is out for vacation.
@zanderso Do you know the right person to review?

**Comment by zanderso** [comment]
Ah, sorry, I left a comment, but I don't know who should review. Maybe @rmacnak-google ?

**Comment by stuartmorgan** [comment]
Ping again on the review above.

**Comment by stuartmorgan** [comment]
Another issue that only showed up in certain build configurations: https://dart-review.googlesource.com/c/sdk/+/144520

That's a hard blocker for us switching to clang (unlike the previous CL that's still unreviewed, which we were able to work around), so if someone could route it to a reviewer that would be great. It's also a potentially serious bug for non-clang, FWIW, and apparently we've just been lucky so far.

**Comment by stuartmorgan** [comment]
The warning suppression CL above is abandoned in favor of fixing the calls to uses non-deprecated versions:
- https://dart-review.googlesource.com/c/sdk/+/151394
- https://dart-review.googlesource.com/c/sdk/+/151362

(Not exhaustive; more minor cleanup to follow)

**Comment by stuartmorgan** [comment]
Alternately, https://dart-review.googlesource.com/c/sdk/+/142704 will fix everything. (It turned out I happened to come back to this when it was already in progress on the Dart team side.)

**Comment by stuartmorgan** [comment]
The PR above didn't quite fix everything, it looks like. Here's what we're seeing in a recent Flutter build:

ANGLE roll is finally in. A bot build log is now a much more reasonable 6k lines and 500kb.

The remaining warnings from the run with the ANGLE fixes are:
```
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime/bin/gen_snapshot.cc(632,26): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
../../third_party/dart/runtime/bin/gen_snapshot.cc(641,15): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
2 warnings generated.
../../third_party/dart/runtime/bin/gen_snapshot.cc(632,26): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
../../third_party/dart/runtime/bin/gen_snapshot.cc(641,15): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
2 warnings generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
```

So it looks like there's one namespace bug, and a couple of places where `strdup` isn't using the new wrapper.

**Comment by cbracken** [comment]
@stuartmorgan @a-siva is this issue still valid?

**Comment by a-siva** [comment]
I checked the latest version of gen_snapst.cc and I see that strdup has been replaced with Utils::StrDup so that warning should be accounted for.
I believe you fixed the other warning from asm_intrinsifier.h here https://dart-review.googlesource.com/c/sdk/+/162901

**Comment by a-siva** [comment]
The issue could be closed I suppose.

**Comment by cbracken** [comment]
Yep, and I sent one more strdup cleanup today which is merged:
https://dart-review.googlesource.com/c/sdk/+/242386
