### ISSUE TITLE
When I debug flutter, dar use a lot of memory, how to find out which part cause this problem.

### ISSUE THREAD

**Issue by jerryzhoujw** [dart-lang/sdk#40450]
<img width="649" alt="Screen Shot 2020-02-04 at 10 49 44 AM" src="https://user-images.githubusercontent.com/6405390/73709621-84cf2800-473c-11ea-9b21-4df28835b615.png">

* Dart SDK Version (`dart --version`)
> Dart VM version: 2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "macos_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable): MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Flutter

**Comment by rmacnak-google** [comment]
When you launch your Flutter application, the Flutter tool will print a message "Observatory ... is available at http://127.0.0.1:xyz/abcdef/". This URL will take you to a web page with many debugging, inspecting and profiling tools. For understanding memory, look at the "allocation profile" and "heap snapshot" tools.

**Comment by jerryzhoujw** [comment]
@rmacnak-google it's a little tricky, `it's not  happening when I debugging`, it's happening when after when I debugging. I have stopped the debug, but not close the vscode, still typing code. After sometime(maybe hours, and I have left computer open when I left), I found memory spend much more, so I checked the Activity Monitor.
