### ISSUE TITLE
Crashing kernel compilation in type promotion - 2.8.0-dev.7.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40459]
Code that's been running for a year+

```dart
T emptyAsNull<T>(T value) {
  if (value is Iterable) {
    return (value?.isEmpty ?? true) ? null : value;
  } else if (value is Map) {
    return (value?.isEmpty ?? true) ? null : value;
  }
  return value;
}
```

At runtime:

```
Unable to spawn isolate: lib/src/util.dart:11:20: Error: The getter 'isEmpty' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEmpty'.
    return (value?.isEmpty ?? true) ? null : value;
                   ^^^^^^^
lib/src/util.dart:13:20: Error: The getter 'isEmpty' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEmpty'.
    return (value?.isEmpty ?? true) ? null : value;
                   ^^^^^^^
```

**Comment by mit-mit** [comment]
cc @johnniwinther

**Comment by kevmoo** [comment]
FYI – it seems things are fine at bleeding edge. We may need to just patch the dev release – or roll dev.8 sooner rather than later

CC @athomas

**Comment by athomas** [comment]
In this case, we don't have a newer roll to release, yet. What is impacted by this dev release having this problem?

**Comment by kevmoo** [comment]
> In this case, we don't have a newer roll to release, yet. What is impacted by this dev release having this problem?

At the moment, I've only seen the issue on a private tool that I use – haven't seen a crash on travis or anything external – yet.

**Comment by johnniwinther** [comment]
This issue should have been fixed in https://dart-review.googlesource.com/c/sdk/+/134161
