### ISSUE TITLE
const at the top level of a structure should propagate down

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#4046]
I have some large objects which are constant. As it stands, writing one of these out requires 22 occurrences of the word &quot;const&quot;, one for every field (which isn't a string literal or number, because those are implicitly const and it's an error to write it explicitly).

It is not legal to write a const constructor call, literal Map or literal List containing non-const expressions. So it seems unnecessary to require a const annotation on the individual pieces. They are required to be const, so we should just enforce that they are without requiring the developer to also spell it out. That is to say, instead of having to write

var list = const [  const ['a'], const ['b'], const ['c']];

I should be able to write

var list = const [  ['a'], ['b'], ['c']];

there the outer const also applies to the inner lists. And the same for maps and const constructor invocations.

**Comment by zoechi** [comment]
I guess the link provides more value here than in #24620. I was sure I have seen the proposal but wasn't able to find it.
https://github.com/lrhn/dep-const/blob/master/proposal.md

**Comment by eernstg** [comment]
This feature is now an accepted part of Dart 2. The feature specification [implicit-creation.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/implicit-creation.md) gives the details, but the following is a good starting point:

> For instance creation expressions we have chosen to use const whenever possible,
> and otherwise new.
> ...
> For composite literals we have chosen to implicitly introduce const whenever it is
> required by the context.

So `C(42)` is a constant expression if the relevant `C` constructor is `const` (even in cases where the context does not require a constant expression), and `const xs = [];` makes `[]` a constant list, but `var xs = [];` makes `[]` a non-constant list.
