### ISSUE TITLE
Migration should consider inserting `as K` instead of putting a ! on `K`.

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40464]
Silly example:

```dart
class HashMapBackedList<T> {
  Map<int, T> _map;

  ...

  T/*!*/ get first => _map[0];

  ...
}
```

If we migrate this to

```dart
  T get first => _map[0]!;
```

then this changes behavior for nullable instantiations

```dart
var x = HashMapBackedList<int/*?*/>();
x.add(null);

// should return null:
x.first;
// instead throws NPE because we call `!` on `_map[0]` which is null.
```

A better migration is

```dart
  T get first => _map[0] as T;
```

@pq @bwilkerson For similar reasons, we may want to lint this.

Cases this doesn't apply:
- if the bound is nullable
- if we call a method on the bound type (ie, `T extends num`, `_map[0].floor()` should become `_map[0]!.floor()`)
- maybe others

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
