### ISSUE TITLE
DartTypeVisitor should be a real visitor

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40478]
Currently the analyzer's `DartTypeVisitor` class dispatches using a bunch of `is` checks.  We should really update it to follow the traditional visitor pattern, using an abstract `accept` method in `DartType`, which each concrete subtype overrides to call the appropriate method in the visitor class.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153361
