### ISSUE TITLE
nnbd: function?.call() must be null-checked

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#40482]
The analyzer doesn't appear to correctly handle a null checked call on a `Function?` in the following program:

```dart
Function? foo;

main() {
  foo?.call();
}
```

It produces the following analyzer errors:

```
Analyzing test.dart...
  error • The expression is nullable and must be null-checked before it can be used. • test.dart:3:3 • unchecked_use_of_nullable_value
1 error found.
```

These calls are supposed to work after talking to @lrhn and @eernstg. 

The issue occurs for me at 43b69d4ba903eb1638e571e944a18ea51c07b425.

This issue blocks getting `dart:_http` clean of analyzer errors in NNBD mode as it has two such calls.

**Comment by vsmenon** [comment]
@stereotype441 tentatively bumping priority on this, as it's the only issue left keeping the ddc sdk from being analyzer clean:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/tool/dartdevc_nnbd_sdk_error_golden.txt

If this will take a while, we could probably workaround in `dart:_http` ( @sortie ?).  That would unblock unforking / legacy, but we'll likely hit this shortly after that.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135185
