### ISSUE TITLE
Migration tool navigation links are broken

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40487]
Steps to reproduce:
- Attempt to migrate the collection package to NNBD
- Open the navigation preview
- Click on the file `algorithms.dart`
- Click on the first change (the `?` on the line `int binarySearch<T>(List<T> sortedList, T value, {int Function(T, T)? compare}) {`)
- Click on the first link in the `Edit Info` pane (which says "2. This named parameter is omitted in a call to this function in test code (../../test/algorithms_test.dart)"

Expected result: navigated to the file `algorithms_test.dart`

Observed result: an error message dialog reading "Could not load /.../collection/../../test/algorithms_test.dart?offset=1924&line=62; preview server might be disconnected."

I was able to bisect this behavior to f51187a18dbf328aaaa39723f5e3f67e18dae725.
Marking as P1 because this is making it difficult to diagnose migration problems with the collection package.
@devoncarew FYI

**Comment by devoncarew** [comment]
Thanks! I can reproduce this.

**Comment by devoncarew** [comment]
Fix in flight: https://dart-review.googlesource.com/c/sdk/+/134767

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/sdk/commit/8f5b1ea9bbd7104f04447110e12cb5383bae6af2
