### ISSUE TITLE
Provide access to the feature set of a library

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#40491]
The getter `LibraryElement.isNonNullableByDefault` should be removed and a more general mechanism, such as `LibraryElement.featureSet` should be added. The first is just a special case that could be handled by the second and the second will be needed for more than just the NNBD feature.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by srawlins** [comment]
`.featureSet` is now available, and `.isNonNullableByDefault` is now deprecated.

**Comment by scheglov** [comment]
I guess, I did it :-)
