### ISSUE TITLE
Failures on [cfe] Handle opt-out Null override of opt-in Never

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40516]
There are new test failures on [[cfe] Handle opt-out Null override of opt-in Never](https://dart-review.googlesource.com/c/sdk/+/134702).

The tests
```
co19/LanguageFeatures/nnbd/override_checking_A01_CLASSPARAM_t33 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A01_CLASSPARAM_t34 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A01_CLASSPARAM_t37 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A01_CLASSPARAM_t38 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A01_CLASSPARAM_t39 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A01_GETTER_t23 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A06_t10 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/override_checking_A06_t13 CompileTimeError (expected Pass)
```
are failing on configurations
```
cfe-weak-linux
dartdevk-strong-linux-release-chrome
```

**Comment by iarkh** [comment]
Below is a list of the bugs related with the test failures. Could you please check?

**#3966:**
override_checking_A01_CLASSPARAM_t33 CompileTimeError (expected Pass)
override_checking_A01_CLASSPARAM_t34 CompileTimeError (expected Pass)
override_checking_A01_CLASSPARAM_t37 CompileTimeError (expected Pass)
override_checking_A01_CLASSPARAM_t38 CompileTimeError (expected Pass)

**#40389:**
override_checking_A01_CLASSPARAM_t39 CompileTimeError (expected Pass)
override_checking_A01_GETTER_t23 CompileTimeError (expected Pass)

**#40481:**
override_checking_A06_t10 CompileTimeError (expected Pass)
override_checking_A06_t13 CompileTimeError (expected Pass)

**Comment by johnniwinther** [comment]
These have all been fixed.
