### ISSUE TITLE
dart:mirrors does not account for nullability

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#40510]
`TypeMirror.isSubtypeOf` and `TypeMirror.isAssignableTo` do not account for recent language breakage.

`TypeMirror.isNullable` should be added.

**Comment by a-siva** [comment]
@rmacnak-google is this something you are looking at adding ?

**Comment by Silentdoer** [comment]
VariableMirror should support a api to get field's type when it's default null;
like this code:
class Foo {
int? kk;
}
kk is default null, so instanceMirror.getField(#kk).type can not get kk's declare type.

**Comment by Silentdoer** [comment]
VariableMirror should support a api to get field's type when it's default null;
like this code:
class Foo {
int? kk;
}
kk is default null, so instanceMirror.getField(#kk).type is Null, we can not get kk's declare type int?

**Comment by lrhn** [comment]
The `dart:mirrors` library does not account for nullability at all. There is no understanding of nullable types at all.
The library will need to be migrated.

**Comment by franklinyow** [comment]
Any update on this?

**Comment by a-siva** [comment]
the` dart:mirrors` library is in maintenance mode and I would prefer if we did not add any new functionality or APIs to it.

**Comment by Silentdoer** [comment]
Oh, why? TypeMirror.isNullable is very useful.

**Comment by Silentdoer** [comment]
May be T? equals Nullable<T> is a good choice?
AClass? equals Nullable<AClass>;
AClass? obj = AClass();
obj?.prop will auto unboxing to obj.getValue().prop

**Comment by franklinyow** [comment]
@a-siva Can this be move out of the beta Epic?

**Comment by a-siva** [comment]
Yes we should move it out of the beta Epic.

**Comment by Silentdoer** [comment]
main(List<String> args) {
  var pro1 = reflectClass(NullableTest).declarations[#pro1] as VariableMirror;
  // type should return a list, [ClassMirror on 'int', ClassMirror on 'Null']
  print(pro1.type);
}

class NullableTest {

  int? pro1;

  double pro2 = 9;
}

**Comment by Silentdoer** [comment]
main(List args) {
var pro1 = reflectClass(NullableTest).declarations[#pro1] as VariableMirror;
// type should return a list?, [ClassMirror on 'int', ClassMirror on 'Null']
print(pro1.type);
}

class NullableTest {

int? pro1;

double pro2 = 9;
}

**Comment by pouyakary** [comment]
Any progress?

**Comment by a-siva** [comment]
@pouyakary at this point we have no plans for making `dart:mirrors` library account for nullability.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for `dart:mirrors`
