### ISSUE TITLE
Move builder dart2js-nnbd-linux-x64-chrome back to CQ

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#40521]
I have removed it from the CQ for now (https://dart-review.googlesource.com/c/sdk/+/134821/), but we should find a solution for the timeouts and move it back to the CQ.

**Comment by sigmundch** [comment]
Not sure why we are hitting so many timeouts - it's possible also that it is a combination of the fact that it is running a vm with assertions enabled in nnbd mode.

I'm inclined to temporarily switch to use a no-assertions configuration for now instead.

**Comment by sigmundch** [comment]
sent https://dart-review.googlesource.com/c/sdk/+/134885 to do use a cheaper configuration for now

**Comment by athomas** [comment]
It was never really removed from the CQ, I've created https://dart-review.googlesource.com/c/sdk/+/135681 to avoid such confusion in the future.
