### ISSUE TITLE
problem when using a FFI 'C' callback function

### ISSUE THREAD

**Issue by AlexB71** [dart-lang/sdk#40529]
I'm on dart 2.7.1 Windows 10 - I'm getting a problem when using a FFI 'C' callback function.
I tried to pass a function pointer to a 'C' method that uses a function call back
When to callback is performed, I'm getting an error message from dart c:\b\s\w\ir\cache\builder\sdk\runtime\vm\runtime_entry.cc: 3217: error: Cannot invoke native callback outside an isolate.
I've tried using an isolate in the registration call but the error still happens

I've seen in issue 37301 that someone has done a callback...

I was wondering if the patch was in 2.7.1 or still on a dev branch ?
Can FFI 'C' callbacks to dart be done yet ?

**Comment by dcharkes** [comment]
> Can FFI 'C' callbacks to dart be done yet ?

Yes.

From which thread are you trying to do a callback? Is this the Dart thread, or are you trying to do a callback from another thread?

**Comment by AlexB71** [comment]
I'm trying the callback from another thread in 'C' outside the Dart thread.
How does the error 'Cannot invoke native callback outside an isolate.'
happen ?

**Comment by dcharkes** [comment]
Yes, doing a callback from another thread is not supported. Dart has one mutator thread per isolate. If a Dart thread is already running in the isolate, and you would call back from C into Dart with another thread, there would be 2 threads executing Dart code in a single isolate. That would break the concurrency assumptions.

Instead, you have to call back into Dart on the main Dart thread. One can notify the main Dart thread asynchronously through a SendPort. Please check this sample: https://dart-review.googlesource.com/c/sdk/+/134704.

**Comment by AlexB71** [comment]
Thanks for the help, I'll follow the example and add adaptor functions to register the port and then to receive callbacks on the 'C' side. I'll use the Dart send message 'C' functions to pass parameter messages into the Dart isolate. Thanks again.

**Comment by shuisheng** [comment]
hi @dcharkes, 
I have dart client and call c++ dll
I use async callback via port, pass data to dart from c++ thread with Dart_PostCObject. 
after I compiled c++ code, then open c++ dll in dart, prompt cannot open the c++ dll
![Uploading 1675741052695.png…]()

then when I remove the call to Dart_PostCObject, that issue not occur

**Comment by shuisheng** [comment]
hi @dcharkes, 
I have dart client and call c++ dll
I use async callback via port, pass data to dart from c++ thread with Dart_PostCObject. 
after I compiled c++ code, then open c++ dll in dart, prompt cannot open the c++ dll
![Uploading 1675741052695.png…]()

then when I remove the call to Dart_PostCObject, that issue not occur

**Comment by shuisheng** [comment]
It's my mistake, I should use Dart_PostCObject_DL instead of Dart_PostCObject. now it can work

**Comment by houzhj58** [comment]
since dart 3.1,  can use NativeCallable
