### ISSUE TITLE
dart:html FontFace.loaded returning Future instead of Future<FontFace> with NNBD breaks a test

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#40530]
Test:
lib_2/html/fontface_loaded_test

Error:
Caught Expected a value of type 'Future<FontFace>', but got one of type 'NativeJavaScriptObject'

Root Cause:
In the autogenerated file sdk_nnbd/lib/html/dart2js/html_dart2js.dart, FontFace.loaded seems to have changed vs. sdk/lib/html/dart2js/html_dart2js.dart.

**Comment by srujzs** [comment]
https://dart-review.googlesource.com/c/sdk/+/134902
