### ISSUE TITLE
Lambda completion on optional parameters not working

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40539]
As @pq asked on https://github.com/dart-lang/sdk/issues/40202#issuecomment-583660685 I am opening this issue for provide completion for optional lambda parameters

**Comment by pq** [comment]
Thanks!

**Comment by scheglov** [comment]
I believe that the progress over years to suggest named arguments, and separately expression / block closure covers this issue.
```dart
class MyFuture {
  MyFuture.delayed(Duration d, {int Function()? operation});
}

void f() {
  MyFuture.delayed(const Duration(), ^);
}
```

<img width="646" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/d4f1a6bd-c245-4ff5-802f-2fa0fe425b29">

<img width="861" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/ad78ce3a-b263-4990-9bae-52a65ebb6a67">

<img width="752" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/bbf2fe44-8096-486f-a2c4-b3b0f725c26b">
