### ISSUE TITLE
AnalysisDriver.getSourceKind can return outdated data

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#40546]
In `AnalysisDriver`, `getSourceKind` appears to return outdated data after calling `changeFile`. This is causing issues with the build system in the following scenario

1. A builder runs on a file, say `/a/input.dart`, which has the following content. At this point, neither `/a/input.a.dart` or `/a/input.b.dart` exist.
  ```dart
part 'input.a.dart';
part 'input.b.dart';
   ```
2. That builder creates `input.a.dart` with the content `part of 'input.dart';`
3. Another builder runs on `input.a.dart`. `build_resolvers` will call `changeFile('/a/input.a.dart')` on the driver
4. `getSourceKind('/a/input.a.dart')` returns `SourceKind.LIBRARY`.

I'd expect that the last step should return `SourceKind.PART`, since the file has since been created and contains a `part of` statement. Adding a `file.refresh()` before [this line](https://github.com/dart-lang/sdk/blob/9464eb51f539593ac878dcd9e33ae5847cc48b8e/pkg/analyzer/lib/src/dart/analysis/file_state.dart#L845) fixes this problem, but I'm not sure if it's correct to make that change. Maybe `AnalysisDriver` doesn't properly invalidate the `FileSystemState` after calling `changeFile`?

This is causing https://github.com/dart-lang/source_gen/issues/447. @jakemac53 wrote a smaller test that can be used to reproduce this behavior: https://github.com/dart-lang/build/pull/2620. I'm using analyzer version `0.39.4`.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135100

**Comment by jakemac53** [comment]
Hmm, I am still seeing this in the test I had added. Looking into it a bit more.

**Comment by scheglov** [comment]
This change causes internal build failures when `getSourceKind()` is invoked for a path that is in a provided summary, so not all data structures are filled for it.

```
NoSuchMethodError: The method 'toList' was called on null.
Receiver: null
Tried calling: toList()
dart:core                                                         Object.noSuchMethod
package:analyzer/src/dart/analysis/file_state.dart 905:51         FileSystemState.getFilesForPath
package:analyzer/src/dart/analysis/file_tracker.dart 227:40       FileTracker.verifyApiSignature.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/file_tracker.dart 223:20       FileTracker.verifyApiSignature
package:analyzer/src/dart/analysis/driver.dart 834:37             AnalysisDriver.getSourceKind
package:_bazel_codegen/src/resolver/resolvers.dart 93:32          AnalysisResolver.isLibrary
package:build/src/builder/build_step_impl.dart 193:25             _DelayedResolver.isLibrary
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135280
