### ISSUE TITLE
Failures on Issue 40394. Updates to switch / case validation.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40543]
There are new test failures on [Issue 40394. Updates to switch / case validation.](https://github.com/dart-lang/sdk/commit/eeaa9085ae8c4c399db87e708ada12bbbe8b6a70).

The tests
```
co19/LanguageFeatures/nnbd/static_errors_A31_t03 MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-strong-linux
```

@scheglov FYI

**Comment by scheglov** [comment]
I opened https://github.com/dart-lang/co19/issues/525 and https://github.com/dart-lang/co19/issues/526, and marked tests as failing, but probably pre-approved them incorrectly.

**Comment by scheglov** [comment]
analyzer-nnbd-linux-release is green now.
