### ISSUE TITLE
32-bit dart2native

### ISSUE THREAD

**Issue by cup** [dart-lang/sdk#40545]
If I go here:

https://dart.dev/tools/sdk/archive

For both 2.7.1 and 2.8.0, the 32-bit version (ia32) does not include
`dart2native`, while the 64-bit variant does.

Normally I would be fine with just using the 64-bit variant, but it has its own
problem as its currently erroneously bundling some machine learning software
which has tripled the download size.

**Comment by cup** [comment]
https://github.com/dart-lang/sdk/issues/40544

**Comment by cup** [comment]
https://github.com/dart-lang/sdk/issues/39439

**Comment by mraleph** [comment]
We currently do not support AOT compilation on IA32 and there are no immediate plans to change that.
