### ISSUE TITLE
getting Platform from dart:io throws an exception when running in browser

### ISSUE THREAD

**Issue by ali2236** [dart-lang/sdk#40558]
While it is understandable why it does that, I think that when calling `Platform.isAndroid` in flutter web, it should just return `false`.

Another suggestion is to add `Platform.isWeb` to `dart:io` instead of using the `kIsWeb` constant from `package:flutter/foundation.dart` for checking that dart code is executing in the browser.

**Comment by vsmenon** [comment]
Merging to https://github.com/dart-lang/sdk/issues/35969
