### ISSUE TITLE
Exact-nullable is propagated too greedily

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40552]
```dart
class B<T extends Object> {                                                      
  void f(T t) {                                                                  
    // Create an edge from the bound to some type                                
    List<dynamic> x = [t];                                                       
    // and make that type exact nullable                                         
    x[0] = null;                                                                 
  }                                                                              
}
```

This migration should produce no source edits.

Currently, the assignment from `List<T>` to `List<dynamic>` results in an edge from the parameter `T` to the `dynamic` type argument in `List<dynamic>`. This is correct.

But it has an unfortunate consequence, it means that when `dynamic` is marked exact nullable (by assigning `null` to the list index), that exact nullability is propagated upstream, and that is currently not stopped in any way from marking the parameter `T` as exact nullable.

We therefore get ``void f(T t)` which is unnecessary.

Related to https://github.com/dart-lang/sdk/issues/40551

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
