### ISSUE TITLE
NNBD: Analyzer throws unexpected compile error for NNBD_TOP_MERGE(Never, Never)

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40554]
Dart VM version: 2.8.0-edge.aadcb4418b1a7ccbb74a7cc925ad55020ce4a924 (Thu Feb 6 02:00:49 2020 +0000) on "linux_x64"

Please run the following example:
``` dart
class A<T> {}

class B extends A<Never> {}
class C extends A<Never> {}

class D extends B implements C {}

void main() {}
```
It passes with dart both with nnbd turned on and off.

Analyzer passes with the same example when nnbd is off and throws unexpected compile error when nnbd is on.

Sample output is:
> $  dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error • The class 'D' cannot implement both 'A<Never>' and 'A<Never>' because the type arguments are different. • test.dart:6:1 • conflicting_generic_interfaces
> 1 error found.
> $  dart --enable-experiment=non-nullable test.dart
> $  dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143249
