### ISSUE TITLE
Consider a --machine or --no-backwards-compat mode for dartdev commands

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#40567]
(Based on my understanding) To maintain backwards compatibility, the Dart command will check for a local file matching the name of a sub-command before executing it.

While this is necessary for command line usage, tools which embed dart functionality may need to disable this behavior. This prevents locally checked in files with names matching the sub-command from breaking tooling functionality in unexpected ways.

Example: User has non-dart file named `format` in cwd. Flutter tool calls `dartfmt` through `dart format` in directory, ends up executing incorrect file and crashing.

@bkonyi

**Comment by a-siva** [comment]
Maybe we should discuss in the original dartdev proposal as to whether it is ok to make the breaking change of first matching the name of a sub-command and if not found execute the local file.
Adding another option to me seems like an overkill.

**Comment by bkonyi** [comment]
> Maybe we should discuss in the original dartdev proposal as to whether it is ok to make the breaking change of first matching the name of a sub-command and if not found execute the local file.
> Adding another option to me seems like an overkill.

That's probably the best bet. I'll make a comment on the doc.

**Comment by bkonyi** [comment]
The standalone VM now has a `--disable-dart-dev` flag which will allow for pre-dartdev behavior.
