### ISSUE TITLE
Migrate analyzer to the latest package_config

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40569]
This unblocks users of package:test to get the latest version.

Note that this will likely be blocked on the entire SDK migrating - including rolling in external DEPS once they have migrated.

I am filing a meta issue on package:test which I will link this to.

**Comment by devoncarew** [comment]
@jakemac53 - it looks like `package: package_config` is on the latest commit in the sdk DEPS file. I assume that means that there's no more work for the analyzer here?
