### ISSUE TITLE
RegExp group capture problem

### ISSUE THREAD

**Issue by ismlsmile** [dart-lang/sdk#40561]
I am using dart 2.8.0-dev5.0, Here is the example:

void main(List<String> arguments) {
  String pattern = "D(\\d+)";
  String content = "D1D2D3";

  RegExp exp = new RegExp(pattern);
  Iterable<RegExpMatch> arMatch = exp.allMatches(content);
  for (int i = 0; i < arMatch.length; ++i)
  {
    RegExpMatch match = arMatch.elementAt(i);

    for (int j = 0; j < match.groupCount; ++j)
    {
      // The Value here is "D1", "D2", "D3", but not contain "1", "2", "3"
      String group = match.group(j);

      print(group);
    }
  }
}

How to get the needed result: "1", "2", "3" ?

**Comment by julemand101** [comment]
Something like this?
```
void main(List arguments) {
  final exp = RegExp(r'D((\d+))');
  final arMatch = exp.allMatches('D1D2D3');

  for (final match in arMatch)
  {
    print('Capture Group 0: ${match.group(0)}');
    print('Capture Group 1: ${match.group(1)}');
  }
}
```

This will print:
```
Capture Group 0: D1
Capture Group 1: 1
Capture Group 0: D2
Capture Group 1: 2
Capture Group 0: D3
Capture Group 1: 3
```

**Comment by vsmenon** [comment]
Thanks @julemand101 

Closing as I don't think there is an sdk bug / issue here.  ( In general, these are better resources 
for how-to questions:  https://dart.dev/community#join-the-conversation )

**Comment by ismlsmile** [comment]
Thanks for the reply.
But if the regexp syntax in dart is different from other language? In C#, Go, Java, I can just use r'D(\d+)', but in dart I have to use r'D((\d+))', it seems that it is not standart regexp syntax.

**Comment by vsmenon** [comment]
@ismlsmile - please feel free to open a new issue for a language or library feature request.  Thanks!

**Comment by julemand101** [comment]
@ismlsmile - I have updated my answer since it also works with `r'D(\d+)` like other languages.

**Comment by ismlsmile** [comment]
Thanks for the answer. It really works, and now I find where the problem is:
match.groupCount return 1, but I can index 0, and 1
I will open a new issue to see if it is a bug.
