### ISSUE TITLE
Migration should propagate non-null intent through substitution nodes

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40568]
Consider the following program:
```dart
abstract class C {
  void f(List<int/*!*/> x, int y) {
    x.add(y); // (1)
  }
  int/*?*/ g();
  void test() {
    f(<int>[], g()); // (2)
  }
}
```
The correct migration should be to propagate non-null intent up from the call to `x.add` (at (1)) to the type of the argument `y` of `f`, so that a null-check is inserted on the value returned from `g()` at (2).

What happens instead is that a null check is performed on the value of `y` at (1).

The reason this is happening is that in the nullability graph, the return type of `g` points to a substitution node, which in turn points to the type argument of `List` in the declaration of `f`, and the parameter type of `List.add` in the core library.  Both of the nodes pointed to by the substitution node have non-null intent (the former because the core library has already been migrated, and `List.add`'s parameter type doesn't have a `?` in its declaration, the latter because of the explicit hint in the decalaration of `f`).  But nothing is propagating that non-null intent to the substitution node.  So the nullability from the return type of of `g()` gets propagated down through `y` to the substitution node, at which point the migration engine can't figure out a way to resolve the substitution node, so it gives up.  Later, the FixBuilder partly cleans up the mess by inserting the a null check at (1).

What should happen is that during propagation of non-null intent, if we find that both nodes pointed to by a substitution node have non-null intent, we should propagate non-null intent back to the substitution node.

Note that this is similar to #40509, except that it concerns substitution nodes rather than ordinary nodes.

**Comment by srawlins** [comment]
This has been fixed. The current migration is as Paul describes.
