### ISSUE TITLE
ReplaceNullWithClosureTest.test_named_withArgs fails with NNBD SDK

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#40578]
https://dart-review.googlesource.com/c/sdk/+/135241 will re-land `MockSdk` which is closer to what NNBD SDK is, in particular, `String.splitMapJoin` uses generic function typed parameters. This break codegen for the quick fix.

@bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/138140
