### ISSUE TITLE
RegExp match.groupCount problem

### ISSUE THREAD

**Issue by ismlsmile** [dart-lang/sdk#40575]
example code:
void main(List<String> arguments) {
  RegExp exp = RegExp(r'D(\d+)');
  Iterable arMatch = exp.allMatches('D1D2D3');
  for (final match in arMatch)
  {
    print('Capture Group Count: ${match.groupCount}');
    print('Capture Group 0: ${match.group(0)}');
    print('Capture Group 1: ${match.group(1)}');
  }
}

result:
Capture Group Count: 1
Capture Group 0: D1
Capture Group 1: 1
Capture Group Count: 1
Capture Group 0: D2
Capture Group 1: 2
Capture Group Count: 1
Capture Group 0: D3
Capture Group 1: 3

the match.groupCount is 1, but I can index 0 and 1. Is it a bug?

**Comment by julemand101** [comment]
It works by design (I think based on how I read the documentation). If you read the documentation for `groupCount` property:

> Returns the number of captured groups in the match.
> 
> Some patterns may capture parts of the input that was used to compute the full match. This is the number of captured groups, **which is also the maximal allowed argument to the group method**.

The reason why can be found in the documentation for the `group` method:

> Returns the string matched by the given group.
> 
> **If group is 0, returns the match of the pattern.**

So the value `0` is special since it will not return the result from any group but instead the match. Therefore if `groupCount` is e.g. `1` then the max value we can insert into the `group` method is `1`. `groupCount` should therefore not be used like the `length` property of lists.

This can also be showed in the following example where I specify that the `(\d+)` should be a Non-capturing group:

```dart
void main(List arguments) {
  final exp = RegExp(r'D(\d+)');
  final arMatch = exp.allMatches('D1D2D3');

  print('Normal capture group:');
  for (final match in arMatch) {
    print('\tCapture Group 0: ${match.group(0)}');
    print('\tCapture Group 1: ${match.group(1)}');
    print('\tGroup Count: ${match.groupCount}');
  }

  final expNonCapture = RegExp(r'D(?:\d+)');
  final arMatchNonCapture = expNonCapture.allMatches('D1D2D3');

  print('\nNon-capture group');
  for (final match in arMatchNonCapture) {
    print('\tCapture Group 0: ${match.group(0)}');
    print('\tGroup Count: ${match.groupCount}');
  }
}
```

Which gives the following result:
```
Normal capture group:
	Capture Group 0: D1
	Capture Group 1: 1
	Group Count: 1
	Capture Group 0: D2
	Capture Group 1: 2
	Group Count: 1
	Capture Group 0: D3
	Capture Group 1: 3
	Group Count: 1

Non-capture group
	Capture Group 0: D1
	Group Count: 0
	Capture Group 0: D2
	Group Count: 0
	Capture Group 0: D3
	Group Count: 0
```

As you can see, even if `groupCount` is `0` we can still get the match with `match.group(0)`.

**Comment by ismlsmile** [comment]
Yes, it is correct according the document.
I find this problem because I used to write Java, C#, Go, they all return 2 at match.groupCount, but in dart it is 1. It is a little strange.

This problem is not a big problem when you know what the match.groupCount means. But it maybe confuses some starters switched from other languages.

**Comment by julemand101** [comment]
Not sure about other languages but for Java it looks to be the same as Dart:

> Returns the number of capturing groups in this matcher's pattern.
> 
> Group zero denotes the entire pattern by convention. It is not included in this count.
> 
> **Any non-negative integer smaller than or equal** to the value returned by this method is guaranteed to be a valid group index for this matcher. 
https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#groupCount()

And:

> Capturing groups are indexed from left to right, **starting at one**. **Group zero** denotes the entire pattern, so the expression m.group(0) is equivalent to m.group().
https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#group(int)

**Comment by ismlsmile** [comment]
I am sorry, I confused my memory, Dart is same as Java, and C# itself do some trick. 
Thanks for all the reply. It is my fault.
