### ISSUE TITLE
Failures on Steel thread through fantasyland.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#40570]
There are new test failures on [Steel thread through fantasyland.](https://github.com/dart-lang/sdk/commit/7869bc39c6c7a57fb222ffc7ea2bc51c872bd4d1).

The tests
```
pkg/nnbd_migration/test/fantasyland/fantasy_workspace_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/135180

**Comment by jcollins-g** [comment]
This should be fixed now.
