### ISSUE TITLE
Provide an alternative to Catapult for displaying timelines

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#40574]
As of Chrome v80, Catapult has ceased operating as an embeddable tool and is now only (temporarily?) accessible through `chrome://trace`. This means that Observatory now effectively has no way to display an embedded timeline view.

We have a few options to move forward here:

- We direct users to save their timeline via the timeline page and have them import their trace into `chrome://trace` manually
- We create a custom timeline view that has feature parity with the Catapult viewer
- The DevTools timeline view can be brought to feature parity with the Catapult viewer and:
  - We direct users to perform timeline analysis solely in DevTools
  - We find a way to import the DevTools timeline view into Observatory (likely difficult or impossible as DevTools is using Flutter now)
  - We also bring DevTools to feature parity with Observatory, with VM debugging features made available via an 'advanced mode' toggle, and replace Observatory with DevTools as the pre-packaged developer tooling (this would obviously require some serious discussion between the VM and DevTools teams as to how this would look)

I'm marking this as a P0 as timeline inspection through Catapult is core functionality and will require a fix or reasonable alternative as soon as possible.

VM team cc/ @a-siva @rmacnak-google 
DevTools team cc/ @devoncarew @jacob314 @kenzieschmoll

**Comment by mraleph** [comment]
There is also Perfetto - which is what chrome://tracing is going to be replaced with (AFAIK targeting EOY 2020)

I don't know how embeddable - but I suggest we evaluate using Perfetto instead of trying to build our own feature complete trace viewer.

**Comment by bkonyi** [comment]
Dropping the priority of this as @rmacnak-google might have a temporary fix. We'll still need to determine an alternative sooner than later as Catapult displays a message stating that some features may stop working.

@mraleph while that would be the best solution, EOY 2020 is still a long ways off and it's unclear what the embedding situation will look like (the docs are listed as a [WIP](https://www.perfetto.dev/#/embedder-guide.md)). We'd be taking a gamble waiting for Perfetto to make progress on its embedding story, especially if Catapult is broken with no workaround before Perfetto is ready.

In addition, I don't think it would be a bad idea to improve timeline functionality in DevTools in general. What's there right now is very tailored to single isolate Flutter applications, and since we're generally guiding developers to use DevTools rather than Observatory we might want to start thinking about porting important functionality to DevTools. Providing a fully featured timeline viewer for more advanced use cases would be a usability win for DevTools and would save us from having to tell users to use a separate tools for different functionality,

**Comment by devoncarew** [comment]
> In addition, I don't think it would be a bad idea to improve timeline functionality in DevTools in general. What's there right now is very tailored to single isolate Flutter applications, and since we're generally guiding developers to use DevTools rather than Observatory we might want to start thinking about porting important functionality to DevTools. Providing a fully featured timeline viewer for more advanced use cases would be a usability win for DevTools and would save us from having to tell users to use a separate tools for different functionality,

I would definitely be good to know about any feature gaps - we'd like to make sure the timeline viewer in devtools serves the needs of both typical users aa well as power users.

> with VM debugging features made available via an 'advanced mode' toggle

I think this could work - we're already planning to have framework specific sub-pages that are only visible under certain criteria. It would definitely be possible to have more advanced pages that wouldn't be visible to general users (that you'd need to opt-in to, or enable via an advanced mode).

The codebase is well on its way to being 100% flutter web, so would be pretty easy to work on.

**Comment by devoncarew** [comment]
Is this still a P1? Triaging to a P2.

**Comment by bkonyi** [comment]
Let's knock this down to P3. Observatory -> DevTools migration work will hopefully start soon so this isn't as pressing of an issue.

**Comment by kenzieschmoll** [comment]
DevTools should be closer to feature parity with Observatory now than when this issue was filed. Would be good to know what feature gaps still exist. I met with @chinmaygarde recently to discuss feature gaps for diagnosing flutter perf problems and other features important to Flutter engine folks. We should do something similar to create a burndown list of items that are important to vm folks.

**Comment by bkonyi** [comment]
Closing since Catapult is still working and DevTools has a more fully featured timeline viewer at this point. Remaining feature gaps will be identified as part of the Observatory migration effort.
