### ISSUE TITLE
Wrapping C representations of Optional/List types

### ISSUE THREAD

**Issue by mqnfred** [dart-lang/sdk#40577]
Hello friends!

Thank you for working on dart ffi. I am unsure whether this is the right place to post this. Please redirect me if it is not.

I am currently trying to write a code generator for rust-dart compatibility. I am encountering problems when it comes to representing FFI `Optional`/`List` types as native dart types.

Consider the following C structs. This is how I represent a user who has to have a birthday:

```C
struct User {
        char* name;
        Date* birthday;
}

struct Date {
        int year;
        int month;
        int day;
}
```

I do not embed the `Date` struct directly, which allows me to build the same hierarchy in Dart easily:

```Dart
class User extends ffi.Struct {
    ffi.Pointer<ffi.Utf8> name;
    ffi.Pointer<Date> _birthday;
    Date get birthday => _birthday.ref;
}

class Date extends ffi.Struct {
    @ffi.Uint32()
    int year;

    @ffi.Uint32()
    int month;

    @ffi.Uint32()
    int day;
}
```

To clarify, in my generated dart code, I expect the user to manipulate references (the `Date` class extending `ffi.Struct`) and guarantee that all provided structs are non-nil. The `birthday` getter is the one relying on this assumption, allowing us to manipulate `Date` instead of `ffi.Pointer<Date>`.

Now, I have to introduce options. Since I represent optionals as pointers to the contained data, I pretty much get this `User` struct:

```C
struct User {
        char* name;
        Date** birthday;
}
```

The Dart equivalent would look like this:

```Dart
class User extends ffi.Struct {
    ffi.Pointer<ffi.Utf8> name;
    ffi.Pointer<ffi.Pointer<Date>> birthday;
}
```

Now, I would like the interfacing to be transparent to the developer, which means I am uncomfortable with giving a `ffi.Pointer` object for the user of the library to handle. How can one wrap the dart code above to get a usage like this?

```Dart
void main() {
    // var user = ...
    Option<Date> birthday = user.birthday;
    if birthday.is_some() {
        Date birthday_for_sure = birthday.unwrap();
        print(birthday_for_sure.year);
    }
}
```

I have been trying to solve this for a few days but I am not managing to formulate a type-safe solution without generating one `OptionDate` for each type, which is obviously not going to cut it.

I believe the problem is very similar when it comes to lists, which makes me feel like this is more about templating/generics than anything else, and that maybe the language is not suited to what I am trying to do? If that's the case, what would be another, more idiomatic approach?

Thank you for taking the time to read this far,
Cheers

**Comment by mraleph** [comment]
All Dart types are currently more or less equivalent to Rust's `Option<T>` because Dart types are all nullable. So right now the most natural representation of `Option<Date>` in Dart is just Date. Without non-nullable types there is no type safe way to represent the distinction between non-nullable Date and nullable date. 

In future when NNDB transition is complete you would be able to do what you want by using `Date?` as an equivalent of `Option<Date>` and `Date` as equivalent of `&Date`.
 
I would like to also point to the fact that you don't need `Date** birthday;` to represent optional birthday field, because C pointers are nullable. which means `Date* birthday` is already good enough to represent it.

**Comment by mqnfred** [comment]
Thank you very much Vyacheslav for taking the time to answer! I think you are right when it comes to the `Date*` aspect, I am still in the MVP phase however so I am leaving out some of those inefficiencies for now on purpose.

When it comes to optionals, it looks like I will have to make peace with not having it reflected in the type system on the Dart side. Oh well! I have implemented the feature and it is working well. Thank you for that analysis. Do you know when the NNDB will be complete? I took a few glances online but there was nothing conclusive.

The silly thing that still gets me is how to wrap vectors properly. I have a `Vec` type on the rust side, that I represent as a:

```C
struct Array {
    int len;
    void *contents;
}
```

On the Dart side, to mirror this, we would have a:

```Dart
class Array extends ffi.Struct {
    @ffi.Uint32() int len;
    ffi.Pointer<ffi.Void> contents;
}
```

I cannot really extend array, as it looks like classes deriving `ffi.Struct` are not "parametrizable"? (`Array<T extends ffi.NativeType>` maybe?) I am really struggling to get this look:

```Dart
void main() {
    // var user = ...
    List<User> users = get_users();
    for (User u in users) {
        print(u.name);
    }
}
```

Is this doable? I feel like I need to parametrize against something that extends like `ffi.NativeType` but I am struggling to find the cleanest, least redundant solution (can I avoid `ListString`, `ListStruct`, `ListInt32` etc?)

Thanks again for your time, it is helping me make a lot of progress in Dart!

**Comment by mraleph** [comment]
> Do you know when the NNDB will be complete?

We usually don't commit to any concrete schedules externally. 

> Is this doable? I feel like I need to parametrize against something that extends like ffi.NativeType but I am struggling to find the cleanest, least redundant solution (can I avoid ListString, ListStruct, ListInt32 etc?)

Unfortunately I don't really see a good way to do it - you can reduce code duplication by wrapping core functionality in few base classes and using inheritance. The core of the problem is that we don't have generic way of reading and writing primitive types, e.g. you can write something like

```
T read<T extends PrimitiveType>(Pointer<T> p) {
  return p.value;
}
```

Which is pretty intentional due to how Dart generics work.

So certain level of duplication is unavoidable.

**Comment by mqnfred** [comment]
Thank you for taking the time to educate me, @mraleph. I have introduced the required code duplication and it works fine right now!
