### ISSUE TITLE
Analyzer CLI appears to ignore --packages flag

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40572]
@munificent, @scheglov, and I are currently trying to get the test bots to test the legacy tests with the NNBD SDK.  In this test configuration, the analyzer gets invoked like this: `DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/usr/local/google/home/paulberry/dart-new/sdk/.packages --format=machine --no-hints /usr/local/google/home/paulberry/dart-new/sdk/out/ReleaseX64NNBD/generated_tests/corelib_2/bigint_test_08.dart`

Based on the text of https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md, we would expect the analyzer to do the following:
- Look for a file at `/usr/local/google/home/paulberry/dart-new/sdk/.packages`.  (Under the current state of the SDK repo, it will find an old-style .packages file there)
- Assuming it finds an old-style packages file there, it should then look for a new-style package config file at `/usr/local/google/home/paulberry/dart-new/sdk/.dart_tool/package_config.json`.  (Under the current state of the SDK repo, it will find nothing there)
- If it finds nothing there, it should use the file at `/usr/local/google/home/paulberry/dart-new/sdk/.packages`.

But if I add print statements to the analyzer's `findPackagesFrom` method, I can see that it's going and looking for a `.packages` or `.dart_tool/package_config.json` file starting at `/usr/local/google/home/paulberry/dart-new/sdk/out/ReleaseX64NNBD/generated_tests/corelib_2/bigint_test_08.dart`, and then proceeding to ancestors until it finds one (which it finds at `/usr/local/google/home/paulberry/dart-new/sdk/out/ReleaseX64NNBD/generated_tests/.dart_tool/package_config.json`).  If I also add print statements to `FeatureSetProvider.getFeatureSet`, I can see that it's using this file to decide whether the file it's analyzing should be opted in to NNBD or not.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135188 will update analyzer_cli to handle `--packages`.

**Comment by stereotype441** [comment]
Fixed by abf7d1fc08458a77770bf5bc467fccdb4fcdfe02
