### ISSUE TITLE
Failures on [tests] Add tests for generic function type bounds with null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#40584]
I am adding new tests for generic function type tests with null safety. There are new test failures on [[tests] Add tests for generic function type bounds with null safety](https://dart-review.googlesource.com/c/sdk/+/134867).

The tests
```
language/nnbd/subtyping/function_type_bounds_weak_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

**Comment by crelier** [comment]
I am not able to reproduce this failure. It must have been fixed at some time.
