### ISSUE TITLE
Completion not working on parameters of function references

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40588]
Check this code:

![image](https://user-images.githubusercontent.com/1146982/74276593-c475b100-4cf4-11ea-932e-dcfb24e2308b.png)

`aFunction` simply returns a function. When I invoke the "show parameters" action form Intellij, it doesn't know the parameters I should be passing. 

If I try to auto complete it suggets me random stuff:

![image](https://user-images.githubusercontent.com/1146982/74276629-d5bebd80-4cf4-11ea-8bca-f03b8f6f06b1.png)

This is my piece of code:

```dart
void Function(int, String) aFunction() {
  return (theInt, theString) {
    print('CALLED ME!');
  };
}

void main(List<String> arguments) async {
  var value = 1;
  var text = 'asda';

  final theFunction = aFunction();

  theFunction();
}
```

The missing of the parameters is a bit of pain when working with `dart ffi`, since all you have are function references to the equivalents on C++ language, like: 
```dart
final int Function(int x, int y) nativeAdd =
  nativeAddLib
    .lookup<NativeFunction<Int32 Function(Int32, Int32)>>("native_add")
    .asFunction();
```

Another one for @pq ?

**Comment by AntonBlomstrom** [comment]
Is this related to why there isn't code completion for something like:
`typedef func = void Function({int val});`?
Or am I doing something wrong here?
![image](https://user-images.githubusercontent.com/39986991/77956719-aed33f80-72d2-11ea-883d-25ea78917caf.png)
![image](https://user-images.githubusercontent.com/39986991/77956813-cf9b9500-72d2-11ea-8da6-089f36883ccc.png)

**Comment by bwilkerson** [comment]
> If I try to auto complete it suggets me random stuff:

I'm not sure what you were expecting to see (or not see) that differs from what's in the list.

@jwren The OP wrote

> When I invoke the "show parameters" action form Intellij, it doesn't know the parameters I should be passing.

Do we currently have support for "Parameter Info"? If so, which server API does that use.

**Comment by shinayser** [comment]
> I'm not sure what you were expecting to see (or not see) that differs from what's in the list.
> 

I was especting to see suggestions for the int and String parameters.

**Comment by bwilkerson** [comment]
Sorry, I wasn't clear. I can reproduce the failure to display parameter info and followed up jwren to try to figure out why. I was trying to as you about the code completion case where it's suggesting `value` for the first argument, which seems like a valid suggestion.

**Comment by scheglov** [comment]
@bwilkerson Yes, `value` is in suggestions, but the point is that suggestions are not prioritized by types, `theFunction` has type `void Function(int, String)`, so the context type for the first arguments is `int`. However we see that `arguments` was suggested. Which tells me that we don't know context types, i.e. don't know formal parameters of `theFunction`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356480
