### ISSUE TITLE
pkg/analysis_server/test/client/completion_driver_test fails on Windows

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#40583]
See [the log](https://dart-ci.appspot.com/log/analyzer-win-release/analyzer-unittest-asserts-release-win/8989/pkg/analysis_server/test/client/completion_driver_test).

How to test on Mac.
1. Open `ResourceProviderMixin`, and change `resourceProvider`:
```dart
  MemoryResourceProvider resourceProvider = MemoryResourceProvider(context: windows);
```
2. Run the test.

@bwilkerson @pq

**Comment by pq** [comment]
Whoops.  Taking a look.  Thanks!

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/135345

@scheglov: is this the right try-job?:

![image](https://user-images.githubusercontent.com/67586/74268817-5bbf1200-4cbd-11ea-9a5a-17061ebe6f05.png)


(And if so, why don't we have it enabled by default? 🤔 )

**Comment by scheglov** [comment]
Yes, I think this is the right bot name.
It is not enable by default probably because it is slow.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/42e840c6ae6c7ce3f4283225ea046dabd3870e45.
