### ISSUE TITLE
Exact nullability is not described well in migration ux

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40587]
This is an unspecific issue noting that I have experienced this a lot looking at the migration tool.

There are also issues with reading the graph after solve in an attempt to figure out where exact nullabilities case from. This may be fixable by implementing root causes. Currently we show nullability explanations that we should not, but hiding them hides nullability explanations that should not be hidden.

**Comment by stereotype441** [comment]
We've switched over to describing nullability reasons using a "stacktrace-like" view, which does handle exact nullabilities well.  So I believe this issue is addressed.
