### ISSUE TITLE
Migration tool: Remove or fix exact nullability

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40586]
We are disabling exact nullability because we currently don't have a good way to test its usefulness, and we've found a few bugs in it over time.

We need to either remove it or fix these bugs or figure out a different design, etc.

**Comment by MichaelRFairhurst** [comment]
Previous exact nullable issues as well that have come up but been fixed: #40181

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
