### ISSUE TITLE
Add support for automatic debug assertion insertion to the CFE

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40597]
There's a [section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#automatic-debug-assertion-insertion) in the spec that describes insertion of assert statements for debug purposes.  This functionality may be supported by the CFE and enabled on a per-target basis.

Context: https://dart-review.googlesource.com/c/sdk/+/135320

**Comment by johnniwinther** [comment]
Putting this on backlog until the new rules for strong mode as pure strong mode arrives. This change might not be necessary.

**Comment by johnniwinther** [comment]
Backends are added the necessary assertions.
