### ISSUE TITLE
Failures on Reland "Implementation of evaluation to JS in frontend server"

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#40592]
There are new test failures on [filtering on kinds; relevance boosting...Reland "Implementation of evaluation to JS in frontend server"](https://github.com/dart-lang/sdk/compare/25559399edd169a579597e06e68a78979ddd2746~...b9fbf58e33735c6462750b6f3b53111b5265b518).

The tests
```
pkg/frontend_server/test/src/expression_compiler_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

**Comment by devoncarew** [comment]
@annagrin, when opening an issue, can you assign it an `area-` label (if you know the right area)? That'll make the job of the issue triages easier; thanks!
