### ISSUE TITLE
lib/mirrors/ tests are not NNBD clean

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#40591]
@rmacnak-google @bkonyi 

https://github.com/dart-lang/sdk/commit/0fde59b21d43456b7ce1f2c3101ea0e217dd4b87 breaks analyzer NNBD bots: analyzer-asserts-strong-linux and analyzer-asserts-weak-linux

See https://dart-ci.firebaseapp.com/#showLatestFailures=true&showUnapprovedOnly=true&configurationGroups=unittest,analyzer

For example: https://dart-ci.appspot.com/log/analyzer-nnbd-linux-release/analyzer-asserts-strong-linux/1373/lib/mirrors/instance_members_easier_test

**Comment by a-siva** [comment]
At this point we have no plans for making dart:mirrors library or it's tests account for nullability.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for dart:mirrors
