### ISSUE TITLE
VM garden, FlowGraphCompiler::GenerateStaticDartCall failed 

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/sdk#40593]
VM-kernel-mac-debug bots failed.

Here are logs:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8888711249094170464/+/steps/test_results/0/logs/new_test_failures__logs_/0

@sjindel-google

**Comment by ZichangG** [comment]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8888710957169301696/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by mkustermann** [comment]
@sjindel-google This probably started with your change in e5a22713b1b7d4cb539b8f0b719e46bb39630292
