### ISSUE TITLE
Sometimes CFE incorrectly complains about not definitely unassigned late local variable

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40601]
In the following program local variable `value` isn't assigned before it's used, but according to the spec that shouldn't be treated as an error at compile time.

```dart
abstract class A<T> {
  T baz();
  bar(T value) {}
  foo() {
    late T value;
    var result = () => bar(value);
    (() { value = baz(); })();
    return result;
  }
}
```

Currently, the CFE produces the following error: `Error: Non-nullable variable 'value' must be assigned before it can be used.`

**Comment by eernstg** [comment]
I actually think this case is covered [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings):

> It is a compile time error to read a local variable marked
> `late` when the variable is definitely unassigned.

**Comment by stefantsov** [comment]
Thanks for the comment!  Indeed, the initial example should result in an error reported by the compiler.  I've updated the example, so that the local variable is not definitely unassigned.
