### ISSUE TITLE
Analyzer tests use `factory something() => null;` as test code.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40603]
With null-safety, a factory can no longer return `null`. The implicit return type is non-nullable, so all these factory constructors become invalid code. The tests need to be fixed before the code can be migrated to null safety.

Example from pkg/analysis_server/test/analysis/notification_highlights2_test.dart:  
```dart
factory A() => null;
```

Other occurrences are in the `mock_sdk.dart` library

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/135532

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/137422
