### ISSUE TITLE
Analyzer doesn't recognize upgrading language version for existing classes/extensions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40609]
The repro here is a bit weird, but you can do the following:

1. Create a new package with the following pubspec.yaml file, and open it in vscode (probably works with anything using analysis server):

```yaml
name: hello
environment:
  sdk: '>=2.0.0 <3.0.0'
```

2. Run `pub get` (you must do this first).

3. Create `lib/dog.dart` with these contents

```dart
class Dog {}

extension Bark on Dog {
  void bark() => print('woof');
}
```

This correctly shows an error - our min SDK does not support extension methods.

4. Update sdk constraint in the pubspec to `>=2.7.0 <3.0.0` 

The analyzer will still say that the experiment is not enabled.

I also tried re-running pub get (to update the packag_config.json language version), as well as reloading the window to restart the analyzer (ctrl+shift+p then search for reload window).

I can create new classes and use extensions, but any pre-existing extensions will complain no matter what I do, so it seems that the error is cached somewhere.

EDIT: it appears making any actual edit to the file will resolve the issue as well - but undoing that edit will get me back to the old error. So likely some cache by content hash of the file is not getting invalidated?

**Comment by jakemac53** [comment]
cc @scheglov @stereotype441

**Comment by scheglov** [comment]
Coincidentally @kevmoo also ran into this issue.
https://dart-review.googlesource.com/c/sdk/+/135500 should fix it.

**Comment by scheglov** [comment]
The CL landed.
