### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by kevosbash** [dart-lang/sdk#40608]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.7.1`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v5.3.0-28-generic, screens 1366x768`

**Comment by devoncarew** [comment]
Closing this as it doesn't contain any crash info; please re-open if you do see this again or have additional info.
