### ISSUE TITLE
Have a way to get the current stack trace without throwing exceptions.

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#4061]
There's currently no way to get the full, current stack trace. This means that there's also no way for an asynchronous method to give an accurate stack trace when it has an error. For example:

&nbsp;&nbsp;Future&lt;String&gt; getLinks(String url) {
&nbsp;&nbsp;&nbsp;&nbsp;return fetchPage(url).transform((html) =&gt; parseLinks(html));
&nbsp;&nbsp;}

Now suppose fetchPage detects an error asynchronously and wants to display a stack trace for that error. A useful stack trace would show that it had originally been called by getLinks, but there's no way for it to know that.

**Comment by kevmoo** [comment]
Never say never - https://github.com/dart-lang/sdk/commit/027b8dca39a753a95b01a9845d4fc5f7cd08be1a
