### ISSUE TITLE
Lambda completion should be invoked by user

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40616]
A follow up for https://github.com/dart-lang/sdk/issues/40013 as requested by @pq on https://github.com/dart-lang/sdk/issues/40013#issuecomment-585747269

The lastest implementations for lambda completion caused a problem on usability.
Since Dart is a functional language, we often pass other functions as parameters to functions and this lambda auto-completion is causing a usability problem, becuase it auto inserts a lambda without being request by the user.

My proposal is that it should be invoked by the user instead of auto-inserting the lambdas.
It could also suggest arrow functions or block functions, like: `(e) =>` or `(e) { }` as desired by the user.

**Comment by pq** [comment]
Thanks for opening this @shinayser!

**Comment by shinayser** [comment]
Hey @pq have you guys already discussed anything about this issue?

**Comment by pq** [comment]
Hey @shinayser.  We haven't made any progress just yet but are looking at improvements.  You're continue feedback is definitely appreciated!

**Comment by scheglov** [comment]
Related to https://github.com/dart-lang/sdk/issues/35272 (mostly a note to myself)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/355824
