### ISSUE TITLE
List.shuffle seems to leak a midway stage

### ISSUE THREAD

**Issue by joyfulmantis** [dart-lang/sdk#40617]
Dart Version: 2.7.0

Steps:
1. Have FutureBuilder to wait on a future List of items
2. In the snapshot.hasData if block run snapshot.data.shuffle
3. Pass that snapshot.data on to a new view
4. In the new view displaying the first item in the List.
5. Change state not related to the List.
6. Which causes a rebuild again displaying the first item in the list -- but it's a different item than in 4

Expected Behavior:
Step 4 and 6 the first element of the list should be the same.

I also commented out the snapshot.data.shuffle line to isolate the problem. When the line is commented out 4 and 6 display the same data.

**Comment by devoncarew** [comment]
Thanks for the report! Could you post a snippet of source code showing the issue? That would help us to triage; thanks.

**Comment by joyfulmantis** [comment]
Yep, I made a demo flutter app that exhibits the bug. Check it out the relevant bit at https://github.com/joyfulmantis/dartbugdemo/blob/master/lib/main.dart I am also attaching images of the demonstration below
![微信图片_20200214173638](https://user-images.githubusercontent.com/5304496/74519490-c176fc80-4f50-11ea-8436-6817be107c51.jpg)
![微信图片_20200214173651](https://user-images.githubusercontent.com/5304496/74519497-c340c000-4f50-11ea-9277-3c134572f121.jpg)
![微信图片_20200214173656](https://user-images.githubusercontent.com/5304496/74519500-c3d95680-4f50-11ea-9770-64379219d4b6.jpg)

**Comment by lrhn** [comment]
I'm guessing this is not a plain Dart list. Are you shuffling an `ObservableList`? If so, it's an issue with that, not the default `List.shuffle` implementation.
