### ISSUE TITLE
Migrate lib_2/html tests off unittest

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40628]
The unittest package has been deprecated for ages. We hoped to eliminate it during the Dart 2.0 test migration but didn't have the time and instead made it strong mode clean. I don't think we want to do that *again* and make it NNBD clean. It's time for it to die.

@srujzs has started on this migration. In many cases, it's as simple as replacing an import of "package:unittest/unittest.dart" with "package:expect/minitest.dart". However, there are some tendrils connecting unittest to the test runner. The test runner specifically looks for `useHtmlIndividualConfiguration()` in test files and treats those specially. There is something around `group()` calls too. That needs to be figured out and removed or replaced with something else.

Unless we migrate unittest to NNBD (which I hope we don't do), we'll need to get this done in order to be able to run all the SDK tests in NNBD strong mode.

**Comment by munificent** [comment]
I filed separate tracking bugs for the isolate and observatory and isolate tests, so renaming this to scope down to just web tests, which are the only other tests using unittest.

**Comment by srujzs** [comment]
The tests have been migrated off, not sure if there's any dependencies/code left to remove.

**Comment by munificent** [comment]
Eventually there is some other clean-up we can do, but that covers this tracking issue.
