### ISSUE TITLE
Migration: Async function returns shouldn't be marked uncheckable

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40621]
```dart
Future<int/*1*/> f(int/*2*/ x) async => x;
```

At the moment, we create an uncheckable edge from `int/*2*/` to `int/*1*/`. This is not correct. Clearly we can check this edge. As long as this bug exists, its possible to make 2 nullable just because 1 is marked exact nullable.

I'm not sure if its realistically possible if even at all likely, for node 1 to become marked exact nullable anyway.

Other concerns are what might happen when non-null intents get involved.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
