### ISSUE TITLE
Uncheckable edges does not perfectly capture "exact nullability"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40625]
Uncheckable edges mostly correctly cover exact nullability, but don't necessarily do so with perfect results.

Here are some examples of where it can go wrong:

```dart
int/*1*/ Function(String/*2*/) f1;
int/*3*/ Function(String/*4*/) f2 = f1;
```

Here we create uncheckable edges from 1 -> 3 and 4 -> 2. If 2 or 3 were to become exact nullable, this could become messed up.

Trying to reproduce this, I cannot.

```dart
typedef F<T> = T Function(String);
int? Function(String) f1; // return type made nullable for no reason
F<int?> f2 = f1;
f2 = (_) => null; // exact nullability induced here
```

or:

```dart
typedef F<T> = int Function(T);
F<String?> f1;
f1(null); // induce exact nullability
int Function(String?) f2 = f1; // parameter made nullable for no reason
```

This may one day be an issue, so I'm filing & closing this to link from the code in question.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
