### ISSUE TITLE
Migration: exceptions in nnbd_migration should result in non-zero exit code from entry point

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40623]
dartfix currently just ignores server errors, fatal or not.  Exceptions preventing the generation of any fixes should result in dartfix exiting with a non-zero exit code.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
