### ISSUE TITLE
Migration: should not mark casts to type parameter bounds as uncheckable

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40622]
```dart
class C<T extends List<int/*1*/>> {                                                   
  List<int/*2*/> f(T x) => x;
  T g(List<int/*3*/> x) => x;
}
```

This marks the cast from 1 -> 2 as uncheckable, and from 3 -> 1 as uncheckable. That means that if 2 gets marked exact nullable:

```dart
C<...>(...).f().add(null);
```

then in turn 1 will get marked exact nullable, and 3 will get marked exact nullable. This is probably not correct. Perhaps 1 -> 2 being uncheckable is correct, but 3 -> 1 seems flat wrong.

This also could have some effect on how non-null intent is propagated.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
