### ISSUE TITLE
An unmigrated test is running on an NNBD bot

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40638]
The test `dart2js_extra/switch_test/00` expects a compile-time error because of a case block that doesn't end with one of the terminating statements, such as `break`.  Instead, the block contains a call to a function that never returns (it's return type is `Never`).  In NNBD it's allowed to end a case block with such an invocation, so the test should be migrated because it's running on a bot where NNBD is enabled: `dart2js-weak-linux-x64-d8`.

**Comment by sigmundch** [comment]
Ah, we should actually for now opt-out dart2js_extra and dart2js_native (we intended to run these in legacy mode for a while longer until we migrate them over)
