### ISSUE TITLE
Generic function type inference is wrong for ternary expressions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40643]
In the following example, the `foo` function causes a compile time error where the `foo2` function does not. The only difference is one uses a ternary expression and one uses an if/else.

Note that both are accepted by the analyzer and infer the expected type of `Set<T> Function<T>(List<T>)`.

```dart
Set<T> setOf<T>(List<T> baz) => Set.of(baz);
Set<T> toSet<T>(List<T> baz) => baz.toSet();

/// Compile error
Set<T> Function<T>(List<T>) foo(bool bar) => bar ? setOf : toSet;

Set<T> Function<T>(List<T>) foo2(bool bar) {
  if (bar) {
    return setOf;
  } else {
    return toSet;
  }
}
```

The specific error is as follows, tested on the vm and dart2js so it seems like a CFE thing:

```
Error: A value of type 'Set<Object> Function(bottom-type)' can't be assigned to a variable of type 'Set<T> Function<T>(List<T>)'.
 - 'Set' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
 - 'List' is from 'dart:core'.
Set<T> Function<T>(List<T>) foo(bool bar) => bar ? setOf : toSet;
```

I would expect at least the analyzer/cfe to agree here on the type inference - but I am not completely sure which is actually correct :). The analyzer behavior seems more desirable to me.

cc @lrhn @leafpetersen for clarification on the intended behavior here.

**Comment by johnniwinther** [comment]
cc @stefantsov

**Comment by stefantsov** [comment]
This is a known bug that's been around for a while, so fixing it is considered a breaking change.  The current plan is to bundle the fix with the NNBD update.  Right now the code from the example above compiles if the NNBD experiment is enabled and the library is opted in.

A possible work-around for the code that is not opted-in to NNBD is to cast one of the branches to dynamic:

```dart
Set<T> setOf<T>(List<T> baz) => Set.of(baz);
Set<T> toSet<T>(List<T> baz) => baz.toSet();

Set<T> Function<T>(List<T>) foo(bool bar) => bar ? setOf : toSet as dynamic;

Set<T> Function<T>(List<T>) foo2(bool bar) {
  if (bar) {
    return setOf;
  } else {
    return toSet;
  }
}
```

**Comment by jakemac53** [comment]
SGTM, if we have a fix coming with NNBD then I will go ahead and close this
