### ISSUE TITLE
Cannot compile from source

### ISSUE THREAD

**Issue by nico202** [dart-lang/sdk#40651]
Hi, I'm trying to build dart without having to depend on pre-build dart binaries.

Version 1.24.3 works.  Version 2.0.0 requires prebuild binaries.  I tried to use dart-1.24.3 to build it, but it fails
```
output: 'package:kernel/binary/ast_to_binary.dart': error: line 18 pos 40: 'void' not allowed here
class BinaryPrinter implements Visitor<void>, BinarySink {
```

Do you know which commits add this? [found this maybe](https://github.com/dart-lang/sdk/commit/1d44f5296a711c5f60c99a525db1458014c3fe41.patch) Maybe I can patch v1.24.3 to support it and continue v2.0.0 build with it.
I'm downloading releases from https://gsdview.appspot.com/dart-archive/channels/stable/raw/ , and does not seems to exist a release after 1.24.3 and before 2.0.0.  I'm I right?

I'm new to gn, but there's this: dart_executable("dart_bootstrap"). Is this the v2 dart binary that can be used to bootstrap everything? Can I compile it manually?

It's fine to bootstrap a later version too (the aim is to get the current release)

Thanks, Nicolò

**Comment by lrhn** [comment]
Version 1.24.3 is very old by now. You should use a Dart 2.0 or later SDK to get some of the features. For example, Dart 1 did not allow `void` to be used as a type argument, so you cannot write `Visitor<void>` and use a pre-2.0 SDK to compile it.
My guess is that you will find many other changes in the SDK that will not compile with a pre 2.0 compiler. Some might even require later SDK versions.

(I don't know how to get bootstrapping started, though, so I'll defer that to the people who actually know).

**Comment by nico202** [comment]
Thanks, in the following days I'll try each commit between 1.24.3 and 2.0, and hopefully will find one that can bootstrap 2.0.  I'll report my findings here

**Comment by lrhn** [comment]
I think you will be unlikely to find any pre 2.0 release which enables the Dart 2 features that you need (but I won't stop you from trying, maybe you'll be lucky).

**Comment by mraleph** [comment]
We don't currently have a way to bootstrap Dart without running a prebuilt binary, and we are not planning to provide one. It is possible theoretically: we could check in Dart front-end compiled to Kernel which than could be run on newly built VM binary, but this has never came up - so we are not doing it.

**Comment by nico202** [comment]
I wasn't asking you to provide a way, just some help on doing it.  If you know (as you should) [this paper](https://www.win.tue.nl/~aeb/linux/hh/thompson/trust.html), you should know that depending on a pre-built compiler is a big security issue

**Comment by mraleph** [comment]
I think you are missing the point of Ken Thomson's Turing Award Lecture. Yes he did a neat trick hiding his trojan inside a prebuilt compiler. No, it does not mean that if you bootstrap your compiler purely from source you are suddenly much more secure. 

> The moral is obvious. You can't trust code that you did not totally create yourself. (Especially code from companies that employ people like me.) No amount of source-level verification or scrutiny will protect you from using untrusted code
 
There are hundreds of thousands of lines of code which run every time you build Dart SDK. Yes, you can build everything (starting from your OS to C++ compiler) from source. No, it is not going to save you if some of those thousands lines of code are malicious - unless of course you depart on the endeavour of reading every single line of code in the Dart SDK and its dependencies.... but even then malicious code could still hide in a plain sight.

There are reasons why prebuilt binaries are better avoided in bootstrapping (most importantly portability) but security is not one of the valid reasons.

**Comment by nico202** [comment]
That's the difference between making it theoretically possible to read and understand what the code does, and making it practically impossible.  This is the same difference that exists between "open source" (I'm not going to read the whole linux kernel source code, but I could) and closed 

So, what's even the point in "open source"
