### ISSUE TITLE
Migrate runtime/observatory/tests/service/ tests off unittest

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40650]
There are 176 test files in that directory that use the ancient unittest package. That package was deprecated years ago, well before Dart 2.0. It has not been touched or maintained in ages. We do not intend to migrate it to NNBD and would like to completely delete it from the SDK repo.

Ideally, they would be migrated to only use "package:expect/expect.dart" and "package:async_helper/async_helper.dart". If that's too difficult of a migration, the libraries "package:expect/minitest.dart" and "package:async_helper/async_minitest.dart" provide an API that mirrors a subset of the unittest API. Migrating to those should be fairly straightforward.

(I intend to merge "minitest.dart" and "async_minitest.dart" into a single library. If I do, I will update this issue.)

Who owns these tests? Can they own this migration?

@a-siva cc @vsmenon

**Comment by bkonyi** [comment]
Thanks for alerting me to this @alexmarkov. This was resolved a couple of months ago and there's no longer any usages of `package:unittest` in the runtime tests.
