### ISSUE TITLE
html test migrated off of unittest.dart incorrectly

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#40659]
The test lib_2/html/fileapi_entry_test has an async test which wasn't migrated properly to test.
It didn't show up on the linux builder because the test was already failing on that builder, that is why it only showed up on Windows.  It should probably be fixed on both builders.

Log of previous error on linux is https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-weak-linux-release-chrome/1645/lib_2/html/fileapi_entry_test

Log of current error on linux is the same error as on Windows, so you don't need a Windows machine to debug and fix it:
https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-weak-linux-release-chrome/1932/lib_2/html/fileapi_entry_test

@srujzs 

There are new test failures on [Migrate html tests off of unittest.dart](https://github.com/dart-lang/sdk/commit/6ae9dedc60583c19e37866e8079bf7b459df1770).

The tests
```
lib_2/html/fileapi_entry_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-checked-win-release-chrome
```

**Comment by srujzs** [comment]
Thanks for finding and filing this. This should be resolved now with https://dart-review.googlesource.com/c/sdk/+/136480. Running the Windows bots shows the result as passing for this test now.
