### ISSUE TITLE
Request to allow frontend_server to override default values of dart.library.libraryName defines

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#40669]
In https://github.com/dart-lang/sdk/blob/master/pkg/vm/lib/kernel_front_end.dart#L409 , the dart.library.libraryName defines are set to true based on the Kernel target's additionalRequiredLibraries. This is a request to updated the logic to use `??=` instead to allow the frontend_server to override default values.

The intention of this change is to allow the Flutter web on frontend_server workflow to match the old ddc semantics, where dart.library.io and dart.library.isolate evaluated to false

**Comment by jakemac53** [comment]
The core problem here seems to be that frontend_server is calling a vm specific function regardless of the target. This is also setting other vm specific things such as `dart.vm.product`. So, I think the fix should really be in frontend_server to call some other method that isn't vm specific when not compiling for the vm.

**Comment by jonahwilliams** [comment]
Yeah, that sounds like another approach too. We do assume that dart.vm.product is true in "release" modes for flutter, but we also provide that value ourselves too.

**Comment by jakemac53** [comment]
As far as I can tell the modular pipeline only adds explicit `-D` arguments to this map so we can just not call the function at all.

**Comment by jakemac53** [comment]
All other targets extend `VmTarget` so I will wrap this call in an `is VmTarget` check.

**Comment by jakemac53** [comment]
Sent out https://dart-review.googlesource.com/c/sdk/+/136342 which should resolve this

**Comment by aam** [comment]
@jonahwilliams do you have small repro that shows what is broken with `dart.library.io` and `dart.library.isolate` evalauted to `true` for flutter web?

**Comment by jakemac53** [comment]
I made a repro in the `hello_world` example - you can check out my flutter branch here https://github.com/jakemac53/flutter/tree/vm-env-repro, then:

```
cd examples/hello_world
flutter run -d web
```

If you load the app in chrome and look at the console you will see this error:

```
Uncaught (in promise) Error: Unsupported operation: Platform._version
``` 

Because it thinks that `dart.library.io` exists and tries to use it but it throws.

**Comment by aam** [comment]
Aha, thank you!
