### ISSUE TITLE
Breaking Change Request: Don't infer promoted types on local variables

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40675]
## Planned change

Type inference for local variables will not use promoted type variables. 

For instance
```Dart
method<T>(T a, T b) {
  if (a is String) {
    var o = a; // The type of `o` will be `T` and not `T & String`.
    o = b; // Previously an implicit cast `b as T & String` was inserted here.
    o.length; // This is now (correctly) an error since `T` does not have a `.length` property.
  }
}
```

This fixes a bug in the existing implementation that was masked by the support for implicit down casts. 

## Expected Impact
Code that used untyped locals derived from locals with promoted type variable types that _also_ use the untyped local as the promote type will now result in compile-time errors, like this:
```Dart
method<T>(T a, T b) {
  if (a is String) {
    var o = a;
    o.length; // This is now an error since `T` does not have a `.length` property.
  }
}
```
These cases are expected to be rare.

## Mitigation
The fix is to either type the local explicitly, like this:
```Dart
method<T>(T a, T b) {
  if (a is String) {
    String o = a;
    o.length;
  }
}
```
or to explicitly cast the use of the local, like this:
```Dart
method<T>(T a, T b) {
  if (a is String) {
    var o = a;
    (o as String).length;
  }
}
```

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @dgrove @vsmenon for review and approval.

**Comment by Hixie** [comment]
I don't have strong opinions about type inference. LGTM.

**Comment by vsmenon** [comment]
lgtm

**Comment by matanlurey** [comment]
LGTM

**Comment by franklinyow** [comment]
Approved
