### ISSUE TITLE
[Breaking change request] StreamSubscription.cancel can no longer return null

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40676]
# Summary

The [`StreamSubscription.cancel`](https://api.dart.dev/stable/2.7.1/dart-async/StreamSubscription/cancel.html) method's return type is changed to `Future<void>`.

# What is changing:

We change the return type of `StreamSubscription.cancel` to `Future<void>`.
The return type will be *non-nullable* in Null Safe code, and you are not allowed to return `null`.

# Why is this changing?

The [`StreamSubscription.cancel`](https://api.dart.dev/stable/2.7.1/dart-async/StreamSubscription/cancel.html) method currently has a return type of `Future` (aka. `Future<dynamic>`). It allows you to return `null` as well, but this has been discouraged since the release of Dart 1, it's just not something the type system could prevent.

When migrating this method to Null Safety, we have decided to change the return type to `Future<void>` (non-nullable). That means that implementations of the `StreamSubscription` class can no longer return a `null` value, and you can no longer use the value of the returned future without casting the `Future` away from `void` first. 
That is considered reasonable because the future is not intended to contain any useful value.

If a specific user of a specific stream subscription happens to know that that stream subscription's cancel returns a future with a useful value, then that should be reflected by having a sub-class of  stream subscription with a different return type. (Or, as a hack, by casting the `Future<void>` to `Future<dynamic>` or similar before using it).

# Expected impact

The type change disallows code which currently awaits the returned future and uses its value.
That code needs to cast the future to something else first, so the result won't have type `void`.

The non-null part won't be enforced until Null Safety, at which point tools will help find places where `null` is currently returned. That code should then return `Future<Null>.value(null)`.

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @dgrove @vsmenon for review and approval.

**Comment by matanlurey** [comment]
LGTM

**Comment by leafpetersen** [comment]
ping on this.

**Comment by franklinyow** [comment]
Ping again @Hixie @vsmenon

**Comment by Hixie** [comment]
assuming there's no code seriously broken by this, lgtm

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by leafpetersen** [comment]
This has landed in bleeding edge.
