### ISSUE TITLE
Create a Dart SDK beta channel

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#40687]
## Why does the Dart SDK need a beta channel?

- Aligns Dart more closely with Flutter's release process.
_Flutter already has a beta channel, that currently ships latest-hash-from-master Dart versions._
- Enables Dart to release not-quite-stable releases between stable releases (e.g. feature previews).
- Decouples stabilization from the dev channel.
_Previously, we had to freeze the dev channel for cherry-pick season, with a beta channel we will be able to keep dev releases flowing while we stabilize on/cherry-pick to beta._

## How does this affect Dart's versioning scheme?

Currently Dart dev channel versions look like this:
`2.7.0-dev.2.5` (or: `MAJOR.MINOR.PATCH-dev.PRERELEASE.PRERELEASE_PATCH`).

The change will happen in two phases and only affect versions on the dev and beta channels. Stable release, and builds from the master branch will remain the same.

### Phase 1
In the first phase, we will change the meaning of the pre-release numbers slightly. Regular dev release will look like before, but `PRERELEASE_PATCH` will always be `0` on the dev channel. Beta channel releases will always have `PRERELEASE_PATCH` version of `1` or higher. The first beta release based on a dev release will have `PRERELEASE_PATCH` set to `1` but all other parts of the version will be the same as the dev release. For each cherry-pick release of beta `PRERELEASE_PATCH` is incremented by `1`. At this point, beta releases will still have `-dev` in the version string to ensure that these versions sort semantically close to the dev release they are based on.

*Example:*
dev: `2.8.0-dev.15.0`
beta (branched off the version above): `2.8.0-dev.15.1`
beta with some cherry-picks: `2.8.0-dev.15.2`
stable (unchanged): `2.8.0`

To make it easier for users to see what channel they are on, tools should display a version string that includes the channel name (notice the beta):

```sh
$ dart  --version
Dart VM version: 2.8.0-dev.15.2 (beta) (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64"

$ pub --version
Pub 2.8.0-dev.15.2 (beta)
```

#### Alternative
Alternatively, we could add the channel to the version string directly like this:
`2.8.0-dev.15.2.beta` or `2.8.0-dev.15.2+beta`

That way, tools wouldn't need to be changed at all to display the channel but it may need to be considered a breaking change.

### Phase 2 (implemented 2))
The second phase is about removing the `dev` string from beta releases. This can only happen for the first dev release after stable release. There are two aspects, 1) remove the string `dev` after the `-`:

dev: `2.8.0-dev.15.0` -> `2.8.0-15.0`
beta: `2.8.0-dev.15.2` -> `2.8.0-15.2`

And 2), add a channel identifier at the end:
dev: `2.8.0-15.0` -> `2.8.0-15.0.dev`
beta: `2.8.0-15.2` -> `2.8.0-15.2.beta`

**Comment by jakemac53** [comment]
Have we considered calling beta preview instead or some other name that sorts after dev naturally? That seems less confusing.

**Comment by athomas** [comment]
@jakemac53 Yes, I have. It doesn't quite solve the problem, though. Let's say we use `-preview` instead of `-beta`, that means that all `-preview` versions will sort after all `-dev` versions. But the current plan is to also use the beta channel for mid-cycle tech preview versions, so using the numbers would sort them based on their branch point, which is more correct (cherry-picks aside), than if they are sorted to either end of the release cycle.

```
2.9.0-dev.13.0 (hypothetical branch point for the null safety tech preview 2.9.0-preview.13.1)
...
2.9.0-dev.25.0
2.9.0-preview.13.1 <-- In the wrong place, doesn't have features added after 2.9.0-dev.13.0
2.9.0-preview.25.1
2.9.0
```
Whereas with the cosmetic label at the end, it sorts better:
```
2.9.0-13.0.dev (hypothetical branch point for the null safety tech preview 2.9.0-13.1.beta)
2.9.0-13.1.beta
...
2.9.0-25.0.dev
2.9.0-25.1.beta
2.9.0
```

**Comment by jakemac53** [comment]
ah interesting, that makes sense 👍
