### ISSUE TITLE
CFE allows `await voidExpression`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40685]
The language specification allows `void`-typed expressions to occur only in an enumerated number of syntactical positions. Those do not include `await voidExpression`.

If you do:
```dart
void foo() {}
void main() {
  await foo();
}
```
it should be a compile-time error, but it is accepted by both the front-end and the analyzer (the latter with a hint about awaiting a non-future).

The spec says:
> ```latex
> The occurrence of an expression of type \VOID{} is a compile-time error unless it is permitted according to one of the following rules.
> ```
and then goes on to list the rules which do not include `await`. So, the code above should be a compile-time error.

**Comment by eernstg** [comment]
We still agree that it would be nice to make this an error, but we [decided](https://github.com/dart-lang/sdk/issues/33415#issuecomment-404253308) that it is not an error (the breakage was more substantial than anticipated). I'll update the language specification to be aligned with this, noting that a tool is very welcome to issue a hint.
