### ISSUE TITLE
Conditional breakpoints, watchpoints, setting variables in debugger

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#4068]
This probably affects both the VM and the Dart Editor. I'd like to be able to have conditional breakpoints, watchpoints, assign values to variables, and those sorts of things generally available in debuggers. Conditional breakpoints seems to require the ability to evaluate Dart code in the current context, and if the debugger can do that, I'd like to be able to do it interactively as well, being able to type in or highlight a snippet of Dart code, run it, and see the result.

**Comment by mhausner** [comment]
Much of this functionality is available in the Observatory debugger. If there are missing features in our IDE, new bugs should be filed.
