### ISSUE TITLE
Available Suggestions (wrongly) class instance getters/setters

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40689]
![image](https://user-images.githubusercontent.com/67586/74861073-9862bd00-52fe-11ea-89f8-460fd1abcefb.png)

**Comment by pq** [comment]
Related to https://github.com/dart-lang/sdk/issues/40626.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/136410

**Comment by scheglov** [comment]
@pq the issue of suggesting class fields / getters has been [fixed](https://dart-review.googlesource.com/c/sdk/+/136410). Now we don't suggest them at all :-)

If you want to add static getters, you probably can continue from here.

**Comment by pq** [comment]
Thank you!
