### ISSUE TITLE
[breaking change] Null safety changes

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#40686]
This is a meta-issue summarizing breaking changes made as part of realizing the [null safety feature](https://github.com/dart-lang/language/issues/110).

We are planning on landing these breaking changes fairly soon, and this in advance of the full null safety feature to ensure that we have sufficient time to uncover any unanticipated consequences.

## Language

- **type system**
  - #40633: Types objects will now be normalized 
  - #40633: Subtyping of type bounds in function types will switch from using structural subtyping to use mutual subtyping.
  - #40675: Type inference for local variables will not use promoted type variables.

## Core libraries

- **`dart:core`**
  - #40674: The [`RuneIterator` class](https://api.dart.dev/stable/2.7.1/dart-core/RuneIterator-class.html) has some members which return `null` in the state where the iterator has no "current" element; they will now return -1 or an empty string
  - #40678: The [`String.fromEnvironment`](https://api.dart.dev/stable/2.7.1/dart-core/String/String.fromEnvironment.html) and [`int.fromEnvironment`](https://api.dart.dev/stable/2.7.1/dart-core/int/int.fromEnvironment.html) const constructors will have a non-`null` `defaultValue` default value.
  - #40317: We will make the platform TypeError class not extend/implement the AssertionError class.
That will also make it not inherit the message getter.

- **`dart:async`**:
   - #40681: The [`runZoned`](https://api.dart.dev/stable/2.7.1/dart-async/runZoned.html) method will now *not* catch synchronously thrown errors even when given an error handler. 
  - #40676: The [`StreamSubscription.cancel`](https://api.dart.dev/stable/2.7.1/dart-async/StreamSubscription/cancel.html) method's return type is changed to `Future<void>`.
  - #40683: We disallow throwing nullable values entirely, and methods which accept thrown objects requires non-null arguments. This includes methods accepting async errors.
  - #40130: We will replace a null stack trace supplied by users with a default stack trace.

- **`dart:io`**:
  - #40483: Detached processes now throws StateError on meaningless getters
  - #40702: Destroyed/Upgraded Sockets now throw when accessing socket options
  - #40706: Provide epoch timestamps in the FileStat notFound object
  - #40709: HeaderValue parses invalid parameters as empty string instead of null

**Comment by franklinyow** [comment]
Announced :  https://groups.google.com/a/dartlang.org/g/announce/c/JwPWiC0jTiU

**Comment by jesserwright** [comment]
> Announced : https://groups.google.com/a/dartlang.org/g/announce/c/JwPWiC0jTiU

This link is broken (404).

**Comment by franklinyow** [comment]
Ok, let's try this:

https://groups.google.com/a/dartlang.org/d/msg/announce/JwPWiC0jTiU/diljrydDCQAJ

**Comment by franklinyow** [comment]
All issues landed

**Comment by mit-mit** [comment]
@franklinyow looks like some of these might be missing from https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md?
