### ISSUE TITLE
Internal test deobfuscation broken on nullable types

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40694]
See:

https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/1956/co19/LanguageFeatures/nnbd/generics_A01_t01

This:
```
Error: Expect.equals(expected: <A<Object?>>, actual: <A<dynamic>>) fails.
```

Becomes:
```
Error: Expect.equals(expected: <A<Object: <A<dynamic>>) fails.
```

fyi - @sigmundch (not a big deal if it's just internal, since we're printing both)

**Comment by nshahan** [comment]
This has already been resolved.
