### ISSUE TITLE
Allow version 2.10 to opt into NNBD

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40691]
Currently the analyzer considers the presence of any version number in the `package_config.json` file (or any `// @dart = ` version override) as an indication that code should be opted *out* of NNBD.  The logic behind this decision was that we did not know what version of Dart would be the first to support NNBD, so we wanted to play it safe by assuming that all known versions are pre-NNBD versions.

According to @munificent, it's been decided by the language team that version 2.10 will be the first version to support NNBD.  So the analyzer should be changed so that a version of 2.10 in the `package_config.json` file (or any `// @dart = ` version override) opts code *in* to NNBD.

**Comment by lrhn** [comment]
We will still ensure that opting in to NNBD *only* works when passing the `--enable-experiment=non-nullable` flag. No source-code-only approach should be able to permanently enable an experiment.

**Comment by leafpetersen** [comment]
@lrhn is there more context on this?  The behavior that we had proposed in the relevant section of the [language versioning spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md#experiment-flags) was that when you turn on an experiment flag, the current version of the SDK that you are on becomes the opt in language version.

Is this changing, and why?  And how will we experiment with package migrations in the new model?  That is, do I need to specify a min SDK constraint of 2.10 even though I'm on 2.8?  If so then we need some way of getting the various tools (e.g. pub) to work with that.

**Comment by stereotype441** [comment]
Note: @leafpetersen and I had some discussion about this today and it sounds like although it's been agreed that 2.10 will be the first version of Dart to support NNBD, it's not yet decided how we want to handle opting in/out under the experiment flag during the time before we reach version 2.10.  Expect a follow-up after we've had more discussion.

**Comment by scheglov** [comment]
I believe we changed our plan and decided that experiments can be enabled for any "current unreleased" version of Dart language, and 81bc6295824036c52825769394ae515dd162c245 implemented this for analyzer.
