### ISSUE TITLE
Analyzer support for ?[

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#40704]
Parser support for ?[ was added in cf4e044e07313e2c7f6d65202296c6adb1c5dc4d (see #40267), but introduced another token that the analyzer currently doesn't save.

I've skipped the following tests in analyzer:
* front_end/parser_testcases/nnbd/issue_40267_case_02.dart
* front_end/parser_testcases/nnbd/issue_40267_case_05.dart

Note: It was reverted. I'll assign this to myself until the fix lands.

**Comment by jensjoha** [comment]
Change landed again as 3660b9ecc70e9e5ec3b5fce24485dff0687fb099 --- @bwilkerson I took the liberty to assign you. Hope that's okay.

**Comment by bwilkerson** [comment]
The AST and summary support have landed in https://dart-review.googlesource.com/c/sdk/+/137252. I'm going to hand the issue off to @scheglov for the remainder of the work.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/138563

**Comment by scheglov** [comment]
The change landed, but it is not clear to me if we should support both `?.[` and `?[`.

**Comment by jensjoha** [comment]
For what its worth, my understanding is that we should stop supporting `?.[`, but that - considering we have tests and whatnot - that should be cleaned up first.

**Comment by jensjoha** [comment]
fyi, https://dart-review.googlesource.com/c/sdk/+/138927 also added

* front_end/parser_testcases/nnbd/issue_40267_lookup_plus_plus.dart
* front_end/parser_testcases/nnbd/issue_40267_lookup_plus.dart
* front_end/parser_testcases/nnbd/issue_40267_plus_plus_lookup.dart

to the skip list.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/139483

**Comment by jensjoha** [comment]
pkg/analyzer/test/src/summary2/ast_text_printer_integration_test.dart still has ignored entries because of this. If I disable it (i.e. don't ignore them) they still fail with something like this:

```
00:02 +2045 -1: Parse and print AST | front_end/parser_testcases/nnbd/issue_40267_plus_plus_lookup.dart [E]
                                                                                   
  Bad state: |x| must be followed by |?|, got |[|     
```

so I'm guessing you accidentally closed the wrong issue.

**Comment by scheglov** [comment]
Sorry, I was confused.
I looked at this issue as if it is for tracking `?[` resolution support, which we did in analyzer.
But I missed the fact that there are also necessary `AstTextPrinter` changes.
Thank you for pointing at this.

https://dart-review.googlesource.com/c/sdk/+/139743 will fix `AstTextPrinter`.
