### ISSUE TITLE
Weird caching behavior when making a field `late final`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40701]
At 2.8.0-edge 3dc8cb0d2b0b7a86812c782390e6a62cb0714a84

* Add final to an already late field.
* notice analyzer error
* change the file in some tangible way – rename function param, add function, etc
* notice error goes away

Caching?

![analyzer_weird](https://user-images.githubusercontent.com/17034/74889381-b8fa3980-5335-11ea-876e-96e28b9b0b72.gif)

**Comment by kevmoo** [comment]
I had to delete the `~/.dartServer` cache to fix it!

Restarting the server, restarting intellij – didn't help

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Yes, apparently `late` is omitted from the unlinked API signature of a file.
I will have a fix CL shortly.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/136529
