### ISSUE TITLE
[Breaking Change Request] Provide epoch timestamps in the FileStat notFound object

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#40706]
# Intended change

The dummy object returned if `FileStat.stat()` and `FileStat.statSync()` fail now contains Unix epoch timestamps instead of `null` for the `accessed`, `changed`, and `modified` getters.

# Rationale

These timestamps are always non-null if the API succeeds and the timestamps are meaningless when the API fails and returns the `FileSystemEntityType.notFound` type. This change makes the timestamps always non-null, which avoids all legitimate accesses needing a needless null check when Dart becomes null safe. This change is consistent with the `mode` and `size` getters that are initialized to non-null dummy values when the API fail.

# Expected impact

Callers are supposed to handle if files doesn't exist or if the API fails for other reasons. The timestamp getters in question are meaningless if the API fails. Code that would break would be looking at these timestamps and acting differently if they are null, which is not the right way to use the API, as it should instead use the `type` getter to check for the `FileSystemEntityType.notFound` type. For that reason, reasonable code wouldn't break on this change and no breakage in particular is anticipated.

# Steps for mitigation

Code that breaks should be updated to check for the `FileSystemEntityType.notFound` type.
# Implementation

A proposed implementation of this breaking change: https://dart-review.googlesource.com/c/sdk/+/136585

cc @franklinyow @mit-mit @lrhn @athomas

**Comment by sortie** [comment]
A case was identified in `package:watcher` where it [returns the modified time](https://github.com/dart-lang/watcher/blob/master/lib/src/stat.dart#L31) rather than checking for `notFound` and relied on non-existent files having a `null` modified time. It affects a single G3 test. The fix to check for `notFound` is trivial and backwards compatible.

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @dgrove @vsmenon for review and approval.

**Comment by Hixie** [comment]
fine by me

**Comment by matanlurey** [comment]
No input

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by sortie** [comment]
The updated package:watcher has rolled into G3 and the SDK DEPS has been updated. I'm still waiting on the SDK DEPS update to roll into G3, and for it to roll into Flutter. I'll try again tomorrow.

**Comment by sortie** [comment]
The updated SDK DEPS has rolled into G3. I'm doing another global presubmit to confirm this change is now safe to land.

**Comment by sortie** [comment]
The G3 global presubmit was green. I've now landed the breaking change in the Dart SDK. I've filed an [issue](https://github.com/dart-lang/co19/issues/573) to update the relevant co19 tests and approved the relevant failures. No issues are expected for when this change rolls into G3. Rolling into Flutter remains to be seen although there are no known issues at this time.
