### ISSUE TITLE
DDC needs to implement the changes of lang/#807

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#40720]
There are new test failures on [[VM/nnbd] Implement pre-nnbd language changes (see lang/#807).](https://dart-review.googlesource.com/c/sdk/+/135787).

The tests
```
corelib/type_tostring_test RuntimeError (expected Pass)
corelib_2/type_tostring_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-checked-linux-release-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
```
These tests have been updated (in CL above) to pass on the VM when implementing the changes of lang/#807.
Until DDC implements the same changes, these 2 updated tests will fail.

**Comment by sigmundch** [comment]
This was fixed by ab30452
