### ISSUE TITLE
[Analyzer]Add Support for Auto Import + Smart Completion for extension methods.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40731]
Since I'm used to all my methods getting Smart Completed and auto imported if they are in the same project, however we don't get this option with extension methods.

**Comment by bwilkerson** [comment]
Thanks for the report. We've recently become aware of the issue and are working to support that case.

@pq

**Comment by srawlins** [comment]
Looks like a duplicate of #38894

**Comment by ThinkDigitalSoftware** [comment]
@srawlins ah, yes it is
