### ISSUE TITLE
Analyzer doesn't seem to parse language versions with more than one trailing digit correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40734]
If I write `// @dart=2.10` in a file, the analyzer produces the following hint:

```
  hint • The Dart language version override comment can't be followed by any non-whitespace characters • test4.dart:3:1 • invalid_language_version_override
```

Changing the `2.10` to `2.8` seems to make the hint go away, so it seems like there may be a parsing issue here?

cc @stereotype441 @scheglov

**Comment by stereotype441** [comment]
Related: https://github.com/dart-lang/sdk/issues/40691

**Comment by scheglov** [comment]
Probably an issue in hint reporting, https://dart-review.googlesource.com/c/sdk/+/125522.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/136804
