### ISSUE TITLE
unused_catch_clause is incorrect warning

### ISSUE THREAD

**Issue by safield** [dart-lang/sdk#40742]
I have received the analyzer warning...

The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/framework/server.dart:65:38 •
          unused_catch_clause

This is quite obviously an incorrect warning. I might want to catch a certain exception to do some other logic, like return an error enum from my method, even though I didn't do anything with the caught exception.

Catch blocks are for executing certain logic when a certain exception is thrown, regardless if anything is done with the exception message.

**Comment by bwilkerson** [comment]
That's true, but in Dart you don't need the `catch` clause in order to do so. For example, the following is valid:
```
try {
  // Some code that might throw an ArgumentError.
} on ArgumentError {
  // Do something about the exception.
}
```
The only purpose of the `catch` clause is to allow you to capture the exception and possibly the stack trace associated with the exception.
