### ISSUE TITLE
[Analyzer] Convert to expression body can lead to unwanted results

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40743]
The following suggestion to convert this expression to a function body changes the function from being assigned when the line is run, to being executed when the line is run. I understand that the fat arrow notation also means return, which means the function gets evaluated, but in my case, this causes the function to get run too early and was a beast to track down.
[Link to DartPad example](https://dartpad.dartlang.org/ec30fcfcf71e5812b3aa6b58e88e2e67)

<img width="716" alt="Screen Shot 2020-02-22 at 2 40 30 PM" src="https://user-images.githubusercontent.com/23037821/75100367-86dd1780-5581-11ea-98a3-f2e43cf7f9e6.png">

**Comment by natebosch** [comment]
> changes the function from being assigned when the line is run, to being executed when the line is run

This is not expected - can you clarify?

In the linked dartpad the only difference is whether a value is returned, there is no difference on timing for when a function is executed.

**Comment by ThinkDigitalSoftware** [comment]
Sorry, I'm my case, I believe that the function was being evaluated in order to set the variable when the variable was run across, not when the function was called. I was setting a variable equal to a function to be ready when it was called, but my setting that variable, the function was called to evaluate the variable, well before it was actually  used. It was a void function, so no real evaluation was necessary, but it still made a call to my bloc early than I planned. Does that make sense?

**Comment by natebosch** [comment]
There must have been some other difference in the code. Using `=>` would not cause the expression to be evaluated at the time the function is assigned to a variable.

**Comment by ThinkDigitalSoftware** [comment]
Alright, Ill double check what I submitted, thanks!

**Comment by srawlins** [comment]
Please re-open if you encounter this again.
