### ISSUE TITLE
Investigate if we can expand fast case for running async code inside custom error zone without overriding callback binding behavior

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#40752]
Each invocation of an async/async* function will call `_asyncThenWrapperHelper` to bind the inner `async_op` closure using the current zone.

There's a fast case if we're doing this inside the `Zone.root`, see [async_patch.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/async_patch.dart#L74)

```dart
Function _asyncThenWrapperHelper(continuation) {
  // Any function that is used as an asynchronous callback must be registered
  // in the current Zone. Normally, this is done by the future when a
  // callback is registered (for example with `.then` or `.catchError`). In our
  // case we want to reuse the same callback multiple times and therefore avoid
  // the multiple registrations. For our internal futures (`_Future`) we can
  // use the shortcut-version of `.then`, and skip the registration. However,
  // that means that the continuation must be registered by us.
  //
  // Furthermore, we know that the root-zone doesn't actually do anything and
  // we can therefore skip the registration call for it.
  //
  // Note, that the continuation accepts up to three arguments. If the current
  // zone is the root zone, we don't wrap the continuation, and a bad
  // `Future` implementation could potentially invoke the callback with the
  // wrong number of arguments.
  if (Zone.current == Zone.root) return continuation;
  return Zone.current.registerUnaryCallback(continuation);
}
```

Very often users run code inside a custom zone where this condition doesn't hold, so we'll execute slower code. Though custom zones very rarely overriding callback binding functionality, most of the time the custom zones are only used for catching errors.

We should investigate whether we can extend the fast case to custom zones which don't change callback binding behavior.

Since this intersects with the faster async work, could you take a look at this, @cskau-g ?

**Comment by cskau-g** [comment]
622d54c addressed the particular changes possible in `_asyncThenWrapperHelper` and `_asyncErrorWrapperHelper`.
The result was a 2-5% runtime reduction for the particular custom-zone-with-no-register-override cases.

https://github.com/dart-lang/sdk/issues/44936 tracks the follow-up work to investigate further optimisations.
