### ISSUE TITLE
Failures on [nnbd] Re-add null checks in NNBD SDK file_impl.dart and directory_impl.dart

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40757]
There are new test failures on [[nnbd] Re-add null checks in NNBD SDK file_impl.dart and directory_impl.dart](https://dart-review.googlesource.com/c/sdk/+/135540).

The tests
```
corelib/iterable_followed_by_test RuntimeError (expected Pass)
corelib/queue_test RuntimeError (expected Pass)
lib/typed_data/typed_data_list_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-strong-linux-release-chrome
```

**Comment by liamappelbe** [comment]
My CL seems to be causing these tests to fail, but I've just re-added null checks that used to be there. Maybe they're testing invalid behavior? I've pre-approved the failures

**Comment by sigmundch** [comment]
Thanks @liamappelbe - it appears that you were hitting an infrastructure issue, were failures from a previous commit were being misattributed to your change (same issue as https://github.com/dart-lang/dart_ci/issues/74).

Now that the result feed has caught up, I can verify that they were first introduced on https://github.com/dart-lang/sdk/commit/b5a08c916ce542232d4f7b0446d3b485426716d5
