### ISSUE TITLE
Uses of v dominated by AssertAssignable(v) should point to AssertAssignable

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#40765]
`AssertAssignable` influences reaching type of the value - which means we must prevent hoisting of instructions which use affected value past `AssertAssignable`. Similar to how we insert redefinitions after branches which narrow type of the value. 

Here is a reproduction for the problem (in AOT mode):

```dart
class Something {
  final int x;
  Something({this.x});
}

abstract class Base {
  Something get x;
}

class Child1 extends Base {
  final Something x;
  Child1({this.x});
}

class Child2 extends Base {
  final int y;
  final Something x;
  Child2({this.x, this.y});
}

@pragma('vm:never-inline')
int foo(int k, Base x) {
  var y = 0;
  for (var i = 0; i < k; i++) {
    x as Child1;
    y = x.x.x; // Will be hoisted out as x.{Child1::x}.{Something::x}
               // and at foo(0, Child2(..., y: 24)) will end up executing as
               // x.{Child1::x} -> will load Child2::y (42) and then segfault.
  }
  return y;
}

void main() {
  print(foo(1, Child1(x: Something(x: 1))));
  print(foo(1, Child1(x: Something(x: 2))));
  print(foo(0, Child2(x: Something(x: 42), y: 24)));
}
```

**Comment by mraleph** [comment]
Assigning to @askeksa-google because he will need to solve the same problem for `AssertBoolean` as part of his boolean optimisation change.

/cc @mkustermann @alexmarkov

**Comment by rmacnak-google** [comment]
Compare aae0f7997de4d06df22766a089bc2eb18cb24e2d, which indroduced a similar dependency for bounds checks.

**Comment by mraleph** [comment]
@rmacnak-google yeah, I actually was under impression that we handled all of the similar instructions after we did it to bounds checks, but apparently we did not :( 

there is a subtle difference though - in aae0f79 we try to do it during construction. I think instead (to be on the safe side) we should be doing it at a separate pass by dominance. Similar to how we do it for redefinitions right before the LICM.

**Comment by mkustermann** [comment]
Our flow graph building code - generating stack-based unoptimized IR - does not introduce those dependencies via StoreLocal/LoadLocal (sometimes maybe also not possible due to inability to store into expression variables).
=> That means the dependencies will not be there after SSA construction. This is a known issue.

> we should be doing it at a separate pass by dominance

agree

**Comment by alexmarkov** [comment]
We only add `AssertAssignable` during flow graph construction. It shouldn't be too hard to use result of `AssertAssignable` instead of dropping it and using the original value (bytecode flow graph builder does that), so I don't really understand why we need a separate pass for this. The only complication might be related to parameters - they are sometimes copied from raw parameter variables to real parameter variables before their type is checked. I think it make sense to fix the problem with parameters anyway, in order to be able to use static type for parameter variables (including captured variables).

**Comment by mraleph** [comment]
@alexmarkov 

> It shouldn't be too hard to use result of AssertAssignable instead of dropping it and using the original value (bytecode flow graph builder does that), so I don't really understand why we need a separate pass for this.

That does not help. You can see from the reproduction that there is no syntactical connection between `x as Foo` and subsequent use of `x`. This can be even more hidden, e.g.  I can write:

```
o.f as Child1;
y = o.f.x.x;
```

here you need to have few optimizations passes to figure out that `o.f` is the same definition. 

That is why you need a separate pass.

**Comment by alexmarkov** [comment]
@mraleph Thank you for the explanation. We can add this logic into type propagation pass as it inserts redefinitions already - the case you mentioned is not really different from using a value after `is` test (handled in `FlowGraphTypePropagator::VisitBranch`) or inferring non-nullability of receiver after instance call (`FlowGraphTypePropagator::CheckNonNullSelector`).

`FlowGraphTypePropagator::VisitAssertAssignable` could replace dominated uses of operand with `AssertAssignable`.

We might also want to revise other uses of `FlowGraphTypePropagator::SetTypeOf` and check if we need to rename dominated uses of a value when assigning a more accurate type.

**Comment by mraleph** [comment]
>  We might also want to revise other uses of FlowGraphTypePropagator::SetTypeOf and check if we need to rename dominated uses of a value when assigning a more accurate type.

That is an alternative implementation that I have considered. We can change `SetTypeOf` to take another parameter (redefinition)  and then update `Value`s as we assign reaching types to them.
