### ISSUE TITLE
NNBD: Instantiate-to-bounds works in different ways in runtime and analyzer 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40764]
Dart VM version: 2.8.0-edge.b0b06bff31b167d13ecd9217182ec7e7a8f4f937 (Tue Feb 25 04:39:10 2020 +0000) on "linux_x64"

The source code below throws compile error with analyzer and passes with dart when run in nnbd mode.

Without nnbd, it passes both with  analyzer and dart.

``` dart
class A<X extends A<X>> {}
class C<T> {}

main() {
  new C<A>();
}
```
Sample output is:

> $ dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error • 'A<dynamic>' doesn't extend 'A<A<dynamic>>'. • test.dart:5:9 • type_argument_not_matching_bounds
> 1 error found.
> 
> $ dart --enable-experiment=non-nullable test.dart
> 
> $ dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!
> 
> $ dart test.dart
> 

If I change type parameter in the first line to the nullable one, it passes both with analyzer and dart:
``` dart
class A<X extends A<X>?> {}
class C<T> {}

main() {
  new C<A>();
}
```

I am not quite sure if this is a bug in the analyzer or runtime, but anyway analizer and dart should work similarly here.

**Comment by mraleph** [comment]
@stefantsov is CFE wrong or is analyzer wrong?

**Comment by stefantsov** [comment]
To me, this code doesn't look like a compile-time error.  It actually looks like one of the primary use cases for the instantiate-to-bounds feature.

/cc @eernstg

**Comment by eernstg** [comment]
Agreed, instantiate to bounds should yield a correctly super-bounded type as the desugaring of the raw type `A` (in any location where it isn't equipped with type arguments via type inference, e.g., except `A<Never> a = A();`).

**Comment by eernstg** [comment]
Here is a smaller example causing the same response from the analyzer:

```dart
class A<X extends A<X>> {}
A get g => throw 0;
```

I suspect that this is caused by a missing nnbd update: If the check for whether a given type is super-bounded replaces each occurrence of a top type by `Null` (where it should use `Never`), we get exactly the test where a bound with `?` will be a supertype as required, but the plain `A<X>` won't:

`A<dynamic>` is clearly not regular-bounded; so we replace covariant top by bottom, get `A<Never>`, and check: `Never <: A<Never>` is true, so that's regular-bounded, so `A<dynamic>` is correctly super-bounded. But if we check with `Null` then we need `Null <: A<Null>`, and that's not true.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/137280

**Comment by scheglov** [comment]
This CL adds the test from [the comment](https://github.com/dart-lang/sdk/issues/40764#issuecomment-590857234), but it fails for CFE :-(

```
/====================================================================================================================\
| cfe-strong-linux:language/instantiate_to_bound/issue40764_test is new and failed (CompileTimeError, expected Pass) |
\====================================================================================================================/

--- Command "fasta" (took 737ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_language_instantiate_to_bound_issue40764_test/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong --packages=./.packages ./tests/language/instantiate_to_bound/issue40764_test.dart )

exit code:
1

stdout:
tests/language/instantiate_to_bound/issue40764_test.dart:3:9: Error: Type argument 'A<dynamic>' doesn't conform to the bound 'A<X>' of the type variable 'X' on 'A' in the return type.
 - 'A' is from 'tests/language/instantiate_to_bound/issue40764_test.dart'.
Try changing type arguments so that they conform to the bounds.
A get g => throw 0;
        ^
tests/language/instantiate_to_bound/issue40764_test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends A<X>> {}
        ^

--- Re-run this test:
python tools/test.py -n cfe-strong-linux language/instantiate_to_bound/issue40764_test
```
