### ISSUE TITLE
Severity of a warning is coming through as an error severity...

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#40768]
The severity of `StaticWarningCode.MISSING_ENUM_CONSTANT_IN_SWITCH` should be a warning, but is an error when it gets through the analysis server.

Debugging, the `test_middle()` test in `test/src/diagnostics/missing_enum_constant_in_switch_test.dart` shows that the analyzer itself has the correct severity.  I am not seeing where/ why it would be reported differently in the DAS.

`{"event":"analysis.errors","params":{"file":"/tmp/dartdevYGMRJV/lib/main.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/tmp/dartdevYGMRJV/lib/main.dart","offset":40,"length":10,"startLine":3,"startColumn":5},"message":"Missing case clause for 'e2'.","correction":"Try adding a case clause for the missing constant, or adding a default clause.","code":"missing_enum_constant_in_switch","hasFix":false}]}}`

**Comment by jwren** [comment]
@stereotype441 @bwilkerson @pq

**Comment by devoncarew** [comment]
@jwren - I think this is WAI. The code names have warning in them as they were defined pre-dart 2. The issues severities returned _are_ error level severities - that's correct for dart 2.

In strong mode, it's hard to create analysis errors that are warnings. I have a CL that does it via a lint (promoted to a warning).

https://dart-review.googlesource.com/c/sdk/+/141472
