### ISSUE TITLE
VM Regression rss is null for the first Heap sample.

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#40766]
The rss value of the first heap sample received from the VM is null.  Subsequent samples received from the VM the rss is a valid integer value.  This is a recent regression.

One of our memory tests devtools/packages/devtools_testing/lib/memory_service_test.dart started failing:

`      expect(sample.rss, greaterThan(0));`

because sample.rss isnull.

Added this workaround but this seems like a problem.

```
    // TODO(terry): Bug VM first HeapSample returns a null for an rss value after first
    //              sample rss subsequent rss values has a valid integer value.  This is
    //              a VM regression see issue 
    //              When fixed remove the test for rss != null and the firstSample global.
    if (sample.rss != null && firstSample) {
      expect(sample.rss, greaterThan(0));
      expect(sample.rss, greaterThan(sample.capacity));
      firstSample = false;
    }
```

**Comment by bkonyi** [comment]
Ryan might have a better idea of what's going on here.

However, it looks like this RSS property is populated by grabbing the `_currentRSS` property from the `VM` object. This is a private field that shouldn't be relied upon outside of Observatory so _technically_ this isn't a regression.
